# $FreeBSD$

SUBDIR =
SUBDIR+= contributing
SUBDIR+= cvs-freebsd
SUBDIR+= hubs
SUBDIR+= mailing-list-faq
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
