# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: r51426

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=  about.xml
#DOCS+=	bylaws.xml
#DOCS+=	clusteradm.xml
#DOCS+=	code-of-conduct.xml
#DOCS+=	core-vote.xml
#DOCS+= data.xml
DOCS+=	developer.xml
#DOCS+=	doceng.xml
#DOCS+=	expire-bits.xml
#DOCS+=	hats.xml
#DOCS+=	i18n.xml
DOCS+=  internal.xml
DOCS+=  machines.xml
#DOCS+=	members.xml
DOCS+=  mirror.xml
#DOCS+=	new-account.xml
#DOCS+=	policies.xml
#DOCS+=	releng.xml
#DOCS+=  resources.xml
#DOCS+=	statistic.xml
#DOCS+=  software-license.xml
#DOCS+=	working-with-hats.xml

INDEXLINK=	internal.html

#DATA+=	ssh-keys.asc

.include "${DOC_PREFIX}/share/mk/web.site.mk"
