#
# $FreeBSD$
#
# Author: Victoria Chan, Hiten Pandya
# Article: Java and Jakarta Tomcat on FreeBSD

MAINTAINER=hmp@FreeBSD.org vkchan@kendryl.net

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
