#
# FreeBSD Documentation Project
# $FreeBSD$
#
# Makefile for "Java and FreeBSD First Steps"
# Author: Victoria Chan, Hiten Pandya

MAINTAINER=vkchan@kendryl.net hiten@uk.FreeBSD.org

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

WITH_DOCFORMAT_NAVI_LINK?=YES

# SGML content
SRCS=  article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
