#
# $FreeBSD$
#
# Author: Victoria Chan, Hiten Pandya
# Article: Java and Jakarta Tomcat on FreeBSD

MAINTAINER=vkchan@kendryl.net hiten@uk.FreeBSD.org

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
