# $Id: Makefile,v 1.3 1999-02-14 10:58:22 wosch Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=	photos.sgml	
DOCS+=	internal.sgml	
DOCS+= 	about.sgml
DOCS+= 	machines.sgml
DOCS+= 	mirror.sgml
DOCS+=	statistic.sgml

INDEXLINK=	internal.html

DATA+=	README.mirror

.include "../web.mk"
