---
description: 'Новичок в FreeBSD обнаружит, что первая часть этой книги проведёт его через процесс установки FreeBSD и мягко познакомит с концепциями и соглашениями, лежащими в основе UNIX'
next: books/handbook/parti
params:
  path: /books/handbook/preface/
prev: books/handbook
showBookMenu: 'true'
tags: ["preface", "audience", "organization", "conventions", "acknowledgments"]
title: Предисловие
weight: 1
---

[preface]
[[book-preface]]
= Предисловие
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/preface/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[preface-audience]]
== Целевая аудитория

Новичок в FreeBSD обнаружит, что первая часть этой книги проведёт пользователя через процесс установки FreeBSD и мягко познакомит с концепциями и соглашениями, лежащими в основе UNIX(R). Для работы с этой частью требуется лишь желание исследовать и способность усваивать новые концепции по мере их появления.

После прохождения этого этапа вторая, значительно более обширная часть Руководства представляет собой всеобъемлющий справочник по различным темам, представляющим интерес для администраторов систем FreeBSD. Некоторые из этих глав могут рекомендовать предварительное ознакомление с другими материалами, что отмечается в кратком обзоре в начале каждой главы.

Для получения дополнительных источников информации см. crossref:bibliography[bibliography,Библиография].

[[preface-changes-from4]]
== Четвертое издание

Текущая версия Руководства представляет собой совокупный результат рабочей группы, которая занимается проверкой и обновлением всего содержимого Руководства. Ниже приведены основные изменения по сравнению с четвёртым изданием Руководства.

* Справочник был преобразован из link:https://docbook.org/[Docbook] в link:https://gohugo.io/[Hugo] и link:https://asciidoctor.org/[AsciiDoctor]
* link:https://docs.FreeBSD.org[Портал документации FreeBSD] был создан.
* Глава crossref:introduction[introduction, Введение] была обновлена для улучшения описания истории FreeBSD и исправления незначительных опечаток.
* Глава crossref:bsdinstall[bsdinstall, Установка] была обновлена с улучшенной аннотацией, последними изменениями в установщике, обновленными изображениями, добавленным альтернативным текстом для изображений и удалением упоминаний конкретных версий.
* Глава crossref:basics[basics, Основы] содержит обновлённые таблицы, выводы команд и структуру каталогов в соответствии с man:hier.
* Глава crossref:ports[ports, Порты] была обновлена и теперь упрощает поиск пакетов, обновляет примеры программного обеспечения (Nginx заменяет Apache), улучшает процесс начальной загрузки man:pkg[8] и добавляет новые инструкции по настройке и управлению пакетами, включая их блокировку и разблокировку.
* Глава crossref:x11[x11, X11] была обновлена, чтобы отразить текущее состояние графики в FreeBSD: удалены устаревшие ссылки на старые драйверы Intel, конфигурации и compiz, а инструкции по настройке окружений рабочего стола (таких как KDE Plasma и GNOME) перенесены в главу «Окружения рабочего стола», так как эти окружения теперь поддерживают не только X11, но и Wayland.
* Добавлена глава crossref:wayland[wayland,Wayland] с информацией об установке и настройке Wayland в FreeBSD.
* Глава crossref:network[network, Сеть] была создана для описания базовой настройки проводных и беспроводных сетей, включая имя хоста, DNS и устранение неполадок. Разделы о проводных сетях, беспроводных сетях и IPv6 были перемещены и обновлены с улучшенными выводами команд, использованием sysrc и улучшенным синтаксисом AsciiDoc.
* Глава crossref:desktop[desktop,Рабочий стол] была обновлена: добавлены улучшенные инструкции по установке KDE Plasma, GNOME, XFCE, MATE, Cinnamon и LXQT, расширены варианты браузеров, добавлен новый раздел о инструментах разработки, а также обновлены разделы о офисных приложениях, программах для просмотра документов и финансовых инструментах.
* Глава crossref:multimedia[multimedia,Мультимедиа] была переработана с обновлениями в разделе о звуке, новыми таблицами для микшеров звука, аудиоплееров и видеоплееров, рекомендациями по автоматическому переключению на наушники, новым разделом о конференциях и встречах, а также пересмотренным разделом о сканерах изображений.
* Раздел crossref:linuxemu[linuxemu, Linuxemu] был улучшен за счет обновленных инструкций по настройке базовой системы Debian/Ubuntu с использованием debootstrap.
* Глава crossref:config[config, Config] была переименована для точности, с обновлениями в разделах управления службами, cron и periodic, syslog, управления питанием и подкачки. Добавлена новая запись о конфигурационных файлах, а устаревший раздел по настройке удалён.
* Глава crossref:security[security, Безопасность] была обновлена с улучшениями для VPN через IPSec, защиты учетных записей, хешей паролей, sudo/doas и OpenSSH/OpenSSL. Добавлены новые разделы, посвященные IDS, уровням безопасности, флагам файлов, Capsicum, ACL NFSv4 и ограничениям ресурсов.
* Глава crossref:jails[jails, Клетки] была обновлена и теперь включает подробности о типах клеток (толстых, тонких, VNET клеток и клеток Linux), настройке хостовой системы, вариантах сетевого взаимодействия, файле конфигурации клетки, процедурах настройки, методах обновления, ограничениях ресурсов, а также различных менеджерах клеток и решениях для контейнеров.
* Глава crossref:mail[mail,Почта] была обновлена и теперь включает информацию о DMA, обновлениях Sendmail, инструкции по замене DMA и Sendmail на другие MTA, а также удаление разделов Dialup и Fetchmail с последующей реорганизацией главы.
* crossref:bibliography[bibliography,Библиография] была значительно обновлена.

[[preface-changes-from3]]
== Третье издание

Текущая онлайн-версия Handbook представляет собой результат совместных усилий сотен участников за последние 10 лет. Ниже перечислены некоторые значительные изменения, внесённые с момента публикации третьего издания в двух томах в 2004 году:

* В документацию FreeBSD добавлен раздел crossref:wine[wine,WINE] с информацией о запуске приложений Windows(R) в FreeBSD.
* В документацию FreeBSD добавлен раздел crossref:dtrace[dtrace,DTrace] с информацией о мощном инструменте анализа производительности DTrace.
* В файле crossref:filesystems[filesystems,Другие файловые системы] добавлена информация о не родных файловых системах в FreeBSD, таких как ZFS от Sun(TM).
* В документе crossref:audit[audit,Аудит событий безопасности] добавлен раздел, посвящённый новым возможностям аудита в FreeBSD, с объяснением их использования.
* В документе FreeBSD добавлен раздел crossref:virtualization[виртуализация,Виртуализация] с информацией об установке FreeBSD на программное обеспечение для виртуализации.
* Добавлен раздел crossref:bsdinstall[bsdinstall,Установка FreeBSD], посвящённый установке FreeBSD с помощью новой утилиты bsdinstall.

[[preface-changes-from2]]
== Второе издание (2004)

Третье издание стало результатом более чем двухлетней работы преданных участников проекта FreeBSD Documentation Project. Печатное издание увеличилось до такого объёма, что потребовалось выпустить его в виде двух отдельных томов. Ниже приведены основные изменения в этом новом издании:

* crossref:config[config-tuning,Настройка и оптимизация системы] была дополнена новой информацией об управлении питанием и ресурсами ACPI, системной утилите `cron`, а также дополнительными параметрами настройки ядра.
* crossref:security[security,Безопасность] дополнена новой информацией о виртуальных частных сетях (VPN), списках контроля доступа (ACL) файловых систем и рекомендациях по безопасности.
* crossref:mac[mac,Принудительный контроль доступа] — это новая глава в данном издании. В ней объясняется, что такое MAC и как этот механизм может быть использован для защиты системы FreeBSD.
* crossref:disks[disks,Хранение данных] была дополнена новой информацией о USB-накопителях, снимках файловых систем, квотах файловых систем, файловых и сетевых файловых системах, а также о зашифрованных разделах диска.
* В раздел crossref:ppp-and-slip[ppp-and-slip,PPP] добавлен подраздел по устранению неполадок.
* crossref:mail[mail,Электронная почта] была дополнена новой информацией об использовании альтернативных транспортных агентов, SMTP-аутентификации, UUCP, fetchmail, procmail и других расширенных темах.
* crossref:network-servers[network-servers,Сетевые серверы] полностью обновлена в этом издании. Эта глава включает информацию о настройке Apache HTTP Server, ftpd, а также о настройке сервера для клиентов Microsoft(R) Windows(R) с помощью Samba. Некоторые разделы из crossref:advanced-networking[advanced-networking,Расширенные сетевые технологии] были перемещены сюда для улучшения изложения.
* crossref:advanced-networking[advanced-networking,Расширенные сетевые технологии] дополнены новой информацией об использовании устройств Bluetooth(R) с FreeBSD, настройке беспроводных сетей и работе с сетями Asynchronous Transfer Mode (ATM).
* В книгу добавлен глоссарий, который служит центральным местом для определений технических терминов, используемых в тексте.
* В книгу внесен ряд визуальных улучшений в таблицы и иллюстрации.

[[preface-changes]]
== Первое издание (2001)

Второе издание стало результатом более двух лет работы преданных членов Проекта документации FreeBSD. Основные изменения в этом издании включали:

* Добавлен полный указатель.
* Все ASCII-рисунки заменены графическими диаграммами.
* В начало каждой главы добавлено стандартное краткое содержание, которое даёт общее представление о том, какую информацию содержит глава и какие знания ожидаются от читателя.
* Содержание было логически реорганизовано в три части: «Начало работы», «Администрирование системы» и «Приложения».
* Раздел crossref:basics[basics,Основы FreeBSD] был расширен, и теперь включает дополнительную информацию о процессах, демонах и сигналах.
* Раздел crossref:ports[ports,Установка приложений: Пакеты и порты] был дополнен дополнительной информацией об управлении бинарными пакетами.
* Раздел crossref:x11[x11,Система X Window] был полностью переписан с акцентом на использование современных технологий для рабочих столов, таких как KDE и GNOME на XFree86(TM) 4.X.
* Раздел crossref:boot[boot,Процесс загрузки FreeBSD] был расширен.
* Раздел crossref:disks[disks,Хранение данных] был написан на основе двух глав: «Диски» и «Резервное копирование», которые ранее были отдельными. Мы считаем, что объединение этих тем в одну главу облегчает их понимание. Также добавлен раздел о RAID (как аппаратном, так и программном).
* Раздел crossref:serialcomms[serialcomms,Последовательные коммуникации] был полностью переработан и обновлен для FreeBSD 4.X/5.X.
* Раздел crossref:ppp-and-slip[ppp-and-slip,PPP] был значительно обновлен.
* В новую секцию crossref:advanced-networking[advanced-networking,Сложные вопросы работы в сети] добавлено множество новых разделов.
* Раздел crossref:mail[mail,Электронная почта] был дополнен дополнительной информацией о настройке sendmail.
* Раздел crossref:linuxemu[linuxemu,Совместимость с бинарными файлами Linux®] был расширен и включает информацию об установке Oracle(R) и SAP(R) R/3(R).
* В этом втором издании рассматриваются следующие новые темы:

** crossref:config[config-tuning,Настройка и конфигурирование].
** crossref:multimedia[multimedia,Мультимедиа].

[[preface-overview]]
== Организация книги

Эта книга разделена на пять логически обособленных частей. Первая часть, _Начало работы_, посвящена установке и основам использования FreeBSD. Предполагается, что читатель будет изучать эти главы последовательно, возможно, пропуская главы на знакомые темы. Вторая часть, _Повседневные задачи_, охватывает часто используемые возможности FreeBSD. Эту часть, как и все последующие, можно читать в любом порядке. Каждая глава начинается с краткого описания, в котором указано, что рассматривается в главе и какие знания уже должны быть у читателя. Это позволяет бегло просматривать содержание и находить интересующие главы. Третья часть, _Администрирование системы_, посвящена вопросам администрирования. Четвёртая часть, _Сетевое взаимодействие_, охватывает темы, связанные с сетями и серверами. Пятая часть содержит справочные приложения.

_crossref:introduction[introduction,Введение]_::
Представляет FreeBSD новому пользователю. Описывает историю проекта FreeBSD, его цели и модель разработки.

_crossref:bsdinstall[bsdinstall,Установка FreeBSD]_::
Проводит пользователя через весь процесс установки FreeBSD 9._x_ и более поздних версий с использованием bsdinstall.

_crossref:basics[basics,Основы FreeBSD]_::
Охватывает основные команды и функциональность операционной системы FreeBSD. Если вы знакомы с Linux(R) или другой разновидностью UNIX(R), то, вероятно, можете пропустить эту главу.

_crossref:ports[ports,Установка приложений: Пакеты и порты]_::
Охватывает установку стороннего программного обеспечения с использованием инновационной "Коллекции портов" FreeBSD и стандартных бинарных пакетов.

_crossref:x11[x11,Система X Window]_::
Описывает X Window System в общем и использование X11 в FreeBSD в частности. Также рассматриваются популярные окружения рабочего стола, такие как KDE и GNOME.

_crossref:wayland[wayland,Wayland]_::
Описывает Wayland, сервер отображения в целом, и использование Wayland в FreeBSD в частности. Также рассматриваются популярные композиторы, такие как Wayfire, Hikari и Sway.

_crossref:desktop[desktop,Приложения для рабочего стола]_::
Перечисляет некоторые распространённые настольные приложения, такие как веб-браузеры и офисные пакеты, и описывает, как их установить в FreeBSD.

_crossref:multimedia[multimedia,Мультимедиа]_::
Показывает, как настроить поддержку воспроизведения звука и видео в системе. Также описываются некоторые примеры аудио- и видеоприложений.

_crossref:kernelconfig[kernelconfig,Настройка ядра FreeBSD]_::
Объясняет, зачем может потребоваться настройка нового ядра, и предоставляет подробные инструкции по настройке, сборке и установке кастомного ядра.

_crossref:printing[printing,Печать]_::
Описывает управление принтерами в FreeBSD, включая информацию о титульных страницах, учёте печати и первоначальной настройке.

_crossref:linuxemu[linuxemu,Совместимость с бинарными файлами Linux®]_::
Описывает возможности совместимости FreeBSD с Linux(R). Также содержит подробные инструкции по установке многих популярных приложений Linux(R), таких как Oracle(R) и Mathematica(R).

_crossref:wine[wine,WINE]_::
Описывает WINE и предоставляет подробные инструкции по установке. Также описывает, как работает WINE, как установить графический помощник, как запускать приложения Windows(R) на FreeBSD, а также предлагает другие советы и решения.

_crossref:config[config-tuning,Настройка и Тонкая Настройка]_::
Описывает параметры, доступные системным администраторам для настройки системы FreeBSD с целью достижения оптимальной производительности. Также описываются различные конфигурационные файлы, используемые в FreeBSD, и их расположение.

_crossref:boot[boot,Процесс загрузки FreeBSD]_::
Описывает процесс загрузки FreeBSD и объясняет, как управлять этим процессом с помощью параметров конфигурации.

_crossref:security[security,Безопасность]_::
Описывает множество различных инструментов, доступных для обеспечения безопасности системы FreeBSD, включая Kerberos, IPsec и OpenSSH.

_crossref:jails[jails,Клетки]_::
Описывает фреймворк клеток и улучшения по сравнению с традиционной поддержкой chroot в FreeBSD.

_crossref:mac[mac,Принудительный контроль доступа]_::
Объясняет, что такое Принудительный Контроль Доступа (Mandatory Access Control, MAC) и как этот механизм может быть использован для защиты системы FreeBSD.

_crossref:audit[audit,Аудит событий безопасности]_::
Описывает, что такое аудит событий в FreeBSD, как его можно установить, настроить, а также как проверять или отслеживать журналы аудита.

_crossref:disks[disks,Устройства хранения]_::
Описывает, как управлять носителями данных и файловыми системами в FreeBSD. Это включает физические диски, RAID-массивы, оптические и ленточные носители, диски в памяти и сетевые файловые системы.

_crossref:geom[geom,GEOM: Модульная инфраструктура преобразования дисковых запросов]_::
Описывает, что такое фреймворк GEOM в FreeBSD и как настроить различные поддерживаемые уровни RAID.

_crossref:zfs[zfs,Платформа хранения данных OpenZFS]_::
Описывает платформу хранения данных OpenZFS и предоставляет краткое руководство по началу работы, а также информацию о продвинутых темах, связанных с использованием OpenZFS в FreeBSD.

_crossref:filesystems[filesystems,Другие файловые системы]_::
Изучает поддержку неродных файловых систем в FreeBSD, таких как ext2, ext3 и ext4.

_crossref:virtualization[virtualization,Виртуализация]_::
Описывает, какие системы виртуализации доступны и как их можно использовать с FreeBSD.

_crossref:l10n[l10n, Локализация - использование и настройка i18n/L10n]_::
Описывает, как использовать FreeBSD на языках, отличных от английского. Рассматривает локализацию как на уровне системы, так и на уровне приложений.

_crossref:cutting-edge[updating-upgrading,Обновление и модернизация FreeBSD]_::
Объясняет различия между FreeBSD-STABLE, FreeBSD-CURRENT и выпусками FreeBSD. Описывает, какие пользователи могут извлечь выгоду из отслеживания разработки системы, и излагает этот процесс. Рассматривает методы, которые пользователи могут использовать для обновления своей системы до последнего безопасного выпуска.

_crossref:dtrace[dtrace,DTrace]_::
Описывает, как настроить и использовать инструмент DTrace от Sun(TM) в FreeBSD. Динамическая трассировка помогает выявлять проблемы с производительностью, выполняя анализ системы в реальном времени.

_crossref:usb-device-mode[usb-device-mode,Режим USB-устройства / USB OTG]_::
Объясняет использование режима USB0-устройства и USB On The Go (USB OTG) в FreeBSD.

_crossref:ppp-and-slip[ppp-and-slip,PPP]_::
Описывает, как использовать PPP для подключения к удалённым системам в FreeBSD.

_crossref:mail[mail,Электронная Почта]_::
Объясняет различные компоненты почтового сервера и рассматривает простые вопросы настройки для наиболее популярного почтового сервера: sendmail.

_crossref:network-servers[network-servers,Сетевые серверы]_::
Предоставляет подробные инструкции и примеры конфигурационных файлов для настройки вашей FreeBSD-машины в качестве сервера сетевых файловых систем, сервера доменных имен, сервера сетевой информационной системы или сервера синхронизации времени.

_crossref:firewalls[firewalls,Межсетевые экраны]_::
Объясняет философию программных межсетевых экранов и предоставляет подробную информацию о настройке различных межсетевых экранов, доступных для FreeBSD.

_crossref:advanced-networking[advanced-networking,Расширенные сетевые технологии]_::
Описывает множество тем, связанных с сетями, включая совместное использование интернет-подключения с другими компьютерами в локальной сети, расширенные темы маршрутизации, беспроводные сети, Bluetooth(R), ATM, IPv6 и многое другое.

_crossref:mirrors[mirrors,Получение FreeBSD]_::
Перечисляет различные источники для получения FreeBSD на CDROM или DVD, а также различные сайты в Интернете, которые позволяют загрузить и установить FreeBSD.

_crossref: bibliography[bibliography,Библиография]_::
Эта книга затрагивает множество различных тем, которые могут пробудить в вас желание узнать больше. В библиографии приведён список отличных книг, на которые есть ссылки в тексте.

_crossref:eresources[eresources,Ресурсы в Интернете]_::
Описывает множество форумов, доступных для пользователей FreeBSD, где можно задавать вопросы и участвовать в технических обсуждениях, связанных с FreeBSD.

_crossref:pgpkeys[pgpkeys,OpenPGP Ключи]_::
Перечисляет PGP-отпечатки нескольких разработчиков FreeBSD.

[[preface-conv]]
== Условные обозначения, используемые в этой книге

Для обеспечения единообразия и удобочитаемости текста в книге соблюдаются определённые соглашения.

[[preface-conv-typographic]]
=== Типографические соглашения

_Курсив_::
_Курсивный_ шрифт используется для имен файлов, URL-адресов, выделенного текста и первого упоминания технических терминов.

`Моноширинный`::
Моноширинный шрифт используется для сообщений об ошибках, команд, переменных окружения, названий портов, имён хостов, имён пользователей, имён групп, имён устройств, переменных и фрагментов кода.

*Жирный*::
*Жирный* шрифт используется для приложений, команд и клавиш.

[[preface-conv-commands]]
=== Ввод пользователя

Ключи выделены *жирным шрифтом*, чтобы отличаться от остального текста. Комбинации клавиш, которые нужно нажимать одновременно, обозначаются символом `+` между клавишами, например:

kbd:[Ctrl+Alt+Del]

Пользователь должен одновременно нажать клавиши kbd:[Ctrl], kbd:[Alt] и kbd:[Del].

Клавиши, которые нужно нажимать последовательно, разделяются запятыми, например:

kbd:[Ctrl+X], kbd:[Ctrl+S]

Это означает, что пользователь должен одновременно нажать клавиши kbd:[Ctrl] и kbd:[X], а затем одновременно нажать клавиши kbd:[Ctrl] и kbd:[S].

[[preface-conv-examples]]
=== Примеры

Примеры, начинающиеся с [.filename]#C:\>#, обозначают команду MS-DOS(R). Если не указано иное, эти команды могут быть выполнены в окне "Командная строка" в современной среде Microsoft(R) Windows(R).

[source, shell]
....
C:\> tools\fdimage floppies\kern.flp A:
....

Примеры, начинающиеся с символа `#`, обозначают команды, которые должны выполняться с правами суперпользователя в FreeBSD. Вы можете войти в систему как `root` для выполнения команды или использовать обычную учётную запись и применить man:su[1] для получения прав суперпользователя.

[source, shell]
....
# dd if=kern.flp of=/dev/fd0
....

Примеры, начинающиеся с символа %, обозначают команды, которые должны выполняться от имени обычной учётной записи. Если не указано иное, для установки переменных окружения и других команд оболочки используется синтаксис C-shell.

[source, shell]
....
% top
....

[[preface-acknowledgements]]
== Благодарности

Книга, которую вы держите в руках, — это результат труда многих сотен людей по всему миру. Будь то исправления опечаток или целые главы, все их вклады оказались полезными.

Несколько компаний поддержали разработку этого документа, оплачивая работу авторов на полную ставку, финансируя публикацию и т.д. В частности, BSDi (позже приобретенная http://www.windriver.com[Wind River Systems]) оплачивала членам FreeBSD Documentation Project работу над улучшением этой книги на полной ставке вплоть до публикации первого печатного издания в марте 2000 года (ISBN 1-57176-241-8). Затем Wind River Systems оплатила работу нескольких дополнительных авторов для внесения ряда улучшений в инфраструктуру печатного вывода и добавления новых глав к тексту. Эта работа завершилась публикацией второго печатного издания в ноябре 2001 года (ISBN 1-57176-303-1). В 2003-2004 годах http://www.freebsdmall.com[FreeBSD Mall, Inc] оплатила работу нескольких участников над улучшением Руководства в рамках подготовки к третьему печатному изданию. Третье печатное издание было разделено на два тома. Оба тома были опубликованы как *The FreeBSD Handbook 3rd Edition Volume 1: User Guide* (ISBN 1-57176-327-9) и *The FreeBSD Handbook 3rd Edition Volume 2: Administrators Guide* (ISBN 1-57176-328-7).
