---
title: Предисловие
prev: books/handbook/
next: books/handbook/parti
---

[preface]
[[book-preface]]
= Предисловие
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums!:
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Содержание
:table-caption: Таблица
:figure-caption: Рисунок
:example-caption: Пример
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:

[[preface-audience]]
== Целевая аудитория

Люди, которые используют FreeBSD с недавнего времени, найдут, что первая часть этой книги проводит читателя через процесс установки FreeBSD и кратко освещает идеи и традиции, на которых базируется UNIX(R). Работа с этой частью требует несколько большего, чем просто желание исследовать - необходима возможность принимать к сведению новые идеи.

Вторая, много большая часть Руководства, является всеобъемлющим справочником о всех темах, которые могут интересовать администраторов FreeBSD. Некоторые из глав этой части могут рекомендовать вам предварительное чтение других документов, о чём упоминается в кратком обзоре в начале каждой главы.

Список рекомендуемой дополнительной литературы вы можете найти в crossref:bibliography[bibliography,Библиография].

[[preface-changes-from2]]
== Изменения по сравнению со второй редакцией

Третья редакция является кульминацией более чем двух лет работы отдельных членов проекта документации FreeBSD. Вот основные изменения в новой редакции:

* crossref:config[config-tuning, Настройка и оптимизация], Настройка и оптимизация, была расширена новой информацией о ACPI управлении питанием и ресурсами, системной утилите cron и дополнительных параметрах оптимизации ядра.
* crossref:security[security, Безопасность], Безопасность, была расширена новой информацией о виртуальных частных сетях (VPN), списках контроля доступа файловой системы (ACL), и сообщениях безопасности.
* crossref:mac[mac, Принудительный контроль доступа (MAC)], Принудительный контроль доступа (MAC), новая глава этой редакции. Она описывает, что такое MAC и как этот механизм может быть использован для защиты системы FreeBSD.
* crossref:disks[disks, Устройства хранения], Устройства хранения, была расширена новой информацией о устройствах хранения USB, образах файловой системы, квотах файловой системы, файловых системах в файлах и в сети, зашифрованных дисковых разделах.
* К crossref:ppp-and-slip[ppp-and-slip, PPP и SLIP], PPP и SLIP, был добавлен раздел о решении проблем.
* crossref:mail[mail, Электронная почта], Электронная почта, была расширена новой информацией об использовании альтернативных транспортных агентов, SMTP аутентификации, UUCP, fetchmail, procmail, и другими разделами повышенной сложности.
* crossref:network-servers[network-servers, Сетевые серверы], Сетевые серверы, появилась в этой редакции. Эта главы включает информацию о установке Apache HTTP Server, FTPd, и настройке Samba сервера для клиентов Microsoft Windows. Некоторые разделы были перемещены сюда из crossref:advanced-networking[advanced-networking, Сложные вопросы работы в сети], Сложные вопросы работы в сети.
* crossref:advanced-networking[advanced-networking, Сложные вопросы работы в сети], Сложные вопросы работы в сети, была расширена новой информацией об использовании устройств Bluetooth в FreeBSD, настройке беспроводных сетей, и сетях Asynchronous Transfer Mode (ATM).
* Был добавлен глоссарий, объединяющий информацию о технических терминах, используемых в книге.
* Множество эстетических улучшений были внесены в таблицы и иллюстрации этой книги.

[[preface-changes]]
== Изменения во второй редакции

Вторая редакция является кульминацией более чем двухлетней работы членов Проекта документации FreeBSD. Нижеследующий список перечисляет все значительные изменения, внесенные в эту редакцию:

* Был добавлен полный указатель тем.
* Все ASCII-иллюстрации были заменены на графические.
* Был добавлен стандартный краткий обзор к каждому разделу для того, чтобы читатель мог получить представление о содержании раздела и о том, что необходимо знать для его изучения.
* Содержимое было логически реорганизовано на три части: "В Начале", "Системное администрирование" и "Приложения".
* crossref:install[install, Установка FreeBSD версий 8.X и более ранних] ("Установка FreeBSD") была полностью переписана, добавлено большое количество снимков экрана, чтобы облегчить понимание текста для новых пользователей.
* crossref:basics[basics, Основы UNIX] ("Основы UNIX(R)") была расширена и содержит дополнительную информацию о процессах, даемонах и сигналах.
* crossref:ports[ports, Установка приложений. порты и пакеты] ("Установка приложений: порты и пакеты") была расширена и содержит дополнительную информации об управлении бинарными пакетами.
* crossref:x11[x11, X Window System] ("X Window System") была полностью переписана и обращает больше внимания на современные технологии для рабочего стола, такие, как KDE и GNOME на XFree86(TM) 4.X.
* crossref:boot[boot, Процесс загрузки FreeBSD] ("Процесс загрузки FreeBSD") была расширена.
* crossref:disks[disks, Устройства хранения] ("Устройства хранения") была составлена из того, что раньше было двумя различными главами: "Диски" и "Резервное копирование". Мы считаем, что данные темы будут проще и более полно описаны как одна глава. Был добавлен раздел о программном и аппаратном RAID.
* crossref:serialcomms[serialcomms, Последовательные соединения] ("Последовательные коммуникации") была полностью реорганизована и обновлена для FreeBSD 4.X/5.X.
* crossref:ppp-and-slip[ppp-and-slip, PPP и SLIP] ("PPP и SLIP") была существенно обновлена.
* Было добавлено множество новых разделов в crossref:advanced-networking[advanced-networking, Сложные вопросы работы в сети] ("Сложные вопросы работы в сети").
* crossref:mail[mail, Электронная почта] ("Электронная почта") была расширена, теперь она включает больше информации о настройке sendmail.
* crossref:linuxemu[linuxemu, Двоичная совместимость с Linux] ("Работа с приложениями, написанными для Linux(R)") была дополнена включением информации об установке Oracle(R) и SAP(R) R/3(R).
* Следующие новые темы были рассмотрены в этой, второй, редакции:

** Настройка и оптимизация (crossref:config[config-tuning, Настройка и оптимизация]).
** Мультимедиа (crossref:multimedia[multimedia, Мультимедиа])

[[preface-overview]]
== Структура этой книги

Эта книга разбита на пять частей. В первой части, _В начале_, рассматривается установка и основные навыки использования FreeBSD. Предполагается, что читатель освоит эти разделы последовательно, возможно пропуская разделы, в которых обсуждаются уже знакомые для него темы. Вторая часть, _Общие задачи_, рассказывает о некоторых наиболее часто используемых возможностях FreeBSD. Этот раздел и все последующие могут быть прочитаны не по порядку. Каждая глава начинается с краткого обзора, который описывает, о чём говорится в ней и что читатель должен будет знать для прочтения этой главы. Это сделано для того, чтобы случайно встретивший этот материал читатель мог найти разделы, которые его интересуют. В третьей части, _Системное администрирование_, рассмотрены вопросы администрирования. В четвертой части, _Сетевые коммуникации_, охвачены темы, связанные с серверами и сетью. Пятая часть содержит приложения и справочную информацию.

_crossref:introduction[introduction, Введение], Введение_::
Знакомит пользователя с FreeBSD. Рассказывает об истории проекта FreeBSD, его задачах и модели разработки.

_crossref:install[install, Установка FreeBSD версий 8.X и более ранних], Установка_::
Проводит пользователя через весь процесс установки. Обсуждаются также некоторые более сложные вопросы установки, такие как установка по последовательной консоли.

_crossref:basics[basics, Основы UNIX], Основы UNIX(R)_::
Рассказывает об основных командах и функциональности операционной системы FreeBSD. Если вы знакомы с Linux(R) или другой UNIX(R)-подобной операционной системой, возможно, вы пропустите эту главу.

_crossref:ports[ports, Установка приложений. порты и пакеты], Установка приложений: порты и пакеты_::
Рассказывает о процессе установки программного обеспечения сторонних производителей с использованием "Коллекции Портов FreeBSD" и стандартных бинарных пакетов.

_crossref:x11[x11, X Window System], X Window System_::
Описывает X Window System вообще и использование X11 под управлением FreeBSD в частности. Также описывает популярные окружения рабочего стола, такие как KDE и GNOME.

_crossref:desktop[desktop, Приложения для настольного компьютера], Приложения для настольного компьютера_::
Перечисляет некоторые популярные приложения для рабочей станции, такие как веб-браузеры и офисные пакеты и описывает процесс их установки на FreeBSD.

_crossref:multimedia[multimedia, Мультимедиа], Мультимедиа_::
Показывает, как настроить поддержку воспроизведения звука и видео на вашей системе. Также описывает некоторые примеры приложений для воспроизведения звука и видео.

_crossref:kernelconfig[kernelconfig, Настройка ядра FreeBSD], Настройка ядра FreeBSD_::
Объясняет, почему вам может понадобиться перенастроить ядро и детально описывает процесс настройки, сборки и установки нового ядра.

_crossref:printing[printing, Печать], Печать_::
Рассказывает об управлении принтерами в FreeBSD, включая информацию об титульных страницах, учёте использования принтеров и первоначальной настройке.

_crossref:linuxemu[linuxemu, Двоичная совместимость с Linux], Двоичная совместимость с Linux(R)_::
Описывает возможности Linux(R)-совместимости в FreeBSD. Также предоставляет детальные инструкции по установке многих популярных приложений для Linux(R), таких как: Oracle(R), SAP(R) R/3(R) и Mathematica(R).

_crossref:config[config-tuning, Настройка и оптимизация], Настройка и оптимизация_::
Описывает всевозможные параметры настройки FreeBSD, которые может использовать системный администратор для оптимальной настройки системы. Также описывает различные конфигурационные файлы, используемые в FreeBSD и расположение этих файлов на диске.

_crossref:boot[boot, Процесс загрузки FreeBSD], Процесс загрузки FreeBSD_::
Рассказывает о процессе загрузки FreeBSD и объясняет, как управлять этим процессом при помощи различных настроек.

_crossref:users[users-synopsis, Пользователи и основы управления учётными записями], Пользователи и основы управления учётными записями_::
Рассказывает о создании и управлении пользовательскими учётными записями. Также обсуждает установку ограничений ресурсов для пользователей и другие задачи управления пользователями.

_crossref:security[security, Безопасность], Безопасность_::
Описывает множество различных утилит, которые помогут вам поддерживать FreeBSD в безопасном, надёжном состоянии, включая Kerberos, IPsec и OpenSSH.

_crossref:mac[mac, Принудительный контроль доступа (MAC)], Принудительный контроль доступа (MAC)_::
Описывает что такое принудительный контроль доступа (Mandatory Access Control, MAC) и как этот механизм может быть использован для защиты системы FreeBSD.

_crossref:disks[disks, Устройства хранения], Устройства хранения_::
Описывает как управлять накопителями информации и файловыми системами в FreeBSD, включая физические диски, массивы RAID, оптические и ленточные носители, диски в оперативной памяти и сетевые файловые системы.

_crossref:geom[GEOM, GEOM. Модульная инфраструктура преобразования дисковых запросов], GEOM_::
Рассказывает о подсистеме GEOM в FreeBSD и описывает различные поддерживаемые уровни RAID.

_crossref:filesystems[filesystems, Поддержка файловых систем], Поддержка файловых систем_::
Исследует поддержку неосновных файловых систем во FreeBSD, таких как, например, Sun(TM) Z File System.

_crossref:l10n[l10n, Локализация - использование и настройка i18n/L10n], Локализация - I18N/L10N использование и настройка_::
Описывает использование FreeBSD с языками, отличными от английского. Рассказывает о локализации на уровне системы и отдельных приложений.

_crossref:cutting-edge[updating-upgrading, Обновление системы и смена версии FreeBSD], Обновление системы и смена версии_::
Объясняет различия между FreeBSD-STABLE, FreeBSD-CURRENT и FreeBSD-RELEASE. Рассказывает, кому из пользователей будет полезно отслеживать версию системы в разработке и вкратце описывает этот процесс.

_crossref:serialcomms[serialcomms, Последовательные соединения], Последовательные соединения_::
Объясняет, как подключать терминалы и модемы к вашей системе FreeBSD, как в серверном, так и в клиентском режиме.

_crossref:ppp-and-slip[ppp-and-slip, PPP и SLIP], PPP и SLIP_::
Описывает использование PPP, SLIP или PPP через Ethernet для соединения с удалёнными системами при помощи FreeBSD.

_crossref:mail[mail, Электронная почта], Электронная почта_::
Описывает использование различных компонентов почтового сервера и более углублённо рассматривает простые вопросы конфигурации для наиболее популярного программного обеспечения почтовых серверов: sendmail.

_crossref:network-servers[network-servers, Сетевые серверы], Сетевые серверы_::
Предоставляет детальные инструкции и примеры файлов настройки для использования компьютера с FreeBSD в качестве файлового сервера (NFS), сервера доменных имен (DNS), сервера сетевой информационной системы (NIS), или сервера точного времени (ntpd).

_crossref:firewalls[firewalls, Межсетевые экраны], Брандмауэры_::
Описывает принципы, на которых основаны программные брандмауэры, и содержит детали конфигурирования различных брандмауэров, доступных в FreeBSD.

_crossref:advanced-networking[advanced-networking, Сложные вопросы работы в сети], Сложные вопросы работы в сети_::
Рассматривает множество вопросов работы с сетью, включая совместный доступ компьютеров вашей локальной сети к интернет, расширенные вопросы маршрутизации, беспроводные соединения, bluetooth, ATM, IPv6 и многое другое.

_crossref:mirrors[mirrors, Получение FreeBSD], Получение FreeBSD_::
Перечисляет различные источники, из которых можно получить FreeBSD на CDROM или DVD, равно как и различные сайты в интернет, с которых можно скачать и установить FreeBSD.

_crossref:bibliography[bibliography, Библиография], Библиография_::
Эта книга касается многих различных тем, которые могут сподвигнуть вас на более детальное изучение. Библиография перечисляет множество отличных книг, упоминаемых в тексте.

_crossref:eresources[eresources, Ресурсы в интернет], Ресурсы в интернет_::
Описывает множество форумов, доступных для пользователей FreeBSD, где можно задать вопросы и поучаствовать в технических обсуждениях FreeBSD.

_crossref:pgpkeys[pgpkeys, Ключи PGP], Ключи PGP_::
Содержит ключи PGP некоторых разработчиков FreeBSD.

[[preface-conv]]
== Договоренности, используемые в этой книге

Для того чтобы обеспечить целостность и простоту чтения текста в данной книге, мы применяем некоторые договорённости.

[[preface-conv-typographic]]
=== Типографические договорённости

_Наклонный шрифт_::
_Наклонный шрифт_ используется для имен файлов, адресов в интернет (URL), выделенного текста и первого применения технических терминов.

`Моноширинный шрифт`::
`Моноширинных шрифт` используется для сообщений об ошибках, команд, имен пользователей, названий групп, названий устройств, переменных и фрагментов кода.

Полужирный шрифт::
Полужирный шрифт используется для обозначения приложений, команд и параметров.

[[preface-conv-commands]]
=== Пользовательский ввод

Клавиши представляются в виде *полужирного текста* для того, чтобы выделяться среди остального текста. Комбинации клавиш, которые должны вводиться одновременно, разделяются символом `+`, например:

kbd:[Ctrl+Alt+Del]

Это будет означать, что пользователь должен нажать клавиши kbd:[Ctrl], kbd:[Alt] и kbd:[Del] одновременно.

Комбинации клавиш, которые должны вводиться последовательно, разделяются запятыми, например:

kbd:[Ctrl+X], kbd:[Ctrl+S]

Это будет означать, что пользователь должен нажать kbd:[Ctrl] и kbd:[X] одновременно, после чего одновременно нажать kbd:[Ctrl] и kbd:[S].

[[preface-conv-examples]]
=== Примеры

Примеры, которые начинаются с [.filename]#E:\># обозначают команды MS-DOS(R). Если не указано обратного, эти команды могут вводиться из окна "Сеанс MS-DOS(R)" в современных системах Microsoft(R) Windows(R).

[source,bash]
....
E:\> tools\fdimage floppies\kern.flp A:
....

Примеры, которые начинаются с # обозначают команды, которые должны быть запущены с правами суперпользователя в FreeBSD. Вы можете войти в систему как пользователь `root` для того, чтобы ввести эти команды или войти в систему обычным пользователем и использовать man:su[1] для того, чтобы получить привилегии суперпользователя.

[source,bash]
....
# dd if=kern.flp of=/dev/fd0
....

Примеры, начинающиеся с %, указывают, что команда должна быть исполнена с правами обычного пользователя. Если не указано обратного, используется синтаксис C-shell для установки переменных окружения и других команд.

[source,bash]
....
% top
....

[[preface-acknowledgements]]
== Благодарности

Книга, которую вы держите в руках являет собой результат труда многих сотен людей по всему миру. Не имеет значения, присылали ли они исправления опечаток или предоставляли целые главы, их труд был полезен.

Несколько компаний поддерживали разработку этого документа, оплачивая авторам их труд, оплачивая публикацию и т.д. В частности, BSDi (в последствии приобретённая компанией http://www.windriver.com[Wind River Systems]) оплачивала труд по улучшению этой книги участникам Проекта Документации FreeBSD, что в итоге сделало возможным выпуск первой печатной версии в марте 2000 года (ISBN 1-57176-241-8). Впоследствии компания Wind River Systems оплатила работу нескольких авторов по улучшению генерации книги в удобном для печати виде и добавлению нескольких глав. Кульминация этой работы являла собой публикацию второй печатной версии в ноябре 2001 года (ISBN 1-57176-303-1). В 2003-2004 годах http://www.freebsdmall.com[FreeBSD Mall, Inc] заплатила нескольким контрибьюторам за улучшение Handbook при подготовке к третьей редакции.
