# $Id: Makefile,v 1.2 1999-02-26 14:36:05 jesusr Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists("../Makefile.conf")
.include "../Makefile.conf"
.endif

# quick news letter
DOCS=	qnewsletter.sgml
DOCS+=	qnewsletter-1-1.sgml
DOCS+=	qnewsletter-1-2.sgml
DOCS+=	qnewsletter-1-3.sgml
DOCS+=	qnewsletter-1-4.sgml
DOCS+=	qnewsletter-1-5.sgml
DOCS+=	qnewsletter-1-6.sgml
DOCS+=	qnewsletter-1-7.sgml
DOCS+=	qnewsletter-2-1.sgml

DOCS+= press.sgml
DOCS+= newsflash.sgml
DOCS+= news.sgml
DOCS+= webchanges.sgml

INDEXLINK= news.html

.include "../web.mk"
