# $FreeBSD: www/es/ports/Makefile.inc0,v 1.1 1999/11/15 20:37:56 jesusr Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

.if exists(Makefile.inc)
.include "Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif


.include "${WEB_PREFIX}/share/mk/web.site.mk"
