# $FreeBSD: www/en/ports/Makefile.inc0,v 1.2 1999/09/06 07:02:48 peter Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(Makefile.inc)
.include "Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif


.include "../web.mk"
