#!/bin/sh
# Copyright (c) June 1998 Wolfram Schneider <wosch@FreeBSD.ORG>, Berlin.
#
# packages - create a sorted list of precompiled packages which
#            are available at the FreeBSD FTP Server.
#
# $Id: packages,v 1.1.1.1 1999-02-08 19:26:11 wosch Exp $

PATH=/bin:/usr/bin:/usr/local/bin; export PATH

release='packages-stable';
url="ftp://ftp.freebsd.org/pub/FreeBSD/$release/All/"


lynx -source "$url" | 
    perl -ne 'print $1, "\n" if m%href="([^"]+)"%oi' |
    perl -npe  's%.*/%%' | sort | grep -v '^\.\.$'

