# $FreeBSD$
# The FreeBSD Russian Documentation Project
# Original revision: 1.7

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS = gallery.sgml

INDEXLINK= gallery.html

#BUILDTOP=	../..
#DIR_IN_LOCAL=	gallery

.include "../web.mk"
