---
title: Bijlage B. Bibliografie
part: Deel V. Appendix
prev: books/handbook/mirrors
next: books/handbook/eresources
---

[appendix]
[[bibliography]]
= Bibliography
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Inhoudsopgave
:table-caption: Tabel
:figure-caption: Afbeelding
:example-caption: Voorbeeld
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: B

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/nl/mailing-lists.adoc[]
include::shared/nl/teams.adoc[]
include::shared/nl/urls.adoc[]

Hoewel de handleiding de juiste referentie is voor individuele stukken van het FreeBSD besturingssysteem, staan ze erom bekend niet te illustreren hoe de stukken in elkaar vallen om het hele besturingssysteem soepel te laten draaien. Daarom wordt er gesteld dat er geen vervanger is voor een goed boek over UNIX(R) systeembeheer en een goede gebruikershandleiding.

[[bibliography-freebsd]]
== Boeken & tijdschriften over FreeBSD

_Internationale boeken & Tijdschriften:_

* http://jdli.tw.FreeBSD.org/publication/book/freebsd2/index.htm[ Using FreeBSD] (Traditioneel Chinees), gepubliceerd door http://www.drmaster.com.tw/[Drmaster], 1997. ISBN 9-578-39435-7.
* FreeBSD Unleashed (Versimpelde Chinese vertaling), gepubliceerd door http://www.hzbook.com/[China Machine Press]. ISBN 7-111-10201-0.
* FreeBSD From Scratch Second Edition (Versimpeld Chinees), gepubliceerd door China Machine Press. ISBN 7-111-10286-X.
* FreeBSD Handbook Second Edition (Versimpeld Chinese vertaling), gepubliceerd door http://www.ptpress.com.cn/[Posts & Telecom Press]. ISBN 7-115-10541-3.
* FreeBSD & Windows (Versimpeld Chinees), gepubliceerd door gepubliceerd door http://www.tdpress.com/[China Railway Publishing House]. ISBN 7-113-03845-X
* FreeBSD Internet Services HOWTO (Versimpeld Chinees), gepubliceerd door China Railway Publishing House. ISBN 7-113-03423-3
* FreeBSD (Japans), gepubliceerd door CUTT. ISBN 4-906391-22-2 C3055 P2400E.
* http://www.shoeisha.com/book/Detail.asp?bid=650[Complete Introduction to FreeBSD] (Japans), gepubliceerd door http://www.shoeisha.co.jp/[Shoeisha Co., Ltd]. ISBN 4-88135-473-6 P3600E.
* http://www.ascii.co.jp/pb/book1/shinkan/detail/1322785.html[Personal UNIX Starter Kit FreeBSD] (Japans), gepubliceerd door http://www.ascii.co.jp/[ASCII]. ISBN 4-7561-1733-3 P3000E.
* FreeBSD Handbook (Japanse vertaling), gepubliceerd door http://www.ascii.co.jp/[ASCII]. ISBN 4-7561-1580-2 P3800E.
* FreeBSD mit Methode (Duits), gepubliceerd door http://www.cul.de[Computer und Literatur Verlag]/Vertrieb Hanser, 1998. ISBN 3-932311-31-0.
* http://www.mitp.de/vmi/mitp/detail/pWert/1343/[FreeBSD de Luxe] (Duits), gepubliceerd door http://www.mitp.de[Verlag Modere Industrie], 2003. ISBN 3-8266-1343-0.
* http://www.pc.mycom.co.jp/FreeBSD/install-manual.html[FreeBSD Install and Utilization Manual] (Japans), gepubliceerd door http://www.pc.mycom.co.jp/[Mainichi Communications Inc.].
* Onno W Purbo, Dodi Maryanto, Syahrial Hubbany, Widjil Widodo _http://maxwell.itb.ac.id/[Building Internet Server with FreeBSD]_ (Indonesisch), published by http://www.elexmedia.co.id/[Elex Media Komputindo].
* Absolute BSD: The Ultimate Guide to FreeBSD (Traditioneel Chinese vertaling), gepubliceerd door http://www.grandtech.com.tw/[GrandTech Press], 2003. ISBN 986-7944-92-5.
* http://www.twbsd.org/cht/book/[The FreeBSD 6.0 Book] (Traditioneel Chinees), gepubliceerd door Drmaster, 2006. ISBN 9-575-27878-X.

_Engelstalige boeken & Tijdschriften:_

* http://www.absoluteFreeBSD.com/[Absolute FreeBSD, 2e editie: The Complete Guide to FreeBSD], gepubliceerd door http://www.nostarch.com/[No Starch Press], 2007. ISBN: 978-1-59327-151-0
* http://www.freebsdmall.com/cgi-bin/fm/bsdcomp[The Complete FreeBSD], gepubliceerd door http://www.oreilly.com/[O'Reilly], 2003. ISBN: 0596005164
* http://www.freebsd-corp-net-guide.com/[The FreeBSD Corporate Networker's Guide], gepubliceerd door http://www.awl.com/aw/[Addison-Wesley], 2000. ISBN: 0201704811
* http://andrsn.stanford.edu/FreeBSD/introbook/[FreeBSD: An Open-Source Operating System for Your Personal Computer], gepubliceerd door The Bit Tree Press, 2001. ISBN: 0971204500
* Teach Yourself FreeBSD in 24 Hours, gepubliceerd door http://www.samspublishing.com/[Sams], 2002. ISBN: 0672324245
* FreeBSD unleashed, gepubliceerd door http://www.samspublishing.com/[Sams], 2006. ISBN: 0672328755
* FreeBSD: The Complete Reference, gepubliceerd door http://books.mcgraw-hill.com[McGrawHill], 2003. ISBN: 0072224096 
* http://www.bsdmag.org[BSD Magazine], gepubliceerd door Software Press Sp. z.o.o. SK. ISSN 1898-9144

[[bibliography-userguides]]
== Voor gebruikers

* Ohio State University heeft een http://www.cs.duke.edu/csl/docs/unix_course/[UNIX Introductiecursus] geschreven welke online in HTML en in PostScript(R) formaat beschikbaar is.
+ 
Een Italiaanse https://www.FreeBSD.org/doc/it_IT.ISO8859-15/books/unix-introduction/index.html[vertaling] van dit document is beschikbaar als onderdeel van het FreeBSD Italian Documentation Project.
* http://www.jp.FreeBSD.org/[Jpman Project, Japan FreeBSD Users Group]. http://www.pc.mycom.co.jp/FreeBSD/urm.html[FreeBSD User's Reference Manual] (Japanse vertaling). http://www.pc.mycom.co.jp/[Mainichi Communications Inc.], 1998. ISBN4-8399-0088-4 P3800E.
* http://www.ed.ac.uk/[Edinburgh University] heeft een http://unixhelp.ed.ac.uk/[Online Guide] geschreven voor nieuwkomers in de UNIX(R) omgeving.

[[bibliography-adminguides]]
== Voor beheerders

* http://www.jp.FreeBSD.org/[Jpman Project, Japan FreeBSD Users Group]. http://www.pc.mycom.co.jp/FreeBSD/sam.html[FreeBSD System Administrator's Manual] (Japanse vertaling). http://www.pc.mycom.co.jp/[Mainichi Communications Inc.], 1998. ISBN4-8399-0109-0 P3300E.
* Dreyfus, Emmanuel. http://www.eyrolles.com/Informatique/Livre/9782212114638/[Cahiers de l'Admin: BSD] 2nd Ed. (Frans), Eyrolles, 2004. ISBN 2-212-11463-X

[[bibliography-programmers]]
== Voor programmeurs

* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Reference Manual_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-078-3
* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Supplementary Documents_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-079-1
* Harbison, Samuel P. and Steele, Guy L. Jr. _C: A Reference Manual_. 4th ed. Prentice Hall, 1995. ISBN 0-13-326224-3
* Kernighan, Brian and Dennis M. Ritchie. _The C Programming Language._. 2nd Ed. PTR Prentice Hall, 1988. ISBN 0-13-110362-8
* Lehey, Greg. _Porting UNIX Software_. O'Reilly & Associates, Inc., 1995. ISBN 1-56592-126-7
* Plauger, P. J. _The Standard C Library_. Prentice Hall, 1992. ISBN 0-13-131509-9
* Spinellis, Diomidis. http://www.spinellis.gr/codereading/[Code Reading: The Open Source Perspective]. Addison-Wesley, 2003. ISBN 0-201-79940-5
* Marshall Kirk McKusick, George V. Neville-Neil. _The Design and Implementation of the FreeBSD UNIX Operating System_. Boston, Mass. : Addison-Wesley, 2004. ISBN 0-201-70245-2
* Spinellis, Diomidis. http://www.spinellis.gr/codequality/[Code Quality: The Open Source Perspective]. Addison-Wesley, 2006. ISBN 0-321-16607-8
* Stevens, W. Richard. _Advanced Programming in the UNIX Environment_. Reading, Mass. : Addison-Wesley, 2005. ISBN 0-201-43307-9
* Stevens, W. Richard. _UNIX Network Programming_. 2nd Ed, PTR Prentice Hall, 1998. ISBN 0-13-490012-X

[[bibliography-osinternals]]
== Dieper in het besturingssysteem

* Andleigh, Prabhat K. _UNIX System Architecture_. Prentice-Hall, Inc., 1990. ISBN 0-13-949843-5
* Jolitz, William. "Porting UNIX to the 386". _Dr. Dobb's Journal_. January 1991-July 1992.
* Leffler, Samuel J., Marshall Kirk McKusick, Michael J Karels en John Quarterman _The Design and Implementation of the 4.3BSD UNIX Operating System_. Reading, Mass. : Addison-Wesley, 1989. ISBN 0-201-06196-1
* Leffler, Samuel J., Marshall Kirk McKusick, _The Design and Implementation of the 4.3BSD UNIX Operating System: Answer Book_. Reading, Mass. : Addison-Wesley, 1991. ISBN 0-201-54629-9
* McKusick, Marshall Kirk, Keith Bostic, Michael J Karels, and John Quarterman. _The Design and Implementation of the 4.4BSD Operating System_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-54979-4
+ 
Hoofdstuk 2 is link:{design-44bsd}[online] beschikbaar als onderdeel van het FreeBSD Documentatie Project.
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 1: The Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63346-9
* Schimmel, Curt. _Unix Systems for Modern Architectures_. Reading, Mass. : Addison-Wesley, 1994. ISBN 0-201-63338-8
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 3: TCP for Transactions, HTTP, NNTP and the UNIX Domain Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63495-3
* Vahalia, Uresh. _UNIX Internals -- The New Frontiers_. Prentice Hall, 1996. ISBN 0-13-101908-2
* Wright, Gary R. and W. Richard Stevens. _TCP/IP Illustrated, Volume 2: The Implementation_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63354-X

[[bibliography-security]]
== Over beveiliging

* Cheswick, William R. and Steven M. Bellovin. _Firewalls and Internet Security: Repelling the Wily Hacker_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63357-4
* Garfinkel, Simson. _PGP Pretty Good Privacy_ O'Reilly & Associates, Inc., 1995. ISBN 1-56592-098-8

[[bibliography-hardware]]
== Over hardware

* Anderson, Don and Tom Shanley. _Pentium Processor System Architecture_. 2nd Ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40992-5
* Ferraro, Richard F. _Programmer's Guide to the EGA, VGA, and Super VGA Cards_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-62490-7
* Intel Corporation publiceert documentatie over haar CPU's, chipsets en standaarden op haar http://developer.intel.com/[ontwikkelaars website], gewoonlijk als PDF bestanden.
* Shanley, Tom. _80486 System Architecture_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40994-1
* Shanley, Tom. _ISA System Architecture_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40996-8
* Shanley, Tom. _PCI System Architecture_. 4th ed. Reading, Mass. : Addison-Wesley, 1999. ISBN 0-201-30974-2
* Van Gilluwe, Frank. _The Undocumented PC_, 2nd Ed. Reading, Mass: Addison-Wesley Pub. Co., 1996. ISBN 0-201-47950-8
* Messmer, Hans-Peter. _The Indispensable PC Hardware Book_, 4th Ed. Reading, Mass: Addison-Wesley Pub. Co., 2002. ISBN 0-201-59616-4

[[bibliography-history]]
== UNIX(R) geschiedenis

* Lion, John _Lion's Commentary on UNIX, 6th Ed. With Source Code_. ITP Media Group, 1996. ISBN 1573980137
* Raymond, Eric S. _The New Hacker's Dictionary, 3rd edition_. MIT Press, 1996. ISBN 0-262-68092-0. Ook bekend als het http://www.catb.org/~esr/jargon/html/index.html[Jargon Bestand]
* Salus, Peter H. _A quarter century of UNIX_. Addison-Wesley Publishing Company, Inc., 1994. ISBN 0-201-54777-5
* Simon Garfinkel, Daniel Weise, Steven Strassmann. _The UNIX-HATERS Handbook_. IDG Books Worldwide, Inc., 1994. ISBN 1-56884-203-1. Het is niet meer te leveren, maar wel http://www.simson.net/ref/ugh.pdf[online] beschikbaar.
* Don Libes, Sandy Ressler _Life with UNIX_ - special edition. Prentice-Hall, Inc., 1989. ISBN 0-13-536657-7
* _The BSD family tree_. http://www.FreeBSD.org/cgi/cvsweb.cgi/src/shared/misc/bsd-family-tree[http://www.FreeBSD.org/cgi/cvsweb.cgi/src/shared/misc/bsd-family-tree] of link:file://localhost/usr/shared/misc/bsd-family-tree[/usr/shared/misc/bsd-family-tree] op een FreeBSD machine.
* _Networked Computer Science Technical Reports Library_. http://www.ncstrl.org/[http://www.ncstrl.org/]
* _Oude BSD releases van de Computer Systems Research group (CSRG)_. http://www.mckusick.com/csrg/[http://www.mckusick.com/csrg/]: De set van 4 cd-roms bevat alle versies van BSD van 1BSD to 4.4BSD en 4.4BSD-Lite2 (maar helaas 2.11BSD niet). Op de laatste disk staan ook de laatste broncode en de SCCS bestanden.

[[bibliography-journals]]
== Tijdschriften en periodieken

* _The C/C++ Users Journal_. R&D Publications Inc. ISSN 1075-2838
* _Sys Admin - The Journal for UNIX System Administrators_ Miller Freeman, Inc., ISSN 1061-2688
* _freeX - Das Magazin für Linux - BSD - UNIX_ (Duits) Computer- und Literaturverlag GmbH, ISSN 1436-7033
