# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

#DOCS=	announce.sgml notes.sgml errata.sgml
DOCS=	notes.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/3.5R

.include "../../../web.mk"
