# $FreeBSD: www/ja/releases/3.5R/Makefile,v 1.1 2000/06/29 00:06:23 motoyuki Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

DOCS=	announce.sgml notes.sgml errata.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/3.5R

.include "../../../web.mk"
