# $FreeBSD: www/ja/releases/3.5R/Makefile,v 1.2 2000/07/09 15:55:59 hrs Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

LOCALTOP= ../..

DOCS=	announce.sgml notes.sgml errata.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
