# $FreeBSD: www/ja/releases/2.2R/Makefile,v 1.2 1999/09/06 07:03:27 peter Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

DOCS=	announce.sgml install-media.sgml notes.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/2.2R

.include "../../../web.mk"
