# $FreeBSD: www/ja/releases/2.2R/Makefile,v 1.3 1999/12/23 01:16:06 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

LOCALTOP= ../..

DOCS=	announce.sgml install-media.sgml notes.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
