.\" Copyright (c) 1994 by Tatsumi Hosokawa <hosokawa@jp.FreeBSD.org>
.\" 
.\" This software may be used, modified, copied, and distributed, in
.\" both source and binary form provided that the above copyright and
.\" these terms are retained. Under no circumstances is the author 
.\" responsible for the proper functioning of this software, nor does 
.\" the author assume any responsibility for damages incurred with its 
.\" use.
.\"
.\" Original Revision: 1.4
.\" jpman %Id: apmconf.8,v 1.3 1997/06/28 09:27:16 jsakai Stab %
.Dd November 1, 1994
.Dt APMCONF 8
.Os
.Sh 名称
.Nm apmconf
.Nd APM BIOS ドライバの設定を行う
.Sh 書式
.Nm apmconf
.Op Fl e
.Op Fl d
.Op Fl h
.Op Fl t
.Sh 解説
.Nm apmconf
は、ラップトップ PC 上の APM (Advanced Power Management) BIOS ドライバ
.Xr apm 4 
の設定のために使われます。
.Pp
以下のオプションが利用可能です。
.Bl -tag -width indent
.It Fl e
パワー管理を有効にします。
.It Fl d
パワー管理を無効にします。
.El
.Pp
これらのオプションは、
.Xr apm 4 
によって提供されるパワー管理機能を有効もしくは無効とします。
.Bl -tag -width indent
.It Fl h
カーネルのコンテキストスイッチルーチン内の HLT 命令を有効とします。
.It Fl t
カーネルのコンテキストスイッチルーチン内の HLT 命令を無効とします。
.El
.Pp
これらのオプションは、ほとんど全ての APM の実装においては必要では
ありませんが、
.Dq Pa Idle CPU
呼び出しが CPU クロックの減速と HLT 命令を同時に実行する場合は、
そのピーク性能の減少からシステムをまもるために
.Fl t
オプションが必要です。
詳細については、
.Xr apm 4
を参照してください。
.Sh 関連項目
.Xr apm 4 ,
.Xr apm 8 ,
.Xr zzz 8
.Sh 作者
.An Tatsumi Hosokawa Aq hosokawa@jp.FreeBSD.org
