.\" Copyright (c) 1994 Wolfgang Stanglmeier.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\"     %Id: ncrcontrol.8,v 1.4.2.1 1997/10/06 07:36:16 charnier Exp %
.\" jpman %Id: ncrcontrol.8,v 1.3 1997/06/20 00:23:48 yugawa Stab %
.\"
.Dd September 16, 1994
.Dt NCRCONTROL 8
.Os FreeBSD
.Sh 名称
.Nm ncrcontrol
.Nd ncr810/825 PCI/SCSI デバイスドライバを手動設定する
.Sh 書式
.\"--------------------------------------------------------
.\"  ncrcontrol [-Mcore] [-Nsystem] [-u unit] [-v] [-v] -i
.\"--------------------------------------------------------
.Nm ncrcontrol
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl u Ar unit
.Op Fl v
.Op Fl v
.Fl i
.\"--------------------------------------------------------
.\"  ncrcontrol [-N system] [-u unit] [-p wait]
.\"--------------------------------------------------------
.Nm ncrcontrol
.Op Fl N Ar system
.Op Fl u Ar unit
.Op Fl p Ar wait
.\"------------------------------------------------------------
.\"  ncrcontrol [-Nsystem] [-u unit] [-t target] -s name=value
.\"------------------------------------------------------------
.Nm ncrcontrol
.Op Fl N Ar system
.Op Fl u Ar unit
.Op Fl t Ar target
.Fl s
.Ar name=value
.\"------------------------------------------------------------
.\"  ncrcontrol [-Mcore] [-Nsystem] [-u unit] [-t target] -d pattern
.\"------------------------------------------------------------
.Nm ncrcontrol
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl u Ar unit
.Op Fl t Ar target
.Fl d
.Ar debug
.\"------------------------------------------------------------
.\"  ncrcontrol [-Nsystem] [-u unit] -w -k torture
.\"------------------------------------------------------------
.Nm ncrcontrol
.Op Fl N Ar system
.Op Fl u Ar unit
.Fl w
.Fl k
.Ar torture
.\"
.\"=====================================================================
.\"
.Sh 解説
.Nm
コマンドは ncr810/ncr825
pci/scsi ドライバの制御構造体の内容をシンボリックに表示します。
どのオプションで情報を表示するかにより、
何種類かの出力フォーマットが存在します。
このコマンドは、いくつかの値を設定するために使うこともできます。

.\"--------------------------------------------------------
.\"  ncrcontrol [-Mcore] [-Nsystem] [-u unit] [-v] [-v] -i
.\"--------------------------------------------------------
このコマンドの最初の形式では、接続されているターゲットの概要が
出力されます。
.Fl v
を指定すると、詳細な出力がおこなわれます。

.\"--------------------------------------------------------
.\"  ncrcontrol [-N system] [-u unit] [-p wait]
.\"--------------------------------------------------------
第 2 の形式では、
.Ar wait
インターバルが指定されている場合、
.Nm
は選択された SCSI バスのデータトラフィックに関する情報を
連続的に表示します。

.\"------------------------------------------------------------
.\"  ncrcontrol [-Nsystem] [-u unit] [-t target] -s name=value
.\"------------------------------------------------------------
第 3 の形式では、選択された SCSI バスの
一つまたはすべてのターゲットで使われる値の設定をおこないます。
カーネルコンフィグレーションでデバイスドライバのオプションが
正しく設定されているのであれば、通常は必要ありません。

.\"------------------------------------------------------------
.\"  ncrcontrol [-M core] [-N system] [-u unit] [-t target] -w -d pattern
.\"------------------------------------------------------------
第 4 の形式では、ドライバの制御構造体の内容を表示します。
.Ar pattern
を指定することにより、特定の部分の出力を許可/禁止することができます。
これはドライバのデバッグのためだけに使われます。

.\"------------------------------------------------------------
.\"  ncrcontrol [-N system] [-u unit] -w -k torture
.\"------------------------------------------------------------
最後の形式では、強制的にある障害をドライバに発生させることができます。
これはあなたのシステムをクラッシュさせる場合があります。
これはドライバのデバッグのためだけに使われます。

.\"
.\"=====================================================================
.\"
.Pp
オプションは以下の意味を持っています:
.Bl -tag -width flag
.\"------------------------------------------------------------
.\"  -d pattern
.\"------------------------------------------------------------
.It Fl d
ドライバの制御構造体の内容を表示します。
.Ar pattern
により表示されるフィールドを選択することができます。
.Fl d?
により有効なフラグのリストを得ることができます。

.\"------------------------------------------------------------
.\"  -i
.\"------------------------------------------------------------
.It Fl i
接続されているターゲットの設定状況を表示します。
.Fl v
オプションにより、さらに詳細な情報を要求することができます。

.\"------------------------------------------------------------
.\"  -k torture
.\"------------------------------------------------------------
.It Fl k
エラー回復機能のチェックのため、強制的にある障害をドライバに発生させます。
このオプションは開発者のみが使用するべきです。
.Fl k?
により、発生可能な障害の一覧が得られます。
このオプションを使用するためには
.Fl w
オプションを指定しておく必要があります。

.\"------------------------------------------------------------
.\"  -M core
.\"------------------------------------------------------------
.It Fl M
デフォルトの
.Pa /dev/kmem
のかわりに、指定したコアファイルから
ネームリストに結びつけられている値を取り出します。
.\"------------------------------------------------------------
.\"  -N system
.\"------------------------------------------------------------
.It Fl N
デフォルトの
.Pa /kernel
のかわりに、指定したカーネルファイルからネームリストを取り出します。

.\"------------------------------------------------------------
.\"  -p wait
.\"------------------------------------------------------------
.Ar wait
インターバルつきで実行された場合、
.Nm
は選択された SCSI バスにおける転送に関連する統計の現在の値を表示します。

この表示は、コントローラと接続されたターゲットそれぞれについての、
転送の実行回数と転送されたバイト数からなります。

(未完成)

.\"------------------------------------------------------------
.\"  -s field=value
.\"------------------------------------------------------------
.It Fl s
一つまたはそれ以上のターゲットで使われる値の設定をおこないます。
ターゲットは
.Fl t
オプションにより指定できます。ターゲットが指定されていない場合は、
接続されているターゲットすべてに対して設定がおこなわれます。

(未完成)

.\"------------------------------------------------------------
.\"  -t target
.\"------------------------------------------------------------
.It Fl t
.Fl s
オプションの対象となるターゲットを指定します。
このオプションは複数回指定することができます。

.\"------------------------------------------------------------
.\"  -u unit
.\"------------------------------------------------------------
.It Fl u
コントローラユニットを指定します。
このオプションが指定されていない場合、コントローラ 0 が仮定されます。
ほとんどのシステムでは、コントローラは一つだけです。

.\"------------------------------------------------------------
.\"  -v
.\"------------------------------------------------------------
.It Fl v
.Fl i
オプションの詳細出力を有効にします。

.\"------------------------------------------------------------
.\"  -w
.\"------------------------------------------------------------
.It Fl w
ウィザードオプションです。
.Fl k
オプションを使用する際に必要です。

.\"
.\"=====================================================================
.\"
.Pp
(未完成)

.\"
.\"=====================================================================
.\"
.Sh 関連項目
.Xr scsi 4 ,
.Xr scsi 8

.\"
.\"=====================================================================
.\"
.Sh 歴史
.Nm
コマンドは
.An Wolfgang Stanglmeier Aq wolf@dentaro.GUN.de
により
.Bx 386
用にハックされ、
.Bx Free
のバージョン 1.1 に移植されました。
.An Charles M. Hannum Aq mycroft@gnu.ai.mit.edu
により
.Bx Net
に移植され、
.An Stefan Esser Aq se@zpr.Uni-Koeln.DE
により
.Bx Free
のバージョン 2.0 に移植されました。

.\"
.\"=====================================================================
.\"
.Sh バグ
.Nm
は ncr810 ドライバのためのデバッグツールとしてハックされました。
これは近いうちに削除されるべきです。
デバイスドライバのオプションを動作中に変更するための
汎用のツールを用意するべきです。
統計データはジェネリック SCSI ドライバにより収集されるべきです。
