.\"	@(#) %Id: pppstats.8,v 1.3.2.2 1997/03/15 21:23:40 bde Exp %
.\" jpman %Id: pppstats.8,v 1.2 1997/05/23 09:03:43 mitchy Stab %
.Dd May 2, 1995
.Dt PPPSTATS 8
.Sh 名称
.Nm pppstats
.Nd PPP の利用統計を表示する
.Sh 書式
.Nm
.Op Fl v
.Op Fl r
.Op Fl c
.Op Fl i Ar secs
.Op Ar unit#
.Sh 解説
.Nm pppstats
は、PPP に関連した統計情報を表示します。
.Pp
.Fl v
オプションを指定すると
.Nm
は、通常の情報に加え、追加情報を表示します。
たとえば、エラーのために発信元に戻ったパケット数です
(VJ TCP ヘッダ圧縮で伸長に失敗した数です)。
.Pp
.Fl r
オプションを指定すると
.Nm
は、全体のパケットの圧縮率を表示します。圧縮率は、
0 から 1 の値で表され、 0 はデータが圧縮できないことを意味します。
.Pp
.Fl c
オプションは、パケット圧縮の統計の別の表示法を指定します:
圧縮、伸長されたパケットの数およびバイト数 (すなわち圧縮前と圧縮後の値)、
圧縮できなかった (圧縮で小さくならないため無圧縮で送られた)
パケットの数およびバイト数、最近の圧縮率が表示されます。
圧縮率は、圧縮が許可されてから以降の平均の値ではなく、最近の圧縮率を
反映したものです。
.Pp
.Fl i
オプションは、統計情報の表示の間隔を指定します。無指定時は 5 秒です。
.Pp
.Ar unit#
は、統計情報を表示するインターフェースを指定します。
.Sh 関連項目
.Xr pppd 8
