.TH ZDUMP 8
.\" jpman %Id: zdump.8,v 1.3 1997/08/30 18:39:05 take-i Stab %
.SH 名称
zdump \- タイムゾーンをダンプする
.SH 書式
.B zdump
[
.B \-v
] [
.B \-c
cutoffyear ] [ zonename ... ]
.SH 解説
.I zdump
は、コマンドラインの
.I zonename
で指定された各タイムゾーンを用いて現在時刻を表示します。
.PP
以下のオプションが利用可能です:
.TP
.B \-v
コマンドラインの各
.I zonename
に対し、表現可能な最も古い時刻、
その最も古い時刻から 1 日後の時刻、
検知された時間の不連続点の 1 秒前および不連続点そのものの時刻、
表現可能な最も先の時刻の 1 日前の時刻、
および表現可能な最も先の時刻そのもの
を表示します。
各時刻は、それが夏時間 (Daylight Saving Time) であれば
.B isdst=1
、そうでなければ
.B isdst=0
と行末にしるして表示されます。
.TP
.BI "\-c " cutoffyear
指定した年の最初に近い余分な出力をなくします。
.SH 関連項目
ctime(3), tzfile(5), zic(8)
.\" @(#)zdump.8	7.3
