---
title: "A FreeBSD/ARM projekt"
sidenav: developers
---

include::shared/authors.adoc[]
include::shared/hu/urls.adoc[]

= A FreeBSD/ARM projekt

== Bevezetés

Ezen az oldalon találhatunk információkat a FreeBSD ARM architektúrán és -hardveren futó változatáról. Az ezzel kapcsolatos megbeszélések a http://lists.freebsd.org/mailman/listinfo/freebsd-arm[freebsd-arm] levelezési listán folynak.

== Tartalomjegyzék

* <<status,Helyzet>>
* <<hw,Támogatott hardverek>>
* <<todo,További teendõk>>
* <<links,FreeBSD/ARM linkek>>
* <<miniinst,Rövid telepítési útmutató>>
* <<list,A FreeBSD/ARM levelezési lista>>

[[status]]
== Helyzet

Az ARM hivatalosan egy link:{committers-guide}#archs[Tier 2] szintû architektúra, tehát a link:../../[FreeBSD] Projekt ehhez nem készít hivatalos kiadásokat vagy elõre fordított csomagokat, mivel ez elsõsorban a beágyazott rendszereket veszi célba. Ettõl függetlenül a FreeBSD/ARM platformot aktívan fejlesztik és karbantartják, nagyon jó a támogatottsága, kitûnõ vázat nyújt az ARM-alapú rendszerek építéséhez.

[[hw]]
== Támogatott hardverek

A FreeBSD általában elindul az IQ31244 és IQ80321 chipeket tartalmazó, i80321 alapú Intel XScale(R) fejlesztõi kártyákon. A támogatása jelenleg csak minimális, kizárólag a processzort, a PCI-X buszt, az em(4) típusú Ethernet kártyákat, az UART és idõzítõ eszközöket ismeri.

Az EP80219 fejlesztõi kártyákon található i80219 XScale processzorok is támogatottak.

Az Avila GW2348-4 fejlesztõi kártyákon található IXP425 is támogatott.

A StrongARM 1100 CPU minimálisan támogatott, de csak a Simics emuláció keretein belül: CPU, UART és órajel. Elméletileg indítható a Simics által emulált kártyákon, de errõl eddig még nem érkezett sikeres vagy sikertelen visszajelzés.

Ezeken kívül még a Technologic Systems TS-7200 típusú fejlesztõi kártyáin található Atmel AT91SAM926x processzorok, a Marvell Orion ARM SoC, a Samsung S3C2XX0 sorozat és a Cirrus Logic EP93XX processzorok is támogatottak.

[[todo]]
== További teendõk

* SATA támogatás
* Egyéb eszközök, mint például watchdog, i2c és bus támogatását be kell olvasztani a NetBSD-bõl

[[links]]
== FreeBSD/ARM linkek

* http://tisu.mit.jyu.fi/embedded/TIE345/luentokalvot/Embedded_3_ARM.pdf[Az ARM rövid története]
* http://www.netbsd.org/Ports/arm32/[A NetBSD Arm/32 Projekt]

[[miniinst]]
== Rövid telepítési útmutató

{cognet} írt egy rövid telepítési útmutatót a jelenlegi FreeBSD forráskódhoz. Az útmutató elérhetõ http://people.freebsd.org/\~cognet/arm.html[itt].

[[list]]
== A FreeBSD/ARM levelezési lista

Úgy tudunk feliratkozni erre a listára, ha küldünk egy levelet a `<freebsd-arm-subscribe@FreeBSD.org>` címre, vagy használjuk a http://lists.FreeBSD.org/mailman/listinfo/freebsd-arm[mailman felületét].

== A zenészek ezt mondják a FreeBSD/ARM portról

A FreeBSD/ARM segítségével élvezheti a (beágyazott) rendszerébõl áradó csendet. A Depeche Mode-nak is errõl szól az "Enjoy The Silence" címû dala:

....
All I ever wanted
All I ever needed
Is here in my ARMs
Words are very unnecessary
They can only do harm
....
