---
title: "FreeBSD/ppc Project"
sidenav: developers
---

include::shared/releases.adoc[]
include::shared/hu/urls.adoc[]
include::shared/authors.adoc[]

= FreeBSD/ppc Project

== Bevezetés

A FreeBSD/ppc projekt oldalán a FreeBSD PowerPC(R) architektúrán futó változatáról olvashatunk részletesebb információkat. Ahogy maga ez a verzió is, úgy ez az oldal is folyamatos fejlesztés alatt áll.

* <<status,Helyzet>>
* <<news,Hírek>>
* <<faq,GYIK>>
* <<hardware,Támogatott hardverek>>
* <<list,A FreeBSD/ppc levelezési lista>>
* <<issues,Ismert problémák>>
* <<doc,Dokumentumok, segédprogramok>>
* <<links,Egyéb linkek>>

A FreeBSD/ppc port jelenleg egy link:{committers-guide}#archs[Tier 2] platform. Ez azt jelenti, hogy még nem támogatja teljes mértékben a security officer, sem a release engineerek és a toolchain karbantartói.

'''''

[[news]]
== Hírek

* *2009. április 3.* - A PowerPC G5 támogatása bekerült SVN alá.
* *2008. március 3.* - A fejlesztõi kártyákra integrált Freescale(R) PowerQUICC III MPC85XX család támogatása bekerült a CVS-be.
* *2008. február 27.* - A FreeBSD 7.0 az elsõ kiadás, amely hivatalosan támogatja a FreeBSD/ppc portot.

'''''

[[faq]]
== Gyakran Ismételt Kérdések

. <<one,Hogyan telepíthetjük a FreeBSD/ppc portot?>>
. <<two,Hogyan használjuk a Portgyûjteményt FreeBSD/ppc alatt?>>
. <<four,Kihez fordulhatunk?>>

[[one]]
=== Hogyan telepíthetjük a FreeBSD/ppc portot?

Tudunk letölteni új típusú Macekhez használható FreeBSD {rel-head-major} ISO image-eket, amelyekrõl részletesebben a link:https://www.FreeBSD.org/releases/{rel-head-major}R/announce.html[kiadás bejelentésében] olvashatunk. Ezután kövessük az http://people.freebsd.org/\~grehan/iso_install.txt[itt] található utasításokat.

[[three]]
=== Hogyan használjuk a Portgyûjteményt FreeBSD/ppc alatt?

A FreeBSD 6.0-RELEASE óta elérhetõ portsnap segítségével könnyû a portok használhata. Olvassuk el a kézikönyvet, amennyiben segítségre szorulnánk a link:{handbook}#ports-using[Portgyûjtemény] használata során.

[[four]]
=== Kihez fordulhatunk?

{grehan} a projekt vezetõje. õt kell megkeresnünk, ha fejlesztéseinkkel támogatni tudjuk a projektet. Ha csak a projekt aktuális állapota érdekel, ezt az oldalt olvassuk rendszeresen, vagy iratkozzunk fel a <<list,FreeBSD/ppc levelezési listára>>.

'''''

[[hardware]]
== Támogatott hardverek

A FreeBSD/ppc portnak mûködnie kell minden új (tehát bármilyen beépített USB porttal rendelkezõ Apple) számítógépen. A felhasználók a következõ számítógépeken futtatták sikeresen a FreeBSD-t:

[cols=",,,",options="header",]
|===
|Gyártó |Modell |Beküldõ (helyenként link is) |Megjegyzések
|Apple |iMac G3 350 MHz |mailto:diskiller@diskiller.net[Martin Minkus] |Rage 128VR
|Apple |iMac G3 DV Special Edition |mailto:webmaster@machowto.com[David S. Besade] (http://people.freebsd.org/\~flz/local/dmesg.ppc[dmesg]) |Nincs
|Apple |iMac G3 Revision B |{grehan} |Rage 3D Pro 215GP, gyors. letiltva
|Apple |eMac 700 MHz |{grehan} |Nvidia GeForce2 MX
|Apple |Mac Mini G4 1.4 GHz |{arved} (http://people.freebsd.org/\~arved/stuff/minimac[dmesg]) |Nincs
|Apple |Powerbook G4 1.33 GHz |{grehan} |Nvidia GeForce G5200
|Apple |Aluminium Powerbook G4 1.5 GHz |mailto:toa@pop.agri.ch[Andreas Tobler] |Nincs
|Apple |PowerMac G5 | |FreeBSD 8.0
|Apple |iMac G5 | |FreeBSD 8.0
|Apple |Xserve G5 | |FreeBSD 8.1
|Apple |PowerMac G5 (2005 vége) | |FreeBSD 8.1
|===

'''''

[[list]]
== A FreeBSD/ppc levelezési lista

A feliratkozáshoz küldjünk egy levelet a `<freebsd-ppc-subscribe@FreeBSD.org>` címre, vagy használjuk a http://lists.FreeBSD.org/mailman/listinfo/freebsd-ppc[mailman webes felületét].

'''''

[[issues]]
== Ismert problémák

* A sysinstall nem tud rendesen lemezeket particionálni - helyette a gpart használatát javasoljuk.
* Az ATI kártyás gépek esetén vissza kell fogni az ofw syscons mûködéséhez kötõdõ ellenõrzéseket a hw.ofwfb.relax_mmap sysctl változó segítségével.
* A rendszertöltõben van egy olyan hiba, amely megakadályozza abban, hogy betöltsön egy alternatív rendszermagot, így a rendszermag tesztelése egy kissé kockázatos. Amikor a rendszertöltõ indul az Open Firmware promptból, adjunk meg egy nem lézõ, rendszermagot nem tartalmazó, vagy nem UFS partíciót:

....
0 > boot hd:loader hd:0
....

Ekkor be tudjuk állítani a currdev értékét, és manuálisan betölthet egy rendszermagot:

....
OK set currdev=hd:14
OK load /boot/kernel/kernel.save
....

'''''

[[doc]]
== Dokumentumok, segédeszközök

* http://e-www.motorola.com/brdata/PDFDB/docs/MPCFPE32B.pdf[PowerPC chip dokumentáció]
* http://www.firmworks.com/QuickRef.html[Open Firmware gyors referencia]
* http://developer.apple.com/technotes/tn/tn1061.html["TN1061: Fundamentals of Open Firmware, Part 1 - The User Interface"]
* http://developer.apple.com/technotes/tn/tn1062.html["TN1062: Fundamentals of Open Firmware, Part 2 - The Device Tree"]
* http://developer.apple.com/techpubs/hardware/hardware2.html[Apple hardverfejlesztõi dokumentációk]
* http://developer.apple.com/technotes/tn/tn2004.html["TN2004: Debugging Open Firmware Using Telnet"]
* http://developer.apple.com/technotes/tn/tn2023.html["TN2023: Open Firmware Ethernet Debugging II - Telnet Downloading"]
* http://developer.apple.com/technotes/tn/tn2001.html["TN2001: Running Files from a Hard Drive in Open Firmware"]
* http://sourceware.org/psim/[psim] - Egy PowerPC szimulátor, elérhetõ FreeBSD portként: http://www.freshports.org/?package=psim-freebsd[emulators/psim-freebsd]

[[links]]
== Egyéb linkek

* http://wiki.freebsd.org/moin.cgi/powerpc[A FreeBSD/ppc wiki oldala]
* http://lists.freebsd.org/pipermail/freebsd-ppc/2005-January/000814.html[Garance A. Drosehn leírása a FreeBSD-rõl Mac Minin]
* http://www.NetBSD.org/Ports/macppc/[NetBSD/macppc]
* http://www.OpenBSD.org/macppc.html[OpenBSD/macppc]
