# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/news/Makefile.inc,v 1.1 2000/11/10 17:04:51 phantom Exp $
# Original revision: 1.2

WEBBASE?=	/data/ru/news
DOC_PREFIX?=	${.CURDIR}/../../../..
