---
title: "Projet GNOME pour FreeBSD : FAQ GNOME 1.4"
sidenav: gnome
--- 

include::shared/fr/urls.adoc[]

= Projet GNOME pour FreeBSD : FAQ GNOME 1.4

== Sommaire

. <<q1,Comment obtenir GNOME pour FreeBSD ?>>
. <<q2,Le port de GNOME ne compile pas. Que faire ?>>
. <<q3,J'ai installé GNOME, mais il me manque l'application "bidule". Pourquoi ?>>
. <<q4,Comment garder à jour mes composants et applications GNOME ?>>
. <<q5,Quel est la différence entre GNOME et KDE ? Lequel est le meilleur ?>>
. <<q6,Où puis-je trouver d'autres thèmes pour GNOME ?>>
. <<q7,Quels sont les gestionnaires de fenêtres qui fonctionnent avec GNOME ?>>
. <<q8,Pourquoi je ne peux pas lancer d'applications Linux à partir du tableau de bord GNOME ?>>
. <<q9,Pourquoi GNOME est si énorme, lent et au fond inutile ?>>
. <<q10,Est-ce que GNOME supporte l'anti-aliasing pour les polices de caractères ?>>
. <<q11,Comment activer le support Java dans les navigateurs web Mozilla ou Galeon ?>>

== Texte complet

[[q1]]
*1.# Comment obtenir GNOME pour FreeBSD ?*

Il y a 2 manières d'installer GNOME sur FreeBSD. L'une est d'utiliser link:{handbook}#packages-using[les paquetages], l'autre est d'utiliser link:{handbook}#ports-using[les ports].

Pour installer GNOME à partir des paquetages, utilisez la commande :

`# pkg_add -r gnome`

Les derniers paquetages GNOME seront téléchargés depuis le site FTP FreeBSD et seront installés sur votre système.

Pour compiler et installer GNOME à partir des ports, utilisez tout d'abord link:{handbook}#cvsup[cvsup] pour avoir la toute dernière version des ports. Puis :

....
# cd /usr/ports/x11/gnome
# make clean
# make install clean
....

Après l'installation de GNOME, vous pouvez ajouter la ligne suivante dans le fichier `/etc/make.conf`:

....
WITH_GTK=yes
....

Ce n'est pas obligatoire, mais cela permettra à certains ports, comme Vim, d'utiliser la bibliothèque Gtk+.

La méthode recommandée pour l'installation de GNOME est celle des ports.

[[q2]]
*2.# Le port de GNOME ne compile pas. Que faire ?*

La majorité des problèmes de compilation de GNOME peut se résoudre en s'assurant que tous les composants nécessaires à GNOME sont <<q4[à jour]. Toutes les applications GNOME ont besoin des composants suivants pour la compilation :

....
pkg-config
glib
gettext
gtk+
ORBit
Imlib
esound
gnomelibs
gnomecore
....

Vérifier que tous ces composants sont à jour, et essayer à nouveau la compilation de GNOME ou de l'application GNOME. Vous pouvez éventuellement voir des erreurs du compilateur en rapport avec les pthreads (threads POSIX), comme par exemple :

....
undefined reference to 'strerror_r'    
....

Pour corriger ces erreurs liées aux threads, assurez-vous que les options suivantes sont dans le fichier de configuration de votre noyau :

....
options     _KPOSIX_PRIORITY_SCHEDULING    
....

Et assurez-vous, si vous suivez la branche -stable ou -current, que vous *n'avez pas* l'option `NOLIBC_R` dans le fichier `/etc/make.conf`. Si c'est le cas, supprimez la, puis recompilez et réinstallez le système ("make world").

Les ports tels que `devel/pth` et `devel/ngpt` peuvent également causer des problèmes liés aux pthreads lors de la compilation de GNOME. Si vous n'avez pas besoin de ces ports, il est recommandé de les supprimer.

Si malgré tout vous avez encore des problèmes, envoyez un courrier électronique à &email;@FreeBSD.org avec le détail des erreurs de compilation.

[[q3]]
*3.# 'ai installé GNOME, mais il me manque l'application "bidule". Pourquoi ?*

Seuls les composants principaux, et quelques extras, sont inclus dans paquetage `gnome`. Il existe un autre meta-port appelé `gnome-fifth-toe` qui inclue des applications GNOME plus populaires (et plus grosses). `gnome-fifth-toe` inclue Galeon, Pan, Gnumeric, AbiWord, GNUCash, Evolution, Gimp, Dia et plus encore.

Pour installer `gnome-fifth-toe` à partir des paquetages.

....
# pkg_add -r gnome-fifth-toe
....

Pour compiler `gnome-fifth-toe` à partir des ports :

....
# cd /usr/ports/x11/gnome-fifth-toe
# make clean
# make install clean
....

Une liste complète des applications GNOME portées sur est disponible link:../../ports/gnome.html[ici].

[[q4]]
*4.# Comment garder à jour mes composants et applications GNOME ?*

J'ai découvert que `/usr/ports/sysutils/portupgrade` fonctionne très bien. Par exemple :

`# portupgrade -r pkgconfig`

Cela mettra à jour pkgconfig et tous les autres ports qui en dépendent (s'ils ont besoin d'être mis à jour).

Cependant, il y a parfois de tels changements, qu'il devient nécessaire de faire d'abord un peu de nettoyage. Dans ce cas, la procédure suivante fonctionne dans la plupart des cas :

....
# pkg_delete -rf pkgconfig\*
# cd /usr/ports/x11/gnome
# make clean
# make install clean
....

Ces commandes supprimeront *tous* les composants et applications de GNOME 1 et 2 sur votre machine, et seul le bureau de GNOME 1 sera réinstallé. Attention, si vous suivez cette procédure, vous devrez réinstaller vos applications après avoir réinstallé le bureau. Heureusement, cette méthode extrême est rarement nécessaire.

[[q5]]
*5.# Quelle est la différence entre GNOME et KDE ? Lequel est le meilleur ?*

GNOME et KDE sont tous les deux des environnements de bureau. GNOME est basé sur la librairie GTK+ et est principalement écrit en C. Par contre, KDE est basé sur la librairie QT et est principalement écrit en C++.

Les deux environnements offrent une large variété d'applications depuis des gadgets et des jeux jusqu'à des suites complètes d'outils bureautiques. Les deux sont développés activement et disponibles sous FreeBSD. Si vous voulez décider lequel utiliser, essayez les deux, et choisissez celui que *vous* préférez.

Pour en savoir plus sur KDE sous FreeBSD, vous pouvez consulter http://freebsd.kde.org.

[[q6]]
*6.# Où puis-je trouver d'autres thèmes pour GNOME ?*

Si vous êtes fatigué des thèmes par défaut fournis avec GNOME, vous avez plusieurs options. Tout d'abord, la collection des ports FreeBSD contient une large collection de thèmes GTK pour GNOME. Pour les installer à partir des paquetages, utilisez la commande :

`# pkg_add -r gtk-engines-collection`

Pour installer les thèmes à partir des ports, utilisez les commandes :

....
# cd /usr/ports/x11-toolkits/gtk-engines-collection
# make clean
# make install clean
....

Si vous voulez encore plus de thèmes, consultez le site http://art.gnome.org/. Notez que vous devrez probablement installer `gtk-engines-collection` avant de pouvoir utiliser les thèmes.

[[q7]]
*7.# Quels sont les gestionnaires de fenêtres qui fonctionnent avec GNOME ?*

Le meta-port `gnome` installe par défaut le gestionnaire de fenêtres http://sawmill.sourceforge.net/[Sawfish]. Cependant, d'autres gestionnaires de fenêtres peuvent s'utiliser avec GNOME. Comme par exemple :

* http://www.enlightenment.org/pages/main.html[Enlightenment]
* http://www.fvwm.org/[FVWM2]
* http://www.windowmaker.org/[WindowMaker]
* http://www.afterstep.org/[Afterstep]
* http://www.icewm.org/[IceWM]
* http://www.xfce.org/[XFce]

[[q8]]
*8.# Pourquoi je ne peux pas lancer d'applications Linux à partir du tableau de bord GNOME ?*

La réponse courte est que vous le pouvez. Le problème est lié au fait que vous avez sans doute activé le "Launch Feedback" (xalf). xalf est un objet partagé FreeBSD et, en tant que tel, il ne peut être chargé par des applications Linux. Lorsque vous essayez de charger une application Linux, rien ne se passe, et des lignes comme ci-dessous apparaissent dans le fichier `~/.gnomerc-errors` ou sur la sortie standard :

....
/usr/local/Acrobat4/Reader/intellinux/bin/acroread: error in loading shared
libraries: /usr/X11R6/lib/libxalflaunch.so.0: ELF file OS ABI invalid.
....

Pour corriger ce problème, vous devez installer le port `linux-xalf`. Ce port (ou ce paquetage) installe la version Linux de `libxalflaunch.so.0` dans `/compat/linux/usr/X11R6/lib`, et sera utilisé à la place du binaire FreeBSD lors du lancement d'applications Linux. Vous pouvez éventuellement voir l'erreur suivante après avoir installé `linux-xalf` :

....
/usr/libexec/ld-elf.so.1: Shared object "libkrb.so.3" not found
....

Cette erreur est sans danger et peut être ignorée.

[[q9]]
*9.# Pourquoi GNOME est si énorme, lent et au fond inutile ?*

Cela dépend du point de vue. Bien sûr, GNOME et KDE sont encore loin d'être parfaits ou même d'être totalement achevés et ils peuvent difficilement être comparés aux logiciels commerciaux en terme de facilité d'utilisation. Mais, dans le même temps, c'est un grand pas vers la bonne direction. Il faut aussi noté que GNOME et KDE sont encore très jeunes et la situation ne peut que s'améliorer dans le futur (quelqu'un se rappelle-t'il quelle sorte de me..e était Windows 3.11 ?).

[[q10]]
*10.# Est-ce que GNOME supporte l'anti-aliasing pour les polices de caractères ?*

Oui ! Cependant, il y a 2 choses à faire. Tout d'abord, vous avez besoin de XFree86 4.0 ou supérieur (la version 4.1 ou supérieure est recommandée). Puis, vous avez besoin du port `x11/gdkxft`. C'est tout ! Vous n'avez pas besoin de recompiler vos applications GNOME.

Si vous rencontrez des problèmes, consultez le http://gdkxft.sourceforge.net/[site web gdkxft] ou envoyez un courrier électronique à &email;@FreeBSD.org.

Si vous avez des questions, vous pouvez les envoyer à &email;@FreeBSD.org.

[[q11]]
*11.# Comment activer le support Java dans les navigateurs web Mozilla ou Galeon ?*

Pour activer le support Java dans le navigateur web Mozilla vous devez installer le kit de développement Java à partir du port `java/jdk13` (version 1.3.1p6 ou supérieure nécessaire) et redémarrer le navigateur. Notez que si la version du paquetage Mozilla installé sur votre ordinateur est inférieure à la 0.9.8_2,1 vous avez également besoin d'utiliser la commande suivante afin de créer le lien symbolique nécessaire au fonctionnement du plugin Java :

....
# ln -sf /usr/local/jdk1.3.1/jre/plugin/i386/ns600/libjavaplugin_oji.so \
    /usr/X11R6/lib/mozilla/plugins/libjavaplugin_oji.so
....

Vous pouvez vérifier que Mozilla a bien pris en compte le plugin Java en sélectionnant _A propos des Plug-ins_ du menu _Aide_ après avoir redémarrer Mozilla. Vous devez voir /usr/local/jdk1.3.1/jre/plugin/i386/ns600/libjavaplugin_oji.so dans la liste des plugins disponibles, ce qui indique que le support Java est activé.

Si vous compilez Galeon avec la version complète de Mozilla, le plugin Java fonctionnera également pour ce navigateur. Assurez-vous simplement de cocher l'option _Activer Java_ dans le menu _Préférence_.
