---
title: "Projet GNOME pour FreeBSD : FAQ GNOME 2.2"
sidenav: gnome
--- 

include::shared/fr/urls.adoc[]

= Projet GNOME pour FreeBSD : FAQ GNOME 2.2

== Contenus

. <<q1,Comment installer GNOME 2.2 sur FreeBSD ?>>
. <<q2,Le port de GNOME 2.2 ne compile pas. Que dois-je faire ?>>
. <<q3,J'ai installé GNOME 2.2 mais il me manque l'application "truc". Que faire ?>>
. <<q4,Quel est le meilleur moyen de mettre à jour GNOME 1.4 vers GNOME 2 ?>>
. <<q5,Comment garder à jour les applications et les composants de GNOME 2.2 ?>>
. <<q6,Puis-je installer des applications GNOME 1.4 sous GNOME 2.2 et vice-versa ?>>
. <<q7,Où puis-je trouver plus de thèmes pour GNOME 2.2 ?>>
. <<q8,Quels gestionnaires de fenêtre fonctionnent correctement avec GNOME 2.2 ?>>
. <<q9,Est-ce que GNOME 2.2 supporte l'anti-aliasing pour les fontes ?>>
. <<q10,Comment contrôler quelles fontes utilisent l'anti-aliasing ?>>
. <<q11,Comment éditer mes menus GNOME 2 ?>>
. <<q12,Comment utiliser les paramètres de ressource GTK+ 2 pour les applications GTK+ 2 sans être dans l'environnement GNOME ?>>
. <<q13,Comment configurer les paramètres des applications GNOME 1.4 sous GNOME 2.2 ?>>

== Textes complets

[[q1]]
*1.# Comment installer GNOME 2.2 sur FreeBSD ?*

Il existe deux façons d'installer GNOME 2.2 sur FreeBSD. L'une d'elle est d'utiliser link:{handbook}#packages-using[les paquetages], et l'autre est d'utiliser link:{handbook}#ports-using[les ports]. Avant d'utiliser l'une ou l'autre de ces installations, vous devriez tout d'abord consulter les http://www.gnome.org/start/2.2/notes/[notes de version] de GNOME 2.2.

Pour installer GNOME 2.2 à partir des paquetages, utilisez la commande :

`# pkg_add -r gnome2`

Cela téléchargera les dernières versions des paquetages GNOME 2.2 depuis le site FTP FreeBSD et procèdera à leur installation sur votre système.

Pour compiler et installer GNOME 2.2 à partir des ports, vous devez d'abord mettre à jour via link:{handbook}#cvsup[cvsup] l'arbre des ports. Puis :

....
# cd /usr/ports/x11/gnome2
# make clean
# make install clean
....

Pour profiter au mieux de GNOME 2, vous devriez l'installer à partir des ports et ajouter les lignes suivantes à votre fichier `/etc/make.conf` :

....
WITH_FAM=   yes
WITH_LAME=  yes
....

`WITH_FAM` autorise le support du gestionnaire de modification de fichier ce qui permet à Nautilus de mettre à jour ses listes de fichiers en temps réel ainsi qu'aux composants GNOME de détecter les changements dans les fichiers de configuration sans avoir besoin de redémarrer GNOME. `WITH_LAME` ajoute le support du MP3, ce qui permet d'écouter des MP3s directement depuis Nautilus.

Ces options peuvent provoquer des erreurs de compilation sur certaines plates-formes, c'est pourquoi elles ne sont pas activées par défaut.

[[q2]]
*2.# Le port de GNOME 2.2 ne compile pas. Que dois-je faire ?*

La majorité des problèmes de compilation avec GNOME 2.2 peuvent être résolus en s'assurant que tous les composants nécessaires à GNOME 2.2 sont <<q5[à jour]. Vous pouvez avoir des erreurs de compilation liées aux pthreads (les threads POSIX) comme :

....
undefined reference to 'strerror_r'  
....

Pour corriger ces erreurs liées aux threads, assurez vous d'avoir ces options dans le fichier de configuration de votre noyau :

....
options     _KPOSIX_PRIORITY_SCHEDULING   
....

Et assurez-vous, si vous suivez la branche -stable ou -current, que vous n'avez *pas* l'option `NOLIBC_R` dans le fichier `/etc/make.conf`. Si vous l'avez, supprimez la et remettez à jour le système avec un "make world". Si vous avez toujours des problèmes, merci d'envoyer un courrier électronique à &email;@FreeBSD.org en indiquant les erreurs de compilation. Il est aussi utile d'inclure le fichier config.log du répertoire "work" du port.

Les ports tels que `devel/pth` et `devel/ngpt` peuvent aussi causer des problèmes liés aux pthreads lors de la compilation de GNOME 2.2. Si vous n'avez pas besoin d'avoir ces ports installés, il est recommandé de les supprimer.

[[q3]]
*3.# J'ai installé GNOME 2.2 mais il me manque l'application "truc". Que faire ?*

Seuls les composants principaux, et quelques extras, sont inclus dans le paquetage `gnome2`. Comme GNOME 2 est relativement récent, il n'y a pas encore beaucoup d'applications portées pour cette version. Au fur et à mesure que les applications seront disponibles, elles seront portées pour cette version. En attendant, vous pouvez toutefois faire fonctionner <<q6[les applications GNOME 1.4] sous GNOME 2.2.

De nombreuses applications qui ont déjà été portées sont inclues dans le méta-port `gnome2-fifth-toe`. `gnome2-fifth-toe` inclu les versions GNOME 2.2 de certaines applications GNOME 1.4. Attention, certaines de ces applications sont encore en cours de développement et peuvent être encore instables.

Pour installer `gnome2-fifth-toe` à partir des paquetages :

....
# pkg_add -r gnome2-fifth-toe    
....

Pour installer `gnome2-fifth-toe` à partir des ports :

....
# cd /usr/ports/x11/gnome2-fifth-toe
# make clean
# make install clean
....

[[q4]]
*4.# Quel est le meilleur moyen de mettre à jour GNOME 1.4 vers GNOME 2 ?*

A l'heure actuelle, le projet GNOME est encore très changeant. Beaucoup de travail reste à faire sur l'infrastructure des ports GNOME pour faire fonctionner correctement les choses. Cependant, si vous avez GNOME 1.4 et que vous voulez le mettre à jour avec GNOME 2.2, familiarisez-vous tout d'abord avec les http://www.gnome.org/start/2.0/installation.html#upgrading[official] instructions de mise à jour du site GNOME. Puis, assurez-vous que vos ports GNOME 1.4 sont bien à jour et supprimez les paquetages GNOME 1.4 suivants du système :

....
gnomecore
sawfish
gnomeapplets
gnomemedia
gtop
libgtop
nautilus
gedit
xalf
bugbuddy
gnomegames
gnomeutils
gdm
eog
ggv
....

Une fois que ces paquetages ont été supprimés, vous pouvez installer GNOME 2.2 en suivant les instructions données ci-dessus.

[[q5]]
*5.# Comment garder à jour les applications et les composants de GNOME 2.2 ?*

J'ai trouvé que `/usr/ports/sysutils/portupgrade` fonctionne très bien. Par exemple :

`# portupgrade -r pkgconfig`

Cela mettra à jour pkgconfig et tous les autres ports qui en dépendent (ceux qui ont besoin d'être mis à jour).

Toutefois, il y a parfois tellement de changements qu'il devient nécessaire de d'abord faire un peu de ménage. Dans ce cas, cela fonctionne la plupart du temps :

....
# pkg_delete -rf pkgconfig\*
# cd /usr/ports/x11/gnome2
# make clean
# make install clean
....

Ces commandes supprimeront *tous* les composants et applications de GNOME 1 et 2 de votre machine mais réinstalleront uniquement le bureau GNOME 2. Vous devez cependant savoir que, si vous suivez cette méthode, vous devrez réinstaller vos applications après la réinstallation du bureau. Heureusement, cette méthode "extrême" est rarement nécessaire.

[[q6]]
*6.# Puis-je installer des applications GNOME 1.4 sous GNOME 2.2 et vice-versa ?*

Bien sûr ! Actuellement, l'équipe de GNOME pour FreeBSD travaille sur la migration de tous les ports GNOME 1.4 vers la nouvelle infrastructure de compilation. Cette nouvelle infrastructure, appelée *GNOMENG*, permettra aux utilisateurs de GNOME 2 d'installer les ports GNOME 1.4 sans écraser leur bureau GNOME 2.

Avant d'installer un port GNOME 1.4 sous GNOME 2, consultez le fichier Makefile du port et vérifiez qu'il contient :

....
USE_GNOMENG=    yes
....

Si c'est bien le cas, vous pouvez sans problème installer ce port sous GNOME 2. Si le Makefile contient la ligne suivante, ne l'installez pas car il écraserait votre bureau GNOME 2 :

....
USE_GNOME=  yes
....

Dans ce cas, envoyez un courrier électronique à &email;@FreeBSD.org en mentionnant le nom du port et nous le convertirons pour qu'il utilise la nouvelle infrastructure. Vous pouvez aussi convertir vous-même le port et soumettre un PR.

*NOTE !* Vous *devez* avoir un répertoire `/usr/ports/Mk` à jour pour pouvoir utiliser le nouveau GNOMENG. Si vous n'avez pas un répertoire Mk à jour, vous écraserez votre bureau GNOME 2 même si USE_GNOMENG est défini. Pour mettre à jour votre répertoire Mk, assurez-vous que votre fichier de configuration cvsup pour les ports permet de récupérer le tag *ports-base*. C'est automatique si votre fichier contient le tag *ports-all*.

Pour faire fonctionner les applications GNOME 2.2 sous GNOME 1.4, vous devez vous assurez que vos composants GNOME 1.4 sont à jour puis installer le port `gnome2-devel`. Pour installer ce port, suivez la procédure suivante :

....
# cd /usr/ports/devel/gnome2-devel
# make clean
# make install
....

Après l'installtion du port `gnome2-devel`, vous pourrez installer les applications GNOME 2.2 *indépendantes du bureau* (par exemple `math/gcalctool`).

[[q7]]
*7.# Où puis-je trouver plus de thèmes pour GNOME 2.2 ?*

Le site web http://art.gnome.org[art.gnome.org] propose plusieurs thèmes GNOME. Cela inclue des thèmes gtk+-2.0, metacity, sawfish, nautilus, icon et gdm ainsi que quelques fonds d'écrans.

Un nouveau site de thèmes appelé http://www.themedepot.org[The Theme Depot] vient d'ouvrir. Ce site contient des thèmes pour GNOME 2 ainsi que pour KDE et quelques gestionnaires de fenêtres.

Un bon site pour trouver plusieurs icônes GNOME (certains classiques, d'autres nouveaux) est le site http://jimmac.musichall.cz/ikony.php3[Icons] de jimmac.

Consultez les instructions présentes sur les sites web pour savoir comment installer ces thèmes. Si vous avez envie de créer un port pour certains d'entre eux, vous êtes également plus que bienvenu ;-).

[[q8]]
*8.# Quels gestionnaires de fenêtre fonctionnent correctement avec GNOME 2.2 ?*

Le méta-port `gnome2` installe les gestionnaires de fenêtres metacity par défaut. Un autre gestionnaire de fenêtres très populaire et qui fonctionne très bien avec GNOME 2.2 est http://sawmill.sourceforge.net/[sawfish]. Sawfish est inclus dans le méta-port `x11/gnome2-fifth-toe`.

Pour passer de metacity à sawfish et inversement avec GNOME 2, vous devez utiliser les commandes suivantes :

....
killall metacity; sawfish &
gnome-session-save --gui
....

Le `gnome-session-save` est important. Sans cette commande, le gestionnaire de fenêtres retournera à celui configuré précédemment lors de la prochaine connexion. Pour faire le passage inverse, inversez simplement sawfish et metacity.

[[q9]]
*9.# Est-ce que GNOME 2.2 supporte l'anti-aliasing pour les fontes ?*

Oui ! L'anti-aliasing nécessite XFree86 4.x avec le support freetype2. Pour ajouter le support freetype2 à X, assurez-vous de charger les modules suivants dans votre fichier de configuration XF86Config (section Modules) :

....
Load    "freetype"
Load    "type1"
....

Puis, utilisez tout simplement l'applet de configuration "Fontes" dans Applications->Préférences Bureau. Si vous voulez un bon ensemble de fontes TrueType pour commencer, installez le port `x11-fonts/webfonts`.

Il arrive parfois qu'après avoir ajouter de nouvelles fontes au système, il soit nécessaire de les indiquer explicitement à fontconfig. Si vous constatez que les nouvelles fontes ne sont pas disponibles même après avoir redémarré GNOME 2, utilisez la commande suivante en tant que root.

....
# fc-cache -f -v 
....

Si vous avez des questions, vous pouvez les envoyer à &email;@FreeBSD.org.

[[q10]]
*10.# Comment contrôler quelles fontes utilisent l'anti-aliasing ?*

GNOME 2.2 utilise Xft2 et fontconfig pour gérer l'anti-aliasing. Fontconfig est un très puissant gestionnaire de configuration de fontes basé sur XML-based. Vous pouvez créer un fichier `~/.fonts.conf` qui contrôle virtuellement chaque aspect de fontconfig. Par exemple, si vous ne voulez pas l'anti-aliasing pour les fontes inférieures à 16 points, créez le fichier a `~/.fonts.conf` avec le contenu suivant :

....
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>

<match target="font">
        <test name="size" compare="less_eq">
                <double>16</double>
        </test>
        <edit name="antialias" mode="assign">
                <bool>false</bool>
        </edit>
</match>
</fontconfig>
....

Consultez fontconfig(3) pour plus d'informations.

[[q11]]
*11.# Comment éditer mes menus GNOME 2 ?*

Vous devez utiliser Nautilus pour éditer vos menus GNOME 2. Si vous voulez éditer n'importe quel autre menu que "Favoris", vous devez être root. Cette fonction nécessite GNOME 2.0.2 ou plus.

Pour éditer les menus, lancez Nautilus et entrez l'URL *applications:///*. A partir de là, vous devriez pouvoir éditer tout le menu.

[[q12]]
*12.# Comment utiliser les paramètres de ressource GTK+ 2 pour les applications GTK+ 2 sans être dans l'environnement GNOME ?*

Les applications GNOME 2 obtiennent leurs ressources GTK+ 2 à partir des thèmes et du moteur de thème correspondant. Si vous souhaitez plutôt utiliser vos applications GTK+ 2 dans un environnement non-GNOME, vous devez alors créer un fichier `~/.gtkrc-2.0`. Pour la plus grande part, vous pouvez transférer vos paramètres à partir de votre fichier `~/.gtkrc` (utilisé pour GTK+ 1.2) avec seulement quelques difficultés mineures.

. Si vous avez des références à un moteur de thème, vous devrez vous assurer qu'il existe un moteur de thème GTK+ 2 correspondant. Sinon, supprimez les entrées concernant ce moteur.
. L'indication de la fonte par défaut doit se située en dehors des bloques `style` et doit être spécifiée avec le mot clef `gtk-font-name`. Par exemple :
+
....
gtk-font-name = "Verdana 11"
....

[[q13]]
*13.# Comment configurer les paramètres des applications GNOME 1.4 sous GNOME 2.2 ?*

Installez `sysutils/gnomecontrolcenter`, puis lancez `gnomecc` à partir de la ligne de commande pour démarrer le centre de contrôle de GNOME 1.4. A noter que, depuis Evolution-1.2.0_3 et gnomepilot-0.1.69_1, `gnomecontrolcenter` est automatiquement installé car il est nécessaire pour la configuration des communications avec Palm Pilot.
