#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
# $FreeBSDnl: nl_NL.ISO8859-1/books/handbook/network-servers/Makefile,v 1.2 2004/12/26 21:39:15 remko Exp $
#
# %SOURCE%	en_US.ISO8859-1/books/handbook/network-servers/Makefile
# %SRCID%	1.1
#

CHAPTERS= 	network-servers/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
