---
title: Kapitel 6. Desktop-Anwendungen
part: Teil II. Oft benutzte Funktionen
prev: books/handbook/partii
next: books/handbook/multimedia
---

[[desktop]]
= Desktop-Anwendungen
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:table-caption: Tabelle
:figure-caption: Abbildung
:example-caption: Beispiel
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 6

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/de/mailing-lists.adoc[]
include::shared/de/teams.adoc[]
include::shared/de/urls.adoc[]

toc::[]

[[desktop-synopsis]]
== Übersicht

Obwohl FreeBSD wegen seiner Leistung und Stabilität vor allem auf Serversystemen sehr beliebt ist, so ist es auch für den täglichen Einsatz als Desktop geeignet. Mit über {numports} Anwendungen, die als Pakete oder Ports vorliegen, ist es leicht einen individuellen Desktop zu bauen, auf dem eine Vielzahl von Desktop-Anwendungen laufen. Dieses Kapitel zeigt, wie Sie die zahlreichen Desktop-Anwendungen, wie Web-Browser, Office-Pakete, Dokumentbetrachter und Finanzsoftware, installieren können.

[NOTE]
====
Benutzer die es vorziehen eine vorkonfigurierte Desktop-Version von FreeBSD zu installieren, anstatt das System von Grund auf zu konfigurieren, sollten sich https://www.furybsd.org[FuryBSD], https://ghostbsd.org[GhostBSD] oder https://www.midnightbsd.org[MidnightBSD] ansehen.
====

Bevor Sie dieses Kapitel lesen, sollten Sie wissen:

* wie zusätzliche Anwendungen als Paket oder aus der Ports-Sammlung installiert werden. Dies wird in crossref:ports[ports,Installieren von Anwendungen: Pakete und Ports] beschrieben.
* wie X und ein Window-Manager installiert wird. Dies wird in crossref:x11[x11,Das X-Window-System] beschrieben.

Informationen zur Konfiguration von Multimedia-Anwendungen finden Sie in crossref:multimedia[multimedia,Multimedia].

[[desktop-browsers]]
== Browser

FreeBSD besitzt keinen vorinstallierten Browser, stattdessen enthält das https://www.FreeBSD.org/ports/[www]-Verzeichnis der Ports-Sammlung viele Browser, die als Paket oder aus der Ports-Sammlung installiert werden können.

Die Desktop-Umgebungen KDE und GNOME verfügen über eigene HTML-Browser. Weitere Informationen zur Einrichtung dieser Umgebungen finden Sie in crossref:x11[x11-wm,“Grafische Oberflächen”].

Besonders schlanke Browser sind package:www/dillo2[], package:www/links[] und package:www/w3m[].

Dieser Abschnitt demonstriert, wie die folgenden gängigen Webbrowser installiert werden, sowie den Ressourcenbedarf, den Installationsaufwand beim Übersetzen des Ports, oder ob die Anwendung wichtige Abhängigkeiten benötigt.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Anwendung
| Ressourcenbedarf
| Installationsaufwand aus den Ports
| Anmerkungen

|Firefox
|mittel
|hoch
|FreeBSD, Linux(R) und lokalisierte Versionen sind verfügbar

|Konqueror
|mittel
|hoch
|Benötigt KDE-Biliotheken

|Chromium
|mittel
|hoch
|Benötigt Gtk+
|===

=== Firefox

Firefox ist ein Open-Source Browser. Er bietet eine dem HTML-Standard konforme Anzeige, Browserfenster als Tabs, Blockierung von Pop-up-Fenstern, Erweiterungen, verbesserte Sicherheit und mehr. Firefox basiert auf der Mozilla Codebasis.

Installieren Sie das Paket der aktuellen Release-Version von Firefox:

[source,bash]
....
# pkg install firefox
....

Um stattdessen die Extended Support Release (ESR) Version zu installieren, benutzen Sie:

[source,bash]
....
# pkg install firefox-esr
....

Alternativ kann auch die Ports-Sammlung verwendet werden, um die gewünschte Version von Firefox aus dem Quellcode zu installieren. Dieses Beispiel baut package:www/firefox[], wobei sich `firefox` durch die ESR oder die lokalisierte Version ersetzen lässt.

[source,bash]
....
# cd /usr/ports/www/firefox
# make install clean
....

=== Konqueror

Konqueror ist mehr als nur ein Webbrowser, da es ebenfalls Dateimanager und Multimedia-Betrachter ist. Es unterstützt sowohl WebKit als auch sein eigenes KHTML. WebKit wird von vielen modernen Browsern verwendet, einschließlich Chromium.

Das Konqueror-Paket wird wie folgt installiert:

[source,bash]
....
# pkg install konqueror
....

Alternativ können Sie den Port installieren:

[source,bash]
....
# cd /usr/ports/www/konqueror
# make install clean
....

=== Chromium

Chromium ist ein quelloffenes Browserprojekt mit dem Ziel ein sicheres, schnelleres und stabileres Surferlebnis im Web zu ermöglichen. Chromium ermöglicht surfen mit Tabs, Blockieren von Pop-Ups, Erweiterungen und vieles mehr. Chromium ist das Open Source Projekt, welches auf dem Google Chrome Webbrowser basiert.

Chromium kann als Paket durch die Eingabe des folgenden Befehls installiert werden:

[source,bash]
....
# pkg install chromium
....

Als Alternative kann Chromium aus dem Quellcode durch die Ports Collection übersetzt werden:

[source,bash]
....
# cd /usr/ports/www/chromium
# make install clean
....

[NOTE]
====
Die ausführbare Datei für Chromium ist [.filename]#/usr/local/bin/chrome# und nicht [.filename]#/usr/local/bin/chromium#.
====

[[desktop-productivity]]
== Büroanwendungen

Neue Benutzer suchen oft ein komplettes Office-Paket oder eine leicht zu bedienende Textverarbeitung. Einige crossref:x11[x11-wm,graphische Oberflächen] wie KDE enthalten zwar ein Office-Paket, diese werden unter FreeBSD jedoch nicht standardmäßig installiert. Unabhängig von der installierten graphischen Oberfläche können diverse Office-Pakete jederzeit installiert werden.

Dieser Abschnitt demonstriert, wie die folgenden gängigen Büroanwendungen installiert werden, sowie den Ressourcenbedarf, den Installationsaufwand beim Übersetzen des Ports, oder ob die Anwendung wichtige Abhängigkeiten benötigt.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Anwendung
| Ressourcenbedarf
| Installationsaufwand aus den Ports
| wichtige Abhängigkeiten

|Calligra
|niedrig
|hoch
|KDE

|AbiWord
|niedrig
|niedrig
|Gtk+ oder GNOME

|The Gimp
|niedrig
|hoch
|Gtk+

|Apache OpenOffice
|hoch
|enorm
|JDK(TM) und Mozilla

|LibreOffice
|etwas hoch
|enorm
|Gtk+, KDE/ GNOME oder JDK(TM)
|===

=== Calligra

Die KDE-Gemeinschaft stellt ein Office-Paket bereit, das auch separat von KDE eingesetzt werden kann. Calligra umfasst Standardkomponenten, die auch in anderen Office-Paketen enthalten sind. Words ist die Textverarbeitung, Sheets die Tabellenkalkulation, mit Stage werden Präsentationen erstellt und Karbon ist ein Zeichenprogramm.

In FreeBSD kann package:editors/calligra[] als Paket oder Port installiert werden. Um das Paket zu installieren, geben Sie folgendes ein:

[source,bash]
....
# pkg install calligra
....

Wenn das Paket nicht verfügbar ist, benutzen Sie stattdessen die Ports-Sammlung:

[source,bash]
....
# cd /usr/ports/editors/calligra
# make install clean
....

=== AbiWord

AbiWord ist eine freie Textverarbeitung, die dem Erscheinungsbild von Microsoft(R) Word ähnlich ist. Das Programm ist schnell, besitzt viele Funktionen und ist benutzerfreundlich.

AbiWord kann viele Dateiformate importieren oder exportieren, unter anderem auch propietäre wie Microsoft(R) [.filename]#.rtf#.

Das AbiWord-Paket installieren Sie wie folgt:

[source,bash]
....
# pkg install abiword
....

Sollte das Paket nicht zur Verfügung stehen, kann es über die Ports-Sammlung installiert werden:

[source,bash]
....
# cd /usr/ports/editors/abiword
# make install clean
....

=== The GIMP

The GIMP ist ein ausgereiftes Bildverarbeitungsprogramm mit dem Bilder erstellt oder retuschiert werden können. Es kann sowohl als einfaches Zeichenprogramm oder zum retuschieren von Fotografien benutzt werden. Das Programm besitzt eine eingebaute Skriptsprache und es existieren sehr viele Plugins. The GIMP kann zahlreiche Formate lesen und speichern und stellt Schnittstellen zu Scannern und Tablets zur Verfügung.

Um das Paket zu installieren, geben Sie ein:

[source,bash]
....
# pkg install gimp
....

Benutzen Sie alternativ die Ports-Sammlung:

[source,bash]
....
# cd /usr/ports/graphics/gimp
# make install clean
....

Die Kategorie _graphics_ (https://www.FreeBSD.org/ports/graphics.html[freebsd.org/ports/graphics.html]) der Ports-Sammlung enthält für The Gimp verschiedene Plugins, Hilfedateien und Handbücher.

=== Apache OpenOffice

Apache OpenOffice ist eine Open Source Büroanwendung, die unter Leitung der Apache Software Foundation weiterentwickelt wird. Es enthält die typischen Anwendungen eines Office-Pakets: Textverarbeitung, Tabellenkalkulation, Präsentation und ein Zeichenprogramm. Die Bedienung gleicht anderen Office-Paketen und das Programm kann zahlreiche Dateiformate importieren und exportieren. Es gibt lokalisierte Versionen mit angepassten Menüs, Rechtschreibkontrollen und Wörterbüchern.

Die Textverarbeitung von Apache OpenOffice speichert Dateien im XML-Format. Dadurch wird die Verwendbarkeit der Dateien auf anderen Systemen erhöht und die Handhabung der Daten vereinfacht. Die Tabellenkalkulation besitzt eine Makrosprache und eine Schnittstelle zu Datenbanken. Apache OpenOffice läuft stabil auf Windows(R), Solaris(TM), Linux(R), FreeBSD und Mac OS(R) X. Weitere Informationen über Apache OpenOffice finden Sie auf http://www.openoffice.org/[openoffice.org]. Spezifische Informationen für FreeBSD finden Sie auf http://porting.openoffice.org/freebsd/[porting.openoffice.org/freebsd/].

Apache OpenOffice installieren Sie wie folgt:

[source,bash]
....
# pkg install apache-openoffice
....

Nachdem das Paket installiert ist, geben Sie folgenden ein, um Apache OpenOffice zu starten:

[source,bash]
....
% openoffice-X.Y.Z
....

wobei _X.Y.Z_ die Versionsnummer von Apache OpenOffice darstellt. Nach dem ersten Start werden einige Fragen gestellt. Außerdem wird im Heimatverzeichnis des Benutzers ein Verzeichnis [.filename]#.openoffice.org# angelegt.

Falls das gewünschte Apache OpenOffice-Paket nicht verfügbar ist, kann immer noch der Port übersetzt werden. Es erfordert jedoch eine Menge Plattenplatz und ziemlich viel Zeit um die Quellen zu übersetzten.

[source,bash]
....
# cd /usr/ports/editors/openoffice-4
# make install clean
....

[NOTE]
====
Um eine lokalisierte Version zu bauen, ersetzen Sie den letzten Befehl durch:

[source,bash]
....
# make LOCALIZED_LANG=Ihre_Sprache install clean
....

Ersetzen Sie _Ihre_Sprache_ durch den korrekten ISO-Code. Eine Liste der unterstützten Codes steht in [.filename]#files/Makefile.localized#, die sich im Portsverzeichnis befindet.
====

=== LibreOffice

LibreOffice ist ein frei verfügbares Office-Paket, welches von http://www.documentfoundation.org/[documentfoundation.org] entwickelt wird. Es mit anderen großen Office-Paketen kompatibel und für eine Vielzahl von Plattformen erhältlich. Es ist ein Fork von Apache OpenOffice unter neuem Namen, das alle Anwendungen in einem kompletten Office-Paket enthält: Textverarbeitung, Tabellenkalkulation, Präsentationsmanager, Zeichenprogramm, Datenbankmanagementprogramm und ein Werkzeug zum Erstellen und Bearbeiten von mathematischen Formeln. Das Programm steht in verschiedenen Sprachen zur Verfügung, und die Internationalisierung wurde auf die Oberfläche, Rechtschreibkorrektur und die Wörterbücher ausgeweitet.

Das Textverarbeitungsprogramm von LibreOffice benutzt ein natives XML-Dateiformat für erhöhte Portabilität und Flexibilität. Die Tabellenkalkulation enthält eine Makrosprache und kann mit externen Datenbanken Verbindungen herstellen. LibreOffice ist stabil und läuft nativ auf Windows(R), Linux(R), FreeBSD und Mac OS(R) X. Weitere Informationen zu LibreOffice finden Sie unter http://www.libreoffice.org/[libreoffice.org].

Um die englische Version von LibreOffice als Paket zu installieren, geben Sie folgenden Befehl ein:

[source,bash]
....
# pkg install libreoffice
....

Die Kategorie _editors_ (https://www.FreeBSD.org/ports/[freebsd.org/ports/]) der Ports-Sammlung enthält viele Lokalisierungen für LibreOffice. Wenn Sie ein lokalisiertes Paket installieren, ersetzen Sie `libreoffice` durch den Namen des lokalisierten Pakets.

Wenn das Paket installiert ist, geben Sie folgendes Kommando ein, um LibreOffice zu starten:

[source,bash]
....
% libreoffice
....

Während des ersten Starts werden einige Fragen gestellt. Außerdem wird im Heimatverzeichinis des Benutzers ein Verzeichnis [.filename]#.libreoffice# angelegt.

Falls das gewünschte LibreOffice-Paket nicht verfügbar ist, kann immer noch der Port übersetzt werden. Es erfordert jedoch eine Menge Plattenplatz und ziemlich viel Zeit um die Quellen zu übersetzten. Dieses Beispiel übersetzt die englische Version:

[source,bash]
....
# cd /usr/ports/editors/libreoffice
# make install clean
....

[NOTE]
====
Um eine lokalisierte Version zu bauen, wechseln Sie mit `cd` in das Portverzeichnis der gewünschten Sprache. Unterstützte Sprachen finden Sie in der Kategorie _editors_ (https://www.FreeBSD.org/ports/[ freebsd.org/ports/]) der Ports-Sammlung.
====

[[desktop-viewers]]
== Anzeigen von Dokumenten

Einige neuere Dokumentformate, die sich aktuell großer Beliebtheit erfreuen, können Sie sich mit den im Basissystem enthaltenen Programmen möglicherweise nicht ansehen. Dieser Abschnitt zeigt, wie Sie die folgenden Dokumentbetrachter installieren können:

Die nachstehenden Anwendungen werden behandelt:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Anwendung
| Ressourcenbedarf
| Installationsaufwand aus den Ports
| wichtige Abhängigkeiten

|Xpdf
|niedrig
|niedrig
|FreeType

|gv
|niedrig
|niedrig
|Xaw3d

|Geeqie
|niedrig
|niedrig
|Gtk+ oder GNOME

|ePDFView
|niedrig
|niedrig
|Gtk+

|Okular
|niedrig
|hoch
|KDE
|===

=== Xpdf

Für Benutzer, die einen schnellen PDF-Betrachter bevorzugen, bietet Xpdf eine schlanke und effiziente Alternative, die wenig Ressourcen benötigt. Da das Programm die Standard X-Zeichensätze benutzt, ist es nicht auf andere Toolkits angewiesen.

Um das Xpdf-Paket zu installieren, geben Sie folgendes ein:

[source,bash]
....
# pkg install xpdf
....

Wenn das Paket nicht verfügbar ist, benutzen Sie die Ports-Sammlung:

[source,bash]
....
# cd /usr/ports/graphics/xpdf
# make install clean
....

Starten Sie nach der Installation `xpdf` und aktivieren Sie das Menü mit der rechten Maustaste.

=== gv

gv kann PostScript(R)- und PDF-Dokumente anzeigen. Es stammt von ghostview ab, hat aber wegen der Xaw3d-Bibliothek eine schönere Benutzeroberfläche. gv besitzt viele konfigurierbare Funktionen, wie z. B. Ausrichtung, Papiergröße, Skalierung und Kantenglättung (Anti-Aliasing). Fast jede Operation kann sowohl mit der Tastatur als auch mit der Maus durchgeführt werden.

Installieren Sie das gv-Paket wie folgt:

[source,bash]
....
# pkg install gv
....

Benutzen Sie die Ports-Sammlung, wenn das Paket nicht zur Verfügung steht:

[source,bash]
....
# cd /usr/ports/print/gv
# make install clean
....

=== Geeqie

Geeqie ist ein Fork des nicht mehr betreuten GQview Projekts, mit dem Ziel die Entwicklung weiter voranzutreiben und bestehende Fehlerkorrekturen zu integrieren. Mit Geeqie lassen sich Bilder verwalten. Es kann unter anderem Bilder anzeigen, einen externen Editor starten und eine Vorschau (thumbnail) erzeugen. Zudem beherrscht Geeqie einen Diashow-Modus und einige grundlegende Dateioperationen, was die Verwaltung von Bildern und das auffinden von doppelten Dateien erleichtert. Geeqie unterstützt Vollbild-Ansicht und Internationalisierung.

Um das Geeqie-Paket zu installieren, geben Sie folgendes ein:

[source,bash]
....
# pkg install geeqie
....

Wenn das Paket nicht verfügbar ist, benutzen Sie die Ports-Sammlung:

[source,bash]
....
# cd /usr/ports/graphics/geeqie
# make install clean
....

=== ePDFView

ePDFView ist ein leichtgewichtiger PDF-Betrachter, der nur die Gtk+- und Poppler-Bibliotheken benötigt. Es befindet sich derzeit noch in Entwicklung, kann aber bereits die meisten PDF-Dateien (auch verschlüsselte) öffnen, speichern und über CUPS drucken.

Um das Paket ePDFView zu installieren, geben Sie folgendes ein:

[source,bash]
....
# pkg install epdfview
....

Benutzen Sie die Ports-Sammlung, falls das Paket nicht verfügbar ist:

[source,bash]
....
# cd /usr/ports/graphics/epdfview
# make install clean
....

=== Okular

Okular ist ein universeller Dokumentbetrachter der auf KPDF für KDE basiert. Es kann die meisten Formate öffnen, einschließlich PDF, PostScript(R), DjVu, CHM, XPS und ePub.

Um das Paket Okular zu installieren, geben Sie folgendes ein:

[source,bash]
....
# pkg install okular
....

Benutzen Sie die Ports-Sammlung, falls das Paket nicht verfügbar ist:

[source,bash]
....
# cd /usr/ports/graphics/okular
# make install clean
....

[[desktop-finance]]
== Finanzsoftware

Zur Verwaltung der persönlichen Finanzen können einige leistungsfähige und einfach zu bedienende Anwendungen installiert werden. Einige von ihnen unterstützen verbreitete Formate, darunter Dateiformate, die von Quicken und Excel verwendet werden.

Dieser Abschnitt behandelt die folgenden Anwendungen:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Anwendung
| Ressourcenbedarf
| Installationsaufwand aus den Ports
| wichtige Abhängigkeiten

|GnuCash
|niedrig
|hoch
|GNOME

|Gnumeric
|niedrig
|hoch
|GNOME

|KMyMoney
|niedrig
|hoch
|KDE
|===

=== GnuCash

GnuCash ist Teil des GNOME-Projekts, mit dem Ziel, leicht zu bedienende und leistungsfähige Anwendungen bereitzustellen. Mit GnuCash können Einnahmen und Ausgaben, Bankkonten und Wertpapiere verwaltet werden. Das Programm ist leicht zu bedienen und genügt dennoch hohen Ansprüchen.

GnuCash stellt ein Register, ähnlich dem in einem Scheckheft und ein hierarchisches System von Konten zur Verfügung. Eine Transaktion kann in einzelne Teile aufgespaltet werden. GnuCash kann Quicken-Dateien (QIF) importieren und einbinden. Weiterhin unterstützt das Programm die meisten internationalen Formate für Zeitangaben und Währungen. Die Bedienung des Programms kann durch zahlreiche Tastenkombinationen und dem automatischen Vervollständigen von Eingaben beschleunigt werden.

Das GnuCash-Paket installieren Sie wie folgt:

[source,bash]
....
# pkg install gnucash
....

Wenn das Paket nicht zur Verfügung steht, benutzen Sie die Ports-Sammlung:

[source,bash]
....
# cd /usr/ports/finance/gnucash
# make install clean
....

=== Gnumeric

Gnumeric ist eine Tabellenkalkulation, die von der GNOME-Gemeinschaft entwickelt wird. Das Programm kann Eingaben anhand des Zellenformats oder einer Folge von Eingaben vervollständigen. Dateien verbreiteter Formate, wie die von Excel, Lotus 1-2-3 oder Quattro Pro lassen sich importieren. Es besitzt viele eingebaute Funktionen und Zellenformate, darunter die üblichen wie Zahl, Währung, Datum, Zeit, und viele weitere.

Installieren Sie das Gnumeric-Paket mit folgendem Kommando:

[source,bash]
....
# pkg install gnumeric
....

Wenn das Paket nicht zur Verfügung steht, benutzen Sie die Ports-Sammlung:

[source,bash]
....
# cd /usr/ports/math/gnumeric
# make install clean
....

=== KMyMoney

KMyMoney ist ein Programm zur Verwaltung der persönlichen Finanzen, das von der KDE-Gemeinschaft entwickelt wird. KMyMoney hat das Ziel, wichtige Funktionen zu bieten, die auch von kommerziellen Programmen zur Verwaltung der persönlichen Finanzen unterstützt werden. Zudem zählen eine einfache Bedienung sowie korrekte doppelte Buchführung zu den herausragenden Fähigkeiten dieses Programms. KMyMoney unterstützt den Import von Datendateien im Format Quicken (QIF), kann Investionen verfolgen, unterstützt verschiedene Währungen und bietet umfangreiche Reportmöglichkeiten.

Um das Paket KMyMoney zu installieren, geben Sie folgendes ein:

[source,bash]
....
# pkg install kmymoney-kde4
....

Sollte das Paket nicht verfügbar sein, benutzen Sie die Ports-Sammlung:

[source,bash]
....
# cd /usr/ports/finance/kmymoney2-kde4
# make install clean
....
