#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/internal/Makefile,v 1.11 2006/02/10 12:57:39 marck Exp $
#
# Original revision: 1.44
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	photos.xml
DOCS+=	internal.xml
DOCS+= 	about.xml
DOCS+= 	machines.xml
DOCS+= 	mirror.xml
DOCS+=	new-account.xml
DOCS+=	statistic.xml
DOCS+= 	developer.xml
DOCS+=	bylaws.xml
DOCS+=  releng.xml
DOCS+=	expire-bits.xml
DOCS+=	core-vote.xml
DOCS+=	doceng.xml
DOCS+=	rtp.xml
DOCS+=	policies.xml
DOCS+=	fortunes.xml

INDEXLINK=	internal.html

DATA+=	README.mirror

.include "${DOC_PREFIX}/share/mk/web.site.mk"
