# $FreeBSD: doc/es_ES.ISO8859-1/FAQ/Makefile,v 1.6 1999/09/06 06:53:13 peter Exp $

.NOTPARALLEL: 

DOC=    FAQ
VOLUME=	faq
DOCDIR= /usr/local/share/doc/fdp/es_ES.ISO8859-1/books
FORMATS?= html roff
SGMLOPTS+=-links

SRCS= FAQ.sgml acknowledgments.sgml admin.sgml applications.sgml
SRCS+= commercial.sgml hackers.sgml hardware.sgml install.sgml
SRCS+= kernelconfig.sgml misc.sgml network.sgml preface.sgml
SRCS+=	serial.sgml troubleshoot.sgml x.sgml

.include <bsd.sgml.mk>
