# $Id: Makefile,v 1.2 1998-10-07 02:54:53 jkh Exp $

SGMLOPTS=-links
DOC=	FAQ
DOCDIR=	${SHAREDIR}/doc/es
SRCS= FAQ.sgml acknowledgments.sgml admin.sgml applications.sgml
SRCS+= commercial.sgml hackers.sgml hardware.sgml install.sgml
SRCS+= kernelconfig.sgml misc.sgml network.sgml preface.sgml
SRCS+=	serial.sgml troubleshoot.sgml x.sgml

.include <bsd.sgml.mk>
