# $Id: Makefile,v 1.3 1998-11-26 22:33:32 nik Exp $

.NOTPARALLEL: 

SGMLOPTS=-links
DOC=	FAQ
SRCS= FAQ.sgml acknowledgments.sgml admin.sgml applications.sgml
SRCS+= commercial.sgml hackers.sgml hardware.sgml install.sgml
SRCS+= kernelconfig.sgml misc.sgml network.sgml preface.sgml
SRCS+=	serial.sgml troubleshoot.sgml x.sgml

.include <bsd.sgml.mk>
