---
title: "Проект FreeBSD CVSweb"
sidenav: support
---

include::shared/ru/urls.adoc[]

= Проект FreeBSD CVSweb

== Содержание

* <<about,Что такое CVSweb?>>
* <<downloads,Файлы для сгрузки>>
* <<resources,Ресурсы>>

[[about]]
== Что такое CVSweb?

CVSweb представляет собой Web-интерфейс для CVS-хранилищ, при помощи которого вы можете просматривать в вашем браузере файловую иерархию и историю изменений любого файла, которые представлены в весьма удобном виде.

CVSweb первоначально создал &a.fenner; для Проекта FreeBSD, и он получил широкое распространение среди разработчиков программного обеспечения в силу своего удобства использования.

Пакет FreeBSD-CVSweb, который раньше назывался knu-CVSweb, является улучшенной версией CVSweb, основанной на версии CVSweb от Henner Zeller, которая, в свою очередь, является расширенной версией оригинального CVSweb. &a.knu; внёс в эту версию множество улучшений, исправлений и усовершенствований, в том числе касающихся информационной безопасности, и предоставил её для использования авторам. Пакет FreeBSD-CVSweb сейчас поддерживает &a.scop;.

FreeBSD-CVSweb распространяется свободно на условиях http://www.opensource.org/licenses/bsd-license.html[Лицензии BSD]. На данный момент этот пакет используется в таких проектах, как http://cvsweb.freebsd.org/[FreeBSD], http://cvsweb.netbsd.org/[NetBSD], http://www.ruby-lang.org/cgi-bin/cvsweb.cgi/[Ruby].

'''''

[[downloads]]
== Файлы для сгрузки

Сгрузите tar-архив с указанных ниже сайтов. Последним стабильным релизом является *3.0.5* (выпущен 2005-01-22), для просмотра изменений посмотрите файлы http://www.FreeBSD.org/cgi/cvsweb.cgi/projects/cvsweb/NEWS?rev=1.44&content-type=text/x-cvsweb-markup[NEWS] и http://www.FreeBSD.org/cgi/cvsweb.cgi/projects/cvsweb/ChangeLog?rev=1.188&content-type=text/x-cvsweb-markup[ChangeLog].

* ftp://ftp.FreeBSD.org/pub/FreeBSD/ports/local-distfiles/scop/
* http://people.FreeBSD.org/~scop/cvsweb/
* Прочтите документ FreeBSD link:{handbook}#mirrors-ftp[Серверы FTP] для получения информации о зеркалирующих сайтах.

В дистрибутивных каталогах также находятся старые версии. Рекомендуется обновление до 3.x, но если вы ограничены Perl старше 5.6, используйте версию 2.0.x.

Готовый к использованию в виде пакаджа пакет FreeBSD-CVSweb включен в состав дистрибутивов нескольких операционных систем:

* link:../ports/[Порт] http://www.FreeBSD.org/[FreeBSD] (в devel/cvsweb3 находится версия 3.x, а в devel/cvsweb размещена версия 2.x)
* Пакет http://www.netbsd.org/[NetBSD] (www/cvsweb)
* Порт http://www.openbsd.org/[OpenBSD] (devel/cvsweb)
* http://www.debian.org/[Debian GNU/Linux] (testing и unstable)
* http://fedora.redhat.com/projects/extras/[Fedora Extras]

'''''

[[resources]]
== Ресурсы

Список рассылки проекта:::
freebsd-cvsweb@FreeBSD.org представляет собой список рассылки для обсуждения хода разработки FreeBSD-CVSweb. Приветствуются патчи, сообщения об ошибках и просьбы о добавлениях новых возможностей. Для подключения к списку рассылки следуйте инструкциям, помещённым в link:{handbook}#ERESOURCES-SUBSCRIBE[Руководство FreeBSD]. Доступны также http://lists.FreeBSD.org/pipermail/freebsd-cvsweb/[Архивы списков рассылки].
CVS-хранилище::
FreeBSD-CVSweb доступен через link:{handbook}#anoncvs[общедоступный pserver для CVS]. Модуль имеет имя `/projects/cvsweb`. Текущей стабильной веткой является `MAIN`, ветка `rel-2_0-branch` содержит старую версию.
CVSweb в CVSweb::
Вы можете просмотреть исходный код FreeBSD-CVSweb при помощи самого этого пакета по адресу http://www.FreeBSD.org/cgi/cvsweb.cgi/projects/cvsweb/.
