#
# $FreeBSD$
# $FreeBSDes: doc/es_ES.ISO8859-1/articles/problem-reports/Makefile,v 1.1 2004/10/08 23:06:08 carvay Exp $
#
# Article: Writing FreeBSD Problem Reports

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
