---
title: Manuale di FreeBSD
authors:
  - author: The FreeBSD Italian Documentation Project
copyright: 1995-2020 The FreeBSD Italian Documentation Project
releaseinfo: "$FreeBSD$" 
trademarks: ["freebsd", "3com", "3ware", "arm", "adaptec", "adobe", "apple", "corel", "creative", "cvsup", "heidelberger", "ibm", "ieee", "intel", "intuit", "linux", "lsilogic", "m-systems", "macromedia", "microsoft", "netscape", "nexthop", "opengroup", "oracle", "powerquest", "realnetworks", "redhat", "sap", "sun", "symantec", "themathworks", "thomson", "usrobotics", "vmware", "waterloomaple", "wolframresearch", "xfree86", "xiph", "general"] 
next: books/handbook/preface
---

= Manuale di FreeBSD
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:toc-title: Indice
:part-signifier: Parte
:chapter-signifier: Capitolo
:appendix-caption: Appendice
:table-caption: Tabella
:figure-caption: Figura
:example-caption: Esempio

include::shared/releases.adoc[]
include::shared/it/mailing-lists.adoc[]

[.abstract-title]
Sommario

Benvenuto in FreeBSD! Questo manuale copre l'installazione e l'uso giorno per giorno di _FreeBSD {rel112-current}-RELEASE_ e _FreeBSD {rel120-current}-RELEASE_. Questo manuale è un _progetto in evoluzione_ ed è il frutto del lavoro di molti singoli.  Come tale alcun sezioni potrebbero richiedere degli aggiornamenti poichè datate. Se sei interessato ad aiutare questo progetto, invia un'email alla {freebsd-doc}.  L'ultima versione di questo documento è sempre disponibile sul http://www.FreeBSD.org/[sito web di FreeBSD] (versioni precedenti di questo manuale possono essere trovate all'indirizzo seguente http://docs.FreeBSD.org/doc/[http://docs.FreeBSD.org/doc/]). Inoltre può essere scaricata in una varietà di formati e tipi di compressione dal ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/[server FTP di FreeBSD] o da uno dei numerosi <<mirrors-ftp,siti mirror>>. Se preferisci avere una copia rilegata del manuale, puoi comprarne una su http://www.freebsdmall.com/[FreeBSD Mall]. Puoi anche voler https://www.FreeBSD.org/search/[cercare nel manuale].

'''

include::content/it/books/handbook/toc.adoc[]

include::content/it/books/handbook/toc-figures.adoc[]

include::content/it/books/handbook/toc-tables.adoc[]

include::content/it/books/handbook/toc-examples.adoc[]
