# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml 

SUBDIR=	stable
SUBDIR+= advocacy

.include "${WEB_PREFIX}/share/mk/web.site.mk"
