#
# $FreeBSD$
#
# Article: FreeBSD Release Engineering

DOC?=		article

FORMATS?=	html html-split

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.xml

CSS_SHEET_ADDITIONS=extra.css

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"

