#
# The FreeBSD Russian Documentation Project
# 
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/zip-drive/Makefile,v 1.4 2005/10/28 18:00:47 gad Exp $
#
# Original revision: 1.4
#
# Article: IOmega ZIP Drives

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=  article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
