#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD$
#    $FreeBSDde: de-docproj/articles/new-users/Makefile,v 1.2 2005/02/08 00:43:39 mheinen Exp $
#    basiert auf: 1.11
#
# Article: Informationen für &os;- und &unix;-Einsteiger

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
