---
title: Chapter 17. Using USES Macros
prev: books/porters-handbook/keeping-up
next: books/porters-handbook/versions
---

[[uses]]
= Using `USES` Macros
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: 目录
:part-signifier: 部分
:chapter-signifier: 第
:appendix-caption: 附录
:table-caption: 表
:figure-caption: 图
:example-caption: 例 
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:c-plus-plus: c++
:sectnumoffset: 17

include::shared/mirrors.adoc[]
include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/zh-tw/mailing-lists.adoc[]
include::shared/zh-tw/urls.adoc[]

toc::[]

[[uses-intro]]
== An Introduction to `USES`

`USES` macros make it easy to declare requirements and settings for a port. They can add dependencies, change building behavior, add metadata to packages, and so on, all by selecting simple, preset values.

Each section in this chapter describes a possible value for `USES`, along with its possible arguments. Arguments are appeneded to the value after a colon (`:`). Multiple arguments are separated by commas (`,`).

[[uses-intro-ex1]]
.Using Multiple Values
[example]
====

[.programlisting]
....
USES=	bison perl
....

====

[[uses-intro-ex2]]
.Adding an Argument
[example]
====

[.programlisting]
....
USES=	tar:xz
....

====

[[uses-intro-ex3]]
.Adding Multiple Arguments
[example]
====

[.programlisting]
....
USES=	drupal:7,theme
....

====

[[uses-intro-ex4]]
.Mixing it All Together
[example]
====

[.programlisting]
....
USES=	pgsql:9.3+ cpe python:2.7,build
....

====

[[uses-7z]]
== `7z`

Possible arguments: (none), `p7zip`, `partial`

Extract using man:7z[1] instead of man:bsdtar[1] and sets `EXTRACT_SUFX=.7z`. The `p7zip` option forces a dependency on the `7z` from package:archivers/p7zip[] if the one from the base system is not able to extract the files. `EXTRACT_SUFX` is not changed if the `partial` option is used, this can be used if the main distribution file does not have a [.filename]#.7z# extension.

[[uses-ada]]
== `ada`

Possible arguments: (none), `5`, `6`

Depends on an Ada-capable compiler, and sets `CC` accordingly. Defaults to use gcc 5 from ports. Use the `:__X__` version option to force building with a different version.

[[uses-autoreconf]]
== `autoreconf`

Possible arguments: (none), `build`

Runs `autoreconf`. It encapsulates the `aclocal`, `autoconf`, `autoheader`, `automake`, `autopoint`, and `libtoolize` commands. Each command applies to [.filename]#${AUTORECONF_WRKSRC}/configure.ac# or its old name, [.filename]#${AUTORECONF_WRKSRC}/configure.in#. If [.filename]#configure.ac# defines subdirectories with their own [.filename]#configure.ac# using `AC_CONFIG_SUBDIRS`, `autoreconf` will recursively update those as well. The `:build` argument only adds build time dependencies on those tools but does not run `autoreconf`. A port can set `AUTORECONF_WRKSRC` if `WRKSRC` does not contain the path to [.filename]#configure.ac#.

[[uses-blaslapack]]
== `blaslapack`

Possible arguments: (none), `atlas`, `netlib` (default), `gotoblas`, `openblas`

Adds dependencies on Blas / Lapack libraries.

[[uses-bdb]]
== `bdb`

Possible arguments: (none), `48`, `5` (default), `6`

Add dependency on the Berkeley DB library. Default to package:databases/db5[]. It can also depend on package:databases/db48[] when using the `:48` argument or package:databases/db6[] with `:6`. It is possible to declare a range of acceptable values, `:48+` finds the highest installed version, and falls back to 4.8 if nothing else is installed. `INVALID_BDB_VER` can be used to specify versions which do not work with this port. The framework exposes the following variables to the port:

`BDB_LIB_NAME`::
The name of the Berkeley DB library. For example, when using package:databases/db5[], it contains `db-5.3`.

`BDB_LIB_CXX_NAME`::
The name of the Berkeley DBC++ library. For example, when using package:databases/db5[], it contains `db_cxx-5.3`.

`BDB_INCLUDE_DIR`::
The location of the Berkeley DB include directory. For example, when using package:databases/db5[], it will contain `${LOCALBASE}/include/db5`.

`BDB_LIB_DIR`::
The location of the Berkeley DB library directory. For example, when using package:databases/db5[], it contains `${LOCALBASE}/lib`.

`BDB_VER`::
The detected Berkeley DB version. For example, if using `USES=bdb:48+` and Berkeley DB 5 is installed, it contains `5`.

[IMPORTANT]
====
package:databases/db48[] is deprecated and unsupported. It must not be used by any port.
====

[[uses-bison]]
== `bison`

Possible arguments: (none), `build`, `run`, `both`

Uses package:devel/bison[] By default, with no arguments or with the `build` argument, it implies `bison` is a build-time dependency, `run` implies a run-time dependency, and `both` implies both run-time and build-time dependencies.

[[uses-cabal]]
== `cabal`

[IMPORTANT]
====
Ports should not be created for Haskell libraries, see <<haskell-libs>> for more information.
====

Possible arguments: (none), `hpack`

Sets default values and targets used to build Haskell software using Cabal. A build dependency on the Haskell compiler port (GHC) is added. If `hpack` argument is given, a build dependency on package:devel/hs-hpack[] is added and `hpack` is invoked at configuration step to generate .cabal file.

The framework provides the following variables:

`USE_CABAL`::
If the software uses Haskell dependencies, list them in this variable. Each item should be present on Hackage and be listed in form `packagename-_0.1.2_`. Dependencies can have revisions, which are specified after the `_` symbol. Automatic generation of dependency list is supported, see <<using-cabal>>.

`CABAL_FLAGS`::
List of flags to be passed to `cabal-install` during the configuring and building stage. The flags are passed verbatim.

`EXECUTABLES`::
List of executable files installed by the port. Default value: `${PORTNAME}`. Items from this list are automatically added to pkg-plist.

`SKIP_CABAL_PLIST`::
If defined, do not add items from `${EXECUTABLES}` to pkg-plist.

`opt_USE_CABAL`::
Adds items to `${USE_CABAL}` depending on `opt` option.

`opt_EXECUTABLES`::
Adds items to `${EXECUTABLES}` depending on `opt` option.

`opt_CABAL_FLAGS`::
If `opt` is enabled, append the value to `${CABAL_FLAGS}`. Otherwise, append `-value` to disable the flag.

`FOO_DATADIR_VARS`::
For an executable named `FOO` list Haskell packages, whose data files should be accessible by the executable.

[[uses-cargo]]
== `cargo`

Possible arguments: (none)

Uses Cargo for configuring, building, and testing. It can be used to port Rust applications that use the Cargo build system. For more information see <<using-cargo>>.

[[uses-charsetfix]]
== `charsetfix`

Possible arguments: (none)

Prevents the port from installing [.filename]#charset.alias#. This must be installed only by package:converters/libiconv[]. `CHARSETFIX_MAKEFILEIN` can be set to a path relative to `WRKSRC` if [.filename]#charset.alias# is not installed by [.filename]#${WRKSRC}/Makefile.in#.

[[uses-cmake]]
== `cmake`

Possible arguments: (none), `insource`, `noninja`, `run`

Uses CMake for configuring and building.

By default an out-of-source build is performed, leaving the sources in `WRKSRC` free from build artifacts. With the `insource` argument, an in-source build will be performed instead. Setting it should be the exception when a regular out-of-source build does not work.

By default Ninja is used for the build. In some cases this does not work correctly. With the `noninja` argument, the build will fallback to using regular `make` for builds. It should only be used if a Ninja-based build does not work.

With the `run` argument, a run dependency is registered in addition to a build dependency.

For more information see <<using-cmake>>.

[[uses-compiler]]
== `compiler`

Possible arguments: (none), `env` (default, implicit), `{c-plus-plus}17-lang`, `{c-plus-plus}14-lang`, `{c-plus-plus}11-lang`, `gcc-{c-plus-plus}11-lib`, `{c-plus-plus}11-lib`, `{c-plus-plus}0x`, `c11`, `openmp`, `nestedfct`, `features`

Determines which compiler to use based on any given wishes. Use `{c-plus-plus}17-lang` if the port needs a {c-plus-plus}17-capable compiler, `{c-plus-plus}14-lang` if the port needs a {c-plus-plus}14-capable compiler, `{c-plus-plus}11-lang` if the port needs a {c-plus-plus}11-capable compiler, `gcc-{c-plus-plus}11-lib` if the port needs the `g++` compiler with a {c-plus-plus}11 library, or `{c-plus-plus}11-lib` if the port needs a {c-plus-plus}11-ready standard library. If the port needs a compiler understanding {c-plus-plus}0X, C11, OpenMP, or nested functions, the corresponding parameters should be used.

Use `features` to request a list of features supported by the default compiler. After including [.filename]#bsd.port.pre.mk# the port can inspect the results using these variables:

* `COMPILER_TYPE`: the default compiler on the system, either gcc or clang
* `ALT_COMPILER_TYPE`: the alternative compiler on the system, either gcc or clang. Only set if two compilers are present in the base system.
* `COMPILER_VERSION`: the first two digits of the version of the default compiler.
* `ALT_COMPILER_VERSION`: the first two digits of the version of the alternative compiler, if present.
* `CHOSEN_COMPILER_TYPE`: the chosen compiler, either gcc or clang
* `COMPILER_FEATURES`: the features supported by the default compiler. It currently lists the {c-plus-plus} library.

[[uses-cpe]]
== `cpe`

Possible arguments: (none)

Include Common Platform Enumeration (CPE) information in package manifest as a CPE 2.3 formatted string. See the http://scap.nist.gov/specifications/cpe/[CPE specification] for details. To add CPE information to a port, follow these steps:

[.procedure]
====
. Search for the official CPE entry for the software product either by using the NVD's http://web.nvd.nist.gov/view/cpe/search[CPE search engine] or in the http://static.nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml[official CPE dictionary] (warning, very large XML file). _Do not ever make up CPE data._
. Add `cpe` to `USES` and compare the result of `make -V CPE_STR` to the CPE dictionary entry. Continue one step at a time until `make -V CPE_STR` is correct.
. If the product name (second field, defaults to `PORTNAME`) is incorrect, define `CPE_PRODUCT`.
. If the vendor name (first field, defaults to `CPE_PRODUCT`) is incorrect, define `CPE_VENDOR`.
. If the version field (third field, defaults to `PORTVERSION`) is incorrect, define `CPE_VERSION`.
. If the update field (fourth field, defaults to empty) is incorrect, define `CPE_UPDATE`.
. If it is still not correct, check [.filename]#Mk/Uses/cpe.mk# for additional details, or contact the {ports-secteam}.
. Derive as much as possible of the CPE name from existing variables such as `PORTNAME` and `PORTVERSION`. Use variable modifiers to extract the relevant portions from these variables rather than hardcoding the name.
. _Always_ run `make -V CPE_STR` and check the output before committing anything that changes `PORTNAME` or `PORTVERSION` or any other variable which is used to derive `CPE_STR`.
====

[[uses-cran]]
== `cran`

Possible arguments: (none), `auto-plist`, `compiles`

Uses the Comprehensive R Archive Network. Specify `auto-plist` to automatically generate [.filename]#pkg-plist#. Specify `compiles` if the port has code that need to be compiled.

[[uses-desktop-file-utils]]
== `desktop-file-utils`

Possible arguments: (none)

Uses update-desktop-database from package:devel/desktop-file-utils[]. An extra post-install step will be run without interfering with any post-install steps already in the port [.filename]#Makefile#. A line with <<plist-keywords-desktop-file-utils,`@desktop-file-utils`>> will be added to the plist.

[[uses-desthack]]
== `desthack`

Possible arguments: (none)

Changes the behavior of GNU configure to properly support `DESTDIR` in case the original software does not.

[[uses-display]]
== `display`

Possible arguments: (none), _ARGS_

Set up a virtual display environment. If the environment variable `DISPLAY` is not set, then Xvfb is added as a build dependency, and `CONFIGURE_ENV` is extended with the port number of the currently running instance of Xvfb. The _ARGS_ parameter defaults to `install` and controls the phase around which to start and stop the virtual display.

[[uses-dos2unix]]
== `dos2unix`

Possible arguments: (none)

The port has files with line endings in DOS format which need to be converted. Several variables can be set to control which files will be converted. The default is to convert _all_ files, including binaries. See <<slow-patch-automatic-replacements>> for examples.

* `DOS2UNIX_REGEX`: match file names based on a regular expression.
* `DOS2UNIX_FILES`: match literal file names.
* `DOS2UNIX_GLOB`: match file names based on a glob pattern.
* `DOS2UNIX_WRKSRC`: the directory from which to start the conversions. Defaults to `${WRKSRC}`.

[[uses-drupal]]
== `drupal`

Possible arguments: `7`, `module`, `theme`

Automate installation of a port that is a Drupal theme or module. Use with the version of Drupal that the port is expecting. For example, `USES=drupal:7,module` says that this port creates a Drupal 6 module. A Drupal 7 theme can be specified with `USES=drupal:7,theme`.

[[uses-fakeroot]]
== `fakeroot`

Possible arguments: (none)

Changes some default behavior of build systems to allow installing as a user. See https://wiki.debian.org/FakeRoot[] for more information on `fakeroot`.

[[uses-fam]]
== `fam`

Possible arguments: (none), `fam`, `gamin`

Uses a File Alteration Monitor as a library dependency, either package:devel/fam[] or package:devel/gamin[]. End users can set WITH_FAM_SYSTEM to specify their preference.

[[uses-firebird]]
== `firebird`

Possible arguments: (none), `25`

Add a dependency to the client library of the Firebird database.

[[uses-fonts]]
== `fonts`

Possible arguments: (none), `fc`, `fcfontsdir` (default), `fontsdir`, `none`

Adds a runtime dependency on tools needed to register fonts. Depending on the argument, add a `<<plist-keywords-fc,@fc>> ${FONTSDIR}` line, `<<plist-keywords-fcfontsdir,@fcfontsdir>> ${FONTSDIR}` line, `<<plist-keywords-fontsdir,@fontsdir>> ${FONTSDIR}` line, or no line if the argument is `none`, to the plist. `FONTSDIR` defaults to [.filename]#${PREFIX}/shared/fonts/${FONTNAME}# and `FONTNAME` to `${PORTNAME}`. Add `FONTSDIR` to `PLIST_SUB` and `SUB_LIST`

[[uses-fortran]]
== `fortran`

Possible arguments: `gcc` (default)

Uses the GNU Fortran compiler.

[[uses-fuse]]
== `fuse`

Possible arguments: `2` (default), `3`

The port will depend on the FUSE library and handle the dependency on the kernel module depending on the version of FreeBSD.

[[uses-gem]]
== `gem`

Possible arguments: (none), `noautoplist`

Handle building with RubyGems. If `noautoplist` is used, the packing list is not generated automatically.

[[uses-gettext]]
== `gettext`

Possible arguments: (none)

Deprecated. Will include both <<uses-gettext-runtime,`gettext-runtime`>> and <<uses-gettext-tools,`gettext-tools`>>.

[[uses-gettext-runtime]]
== `gettext-runtime`

Possible arguments: (none), `lib` (default), `build`, `run`

Uses package:devel/gettext-runtime[]. By default, with no arguments or with the `lib` argument, implies a library dependency on [.filename]#libintl.so#. `build` and `run` implies, respectively a build-time and a run-time dependency on [.filename]#gettext#.

[[uses-gettext-tools]]
== `gettext-tools`

Possible arguments: (none), `build` (default), `run`

Uses package:devel/gettext-tools[]. By default, with no argument, or with the `build` argument, a build time dependency on [.filename]#msgfmt# is registered. With the `run` argument, a run-time dependency is registered.

[[uses-ghostscript]]
== `ghostscript`

Possible arguments: _X_, `build`, `run`, `nox11`

A specific version _X_ can be used. Possible versions are `7`, `8`, `9`, and `agpl` (default). `nox11` indicates that the `-nox11` version of the port is required. `build` and `run` add build- and run-time dependencies on Ghostscript. The default is both build- and run-time dependencies.

[[uses-gl]]
== `gl`

Possible arguments: (none)

Provides an easy way to depend on GL components. The components should be listed in `USE_GL`. The available components are:

`egl`::
add a library dependency on [.filename]#libEGL.so# from package:graphics/mesa-libs[]

`gbm`::
Add a library dependency on [.filename]#libgbm.so# from package:graphics/mesa-libs[]

`gl`::
Add a library dependency on [.filename]#libGL.so# from package:graphics/mesa-libs[]

`glesv2`::
Add a library dependency on [.filename]#libGLESv2.so# from package:graphics/mesa-libs[]

`glew`::
Add a library dependency on [.filename]#libGLEW.so# from package:graphics/glew[]

`glu`::
Add a library dependency on [.filename]#libGLU.so# from package:graphics/libGLU[]

`glut`::
Add a library dependency on [.filename]#libglut.so# from package:graphics/freeglut[]

[[uses-gmake]]
== `gmake`

Possible arguments: (none)

Uses package:devel/gmake[] as a build-time dependency and sets up the environment to use `gmake` as the default `make` for the build.

[[uses-gnome]]
== `gnome`

Possible arguments: (none)

Provides an easy way to depend on GNOME components. The components should be listed in `USE_GNOME`. The available components are:

* `atk`
* `atkmm`
* `cairo`
* `cairomm`
* `dconf`
* `esound`
* `evolutiondataserver3`
* `gconf2`
* `gconfmm26`
* `gdkpixbuf`
* `gdkpixbuf2`
* `glib12`
* `glib20`
* `glibmm`
* `gnomecontrolcenter3`
* `gnomedesktop3`
* `gnomedocutils`
* `gnomemenus3`
* `gnomemimedata`
* `gnomeprefix`
* `gnomesharp20`
* `gnomevfs2`
* `gsound`
* `gtk-update-icon-cache`
* `gtk12`
* `gtk20`
* `gtk30`
* `gtkhtml3`
* `gtkhtml4`
* `gtkmm20`
* `gtkmm24`
* `gtkmm30`
* `gtksharp20`
* `gtksourceview`
* `gtksourceview2`
* `gtksourceview3`
* `gtksourceviewmm3`
* `gvfs`
* `intlhack`
* `intltool`
* `introspection`
* `libartlgpl2`
* `libbonobo`
* `libbonoboui`
* `libgda5`
* `libgda5-ui`
* `libgdamm5`
* `libglade2`
* `libgnome`
* `libgnomecanvas`
* `libgnomekbd`
* `libgnomeprint`
* `libgnomeprintui`
* `libgnomeui`
* `libgsf`
* `libgtkhtml`
* `libgtksourceviewmm`
* `libidl`
* `librsvg2`
* `libsigc++12`
* `libsigc++20`
* `libwnck`
* `libwnck3`
* `libxml++26`
* `libxml2`
* `libxslt`
* `metacity`
* `nautilus3`
* `orbit2`
* `pango`
* `pangomm`
* `pangox-compat`
* `py3gobject3`
* `pygnome2`
* `pygobject`
* `pygobject3`
* `pygtk2`
* `pygtksourceview`
* `referencehack`
* `vte`
* `vte3`

The default dependency is build- and run-time, it can be changed with `:build` or `:run`. For example:

[.programlisting]
....
USES=		gnome
USE_GNOME=	gnomemenus3:build intlhack
....

See <<using-gnome>> for more information.

[[uses-go]]
== `go`

[IMPORTANT]
====
Ports should not be created for Go libs, see <<go-libs>> for more information.
====

Possible arguments: (none), `modules`, `no_targets`, `run`

Sets default values and targets used to build Go software. A build dependency on the Go compiler port selected via `GO_PORT` is added. By default the build is performed in GOPATH mode. If Go software uses modules, the modules-aware mode can be switched on with `modules` argument. `no_targets` will setup build environment like `GO_ENV`, `GO_BUILDFLAGS` but skip creating `post-extract` and `do-{build,install,test}` targets. `run` will also add a run dependency on what is in `GO_PORT`.

The build process is controlled by several variables:

`GO_PKGNAME`::
The name of the Go package when building in GOPATH mode. This is the directory that will be created in `${GOPATH}/src`. If not set explicitly and `GH_SUBDIR` or `GL_SUBDIR` is present, `GO_PKGNAME` will be inferred from it. It is not needed when building in modules-aware mode.

`GO_TARGET`::
The packages to build. The default value is `${GO_PKGNAME}`. `GO_TARGET` can also be a tuple in the form `package:path` where path can be either a simple filename or a full path starting with `${PREFIX}`.

`GO_TESTTARGET`::
The packages to test. The default value is `./...` (the current package and all subpackages).

`CGO_CFLAGS`::
Additional `CFLAGS` values to be passed to the C compiler by `go`.

`CGO_LDFLAGS`::
Additional `LDFLAGS` values to be passed to the C compiler by `go`.

`GO_BUILDFLAGS`::
Additional build arguments to be passed to `go build`.

`GO_TESTFLAGS`::
Additional build arguments to be passed to `go test`.

`GO_PORT`::
The Go compiler port to use. By default this is package:lang/go[] but can be set to package:lang/go-devel[] in `make.conf` for testing with future Go versions.
+

[WARNING]
====

This variable must not be set by individual ports!
====

See <<using-go>> for usage examples.

[[uses-gperf]]
== `gperf`

Possible arguments: (none)

Add a buildtime dependency on package:devel/gperf[] if `gperf` is not present in the base system.

[[uses-grantlee]]
== `grantlee`

Possible arguments: `5`, `selfbuild`

Handle dependency on Grantlee. Specify `5` to depend on the Qt5 based version, package:devel/grantlee5[]. `selfbuild` is used internally by package:devel/grantlee5[] to get their versions numbers.

[[uses-groff]]
== `groff`

Possible arguments: `build`, `run`, `both`

Registers a dependency on package:textproc/groff[] if not present in the base system.

[[uses-gssapi]]
== `gssapi`

Possible arguments: (none), `base` (default), `heimdal`, `mit`, `flags`, `bootstrap`

Handle dependencies needed by consumers of the GSS-API. Only libraries that provide the Kerberos mechanism are available. By default, or set to `base`, the GSS-API library from the base system is used. Can also be set to `heimdal` to use package:security/heimdal[], or `mit` to use package:security/krb5[].

When the local Kerberos installation is not in `LOCALBASE`, set `HEIMDAL_HOME` (for `heimdal`) or `KRB5_HOME` (for `krb5`) to the location of the Kerberos installation.

These variables are exported for the ports to use:

* `GSSAPIBASEDIR`
* `GSSAPICPPFLAGS`
* `GSSAPIINCDIR`
* `GSSAPILDFLAGS`
* `GSSAPILIBDIR`
* `GSSAPILIBS`
* `GSSAPI_CONFIGURE_ARGS`

The `flags` option can be given alongside `base`, `heimdal`, or `mit` to automatically add `GSSAPICPPFLAGS`, `GSSAPILDFLAGS`, and `GSSAPILIBS` to `CFLAGS`, `LDFLAGS`, and `LDADD`, respectively. For example, use `base,flags`.

The `bootstrap` option is a special prefix only for use by package:security/krb5[] and package:security/heimdal[]. For example, use `bootstrap,mit`.

[[uses-gssapi-ex1]]
.Typical Use
[example]
====

[.programlisting]
....
OPTIONS_SINGLE=	GSSAPI
OPTIONS_SINGLE_GSSAPI=	GSSAPI_BASE GSSAPI_HEIMDAL GSSAPI_MIT GSSAPI_NONE

GSSAPI_BASE_USES=	gssapi
GSSAPI_BASE_CONFIGURE_ON=	--with-gssapi=${GSSAPIBASEDIR} ${GSSAPI_CONFIGURE_ARGS}
GSSAPI_HEIMDAL_USES=	gssapi:heimdal
GSSAPI_HEIMDAL_CONFIGURE_ON=	--with-gssapi=${GSSAPIBASEDIR} ${GSSAPI_CONFIGURE_ARGS}
GSSAPI_MIT_USES=	gssapi:mit
GSSAPI_MIT_CONFIGURE_ON=	--with-gssapi=${GSSAPIBASEDIR} ${GSSAPI_CONFIGURE_ARGS}
GSSAPI_NONE_CONFIGURE_ON=	--without-gssapi
....

====

[[uses-horde]]
== `horde`

Possible arguments: (none)

Add buildtime and runtime dependencies on package:devel/pear-channel-horde[]. Other Horde dependencies can be added with `USE_HORDE_BUILD` and `USE_HORDE_RUN`. See <<php-horde>> for more information.

[[uses-iconv]]
== `iconv`

Possible arguments: (none), `lib`, `build`, `patch`, `translit`, `wchar_t`

Uses `iconv` functions, either from the port package:converters/libiconv[] as a build-time and run-time dependency, or from the base system on 10-CURRENT after a native `iconv` was committed in link:https://svnweb.freebsd.org/changeset/base/254273[r254273]. By default, with no arguments or with the `lib` argument, implies `iconv` with build-time and run-time dependencies. `build` implies a build-time dependency, and `patch` implies a patch-time dependency. If the port uses the `WCHAR_T` or `//TRANSLIT` iconv extensions, add the relevant arguments so that the correct iconv is used. For more information see <<using-iconv>>.

[[uses-imake]]
== `imake`

Possible arguments: (none), `env`, `notall`, `noman`

Add package:devel/imake[] as a build-time dependency and run `xmkmf -a` during the `configure` stage. If the `env` argument is given, the `configure` target is not set. If the `-a` flag is a problem for the port, add the `notall` argument. If `xmkmf` does not generate a `install.man` target, add the `noman` argument.

[[uses-kde]]
== `kde`

Possible arguments: `5`

Add dependency on KDE components. See <<using-kde>> for more information.

[[uses-kmod]]
== `kmod`

Possible arguments: (none), `debug`

Fills in the boilerplate for kernel module ports, currently:

* Add `kld` to `CATEGORIES`.
* Set `SSP_UNSAFE`.
* Set `IGNORE` if the kernel sources are not found in `SRC_BASE`.
* Define `KMODDIR` to [.filename]#/boot/modules# by default, add it to `PLIST_SUB` and `MAKE_ENV`, and create it upon installation. If `KMODDIR` is set to [.filename]#/boot/kernel#, it will be rewritten to [.filename]#/boot/modules#. This prevents breaking packages when upgrading the kernel due to [.filename]#/boot/kernel# being renamed to [.filename]#/boot/kernel.old# in the process.
* Handle cross-referencing kernel modules upon installation and deinstallation, using <<plist-keywords-kld,`@kld`>>.
* If the `debug` argument is given, the port can install a debug version of the module into [.filename]#KERN_DEBUGDIR#/[.filename]#KMODDIR#. By default, `KERN_DEBUGDIR` is copied from `DEBUGDIR` and set to [.filename]#/usr/lib/debug#. The framework will take care of creating and removing any required directories.

[[uses-lha]]
== `lha`

Possible arguments: (none)

Set `EXTRACT_SUFX` to `.lzh`

[[uses-libarchive]]
== `libarchive`

Possible arguments: (none)

Registers a dependency on package:archivers/libarchive[]. Any ports depending on libarchive must include `USES=libarchive`.

[[uses-libedit]]
== `libedit`

Possible arguments: (none)

Registers a dependency on package:devel/libedit[]. Any ports depending on libedit must include `USES=libedit`.

[[uses-libtool]]
== `libtool`

Possible arguments: (none), `keepla`, `build`

Patches `libtool` scripts. This must be added to all ports that use `libtool`. The `keepla` argument can be used to keep [.filename]#.la# files. Some ports do not ship with their own copy of libtool and need a build time dependency on package:devel/libtool[], use the `:build` argument to add such dependency.

[[uses-linux]]
== `linux`

Possible arguments: `c6`, `c7`

Ports Linux compatibility framework. Specify `c6` to depend on CentOS 6 packags. Specify `c7` to depend on CentOS 7 packages. The available packages are:

* `allegro`
* `alsa-plugins-oss`
* `alsa-plugins-pulseaudio`
* `alsalib`
* `atk`
* `avahi-libs`
* `base`
* `cairo`
* `cups-libs`
* `curl`
* `cyrus-sasl2`
* `dbusglib`
* `dbuslibs`
* `devtools`
* `dri`
* `expat`
* `flac`
* `fontconfig`
* `gdkpixbuf2`
* `gnutls`
* `graphite2`
* `gtk2`
* `harfbuzz`
* `jasper`
* `jbigkit`
* `jpeg`
* `libasyncns`
* `libaudiofile`
* `libelf`
* `libgcrypt`
* `libgfortran`
* `libgpg-error`
* `libmng`
* `libogg`
* `libpciaccess`
* `libsndfile`
* `libsoup`
* `libssh2`
* `libtasn1`
* `libthai`
* `libtheora`
* `libv4l`
* `libvorbis`
* `libxml2`
* `mikmod`
* `naslibs`
* `ncurses-base`
* `nspr`
* `nss`
* `openal`
* `openal-soft`
* `openldap`
* `openmotif`
* `openssl`
* `pango`
* `pixman`
* `png`
* `pulseaudio-libs`
* `qt`
* `qt-x11`
* `qtwebkit`
* `scimlibs`
* `sdl12`
* `sdlimage`
* `sdlmixer`
* `sqlite3`
* `tcl85`
* `tcp_wrappers-libs`
* `tiff`
* `tk85`
* `ucl`
* `xorglibs`

[[uses-localbase]]
== `localbase`

Possible arguments: (none), `ldflags`

Ensures that libraries from dependencies in `LOCALBASE` are used instead of the ones from the base system. Specify `ldflags` to add `-L${LOCALBASE}/lib` to `LDFLAGS` instead of `LIBS`. Ports that depend on libraries that are also present in the base system should use this. It is also used internally by a few other `USES`.

[[uses-lua]]
== `lua`

Possible arguments: (none), `_XY_+`, `_XY_`, `build`, `run`

Adds a dependency on Lua. By default this is a library dependency, unless overridden by the `build` or `run` option. The default version is 5.2, unless set by the `_XY_` parameter (for example, `51` or `52+`).

[[uses-lxqt]]
== `lxqt`

Possible arguments: (none)

Handle dependencies for the LXQt Desktop Environment. Use `USE_LXQT` to select the components needed for the port. See <<using-lxqt>> for more information.

[[uses-makeinfo]]
== `makeinfo`

Possible arguments: (none)

Add a build-time dependency on `makeinfo` if it is not present in the base system.

[[uses-makeself]]
== `makeself`

Possible arguments: (none)

Indicates that the distribution files are makeself archives and sets the appropriate dependencies.

[[uses-mate]]
== `mate`

Possible arguments: (none)

Provides an easy way to depend on MATE components. The components should be listed in `USE_MATE`. The available components are:

* `autogen`
* `caja`
* `common`
* `controlcenter`
* `desktop`
* `dialogs`
* `docutils`
* `icontheme`
* `intlhack`
* `intltool`
* `libmatekbd`
* `libmateweather`
* `marco`
* `menus`
* `notificationdaemon`
* `panel`
* `pluma`
* `polkit`
* `session`
* `settingsdaemon`

The default dependency is build- and run-time, it can be changed with `:build` or `:run`. For example:

[.programlisting]
....
USES=		mate
USE_MATE=	menus:build intlhack
....

[[uses-meson]]
== `meson`

Possible arguments: (none)

Provide support for Meson based projects. For more information see <<using-meson>>.

[[uses-metaport]]
== `metaport`

Possible arguments: (none)

Sets the following variables to make it easier to create a metaport: `MASTER_SITES`, `DISTFILES`, `EXTRACT_ONLY`, `NO_BUILD`, `NO_INSTALL`, `NO_MTREE`, `NO_ARCH`.

[[uses-mysql]]
== `mysql`

Possible arguments: (none), `_version_`, `client` (default), `server`, `embedded`

Provide support for MySQL. If no version is given, try to find the current installed version. Fall back to the default version, MySQL-5.6. The possible versions are `55`, `55m`, `55p`, `56`, `56p`, `56w`, `57`, `57p`, `80`, `100m`, `101m`, and `102m`. The `m` and `p` suffixes are for the MariaDB and Percona variants of MySQL. `server` and `embedded` add a build- and run-time dependency on the MySQL server. When using `server` or `embedded`, add `client` to also add a dependency on [.filename]#libmysqlclient.so#. A port can set `IGNORE_WITH_MYSQL` if some versions are not supported.

The framework sets `MYSQL_VER` to the detected MySQL version.

[[uses-mono]]
== `mono`

Possible arguments: (none), `nuget`

Adds a dependency on the Mono (currently only C#) framework by setting the appropriate dependencies.

Specify `nuget` when the port uses nuget packages. `NUGET_DEPENDS` needs to be set with the names and versions of the nuget packages in the format `_name=version_`. An optional package origin can be added using `_name=version:origin_`.

The helper target, `buildnuget`, will output the content of the `NUGET_DEPENDS` based on the provided [.filename]#packages.config#.

[[uses-motif]]
== `motif`

Possible arguments: (none)

Uses package:x11-toolkits/open-motif[] as a library dependency. End users can set `WANT_LESSTIF` for the dependency to be on package:x11-toolkits/lesstif[] instead of package:x11-toolkits/open-motif[].

[[uses-ncurses]]
== `ncurses`

Possible arguments: (none), `base`, `port`

Uses ncurses, and causes some useful variables to be set.

[[uses-ninja]]
== `ninja`

Possible arguments: (none)

Uses ninja to build the port.

[[uses-objc]]
== `objc`

Possible arguments: (none)

Add objective C dependencies (compiler, runtime library) if the base system does not support it.

[[uses-openal]]
== `openal`

Possible arguments: `al`, `soft` (default), `si`, `alut`

Uses OpenAL. The backend can be specified, with the software implementation as the default. The user can specify a preferred backend with `WANT_OPENAL`. Valid values for this knob are `soft` (default) and `si`.

[[uses-pathfix]]
== `pathfix`

Possible arguments: (none)

Look for [.filename]#Makefile.in# and [.filename]#configure# in `PATHFIX_WRKSRC` (defaults to `WRKSRC`) and fix common paths to make sure they respect the FreeBSD hierarchy. For example, it fixes the installation directory of ``pkgconfig``'s [.filename]#.pc# files to [.filename]#${PREFIX}/libdata/pkgconfig#. If the port uses `USES=autoreconf`, [.filename]#Makefile.am# will be added to `PATHFIX_MAKEFILEIN` automatically.

If the port <<uses-cmake,`USES=cmake`>> it will look for [.filename]#CMakeLists.txt# in `PATHFIX_WRKSRC`. If needed, that default filename can be changed with `PATHFIX_CMAKELISTSTXT`.

[[uses-pear]]
== `pear`

Possible arguments: `env`

Adds a dependency on package:devel/pear[]. It will setup default behavior for software using the PHP Extension and Application Repository. Using the `env` arguments only sets up the PEAR environment variables. See <<php-pear>> for more information.

[[uses-perl5]]
== `perl5`

Possible arguments: (none)

Depends on Perl. The configuration is done using `USE_PERL5`.

`USE_PERL5` can contain the phases in which to use Perl, can be `extract`, `patch`, `build`, `run`, or `test`.

`USE_PERL5` can also contain `configure`, `modbuild`, or `modbuildtiny` when [.filename]#Makefile.PL#, [.filename]#Build.PL#, or Module::Build::Tiny's flavor of [.filename]#Build.PL# is required.

`USE_PERL5` defaults to `build run`. When using `configure`, `modbuild`, or `modbuildtiny`, `build` and `run` are implied.

See <<using-perl>> for more information.

[[uses-pgsql]]
== `pgsql`

Possible arguments: (none), `_X.Y_`, `_X.Y_+`, `_X.Y_-`, `_X.Y_-_Z.A_`

Provide support for PostgreSQL. Port maintainer can set version required. Minimum and maximum versions or a range can be specified; for example, `9.0-`, `8.4+`, `8.4-9.2.`

By default, the added dependency will be the client, but if the port requires additional components, this can be done using `WANT_PGSQL=_component[:target]_`; for example, `WANT_PGSQL=server:configure pltcl plperl`. The available components are:

* `client`
* `contrib`
* `docs`
* `pgtcl`
* `plperl`
* `plpython`
* `pltcl`
* `server`

[[uses-php]]
== `php`

Possible arguments: (none), `phpize`, `ext`, `zend`, `build`, `cli`, `cgi`, `mod`, `web`, `embed`, `pecl`, `flavors`, `noflavors`

Provide support for PHP. Add a runtime dependency on the default PHP version, package:lang/php56[].

`phpize`::
Use to build a PHP extension. Enables flavors.

`ext`::
Use to build, install and register a PHP extension. Enables flavors.

`zend`::
Use to build, install and register a Zend extension. Enables flavors.

`build`::
Set PHP also as a build-time dependency.

`cli`::
Needs the CLI version of PHP.

`cgi`::
Needs the CGI version of PHP.

`mod`::
Needs the Apache module for PHP.

`web`::
Needs the Apache module or the CGI version of PHP.

`embed`::
Needs the embedded library version of PHP.

`pecl`::
Provide defaults for fetching PHP extensions from the PECL repository. Enables flavors.

`flavors`::
Enable automatic <<flavors-auto-php,PHP flavors>> generation. Flavors will be generated for all PHP versions, except the ones present in <<uses-php-ignore,`IGNORE_WITH_PHP`>>.

`noflavors`::
Disable automatic PHP flavors generation. _Must only_ be used with extensions provided by PHP itself.

Variables are used to specify which PHP modules are required, as well as which version of PHP are supported.

`USE_PHP`::
The list of required PHP extensions at run-time. Add `:build` to the extension name to add a build-time dependency. Example: `pcre xml:build gettext`
[[uses-php-ignore]]
`IGNORE_WITH_PHP`::
The port does not work with PHP of the given version. For possible values look at the content of `_ALL_PHP_VERSIONS` in [.filename]#Mk/Uses/php.mk#.

When building a PHP or Zend extension with `:ext` or `:zend`, these variables can be set:

`PHP_MODNAME`::
The name of the PHP or Zend extension. Default value is `${PORTNAME}`.

`PHP_HEADER_DIRS`::
A list of subdirectories from which to install header files. The framework will always install the header files that are present in the same directory as the extension.

`PHP_MOD_PRIO`::
The priority at which to load the extension. It is a number between `00` and `99`.
+
For extensions that do not depend on any extension, the priority is automatically set to `20`, for extensions that depend on another extension, the priority is automatically set to `30`. Some extensions may need to be loaded before every other extension, for example package:www/php56-opcache[]. Some may need to be loaded after an extension with a priority of `30`. In that case, add `PHP_MOD_PRIO=_XX_` in the port's Makefile. For example:
+
[.programlisting]
....
USES=		php:ext
USE_PHP=	wddx
PHP_MOD_PRIO=	40
....

These variables are available to use in `PKGNAMEPREFIX` or `PKGNAMESUFFIX`:

`PHP_PKGNAMEPREFIX`::
Contains `php__XY__-` where _XY_ is the current flavor's PHP version. Use with PHP extensions and modules.

`PHP_PKGNAMESUFFIX`::
Contains `-php__XY__` where _XY_ is the current flavor's PHP version. Use with PHP applications.

`PECL_PKGNAMEPREFIX`::
Contains `php__XY__-pecl-` where _XY_ is the current flavor's PHP version. Use with PECL modules.

[IMPORTANT]
====
With flavors, all PHP extensions, PECL extensions, PEAR modules _must have_ a different package name, so they must all use one of these three variables in their `PKGNAMEPREFIX` or `PKGNAMESUFFIX`.
====

[[uses-pkgconfig]]
== `pkgconfig`

Possible arguments: (none), `build` (default), `run`, `both`

Uses package:devel/pkgconf[]. With no arguments or with the `build` argument, it implies `pkg-config` as a build-time dependency. `run` implies a run-time dependency and `both` implies both run-time and build-time dependencies.

[[uses-pure]]
== `pure`

Possible arguments: (none), `ffi`

Uses package:lang/pure[]. Largely used for building related pure ports. With the `ffi` argument, it implies package:devel/pure-ffi[] as a run-time dependency.

[[uses-pyqt]]
== `pyqt`

Possible arguments: (none), `4`, `5`

Uses PyQt. If the port is part of PyQT itself, set `PYQT_DIST`. Use `USE_PYQT` to select the components the port needs. The available components are:

* `core`
* `dbus`
* `dbussupport`
* `demo`
* `designer`
* `designerplugin`
* `doc`
* `gui`
* `multimedia`
* `network`
* `opengl`
* `qscintilla2`
* `sip`
* `sql`
* `svg`
* `test`
* `webkit`
* `xml`
* `xmlpatterns`

These components are only available with PyQT4:

* `assistant`
* `declarative`
* `help`
* `phonon`
* `script`
* `scripttools`

These components are only available with PyQT5:

* `multimediawidgets`
* `printsupport`
* `qml`
* `serialport`
* `webkitwidgets`
* `widgets`

The default dependency for each component is build- and run-time, to select only build or run, add `_build` or `_run` to the component name. For example:

[.programlisting]
....
USES=		pyqt
USE_PYQT=	core doc_build designer_run
....

[[uses-python]]
== `python`

Possible arguments: (none), `_X.Y_`, `_X.Y+_`, `_-X.Y_`, `_X.Y-Z.A_`, `patch`, `build`, `run`, `test`

Uses Python. A supported version or version range can be specified. If Python is only needed at build time, run time or for the tests, it can be set as a build, run or test dependency with `build`, `run`, or `test`. If Python is also needed during the patch phase, use `patch`. See <<using-python>> for more information.

`PYTHON_NO_DEPENDS=yes` can be used when the variables exported by the framework are needed but a dependency on Python is not. It can happen when using with <<uses-shebangfix,`USES=shebangfix`>>, and the goal is only to fix the shebangs but not add a dependency on Python.

[[uses-qmail]]
== `qmail`

Possible arguments: (none), `build`, `run`, `both`, `vars`

Uses package:mail/qmail[]. With the `build` argument, it implies `qmail` as a build-time dependency. `run` implies a run-time dependency. Using no argument or the `both` argument implies both run-time and build-time dependencies. `vars` will only set QMAIL variables for the port to use.

[[uses-qmake]]
== `qmake`

Possible arguments: (none), `norecursive`, `outsource`, `no_env`, `no_configure`

Uses QMake for configuring. For more information see <<using-qmake>>.

[[uses-qt]]
== `qt`

Possible arguments: `5`, `no_env`

Add dependency on Qt components. `no_env` is passed directly to `USES= qmake`. See <<using-qt>> for more information.

[[uses-qt-dist]]
== `qt-dist`

Possible arguments: (none) or `5` and (none) or one of `3d`, `activeqt`, `androidextras`, `base`, `canvas3d`, `charts`, `connectivity`, `datavis3d`, `declarative`, `doc`, `gamepad`, `graphicaleffects`, `imageformats`, `location`, `macextras`, `multimedia`, `networkauth`, `purchasing`, `quickcontrols2`, `quickcontrols`, `remoteobjects`, `script`, `scxml`, `sensors`, `serialbus`, `serialport`, `speech`, `svg`, `tools`, `translations`, `virtualkeyboard`, `wayland`, `webchannel`, `webengine`, `websockets`, `webview`, `winextras`, `x11extras`, `xmlpatterns`

Provides support for building Qt 5 components. It takes care of setting up the appropriate configuration environment for the port to build.

[[qt5-dist-example]]
.Building Qt 5 Components
[example]
====

The port is Qt 5's `networkauth` component, which is part of the `networkauth` distribution file.

[.programlisting]
....
PORTNAME=	networkauth
DISTVERSION=	${QT5_VERSION}

USES=		qt-dist:5
....

====

If `PORTNAME` does not match the component name, it can be passed as an argument to `qt-dist`.

[[qt5-dist-example-explicit]]
.Building Qt 5 Components with Different Names
[example]
====

The port is Qt 5's `gui` component, which is part of the `base` distribution file.

[.programlisting]
....
PORTNAME=	gui
DISTVERSION=	${QT5_VERSION}

USES=		qt-dist:5,base
....

====

[[uses-readline]]
== `readline`

Possible arguments: (none), `port`

Uses readline as a library dependency, and sets `CPPFLAGS` and `LDFLAGS` as necessary. If the `port` argument is used or if readline is not present in the base system, add a dependency on package:devel/readline[]

[[uses-samba]]
== `samba`

Possible arguments: `build`, `env`, `lib`, `run`

Handle dependency on Samba. `env` will not add any dependency and only set up the variables. `build` and `run` will add build-time and run-time dependency on [.filename]#smbd#. `lib` will add a dependency on [.filename]#libsmbclient.so#. The variables that are exported are:

`SAMBAPORT`::
The origin of the default Samba port.

`SAMBAINCLUDES`::
The location of the Samba header files.

`SAMBALIBS`::
The directory where the Samba shared libraries are available.

[[uses-scons]]
== `scons`

Possible arguments: (none)

Provide support for the use of package:devel/scons[]. See <<using-scons>> for more information.

[[uses-shared-mime-info]]
== `shared-mime-info`

Possible arguments: (none)

Uses update-mime-database from package:misc/shared-mime-info[]. This uses will automatically add a post-install step in such a way that the port itself still can specify there own post-install step if needed. It also add an <<plist-keywords-shared-mime-info,`@shared-mime-info`>> entry to the plist.

[[uses-shebangfix]]
== `shebangfix`

Possible arguments: (none)

A lot of software uses incorrect locations for script interpreters, most notably [.filename]#/usr/bin/perl# and [.filename]#/bin/bash#. The shebangfix macro fixes shebang lines in scripts listed in `SHEBANG_REGEX`, `SHEBANG_GLOB`, or `SHEBANG_FILES`.

`SHEBANG_REGEX`::
Contains _one_ extended regular expressions, and is used with the `-iregex` argument of man:find[1]. See <<uses-shebangfix-ex-regex>>.

`SHEBANG_GLOB`::
Contains a list of patterns used with the `-name` argument of man:find[1]. See <<uses-shebangfix-ex-glob>>.

`SHEBANG_FILES`::
Contains a list of files or man:sh[1] globs. The shebangfix macro is run from `${WRKSRC}`, so `SHEBANG_FILES` can contain paths that are relative to `${WRKSRC}`. It can also deal with absolute paths if files outside of `${WRKSRC}` require patching. See <<uses-shebangfix-ex-files>>.

Currently Bash, Java, Ksh, Lua, Perl, PHP, Python, Ruby, Tcl, and Tk are supported by default.

There are three configuration variables:

`SHEBANG_LANG`::
The list of supported interpreters.

`interp_CMD`::
The path to the command interpreter on FreeBSD. The default value is `${LOCALBASE}/bin/_interp_`.

`interp_OLD_CMD`::
The list of wrong invocations of interpreters. These are typically obsolete paths, or paths used on other operating systems that are incorrect on FreeBSD. They will be replaced by the correct path in `interp_CMD`.
+
[NOTE]
====
These will _always_ be part of `interp_OLD_CMD`: `"/usr/bin/env _interp_" /bin/_interp_ /usr/bin/_interp_ /usr/local/bin/_interp_`.
====
+
[TIP]
====

`interp_OLD_CMD` contain multiple values. Any entry with spaces must be quoted. See <<uses-shebangfix-ex-ksh>>.
====

[IMPORTANT]
====
The fixing of shebangs is done during the `patch` phase. If scripts are created with incorrect shebangs during the `build` phase, the build process (for example, the [.filename]#configure# script, or the [.filename]#Makefiles#) must be patched or given the right path (for example, with `CONFIGURE_ENV`, `CONFIGURE_ARGS`, `MAKE_ENV`, or `MAKE_ARGS`) to generate the right shebangs.

Correct paths for supported interpreters are available in `interp_CMD`.
====

[TIP]
====

When used with <<uses-python,`USES=python`>>, and the aim is only to fix the shebangs but a dependency on Python itself is not wanted, use `PYTHON_NO_DEPENDS=yes`.
====

[[uses-shebangfix-ex-lua]]
.Adding Another Interpreter to `USES=shebangfix`
[example]
====

To add another interpreter, set `SHEBANG_LANG`. For example:

[.programlisting]
....
SHEBANG_LANG=	lua
....

====

[[uses-shebangfix-ex-ksh]]
.Specifying all the Paths When Adding an Interpreter to `USES=shebangfix`
[example]
====

If it was not already defined, and there were no default values for `interp_OLD_CMD` and `interp_CMD` the Ksh entry could be defined as:

[.programlisting]
....
SHEBANG_LANG=	ksh
ksh_OLD_CMD=	"/usr/bin/env ksh" /bin/ksh /usr/bin/ksh
ksh_CMD=	${LOCALBASE}/bin/ksh
....

====

[[uses-shebangfix-ex-strange]]
.Adding a Strange Location for an Interpreter
[example]
====

Some software uses strange locations for an interpreter. For example, an application might expect Python to be located in [.filename]#/opt/bin/python2.7#. The strange path to be replaced can be declared in the port [.filename]#Makefile#:

[.programlisting]
....
python_OLD_CMD=	/opt/bin/python2.7
....

====

[[uses-shebangfix-ex-regex]]
.`USES=shebangfix` with `SHEBANG_REGEX`
[example]
====

To fix all the files in `${WRKSRC}/scripts` ending in [.filename]#.pl#, [.filename]#.sh#, or [.filename]#.cgi# do:

[.programlisting]
....
USES=	shebangfix
SHEBANG_REGEX=	./scripts/.*\.(sh|pl|cgi)
....

[NOTE]
****
`SHEBANG_REGEX` is used by running `find -E`, which uses modern regular expressions also known as extended regular expressions. See man:re_format[7] for more information.
****
====

[[uses-shebangfix-ex-glob]]
.`USES=shebangfix` with `SHEBANG_GLOB`
[example]
====
To fix all the files in `${WRKSRC}` ending in [.filename]#.pl# or [.filename]#.sh#, do:

[.programlisting]
....
USES=	shebangfix
SHEBANG_GLOB=	*.sh *.pl
....
====

[[uses-shebangfix-ex-files]]
.`USES=shebangfix` with `SHEBANG_FILES`
[example]
====
To fix the files [.filename]#script/foobar.pl# and [.filename]#script/*.sh# in `${WRKSRC}`, do:

[.programlisting]
....
USES=	shebangfix
SHEBANG_FILES=	scripts/foobar.pl scripts/*.sh
....
====

[[uses-sqlite]]
== `sqlite`

Possible arguments: (none), `2`, `3`

Add a dependency on SQLite. The default version used is 3, but version 2 is also possible using the `:2` modifier.

[[uses-ssl]]
== `ssl`

Possible arguments: (none), `build`, `run`

Provide support for OpenSSL. A build- or run-time only dependency can be specified using `build` or `run`. These variables are available for the port's use, they are also added to `MAKE_ENV`:

`OPENSSLBASE`::
Path to the OpenSSL installation base.

`OPENSSLDIR`::
Path to OpenSSL's configuration files.

`OPENSSLLIB`::
Path to the OpenSSL libraries.

`OPENSSLINC`::
Path to the OpenSSL includes.

`OPENSSLRPATH`::
If defined, the path the linker needs to use to find the OpenSSL libraries.

[TIP]
====

If a port does not build with an OpenSSL flavor, set the `BROKEN_SSL` variable, and possibly the `BROKEN_SSL_REASON_flavor`:

[.programlisting]
....
BROKEN_SSL=	libressl
BROKEN_SSL_REASON_libressl=	needs features only available in OpenSSL
....

====

[[uses-tar]]
== `tar`

Possible arguments: (none), `Z`, `bz2`, `bzip2`, `lzma`, `tbz`, `tbz2`, `tgz`, `txz`, `xz`

Set `EXTRACT_SUFX` to `.tar`, `.tar.Z`, `.tar.bz2`, `.tar.bz2`, `.tar.lzma`, `.tbz`, `.tbz2`, `.tgz`, `.txz` or `.tar.xz` respectively.

[[uses-tcl]]
== `tcl`

Possible arguments: _version_, `wrapper`, `build`, `run`, `tea`

Add a dependency on Tcl. A specific version can be requested using _version_. The version can be empty, one or more exact version numbers (currently `84`, `85`, or `86`), or a minimal version number (currently `84+`, `85+` or `86+`). To only request a non version specific wrapper, use `wrapper`. A build- or run-time only dependency can be specified using `build` or `run`. To build the port using the Tcl Extension Architecture, use `tea`. After including [.filename]#bsd.port.pre.mk# the port can inspect the results using these variables:

* `TCL_VER`: chosen major.minor version of Tcl
* `TCLSH`: full path of the Tcl interpreter
* `TCL_LIBDIR`: path of the Tcl libraries
* `TCL_INCLUDEDIR`: path of the Tcl C header files
* `TK_VER`: chosen major.minor version of Tk
* `WISH`: full path of the Tk interpreter
* `TK_LIBDIR`: path of the Tk libraries
* `TK_INCLUDEDIR`: path of the Tk C header files

[[uses-terminfo]]
== `terminfo`

Possible arguments: (none)

Adds <<plist-keywords-terminfo,`@terminfo`>> to the [.filename]#plist#. Use when the port installs [.filename]#*.terminfo# files in [.filename]#${PREFIX}/shared/misc#.

[[uses-tk]]
== `tk`

Same as arguments for `tcl`

Small wrapper when using both Tcl and Tk. The same variables are returned as when using Tcl.

[[uses-uidfix]]
== `uidfix`

Possible arguments: (none)

Changes some default behavior (mostly variables) of the build system to allow installing this port as a normal user. Try this in the port before using <<uses-fakeroot,USES=fakeroot>> or patching.

[[uses-uniquefiles]]
== `uniquefiles`

Possible arguments: (none), `dirs`

Make files or directories 'unique', by adding a prefix or suffix. If the `dirs` argument is used, the port needs a prefix (and only a prefix) based on `UNIQUE_PREFIX` for standard directories `DOCSDIR`, `EXAMPLESDIR`, `DATADIR`, `WWWDIR`, `ETCDIR`. These variables are available for ports:

* `UNIQUE_PREFIX`: The prefix to be used for directories and files. Default: `${PKGNAMEPREFIX}`.
* `UNIQUE_PREFIX_FILES`: A list of files that need to be prefixed. Default: empty.
* `UNIQUE_SUFFIX`: The suffix to be used for files. Default: `${PKGNAMESUFFIX}`.
* `UNIQUE_SUFFIX_FILES`: A list of files that need to be suffixed. Default: empty.

[[uses-varnish]]
== `varnish`

Possible arguments: `4`, `5`

Handle dependencies on Varnish Cache. `4` will add a dependency on package:www/varnish4[]. `5` will add a dependency on package:www/varnish5[].

[[uses-webplugin]]
== `webplugin`

Possible arguments: (none), `ARGS`

Automatically create and remove symbolic links for each application that supports the webplugin framework. `ARGS` can be one of:

* `gecko`: support plug-ins based on Gecko
* `native`: support plug-ins for Gecko, Opera, and WebKit-GTK
* `linux`: support Linux plug-ins
* `all` (default, implicit): support all plug-in types
* (individual entries): support only the browsers listed

These variables can be adjusted:

* `WEBPLUGIN_FILES`: No default, must be set manually. The plug-in files to install.
* `WEBPLUGIN_DIR`: The directory to install the plug-in files to, default [.filename]#PREFIX/lib/browser_plugins/WEBPLUGIN_NAME#. Set this if the port installs plug-in files outside of the default directory to prevent broken symbolic links.
* `WEBPLUGIN_NAME`: The final directory to install the plug-in files into, default `PKGBASE`.

[[uses-xfce]]
== `xfce`

Possible arguments: (none), `gtk2`

Provide support for Xfce related ports. See <<using-xfce>> for details.

The `gtk2` argument specifies that the port requires GTK2 support. It adds additional features provided by some core components, for example, package:x11/libxfce4menu[] and package:x11-wm/xfce4-panel[].

[[uses-xorg]]
== `xorg`

Possible arguments: (none)

Provides an easy way to depend on X.org components. The components should be listed in `USE_XORG`. The available components are:
[[using-x11-components]]
.Available X.Org Components
[cols="1,1", frame="none", options="header"]
|===
| Name
| Description

|`dmx`
|DMX extension library

|`fontenc`
|The fontenc Library

|`fontutil`
|Create an index of X font files in a directory

|`ice`
|Inter Client Exchange library for X11

|`libfs`
|The FS library

|`pciaccess`
|Generic PCI access library

|`pixman`
|Low-level pixel manipulation library

|`sm`
|Session Management library for X11

|`x11`
|X11 library

|`xau`
|Authentication Protocol library for X11

|`xaw`
|X Athena Widgets library

|`xaw6`
|X Athena Widgets library

|`xaw7`
|X Athena Widgets library

|`xbitmaps`
|X.Org bitmaps data

|`xcb`
|The X protocol C-language Binding (XCB) library

|`xcomposite`
|X Composite extension library

|`xcursor`
|X client-side cursor loading library

|`xdamage`
|X Damage extension library

|`xdmcp`
|X Display Manager Control Protocol library

|`xext`
|X11 Extension library

|`xfixes`
|X Fixes extension library

|`xfont`
|X font library

|`xfont2`
|X font library

|`xft`
|Client-sided font API for X applications

|`xi`
|X Input extension library

|`xinerama`
|X11 Xinerama library

|`xkbfile`
|XKB file library

|`xmu`
|X Miscellaneous Utilities libraries

|`xmuu`
|X Miscellaneous Utilities libraries

|`xorg-macros`
|X.Org development aclocal macros

|`xorg-server`
|X.Org X server and related programs

|`xorgproto`
|xorg protocol headers

|`xpm`
|X Pixmap library

|`xpresent`
|X Present Extension library

|`xrandr`
|X Resize and Rotate extension library

|`xrender`
|X Render extension library

|`xres`
|X Resource usage library

|`xscrnsaver`
|The XScrnSaver library

|`xshmfence`
|Shared memory 'SyncFence' synchronization primitive

|`xt`
|X Toolkit library

|`xtrans`
|Abstract network code for X

|`xtst`
|X Test extension

|`xv`
|X Video Extension library

|`xvmc`
|X Video Extension Motion Compensation library

|`xxf86dga`
|X DGA Extension

|`xxf86vm`
|X Vidmode Extension
|===

[[uses-xorg-cat]]
== `xorg-cat`

Possible arguments: `app`, `data`, `doc`, `driver`, `font`, `lib`, `proto`, `util`, `xserver` and (none) or one off `autotools` (default), `meson`

Provide support for building Xorg components. It takes care of setting up common dependencies and an appropriate configuration environment needed. This is intended only for Xorg components.

The category has to match upstream categories.

The second argument is the build system to use. autotools is the default, but meson is also supported.

[[uses-zip]]
== `zip`

Possible arguments: (none), `infozip`

Indicates that the distribution files use the ZIP compression algorithm. For files using the InfoZip algorithm the `infozip` argument must be passed to set the appropriate dependencies.
