# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq2.xml
DOCS+=	faq28.xml
DOCS+=	faq210.xml
DOCS+=	faq212.xml
DOCS+=	faq214.xml
DOCS+=	faq216.xml
DOCS+=	faq218.xml
DOCS+=	faq220.xml
DOCS+=	faq222.xml
DOCS+=	faq224.xml
DOCS+=	faq226.xml
DOCS+=	faq228.xml
DOCS+=	faq230.xml
DOCS+=	faq232.xml
DOCS+=	gnome_porting.xml
DOCS+=	gnome1_porting.xml
DOCS+=	gnome2_porting.xml
DOCS+=	porting.xml
DOCS+=	bugging.xml
DOCS+=  volunteer.xml
DOCS+=	develfaq.xml
DOCS+=	example-Makefile.xml
DOCS+=	halfaq.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
