# $Id: Makefile,v 1.5 1999-08-29 00:02:20 jhb Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ../../..

.include "${DOC_PREFIX}/share/mk/docproj.docbook.mk"
