#
# Build the Handbook with just the content from this chapter.
#
# %SOURCE%    en_US.ISO8859-1/books/handbook/l10n/Makefile
# %SRCID%     1.1
#
# $FreeBSD$
#

CHAPTERS= 	l10n/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
