---
title: "The FreeBSD GNOME Project"
sidenav: gnome
--- 

= The FreeBSD GNOME Project

== What software does the GNOME Team maintain?

The GNOME Team maintains the GNOME, MATE, and Cinnamon desktop environments.

== What is GNOME?

GNOME is a complete graphical desktop for X, including everything from a window manager to web browsers, audio players, office programs, graphical login programs and more. MATE is a continuation of the old GNOME 2 desktop environment. Cinnamon is originally a fork of GNOME 3's gnome-shell, but grew into its own desktop environment.

== How to install these desktop environments?

There are some so called meta ports available for installing these desktop environments or parts of them. They are: 

* gnome3 (full GNOME desktop)
* gnome3-lite (minimal GNOME desktop)
* mate (full MATE desktop)
* mate-lite (minimal MATE desktop)
* cinnamon

The easiest way of installing is to run the following command and replace gnome3 with the desktop environment of choice:

....
# pkg install gnome3
....

Or if you prefer to build from source:

....
# cd /usr/ports/x11/gnome3
# make clean
# make install clean
....

== State of the port:

GNOME, MATE, and Cinnamon for FreeBSD are currently fully supported on 11.1, 11-STABLE, and 10.4, while support for 12.0-CURRENT is provided on a best effort basis.

GNOME is simple and easy to build using the FreeBSD ports system, but sometimes things simply go wrong. Please see our link:docs/bugging/[Bug reporting] page for more info.

== Resources

* link:https://wiki.freebsd.org/Gnome[FreeBSD GNOME's wiki page]
* link:https://www.gnome.org/[GNOME Project]
* link:https://news.gnome.org/[GNOME Project news]
* link:https://developer.gnome.org/[GNOME development platform]
* link:http://planet.gnome.org/[Planet GNOME (blogs)]
* link:https://mate-desktop.org/[MATE Project]
* link:https://github.com/linuxmint/Cinnamon[Cinnamon Project]

== Related Projects

* link:https://www.kde.org/[KDE Project]
* link:https://freebsd.kde.org/[KDE on FreeBSD]
* link:https://www.xfce.org/[XFCE Project]
* link:https://wiki.freebsd.org/Xfce[XFCE on FreeBSD]
* link:http://www.opengroup.org/cde/[CDE]
