# $FreeBSD: www/en/marketing/Makefile,v 1.1 2005/05/08 15:53:13 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml os-comparison.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
