---
title: Κεφάλαιο 10. Εκτυπώσεις
part: Μέρος II. Βασικές Εργασίες
prev: books/handbook/kernelconfig
next: books/handbook/linuxemu
---

[[printing]]
= Εκτυπώσεις
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Πίνακας Περιεχομένων
:table-caption: Πίνακας
:figure-caption: Σχήμα
:example-caption: Παράδειγμα
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 10

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/printing/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/printing/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/printing/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/el/mailing-lists.adoc[]
include::shared/el/teams.adoc[]
include::shared/el/urls.adoc[]

toc::[]

[[printing-synopsis]]
== Σύνοψη

Μπορείτε να χρησιμοποιήσετε το FreeBSD για να κάνετε εκτυπώσεις σε διάφορους τύπους εκτυπωτών, από τον παλαιότερο κρουστικό ως τον πιο σύγχρονο laser εκτυπωτή, καθώς και οποιασδήποτε άλλης τεχνολογίας ανάμεσα τους, και να δημιουργήσετε εκτυπώσεις υψηλής ποιότητας με τις εφαρμογές που εκτελείτε.

Το FreeBSD μπορεί επίσης να ρυθμιστεί ώστε να λειτουργεί ως εξυπηρετητής εκτυπώσεων δικτύου. Με αυτή τη δυνατότητα το FreeBSD μπορεί να λαμβάνει εργασίες εκτύπωσης από διάφορους άλλους υπολογιστές, συμπεριλαμβανομένων υπολογιστών FreeBSD, Windows(R) και Mac OS(R). Το FreeBSD μπορεί να εξασφαλίζει ότι μόνο μια εργασία θα τυπώνεται κάθε χρονική στιγμή και μπορεί να τηρεί στατιστικά για τους χρήστες και τα μηχανήματα που θα κάνουν τις περισσότερες εκτυπώσεις, να παράγει σελίδες "banner" που να δείχνουν σε ποιόν ανήκει η κάθε εκτύπωση, και πολλά άλλα.

Αφού διαβάσετε αυτό το κεφάλαιο θα ξέρετε:

* Πως να ρυθμίσετε την ουρά εκτυπώσεων (print spooler) του FreeBSD.
* Πως να εγκαθιστάτε φίλτρα εκτύπωσης, να χειρίζεστε ειδικές εργασίες εκτύπωσης (π.χ. τη μετατροπή εισερχόμενων κειμένων σε μορφές εκτύπωσης που είναι κατανοητές από τους εκτυπωτές σας).
* Πως να ενεργοποιήσετε σελίδες τύπου κεφαλίδας ή banner στις εκτυπώσεις σας.
* Πως να εκτυπώνετε σε εκτυπωτές που είναι συνδεδεμένοι σε άλλους υπολογιστές.
* Πως να εκτυπώνετε σε εκτυπωτές που είναι συνδεδεμένοι απευθείας στο δίκτυο.
* Πως να ελέγχετε τους περιορισμούς εκτύπωσης, συμπεριλαμβανομένων των περιορισμών μεγέθους των εργασιών εκτύπωσης, και πως να παρεμποδίζετε την δυνατότητα εκτύπωσης σε συγκεκριμένους χρήστες.
* Πως να κρατήσετε στατιστικά για τον εκτυπωτή, και καταγραφή για τη χρήση του εκτυπωτή από κάθε χρήστη.
* Πως να αντιμετωπίσετε προβλήματα στις εκτυπώσεις.

Πριν διαβάσετε αυτό το κεφάλαιο, θα πρέπει:

* Να γνωρίζετε πως να ρυθμίσετε και να εγκαταστήσετε ένα νέο πυρήνα (crossref:kernelconfig[kernelconfig,Ρυθμίζοντας τον Πυρήνα του FreeBSD]).

[[printing-intro-spooler]]
== Εισαγωγή

Για να χρησιμοποιήσετε εκτυπωτές στο FreeBSD, θα χρειαστεί να ρυθμίσετε τη λειτουργία τους με το σύστημα παροχέτευσης (spooling) εκτυπωτών γραμμής του Berkeley, γνωστό επίσης και ως σύστημα παροχέτευσης LPD, ή απλά LPD. Αυτό είναι το προκαθορισμένο σύστημα ελέγχου εκτυπωτών στο FreeBSD. Το κεφάλαιο αυτό είναι μια εισαγωγή στο LPD και θα σας καθοδηγήσει στις ρυθμίσεις του.

Εάν σας είναι οικείο το LPD ή κάποιο άλλο σύστημα παροχέτευσης εκτυπωτών, τότε μπορείτε να μεταπηδήσετε στην ενότητα <<printing-intro-setup,Βασική Εγκατάσταση>>.

Το LPD μπορεί να ελέγχει εξ' ολοκλήρου όλες τις λειτουργίες των εκτυπωτών ενός υπολογιστή. Είναι κυρίως υπεύθυνο για ένα πλήθος λειτουργιών:

* Ελέγχει την πρόσβαση σε απευθείας συνδεμένους εκτυπωτές και εκτυπωτές προσαρτημένους σε άλλους κόμβους στο δίκτυο.
* Επιτρέπει σε χρήστες να στέλνουν αρχεία προς εκτύπωση. Οι αποστολές αυτές είναι γνωστές ως _εργασίες (jobs)_.
* Διατηρεί _ουρά αναμονής (queue)_ για κάθε εκτυπωτή, ώστε να προλαμβάνει την ταυτόχρονη πρόσβαση από πολλούς χρήστες.
* Μπορεί να εκτυπώνει _σελίδες κεφαλίδας_ (γνωστές επίσης ως _banner_ ή _σελίδες burst_) ώστε οι χρήστες να μπορούν εύκολα να ξεχωρίσουν τις εργασίες τους μέσα στην στοίβα εκτυπώσεων.
* Φροντίζει για την ορθότητα των παραμέτρων επικοινωνίας των εκτυπωτών που είναι συνδεδεμένοι σε σειριακές θύρες.
* Μπορεί μέσω του δικτύου να στείλει εργασίες σε σύστημα παροχέτευσης LPD διαφορετικού υπολογιστή.
* Μπορεί να εκτελέσει διάφορα φίλτρα για να προσαρμόσει εργασίες ώστε να είναι δυνατή η εκτύπωση τους σε εκτυπωτές που χρησιμοποιούν διαφορετικές γλώσσες ή έχουν διαφορετικές δυνατότητες.
* Μπορεί να κάνει καταμέτρηση χρήσης του εκτυπωτή.

Μέσω του αρχείου ρύθμισης ([.filename]#/etc/printcap#), και με τη βοήθεια ειδικών προγραμμάτων φίλτρων, μπορείτε να ενεργοποιήσετε το σύστημα LPD να κάνει όλες ή κάποιες από τις παραπάνω εργασίες σε μια μεγάλη γκάμα συσκευών εκτύπωσης.

[[printing-intro-why]]
=== Γιατί θα πρέπει να χρησιμοποιείτε τον Spooler

Αν είστε ο μοναδικός χρήστης του συστήματος, θα αναρωτιέστε γιατί θα έπρεπε να ενδιαφερθείτε για τον spooler αφού δεν χρειάζεστε έλεγχο πρόσβασης, σελίδες κεφαλίδας, ή αναφορές εκτύπωσης. Αν και μπορείτε να ενεργοποιήσετε την άμεση πρόσβαση στον εκτυπωτή, είναι καλύτερα να χρησιμοποιείτε τον spooler για τους παρακάτω λόγους:

* το LPD εκτυπώνει τις εργασίες στο παρασκήνιο, δεν χρειάζεται να περιμένετε να αντιγραφούν τα δεδομένα στον εκτυπωτή.
* Το LPD μπορεί άνετα να εκτελεί μια εργασία εκτύπωσης διαμέσου φίλτρων και να προσθέτει κεφαλίδες ημερομηνίας/ώρας ή να μετατρέπει κάποιο ειδικό τύπο αρχείου (όπως ένα αρχείο TeX DVI) σε ένα τύπο κατανοητό από τον εκτυπωτή σας. Αυτές οι διαδικασίες δεν χρειάζεται να γίνονται χειροκίνητα.
* Πολλά από τα ελεύθερα και εμπορικά διαθέσιμα προγράμματα που παρέχουν διευκολύνσεις στην εκτύπωση, συνήθως επιζητούν να επικοινωνήσουν με τον spooler του συστήματος σας. Ρυθμίζοντας το σύστημα παροχέτευσης, θα μπορείτε ευκολότερα να υποστηρίζετε λογισμικό τρίτων, που μπορεί ήδη να έχετε ή που πρόκειται να εγκαταστήσετε στο μέλλον.

[[printing-intro-setup]]
== Βασική Εγκατάσταση

[WARNING]
====

Από το FreeBSD 8.0 και μετά, τα αρχεία συσκευών για τις σειριακές θύρες μετονομάστηκαν από [.filename]#/dev/ttydN# σε [.filename]#/dev/ttyuN#. Οι χρήστες του FreeBSD 7.X θα πρέπει να προσαρμόσουν την τεκμηρίωση που ακολουθεί με βάση αυτές τις αλλαγές.
====

Για να χρησιμοποιήσετε εκτυπωτές με το σύστημα παροχέτευσης LPD, θα πρέπει να εγκαταστήσετε τόσο το hardware του εκτυπωτή σας όσο και το λογισμικό LPD. Αυτό το έγγραφο περιγράφει την εγκατάσταση σε δύο στάδια:

* Δείτε την ενότητα <<printing-simple,Βασικές Ρυθμίσεις Εκτυπωτών>> για να μάθετε πως γίνεται η σύνδεση εκτυπωτών, με ποιο τρόπο επικοινωνεί το LPD με τους εκτυπωτές, και πως να εκτυπώνετε απλά αρχεία κειμένου.
* Δείτε την ενότητα <<printing-advanced,Ρυθμίσεις Εκτυπωτών για Προχωρημένους>> για να μάθετε πως να εκτυπώνετε αρχεία ειδικής μορφής διαφόρων τύπων, πως να εκτυπώνετε σελίδες κεφαλίδας, πως να εκτυπώνετε σε ένα δίκτυο, πως να ελέγχετε την πρόσβαση στους εκτυπωτές, και πως να χρησιμοποιείτε την καταγραφή εκτυπώσεων.

[[printing-simple]]
=== Βασικές Ρυθμίσεις Εκτυπωτών

Αυτή η ενότητα περιγράφει πως να ρυθμίσετε το hardware του εκτυπωτή και το λογισμικό LPD. Παρέχει βασικές γνώσεις για τα εξής θέματα:

* Η Ενότητα <<printing-hardware,Ρυθμίσεις Hardware>> υποδεικνύει πως να συνδέσετε τον εκτυπωτή σε μια θύρα του υπολογιστή σας.
* Η Ενότητα <<printing-software,Ρυθμίσεις Λογισμικού>> υποδεικνύει πως να εγκαταστήσετε το αρχείο ρύθμισης του συστήματος παροχέτευσης LPD: το αρχείο [.filename]#/etc/printcap#.

Αν προσπαθείτε να εγκαταστήσετε έναν εκτυπωτή που δέχεται δεδομένα μέσω πρωτοκόλλου δικτύου και όχι μέσω διασύνδεσης τοπικής θύρας, τότε δείτε την ενότητα <<printing-advanced-network-net-if,Εκτυπωτές Με Συνδέσεις Δικτύου>>.

Αν και αυτή η ενότητα ονομάζεται "Βασικές Ρυθμίσεις Εκτυπωτών", στην πραγματικότητα είναι αρκετά περίπλοκη. Το δυσκολότερο στάδιο στην εγκατάσταση είναι η επιτυχής λειτουργία στην επικοινωνία του εκτυπωτή με τον υπολογιστή σας και το σύστημα παροχέτευσης LPD. Οι επιλογές για προχωρημένους, όπως οι σελίδες κεφαλίδας και αναφοράς είναι σχετικά εύκολες να επιτευχθούν, μετά την επιτυχή ρύθμιση της βασικής λειτουργίας εκτύπωσης.

[[printing-hardware]]
==== Ρυθμίσεις Hardware

Αυτή η ενότητα εξηγεί τους διάφορους τρόπους σύνδεσης του εκτυπωτή με τον υπολογιστή σας. Περιγράφει τους διάφορους τύπους θυρών και καλωδίων, και τις ρυθμίσεις που πρέπει να κάνετε στον πυρήνα για να ενεργοποιήσετε την επικοινωνία μεταξύ FreeBSD και εκτυπωτή.

Αν ήδη έχετε καταφέρει να συνδέσετε τον εκτυπωτή σας και έχετε εκτυπώσει επιτυχώς σε άλλο λειτουργικό σύστημα, τότε μπορείτε να μεταβείτε κατευθείαν στην ενότητα <<printing-software,Ρυθμίσεις Λογισμικού>>.

[[printing-ports]]
===== Θύρες και Καλώδια

Οι εκτυπωτές που διατίθενται σήμερα για χρήση με Η/Υ παρέχονται με μία ή περισσότερες εκ των ακολούθων τριών διασυνδέσεων:

* Οι _Σειριακές_ διασυνδέσεις, γνωστές και ως RS-232 ή θύρες COM, χρησιμοποιούν την σειριακή θύρα του υπολογιστή σας για να στείλουν δεδομένα στον εκτυπωτή. Οι σειριακές διασυνδέσεις είναι συνήθεις στην βιομηχανία κατασκευής Η/Υ και τα καλώδια είναι εκτενώς διαδεδομένα και επίσης εύκολα να κατασκευαστούν. Οι σειριακές διασυνδέσεις μερικές φορές χρειάζονται ειδικά καλώδια και μπορεί να σας ζητηθούν πολύπλοκες επικοινωνιακές ρυθμίσεις. Οι περισσότερες σειριακές θύρες των Η/Υ έχουν μέγιστη ταχύτητα μετάδοσης 115200 bps, κάνοντας δύσκολη την εργασία εκτύπωσης γραφικών μεγάλων διαστάσεων.
* Οι _Παράλληλες_ διασυνδέσεις χρησιμοποιούν την παράλληλη θύρα του υπολογιστή σας για να στέλνουν δεδομένα στον εκτυπωτή. Οι παράλληλες διασυνδέσεις είναι διαδεδομένες στο εμπόριο και είναι γρηγορότερες από τις σειριακές RS-232. Τα καλώδια διατίθενται έτοιμα, αλλά είναι δυσκολότερο να κατασκευαστούν χειρωνακτικά. Με τις παράλληλες διασυνδέσεις δεν προβλέπονται επιλογές ρύθμισης επικοινωνίας, κάνοντας την ρύθμιση τους εξαιρετικά απλή.
+ 
Οι παράλληλες διασυνδέσεις είναι γνωστές και ως διασυνδέσεις "Centronics", ονομασία προερχόμενη από τον τύπο του ακροδέκτη του εκτυπωτή.
* Οι διασυνδέσεις USB, συντομογραφία από το Universal Serial Bus, δουλεύουν σε ακόμη μεγαλύτερες ταχύτητες από την παράλληλη και την RS-232 σειριακή διασύνδεση. Τα καλώδια τους είναι απλά και φτηνά. Η USB είναι ανώτερη από την Σειριακή RS-232 και από την Παράλληλη στην εκτύπωση, αλλά δυστυχώς δεν υποστηρίζεται καλά από τα συστήματα UNIX(R). Ένας τρόπος για να αποφύγετε αυτό το πρόβλημα είναι να αγοράσετε εκτυπωτή που φέρει διασύνδεση USB και Παράλληλη, όπως συμβαίνει με πολλούς εκτυπωτές.

Γενικά, οι Παράλληλες διασυνδέσεις προσφέρουν συνήθως μίας κατεύθυνσης επικοινωνία (από τον υπολογιστή στον εκτυπωτή) ενώ η σειριακή και η USB δίνουν αμφίδρομη. Στο FreeBSD οι πιο πρόσφατες παράλληλες θύρες (EPP και ECP) καταφέρνουν αμφίδρομη επικοινωνία με τους εκτυπωτές, όταν χρησιμοποιούνται καλώδια που συμμορφώνονται με το πρότυπο IEEE-1284.

Η αμφίδρομη επικοινωνία με εκτυπωτές διαμέσου παράλληλης θύρας μπορεί να επιτευχθεί γενικά με δύο τρόπους. Ο πρώτος τρόπος χρησιμοποιεί ένα προσαρμοσμένο πρόγραμμα οδήγησης εκτυπωτή, ώστε να μπορεί το FreeBSD να συνομιλεί στην γλώσσα του εκτυπωτή. Αυτό είναι σύνηθες με εκτυπωτές inkjet και μπορεί επίσης να χρησιμοποιηθεί για αναφορές διαθέσιμης ποσότητας μελανιού και για άλλες πληροφορίες λειτουργίας. Η δεύτερη μέθοδος χρησιμοποιείται όταν ο εκτυπωτής έχει δυνατότητα υποστήριξης PostScript(R).

Οι εργασίες PostScript(R) είναι στην πραγματικότητα προγράμματα που αποστέλλονται στον εκτυπωτή, δεν είναι απαραίτητο να παράγουν εκτυπώσεις, ενώ μπορούν να επιστρέψουν το αποτέλεσμα τους απευθείας στον υπολογιστή. Το PostScript(R) χρησιμοποιεί αμφίδρομη επικοινωνία για να ενημερώσει τον υπολογιστή για τυχόν προβλήματα, όπως σφάλματα στο πρόγραμμα PostScript(R) ή μπλοκάρισμα τροφοδοσίας χαρτιού. Οι χρήστες σας, θα σας είναι ευγνώμονες για αυτές τις πληροφορίες. Επιπλέον, ο καλύτερος τρόπος για να κάνετε σωστή καταμέτρηση με ένα αμφίδρομο εκτυπωτή PostScript(R) είναι: να ρωτήσετε τον εκτυπωτή για την συνολική καταμέτρηση των σελίδων του (πόσες σελίδες εκτύπωσε σε όλη τη διάρκεια ζωής του), μετά να αποστείλετε την εργασία του χρήστη, και έπειτα να ξαναρωτήσετε για την καταμέτρηση των σελίδων του. Αφαιρέστε τις δύο τιμές και θα γνωρίζετε πόσες σελίδες να χρεώσετε στον χρήστη.

[[printing-parallel]]
===== Παράλληλες Θύρες

Για να συνδέσετε έναν εκτυπωτή σε παράλληλη θύρα, συνδέστε το καλώδιο Centronics μεταξύ εκτυπωτή και υπολογιστή. Οι οδηγίες που συνοδεύουν τον εκτυπωτή και τον υπολογιστή θα σας καθοδηγήσουν να ολοκληρώσετε την σύνδεση.

Θυμηθείτε ποια παράλληλη θύρα χρησιμοποιείτε στον υπολογιστή. Η πρώτη παράλληλη θύρα στο FreeBSD είναι η [.filename]#ppc0#, η δεύτερη είναι η [.filename]#ppc1#, και ούτω καθεξής. Το όνομα συσκευής του εκτυπωτή χρησιμοποιεί την ίδια αρίθμηση: [.filename]#/dev/lpt0# για τον εκτυπωτή στην πρώτη παράλληλη θύρα κ.τ.λ.

[[printing-serial]]
===== Σειριακές Θύρες

Για να συνδέσετε έναν εκτυπωτή χρησιμοποιώντας σειριακή διασύνδεση, συνδέστε το κατάλληλο σειριακό καλώδιο μεταξύ εκτυπωτή και υπολογιστή. Οι οδηγίες που συνοδεύουν τον εκτυπωτή και τον υπολογιστή σας, θα σας καθοδηγήσουν να ολοκληρώσετε την σύνδεση.

Αν δεν είστε σίγουροι ποιο είναι το "κατάλληλο σειριακό καλώδιο", μπορείτε να δοκιμάσετε μία από τις ακόλουθες εναλλακτικές:

* Ένα καλώδιο _modem_ ενώνει κάθε pin του ακροδέκτη από τη μια πλευρά του καλωδίου κατευθείαν με το αντίστοιχο pin του ακροδέκτη στο άλλο άκρο. Αυτός ο τύπος καλωδίου είναι γνωστός και ως καλώδιο "DTE-to-DCE".
* Ένα καλώδιο _null-modem_ ενώνει κατευθείαν μερικά pins, ανταλλάσσει μερικά άλλα (για παράδειγμα, τα pins αποστολής και λήψης), ενώ βραχυκυκλώνει μερικά άλλα, εσωτερικά, στο προστατευτικό κάλυμμα κάθε ακροδέκτη. Αυτός ο τύπος καλωδίου είναι γνωστός και ως καλώδιο "DTE-to-DTE".
* Ένα καλώδιο _σειριακού εκτυπωτή_, που απαιτείται από κάποιους λιγότερο συνηθισμένους εκτυπωτές, είναι σαν το καλώδιο null-modem, αλλά στέλνει ισοδύναμα σήματα και στα δύο άκρα αντί να τα βραχυκυκλώνει εσωτερικά.

Θα πρέπει επίσης να ρυθμίσετε τις παραμέτρους επικοινωνίας του εκτυπωτή, συνήθως από τον μπροστινό πίνακα ελέγχου ή από τους DIP διακόπτες του. Επιλέξτε την μέγιστη τιμή `bps` (bits per second = bits ανά δευτερόλεπτο, αναφέρεται και ως _ρυθμός baud_) που υποστηρίζουν ο υπολογιστής και ο εκτυπωτής σας. Επιλέξτε 7 ή 8 data bits, none, even, ή odd parity, και 1 ή 2 stop bits. Επίσης επιλέξτε ένα πρωτόκολλο ελέγχου ροής: είτε none, ή XON/XOFF (αναφέρεται και ως έλεγχος ροής "in-band" ή "software"). Να θυμάστε αυτές τις ρυθμίσεις, για το στάδιο ρύθμισης λογισμικού που ακολουθεί.

[[printing-software]]
==== Ρυθμίσεις Λογισμικού

Αυτή η ενότητα περιγράφει τις αναγκαίες ρυθμίσεις που πρέπει να γίνουν στο λογισμικό για να μπορείτε να εκτυπώνετε με το σύστημα παροχέτευσης εκτυπωτών LPD στο FreeBSD.

Μια γενική άποψη των ενεργειών που πρέπει να ακολουθήσετε είναι:

[.procedure]
. Ρυθμίστε τον πυρήνα σας, αν είναι αναγκαίο, για την θύρα που χρησιμοποιείτε για τον εκτυπωτή σας. Οι απαραίτητες ρυθμίσεις περιγράφονται στην ενότητα <<printing-kernel,Ρυθμίσεις Πυρήνα>>.
. Ρυθμίστε την κατάσταση επικοινωνίας για την παράλληλη θύρα, αν πρόκειται να την χρησιμοποιήσετε. Η ενότητα <<printing-parallel-port-mode,Ρυθμίσεις Κατάστασης Επικοινωνίας για την Παράλληλη Θύρα>> περιέχει λεπτομέρειες.
. Ελέγξτε αν το λειτουργικό σύστημα μπορεί να στείλει δεδομένα στον εκτυπωτή. Η ενότητα <<printing-testing,Έλεγχος Επικοινωνίας του Εκτυπωτή>> παρέχει μερικές συμβουλές για το πως θα μπορούσε να γίνει ο έλεγχος.
. Ρυθμίστε το LPD για τον εκτυπωτή σας, τροποποιώντας το αρχείο [.filename]#/etc/printcap#. Θα βρείτε οδηγίες για αυτές τις ρυθμίσεις σε επόμενο τμήμα αυτού του κεφαλαίου.

[[printing-kernel]]
===== Ρυθμίσεις Πυρήνα

Ο πυρήνας του λειτουργικού συστήματος έχει μεταγλωττιστεί έτσι ώστε να δουλεύει με ένα συγκεκριμένο σύνολο συσκευών. Η σειριακή και η παράλληλη διασύνδεση του εκτυπωτή είναι μέρος αυτού του συνόλου. Επομένως, ίσως να είναι αναγκαίο να προσθέσετε υποστήριξη για κάποια πρόσθετη σειριακή ή παράλληλη θύρα, αν δεν είναι ήδη ρυθμισμένη στον πυρήνα σας.

Για να ελέγξετε αν ο πυρήνας σας μπορεί να υποστηρίξει μια σειριακή διασύνδεση, πληκτρολογήστε:

[source,bash]
....
# grep sioN /var/run/dmesg.boot
....

Όπου _N_ είναι ο αριθμός της σειριακής θύρας, ξεκινώντας από το μηδέν. Αν δείτε στην έξοδο του τερματικού σας κάτι παρόμοιο με:

[source,bash]
....
sio2 at port 0x3e8-0x3ef irq 5 on isa
sio2: type 16550A
....

τότε ο πυρήνας υποστηρίζει αυτή τη θύρα.

Για να ελέγξετε αν ο πυρήνας σας υποστηρίζει παράλληλες διασυνδέσεις, πληκτρολογήστε:

[source,bash]
....
# grep ppcN /var/run/dmesg.boot
....

Όπου _N_ είναι ο αριθμός της παράλληλης θύρας, ξεκινώντας από το μηδέν. Αν δείτε στην έξοδο του τερματικού σας κάτι παρόμοιο με:

[source,bash]
....
ppc0: <Parallel port> at port 0x378-0x37f irq 7 on isa0
ppc0: SMC-like chipset (ECP/EPP/PS2/NIBBLE) in COMPATIBLE mode
ppc0: FIFO with 16/16/8 bytes threshold
....

τότε ο πυρήνας υποστηρίζει αυτή τη θύρα.

Για να μπορεί το λειτουργικό σύστημα να αναγνωρίζει και να χρησιμοποιεί την θύρα (παράλληλη ή σειριακή) για τον εκτυπωτή σας, ίσως χρειαστεί να επαναπροσαρμόσετε τον πυρήνα σας.

Για την υποστήριξη σειριακής θύρας, δείτε την ενότητα στις ρυθμίσεις του πυρήνα. Για την υποστήριξη παράλληλης θύρας, δείτε την ίδια ενότητα _και_ την ενότητα που ακολουθεί.

[[printing-parallel-port-mode]]
==== Ρυθμίσεις Κατάστασης Επικοινωνίας για την Παράλληλη Θύρα

Όταν χρησιμοποιείτε την παράλληλη διασύνδεση, μπορείτε να επιλέξετε αν η επικοινωνία του FreeBSD με τον εκτυπωτή θα είναι τύπου interrupt-driven ή polled. Ο γενικός οδηγός συσκευής του εκτυπωτή (man:lpt[4]) στο FreeBSD χρησιμοποιεί το σύστημα man:ppbus[4], το οποίο ελέγχει την θύρα του chipset με τον οδηγό man:ppc[4].

* Η μέθοδος _interrupt-driven_ είναι προεπιλεγμένη στον πυρήνα GENERIC. Με αυτή τη μέθοδο, το λειτουργικό σύστημα χρησιμοποιεί ένα σήμα IRQ για να προσδιορίσει αν ο εκτυπωτής είναι έτοιμος για δεδομένα.
* Η μέθοδος _polled_ οδηγεί το λειτουργικό σύστημα να ζητά κατά επανάληψη από τον εκτυπωτή αν είναι έτοιμος για πρόσθετα δεδομένα. Όταν απαντήσει θετικά, ο πυρήνας στέλνει πρόσθετα δεδομένα.

Η μέθοδος interrupt-driven είναι συνήθως κάπως γρηγορότερη αλλά χρησιμοποιεί μια πολύτιμη γραμμή IRQ. Έχει παρατηρηθεί πως κάποιοι σύγχρονοι εκτυπωτές HP δε δουλεύουν σωστά σε κατάσταση interrupt, πιθανώς λόγω κάποιων (όχι απόλυτα εξακριβωμένων) προβλημάτων συγχρονισμού. Αυτοί οι εκτυπωτές χρειάζονται την μέθοδο polled. Θα πρέπει να χρησιμοποιείτε την αποτελεσματικότερη κατάσταση λειτουργίας. Κάποιοι εκτυπωτές δουλεύουν και στις δυο καταστάσεις, αλλά είναι οδυνηρά αργοί στην κατάσταση λειτουργίας interrupt.

Μπορείτε να ρυθμίσετε την κατάσταση επικοινωνίας με δύο τρόπους: ρυθμίζοντας τον πυρήνα ή χρησιμοποιώντας το πρόγραμμα man:lptcontrol[8].

_Για να θέσετε την κατάσταση επικοινωνίας ρυθμίζοντας τον πυρήνα:_

[.procedure]
. Επεξεργαστείτε το αρχείο ρύθμισης του πυρήνα. Δείτε την καταχώριση `ppc0`. Αν εγκαθιστάτε την δεύτερη παράλληλη θύρα, τότε χρησιμοποιείστε `ppc1`. Για την τρίτη θύρα `ppc2` και ούτω καθεξής.

** Αν επιθυμείτε κατάσταση λειτουργίας interrupt-driven, επεξεργαστείτε την ακόλουθη γραμμή:
+
[.programlisting]
....
hint.ppc.0.irq="N"
....

+ 
στο αρχείο [.filename]#/boot/device.hints# και αντικαταστήστε το _N_ με τον σωστό αριθμό IRQ. Το αρχείο ρύθμισης του πυρήνα πρέπει επίσης να περιέχει τον οδηγό man:ppc[4]:
+

[source,bash]
....
device ppc
....

** Αν επιθυμείτε κατάσταση λειτουργίας polled, διαγράψτε από το αρχείο [.filename]#/boot/device.hints#, την ακόλουθη γραμμή:
+
[.programlisting]
....
hint.ppc.0.irq="N"
....

+ 
Σε μερικές περιπτώσεις, το παραπάνω δεν είναι αρκετό για να θέσετε την θύρα σε κατάσταση polled. Τις περισσότερες φορές το πρόβλημα προέρχεται από τον οδηγό man:acpi[4], ο οποίος έχει την ευχέρεια να εξετάζει και να προσαρτά συσκευές, και επομένως, να ελέγχει τον τρόπο πρόσβασης στην θύρα του εκτυπωτή. Θα πρέπει να ελέγξετε τις ρυθμίσεις του man:acpi[4] για να διορθώσετε αυτό το πρόβλημα.

. Αποθηκεύστε το αρχείο. Ρυθμίστε, μεταγλωττίστε, και εγκαταστήστε τον πυρήνα, και έπειτα κάντε επανεκκίνηση. Για περισσότερες λεπτομέρειες, δείτε τις crossref:kernelconfig[kernelconfig,ρυθμίσεις του πυρήνα].

_Για να θέσετε την κατάσταση επικοινωνίας με το_ man:lptcontrol[8]:

[.procedure]
. Πληκτρολογήστε:
+

[source,bash]
....
# lptcontrol -i -d /dev/lptN
....

+ 
για να θέσετε την κατάσταση λειτουργίας interrupt-driven για το `lptN`.
. Πληκτρολογήστε:
+

[source,bash]
....
# lptcontrol -p -d /dev/lptN
....

+ 
για να θέσετε την κατάσταση λειτουργίας polled για το `lptN`.

Θα μπορούσατε να καταχωρίσετε αυτές τις εντολές στο δικό σας αρχείο [.filename]#/etc/rc.local#. Έτσι θα εκτελούνται αυτόματα κατά την εκκίνηση του συστήματος σας. Για περισσότερες πληροφορίες δείτε το man:lptcontrol[8].

[[printing-testing]]
==== Έλεγχος Επικοινωνίας του Εκτυπωτή

Πριν συνεχίσουμε να ρυθμίζουμε το σύστημα παροχέτευσης, θα πρέπει να βεβαιωθείτε ότι το λειτουργικό σύστημα μπορεί να στείλει επιτυχώς δεδομένα στον εκτυπωτή σας. Είναι ευκολότερο να κάνουμε ξεχωριστά την αποσφαλμάτωση επικοινωνίας του εκτυπωτή και την αποσφαλμάτωση του συστήματος παροχέτευσης.

Θα ελέγξουμε τον εκτυπωτή στέλνοντας μερικά δεδομένα κειμένου. Για εκείνους τους εκτυπωτές που μπορούν να εκτυπώνουν άμεσα τους χαρακτήρες που έχουν αποσταλεί, το πρόγραμμα man:lptest[1] είναι τέλειο: Παράγει όλους τους εκτυπώσιμους χαρακτήρες (96) ASCII σε 96 γραμμές.

Για εκτυπωτές PostScript(R) (ή που βασίζονται σε άλλη γλώσσα), θα χρειαστεί να κάνουμε ένα πιο πολύπλοκο τεστ. Ένα μικρό πρόγραμμα PostScript(R), όπως αυτό που ακολουθεί, επαρκεί:

[.programlisting]
....
%!PS
100 100 moveto 300 300 lineto stroke
310 310 moveto /Helvetica findfont 12 scalefont setfont
(Is this thing working?) show
showpage
....

Ο παραπάνω κώδικας PostScript(R) μπορεί να τοποθετηθεί σε ένα αρχείο και να χρησιμοποιηθεί όπως υποδεικνύουν τα παραδείγματα στις ακόλουθες ενότητες.

[NOTE]
====
Όταν αυτό το έγγραφο αναφέρεται σε μια γλώσσα εκτυπωτή, εννοείται μια γλώσσα όπως η PostScript(R), αλλά όχι η PCL της Hewlett Packard - η PCL είναι μια γλώσσα ευρείας λειτουργικότητας η οποία επιτρέπει την ανάμιξη απλού κειμένου με ακολουθίες διαφυγής. Η PostScript(R) δεν μπορεί να εκτυπώσει άμεσα απλό κείμενο, και αυτός είναι ακριβώς ο τύπος της γλώσσας εκτυπωτή που θα πρέπει να διευθετήσουμε κατάλληλα.
====

[[printing-checking-parallel]]
===== Έλεγχος Παράλληλου Εκτυπωτή

Αυτή η ενότητα υποδεικνύει πως να ελέγξετε αν το FreeBSD μπορεί να επικοινωνήσει με έναν εκτυπωτή συνδεδεμένο σε παράλληλη θύρα.

_Για να ελέγξετε έναν εκτυπωτή σε παράλληλη θύρα:_

[.procedure]
. Γίνετε `root` με man:su[1].
. Στείλτε δεδομένα στον εκτυπωτή.

** Αν ο εκτυπωτής μπορεί να εκτυπώσει απλό κείμενο, τότε χρησιμοποιήστε το man:lptest[1]. Πληκτρολογήστε:
+

[source,bash]
....
# lptest > /dev/lptN
....

+ 
Όπου _N_ είναι ο αριθμός της παράλληλης θύρας, ξεκινώντας από το μηδέν.
** Εάν ο εκτυπωτής καταλαβαίνει PostScript(R) ή κάποια άλλη γλώσσα εκτυπωτών, τότε στείλτε ένα μικρό πρόγραμμα στον εκτυπωτή. Πληκτρολογήστε:
+

[source,bash]
....
# cat > /dev/lptN
....

+ 
Έπειτα πληκτρολογήστε το πρόγραμμα μία προς μία γραμμή, _προσεκτικά_, γιατί δεν μπορείτε να επεξεργαστείτε μια γραμμή αφότου έχετε πιέσει το πλήκτρο `RETURN` ή `ENTER`. Αφού τελειώσετε με την καταχώριση του προγράμματος, πιέστε `CONTROL+D`, ή άλλο πλήκτρο τερματισμού αρχείου.
+ 
Εναλλακτικά, μπορείτε να τοποθετήσετε το πρόγραμμα σε ένα αρχείο και να πληκτρολογήσετε:
+

[source,bash]
....
# cat file > /dev/lptN
....

+ 
Όπου _file_ είναι το όνομα του αρχείου που περιέχει το πρόγραμμα που θέλετε να στείλετε στον εκτυπωτή.

Θα δείτε κάτι να εκτυπώνεται. Μην ανησυχείτε αν το κείμενο δεν φαίνεται σωστό. Θα το διορθώσουμε αργότερα.

[[printing-checking-serial]]
===== Έλεγχος Σειριακού Εκτυπωτή

Αυτή η ενότητα υποδεικνύει πως να ελέγξετε αν το FreeBSD μπορεί να επικοινωνήσει με έναν εκτυπωτή συνδεδεμένο σε σειριακή θύρα.

_Για να ελέγξετε έναν εκτυπωτή σε σειριακή θύρα:_

[.procedure]
. Γίνετε `root` με man:su[1].
. Επεξεργαστείτε το αρχείο [.filename]#/etc/remote#. Προσθέστε την ακόλουθη καταχώριση:
+
[.programlisting]
....
printer:dv=/dev/port:br#bps-rate:pa=parity
....

+ 
Όπου _port_ είναι η καταχώριση συσκευής για την σειριακή πόρτα (`ttyu0`, `ttyu1`, κτλ.), _bps-rate_ είναι η ταχύτητα bits-per-second επικοινωνίας με τον εκτυπωτή, και _parity_ η ισοτιμία που απαιτείται από τον εκτυπωτή (`even`, `odd`, `none`, ή `zero`).
+ 
Παρακάτω φαίνεται ένα υπόδειγμα καταχώρισης, για έναν εκτυπωτή συνδεδεμένο μέσω σειριακής γραμμής στην τρίτη σειριακή θύρα με ταχύτητα 19200 bps και χωρίς parity:
+
[.programlisting]
....
printer:dv=/dev/ttyu2:br#19200:pa=none
....

. Συνδεθείτε στον εκτυπωτή με man:tip[1]. Πληκτρολογήστε:
+

[source,bash]
....
# tip printer
....

+ 
Αν αυτό το στάδιο δεν δουλεύει, επεξεργαστείτε πάλι το αρχείο [.filename]#/etc/remote# και προσπαθήστε το χρησιμοποιώντας [.filename]#/dev/cuaaN# αντί για [.filename]#/dev/ttyuN#.
. Στείλτε δεδομένα στον εκτυπωτή.

** Αν ο εκτυπωτής μπορεί να εκτυπώσει απλό κείμενο, χρησιμοποιήστε man:lptest[1]. Γράψτε:
+

[source,bash]
....
% $lptest
....

** Εάν ο εκτυπωτής καταλαβαίνει PostScript(R) ή κάποια άλλη γλώσσα εκτυπωτών, τότε στείλτε ένα μικρό πρόγραμμα στον εκτυπωτή. Πληκτρολογήστε το πρόγραμμα, μία προς μία γραμμή, _πολύ προσεκτικά_, καθώς ο εκτυπωτής μπορεί να ερμηνεύει διαφορετικά την χρήση χαρακτήρων όπως το backspace ή άλλων που παράγονται από διάφορα πλήκτρα επεξεργασίας. Μπορεί επίσης να χρειαστεί να πληκτρολογήσετε κάποιο ειδικό πλήκτρο τερματισμού αρχείου για τον εκτυπωτή ώστε να γνωρίζει πότε ολοκληρώνεται το πρόγραμμα. Για εκτυπωτές PostScript(R), πιέστε `CONTROL+D`.
+ 
Εναλλακτικά, μπορείτε να τοποθετήσετε το πρόγραμμα σε ένα αρχείο και να πληκτρολογήσετε:
+

[source,bash]
....
% >file
....

+ 
Όπου _file_ είναι το όνομα του αρχείου που περιέχει το πρόγραμμα. Αφού το man:tip[1] στείλει το αρχείο, πιέστε το κατάλληλο πλήκτρο τερματισμού αρχείου, αν απαιτείται.

Θα δείτε κάτι να εκτυπώνεται. Μην ανησυχείτε αν το κείμενο δεν φαίνεται σωστό. Θα το διορθώσουμε αργότερα.

[[printing-printcap]]
==== Ενεργοποίηση του Spooler: το Αρχείο [.filename]#/etc/printcap#

Σε αυτό το σημείο, ο εκτυπωτής σας θα πρέπει να είναι συνδεμένος, ο πυρήνας σας ρυθμισμένος να επικοινωνεί μαζί του (αν χρειάζεται), και έχετε πετύχει να στείλετε κάποια δοκιμαστικά δεδομένα στον εκτυπωτή. Είστε τώρα έτοιμοι να ρυθμίσετε το LPD για να ελέγχετε την πρόσβαση στον εκτυπωτή σας.

Μπορείτε να ρυθμίσετε το LPD με επεξεργασία του αρχείου [.filename]#/etc/printcap#. Το σύστημα παροχέτευσης LPD διαβάζει αυτό το αρχείο κάθε φορά που χρησιμοποιείται ο spooler, επομένως πιθανές αναβαθμίσεις του μπαίνουν άμεσα σε εφαρμογή.

Είναι εύκολο να κατανοήσετε την μορφή του αρχείου man:printcap[5]. Χρησιμοποιήστε τον κειμενογράφο που προτιμάτε για να κάνετε αλλαγές στο [.filename]#/etc/printcap#. Η μορφή του είναι παρόμοια με άλλα αρχεία περιγραφής δυνατοτήτων, όπως τα [.filename]#/usr/shared/misc/termcap# και [.filename]#/etc/remote#. Δείτε την man:cgetent[3] για λεπτομερείς πληροφορίες σχετικά με την μορφή του αρχείου.

Η πιο απλή ρύθμιση του spooler αποτελείται από τα ακόλουθα βήματα:

[.procedure]
. Επιλέξτε ένα όνομα (και λίγα βολικά παρωνύμια) για τον εκτυπωτή, και τοποθετήστε τα στο αρχείο [.filename]#/etc/printcap#. Δείτε την ενότητα <<printing-naming,Ονοματοδότηση Εκτυπωτή>> για περισσότερες πληροφορίες σχετικά με την ονομασία των εκτυπωτών.
. Απενεργοποιήστε τις σελίδες κεφαλίδας (είναι ενεργές από προεπιλογή) εισάγοντας την ικανότητα `sh`. Για περισσότερες πληροφορίες δείτε την ενότητα <<printing-no-header-pages,Παρεμπόδιση Σελίδων Κεφαλίδας>>.
. Δημιουργήστε ένα κατάλογο παροχέτευσης, και καθορίστε την τοποθεσία του με την ικανότητα `sd`. Για περισσότερες πληροφορίες δείτε την ενότητα <<printing-spooldir,Δημιουργία Καταλόγου Παροχέτευσης>>.
. Καθορίστε την κατάλληλη καταχώριση [.filename]#/dev# για τον εκτυπωτή, και σημειώστε τη στο [.filename]#/etc/printcap# με την ικανότητα `lp`. Για περισσότερες πληροφορίες, δείτε την ενότητα <<printing-device,Αναγνώριση της Συσκευής Εκτύπωσης>>. Επίσης, αν ο εκτυπωτής είναι σε σειριακή θύρα, εγκαταστήστε τις παραμέτρους επικοινωνίας με την ικανότητα `ms#` η οποία αναλύεται στην ενότητα <<printing-commparam,Ρυθμίσεις Παραμέτρων Επικοινωνίας του Spooler>>.
. Εγκαταστήστε φίλτρα εισόδου απλού κειμένου. Δείτε την ενότητα <<printing-textfilter,Εγκατάσταση Φίλτρου Κειμένου>> για περισσότερες πληροφορίες.
. Ελέγξτε την εγκατάσταση εκτυπώνοντας οτιδήποτε με την εντολή man:lpr[1]. Περισσότερες πληροφορίες είναι διαθέσιμες στις ενότητες <<printing-trying,Δοκιμή του Spooler>> και <<printing-troubleshooting,Εντοπισμός Βλαβών>>.

[NOTE]
====
Εκτυπωτές που βασίζονται σε γλώσσες εκτύπωσης, όπως οι εκτυπωτές PostScript(R), δεν μπορούν να εκτυπώσουν άμεσα απλό κείμενο. Ο απλός τρόπος ρύθμισης που δείξαμε παραπάνω και που θα περιγράψουμε εκτενέστερα στις επόμενες ενότητες, προϋποθέτει πως αν ρυθμίζετε έναν τέτοιο εκτυπωτή θα μπορείτε να εκτυπώσετε μόνον αρχεία γραμμένα στη γλώσσα του.
====

Οι χρήστες συνήθως νομίζουν πως μπορούν να εκτυπώσουν απλό κείμενο σε όλους τους εκτυπωτές που είναι εγκατεστημένοι στο σύστημα τους. Τα προγράμματα που χρησιμοποιούν το LPD για να εκτυπώσουν, κάνουν ακριβώς την ίδια υπόθεση. Αν προσπαθείτε να εγκαταστήσετε έναν τέτοιο εκτυπωτή και θέλετε να μπορείτε να τυπώνετε εργασίες στην γλώσσα του εκτυπωτή αλλά _και_ σε απλό κείμενο, σας συνιστούμε να προσθέσετε ένα επιπλέον βήμα στην διαδικασία εγκατάστασης που περιγράψαμε παραπάνω: Εγκαταστήστε ένα πρόγραμμα αυτόματης μετατροπής από απλό κείμενο σε PostScript (ή σε άλλη γλώσσα εκτυπωτή). Η ενότητα <<printing-advanced-if-conversion,Συμβατότητα Εργασιών Απλού Κειμένου σε εκτυπωτές PostScript(R)>> εξηγεί πως να ενεργήσετε.

[[printing-naming]]
===== Ονοματοδότηση Εκτυπωτή

Το πρώτο (εύκολο) βήμα είναι να επιλέξετε όνομα για τον εκτυπωτή σας. Δεν έχει σημασία αν θα προτιμήσετε ένα λειτουργικό ή κάποιο εξωτικό όνομα αφού μπορείτε επίσης να προσθέσετε και μερικά παρωνύμια (aliases) για τον ίδιο εκτυπωτή.

Τουλάχιστον ένας από τους εκτυπωτές που αναφέρονται στο [.filename]#/etc/printcap# θα πρέπει να έχει το παρωνύμιο `lp`. Αυτή είναι η ονομασία του προεπιλεγμένου εκτυπωτή. Εάν οι χρήστες δεν έχουν την μεταβλητή περιβάλλοντος `PRINTER` και δεν αναφέρουν κάποιο όνομα εκτυπωτή στην γραμμή εντολών με οποιαδήποτε εντολή LPD, τότε ο `lp` θα είναι ο προεπιλεγμένος εκτυπωτής για τις εκτυπώσεις τους.

Επίσης, είναι κοινή πρακτική το τελευταίο alias του εκτυπωτή να είναι μια πλήρης περιγραφή του εκτυπωτή, που να περιλαμβάνει τον κατασκευαστή και το μοντέλο.

Αφού επιλέξετε μια ονομασία και μερικά συνήθη παρωνύμια, καταχωρίστε τα στο αρχείο [.filename]#/etc/printcap#. Το όνομα του εκτυπωτή θα πρέπει να αναφέρεται πρώτο στο αριστερό άκρο. Διαχωρίστε κάθε παρωνύμιο με μια κάθετη μπάρα και τοποθετήστε μια άνω-κάτω τελεία μετά το τελευταίο παρωνύμιο.

Στο ακόλουθο παράδειγμα, ξεκινάμε με ένα εντελώς βασικό [.filename]#/etc/printcap# που ορίζει δύο εκτυπωτές (έναν εκτυπωτή γραμμής Diablo 630 και έναν εκτυπωτή PostScript(R) laser Panasonic KX-P4455):

[.programlisting]
....
#
#  /etc/printcap for host rose
#
rattan|line|diablo|lp|Diablo 630 Line Printer:

bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:
....

Σε αυτό το παράδειγμα, ο πρώτος εκτυπωτής ονομάζεται `rattan` και έχει ως παρωνύμια τα `line`, `diablo`, `lp`, και `Diablo 630 Line Printer`. Από τη στιγμή που έχει το παρωνύμιο `lp`, είναι και ο προεπιλεγμένος εκτυπωτής. Ο δεύτερος ονομάζεται `bamboo`, και έχει ως παρωνύμια τα `ps`, `PS`, `S`, `panasonic`, και `Panasonic KX-P4455 PostScript v51.4`.

[[printing-no-header-pages]]
===== Παρεμπόδιση Σελίδων Κεφαλίδας

Το σύστημα παροχέτευσης LPD, από προεπιλογή, εκτυπώνει μια _σελίδα κεφαλίδας_ για κάθε εργασία. Η σελίδα κεφαλίδας περιλαμβάνει το όνομα χρήστη που αιτήθηκε την εργασία, τον υπολογιστή από τον οποίον προήλθε η εργασία, και το όνομα της εργασίας, με μεγάλους όμορφους χαρακτήρες. Δυστυχώς αυτό το πρόσθετο κείμενο ακολουθεί την διαδικασία αποσφαλμάτωσης της εγκατάστασης ενός απλού εκτυπωτή, επομένως θα παρεμποδίσουμε τις σελίδες κεφαλίδας.

Για την παρεμπόδιση των σελίδων κεφαλίδας, προσθέστε την ικανότητα `sh` στην καταχώριση για τον εκτυπωτή στο αρχείο [.filename]#/etc/printcap#. Εδώ βλέπετε ένα παράδειγμα του [.filename]#/etc/printcap# με προσθήκη της `sh`:

[.programlisting]
....
#
#  /etc/printcap for host rose - no header pages anywhere
#
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :sh:

bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:
....

Παρατηρήστε πως χειριστήκαμε σωστά τη μορφή: η πρώτη γραμμή ξεκινά στην αριστερή στήλη, και οι ακόλουθες γραμμές είναι στοιχισμένες (indented). Κάθε γραμμή καταχώρισης (εκτός από την τελευταία) τελειώνει με μια αριστερόστροφη κάθετο.

[[printing-spooldir]]
===== Δημιουργία Καταλόγου Παροχέτευσης

Το επόμενο βήμα στον απλό τρόπο εγκατάστασης είναι η δημιουργία ενός _καταλόγου παροχέτευσης (spool)_, όπου θα φιλοξενούνται οι εργασίες εκτύπωσης έως ότου να εκτυπωθούν και όπου επίσης φυλάσσονται και κάποια άλλα βοηθητικά αρχεία του συστήματος εκτύπωσης.

Λόγω της μεταβαλλόμενης φύσης των καταλόγων παροχέτευσης, συνηθίζεται να τοποθετούνται κάτω από τον κατάλογο [.filename]#/var/spool#. Δεν είναι αναγκαίο να παίρνετε αντίγραφα ασφαλείας των καταλόγων παροχέτευσης. Η επαναδημιουργία τους είναι τόσο απλή όσο να τρέξουμε την εντολή man:mkdir[1].

Είναι επίσης συνηθισμένο να ονομάζεται ο κατάλογος με το ίδιο όνομα με τον εκτυπωτή, όπως φαίνεται παρακάτω:

[source,bash]
....
# mkdir /var/spool/printer-name
....

Ωστόσο, αν έχετε αρκετούς εκτυπωτές στο δίκτυο, ίσως επιθυμείτε να τοποθετήσετε τους καταλόγους παροχέτευσης κάτω από ένα μοναδικό κατάλογο που θα χρησιμοποιείται αποκλειστικά για εκτυπώσεις με το LPD. Θα κάνουμε ακριβώς αυτό για τα παραδείγματα μας με τους εκτυπωτές `rattan` και `bamboo`:

[source,bash]
....
# mkdir /var/spool/lpd
# mkdir /var/spool/lpd/rattan
# mkdir /var/spool/lpd/bamboo
....

[NOTE]
====
Εάν οι εργασίες των χρηστών περιέχουν προσωπικά δεδομένα, μπορεί να θέλετε να προστατέψετε τον κατάλογο παροχέτευσης με κάποιο τρόπο, ώστε να μην είναι δημόσια προσβάσιμος. Οι κατάλογοι παροχέτευσης θα πρέπει να ανήκουν και να είναι αναγνώσιμοι, εγγράψιμοι και με δυνατότητα αναζήτησης από τον χρήστη daemon και από την ομάδα daemon, από κανέναν άλλο. Για τους εκτυπωτές του παραδείγματος:

[source,bash]
....
# chown daemon:daemon /var/spool/lpd/rattan
# chown daemon:daemon /var/spool/lpd/bamboo
# chmod 770 /var/spool/lpd/rattan
# chmod 770 /var/spool/lpd/bamboo
....

====

Τέλος, πρέπει να ενημερώσετε το LPD για αυτούς τους καταλόγους χρησιμοποιώντας το αρχείο [.filename]#/etc/printcap#. Προσδιορίστε την διαδρομή του καταλόγου παροχέτευσης με την ικανότητα `sd`:

[.programlisting]
....
#
#  /etc/printcap for host rose - added spooling directories
#
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :sh:sd=/var/spool/lpd/rattan:

bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:sd=/var/spool/lpd/bamboo:
....

Σημειώστε πως το όνομα του εκτυπωτή ξεκινά στην πρώτη στήλη, ενώ όλες οι άλλες καταχωρίσεις που περιγράφουν τον εκτυπωτή θα πρέπει να είναι στοιχισμένες και κάθε τέλος γραμμής να φέρει χαρακτήρα διαφυγής με αριστερόστροφη κάθετο.

Εάν δεν προσδιορίσετε τον κατάλογο παροχέτευσης μέσω του `sd`, τότε το σύστημα παροχέτευσης θα χρησιμοποιήσει τον προεπιλεγμένο [.filename]#/var/spool/lpd#.

[[printing-device]]
===== Αναγνώριση της Συσκευής Εκτύπωσης

Στην ενότητα <<printing-hardware,Ρυθμίσεις Hardware>> αναγνωρίσαμε τη θύρα, και κατά συνέπεια την καταχώριση του καταλόγου [.filename]#/dev# που θα χρησιμοποιήσει το FreeBSD για να επικοινωνήσει με τον εκτυπωτή. Τώρα, θα δώσουμε στο LPD αυτή την πληροφορία. Όταν το σύστημα παροχέτευσης έχει μια εργασία να εκτυπώσει, θα ανοίξει αυτή την ειδική συσκευή για λογαριασμό του προγράμματος φίλτρου (που είναι υπεύθυνο για το πέρασμα των δεδομένων στον εκτυπωτή).

Προσδιορίστε την διαδρομή της καταχώρισης [.filename]#/dev# στο αρχείο [.filename]#/etc/printcap# χρησιμοποιώντας την ικανότητα `lp`.

Στο τρέχον παράδειγμα μας, ας υποθέσουμε ότι ο `rattan` είναι στην πρώτη παράλληλη θύρα, και ο `bamboo` είναι στην έκτη σειριακή πόρτα. Οι νέες καταχωρίσεις στο [.filename]#/etc/printcap# θα είναι:

[.programlisting]
....
#
#  /etc/printcap for host rose - identified what devices to use
#
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :sh:sd=/var/spool/lpd/rattan:\
        :lp=/dev/lpt0:

bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:sd=/var/spool/lpd/bamboo:\
        :lp=/dev/ttyu5:
....

Αν δεν καθορίσετε σε κάποιον εκτυπωτή την ικανότητα `lp` στο αρχείο [.filename]#/etc/printcap#, το LPD χρησιμοποιεί από προεπιλογή το [.filename]#/dev/lp#. Το [.filename]#/dev/lp# δεν υπάρχει την δεδομένη στιγμή στο FreeBSD.

Εάν ο εκτυπωτής που εγκαθιστάτε είναι συνδεδεμένος σε παράλληλη θύρα, διαβάστε απευθείας την ενότητα με τίτλο <<printing-textfilter,Εγκατάσταση Φίλτρου Κειμένου>>. Διαφορετικά, ακολουθήστε προσεκτικά τις οδηγίες που ακολουθούν στην επόμενη ενότητα.

[[printing-commparam]]
===== Ρυθμίσεις Παραμέτρων Επικοινωνίας του Spooler

Για εκτυπωτές σε σειριακή πόρτα, το LPD μπορεί να ρυθμίσει την ταχύτητα σε bps, το parity, και άλλες παραμέτρους σειριακής επικοινωνίας για λογαριασμό του προγράμματος φίλτρου που στέλνει δεδομένα στον εκτυπωτή. Αυτό είναι πλεονέκτημα γιατί:

* Σας επιτρέπει να δοκιμάσετε διάφορες παραμέτρους επικοινωνίας προσθέτοντας τις απλά με επεξεργασία του αρχείου [.filename]#/etc/printcap#. Δεν χρειάζεται να επαναμεταγλωττίσετε το πρόγραμμα φίλτρου.
* Επιτρέπει στο σύστημα παροχέτευσης να χρησιμοποιεί το ίδιο πρόγραμμα για πολλαπλούς εκτυπωτές, οι οποίοι μπορεί να έχουν διαφορετικές σειριακές ρυθμίσεις επικοινωνίας.

Οι ακόλουθες ικανότητες του [.filename]#/etc/printcap# ελέγχουν τις παραμέτρους σειριακής επικοινωνίας των συσκευών που αναφέρονται στην ικανότητα `lp`:

`br#bps-rate`::
Ορίζει την ταχύτητα επικοινωνίας της συσκευής σε _bps-rate_, όπου το _bps-rate_ μπορεί να είναι 50, 75, 110, 134, 150, 200, 300, 600, 1200, 1800, 2400, 4800, 9600, 19200, 38400, 57600, ή 115200 bits-per-second.

`ms#stty-mode`::
Ορίζει τις επιλογές της συσκευής τερματικού μετά το άνοιγμα της συσκευής. Η man:stty[1] εξηγεί τις διαθέσιμες επιλογές.

Όταν το LPD ανοίγει την συσκευή που ορίζεται από την ικανότητα `lp`, υιοθετεί τα χαρακτηριστικά της συσκευής με ικανότητα `ms#`. Έχουν ιδιαίτερο ενδιαφέρον οι καταστάσεις λειτουργίας `parenb`, `parodd`, `cs5`, `cs6`, `cs7`, `cs8`, `cstopb`, `crtscts`, και `ixon`, που εξηγούνται στην σελίδα βοηθείας man:stty[1].

Ας προσθέσουμε στο παράδειγμα μας έναν εκτυπωτή στην έκτη σειριακή θύρα. Θα θέσουμε την ταχύτητα bps σε 38400. Για την κατάσταση λειτουργίας θα θέσουμε , no parity με `-parenb`, χαρακτήρες 8-bit με `cs8`, no modem control με `clocal` και έλεγχο ροής μέσω hardware με `crtscts`:

[.programlisting]
....
bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:sd=/var/spool/lpd/bamboo:\
        :lp=/dev/ttyu5:ms#-parenb cs8 clocal crtscts:
....

[[printing-textfilter]]
===== Εγκατάσταση Φίλτρου Κειμένου

Τώρα είμαστε έτοιμοι να πούμε στο LPD ποιο φίλτρο κειμένου να χρησιμοποιήσει για να στείλει εργασίες στον εκτυπωτή. Το φίλτρο κειμένου, γνωστό και ως _φίλτρο εισόδου_, είναι ένα πρόγραμμα που εκτελεί το LPD όταν υπάρχει εργασία προς εκτύπωση. Όταν το LPD εκτελεί το φίλτρο κειμένου για κάποιον εκτυπωτή, θέτει την standard input του φίλτρου στην εργασία εκτύπωσης, και την standard output στην συσκευή του εκτυπωτή που ορίζεται με την ικανότητα `lp`. Το φίλτρο αναμένεται να αναγνώσει την εργασία από την standard input, να εκτελέσει όλες τις απαραίτητες μεταγλωττίσεις για τον εκτυπωτή, και να γράψει το αποτέλεσμα στην standard output, το οποίο και θα εκτυπωθεί. Για περισσότερες πληροφορίες για τα φίλτρα κειμένου, δείτε την ενότητα <<printing-advanced-filters,Φίλτρα>>.

Για την απλή εγκατάσταση των εκτυπωτών μας, το φίλτρο κειμένου μπορεί να είναι ένα μικρό shell script που απλά θα εκτελεί την εντολή `/bin/cat` για να στέλνει εργασίες στον εκτυπωτή. Το FreeBSD έρχεται με άλλο ένα φίλτρο, το [.filename]#lpf# που χειρίζεται δυνατότητες backspacing και υπογράμμισης για εκτυπωτές που ίσως να μην χειρίζονται σωστά αυτές τις λειτουργίες. Και φυσικά, μπορείτε να χρησιμοποιήσετε οποιοδήποτε άλλο πρόγραμμα φίλτρου επιθυμείτε. Το φίλτρο `lpf` περιγράφεται λεπτομερώς στην ενότητα <<printing-advanced-lpf,lpf: ένα Φίλτρο Κειμένου>>.

Θα ξεκινήσουμε δημιουργώντας το shell script [.filename]#/usr/local/libexec/if-simple# σαν ένα απλό φίλτρο κειμένου. Τοποθετήστε το ακόλουθο κείμενο στο αρχείο χρησιμοποιώντας τον κειμενογράφο που προτιμάτε:

[.programlisting]
....
#!/bin/sh
#
# if-simple - Simple text input filter for lpd
# Installed in /usr/local/libexec/if-simple
#
# Simply copies stdin to stdout.  Ignores all filter arguments.

/bin/cat && exit 0
exit 2
....

Κάντε το αρχείο εκτελέσιμο:

[source,bash]
....
# chmod 555 /usr/local/libexec/if-simple
....

Και ενημερώστε το LPD να το χρησιμοποιήσει, ορίζοντας το με την ικανότητα `if` στο αρχείο [.filename]#/etc/printcap#. Θα το προσθέσουμε στους δύο εκτυπωτές από το προηγούμενο παράδειγμα στο [.filename]#/etc/printcap#:

[.programlisting]
....
#
#  /etc/printcap for host rose - added text filter
#
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :sh:sd=/var/spool/lpd/rattan:\
        :lp=/dev/lpt0:\
        :if=/usr/local/libexec/if-simple:

bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:sd=/var/spool/lpd/bamboo:\
        :lp=/dev/ttyu5:ms#-parenb cs8 clocal crtscts:\
        :if=/usr/local/libexec/if-simple:
....

[NOTE]
====
Μπορείτε να βρείτε ένα αντίγραφο του script [.filename]#if-simple# στον κατάλογο [.filename]#/usr/shared/examples/printing#.
====

===== Ενεργοποίηση του LPD

Το man:lpd[8] εκτελείται από το [.filename]#/etc/rc#, και ελέγχεται από την μεταβλητή `lpd_enable`. Η μεταβλητή αυτή έχει προεπιλεγμένη τιμή `NO`. Αν δεν το έχετε κάνει ακόμα, προσθέστε την ακόλουθη γραμμή:

[.programlisting]
....
lpd_enable="YES"
....

στο αρχείο [.filename]#/etc/rc.conf#, και επανεκκινήστε το σύστημα σας, ή απλά εκτελέστε το man:lpd[8].

[source,bash]
....
# lpd
....

[[printing-trying]]
===== Δοκιμή του Spooler

Φτάσατε στο τέλος της απλής εγκατάστασης του LPD. Θα αφήσουμε για αργότερα τα συγχαρητήρια, αφού ακόμη θα πρέπει να ελέγξουμε την εγκατάσταση και να διορθώσουμε οποιοδήποτε πρόβλημα έχει προκύψει. Για να ελέγξετε την εγκατάσταση προσπαθήστε να εκτυπώσετε κάτι. Για να εκτυπώσετε με το σύστημα LPD, χρησιμοποιήστε την εντολή man:lpr[1], η οποία αποστέλλει μία εργασία προς εκτύπωση.

Μπορείτε να συνδυάσετε την man:lpr[1] με το πρόγραμμα man:lptest[1], για το οποίο κάναμε μια εισαγωγή στην ενότητα <<printing-testing,Έλεγχος Επικοινωνίας του Εκτυπωτή>>, για τον έλεγχο κειμένου.

_Για τον έλεγχο μιας απλής εγκατάστασης LPD:_

Πληκτρολογήστε:

[source,bash]
....
# lptest 20 5 | lpr -Pprinter-name
....

Όπου _printer-name_ είναι το όνομα ενός εκτυπωτή (ή το alias) που αναφέρεται στο [.filename]#/etc/printcap#. Για να ελέγξετε τον προεπιλεγμένο εκτυπωτή, πληκτρολογήστε man:lpr[1] χωρίς το πρόθεμα `-P`. Αν ο εκτυπωτής σας χρησιμοποιεί PostScript(R), πρέπει να στείλετε ένα πρόγραμμα PostScript(R), αντί να χρησιμοποιήσετε το man:lptest[1]. Για να τα καταφέρετε, τοποθετήστε το πρόγραμμα σε ένα αρχείο και πληκτρολογήστε `lpr file`.

Σε έναν εκτυπωτή PostScript(R), η εκτύπωση θα είναι το αποτέλεσμα του προγράμματος που στείλατε. Αν χρησιμοποιείτε το man:lptest[1], τότε το αποτέλεσμα θα μοιάζει με το ακόλουθο:

[source,bash]
....
!"#$%&'()*+,-./01234
"#$%&'()*+,-./012345
#$%&'()*+,-./0123456
$%&'()*+,-./01234567
%&'()*+,-./012345678
....

Για περαιτέρω έλεγχο του εκτυπωτή, δοκιμάστε να κατεβάσετε μεγαλύτερα προγράμματα (για εκτυπωτές που χρησιμοποιούν γλώσσα προγραμματισμού) ή τρέξτε το man:lptest[1] με διαφορετικά προθέματα. Για παράδειγμα, η εντολή `lptest 80 60` θα παράγει 60 γραμμές των 80 χαρακτήρων η καθεμία.

Αν ο εκτυπωτής δεν δουλεύει, δείτε την ενότητα <<printing-troubleshooting,Εντοπισμός Βλαβών>>.

[[printing-advanced]]
== Ρυθμίσεις Εκτυπωτών για Προχωρημένους

[WARNING]
====

Από το FreeBSD 8.0 και μετά, τα αρχεία συσκευών για τις σειριακές θύρες μετονομάστηκαν από [.filename]#/dev/ttydN# σε [.filename]#/dev/ttyuN#. Οι χρήστες του FreeBSD 7.X θα πρέπει να προσαρμόσουν την τεκμηρίωση που ακολουθεί με βάση αυτές τις αλλαγές.
====

Αυτή η ενότητα περιγράφει φίλτρα για την εκτύπωση ειδικής μορφής αρχείων, σελίδων κεφαλίδας, για εκτυπώσεις μέσω δικτύου, καθώς και για τον έλεγχο πρόσβασης και την καταμέτρηση χρήσης των εκτυπωτών.

[[printing-advanced-filter-intro]]
=== Φίλτρα

Αν και το LPD μπορεί να χειριστεί πρωτόκολλα δικτύων, λίστες αναμονής, έλεγχο πρόσβασης, και άλλες παραμέτρους των εκτυπώσεων, το κύριο μέρος της _πραγματικής_ εργασίας γίνεται με τα _φίλτρα_. Τα φίλτρα είναι προγράμματα που επικοινωνούν με τον εκτυπωτή και χειρίζονται τις εξαρτήσεις της συσκευής και άλλες ειδικές απαιτήσεις της. Στην απλή εγκατάσταση εκτυπωτή, εγκαταστήσαμε ένα φίλτρο απλού κειμένου ιδιαίτερα απλής μορφής, που θα πρέπει να δουλεύει με τους περισσότερους εκτυπωτές (ενότητα <<printing-textfilter,Εγκατάσταση Φίλτρου Κειμένου>>).

Ωστόσο, για να μπορέσετε να εκμεταλλευτείτε τις δυνατότητες μετατροπών μορφής, ελέγχου πρόσβασης και καταμέτρησης, και τυχόν ειδικές δυνατότητες του εκτυπωτή σας, θα πρέπει να καταλάβετε πως δουλεύουν τα φίλτρα. Σε τελική ανάλυση, θα είναι ευθύνη των φίλτρων να χειρίζονται όλες αυτές τις παραμέτρους. Τα κακά νέα είναι πως τις περισσότερες φορές θα πρέπει να παρέχετε _εσείς οι ίδιοι_ τα φίλτρα σας. Τα καλά νέα είναι πως γενικώς υπάρχουν αρκετά διαθέσιμα, και αν δεν υπάρχουν, είναι σχετικά εύκολο να τα γράψετε.

Επίσης, το FreeBSD διατίθεται με ένα φίλτρο, το [.filename]#/usr/libexec/lpr/lpf#, που δουλεύει με πολλούς εκτυπωτές που μπορούν να εκτυπώσουν απλό κείμενο. (Χειρίζεται backspacing και tabs στο αρχείο, και κάνει καταμέτρηση, αλλά τίποτα περισσότερο.) Υπάρχουν, επίσης, διάφορα άλλα φίλτρα και συστατικά τους στην Συλλογή των Ports του FreeBSD.

Σε αυτή την ενότητα θα βρείτε: :

* Η ενότητα <<printing-advanced-filters,Πως δουλεύουν τα Φίλτρα>>, προσπαθεί να δώσει μια γενική άποψη για τις αρμοδιότητες των φίλτρων στις διεργασίες εκτύπωσης. Θα πρέπει να διαβάσετε αυτή την ενότητα για να μπορείτε να καταλάβετε τι "πραγματικά" συμβαίνει όταν το LPD χρησιμοποιεί φίλτρα. Αυτές οι γνώσεις θα σας βοηθήσουν να προλαμβάνετε και να αποσφαλματώνετε προβλήματα που μπορούν να συμβούν καθώς εγκαθιστάτε όλο και περισσότερα φίλτρα σε κάθε εκτυπωτή σας.
* Το LPD αναμένει πως κάθε εκτυπωτής είναι ικανός, από προεπιλογή, να εκτυπώσει απλό κείμενο. Αυτό όμως είναι πρόβλημα για εκτυπωτές PostScript(R) (ή άλλους που βασίζονται σε γλώσσες προγραμματισμού) οι οποίοι δεν μπορούν να εκτυπώσουν άμεσα απλό κείμενο. Η ενότητα <<printing-advanced-if-conversion,Συμβατότητα Εργασιών Απλού Κειμένου σε εκτυπωτές PostScript(R)>> σας εξηγεί τι θα πρέπει να κάνετε για να ξεπεράσετε αυτό το πρόβλημα. Θα πρέπει να διαβάσετε αυτή την ενότητα αν έχετε εκτυπωτή PostScript(R).
* Το PostScript(R) είναι δημοφιλής μορφή εξόδου για πολλά προγράμματα. Μερικοί άνθρωποι προτιμούν και να γράφουν κατευθείαν σε κώδικα PostScript(R). Δυστυχώς, οι εκτυπωτές PostScript(R) έχουν μεγάλο κόστος. Η ενότητα <<printing-advanced-ps,Προσομοίωση PostScript(R) για εκτυπωτές που δεν το υποστηρίζουν>> εξηγεί λεπτομερώς πως να μετατρέψετε ένα φίλτρο κειμένου για εκτυπωτές ώστε να λαμβάνει και να τυπώνει δεδομένα PostScript(R) σε εκτυπωτές που _δεν είναι PostScript(R)_. Θα πρέπει να διαβάσετε αυτήν την ενότητα αν είστε κάτοχος εκτυπωτή που δεν υποστηρίζει PostScript(R).
* Η ενότητα <<printing-advanced-convfilters,Φίλτρα Μετατροπής>> περιγράφει μια αυτοματοποιημένη διαδικασία για την μετατροπή αρχείων ειδικής μορφής, όπως δεδομένα γραφικών ή στοιχειοθεσίας, σε μια μορφή κατανοητή από τον εκτυπωτή σας. Μετά την ανάγνωση αυτής της ενότητας, θα πρέπει να είστε σε θέση να ρυθμίσετε τους εκτυπωτές σας με τέτοιο τρόπο ώστε πληκτρολογώντας `lpr -t` οι χρήστες σας να μπορούν να εκτυπώσουν δεδομένα troff, ή με `lpr -d` δεδομένα TeX DVI, ή με `lpr -v` να εκτυπώνουν εικόνες δεδομένων ράστερ, και ούτω καθεξής. Σας συμβουλεύουμε να διαβάσετε αυτή την ενότητα.
* Η ενότητα <<printing-advanced-of,Φίλτρα Εξόδου>> περιγράφει ένα χαρακτηριστικό του LPD που δεν χρησιμοποιείται συχνά: τα φίλτρα εξόδου. Μπορείτε να προσπεράσετε αυτή την ενότητα, εκτός αν τυπώνετε σελίδες κεφαλίδας (δείτε τις <<printing-advanced-header-pages,Σελίδες Κεφαλίδας>>).
* Η ενότητα <<printing-advanced-lpf,lpf: ένα Φίλτρο Κειμένου>> περιγράφει το `lpf`, ένα πραγματικά πλήρες, αν και απλό, φίλτρο κειμένου για εκτυπωτές γραμμής (και εκτυπωτές laser που μπορούν να λειτουργήσουν και ως εκτυπωτές γραμμής) που περιέχεται στο FreeBSD. Αν χρειάζεστε ένα γρήγορο τρόπο για να κάνετε την καταμέτρηση σελίδων να δουλεύει σε απλό κείμενο, ή αν έχετε κάποιον εκτυπωτή που βγάζει καπνούς όταν βλέπει χαρακτήρες backspace, θα πρέπει οπωσδήποτε να εξετάσετε την περίπτωση του `lpf`.

[NOTE]
====
Μπορείτε να βρείτε αντίγραφο των διάφορων scripts που αναφέρονται παρακάτω, στον κατάλογο [.filename]#/usr/shared/examples/printing#.
====

[[printing-advanced-filters]]
==== Πως Δουλεύουν τα Φίλτρα

Όπως αναφέραμε προηγουμένως, φίλτρο είναι ένα εκτελέσιμο πρόγραμμα που ενεργοποιείται από το LPD για να χειρίζεται το τμήμα της επικοινωνίας με τον εκτυπωτή που εξαρτάται από τον τύπο της ίδιας της συσκευής.

Όταν το LPD θέλει να εκτυπώσει ένα αρχείο μιας εργασίας, ξεκινά το πρόγραμμα του φίλτρου. Θέτει ως standard input του φίλτρου το αρχείο που πρέπει να εκτυπωθεί, ως standard output τον ίδιο τον εκτυπωτή και ως standard error το αρχείο αναφοράς σφαλμάτων (αναφέρεται στην ικανότητα `lf` του [.filename]#/etc/printcap#, ή από προεπιλογή το [.filename]#/dev/console#).

Το φίλτρο που θα ξεκινήσει το LPD καθώς και οι παράμετροι του φίλτρου, εξαρτώνται από το τι έχετε δηλώσει στο αρχείο [.filename]#/etc/printcap# και από το τι παραμέτρους έχει καθορίσει ο ίδιος ο χρήστης για την εργασία με την γραμμή εντολής man:lpr[1]. Για παράδειγμα, αν ο χρήστης πληκτρολογήσει `lpr -t`, το LPD θα ξεκινήσει το φίλτρο troff, που υποδηλώνεται με την ικανότητα `tf` για τον εκτυπωτή προορισμού. Αν ο χρήστης επιθυμεί να εκτυπώσει απλό κείμενο, θα ξεκινήσει το φίλτρο `if` (αυτό πράγματι ισχύει τις περισσότερες φορές: δείτε τα <<printing-advanced-of,Φίλτρα Εξόδου>> για λεπτομέρειες).

Υπάρχουν τρεις τύποι φίλτρων που μπορείτε να προσδιορίσετε στο [.filename]#/etc/printcap#:

* Το _φίλτρο κειμένου_, επονομαζόμενο και ως _φίλτρο εισόδου_ στην τεκμηρίωση του LPD, χειρίζεται εκτυπώσεις κανονικού κειμένου. Θεωρήστε το ως το προεπιλεγμένο φίλτρο. Το LPD αναμένει πως όλοι οι εκτυπωτές, από προεπιλογή, είναι σε θέση να εκτυπώσουν απλό κείμενο, και είναι δουλειά του φίλτρου κειμένου να βεβαιωθεί ότι τα backspaces, τα tabs, και όλοι οι άλλοι ειδικοί χαρακτήρες δεν πρόκειται να προβληματίσουν τον εκτυπωτή. Εάν βρίσκεστε σε ένα περιβάλλον όπου θα πρέπει να καταμετρήσετε την χρήση των εκτυπωτών, το φίλτρο κειμένου θα πρέπει επίσης να καταμετρήσει τις εκτυπωμένες σελίδες, συνήθως μετρώντας τον αριθμό των εκτυπωμένων γραμμών και συγκρίνοντας τον με τον αριθμό των γραμμών που υποστηρίζει ο εκτυπωτής ανά σελίδα. Το φίλτρο κειμένου ξεκινά με την ακόλουθη λίστα παραμέτρων: 
+
`filter-name` [ -c ] -w__width__ -l__length__ -i__indent__ -n __login__ -h __host__ __acct-file__
+
όπου 

`-c`:::
εμφανίζεται αν η εργασία έχει αποσταλεί με `lpr -l`

`_width_`:::
είναι η τιμή από την ικανότητα `pw` (πλάτος σελίδας - page width) όπως προσδιορίζεται στο [.filename]#/etc/printcap#, με προεπιλεγμένη τιμή το 132

`_length_`:::
είναι η τιμή από την ικανότητα `pl` (μήκος σελίδας - page length), με προεπιλεγμένη τιμή το 66

`_indent_`:::
είναι το μέγεθος της εσοχής (indentation) από το `lpr -i`, με προεπιλεγμένη τιμή 0

`_login_`:::
είναι το καταγεγραμμένο όνομα χρήστη που εκτυπώνει το αρχείο

`_host_`:::
είναι το όνομα του υπολογιστή από τον οποίο στάλθηκε η εργασία

`_acct-file_`:::
είναι το όνομα του αρχείου καταμέτρησης από την ικανότητα `af`.

* Ένα _φίλτρο μετατροπής_ μετατρέπει ένα αρχείο ειδικής μορφής σε ένα τύπο αρχείου κατάλληλο για εκτύπωση από τον συγκεκριμένο εκτυπωτή. Για παράδειγμα, τα δεδομένα στοιχειοθεσίας ditroff δεν μπορούν να εκτυπωθούν κατευθείαν, αλλά μπορείτε να εγκαταστήσετε ένα φίλτρο μετατροπής αρχείων ditroff, ώστε να μετατρέψετε τα δεδομένα ditroff σε μια μορφή που ο εκτυπωτής να μπορεί να αφομοιώσει και να τυπώσει. Θα μάθετε περισσότερα στην ενότητα <<printing-advanced-convfilters,Φϊλτρα Μετατροπής>>. Τα φίλτρα μετατροπής επίσης χρειάζονται για να κάνετε αρίθμηση/καταμέτρηση, αν χρειάζεστε καταμέτρηση των εκτυπώσεων σας. Τα φίλτρα μετατροπής ξεκινούν με τις ακόλουθες παραμέτρους: 
+
`filter-name` -x__pixel-width__ -y__pixel-height__ -n _login_ -h _host_ _acct-file_ όπου _pixel-width_ είναι η τιμή από την ικανότητα px (προεπιλεγμένη τιμή 0) και _pixel-height_ είναι η τιμή από την ικανότητα py (προεπιλεγμένη τιμή 0).
* Το _φίλτρο εξόδου_ χρησιμοποιείται μόνον αν δεν υπάρχει φίλτρο κειμένου, ή αν είναι ενεργοποιημένες οι σελίδες κεφαλίδας. Διαβάστε τη σχετική ενότητα <<printing-advanced-of,Φίλτρα Εξόδου>>, αν και από την εμπειρία μας μπορούμε να σας πούμε ότι χρησιμοποιούνται σπάνια. Υπάρχουν μόνο δύο παράμετροι για τα φίλτρα εξόδου: 
+
`filter-name` -w__width__ -l__length__ οι οποίες είναι πανομοιότυπες με τις παραμέτρους `-w` και `-l` των φίλτρων κειμένου.

Τα φίλτρα θα πρέπει επίσης να _τερματίζουν_ με κάποια από τις ακόλουθες καταστάσεις εξόδου:

exit 0::
Αν το φίλτρο τύπωσε επιτυχώς το αρχείο.

exit 1::
Αν το φίλτρο απέτυχε να τυπώσει το αρχείο, αλλά θέλει το LPD να προσπαθήσει να εκτυπώσει το αρχείο ξανά. Το LPD θα ξεκινήσει ξανά το φίλτρο αν γίνει έξοδος με αυτή την κατάσταση.

exit 2::
Αν το φίλτρο απέτυχε να εκτυπώσει το αρχείο και δεν θέλει το LPD να προσπαθήσει ξανά. Το LPD θα απορρίψει το αρχείο.

Το φίλτρο κειμένου που έρχεται με την κανονική έκδοση του FreeBSD, [.filename]#/usr/libexec/lpr/lpf#, εκμεταλλεύεται τις παραμέτρους πλάτους και μήκους σελίδας για να προσδιορίσει πότε να αποστείλει το form feed και πως να κάνει καταμέτρηση. Χρησιμοποιεί τις παραμέτρους για login, host, και αρχείου καταμέτρησης για να δημιουργήσει τις σχετικές εγγραφές καταμέτρησης.

Αν είστε στη διαδικασία επιλογής φίλτρων, ελέγξτε αν είναι συμβατά με το LPD. Αν είναι συμβατά, τότε πρέπει να υποστηρίζουν την λίστα παραμέτρων που περιγράψαμε προηγουμένως. Αν σχεδιάζετε να γράψατε τα δικά σας φίλτρα γενικής χρήσης, τότε πρέπει να τα κάνετε να υποστηρίζουν την ίδια λίστα παραμέτρων και κωδικών εξόδου.

[[printing-advanced-if-conversion]]
==== Συμβατότητα Εργασιών Απλού Κειμένου σε Εκτυπωτές PostScript(R)

Αν είστε ο μοναδικός χρήστης του Η/Υ σας και του εκτυπωτή PostScript(R) (ή άλλης γλώσσας εκτυπωτών), και είστε σίγουροι πως δεν πρόκειται να στείλετε ποτέ εκτυπώσεις απλού κειμένου στον εκτυπωτή σας και πως δεν θα χρησιμοποιήσετε τις υπηρεσίες των διαφόρων προγραμμάτων σας που θα θελήσουν να στείλουν απλό κείμενο στον εκτυπωτή σας, τότε δεν χρειάζεται να ασχοληθείτε καθόλου με αυτή την ενότητα.

Αλλά, αν επιθυμείτε να στείλετε τόσο εργασίες PostScript(R) όσο και απλού κειμένου στον εκτυπωτή σας, τότε σας προτρέπουμε να προσθέσετε κάποιες ρυθμίσεις στην εγκατάσταση σας. Για να γίνει αυτό, θα πρέπει το φίλτρο κειμένου να ανιχνεύει αν η τρέχουσα εργασία είναι απλό κείμενο ή PostScript(R). Όλες οι εργασίες PostScript(R) πρέπει να ξεκινούν με `%!` (αν ο εκτυπωτής σας χρησιμοποιεί άλλη γλώσσα, συμβουλευθείτε την τεκμηρίωση του). Αν είναι αυτοί οι πρώτοι δύο χαρακτήρες, τότε έχουμε PostScript(R), και η υπόλοιπη εργασία μπορεί να σταλεί απευθείας στον εκτυπωτή. Αν δεν είναι αυτοί οι πρώτοι δύο χαρακτήρες, τότε το φίλτρο θα μετατρέψει το κείμενο σε PostScript(R) και θα τυπώσει το αποτέλεσμα.

Πως γίνεται αυτό;

Αν είστε κάτοχος σειριακού εκτυπωτή, ένας καλός τρόπος για να γίνει αυτό εφικτό είναι να εγκαταστήσετε το `lprps`. Το `lprps` είναι ένα φίλτρο εκτύπωσης PostScript(R) που επικοινωνεί αμφίδρομα με τον εκτυπωτή. Ενημερώνει το αρχείο κατάστασης του εκτυπωτή με αναλυτικές πληροφορίες, ώστε οι χρήστες και οι διαχειριστές να μπορούν να δουν επακριβώς ποια είναι η κατάσταση του εκτυπωτή (όπως `χαμηλή στάθμη toner` ή `πρόβλημα χαρτιού`). Ακόμη πιο σημαντικό είναι πως περιέχει το πρόγραμμα `psif` που ανιχνεύει αν η εισερχόμενη εργασία είναι απλού κειμένου και καλεί το `textps` (ένα άλλο πρόγραμμα που περιέχεται στο `lprps`) να το μετατρέψει σε PostScript(R). Τέλος χρησιμοποιείται το `lprps` για να αποστείλει την εργασία στον εκτυπωτή.

Το `lprps` είναι μέρος της Συλλογής των Ports του FreeBSD (δείτε crossref:ports[ports,Η Συλλογή των Ports]). Φυσικά, μπορείτε να το κατεβάσετε, να το μεταγλωττίσετε και να το εγκαταστήσετε μόνοι σας. Μετά την εγκατάσταση του `lprps`, απλά προσδιορίστε τη διαδρομή προς το πρόγραμμα `psif` που είναι μέρος του `lprps`. Αν εγκαταστήσατε το `lprps` από την Συλλογή των Ports, τότε για τον σειριακό σας εκτυπωτή PostScript(R) χρησιμοποιήστε την ακόλουθη καταχώριση στο αρχείο [.filename]#/etc/printcap#:

[.programlisting]
....
:if=/usr/local/libexec/psif:
....

Θα πρέπει επίσης να καθορίσετε την ικανότητα `rw` η οποία ορίζει ότι το LPD θα χειρίζεται τον εκτυπωτή σε κατάσταση ανάγνωσης και εγγραφής.

Αν έχετε παράλληλο εκτυπωτή PostScript(R) (και για το λόγο αυτό δεν μπορείτε να χρησιμοποιήσετε αμφίδρομη επικοινωνία με τον εκτυπωτή, όπως απαιτείται από το `lprps`), μπορείτε να χρησιμοποιήσετε το ακόλουθο shell script ως φίλτρο κειμένου:

[.programlisting]
....
#!/bin/sh
#
#  psif - Print PostScript or plain text on a PostScript printer
#  Script version; NOT the version that comes with lprps
#  Installed in /usr/local/libexec/psif
#

IFS="" read -r first_line
first_two_chars=`expr "$first_line" : '\(..\)'`

if [ "$first_two_chars" = "%!" ]; then
    #
    #  PostScript job, print it.
    #
    echo "$first_line" && cat && printf "\004" && exit 0
    exit 2
else
    #
    #  Plain text, convert it, then print it.
    #
    ( echo "$first_line"; cat ) | /usr/local/bin/textps && printf "\004" && exit 0
    exit 2
fi
....

Στο παραπάνω script, το `textps` είναι ένα πρόγραμμα που εγκαταστήσαμε ξεχωριστά για να μετατρέπουμε απλό κείμενο σε PostScript(R). Μπορείτε να χρησιμοποιείτε οποιοδήποτε πρόγραμμα μετατροπής από κείμενο- σε-PostScript(R). Η Συλλογή των Ports (δείτε crossref:ports[ports,Η Συλλογή των Ports]) περιέχει επίσης ένα πλήρες πρόγραμμα μετατροπής από κείμενο σε PostScript(R), το `a2ps` που ίσως επιθυμείτε να διερευνήσετε.

[[printing-advanced-ps]]
==== Προσομοίωση PostScript(R) για Εκτυπωτές που δεν το Υποστηρίζουν

Το PostScript(R) είναι το _de facto_ πρότυπο για στοιχειοθεσία και εκτύπωση υψηλής ποιότητας. Ωστόσο, το PostScript(R) είναι κάπως _δαπανηρό_ πρότυπο. Ευτυχώς, η Aladdin Enterprises παρέχει ένα παρεμφερές ελεύθερο PostScript(R) που ονομάζεται Ghostscript και δουλεύει άψογα στο FreeBSD. Το Ghostscript διαβάζει τα περισσότερα αρχεία PostScript(R) και μπορεί να αποδώσει τις σελίδες τους σε μεγάλη γκάμα συσκευών, συμπεριλαμβάνοντας πολλούς τύπους εκτυπωτών που δεν υποστηρίζουν PostScript(R). Εγκαθιστώντας το Ghostscript και χρησιμοποιώντας ένα ειδικό φίλτρο κειμένου για τον εκτυπωτή σας, μπορείτε να κάνετε τον κοινό εκτυπωτή σας να λειτουργεί σαν ένας πραγματικός εκτυπωτής PostScript(R).

Το Ghostscript βρίσκεται στην Συλλογή των Ports του FreeBSD, και μάλιστα σε πολλές εκδόσεις. Η πιο διαδεδομένη είναι το package:print/ghostscript-gpl[].

Για να κάνετε προσομοίωση PostScript(R), πρέπει το φίλτρο κειμένου να ανιχνεύσει αν εκτυπώνετε αρχείο PostScript(R). Εάν όχι, τότε το φίλτρο θα περάσει το αρχείο κατευθείαν στον εκτυπωτή. Διαφορετικά, θα χρησιμοποιήσει το Ghostscript για να μετατρέψει αρχικά το αρχείο σε ένα τύπο που θα καταλαβαίνει ο εκτυπωτής.

Ιδού ένα παράδειγμα: το ακόλουθο script είναι ένα φίλτρο κειμένου για εκτυπωτές Hewlett Packard DeskJet 500. Για άλλους εκτυπωτές, αντικαταστήστε το όρισμα `-sDEVICE` στην εντολή `gs` (Ghostscript). (Πληκτρολογήστε `gs -h` για να δείτε την λίστα συσκευών που υποστηρίζει η τρέχουσα εγκατάσταση του Ghostscript.)

[.programlisting]
....
#!/bin/sh
#
#  ifhp - Print Ghostscript-simulated PostScript on a DeskJet 500
#  Installed in /usr/local/libexec/ifhp

#
#  Treat LF as CR+LF (to avoid the "staircase effect" on HP/PCL
#  printers):
#
printf "\033&k2G" || exit 2

#
#  Read first two characters of the file
#
IFS="" read -r first_line
first_two_chars=`expr "$first_line" : '\(..\)'`

if [ "$first_two_chars" = "%!" ]; then
    #
    #  It is PostScript; use Ghostscript to scan-convert and print it.
    #
    /usr/local/bin/gs -dSAFER -dNOPAUSE -q -sDEVICE=djet500 \
      -sOutputFile=- - && exit 0
else
    #
    #  Plain text or HP/PCL, so just print it directly; print a form feed
    #  at the end to eject the last page.
    #
    echo "$first_line" && cat && printf "\033&l0H" &&
exit 0
fi

exit 2
....

Τέλος, χρειάζεται να ενημερώσετε το LPD για το φίλτρο με την ικανότητα `if`:

[.programlisting]
....
:if=/usr/local/libexec/ifhp:
....

Αυτό είναι όλο. Μπορείτε να πληκτρολογήσετε `lpr plain.text` και `lpr whatever.ps` και τα δύο θα εκτυπωθούν επιτυχώς.

[[printing-advanced-convfilters]]
==== Φίλτρα Μετατροπής

Το επόμενο βήμα μετά την ολοκλήρωση της απλής εγκατάστασης που περιγράψαμε στις <<printing-simple,Βασικές Ρυθμίσεις Εκτυπωτών>>, είναι συνήθως η εγκατάσταση φίλτρων μετατροπής για τους τύπους αρχείων που προτιμάτε (εκτός από απλό κείμενο ASCII).

===== Γιατί να εγκαταστήσετε Φίλτρα Μετατροπής;

Τα φίλτρα μετατροπής κάνουν την εκτύπωση διαφόρων τύπων αρχείων εύκολη υπόθεση. Για παράδειγμα, ας υποθέσουμε ότι έχουμε να κάνουμε αρκετή εργασία με το σύστημα στοιχειοθεσίας TeX, και ότι έχουμε εκτυπωτή PostScript(R). Κάθε φορά που δημιουργούμε ένα αρχείο DVI με το TeX, δεν μπορούμε να εκτυπώσουμε κατευθείαν έως ότου να μετατρέψουμε το αρχείο DVI σε PostScript(R). Η ακολουθία εντολών που πρέπει να ακολουθήσουμε είναι:

[source,bash]
....
% dvips seaweed-analysis.dvi
% lpr seaweed-analysis.ps
....

Με την χρήση ενός φίλτρου μετατροπής για αρχεία DVI, μπορούμε να αποφύγουμε την μετατροπή που πρέπει να κάνουμε κάθε φορά χειροκίνητα, καλώντας το LPD να κάνει τη δουλειά για μας. Τώρα, κάθε φορά που έχουμε ένα αρχείο DVI, για να το τυπώσουμε χρειάζεται μόνο ένα βήμα:

[source,bash]
....
% lpr -d seaweed-analysis.dvi
....

Έχουμε αναθέσει στο LPD να κάνει τη μετατροπή του αρχείου DVI προσθέτοντας του την επιλογή `-d`. Η ενότητα <<printing-lpr-options-format,Επιλογές Μορφοποίησης και Μετατροπής>> περιέχει τους πίνακες επιλογής μετατροπών.

Για κάθε επιλογή μετατροπής που θέλετε να υποστηρίζετε από ένα εκτυπωτή, πρέπει να εγκαταστήσετε ένα _φίλτρο μετατροπής_ και να ορίσετε την διαδρομή του στο αρχείο [.filename]#/etc/printcap#. Ένα φίλτρο μετατροπής είναι σαν το φίλτρο κειμένου στην απλή εγκατάσταση εκτυπωτή (δείτε την ενότητα <<printing-textfilter,Εγκατάσταση Φίλτρου Κειμένου>>) με μόνη διαφορά πως αντί το φίλτρο να εκτυπώνει απλό κείμενο, μετατρέπει το αρχείο σε μια διαφορετική μορφή ώστε να είναι κατανοητό από τον εκτυπωτή.

===== Ποιο Φίλτρο Μετατροπής θα Πρέπει να Εγκαταστήσω;

Θα πρέπει να εγκαθιστάτε τα φίλτρα μετατροπής που νομίζετε πως θα χρησιμοποιήσετε. Αν εκτυπώνετε αρκετά δεδομένα DVI, τότε είναι λογικό να συμπεριλάβετε ένα φίλτρο μετατροπής DVI. Αν εκτυπώνετε συχνά δεδομένα troff, θα θέλετε να εγκαταστήσετε ένα φίλτρο troff.

Ο ακόλουθος πίνακας συνοψίζει τα φίλτρα με τα οποία συνεργάζεται το LPD, τις καταχωρίσεις της αντίστοιχης ικανότητας στο αρχείο [.filename]#/etc/printcap#, και πως να τις καλέσετε μέσω της εντολής `lpr`:

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Τύπος αρχείου
| Ικανότητα /etc/printcap
| Παράμετρος εντολής lpr

|cifplot
|`cf`
|`-c`

|DVI
|`df`
|`-d`

|plot
|`gf`
|`-g`

|ditroff
|`nf`
|`-n`

|FORTRAN text
|`rf`
|`-f`

|troff
|`tf`
|`-f`

|raster
|`vf`
|`-v`

|plain text
|`if`
|none, `-p`, or `-l`
|===

Στο παράδειγμα μας, αν χρησιμοποιήσουμε `lpr -d` σημαίνει ότι ο εκτυπωτής χρειάζεται την ικανότητα `df` στην καταχώριση του στο [.filename]#/etc/printcap#.

Αν και κάποιοι μπορεί να ισχυριστούν το αντίθετο, μερικοί τύποι αρχείων όπως είναι τα κείμενα και γραφικά FORTRAN είναι ξεπερασμένα. Μπορείτε να δώσετε νέα πνοή σε αρχεία αυτού του τύπου (ή και οποιασδήποτε άλλης μορφής εξόδου), εγκαθιστώντας προσαρμοσμένα φίλτρα. Για παράδειγμα, ας υποθέσουμε ότι θα θέλατε να εκτυπώσετε κατευθείαν αρχεία Printerleaf (αρχεία προερχόμενα από το πρόγραμμα επιτραπέζιας τυπογραφίας Interleaf), αλλά δεν θα εκτυπώσετε ποτέ διαγράμματα (plots). Θα μπορούσατε να εγκαταστήσετε ένα φίλτρο μετατροπής αρχείων Printerleaf υπό την ικανότητα `gf` και να εκπαιδεύσετε τους χρήστες σας ότι η εντολή `lpr -g` σημαίνει "τύπωσε αρχεία Printerleaf."

===== Εγκατάσταση Φίλτρων Μετατροπών

Από τη στιγμή που τα φίλτρα μετατροπής είναι προγράμματα που δεν ανήκουν στο βασικό σύστημα εγκατάστασης του FreeBSD, είναι πιο σωστό να εγκατασταθούν στον κατάλογο [.filename]#/usr/local#. Ένας συνήθης προορισμός των προγραμμάτων αυτών είναι ο κατάλογος [.filename]#/usr/local/libexec#, μια που πρόκειται για εξειδικευμένα προγράμματα που εκτελούνται μόνο από το LPD. Οι απλοί χρήστες δεν θα χρειαστεί ποτέ να τα εκτελέσουν.

Για να ενεργοποιήσετε ένα φίλτρο μετατροπής, προσδιορίστε τη διαδρομή του στο αρχείο [.filename]#/etc/printcap#, αλλάζοντας την κατάλληλη ικανότητα στον εκτυπωτή που επιθυμείτε να το χρησιμοποιήσετε.

Στο παράδειγμα μας, θα προσθέσουμε το φίλτρο μετατροπής DVI στην καταχώριση μας για τον εκτυπωτή με το όνομα `bamboo`. Ακολουθεί, λοιπόν, το παράδειγμα για το αρχείο [.filename]#/etc/printcap#, με την νέα ικανότητα `df` για τον εκτυπωτή `bamboo`:

[.programlisting]
....
#
#  /etc/printcap for host rose - added df filter for bamboo
#
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :sh:sd=/var/spool/lpd/rattan:\
        :lp=/dev/lpt0:\
        :if=/usr/local/libexec/if-simple:

bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:sd=/var/spool/lpd/bamboo:\
        :lp=/dev/ttyu5:ms#-parenb cs8 clocal crtscts:rw:\
        :if=/usr/local/libexec/psif:\
        :df=/usr/local/libexec/psdf:
....

Το φίλτρο DVI είναι ένα shell script που ονομάζεται [.filename]#/usr/local/libexec/psdf#, το οποίο και παραθέτουμε παρακάτω:

[.programlisting]
....
#!/bin/sh
#
#  psdf - DVI to PostScript printer filter
#  Installed in /usr/local/libexec/psdf
#
# Invoked by lpd when user runs lpr -d
#
exec /usr/local/bin/dvips -f | /usr/local/libexec/lprps "$@"
....

Αυτό το script τρέχει το `dvips` σε κατάσταση φίλτρου (με την παράμετρο `-f`) στην standard input, από όπου και λαμβάνει την εργασία προς εκτύπωση. Αυτό ξεκινά το φίλτρο εκτύπωσης PostScript(R) `lprps` (δείτε την ενότητα <<printing-advanced-if-conversion,Συμβατότητα Εργασιών Απλού Κειμένου σε εκτυπωτές PostScript(R)>>) δίνοντας του και τις παραμέτρους που πέρασε το LPD στο παραπάνω script. Το `lprps` θα χρησιμοποιήσει αυτές τις παραμέτρους για την καταμέτρηση των εκτυπωμένων σελίδων.

===== Ακόμα μερικά Παραδείγματα Φίλτρων Μετατροπής

Από τη στιγμή που δεν υπάρχει αυτοματοποιημένη μέθοδος για την εγκατάσταση των φίλτρων μετατροπής, ας μας επιτραπεί να παρέχουμε μερικά ακόμη παραδείγματα. Μπορείτε να τα χρησιμοποιήσετε σαν οδηγό για την δημιουργία των δικών σας φίλτρων. Αν νομίζετε πως είναι κατάλληλα για την περίπτωση σας μπορείτε να τα χρησιμοποιήσετε και κατευθείαν.

Αυτό το παράδειγμα script είναι ένα φίλτρο μετατροπής ράστερ (αρχείου GIF για την ακρίβεια) για έναν εκτυπωτή Hewlett Packard LaserJet III-Si:

[.programlisting]
....
#!/bin/sh
#
#  hpvf - Convert GIF files into HP/PCL, then print
#  Installed in /usr/local/libexec/hpvf

PATH=/usr/X11R6/bin:$PATH; export PATH
giftopnm | ppmtopgm | pgmtopbm | pbmtolj -resolution 300 \
    && exit 0 \
    || exit 2
....

Δουλεύει ως εξής: μετατρέπει το αρχείο GIF σε ένα γενικό φορητό τύπο anymap, εν συνεχεία το μετατρέπει σε ένα φορητό τύπο graymap, έπειτα σε ένα φορητό τύπο bitmap, και τέλος το μετατρέπει σε δεδομένα συμβατά με PCL για τον LaserJet.

Εδώ είναι το αρχείο [.filename]#/etc/printcap# με μια καταχώριση για έναν εκτυπωτή που χρησιμοποιεί το παραπάνω φίλτρο:

[.programlisting]
....
#
#  /etc/printcap for host orchid
#
teak|hp|laserjet|Hewlett Packard LaserJet 3Si:\
        :lp=/dev/lpt0:sh:sd=/var/spool/lpd/teak:mx#0:\
        :if=/usr/local/libexec/hpif:\
        :vf=/usr/local/libexec/hpvf:
....

Το ακόλουθο script είναι ένα φίλτρο μετατροπής δεδομένων troff από το σύστημα στοιχειοθεσίας groff για τον εκτυπωτή PostScript(R) με όνομα `bamboo`:

[.programlisting]
....
#!/bin/sh
#
#  pstf - Convert groff's troff data into PS, then print.
#  Installed in /usr/local/libexec/pstf
#
exec grops | /usr/local/libexec/lprps "$@"
....

Το παραπάνω script χρησιμοποιεί πάλι το `lprps` για να χειριστεί την επικοινωνία με τον εκτυπωτή. Αν ο εκτυπωτής ήταν σε παράλληλη πόρτα τότε θα είχαμε, αντιθέτως, χρησιμοποιήσει το ακόλουθο script:

[.programlisting]
....
#!/bin/sh
#
#  pstf - Convert groff's troff data into PS, then print.
#  Installed in /usr/local/libexec/pstf
#
exec grops
....

Εδώ είναι η καταχώριση που χρειάζεται να προσθέσουμε στο [.filename]#/etc/printcap# για να ενεργοποιήσουμε το φίλτρο:

[.programlisting]
....
:tf=/usr/local/libexec/pstf:
....

Εδώ είναι ένα παράδειγμα που μας επιτρέπει να εκτυπώσουμε παλαιό κώδικα της FORTRAN. Είναι ένα φίλτρο κειμένου για FORTRAN για οποιονδήποτε εκτυπωτή μπορεί να εκτυπώσει κατευθείαν απλό κείμενο. Θα το εγκαταστήσουμε για έναν εκτυπωτή που ονομάζεται `teak`:

[.programlisting]
....
#!/bin/sh
#
# hprf - FORTRAN text filter for LaserJet 3si:
# Installed in /usr/local/libexec/hprf
#

printf "\033&k2G" && fpr && printf "\033&l0H" &&
 exit 0
exit 2
....

Και θα προσθέσουμε αυτή τη γραμμή στο [.filename]#/etc/printcap# για να ενεργοποιήσουμε το φίλτρο για τον εκτυπωτή `teak`:

[.programlisting]
....
:rf=/usr/local/libexec/hprf:
....

Και ένα τελευταίο κάπως περίπλοκο παράδειγμα: Θα προσθέσουμε ένα φίλτρο DVI στον εκτυπωτή LaserJet `teak` που αναφέραμε προηγούμενα. Καταρχήν το εύκολο μέρος: αναβαθμίζουμε το [.filename]#/etc/printcap# με την τοποθεσία όπου βρίσκεται το φίλτρο DVI:

[.programlisting]
....
:df=/usr/local/libexec/hpdf:
....

Τώρα, το δύσκολο μέρος: η κατασκευή του φίλτρου. Θα χρειαστούμε ένα πρόγραμμα μετατροπής από DVI-σε-LaserJet/PCL. Στην Συλλογή των Ports του FreeBSD (δείτε crossref:ports[ports,Συλλογή των Ports]) υπάρχει ένα τέτοιο πρόγραμμα: Το όνομα του πακέτου είναι `dvi2xx`. Η εγκατάσταση του πακέτου, μας παρέχει ακριβώς το πρόγραμμα που χρειαζόμαστε, το `dvilj2p`, το οποίο μετατρέπει τον κώδικα DVI σε κώδικα συμβατό με LaserJet IIp, LaserJet III, και LaserJet 2000.

Το `dvilj2p` κάνει το φίλτρο `hpdf` αρκετά περίπλοκο από τη στιγμή που το `dvilj2p` δε μπορεί να διαβάσει από το standard input. Χρειάζεται να δουλέψει με κάποιο όνομα αρχείου. Ακόμη χειρότερα, το όνομα του αρχείου πρέπει να τελειώνει σε [.filename]#.dvi# κι επομένως η χρήση του [.filename]#/dev/fd/0# ως standard input είναι προβληματική. Θα μπορούσαμε να αντιμετωπίσουμε το πρόβλημα δημιουργώντας (συμβολικούς) δεσμούς με κάποιο προσωρινό όνομα αρχείου (που να τελειώνει σε [.filename]#.dvi#) για το [.filename]#/dev/fd/0#, και με αυτό τον τρόπο να εξαναγκάσουμε το `dvilj2p` να διαβάζει από το standard input.

Ακόμη ένα πρόβλημα που προκύπτει είναι το γεγονός πως δεν μπορούμε να χρησιμοποιήσουμε το [.filename]#/tmp# για τον προσωρινό δεσμό. Οι συμβολικοί δεσμοί ανήκουν στον χρήστη και στην ομάδα `bin`, ενώ το φίλτρο τρέχει σαν χρήστης `daemon`. Επίσης στον κατάλογο [.filename]#/tmp# είναι ενεργό το sticky bit. Το φίλτρο μπορεί να δημιουργήσει το δεσμό, αλλά δεν θα είναι ικανό να τον εξαλείψει και να τον αφαιρέσει από τη στιγμή που αυτός θα ανήκει σε διαφορετικό χρήστη.

Αντίθετα, το φίλτρο θα φτιάξει το συμβολικό link στον τρέχοντα κατάλογο, που είναι ο κατάλογος παροχέτευσης (spooling) (και που προσδιορίζεται από την ικανότητα `sd` στο [.filename]#/etc/printcap#). Αυτό είναι το τέλειο μέρος για να δουλεύουν τα φίλτρα, ειδικά λόγω του ότι (μερικές φορές) υπάρχει περισσότερες ελεύθερος χώρος στο δίσκο στον κατάλογο παροχέτευσης (spool) από ότι στο [.filename]#/tmp#.

Και τελικά, ιδού το φίλτρο:

[.programlisting]
....
#!/bin/sh
#
#  hpdf - Print DVI data on HP/PCL printer
#  Installed in /usr/local/libexec/hpdf

PATH=/usr/local/bin:$PATH; export PATH

#
#  Define a function to clean up our temporary files.  These exist
#  in the current directory, which will be the spooling directory
#  for the printer.
#
cleanup() {
   rm -f hpdf$$.dvi
}

#
#  Define a function to handle fatal errors: print the given message
#  and exit 2.  Exiting with 2 tells LPD to do not try to reprint the
#  job.
#
fatal() {
    echo "$@" 1>&2
    cleanup
    exit 2
}

#
#  If user removes the job, LPD will send SIGINT, so trap SIGINT
#  (and a few other signals) to clean up after ourselves.
#
trap cleanup 1 2 15

#
#  Make sure we are not colliding with any existing files.
#
cleanup

#
#  Link the DVI input file to standard input (the file to print).
#
ln -s /dev/fd/0 hpdf$$.dvi || fatal "Cannot symlink /dev/fd/0"

#
#  Make LF = CR+LF
#
printf "\033&k2G" || fatal "Cannot initialize printer"

#
#  Convert and print.  Return value from dvilj2p does not seem to be
#  reliable, so we ignore it.
#
dvilj2p -M1 -q -e- dfhp$$.dvi

#
#  Clean up and exit
#
cleanup
exit 0
....

[[printing-advanced-autoconv]]
===== Αυτοματοποιημένες Μετατροπές: Μία Εναλλακτική στα Φίλτρα Μετατροπής

Όλα τα φίλτρα μετατροπής μπορεί να πληρούν το περιβάλλον εκτυπώσεων σας, αλλά υποχρεώνουν τον χρήστη να προσδιορίζει (στην γραμμή εντολών του man:lpr[1]) ποιό από αυτά θα χρησιμοποιηθεί. Αν οι χρήστες σας δεν είναι ιδιαίτερα εξοικειωμένοι με τους Η/Υ, το να πρέπει να αναφέρουν κάθε φορά ένα φίλτρο πιθανώς να είναι ενοχλητικό. Είναι ακόμα χειρότερο ωστόσο να γίνει λανθασμένη επιλογή φίλτρου, το οποίο θα εκτελεστεί σε ακατάλληλο για αυτό τύπο αρχείου, και θα προκαλέσει την σπατάλη εκατοντάδων σελίδων χαρτιού.

Αντί να εγκαταστήσετε οποιοδήποτε φίλτρο μετατροπής, μπορεί να θέλετε να δοκιμάσετε να έχετε ένα φίλτρο κειμένου (αφού είναι το προεπιλεγμένο φίλτρο) που να ανιχνεύει τον τύπο του αρχείου που έχει ζητηθεί να εκτυπωθεί και να εκτελεί αυτόματα το κατάλληλο φίλτρο μετατροπής. Εργαλεία σαν το `file` μπορούν να σας βοηθήσουν. Μπορεί να είναι δύσκολο να προσδιοριστούν οι διαφορές μεταξύ _κάποιων_ τύπων αρχείων-αλλά, φυσικά, μπορείτε πάντα να παρέχετε φίλτρα μετατροπής ειδικά για αυτές τις περιπτώσεις.

Η Συλλογή των Ports του FreeBSD έχει ένα φίλτρο κειμένου που εκτελεί αυτόματες μετατροπές και ονομάζεται `apsfilter`. Μπορεί να ανιχνεύει απλό κείμενο, PostScript(R), DVI και σχεδόν οποιοδήποτε τύπο αρχείου, να εκτελεί την κατάλληλη μετατροπή, και να εκτυπώνει.

[[printing-advanced-of]]
==== Φίλτρα Εξόδου

Το σύστημα παροχέτευσης LPD υποστηρίζει έναν ακόμη τύπο φίλτρου που ίσως να μην έχετε εξερευνήσει ακόμα: το φίλτρο εξόδου. Το φίλτρο εξόδου προορίζεται μόνο για εκτύπωση απλού κειμένου, όπως το φίλτρο κειμένου, αλλά με πολλές απλοποιήσεις. Εάν χρησιμοποιείτε φίλτρο εξόδου αλλά όχι φίλτρο κειμένου, τότε:

* Το LPD ξεκινά ένα φίλτρο εξόδου μόνο μια φορά για όλη την εργασία, αντί ένα χωριστό για κάθε αρχείο της εργασίας.
* Το LPD δεν φροντίζει να αναγνωρίσει την αρχή ή το τέλος των αρχείων μέσα στην ίδια την εργασία όταν χρησιμοποιείται το φίλτρο εξόδου.
* Το LPD δεν περνάει στο φίλτρο τα δεδομένα εισόδου του χρήστη ή το όνομα του μηχανήματος, επομένως δεν προορίζεται για καταμέτρηση εκτυπωμένων σελίδων. Το φίλτρο εξόδου δέχεται μόνος τις παραμέτρους:
+`filter-name` -w__width__ -l__length__
+ 
Όπου το _width_ είναι από την ικανότητα `pw` και το _length_ είναι από την ικανότητα `pl` για τον συγκεκριμένο εκτυπωτή.

Μην παρασύρεστε από την απλότητα του φίλτρου εξόδου. Αν επιθυμείτε κάθε αρχείο μιας εργασίας να ξεκινά σε μια νέα σελίδα, το φίλτρο εξόδου _δεν κάνει για σας_. Χρησιμοποιήστε ένα φίλτρο κειμένου (γνωστό και ως φίλτρο εισόδου). Δείτε την ενότητα <<printing-textfilter,Εγκατάσταση Φίλτρου Κειμένου>>. Επιπλέον, ένα φίλτρο εξόδου είναι στην πραγματικότητα _πιο περίπλοκο_ αφού πρέπει να εξετάζει την ροή των byte που αποστέλλεται προς αυτό για ειδικούς χαρακτήρες flag και πρέπει να στέλνει σήματα στον εαυτό του για λογαριασμό του LPD.

Ωστόσο, ένα φίλτρο εξόδου είναι _αναγκαίο_ αν θέλετε σελίδες κεφαλίδας και χρειάζεται να στέλνετε ακολουθίες διαφυγής ή άλλες ακολουθίες αρχικοποίησης προκειμένου να τις εκτυπώσετε. (Αλλά είναι επίσης _μάταιο_ αν θέλετε να χρεώνετε σελίδες κεφαλίδας στον λογαριασμό του αντίστοιχου χρήστη, από τη στιγμή που το LPD δεν στέλνει καμιά πληροφορία για τον χρήστη ή τον υπολογιστή στο φίλτρο εξόδου.)

Το LPD επιτρέπει την συνύπαρξη ενός φίλτρου εξόδου και άλλων φίλτρων (κειμένου ή διαφορετικού τύπου) στον ίδιο εκτυπωτή. Σε αυτές τις περιπτώσεις, το LPD θα ξεκινά το φίλτρο εξόδου μόνο για την εκτύπωση της σελίδας κεφαλίδας (δείτε την ενότητα <<printing-advanced-header-pages,Σελίδες Κεφαλίδας>>). Το LPD θα αναμένει το φίλτρο εξόδου να _σταματήσει από μόνο του_ όταν του στείλει δύο bytes: ένα ASCII 031 ακολουθούμενο από ένα ASCII 001. Όταν ένα φίλτρο εξόδου βλέπει αυτά τα δύο bytes (031, 001), θα πρέπει να σταματά στέλνοντας σήμα `SIGSTOP` στον εαυτό του. Όταν το LPD ολοκληρώσει την εκτέλεση και των υπολοίπων φίλτρων, θα επανεκκινήσει το φίλτρο εξόδου στέλνοντας του το σήμα `SIGCONT`.

Αν υπάρχει φίλτρο εξόδου, αλλά _δεν υπάρχει_ φίλτρο κειμένου και το LPD δουλεύει σε εργασία απλού κειμένου, το LPD χρησιμοποιεί το φίλτρο εξόδου για την εκτέλεση της εργασίας. Όπως αναφέραμε και παραπάνω, το φίλτρο εξόδου θα εκτυπώσει κάθε αρχείο εργασίας στη σειρά, δίχως δυνατότητα παρεμβολής κενής σελίδας ή άλλων ρυθμίσεων στην τροφοδοσία χαρτιού, και πιθανώς αυτό να _μην_ είναι επιθυμητό. Σχεδόν σε όλες τις περιπτώσεις, θα χρειαστείτε ένα φίλτρο κειμένου.

Το πρόγραμμα `lpf`, που αναφέραμε νωρίτερα σαν φίλτρο κειμένου, μπορεί να τρέξει και σαν φίλτρο εξόδου. Αν χρειάζεστε ένα γρήγορο φίλτρο εξόδου αλλά δεν θέλετε να γράψετε τον κώδικα ανίχνευσης των byte και τον κώδικα αποστολής σημάτων, δοκιμάστε το `lpf`. Μπορείτε επίσης να χρησιμοποιήσετε το `lpf` μέσα από ένα shell script το οποίο θα χειρίζεται τους κωδικούς αρχικοποίησης που ίσως να χρειάζεται ο εκτυπωτής.

[[printing-advanced-lpf]]
==== `lpf`: ένα Φίλτρο Κειμένου

Το πρόγραμμα [.filename]#/usr/libexec/lpr/lpf# που παρέχεται με τη διανομή εκτελέσιμων του FreeBSD είναι ένα φίλτρο κειμένου (φίλτρο εισόδου) που μπορεί να παραγραφοποιεί την έξοδο (εργασίες που έχουν σταλεί με `lpr -i`), να επιτρέπει την διέλευση literal χαρακτήρων (εργασίες που έχουν σταλεί με `lpr -l`), να ρυθμίζει την θέση εκτύπωσης με τη χρήση χαρακτήρων backspace και tab στην εργασία, και να κάνει καταμέτρηση των εκτυπωμένων σελίδων. Επίσης μπορεί να ενεργεί και σαν φίλτρο εξόδου.

Το `lpf` είναι κατάλληλο για διάφορα περιβάλλοντα εκτύπωσης. Αν και δεν έχει δυνατότητα αποστολής ακολουθιών αρχικοποίησης στον εκτυπωτή, είναι εύκολο να γράψετε ένα shell script για να κάνετε την απαραίτητη αρχικοποίηση και να εκτελέσετε έπειτα το `lpf`.

Για να κάνει σωστά καταμέτρηση σελίδων, το `lpf` χρειάζεται κατάλληλες τιμές για τις ικανότητες `pw` και `pl` στο αρχείο [.filename]#/etc/printcap#. Χρησιμοποιεί αυτές τις τιμές για να προσδιορίσει πόσο κείμενο μπορεί να χωρέσει σε μία σελίδα και από πόσες σελίδες αποτελείται η εργασία του χρήστη. Για περισσότερες πληροφορίες σχετικά με την καταμέτρηση σελίδων, συμβουλευτείτε την <<printing-advanced-acct,Καταμέτρηση Χρήσης Εκτυπωτών>>.

[[printing-advanced-header-pages]]
=== Σελίδες Κεφαλίδας

Αν έχετε _αρκετούς_ χρήστες, και όλοι τους χρησιμοποιούν διάφορους εκτυπωτές, τότε πιθανώς να θεωρείτε τις _σελίδες κεφαλίδας_ ως αναγκαίο κακό.

Οι σελίδες κεφαλίδας, γνωστές επίσης και ως _banner_ ή _σελίδες burst_ αναγνωρίζουν σε ποιον ανήκουν οι εργασίες μετά την εκτύπωση τους. Συνήθως τυπώνονται με μεγάλα, έντονα γράμματα, και ίσως με διακοσμητικά περιγράμματα, ώστε σε μια στοίβα εκτυπώσεων να ξεχωρίζουν από τα πραγματικά έγγραφα εργασιών των χρηστών. Επιτρέπουν έτσι στους χρήστες να βρίσκουν γρήγορα τις εργασίες τους. Το προφανές μειονέκτημα σε μια σελίδα κεφαλίδας είναι πως πρόκειται να εκτυπωθεί μια ακόμα σελίδα για κάθε μία εργασία. Η εφήμερη χρησιμότητα τους διαρκεί λίγα λεπτά, και ο προορισμός τους είναι ο κάδος αχρήστων/ανακύκλωσης. (Παρατηρήστε πως οι σελίδες κεφαλίδας είναι ανά εργασία, και όχι ανά αρχείο σε μια εργασία, επομένως το αχρηστευμένο χαρτί ίσως να μην είναι τόσο πολύ).

Το σύστημα LPD μπορεί να παρέχει αυτόματα σελίδες κεφαλίδας για τις εκτυπώσεις σας, _αν_ ο εκτυπωτής σας μπορεί να εκτυπώσει άμεσα απλό κείμενο. Αν έχετε εκτυπωτή PostScript(R), θα χρειαστείτε ένα εξωτερικό πρόγραμμα για να δημιουργήσετε την σελίδα κεφαλίδας. Δείτε το <<printing-advanced-header-pages-ps,Σελίδες Κεφαλίδας σε Εκτυπωτές PostScript(R)>>.

[[printing-advanced-header-pages-enabling]]
==== Ενεργοποίηση Σελίδων Κεφαλίδας

Στην ενότητα <<printing-simple,Βασικές Ρυθμίσεις Εκτυπωτών>>, απενεργοποιήσαμε τις σελίδες κεφαλίδας με την καταχώριση `sh` (σημαίνει "suppress header") στο αρχείο [.filename]#/etc/printcap#. Για να ενεργοποιήσετε τις σελίδες κεφαλίδας για κάποιον εκτυπωτή, απλά αφαιρέστε την ικανότητα `sh`.

Ακούγεται εύκολο, δεν νομίζετε;

Έτσι είναι. _Ίσως_ χρειαστεί να παρέχετε ένα φίλτρο εξόδου για να στείλετε εντολές αρχικοποίησης στον εκτυπωτή. Εδώ είναι ένα παράδειγμα φίλτρου εξόδου για εκτυπωτές συμβατούς με τον τύπο PCL της Hewlett Packard:

[.programlisting]
....
#!/bin/sh
#
#  hpof - Output filter for Hewlett Packard PCL-compatible printers
#  Installed in /usr/local/libexec/hpof

printf "\033&k2G" || exit 2
exec /usr/libexec/lpr/lpf
....

Προσδιορίστε την διαδρομή προς το φίλτρο εξόδου στην ικανότητα `of`. Δείτε την ενότητα <<printing-advanced-of,Φίλτρα Εξόδου>> για περισσότερες πληροφορίες.

Εδώ είναι ένα παράδειγμα αρχείου [.filename]#/etc/printcap# για τον εκτυπωτή `teak` από το προηγούμενο παράδειγμα. Ενεργοποιήσαμε τις σελίδες κεφαλίδας και προσθέσαμε το παραπάνω φίλτρο εξόδου:

[.programlisting]
....
#
#  /etc/printcap for host orchid
#
teak|hp|laserjet|Hewlett Packard LaserJet 3Si:\
        :lp=/dev/lpt0:sd=/var/spool/lpd/teak:mx#0:\
        :if=/usr/local/libexec/hpif:\
        :vf=/usr/local/libexec/hpvf:\
        :of=/usr/local/libexec/hpof:
....

Τώρα, όταν οι χρήστες εκτυπώνουν εργασίες στον `teak`, θα παίρνουν και μία σελίδα κεφαλίδας ανά εργασία. Αν οι χρήστες θέλουν να ξοδεύουν χρόνο ψάχνοντας για τις εκτυπώσεις τους, μπορούν να παρεμποδίσουν τις σελίδες κεφαλίδας αποστέλλοντας τις εργασίες τους με `lpr -h`. Δείτε την ενότητα <<printing-lpr-options-misc,Επιλογές Σελίδων Κεφαλίδας>> για περισσότερες επιλογές του man:lpr[1].

[NOTE]
====
Το LPD στέλνει το χαρακτήρα αλλαγής σελίδας (form feed) αμέσως μετά τη σελίδα κεφαλίδας. Αν ο εκτυπωτής σας χρησιμοποιεί διαφορετικό χαρακτήρα ή ακολουθία χαρακτήρων για την αλλαγή σελίδας, προσδιορίστε τα με την ικανότητα `ff` στο αρχείο [.filename]#/etc/printcap#.
====

[[printing-advanced-header-pages-controlling]]
==== Έλεγχος Σελίδων Κεφαλίδας

Μετά την ενεργοποίηση των σελίδων κεφαλίδας, το LPD θα παράγει μία _επιμήκη κεφαλίδα_, μία ολόκληρη σελίδα με μεγάλα γράμματα που προσδιορίζει τον χρήστη, τον υπολογιστή (host), και την εργασία. Εδώ είναι ένα παράδειγμα (η `kelly` εκτύπωσε την εργασία με όνομα "outline" από τον υπολογιστή `rose`):

[source,bash]
....
      k                   ll       ll
      k                    l        l
      k                    l        l
      k   k     eeee       l        l     y    y
      k  k     e    e      l        l     y    y
      k k      eeeeee      l        l     y    y
      kk k     e           l        l     y    y
      k   k    e    e      l        l     y   yy
      k    k    eeee      lll      lll     yyy y
                                               y
                                          y    y
                                           yyyy

                                   ll
                          t         l        i
                          t         l
       oooo    u    u   ttttt       l       ii     n nnn     eeee
      o    o   u    u     t         l        i     nn   n   e    e
      o    o   u    u     t         l        i     n    n   eeeeee
      o    o   u    u     t         l        i     n    n   e
      o    o   u   uu     t  t      l        i     n    n   e    e
       oooo     uuu u      tt      lll      iii    n    n    eeee

      r rrr     oooo     ssss     eeee
      rr   r   o    o   s    s   e    e
      r        o    o    ss      eeeeee
      r        o    o      ss    e
      r        o    o   s    s   e    e
      r         oooo     ssss     eeee

                                              Job:  outline
                                              Date: Sun Sep 17 11:04:58 1995
....

Το LPD προσθέτει μια εντολή αλλαγής σελίδας (form feed) μετά από αυτό το κείμενο έτσι ώστε η εργασία να ξεκινήσει σε νέα σελίδα (εκτός αν έχετε προσδιορίσει την ικανότητα `sf` (suppress form feeds) για τον εκτυπωτή στο αρχείο [.filename]#/etc/printcap#).

Αν προτιμάτε, το LPD μπορεί να φτιάξει μια _μικρότερου μήκους κεφαλίδα_. Προσδιορίστε `sb` (short banner) στο αρχείο [.filename]#/etc/printcap#. Η σελίδα κεφαλίδας θα μοιάζει σαν αυτή:

[source,bash]
....
rose:kelly  Job: outline  Date: Sun Sep 17 11:07:51 1995
....

Το LPD τυπώνει (από προεπιλογή) πρώτα την σελίδα κεφαλίδας, και μετά την εργασία. Για να αντιστρέψετε την σειρά, χρησιμοποιήστε την ικανότητα `hl` (header last) στο αρχείο [.filename]#/etc/printcap#.

[[printing-advanced-header-pages-accounting]]
==== Καταμέτρηση με Σελίδες Κεφαλίδας

Η χρήση των προεγκατεστημένων σελίδων κεφαλίδας του LPD ουσιαστικά υποχρεώνουν την τήρηση του παρακάτω κανόνα όταν κάνουμε καταμέτρηση χρήσης του εκτυπωτή: Οι σελίδες κεφαλίδας πρέπει να διατίθενται _ελεύθερα (δίχως χρέωση)_.

Γιατί;

Διότι το φίλτρο εξόδου είναι το μοναδικό εξωτερικό πρόγραμμα που έχει τον έλεγχο στην εκτύπωση της κεφαλίδας και θα μπορούσε να κάνει καταμέτρηση, αλλά ωστόσο δεν παρέχει καμία πληροφορία για _τον χρήστη ή τον υπολογιστή_ ή κάποιο άλλο αρχείο καταμέτρησης, επομένως δεν γνωρίζει σε ποιόν να αποδώσει την χρήση του εκτυπωτή. Δεν αρκεί απλά να "προσθέσετε μία ακόμη σελίδα στην καταμέτρηση" τροποποιώντας το φίλτρο κειμένου ή οποιοδήποτε άλλο φίλτρο μετατροπής (το οποίο διαθέτει τις πληροφορίες χρήστη και υπολογιστή), από τη στιγμή που οι χρήστες έχουν την δυνατότητα να παρεμποδίσουν τις σελίδες κεφαλίδας με `lpr -h`. Θα μπορούσαν πάλι να χρεωθούν για σελίδες κεφαλίδας που δεν εκτύπωσαν. Βασικά, η `lpr -h` θα είναι η προτιμώμενη επιλογή σε ένα περιβάλλον που οι χρήστες έχουν οικολογική συνείδηση, αλλά δεν μπορείτε πραγματικά να παροτρύνετε οποιονδήποτε να τη χρησιμοποιήσει.

_Δεν είναι αρκετό_ απλά κάθε φίλτρο σας να δημιουργεί τη δικιά του σελίδα κεφαλίδας (έτσι ώστε να μπορεί να χρεώνει με αυτό τον τρόπο). Αν οι χρήστες επιθυμούν την επιλογή παρεμπόδισης των σελίδων κεφαλίδας με `lpr -h`, θα συνεχίσουν να τις παραλαμβάνουν - και να χρεώνονται για αυτές - αφού το LPD δεν έχει δυνατότητα να περάσει σε οποιοδήποτε φίλτρο την επιλογή `-h`.

Επομένως, ποιες επιλογές έχετε;

Μπορείτε:

* Να αποδεχθείτε την υπόδειξη του LPD και να παρέχετε τις σελίδες κεφαλίδας ελεύθερα.
* Να εγκαταστήσετε εναλλακτικές λύσεις αντί του LPD, όπως το LPRng. Η ενότητα <<printing-lpd-alternatives,Εναλλακτικές Λύσεις για τον Στάνταρ Spooler>> δίνει περισσότερες πληροφορίες για άλλες εφαρμογές παροχέτευσης που μπορείτε να χρησιμοποιήσετε αντί για το LPD.
* Να γράψετε ένα _έξυπνο_ φίλτρο εξόδου. Υπό κανονικές συνθήκες, ένα "φίλτρο εξόδου" δεν κάνει τίποτε παραπάνω από την αρχικοποίηση ενός εκτυπωτή ή μερικές απλές μετατροπές χαρακτήρων. Είναι κατάλληλο για σελίδες κεφαλίδας και για εργασίες απλού κειμένου (όταν δεν υπάρχει φίλτρο (εισόδου) κειμένου). Αλλά αν υπάρχει φίλτρο κειμένου για εργασίες απλού κειμένου, τότε το LPD θα ενεργοποιεί το φίλτρο εξόδου μόνο για τις σελίδες κεφαλίδας. Και το φίλτρο εξόδου μπορεί να αναλύει το κείμενο της σελίδας κεφαλίδας που δημιουργεί το LPD για να προσδιορίζει τον χρήστη και τον υπολογιστή, ώστε να χρεώνει τις σελίδες κεφαλίδας. Το μόνο επιπλέον πρόβλημα με αυτή τη μέθοδο είναι πως το φίλτρο εξόδου εξακολουθεί να μη γνωρίζει ποιό αρχείο καταμέτρησης να χρησιμοποιήσει (δεν του έχει δοθεί το όνομα του αρχείου από την ικανότητα `af`), αλλά αν το όνομα του αρχείου σας είναι γνωστό, μπορείτε να το ενσωματώσετε απευθείας στον κώδικα του φίλτρου εξόδου. Για να διευκολύνετε την διαδικασία ανάλυσης, χρησιμοποιήστε την ικανότητα `sh` (short header) στο [.filename]#/etc/printcap#. Ίσως πάλι όλα αυτά να είναι υπερβολικά κοπιαστικά, ενώ είναι σίγουρο πως οι χρήστες θα εκτιμήσουν τον γενναιόδωρο διαχειριστή συστήματος που επιτρέπει ελεύθερα τις σελίδες κεφαλίδας.

[[printing-advanced-header-pages-ps]]
==== Σελίδες Κεφαλίδας σε Εκτυπωτές PostScript(R)

Όπως περιγράψαμε παραπάνω, το LPD μπορεί να δημιουργήσει μία σελίδα κεφαλίδας απλού κειμένου, κατάλληλη για πολλούς εκτυπωτές. Οι εκτυπωτές PostScript(R), φυσικά, δεν μπορούν να τυπώσουν κατευθείαν απλό κείμενο, επομένως αυτή η δυνατότητα του LPD για τις σελίδες κεφαλίδας είναι άχρηστη σε αυτή την περίπτωση.

Ένας προφανής τρόπος να παρέχονται σελίδες κεφαλίδας είναι να δημιουργούνται από κάθε φίλτρο μετατροπής και το φίλτρο κειμένου. Τα φίλτρα θα πρέπει να δέχονται ως παραμέτρους το όνομα του χρήστη και του υπολογιστή ώστε να δημιουργούν την κατάλληλη σελίδα κεφαλίδας. Το μειονέκτημα αυτής της μεθόδου είναι πως οι χρήστες θα εκτυπώνουν πάντα σελίδα κεφαλίδας, ακόμη κι αν αποστέλλουν την εργασία τους με `lpr -h`.

Επιτρέψτε μας να εξερευνήσουμε αυτή τη μέθοδο. Το ακόλουθο script δέχεται τρεις παραμέτρους (το όνομα χρήστη - login name, το όνομα του υπολογιστή - host name, και το όνομα εργασίας) και δημιουργεί μία απλή σελίδα κεφαλίδας PostScript(R):

[.programlisting]
....
#!/bin/sh
#
#  make-ps-header - make a PostScript header page on stdout
#  Installed in /usr/local/libexec/make-ps-header
#

#
#  These are PostScript units (72 to the inch).  Modify for A4 or
#  whatever size paper you are using:
#
page_width=612
page_height=792
border=72

#
#  Check arguments
#
if [ $# -ne 3 ]; then
    echo "Usage: `basename $0` <user> <host> <job>" 1>&2
    exit 1
fi

#
#  Save these, mostly for readability in the PostScript, below.
#
user=$1
host=$2
job=$3
date=`date`

#
#  Send the PostScript code to stdout.
#
exec cat <<EOF
%!PS

%
%  Make sure we do not interfere with user's job that will follow
%
save

%
%  Make a thick, unpleasant border around the edge of the paper.
%
$border $border moveto
$page_width $border 2 mul sub 0 rlineto
0 $page_height $border 2 mul sub rlineto
currentscreen 3 -1 roll pop 100 3 1 roll setscreen
$border 2 mul $page_width sub 0 rlineto closepath
0.8 setgray 10 setlinewidth stroke 0 setgray

%
%  Display user's login name, nice and large and prominent
%
/Helvetica-Bold findfont 64 scalefont setfont
$page_width ($user) stringwidth pop sub 2 div $page_height 200 sub moveto
($user) show

%
%  Now show the boring particulars
%
/Helvetica findfont 14 scalefont setfont
/y 200 def
[ (Job:) (Host:) (Date:) ] {
200 y moveto show /y y 18 sub def }
forall

/Helvetica-Bold findfont 14 scalefont setfont
/y 200 def
[ ($job) ($host) ($date) ] {
        270 y moveto show /y y 18 sub def
} forall

%
% That is it
%
restore
showpage
EOF
....

Τώρα, καθένα από τα φίλτρα μετατροπής και το φίλτρο κειμένου μπορούν να καλέσουν το script, πρώτα για να δημιουργήσουν τη σελίδα κεφαλίδας, και έπειτα για να εκτυπώσουν την εργασία του χρήστη. Ακολουθεί το φίλτρο μετατροπής DVI που δείξαμε νωρίτερα, ειδικά διαμορφωμένο για να φτιάξουμε μια σελίδα κεφαλίδας:

[.programlisting]
....
#!/bin/sh
#
#  psdf - DVI to PostScript printer filter
#  Installed in /usr/local/libexec/psdf
#
#  Invoked by lpd when user runs lpr -d
#

orig_args="$@"

fail() {
    echo "$@" 1>&2
    exit 2
}

while getopts "x:y:n:h:" option; do
    case $option in
        x|y)  ;; # Ignore
        n)    login=$OPTARG ;;
        h)    host=$OPTARG ;;
        *)    echo "LPD started `basename $0` wrong." 1>&2
              exit 2
              ;;
    esac
done

[ "$login" ] || fail "No login name"
[ "$host" ] || fail "No host name"

( /usr/local/libexec/make-ps-header $login $host "DVI File"
  /usr/local/bin/dvips -f ) | eval /usr/local/libexec/lprps $orig_args
....

Παρατηρήστε πως το φίλτρο πρέπει να αναλύσει την λίστα παραμέτρων για να προσδιορίσει το όνομα χρήστη και υπολογιστή. Η μέθοδος ανάλυσης είναι παρόμοια και για τα υπόλοιπα φίλτρα μετατροπής. Το φίλτρο κειμένου παίρνει ένα ελαφρώς διαφορετικό σετ παραμέτρων, (δείτε την ενότητα <<printing-advanced-filters,Πως δουλεύουν τα Φίλτρα>>).

Όπως αναφέραμε προηγούμενα, ο παραπάνω σχεδιασμός, αν και πραγματικά απλός, απενεργοποιεί την επιλογή "παρεμπόδισης σελίδων κεφαλίδας" (την επιλογή `-h`) του `lpr`. Αν οι χρήστες επιθυμούν να σώσουν ένα δέντρο (ή λίγα χρήματα, αν χρεώνετε τις σελίδες κεφαλίδας), δεν θα υπάρχει τρόπος για να γίνει αυτό, από τη στιγμή που κάθε εκτύπωση μέσω των φίλτρων θα συνοδεύεται και από μια σελίδα κεφαλίδας για κάθε εργασία.

Για να επιτρέψετε στους χρήστες να απενεργοποιούν τις σελίδες κεφαλίδας ανά εργασία, θα πρέπει να χρησιμοποιήσετε το τέχνασμα που παρουσιάσαμε στην ενότητα <<printing-advanced-header-pages-accounting,Καταμέτρηση με Σελίδες Κεφαλίδας>>: δηλαδή να γράψετε ένα φίλτρο εξόδου που να αναλύει την σελίδα κεφαλίδας που δημιουργείται από το LPD και να κατασκευάζει μια PostScript(R) έκδοση. Αν ο χρήστης στείλει μια εργασία με `lpr -h`, τότε ούτε το LPD, ούτε το φίλτρο εξόδου θα φτιάξουν σελίδα κεφαλίδας. Σε όλες τις άλλες περιπτώσεις, το φίλτρο εξόδου θα διαβάζει το κείμενο από το LPD και θα στέλνει τον κατάλληλο κώδικα PostScript(R) στον εκτυπωτή ώστε να εκτυπώνεται η σελίδα κεφαλίδας.

Αν έχετε εκτυπωτή PostScript(R) με σειριακή σύνδεση, μπορείτε να κάνετε χρήση της `lprps`, η οποία συνοδεύεται από ένα φίλτρο εξόδου, το `psof`, το οποία κάνει τα παραπάνω. Σημειώστε πως το `psof` δεν χρεώνει για τις σελίδες κεφαλίδας.

[[printing-advanced-network-printers]]
=== Εκτυπώσεις μέσω Δικτύου

Το FreeBSD υποστηρίζει τις εκτυπώσεις μέσω δικτύου: μπορεί να στείλει εργασίες σε απομακρυσμένους εκτυπωτές. Η έννοια της δικτυακής εκτύπωσης αναφέρεται γενικά σε δύο διαφορετικά πράγματα:

* Πρόσβαση σε εκτυπωτή συνδεδεμένο σε απομακρυσμένο υπολογιστή (host). Εγκαθιστάτε έναν εκτυπωτή με συμβατική σειριακή ή παράλληλη σύνδεση σε ένα υπολογιστή. Έπειτα, ρυθμίζετε το LPD για να ενεργοποιηθεί η πρόσβαση στον εκτυπωτή από άλλους υπολογιστές του δικτύου. Η ενότητα <<printing-advanced-network-rm,Εκτυπωτές Εγκατεστημένοι σε Απομακρυσμένους Υπολογιστές>> εξηγεί τις απαραίτητες ενέργειες.
* Πρόσβαση σε εκτυπωτή συνδεδεμένο κατευθείαν στο δίκτυο. Εκτός (ή αντί) της συμβατικής σειριακής ή παράλληλης θύρας, ο εκτυπωτής πρέπει να έχει επιπρόσθετα μια δικτυακή διασύνδεση. Ένας τέτοιος εκτυπωτής δουλεύει ως εξής:

** Μπορεί να καταλαβαίνει το πρωτόκολλο LPD και να δημιουργεί ουρά αναμονής για τις εργασίες που προέρχονται από απομακρυσμένους υπολογιστές. Σε αυτή την περίπτωση, ενεργεί σαν ένας κανονικός υπολογιστής που εκτελεί το LPD. Ακολουθήστε την ίδια διαδικασία με την ενότητα <<printing-advanced-network-rm,Εκτυπωτές Εγκατεστημένοι σε Απομακρυσμένους Υπολογιστές>> για να εγκαταστήσετε αυτόν τον εκτυπωτή.
** Μπορεί να υποστηρίζει σύνδεση δικτυακής ροής δεδομένων (data stream). Σε αυτή την περίπτωση, "συνδέετε" τον εκτυπωτή σε έναν υπολογιστή συνδεδεμένο στο δίκτυο, ο οποίος θα είναι υπεύθυνος για την παροχέτευση των εργασιών και την αποστολή τους στον εκτυπωτή. Η ενότητα <<printing-advanced-network-net-if,Εκτυπωτές Με Συνδέσεις Δικτύου>> δίνει μερικές συμβουλές για την εγκατάσταση εκτυπωτών αυτού του τύπου.

[[printing-advanced-network-rm]]
==== Εκτυπωτές Εγκατεστημένοι σε Απομακρυσμένους Υπολογιστές

Το σύστημα παροχέτευσης LPD έχει ενσωματωμένη υποστήριξη για την αποστολή εργασιών σε άλλους υπολογιστές που εκτελούν το LPD (ή που είναι συμβατοί με το LPD). Αυτό το χαρακτηριστικό σας επιτρέπει να εγκαταστήσετε έναν εκτυπωτή σε ένα υπολογιστή και να έχετε πρόσβαση σε αυτόν από άλλους. Επίσης δουλεύει και με εκτυπωτές που έχουν δικτυακές διασυνδέσεις που καταλαβαίνουν το πρωτόκολλο LPD.

Για να ενεργοποιήσετε αυτόν τον τύπο απομακρυσμένης εκτύπωσης, εγκαταστήστε πρώτα έναν εκτυπωτή σε ένα υπολογιστή, τον _υπολογιστή εκτύπωσης (printer host)_, χρησιμοποιώντας την απλή εγκατάσταση εκτυπωτή που περιγράφεται στην ενότητα <<printing-simple,Βασικές Ρυθμίσεις Εκτυπωτών>>. Κάντε όσες προχωρημένες ρυθμίσεις χρειάζεστε όπως αναφέρεται στις <<printing-advanced,Ρυθμίσεις Εκτυπωτών για Προχωρημένους>>. Ελέγξτε τον εκτυπωτή και δείτε αν δουλεύει με τα χαρακτηριστικά του LPD που έχετε ενεργοποιήσει. Επίσης βεβαιωθείτε πως ο _τοπικός υπολογιστής (local host)_ είναι εξουσιοδοτημένος να χρησιμοποιεί τις υπηρεσίες του LPD στον _απομακρυσμένο υπολογιστή (remote host)_ (δείτε <<printing-advanced-restricting-remote,Παρεμπόδιση Εργασιών από Απομακρυσμένους Υπολογιστές>>).

Εάν χρησιμοποιείτε εκτυπωτή με δικτυακή διασύνδεση που είναι συμβατός με το LPD, τότε ο _ο υπολογιστής εκτύπωσης (printer host)_ είναι ο εν λόγω εκτυπωτής, και το _όνομα του εκτυπωτή_ είναι το όνομα που έχετε ορίσει για τον εκτυπωτή. Δείτε την τεκμηρίωση που συνοδεύει τον εκτυπωτή σας και/ή την κάρτα δικτύου του.

[TIP]
====

Αν χρησιμοποιείτε Hewlett Packard Laserjet με όνομα εκτυπωτή `text` θα γίνονται αυτόματα οι μετατροπές από LF σε CRLF, επομένως δεν χρειάζεται να τρέξετε το script [.filename]#hpif#.
====

Επομένως, στους υπόλοιπους υπολογιστές όπου επιθυμείτε να έχετε πρόσβαση στον εκτυπωτή, απλά κάντε μια καταχώριση στο αρχείο [.filename]#/etc/printcap# με τα ακόλουθα στοιχεία:

. Ονομάστε την καταχώριση όπως επιθυμείτε: Για δική σας ευκολία πιθανώς να θέλετε να χρησιμοποιήσετε το ίδιο όνομα και τα ίδια παρωνύμια με αυτά του υπολογιστή εκτύπωσης.
. Αφήστε την ικανότητα `lp` κενή, για την ακρίβεια (`:lp=:`).
. Δημιουργήστε ένα κατάλογο spooling και προσδιορίστε την τοποθεσία του με την ικανότητα `sd`. Το LPD θα αποθηκεύει εδώ τις εργασίες πριν την αποστολή τους στον υπολογιστή εκτύπωσης.
. Τοποθετήστε το όνομα του υπολογιστή εκτύπωσης στην ικανότητα `rm`.
. Τοποθετήστε το όνομα του εκτυπωτή στην ικανότητα `rp`, στον _υπολογιστή εκτύπωσης_.

Αυτό είναι όλο. Δεν χρειάζεται να δημιουργήσετε λίστα φίλτρων μετατροπής, διαστάσεις σελίδας, ή οτιδήποτε άλλο στο αρχείο [.filename]#/etc/printcap#.

Εδώ είναι ένα παράδειγμα. Ο υπολογιστής `rose` έχει δύο εκτυπωτές, τον `bamboo` και τον `rattan`. Θέλουμε να ενεργοποιήσουμε τις εκτυπώσεις σε αυτούς τους εκτυπωτές για τους χρήστες του απομακρυσμένου υπολογιστή `orchid`. Εδώ είναι το αρχείο [.filename]#/etc/printcap# του υπολογιστή `orchid` (δείτε πιο πίσω στην ενότητα <<printing-advanced-header-pages-enabling,Ενεργοποίηση Σελίδων Κεφαλίδας>>). Ήδη έχει μια καταχώριση για τον εκτυπωτή `teak`. Εδώ προσθέσαμε τις απαραίτητες καταχωρίσεις για τους δύο εκτυπωτές του υπολογιστή `rose`:

[.programlisting]
....
#
#  /etc/printcap for host orchid - added (remote) printers on rose
#

#
#  teak is local; it is connected directly to orchid:
#
teak|hp|laserjet|Hewlett Packard LaserJet 3Si:\
        :lp=/dev/lpt0:sd=/var/spool/lpd/teak:mx#0:\
        :if=/usr/local/libexec/ifhp:\
        :vf=/usr/local/libexec/vfhp:\
        :of=/usr/local/libexec/ofhp:

#
#  rattan is connected to rose; send jobs for rattan to rose:
#
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :lp=:rm=rose:rp=rattan:sd=/var/spool/lpd/rattan:

#
#  bamboo is connected to rose as well:
#
bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :lp=:rm=rose:rp=bamboo:sd=/var/spool/lpd/bamboo:
....

Το μόνο που απομένει είναι να δημιουργήσουμε τους καταλόγους spooling στον κόμβο `orchid`:

[source,bash]
....
# mkdir -p /var/spool/lpd/rattan /var/spool/lpd/bamboo
# chmod 770 /var/spool/lpd/rattan /var/spool/lpd/bamboo
# chown daemon:daemon /var/spool/lpd/rattan /var/spool/lpd/bamboo
....

Τώρα, οι χρήστες του `orchid` μπορούν να εκτυπώνουν στον `rattan` και στον `bamboo`. Αν, για παράδειγμα, ένας χρήστης του `orchid` πληκτρολογήσει: 

[source,bash]
....
% lpr -P bamboo -d sushi-review.dvi
....
το σύστημα LPD στον `orchid` θα αντιγράψει την εργασία στον κατάλογο spooling [.filename]#/var/spool/lpd/bamboo# και θα σημειώσει πως πρόκειται για εργασία DVI. Μόλις ο υπολογιστής `rose` έχει διαθέσιμο χώρο στον κατάλογο spooling του `bamboo`, τα δύο LPDs θα μεταφέρουν το αρχείο στον `rose`. Το αρχείο θα μπει σε ουρά αναμονής στον υπολογιστή `rose` έως ότου εκτυπωθεί. Θα μετατραπεί από DVI σε PostScript(R) (αφού ο `bamboo` είναι εκτυπωτής PostScript(R)) στον υπολογιστή `rose`.

[[printing-advanced-network-net-if]]
==== Εκτυπωτές με Συνδέσεις Δικτύου

Συχνά, όταν αγοράζετε κάρτα δικτύου για εκτυπωτή, έχετε τη δυνατότητα επιλογής δύο εκδόσεων: η μία είναι προσομοίωση του spooler (η πιο ακριβή έκδοση) ενώ η άλλη απλά σας επιτρέπει να στέλνετε δεδομένα μέσω αυτής σαν να χρησιμοποιούσατε μια σειριακή ή παράλληλη θύρα (η φτηνή έκδοση). Αυτή η ενότητα περιγράφει πως να χρησιμοποιείτε την φτηνή έκδοση. Για την πιο ακριβή έκδοση μπορείτε να βρείτε περισσότερες πληροφορίες στην προηγούμενη ενότητα <<printing-advanced-network-rm,Εκτυπωτές Εγκατεστημένοι σε Απομακρυσμένους Υπολογιστές>>.

Η μορφή του αρχείου [.filename]#/etc/printcap# σας επιτρέπει να ορίσετε τη διασύνδεση - σειριακή ή παράλληλη - που θα χρησιμοποιήσετε, και (αν χρησιμοποιείτε σειριακή διασύνδεση) τον ρυθμό baud, πιθανούς ελέγχους ροής, καθυστερήσεις για tabs, μετατροπές για χαρακτήρες νέας γραμμής, και άλλα. Αλλά δεν υπάρχει τρόπος να ορίσετε μια σύνδεση σε εκτυπωτή που ακούει σε θύρα TCP/IP ή άλλο τύπο δικτύου.

Για να στείλετε δεδομένα σε ένα δικτυακό εκτυπωτή, χρειάζεται να αναπτύξετε προγράμματα επικοινωνίας που να καλούνται από φίλτρα κειμένου και φίλτρα μετατροπής. Εδώ έχουμε ένα τέτοιο παράδειγμα: το script `netprint` παίρνει όλα τα δεδομένα από το standard input και τα στέλνει σε έναν εκτυπωτή συνδεδεμένο στο δίκτυο. Ορίζουμε στο `netprint` το όνομα του εκτυπωτή ως πρώτη παράμετρο, και τον αριθμό θύρας στην οποία συνδέεται ως δεύτερη. Σημειώστε πως αυτός ο τρόπος υποστηρίζει μόνο επικοινωνία μιας κατεύθυνσης (από το FreeBSD στον εκτυπωτή). Πολλοί δικτυακοί εκτυπωτές υποστηρίζουν αμφίδρομη επικοινωνία, και είναι πολύ πιθανό να επιθυμείτε να εκμεταλλευτείτε τα προτερήματα τους (για να ελέγχετε την κατάσταση του εκτυπωτή, για καταμέτρηση εκτυπώσεων, κλπ.).

[.programlisting]
....
#!/usr/bin/perl
#
#  netprint - Text filter for printer attached to network
#  Installed in /usr/local/libexec/netprint
#
$#ARGV eq 1 || die "Usage: $0 <printer-hostname> <port-number>";

$printer_host = $ARGV[0];
$printer_port = $ARGV[1];

require 'sys/socket.ph';

($ignore, $ignore, $protocol) = getprotobyname('tcp');
($ignore, $ignore, $ignore, $ignore, $address)
    = gethostbyname($printer_host);

$sockaddr = pack('S n a4 x8', &AF_INET, $printer_port, $address);

socket(PRINTER, &PF_INET, &SOCK_STREAM, $protocol)
    || die "Can't create TCP/IP stream socket: $!";
connect(PRINTER, $sockaddr) || die "Can't contact $printer_host: $!";
while (<STDIN>) { print PRINTER; }
exit 0;
....

Μπορείτε να χρησιμοποιήσετε αυτό το script σε διάφορα φίλτρα. Ας υποθέσουμε πως έχουμε έναν εκτυπωτή γραμμής Diablo 750-N συνδεδεμένο στο δίκτυο. Ο εκτυπωτής δέχεται δεδομένα προς εκτύπωση στην θύρα 5100. Το όνομα του εκτυπωτή στο δίκτυο είναι `scrivener`. Εδώ είναι το φίλτρο κειμένου για τον εκτυπωτή:

[.programlisting]
....
#!/bin/sh
#
#  diablo-if-net - Text filter for Diablo printer `scrivener' listening
#  on port 5100.   Installed in /usr/local/libexec/diablo-if-net
#
exec /usr/libexec/lpr/lpf "$@" | /usr/local/libexec/netprint scrivener 5100
....

[[printing-advanced-restricting]]
=== Έλεγχος Πρόσβασης και Περιορισμοί στη Χρήση των Εκτυπωτών

Αυτή η ενότητα δίνει πληροφορίες για τον έλεγχο πρόσβασης και τον περιορισμό χρήσης των εκτυπωτών. Το σύστημα LPD σας επιτρέπει να ελέγχετε ποιός μπορεί να έχει πρόσβαση σε κάθε εκτυπωτή, τόσο τοπικά όσο και απομακρυσμένα, και επίσης αν μπορούν οι χρήστες να εκτυπώνουν πολλαπλά αντίγραφα, πόσο μεγάλες μπορούν να είναι οι εργασίες τους, και πόσο μεγάλες μπορούν να γίνουν οι ουρές αναμονής (print queues).

[[printing-advanced-restricting-copies]]
==== Περιορισμός Εκτύπωσης Πολλαπλών Αντιγράφων

Το σύστημα LPD διευκολύνει τους χρήστες να εκτυπώσουν πολλαπλά αντίγραφα ενός αρχείου. Οι χρήστες μπορούν να εκτυπώνουν εργασίες με `lpr -#5` (για παράδειγμα) και να παίρνουν πέντε αντίγραφα κάθε αρχείου της εργασίας εκτύπωσης. Το αν αυτό είναι καλό, εξαρτάται από εσάς.

Αν πιστεύετε πως τα πολλαπλά αντίγραφα δημιουργούν άσκοπη καταπόνηση των εκτυπωτών σας, μπορείτε να απενεργοποιήσετε την επιλογή `-#` στο man:lpr[1] προσθέτοντας την ικανότητα `sc` στο αρχείο [.filename]##/etc/printcap##. Όταν οι χρήστες αποστέλλουν εργασίες με την επιλογή `-#`, θα βλέπουν:

[source,bash]
....
lpr: multiple copies are not allowed
....

Σημειώστε πως αν έχετε ρυθμίσει πρόσβαση σε έναν εκτυπωτή απομακρυσμένα (δείτε την ενότητα <<printing-advanced-network-rm,Εκτυπωτές Εγκατεστημένοι σε Απομακρυσμένους Υπολογιστές>>), θα χρειαστεί να προσθέσετε την ικανότητα `sc` σε όλα τα απομακρυσμένα αρχεία [.filename]#/etc/printcap#, διαφορετικά οι χρήστες θα έχουν ακόμη την δυνατότητα να αποστέλλουν εργασίες πολλαπλών αντιγράφων χρησιμοποιώντας διαφορετικό κόμβο.

Εδώ είναι ένα παράδειγμα. Αυτό είναι το αρχείο [.filename]#/etc/printcap# για τον κόμβο `rose`. Ο εκτυπωτής `rattan` είναι δυνατό μηχάνημα και επιτρέπει την εκτύπωση πολλαπλών αντιγράφων, αλλά ο εκτυπωτής laser `bamboo` είναι πιο ευαίσθητο, επομένως θα απενεργοποιήσουμε τη δυνατότητα πολλαπλών αντιγράφων προσθέτοντας την ικανότητα `sc`:

[.programlisting]
....
#
#  /etc/printcap for host rose - restrict multiple copies on bamboo
#
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :sh:sd=/var/spool/lpd/rattan:\
        :lp=/dev/lpt0:\
        :if=/usr/local/libexec/if-simple:

bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:sd=/var/spool/lpd/bamboo:sc:\
        :lp=/dev/ttyu5:ms#-parenb cs8 clocal crtscts:rw:\
        :if=/usr/local/libexec/psif:\
        :df=/usr/local/libexec/psdf:
....

Τώρα, θα χρειαστεί να προσθέσουμε επίσης την ικανότητα `sc` στο αρχείο [.filename]#/etc/printcap# του κόμβου `orchid` (και ενώ βρισκόμαστε σε αυτό, επιτρέψτε μας να απενεργοποιήσουμε τα πολλαπλά αντίγραφα για τον εκτυπωτή `teak`):

[.programlisting]
....
#
#  /etc/printcap for host orchid - no multiple copies for local
#  printer teak or remote printer bamboo
teak|hp|laserjet|Hewlett Packard LaserJet 3Si:\
        :lp=/dev/lpt0:sd=/var/spool/lpd/teak:mx#0:sc:\
        :if=/usr/local/libexec/ifhp:\
        :vf=/usr/local/libexec/vfhp:\
        :of=/usr/local/libexec/ofhp:

rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :lp=:rm=rose:rp=rattan:sd=/var/spool/lpd/rattan:

bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :lp=:rm=rose:rp=bamboo:sd=/var/spool/lpd/bamboo:sc:
....

Χρησιμοποιώντας την ικανότητα `sc`, προλαμβάνουμε την χρήση των εντολών `lpr -#`, αλλά δεν έχουμε ακόμη την δυνατότητα να παρεμποδίσουμε τους χρήστες να τρέξουν την εντολή man:lpr[1] πολλές φορές, ή να αποστείλουν το ίδιο αρχείο πολλές φορές σε μία μοναδική εργασία, όπως εδώ:

[source,bash]
....
% lpr forsale.sign forsale.sign forsale.sign forsale.sign forsale.sign
....

Υπάρχουν πολλοί τρόποι πρόληψης αυτών των ενεργειών (συμπεριλαμβάνοντας και την περίπτωση να το αγνοήσετε) που είστε ελεύθεροι να εξερευνήσετε.

[[printing-advanced-restricting-access]]
==== Περιορίζοντας την Πρόσβαση σε Εκτυπωτές

Μπορείτε να ελέγχετε ποιός μπορεί να εκτυπώνει σε ποιόν εκτυπωτή χρησιμοποιώντας τους μηχανισμούς ομάδων (groups) του UNIX(R) και την ικανότητα `rg` στο [.filename]#/etc/printcap#. Απλά τοποθετήστε τους χρήστες που θέλετε να έχουν πρόσβαση σε κάποιον εκτυπωτή σε μια συγκεκριμένη ομάδα (χρηστών), και δηλώστε αυτή την ομάδα στην ικανότητα `rg`.

Όλοι οι χρήστες που δεν ανήκουν στην ομάδα (συμπεριλαμβανομένου και του `root`) θα δέχονται το ακόλουθο μήνυμα: `lpr: Not a member of the restricted group` όταν προσπαθούν να εκτυπώσουν στον ελεγχόμενο εκτυπωτή.

Όπως και με την ικανότητα `sc` (περιορισμού πολλαπλών αντιγράφων), θα χρειαστεί να προσδιορίσετε την `rg` στους απομακρυσμένους κόμβους που θα έχουν πρόσβαση στους εκτυπωτές σας, αν νομίζετε πως αυτό είναι σωστό (δείτε την ενότητα <<printing-advanced-network-rm,Εκτυπωτές Εγκατεστημένοι σε Απομακρυσμένους Υπολογιστές>>).

Για παράδειγμα, θα αφήσουμε για όλους ελεύθερη την πρόσβαση στον εκτυπωτή `rattan`, αλλά μόνο οι χρήστες της ομάδας `artists` θα μπορούν να χρησιμοποιήσουν τον `bamboo`. Εδώ είναι το γνωστό μας [.filename]#/etc/printcap# για τον κόμβο `rose`:

[.programlisting]
....
#
#  /etc/printcap for host rose - restricted group for bamboo
#
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :sh:sd=/var/spool/lpd/rattan:\
        :lp=/dev/lpt0:\
        :if=/usr/local/libexec/if-simple:

bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:sd=/var/spool/lpd/bamboo:sc:rg=artists:\
        :lp=/dev/ttyu5:ms#-parenb cs8 clocal crtscts:rw:\
        :if=/usr/local/libexec/psif:\
        :df=/usr/local/libexec/psdf:
....

Επιτρέψτε μας να μην αλλάξουμε το αρχείο [.filename]#/etc/printcap# από το άλλο παράδειγμα (για τον υπολογιστή `orchid`). Φυσικά, οποιοσδήποτε χρήστης του `orchid` μπορεί να εκτυπώσει στον `bamboo`. Ίσως όμως να επιτρέπουμε μόνον σε συγκεκριμένους χρήστες την πρόσβαση στον υπολογιστή `orchid`, και θέλουμε αυτοί οι χρήστες να έχουν πρόσβαση στον εκτυπωτή. Ή ίσως πάλι, και όχι.

[NOTE]
====
Επιτρέπεται μόνο μια περιορισμένη ομάδα ανά εκτυπωτή.
====

[[printing-advanced-restricting-sizes]]
==== Έλεγχος Μεγέθους των Απεσταλμένων Εργασιών

Αν πολλοί χρήστες έχουν πρόσβαση στους εκτυπωτές σας, πιθανώς να χρειάζεται να θέσετε ένα ανώτατο όριο στο επιτρεπόμενο μέγεθος αρχείων που μπορούν να αποστείλουν οι χρήστες για εκτύπωση. Ακόμα και αν υπάρχει αρκετός χώρος στο σύστημα αρχείων που φιλοξενεί τους καταλόγους spool, θα πρέπει ωστόσο να βεβαιωθείτε ότι επαρκεί για τις εργασίες όλων των χρηστών.

Το LPD σας επιτρέπει να οριοθετήσετε το μέγιστο αριθμό bytes που περιέχει μια εργασία, με την ικανότητα `mx`. Η μονάδα μέτρησης είναι σε `BUFSIZ` blocks, τα οποία είναι 1024 bytes. Αν θέσετε μηδέν σε αυτή την ικανότητα, δεν θα υπάρχουν όρια στο μέγεθος των αρχείων. Ωστόσο, αν δεν έχει οριστεί η ικανότητα `mx`, τότε θα χρησιμοποιείται η προεπιλεγμένη τιμή των 1000 blocks.

[NOTE]
====
Το όριο εφαρμόζεται στα _αρχεία_ μιας εργασίας, και _όχι_ στο συνολικό μέγεθος της εργασίας.
====

Το LPD δεν θα απορρίψει ένα αρχείο που ξεπερνά το όριο μεγέθους που έχετε θέσει. Αντιθέτως, θα το τοποθετήσει στην ουρά αναμονής με μέγεθος ίσο με το μέγιστο επιτρεπτό, το οποίο και θα εκτυπώσει τελικά. Το υπόλοιπο αρχείο απορρίπτεται. Αν αυτός είναι σωστός ή λανθασμένος τρόπος αντιμετώπισης για την υπέρβαση του ορίου, είναι θέμα προς συζήτηση.

Ας οριοθετήσουμε στο παράδειγμα μας τους εκτυπωτές `rattan` και `bamboo`. Επειδή τα αρχεία PostScript(R) των `artists` τείνουν προς μεγάλα μεγέθη, θα θέσουμε ένα όριο πέντε megabytes. Δεν θα θέσουμε όρια για τον εκτυπωτή γραμμής απλού κειμένου:

[.programlisting]
....
#
#  /etc/printcap for host rose
#

#
#  No limit on job size:
#
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :sh:mx#0:sd=/var/spool/lpd/rattan:\
        :lp=/dev/lpt0:\
        :if=/usr/local/libexec/if-simple:

#
#  Limit of five megabytes:
#
bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:sd=/var/spool/lpd/bamboo:sc:rg=artists:mx#5000:\
        :lp=/dev/ttyu5:ms#-parenb cs8 clocal crtscts:rw:\
        :if=/usr/local/libexec/psif:\
        :df=/usr/local/libexec/psdf:
....

Και πάλι, τα όρια εφαρμόζονται μόνο για τους τοπικούς χρήστες. Αν έχετε ενεργοποιήσει απομακρυσμένη πρόσβαση για τους εκτυπωτές σας, τα όρια αυτά δεν ισχύουν για τους απομακρυσμένους χρήστες. Θα χρειαστεί να προσδιορίσετε με την ικανότητα `mx` και τα απομακρυσμένα αρχεία [.filename]#/etc/printcap#. Δείτε την ενότητα <<printing-advanced-network-rm,Εκτυπωτές Εγκατεστημένοι σε Απομακρυσμένους Υπολογιστές>> για περισσότερες πληροφορίες σχετικά με τις εκτυπώσεις από απομακρυσμένους υπολογιστές.

Υπάρχει και άλλος εξειδικευμένος τρόπος περιορισμού του μεγέθους εργασιών για απομακρυσμένους εκτυπωτές. Δείτε την ενότητα <<printing-advanced-restricting-remote,Περιορισμός Εργασιών από Απομακρυσμένους Υπολογιστές>>.

[[printing-advanced-restricting-remote]]
==== Περιορισμός Εργασιών από Απομακρυσμένους Υπολογιστές

Το σύστημα παροχέτευσης LPD παρέχει διάφορους τρόπους περιορισμού των εργασιών από απομακρυσμένους υπολογιστές:

Παρεμπόδιση υπολογιστών::
Μπορείτε να ελέγχετε από ποιους απομακρυσμένους υπολογιστές θα δέχεται αιτήσεις εκτύπωσης το τοπικό LPD, χρησιμοποιώντας τα αρχεία [.filename]#/etc/hosts.equiv# και [.filename]#/etc/hosts.lpd#. Το LPD ελέγχει να δει αν η εισερχόμενη αίτηση προέρχεται από έναν υπολογιστή που αναφέρεται σε κάποιο από τα δύο αρχεία. Αν όχι, το LPD απορρίπτει την αίτηση.
+
Η μορφή αυτών των αρχείων είναι απλή: ένα όνομα υπολογιστή ανά γραμμή. Παρατηρήστε πως το αρχείο [.filename]#/etc/hosts.equiv# χρησιμοποιείται και από το πρωτόκολλο man:ruserok[3], και επηρεάζει προγράμματα όπως το man:rsh[1] και το man:rcp[1], επομένως να είστε προσεκτικοί.
+
Για παράδειγμα, εδώ είναι το αρχείο [.filename]#/etc/hosts.lpd# στον υπολογιστή `rose`:
+
[.programlisting]
....
orchid
violet
madrigal.fishbaum.de
....
+
Αυτό σημαίνει πως ο `rose` δέχεται αιτήσεις από τους υπολογιστές `orchid`, `violet`, και `madrigal.fishbaum.de`. Αν κάποιος άλλος υπολογιστής προσπαθήσει να αποκτήσει πρόσβαση στο LPD του `rose`, η εργασία θα απορριφθεί.

Περιορισμοί στο Μέγεθος::
Μπορείτε να ελέγχετε πόσος ελεύθερος χώρος πρέπει να απομένει στο σύστημα αρχείων όπου βρίσκεται ο κατάλογος spool. Δημιουργήστε ένα αρχείο με όνομα [.filename]#minfree# στον κατάλογο spool για τον τοπικό εκτυπωτή. Εισάγετε σε αυτό το αρχείο έναν αριθμό που αντιπροσωπεύει πόσα blocks δίσκου (512 bytes) ελεύθερου χώρου πρέπει να υπάρχουν για να είναι δεκτή μια απομακρυσμένη εργασία.
+
Αυτό σας επιτρέπει να είστε βέβαιοι πως οι απομακρυσμένοι χρήστες δεν θα γεμίσουν το σύστημα αρχείων σας. Μπορείτε επίσης να το χρησιμοποιήσετε για να δώσετε μερική προτεραιότητα στους τοπικούς χρήστες: οι τοπικοί χρήστες θα μπορούν να στέλνουν εργασίες στην ουρά αναμονής ακόμη και όταν ο ελεύθερος χώρος του δίσκου έχει πέσει κάτω από τον αριθμό που αναφέρεται στο αρχείο [.filename]#minfree#.
+
Για παράδειγμα, ας προσθέσουμε ένα αρχείο [.filename]#minfree# για τον εκτυπωτή `bamboo`. Εξετάζουμε το [.filename]#/etc/printcap# για να βρούμε τον κατάλογο spool για αυτόν τον εκτυπωτή. Εδώ είναι η καταχώριση για τον `bamboo`:
+
[.programlisting]
....
bamboo|ps|PS|S|panasonic|Panasonic KX-P4455 PostScript v51.4:\
        :sh:sd=/var/spool/lpd/bamboo:sc:rg=artists:mx#5000:\
        :lp=/dev/ttyu5:ms#-parenb cs8 clocal crtscts:rw:mx#5000:\
        :if=/usr/local/libexec/psif:\
        :df=/usr/local/libexec/psdf:
....
+
Ο κατάλογος spool καθορίζεται στην ικανότητα `sd`. Θα θέσουμε τρία megabytes (ισοδυναμεί με 6144 disk blocks) ως το μέγεθος του ελεύθερου χώρου που πρέπει να υπάρχει στο σύστημα αρχείων, ώστε το LPD να δέχεται απομακρυσμένες εργασίες:
+
[source,bash]
....
# echo 6144 > /var/spool/lpd/bamboo/minfree
....

Περιορισμοί χρηστών::
Μπορείτε να ελέγχετε ποιός απομακρυσμένος χρήστης μπορεί να εκτυπώνει στους τοπικούς εκτυπωτές ορίζοντας την ικανότητα `rs` στο [.filename]#/etc/printcap#. Όταν εμφανίζεται η `rs` σε μια καταχώριση κάποιου τοπικά συνδεδεμένου εκτυπωτή, το LPD θα δεχθεί εργασίες από απομακρυσμένους υπολογιστές _αν_ ο χρήστης που αποστέλλει την εργασία έχει λογαριασμό στον τοπικό υπολογιστή και με το ίδιο όνομα χρήστη. Διαφορετικά, το LPD θα απορρίψει την εργασία.
+
Αυτή η ικανότητα είναι ιδιαίτερα χρήσιμη σε περιβάλλοντα όπου υπάρχουν (για παράδειγμα) διαφορετικά επιχειρησιακά τμήματα που μοιράζονται το δίκτυο, και κάποιοι χρήστες πρέπει να υπερβαίνουν τα σύνορα του τμήματος. Δημιουργώντας λογαριασμούς στα συστήματα σας, θα μπορούν να χρησιμοποιούν τους εκτυπωτές σας από το δικό τους τμήμα της επιχείρησης. Αν επιθυμείτε να τους επιτρέπετε να χρησιμοποιούν _μόνο_ τους εκτυπωτές και όχι τα μηχανήματα σας, τότε μπορείτε να δημιουργήσετε λογαριασμούς "token", δίχως προσωπικούς καταλόγους και με κέλυφος που δεν μπορεί να χρησιμοποιηθεί, όπως το [.filename]#/usr/bin/false#.

[[printing-advanced-acct]]
=== Καταμέτρηση Χρήσης Εκτυπωτών

Αποφασίσατε ότι χρειάζεται να χρεώνετε για τις εκτυπώσεις σας. Και γιατί όχι; Το χαρτί και το μελάνι κοστίζουν χρήματα. Και επιπλέον υπάρχει κόστος συντήρησης - οι εκτυπωτές αποτελούνται από κινητά μέρη και έχουν την τάση να χαλάνε. Έχετε εξετάσει τους εκτυπωτές σας, τον τρόπο που χρησιμοποιούνται, και το κόστος συντήρησης και έχετε υπολογίσει μια χρέωση ανά σελίδα (ή ανά μέτρο, ανά πόδι, ή άλλη μονάδα μέτρησης). Το θέμα είναι τώρα πως μπορείτε πραγματικά να ξεκινήσετε να καταμετράτε τις εκτυπώσεις σας.

Τα άσχημα νέα είναι πως το σύστημα παροχέτευσης του LPD δεν παρέχει πολύ βοήθεια σε αυτόν τον τομέα. Η καταμέτρηση εξαρτάται σε μεγάλο βαθμό από τον τύπο του εκτυπωτή που χρησιμοποιείτε, τους τύπους αρχείων που εκτυπώνετε, και τις _δικές σας_ απαιτήσεις για την χρέωση των εκτυπώσεων.

Για την καταμέτρηση, θα πρέπει να μετατρέψετε το φίλτρο κειμένου (για τη χρέωση εργασιών απλού κειμένου) του εκτυπωτή και τα φίλτρα μετατροπής (για τη χρέωση όλων των άλλων τύπων αρχείων) ώστε να μετρούν σελίδες ή να ζητούν να μάθουν από τον εκτυπωτή τον αριθμό των εκτυπωμένων σελίδων. Δεν θα σας βοηθήσει ιδιαίτερα η χρήση φίλτρου εξόδου, από τη στιγμή που δεν μπορεί να κάνει καταμέτρηση. Δείτε την ενότητα <<printing-advanced-filter-intro,Φίλτρα>>.

Γενικά, υπάρχουν δύο τρόποι για να κάνετε καταμέτρηση:

* Η _Περιοδική καταμέτρηση_ είναι ο πιο συνηθισμένος τρόπος, πιθανώς γιατί είναι ο ευκολότερος. Κάθε φορά που κάποιος εκτυπώνει μια εργασία, το φίλτρο δημιουργεί ένα αρχείο καταγραφής όπου αναφέρει τον χρήστη, τον υπολογιστή, και τον αριθμό των σελίδων. Κάθε μήνα, εξάμηνο, χρόνο, ή άλλη χρονική περίοδο της αρεσκείας σας, συλλέγετε τα αρχεία καταγραφής για τους διάφορους εκτυπωτές, λογαριάζετε τις σελίδες που αναλογούν στους χρήστες, και χρεώνετε αναλόγως. Έπειτα σβήνετε τα στοιχεία από τα αρχεία καταγραφής, ξεκινώντας από καθαρή κατάσταση για την επόμενη περίοδο.
* Η _Καταμέτρηση κατά τη χρήση_ είναι λιγότερο γνωστή, ίσως επειδή είναι πιο δύσκολος τρόπος. Σε αυτή τη μέθοδο τα φίλτρα χρεώνουν τους χρήστες για τις εκτυπώσεις τους αμέσως μόλις αυτές πραγματοποιηθούν. Όπως και με την καταγραφή χρήσης δίσκου (disk quotas), η καταμέτρηση είναι άμεση. Μπορείτε να προλαμβάνετε την χρήση εκτυπωτών από χρήστες που έχουν χτυπήσει κόκκινο, και μπορείτε να παρέχετε στους χρήστες ένα τρόπο για να ελέγχουν και να ρυθμίζουν τον "όγκο εκτυπώσεων (print quotas)." Αλλά αυτή η μέθοδος προϋποθέτει λίγο κώδικα βάσεων δεδομένων για την καταγραφή χρηστών και των εν λόγω μεγεθών.

Το σύστημα παροχέτευσης LPD υποστηρίζει εύκολα και τις δύο μεθόδους: από τη στιγμή που πρέπει εσείς να παρέχετε τα φίλτρα (τις περισσότερες φορές), θα πρέπει επίσης να παρέχετε και τον κώδικα καταμέτρησης. Αλλά υπάρχει και ένα καλό σε αυτή την υπόθεση: έχετε απεριόριστη ευελιξία στις μεθόδους καταμέτρησης. Για παράδειγμα, μπορείτε να επιλέξετε περιοδική ή κατά τη χρήση καταμέτρηση. Μπορείτε να επιλέξετε τις πληροφορίες που θα καταγράφονται: ονόματα χρηστών, ονόματα υπολογιστών, τύπους εργασιών, τυπωμένες σελίδες, τετραγωνικά μέτρα χαρτιού που χρησιμοποιήθηκε, πόσος χρόνος χρειάστηκε για να γίνει η εκτύπωση, και πολλά ακόμα. Και όλα αυτά γίνονται μετατρέποντας τα φίλτρα για να αποθηκεύουν αυτές τις πληροφορίες.

==== Γρήγορη και Πρόχειρη Καταμέτρηση Εκτυπώσεων

Το FreeBSD διατίθεται με δύο προγράμματα που μπορούν να παρέχουν άμεσα απλή περιοδική καταμέτρηση. Είναι το φίλτρο κειμένου `lpf`, που περιγράφεται στην ενότητα <<printing-advanced-lpf,lpf: ένα Φίλτρο Κειμένου>>, και το man:pac[8], ένα πρόγραμμα που συλλέγει και αθροίζει καταχωρίσεις από αρχεία καταμετρήσεων.

Όπως αναφέραμε στην ενότητα των φίλτρων (<<printing-advanced-filters,Φίλτρα>>), το LPD ξεκινά τα φίλτρα κειμένου και μετατροπής περνώντας στην γραμμή εντολών του φίλτρου και το όνομα του αρχείου καταγραφής. Τα φίλτρα μπορούν να χρησιμοποιήσουν αυτή την παράμετρο για να ξέρουν που να γράφουν τις καταχωρίσεις καταμέτρησης. Το όνομα του αρχείου καταμέτρησης φαίνεται στην ικανότητα `af` στο [.filename]#/etc/printcap#, και αν δεν ορίζεται η πλήρης διαδρομή του, χρησιμοποιείται η σχετική διαδρομή ως προς τον κατάλογο spool.

Το LPD ξεκινά το `lpf` με παραμέτρους πλάτους και μήκους σελίδας (από τις ικανότητες `pw` και `pl`). Το `lpf` χρησιμοποιεί αυτές τις παραμέτρους για να προσδιορίσει την ποσότητα χαρτιού που χρησιμοποιήθηκε. Μετά την αποστολή του αρχείου στον εκτυπωτή, γράφει μια καταχώριση καταμέτρησης στο αρχείο καταγραφής. Οι καταχωρίσεις μοιάζουν με τις παρακάτω:

[.programlisting]
....
2.00 rose:andy
3.00 rose:kelly
3.00 orchid:mary
5.00 orchid:mary
2.00 orchid:zhang
....

Θα πρέπει να χρησιμοποιείτε ξεχωριστό αρχείο καταγραφής για κάθε εκτυπωτή, αφού το `lpf` δεν έχει ενσωματωμένη δυνατότητα κλειδώματος αρχείου (file locking), και δύο `lpf` μπορούν να καταστρέψουν το ένα την καταχώριση του άλλου αν πρόκειται να γράψουν ταυτόχρονα στο ίδιο αρχείο. Ένας εύκολος τρόπος για να βεβαιώσετε την μοναδικότητα αρχείου καταγραφής ανά εκτυπωτή είναι να χρησιμοποιήσετε την ικανότητα `af=acct` στο [.filename]#/etc/printcap#. Έτσι, κάθε αρχείο καταγραφής θα βρίσκεται στον κατάλογο spool του αντίστοιχου εκτυπωτή, σε ένα αρχείο με όνομα [.filename]#acct#.

Όταν είστε έτοιμοι να χρεώσετε τους χρήστες για τις εκτυπώσεις, εκτελέστε το πρόγραμμα man:pac[8]. Απλά μεταβείτε στον κατάλογο spool για τον εκτυπωτή που κάνετε καταμέτρηση και πληκτρολογήστε `pac`. Θα εμφανιστεί ένας απολογισμός με χρεώσεις σε δολάρια, όπως βλέπετε στη συνέχεια:

[source,bash]
....
  Login               pages/feet   runs    price
orchid:kelly                5.00    1   $  0.10
orchid:mary                31.00    3   $  0.62
orchid:zhang                9.00    1   $  0.18
rose:andy                   2.00    1   $  0.04
rose:kelly                177.00  104   $  3.54
rose:mary                  87.00   32   $  1.74
rose:root                  26.00   12   $  0.52

total                     337.00  154   $  6.74
....

Παρακάτω είναι οι παράμετροι που δέχεται το man:pac[8]:

`-P__printer__`::
Για ποιό _printer_ να κάνει απολογισμό. Αυτή η επιλογή δουλεύει μόνο αν υπάρχει η πλήρης διαδρομή στην ικανότητα `af` στο [.filename]#/etc/printcap#.

`-c`::
Ταξινομεί το αποτέλεσμα ανά κόστος αντί της αλφαβητικής ταξινόμησης των χρηστών.

`-m`::
Αγνοεί το όνομα του υπολογιστή στα αρχεία καταγραφής. Με αυτή την επιλογή, ο χρήστης `smith` στον υπολογιστή `alpha` είναι ο ίδιος χρήστης με τον `smith` στον υπολογιστή `gamma`. Χωρίς την επιλογή αυτή, είναι διαφορετικοί χρήστες.

`-p__price__`::
Υπολογίζει τις χρεώσεις με _price_ (τιμή) σε δολάρια ανά σελίδα ή ανά πόδι αντί για την τιμή από την ικανότητα `pc` στο [.filename]#/etc/printcap#, ή αλλιώς δύο σεντς (από προεπιλογή). Μπορείτε να ορίσετε ως _price_ μια τιμή με δεκαδικά ψηφία (floating point).

`-r`::
Αντιστρέφει την σειρά ταξινόμησης.

`-s`::
Δημιουργεί ένα αρχείο απολογισμού των καταμετρήσεων και καθαρίζει τα περιεχόμενα των αρχείων καταγραφής.

__name...__::
Τυπώνει πληροφορίες αναφοράς μόνο για τα συγκεκριμένα _name_ (ονόματα) χρηστών.

Στον προεπιλεγμένο απολογισμό που παράγει το man:pac[8], βλέπετε των αριθμό των τυπωμένων σελίδων ανά χρήστη από τους διάφορους υπολογιστές. Αν, στο χώρο σας, ο υπολογιστής δεν έχει σημασία (γιατί οι χρήστες μπορούν να χρησιμοποιήσουν οποιονδήποτε θέλουν), εκτελέστε την εντολή `pac -m`, για να δημιουργήσετε τον ακόλουθο απολογισμό:

[source,bash]
....
  Login               pages/feet   runs    price
andy                        2.00    1   $  0.04
kelly                     182.00  105   $  3.64
mary                      118.00   35   $  2.36
root                       26.00   12   $  0.52
zhang                       9.00    1   $  0.18

total                     337.00  154   $  6.74
....

Για τον ορισμό ποσοστού χρέωσης σε δολάρια, το man:pac[8] χρησιμοποιεί την ικανότητα `pc` στο αρχείο [.filename]#/etc/printcap# (προεπιλεγμένη τιμή 200, ή 2 σεντς ανά σελίδα). Προσδιορίστε σε αυτήν την ικανότητα, σε εκατοστά του σεντ, την τιμή ανά σελίδα ή ανά πόδι που θέλετε να χρεώνετε για τις εκτυπώσεις. Μπορείτε να προσπεράσετε αυτή την τιμή όταν τρέχετε το man:pac[8] με την επιλογή `-p`. H μονάδα μέτρησης για την επιλογή `-p` είναι σε δολάρια, όχι σε εκατοστά του σεντ. Για παράδειγμα, 

[source,bash]
....
# pac -p1.50
....
 ορίζει κόστος κάθε σελίδας ένα δολάριο και πενήντα σεντς. Μπορείτε πραγματικά να έχετε πολλά έσοδα χρησιμοποιώντας αυτές τις χρεώσεις.

Τέλος, εκτελώντας `pac -s` θα αποθηκεύσετε τις πληροφορίες του απολογισμού σε ένα αρχείο καταγραφής απολογισμού, που θα έχει το ίδιο όνομα με το αρχείο καταγραφής του εκτυπωτή, αλλά με κατάληξη `_sum`. Έπειτα καθαρίζεται το αρχείο καταγραφής. Όταν εκτελέσετε πάλι το man:pac[8], θα ξαναδιαβάσει το αρχείο απολογισμού, για να πάρει τα αρχικά σύνολα, και θα προσθέσει τις πληροφορίες από το κανονικό αρχείο καταγραφής.

==== Πως Μπορείτε να Μετρήσετε τις Τυπωμένες Σελίδες;

Για να μετρήσετε τις τυπωμένες σελίδες με έστω στοιχειώδη λεπτομέρεια, θα πρέπει να προσδιορίσετε πόσο χαρτί χρειάζεται μια εργασία. Αυτό είναι το ουσιαστικότερο πρόβλημα στην καταμέτρηση εκτυπώσεων.

Για εργασίες απλού κειμένου, το πρόβλημα δεν είναι δύσκολο να λυθεί: Μετράτε πόσες γραμμές υπάρχουν σε μια εργασία και τις συγκρίνετε με πόσες γραμμές μπορεί να τυπώσει ο εκτυπωτής σας σε μια σελίδα. Μην ξεχάσετε να συμπεριλάβετε τα backspaces που προκαλούν υπερτύπωση, ή επιμήκης λογικές γραμμές που αναδιπλώνονται σε περισσότερες από μία φυσικές γραμμές.

Το φίλτρο κειμένου `lpf` (που παρουσιάσαμε στο <<printing-advanced-lpf,lpf: ένα Φίλτρο Κειμένου>>) λαμβάνει υπόψιν του αυτά τα στοιχεία όταν κάνει καταμέτρηση. Αν γράφετε κάποιο φίλτρο κειμένου που χρειάζεται να κάνει καταμέτρηση, ίσως να θέλετε να ελέγξετε τον πηγαίο κώδικα του `lpf`.

Πως χειρίζεστε όμως τους υπόλοιπους τύπους αρχείων;

Για τις μετατροπές από DVI-σε-LaserJet ή από DVI-σε-PostScript(R), μπορείτε να κάνετε το φίλτρο σας να αναλύει την έξοδο του `dvilj` ή του `dvips` και να ελέγχει πόσες σελίδες δημιουργήθηκαν από τη μετατροπή. Ίσως μπορέσετε να κάνετε κάτι παρόμοιο και με διαφορετικούς τύπους αρχείων και προγράμματα μετατροπής

Ωστόσο, όλες αυτές οι μέθοδοι έχουν το μειονέκτημα πως ο εκτυπωτής πιθανώς στην πραγματικότητα να μην εκτυπώσει όλες τις σελίδες. Για παράδειγμα, θα μπορούσε να μπλοκαριστεί το χαρτί, ή να τελειώσει το τόνερ, ή ακόμη να συμβεί και έκρηξη -ενώ ο χρήστης θα συνεχίσει να χρεώνεται.

Τι θα μπορούσατε να κάνετε;

Υπάρχει μόνο ένας _σίγουρος_ τρόπος για να κάνετε καταμέτρηση _ακριβείας_. Να πάρετε έναν εκτυπωτή που να μπορεί να σας πει πόσο χαρτί χρησιμοποιεί, και να τον συνδέσετε μέσω σειριακής θύρας ή μέσω δικτύου. Σχεδόν όλοι οι εκτυπωτές PostScript(R) υποστηρίζουν αυτή την δυνατότητα. Θα βρείτε και άλλους τύπους και κατασκευαστές που κάνουν επίσης το ίδιο (για παράδειγμα, οι laser εκτυπωτές δικτύου της Imagen). Μετατρέψτε τα φίλτρα για αυτούς τους εκτυπωτές ώστε να καταγράφουν τις τυπωμένες σελίδες μετά την ολοκλήρωση της εκάστοτε εργασίας εκτύπωσης, και ρυθμίστε τους να κρατούν αρχεία καταγραφής με _μόνο_ αυτή την πληροφορία. Δεν χρειάζεται καταμέτρηση γραμμών ούτε αναφορά σφαλμάτων.

Φυσικά, πάντα έχετε τη δυνατότητα να φανείτε γενναιόδωρος και να παρέχετε τις εκτυπώσεις σας δωρεάν.

[[printing-using]]
== Χρήση Εκτυπωτών

Αυτή η ενότητα περιγράφει πως να χρησιμοποιείτε τους εκτυπωτές που έχετε εγκαταστήσει στο FreeBSD. Οι βασικές εντολές για τον τελικό χρήστη είναι οι ακόλουθες:

man:lpr[1]::
Εκτύπωση εργασιών

man:lpq[1]::
Έλεγχος ουράς αναμονής (print queue) του εκτυπωτή

man:lprm[1]::
Διαγραφή εργασιών από την ουρά αναμονής

Υπάρχει επίσης μια εντολή για τους διαχειριστές, η man:lpc[8], που περιγράφεται στην ενότητα <<printing-lpc,Διαχείριση Εκτυπωτών>>, και χρησιμοποιείται για να ελέγχει τους εκτυπωτές και τις ουρές αναμονής.

Και οι τρεις εντολές man:lpr[1], man:lprm[1], και man:lpq[1] δέχονται την επιλογή `-P _printer-name_` με την οποία καθορίζεται σε ποιον εκτυπωτή ή ουρά αναμονής θα ενεργήσουν, όπως αναφέρεται στο αρχείο [.filename]#/etc/printcap#. Αυτό σας επιτρέπει να αποστείλετε, να διαγράψετε, και να ελέγξετε εργασίες σε διάφορους εκτυπωτές. Αν δεν χρησιμοποιείτε την επιλογή `-P`, τότε οι εντολές χρησιμοποιούν τον εκτυπωτή που αναφέρεται στη μεταβλητή περιβάλλοντος `PRINTER`. Τέλος, αν δεν έχετε θέσει μια μεταβλητή περιβάλλοντος `PRINTER`, οι εντολές εκτελούνται με τον προεπιλεγμένο εκτυπωτή που ονομάζεται `lp`.

Από δω και στο εξής, με την ορολογία _προεπιλεγμένος εκτυπωτής_ θα εννοούμε τον εκτυπωτή που αναφέρεται στην μεταβλητή περιβάλλοντος `PRINTER`, ή αν δεν υπάρχει, τον εκτυπωτή με το όνομα `lp`.

[[printing-lpr]]
=== Εκτύπωση Εργασιών

Για να εκτυπώσετε αρχεία, πληκτρολογήστε:

[source,bash]
....
% lpr filename ...
....

Θα εκτυπωθούν όλα τα αναφερόμενα αρχεία στον προεπιλεγμένο εκτυπωτή. Αν δεν αναφέρετε αρχεία, το man:lpr[1] διαβάζει δεδομένα από το standard input. Για παράδειγμα, αυτή η εντολή θα εκτυπώσει μερικά σημαντικά αρχεία του συστήματος:

[source,bash]
....
% lpr /etc/host.conf /etc/hosts.equiv
....

Για να επιλέξετε ένα συγκεκριμένο εκτυπωτή, πληκτρολογήστε:

[source,bash]
....
% lpr -P printer-name filename ...
....

Στο παράδειγμα μας θα εκτυπωθεί μια μεγάλη λίστα αρχείων του τρέχοντος καταλόγου στον εκτυπωτή που ονομάζεται `rattan`:

[source,bash]
....
% ls -l | lpr -P rattan
....

Αφού δεν αναφέρονται ονόματα αρχείων στην εντολή man:lpr[1], το `lpr` διαβάζει τα δεδομένα που θα εκτυπώσει από το standard input, τα οποία είναι η έξοδος της εντολής `ls -l`.

Η εντολή man:lpr[1] μπορεί να δεχθεί ένα μεγάλο αριθμό επιλογών για να ελέγχει την μορφοποίηση, να μετατρέπει αρχεία, να δημιουργεί πολλαπλά αντίγραφα, κ.λ.π. Για περισσότερες πληροφορίες, δείτε την ενότητα <<printing-lpr-options,Επιλογές Εκτύπωσης>>.

[[printing-lpq]]
=== Έλεγχος Εργασιών

Όταν εκτυπώνετε με το man:lpr[1], τα δεδομένα που θέλετε να εκτυπώσετε τοποθετούνται σε ένα πακέτο (package) που ονομάζεται "εργασία εκτύπωσης (print job)", η οποία αποστέλλεται στο σύστημα παροχέτευσης LPD. Κάθε εκτυπωτής έχει μια ουρά αναμονής εργασιών, και η εργασία σας αναμένει μαζί με άλλες δικές σας και άλλων χρηστών. Ο εκτυπωτής τις εκτυπώνει με την σειρά άφιξης στην ουρά αναμονής.

Για να εμφανίσετε την ουρά αναμονής για τον προεπιλεγμένο εκτυπωτή, πληκτρολογήστε man:lpq[1]. Για κάποιον συγκεκριμένο εκτυπωτή, χρησιμοποιήστε την επιλογή `-P`. Για παράδειγμα, η εντολή: 

[source,bash]
....
% lpq -P bamboo
....

εμφανίζει την ουρά αναμονής για τον εκτυπωτή με το όνομα `bamboo`. Ακολουθεί ένα παράδειγμα εξόδου της εντολής `lpq`:

[source,bash]
....
bamboo is ready and printing
Rank   Owner    Job  Files                              Total Size
active kelly    9    /etc/host.conf, /etc/hosts.equiv   88 bytes
2nd    kelly    10   (standard input)                   1635 bytes
3rd    mary     11   ...                                78519 bytes
....

Εμφανίζονται τρεις εργασίες στη λίστα αναμονής για τον `bamboo`. Στην πρώτη εργασία, που έχει σταλεί από τον χρήστη kelly, έχει αποδοθεί ο "αριθμός εργασίας (job number)" 9. Κάθε εργασία ενός εκτυπωτή χαρακτηρίζεται από ένα μοναδικό τέτοιο αριθμό. Τις περισσότερες φορές μπορείτε να τον αγνοήσετε, αλλά θα τον χρειαστείτε αν θέλετε να διαγράψετε κάποια εργασία. Δείτε την ενότητα <<printing-lprm,Διαγραφή Εργασιών>> για περισσότερες πληροφορίες.

Η εργασία με το νούμερο εννέα αποτελείται από δύο αρχεία. Τα πολλαπλά αρχεία που δόθηκαν στη γραμμή εντολών του man:lpr[1] θεωρούνται μέρος μίας μόνο εργασίας. Αυτή είναι και η τρέχουσα ενεργή εργασία (παρατηρήστε τη λέξη `active` της στήλης "Rank"), που σημαίνει πως η εργασία εκτυπώνεται αυτή τη στιγμή. Η δεύτερη εργασία αποτελείται από δεδομένα που έχουν περάσει στην standard input της εντολής man:lpr[1]. Η τρίτη εργασία προέρχεται από τον χρήστη `mary`, και πρόκειται για μια πολύ ογκώδη εργασία. Το όνομα διαδρομής του αρχείου που πρόκειται να εκτυπωθεί είναι πολύ μεγάλο για να χωρέσει στη στήλη, και για αυτό η εντολή man:lpq[1] απλά το συμβολίζει με τρεις τελείες.

Η πρώτη γραμμή της εξόδου από την man:lpq[1] είναι επίσης πολύ χρήσιμη: μας ενημερώνει για το τι κάνει την παρούσα στιγμή ο εκτυπωτής (ή τουλάχιστον για το τι πιστεύει το LPD πως κάνει ο εκτυπωτής αυτή τη στιγμή).

Η εντολή man:lpq[1] επίσης υποστηρίζει την επιλογή `-l` για να δημιουργήσει μια μεγάλη, λεπτομερή λίστα. Ακολουθεί ένα παράδειγμα του `lpq -l`:

[source,bash]
....
waiting for bamboo to become ready (offline ?)
kelly: 1st				 [job 009rose]
       /etc/host.conf                    73 bytes
       /etc/hosts.equiv                  15 bytes

kelly: 2nd				 [job 010rose]
       (standard input)                  1635 bytes

mary: 3rd                                [job 011rose]
      /home/orchid/mary/research/venus/alpha-regio/mapping 78519 bytes
....

[[printing-lprm]]
=== Αφαίρεση Εργασιών

Αν αλλάξετε γνώμη για μια εργασία που είχατε αποστείλει προς εκτύπωση, μπορείτε να την αφαιρέσετε από την λίστα αναμονής με την εντολή man:lprm[1]. Μπορείτε ακόμη να χρησιμοποιήσετε την man:lprm[1] για να αφαιρέσετε μια ενεργή εργασία, αλλά πιθανόν κάποιο μέρος της να εκτυπωθεί έτσι και αλλιώς.

Για να αφαιρέσετε μια εργασία από τον προεπιλεγμένο εκτυπωτή, χρησιμοποιήστε πρώτα την man:lpq[1] για να βρείτε τον αριθμό της. Έπειτα πληκτρολογήστε:

[source,bash]
....
% lprm job-number
....

Για να αφαιρέσετε μια εργασία από κάποιον συγκεκριμένο εκτυπωτή, προσθέστε την επιλογή `-P`. Η ακόλουθη εντολή αφαιρεί την εργασία με αριθμό 10 από την ουρά αναμονής για τον εκτυπωτή `bamboo`:

[source,bash]
....
% lprm -P bamboo 10
....

Η εντολή man:lprm[1] έχει μερικές συντομεύσεις:

lprm -::
Αφαιρεί όλες τις εργασίες (για τον προεπιλεγμένο εκτυπωτή) που ανήκουν σε εσάς.

lprm _user_::
Αφαιρεί όλες τις εργασίες (για τον προεπιλεγμένο εκτυπωτή) που ανήκουν στον _χρήστη (user)_. Ο υπερχρήστης (superuser) μπορεί να αφαιρέσει εργασίες άλλων χρηστών, εσείς μπορείτε να αφαιρέσετε μόνο τις δικές σας.

lprm::
Η εντολή man:lprm[1] χωρίς αριθμό εργασίας, όνομα χρήστη, ή `-` που εμφανίζεται στην γραμμή εντολών, αφαιρεί την τρέχουσα ενεργή εργασία στον προεπιλεγμένο εκτυπωτή, αν ανήκει σε σάς. Ο υπερχρήστης (superuser) μπορεί να αφαιρέσει οποιαδήποτε ενεργή εργασία.

Για να δουλέψετε σε κάποιον συγκεκριμένο εκτυπωτή αντί του προεπιλεγμένου, απλά χρησιμοποιήστε την επιλογή `-P` με τις παραπάνω συντομεύσεις. Για παράδειγμα, η ακόλουθη εντολή αφαιρεί όλες τις εργασίες του τρέχοντος χρήστη από την ουρά αναμονής του εκτυπωτή `rattan`:

[source,bash]
....
% lprm -P rattan -
....

[NOTE]
====
Αν εργάζεστε σε περιβάλλον δικτύου, η man:lprm[1] θα σας επιτρέψει να αφαιρέσετε εργασίες μόνο από τον υπολογιστή που τις έχετε στείλει, ανεξάρτητα αν ο εκτυπωτής είναι προσβάσιμος και από άλλους υπολογιστές. Η ακόλουθη εντολή επιδεικνύει ακριβώς αυτό το χαρακτηριστικό:

[source,bash]
....
% lpr -P rattan myfile
% rlogin orchid
% lpq -P rattan
Rank   Owner	  Job  Files                          Total Size
active seeyan	  12	...                           49123 bytes
2nd    kelly      13   myfile                         12 bytes
% lprm -P rattan 13
rose: Permission denied
% logout
% lprm -P rattan 13
dfA013rose dequeued
cfA013rose dequeued

....

====

[[printing-lpr-options]]
=== Πέρα από το Απλό Κείμενο: Περισσότερες Επιλογές Εκτύπωσης

Η εντολή man:lpr[1] υποστηρίζει μια γκάμα επιλογών για τον έλεγχο μορφοποίησης κειμένου, μετατροπής γραφικών και άλλων μορφών αρχείων, παραγωγής πολλαπλών αντιγράφων, χειρισμού εργασιών, και άλλα. Οι επιλογές αυτές περιγράφονται στην παρούσα ενότητα.

[[printing-lpr-options-format]]
==== Επιλογές Μορφοποίησης και Μετατροπής

Οι ακόλουθες επιλογές της man:lpr[1] ελέγχουν την μορφοποίηση των αρχείων της εργασίας εκτύπωσης. Χρησιμοποιήστε τις αν η εργασία σας δεν περιέχει απλό κείμενο ή αν επιθυμείτε να μορφοποιήσετε απλό κείμενο διαμέσου του εργαλείου man:pr[1].

Για παράδειγμα, η ακόλουθη εντολή τυπώνει ένα αρχείο DVI (από το σύστημα στοιχειοθεσίας TeX) με όνομα [.filename]#fish-report.dvi# στον εκτυπωτή με όνομα `bamboo`:

[source,bash]
....
% lpr -P bamboo -d fish-report.dvi
....

Αυτές οι επιλογές εφαρμόζονται σε κάθε αρχείο της εργασίας, και έτσι δεν μπορείτε να αναμίξετε (ας πούμε) αρχεία DVI και ditroff μαζί στην ίδια εργασία. Απλώς στείλτε τα αρχεία σαν διαφορετικές εργασίες, χρησιμοποιώντας διαφορετικές επιλογές μετατροπής για κάθε εργασία.

[NOTE]
====
Όλες αυτές οι επιλογές εκτός της `-p` και της `-T` απαιτούν εγκατεστημένα φίλτρα μετατροπής για τον εκτυπωτή προορισμού. Για παράδειγμα, η επιλογή `-d` απαιτεί το φίλτρο μετατροπής DVI. Η ενότητα <<printing-advanced-convfilters,Φίλτρα Μετατροπής>> δίνει περισσότερες λεπτομέρειες.
====

`-c`::
Εκτυπώνει αρχεία cifplot.

`-d`::
Εκτυπώνει αρχεία DVI.

`-f`::
Εκτυπώνει αρχεία κειμένου FORTRAN.

`-g`::
Εκτυπώνει δεδομένα σχεδίασης (plot).

`-i _number_`::
Εκτυπώνει την έξοδο με εσοχή _number_ στηλών. Αν παραλείψετε το _number_, η εσοχή θα είναι 8 στήλες. Αυτή η επιλογή δουλεύει μόνο με ορισμένα φίλτρα μετατροπής.
+

[NOTE]
====
Μην τοποθετείτε κενό διάστημα μεταξύ του `-i` και του αριθμού.
====

`-l`::
Εκτυπώνει δεδομένα κειμένου κατά γράμμα (literal), συμπεριλαμβάνοντας και τους χαρακτήρες ελέγχου.

`-n`::
Εκτυπώνει δεδομένα ditroff (δεδομένα troff ανεξάρτητα από τη συσκευή).

-p::
Μορφοποιεί το απλό κείμενο με την man:pr[1] πριν να το εκτυπώσει. Δείτε την man:pr[1] για περισσότερες πληροφορίες.

`-T _title_`::
Χρησιμοποιεί το _title_ στην κεφαλίδα του man:pr[1] αντί για το όνομα αρχείου. Αυτή η επιλογή επιδρά μόνο όταν χρησιμοποιείται με την επιλογή `-p`

`-t`::
Εκτυπώνει δεδομένα troff.

`-v`::
Εκτυπώνει δεδομένα ράστερ.

Εδώ είναι ένα παράδειγμα: αυτή η εντολή εκτυπώνει μια κομψά μορφοποιημένη έκδοση της σελίδας βοηθείας man:ls[1] στον προεπιλεγμένο εκτυπωτή:

[source,bash]
....
% zcat /usr/shared/man/man1/ls.1.gz | troff -t -man | lpr -t
....

Η εντολή man:zcat[1] αποσυμπιέζει τον πηγαίο κώδικα της σελίδας βοηθείας man:ls[1] και τον περνάει στην εντολή man:troff[1], η οποία τον μορφοποιεί και δημιουργεί στην έξοδο της δεδομένα GNU troff, τα αποστέλλει στην man:lpr[1], η οποία με τη σειρά της αποστέλλει την εργασία στο LPD. Επειδή χρησιμοποιήσαμε την επιλογή `-t` στο man:lpr[1], ο spooler, κατά τη διάρκεια της εκτύπωσης, θα μετατρέψει την έξοδο GNU troff σε ένα τύπο δεδομένων κατανοητό από τον προεπιλεγμένο εκτυπωτή.

[[printing-lpr-options-job-handling]]
==== Επιλογές Χειρισμού Εργασιών

Οι ακόλουθες επιλογές του man:lpr[1] οδηγούν το LPD να χειριστεί τις εργασίες με ειδικό τρόπο:

-# _copies_::
Δημιουργεί έναν αριθμό _copies_ (αντιγράφων) για κάθε αρχείο της εργασίας αντί για ένα μόνο αντίγραφο. Ο διαχειριστής μπορεί να απενεργοποιήσει αυτή την επιλογή για να μειώσει την καταπόνηση των εκτυπωτών και να ενθαρρύνει την χρήση φωτοτυπικών μηχανημάτων. Δείτε την ενότητα <<printing-advanced-restricting-copies,Περιορισμός Εκτύπωσης Πολλαπλών Αντιγράφων>>.
+
Σε αυτό το παράδειγμα, εκτυπώνουμε στον προεπιλεγμένο εκτυπωτή τρία αντίγραφα του [.filename]#parser.c# και τρία αντίγραφα του [.filename]#parser.h#:
+

[source,bash]
....
% lpr -#3 parser.c parser.h
....

-m::
Αποστολή mail μετά την ολοκλήρωση εκτύπωσης της εργασίας. Με αυτή την επιλογή, το σύστημα LPD στέλνει mail στο λογαριασμό σας μόλις ολοκληρωθεί ο χειρισμός εκτύπωσης της εργασίας σας. Στο μήνυμα του, θα σας ενημερώσει αν η εργασία ολοκληρώθηκε επιτυχώς ή αν παρουσιάστηκε σφάλμα και (συχνά) ποιό ήταν το σφάλμα.

-s::
Δεν αντιγράφει τα αρχεία στον κατάλογο spool, αλλά αντί για αυτό, δημιουργεί συμβολικές συντομεύσεις (symbolic links) προς αυτά.
+
Αν εκτυπώνετε μια μεγάλη εργασία, ίσως θέλετε να χρησιμοποιήσετε αυτή την επιλογή. Θα σας γλυτώσει χώρο στον κατάλογο spool (ίσως η εργασία σας να υπερβαίνει τον ελεύθερο χώρο του συστήματος αρχείων που περιέχει τον κατάλογο spool). Επίσης θα κερδίσετε χρόνο αφού το LPD δεν θα χρειαστεί να αντιγράψει όλη την εργασία σας στον κατάλογο spool.
+
Αυτό, ωστόσο, έχει και ένα μειονέκτημα: από τη στιγμή που το LPD θα κάνει αναφορά κατευθείαν στο πρωτότυπο αρχείο, δεν θα έχετε δυνατότητα να μετατρέψετε ή να διαγράψετε το αρχείο έως ότου εκτυπωθεί.
+

[NOTE]
====
Αν εκτυπώνετε σε ένα απομακρυσμένο εκτυπωτή, το LPD πιθανώς θα χρειαστεί τελικά να αντιγράψει τα αρχεία από τον τοπικό υπολογιστή στον απομακρυσμένο, επομένως η επιλογή `-s` σε αυτή την περίπτωση εξοικονομεί χώρο στον τοπικό κατάλογο spool, αλλά όχι στον απομακρυσμένο. Εξακολουθεί ωστόσο να είναι ιδιαίτερα χρήσιμη.
====

-r::
Απομακρύνει τα αρχεία της εργασίας μετά την αντιγραφή τους στον κατάλογο spool, ή μετά την εκτύπωση τους με την επιλογή `-s`. Να είστε προσεκτικοί με αυτή την επιλογή!

[[printing-lpr-options-misc]]
==== Επιλογές Σελίδων Κεφαλίδας

Αυτές οι επιλογές του man:lpr[1] ρυθμίζουν το κείμενο που κανονικά εμφανίζεται στην σελίδα κεφαλίδας της εργασίας. Αν οι σελίδες κεφαλίδας παρεμποδίζονται για τον συγκεκριμένο εκτυπωτή, αυτές οι επιλογές δεν έχουν καμία επίδραση. Δείτε την ενότητα <<printing-advanced-header-pages,Σελίδες Κεφαλίδας>> για πληροφορίες σχετικά με τις ρυθμίσεις των σελίδων κεφαλίδας.

-C _text_::
Αντικαθιστά το όνομα υπολογιστή στη σελίδα κεφαλίδας με _text_. Το όνομα υπολογιστή που εμφανίζεται είναι, από προεπιλογή, το όνομα του υπολογιστή από τον οποίο έγινε η αποστολή της εργασίας.

-J _text_::
Αντικαθιστά το όνομα εργασίας στη σελίδα κεφαλίδας με _text_. Το όνομα εργασίας που εμφανίζεται από προεπιλογή, είναι το όνομα του πρώτου αρχείου της εργασίας, ή [.filename]#stdin# αν η εκτύπωση γίνεται από το standard input.

-h::
Δεν εκτυπώνει σελίδα κεφαλίδας.
+

[NOTE]
====
Ανάλογα με τις ρυθμίσεις, αυτή η επιλογή ίσως να μην έχει επίδραση λόγω του τρόπου με τον οποίο δημιουργούνται οι σελίδες κεφαλίδας. Για περισσότερες λεπτομέρειες, δείτε την ενότητα <<printing-advanced-header-pages,Σελίδες Κεφαλίδας>>.
====

[[printing-lpc]]
=== Διαχείριση Εκτυπωτών

Ως διαχειριστής, χρειάστηκε να εγκαταστήσετε, να ρυθμίσετε και να δοκιμάσετε τους εκτυπωτές σας. Χρησιμοποιώντας την εντολή man:lpc[8], μπορείτε να επικοινωνήσετε με τους εκτυπωτές σας με ακόμη περισσότερους τρόπους. Με την man:lpc[8], μπορείτε:

* Να εκκινείτε και να σταματάτε τους εκτυπωτές
* Να ενεργοποιείτε και να απενεργοποιείτε τις ουρές αναμονής
* Να ανακατατάσσετε την σειρά εργασιών σε κάθε ουρά αναμονής.

Καταρχήν, μία σημείωση σχετικά με την ορολογία: αν ένας εκτυπωτής είναι _σταματημένος (stopped)_, δεν θα εκτυπώσει τίποτε από την ουρά αναμονής εργασιών. Οι χρήστες μπορούν ακόμη να στέλνουν εργασίες, οι οποίες μπαίνουν στην ουρά αναμονής έως ότου ο εκτυπωτής _ξεκινήσει_ ή καθαριστεί η ουρά αναμονής.

Αν έχει _απενεργοποιηθεί_ η ουρά αναμονής, κανείς χρήστης (εκτός του `root`) δεν μπορεί να αποστείλει εργασίες στον εκτυπωτή. Μια _ενεργή_ ουρά αναμονής επιτρέπει να αποσταλούν εργασίες στον εκτυπωτή. Ένας εκτυπωτής μπορεί να _ξεκινήσει_ με ουρά αναμονής απενεργοποιημένη, και σε αυτή την περίπτωση θα συνεχίσει να εκτυπώνει τις εργασίες της ουράς έως ότου αυτή αδειάσει.

Γενικά, πρέπει να έχετε προνόμια `root` για να χρησιμοποιήσετε την εντολή man:lpc[8]. Οι κανονικοί χρήστες μπορούν να χρησιμοποιούν την εντολή man:lpc[8] μόνο για να βλέπουν την κατάσταση του εκτυπωτή και να επανεκκινούν τον εκτυπωτή σε περίπτωση μπλοκαρίσματος.

Παρακάτω θα βρείτε μια λίστα εντολών του man:lpc[8]. Οι περισσότερες από τις εντολές παίρνουν ως παράμετρο το _printer-name_ για τη ρύθμιση του συγκεκριμένου εκτυπωτή. Μπορείτε να χρησιμοποιείτε `all` στη θέση του _printer-name_ για να αναφερθείτε σε όλους τους εκτυπωτές που είναι καταχωρισμένοι στο [.filename]#/etc/printcap#.

`abort printer-name`::
Διαγράφει την τρέχουσα εργασία και σταματάει τον εκτυπωτή. Οι χρήστες μπορούν ακόμη να αποστείλουν εργασίες αν η ουρά αναμονής είναι ακόμη ενεργή.

`clean printer-name`::
Διαγράφει τα παλιά αρχεία από τον κατάλογο spool του εκτυπωτή. Σε κάποιες περιπτώσεις, τα αρχεία από τα οποία αποτελείται κάποια εργασία δεν αφαιρούνται κανονικά από το LPD, ειδικά αν υπήρξαν σφάλματα κατά την εκτύπωση ή κάποιες ενέργειες από τον διαχειριστή. Αυτή η εντολή βρίσκει αρχεία που δεν ανήκουν στον κατάλογο spool και τα αφαιρεί.

`disable printer-name`::
Απενεργοποιεί την ουρά αναμονής για νέες εργασίες. Αν ο εκτυπωτής δουλεύει, θα συνεχίσει να εκτυπώνει τις εναπομείναντες εργασίες στην ουρά αναμονής. Ο superuser (`root`) μπορεί πάντα να στέλνει εργασίες, ακόμη και σε απενεργοποιημένη σειρά αναμονής.
+
Αυτή η εντολή είναι χρήσιμη, όταν ελέγχετε ένα νέο εκτυπωτή ή όταν εγκαθιστάτε ένα φίλτρο: απενεργοποιήστε την ουρά αναμονής και στείλτε εργασίες σαν `root`. Οι υπόλοιποι χρήστες δεν θα έχουν δυνατότητα να αποστείλουν εργασίες έως ότου ολοκληρώσετε τους ελέγχους σας και επανενεργοποιήσετε την ουρά αναμονής με την εντολή `enable`.

`down printer-name message`::
Οδηγεί τον εκτυπωτή σε "κατέβασμα" (down). Είναι ισοδύναμο με το `disable` ακολουθούμενο από ένα `stop`. Το _message_ (μήνυμα) εμφανίζεται όταν κάποιος χρήστης ελέγχει την σειρά αναμονής με man:lpq[1] ή την κατάσταση του εκτυπωτή με `lpc status`.

`enable printer-name`::
Ενεργοποίηση της ουράς αναμονής του εκτυπωτή. Οι χρήστες μπορούν να αποστείλουν εργασίες αλλά ο εκτυπωτής δεν θα τυπώσει έως ότου ξεκινήσει.

`help command-name`::
Τυπώνει σελίδες βοηθείας για την εντολή _command-name_. Δίχως το _command-name_, εκτυπώνει μια περίληψη όλων των διαθέσιμων εντολών.

`restart printer-name`::
Ξεκινά τον εκτυπωτή. Οι κανονικοί χρήστες μπορούν να χρησιμοποιήσουν αυτή την εντολή μόνο σε κάποια ειδική περίπτωση που το LPD δεν αποκρίνεται, αλλά δεν μπορούν να ξεκινήσουν ένα εκτυπωτή που έχει σταματήσει εξαιτίας των εντολών `stop` ή `down`. Η εντολή `restart` είναι ισοδύναμη με την `abort` ακολουθούμενη από τη `start`.

`start printer-name`::
Ξεκινά τον εκτυπωτή. Ο εκτυπωτής θα τυπώσει εργασίες από την ουρά αναμονής του.

`stop printer-name`::
Σταματάει τον εκτυπωτή. Ο εκτυπωτής θα ολοκληρώσει την τρέχουσα εργασία του και δεν θα τυπώσει καμία άλλη εργασία από την ουρά αναμονής του. Ακόμη και αν ο εκτυπωτής είναι σταματημένος, οι χρήστες μπορούν ακόμη να στέλνουν εργασίες αν είναι ενεργοποιημένη η ουρά αναμονής.

`topq printer-name job-or-username`::
Ανακατάταξη της ουράς αναμονής για τον _printer-name_. Τοποθετούνται πρώτες οι εργασίες με αριθμό αναφοράς _job_ ή αυτές που ανήκουν στο χρήστη _username_. Για αυτή την εντολή, δεν μπορείτε να χρησιμοποιήσετε `all` στην θέση του _printer-name_.

`up printer-name`::
Οδηγεί τον εκτυπωτή σε "ανέβασμα" (up). Το αντίθετο της εντολής `down`. Ισοδυναμεί με την `start` ακολουθούμενη από την εντολή `enable`.

Το man:lpc[8] δέχεται τις παραπάνω εντολές στην γραμμή εντολών. Αν δεν εισάγετε καμία εντολή, το man:lpc[8] μπαίνει σε κατάσταση αλληλεπίδρασης (interactive), όπου μπορείτε να πληκτρολογείτε εντολές μέχρι να δώσετε `exit`, `quit`, ή end-of-file.

[[printing-lpd-alternatives]]
== Εναλλακτικές Λύσεις για τον Στάνταρ Spooler

Αν έχετε μελετήσει πιστά όλο το κεφάλαιο μέχρι εδώ, θα έχετε μάθει σχεδόν τα πάντα σχετικά με το σύστημα παροχέτευσης LPD που διατίθεται με το FreeBSD. Θα έχετε κατανοήσει και πολλές από τις ελλείψεις του, που φυσικά γεννούν το ερώτημα: "Ποια άλλα συστήματα παροχέτευσης (που να λειτουργούν στο FreeBSD) υπάρχουν διαθέσιμα;"

LPRng::
Το LPRng, το οποίο σκόπιμα σημαίνει "LPR: the Next Generation (η Επόμενη Γενιά)" είναι μια από την αρχή υλοποίηση του PLP. Ο Patrick Powell και ο Justin Mason (κύριος συντηρητής του PLP) συνεργάστηκαν για να φτιάξουν το LPRng. Η κύρια τοποθεσία του LPRng είναι η http://www.lprng.org/[http://www.lprng.org/].

CUPS::
Το CUPS, ή αλλιώς Common UNIX Printing System, παρέχει μια φορητή πλατφόρμα εκτυπώσεων για λειτουργικά συστήματα βασισμένα στο UNIX(R). Αναπτύχθηκε από την Easy Software Products για να προωθήσει μια στάνταρ λύση εκτυπώσεων για όλους τους χρήστες και κατασκευαστές UNIX(R).
+
Το CUPS χρησιμοποιεί το πρωτόκολλο Internet Printing Protocol (IPP) ως βάση του για τη διαχείριση εργασιών εκτύπωσης και ουρών αναμονής. Υποστηρίζονται επίσης, αλλά με μειωμένη λειτουργικότητα, τα πρωτόκολλα Line Printer Daemon (LPD), Server Message Block (SMB), και AppSocket (γνωστό ως JetDirect). Το CUPS προσθέτει δυνατότητες ανίχνευσης δικτυακών εκτυπωτών, ενώ μέσω των επιλογών PostScript Printer Description (PPD) γίνεται εφικτή η υποστήριξη σύγχρονων εκτυπωτών στον κόσμο του UNIX(R).
+
Η κύρια τοποθεσία του CUPS είναι η http://www.cups.org/[http://www.cups.org/].

HPLIP::
Το HPLIP, ή Σύστημα Απεικόνισης και Εκτύπωσης της HP για Linux(R), είναι μια σουίτα εφαρμογών για συσκευές της HP, που υποστηρίζει λειτουργίες όπως η εκτύπωση, η σάρωση και η αποστολή / λήψη φαξ. Η σουίτα αυτή χρησιμοποιεί το CUPS ως backend για κάποιες από τις λειτουργίες εκτύπωσης που παρέχει.
+
Η κύρια δικτυακή τοποθεσία της εφαρμογής HPLIP είναι http://hplipopensource.com/hplip-web/index.html[http://hplipopensource.com/hplip-web/index.html].

[[printing-troubleshooting]]
== Εντοπισμός Βλαβών

Μετά την εκτέλεση του απλού τεστ με το man:lptest[1], αντί της κανονικής εκτύπωσης, μπορεί να έχετε λάβει ως αποτέλεσμα μία από τις ακόλουθες καταστάσεις:

Ο εκτυπωτής καθυστέρησε να ξεκινήσει ή δεν εκτύπωσε ολόκληρη τη σελίδα.::
Ο εκτυπωτής τύπωσε το τεστ, αλλά δεν ξεκίνησε αμέσως. Ίσως χρειάστηκε να πιέσετε το πλήκτρο PRINT REMAINING ή το FORM FEED του εκτυπωτή σας για να εμφανιστεί το επιθυμητό αποτέλεσμα.
+
Εάν είναι όντως αυτή η περίπτωση σας, ο εκτυπωτής πιθανώς να ήταν σε αναμονή για να εξακριβώσει αν υπήρχαν πρόσθετα δεδομένα στην εργασία εκτύπωσης πριν ξεκινήσει να εκτυπώνει οτιδήποτε. Για να διορθώσετε το πρόβλημα, μπορείτε να θέσετε το φίλτρο κειμένου να στέλνει ένα χαρακτήρα FORM FEED (ή άλλο κατάλληλο) στον εκτυπωτή. Αυτό συνήθως είναι αρκετό για να μπορείτε να εκτυπώνετε κατευθείαν οποιοδήποτε κείμενο απομένει σε αναμονή στην εσωτερική μνήμη (buffer) του εκτυπωτή. Είναι επίσης χρήσιμο να ρυθμίζετε τις εκτυπώσεις σας ώστε να τελειώνουν με γεμάτη την τελευταία σελίδα, ώστε η επόμενη εργασία να μην αρχίζει από τα μισά του προηγούμενου φύλλου.
+
Η ακόλουθη τροποποίηση στο shell script [.filename]#/usr/local/libexec/if-simple# εκτυπώνει ένα form feed μετά την αποστολή της εργασίας στον εκτυπωτή:
+
[.programlisting]
....
#!/bin/sh
#
# if-simple - Simple text input filter for lpd
# Installed in /usr/local/libexec/if-simple
#
# Simply copies stdin to stdout.  Ignores all filter arguments.
# Writes a form feed character (\f) after printing job.

/bin/cat && printf "\f" && exit 0
exit 2
....

Η εκτύπωση παρουσιάζει "φαινόμενο σκάλας (staircase effect)."::
Στην εκτύπωση σας φαίνεται το ακόλουθο:
+
[source,bash]
....
!"#$%&'()*+,-./01234
                "#$%&'()*+,-./012345
                                 #$%&'()*+,-./0123456
....
+
Γίνατε ένα ακόμα θύμα του _φαινομένου σκάλας_, που προκλήθηκε από αντιφατικές ερμηνείες των χαρακτήρων με τους οποίους δηλώνεται η τροφοδοσία νέας γραμμής. Τα λειτουργικά συστήματα τύπου UNIX(R) χρησιμοποιούν έναν μόνο χαρακτήρα ASCII με κωδικό 10, τον line feed (τροφοδοσία γραμμής, LF). Το MS-DOS(R), το OS/2(R), και διάφορα άλλα, χρησιμοποιούν ένα ζεύγος χαρακτήρων ASCII κωδικού 10 _και_ ASCII κωδικού 13 (τον carriage return ή αλλιώς CR). Πολλοί εκτυπωτές χρησιμοποιούν την σύμβαση του MS-DOS(R) για την αλλαγή γραμμής.
+
Όταν εκτυπώνετε με το FreeBSD, το κείμενο σας απλά χρησιμοποιεί τον χαρακτήρα τροφοδοσίας γραμμής (line feed). Ο εκτυπωτής, μόλις αντιληφθεί τον χαρακτήρα line feed, προωθεί το χαρτί κατά μία γραμμή, αλλά κρατάει την ίδια θέση οριζόντια καθώς καλείται να εκτυπώσει τον επόμενο χαρακτήρα. Σε αυτό το σημείο χρησιμοποιείται το CR (carriage return): μετακινεί δηλαδή την θέση εργασίας για τον επόμενο χαρακτήρα που πρόκειται να εκτυπωθεί στο αριστερό άκρο του χαρτιού.
+
Το FreeBSD επιθυμεί ο εκτυπωτής να μπορεί να ενεργεί ως εξής:
+
[.informaltable]
[cols="1,1", frame="none"]
|===

|Όταν ο εκτυπωτής λαμβάνει CR
|Να εκτυπώνει CR

|Όταν ο εκτυπωτής λαμβάνει LF
|Να εκτυπώνει CR + LF
|===
+
Υπάρχουν διάφοροι τρόποι για να επιτευχθεί αυτό:

** Χρησιμοποιήστε τα πλήκτρα ρύθμισης του εκτυπωτή ή τον πίνακα ελέγχου για να αλλάξετε τον τρόπο με τον οποίο ερμηνεύει αυτούς τους χαρακτήρες ο εκτυπωτής σας. Συμβουλευτείτε το εγχειρίδιο χρήσης του για να δείτε πως μπορεί να γίνει αυτό.
+
[NOTE]
====
Αν έχετε και άλλα λειτουργικά στο σύστημα σας εκτός από το FreeBSD, πιθανόν να χρειαστεί, όταν τα χρησιμοποιείτε, να _επαναρυθμίσετε_ τον εκτυπωτή σας ώστε να ερμηνεύει διαφορετικά τους χαρακτήρες CR και LF. Στην περίπτωση αυτή, ίσως είναι καλύτερο να προτιμήσετε κάποια από τις λύσεις που ακολουθούν.
====

** Ο οδηγός (driver) της σειριακής γραμμής του FreeBSD μπορεί να μετατρέπει αυτόματα από LF σε CR+LF. Φυσικά, αυτό δουλεύει _μόνο_ σε σειριακές θύρες. Για να ενεργοποιήσετε αυτή την λειτουργία, χρησιμοποιήστε την ικανότητα `ms#` και ορίστε την κατάσταση λειτουργίας `onlcr` στο αρχείο [.filename]#/etc/printcap# για τον εκτυπωτή.
** Στείλτε ένα _κωδικό διαφυγής (escape code)_ στον εκτυπωτή ώστε να χειρίζεται προσωρινά τους χαρακτήρες LF με διαφορετικό τρόπο. Συμβουλευτείτε το εγχειρίδιο χρήσης του εκτυπωτή σας για τους κώδικες διαφυγής που υποστηρίζονται. Όταν ανακαλύψετε τον κατάλληλο, μετατρέψτε το φίλτρο κειμένου ώστε να στέλνει πρώτα τον κωδικό, και έπειτα την εργασία στον εκτυπωτή.
+ 
Εδώ είναι ένα παράδειγμα φίλτρου κειμένου για εκτυπωτές που καταλαβαίνουν τους κωδικούς διαφυγής PCL της Hewlett-Packard. Αυτό το φίλτρο κάνει τον εκτυπωτή να χειρίζεται τους χαρακτήρες LF ως LF και CR. Έπειτα αποστέλλει την εργασία, στέλνοντας στο τέλος της ένα χαρακτήρα αλλαγής σελίδας (form feed) ώστε να γίνει σωστή εξαγωγή της τελευταίας σελίδας. Το φίλτρο αυτό θα πρέπει να δουλεύει με σχεδόν όλους τους εκτυπωτές της Hewlett Packard.
+
[.programlisting]
....
#!/bin/sh
#
# hpif - Simple text input filter for lpd for HP-PCL based printers
# Installed in /usr/local/libexec/hpif
#
# Simply copies stdin to stdout.  Ignores all filter arguments.
# Tells printer to treat LF as CR+LF.  Ejects the page when done.

printf "\033&k2G" && cat && printf "\033&l0H" && exit 0
exit 2
....
+ 
Εδώ είναι ένα παράδειγμα για το [.filename]#/etc/printcap# ενός υπολογιστή με όνομα `orchid`. Έχει ένα μόνο εκτυπωτή στην πρώτη παράλληλη θύρα του, ένα Hewlett Packard LaserJet 3Si με όνομα `teak`. Χρησιμοποιεί το παραπάνω script ως φίλτρο κειμένου:
+
[.programlisting]
....
#
#  /etc/printcap for host orchid
#
teak|hp|laserjet|Hewlett Packard LaserJet 3Si:\
        :lp=/dev/lpt0:sh:sd=/var/spool/lpd/teak:mx#0:\
        :if=/usr/local/libexec/hpif:
....

Εκτυπώνεται η μία γραμμή πάνω στην άλλη.::
Ο εκτυπωτής δεν προωθεί καθόλου το χαρτί και όλες οι γραμμές κειμένου τυπώνονται η μία πάνω από την άλλη, σε μία γραμμή.
+
Αυτό το πρόβλημα είναι το "αντίστροφο" του φαινόμενου σκάλας, που περιγράψαμε προηγουμένως, και είναι πολύ σπάνιο. Σε κάποιο σημείο, οι χαρακτήρες LF που χρησιμοποιεί το FreeBSD για να τερματίσει την γραμμή, ερμηνεύονται ως χαρακτήρες CR οι οποίοι επιστρέφουν την κεφαλή στο αριστερό άκρο του χαρτιού, αλλά δίχως να προωθήσουν το χαρτί μία γραμμή προς τα κάτω.
+
Χρησιμοποιήστε τους διακόπτες ρυθμίσεων του εκτυπωτή ή τον πίνακα ελέγχου για να θέσετε τις ακόλουθες επιλογές για τα LF και CR characters:
+
[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Ο εκτυπωτής λαμβάνει
| Ο εκτυπωτής τυπώνει

|CR
|CR

|LF
|CR + LF
|===
Ο εκτυπωτής δεν εκτυπώνει (χάνει) κάποιους χαρακτήρες.::
Ο εκτυπωτής, ενώ είναι σε λειτουργία εκτύπωσης, δεν εκτυπώνει κάποιους χαρακτήρες σε όλες τις γραμμές. Το πρόβλημα πιθανώς να γίνεται εντονότερο καθώς η εκτύπωση εξελίσσεται, χάνοντας ακόμη περισσότερους χαρακτήρες.
+
Το πρόβλημα είναι πως ο εκτυπωτής, καθώς εκτυπώνει, δεν προλαβαίνει να ακολουθήσει την ταχύτητα με την οποία ο υπολογιστής στέλνει δεδομένα μέσω της σειριακής διασύνδεσης (αυτό το πρόβλημα δεν πρέπει κανονικά να συμβαίνει σε εκτυπωτές συνδεμένους σε παράλληλες θύρες). Υπάρχουν δύο τρόποι για να ξεπεραστεί αυτό το πρόβλημα:

** Εάν ο εκτυπωτής υποστηρίζει έλεγχο ροής XON/XOFF, ρυθμίστε το FreeBSD να τον χρησιμοποιήσει ορίζοντας την κατάσταση λειτουργίας `ixon` με την ικανότητα `ms#`.
** Εάν ο εκτυπωτής υποστηρίζει έλεγχο ροής τύπου Request to Send / Clear to Send (hardware handshake, γνωστό και με την ονομασία `RTS/CTS`), πρέπει να οριστεί η κατάσταση λειτουργίας `crtscts` στην ικανότητα `ms#`. Βεβαιωθείτε πως το καλώδιο που συνδέει τον εκτυπωτή με τον υπολογιστή είναι σωστά φτιαγμένο για χρήση αυτού του ελέγχου ροής.

Ο εκτυπωτής τυπώνει σκουπίδια.::
Ο εκτυπωτής τύπωσε κάτι που αποκαλούμε τυχαία σκουπίδια, εννοώντας οτιδήποτε εκτός του επιθυμητού κειμένου.
+
Αυτό είναι συνήθως ένα ακόμα σύμπτωμα λανθασμένων παραμέτρων σειριακής επικοινωνίας με τον εκτυπωτή. Ελέγξτε ξανά την τιμή bps rate στην ικανότητα `br`, και την ρύθμιση parity στην ικανότητα `ms#`. Βεβαιωθείτε πως ο εκτυπωτής χρησιμοποιεί τις ίδιες ρυθμίσεις που έχουν καθοριστεί στο αρχείο [.filename]#/etc/printcap#.

Δεν συνέβη τίποτε, ο εκτυπωτής δεν ξεκίνησε καν.::
Αν δεν συνέβη τίποτε, το πρόβλημα πιθανόν να οφείλεται στο FreeBSD και όχι στο hardware. Προσθέστε την ικανότητα αρχείου καταγραφής (log file, `lf`) στο αρχείο [.filename]#/etc/printcap#, στην καταχώριση του εκτυπωτή που έχει το πρόβλημα. Για παράδειγμα, εδώ είναι η καταχώριση για τον `rattan`, με την ικανότητα `lf`:
+
[.programlisting]
....
rattan|line|diablo|lp|Diablo 630 Line Printer:\
        :sh:sd=/var/spool/lpd/rattan:\
        :lp=/dev/lpt0:\
        :if=/usr/local/libexec/if-simple:\
        :lf=/var/log/rattan.log
....
+
Έπειτα, προσπαθήστε να ξαναεκτυπώσετε. Ελέγξτε το αρχείο καταγραφής (log) (στο παράδειγμα μας, [.filename]#/var/log/rattan.log#) για να βρείτε πιθανές αναφορές σφαλμάτων. Με βάση τα μηνύματα που βλέπετε, προσπαθήστε να διορθώσετε το πρόβλημα.
+
Αν δεν καθορίσετε την ικανότητα `lf`, το LPD χρησιμοποιεί από προεπιλογή το [.filename]#/dev/console#.
