---
title: Chapter 11. Writing Style
prev: books/fdp-primer/manual-pages
next: books/fdp-primer/editor-config
---

[[writing-style]]
= Writing Style
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 11

include::shared/en/mailing-lists.adoc[]

toc::[]

[[writing-style-tips]]
== Tips

Technical documentation can be improved by consistent use of several principles. Most of these can be classified into three goals: _be clear_, _be complete_, and _be concise_. These goals can conflict with each other. Good writing consists of a balance between them.

[[writing-style-be-clear]]
=== Be Clear

Clarity is extremely important. The reader may be a novice, or reading the document in a second language. Strive for simple, uncomplicated text that clearly explains the concepts.

Avoid flowery or embellished speech, jokes, or colloquial expressions. Write as simply and clearly as possible. Simple text is easier to understand and translate.

Keep explanations as short, simple, and clear as possible. Avoid empty phrases like "in order to", which usually just means "to". Avoid potentially patronizing words like "basically". Avoid Latin terms like "i.e.," or "cf.", which may be unknown outside of academic or scientific groups.

Write in a formal style. Avoid addressing the reader as "you". For example, say "copy the file to [.filename]#/tmp#" rather than "you can copy the file to [.filename]#/tmp#".

Give clear, correct, _tested_ examples. A trivial example is better than no example. A good example is better yet. Do not give bad examples, identifiable by apologies or sentences like "but really it should never be done that way". Bad examples are worse than no examples. Give good examples, because _even when warned not to use the example as shown_, the reader will usually just use the example as shown.

Avoid _weasel words_ like "should", "might", "try", or "could". These words imply that the speaker is unsure of the facts, and create doubt in the reader.

Similarly, give instructions as imperative commands: not "you should do this", but merely "do this".

[[writing-style-be-complete]]
=== Be Complete

Do not make assumptions about the reader's abilities or skill level. Tell them what they need to know. Give links to other documents to provide background information without having to recreate it. Put yourself in the reader's place, anticipate the questions they will ask, and answer them.

[[writing-style-be-concise]]
=== Be Concise

While features should be documented completely, sometimes there is so much information that the reader cannot easily find the specific detail needed. The balance between being complete and being concise is a challenge. One approach is to have an introduction, then a "quick start" section that describes the most common situation, followed by an in-depth reference section.

[[writing-style-guidelines]]
== Guidelines

To promote consistency between the myriad authors of the FreeBSD documentation, some guidelines have been drawn up for authors to follow.

Use American English Spelling::
There are several variants of English, with different spellings for the same word. Where spellings differ, use the American English variant. "color", not "colour", "rationalize", not "rationalise", and so on.
+
[NOTE]
====
The use of British English may be accepted in the case of a contributed article, however the spelling must be consistent within the whole document. The other documents such as books, web site, manual pages, etc. will have to use American English.
====

Do not use contractions::
Do not use contractions. Always spell the phrase out in full. "Don't use contractions" is wrong.
+
Avoiding contractions makes for a more formal tone, is more precise, and is slightly easier for translators.

Use the serial comma::
In a list of items within a paragraph, separate each item from the others with a comma. Separate the last item from the others with a comma and the word "and".
+
For example:
+
This is a list of one, two and three items.
+
Is this a list of three items, "one", "two", and "three", or a list of two items, "one" and "two and three"?
+
It is better to be explicit and include a serial comma:
+
This is a list of one, two, and three items.
Avoid redundant phrases::
Do not use redundant phrases. In particular, "the command", "the file", and "man command" are often redundant.
+
For example, commands:
+
Wrong: Use the `git` command to update sources.
+
Right: Use `git` to update sources.
+
Filenames:
+
Wrong: ... in the filename [.filename]#/etc/rc.local#...
+
Right: ... in [.filename]#/etc/rc.local#...
+
Manual page references (the second example uses `citerefentry` with the man:csh[1] entity):.
+
Wrong: See `man csh` for more information.
+
Right: See man:csh[1].

For more information about writing style, see http://www.bartleby.com/141/[Elements of Style], by William Strunk.

[[writing-style-guide]]
== Style Guide

To keep the source for the documentation consistent when many different people are editing it, please follow these style conventions.

[[writing-style-acronyms]]
=== Acronyms

Acronyms should be defined the first time they appear in a document, as in: "Network Time Protocol (NTP)". After the acronym has been defined, use the acronym alone unless it makes more sense contextually to use the whole term. Acronyms are usually defined only once per chapter or per document.

All acronyms should be enclosed using the ` character.

[[writing-style-word-list]]
== Word List

This list of words shows the correct spelling and capitalization when used in FreeBSD documentation. If a word is not on this list, ask about it on the {freebsd-doc}.

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Name
| Syntax
| Rendered


| Copyright
| +(C)+
| (C)

| Registered
| +(R)+
| (R)

| Trademark
| +(TM)+
| (TM)

| Em dash
| +--+
| --

| Ellipses
| +...+
| ...

| Single right arrow
| +->+
| ->

| Double right arrow
| +=>+
| =>

| Single left arrow
| +<-+
| <-

| Double left arrow
| +<=+
| <=

|===
