# $FreeBSD$
# $FreeBSDde: de-www/gifs/Makefile,v 1.2 2004/05/16 22:06:56 mheinen Exp $
# basiert auf: 1.50

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   bar.gif

.include "${DOC_PREFIX}/share/mk/web.site.mk"
