# $FreeBSD: www/fr/news/1998/Makefile,v 1.1 2002/12/22 22:02:23 stephane Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"

