# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.sgml mailinglists.sgml newsgroups.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
