---
title: "FreeBSD Press Release: 2000 年 10 月 18 日"
sidenav: about
loadPress: false
---

= FreeBSD Press Release: 2000 年 10 月 18 日

== 選挙で誕生した新生コアチーム

*BSD カンファレンス (カリフォルニア州モントレー) 発、2000 年 10 月 18 日:* FreeBSD プロジェクトは、プロジェクトの管理委員会であるコアチーム (Core Team) を新たに選出するための選挙の結果を発表しました。 プロジェクトの開発者から選挙というかたちでコアチームが選ばれるのは、 これがはじめてのことです。 選挙の結果、新たに Greg Lehey 氏、 Warner Losh 氏、Mike Smith 氏、Robert Watson 氏がコアチームへ参加し、 浅見 賢 氏、David Greenman 氏、Jordan Hubbard 氏、Doug Rabson 氏、 Peter Wemm 氏の再選が決まりました。

FreeBSD プロジェクトの共同創立者であり、コアチームの一員として再選された Jordan Hubbard 氏は、この白熱した選挙結果について次のように述べています。 「コアチームのメンバを決めるための公開選挙は FreeBSD プロジェクトがはじまって以来初の出来事であり、 FreeBSD の開発者ならば誰でもプロジェクトのリーダとして参加する資格を持っていることを示した、 とても大きな意味を持つものとなりました」 新しいコアチームは FreeBSD の多様性を良く表しており、RAID ファイルシステムやデバイスドライバの開発、 幅広いセキュリティ問題に至るまで、 さまざまな専門技術を持った世界各国の有能な開発者たちのグループでもあります。

新しいコアチームのメンバは、FreeBSD プロジェクトの公式の開発者である FreeBSD コミッターチームの中から、チーム内の投票によって選出されています。 コミッターは FreeBSD ソースリポジトリに直接アクセスし、 プロジェクトに関わるソフトウェア開発の大部分を遂行します。 現在までのコアチームは、 設計や運営の監督を行なうための委員会のようなものでした。

今年の夏、FreeBSD のコミッターたちの間で行なわれた投票により、 このオープンソースのオペレーティングシステムのコミュニティに開発者として参加するための条件の見直しについて、 プロジェクト内部での議論を可能にする民主主義モデルを採用し、 運営形態をそれに移行させるという案が可決されました。 ただし一方で、前任のコアチームメンバの半数以上が再任されたため、 組織が従来から大きく変わったというわけではありません。

前コアチームの Poul-Henning Kamp 氏は次のように語っています。 「過去 8 年間、わたしたちがコアチームの中で一緒に成し遂げたことについて、 とても誇りに思っています。 新しいコアチームと、 そして彼らがコミッターの中から選出されたという事実は、 将来のプロジェクトをより柔軟なものにするでしょう」

また、プロジェクトのリーダが交代することは良い傾向であることを、 Kamp 氏は次のように指摘しています。 前任のコアチームのメンバはもちろん全員がプロジェクトに残りますし、 今度はプロジェクトで開発により重点をおいた活動ができるようになります。 「今はプロジェクトの管理じゃなく、FreeBSD のソースコードにもっと時間をかけることができるんですよ」

== 選出されたコアチームのメンバ

**浅見 賢 (Satoshi Asami) 氏**は DecorMagic, Inc. の共同創立者兼 CTO です。 FreeBSD では FreeBSD Ports Collection を監督しています。

**David Greenman 氏**は FreeBSD プロジェクトの共同創立者であり、現在は TeraSolutions, Inc. の社長 (President) を務めています。 TeraSolutions, Inc. はインターネットサーバと RAID ストレージシステムを製造している企業です。

**Jordan Hubbard 氏**は FreeBSD プロジェクトの共同創立者であり、 プロジェクトにおける広報とリリースエンジニアリングを担当しています。 また、彼は BSDi の Open Source Solutions グループの副社長 (Vice President) でもあります。

**Greg Lehey 氏**は Linuxcare, Inc. に所属するオープンソース研究者であり、 仕事の大部分を、彼が以前勤めていた Univac、Tandem、Siemens-Nixdorf といったコンピュータメーカのあるドイツで行なっています。 彼は FreeBSD 用の Vinum ボリューム管理システムと RAID ソフトウェアの作者であり、 現在は FreeBSD SMPng プロジェクトで活躍しています。 Porting Unix Software および The Complete FreeBSD の著者としても知られています。

**Warner Losh 氏**は NetBSD の PC カードのコードを FreeBSD に移植している人物です。 また過去二年間、FreeBSD セキュリティオフィサも務めました。

**Doug Rabson 氏**は 3D グラフィックス技術を専門とする Qube Software Ltd. の共同創立者です。 彼は以前 FreeBSD デバイスドライバフレームワークのメインアーキテクトを担当していましたが、 現在は FreeBSD を alpha と ia64 に移植する作業を担当しています。

**Mike Smith 氏**は BSDi の Open Source Solutions グループの主任技術者であり、 FreeBSD 開発者コミュニティに開発者の一員として、OEM 渉外担当として、 そして時折、アーキテクトやデバイスドライバの作者としても活躍しています。

**Robert Watson 氏**は NAI Labs の研究者であり、ネットワークと オペレーティングシステムのセキュリティに関する研究を行なっている 人物です。 彼の FreeBSD プロジェクトにおける貢献は、オペレーティング システムのセキュリティを向上させる拡張 (http://www.trustedbsd.org[TrustedBSD]) およびセキュリティアーキテクチャに関するもの、 さらにセキュリティオフィサチームでの活動にまで及びます。

**Peter Wemm 氏**はオーストラリアで ISP 産業がはじめて生まれた頃から FreeBSD の活動に参加している人物で、合衆国へ移ってからは Yahoo!, Inc. のソフトウェア技術者として働いています。 彼の担当は、FreeBSD ソースコードリポジトリとカーネル開発の管理です。

== FreeBSD とは

FreeBSD は制限の少ないライセンスを持ち、カリフォルニア大学バークレー校で 1994 年まで開発が続けられていた Berkeley Software Distributions、BSD Net/2 と 4.4 Lite に由来するオープンソースのオペレーティングシステムです。 このシステムの開発や管理は、 従業員とボランティア貢献者でつくる国際的な組織によって行なわれています。 FreeBSD は高いパフォーマンスのネットワーク機能とファイルシステムをサポートしており、 *Yahoo!*、*above.net*、*Verio* といった産業の先端を行く企業のインターネットサービスプロバイダに広く採用されているものです。 また、FreeBSD は *IBM*、*Inktomi*、*Juniper Networks*、 そして**ネットワーク最大手の Nokia Company** の組み込みネットワーク機器用のプラットフォームにも良く利用されています。

詳細は http://www.FreeBSD.org[http://www.FreeBSD.org/] をご覧ください。

== お問い合わせ先

Jordan Hubbard +
The FreeBSD Project +
925-682-7859 +
jkh@FreeBSD.org

== # # #

BSD は Berkeley Software Design, Inc. の登録商標です。 その他、記載された商標名は各社の商標または登録商標です。 BSD の技術はカリフォルニア大学バークレー校とそれに貢献した人々によって開発されました。
