# $FreeBSD$

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################
# %SOURCE%    en/events/Makefile.inc
# %SRCID%     1.2

DOC_PREFIX?=	${.CURDIR}/../../..
WEBBASE?=	/data/hu/events
