# $FreeBSD: www/hu/events/Makefile.inc,v 1.1 2009/04/06 17:56:08 pgj Exp $

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################
# %SOURCE%    en/events/Makefile.inc
# %SRCID%     1.2

WEB_PREFIX?=	${.CURDIR}/../../..
WEBBASE?=	/data/hu/events
