---
title: Vorwort
prev: books/handbook/
next: books/handbook/parti
---

[preface]
[[book-preface]]
= Vorwort
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums!:
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:table-caption: Tabelle
:figure-caption: Abbildung
:example-caption: Beispiel
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:

[[preface-audience]]
== Über dieses Buch

Der erste Teil dieses Buchs führt FreeBSD-Einsteiger durch den Installationsprozess und stellt leicht verständlich Konzepte und Konventionen vor, die UNIX(R) zu Grunde liegen. Sie müssen nur neugierig sein und bereitwillig neue Konzepte aufnehmen, wenn diese vorgestellt werden, um diesen Teil durchzuarbeiten.

Wenn Sie den ersten Teil bewältigt haben, bietet der umfangreichere zweite Teil eine verständliche Darstellung vieler Themen, die für FreeBSD-Administratoren relevant sind. Wenn Kapitel auf anderen Kapiteln aufbauen, wird das in der Übersicht am Anfang eines Kapitels erläutert.

Weitere Informationsquellen entnehmen Sie bitte crossref:bibliography[bibliography,Bibliografie].

[[preface-changes-from3]]
==  Änderungen gegenüber der dritten Auflage

Die aktuelle Auflage des Handbuchs ist das Ergebnis der engagierten Arbeit Hunderter Mitarbeiter des FreeBSD Documentation Projects in den vergangenen 10 Jahren. Die wichtigsten Änderungen dieser Auflage gegenüber der dritten Auflage von 2004 sind:

* crossref:dtrace[dtrace,DTrace] informiert Sie über die mächtigen Funktionen zur Leistungsmessung, die dieses Werkzeug bietet.
* crossref:filesystems[filesystems,Dateisystemunterstützung] enthält Informationen über die Unterstützung nicht-nativer Dateisysteme in FreeBSD, wie beispielsweise ZFS von Sun(TM).
* crossref:audit[audit,Security Event Auditing] informiert über die neuen Auditing-Fähigkeitenvon FreeBSD.
* crossref:virtualization[virtualization,Virtualisierung] enthält Informationen zur Installation von FreeBSD in verschiedenen Virtualisierungs-Programmen.
* crossref:bsdinstall[bsdinstall,FreeBSD installieren] wurde hinzugefügt, um die Installation von FreeBSD mit dem neuen Installationswerkzeug, bsdinstall, zu dokumentieren.

[[preface-changes-from2]]
== Änderungen gegenüber der zweiten Auflage (2004)

Die dritte Auflage des Handbuchs war das Ergebnis der über zwei Jahre dauernden engagierten Arbeit des FreeBSD Documentation Projects. Die gedruckte Ausgabe war derart umfangreich, dass es notwendig wurde, sie in zwei Bände aufzuteilen. Die wichtigsten Änderungen dieser Auflage waren:

* crossref:config[config-tuning,Konfiguration und Tuning] enthält neue Abschnitte über ACPI, Energie- und Ressourcenverwaltung und das Werkzeug `cron`.
* crossref:security[security,Sicherheit] erläutert nun Virtual Private Networks (VPNs), Zugriffskontrolllisten (ACLs) und Sicherheitshinweise.
* crossref:mac[mac,Verbindliche Zugriffskontrolle] ist ein neues Kapitel, das vorgeschriebene Zugriffskontrollen vorstellt und erklärt, wie FreeBSD-Systeme mit MACs abgesichert werden können.
* crossref:disks[disks,Speichermedien] enthält neue Informationen über USB-Speichergeräte, Dateisystem-Snapshots, Quotas, Datei- und Netzwerk-basierte Dateisysteme sowie verschlüsselte Partitionen.
* Zum crossref:ppp-and-slip[ppp-and-slip,PPP] wurde ein Abschnitt über Fehlersuche hinzugefügt.
* crossref:mail[mail,Elektronische Post (E-Mail)] wurde um Abschnitte über alternative Transport-Agenten (MTAs), SMTP-Authentifizierung, UUCP, fetchmail, procmail und weitere Themen erweitert.
* crossref:network-servers[network-servers,Netzwerkserver] ist ein weiteres neues Kapitel dieser Auflage. Das Kapitel beschreibt, wie der Apache HTTP-Server, ftpd und ein Samba-Server für Microsoft(R) Windows(R)-Clients eingerichtet werden. Einige Abschnitte aus dem crossref:advanced-networking[advanced-networking,Weiterführende Netzwerkthemen] befinden sich nun, wegen des thematischen Zusammenhangs, in diesem Kapitel.
* Das crossref:advanced-networking[advanced-networking,Weiterführende Netzwerkthemen] beschreibt nun den Einsatz von Bluetooth(R)-Geräten unter FreeBSD und das Einrichten von drahtlosen Netzwerken sowie ATM-Netzwerken.
* Neu hinzugefügt wurde ein Glossar, das die im Buch verwendeten technischen Ausdrücke definiert.
* Das Erscheinungsbild der Tabellen und Abbildungen im Buch wurde verbessert.

[[preface-changes]]
== Änderungen gegenüber der ersten Auflage (2001)

Die zweite Auflage ist das Ergebnis der engagierten Arbeit der Mitglieder des FreeBSD Documentation Projects über zwei Jahre. Die wichtigsten Änderungen gegenüber der ersten Auflage sind:

* Ein Index wurde erstellt.
* Alle ASCII-Darstellungen wurden durch Grafiken ersetzt.
* Jedes Kapitel wird durch eine Übersicht eingeleitet, die den Inhalt des Kapitels zusammenfasst und die Voraussetzungen für ein erfolgreiches Durcharbeiten des Kapitels darstellt.
* Der Inhalt wurde in die logischen Abschnitte "Erste Schritte", "Systemadministration" und "Anhänge" unterteilt.
* crossref:basics[basics,Grundlagen des FreeBSD Betriebssystems] wurde um den Abschnitt "Dämonen, Signale und Stoppen von Prozessen" erweitert.
* Das crossref:ports[ports,Installieren von Anwendungen: Pakete und Ports] behandelt nun auch Pakete.
* crossref:x11[x11,Das X-Window-System] wurde neu geschrieben. Der Schwerpunkt liegt auf modernen Benutzeroberflächen wie KDE und GNOME unter XFree86(TM).
* Das crossref:boot[boot,FreeBSDs Bootvorgang] wurde erweitert.
* crossref:disks[disks,Speichermedien] ist aus den beiden Kapiteln "Laufwerke" und "Sicherungen" entstanden. Die in den beiden Kapiteln diskutierten Themen sind so leichter zu verstehen. Hinzugekommen ist ein Abschnitt über Software- und Hardware-RAID.
* Das crossref:serialcomms[serialcomms,Serielle Datenübertragung] wurde reorganisiert und auf FreeBSD 4.X/5.X angepasst.
* Das crossref:ppp-and-slip[ppp-and-slip,PPP] wurde aktualisiert.
* crossref:advanced-networking[advanced-networking,Weiterführende Netzwerkthemen] wurde um viele neue Abschnitte erweitert.
* crossref:mail[mail,Elektronische Post (E-Mail)] wurde um einen Abschnitt über die Konfiguration von Sendmail erweitert.
* crossref:linuxemu[linuxemu,Linux®-Binärkompatibilität] behandelt zusätzlich die Installation von Oracle(R) und SAP(R) R/3(R).
* Neu hinzugekommen sind:

** crossref:config[config-tuning,Konfiguration und Tuning].
** crossref:multimedia[multimedia,Multimedia].

[[preface-overview]]
== Gliederung

Dieses Buch ist in fünf Abschnitte unterteilt. Der erste Abschnitt, _Erste Schritte_, behandelt die Installation und die Grundlagen von FreeBSD. Dieser Abschnitt sollte in der vorgegebenen Reihenfolge durchgearbeitet werden, schon Bekanntes darf aber übersprungen werden. Der zweite Abschnitt, _Oft benutzte Funktionen_, behandelt häufig benutzte Funktionen von FreeBSD. Dieser Abschnitt sowie alle nachfolgenden Abschnitte können in beliebiger Reihenfolge gelesen werden. Jeder Abschnitt beginnt mit einer kurzen Übersicht, die das Thema des Abschnitts und das nötige Vorwissen erläutert. Die Übersichten helfen dem Leser, interessante Kapitel zu finden und erleichtern das Stöbern im Handbuch. Der dritte Abschnitt, _Systemadministration_, behandelt die Administration eines FreeBSD-Systems. Der vierte Abschnitt, _Netzwerke_, bespricht Netzwerke und Netzwerkdienste. Der fünfte Abschnitt enthält Anhänge und Verweise auf weitere Informationen.

_crossref:introduction[introduction,Einleitung]_::
Dieses Kapitel macht Einsteiger mit FreeBSD vertraut. Es behandelt die Geschichte, die Ziele und das Entwicklungsmodell des FreeBSD-Projekts.

_crossref:bsdinstall[bsdinstall,FreeBSD installieren]_::
Beschreibt den Ablauf der Installation von FreeBSD 9._x_ und neuere mittels bsdinstall.

_crossref:basics[basics,Grundlagen des FreeBSD Betriebssystems]_::
Erläutert die elementaren Kommandos und Funktionen von FreeBSD. Wenn Sie schon mit Linux(R) oder einem anderen UNIX(R) System vertraut sind, können Sie dieses Kapitel überspringen.

_crossref:ports[ports,Installieren von Anwendungen: Pakete und Ports]_::
Zeigt wie mit der innovativen Ports-Sammlung oder mit Paketen Software von Fremdherstellern installiert wird.

_crossref:x11[x11,Das X-Window-System]_::
Beschreibt allgemein das X Window System und geht speziell auf X11 unter FreeBSD ein. Weiterhin werden graphische Benutzeroberflächen wie KDE und GNOME behandelt.

_crossref:desktop[desktop,Desktop-Anwendungen]_::
Enthält eine Aufstellung verbreiteter Anwendungen wie Browser, Büroanwendungen und Office-Pakete und beschreibt wie diese Anwendungen installiert werden.

_crossref:multimedia[multimedia,Multimedia]_::
Erklärt, wie Sie auf Ihrem System Musik und Videos abspielen können. Beispielhaft werden auch Anwendungen aus dem Multimedia-Bereich beleuchtet.

_crossref:kernelconfig[kernelconfig,Konfiguration des FreeBSD-Kernels]_::
Erklärt, warum Sie einen angepassten Kernel erzeugen sollten und gibt ausführliche Anweisungen wie Sie einen angepassten Kernel konfigurieren, bauen und installieren.

_crossref:printing[printing,Drucken]_::
Beschreibt, wie Sie Drucker unter FreeBSD verwalten. Diskutiert werden Deckblätter, das Einrichten eines Druckers und ein Abrechnungssystem für ausgedruckte Seiten.

_crossref:linuxemu[linuxemu,Linux®-Binärkompatibilität]_::
Beschreibt die binäre Kompatibilität zu Linux(R). Weiterhin werden ausführliche Installationsanleitungen für Oracle(R) und Mathematica(R) gegeben.

_crossref:config[config-tuning,Konfiguration und Tuning]_::
Beschreibt die Einstellungen, die ein Systemadministrator vornehmen kann, um die Leistungsfähigkeit eines FreeBSD Systems zu verbessern. In diesem Kapitel werden auch verschiedene Konfigurationsdateien besprochen.

_crossref:boot[boot,FreeBSDs Bootvorgang]_::
Erklärt den Bootprozess von FreeBSD und beschreibt die Optionen, mit denen sich der Bootprozess beeinflussen lässt.

_crossref:security[security,Sicherheit]_::
Beschreibt die Werkzeuge mit denen Sie Ihr FreeBSD-System absichern. Unter Anderem werden Kerberos, IPsec und OpenSSH besprochen.

_crossref:jails[jails,Jails]_::
Dieses Kapitel beschreibt das Jails-Framework sowie die Vorteile von Jails gegenüber der traditionellen chroot-Unterstützung von FreeBSD.

_crossref:mac[mac,Verbindliche Zugriffskontrolle]_::
Erklärt vorgeschriebene Zugriffskontrollen (MACs) und wie mit ihrer Hilfe FreeBSD-Systeme gesichert werden.

_crossref:audit[audit,Security Event Auditing]_::
Beschreibt, was FreeBSD Event Auditing ist, wie Sie diese Funktion installieren und konfigurieren und die damit erzeugten Audit-Trails überwachen und auswerten können.

_crossref:disks[disks,Speichermedien]_::
Erläutert den Umgang mit Speichermedien und Dateisystemen. Behandelt werden Plattenlaufwerke, RAID-Systeme, optische Medien, Bandlaufwerke, speicherbasierte Laufwerke und verteilte Dateisysteme.

_crossref:geom[geom,GEOM: Modulares Framework zur Plattentransformation]_::
Beschreibt das GEOM-Framework von FreeBSD sowie die Konfiguration der verschiedenen unterstützten RAID-Level.

_crossref:filesystems[filesystems,Dateisystemunterstützung]_::
Beschreibt die Unterstützung nicht-nativer Dateisysteme (beispielsweise des Z-Dateisystems (zfs) von Sun(TM)) durch FreeBSD.

_crossref:virtualization[virtualization,Virtualisierung]_::
Dieses Kapitel beschreibt verschiedene Virtualisierungslösungen und wie diese mit FreeBSD zusammenarbeiten.

_crossref:l10n[l10n,Lokalisierung – I18N/L10N einrichten und benutzen]_::
Zeigt wie Sie FreeBSD mit anderen Sprachen als Englisch einsetzen. Es wird sowohl die Lokalisierung auf der System-Ebene wie auch auf der Anwendungs-Ebene betrachtet.

_crossref:cutting-edge[updating-upgrading,FreeBSD aktualisieren]_::
Erklärt die Unterschiede zwischen FreeBSD-STABLE, FreeBSD-CURRENT und FreeBSD-Releases. Das Kapitel enthält Kriterien anhand derer Sie entscheiden können, ob es sich lohnt, ein Entwickler-System zu installieren und aktuell zu halten. Außerdem wird beschrieben, wie Sie ein System durch das Einspielen neuer Sicherheits-Patches absichern.

_crossref:dtrace[dtrace,DTrace]_::
Beschreibt, wie das von Sun(TM) entwickelte DTrace-Werkzeug unter FreeBSD konfiguriert und eingesetzt werden kann. Dynamisches Tracing kann Ihnen beim Aufspüren von Leistungsproblemen helfen, indem Sie Echtzeit-Systemanalysen durchführen.

_crossref:serialcomms[serialcomms,Serielle Datenübertragung]_::
Erläutert, wie Sie Terminals und Modems an Ihr FreeBSD-System anschließen und sich so ein- und auswählen können.

_crossref:ppp-and-slip[ppp-and-slip,PPP]_::
Erklärt wie Sie mit PPP, SLIP oder PPP über Ethernet ein FreeBSD-System mit einem entfernten System verbinden.

_crossref:mail[mail,Elektronische Post (E-Mail)]_::
Erläutert die verschiedenen Bestandteile eines E-Mail Servers und zeigt einfache Konfigurationen für sendmail, dem meist genutzten E-Mail-Server.

_crossref:network-servers[network-servers,Netzwerkserver]_::
Bietet ausführliche Informationen und Beispielkonfigurationen, die es Ihnen ermöglichen, Ihren FreeBSD-Rechner als Network File System Server, Domain Name Server, Network Information Server, oder als Zeitsynchronisationsserver einzurichten.

_crossref:firewalls[firewalls,Firewalls]_::
Erklärt die Philosophie hinter softwarebasierten Firewalls und bietet ausführliche Informationen zur Konfiguration der verschiedenen, für FreeBSD verfügbaren Firewalls.

_crossref:advanced-networking[advanced-networking,Weiterführende Netzwerkthemen]_::
Behandelt viele Netzwerkthemen, beispielsweise das Verfügbarmachen einer Internetverbindung für andere Rechner eines LANs, Routing, drahtlose Netzwerke, Bluetooth(R), IPv6, ATM und andere mehr.

_crossref:mirrors[mirrors,Bezugsquellen für FreeBSD]_::
Enthält eine Aufstellung der Quellen von denen Sie FreeBSD beziehen können: CD-ROM, DVD sowie Internet-Sites.

_crossref:bibliography[bibliography,Bibliografie]_::
Dieses Buch behandelt viele Themen und kann nicht alle Fragen erschöpfend beantworten. Die Bibliografie enthält weiterführende Bücher, die im Text zitiert werden.

_crossref:eresources[eresources,Ressourcen im Internet]_::
Enthält eine Aufstellung der Foren, die FreeBSD Benutzern für Fragen und Diskussionen zur Verfügung stehen.

_crossref:pgpkeys[pgpkeys,OpenPGP-Schlüssel]_::
Enthält PGP-Fingerabdrücke von etlichen FreeBSD Entwicklern.

[[preface-conv]]
== Konventionen in diesem Buch

Damit der Text einheitlich erscheint und leicht zu lesen ist, werden im ganzen Buch die nachstehenden Konventionen beachtet:

[[preface-conv-typographic]]
===  Typographie

_Kursiv_::
Für Dateinamen, URLs, betonte Teile eines Satzes und das erste Vorkommen eines Fachbegriffs wird ein _kursiver_ Zeichensatz benutzt.

`Fixschrift`::
Fehlermeldungen, Kommandos, Umgebungsvariablen, Namen von Ports, Hostnamen, Benutzernamen, Gruppennamen, Gerätenamen, Variablen und Code-Ausschnitte werden in einer `Fixschrift` dargestellt.

Fett::
*Fett* kennzeichnet Anwendungen, Kommandozeilen und Tastensymbole.

[[preface-conv-commands]]
=== Benutzereingaben

Tasten werden *fett* dargestellt, um sie von dem umgebenden Text abzuheben. Tasten, die gleichzeitig gedrückt werden müssen, werden durch ein `+` zwischen den einzelnen Tasten dargestellt:

kbd:[Ctrl+Alt+Del]

Im gezeigten Beispiel soll der Benutzer die Tasten kbd:[Ctrl], kbd:[Alt] und kbd:[Del] gleichzeitig drücken.

Tasten, die nacheinander gedrückt werden müssen, sind durch Kommas getrennt:

kbd:[Ctrl+X], kbd:[Ctrl+S]

Das letzte Beispiel bedeutet, dass die Tasten kbd:[Ctrl] und kbd:[X] gleichzeitig betätigt werden und danach die Tasten kbd:[Ctrl] und kbd:[S] gleichzeitig gedrückt werden müssen.

[[preface-conv-examples]]
=== Beispiele

Beispiele, die durch [.filename]#C:\># eingeleitet werden, zeigen ein MS-DOS(R) Kommando. Wenn nichts Anderes angezeigt wird, können diese Kommandos unter neuen Versionen von Microsoft(R) Windows(R) auch in einem DOS-Fenster ausgeführt werden.

[source,bash]
....

E:\> tools\fdimage floppies\kern.flp A:
....

Beispiele, die mit # beginnen, müssen unter FreeBSD mit Superuser-Rechten ausgeführt werden. Dazu melden Sie sich entweder als `root` an oder Sie wechseln von Ihrem normalen Account mit man:su[1] zu dem Benutzer `root`.

[source,bash]
....
# dd if=kern.flp of=/dev/fd0
....

Beispiele, die mit % anfangen, werden unter einem normalen Benutzer-Account ausgeführt. Sofern nichts Anderes angezeigt wird, verwenden die Beispiele die Syntax der C-Shell.

[source,bash]
....
% top
....

[[preface-acknowledgements]]
== Danksagung

Dieses Buch ist aus Beiträgen von vielen Leuten aus allen Teilen der Welt entstanden. Alle eingegangen Beiträge, zum Beispiel Korrekturen oder vollständige Kapitel, waren wertvoll.

Einige Firmen haben dieses Buch dadurch unterstützt, dass Sie Autoren in Vollzeit beschäftigt und die Veröffentlichung des Buchs finanziert haben. Besonders BSDi (das später von http://www.windriver.com[Wind River Systems] übernommen wurde) beschäftigte Mitglieder des FreeBSD Documentation Projects, um dieses Buch zu erstellen. Dadurch wurde die erste (englische) gedruckte Auflage im März 2000 möglich (ISBN 1-57176-241-8). Wind River Systems bezahlte dann weitere Autoren, die die zum Drucken nötige Infrastruktur verbesserten und zusätzliche Kapitel beisteuerten. Das Ergebnis dieser Arbeit ist die zweite (englische) Auflage vom November 2001 (ISBN 1-57176-303-1). Zwischen 2003 und 2004 bezahlte http://www.freebsdmall.com[FreeBSD Mall, Inc] mehrere Mitarbeiter für die Vorbereitung der gedruckten dritten Auflage.
