# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
# $FreeBSD$
# $FreeBSDde: de-www/docproj/Makefile,v 1.3 2007/01/16 20:32:55 jkois Exp $
# basiert auf: 1.11


.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	doc-set.xml
DOCS+=	docproj.xml
DOCS+=	sgml.xml
DOCS+=	submitting.xml
DOCS+=	who.xml

INDEXLINK= docproj.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
