---
title: "FreeBSD X.0 Release Process"
sidenav: download
---

= FreeBSD {localRel} Release Process
:localRel: X.0
:localBranchHead: head
:localBranchStable: stable/X
:localBranchReleng: releng/X.0

include::shared/en/urls.adoc[]

== Introduction

This is the release schedule for FreeBSD {localRel}.
For more information about the release engineering process, please see the link:../../../releng/[Release Engineering] section of the web site.

General discussions about the pending release and known issues should be sent to the public mailto:FreeBSD-current@FreeBSD.org[freebsd-current] mailing list.

// link:{handbook}glossary/#mfc-glossary[MFC] requests are no longer being accepted for {localBranchReleng}.

// link:{handbook}glossary/#mfc-glossary[MFC] requests should be sent to re@FreeBSD.org.

== Schedule

During the {localBranchHead} freeze, the Release Engineering Team may create ALPHA snapshots to publish for testing purposes.
As the frequency and total number of the ALPHA snapshots will depend on the length of time the {localBranchHead} branch is frozen, no official schedule is provided.

Announcements regarding the availability of the ALPHA snapshots will be sent to the mailto:freebsd-current@FreeBSD.org[freebsd-current] and mailto:freebsd-snapshots@FreeBSD.org[freebsd-snapshots] mailing lists.

[.tblbasic]
[cols=",,,",options="header",]
|===
|Action |Expected |Actual |Description

|===

"*" indicates "as-needed" items.

////
== Status / TODO
link:todo/[FreeBSD Release Engineering TODO Page]
////

== Additional Information

* link:../../../releng/[FreeBSD Release Engineering website]
