# $Id: Makefile,v 1.3 1998-08-03 09:51:12 wosch Exp $

DOCS=   current.sgml 
DOCS+=	doc-set.sgml
DOCS+=  sgml.sgml
DOCS+=  submitting.sgml
DOCS+=  who.sgml 
DOCS+=  translations.sgml
DOCS+=	docproj.sgml

.include "../web.mk"
