# $Id: Makefile,v 1.5 1998-08-11 01:18:36 wosch Exp $

.if exists("../Makefile.conf")
.include "../Makefile.conf"
.endif

DOCS=   current.sgml 
DOCS+=	doc-set.sgml
DOCS+=  sgml.sgml
DOCS+=  submitting.sgml
DOCS+=  who.sgml 
DOCS+=  translations.sgml
DOCS+=	docproj.sgml

INDEXLINK= docproj.html

.include "../web.mk"
