---
title: "Communiqué de presse FreeBSD : 31 Octobre 2002"
sidenav: about
loadPress: false
---

= Communiqué de presse FreeBSD : 31 Octobre 2002

== Le Démon de l'Opéra : Opera Software sort une version pour FreeBSD

*Oslo, Norvège, 31 Octobre 2002 :* Opera Software est fier d' annoncer la première version "Or" de son nouveau port pour le système de type UNIX FreeBSD. Avec cette version pour FreeBSD, Opera est maintenant disponible sur huit systèmes d'exploitation différents.

Le système d'exploitation BSD (Berkeley Software Distribution) trouve ses origines à l'Université de Californie, Berkeley. Il a commencé sa carrière en tant que supplément à UNIX, mais il a évolué au fil du temps en plusieurs systèmes d'exploitation. Parmi ces différentes variantes de BSD, la plus largement distribuée est FreeBSD, très populaire parmi les utilisateurs expérimentés comme les administrateurs systèmes qui recherchent un système rapide et fiable.

"Les utilisateurs d'Opera et de FreeBSD ont ceci de commun qu'ils mettent en avant, et s'attendent à trouver, la stabilité et la fiabilité. Ce point commun entre FreeBSD et Opera devrait plaire à de nombreux clients professionnels." déclare Jon S. von Tetzchner, CEO, Opera Software ASA. "A un niveau plus personnel, je suis également heureux d'accueillir les utilisateurs FreeBSD dans la famille Opera. FreeBSD n'est pas uniquement un système d'exploitation, c'est aussi une communauté et une philosophie avec des valeurs qui, je le sais, sont en accords avec les notres."

La communauté FreeBSD est enthousiaste à l'idée de pouvoir enfin surfer avec Opera.

"Avec la sortie de Opera pour FreeBSD, les utilisateurs FreeBSD qui téléchargent Opera pour FreeBSD peuvent surfer sur le web avec l'un des navigateurs les plus rapides du marché," déclare Robert Watson, membre de l'équipe principale FreeBSD. "La réputation de FreeBSD comme système d'exploitation fiable et rapide pour les postes bureautiques s'étend de plus en plus et nous sommes heureux de voir que Opera Software nous aide à créer un environnement bureautique encore plus complet."

Opera 6.1 pour FreeBSD peut être téléchargé sur http://www.opera.com/[www.opera.com].

== A propos de Opera Software

Opera Software ASA est une société leader dans le développement de navigateurs Web pour les marchés de la bureautique et de l'embarqué. Elle est partenaire de sociétés comme IBM, AMD, Symbian, Canal+ Technologies, Ericsson, Sharp et Lineo (maintenant division de Embedix). Le navigateur Opera a été reconnu internationalement aussi bien par les utilisateurs que par la presse spécialisée comme étant plus rapide, moins gourmand en ressources et plus respectueux des standards que les autres navigateurs. Opera est disponible pour Windows, Mac, Linux, Solaris, FreeBSD, OS/2, Symbian OS et QNX. Opera Software ASA est une société privée dont le siège se situe à Oslo, Norvège. Pour en savoir plus sur Opera, vous pouvez consulter le site http://www.opera.com/[www.opera.com].

== A propos du système d'exploitation "Berkeley Software Distribution"

Les technologies du système BSD ("Berkeley Software Distribution") ont été à l'origine développées entre 1979 et 1992 par le "Computer Systems Research Group (CSRG)" à l'Université de Californie à Berkeley. Les technologies systèmes et réseaux dérivées de Berkeley sont au coeur des systèmes Unix et apparentés les plus modernes. Actuellement, tous les grandsd fournisseurs d'infrastructures Internet utilisent virtuellement des systèmes d'exploitation BSD. Les technologies du système BSD sont utilisées dans d'importants projets où la partie réseau est critique et sont embarquées dans des plates-formes Internet qui nécessitent des fonctions Internet avancées, une excellente fiabilité et une très bonne sécurité.

== A propos du Projet FreeBSD

FreeBSD est un système d'exploitation open-source très populaire développé par le Projet FreeBSD et toute une équipe de personnes répartie dans le monde entier qui consiste en plus de 5000 développeurs qui coordonnent leurs travaux via 185 développeurs "committers" (N.d.T.: développeurs pouvant modifier le code source). Il est disponible gratuitement sur le site ftp://ftp.FreeBSD.org/[ftp.FreeBSD.org] et est aussi distribué en CDs/DVDs chez CompUSA, Fry's, Borders, Ingram, FreeBSDmall.com et d'autres. FreeBSD inclue des milliers d'applications dont des logiciels bureautiques, "groupware" et multimédia. Il est largement utilisé par des sociétés du monde entier en tant que serveur web, serveur de fichiers, firewall et routeur. FreeBSD est distribué sous licence "Berkeley Software Distribution", ce qui signifie qu'il peut être copié et modifié librement y compris dans un but commercial. Pour plus d'informations à propos du Projet FreeBSD, visitez le site http://www.FreeBSD.org/[www.FreeBSD.org].

== Contacts Presse

Opera Software +
Pal A. Hvistendahl +
Marcom Director +
Tél: +47 99 72 43 31 +
Fax: +47 24 16 40 01 +
pal@opera.com +
Numéro vert aux USA : 1-888-624-4846, uniquement la presse svp

Le projet FreeBSD +
press@FreeBSD.org
