---
title: "FreeBSD - revue de presse : 29 avril 1999"
sidenav: about
loadPress: false
---

= FreeBSD - revue de presse : 29 avril 1999

== Un système complet de développement XML intégré avec FreeBSD

*Concord, CA, 29 avril 1999* : FreeBSD 3.1 contient un système de développement SGML/XML intégré complet et qui s'installe très facilement.

Le système de logiciels portés et l'architecture multitâche de FreeBSD rendent facile pour un développeur SGML/XML le téléchargement et l'installation des dernières versions des outils et des documents de référence dont il a besoin pour développer en SGML et XML; et les listes de diffusion Internet en ligne pourront l'aider à apprendre et à rester à jour avec les évolutions des implémentations XML.

FreeBSD est un système d'exploitation open-source complet qui fonctionne sur pratiquement tous les ordinateurs personnels à base de processeurs Intel x86. Son "manuel de référence" de 580 pages a été récemment achevé au format DocBook, vivant exemple d'un document évolutif construit avec les outils SGML. Ce manuel de référence est disponible, en anglais, sur Internet :

* http://www.FreeBSD.org/handbook/
* ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/

Le Projet de Documentation de FreeBSD met aussi à disposition une "Introduction au Projet de Documentation FreeBSD pour les nouveaux participants" qui permet aux nouveaux participants de contribuer, sans douleur, à la documentation de FreeBSD. La plupart des informations de cette introduction peuvent s'appliquer à tous les utilisateurs de SGML/XML et est disponible librement. Elle est constamment remise à jour par l'équipe du Projet de Documentation et se trouve sur :

* http://www.FreeBSD.org/tutorials/primer/

=== Les fonctionnalités majeures du Système SGML/XML du Projet de Documentation comprennent :

* Jade 1.2.1 de James Clark et la suite SP version 1.3.3, qui permet le formatage et la validation des documents SGML et XML.
* Un ensemble complet de 19 jeux d'entités de caractères ISO SGML.
* Le DocBook (v2.4.1, v3.0, v3.1), HTML (toutes versions) et les définitions des documents LinuxDoc (DTD).
* Des feuilles de styles DocBook modulaires, par Norm Walsh, permettant un contrôle fin de l'apparence et du formatage des documents DocBook.
* Emacs et XEmacs, associés au paquetage d'extension PSGML, fournissent une solution personnalisable et professionnelle d'édition SGML.
* Le paquetage teTeX-beta, associé aux macros JadeTeX, permet de convertir des documents DocBook en DVI, PostScript et PDF avec hyper-liens intégrés.
* D'autres logiciels et utilitaires SGML se trouvent au catalogue des logiciels portés sous FreeBSD.

Le Projet de Documentation FreeBSD migre activement du DTD de LinuxDoc à celui du DocBook et a fait des propositions aux responsables du DocBook au sujet de nouvelles fonctions et de possibles implémentations l'année passée. Pour plus d'informations sur le Projet de Documentation FreeBSD, veuillez contacter la liste de diffusion freebsd-doc@FreeBSD.org.

Le système d'exploitation FreeBSD est disponible sur Internet depuis le site officiel de FreeBSD et sur de nombreux sites miroirs répartis à travers le monde. Il peut aussi être obtenu sur cédéroms auprès de Walnut Creek CDROM. Plus d'informations sont disponibles sur :

* http://www.FreeBSD.org/
* http://www.cdrom.com/
