---
title: "Communiqué de presse FreeBSD : 9 Mars 2000"
sidenav: about
loadPress: false
---

= Communiqué de presse FreeBSD : 9 Mars 2000

== POUR DIFFUSION IMMEDIATE

== DES FOURNISSEURS BSD FUSIONNENT POUR DIFFUSER LE SYSTEME D'EXPLOITATION POUR INTERNET LE PLUS POPULAIRE DU MONDE

=== La nouvelle société BSDI va diffuser les technologies du système d'exploitation BSD et épauler la communauté "Open Source" FreeBSD dans sa croissance rapide.

*Colorado Springs, Colorado, 9 Mars 2000:* Berkeley Software Design, Inc. (BSDI) a annoncé aujourd'hui sa fusion avec Walnut Creek CDROM, qui distribue le celèbre système d'exploitation FreeBSD. Avec cette fusion, la nouvelle société BSDI rassemble les principaux développeurs et fournisseurs du système d'exploitation de Berkeley Software Distribution. BSDI développera et fournira des systèmes d'exploitation et des plate-formes Internet BSD(R), tout en fournissant technologie, support et assistance au Projet FreeBSD, logiciel libre.

Les systèmes d'exploitation BSD sont au coeur des plus gros sites Internet et sont employés par les plus gros fournisseurs de services, dont Yahoo!, Hotmail de Microsoft et UUNET, une société de MCI WorldCom. BSD et Linux sont actuellement les systèmes d'exploitation en plus forte croissance, selon Survey.com, la principale société d'"eRecherche".

Le système d'exploitation BSD et ses technologies réseau et Internet ont acquis une reconnaissance étendue dans l'infrastructure Internet. Plus de 100,000 utilisateurs commerciaux Internet utilisent des systèmes d'exploitation BSD sur plus de 2,000,000 serveurs BSD. On estime que 9 Fournisseurs d'Accès Internet - Internet Service Providers (ISP) - et Fournisseurs d'Accès Réseau - Network Service Providers (NSP) - sur 10, et 15 pour 100 des sites Internet, utilisent des systèmes BSD. Les systèmes d'exploitation BSD sont aussi incorporés à des solutions Internet integrées produites par Intel, IBM, Lucent, F5 Labs, Hitachi et bien d'autres.

BSDI a aussi annoncé que Yahoo! Inc. apportera son soutien financier à la nouvelle société. BSDI utilisera cette participation pour rapprocher les innovations du logiciel libre des exigences commerciales. Elle servira à renforcer la position dominante de BSDI comme fournisseur du plus évolué des systèmes d'exploitation pour l'infrastructure Internet.

BSDI souhaite créer un front uni pour les systèmes d'exploitation BSD. La société distribuera, supportera et améliorera aussi bien BSD/OS que FreeBSD. BSDI et le Projet FreeBSD évaluent ensemble la technologie et les besoins du marché en vue de fusionner les codes des deux systèmes d'exploitation.

== Le nouveau chef de file BSDI

"Les technologies BSD ont un long historique de développements avancées qui sont au coeur de l'Internet," a déclaré le Dr. Marshall Kirk McKusick, président de BSDI. "La nouvelle BSDI enrichira encore la populaire plate-forme BSD, qui est déjà largement déployée à travers le monde." McKusick fut un des fondateur du Computer Systems Research Group (CSRG) de l'Université de Californie à Berkeley et est unaniment reconnu comme un des participants clés aux débuts du mouvement du logiciel libre.

Pour mener la nouvelle vision de BSDI, ses plans et sa croissance continue, Gary J. Johnson a été nommé directeur. Johnson est un dirigeant expérimenté dans le domaine technologique, qui a occupé divers postes de gestion, vente, marketing et de responsable d'opération dans des compagnies phares de la Silicon Valley dont Tandem Computers (Compaq), Convergent Technologies (Unisys) et SCO. Johnson était dernièrement président de ClickService Software, un fournisseur majeur de logiciel d'e-commerce et de gestion des relations clientèle (Customer Relationship Management - CRM).

"L'innovation sur le terrain des systèmes d'exploitation s'appuie principalement sur le travail de la communauté du logiciel libre," a dit Johnson. "Aujourd'hui, les fournisseurs Linux, tels Red Hat Software et VA Linux, ont attiré l'attention de tous sur l'approche de développement du logiciel libre. Au coeur de l'Internet, toutefois, les technologies BSD sont partout. Le nouveau BSDI travaillera étroitement avec la communauté du logiciel libre pour garantir que les systèmes d'exploitation et plate-formes BSD avancés continuent à répondre à la demande toujours croissante de serveurs Internet, d'applications, de systèmes intégrés et autres éléments vitaux pour l'infrastructure Internet."

En plus de ses responsabilités actuelles, Mike Karels, vice-directeur de l'ingénierie de BSDI, ancien architecte système en chef et programmeur principal pour le CSRG de l'Université de Californie à Berkeley, projette de rejoindre l'équipe d'architectes du Projet. Karels, qui a remplacé le co-fondateur de Sun Microsystems Bill Joy au CSRG, est reconnu comme l'un des plus éminents développeurs des internes d'Unix et du logiciel réseau TCP/IP au monde.

"Les technologies BSD ont contribué au succès continu de Yahoo! en apportant la fiabilité et la qualité de service nécessaire pour assurer la disponibilité et l'evolutivité dont nous avons besoin pour que Yahoo! fonctionne sans interruption, quelque soit la demande croissante des utilisateurs," a déclaré David Filo, co-fondateur et président de Yahoo! Inc.

== BSDI continue à distribuer BSD/OS et FreeBSD et étend et accélère les initiatives logiciel libre de FreeBSD

Le nouveau BSDI vendra et supportera FreeBSD, BSD/OS, BSDI Internet Super Server et une ligne de produits BSD à valeur ajouté via ses réseaux mondiaux de distribution aux fournisseurs d'infrastructure Internet, développeurs de solutions intégrées et utilisateurs professionnels. BSDI fournira des systèmes d'exploitation BSD et des applications associées, avec un support commercial, des plate-formes intégrées pour Internet, le support et des services techniques, développera du logiciel libre, et fournira des prestations de conseil. La société offrira ses technologies Internet et réseau BSD sur les principales architectures de microprocesseur, dont Intel, SPARC, Alpha, PowerPC et StrongARM.

BSDI continuera a développer, améliorer et distribuer BSD/OS et FreeBSD sous les termes de la licence logicielle Berkeley, non restrictive et favorable aux utilisations commerciales, qui encourage le développement de projets de logiciel libre, systèmes embarqués, applications spécialisées, solutions intégrées et autres produits basés sur un système d'exploitation.

BSDI étendra et accélérera les initiatives logiciel libre FreeBSD de Walnut Creek CDROM en partageant les innovations techniques de BSD/OS avec le Projet FreeBSD et en fournissant à ce projet de logiciel libre un support technique et opérationnel, le marketing et des fonds. BSDI continuera à distribuer les versions prêtes à l'emploi de FreeBSD et projette aussi de développer des produits à valeur ajoutée autour de FreeBSD, ainsi que de fournir support technique, conseil et formation aux utilisateurs de FreeBSD. Ces initiatives devraient promouvoir et encourager le mouvement de logiciel libre BSD. Le Projet FreeBSD développe le célébre système d'exploitation FreeBSD et rassemble et intègre les contributions en logiciel de plus de 5.000 développeurs dans le monde entier.

== Les chefs de file de l'Internet et du Logiciel Libre supportent le nouveau BSDI

"Nous nous réjouissons que BSDI épaule la communauté logiciel libre FreeBSD," a dit Jordan Hubbard, principal promoteur et co-fondateur du Projet FreeBSD. "La nouvelle société BSDI dispose d'une expertise considérable de commercialisation, maintenance, distribution et support du plus avancé des systèmes d'exploitation Internet au monde. Nous sommes enthousiasmés et impatients de coopérer avec les principaux développeurs de BSDI, et notamment Mike Karels et les autres membres de l'équipe d'origine du CSRG de l'UC Berkeley's, pour accélerer l'innovation dans le domaine des systèmes d'exploitation, du réseau et d'Internet."

"Les systèmes d'exploitation libres comme BSD apporte à l'utilisateur une meilleure technologie et plus de choix," a déclaré Eric Raymond, président de l'"Open Source Initiative". "Je m'attends à ce que BSDI prouve une fois de plus que la communauté du logiciel libre et la communauté professionnelle prouvent une fois de plus qu'elles peuvent faire de grandes choses ensemble et pousser l'industrie de façon aussi spectaculaire que l'Internet."

"Nos investigations montrent que BSD et Linux vont augmenter leur présence sur les serveurs d'entreprise de 100 à 500 pour cent dans les deux années à venir pour les applications essentielles dans les entreprises américaines," a dit Dave Trowbridge, analyste senior chez Survey.com. "Cette nouvelle société contribuera à garantir que BSD ait sa place au soleil, ce que méritent son riche héritage et ses solides fondations technologiques."

== A propos du système d'exploitation "Berkeley Software Distribution"

Les technologies du système d'exploitation Berkeley Software Distribution ont été développées à l'origine de 1979 à 1992 par le "Computer Systems Research Group" (CSRG) de l'Université de Californie à Berkeley. Des dérivés de ces technologies de système d'exploitation et réseau de Berkeley sont au coeur de la plupart des systèmes d'exploitation Unix et apparentés modernes. Aujourd'hui, pratiquement tous les grands fournisseurs d'infrastructure Internet utilisent des systèmes d'exploitation BSD. Les technologies du système d'exploitation BSD sont utilisés dans la plupart des principaux environnements informatiques critiques et sont embarquées dans des plate-formes Internet intégrées qui ont besoin de fonctionnalités Internet avancées, en même temps que de fiabilité et de sécurité.

== A propos du Projet FreeBSD

FreeBSD est un système d'exploitation libre populaire développé par le Projet FreeBSD et son équipe répartie dans le monde entier, et constituée de plus de 5,000 développeurs dont le travail est intégré par 185 développeurs "soumetteurs". Il est disponible gratutement sur ftp.FreeBSD.org et est aussi distribué sous forme de produit logiciel "packagé" par CompUSA, Fry's, Borders, Ingram, FreeBSDmall.com et d'autres. FreeBSD incorpore des milliers d'applications portées, dont les plus populaires logiciels Web, Internet et E-mail. FreeBSD est distribué sous les termes de la licence Berkeley Software Distribution, ce qui signifie qu'il peut être librement copié et modifié. Pour plus d'informations sur le Projet FreeBSD, visitez http://www.FreeBSD.org/[www.FreeBSD.org].

== A propos de Walnut Creek

Walnut Creek CDROM a été créé en 1991 et a commencé à publier du logiciel Linux en 1992, et du logiciel BSD en 1993. La société a une longue histoire de coopération étroite avec la communauté du logiciel libre, apportant finances, compétences et autres ressources aux projets "Open Source". Walnut Creek CDROM publie de nombreux logiciels, dont FreeBSD et Slackware, la plus BSD des versions de Linux.

A propos de Berkeley Software Design, Inc. (BSDI)

Les principaux développeurs de BSD ont créé Berkeley Software Design, Inc. en 1991 pour commercialiser les technologies BSD et prolonger la tradition Berkeley Unix de systèmes d'exploitation réseau et Internet robustes, fiables et extrèmement sûrs. En fusionnant Berkeley Software Design, Inc. et Walnut Creek CDROM, BSDI devient le premier fournisseur mondial de systèmes d'exploitation Internet avancés pour l'infrastructure Internet. Vous pouvez contacter BSDI à info@BSDI.com ou sur http://www.BSDI.com/[www.BSDI.com] ou par téléphone au 1-719-593-9445 (numéro vert : 1-800-800-4273).

== # # #

BSD est une marque déposée et BSD/OS et BSDI sont des marques déposées de Berkeley Software Design, Inc. Yahoo! et le logo Yahoo! sont des marques déposées de Yahoo! Inc. Toutes les autres marques citées sont la propriété de leurs détenteurs respectifs.

Contacts : +
Kevin Rose +
BSDI +
801-553-8166 +
kgr@bsdi.com

Jordan Hubbard +
FreeBSD Project +
925-691-2863 +
jkh@FreeBSD.org

Brigid Fuller +
ZNA Communications +
831-425-1581 +
brigid@zna.com

 +

== Note du Traducteur :

Cette traduction est publiée sous réserves et à titre informatif. N'étant ni juriste, ni financier, certains aspects du document original ont pu m'échapper ou être mal interprétés. Merci au besoin de consulter l'original sur %3Ehttp://www.freebsd.org/news/press-rel-4.html[http://www.freebsd.org/news/press-rel-4.html]. +
