---
title: Πρόλογος
prev: books/handbook/
next: books/handbook/parti
---

[preface]
[[book-preface]]
= Πρόλογος
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums!:
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Πίνακας Περιεχομένων
:table-caption: Πίνακας
:figure-caption: Σχήμα
:example-caption: Παράδειγμα
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:

[[preface-audience]]
== Σε Ποιους Απευθύνεται Αυτό το Βιβλίο

Το πρώτο τμήμα αυτού του βιβλίου, οδηγεί τον νέο χρήστη στη διαδικασία εγκατάστασης του FreeBSD και τον εισάγει ομαλά στη φιλοσοφία και τον σχεδιασμό του UNIX(R). Αυτό το τμήμα δεν έχει ιδιαίτερες απαιτήσεις. Αρκεί μόνο η διάθεση για εξερεύνηση ενός νέου συστήματος και η δυνατότητα αφομοίωσης των γνώσεων για το FreeBSD καθώς αυτές εισάγονται σταδιακά.

Αφού διαβάσετε το πρώτο τμήμα, το δεύτερο, κατά πολύ μεγαλύτερο τμήμα, περιλαμβάνει μια εκτενή αναφορά σε διάφορα θέματα που ενδιαφέρουν τους διαχειριστές συστημάτων FreeBSD. Μερικά από αυτά τα κεφάλαια είναι ευκολότερο να τα κατανοήσετε αν έχετε ήδη μελετήσει συγκεκριμένα τμήματα του βιβλίου. Όπου χρειάζεται κάτι τέτοιο, θα αναφέρεται στη σύνοψη του κεφαλαίου που μόλις ξεκινήσατε να διαβάζετε.

Για περισσότερες πηγές πληροφοριών, δείτε το crossref:bibliography[bibliography,Βιβλιογραφία].

[[preface-changes-from3]]
== Αλλαγές από την Τρίτη Έκδοση

Η τρέχουσα έκδοση του Εγχειριδίου στο διαδίκτυο, είναι το αποτέλεσμα της προσπάθειας πολλών εκατοντάδων εθελοντών στο διάστημα των τελευταίων 10 χρόνων. Οι πιο σημαντικές αλλαγές σε σχέση με την τρίτη έντυπη έκδοση του Εγχειριδίου (2004) φαίνονται παρακάτω:

* Το crossref:dtrace[dtrace,DTrace] είναι ένα νέο κεφάλαιο με πληροφορίες σχετικά με αυτό το πανίσχυρο εργαλείο ανάλυσης απόδοσης.
* Το crossref:filesystems[filesystems,Υποστήριξη Συστημάτων Αρχείων] είναι ένα νέο κεφάλαιο με πληροφορίες για συστήματα αρχείων τα οποία υποστηρίζονται από το FreeBSD αλλά αναπτύσσονται από άλλες ομάδες, όπως το ZFS από την Sun(TM).
* Το crossref:audit[audit,Έλεγχος Συμβάντων Ασφαλείας] είναι ένα νέο κεφάλαιο με πληροφορίες σχετικά με τις νέες δυνατότητες και την χρήση του auditing στο FreeBSD.
* Το crossref:virtualization[virtualization,Εικονικοποίηση] είναι ένα νέο κεφάλαιο με πληροφορίες σχετικά με την εγκατάσταση του FreeBSD σε λογισμικό εκτέλεσης εικονικών (virtual) μηχανημάτων.
* Το crossref:bsdinstall[bsdinstall,Εγκατάσταση του FreeBSD 9.x και Μεταγενέστερων Εκδόσεων] FreeBSD 9._x_ και Μεταγενέστερων Εκδόσεων, είναι ένα νέο κεφάλαιο σχετικά με την εγκατάσταση του FreeBSD με τη βοήθεια του νέου προγράμματος bsdinstall.

[[preface-changes-from2]]
== Αλλαγές από τη Δεύτερη Έκδοση (2004)

Η τρίτη έκδοση αυτού του βιβλίου ήταν το αποτέλεσμα της προσπάθειας περισσότερων από δύο χρόνων από τα μέλη της Ομάδας Τεκμηρίωσης του FreeBSD. Η έντυπη έκδοση είχε τόσο μεγάλο μέγεθος, που κρίθηκε αναγκαίο να τυπωθεί σε δύο χωριστούς τόμους. Παρακάτω φαίνονται οι σημαντικότερες αλλαγές σε αυτή τη νέα έκδοση:

* Το crossref:config[config-tuning,Ρύθμιση και Βελτιστοποίηση] επεκτάθηκε με νέες πληροφορίες για τη διαχείριση ενέργειας και πόρων του συστήματος μέσω ACPI, με περισσότερες πληροφορίες για το σύστημα `cron` και με περισσότερες επιλογές παραμετροποίησης του πυρήνα του FreeBSD.
* Το crossref:security[security,Ασφάλεια] επεκτάθηκε με νέες πληροφορίες για Δίκτυα VPN, για λίστες ελέγχου πρόσβασης αρχείων (ACLs) και περισσότερες συμβουλές σχετικά με την ασφάλεια του FreeBSD.
* Το crossref:mac[mac,Υποχρεωτικός Έλεγχος Πρόσβασης] είναι ένα νέο κεφάλαιο σε αυτή την έκδοση. Εξηγεί τι είναι ο μηχανισμός MAC και πώς μπορεί να χρησιμοποιηθεί για να ενισχυθεί η ασφάλεια ενός συστήματος FreeBSD.
* Το crossref:disks[disks,Αποθηκευτικά Μέσα] επεκτάθηκε, με νέες πληροφορίες για συσκευές αποθήκευσης USB, στιγμιότυπα συστήματος αρχείων (snapshots), περιορισμούς στη χρήση των συστημάτων αρχείων (quotas), συστήματα αρχείων που βασίζονται σε υπάρχοντα αρχεία ή στο δίκτυο, καθώς και κρυπτογραφημένες κατατμήσεις δίσκων.
* Προστέθηκε μια ενότητα σχετικά με την αντιμετώπιση προβλημάτων στο crossref:ppp-and-slip[ppp-and-slip,PPP και SLIP].
* Το crossref:mail[mail,Ηλεκτρονικό Ταχυδρομείο] επεκτάθηκε με νέες πληροφορίες για την χρήση εναλλακτικών MTA, πιστοποίηση ταυτότητας στο SMTP, το πρωτόκολλο UUCP, τα εργαλεία fetchmail και procmail και με άλλα θέματα για προχωρημένους.
* Το crossref:network-servers[network-servers,Εξυπηρετητές Δικτύου] περιλαμβάνεται για πρώτη φορά σε αυτή την έκδοση. Αυτό το κεφάλαιο περιγράφει πως να εγκαταστήσετε τον Διακομιστή HTTP Apache, τον εξυπηρετητή ftpd του FreeBSD και τον διακομιστή Samba για επικοινωνία με πελάτες Microsoft(R) Windows(R). Στο κεφάλαιο αυτό, έχουν μεταφερθεί κάποιες ενότητες από το crossref:advanced-networking[advanced-networking,Προχωρημένα Θέματα Δικτύωσης] (Προχωρημένα Θέματα Δικτύωσης), προκειμένου να βελτιωθεί η παρουσίαση τους.
* Το crossref:advanced-networking[advanced-networking,Προχωρημένα Θέματα Δικτύωσης] επεκτάθηκε με νέες πληροφορίες για τη χρήση συσκευών Bluetooth(R) στο FreeBSD, την εγκατάσταση ασύρματων δικτύων, και την Μέθοδο Δικτύωσης Ασύγχρονης Μεταφοράς (ATM).
* Προστέθηκε ένα Λεξιλόγιο, για να συγκεντρώσει όλους τους τεχνικούς όρους και τους διάφορους ορισμούς που περιέχονται σε ολόκληρο το βιβλίο.
* Έγιναν αισθητικές βελτιώσεις στους πίνακες και στα γραφήματα σε ολόκληρο το βιβλίο.

[[preface-changes]]
== Αλλαγές από την Πρώτη Έκδοση (2001)

Η δεύτερη έκδοση ήταν το αποτέλεσμα τουλάχιστον δύο χρόνων εργασίας από τα μέλη της Ομάδας Τεκμηρίωσης του FreeBSD. Οι πιο σημαντικές αλλαγές σε αυτή την έκδοση ήταν οι παρακάτω:

* Προστέθηκε ένα ολοκληρωμένο Ευρετήριο.
* Όλα τα γραφήματα σε ASCII αντικαταστάθηκαν από γραφικά διαγράμματα.
* Προστέθηκε μια τυποποιημένη σύνοψη σε κάθε κεφάλαιο, η οποία περιέχει μια σύντομη ανακεφαλαίωση των πληροφοριών που περιέχει το κεφάλαιο και τι αναμένεται να γνωρίζει από πριν ο αναγνώστης.
* Το περιεχόμενο αναδιοργανώθηκε σε τρία λογικά μέρη: "Ξεκινώντας με το FreeBSD", "Διαχείριση Συστήματος" και "Παραρτήματα".
* Το crossref:install[install,Εγκατάσταση του FreeBSD 8.x και Προγενέστερων Εκδόσεων] ξαναγράφτηκε από την αρχή με πολλές εικόνες, ώστε να διευκολύνει τους χρήστες να κατανοήσουν το κείμενο.
* Το crossref:basics[basics,Βασικές Έννοιες στο UNIX(R)] επεκτάθηκε ώστε να συμπεριλαμβάνει πρόσθετες πληροφορίες για τις διεργασίες (processes), τους δαίμονες (daemons), και τα σήματα (signals).
* Το crossref:ports[ports,Εγκατάσταση Εφαρμογών: Πακέτα και Ports] επεκτάθηκε ώστε να συμπεριλαμβάνει πρόσθετες πληροφορίες για την διαχείριση προμεταγλωττισμένων πακέτων (packages).
* Το crossref:x11[x11,Το Σύστημα X Window] ξαναγράφτηκε από την αρχή με έμφαση στην χρήση μοντέρνων τεχνολογιών, όπως τα περιβάλλοντα εργασίας KDE και GNOME σε XFree86(TM) 4.X.
* Το crossref:boot[boot,Η Διαδικασία Εκκίνησης του FreeBSD] επεκτάθηκε με περισσότερες πληροφορίες.
* Το crossref:disks[disks,Αποθηκευτικά Μέσα] ξαναγράφτηκε με βάση τα παλαιότερα δύο κεφάλαια "Δίσκοι" και "Αντίγραφα Ασφαλείας". Πιστεύουμε ότι τα θέματα αυτά είναι πιο ευκολονόητα όταν παρουσιάζονται μαζί σαν ένα κεφάλαιο. Προστέθηκε επίσης μια ενότητα για RAID (υλοποίηση μέσω υλικού ή λογισμικού).
* Το crossref:serialcomms[serialcomms,Σειριακές Επικοινωνίες] αναδιοργανώθηκε από την αρχή και ενημερώθηκε για τις εκδόσεις FreeBSD 4.X/5.X.
* Το crossref:ppp-and-slip[ppp-and-slip,PPP και SLIP] ενημερώθηκε σε σημαντικό βαθμό.
* Πολλοί νέοι τομείς προστέθηκαν στο crossref:advanced-networking[advanced-networking,Προχωρημένα Θέματα Δικτύωσης].
* Το crossref:mail[mail,Ηλεκτρονικό Ταχυδρομείο] επεκτάθηκε για να συμπεριλαμβάνει περισσότερες πληροφορίες για τις ρυθμίσεις του sendmail.
* Το crossref:linuxemu[linuxemu,Συμβατότητα με Εκτελέσιμα του Linux] επεκτάθηκε για να συμπεριλαμβάνει πληροφορίες για την εγκατάσταση της βάσης δεδομένων Oracle(R) και του SAP(R) R/3(R).
* Στην δεύτερη έκδοση καλύπτονται επίσης τα παρακάτω νέα θέματα:

** crossref:config[config-tuning,Ρύθμιση και Βελτιστοποίηση].
** crossref:multimedia[multimedia,Πολυμέσα].

[[preface-overview]]
== Οργάνωση Αυτού του Βιβλίου

Αυτό το βιβλίο χωρίζεται σε πέντε διακριτά λογικά τμήματα. Το πρώτο τμήμα, _Ξεκινώντας με το FreeBSD_, περιγράφει την εγκατάσταση και την βασική χρήση του FreeBSD. Ο προτεινόμενος τρόπος ανάγνωσης αυτού του τμήματος είναι ένα-ένα κεφάλαιο, με τη σειρά, προσπερνώντας κεφάλαια με γνωστά θέματα. Το δεύτερο τμήμα, _Βασικές Εργασίες_, περιγράφει μερικά χαρακτηριστικά του FreeBSD τα οποία χρησιμοποιούνται συχνά. Μπορείτε να διαβάσετε τα κεφάλαια σε αυτό το τμήμα (καθώς και σε όλα τα τμήματα που ακολουθούν) με όποια σειρά θέλετε. Κάθε κεφάλαιο ξεκινά με μια σαφή και σύντομη σύνοψη, η οποία περιγράφει τα περιεχόμενα του κεφαλαίου καθώς και τι χρειάζεται να γνωρίζει ήδη ο αναγνώστης. Αυτό επιτρέπει στον περιστασιακό αναγνώστη να προσπερνά γρήγορα ενότητες, για να βρει κεφάλαια τα οποία τον ενδιαφέρουν περισσότερο. Το τρίτο τμήμα, _Διαχείριση Συστήματος_, περιέχει θέματα σχετικά με τη διαχείριση συστημάτων FreeBSD. Το τέταρτο τμήμα, _Δικτυακές Επικοινωνίες_, καλύπτει θέματα δικτύωσης και διακομιστών. Το πέμπτο τμήμα περιέχει παραρτήματα με διάφορες πληροφορίες.

_crossref:introduction[introduction,Εισαγωγή]_::
Παρουσιάζει το FreeBSD στο νέο χρήστη. Περιγράφει την ιστορία του FreeBSD Project, τους στόχους του και το μοντέλο ανάπτυξης του.

_crossref:bsdinstall[bsdinstall,Εγκατάσταση του FreeBSD 9.x και Μεταγενέστερων Εκδόσεων]_::
Οδηγεί τον χρήστη στην διαδικασία εγκατάστασης του FreeBSD 9._x_ και μεταγενέστερων εκδόσεων με τη χρήση του bsdinstall.

_crossref:install[install,Εγκατάσταση του FreeBSD 8.x και Προγενέστερων Εκδόσεων]_::
Οδηγεί τον χρήστη στην διαδικασία εγκατάστασης του FreeBSD 8._x_ και προγενέστερων εκδόσεων με τη χρήση του sysinstall. Συμπεριλαμβάνονται επίσης μερικά θέματα εγκατάστασης για προχωρημένους, όπως η εγκατάσταση μέσω σειριακής κονσόλας.

_crossref:basics[basics,Βασικές Έννοιες στο UNIX(R)]_::
Περιέχει τις βασικές εντολές και λειτουργίες του λειτουργικού συστήματος FreeBSD. Εάν είστε εξοικειωμένος με το Linux(R) ή με άλλο λειτουργικό τύπου UNIX(R) μπορείτε πιθανώς να προσπεράσετε αυτό το κεφάλαιο.

_crossref:ports[ports,Εγκατάσταση Εφαρμογών: Πακέτα και Ports]_::
Περιγράφει τον τρόπο εγκατάστασης λογισμικού τρίτων κατασκευαστών με την καινοτόμο "Συλλογή των Ports (Ports Collection)" του FreeBSD και με τα συνήθη προμεταγλωττισμένα πακέτα (packages).

_crossref:x11[x11,Το Σύστημα X Window]_::
Περιγράφει γενικά το σύστημα X Window και ειδικότερα το X11 του FreeBSD. Επίσης περιγράφει ολοκληρωμένα περιβάλλοντα εργασίας όπως το KDE και το GNOME.

_crossref:desktop[desktop,Desktop Εφαρμογές]_::
Αναφέρει και εξηγεί μερικές από τις πιο συνήθεις εφαρμογές για υπολογιστές γραφείου, όπως προγράμματα πλοήγησης ιστοσελίδων και εφαρμογές γραφείου και περιγράφει πως να τις εγκαταστήσετε στο FreeBSD.

_crossref:multimedia[multimedia,Πολυμέσα]_::
Υποδεικνύει πως να εγκαταστήσετε δυνατότητες αναπαραγωγής ήχου και βίντεο στο σύστημα σας. Επίσης περιλαμβάνει δειγματοληπτικά κάποιες εφαρμογές ήχου και βίντεο.

_crossref:kernelconfig[kernelconfig,Ρυθμίζοντας τον Πυρήνα του FreeBSD]_::
Εξηγεί τους λόγους για τους οποίους θα πρέπει να δημιουργήσετε ένα νέο πυρήνα. Παρέχει, επίσης, λεπτομερείς οδηγίες για την ρύθμιση, μεταγλώττιση και εγκατάσταση του νέου σας προσαρμοσμένου πυρήνα.

_crossref:printing[printing,Εκτυπώσεις]_::
Περιγράφει πως να διαχειρίζεστε εκτυπωτές στο FreeBSD. Συμπεριλαμβάνει πληροφορίες για σελίδες λογοτύπων, λογαριασμούς εκτυπωτών και αρχικές ρυθμίσεις.

_crossref:linuxemu[linuxemu,Συμβατότητα με Εκτελέσιμα του Linux]_::
Περιγράφει τις δυνατότητες συμβατότητας του FreeBSD με εφαρμογές Linux(R). Επίσης παρέχει λεπτομερείς οδηγίες εγκατάστασης για πολλές γνωστές εφαρμογές του Linux(R) όπως Oracle(R), και Mathematica(R).

_crossref:config[config-tuning,Ρύθμιση και Βελτιστοποίηση]_::
Περιγράφει τις παραμέτρους που έχουν στη διάθεση τους οι διαχειριστές του συστήματος, ώστε να ρυθμίσουν ένα σύστημα FreeBSD για βέλτιστη απόδοση. Επίσης περιγράφει τα διάφορα αρχεία ρυθμίσεων που χρησιμοποιούνται στο FreeBSD και που να τα βρείτε.

_crossref:boot[boot,Η Διαδικασία Εκκίνησης του FreeBSD]_::
Περιγράφει την διαδικασία εκκίνησης του FreeBSD και εξηγεί πως μπορούμε να την ελέγχουμε με τη βοήθεια επιλογών και ρυθμίσεων.

_crossref:users[users,Χρήστες και Βασική Διαχείριση Λογαριασμών]_::
Περιγράφει την δημιουργία και την διαχείριση των λογαριασμών χρηστών. Επίσης περιγράφει τρόπους με τους οποίους μπορούν να τεθούν περιορισμοί στους χρήστες όσο αφορά τη χρήση πόρων του συστήματος, καθώς και άλλες λειτουργίες διαχείρισης λογαριασμών.

_crossref:security[security,Ασφάλεια]_::
Περιγράφει διάφορα διαθέσιμα εργαλεία που θα σας βοηθήσουν να κρατήσετε το FreeBSD σύστημα σας ασφαλές. Συμπεριλαμβάνονται οι υλοποιήσεις Kerberos, IPsec και OpenSSH.

_crossref:jails[jails,Jails]_::
Περιγράφει το πλαίσιο λειτουργιών των jails και τις βελτιώσεις που παρέχουν σε σχέση με την παραδοσιακή chroot υποστήριξη του FreeBSD.

_crossref:mac[mac,Υποχρεωτικός Έλεγχος Πρόσβασης]_::
Εξηγεί τι είναι ο Υποχρεωτικός Έλεγχος Πρόσβασης (MAC) και πως ο μηχανισμός αυτός μπορεί να χρησιμοποιηθεί για την ασφάλιση ενός FreeBSD συστήματος.

_crossref:audit[audit,Έλεγχος Συμβάντων Ασφαλείας]_::
Περιγράφει τι είναι ο Έλεγχος Συμβάντων, πως μπορεί να εγκατασταθεί, να ρυθμιστεί και πως μπορούν να διερευνώνται και να παρακολουθούνται τα ίχνη του ελέγχου (audit trails).

_crossref:disks[disks,Αποθηκευτικά Μέσα]_::
Περιγράφει πως να διαχειρίζεστε μέσα αποθήκευσης και συστήματα αρχείων με το FreeBSD. Συμπεριλαμβάνονται φυσικοί δίσκοι, συστοιχίες RAID, οπτικά και μαγνητικά μέσα, εικονικοί δίσκοι μνήμης και δικτυακά συστήματα αρχείων.

_crossref:geom[geom,GEOM: Διαχείριση Συστοιχιών Δίσκων]_::
Περιγράφει τι είναι το πλαίσιο λειτουργιών GEOM στο FreeBSD και πως να ρυθμίσετε διάφορα επίπεδα RAID που υποστηρίζονται στο FreeBSD.

_crossref:filesystems[filesystems,Υποστήριξη Συστημάτων Αρχείων]_::
Εξετάζει την υποστήριξη μη-εγγενών συστημάτων αρχείων στο FreeBSD, όπως το Z File System της Sun(TM).

_crossref:virtualization[virtualization,Εικονικοποίηση]_::
Περιγράφει τι προσφέρουν τα συστήματα εικονικοποίησης και πως μπορούν να χρησιμοποιηθούν με το FreeBSD.

_crossref:l10n[l10n,Τοπικές Ρυθμίσεις - Χρήση και ρύθμιση I18N/L10N]_::
Περιγράφει πως να χρησιμοποιήσετε το FreeBSD σε γλώσσες εκτός της Αγγλικής. Καλύπτει την δυνατότητα τοπικών ρυθμίσεων τόσο σε επίπεδο συστήματος, όσο και σε επίπεδο εφαρμογών.

_crossref:cutting-edge[updating-upgrading,Ενημέρωση και Αναβάθμιση του FreeBSD]_::
Εξηγεί τις διαφορές μεταξύ των εκδόσεων FreeBSD-STABLE, FreeBSD-CURRENT και των επίσημων (RELEASE) εκδόσεων του FreeBSD. Περιγράφει ποιοι χρήστες ωφελούνται όταν ακολουθούν ένα σύστημα ανάπτυξης καθώς και τα απαιτούμενα για αυτό το σκοπό βήματα. Καλύπτει τις μεθόδους που μπορούν να χρησιμοποιήσουν οι χρήστες για να ενημερώσουν το σύστημα τους με τις τελευταίες διορθώσεις ασφαλείας.

_crossref:dtrace[dtrace,DTrace]_::
Περιγράφει την ρύθμιση και χρήση του εργαλείου DTrace της Sun(TM) στο FreeBSD. Το δυναμικό tracing μπορεί να βοηθήσει στον εντοπισμό προβλημάτων απόδοσης, παρέχοντας ανάλυση του συστήματος σε πραγματικό χρόνο.

_crossref:serialcomms[serialcomms,Σειριακές Επικοινωνίες]_::
Εξηγεί πως να συνδέσετε τερματικά και μόντεμ στο FreeBSD σύστημα σας, για χρήση τόσο σε εισερχόμενες όσο και σε εξερχόμενες συνδέσεις.

_crossref:ppp-and-slip[ppp-and-slip,PPP και SLIP]_::
Περιγράφει πως να χρησιμοποιήσετε τις τεχνολογίες PPP, SLIP, ή PPP μέσω Ethernet για να συνδεθείτε σε απομακρυσμένα συστήματα με το FreeBSD.

_crossref:mail[mail,Ηλεκτρονικό Ταχυδρομείο]_::
Εξηγεί τα διαφορετικά στοιχεία ενός διακομιστή ηλεκτρονικής αλληλογραφίας και εμβαθύνει σε θέματα απλών ρυθμίσεων για το πλέον δημοφιλές λογισμικό διακομιστή ηλεκτρονικής αλληλογραφίας: το sendmail.

_crossref:network-servers[network-servers,Εξυπηρετητές Δικτύου]_::
Παρέχει λεπτομερείς οδηγίες και παραδείγματα αρχείων ρύθμισης για να ρυθμίσετε το FreeBSD να ενεργεί ως δικτυακός εξυπηρετητής αρχείων, εξυπηρετητής ονομάτων τομέα (DNS), εξυπηρετητής δικτυακών πληροφοριών (NIS), η εξυπηρετητής συγχρονισμού ώρας (NTP).

_crossref:firewalls[firewalls,Firewalls]_::
Εξηγεί την φιλοσοφία που κρύβεται πίσω από τα firewalls (τείχη προστασίας) που βασίζονται σε λογισμικό και παρέχει λεπτομερείς πληροφορίες για τις ρυθμίσεις των διαφόρων firewalls που διατίθενται για το FreeBSD.

_crossref:advanced-networking[advanced-networking,Προχωρημένα Θέματα Δικτύωσης]_::
Περιγράφει πολλά προχωρημένα θέματα δικτύωσης, συμπεριλαμβανομένου του διαμοιρασμού μιας σύνδεσης Internet με άλλους υπολογιστές στο τοπικό σας δίκτυο (LAN), θέματα δρομολόγησης για προχωρημένους, ασύρματη δικτύωση, Bluetooth(R), ATM, IPv6 και πολλά ακόμη.

_crossref:mirrors[mirrors,Που θα Βρείτε το FreeBSD]_::
Περιέχει λίστα με διάφορες πηγές για να αποκτήσετε το FreeBSD σε CD-ROM ή DVD, όπως επίσης και διάφορες τοποθεσίες στο Internet από όπου μπορείτε να κατεβάσετε και να εγκαταστήσετε το FreeBSD.

_crossref:bibliography[bibliography,Βιβλιογραφία]_::
Αυτό το βιβλίο αγγίζει πολλά διαφορετικά θέματα που μπορεί να σας κεντρίσουν το ενδιαφέρον για μια πιο λεπτομερή εξερεύνηση. Η βιβλιογραφία ταξινομεί σε κατηγορίες πολλά εξαιρετικά βιβλία τα οποία αναφέρονται στο κείμενο.

_crossref:eresources[eresources,Πηγές Πληροφόρησης στο Διαδίκτυο]_::
Περιγράφει πολλά φόρουμ που διατίθενται στους χρήστες του FreeBSD, ώστε να θέτουν ερωτήματα και να συμμετέχουν σε τεχνικές συζητήσεις για το FreeBSD.

_crossref:pgpkeys[pgpkeys,Κλειδιά PGP]_::
Καταγράφει τα δακτυλικά αποτυπώματα των κλειδιών PGP αρκετών μελών της Ομάδας Ανάπτυξης του FreeBSD.

[[preface-conv]]
== Συμβάσεις που χρησιμοποιούνται σε αυτό το βιβλίο

Σε ολόκληρο το βιβλίο, χρησιμοποιούνται κάποιες τυπογραφικές συμβάσεις ώστε η μορφοποίηση του να είναι συνεπής και να είναι πιο ευανάγνωστο:

[[preface-conv-typographic]]
=== Τυπογραφικές Συμβάσεις

_Πλάγια γραφή_::
Η _πλάγια_ γραμματοσειρά χρησιμοποιείται για ονόματα αρχείων, URLs, κείμενο με έμφαση και για χρήση πρωτοεμφανιζόμενων τεχνικών όρων.

`Γραφή σταθερού πλάτους`::
Η `σταθερού πλάτους` γραμματοσειρά χρησιμοποιείται για μηνύματα λάθους, εντολές, μεταβλητές περιβάλλοντος, ονομασίες των ports, ονόματα κεντρικών υπολογιστών, ονόματα χρηστών, ονόματα ομάδων, ονόματα συσκευών, μεταβλητές και αποσπάσματα κώδικα.

Έντονη γραφή::
Η έντονη γραμματοσειρά χρησιμοποιείται για εφαρμογές, εντολές και πλήκτρα.

[[preface-conv-commands]]
=== Είσοδος Δεδομένων από το Χρήστη

Η πληκτρολόγηση σημειώνεται με *έντονη* γραφή ώστε να ξεχωρίζει από το υπόλοιπο κείμενο. Συνδυασμοί πλήκτρων που πρέπει να πιεσθούν ταυτόχρονα σημειώνονται με `+`' μεταξύ των πλήκτρων, όπως:

kbd:[Ctrl+Alt+Del]

Το οποίο σημαίνει πως ο χρήστης θα πρέπει να πιέσει τα πλήκτρα kbd:[Ctrl], kbd:[Alt] και το πλήκτρο kbd:[Del] ταυτόχρονα.

Σε περίπτωση που κάποια πλήκτρα πρέπει να πιεσθούν με συγκεκριμένη σειρά, θα εμφανίζονται χωρισμένα με κόμματα:

kbd:[Ctrl+X], kbd:[Ctrl+S]

Το οποίο σημαίνει πως ο χρήστης αναμένεται να πιέσει τα πλήκτρα kbd:[Ctrl] και kbd:[X] ταυτόχρονα και έπειτα να πιέσει τα πλήκτρα kbd:[Ctrl] και kbd:[S] ταυτόχρονα.

[[preface-conv-examples]]
=== Παραδείγματα

Τα παραδείγματα που ξεκινούν με [.filename]#C:\># υποδηλώνουν μια εντολή MS-DOS(R). Αυτές οι εντολές μπορούν να εκτελούνται από το παράθυρο "Γραμμής Εντολών" σε σύγχρονο περιβάλλον Microsoft(R) Windows(R), εκτός αν αναφέρεται κάτι διαφορετικό.

[source,bash]
....
E:\> tools\fdimage floppies\kern.flp A:
....

Τα παραδείγματα που ξεκινούν με # υποδηλώνουν μια εντολή που θα πρέπει να εκτελεστεί από τον υπερχρήστη (superuser) ενός συστήματος FreeBSD. Μπορείτε να συνδεθείτε σαν χρήστης `root` για να πληκτρολογήσετε την εντολή, ή να συνδεθείτε σαν κανονικός χρήστης και να χρησιμοποιήσετε την εντολή man:su[1] ώστε να αποκτήσετε προνόμια υπερχρήστη.

[source,bash]
....
# dd if=kern.flp of=/dev/fd0
....

Τα παραδείγματα που ξεκινούν με % υποδηλώνουν μια εντολή που πρέπει να εκτελεστεί από ένα κανονικό χρήστη. Χρησιμοποιείται η σύνταξη C-shell για να θέσουμε μεταβλητές περιβάλλοντος και άλλες εντολές κελύφους, εκτός αν αναφέρεται κάτι διαφορετικό.

[source,bash]
....
% top
....

[[preface-acknowledgements]]
== Ευχαριστίες

Το βιβλίο που κρατάτε, παρουσιάζει τις προσπάθειες πολλών εκατοντάδων ανθρώπων από όλο τον κόσμο. Είτε μας ενημέρωσαν για τυπογραφικά λάθη, είτε μας έστειλαν ολόκληρα κεφάλαια, η συμβολή όλων ήταν χρήσιμη.

Μερικές εταιρείες υποστήριξαν την ανάπτυξη αυτού του εγγράφου μισθώνοντας συντάκτες να εργάζονται σε πλήρη απασχόληση, πληρώνοντας για την έκδοση, κτλ. Ειδικότερα, η BSDi (η οποία αργότερα αποκτήθηκε από την http://www.windriver.com[Wind River Systems]) μίσθωσε μέλη του FreeBSD Documentation Project να εργάζονται σε πλήρη απασχόληση για την βελτίωση του βιβλίου, οδηγώντας στην πρώτη έντυπη έκδοση στα αγγλικά τον Μάρτιο του 2000 (ISBN 1-57176-241-8). Η εταιρεία Wind River Systems μίσθωσε τότε μερικούς επιπρόσθετους συντάκτες ώστε να κάνει βελτιώσεις στην δομή της έντυπης έκδοσης και να προσθέσει κάποια νέα κεφάλαια. Η αποκορύφωση αυτής της εργασίας ήταν η παρουσίαση της δεύτερης έντυπης έκδοσης, τον Νοέμβριο του 2001 (ISBN 1-57176-303-1). 1-57176-303-1). Το 2003-2004, η http://www.freebsdmall.com[FreeBSD Mall, Inc], μίσθωσε αρκετούς συνεργάτες να βελτιώσουν το Εγχειρίδιο Χρήσης προς ετοιμασία της τρίτης έντυπης έκδοσης.
