# $FreeBSDde: de-www/ipv6/Makefile,v 1.1 2011/06/13 21:33:54 jkois Exp $
# $FreeBSD$
# basiert auf: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=		index.sgml

#DATA+=		../../en/ipv6/IPv6-badge-blue-256-trans.png	\
#		../../en/ipv6/IPv6-badge-blue-128-trans.png
#DATA+=		../../en/ipv6/w6d-www-stats-large.png		\
#		../../en/ipv6/w6d-www-stats-v6-large.png	\
#		../../en/ipv6/w6d-www-stats-v6.png		\
#		../../en/ipv6/w6d-www-stats.png

.include "${WEB_PREFIX}/share/mk/web.site.mk"
