# $FreeBSD: www/en/releases/4.2R/Makefile,v 1.1 2000/11/21 20:40:39 jkh Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml
DOCS+=	errata.sgml
DOCS+=	notes.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
