# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	CONTRIB.386BSD CONTRIB.FreeBSD COPYRIGHT.386BSD
DATA+=	COPYRIGHT.FreeBSD COPYRIGHT.USL KNOWNBUGS MIRROR.SITES
DATA+=	PERSONAL.ACKS REGISTER.FreeBSD RELNOTES.FreeBSD.txt ROSTER.FreeBSD
DATA+=	SUPPORT.TXT TODO-1.1.5 WHATS_NEW-1.1.5.txt

.include "${DOC_PREFIX}/share/mk/web.site.mk"
