# $FreeBSD: www/en/conspectus/Makefile,v 1.1 2000/05/31 20:35:46 nik Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml 

SUBDIR=	stable

.include "${WEB_PREFIX}/share/mk/web.site.mk"
