# $FreeBSD: www/en/conspectus/Makefile,v 1.2 2000/11/07 04:05:10 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml 

SUBDIR=	stable
SUBDIR+= advocacy

.include "${WEB_PREFIX}/share/mk/web.site.mk"
