---
title: "FreeBSD 文档授权"
sidenav: about
--- 

= FreeBSD 文档授权

版权所有 1994-2006 The FreeBSD Project. 保留所有权利。

在满足下列条件的前提下， 允许重新分发修改过或未经修改的源代码 (SGML DocBook) 及其 ‘编译过的’ 形式 (SGML, HTML, PDF, PostScript, RTF 等等)：

. 以源代码形式 (SGML DocBook) 重新发布必须保留未经修改的上述版权声明、本许可条件以及其后的免责声明。
. 以编译过的形式 (转换为其他 DTD、 PDF、 PostScript、 RTF 以及其他格式) 必须重述上述版权声明、 本许可条件及其后面的免责声明。

这份文档由 THE FREEBSD DOCUMENTATION PROJECT "按现状形式" (AS-IS) 提供。 此处明示不提供任何明示或暗示的保证， 包括但不必限于对适售性和适用性的任何暗示保证。 任何情况下， THE FREEBSD DOCUMENTATION PROJECT 不承担任何直接， 间接， 连带， 特别， 惩戒性的或因此而产生的其它损害之责任 (包括但不必限于， 获得货品更换或服务； 使用， 数据或盈利损失； 或导致业务中断)， 无论基于何种责任推定， 是否是合同之约， 严格赔偿责任， 或民事侵害 (包括疏忽以及其它情形) 之下以任何方式使用此文档， 即使事先被告知可能发生类似损害。

== 联机手册

一些 FreeBSD 联机手册包含了来自 _IEEE Std 1003.1 的 2004 版， 信息技术标准 ―― 可移植操作系统接口 (POSIX(R)) 规范_。 使用这些联机手册遵循下述授权协议：

____
The Institute of Electrical and Electronics Engineers 和 The Open Group 授权我们复制他们的文档中的部分内容。

在下述描述中， 短语 “此文本” 指代系统文档中用到的那部分内容。

此文本的部分内容来自 IEEE Std 1003.1 的 2004 版， 信息技术标准 ―― 可移植操作系统接口 (POSIX)， 以及 The Open Group 基础标准第 6 期， 并以电子的形式在 FreeBSD 联机手册中再版并复制， 其版权归 (C) 2001-2004 the Institute of Electrical and Electronics Engineers, Inc 以及 The Open Group 所有。 如果这些版本与 IEEE 以及 The Open Group 标准存在差异， 则原始的 IEEE 和 Open Group 标准应被视为仲裁文档。 原始的标准可以通过网络从 http://www.opengroup.org/unix/online.html 获得。

这一说明应出现在包含这些资料的所有产品中。
____

link:../../copyright/[法务主页]
