# $FreeBSD: www/ja/releases/2.2.5R/Makefile,v 1.3 1999/09/06 07:03:25 peter Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

DOCS=	announce.sgml notes.sgml errata.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/2.2.5R

.include "../../../web.mk"
