# $FreeBSD: www/ja/releases/2.2.5R/Makefile,v 1.4 1999/12/23 01:16:02 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

LOCALTOP= ../..

DOCS=	announce.sgml notes.sgml errata.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
