# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	patch-ltmain.sh
DATA+=	patch-po::Makefile.in.in

.include "${WEB_PREFIX}/share/mk/web.site.mk"
