# $FreeBSD: www/zh_CN/news/Makefile.inc,v 1.1.1002.3 2005/12/17 18:58:15 delphij Exp $
# The FreeBSD Simplified Chinese Documentation Project
# Original Revision: 1.2

WEBBASE?=	/data/zh_CN/news
WEB_PREFIX?=	${.CURDIR}/../../..
