---
title: 章 23. 其他檔案系統
part: 部 III. 系統管理
prev: books/handbook/zfs
next: books/handbook/virtualization
description: 本章介紹 FreeBSD 所支援的其他檔案系統
tags: ["filesystem", "ext2", "ext3", "ext4", "ext2fs", "FAT", "exFAT", "NTFS", "HFS", "HFS+", "Apple", "Microsoft", "Linux"]
showBookMenu: true
weight: 27
params:
  path: "/books/handbook/filesystems/"
---

[[filesystems]]
= 其他檔案系統
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 23
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/filesystems/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[filesystems-synopsis]]
== 概述

檔案系統是作業系統的基礎元件，讓使用者能夠儲存、管理及存取資料，使硬碟、隨身碟、USB 儲存裝置等設備得以發揮實際用途。不同的作業系統各有其原生的檔案系統。

FreeBSD 傳統上以 Unix File System (UFS) 為基礎，其現代化版本 UFS2 是主要的原生檔案系統。FreeBSD 也支援 Z File System (ZFS)，以其進階功能、強健性及可靠性著稱。詳情請參閱 crossref:zfs[zfs,Z 檔案系統 (ZFS)]。

除了原生檔案系統之外，FreeBSD 還廣泛支援其他作業系統的檔案系統。這些檔案系統的支援程度各異——有些需要載入核心模組，有些則需要額外安裝使用者空間工具。

閱讀本章之前，您應先：

* 熟悉 UNIX(R) 概念及 crossref:basics[basics,FreeBSD 基礎]。
* 了解如何在 FreeBSD 上 crossref:ports[ports,安裝軟體]。
* 對 crossref:disks[disks,磁碟]、儲存裝置及 FreeBSD 的裝置命名慣例有基本認識。

閱讀本章後，您將了解：

* 原生檔案系統與外部支援檔案系統之間的差異。
* FreeBSD 支援哪些檔案系統，以及各自的支援程度。
* 如何啟用、設定、存取及使用非原生檔案系統。

[[filesystems-linux]]
== Linux(R) 檔案系統

FreeBSD 內建支援數種 Linux(R) 檔案系統。本節說明如何載入支援並掛載這些檔案系統。

[[ext]]
=== Extended File System (EXT)

FreeBSD 自 2.2 版起便在核心中支援 Extended File System (EXT)。man:ext2fs[5] 驅動程式允許 FreeBSD 核心對 ext2、ext3 及 ext4 檔案系統進行讀寫。

[WARNING]
====
目前尚不支援日誌 (journalling) 及加密功能。
====

要存取 ext 檔案系統，請指定 FreeBSD 分割區名稱及現有的掛載點來掛載 ext 磁碟區。以下範例將 [.filename]#/dev/ada1s1# 掛載至 [.filename]#/mnt#：

[source,shell]
....
# mount -t ext2fs /dev/ada1s1 /mnt
....

[[filesystems-windows]]
== Windows(R) 檔案系統

FreeBSD 支援 FAT、exFAT 及 NTFS 檔案系統，能夠存取 Windows 格式的儲存裝置。

[[fat]]
=== FAT 檔案系統

FAT 是一種簡單且穩定的檔案系統。雖然在效能、可靠性及擴展性方面不如現代替代方案，但由於幾乎所有作業系統都支援 FAT，因此常被用來在不同裝置間交換資料。

要存取 FAT 檔案系統，請指定 FreeBSD 分割區名稱及現有的掛載點來掛載 FAT 磁碟區。以下範例將 [.filename]#/dev/ada0s1# 掛載至 [.filename]#/mnt#：

[source,shell]
....
# mount -t msdosfs /dev/ada0s1 /mnt
....

[[ex-fat]]
=== exFAT 檔案系統

exFAT (Extended File Allocation Table) 是針對快閃儲存裝置（如 USB 隨身碟及 SD 卡）最佳化的輕量級檔案系統。它支援大型檔案，並且跨平台廣泛通用，非常適合外接儲存裝置使用。

要在 FreeBSD 上使用 exFAT，需安裝 package:filesystems/exfat[] 套件、載入 FUSE 核心模組，然後進行掛載，步驟如下：

安裝 exFAT 套件：

[source,shell]
....
# pkg install fusefs-exfat
....

使用 FUSE 檔案系統之前，必須先載入 man:fusefs[5] 核心模組：

[source,shell]
....
# kldload fusefs
....

使用 man:sysrc[8] 設定開機時自動載入該模組：

[source,shell]
....
# sysrc kld_list+=fusefs
....

指定 FreeBSD 分割區名稱及現有的掛載點來掛載 exFAT 磁碟區。以下範例將 [.filename]#/dev/ada0s1# 掛載至 [.filename]#/mnt#：

[source,shell]
....
# mount.exfat /dev/ada0s1 /mnt
....

[[using-ntfs]]
=== NTFS 檔案系統

NTFS 是 Microsoft(R) 開發的檔案系統，廣泛使用於 Windows 作業系統。FreeBSD 透過 package:filesystems/ntfs[] 套件提供完整的 NTFS 讀寫支援，方便存取及修改 NTFS 格式的儲存裝置。

要在 FreeBSD 上使用 NTFS，需安裝 package:filesystems/ntfs[] 套件、載入 FUSE 核心模組，然後進行掛載，步驟如下：

安裝 NTFS 套件：

[source,shell]
....
# pkg install fusefs-ntfs
....

使用 FUSE 檔案系統之前，必須先載入 man:fusefs[5] 核心模組：

[source,shell]
....
# kldload fusefs
....

使用 man:sysrc[8] 設定開機時自動載入該模組：

[source,shell]
....
# sysrc kld_list+=fusefs
....

指定 FreeBSD 分割區名稱及現有的掛載點來掛載 NTFS 磁碟區。以下範例將 [.filename]#/dev/ada0s1# 掛載至 [.filename]#/mnt#：

[source,shell]
....
# ntfs-3g /dev/ada0s1 /mnt
....

[[filesystems-macos]]
== MacOS(R) 檔案系統

FreeBSD 支援 MacOS(R) 檔案系統，包括 HFS/HFS+，可存取 Apple(R) 系統格式的儲存裝置。

[[hfs]]
=== HFS/HFS+ 檔案系統

HFS/HFS+ 是 APFS 出現之前 MacOS 的主要檔案系統，常見於較舊的 Mac 設備及外接硬碟。FreeBSD 透過 package:filesystems/hfsfuse[] 套件提供 HFS/HFS+ 的唯讀支援。

要在 FreeBSD 上使用 HFS/HFS+，需安裝 package:filesystems/hfsfuse[] 套件、載入 FUSE 核心模組，然後進行掛載，步驟如下：

安裝 HFS/HFS+ 套件：

[source,shell]
....
# pkg install fusefs-hfsfuse
....

使用 FUSE 檔案系統之前，必須先載入 man:fusefs[5] 核心模組：

[source,shell]
....
# kldload fusefs
....

使用 man:sysrc[8] 設定開機時自動載入該模組：

[source,shell]
....
# sysrc kld_list+=fusefs
....

指定 FreeBSD 分割區名稱及現有的掛載點來掛載 HFS/HFS+ 磁碟區。以下範例將 [.filename]#/dev/ada0s1# 掛載至 [.filename]#/mnt#：

[source,shell]
....
# hfsfuse /dev/ada0s1 /mnt
....
