---
title: Chapter 1. Introduction
authors:
  - author: Murray Stokely
  - author: Jeroen Ruigrok van der Werven
prev: books/developers-handbook/parti
next: books/developers-handbook/tools
description: Introduction to the FreeBSD Developers Handbook
tags: ["introduction", "Developing on FreeBSD", "BSD Vision", "Architectural Guidelines"]
showBookMenu: true
weight: 2
params:
  path: "/books/developers-handbook/introduction/"
---

[[introduction]]
= Introduction
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 1
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/developers-handbook/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[introduction-devel]]
== Developing on FreeBSD

So here we are.
System all installed and you are ready to start programming.
But where to start? What does FreeBSD provide? What can it do for me, as a programmer?

These are some questions which this chapter tries to answer.
Of course, programming has different levels of proficiency like any other trade.
For some it is a hobby, for others it is their profession.
The information in this chapter might be aimed toward the beginning programmer;
indeed, it could serve useful for the programmer unfamiliar with the FreeBSD platform.

[[introduction-bsdvision]]
== The BSD Vision

To produce the best UNIX(R) like operating system package possible, with due respect to the original software tools ideology as well as usability, performance and stability.

[[introduction-archguide]]
== Architectural Guidelines

Our ideology can be described by the following guidelines

* Do not add new functionality unless an implementor cannot complete a real application without it.
* It is as important to decide what a system is not as to decide what it is. Do not serve all the world's needs; rather, make the system extensible so that additional needs can be met in an upwardly compatible fashion.
* The only thing worse than generalizing from one example is generalizing from no examples at all.
* If a problem is not completely understood, it is probably best to provide no solution at all.
* If you can get 90 percent of the desired effect for 10 percent of the work, use the simpler solution.
* Isolate complexity as much as possible.
* Provide mechanism, rather than policy. In particular, place user interface policy in the client's hands.

From Scheifler & Gettys: "X Window System"

[[introduction-layout]]
== The Layout of /usr/src

The complete source code for FreeBSD is available from our link:https://cgit.freebsd.org/src/[public Git repository].
The source code is normally installed in [.filename]#/usr/src#.
The layout of the source tree is described by the top-level link:https://cgit.freebsd.org/src/tree/README.md[README.md] file.
