# $FreeBSD: www/en/releases/5.4R/Makefile,v 1.1 2004/10/22 09:49:00 rwatson Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml todo.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
