=== Bugmeister Team and Bugzilla

Links: +
link:https://www.freebsd.org/administration/#t-bugmeister[Bugmeister team] URL: link:https://www.freebsd.org/administration/#t-bugmeister[] +
link:https://bugs.freebsd.org/bugzilla/[FreeBSD Bugzilla] URL: link:https://bugs.freebsd.org/bugzilla/[]

Contact: Bugmeister <bugmeister@FreeBSD.org>

Some recent maintenance has been done on our Bugzilla instance:

* the weekly reminder emails now include the correct values for mfc-* Flags queries;
* the Dashboard page has had an obsolete query removed.
(We no longer use the 'patch-ready' Keyword; it was too much paperwork.
Thus, the query on that field was useless.);
* the limit that capped the maximum number of reported PRs at 10000 has been raised to 12500.

In addition, the Wiki documentation on our Bugzilla has been
updated:

* the page link:https://wiki.freebsd.org/Bugzilla/SearchQueries[] has been substantially reworked:
** In particular, documentation about how to search on Flag values has been added.
(This may not have been done before.)
Example: search for PRs with Flag 'mfc-stable14' set;
** This page may be of interest to all committers and contributors;

* the page https://wiki.freebsd.org/Bugmeister/BugmeisterQA has also been updated;
While similar to the above, it is of more specific interest to bugmeister and triagers.

As well, PRs that are specific to FreeBSD 12 are being culled, as 12 has gone out of support as of 20231231.

A further effort is being made to document our setup of Bugzilla itself, especially with respect to our customizations.
This is needed to bring our own repository up to date with what is running
on production.

The number of PRs over the past quarter (and year) has remained consistent.
However, we do seem to be closing incoming PRs more quickly these days.
For reference: link:https://bugs.freebsd.org/bugzilla/page.cgi?id=dashboard.html&days=90[].

The overall number of PRs remains around 11,400.

Bugmeister is also working towards restarting the Bugathons.
See the updated page link:https://wiki.freebsd.org/Bugathons[].

Bugmeister would like to thank a number of people who have assisted with bugbusting, including Mina Galić, Graham Perrin, mailto:salvadore@FreeBSD.org[Lorenzo Salvadore], and mailto:fernape@FreeBSD.org[Fernando Apesteguìa], among others.

In addition, bugmeister would like to thank all the FreeBSD committers who help process the PRs as they come in.
Over the last few months we seem to be much closer to steady-state.
