=== Cluster Administration Team

Links: +
link:https://www.freebsd.org/administration/#t-clusteradm[Cluster Administration Team members] URL: link:https://www.freebsd.org/administration/#t-clusteradm[]

Contact: Cluster Administration Team <clusteradm@FreeBSD.org>

FreeBSD Cluster Administration Team members are responsible for managing the machines the Project relies on to synchronize its distributed work and communications.

In this quarter, the team has worked on the following:

* Regular support for FreeBSD.org user accounts.
* Regular disk and parts support (and replacement) for all physical hosts and mirrors.
* Enable mirroring of link:https://www.FreeBSD.org[] and link:https://docs.FreeBSD.org[] in the FreeBSD project-managed mirrors.
* Cluster refresh, upgrading all hosts and jails to the most recent versions of 15-CURRENT, 14-STABLE, 13-STABLE, and 12-STABLE.
* Begin sunsetting 12-STABLE infrastructure as the branch approaches its end of life.

In addition to these projects, with link:https://www.modirum.com[Modirum] generously link:https://github.com/sponsors/ppaeps/[sponsoring Philip's time] for most of October, we were able to bring pkgbase into "preview" production in time for 14.0-RELEASE in November.

We also installed a new European mirror site in Sjöbo, Sweden, sponsored by Teleservice Skåne AB.
Traffic in Europe is now directed roughly equally between our existing mirror in Frankfurt (sponsored by Equinix) and the new mirror in Sweden.
After well over ten years in service, we plan to decommission our mirror site in the UK during first quarter of 2024.
We would like to thank link:https://www.bytemark.co.uk/[Bytemark Hosting] for supporting this mirror for all this time.

Next quarter, supported by the FreeBSD Foundation, we plan to bring up a new primary cluster site in Chicago.

==== FreeBSD Official Mirrors Overview

Current locations are Australia, Brazil, Germany, Japan (two full mirror sites), Malaysia, South Africa, Sweden, Taiwan, United Kingdom (full mirror site), United States of America -- California, New Jersey (primary site), and Washington.

The hardware and network connection have been generously provided by:

* https://www.bytemark.co.uk/[Bytemark Hosting] (decommissioned during 2024Q1)
* Cloud and SDN Laboratory at https://www.bbtower.co.jp/en/corporate/[BroadBand Tower, Inc]
* https://www.cs.nycu.edu.tw/[Department of Computer Science, National Yang Ming Chiao Tung University]
* https://deploy.equinix.com/[Equinix]
* https://internet.asn.au/[Internet Association of Australia]
* https://www.isc.org/[Internet Systems Consortium]
* https://www.inx.net.za/[INX-ZA]
* https://www.kddi-webcommunications.co.jp/english/[KDDI Web Communications Inc]
* https://www.mohe.gov.my/en/services/research/myren[Malaysian Research & Education Network]
* https://www.metapeer.com/[Metapeer]
* https://nic.br/[NIC.br]
* https://your.org/[Your.Org]
* https://365datacenters.com/[365 Data Centers]
* https://www.teleservice.net/[Teleservice Skåne AB] (new since 2023Q4)
