////
Quarter:	4th quarter of 2023
Prepared by:	fernape
Reviewed by:	
Last edit:	$Date$
Version:	$Id$
////

=== Documentation Engineering Team

Link: link:https://www.freebsd.org/docproj/[FreeBSD Documentation Project] URL: link:https://www.freebsd.org/docproj/[] +
Link: link:https://docs.freebsd.org/en/books/fdp-primer/[FreeBSD Documentation Project Primer for New Contributors] URL: link:https://docs.freebsd.org/en/books/fdp-primer/[] +
Link: link:https://www.freebsd.org/administration/#t-doceng[Documentation Engineering Team] URL: link:https://www.freebsd.org/administration/#t-doceng[]

Contact: FreeBSD Doceng Team <doceng@FreeBSD.org>

The doceng@ team is a body to handle some of the meta-project issues associated with the FreeBSD Documentation Project; for more information, see link:https://www.freebsd.org/internal/doceng/[FreeBSD Doceng Team Charter].

During the last quarter:

Glen Barber stepped down from doceng.
doceng would like to thank gjb@ for his service.

Ceri Davies' commit bit was taken for safekeeping as per his request.
doceng would like to thank ceri@ for his contributions.

mhorne@ to be mentored by carlavilla@ to obtain a documentation commit bit.

==== FreeBSD Handbook:

The Handbook was updated to show that FreeBSD 14.0 is the latest release.


==== FreeBSD Translations on Weblate

Link: link:https://wiki.freebsd.org/Doc/Translation/Weblate[Translate FreeBSD on Weblate] URL: link:https://wiki.freebsd.org/Doc/Translation/Weblate[] +
Link: link:https://translate-dev.freebsd.org/[FreeBSD Weblate Instance] URL: link:https://translate-dev.freebsd.org/[]

===== Q4 2023 Status

* 17 team languages
* 203 registered users

===== Languages

* Chinese (Simplified) (zh-cn)	(progress: 7%)
* Chinese (Traditional) (zh-tw)	(progress: 3%)
* Dutch (nl) 			(progress: 1%)
* French (fr)			(progress: 1%)
* German (de)			(progress: 1%)
* Indonesian (id)		(progress: 1%)
* Italian (it)			(progress: 5%)
* Korean (ko)			(progress: 33%)
* Norwegian (nb-no)		(progress: 1%)
* Persian (fa-ir)		(progress: 2%)
* Polish			(progress: 1%)
* Portuguese			(progress: 0%)
* Portuguese (pt-br)		(progress: 22%)
* Spanish (es)			(progress: 35%)
* Turkish (tr)			(progress: 2%)

We want to thank everyone that contributed, translating or reviewing documents.

And please, help promote this effort on your local user group, we always need more volunteers.

==== FreeBSD Handbook working group

Contact: Sergio Carlavilla <carlavilla@FreeBSD.org>

 * link:https://reviews.freebsd.org/D40546[The Network chapter has been rewritten]
 * link:https://cgit.freebsd.org/doc/commit/?id=612b7cc1721224c494c5b2600188e1508bb5611b[The Jails chapter has been rewritten]
 * The next section to work on will be the file systems part: UFS, ZFS, Other File Systems

==== FAQ Working Group

Contact: Sergio Carlavilla <carlavilla@FreeBSD.org>

A new FAQ was released alongside FreeBSD 14.0.

==== FreeBSD Website Revamp - WebApps working group

Contact: Sergio Carlavilla <carlavilla@FreeBSD.org>

Working group in charge of creating the new FreeBSD Documentation Portal and redesigning the FreeBSD main website and its components.
FreeBSD developers can follow and join the working group on the FreeBSD Slack channel #wg-www21.
The work will be divided into three phases:

. Redesign of the Manual Pages on web
+
Scripts to generate the HTML pages using mandoc. (_Complete, Approved by Doceng, Deploy Date Not Decided Yet_)
Public instance on https://man-dev.FreeBSD.org

. Redesign of the FreeBSD main website
+
New design, responsive and dark theme. (_Almost Complete, Presented at EuroBSDCon_)

. Redesign of the Ports page on web
+
Ports scripts to create an applications portal. (_Work in progress_)
