=== FreeBSD Foundation

Links: +
link:https://freebsdfoundation.org/[FreeBSD Foundation] URL: link:https://freebsdfoundation.org/[] +
link:https://freebsdfoundation.org/blog/technology-roadmap/[Technology Roadmap] URL: link:https://freebsdfoundation.org/blog/technology-roadmap/[] +
link:https://freebsdfoundation.org/donate/[Donate] URL: link:https://freebsdfoundation.org/donate/[] +
link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[Foundation Partnership Program] URL: link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[] +
link:https://freebsdfoundation.org/journal/[FreeBSD Journal] URL: link:https://freebsdfoundation.org/journal/[] +
link:https://freebsdfoundation.org/our-work/events/[Foundation Events] URL: link:https://freebsdfoundation.org/our-work/events/[]

Contact: Deb Goodkin <deb@FreeBSDFoundation.org>

The FreeBSD Foundation is a 501(c)(3) non-profit organization dedicated to supporting and promoting the FreeBSD Project and worldwide community, and helping to advance the state of FreeBSD.
We do this in both technical and non-technical ways.
We are 100% supported by donations from individuals and corporations and those investments help us fund the:

* Software development projects to implement features and functionality in FreeBSD
* Sponsor and organize conferences and developer summits to provide collaborative opportunities and promote FreeBSD
* Purchase and support of hardware to improve and maintain FreeBSD infrastructure,
* Resources to improve security, quality assurance, and continuous integration efforts.
* Materials and staff needed to promote, educate, and advocate for FreeBSD,
* Collaboration between commercial vendors and FreeBSD developers,
* Representation of the FreeBSD Project in executing contracts, license agreements, and other legal arrangements that require a recognized legal entity.

We supported FreeBSD in the following ways during the last quarter of 2023:

==== OS Improvements

During the fourth quarter of 2023, 236 src, 47 ports, and 33 doc tree commits identified The FreeBSD Foundation as a sponsor.
Some of this Foundation-sponsored work is described in separate report entries:

* <<_openstack_on_freebsd,OpenStack on FreeBSD>>
* <<_simd_enhancements_for_amd64,SIMD enhancements for amd64>>.

Three new contractors started.
Cheng Cui began working full-time on wireless networking.
A main goal for Cheng's project is to assist Bjoern Zeeb with 802.11ac support in iwlwifi.
Tom Jones began work to port the Vector Packet Processor (VPP) to FreeBSD.
VPP is an open-source, high-performance user space networking stack that provides fast packet processing suitable for software-defined networking and network function virtualization applications.
Olivier Certner joined the FreeBSD Foundation as a general FreeBSD developer.
Some of Olivier's contributions so far include:

* reviewing, fixing, and hardening several security policies aimed at limiting process visibility, policies that are based on user identity, group membership, or sub-jail membership
* committing fixes in the login class code, including one that allowed unprivileged users to bypass resource limits
* implementing a secure hardware fix for the Zenbleed issue affecting AMD Zen2 processors.

Here is a sampling of other Foundation-sponsored work completed over the last quarter of 2023:

* arm64: Add Armv8 rndr random number provider
* net80211, LinuxKPI, and iwlwifi fixes and improvements
* OpenSSL: updates to 3.0.11 and 3.0.12
* Various freebsd-update fixes in preparation for 14.0
* ssh: Update to OpenSSH 9.5p1
* Various iommu fixes
* Various makefs/zfs fixes

Learn more about our software development work for all of 2023 at https://freebsdfoundation.org/blog/2023-in-review-software-development/.

==== FreeBSD Infrastructure

We approved over $100,000 for a cluster refresh that began in late 2023 and will carry over into the new year by purchasing and shipping 15 new servers to 4 racks generously donated by NYI in their new Chicago facility.
The systems specifications were determined by the Cluster Administration team and consist of:

* 5 package builders
* 3 web servers
* 2 package mirrors
* 2 CI servers
* 2 firewall/router
* 1 admin bastion

More on our 2023 infrastructure support can be found at: https://freebsdfoundation.org/blog/2023-in-review-infrastructure/.

==== Continuous Integration and Workflow Improvement

As part of our continued support of the FreeBSD Project, the Foundation supports a full-time staff member dedicated to improving the Project's continuous integration system and the test infrastructure.
The full update can be found within the quarterly status report.

==== Partnerships and Research

In Q4 I connected with the following people, companies, and organizations: Phil Shafer, who works at Juniper Networks, and I met at All Things Open.
He told me about the libxo library and his continuing work on related issues, like rewriting and filtering output to allow richer options that regular expressions provide.
Sticking with Juniper, I also met Simon Gerraty at the Vendor Summit and heard his talk on link:https://www.youtube.com/live/k-AzShVdAHo?si=otJvsMLc3gqilZSU&t=22069[SecureBoot].
In alphabetical order, I also met with AMD, Ampere, Center for Internet Security (CIS), Innovate UK, Michael Dexter, Metify, Microsoft, several people at NetApp when I attended their annual conference (Thank you for the invitation!!), NetScaler, NIST, Nozomi Networks, NVIDIA, members of the Open Container Initiative community, OpenSSF, RG Nets, Doug Rabson.

I greatly appreciated the opportunity to attend NetApp's annual conference in October.
I heard from and connected with experts at NetApp and their partners and customers on topics such as AI and seamless AI data pipelines, hybrid cloud, and green computing.
I took the opportunity to hand out some FreeBSD lapel pins 🙂 and I connected with a FreeBSD user and member of the Enterprise WG whose company is a NetApp Customer.

In Q4 we link:https://freebsdfoundation.org/news-and-events/latest-news/freebsd-foundation-announces-ssdf-attestation/[announced the new FreeBSD SSDF Attestation] program to help commercial users of FreeBSD comply with new US Government procurement regulations.
This program was informed by valuable feedback from NetApp, Metify, and NIST, and the genesis of the idea came thanks to my involvement with open source policy experts, in particular via the OSI's Open Policy Alliance.

The link:https://github.com/opencontainers/tob/pull/133[Open Container Initiative Technical Oversight Board voted] in December to approve Doug Rabson's proposal to create a Working Group to extend the OCI runtime specification to support FreeBSD.
Huge thanks to all involved!
An OCI runtime extension for FreeBSD is one of the most frequently requested capabilities and I was happy to play a small role in helping to coordinate this effort so far.

The Vendor Summit in November was a great event.
Huge props to John Baldwin and Anne Dickison for all the work to organize and orchestrate.
I got a lot out of the event.
Personal highlights were conversations with a diversity of users, the CHERI talk, the end user panel, and Allan's talk on being an upstream first company.
For a full recap on our efforts to strengthen partnerships and increase funding in 2023, check out: link:https://freebsdfoundation.org/blog/2023-in-review-partnerships-and-research/[].

==== Advocacy

From organizing and attending events, to creating technical content that educates, and expanding the coverage of FreeBSD in the media, here is a sample of what we did last quarter to support FreeBSD.

* Helped organize and sponsor the November 2023 Vendor Summit held at NetApp in San Jose.
  Many consider this one of the best summits to date.
  Be sure to check out the link:https://youtube.com/playlist?list=PLugwS7L7NMXzSalaF4l_78sfRa2l8xvag&feature=shared[videos].
* Introduced FreeBSD to new and returning folks at link:https://freebsdfoundation.org/blog/all-things-open-2023-conference-report/[All Things Open] in North Carolina.
* Provided an overview of FreeBSD 14: link:https://freebsdfoundation.org/blog/security-performance-and-interoperability-introducing-freebsd-14/[Security, Performance, and Interoperability; Introducing FreeBSD 14]
* In collaboration with the Core team, released the link:https://freebsdfoundation.org/blog/2024-freebsd-community-survey-is-here/[2024 FreeBSD Community Survey]
* Participated in an interview about FreeBSD: link:https://freebsdfoundation.org/news-and-events/latest-news/what-the-dev-podcast-the-evolution-of-the-freebsd-project/[What the Dev Podcast: The Evolution of the FreeBSD Project]
* Release the link:https://freebsdfoundation.org/past-issues/13099/[September/October 2023] issue of the FreeBSD Journal now with HTML versions of the articles.

For a full recap of what we did to advocate for FreeBSD in 2023, please check out the Advocacy Year in Review: link:https://freebsdfoundation.org/blog/2023-in-review-advocacy/[] or the monthly  newsletters: link:https://freebsdfoundation.org/our-work/latest-updates/?filter=newsletter[].

==== Fundraising

Thank you to everyone who gave us a financial contribution last quarter to help fund our work to support the Project.
You brought us even closer to our goal and we are grateful for your investment in FreeBSD!
We are still receiving donations in the mail and will post the final number in mid-February.

Please consider supporting our efforts in 2024 by making a donation here: link:https://freebsdfoundation.org/donate/[].

Or, check out our Partnership opportunities here:
link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[].

==== Legal/FreeBSD IP

The Foundation owns the FreeBSD trademarks, and it is our responsibility to protect them.
We also provide legal support for the core team to investigate questions that arise.

Go to link:https://freebsdfoundation.org[] to find more about how we support FreeBSD and how we can help you!
