=== Ports Collection

Links: +
link:https://www.FreeBSD.org/ports/[About FreeBSD Ports] URL: link:https://www.FreeBSD.org/ports/[] +
link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[Contributing to Ports] URL: link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[]

link:https://www.freebsd.org/portmgr/[Ports Management Team] URL: link:https://www.freebsd.org/portmgr/[] +
link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[Ports Tarball] URL: link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[]

Contact: Tobias C. Berner <portmgr-secretary@FreeBSD.org> +
Contact: FreeBSD Ports Management Team <portmgr@FreeBSD.org>

The Ports Management Team is responsible for overseeing the overall direction of the Ports Tree, building packages, and personnel matters.
Below is what happened in the quarter.

* According to INDEX, there are currently 31,942 ports in the Ports Collection.
There are currently ~3,100 open ports PRs.
The quarter saw 9,424 commits by 157 committers on the main branch and 781 commits by 71 committers on the 2023Q4 branch.
Compared to last quarter, this means a hefty decrease in the number of commits on the main branch (down from 11,454) and slightly fewer backports to the quarterly branch (down from 828).
The number of ports also fell a bit (down from 34,600).

In Q4 there were around 9424 commits to main.
The most active committers were:

        sunpoet   2946
        yuri       861
        bofh       793
        jbeich     419
        fuz        324
        eduardo    168
        fernape    160
        jhale      153
        thierry    146
        diizzy     123

During Q4 we welcomed Michael Osipov (michaelo) and  Timothy Beyer (beyert) as new committers, but sadly also had to say goodbye to bland, sbruno, hselasky and gjb.

We invited arrowd, flo and riggs to be part of portmgr-lurkers for the next months.

Support for FreeBSD 12.x was removed at the end of the quarter.

The end of Q4 also saw the introduction of subpackages to the ports tree.
Similar to when flavors were introduced, new subpackages will require an approval by portmgr before being pushed to the tree.
With subpackages it is possible to create multiple packages from a single build of a port.

The following happened on the infrastructure side:

* Packages for 14.0-RELEASE were built
* Poudriere was updated to release-3.4

The no-longer maintained package:www/qt5-webkit[] was removed.

postgresql11, php80, mysql57, percona57, ghostscript9 were removed.

The following default versions changed:

* perl                    to 5.36
* ghostcript              to 10
* corosync                to 3

Updates to major ports that happened were:

* package:ports-mgmt/pkg[]          to 1.20.9
* package:ports-mgmt/poudriere[]    to 3.4.0 (subpackage support)
* KDE-bits                to plasma-5.27.10, frameworks-5.112, gear-23.08.4, and beta-2
* package:www/chromium[]            to 120.0.6099.129
* package:www/firefox[]             to 121.0 (rc1)
* package:lang/rust[]               to 1.74.1
* ... and many more ...

During the last quarter, pkgmgr@ ran 26 exp-runs to test various ports upgrades, updates to default versions of ports, subpackage support and base system changes.
