# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/gnome/Makefile.inc,v 1.2 2003/10/25 15:29:10 andy Exp $
#
# Original revision: 1.1

WEBBASE?=	/data/ru/gnome
DOC_PREFIX?=	${.CURDIR}/../../..
