# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original version: 1.8
#
# $FreeBSD: www/pt_BR/FAQ/Makefile,v 1.1 2002/10/05 16:03:59 lioux Exp $
#
# Build the FreeBSD FAQ *outside* of the www tree, and install it
# in to the right place as necessary.

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	index.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
