---
title: FreeBSD handboek
authors:
  - author: The FreeBSD Dutch Documentation Project
copyright: 1995-2020 The FreeBSD Dutch Documentation Project
releaseinfo: "$FreeBSD$" 
trademarks: ["freebsd", "ibm", "ieee", "redhat", "3com", "adobe", "apple", "intel", "linux", "microsoft", "opengroup", "sun", "realnetworks", "oracle", "3ware", "arm", "adaptec", "heidelberger", "intuit", "lsilogic", "themathworks", "thomson", "vmware", "wolframresearch", "xiph", "xfree86", "general"] 
next: books/handbook/preface
---

= FreeBSD handboek
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:toc-title: Inhoudsopgave
:part-signifier: Deel
:chapter-signifier: Hoofdstuk
:appendix-caption: Bijlage
:table-caption: Tabel
:figure-caption: Afbeelding
:example-caption: Voorbeeld

include::shared/releases.adoc[]
include::shared/nl/mailing-lists.adoc[]

[.abstract-title]
Samenvatting

Welkom bij FreeBSD! Dit handboek behandelt de installatie en het dagelijks gebruik van _FreeBSD {rel112-current}-RELEASE_ en _FreeBSD {rel120-current}-RELEASE_. Aan deze handleiding wordt nog gewerkt, en is het resultaat van het werk van veel mensen. Veel hoofdstukken of paragrafen bestaan nog niet en wat bestaat dient soms nog bijgewerkt te worden. Als de lezer mee wil helpen aan dit project kan een mail gestuurd worden naar de {freebsd-doc}. De meest recente versie van dit document is te vinden op de http://www.FreeBSD.org/[FreeBSD website]. Eerdere versies van dit handboek zijn te vinden op http://docs.FreeBSD.org/doc/[http://docs.FreeBSD.org/doc/]. Het kan ook gedownload worden in veel verschillende formaten en compressiewijzen van de link:ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/[FreeBSD FTP server] of een van de vele <<mirrors-ftp,mirrorsites>>. Een gedrukt exemplaar van het handboek is te koop bij de http://www.freebsdmall.com/[FreeBSD Mall] (Engels). Het handboek kan ook link:https://www.FreeBSD.org/search/[doorzocht worden].

'''

include::content/nl/books/handbook/toc.adoc[]

include::content/nl/books/handbook/toc-figures.adoc[]

include::content/nl/books/handbook/toc-tables.adoc[]

include::content/nl/books/handbook/toc-examples.adoc[]
