# $Id: Makefile,v 1.3 1998-08-09 16:22:16 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.3

DOCS = 	commercial.sgml
# DOCS+=  consulting.sgml
# DOCS+=  hardware.sgml
# DOCS+=  misc.sgml
# DOCS+=  software.sgml

INDEXLINK=commercial.html

.include "../../web.mk"
