# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.7

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS = 	commercial.sgml
# DOCS+=  consulting.sgml
# DOCS+=  consulting_bycat.sgml
# DOCS+=  hardware.sgml
# DOCS+=  misc.sgml
# DOCS+=  software.sgml
# DOCS+=  software_bycat.sgml

INDEXLINK=commercial.html

.include "../../web.mk"
