---
title: Хавсралт C. Интернэт дэх эх үүсвэрүүд
part: хэсэг V. Хавсралтууд
prev: books/handbook/bibliography
next: books/handbook/pgpkeys
---

[appendix]
[[eresources]]
= Интернэт дэх эх үүсвэрүүд
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Гарчиг
:table-caption: Хүснэгт
:figure-caption: Зураг
:example-caption: Жишээ
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: C

include::shared/mirrors.adoc[]
include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/mn/mailing-lists.adoc[]
include::shared/mn/teams.adoc[]
include::shared/mn/urls.adoc[]

FreeBSD-ийн дэвшлийн хурдан алхаа нь хамгийн сүүлийн хөгжүүлэлтүүдийг дагахаас хамаараад хэвлэн гаргах хэрэгцээгүй болгоход хүргэдэг. Цахим эх үүсвэрүүд нь хамгийн шилдэг нь бөгөөд хамгийн сүүлийн үеийн дэвшилтүүдийн талаар мэдлэгтэй байх бараг цорын ганц арга юм. FreeBSD нь сайн дурын чармайлт болохоор хэрэглэгчийн хүрээнийхэн нь өөрсдөө цахим захидал, вэб хэлэлцүүлгүүд болон тэр хүрээнийхэнд хүрэх хамгийн үр ашигтай арга болох USENET мэдээнүүдийн тусламжтайгаар ерөнхийдөө нэгэн хэлбэрийн "техникийн дэмжлэгийн хэлтэс" маягаар үйлчилдэг.

FreeBSD-ийн хэрэглэгчийн хүрээнийхэнд хандах хамгийн чухал цэгүүдийг доор дурдав. Хэрэв та энд дурдагдсанаас өөр эх үүсвэрүүдийн талаар мэдэж байвал тэдгээрийг бас энэ жагсаалтад оруулахаар {freebsd-doc} уруу илгээнэ үү.

[[eresources-mail]]
== Захидлын жагсаалтууд

Захидлын жагсаалтууд нь FreeBSD-ийн хэрэглэгчдэд чиглэсэн асуултуудаа тавих эсвэл техникийн хэлэлцүүлэг нээх хамгийн шулуун зам юм. FreeBSD-ийн төрөл бүрийн сэдвүүдээр олон янзын жагсаалт байдаг. Өөрийн асуултуудаа хамгийн тохиромжтой захидлын жагсаалт руу хаягласнаар илүү хурдан, зөв хариу авах боломжтой болгодог.

Энэ баримтын сүүл хэсэгт төрөл бүрийн жагсаалтуудад зориулсан дүрмүүд бий. _Аль нэг жагсаалт уруу элсэн орох эсвэл захидал илгээхээсээ өмнө жагсаалтын дүрмийг уншина уу_. Одоо манай захидлын жагсаалтын захиалагчдын ихэнх нь FreeBSD-тэй холбоотой олон зуун захиануудыг өдөр бүр авдаг бөгөөд зөв хэрэглэх тухай дүрэм, журмуудыг гаргаснаар бид жагсаалтуудын шуугиан, дохионы харьцааг (signal-to-noise ratio) өндөр байлгахыг хичээдэг. Бага хийх нь захидлын жагсаалтыг энэ төсөлд зориулсан үр ашигтай холбооны зөөвөрлөгч байхыг эцсийн эцэст болиулж болох юм.

[NOTE]
====
_Хэрэв та FreeBSD-ийн жагсаалтууд руу илгээж чадаж байгаа эсэхээ шалгаж тест хийхийг хүсвэл {freebsd-test} руу тест захидал илгээнэ үү._ Өөр бусад жагсаалт руу тест захидал битгий илгээгээрэй.
====

Аль жагсаалт уруу асуултаа илгээхээ мэдэхгүй эргэлзэж байгаа бол link:{freebsd-questions-article}[FreeBSD-асуултууд захидлын жагсаалтаас хэрхэн хамгийн их ашгийг авч болох вэ] хэсгээс үзнэ үү.

Аль нэг жагсаалт уруу илгээхээсээ өмнө байнга давтагддаг хэлэлцүүлгүүдийг үүсгэхгүй байхад хэрхэн туслах зэрэг захидлын жагсаалтыг хэрхэн хамгийн үр ашигтай ашиглах талаар сурах хэрэгтэй. Үүнийг тулд link:{mailing-list-faq}[ Захидлын жагсаалтын байнга асуудаг асуултууд] (FAQ) баримтыг унших нь зүйтэй.

Бүх захидлын жагсаалтуудын хувьд архивууд хадгалагддаг бөгөөд link:https://www.FreeBSD.org/search/[FreeBSD Дэлхий Даяарх Вэб сервер] ашиглан хайлт хийж болно. Түлхүүр үгээр хайж болох архив нь байнга асуугддаг асуултуудад зориулсан хариултуудыг олох хамгийн шилдэг аргыг санал болгодог бөгөөд асуулт илгээхээсээ өмнө эдгээрээс лавлах хэрэгтэй юм. Энэ нь бас FreeBSD-ийн захидлын жагсаалт руу илгээсэн захиануудыг үргэлж хадгалж байдаг гэсэн үг юм. Хувийн нууцыг хамгаалах шаардлагатай бол устгах боломжтой хоёр дахь захианы хаяг ашиглаж зөвхөн нийтийн мэдээллийг явуулах хэрэгтэй.

[[eresources-summary]]
=== Жагсаалтын тойм

_Ерөнхий жагсаалтууд:_ Дараах нь ерөнхий жагсаалтууд бөгөөд эдгээрт хэн ч гэсэн чөлөөтэй (зоригтойгоор) элсэж болно:

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Жагсаалт
| Зорилго

|link:{freebsd-advocacy-url}[freebsd-advocacy]
|FreeBSD Evangelism

|{freebsd-announce}
|Чухал үйл явдлууд болон төслийн гол гол үе шатууд (зохицуулалттай)

|link:{freebsd-arch-url}[freebsd-arch]
|Архитектур болон дизайны хэлэлцүүлгүүд

|link:{freebsd-bugbusters-url}[freebsd-bugbusters]
|FreeBSD-ийн асуудлын тайлангийн мэдээллийн бааз болон түүнтэй холбоотой хэрэгслүүдийн арчилгаатай холбоотой хэлэлцүүлгүүд

|link:{freebsd-bugs-url}[freebsd-bugs]
|Алдааны тайлангууд

|link:{freebsd-chat-url}[freebsd-chat]
|FreeBSD хүрээнийхэнтэй холбоотой техникийн бус зүйлс

|link:{freebsd-chromium-url}[freebsd-chromium]
|FreeBSD-тэй холбоотой Chromium-ийн хэлэлцүүлэг

|{freebsd-current}
|FreeBSD-CURRENT-н хэрэглээтэй хамаатай хэлэлцүүлэг

|link:{freebsd-isp-url}[freebsd-isp]
|FreeBSD ашиглаж байгаа Интернэтийн үйлчилгээ үзүүлэгчдийн асуудлууд

|link:{freebsd-jobs-url}[freebsd-jobs]
|FreeBSD-тэй холбоотой ажил болон зөвлөгөөний боломжууд

|link:{freebsd-questions-url}[freebsd-questions]
|Хэрэглэгчийн асуултууд болон техникийн дэмжлэг

|{freebsd-security-notifications}
|Аюулгүй байдлын мэдэгдлүүд (зохицуулалттай)

|{freebsd-stable}
|FreeBSD-STABLE-н хэрэглээтэй холбоотой хэлэлцүүлэг

|{freebsd-test}
|Аль нэг жагсаалт уруу тест захиа явуулахын оронд энэ жагсаалт ашиглагдана
|===

_Техникийн жагсаалтууд:_ Дараах жагсаалтууд нь техникийн хэлэлцүүлэгт зориулагдсан. Эдгээр жагсаалтын агуулга болон хэрхэн ашиглах талаар нарийн чанд зааврууд байдаг учраас аль нэг уруу нь элсэх юм уу эсвэл захидал илгээхээсээ өмнө жагсаалт болгоны дүрэм, журмыг та унших хэрэгтэй юм.

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Жагсаалт
| Зорилго

|{freebsd-acpi}
|ACPI болон тэжээлийн удирдлагын хөгжүүлэлт

|link:{freebsd-afs-url}[freebsd-afs]
|AFS-г FreeBSD уруу хөрвүүлэх

|link:{freebsd-aic7xxx-url}[freebsd-aic7xxx]
|Adaptec(R) AIC 7xxx-д зориулж драйверууд хөгжүүлэх

|link:{freebsd-amd64-url}[freebsd-amd64]
|FreeBSD-г AMD64 системүүд уруу хөрвүүлэх (зохицуулалттай)

|link:{freebsd-apache-url}[freebsd-apache]
|Apache-тай холбоотой портуудын тухай хэлэлцүүлэг

|link:{freebsd-arm-url}[freebsd-arm]
|FreeBSD-г ARM(R) процессорууд уруу хөрвүүлэх

|link:{freebsd-atm-url}[freebsd-atm]
|FreeBSD дээр ATM сүлжээг ашиглах

|link:{freebsd-bluetooth-url}[freebsd-bluetooth]
|FreeBSD дээр Bluetooth(R) технологийг ашиглах

|link:{freebsd-cluster-url}[freebsd-cluster]
|FreeBSD-г кластерчлагдсан орчинд ашиглах

|link:{freebsd-cvsweb-url}[freebsd-cvsweb]
|CVSweb арчилгаа

|link:{freebsd-database-url}[freebsd-database]
|FreeBSD дээрх мэдээллийн бааз болон хөгжүүлэлтийн талаар хэлэлцэх

|link:{freebsd-desktop-url}[freebsd-desktop]
|Десктоп дээр FreeBSD-г ашиглах ба сайжруулах

|link:{freebsd-doc-url}[freebsd-doc]
|FreeBSD-тэй холбоотой баримтуудыг үүсгэх

|link:{freebsd-drivers-url}[freebsd-drivers]
|FreeBSD-д зориулж төхөөрөмжийн драйверуудыг бичих

|link:{freebsd-eclipse-url}[freebsd-eclipse]
|Eclipse IDE, хэрэгслүүд, клиентийн баялаг програмууд болон портуудын FreeBSD хэрэглэгчид.

|link:{freebsd-embedded-url}[freebsd-embedded]
|FreeBSD-г авсаар (embedded) програмуудад ашиглах

|link:{freebsd-eol-url}[freebsd-eol]
|FreeBSD төслөөр дэмжигдэхээ больсон FreeBSD-тэй холбоотой програм хангамжийн дэмжлэг.

|link:{freebsd-emulation-url}[freebsd-emulation]
|Линукс/MS-DOS(R)/Windows(R) зэрэг системүүдийн эмуляц

|link:{freebsd-firewire-url}[freebsd-firewire]
|FreeBSD FireWire(R) (iLink, IEEE 1394) техникийн хэлэлцүүлэг

|link:{freebsd-fs-url}[freebsd-fs]
|Файлын системүүд

|link:{freebsd-gecko-url}[freebsd-gecko]
|Gecko Rendering Engine-тэй холбоотой асуудлууд

|link:{freebsd-geom-url}[freebsd-geom]
|GEOM-той холбоотой хэлэлцүүлгүүд болон шийдлүүд

|link:{freebsd-gnome-url}[freebsd-gnome]
|GNOME болон GNOME програмуудыг хөрвүүлэх

|link:{freebsd-hackers-url}[freebsd-hackers]
|Техникийн ерөнхий хэлэлцүүлэг

|link:{freebsd-hardware-url}[freebsd-hardware]
|FreeBSD-г тааруулахтай холбоотой тоног төхөөрөмжийн ерөнхий хэлэлцүүлэг

|link:{freebsd-i18n-url}[freebsd-i18n]
|FreeBSD Интернационалчлал

|link:{freebsd-ia32-url}[freebsd-ia32]
|IA-32 (Intel(R) x86) тавцан дээрх FreeBSD

|link:{freebsd-ia64-url}[freebsd-ia64]
|FreeBSD-г Intel(R)-ийн ирж байгаа IA64 системүүд уруу хөрвүүлэх

|link:{freebsd-infiniband-url}[freebsd-infiniband]
|FreeBSD дээрх Infiniband

|link:{freebsd-ipfw-url}[freebsd-ipfw]
|IP галт ханын кодны шинэ дизайны тухай техникийн хэлэлцүүлэг

|link:{freebsd-isdn-url}[freebsd-isdn]
|ISDN хөгжүүлэгчид

|link:{freebsd-jail-url}[freebsd-jail]
|man:jail[8] боломжийн тухай хэлэлцүүлэг

|link:{freebsd-java-url}[freebsd-java]
|Java(TM) хөгжүүлэгчид болон JDK(TM)-г FreeBSD уруу хөрвүүлж байгаа хүмүүс

|link:{freebsd-kde-url}[freebsd-kde]
|KDE болон KDE програмуудыг порт хийх

|link:{freebsd-lfs-url}[freebsd-lfs]
|LFS-г FreeBSD руу порт хийх

|link:{freebsd-mips-url}[freebsd-mips]
|FreeBSD-г MIPS(R) рүү порт хийх;

|link:{freebsd-mobile-url}[freebsd-mobile]
|Хөдөлгөөнт тооцооллын тухай хэлэлцүүлгүүд

|link:{freebsd-mono-url}[freebsd-mono]
|FreeBSD дээрх Mono болон C# програмууд

|link:{freebsd-mozilla-url}[freebsd-mozilla]
|Mozilla-г FreeBSD руу порт хийх

|{freebsd-multimedia}
|Мультимедиа програмууд

|link:{freebsd-new-bus-url}[freebsd-new-bus]
|Шугамын архитектурын тухай техникийн хэлэлцүүлгүүд

|link:{freebsd-net-url}[freebsd-net]
|Сүлжээний хэлэлцүүлэг ба TCP/IP эх код

|link:{freebsd-numerics-url}[freebsd-numerics]
|libm функцуудын өндөр чанартай шийдлийн тухай хэлэлцүүлгүүд

|link:{freebsd-office-url}[freebsd-office]
|FreeBSD дээрх Оффисын програмууд

|link:{freebsd-performance-url}[freebsd-performance]
|Өндөр хурдтай ажиллагаа/ачааллын суулгалтуудад зориулсан ажиллагааг тааруулах асуултууд

|link:{freebsd-perl-url}[freebsd-perl]
|Perl-тэй холбоотой портуудын арчилгаа

|link:{freebsd-pf-url}[freebsd-pf]
|Пакет шүүгч галт ханын системийн тухай хэлэлцүүлэг болон асуултууд

|link:{freebsd-platforms-url}[freebsd-platforms]
|Intel(R) биш архитектур тавцангууд руу порт хийх талаар

|link:{freebsd-ports-url}[freebsd-ports]
|Портын цуглуулгын тухай хэлэлцүүлэг

|link:{freebsd-ports-announce-url}[freebsd-ports-announce]
|Портын цуглуулгын тухай чухал мэдээнүүд болон зааврууд (зохицуулалттай)

|link:{freebsd-ports-bugs-url}[freebsd-ports-bugs]
|Портын алдаанууд/PR-уудын тухай хэлэлцүүлэг

|link:{freebsd-ppc-url}[freebsd-ppc]
|FreeBSD-г PowerPC(R) руу порт хийх

|link:{freebsd-proliant-url}[freebsd-proliant]
|HP ProLiant сервер тавцангууд дээрх FreeBSD-ийн тухай техникийн хэлэлцүүлэг

|link:{freebsd-python-url}[freebsd-python]
|FreeBSD-тэй холбоотой Python-ий асуудлууд

|link:{freebsd-rc-url}[freebsd-rc]
|[.filename]#rc.d# систем болон түүний хөгжүүлэлттэй холбоотой хэлэлцүүлэг

|link:{freebsd-realtime-url}[freebsd-realtime]
|FreeBSD-ийн realtime өргөтгөлүүдийн хөгжүүлэлт

|link:{freebsd-ruby-url}[freebsd-ruby]
|FreeBSD-тэй холбоотой Ruby-ийн хэлэлцүүлэг

|link:{freebsd-scsi-url}[freebsd-scsi]
|SCSI дэд систем

|{freebsd-security}
|FreeBSD-д нөлөөлөх аюулгүй байдлын асуудлууд

|link:{freebsd-small-url}[freebsd-small]
|Embedded буюу авсаар програмуудад FreeBSD-г ашиглах (хуучин; үүний оронд link:{freebsd-embedded-url}[freebsd-embedded]-г ашигла)

|link:{freebsd-snapshots-url}[freebsd-snapshots]
|FreeBSD хөгжүүлэлтийн хормын хувилбарын зарууд

|link:{freebsd-sparc64-url}[freebsd-sparc64]
|FreeBSD-г SPARC(R) дээр суурилсан системүүдэд порт хийх

|link:{freebsd-standards-url}[freebsd-standards]
|C99 болон POSIX(R) стандартуудтай FreeBSD-ийн нийцтэй байдал

|link:{freebsd-sysinstall-url}[freebsd-sysinstall]
|man:sysinstall[8]-ийн хөгжүүлэлт

|link:{freebsd-tcltk-url}[freebsd-tcltk]
|FreeBSD-ийн Tcl/Tk хэлэлцүүлэг

|link:{freebsd-threads-url}[freebsd-threads]
|FreeBSD дээрх урсгалжилт

|link:{freebsd-tilera-url}[freebsd-tilera]
|Tilera төрлийн CPU-ууд руу FreeBSD-г порт хийх тухай хэлэлцүүлэг

|link:{freebsd-tokenring-url}[freebsd-tokenring]
|FreeBSD дээрх Token Ring-ийн дэмжлэг

|link:{freebsd-toolchain-url}[freebsd-toolchain]
|FreeBSD-д багтдаг хэрэгслүүдийн цуглуулгын тухай хэлэлцүүлэг

|link:{freebsd-usb-url}[freebsd-usb]
|USB-д зориулсан FreeBSD-ийн дэмжлэгийн тухай хэлэлцүүлэг

|link:{freebsd-virtualization-url}[freebsd-virtualization]
|FreeBSD-ийн дэмждэг төрөл бүрийн виртуалчлалтын техникүүдийн талаарх хэлэлцүүлэг

|link:{freebsd-vuxml-url}[freebsd-vuxml]
|VuXML дэд бүтцийн тухай хэлэлцүүлэг

|link:{freebsd-x11-url}[freebsd-x11]
|FreeBSD дээрх X11-ийн арчилгаа ба дэмжлэг

|link:{freebsd-xen-url}[freebsd-xen]
|FreeBSD-ийн Xen(TM) портын хэлэлцүүлэг - шийдэл ба хэрэглээ

|link:{freebsd-xfce-url}[freebsd-xfce]
|FreeBSD дээрх XFCE - порт хийх ба арчилгаа

|link:{freebsd-zope-url}[freebsd-zope]
|FreeBSD дээрх Zope - порт хийх ба арчилгаа
|===

_Хязгаарлагдмал жагсаалтууд:_ Дараах жагсаалтууд нь илүү тусгайлсан (болон шаардаж байгаа) олон нийтэд зориулагдсан бөгөөд ерөнхий нийтийн сонирхлыг татахгүй байж болох юм. Эдгээр хязгаарлагдмал жагсаалтуудын аль нэг уруу элсэхээсээ өмнө техникийн жагсаалтуудад орох нь зүйтэй юм. Ингэснээр та харилцааны ёс дүрмийг ойлгох болно.

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Жагсаалт
| Зорилго

|link:{freebsd-hubs-url}[freebsd-hubs]
|Толин тусгал сайтуудыг ажиллуулж байгаа хүмүүс (дэд бүтцийн дэмжлэг)

|link:{freebsd-user-groups-url}[freebsd-user-groups]
|Хэрэглэгчийн бүлгийн зохицуулалт

|link:{freebsd-wip-status-url}[freebsd-wip-status]
|FreeBSD-ийн Work-In-Progress буюу хийгдэж байгаа ажлуудын төлөв

|link:{freebsd-wireless-url}[freebsd-wireless]
|802.11 стек, хэрэгслүүд, драйверын хөгжүүлэлтийн талаарх хэлэлцүүлэг
|===

_Digest буюу товч мэдээллийн жагсаалтууд:_ Дээрх бүх жагсаалтууд нь товч хэлбэрээр байдаг. Жагсаалтад бүртгүүлсний дараа та өөрийн бүртгэлийн тохируулгуудын хэсэгт товч мэдээлэл хүлээж авах тохируулгуудыг өөрчилж болно.

_SVN жагсаалтууд:_ Дараах жагсаалтууд нь эх модны төрөл бүрийн талбарууд дахь өөрчлөлтүүдийн тухай бүртгэлийн мэдэгдлүүдийг харахыг хүссэн хүмүүст зориулагдсан байдаг. Тэдгээр нь _Зөвхөн Уншигдах_ жагсаалтууд бөгөөд тэдгээр рүү захидал илгээх ёсгүй юм.

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Жагсаалт
| Эх талбар
| Талбарын тайлбар (зориулагдсан эх)

|link:{svn-doc-all-url}[svn-doc-all]
|[.filename]#/usr/doc#
|doc Subversion репозиторын бүх өөрчлөлтүүд ( [.filename]#user#, [.filename]#projects# ба [.filename]#translations# бусад)

|link:{svn-doc-head-url}[svn-doc-head]
|[.filename]#/usr/doc#
|doc Subversion репозиторын "head" салбарын бүх өөрчлөлтүүд

|link:{svn-doc-projects-url}[svn-doc-projects]
|[.filename]#/usr/doc/projects#
|doc Subversion репозиторын [.filename]#projects# талбарын бүх өөрчлөлтүүд

|link:{svn-doc-svnadmin-url}[svn-doc-svnadmin]
|[.filename]#/usr/doc#
|doc Subversion репозиторын удирдлагын скриптүүд, hook, болон бусад тохиргооны өгөгдлийн бүх өөрчлөлтүүд

|link:{svn-ports-all-url}[svn-ports-all]
|[.filename]#/usr/ports#
|Портын Subversion репозиторын бүх өөрчлөлтүүд

|link:{svn-ports-head-url}[svn-ports-head]
|[.filename]#/usr/ports#
|Портын Subversion репозиторын "head" салбарын бүх өөрчлөлтүүд

|link:{svn-ports-svnadmin-url}[svn-ports-svnadmin]
|[.filename]#/usr/ports#
|Портын Subversion репозиторын удирдлагын скриптүүд, hook, болон бусад тохиргооны өгөгдлийн бүх өөрчлөлтүүд

|{svn-src-all}
|[.filename]#/usr/src#
|src Subversion репозиторын бүх өөрчлөлтүүд ([.filename]#user# болон [.filename]#projects#-с бусад)

|{svn-src-head}
|[.filename]#/usr/src#
|src Subversion репозиторын "head" салбарын бүх өөрчлөлтүүд (FreeBSD-CURRENT салбар)

|link:{svn-src-projects-url}[svn-src-projects]
|[.filename]#/usr/projects#
|src Subversion репозиторын [.filename]#projects# талбарын бүх өөрчлөлтүүд

|link:{svn-src-release-url}[svn-src-release]
|[.filename]#/usr/src#
|src Subversion репозиторын [.filename]#releases# талбарын бүх өөрчлөлтүүд

|link:{svn-src-releng-url}[svn-src-releng]
|[.filename]#/usr/src#
|src Subversion репозиторын [.filename]#releng# салбаруудын бүх өөрчлөлтүүд (аюулгүй байдал / хувилбар инженерчлэлийн салбарууд)

|link:{svn-src-stable-url}[svn-src-stable]
|[.filename]#/usr/src#
|src Subversion репозиторын бүх тогтвортой салбаруудын бүх өөрчлөлтүүд

|link:{svn-src-stable-6-url}[svn-src-stable-6]
|[.filename]#/usr/src#
|src Subversion репозиторын [.filename]#stable/6# салбарын бүх өөрчлөлтүүд

|link:{svn-src-stable-7-url}[svn-src-stable-7]
|[.filename]#/usr/src#
|src Subversion репозиторын [.filename]#stable/7# салбарын бүх өөрчлөлтүүд

|link:{svn-src-stable-8-url}[svn-src-stable-8]
|[.filename]#/usr/src#
|src Subversion репозиторын [.filename]#stable/8# салбарын бүх өөрчлөлтүүд

|{svn-src-stable-9}
|[.filename]#/usr/src#
|src Subversion репозиторын [.filename]#stable/9# салбарын бүх өөрчлөлтүүд

|link:{svn-src-stable-other-url}[svn-src-stable-other]
|[.filename]#/usr/src#
|src Subversion репозиторын хуучин [.filename]#stable# салбаруудын бүх өөрчлөлтүүд

|link:{svn-src-svnadmin-url}[svn-src-svnadmin]
|[.filename]#/usr/src#
|src Subversion репозиторын удирдлагын скриптүүд, хуукууд, болон бусад тохиргооны өгөгдлийн бүх өөрчлөлтүүд

|link:{svn-src-user-url}[svn-src-user]
|[.filename]#/usr/src#
|src Subversion репозиторын туршилтын [.filename]#user# талбарын бүх өөрчлөлтүүд

|link:{svn-src-vendor-url}[svn-src-vendor]
|[.filename]#/usr/src#
|src Subversion репозиторын үйлдвэрлэгчийн ажлын талбарын бүх өөрчлөлтүүд
|===

[[eresources-subscribe]]
=== Хэрхэн бүртгүүлэх вэ

Жагсаалтанд бүртгүүлэхийн тулд дээр байгаа жагсаалтын нэрэн дээр дарах юм уу эсвэл {mailman-lists-url} руу очоод сонирхож байгаа жагсаалт дээрээ дарах хэрэгтэй. Жагсаалтын хуудас бүртгүүлэхэд хэрэгтэй бүх заавруудыг агуулсан байх ёстой.

Өгөгдсөн жагсаалт уруу илгээхийн тулд ердөө л mailto:жагсаалтын_нэр@FreeBSD.org[жагсаалтын_нэр@FreeBSD.org] хаяг уруу захидал илгээнэ. Дараа нь захидлын жагсаалтын дэлхий даяарх гишүүдэд тараагдах болно.

Жагсаалтаас гарахын тулд жагсаалтаас хүлээн авсан цахим захидал бүрийн доор байрлах URL дээр дарах хэрэгтэй. Өөрийгөө бүртгэлээс хасахын тулд бас цахим захидал mailto:жагсаалтын_нэр-unsubscribe@FreeBSD.org[жагсаалтын_нэр-unsubscribe@FreeBSD.org] руу илгээж болно.

Дахин хэлэхэд бид техникийн захидлын жагсаалтуудад техникийн талын зүйлс хэлэлцэхийг танаас хүсэж байна. Хэрэв та зөвхөн чухал зарлалуудыг сонирхож байгаа бол та {freebsd-announce}-д бүртгүүлэх нь зүйтэй юм. Энэ жагсаалт нь зөвхөн мэдээллийн сийрэг урсгалд зориулагдсан юм.

[[eresources-charters]]
=== Жагсаалтын дүрэм, журмууд

FreeBSD-ийн _бүх_ захидлын жагсаалтууд нь тодорхой нэг үндсэн дүрмүүдтэй байдаг. Тэдгээрийг ашиглаж байгаа болгон дагаж мөрдөх ёстой. Эдгээр заавруудыг дагахгүй байх тохиолдолд FreeBSD Postmaster mailto:postmaster@FreeBSD.org[postmaster@FreeBSD.org]-с хоёр (2) анхааруулга бичгээр ирэх бөгөөд үүний дараа гурав дахь удаагаа зөрчсөн тохиолдолд илгээгчийг FreeBSD-ийн бүх захидлын жагсаалтаас хасаж тэдгээр рүү дахиж илгээхийг нь шүүх болно. Бид ийм дүрмүүд, арга хэмжээнүүд байгаад харамсаж байгаа боловч өнөөгийн Интернэт нь маш танхай балмад орчин юм шиг санагддаг бөгөөд олон хүмүүс эдгээрийн арга замууд ямар эмзэг болохыг хүндэтгэдэггүй билээ.

Дагаж мөрдөх дүрэм, журмууд:

* Аль ч илгээлтийн сэдэв нь илгээгдсэн жагсаалтынхаа үндсэн дүрэм, журмыг дагаж мөрдөж байх ёстой, өөрөөр хэлбэл хэрэв жагсаалт техникийн асуудлуудын талаар бол таны илгээж байгаа захидал техникийн хэлэлцүүлэг агуулсан байх ёстой. Хамааралгүй үргэлжлэх чалчаа эсвэл уурлаж шатсан байдал нь захидлын жагсаалтын утгыг түүн дээр байгаа бүхний хувьд алдагдуулж тэвчихгүй байдалд хүргэнэ. Ямар ч тодорхой сэдэвгүй чөлөөт хэлбэрийн хэлэлцүүлэгт зориулсан {freebsd-chat} хэлэлцүүлэг чөлөөтэй байдаг бөгөөд үүнийг ашиглах ёстой юм.
* 2-оос илүү захидлын жагсаалтад зэрэг илгээж болохгүй бөгөөд зөвхөн 2 хүртэлхийг хэрэв тодорхой, илт хэрэгцээ байгаа тохиолдолд хоёр жагсаалт уруу илгээхийг зөвшөөрдөг. Ихэнх жагсаалтуудын хувьд аль хэдийн маш их хэмжээний бүртгэгдсэн хүмүүс давхацдаг бөгөөд ихэнх тусгай зориулагдсан холилдлуудыг ("-stable & -scsi" гэх мэт) тооцохгүй юм бол нэгэн зэрэг нэг жагсаалтаас олон жагсаалт уруу илгээх шалтгаан жинхэнэдээ байхгүй юм. Хэрэв мэдээ ийм замаар `Cc` мөрөн дээр олон захидлын жагсаалттайгаар тань руу илгээгдсэн бол дахин илгээхээсээ өмнө `Cc` мөрийг бас авч хаях ёстой юм. _ Анхлан эхлэгч нь хэн байгаагаас үл хамааран та олон жагсаалт уруу илгээх өөрийн илгээлтүүдийнхээ төлөө хариуцлага бас хүлээх ёстой юм._
* Хувь хүн рүү чиглэсэн халдлагууд болон гутаан доромжлол нь (маргаан) зөвшөөрөгддөггүй бөгөөд энэ нь хэрэглэгчид болон хөгжүүлэгчдийг адилхан хамардаг. Зөвшөөрөөгүй байхад эсвэл зөвшөөрөл өгөгдөхөөргүй байхад хувийн захиаг нээх эсвэл дахин илгээх зэрэг сүлжээн дэх харилцааны бүдүүлэг үйлдлүүд сайшаагддаггүй боловч хүчээр таслан зогсоогддоггүй. _Гэхдээ_ жагсаалтын дүрэм, журмын хүрээнд ийм агуулга таарах зарим цөөн тохиолдол бас байдаг бөгөөд ийм тохиолдолд анхааруулга явуулах (эсвэл хөөх) арга хэмжээнүүдийг тухай бүрт нь авч болох юм.
* FreeBSD-тэй холбоогүй бүтээгдэхүүнүүд эсвэл үйлчилгээнүүдийг сурталчлахыг хатуугаар хориглодог бөгөөд хэрэв зөрчигч спамаар сурталчилж байгаа нь илт байвал түүнийг нэн даруй хөөхөд хүргэнэ.

_Жагсаалт бүрийн дүрэм, журмууд:_

{freebsd-acpi}::
_ACPI болон тэжээлийн удирдлагын хөгжүүлэлт_

link:{freebsd-afs-url}[freebsd-afs]::
_Andrew File System_ буюу Эндрю файлын систем
+
Энэ жагсаалт нь AFS-г CMU/Transarc-аас порт хийж ашиглах тухай хэлэлцүүлэгт зориулагдсан

{freebsd-announce}::
_Чухал үйл явдлууд / түүхийн гол үеүүд_
+
Энэ нь FreeBSD-ийн чухал үйл явдлуудын тухай тохиолдлын зарлалуудыг сонирхсон хүмүүст зориулагдсан захидлын жагсаалт юм. Үүнд хормын хувилбарууд болон бусад хувилбаруудын тухай зарлалууд багтдаг. Энэ нь бас FreeBSD-ийн шинэ боломжуудын зарлалуудыг агуулдаг. Сайн дурынхныг уриалах гэх мэтийг бас агуулж болох юм. Энэ нь бага ачаалалтай, чанд хянагдсан захидлын жагсаалт юм.

link:{freebsd-arch-url}[freebsd-arch]::
_Архитектур болон дизайны хэлэлцүүлгүүд_
+
Энэ жагсаалт нь FreeBSD-ийн архитектурын хэлэлцүүлэгт зориулагдсан. Захианууд нь ихэвчлэн маш техникийн шинж чанартай байх болно. Тохиромжтой сэдвүүдийн жишээг дурдвал:

** Нэгэн зэрэг хэд хэдэн өөрчлөн тохируулсан бүтээлтүүдийг ажиллуулахын тулд бүтээх системийг хэрхэн засаж сэлбэх талаар.
** Heidemann буюу Хайдеман давхаргуудыг ажиллуулахын тулд VFS-д юуг засварлах ёстой талаар.
** Ижил драйверуудыг олон шугамууд болон архитектурууд дээр цэвэрхэн ашиглаж чаддаг байхын тулд төхөөрөмжийн драйверийн интерфэйсийг хэрхэн өөрчлөх талаар.
** Сүлжээний драйверийг хэрхэн бичих талаар.

link:{freebsd-bluetooth-url}[freebsd-bluetooth]::
_FreeBSD дээрх Bluetooth(R)_
+
Энэ нь FreeBSD-ийн Bluetooth(R) хэрэглэгчид цугладаг хэлэлцүүлэг юм. Дизайны асуудлууд, шийдлийн тухай дэлгэрэнгүй зүйлс, засварууд, алдааны тайлангууд, төлвийн тайлангууд, боломжийн хүсэлтүүд, итгэмжлэн оруулсан зүйлсийн бүртгэлүүд болон Bluetooth(R)-тай холбоотой бусад бүх зүйлс энэ жагсаалтаар хэлэлцэгддэг.

link:{freebsd-bugbusters-url}[freebsd-bugbusters]::
_Асуудал Тайлагналттай (Problem Report) ажиллах хүчин чармайлтын зохицуулалт_
+
Энэ жагсаалтын зорилго нь Алдааны маэстро (Bugmeister), түүний Цох нядлагчид (Bugbusters) болон PR мэдээллийн баазад үнэн сэтгэлээсээ сонирхолтой бусад талуудад зориулсан зохицуулалт болон хэлэлцүүлэг болон үйлчлэх явдал юм. Энэ жагсаалт нь тусгайлсан алдаанууд, засварууд юм уу эсвэл PR-уудын тухай хэлэлцүүлгүүдэд зориулагдаагүй.

link:{freebsd-bugs-url}[freebsd-bugs]::
_Алдааны тайлангууд_
+
Энэ нь FreeBSD дээрх алдаануудыг тайлагнахад зориулагдсан захидлын жагсаалт юм. Алдаануудыг аль болох man:send-pr[1] тушаалыг ашиглах юм уу эсвэл түүний link:https://www.FreeBSD.org/send-pr/[ВЭБ интерфэйс]ийг ашиглан илгээх ёстой.

link:{freebsd-chat-url}[freebsd-chat]::
_FreeBSD-ийн хүрээнийхэнд хамаагүй техникийн бус зүйлс_
+
Энэ жагсаалт нь бусад жагсаалтаас хальсан техникийн бус, нийгмийн мэдээллийг агуулдаг. Жордан хүүхэлдэйн киноны өмхий хүрэнтэй адил уу эсвэл үгүй юу, томоор бичих үү эсвэл үгүй юу, хэн хэтэрхий их кофе ууж байна, хамгийн шилдэг пиво хаана исгэж байна, хэн подвалдаа пиво исгэж байна гэх мэт хэлэлцүүлгүүд үүнд багтдаг. Чухал үйл явдлуудын (болох үдэшлэгүүд, хуримнууд, төрсөн өдрүүд, шинэ ажлууд гэх мэт) тохиолдлын зарлал техникийн жагсаалтууд уруу хийгдэж болох боловч дараа дараагийн захианууд энэ -chat жагсаалт уруу заагдах ёстой байдаг.

link:{freebsd-chromium-url}[freebsd-chromium]::
_FreeBSD-тэй холбоотой Chromium-ийн хэлэлцүүлэг_
+
Энэ жагсаалт нь FreeBSD-д зориулсан Chromium-ийн дэмжлэгийг хэлэлцэхэд зориулагдсан. Энэ нь Chromium-ийн хөгжүүлэлт болон суулгалтыг хэлэлцэх техникийн жагсаалт юм.

{core-name}::
_FreeBSD гол баг_
+
Энэ нь гол гишүүдийн ашиглахад зориулсан дотоод захидлын жагсаалт юм. FreeBSD-тэй холбоотой чухал зүйлийг шүүх эсвэл өндөр түвшний нарийвчилсан нягтлал хийх шаардлагатай үед захидлууд энэ жагсаалт уруу илгээгдэж болно.

{freebsd-current}::
_FreeBSD-CURRENT-г ашиглах тухай хэлэлцүүлэг_
+
Энэ нь FreeBSD-CURRENT-ийн хэрэглэгчдэд зориулсан захидлын жагсаалт юм. Хэрэглэгчдэд нөлөөлөх -CURRENT-с гарсан шинэ боломжуудын тухай анхааруулгууд болон -CURRENT байхын тулд хийх алхмуудын заавруудыг энэ жагсаалт агуулдаг. "CURRENT"-г ашиглаж байгаа хэн бүхэн энэ жагсаалтад бүртгүүлэх ёстой. Энэ нь техникийн чанартай агуулгыг хатуу чанд хүлээж байдаг техникийн захидлын жагсаалт юм.

link:{freebsd-cvsweb-url}[freebsd-cvsweb]::
_FreeBSD CVSweb төсөл_
+
FreeBSD-CVSweb-ийн хэрэглээ, хөгжүүлэлт болон арчилгааны тухай техникийн хэлэлцүүлгүүд.

link:{freebsd-desktop-url}[freebsd-desktop]::
_Десктоп дээр FreeBSD-г ашиглах бас сайжруулах_
+
Энэ хэлэлцүүлэг нь десктоп дээрх FreeBSD-н талаар юм. Десктоп руу хөрвүүлэгчид болон хэрэглэгчдийн хувьд FreeBSD-н десктопын дэмжлэгийг сайжруулах болон түүнтэй холбоотой асуудлуудыг хэлэлцэхэд зориулсан гол талбар юм.

link:{freebsd-doc-url}[freebsd-doc]::
_Баримтжуулах төсөл_
+
Энэ захидлын жагсаалт нь FreeBSD-д зориулсан баримтжуулалтыг үүсгэхтэй холбоотой төслүүд болон асуудлуудын хэлэлцүүлэгт зориулсан билээ. Энэ захидлын жагсаалтын гишүүдийг бүхэлд нь "FreeBSD баримтжуулах төсөл" гэдэг. Энэ нь нээлттэй жагсаалт юм; чөлөөтэй нэгдэж хувь нэмрээ оруулаарай!

link:{freebsd-drivers-url}[freebsd-drivers]::
_FreeBSD-д зориулж төхөөрөмжийн драйверууд бичих_
+
Энэ нь FreeBSD дээрх төхөөрөмжийн драйверуудтай холбоотой техникийн хэлэлцүүлгүүдэд зориулсан форум юм. FreeBSD цөм дэх API-уудыг ашиглан төхөөрөмжийн драйверуудыг хэрхэн бичих талаар төхөөрөмжийн драйвер бичигчдийн асуух тэр талбар юм.

link:{freebsd-eclipse-url}[freebsd-eclipse]::
_Eclipse IDE, хэрэгслүүд, клиентийн баялаг програмууд болон портуудын FreeBSD хэрэглэгчид._
+
Энэ жагсаалтын зорилго нь FreeBSD тавцан дээр Eclipse IDE, хэрэгслүүд, клиентийн баялаг програмуудыг сонгох, суулгах, ашиглах, хөгжүүлэх болон арчлах, Eclipse IDE болон залгаасуудыг FreeBSD орчин уруу порт хийхэд туслахтай холбоотой бүх зүйлсэд зориулж хамтын дэмжлэгийг хангах явдал юм.
+
Eclipse хүрээнийхэн болон FreeBSD хүрээнийхэнд хоёуланд нь ашигтай байхаар тэдгээрийн хооронд мэдээлэл солилцохыг хөнгөвчлөх бас зорилготой юм.
+
Энэ жагсаалт нь Eclipse хэрэглэгчдийн хэрэглээн дээр үндсэндээ анхаарал тавьдаг боловч бас Eclipse тогтолцоог ашиглан FreeBSD програмуудыг хөгжүүлэхийг хүссэн хүмүүст зориулсан форум болдог. 

link:{freebsd-embedded-url}[freebsd-embedded]::
_FreeBSD-г суулгагдсан авсаар програмуудад ашиглах_
+
Энэ жагсаалт нь FreeBSD-г суулгагдсан програмуудад ашиглахтай холбоотой сэдвүүдийг хэлэлцдэг. Энэ нь зөвхөн техникийн агуулга хүлээж байдаг техникийн захидлын жагсаалт юм. Энэ жагсаалтын зорилгын хувьд бид суулгагдсан системүүдийг тодорхойлдог бөгөөд эдгээр системүүд нь ширээний системүүд биш бөгөөд тооцоолох ерөнхий орчнуудад зориулагдаагүй тодорхой нэг зорилгоор ашиглагддаг тооцоолох төхөөрөмжүүд юм. Жишээнүүдэд бүх төрлийн утасны харилцуурууд, чиглүүлэгчүүд, шилжүүлэгчүүд болон PBX-үүд, алсын хэмжих төхөөрөмж, PDA-ууд, Point of Sale буюу POS системүүд гэх зэрэг орох бөгөөд зөвхөн энд дурдагдсанаар хязгаарлагдахгүй юм.

link:{freebsd-emulation-url}[freebsd-emulation]::
_Линукс/MS-DOS(R)/Windows(R) зэрэг бусад системүүдийн эмуляц_
+
Бусад үйлдлийн системүүдэд зориулж бичигдсэн програмуудыг FreeBSD дээр ажиллуулахтай холбоотой техникийн хэлэлцүүлгүүдэд зориулсан форум юм. 

link:{freebsd-eol-url}[freebsd-eol]::
_FreeBSD төслийн дэмжихээ больсон FreeBSD-тэй холбоотой програм хангамжуудын тэгш дэмжлэг._
+
Энэ жагсаалт нь FreeBSD төслийн албан ёсны (өөрөөр хэлбэл аюулгүй байдлын зөвлөгөөнүүд болон засваруудын хэлбэрээр) дэмжлэг үзүүлэхээ больсон FreeBSD-тэй холбоотой програм хангамжийн дэмжлэг үзүүлэх эсвэл ашиглахыг хүссэн хүмүүст зориулагдсан юм.

link:{freebsd-firewire-url}[freebsd-firewire]::
_FireWire(R) (iLink, IEEE 1394)_
+
Энэ нь FreeBSD дээр FireWire(R) (IEEE 1394, бас iLink гэгддэг) дэд системийн дизайн болон шийдлийн хэлэлцүүлэгт зориулсан захидлын жагсаалт юм. Хамааралтай сэдвүүдэд ялангуяа стандартууд, шугамын төхөөрөмжүүд болон тэдгээрийн протоколууд, адаптер хавтангууд/картууд/бичил схемүүд, тэдгээрийг зөв дэмжих кодын архитектур болон шийдэл ордог.

link:{freebsd-fs-url}[freebsd-fs]::
_Файлын системүүд_
+
FreeBSD файлын системтэй холбоотой хэлэлцүүлгүүд. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-gecko-url}[freebsd-gecko]::
_Gecko Rendering Engine_
+
Энэ нь FreeBSD дээр Gecko програмуудыг ашиглах талаар хэлэлцэх хэлэлцүүлэг юм.
+
FreeBSD дээрх Gecko портын програмуудыг тойрсон хэлэлцүүлэг, тэдгээрийн суулгалт, хөгжүүлэлт болон дэмжлэг.

link:{freebsd-geom-url}[freebsd-geom]::
_GEOM_
+
GEOM болон түүнтэй холбоотой шийдлүүдтэй холбоотой хэлэлцүүлгүүд. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-gnome-url}[freebsd-gnome]::
_GNOME_
+
FreeBSD системүүдэд зориулсан GNOME Ширээний орчны тухай хэлэлцүүлгүүд. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-infiniband-url}[freebsd-infiniband]::
_FreeBSD дээрх Infiniband_
+
FreeBSD дээрх Infiniband, OFED ба OpenSM-ийн талаар хэлэлцдэг техникийн захидлын жагсаалт.

link:{freebsd-ipfw-url}[freebsd-ipfw]::
_IP Firewall буюу галт хана_
+
Энэ нь FreeBSD дээрх IP галт ханын кодыг дахин дизайн хийхтэй холбоотой техникийн хэлэлцүүлгүүдэд зориулсан форум юм. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-ia64-url}[freebsd-ia64]::
_FreeBSD-г IA64 руу порт хийх_
+
Энэ нь FreeBSD-г Intel(R)-ийн IA-64 тавцан руу порт хийхээр идэвхтэйгээр ажиллаж байгаа хувь хүмүүст зориулсан, асуудлууд гаргаж тавих юм уу эсвэл өөр шийдлүүдийн талаар хэлэлцэх техникийн захидлын жагсаалт юм. Техникийн хэлэлцүүлгийг дагах сонирхолтой хувь хүмүүс бас нэгдэж болох юм.

link:{freebsd-isdn-url}[freebsd-isdn]::
_ISDN холбоонууд_
+
Энэ нь FreeBSD-д зориулсан ISDN-ий дэмжлэгийн хөгжүүлэлтийг хэлэлцэхэд зориулсан захидлын жагсаалт юм.

link:{freebsd-java-url}[freebsd-java]::
_Java(TM) хөгжүүлэлт_
+
Энэ нь FreeBSD дээр чухал Java(TM) програмуудыг хөгжүүлэх болон JDK(TM)-г порт хийх болон арчлах талаар хэлэлцэхэд зориулсан захидлын жагсаалт юм.

[[eresources-charters-jobs]]
link:{freebsd-jobs-url}[freebsd-jobs]::
_Санал болгож байгаа болон хайж байгаа ажлууд_
+
Энэ нь FreeBSD-тэй ялангуяа холбоотой ажлын мэдэгдлүүд болон CV/resume-үүдийг илгээх зориулалттай форум юм. Өөрөөр хэлбэл хэрэв та FreeBSD-тэй холбоотой ажил хайж байгаа эсвэл танд FreeBSD оролцсон зарлах ажил байгаа бол энэ нь зөв газар юм. Энэ нь ерөнхий ажилтай холбоотой асуудлуудад зориулсан захидлын жагсаалт _биш_ юм. Учир нь түүнд зориулсан тохирсон форумууд хаа нэгтээ аль хэдийн байдаг.
+
Энэ жагсаалт нь бусад `FreeBSD.org` захидлын жагсаалтуудын адил дэлхий даяар тардаг. Тиймээс та байрлал болон аялах эсвэл шинэ газар нүүхтэй холбоотой туслалцаа байгаа эсэх тэр хир хэмжээг ойлгосон байх хэрэгтэй.
+
Цахим захидлууд нь нээлттэй хэлбэршилтүүдийг ашиглах ёстой - цэвэр текстийг аль болох эрхэмлэсэн байх ёстой боловч Portable Document Format (PDF), HTML, болон бусад цөөн хэдэн хэлбэршилт ихэнх уншигчдын хувьд хүлээж авах боломжтой байдаг. Microsoft(R) Word ([.filename]#.doc#) зэрэг хаалттай хэлбэршилтүүдээс захидлын жагсаалтын сервер татгалзах болно.

link:{freebsd-kde-url}[freebsd-kde]::
_KDE_
+
FreeBSD системүүд дээрх KDE-тэй холбоотой хэлэлцүүлгүүд. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-hackers-url}[freebsd-hackers]::
_Техникийн хэлэлцүүлгүүд_
+
Энэ нь жагсаалт нь FreeBSD-тэй холбоотой техникийн хэлэлцүүлгүүдэд зориулагдсан. Энэ нь техникийн анхдагч захидлын жагсаалт юм. Энэ нь FreeBSD дээр идэвхтэйгээр ажиллаж байгаа хувь хүмүүст асуудлууд гаргаж тавих эсвэл өөр шийдлүүдийг хэлэлцэхэд нь зориулагджээ. Техникийн хэлэлцүүлгийг дагах сонирхолтой хувь хүмүүс нэгдэхэд дуртайяа байх болно. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-hardware-url}[freebsd-hardware]::
_FreeBSD тоног төхөөрөмжийн ерөнхий хэлэлцүүлэг_
+
FreeBSD-ийн ажиллаж байгаа тоног төхөөрөмжийн төрлүүд, төрөл бүрийн асуудлууд болон юу худалдаж авах эсвэл авахгүй байхтай холбоотой саналуудын тухай ерөнхий хэлэлцүүлэг.

link:{freebsd-hubs-url}[freebsd-hubs]::
_Толин тусгал сайтууд_
+
FreeBSD толин тусгал сайтуудыг ажиллуулж байгаа хүмүүст зориулсан зарлалууд ба хэлэлцүүлэг.

link:{freebsd-isp-url}[freebsd-isp]::
_Интернэтийн үйлчилгээ үзүүлэгчдэд зориулсан асуудлууд_
+
Энэ захидлын жагсаалт нь FreeBSD ашиглаж байгаа Интернэтийн үйлчилгээ үзүүлэгчидтэй (ISP-ууд) холбоотой сэдвүүдийг хэлэлцэхэд зориулагдсан. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-mono-url}[freebsd-mono]::
_FreeBSD дээрх Mono болон C# програмууд_
+
Энэ нь FreeBSD дээрх Mono хөгжүүлэлтийн тогтолцоотой хамааралтай хэлэлцүүлгүүдэд зориулагдсан жагсаалт юм. Энэ нь техникийн захидлын жагсаалт юм. Энэ нь FreeBSD рүү Mono болон C# програмуудыг хөрвүүлэхэхээр идэвхтэйгээр ажиллаж байгаа хүмүүс асуудлууд тавих эсвэл өөр боломжит шийдлүүдийг хэлэлцэхэд зориулагдсан юм. Техникийн хэлэлцүүлгүүдийг сонирхож дагах гэсэн хүмүүс бас оролцох боломжтой юм.

link:{freebsd-office-url}[freebsd-office]::
_FreeBSD дээрх Оффисын програмууд_
+
Хэлэлцүүлэг FreeBSD дээрх оффисын програмууд, тэдгээрийг суулгах, хөгжүүлэх болон дэмжлэгийн талаар голчлон хэлэлцдэг.

link:{freebsd-ops-announce-url}[freebsd-ops-announce]::
_Төслийн дэд бүтцийн талаарх мэдээлэл_
+
Энэ захидлын жагсаалт нь FreeBSD.org төслийн дэд бүтэцтэй холбоотой асуудлууд болон өөрчлөлтүүдийг сонирхсон хүмүүст зориулагдсан.
+
Энэ зохицуулагдсан жагсаалт зөвхөн мэдээлэл, зард зориулагдсан бөгөөд хариулт, хүсэлт, хэлэлцүүлэг болон санал бодолд зориулагдаагүй.

link:{freebsd-performance-url}[freebsd-performance]::
_FreeBSD-г тааруулах эсвэл хурдлуулах тухай хэлэлцүүлгүүд_
+
Энэ захидлын жагсаалт нь хакерууд, администраторууд ба/эсвэл оролцож байгаа талууд FreeBSD-тэй хамаатай ажиллагаатай холбоотой сэдвүүдийг хэлэлцэхэд зориулсан талбар юм. Хүлээж авах боломжтой сэдвүүдэд их ачаалалтай, ажиллагааны асуудлуудтай учирч байгаа эсвэл FreeBSD-ийн хязгааруудад тулж байгаа FreeBSD суулгацуудын тухай хэлэлцүүлэг ордог. FreeBSD-ийн ажиллагааг сайжруулах талаар ажиллах сонирхолтой талуудыг энэ жагсаалтад бүртгүүлэхэд туйлаас дэмждэг. Энэ нь FreeBSD-г хурдан, хүчирхэг, өргөжих боломжтой болгох сонирхолтой, туршлагатай FreeBSD хэрэглэгчид, хакерууд эсвэл администраторуудад туйлын таарсан техникийн жагсаалт юм. Энэ нь баримтыг уншсанаар орлуулж болох асуулт хариултын жагсаалт биш боловч хувь нэмэр оруулах юм уу эсвэл хариулагдаагүй бөгөөд ажиллагаатай холбоотой сэдвүүдийн талаар лавлаж болох талбар юм.

link:{freebsd-pf-url}[freebsd-pf]::
_Пакет шүүгч галт ханын системийн тухай хэлэлцүүлэг ба асуултууд_
+
Пакет шүүгч (pf) галт ханын системийн тухай FreeBSD-тэй холбоотой хэлэлцүүлэг. Техникийн хэлэлцүүлэг болон хэрэглэгчийн асуултууд аль алийг хэлэлцэх боломжтой. Энэ жагсаалт нь ALTQ QoS тогтолцоог хэлэлцэх бас талбар юм.

link:{freebsd-pkg-url}[freebsd-pkg]::
_Бинар багцын удирдлага болон багцын хэрэгслүүдийн хэлэлцүүлэг_
+
FreeBSD систем дээр програм суулгахдаа бинар багцын хэрэгслүүд, хэлбэрүүд, тэдгээрийн хөгжүүлэлт ба FreeBSD дээрх багцын репозиторын удирдлага дахь дэмжлэг болон гуравдагч талуудын багцууд зэрэг бинар багцуудыг ашиглахтай хоблоотой бүхий л төрлийн хэлэлцүүлэг.
+
Багц үүсгэхдээ зөв үүсгэдэггүй портуудын талаарх хэлэлцүүлэг нь портын асуудалд хамаатай бөгөөд энэ жагсаалтад хамаарахгүй.

link:{freebsd-platforms-url}[freebsd-platforms]::
_Intel(R) биш тавцангууд руу порт хийх_
+
Тавцан хоорондох FreeBSD-ийн асуудлууд, ерөнхий хэлэлцүүлэг ба Intel(R) биш FreeBSD портуудад зориулагдсан төслүүд. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-ports-url}[freebsd-ports]::
_"Портуудын" хэлэлцүүлэг_
+
FreeBSD-ийн "портын цуглуулга" ([.filename]#/usr/ports#), портын дэд бүтэц болон портын ерөнхий зохицуулалтын чармайлтуудын тухай хэлэлцүүлгүүд. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-ports-announce-url}[freebsd-ports-announce]::
_FreeBSD "Портын цуглуулгын" тухай чухал мэдээнүүд болон зааврууд_
+
"Портын цуглуулгын" ([.filename]#/usr/ports#) хөгжүүлэгчид, порт хийгчид болон хэрэглэгчдэд зориулсан архитектур/дэд бүтцийн өөрчлөлтүүд, шинэ боломжууд, маш чухал шинэчлэх зааврууд болон хувилбар инженерчлэлийн мэдээлэл зэрэг чухал мэдээнүүд. Энэ нь бага ачаалалтай захидлын жагсаалт бөгөөд зарлалд зориулагдсан.

link:{freebsd-ports-bugs-url}[freebsd-ports-bugs]::
_"Портуудын" алдаануудын хэлэлцүүлэг_
+
FreeBSD-ийн "портын цуглуулга"д ([.filename]#/usr/ports#) зориулсан асуудлын тайлангууд, санал болгогдож байгаа портууд эсвэл портуудад хийгдэх өөрчлөлтүүдтэй холбоотой хэлэлцүүлгүүд. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-proliant-url}[freebsd-proliant]::
_HP Proliant сервер тавцангууд дээрх FreeBSD-ийн техникийн хэлэлцүүлэг_
+
Энэ захидлын жагсаалт нь Proliant-тай холбоотой драйверууд, удирдлагын програм хангамж, тохиргооны хэрэгслүүд ба BIOS-ийн шинэчлэлтүүдийн хэлэлцүүлэг зэрэг HP Proliant серверүүд дээрх FreeBSD-ийн хэрэглээний техникийн хэлэлцүүлэгт зориулагдсан талбар юм. Тиймээс энэ нь hpasmd, hpasmcli, болон hpacucli модулиудын талаар хэлэлцэх үндсэн газар юм.

link:{freebsd-python-url}[freebsd-python]::
_FreeBSD дээрх Python_
+
Энэ нь FreeBSD дээр Python дэмжлэгийг сайжруулахтай холбоотой хэлэлцүүлгүүдэд зориулсан жагсаалт юм. Энэ нь техникийн захидлын жагсаалт юм. Энэ нь Python, түүний гуравдагч талуудын модулиуд болон Zope-ийн юмсыг FreeBSD руу порт хийхээр ажиллаж байгаа хувь хүмүүст зориулагдсан юм. Техникийн хэлэлцүүлгийг дагах сонирхолтой хувь хүмүүс нэгдэхэд бас дуртайяа байх болно.

link:{freebsd-questions-url}[freebsd-questions]::
_Хэрэглэгчийн асуултууд_
+
Энэ нь FreeBSD-ийн тухай асуултуудад зориулагдсан захидлын жагсаалт юм. Та асуултаа нэлээн техникийн гэж үзэж байгаагаас бусад тохиолдолд "how to" буюу "хэрхэн яаж" гэсэн асуултуудыг техникийн жагсаалтууд руу илгээх ёсгүй юм.

link:{freebsd-ruby-url}[freebsd-ruby]::
_FreeBSD-тэй холбоотой Ruby-ийн хэлэлцүүлэг_
+
Энэ нь FreeBSD дээрх Ruby-ийн дэмжлэгтэй холбоотой хэлэлцүүлэгт зориулсан жагсаалт юм. Энэ нь техникийн захидлын жагсаалт юм. Ruby портууд, гуравдагч сангууд болон тогтолцоонууд дээр ажиллаж байгаа хувь хүмүүст зориулсан юм.
+
Техникийн хэлэлцүүлгийг дагах сонирхолтой хувь хүмүүс нэгдэхэд бас дуртайяа байх болно.

link:{freebsd-scsi-url}[freebsd-scsi]::
_SCSI дэд систем_
+
Энэ нь FreeBSD-д зориулагдсан SCSI дэд систем дээр ажиллаж байгаа хүмүүст зориулсан захидлын жагсаалт юм. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

{freebsd-security}::
_Аюулгүй байдлын асуудлууд_
+
FreeBSD компьютерийн аюулгүй байдлын асуудлууд (DES, Kerberos, мэдэгдэж байгаа аюулгүй байдлын цоорхойнууд болон засварууд гэх мэт). Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг. Энэ нь асуулт, хариултын жагсаалт биш гэдгийг санах хэрэгтэй, гэхдээ FAQ-д хувь нэмэр оруулахыг (асуулт, хариултын аль нь ч байсан гэсэн) дэмждэг.

{freebsd-security-notifications}::
_Аюулгүй байдлын мэдэгдлүүд_
+
FreeBSD-ийн аюулгүй байдлын асуудлууд ба засваруудын мэдэгдлүүд. Энэ нь хэлэлцүүлгийн жагсаалт биш юм. Хэлэлцүүлгийн жагсаалт нь FreeBSD-security юм.

link:{freebsd-small-url}[freebsd-small]::
_FreeBSD-г суулгагдсан програмууд дээр ашиглах_
+
Энэ жагсаалт нь ердийн биш жижиг ба суулгагдсан авсаар FreeBSD суулгацуудтай холбоотой сэдвүүдийг хэлэлцдэг. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.
+

[NOTE]
====
Энэ жагсаалт нь link:{freebsd-embedded-url}[freebsd-embedded]-р хуучирч ашиглагдахаа больсон.
====

link:{freebsd-snapshots-url}[freebsd-snapshots]::
_FreeBSD хөгжүүлэлтийн хормын хувилбарын зарууд_
+
Энэ жагсаалт нь FreeBSD-н хөгжүүлэлтийн head/ ба stable/ салбарын шинэ хормын хувилбарууд гарсан талаар мэдээлнэ.

{freebsd-stable}::
_FreeBSD-STABLE-ийн хэрэглээний тухай хэлэлцүүлэг_
+
Энэ нь FreeBSD-STABLE-ийн хэрэглэгчдэд зориулсан захидлын жагсаалт юм. Хэрэглэгчдэд нөлөөлөх -STABLE-с гарсан шинэ боломжуудын тухай анхааруулгууд болон -STABLE байхын тулд хийх алхмуудын заавруудыг энэ жагсаалт агуулдаг. "STABLE"-г ашиглаж байгаа хэн бүхэн энэ жагсаалтад бүртгүүлэх хэрэгтэй. Энэ жагсаалт нь техникийн захидлын жагсаалт бөгөөд зөвхөн техникийн агуулгыг хүлээж байдаг.

link:{freebsd-standards-url}[freebsd-standards]::
_C99 & POSIX нийцтэй байдал_
+
Энэ нь C99 болон POSIX стандартуудтай FreeBSD хэрхэн нийцэж байгаатай холбоотой техникийн хэлэлцүүлгүүдэд зориулагдсан форум юм.

link:{freebsd-toolchain-url}[freebsd-toolchain]::
_FreeBSD-д багтдаг хэрэгслүүдийн цуглуулгын үйлчилгээ_
+
Энэ захидлын жагсаалт нь FreeBSD-тэй цуг ирдэг хэрэгслүүдийн цуглуулгын үйлчилгээтэй холбоотой хэлэлцүүлэгт зориулагдсан. Энэ сэдэвт Clang болон GCC-ийн төлөв бас асемблер, линкер болон дибаг хийгч зэрэг програм хангамжууд багтаж болно.

link:{freebsd-usb-url}[freebsd-usb]::
_USB-д зориулсан FreeBSD-ийн дэмжлэгийг хэлэлцэх_
+
Энэ нь USB-д зориулсан FreeBSD-ийн дэмжлэгтэй холбоотой техникийн хэлэлцүүлгүүдэд зориулсан захидлын жагсаалт юм.

link:{freebsd-user-groups-url}[freebsd-user-groups]::
_Хэрэглэгчийн бүлгийн зохицуулалтын жагсаалт_
+
Энэ нь бүс нутгийн Хэрэглэгчдийн бүлэг бүрийн зохицуулагчид нэг нэгэнтэйгээ болон гол багийн хариуцсан хүнтэй юмс хэлэлцэхэд зориулагдсан захидлын жагсаалт юм. Энэ захидлын жагсаалт нь ерөнхий агуулгууд болон хэрэглэгчийн бүлгүүдэд тархсан төслүүдийн зохицуулалтад тааран хязгаарлагдсан байх ёстой.

link:{freebsd-virtualization-url}[freebsd-virtualization]::
_FreeBSD-ийн дэмждэг төрөл бүрийн виртуалчлалын техникүүдийн талаарх хэлэлцүүлэг_
+
FreeBSD-ийн дэмждэг төрөл бүрийн виртуалчлалын техникүүдийн талаар хэлэлцэх жагсаалт. Нэг талаасаа үндсэн ажиллагааны шийдэл болон шинэ техникүүд нэмэх тал дээр төвлөрөх болно. Нөгөө талаасаа хэрэглэгчдэд ямар нэг асуудал гарсан үед тусламж гуйх эсвэл өөрсдийнхөө хэрэглээний тохиолдлуудыг хэлэлцэх хэлэлцүүлэг байх болно.

link:{freebsd-wip-status-url}[freebsd-wip-status]::
_FreeBSD-ийн Work-In-Progress буюу хийгдэж байгаа ажлуудын төлөв_
+
Энэхүү захидлын жагсаалтыг FreeBSD-тэй холбоотой өөрийн эхлүүлж байгаа ажил болон түүний явцыг зарлахад ашиглаж болох юм. Захидлууд нь хянагддаг. Илүү сэдэвт ойр FreeBSD-ийн жагсаалт руу "To:" дээр хаягийг бичин, харин энэ жагсаалт руу "BCC:" хийж захидлыг илгээх нь зүйтэй юм. Энэ жагсаалтад хэлэлцүүлэг зөвшөөрөгддөггүй учир ингэснээр таны WIP бас тухайн сэдэвтэй холбоотой жагсаалтад хэлэлцэгдэх боломжтой юм.
+
Тохиромжтой захидлуудын жишээг архиваас үзнэ үү.
+
Энэ жагсаалтад явуулсан захидлуудын редакторын тоймыг FreeBSD-ийн вэб хуудсанд хэдэн сар тутам Төлвийн Тайлангийн  хэсэг болгон тавьж болох юм. Тэндээс илүү олон жишээнүүд болон хуучин тайлангуудыг та бас олж болох юм.

link:{freebsd-wireless-url}[freebsd-wireless]::
_802.11 стек, хэрэгслүүд, драйверын хөгжүүлэлтийн талаарх хэлэлцүүлэг_
+
FreeBSD-wireless жагсаалт нь 802.11 стек (sys/net80211), төхөөрөмжийн драйвер болон хэрэгслүүдийг хөгжүүлэхтэй холбоотой асуудлыг хэлэлцэхэд зориулагдсан. Үүнд цоорхой, шинэ боломжууд болон арчлахтай холбоотой асуудлууд багтана.

link:{freebsd-xen-url}[freebsd-xen]::
_FreeBSD-ийн Xen(TM) портын хэлэлцүүлэг - шийдэл ба хэрэглээ_
+
Энэ жагсаалт нь FreeBSD-ийн Xen(TM) портын талаар хэлэлцдэг. Захидлын урсгалын түвшин бага болохоор дизайны нарийн зүйлсүүд ба шийдлийн техникийн хэлэлцүүлэг болон хэрэгжүүлэхтэй холбоотой удирдлагын асуудлуудыг хэлэлцэхээр зориулагдсан.

link:{freebsd-xfce-url}[freebsd-xfce]::
_XFCE_
+
Энэхүү хэлэлцүүлэг нь XFCE орчинг FreeBSD-д оруулахтай хамааралтай юм. Энэ нь техникийн захидлын жагсаалт юм. XFCE-г FreeBSD рүү порт хийхээр идэвхтэй ажиллаж байгаа хүмүүст асуудлыг тавих эсвэл өөр шийдэл ярилцахад нь зориулагдсан юм. Техникийн хэлэлцүүлгийг дагаж унших сонирхолтой хүмүүс бас бүртгүүлж болно.

link:{freebsd-zope-url}[freebsd-zope]::
_Zope_
+
Энэхүү хэлэлцүүлэг нь Zope орчинг FreeBSD-д оруулахтай хамааралтай юм. Энэ нь техникийн захидлын жагсаалт юм. Zope-г FreeBSD рүү порт хийхээр идэвхтэй ажиллаж байгаа хүмүүст асуудлыг тавих эсвэл өөр шийдэл ярилцахад нь зориулагдсан юм. Техникийн хэлэлцүүлгийг дагаж унших сонирхолтой хүмүүс бас бүртгүүлж болно.

[[eresources-mailfiltering]]
=== Захидлын жагсаалтууд дээрх шүүлт

FreeBSD-ийн захидлын жагсаалтууд нь спам, вирус, болон бусад хүсээгүй цахим захидлуудаас сэргийлэхийн тулд олон аргаар шүүгддэг. Энэ хэсэгт тайлбарласан шүүлт хийх үйлдлүүд нь захидлын жагсаалтуудыг хамгаалахад хэрэглэгддэг бүх зүйлсийг хамрахгүй.

Захидлын жагсаалтад зөвхөн тодорхой төрлийн хавсралтууд зөвшөөрөгддөг. Доорх жагсаалтад дурдагдаагүй MIME агуулгын төрөл бүхий бүх хавсралтууд захидлын жагсаалтад цахим захидал түгээгдэхээс өмнө авагддаг.

* application/octet-stream
* application/pdf
* application/pgp-signature
* application/x-pkcs7-signature
* message/rfc822
* multipart/alternative
* multipart/related
* multipart/signed
* text/html
* text/plain
* text/x-diff
* text/x-patch

[NOTE]
====
Зарим захидлын жагсаалтууд бусад MIME агуулгын төрлийн хавсралтуудыг зөвшөөрч болох боловч дээрх жагсаалт нь захидлын жагсаалтуудын ихэнх хэсэгт хамаарах болно.
====

Хэрэв цахим захидал HTML болон цэвэр текст хувилбарыг хоёуланг агуулж байвал HTML хувилбарыг устгах болно. Хэрэв цахим захидал зөвхөн HTML хувилбарыг агуулж байвал энэ нь цэвэр текст рүү хөрвүүлэгдэх болно.

[[eresources-news]]
== Usenet Newsgroups буюу мэдээний бүлгүүд

FreeBSD-ийн хоёр тусгай мэдээний бүлгээс гадна FreeBSD-н талаар хэлэлцдэг юм уу эсвэл FreeBSD хэрэглэгчидтэй холбоотой бусад олон бүлгүүд байдаг.

=== BSD-тэй холбоотой мэдээний бүлгүүд

* link:news:comp.unix.bsd.freebsd.announce[comp.unix.bsd.freebsd.announce]
* link:news:comp.unix.bsd.freebsd.misc[comp.unix.bsd.freebsd.misc]
* link:news:de.comp.os.unix.bsd[de.comp.os.unix.bsd] (German)
* link:news:fr.comp.os.bsd[fr.comp.os.bsd] (French)
* link:news:it.comp.os.freebsd[it.comp.os.freebsd] (Italian)

=== Бусад сонирхол татахуйц UNIX(R)-ийн мэдээний бүлгүүд

* link:news:comp.unix[comp.unix]
* link:news:comp.unix.questions[comp.unix.questions]
* link:news:comp.unix.admin[comp.unix.admin]
* link:news:comp.unix.programmer[comp.unix.programmer]
* link:news:comp.unix.shell[comp.unix.shell]
* link:news:comp.unix.user-friendly[comp.unix.user-friendly]
* link:news:comp.security.unix[comp.security.unix]
* link:news:comp.sources.unix[comp.sources.unix]
* link:news:comp.unix.advocacy[comp.unix.advocacy]
* link:news:comp.unix.misc[comp.unix.misc]
* link:news:comp.unix.bsd[comp.unix.bsd]

=== X Цонхот Систем

* link:news:comp.windows.x.i386unix[comp.windows.x.i386unix]
* link:news:comp.windows.x[comp.windows.x]
* link:news:comp.windows.x.apps[comp.windows.x.apps]
* link:news:comp.windows.x.announce[comp.windows.x.announce]
* link:news:comp.windows.x.intrinsics[comp.windows.x.intrinsics]
* link:news:comp.windows.x.motif[comp.windows.x.motif]
* link:news:comp.windows.x.pex[comp.windows.x.pex]
* link:news:comp.emulators.ms-windows.wine[comp.emulators.ms-windows.wine]

[[eresources-web]]
== Word Wide Web серверүүд

[[eresources-web-social]]
=== Форум, блог, болон нийгмийн сүлжээнүүд

* http://forums.freebsd.org/[FreeBSD-ийн форумууд] нь FreeBSD-ийн асуултууд болон техникийн хэлэлцүүлэгт зориулсан вэб дээр суурилсан хэлэлцүүлгийн форумууд юм.
* http://planet.freebsdish.org/[FreeBSD-ийн ертөнц] нь FreeBSD-ийн хөгжүүлэгчдийн бичсэн хэдэн арван блог дээрх мэдээллийг цуглуулж харуулах боломжийг бүрдүүлдэг. Олон хөгжүүлэгч юун дээр ажиллаж байгаагаа болон шинэ нөхөөсүүд ба бусад хийгдэж байгаа ажлуудынхаа талаар илгээхдээ үүнийг ашигладаг.
* http://www.youtube.com/bsdconferences[YouTube суваг дээрх BSD-ийн хурлууд] нь дэлхий даяар болсон BSD хурлуудын өндөр чанартай видеонуудын цуглуулгыг агуулдаг. Энэ нь гол хөгжүүлэгчдийн FreeBSD дээрх өөрсдийн шинэ ажлуудынхаа талаар илтгэл тавихыг нь үзэх шилдэг арга юм.

[[eresources-web-mirrors]]
=== Албан ёсны толин хуудаснууд

[[eresources-email]]
== Цахим захидлын хаягууд

Дараах хэрэглэгчийн бүлгүүд нь FreeBSD-тэй холбоотой цахим захидлын хаягуудыг өөрсдийн гишүүддээ хангадаг. Жагсаагдсан администратор нь хаягийг буруугаар ашигласан тохиолдолд цуцлах эрхийг эдэлдэг.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Домэйн
| Боломжууд
| Хэрэглэгчийн бүлэг
| Администратор

|ukug.uk.FreeBSD.org
|Зөвхөн дамжуулах
| mailto:ukfreebsd@uk.FreeBSD.org[ukfreebsd@uk.FreeBSD.org]
|Ли Жонстон mailto:lee@uk.FreeBSD.org[lee@uk.FreeBSD.org]
|===
