#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD$
#    $FreeBSDde: de-docproj/books/Makefile.inc,v 1.4 2001/02/01 21:24:27 alex Exp $
#

DESTDIR?=	${DOCDIR}/de_DE.ISO8859-1/books/${.CURDIR:T}
