#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD: doc/de_DE.ISO_8859-1/books/Makefile,v 1.1 2000/08/06 14:44:20 alex Exp $
#    $FreeBSDde: de-docproj/books/Makefile,v 1.4 2001/02/01 21:24:27 alex Exp $
#

SUBDIR=		faq handbook

ROOT_SYMLINKS=	handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
