#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD$
#    $FreeBSDde: de-docproj/books/Makefile,v 1.7 2009/02/10 11:36:13 jkois Exp $
#

SUBDIR=		developers-handbook
SUBDIR+=	faq
SUBDIR+=	fdp-primer
SUBDIR+=	handbook
SUBDIR+=	porters-handbook

ROOT_SYMLINKS=	handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
