#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD$
#    $FreeBSDde: de-docproj/books/Makefile.inc,v 1.7 2002/04/06 18:44:10 ue Exp $
#    basiert auf: 1.4
#

DESTDIR?=	${DOCDIR}/de_DE.ISO8859-1/books/${.CURDIR:T}
