#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD$
#    $FreeBSDde: de-docproj/books/Makefile,v 1.5 2003/10/27 23:11:08 mheinen Exp $
#

SUBDIR =	faq
SUBDIR+=	fdp-primer
SUBDIR+=	handbook

ROOT_SYMLINKS=	handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
