#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD$
#    $FreeBSDde: de-docproj/books/Makefile.inc,v 1.8 2002/04/12 05:57:24 mheinen Exp $
#    basiert auf: 1.4
#

DESTDIR?=	${DOCDIR}/de_DE.ISO8859-1/books/${.CURDIR:T}
