# ACPI project page
#
# $FreeBSD$

MAINTAINER=	marks

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
DATA=	style.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
