---
title: "A FreeBSD Dokumentációs Projekt: A dokumentációs csomag"
sidenav: docs
---

= A FreeBSD Dokumentációs Projekt: A dokumentációs csomag

A FreeBSD dokumentációja három fõ kategóriára osztható:

. http://www.FreeBSD.org/cgi/man.cgi[*A man oldalak*]
+
A projekt ezzel nem igazán foglalkozik, mert ez az alaprendszer részét képezi. Kivételt képez ez alól a japán csapat, õk lefordítják ezeket az oldalakat is. Nincs akadálya azonban, hogy mások is így tegyenek.
+
Nem arról van szó, hogy a man oldalak nem fontosak, egyáltalán nem! Egyszerûen csak annyira kötõdnek a FreeBSD néhány részéhez, hogy a legtöbb esetben a legalkalmasabb ember, aki lefordíthatná ezeket az, aki a FreeBSD azon részét írta.
. link:../../docs/books/[*Könyvek*]
+
A projekt sok olyan dokumentációval rendelkezik, melyek már "`könyv terjedelmûek`", vagy azok lesznek. Ezek közé tartozik a FreeBSD GYIK és a FreeBSD kézikönyv.
. link:../../docs/books/#articles[*Cikkek*]
+
A FreeBSD-t érintõ hatalmas információmennyiség érhetõ el rövidebb cikkek formájában, hasonlóan más projektek oktatóanyagaihoz vagy HOGYAN leírásaihoz.

link:..[A FreeBSD Dokumentációs Projekt kezdõlapja]
