---
title: "A Magyar FreeBSD Dokumentációs Projekt"
sidenav: docs
---

include::shared/hu/urls.adoc[]

= A Magyar FreeBSD Dokumentációs Projekt

== A Projekt célja

A FreeBSD Dokumentációs Projekt által létrehozott dokumentációk felölelnek ugyan minden témát, de ezek a dokumentumok az angol nyelv amerikai követelményei szerint íródtak, hiszen az angol nyelv vált az informatika "`hivatalos`" nyelvévé. A Magyar FreeBSD Dokumentációs Projekt célja, hogy egy egységes magyar nyelvû dokumentációt nyújtson az angol nyelvismerettel egyáltalán nem rendelkezõ, vagy angol nyelvet kevésbé jól értõ felhasználók számára.

== Hogyan segíthetünk?

Lefordíthatunk egy még le nem fordított angol nyelvû dokumentumot, vagy akár saját magunk is írhatunk új dokumentumokat. Mind az angol, mind a magyar nyelvû dokumentumok link:../sgml/[SGML] nyelven készülnek, így az angol nyelv ismerete mellett az SGML nyelv alapjaival is tisztában kell lennünk, valamint követnünk kell az link:{fdp-primer}[A FreeBSD Dokumentációs Projekt irányelvei kezdõknek] címû könyv tartalmi és formai elõírásait.

== Kapcsolat

Kövesdán Gábor <gabor@FreeBSD.org>
