---
title: "FreeBSD Documentation Project: Documentation Set"
sidenav: docs
---

include::shared/hu/urls.adoc[]

= FreeBSD Documentation Project: Documentation Set

A projekt néhány ember laza csoportja, akikben csupán az a közös, hogy feliratkoztak a mailto:FreeBSD-doc@FreeBSD.org[freebsd-doc] levelezési listára.

Néhányan közülünk közvetlenül végezhetnek módosításokat a FreeBSD dokumentációján. Az ilyen jogosultsággal rendelkezõ fejlesztõk teljes listáját link:{contributors}#staff-committers[itt], a FreeBSD Dokumentációs Projekt fontosabb tagjainak listáját pedig link:../../administration/#t-doceng[itt] tekinthetjük meg.

Mások jogosultságok nélkül is folyamatosan írhatnak és beküldhetnek dokumentációkat. Miután a dokumentáció beküldésre került, a link:../submitting/[Dokumentáció beküldése] oldalon leírtak szerint, a jogosultsággal rendelkezõk egyike átnézi és beilleszti a dokumentációba.

Amennyiben segíteni szeretnénk a Dokumentációs Projekt munkáját (reményeink szerint igen), csupán annyit kell tennünk, hogy a feliratkozunk az elõbb említett levelezési listára és résztveszünk a feladatokban. Ha mindezt megtettük, immáron mi magunk is a projekt tagjai vagyunk.

link:..[A FreeBSD Dokumentációs Projekt kezdõlapja]

link:../hungarian/[A Magyar FreeBSD Dokumentációs Projekt kezdõlapja]
