# $Id: Makefile,v 1.1 1998-07-27 05:44:04 hanai Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

DOCS=	qnewsletter.sgml

DOCS+=	qnewsletter-1-1.sgml
DOCS+=	qnewsletter-1-2.sgml
DOCS+=	qnewsletter-1-3.sgml

.include "../../web.mk"
