# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/news/1997/Makefile,v 1.1 2000/10/11 16:19:22 phantom Exp $
# Original revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=	index.sgml

.include "../../web.mk"
