# $Id: Makefile,v 1.2 1998-08-11 01:18:36 wosch Exp $

.if exists("../Makefile.conf")
.include "../Makefile.conf"
.endif

DOCS=	license.sgml
DOCS+=	daemon.sgml

DATA+= COPYING COPYING.LIB

.include "../web.mk"
