#
# The FreeBSD Simplified Chinese Project
# Original Revision: 1.52
#
# $FreeBSD$

SUBDIR =
SUBDIR+= contributing
SUBDIR+= cvs-freebsd
SUBDIR+= linux-users
SUBDIR+= nanobsd
SUBDIR+= rc-scripting
SUBDIR+= remote-install

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
