#
# The FreeBSD Simplified Chinese Project
# Original Revision: 1.52
#
# $FreeBSD$

SUBDIR =
SUBDIR+= contributing
SUBDIR+= nanobsd

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
