---
title: "Проект FreeBSD Java®: FAQ"
sidenav: developers
---

include::shared/ru/urls.adoc[]

= Проект FreeBSD Java(R): FAQ

== Содержание

. <<q1,Существует ли JDK(R) 1.3 для FreeBSD?>>
. <<q2,Можно ли использовать Linux-Port от команды Blackdown?>>

== Полная версия

[[q1]]
. Существует ли JDK(R) 1.3 для FreeBSD?
Да. Вы можете собрать FreeBSD JDK из исходных текстов или загрузить готовый бинарный дистрибутив. За дальнейшей информацией обращайтесь к основной странице FreeBSD Java.
+
[[q2]]
. Можно ли использовать Linux-Port от команды Blackdown?
Некоторые сообщили, что успешно это сделали. Попробуйте сделать так: Скачайте архивы, распакуйте его куда-нибудь. Теперь примените такой diff-файл: 
....
      --- bin/.java_wrapper.dist      Thu Jun  3 01:14:34 1999
      +++ bin/.java_wrapper   Thu Oct 14 19:17:11 1999
      @@ -31,8 +31,8 @@
      # Resolve symlinks. See 4152645.
      while [ -h "$PRG" ]; do
      ls=`/bin/ls -ld "$PRG"`
      -    link=`/usr/bin/expr "$ls" : '.*-> \(.*\)$'`
      -    if /usr/bin/expr "$link" : '/' > /dev/null; then
      +    link=`/compat/linux/usr/bin/expr "$ls" : '.*-> \(.*\)$'`
      +    if /compat/linux/usr/bin/expr "$link" : '/' > /dev/null; then
      PRG="$link"
      else
      PRG="`/usr/bin/dirname $PRG`/$link"
      @@ -63,7 +63,7 @@
      # Select vm type (if classic vm, also select thread type).
      unset vmtype
      unset ttype
      -DEFAULT_THREADS_FLAG=native
      +DEFAULT_THREADS_FLAG=green
      if [ "x$1" = "x-hotspot" ]; then
      vmtype=hotspot
      ttype=native_threads
      --- jre/bin/.java_wrapper.dist  Thu Jun  3 01:14:34 1999
      +++ jre/bin/.java_wrapper   Thu Oct 14 19:32:06 1999
      @@ -31,8 +31,8 @@
      # Resolve symlinks. See 4152645.
      while [ -h "$PRG" ]; do
      ls=`/bin/ls -ld "$PRG"`
      -    link=`/usr/bin/expr "$ls" : '.*-> \(.*\)$'`
      -    if /usr/bin/expr "$link" : '/' > /dev/null; then
      +    link=`/compat/linux/usr/bin/expr "$ls" : '.*-> \(.*\)$'`
      +    if /compat/linux/usr/bin/expr "$link" : '/' > /dev/null; then
      PRG="$link"
      else
      PRG="`/usr/bin/dirname $PRG`/$link"
      @@ -63,7 +63,7 @@
      # Select vm type (if classic vm, also select thread type).
      unset vmtype
      unset ttype
      -DEFAULT_THREADS_FLAG=native
      +DEFAULT_THREADS_FLAG=green
      if [ "x$1" = "x-hotspot" ]; then
      vmtype=hotspot
      ttype=native_threads
....

Thanks to Makoto MATSUSHITA (matusita@ics.es.osaka-u.ac.jp)
