# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/links/Makefile,v 1.3 2000/11/10 17:04:51 phantom Exp $
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	freebsd.xml
DOCS+=	tools.xml
DOCS+=	api.xml
DOCS+=	index.xml
DOCS+=	tutorials.xml
DOCS+=	development.xml
DOCS+=	resources.xml
DOCS+=	vendor.xml
DOCS+=	documentation.xml
DOCS+=	servlets.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
