---
title: "FreeBSD Internal Pages"
sidenav: docs
---

include::shared/authors.adoc[]
include::shared/en/urls.adoc[]

= FreeBSD Internal Pages

This page contains pointers to pages documenting aspects of the FreeBSD project itself, as viewed separately from the codebase.

== Projects

There are various projects which lie link:../projects/[outside the mainstream development path]. A number of groups are working on the 'cutting edge' to expand FreeBSD's range of capabilities in new directions.

Here is an overview of the link:{freebsd-releng}[FreeBSD Release Engineering Process].

And here you will find the link:../releng/[schedules for upcoming official releases of FreeBSD].

== Policies

To avoid chaos with a project this large spread out all over the globe, there have to be some link:policies[Policies for FreeBSD Committers].

== People

The FreeBSD Project Staff consists of link:../administration[teams, groups and individuals] with designated project roles and areas of responsibility and the link:{contributors}#staff-committers[developers]. By following the links, one will find a list of them, as well as explanations of who is responsible for what.

You can read here core's link:hats[Hat Term Limits Policy] and some guidelines from {imp-name} on link:working-with-hats[how to work with hats].

== Resources

Here is a list of some link:developer[technical resources for FreeBSD committers].

For those with accounts on link:machines[the main FreeBSD.org network], here are the machine resources that are available and the sorts of work they are intended for.

You can learn more link:about[about the FreeBSD WWW server], including the machine, the software, mirroring the FreeBSD web pages.
