---
title: "Charter for the Cluster Administrators"
sidenav: docs
--- 

= Charter for the Cluster Administrators

Lead cluster administrator is a delegated officer role (aka. "hat") that answers to the FreeBSD Core Team and ultimately the FreeBSD community at large. This person shall have the operational authority over the FreeBSD cluster infrastructure (to the extent that the Core Team can delegate this authority) and will be responsible for the following in general:

* Ensure the reliable operation of the Project's equipment and network resources.
* Ensure that the Project's resources are suitably and effectively used to serve the Project's interests.
* Ensure that reasonable security precautions and mitigations are implemented within the constraints of the nature of a highly distributed project.
* Delegate to and coordinating with both the site-specific admin teams and the admins at large.
* Ensure that standard operating procedures, rules, guidelines etc are documented and understandable.
* Take measures to ensure that a competent administrator would be expected to be able to adopt a predecessor's work in a reasonable amount of time.
* Contingency planning and implementation to ensure continuity across site specific problems (including donated site withdrawal or outages).
* Keep the interested parties (Core Team, Security Team, FreeBSD Foundation, Port Management Team, etc), project members and community members appropriately informed.
* Give timely and authoritive answers to questions, or a direct referral to the appropriate party.
* Aid other hat wearers and cluster administrators to get their job done.
* Where practical and appropriate, use the Project's own product as a proving ground.
* Make sure that it is easy for developers to know what hardware resources they have access to for project purposes.

The lead cluster administrator answers to the FreeBSD Core Team. If a party is unhappy with a position that the hat wearer takes and is unable to change their mind, they may take the issue to the Core Team. The Core Team has the final say in the matter. If the lead cluster administrator is a member of the Core Team then a complaint may be made in confidence via the core secretary or another member if desired.

Any of the following still require a sign-off from the Core Team:

* New public facing services.
* Planned withdrawal of public facing services.
* New team members.

Notable interaction with other hats:

* The lead cluster administrator will consult with the Security Officer and the Security Team where appropriate but will be responsible for making decisions. However, the Security Officer may respond to security emergencies involving project infrastructure as necessary.
* The Port Management Team has a large resource footprint and arrangements will be made with them to effectively operate their resources within the constraints of the overall cluster operation.

Earmarked resources:

Some site resources are provided for specific purposes. Any such earmarking or use restrictions will be documented to make sure such resources are used as intended.
