---
title: "FreeBSD Doceng Team Charter"
sidenav: docs
---

include::shared/authors.adoc[]

= FreeBSD Doceng Team Charter

The doceng@ team is a body to handle some of the meta-project issues associated with the FreeBSD Documentation Project. The main responsibilities of this team are:

* To grant approval for new documentation committers. Documentation includes articles and books, website pages, manual pages, release notes and translations of the above. There are two kinds of doc commit bits: translator commit bit, which is limited to translations in a particular language and full commit bit, which is only granted to aspirants, who have shown enough English writing skills.
* To maintain the doc project primer, which documents best practices for the FreeBSD Documentation Project.
* To manage the doc/ release process. This includes coordinating the release documentation updates with the various translation teams, coordinating with the release engineering team to tag the doc/ tree during the release cycle, and documenting these procedures.
* To ensure that the generated documentation (PDF, HTML, etc.) on the Web site and FTP site are up to date with respect to the versions of the documents in the SVN tree. This includes making sure the Web site build is functioning correctly, and also involves working with the admin team to ensure that the primary Web server has all of the requisite software installed (including build scripts).
* To act as MAINTAINER (when necessary) or to work in coordination with existing MAINTAINERs, to ensure that the documentation toolchains (DocBook, groff, etc.) are in good working order.
* To maintain the sanctity of the FreeBSD doc/ tree. Due to the visibility of these files and documents to the outside world, doceng@ reserves the right to immediately backout (or fix without waiting for response from the original committer) changes that introduce broken links, cause the Web site build to break, or otherwise degrade the accessibility of the FreeBSD Web site and documentation.
* To appoint and oversee a FreeBSD Webmaster Team that carries out daily maintenance of the Project web servers in collaboration with other teams.

It is specifically noted here that doceng@ is *not* a conflict resolution body for the FreeBSD Documentation Project. Discussion and consensus on the freebsd-doc mailing list is how the project has conducted itself, and how it is expected to conduct itself in the future.

== Current Membership

The current members of this team are {doceng-members}.

== New Doc Committers

New doc committers are approved by doceng@ with a vote through email and a two week timeout. A committer is approved if at least one doceng@ member votes yes, and no doceng@ members vote no. When a commit bit proposal is accepted, doceng@ sends out an acceptance email to the mentor and the new committer with core@ and accounts@ CC'ed.

== Idle Doc Committers

Doc Committers that have not made a commit in 18 months will be contacted by a doceng@ member and without a response after a delay of 2 weeks, these committers will be automatically removed from the access file. In case of no response, doceng@ will also contact core@ about the idle committers. Committers that wish to get back their commit bits will have to reapply with the appropriate authority.
