---
title: "Commit Bit Expiration Policy"
sidenav: docs
---

= Commit Bit Expiration Policy

== Rationale

Over time, FreeBSD committers may find other demands on their time, and decide that they wish to resign their commit bit.
However, under some circumstances, a committer may become inactive over a long period of time without explicitly resigning their bit.
Over the long term, these accounts can represent a security risk, as well as posing procedural questions regarding the degree to which contact information and access methods for the account are maintainable.
For these reasons, the FreeBSD Core Team approved the following commit bit expiration policy, last updated in February 2021.

== Policy

Documentation and source committers that have not made a commit in 18 months may have their commit bit removed from the access file.
For ports committers this period is 12 months.
Committers are encouraged to reactivate their commit bit by contacting the appropriate authority.

If all of a committer's commit bits expire, then the committer's `FreeBSD.org` account will be suspended.
It can remain active upon request at the FreeBSD Core Team's discretion.
An account is suspended by disabling login access and any other services (such as CGI scripts or non-trivial mail forwarding configurations) that execute under the committer's account.
Simple mail forwarding will continue to work, and an individual may e-mail `postmaster@FreeBSD.org` to update mail forwarding settings.
The committer's files may or may not be preserved at the FreeBSD Core Team's discretion.
A suspended account will be reactivated if any of a committer's commit bits are restored.
