---
title: "Hats Term Limits Policy"
sidenav: docs
--- 

= Hats Term Limits Policy

== Rationale

The FreeBSD Core team appoints several individuals ("hats") that perform critical roles within the project. It is important to reduce single points of failure in these roles. Additionally, turnover in hats can provide fresh insight and help avoid burnout.

The current set of core-appointed hats is core secretary, head release engineer, the security officer, and postmaster.

The FreeBSD Core team has approved the following hats term limits policy. This was first posted to the Developers mailing list on June 22, 2012, and amended in June 2015.

== Policy

An individual may serve as a core-appointed hat given that:

* Core approves their appointment or re-appointment to the role.
* The individual is willing to continue.
* The individual is still able to perform the role effectively.

Hats are appointed at the pleasure of core. Appointments may be rescinded by core at any time where this serves the needs of the project.

Each hat's term begins three months after the start of a core team's two year term and ends three months after the end of the core team's term. Hats are explicitly approved by the new core team at the start of the hat's term.

If a hat becomes vacant during a term, core shall appoint a replacement for the remainder of the term.

Core shall review all hats annually.

In general it is expected that volunteers serving in hat positions will be limited to serving for four consecutive years, rounded up to the first natural review/appointment cycle.

Non volunteers serving in hat positions are still expected to participate in annual reviews and provide for continuity to core's satisfaction.

Each hat must appoint a deputy who can cover their role in the case of absence or illness, and be trained and ready to take over the role (subject to core approval) should the role holder resign before the end of their term.

If a core team is dissolved prematurely, then the next term for each hat will begin three months after the new core team's term begins.

These limits apply to individual hats and not to teams. For teams with a single lead role, the limits shall apply to the lead role. An individual that is not eligible to serve as the lead of a team may continue to serve as a member of the team.
