# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.10

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq2.sgml
DOCS+=	gnome_porting.sgml
DOCS+=	gnome2_porting.sgml
DOCS+=	porting.sgml
DOCS+=	bugging.sgml
DOCS+=  volunteer.sgml
# DOCS+=	knownissues.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
