# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.6

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

#DOCS=	schedule.sgml \
#	relnotes.sgml \
#	announce.sgml
DOCS=	announce.sgml

DATA=	docbook.css \
#	hardware.html \
#	readme.html \
#	installation.html \
#	errata.html \
#	relnotes-detailed.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
