DOCS=	freebsd.sgml tools.sgml api.sgml index.sgml 
DOCS+=	tutorials.sgml development.sgml resources.sgml 
DOCS+=	vendor.sgml documentation.sgml servlets.sgml

WEBBASE=        /data/java

.include "../../web.mk"
