# $FreeBSD$

DOCS =	freebsd.sgml
DOCS+=	tools.sgml
DOCS+=	api.sgml
DOCS+=	index.sgml 
DOCS+=	tutorials.sgml
DOCS+=	development.sgml
DOCS+=	resources.sgml 
DOCS+=	vendor.sgml
DOCS+=	documentation.sgml
DOCS+=	servlets.sgml

.include "../../web.mk"
