#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD$
#    Original revision: 1.3
#

SUBDIR = diskless-x
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= ip-aliasing
SUBDIR+= make-world
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= ntfs
SUBDIR+= ppp
SUBDIR+= programming-tools
SUBDIR+= committers-guide
SUBDIR+= zip-drive
SUBDIR+= ddwg
SUBDIR+= euro
SUBDIR+= java-tomcat
SUBDIR+= dialup-firewall

ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
