#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: doc/fr_FR.ISO8859-1/articles/Makefile.inc,v 1.2 2001/03/13 18:19:22 nik Exp $
#    Original revision: 1.2
#

DESTDIR?=	${DOCDIR}/fr_FR.ISO8859-1/articles/${.CURDIR:T}
