#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD$
#    Original revision: 1.3
#

SUBDIR = building-products
SUBDIR+= committers-guide
SUBDIR+= contributing
SUBDIR+= contributors
SUBDIR+= explaining-bsd
SUBDIR+= filtering-bridges
SUBDIR+= fonts
SUBDIR+= ipsec-must
SUBDIR+= leap-seconds
SUBDIR+= linux-users
SUBDIR+= nanobsd
SUBDIR+= new-users
SUBDIR+= pam
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports

ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
