# $FreeBSD$

SUBDIR =
SUBDIR+= 5-roadmap
SUBDIR+= checkpoint
SUBDIR+= committers-guide
SUBDIR+= console-server
SUBDIR+= contributing
SUBDIR+= contributors
SUBDIR+= cvs-freebsd
SUBDIR+= cvsup-advanced
SUBDIR+= dialup-firewall
SUBDIR+= diskless-x
SUBDIR+= euro
SUBDIR+= explaining-bsd
SUBDIR+= fbsd-from-scratch
SUBDIR+= filtering-bridges
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= freebsd-questions
SUBDIR+= hats
SUBDIR+= hubs
SUBDIR+= ipsec-must
SUBDIR+= java-tomcat
SUBDIR+= laptop
SUBDIR+= mailing-list-faq
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= pam
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports
SUBDIR+= programming-tools
SUBDIR+= pxe
SUBDIR+= releng
SUBDIR+= releng-packages
SUBDIR+= serial-uart
SUBDIR+= solid-state
SUBDIR+= storage-devices
SUBDIR+= vinum
SUBDIR+= vm-design
SUBDIR+= zip-drive

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
