# $FreeBSD: doc/en_US.ISO8859-1/articles/Makefile,v 1.13 2001/06/25 15:10:30 nik Exp $

SUBDIR = committers-guide
SUBDIR+= dialup-firewall
SUBDIR+= diskless-x
SUBDIR+= explaining-bsd
SUBDIR+= filtering-bridges
SUBDIR+= freebsd-questions
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= ipsec-must
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= programming-tools
SUBDIR+= pxe
SUBDIR+= serial-uart
SUBDIR+= solid-state
SUBDIR+= storage-devices
SUBDIR+= vm-design
SUBDIR+= zip-drive

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
