#       $Id: Makefile,v 1.1 1999-08-16 22:09:19 nik Exp $

SUBDIR = diskless-x
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= programming-tools

.include <bsd.subdir.mk>
