# $FreeBSD$
# $FreeBSDde: de-www/Makefile.inc,v 1.2 2001/02/25 11:41:30 alex Exp $
# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
# Original revision: 1.8

WEBBASE?=	/data/de
WEB_PREFIX?=	${.CURDIR}/../..
