---
title: Информация об аппаратной совместимости FreeBSD 15.0
sidenav: download
---

:localRel: 15.0
:doctype: article
:toc: macro
:toclevels: 2
:icons: font
:sectnums:
:source-highlighter: rouge
:experimental:

= Информация об аппаратной совместимости FreeBSD {localRel}

toc::[]

[[intro]]
== Введение

Эта заметка об аппаратной совместимости описывает всё оборудование, которое, как известно, работает с FreeBSD {localRel}.
Другие конфигурации также могут работать, но просто ещё не были протестированы.
Приветствуются отзывы, обновления и исправления этого списка!

[[proc]]
== Поддерживаемые платформы

В этом разделе описываются архитектуры CPU, поддерживаемые в настоящее время проектами платформ FreeBSD, их уровни поддержки и системы, поддерживаемые каждой платформой.

[[proc-amd64]]
=== x86-64

crossref:platforms[amd64,FreeBSD/amd64] поддерживает x86-64 как полностью поддерживаемую, crossref:committers-guide[archs,Уровень 1] архитектуру.
Ожидается, что носители с выпуском будут работать на всех машинах x86-64 с как минимум 256 МБ ОЗУ.
Этот выпуск включает оптимизации и улучшения для использования всех возможностей систем на основе FreeBSD/amd64, обеспечивая повышенную производительность для широкого спектра рабочих нагрузок.

[[proc-arm-64]]
=== AArch64

crossref:platforms[arm64,FreeBSD/aarch64] поддерживает 64-битный ARM (ARMv9 и ARMv8) как crossref:committers-guide[archs,Уровень 1] архитектуру.

В настоящее время поддерживаются следующие устройства:

Ampere Computing:

* Altra Max
* Altra
* eMAG

link:https://wiki.freebsd.org/arm/Allwinner[Allwinner]:

* Allwinner A64 SoC
* A64-Olinuxino
* Orange Pi PC2
* Pine A64
* Pine A64+
* Pine A64+ 2GB
* Pine A64-LTS
* SOPINE
* NanoPi A64
* OrangePi PC2
* NanoPI K1 Plus
* Pine H64
* Orange Pi 3 LTS

AWS / Annapurna Labs:

* Graviton
* Graviton 2
* Graviton 3

Cavium:

* ThunderX

NXP Semiconductors:

* LS1028A SoC
* LS1046A SoC
* LS1088A SoC
* LX2160A SoC
* Conclusive Engineering WHLE-LS1
* SolidRun HoneyComb LX2
* Traverse Technologies Ten64

link:https://wiki.freebsd.org/arm/Raspberry%20Pi[Raspberry Pi]:

* Raspberry Pi Zero 2 W
* Raspberry Pi 3
* Raspberry Pi 4

link:https://wiki.freebsd.org/arm/RockChip[RockChip]:

* RK3328 SoC
* RK3399 SoC
* RK3566 SoC
* RK3568 SoC
* NanoPC-T4
* NanoPi R2S
* NanoPi R2S-Plus
* NanoPi R4S
* Radxa
* Pinebook Pro
* Rock64
* RockPro64

Zedboard:

* Zynq 7000 SoC

[[proc-arm-32]]
=== AArch32

crossref:platforms[armv7,FreeBSD/armv7] поддерживает 32-битный ARM (ARM-v7 и выше) как crossref:committers-guide[archs,Уровень 2] архитектуру.

В настоящее время поддерживаются следующие устройства:

link:https://wiki.freebsd.org/arm/Allwinner[Allwinner]:

* Allwinner A10 SoC
* Allwinner A13/R8 SoC
* Allwinner A20 SoC
* Allwinner A31 & A31s SoC
* Allwinner A83T SoC
* Allwinner H3 & H2+ SoC
* Allwinner H5 SoC
* Allwinner H6 SoC
* Cubieboard
* A10-OlinuXino-Lime
* A13-OLinuXino
* Banana Pi
* CubieBoard 2
* Lamobo R1
* Olimex A20 SOM
* PCDuino3
* BananaPi M3
* Orange Pi +2E
* OrangePi One
* Orange Pi One Lite
* Orange Pi PC
* Orange Pi Zero
* NanoPI NEO

link:https://wiki.freebsd.org/arm/imx6[NXP i.MX6]:

* Wandboard
* CuBox i
* HummingBoard

link:https://wiki.freebsd.org/arm/Raspberry%20Pi[Raspberry Pi]:

* Raspberry Pi 2 (до v1.2)

[[proc-powerpc]]
=== POWER

FreeBSD поддерживает 64-битный POWER как crossref:committers-guide[archs,Уровень 2] архитектуру.

crossref:platforms[powerpc,FreeBSD/powerpc64le] поддерживает 64-битный, двунаправленный POWER9 и POWER8, включая:

IBM:

* Power System LC922 (POWER9)
* Power System IC922 (POWER8)

QEMU

* PowerNV

Raptor CS:

* Talos II (POWER9)
* Blackbird (POWER9)

crossref:platforms[powerpc,FreeBSD/powerpc64] поддерживает 64-битный, обратный порядок байт POWER9 через POWER4, включая вышеперечисленные, а также:

A-EON:

* AmigaONE X5000 (NXP QorIQ P5)

Apple:

* Power Mac G5 (PowerPC 970)
* Xserve G5 (PowerPC 970)

IBM:

* pSeries VM

[[proc-risc-v]]
=== RISC-V

link:https://wiki.freebsd.org/riscv[FreeBSD/riscv64] поддерживает 64-битный RISC-V как crossref:committers-guide[archs,Уровень 2] архитектуру.

Поддержка RISC-V представляет собой важную веху в эволюции этой операционной системы с открытым исходным кодом.
FreeBSD была первой операционной системой, получившей загружаемую поддержку RISC-V в дереве исходного кода, что подчёркивает её приверженность поддержке новых аппаратных архитектур.

FreeBSD в настоящее время поддерживает следующие платформы:

* HiFive Unleashed (SiFive FU540)
* HiFive Unmatched (SiFive FU740)
* StarFive VisionFive 2 (StarFive JH7110)
* Spike
* QEMU

// Раздел "Поддерживаемые устройства" примечаний к выпуску.
// Обычно независимый от процессора, с условным включением текста,
// обрабатывающим любой архитектурно-зависимый текст.

// В каждом подразделе, описывающем класс оборудования
// (т.е. интерфейсы Ethernet), перечисляйте широкие группы устройств
// в алфавитном порядке как абзацы, отсортированные по алфавиту (часто
// эти группы будут упорядочены по производителю, т.е. интерфейсы
// Ethernet от 3Com).

// При необходимости может следовать раздел "Разное" после всех
// других именованных разделов.

// Эти рекомендации не являются жёсткими правилами, и исключения
// будут встречаться. Следование этим рекомендациям (сколь бы
// расплывчатыми они ни были) настоятельно рекомендуется для
// поддержания единообразного форматирования этого раздела.

// Мы даём ссылки на страницы руководств, используя сущности &man, где
// это возможно. Если для драйвера нет страницы руководства
// (и, следовательно, нет сущности &man), мы просто указываем имя драйвера).
// Пожалуйста, избегайте преобразований в сущности &man, если вы
// не уверены, что сущность и страница руководства существуют;
// массовые проверки этого файла для исправления "пропущенных"
// преобразований, вероятно, нарушат сборку.

[[support]]
== Поддерживаемые устройства

В этом разделе описываются устройства, которые, как известно в настоящее время, поддерживаются каждым драйвером устройств в FreeBSD.
Если рассматриваемый драйвер имеет страницу руководства в базовом дистрибутиве FreeBSD (большинство должно иметь), она указана здесь.
Информация об использовании, конфигурации и конкретных моделях поддерживаемых устройств, контроллеров и т.д. может быть найдена на страницах руководств.

[NOTE]
====
Списки устройств в этом документе генерируются автоматически из страниц руководств FreeBSD.
Это означает, что некоторые устройства, которые поддерживаются несколькими драйверами, могут появляться несколько раз.
====

[[disk]]
=== Контроллеры дисков


Драйвер
**aac**
поддерживает следующие Parallel SCSI, SATA и 3G SAS
RAID-контроллеры из семейства Adaptec AAC:

*	Adaptec AAC-364
*	Adaptec RAID 2045
*	Adaptec RAID 2405
*	Adaptec RAID 2445
*	Adaptec RAID 2805
*	Adaptec RAID 3085
*	Adaptec RAID 31205
*	Adaptec RAID 31605
*	Adaptec RAID 5085
*	Adaptec RAID 51205
*	Adaptec RAID 51245
*	Adaptec RAID 51605
*	Adaptec RAID 51645
*	Adaptec RAID 52445
*	Adaptec RAID 5405
*	Adaptec RAID 5445
*	Adaptec RAID 5805
*	Adaptec SAS RAID 3405
*	Adaptec SAS RAID 3805
*	Adaptec SAS RAID 4000SAS
*	Adaptec SAS RAID 4005SAS
*	Adaptec SAS RAID 4800SAS
*	Adaptec SAS RAID 4805SAS
*	Adaptec SATA RAID 2020SA ZCR
*	Adaptec SATA RAID 2025SA ZCR
*	Adaptec SATA RAID 2026ZCR
*	Adaptec SATA RAID 2410SA
*	Adaptec SATA RAID 2420SA
*	Adaptec SATA RAID 2610SA
*	Adaptec SATA RAID 2620SA
*	Adaptec SATA RAID 2810SA
*	Adaptec SATA RAID 2820SA
*	Adaptec SATA RAID 21610SA
*	Adaptec SCSI RAID 2020ZCR
*	Adaptec SCSI RAID 2025ZCR
*	Adaptec SCSI RAID 2120S
*	Adaptec SCSI RAID 2130S
*	Adaptec SCSI RAID 2130SLP
*	Adaptec SCSI RAID 2230SLP
*	Adaptec SCSI RAID 2200S
*	Adaptec SCSI RAID 2240S
*	Adaptec SCSI RAID 3230S
*	Adaptec SCSI RAID 3240S
*	Adaptec SCSI RAID 5400S
*	Dell CERC SATA RAID 2
*	Dell PERC 2/Si
*	Dell PERC 2/QC
*	Dell PERC 3/Si
*	Dell PERC 3/Di
*	Dell PERC 320/DC
*	HP ML110 G2 (Adaptec SATA RAID 2610SA)
*	HP NetRAID 4M
*	IBM ServeRAID 8i
*	IBM ServeRAID 8k
*	IBM ServeRAID 8s
*	ICP RAID ICP5045BL
*	ICP RAID ICP5085BL
*	ICP RAID ICP5085SL
*	ICP RAID ICP5125BR
*	ICP RAID ICP5125SL
*	ICP RAID ICP5165BR
*	ICP RAID ICP5165SL
*	ICP RAID ICP5445SL
*	ICP RAID ICP5805BL
*	ICP RAID ICP5805SL
*	ICP ICP5085BR SAS RAID
*	ICP ICP9085LI SAS RAID
*	ICP ICP9047MA SATA RAID
*	ICP ICP9067MA SATA RAID
*	ICP ICP9087MA SATA RAID
*	ICP ICP9014RO SCSI RAID
*	ICP ICP9024RO SCSI RAID
*	Legend S220
*	Legend S230
*	Sun STK RAID REM
*	Sun STK RAID EM
*	SG-XPCIESAS-R-IN
*	SG-XPCIESAS-R-EX
*	AOC-USAS-S4i
*	AOC-USAS-S8i
*	AOC-USAS-S4iR
*	AOC-USAS-S8iR
*	AOC-USAS-S8i-LP
*	AOC-USAS-S8iR-LP



Драйвер
**aacraid**
поддерживает следующие
Adaptec 6G и 12G SAS/SATA RAID-контроллеры:

*	Adaptec ASR-6405(T|E)
*	Adaptec ASR-6445
*	Adaptec ASR-6805(T|E|Q|TQ)
*	Adaptec ASR-7085
*	Adaptec ASR-7805(Q)
*	Adaptec ASR-70165
*	Adaptec ASR-71605(E|Q)
*	Adaptec ASR-71685
*	Adaptec ASR-72405
*	Adaptec Series 8 cards



Драйвер
**ahc**
поддерживает следующие VL/ISA/PCI Parallel SCSI-контроллеры и карты:

*	Adaptec
	`AIC7770`
	чип хост-адаптера
*	Adaptec
	`AIC7850`
	чип хост-адаптера
*	Adaptec
	`AIC7860`
	чип хост-адаптера
*	Adaptec
	`AIC7870`
	чип хост-адаптера
*	Adaptec
	`AIC7880`
	чип хост-адаптера
*	Adaptec
	`AIC7890`
	чип хост-адаптера
*	Adaptec
	`AIC7891`
	чип хост-адаптера
*	Adaptec
	`AIC7892`
	чип хост-адаптера
*	Adaptec
	`AIC7895`
	чип хост-адаптера
*	Adaptec
	`AIC7896`
	чип хост-адаптера
*	Adaptec
	`AIC7897`
	чип хост-адаптера
*	Adaptec
	`AIC7899`
	чип хост-адаптера
*	Adaptec
	`274X(W)`
*	Adaptec
	`274X(T)`
*	Adaptec
	`2910`
*	Adaptec
	`2915`
*	Adaptec
	`2920C`
*	Adaptec
	`2930C`
*	Adaptec
	`2930U2`
*	Adaptec
	`2940`
*	Adaptec
	`2940J`
*	Adaptec
	`2940N`
*	Adaptec
	`2940U`
*	Adaptec
	`2940AU`
*	Adaptec
	`2940UW`
*	Adaptec
	`2940UW Dual`
*	Adaptec
	`2940UW Pro`
*	Adaptec
	`2940U2W`
*	Adaptec
	`2940U2B`
*	Adaptec
	`2950U2W`
*	Adaptec
	`2950U2B`
*	Adaptec
	`19160B`
*	Adaptec
	`29160B`
*	Adaptec
	`29160N`
*	Adaptec
	`3940`
*	Adaptec
	`3940U`
*	Adaptec
	`3940AU`
*	Adaptec
	`3940UW`
*	Adaptec
	`3940AUW`
*	Adaptec
	`3940U2W`
*	Adaptec
	`3950U2`
*	Adaptec
	`3960`
*	Adaptec
	`39160`
*	Adaptec
	`3985`
*	Adaptec
	`4944UW`
*	Многие материнские платы со встроенной
	`SCSI`
	поддержкой



Драйвер
**ahci**
поддерживает AHCI-совместимые контроллеры, имеющие PCI класс 1 (массовое хранилище),
подкласс 6 (SATA) и программный интерфейс 1 (AHCI).

Также, в сотрудничестве с драйверами atamarvell и atajmicron из ata(4),
он поддерживает AHCI-часть комбинированных контроллеров legacy-PATA + AHCI-SATA,
таких как JMicron JMB36x и Marvell 88SE61xx.

Драйвер
**ahci**
также поддерживает AHCI-устройства, которые действуют как PCI-мосты для
nvme(4)
с использованием Intel Rapid Storage Technology (RST).
Чтобы использовать устройство
nvme(4),
необходимо либо установить режим SATA в BIOS на AHCI (вместо RST),
либо смириться с производительностью при включённом RST из-за разделения прерываний.
FreeBSD
будет автоматически обнаруживать AHCI-устройства с этим расширением, которые находятся
в режиме RST.
Когда это происходит,
**ahci**
присоединяет дочерние
устройства
nvme(4)
к устройству
**ahci**.



Драйвер
**ahd**
поддерживает следующие PCI/PCI-X Parallel SCSI-контроллеры:

*	Adaptec
	`AIC7901`
	чип хост-адаптера
*	Adaptec
	`AIC7901A`
	чип хост-адаптера
*	Adaptec
	`AIC7902`
	чип хост-адаптера
*	Adaptec
	`29320`
	хост-адаптер
*	Adaptec
	`39320`
	хост-адаптер
*	Многие материнские платы со встроенной
	`SCSI`
	поддержкой



Драйвер
**arcmsr**
поддерживает следующие карты:

*	ARC-1110
*	ARC-1120
*	ARC-1130
*	ARC-1160
*	ARC-1170
*	ARC-1110ML
*	ARC-1120ML
*	ARC-1130ML
*	ARC-1160ML
*	ARC-1200
*	ARC-1201
*	ARC-1203
*	ARC-1210
*	ARC-1212
*	ARC-1213
*	ARC-1214
*	ARC-1216
*	ARC-1220
*	ARC-1222
*	ARC-1223
*	ARC-1224
*	ARC-1226
*	ARC-1230
*	ARC-1231
*	ARC-1260
*	ARC-1261
*	ARC-1270
*	ARC-1280
*	ARC-1210ML
*	ARC-1220ML
*	ARC-1231ML
*	ARC-1261ML
*	ARC-1280ML
*	ARC-1380
*	ARC-1381
*	ARC-1680
*	ARC-1681
*	ARC-1880
*	ARC-1882
*	ARC-1883
*	ARC-1884
*	ARC-1886



Драйвер
**ata**
поддерживает интерфейс IDE на следующих ATA/SATA-контроллерах:

Acard:

> ATP850P, ATP860A, ATP860R, ATP865A, ATP865R.

ALI:

> M5228, M5229, M5281, M5283, M5287, M5288, M5289.

AMD:

> AMD756, AMD766, AMD768, AMD8111, CS5536.

ATI:

> IXP200, IXP300, IXP400, IXP600, IXP700, IXP800.

CMD:

> CMD646, CMD646U2, CMD648, CMD649.

Cypress:

> Cypress 82C693.

Cyrix:

> Cyrix 5530.

HighPoint:

> HPT302, HPT366, HPT368, HPT370, HPT371, HPT372, HPT372N, HPT374.

Intel:

> 6300ESB, 31244, PIIX, PIIX3, PIIX4, ESB2, ICH, ICH0, ICH2, ICH3, ICH4, ICH5,
> ICH6, ICH7, ICH8, ICH9, ICH10, SCH, PCH.

ITE:

> IT8211F, IT8212F, IT8213F.

JMicron:

> JMB360, JMB361, JMB363, JMB365, JMB366, JMB368.

Marvell

> 88SE6101, 88SE6102, 88SE6111, 88SE6121, 88SE6141, 88SE6145.

National:

> SC1100.

NetCell:

> NC3000, NC5000.

nVidia:

> nForce, nForce2, nForce2 MCP, nForce3, nForce3 MCP, nForce3 Pro, nForce4,
> MCP51, MCP55, MCP61, MCP65, MCP67, MCP73, MCP77, MCP79, MCP89.

Promise:

> PDC20246, PDC20262, PDC20263, PDC20265, PDC20267, PDC20268, PDC20269, PDC20270,
> PDC20271, PDC20275, PDC20276, PDC20277, PDC20318, PDC20319, PDC20371, PDC20375,
> PDC20376, PDC20377, PDC20378, PDC20379, PDC20571, PDC20575, PDC20579, PDC20580,
> PDC20617, PDC20618, PDC20619, PDC20620, PDC20621, PDC20622, PDC40518, PDC40519,
> PDC40718, PDC40719.

ServerWorks:

> HT1000, ROSB4, CSB5, CSB6, K2, Frodo4, Frodo8.

Silicon Image:

> SiI0680, SiI3112, SiI3114, SiI3512.

SiS:

> SIS180, SIS181, SIS182, SIS5513, SIS530, SIS540, SIS550, SIS620, SIS630,
> SIS630S, SIS633, SIS635, SIS730, SIS733, SIS735, SIS745, SIS961, SIS962,
> SIS963, SIS964, SIS965.

VIA:

> VT6410, VT6420, VT6421, VT82C586, VT82C586B, VT82C596, VT82C596B, VT82C686,
> VT82C686A, VT82C686B, VT8231, VT8233, VT8233A, VT8233C, VT8235, VT8237,
> VT8237A, VT8237S, VT8251, CX700, VX800, VX855, VX900.

Некоторые из вышеперечисленных чипов могут быть настроены для режима AHCI.
В таком случае они поддерживаются драйвером
ahci(4)
вместо этого.

Неизвестные чипсеты ATA поддерживаются в режимах PIO, и если присутствуют стандартные
регистры busmaster DMA и содержат корректные настройки, DMA также
включается, хотя максимальный режим ограничен UDMA33, так как
неизвестно, что может делать чипсет и как его программировать.



Драйвер
**ciss**
поддерживает контроллеры, реализующие
Common Interface for SCSI-3 Support Open Specification v1.04, включая:

*	Compaq Smart Array 5300 (только простой режим)
*	Compaq Smart Array 532
*	Compaq Smart Array 5i
*	HP Smart Array 5312
*	HP Smart Array 6i
*	HP Smart Array 641
*	HP Smart Array 642
*	HP Smart Array 6400
*	HP Smart Array 6400 EM
*	HP Smart Array E200
*	HP Smart Array E200i
*	HP Smart Array P212
*	HP Smart Array P220i
*	HP Smart Array P222
*	HP Smart Array P230i
*	HP Smart Array P400
*	HP Smart Array P400i
*	HP Smart Array P410
*	HP Smart Array P410i
*	HP Smart Array P411
*	HP Smart Array P420
*	HP Smart Array P420i
*	HP Smart Array P421
*	HP Smart Array P430
*	HP Smart Array P430i
*	HP Smart Array P431
*	HP Smart Array P440ar
*	HP Smart Array P530
*	HP Smart Array P531
*	HP Smart Array P600
*	HP Smart Array P721m
*	HP Smart Array P731m
*	HP Smart Array P800
*	HP Smart Array P812
*	HP Smart Array P830
*	HP Smart Array P830i
*	HP Modular Smart Array 20 (MSA20)
*	HP Modular Smart Array 500 (MSA500)


[NOTE]
====
[amd64, i386] Загрузка с этих контроллеров поддерживается.
Адаптеры EISA не поддерживаются.
====


Драйвер
**hpt27xx**
поддерживает следующие SAS
контроллеры:

*	HighPoint's RocketRAID 271x series
*	HighPoint's RocketRAID 272x series
*	HighPoint's RocketRAID 274x series
*	HighPoint's RocketRAID 276x series
*	HighPoint's RocketRAID 278x series



Драйвер
**hptiop**
поддерживает следующие SAS и SATA RAID-контроллеры:

*	HighPoint RocketRAID 4522
*	HighPoint RocketRAID 4521
*	HighPoint RocketRAID 4520
*	HighPoint RocketRAID 4322
*	HighPoint RocketRAID 4321
*	HighPoint RocketRAID 4320
*	HighPoint RocketRAID 4311
*	HighPoint RocketRAID 4310
*	HighPoint RocketRAID 3640
*	HighPoint RocketRAID 3622
*	HighPoint RocketRAID 3620

Драйвер
**hptiop**
также поддерживает следующие SAS и SATA RAID-контроллеры, которые
уже достигли конца срока службы:

*	HighPoint RocketRAID 4211
*	HighPoint RocketRAID 4210
*	HighPoint RocketRAID 3560
*	HighPoint RocketRAID 3540
*	HighPoint RocketRAID 3530
*	HighPoint RocketRAID 3522
*	HighPoint RocketRAID 3521
*	HighPoint RocketRAID 3520
*	HighPoint RocketRAID 3511
*	HighPoint RocketRAID 3510
*	HighPoint RocketRAID 3410
*	HighPoint RocketRAID 3320
*	HighPoint RocketRAID 3220
*	HighPoint RocketRAID 3122
*	HighPoint RocketRAID 3120
*	HighPoint RocketRAID 3020



Драйвер
**hptmv**
поддерживает следующие ATA RAID
контроллеры:

*	HighPoint's RocketRAID 182x series



Драйвер
**hptnr**
поддерживает следующие SATA
контроллеры:

*	HighPoint's DC7280 series
*	HighPoint's Rocket R750 series



Драйвер
**hptrr**
поддерживает следующие RAID
контроллеры:

*	RocketRAID 172x series
*	RocketRAID 174x series
*	RocketRAID 2210
*	RocketRAID 222x series
*	RocketRAID 2240
*	RocketRAID 230x series
*	RocketRAID 231x series
*	RocketRAID 232x series
*	RocketRAID 2340
*	RocketRAID 2522



Следующие контроллеры поддерживаются
драйвером
**ida**:

*	Compaq SMART Array 221
*	Compaq Integrated SMART Array Controller
*	Compaq SMART Array 4200
*	Compaq SMART Array 4250ES
*	Compaq SMART 3200 Controller
*	Compaq SMART 3100ES Controller
*	Compaq SMART-2/DH Controller
*	Compaq SMART-2/SL Controller
*	Compaq SMART-2/P Controller



Контроллеры, поддерживаемые драйвером
**ips**
, включают:

*	IBM ServeRAID 3H
*	ServeRAID 4L/4M/4H
*	ServeRAID Series 5
*	ServeRAID 6i/6M
*	ServeRAID 7t/7k/7M

Более новые контроллеры ServeRAID
поддерживаются драйвером
aac(4)
или
mfi(4).



Драйвер
**isci**
обеспечивает поддержку Intel C600
`SAS`
контроллеров.



Драйвер
**isp**
поддерживает следующие оптические адаптеры Fibre Chanel:

	Модель:                               Скорость:   Шина:
	Qlogic QLE2874 (2814)                64Gb     PCIe
	Qlogic QLE2870/QLE2872 (2812)        64Gb     PCIe
	Qlogic QLE2774 (2814)                32Gb     PCIe
	Qlogic QLE2770/QLE2772 (2812)        32Gb     PCIe
	Qlogic 2740/2742/2764 (2722/2714)    32Gb     PCIe
	Qlogic 2690/2692/2694 (2684/2692)    16Gb     PCIe
	Qlogic 267x/836x (2031/8031) FCoE    16Gb     PCIe
	Qlogic 256x (2532)                   8Gb      PCIe
	Qlogic 246x (2432)                   4Gb      PCIe
	Qlogic 2422                          4Gb      PCI-X



Драйвер
**mfi**
поддерживает следующее оборудование:

*	LSI MegaRAID SAS 1078
*	LSI MegaRAID SAS 8408E
*	LSI MegaRAID SAS 8480E
*	LSI MegaRAID SAS 9240
*	LSI MegaRAID SAS 9260
*	Dell PERC5
*	Dell PERC6
*	IBM ServeRAID M1015 SAS/SATA
*	IBM ServeRAID M1115 SAS/SATA
*	IBM ServeRAID M5015 SAS/SATA
*	IBM ServeRAID M5110 SAS/SATA
*	IBM ServeRAID-MR10i
*	Intel RAID Controller SRCSAS18E
*	Intel RAID Controller SROMBSAS18E



Драйвер
**mlx**
поддерживает следующие Parallel SCSI RAID-контроллеры:

*	Mylex DAC960P (Wide Fast SCSI-2)
*	Mylex DAC960PD / DEC KZPSC (Wide Fast SCSI-2)
*	Mylex DAC960PDU (Ultra SCSI-3)
*	Mylex DAC960PL (Wide Fast SCSI-2)
*	Mylex DAC960PJ (Wide Ultra SCSI-3)
*	Mylex DAC960PG (Wide Ultra SCSI-3)
*	Mylex DAC960PU / DEC PZPAC (Wide Ultra SCSI-3)
*	Mylex AcceleRAID 150 (DAC960PRL) (Wide Ultra2 SCSI)
*	Mylex AcceleRAID 250 (DAC960PTL1) (Wide Ultra2 SCSI)
*	Mylex eXtremeRAID 1100 (DAC1164P) (Wide Ultra2 SCSI)
*	RAIDarray 230 controllers, aka the Ultra-SCSI DEC KZPAC-AA (1-ch, 4MB
	cache), KZPAC-CA (3-ch, 4MB), KZPAC-CB (3-ch, 8MB cache)


[NOTE]
====
[amd64, i386] Загрузка с этих контроллеров поддерживается.
Адаптеры EISA не поддерживаются.
====


Драйвер
**mmcsd**
реализует блочное устройство прямого доступа для карт памяти MMC и SD.



Эти контроллеры поддерживаются
драйвером
**mpi3mr**:

*	Broadcom Ltd. SAS 4116 Tri-Mode RAID Adapter
*	Broadcom Ltd. 9670W-16i 24G PCIe 4.0 Tri-Mode RAID Adapters
*	Broadcom Ltd. 9670-24i 24G PCIe 4.0 Tri-Mode RAID Adapters
*	Broadcom Ltd. 9660-16i 24G PCIe 4.0 Tri-Mode RAID Adapters
*	Broadcom Ltd. 9620-16i 24G PCIe 4.0 Tri-Mode RAID Adapters
*	Broadcom Ltd. 9600-24i 24G PCIe 4.0 Tri-Mode RAID Adapters
*	Broadcom Ltd. 9600-16i 24G PCIe 4.0 Tri-Mode RAID Adapters
*	Broadcom Ltd. 9600W-16e 24G PCIe 4.0 Tri-Mode RAID Adapters
*	Broadcom Ltd. 9600-16e 24G PCIe 4.0 Tri-Mode RAID Adapters
*	Broadcom Ltd. 9600-8i8e 24G PCIe 4.0 Tri-Mode RAID Adapters



Драйвер
**mpr**
поддерживает следующие SATA/SAS/NVMe RAID-контроллеры:

*	Broadcom Ltd./Avago Tech (LSI) SAS 3004 (4 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3008 (8 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3108 (8 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3216 (16 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3224 (24 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3316 (16 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3324 (24 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3408 (8 Port SAS/PCIe)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3416 (16 Port SAS/PCIe)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3508 (8 Port SAS/PCIe)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3516 (16 Port SAS/PCIe)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3616 (16 Port SAS/PCIe)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3708 (8 Port SAS/PCIe)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3716 (16 Port SAS/PCIe)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3808 (8 Port SAS/PCIe)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3816 (16 Port SAS/PCIe)
*	Broadcom Ltd./Avago Tech (LSI) SAS 3916 (16 Port SAS/PCIe)



Эти контроллеры поддерживаются
драйвером
**mps**:

*	Broadcom Ltd./Avago Tech (LSI) SAS 2004 (4 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 2008 (8 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 2108 (8 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 2116 (16 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 2208 (8 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SAS 2308 (8 Port SAS)
*	Broadcom Ltd./Avago Tech (LSI) SSS6200 Solid State Storage
*	Intel Integrated RAID Module RMS25JB040
*	Intel Integrated RAID Module RMS25JB080
*	Intel Integrated RAID Module RMS25KB040
*	Intel Integrated RAID Module RMS25KB080



Следующие контроллеры поддерживаются
драйвером
**mpt**:

*	LSI Logic 53c1030,
	LSI Logic LSI2x320-X
	(одинарный и двойной Ultra320
	`SCSI`)
*	LSI Logic AS1064,
	LSI Logic AS1068
	(`SAS/SATA`)
*	LSI Logic FC909
	(1Gb/s
	`Fibre Channel`)
*	LSI Logic FC909A
	(двойной 1Gb/s
	`Fibre Channel`)
*	LSI Logic FC919,
	LSI Logic 7102XP-LC
	(одинарный 2Gb/s
	`Fibre Channel`)
*	LSI Logic FC929,
	LSI Logic FC929X,
	LSI Logic 7202XP-LC
	(двойной 2Gb/s
	`Fibre Channel`)
*	LSI Logic FC949X
	(двойной 4Gb/s
	`Fibre Channel`)
*	LSI Logic FC949E,
	LSI Logic FC949ES
	(двойной 4Gb/s
	`Fibre Channel PCI-Express)`

Чипы контроллеров
`Ultra 320 SCSI`
поддерживаемые драйвером
**mpt**
можно найти встроенными во многих системах, включая:

*	Dell PowerEdge 1750 через 2850
*	IBM eServer xSeries 335

Эти системы также содержат Integrated RAID Mirroring и Integrated
RAID Mirroring Enhanced, которые этот драйвер также поддерживает.

Чипы контроллеров
`SAS`
также присутствуют во многих новых системах на базе AMD/Opteron,
таких как Sun 4100.
Обратите внимание, что этот контроллер может управлять как SAS, так и SATA
накопителями или их смесью одновременно.
Integrated RAID Mirroring
доступный для этих контроллеров поддерживается в лучшем случае плохо.

Наборы чипов контроллеров
`Fibre Channel`
поддерживаются в широком
спектре скоростей и систем.
`Apple`
Fibre Channel HBA фактически
является картой
`FC949ES`.

Этот драйвер также поддерживает режим цели (target mode) для карт Fibre Channel.
Эта поддержка может быть включена установкой желаемой роли ядра через
утилиту прошивки LSI Logic, которая определяет, какие роли может принимать карта
- отдельная компиляция не требуется.



Драйвер
**mrsas**
поддерживает следующие LSI/Broadcom SATA/SAS RAID-контроллеры:

	Контроллер               Чип            Скорость
	Broadcom SAS3916         Aero            12Gb/s
	Broadcom SAS3908         Aero            12Gb/s
	LSI MegaRAID SAS 9380    Invader/Fury    12Gb/s
	LSI MegaRAID SAS 9361    Invader/Fury    12Gb/s
	LSI MegaRAID SAS 9341    Invader/Fury    12Gb/s
	LSI MegaRAID SAS 9286    Thunderbolt     6Gb/s
	LSI MegaRAID SAS 9285    Thunderbolt     6Gb/s
	LSI MegaRAID SAS 9272    Thunderbolt     6Gb/s
	LSI MegaRAID SAS 9271    Thunderbolt     6Gb/s
	LSI MegaRAID SAS 9270    Thunderbolt     6Gb/s
	LSI MegaRAID SAS 9267    Thunderbolt     6Gb/s
	LSI MegaRAID SAS 9266    Thunderbolt     6Gb/s
	LSI MegaRAID SAS 9265    Thunderbolt     6Gb/s
	LSI SAS 3108                             12Gb/s
	LSI SAS 3008                             12Gb/s
	LSI SAS 2308                             6Gb/s
	LSI SAS 2208                             6Gb/s
	DELL PERC H830           Invader/Fury    12Gb/s
	DELL PERC H810           Thunderbolt     6Gb/s
	DELL PERC H730/P         Invader/Fury    12Gb/s
	DELL PERC H710/P         Thunderbolt     6Gb/s
	DELL PERC H330           Invader/Fury    12Gb/s



Драйвер
**mvs**
поддерживает следующие контроллеры:

Gen-I (SATA 1.5Gbps):

*	88SX5040
*	88SX5041
*	88SX5080
*	88SX5081

Gen-II (SATA 3Gbps, NCQ, PMP):

*	88SX6040
*	88SX6041 (включая Adaptec 1420SA)
*	88SX6080
*	88SX6081

Gen-IIe (SATA 3Gbps, NCQ, PMP с FBS):

*	88SX6042
*	88SX7042 (включая Adaptec 1430SA)
*	88F5182 SoC
*	88F6281 SoC
*	MV78100 SoC

Обратите внимание, что это оборудование поддерживает очереди команд и коммутацию на основе FIS
только для команд ATA DMA.
Команды ATAPI и не-DMA ATA выполняются по одной для каждого порта.



Драйвер
**nda**
поддерживает устройства хранения NVMe
(Non-Volatile Memory Express)
подключенные через PCIe или через NVMF
(NVMe over Fabric)
через подсистему CAM.



Драйвер
**nvd**
поддерживает устройства хранения NVMe, использующие пространства имён NVMe.



Драйвер
**ocs_fc**
поддерживает эти адаптеры Fibre Channel:

Emulex 16/8G FC GEN 5 HBAS

> > LPe15004 FC Host Bus Adapters
> > LPe160XX FC Host Bus Adapters

Emulex 32/16G FC GEN 6 HBAS

> > LPe3100X FC Host Bus Adapters
> > LPe3200X FC Host Bus Adapters

Emulex 64/32G FC GEN 7 HBAS

> > LPe3500X FC Host Bus Adapters



Драйвер
**pms**
поддерживает следующее оборудование:

*	Tachyon TS Fibre Channel Card
*	Tachyon TL Fibre Channel Card
*	Tachyon XL2 Fibre Channel Card
*	Tachyon DX2 Fibre Channel Card
*	Tachyon DX2+ Fibre Channel Card
*	Tachyon DX4+ Fibre Channel Card
*	Tachyon QX2 Fibre Channel Card
*	Tachyon QX4 Fibre Channel Card
*	Tachyon DE4 Fibre Channel Card
*	Tachyon QE4 Fibre Channel Card
*	Tachyon XL10 Fibre Channel Card
*	PMC Sierra SPC SAS-SATA Card
*	PMC Sierra SPC-V SAS-SATA Card
*	PMC Sierra SPC-VE SAS-SATA Card
*	PMC Sierra SPC-V 16 Port SAS-SATA Card
*	PMC Sierra SPC-VE 16 Port SAS-SATA Card
*	PMC Sierra SPC-V SAS-SATA Card 12Gig
*	PMC Sierra SPC-VE SAS-SATA Card 12Gig
*	PMC Sierra SPC-V 16 Port SAS-SATA Card 12Gig
*	PMC Sierra SPC-VE 16 Port SAS-SATA Card 12Gig
*	Adaptec Hialeah 4/8 Port SAS-SATA HBA Card 6Gig
*	Adaptec Hialeah 4/8 Port SAS-SATA RAID Card 6Gig
*	Adaptec Hialeah 8/16 Port SAS-SATA HBA Card 6Gig
*	Adaptec Hialeah 8/16 Port SAS-SATA RAID Card 6Gig
*	Adaptec Hialeah 8/16 Port SAS-SATA HBA Encryption Card 6Gig
*	Adaptec Hialeah 8/16 Port SAS-SATA RAID Encryption Card 6Gig
*	Adaptec Delray 8 Port SAS-SATA HBA Card 12Gig
*	Adaptec Delray 8 Port SAS-SATA HBA Encryption Card 12Gig
*	Adaptec Delray 16 Port SAS-SATA HBA Card 12Gig
*	Adaptec Delray 16 Port SAS-SATA HBA Encryption Card 12Gig



Драйвер
**pst**
поддерживает контроллер аппаратного
RAID Promise Supertrak SX6000 ATA.



Драйвер
**sdhci**
поддерживает спецификацию SD Host Controller.
При подключении через шину PCI,
контроллер автоматически настраивается.
Многие чипы SoC предоставляют контроллер SDHCI, напрямую отображённый в память ввода-вывода.
Для них контроллер может быть настроен с использованием методов
fdt(4)
или
acpi(4)
предоставленных производителем вашей платы.

В отличие от большинства других драйверов, поддерживающих общий стандарт,
**sdhci**
требует большого количества особенностей (quirks) для обработки аппаратных ошибок,
проприетарных регистров и плохо определённого управления питанием.
Хотя многие чипсеты от
Intel, Xilinx, Rockchip, Frescale, Ricoh и TI имеют эти записи,
может наблюдаться неоптимальная производительность при использовании некоторых контроллеров.
Особенности и пользовательская конфигурация чаще всего требуются
когда устройство настраивается через
fdt(4)
или
acpi(4).



Драйвер
**siis**
поддерживает следующие чипы контроллеров:

*	SiI3124 (PCI-X 133MHz/64bit, 4 порта)
*	SiI3131 (PCIe 1.0 x1, 1 порт)
*	SiI3132 (PCIe 1.0 x1, 2 порта)
*	SiI3531 (PCIe 1.0 x1, 1 порт)



Контроллеры, поддерживаемые драйвером
**smartpqi**, включают,
но не ограничиваются:

*	Семейство контроллеров HPE Gen10 Smart Array
*	Контроллеры Adaptec SmartRaid и SmartHBA
*	OEM-контроллеры на основе чипсетов Microchip Technology Inc. SmartROC
	и SmartIOC



Драйвер
**sym**
обеспечивает поддержку следующих Symbios/LSI Logic PCI SCSI
контроллеров:

*	`53C810`
*	`53C810A`
*	`53C815`
*	`53C825`
*	`53C825A`
*	`53C860`
*	`53C875`
*	`53C876`
*	`53C895`
*	`53C895A`
*	`53C896`
*	`53C897`
*	`53C1000`
*	`53C1000R`
*	`53C1010-33`
*	`53C1010-66`
*	`53C1510D`

SCSI-контроллеры, поддерживаемые
**sym**
могут быть либо встроены в материнскую плату, либо находиться на
одной из следующих плат расширения:

*	ASUS SC-200, SC-896
*	Data Technology DTC3130 (все варианты)
*	DawiControl DC2976UW
*	Diamond FirePort (все)
*	NCR cards (все)
*	Symbios cards (все)
*	Tekram DC390W, 390U, 390F, 390U2B, 390U2W, 390U3D, и 390U3W
*	Tyan S1365



Драйвер
**tws**
поддерживает следующий SATA/SAS RAID-контроллер:

*	LSI's 3ware SAS 9750 series



Драйвер
**ufshci**
поддерживает как хост-контроллеры, так и устройства, реализующие
Universal Flash Storage Host Controller Interface 4.1 и более ранние.


Со всеми поддерживаемыми SCSI-контроллерами обеспечивается полная поддержка периферийных устройств SCSI-I, SCSI-II и SCSI-III, включая жёсткие диски, оптические диски, ленточные накопители (включая DAT, 8mm Exabyte, Mammoth и DLT), сменщики носителей, устройства-цели процессоров и приводы CD-ROM.
Устройства WORM, которые поддерживают команды CD-ROM, поддерживаются для доступа только для чтения драйверами CD-ROM (такими как man:cd[4]).
Поддержка записи WORM/CD-R/CD-RW предоставляется man:cdrecord[1], который является частью порта package:sysutils/cdrtools[] в Коллекции портов.

В настоящее время поддерживаются следующие системы типа CD-ROM:

* SCSI-интерфейс (также включает ProAudio Spectrum и SoundBlaster SCSI) (man:cd[4])
* ATAPI IDE-интерфейс (man:acd[4])

[[ethernet]]
=== Сетевые интерфейсы Ethernet


Драйвер
**ae**
поддерживает контроллеры Attansic/Atheros L2 PCIe FastEthernet и,
как известно, работает со следующим оборудованием:

*	ASUS EeePC 701
*	ASUS EeePC 900

Другое оборудование может работать с этим драйвером, а может и нет.



Драйвер
**age**
обеспечивает поддержку встроенных сетевых контроллеров (LOM) на основе
чипов контроллера Ethernet Attansic/Atheros L1 Gigabit, включая:

*	ASUS M2N8-VMX
*	ASUS M2V
*	ASUS M3A
*	ASUS P2-M2A590G
*	ASUS P5B-E
*	ASUS P5B-MX/WIFI-AP
*	ASUS P5B-VMSE
*	ASUS P5K
*	ASUS P5KC
*	ASUS P5KPL-C
*	ASUS P5KPL-VM
*	ASUS P5K-SE
*	ASUS P5K-V
*	ASUS P5L-MX
*	ASUS P5DL2-VM
*	ASUS P5L-VM 1394
*	ASUS G2S



Драйвер устройства
**alc**
обеспечивает поддержку следующих контроллеров Ethernet:

*	Контроллер Ethernet Atheros AR8131 PCI Express Gigabit
*	Контроллер Ethernet Atheros AR8132 PCI Express Fast
*	Контроллер Ethernet Atheros AR8151 v1.0 PCI Express Gigabit
*	Контроллер Ethernet Atheros AR8151 v2.0 PCI Express Gigabit
*	Контроллер Ethernet Atheros AR8152 v1.1 PCI Express Fast
*	Контроллер Ethernet Atheros AR8152 v2.0 PCI Express Fast
*	Контроллер Ethernet Atheros AR8161 PCI Express Gigabit
*	Контроллер Ethernet Atheros AR8162 PCI Express Fast
*	Контроллер Ethernet Atheros AR8171 PCI Express Gigabit
*	Контроллер Ethernet Atheros AR8172 PCI Express Fast
*	Контроллер Ethernet Killer E2200 Gigabit
*	Контроллер Ethernet Killer E2400 Gigabit
*	Контроллер Ethernet Killer E2500 Gigabit



Драйвер устройства
**ale**
обеспечивает поддержку следующих контроллеров Ethernet:

*	Контроллер Ethernet Atheros AR8113 PCI Express Fast
*	Контроллер Ethernet Atheros AR8114 PCI Express Fast
*	Контроллер Ethernet Atheros AR8121 PCI Express Gigabit



Драйвер
**aue**
поддерживает следующие USB-адаптеры Fast Ethernet на основе
чипсета ADMtek AN986 Pegasus:

*	Abocom UFE1000, DSB650TX_NA
*	Accton USB320-EC, SpeedStream
*	ADMtek AN986, AN8511
*	Billionton USB100, USB100LP, USB100EL, USBE100
*	Corega Ether FEther USB-T, FEther USB-TX, FEther USB-TXS
*	D-Link DSB-650, DSB-650TX, DSB-650TX-PNA
*	Elecom LD-USBL/TX
*	Elsa Microlink USB2Ethernet
*	HP hn210e
*	I-O Data USB ETTX
*	Kingston KNU101TX
*	Адаптеры LinkSys USB10T, содержащие чипсет AN986 Pegasus,
	USB10TA, USB10TX, USB100TX, USB100H1
*	MELCO LUA-TX, LUA2-TX
*	Netgear FA101
*	Planex UE-200TX
*	Sandberg USB to Network Link (модель 133-06)
*	Siemens Speedstream
*	SmartBridges smartNIC
*	SMC 2202USB
*	SOHOware NUB100



Драйвер
**axe**
поддерживает USB-адаптеры Ethernet на основе ASIX Electronics AX88172/AX88178/AX88772/AX88772A/AX88772B/AX88760,
включая:

AX88172:

*	AboCom UF200
*	Acer Communications EP1427X2
*	ASIX AX88172
*	ATen UC210T
*	Billionton SnapPort
*	Billionton USB2AR
*	Buffalo (Melco Inc.) LUA-U2-KTX
*	Corega USB2_TX
*	D-Link DUBE100
*	Goodway GWUSB2E
*	JVC MP_PRX1
*	LinkSys USB200M
*	Netgear FA120
*	Sitecom LN-029
*	System TALKS Inc. SGC-X2UL

AX88178:

*	ASIX AX88178
*	Belkin F5D5055
*	Logitec LAN-GTJ/U2A
*	Buffalo (Melco Inc.) LUA3-U2-AGT
*	Planex Communications GU1000T
*	Sitecom Europe LN-028

AX88772:

*	ASIX AX88772
*	Buffalo (Melco Inc.) LUA3-U2-ATX
*	D-Link DUBE100B1
*	Planex UE-200TX-G
*	Planex UE-200TX-G2

AX88772A:

*	ASIX AX88772A
*	Cisco-Linksys USB200Mv2

AX88772B:

*	ASIX AX88772B
*	Lenovo USB 2.0 Ethernet

AX88760:

*	ASIX AX88760



Драйвер
**axge**
поддерживает следующие USB-контроллеры Gigabit Ethernet:

*	ASIX Electronics AX88179A
*	ASIX Electronics AX88179
*	ASIX Electronics AX88178A



Драйвер
**bce**
обеспечивает поддержку различных сетевых карт на основе семейства
контроллеров Gigabit Ethernet QLogic NetXtreme II, включая
следующие:

*	QLogic NetXtreme II BCM5706 1000Base-SX
*	QLogic NetXtreme II BCM5706 1000Base-T
*	QLogic NetXtreme II BCM5708 1000Base-SX
*	QLogic NetXtreme II BCM5708 1000Base-T
*	QLogic NetXtreme II BCM5709 1000Base-SX
*	QLogic NetXtreme II BCM5709 1000Base-T
*	QLogic NetXtreme II BCM5716 1000Base-T
*	Интегрированный сетевой контроллер Dell PowerEdge 1950 BCM5708
*	Интегрированный сетевой контроллер Dell PowerEdge 2950 BCM5708
*	Интегрированный сетевой контроллер Dell PowerEdge R710 BCM5709
*	Многофункциональный гигабитный серверный адаптер HP NC370F
*	Многофункциональный гигабитный серверный адаптер HP NC370T
*	Многофункциональный гигабитный серверный адаптер HP NC370i
*	Многофункциональный гигабитный серверный адаптер HP NC371i
*	Многофункциональный гигабитный серверный адаптер HP NC373F PCIe
*	Многофункциональный гигабитный серверный адаптер HP NC373T PCIe
*	Многофункциональный гигабитный серверный адаптер HP NC373i
*	Многофункциональный гигабитный серверный адаптер HP NC373m
*	Многофункциональный адаптер HP NC374m PCIe
*	Многофункциональный гигабитный серверный адаптер HP NC380T PCIe DP
*	Многофункциональный гигабитный серверный адаптер HP NC382T PCIe DP
*	Многофункциональный гигабитный серверный адаптер HP NC382i DP
*	Многофункциональный адаптер HP NC382m DP 1GbE BL-c


Драйвер man:bfe[4] поддерживает устройства Fast Ethernet на основе Broadcom BCM4401.


Драйвер
**bge**
обеспечивает поддержку различных сетевых карт на основе семейства
чипов контроллера Gigabit Ethernet Broadcom BCM570x, включая
следующие:

*	3Com 3c996-SX (1000baseSX)
*	3Com 3c996-T (10/100/1000baseTX)
*	Apple Thunderbolt Display (10/100/1000baseTX)
*	Адаптер Apple Thunderbolt to Gigabit Ethernet (10/100/1000baseTX)
*	Интегрированный сетевой контроллер Dell PowerEdge 1750 BCM5704C (10/100/1000baseTX)
*	Интегрированный сетевой контроллер Dell PowerEdge 2550 BCM5700 (10/100/1000baseTX)
*	Интегрированный сетевой контроллер Dell PowerEdge 2650 BCM5703 (10/100/1000baseTX)
*	Интегрированный сетевой контроллер Dell PowerEdge R200 BCM5750 (10/100/1000baseTX)
*	Интегрированный сетевой контроллер Dell PowerEdge R300 BCM5722 (10/100/1000baseTX)
*	Интегрированный сетевой контроллер IBM x235 BCM5703x (10/100/1000baseTX)
*	Интегрированный сетевой контроллер HP Compaq dc7600 BCM5752 (10/100/1000baseTX)
*	Встраиваемый гигабитный сетевой контроллер HP ProLiant NC7760 (10/100/1000baseTX)
*	Гигабитная сетевая карта HP ProLiant NC7770 PCI-X (10/100/1000baseTX)
*	Гигабитная сетeвая карта HP ProLiant NC7771 PCI-X (10/100/1000baseTX)
*	Встраиваемая гигабитная сетeвая карта HP ProLiant NC7781 PCI-X (10/100/1000baseTX)
*	Netgear GA302T (10/100/1000baseTX)
*	SysKonnect SK-9D21 (10/100/1000baseTX)
*	SysKonnect SK-9D41 (1000baseSX)



Драйвер
**bnxt**
обеспечивает поддержку различных сетевых карт на основе семейств
контроллеров Gigabit Ethernet Broadcom NetXtreme-C и
NetXtreme-E, включая следующие:

*	Broadcom BCM57301 NetXtreme-C 10Gb Контроллер Ethernet
*	Broadcom BCM57302 NetXtreme-C 10Gb/25Gb Контроллер Ethernet
*	Broadcom BCM57304 NetXtreme-C 10Gb/25Gb/40Gb/50Gb Контроллер Ethernet
*	Broadcom BCM57304 NetXtreme-C Виртуальная функция Ethernet
*	Broadcom BCM57314 NetXtreme-C Виртуальная функция Ethernet
*	Broadcom BCM57402 NetXtreme-E 10Gb Контроллер Ethernet
*	Broadcom BCM57402 NetXtreme-E Раздел Ethernet
*	Broadcom BCM57404 NetXtreme-E 10Gb/25Gb Контроллер Ethernet
*	Broadcom BCM57404 NetXtreme-E Виртуальная функция Ethernet
*	Broadcom BCM57404 NetXtreme-E Раздел
*	Broadcom BCM57406 NetXtreme-E 10GBASE-T Контроллер Ethernet
*	Broadcom BCM57406 NetXtreme-E Раздел
*	Broadcom BCM57407 NetXtreme-E 10GBase-T Контроллер Ethernet
*	Broadcom BCM57407 NetXtreme-E 25Gb Контроллер Ethernet
*	Broadcom BCM57407 NetXtreme-E Раздел
*	Broadcom BCM57412 NetXtreme-E Раздел
*	Broadcom BCM57414 NetXtreme-E Виртуальная функция Ethernet
*	Broadcom BCM57414 NetXtreme-E Раздел
*	Broadcom BCM57416 NetXtreme-E Раздел
*	Broadcom BCM57417 NetXtreme-E Раздел Ethernet
*	Broadcom BCM57454 NetXtreme-E 10Gb/25Gb/40Gb/50Gb/100Gb Ethernet
*	Broadcom BCM57502 NetXtreme-E 10Gb/25Gb/50Gb/100Gb/200Gb Ethernet
*	Broadcom BCM57504 NetXtreme-E 10Gb/25Gb/50Gb/100Gb/200Gb Ethernet
*	Broadcom BCM57508 NetXtreme-E 10Gb/25Gb/50Gb/100Gb/200Gb Ethernet



Драйвер
**bxe**
обеспечивает поддержку различных сетевых карт на основе семейства
чипов контроллера 10Gb Ethernet QLogic NetXtreme II, включая следующие:

*	QLogic NetXtreme II BCM57710 10Gb
*	QLogic NetXtreme II BCM57711 10Gb
*	QLogic NetXtreme II BCM57711E 10Gb
*	QLogic NetXtreme II BCM57712 10Gb
*	QLogic NetXtreme II BCM57712-MF 10Gb
*	QLogic NetXtreme II BCM57800 10Gb
*	QLogic NetXtreme II BCM57800-MF 10Gb
*	QLogic NetXtreme II BCM57810 10Gb
*	QLogic NetXtreme II BCM57810-MF 10Gb
*	QLogic NetXtreme II BCM57840 10Gb / 20Gb
*	QLogic NetXtreme II BCM57840-MF 10Gb



Чипы, поддерживаемые
драйвером
**cas**:

*	National Semiconductor DP83065 Saturn Gigabit Ethernet
*	Sun Cassini Gigabit Ethernet
*	Sun Cassini+ Gigabit Ethernet

Следующие дополнительные карты, как известно,
на данный момент
работают с драйвером
**cas**:

*	Sun GigaSwift Ethernet 1.0 MMF (Cassini Kuheen)
	(парт. номер 501-5524)
*	Sun GigaSwift Ethernet 1.0 UTP (Cassini)
	(парт. номер 501-5902)
*	Sun GigaSwift Ethernet UTP (GCS)
	(парт. номер 501-6719)
*	Sun Quad GigaSwift Ethernet UTP (QGE)
	(парт. номер 501-6522)
*	Sun Quad GigaSwift Ethernet PCI-X (QGE-X)
	(парт. номер 501-6738)



Драйвер
**cdce**
поддерживает USB-интерфейсы Ethernet, реализующие
протокол USB Communication Device Class Ethernet Control Model (CDC ECM) или
Network Control Model (CDC NCM), такие как:

*	USB-модем Android (tethering)
*	USB-модем iPhone (tethering)
*	Контроллер моста Host-to-Host Prolific PL-2501
*	КПК Sharp Zaurus
*	Кабельный модем DOCSIS Terayon TJ-715
*	Мобильные сетевые устройства Huawei 3G/4G LTE (напр. E3372, E5573) и другие



Драйвер
**cue**
поддерживает USB-адаптеры Ethernet на основе CATC USB-EL1210A,
включая:

*	Belkin F5U011/F5U111
*	CATC Netmate
*	CATC Netmate II
*	SmartBridges SmartLink



Драйвер
**cxgb**
поддерживает адаптеры Ethernet 10 Gigabit и 1 Gigabit на основе чипсетов T3 и T3B:

*	Chelsio 10GBase-CX4
*	Chelsio 10GBase-LR
*	Chelsio 10GBase-SR



Драйвер
**cxgbe**
поддерживает адаптеры Ethernet 100Gb и 25Gb на основе ASIC T6:

*	Chelsio T6225-CR
*	Chelsio T6225-SO-CR
*	Chelsio T62100-LP-CR
*	Chelsio T62100-SO-CR
*	Chelsio T62100-CR

Драйвер
**cxgbe**
поддерживает адаптеры Ethernet 40Gb, 10Gb и 1Gb на основе ASIC T5:

*	Chelsio T580-CR
*	Chelsio T580-LP-CR
*	Chelsio T580-LP-SO-CR
*	Chelsio T560-CR
*	Chelsio T540-CR
*	Chelsio T540-LP-CR
*	Chelsio T522-CR
*	Chelsio T520-LL-CR
*	Chelsio T520-CR
*	Chelsio T520-SO
*	Chelsio T520-BT
*	Chelsio T504-BT

Драйвер
**cxgbe**
поддерживает адаптеры Ethernet 10Gb и 1Gb на основе ASIC T4:

*	Chelsio T420-CR
*	Chelsio T422-CR
*	Chelsio T440-CR
*	Chelsio T420-BCH
*	Chelsio T440-BCH
*	Chelsio T440-CH
*	Chelsio T420-SO
*	Chelsio T420-CX
*	Chelsio T420-BT
*	Chelsio T404-BT



Драйвер
**cxgbev**
поддерживает Виртуальные Функции на адаптерах Ethernet 100Gb и 25Gb
на основе ASIC T6:

*	Chelsio T6225-CR
*	Chelsio T6225-SO-CR
*	Chelsio T62100-LP-CR
*	Chelsio T62100-SO-CR
*	Chelsio T62100-CR

Драйвер
**cxgbev**
поддерживает Виртуальные Функции на адаптерах Ethernet 40Gb, 10Gb и 1Gb
на основе ASIC T5:

*	Chelsio T580-CR
*	Chelsio T580-LP-CR
*	Chelsio T580-LP-SO-CR
*	Chelsio T560-CR
*	Chelsio T540-CR
*	Chelsio T540-LP-CR
*	Chelsio T522-CR
*	Chelsio T520-LL-CR
*	Chelsio T520-CR
*	Chelsio T520-SO
*	Chelsio T520-BT
*	Chelsio T504-BT

Драйвер
**cxgbev**
поддерживает Виртуальные Функции на адаптерах Ethernet 10Gb и 1Gb
на основе ASIC T4:

*	Chelsio T420-CR
*	Chelsio T422-CR
*	Chelsio T440-CR
*	Chelsio T420-BCH
*	Chelsio T440-BCH
*	Chelsio T440-CH
*	Chelsio T420-SO
*	Chelsio T420-CX
*	Chelsio T420-BT
*	Chelsio T404-BT



Драйвер
**dc**
обеспечивает поддержку следующих чипсетов:

*	DEC/Intel 21143
*	ADMtek AL981 Comet, AN985 Centaur, ADM9511 Centaur II и ADM9513
	Centaur II
*	ALi/ULi M5261 и M5263
*	ASIX Electronics AX88140A и AX88141
*	Conexant LANfinity RS7112 (miniPCI)
*	Davicom DM9009, DM9100, DM9102 и DM9102A
*	Lite-On 82c168 и 82c169 PNIC
*	Lite-On/Macronix 82c115 PNIC II
*	Macronix 98713, 98713A, 98715, 98715A, 98715AEC-C, 98725, 98727 и 98732
*	Xircom X3201 (только cardbus)

Следующие сетевые карты, как известно,
на данный момент
работают с драйвером
**dc**:

*	3Com OfficeConnect 10/100B (ADMtek AN985 Centaur-P)
*	Abocom FE2500
*	Accton EN1217 (98715A)
*	Accton EN2242 MiniPCI
*	Adico AE310TX (98715A)
*	Alfa Inc GFC2204 (ASIX AX88140A)
*	Встроенный Ethernet только на 10 Мбит/с на настольных компьютерах Compaq Presario 7900 series
	(21143, non-MII)
*	Встроенный Ethernet на LinkSys EtherFast 10/100 Instant GigaDrive (DM9102, MII)
*	CNet Pro110B (ASIX AX88140A)
*	CNet Pro120A (98715A или 98713A) и CNet Pro120B (98715)
*	Compex RL100-TX (98713 или 98713A)
*	D-Link DFE-570TX (21143, MII, четырехпортовый)
*	Digital DE500-BA 10/100 (21143, non-MII)
*	ELECOM Laneed LD-CBL/TXA (ADMtek AN985)
*	Hawking CB102 CardBus
*	Адаптер IBM EtherJet Cardbus
*	Карта Intel PRO/100 Mobile Cardbus (версии, использующие чипсет X3201)
*	Jaton XpressNet (Davicom DM9102)
*	Kingston KNE100TX (21143, MII)
*	Kingston KNE110TX (PNIC 82c169)
*	LinkSys LNE100TX (PNIC 82c168, 82c169)
*	LinkSys LNE100TX v2.0 (PNIC II 82c115)
*	LinkSys LNE100TX v4.0/4.1 (ADMtek AN985 Centaur-P)
*	Matrox FastNIC 10/100 (PNIC 82c168, 82c169)
*	Melco LGY-PCI-TXL
*	Microsoft MN-120 10/100 CardBus (ADMTek Centaur-C)
*	Microsoft MN-130 10/100 PCI (ADMTek Centaur-P)
*	NDC SOHOware SFA110A (98713A)
*	NDC SOHOware SFA110A Rev B4 (98715AEC-C)
*	NetGear FA310-TX Rev. D1, D2 или D3 (PNIC 82c169)
*	Netgear FA511
*	PlaneX FNW-3602-T (ADMtek AN985)
*	SMC EZ Card 10/100 1233A-TX (ADMtek AN985)
*	SVEC PN102-TX (98713)
*	Xircom Cardbus Realport
*	Xircom Cardbus Ethernet 10/100
*	Xircom Cardbus Ethernet II 10/100



Встроенные контроллеры Gigabit Ethernet в
следующих системах-на-кристалле
Freescale, как известно, работают с драйвером
**dtsec**:

*	P2041, P3041
*	P5010, P5020

Кроме того, следующие устройства должны работать, но не тестировались:

*	P4080, P4040
*	P5040



Драйвер
**em**
поддерживает адаптеры Gigabit Ethernet
на основе чипов контроллера Intel
82540, 82541ER, 82541PI, 82542, 82543, 82544, 82545, 82546, 82546EB,
82546GB, 82547, 82571, 82572, 82573, 82574, 82575, 82576 и 82580:

*	Двухпортовый серверный адаптер Intel Gigabit ET (82576)
*	Четырехпортовый серверный адаптер Intel Gigabit VT (82575)
*	Одно-, двух- и четырехпортовый контроллер Intel Gigabit Ethernet (82580)
*	Контроллер Intel i210 и i211 Gigabit Ethernet
*	Контроллер Intel i350 и i354 Gigabit Ethernet
*	Сетевое подключение Intel PRO/1000 CT (82547)
*	Серверный адаптер Intel PRO/1000 F (82543)
*	Серверный адаптер Intel PRO/1000 Gigabit (82542)
*	Настольный адаптер Intel PRO/1000 GT (82541PI)
*	Двухпортовый серверный адаптер Intel PRO/1000 MF (82546)
*	Серверный адаптер Intel PRO/1000 MF (82545)
*	Серверный адаптер Intel PRO/1000 MF (LX) (82545)
*	Настольный адаптер Intel PRO/1000 MT (82540)
*	Настольный адаптер Intel PRO/1000 MT (82541)
*	Двухпортовый серверный адаптер Intel PRO/1000 MT (82546)
*	Четырехпортовый серверный адаптер Intel PRO/1000 MT (82546EB)
*	Серверный адаптер Intel PRO/1000 MT (82545)
*	Двухпортовый серверный адаптер Intel PRO/1000 PF (82571)
*	Четырехпортовый серверный адаптер Intel PRO/1000 PF (82571)
*	Серверный адаптер Intel PRO/1000 PF (82572)
*	Настольный адаптер Intel PRO/1000 PT (82572)
*	Двухпортовый серверный адаптер Intel PRO/1000 PT (82571)
*	Четырехпортовый серверный адаптер Intel PRO/1000 PT (82571)
*	Серверный адаптер Intel PRO/1000 PT (82572)
*	Настольный адаптер Intel PRO/1000 T (82544)
*	Серверный адаптер Intel PRO/1000 T (82543)
*	Серверный адаптер Intel PRO/1000 XF (82544)
*	Серверный адаптер Intel PRO/1000 XT (82544)


Драйвер man:ena[4] поддерживает эластичный сетевой адаптер AWS EC2 (Elastic Network Adapter).


Драйвер
**enic**
должен поддерживать все известные карты Cisco VIC.




Драйвер
**et**
поддерживает адаптеры
Ethernet Agere ET1310 10/100/Gigabit.





Адаптеры, поддерживаемые драйвером
**fxp**
, включают:

*	Intel EtherExpress PRO/10
*	Intel InBusiness 10/100
*	Intel PRO/100B / Адаптер EtherExpressPRO/100 B PCI
*	Адаптер управления Intel PRO/100+
*	Настольный адаптер Intel PRO/100 VE
*	Сетевое подключение Intel PRO/100 VM
*	Настольный адаптер Intel PRO/100 M
*	Настольные, серверные и двухпортовые серверные адаптеры Intel PRO/100 S
*	Многие встроенные сетевые интерфейсы на материнских платах Intel



Чипы, поддерживаемые драйвером
**gem**
, включают:

*	Apple GMAC
*	Sun GEM Gigabit Ethernet

Следующие дополнительные карты,
как известно, на данный момент
работают с драйвером
**gem**:

*	Sun Gigabit Ethernet PCI 2.0/3.0 (GBE/P)
	(парт. номер 501-4373)



Драйвер
**genet**
поддерживает часть контроллера Ethernet в Broadcom BCM2711
на Raspberry Pi 4 Model B и связанных системах.
Он использует PHY BCM54213PE.


Драйвер man:gve[4] поддерживает виртуальный сетевой контроллер Google Cloud Compute Engine (GCE) (gVNIC).



Драйвер
**ice**
поддерживает следующие
контроллеры Ethernet Intel 800 series от 1Gb до 200Gb:

*	Контроллер Ethernet Intel E810-C
*	Контроллер Ethernet Intel E810-XXV
*	Подключение Ethernet Intel E822-C
*	Подключение Ethernet Intel E822-L
*	Подключение Ethernet Intel E823-C
*	Подключение Ethernet Intel E823-L
*	Подключение Ethernet Intel E825-C
*	Подключение Ethernet Intel E830-C
*	Подключение Ethernet Intel E830-CC
*	Подключение Ethernet Intel E830-L
*	Подключение Ethernet Intel E830-XXV
*	Подключение Ethernet Intel E835-C
*	Подключение Ethernet Intel E835-CC
*	Подключение Ethernet Intel E835-L
*	Подключение Ethernet Intel E835-XXV

Драйвер
**ice**
поддерживает некоторые адаптеры этой серии с модулями SFP28/QSFP28,
которые имеют прошивку, требующую использования квалифицированных модулей Intel;
эти квалифицированные модули перечислены ниже.
Эта проверка квалификации не может быть отключена драйвером.

Драйвер
**ice**
поддерживает адаптеры Ethernet 100Gb с этими модулями QSFP28:

*	Intel 100G QSFP28 100GBASE-SR4   E100GQSFPSR28SRX
*	Intel 100G QSFP28 100GBASE-SR4   SPTMBP1PMCDF
*	Intel 100G QSFP28 100GBASE-CWDM4 SPTSBP3CLCCO
*	Intel 100G QSFP28 100GBASE-DR    SPTSLP2SLCDF

Драйвер
**ice**
поддерживает адаптеры Ethernet 25Gb и 10Gb с этими модулями SFP28:

*	Intel 10G/25G SFP28 25GBASE-SR E25GSFP28SR
*	Intel     25G SFP28 25GBASE-SR E25GSFP28SRX (расширенная температура)
*	Intel     25G SFP28 25GBASE-LR E25GSFP28LRX (расширенная температура)

Драйвер
**ice**
поддерживает адаптеры Ethernet 10Gb и 1Gb с этими модулями SFP+:

*	Intel 1G/10G SFP+ 10GBASE-SR E10GSFPSR
*	Intel 1G/10G SFP+ 10GBASE-SR E10GSFPSRG1P5
*	Intel 1G/10G SFP+ 10GBASE-SR E10GSFPSRG2P5
*	Intel    10G SFP+ 10GBASE-SR E10GSFPSRX (расширенная температура)
*	Intel 1G/10G SFP+ 10GBASE-LR E10GSFPLR



Драйвер
**igc**
поддерживает следующие модели:

*	I220-V
*	I221-V
*	I225-LM
*	I225-LMvP(2)
*	I225-V
*	I225-IT, I225-IT(2)
*	I225-K, I225-K(2)
*	I226-LM
*	I226-LMvP
*	I226-V
*	I226-IT
*	I226-K



Следующие устройства
поддерживаются драйвером
**ipheth**:

*	USB-модем Apple iPhone (все модели)
*	USB-модем Apple iPad (все модели)



Драйвер
**ix**
поддерживает адаптеры Intel 10Gb Ethernet PCIe,
включая:

*	Intel(R) Ethernet E610
*	Intel(R) Ethernet X553
*	Intel(R) Ethernet X552
*	Intel(R) Ethernet X550
*	Intel(R) Ethernet X540 Bypass
*	Intel(R) Ethernet X540
*	Intel(R) Ethernet X520 Bypass (82599)
*	Intel(R) Ethernet X520 (82599)
*	Intel(R) 10 Gigabit Server Adapter (82598EB)



Драйвер
**ixl**
поддерживает серию Intel Ethernet 700.
Большинство адаптеров этой серии с модулями SFP+/SFP28/QSFP+
имеют прошивку, требующую использования квалифицированных модулей Intel; эти
квалифицированные модули перечислены ниже.
Эта проверка квалификации не может быть отключена драйвером.

Драйвер
**ixl**
поддерживает адаптеры Ethernet 40Gb с этими модулями QSFP+:

*	Intel 4x10G/40G QSFP+ 40GBASE-SR4 E40GQSFPSR
*	Intel 4x10G/40G QSFP+ 40GBASE-LR4 E40GQSFPLR

Драйвер
**ixl**
поддерживает адаптеры Ethernet 25Gb с этими модулями SFP28:

*	Intel 10G/25G SFP28 25GBASE-SR E25GSFP28SR
*	Intel 10G/25G SFP28 25GBASE-SR E25GSFP28SRX (расширенная температура)

Драйвер
**ixl**
поддерживает адаптеры Ethernet 25Gb и 10Gb с этими модулями SFP+:

*	Intel 1G/10G SFP+ SR FTLX8571D3BCV-IT
*	Intel 1G/10G SFP+ SR AFBR-703SDZ-IN2
*	Intel 1G/10G SFP+ LR FTLX1471D3BCV-IT
*	Intel 1G/10G SFP+ LR AFCT-701SDZ-IN2
*	Intel 1G/10G SFP+ 10GBASE-SR E10GSFPSR
*	Intel 10G SFP+ 10GBASE-SR E10GSFPSRX (расширенная температура)
*	Intel 1G/10G SFP+ 10GBASE-LR E10GSFPLR

Обратите внимание, что адаптеры также поддерживают все пассивные и активные
кабели прямого подключения, соответствующие спецификациям SFF-8431 v4.1 и
SFF-8472 v10.4.

Это не исчерпывающий список; пожалуйста, обратитесь к документации продукта для
получения актуального списка поддерживаемых сред.



Драйвер устройства
**jme**
обеспечивает поддержку следующих контроллеров Ethernet:

*	Контроллер JMicron JMC250 PCI Express Gigabit Ethernet
*	Контроллер JMicron JMC251 PCI Express Gigabit Ethernet с хост-контроллером чтения карт
*	Контроллер JMicron JMC260 PCI Express Fast Ethernet
*	Контроллер JMicron JMC261 PCI Express Gigabit Ethernet с хост-контроллером чтения карт



Драйвер
**kue**
поддерживает USB-адаптеры Ethernet на основе Kawasaki LSI KL5KLUSB101B,
включая:

*	3Com 3c19250
*	Адаптер 3Com 3c460 HomeConnect Ethernet USB
*	ADS Technologies USB-10BT
*	AOX USB101
*	ATen UC10T
*	Abocom URE 450
*	Corega USB-T
*	D-Link DSB-650C
*	Entrega NET-USB-E45, NET-HUB-3U1E
*	I/O Data USB ETT
*	Kawasaki DU-H3E
*	LinkSys USB10T
*	Netgear EA101
*	Адаптер Peracom USB Ethernet
*	Адаптер Psion Gold Port USB Ethernet
*	SMC 2102USB, 2104USB



Адаптеры, поддерживаемые драйвером
**lge**
, включают:

*	SMC TigerCard 1000 (SMC9462SX)
*	D-Link DGE-500SX



Драйвер
**liquidio**
поддерживает следующие карты:

*	LiquidIO II CN2350 210SV/225SV
*	LiquidIO II CN2360 210SV/225SV



Драйвер
**mgb**
поддерживает:

*	Контроллер Microchip LAN7430 PCIe Gigabit Ethernet с PHY
*	Контроллер Microchip LAN7431 PCIe Gigabit Ethernet с интерфейсом RGMII



Драйвер
**mlx4en**
поддерживает следующие сетевые адаптеры:

*	Mellanox ConnectX-2 (ETH)
*	Mellanox ConnectX-3 (ETH)



Драйвер
**mlx4ib**
поддерживает следующие сетевые адаптеры:

*	Mellanox ConnectX-2 (IB)
*	Mellanox ConnectX-3 (IB)



Драйвер
**mlx5en**
поддерживает адаптеры Ethernet 200Gb, 100Gb, 50Gb, 40Gb, 25Gb и 10Gb.

*	ConnectX-6 поддерживает скорости 10/20/25/40/50/56/100Gb/200Gb/с.
*	ConnectX-5 поддерживает скорости 10/20/25/40/50/56/100Gb/с.
*	ConnectX-4 поддерживает скорости 10/20/25/40/50/56/100Gb/с.
*	ConnectX-4 LX поддерживает скорости 10/25/40/50Gb/с и сниженное энергопотребление.



Драйвер
**mlx5ib**
поддерживает сетевые адаптеры 100Gb, 50Gb, 40Gb, 25Gb и 10Gb.
ConnectX-4 поддерживает: скорости 10/20/25/40/50/56/100Gb/с.
ConnectX-4 LX поддерживает: скорости 10/25/40/50Gb/с (и сниженное энергопотребление):

*	Mellanox MCX455A-ECAT
*	Mellanox MCX456A-ECAT
*	Mellanox MCX415A-CCAT
*	Mellanox MCX416A-CCAT
*	Mellanox MCX455A-FCAT
*	Mellanox MCX456A-FCAT
*	Mellanox MCX415A-BCAT
*	Mellanox MCX416A-BCAT
*	Mellanox MCX4131A-GCAT
*	Mellanox MCX4131A-BCAT
*	Mellanox MCX4121A-ACAT
*	Mellanox MCX4111A-ACAT
*	Mellanox MCX4121A-XCAT
*	Mellanox MCX4111A-XCAT



Адаптеры, поддерживаемые драйвером
**mos**
, включают:

*	Sitecom LN030



Драйвер
**msk**
обеспечивает поддержку различных сетевых карт на основе чипов контроллера
Gigabit Ethernet Marvell/SysKonnect Yukon II, включая:

*	D-Link 550SX Gigabit Ethernet
*	D-Link 560SX Gigabit Ethernet
*	D-Link 560T Gigabit Ethernet
*	Marvell Yukon 88E8021CU Gigabit Ethernet
*	Marvell Yukon 88E8021 SX/LX Gigabit Ethernet
*	Marvell Yukon 88E8022CU Gigabit Ethernet
*	Marvell Yukon 88E8022 SX/LX Gigabit Ethernet
*	Marvell Yukon 88E8061CU Gigabit Ethernet
*	Marvell Yukon 88E8061 SX/LX Gigabit Ethernet
*	Marvell Yukon 88E8062CU Gigabit Ethernet
*	Marvell Yukon 88E8062 SX/LX Gigabit Ethernet
*	Marvell Yukon 88E8035 Fast Ethernet
*	Marvell Yukon 88E8036 Fast Ethernet
*	Marvell Yukon 88E8038 Fast Ethernet
*	Marvell Yukon 88E8039 Fast Ethernet
*	Marvell Yukon 88E8040 Fast Ethernet
*	Marvell Yukon 88E8040T Fast Ethernet
*	Marvell Yukon 88E8042 Fast Ethernet
*	Marvell Yukon 88E8048 Fast Ethernet
*	Marvell Yukon 88E8050 Gigabit Ethernet
*	Marvell Yukon 88E8052 Gigabit Ethernet
*	Marvell Yukon 88E8053 Gigabit Ethernet
*	Marvell Yukon 88E8055 Gigabit Ethernet
*	Marvell Yukon 88E8056 Gigabit Ethernet
*	Marvell Yukon 88E8057 Gigabit Ethernet
*	Marvell Yukon 88E8058 Gigabit Ethernet
*	Marvell Yukon 88E8059 Gigabit Ethernet
*	Marvell Yukon 88E8070 Gigabit Ethernet
*	Marvell Yukon 88E8071 Gigabit Ethernet
*	Marvell Yukon 88E8072 Gigabit Ethernet
*	Marvell Yukon 88E8075 Gigabit Ethernet
*	SysKonnect SK-9Sxx Gigabit Ethernet
*	SysKonnect SK-9Exx Gigabit Ethernet



Драйвер
**muge**
поддерживает:

*	Контроллер Microchip LAN7800 USB 3.1 Gigabit Ethernet с PHY
*	Контроллер Microchip LAN7850 USB 2.0 Gigabit Ethernet с PHY
*	Концентратор Microchip LAN7515 USB 2 и контроллер Gigabit Ethernet с PHY



Драйвер
**mxge**
поддерживает адаптеры 10 Gigabit Ethernet на основе
чипов Myricom LANai Z8E:

*	Myricom 10GBase-CX4 (10G-PCIE-8A-C, 10G-PCIE-8AL-C)
*	Myricom 10GBase-R (10G-PCIE-8A-R, 10G-PCIE-8AL-R)
*	Myricom 10G XAUI по ленточному волокну (10G-PCIE-8A-Q, 10G-PCIE-8AL-Q)



Драйвер
**my**
обеспечивает поддержку различных сетевых карт на основе чипсета Myson.
Поддерживаемые модели включают:

*	Чип Myson MTD800 PCI Fast Ethernet
*	Чип Myson MTD803 PCI Fast Ethernet
*	Чип Myson MTD89X PCI Gigabit Ethernet



Драйвер
**nfe**
поддерживает следующие встроенные адаптеры NVIDIA MCP:

*	Сетевой адаптер NVIDIA nForce MCP
*	Сетевой адаптер NVIDIA nForce MCP04
*	Сетевой адаптер NVIDIA nForce 430 MCP12
*	Сетевой адаптер NVIDIA nForce 430 MCP13
*	Сетевой адаптер NVIDIA nForce MCP51
*	Сетевой адаптер NVIDIA nForce MCP55
*	Сетевой адаптер NVIDIA nForce MCP61
*	Сетевой адаптер NVIDIA nForce MCP65
*	Сетевой адаптер NVIDIA nForce MCP67
*	Сетевой адаптер NVIDIA nForce MCP73
*	Сетевой адаптер NVIDIA nForce MCP77
*	Сетевой адаптер NVIDIA nForce MCP79
*	Сетевой адаптер NVIDIA nForce2 MCP2
*	Сетевой адаптер NVIDIA nForce2 400 MCP4
*	Сетевой адаптер NVIDIA nForce2 400 MCP5
*	Сетевой адаптер NVIDIA nForce3 MCP3
*	Сетевой адаптер NVIDIA nForce3 250 MCP6
*	Сетевой адаптер NVIDIA nForce3 MCP7
*	Сетевой адаптер NVIDIA nForce4 CK804 MCP8
*	Сетевой адаптер NVIDIA nForce4 CK804 MCP9



Драйвер
**nge**
поддерживает адаптеры Gigabit Ethernet на основе National Semiconductor DP83820 и DP83821,
включая:

*	Addtron AEG320T
*	Ark PC SOHO-GA2500T (32-бит PCI) и SOHO-GA2000T (64-бит PCI)
*	Asante FriendlyNet GigaNIX 1000TA и 1000TPC
*	D-Link DGE-500T
*	Linksys EG1032, ревизия 1
*	Netgear GA621
*	Netgear GA622T
*	SMC EZ Card 1000 (SMC9462TX)
*	Surecom Technology EP-320G-TX
*	Trendware TEG-PCITX (32-бит PCI) и TEG-PCITX2 (64-бит PCI)



Драйвер
**oce**
поддерживает следующие сетевые адаптеры:

*	Emulex BladeEngine 2
*	Emulex BladeEngine 3
*	Emulex Lancer




Драйвер
**qlnxe**
поддерживает адаптеры 25/40/100 Gigabit Ethernet & CNA на основе следующих
чипсетов:

*	Серия QLogic 45000
*	Серия QLogic 41000



Драйвер
**qlxgb**
поддерживает адаптеры 10 Gigabit Ethernet & CNA на основе следующих
чипсетов:

*	Серия QLogic 3200
*	Серия QLogic 8200



Драйвер
**qlxgbe**
поддерживает адаптеры 10 Gigabit Ethernet & CNA на основе следующих
чипсетов:

*	Серия QLogic 8300



Драйвер
**qlxge**
поддерживает адаптеры 10 Gigabit Ethernet & CNA на основе следующих
чипсетов:

*	Серия QLogic 8100



Драйвер
**re**
поддерживает адаптеры Fast Ethernet и Gigabit Ethernet на основе RealTek RTL8139C+, RTL8169, RTL816xS, RTL811xS, RTL8168,
RTL810xE и RTL8111, включая:

*	Alloy Computer Products EtherGOLD 1439E 10/100 (8139C+)
*	Встроенный Ethernet Compaq Evo N1015v (8139C+)
*	Corega CG-LAPCIGT Gigabit Ethernet (8169S)
*	D-Link DGE-528(T) Gigabit Ethernet (8169S)
*	Встроенный Gigabit Ethernet Gigabyte 7N400 Pro2 (8110S)
*	LevelOne GNC-0105T (8169S)
*	LinkSys EG1032 (32-бит PCI)
*	PLANEX COMMUNICATIONS Inc. GN-1200TC (8169S)
*	TP-Link TG-3468 v2 Gigabit Ethernet (8168)
*	USRobotics USR997902 Gigabit Ethernet (8169S)
*	Xterasys XN-152 10/100/1000 NIC (8169)



Адаптеры, поддерживаемые драйвером
**rl**
, включают:

*	Accton
	"Cheetah"
	EN1207D (MPX 5030/5038; клон RealTek 8139)
*	Allied Telesyn AT2550
*	Allied Telesyn AT2500TX
*	Belkin F5D5000
*	BUFFALO (Melco INC.) LPC-CB-CLX (CardBus)
*	Compaq HNE-300
*	Сетевая карта CompUSA no-name 10/100 PCI Ethernet
*	Corega FEther CB-TXD
*	Corega FEtherII CB-TXD
*	D-Link DFE-520TX (ревизия C1)
*	D-Link DFE-528TX
*	D-Link DFE-530TX+
*	D-Link DFE-538TX
*	D-Link DFE-690TXD
*	Edimax EP-4103DL CardBus
*	Encore ENL832-TX 10/100 M PCI
*	Farallon NetLINE 10/100 PCI
*	Genius GF100TXR
*	GigaFast Ethernet EE100-AXP
*	KTX-9130TX 10/100 Fast Ethernet
*	LevelOne FPC-0106TX
*	Longshine LCS-8038TX-R
*	NDC Communications NE100TX-E
*	Netronix Inc. EA-1210 NetEther 10/100
*	Nortel Networks 10/100BaseTX
*	OvisLink LEF-8129TX
*	OvisLink LEF-8139TX
*	Peppercon AG ROL-F
*	Planex FNW-3603-TX
*	Planex FNW-3800-TX
*	SMC EZ Card 10/100 PCI 1211-TX
*	SOHO (PRAGMATIC) UE-1211C



Драйвер
**rue**
поддерживает USB-адаптеры Ethernet на основе RealTek RTL8150,
включая:

*	Buffalo (Melco Inc.) LUA-KTX
*	Green House GH-USB100B
*	LinkSys USB100M
*	Billionton 10/100 FastEthernet USBKR2




Драйвер
**sfxge**
поддерживает все адаптеры 10Gb Ethernet на основе контроллеров
семейства Solarflare SFC9000.



Драйвер устройства
**sge**
обеспечивает поддержку следующих контроллеров Ethernet:

*	Контроллер SiS190 Fast Ethernet
*	Контроллер SiS191 Fast/Gigabit Ethernet



Драйвер
**sis**
поддерживает адаптеры Fast Ethernet и встроенные контроллеры на основе
Silicon Integrated Systems SiS 900 и SiS 7016,
а также адаптеры Fast Ethernet
на основе чипов National Semiconductor DP83815 (MacPhyter) и DP83816.
Поддерживаемые адаптеры включают:

*	@Nifty FNECHARD IFC USUP-TX
*	MELCO LGY-PCI-TXC
*	Netgear FA311-TX (DP83815)
*	Netgear FA312-TX (DP83815)
*	Чипсеты материнских плат SiS 630, 635 и 735
*	Soekris Engineering net45xx, net48xx, lan1621 и lan1641



Адаптеры, поддерживаемые драйвером
**sk**
, включают:

*	3Com 3C940 однопортовый адаптер 1000baseT
*	3Com 3C2000-T однопортовый адаптер 1000baseT
*	Belkin F5D5005 однопортовый адаптер 1000baseT
*	D-Link DGE-530T однопортовый адаптер 1000baseT
*	Linksys (ревизия 2) однопортовый адаптер 1000baseT
*	SK-9521 SK-NET GE-T однопортовый адаптер 1000baseT
*	SK-9821 SK-NET GE-T однопортовый адаптер 1000baseT
*	SK-9822 SK-NET GE-T двухпортовый адаптер 1000baseT
*	SK-9841 SK-NET GE-LX однопортовый адаптер одномодового волокна
*	SK-9842 SK-NET GE-LX двухпортовый адаптер одномодового волокна
*	SK-9843 SK-NET GE-SX однопортовый адаптер многомодового волокна
*	SK-9844 SK-NET GE-SX двухпортовый адаптер многомодового волокна
*	SMC 9452TX однопортовый адаптер 1000baseT



Следующие устройства
поддерживаются драйвером
**smsc**:

*	Адаптеры Ethernet на основе LAN9500, LAN9500A, LAN9505 и LAN9505A
*	Адаптеры Ethernet на основе LAN89530, LAN9530 и LAN9730
*	Адаптеры Ethernet LAN951x со встроенным USB-концентратором




Драйвер
**ste**
поддерживает адаптеры Fast Ethernet и встроенные контроллеры
на основе Sundance Technologies ST201, включая:

*	D-Link DFE-530TXS
*	D-Link DFE-550TX
*	D-Link DFE-580TX



Драйвер
**stge**
обеспечивает поддержку различных сетевых карт на основе чипов контроллера
Gigabit Ethernet Sundance/Tamarack TC9021, включая:

*	Antares Microsystems Gigabit Ethernet
*	ASUS NX1101 Gigabit Ethernet
*	D-Link DL-4000 Gigabit Ethernet
*	IC Plus IP1000A Gigabit Ethernet
*	Sundance ST-2021 Gigabit Ethernet
*	Sundance ST-2023 Gigabit Ethernet
*	Sundance TC9021 Gigabit Ethernet
*	Tamarack TC9021 Gigabit Ethernet



Драйвер
**ti**
поддерживает адаптеры Gigabit Ethernet на основе
чипов Alteon Tigon I и II.
Драйвер
**ti**
тестировался со следующими адаптерами:

*	Адаптер 3Com 3c985-SX Gigabit Ethernet (Tigon 1)
*	Адаптер 3Com 3c985B-SX Gigabit Ethernet (Tigon 2)
*	Адаптер Alteon AceNIC V Gigabit Ethernet (1000baseSX)
*	Адаптер Alteon AceNIC V Gigabit Ethernet (1000baseT)
*	Адаптер Digital EtherWORKS 1000SX PCI Gigabit
*	Адаптер Netgear GA620 Gigabit Ethernet (1000baseSX)
*	Адаптер Netgear GA620T Gigabit Ethernet (1000baseT)

Следующие адаптеры также должны поддерживаться, но
еще не тестировались:

*	Адаптер Asante GigaNIX1000T Gigabit Ethernet
*	Адаптер Asante PCI 1000BASE-SX Gigabit Ethernet
*	Адаптер Farallon PN9000SX Gigabit Ethernet
*	NEC Gigabit Ethernet
*	Адаптер Silicon Graphics PCI Gigabit Ethernet




Встроенные контроллеры Gigabit Ethernet
в следующих системах-на-кристалле
Freescale, как известно, работают с драйвером
**tsec**:

*	MPC8349
*	MPC8533, MPC8541, MPC8555

Усовершенствованная версия контроллера (eTSEC), интегрированная в следующие
устройства, также поддерживается этим драйвером:

*	MPC8548, MPC8572




Драйвер
**udav**
поддерживает следующие адаптеры:

*	Corega FEther USB-TXC
*	ShanTou ST268 USB NIC



Устройства, поддерживаемые драйвером
**ufoma**
, включают:

*	SHARP FOMA SH902i
*	KYOCERA PHS AH-K3001V (также известный как Kyopon)
*	SANYO Vodafone3G V801SA



Драйвер
**uhso**
должен работать с большинством устройств от Option.
Следующие устройства проверены на работоспособность:

*	Option GlobeSurfer iCON 7.2 (новая прошивка)
*	Option GlobeTrotter Max 7.2 (новая прошивка)
*	Option iCON 225
*	Option iCON 452
*	Option iCON 505

Устройство имеет устройство хранения данных, называемое
"Zero-CD"
которое содержит драйверы для Microsoft Windows; это режим
по умолчанию для устройства.
Драйвер
**uhso**
автоматически переключает устройство из режима
"Zero-CD"
в режим модема.
Это поведение может быть отключено путем установки
*hw.usb.uhso.auto_switch*
в 0 с помощью
sysctl(8).



Драйвер
**ure**
поддерживает следующие USB-контроллеры Ethernet:

	Модель:                                          Скорость (Мбит/с):
	Realtek RTL8156/RTL8156B/RTL8156BG              10, 100, 1000 и 2500
	Realtek RTL8153/RTL8153B                        10, 100 и 1000
	Realtek RTL8152                                 10 и 100
	Realtek RTL8168/8169/8110/8211 через rgephy(4)  10, 100 и 1000



Драйвер
**urndis**
поддерживает функциональность
"модема" (tethering)
многих устройств Android.



Драйвер
**vge**
поддерживает адаптеры Gigabit Ethernet на основе VIA Networking VT6120, VT6122, VT6130 и VT6132,
включая:

*	Встроенный Gigabit Ethernet VIA Networking LAN-on-motherboard
*	Сетевая карта ZyXEL GN650-T 64-бит PCI Gigabit Ethernet (ZX1701)
*	Сетевая карта ZyXEL GN670-T 32-бит PCI Gigabit Ethernet (ZX1702)



Драйвер
**vr**
поддерживает адаптеры Fast Ethernet на основе VIA Technologies Rhine I, Rhine II и Rhine III,
включая:

*	AOpen/Acer ALN-320
*	D-Link DFE520-TX
*	D-Link DFE530-TX
*	Hawking Technologies PN102TX
*	Soekris Engineering net5501



Драйвер устройства
**vte**
обеспечивает поддержку следующих контроллеров Ethernet:

*	Контроллер DM&P Vortex86 RDC R6040 Fast Ethernet






Драйвер
**xl**
поддерживает следующее оборудование:

*	3Com 3c900-TPO
*	3Com 3c900-COMBO
*	3Com 3c905-TX
*	3Com 3c905-T4
*	3Com 3c900B-TPO
*	3Com 3c900B-TPC
*	3Com 3c900B-FL
*	3Com 3c900B-COMBO
*	3Com 3c905B-T4
*	3Com 3c905B-TX
*	3Com 3c905B-FX
*	3Com 3c905B-COMBO
*	3Com 3c905C-TX
*	Серверные адаптеры 3Com 3c980, 3c980B и 3c980C
*	Адаптеры 3Com 3cSOHO100-TX OfficeConnect
*	Адаптеры 3Com 3c450 HomeConnect
*	Адаптеры 3Com 3c555, 3c556 и 3c556B mini-PCI
*	Адаптеры CardBus 3Com 3C3SH573BT, 3C575TX, 3CCFE575BT, 3CXFE575BT, 3CCFE575CT, 3CXFE575CT,
	3CCFEM656, 3CCFEM656B и 3CCFEM656C, 3CXFEM656, 3CXFEM656B и
	3CXFEM656C
*	Встроенные адаптеры 3Com 3c905-TX, 3c905B-TX 3c905C-TX, 3c920B-EMB и 3c920B-EMB-WNM

Как семейство карт CardBus 3C656, так и семейство карт MiniPCI
3C556 имеют встроенный проприетарный модем.
Ни драйвер
**xl**,
ни любой другой драйвер
FreeBSD
не поддерживает этот модем.


[[switch]]
=== Коммутаторы Ethernet

Драйвер man:adm6996fc[4] поддерживает контроллер коммутатора Fast Ethernet Infineon ADM6996FC.


Драйвер
**ar40xx_switch**
поддерживает следующие контроллеры коммутаторов Gigabit Ethernet:

*	Qualcomm IPQ 4019 Пятипортовый коммутатор Gigabit Ethernet
*	Qualcomm IPQ 4018 Пятипортовый коммутатор Gigabit Ethernet



Драйвер
**arswitch**
поддерживает следующие контроллеры коммутаторов Ethernet:

*	Atheros AR8327 Семипортовый коммутатор Gigabit Ethernet
*	Atheros AR8316 Шестипортовый коммутатор Gigabit Ethernet
*	Atheros AR8236 Шестипортовый коммутатор Fast Ethernet
*	Atheros AR8226 Шестипортовый коммутатор Fast Ethernet
*	Atheros AR8216 Шестипортовый коммутатор Fast Ethernet



Драйвер
**e6000sw**
поддерживает следующие контроллеры коммутаторов Gigabit Ethernet:

*	Marvell 88E6190X
*	Marvell 88E6190
*	Marvell 88E6176
*	Marvell 88E6172
*	Marvell 88E6341
*	Marvell 88E6141



Драйвер
**e6060sw**
поддерживает следующие контроллеры коммутаторов Fast Ethernet:

*	Marvell 88E6060
*	Marvell 88E6063
*	Marvell 88E6065


Драйвер man:felix[4] поддерживает контроллер коммутатора Gigabit Ethernet Microsemi VSC9959 Felix, найденный в SoC NXP Layerscape LS1028A.


Драйвер
**ip17x**
поддерживает следующие контроллеры коммутаторов Fast Ethernet:

*	IC Plus IP178C
*	IC Plus IP175D
*	IC Plus IP175C
*	IC Plus IP175A


Драйвер man:ksz8995ma[4] поддерживает контроллер коммутатора Fast Ethernet Micrel KSZ8995MA/KSZ8995FQ.


Драйвер
**mtkswitch**
поддерживает следующие контроллеры коммутаторов Ethernet:

*	MediaTek MT7628 (5 портов Fast Ethernet)
*	MediaTek MT7621 (5 портов Gigabit Ethernet)
*	MediaTek MT7620 (5 портов Fast Ethernet)
*	Ralink RT5350 (5 портов Fast Ethernet)
*	Ralink RT3352 (5 портов Fast Ethernet)
*	Ralink RT3050 (5 портов Fast Ethernet)


Драйвер *rtl8366* поддерживает контроллер коммутатора Gigabit Ethernet Realtek 8366.

Драйвер *ukswitch* предназначен для поддержки потенциально неизвестных коммутаторов Ethernet.

[[wlan]]
=== Беспроводные сетевые интерфейсы


Драйвер
**ath**
поддерживает все карты Atheros Cardbus, ExpressCard, PCI и PCIe,
за исключением тех, которые основаны на чипсете AR5005VL.



Следующие карты входят в число
поддерживаемых модулем
**ath_hal**:

	*Карта*               Чип       Шина       Стандарт
	Aztech WL830PC       AR5212    CardBus    b/g
	D-Link DWL-A650      AR5210    CardBus    a
	D-Link DWL-AB650     AR5211    CardBus    a/b
	D-Link DWL-A520      AR5210    PCI        a
	D-Link DWL-AG520     AR5212    PCI        a/b/g
	D-Link DWL-AG650     AR5212    CardBus    a/b/g
	D-Link DWL-G520B     AR5212    PCI        b/g
	D-Link DWL-G650B     AR5212    CardBus    b/g
	Elecom LD-WL54AG     AR5212    Cardbus    a/b/g
	Elecom LD-WL54       AR5211    Cardbus    a
	Fujitsu E5454        AR5212    Cardbus    a/b/g
	Fujitsu FMV-JW481    AR5212    Cardbus    a/b/g
	Fujitsu E5454        AR5212    Cardbus    a/b/g
	HP NC4000            AR5212    PCI        a/b/g
	I/O Data WN-AB       AR5212    CardBus    a/b
	I/O Data WN-AG       AR5212    CardBus    a/b/g
	I/O Data WN-A54      AR5212    CardBus    a
	Linksys WMP55AG      AR5212    PCI        a/b/g
	Linksys WPC51AB      AR5211    CardBus    a/b
	Linksys WPC55AG      AR5212    CardBus    a/b/g
	NEC PA-WL/54AG       AR5212    CardBus    a/b/g
	Netgear WAG311       AR5212    PCI        a/b/g
	Netgear WAB501       AR5211    CardBus    a/b
	Netgear WAG511       AR5212    CardBus    a/b/g
	Netgear WG311 (также WG311v1) AR5212    PCI        b/g
	Netgear WG311v2      AR5212    PCI        b/g
	Netgear WG311T       AR5212    PCI        b/g
	Netgear WG511T       AR5212    CardBus    b/g
	Orinoco 8480         AR5212    CardBus    a/b/g
	Orinoco 8470WD       AR5212    CardBus    a/b/g
	Proxim Skyline 4030  AR5210    CardBus    a
	Proxim Skyline 4032  AR5210    PCI        a
	Samsung SWL-5200N    AR5212    CardBus    a/b/g
	SMC SMC2735W         AR5210    CardBus    a
	Sony PCWA-C700       AR5212    Cardbus    a/b
	Sony PCWA-C300S      AR5212    Cardbus    b/g
	Sony PCWA-C500       AR5210    Cardbus    a
	3Com 3CRPAG175       AR5212    CardBus    a/b/g
	TP-LINK TL-WDN4800   AR9380    PCIe       a/b/g/n



Драйвер
**bwi**
поддерживает беспроводные устройства на основе Broadcom BCM43xx, включая:

	*Карта*                   *Чип*     *Шина*       *Стандарт*
	Apple Airport Extreme    BCM4306    PCI         b/g
	Apple Airport Extreme    BCM4318    PCI         b/g
	ASUS WL-100g             BCM4306    CardBus     b/g
	ASUS WL-138g             BCM4318    PCI         b/g
	Buffalo WLI-CB-G54S      BCM4318    CardBus     b/g
	Buffalo WLI-PCI-G54S     BCM4306    PCI         b/g
	Compaq R4035 onboard     BCM4306    PCI         b/g
	Dell Wireless 1390       BCM4311    Mini PCI    b/g
	Dell Wireless 1470       BCM4318    Mini PCI    b/g
	Dell Truemobile 1300 r2  BCM4306    Mini PCI    b/g
	Dell Truemobile 1400     BCM4309    Mini PCI    b/g
	HP nx6125                BCM4319    PCI         b/g
	Linksys WPC54G Ver 3     BCM4318    CardBus     b/g
	Linksys WPC54GS Ver 2    BCM4318    CardBus     b/g
	TRENDnet TEW-401PCplus   BCM4306    CardBus     b/g
	US Robotics 5411         BCM4318    CardBus     b/g

Драйвер
**bwi**
использует более старую версию v3 прошивки Broadcom.
Хотя эта старая прошивка поддерживает большинство компонентов BCM43xx,
драйвер bwn(4)
работает лучше для новых чипов, которые он поддерживает.
Вы должны использовать драйвер
**bwi**
если вы используете старые чипсеты Broadcom (BCM4301, BCM4303 и
BCM4306 rev 2).
Версия v4 прошивки, которую использует
bwn(4),
не поддерживает эти чипы.



Драйвер
**bwn**
поддерживает беспроводные устройства на основе Broadcom BCM43xx, включая:

	*Карта*                   *Чип*     *Шина*       *Стандарт*
	Apple Airport Extreme    BCM4318    PCI         b/g
	ASUS WL-138g             BCM4318    PCI         b/g
	Buffalo WLI-CB-G54S      BCM4318    CardBus     b/g
	Dell Wireless 1390       BCM4311    Mini PCI    b/g
	Dell Wireless 1470       BCM4318    Mini PCI    b/g
	Dell Truemobile 1400     BCM4309    Mini PCI    b/g
	HP Compaq 6715b          BCM4312    PCI         b/g
	HP nx6125                BCM4319    PCI         b/g
	Linksys WPC54G Ver 3     BCM4318    CardBus     b/g
	Linksys WPC54GS Ver 2    BCM4318    CardBus     b/g
	US Robotics 5411         BCM4318    CardBus     b/g

Пользователи старых чипсетов Broadcom (BCM4301, BCM4303 и BCM4306 rev 2)
должны использовать
bwi(4),
потому что версия v4 прошивки не поддерживает эти чипы.
Новая прошивка слишком велика, чтобы поместиться в эти старые чипы.



Драйвер
**ipw**
обеспечивает поддержку
сетевого адаптера Intel PRO/Wireless 2100a/b MiniPCI.



Драйвер
**iwi**
поддерживает следующие беспроводные сетевые устройства:

*	Сетевое подключение Intel PRO/Wireless 2200BG MiniPCI
*	Сетевое подключение Intel PRO/Wireless 2225BG PCI
*	Сетевое подключение Intel PRO/Wireless 2915ABG MiniPCI



Драйвер
**iwlwifi**
поддерживает устройства PCIe из
под-драйвера **mvm**
со следующими поколениями чипсетов:

*	7000
*	8000
*	9000
*	22000
*	AX210

Драйвер
**iwlwifi**
поддерживает устройства PCIe из
под-драйвера **mld**
со следующими поколениями чипсетов:

*	BZ
*	SC

Эти поколения чипсетов соответствуют следующим распространенным названиям устройств:

*	Intel(R) Dual Band Wireless AC 7260
*	Intel(R) Dual Band Wireless N 7260
*	Intel(R) Wireless N 7260
*	Intel(R) Dual Band Wireless AC 3160
*	Intel(R) Dual Band Wireless N 3160
*	Intel(R) Wireless N 3160
*	Intel(R) Dual Band Wireless AC 3165
*	Intel(R) Dual Band Wireless AC 3168
*	Intel(R) Dual Band Wireless AC 7265
*	Intel(R) Wireless N 7265
*	Intel(R) Dual Band Wireless N 7265
*	Intel(R) Dual Band Wireless AC 8260
*	Intel(R) Dual Band Wireless N 8260
*	Intel(R) Dual Band Wireless AC 4165
*	Intel(R) Dual Band Wireless AC 8265
*	Intel(R) Dual Band Wireless AC 8275
*	Беспроводной сетевой адаптер Killer (R) Wireless-AC 1550 (9260NGW) 160MHz
*	Беспроводной сетевой адаптер Killer (R) Wireless-AC 1550s (9560NGW)
*	Беспроводной сетевой адаптер Killer (R) Wireless-AC 1550i (9560NGW)
*	Беспроводной сетевой адаптер Killer(R) Wireless-AC 1550s (9560D2W) 160MHz
*	Беспроводной сетевой адаптер Killer(R) Wireless-AC 1550i (9560NGW) 160MHz
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6E AX1690s 160MHz (411D2W)
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6E AX1690i 160MHz (411NGW)
*	Intel(R) Wireless-AC 9260-1
*	Intel(R) Wi-Fi 6 AX200 160MHz
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6 AX1650w 160MHz (200D2W)
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6 AX1650x 160MHz (200NGW)
*	Intel(R) Wi-Fi 6 AX201 160MHz
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6 AX1650s 160MHz (201D2W)
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6 AX1650i 160MHz (201NGW)
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6 AX1650s 160MHz (201NGW)
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6 AX1650i 160MHz (201D2W)
*	Intel(R) Wi-Fi 6E AX211 160MHz
*	Intel(R) Wi-Fi 6 AX210 160MHz
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6E AX1675w 160MHz (210D2W)
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6E AX1675x 160MHz (210NGW)
*	Intel(R) Wi-Fi 6E AX411 160MHz
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6E AX1675s 160MHz (211NGW)
*	Беспроводной сетевой адаптер Killer(R) Wi-Fi 6E AX1675i 160MHz (211NGW)
*	Intel(R) Wireless-AC 9461 160MHz
*	Intel(R) Wireless-AC 9461
*	Intel(R) Wireless-AC 9462 160MHz
*	Intel(R) Wireless-AC 9462
*	Intel(R) Wireless-AC 9560 160MHz
*	Intel(R) Wireless-AC 9560
*	Intel(R) Wireless-AC 9270 160MHz
*	Intel(R) Wireless-AC 9270
*	Intel(R) Wireless-AC 9162 160MHz
*	Intel(R) Wireless-AC 9162
*	Intel(R) Wireless-AC 9260 160MHz
*	Intel(R) Wireless-AC 9260
*	Intel(R) Wi-Fi 6 AX101
*	Intel(R) Wi-Fi 6 AX203
*	Intel(R) Wi-Fi 6E AX231 160MHz
*	Intel(R) Wi-Fi 7 BE201 320MHz
*	Intel(R) Wi-Fi 7 BE200 320MHz
*	Intel(R) Wi-Fi 7 BE202 160MHz
*	Intel(R) TBD Sc device
*	Intel(R) TBD Sc2 device
*	Intel(R) TBD Sc2f device



Драйвер
**iwm**
поддерживает следующие устройства Wi-Fi PCIe:

*	Intel Dual Band Wireless AC 3160
*	Intel Dual Band Wireless AC 3165
*	Intel Dual Band Wireless AC 3168
*	Intel Dual Band Wireless AC 7260
*	Intel Dual Band Wireless AC 7265
*	Intel Dual Band Wireless AC 8260
*	Intel Dual Band Wireless AC 8265
*	Intel Dual Band Wireless AC 9260
*	Intel Dual Band Wireless AC 9270
*	Intel Dual Band Wireless AC 946X
*	Intel Dual Band Wireless AC 9560



Драйвер
**iwn**
обеспечивает поддержку:

*	Intel Centrino Advanced-N 6200
*	Intel Centrino Advanced-N 6205
*	Intel Centrino Advanced-N 6230
*	Intel Centrino Advanced-N 6235
*	Intel Centrino Advanced-N + WiMAX 6250
*	Intel Centrino Ultimate-N 6300
*	Intel Centrino Wireless-N 100
*	Intel Centrino Wireless-N 105
*	Intel Centrino Wireless-N 130
*	Intel Centrino Wireless-N 135
*	Intel Centrino Wireless-N 1000
*	Intel Centrino Wireless-N 1030
*	Intel Centrino Wireless-N 2200
*	Intel Centrino Wireless-N 2230
*	Intel Centrino Wireless-N 4965
*	Intel Centrino Wireless-N 5100
*	Intel Centrino Wireless-N 6150
*	Intel Centrino Wireless-N 6200
*	Intel Centrino Wireless-N 6250
*	Intel Centrino Wireless-N + WiMAX 6150
*	Intel Ultimate N WiFi Link 5300
*	Intel Wireless WiFi Link 4965
*	Intel WiFi Link 5100
*	Intel WiMAX/WiFi Link 5150
*	Intel WiMAX/WiFi Link 5350



Драйвер
**iwx**
поддерживает следующие беспроводные сетевые адаптеры M.2:

*	Intel Wi-Fi 6 AX200
*	Intel Wi-Fi 6 AX201 CNVi
*	Intel Wi-Fi 6 AX210
*	Intel Wi-Fi 6 AX211 CNVi



Следующие карты входят в число
поддерживаемых драйвером
**malo**:

	*Карта*             *Чип*     *Шина*  *Стандарт*
	Netgear WG311v3    88W8335    PCI    b/g
	Tenda TWL542P      88W8335    PCI    b/g
	U-Khan UW-2054i    88W8335    PCI    b/g


Беспроводные сетевые адаптеры Marvell 88W8363 IEEE 802.11n (драйвер man:mwl[4])


Драйвер
**mtw**
поддерживает USB-адаптеры беспроводной сети на основе MediaTek MT7601U,
включая (но не все из них протестированы):

*	ASUS USB-N10 v2
*	D-Link DWA-127 rev B1
*	Edimax EW-7711UAn v2
*	Foxconn WFU03
*	Tenda U2
*	Tenda W311MI v2
*	TP-LINK TL-WN727N v4 (протестировано, работает)
*	Yealink WF40



Драйвер
**otus**
обеспечивает поддержку беспроводных сетевых адаптеров Atheros AR9170 USB IEEE 802.11b/g/n,
включая:

*	3Com 3CRUSBN275
*	Arcadyan WN7512
*	CACE AirPcap Nx
*	D-Link DWA-130 rev D1
*	D-Link DWA-160 rev A1
*	D-Link DWA-160 rev A2
*	IO-Data WN-GDN/US2
*	NEC Aterm WL300NU-G
*	Netgear WNDA3100
*	Netgear WN111 v2
*	Planex GW-US300
*	SMC Networks SMCWUSB-N2
*	TP-Link TL-WN821N v1, v2
*	Ubiquiti SR71 USB
*	Unex DNUA-81
*	Z-Com UB81
*	Z-Com UB82
*	ZyXEL NWD-271N



Драйвер
**ral**
поддерживает беспроводные адаптеры PCI/PCIe/CardBus на основе чипсетов Ralink Technology,
включая:

	*Карта*                       *MAC/BBP*  *Шина*
	A-Link WL54H                 RT2560     PCI
	A-Link WL54PC                RT2560     CardBus
	AirLink101 AWLC5025          RT2661     CardBus
	AirLink101 AWLH5025          RT2661     PCI
	Amigo AWI-914W               RT2560     CardBus
	Amigo AWI-922W               RT2560     mini-PCI
	Amigo AWI-926W               RT2560     PCI
	AMIT WL531C                  RT2560     CardBus
	AMIT WL531P                  RT2560     PCI
	AOpen AOI-831                RT2560     PCI
	ASUS WL-107G                 RT2560     CardBus
	ASUS WL-130g                 RT2560     PCI
	Atlantis Land A02-PCI-W54    RT2560     PCI
	Atlantis Land A02-PCM-W54    RT2560     CardBus
	Belkin F5D7000 v3            RT2560     PCI
	Belkin F5D7010 v2            RT2560     CardBus
	Billionton MIWLGRL           RT2560     mini-PCI
	Canyon CN-WF511              RT2560     PCI
	Canyon CN-WF513              RT2560     CardBus
	CC&C WL-2102                 RT2560     CardBus
	CNet CWC-854                 RT2560     CardBus
	CNet CWP-854                 RT2560     PCI
	Compex WL54G                 RT2560     CardBus
	Compex WLP54G                RT2560     PCI
	Conceptronic C54RC           RT2560     CardBus
	Conceptronic C54Ri           RT2560     PCI
	D-Link DWA-525 rev A2        RT5392     PCI
	Digitus DN-7001G-RA          RT2560     CardBus
	Digitus DN-7006G-RA          RT2560     PCI
	E-Tech WGPC02                RT2560     CardBus
	E-Tech WGPI02                RT2560     PCI
	Edimax EW-7108PCg            RT2560     CardBus
	Edimax EW-7128g              RT2560     PCI
	Eminent EM3036               RT2560     CardBus
	Eminent EM3037               RT2560     PCI
	Encore ENLWI-G-RLAM          RT2560     PCI
	Encore ENPWI-G-RLAM          RT2560     CardBus
	Fiberline WL-400P            RT2560     PCI
	Fibreline WL-400X            RT2560     CardBus
	Gigabyte GN-WI01GS           RT2561S    mini-PCI
	Gigabyte GN-WIKG             RT2560     mini-PCI
	Gigabyte GN-WMKG             RT2560     CardBus
	Gigabyte GN-WP01GS           RT2561S    PCI
	Gigabyte GN-WPKG             RT2560     PCI
	Hawking HWC54GR              RT2560     CardBus
	Hawking HWP54GR              RT2560     PCI
	iNexQ CR054g-009 (R03)       RT2560     PCI
	JAHT WN-4054P                RT2560     CardBus
	JAHT WN-4054PCI              RT2560     PCI
	LevelOne WNC-0301 v2         RT2560     PCI
	LevelOne WPC-0301 v2         RT2560     CardBus
	Linksys WMP54G v4            RT2560     PCI
	Micronet SP906GK             RT2560     PCI
	Micronet SP908GK V3          RT2560     CardBus
	Minitar MN54GCB-R            RT2560     CardBus
	Minitar MN54GPC-R            RT2560     PCI
	MSI CB54G2                   RT2560     CardBus
	MSI MP54G2                   RT2560     mini-PCI
	MSI PC54G2                   RT2560     PCI
	OvisLink EVO-W54PCI          RT2560     PCI
	PheeNet HWL-PCIG/RA          RT2560     PCI
	Planex GW-NS300N             RT2860     CardBus
	Pro-Nets CB80211G            RT2560     CardBus
	Pro-Nets PC80211G            RT2560     PCI
	Repotec RP-WB7108            RT2560     CardBus
	Repotec RP-WP0854            RT2560     PCI
	SATech SN-54C                RT2560     CardBus
	SATech SN-54P                RT2560     PCI
	Sitecom WL-112               RT2560     CardBus
	Sitecom WL-115               RT2560     PCI
	SMC SMCWCB-GM                RT2661     CardBus
	SMC SMCWPCI-GM               RT2661     PCI
	SparkLAN WL-685R             RT2560     CardBus
	Surecom EP-9321-g            RT2560     PCI
	Surecom EP-9321-g1           RT2560     PCI
	Surecom EP-9428-g            RT2560     CardBus
	Sweex LC500050               RT2560     CardBus
	Sweex LC700030               RT2560     PCI
	TekComm NE-9321-g            RT2560     PCI
	TekComm NE-9428-g            RT2560     CardBus
	Unex CR054g-R02              RT2560     PCI
	Unex MR054g-R02              RT2560     CardBus
	Zinwell ZWX-G160             RT2560     CardBus
	Zinwell ZWX-G360             RT2560     mini-PCI
	Zinwell ZWX-G361             RT2560     PCI
	Zonet ZEW1500                RT2560     CardBus
	Zonet ZEW1600                RT2560     PCI



Драйвер
**rsu**
обеспечивает поддержку беспроводных сетевых адаптеров Realtek RTL8188SU/RTL8192SU USB IEEE 802.11b/g/n,
включая:

*	ASUS USB-N10
*	ASUS WL-167G V3
*	Belkin F7D1101 v1
*	D-Link DWA-131 A1
*	EDUP EP-MS150N(W)
*	Edimax EW-7622UMN
*	Hercules HWGUn-54
*	Hercules HWNUm-300
*	Planex GW-USNano
*	Sitecom WL-349 v1
*	Sitecom WL-353
*	Sitecom WLA-1100 v1001
*	Sweex LW154
*	TRENDnet TEW-646UBH
*	TRENDnet TEW-648UB
*	TRENDnet TEW-649UB



Драйвер
**rtw88**
поддерживает устройства PCIe со следующими чипсетами:

*	Realtek 802.11n беспроводной 8723de (RTL8723DE)
*	Realtek 802.11ac беспроводной 8821ce (RTL8821CE)
*	Realtek 802.11ac беспроводной 8822be (RTL8822BE)
*	Realtek 802.11ac беспроводной 8822ce (RTL8822CE)



Драйвер
**rtw89**
поддерживает устройства PCIe со следующими чипсетами:

*	Realtek 8851BE Wi-Fi 6  (RTL8851BE)
*	Realtek 8852AE Wi-Fi 6  (RTL8852AE)
*	Realtek 8852BE Wi-Fi 6  (RTL8852BE)
*	Realtek 8852CE Wi-Fi 6E (RTL8852CE)
*	Realtek 8922AE Wi-Fi 7  (RTL8922AE)



Драйвер
**rtwn_pci**
поддерживает следующие устройства Wi-Fi PCIe:

*	Realtek 802.11n беспроводной 8188  (RTL8188EE)
*	Realtek 802.11n беспроводной 8192  (RTL8192CE)



Драйвер
**rtwn_usb**
поддерживает USB-адаптеры беспроводной сети на основе некоторых
чипсетов Realtek RTL 8188/8192/8812 и 8821, включая:

	*Карта*                                *Чип*        *Шина*
	Alfa AWUS036NHR v2                    RTL8188RU     USB 2.0
	ASUS USB-AC56                         RTL8812AU     USB 3.0
	ASUS USB-N10 NANO                     RTL8188CUS    USB 2.0
	ASUS USB-N10 NANO rev B1              RTL8188EUS    USB 2.0
	Asus USB-N13, рев. B1                 RTL8192CU     USB 2.0
	Belkin F7D1102 Surf Wireless Micro    RTL8188CUS    USB 2.0
	Buffalo WI-U2-433DHP                  RTL8821AU     USB 2.0
	Buffalo WI-U2-433DM                   RTL8821AU     USB 2.0
	Buffalo WI-U3-866D                    RTL8812AU     USB 3.0
	D-Link DWA-121 рев. C1A (N150 Nano)    RTL8188EU     USB 2.0
	D-Link DWA-123 рев. D1                 RTL8188EU     USB 2.0
	D-Link DWA-125 рев. D1                 RTL8188EU     USB 2.0
	D-Link DWA-131                        RTL8192CU     USB 2.0
	D-Link DWA-131 рев. E1                 RTL8192EU     USB 2.0
	D-Link DWA-171 рев. A1                 RTL8821AU     USB 2.0
	D-Link DWA-172 рев. A1                 RTL8821AU     USB 2.0
	D-Link DWA-180 рев. A1                 RTL8812AU     USB 2.0
	D-Link DWA-182 рев. C1                 RTL8812AU     USB 3.0
	Edimax EW-7811Un                      RTL8188CUS    USB 2.0
	Edimax EW-7811UTC                     RTL8821AU     USB 2.0
	Edimax EW-7822UAC                     RTL8812AU     USB 3.0
	EDUP EP-AC1620                        RTL8821AU     USB 2.0
	Elecom WDC-150SU2M                    RTL8188EU     USB 2.0
	EnGenius EUB1200AC                    RTL8812AU     USB 3.0
	Foxconn WFUR6                         RTL8812AU     USB 2.0
	Hawking HD65U                         RTL8821AU     USB 2.0
	Hercules Wireless N USB Pico          RTL8188CUS    USB 2.0
	I-O Data WN-AC867U                    RTL8812AU     USB 3.0
	Linksys WUSB6300                      RTL8812AU     USB 3.0
	NEC AtermWL900U PA-WL900U             RTL8812AU     USB 3.0
	Netgear A6100                         RTL8821AU     USB 2.0
	Netgear WNA1000M                      RTL8188CUS    USB 2.0
	Mercusys MW150US                      RTL8188EU     USB 2.0
	Planex GW-900D                        RTL8812AU     USB 3.0
	Realtek RTL8192CU                     RTL8192CU     USB 2.0
	Realtek RTL8188CUS                    RTL8188CUS    USB 2.0
	Sitecom WLA-7100                      RTL8812AU     USB 3.0
	TP-Link Archer T2U Nano               RTL8821AU     USB 2.0
	TP-Link Archer T2U Plus               RTL8821AU     USB 2.0
	TP-Link Archer T2U v3                 RTL8821AU     USB 2.0
	TP-Link Archer T4U                    RTL8812AU     USB 3.0
	TP-Link Archer T4U v2                 RTL8812AU     USB 3.0
	TP-Link Archer T4UH v1                RTL8812AU     USB 3.0
	TP-Link Archer T4UH v2                RTL8812AU     USB 3.0
	TP-Link TL-WN722N v2                  RTL8188EU     USB 2.0
	TP-LINK TL-WN723N v3                  RTL8188EU     USB 2.0
	TP-LINK TL-WN725N v2                  RTL8188EU     USB 2.0
	TP-LINK TL-WN727N v5                  RTL8188EU     USB 2.0
	TP-LINK TL-WN821N v4                  RTL8192CU     USB 2.0
	TP-LINK TL-WN821N v5                  RTL8192EU     USB 2.0
	TP-LINK TL-WN822N v4                  RTL8192EU     USB 2.0
	TP-LINK TL-WN823N v1                  RTL8192CU     USB 2.0
	TP-LINK TL-WN823N v2                  RTL8192EU     USB 2.0
	TRENDnet TEW-805UB                    RTL8812AU     USB 3.0
	ZyXEL NWD6605                         RTL8812AU     USB 3.0



Драйвер
**rum**
поддерживает USB 2.0 беспроводные
адаптеры на основе чипсетов Ralink RT2501USB и RT2601USB,
включая:

	*Карта*                       *Шина*
	3Com Aolynk WUB320g          USB
	Abocom WUG2700 Ta            USB
	Airlink101 AWLL5025          USB
	ASUS WL-167g вер. 2           USB
	Belkin F5D7050 вер. 3         USB
	Belkin F5D9050 вер. 3         USB
	Buffalo WLI-U2-SG54HP        USB
	Buffalo WLI-U2-SG54HG        USB
	Buffalo WLI-U2-G54HP         USB
	Buffalo WLI-UC-G             USB
	CNet CWD-854 вер. F           USB
	Conceptronic C54RU вер. 2     USB
	Corega CG-WLUSB2GO           USB
	D-Link DWA-110               USB
	D-Link DWA-111               USB
	D-Link DWL-G122 рев. C1       USB
	D-Link WUA-1340              USB
	Digitus DN-7003GR            USB
	Edimax EW-7318USG            USB
	Gigabyte GN-WB01GS           USB
	Gigabyte GN-WI05GS           USB
	Hawking HWUG1                USB
	Hawking HWU54DM              USB
	Hercules HWGUSB2-54-LB       USB
	Hercules HWGUSB2-54V2-AP     USB
	LevelOne WNC-0301USB v3      USB
	Linksys WUSB54G рев. C        USB
	Linksys WUSB54GR             USB
	Planex GW-US54HP             USB
	Planex GW-US54Mini2          USB
	Planex GW-USMM               USB
	Senao NUB-3701               USB
	Sitecom WL-113 вер. 2         USB
	Sitecom WL-172               USB
	Sweex LW053                  USB
	TP-LINK TL-WN321G v1/v2/v3   USB



Драйвер
**run**
поддерживает следующие беспроводные адаптеры:

*	Airlink101 AWLL6090
*	ASUS USB-N11
*	ASUS USB-N13 вер. A1
*	ASUS USB-N14
*	ASUS USB-N66
*	ASUS WL-160N
*	Belkin F5D8051 вер. 3000
*	Belkin F5D8053
*	Belkin F5D8055
*	Belkin F6D4050 вер. 1
*	Belkin F9L1103
*	Buffalo WLI-UC-AG300N
*	Buffalo WLI-UC-G300HP
*	Buffalo WLI-UC-G300N
*	Buffalo WLI-UC-G301N
*	Buffalo WLI-UC-GN
*	Buffalo WLI-UC-GNM
*	Buffalo WLI-UC-GNM2
*	Corega CG-WLUSB2GNL
*	Corega CG-WLUSB2GNR
*	Corega CG-WLUSB300AGN
*	Corega CG-WLUSB300GNM
*	D-Link DWA-130 рев. B1
*	D-Link DWA-130 рев. F1
*	D-Link DWA-140 рев. B1, B2, B3, D1
*	D-Link DWA-160 рев. B2
*	D-Link DWA-162
*	DrayTek Vigor N61
*	Edimax EW-7711UAn
*	Edimax EW-7711UTn
*	Edimax EW-7717Un
*	Edimax EW-7718Un
*	Edimax EW-7733UnD
*	Gigabyte GN-WB30N
*	Gigabyte GN-WB31N
*	Gigabyte GN-WB32L
*	Hawking HWDN1
*	Hawking HWUN1
*	Hawking HWUN2
*	Hercules HWNU-300
*	Linksys WUSB54GC v3
*	Linksys WUSB600N
*	Logitec LAN-W150N/U2
*	Mvix Nubbin MS-811N
*	Panda Wireless PAU06
*	Planex GW-USMicroN
*	Planex GW-US300MiniS
*	Sitecom WL-182
*	Sitecom WL-188
*	Sitecom WL-301
*	Sitecom WL-302
*	Sitecom WL-315
*	Sitecom WL-364
*	SMC SMCWUSBS-N2
*	Sweex LW303
*	Sweex LW313
*	TP-LINK TL-WDN3200
*	TP-LINK TL-WN321G v4
*	TP-LINK TL-WN727N v3
*	Unex DNUR-81
*	Unex DNUR-82
*	ZyXEL NWD2705
*	ZyXEL NWD210N
*	ZyXEL NWD270N



Драйвер
**uath**
должен работать со следующими адаптерами:

	*Адаптер*                            *Чипсет*
	`Compex WLU108AG`                    AR5005UX
	`Compex WLU108G`                     AR5005UG
	`D-Link DWL-G132`                    AR5005UG
	`IODATA WN-G54/US`                   AR5005UG
	`MELCO WLI-U2-KAMG54`                AR5005UX
	`Netgear WG111T`                     AR5005UG
	`Netgear WG111U`                     AR5005UX
	`Netgear WPN111`                     AR5005UG
	`Olitec 000544`                      AR5005UG
	`PLANET WDL-U357`                    AR5005UX
	`Siemens Gigaset 108`                AR5005UG
	`SMC SMCWUSBT-G`                     AR5005UG
	`SMC SMCWUSBT-G2`                    AR5005UG
	`SparkLAN WL-785A`                   AR5005UX
	`TP-Link TL-WN620G`                  AR5005UG
	`TRENDware International TEW-444UB`  AR5005UG
	`TRENDware International TEW-504UB`  AR5005UX
	`Unex Technology UR054ag`            AR5005UX
	`ZyXEL XtremeMIMO M-202`             AR5005UX



Драйвер
**upgt**
поддерживает USB 2.0 беспроводные адаптеры серии Conexant/Intersil PrismGT
на основе чипсета GW3887, среди них:

*	Belkin F5D7050 (версия 1000)
*	Cohiba Proto Board
*	D-Link DWL-G120 Cohiba
*	FSC Connect2Air E-5400 USB D1700
*	Gigaset USB Adapter 54
*	Inventel UR045G
*	Netgear WG111v1 (rev2)
*	SMC EZ ConnectG SMC2862W-G
*	Sagem XG703A
*	Spinnaker DUT
*	Spinnaker Proto Board



Драйвер
**ural**
поддерживает USB 2.0 беспроводные адаптеры на основе чипсета Ralink Technology
RT2500USB, включая:

	*Карта*                       *Шина*
	AMIT WL532U                  USB
	ASUS WL-167g                 USB
	Belkin F5D7050 v2000         USB
	Buffalo WLI-U2-KG54-AI       USB
	CNet CWD-854                 USB
	Compex WLU54G 2A1100         USB
	Conceptronic C54RU           USB
	D-Link DWL-G122 b1           USB
	Dynalink WLG25USB            USB
	E-Tech WGUS02                USB
	Gigabyte GN-WBKG             USB
	Hercules HWGUSB2-54          USB
	KCORP LifeStyle KLS-685      USB
	Linksys WUSB54G v4           USB
	Linksys WUSB54GP v4          USB
	MSI MS-6861                  USB
	MSI MS-6865                  USB
	MSI MS-6869                  USB
	NovaTech NV-902              USB
	OvisLink Evo-W54USB          USB
	SerComm UB801R               USB
	SparkLAN WL-685R             USB
	Surecom EP-9001-g            USB
	Sweex LC100060               USB
	Tonze UW-6200C               USB
	Zinwell ZWX-G261             USB
	Zonet ZEW2500P               USB

Актуальный список можно найти по адресу
*http://ralink.rapla.net/*.



Драйвер
**urtw**
поддерживает беспроводные сетевые устройства на основе Realtek RTL8187B/L, включая:

	*Карта*                        *Радио*    *Шина*
	Belkin F5D7050E               RTL8225    USB
	Linksys WUSB54GCv2            RTL8225    USB
	Netgear WG111v2               RTL8225    USB
	Netgear WG111v3               RTL8225    USB
	Safehome WLG-1500SMA5         RTL8225    USB
	Shuttle XPC Accessory PN20    RTL8225    USB
	Sitecom WL168v1               RTL8225    USB
	Sitecom WL168v4               RTL8225    USB
	SureCom EP-9001-g(2A)         RTL8225    USB
	TRENDnet TEW-424UB V3.xR      RTL8225    USB



Драйвер
**wpi**
обеспечивает поддержку
сетевого адаптера Intel PRO/Wireless 3945ABG Mini PCIe.



Следующие устройства, как известно,
поддерживаются драйвером
**zyd**:

*	3COM 3CRUSB10075
*	Acer WLAN-G-US1
*	Airlink+ AWLL3025
*	Airlink 101 AWLL3026
*	AOpen 802.11g WL54
*	Asus A9T встроенный беспроводной
*	Asus WL-159g
*	Belkin F5D7050 в.4000
*	Billion BiPAC 3011G
*	Buffalo WLI-U2-KG54L
*	CC&C WL-2203B
*	DrayTek Vigor 550
*	Edimax EW-7317UG
*	Edimax EW-7317LDG
*	Fiberline Networks WL-43OU
*	iNexQ UR055g
*	Linksys WUSBF54G
*	Longshine LCS-8131G3
*	MSI US54SE
*	MyTek MWU-201 USB адаптер
*	Philips SNU5600
*	Planet WL-U356
*	Planex GW-US54GZ
*	Planex GW-US54GZL
*	Planex GW-US54Mini
*	Safecom SWMULZ-5400
*	Sagem XG 760A
*	Sagem XG 76NA
*	Sandberg Wireless G54 USB
*	Sitecom WL-113
*	SMC SMCWUSB-G
*	Sweex wireless USB 54 Mbps
*	Tekram/Siemens USB адаптер
*	Telegent TG54USB
*	Trendnet TEW-424UB рев. A
*	Trendnet TEW-429UB
*	TwinMOS G240
*	Unicorn WL-54G
*	US Robotics 5423
*	X-Micro XWL-11GUZX
*	Yakumo QuickWLAN USB
*	Zonet ZEW2501
*	ZyXEL ZyAIR G-202
*	ZyXEL ZyAIR G-220


[[misc-network]]
=== Прочие сетевые устройства






Драйвер
**u3g**
поддерживает следующие сотовые модемы:

*	Option GT 3G Fusion, GT Fusion Quad и др.
	(только 3G, не WLAN)
*	Option GT 3G, GT 3G Quad и др.
*	Vodafone Mobile Connect Card 3G
*	Vodafone Mobile Broadband K3772-Z
*	Qualcomm Inc. CDMA MSM
*	Устройства Qualcomm Inc. GOBI 1000, 2000 и 3000 с чипсетами MDM1000 или MDM2000
*	Серии QUECTEL BGX, ECX, EGX, EMX, EPX, RGX
*	Quectel EM160R
	(см. *ПРЕДУПРЕЖДЕНИЯ*)
*	Huawei B190, E180v, E220, E3372, E3372v153, E5573Cs322, ('&lt;Huawei Mobile&gt;')
*	Novatel U740, MC950D, X950D и др.
*	Sierra MC875U, MC8775U и др.
*	Panasonic CF-F9 GOBI

Поддерживается множество других моделей, см.
*/sys/dev/usb/serial/u3g.c*
для получения полного списка.



Драйвер
**umb**
должен поддерживать любые USB-устройства, реализующие MBIM, включая
следующие сотовые модемы:

*	Ericsson H5321gw и N5321gw
*	Fibocom L831-EAU
*	Medion Mobile S4222 (производства MediaTek)
*	Sierra Wireless EM7345
*	Sierra Wireless EM7455
*	Sierra Wireless EM8805
*	Sierra Wireless MC8305


[[serial]]
=== Последовательные интерфейсы


Основной компонент и интерфейсы ядра взаимодействуют с оборудованием через
аппаратный интерфейс.
Этот интерфейс служит абстракцией оборудования и позволяет использовать
различные UART для последовательной связи.


Драйвер
**uart**
поддерживает следующие классы UART:

*	NS8250: стандартное оборудование на основе UART 8250, 16450, 16550, 16650, 16750 или
	16950.
*	SCC: контроллеры последовательной связи, поддерживаемые
	драйвером устройства
	scc(4).



Драйвер
**scc**
поддерживает следующие классы контроллеров последовательной связи:

*	QUICC: Freescale/NXP QUad Integrated Communications Controllers.
*	Z8530: контроллеры последовательной связи на основе Zilog 8530.



Драйвер
**puc**
поддерживает следующие
многопортовые последовательные и параллельные адаптеры PCI/PCIe:

*	Advantech 2-port PCI PCI-1602/1603 Rev A/B1
*	Applied Micro Circuits PCI 8 Port UART
*	Avlab Technology PCI IO 2S
*	Avlab Low Profile PCI 4 Serial
*	Boca Research PCI Turbo Serial 658/654
*	Brainboxes:

	-	Instashield PCIe IX-400, IX-200, IX-100
	-	Instashield PCI IS-400, IS-200
	-	PX Series PCIe RS232/RS422/RS485/LPT
	-	UC Series Universal PCI RS232/RS422/RS485/LPT
	-	UP Series PCI Dual RS232

*	Comtrol RocketPort 550 PCI 16/8/4 port
*	Decision Computer PCCOM PCI 8/4/2 port
*	Digi Neo PCIe 4 and 8 Port (с RJ45 и без)
*	Digi Neo PCI 4 and 8 Port
*	Dolphin Peripherals PCI 4035/4014
*	Exar:

	-	XR17C/D152
	-	XR17C154
	-	XR17C158
	-	XR17V258IV
	-	XR17V352
	-	XR17V354
	-	XR17V358

*	Feasso PCI FPP-02 2S1P
*	HP Diva Serial \[GSP] Multiport UART:

	-	Tosca Console
	-	Tosca Secondary
	-	Maestro SP2
	-	Superdome Console
	-	Keystone SP2
	-	Everest SP2

*	I-O DATA RSA-PCI2/R
*	IBM SurePOS 300 Series (481033H) последовательные порты
*	IC Book Labs:

	-	Dreadnought x16 Pro/Lite
	-	Ironclad x8 Pro
	-	Gunboat x4 Pro/Lite/Low Profile
	-	Gunboat x2 Low Profile

*	Kuroutoshikou SERIAL4P-LPPCI2
*	Lava Computers:

	-	Dual Serial PCI
	-	Quattro-PCIe
	-	Quattro-PCI
	-	Octopus-550 PCI

*	Moxa Technologies:

	-	Smartio CP-102E/PCIe
	-	Smartio CP-102EL/PCIe
	-	Smartio C104H/PCI
	-	Smartio CP-104UL/PCI
	-	Smartio CP-104JU/PCI
	-	Smartio CP-104EL/PCIe
	-	Smartio CP-104EL-A/PCIe
	-	CP-112UL PCI
	-	Industio CP-114
	-	Smartio CP-114EL/PCIe
	-	Smartio CP-118EL-A/PCIe
	-	C168H/PCI
	-	C168U/PCI
	-	CP-168EL/PCIe
	-	Smartio CP-168EL-A/PCIe

*	NetMos NM9815 Dual 1284 Printer port PCI
*	NetMos NM9835 2/1 port UART + 1284 Printer PCI
*	NetMos NM9845 4/6 port UART + 1284 Printer PCI
*	NetMos NM9865 4/3/2 port UART + 1/2 port 1284 Printer PCI
*	Платы на основе Oxford Semiconductor:

	-	OX16PCI952 UART (с параллельным портом и без)
	-	OX16PCI954 UART
	-	OX9160/OX16PCI954 UARTs
	-	OX16PCI958 UART

*	Perle Ultraport4 Express PCIe Serial
*	Perle Speed8/Speed4/Speed2 LE PCI Serial
*	Quatech:

	-	DSC-300/200/100 PCI
	-	DSCLP-300/200/100 PCI
	-	ESC-100/100D/100M PCI
	-	QSC-300/200/100 PCI
	-	QSCLP-100 PCI

*	Серии плат UART и параллельного порта SIIG Cyber:

	-	Cyber 2S и 2SP1 PCI 16550
	-	Cyber 4 и 4S PCI 16C650 (семейство 10x и семейство 20x)
	-	Cyber I/O PCI (семейство 10x и семейство 20x)
	-	Cyber Parallel Dual PCI (семейство 10x и семейство 20x)
	-	Cyber Serial Dual PCI (семейство 10x и семейство 20x)
	-	Cyber 2S1P PCI (семейство 10x и семейство 20x)
	-	PS8000 8S PCI 16C650 (семейство 20x)
	-	Quartet Serial 850 PCI

*	Sun 1040 PCI Quad Serial
*	Sunix MIO5xxxx 4/2/1 port UART и 1284 Printer
*	Sunix SUN1889/1888 PCI dual port serial
*	Sunix SER5xxxx 8/4/2 port serial
*	Syba Tech Ltd PCI-4S2P-550-ECP
*	Systembase SB16C1054/8 4/8 port serial
*	Titan PCI-800H/PCI-200H
*	VScom:

	-	PCIex-800H
	-	PCI-200HV2
	-	200Li uPCI
	-	PCI-800L, PCI-200L, и PCI-100L
	-	PCI-800, PCI-400, и PCI-200



Драйвер
**uark**
поддерживает следующие адаптеры:

*	HL USB-RS232
*	HugePine USB-UART
*	KQ-U8A Data Cable
*	Skymaster USB to RS232



Драйвер
**ubsa**
поддерживает следующие адаптеры:

*	AnyData ADU-500A EV-DO модем
*	AnyData ADU-E100A (без поддержки режима EV-DO)
*	Belkin F5U103
*	Belkin F5U120
*	e-Tek Labs Kwik232
*	GoHubs GoCOM232
*	Peracom однопортовый последовательный адаптер



Драйвер
**ubser**
обеспечивает поддержку последовательных адаптеров управления консолью BWCT.



Драйвер
**uchcom**
поддерживает следующие USB-контроллеры UART для последовательного интерфейса:

*	WinChipHead CH9102 (макс. 6 Мбит/с)
*	WinChipHead CH343 (макс. 6 Мбит/с)
*	WinChipHead CH341 (макс. 2 Мбит/с)
*	WinChipHead CH340 (макс. 2 Мбит/с)



Драйвер
**ucycom**
в настоящее время поддерживает следующие устройства, содержащие
мостовые микросхемы Cypress USB to RS232:

*	GPS-приемник DeLorme Earthmate USB



Драйвер
**uftdi**
поддерживает следующие USB-контроллеры UART для последовательного интерфейса:

*	FTDI FT4232H
*	FTDI FT232R
*	FTDI FT230X
*	FTDI FT2232H
*	FTDI FT2232D
*	FTDI FT2232C
*	FTDI FT8U232BM
*	FTDI FT8U232AM
*	FTDI FT8U100AX



Драйвер
**umcs**
тестировался на следующих адаптерах:

*	ST Lab U-360 двухпортовый последовательный USB-адаптер
*	ST Lab U-400 четырехпортовый последовательный USB-адаптер



Драйвер
**umct**
поддерживает следующие адаптеры:

*	Belkin F5U109
*	Belkin F5U409
*	D-Link DU-H3SP USB BAY Hub
*	Magic Control Technology USB-232
*	Sitecom USB-232




Драйвер
**uplcom**
поддерживает следующие устройства и адаптеры:

*	ADLINK ND-6530 USB-Serial Adapter
*	Телефон Alcatel One Touch 535/735
*	Alcor AU9720 USB-RS232 Serial Adapter
*	Модем AlDiga AL-11U
*	Модем Alltronix ACM003U00
*	Адаптер Anchor Serial
*	ATEN UC-232A
*	ATEN UC-232B
*	BAFO BF-800 и BF-810
*	Belkin F5U257
*	Телефон BenQ S81
*	Адаптер Corega CG-USBRS232R Serial
*	Дайв-компьютер Cressi Edy (Seiko)
*	Адаптер ELECOM UC-SGT Serial
*	ИК-пульт HAL Corporation Crossam2+USB IR commander
*	Адаптер Hama USB RS-232 Serial
*	Hamlet exaggerate XURS232
*	Дисплей HP LD220 Point-Of-Sale (POS)
*	IOGEAR UC-232A
*	I/O DATA USB-RSAQ, USB-RSAQ2, USB-RSAQ3 и USB-RSAQ5
*	Модем iTegno WM1080A GSM/GFPRS
*	Модем iTegno WM2080A CDMA
*	GPS Leadtek 9531
*	Модем Micromax 610U
*	Microsoft Palm 700WX
*	ИК-адаптер Mobile Action MA-620
*	Кабели Motorola
*	Кабель Nokia CA-42
*	Кабель OTI DKU-5
*	Панель Panasonic TY-TP50P6-S flat screen
*	Телефонный кабель PLX CA-42
*	PLANEX USB-RS232 URS-03
*	Универсальные USB-последовательные адаптеры Prolific
*	Универсальные USB-последовательные адаптеры Prolific (HXN)
*	USB-последовательный адаптер Prolific Pharos
*	Контроллер Prolific USB-Serial Controller D
*	RATOC REX-USB60
*	Кабель Radio Shack USB Serial Cable
*	Адаптер Sagem USB-Serial
*	Док-станция Samsung I330 Phone Cradle
*	Sandberg USB to Serial Link (модель 133-08)
*	Кабель Sanwa KB-USB2 для мультиметра
*	Мобильные телефоны Siemens/BenQ EF81, SX1, X65 и X75
*	Адаптер Sitecom USB-Serial
*	Адаптер SMART Technologies USB-Serial
*	Телефонный кабель Sony QN3
*	Sony Ericsson Datapilot
*	USB-кабели Sony Ericsson DCU-10 и DCU-11 (Susteen)
*	SOURCENEXT KeikaiDenwa 8 (с зарядным устройством и без)
*	Кабель Speed Dragon USB-Serial Cable
*	Сканер штрих-кода Syntech CPT-8001C
*	Адаптеры TDK UHA6400 и UPA9664 USB-PHS
*	Преобразователь TRENDnet USB to Serial Converter (TU-S9)
*	Адаптер Tripp-Lite U209-000-R USB-Serial
*	Считыватель магнитных карт UIC HCR331
*	Считыватель магнитных карт UIC MSR206
*	Терминал PHS Willcom W-SIM DD (WS002IN)
*	Адаптер YC-Cable USB-Serial
*	Дайв-компьютер Zeagle N2iTion3



Следующие устройства должны
работать с драйвером
**uslcom**:

*	Интерфейсы AC-Services CAN, CIS-IBUS, IBUS и OBD
*	Радио Aerocomm
*	Кабель AKTACOM ACE-1001
*	AMBER Wireless AMB2560
*	Адаптер Arkham DS-101
*	Argussoft ISP
*	Считыватель RFID Arygon Technologies Mifare
*	Интерфейс AVIT Research USB-TTL
*	Кабель данных B&G H3000
*	Считыватель Balluff RFID
*	Считыватель карт Baltech
*	Датчик BEI USB VCP
*	Burnside Telecom Desktop Mobile
*	Модуль chip45.com Crumb128
*	Продукты Clipsal 5000CT2, 5500PACA, 5500PCU, 560884, 5800PC, C5000CT2
	и L51xx C-Bus Home Automation
*	Модем Commander 2 EDGE(GSM)
*	Адаптер Cygnal Fasttrax GPS и Debug
*	Преобразователь DataApex MultiCOM USB to RS232
*	Адаптер Degree Controls USB
*	Усилитель DekTec DTA Plus VHF/UHF
*	GPS-приемник Dell DW700
*	Digianswer ZigBee/802.15.4 MAC
*	Комплекты разработки Dynastream ANT
*	Elan USBcount50, USBscope50, USBpulse100 и USBwave12
*	Интерфейс ELV USB-I2C
*	Контроллер EMS C1007 HF RFID
*	Интерфейсы Festo CPX-USB и CMSP
*	Бесконтактный считыватель карт Gemalto Prox-PU/CU
*	Helicomm IP-Link 1220-DVM
*	Адаптер IMS USB-RS422
*	Infinity GPS-MIC-1 Radio Monophone
*	Модем INSYS
*	Модемы IRZ SG-10 и MC35pu GSM/GPRS
*	Jablotron PC-60B
*	Интерфейсы Kamstrup M-Bus Master MultiPort 250D
	и Optical Eye/3 wire для счетчиков коммунальных услуг
*	GPS Kyocera
*	Link Instruments MS-019 и MS-028
	Осциллографы/логические анализаторы/генераторы паттернов
*	Lipowsky Baby-JTAG, Baby-LIN и HARP-1
*	Приемники наличных MEI CashFlow SC и Series 2000
*	Адаптер MJS USB-TOSLINK
*	Модемы MobiData GPRS USB
*	MSD DashHawk
*	Адаптер Multiplex RC
*	Термометр Optris MSpro LT
*	Преобразователь Owen AC4 USB-RS485
*	SIP-телефон Pirelli DP-L10
*	Телефонный кабель PLX CA-42
*	Pololu USB to Serial
*	Procyon AVS Mind Machine
*	Renesas RX-Stick для RX610
*	Кабель Siemens MC60
*	Универсальные чипы Silicon Laboratories CP2101/CP2102/CP2103/CP2104/CP2105
*	Software Bisque Paramount ME
*	SPORTident BSM7-D USB
*	Спортивный инструмент Suunto
*	Сканер штрих-кода Syntech CipherLab USB
*	SIP-телефон T-Com TC 300
*	Tams Master Easy Control
*	Telegesis ETRX2USB
*	Timewave HamLinkUSB
*	Считыватель Tracient RFID
*	Track Systems Traqmate
*	Кабель Vaisala USB Instrument
*	Контроллер VStabi
*	Сервисный кабель WAGO 750-923 USB
*	Глюкометр WaveSense Jazz Blood Glucose Meter
*	WIENER Plein & Baus CML Data Logger, RCM Remote,
	и блоки питания PL512 и MPOD
*	WMR RIGblaster Plug&Play и RIGtalk RT1
*	Zephyr Bioharness



Драйвер
**uvscom**
поддерживает следующие адаптеры:

*	DDI Pocket Air H" C@rd
*	DDI Pocket Air H" C@rd 64
*	NTT P-in
*	NTT P-in m@ster


[[sound]]
=== Звуковые устройства


Драйвер
**snd_als4000**
поддерживает следующие звуковые карты:

*	Avance Logic ALS4000



Драйвер
**snd_atiixp**
поддерживает следующие аудиочипсеты:

*	ATI IXP 200
*	ATI IXP 300
*	ATI IXP 400



Драйвер
**snd_cmi**
поддерживает следующие звуковые карты:

*	CMedia CMI8338A
*	CMedia CMI8338B
*	CMedia CMI8738
*	CMedia CMI8738B



Драйвер
**snd_cs4281**
поддерживает следующие звуковые карты:

*	Crystal Semiconductor CS4281



Драйвер
**snd_csa**
поддерживает следующие звуковые карты:

*	Crystal Semiconductor CS4280
*	Crystal Semiconductor CS4610
*	Crystal Semiconductor CS4611
*	Crystal Semiconductor CS4614
*	Crystal Semiconductor CS4615
*	Crystal Semiconductor CS4622
*	Crystal Semiconductor CS4624
*	Crystal Semiconductor CS4630
*	Genius Soundmaker 128 Value
*	Hercules Game Theatre XP
*	Turtle Beach Santa Cruz

Некоторые встроенные чипы CS4610
сопровождаются кодеком CS423x ISA
вместо кодека CS4297 AC97.
Такие конфигурации пока
не поддерживаются драйвером
**snd_csa**.



Драйвер
**snd_emu10k1**
поддерживает следующие звуковые карты:

*	Creative SoundBlaster Live! (чипсет EMU10K1)
*	Creative SoundBlaster Audigy (чипсет EMU10K2)
*	Creative SoundBlaster Audigy 2 (чипсет EMU10K2)
*	Creative SoundBlaster Audigy 2 (чипсет EMU10K3)



Драйвер
**snd_emu10kx**
поддерживает следующие звуковые карты:

*	Creative Sound Blaster Live! (чипсет EMU10K1).
	Доступны как PCM, так и MIDI интерфейсы.
*	Creative Sound Blaster Audigy (чипсеты CA0100 и CA0101).
	Доступны PCM и два MIDI интерфейса.
*	Creative Sound Blaster Audigy 2 и Creative Sound Blaster
	Audigy 4 (чипсет CA0102).
	Поддержка PCM ограничена стерео 48кГц/16 бит (часть чипсета
	192кГц/24 бит не поддерживается).
*	Creative Sound Blaster Audigy 2 Value (чипсет CA0108).
	Поддержка PCM ограничена
	стерео 48кГц/16 бит (часть чипсета 192кГц/24 бит не поддерживается).
	Для этой карты нет поддержки MIDI.

Драйвер
**snd_emu10kx**
*не*
поддерживает следующие звуковые карты
(хотя их названия
похожи на некоторые поддерживаемые):

*	Creative Sound Blaster Live! 24-Bit, идентифицируемая
	FreeBSD
	как
	"`emu10k1x Soundblaster Live! 5.1`".
*	Creative Sound Blaster Audigy LS / ES, идентифицируемая
	FreeBSD
	как
	"`CA0106-DAT Audigy LS`".
*	Все другие звуковые карты Creative с чипсетами -DAT.
*	Все звуковые карты серии Creative X-Fi.



Драйвер
**snd_envy24**
поддерживает следующие аудиоустройства:

*	M-Audio Audiophile 2496
*	M-Audio Delta Dio 2496
*	Terratec DMX 6fire

Поддерживается только аналоговое воспроизведение.
Запись и другие функции этих карт не поддерживаются.



Драйвер
**snd_envy24ht**
поддерживает следующие аудиоустройства:

*	Audiotrak Prodigy 7.1
*	Audiotrak Prodigy 7.1 LT
*	Audiotrak Prodigy 7.1 XT
*	Audiotrak Prodigy HD2
*	ESI Juli@
*	ESI Juli@ XTe
*	M-Audio Audiophile 192
*	M-Audio Revolution 5.1
*	M-Audio Revolution 7.1
*	Terratec Aureon 5.1 Sky
*	Terratec Aureon 7.1 Space
*	Terratec Aureon 7.1 Universe
*	Terratec PHASE 22
*	Terratec PHASE 28

Поддерживается только аналоговое воспроизведение.
Запись и другие функции этих карт не поддерживаются.



Драйвер
**snd_es137x**
поддерживает следующие звуковые карты:

*	Creative CT5880-A
*	Creative CT5880-C
*	Creative CT5880-D
*	Creative CT5880-E
*	Creative SB AudioPCI CT4730
*	Ensoniq AudioPCI ES1370
*	Ensoniq AudioPCI ES1371-A
*	Ensoniq AudioPCI ES1371-B
*	Ensoniq AudioPCI ES1373-A
*	Ensoniq AudioPCI ES1373-B
*	Ensoniq AudioPCI ES1373-8



Драйвер
**snd_fm801**
поддерживает аудиоустройства на основе следующего чипсета:

*	Forte Media FM801



Драйвер
**snd_hda**
поддерживает аудиоконтроллеры и кодеки PCI класса 04h
(мультимедиа),
подкласса 03h
(HDA)
совместимые со спецификацией
Intel High Definition Audio 1.0.



Драйвер
**snd_hdspe**
поддерживает следующие аудиоустройства:

*	RME HDSPe AIO (опциональные платы расширения AO4S-192 и AI4S-192)
*	RME HDSPe RayDAT

По умолчанию каждое устройство
pcm(4)
соответствует физическому порту на звуковой карте.
Для портов ADAT поддерживаются форматы на 8, 4 и 2 канала.
Эффективное количество каналов ADAT составляет 8 каналов при одинарной скорости
(32кГц-48кГц), 4 канала при двойной скорости (64кГц-96кГц) и 2 канала при
четверной скорости (128кГц-192кГц).
В зависимости от выбранной частоты дискретизации и формата каналов, не все каналы pcm могут
быть сопоставлены с каналами ADAT и наоборот.



Драйвер
**snd_ich**
поддерживает следующие аудиоустройства:

*	AMD 768
*	AMD 8111
*	Intel 443MX
*	Intel ICH
*	Intel ICH ревизия 1
*	Intel ICH2
*	Intel ICH3
*	Intel ICH4
*	Intel ICH5
*	Intel ICH6
*	Intel ICH7
*	NVIDIA nForce
*	NVIDIA nForce2
*	NVIDIA nForce2 400
*	NVIDIA nForce3
*	NVIDIA nForce3 250
*	NVIDIA nForce4
*	SiS 7012



Драйвер
**snd_maestro3**
поддерживает следующие аудиоустройства:

*	ESS Technology Allegro-1
*	ESS Technology Maestro3



Драйвер
**snd_neomagic**
поддерживает следующие аудиоустройства:

*	NeoMagic 256AV
*	NeoMagic 256ZX



Драйвер
**snd_solo**
поддерживает следующие звуковые карты:

*	ESS Solo-1 (чипсет ES1938)
*	ESS Solo-1E (чипсет ES1946)



Драйвер
**snd_spicds**
поддерживает следующие кодеки:

*	AK4358
*	AK4381
*	AK4396
*	AK4524
*	AK4528
*	WM8770




Драйвер
**snd_t4dwave**
поддерживает следующие аудиоустройства:

*	Acer Labs M5451
*	SIS 7018
*	Trident 4DWave DX
*	Trident 4DWave NX


Драйвер
**snd_uaudio**
обеспечивает поддержку устройств USB audio class и
устройств USB MIDI class.



Драйвер
**snd_via8233**
поддерживает следующие аудиочипсеты:

*	VIA VT8233
*	VIA VT8233A
*	VIA VT8233C
*	VIA VT8235
*	VIA VT8237
*	VIA VT8251



Драйвер
**snd_via82c686**
поддерживает аудиоустройства на основе следующего чипсета:

*	VIA 82C686A



Драйвер
**snd_vibes**
поддерживает аудиоустройства на основе следующего чипсета:

*	S3 SonicVibes


[[usb]]
=== USB-устройства

Поддерживается ряд USB-периферийных устройств; известные рабочие устройства перечислены в этом разделе.
Благодаря универсальной природе большинства USB-устройств, за некоторыми исключениями, любое устройство данного класса будет поддерживаться, даже если оно явно не указано здесь.

[NOTE]
====
Адаптеры USB Bluetooth можно найти в разделе <<bluetooth,Bluetooth>>.

USB-устройства интерфейса пользователя можно найти в разделе <<misc,Прочие устройства>>.

USB-сетевые интерфейсы можно найти в разделах <<ethernet,Сетевые интерфейсы Ethernet>> или <<wlan,Беспроводные сетевые интерфейсы>>.

USB-последовательные интерфейсы можно найти в разделе <<serial,Последовательные интерфейсы>>.
====


Драйвер
**atp**
обеспечивает поддержку следующих Product ID:

*	PowerBooks, iBooks (ID: 0x020e, 0x020f, 0x0210, 0x0214, 0x0215, 0x0216)
*	Core Duo MacBook & MacBook Pro (ID: 0x0217, 0x0218, 0x0219)
*	Core2 Duo MacBook & MacBook Pro (ID: 0x021a, 0x021b, 0x021c)
*	Core2 Duo MacBook3,1 (ID: 0x0229, 0x022a, 0x022b)
*	12-дюймовые PowerBook и iBook (ID: 0x030a, 0x030b)
*	15-дюймовые PowerBook (ID: 0x020e, 0x020f, 0x0215)
*	17-дюймовые PowerBook (ID: 0x020d)
*	Почти все последние Macbook-Pro и Air (ID: 0x0223, 0x0223, 0x0224, 0x0224,
	0x0225, 0x0225, 0x0230, 0x0230, 0x0231, 0x0231, 0x0232, 0x0232, 0x0236,
	0x0236, 0x0237, 0x0237, 0x0238, 0x0238, 0x023f, 0x023f, 0x0240, 0x0241,
	0x0242, 0x0243, 0x0244, 0x0245, 0x0246, 0x0247, 0x0249, 0x024a, 0x024b,
	0x024c, 0x024d, 0x024e, 0x0252, 0x0252, 0x0253, 0x0253, 0x0254, 0x0254,
	0x0259, 0x025a, 0x025b, 0x0262, 0x0262, 0x0263, 0x0264, 0x0290, 0x0291,
	0x0292)



Драйвер
**atopcase**
поддерживает следующие MacBooks, выпущенные в 2015-2018 годах:

*	Macbook8,1
*	Macbook9,1
*	Macbook10,1
*	MacbookPro11,4
*	MacbookPro12,1
*	MacbookPro13,1
*	MacbookPro13,2
*	MacbookPro13,3
*	MacbookPro14,1
*	MacbookPro14,2
*	MacbookPro14,3



Драйвер
**abtn**
поддерживает расширенные клавиши клавиатуры (специальные F-клавиши) на следующих устройствах:

*	Клавиатура Apple iBook
*	Клавиатура Apple PowerBook



Устройства, поддерживаемые драйвером
**akbd**
, включают:

*	Apple Extended Keyboard
*	Apple Keyboard II
*	Клавиатура Apple iBook
*	Клавиатура Apple PowerBook



Устройства, поддерживаемые драйвером
**ams**
, включают:

*	Apple Mouse
*	ADB Extended Mouse
*	MacAlly 2-Button Mouse
*	Трекпад Apple iBook
*	Трекпад Apple PowerBook


Драйвер man:ehci[4] поддерживает USB 2.0 контроллеры, реализующие стандарт Enhanced Host Controller Interface.


Драйвер
**ohci**
поддерживает все OHCI v1.0 совместимые контроллеры, включая:

*	AcerLabs M5237 (Aladdin-V)
*	AMD-756
*	OPTi 82C861 (FireLink)
*	NEC uPD 9210
*	CMD Tech 670 (USB0670)
*	CMD Tech 673 (USB0673)
*	NVIDIA nForce3



Следующие устройства
поддерживаются драйвером
**ugold**:

*	RDing TEMPer1V1.2



Драйвер
**uhci**
поддерживает все UHCI v1.1 совместимые контроллеры, включая:

*	Intel 82371AB/EB (PIIX4)
*	Intel 82371SB (PIIX3)
*	VIA 83C572



Драйвер
**uipaq**
поддерживает следующие устройства iPAQ:

*	КПК ASUS P535
*	КПК Casio BE-300
*	Compaq IPaq PocketPC
*	HP Jornada 568
*	HP iPAQ 22xx/Jornada 548
*	Модем HTC PPC6700
*	Смартфон HTC
*	HTC Winmobile
*	Телефон Sharp W-ZERO3 ES Spart
*	Большинство телефонов на основе Windows CE



Драйвер
**umass**
поддерживает устройства USB Mass Storage, такие как:

*	USB-флешки
*	USB-жесткие диски
*	USB-флоппи-дисководы



Следующие устройства
поддерживаются драйвером
**urio**:

*	Diamond MultiMedia Rio 500
*	Diamond MultiMedia Rio 600
*	Diamond MultiMedia Rio 800



Устройства, поддерживаемые драйвером
**umodem**
, включают:

*	3Com 5605
*	Беспроводной модем Curitel PC5740
*	Мобильный телефон Kyocera AH-K3001V (WILLCOM)
*	Мобильный телефон Kyocera WX320K (WILLCOM)
*	Беспроводной модем Metricom Ricochet GS USB
*	Беспроводной модем Sierra MC5720
*	Беспроводной маршрутизатор Yamaha Broadband RTW65b
*	Модем ELSA MicroLink 56k USB
*	Телефон Sony Ericsson W810i
*	Sonim XP5300 Force



Драйвер
**rtsx**
поддерживает следующие кард-ридеры Realtek SD:

*	RTS5209
*	RTS5227
*	RTS5229
*	RTS522A
*	RTS525A
*	RTS5260
*	RTL8411B
*	RTS5249 (не проверено)
*	RTL8402 (не проверено)
*	RTL8411 (не проверено)



Драйвер
**ulpt**
обеспечивает поддержку USB-принтеров и кабелей преобразования
параллельного принтера, включая следующие:

*	Адаптер параллельного принтера ATen
*	Адаптер параллельного принтера Belkin F5U002
*	Canon BJ F850, S600
*	Canon LBP-1310, 350
*	Адаптер USB-to-parallel printer Entrega


Драйвер
**umct**
поддерживает следующие адаптеры:

*	Belkin F5U109
*	Belkin F5U409
*	D-Link DU-H3SP USB BAY Hub
*	Magic Control Technology USB-232
*	Sitecom USB-232



Драйвер
**uvisor**
поддерживает следующие устройства:

*	Aceeca Mez1000 RDA
*	Handspring Treo
*	Handspring Treo 600
*	Handspring Visor
*	Palm I705
*	Palm M125
*	Palm M130
*	Palm M500
*	Palm M505
*	Palm M515
*	Palm Tungsten T
*	Palm Tungsten Z
*	Palm Zire
*	Palm Zire 31
*	Sony Clie 4.0
*	Sony Clie 4.1
*	Sony Clie 5.0
*	Sony Clie PEG-S500C
*	Sony Clie NX60
*	Sony Clie S360
*	Sony Clie TJ37



Драйвер
**xhci**
поддерживает
`XHCI`
совместимые контроллеры с PCI классом 12 (последовательная шина),
подклассом 3 (USB) и интерфейсом программирования 48 (XHCI).


[[firewire]]
=== Устройства IEEE 1394 (Firewire)


Драйвер
**fwohci**
обеспечивает поддержку карт интерфейса FireWire PCI/CardBus.
Драйвер поддерживает следующие чипсеты IEEE 1394 OHCI:

*	Adaptec AHA-894x/AIC-5800
*	Apple Pangea
*	Apple UniNorth
*	Intel 82372FB
*	IOGEAR GUF320
*	Lucent / Agere FW322/323
*	NEC uPD72861
*	NEC uPD72870
*	NEC uPD72871/2
*	NEC uPD72873
*	NEC uPD72874
*	National Semiconductor CS4210
*	Ricoh R5C551
*	Ricoh R5C552
*	Sony CX3022
*	Sony i.LINK (CXD3222)
*	Texas Instruments PCI4410A
*	Texas Instruments PCI4450
*	Texas Instruments PCI4451
*	Texas Instruments TSB12LV22
*	Texas Instruments TSB12LV23
*	Texas Instruments TSB12LV26
*	Texas Instruments TSB43AA22
*	Texas Instruments TSB43AB21/A/AI/A-EP
*	Texas Instruments TSB43AB22/A
*	Texas Instruments TSB43AB23
*	Texas Instruments TSB82AA2
*	VIA Fire II (VT6306)



Драйвер
**sbp**
поддерживает устройства хранения данных
FireWire Serial Bus Protocol 2
(SBP-2).


[[bluetooth]]
=== Устройства Bluetooth


Драйвер
**ng_ubt**
поддерживает все USB-устройства Bluetooth, соответствующие
спецификации Bluetooth v1.1, включая:

*	3Com 3CREB96
*	AIPTEK BR0R02
*	EPoX BT-DG02
*	Адаптер Bluetooth Mitsumi
*	MSI MS-6967
*	Адаптер Bluetooth TDK
*	Адаптер Bluetooth Broadcom


[[crypto-accel]]
=== Криптографические ускорители

Драйвер man:aesni[4] поддерживает функции AES и SHA процессоров x86.

Драйвер man:armv8crypto[4] поддерживает функции AES, SHA-1, SHA-2 и арифметические механизмы конечных полей в процессорах, реализующих ARMv8 Cryptograpic Extension.

Драйвер **ccp** поддерживает криптографический сопроцессор AMD Platform Security Processor (PSP), найденный в устройствах AMD Ryzen.


Драйвер
**ccr**
поддерживает механизм криптографического ускорения, встроенный в адаптеры
на основе ASIC T6:

*	Chelsio T6225-CR
*	Chelsio T6225-SO-CR
*	Chelsio T62100-LP-CR
*	Chelsio T62100-SO-CR
*	Chelsio T62100-CR


Драйвер man:glxsb[4] поддерживает блок безопасности, найденный в устройствах AMD Geode LX.


Драйвер
**hifn**
поддерживает различные карты,
содержащие чипсеты Hifn 7751, 7951,
7811, 7955 и 7956, такие как:

Invertex AEON

> Больше не производится.
> Поставлялась в моделях с 128 КБ SRAM или 2 МБ DRAM.

Hifn 7751

> Референсная плата с 512 КБ SRAM.

PowerCrypt

> Поставляется с 512 КБ SRAM.

XL-Crypt

> Единственная плата на основе 7811 (которая быстрее 7751 и имеет
> генератор случайных чисел).

NetSec 7751

> Поддерживает наибольшее количество IPsec-сессий, с 1 МБ SRAM.

Soekris Engineering vpn1201 и vpn1211

> См.
> *http://www.soekris.com/*.
> Содержит 7951 и поддерживает симметричные операции и операции со случайными числами.

Soekris Engineering vpn1401 и vpn1411

> См.
> *http://www.soekris.com/*.
> Содержит 7955 и поддерживает симметричные операции и операции со случайными числами.


Драйвер man:padlock[4] поддерживает механизмы AES/RNG/RSA/SHA-1 и SHA-2, найденные в устройствах Via Technologies C7, C3 и Eden.


Драйвер
**qat**
поддерживает следующие механизмы Intel QuickAssist Technology:

*	Чипсет Intel (R) C62x
*	Семейство процессоров Intel (R) Atom C3000
*	Адаптер Intel (R) QuickAssist Adapter 8960/Адаптер Intel (R) QuickAssist Adapter 8970
	(ранее известный как "Lewis Hill")
*	Серия Intel (R) Communications Chipset 8925 to 8955
*	Семейство процессоров Intel (R) Atom P5300
*	Серия Intel (R) QAT 4xxx


Драйвер man:qat_c2xxx[4] поддерживает механизм Intel QuickAssist Technology, найденный в устройствах Atom C2000.


Драйвер
**safe**
поддерживает следующие чипы SafeXcel:

	SafeNet 1141    Оригинальный чипсет.
	Поддерживает симметричные криптооперации
	DES, Triple-DES, AES, MD5 и SHA-1,
	RNG, операции с открытым ключом и полную обработку IPsec-пакетов.
	SafeNet 1741    Более быстрая версия 1141.



Драйвер
**safexcel**
поддерживает функции криптографического ускорения устройства
Inside Secure EIP-97, найденного в некоторых системах-на-кристалле Marvell.


[[misc]]
=== Прочие устройства

Клавиатуры, включая:

* Клавиатуры HID (драйвер man:hkbd[4]) через USB, I2C или Apple SPI
* USB-клавиатуры (драйвер man:ukbd[4])
* Клавиатуры PS/2 (драйвер man:atkbd[4])
* Клавиатуры ADB (драйвер man:akbd[4])
* Клавиатуры в стиле AT (драйвер man:atkbd[4])
* Клавиатуры Hyper-v (драйвер **hv_kbd**)

Указывающие устройства, включая:

* Мыши HID (драйвер man:hms[4]) и сенсорные устройства (драйвер man:hmt[4])
через USB, I2C, Hyper-V или Apple SPI
* USB-мыши (драйвер man:ums[4]) и сенсорные устройства (драйвер man:wmt[4])
* Трекпады ноутбуков Apple (драйверы man:wsp[4] или man:apt[4])
* Сенсорные панели Elantech I2C (драйвер man:ietp[4])
* Сенсорные панели Chromebook Cypress APA I2C (драйвер man:cyapa[4])
* Мыши PS/2 и совместимые устройства,
включая многие указывающие устройства ноутбуков (драйвер man:psm[4])
* Мыши ADB и сенсорные устройства (драйвер man:ams[4])
* Последовательные мыши и совместимые устройства

[NOTE]
====
man:moused[8] содержит дополнительную информацию об использовании традиционных указывающих устройств с консолью FreeBSD.
====


Драйвер
**hgame**
поддерживает геймпады, джойстики и контроллеры HID, такие как:

*	8bitdo USB Wireless Adapter 2


[amd64, i386] Дисководы гибких дисков (драйвер man:fdc[4])

[amd64, i386] Видеокарты, совместимые с VGA (драйвер man:vga[4])

[NOTE]
====
Информацию о конкретных видеокартах и совместимости с Xorg можно найти на link:http://www.x.org/[http://www.x.org/].
====

[amd64, i386] Параллельные порты "стандарта PC" (драйвер man:ppc[4])


Драйвер
**ads111x**
обеспечивает поддержку следующих устройств:

	ADS1013     ADS1113
	ADS1014     ADS1114
	ADS1015     ADS1115



Драйвер
**amdsbwd**
поддерживает следующие чипсеты:

*	Южные мосты AMD SB600/7x0/8x0/9x0
*	Контроллеры концентраторов AMD Axx/Hudson/Bolton FCH
*	Контроллеры концентраторов FCH, интегрированные в процессоры Family 15h Models 60h-6Fh, 70h-7Fh
*	Контроллеры концентраторов FCH, интегрированные в процессоры Family 16h Models 00h-0Fh, 30h-3Fh



Драйвер
**at45d**
обеспечивает поддержку следующих устройств:

*	AT45DB011B
*	AT45DB021B
*	AT45DB041x
*	AT45DB081B
*	AT45DB161x
*	AT45DB321x
*	AT45DB321x
*	AT45DB641E
*	AT45DB642x



Драйвер
**gpioths**
обеспечивает поддержку следующих устройств:

	DHT11       DHT12
	DHT21       DHT22
	AM3201      AM3202

Поддерживаемые устройства похожи друг на друга, различаясь
в основном точностью и разрешением.
Устройства требуют одного провода для передачи данных, используя
пользовательский протокол, несовместимый с 1-wire(tm) от Maxim.
Устройства AM320x также поддерживают подключение к шине i2c,
но этот драйвер поддерживает только опцию подключения с одним проводом.



**ig4**
поддерживает контроллеры I2C на основе IP Synopsys DesignWare, которые можно найти
в процессорах Intel(R) Core(TM), начиная с четвертого поколения, в семействах
систем-на-кристалле Intel(R) Bay Trail, Apollo Lake и некоторых системах AMD.



Драйвер
**intpm**
поддерживает следующие чипсеты:

*	Intel 82371AB/82443MX
*	ATI IXP400
*	Южные мосты AMD SB600/7x0/8x0/9x0
*	Контроллеры концентраторов AMD Axx/Hudson/Bolton FCH
*	Контроллер концентратора FCH, интегрированный в процессоры Family 15h Models 60h-6Fh, 70h-7Fh
*	Контроллер концентратора FCH, интегрированный в процессоры Family 16h Models 00h-0Fh, 30h-3Fh



Драйвер
**mx25l**
поддерживает следующие устройства flash-памяти SPI:

*	AT25DF641
*	EN25F32
*	EN25P32
*	EN25P64
*	EN25Q32
*	EN25Q64
*	GD25Q64
*	M25P32
*	M25P64
*	MX25L1606E
*	MX25LL128
*	MX25LL256
*	MX25LL32
*	MX25LL64
*	N25Q64
*	S25FL032
*	S25FL064
*	S25FL128
*	S25FL256S
*	SST25VF010A
*	SST25VF032B
*	W25Q128
*	W25Q256
*	W25Q32
*	W25Q64
*	W25Q64BV
*	W25X32
*	W25X64



Текущая версия драйвера
**netfpga10g_nf10bmac**
работает с одним интерфейсом режима PIO
ядра NetFPGA-10G Embedded CPU Ethernet версии 1.00a.



Следующие чипы PLX/Avago/Broadcom
поддерживаются драйвером
**ntb_hw_plx**:

*	PEX 8713
*	PEX 8717
*	PEX 8725
*	PEX 8733
*	PEX 8749

, но он также может работать с другими совместимыми чипами.



Драйвер
**ow_temp**
поддерживает следующие датчики температуры:

	DS1820     1-Wire Digital Thermometer
	DS18S20    High-Precision 1-Wire Digital Thermometer
	DS18B20    Programmable Resolution 1-Wire Digital Thermometer
	DS1822     Econo 1-Wire Digital Thermometer
	DS1825     Programmable Resolution 1-Wire Digital Thermometer with 4-bit ID
	MAX31820   1-Wire, Parasite-Power, Ambient Temperature Sensor

Драйвер поддерживает семейства кодов 0x10, 0x22, 0x28 и 0x3b.



Драйвер
**superio**
поддерживает множество контроллеров Super I/O, производимых Nuvoton
(ранее известными как Winbond) и ITE, а именно:

*	Fintek F81803
*	Fintek F81865
*	Nuvoton NCT5104D/NCT6102D/NCT6106D рев. A и B+
*	Nuvoton NCT5585D
*	Nuvoton NCT6116D
*	Nuvoton NCT6775
*	Nuvoton NCT6776
*	Nuvoton NCT6779
*	Nuvoton NCT6791
*	Nuvoton NCT6792
*	Nuvoton NCT6793
*	Nuvoton NCT6795
*	Nuvoton NCT6796D-E
*	Winbond 83627HF/F/HG/G/S/THF/EHF/DHG/UHG/DHG-P
*	Winbond 83637HF
*	Winbond 83667HG/HG-B
*	Winbond 83687THF
*	Winbond 83697HF/UG



Драйвер
**u2f**
поддерживает USB-ключи безопасности, совместимые со стандартом FIDO/U2F.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (14.11.2025): def336c22c1ac5d8771ecd6727d8d170d36470a4
//
