---
title: "FreeBSD 2.1.6 Announcement"
sidenav: download
--- 

= FreeBSD 2.1.6 Announcement

Please read an link:../security/[important security announcement] regarding FreeBSD 2.1.6

FreeBSD 2.1.6 is now available in:

____
link:../security[ftp://ftp.FreeBSD.org/pub/FreeBSD/2.1.6-RELEASE]
____

And shortly from its various mirror sites, a list of which may be obtained from: http://www.FreeBSD.org/handbook/mirrors.html

This release will also be available on CDROM from http://www.cdrom.com/[Walnut Creek CDROM], hopefully shipping within the next 4-6 weeks.

Those puzzled by the near-simultaneous release of 2.1.6 and 2.2 need also look no further than http://www.FreeBSD.org/branch.html for the reasons behind this release schedule. CDROM subscription customers should also see this page for information on Walnut Creek CDROM's plans for these releases.

If you are a commercial user of FreeBSD who would like to take advantage of recent bug fixes without making the jump to our more ambitious 2.2 release (or delay that jump until 2.2 has had more time to mature), or if you're simply looking for the lowest-impact upgrade from 2.1.5, then 2.1.6-RELEASE is for you.

link:../../[Release Home]
