# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	CONTRIB.386BSD CONTRIB.FreeBSD COPYRIGHT.386BSD COPYRIGHT.FreeBSD
DATA+=	MIRROR.SITES PERSONAL.ACKS RELNOTES.FreeBSD SUPPORT.TXT

.include "${WEB_PREFIX}/share/mk/web.site.mk"
