# ACPI project page
#
# $FreeBSD: www/en/projects/acpi/Makefile,v 1.1 2004/04/18 20:34:26 marks Exp $

MAINTAINER=	marks

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
DOCS+=	completed.sgml
DATA=	style.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
