---
title: "Коммерческие поставщики"
sidenav: support
---

= Коммерческие поставщики

Мощь, гибкость и удобство FreeBSD привлекает широкий круг пользователей и поставщиков.
Ниже располагается список поставщиков, предлагающих коммерческие продукты, сервисы, и/или консультации по FreeBSD.

* link:consult_bycat[Консалтинговые услуги] Вне зависимости от того, являетесь вы начинающим пользователем FreeBSD или вам нужно завершить большой проект, наёмный консультант может помочь.
Вы можете просмотреть список link:consult[в алфавитном порядке] или разбитым по link:consult_bycat[категориям].
* link:hardware[Аппаратное обеспечение] Вам нужно специализированное оборудование, ищете новый настольный компьютер, или хотите поставить в стойку сервера с предустановленной FreeBSD?
У этих компаний может быть то, что вам нужно!
* link:isp[Интернет провайдеры] Если вам нужно веб-пространство на системе FreeBSD или вы хотите подключить свою компанию к интернету, эти компании могут предложить вам то, что нужно!
* link:misc[Различные поставщики] Книги и аксессуары, без которых вы просто жить не можете!
* link:software_bycat[Программное обеспечение] В FreeBSD имеется широкий спектр качественного программного обеспечения, от аудиоплееров и драйверов сетевых адаптеров до коммерческих баз данных.
Вы можете просмотреть список link:software[в алфавитном порядке] или разбитым по link:software_bycat[категориям].

Если Ваша компания поддерживает продукт для FreeBSD, сервис, дает консультации, или осуществляет техническую поддержку, информация о которых должна быть внесена на эту страницу, пожалуйста заполните link:../support/bugreports/[форму в сообщениях о проблеме] с категорией Documentation->Website.
В сообщение должен параграф средней длины, описывающий вашу компанию.
Пожалуйста, имейте ввиду, что включение поставщиков в наш список не означает поддержку их продуктов или сервисов проектом FreeBSD.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (02.08.2023): ac03e7f788f8b73e36bf1fda4695bf0ab200d79d
//
