---
title: "Консалтинговые услуги"
sidenav: support
vendor: consult
grouped: false
---

Мощь, гибкость и надежность FreeBSD привлекают широкий круг пользователей и поставщиков.
Здесь вы найдете компании, предлагающие коммерческие продукты и/или услуги для FreeBSD.

Для вашего удобства мы разделили наш растущий коммерческий список на несколько разделов.
Если Ваша компания поддерживает продукт для FreeBSD, сервис, дает консультации, или осуществляет техническую поддержку, информация о которых должна быть внесена на эту страницу, пожалуйста заполните link:../../support/bugreports/[форформу в сообщениях о проблемему] с категорией Documentation->Website.
В сообщение должен параграф средней длины, описывающий вашу компанию.
Пожалуйста, имейте ввиду, что включение поставщиков в наш список не означает поддержку их продуктов или сервисов проектом FreeBSD.

== Консалтинговые услуги

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (02.08.2023): 816926c6780817942f743be770fbfceb7534645d
//
