---
title: Chapitre 10. Compatibilité binaire avec Linux®
part: Partie II. Tâches courantes
prev: books/handbook/printing
next: books/handbook/partiii
---

[[linuxemu]]
= Compatibilité binaire avec Linux(R)
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Table des matières
:table-caption: Tableau
:example-caption: Exemple
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 10

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/linuxemu/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/linuxemu/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/linuxemu/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/fr/mailing-lists.adoc[]
include::shared/fr/teams.adoc[]
include::shared/fr/urls.adoc[]

toc::[]

[[linuxemu-synopsis]]
== Synopsis

FreeBSD fournit une compatibilité binaire avec Linux(R), permettant aux utilisateurs d'installer et d'exécuter la plupart des applications Linux(R) sur un système FreeBSD sans avoir à modifier ces applications. On rapporte également que dans certaines situations, les binaires Linux sont plus performants sous FreeBSD que sous Linux(R),.

Il existe cependant certaines caractéristiques spécifiques à Linux(R), qui ne sont pas supportées sous FreeBSD. Par exemple, des binaires Linux(R) ne fonctionneront pas sous FreeBSD s'ils utilisent massivement des appels i386(TM) spécifiques, comme activation du mode virtuel 8086.

[NOTE]
====
Le support de la compatibilité Linux(R) pour les binaires 64bits a été ajouté avec FreeBSD 10.3.
====

Après la lecture de ce chapitre, vous connaîtrez:

* Comment activer la compatibilité binaire avec Linux(R) sur un système FreeBSD.
* Comment installer des bibliothèques partagées Linux(R) supplémentaires.
* Comment installer des application Linux(R) sur un système FreeBSD.
* Les détails de l'implémentation de la compatibilité Linux(R) sous FreeBSD.

Avant de lire ce chapitre, vous devrez:

* Savoir comment installer des crossref:ports[ports,logiciels tiers].

[[linuxemu-lbc-install]]
== Configurer la compatibilité binaire avec Linux(R)

Par défaut, les bibliothèques Linux(R) ne sont pas installées et la compatibilité binaire avec Linux n'est pas activée. Les bibliothèques Linux(R) peuvent être installées soit manuellement soit à partir du catalogue des logiciels portés.

Avant de tenter de compiler un logiciel, charger le module du noyau Linux(R), sinon la compilation risque d'échouer:

[source,bash]
....
# kldload linux
....

Pour une compatibilité en 64bits:

[source,bash]
....
# kldload linux64
....

Pour vérifier que le module est bien chargé:

[source,bash]
....
% kldstat
      Id Refs Address    Size     Name
      1    2 0xc0100000 16bdb8   kernel
      7    1 0xc24db000 d000     linux.ko
....

Le logiciel précompilé package:emulators/linux_base-c7[] ou la version compilée à partir du catalogue des logiciels portés est la méthode la plus simple pour installer l'ensemble des bibliothèques et binaires de base Linux(R) sur un système FreeBSD. Pour installer le logiciel porté:

[source,bash]
....
# pkg install emulators/linux_base-c7
....

Pour activer au démarrage la compatibilité Linux(R), ajouter ligne suivante au fichier [.filename]#/etc/rc.conf#:

[.programlisting]
....
linux_enable="YES"
....

Sur les machines 64bits, [.filename]#/etc/rc.d/abi# chargera automatiquement le module pour l'émulation 64bits.

Depuis qu'à été ajouté le support pour l'exécution des binaires Linux(R) 32 et 64 bits à la couche de compatibilité Linux(R) (sur les hôtes 64 bits de type x86), il n'est plus possible d'ajouter l'émulation en statique dans un noyau personnalisé.

[[linuxemu-libs-manually]]
=== Installer des bibliothèques supplémentaires à la main

Si une application Linux(R) se plaint de l'absence d'une bibliothèque partagée après avoir configuré la compatibilité binaire Linux(R), déterminez quelle est la bibliothèque partagée nécessaire au binaire Linux(R) et installez-la à la main.

A partir d'un système Linux(R), la commande `ldd` peut être utilisée pour déterminer quelles sont les bibliothèques partagées dont l'application a besoin. Par exemple, pour contrôler quelles bibliothèques partagées sont nécessaires à `linuxdoom`, exécuter cette commande à partir d'un système Linux(R) où est installé Doom:

[source,bash]
....
% ldd linuxdoom
libXt.so.3 (DLL Jump 3.1) => /usr/X11/lib/libXt.so.3.1.0
libX11.so.3 (DLL Jump 3.1) => /usr/X11/lib/libX11.so.3.1.0
libc.so.4 (DLL Jump 4.5pl26) => /lib/libc.so.4.6.29
....

Ensuite, copier tous les fichiers mentionnés dans la dernière colonne, du système sous Linux(R) vers [.filename]#/compat/linux# sur le système FreeBSD. Une fois copiés, créer les liens symboliques vers les noms de fichiers donnés dans la première colonne. Cet exemple donnera lieu aux fichiers suivants sur le système FreeBSD:

[source,bash]
....
/compat/linux/usr/X11/lib/libXt.so.3.1.0
/compat/linux/usr/X11/lib/libXt.so.3 -> libXt.so.3.1.0
/compat/linux/usr/X11/lib/libX11.so.3.1.0
/compat/linux/usr/X11/lib/libX11.so.3 -> libX11.so.3.1.0
/compat/linux/lib/libc.so.4.6.29
/compat/linux/lib/libc.so.4 -> libc.so.4.6.29
....

Si une bibliothèque Linux(R) partagée existe avec le même numéro de version majeure que celle indiquée par la première colonne du résultat de la commande `ldd`, il est inutile de la copier vers le nom de fichier donné par la dernière colonne, la bibliothèque déjà existante devrait fonctionner. Il est cependant recommandé de copier malgré tout la bibliothèque partagée si c'est une version récente. L'ancienne version peut être supprimée, du moment que le lien symbolique pointe sur la nouvelle.

Par exemple, les bibliothèques suivantes existent déjà sur le système FreeBSD:

[source,bash]
....
/compat/linux/lib/libc.so.4.6.27
/compat/linux/lib/libc.so.4 -> libc.so.4.6.27
....

et `ldd` indique qu'un binaire a besoin d'une version plus récente:

[source,bash]
....
libc.so.4 (DLL Jump 4.5pl26) -> libc.so.4.6.29
....

Etant donné que la bibliothèque existante n'a qu'une ou deux versions de retard sur le dernier digit, le programme devrait fonctionner avec la version légèrement plus ancienne. Il est, néanmoins, plus sûr de remplacer la [.filename]#libc.so# existante avec la version plus récente:

[source,bash]
....
/compat/linux/lib/libc.so.4.6.29
/compat/linux/lib/libc.so.4 -> libc.so.4.6.29
....

Généralement, vous ne devrez cherchez à savoir de quelles bibliothèques partagées dépendent les binaires Linux(R) que les premières fois que vous installerez des programmes Linux(R) sur le système FreeBSD. Au bout d'un moment, il y aura un ensemble suffisant de bibliothèques partagées Linux(R) sur le système pour être en mesure d'exécuter les binaires Linux(R) nouvellement importés sans effort supplémentaire.

=== Installer des binaires Linux(R) ELF

Une étape supplémentaire est parfois nécessaire pour les binaires ELF. Quand un binaire ELF non marqué est exécuté, une erreur sera générée:

[source,bash]
....
% ./mon-binaire-elf-linux
ELF binary type not known
Abort
....

Pour que le noyau FreeBSD puisse distinguer un binaire ELF FreeBSD d'un binaire Linux(R), vous devez employer l'utilitaire man:brandelf[1]:

[source,bash]
....
% brandelf -t Linux mon-binaire-elf-linux
....

Les outils GNU incorporent désormais automatiquement les marques nécessaires dans les binaires ELF, cette étape n'est généralement pas nécessaire.

=== Installer une application Linux(R) basée sur RPM

Pour installer une application Linux(R) basée sur RPM, installer en premier le logiciel précompilé ou porté package:archivers/rpm4[]. Une fois installé, `root` peut utiliser la commande suivante pour installer un [.filename]#.rpm#:

[source,bash]
....
# cd /compat/linux
# rpm2cpio  /path/to/linux.archive.rpm | cpio -id
....

Si nécessaire, utiliser `brandelf` sur les binaires ELF installés. Il faut noter que cela empêchera une desinstallation propre.

=== Configurer le résolveur de noms de domaines

Si le DNS ne fonctionne pas, ou si cette erreur apparaît::

[source,bash]
....
resolv+: "bind" is an invalid keyword resolv+:
"hosts" is an invalid keyword
....

Vous devrez configurer un fichier [.filename]#/compat/linux/etc/host.conf# contenant:

[.programlisting]
....
order hosts, bind
multi on
....

Cela indique qu'il faut tout d'abord regarder dans le fichier [.filename]#/etc/hosts# puis interroger le DNS. Quand le fichier [.filename]#/compat/linux/etc/host.conf# n'existe pas, les applications Linux(R) trouvent le fichier [.filename]#/etc/host.conf# et se plaignent de sa syntaxe FreeBSD incompatible. Supprimez `bind` si un serveur de noms n'est pas configuré avec le fichier [.filename]#/etc/resolv.conf#.

[[linuxemu-advanced]]
== Sujets avancés

Cette section décrit comment la compatibilité binaire avec Linux(R) fonctionne, et est basée sur un courrier électronique de Terry Lambert mailto:tlambert@primenet.com[tlambert@primenet.com] envoyé à la {freebsd-chat} (Message ID: `199906020108.SAA07001@usr09.primenet.com`).

FreeBSD possède une abstraction appelée "chargeur de classe d'exécution". C'est une portion de l'appel système man:execve[2].

Historiquement, le chargeur UNIX(R) examinait le nombre magique (généralement les 4 ou 8 premiers octets du fichier) pour voir si c'était un binaire connu par le système, et si c'était le cas, invoquait le chargeur binaire.

Si ce n'était pas le type de binaire du système, l'appel man:execve[2] retournait un échec, et l'interpréteur de commandes tentait de l'exécuter comme une commande d'interpréteur. Cette hypothèse était celle par défaut "quelque soit l'interpréteur de commandes actuel".

Plus tard, une modification a été faite sur man:sh[1] pour examiner les deux premiers caractères, et s'ils étaient `:\n`, alors elle invoquait l'interpréteur de commandes man:csh[1] à la place.

FreeBSD possède désormais une liste de chargeurs, avec un chargeur par défaut, `#!`, pour exécuter les interpréteurs ou les procédures de commandes.

Pour le support de l'ABI Linux(R), FreeBSD voit le nombre magique comme un binaire ELF. Le chargeur ELF recherche une _marque_ spécifique, qui se trouve dans une section de commentaires dans l'image ELF, et qui n'est pas présente dans les binaires SVR4/Solaris(TM) ELF.

Pour que les binaires Linux(R) puissent fonctionner, ils doivent être _marqués_ sous le type `Linux` avec man:brandelf[1]:

[source,bash]
....
# brandelf -t Linux file
....

Lorsque le chargeur ELF voit le marquage `Linux`, le chargeur remplace un pointeur dans la structure `proc`. Tous les appels système sont indexés par l'intermédiaire de ce pointeur (dans un système UNIX(R) traditionnel, cela serait la structure `sysent[]`, contenant les appels système). De plus, le processus est marqué pour une gestion spéciale du vecteur d'interruption ("trap") pour le signal de code "trampoline", et plusieurs autres corrections (mineures) qui sont gérées par le noyau Linux(R).

Le vecteur d'appel système Linux(R) contient, entre autres, une liste des entrées `sysent[]` dont les adresses résident dans le noyau.

Quand un appel système est effectué par le binaire Linux, le code "trap" déréférence de la structure `proc` le pointeur de la fonction de l'appel système, et utilise les points d'entrée Linux(R), et non pas FreeBSD, de d'appel système.

Le mode Linux(R) _redéfinit dynamiquement_ l'origine des requêtes. C'est, en effet, équivalent à l'option `union` de montage des systèmes de fichiers. Tout d'abord, une tentative est faite pour rechercher le fichier dans le répertoire [.filename]#/compat/linux/chemin-origine#. Si cela échoue, la recherche est effectuée dans le répertoire [.filename]#/chemin-origine#. Cela permet de s'assurer que les binaires nécessitant d'autres binaires puissent s'exécuter. Par exemple, l'ensemble des outils Linux(R) peuvent tourner sous l'ABI Linux(R). Cela signifie également que les binaires Linux(R) peuvent charger et exécuter les binaires FreeBSD, s'il n'y a pas de binaires Linux(R) correspondant présents, et vous pourriez placer une commande man:uname[1] dans l'arborescence [.filename]#/compat/linux# pour vous assurer que les binaires Linux(R) ne puissent pas dire qu'ils ne tournent pas sous Linux(R).

En effet, il y a un noyau Linux(R) dans le noyau FreeBSD. Les diverses fonctions sous-jacentes qui implémentent tous les services fournis par le noyau sont identiques entre les deux tables d'entrées des appels systèmes FreeBSD et Linux(R): les opérations sur les systèmes de fichiers, les opérations sur la mémoire virtuelle, la gestion des signaux, iet l'IPC System V. La seule différence est que les binaires FreeBSD utilisent les fonctions _glue_ de FreeBSD, et les binaires Linux(R) celles de Linux(R). Les fonctions _glue_ de FreeBSD sont liées en statique dans le noyau, les fonctions _glue_ Linux(R) peuvent être liées statiquement, ou l'on peut y accéder via un module du noyau.

Techniquement, ce n'est pas vraiment de l'émulation, c'est l'implémentation d'une interface binaire pour les applications (ABI). Cela est parfois appelé "émulation Linux(R)" parce que l'implémentation a été faite à une époque où il n'y avait pas vraiment d'autres mots pour décrire ce qui était en développement. Dire que FreeBSD exécutait les binaires Linux(R) n'était pas vrai, jusqu'à ce le code de support Linux(R) soit compilé ou le module soit chargé.
