---
title: Capítulo 13. Usuarios y administración básica de cuentas
part: Parte III. Administración del sistema
prev: books/handbook/boot
next: books/handbook/security
---

[[users]]
= Usuarios y administración básica de cuentas
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Tabla de contenidos
:table-caption: Tabla
:figure-caption: Figura
:example-caption: Ejemplo
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 13

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/users/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/users/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/users/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/es/mailing-lists.adoc[]
include::shared/es/teams.adoc[]
include::shared/es/urls.adoc[]

toc::[]

[[users-synopsis]]
== Sinopsis

FreeBSD permite que varios usuarios usen el mismo ordenador. Obviamente, sólo uno de estos usuarios puede sentarse frente al monitor y al teclado en un momento dado  , pero cualquier número de usuarios puede entrar por la red para hacer su trabajo. Para usar el sistema cada usuario ha de tener una cuenta.

Después de leer este capítulo sabrás:

* Cuáles son las diferencias entre las distintas cuentas de usuario en sistemas FreeBSD.
* Cómo añadir cuentas.
* Cómo eliminar cuentas.
* Cómo cambiar detalles de las cuentas, como el nombre completo del usuario, o su shell preferida.
* Cómo establecer límites por cuenta, para controlar los recursos como memoria o tiempo de CPU que las cuentas y grupos de cuentas pueden emplear.
* Cómo usar grupos para facilitar la administración de cuentas.

Antes de leer este capítulo deberías:

* Entender los conceptos básicos de Unix y FreeBSD (crossref:basics[basics,Conceptos básicos de Unix]).

[[users-introduction]]
== Introducción

Todos los accesos al sistema se consiguen vía cuentas, y todos los procesos son ejecutados por usuarios, por ello la administración de usuarios y cuentas es de una gran importancia en sistemas FreeBSD.

Cada cuenta en un sistema FreeBSD tiene cierta información asociada que la identifica.

Nombre de usuario::
El nombre de usuario como se le entraría al prompt `login:`. Los nombres de usuario han de ser únicos en la computadora; no puede haber dos usuarios con el mismo nombre de usuario. Existen algunas reglas para la creación de nombres de usuario válidos documentadas en man:passwd[5]; típicamente se usarían nombres de usuario de a lo sumo ocho caracteres, todos ellos en minúscula.

Contraseña::
Cada cuenta tiene una contraseña asociada. La contraseña puede ser vacía, en cuyo caso no se requerirá ninguna para acceder al sistema. Esto normalmente es una mala idea; cada cuenta debería tener una constraseña no vacía.

Identificador de usuario (UID)::
El UID es un numero entre 0 y 65536 que sirve para identificar unívocamente al usuario en el sistema. Internamente, FreeBSD usa el UID para identificar usuarios y cualquier comando de FreeBSD que permita especificar un nombre de usuario convertirá éste al UID antes de trabajar con él. Esto significa que puedes tener varias cuentas con nombres de usuario distintos pero con el mismo UID. En lo que a FreeBSD respecta, tales cuentas son un solo usuario. Es improbable que alguna vez tengas que hacer algo así.

Identificador de grupo (GID)::
El GID es un número entre 0 y 65536 que sirve para identificar unívocamente el grupo principal al cual pertenece un usuario. Los grupos son un mecanismo para controlar el acceso a recursos del sistema en base al GID, en vez del UID. Esto puede reducir significativamente el tamaño de algunos ficheros de configuración. Un usuario puede pertencer a más de un grupo.

Clase de login::
Las clases de login son una extensión al mecanismo de grupos que ofrecen una mayor flexibilidad a la hora de adaptar el sistema a distintos usuarios.

Tiempo de cambio de contraseña::
Por defecto FreeBSD no obliga a los usuarios a cambiar su contraseña periódicamente. Se puede requerir esto a determinados usuarios, haciendo que algunos o todos deban cambiar sus contraseñas al cabo de cierto periodo de tiempo.

Tiempo de expiración de cuentas::
Por defecto las cuentas en FreeBSD no expiran. Si estás creando cuentas que sabes que van a tener un tiempo limitado de vida, por ejemplo, las cuentas de los estudiantes de una escuela, entonces puedes especificar cuándo expiran. Una vez vencido su tiempo de expiración una cuenta no puede ser usada para entrar en el sistema, si bien sus directorios y archivos serán conservados.

Nombre completo de usuario::
El nombre de usuario identifica unívocamente a una cuenta para FreeBSD, pero no refleja su verdadero nombre necesariamente. Esta información puede ser asociada a la cuenta. 

Directorio home::
El directorio home es el camino completo de un directorio en el sistema en el que el usuario se hallará cuando entre. Una convención usual consiste en poner todos los directorios home en [.filename]#/home/nombre_de_usuario# o en [.filename]#/usr/home/nombre_de_usuario#. Los usuarios guardarían sus archivos personales en sus directorios home, y en cualquier directorio que creasen allí.

Shell de usuario::
La shell provee el entorno por defecto mediante el cual los usuarios interactúan con el sistema. Existen varios tipos de shell y los usuarios experimentados tendrán sus propias preferencias, que pueden expresarse en la configuración de su cuenta.

Existen principalmente tres tipos de cuentas; la cuenta de <<users-superuser,superusuario>>, las cuentas de <<users-system,usuarios del sistema>>, y las de <<users-user,usuarios>>. La cuenta de superusuario, normalmente llamada `root`, se usa para administrar el sistema sin limitaciones en los privilegios. Los usuarios del sistema utilizan servicios del mismo. Finalmente, las cuentas de usuarios son usadas por gente real, aquellos que entran, leen correo, etcétera.

[[users-superuser]]
== La cuenta superusuario

La cuenta superusuario, normalmente llamada `root`, viene preconfigurada para facilitar la administración del sistema, y no debería ser utilizada para tareas cotidianas como enviar o recibir correo, exploración general del sistema, o programación.

Esto es así porque el superusuario, a diferencia de las cuentas de usuario, puede operar sin límites, y un mal uso de la cuenta de superusuario puede conllevar desastres espectaculares. Las cuentas de usuario no pueden destruir el sistema por un error, por ello es generalmente mejor utilizar cuentas de usuario normales cuando sea posible, a no ser que especialmente necesites privilegios extra.

Deberías comprobar siempre un par o tres de veces los comandos que ejecutas como superusuario, ya que un espacio de más o un carácter omitido pueden significar una pérdida de datos irreparable.

Así pues, lo primero que deberías hacer después de leer este capítulo es crear una cuenta sin privilegios de uso general para ti si aún no la tienes. Esto aplica tanto si trabajas en una máquina con varios usuarios como si trabajas en una máquina con un solo usuario. Más adelante, en este mismo capítulo, explicamos cómo crear cuentas adicionales, y cómo cambiar de usuario normal a superusuario.

[[users-system]]
== Cuentas de sistema

Los usuarios de sistema son aquéllos que corren servicios como DNS, correo, servidores web, etc. Esto es así por seguridad; si todos los servicios corrieran como superusuario podrían actuar sin ninguna restricción.

Algunos ejemplos de usuarios de sistema son `daemon`, `operator`, `bind` (para el DNS), y `news`. Con frecuencia, los administradores de sistemas crean el usuario `httpd` para que ejecute los servidores web que instalan.

`nobody` es el usuario de sistema sin privelegios genérico. No obstante, es importante tener en cuenta que cuantos más servicios use `nobody`, más ficheros y procesos estarán asociados con dicho usuario, y en consecuencia más privilegiado será.

[[users-user]]
== Cuentas de usuario

Las cuentas de usuario constituyen la principal vía de acceso al sistema para la gente real. Estas cuentas aíslan al usuario del entorno, impidiendo que pueda dañar al sistema o a otros usuarios, y permitiendo a su vez que pueda personalizar su entorno sin que esto afecte a otros.

Cada persona que acceda a tu sistema debería tener una sola cuenta de usuario. Esto te permite averiguar quién está haciendo qué, evita que interfieran las configuraciones de distintos usuarios, que unos puedan leer el correo de otros, etcétera.

Cada usuario puede configurar su entorno para acomodarlo al uso que hace del sistema, utilizando shells, editores, atajos de teclado e idioma alternativos.

[[users-modifying]]
== Modificación de cuentas

Existe una variedad de comandos disponible en el entorno Unix para modificar cuentas de usuario. Los comandos más comunes se hallan resumidos a continuación, seguidos de ejemplos más detallados de su uso.

[.informaltable]
[cols="1,1", options="header"]
|===
| Comando
| Resumen

|`adduser`
|La aplicación de línea de comandos recomendada para añadir nuevos usuarios.

|`rmuser`
|La aplicación de línea de comandos recomendada para eliminar usuarios.

|`chpass`
|Una herramienta flexible para modificar la base de datos de usuarios.

|`passwd`
|Una herramienta de línea de comandos simple para cambiar contraseñas de usuario.

|`pw`
|Una herramienta potente y flexible para modificar cualquier aspecto de las cuentas de usuario.
|===

[[users-adduser]]
=== adduser

`adduser` es un programa simple para añadir usuarios. Crea entradas en los archivos de sistema [.filename]#passwd# y [.filename]#group#. También crea un directorio home para el nuevo usuario, copia allí ficheros de configuración por defecto ("dotfiles") de [.filename]#/usr/shared/skel#, y opcionalmente puede enviar al usuario un mensaje de bienvenida.

Para crear el fichero inicial de configuración usa `adduser -s -config_create`.  A continuación configuramos valores por defecto para adduser y creamos nuestra primera cuenta de usuario, dado que utilizar `root` para uso normal del sistema es pernicioso y peligroso.

.Configuración de adduser
[example]
====

[source,bash]
....
# adduser -v
Use option ``-silent'' if you don't want to see all warnings and questions.
Check /etc/shells
Check /etc/master.passwd
Check /etc/group
Enter your default shell: csh date no sh tcsh zsh [sh]: zsh
Your default shell is: zsh -> /usr/local/bin/zsh
Enter your default HOME partition: [/home]:
Copy dotfiles from: /usr/shared/skel no [/usr/shared/skel]:
Send message from file: /etc/adduser.message no
[/etc/adduser.message]: no
Do not send message
Use passwords (y/n) [y]: y

Write your changes to /etc/adduser.conf? (y/n) [n]: y

Ok, let's go.
Don't worry about mistakes. I will give you the chance later to correct any input.
Enter username [a-z0-9_-]: jru
Enter full name []: J. Random User
Enter shell csh date no sh tcsh zsh [zsh]:
Enter home directory (full path) [/home/jru]:
Uid [1001]:
Enter login class: default []:
Login group jru [jru]:
Login group is ``jru''. Invite jru into other groups: guest no
[no]: wheel
Enter password []:
Enter password again []:

Name:     jru
Password: ****
Fullname: J. Random User
Uid:      1001
Gid:      1001 (jru)
Class:
Groups:   jru wheel
HOME:     /home/jru
Shell:    /usr/local/bin/zsh
OK? (y/n) [y]: y
Added user ``jru''
Copy files from /usr/shared/skel to /home/jru
Add another user? (y/n) [y]: n
Goodbye!
#
....

====

En resumen, cambiamos la shell por defecto a zsh (una shell alternativa incluida en la colección de ports), y deshabilitamos el envío de un mensaje de bienvenida a nuevos usuarios. Luego grabamos la configuración, creamos una cuenta para `jru`, y nos aseguramos de que `jru` esté en el grupo `wheel` (de modo que puede asumir el papel de `root` vía el comando `su`).

[NOTE]
====
La contraseña que escribes no se muestra, tampoco se muestran asteriscos. Asegúrate de no entrar dos veces una contraseña equivocada.
====

[NOTE]
====
Usa `adduser` sin argumentos en adelante, no necesitarás cambiar las opciones por defecto. Si el programa te pide modificarlas sal y prueba con la opción `-s`.
====

[[users-rmuser]]
=== rmuser

Puedes usar `rmuser` para eliminar completamente del sistema a un usuario. `rmuser` efectúa los siguientes pasos:

[.procedure]
====
. Elimina la entrada del usuario en man:crontab[1] (si tiene alguna).
. Elimina las tareas man:at[1] pertenecientes al usuario.
. Mata todos los procesos pertenecientes al usuario.
. Elimina al usuario del fichero local de contraseñas del sistema.
. Borra el directorio home del usuario (si le pertenece).
. Elimina los archivos de correo entrante del usuario de [.filename]#/var/mail#.
. Borra todos los ficheros del usuario de áreas en las que se guardan archivos temporales como [.filename]#/tmp#.
. Finalmente, elimina el nombre de usuario de todos aquellos grupos a los que pertenece en [.filename]#/etc/group#. 
+
[NOTE]
======
Si un grupo queda vacío y el nombre del grupo coincide con el del usuario, el grupo es eliminado; esto complementa la creación de grupos por usuario de man:adduser[8].
======
====
`rmuser` no puede ser usado para eliminar cuentas de superusuario, dado que algo así es casi siempre señal de masiva destrucción.

Por defecto existe un modo interactivo que intenta asegurar que uno sabe lo que hace.

.Eliminación interactiva de cuenta con rmuser
[example]
====

[source,bash]
....
# rmuser jru
Matching password entry:
jru:*:1001:1001::0:0:J. Random User:/home/jru:/usr/local/bin/tcsh
Is this the entry you wish to remove? y
Remove user's home directory (/home/jru)? y
Updating password file, updating databases, done.
Updating group file: trusted (removing group jru -- personal group is empty) done.
Removing user's incoming mail file /var/mail/jru: done.
Removing files belonging to jru from /tmp: done.
Removing files belonging to jru from /var/tmp: done.
Removing files belonging to jru from /var/tmp/vi.recover: done.
#
....

====

[[users-chpass]]
=== chpass

`chpass` cambia información de los usuarios en base de datos como contraseñas, shells y datos personales.

Los administradores del sistema, como el superusuario, son los únicos que pueden modificar la información y contraseñas de otros usuarios con `chpass`.

Cuando no le pasamos más opciones, salvo un nombre de usuario opcional, `chpass` muestra un editor con información de usuario. Cuando se sale del editor la base de datos de usuarios se actualiza con la nueva información.

.chpass interactivo ejecutado por el superusuario
[example]
====

[source,bash]
....
#Changing user database information for jru.
Login: jru
Password: *
Uid [#]: 1000
Gid [# or name]: 1000
Change [month day year]:

Expire [month day year]:
Class:
Home directory: /home/jru
Shell: /usr/local/bin/tcsh
Full Name: J. Random User
Office Location:
Office Phone:
Home Phone:
Other information:
....

====

Un usuario normal puede modificar un pequeño subconjunto de esta información, y sólo para sí mismo.

.chpass interactivo ejecutado por un usuario normal
[example]
====

[source,bash]
....
#Changing user database information for jru.
Shell: /usr/local/bin/tcsh
Full Name: J. Random User
Office Location:
Office Phone:
Home Phone:
Other information:
....

====

[NOTE]
====
`chfn` y `chsh` son enlaces a `chpass`, como también lo son `ypchpass`, `ypchfn`, e `ypchsh`. El soporte para NIS es automático, por lo que no es necesario especificar el `yp` antes del comando. Si esto te resulta algo confuso no te preocupes, NIS será tratado en el crossref:advanced-networking[advanced-networking,Networking avanzado].
====

[[users-passwd]]
=== passwd

`passwd` es el comando que se usa normalmente para cambiar tu propia contraseña como usuario o, como superusuario, la de otros usuarios.

[NOTE]
====
Los usuarios han de introducir su contraseña original antes de cambiarla para prevenir que gente no autorizada pueda hacerlo cuando no se encuentren en la consola.
====

.Cambio de tu contraseña
[example]
====

[source,bash]
....
% passwd
Changing local password for jru.
Old password:
New password:
Retype new password:
passwd: updating the database...
passwd: done
....

====

.Cambio de la contraseña de otro usuario como superusuario
[example]
====

[source,bash]
....
# passwd jru
Changing local password for jru.
New password:
Retype new password:
passwd: updating the database...
passwd: done
....

====

[NOTE]
====
Como ocurre con `chpass`, `yppasswd` es un enlace a `passwd`, de manera que NIS funciona con ambos comandos.
====

[[users-pw]]
=== pw

man:pw[8] es una utilidad de línea de comandos para crear, eliminar, modificar, y mostrar usuarios y grupos. Hace de interfaz a los archivos del sistema de usuarios y grupos. `pw` tiene un conjunto de opciones de línea de comandos bastante potente que lo hacen adecuado para su uso en scripts de shell, aunque los nuevos usuarios puede que lo encuentren algo más complicado que el resto de comandos que presentamos aquí.

[[users-limiting]]
== Limitar a los usuarios

En un sistema multiusuario es probable que no confíes en que el sistema no vaya a ser dañado por ningún usuario.

Las cuotas de disco permiten al administrador decirle al sistema de ficheros qué cantidad de espacio de disco puede utilizar un usuario; además, ofrecen una manera rápida de comprobar el uso de disco de un usuario sin tener que calcularlo cada vez. Las cuotas se estudian en el capítulo de quotas.

El resto de límites de recursos incluyen cantidad de CPU, memoria, y otros recursos que el usuario puede utilizar.

Las clases de login se definen en [.filename]#/etc/login.conf#. La semántica precisa está fuera del alcance de esta sección, pero se describe con detalle en la página de manual man:login.conf[5]. Es suficiente decir que cada usuario es asignado a una clase de login (`default` por defecto), y que cada clase de login tiene un conjunto de capacidades asociado. Una capacidad de login es un par `nombre=valor`, donde _nombre_ es un identificador conocido y _valor_ una cadena de texto arbitraria que se procesa en función del nombre. Establecer clases y capacidades de login es bastante sencillo y también se describe en man:login.conf[5].

Los límites de recursos son diferentes de las capacidades de login en dos sentidos. En primer lugar, para cada límite existe un límite blando (actual) y uno duro. Un límite blando puede ser ajustado por el usuario o una aplicación, pero no puede ser más alto que el límite duro. Éste último puede ser disminuido por el usuario pero nunca aumentado. En segundo lugar, la mayoría de los límites de recursos aplican a un usuario concreto por proceso, no globalmente. Nótese, no obstante, que estas diferencias vienen impuestas por cómo se tratan los límites específicamente, no por la implementación del marco de capacidades de login (es decir, en realidad no constituyen un caso especial de capacidades de login).

Sin más, a continuación veremos los límites de recursos más comúnmente usados (el resto, junto con el resto de capacidades de login, puede encontrarse en man:login.conf[5]).

`coredumpsize`::
El tamaño de un fichero core generado por un programa está, por razones obvias, subordinado a otros límites sobre uso de disco (p. ej., `filesize`, o cuotas de disco). Aun y así, se usa frecuentemente como un método menos severo de controlar consumo de espacio de disco, dado que los usuarios no generan ficheros core por ellos mismos, y a menudo no los borran, activar este límite puede evitar que agoten el espacio de disco de que disponen si algún programa grande (p. ej., emacs) deja de funcionar abruptamente.

`cputime`::
Ésta es la máxima cantidad de tiempo de CPU que los procesos de un usuario pueden consumir. 
+
[NOTE]
====
Éste es un límite sobre el _tiempo_ de CPU consumido, no el porcentaje de uso de CPU que se muestra en algunos campos de man:top[1] y man:ps[1]. Un límite de ese tipo no es posible a día de hoy, y sería bastante inútil: un compilador -probablemente una tarea legítima- puede usar prácticamente el 100% de la CPU durante algún tiempo con facilidad.
====

`filesize`::
Éste es el tamaño máximo que puede llegar a tener un fichero del usuario. A diferencia de las cuotas de disco, este límite se especifica para ficheros individuales, no para el conjunto de todos los archivos que posee.

`maxproc`::
Éste es el máximo número de procesos que un usuario puede ejecutar a la vez, incluidos tanto los procesos en primer plano como los procesos en segundo plano. Por razones obvias, este límite no puede ser mayor que el límite de sistema especificado por `kern.maxproc sysctl`. Obsérvese también que si asignamos un valor demasiado bajo a este límite podemos mermar la productividad de un usuario: frecuentemente es útil entrar múltiples veces en el sistema o ejecutar pipelines. Algunas tareas, como compilar largos programas, lanzan múltiples procesos (p. ej., man:make[1], man:cc[1], y demás preprocesadores intermedios).

`memorylocked`::
Ésta es la máxima cantidad de memoria que un proceso puede haber solicitado tener bloqueada en memoria principal (p. ej., ver man:mlock[2]). Algunos programas críticos para el sistema, como man:amd[8], se quedan bloqueados en la memoria principal de manera que en caso de ser llevados a swap no contribuyan a la basura del sistema si hay algún problema.

`memoryuse`::
Ésta es la mayor cantidad de memoria que un proceso puede consumir en todo momento. Incluye tanto memoria normal como uso de swap. No se trata de un límite para restringir el consumo de memoria en general, pero es un buen comienzo.

`openfiles`::
Ésta es la máxima cantidad de archivos que un proceso puede tener abiertos. En FreeBSD, los archivos se usan tambien para representar sockets y canales IPC; así, cuida de no poner este límite demasiado bajo. A nivel de sistema, el límite para esto lo define `kern.maxfiles sysctl`.

`sbsize`::
Éste es el límite de cantidad de memoria de red, y por lo tanto mbufs, que un usuario puede consumir. Se originó como respuesta a un viejo ataque DoS que creaba muchos sockets, pero puede ser usado en general para limitar las comunicaciones por red.

`stacksize`::
Éste es el tamaño máximo que puede alcanzar la pila de un proceso. Por sí solo no es suficiente para limitar la cantidad de memoria que puede usar un programa; en consecuencia, debería ser usado junto con otros límites.

Hay unas pocas cosas más a recordar cuando establecemos límites de recursos. A continuación vienen algunas recomendaciones, sugerencias, y comentarios varios.

* Los procesos que se ponen en marcha cuando arranca el sistema por [.filename]#/etc/rc# están asignados a la clase de login `daemon`.
* Aunque el [.filename]#/etc/login.conf# que viene con el sistema tiene valores razonables para la mayoría de los límites, sólo tú, el administrador, puedes saber lo que es apropiado para tu sistema.
* A los usuarios del X Window System (X11) probablemente se les debería conceder más recursos que al resto. X11 de por sí consume muchos recursos, pero además contribuye a que los usuarios ejecuten más programas simultáneamente.
* Recuerda que hay muchos límites que aplican a procesos individuales, no al usuario en general. Por ejemplo, poner `openfiles` a 50 significa que cada uno de los procesos que ejecute un usuario puede abrir a lo máximo 50 ficheros. Así, la cantidad de ficheros que un usuario puede abrir es el valor de `openfiles` multiplicado por el valor de `maxproc`. Esto también aplica al uso de memoria.

Para más información acerca de límites de recursos y clases y capacidades de login en general, consulta las páginas de manual relevantes: man:cap.mkdb[1], man:getrlimit[2], man:login.conf[5].

[[users-personalizing]]
== Personalizar a los usuarios

La localización es un entorno establecido por el administrador o el usuario para dar soporte a distintos lenguajes, juegos de caracteres, estándares sobre fechas y horas, etcétera. Éste tema se trata en el capítulo crossref:l10n[l10n,Localización].

[[users-groups]]
== Grupos

Un grupo es simplemente una lista de usuarios. Los grupos se identifican por su nombre de grupo y gid (ID de grupo). En FreeBSD (y en la mayoría de sistemas Unix), los dos factores que tiene en cuenta el núcleo para decidir si un proceso puede hacer algo es su ID de usuario y la lista de grupos a los que pertenece. A diferencia del ID de usuario, un proceso tiene una lista de grupos asociados. En ocasiones encontrarás menciones al "ID de grupo" de un usuario o de un proceso; la mayoría de las veces referirán simplemente al primero de los grupos de la lista.

La correspondencia entre nombres e IDs de grupo está en [.filename]#/etc/group#. Se trata de un fichero de texto plano con cuatro campos separados por el signo dos puntos. El primer campo es el nombre de grupo, el segundo la contraseña encriptada, el tercero el ID de grupo, y el cuarto la lista de miembros separados por comas. Puede ser editado a mano sin peligro (¡suponiendo, por supuesto, que no se cometan errores de sintaxis!). Para una descripción más completa de la sintaxis, ver la página de manual man:group[5].

Si no quieres editar [.filename]#/etc/group# manualmente, puedes usar el comando man:pw[8] para añadir y modificar grupos. Por ejemplo, para añadir un grupo llamado `teamtwo` y luego confirmar que existe puedes usar:

.Añadir un grupo usando man:pw[8]
[example]
====

[source,bash]
....
# pw groupadd teamtwo
# pw groupshow teamtwo
teamtwo:*:1100:
....

====

El número `1100` en el ejemplo anterior es el ID de grupo del grupo `teamtwo`. Ahora mismo `teamtwo` no tiene miembros, y es por tanto bastante inútil. Cambiemos eso invitando a `jru` a formar parte del grupo `teamtwo`.

.Añadir a alguien a un grupo usando man:pw[8]
[example]
====

[source,bash]
....
# pw groupmod teamtwo -M jru
# pw groupshow teamtwo
teamtwo:*:1100:jru
....

====

El argumento de la opción `-M` es una lista con los usuarios que son miembros del grupo separados por comas. Sabemos de secciones anteriores que el fichero de contraseñas también contiene un grupo para cada usuario. El usuario es automáticamente añadido a la lista de grupos por el sistema; no constará como miembro cuando usemos el comando `groupshow` con man:pw[8], pero sí cuando la información se consulte con man:id[1] u otra herramienta similar. En otras palabras, man:pw[8] sólo manipula el fichero [.filename]#/etc/group#; nunca tratará de leer datos adicionales de [.filename]#/etc/passwd#.

.Determinar pertenencia a grupos con man:id[1]
[example]
====

[source,bash]
....
% id jru
uid=1001(jru) gid=1001(jru) groups=1001(jru), 1100(teamtwo)
....

====

Como puedes ver, `jru` es miembro de los grupos `jru` y `teamtwo`.

Para más información acerca de man:pw[8], consulta su página de manual, y para más información acerca del formato de [.filename]#/etc/group#, consulta la página de manual de man:group[5].
