# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   current.sgml
DOCS+=	doc-set.sgml
DOCS+=	handbook.sgml
DOCS+=	handbook3.sgml
DOCS+=  sgml.sgml
DOCS+=  submitting.sgml
DOCS+=  who.sgml
DOCS+=  translations.sgml
DOCS+=	docproj.sgml
DOCS+=	todo.sgml

INDEXLINK= docproj.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
