=== The FreeBSD Russian Documentation Project

Links: +
link:https://docs.freebsd.org/ru/books/faq/[FAQ] URL: link:https://docs.freebsd.org/ru/books/faq/[] +
link:https://www.freebsd.org/ru/[Web] URL: link:https://www.freebsd.org/ru/[]

Contact: Andrey Zakhvatov <andrey.zakhvatov@gmail.com>

The FreeBSD Russian Documentation Project current goal is to provide up-to-date Russian translations of the most significant parts of FreeBSD documentation (FAQ, Handbook, Web).
It is important to support Russian-speaking persons with high-quality official technical materials and increase acceptance of the operating system around the globe.
We hope that this activity will receive some support within the Russian-speaking FreeBSD community and lead to an increased number of translated materials.

FAQ translation was updated and synched with the latest original version.
There is also a very slight progress with web pages updates.

Check the link:https://docs.freebsd.org/en/books/fdp-primer/translations/[official translation guide] in case you are willing to help.
We will appreciate your help with translation of the following materials:

* Web pages (easy)
* Handbook sections (only the X11 section is in progress right now)
* Articles
