=== FreeBSD Foundation

Links: +
link:https://www.freebsdfoundation.org[FreeBSD Foundation] URL: link:https://www.freebsdfoundation.org[] +
link:https://freebsdfoundation.org/blog/technology-roadmap/[Technology Roadmap] URL: link:https://freebsdfoundation.org/blog/technology-roadmap/[] +
link:https://www.freebsdfoundation.org/donate/[Donate] URL: link:https://www.freebsdfoundation.org/donate/[] +
link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[Foundation Partnership Program] URL: link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[] +
link:https://www.freebsdfoundation.org/journal/[FreeBSD Journal] URL: link:https://www.freebsdfoundation.org/journal/[] +
link:https://www.freebsdfoundation.org/news-and-events/[Foundation News and Events] URL: link:https://www.freebsdfoundation.org/news-and-events/[]

Contact: Deb Goodkin <deb@FreeBSDFoundation.org>

The FreeBSD Foundation is a 501(c)(3) non-profit organization dedicated to supporting and promoting the FreeBSD Project and community worldwide.
Donations from individuals and corporations are used to fund and manage software development projects, conferences, and developer summits.
We also provide travel grants to FreeBSD contributors, purchase and support hardware to improve and maintain FreeBSD infrastructure, and provide resources to improve security, quality assurance, and release engineering efforts.
We publish marketing material to promote, educate, and advocate for the FreeBSD Project, facilitate collaboration between commercial vendors and FreeBSD developers, and finally, represent the FreeBSD Project in executing contracts, license agreements, and other legal arrangements that require a recognized legal entity.

==== Fundraising Efforts

We finally have our 2022 fundraising numbers in and we raised a total of $1,231,096!
We were short of our goal, which forced us to pull around $74,000 from our longer term investments.

Besides receiving a lot of donations from you our users and contributors, we received larger donations from Juniper, Meta, Arm, Netflix, Beckhoff, Tarsnap, Modirum, Koum Family Foundation, and Stormshield.
I’d like to extend a heartfelt thank you on behalf of the Foundation to everyone, including individuals and corporations, for your financial contributions in 2022!

This year our budget is around $2,230,000, which includes increased spending towards FreeBSD advocacy and software development.
More than half our budget is allocated towards work directly related to improving FreeBSD and keeping it secure.
To fund the 2023 budget, we increased our fundraising goal and plan on using some of our investment money.
When we received our first million dollar donation, the plan was to use up to 10% of it each year to increase our work to improve FreeBSD, so this has been part of our funding plan for a few years now.

The 2023 budget is in the process of being approved by the board of directors and will be published once it is approved.

This quarter we received donations from Juniper, Tarsnap, Microsoft, and Stormshield.
So, we are already off to a great start!
But, we definitely need more to support our planned efforts for 2023.

If you want to help us continue our efforts, please consider making a donation towards our 2023 fundraising campaign!
link:https://www.freebsdfoundation.org/donate/[]

We also have a Partnership Program for larger commercial donors.
You can read about it at link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[].

==== OS Improvements

During the first quarter of 2023, 226 src, 39 ports, and 12 doc tree commits identified the Foundation as a sponsor.
Some of this sponsored work is described in separate report entries:

* Continuous Integration
* Enabling Snapshots on Filesystems Using Journaled Soft Updates
* FreeBSD as a Tier 1 cloud-init Platform
* FreeBSD Release Engineering Team
* Improve the kinst DTrace provider
* OpenStack on FreeBSD

Other Foundation-sponsored work included:

* OpenSSH fixes and updates to versions 9.2p1 and 9.3p1
* a vendor import and update of libpcap to version 1.10.3
* improvements to tmpfs, msdosfs, and makefs
* the addition of a new kqueue1 syscall
* man page updates
* dtrace and bhyve fixes
* LinuxKPI work

==== Continuous Integration and Quality Assurance

The Foundation provides a full-time staff member and funds projects to improve continuous integration, automated testing, and overall quality assurance efforts for the FreeBSD project.
You can read more about CI work in a dedicated report entry.
A current project that is being funded by the FreeBSD Foundation is one to develop a set of scripts to help src developers conduct CI tests themselves.
One of the main goals is to offer more visibility at the pre-commit stage.
link:https://reviews.freebsd.org/D38815[A review for the first milestone] has been submitted.

==== FreeBSD Advocacy and Education

Much of our effort is dedicated to the FreeBSD Project advocacy.
This may involve highlighting interesting FreeBSD work, producing literature and video tutorials, attending events, or giving presentations.
The goal of the literature we produce is to teach people FreeBSD basics and help make their path to adoption or contribution easier.
Other than attending and presenting at events, we encourage and help community members run their own FreeBSD events, give presentations, or staff FreeBSD tables.

The FreeBSD Foundation sponsors many conferences, events, and summits around the globe.
These events can be BSD-related, open source, or technology events geared towards underrepresented groups.
We support the FreeBSD-focused events to help provide a venue for sharing knowledge, working together on projects, and facilitating collaboration between developers and commercial users.
This all helps provide a healthy ecosystem.
We support the non-FreeBSD events to promote and raise awareness of FreeBSD, to increase the use of FreeBSD in different applications, and to recruit more contributors to the Project.
We are back to attending events mostly in person and began planning the in person May 2023 Developer Summit, co-located with BSDCan.
In addition to attending and planning events, we are continually working on new training initiatives and updating our selection of link:https://freebsdfoundation.org/freebsd-project/resources/[how-to guides] to facilitate getting more folks to try out FreeBSD.

Check out some of our advocacy and education work:

* Hosted a stand at FOSDEM 2023, February 4-5, 2023 in Brussels, Belgium.
Check out the link:https://freebsdfoundation.org/blog/fosdem-2023-conference-report/[trip report].
* Hosted a table at State of Open Con 2023, February, 7-8, 2023, in London, England.
link:https://freebsdfoundation.org/blog/advocating-for-freebsd-around-the-world/[Read more] about it.
* Sponsored, held a workshop and hosted a booth at SCALE 20x, in March 9-12, 2023, Pasadena, California.
Check out the link:https://freebsdfoundation.org/blog/freebsd-at-scale-20x/[trip report].
* Sponsored Open Source 101, March 23 2023, in Charlotte, NC.
* Sponsored and began planning the in-person link:https://wiki.freebsd.org/DevSummit/202305[May 2023 Developer Summit] taking place May 17-18, 2023 in Ottawa, Ontario
* Secured our Media Partner sponsorship status and submitted a workshop for link:https://2023.allthingsopen.org/[All Things Open], October 15-17, 2023 in Raleigh, NC.
* Submitted a Workshop proposal for link:https://sfconservancy.org/fossy/[FOSSY], July 13-16, 2023, in Portland, OR.
* The FreeBSD Project was accepted as a link:https://summerofcode.withgoogle.com/programs/2023/organizations/the-freebsd-project[Participating Organization] for Google Summer of Code.
* We held link:https://youtu.be/NpOkTR_d8os[GSoC Office Hours] to help prospective participants with questions.
* Published link:https://freebsdfoundation.org/news-and-events/newsletter/freebsd-foundation-update-march-2023/[March Newsletter]

* Additional Blog Posts

** link:https://freebsdfoundation.org/blog/under-the-hood-with-freebsd-and-ampere-altra/[Under the Hood with FreeBSD and Ampere Altra]
** link:https://freebsdfoundation.org/blog/under-the-hood-with-freebsd-and-ampere-altra/[New Open Position: FreeBSD Userland Software Developer] - Note: Posting is closed.
** link:https://freebsdfoundation.org/blog/bsdcan-2023-travel-grant-application-now-open/[BSDCan 2023 Travel Grant Application Now Open] - Note: Applications are closed

* FreeBSD in the News:

** link:https://freebsdfoundation.org/news-and-events/latest-news/vmblog-state-of-open-con-qa-with-deb-goodkin/[VMBlog State of Open Con Q&A with Deb Goodkin]

We help educate the world about FreeBSD by publishing the professionally produced FreeBSD Journal.
As we mentioned previously, the FreeBSD Journal is now a free publication.
Find out more and access the latest issues at link:https://www.freebsdfoundation.org/journal/[].

You can find out more about events we attended and upcoming events at link:https://www.FreeBSDfoundation.org/news-and-events/[].

==== Legal/FreeBSD IP

The Foundation owns the FreeBSD trademarks, and it is our responsibility to protect them.
We also provide legal support for the core team to investigate questions that arise.

Go to link:https://www.freebsdfoundation.org[] to find more about how we support FreeBSD and how we can help you!
