=== GCC on FreeBSD

Links: +
link:https://gcc.gnu.org[GCC Project] URL: link:https://gcc.gnu.org[] +
link:https://gcc.gnu.org/gcc-11/[GCC 11 release series] URL: link:https://gcc.gnu.org/gcc-11/[] +
link:https://gcc.gnu.org/gcc-12/[GCC 12 release series] URL: link:https://gcc.gnu.org/gcc-12/[]

Contact: Lorenzo Salvadore <salvadore@FreeBSD.org> +
Contact: Gerald Pfeifer <gerald@pfeifer.com>

The main news this quarter is the cleaning of old GCC versions from the ports tree: this will allow for a more efficient approach to bugs.

==== Deprecation of old GCC ports

The ports tree still contains several ports related to old and unsupported GCC versions.
They are usually needed as dependencies for a few old ports, that it would be better to either update to use a supported GCC release, or deprecate.
link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269644[Bug reports] have been created to track the issue and work has already started towards its resolution.
Thanks to all ports contributors who are helping.

==== Deprecation of USE_GCC=X+

Gerald, who maintained the GCC ports for many years until recently, still contributes to the GCC maintenance on FreeBSD by helping simplify the GCC infrastructure in the ports tree, for example by removing special cases that deal with old unsupported GCC versions.

This quarter the most significant of his changes is probably link:https://cgit.freebsd.org/ports/commit/?id=9b5f5ab8482f105311d01a32260ef32bba4a2628[the removal of support for the `USE_GCC=X+` construct]: any port depending on GCC should set `USE_GCC=yes` if `GCC_DEFAULT` works; if not, it should require a specific version (e.g. `USE_GCC=11`); it cannot ask for a minimal version anymore (e.g. `USE_GCC=11+`).
