=== KDE on FreeBSD

Links: +
link:https://freebsd.kde.org/[KDE FreeBSD] URL: link:https://freebsd.kde.org/[] +
link:https://community.kde.org/FreeBSD[KDE Community FreeBSD] URL:link:https://community.kde.org/FreeBSD[]

Contact: Adriaan de Groot <kde@FreeBSD.org>

The KDE on FreeBSD project packages CMake, Qt, and software from the KDE Community, for the FreeBSD ports tree.
The software includes a full desktop environment called KDE Plasma (for both X11 and Wayland) and hundreds of applications that can be used on any FreeBSD machine.

The KDE team (kde@) is part of desktop@ and x11@, building the software stack to make FreeBSD beautiful and usable as a daily-driver graphics-based desktop machine.
The notes below describe *mostly* ports for KDE, but also include items that are important for the entire desktop stack.

==== Infrastructure

* The Qt5 ports were updated to the KDE patch collection release 5.15.8.
* The Qt6 ports -- these are not used by KDE yet, but there are many ports that can use Qt6 and have Qt6 flavors -- were updated to release 6.4.2.
Python bindings for the Qt6 release of WebEngine were added.
* The cmake ports were updated to release 3.25.1 and the CPack generator for FreeBSD packages was repaired.
* The package:graphics/poppler[] port -- used by many PDF-viewers -- was updated to release 23.01.
* The package:sysutils/bsdisks[] port -- used as a shim for applications that expect Linux udisks, which means most desktop environments -- was updated to release 0.29.

==== KDE Stack

KDE Gear releases happen every quarter, KDE Plasma updates once a month, and KDE Frameworks have a new release every month as well.
These (large) updates land shortly after their upstream release and are not listed separately.

* KDE Frameworks updated to 5.104.
* KDE Gear updated to 22.12.3.
* KDE Plasma Desktop was updated to version 5.27.
This was a long delayed update, due to unresolved issues in the support stack and a misplaced patch from an earlier release of KDE Plasma.
Thanks to arrowd@ and Serenity Cybersecurity, LLC for sorting that out.
* New port package:devel/ktextaddons[] was added to the tree.
This is part of the KDE PIM suite, and slated to become a new KDE Framework in some future release.

==== Related Ports

* package:audio/amarok[], one of the most popular KDE audio players of the early 2000's, has been marked deprecated in the ports tree.
It is no longer maintained upstream.
* package:astro/kstars[], an interactive planetarium, was updated to release 3.6.3.
* package:devel/gitqlient[], a graphical user interface for git, was updated to release 1.6.1 with support for new git commands.
* package:devel/okteta[], a hex viewer and editor for binary files, was updated to release 0.26.10.
* package:devel/qcoro[], C++ coroutines with Qt support, was updated to release 0.8.0.
* package:graphics/krita[], an application for painting and graphical work, was updated to release 5.1.5.
* package:graphics/quickqanava[], a graph visualization library, got a real release and an update in the ports tree.
* package:irc/kvirc[], an IRC client, was updated to the latest commit; there is no real release but there are bugfixes.
* package:multimedia/haruna[], a video and audio player, was updated to release 0.10.3.
* package:net-im/neochat[], one of a handful of Matrix clients, was updated to chase a new release of package:net-im/libquotient[].
There are continuing troubles with compatibility with older FreeBSD releases, leading to the KDE-FreeBSD team to declare FreeBSD 12 releases "effectively unsupported".
* package:net-im/ruqola[], a Rocket Chat client, was updated to release 1.9.1.
* package:security/keysmith[], a two-factor-authentication support application, was updated to release 23.01.0.
