=== PkgBase.live

Links: +
link:https://web.archive.org/web/20221220222828/https://alpha.pkgbase.live/[Website (archive.org)] URL: link:https://web.archive.org/web/20221220222828/https://alpha.pkgbase.live/[] +
link:https://codeberg.org/pkgbase/website[Website source] URL: link:https://codeberg.org/pkgbase/website[]

Contact: Mina Galić <freebsd@igalic.co>

PkgBase.live _was_ an unofficial repository for the FreeBSD link:https://wiki.freebsd.org/PkgBase[PkgBase project].
As a service, PkgBase.live was inspired by link:https://up.bsd.lv/[], which provides man:freebsd-update[8] for STABLE and CURRENT branches.

Hardware for PkgBase was kindly sponsored by a member of the FreeBSD community.
However, as life and projects moved on, they had to decommission the hardware, giving me three months' notice.
In that time, my own life was rather turbulent after a recent move to a different country so I haven't been able to find a replacement.

For the time being, PkgBase.live is dead.

The website, and with it the link:https://codeberg.org/pkgbase/website/src/branch/main/howto/howdo.md[How Did She Do it?!] are still available in link:https://codeberg.org/pkgbase/website[Git].
I highly encourage copy-cats.

I will also happily accept a new hardware sponsor!

Please note that I _have_ contacted the FreeBSD Project, and they _are_ working on integrating PkgBase into release engineering.
However, they are not yet ready, they also cannot "simply" take over PkgBase.live because it uses a completely different process.
