=== Ports Collection

Links: +
link:https://www.FreeBSD.org/ports/[About FreeBSD Ports] URL: link:https://www.FreeBSD.org/ports/[] +
link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[Contributing to Ports] URL: link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[] +
link:http://portsmon.freebsd.org/[FreeBSD Ports Monitoring] URL: link:http://portsmon.freebsd.org/[] +
link:https://www.freebsd.org/portmgr/[Ports Management Team] URL: link:https://www.freebsd.org/portmgr/[] +
link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[Ports Tarball] URL: link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[]

Contact: René Ladan <portmgr-secretary@FreeBSD.org> +
Contact: FreeBSD Ports Management Team <portmgr@FreeBSD.org>

The Ports Management Team is responsible for overseeing the overall direction of the Ports Tree, building packages (through its subsidiary pkgmgr), and personnel matters.
Below is what happened in this quarter.

Currently we have around 33,500 ports in the tree.
For these ports, there are 3,021 open problem reports, of which 764 are unassigned.
The first three months of this year saw 9,021 commits by 163 committers for the `main` branch and 701 commits by 55 committers for the `2023Q1` branch.
Compared to `2022Q4`, this means a slight increase in the number of ports, port PRs, ports commits, and active port committers.

During this quarter, we welcomed Robert Clausecker (fuz@), Vladimir Druzenko (vvd@), Robert Nagy (rnagy@), welcomed back Norikatsu Shigemura (nork@), and said goodbye to Marius Strobl (marius@).
Portgmr added Muhammad Moinur Rahman (bofh@) as a new member after a successful lurkership.

During the bi-weekly portmgr meetings, the following topics were discussed:

* improving the situation of binary packages for kernel modules
* ways to measure the impact of ports on their dependencies and how to maintain high-impact ports.

During this quarter, 32 exp-runs were run to test port updates, updating default versions (LLVM to 15, MySQL to 8.0, Ruby to 3.1), and updating byacc in base.
Furthermore, the default version of Go switched to 1.20 and that of Lazarus to 2.2.6.

Four new USES were introduced:

* `budgie` to support ports related to the Budgie Desktop
* `ldap` to provide support for OpenLDAP, with a new default version of 26 (i.e. 2.6)
* `nextcloud` to support Nextcloud applications
* `ruby` to provide support for Ruby ports (formerly `bsd.ruby.mk`).
