# $FreeBSD$
#
# Article: FreeBSD and Linux Comparison Whitepaper

MAINTAINER= marketing@FreeBSD.org

DOC?= article

FORMATS?= html
INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
