---
title: Chapter 5. The FreeBSD Documentation Build Process
prev: books/fdp-primer/structure
next: books/fdp-primer/asciidoctor-primer
---

[[doc-build]]
= The FreeBSD Documentation Build Process
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 5

toc::[] 

This chapter covers organization of the documentation build process and how man:make[1] is used to control it.

[[doc-build-rendering]]
== Rendering AsciiDoc into Output

Different types of output can be produced from a single AsciiDoc source file.

[cols="20%,20%,60%", frame="none", options="header"]
|===
| Formats
| File Type
| Description

|`html`
|HTML
|An `article` or `book` chapter.

|`pdf`
|PDF
|Portable Document Format.

|`epub`
|EPUB
|Electronic Publication. ePub file format.
|===

To render the documentation and the website use one of the following examples.

[[documentation-build-example]]
.Build the documentation
[example]
====
[source,bash]
....
% cd ~/doc/documentation
% make
....
====

[[website-build-example]]
.Build the website
[example]
====
[source,bash]
....
% cd ~/doc/website
% make
....
====

[[doc-build-toolset]]
== The FreeBSD Documentation Build Toolset

These are the tools used to build and install the FDP documentation.

* The primary build tool is man:make[1], specifically Berkeley Make.
* Python is used to generate the Table of Contents and other related Tables.
* Hugo
* AsciiDoctor
* Git

[[doc-build-makefile]]
== Understanding the Makefile in the Documentation Tree

There is only one [.filename]#Makefile# in the [.filename]#documentation# and other in the [.filename]#website#. Both are pretty similar.

[[documentation-makefile]]
=== Documentation Makefile

This [.filename]#Makefile# take the form of:

[source,bash]
....
# Generate the FreeBSD documentation
#
# Copyright (c) 2020-2021 The FreeBSD Documentation Project
# Copyright (c) 2020-2021, Sergio Carlavilla <carlavilla@FreeBSD.org>
#
# Targets intended for use on the command line
#
# all (default)	-	generate the books TOC and compile all the documentation
# compile	-	generate the books TOC and build all the documentation

MAINTAINER=carlavilla@FreeBSD.org <.>

PYTHON_CMD =	/usr/local/bin/python3.7 <.>
HUGO_CMD =	/usr/local/bin/hugo <.>
LANGUAGES =	en,es,pt_BR,de,ja,zh_CN,zh_TW,ru,el,hu,it,mn,nl,pl,fr <.>

all: starting-message generate-books-toc run <.>
generate: starting-message generate-books-toc build <.>

starting-message: <.>
	@echo ---------------------------------------------------------------
	@echo                   Building the documentation
	@echo ---------------------------------------------------------------

generate-books-toc: <.>
	${PYTHON_CMD} ./tools/books-toc-parts-creator.py -l ${LANGUAGES}
	${PYTHON_CMD} ./tools/books-toc-creator.py -l ${LANGUAGES}
	${PYTHON_CMD} ./tools/books-toc-figures-creator.py -l ${LANGUAGES}
	${PYTHON_CMD} ./tools/books-toc-tables-creator.py -l ${LANGUAGES}
	${PYTHON_CMD} ./tools/books-toc-examples-creator.py -l ${LANGUAGES}

run: <.>
	${HUGO_CMD} server -D 

build: <.>
	${HUGO_CMD} --minify
....

<.> The `MAINTAINER` flag specifies who is the maintainer of this Makefile.
<.> `PYTHON_CMD` flag specifies the location of the Python binary.
<.> `HUGO_CMD` flag specifies the location of the Hugo binary.
<.> `LANGUAGES` flag specifies in which languages the table of contents has to be generated.
<.> `all` target generate the books TOCs and run the documentation in the Hugo local webserver.
<.> `generate` target generate the books TOCs and build the documentation in the [.filename]#~/doc/documentation/public# folder. The content of this folder should be placed in a HTTP server like nginx.
<.> `starting-message` shows a message in the CLI to show the user that the process is running.
<.> `generate-books-toc` calls the scripts to generate the books TOCs.
<.> `run` runs hugo webserver in a random free port.
<.> `build` builds the documentation and puts the result in the [.filename]#~/doc/documentation/public#.

[[website-makefile]]
=== Website Makefile

This [.filename]#Makefile# take the form of:

[source,bash]
....
# Generate the FreeBSD website
#
# Copyright (c) 2020-2021 The FreeBSD Documentation Project
# Copyright (c) 2020-2021, Sergio Carlavilla <carlavilla@FreeBSD.org>
#
# Targets intended for use on the command line
#
# all (default)	-	generate the releases.toml and compile all the website
# generate	-	generate the releases.toml and build all the website

MAINTAINER=carlavilla@FreeBSD.org <.>

PYTHON_CMD =	/usr/local/bin/python3.7 <.>
HUGO_CMD =	/usr/local/bin/hugo <.>

all: starting-message generate-releases run <.>
generate: starting-message generate-releases build <.>

starting-message: <.>
	@echo ---------------------------------------------------------------
	@echo                   Building the website
	@echo ---------------------------------------------------------------

generate-releases: <.>
	${PYTHON_CMD} ./tools/releases-toml.py -p ./shared/releases.adoc

run: <.>
	${HUGO_CMD} server -D

build: <.>
	${HUGO_CMD} --minify
....

<.> The `MAINTAINER` flag specifies who is the maintainer of this Makefile.
<.> `PYTHON_CMD` flag specifies the location of the Python binary.
<.> `HUGO_CMD` flag specifies the location of the Hugo binary.
<.> `all` target generate the books TOCs and run the website in the Hugo local webserver.
<.> `generate` target generate the books TOCs and build the website in the [.filename]#~/doc/website/public# folder. The content of this folder should be placed in a HTTP server like nginx.
<.> `starting-message` shows a message in the CLI to show the user that the process is running.
<.> `generate-releases` calls the script used to convert from AsciiDoc variables to TOML variables. With this conversion, the releases variables can be used in AsciiDoc and in the Hugo custom templates.
<.> `run` runs hugo webserver in a random free port.
<.> `build` builds the website and puts the result in the [.filename]#~/doc/website/public#.
