.\" %FreeBSD: src/usr.sbin/cdcontrol/cdcontrol.1,v 1.21.2.1 2000/06/29 23:49:28 ps Exp %
.\" jpman %Id: cdcontrol.1,v 1.3 1997/07/22 09:20:03 mutoh Stab %
.\"
.Dd July 3, 1995
.Dt CDCONTROL 1
.Os FreeBSD
.Sh 名称
.Nm cdcontrol
.Nd コンパクトディスク制御ユーティリティ
.Sh 書式
.Nm cdcontrol
.Op Fl sv
.Op Fl f Ar device
.Op Ar command ...
.Sh 解説
.Nm
はオーディオ CD プレイヤーを操作するためのプログラムです。
device には 
.Pa cd0
や
.Pa mcd0
などを指定します。
.Pp
もし、device が指定されなかった場合、環境変数 
.Ev MUSIC_CD ,
.Ev CD_DRIVE ,
.Ev DISC
を (この順番で) 使用して、cd デバイスを探します。
.Pp
コマンドを指定しない場合、
.Nm
は対話モードになり、標準入力からコマンドを読み込みます。
.Pp
以下のオプションを使用可能です。
.Bl -tag -width indent
.It Fl s
サイレントモード - テーブルヘッダ及び人間が可読なコメントを表示しません。
.It Fl v
冗長モード - 表示できる情報は全て表示します。
.It Fl f Ar device
.Pa /dev/cd0c
や
.Pa mcd0
といったデバイスを指定します。
絶対パス及び
.Pa /dev
からの相対パスの指定が可能です。
必要ならば最後に `c' を追加します。
.El
.Pp
現時点では以下のコマンドが利用できます。
コマンドをユニークに特定できるために必要な文字だけ指定する
必要があります。
語
.Em play
は省略可能です。
.Bl -tag -width Cm

.It Cm play first_track last_track
.Ar first_track 
で指定されたトラックから
.Ar last_track 
で指定されたトラックまで演奏します。最初のトラックが1番になります。

.It Cm play start_m:start_s.start_f Op Ar end_m:end_s.end_f
絶対アドレス (MSF) を元に演奏します。演奏開始する時間は
.Ar start_m
に演奏開始する分を、
.Ar start_s
に秒を、
.Ar start_f
にはフレーム番号を指定します。演奏終了の時間は
.Ar end_m
に演奏終了する分を、
.Ar end_s,
に秒を、
.Ar end_f
にフレーム番号を指定することで指定できます。分指定で指定できる数値は 0 
から 99 の範囲の値です。秒には 0 から 59 までが指定できます。フレーム
番号は 0 から 74 までの範囲で指定できます。

.It Cm play Op Ar #start_block Op length
論理ブロック
.Ar start_block
から
.Ar length
論理ブロック分だけ演奏します。

.It Cm pause
演奏を停止します。ディスクは停止しません。

.It Cm resume
演奏を再開します。
.Em pause
で一時停止した後に使います。

.It Cm stop
ディスクを停止します。

.It Cm eject
ディスクを取り出します。

.It Cm close
ディスクを挿入します。

.It Cm setvol left_channel right_channel
左チャンネルのボリュームを
.Ar left_channel
にセットし、右チャンネルを
.Ar right_channel
にセットします。指定できる値は 0 から 255 の範囲の値です。

.It Cm volume Ar mute
音を消します。

.It Cm volume Ar mono
モノラルモードにします。

.It Cm volume Ar stereo
ステレオモードにします。

.It Cm volume Ar left
左サブトラックを左と右の両チャネルで演奏します。

.It Cm volume Ar right
右サブトラックを左と右の両チャネルで演奏します。

.It Cm info
目次を表示します。

.It Cm status
.Op Ar audio | media | volume

ディスクに関する以下のような情報を表示します:

.Nm audio
現在の演奏の状態と位置、

.Nm media
現在のメディアカタログ状態、

.Nm volume
現在の左チャネル及び右チャネルのボリューム値。

.It Cm help
利用可能なコマンドの一覧を表示します。

.It Cm debug Ar on
CD デバイスドライバのデバッグモードを有効にします。

.It Cm debug Ar off
ドライバのデバッグモードを無効にします。

.It Cm reset
デバイスに対するハードウェアリセットを実行します。

.It Cm set Ar msf
minute-second-frame ioctl モードに設定します (デフォルト)。

.It Cm set Ar lba
LBA ioctl モードに設定します。

.It Cm quit
プログラムを終了します。

.Sh 関連ファイル
.Bl -tag -width /dev/mcd0c -compact
.It Pa /dev/cd0c
.It Pa /dev/mcd0c
.It Pa /dev/acd0c
.El
.Sh 作者
.An Jean-Marc Zucconi ,
.An Andrey A.\ Chernov ,
.An Serge V.\ Vakulenko
.Sh 歴史
.Nm
コマンドは
.Fx 2.1
から登場しました。
