.\" Copyright (c) 1989, 1990, 1993, 1994
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)chflags.1	8.2 (Berkeley) 3/31/94
.\" %FreeBSD: src/usr.bin/chflags/chflags.1,v 1.6.2.1 1999/08/29 15:26:09 peter Exp %
.\" jpman %Id: chflags.1,v 1.3 1997/06/18 14:15:48 jsakai Stab %
.\"
.Dd March 31, 1994
.Dt CHFLAGS 1
.Os
.Sh 名称
.Nm chflags
.Nd ファイルのフラグを変更する
.Sh 書式
.Nm chflags
.Oo
.Fl R
.Op Fl H | Fl L | Fl P
.Oc
.Ar flags
.Ar file ...
.Sh 解説
.Nm chflags
は指定したファイルのフラグを、
.Ar flags
で指定した値に変更します。
.Pp
オプションは以下のとおりです。
.Bl -tag -width Ds
.It Fl H
.Fl R
オプションが指定されていれば、引数で指定されたシンボリックリンクを
たどります
(木構造の検索中にみつかったシンボリックリンクはたどりません)。
.It Fl L
.Fl R
オプションが指定されていれば、全てのシンボリックリンクをたどります。
.It Fl P
.Fl R
オプションが指定されていれば、どのシンボリックリンクもたどりません。
.It Fl R
指定されたファイル自身ではなく、
そのファイル以下のディレクトリ階層すべての
フラグを変更します。
.El
.Pp
フラグはキーワードをコンマで区切ったものです。
現在定義されているキーワードは以下のとおりです:
.Bd -literal -offset indent compact
arch	archived フラグをセットします (スーパユーザのみ)
dump	dump フラグをセットします
sappnd	system append-only (システムレベルでの追加専用) フラグをセットします 
	(スーパユーザのみ)
schg	system immutable (システムレベルでの変更不可) フラグをセットします
	(スーパユーザのみ)
sunlnk	system undeletable (システムレベルでの削除不可) フラグをセットします
	(スーパユーザのみ)
uappnd	user append-only (ユーザレベルでの追加専用) フラグをセットします
	(所有者またはスーパユーザのみ)
uchg	user immutable (ユーザレベルでの変更不可) フラグをセットします
	(所有者またはスーパユーザのみ)
uunlnk	user undeletable (ユーザレベルでの削除不可) フラグをセットします
	(所有者またはスーパユーザのみ)
archived、sappend、schange、simmutable、uappend、uchange、uimmutable,
sunlink, uunlink
	は上記のキーワードのエイリアスです。
.Ed
.Pp
オプションキーワードの前に
.Dq no
をつけると、そのフラグを無効にします。
例えば、
.Bd -literal -offset indent compact
nodump	dump フラグをクリアします
.Ed
.Pp
シンボリックリンクにはフラグはありません。
よって、
.Fl H
あるいは
.Fl L
オプションを指定せずにシンボリックリンクに
対して
.Nm chflags
を実行した場合、常に成功しますが、何の効果もありません。
.Fl H
、
.Fl L
、
.Fl P
オプションは
.Fl R
オプションを指定しない限り無視されます。
また、これらのオプションはお互いの効果を上書きするため、
最後に指定されたオプションによってコマンドの動作が決まります。
.Pp
ファイルのフラグを見るには "ls -lo" とします。
.Pp
.Nm chflags
は実行に成功すると 0 を、エラーが発生すると 0 より大きい値を
戻り値として返します。
.Sh 関連項目
.Xr ls 1 ,
.Xr chflags 2 ,
.Xr stat 2 ,
.Xr fts 3 ,
.Xr symlink 7
.Sh 歴史
.Nm chflags
は
.Bx 4.4
に初めて登場しました。
