.\" Copyright (c) 1989, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)df.1	8.3 (Berkeley) 5/8/95
.\" %FreeBSD: src/bin/df/df.1,v 1.13.2.5 2000/05/09 14:27:05 sheldonh Exp %
.\"
.\" jpman %Id: df.1,v 1.2 1997/04/07 05:31:08 mutoh Stab %
.Dd May 8, 1995
.Dt DF 1
.Os BSD 4
.Sh 名称
.Nm df
.Nd ディスクの空き領域等の表示
.Sh 書式
.Nm df
.Oo
.Fl b | h | H | k |
.Fl m | P
.Oc
.Op Fl in
.Op Fl t Ar type
.Op Ar file | Ar filesystem ...
.Sh 解説
.Nm
は、
.Ar file_system
で指定したファイルシステム、
もしくは
.Ar file
で指定したファイルが実際に格納されているファイルシステムの空きディスク容量の
表示を行います。
ディスク容量は、512 バイトを 1 ブロックとしたブロック数で表示
します。
.Nm
の引数として、
.Ar file_system
も
.Ar file
も指定されなかった場合は、マウントされているすべてのファイ
ルシステムについての情報を表示します。
ただし、
.Fl t
オプションによって、表示するファイルタイプの指示が可能です。
.Pp
オプションとしては以下のものがあります:
.Bl -tag -width Ds
.It Fl b
デフォルト値でなく 512 バイトブロックを使用します。
これは、環境の
.Ev BLOCKSIZE
指定に優先することに注意してください。
.It Fl H
「人間が読める」出力です。
単位サフィックスに、バイト、キロバイト、メガバイト、
ギガバイト、テラバイト、ペタバイトを使用して数字を 3 桁以下に減らします。
大きさの基数は 10 です。
.It Fl h
「人間が読める」出力です。
単位サフィックスに、バイト、キロバイト、メガバイト、
ギガバイト、テラバイト、ペタバイトを使用して数字を 3 桁以下に減らします。
大きさの基数は 2 です。
.It Fl i
フリーな i ノードの情報も表示します。
.It Fl k
デフォルトの 512 バイトではなく、 1024 バイト (1K バイト)
を 1 ブロックとしてディスク容量を表示します。
このオプションは、環境変数
.Ev BLOCKSIZE
の指示を無効にします。
.It Fl m
デフォルトの代りに 1048576 バイト (1 M バイト) ブロックを使用します。
これは、環境の
.Ev BLOCKSIZE
指定に優先することに注意してください。
.It Fl n
.Fl n
オプションが指定されると、
.Nm
は、ファイルシステムから以前に得た情報を返します。
情報の問い合わせに長い時間を要するおそれのあるファイルシステムに対して
用いるオプションです。
このオプションを指定すると、
.Nm
はファイルシステムに新しい情報を問い合わせず、
以前に取得しておいた最新ではない可能性のある情報を表示します。
.It Fl P
デフォルトの代りに POSIX 準拠の 512 バイトブロックの出力を行います。
これは、環境の
.Ev BLOCKSIZE
指定に優先することに注意してください。
.It Fl t
指示されたタイプのファイルシステムに関する情報のみ
を表示します。
複数のタイプをコンマで区切ってリスト指定可能です。
リスト中のファイルシステムタイプの前に
.Dq no
を付けて、そのファイルシステムタイプに対しては動作
.Em しない
ように指定可能です。
例えば、
.Nm
コマンド:
.Bd -literal -offset indent
df -t nonfs,mfs
.Ed
.Pp
は
.Tn NFS
および
.Tn MFS
以外の全ファイルシステムを表示します。
システム上で利用可能なファイルシステムタイプは
.Xr lsvfs 1
コマンドを使用して調べられます。
.Sh 環境変数
.Bl -tag -width BLOCKSIZE
.It Ev BLOCKSIZE
環境変数
.Ev BLOCKSIZE
が設定されていれば、指定された値をブロックサイズとしてブロック数を表示します。
.El
.Sh バグ
.Ar file_system
または
.Ar file
が指示されてた場合は、
.Fl n
オプションと
.Fl t
オプションは
無効になります。
.Sh 関連項目
.Xr lsvfs 1 ,
.Xr quota 1 ,
.Xr fstatfs 2 ,
.Xr getfsstat 2 ,
.Xr statfs 2 ,
.Xr getmntinfo 3 ,
.Xr fstab 5 ,
.Xr mount 8 ,
.Xr quot 8
.Sh 歴史
.Nm
ユーティリティは
.At v1
から登場しています。
