.TH IPNAT 1
.\" jpman %Id: ipnat.1,v 1.3 1998/10/15 13:17:52 kuma Stab %
.SH 名称
ipnat \- NAT のユーザインタフェース
.SH 書式
.B ipnat
[
.B \-lnrsvCF
]
.B \-f <\fIfilename\fP>
.SH 解説
.PP
\fBipnat\fP は列挙されたファイルをオープンし ("\-" は標準入力として扱います)、
そのファイルを解釈して、
IP NAT に対し追加または削除するルールセットを求めます。
.PP
\fBipnat\fP が処理する各ルールは、解釈に問題がなければ、
カーネル内部のリストに追加されます。
ルールは、\fBipnat\fP に与えられた時の出現順に一致する順序で
内部リストの最後に追加されます。
.SH オプション
.TP
.B \-C
現在の NAT ルールリスト (NAT ルール) から全エントリを除去します。
.TP
.B \-F
現在の NAT 変換テーブル中のすべての活動エントリ
(現在活動状態の NAT マッピング)
を除去します。
.TP
.B \-l
現在の NAT テーブルエントリマッピングのリストを表示します。
.TP
.B \-n
このフラグ (無変更) は、\fBipnat\fP が実際に ioctl を呼び出すことと、
現在実行中のカーネルを変更することを妨げます。
.\" ipf -> ipnat だと思う
.\" ipnat にしときました(kuma)
.TP
.B \-s
NAT 統計を取り出して表示します。
.TP
.B \-r
マッチする NAT ルールを、内部リストに追加するのではなく、削除します。
.TP
.B \-v
冗長モードをオンにします。
ルール処理とアクティブなルール/テーブルエントリに関する情報を表示します。
.DT
.SH 関連ファイル
/dev/ipnat
.SH 関連項目
ipnat(5), ipf(8), ipfstat(8)
