.\"	from: @(#)key.1	1.0 (Bellcore) 12/2/91
.\" %FreeBSD: src/usr.bin/key/key.1,v 1.5.2.2 2001/03/06 12:52:43 ru Exp %
.\" $FreeBSD$
.\"
.Dd December 2, 1991
.Dt KEY 1
.Os
.Sh 名称
.Nm key
.Nd S/Key 試行の応答を計算するための独立プログラム
.Sh 書式
.Nm
.Op Fl n Ar count
.Ar sequence
.Ar key 
.Sh 解説
.Nm key
は、オプションの count を表示すべき一回利用パスワード
(one time access password) の数として、
そして (最大の) シーケンス番号とキーをコマンドライン引数として取ります。
そして、ユーザに秘密のパスワードの入力を促し、
単語と 16 進フォーマットの両方の応答を作成します。
.Pp
次のオプションが使用可能です:
.Bl -tag -width Fl
.It Fl n Ar count
出力する一回利用パスワードの数です。
デフォルトは 1 です。
.El
.Sh 使用例
使用例です。
.Bd -literal -offset indent -compact
>key -n 5 99 th91334
Enter password: <your secret password is entered here>
OMEN US HORN OMIT BACK AHOY
\&.... 4 more passwords.
>
.Ed
.Sh 関連項目
.Xr keyinfo 1 ,
.Xr keyinit 1 ,
.Xr skey 1
.Sh 作者
.An -nosplit
コマンドは、
.An Phil Karn ,
.An Neil M. Haller ,
.An John S. Walden
によって
作られました。
.Sh 連絡先
.Aq staff@thumper.bellcore.com
