.\"	from: @(#)keyinfo.1	1.1 (Bellcore) 7/20/93
.\" %FreeBSD: src/usr.bin/keyinfo/keyinfo.1,v 1.7.2.1 2000/12/08 15:13:44 ru Exp %
.\" jpman %Id: keyinfo.1,v 1.2 1997/04/18 07:31:28 mutoh Stab %
.\"
.Dd April 26, 1996
.Dt KEYINFO 1
.Os
.Sh 名称
.Nm keyinfo
.Nd 現在の S/Key シーケンスナンバーとキーを表示する
.Sh 書式
.Nm
.Op Ar username
.Sh 解説
.Nm
はユーザ名のオプションをとり、
ユーザの現在の S/Key データベースである
.Pa /etc/skeykeys
にあるシーケンスナンバとキーが表示されます。
このコマンドはフォームの中での
.Xr key 1
コマンドの結合によって、旅行に出かける時に使うパスワードの一覧表を
生成する時に有用です。
.Bd -literal -offset indent
key -n  <number of passwords> `keyinfo` | lpr
.Ed
.Pp
オプションの
.Ar username
引数は、S/key 情報の表示対象のユーザを指定します。
デフォルトでは、本コマンドを起動したユーザの S/key 情報を表示します。
スーパユーザのみが、他のユーザの S/key 情報を問い合わせ可能です。
.Sh 使用例
実行例を以下に示します:
.Bd -literal -offset indent
$ keyinfo
.Ed
.Pp
これは次の出力になります:
.Bd -literal -offset indent
98 ws91340
.Ed
.Sh 診断
.Nm
は、要求されたユーザのキーが見付かったときに終了コード 0 を返し、
そうでない場合に終了コード 1 を返します。
.Sh 関連項目
.Xr key 1 ,
.Xr keyinit 1
.Sh 作者
.An -nosplit
もともとのコマンドは、
.An Phil Karn ,
.An Neil M. Haller ,
.An John S. Walden
に
よって作成されました。
perl 用に書き直したのは、
.if n An Joerg Wunsch
.if t An J\(:org Wunsch
です。この版では setuid をしていますので、 S/Key のキーファイルは
ユーザから読めないようにしておくことができます。
