.\"-
.\" Copyright (c) 2004 Dag-Erling Coïdan Smørgrav
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" %FreeBSD: src/usr.bin/logins/logins.1,v 1.2 2004/03/06 23:36:41 des Exp %
.\" $FreeBSD$
.\"
.Dd March 6, 2004
.Dt LOGINS 1
.Os
.Sh ƒtƒZƒZƒz
.Nm logins
.Nd EuEƒHEƒ’Eó¥ƒlƒZðÊó¤òÉƒXƒVƒBAƒPAk
.Sh ƒXñ¼|
.Nm
.Op Fl admopstux
.Op Fl g Ar groups
.Op Fl l Ar logins
.Sh ƒCòÀb
.Nm
Eæ¡ƒVEƒjEvEê¥ƒjEvAƒ}BuEæ¡ƒVEƒJAƒFAè¤ƒ‚EƒLEƒPEƒjEà¥uEƒHEƒ’Eó¥ƒlAƒzƒZðÊó¤òÉƒXƒVƒBAƒLAJAƒPBv
.Pp
|ƒnƒCƒVAƒzEƒFEƒ‰EƒLEç¥ó¤ò»ƒlƒwƒ€ƒCƒgƒkƒXAƒkAƒP:
.Bl -tag -width ".Fl g Ar groups"
.It Fl a
ƒEƒjEuEƒHEƒ’Eó¥ƒlAƒqAƒgAAAƒjBu
Eƒ€EƒPEï¡ƒVEƒmƒnƒ€ƒPƒPAƒFAè¤ƒ‚EuEƒHEƒ’Eó¥ƒlAƒzƒwƒ…ƒNú´ü¸ƒcAƒqƒGƒŠAƒPAë¾ðÊó¤òÉƒXƒVƒBAƒLAJAƒPBv
.It Fl d
ƒXƒiƒnvAƒLAƒ\ UID Aò»ýAƒgEuEƒHEƒ’Eó¥ƒlAòÁƒFƒcò¤ƒLAJAƒPBv
.It Fl g Ar groups
ƒTƒŠƒgê¤ƒLAƒ\E|Eë¡ƒVEƒ‰Aƒqƒc|AƒPAë¥uEƒHEƒ’Eó¥ƒlAòÁƒFƒcò¤ƒLAJAƒPBv
ƒnvƒ\ô¤ƒzE|Eë¡ƒVEƒ‰ƒtƒZAò»ƒŠƒgê¤ƒPAë¾ì¹ç¤ƒ}Bu
E|Eë¡ƒVEƒ‰ƒtƒZAò¥ƒEEó¥JAƒkƒJèÀƒŒAëÉƒƒƒwƒ‰AƒƒAuAê¤JAƒPBv
.It Fl l Ar logins
ƒTƒŠƒgê¤ƒLAƒ\Eí¥|EAEóÌƒZAƒlEJEƒeEƒ`AƒPAë¥uEƒHEƒ’Eó¥ƒlAòÁƒFƒcò¤ƒLAJAƒPBv
ƒnvƒ\ô¤ƒzEí¥|EAEóÌƒZAò»ƒŠƒgê¤ƒPAë¾ì¹ç¤ƒ}BuEí¥|EAEóÌƒZAò¥ƒEEó¥JAƒkƒJèÀƒŒAëÉƒƒƒwƒ‰AƒƒAuAê¤JAƒPBv
.It Fl m
EƒTEƒHEó¥ƒ^Eê¥|Eë¡ƒVEƒ‰AƒqƒGƒŠAƒPAë¾ðÊó¤òÉƒXƒVƒBAƒLAJAƒPBv
.It Fl o
ƒEƒjEuEƒHEƒ’Eó¥ƒlAƒzƒZðÊó¤ƒqAƒgAAAƒjBu
Eƒ†EvBƒVEë¥ƒmAò¥ƒEEí¥ó¤ƒkƒJèÀƒŒAƒeAƒ\ƒLƒ`AƒqAƒLAƒjBu|ì¥uEƒHEƒ’Eó¥ƒlAƒqAƒgAƒ…|ì¹ƒ„AƒkƒmƒXƒVƒBAƒLAJAƒPBv
.It Fl p
Eƒ€EƒPEï¡ƒVEƒmAƒzAƒnAAEuEƒHEƒ’Eó¥ƒlAòÁƒFƒcò¤ƒLAJAƒPBv
.It Fl s
EƒLEƒPEƒjEà¥uEƒHEƒ’Eó¥ƒlAòÁƒFƒcò¤ƒLAJAƒPBv
ƒNƒXƒRKAƒzAƒlAƒEAí¡uEƒLEƒPEƒjEà¥uEƒHEƒ’Eó¥ƒlAƒlAƒ}BuUID Aƒƒ 1000 ƒtAƒqþAƒzEuEƒHEƒ’Eó¥ƒlAƒFAè¤ƒ‚
.Dq Li nobody
EuEƒHEƒ’Eó¥ƒl (UID 65534) AƒlAƒLAƒjƒgêµƒ`AƒIAì¤ƒjAAAJAƒPBv
.It Fl t
ƒ`ƒFƒcò¤ƒIAì¤ƒ\EuEƒHEƒ’Eó¥ƒlAò¡uUID AƒkAƒ}AƒnAƒbƒtƒZƒ`|AƒkEƒXBƒVEƒlAƒLAJAƒPBv
.It Fl u
Eæ¡ƒVEƒJEuEƒHEƒ’Eó¥ƒlAòÁƒFƒcò¤ƒLAJAƒPBv
ƒNƒXƒRKAƒzAƒlAƒEAí¡uEæ¡ƒVEƒJEuEƒHEƒ’Eó¥ƒlAƒlAƒ}BuUID Aƒƒ 1000 |ƒnƒZå¤ƒzEuEƒHEƒ’Eó¥ƒlAƒzAƒ’Aƒ`Bu
.Dq Li nobody
EuEƒHEƒ’Eó¥ƒl (UID 65534) Aò½ü¤AAƒ\Aâ¤ƒzAƒlAƒLAƒjƒgêµƒ`AƒIAì¤ƒjAAAJAƒPBv
.It Fl x
ƒEƒjEuEƒHEƒ’Eó¥ƒlAƒqAƒgAAAƒjBuEƒBƒVEà¥ƒkEvEì¥ƒbEƒlEê¤ƒlEƒLEƒ@Eë¤ƒqƒGƒŠAƒPAë¾ðÊó¤òÉƒXƒVƒBAƒLAJAƒPBv
.El
.Pp
ƒ`ƒFƒcò¥ƒFEƒ‰EƒLEç¥ó¤ƒƒƒnvƒ\ô»ƒŠƒgê¤ƒIAì¤ƒ\ƒZì¹ç¡u
ƒTƒŠƒgê¤ƒIAì¤ƒ\ƒ`ƒFƒcò¾ò·ï¤ƒzAAAƒRAì¤ƒHAƒqEJEƒeEƒ`AƒPAë¥uEƒHEƒ’Eó¥ƒlAƒƒAƒPAƒ‹AƒjƒmƒXƒVƒBAƒIAì¤JAƒPBv
.Pp
ƒ`ƒFƒcò¥ƒFEƒ‰EƒLEç¥ó¤ƒƒƒTƒŠƒgê¤ƒIAì¤ƒnAƒHAƒeAƒ\ƒZì¹ç¡uAƒPAƒ‹AƒjAƒzEuEƒHEƒ’Eó¥ƒlAƒƒƒmƒXƒVƒBAƒIAì¤JAƒPBv
.Sh ƒGƒŠƒ}uƒPàÌƒ
.Xr getgrent 3 ,
.Xr getpwent 3 ,
.Xr group 5 ,
.Xr passwd 5 ,
.Xr pw 8
.Sh ƒzò»ƒq
.Nm
Eæ¡ƒVEƒjEvEê¥ƒjEvAƒ}
.Fx 4.10
AƒkAƒ}AƒNAá¤ƒjƒiƒ~ƒZì¤ƒLAJAƒLAƒ\Bv
.Sh ƒRî¼ƒ„
.Nm
Eæ¡ƒVEƒjEvEê¥ƒjEvAƒ}Bu
ƒcƒZAƒzEƒFEƒŒEì¡ƒVEƒjEvEó¥|EƒLEƒPEƒjEà¤ƒzƒzà»÷¤ƒzEæ¡ƒVEƒjEvEê¥ƒjEvAò¤â¤ƒlAƒqBu
.An Dag-Erling Sm\(/orgrav Aq des@FreeBSD.org
AƒqAè¤ƒeAƒjƒXñ¤ƒHAì¤JAƒLAƒ\Bv
