.\" Copyright (c) 1980, 1990, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)mail.1	8.2 (Berkeley) 12/30/93
.\" %FreeBSD: src/usr.bin/mail/mail.1,v 1.18.2.5 2001/03/06 12:52:49 ru Exp %
.\" $FreeBSD: doc/ja_JP.eucJP/man/man1/mail.1,v 1.18 2001/05/14 01:07:26 horikawa Exp $
.\"
.Dd December 30, 1993
.Dt MAIL 1
.Os BSD 4
.Sh 名称
.Nm mail
.Nd メールの送信と受信
.Sh 書式
.Nm
.Op Fl iInv
.Op Fl s Ar subject
.Op Fl c Ar cc-addr
.Op Fl b Ar bcc-addr
.Ar to-addr ...
.Oo
.Fl
.Ar sendmail-option ...
.Oc
.Nm
.Op Fl iInNv
.Fl f
.Op Ar name
.Nm
.Op Fl iInNv
.Op Fl u Ar user
.Sh 紹介
.Nm
はインテリジェントなメール処理システムです。
コマンド文法は
.Xr \&ed 1
に似ており、
.Xr \&ed 1
での行の代わりにメッセージを扱う形になっています。
.Pp
.Bl -tag -width flag
.It Fl v
冗長 (verbose) モードです。
メールの配送の詳細がユーザのターミナルに表示されます。
.It Fl i
tty の割り込みシグナルを無視します。
これは特に雑音の多い電話回線を通して
.Nm
を使う場合に役に立ちます。
.It Fl I
入力がターミナルでない場合にでも強制的に mail を対話モードで実行します。
特にメールを送る時の特殊文字
.Sq Ic \&~
は対話モードでのみ有効となります。
.It Fl n
起動時にシステム全体の
.Pa mail.rc
ファイルを読み込みません。
.It Fl N
メールを読んだりメールフォルダを編集する時に、最初のメッセージヘッダの
表示を行いません。
.It Fl s
コマンドラインからサブジェクトを指定します
(
.Fl s
フラグの後の最初の引数だけがサブジェクトとして使われます。空白を含む
サブジェクトは引用符で囲むように注意して下さい。)
.It Fl c
カーボンコピーをユーザの
.Ar list
へ送ります。
.It Fl b
ブラインドカーボンコピーを
.Ar list
へ送ります。
.Ar list
はコンマで区切られた名前のリストとなります。
.It Fl f
あなたの
.Ar mbox
(もしくは指定されたファイル) の内容を処理対象として読み込みます。
.Ar quit
した時には
.Nm
は削除されなかったメッセージをこのファイルに書き戻します。
.It Fl u
これは以下と等価です。
.Pp
.Dl mail -f /var/mail/user
.El
.Ss 起動時の動作
.Nm
は、起動時に、システムのコマンドファイル
.Pa /usr/share/misc/mail.rc ,
.Pa /usr/local/etc/mail.rc ,
.Pa /etc/mail.rc
をこの順番に実行します。ただし、
.Fl n
オプションを使用して、実行しないよう明示的に指定された場合は例外です。
次に、ユーザの個人的なコマンドファイル
.Pa ~/.mailrc
を実行します。その後
.Nm
はコマンドラインオプションを検査し、
新規メッセージを送るのか既存のメールボックスを読むのかを決定します。
.Ss メールを送る
メッセージを 1 人かそれ以上の人に送るために
.Nm
をメールが送られる相手の名前を引数として起動することができます。
メッセージをタイプした後、行の先頭で
.Sq Li control\-D
を入力します。
下記の
.Ar 「メールにリプライしたり、メールを始める」
のセクションでは手紙を編集する際に役に立つ
.Nm
の機能について説明しています。
.Pp
.Ss メールを読む
通常の使い方では
.Nm
は引数を指定しないで起動すると、ポストオフィスのメールをチェックし、見
つかった各メッセージにつき 1 行ずつヘッダを表示します。
現在のメッセージは初期状態では最初のメッセージ ( 1 番に番号が振られて
います) となっており、
.Ic print
コマンド (省略形
.Ic p
を使うことができます) によって表示することができます。
メッセージの位置を
.Xr \&ed 1
と同様に
.Ql Ic \&+
と
.Ql Ic \&\-
のコマンドを使って後や前に移動したり、単に数字を指定して移動したりする
ことができます。
.Pp
.Ss メールを廃棄する
メッセージをチェックした後、メッセージを
.Ic delete
コマンド
.Pq Ic d
で削除したり、それに
.Ic reply
コマンド
.Pq Ic r
でリプライ (返事を出す) したりすることができます。
メッセージを削除すると
.Nm
プログラムはそのメッセージのことを忘れますが、
この操作は取り消すことができます。
メッセージは
.Ic undeleted
コマンド
.Pq Ic u
を使ってメッセージの番号を指定するか、
.Nm
のセッションを
.Ic exit
コマンド
.Pq Ic x
で中途終了することによって削除をとりやめることができます。
しかし、削除されたメッセージは通常はなくなり二度と見ることはできませ
ん。
.Pp
.Ss メッセージを指定する
.Ic print
や
.Ic delete
のようなコマンドは、引数に複数のメッセージの番号を指定することによって
複数のメッセージに対して一度に適用することができます。
たとえば
.Dq Li delete 1 2
はメッセージ 1 と 2 を削除し、
.Dq Li delete 1\-5
は 1 から 5 のメッセージを削除します。
特別な名前
.Ql Li \&*
は全てのメッセージを意味し、
.Ql Li \&$
は最後のメッセージを意味します。
メッセージの最初の数行を表示するコマンド
.Ic top
を使って
.Dq Li top \&*
で全てのメッセージの最初の数行を表示することができます。
.Pp
.Ss メールにリプライしたり、メールを始める
.Ic reply
コマンドを使ってメッセージに対する返事を用意して、それをメッセージの差
出人に送り返すことができます。
タイプインしたメッセージは end-of-file までがメッセージの内容として定
義されます。
メッセージを編集している時に
.Nm
は
文字
.Ql Ic \&~
で始まる行を特別に扱います。
例えば、
.Ql Ic \&~m
とタイプする (行にこれだけタイプします) と現在のメッセージを
タブの分 (下記の変数
.Em indentprefix
を参照) だけ右にシフトして返事のメッセージにコピーします。
他のエスケープはサブジェクトの設定や、メッセージの受取人の追加や削除を
行なったり、またメッセージを修正するためにエディタを起動したり、コマン
ドを実行するためにシェルを起動したりします。
(下にこれらのオプションの要約があります。)
.Pp
.Ss メールの処理セッションを終了する
.Nm
セッションは
.Ic quit
コマンド
.Pq Ic q
で終了することができます。
チェックされたメッセージは削除されていなければ
.Ar mbox
ファイルにセーブされます。削除されている場合は本当に廃棄されます。
チェックされていないメッセージはポストオフィスに書き戻されます
(上記の
.Fl f
オプション参照)。
.Pp
.Ss 個人の配布リストとシステム全体の配布リスト
たとえば
.Dq Li cohorts
へメールを送ると複数の人に配布されるように、個人の配布リストを作成する
こともできます。
このようなリストは
.Pp
.Dl alias cohorts bill ozalp jkf mark kridle@ucbcory
.Pp
というような行をホームディレクトリの
.Pa \&.mailrc
ファイルに書いておくことによって定義できます。
このようなエイリアス (別名) の現在のリストは
.Nm
内で
.Ic alias
コマンドを使って表示することができます。
システム全体にわたる配布リストは
.Pa /etc/mail/aliases
を編集することによって作成することができます。
これについては
.Xr aliases  5
と
.Xr sendmail  8 
を参照してください。これらでは違った形式で記述されます。
あなたが送ったメールの中では個人のエイリアスが展開され、そのメールの受取
人が他の受取人に
.Ic reply
できるようになります。
システム全体の
.Ic aliases
はメールが送られた時には展開されませんが、
そのマシンに返信されたメールは
.Xr sendmail
によって処理される際にシステム全体のエイリアスで展開されます。
.Pp
.Ss ネットワークメール (ARPA, UUCP, Berknet)
ネットワークアドレスの説明については
.Xr mailaddr 7
を参照してください。
.Pp
.Nm
には
.Pa .mailrc
ファイルの中でセットして動作方法を変更するためのオプションがたくさんあ
ります。
たとえば
.Dq Li set askcc
は
.Ar askcc
機能を有効にします。
(これらのオプションについては下にまとめてあります。)
.Sh 要約
(`Mail Reference Manual' より抜粋)
.Pp
各コマンドは行中に単独入力されるか、またコマンドの後に引数をとることも
あります。
コマンドは全て入力する必要はありません。途中まで入力されたも
のに最初にマッチしたコマンドが使われます。
メッセージリストを引数として取るコマンドについては、メッセージリストが
与えられなければコマンドに要求されるものを満たす次のメッセージが使われ
ます。
次のメッセージがない場合にはサーチは逆順に行なわれ、もし適用されるメッ
セージが発見できない場合には
.Nm
は
.Dq Li \&No applicable messages
と表示しコマンドを中断します。
.Bl -tag -width delete
.It Ic \&\-
前のメッセージを表示します。
数字の引数
.Ar n
が指定されると、
.Ar n
個前に移動してメッセージを表示します。
.It Ic \&#
行中のこれ以降をコメントとして無視します。
.It Ic \&?
コマンドの短い要約を表示します。
.It Ic \&!
これに引き続くシェルコマンドを実行します
(
.Xr sh 1
と
.Xr csh 1
を参照) 。
.It Ic Print
.Pq Ic P
.Ic print
と同様ですが、無視されるヘッダフィールドも表示されます。
.Ic print ,
.Ic ignore ,
.Ic retain
を参照してください。
.It Ic Reply
.Pq Ic R
発信者に返信します。
元のメッセージの他の受取人には返信されません。
.It Ic Type
.Pq Ic T
.Ic Print
と同じです。
.It Ic alias
.Pq Ic a
引数がない場合は、現在定義されている全てのエイリアスを表示します。
引数がひとつ伴うと、そのエイリアスを表示します。
複数の引数が指定されると、新しいエイリアスを作成するか、古いものを変更
します。
.It Ic alternates
.Pq Ic alt
.Ic alternates
コマンドはいくつかのマシンにアカウントがある場合に便利な機能です。
.Nm
に対してリストされたアドレスがあなたのアドレスであることを指示するため
に使われます。
.Ic reply
コマンドによってメッセージに返信するときに
.Nm
は
.Ic alternates
リストにリストされているアドレスにはメッセージのコピーを送付しません。
.Ic alternates
コマンドが引数なしで指定された場合、現在の alternate の内容が表示され
ます。 
.It Ic chdir
.Pq Ic c
ユーザの作業ディレクトリを指定されたものに変更します。
ディレクトリが指定されていなければ、ユーザのログインディレクトリに変更
します。
.It Ic copy
.Pq Ic co
.Ic copy
コマンドは
.Ic save
と同様のことを行ないますが、終了時に削除を行なうためのマークをメッセー
ジにつけません。
.It Ic delete
.Pq Ic d
メッセージのリストを引数として取り、それら全てを削除されたものとしてマー
クします。
削除されるメッセージは
.Ar mbox
にはセーブされず、また他のほとんどのコマンドの対象となりません。
.It Ic dp
(もしくは
.Ic dt )
現在のメッセージを削除し、次のメッセージを表示します。
次のメッセージがなければ、
.Nm
は
.Dq Li "at EOF"
と表示します。
.It Ic edit
.Pq Ic e
メッセージのリストを引数として取り、各々を順にテキストエディタで開きま
す。
メッセージはテキストエディタから戻ってきた時に再度読み込まれます。
.It Ic exit
.Ic ( ex
もしくは
.Ic x )
ユーザのシステムメールボックス、
.Ar mbox
ファイル、
.Fl f
での編集ファイルを変更せずにシェルへ直ちに戻ります。
.It Ic file
.Pq Ic fi
.Ic folder
と同様です。
.It Ic folders
フォルダディレクトリ内のフォルダ名をリストします。
.It Ic folder
.Pq Ic fo
.Ic folder
コマンドは新しいメールファイルかフォルダに切り替えます。
引数がないと、現在どのファイルを読んでいるかを表示します。
引数を指定すると、現在のファイルに対して行なった変更 (削除など) を書き
出し、新しいファイルを読み込みます。
引数の名前にはいくつかの特別な記法を使うことができます。
# は前のファイルを意味します。
% はあなたのシステムメールボックスを意味します。
%user は user のシステムメールボックスを意味します。
& はあなたの 
.Ar mbox
ファイルを意味します。
\&+\&folder はあなたのフォルダディレクトリ中のファイルを意味します。
.It Ic from
.Pq Ic f
メッセージのリストを引数として取り、それらのメッセージのヘッダを表示し
ます。
.It Ic headers
.Pq Ic h
現在の範囲のヘッダをリストします。現在の範囲は 18 個のメッセージのグルー
プです。 
引数として
.Ql \&+
が指定されると次の 18 個のメッセージのグループが表示され、
.Ql \&\-
が指定されると前の 18 個のメッセージのグループが表示されます。
.It Ic help
.Ic \&?
と同じです。
.It Ic hold
.Ic ( ho
もしくは
.Ic preserve )
メッセージのリストを引数として取り、各メッセージを
.Ar mbox 
ではなくユーザのシステムメールボックスにセーブするためのマークをつけ 
ます。
.Ic delete
によってマークが付けられているメッセージにはマークはつけません。
.It Ic ignore
.Ar ignored list
にヘッダフィールドのリストを追加します。
ignore list (無視リスト) に登録されているヘッダフィールドは
メッセージを表示する際にターミナルに表示されません。
このコマンドはマシンが生成するヘッダフィールドの表示を省略するのに非常
に便利です。
.Ic Type
と
.Ic Print
コマンドを使うと表示の際に無視するフィールドも含めメッセージの全てを表
示することができます。
.Ic ignore
が引数なしで実行されると現在の無視するフィールドのリストが表示されます。
.It Ic mail
.Pq Ic m
ログイン名と配布グループ名を引数として取り、メールをそれらの人々に送付
します。
.It Ic more
.Pq Ic \&mo
メッセージのリストを引数として取り、そのリストに対してページャを起動し
ます。
.It Ic mbox
終了時にあなたのホームディレクトリの
.Ic mbox
へ書き込むメッセージのリストを指定します。
.Ic hold
オプションをセットして
.Em いなければ
、これはメッセージに対するデフォルトの動作となります。
.It Ic next
.Pq Ic n
(
.Ic \&+
や
.Tn CR
と同様)
次のメッセージへ進み、それを表示します。
引数リストを指定すると、次にマッチするメッセージを表示します。
.It Ic preserve
.Pq Ic pre
.Ic hold 
と同様です。
.It Ic print
.Pq Ic p
メッセージリストを引数として取り、各メッセージをユーザのターミナルに表
示します。
.It Ic quit
.Pq Ic q
セッションを終了し、全ての未削除のまだセーブしていないメッセージをユー
ザのホームディレクトリの
.Ar mbox
ファイルへセーブし、
.Ic hold
か
.Ic preserve
でマークされたメッセージか参照されなかったメッセージはシステムメールボッ
クスに残し、その他の全てのメッセージをシステムメールボックスから削除し
ます。
もし新しいメールがセッション中に届いていたら、メッセージ
.Dq Li "You have new mail"
を表示します。
もしメールボックスのファイルを
.Fl f
フラグ付きで編集している途中であれば、編集中のファイルは再度書き込まれ
ます。
編集中のファイルの再書き込みが失敗しなければシェルに戻ります。
編集中のファイルの再書き込みが失敗した場合、ユーザは
.Ic exit
コマンドによって抜け出すことができます。
.It Ic reply
.Pq Ic r
メッセージリストを引数として取り、メールを指定されたメッセージの差出人
と全ての受取人に送ります。
デフォルトのメッセージは削除されていてはいけません。
.It Ic respond
.Ic reply
と同様です。
.It Ic retain
.Ar retained list
(保持リスト) にヘッダフィールドのリストを追加します。
メッセージを表示する時には、retain list に登録されているヘッダ
フィールドのみがターミナルに表示されます。
他の全てのフィールドは省略されます。
.Ic Type
と
.Ic Print
コマンドを使うとメッセージの全てを表示することができます。
.Ic retain
が引数を指定されずに実行されると、現在 retain list に登録されているフィー
ルドのリストを表示します。
.It Ic save
.Pq Ic s
メッセージのリストとファイル名を引数として取り、各メッセージを順にファ
イルの末尾に追加します。
ファイル名が引用符で囲まれて表示され、それに続いて行数と文字数がユーザ
のターミナルにエコーされます。
.It Ic set
.Pq Ic se
引数がない場合には全ての変数の値を表示します。
引数が指定された場合はオプションをセットします。
引数は
.Ar option=value
( = の前後にはスペースは入りません) か
.Ar option
の形式を取ります。
空白やタブを代入式に含めるために引用符を代入文の どの部分にでも
置いてかまいません。例えば次のようになります。
.Dq Li "set indentprefix=\*q->\*q"
.It Ic saveignore
.Ic saveignore
は
.Ic ignore
コマンドが
.Ic print
や
.Ic type
の際に行なうことを
.Ic save
の際に行なうものです。
これでマークされたヘッダフィールドは
.Ic save
コマンドによって保存される時や自動的に
.Ar mbox
へ保存される時にフィルタリングされて取り除かれます。
.It Ic saveretain
.Ic saveretain
は
.Ic retain
が
.Ic print
や
.Ic type
の際に行なうことを
.Ic save
の際におこなうものです。
.Ic save
コマンドによって保存される時や自動的に
.Ar mbox
へ保存される時には、これでマークされたヘッダフィールドのみが保存されます。
.Ic saveretain
は
.Ic saveignore
に優先します。
.It Ic shell
.Pq Ic sh
シェルを対話モード起動します。
.It Ic size
メッセージのリストを引数として取り、各メッセージのサイズを文字数で表示
します。
.It Ic source
.Ic source
コマンドはファイルからコマンドを読み込みます。
.It Ic top
メッセージのリストを引数として取り、各メッセージの先頭の数行を表示しま
す。
表示する行数は変数
.Ic toplines
によって制御でき、デフォルトでは 5 行となっています。
.It Ic type
.Pq Ic t
.Ic print
と同様です。
.It Ic unalias
.Ic alias
コマンドによって定義された名前のリストを引数として取り、記憶されている
ユーザのグループを無効にします。
グループの名前は以後意味を持たなくなります。
.It Ic undelete
.Pq Ic u
メッセージのリストを引数として取り、各メッセージを削除されて
.Ic いない
ものとしてマークします。
.It Ic unread
.Pq Ic U
メッセージのリストを引数として取り、各メッセージを
.Ic 未読
としてマークします。
.It Ic unset
オプションの名前のリストを引数として取り、それらの記憶されている値を無
効とします。
.Ic set
の逆です。
.It Ic visual
.Pq Ic v
メッセージのリストを引数として取り、各メッセージについてスクリーンエディ
タを起動します。
.It Ic write
.Pq Ic w
.Ic save
と同様ですが、
.Pq Ar ヘッダを除いて
メッセージの本文
.Ic のみ
が保存されます。
メッセージシステムを使ってソースプログラムテキストを送受信するような作
業で非常に便利です。
.It Ic xit
.Pq Ic x
.Ic exit 
と同様です。
.It Ic z
.Nm
は
.Ic headers
コマンドにて説明されているようにウィンドウいっぱいにメッセージヘッダを
表示します。
.Nm
が指し示しているメッセージの位置は
.Ic \&z
コマンドによって次のウィンドウに進めることができます。
また、
.Ic \&z\&\-
コマンドを使って前のウィンドウに戻ることもできます。
.El
.Ss チルダ/エスケープ
.Pp
ここではチルダエスケープを要約します。
チルダエスケープはメッセージを編集している時に特別の機能を実行するため
に使われます。
チルダエスケープは行の先頭でのみ認識されます。
実際のエスケープ文字は
.Ic escape
オプションによってセットできるので、
.Dq Em チルダエスケープ
という呼び方は多少間違ったものです。
.Bl -tag -width Ds
.It Ic \&~! Ns Ar command
指定されたシェルコマンドを実行し、メッセージに戻ります。
.It Ic \&~b Ns Ar name ...
カーボンコピーの受取人のリストへ指定された name を追加します。
ただし name は Cc: 行へは表示されません ("ブラインド" カーボ
ンコピー)。
.It Ic \&~c Ns Ar name ...
指定された name をカーボンコピーの受取人のリストに追加します。
.It Ic \&~d
ホームディレクトリの
.Dq Pa dead.letter
ファイルをメッセージ中に読み込みます。
.It Ic \&~e
今までに編集したメッセージをテキストエディタで開きます。
編集セッションの終了後、メッセージに続けてテキストを追加することができ
ます。
.It Ic \&~f Ns Ar messages
指定されたメッセージを送ろうとしているメッセージ中に読み込みます。
メッセージが指定されない場合は、現在のメッセージを読み込みます。
現在無視されているメッセージヘッダ (
.Ic ignore
か
.Ic retain
コマンドによる) は読み込まれません。
.It Ic \&~F Ns Ar messages
.Ic \&~f
と同様ですが、全てのメッセージヘッダが含まれます。
.It Ic \&~h
メッセージヘッダを順に各々を入力して編集し、テキストを末尾に追加したり、
現在のターミナルの erase 文字や kill 文字を使ってフィールドを変更した
りします。
.It Ic \&~m Ns Ar messages
指定されたメッセージを現在送ろうとしているメッセージの中に読み込み、タ
ブか
.Ar indentprefix
に設定されている値でインデントします。
メッセージが指定されていない場合は現在のメッセージが読み込まれます。
現在無視されているメッセージヘッダ (
.Ic ignore
か
.Ic retain
コマンドによる) は読み込まれません。
.It Ic \&~M Ns Ar messages
.Ic \&~m
と同様ですが、全てのメッセージヘッダが読み込まれます。
.It Ic \&~p
今までに修正したメッセージをメッセージヘッダフィールドと共に表示します。 
.It Ic \&~q
送ろうとしているメッセージを中断し、
.Ic save
がセットされている場合はホームディレクトリの
.Dq Pa dead.letter
にメッセージをセーブします。
.It Ic \&~r Ns Ar filename
指定されたファイルをメッセージに読み込みます。
.It Ic \&~R Ns Ar string
.Ar string
を Reply-To: フィールドとして使用します。
.It Ic \&~s Ns Ar string
指定された文字列を現在のサブジェクトフィールドに設定します。
.It Ic \&~\&t Ns Ar name ...
指定された名前を受取人のリストに追加します。
.It Ic \&~\&v
別のエディタ (
.Ev VISUAL
オプションによって定義されているもの) で現在までに修正したメッセージを
開きます。
通常は別のエディタはスクリーンエディタとなります。
エディタを終了した後、メッセージの末尾にテキストを追加できるようになり
ます。
.It Ic \&~w Ns Ar filename
指定されたファイルにメッセージを書き込みます。
.It Ic \&~\&| Ns Ar command
指定されたコマンドをフィルタとし、パイプを通してメッセージに適用します。
コマンドから何の出力もないか、コマンドが異常終了した場合は、メッセージ
のテキストは元のままとなります。
メッセージを整形するためによく
.Xr fmt 1
コマンドが
.Ic command
として使われます。
.It Ic \&~: Ns Ar mail-command
指定されたメールコマンドを実行します。
しかし全てのコマンドが使えるわけではありません。
.It Ic \&~~ Ns Ar string
メッセージに単独の ~ で始まるテキスト文字列を挿入します。
エスケープ文字が変更されている場合は、それを送るためにはエスケープ文字
を 2 つ指定しなければなりません。
.El
.Ss メールオプション
オプションは
.Ic set
と
.Ic unset
コマンドで制御します。
オプションは 2 値か文字列となります。
2 値の場合はセットされているか、されていないかだけが意味を持ちます。
文字列の場合は実際にセットしている値が意味を持ちます。
2 値のオプションには次のものがあります。
.Bl -tag -width append
.It Ar append
メッセージを
.Ar mbox
にセーブする場合、先頭に書くのではなく、末尾に追加します。
これは常にセットされていなければなりません (システムの
.Pa mail.rc
ファイルにおいて設定することが望ましいです)。
.It Ar ask
.Nm
は送ろうとしている各メッセージのサブジェクトの入力を促します。
改行のみを入力するとサブジェクトフィールドは送られません。
.It Ar askcc
各メッセージの編集後に追加のカーボンコピーの受取人の入力を促します。
現在のリストで十分な場合は改行のみを入力してください。
.It Ar autoprint
.Ic delete
コマンドを
.Ic dp
のように動作させます。
すなわちメッセージの削除後、次のものが自動的に表示されます。
.It Ar debug
2 値のオプション
.Ar debug
をセットするとコマンド行で
.Fl d
を指定した時と同じ動作になり、
.Nm
はデバッグに有用な全ての種類の情報を出力します。
.It Ar dot
2 値のオプション
.Ar dot
をセットすることによって、
.Nm
は行中にピリオドが単独で入力されると、送ろうとしているメッセージが終了した
ものとみなします。
.It Ar hold
このオプションはデフォルトでメッセージをシステムメールボックス中に保持
するために使われます。
.It Ar ignore
ターミナルからの割り込み信号を無視し、@ としてエコーします。
.It Ar ignoreeof
.Ar ignoreeof
は
.Ar dot
に関連するオプションであり、
.Nm
にメッセージの最後での control-d を無視させます。
.Ar Ignoreeof
は
.Nm
のコマンドモード中でも有効となります。
.It Ar metoo
通常、差出人を含むグループの展開時には差出人は取り除かれます。
このオプションをセットすることによって差出人も展開されたグループに含ま
れるようになります。
.It Ar noheader
.Ar noheader
オプションをセットすると、コマンド行で
.Fl N
フラグを指定するのと同様の動作となります。
.It Ar nosave
普通は
.Tn RUBOUT
(erase もしくは delete) を 2 回入力してメッセージの編集を中断する時、
.Nm
はホームディレクトリのファイル
.Dq Pa dead.letter
に中断した手紙をコピーします。
この 2 値のオプション
.Ar nosave
をセットすると、ファイルへのコピーは行なわれません。
.It Ar Replyall
.Ic reply
コマンドと
.Ic Reply
コマンドの意味を逆転させます。
.It Ar quiet
最初に起動された時にバージョンの表示を省略します。
.It Ar searchheaders
このオプションがセットされていると、``/x:y'' の形式でのメッセージリス
トの指定はヘッダフィールド ``x'' 中にサブストリング ``y'' を含む全ての
メッセージに展開されます。ストリングのサーチは大文字と小文字を区別しま
せん。
.It Ar verbose
.Ar verbose
オプションをセットするとコマンド行で
.Fl v
フラグをセットした時と同様の動作となります。
.Nm
が verbose (饒舌) モードで実行されている時、実際のメッセージの配送の様
子がターミナルに表示されます。
.El
.Ss オプションストリング値
.Bl -tag -width Va
.It Ev EDITOR
.Ic edit
コマンドと
.Ic \&~e
エスケープで使われるテキストエディタのパス名です。
定義されていない場合はデフォルトのエディタが使われます。
.It Ev LISTER
.Ic folders
コマンドで使われるディレクトリをリストするコマンドのパス名です。
デフォルトは
.Pa /bin/ls
です。
.It Ev PAGER
.Ic more
コマンドや変数
.Ic crt
がセットされている時に使われるプログラムのパス名です。
このオプションが定義されていないとデフォルトのページャ
.Xr more 1
が使われます。
.It Ev REPLYTO
設定されている場合、送信メッセージの Reply-To フィールドの初期化に使用
されます。
.It Ev SHELL
.Ic !\&
コマンドや
.Ic \&~!
エスケープで使われるシェルのパス名です。
このオプションが定義されていないとデフォルトのシェルが使われます。
.It Ev VISUAL
.Ic visual
コマンドや
.Ic \&~v
エスケープで使われるテキストエディタのパス名です。
.It Va crt
値をとるオプション
.Va crt
は、メッセージを読むために
.Ev PAGER
が使われるメッセージの長さの閾値として使われます。
.Va crt
が値なしでセットされていると、システムに保存されているターミナルの画面
の高さが閾値の計算に使われます (
.Xr stty 1 
を参照して下さい)。
.It Ar escape
これが定義されていると、このオプションの最初のキャラクタがエスケープを 
示すための ~ の代わりに使われます。
.It Ar folder
メッセージのフォルダを置くためのディレクトリ名です。
これが `/' で始まっていると
.Nm
は絶対パスとして解釈します。それ以外の場合はフォルダのディレクトリはホー
ムディレクトリからの相対パスとして扱われます。
.It Ev MBOX
.Ar mbox
の名前です。
これはフォルダの名前とすることもできます。
デフォルトはホームディレクトリの
.Dq Li mbox
となります。
.It Ar record
これが定義されていると、全ての発信されるメールを記録するために使われる
ファイルのパス名となります。
定義されていない場合は、発信メールはセーブされません。
.It Ar indentprefix
チルダエスケープ ``~m'' で、通常のタブ文字 (^I) の代わりにメッセージを
インデントするために使われる文字列となります。
これにスペースやタブが含まれている場合は引用符で囲んで下さい。
.It Ar toplines
これが定義されていると、
.Ic top
コマンドで表示するメッセージの行数となります。通常は先頭の 5 行が表示
されます。
.El
.Sh 環境変数
.Nm
は環境変数
.Ev HOME
と
.Ev USER
を使用します。また、環境変数
.Ev MAIL
がセットされていると、デフォルトの /var/mail の代わりにユーザのメール
ボックスの位置として使われます。
.Sh 関連ファイル
.Bl -tag -width /usr/share/misc/mail.*help -compact
.It Pa /var/mail/*
ポストオフィスです。
.It Pa ~/mbox
ユーザの古いメールです。
.It Pa ~/.mailrc
起動時に実行されるメールコマンドを指定するファイルです。
.It Pa /tmp/R*
一時ファイルです。
.It Pa /usr/share/misc/mail.*help
ヘルプファイルです。
.Pp
.It Pa /usr/share/misc/mail.rc
.It Pa /usr/local/etc/mail.rc
.It Pa /etc/mail.rc
システムの初期化ファイルです。
各ファイルが存在すればこの順に読み込まれます。
.El
.Sh 関連項目
.Xr fmt 1 ,
.Xr newaliases 1 ,
.Xr vacation 1 ,
.Xr aliases 5 ,
.Xr mailaddr 7 ,
.Xr sendmail 8 ,
.Rs
.%T "The Mail Reference Manual"
.Re
.Sh 歴史
.Nm
コマンドは
.At v1
で登場しました。
本マニュアルページは
元々 Kurt Shoens によって書かれた
.%T "The Mail Reference Manual"
をベースにしています。
.Sh バグ
ここに文書化されていないフラグがいくつか存在します。
ほとんどは一般のユーザには役に立たないものです。
.Pp
混乱しやすいのですが、通常
.Nm
は
.Nm Mail
への単なるリンクとなっています。
