MAN1 =	a2p.1\
	addftinfo.1\
	addr2line.1\
	afmtodit.1\
	apply.1\
	apropos.1\
	ar.1\
	as.1\
	at.1\
	basename.1\
	bc.1\
	bdes.1\
	biff.1\
	brandelf.1\
	builtin.1\
	c89.1\
	calendar.1\
	cap_mkdb.1\
	cat.1\
	catman.1\
	cccp.1\
	cdcontrol.1\
	checknr.1\
	chflags.1\
	chgrp.1\
	chio.1\
	chkey.1\
	chmod.1\
	chpass.1\
	ci.1\
	ckdist.1\
	cksum.1\
	cmp.1\
	co.1\
	col.1\
	colcrt.1\
	colldef.1\
	colrm.1\
	column.1\
	comm.1\
	compile_et.1\
	compress.1\
	cp.1\
	cpio.1\
	crontab.1\
	crunchgen.1\
	crunchide.1\
	ctags.1\
	ctm.1\
	ctm_rmail.1\
	cu.1\
	cursor.1\
	cut.1\
	cvs.1\
	date.1\
	dc.1\
	dd.1\
	df.1\
	dialog.1\
	diff.1\
	diff3.1\
	dig.1\
	dnskeygen.1\
	dnsquery.1\
	domainname.1\
	doscmd.1\
	dtmfdecode.1\
	du.1\
	echo.1\
	ed.1\
	ee.1\
	enigma.1\
	eqn.1\
	expand.1\
	expr.1\
	f77.1\
	false.1\
	fdformat.1\
	fdwrite.1\
	fetch.1\
	file.1\
	file2c.1\
	find.1\
	finger.1\
	fmt.1\
	fold.1\
	fontedit.1\
	from.1\
	fstat.1\
	fsync.1\
	ftp.1\
	g711conv.1\
	gasp.1\
	gawk.1\
	gcc.1\
	gcore.1\
	gdb.1\
	gdbserver.1\
	gencat.1\
	getNAME.1\
	getopt.1\
	gperf.1\
	gprof.1\
	grep.1\
	grn.1\
	grodvi.1\
	groff.1\
	grog.1\
	grolbp.1\
	grolj4.1\
	grops.1\
	grotty.1\
	groups.1\
	gzexe.1\
	gzip.1\
	h2ph.1\
	head.1\
	hexdump.1\
	host.1\
	hostname.1\
	hpftodit.1\
	id.1\
	ident.1\
	indent.1\
	indxbib.1\
	info.1\
	install-info.1\
	install.1\
	intro.1\
	ipcrm.1\
	ipcs.1\
	ipftest.1\
	ipnat.1\
	ipresend.1\
	ipsend.1\
	iptest.1\
	join.1\
	jot.1\
	kbdcontrol.1\
	kbdmap.1\
	kcon.1\
	kdump.1\
	kenv.1\
	key.1\
	keyinfo.1\
	keyinit.1\
	keylogin.1\
	keylogout.1\
	kill.1\
	killall.1\
	ktrace.1\
	lam.1\
	last.1\
	lastcomm.1\
	ld.1\
	ldd.1\
	leave.1\
	less.1\
	lesskey.1\
	lex.1\
	limits.1\
	lint.1\
	lkbib.1\
	ln.1\
	loadfont.1\
	locate.1\
	lock.1\
	lockf.1\
	logger.1\
	login.1\
	logname.1\
	look.1\
	lookbib.1\
	lorder.1\
	lp.1\
	lpq.1\
	lpr.1\
	lprm.1\
	lptest.1\
	ls.1\
	lsvfs.1\
	m4.1\
	mail.1\
	mailq.1\
	make.1\
	makeinfo.1\
	makewhatis.1\
	man.1\
	manpath.1\
	mcon.1\
	md5.1\
	merge.1\
	mesg.1\
	minigzip.1\
	mk_cmds.1\
	mkdep.1\
	mkdir.1\
	mkfifo.1\
	mklocale.1\
	mkstr.1\
	mktemp.1\
	mptable.1\
	msgs.1\
	mt.1\
	mv.1\
	ncal.1\
	ncplist.1\
	ncplogin.1\
	ncplogout.1\
	neqn.1\
	netstat.1\
	newaliases.1\
	nfsstat.1\
	nice.1\
	nm.1\
	nohup.1\
	nroff.1\
	objcopy.1\
	objdump.1\
	objformat.1\
	od.1\
	opieinfo.1\
	opiekey.1\
	opiepasswd.1\
	pagesize.1\
	passwd.1\
	paste.1\
	patch.1\
	pawd.1\
	pax.1\
	perl.1\
	pfbtops.1\
	pic.1\
	pim6stat.1\
	pkg_add.1\
	pkg_create.1\
	pkg_delete.1\
	pkg_info.1\
	pkg_sign.1\
	pkg_update.1\
	pkg_version.1\
	pr.1\
	printenv.1\
	printf.1\
	ps.1\
	psroff.1\
	pwd.1\
	quota.1\
	ranlib.1\
	rcp.1\
	rcs.1\
	rcsclean.1\
	rcsdiff.1\
	rcsfreeze.1\
	rcsintro.1\
	rcsmerge.1\
	rdist.1\
	realpath.1\
	refer.1\
	rev.1\
	rlog.1\
	rlogin.1\
	rm.1\
	rmdir.1\
	rpcgen.1\
	rs.1\
	rsh.1\
	rtld.1\
	rtprio.1\
	rup.1\
	ruptime.1\
	rusers.1\
	rwall.1\
	rwho.1\
	s2p.1\
	sasc.1\
	scon.1\
	scp.1\
	script.1\
	sdiff.1\
	sed.1\
	send-pr.1\
	sgsc.1\
	sh.1\
	shar.1\
	size.1\
	skey.1\
	sleep.1\
	sockstat.1\
	soelim.1\
	sort.1\
	split.1\
	ssh-add.1\
	ssh-agent.1\
	ssh-keygen.1\
	ssh.1\
	startslip.1\
	strings.1\
	strip.1\
	stty.1\
	su.1\
	symorder.1\
	systat.1\
	tail.1\
	talk.1\
	tar.1\
	tbl.1\
	tcopy.1\
	tcpdump.1\
	tcpslice.1\
	tcsh.1\
	tee.1\
	telnet.1\
	test.1\
	texindex.1\
	tfmtodit.1\
	tftp.1\
	time.1\
	tip.1\
	top.1\
	touch.1\
	tput.1\
	tr.1\
	troff.1\
	true.1\
	truncate.1\
	truss.1\
	tset.1\
	tsort.1\
	tty.1\
	ul.1\
	uname.1\
	unifdef.1\
	uniq.1\
	units.1\
	unvis.1\
	uptime.1\
	users.1\
	uuconv.1\
	uucp.1\
	uuencode.1\
	uulog.1\
	uuname.1\
	uupick.1\
	uustat.1\
	uuto.1\
	uux.1\
	vacation.1\
	vgrind.1\
	vi.1\
	vidcontrol.1\
	vis.1\
	vt220keys.1\
	vttest.1\
	w.1\
	wall.1\
	wc.1\
	what.1\
	whereis.1\
	which.1\
	who.1\
	whoami.1\
	whois.1\
	window.1\
	write.1\
	xargs.1\
	xstr.1\
	xten.1\
	yacc.1\
	yes.1\
	ypcat.1\
	ypmatch.1\
	ypwhich.1\
	yyfix.1\
	zdiff.1\
	zforce.1\
	zmore.1\
	znew.1

MLINKS= builtin.1 alias.1 builtin.1 alloc.1 builtin.1 bg.1 builtin.1 bindkey.1 \
	builtin.1 break.1 builtin.1 breaksw.1 builtin.1 builtins.1 \
	builtin.1 case.1 builtin.1 cd.1 builtin.1 chdir.1 builtin.1 command.1 \
	builtin.1 complete.1 \
	builtin.1 continue.1 builtin.1 default.1 \
	builtin.1 dirs.1 builtin.1 do.1 builtin.1 done.1 \
	builtin.1 echotc.1 builtin.1 elif.1 builtin.1 else.1 \
	builtin.1 end.1 builtin.1 endif.1 builtin.1 endsw.1 \
	builtin.1 esac.1 builtin.1 eval.1 builtin.1 exec.1 \
	builtin.1 exit.1 builtin.1 export.1 builtin.1 fc.1 \
	builtin.1 fg.1 builtin.1 fi.1 builtin.1 filetest.1 builtin.1 for.1 \
	builtin.1 foreach.1 builtin.1 getopts.1 builtin.1 glob.1 \
	builtin.1 goto.1 builtin.1 hash.1 builtin.1 hashstat.1 \
	builtin.1 history.1 builtin.1 hup.1 builtin.1 if.1 builtin.1 jobid.1 \
	builtin.1 jobs.1 builtin.1 limit.1 builtin.1 log.1 builtin.1 logout.1 \
	builtin.1 ls-F.1 \
	builtin.1 notify.1 builtin.1 onintr.1 builtin.1 popd.1 \
	builtin.1 pushd.1 builtin.1 read.1 builtin.1 readonly.1 \
	builtin.1 rehash.1 \
	builtin.1 repeat.1 builtin.1 sched.1 builtin.1 set.1 \
	builtin.1 setenv.1 builtin.1 settc.1 builtin.1 setty.1 \
	builtin.1 setvar.1 builtin.1 shift.1 builtin.1 source.1 \
	builtin.1 stop.1 builtin.1 suspend.1 builtin.1 switch.1 \
	builtin.1 telltc.1 builtin.1 then.1 builtin.1 trap.1 builtin.1 type.1 \
	builtin.1 ulimit.1 builtin.1 umask.1 builtin.1 unalias.1 \
	builtin.1 uncomplete.1 \
	builtin.1 unhash.1 builtin.1 unlimit.1 builtin.1 unset.1 \
	builtin.1 unsetenv.1 builtin.1 until.1 builtin.1 wait.1 \
	builtin.1 where.1 \
	builtin.1 while.1
MLINKS+=ed.1 red.1
MLINKS+=test.1 '[.1'
MLINKS+=gawk.1 awk.1
MLINKS+=gcc.1 cc.1 
MLINKS+=gcc.1 c++.1
MLINKS+=gcc.1 g++.1
MLINKS+=gcc.1 CC.1
MLINKS+=cccp.1 cpp.1
MLINKS+=grep.1 egrep.1
MLINKS+=grep.1 fgrep.1
MLINKS+=grep.1 zgrep.1
MLINKS+=grep.1 zegrep.1
MLINKS+=grep.1 zfgrep.1
MLINKS+=gzip.1 gunzip.1
MLINKS+=gzip.1 zcat.1
MLINKS+=gzip.1 gzcat.1
MLINKS+=zdiff.1 zcmp.1
MLINKS+=apropos.1 whatis.1
MLINKS+=send-pr.1 sendbug.1
MLINKS+=at.1 batch.1
MLINKS+=at.1 atq.1
MLINKS+=at.1 atrm.1
MLINKS+=basename.1 dirname.1
MLINKS+=chpass.1 chfn.1
MLINKS+=chpass.1 chsh.1
MLINKS+=chpass.1 ypchpass.1
MLINKS+=chpass.1 ypchfn.1
MLINKS+=chpass.1 ypchsh.1
MLINKS+=compress.1 uncompress.1
MLINKS+=ee.1 ree.1
MLINKS+=expand.1 unexpand.1
MLINKS+=ftp.1 pftp.1
MLINKS+=ftp.1 gate-ftp.1
MLINKS+=hexdump.1 hd.1
MLINKS+=intro.1 introduction.1
MLINKS+=less.1 more.1
MLINKS+=lex.1 flex.1
MLINKS+=lex.1 flex++.1
MLINKS+=lex.1 lex++.1
MLINKS+=mail.1 Mail.1
MLINKS+=passwd.1 yppasswd.1
MLINKS+=printenv.1 env.1
MLINKS+=rtld.1 ld-elf.so.1
MLINKS+=tput.1 clear.1
MLINKS+=tset.1 reset.1
MLINKS+=vi.1 ex.1
MLINKS+=vi.1 view.1
MLINKS+=vi.1 nex.1
MLINKS+=vi.1 nview.1
MLINKS+=vi.1 nvi.1
MLINKS+=yacc.1 byacc.1
MLINKS+=ctm_rmail.1 ctm_smail.1
MLINKS+=ctm_rmail.1 ctm_dequeue.1
MLINKS+=kbdmap.1 vidfont.1
MLINKS+=rtprio.1 idprio.1
MLINKS+=cksum.1 sum.1
MLINKS+=ktrace.1 trace.1
MLINKS+=uuencode.1 uudecode.1
MLINKS+=ncal.1 cal.1
MLINKS+=enigma.1 crypt.1
MLINKS+=ln.1 link.1
MLINKS+=rm.1 unlink.1
MLINKS+=opiekey.1 otp-md4.1
MLINKS+=opiekey.1 otp-md5.1
MLINKS+=tcsh.1 csh.1
MLINKS+=ee.1 edit.1
MLINKS+=pkg_sign.1 pkg_check.1
MLINKS+=ssh.1 slogin.1

.include "bsd.prog.mk"
