.ig \"-*- nroff -*-
Copyright (C) 1989-1995 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.\" jpman %Id: pfbtops.1,v 1.2 1997/05/13 16:18:42 horikawa Stab %
.TH PFBTOPS 1 "7 September 1996" "Groff Version 1.15"
.SH 名称
pfbtops \- .pfb フォーマットの PostScript フォントを
ASCII フォーマットに変換する
.SH 書式
.B pfbtops
[
.I pfb_file
]
.SH 解説
.B pfbtops
は、
.B .pfb
フォーマットの PostScript フォントを
ASCII フォーマットに変換します。
.I pfb_file
が省略された場合、標準入力から pfb ファイルを読み込みます。
ASCII フォーマットの PostScript フォントは標準出力に出力されます。
MS-DOS における PostScript フォントは普通
.B pfb
フォーマットで供給されます。
.LP
変換後の ASCII フォーマットの PostScript フォントは
groff で使用することができます。groff で用いる前に
.B /usr/share/groff_font/devps/download 
に登録する必要があります。
.SH 関連項目
.BR grops (1)
