.\" Copyright (c) 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)uname.1	8.3 (Berkeley) 4/8/94
.\" %FreeBSD: src/usr.bin/uname/uname.1,v 1.8 1999/08/28 01:07:03 peter Exp %
.\" jpman %Id: uname.1,v 1.2 1997/03/29 11:54:31 horikawa Stab %
.\"
.Dd April 8, 1994
.Dt UNAME 1
.Os
.Sh 名称
.Nm uname
.Nd システムに関する情報を表示する
.Sh 書式
.Nm
.Op Fl amnprsv
.Sh 解説
.Nm
は、オペレーティングシステム実装の名前を標準出力へ出力します。
オプションがあると、システムの特徴を標準出力へ出力します。
.Pp
オプション:
.Bl -tag -width Ds
.It Fl a
は、
.Fl m ,
.Fl n ,
.Fl r ,
.Fl s ,
.Fl v
をすべて指定した場合と同一です。
.It Fl m
現在のハードウェアプラットフォームのタイプを標準出力に出力します。
.It Fl n
システム名を標準出力に出力します。
.It Fl p
.Fl m
が指定された時と同じ値を出力します。
このオプションは SVR4 への後方互換性のために存在します。
.It Fl r
現在のオペレーティングシステムのリリースレベルを標準出力へ出力します。
.It Fl s
オペレーティングシステム実装の名前を標準出力へ出力します。
.It Fl v
このリリースのオペレーティングシステムにおける
バージョンレベルを標準出力へ出力します。
.El
.Pp
もし
.Fl a
オプションが指定されるか、複数のオプションが指定されれば、
出力はすべて一行にスペースで区切られて表示します。
.Pp
.Nm
は、成功時に 0 を、エラー時は >0 を返します。
.Sh 関連項目
.Xr sysctl 3 ,
.Xr uname 3 ,
.Xr sysctl 8
.Sh 歴史
.Nm
コマンドは
.Bx 4.4
から登場しました。
.Sh 規格
.Nm
コマンドは
.St -p1003.2
準拠であると考えられています。
