.\" Copyright (c) 1999-2000 Sendmail, Inc. and its suppliers.
.\"	All rights reserved.
.\" Copyright (c) 1985, 1987, 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\"
.\" By using this file, you agree to the terms and conditions set
.\" forth in the LICENSE file which can be found at the top level of
.\" the sendmail distribution.
.\"
.\"	%Id: vacation.1,v 8.11.4.6 2000/12/29 18:12:23 gshapiro Exp %
.\"
.\" %FreeBSD: src/contrib/sendmail/vacation/vacation.1,v 1.1.1.1.2.3 2001/02/27 21:09:46 gshapiro Exp %
.\"
.\" $FreeBSD$
.TH VACATION 1 "%Date: 2000/12/29 18:12:23 %"
.SH 名称
.B vacation
\- 不在の通知を返送する
.SH 書式
.B vacation
.RB [ \-i ]
.RB [ \-I ]
.RB [ \-r 
.IR interval ]
.RB [ \-x ]
.RB [ \-a
.IR alias ]
.RB [ \-d ]
.RB [ \-f
.IR database ]
.RB [ \-m
.IR message ]
.RB [ \-s
.IR address ]
.RB [ \-t
.IR time ]
.RB [ \-z ]
.I login
.SH 解説
.B vacation
は、メールの送信者に対して、あなたが現在メールを
読んでいない旨を通知するメッセージを返送します。通常、
.I .forward
ファイルの中で使われます。
例えば、あなたの
.I .forward
ファイルの中で次のように記述します。
.IP
\eeric, "|/usr/bin/vacation -a allman eric"
.PP
これで、あなた自身 (ここではログイン名が eric であるとします)
にメッセージを送るとともに、
``eric''
もしくは
``allman''
に宛てられたメッセージに自動応答します。
.PP
以下のオプションを指定することができます。
.TP
.BI \-a " alias"
.I alias
宛てのメッセージをユーザのログイン名に送られたメールと同様に処理します。
.TP
.B \-d
エラーおよびデバッグのメッセージを、syslog の代りに標準出力へ送ります。
本オプションを使用しない場合、正しくない引数や存在しない
.I login
で
.B vacation
を呼び出す等の致命的なエラーは、
syslog(8)
を使用して、システムログファイルへ記録します。
.TP
.BI \-f " filename"
データベース名として、
.I filename
を
.IR ~/.vacation.db
の代りに使用します。
.I filename
が / で開始しない場合には、~ からの相対となります。
.TP
.B \-i
vacation データベースを初期化します。
これは、
.I .forward
ファイルを変更する前に行なっておく必要があります。
.TP
.B \-I
.B \-i
と同じです
(後方互換性のためにあります)。
.TP
.B \-l
vacation データベースファイルの内容を列挙します。
この情報には、
アドレスと、それぞれのアドレスにおいて最後に自動応答した時刻を含みます。
.TP
.BI \-m " filename"
送信されるメッセージを含むファイルとして、
.I filename
を
.IR ~/.vacation.msg
の代りに使用します。
.I filename
が / で開始しない場合には、~ からの相対となります。
.TP
.BI \-r " interval"
自動応答の間隔を
.I interval
日に設定します。デフォルトは 1 週間です。間隔を
``0''
に設定すると、全てのメッセージに対して自動応答を行ないます。
``infinite''
(実際には数字以外の文字ならなんでも) を設定すると、
同じ送信者には一度しか自動応答を行ないません。
.TP
.BI \-s " address"
受け付けるメールの
.I From 
行にある送信者アドレスの代りに、
.I address
を、vacation メッセージの受信者として使用します。
.TP
.BI \-t " time"
無視されます。
Sun の vacation プログラムとの互換性のためだけに存在します。
.TP
.B \-x
除外リストを標準入力から読み込みます (行毎に 1 アドレス)。
除外リストに含まれるアドレスから届くメールに対しては、
.BR vacation
は返送しません。
除外リストの要素として
``@domain''
を指定することで、ドメイン全体を除外することも可能です。
.TP
.B \-z
vacation メッセージの送信者を、ユーザの代りに
``<>''
にします。
vacation メッセージの送信者を空の逆パスにすることは
standards-track RFC は求めていませんので、RFC 違反となるかもしれません。
.PP
.I login
(もしくは
.B \-a
オプションによって指定された
.I alias
) がメールの
``To:''
もしくは
``Cc:''
ヘッダになければ、自動応答は送られません。また、
``???-REQUEST'',
``???-RELAY'',
``???-OWNER'',
``OWNER-???'',
``Postmaster'',
``UUCP'',
``MAILER'',
``MAILER-DAEMON''
から (大文字、小文字は区別されません) のメールや、
``Precedence: bulk''
や
``Precedence: junk''
の行がヘッダに含まれているメールに対しても自動応答は送られません。
あなたへのメールの送信者のアドレスは
ホームディレクトリの
.Pa .vacation.db
ファイル中で
db(3)
を使用して管理されます。
.PP
.B vacation
ではホームディレクトリに
.I .vacation.msg
ファイルを置くことによって、
あなたへのメールの送信者へのメッセージを指定します。
このファイルは (ヘッダを含む) 完全なメッセージでなければなりません。
以下に例を示します。
.IP
.nf
From: eric@CS.Berkeley.EDU (Eric Allman)
Subject: I am on vacation
Delivered-By-The-Graces-Of: The Vacation program
Precedence: bulk

わたしは 7 月 22 日まで休暇をとっています。緊急の場合は
Keith Bostic <bostic@CS.Berkeley.EDU> に連絡願います。
--eric
.fi 
.PP
.B Vacation

(訳註)返答メッセージに日本語を使う場合には、
漢字コードは JIS (ISO-2022-JP) でなければいけません。
.\" 上記(訳註)は日本語対応のために追加しました。
.\" 2.2.1-RELEASE 対象
.\" by mihara@prd.fc.nec.co.jp (Apr. 4, 1997)
.PP
.B vacation
はメールの送信者を決定するために標準入力の 1 行目の
UNIX
``From''
行を読みます。この
``From''
行は
sendmail(8)
が自答的に付加するものです。
.PP
.B vacation
が不正な引数で呼ばれたり、
.I login
名が存在しないような致命的なエラーはシステムのログファイルに
syslog(8)
を使って記録されます。
.SH 関連ファイル
.TP 1.8i
~/.vacation.db
デフォルトのデータベースファイル
.TP
~/.vacation.msg
デフォルトの送信メッセージ
.SH 関連項目
sendmail(8),
syslogd(8)
.SH 歴史
.B vacation
コマンドは
4.3BSD
から登場しました。
