.\" %FreeBSD: src/usr.sbin/pcvt/vttest/vttest.1,v 1.6 2002/04/20 12:26:52 charnier Exp %
.\"
.\" $FreeBSD$
.Dd January 16, 2001
.Dt VTTEST 1
.Os
.Sh 名称
.Nm vttest
.Nd "VT100 タイプターミナルのテスト"
.Sh 書式
.Nm
.Sh 解説
.Nm
ユーティリティは、
.Tn VT100
ターミナル (またはエミュレータ)
の機能をテストするためにデザインされたプログラムです。
ディスプレイ (エスケープシーケンスの取り扱い)
とキーボードをテストします。
.Pp
プログラムはメニュー方式であり、
十分なオンライン操作指示を含んでいます。
