.\" Copyright (c) 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" the Institute of Electrical and Electronics Engineers, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)wc.1	8.2 (Berkeley) 4/19/94
.\" %FreeBSD: src/usr.bin/wc/wc.1,v 1.6.2.1 2000/06/30 09:51:59 ps Exp %
.\" jpman %Id: wc.1,v 1.2 1997/03/29 20:55:21 iwasaki Stab %
.\"
.Dd April 19, 1994
.Dt WC 1
.Os
.Sh 名称
.Nm wc
.Nd 行数、単語数、バイト数を数える。
.Sh 書式
.Nm wc
.Op Fl clw
.Op Ar
.Sh 解説
.Nm
は各入力ファイル
.Ar file
(デフォルトでは標準入力)
に含まれる行数、単語数、バイト数を数えて標準出力に表示します。
行は改行文字で区切られた文字列、
単語は空白文字で区切られた文字列、と定義されます。
ここで空白文字とは
.Xr isspace 3
が真を返すような文字をいいます。
複数のファイルが指定された場合は、
最後に行数、単語数、バイト数の各項目別の合計も表示します。
.Pp
オプションとしては以下のものがあります。
.Bl -tag -width Ds
.It Fl c
各入力ファイルのバイト数を標準出力に表示します。
.It Fl l
各入力ファイルの行数を標準出力に表示します。
.It Fl w
各入力ファイルの単語数を標準出力に表示します。
.El
.Pp
オプションが指定された場合、
.Nm
は要求された情報のみを表示します。
デフォルトの動作はすべてのオプションが指定された場合と同じです。
.Pp
.Ar file
が指定されなかった場合は、標準入力から読み込まれ、
ファイル名は出力されません。
.Sh 診断
.Nm
は、成功した場合は 0 を、エラーが起きた場合は 0 より大きな値を返します。
.Sh 関連項目
.Xr isspace 3
.Sh 互換性
歴史的には、
.Nm
では単語は「スペース、タブ、改行文字で区切られる最長の文字列」として
定義する、とドキュメントに記述されていました。
しかしこの実装は非表示文字を正しく扱いませんでした。
例えば ``foo^D^Ebar'' を 8 文字と数える一方、``  ^D^E  '' を 6 つの空白と
数えたのでした。4.3BSD 以降の 4BSD では
ドキュメントと矛盾のないよう修正され、
.St -p1003.2
で要求されているように、
.Xr isspace 3
を用いて「単語」を定義するよう実装し直されました。
.Sh 規格
.Nm
は
.St -p1003.2
準拠です。
.Sh 歴史
.Nm
コマンドは
.At v1
から登場しました。
