.\" $FreeBSD$
.TH curs_scroll 3 ""
.SH 名称
\fBscroll\fR, \fBscrl\fR, \fBwscrl\fR - scroll a \fBncurses\fR window
.SH 書式
\fB#include <ncurses.h>\fR

\fBint scroll(WINDOW *win);\fR
.br
\fBint scrl(int n);\fR
.br
\fBint wscrl(WINDOW *win, int n);\fR
.br
.SH 解説
\fBscroll\fR
ルーチンは、ウィンドウを
1
行だけ上方にスクロールします。これには、
ウィンドウデータ構造内の行を移動することが含まれます。ウィンドウの
スクロール領域が画面全体である場合、最適化として、物理画面が同時に
スクロールされます。

\fBscrl\fR
ルーチンと
\fBwscrl\fR
ルーチンでは、
\fIn\fR
が正の場合、ウィンドウを上方に
\fIn\fR
行
スクロールします
(
行
\fIi\fR+\fIn\fR
が
\fIi\fR
になります
)
。そうでない場合、ウィンドウを
下方に
\fIn\fR
行スクロールしますこれにはウィンドウキャラクタイメージ構造内の行を
移動することが含まれます。現在のカーソル位置は変更されません。

これらの関数が機能するためには、
\fBscrollok\fR
でスクロールを有効にする必要があります。
.SH 戻り値
すべてのルーチンが処理失敗すると整数
\fBERR\fR
を返し、処理が正常に完了すると
\fBERR\fR
以外の整数値を返します。
.SH 注釈
\fBscrl\fR
と
\fBscroll\fR
はマクロである可能性があることに注意してください。
.SH 関連項目
\fBncurses\fR(3), \fBcurs_outopts\fR(3)
.\"#
.\"# The following sets edit modes for GNU EMACS
.\"# Local Variables:
.\"# mode:nroff
.\"# fill-column:79
.\"# End:
