.\" @(#)getrpcport.3r	2.2 88/08/02 4.0 RPCSRC; from 1.12 88/02/26 SMI
.\" %FreeBSD: src/lib/libc/rpc/getrpcport.3,v 1.6 1999/08/28 00:00:40 peter Exp %
.\" $FreeBSD$
.\"
.Dd October 6, 1987
.Dt GETRPCPORT 3
.Os
.Sh 名称
.Nm getrpcport
.Nd RPC ポート番号を取得
.Sh 書式
.Ft int
.Fn getrpcport "char *host" "int prognum" "int versnum" "int proto"
.Sh 解説
.Fn getrpcport
関数は、プロトコル
.Fa proto
を使用して
.Fa host
で実行している
RPC
プログラム
.Fa prognum
の、バージョン
.Fa versnum
用ポート番号を返します。
ポートマッパにコンタクトできない場合、または
.Fa prognum
が登録されていなければ
0 が返ります。
.Fa prognum
が登録されていれば、たとえバージョン
.Fa versnum
がなくてもやはりポート番号
(そのプログラムの適当なバージョン用)
が返り、
プログラムの登録が示されます。バージョンの不適合は、サービスの最初の呼び
出しで検出されます。
