# $FreeBSD$

MAN3 =	_secure_path.3\
	abort.3\
	abs.3\
	acos.3\
	acosh.3\
	alarm.3\
	alloca.3\
	arc4random.3\
	asin.3\
	asinh.3\
	assert.3\
	atan.3\
	atan2.3\
	atanh.3\
	atexit.3\
	atof.3\
	atoi.3\
	atol.3\
	bcmp.3\
	bcopy.3\
	bindresvport.3\
	bitstring.3\
	bsearch.3\
	bstring.3\
	btree.3\
	byteorder.3\
	bzero.3\
	calendar.3\
	cam.3\
	cam_cdbparse.3\
	catclose.3\
	catgets.3\
	catopen.3\
	ceil.3\
	clock.3\
	com_err.3\
	confstr.3\
	cos.3\
	cosh.3\
	crypt.3\
	ctermid.3\
	ctime.3\
	ctype.3\
	curs_addch.3\
	curs_addchst.3\
	curs_addstr.3\
	curs_attr.3\
	curs_beep.3\
	curs_bkgd.3\
	curs_border.3\
	curs_clear.3\
	curs_color.3\
	curs_delch.3\
	curs_move.3\
	curs_outopts.3\
	curs_overlay.3\
	curs_pad.3\
	curs_printw.3\
	curs_refresh.3\
	curs_scanw.3\
	curs_scroll.3\
	curs_slk.3\
	curs_touch.3\
	curs_util.3\
	curs_window.3\
	curses.3\
	cuserid.3\
	daemon.3\
	dbopen.3\
	des_crypt.3\
	devname.3\
	devstat.3\
	dialog.3\
	directory.3\
	div.3\
	dladdr.3\
	dlopen.3\
	editline.3\
	end.3\
	erf.3\
	err.3\
	ethers.3\
	exec.3\
	exit.3\
	exp.3\
	fabs.3\
	fclose.3\
	ferror.3\
	fetch.3\
	fflush.3\
	ffs.3\
	fgetln.3\
	fgets.3\
	floor.3\
	fmod.3\
	fnmatch.3\
	fopen.3\
	fpgetround.3\
	fputs.3\
	fread.3\
	frexp.3\
	fseek.3\
	ftime.3\
	ftok.3\
	fts.3\
	funopen.3\
	getbootfile.3\
	getbsize.3\
	getc.3\
	getcap.3\
	getcwd.3\
	getdiskbyname.3\
	getdomainname.3\
	getenv.3\
	getfsent.3\
	getgrent.3\
	getgrouplist.3\
	gethostbyname.3\
	gethostid.3\
	gethostname.3\
	getloadavg.3\
	getmntinfo.3\
	getnetent.3\
	getnetgrent.3\
	getopt.3\
	getpagesize.3\
	getpass.3\
	getprotoent.3\
	getpwent.3\
	getrpcent.3\
	getrpcport.3\
	getservent.3\
	getsubopt.3\
	getttyent.3\
	getusershell.3\
	getvfsbyname.3\
	glob.3\
	hash.3\
	hypot.3\
	ieee.3\
	ieee_test.3\
	index.3\
	inet.3\
	initgroups.3\
	insque.3\
	intro.3\
	isalnum.3\
	isalpha.3\
	isascii.3\
	isblank.3\
	iscntrl.3\
	isdigit.3\
	isgraph.3\
	isinf.3\
	islower.3\
	isprint.3\
	ispunct.3\
	isspace.3\
	isupper.3\
	isxdigit.3\
	j0.3\
	kvm.3\
	kvm_geterr.3\
	kvm_getloadavg.3\
	kvm_getprocs.3\
	kvm_nlist.3\
	kvm_open.3\
	kvm_read.3\
	labs.3\
	ldexp.3\
	ldiv.3\
	lgamma.3\
	libalias.3\
	libdisk.3\
	libradius.3\
	libtacplus.3\
	link_addr.3\
	lockf.3\
	login_auth.3\
	login_cap.3\
	login_class.3\
	login_ok.3\
	login_times.3\
	login_tty.3\
	lsearch.3\
	malloc.3\
	math.3\
	md5.3\
	memccpy.3\
	memchr.3\
	memcmp.3\
	memcpy.3\
	memmove.3\
	memory.3\
	memset.3\
	mktemp.3\
	modf.3\
	moncontrol.3\
	mpool.3\
	multibyte.3\
	ncurses.3\
	nice.3\
	nlist.3\
	pam_authenticate.3\
	pam_chauthtok.3\
	pam_fail_delay.3\
	pam_open_session.3\
	pam_setcred.3\
	pam_start.3\
	pam_strerror.3\
	pause.3\
	pcap.3\
	popen.3\
	printf.3\
	property.3\
	psignal.3\
	pthread.3\
	pthread_cleanup_pop.3\
	pthread_cleanup_push.3\
	pthread_cond_broadcast.3\
	pthread_cond_destroy.3\
	pthread_cond_init.3\
	pthread_cond_signal.3\
	pthread_cond_timedwait.3\
	pthread_cond_wait.3\
	pthread_create.3\
	pthread_detach.3\
	pthread_equal.3\
	pthread_exit.3\
	pthread_getspecific.3\
	pthread_join.3\
	pthread_key_create.3\
	pthread_key_delete.3\
	pthread_mutex_destroy.3\
	pthread_mutex_init.3\
	pthread_mutex_lock.3\
	pthread_mutex_trylock.3\
	pthread_mutex_unlock.3\
	pthread_once.3\
	pthread_rwlock_destroy.3\
	pthread_rwlock_init.3\
	pthread_rwlock_rdlock.3\
	pthread_rwlock_unlock.3\
	pthread_rwlock_wrlock.3\
	pthread_rwlockattr_destroy.3\
	pthread_rwlockattr_getpshared.3\
	pthread_rwlockattr_init.3\
	pthread_rwlockattr_setpshared.3\
	pthread_self.3\
	pthread_setspecific.3\
	pty.3\
	publickey.3\
	putc.3\
	pwcache.3\
	qsort.3\
	queue.3\
	radixsort.3\
	raise.3\
	rand.3\
	rand48.3\
	random.3\
	rcmd.3\
	re_comp.3\
	realpath.3\
	recno.3\
	regex.3\
	remove.3\
	resolver.3\
	rexec.3\
	rindex.3\
	rint.3\
	rpc.3\
	rpc_secure.3\
	rtime.3\
	scandir.3\
	scanf.3\
	setbuf.3\
	setjmp.3\
	setlocale.3\
	setmode.3\
	setproctitle.3\
	setruid.3\
	siginterrupt.3\
	signal.3\
	sigsetops.3\
	sin.3\
	sinh.3\
	skey.3\
	sleep.3\
	sqrt.3\
	stdarg.3\
	stdio.3\
	strcasecmp.3\
	strcat.3\
	strchr.3\
	strcmp.3\
	strcoll.3\
	strcpy.3\
	strcspn.3\
	strdup.3\
	strerror.3\
	strftime.3\
	string.3\
	stringlist.3\
	strlen.3\
	strmode.3\
	strpbrk.3\
	strptime.3\
	strrchr.3\
	strsep.3\
	strspn.3\
	strstr.3\
	strtod.3\
	strtok.3\
	strtol.3\
	strtoul.3\
	strxfrm.3\
	swab.3\
	sysconf.3\
	sysctl.3\
	sysexits.3\
	syslog.3\
	system.3\
	tan.3\
	tanh.3\
	tcgetpgrp.3\
	tcsendbreak.3\
	tcsetattr.3\
	tcsetpgrp.3\
	termcap.3\
	time.3\
	time2posix.3\
	times.3\
	timezone.3\
	tmpnam.3\
	toascii.3\
	tolower.3\
	toupper.3\
	ttyname.3\
	tzset.3\
	ualarm.3\
	uname.3\
	ungetc.3\
	unvis.3\
	usleep.3\
	utime.3\
	uucplock.3\
	valloc.3\
	vgl.3\
	vis.3\
	vlimit.3\
	vtimes.3\
	xdr.3\
	zlib.3

MLINKS= acos.3 acosf.3
MLINKS+= acosh.3 acoshf.3
MLINKS+= addr2ascii.3 ascii2addr.3
MLINKS+= arc4random.3 arc4random_addrandom.3
MLINKS+= arc4random.3 arc4random_stir.3
MLINKS+= asin.3 asinf.3
MLINKS+= asinh.3 asinhf.3
MLINKS+= atan.3 atanf.3
MLINKS+= atan2.3 atan2f.3
MLINKS+= atanh.3 atanhf.3
MLINKS+= auth.3 auth_getval.3
MLINKS+= bitstring.3 bit_alloc.3
MLINKS+= bitstring.3 bit_clear.3
MLINKS+= bitstring.3 bit_decl.3
MLINKS+= bitstring.3 bit_ffs.3
MLINKS+= bitstring.3 bit_nclear.3
MLINKS+= bitstring.3 bit_nset.3
MLINKS+= bitstring.3 bit_set.3
MLINKS+= bitstring.3 bit_test.3
MLINKS+= bitstring.3 bitstr_size.3
MLINKS+= byteorder.3 htonl.3
MLINKS+= byteorder.3 htons.3
MLINKS+= byteorder.3 ntohl.3
MLINKS+= byteorder.3 ntohs.3
MLINKS+= calendar.3 easterg.3
MLINKS+= calendar.3 easterog.3
MLINKS+= calendar.3 easteroj.3
MLINKS+= calendar.3 gdate.3
MLINKS+= calendar.3 jdate.3
MLINKS+= calendar.3 ndaysg.3
MLINKS+= calendar.3 ndaysj.3
MLINKS+= calendar.3 week.3
MLINKS+= calendar.3 weekday.3
MLINKS+= cam.3 cam_close_device.3
MLINKS+= cam.3 cam_close_spec_device.3
MLINKS+= cam.3 cam_device_copy.3
MLINKS+= cam.3 cam_device_dup.3
MLINKS+= cam.3 cam_freeccb.3
MLINKS+= cam.3 cam_get_device.3
MLINKS+= cam.3 cam_getccb.3
MLINKS+= cam.3 cam_open_btl.3
MLINKS+= cam.3 cam_open_device.3
MLINKS+= cam.3 cam_open_pass.3
MLINKS+= cam.3 cam_open_spec_device.3
MLINKS+= cam.3 cam_path_string.3
MLINKS+= cam.3 cam_send_ccb.3
MLINKS+= cam_cdbparse.3 buff_decode.3
MLINKS+= cam_cdbparse.3 buff_decode_visit.3
MLINKS+= cam_cdbparse.3 buff_encode_visit.3
MLINKS+= cam_cdbparse.3 csio_build.3
MLINKS+= cam_cdbparse.3 csio_build_visit.3
MLINKS+= cam_cdbparse.3 csio_decode.3
MLINKS+= cam_cdbparse.3 csio_decode_visit.3
MLINKS+= cam_cdbparse.3 csio_encode.3
MLINKS+= cam_cdbparse.3 csio_encode_visit.3
MLINKS+= ceil.3 ceilf.3
MLINKS+= cipher.3 encrypt.3
MLINKS+= cipher.3 setkey.3
MLINKS+= cipher.3 des_cipher.3
MLINKS+= cipher.3 des_setkey.3
MLINKS+= cos.3 cosf.3
MLINKS+= cosh.3 coshf.3
MLINKS+= crypt.3 des_cipher.3
MLINKS+= crypt.3 des_setkey.3
MLINKS+= crypt.3 encrypt.3
MLINKS+= crypt.3 setkey.3
MLINKS+= ctime.3 asctime.3
MLINKS+= ctime.3 difftime.3
MLINKS+= ctime.3 gmtime.3
MLINKS+= ctime.3 localtime.3
MLINKS+= ctime.3 mktime.3
MLINKS+= ctime.3 timegm.3
MLINKS+= curs_addch.3 addch.3
MLINKS+= curs_addch.3 echochar.3
MLINKS+= curs_addch.3 mvaddch.3
MLINKS+= curs_addch.3 mvwaddch.3
MLINKS+= curs_addch.3 waddch.3
MLINKS+= curs_addch.3 wechochar.3
MLINKS+= curs_addchst.3 addchnstr.3
MLINKS+= curs_addchst.3 addchstr.3
MLINKS+= curs_addchst.3 mvaddchnstr.3
MLINKS+= curs_addchst.3 mvaddchstr.3
MLINKS+= curs_addchst.3 mvwaddchnstr.3
MLINKS+= curs_addchst.3 mvwaddchstr.3
MLINKS+= curs_addchst.3 waddchnstr.3
MLINKS+= curs_addchst.3 waddchstr.3
MLINKS+= curs_addstr.3 addnstr.3
MLINKS+= curs_addstr.3 addstr.3
MLINKS+= curs_addstr.3 mvaddnstr.3
MLINKS+= curs_addstr.3 mvaddstr.3
MLINKS+= curs_addstr.3 mvwaddnstr.3
MLINKS+= curs_addstr.3 mvwaddstr.3
MLINKS+= curs_addstr.3 waddnstr.3
MLINKS+= curs_addstr.3 waddstr.3
MLINKS+= curs_attr.3 attroff.3
MLINKS+= curs_attr.3 attron.3
MLINKS+= curs_attr.3 attrset.3
MLINKS+= curs_attr.3 standend.3
MLINKS+= curs_attr.3 standout.3
MLINKS+= curs_attr.3 wattroff.3
MLINKS+= curs_attr.3 wattron.3
MLINKS+= curs_attr.3 wattrset.3
MLINKS+= curs_attr.3 wstandend.3
MLINKS+= curs_attr.3 wstandout.3
MLINKS+= curs_beep.3 beep.3
MLINKS+= curs_beep.3 flash.3
MLINKS+= curs_bkgd.3 bkgd.3
MLINKS+= curs_bkgd.3 bkgdset.3
MLINKS+= curs_bkgd.3 wbkgd.3
MLINKS+= curs_bkgd.3 wbkgdset.3
MLINKS+= curs_border.3 border.3
MLINKS+= curs_border.3 box.3
MLINKS+= curs_border.3 hline.3
MLINKS+= curs_border.3 vline.3
MLINKS+= curs_border.3 wborder.3
MLINKS+= curs_border.3 whline.3
MLINKS+= curs_border.3 wvline.3
MLINKS+= curs_clear.3 clear.3
MLINKS+= curs_clear.3 clrtobot.3
MLINKS+= curs_clear.3 clrtoeol.3
MLINKS+= curs_clear.3 erase.3
MLINKS+= curs_clear.3 wclear.3
MLINKS+= curs_clear.3 wclrtobot.3
MLINKS+= curs_clear.3 wclrtoeol.3
MLINKS+= curs_clear.3 werase.3
MLINKS+= curs_color.3 can_change_color.3
MLINKS+= curs_color.3 color_content.3
MLINKS+= curs_color.3 has_colors.3
MLINKS+= curs_color.3 init_color.3
MLINKS+= curs_color.3 init_pair.3
MLINKS+= curs_color.3 pair_content.3
MLINKS+= curs_color.3 start_color.3
MLINKS+= curs_delch.3 delch.3
MLINKS+= curs_delch.3 mvdelch.3
MLINKS+= curs_delch.3 mvwdelch.3
MLINKS+= curs_delch.3 wdelch.3
MLINKS+= curs_move.3 move.3
MLINKS+= curs_move.3 wmove.3
MLINKS+= curs_outopts.3 clearok.3
MLINKS+= curs_outopts.3 idcok.3
MLINKS+= curs_outopts.3 idlok.3
MLINKS+= curs_outopts.3 immedok.3
MLINKS+= curs_outopts.3 leaveok.3
MLINKS+= curs_outopts.3 nl.3
MLINKS+= curs_outopts.3 nonl.3
MLINKS+= curs_outopts.3 scrollok.3
MLINKS+= curs_outopts.3 setscrreg.3
MLINKS+= curs_outopts.3 wsetscrreg.3
MLINKS+= curs_overlay.3 copywin.3
MLINKS+= curs_overlay.3 overlay.3
MLINKS+= curs_overlay.3 overwrite.3
MLINKS+= curs_pad.3 newpad.3
MLINKS+= curs_pad.3 pechochar.3
MLINKS+= curs_pad.3 pnoutrefresh.3
MLINKS+= curs_pad.3 prefresh.3
MLINKS+= curs_pad.3 subpad.3
MLINKS+= curs_printw.3 mvprintw.3
MLINKS+= curs_printw.3 mvwprintw.3
MLINKS+= curs_printw.3 printw.3
MLINKS+= curs_printw.3 vwprintw.3
MLINKS+= curs_printw.3 wprintw.3
MLINKS+= curs_refresh.3 doupdate.3
MLINKS+= curs_refresh.3 redrawwin.3
MLINKS+= curs_refresh.3 refresh.3
MLINKS+= curs_refresh.3 wnoutrefresh.3
MLINKS+= curs_refresh.3 wredrawln.3
MLINKS+= curs_refresh.3 wrefresh.3
MLINKS+= curs_scanw.3 mvscanw.3
MLINKS+= curs_scanw.3 mvwscanw.3
MLINKS+= curs_scanw.3 scanw.3
MLINKS+= curs_scanw.3 vwscanw.3
MLINKS+= curs_scanw.3 wscanw.3
MLINKS+= curs_scroll.3 scrl.3
MLINKS+= curs_scroll.3 scroll.3
MLINKS+= curs_scroll.3 wscrl.3
MLINKS+= curs_slk.3 slk_attroff.3
MLINKS+= curs_slk.3 slk_attron.3
MLINKS+= curs_slk.3 slk_attrset.3
MLINKS+= curs_slk.3 slk_clear.3
MLINKS+= curs_slk.3 slk_init.3
MLINKS+= curs_slk.3 slk_label.3
MLINKS+= curs_slk.3 slk_noutrefresh.3
MLINKS+= curs_slk.3 slk_refresh.3
MLINKS+= curs_slk.3 slk_restore.3
MLINKS+= curs_slk.3 slk_set.3
MLINKS+= curs_slk.3 slk_touch.3
MLINKS+= curs_touch.3 is_linetouched.3
MLINKS+= curs_touch.3 is_wintouched.3
MLINKS+= curs_touch.3 touchline.3
MLINKS+= curs_touch.3 touchwin.3
MLINKS+= curs_touch.3 untouchwin.3
MLINKS+= curs_touch.3 wtouchln.3
MLINKS+= curs_util.3 delay_output.3
MLINKS+= curs_util.3 filter.3
MLINKS+= curs_util.3 flushinp.3
MLINKS+= curs_util.3 getwin.3
MLINKS+= curs_util.3 keyname.3
MLINKS+= curs_util.3 putwin.3
MLINKS+= curs_util.3 unctrl.3
MLINKS+= curs_util.3 use_env.3
MLINKS+= curs_window.3 delwin.3
MLINKS+= curs_window.3 derwin.3
MLINKS+= curs_window.3 dupwin.3
MLINKS+= curs_window.3 mvderwin.3
MLINKS+= curs_window.3 mvwin.3
MLINKS+= curs_window.3 newwin.3
MLINKS+= curs_window.3 subwin.3
MLINKS+= curs_window.3 syncok.3
MLINKS+= curs_window.3 wcursyncup.3
MLINKS+= curs_window.3 wsyncdown.3
MLINKS+= curs_window.3 wsyncup.3
MLINKS+= dbopen.3 db.3
MLINKS+= devstat.3 buildmatch.3
MLINKS+= devstat.3 checkversion.3
MLINKS+= devstat.3 compute_etime.3
MLINKS+= devstat.3 compute_stats.3
MLINKS+= devstat.3 getdevs.3
MLINKS+= devstat.3 getgeneration.3
MLINKS+= devstat.3 getnumdevs.3
MLINKS+= devstat.3 getversion.3
MLINKS+= devstat.3 selectdevs.3
MLINKS+= dialog.3 dialog_checklist.3
MLINKS+= dialog.3 dialog_clear.3
MLINKS+= dialog.3 dialog_clear_norefresh.3
MLINKS+= dialog.3 dialog_create_rc.3
MLINKS+= dialog.3 dialog_fselect.3
MLINKS+= dialog.3 dialog_ftree.3
MLINKS+= dialog.3 dialog_gauge.3
MLINKS+= dialog.3 dialog_inputbox.3
MLINKS+= dialog.3 dialog_menu.3
MLINKS+= dialog.3 dialog_mesgbox.3
MLINKS+= dialog.3 dialog_msgbox.3
MLINKS+= dialog.3 dialog_notify.3
MLINKS+= dialog.3 dialog_prgbox.3
MLINKS+= dialog.3 dialog_radiolist.3
MLINKS+= dialog.3 dialog_textbox.3
MLINKS+= dialog.3 dialog_tree.3
MLINKS+= dialog.3 dialog_update.3
MLINKS+= dialog.3 dialog_yesno.3
MLINKS+= dialog.3 draw_box.3
MLINKS+= dialog.3 draw_shadow.3
MLINKS+= dialog.3 end_dialog.3
MLINKS+= dialog.3 get_helpline.3
MLINKS+= dialog.3 init_dialog.3
MLINKS+= dialog.3 line_edit.3
MLINKS+= dialog.3 restore_helpline.3
MLINKS+= dialog.3 strheight.3
MLINKS+= dialog.3 strwidth.3
MLINKS+= dialog.3 use_helpfile.3
MLINKS+= dialog.3 use_helpline.3
MLINKS+= directory.3 closedir.3
MLINKS+= directory.3 dirfd.3
MLINKS+= directory.3 opendir.3
MLINKS+= directory.3 readdir.3
MLINKS+= directory.3 rewinddir.3
MLINKS+= directory.3 seekdir.3
MLINKS+= directory.3 telldir.3
MLINKS+= dlopen.3 dlclose.3
MLINKS+= dlopen.3 dlerror.3
MLINKS+= dlopen.3 dlsym.3
MLINKS+= editline.3 el_deletestr.3
MLINKS+= editline.3 el_end.3
MLINKS+= editline.3 el_getc.3
MLINKS+= editline.3 el_gets.3
MLINKS+= editline.3 el_init.3
MLINKS+= editline.3 el_insertstr.3
MLINKS+= editline.3 el_line.3
MLINKS+= editline.3 el_parse.3
MLINKS+= editline.3 el_push.3
MLINKS+= editline.3 el_reset.3
MLINKS+= editline.3 el_resize.3
MLINKS+= editline.3 el_set.3
MLINKS+= editline.3 el_source.3
MLINKS+= editline.3 history.3
MLINKS+= editline.3 history_end.3
MLINKS+= editline.3 history_init.3
MLINKS+= end.3 edata.3
MLINKS+= end.3 etext.3
MLINKS+= erf.3 erfc.3
MLINKS+= erf.3 erfcf.3
MLINKS+= erf.3 erff.3
MLINKS+= err.3 err_set_exit.3
MLINKS+= err.3 err_set_file.3
MLINKS+= err.3 errx.3
MLINKS+= err.3 verr.3
MLINKS+= err.3 verrx.3
MLINKS+= err.3 vwarn.3
MLINKS+= err.3 vwarnx.3
MLINKS+= err.3 warn.3
MLINKS+= err.3 warnx.3
MLINKS+= ethers.3 ether_aton.3
MLINKS+= ethers.3 ether_hostton.3
MLINKS+= ethers.3 ether_line.3
MLINKS+= ethers.3 ether_ntoa.3
MLINKS+= ethers.3 ether_ntohost.3
MLINKS+= exec.3 execl.3
MLINKS+= exec.3 execle.3
MLINKS+= exec.3 execlp.3
MLINKS+= exec.3 exect.3
MLINKS+= exec.3 execv.3
MLINKS+= exec.3 execvp.3
MLINKS+= exp.3 exp10.3
MLINKS+= exp.3 exp10f.3
MLINKS+= exp.3 exp2.3
MLINKS+= exp.3 exp2f.3
MLINKS+= exp.3 expf.3
MLINKS+= exp.3 expm1.3
MLINKS+= exp.3 expm1f.3
MLINKS+= exp.3 log.3
MLINKS+= exp.3 log10.3
MLINKS+= exp.3 log10f.3
MLINKS+= exp.3 log1p.3
MLINKS+= exp.3 log1pf.3
MLINKS+= exp.3 log2.3
MLINKS+= exp.3 log2f.3
MLINKS+= exp.3 logf.3
MLINKS+= exp.3 pow.3
MLINKS+= exp.3 powf.3
MLINKS+= fabs.3 fabsf.3
MLINKS+= ferror.3 clearerr.3
MLINKS+= ferror.3 feof.3
MLINKS+= ferror.3 fileno.3
MLINKS+= fflush.3 fpurge.3
MLINKS+= fgets.3 gets.3
MLINKS+= floor.3 floorf.3
MLINKS+= fmod.3 fmodf.3
MLINKS+= fopen.3 fdopen.3
MLINKS+= fopen.3 freopen.3
MLINKS+= fpgetround.3 fpgetmask.3
MLINKS+= fpgetround.3 fpgetprec.3
MLINKS+= fpgetround.3 fpgetsticky.3
MLINKS+= fpgetround.3 fpresetsticky.3
MLINKS+= fpgetround.3 fpsetmask.3
MLINKS+= fpgetround.3 fpsetprec.3
MLINKS+= fpgetround.3 fpsetround.3
MLINKS+= fpgetround.3 fpsetsticky.3
MLINKS+= fputs.3 puts.3
MLINKS+= fread.3 fwrite.3
MLINKS+= fseek.3 fgetpos.3
MLINKS+= fseek.3 fsetpos.3
MLINKS+= fseek.3 ftell.3
MLINKS+= fseek.3 rewind.3
MLINKS+= fts.3 fts_children.3
MLINKS+= fts.3 fts_close.3
MLINKS+= fts.3 fts_open.3
MLINKS+= fts.3 fts_read.3
MLINKS+= fts.3 fts_set.3
MLINKS+= funopen.3 fropen.3
MLINKS+= funopen.3 fwopen.3
MLINKS+= getc.3 fgetc.3
MLINKS+= getc.3 getchar.3
MLINKS+= getc.3 getw.3
MLINKS+= getcap.3 cgetcap.3
MLINKS+= getcap.3 cgetclose.3
MLINKS+= getcap.3 cgetent.3
MLINKS+= getcap.3 cgetfirst.3
MLINKS+= getcap.3 cgetmatch.3
MLINKS+= getcap.3 cgetnext.3
MLINKS+= getcap.3 cgetnum.3
MLINKS+= getcap.3 cgetset.3
MLINKS+= getcap.3 cgetstr.3
MLINKS+= getcap.3 cgetustr.3
MLINKS+= getcwd.3 getwd.3
MLINKS+= getdomainname.3 setdomainname.3
MLINKS+= getenv.3 putenv.3
MLINKS+= getenv.3 setenv.3
MLINKS+= getenv.3 unsetenv.3
MLINKS+= getfsent.3 endfsent.3
MLINKS+= getfsent.3 getfsfile.3
MLINKS+= getfsent.3 getfsspec.3
MLINKS+= getfsent.3 getfstype.3
MLINKS+= getfsent.3 setfsent.3
MLINKS+= getgrent.3 endgrent.3
MLINKS+= getgrent.3 getgrgid.3
MLINKS+= getgrent.3 getgrnam.3
MLINKS+= getgrent.3 setgrent.3
MLINKS+= getgrent.3 setgroupent.3
MLINKS+= gethostbyname.3 endhostent.3
MLINKS+= gethostbyname.3 gethostbyaddr.3
MLINKS+= gethostbyname.3 gethostbyname2.3
MLINKS+= gethostbyname.3 gethostent.3
MLINKS+= gethostbyname.3 herror.3
MLINKS+= gethostbyname.3 hstrerror.3
MLINKS+= gethostbyname.3 sethostent.3
MLINKS+= gethostid.3 sethostid.3
MLINKS+= gethostname.3 sethostname.3
MLINKS+= getnetent.3 endnetent.3
MLINKS+= getnetent.3 getnetbyaddr.3
MLINKS+= getnetent.3 getnetbyname.3
MLINKS+= getnetent.3 setnetent.3
MLINKS+= getnetgrent.3 endnetgrent.3
MLINKS+= getnetgrent.3 innetgr.3
MLINKS+= getnetgrent.3 setnetgrent.3
MLINKS+= getprotoent.3 endprotoent.3
MLINKS+= getprotoent.3 getprotobyname.3
MLINKS+= getprotoent.3 getprotobynumber.3
MLINKS+= getprotoent.3 setprotoent.3
MLINKS+= getpwent.3 endpwent.3
MLINKS+= getpwent.3 getpwnam.3
MLINKS+= getpwent.3 getpwuid.3
MLINKS+= getpwent.3 setpassent.3
MLINKS+= getpwent.3 setpwent.3
MLINKS+= getpwent.3 setpwfile.3
MLINKS+= getrpcent.3 endrpcent.3
MLINKS+= getrpcent.3 getrpcbyname.3
MLINKS+= getrpcent.3 getrpcbynumber.3
MLINKS+= getrpcent.3 setrpcent.3
MLINKS+= getservent.3 endservent.3
MLINKS+= getservent.3 getservbyname.3
MLINKS+= getservent.3 getservbyport.3
MLINKS+= getservent.3 setservent.3
MLINKS+= getttyent.3 endttyent.3
MLINKS+= getttyent.3 getttynam.3
MLINKS+= getttyent.3 isdialuptty.3
MLINKS+= getttyent.3 isnettty.3
MLINKS+= getttyent.3 setttyent.3
MLINKS+= getusershell.3 endusershell.3
MLINKS+= getusershell.3 setusershell.3
MLINKS+= getvfsent.3 endvfsent.3
MLINKS+= getvfsent.3 getvfsbytype.3
MLINKS+= getvfsent.3 setvfsent.3
MLINKS+= getvfsent.3 vfsisloadable.3
MLINKS+= getvfsent.3 vfsload.3
MLINKS+= glob.3 globfree.3
MLINKS+= hypot.3 cabs.3
MLINKS+= hypot.3 cabsf.3
MLINKS+= hypot.3 hypotf.3
MLINKS+= ieee.3 copysign.3
MLINKS+= ieee.3 copysignf.3
MLINKS+= ieee.3 finite.3
MLINKS+= ieee.3 finitef.3
MLINKS+= ieee.3 ilogb.3
MLINKS+= ieee.3 ilogbf.3
MLINKS+= ieee.3 nextafter.3
MLINKS+= ieee.3 nextafterf.3
MLINKS+= ieee.3 remainder.3
MLINKS+= ieee.3 remainderf.3
MLINKS+= ieee.3 scalbn.3
MLINKS+= ieee.3 scalbnf.3
MLINKS+= ieee_test.3 logb.3
MLINKS+= ieee_test.3 logbf.3
MLINKS+= ieee_test.3 scalb.3
MLINKS+= ieee_test.3 scalbf.3
MLINKS+= ieee_test.3 significand.3
MLINKS+= ieee_test.3 significandf.3
MLINKS+= inet.3 addr.3
MLINKS+= inet.3 inet_addr.3
MLINKS+= inet.3 inet_aton.3
MLINKS+= inet.3 inet_lnaof.3
MLINKS+= inet.3 inet_makeaddr.3
MLINKS+= inet.3 inet_netof.3
MLINKS+= inet.3 inet_network.3
MLINKS+= inet.3 inet_ntoa.3
MLINKS+= inet.3 network.3
MLINKS+= inet.3 ntoa.3
MLINKS+= insque.3 remque.3
MLINKS+= isinf.3 isnan.3
MLINKS+= j0.3 j0f.3
MLINKS+= j0.3 j1.3
MLINKS+= j0.3 j1f.3
MLINKS+= j0.3 jn.3
MLINKS+= j0.3 jnf.3
MLINKS+= j0.3 y0.3
MLINKS+= j0.3 y0f.3
MLINKS+= j0.3 y1.3
MLINKS+= j0.3 y1f.3
MLINKS+= j0.3 yn.3
MLINKS+= j0.3 ynf.3
MLINKS+= keycap.3 kgetent.3
MLINKS+= keycap.3 kgetflag.3
MLINKS+= keycap.3 kgetnum.3
MLINKS+= keycap.3 kgetstr.3
MLINKS+= kvm_getprocs.3 kvm_getargv.3
MLINKS+= kvm_getprocs.3 kvm_getenvv.3
MLINKS+= kvm_open.3 kvm_close.3
MLINKS+= kvm_open.3 kvm_openfiles.3
MLINKS+= kvm_read.3 kvm_write.3
MLINKS+= lgamma.3 gamma.3
MLINKS+= lgamma.3 gammaf.3
MLINKS+= lgamma.3 lgammaf.3
MLINKS+= libdisk.3 All_FreeBSD.3
MLINKS+= libdisk.3 CheckRules.3
MLINKS+= libdisk.3 ChunkCanBeRoot.3
MLINKS+= libdisk.3 Clone_Disk.3
MLINKS+= libdisk.3 Collapse_Chunk.3
MLINKS+= libdisk.3 Collapse_Disk.3
MLINKS+= libdisk.3 Create_Chunk.3
MLINKS+= libdisk.3 Create_Chunk_DWIM.3
MLINKS+= libdisk.3 Cyl_Aligned.3
MLINKS+= libdisk.3 Debug_Disk.3
MLINKS+= libdisk.3 Delete_Chunk.3
MLINKS+= libdisk.3 Disk_Names.3
MLINKS+= libdisk.3 Free_Disk.3
MLINKS+= libdisk.3 MakeDev.3
MLINKS+= libdisk.3 MakeDevDisk.3
MLINKS+= libdisk.3 Next_Cyl_Aligned.3
MLINKS+= libdisk.3 Next_Track_Aligned.3
MLINKS+= libdisk.3 Open_Disk.3
MLINKS+= libdisk.3 Prev_Cyl_Aligned.3
MLINKS+= libdisk.3 Prev_Track_Aligned.3
MLINKS+= libdisk.3 Set_Bios_Geom.3
MLINKS+= libdisk.3 Set_Boot_Blocks.3
MLINKS+= libdisk.3 Set_Boot_Mgr.3
MLINKS+= libdisk.3 ShowChunkFlags.3
MLINKS+= libdisk.3 Track_Aligned.3
MLINKS+= libdisk.3 Write_Disk.3
MLINKS+= libdisk.3 slice_type_name.3
MLINKS+= link_addr.3 link_ntoa.3
MLINKS+= link_addr.3 linkaddr.3
MLINKS+= login_cap.3 login_close.3
MLINKS+= login_cap.3 login_getcapbool.3
MLINKS+= login_cap.3 login_getcaplist.3
MLINKS+= login_cap.3 login_getcapnum.3
MLINKS+= login_cap.3 login_getcapsize.3
MLINKS+= login_cap.3 login_getcapstr.3
MLINKS+= login_cap.3 login_getcaptime.3
MLINKS+= login_cap.3 login_getclass.3
MLINKS+= login_cap.3 login_getclassbyname.3
MLINKS+= login_cap.3 login_getpath.3
MLINKS+= login_cap.3 login_getstyle.3
MLINKS+= login_cap.3 login_getuserclass.3
MLINKS+= login_class.3 setclasscontext.3
MLINKS+= login_class.3 setclassenvironment.3
MLINKS+= login_class.3 setclassresources.3
MLINKS+= login_class.3 setusercontext.3
MLINKS+= login_ok.3 auth_hostok.3
MLINKS+= login_ok.3 auth_timeok.3
MLINKS+= login_ok.3 auth_ttyok.3
MLINKS+= login_times.3 in_lt.3
MLINKS+= login_times.3 in_ltm.3
MLINKS+= login_times.3 in_ltms.3
MLINKS+= login_times.3 in_lts.3
MLINKS+= login_times.3 parse_lt.3
MLINKS+= lsearch.3 lfind.3
MLINKS+= malloc.3 calloc.3
MLINKS+= malloc.3 free.3
MLINKS+= malloc.3 realloc.3
MLINKS+= malloc.3 reallocf.3
MLINKS+= mbrune.3 mbmb.3
MLINKS+= mbrune.3 mbrrune.3
MLINKS+= md2.3 MD2Data.3
MLINKS+= md2.3 MD2End.3
MLINKS+= md2.3 MD2File.3
MLINKS+= md2.3 MD2Final.3
MLINKS+= md2.3 MD2Init.3
MLINKS+= md2.3 MD2Update.3
MLINKS+= md4.3 MD4Data.3
MLINKS+= md4.3 MD4End.3
MLINKS+= md4.3 MD4File.3
MLINKS+= md4.3 MD4Final.3
MLINKS+= md4.3 MD4Init.3
MLINKS+= md4.3 MD4Update.3
MLINKS+= md5.3 MD5Data.3
MLINKS+= md5.3 MD5End.3
MLINKS+= md5.3 MD5File.3
MLINKS+= md5.3 MD5Final.3
MLINKS+= md5.3 MD5Init.3
MLINKS+= md5.3 MD5Update.3
MLINKS+= mktemp.3 mkdtemp.3
MLINKS+= mktemp.3 mkstemp.3
MLINKS+= moncontrol.3 monstartup.3
MLINKS+= multibyte.3 mblen.3
MLINKS+= multibyte.3 mbstowcs.3
MLINKS+= multibyte.3 mbtowc.3
MLINKS+= multibyte.3 wcstombs.3
MLINKS+= multibyte.3 wctomb.3
MLINKS+= pam_open_session.3 pam_close_session.3
MLINKS+= pam_start.3 pam_end.3
MLINKS+= popen.3 pclose.3
MLINKS+= printf.3 asprintf.3
MLINKS+= printf.3 fprintf.3
MLINKS+= printf.3 snprintf.3
MLINKS+= printf.3 sprintf.3
MLINKS+= printf.3 vasprintf.3
MLINKS+= printf.3 vfprintf.3
MLINKS+= printf.3 vprintf.3
MLINKS+= printf.3 vsnprintf.3
MLINKS+= printf.3 vsprintf.3
MLINKS+= property.3 properties_free.3
MLINKS+= property.3 properties_read.3
MLINKS+= property.3 property_find.3
MLINKS+= psignal.3 sys_siglist.3
MLINKS+= psignal.3 sys_signame.3
MLINKS+= pty.3 forkpty.3
MLINKS+= pty.3 openpty.3
MLINKS+= putc.3 fputc.3
MLINKS+= putc.3 putchar.3
MLINKS+= putc.3 putw.3
MLINKS+= pwcache.3 group_from_gid.3
MLINKS+= pwcache.3 user_from_uid.3
MLINKS+= qsort.3 heapsort.3
MLINKS+= qsort.3 mergesort.3
MLINKS+= queue.3 CIRCLEQ_ENTRY.3
MLINKS+= queue.3 CIRCLEQ_HEAD.3
MLINKS+= queue.3 CIRCLEQ_INIT.3
MLINKS+= queue.3 CIRCLEQ_INSERT_AFTER.3
MLINKS+= queue.3 CIRCLEQ_INSERT_BEFORE.3
MLINKS+= queue.3 CIRCLEQ_INSERT_HEAD.3
MLINKS+= queue.3 CIRCLEQ_INSERT_TAIL.3
MLINKS+= queue.3 CIRCLEQ_REMOVE.3
MLINKS+= queue.3 LIST_ENTRY.3
MLINKS+= queue.3 LIST_HEAD.3
MLINKS+= queue.3 LIST_INIT.3
MLINKS+= queue.3 LIST_INSERT_AFTER.3
MLINKS+= queue.3 LIST_INSERT_BEFORE.3
MLINKS+= queue.3 LIST_INSERT_HEAD.3
MLINKS+= queue.3 LIST_REMOVE.3
MLINKS+= queue.3 SLIST_ENTRY.3
MLINKS+= queue.3 SLIST_HEAD.3
MLINKS+= queue.3 SLIST_INIT.3
MLINKS+= queue.3 SLIST_INSERT_AFTER.3
MLINKS+= queue.3 SLIST_INSERT_HEAD.3
MLINKS+= queue.3 SLIST_REMOVE.3
MLINKS+= queue.3 SLIST_REMOVE_HEAD.3
MLINKS+= queue.3 STAILQ_ENTRY.3
MLINKS+= queue.3 STAILQ_HEAD.3
MLINKS+= queue.3 STAILQ_INIT.3
MLINKS+= queue.3 STAILQ_INSERT_AFTER.3
MLINKS+= queue.3 STAILQ_INSERT_HEAD.3
MLINKS+= queue.3 STAILQ_INSERT_TAIL.3
MLINKS+= queue.3 STAILQ_REMOVE.3
MLINKS+= queue.3 STAILQ_REMOVE_HEAD.3
MLINKS+= queue.3 TAILQ_EMPTY.3
MLINKS+= queue.3 TAILQ_ENTRY.3
MLINKS+= queue.3 TAILQ_FIRST.3
MLINKS+= queue.3 TAILQ_HEAD.3
MLINKS+= queue.3 TAILQ_INIT.3
MLINKS+= queue.3 TAILQ_INSERT_AFTER.3
MLINKS+= queue.3 TAILQ_INSERT_BEFORE.3
MLINKS+= queue.3 TAILQ_INSERT_HEAD.3
MLINKS+= queue.3 TAILQ_INSERT_TAIL.3
MLINKS+= queue.3 TAILQ_LAST.3
MLINKS+= queue.3 TAILQ_NEXT.3
MLINKS+= queue.3 TAILQ_REMOVE.3
MLINKS+= rand.3 srand.3
MLINKS+= rand48.3 _rand48.3
MLINKS+= rand48.3 drand48.3
MLINKS+= rand48.3 erand48.3
MLINKS+= rand48.3 jrand48.3
MLINKS+= rand48.3 lcong48.3
MLINKS+= rand48.3 lrand48.3
MLINKS+= rand48.3 mrand48.3
MLINKS+= rand48.3 nrand48.3
MLINKS+= rand48.3 seed48.3
MLINKS+= rand48.3 srand48.3
MLINKS+= random.3 initstate.3
MLINKS+= random.3 setstate.3
MLINKS+= random.3 srandom.3
MLINKS+= random.3 srandomdev.3
MLINKS+= rcmd.3 iruserok.3
MLINKS+= rcmd.3 rresvport.3
MLINKS+= rcmd.3 ruserok.3
MLINKS+= re_comp.3 re_exec.3
MLINKS+= regex.3 regcomp.3
MLINKS+= regex.3 regerror.3
MLINKS+= regex.3 regexec.3
MLINKS+= regex.3 regfree.3
MLINKS+= regexp.3 regsub.3
MLINKS+= resolver.3 dn_comp.3
MLINKS+= resolver.3 dn_expand.3
MLINKS+= resolver.3 res_init.3
MLINKS+= resolver.3 res_mkquery.3
MLINKS+= resolver.3 res_query.3
MLINKS+= resolver.3 res_search.3
MLINKS+= resolver.3 res_send.3
MLINKS+= rint.3 rintf.3
MLINKS+= rpc.3 auth_destroy.3
MLINKS+= rpc.3 authnone_create.3
MLINKS+= rpc.3 authunix_create.3
MLINKS+= rpc.3 authunix_create_default.3
MLINKS+= rpc.3 callrpc.3
MLINKS+= rpc.3 clnt_broadcast.3
MLINKS+= rpc.3 clnt_call.3
MLINKS+= rpc.3 clnt_control.3
MLINKS+= rpc.3 clnt_create.3
MLINKS+= rpc.3 clnt_destroy.3
MLINKS+= rpc.3 clnt_freeres.3
MLINKS+= rpc.3 clnt_geterr.3
MLINKS+= rpc.3 clnt_pcreateerror.3
MLINKS+= rpc.3 clnt_perrno.3
MLINKS+= rpc.3 clnt_perror.3
MLINKS+= rpc.3 clnt_spcreateerror.3
MLINKS+= rpc.3 clnt_sperrno.3
MLINKS+= rpc.3 clnt_sperror.3
MLINKS+= rpc.3 clntraw_create.3
MLINKS+= rpc.3 clnttcp_create.3
MLINKS+= rpc.3 clntudp_bufcreate.3
MLINKS+= rpc.3 clntudp_create.3
MLINKS+= rpc.3 get_myaddress.3
MLINKS+= rpc.3 pmap_getmaps.3
MLINKS+= rpc.3 pmap_getport.3
MLINKS+= rpc.3 pmap_rmtcall.3
MLINKS+= rpc.3 pmap_set.3
MLINKS+= rpc.3 pmap_unset.3
MLINKS+= rpc.3 regsterrpc.3
MLINKS+= rpc.3 rpc_createerr.3
MLINKS+= rpc.3 svc_destroy.3
MLINKS+= rpc.3 svc_fds.3
MLINKS+= rpc.3 svc_fdset.3
MLINKS+= rpc.3 svc_getargs.3
MLINKS+= rpc.3 svc_getcaller.3
MLINKS+= rpc.3 svc_getreg.3
MLINKS+= rpc.3 svc_getregset.3
MLINKS+= rpc.3 svc_register.3
MLINKS+= rpc.3 svc_run.3
MLINKS+= rpc.3 svc_sendreply.3
MLINKS+= rpc.3 svc_unregister.3
MLINKS+= rpc.3 svcerr_auth.3
MLINKS+= rpc.3 svcerr_decode.3
MLINKS+= rpc.3 svcerr_noproc.3
MLINKS+= rpc.3 svcerr_noprog.3
MLINKS+= rpc.3 svcerr_progvers.3
MLINKS+= rpc.3 svcerr_systemerr.3
MLINKS+= rpc.3 svcerr_weakauth.3
MLINKS+= rpc.3 svcfd_create.3
MLINKS+= rpc.3 svcraw_create.3
MLINKS+= rpc.3 svctcp_create.3
MLINKS+= rpc.3 svcudp_bufcreate.3
MLINKS+= rpc.3 xdr_accepted_reply.3
MLINKS+= rpc.3 xdr_authunix_parms.3
MLINKS+= rpc.3 xdr_callhdr.3
MLINKS+= rpc.3 xdr_callmsg.3
MLINKS+= rpc.3 xdr_opaque_auth.3
MLINKS+= rpc.3 xdr_pmap.3
MLINKS+= rpc.3 xdr_pmaplist.3
MLINKS+= rpc.3 xdr_rejected_reply.3
MLINKS+= rpc.3 xdr_replymsg.3
MLINKS+= rpc.3 xprt_register.3
MLINKS+= rpc.3 xprt_unregister.3
MLINKS+= rune.3 fgetrune.3
MLINKS+= rune.3 fputrune.3
MLINKS+= rune.3 fungetrune.3
MLINKS+= rune.3 setinvalidrune.3
MLINKS+= rune.3 setrunelocale.3
MLINKS+= rune.3 sgetrune.3
MLINKS+= rune.3 sputrune.3
MLINKS+= scandir.3 alphasort.3
MLINKS+= scanf.3 fscanf.3
MLINKS+= scanf.3 sscanf.3
MLINKS+= scanf.3 vfscanf.3
MLINKS+= scanf.3 vscanf.3
MLINKS+= scanf.3 vsscanf.3
MLINKS+= setbuf.3 setbuffer.3
MLINKS+= setbuf.3 setlinebuf.3
MLINKS+= setbuf.3 setvbuf.3
MLINKS+= setjmp.3 _longjmp.3
MLINKS+= setjmp.3 _setjmp.3
MLINKS+= setjmp.3 longjmp.3
MLINKS+= setjmp.3 longjmperr.3
MLINKS+= setjmp.3 longjmperror.3
MLINKS+= setjmp.3 siglongjmp.3
MLINKS+= setjmp.3 sigsetjmp.3
MLINKS+= setlocale.3 localeconv.3
MLINKS+= setmode.3 getmode.3
MLINKS+= setruid.3 setrgid.3
MLINKS+= sigsetops.3 sigaddset.3
MLINKS+= sigsetops.3 sigdelset.3
MLINKS+= sigsetops.3 sigemptyset.3
MLINKS+= sigsetops.3 sigfillset.3
MLINKS+= sigsetops.3 sigismember.3
MLINKS+= sin.3 sinf.3
MLINKS+= sinh.3 sinhf.3
MLINKS+= skey.3 skey_crypt.3
MLINKS+= skey.3 skey_getpass.3
MLINKS+= skey.3 skeyaccess.3
MLINKS+= skey.3 skeychallenge.3
MLINKS+= skey.3 skeyinfo.3
MLINKS+= skey.3 skeylookup.3
MLINKS+= skey.3 skeyverify.3
MLINKS+= sqrt.3 cbrt.3
MLINKS+= sqrt.3 cbrtf.3
MLINKS+= sqrt.3 sqrtf.3
MLINKS+= stdarg.3 va_arg.3
MLINKS+= stdarg.3 va_end.3
MLINKS+= stdarg.3 va_start.3
MLINKS+= stdarg.3 varargs.3
MLINKS+= strcasecmp.3 strncasecmp.3
MLINKS+= strcat.3 strncat.3
MLINKS+= strcmp.3 strncmp.3
MLINKS+= strcpy.3 strncpy.3
MLINKS+= strerror.3 perror.3
MLINKS+= strerror.3 sys_errlist.3
MLINKS+= strerror.3 sys_nerr.3
MLINKS+= strtok.3 strtok_r.3
MLINKS+= strtol.3 strtoq.3
MLINKS+= strtoul.3 strtouq.3
MLINKS+= stty.3 gtty.3
MLINKS+= sysctl.3 sysctlbyname.3
MLINKS+= syslog.3 closelog.3
MLINKS+= syslog.3 openlog.3
MLINKS+= syslog.3 setlogmask.3
MLINKS+= syslog.3 vsyslog.3
MLINKS+= tan.3 tanf.3
MLINKS+= tanh.3 tanhf.3
MLINKS+= tcsendbreak.3 tcdrain.3
MLINKS+= tcsendbreak.3 tcflow.3
MLINKS+= tcsendbreak.3 tcflush.3
MLINKS+= tcsetattr.3 cfgetispeed.3
MLINKS+= tcsetattr.3 cfgetospeed.3
MLINKS+= tcsetattr.3 cfmakeraw.3
MLINKS+= tcsetattr.3 cfsetispeed.3
MLINKS+= tcsetattr.3 cfsetospeed.3
MLINKS+= tcsetattr.3 cfsetspeed.3
MLINKS+= tcsetattr.3 tcgetattr.3
MLINKS+= termcap.3 __set_ospeed.3
MLINKS+= termcap.3 tgetent.3
MLINKS+= termcap.3 tgetflag.3
MLINKS+= termcap.3 tgetnum.3
MLINKS+= termcap.3 tgetstr.3
MLINKS+= termcap.3 tgoto.3
MLINKS+= termcap.3 tparm.3
MLINKS+= termcap.3 tputs.3
MLINKS+= time2posix.3 posix2time.3
MLINKS+= tmpnam.3 tempnam.3
MLINKS+= tmpnam.3 tmpfile.3
MLINKS+= ttyname.3 isatty.3
MLINKS+= ttyname.3 ttyslot.3
MLINKS+= tzset.3 tzsetwall.3
MLINKS+= unvis.3 strunvis.3
MLINKS+= uucplock.3 uu_lock.3
MLINKS+= uucplock.3 uu_lock_txfr.3
MLINKS+= uucplock.3 uu_lockerr.3
MLINKS+= uucplock.3 uu_unlock.3
MLINKS+= vis.3 strvis.3
MLINKS+= vis.3 strvisx.3
MLINKS+= xdr.3 xdr_array.3
MLINKS+= xdr.3 xdr_bool.3
MLINKS+= xdr.3 xdr_bytes.3
MLINKS+= xdr.3 xdr_char.3
MLINKS+= xdr.3 xdr_destroy.3
MLINKS+= xdr.3 xdr_double.3
MLINKS+= xdr.3 xdr_enum.3
MLINKS+= xdr.3 xdr_float.3
MLINKS+= xdr.3 xdr_free.3
MLINKS+= xdr.3 xdr_getpos.3
MLINKS+= xdr.3 xdr_inline.3
MLINKS+= xdr.3 xdr_int.3
MLINKS+= xdr.3 xdr_long.3
MLINKS+= xdr.3 xdr_opaque.3
MLINKS+= xdr.3 xdr_pointer.3
MLINKS+= xdr.3 xdr_reference.3
MLINKS+= xdr.3 xdr_setpos.3
MLINKS+= xdr.3 xdr_short.3
MLINKS+= xdr.3 xdr_string.3
MLINKS+= xdr.3 xdr_u_char.3
MLINKS+= xdr.3 xdr_u_long.3
MLINKS+= xdr.3 xdr_u_short.3
MLINKS+= xdr.3 xdr_union.3
MLINKS+= xdr.3 xdr_vector.3
MLINKS+= xdr.3 xdr_void.3
MLINKS+= xdr.3 xdr_wrapstring.3
MLINKS+= xdr.3 xdrmem_create.3
MLINKS+= xdr.3 xdrrec_create.3
MLINKS+= xdr.3 xdrrec_endofrecord.3
MLINKS+= xdr.3 xdrrec_eof.3
MLINKS+= xdr.3 xdrrec_skiprecord.3
MLINKS+= xdr.3 xdrstdio_create.3

.include "bsd.prog.mk"
