.\" Hey Emacs! This file is -*- nroff -*- source.
.\" $Id: pam_authenticate.3,v 1.1.1.1 1999-12-09 16:25:59 kuriyama Exp $
.\" Copyright (c) Andrew G. Morgan 1996-7 <morgan@parc.power.net>
.TH PAM_AUTHENTICATE 3 "1996 Dec 9" "PAM 0.55" "App. Programmers' Manual"
.SH 名称

pam_authenticate \- ユーザの認証

.SH 書式
.B #include <security/pam_appl.h>
.sp
.BI "int pam_authenticate(pam_handle_t " *pamh ", int  " flags ");"
.sp 2
.SH 解説
.B pam_authenticate

.br
この関数を使用すると、申請ユーザを認証できます。この関数は、
.BR PAM
で認証モジュールに
.I ダイナミックに
リンクされており、
この認証モジュールが認証を行ないます。
アプリケーションが認証の本質に関わることはありません。

.br
認証が問題なく終了すると、認証されたユーザの
.BR 名前
が
.BR PAM
アイテム
.BR PAM_USER
に入ります。
このアイテムは、
.BR pam_get_item "(3)"
を呼び出して取得できます。

.br
アプリケーション開発者は、認証モジュールが対話メカニズム(
.BR pam_start "(3)"
参照)
でユーザにユーザ名を入力させることがあることに注意する必要があります。
この場合は、ユーザプロンプトストリングを
.BR PAM_USER_PROMPT
アイテム(
.BR pam_set_item "(3)"
参照)
で設定できます。

.SH 戻り値
問題がない場合は
.BR PAM_SUCCESS
が戻されます。その他の値が戻された場合は、
認証で問題が発生したとみなされ、以前に呼び出した
.BR pam_fail_delay "(3)"
で指定された値だけ
.I 遅延
が発生します。
とくに注意が必要なエラーは以下のとおりです。
.TP
.B PAM_ABORT
アプリケーションをすぐに終了する必要があります。もちろん最初に
.BR pam_end "(3)"
を呼び出してください。

.TP
.B PAM_MAXTRIES
アプリケーションがユーザの認証を何度も繰り返しています。
認証を止めてください。

.SH エラー
.BR pam_strerror "(3)"
でテキストに変換できます。

.SH 準拠
DCE-RFC 86.0, October 1995.

.SH バグ
.sp 2
見つかっていません。

.SH 関連項目
.BR pam_start "(3), "
.BR pam_get_item "(3), "
.BR pam_fail_delay "(3), "
.BR pam_strerror "(3)"

.BR システム管理者
、
.BR モジュール開発者
、
.BR アプリケーション開発者
用の
.BR PAM
ガイドも参照してください。
