.\" @(#)publickey.3r	2.1 88/08/07 4.0 RPCSRC
.TH PUBLICKEY 3R  "6 October 1987"
.SH 名称
publickey, getpublickey, getsecretkey \- 公開鍵か秘密鍵の入手
.SH 書式
.nf
.B #include <rpc/rpc.h>
.B #include <rpc/key_prot.h>
.LP
.B getpublickey(netname, publickey)
.B	char netname[\s-1MAXNETNAMELEN\s0+1];
.B	char publickey[\s-1HEXKEYBYTES\s0+1];
.LP
.B getsecretkey(netname, secretkey, passwd)
.B	char netname[\s-1MAXNETNAMELEN\s0+1];
.B	char secretkey[\s-1HEXKEYBYTES\s0+1];
.B	char *passwd;
.fi
.SH 解説
.IX "getpublickey function" "" "\fLgetpublickey()\fP function"
.IX "getsecretkey function" "" "\fLgetsecretkey()\fP function"
このルーチンでは、公開鍵と秘密鍵を
.SM YP
データベースから入手します。
.B getsecretkey(\|)
には
.I passwd
という引数があり、データベースに保存されている、
暗号化された秘密鍵の復号化に使用されます。どちらのルーチンも、鍵が
見つかると 1 を戻し、見つからないと 0 を戻します。
鍵は、
.SM NULL
で終わる 16 進文字列として戻されます。
.B getsecretkey(\|)
に指定されたパスワードで秘密鍵を復号化できない場合は 1 が戻されますが、
.I secretkey
引数は
.SM NULL
文字列 (``'') になります。
.SH 関連項目
.BR publickey (5)
.LP
.TX NETP
の
.I \s-1RPC\s0 Programmer's Manual
