.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)setruid.3	8.1 (Berkeley) 6/2/93
.\" %FreeBSD: src/lib/libc/compat-43/setruid.3,v 1.5.2.5 2001/12/14 18:33:49 ru Exp %
.\"
.\" $FreeBSD$
.Dd June 2, 1993
.Dt SETRUID 3
.Os
.Sh 名称
.Nm setruid ,
.Nm setrgid
.Nd ユーザとグループ ID を設定する
.Sh ライブラリ
.Lb libc
.Sh 書式
.In unistd.h
.Ft int
.Fn setruid "uid_t ruid"
.Ft int
.Fn setrgid "gid_t rgid"
.Sh 解説
.Fn setruid
関数
.Pq Fn setrgid
は、現在のプロセスの実際のユーザ ID (グループ ID) を
設定します。
.Sh 戻り値
.Rv -std
.Sh エラー
関数は次の場合に失敗します:
.Bl -tag -width Er
.It Bq Er EPERM
ユーザがスーパユーザでなく、
指定された ID が実 ID でも実効 ID でもありませんでした。
.El
.Sh 互換性
これらの呼び出しの使用は移植可能ではありません。
これらを使用するのはお勧めできません。将来除去される予定だからです。
.Sh 関連項目
.Xr getgid 2 ,
.Xr getuid 2 ,
.Xr setegid 2 ,
.Xr seteuid 2 ,
.Xr setgid 2 ,
.Xr setuid 2
.Sh 歴史
.Fn setruid
と
.Fn setrgid
システムコールは
.Bx 4.2
で現れ、
.Bx 4.4
で落とされました。
