# $FreeBSD: doc/ja_JP.eucJP/books/Makefile,v 1.5 1999/09/06 06:53:19 peter Exp $

SUBDIR = faq
SUBDIR+= handbook
SUBDIR+= ppp-primer

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
