# $FreeBSD: doc/ja_JP.eucJP/books/Makefile,v 1.6 2000/02/20 02:16:51 motoyuki Exp $

SUBDIR = faq
SUBDIR+= handbook
SUBDIR+= ppp-primer
SUBDIR+= porters-handbook

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
