# $FreeBSD: doc/ja_JP.eucJP/books/Makefile,v 1.7 2000/07/16 20:32:31 hrs Exp $

#SUBDIR = corp-net-guide
SUBDIR = design-44bsd
#SUBDIR+= developers-handbook
SUBDIR+= faq
#SUBDIR+= fdp-primer
SUBDIR+= handbook
SUBDIR+= porters-handbook
SUBDIR+= ppp-primer

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
