# $FreeBSD$

.NOTPARALLEL: 

DOC=	FAQ
VOLUME= faq
DOCDIR= /usr/local/share/doc/fdp/zh_TW.Big5/books
FORMATS?= html roff
SGMLOPTS=-links -e big5

SRCS= FAQ.sgml acknowledgments.sgml admin.sgml applications.sgml
SRCS+= commercial.sgml hackers.sgml hardware.sgml install.sgml
SRCS+= kernelconfig.sgml misc.sgml network.sgml preface.sgml
SRCS+=	serial.sgml troubleshoot.sgml x.sgml

.include <bsd.sgml.mk>

