# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

SUBDIR= dists docs links

DOCS =  index.sgml
DOCS+=  advocacy.sgml
DOCS+=  howhelp.sgml
DOCS+=  index.sgml
DOCS+=  install.sgml
DOCS+=  newsflash.sgml
DOCS+=  press.sgml

DATA=	j2j.gif

.include <../web.mk>
