# $FreeBSD: www/ja/support/Makefile,v 1.1 2009/07/21 06:12:12 hrs Exp $
# Original Revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	bugreports.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
