---
title: "FreeBSD/MIPS Project"
sidenav: developers
---

= FreeBSD/MIPS Project

== Project Goal

The FreeBSD/MIPS Project is responsible for the maintenance and development of FreeBSD on platforms using MIPS processors. The port currently runs multi-user on a number of platforms and a wide variety of 32-bit and 64-bit MISP ISA processors.

== Supported MIPS Platforms

FreeBSD supports a broad range of MIPS-based devices, including MIPS Malta, Ubiquiti Networks Router-Station and Router-Station Pro, Cavium Octeon, NetLogicMicro/RMI XLS and XLR (XLP in progress), as well as emulated MIPS environments such as gxemul. On supporting hardware platforms, FreeBSD supports both multi-core and hardware multi-threading features. In many cases, additional accelerator functions, such as cryptographic and network offload engines, are also supported.

== How to Contribute

If you have code that you are interested in committing, you can send it for review to the <<mailinglist,freebsd-mips mailing list>>.

== Resources and Links

* The FreeBSD.org wiki's https://wiki.freebsd.org/FreeBSD/mips[FreeBSD/MIPS port] page, which includes information on building FreeBSD/mips.
* General MIPS information is available from http://www.mips.com[MIPS Technologies, Inc.]
* [[mailinglist]] Most discussion relating to this project takes place on the freebsd-mips@FreeBSD.org mailing list. To subscribe to the list, send a message to freebsd-mips-subscribe@FreeBSD.org.
* http://zrouter.org/[zrouter], a FreeBSD-based MIPS router firmware build environment.
