# $FreeBSD: doc/en_US.ISO_8859-1/articles/Makefile,v 1.10 2001/03/14 18:11:19 nik Exp $

SUBDIR = committers-guide
SUBDIR+= dialup-firewall
SUBDIR+= diskless-x
SUBDIR+= explaining-bsd
SUBDIR+= freebsd-questions
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= ipsec-must
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= programming-tools
SUBDIR+= vm-design
SUBDIR+= zip-drive

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
