#       $Id: Makefile,v 1.3 1999-09-03 17:11:28 nik Exp $

SUBDIR = committers-guide
SUBDIR+= diskless-x
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= programming-tools

ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
