# $FreeBSD: www/en/alpha/Makefile,v 1.7 2000/11/07 04:05:08 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   alpha.sgml
DOCS+=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
