# $Id: Makefile,v 1.4 1998-08-11 11:43:45 wosch Exp $
 
.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=   alpha.sgml
 
DOCS+=  current.sgml
DOCS+=  bootstrapping.sgml

INDEXLINK=alpha.html
 
.include "../web.mk"
