# $Id: Makefile,v 1.3 1998-08-11 01:18:28 wosch Exp $
 
.if exists("../Makefile.conf")
.include "../Makefile.conf"
.endif

DOCS=   alpha.sgml
 
DOCS+=  current.sgml
DOCS+=  bootstrapping.sgml

INDEXLINK=alpha.html
 
.include "../web.mk"
