# $Id: Makefile.inc,v 1.3 1997-11-23 22:55:07 max Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.5

WEBBASE?=	/data/ja_JP.EUC
SGMLOPTS+=	-links -hdr ${.CURDIR}/../doc.hdr -ftr ${.CURDIR}/../doc.ftr
