#
# The FreeBSD Russian Documentation Project

# $FreeBSD$
# $FreeBSDru: frdp/www/ru/docproj/Makefile,v 1.4 2003/09/26 17:13:55 andy Exp $
#
# Original revision: 1.10
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   current.sgml 
DOCS+=	doc-set.sgml
DOCS+=	handbook.sgml
DOCS+=	handbook3.sgml
DOCS+=  sgml.sgml
DOCS+=  submitting.sgml
DOCS+=  who.sgml 
DOCS+=  translations.sgml
DOCS+=	docproj.sgml

INDEXLINK= docproj.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
