freebsd_instance:
  image_family: freebsd-13-2

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  timeout_in: 20m
  install_script:
    - pkg install -y docproj
  test_script:
    - make HUGO_ARGS="--verbose --debug"

