---
title: "FreeBSD/MIPS プロジェクト"
sidenav: developers
---

include::shared/ja/urls.adoc[]

= FreeBSD/MIPS プロジェクト

== はじめに

このページは、FreeBSD の MIPS(R) プラットフォームへの移植に関する情報を掲載しています。 MIPS への移植についての議論は、 https://lists.freebsd.org/mailman/listinfo/freebsd-mips[freebsd-mips] メーリングリストで行われています。

== 目次

* <<status,現在の状況>>
* <<hw,FreeBSD/MIPS ハードウェアノート>>
* <<list,FreeBSD/MIPS メーリングリスト>>

[[status]]
== 現在の状況

MIPS は link:{committers-guide}#archs[Tier 2] アーキテクチャであり、link:../../[FreeBSD] プロジェクトにより全面的にサポートされているというわけではありません。

[[hw]]
== FreeBSD/MIPS ハードウェアノート

FreeBSD/MIPS は、FreeBSD オペレーティングシステムの MIPS 系プロセッサを搭載したプラットフォームへの移植です。 現時点では、MIPS32 および MIPS64 development ボード、 組み込みプラットフォームが対象です。

対応しているすべての CPU およびボードの一覧をこのページでまとめることは現実的ではありません。 多くの情報はメーリングリスト、アーカイブ、 http://wiki.freebsd.org/FreeBSD/mips[MIPS Wiki ページ] で見つけることができます。 https://svnweb.freebsd.org/base/head/sys/mips/conf/[カーネルコンフィグレーションファイル] にもあります。

=== CPU

完全に網羅しているわけではありませんが、 以下に挙げたものが対応している CPU および CPU ファミリです。

* MIPS4Kc
* MIPS24Kc
* MIPS74Kc
* Atheros AR71xx, AR724x, AR91xx, AR933x, AR934x
* Cavium OCTEON
* NetLogic XLR/XLS CPU family
* SRI/Cambridge's BERI and CHERI open-source FPGA soft-cores

すべての CPU がすべての周辺機器に対応しているわけではありません。

=== ボード

以下のボードに対応しています。

* Ubiquiti Networks Router-Station (AR7130)
* Ubiquiti Networks Router-Station Pro (AR7161)
* Ubiquiti Networks PicoStation M2HP (AR7241)
* Ubiquiti Networks EdgeRouter Lite (OCTEON)
* TP-Link TL-WR1043ND (AR9132)
* Mikrotik RouterBoard RB450G
* Alfa Networks Hornet UB (AR933x)
* D-Link DIR-825 (AR7161)
* Atheros PB44, PB47, AP94, AP96 reference designs (AR7161)
* Atheros DB120 reference design (AR9344)
* 8devices Carambola-2 (AR9330)
* Engenius ENH-200 (AR7240+AR9285)
* Buffalo Airstation WZR-300HP B0 A1
* MIPS Malta evaluation board
* Lanner MR-320, MR-730, MR-995 (OCTEON)
* Portwell CAM-0100 (OCTEON)
* Radisys AMC-7211 / ATCA-7220 (OCTEON)
* D-Link DSR-500, DSR-500N, DSR-1000 and DSR-1000N (OCTEON)
* GE Intelligent Platforms WANIC 6354 (OCTEON)
* Cavium development boards CN5860-EVB-NIC4, CN5650-EVB-NIC16, CN5200-EVB-MB4

すべてのボードがすべての周辺機器に対応しているわけではありません。

[[list]]
== FreeBSD/MIPS メーリングリスト

本プロジェクトにコードで貢献したいと考えていたり、 現在の状況を知りたいのであれば、 <<list,FreeBSD/MIPS メーリングリスト>> に参加してください。

このメーリングリストを購読するには、`<freebsd-mips-subscribe@FreeBSD.org>` にメールを送るか、link:http://lists.FreeBSD.org/mailman/listinfo/freebsd-mips[mailman インタフェース]を利用してください。
