---
title: "FreeBSD 12.2 Release Information"
sidenav: download
---

:localRel: "12.2"
:localBranchStable: "stable/12"
:localBranchReleng: "releng/12.2"

= FreeBSD {localRel}-RELEASE Announcement

== Introduction

This is the index page for FreeBSD {localRel}. For more information about the release engineering process, please see the link:../[Release Engineering] section of the web site.

== Introduction

This is the index page for FreeBSD {localRel}. For more information about the release engineering process, please see the link:../../releng/[Release Engineering] section of the web site.

== Detailed Information

More detailed information, such as release notes and hardware notes can be found at these pages:

link:signatures/[FreeBSD{localRel}-RELEASE signed checksum files] +
link:installation/[FreeBSD{localRel}-RELEASE installation information] +
link:hardware/[FreeBSD{localRel}-RELEASE hardware information] +
link:relnotes/[FreeBSD{localRel}-RELEASE release notes] +
link:errata/[FreeBSD{localRel}-RELEASE errata] +
link:readme/[FreeBSD{localRel}-RELEASE readme] +
link:schedule/[FreeBSD{localRel}-RELEASE schedule] +

////
link:todo/[FreeBSD Release Engineering TODO Page] +
////
