---
title: "Projet de Documentation FreeBSD"
sidenav: docs
---

= Projet de Documentation FreeBSD

== Vue d'ensemble

S'attaquer à un système d'exploitation nouveau et complexe est toujours une tâche difficile, quelque soit sa convivialité. FreeBSD n'est pas différent à cet égard.

Il existe de nombreux livres sur les Unix BSD (et les UNIX(R) en général) mais FreeBSD possède ses propres caractéristiques, procédures et bizarreries.

De plus, FreeBSD est amené à être le premier contact avec un système d'exploitation dérivé d'Unix pour beaucoup d'utilisateurs donc la disponibilité d'une documentation précise et de haute qualité est indispensable.

Le Projet de Documentation FreeBSD est là pour combler ce vide. Il s'y prend de deux façons :

. Les membres du Projet de Documentation écrivent un document et le soumettent afin qu'il soit inclu dans le _Jeu de Documentation FreeBSD_.
. Les membres du Projet de Documentation débatent de la forme et de l'organisation du _Jeu de Documentation FreeBSD_.

[.tblbasic]
[width="100%",cols="100%",]
|===
a|
[.center]
=== link:current[Projets en cours]

Plusieurs projets sont actuellement _en cours de réalisation_ dans le cadre de l'effort de documentation. Prenez le temps de consulter cette liste afin de savoir s'il y en a un pour lequel *vous* pouvez apporter de l'aide.

|===

== link:who[Qui sommes-nous, comment nous rejoindre]

Cette page explique qui compose le Projet de Documentation et comment s'y joindre.

== link:doc-set[Le Jeu de Documentation FreeBSD]

Cette page esquisse la composition du Jeu de Documentation FreeBSD ainsi que le travail que le Projet de Documentation réalise.

== link:sgml[SGML et le Projet de Documentation]

Le projet utilise le SGML pour la documentation. Cette page survole la méthode utilisée et dirige les lecteurs intéressés vers davantage de ressources SGML.

== link:submitting[Proposer une documentation]

Les propositions de documentation sont le meilleur moyen de faire partie du projet et de rendre FreeBSD plus facile à utiliser. Cette page décrit la meilleure façon de soumettre un document afin qu'il soit examiné le plus rapidement possible.

== link:translations[Traduction]

Traductions de la documentation FreeBSD : pages web, manuel de référence, pages de manuel et FAQ.
