---
title: "Projet de documentation de FreeBSD : Projects actuels"
sidenav: docs
---

= Projet de documentation de FreeBSD : Projects actuels

Voici les projets en cours de réalisation (ou étant sérieusement envisagés sur la liste de diffusion freebsd-doc). J'en ai aussi inclus certains dont nous n'avons pas vraiment parlé mais qui peuvent être une bonne idée. Pour chaque projet est indiqué la personne à contacter (si je sais qui s'occupe du projet).

Si vous pensez que vous pouvez contribuer à l'un d'eux, n'hésitez pas à nous rejoindre. Vous pouvez contacter la personne qui s'occupe du projet en particulier, elle vous guidera et vous mettra au courant de ce qu'il s'y passe. Si vous avez une idée de nouveau projet, veuillez envoyer un courrier électronique à FreeBSD-doc@FreeBSD.org

* <<pr,Rapports de problèmes dans la documentation>>
* <<handbook3,Manuel de Référence, 3ème édition imprimée>>
* <<handbook,Manuel de Référence, 2ème édition imprimée (terminé)>>
* <<freebsd4linux,FreeBSD pour les utilisateurs Linux>>
* <<handbooksection,Écrire une section du manuel de référence ou de la FAQ>>
* <<newpapers,Écrire de nouveaux articles>>
* <<develbook,Écrire de nouveaux chapitres pour le Manuel des Développeurs>>
* <<cgiscripts,Scripts CGI>>
* <<multilingualwebscripts,Scripts web polyglottes>>
* <<translations,Traductions de la documentation de FreeBSD>>
* <<search-enhancements,Amélioration du moteur de recherche>>
* <<tunables,Documenter les réglages possibles de FreeBSD>>
* <<newkernelmanpages,Écrire des pages de manuel pour le noyau>>

[[pr]]
== Rapports de problèmes dans la documentation

Les rapports de problèmes avec FreeBSD sont recueillis dans une base de données GNATS. Vous pouvez les consulter http://www.FreeBSD.org/cgi/query-pr-summary.cgi?category=docs&responsible=.[ici] .

[[handbook3]]
== Manuel de Référence FreeBSD, 3ème édition

*Responsable :* Murray Stokely <murray@FreeBSD.org>

*Synopsis :* Le travail de préparation pour la publication du Manuel de Référence FreeBSD a commencé. Consultez la link:handbook3.html[liste complète des tâches] pour savoir de quelle façon vous pouvez aider.

[[handbook]]
== Manuel de Référence FreeBSD, 2ème édition

*Responsable :* Murray Stokely <murray@FreeBSD.org>

*Synopsis :* Ce projet est achevé. La seconde édition du Manuel de Référence FreeBSD est maintenant disponible sur le site http://www.freebsdmall.com[The FreeBSD Mall]. Le manuscrit final contient 653 pages et le numéro ISBN est 1571763031. Merci à tous ceux qui ont participé. Vous pouvez lire l'annonce complète http://docs.freebsd.org/cgi/getmsg.cgi?fetch=0+0+archive/2001/freebsd-announce/20011028.freebsd-announce[ici].

La liste des tâches que nous avons utilisée pendant le développement de ce livre est toujours archivée link:handbook.html[ici] pour la postérité.

[[freebsd4linux]]
== FreeBSD pour les utilisateurs Linux

*Responsable :* FreeBSD-doc <FreeBSD-doc@FreeBSD.org>

*Synopsis :* Les utilisateurs de Linux qui migrent vers FreeBSD peuvent être déroutés par certaines différences entre ces systèmes (les différents shells par défaut, la prise en compte des paramètres de démarrage, etc...).

[[handbooksection]]
== Écrire une section du manuel de référence ou de la FAQ

*Responsable :* personne

*Synopsis :* La FAQ et le manuel de référence ont encore des sections vides qui se doivent d'être comblées. Si vous avez utilisé un de ces document pour vous aider dans une tâche et que vous avez constaté des manques, prenez le temps de d'écrire vos expériences qui pourront servir aux autres.

De même, si vous avez eu à faire une chose pour laquelle aucune entrée ne se trouve dans la FAQ ou le manuel, vous pouvez envisager d'écrire une nouvelle section. Vous pourrez alors la soumettre comme indiqué ci-dessus.

[[newpapers]]
== Écrire de nouveaux articles

=== La nouvelle couche SCSI de FreeBSD (CAM)

*Responsable :* <doc@FreeBSD.org>, <scsi@FreeBSD.org>

*Synopsis :* Voyez la page http://www.FreeBSD.org/~gibbs/[Conception et implémentation du sous-système SCSI de FreeBSD] pour une première approche.

[[develbook]]
== Écrire de nouveaux chapitres pour le Manuel des Développeurs

*Responsable :* <doc@FreeBSD.org>

*Synopsis :*

* Le Manuel des Développeurs FreeBSD manque encore de contenu, merci de nous aider à finir ce livre.

[[cgiscripts]]
== Scripts CGI

*Responsable :* <doc@FreeBSD.org>, Wolfram Schneider <wosch@FreeBSD.org>

*Synopsis :* Modifier les scripts CGI url.cgi, ports.cgi, pds.cgi et le script portindex pour utiliser les modules Perl de http://people.FreeBSD.org/~tom/portpm/[FreeBSD::Ports]. Ces modules ont aussi besoin d'être testés plus à fond.

[[multilingualwebscripts]]
== Scripts web multi-langues

*Responsable :* <doc@FreeBSD.org>

*Synopsis :*

Nos principales pages web sont écrites en anglais (américain). Les link:translations.html[Projets de traduction FreeBSD] sont chargés de traduire les pages web, le manuel de référence et la FAQ dans d'autres langues.

Nous devons aussi traduire les scripts cgi et les scripts de construction des pages web. Ces scripts devraient supporter plusieurs langues, pas seulement une seule. La plupart des scripts sont écrits en perl.

* Rassembler les scripts perl ftp://ftp.FreeBSD.org/pub/FreeBSD/FreeBSD-current/www/en/ports/portindex[www/en/ports/portindex] et ftp://ftp.FreeBSD.org/pub/FreeBSD/FreeBSD-current/www/ja/ports/portindex[www/ja/ports/portindex] en un seul. Ajouter une option pour choisir la sortie en anglais ou en japonais.

[[translations]]
== Traductions de la documentation FreeBSD

*Responsable :* <doc@FreeBSD.org>

Traduire la documentation de FreeBSD (pages web, FAQ, manuel de référence, pages de manuel) dans d'autres langues. Reportez-vous aux link:translations.html[Projets de traductions FreeBSD].

[[search-enhancements]]
== Amélioration du moteur de recherche

**Responsable :**Eric Anderson <anderson@centtech.com>

Les résultats de recherches sur le site web contiennent les noms des fichiers trouvés comme, par exemple, `+FAQ34.html+`.

Il serait plus utile que les résultats contiennent le texte de la question, permettant à l'utilisateur de savoir si une réponse est pertinente ou non.

[[tunables]]
== Documenter les réglages possibles de FreeBSD.

*Responsable :* Tom Rhodes <trhodes@FreeBSD.org >

Plusieurs réglages de FreeBSD sont encore non documentés. Tout le monde sait à quel point il est difficile d'utiliser un système non documenté, et c'est la raison pour laquelle ce projet a été créé. L'objectif initial est de créer un outil permettant de générer une page de manuel sur les réglages possibles. Pour cela, nous avons besoin de générer la liste de ces réglages à partir du code source.

[[newkernelmanpages]]
== Écrire les pages de manuel de la section 9

*Responsable :* Tom Rhodes < trhodes@FreeBSD.org> et Hiten Pandya <hmp@FreeBSD.org>

*Synopsis :* Documentation des interfaces et des fonctions du noyau

link:..[Accueil du Projet de documentation FreeBSD]
