---
title: "FreeBSD Documentation Project: Documentation Set"
sidenav: docs
---

= FreeBSD Documentation Project: Documentation Set

La documentation de FreeBSD est composée de trois grandes catégories :

. http://www.FreeBSD.org/cgi/man.cgi[*Les pages de manuel*]
+
Le Projet n'est pas réellement concerné car elles font partie du système de base. Exception faite de l'équipe japonaise qui les traduit. Il n'y a pas de raisons que d'autres volontaires ne se mettent pas à traduire les pages de manuel dans d'autres langues.
+
Cela ne veut pas dire que les pages de manuel ne sont pas importantes, loin de là. C'est juste qu'elles sont intimement liées aux systèmes spécifiques à FreeBSD et que la plupart du temps la personne la mieux placée pour les écrire est le développeur lui-même.
. link:../../docs/books/[*Les livres*]
+
Le projet a un grand nombre de documentations qui sont de la taille d'un livre ou qui sont conçues comme un livre. C'est par exemple le cas de la FAQ FreeBSD et du Manuel de Référence FreeBSD.
. link:../docs/books/#articles[*Les articles*]
+
FreeBSD a une mine d'informations disponibles sous formes d'articles plus courts -- à la manière des guides ou des HOWTO d'autres projets.

link:..[Accueil du Projet de Documentation FreeBSD]
