---
title: "FreeBSD Documentation Project: Translations"
sidenav: docs
---

= FreeBSD Documentation Project: Translations

<<brazilian_portuguese,Projet de documentation en brésilien-portugais>>
<<bulgarian,Projet de documentation en bulgare>>
<<chinese-cn,Projet de documentation en chinois simplifié>>
<<chinese-tw,Projet de documentation en chinois traditionnel>>
<<dutch,Projet de documentation en hollandais>>
<<estonian,Projet de documentation en estonien>>
<<french,Projet de documentation en français>>
<<german,Projet de documentation en allemand>>
<<italian,Projet de documentation en italien>>
<<japanese,Projet de documentation en japonais>>
<<korean,Projet de documentation en coréen>>
<<polish,Projet de documentation en polonais>>
<<romanian,Projet de documentation en roumain>>
<<russian,Projet de documentation en russe>>
<<spanish,Projet de documentation en espagnol>>
<<turkish,Projet de documentation en turc]>>

[[brazilian_portuguese]]
== Le projet de documentation FreeBSD en brésilien-portugais

*Web* : http://doc.fugspbr.org/ +
*E-Mail* : lioux@FreeBSD.org +

_Listes de diffusion_::
Consultez l'URL http://lists.fugspbr.org/listinfo.cgi/doc-fugspbr.org/ pour savoir comment s'inscrire à la liste de diffusion du groupe de traduction brésilien-portugais. +
Ou bien envoyez un courrier électronique à mailto:doc-request@fugspbr.org?subject=subscribe[doc-request@fugspbr.org] avec le mot "subscribe" dans le sujet du message. +
Les messages (autorisés uniquement pour les personnes inscrites) sont à envoyer à l'adresse doc@fugspbr.org
_Documents disponibles_::
link:https://www.FreeBSD.org/doc/pt_BR/books/faq/[FAQ]
+
link:https://www.FreeBSD.org/doc/pt_BR/articles/contributing/[Contribuer à FreeBSD]
_Documents en cours de traduction_::
http://doc.fugspbr.org/fdp/[Introduction au Projet de Documentation de FreeBSD pour les nouveaux participants]
+
http://doc.fugspbr.org/handbook/[Manuel de référence FreeBSD]

[[bulgarian]]
== Le projet de documentation FreeBSD en bulgare

*Web*: http://fdp.bg-freebsd.org/ +
*E-Mail*: freebsd-fdp@bg-freebsd.org +

_Listes de diffusion disponibles_::
Consultez l'URL http://lists.bg-freebsd.org/ pour savoir comment s'inscrire à la liste de diffusion du groupe de traduction bulgare. +
Ou bien envoyez un courrier électronique à freebsd-fdp-subscribe@bg-freebsd.org. +
Les messages (autorisés uniquement pour les personnes inscrites) sont à envoyer à l'adresse freebsd-fdp@bg-freebsd.org
_Documents disponibles_::
http://www.cybershade.us/freebsd/bg/fdp/split/[Introduction au Projet de Documentation de FreeBSD pour les nouveaux participants]
_Documents en cours de traduction_::
Manuel de référence FreeBSD
+
Site web FreeBSD
+
Conception et Implémentation du Système d'Exploitation 4.4BSD (chapitre 2)
+
Questions Fréquemment Posées sur FreeBSD

[[chinese-tw]]
== Le projet de documentation FreeBSD en chinois traditionnel

*Web*: - +
*E-Mail*: foxfair@FreeBSD.org +

_Listes de diffusion disponibles_::
Envoyer un courrier à l'adresse majordomo@freebsd.sinica.edu.tw comportant "subscribe freebsd-chinese-doc" dans le corps du message. +
L'envoi de messages est authorisé aux membres à l'adresse freebsd-chinese-doc@freebsd.sinica.edu.tw
_Documents disponibles_::
link:https://www.FreeBSD.org/doc/zh-tw/books/faq/[FAQ]
_Document en cours de traduction_::
http://www.tw.FreeBSD.org/handbook-big5.html[Le manuel de référence]

[[chinese-cn]]
== Le projet de documentation FreeBSD en chinois simplifié

*Web*: http://www.FreeBSD.org.cn[www.FreeBSD.org.cn] +
*E-Mail*: delphij@FreeBSD.org +

_Liste de diffusion_::
Les instructions pour s'inscrire à la liste de diffusion du projet de documentation en chinois simplifié sont disponibles sur http://lists.FreeBSD.org.cn/mailman/listinfo
_Documents en cours de traduction_::
http://www.freebsd.org.cn/doc/zh_CN/books/arch-handbook[Manuel de l'architecture FreeBSD]
+
http://www.freebsd.org.cn/doc/zh_CN/books/handbook[Manuel de référence FreeBSD]
+
http://www.freebsd.org.cn/doc/zh_CN/books/porters-handbook[Manuel du porteur d'applications]
+
http://www.freebsd.org.cn/doc/zh_CN/books/faq[Questions Fréquemment Posées sur FreeBSD]

[[dutch]]
== Le projet de documentation FreeBSD en hollandais

*E-Mail*: remko@FreeBSD.org +

_Listes de diffusion_::
Envoyez un courrier électronique à majordomo@majordomo.elvandar.org avec "subscribe freebsd-doc-nl" dans le corps du message pour vous inscrire à la liste de diffusion en hollandais FreeBSD-doc-nl. +
+
Envoyez un courrier électronique à majordomo@majordomo.elvandar.org avec "subscribe freebsd-doc-nl-cvs" dans le corps du message pour vous inscrire à la liste de diffusion CVS FreeBSD-doc-nl-cvs. +
_Documents parus_::
http://www.freebsd.org/doc/nl/books/handbook[Manuel de référence (complet à 80%)]
_Documents en cours de traduction_::
http://www.freebsd-nl.org/doc/nl[Manuel de référence]
+
http://www.freebsd-nl.org/www/nl[Pages Web]

[[estonian]]
== Le projet de documentation FreeBSD en estonien

*Web*: http://www.bsd.ee/tolge.php +

_Document disponible_::
http://www.bsd.ee/handbook/[Manuel de référence FreeBSD]

[[french]]
== Le projet de documentation FreeBSD en français

*Web*: http://www.freebsd-fr.org/[http://www.freebsd-fr.org] +

_Listes de diffusion disponibles_::
Envoyer un courrier à l'adresse listserver@freebsd-fr.org comportant "SUB freebsd-questions" dans le corps du message afin de souscrire à la liste de diffusion française dédiée aux questions d'ordres générales. +
+
Envoyer un courrier à l'adresse listserver@freebsd-fr.org comportant "SUB annonces" dans le corps du message afin de souscrire à la liste de diffusion française dédiée aux annonces. +
_Documents disponibles_::
link:https://www.FreeBSD.org/doc/fr/books/faq/[FAQ]
+
link:https://www.FreeBSD.org/doc/fr/articles/[Certains articles et guides]
+
http://www.freebsd-fr.org/local-fr/www/spec/bulletins_index.html[Des nouvelles (vraiment) brèves]
+
http://www.freebsd-fr.org/doc/fr/books/picobsd/[PicoBSD]
_Document en cours de traduction_::
link:https://www.FreeBSD.org/doc/fr/books/handbook/book[Le Manuel de référence FreeBSD], link:https://www.FreeBSD.org/fr/index.html[Site web]
_Dépôt CVS_::
http://www.freebsd-fr.org/cgi-fr/cvsweb.cgi/[Site web CVS]
+
Envoyer un courrier à l'adresse listserver@freebsd-fr.org comportant "SUB cvs" dans le corps du message afin de souscrire à la liste de diffusion française dédiée aux modifications CVS. +

[[german]]
== Le projet de documentation FreeBSD en allemand

*Web*: http://people.FreeBSD.org/~mheinen/de-bsd-translators/de-bsd-translators.html +
*E-Mail*: de-bsd-translators@de.FreeBSD.org +

_Documents disponibles_::
link:https://www.FreeBSD.org/doc/de/books/faq/[FAQ], link:https://www.FreeBSD.org/doc/de/articles/[quelques articles]
_Documents en cours de traduction_::
link:https://www.FreeBSD.org/doc/de/books/handbook/[Manuel de référence FreeBSD], link:https://www.FreeBSD.org/doc/de/books/fdp-primer/[Introduction au Projet de Documentation de FreeBSD pour les nouveaux participants], link:https://www.FreeBSD.org/de/[Web]

[[italian]]
== Le projet de documentation FreeBSD en italien

*Web*: http://www.gufi.org/~alex/ +
*E-Mail*: ale@freebsd.org +

_Listes de diffusion disponibles_::
Consulter l'adresse http://liste.gufi.org/mailman/listinfo/traduzioni pour savoir comment s'inscrire à la liste de diffusion du groupe de traduction italien. +
Ou, envoyer un courrier électronique à mailto:traduzioni-request@gufi.org?subject=subscribe[traduzioni-request@gufi.org] avec le mot "subscribe" dans le sujet du message. +
L'envoi est permis aux membres à l'adresse traduzioni@gufi.org
_Documents disponibles_::
link:https://www.FreeBSD.org/doc/it/books/unix-introduction/[Introduction à Unix]
+
link:https://www.FreeBSD.org/it/docs/#articles[Quelques Articles]
_Documents en cours de traduction_::
link:https://www.FreeBSD.org/doc/it/books/handbook/[Manuel de référence FreeBSD]
+
link:https://www.FreeBSD.org/it/index.html[Web]
_Dépôt CVS_::
http://cvs.gufi.org/cgi/cvsweb.cgi/doc/[CVS web]
+
Envoyer un courrier électronique à mailto:cvs-all-request@gufi.org?subject=subscribe[cvs-all-request@gufi.org] avec le mot "subscribe" dans le sujet du message pour s'inscrire à la liste de diffusion des mises à jour du CVS italien en italien. +

[[japanese]]
== Le projet de documentation FreeBSD en japonais

*Web*: http://www.jp.FreeBSD.org/doc-jp/ +
*E-Mail*: doc-jp@jp.FreeBSD.org +

_Documents disponibles_::
link:https://www.FreeBSD.org/doc/ja/books/handbook/[Le manuel de référence], link:https://www.FreeBSD.org/doc/ja/books/faq[FAQ], link:https://www.FreeBSD.org/ja/[Web], http://www.jp.FreeBSD.org/NewsLetter/Issue2/[Bulletin d'information FreeBSD numéro 2]
_Documents en cours de traduction_::
Guides FreeBSD

[[korean]]
== Le projet de documentation FreeBSD en coréen

*Web*: http://www.kr.FreeBSD.org/projects/doc-kr/ +
*E-Mail*: doc@kr.FreeBSD.org +

_Document en cours de traduction_::
Le manuel de référence

[[polish]]
== Le projet de documentation FreeBSD en polonais

*Web* : http://tlumaczenie.freebsd.pl +
*E-Mail* : ni@merkury.pol.lublin.pl +

_Documents disponibles_::
Quelques guides
_Documents en cours de traduction_::
Guides FreeBSD
+
Manuel de référence
+
Introduction au Projet de Documentation de FreeBSD pour les nouveaux participants

[[romanian]]
== Le projet de documentation FreeBSD en roumain

*Web*: http://www.rofug.ro/projects/ro-l10n/ +
*E-Mail*: ady@rofug.ro +

_Listes de diffusion disponibles_::
Pour souscrire à la liste de diffusion ro-l10n, consultez la page web du projet ou envoyez un courrier à l'adresse listar@rofug.ro comportant "subscribe ro-l10n" dans le corps du message. +
Seuls les membres de la liste de diffusion ro-l10n sont autorisés à envoyer des messages.
_Document en cours de traduction_::
Manuel de référence

[[russian]]
== Le projet de documentation FreeBSD en russe

*Web*: http://www.FreeBSD.org.ua/[http://www.FreeBSD.org.ua] +
*E-Mail*: frdp@FreeBSD.org.ua +

_Documents disponibles_::
link:https://www.FreeBSD.org/doc/ru/books/faq/[FAQ]
+
link:https://www.FreeBSD.org/ru/[WWW]
+
http://www.FreeBSD.org.ua/docs.html[Liste des autres documents]
_Documents en cours de traduction_::
http://www.FreeBSD.org.ua/doc/ru_RU.KOI8-R/books/handbook/[Le manuel de référence]

[[spanish]]
== Le projet de documentation FreeBSD en espagnol

*Web*: http://www.es.FreeBSD.org/es/ +
*E-Mail*: jesusr@FreeBSD.org +

_Listes de diffusion disponibles_::
https://listas.es.freebsd.org/mailman/listinfo/doc[Documentation en espagnol]
_Documents disponibles_::
link:https://www.FreeBSD.org/doc/es/books/faq/[FAQ]
+
link:https://www.FreeBSD.org/doc/es/books/handbook/[Le manuel de référence]
+
link:https://www.FreeBSD.org/doc/es/articles/[Articles]

[[turkish]]
== Le projet de documentation FreeBSD en turc

*Web*: http://www.enderunix.org/ftdp/ +
*E-Mail*: ofsen@enderunix.org +

_Listes de diffusion disponibles_::
Pour s'inscrire à la liste de diffusion du projet, consultez la page web ou envoyer un courrier électronique vide à link:ftdp-subscribe@lists.enderunix.org[ftpd-subscribe@lists.enderunix.org].
_Documents disponibles_::
link:https://www.FreeBSD.org/tr/[WWW]
+
http://www.enderunix.org/ftdp/[Liste des autres documents]
_Documents en cours de traduction_::
Introduction au Projet de Documentation de FreeBSD pour les nouveaux participants

link:..[Site du projet de documentation FreeBSD]
