# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/articles/laptop/Makefile
# %SRCID%	1.4

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.xml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
