#
# $FreeBSD$
# Original version: 1.1
#
# Article about using FreeBSD on laptops
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

TIDYFLAGS+=	-raw

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
