# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=	16.xml
DOCS+=	17.xml
DOCS+=	index.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
