# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/articles/explaining-bsd/Makefile
# %SRCID%	1.6

MAINTAINER=keramida@FreeBSD.org

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=  article.xml

URL_RELPREFIX?=        ../../../..
DOC_PREFIX?=   ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
