MAN9 =	BUS_CONNECT_INTR.9\
	BUS_CREATE_INTR.9\
	BUS_PRINT_CHILD.9\
	BUS_READ_IVAR.9\
	DEVICE_ATTACH.9\
	DEVICE_DETACH.9\
	DEVICE_PROBE.9\
	DEVICE_SHUTDOWN.9\
	MD5.9\
	VFS.9\
	bus_generic_attach.9\
	bus_generic_detach.9\
	bus_generic_map_intr.9\
	bus_generic_print_child.9\
	bus_generic_read_ivar.9\
	bus_generic_shutdown.9\
	copy.9\
	fetch.9\
	free.9\
	inittodr.9\
	intro.9\
	malloc.9\
	panic.9\
	physio.9\
	resettodr.9\
	spl.9\
	store.9\
	style.9\
	uio.9\
	vslock.9

MLINKS+=BUS_READ_IVAR.9 BUSWRITE_IVAR.9
MLINKS+=malloc.9 FREE.9
MLINKS+=malloc.9 MALLOC.9
MLINKS+=MD5.9 MD5Init.9
MLINKS+=MD5.9 MD5Transform.9
MLINKS+=bus_generic_read_ivar.9 bus_generic_write_ivar.9
MLINKS+=copy.9 copyin.9
MLINKS+=copy.9 copyinstr.9
MLINKS+=copy.9 copyout.9
MLINKS+=copy.9 copystr.9
MLINKS+=copy.9 malloc.9
MLINLS+=fetch.9 fubyte.9
MLINKS+=fetch.9 fuswintr.9
MLINKS+=fetch.9 fusword.9
MLINKS+=fetch.9 fuword.9
MLINKS+=fetch.9 subyte.9
MLINKS+=fetch.9 suswintr.9
MLINKS+=fetch.9 susword.9
MLINKS+=fetch.9 suword.9
MLINKS+=spl.9 spl0.9
MLINKS+=spl.9 splbio.9
MLINKS+=spl.9 splclock.9
MLINKS+=spl.9 splhigh.9
MLINKS+=spl.9 splimp.9
MLINKS+=spl.9 splnet.9
MLINKS+=spl.9 splsoftclock.9
MLINKS+=spl.9 splsofttty.9
MLINKS+=spl.9 splstatclock.9
MLINKS+=spl.9 spltty.9
MLINKS+=spl.9 splvm.9
MLINKS+=spl.9 splx.9
MLINKS+=uio.9 uiomove.9
MLINKS+=vslock.9 vsunlock.9

.include "bsd.prog.mk"

