.\" Copyright (c) 1999 Chris Costello
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\" 
.\" %FreeBSD: src/share/man/man9/make_dev.9,v 1.2 1999/12/23 17:16:31 bde Exp %
.\" 
.Dd September 25, 1999
.Os
.Dt MAKE_DEV 9
.Sh 名称
.Nm make_dev ,
.Nm destroy_dev
.Nd 新しいデバイスのための dev_t および devfs 登録の作成と削除
.Sh 書式
.Fd #include <sys/types.h>
.Fd #include <sys/conf.h>
.Ft dev_t
.Fn make_dev "struct cdevsw *cdevsw" "int minor" "uid_t uid" "gid_t gid" "int perms" "char *fmt" ...
.Ft void
.Fn destroy_dev "dev_t dev"
.Sh 解説
.Fn make_dev
関数は新しいデバイスのための
.Fa dev_t
構造体を作成します。
DEVFS が利用可能な場合、
DEVFS にもまた新しいデバイスの存在が通知されます。
そのデバイスは
.Va uid
によって所有され、
.Va gid
のグループに所有され、
.Va name
で指定される名前を持ちます。
.Va perms
に指定するファイルのパーミッションは
.Aq Pa sys/stat.h
で定義されています。
.Pp
.Bd -literal -offset indent -compact
#define S_IRWXU 0000700    /* 所有者の RWX マスク
#define S_IRUSR 0000400    /* 所有者の R */
#define S_IWUSR 0000200    /* 所有者の W */
#define S_IXUSR 0000100    /* 所有者の X */

#define S_IRWXG 0000070    /* グループの RWX マスク */
#define S_IRGRP 0000040    /* グループの R */
#define S_IWGRP 0000020    /* グループの W */
#define S_IXGRP 0000010    /* グループの X */

#define S_IRWXO 0000007    /* その他の RWX マスク */
#define S_IROTH 0000004    /* その他の R */
#define S_IWOTH 0000002    /* その他の W */
#define S_IXOTH 0000001    /* その他の X */

#define S_ISUID 0004000    /* 実行時にユーザ ID を設定 */
#define S_ISGID 0002000    /* 実行時にグループ ID を設定 */
#define S_ISVTX 0001000    /* スティッキービット */
#ifndef _POSIX_SOURCE
#define S_ISTXT 0001000
#endif
.Ed
.Pp
.Fn destroy_dev
関数は、
.Fn make_dev
から返された
.Fa dev_t
をとり、そのデバイスの登録を削除します。
.Sh 歴史
.Fn make_dev
および
.Fn destroy_dev
関数は
.Fx 4.0
で初めて登場しました。
