.\" -*- nroff -*-
.\"
.\" Copyright (c) 1996 Doug Rabson
.\"
.\" All rights reserved.
.\"
.\" This program is free software.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE DEVELOPERS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $FreeBSD: src/share/man/man9/vrele.9,v 1.6 1999/08/28 00:21:35 peter Exp $
.\"
.Dd July 24, 1996
.Os
.Dt VRELE 9
.Sh 名称
.Nm vrele
.Nd vnode の使用カウントのデクリメント
.Sh 書式
.Fd #include <sys/param.h>
.Fd #include <sys/vnode.h>
.Ft void
.Fn vrele "struct vnode *vp"
.Sh 解説
vnode の
.Dv v_usecount
フィールドをデクリメントします。
.Bl -tag -width vpXX
.It Ar vp
デクリメントされる vnode。
.El
.Pp
vnode を使用中のシステム中の全てのコードは、
その vnode を使い終えた時には、
.Xr vrele 9
を呼び出すべきです。
その vnode の
.Dv v_usecount
フィールドが 0 に達した場合には、その vnode はフリーリストに置かれます。
.Sh 関連項目
.Xr vget 9 ,
.Xr vnode 9 ,
.Xr vput 9 ,
.Xr vref 9
.Sh 作者
このマニュアルページは
.An Doug Rabson
が書きました。

