# $FreeBSD: www/en/news/Makefile,v 1.17 2000/03/09 21:00:25 jim Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=	index.sgml

INDEXLINK= ../news.html

.include "../../web.mk"
