---
title: "About FreeBSD Ports"
sidenav: ports
---

include::shared/en/urls.adoc[]

= About FreeBSD Ports

{{< form-ports >}}

'''''

The FreeBSD ports and packages collections offer two simple ways for users and administrators to install over 30,000 applications, utilities or libraries.

For most of those, a precompiled `package` with default options exists for each supported release, saving the user the work and time of having to compile anything at all.
Use man:pkg-install[8] to securely download and install a package.
For more information see link:{handbook}ports/#pkgng-intro[Using pkg for Binary Package Management].

Both collections support the latest point release on the link:{faq}#stable[FreeBSD-STABLE] branches.
In addition, the ports collection supports the link:{faq}#current[FreeBSD-CURRENT] branch.
Older releases are not supported and may or may not work correctly with an up-to-date ports collection.
Over time, changes to the ports collection may rely on features that are not present in older releases.
When this occurs, patches contributed by the user community to maintain support for older releases will usually be committed.

Each `port` listed here contains any patches necessary to make the original application source code compile and run on FreeBSD.
If you download the framework for the entire list of ports by installing the link:{handbook}ports/#ports-using[ports hierarchy], you can have thousands of applications right at your fingertips.

Each port's `Makefile` automatically fetches the application source code, either from a local disk or the network, unpacks it on your system, applies the patches, and compiles.
If all went well, a simple `make install` will install the application and register it with the package system.
