# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/commercial/Makefile,v 1.3 2000/11/10 17:04:48 phantom Exp $
# Original revision: 1.14

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

PERL=	perl5

DOCS = 	commercial.sgml
# DOCS+=  consulting.sgml
# DOCS+=  consulting_bycat.sgml
# DOCS+=  hardware.sgml
# DOCS+=  misc.sgml
# DOCS+=  software.sgml
# DOCS+=  software_bycat.sgml

INDEXLINK=commercial.html

BUILDTOP=	../..
DIR_IN_LOCAL=	commercial

.include "${WEB_PREFIX}/share/mk/web.site.mk"
