# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/commercial/Makefile,v 1.2 2000/10/27 11:26:10 phantom Exp $
# Original revision: 1.9

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

PERL=	perl5

DOCS = 	commercial.sgml
# DOCS+=  consulting.sgml
# DOCS+=  consulting_bycat.sgml
# DOCS+=  hardware.sgml
# DOCS+=  misc.sgml
# DOCS+=  software.sgml
# DOCS+=  software_bycat.sgml

INDEXLINK=commercial.html

BUILDTOP=	../..
DIR_IN_LOCAL=	commercial

.include "../web.mk"
