# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	Email.pm FieldStart.pm MIME.pm Patch.pm StateChange.pm Text.pm

.include "${WEB_PREFIX}/share/mk/web.site.mk"
