---
title: "Proyecto de Documentación de FreeBSD: Traducciones"
sidenav: docs
---

= Proyecto de Documentación de FreeBSD: Traducciones

* <<chinese,Chinese Documentation Project>>
* <<estonian,Estonian Documentation Project>>
* <<french,French Documentation Project>>
* <<german,German Documentation Project>>
* <<italian,Italian Documentation Project>>
* <<japanese,Japanese Documentation Project>>
* <<korean,Korean Documentation Project>>
* <<russian,Russian Documentation Project>>
* <<spanish,Spanish Documentation Project>>

[[chinese]]
== El "FreeBSD Chinese Documentation Project"

*Web*: - +
*E-Mail*: foxfair@FreeBSD.org +

_Listas de distribución disponibles_::
Envía un mail a majordomo@freebsd.sinica.edu.tw con el texto "subscribe freebsd-chinese-doc" en el cuerpo del mensaje. +
El envío de mensajes sólo está permitido para los miembros de freebsd-chinese-doc@freebsd.sinica.edu.tw
_Documentos disponibles_::
link:https://www.FreeBSD.org/zh_CN/doc/faq/[FAQ]
_Documentos en desarrollo_::
http://www.tw.freebsd.org/handbook-big5.html[Handbook]

[[Estonian]]
== El "FreeBSD Estonian Documentation Project"

*Web*: http://www.matti.ee/~vallo/ +

_Documentos disponibles_::
>http://www.matti.ee/~vallo/ppphandbook/ppp1.html[Sección PPP del Hnadbook]

[[french]]
== El "French FreeBSD Documentation Project"

*Web*: http://www.freebsd-fr.org/[http://www.freebsd-fr.org] +

_Listas de distribución disponibles_::
Envía un mail a mailto:majordomo@listserver-fr.org[listserver@freebsd-fr.org] con las palabras "SUB freebsd-questions" en el cuerpo del mensaje para hacer la subscripción en la lista questions en francés +
+
Envía un mail a mailto:listserver@freebsd-fr.org[listserver@freebsd-fr.org">] con las palabras "SUB annonces" en el cuerpo del mensaje para hacer la subscripción en la lista announce en francés. +
_Documentos disponibles_::
http://www.freebsd-fr.org/FAQ/FAQ.html[FAQ]
+
http://www.freebsd-fr.org/tutoriaux.html[Algunos tutoriales]
+
http://www.freebsd-fr.org/bulletins_index.html[Really Quick Newsletters]
+
http://www.freebsd-fr.org/picobsd/index.html[PicoBSD]
_Documentos actualmente en desarrollo_::
http://www.freebsd-fr.org/handbook.html[Handbook]
_CVS repository_::
http://www.freebsd-fr.org/cgi-bin/cvsweb.cgi[CVS web]

[[german]]
== El "FreeBSD German Documentation Project"

*Web*: http://www.de.freebsd.org/de/uebersetzung.html +
*E-Mail*: de-bsd-translators@de.freebsd.org +

_Documentos actualmente en desarrollo_::
http://www.de.freebsd.org/de/handbook/[Handbook]

[[italian]]
== El "FreeBSD Italian Documentation Project"

*Web*: - +
*E-Mail*: maw58@hotmail.com +

_Documentos actualmente en desarrollo_::
Handbook

[[japanese]]
== El "FreeBSD Japanese Documentation Project"

*Web*: http://www.jp.freebsd.org/doc-jp/ +
*E-Mail*: doc-jp@jp.freebsd.org +

_Documentos disponibles_::
link:https://www.FreeBSD.org/ja/doc/handbook/[Handbook], link:https://www.FreeBSD.org/ja/doc/faq/[FAQ], link:https://www.FreeBSD.org/ja[Web], http://www.jp.freebsd.org/NewsLetter/Issue2/[FreeBSD NewsLetter Issue #2]
_Documentos actualmente en desarrollo_::
Tutoriales de FreeBSD

[[korean]]
== El "FreeBSD Korean Documentation Project"

*Web*: http://www.kr.freebsd.org/projects/doc-kr/ +
*E-Mail*: doc@kr.freebsd.org +

_Documentos actualmente en desarrollo_::
Handbook

[[russian]]
== El "FreeBSD Russian Documentation Project"

*Web*: http://surw.chel.su/~andy/index.html +
*E-Mail*: mailto:andy@icc.surw.chel.su[Andrey Zakhvatov <andy@cgu.chel.su>] +

_Documentos disponibles_::
link:https://www.FreeBSD.org/ru/doc/faq/[FAQ]
+
http://surw.chel.su/~andy/ncvs/doc/ru/QA/QA.html[QA]
_Documents currently at working_::
http://surw.chel.su/~andy/ncvs/www/ru/index.html[WWW]
+
mailto:ru-freebsd-doc@freebsd.ru[Handbook]

[[spanish]]
== El "FreeBSD Spanish Documentation Project"

*Web*: http://www.es.freebsd.org/es/ +
*E-Mail*: jesusr@freebsd.org +

_Listas de distribución disponibles_::
Envía un mail a freebsd-subscribe@es.freebsd.org para suscribirte en la lista.
_Documentos disponibles_::
link:https://www.FreeBSD.org/es/doc/faq/[FAQ]
_Documentos actualmente en desarrollo_::
Handbook, Web

link:..[FreeBSD Documentation Project Home]
