# $Id: Makefile,v 1.1.1.1 1997-11-23 22:23:06 max Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

#DOCS=	announce.sgml notes.sgml
DOCS=	notes.sgml

.include "../../../web.mk"
