#
# FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/java-tomcat/Makefile,v 1.1 2004/02/20 19:20:45 andy Exp $
#
# Original revision: 1.3
#
# Makefile for "Java and FreeBSD First Steps"
# Author: Victoria Chan, Hiten Pandya

MAINTAINER=vkchan@kendryl.net hiten@uk.FreeBSD.org

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

# SGML content
SRCS=  article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
