# $FreeBSD: doc/nl_NL.ISO8859-1/articles/Makefile,v 1.4 2008/12/27 20:34:02 rene Exp $

# %SOURCE%	en_US.ISO8859-1/articles/Makefile
# %SRCID%	1.60

SUBDIR =
SUBDIR+= contributing
SUBDIR+= contributing-ports
SUBDIR+= explaining-bsd
SUBDIR+= problem-reports
SUBDIR+= solid-state

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
