# $FreeBSD$

SUBDIR =
SUBDIR+= contributing
SUBDIR+= explaining-bsd
SUBDIR+= leap-seconds
SUBDIR+= problem-reports
SUBDIR+= solid-state

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
