---
description: 'Prefácio sobre o Projeto de Documentação do FreeBSD'
next: books/fdp-primer/overview
path: /books/fdp-primer/
prev: books/fdp-primer
showBookMenu: 'true'
tags: ["preface", "prompts", "conventions"]
title: Prefácio
weight: 1
---

[preface]
[[preface]]
= Prefácio
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[preface-prompts]]
== Prompts do Shell

Esta tabela mostra o prompt padrão do sistema e o prompt do super usuário. Os exemplos usam estes prompts para indicar com qual usuário o exemplo foi executado.

[.informaltable]
[cols="1,2", frame="none", options="header"]
|===
| Usuário
| Prompt


|Usuário normal
|%

|`root`
|# 
|===

[[preface-conventions]]
== Convenções Tipográficas

Esta tabela descreve as convenções tipográficas utilizadas neste livro.

[.informaltable]
[cols="1,2", frame="none", options="header"]
|===
| Propósito
| Exemplos


|Nome dos comandos.
|Utilize `ls -l` para listar todos os arquivos.

|Nome dos arquivos.
|Edite [.filename]#.login#.

|Saída de um programa na tela do computador.
a| 

[source,shell]
....
You have mail.
....


|O que o usuário digita, quando contrastado com a saída do programa na tela do computador.
a| 

[source,shell]
....
% date +"The time is %H:%M"
The time is 09:18
....

|Referência a uma página de manual.
|Utilize man:su[1] para assumir outro nome de usuário.

|Nome de usuário e de grupos de usuários.
|Apenas o `root` pode fazer isso.

|Ênfase.
|O usuário _deve_ fazer isso.

|Texto que o usuário deve substituir com o texto real.
|Para buscar por uma palavra chave nas páginas de manual, digite `man -k _keyword_`

|Variáveis de ambiente.
|`$HOME` aponta para o diretório inicial do usuário.
|===

[[preface-notes]]
== Notas, Dicas, Informações Importantes, Avisos e Exemplos

Notas, avisos e exemplos aparecem ao longo do texto.

[NOTE]
====
Notas são representadas desta forma, e contêm informações para as quais se deve ficar atento, pois podem afetar o que o usuário faz.
====

[TIP]
====

Dicas são representadas desta forma, e contêm informações úteis para o usuário, como as que mostram uma maneira mais fácil de fazer alguma coisa.
====

[IMPORTANT]
====
Informações importantes são representadas desta forma. Normalmente elas destacam passos extras que o usuário pode precisar realizar.
====

[WARNING]
====

Avisos são representados deste modo, e contêm informações de alerta sobre possíveis danos se não seguir as instruções. Estes danos podem ser físicos, para o equipamento ou para o usuário, ou podem ser não-físicos, tal como a deleção inadvertida de arquivos importantes.
====

.Uma Amostra de Exemplo
[example]
====
Os exemplos são representados deste modo, e normalmente contêm exemplos passo a passo, ou mostram os resultados de uma determinada ação.
====

[[preface-acknowledgements]]
== Agradecimentos

Meu muito obrigado a Sue Blake, Patrick Durusau, Jon Hamilton, Peter Flynn, e Christopher Maden, por terem gasto parte do seu tempo lendo os primeiros rascunhos deste documento e por terem oferecido muitos comentários e críticas construtivas para este trabalho.
