=== FreeBSD Driver Development for BananaPi R2 / R64 / R2 Pro

Links: +
link:https://wiki.freebsd.org/arm/Bananapi[Banana Pi on the FreeBSD Wiki] URL: link:https://wiki.freebsd.org/arm/Bananapi[]

Contact: Martin Filla <freebsd@sysctl.cz>

This project adds FreeBSD support for three Banana Pi router boards: the
BPI-R2 (MediaTek MT7623, armv7), the BPI-R64 (MediaTek MT7622, arm64) and
the BPI-R2 Pro (Rockchip RK3568, arm64).

==== BPI-R2 (MT7623) Introduction

The Banana Pi BPI-R2 is a MediaTek MT7623N-based router board (quad-core
ARM Cortex-A7, up to 1.3 GHz) with 2 GB DDR3, 8 GB eMMC, 4x Gigabit LAN and
1x Gigabit WAN driven by the built-in MT7530 switch, two SATA ports, two
USB 3.0 ports, a mini PCIe slot, HDMI output, MIPI DSI/CSI connectors and
the usual UART, I2C, SPI, PWM and GPIO headers.  Because the MT7623 is an
armv7 part, it is the only board of the three that is built from the
32-bit `GENERIC` kernel configuration.

==== Current State of FreeBSD Support BPI-R2

Implemented so far:

* Platform / machdep support - device map, early console, late init and
  SoC reset, plus the `SOC_MEDIATEK` kernel option and a DTB build for
  `mt7623n-bananapi-bpi-r2.dts`
* SMP startup for the four Cortex-A7 cores
* UART driver
* Clock management - shared MediaTek clock infrastructure (gates, muxes,
  fixed factors) used by the topckgen, infracfg, pericfg, hifsys, bdpsys,
  imgsys, vdecsys and audsys clock controllers
* PLL clocks (apmixedsys)
* System configuration registers (syscfg/syscon)
* Pinctrl
* GPIO

==== Development roadmap BPI-R2

Implement missing drivers:

* Storage controller (eMMC/SD/MMC)
* Ethernet (GMAC) and the MT7530 switch
* USB 3.0 (xHCI) and T-PHY
* SATA / AHCI
* PCIe
* Watchdog
* I2C
* SPI
* PWM

==== BPI-R64 Introduction

The Banana Pi BPI-R64 is a MediaTek MT7622-based development board
(dual-core ARM Cortex-A53, ~1.35 GHz) featuring 4x Gigabit LAN, 1x Gigabit
WAN, 802.11n 4x4 Wi-Fi, Bluetooth 5.0 and a range of peripheral interfaces
(UART, SPI, I2C, GPIO, SATA, mini PCIe, eMMC and others).

==== Current State of FreeBSD Support BPI-R64

Implemented so far:

* UART driver
* Clock management (clocks)
* Pinctrl
* Storage controller (eMMC/SD/MMC)
* Ethernet driver for the MT7622 GMAC
* USB 3.0 (xHCI) driver
* T-PHY (USB and PCIe PHY)
* Watchdog driver
* RTC driver
* Random number generator driver
* PCIe configuration space driver (pciecfg)
* sysirq - the interrupt polarity controller
* PCIe - experimental
* Wi-Fi - experimental

==== Development roadmap BPI-R64

Implement missing drivers:

* SATA / AHCI, including SATA mode for the T-PHY
* GPIO
* I2C
* SPI
* PWM

Work in progress:

* Review and rework of the clock drivers
* MT7531 Ethernet switch

==== BPI-R2 Pro Introduction

The Banana Pi BPI-R2 Pro is the next generation smart router development
board, powered by a Rockchip RK3568 processor.  It carries 2 GB LPDDR4
memory and 16 GB eMMC storage, and offers two USB 3.0 ports, five Gigabit
Ethernet ports, an M.2 Key-E and a mini PCIe slot, two MIPI DSI interfaces
(one of which can be switched to LVDS in software), one MIPI CSI camera
interface and one HDMI output.

==== Current State of FreeBSD Support BPI-R2 Pro

Implemented so far:

* UART driver
* Clock management (clocks)
* Pinctrl
* GPIO
* Storage controller (eMMC/SD/MMC)
* USB 3.0 (xHCI) driver
* Watchdog driver
* PCIe driver

==== Development roadmap BPI-R2 Pro

Implement missing drivers:

* HDMI
* MIPI DSI/CSI

Work in progress:

* AHCI / SATA
* PCIe
