=== A bhyve management GUI written in Freepascal/Lazarus

Links: +
link:https://github.com/alonsobsd/bhyvemgr[Bhyvemgr] URL: link:https://github.com/alonsobsd/bhyvemgr/[] +
link:https://github.com/alonsobsd/bhyvemgrd[Bhyvemgrd] URL: link:https://github.com/alonsobsd/bhyvemgrd/[] +

Contact: José Alonso Cárdenas Márquez <acm@FreeBSD.org>

Bhyvemgr is a bhyve management GUI written in Freepascal/Lazarus on FreeBSD.
It needs a bunch of tools, mostly installed on base system, and some installed from ports/packages.
The main goal is to be a desktop application with focus on desktop users to easily and quickly setup and run virtual machines on FreeBSD hosts.

Starting with version v2.0.0, bhyvemgr was migrated to client/server architecture. As a result, a server component was developed. This new component is called bhyvemgrd.
Bhvemgrd supports two ways to run priviliged tasks: mac_do/mdo (FreeBSD >= 140000) and mac_do/setcred/exec_paths (only for FreeBSD >= 1501501). The process itself run under an unpriviliged bhyvemgrd user.

During last two quarters, there were many bugfixes and improvements to Bhyvemgr.

These are some highlights that were added:

- Add new operating system options
- Add support to use VNC unix sock (vnc.sock) when FreeBSD >= 1500509
- Add support for storage snapshot (only if zfs is enable)
- Improve TPM support
- Move to client/server architecture (unixsocket, json, etc). The bhyvemgr keeps like a client and a new bhyvemgrd app is used like a server.
- Remove privileged functions/procedures. Now they are part of bhyvemgrd.
- Remove sudo/doas support. It is not necessary anymore because privileged tasks will trigger from bhyvemgrd service.
- Remove FreeBSD 13.x support
- Replace remote-viewer support (virt-viewer) with vncviewer (tigervnc-viewer). The vncviewer needs less dependencies and it can be ligther than virt option.
- Other fixes, improvements and changes

Bhyvemgr and Bhyvemgrd supports aarch64 from 15.x to 16-CURRENT and amd64 from FreeBSD 14.x to 16-CURRENT.
Bhyvemgr can be compiled or installed from link:https://www.freshports.org/sysutils/bhyvemgr[ports] or packages with gtk2, qt5, or qt6 interface support.
Bhyvemgrd can be compiled or installed from link:https://www.freshports.org/sysutils/bhyvemgrd[ports] or packages.

People interested in helping or supporting the projects are welcome.

Current bhyvemgr version: 2.1.0
Current bhyvemgrd version: 1.2.0

Sponsor: link:https://paypal.me/alonsocbsd[]
