=== Improve libvirt support for bhyve hypervisor

Links: +
link:https://libvirt.org/drvbhyve.html[libvirt: Bhyve driver] URL: link:https://libvirt.org/drvbhyve.html[] +

Contact: Roman Bogorodskiy <novel@FreeBSD.org>

==== Completed work

* libvirt/bhyve driver:
** Added support for VLAN configuration, VLAN filtering, and isolated bridge ports on FreeBSD.
** Added boot order configuration for disk devices.
** Implemented several new APIs: domain renaming, lifecycle management, getting guest
   info using the QEMU Guest Agent, and setting QEMU Guest Agent response timeout.
** Added serial number configuration for SATA disks and NVMe controllers,
   as well as EUI-64 configuration for NVMe disks.
** Fixed several issues related to transient and persistent domain handling, monitor events,
   startup error reporting, and TAP device cleanup.
* Added `guest-get-fsinfo` support for FreeBSD to the QEMU Guest Agent.
* Extended libvirt-tck coverage for libvirt/bhyve.
* Work in progress on unprivileged `bhyve:///session` support.

==== Plans for the next quarter

* Complete unprivileged `bhyve:///session` support.
* Add support for TPM devices.
* Complete suspend/resume support.
* Continue implementing features based on the QEMU Guest Agent.
* Continue extending CI and cover the new guest-agent-based features with new tests.

Sponsor: The FreeBSD Foundation
