=== Status Report Sample - This Will Become The Title

Links: +
link:https://github.com/Yohello1/rocm-systems/tree/rebase-systems[ROCm-Systems Fork] URL: https://github.com/Yohello1/rocm-systems/tree/rebase-systems[] +
link:https://github.com/Yohello1/drm-kmod-rocm/super-special[Yohello1/drm-kmod-rocm] URL: https://github.com/Yohello1/drm-kmod-rocm/super-special[] +

Contact: Sourojeet Adhikari <siri@racha.ca>

==== Completed Work 

* amdkfd driver
** amdkfd driver now compiles, and links, and loads
** Ported v11 platform files for certain AMDGPU generations
** /dev/kfd is now exposed, and interactable
** Cleaned up undefined symbols which do not get used as of now

* ROCm Systems
** 


Paragraphs are separated with an empty line.
If at all possible, write one sentence per line and don't split a sentence between lines.
Use link:https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc syntax], if you can.
If you don't know AsciiDoc, just use plain text.

Introduce your work.
Do not assume that the person reading the report knows about your project.

Show the importance of your work.
Status reports are not just about telling everyone that things were done, they also need to explain why things were done.

What has happened since the last report?
Let us know what is new in this area.

If help is needed, make this explicit.
List tasks, with enough detail that people know if they are likely to be able to do them, and invite people to get in contact:

* First task
* Second task
* Additional tasks, if any …

Optionally include the information about the sponsor.

Sponsor: Sponsoring Organisation, if any
