#
# $FreeBSD$
#
# Article: LDAP Authentication

MAINTAINER= kurin@causa-sui.net

DOC?=	article

FORMATS?= html-split html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
