# $FreeBSD$
#
# The FreeBSD Mongolian Documentation Project
#
# Original revision 1.7

#SUBDIR = articles
SUBDIR = books

COMPAT_SYMLINK = mn

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
