---
title: Prefácio
prev: books/handbook/
next: books/handbook/parti
---

[preface]
[[book-preface]]
= Prefácio
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Índice
:table-caption: Tabela
:figure-caption: Figura
:example-caption: Exemplo
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:

[[preface-audience]]
== Audiência Pretendida

O novato no FreeBSD descobrirá que a primeira seção deste livro guia o usuário através do processo de instalação do FreeBSD e gentilmente apresenta os conceitos e convenções que sustentam o UNIX(TM). Trabalhar através desta seção exige pouco mais do que o desejo de explorar, e a capacidade de incorporar novos conceitos à medida que eles são introduzidos.

Uma vez que você chegou até aqui, a segunda seção do Handbook, muito maior, é uma referência abrangente a todos os tópicos de interesse para administradores de sistemas FreeBSD. Alguns destes capítulos podem recomendar que você faça alguma leitura prévia, e isto é destacado na sinopse no início de cada capítulo.

Para uma lista de fontes adicionais de informação, por favor veja o crossref:bibliography[bibliography, Bibliografia].

[[preface-changes-from3]]
== Mudanças desde a Terceira Edição

A versão online atual do Handbook representa o esforço cumulativo de muitas centenas de contribuidores nos últimos 10 anos. A seguir estão algumas das mudanças significativas desde a publicação da terceira edição do volume em 2004:

* crossref:dtrace[dtrace, DTrace] foi adicionado com informações sobre a poderosa ferramenta de análise de desempenho DTrace.
* crossref:filesystems[filesystems, Outros Sistemas de Arquivos] foi adicionado com informações sobre sistemas de arquivos não-nativos no FreeBSD, como o ZFS da Sun(TM).
* crossref:audit[audit, Auditoria de Evento de Segurança] foi adicionado para cobrir os novos recursos de auditoria no FreeBSD e explicar seu uso.
* crossref:virtualization[virtualization, Virtualização] foi adicionado com informações sobre a instalação do FreeBSD em ambientes virtualizados.
* crossref:bsdinstall[bsdinstall, Instalando o FreeBSD] foi adicionado para cobrir a instalação do FreeBSD usando o novo utilitário de instalação, bsdinstall.

[[preface-changes-from2]]
== Mudanças desde a Segunda Edição (2004)

A terceira edição foi o culminar de mais de dois anos de trabalho pelos membros dedicados do Projeto de Documentação do FreeBSD. A edição impressa cresceu a tal tamanho que foi necessário publicar como dois volumes separados. A seguir estão as principais mudanças nesta nova edição:

* crossref:config[config-tuning, Configuração e Ajuste] foi expandido com novas informações sobre o gerenciamento de recursos e energia da ACPI, o utilitário de sistema `cron` e mais opções para ajuste do kernel.
* crossref:security[security, Segurança] foi expandido com novas informações sobre redes virtuais privadas (VPNs), listas de controle de acesso (ACLs) do sistema de arquivos e avisos de segurança.
* crossref:mac[mac, Controle de acesso obrigatório] é um novo capítulo desta edição. Ele explica o que é MAC e como esse mecanismo pode ser usado para proteger um sistema FreeBSD.
* crossref:disks[disks, Armazenamento] foi expandido com novas informações sobre dispositivos de armazenamento USB, snapshots do sistema de arquivos, cotas do sistema de arquivos, arquivos e sistemas de arquivos com suporte de rede e partições de disco criptografadas.
* Uma seção de solução de problemas foi adicionada ao crossref:ppp-and-slip[ppp-and-slip, PPP].
* crossref:mail[mail, Correio Eletrônico] foi expandido com novas informações sobre o uso de agentes de transporte alternativos, autenticação SMTP, UUCP, fetchmail, procmail e outros tópicos avançados.
* crossref:network-servers[network-servers, Servidores de Rede] é novidade nesta edição. Este capítulo inclui informações sobre a configuração do Servidor HTTP Apache, ftpd e a configuração de um servidor para clientes Microsoft(TM)Windows(TM) com Samba. Algumas seções do crossref:advanced-networking[advanced-networking, Rede Avançada] foram movidas para cá para melhorar a apresentação.
* crossref:advanced-networking[advanced-networking, Rede Avançada] foi expandido com novas informações sobre o uso de dispositivos Bluetooth(TM) com o FreeBSD, configuração de redes sem fio e redes ATM (Asynchronous Transfer Mode).
* Um glossário foi adicionado para fornecer um local central para as definições de termos técnicos utilizados ao longo do livro.
* Uma série de melhorias estéticas foram feitas nas tabelas e figuras ao longo do livro.

[[preface-changes]]
== Mudanças desde a Primeira Edição (2001)

A segunda edição foi o culminar de mais de dois anos de trabalho pelos membros dedicados do Projeto de Documentação do FreeBSD. A seguir, as principais mudanças nesta edição:

* Um índice completo foi adicionado.
* Todas as figuras ASCII foram substituídas por diagramas gráficos.
* Uma sinopse padrão foi adicionada a cada capítulo para fornecer um resumo rápido de quais informações o capítulo contém e o que se espera que o leitor saiba.
* O conteúdo foi logicamente reorganizado em três partes: "Introdução", "Administração do Sistema" e "Apêndices".
* crossref:basics[basics, Fundamentos do FreeBSD] foi expandido para conter informações adicionais sobre processos, daemons e sinais.
* crossref:ports[ports, Instalando Aplicativos. Pacotes e Ports] foi expandido para conter informações adicionais sobre o gerenciamento de pacotes binários.
* crossref:x11[x11, O sistema X Window] foi completamente reescrito com ênfase no uso de tecnologias de desktop modernas como KDE e GNOME sobre o XFree86(TM) 4.X.
* crossref:boot[boot, O processo de inicialização do FreeBSD] foi expandido.
* crossref:disks[disks, Armazenamento] foi escrito a partir do que costumava ser dois capítulos separados em "Discos" e "Backups". Sentimos que os tópicos são mais fáceis de compreender quando apresentados como um único capítulo. Uma seção sobre RAID (hardware e software) também foi adicionada.
* crossref:serialcomms[serialcomms, Comunicações Seriais] foi completamente reorganizado e atualizado para o FreeBSD 4.X/5.X.
* crossref:ppp-and-slip[ppp-and-slip, PPP] foi substancialmente atualizado.
* Muitas novas seções foram adicionadas ao crossref:advanced-networking[advanced-networking, Rede Avançada].
* crossref:mail[mail, Correio Eletrônico] foi expandido para incluir mais informações sobre a configuração do sendmail.
* crossref:linuxemu[linuxemu, Compatibilidade binária com o Linux®] foi expandido para incluir informações sobre como instalar o Oracle(TM) e o SAP(TM)R/3(TM).
* Os novos tópicos a seguir são abordados nesta segunda edição:

** crossref:config[config-tuning, Configuração e Ajuste].
** crossref:multimedia[multimedia, Multimídia].

[[preface-overview]]
== Organização deste Livro

Este livro é dividido em cinco seções logicamente distintas. A primeira seção, _Introdução_, cobre a instalação e o uso básico do FreeBSD. Espera-se que o leitor siga estes capítulos em sequência, possivelmente ignorando capítulos que abordam tópicos familiares. A segunda seção, _Tarefas Comuns_, cobre alguns dos recursos mais usados do FreeBSD. Esta seção e todas as seções subsequentes podem ser lidas fora de ordem. Cada capítulo começa com uma sinopse sucinta que descreve o que o capítulo cobre e o que se espera que o leitor já conheça. Isso permite que o leitor casual pule para encontrar capítulos de interesse. A terceira seção, _Administração do Sistema_, cobre tópicos de administração. A quarta seção, _Comunicação de Rede_, aborda tópicos sobre redes e servidores. A quinta seção contém apêndices de informações de referência.

_crossref:introduction[introduction, Introdução]_::
Introduz o FreeBSD para um novo usuário. Descreve a história do projeto FreeBSD, seus objetivos e modelo de desenvolvimento.

_crossref:bsdinstall[bsdinstall, Instalando o FreeBSD]_::
Guia o usuário durante todo o processo de instalação do FreeBSD 9._x_ usando o bsdinstall.

_crossref:basics[basics, Fundamentos do FreeBSD]_::
Cobre os comandos básicos e a funcionalidade do sistema operacional FreeBSD. Se você está familiarizado com Linux(TM) ou outro tipo de UNIX(TM), provavelmente você pode pular este capítulo.

_crossref:ports[ports, Instalando Aplicativos. Pacotes e Ports]_::
Cobre a instalação de softwares de terceiros com a inovadora "Coleção de Ports" do FreeBSD, e com pacotes binários tradicionais.

_crossref:x11[x11, O sistema X Window]_::
Descreve o Sistema X Window em geral e usa o X11 no FreeBSD em particular. Também descreve ambientes comuns de desktop, como o KDE e GNOME.

_crossref:desktop[desktop, Aplicações de Desktop]_::
Lista alguns aplicativos comuns de desktop, como navegadores web e pacotes de produtividade, e descreve como instalá-los no FreeBSD.

_crossref:multimedia[multimedia, Multimídia]_::
Mostra como configurar o suporte a reprodução de som e vídeo para o seu sistema. Também descreve alguns exemplos de aplicativos de áudio e vídeo.

_crossref:kernelconfig[kernelconfig, Configurando o kernel do FreeBSD]_::
Explica o porque que você pode precisar configurar um novo kernel e fornece instruções detalhadas para configurar, compilar e instalar um kernel personalizado.

_crossref:printing[printing, Impressão]_::
Descreve o gerenciamento de impressoras no FreeBSD, incluindo informações sobre páginas de banner, contabilidade de impressoras e configuração inicial.

_crossref:linuxemu[linuxemu, Compatibilidade binária com o Linux®]_::
Descreve os recursos de compatibilidade Linux(TM) do FreeBSD. Também fornece instruções detalhadas de instalação para muitos aplicativos Linux(TM) populares, como o Oracle(TM) e o Mathematica(TM).

_crossref:config[config-tuning, Configuração e Ajuste]_::
Descreve os parâmetros disponíveis para os administradores do sistema ajustarem um sistema FreeBSD para um ótimo desempenho. Também descreve os vários arquivos de configuração usados no FreeBSD e onde encontrá-los.

_crossref:boot[boot, O processo de inicialização do FreeBSD]_::
Descreve o processo de inicialização do FreeBSD e explica como controlar este processo com opções de configuração.

_crossref:security[security, Segurança]_::
Descreve muitas ferramentas diferentes disponíveis para ajudar a manter seu sistema FreeBSD seguro, incluindo Kerberos, IPsec e OpenSSH.

_crossref:jails[jails, Jails]_::
Descreve o framework do jail e as suas vantagens sobre o chroot tradicional do FreeBSD.

_crossref:mac[mac,Controle de acesso obrigatório]_::
Explica o que é o Mandatory Access Control (MAC) e como esse mecanismo pode ser usado para proteger um sistema FreeBSD.

_crossref:audit[audit, Auditoria de Evento de Segurança]_::
Descreve o que é a Auditoria de Eventos do FreeBSD, como ela pode ser instalada, configurada e como as trilhas de auditoria podem ser inspecionadas ou monitoradas.

_crossref:disks[disks, Armazenamento]_::
Descreve como gerenciar mídias de armazenamento e sistemas de arquivos com o FreeBSD. Isto inclui discos físicos, matrizes RAID, mídias óticas e de fita, discos com suporte de memória e sistemas de arquivos de rede.

_crossref:geom[geom, GEOM. Framework de Transformação de Disco Modular]_::
Descreve o que é o framework GEOM do FreeBSD e como configurar os vários níveis suportados de RAID.

_crossref:filesystems[filesystems, Outros Sistemas de Arquivos]_::
Examina o suporte a sistemas de arquivos não-nativos no FreeBSD, como o Z File System da Sun(TM).

_crossref:virtualization[virtualization, Virtualização]_::
Descreve o que os sistemas de virtualização oferecem e como eles podem ser usados com o FreeBSD.

_crossref:l10n[l10n, Localização - Uso e Configuração do i18n/L10n]_::
Descreve como usar o FreeBSD em outros idiomas além do inglês. Abrange a localização tanto em nível de sistema como em nível de aplicativo.

_crossref:cutting-edge[updating-upgrading, Atualização e Upgrade do FreeBSD]_::
Explica as diferenças entre FreeBSD-STABLE, FreeBSD-CURRENT e FreeBSD releases. Descreve quais usuários se beneficiariam do uso de um sistema em desenvolvimento e descreve este processo. Cobre os métodos que os usuários podem usar para atualizar seu sistema para a última release de segurança.

_crossref:dtrace[dtrace, DTrace]_::
Descreve como configurar e usar a ferramenta DTrace da Sun(TM) no FreeBSD. O rastreamento dinâmico pode ajudar a localizar problemas de desempenho, realizando a análise do sistema em tempo real.

_crossref:serialcomms[serialcomms, Comunicações Seriais]_::
Explica como conectar terminais e modems ao seu sistema FreeBSD para conexões de discagem de entrada e de saída.

_crossref:ppp-and-slip[ppp-and-slip, PPP]_::
Descreve como usar o PPP para se conectar a sistemas remotos com o FreeBSD.

_crossref:mail[mail, Correio Eletrônico]_::
Explica os diferentes componentes de um servidor de e-mail e mergulha em tópicos simples de configuração do software mais popular de servidor de e-mails: o sendmail.

_crossref:network-servers[network-servers, Servidores de Rede]_::
Fornece instruções detalhadas e exemplos de arquivos de configuração para configurar sua máquina FreeBSD como um servidor de sistema de arquivos de rede, servidor de nome de domínio, servidor de sistema de informações de rede ou servidor de sincronização de horário.

_crossref:firewalls[firewalls, Firewalls]_::
Explica a filosofia por trás dos firewalls baseados em software e fornece informações detalhadas sobre a configuração dos diferentes firewalls disponíveis para o FreeBSD.

_crossref:advanced-networking[advanced-networking, Rede Avançada]_::
Descreve muitos tópicos de rede, incluindo o compartilhamento de uma conexão à Internet com outros computadores em sua LAN, tópicos avançados de roteamento, rede sem fio, Bluetooth(TM), ATM, IPv6 e muito mais.

_crossref:mirrors[mirrors, Obtendo o FreeBSD]_::
Lista diferentes fontes para obter a mídia de instalação do FreeBSD em CD-ROM ou DVD, bem como diferentes sites na Internet que permitem que você baixe e instale o FreeBSD.

_crossref:bibliography[bibliography, Bibliografia]_::
Este livro aborda muitos assuntos diferentes que podem deixá-lo com a curiosidade de uma explicação mais detalhada. A bibliografia lista muitos livros excelentes que são referenciados no texto.

_crossref:eresources[eresources, Recursos na Internet]_::
Descreve os muitos fóruns disponíveis para usuários do FreeBSD postarem perguntas e se engajarem em conversas técnicas sobre o FreeBSD.

_crossref:pgpkeys[pgpkeys, Chaves OpenPGP]_::
Lista as fingerprints PGP de vários desenvolvedores do FreeBSD.

[[preface-conv]]
== Convenções utilizadas neste livro

Para fornecer um texto consistente e fácil de ler, várias convenções são seguidas ao longo do livro.

[[preface-conv-typographic]]
=== Convenções Tipográficas

_Itálico_::
Uma fonte _itálica_ é usada para nomes de arquivos, URLs, textos enfatizados e o primeiro uso de termos técnicos.

`Monospace`::
Uma fonte `monoespaçada` é usada para mensagens de erro, comandos, variáveis de ambiente, nomes de ports, nomes de host, nomes de usuários, nomes de grupos, nomes de dispositivos, variáveis e fragmentos de código.

Negrito::
Uma fonte kbd:[negrita] é usada para aplicativos, comandos e chaves.

[[preface-conv-commands]]
=== Entrada do Usuário

As teclas são mostradas em *negrito* para se destacar do restante do texto. As combinações de teclas que devem ser digitadas simultaneamente são mostradas com `+` entre as teclas, como:

kbd:[Ctrl+Alt+Del]

Isso significa que o usuário deve digitar as teclas kbd:[Ctrl], kbd:[Alt] e kbd:[Del] ao mesmo tempo.

As teclas que devem ser digitadas em sequência serão separadas por vírgulas, por exemplo:

kbd:[Ctrl+X], kbd:[Ctrl+S]

Significaria que o usuário deve digitar as teclas kbd:[Ctrl] e kbd:[X] simultaneamente e, em seguida, digitar as teclas kbd:[Ctrl] e kbd:[S] simultaneamente.

[[preface-conv-examples]]
=== Exemplos

Exemplos começando com [.filename]#C:\># indicam um comando MS-DOS(TM). Salvo indicação em contrário, estes comandos podem ser executados a partir de uma janela de "Prompt de Comando" em um ambiente Microsoft(TM)Windows(TM).

[source,bash]
....
E:\> tools\fdimage floppies\kern.flp A:
....

Exemplos começando com `#` indicam um comando que deve ser executado como superusuário no FreeBSD. Você pode logar como `root` para digitar o comando, ou logar como sua conta normal e usar o comando man:su[1] para obter privilégios de superusuário.

[source,bash]
....
# dd if=kern.flp of=/dev/fd0
....

Exemplos começando com `%` indicam um comando que deve ser chamado a partir de uma conta de usuário normal. Salvo indicação em contrário, a sintaxe C-shell é usada para definir variáveis de ambiente e outros comandos do shell.

[source,bash]
....
% top
....

[[preface-acknowledgements]]
== Agradecimentos

O livro que você está segurando representa os esforços de muitas centenas de pessoas em todo o mundo. Não importa se eles enviaram correções para erros de digitação ou submeteram capítulos completos, todas as contribuições foram úteis.

Várias empresas têm apoiado o desenvolvimento deste documento, pagando aos autores para trabalhar em tempo integral, pagando pela publicação, etc. Em particular, a BSDi (posteriormente adquirida pela http://www.windriver.com[Wind River Systems]) pagou membros do Projeto de Documentação do FreeBSD para trabalhar na melhoria deste livro em tempo integral, levando à publicação da primeira edição impressa em março de 2000 (ISBN 1-57176-241-8). A Wind River Systems pagou vários autores adicionais para fazer uma série de melhorias na infraestrutura de impressão e adicionar capítulos adicionais ao texto. Este trabalho culminou com a publicação da segunda edição impressa em novembro de 2001 (ISBN 1-57176-303-1). Em 2003-2004, a http://www.freebsdmall.com[FreeBSD Mall, Inc.] pagou a vários contribuidores para melhorar o Handbook em preparação para a terceira edição impressa.
