# $FreeBSD$
# $FreeBSDru: frdp/www/ru/alpha/Makefile,v 1.2 2000/10/27 11:26:09 phantom Exp $
 
.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=   alpha.sgml
 
INDEXLINK=alpha.html
 
.include "../web.mk"
