# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/alpha/Makefile,v 1.4 2000/11/29 12:50:51 phantom Exp $
# Original revision: 1.8
 
.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   alpha.sgml
 
INDEXLINK=alpha.html
 
.include "${WEB_PREFIX}/share/mk/web.site.mk"
