# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/alpha/Makefile,v 1.3 2000/11/10 17:04:48 phantom Exp $
# Original revision: 
 
.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   alpha.sgml
 
INDEXLINK=alpha.html
 
.include "${WEB_PREFIX}/share/mk/web.site.mk"
