# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

# DOCS=	hardware.xml relnotes.xml installation.xml
# DOCS+=	announce.xml
# contents.xml
DOCS= relnotes.xml

# DATA=	docbook.css
# DATA+=	errata.html
# DATA+=	hardware-alpha.html
# DATA+=	hardware-i386.html
# DATA+=	hardware-sparc64.html
# DATA+=	relnotes-alpha.html
# DATA+=	relnotes-i386.html
# DATA+=	relnotes-sparc64.html
# DATA+=	installation-alpha.html
# DATA+=	installation-i386.html
# DATA+=	installation-sparc64.html
# DATA+=  cd1.txt cd2.txt cd3.txt cd4.txt

.include "${DOC_PREFIX}/share/mk/web.site.mk"
