#
#    The FreeBSD Documentation Project
#    The FreeBSD Norwegian Documentation Project
#
#    $FreeBSD$
#

SUBDIR= handbook

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
