# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.xml \
	todo.xml

DATA=	docbook.css \
	installation.html \
	relnotes.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
