# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/conspectus/Makefile,v 1.2 2000/11/10 17:04:48 phantom Exp $
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml 

#SUBDIR=	stable

.include "${WEB_PREFIX}/share/mk/web.site.mk"
