# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/conspectus/Makefile,v 1.1 2000/10/11 16:11:18 phantom Exp $
# Original revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=   index.sgml 

#SUBDIR=	stable

.include "../web.mk"
