# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/conspectus/Makefile.inc,v 1.2 2000/11/10 17:04:48 phantom Exp $
# Original revision: 1.2

WEBBASE?=	/data/ru/conspectus
WEB_PREFIX?=	${.CURDIR}/../../..
