# $FreeBSD: www/en/releases/2.2.2R/Makefile,v 1.3 2000/11/07 04:05:29 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	notes.sgml
DOCS+=	errata.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
