---
description: 'Введение во вспомогательные технологии в FreeBSD'
next: books/accessibility/parti
params:
  path: /books/accessibility/preface/
prev: books/accessibility
showBookMenu: 'true'
tags: ["preface"]
title: Предисловие
weight: 1
---

[preface]
[[a11y-preface]]
= Предисловие
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:source-highlighter: rouge
:experimental:
:images-path: books/accessibility/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[intended-audience]]
== Целевая аудитория

Это руководство предназначено для всех, кто интересуется вспомогательными технологиями, доступными в операционной системе FreeBSD. Пользователи и администраторы могут узнать, как настроить систему для обеспечения доступности. Разработчики найдут ресурсы и рекомендации, которые помогут им создавать, улучшать и тестировать доступное программное обеспечение.

[[organization-book]]
== Организация этой книги

Эта книга организована по разделам, главам и параграфам, каждый из которых можно читать независимо и в произвольном порядке. Первый раздел, _crossref:parti[parti-general,Часть I. Общие сведения]_, содержит рекомендации о том, как искать помощь, и включает различные дополнительные темы. Второй раздел, _crossref:partii[partii-vision,Часть II. Зрение]_, посвящен вспомогательным технологиям для визуальной доступности; он сознательно не содержит изображений для максимальной доступности. Все разделы и главы самодостаточны и могут быть прочитаны в любом порядке.

Главы:

_crossref:help[help,Справка]_::
Объясняет, где и как искать поддержку в сообществе FreeBSD.

_crossref:virtual-terminal[virtual-terminal,Виртуальный терминал]_::
Выделяет особенности виртуальной консоли системы для визуальной доступности.

_crossref:colors[colors,Цвета]_::
Описывает, как настроить параметры цвета в графических средах для улучшения видимости.

_crossref:lowvision[lowvision,Низкое зрение]_::
Представляет инструменты и настройки для пользователей с ослабленным зрением.

_crossref:blindness[blindness,Слепота]_::
Охватывает инструменты и настройки доступности для незрячих пользователей, включая экранные читалки, текстовые утилиты и соответствующие порты.

_crossref:development[development,Разработка]_::
Предоставляет рекомендации и ресурсы для разработчиков по улучшению доступности для пользователей с нарушениями зрения.

[[commands]]
== Команды

FreeBSD предоставляет мощный интерфейс командной строки, который позволяет пользователям выполнять широкий спектр текстовых команд для настройки и использования операционной системы. Данное Руководство, как и вся официальная документация FreeBSD, следует следующим соглашениям о командной строке:

- Команда, предварённая символом `%`, может быть выполнена любым обычным пользователем.
- Команда, перед которой стоит `#`, должна быть выполнена пользователем `root` (системным администратором).

