# $FreeBSD: www/en/releases/4.9R/Makefile,v 1.4 2003/10/29 07:30:30 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	hardware.sgml relnotes.sgml schedule.sgml todo.sgml qa.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
