# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	faq.xml
DOCS+=	howtoports.xml
DOCS+=	newbies.xml
DOCS+=	tutorials.xml
DOCS+=	performance.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
