# $FreeBSD$
# $FreeBSDde: de-www/gifs/Makefile,v 1.1 2003/05/11 17:38:16 mheinen Exp $
# basiert auf: 1.44

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   bar.gif

.include "${WEB_PREFIX}/share/mk/web.site.mk"
