---
title: "FreeBSD/alpha Project"
sidenav: developers
---

= FreeBSD/alpha Project

This page contains information about the FreeBSD port to HP/Compaq Alpha systems.

== Status

As of FreeBSD 7.0, support for the Alpha platform has been removed. The development of new Alpha systems has been discontinued by the hardware vendor; this combined with the widespread deployment of more mainstream 64-bit platforms, such as the AMD64 and Intel EM64T architectures, has resulted in significantly reduced user and developer community interest.

== FreeBSD/alpha mailing list

Because of the dropped support for the Alpha plattform the mailing list _freebsd-alpha_ has been closed. Although it is no longer possible to send messages to this mailing list, the archives can still be https://www.freebsd.org/search/#mailinglists[searched] or https://docs.freebsd.org/mail/archive/freebsd-alpha.html[browsed].

== Other Links of Interest

=== Hardware

* http://h18002.www1.hp.com/alphaserver/[HP AlphaServer]
* http://h18002.www1.hp.com/alphaserver/workstations.html[HP AlphaStation]

=== Projects

* http://www.NetBSD.org/ports/alpha/[NetBSD/alpha]
* http://www.OpenBSD.org/alpha.html[OpenBSD/alpha]
