---
title: "FreeBSD/pc98 Project"
sidenav: developers
---

include::shared/en/urls.adoc[]

= FreeBSD/pc98 Project

== Introduction

FreeBSD/pc98 is a port of FreeBSD which aims to run on the NEC PC-98x1 (pc98) architecture. The project's goal is to make FreeBSD/pc98 work the same as FreeBSD on other architectures. Most of the kernel source is already included in the FreeBSD source tree and most of the userland utilities built from the source work fine.

== Status

FreeBSD/pc98 support was removed from 12.0 in revision `r312910`.

FreeBSD/pc98 was a link:{committers-guide}#archs[Tier 2] architecture at the time of 9.0-RELEASE.

Although FreeBSD/pc98 was a Tier 1 for a long time since 5.0-RELEASE, it was downgraded due to FreeBSD no longer supporting installation from floppy disks, and most pc98 machines cannot boot from CD/DVD. Although later pc98 machines can boot from CDROM, FreeBSD's support for that has not been integrated into bsdinstall and release tools.

== FreeBSD/pc98 Related Links

* http://www.jp.FreeBSD.org/pc98/index.html.en[FreeBSD(98) Project]
* http://www.nisoc.or.jp/~karl/freebsd-pc98/[Unofficial guide to FreeBSD(98) by karl (Japanese)]
* http://www32.ocn.ne.jp/~chi/FreeBSD/[Chi's personal notes on FreeBSD(98) (Japanese)]
* https://people.FreeBSD.org/~kato/pc98.html[Kato's page]
