# $FreeBSD: www/en/ports/Makefile.inc0,v 1.3 2000/09/30 00:21:39 nbm Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif
.if exists(Makefile.inc)
.include "Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif

.include "${WEB_PREFIX}/share/mk/web.site.mk"
