#	$Id: Makefile.inc0,v 1.1 1999-05-15 10:16:06 wosch Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(Makefile.inc)
.include "Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif


.include "../web.mk"
