#!/bin/sh
# Copyright (c) June 1998 Wolfram Schneider <wosch@FreeBSD.ORG>, Berlin.
#
# packages - create a sorted list of precompiled packages which
#            are available at the FreeBSD FTP Server.
#
# $FreeBSD: www/en/ports/packages,v 1.8 2001/04/25 22:59:57 wosch Exp $

PATH=/bin:/usr/bin:/usr/local/bin; export PATH

release='packages-stable';
url="ftp://ftp.freebsd.org/pub/FreeBSD/ports/i386/$release/All/"

temp=_lynx$$

if lynx -source "$url" > $temp || ( sleep 300; lynx -source "$url" > $temp ) || ( sleep 300; lynx -source "$url" > $temp )
then
    perl -ne 'print $1, "\n" if m%href="([^"]+)"%oi' < $temp |
    perl -npe  's%.*/%%' | sort | grep -v '^\.\.$'
    rm -f $temp
else
	rm -f $temp
	exit 1
fi
