---
title: Hoofdstuk 6. Het X Window systeem
part: Deel I. Beginnen
prev: books/handbook/ports
next: books/handbook/partii
---

[[x11]]
= Het X Window systeem
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Inhoudsopgave
:table-caption: Tabel
:figure-caption: Afbeelding
:example-caption: Voorbeeld
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 6

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/x11/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/x11/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/x11/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/nl/mailing-lists.adoc[]
include::shared/nl/teams.adoc[]
include::shared/nl/urls.adoc[]

toc::[]

[[x11-synopsis]]
== Overzicht

FreeBSD gebruikt X11 om gebruikers een krachtige grafische gebruikersschil te bieden. X11 is een vrij beschikbare versie van het X Window System dat geïmplementeerd is in XorgXFree86(TM) (en andere softwarepakketten die hier niet worden besproken). De standaard en officiele smaak van X11 in FreeBSD is Xorg, de X11-server die is ontwikkeld door de X.Org Foundation onder een licentie die veel lijkt op degene die door FreeBSD wordt gebruikt.

Meer informatie over de videohardware die X11 ondersteunt kan gevonden worden op de http://www.x.org/[Xorg] website.

Na het lezen van dit hoofdstuk weet de lezer:

* Wat de componenten van het X Window systeem zijn en hoe zij samenwerken.
* Hoe X11 geïnstalleerd en ingesteld kan worden.
* Hoe verschillende window managers geïnstalleerd en gebruikt kunnen worden.
* Hoe TrueType(R) lettertypen in X11 te gebruiken.
* Hoe het systeem ingesteld moet worden voor grafisch aanmelden (XDM).

Aangeraden voorkennis:

* Hoe extra software van derden te installeren (crossref:ports[ports,Applicaties installeren. pakketten en ports]).

[[x-understanding]]
== X begrijpen

X voor de eerste keer gebruiken kan een hele schok zijn voor mensen die gewend zijn aan andere grafische omgevingen, zoals Microsoft(R) Windows(R) of Mac OS(R).

Het is niet noodzakelijk om alle details te kennen over de X componenten en hoe zij samenwerken, maar enige basiskennis draagt wel bij aan krachtiger gebruik kunnen maken van X.

=== Waarom X?

X is niet het eerste windows systeem dat geschreven is voor UNIX(R), maar wel het meest populaire. Het oorspronkelijke X ontwikkelteam werkte eerst aan een ander window systeem. De naam van dat systeem was "W" (van "Window"). X was gewoon de volgende letter in het alfabet.

X kan gewoon "X", "X Window systeem", "X11" of nog anders genoemd worden. X11 "X Windows" noemen kan door sommigen als een belediging opgevat worden. man:X[7] kan hierover wat licht laten schijnen.

=== Het X client/server model

X is vanaf het begin aan ontworpen om netwerk-centraal te zijn en gebruikt een "client-server" model.

In het X model draait de "X server" op de computer waar het toetsenbord, beeldscherm en muis aan vast zit. De server is verantwoordelijk voor het regelen van beeldinformatie, verwerken van invoer van toetsenbord en muis, en andere invoer- of uitvoerapparaten (i.e., een "tablet" kan als invoerapparaat worden gebruikt, en een videoprojector kan een alternatief uitvoerapparaat zijn). Iedere X applicatie (zoals XTerm of Firefox) is een "cliënt". Een cliënt stuurt berichten naar de server zoals "teken een venster op deze coördinaten" en de server stuurt berichten terug zoals "de gebruiker heeft op de OK knop gedrukt".

Thuis of in kleine bedrijven draaien zowel de X server als de X clients op dezelfde machine. Het is heel goed mogelijk dat de X server op een minder krachtige desktop computer draait en de X applicaties (de clients) op een, zeg maar, dure krachtige machine van het bedrijf. Hier vindt de communicatie tussen de X client en server plaats over het netwerk.

Dit verwart sommige mensen, omdat de X terminologie geheel omgekeerd is aan wat ze verwachten. Dat is namelijk dat de "X server" de grote krachtige machine aan het eind van de gang is en de "X client" de machine op hun bureau is.

[NOTE]
====
De X server is de machine met het beeldscherm en het toetsenbord en de X clients zijn de programma's die de vensters tonen.
====

Het protocol vereist niet dat de clients en servers hetzelfde besturingssysteem moeten draaien of hetzelfde soort computer moeten zijn. Het is heel goed mogelijk om X server op een Microsoft(R) Windows(R) of Apple's Mac OS(R) te draaien en er zijn verschillende gratis en commerciële applicaties die dat doen.

=== De window manager

De filosofie van het X ontwerp lijkt veel op die van UNIX(R): "gereedschappen, geen beleid". Dit houdt in dat X niet bepaalt hoe een taak volbracht moet worden. In plaats daarvan worden gereedschappen geleverd aan de gebruiker die verantwoordelijk is voor het juiste gebruik hiervan.

Deze filosofie verbreedt zich door X niet te laten bepalen hoe vensters er moeten uitzien op het scherm, hoe ze verplaatst moeten worden met de muis, welke toetsaanslagen gebruikt moeten worden om te schakelen tussen vensters (bijvoorbeeld kbd:[Alt+Tab] in het geval van Microsoft(R) Windows(R)), hoe de titelbalken eruit moeten zien, of ze wel of niet sluitknoppen moeten hebben, enzovoort.

In plaats daarvan delegeert X deze verantwoordelijkheid aan een applicatie die "Window Manager" heet. Er zijn http://xwinman.org/[tientallen window managers] beschikbaar voor X. Elk van deze window managers heeft een eigen voorkomen en werking. Er zijn window managers met "virtual desktops" of met eigen toetscombinaties om de desktop te beheren; of hebben een "Start" knop of iets gelijksoortig. Sommige gebruiken "thema's" die uiterlijk en beleving compleet veranderen door een nieuw thema te kiezen. Window managers zijn te vinden in de categorie [.filename]#x11-wm# van de Portscollectie.

De KDE en GNOME desktop omgevingen hebben hun eigen window managers die in het bureaublad zijn geïntegreerd.

Iedere windows manager heeft zijn eigen manier van instellen. Sommige werken met handgetypte bestanden, anderen beschikken over grafische gereedschappen voor de meeste instellingen. Er is er minstens één (Sawfish) waarvan het instellingenbestand is geschreven in een dialect van de taal Lisp.

[NOTE]
.Focusbeleid
====
De window manager is ook verantwoordelijk voor het "focusbeleid" van de muis. Ieder window geörienteerd systeem heeft een manier nodig om te bepalen welk venster actief is, toetsaanslagen ontvangt en daarbij zichtbaar aangeeft welk venster actief is.

Een bekend focus beleid heet "click-to-focus". Dit model wordt gebruikt door Microsoft(R) Windows(R), waarbij een venster actief wordt door er met de muis op te klikken.

X ondersteunt geen specifiek focusbeleid. In plaats daarvan bepaalt de window manager op welk venster, op welk moment, de focus ligt. Een aantal window managers ondersteunen verschillende focusmethoden. Ze ondersteunen allemaal "click to focus" en de meerderheid ondersteunt ook nog andere.

De meest populaire zijn:

focus-volgt-muis (focus-follows-mouse)::
Het venster dat onder de muis zit is het venster waarop de focus ligt. Dit hoeft niet het venster te zijn dat bovenop alle andere vensters ligt. De focus verandert door te wijzen naar een ander venster. Het is niet nodig om er ook nog eens op te klikken.

slordige-focus (sloppy-focus)::
Dit beleid is een kleine uitbreiding op focus-follows-mouse. Indien bij focus-follows-mouse de muis over het root venster (of de achtergrond) gaat, ligt op geen enkel venster de focus en gaan alle toetsaanslagen verloren. Bij sloppy-focus, verandert de focus alleen als de muis in een nieuw venster komt en niet als het huidige venster wordt verlaten.

klik-voor-focus (click-to-focus)::
Het actieve venster wordt geselecteerd door erop te klikken. Het venster wordt dan "opgetild" en verschijnt dan voor alle andere vensters. Alle toetsaanslagen worden nu naar dit venster gestuurd, zelfs als de cursor naar een ander scherm wordt verplaatst.

Veel window managers ondersteunen andere soorten of variaties op de bovenstaande typen muisbeleid. Hierover staat meestal meer in de documentatie van de betreffende window manager.
====

=== Widgets

De X aanpak door gereedschappen te leveren en niets af te dwingen breidt zich uit naar de widgets die in elk applicatievenster te zien zijn.

"Widget" is een term voor alle dingen van de gebruikersinterface waarop geklikt kan worden of een andere actie mee uitgevoerd kan worden: knoppen, vinkvakjes, iconen, lijsten en ga zo maar door. Microsoft(R) Windows(R) noemt ze "controls".

Microsoft(R) Windows(R) en Apple's Mac OS(R) hebben beide een erg strikt widgetbeleid. Van de applicatieontwikkelaars wordt verwacht dat hun applicaties eenduidig zijn wat betreft uiterlijk en beleving. Bij X is ervoor gekozen geen grafische stijl of widgets te verplichten.

X applicaties hebben dus niet allemaal hetzelfde uiterlijk. Er zijn populaire widgetsets en variaties, inclusief Qt, gebruikt door KDE, of GTK+ van het GNOME project. Vanuit dit oogpunt lijkt het enigszins op de UNIX(R) desktop, wat het makkelijker maakt voor de beginnende gebruiker.

[[x-install]]
== X11 installeren

Xorg is de X11-implementatie voor FreeBSD. Xorg is de X11 server van de open source implementatie die is uitgebracht door de X.Org Foundation. Xorg is gebaseerd op de code van XFree86(TM) 4.4RC2 en X11R6.6. De versie van Xorg die momenteel beschikbaar is in de FreeBSD Portscollectie is 7.7.

Om Xorg vanuit de Portscollectie te bouwen en te installeren:

[source,bash]
....
# cd /usr/ports/x11/xorg
# make install clean
....

[NOTE]
====
Om Xorg compleet te bouwen is tenminste 4 GB vrije schijfruimte nodig.
====

X11 kan ook als pakket geïnstalleerd worden doordat er binaire pakketten beschikbaar zijn voor man:pkg_add[1]. Als hiervoor de optie "remote fetching" van man:pkg_add[1] wordt gebruikt, dan moet het versienummer verwijderd worden. man:pkg_add[1] haalt automatisch de laatste versie van het programma op.

Om het pakket voor Xorg op te halen en te installeren:

[source,bash]
....
# pkg_add -r xorg
....

[NOTE]
====
Het voorbeeld hierboven installeert de complete X11 distributie inclusief de servers, clients, lettertypen enz. Er zijn ook afzonderlijke pakketten en ports beschikbaar voor verschillende delen van X11.

Om een minimale X11-distributie te installeren kunt u als alternatief package:x11/xorg-minimal[] installeren.
====

De rest van dit hoofdstuk licht toe hoe X11 wordt ingesteld en hoe een productieve desktopomgeving gebouwd kan worden.

[[x-config]]
== X11 instellen

=== Voorbereiding

In de meeste gevallen configureert X11 zichzelf. Voor degenen met oudere of ongebruikelijke apparatuur kan het nuttig zijn om informatie over de hardware te verzamelen voordat er met de configuratie wordt begonnen.

* Monitor synchronisatiefrequenties
* Chipset van de videokaart
* Geheugen van de videokaart

De schermresolutie en ververssnelheid worden bepaald door de horizontale en verticale synchronisatiefrequenties. Bijna alle monitoren ondersteunen het automatisch elektronisch detecteren van deze waardes. Sommige monitoren geven deze waardes niet, dus moeten de specificaties worden bepaald uit de geprinte handleiding of van de website van de fabrikant.

De chipset van de videokaart wordt ook automatisch gedetecteerd en gebruikt om het juiste videostuurprogramma te selecteren. Het kan handig voor de gebruiker zijn om te weten welke chipset is geïnstalleerd wanneer de automatische detectie niet het gewenste resultaat geeft.

Het geheugen van de videokaart bepaalt de maximale resolutie en de kleurdiepte die afgebeeld kunnen worden.

=== X11 instellen

Xorg gebruikt HAL om toetsenborden en muizen automatisch te detecteren. De ports package:sysutils/hal[] en package:devel/dbus[] worden als afhankelijkheden van package:x11/xorg[] geïnstalleerd, maar moeten met de volgende regels in het bestand [.filename]#/etc/rc.conf# worden aangezet:

[.programlisting]
....
hald_enable="YES"
dbus_enable="YES"
....

Deze diensten dienen gestart te worden (ofwel handmatig of door opnieuw op te starten) voordat er verder wordt gegaan met de configuratie of gebruik van Xorg.

Xorg werkt vaak zonder enige verdere configuratie door het volgende op de prompt te typen:

[source,bash]
....
% startx
....

De automatische configuratie kan met sommige hardware mislukken, of het kan dingen anders instellen dan gewenst is. In deze gevallen is handmatige configuratie nodig.

[NOTE]
====
Bureaubladomgevingen als GNOME, KDE, of Xfce hebben gereedschappen waarmee de gebruiker eenvoudig de schermparameters zoals de resolutie kan instellen. Dus als de standaardconfiguratie niet acceptabel is en u van plan bent om een bureaubladomgeving te installeren kunt u gewoon doorgaan met de installatie van de bureaubladomgeving en het juiste scherminstelgereedschap gebruiken.
====

Het instellen van X11 bestaat uit meerdere stappen. De eerste stap is het bouwen van een instellingenbestand. Dit kan als de supergebruiker met:

[source,bash]
....
# Xorg -configure
....

Dit genereert een kaal X11-instellingenbestand in de map [.filename]#/root# met de naam [.filename]#xorg.conf.new#. Feitelijk wordt bepaald waar de map staat door hoe er superuser rechten zijn verkregen. `$HOME` is anders bij gebruik van man:su[1] of bij direct aanmelden. Het X11 programma probeert dan de grafische hardware te detecteren en schrijft een instellingenbestand dat de juiste stuurprogramma's laadt voor de gevonden hardware van het systeem.

De volgende stap is het testen van de bestaande instellingen om te controleren of Xorg met de grafische kaart van het doelsysteem kan werken. Typ:

[source,bash]
....
# Xorg -config xorg.conf.new -retro
....

Als er een zwart/grijs rooster en een X muis cursor verschijnen was de instelling succesvol. Om de test te stoppen dient naar de virtuele console waarmee de test werd gestart overgeschakeld te worden door op kbd:[Ctrl+Alt+Fn] (kbd:[F1] voor de eerste virtuele console) en kbd:[Ctrl+C] te drukken.

[NOTE]
====
De toetsencombinatie kbd:[Ctrl+Alt+Backspace] kan ook gebruikt worden om uit Xorg te breken. Om het aan te zetten, kunt u òfwel het volgende commando uitvoeren vanaf elke X-terminal-emulator:

[source,bash]
....
% setxkbmap -option terminate:ctrl_alt_bksp
....

òf een instellingenbestand voor het toetsenbord genaamd [.filename]#x11-input.fdi# voor hald aanmaken en het in de map [.filename]#/usr/local/etc/hal/fdi/policy# opslaan. Dit bestand dient het volgende te bevatten:

[.programlisting]
....
<?xml version="1.0" encoding="utf-8"?>
<deviceinfo version="0.2">
  <device>
    <match key="info.capabilities" contains="input.keyboard">
      <merge key="input.x11_options.XkbOptions" type="string">terminate:ctrl_alt_bksp</merge>
    </match>
  </device>
</deviceinfo>
....

U moet uw machine opnieuw opstarten om hald te forceren om dit bestand te lezen.

De volgende regel dient ook aan de sectie `ServerLayout` of `ServerFlags` van [.filename]#xorg.conf.new# te worden toegevoegd:

[.programlisting]
....
Option "DontZap"	"off"
....

====

Als de muis niet werkt, dan moet deze eerst ingesteld worden. Zie crossref:install[mouse,Muisinstellingen] in het FreeBSD installatiehoofdstuk. In recente versies van Xorg worden de secties `InputDevice` in [.filename]#xorg.conf# genegeerd ten voorkeur van de automatisch gedetecteerde apparaten. Voeg de volgende regel aan de sectie `ServerLayout` of `ServerFlags` van dit bestand toe om het oude gedrag te herstellen:

[.programlisting]
....
Option "AutoAddDevices" "false"
....

Invoerapparaten kunnen dan zoals in vorige versies worden geconfigureerd, tezamen met eventuele andere benodigde opties (bijvoorbeeld omschakelen van toetsenbordindeling).

[NOTE]
====
Zoals al eerder is uitgelegd zal de daemon hald standaard automatisch uw toetsenbord detecteren. Het kan zijn dat de indeling of het model van uw toetsenbord niet juist zijn. Bureaubladomgevingen zoals GNOME, KDE of Xfce bieden gereedschappen om het toetsenbord in te stellen. Het is echter mogelijk om de eigenschappen direct in te stellen met behulp van het gereedschap man:setxkbmap[1] of met een configuratieregel van hald.

Als men bijvoorbeeld een PC-toetsenbord met 102 toetsen met een Franse indeling wilt gebruiken, dienen we een instellingenbestand voor het toestenbord voor hald aan te maken genaamd [.filename]#x11-input.fdi# en het op te slaan in de map [.filename]#/usr/local/etc/hal/fdi/policy#. Het dient de volgende regels te bevatten:

[.programlisting]
....
<?xml version="1.0" encoding="utf-8"?>
<deviceinfo version="0.2">
  <device>
    <match key="info.capabilities" contains="input.keyboard">
      <merge key="input.x11_options.XkbModel" type="string">pc102</merge>
      <merge key="input.x11_options.XkbLayout" type="string">fr</merge>
    </match>
  </device>
<deviceinfo>
....

Als dit bestand al bestaat, kunt u de regels betreffende de configuratie van het toetsenbord kopiëren en aan uw bestand toevoegen.

U dient uw machine opnieuw op te starten om hald te forceren om dit bestand te lezen.

Het is mogelijk om hetzelfde te bereiken vanaf een X-terminal of een script met dit commando:

[source,bash]
....
% setxkbmap -model pc102 -layout fr
....

Het bestand [.filename]#/usr/local/shared/X11/xkb/rules/base.lst# noemt de beschikbare toetsenborden, indelingen en opties.
====

Het bestand [.filename]#xorg.conf.new# kan nu naar wens worden aangepast. Open het bestand in een tesktverwerker zoals man:emacs[1] of man:ee[1]. Indien de monitor een ouder of ongebruikelijk model is dat geen automatische detectie van de synchronisatiefrequenties ondersteunt, dan kunnen deze instellingen worden toegevoegd aan [.filename]#xorg.conf.new# in de sectie `"Monitor"`:

[.programlisting]
....
Section "Monitor"
        Identifier   "Monitor0"
        VendorName   "Monitor Vendor"
        ModelName    "Monitor Model"
        HorizSync    30-107
        VertRefresh  48-120
EndSection
....

De meeste monitoren ondersteunen de automatische detectie van de synchronisatiefrequentie, wat het handmatig invoeren van deze waardes overbodig maakt. Voor de enkele monitoren die geen automatische detectie ondersteunen, dienen om mogelijke schade te voorkomen alleen waardes die door de fabrikant zijn opgegeven te worden ingevoerd.

X kan DPMS (Energy Star) eigenschappen gebruiken bij monitoren die dit ondersteunen. man:xset[1] regelt de timeouts en kan de statussen standby, suspend of uit forceren. Om DPMS eigenschappen voor een monitor te activeren, moet de volgende regel toegevoegd worden aan de monitor sectie:

[.programlisting]
....
Option       "DPMS"
....

Als het instellingenbestand [.filename]#xorg.conf.new# toch open staat in de editor dan kan ook meteen de gewenste standaardresolutie en kleurdiepte gekozen worden. Dit staat in het onderdeel `"Screen"`:

[.programlisting]
....
Section "Screen"
        Identifier "Screen0"
        Device     "Card0"
        Monitor    "Monitor0"
        DefaultDepth 24
        SubSection "Display"
                Viewport  0 0
                Depth     24
                Modes     "1024x768"
        EndSubSection
EndSection
....

Het sleutelwoord `DefaultDepth` beschrijft de kleurdiepte die standaard wordt gebruikt. Met de commandoregeloptie `-depth` van man:Xorg[1] kan dit overschreven worden. Het sleutelwoord `Modes` beschrijft de resolutie waarmee gewerkt wordt bij de opgegeven kleurdiepte. Alleen VESA standaarden die door de grafische kaart van het systeem worden gedefinieerd worden ondersteund. In het voorbeeld hierboven is de standaard kleurdiepte 24 bits per pixel. Bij deze kleurdiepte is de toegestane resolutie 1024 bij 768 pixels.

[NOTE]
====
Bij het oplossen van problemen zijn de logboekbestanden van X11 vaak een goede hulp. Ze bevatten informatie voor ieder apparaat waar de X11 server verbinding mee maakt. Namen van Xorg logboekbestanden hebben de vorm [.filename]#/var/log/Xorg.0.log#. De precieze naam van een logboekbestand van variëren van [.filename]#Xorg.0.log# tot [.filename]#Xorg.8.log# enzovoort.
====

Als alles is ingesteld, moet het instellingenbestand op een plaats gezet worden waar man:Xorg[1] het kan vinden. Dit is meestal [.filename]#/etc/X11/xorg.conf# of [.filename]#/usr/local/etc/X11/xorg.conf#:

[source,bash]
....
# cp xorg.conf.new /etc/X11/xorg.conf
....

Het instellen van X11 is nu gereed. Xorg gestart worden met man:startx[1]. De X11-server kan ook gestart worden met behulp van man:xdm[1].

=== Bijzondere instellingen

==== Instellen met de Intel(R) `i810` grafische chipset

Instellen met Intel(R) i810 geïntegreerde chipsets vereist de [.filename]#agpgart# AGP programmeerinterface voor X11 om de kaart aan te sturen. Zie de man:agp[4] handleiding voor meer informatie.

Hierdoor wordt het instellen van de hardware net als ieder andere grafische kaart. Bij systemen die zonder man:agp[4] stuurprogramma gecompileerd zijn slaagt het laden van module met man:kldload[8] niet. Het stuurprogramma moet in de kernel geladen zijn tijdens het opstarten door te compileren of door [.filename]#/boot/loader.conf# te gebruiken.

==== Een Breedbeeld Flatpanel toevoegen

Deze sectie gaat uit van wat diepere configuratiekennis. Als pogingen om de bovenstaande standaard instelgereedschappen niet tot een werkende configuratie leidden, dan is er genoeg informatie in de logbestanden om de opstelling aan de praat te krijgen. Het gebruik van een tekstverwerker zal nodig zijn.

Huidige breedbeeldformaten (zoals WSXGA, WSXGA+, WUXGA, WXGA en WXGA+) ondersteunen 16:10 en 10:9 formaten of aspectverhoudingen die problematisch kunnen zijn. Voorbeelden van enkele veelvoorkomende schermresoluties voor 16:10 aspectverhoudingen zijn:

* 2560x1600
* 1920x1200
* 1680x1050
* 1440x900
* 1280x800

Op een gegeven moment zal het toevoegen van een van deze resoluties net zo eenvoudig zijn als een mogelijke `Mode` in het `Section "Screen"`:

[.programlisting]
....
Section "Screen"
Identifier "Screen 0"
Device     "Card0"
Monitor    "Monitor0"
DefaultDepth 24
SubSection "Display"
	Viewport 0 0
	Depth    24
	Modes    "1680x1050"
EndSubSection
EndSection
....

Xorg is slim genoeg om de resolutie-informatie via I2C/DDC-informtie uit het flatpanel te onttrekken zodat het weet wat de monitor aan kan wat betreft frequenties en resoluties.

Als die `ModeLines` niet bestaan in de stuurprogramma's, dient men Xorg een kleine hint te geven. Met behulp van [.filename]#/var/log/Xorg.0.log# kan men genoeg informatie onttrekken om handmatig een werkende `ModeLine` aan te maken. Kijk naar informatie die op deze lijkt:

[.programlisting]
....
(II) MGA(0): Supported additional Video Mode:
(II) MGA(0): clock: 146.2 MHz   Image Size:  433 x 271 mm
(II) MGA(0): h_active: 1680  h_sync: 1784  h_sync_end 1960 h_blank_end 2240 h_border: 0
(II) MGA(0): v_active: 1050  v_sync: 1053  v_sync_end 1059 v_blanking: 1089 v_border: 0
(II) MGA(0): Ranges: V min: 48  V max: 85 Hz, H min: 30  H max: 94 kHz, PixClock max 170 MHz
....

Deze informatie wordt EDID-informatie genoemd. Hiervan een `ModeLine` maken is gewoon een kwestie van de nummers in de juiste volgorde zetten:

[.programlisting]
....
ModeLine <name> <clock> <4 horiz. timings> <4 vert. timings>
....

Dus de `ModeLine` in `Section "Monitor"` zou er voor dit voorbeeld uitzien als:

[.programlisting]
....
Section "Monitor"
Identifier       "Monitor1"
VendorName       "GroteNaam"
ModelName        "BesteModel"
ModeLine         "1680x1050" 146.2 1680 1784 1960 2240 1050 1053 1059 1089
Option           "DPMS"
EndSection
....

Na het voltooien van deze eenvoudige stappen, zou X moeten starten op uw nieuwe breedbeeldmonitor.

[[x-fonts]]
== Lettertypen gebruiken in X11

[[type1]]
=== Type1 lettertypen

De standaard lettertypen van X11 zijn allerminst ideaal voor het typische bureaubladprogramma. Grote presentatielettertypen zien er hoekig en onprofessioneel uit en kleine lettertypen zijn bijna onleesbaar. Er zijn diverse gratis, kwalitatief goede Type1 (PostScript(R)) lettertypen die meteen gebruikt kunnen worden met X11. De URW lettertypecollectie (package:x11-fonts/urwfonts[]) heeft bijvoorbeeld hoge kwaliteit versies van standaard Type1 lettertypen (Times Roman(TM), Helvetica(TM), Palatino(TM) en anderen). De Freefonts collectie (package:x11-fonts/freefonts[]) heeft nog meer lettertypen, maar de meesten ervan zijn bedoeld om in grafische software als Gimp gebruikt te worden en zijn niet compleet genoeg om als schermlettertypen te gebruiken. Daarbij kan X11 zonder veel moeite ingesteld worden om TrueType(R) lettertypen te gebruiken. Meer informatie staat in man:X[7] of de paragraaf over <<truetype,TrueType(R) Lettertypen>>.

Om de bovenstaande Type1 lettertypecollectie van de Portscollectie te installeren:

[source,bash]
....
# cd /usr/ports/x11-fonts/urwfonts
# make install clean
....

Dat geldt ook voor de freefont en andere collecties. Om de X server te vertellen dat deze lettertypen bestaan, dient de volgende regel toegevoegd te worden aan het instellingenbestand van de X server ([.filename]#/etc/X11/xorg.conf#):

[.programlisting]
....
FontPath "/usr/local/lib/X11/fonts/URW/"
....

Ook kan op de commando regel in de X sessie het volgende gestart worden:

[source,bash]
....
% xset fp+ /usr/local/lib/X11/fonts/URW
% xset fp rehash
....

Dit werkt wel, maar zodra de X sessie wordt afgesloten is het weer verdwenen tenzij het is toegevoegd aan het opstartbestand ([.filename]#~/.xinitrc# voor een normale `startx` sessie of [.filename]#~/.xsession# als er wordt aangemeld met een grafische aanmeldmanager als XDM). Een derde manier is het gebruik van het nieuwe bestand [.filename]#/usr/local/etc/fonts/local.conf#: zie hiervoor de paragraaf over <<antialias,Anti-aliasing>>.

[[truetype]]
=== TrueType(R) lettertypen

Xorg heeft ingebouwde ondersteuning voor het renderen van TrueType(R) lettertypen. Er zijn twee verschillende modules die deze functionaliteit activeren. In dit voorbeeld wordt de freetype module gebruikt omdat deze beter werkt met de andere lettertypen die back-ends renderen. Om de freetype module te activeren dient de volgende regel toegevoegd te worden aan het onderdeel `"Module"` van [.filename]#/etc/X11/xorg.conf#.

[.programlisting]
....
Load  "freetype"
....

Hierna dient een map voor de TrueType(R) lettertypen gemaakt te worden (bijvoorbeeld [.filename]#/usr/local/lib/X11/fonts/TrueType#) en alle TrueType(R) lettertypen moeten naar deze map gekopieerd worden. TrueType(R) lettertypen kunnen niet direct van een Macintosh(R) gehaald worden. Ze moeten in een UNIX(R)/MS-DOS(R)/Windows(R) formaat zijn voor X11. Zodra de bestanden naar deze map zijn gekopieerd, kan ttmkfdir gestart worden om een [.filename]#fonts.dir# bestand te maken zodat de X lettertyperenderer weet waar deze nieuwe bestanden zijn geïnstalleerd. `ttmkfdir` zit in de FreeBSD Portscollectie als package:x11-fonts/ttmkfdir[].

[source,bash]
....
# cd /usr/local/lib/X11/fonts/TrueType
# ttmkfdir -o fonts.dir
....

Nu moet de TrueType(R) map toe aan het lettertypepad toegevoegd worden. Dit gebeurt op dezelfde wijze als boven is beschreven voor <<type1,Type1>> lettertypen:

[source,bash]
....
% xset fp+ /usr/local/lib/X11/fonts/TrueType
% xset fp rehash
....

of door een `FontPath` regel toe te voegen aan [.filename]#xorg.conf#.

Dat is alles. Nu herkennen Gimp, Apache OpenOffice en alle andere X applicaties de geïnstalleerde TrueType(R) lettertypen. Extreem kleine lettertypen (zoals hoge resolutie tekst op een webpagina) en extreme grote lettertypen (in StarOffice(TM)) zien er nu veel beter uit.

[[antialias]]
=== Antialias lettertypen

Alle lettertypen die X11 in de mappen [.filename]#/usr/local/lib/X11/fonts/# en [.filename]#~/.fonts/# staan zijn automatisch beschikbaar voor anti-aliasing in applicaties die Xft ondersteunen. De meeste recente applicaties ondersteunen Xft, inclusief KDE, GNOME, en Firefox.

Om te kunnen regelen welke lettertypen gebruik maken van anti-alias of om de eigenschappen van anti-aliasing in te stellen kan [.filename]#/usr/local/etc/fonts/local.conf# gemaakt of gewijzigd worden. In dit bestand kunnen speciale eigenschappen van het Xft lettertypesysteem aangepast worden. Deze paragraaf beschrijft wat eenvoudige mogelijkheden. Meer details staan in man:fonts-conf[5].

Dit bestand moet in het XML formaat opgemaakt worden. Hoofdletters en kleine letters worden onderscheiden en alle tags moeten netjes worden afgesloten. Het bestand begint met de gewone XML header gevolgd door een DOCTYPE definitie en daarna de `<fontconfig>` tag:

[.programlisting]
....
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
....

Zoals al eerder is vermeld zijn alle lettertypen in [.filename]#/usr/local/lib/X11/fonts/# en in [.filename]#~/.fonts/# al geschikt gemaakt voor Xft applicaties. Als naast deze twee mappen nog een andere lettertypen moeten kunnen bevatten, dan dient een soortgelijke regel als de onderstaande aan [.filename]#/usr/local/etc/fonts/local.conf# toegevoegd te worden:

[.programlisting]
....
<dir>/pad/naar/mijn/fonts</dir>
....

Na het toevoegen van nieuwe lettertypen en zeker nieuwe lettertypemappen dienen de lettertypecaches opnieuw opgebouwd worden met:

[source,bash]
....
# fc-cache -f
....

Anti-aliasing maakt randen een beetje wazig wat kleine teksten beter leesbaar maakt en voorkomt "trapvorming" van grote letters. Maar het kan oogkramp veroorzaken als het op normale tekst wordt toegepast. Om lettertypen kleiner dan 14 punten uit te sluiten van anti-aliasing moeten de volgende regels toegevoegd worden:

[.programlisting]
....
<match target="font">
    <test name="size" compare="less">
        <double>14</double>
    </test>
    <edit name="antialias" mode="assign">
        <bool>false</bool>
    </edit>
</match>
<match target="font">
    <test name="pixelsize" compare="less" qual="any">
        <double>14</double>
    </test>
    <edit mode="assign" name="antialias">
        <bool>false</bool>
    </edit>
</match>
....

Spatiëring voor sommige enkel gespatieerde lettertypen kan ook ongepast zijn bij anti-aliasing. Dit lijkt vooral een probleem te zijn bij KDE. Een mogelijke oplossing hiervoor is het vergroten van de spatiëring van die lettertypen naar 100:

[.programlisting]
....
<match target="pattern" name="family">
   <test qual="any" name="family">
       <string>fixed</string>
   </test>
   <edit name="family" mode="assign">
       <string>mono</string>
   </edit>
</match>
<match target="pattern" name="family">
    <test qual="any" name="family">
        <string>console</string>
    </test>
    <edit name="family" mode="assign">
        <string>mono</string>
    </edit>
</match>
....

Het bovenstaande hernoemt de standaardnamen van lettertypen naar `"mono"`). Voeg daarna het volgende toe:

[.programlisting]
....
<match target="pattern" name="family">
    <test qual="any" name="family">
        <string>mono</string>
    </test>
    <edit name="spacing" mode="assign">
        <int>100</int>
    </edit>
</match>
....

Bepaalde lettertypen, zoals Helvetica, kunnen problemen hebben met anti-aliasing. Dit uit zich meestal in een lettertype dat verticaal door midden lijkt gesneden. Op zijn ergst kan het applicaties laten crashen. Om dit te voorkomen kan overwogen worden om ook de volgende regels toe te voegen aan [.filename]#local.conf#:

[.programlisting]
....
<match target="pattern" name="family">
    <test qual="any" name="family">
        <string>Helvetica</string>
    </test>
    <edit name="family" mode="assign">
        <string>sans-serif</string>
    </edit>
</match>
....

Als de wijzigingen in [.filename]#local.conf# zijn gemaakt dient niet vergeten te worden het bestand te eindigen met de tag `</fontconfig>` tag. Als dit niet gedaan wordt, dan worden de wijzigingen niet gezien.

Als laatste kunnen gebruikers hun eigen instellingen aan een persoonlijk [.filename]#.fonts.conf# bestand toevoegen. Om dit te doen moet iedere gebruiker het bestand [.filename]#~/.fonts.conf# maken. Ook dit bestand moet in het XML formaat zijn.

Nog een laatste punt: bij een LCD scherm kan sub-pixel sampling prettig zijn. Eigenlijk zorgt dit er voor dat de (horizontaal gesplitste) rode, groene en blauwe componenten gewijzigd worden om de horizontale resolutie te verbeteren. Het resultaat is geweldig. Voeg hiervoor de volgende regels ergens aan [.filename]#local.conf# toe:

[.programlisting]
....
<match target="font">
    <test qual="all" name="rgba">
        <const>unknown</const>
    </test>
    <edit name="rgba" mode="assign">
        <const>rgb</const>
    </edit>
</match>
....

[NOTE]
====
Afhankelijk van het soort beeldscherm kan `rgb` veranderd moeten worden in `bgr`, `vrgb` of `vbgr`. Experimenteren levert de beste instelling op.
====

[[x-xdm]]
== De X beeldschermmanager

=== Overzicht

De X beeldschermmanager (XDM) is een optioneel onderdeel van het X Window systeem dat gebruikt wordt voor beheer van aanmeldsessies. Dit is vaak erg handig bij bijvoorbeeld "X Terminals", desktops en grote netwerk beeldschermservers. Omdat het X Window systeem netwerk- en protocolonafhankelijk is, zijn er veel mogelijkheden om X clients en servers op verschillende machines in een netwerk te verbinden. XDM levert een grafische interface waarmee er gekozen kan worden welke beeldschermserver gebruikt moet worden en handelt autorisatie informatie (gebruikersnaam en wachtwoord) af.

XDM levert de gebruiker dezelfde functionaliteit levert als man:getty[8] (zie crossref:serialcomms[term-config,Instellen]). Dus het regelt de systeemaanmeldingen voor de schermen waaraan verbonden moet worden en start dan een sessie manager namens de gebruiker (meestal een X window manager). XDM wacht dan tot het programma stopt en geeft aan dat de gebruiker klaar is en afgemeld kan worden. Hierna kan XDM het aanmeldscherm weer tonen zodat de volgende gebruiker kan aanmelden.

=== XDM gebruiken

Om XDM te gebruiken moet de port package:x11/xdm[] geïnstalleerd worden (het wordt in recente versies van Xorg niet standaard geïnstalleerd). Het daemon-programma XDM is daarna beschikbaar in [.filename]#/usr/local/bin/xdm#. Dit programma kan als `root` altijd gestart worden en regelt dan het X weergavegedeelte van de lokale machine. Als XDM iedere keer bij het opstarten moet starten is het handig om een regel toe te voegen aan [.filename]#/etc/ttys#. Meer informatie over het gebruik van dit bestand staat in crossref:serialcomms[term-etcttys,Een regel aan /etc/ttys toevoegen]. In de standaardversie van [.filename]#/etc/ttys# staat een regel om de applicatie daemon XDM op een virtuele terminal te draaien:

[source,bash]
....
ttyv8   "/usr/local/bin/xdm -nodaemon"  xterm   off secure
....

Standaard staat deze regel uit. Om hem aan te zetten moet veld 5 van `off` naar `on` gewijzigd worden en moet met man:init[8] herstart worden met gebruikmaking van de aanwijzingen in crossref:serialcomms[term-hup,init forceren om /etc/ttys opnieuw te lezen]. Het eerste veld, de naam van de terminal die het programma aanstuurt, is `ttyv8`. Dit houdt in dat XDM op de negende virtuele terminal begint te draaien.

=== XDM instellen

De map met instellingen voor XDM is [.filename]#/usr/local/lib/X11/xdm#. In deze map staan diverse bestanden die gebruikt kunnen worden om het gedrag en uiterlijk van XDM te veranderen. Meestal zijn dit de volgende bestanden:

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Bestand
| Omschrijving

|[.filename]#Xaccess#
|Regels voor client authorisatie.

|[.filename]#Xresources#
|Standaard waarden voor X bronnen.

|[.filename]#Xservers#
|Lijst met op afstand en lokaal te beheren schermen.

|[.filename]#Xsession#
|Standaard sessie script voor logins.

|[.filename]#Xsetup_#*
|Script die applicaties start voordat de login interface start.

|[.filename]#xdm-config#
|Algehele instellingen voor alle schermen op deze machine.

|[.filename]#xdm-errors#
|Fouten die gegenereerd zijn door het serverprogramma.

|[.filename]#xdm-pid#
|Het proces ID van de draaiende XDM.
|===

Tevens staan in deze map een aantal scripts en programma's om het bureaublad in te stellen als XDM draait. Het doel van elk van deze bestanden wordt kort omschreven. De juiste syntaxis en het gebruik van deze bestanden staat in man:xdm[1].

De standaardinstelling regelt een eenvoudig rechthoekig aanmeldvenster met bovenin de hostnaam van de machine in een groot lettertype met een "Login:" en "Password:" prompt eronder. Dit is een goed beginpunt om het uiterlijk en werking van het XDM venster te veranderen.

==== Xaccess

Om een verbinding te maken met XDM-gestuurde schermen wordt het protocol X Display Manager Connection Protocol (XDMCP) gebruikt. Het bestand is een set regels die XDMCP verbindingen met andere machines bestuurt. Het wordt genegeerd, tenzij [.filename]#xdm-config# is gewijzigd zodat er wordt geluisterd naar inkomende verbindingen. Standaard wordt het clients niet toegestaan te verbinden.

==== Xresources

Dit is een bestand met standaarden voor de schermkiezer en de aanmeldschermen. Hier kan het uiterlijk van het aanmeldprogramma gewijzigd worden. De indeling is hetzelfde als bij het app-defaults bestand en is beschreven in de X11 documentatie.

==== Xservers

Dit is een lijst met netwerkschermen waaruit gekozen kan worden.

==== Xsession

Dit is het standaard sessiescript voor XDM dat start nadat de gebruiker is aangemeld. Normaal heeft iedere gebruiker een eigen sessiescript in [.filename]#~/.xsession# dat dit script overheerst.

==== Xsetup_*

Deze starten automatisch voordat de kiezers of aanmeldschermen getoond worden. Er is een script voor ieder gebruikt scherm met de naam [.filename]#Xsetup_# gevolgd door het lokale schermnummer (bijvoorbeeld [.filename]#Xsetup_0#). Normaal draaien deze scripts éé of twee programma's in de achtergrond zoals `xconsole`.

==== xdm-config

Dit bevat de instellingen die toegepast worden op ieder scherm die deze installatie aanstuurt. De indeling is hetzelfde als van app-defaults.

==== xdm-errors

Hierin staan de meldingen die de X servers geven als XDM ze probeert te starten. Als een scherm dat gestart is door XDM om onduidelijke reden hangt, is dit een goede plaats om te zoeken naar foutmeldingen. Deze meldingen worden ook per sessie naar het [.filename]#~/.xsession-errors# van de gebruiker gestuurd.

=== Een netwerk beeldschermserver gebruiken

Om gebruikers een verbinding te laten maken met een X server moeten de toegangsregels gewijzigd worden en de connectielistener moet aangezet worden. Deze hebben standaard wat terughoudende waarden. Om XDM te laten luisteren naar verbindingen moet als eerste een regel uitgecommentarieerd worden in [.filename]#xdm-config#:

[source,bash]
....
! SECURITY: do not listen for XDMCP or Chooser requests
! Comment out this line if you want to manage X terminals with XDM
DisplayManager.requestPort:     0
....

Hierna moet XDM herstart worden. Afwijkend in dit bestand is dat commentaar in app-defaults bestanden begint met het karakter "!" en niet met het karakter "#". Het kan wenselijk zijn om de toegangscontrole aan te scherpen - hiervoor staan voorbeeldregels in [.filename]##Xaccess## en lees de hulppagina man:xdm[1] voor meer informatie.

=== Alternatieven voor XDM

Er bestaan diverse alternatieven voor het XDM programma. KDM (wordt geleverd bij KDE) wordt later in dit hoofdstuk behandeld. De beeldschermmanager KDM biedt vele grafische verbeteringen en cosmetische franje en de mogelijkheid om de gebruiker de kans te geven een window manager te laten kiezen bij het aanmelden.

[[x11-wm]]
== Bureaubladomgevingen

Deze sectie beschrijft de verschillende bureaubladomgevingen voor X op FreeBSD. Een "bureaubladomgeving" kan van alles inhouden: van een simpele window manager tot een complete suite van bureaubladapplicaties zoals KDE of GNOME.

[[x11-wm-gnome]]
=== GNOME

[[x11-wm-gnome-about]]
==== Over GNOME

GNOME is een gebruikersvriendelijke bureaubladomgeving die de gebruiker de mogelijkheid geeft om gemakkelijk de computer te gebruiken en in te stellen. GNOME heeft een paneel (voor het starten en tonen van statusinformatie van applicaties), een bureaublad (waar data en applicaties geplaatst kunnen worden), een set standaard bureaubladapplicaties en een regels die het makkelijker maakt voor applicaties om eenduidig met elkaar samen te werken. Gebruikers van andere besturingssystemen of omgevingen voelen zich meestal meteen thuis bij het gebruik van de krachtige grafisch gestuurde omgeving die GNOME biedt. Meer informatie over GNOME op FreeBSD staat op de http://www.FreeBSD.org/gnome[FreeBSD GNOME Project] website. De website bevat ook redelijk complete FAQ's over het installeren, instellen en beheren van GNOME.

[[x11-wm-gnome-install]]
==== GNOME installeren

De software kan eenvoudig worden geïnstalleerd vanuit een pakket of de Portscollectie:

Om het GNOME pakket te installeren:

[source,bash]
....
# pkg_add -r gnome2
....

Om GNOME vanuit de Portscollectie te installeren:

[source,bash]
....
# cd /usr/ports/x11/gnome2
# make install clean
....

Voor een correcte werking, vereist GNOME dat het [.filename]#/proc# bestandssysteem gekoppeld is. Voeg

[.programlisting]
....
proc           /proc       procfs  rw  0   0
....

toe aan [.filename]#/etc/fstab# om man:procfs[5] automatisch te koppelen tijdens het opstarten.

Zodra GNOME geïnstalleerd is, moet de X server verteld worden dat in plaats van de standaard window manager GNOME gebruikt moet worden.

De meest eenvoudige manier om GNOME te starten is via GDM, de GNOME Display Manager. GDM wordt meegeïnstalleerd met de GNOME bureaubladomgeving, maar staat standaard uitgeschakeld. Dit programma kan ingeschakeld worden door het volgende toe te voegen aan [.filename]#/etc/rc.conf#:

[.programlisting]
....
gdm_enable="YES"
....

Na een herstart zal GDM automatisch gestart worden.

Meestal is het gewenst om alle GNOME applicaties tegelijkertijd met GDM te starten. Om dit te bereiken moet de volgende regel worden toegevoegd aan [.filename]#/etc/rc.conf#:

[.programlisting]
....
gnome_enable="YES"
....

GNOME kan ook gestart worden vanaf de commandoregel door het bestand [.filename]#.xinitrc# juist in te stellen. Als er al een [.filename]#.xinitrc# is, dan hoeft alleen de regel die de huidige window manager start veranderd te worden in een regel die /usr/local/bin/gnome-session start. Als er niets speciaals met dit instellingenbestand is gedaan:

[source,bash]
....
% echo "/usr/local/bin/gnome-session" > ~/.xinitrc
....

Nu kan met `startx` de GNOME bureaubladomgeving gestart worden.

[NOTE]
====
Als een beeldschermmanager als XDM gebruikt wordt werkt het bovenstaande niet. In plaats daarvan moet een uitvoerbaar [.filename]#.xsession# gemaakt worden met hetzelfde commando erin. Hiervoor moet het bestand aangepast worden door het bestaande window manager commando te vervangen door /usr/local/bin/gnome-session:
====

[source,bash]
....
% echo "#!/bin/sh" > ~/.xsession
% echo "/usr/local/bin/gnome-session" >> ~/.xsession
% chmod +x ~/.xsession
....

Het is ook mogelijk de beeldschermmanager zo in te stellen dat de window manager gekozen kan worden tijdens het aanmelden. In de paragraaf <<x11-wm-kde-details,Meer KDE Details>> wordt uitgelegd hoe dit gedaan moet worden voor de KDM beeldschermmanager van KDE.

[[x11-wm-kde]]
=== KDE

[[x11-wm-kde-about]]
==== Over KDE

KDE is een bureaubladomgeving die eigentijds is en makkelijk in gebruik. KDE biedt de gebruiker:

* Een schitterende eigentijdse desktop;
* Een desktop die volledig netwerktransparant is;
* Een geïntegreerd hulpsysteem dat eenvoudig bruikbare informatie geeft over het gebruik van het KDE bureaublad en de applicaties;
* Alle KDE applicaties werken op dezelfde manier en zien er hetzelfde uit;
* Gestandaardiseerde menu's en werkbalken, keybindings, kleurschema's, enzovoort;
* Internationalisatie: KDE is beschikbaar in meer dan 55 talen;
* Gecentraliseerde, consistente, dialooggedreven bureaubladinstelling;
* Een grote hoeveelheid bruikbare KDE applicaties;

KDE wordt geleverd met een webbrowser genaamd Konqueror die niet onder doet voor de andere bestaande webbrowsers op UNIX(R) systemen. Meer informatie over KDE staat op de http://www.kde.org/[KDE website]. Voor FreeBSD specifieke informatie en bronnen over KDE is er de website http://freebsd.kde.org/[KDE/FreeBSD initiatief].

Er zijn twee versies van KDE beschikbaar op FreeBSD. Versie 3 is sinds lange tijd aanwezig en is nog steeds beschikbaar in de Portscollectie alhoewel het nu onbeheerd en gedeeltelijk kapot is. Versie 4 wordt punctueel bijgewerkt en is de standaardkeuze voor gebruikers van KDE. Ze kunnen zelfs naast elkaar worden geïnstalleerd.

[[x11-wm-kde-install]]
==== KDE installeren

Net als bij GNOME of iedere andere bureaubladomgeving kan de software eenvoudig geïnstalleerd met een pakket of uit de Portscollectie:

Om het KDE 3 pakket van het netwerk te installeren:

[source,bash]
....
# pkg_add -r kde
....

Om het KDE 4 pakket van het netwerk te installeren:

[source,bash]
....
# pkg_add -r kde4
....

man:pkg_add[1] haalt automatisch de laatste versie van de applicatie op.

Om KDE 3 vanuit de Portscollectie te bouwen en te installeren:

[source,bash]
....
# cd /usr/ports/x11/kde3
# make install clean
....

Gebruik de Portscollectie om KDE 4 vanuit de broncode te bouwen:

[source,bash]
....
# cd /usr/ports/x11/kde4
# make install clean
....

Nadat KDE geïnstalleerd is, moet de X server verteld worden dat déze applicatie gestart moet worden in plaats van de standaard window manager. Hiervoor kan [.filename]#.xinitrc# aangepast worden:

Voor KDE 3:

[source,bash]
....
% echo "exec startkde" > ~/.xinitrc
....

Voor KDE 4:

[source,bash]
....
% echo "exec /usr/local/kde4/bin/startkde" > ~/.xinitrc
....

Als het X Window System wordt gestart met `startx` is KDE het bureaublad.

Als er een beeldschermmanager als XDM gebruikt wordt, is de instelling anders. Dan moet [.filename]#.xsession# gewijzigd worden. Instructies voor KDM worden later in dit hoofdstuk beschreven.

[[x11-wm-kde-details]]
=== Meer KDE details

Nadat KDE geïnstalleerd is op een systeem, kunnen de meeste dingen uitgezocht worden via de hulppagina's of door de verschillende menu's aan te wijzen en erop te klikken. Windows(R) en Mac(R) gebruikers voelen zich meestal helemaal thuis.

Het beste naslagwerk voor KDE is de on-line documentatie. KDE heeft zijn eigen web browser, Konqueror, tientallen handige applicaties en uitgebreide documentatie. De volgende paragrafen beschrijven de technische zaken die moeilijk proefondervindelijk te achterhalen zijn.

[[x11-wm-kde-kdm]]
==== De KDE beeldschermmanager

Een beheerder van een multi-user systeem die een grafisch aanmeldscherm willen hebben voor zijn gebruikers kan hiervoor <<x-xdm,XDM>> gebruiken, zoals eerder beschreven. KDE biedt KDM als alternatief. Dat is ontworpen met een beter uiterlijk en heeft meer aanmeldopties. Gebruikers kunnen via een menu kiezen welke bureaubladomgeving (KDE, GNOME of een andere) zij na het aanmelden willen gebruiken.

Om KDM te starten, moeten verschillende bestanden gewijzigd worden, afhankelijk van de versie van KDE.

Voor KDE 3 dient de regel met `ttyv8` als volgt aangepast te worden:

[.programlisting]
....
ttyv8 "/usr/local/bin/kdm -nodaemon" xterm on secure
....

Voor KDE 4 dient man:procfs[5] te worden aangekoppeld en de volgende regel aan [.filename]#/etc/rc.conf# te worden toegevoegd:

[.programlisting]
....
kdm4_enable="YES"
....

[[x11-wm-xfce]]
=== Xfce

[[x11-wm-xfce-about]]
==== Over Xfce

Xfce is een bureaubladomgeving die gebaseerd is op de GTK+ toolkit die gebruikt wordt bij GNOME, maar is eenvoudiger en bedoeld voor gebruikers die een simpel en efficiënt bureaublad willen dat toch eenvoudig en makkelijk in te stellen is. Het ziet er bijna hetzelfde uit als CDE dat bij commerciële UNIX(R) systemen zit. Een aantal Xfce functies zijn:

* Een eenvoudige, makkelijk te bedienen desktop;
* Geheel in te stellen met de muis, met klikken en slepen, enzovoort;
* Hoofdpaneel hetzelfde als CDE met menu's, applets en applicaties
* Geïntegreerde window manager, bestandsmanager, geluidsmanager, GNOME compliance module en meer zaken;
* Thema's (sinds het gebruik van GTK+);
* Snel, licht en efficiënt: ideaal voor de oudere of langzamere machines of machines met beperkte hoeveelheid geheugen;

Meer informatie over Xfce staat op de http://www.xfce.org/[Xfce website].

[[x11-wm-xfce-install]]
==== Installeren van Xfce

Xfce is met een pakket te installeren:

[source,bash]
....
# pkg_add -r xfce4
....

Of vanuit de Portscollectie:

[source,bash]
....
# cd /usr/ports/x11-wm/xfce4
# make install clean
....

Nu moet de X server weten dat Xfce gestart moet worden als X de volgende keer start:

[source,bash]
....
% echo "/usr/local/bin/startxfce4" > ~/.xinitrc
....

De volgende keer dat X start is Xfce het bureaublad. Wederom: als een beeldschermmanager als XDM gebruikt wordt, moet [.filename]#.xsession# gemaakt worden zoals beschreven in de paragraaf over <<x11-wm-gnome,GNOME>>. Nu moet echter het command [.filename]#/usr/local/bin/startxfce4# gebruikt. Het is ook mogelijk de beeldschermmanager in te stellen om bureaublad te kiezen bij het aanmelden, zoals is uitgelegd in de paragraaf over <<x11-wm-kde-kdm,kdm>>.
