# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

# DOCS=	announce.sgml hardware.sgml notes.sgml
DOCS= announce.sgml

DATA=	docbook.css
# DATA+=	errata.html
# DATA+=	hardware-alpha.html
# DATA+=	hardware-i386.html
# DATA+=	relnotes-alpha.html
# DATA+=	relnotes-i386.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
