# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.7
#
# $FreeBSD$

SUBDIR+= books

COMPAT_SYMLINK = pt_BR
COMPAT_SYMLINK += br

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
