# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.7
#
# $FreeBSD$

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = pt_BR

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
