# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=	Section

DATA=	MIMEIterator.pm Section.pm

.include "${WEB_PREFIX}/share/mk/web.site.mk"
