# $FreeBSD: www/zh_CN/releases/Makefile.inc,v 1.1.1002.1 2005/12/18 08:20:00 delphij Exp $
# The FreeBSD Simplified Chinese Documentation Project
# Original Revision 1.5

WEBBASE?=	/data/zh_CN/releases
WEB_PREFIX?=	${.CURDIR}/../../..
