---
title: "Source code repositories"
sidenav: developers
---

= Source code repositories

== Git

https://git-scm.com/[Git] is the tool the FreeBSD Project uses for keeping its sources under control. Every change (with an accompanying log message explaining its purpose) is stored. It can be easily viewed from the web interface mentioned below.

In December 2020, development of the base system migrated from Subversion to Git. The https://cgit.FreeBSD.org/src/[web interface] is available for browsing the repository.

In December 2020, the FreeBSD Documentation Project moved from Subversion to Git. There is a https://cgit.FreeBSD.org/doc/[web interface] available for browsing the contents of the FreeBSD Documentation Project Git repository.

The FreeBSD Ports tree is planned to move from Subversion to Git at the end of March 2021. There is a https://cgit-dev.FreeBSD.org/ports/[web interface] for browsing the beta repository.

== Subversion

https://subversion.apache.org/[Subversion] (SVN for short) is the legacy tool the FreeBSD Project used for keeping its sources under control. Every change (with an accompanying log message explaining its purpose) is stored. It can be easily viewed from the web interface mentioned below.

In June 2008, development of the base system migrated from CVS to Subversion. Since December 2020, after development moved to Git, Subversion only receives translated commits from git2svn exporter in stable/11, stable/12 and supported release branches. The https://svnweb.FreeBSD.org/base/[web interface] is available for browsing the repository.

In May 2012, the FreeBSD Documentation Project moved from CVS to Subversion. The doc subversion repository does not receive any further updates after the development moved from Subversion to Git Since December 2020. There is a https://svnweb.FreeBSD.org/doc/[web interface] available for browsing the contents of the FreeBSD Documentation Project SVN repository.

In July 2012, the FreeBSD Ports tree moved from CVS to Subversion. There is a https://svnweb.FreeBSD.org/ports/[web interface] for browsing the repository.
