---
title: "关于 FreeBSD 的应用"
sidenav: about
--- 

= 关于 FreeBSD 的应用

== 感受 FreeBSD 的无穷潜能

FreeBSD 几乎能够处理您希望任何一台 UNIX(R) 工作站所能完成的任务， 而且还包括您可能没有想过的：

== FreeBSD 是一个提供了完整的源代码的真正的开放系统。

没有人会怀疑开放系统 _是_ 现代计算应用的前提条件。 然而， 有哪一个商业发行机构提供的解决方案， 能够比提供了包括内核， 以及全部系统服务、 程序和管理工具的源代码的操作系统更为开放呢？ 您可以修改 FreeBSD 的任何部分， 来适应您个人， 所在的组织， 以及公司的需要。

由于采用了宽松的 link:../copyright/freebsd-license/[授权策略]， 您可以几乎不受任何限制地将 FreeBSD 作为运行任意免费 _或商业_ 应用的基础。

== FreeBSD 能够运行上万种的应用软件。

由于 FreeBSD 基于业界 UNIX 标准之一的 4.4BSD， 在其上编译和运行程序易如反掌。 此外， FreeBSD 还提供了包含丰富应用程序的 link:../where/[packages collection] 以及 https://www.FreeBSD.org/ports/[ports collection]， 用以向用户提供预编译的， 以及便于自行构建的各类软件， 以期满足从桌面到企业服务器的种种需求。 此外， 为 FreeBSD 编写的 https://www.FreeBSD.org/commercial/software/[商业应用] 也在与日俱增。

以下是一些典型的 FreeBSD 应用环境：

* *Internet 服务。* 许多 Internet 服务提供商 (ISP) 把 FreeBSD 视为运行 WWW、 Usenet news、 FTP、 Email， 以及其他服务的理想平台。 众多可以立即投入使用的软件， 例如 http://www.apache.org/[Apache] web 服务器， 以及 http://proftpd.org/[ProFTPD] FTP 服务器， 使得构建商业或社区中心的 ISP 变得易如反掌。 当然， 配合 FreeBSD 无与伦比的 link:../internet/[网络子系统]， 您的用户将享受到高速的、 可靠的服务。
* *X Window 工作站。* 从便宜的 X 终端到高档的 X 显示器， FreeBSD 都能游刃有余。 免费的 X 软件 (http://x.org/[X.Org](TM)) 随系统提供。 另外， http://www.nvidia.com/[nVidia] 也提供了用于他们的高性能图形硬件的 native 驱动程序， 并加入了业界标准的 http://www.opengroup.org/motif/[Motif](R) 和 http://www.opengl.org/[OpenGL](R) 函数库支持。 对于 http://www.kde.org[KDE] 和 http://www.gnome.org[GNOME] 桌面环境， 都提供了全面支持， 并提供了办公套件的功能， 以及功能更为强大的 http://www.openoffice.org/[OpenOffice.Org] 和 http://www.softmaker.de/tml_en.htm[TextMaker] 产品。
* *网络。* 无论是包过滤、路由，还是域名服务， FreeBSD 都能够让任何一台 PC 成为 Internet 防火墙、 电子邮件主机， 打印服务器， PC/NFS 服务器， 甚至提供各式各样的其他服务。
* *软件开发。* FreeBSD 提供了一整套开发工具， 这其中包括了 GNU C/C++ 编译器和调试器。 举例而言， 您还可以使用 JJava(R) 或 Tcl/Tk， 以及一些更深奥的开发语言如 Icon 来进行开发。 此外， FreeBSD 还提供了易于构建和使用的各种共享库。 您可以从众多流行的强大的文本编辑器， 例如 XEmacs 和 Vim 中选择自己喜欢来使用。
* *网络冲浪。* 真正的 UNIX 工作站， 是绝佳的 Internet 冲浪板。 FreeBSD 版本的 http://www.mozilla.org/products/firefox/[Firefox] 和 http://www.opera.com/[Opera]， 都为严肃的 web 用户提供了非常优秀的选择。 网上冲浪， 发表自己的 web 页面， 阅读 Usenet news、 收发电子邮件， 都可以通过您桌面上的 FreeBSD 系统来轻松实现。
* *教育和研究。* 由于提供了完整的源代码， FreeBSD 是一个非常优秀的研究平台。 操作系统或其他计算机科学领域的学生和研究人员， 都能够从这一开放而且充分文档华的系统中受益。
* *更多。* 金融， 动作游戏， MIS 数据库， 可视化科研， 视频会议， 由 Internet 中转的聊天 (IRC)， 家庭自动化， 多用户主机， 电子公告板系统， 图像扫描， 以及更多的其他应用， 都已经在 FreeBSD 上开花结果。

== FreeBSD 是随您需要而成长的操作系统。

尽管 FreeBSD 是自由软件， 它同时也是一个 _由用户支持的_ 软件。 您只需简单地将问题通过电子邮件的方式发到 freebsd-questions@FreeBSD.org 邮件列表， 就可以向数百名开发人员和众多的 FreeBSD 用户提问。

FreeBSD 还有一个包括世界各地的开发人员团队， 他们在不断地修正系统中的问题， 增加新特性以及撰写文档。 支持新的设备和功能一直是开发过程的重要部分， 而开发团队在这一过程中一直非常重视可能会影响到系统稳定性的问题。 FreeBSD 的用户群体因其系统的高性能和高稳定性而感到自豪。

== 专家们说 . . .

_“FreeBSD 应对 [我们的] 高负荷应用总是游刃有余， 而且经常能够给人惊喜。 向 FreeBSD 开发团队致敬！”_

---Mark Hittinger, WinNet Communications, Inc. 管理员
