# $FreeBSD: www/en/releases/4.5R/Makefile,v 1.1 2002/01/12 13:29:27 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	hardware.sgml notes.sgml qa.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
