# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.9

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   current.sgml 
DOCS+=	doc-set.sgml
DOCS+=  handbook.sgml
## DOCS+=  sgml.sgml
## DOCS+=  submitting.sgml
## DOCS+=  who.sgml 
## DOCS+=  translations.sgml
DOCS+=	docproj.sgml

INDEXLINK= docproj.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
