# $FreeBSD: www/ja/smp/Makefile,v 1.1 2000/12/30 14:25:15 hrs Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml

### Revision checking
REVCHECK=YES

.include "${WEB_PREFIX}/share/mk/web.site.mk"
