---
title: Συχνές Ερωτήσεις Σχετικά με τις Λίστες Ηλεκτρονικού Ταχυδρομείου του FreeBSD
authors:
  - author: Η Ομάδα Τεκμηρίωσης του FreeBSD
releaseinfo: "$FreeBSD$" 
---

= Συχνές Ερωτήσεις Σχετικά με τις Λίστες Ηλεκτρονικού Ταχυδρομείου του FreeBSD
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:toc-title: Πίνακας Περιεχομένων
:table-caption: Πίνακας
:figure-caption: Σχήμα
:example-caption: Παράδειγμα

include::shared/authors.adoc[]
include::shared/el/mailing-lists.adoc[lines=10..-1]
include::shared/el/urls.adoc[]

[.abstract-title]
Περίληψη

Το άρθρο αυτό αποτελεί τις συχνές ερωτήσεις για τις λίστες ταχυδρομείου του FreeBSD. Αν ενδιαφέρεστε να βοηθήσετε σε αυτό το έργο, στείλτε ένα email στην {freebsd-doc}. Η τελευταία έκδοση αυτού του εγγράφου είναι πάντοτε διαθέσιμη στην link:{mailing-list-faq}[Δικτυακή τοποθεσία του FreeBSD]. Μπορείτε επίσης να το κατεβάσετε ως ένα μεγάλο αρχείο link:.[HTML] ή και ως απλό κείμενο, PostScript, PDF, κ.λ.π. από τον link:ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/[Διακομιστή FTP του FreeBSD]. Μπορεί επίσης να θέλετε να link:https://www.FreeBSD.org/search/[ψάξετε σε αυτό το άρθρο].

'''

toc::[]

[[introduction]]
== Εισαγωγή

Όπως συνηθίζεται στα κείμενα των Συχνών Ερωτήσεων (FAQ), το κείμενο αυτό περιέχει τις πιο συχνές ερωτήσεις που σχετίζονται με τις λίστες ταχυδρομείου του FreeBSD (και φυσικά τις απαντάει!). Αν και ο αρχικός σκοπός των FAQ ήταν να μειώσουν το εύρος ζώνης που απαιτείται από την συνεχόμενη απάντηση των ίδιων και ίδιων ερωτήσεων, τα FAQ τελικά καθιερώθηκαν ως μια πολύ χρήσιμη αυτόνομη πηγή πληροφοριών.

Το κείμενο αυτό προσπαθεί να αντιπροσωπεύσει την κοινά αποδεκτή γνώμη της κοινότητας και ως τέτοιο, δεν μπορεί σε καμιά περίπτωση να θεωρηθεί ότι είναι απόλυτα __έγκυρο__. Αν ωστόσο βρείτε τεχνικά λάθη ή έχετε να προτείνετε θέματα που πρέπει να προστεθούν, παρακαλούμε στείλτε μας μια αναφορά προβλήματος (PR) ή ένα email στην {freebsd-doc}. Ευχαριστούμε!

=== Ποιος είναι ο σκοπός των λιστών ταχυδρομείου του FreeBSD;

Οι λίστες ταχυδρομείου του FreeBSD αποτελούν το βασικό κανάλι επικοινωνίας για την κοινότητα του FreeBSD. Καλύπτουν πολλές διαφορετικές περιοχές θεμάτων και ενδιαφερόντων.

=== Ποιο είναι το κοινό για τις λίστες ταχυδρομείου του FreeBSD;

Αυτό εξαρτάται από τον κανονισμό της κάθε λίστας. Μερικές λίστες είναι περισσότερο προσανατολισμένες στους προγραμματιστές. Άλλες προσανατολίζονται περισσότερο στην κοινότητα του FreeBSD ως σύνολο. Παρακαλούμε δείτε http://lists.FreeBSD.org/mailman/listinfo[αυτή τη λίστα] για την τρέχουσα περίληψη.

=== Είναι όλες οι λίστες του FreeBSD ανοιχτές για συμμετοχή από τον καθένα;

Και πάλι, αυτό εξαρτάται από τον κανονισμό της κάθε λίστας. Σας παρακαλούμε να διαβάσετε τον κανονισμό της λίστας που σας ενδιαφέρει πριν αρχίσετε να δημοσιεύετε σε αυτήν και να τον σέβεστε σε κάθε δημοσίευση σας. Αυτό βοηθάει όλους τους συμμετέχοντες να έχουν την καλύτερη δυνατή εμπειρία από τις λίστες μας.

Αν διαβάζοντας τους κανονισμούς για τις παραπάνω λίστες, δεν μπορείτε ακόμα να αποφασίσετε σε ποια λίστα να στείλετε την ερώτηση σας, μάλλον θα πρέπει να την στείλετε στην {freebsd-questions} (αλλά δείτε πρώτα παρακάτω).

Σημειώστε επίσης ότι κατά παράδοση οι λίστες είναι ανοιχτές και σε άτομα που δεν έχουν εγγραφεί σε αυτές. Αυτή η επιλογή είναι εσκεμμένη, με σκοπό να βοηθήσει τους νέους χρήστες να εισέλθουν πιο εύκολα στην κοινότητα του FreeBSD, και να ενισχύσει την ανοιχτή ανταλλαγή ιδεών. Ωστόσο, λόγω κακής χρήσης από συγκεκριμένα άτομα, κάποιες λίστες έχουν τώρα τον περιορισμό ότι κάθε μήνυμα από μη-μέλος θα πρέπει να ελέγχεται χειροκίνητα για να εξασφαλιστεί ότι είναι κατάλληλο.

=== Πως μπορώ να εγγραφώ;

Μπορείτε να χρησιμοποιήσετε την http://lists.FreeBSD.org/mailman/listinfo[διεπαφή Web του Mailman] για να γραφείτε σε οποιαδήποτε από τις δημόσιες λίστες.

=== Πως μπορώ να διαγραφώ;

Με τον ίδιο τρόπο που εγγραφήκατε. Ή μπορείτε επίσης να ακολουθήσετε τις οδηγίες που βρίσκονται στο τέλος κάθε μηνύματος που στέλνει η λίστα.

Σας παρακαλούμε μη στέλνετε μηνύματα διαγραφής απευθείας σε δημόσιες λίστες. Πρώτα από όλα, αυτό δεν θα επιτύχει το σκοπό σας, και δεύτερον θα εκνευρίσει τους υπάρχοντες συνδρομητές οι οποίοι θα λογομαχήσουν εναντίον σας. Πρόκειται για κλασικό λάθος κατά τη χρήση λιστών ταχυδρομείου και σας παρακαλούμε να προσπαθήσετε να το αποφύγετε.

=== Είναι διαθέσιμα τα αρχεία των λιστών;

Ναι. Μπορείτε να τα βρείτε http://docs.FreeBSD.org/mail/[εδώ], ταξινομημένα κατά θέμα.

=== Είναι διαθέσιμες οι λίστες σε μορφή περίληψης;

Ναι. Δείτε http://lists.FreeBSD.org/mailman/listinfo[τη διεπαφή web του Mailman].

[[etiquette]]
== Συμπεριφορά (Etiquette) στις Λίστες

Η συμμετοχή στις λίστες ηλεκτρονικού ταχυδρομείου, όπως και η συμμετοχή σε οποιαδήποτε κοινότητα, απαιτεί μια κοινή βάση επικοινωνίας. Σας παρακαλούμε να κάνετε μόνο κατάλληλες δημοσιεύσεις, και να ακολουθείτε τους κοινούς κανόνες συμπεριφοράς.

=== Τι πρέπει να κάνω πριν από μια δημοσίευση;

Διαβάζοντας αυτό το κείμενο, έχετε ήδη κάνει το πιο σημαντικό βήμα. Ωστόσο, αν είστε νέος στο FreeBSD, θα πρέπει πρώτα να εξοικειωθείτε με το λογισμικό και όλη την κοινωνική ιστορία που το περιβάλλει, διαβάζοντας τα διάφορα link:https://www.FreeBSD.org/docs/books/[άρθρα και βιβλία] τα οποία είναι διαθέσιμα. Ιδιαίτερο ενδιαφέρον έχουν link:{faq}[Οι Συχνές Ερωτήσεις (FAQ) του FreeBSD], το link:{handbook}[Εγχειρίδιο του FreeBSD] καθώς και τα άρθρα link:{freebsd-questions-article}[Πως να χρησιμοποιείτε με επιτυχία τη λίστα ηλεκτρονικού ταχυδρομείου FreeBSD-questions], link:{explaining-bsd}[Περιγραφή των Συστημάτων BSD], και link:{new-users}[Για Χρήστες Νέους τόσο στο FreeBSD όσο και στο UNIX(R)].

Θεωρείται γενικά κακή συμπεριφορά να ρωτήσετε μια ερώτηση η οποία μπορεί να απαντηθεί από κάποιο από τα παραπάνω κείμενα. Αυτό δεν συμβαίνει επειδή οι εθελοντές που δουλεύουν σε αυτό το έργο είναι κακοί άνθρωποι, αλλά επειδή όταν έχουν απαντήσει την ίδια ερώτηση πολλές φορές, αρχίζει να τους ενοχλεί. Αυτό συμβαίνει ειδικά αν υπάρχει διαθέσιμη η απάντηση της ερώτησης. Να θυμάστε πάντα ότι σχεδόν όλη η δουλειά στο FreeBSD γίνεται από εθελοντές και τελικά είμαστε απλώς άνθρωποι.

=== Τι δημοσίευση μπορεί να θεωρηθεί ακατάλληλη;

* Η δημοσίευση πρέπει να είναι σύμφωνη με τους κανονισμούς της λίστας.
* Οι προσωπικές επιθέσεις είναι γενικά ανεπιθύμητες. Σαν καλοί διαδικτυακοί πολίτες, θα πρέπει να προσπαθούμε να κρατάμε υψηλά επίπεδα συμπεριφοράς.
* Το spam δεν επιτρέπεται ποτέ. Γίνεται επεξεργασία στις λίστες για να απαγορευτούν οι δημοσιεύσεις σε όσους παραβαίνουν αυτό τον κανόνα.

=== Ποια θεωρείται σωστή συμπεριφορά στην αποστολή μηνυμάτων στις λίστες;

* Παρακαλούμε να κάνετε αναδίπλωση των γραμμών κάθε 75 χαρακτήρες. Δεν χρησιμοποιούν όλοι GUI προγράμματα για να διαβάζουν το mail τους.
* Παρακαλούμε σεβαστείτε το γεγονός ότι το εύρος ζώνης δεν είναι απεριόριστο. Δεν διαβάζει καθένας το email του μέσω συνδέσεων υψηλής ταχύτητας, έτσι αν το μήνυμα σας περιέχει κάτι σαν το περιεχόμενο του αρχείου [.filename]#config.log# ή ένα εκτεταμένο stack trace, σας παρακαλούμε να ανεβάσετε αυτές τις πληροφορίες σε κάποια δικτυακή τοποθεσία και να στείλετε ένα σύνδεσμο προς αυτές. Να θυμάστε επίσης ότι γίνεται αρχειοθέτηση αυτών των μηνυμάτων, έτσι αν στείλετε ένα τεράστιο μήνυμα θα μεγαλώσετε και το μέγεθος των αρχείων, ακόμα και όταν αυτές οι πληροφορίες δεν θα είναι πια χρήσιμες.
* Μορφοποιήστε το μήνυμα σας ώστε να είναι ευανάγνωστο και σας παρακαλούμε ΜΗ ΦΩΝΑΖΕΤΕ!!!. Μην υποτιμάτε το αποτέλεσμα που θα έχει ένα φτωχά μορφοποιημένο μήνυμα, και αυτό δεν συμβαίνει μόνο στις λίστες του FreeBSD. Το μήνυμα σας είναι το μόνο που σας γνωστοποιεί στους υπόλοιπους ανθρώπους, και αν είναι άσχημα μορφοποιημένο, γεμάτο θαυμαστικά, θα αφήσει στους άλλους άσχημη εντύπωση για εσάς.
* Χρησιμοποιήστε την κατάλληλη γλώσσα για τη λίστα ταχυδρομείου που πρόκειται να στείλετε μήνυμα. Μπορείτε να δείτε link:https://www.FreeBSD.org/community/mailinglists/[εδώ] τις λίστες που υπάρχουν σε γλώσσες εκτός της Αγγλικής.
+ 
Όσο αφορά τις Αγγλικές λίστες, αντιλαμβανόμαστε ότι για πολλούς η Αγγλική δεν είναι η μητρική τους γλώσσα και δείχνουμε κατανόηση. Θεωρείται κακή συμπεριφορά να κατακρίνετε όσους δεν έχουν τα Αγγλικά ως μητρική γλώσσα για λάθη γραμματικής ή ορθογραφίας. Το FreeBSD έχει μια πολύ καλή παράδοση σε αυτό το θέμα, σας παρακαλούμε να μας βοηθήσετε να τη διατηρήσουμε.
* Παρακαλούμε χρησιμοποιήστε ένα πρόγραμμα αποστολής ταχυδρομείου (MUA) που να ακολουθεί σωστά τα πρότυπα. Πολλά από τα άσχημα μορφοποιημένα μηνύματα προέρχονται από http://www.lemis.com/email.html[κακής ποιότητας ή κακορυθμισμένα προγράμματα ταχυδρομείου]. Τα παρακάτω προγράμματα είναι γνωστό ότι στέλνουν προβληματικά μηνύματα, χωρίς εσείς να το γνωρίζετε:

** cc:Mail
** Eudora(R) (παλιότερες εκδόσεις)
** exmh
** Microsoft(R) Exchange
** Microsoft(R) Internet Mail
** Microsoft(R) Outlook(R)
** Netscape(R) (παλιότερες εκδόσεις)

+ 
Όπως μπορείτε να δείτε, πολλά από τα προβληματικά προγράμματα προέρχονται από τον κόσμο της Microsoft. Αν είναι δυνατόν χρησιμοποιήστε ένα πρόγραμμα που να προέρχεται από το UNIX(R). Αν πρέπει να χρησιμοποιήσετε ένα πρόγραμμα σε περιβάλλον Microsoft, φροντίστε να είναι ρυθμισμένο σωστά. Προσπαθήστε να μην χρησιμοποιήσετε MIME: αρκετός κόσμος χρησιμοποιεί προγράμματα ταχυδρομείου που δεν τα πάνε πολύ καλά με το MIME.
* Βεβαιωθείτε ότι η ώρα και η ζώνη ώρας στον υπολογιστή σας είναι σωστά ρυθμισμένα. Αυτό μπορεί να φαίνεται κάπως ανόητο, ειδικά καθώς το μήνυμα σας θα φτάσει έτσι και αλλιώς, αλλά αρκετοί άνθρωποι σε αυτές τις λίστες λαμβάνουν εκατοντάδες μηνύματα κάθε μέρα. Συχνά τα ταξινομούν κατά θέμα και ημερομηνία, έτσι αν το μήνυμα σας έρθει μετά την πρώτη απάντηση θα θεωρήσουν ότι το έχασαν και δεν θα ασχοληθούν να το ψάξουν.
* Πολλές φορές οι πληροφορίες που πρέπει να παρέχετε περιέχουν την έξοδο προγραμμάτων όπως το man:dmesg[8], ή τα μηνύματα που εμφανίζονται στην κονσόλα, τα οποία συνήθως γράφονται στο [.filename]#/var/log/messages#. Μην προσπαθήσετε να αντιγράψετε αυτές τις πληροφορίες πληκτρολογώντας τις ξανά: όχι μόνο είναι βασανιστικό, αλλά είναι σχεδόν σίγουρο ότι θα κάνετε κάποιο λάθος. Για να στείλετε τα περιεχόμενα κάποιου αρχείου καταγραφής, είτε αντιγράψτε το αρχείο και χρησιμοποιήστε κάποιο συντάκτη κειμένου για να κόψετε τα κομμάτια που σας ενδιαφέρουν, ή κάντε αποκοπή και επικόλληση μέσα στο μήνυμα σας. Για την έξοδο προγραμμάτων όπως το `dmesg`, χρησιμοποιήστε ανακατεύθυνση της εξόδου σε ένα αρχείο και στείλτε αυτό. Για παράδειγμα:
+
[source,bash]
....
% dmesg > /tmp/dmesg.out
....
+ 
Το παραπάνω θα ανακατευθύνει τις πληροφορίες στο αρχείο [.filename]#/tmp/dmesg.out#.
* Όταν χρησιμοποιείτε αποκοπή και επικόλληση να έχετε υπόψη σας ότι αυτές οι λειτουργίες μπορεί να καταστρέψουν το νόημα των μηνυμάτων. Αυτό συμβαίνει ιδιαίτερα όταν στέλνετε αρχεία όπως τα [.filename]#Makefiles#, όπου το `tab` είναι σημαντικός χαρακτήρας. Πρόκειται για πολύ κοινό και ενοχλητικό πρόβλημα ειδικά σε μηνύματα που απευθύνονται στη link:https://www.FreeBSD.org/support/gnats[Βάση Δεδομένων Προβλημάτων GNATS]. Τα [.filename]#Makefiles# όπου τα tabs έχουν αλλάξει είτε σε κενά ή στον ενοχλητικό χαρακτήρα `=3B` δημιουργούν πολλά ενοχλητικά προβλήματα στους committers.

=== Τι πρέπει να έχω υπόψη μου όσο αφορά τη συμπεριφορά στη λίστα όταν απαντάω σε κάποιο υπάρχον μήνυμα;

* Παρακαλούμε να συμπεριλάβετε το σχετικό κείμενο από το αρχικό κείμενο. Περιορίστε το στο ελάχιστο, αλλά μη το παρακάνετε. Θα πρέπει κάποιος που δεν έχει δει το αρχικό μήνυμα να μπορεί να καταλάβει σε τι αναφέρεται η συζήτηση.
+ 
Αυτό είναι ιδιαίτερα σημαντικό σε μηνύματα του τύπου "Ναι και σε μένα συμβαίνει το ίδιο", όπου το αρχικό μήνυμα μπορεί να ήταν αρκετές δεκάδες ή εκατοντάδες γραμμές.
* Χρησιμοποιήστε κάποια τεχνική με την οποία να γίνεται δυνατή η αναγνώριση του κειμένου που ανήκει στο αρχικό μήνυμα και του κειμένου που προσθέσατε. Μια συνηθισμένη σύμβαση είναι να χρησιμοποιείται το "`> `" μπροστά από το αρχικό μήνυμα. Είναι επίσης καλή ιδέα να αφήνετε κενό διάστημα μετά το "`> `" και κενές γραμμές ανάμεσα στο δικό σας και το αρχικό, ώστε το τελικό αποτέλεσμα να είναι πιο ευανάγνωστο.
* Να βεβαιώνεστε πάντα ότι οι αναφορές στον αρχικό συγγραφέα του μηνύματος είναι σωστές. Συχνά οι άνθρωποι προσβάλλονται αν τους εμφανίζετε να έχουν γράψει λέξεις ενώ αυτό δεν συμβαίνει.
* Παρακαλούμε μην κάνετε `top post`. Αυτό σημαίνει να μην ξεκινάτε την απάντηση σας πάνω από το κείμενο του μηνύματος στο οποίο απαντάτε.
+
** Απ: Γιατί αντιστρέφει τη λογική ροή της συζήτησης.
** Ερ: Γιατί θεωρείται κακό το top posting;
+ 
(Ευχαριστούμε το Randy Bush για το ανέκδοτο.)

[[recurring]]
== Επαναλαμβανόμενα Θέματα στις Λίστες Ταχυδρομείου

Η συμμετοχή στις λίστες ταχυδρομείου, όπως και η συμμετοχή σε κάθε κοινότητα, απαιτεί μια κοινή βάση επικοινωνίας. Πολλές από τις λίστες ταχυδρομείου προϋποθέτουν γνώση της ιστορίας του Project. Ειδικότερα, φαίνεται ότι κάποια θέματα προκύπτουν ξανά και ξανά στα νεώτερα μέλη της κοινότητας. Είναι ευθύνη του καθένα που συμμετέχει να φροντίζει ώστε τα μηνύματα του να μην εμπίπτουν σε κάποια από αυτές τις κατηγορίες. Με τον τρόπο αυτό, βοηθάτε τις λίστες ταχυδρομείου να μην ξεφεύγουν από το θέμα τους, και πιθανόν προφυλάσσετε και τον εαυτό σας από τυχόν λεκτικές επιθέσεις (flames).

Η καλύτερη μέθοδος για να αποφύγετε το παραπάνω πρόβλημα είναι να εξοικειωθείτε με τα http://docs.FreeBSD.org/mail/[αρχεία των λιστών] για να μπορέσετε να καταλάβετε το ιστορικό της συζήτησης. Ιδιαίτερα χρήσιμη για αυτό το σκοπό θα σας φανεί και η link:https://www.FreeBSD.org/search/#mailinglists[λειτουργία αναζήτησης της λίστας]. (Αν η μέθοδος αυτή δεν φέρει το επιθυμητό αποτέλεσμα, συμπληρώστε την με μια αναζήτηση μέσω της μηχανής αναζήτησης που προτιμάτε).

Όταν θα έχετε εξοικειωθεί με τα αρχεία της λίστας, όχι μόνο θα γνωρίζετε ποια θέματα έχουν συζητηθεί παλιότερα, αλλά και με ποιο τρόπο εξελίσσονται συνήθως οι συζητήσεις σε αυτή τη λίστα, ποιοι είναι οι συμμετέχοντες και σε ποιο κοινό απευθύνεται. Είναι πάντοτε καλό να γνωρίζετε εκ των προτέρων τα παραπάνω πριν στείλετε μήνυμα σε οποιαδήποτε λίστα (όχι μόνο του FreeBSD).

Δεν υπάρχει αμφιβολία ότι τα αρχεία έχουν μεγάλη έκταση και μερικές ερωτήσεις φαίνονται να επαναλαμβάνονται πιο συχνά από άλλες, μερικές φορές σαν απαντήσεις όπου το θέμα που αναγράφεται στο μήνυμα δεν αντιπροσωπεύει πλέον το νέο περιεχόμενο. Ωστόσο πέφτει σε σας το βάρος να κάνετε όλη την εργασία που χρειάζεται ώστε να αποφύγετε αυτά τα επαναλαμβανόμενα θέματα.

[[bikeshed]]
== Τι είναι το "Bikeshed";

Κυριολεκτικά το `bikeshed` είναι ένα μικρό εξωτερικό καταφύγιο όπου κάποιος μπορεί να φυλάξει το δίτροχο του (υπόστεγο ποδηλάτων). Στην ορολογία του FreeBSD ωστόσο, η λέξη αυτή χρησιμοποιείται για να αναφερόμαστε σε θέματα συζήτησης που είναι τόσο απλά ώστε (σχεδόν) καθένας να μπορεί να εκφέρει μια γνώμη για αυτά - και πολύ συχνά συμβαίνει ακριβώς αυτό. Η γέννηση αυτού του όρου εξηγείται με περισσότερη λεπτομέρεια σε link:{faq}#BIKESHED-PAINTING[αυτό το κείμενο]. Θα πρέπει να κατανοείτε την έννοια αυτού του όρου πριν αρχίσετε να στέλνετε μηνύματα σε οποιαδήποτε λίστα του FreeBSD.

Πιο γενικά, το bikeshed είναι ένα θέμα το οποίο τείνει να δημιουργεί περισσότερες παράπλευρες συζητήσεις και λεκτικούς διαξιφισμούς, αν δεν έχετε διαβάσει σχετικά με την προϊστορία του.

Σας παρακαλούμε να μας βοηθήσετε να κρατήσουμε τις λίστες ταχυδρομείου όσο το δυνατόν πιο χρήσιμες γίνεται για τον περισσότερο κόσμο, προσπαθώντας να αποφύγετε τα bikesheds όποτε είναι δυνατόν. Ευχαριστούμε!

[[acknowledgments]]
== Ευχαριστίες

`{grog}`::
Ο αρχικός συγγραφέας του περισσότερου υλικού που αφορά τους κανονισμούς των λιστών, που προέρχονται από το άρθρο link:{freebsd-questions-article}[Πως να χρησιμοποιείτε με επιτυχία την λίστα ηλεκτρονικού ταχυδρομείου FreeBSD-questions].

`{linimon}`::
Δημιουργία του πρόχειρου αντίγραφου αυτού του FAQ.
