#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
#

CHAPTERS=	jails/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?=	${.CURDIR}/../../../..

.include "../Makefile"
