# $FreeBSD$

.if exists(../../Makefile.conf)
.include "../../Makefile.conf"
.endif
.if exists(../../Makefile.inc)
.include "../../Makefile.inc"
.endif

DATA+=	adamw.jpg
DATA+=	ahze.jpg
DATA+=	kwm.jpg
DATA+=	marcus.jpg
DATA+=	mezz.jpg
DATA+=	pav.jpg
DATA+=	hippobutt.jpg

WEBBASE=		/data/gnome/images
WEB_PREFIX=		${.CURDIR}/../../../..
.include "${WEB_PREFIX}/share/mk/web.site.mk"
