#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
# Original revision: r32971
#

CHAPTERS= 	filesystems/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
