#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/books/handbook/advanced-networking/Makefile
# %SRCID%	1.2
#

CHAPTERS= 	advanced-networking/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
