---
title: "FreeBSD Project - Administration und Management"
sidenav: about
---

include::shared/authors.adoc[]

= FreeBSD Project - Administration und Management

== Einführung

Diese Seite enthält eine Auflistung von Teams, Gruppen und Einzelpersonen innerhalb des FreeBSD Projects und beschreibt deren Rolle und Verantwortungsbereiche innerhalb des Projekts. Außerdem finden Sie hier Tätigkeitsbeschreibungen sowie Kontaktinformationen. Um Missverständnissen vorzubeugen, wurden die Bezeichnungen der Teams und Gruppen *nicht* übersetzt.

* Projektmanagement
** <<t-core, Core Team>>
** <<t-doceng, Documentation Engineering Team>>
** <<t-portmgr, Port Management Team>>
** <<t-ports-secteam, Ports Security Team>>
* Release Engineering
** <<t-re, Primary Release Engineering Team>>
** <<t-re-builder, Builders Release Engineering Team>>
* Teams
** <<t-donations, Donations Team>>
** <<t-secteam, Security Team>>
** <<t-vendor, Vendor Relations>>
* Sekretäre
** <<t-core-secretary, Core Team Secretary>>
** <<t-doceng-secretary, Documentation Engineering Team Secretary>>
** <<t-portmgr-secretary, Port Management Team Secretary>>
* Interne Verwaltung
** <<t-accounts, Accounts Team>>
** <<t-backups, Backup Administrators>>
** <<t-bugmeister, Bugmeisters>>
** <<t-clusteradm, Cluster Administrators>>
** <<t-dnsadm, DNS Administrators>>
** <<t-forum-admins, Forum Administrators>>
** <<t-github-automation, GitHub Repository Mirror>>
** <<t-jenkins-admin, Jenkins Continuous Integration Testing Administrators>>
** <<t-mirror-admin, FTP/WWW Mirror Site Coordinators>>
** <<t-phabric-admin, Phabricator Code Review Administration>>
** <<t-postmaster, Postmaster Team>>
** <<t-subversion, Subversion Administrators>>
** <<t-webmaster, Webmaster Team>>
** <<t-wiki, Wiki Admin Team>>

'''

[[t-core]]
=== FreeBSD Core Team <core@FreeBSD.org>

Das FreeBSD Core Team bildet den "Vorstand" des Projekts. Es legt fest, in welche Richtung sich das FreeBSD Project entwickelt und verwaltet zusätzlich verschiedene Bereiche des Projekts. Das Core Team wird von den aktiven FreeBSD-Entwicklern gewählt.

* {bapt} (Clusteradm Liaison)
* {emaste} (GIT Transition WG and Security Team Liason)
* {gnn} (Foundation Liaison)
* {hrs} (Code-of-Conduct Committee Liaison)
* {kevans} (Portmgr Team Liaison)
* {markj} (Bugmeister and CI Team Liaison)
* {scottl} (Release Engineering Team Liaison)
* {seanc} (Doceng Team Liaison)
* {imp} (GIT Transition WG Liaison)

[[t-doceng]]
=== FreeBSD Documentation Engineering Team <doceng@FreeBSD.org>

Das FreeBSD Documentation Engineering Team legt die Vorgaben für die Committer des Documentation Projects fest und kontrolliert auch deren Einhaltung. Die link:../../en/internal/doceng/[Doceng Team Charter] beschreibt die Aufgaben und Verantwortungsbereiche dieses Teams ausführlich.

* {gjb}
* {wblock}
* {blackend}
* {gabor}
* {bcr}
* {hrs}
* {ryusuke}
* {0mp} (Secretary)

[[t-portmgr]]
=== FreeBSD Port Management Team <portmgr@FreeBSD.org>

Hauptaufgabe des FreeBSD Port Management Teams ist es, dafür zu sorgen, dass die FreeBSD-Port-Entwickler eine funktionierende, stabile, aktuelle und umfangreiche Ports-Sammlung bereitstellen. Dazu koordiniert das Team die Arbeit der Entwickler, die an der Ports-Sammlung arbeiten. Die link:../../en/portmgr/charter/Portmgr Team Charter] beschreibt die Aufgaben und Verantwortungsbereiche dieses Teams ausführlich.

* {adamw}
* {antoine}
* {bapt} (Core Team Liaison)
* {bdrewery} (Release Engineering Team Liaison)
* {mat} (Cluster Administration Team Liaison)
* {rene} (Secretary)
* {swills}

'''

[[t-ports-secteam]]
=== FreeBSD Ports Security Team <ports-secteam@FreeBSD.org>

Die Hauptaufgabe des FreeBSD Port Security Teams ist die rasche Reaktion auf Sicherheitsprobleme, die in der FreeBSD Ports-Sammlung auftreten. Sie informieren die Anwender über Bugs, Sicherheitslücken, bekannte Angriffe und andere Risiken. Lesen Sie bitte die entsprechende https://wiki.freebsd.org/ports-secteam[Wiki]-Seite für weitere Informationen.

* {fluffy}
* {joneum}

'''

[[t-re]]
=== Primary Release Engineering Team <re@FreeBSD.org>

Das Primary Release Engineering Team erstellt und veröffentlicht die Zeitpläne für die Bereitstellung der offiziellen FreeBSD-Releases, verfügt "Code Freezes" und wartet die verschiedenen `releng/*`-Zweige. Die link:https://www.FreeBSD.org/releng/charter/[Release Engineering Team Charter] beschreibt die Aufgaben und Verantwortungsbereiche dieses Teams ausführlich.

* {gjb} (Lead)
* {kib}
* {bdrewery}
* {blackend}
* {delphij}
* {cperciva} (Deputy Lead)
* {hrs}
* {glebius}

[[t-re-builder]]
=== Builders Release Engineering Team <re-builder@FreeBSD.org>

Das FreeBSD Builders Release Engineering Team ist für den Bau von FreeBSD-Releases auf allen unterstützten Plattformen verantwortlich.

* {marcel}
* {nyan}
* {nwhitehorn}

'''

[[t-donations]]
=== Donations Tea <donations@FreeBSD.org>

Das FreeBSD Donations Team kümmert sich um Spendenangebote, legt fest, wie mit Spenden umgegangen wird und koordiniert die angebotenen Spenden mit den FreeBSD-Entwicklern. Eine ausführliche Beschreibung der Aufgaben des Donations Teams finden Sie auf der Seite link:../../en/donations/[FreeBSD Donations Liaison].

* {gahr}
* {bhughes}
* {adridg}

[[t-secteam]]
=== Security Team <secteam@FreeBSD.org>

Das FreeBSD Security Team (das vom Security Officer geleitet wird) ist dafür verantwortlich, die FreeBSD-Gemeinde über neu entdeckte Bugs und Sicherheitslücken im src- und ports-Quellcodebaum zu informieren und Informationen für den sicheren Betrieb eines FreeBSD-Systems zur Verfügung zu stellen. Außerdem sorgt es dafür, dass neu entdeckte Sicherheitslücken geschlossen werden und die Anwender durch Sicherheitshinweise informiert werden. Die link:https://www.FreeBSD.org/security/charter/[FreeBSD Security Officer Charter] beschreibt die Aufgaben und Verantwortungsbereiche des Security Officers ausführlich.

* {gordon} (Officer)
* {delphij} (Officer Emeritus, Release Engineering Team Liaison)
* {des} (Officer Emeritus)
* {gjb} (Cluster Administrators Team Liaison)
* {emaste} (Officer Deputy)
* {brooks} (Core Team Liaison)
* {bz}
* {gnn}
* {markj}
* {philip}

[[t-vendor]]
=== Vendor Relations <vendor-relations@FreeBSD.org>

FreeBSD Vendor Relations ist für die Bearbeitung der E-Mails von Hard- und Softwareverkäufern verantwortlich. An Vendor Relations geschickte E-Mails werden zusätzlich an das FreeBSD Core Team sowie die FreeBSD Foundation weitergeleitet.

'''

[[t-core-secretary]]
=== Core Team Secretary <core-secretary@FreeBSD.org>

Der FreeBSD Core Team Secretary ist ein nicht-stimmberechtigtes Mitglied des Core Teams. Er organisiert und dokumentiert die Arbeit des Core Teams, stellt den Kontakt zwischen dem Core Team und den FreeBSD-Entwicklern her und agiert als Schnittstelle zum Admin Team bei der Aufnahme neuer Committer oder beim Anlegen neuer Benutzerzugänge. Außerdem ist der Core Team Secretary für die Erstellung monatlicher Statusberichte zuständig, in denen die FreeBSD-Entwickler über aktuelle Tätigkeiten und Entscheidungen des Core Teams informiert werden.

* {bofh}

[[t-doceng-secretary]]
=== Documentation Engineering Team Secretary <doceng-secretary@FreeBSD.org>

Der FreeBSD Documentation Engineering Team Secretary ist ein nicht stimmberechtigtes Mitglied des Documentation Engineering Teams. Seine Aufgabe ist es, die Arbeit von doceng zu dokumentieren, Abstimmungen zu protokollieren und den Kontakt mit anderen Teams, insbsondere den Admin und Core Teams, aufrecht zu erhalten.

* {0mp}

[[t-portmgr-secretary]]
=== Port Management Team Secretary <portmgr-secretary@FreeBSD.org>

Der FreeBSD Port Management Team Secretary ist ein nicht-stimmberechtigtes Mitglied des Port Management Teams. Er dokumentiert die Arbeit von portmgr@FreeBSD.org, führt Buch über durchgeführte Abstimmung und agiert als Schnittstelle zu anderen Teams, insbesondere zu den Admin und Core Teams. Außerdem ist er für die Erstellung monatlicher Statusberichte zuständig, in denen die FreeBSD-Entwickler über aktuelle Tätigkeiten und Entscheidungen des Port Management Teams informiert werden.

* {rene}

'''

[[t-accounts]]
=== Accounts Team <accounts@>

Das Accounts Team legt nach Rücksprache mit dem jeweiligen Team Benutzerzugänge für neue Committer an. Neue Zugänge werden ausschließlich nach erfolgter offizieller Zustimmung des betroffenen Teams angelegt.

E-Mails, die an das Accounts Team gesendet werden, werden derzeit an die link:#t-clusteradm[Cluster-Administratoren] weitergeleitet.

[[t-backups]]
=== Backups Administrators <backups@>

Die Backups Administrators kümmern sich um die Datensicherung auf dem FreeBSD-Cluster.

E-Mails, die an das Backups Administrators Team gesendet werden, werden derzeit an die link:#t-clusteradm[Cluster-Administratoren] weitergeleitet.

[[t-bugmeister]]
=== Bugmeisters <bugmeister@FreeBSD.org>

Bugmeister sind dafür verantwortlich, dass die Software zur Verwaltung von Problemberichten einwandfrei funktioniert, neue Einträge korrekt kategorisiert und ungültige Einträge entfernt werden.

* {eadler}
* {mva}
* {gavin}
* {koobs}

[[t-clusteradm]]
=== Cluster-Administratoren <clusteradm@>

Cluster-Administratoren warten die Server und Dienste, die für die Kommunikation innerhalb des Projekts und für die verteilte Arbeit am FreeBSD Project benötigt werden. Fragen zur Projektinfrastruktur oder zur Einrichtung neuer Systeme sollten an die Cluster-Administratoren gerichtet werden. Das Team wird vom Lead Cluster Administrator geleitet, dessen Aufgaben und Verantwortung in der link:../../en/internal/clusteradm/[Cluster Administration Charta] ausführlich beschrieben werden.

* {allanjude}
* {brd}
* {dhw}
* {gavin}
* {gjb}
* {lwhsu}
* {peter}
* {sbruno}
* {simon}
* {zi} (Lead)

[[t-dnsadm]]
=== DNS Administrators <dnsadm@>

DNS Administrators verwalten DNS und verwandte Dienste.

E-Mails, die an das DNS Administrators Team gesendet werden, werden derzeit an die link:#t-clusteradm[Cluster-Administratoren] weitergeleitet.

[[t-forum-admins]]
=== FreeBSD Forum Administrators <forum-admins@FreeBSD.org>

Das Forum Administrators Team betreut das Internetforum des FreeBSD Projects unter https://forums.freebsd.org/ und leitet auch das Moderatorenteam, um Qualität und Relevanz der geposteten Beiträge zu gewährleisten.

* {brd}
* {danger}
* {dutchdaemon}
* {lme}
* {wblock}

[[t-github-automation]]
=== Repository Automated Mirroring to GitHub Coordinators <github-automation@FreeBSD.org>

Das GitHub Automation Team überwacht den Export des FreeBSD Quellcoderepositories an die (read-only)-Instanzen auf GitHub.

* {koobs}
* {mva}
* {robak}
* {rodrigc}
* {uqs}

[[t-jenkins-admin]]
=== Jenkins Continuous Integration Testing Administrators <jenkins-admin@FreeBSD.org>

Jenkins-Administratoren sind für die kontinuierlichen Quellcodebau- und Integrationstests verantwortlich. Zu ihren Aufgaben gehören die Wartung der Jenkins-Instanz und aller Build- und Testjobs.

* {bapt}
* {brd}
* {brooks}
* {lwhsu}
* {markj} (Core Team Liaison)
* {seanc}
* {swills}

[[t-mirror-admin]]
=== FTP/WWW Mirror Site Coordinators <mirror-admin@FreeBSD.org>

FTP/WWW Mirror Site Coordinators koordinieren die Arbeit der Administratoren von FTP/WWW-Spiegelservern, damit diese stets aktuelle Softwareversionen anbieten können. Sie prüfen, ob die Spiegelserver die Kapazität haben, auch große Updates zu verwalten und machen es Anwendern einfach, den nächstgelegenen FTP/WWW-Spiegelserver zu finden.

E-mails an das Mirror Site Coordinators Team wird derzeit an die link:#t-clusteradm[Cluster-Administratoren] weitergeleitet. Und zusätzlich an:

* {kuriyama}

[[t-phabric-admin]]
=== Phabricator Code Review Application Administrators <phabric-admin@FreeBSD.org>

Das Phabricator Administrators Team ist für die Funktion der FreeBSD-Instanz des Phabricator-Online-Codereviewsystems unter https://reviews.freebsd.org/ verantwortlich:

* {allanjude}
* {bofh}
* {eadler}
* {emaste}
* {jtl}
* {lwhsu}
* {mat}
* {miwi}
* {pi}

Bei Problemen mit Phabricator erstellen Sie bitte einen https://bugs.freebsd.org/submit/[Problembericht]. Wählen Sie zuerst die Kategorie "Services" und danach "Code Review".

[[t-postmaster]]
=== Postmaster Team <postmaster@FreeBSD.org>

Das Postmaster Team sorgt für die korrekte Zustellung von E-Mails, betreibt die Mailinglisten und ergreift Maßnahmen gegen Trolle, Spam und Viren.

* {krion}
* {ler}
* {philip}
* {pi}
* {rea}
* {zi}

[[t-subversion]]
=== Subversion Administrators <svnadm@>

Das FreeBSD Subversion Team ist für die korrekte Funktion der Subversion Repositories verantwortlich.

E-mails an das Subversion Administration Team werden derzeit an die link:#t-clusteradm[Cluster-Administratoren] weitergeleitet.

[t-webmaster]]
=== Webmaster Team <webmaster@FreeBSD.org>

Das FreeBSD Webmaster Team ist für den reibungslosen Betrieb der Webseiten des FreeBSD Projects verantwortlich. Zu den Aufgaben dieses Teams gehören insbesondere die Konfiguration des Webservers und der CGI-Skripte sowie der Betrieb der Suchmaschinen für Webseite und Mailinglisten. Das Team kümmert sich um alle technischen Fragen, ausgenommen um Probleme innerhalb der Dokumentation.

E-Mails an das Webmaster Team werden derzeit an das link:#t-doceng[Documentation Engineering] Team weitergeleitet, und zusätzlich an:

* {wosch}

[[t-wiki]]
=== Wiki Admin Team <wiki-admin@FreeBSD.org>

Das FreeBSD Wiki Team ist für den Betrieb, das allgemeine Design sowie die Struktur des FreeBSD https://wiki.FreeBSD.org/[Wiki] verantwortlich.

* {gavin}
* {linimon}
* {theraven}
* {koobs}
