---
title: "Anwendungen für FreeBSD"
sidenav: about
---

= Anwendungen für FreeBSD

== Entdecken Sie die Möglichkeiten mit FreeBSD

FreeBSD kann fast jede Aufgabe übernehmen, die Sie von einer UNIX(R) Workstation erwarten, aber auch solche, die Sie vielleicht nicht erwarten:

== FreeBSD ist ein echtes Betriebssystem mit vollständig verfügbarem Quelltext.

Es besteht kein Zweifel, dass so genannte "Offene Systeme" _die_ Bedingung für heutige Computer-Anwendungen sind. Aber keine kommerzielle Lösung ist offener als eine, die den vollständigen Quelltext des gesamten Betriebssystemes enthält, sowohl des Kernels als auch sämtlicher Dienste und Programme. Sie können jeden Teil von FreeBSD an Ihre persönlichen Bedürfnisse oder die Ihrer Organisation oder Ihres Unternehmens anpassen.

Dank seiner freizügigen link:../../en/copyright/freebsd-license/[Lizenz], können Sie FreeBSD als Basis für alle nur denkbaren kostenlosen _oder kommerziellen_ Anwendungen benutzen.

== FreeBSD ist bereit für Tausende von Programmen.

Da FreeBSD auf 4.4BSD, einer Industrie-Standardversion von UNIX, basiert, ist es sehr einfach, Programme zu kompilieren und auszuführen. FreeBSD enthält zusätzlich eine enorm große link:../where/[Package-Sammlung] und die link:../ports/[Ports-Sammlung], die vorkompilierte und einfach zu kompilierende Software direkt zu Ihrem Desktop oder Enterprise-Server bringt. Außerdem existiert eine wachsende Anzahl an link:../../en/commercial/software/[kommerziellen Anwendungen], die direkt für FreeBSD geschrieben wurden.

Hier sind einige Beispiele von Umgebungen, in denen FreeBSD benutzt wird:

* *Internet Dienste.* Viele Internet Service Provider (ISPs) finden FreeBSD ideal, um WWW, Usenet-News, FTP, E-Mail und andere Dienste zu betreiben. Gebrauchsfertige Software, wie die Webserver http://nginx.org[nginx] oder http://www.apache.org/[Apache], FTP-Server wie http://security.appspot.com/vsftpd.html[vsftpd] oder http://proftpd.org/[ProFTPD] machen es einfach, ein Gewerbe oder einen ISP einzurichten. Natürlich werden sich Ihre Benutzer dabei dank FreeBSDs unschlagbarer link:../internet/[Netzwerkeigenschaften] über hohe Geschwindigkeit und zuverlässige Dienste freuen können.
* *X Window Workstation.* Sei es ein preiswertes X-Terminal oder eine erweiterte X-Workstation, FreeBSD arbeitet sehr zuverlässig. Kostenlose X Software (http://X.org/[X.org](TM)) wird mitgeliefert. http://www.nvidia.com/[nVidia] stellt native Treiber für ihre leistungsfähigen Grafikkarten, den Industrie-Standard http://www.opengroup.org/motif/[Motif](R) sowie http://www.opengl.org/[OpenGL](R)-Bibliotheken bereit. http://xfce.org/[Xfce] und http://lxde.org/[LXDE] bieten Ihnen eine Desktopumgebung. Sowohl http://www.kde.org[KDE] als auch http://www.gnome.org[GNOME] können als vollständige Desktopumgebungen installiert werden. Beide enthalten auch Office-Funktionen, Sie können aber auch die Officepakete https://www.libreoffice.org/[LibreOffice], http://www.openoffice.org/[OpenOffice.Org] oder http://www.softmaker.com/en/[TextMaker] installieren.
* *Netzwerkdienste.* Von Paket-Filtern über Routing zu Namensdiensten: FreeBSD kann aus einem PC eine Internet-Firewall, einen E-Mail-Server, einen Druckserver, einen PC/NFS Server und noch viel mehr machen.
* *Software Entwicklung.* Eine Reihe von Entwicklungswerkzeugen wird mit FreeBSD geliefert, einschließlich GNU C/C++ Compiler und Debugger. Die auf LLVM basierende Clang-Compilersuite ist ebenfalls verfügbar und soll künftig die GNU-Compilersuite ersetzen. Die Entwicklung mit Java(R) und Tcl/Tk-Entwicklung sowie diversen ungewöhnlichen Programmiersprachen wie Icon ist natürlich ebenso möglich. Und dynamische Laufzeitbibliotheken waren unter FreeBSD schon immer einfach zu erstellen und zu benutzen. Für die tägliche Arbeit setzen Sie einen der zahlreich verfügbaren und mächtigen Editoren, wie XEmacs oder Vim, ein.
* *Internet-Surfen.* Eine echte UNIX Workstation ist ein perfektes "Surfbrett" für das Internet, die FreeBSD-Versionen von http://www.chromium.org/Home[Chromium], http://www.mozilla.org/firefox/[Firefox] und http://www.opera.com/[Opera] sind verfügbar. Surfen Sie im Internet, publizieren Sie Ihre eigenen Webseiten, lesen Sie Usenet-News und senden und empfangen Sie E-Mails - mit FreeBSD auf Ihrem Desktop ist dies alles kein Problem.
* *Ausbildung und Forschung.* FreeBSD ist perfekt für Forschungszwecke geeignet, da es mit kompletten Quelltext kommt. Studenten und Wissenschaftler, die an Betriebssystemen oder in anderen Gebieten der Informatik forschen, profitieren von einem offenem und gut dokumentiertem System wie FreeBSD.
* *Und vieles mehr.* Accounting, Action-Spiele, MIS Datenbanken, wissenschaftliche Visualisierung, Video-Konferenzen, Internet Relay Chat (IRC), Haustechnik, Multiuser-Dungeons, Bulletin Board Systeme, Bildbearbeitung und vieles mehr - das alles sind heutzutage bereits echte Anwendungsgebiete von FreeBSD.

== FreeBSD ist ein Betriebssystem, das mit Ihren Ansprüchen wächst.

Obwohl FreeBSD freie Software ist, ist es auch Software, für die es _Unterstützung_ gibt. Jede Frage, die Sie haben, kann zu Hunderten von FreeBSD-Entwicklern und Benutzern geschickt werden, indem Sie einfach eine E-Mail an die Mailingliste de-bsd-questions@de.FreeBSD.org senden.

FreeBSD hat außerdem eine weltweite Gruppe von Programmierern und Autoren, die Fehler beseitigen, neue Sachen implementieren und das System dokumentieren. Unterstützung für neue Hardware oder spezielle Dinge ist ein konstanter Entwicklungsprozess, bei dem insbesondere auf die Systemstabilität geachtet wird. FreeBSD-Benutzer sind ziemlich stolz darauf, dass ihre Systeme nicht nur schnell, sondern zugleich auch noch äußerst stabil sind.

== Was Experten sagen ...

_'FreeBSD handles [our] heavy load quite well and it is nothing short of amazing. Salutations to the FreeBSD team.'_

---Mark Hittinger, administrator of WinNet Communications, Inc.
