---
title: "FreeBSD Ansprechpartner"
sidenav: about
---

include::shared/en/urls.adoc[]

= FreeBSD Ansprechpartner

== Fragen zu FreeBSD

Fragen zu FreeBSD sollten auf der Mailingliste de-bsd-questions@de.FreeBSD.org gestellt werden.

Die Unterstützung der FreeBSD-Benutzer wird hauptsächlich über die link:../community/mailinglists/[Mailinglisten] abgewickelt. Es gibt viele Listen zu verschiedenen Themen, nicht englische Listen stehen ebenfalls zur Verfügung.

== Fragen zum Inhalt dieses WWW-Servers

Fragen und Vorschläge zur Dokumentation (dem link:{handbook}[Handbuch], der link:{faq}[FAQ] sowie den link:../docs/[Büchern und Artikeln]) sollten auf der Liste des FreeBSD Documentation Projects freebsd-doc@FreeBSD.org gestellt werden.

Fragen zur deutschen Dokumentation sollten auf der Liste mailto:de-bsd-translators@DE.FreeBSD.org[de-bsd-translators@de.FreeBSD.org] gestellt werden.

== Sonstiges

CD-ROMs bestellen: http://www.freebsdmall.com/[The FreeBSD Mall]

Kommerzielle Unterstützung: http://www.freebsdmall.com/[The FreeBSD Mall]

== Ansprechpartner

link:../administration/[Wer macht was?] Öffentlichkeitsarbeit, Security-Officer, Postmaster, Webmaster etc.
