#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: doc/fr_FR.ISO8859-1/books/Makefile.inc,v 1.1 1999/11/10 21:28:31 nik Exp $
#    Original revision: 1.2
#

DESTDIR?=	${DOCDIR}/fr_FR.ISO8859-1/books/${.CURDIR:T}
