#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: doc/fr_FR.ISO_8859-1/books/Makefile,v 1.1 1999/11/10 21:28:31 nik Exp $
#    Original revision: 1.4
#

SUBDIR = faq
SUBDIR+= handbook
SUBDIR+= fdp-primer

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
