# $FreeBSD$

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=	doc-set.sgml
DOCS+=	hungarian.sgml
DOCS+=  sgml.sgml
DOCS+=  submitting.sgml
DOCS+=  who.sgml
DOCS+=	docproj.sgml

INDEXLINK= docproj.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
