# $FreeBSD$

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=	doc-set.xml
DOCS+=	hungarian.xml
DOCS+=  sgml.xml
DOCS+=  submitting.xml
DOCS+=  who.xml
DOCS+=	docproj.xml

INDEXLINK= docproj.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
