# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	05.sgml
DOCS+=	12.sgml
DOCS+=	19.sgml
DOCS+=	26.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
