# $FreeBSD: www/en/releases/5.1R/Makefile,v 1.1 2003/03/21 05:59:50 scottl Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	todo.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
