# $FreeBSD$
# %SOURCE%    en_US.ISO8859-1/Makefile
# %SRCID%     1.7

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = hu

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
