---
title: "Projet Java® pour FreeBSD : Comment effectuer l'installation"
sidenav: developers
---

include::shared/fr/urls.adoc[]

= Projet Java(R) pour FreeBSD : Comment effectuer l'installation

Lorsque vous installez Java sous FreeBSD, vous avez le choix entre plusieurs Kits de Développement Java :

[[jdk]]
== Le JDK natif sous FreeBSD

C'est le résultat du travail de l'équipe de portage sous FreeBSD de Java 2. En utilisant les patches et le code source du JDK publiés par Sun, ce port compile un JDK natif pour FreeBSD.

`cd /usr/ports/java/jdk14`

`make install clean`

[[linux-sun-jdk]]
== JDK Sun pour Linux

Ce port installe le Kit de Développement Java 2 de Sun compilé pour Linux. Il tournera sous FreeBSD en utilisant la compatibilité binaire avec Linux.

`cd /usr/ports/java/linux-sun-jdk14`

`make install clean`

[[linux-ibm-jdk]]
== JDK IBM pour Linux

Il s'agit d'une implémentation de l'édition standard du SDK Java 2 pour Linux d'IBM, version 1.4. Contient le compilateur IBM juste-à-temps (just-in-time), amélioré avec un Interpréteur Mode Mixte et une machine virtuelle Java 2 retravaillée.

`cd /usr/ports/java/linux-ibm-jdk14`

`make install clean`

[[linux-blackdown-jdk]]
== JDK Blackdown pour Linux

Kit du développeur Java Blackdown 1.4.1. Contient les machines virtuelles du client Hotspot et du serveur, ainsi qu'une version améliorée de Java Web Start 1.2, un plugin Java pour les navigateurs basés sur Mozilla et un plugin Java pour les navigateurs Netscape 4.x.

`cd /usr/ports/java/linux-blackdown-jdk14`

`make install clean`

*Note :* Veuillez noter qu'en raison de la politique de licence actuelle de Sun, les binaires ne peuvent être redistribués et que vous êtes seul autorisé à les utiliser/étudier. Pour les mêmes raisons, vous devez récupérer manuellement le code source et les patches pour FreeBSD.

Si vous rencontrez des problèmes, consultez le Manuel de référence de FreeBSD au chapitre link:{handbook}#ports[installer des applications] pour trouver de l'aide.
