---
authors:
  - 
    author: 'The FreeBSD Documentation Project'
bookOrder: 5
copyright: '1995-2023 The FreeBSD Documentation Project'
description: 'Часто задаваемые вопросы по FreeBSD'
layout: single
tags: ["FAQ", "FreeBSD FAQ"]
title: 'Часто задаваемые вопросы по FreeBSD'
trademarks: ["freebsd", "ieee", "linux", "microsoft", "openbsd", "netbsd", "general"]
---

= Часто задаваемые вопросы по FreeBSD
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/faq/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[.abstract-title]
Аннотация

Это Часто Задаваемые Вопросы (FAQ) по FreeBSD. Были приложены все усилия, чтобы сделать это руководство максимально информативным.

'''

toc::[]

[[introduction]]
== Введение

Добро пожаловать в мир FreeBSD! В этом разделе представлен обзор системы FreeBSD: что это такое, её происхождение, цели, варианты использования и сообщество, стоящее за ней.

Узнайте причины выбора этого названия, научитесь участвовать в разработке проекта и изучите богатую экосистему FreeBSD в контексте открытых операционных систем.

[[what-is-FreeBSD]]
=== Что такое FreeBSD?

FreeBSD — это универсальная и открытая операционная система, подобная UNIX(R), известная своей исключительной стабильностью, безопасностью и производительностью. Разрабатываемая преданным сообществом добровольцев, она основана на операционной системе Berkeley Software Distribution (BSD) UNIX.

FreeBSD предоставляет мощную и настраиваемую среду, подходящую для широкого спектра применений — от серверов и встраиваемых систем до настольных компьютеров и сетевого оборудования. Приверженность принципам открытого исходного кода обеспечивает прозрачный и совместный процесс разработки, что делает FreeBSD надежным выбором для тех, кто ищет стабильную и высокоадаптируемую операционную систему.

[[why-called-FreeBSD]]
=== Почему система называется FreeBSD?

Название "FreeBSD" происходит от его корней в операционной системе UNIX Berkeley Software Distribution (BSD), известной своим вкладом в мир открытого программного обеспечения. Слово "Free" в FreeBSD подчеркивает приверженность принципам свободного и открытого программного обеспечения, которые предоставляют пользователям свободу изучать, изменять и распространять исходный код.

Стоит отметить, что слово «free» здесь используется в двух значениях: одно означает «бесплатно», а другое — «делай что хочешь».

[[FreeBSD-goals]]
=== Какова цель проекта FreeBSD?

Проект FreeBSD преследует ясную и непоколебимую цель: предоставить высококачественную UNIX-подобную операционную систему с открытым исходным кодом, которая отличается высокой производительностью, безопасностью и стабильностью.

Он стремится предоставить универсальную платформу, подходящую для широкого спектра вычислительных задач — от серверов и рабочих станций до встраиваемых систем и не только. FreeBSD разрабатывается с твердой приверженностью принципам открытого исходного кода, создавая среду для сотрудничества, в которой вклад глобального сообщества разработчиков помогает формировать и совершенствовать операционную систему. Эта приверженность качеству, свободе и надежности отличает FreeBSD и способствует её постоянному успеху как проекта с открытым исходным кодом.

[[FreeBSD-usecases]]
=== Для каких задач подходит FreeBSD?

FreeBSD — это универсальная операционная система, которая превосходно подходит для различных сценариев использования. Она особенно хорошо зарекомендовала себя в серверных средах, где её стабильность и производительность делают её популярным выбором для веб-хостинга, баз данных и сетевых приложений. Надёжные механизмы безопасности FreeBSD также делают её отличным вариантом для развёртывания межсетевых экранов и защищённых устройств. Помимо серверов, FreeBSD может быть адаптирована для работы в специализированных средах, включая встраиваемые системы и игровые консоли. Её гибкость, надёжность и открытый исходный код делают FreeBSD привлекательным выбором для широкого спектра вычислительных задач.

[[responsible]]
=== Кто отвечает за FreeBSD?

FreeBSD - это проект с открытым исходным кодом, развиваемый сообществом и имеющий децентрализованную структуру. Его разработка и поддержка осуществляются глобальным сообществом преданных добровольцев, разработчиков и организаций, которые совместно работают над улучшением и расширением возможностей операционной системы.

Ключевые решения, касающиеся проекта FreeBSD, такие как общее направление развития проекта или право на добавление кода в дерево исходных текстов, принимаются избираемой командой разработчиков (Core Team) из девяти человек.

Этот совместный и ориентированный на сообщество подход был основополагающим для успеха и долголетия FreeBSD в качестве надежной и устойчивой UNIX-подобной операционной системы.

[[how-to-contribute]]
=== Как я могу внести свой вклад в FreeBSD? Чем я могу помочь?

Мы принимаем все виды вкладов: документацию, код и даже произведения искусства. Конкретные рекомендации о том, как это сделать, смотрите в статье extref:{contributing}[Участие в разработке FreeBSD].

И спасибо за идеи!

[[bsd-license-restrictions]]
=== Есть ли ограничения в лицензии FreeBSD?

FreeBSD распространяется под лицензией https://www.FreeBSD.org/copyright/freebsd-license/[BSD License], известной своим разрешительным характером.

Данная лицензия накладывает очень мало ограничений на использование FreeBSD:

* Не утверждайте, что это написали вы.
* Не подавайте на нас в суд, если что-то сломается.
* Не удаляйте и не изменяйте лицензию.

Лицензия означает, что вы можете свободно изменять, распространять и даже продавать FreeBSD, *не будучи обязанным публиковать свои изменения как открытый исходный код*. Однако есть несколько минимальных условий, таких как сохранение оригинального уведомления об авторских правах и отказ от гарантий при распространении FreeBSD. В целом, лицензия BSD предоставляет высокую степень свободы и гибкости, что делает FreeBSD привлекательным выбором для широкого спектра приложений и проектов.

Код в нашем дереве исходников, подпадающий под действие https://www.FreeBSD.org/copyright/COPYING[GNU General Public License (GPL)] или https://www.FreeBSD.org/copyright/COPYING.LIB[GNU Library General Public License (LGPL)], сопровождается несколько большими ограничениями, по крайней мере, в части обеспечения доступа, в отличие от обычной противоположной ситуации.

[[replace-current-OS]]
=== Может ли FreeBSD заменить мою текущую операционную систему?

Для многих пользователей и администраторов — да. Но этот вопрос не настолько однозначен.

FreeBSD — это мощная и универсальная операционная система, которая может заменить или сосуществовать с множеством других операционных систем в зависимости от конкретных потребностей пользователей и администраторов. Однако возможность замены вашей текущей операционной системы на FreeBSD зависит от таких факторов, как ваше оборудование, требования к программному обеспечению и уровень знакомства с FreeBSD.

Хотя она предлагает надежную и многофункциональную альтернативу, важно оценить ваши конкретные задачи и требования к совместимости перед переходом.

Если приложение доступно только в одной операционной системе, эту операционную систему нельзя просто заменить.

Пользователи, переходящие на FreeBSD из другой UNIX-подобной среды, найдут FreeBSD похожей. Пользователи, не знакомые с UNIX, например пользователи Windows(R), должны быть готовы потратить дополнительное время на изучение принципов работы UNIX.

[[run-popular-software]]
=== Может ли FreeBSD запускать популярное открытое программное обеспечение?

Да, FreeBSD хорошо подходит для запуска популярного открытого программного обеспечения. Его совместимость с широким спектром приложений и библиотек делает его предпочтительным выбором для тех, кто хочет развертывать и использовать пакеты открытого ПО. FreeBSD предоставляет надежную и стабильную среду, поддерживающую различные языки программирования, базы данных, веб-серверы и другое ПО, часто используемое в сообществе открытого исходного кода. Система портов и пакетов FreeBSD упрощает установку и управление таким ПО, гарантируя, что пользователи могут легко получить доступ и запускать свои любимые открытые инструменты и приложения на FreeBSD с минимальными трудностями.

[[install-software]]
=== Как установить программное обеспечение в FreeBSD?

FreeBSD предоставляет несколько методов установки программного обеспечения. Один из наиболее распространённых методов — использование встроенного менеджера пакетов man:pkg[8], который упрощает процесс, загружая и устанавливая предварительно собранные бинарные пакеты. Другой подход — компиляция и установка программ из исходного кода с использованием коллекции man:ports[7], что обеспечивает гибкий и настраиваемый способ установки программного обеспечения.

Документация FreeBSD предоставляет подробные руководства по обоим методам, гарантируя, что пользователи смогут легко расширить возможности своей системы с помощью необходимого программного обеспечения.

[[differences-to-other-bsds]]
=== Каковы различия между FreeBSD, NetBSD, OpenBSD и другими открытыми BSD-операционными системами?

FreeBSD, NetBSD, OpenBSD и DragonFly BSD - все они являются частью семейства BSD с открытым исходным кодом, разделяя общие UNIX-подобные основы, но каждый имеет свою собственную направленность и приоритеты. Эти различия отражают уникальные цели каждого проекта, и хотя они имеют сходства, их конкретные сильные стороны и акценты ориентированы на различные сценарии использования и предпочтения в экосистеме BSD.

[[freebsd-linux-distribution]]
=== Является ли FreeBSD дистрибутивом Linux(R)?

Нет, FreeBSD *не* является дистрибутивом Linux.

Хотя FreeBSD и Linux являются UNIX-подобными операционными системами и имеют много общего, у них разные ядра. Linux использует ядро Linux, тогда как FreeBSD использует ядро FreeBSD, основанное на операционной системе Berkeley Software Distribution (BSD) UNIX.

FreeBSD и Linux имеют свои уникальные сообщества разработчиков, циклы выпуска версий и архитектуры систем, что делает их отдельными и независимыми операционными системами.

FreeBSD предоставляет свои собственные преимущества, включая отличную модель лицензирования, дизайн системы и пользовательские утилиты по сравнению с дистрибутивами Linux.

[[run-linux-programs-freebsd]]
=== Возможно ли запускать Linux-программы в FreeBSD?

Да, FreeBSD предоставляет слой совместимости, известный как _linuxulator_ (man:linux[4]), который позволяет многим Linux-программам работать в FreeBSD. Эта функция обеспечивает выполнение широкого спектра Linux-бинарников без необходимости в отдельной Linux-среде.

Тем не менее, важно отметить, что множество широко используемых программ с открытым исходным кодом *имеют собственные версии для FreeBSD*, доступные через систему портов и пакетов.

[[installing-freebsd]]
== Установка FreeBSD

Процесс установки FreeBSD — это первый шаг к использованию возможностей этой мощной операционной системы с открытым исходным кодом. В этом разделе представлена важная информация о том, где получить FreeBSD, подробные инструкции по установке, а также объяснение таких концепций, как FreeBSD-CURRENT и FreeBSD-STABLE. Также рассматриваются график выпуска релизов и снимков (snapshots), инструменты настройки после установки, методы поиска пакетов и ответы на часто задаваемые вопросы об обновлении пакетов.

[[where-get]]
=== Где взять FreeBSD?

FreeBSD доступна для бесплатной загрузки по ссылке: link:https://www.FreeBSD.org/ru/where/[официальный сайт FreeBSD].

Кроме того, FreeBSD также может быть доступен через различные зеркальные сайты, что обеспечивает доступность для пользователей по всему миру. Основным и наиболее надежным источником для получения последних выпусков и обновлений FreeBSD является link:https://www.FreeBSD.org/ru/where/[официальный сайт], что делает его идеальной отправной точкой для начала работы с FreeBSD.

[[install-instructions-location]]
=== Где находятся инструкции по установке FreeBSD?

Инструкции по установке можно найти в главе extref:{handbook}bsdinstall/[Установка FreeBSD Руководства].

[[current]]
=== Что такое концепция FreeBSD-CURRENT?

FreeBSD-CURRENT представляет собой ветку разработки операционной системы FreeBSD. Это самая передовая версия FreeBSD, в которой ведётся активная разработка.

Хотя он включает последние функции, улучшения и экспериментальные изменения, он не всегда может быть таким стабильным, как FreeBSD-STABLE или релизные версии.

FreeBSD-CURRENT — это платформа для разработчиков и энтузиастов, которые хотят внести свой вклад в будущее FreeBSD и оставаться на переднем крае её разработки, даже несмотря на то, что в ней могут иногда происходить значительные изменения и *она не рекомендуется для производственных систем*.

[[stable]]
=== Что такое концепция FreeBSD-STABLE?

Ветка FreeBSD-STABLE — это более стабильная ветка разработки по сравнению с CURRENT. Она содержит код, который проходит дополнительные тестирование и доработку перед слиянием в ветку RELEASE. STABLE — хороший выбор для тех, кто хочет следить за разработкой FreeBSD, но предпочитает более стабильную среду, чем CURRENT.

[[release-freq]]
=== Когда выходят выпуски FreeBSD?

Версия {re} выпускает новую основную версию FreeBSD примерно каждые 18 месяцев и новую промежуточную версию — в среднем каждые 8 месяцев. Даты выпуска объявляются заранее, чтобы разработчики знали, когда их проекты должны быть завершены и протестированы. Перед каждым выпуском проводится период тестирования, чтобы убедиться, что добавление новых функций не нарушает стабильность релиза.

[[snapshot-freq]]
=== Когда создаются снимки состояния FreeBSD?

Снимки FreeBSD обычно создаются с регулярными интервалами для всех активно разрабатываемых веток. Эти снимки фиксируют состояние исходного кода FreeBSD и связанных с ним бинарных пакетов на определённый момент времени. Частота создания снимков может варьироваться, но обычно они делаются еженедельно или раз в две недели. Эти снимки предоставляют пользователям возможность получить доступ к последним изменениям и разработкам в FreeBSD, помогая им оставаться в курсе прогресса проекта.

[[general-configuration-tool]]
=== Есть ли инструмент для выполнения задач пост-установочной конфигурации?

Да. man:bsdconfig[8] предоставляет удобный интерфейс для настройки FreeBSD после установки.

[[search-software-freebsd]]
=== Как найти программное обеспечение для установки в FreeBSD?

Поиск программного обеспечения для установки в FreeBSD упрощается благодаря менеджеру пакетов man:pkg[8] и команде `pkg search`.

Пользователи могут использовать эту команду для поиска доступных пакетов по ключевым словам, названиям пакетов или описаниям. Эта функция помогает быстро найти нужное программное обеспечение в обширной коллекции портов и пакетов FreeBSD, упрощая процесс добавления новых приложений и инструментов в систему FreeBSD.

[[latest-packages-freebsd]]
=== Почему я не получаю последние пакеты в моей системе FreeBSD?

Доступность последних пакетов в FreeBSD может зависеть от различных факторов, включая частоту обновлений репозитория пакетов и используемую версию FreeBSD.

Также следует отметить, что для портов FreeBSD существуют две ветки. Наиболее обновляемая называется `latest`, а наиболее стабильная — `quarterly`. Для использования самых свежих пакетов необходимо настроить ветку `latest`. Информацию о настройке веток можно найти в link:{handbook}ports/[главе о портах в Руководстве].

[[hardware]]
== Оборудование

В разделе «Оборудование» рассматривается совместимость FreeBSD с различными аппаратными конфигурациями. Он охватывает широкий круг тем, включая поддерживаемые архитектуры, максимальный объем оперативной памяти, масштабируемость процессоров, совместимость с видеокартами, поддержку Wi-Fi-адаптеров, а также работу с сетевыми картами 10 Gigabit Ethernet. Независимо от того, планируется ли развертывание FreeBSD на серверах, рабочих станциях или специализированном оборудовании, этот раздел дает представление о возможностях и ограничениях FreeBSD, предоставляя информацию о выборе и настройке оборудования.

[[architectures-support]]
=== Какие архитектуры поддерживает FreeBSD?

FreeBSD поддерживает широкий спектр архитектур, что делает его гибким выбором для различных аппаратных сред. Совместимость распространяется на такие архитектуры, как `amd64`, `arm64`, `riscv` и другие.

Полный список поддерживаемых архитектур можно найти на странице link:https://www.FreeBSD.org/platforms/[платформ].

[[ram-support]]
=== Сколько оперативной памяти поддерживает FreeBSD?

FreeBSD как операционная система обычно поддерживает столько же физической памяти (RAM), сколько и платформа, на которой она работает. Следует учитывать, что разные платформы имеют разные ограничения по памяти.

Например, платформы `amd64` поддерживают до 4 ТБ физической памяти.

[[cpu-support]]
=== Сколько процессоров поддерживает FreeBSD?

Поддержка процессоров в FreeBSD варьируется в зависимости от архитектуры. На системах amd64 и arm64 FreeBSD может эффективно использовать до 1024 процессоров. На системах с архитектурой powerpc FreeBSD поддерживает до 256 процессоров, а на системах risc-v — до 16 процессоров.

[[graphics-cards-support]]
=== Какие графические карты поддерживает FreeBSD?

Известные производители графических устройств, такие как Intel(R), AMD(R) или NVIDIA(R), хорошо поддерживаются.

Список поддерживаемых видеокарт от link:https://wiki.freebsd.org/Graphics/Intel-GPU-Matrix[Intel] и link:https://wiki.freebsd.org/Graphics/AMD-GPU-Matrix[AMD] можно найти в FreeBSD Wiki.

[[wifi-support]]
=== Какие Wi-Fi карты поддерживает FreeBSD?

Это область, которая быстро меняется по состоянию на 2025 год, поэтому рекомендуется проверить Список совместимого оборудования для выбранного link:https://www.freebsd.org/releases/[релиза].

Список устройств PCIe Wi-Fi, которые хорошо работают в FreeBSD:

* Устройства на чипсетах Intel, поддерживаемые man:iwlwifi[4] (высокоскоростные — начиная с FreeBSD 14.3)
* Realtek RTL8188CE Mini PCIe

Список USB Wi-Fi устройств, которые хорошо работают в FreeBSD:

* USB-адаптеры RT5370 (поддерживают режим hostap)
* TP-Link TL-WDN3200 (RT5592, man:if_run[4])
* TP-Link TL-WN725N v2 (RTL8188EU, man:rtwn[4])
* TP-Link Archer T4U (RTL8812AU, man:rtwn[4])
* D-Link DWA-131 (RTL8192CU, man:rtwn[4])
* D-Link DWA-171 rev A1 (RTL8821AU, man:rtwn[4])
* ASUS USB-N10 NANO (RTL8188CUS, man:rtwn[4])


[[gigabit-ethernet-network-support]]
=== Поддерживает ли FreeBSD сетевые карты 10 Gigabit Ethernet?

FreeBSD обеспечивает надежную поддержку сетевых карт 10 Gigabit Ethernet, что делает его подходящим выбором для высокоскоростных сетевых сред. Ядро FreeBSD включает драйверы для широкого спектра адаптеров 10 Gigabit Ethernet от различных производителей, гарантируя беспрерывную интеграцию и оптимальную производительность сети.

Дополнительную информацию можно получить по ссылке: link:https://wiki.freebsd.org/Networking/10GbE[FreeBSD Wiki].

[[documentation-support]]
== Документация и Поддержка

В этом разделе представлены полезные ресурсы для тех, кто хочет углубить свои знания о FreeBSD. Здесь рассматриваются различные темы, включая рекомендуемые книги для изучения FreeBSD, варианты коммерческого обучения и поддержки, информацию о понимании внутреннего устройства FreeBSD, а также о том, где можно получить помощь в сообществе FreeBSD.

[[books]]
=== Какие есть хорошие книги о FreeBSD?

Энтузиасты и изучающие FreeBSD могут ознакомиться с разнообразными информативными книгами, посвящёнными этой операционной системе. Эти книги охватывают темы от основ FreeBSD до продвинутого системного администрирования и разработки.

Некоторые примечательные книги включают *"FreeBSD: Подробное руководство" ("Absolute FreeBSD: The Complete Guide To FreeBSD")* Майкла В. Лукаса и серию *"FreeBSD Mastery"* того же автора, среди прочих. Эти ресурсы предоставляют ценные знания и помогают пользователям любого уровня освоить FreeBSD и раскрыть её потенциал.

Помимо книг, проект FreeBSD создает обширную документацию, доступную онлайн на портале link:https://docs.FreeBSD.org/[Документация].

[[training]]
=== Где можно получить коммерческое обучение и поддержку FreeBSD?

Для тех, кто ищет профессиональное обучение и поддержку по FreeBSD, несколько коммерческих поставщиков предлагают индивидуальные услуги. Проект FreeBSD ведет link:https://www.freebsd.org/commercial/[список компаний], у которых можно запросить поддержку.

[[learn-advanced]]
=== Как можно узнать больше о внутреннем устройстве FreeBSD?

Для более глубокого изучения внутреннего устройства FreeBSD заинтересованные лица могут обратиться к таким ресурсам, как "FreeBSD: Дизайн и архитектура (The Design And Implementation Of The FreeBSD Operating System)". Ещё одним ценным источником информации является extref:{arch-handbook}[Руководство по архитектуре FreeBSD], который предоставляет подробные сведения об архитектуре FreeBSD, организации системы и принципах проектирования

Кроме того, изучение исходного кода FreeBSD, доступного в репозитории исходных текстов FreeBSD, дает ценное представление об основных компонентах операционной системы.

[[help-freebsd-system]]
=== Как получить помощь в системе FreeBSD?

Получить помощь в системе FreeBSD довольно просто. FreeBSD предоставляет обширную встроенную документацию, доступную через команду man:man[1], которая содержит подробную информацию о различных командах и компонентах системы.

Кроме того, extref:{handbook}[Руководство FreeBSD], доступное как онлайн, так и локально в системе, служит ценным ресурсом для получения подробных инструкций.

Если возникают конкретные проблемы, можно обратиться за помощью в сообщество FreeBSD через списки рассылки, форумы или IRC, чтобы получить своевременные решения и советы от опытных пользователей и разработчиков FreeBSD.

[[community-questions]]
== Вопросы о сообществе

Изучите этот раздел, чтобы узнать о способах взаимодействия с сообществом FreeBSD.

Узнайте о каналах FreeBSD в IRC для обсуждений в реальном времени, веб-форумах для обмена мнениями, а также о почтовых рассылках и группах новостей FreeBSD для углубленных обсуждений и получения обновлений.

[[irc]]
=== Есть ли каналы FreeBSD в IRC (Internet Relay Chat)?

Да, большинство крупных IRC-сетей имеют канал для обсуждения FreeBSD, а на вики FreeBSD доступен актуальный link:https://wiki.freebsd.org/IRC/Channels[список IRC-каналов].

Каждый из этих каналов уникален и не связан с другими. Поскольку их стили общения различаются, попробуйте каждый, чтобы найти подходящий вам стиль чата.

[[forums]]
=== Есть ли веб-форумы для обсуждения FreeBSD?

Официальные форумы FreeBSD расположены по ссылке: link:https://forums.FreeBSD.org/[Домашняя страница форумов FreeBSD].

[[mailing]]
=== Где найти информацию о списках рассылки FreeBSD?

Списки рассылки с открытым доступом можно найти по ссылке: link:https://lists.freebsd.org/[списки рассылки FreeBSD].

[[misc]]
== Разные вопросы

Изучите множество интересных и практичных вопросов о FreeBSD, начиная от выбора оболочки (shell) до особенностей системы и даже имени питомца FreeBSD.

[[minimal-sh]]
=== Почему /bin/sh такой минималистичный? Почему FreeBSD не использует bash или другую оболочку?

Многие люди сталкиваются с необходимостью написания сценариев командной оболочки, которые будут переносимы между различными системами. Именно поэтому POSIX(R) детально определяет стандарты для оболочки и утилит. Большинство сценариев пишутся на Bourne shell (man:sh[1]), так как несколько важных программных интерфейсов требуют использования Bourne shell для интерпретации команд. Поскольку Bourne shell так часто и широко применяется, важно, чтобы он быстро запускался, имел предсказуемое поведение и требовал мало памяти.

Существующая реализация — это наш наилучший подход к одновременному удовлетворению как можно большего числа этих требований. Чтобы сохранить `/bin/sh` компактным, мы не добавили многие удобные функции, которые есть в других оболочках.

Вот почему доступны другие, более функциональные оболочки, такие как `bash`, `scsh`, man:tcsh[1] и `zsh`.

[[keyboard-delete-key]]
=== Как использовать клавишу Delete в sh и csh?

Для оболочки Bourne Shell добавьте следующие строки в файл [.filename]#~/.shrc#:

[.programlisting]
....
bind ^[[3~ ed-delete-next-char # for xterm
....

Для оболочки C Shell добавьте следующие строки в файл [.filename]#~/.cshrc#:

[.programlisting]
....
bindkey ^[[3~ delete-char # for xterm
....

[[forgot-root-pw]]
=== Я забыл пароль root! Что делать?

Не паникуйте! Перезагрузите систему, введите `boot -s` при появлении запроса `Boot:`, чтобы перейти в однопользовательский режим. На вопрос о выборе оболочки нажмите kbd:[Enter], после чего появится приглашение #. Введите `mount -urw /`, чтобы перемонтировать корневую файловую систему в режиме чтения/записи, затем выполните `mount -a` для перемонтирования всех файловых систем. Выполните `passwd root`, чтобы изменить пароль `root`, а затем введите man:exit[1] для продолжения загрузки.

[TIP]
====
Если при входе в однопользовательский режим всё ещё запрашивается пароль `root`, это означает, что консоль помечена как `insecure` в [.filename]#/etc/ttys#. В этом случае потребуется загрузиться с установочного диска FreeBSD, выбрать [.guimenuitem]#Live CD# или [.guimenuitem]#Shell# в начале процесса установки и выполнить указанные выше команды. Смонтируйте конкретный раздел в этом случае и затем выполните chroot для него. Например, замените `mount -urw /` на `mount /dev/ada0p1 /mnt; chroot /mnt` для системы на _ada0p1_.
====

[TIP]
====
Если корневой раздел не удаётся смонтировать в однопользовательском режиме, возможно, разделы зашифрованы, и их невозможно смонтировать без ключей доступа. Дополнительную информацию см. в разделе о зашифрованных дисках в extref:{handbook}disks/[Handbook, disks-encrypting].
====

[[rcconf-readonly]]
=== Я допустил ошибку в rc.conf или другом стартовом файле, и теперь не могу его отредактировать, потому что файловая система доступна только для чтения. Что мне делать?

Перезагрузите систему, используя `boot -s` в приглашении загрузчика, чтобы войти в однопользовательский режим. При запросе пути к оболочке нажмите kbd:[Enter] и выполните `mount -urw /`, чтобы перемонтировать корневую файловую систему в режиме чтения/записи. Также может потребоваться выполнить `mount -a -t ufs` для монтирования файловой системы, где находится ваш предпочитаемый редактор. Если этот редактор находится на сетевой файловой системе, либо настройте сеть вручную перед монтированием сетевых файловых систем, либо используйте редактор, расположенный на локальной файловой системе, например, man:ed[1].

Чтобы использовать полноэкранные редакторы, такие как man:vi[1] или man:emacs[1], выполните команду `export TERM=xterm`, чтобы эти редакторы могли загрузить корректные данные из базы man:termcap[5].

После выполнения этих действий отредактируйте файл [.filename]#/etc/rc.conf#, чтобы исправить синтаксическую ошибку. Сообщение об ошибке, отображаемое сразу после сообщений загрузки ядра, должно указывать номер строки в файле, в которой допущена ошибка.

[[free-memory-amount]]
=== Сколько свободной памяти доступно?

Существует несколько видов "свободной памяти". Наиболее распространенный - это объем памяти, который доступен немедленно, без освобождения уже используемой памяти. Это размер очереди свободных страниц плюс некоторые другие зарезервированные страницы. Этот объем отображается через `vm.stats.vm.v_free_count` man:sysctl[8] и, например, выводится man:top[1]. Другой вид "свободной памяти" - это общий объем виртуальной памяти, доступной пользовательским процессам, который зависит от суммы swap-пространства и используемой памяти. Возможны и другие определения "свободной памяти", но их описание относительно бесполезно; гораздо важнее следить за тем, чтобы частота подкачки оставалась низкой, и избегать исчерпания swap-пространства.

[[timezone]]
=== Мое время указано неверно, как я могу изменить часовой пояс?

Используйте man:tzsetup[8].

[[more-swap]]
=== FreeBSD использует много swap-пространства, даже когда в компьютере остаётся свободная память. Почему?

FreeBSD активно перемещает полностью неиспользуемые страницы основной памяти в своп, чтобы освободить больше основной памяти для активного использования. Такое активное использование свопа компенсируется за счет использования дополнительной свободной памяти для кэширования.

Обратите внимание, что хотя FreeBSD активно работает в этом направлении, она не принимает произвольных решений о выгрузке страниц, когда система действительно простаивает. Таким образом, система не будет полностью выгружена в своп после простоя в течение ночи.

[[top-freemem]]
=== Почему top показывает очень мало свободной памяти, даже когда у меня запущено очень мало программ?

Простой ответ заключается в том, что свободная память — это потраченная впустую память.

Любая память, которую программы не используют активно, применяется в ядре FreeBSD в качестве дискового кэша. Значения, отображаемые в man:top[1] с метками `Inact` и `Laundry`, представляют собой кэшированные данные на разных уровнях старения. Эти кэшированные данные позволяют системе не обращаться к медленному диску повторно для данных, к которым она недавно обращалась, тем самым повышая общую производительность. В целом, низкое значение памяти, отображаемое как `Free` в man:top[1], является хорошим признаком, при условии, что оно не _очень_ низкое.

[[daemon-name]]
=== Как зовут этого милого маленького красного человечка?

У него нет имени, и его просто называют "демон BSD". Если вам непременно нужно имя, называйте его "биести" (beastie). Обратите внимание, что "биести" произносится как "Би-Эс-Ди".

Дополнительная информация о демоне BSD доступна на его http://www.mckusick.com/beastie/index.html[домашней странице].

[[use-beastie]]
=== Могу ли я использовать изображение BSD-демона?

Возможно. Демон BSD защищен авторским правом Маршалла Кирка МакКузика. Ознакомьтесь с его http://www.mckusick.com/beastie/mainpage/copyright.html[Заявлением об использовании изображения демона BSD] для получения подробных условий использования.

В заключение, изображение можно использовать в хорошем вкусе, для личного пользования, при условии указания соответствующей авторской принадлежности. Перед коммерческим использованием логотипа свяжитесь с {mckusick} для получения разрешения. Подробнее можно узнать на http://www.mckusick.com/beastie/index.html[домашней странице BSD Daemon].

[[bikeshed-painting]]
=== Почему меня должен волновать цвет сарая для велосипедов?

Очень, очень краткий ответ — не должен. Более развёрнутый ответ: просто потому, что вы способны построить сарай для велосипедов, это не значит, что вы должны мешать другим делать то же самое лишь из-за того, что вам не нравится цвет, которым они собираются его покрасить. Это метафора, напоминающая, что не нужно спорить о каждой мелочи только потому, что у вас достаточно знаний для этого. Некоторые люди отмечали, что количество шума, вызванного изменением, обратно пропорционально сложности этого изменения.

Более длинный и полный ответ заключается в том, что после долгих споров о том, должна ли команда man:sleep[1] принимать аргументы в виде дробных секунд, {phk} опубликовал длинное сообщение под названием link:http://www.bikeshed.com[Велосипедный сарай (любого цвета) на более зелёной траве...].

[[acknowledgments]]
== Благодарности

Этот FAQ претерпел бесчисленные правки и улучшения благодаря разнообразной группе участников на протяжении последних десятилетий.
