=== Pantheon desktop on FreeBSD

Links: +
link:https://elementary.io/[elementary OS] URL: link:https://elementary.io/[] +
link:https://codeberg.org/olivierd/freebsd-ports-elementary[Development repository] URL: link:https://codeberg.org/olivierd/freebsd-ports-elementary[]

Contact: Olivier Duchateau <duchateau.olivier@gmail.com>

The Pantheon desktop environment is designed for elementary OS.
It builds on GNOME technologies (such as Mutter, GTK 3 and 4) and it is written in Vala.
The goal is to have a complete desktop environment for end users.

*13.2-RELEASE or higher is required*, because several core components depend on package:deskutils/xdg-desktop-portal[].

The repository contains a file called [.filename]#elementary.mk# for the [.filename]#Mk/Uses# framework, official applications, and curated ports which depend on package:x11-toolkits/granite7[].

I have submitted several patches in order to keep these ports up-to-date:

* package:deskutils/iconbrowser[]
* package:multimedia/elementary-videos[]
* package:x11-themes/gnome-icons-elementary[]
* package:editors/elementary-code[]

The link:https://bugs.freebsd.org/bugzilla/buglist.cgi?bug_status=__open__&query_format=advanced&short_desc=elementary-calendar%20elementary-terminal%20granite7&short_desc_type=anywordssubstr[bug reports] for updating the following ports are still open on bugzilla:

* package:x11-toolkits/granite7[]: Update to 7.3.0
* package:deskutils/elementary-calendar[]: Update to 7.0.0
* package:x11/elementary-terminal[]: Update to 6.1.2

In the same time, I have also worked on updating the GNOME stack (especially WebKitGTK, libwnck, Mutter, Vala).
I noticed several regressions particularly with package:x11/plank[] (it is related to monitoring open applications).

Three new applications have been added to the development repository:

* deskutils/atlas, a map viewer
* deskutils/nimbus, a weather applet
* audio/leopod, podcasts client
