=== Ports Collection

Links: +
link:https://www.FreeBSD.org/ports/[About FreeBSD Ports] URL:link:https://www.FreeBSD.org/ports/[] +
link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[Contributing to Ports] URL: link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[] +
link:http://portsmon.freebsd.org/[FreeBSD Ports Monitoring] URL: link:http://portsmon.freebsd.org/[] +
link:https://www.freebsd.org/portmgr/[Ports Management Team] URL: link:https://www.freebsd.org/portmgr/[] +
link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[Ports Tarball] URL: link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[]

Contact: René Ladan <portmgr-secretary@FreeBSD.org> +
Contact: FreeBSD Ports Management Team <portmgr@FreeBSD.org>

The Ports Management Team is responsible for overseeing the overall direction of the Ports Tree, building packages, and personnel matters.
Below is what happened in the last quarter.

* According to INDEX, there are currently 34,600 ports in the Ports Collection.
There are currently 3,000 open ports PRs of which some 730 are unassigned.
The last quarter saw 11,454 commits by 130 committers on the main branch and 828 commits by 37 committers on the 2023Q3 branch.
Compared to last quarter, this means a slight decrease in the number of unassigned PRs, a 10% increase in the number of commits on the main branch but also less backports to the quarterly branch.
The number of ports also grew a bit.

During Q3 we welcomed Joel Bodenmann (jbo@) as a new ports committer, granted a ports commit bit to mizhka@ who was already a src committer, and took the commit bits of knu@ and uqs@ in for safe-keeping after a year of inactivity.

Portgmr discussed and worked on the following things during Q3:

* Some progress has been made on sub-packages and a lightning talk was given by pizzamig@ at EuroBSDCon
* Overhauling some parts of the ports tree (LIB_DEPENDS, PREFIX, MANPREFIX, MANPATH)

Support for FreeBSD 13.1 was removed from the ports tree as it reached its end-of-life on August 1st.

The following happened on the infrastructure side:

* USES for ebur128 and guile were added
* Default versions for Mono, Perl, and PostgreSQL were updated to respectively 5.20, 5.34, and 15
* Default versions for ebur128, guile, and pycryptography were added at respectively "rust", 2.2, and "rust"
* Updates to major ports that happened were:

** pkg to 1.20.7
** chromium to 117.0.5938.132
** Firefox to 118.0.1
** KDE to 5.27.8
** Rust to 1.72.0
** Wine to 8.0.2

During the last quarter, pgkmgr@ ran 18 exp-runs to test various ports upgrades, updates to default versions of ports, and changes to pycryptography.
