=== Containers and FreeBSD: Pot, Potluck and Potman

Links: +
link:https://github.com/bsdpot[Pot organization on GitHub] URL: link:https://github.com/bsdpot[]

Contact: Luca Pizzamiglio (Pot) <pizzamig@FreeBSD.org> +
Contact: Bretton Vine (Potluck) <bv@honeyguide.eu> +
Contact: Michael Gmelin (Potman) <grembo@FreeBSD.org>

Pot is a jail management tool that link:https://www.freebsd.org/news/status/report-2020-01-2020-03/#pot-and-the-nomad-pot-driver[also supports orchestration through Nomad].

During this quarter, link:https://github.com/bsdpot/pot/pull/274[Pot 0.15.6] was finished, adding custom pf rule configuration hooks.

Additionally, a new release for the link:https://github.com/bsdpot/nomad-pot-driver[Nomad Pot Driver] that allows setting Pot attributes in Nomad job descriptions will very likely be available by the time you are reading this report.

Potluck aims to be to FreeBSD and Pot what Dockerhub is to Linux and Docker: a repository of Pot flavours and complete container images for usage with Pot and in many cases Nomad.

Quite a few new container images were made available, e.g. link:https://github.com/bsdpot/potluck/tree/master/caddy-s3-nomad[a Caddy S3 proxy], link:https://github.com/bsdpot/potluck/tree/master/mastodon-s3[a Mastodon instance] or a link:https://github.com/bsdpot/potluck/tree/master/redis-single[Redis container]. In total there are now 50 containers available that can either be downloaded as ready-made images at link:https://potluck.honeyguide.net/[the Potluck image registry] if you trust our build process or that you can rebuild yourself from the Pot flavour files stored in the link:https://github.com/bsdpot/potluck[Potluck Github repository].  

The July/August 2023 edition of the FreeBSD Journal contains Luca's link:https://freebsdfoundation.org/wp-content/uploads/2023/08/Pizzamiglio.pdf[Jail Orchestration with pot and nomad] article, explaining how to use Pot and Potluck together with Nomad to orchestrate containers on multiple hosts.

Last not least, link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273583[a patch] for the link:https://www.freshports.org/devel/sccache/[sccache port] was submitted to include sccache-dist and is about to be released at the time of this writing.

As always, feedback and patches are welcome.

Sponsors: Nikulipe UAB, Honeyguide Group
