=== Enabling Snapshots on Filesystems Using Journaled Soft Updates

Contact: Marshall Kirk McKusick <mckusick@FreeBSD.org>

This project has made UFS/FFS filesystem snapshots available when running with journaled soft updates.
The details of this project were link:https://www.freebsd.org/status/report-2022-10-2022-12/#_enabling_snapshots_on_filesystems_using_journaled_soft_updates[described in the 2022 fourth quarter report].

This project had two milestones:

The first milestone of this project was to make it possible to take snapshots when running with journaled soft updates and to use them for doing background dumps on a live filesystem.
Background dumps are requested by using the -L flag to man:dump[8].
This milestone was completed in Q4 of 2022 and was made available in the 13.2 release as link:https://www.freebsd.org/status/report-2023-01-2023-03/#_enabling_snapshots_on_filesystems_using_journaled_soft_updates_in_13_2[described in the 2023 first quarter report].

The second milestone of this project was to do a background check using a snapshot on a filesystem running with journaled soft updates.
This milestone was completed in the third quarter of 2023 in time to be included as part of the 14.0 release.
It was also made available in the 13.2-STABLE release.

Sponsored by: The FreeBSD Foundation
