# $FreeBSD$

DOC?= article

DOCFORMAT= html

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= 		article.sgml
CSS_SHEET=	itgastyle.css
IMAGES_EN=	tk0231-9-1.png

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
