#
# Build the Handbook with just the content from this chapter.
#
# The FreeBSD Documentation Project
# The FreeBSD French Documentation Project
#
# $FreeBSD$
# $Id: Makefile,v 1.1 2002-08-07 09:38:42 blackend Exp $
# Original revision: 1.1
#

CHAPTERS= 	l10n/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
