# $Id: Makefile,v 1.10 1997-07-01 03:52:20 max Exp $

DOCS?=		index.sgml
SUBDIR=		devel disklessx fonts mh multios newuser upgrade
DOCSUBDIR=	ddwg ppp

.if defined $(NEW_BUILD)
SUBDIR=
.endif

.include "../web.mk"
