#SUBDIR = corp-net-guide
#SUBDIR+= design-44bsd
#SUBDIR+= developers-handbook
SUBDIR+= faq
#SUBDIR+= fdp-primer
#SUBDIR+= handbook
#SUBDIR+= porters-handbook
#SUBDIR+= ppp-primer

#ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
