# $FreeBSD: www/en/releases/5.3R/Makefile,v 1.2 2004/08/05 19:57:06 scottl Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	todo.sgml schedule.sgml policy.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
