# $FreeBSD: www/en/releases/5.3R/Makefile,v 1.1 2003/11/07 07:31:43 rwatson Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	todo.sgml schedule.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
