# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: r46415

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=  index.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
