# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: r43646

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR =	dists

DOCS+=  howhelp.xml
DOCS+=  index.xml
DOCS+=  install.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
