#
#  The FreeBSD Documentation Project
#  The FreeBSD Hungarian Documentation Project
#
#  $FreeBSD$
#  %SOURCE%    en_US.ISO8859-1/books/Makefile
#  %SRCID%     1.14
#

SUBDIR = faq
SUBDIR+= fdp-primer
SUBDIR+= handbook

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"

