#
#  The FreeBSD Documentation Project
#  The FreeBSD Hungarian Documentation Project
#
#  $FreeBSD$
#  %SOURCE%    en_US.ISO8859-1/books/Makefile.inc
#  %SRCID%     1.4
#

DESTDIR?=	${DOCDIR}/hu_HU.ISO8859-2/books/${.CURDIR:T}

