#
#  The FreeBSD Documentation Project
#  The FreeBSD Hungarian Documentation Project
#
#  $FreeBSD$
#  Original Revision: 1.4
#

SUBDIR = handbook

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"

