# $FreeBSD$
#
# The FreeBSD Greek Documentation Project
# Makefile.inc for www/el directory (should be created) 
#
# %SOURCE%	mn/Makefile.inc
# %SRCID%	1.1
#

WEBBASE?=	/data/el
WEB_PREFIX?=	${.CURDIR}/../..
