# $FreeBSD: www/el/Makefile.inc,v 1.1 2008/02/10 09:40:20 keramida Exp $
#
# The FreeBSD Greek Documentation Project
#
# %SOURCE%	en/Makefile.inc
# %SRCID%	1.8
#

WEBBASE?=	/data/el
WEB_PREFIX?=	${.CURDIR}/../..
