---
title: Бүлэг 25. FreeBSD-г шинэчилж сайжруулах нь
part: хэсэг III. Системийн Удирдлага
prev: books/handbook/l10n
next: books/handbook/dtrace
---

[[updating-upgrading]]
= FreeBSD-г шинэчилж сайжруулах нь
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Гарчиг
:table-caption: Хүснэгт
:figure-caption: Зураг
:example-caption: Жишээ
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 25

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/cutting-edge/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/cutting-edge/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/cutting-edge/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/mn/mailing-lists.adoc[]
include::shared/mn/teams.adoc[]
include::shared/mn/urls.adoc[]

toc::[]

[[updating-upgrading-synopsis]]
== Ерөнхий агуулга

FreeBSD нь өөрийн хувилбаруудын хооронд байнгын хөгжүүлэлтийн доор оршин тогтнож байдаг. Зарим хүмүүс албан ёсоор гаргасан хувилбаруудыг ашиглах хүсэлтэй байдаг бол зарим хүмүүс хамгийн сүүлийн үеийн хөгжүүлэлтийг дагах сонирхолтой байдаг. Гэхдээ албан ёсны хувилбарууд хүртэл аюулгүй байдлын болоод бусад чухал засваруудаар шинэчлэгдэж байдаг. Ямар хувилбар ашиглаж байгаагаас үл хамаараад FreeBSD нь таны системийг шинэ байлгахад шаардлагатай бүх л хэрэгслүүд болон хувилбар хооронд хялбараар шинэчлэх боломжоор хангадаг. Энэхүү бүлэг нь хөгжүүлэлтийн системийг дагахыг хүсэх эсвэл гаргасан хувилбартай үлдэх эсэхийг шийдэхэд танд туслах болно. Таны системийг шинэчлэхэд зориулсан үндсэн хэрэгслүүдийг бас харуулах болно.

Энэ бүлгийг уншсаны дараа, та дараах зүйлсийг мэдэх болно:

* Систем болон портын цуглуулгыг ямар хэрэгслүүд ашиглан шинэчилж болох талаар.
* freebsd-update, Subversion, CVSup, CVS, эсвэл CTM програмуудын тусламжтай өөрийн системийг хэрхэн хамгийн сүүлийн хэлбэрт авчрах талаар.
* Суулгагдсан системийн төлвийг мэдэгдэж байгаа сайн хуулбартай хэрхэн харьцуулах талаар.
* Subversion эсвэл баримтжуулах порт ашиглан өөрийн баримтуудыг хэрхэн сүүлийн хувилбарт байлгаж байх талаар.
* FreeBSD-STABLE болон FreeBSD-CURRENT хөгжүүлэлтийн салбаруудын ялгаа.
* Бүх үндсэн системийг `make buildworld` (гэх мэт) ашиглан хэрхэн дахин бүтээж суулгах талаар.

Энэ бүлгийг уншихаасаа өмнө, та дараах зүйлсийг мэдэх шаардлагатай:

* Өөрийн сүлжээний холболтыг зөв тохируулах (crossref:advanced-networking[advanced-networking,Сүлжээний нэмэлт ойлголтууд]).
* Нэмэлт гуравдагч програм хангамжуудыг хэрхэн суулгахыг мэдэх (crossref:ports[ports,Програм суулгах. Багцууд болон портууд]).

[NOTE]
====
Энэ бүлэгт FreeBSD-ийн эхийг авч шинэчлэхийн тулд `svn` тушаалыг ашиглагдсан. Үүнийг хэрэглэхийн тулд package:devel/subversion[] гэсэн порт буюу багцыг та суулгах хэрэгтэй.
====

[[updating-upgrading-freebsdupdate]]
== FreeBSD-ийн шинэчлэлт

Аюулгүй байдлын засваруудыг хийнэ гэдэг компьютерийн програм хангамж ялангуяа үйлдлийн системийг арчлалтын чухал хэсгийн нэг юм. Удаан хугацааны туршид FreeBSD дээр энэ процесс хялбар биш байлаа. Засваруудыг эх код руу хийж кодыг хоёртын хэлбэр рүү дахин бүтээж дараа нь хоёртын файлуудыг дахин суулгах шаардлагатай байлаа.

Энэ нь одоо тийм биш болсон бөгөөд FreeBSD нь `freebsd-update` гэгддэг хэрэгслийг агуулдаг. Энэ хэрэгсэл нь хоёр тусдаа функцээр хангадаг. Нэгдүгээрт энэ нь бүтээлт болон суулгах шаардлагагүйгээр хоёртын аюулгүй байдал болон алдааны шинэчлэлтүүдийг FreeBSD-ийн үндсэн системд оруулах боломжийг олгодог. Хоёрдугаарт уг хэрэгсэл бага болон том хувилбарын шинэчлэлтүүдийг дэмждэг.

[NOTE]
====
Аюулгүй байдлын багаар дэмжигдсэн бүх архитектур болон хувилбаруудын хувьд хоёртын шинэчлэлтүүд байдаг. Шинэ хувилбар руу шинэчлэхээс өмнө хүссэн хувилбарт чинь хамаатай чухал мэдээлэл байж болох учир одоогийн хувилбарын зарлалуудыг дахин үзэх хэрэгтэй. Тэдгээр зарлалуудыг дараах холбоосоос үзэж болно: http://www.FreeBSD.org/releases/[http://www.FreeBSD.org/releases/].
====

Хэрэв `crontab` нь `freebsd-update`-ийн боломжуудыг хэрэглэж байвал дараах үйлдлийг эхлэхээс өмнө түүнийг болиулах хэрэгтэй.

[[freebsdupdate-config-file]]
=== Тохиргооны файл

Процессийг илүү хянах боломжтой болгож зарим хэрэглэгчид [.filename]#/etc/freebsd-update.conf# анхны тохиргооны файлыг өөрчлөхийг хүсэж болох юм. Тохиргоонууд нь маш сайн баримтжуулагдсан байдаг боловч дараах хэдэн зүйлийг арай илүү тайлбарлах шаардлагатай байж болох юм:

[.programlisting]
....
# Components of the base system which should be kept updated.
Components src world kernel
....

Энэ өгөгдөл нь FreeBSD-ийн аль хэсгийг шинэчлэхийг хянадаг. Анхдагчаар эх код, үндсэн систем бүтнээрээ ба цөмийг шинэчлэх байдаг. Бүрэлдэхүүн хэсгүүд нь суулгах явцад байдагтай адил байдаг бөгөөд жишээ нь `world/games` гэдгийг энд нэмэхэд тоглоомын засваруудыг хийх боломжийг олгоно. `src/bin` гэдгийг ашиглах нь [.filename]#src/bin# дахь эх кодыг шинэчлэх боломжийг олгодог.

Хамгийн сайн тохиргоо бол үүнийг анхдагчаар нь үлдээх бөгөөд тусгай зүйлс оруулж үүнийг өөрчилснөөр хэрэглэгчид өөрсдийн шинэчлэхийг хүссэн зүйл болгоноо жагсааж оруулах шаардлагатай болно. Ингэснээр эх код болон хоёртын файлуудын хоорондох уялдаа алдагдаж гамшигт үр дагаварт хүргэж болно.

[.programlisting]
....
# Paths which start with anything matching an entry in an IgnorePaths
# statement will be ignored.
IgnorePaths
....

[.filename]#/bin# эсвэл [.filename]#/sbin# зэрэг замуудыг нэмж эдгээр тусгай сангуудыг шинэчлэх процессийн явцад оролдохгүй орхиж болно. Энэ тохиргоо нь `freebsd-update` локал өөрчлөлтүүдийг дарж бичихээс хамгаалахад хэрэглэж болно.

[.programlisting]
....
# Paths which start with anything matching an entry in an UpdateIfUnmodified
# statement will only be updated if the contents of the file have not been
# modified by the user (unless changes are merged; see below).
UpdateIfUnmodified /etc/ /var/ /root/ /.cshrc /.profile
....

Заагдсан сангууд дахь тохиргооны файлууд өөрчлөгдөөгүй тохиолдолд шинэчилнэ. Хэрэглэгчийн хийсэн өөрчлөлтүүд эдгээр файлуудын автомат шинэчлэлтийг хүчингүй болгоно. `freebsd-update`-г нийлүүлэх явцад өөрчлөлтүүдийг хадгалахыг тушаах `KeepModifiedMetadata` гэсэн өөр нэг тохиргоо байдаг.

[.programlisting]
....
# When upgrading to a new FreeBSD release, files which match MergeChanges
# will have any local changes merged into the version from the new release.
MergeChanges /etc/ /var/named/etc/
....

`freebsd-update`-ийн нийлүүлэхийг оролдох тохиргооны файлуудтай сангуудын жагсаалт. Файл нийлүүлэх процесс нь цөөн тохиргоотой man:mergemaster[8]-тай төстэй man:diff[1] засварууд бөгөөд нийлүүлэлтийг эсвэл хүлээн авах юм уу эсвэл засварлагч нээж эсвэл `freebsd-update` ажиллагаагаа зогсоох болно. Эргэлзэж байвал [.filename]#/etc# санг нөөцөлж аваад нийлүүлэлтүүдийг хүлээн авах хэрэгтэй. `mergemaster` тушаалын талаар дэлгэрэнгүй мэдээллийг <<mergemaster>>-с үзнэ үү.

[.programlisting]
....
# Directory in which to store downloaded updates and temporary
# files used by FreeBSD Update.
# WorkDir /var/db/freebsd-update
....

Энэ сан нь бүх засварууд болон түр зуурын файлууд байх сан юм. Хэрэглэгч хувилбар шинэчлэлт хийж байвал энэ байрлал нь хамгийн багаар бодоход гигабайт дискийн зайтай байх шаардлагатай.

[.programlisting]
....
# When upgrading between releases, should the list of Components be
# read strictly (StrictComponents yes) or merely as a list of components
# which *might* be installed of which FreeBSD Update should figure out
# which actually are installed and upgrade those (StrictComponents no)?
# StrictComponents no
....

`yes` гэж тохируулсан үед `freebsd-update` нь `Components` буюу бүрэлдэхүүн хэсгүүдийн жагсаалт бүрэн гэж тооцох бөгөөд жагсаалтаас гадна өөрчлөлт хийхийг оролдохгүй. `freebsd-update` нь `Components`-ийн жагсаалтад хамаарах файл бүрийг шинэчлэхийг оролдох болно.

[[freebsdupdate-security-patches]]
=== Аюулгүй байдлын засварууд

Аюулгүй байдлын засварууд нь алсын машин дээр хадгалагддаг бөгөөд дараах тушаал ашиглан татан авч суулгаж болно:

[source,bash]
....
# freebsd-update fetch
# freebsd-update install
....

Хэрэв цөмийн ямар нэг засвар хийгдсэн бол системийг дахин ачаалах хэрэгтэй. Хэрэв бүгд зөв явагдсан бол систем нь засвар хийгдсэн байх ёстой бөгөөд `freebsd-update`-ийг man:cron[8] ажлаас шөнө бүр ажиллуулж болно. Энэ ажлыг хийхэд дараах мөрийг [.filename]#/etc/crontab#-д хийхэд хангалттай байх болно:

[.programlisting]
....
@daily                                  root    freebsd-update cron
....

Энэ мөр нь өдөр бүр `freebsd-update` хэрэгслийг ажиллуулахыг зааж байна. Ийм аргаар `cron`-ий нэмэлт өгөгдлийг ашиглан `freebsd-update` нь зөвхөн шинэчлэлт байгаа эсэхийг шалгах болно. Хэрэв засварууд байвал тэдгээрийг автоматаар диск рүү татаж авах бөгөөд гэхдээ засваруудыг хийхгүй. `root` хэрэглэгч рүү захиа илгээгдэх бөгөөд дараа нь тэд гараар суулгаж болох юм.

Хэрэв ямар нэг зүйл буруу болбол `freebsd-update` нь дараах тушаалаар сүүлийн өөрчлөлтүүдийг буцаах чадвартай байдаг:

[source,bash]
....
# freebsd-update rollback
....

Дууссаны дараа цөм эсвэл цөмийн модулиуд өөрчлөгдсөн бол системийг дахин эхлүүлэх хэрэгтэй. Энэ нь шинэ хоёртын файлуудыг санах ой руу дуудах боломжийг FreeBSD-д олгоно.

`freebsd-update` хэрэгсэл нь автоматаар зөвхөн [.filename]#GENERIC# цөмийг шинэчилж чаддаг. Хэрэв өөрчлөн тохируулсан цөм ашиглагдаж байвал `freebsd-update` нь шинэчлэлтийг хийж дууссаны дараа цөмийг дахин бүтээж суулгах шаардлагатай. Гэхдээ `freebsd-update` нь [.filename]#/boot/GENERIC# (хэрэв байгаа бол) дахь [.filename]#GENERIC# цөмийг системийн тухайн үеийн (ажиллаж байгаа) цөм биш байсан ч гэсэн олж шинэчилдэг.

[NOTE]
====
[.filename]#/boot/GENERIC# дахь [.filename]#GENERIC# цөмийн хуулбарыг үргэлж хадгалах нь ер нь зүйтэй байдаг. Энэ нь төрөл бүрийн асуудлуудыг шинжлэх болон <<freebsdupdate-upgrade>>-т тайлбарласны дагуу `freebsd-update`-г ашиглан хувилбар шинэчлэлтийг хийхэд ач тустай байх болно.
====

[.filename]#/etc/freebsd-update.conf# дахь анхдагч тохиргоо өөрчлөгдөөгүй л бол `freebsd-update` шинэчлэгдсэн цөмийн эхийг бусад шинэчлэлттэй цуг суулгах болно. Дараа нь өөрийн өөрчлөн тохируулсан цөмийг дахин бүтээж суулгахдаа энгийн сурсан аргаараа хийж болно.

[NOTE]
====
`freebsd-update`-аар түгээгдсэн шинэчлэлтүүд нь цөмтэй үргэлж холбоотой байдаггүй. `freebsd-update install` тушаалаар цөмийн эх өөрчлөгдөөгүй бол өөрийн өөрчлөн тохируулсан цөмийг дахин бүтээх шаардлагагүй юм. Гэхдээ `freebsd-update` тушаал [.filename]#/usr/src/sys/conf/newvers.sh# файлыг үргэлж шинэчлэх болно. Тухайн үеийн нөхөөсийн түвшинг (`uname -r` тушаалаас гарсан `-p` дугаараар заагдсан) энэ файлаас авдаг. Өөр бусад юмс өөрчлөгдөөгүй байсан ч гэсэн өөрийн өөрчлөн тохируулсан цөмийг дахин бүтээх нь системийн тухайн үеийн нөхөөсийн түвшинг зөв гаргах боломжийг man:uname[1]-д олгоно. Энэ нь олон системийг арчилж байгаа үед ялангуяа ач тустай байдаг бөгөөд ингэснээр тэр системүүд дээр суулгагдсан шинэчлэлтүүдэд түргэн шуурхай үнэлгээ өгөх боломжийг олгодог.
====

[[freebsdupdate-upgrade]]
=== Major ба Minor буюу Том ба Бага шинэчлэлтүүд

Энэ процесс нь ихэнх гуравдагч талын прорамуудыг эвдэх хуучин обьект файлууд болон сангуудыг устгах болно. Бүх суулгагдсан портуудыг устгаж дахин суулгах эсвэл package:ports-mgmt/portupgrade[] хэрэгсэл ашиглан сүүлд нь шинэчлэхийг зөвлөдөг. Дараах тушаалыг ашиглан ихэнх хэрэглэгчид тест бүтээлтийг ажиллуулахыг хүснэ:

[source,bash]
....
# portupgrade -af
....

Энэ нь бүгдийг зөв дахин суулгах баталгаа болох юм. `BATCH` орчны хувьсагчийг `yes` гэж тохируулснаар энэ процессийн явцад гарч ирэх хүлээх мөрөнд `yes` гэж хариулан бүтээх процессийн үед оролцох шаардлагыг үгүй болгоно.

Хэрэв өөрчлөн тохируулсан цөм ашиглагдаж байгаа бол шинэчлэх процесс арай илүү ажиллагаатай. [.filename]#GENERIC# цөмийн хуулбар шаардлагатай бөгөөд [.filename]#/boot/GENERIC#-д байрлуулах шаардлагатай. Хэрэв [.filename]#GENERIC# цөм системд байхгүй бол үүнийг доор дурдсан аргуудын аль нэгийг ашиглан олж авч болно:

* Хэрэв өөрчлөн тохируулсан цөм зөвхөн нэг удаа бүтээгдсэн бол [.filename]#/boot/kernel.old# дахь цөм нь [.filename]#GENERIC# цөм юм. Энэ санг [.filename]#/boot/GENERIC# гэж өөрчлөхөд л болно.
* Машинд физикээр хандах боломжтой гэж тооцвол [.filename]#GENERIC# цөмийн хуулбарыг CD-ROM зөөвөрлөгчөөс суулгаж болно. Өөрийн суулгац дискийг хийж дараах тушаалуудыг ашиглана:
+
[source,bash]
....
# mount /cdrom
# cd /cdrom/X.Y-RELEASE/kernels
# ./install.sh GENERIC
....
+ 
[.filename]#X.Y-RELEASE#-г өөрийн ашиглаж байгаа хувилбараар солих хэрэгтэй. [.filename]#GENERIC# цөм анхдагчаар [.filename]#/boot/GENERIC#-д суулгагдах болно.
* Дээр дурдсан бүгдийг хийх боломжгүй бол [.filename]#GENERIC# цөмийг эхээс нь дахин бүтээж суулгаж болох юм:
+
[source,bash]
....
# cd /usr/src
# env DESTDIR=/boot/GENERIC make kernel
# mv /boot/GENERIC/boot/kernel/* /boot/GENERIC
# rm -rf /boot/GENERIC/boot
....
+ 
Энэ цөмийг `freebsd-update` хэрэгсэлд [.filename]#GENERIC# гэж харуулахын тулд [.filename]#GENERIC# тохиргооны файлыг ямар ч тохиолдолд өөрчилсөн байх ёсгүй. Бас ямар нэг тусгай сонголтуудгүйгээр (аль болох хоосон [.filename]#/etc/make.conf# файлтайгаар) бүтээгдсэн байх ёстойг зөвлөдөг.

Энэ үед [.filename]#GENERIC# цөм рүү дахин ачаалах шаардлагагүй юм.

Том ба бага хувилбарын шинэчлэлтүүдийг `freebsd-update` тушаалд хувилбарын дугаарыг өгч гүйцэтгэж болно, жишээ нь дараах тушаал FreeBSD 8.1 руу шинэчилнэ:

[source,bash]
....
# freebsd-update -r 8.1-RELEASE upgrade
....

Тушаал хүлээн авсны дараа `freebsd-update` системийг шинэчлэхэд шаардлагатай мэдээллийг цуглуулахын тулд тохиргооны файл болон одоогийн системийг шалгана. Ямар бүрэлдэхүүн хэсгүүд илрүүлэгдсэн болон ямар бүрэлдэхүүн хэсгүүд илрүүлэгдээгүй гэдгийг дэлгэц дээр үзүүлнэ. Жишээ нь:

[source,bash]
....
Looking up update.FreeBSD.org mirrors... 1 mirrors found.
Fetching metadata signature for 8.1-RELEASE from update1.FreeBSD.org... done.
Fetching metadata index... done.
Inspecting system... done.

The following components of FreeBSD seem to be installed:
kernel/smp src/base src/bin src/contrib src/crypto src/etc src/games
src/gnu src/include src/krb5 src/lib src/libexec src/release src/rescue
src/sbin src/secure src/share src/sys src/tools src/ubin src/usbin
world/base world/info world/lib32 world/manpages

The following components of FreeBSD do not seem to be installed:
kernel/generic world/catpages world/dict world/doc world/games
world/proflibs

Does this look reasonable (y/n)? y
....

Энд хүрэхэд `freebsd-update` шинэчлэлтэд шаардлагатай бүх файлуудыг татан авахаар оролдох болно. Зарим тохиолдолд хэрэглэгчээс юу суулгах эсвэл хэрхэн цааш үргэлжлүүлэх талаар асуултууд асууж болох юм.

Өөрчлөн тохируулсан цөмийг ашиглаж байх үед дээрх алхам дараахтай төстэй анхааруулгыг харуулах болно:

[source,bash]
....
WARNING: This system is running a "MYKERNEL" kernel, which is not a
kernel configuration distributed as part of FreeBSD 8.0-RELEASE.
This kernel will not be updated: you MUST update the kernel manually
before running "/usr/sbin/freebsd-update install"
....

Энэ анхааруулгыг энэ үед орхигдуулахад аюулгүй байдаг. Шинэчлэгдсэн [.filename]#GENERIC# цөм шинэчлэлтийн явцад завсрын алхам болон ашиглагдах болно.

Бүх засварууд локал систем рүү татагдсаны дараа тэдгээрийг хийж өгөх болно. Машины хурд болон ачааллаас хамаарч энэ процесс нь хугацаа шаардаж болох юм. Тохиргооны файлуудыг нийлүүлэх болно. Файл нийлүүлэгдэх юм уу эсвэл гараар нийлүүлэхэд зориулж засварлагч дэлгэц дээр гарч ирч болох учир процессийн энэ хэсэг хэрэглэгчийн оролцоо шаардана. Амжилттай нийлүүлэлт болгоны үр дүн хэрэглэгчид харуулагдаж процесс үргэлжлэх болно. Амжилтгүй болсон эсвэл орхигдсон нийлүүлэлт нь процессийг зогсоох болно. Хэрэглэгчид нь [.filename]#/etc# сангийн нөөцийг хийж [.filename]#master.passwd# эсвэл [.filename]#group# зэрэг чухал файлуудыг гараар сүүлд нь нийлүүлэхийг хүсэж болох юм.

[NOTE]
====
Систем нь өөрчлөгдөөгүй байгаа бөгөөд бүх засвар оруулалт болон нийлүүлэлт өөр сан дотор болж байгаа болно. Бүх засварууд амжилттай хийгдэж бүх тохиргооны файлууд нийлүүлэгдэж процесс тэгш явагдаж байгаа мэт санагдвал хэрэглэгч өөрчлөлтүүдийг хийх хэрэгтэй.
====

Энэ процесс дууссаны дараа шинэчлэлтийг дараах тушаалыг ашиглан диск рүү хийж болно.

[source,bash]
....
# freebsd-update install
....

Цөм болон цөмийн модулиудад эхлээд засвар хийнэ. Энэ үед машиныг дахих ачаалах ёстой. Хэрэв систем өөрчлөн тохируулсан цөмөөр ажиллаж байгаа бол цөмийг [.filename]#/boot/GENERIC# (шинэчлэгдсэн) цөмөөр дараа нь ачаалахаар болгохын тулд man:nextboot[8]-ийг ашиглана:

[source,bash]
....
# nextboot -k GENERIC
....

[WARNING]
====

[.filename]#GENERIC# цөмөөр ачаалахаас өмнө (хэрэв шинэчлэгдэж байгаа машинд алсаас хандаж байгаа бол сүлжээнд холбогдон) таны систем зөв ачаалахын тулд шаардлагатай бүх драйверуудыг агуулсан эсэхийг шалгах хэрэгтэй. Ялангуяа хэрэв өмнө нь ажиллаж байсан өөрчлөн тохируулсан цөм ерөнхийдөө цөмийн модулиудаар хангагдаж байдаг ажиллагааг өөртөө агуулсан бол [.filename]#/boot/loader.conf# боломжийг ашиглан эдгээр модулиудыг [.filename]#GENERIC# цөмд түр зуур ачаалахаа мартуузай. Шинэчлэх процесс бүрэн дуустал шаардлагагүй үйлчилгээнүүд, диск болон сүлжээний холболтууд гэх мэтийг та бас хааж өгч болох юм.
====

Одоо машин шинэчлэгдсэн цөмөөр ачаалагдах ёстой:

[source,bash]
....
# shutdown -r now
....

Систем буцаж ассаны дараа `freebsd-update`-г дахин эхлүүлэх хэрэгтэй. Процессийн төлөв хадгалагдсан болохоор `freebsd-update` эхнээсээ эхлэхгүй бөгөөд бүх хуучин хуваалцсан сангууд болон обьект файлуудыг устгах болно. Энэ шатыг үргэлжлүүлэхийн тулд дараах тушаалыг ажиллуулна:

[source,bash]
....
# freebsd-update install
....

[NOTE]
====
Сангуудын хувилбарын тоо дээшилсэн эсэхээс хамаарч суулгах гурван шатны оронд хоёр шат байж болох юм.
====

Бүх гуравдагч талын програм хангамжийг дахин бүтээж дахин суулгах хэрэгтэй. Суулгагдсан програм хангамж нь шинэчлэлтийн процессийн явцад устгагдсан сангуудаас хамаарч болох учраас энэ нь шаардлагатай юм. package:ports-mgmt/portupgrade[] тушаалыг үүнийг автоматжуулахад ашиглаж болох юм. Энэ процессийг эхлүүлэхийн тулд дараах тушаалыг хэрэглэж болно:

[source,bash]
....
# portupgrade -f ruby
# rm /var/db/pkg/pkgdb.db
# portupgrade -f ruby18-bdb
# rm /var/db/pkg/pkgdb.db /usr/ports/INDEX-*.db
# portupgrade -af
....

Үүнийг дууссаны дараа шинэчлэлтийн процессийг `freebsd-update`-ийг сүүлийн удаа дуудаж төгсгөнө. Шинэчлэлтийн процессийн сул байгаа бүх зүйлсийг гүйцээхийн тулд дараах тушаалыг ажиллуулна:

[source,bash]
....
# freebsd-update install
....

Хэрэв [.filename]#GENERIC# цөм түр зуур ашиглагдаж байсан бол өөрчлөн тохируулсан шинэ цөмийг ердийн хэвшсэн аргаар одоо бүтээж суулгах цаг болжээ.

Машинаа FreeBSD-ийн шинэ хувилбар руу дахин ачаалах хэрэгтэй. Процесс дууслаа.

[[freebsdupdate-system-comparison]]
=== Системийн төлвийн харьцуулалт

`freebsd-update` хэрэгслийг FreeBSD-ийн суулгагдсан хувилбарын төлвийг байгаа зөв хуулбарын эсрэг тест хийхэд хэрэглэж болно. Энэ сонголт нь системийн хэрэгслүүд сангууд болон тохиргооны файлуудын одоогийн хувилбаруудыг шалгадаг. Харьцуулалтыг эхлүүлэхийн тулд дараах тушаалыг ажиллуулна:

[source,bash]
....
# freebsd-update IDS >> outfile.ids
....

[WARNING]
====

Тушаалын нэр IDS боловч энэ нь ямар ч тохиолдолд package:security/snort[] зэрэг халдлага илрүүлэгч системийг солих зориулалттай биш юм. `freebsd-update` нь өгөгдлийг диск дээр хадгалдаг бөгөөд түүнийг өөрчлөх боломж тодорхой юм. `kern.securelevel` тохиргоог ашиглах болон `freebsd-update`-ийн өгөгдлийг зөвхөн уншигдах файлын систем дээр ашиглагдаагүй тохиолдолд хадгалах нь энэ боломжийг багасгах боловч илүү сайн шийдэл нь системийг DVD эсвэл нууцлаг хадгалсан гадаад USB дискийн төхөөрөмж зэрэг нууцлаг дисктэй харьцуулах явдал юм.
====

Систем нь одоо шалгагдах бөгөөд файлууд нь өөрсдийн man:sha256[1] утгуудын хамт, хувилбар дахь мэдэгдэж байгаа сайн утгууд болон одоо суугдсан байгаа утгуудын хамт хэвлэгдэн харуулагдана. Энэ нь яагаад гаралт [.filename]#outfile.ids# файл руу илгээгдсэн шалтгаан юм. Үүнийг нүдээр шалгахад хэтэрхий хурдан дээш гүйж удалгүй консолын буфферийг дүүргэх болно.

Эдгээр мөрүүд нь бас хэтэрхий урт боловч гаралтын хэлбэрийг хялбараар задлан ялгаж болно. Жишээ нь хувилбарт байгаагаас ондоо бүх файлуудын жагсаалтыг авахын тулд дараах тушаалыг ажиллуулна:

[source,bash]
....
# cat outfile.ids | awk '{ print $1 }' | more
/etc/master.passwd
/etc/motd
/etc/passwd
/etc/pf.conf
....

Энэ гаралт нь тайрагдсан бөгөөд олон файл байгаа болно. Эдгээр файлуудын зарим нь төрөлхийн өөрчлөлтүүдтэй байна, жишээ нь [.filename]#/etc/passwd# нь хэрэглэгч системд нэмэгдсэн болохоор өөрчлөгдсөн байна. Зарим тохиолдолд `freebsd-update` нь шинэчилсэн байж болзошгүй учир цөмийн модулиуд зэрэг бусад файлууд өөр байж болох юм. Тусгай файлууд болон сангуудыг хасахын тулд тэдгээрийг [.filename]#/etc/freebsd-update.conf# файлын `IDSIgnorePaths` тохиргоонд нэмж өгнө.

Өмнө хэлэлцсэн хувилбараас гадна нарийн нягт шинэчлэлтийн аргын хэсэг болгон энэ системийг ашиглаж болно.

[[updating-upgrading-portsnap]]
== Portsnap: Портын цуглуулгыг шинэчлэх хэрэгсэл

FreeBSD-ийн үндсэн систем портын цуглуулгыг бас шинэчилдэг man:portsnap[8] хэрэгслийг агуулдаг. Ажиллуулсны дараа энэ нь алсын сайт руу холбогдож нууц түлхүүрийг шалгаж портын цуглуулгын шинэ хуулбарыг татан авдаг. Түлхүүр нь бүх татаж авсан файлууд татагдаж байхдаа өөрчлөгдөөгүй эсэхийг хянан бүрэн бүтэн байдлыг шалгахад ашиглагддаг. Хамгийн сүүлийн үеийн портын цуглуулгыг татаж авахын тулд дараах тушаалыг ажиллуулна:

[source,bash]
....
# portsnap fetch
Looking up portsnap.FreeBSD.org mirrors... 9 mirrors found.
Fetching snapshot tag from geodns-1.portsnap.FreeBSD.org... done.
Fetching snapshot metadata... done.
Updating from Tue May 22 02:12:15 CEST 2012 to Wed May 23 16:28:31 CEST 2012.
Fetching 3 metadata patches.. done.
Applying metadata patches... done.
Fetching 3 metadata files... done.
Fetching 90 patches.....10....20....30....40....50....60....70....80....90. done.
Applying patches... done.
Fetching 133 new ports or files... done.
....

Энэ жишээ нь юу үзүүлж байна вэ гэхээр man:portsnap[8] одоо байгаа портын өгөгдөлд хэд хэдэн засварууд байгааг олж шалгаж байна. Энэ нь бас уг хэрэгсэл өмнө нь ажилласныг харуулж байгаа бөгөөд хэрэв эхний удаа ажилласан бол цуглуулга татагдан авагдах байсан юм.

man:portsnap[8] нь `fetch` үйлдлийг хийж дууссаны дараа локал систем дээр байгаа портын цуглуулга болон дараа дараагийн засваруудыг шалгалтад дамжуулна. `portsnap`-ийг эхний удаа ажиллуулахдаа `extract`-г ашиглан татан авсан файлуудыг суулгаж болно:

[source,bash]
....
# portsnap extract
/usr/ports/.cvsignore
/usr/ports/CHANGES
/usr/ports/COPYRIGHT
/usr/ports/GIDs
/usr/ports/KNOBS
/usr/ports/LEGAL
/usr/ports/MOVED
/usr/ports/Makefile
/usr/ports/Mk/bsd.apache.mk
/usr/ports/Mk/bsd.autotools.mk
/usr/ports/Mk/bsd.cmake.mk
...
....

Аль хэдийн суулгасан портын цуглуулгыг шинэчлэхдээ `portsnap update` тушаалыг ашиглах ёстой:

[source,bash]
....
# portsnap update
....

Процесс одоо дууссан бөгөөд портын цуглуулыг ашиглан програмуудыг суулгаж эсвэл шинэчилж болно.

`fetch` болон `extract` эсвэл `update` үйлдлүүдийг доор харуулсан шиг дараалуулан ажиллуулж болно:

[source,bash]
....
# portsnap fetch update
....

Энэ тушаал нь портын цуглуулгын сүүлийн хувилбарыг татан авч таны машин дээр байгаа локал хувилбарыг [.filename]#/usr/ports# санд шинэчилдэг.

[[updating-upgrading-documentation]]
== Баримтын цуглуулгыг шинэчлэх нь

Үндсэн систем болон портын цуглуулгаас гадна баримтууд нь FreeBSD үйлдлийн системийн салшгүй хэсэг юм. Хэдийгээр FreeBSD-ийн хамгийн сүүлийн үеийн баримтын цуглуулга http://www.freebsd.org/doc/[FreeBSD вэб сайт] дээр үргэлж байдаг боловч зарим хэрэглэгчид удаан сүлжээний холболттой эсвэл бүр тогтмол сүлжээний холболтгүй байж болох юм. Азаар FreeBSD-ийн хамгийн сүүлийн үеийн баримтын цуглуулгын локал хуулбарыг арчлан хувилбар бүртэй цуг ирдэг баримтыг шинэчлэх хэд хэдэн арга байдаг.

[[dsvn-doc]]
=== Баримтыг шинэчлэхийн тулд Subversion-г ашиглах нь

FreeBSD-ийн баримтуудын эхийг Subversion ашиглан авч болно. Энэ хэсэг дараах зүйлсийг тайлбарладаг:

* FreeBSD-ийн баримтуудыг эхээс нь бүтээхэд шаардлагатай хэрэгслүүд, баримтын хэрэгслүүдийг хэрхэн суулгах талаар.
* Subversion ашиглан [.filename]#/usr/doc# дахь баримтын эхийн хуулбарыг хэрхэн татаж авах талаар.
* FreeBSD-ийн баримтыг эхээс нь хэрхэн бүтээж [.filename]#/usr/shared/doc# дотор суулгах талаар.
* Баримтыг бүтээх системийн дэмждэг бүтээлтийн зарим тохируулгууд, өөрөөр хэлбэл баримтын зарим нэг хэл дээрх орчуулгыг зөвхөн бүтээдэг тохируулгууд эсвэл тусгай гаралтын хэлбэржүүлэлтийг сонгодог тохируулгууд.

[[installing-documentation-toolchain]]
=== Subversion болон баримтын хэрэгслүүдийг суулгах нь

FreeBSD-ийн баримтыг эхээс нь бүтээхэд нэлээн олон тооны хэрэгслүүдийг шаарддаг. Эдгээр хэрэгслүүд нь FreeBSD-ийн үндсэн системийн хэсэг биш байдаг. Учир нь эдгээр нь ихээхэн хэмжээний дискийн зай шаарддаг бөгөөд FreeBSD-ийн бүх хэрэглэгчдэд хэрэгтэй байдаггүй. Тэдгээр нь FreeBSD-д зориулж шинэ баримтууд идэвхтэй бичдэг эсвэл өөрсдийн баримтыг эхээс нь байнга шинэчилдэг хэрэглэгчдэд зөвхөн хэрэгтэй байдаг.

Бүх шаардлагатай хэрэгслүүд портын цуглуулгад байдаг. Эдгээр хэрэгслүүдийн эхний суулгалт болон хожмын шинэчлэлтүүдийг хялбаршуулах package:textproc/docproj[] порт нь FreeBSD-ийг баримтжуулах төслөөс хөгжүүлсэн мастер порт юм.

[NOTE]
====
PostScript(R) эсвэл PDF баримт шаардлагагүй үед харин package:textproc/docproj-nojadetex[] портыг суулгаж болох юм. Баримтын хэрэгслийн энэ хувилбар нь teTeX тайпсет хөдөлгүүрээс бусад бүгдийг багтаасан байдаг. teTeX нь маш олон хэрэгслүүдийн цуглуулга учир PDF гаралт үнэхээр шаардлагагүй тохиолдолд суулгахгүй байх нь зохимжтой байдаг.
====

Subversion нь package:textproc/docproj[] порттой цуг суудаг.

[[updating-documentation-sources]]
=== Баримтын эхийг шинэчлэх нь

Subversion нь баримтын эхийн цэвэр хуулбарыг татан авч чаддаг.

[source,bash]
....
# svn checkout svn://svn.FreeBSD.org/doc/head /usr/doc
....

Баримтын эхийн эхний таталт хугацаа шаардаж болох юм. Дуустал нь хүлээх хэрэгтэй.

Баримтын эхийн дараа дараагийн шинэчлэлтүүдийг доорх тушаалыг ашиглан татан авч болно.

[source,bash]
....
# svn update /usr/doc
....

Эхийг татан авсныхаа дараа баримтыг шинэчлэх өөр нэг арга нь [.filename]#/usr/doc# сангийн [.filename]#Makefile#-аар дэмжигдсэн байдаг бөгөөд дараахийг ажиллуулна:

[source,bash]
....
# cd /usr/doc
# make update
....

[[updating-documentation-options]]
=== Баримтын эхийн тааруулж болох тохируулгууд

FreeBSD-ийн баримтжуулалтыг бүтээж шинэчлэх систем нь баримтын зөвхөн тодорхой хэсгийг шинэчлэх эсвэл тусгай орчуулгыг бүтээх процессийг амарчлах хэдэн тохируулгыг дэмждэг. Эдгээр тохируулгуудыг [.filename]#/etc/make.conf# файлд бүхэл системийн хувьд зааж өгөх юм уу эсвэл man:make[1] хэрэгсэлд тушаалын мөрийн тохиргоо маягаар зааж өгч болно.

Дараах тохируулгууд нь эдгээрийн зарим нь юм:

`DOC_LANG`::
Бүтээж суулгах хэл ба кодчилолын жагсаалт, жишээ нь Англи баримтад зөвхөн зориулсан `en_US.ISO8859-1` байна.

`FORMATS`::
Бүтээх ганц хэлбэржүүлэлт эсвэл гаралтын хэлбэржүүлэлтийн жагсаалт. Одоогоор `html`, `html-split`, `txt`, `ps`, `pdf`, болон `rtf` дэмжигдсэн байгаа.

`DOCDIR`::
Баримтыг суулгах газар. Анхдагчаар [.filename]#/usr/shared/doc# байдаг.

FreeBSD дээрх системийн тохируулга болон дэмжигдсэн бүтээлтийн хувьсагчуудын талаар дэлгэрэнгүйг man:make.conf[5]-с үзнэ үү.

FreeBSD-ийн баримтжуулалт бүтээх системийн дэмждэг бүтээлтийн хувьсагчуудын талаар дэлгэрэнгүйг link:{fdp-primer[Шинэ хувь нэмэр оруулагчдад зориулсан FreeBSD баримтжуулах төслийн гарын авлагаас] үзнэ үү.

[[updating-installed-documentation]]
=== FreeBSD-ийн баримтуудыг эхээс суулгах нь

Баримтын эхийн хамгийн сүүлийн хормын хувилбарыг [.filename]#/usr/doc# санд татаж авснаар суулгагдсан баримтын шинэчлэлтийг хийхэд бүх юм бэлэн болно.

`DOC_LANG` makefile-ийн тохиргоонд заагдсан бүх хэлний бүрэн шинэчлэлтийг дараахийг бичин хийж болно:

[source,bash]
....
# cd /usr/doc
# make install clean
....

Хэрэв зөвхөн тусгай хэлний шинэчлэлт хэрэгтэй бол [.filename]#/usr/doc#-ийн тухайн хэлний тусгай дэд санд man:make[1]-ийг ажиллуулж болно, жишээ нь:

[source,bash]
....
# cd /usr/doc/en_US.ISO8859-1
# make update install clean
....

Суулгах гаралтын хэлбэржүүлэлтийг `FORMATS` бүтээлтийн хувьсагчийг зааж өгөн хийж өгч болно, жишээ нь:

[source,bash]
....
# cd /usr/doc
# make FORMATS='html html-split' install clean
....

[[doc-ports]]
=== Баримтжуулах портуудыг ашиглах нь

Өмнөх хэсэгт FreeBSD-ийн баримтжуулалтыг эхээс нь шинэчлэх аргыг бид танилцуулсан. FreeBSD-ийн бүх системүүдийн хувьд эх дээр тулгуурласан шинэчлэлтүүд нь боломжтой эсвэл практикийн биш байж болох юм. Баримтжуулалтын эхүүдийг бүтээх нь нэлээн их хэмжээний хэрэгслийн цуглуулга буюу _баримтжуулалт бүтээх хэрэгслийн олонлог_, Subversion-ийг тодорхой хэмжээгээр мэдэх, репозиториос эхийг татаж авах болон татаж авсан эхээ бүтээх хэд хэдэн шат дарааллуудыг шаарддаг. Энэ хэсэгт бид FreeBSD-ийн баримтжуулалтын суулгагдсан хуулбаруудыг шинэчлэх өөр аргыг тайлбарлах болно. Энэ нь портын цуглуулгыг ашиглах бөгөөд дараах боломжийг бүрдүүлнэ:

* Бүгдийг бүтээлгүйгээр баримтжуулалтын урьдчилан бүтээсэн хормын хувилбарыг татан авч суулгах (ингэснээр баримтжуулалт бүтээх хэрэгслийн олонлогийг бүхэлд нь суулгах шаардлагагүй болно).
* Баримтжуулалтын эхийг татаж аван портын тогтолцоог ашиглан бүтээх (татаж аван бүтээх алхмуудыг арай хялбар болгодог).

FreeBSD-ийн баримтжуулалтыг шинэчлэх эдгээр хоёр арга нь {doceng}-ийн сар бүр шинэчилдэг _баримтжуулалтын портуудын_ цуглуулгаар дэмжигддэг. Эдгээр нь FreeBSD-ийн портын цуглуулгад http://www.freshports.org/docs/[docs] виртуал төрөлд байдаг.

[[doc-ports-install-make]]
==== Баримтжуулалтын портуудыг бүтээж суулгах нь

Баримтжуулалтын портууд нь баримтжуулалтын бүтээлтийг хялбар болгохын тулд порт бүтээх тогтолцоог хэрэглэдэг. man:make[1]-ийг тохирох орчны тохиргоонууд болон тушаалын мөрийн тохиргоонуудын хамтаар ажиллуулж баримтжуулалтын эхийг татаж авах процессыг тэд автоматжуулдаг бөгөөд баримтжуулалтын суулгалт болон устгалтыг FreeBSD-ийн бусад порт эсвэл багцын суулгалтын нэгэн адил хялбар болгодог.

[NOTE]
====
Мөн баримтжуулалтын портуудыг бүтээсний дараа тэд хамааралтай _баримтжуулалтыг бүтээх хэрэгслийн олонлогийн_ портуудыг бүртгэдэг бөгөөд тэдгээрийг автоматаар бас суулгадаг.
====

Баримтжуулалтын портуудын зохион байгуулалт нь дараах хэлбэрийн байна:

* Баримтжуулалтын портын файлууд байдаг package:misc/freebsd-doc-en[]"мастер порт" байдаг. Энэ нь бүх баримтжуулалтын портуудын үндэс болдог. Анхдагчаар энэ нь Англи баримтжуулалтыг зөвхөн бүтээдэг.
* "Нэг портод бүгд багтсан"package:misc/freebsd-doc-all[] байдаг бөгөөд энэ нь байгаа бүх хэл дээр бүх баримтжуулалтыг бүтээж суулгадаг.
* Эцэст нь орчуулга бүрийн хувьд "зарц порт" байдаг, жишээ нь Унгар хэл дээрх баримтуудад зориулсан package:misc/freebsd-doc-hu[]-г дурдаж болно. Эдгээр нь бүгд мастер портоос хамаарах бөгөөд тухайн хэлний орчуулсан баримтжуулалтыг суулгадаг.

Баримтжуулалтын портыг эхээс суулгахын тулд дараах тушаалуудыг ажиллуулна (`root` эрхээр):

[source,bash]
....
# cd /usr/ports/misc/freebsd-doc-en
# make install clean
....

Энэ нь Англи баримтжуулалтыг хуваагдсан HTML хэлбэрээр (http://www.FreeBSD.org[http://www.FreeBSD.org] дээр ашигладагийн адилаар) бүтээж [.filename]#/usr/local/shared/doc/freebsd# санд суулгадаг.

[[doc-ports-options]]
===== Нийтлэг Knob болон тохируулгууд

Баримтжуулалтын портуудын анхдагч байдлыг өөрчлөх олон тохиргоо байдаг. Доор цөөхөн хэдэн жагсаалтыг дурдав:

`WITH_HTML`::
HTML хэлбэрээр бүтээхийг зөвшөөрдөг: баримт бүрийн хувьд нэг HTML файл. Хэлбэршүүлсэн баримтжуулалт нь тохирох [.filename]#article.html# юм уу эсвэл [.filename]#book.html# гэсэн файлуудад зургийн хамтаар хадгалагддаг.

`WITH_PDF`::
Adobe(R) Acrobat Reader(R), Ghostscript эсвэл бусад PDF уншигчдыг ашиглах Adobe(R)-ийн хөрвөх баримтын хэлбэрээр бүтээхийг зөвшөөрдөг. Хэлбэршүүлсэн баримтжуулалт нь тохирох [.filename]#article.pdf# юм уу эсвэл [.filename]#book.pdf# гэсэн файлуудад хадгалагддаг.

`DOCBASE`::
Баримтжуулалтын суулгах байрлал. Энэ нь анхдагчаар [.filename]#/usr/local/shared/doc/freebsd# байдаг.
+
[NOTE]
====
Анхдагч суулгах сан нь Subversion аргын ашигладаг сангаас ялгаатайг санаарай. Энэ нь яагаад гэвэл бид порт суулгаж байгаа бөгөөд портууд нь ихэвчлэн [.filename]#/usr/local# санд суудаг. Үүнийг `PREFIX` хувьсагчийг нэмэн өөрчилж болдог.
====

Энд Унгар баримтжуулалтыг Хөрвөх Баримтын Хэлбэрээр (PDF) суулгахын тулд дээр дурдсан хувьсагчуудыг хэрхэн ашиглахыг харуулсан жишээг үзүүлэв:

[source,bash]
....
# cd /usr/ports/misc/freebsd-doc-hu
# make -DWITH_PDF DOCBASE=share/doc/freebsd/hu install clean
....

[[doc-ports-install-package]]
==== Баримтжуулалтын багцуудыг ашиглах нь

Өмнөх хэсэгт тайлбарласнаар баримтжуулалтын портуудыг эхээс бүтээх нь баримтжуулалтыг бүтээх хэрэгслийн олонлогийг суулгах болон портуудыг бүтээхэд тодорхой хэмжээний дискийн зай шаарддаг. Баримтжуулалтын хэрэгслүүдийг суулгахад эх үүсвэр хүрэлцэхгүй үед эсвэл эхээс бүтээх нь ихээхэн хэмжээний дискийн зай эзлэх бол баримтжуулалтын портуудын урьдчилан бүтээсэн хормын хувилбаруудыг суулгах боломж бас байдаг.

{doceng} нь FreeBSD-ийн баримтжуулалтын багцуудын сар бүрийн хормын хувилбаруудыг бэлддэг. Эдгээр хоёртын багцуудыг man:pkg_add[1], man:pkg_delete[1] гэх зэрэг багцын хэрэгслүүдийн хамтаар ашиглаж болдог.

[NOTE]
====
Хоёртын багцуудыг ашиглаж байгаа үед FreeBSD-ийн баримтжуулалт нь тухайн хэлний хувьд байгаа _бүх_ хэлбэрээр суудаг.
====

Жишээ нь дараах тушаал Унгар баримтжуулалтын хамгийн сүүлийн урьдчилан бүтээсэн багцыг суулгах болно:

[source,bash]
....
# pkg_add -r hu-freebsd-doc
....

[NOTE]
====
Багцууд нь харгалзах портын нэрнээсээ ялгаатай дараах нэрийн хэлбэртэй байдаг: `lang-freebsd-doc`. Энд _lang_ нь хэлний кодын богино хэлбэр юм, жишээ нь `hu` нь Унгар, эсвэл `zh_cn` нь хялбаршуулсан Хятад хэл юм.
====

[[doc-ports-update]]
==== Баримтжуулалтын портуудыг шинэчлэх нь

Өмнө нь суулгасан баримтжуулалтын портыг шинэчлэхийн тулд портууд шинэчлэх аль ч хэрэгсэл байхад хангалттай. Жишээ нь дараах тушаал суулгасан Унгар баримтжуулалтыг package:ports-mgmt/portupgrade[] хэрэгслийн тусламжтайгаар зөвхөн багцуудыг ашиглан шинэчилнэ:

[source,bash]
....
# portupgrade -PP hu-freebsd-doc
....

[[current-stable]]
== Хөгжүүлэлтийн салбарыг дагах нь

FreeBSD-ийн хоёр хөгжүүлэлтийн салбар байдаг: FreeBSD-CURRENT болон FreeBSD-STABLE. Энэ хэсэгт эдгээр тус бүрийг тайлбарлаж өөрийн системийг тус тусын модны хувьд хамгийн шинэ хэлбэрт байнга байлгах талаар тайлбарлах болно. FreeBSD-CURRENT эхлээд хэлэлцэгдэх бөгөөд дараа нь FreeBSD-STABLE-ийн тухай яригдах болно.

[[current]]
=== FreeBSD-ийн одоо үеийн хэлбэрт байх нь

Та үүнийг уншихдаа FreeBSD-CURRENT нь FreeBSD-ийн хөгжүүлэлтийн "bleeding edge салбар буюу амжилт ололтын хамгийн тэргүүний салбар" гэдгийг санаарай. FreeBSD-CURRENT хэрэглэгчдийг техникийн өндөр чадавхитай бөгөөд системийн хүнд хэцүү асуудлуудыг өөрсдөө шийдвэрлэх чадвартай байна гэж тооцдог. Хэрэв та FreeBSD-д анхлан суралцагч бол үүнийг суулгахаасаа өмнө дахин сайн бодоорой.

==== FreeBSD-CURRENT гэж юу вэ?

FreeBSD-CURRENT нь FreeBSD-ийн хамгийн сүүлийн үеийн ажлын эх юм. Энэ нь хийгдэж байгаа ажлууд, туршилтын өөрчлөлтүүд болон програм хангамжийн дараагийн албан ёсны хувилбарт байхгүй ч байж болох эсвэл байж ч болох шилжилтийн аргуудыг багтаадаг. FreeBSD-ийн олон хөгжүүлэгчид FreeBSD-CURRENT-ийн эх кодыг өдөр болгон эмхэтгэн хөрвүүлж байдаг боловч эхийг бүтээх боломжгүй үе бас байдаг. Эдгээр асуудлууд нь боломжийн хэрээр хурдан шийдэгддэг боловч FreeBSD-CURRENT нь сүйрэл авчрах эсвэл тун их хүссэн ажиллагааг авчрах эсэх нь та яг ямар агшинд эх кодыг татаж авснаас хамаарах юм!

==== FreeBSD-CURRENT хэнд хэрэгтэй вэ?

FreeBSD-CURRENT нь үндсэн 3 сонирхлын бүлэгт зориулагдан хийгдсэн:

. Эх модны зарим хэсэг дээр идэвхтэйгээр ажиллаж байгаа FreeBSD-ийн хүрээний гишүүд болон "current буюу одоо үеийн хэлбэрт" байлгах нь туйлын шаардлага болсон хүмүүст.
. FreeBSD-CURRENT-г аль болох ухаалаг байлгахыг хичээж асуудлуудыг шийдвэрлэхэд цагаа зарах хүсэлтэй байдаг идэвхтэй тест хийгч FreeBSD-ийн хүрээний гишүүд. Эдгээр хүмүүс нь өөрчлөлтүүд болон FreeBSD-ийн ерөнхий чиглэлд цаг үеийн саналуудыг тусгахыг хүсэж тэдгээрийг шийдэх засваруудыг илгээдэг бас хүмүүс юм..
. Юу болж байгааг зөвхөн харж мэдэж байхыг хүссэн эсвэл одоо үеийн эхийг лавлагааны зорилгоор ашиглахыг зөвхөн хүссэн хүмүүс (өөрөөр хэлбэл ажиллуулах биш _унших_ зорилгоор). Эдгээр хүмүүс нь хааяа бас санал гаргаж кодонд хувь нэмэр оруулдаг.

==== FreeBSD-CURRENT нь юу _Биш_ вэ?

. Та зарим нэг дажгүй шинэ боломж байгааг сонссон учраас бусдаас түрүүлж урьдчилсан хувилбарын тэдгээр битүүдийг авах таны нэн тэргүүний арга зам. Шинэ боломжийг авч эхэнд байна гэдэг нь та шинэ алдаанууд, хорхойнуудыг бас авч эхэнд байна гэсэн үг юм.
. Алдааны засваруудыг хурдан авах арга зам. FreeBSD-CURRENT-ийн өгөгдсөн дурын хувилбар нь илэрсэн алдаануудыг засахын хажуугаар бас магадгүй шинэ алдаанууд бас гаргаж байдаг.
. Аль ч үед "албан ёсоор дэмжигдсэн". Бид өөрсдийн чадлын хирээр "хууль ёсны" 3 FreeBSD-CURRENT бүлгийн аль нэгэнд хүмүүст бодитоор туслахыг хичээдэг, гэхдээ бидэнд ердөө л техникийн дэмжлэг үзүүлэх _цаг байдаггүй_. Энэ нь бид хүмүүст туслах дургүй өөдгүй муухай хүмүүс учраас гэсэн үг биш юм (хэрэв бид байгаагүй бол бид FreeBSD-г хийж байхгүй байх байсан). Бид ердөө л өдрийн хэдэн зуун захидлуудад хариулахын _хажуугаар_ FreeBSD дээр ажиллаж чаддаггүй! FreeBSD-г сайжруулах болон туршилтын кодон дээр тавигдсан маш олон асуултуудад хариулах хоёр сонголтын эхнийхийг хөгжүүлэгчид сонгосон юм.

==== FreeBSD-CURRENT ашиглах нь

. {freebsd-current} болон {svn-src-head} жагсаалтуудад элсэн орно уу. Энэ нь зөвхөн сайн санаанаас гадна бас _чухал_ юм. Хэрэв та _{freebsd-current}_ жагсаалтад ороогүй бол системийн одоогийн төлвийн талаар хүмүүсийн өгч байгаа санал хүсэлтүүдийг харахгүй учраас бусдын аль хэдийн олоод шийдсэн маш их асуудлууд дээр магадгүй та бүдрэн төөрөлдөж дуусах биз ээ. Бүр илүү чухал зүйл нь юу вэ гэвэл таны системийн эрүүл мэндэд эгзэгтэй байж болох чухал мэдээнүүдээс та хоцрох болно.
+ 
{svn-src-head} жагсаалт нь кодонд оруулсан өөрчлөлт бүрийн бүртгэл оруулгыг болзошгүй сөрөг нөлөөнүүдийн талаар тохирсон мэдээллийн хамтаар танд харах боломжийг олгодог.
+ 
Эдгээр жагсаалтууд эсвэл байгаа бусдын аль нэгэнд элсэхийн тулд {mailman-lists-url} хаяг уруу орж элсэхийг хүссэн жагсаалтаа сонгоорой. Дарааллын үлдсэн зааврууд тэнд байгаа болно. Хэрэв та бүх л эх модон дахь өөрчлөлтийг дагах сонирхолтой байгаа бол {svn-src-all} жагсаалтад бүртгүүлэхийг бид зөвлөж байна.
. FreeBSD-ийн crossref:mirrors[mirrors,толин тусгал]аас эхийг авна. Та үүнийг гурван аргаар хийж болно:
.. Хүссэн хөгжүүлэлт эсвэл салбар хувилбарыг татаж авахдаа crossref:mirrors[svn,svn] програмыг ашиглах хэрэгтэй. Энэ аргыг FreeBSD-н хөгжүүлэлтэд хандахад зөвлөдөг. -CURRENT суурь системийн Subversion татаж авах үндсэн URL нь `http://svn.freebsd.org/base/head/` бөгөөд репозиторын хэмжээ их тул зөвхөн хүссэн дэд модоо татаж авахыг зөвлөдөг. 
.. [.filename]#/usr/shared/examples/cvsup# санд байх [.filename]#standard-supfile# гэж нэрлэгдсэн [.filename]#supfile#-тай цуг crossref:mirrors[cvsup,cvsup] програм ашигла. Та дээр дурдсан жишээ [.filename]#supfile#-г өөрчлөн crossref:mirrors[cvsup,cvsup]-г өөрийн орчны хувьд тохируулах хэрэгтэй.
+
[WARNING]
====

`cvsup`-г ашиглах нь хуучирсан бөгөөд төсөл ашиглахыг зөвлөдөггүй.
====
+
[NOTE]
====
Жишээ [.filename]#standard-supfile# нь FreeBSD-CURRENT-ийн биш FreeBSD-ийн аюулгүй байдлын тусгай салбарыг дагахад хэрэглэгдэнэ. Танд энэ файлыг засварлаж дараах мөрийг өөрчлөх хэрэгтэй болно:

[.programlisting]
....
*default release=cvs tag=RELENG_X_Y
....

Дээрх мөрийг дараах мөрөөр сольно:

[.programlisting]
....
*default release=cvs tag=.
....

Хэрэгцээтэй хаяг/шошгонуудын дэлгэрэнгүй тайлбарыг гарын авлагын crossref:mirrors[cvs-tags,CVS хаяг/шошгонууд] хэсгээс үзнэ үү.
====

.. CTM хэрэгслийг ашигла. Хэрэв та маш муу холболттой (өндөр үнэтэй холболтууд эсвэл зөвхөн цахим захидлын хандалт) бол CTM нь сонголт болох юм. Гэхдээ энэ нь бөөн зовлон бөгөөд та эвдэрсэн файлуудтай үлдэж болох юм. Энэ нь үүнийг ховор ашиглахад хүргэдэг бөгөөд ингэснээр ажиллахгүй байх боломжийг нэлээн удаан хугацаагаар ихэсгэдэг. Бид Интернэт холболттой хүмүүст Subversion-г ашиглахыг зөвлөдөг. 

. Хэрэв та эхийг зөвхөн харахаар биш ажиллуулахаар татаж авч байгаа бол зөвхөн сонгосон хэсгүүдийг биш FreeBSD-CURRENT-ийн _бүх_ эхийг татаж аваарай. Үүний шалтгаан нь эхийн төрөл бүрийн хэсгүүд нь бусад хаа нэгтээ байгаа шинэчлэлтүүдээс хамаардаг бөгөөд зөвхөн хэсэг бүлэг эхийг хөрвүүлэхийг оролдох нь таныг бараг л баталгаатайгаар асуудалтай учруулах болно.
+ 
FreeBSD-CURRENT-ийг хөрвүүлэхээсээ өмнө [.filename]#/usr/src# дахь [.filename]#Makefile#-г анхааралтай уншина уу. Эхний удаа та хамгийн багаар бодоход шинэчлэлтийн процессийн хэсэг болох <<makeworld,шинэ цөмийг суулгаж ертенцийг дахин бүтээх>> хэсгээр дамжих хэрэгтэй. {freebsd-current} болон [.filename]#/usr/src/UPDATING# файлыг унших нь биднийг дараагийн хувилбар уруу шилжихэд заримдаа шаардлагатай болдог бусад эхлүүлэх процедуруудын хувьд хамгийн сүүлийн мэдээлэлтэй байлгах боломжийг бидэнд олгодог.
. Идэвхтэй бай! Хэрэв та FreeBSD-CURRENT ажиллуулж байгаа бол түүний талаар таныг юу хэлэхийг ялангуяа хэрэв танд өргөжүүлэлт эсвэл алдааны засваруудын талаар санал хүсэлт байвал түүнийг бид мэдэхийг хүсдэг юм. Хавсаргасан кодтой санал хүсэлтүүдийг хамгийн их урам зоригтойгоор хүлээн авдаг билээ!

[[stable]]
=== FreeBSD-ийн тогтвортой хэлбэрт байх нь

==== FreeBSD-STABLE гэж юу вэ?

FreeBSD-STABLE нь үндсэн хувилбарууд гардаг бидний хөгжүүлэлтийн салбар юм. Өөрчлөлтүүд нь эхлээд тест хийгдэх зорилгоор FreeBSD-CURRENT уруу ордог гэсэн ерөнхий төсөөлөл/таамаглалтайгаар янз бүрийн зөвшөөрлөөр энэ салбар уруу ордог. Энэ нь _одоо болтол_ хөгжүүлэлтийн салбар бөгөөд гэхдээ энэ нь ямар ч үед FreeBSD-STABLE-д зориулагдсан эх нь ямар ч зорилгод тохирч эсвэл тохирохгүй байж болно гэсэн үг юм. Энэ нь эцсийн хэрэглэгчид зориулагдсан эх үүсвэр бус ердөө л өөр нэг инженерчлэлийн хөгжүүлэлтийн арга зам юм.

==== FreeBSD-STABLE хэнд хэрэгтэй вэ?

Хэрэв та FreeBSD-ийн хөгжүүлэлтийн процессод хувь нэмэр оруулах сонирхолтой, энэ нь ялангуяа FreeBSD-ийн дараагийн "гарах" хувилбартай холбоотой байдаг, эсвэл юу болж байгааг мэдэж байх сонирхолтой байгаа бол та дараах FreeBSD-STABLE-г бодолцох хэрэгтэй.

Аюулгүй байдлын засварууд бас FreeBSD-STABLE салбар уруу орж байдаг нь үнэн боловч та үүнийг хийхийн тулд FreeBSD-STABLE-г заавал дагах _хэрэггүй_. FreeBSD-ийн аюулгүй байдлын зөвлөмжүүд нь тухайн хувилбарт хамааралтай асуудлыг хэрхэн засах тухай тайлбарладаг  бөгөөд зөвхөн аюулгүй байдлын үүднээс бүхэл бүтэн хөгжүүлэлтийн салбарыг дагаж байна гэдэг бас зөндөө олон хүсээгүй өөрчлөлтүүдийг авчрах магадлалтай юм.

Бид FreeBSD-STABLE салбар үргэлж хөрвүүлэгдэн эмхэтгэгдэж дандаа ажилладаг байлгахаар чармайж байдаг боловч энэ нь баталгаатай биш юм. Нэмж хэлэхэд код нь FreeBSD-STABLE-д орохоосоо өмнө FreeBSD-CURRENT-д хөгжүүлэгдэж байдаг боловч FreeBSD-CURRENT-г ашиглан ажиллуулдгаас илүү FreeBSD-STABLE-г хүмүүс ажиллуулдаг болохоор FreeBSD-CURRENT-ийн хувьд илэрхий биш байсан алдаанууд болон булангийн тохиолдлууд FreeBSD-STABLE-д илрэх нь заримдаа зайлшгүй юм.

Эдгээр шалтгаануудаас болоод бид FreeBSD-STABLE-г сохроор дагахыг танд _зөвлөдөггүй_ бөгөөд энэ нь өөрийн хөгжүүлэлтийн орчиндоо кодыг эхлээд сайтар тест хийлгүйгээр үйлдвэрлэлд (production) ашиглаж байгаа серверүүдээ FreeBSD-STABLE уруу шинэчлэхгүй байхад танд ялангуяа чухал ач холбогдолтой юм.

Хэрэв танд үүнийг хийх эх үүсвэрүүд байхгүй бол бид FreeBSD-ийн хамгийн сүүлийн үеийн хувилбарыг ажиллуулж хоёртын шинэчлэлт хийх аргыг хувилбараас хувилбар уруу шилжихдээ ашиглахыг танд зөвлөж байна.

==== FreeBSD-STABLE ашиглах нь

. {freebsd-stable} жагсаалтад элсэн орно уу. Энэ нь FreeBSD-STABLE-д илэрч болох бүтээлтийн хамаарлууд эсвэл тусгайлсан анхаарал шаардлагатай өөр бусад асуудлуудын талаар танд мэдээлж байх болно. Хөгжүүлэгчид нь зарим нэг маргаантай засвар эсвэл шинэчлэлийн талаар бодож байгаа талаараа бас энэ захидлын жагсаалтад мэдээлдэг бөгөөд ийнхүү санал болгож байгаа өөрчлөлтийн талаар хэрэглэгчдэд ямар нэг асуудал байвал тэдэнд эргээд хариу өгөх боломж олгодог юм.
+ 
Өөрийн дагаж байгаа салбарын тохирох SVN жагсаалтад элсэн орох хэрэгтэй. Жишээ нь хэрэв та 9-STABLE салбарыг дагаж байгаа бол {svn-src-stable-9} жагсаалтад элсэн ороорой. Энэ нь кодонд оруулсан өөрчлөлт бүрийн бүртгэл оруулгыг болзошгүй сөрөг нөлөөнүүдийн талаар тохирсон мэдээллийн хамтаар танд харах боломжийг олгодог.
+ 
Эдгээр жагсаалтууд эсвэл байгаа бусдын аль нэгэнд элсэхийн тулд {mailman-lists-url} хаяг уруу орж элсэхийг хүссэн жагсаалтаа сонгоорой. Дарааллын үлдсэн зааврууд тэнд байгаа болно. Хэрэв та бүх л эх модон дахь өөрчлөлтийг дагах сонирхолтой байгаа бол {svn-src-all} жагсаалтад бүртгүүлэхийг бид зөвлөж байна.
. Хэрэв та шинэ систем суулгаж FreeBSD-STABLE-ээс бүтээсэн сар бүрийн хормын агшны хувилбарыг түүн дээр ажиллуулахыг хүсэж байгаа бол дэлгэрэнгүй мэдээллийн талаар link:https://www.FreeBSD.org/snapshots/[Хормын агшны хувилбарууд] вэб хуудаснаас шалгана уу. Үүнээс гадна хамгийн сүүлийн үеийн FreeBSD-STABLE хувилбарыг crossref:mirrors[mirrors,толин тусгалын хаягууд]аас татан авч суулгах боломжтой бөгөөд доор дурдсан заавруудыг дагаж өөрийн системийг хамгийн сүүлийн үеийн FreeBSD-STABLE эх код уруу шинэчилж болох юм.
+ 
Хэрэв та FreeBSD-ийн урдны хувилбар аль хэдийн ажиллуулж байгаа бөгөөд эхээс шинэчлэхийг хүсэж байгаа бол FreeBSD-ийн crossref:mirrors[mirrors,толин тусгал хуудас]аас хялбараар хийж болно. Үүнийг гурван аргаар хийж болно:

.. Хүссэн хөгжүүлэлт эсвэл салбар хувилбарыг татахдаа crossref:mirrors[svn,svn] програмыг ашиглах хэрэгтэй. Энэ аргыг FreeBSD-н хөгжүүлэлтэд хандахад зөвлөдөг. Салбарын нэрсэд одоогийн хөгжүүлэлтийн толгой хувилбарын хувьд `head`, болон `stable/9` эсвэл `releng/9.0` гэх зэрэг link:https://www.FreeBSD.org/releng/[хувилбар инженерчлэлийн хуудас] дахь салбарууд ордог. Суурь системийн Subversion татаж авах үндсэн URL нь `http://svn.freebsd.org/base/` бөгөөд репозиторын хэмжээ их тул зөвхөн хүссэн дэд модоо татаж авахыг зөвлөдөг. 

.. [.filename]#/usr/shared/examples/cvsup# санд байх [.filename]#standard-supfile# гэж нэрлэгдсэн [.filename]#supfile#-тай цуг crossref:mirrors[cvsup,cvsup] програм ашигла. Та дээр дурдсан жишээ [.filename]#supfile#-г өөрчлөн crossref:mirrors[cvsup,cvsup]-г өөрийн орчны хувьд тохируулах хэрэгтэй.
+
[WARNING]
====

`cvsup` нь хуучирсан бөгөөд төсөл ашиглахыг зөвлөдөггүй.
====

.. CTM хэрэгслийг ашигла. Хэрэв танд Интернэт уруу холбогдсон хурдан хямд холболт байхгүй бол энэ аргыг та ашиглах хэрэгтэй. 

. Гол нь хэрэв та эхэд хурдан, шаардлагын улмаас хандах хэрэгтэй болоод холболтуудын зурвасын өргөн ач холбогдолгүй бол `cvsup` эсвэл `ftp` ашиглаарай. Бусад тохиолдолд CTM-г ашигла.
. FreeBSD-CURRENT-ийг хөрвүүлэхээсээ өмнө [.filename]#/usr/src# дахь [.filename]#Makefile#-г анхааралтай уншина уу. Эхний удаа та хамгийн багаар бодоход шинэчлэлтийн процессийн хэсэг болох <<makeworld,шинэ цөмийг суулгаж ертенцийг дахин бүтээх>> хэсгээр дамжих хэрэгтэй. {freebsd-current} болон [.filename]#/usr/src/UPDATING# файлыг унших нь биднийг дараагийн хувилбар уруу шилжихэд заримдаа шаардлагатай болдог бусад эхлүүлэх процедуруудын хувьд хамгийн сүүлийн мэдээлэлтэй байлгах боломжийг бидэнд олгодог.

[[synching]]
== Өөрийн эхийг хамгийн сүүлийн хэлбэрт аваачих нь

Интернетийн (эсвэл цахим захидал) холболт ашиглан FreeBSD төслийн эхүүдийн аль ч хэсгийн хувьд эсвэл таны юу сонирхож байгаагаас хамааран бүх хэсгүүдийг хамгийн шинэ байлгаж байх төрөл бүрийн аргууд байдаг. Бидний санал болгодог үндсэн үйлчилгээнүүд бол crossref:mirrors[svn,Subversion], crossref:mirrors[anoncvs,Anonymous буюу нэргүй CVS], crossref:mirrors[cvsup,CVSup] болон crossref:mirrors[ctm,CTM] юм.

[WARNING]
====

Өөрийн эх модны зөвхөн зарим хэсгийг шинэчлэх боломжтой боловч цорын ганц шинэчлэх арга бол модыг бүтнээр нь шинэчилж хэрэглэгчийн талбар (өөрөөр хэлбэл [.filename]#/bin# болон [.filename]#/sbin# гэх мэт дэх хэрэглэгчийн талбарт ажилладаг бүх програмууд) болон цөмийн эхүүдийг дахин эмхэтгэх явдал юм. Өөрийн эх модны зөвхөн нэг хэсэг зөвхөн цөм эсвэл зөвхөн хэрэглэгчийн талбарыг шинэчлэх нь асуудлууд гарахад ихэвчлэн хүргэдэг. Эдгээр асуудлууд нь эмхэтгэлтийн үеийн алдаануудаас авахуулаад цөмийн сүйрлүүд эсвэл өгөгдлийн эвдрэлийг хүртэл хамардаг.
====

Subversion, Нэргүй CVS болон CVSup нь эхийг шинэчлэхдээ _татах_ загварыг хэрэглэдэг. Subversion-ийн хувьд хэрэглэгч (эсвэл `cron` скрипт) `svn` програмыг эхлүүлэн файлуудыг хамгийн шинэ хэлбэрт авчирдаг. Локал эх модыг шинэчлэхэд зөвлөдөг арга бол Subversion юм. `cvsup` ба `cvs` нь ижил зарчмаар ажиллах боловч хуучирсан бөгөөд Subversion-ийг ашиглахыг зөвлөдөг. Таны хүлээн авах шинэчлэлтүүд нь хамгийн сүүлийн минут хүртэлх үеийнх байх бөгөөд та тэдгээрийг зөвхөн өөрийн хүссэн тэр үедээ авдаг. Та өөрийн шинэчлэлтүүдийг таны сонирхож байгаа тусгайлсан файлууд эсвэл сангуудаар хялбараар хязгаарлаж болно. Шинэчлэлтүүд нь таны юуг авахыг хүссэн болон танд юу байгаагаас хамааран серверээр тухайн үед үүсгэгддэг. Үнэхээр шаардлагагүй л бол хуучирч ирээдүйд үргэлжүүлэн ашиглахаа болих бусад синхрон хийх аргуудаас илүүтэй Subversion-г ашиглах ёстой юм.

Нөгөө талаас CTM нь танд байгаа эхийг мастер архив дахь эхтэй лавлаж асуух зарчмаар харьцуулдаггүй бөгөөд өөрөөр хэлбэл тэдгээрийг татаж авдаггүй. Ингэхийн оронд харин өмнө нь ажиллуулснаас хойшх файл дахь өөрчлөлтүүдийг таньдаг скрипт өдөрт хэд хэдэн удаа мастер CTM машин дээр ажиллаж илэрсэн өөрчлөлтүүдийг шахаж дарааллын-дугаар тавин цахим захидлаар дамжуулахад зориулан кодчилдог (зөвхөн хэвлэгдэх боломжтой ASCII хэлбэрээр). Эдгээр "CTM дельтануудыг" авсаны дараа тэдгээрийг автоматаар декод хийж шалган хэрэгчид байгаа эхийн хуулбарт өөрчлөлтүүдийг хийх man:ctm_rmail[1] хэрэгсэл уруу өгдөг. Энэ процесс нь CVSup-с хамаагүй илүү үр дүнтэй бөгөөд энэ нь _татах_ биш харин _түлхэх_ загвар учраас бидний серверийн эх үүсвэрт бага ачаалал учруулдаг юм.

Мэдээж үүнээс гадна харилцан сул болон давуу талуудтай асуудлууд байдаг. Хэрэв та санамсаргүйгээр өөрийн архивын хэсгийг устгачих юм бол CVSup үүнийг илрүүлж эвдэрсэн хэсгүүдийг дахин бүтээж өгдөг. CTM ингэж хийдэггүй бөгөөд хэрэв та өөрийн эх модны зарим хэсгийг устгасан (бас нөөцлөн аваагүй) бол та дахин шинээр эхнээс нь (хамгийн сүүлийн үеийн CVS "суурь дельтагаас") эхэлж CTM-ийн тусламжтайгаар бүгдийг дахин бүтээх буюу эсвэл Нэргүй CVS-ийн тусламжтайгаар муу битүүдийг ердөө л устгаж дахин сүүлийн хэлбэрт аваачих хэрэгтэй болно.

[[makeworld]]
== "Ертөнц"ийг дахин бүтээх нь

Та өөрийн локал эх модоо FreeBSD-ийн тухайн хувилбарын (FreeBSD-STABLE, FreeBSD-CURRENT, гэх зэрэг) хамгийн сүүлийн үеийн хэлбэрт аваачсаныхаа дараа та эх модоо ашиглан системийг дахин бүтээж болно.

[WARNING]
.Нөөц хий
====
Та дээрхийг хийхээсээ _өмнө_ өөрийн системийг нөөцлөн авах нь ямар чухал болохыг энэ нь хангалттай хэлж өгч чаддаггүй. Ертөнцийг дахин бүтээх нь (хэрэв та эдгээр заавруудыг дагасан тохиолдолд) хялбар боловч таныг алдаа гаргахад эсвэл бусдын эх модонд хийсэн алдаанууд нь таны системийг ачаалагдахгүй болгох нөхцөлд зайлшгүй хүргэдэг.

Нөөц хийж авсан эсэхээ шалгаарай. Засварлах уян диск эсвэл ачаалагдах CD-г гарын дор байлгаарай. Магадгүй та үүнийг хэзээ ч хэрэглэхгүй байж болох юм, гэхдээ харамсахаасаа өмнө аюулгүй байж байх нь илүү дээр юм!
====

[WARNING]
.Тохирох захидлын жагсаалтад бүртгүүл
====
FreeBSD-STABLE болон FreeBSD-CURRENT салбарууд нь угаасаа _хөгжүүлэлтэд байдаг_. FreeBSD-д хувь нэмэр оруулж байгаа хүмүүс нь хүн л учраас алдаанууд заримдаа гардаг.

Заримдаа эдгээр алдаанууд нь нэг их хор хөнөөлгүй бөгөөд ердөө л таны системийг шинэ оношлогооны анхааруулга хэвлэхэд хүргэдэг. Эсвэл өөрчлөлт нь сүйрлийн байж болзошгүй байдаг бөгөөд таны системийг ачаалагдахгүй болгож эсвэл файлын системүүдийг чинь устгаж (эсвэл бүр муу юм болж) болох юм.

Эдгээртэй адил асуудлууд гарвал асуудлын учир шалтгаан болон аль систем дээр энэ асуудал хамааралтайг тайлбарласан "heads up буюу бүхний сонорт" хандсан зарлал тохирох захидлын жагсаалтад илгээгддэг. Тэгээд "all clear буюу бүгд цэвэр" зарлал асуудал шийдэгдсэний дараа тавигддаг.

Хэрэв та FreeBSD-STABLE эсвэл FreeBSD-CURRENT-ийг дагахыг оролдож {freebsd-stable} эсвэл {freebsd-current}-г харгалзуулан уншихгүй байгаа бол энэ нь та өөртөө гай төвөг асууж байна л гэсэн үг юм.
====

[WARNING]
.`make world` тушаалыг бүү ашигла
====
Ихэнх хуучин баримтууд үүнд зориулан `make world` тушаалыг ашиглахыг зөвлөдөг. Энэ тушаалыг ажиллуулснаар зарим нэг чухал алхмуудыг алгасах бөгөөд та юу хийж байгаагаа мэдэж байгаа тохиолдолд үүнийг зөвхөн ашиглах хэрэгтэй. Бараг ихэнх тохиолдолд `make world` хийх нь буруу зүйл бөгөөд энд тайлбарласан процедурыг түүний оронд ашиглах ёстой юм.
====

[[canonical-build]]
=== Шалгагдсан аргаар өөрийн системийг шинэчлэх нь

Өөрийн системийг шинэчлэхийн тулд өөрт чинь байгаа эхийн хувилбарт шаардлагатай байгаа бүтээхээс урьдах алхмууд та [.filename]#/usr/src/UPDATING# файлд байгаа эсэхийг шалгах хэрэгтэй бөгөөд үүний дараа энд дурдсан процедурыг ашиглана.

Эдгээр шинэчлэлтийн алхмууд нь таныг хуучин хөрвүүлэгч, хуучин цөм, хуучин ертөнц болон хуучин тохиргооны файлууд бүхий FreeBSD-ийн хуучин хувилбар ашиглаж байгаа гэж тооцдог. "Ертөнц" гэдгийг бид энд системийн гол хоёртын файлууд, сангууд болон програмын файлууд гэж ойлгоно. Хөрвүүлэгч нь "ертөнц"ийн хэсэг бөгөөд цөөн асуудлуудтай байдаг.

Таныг шинэ системийн эхийг аль хэдийн авсан байгаа гэж бид бас энд тооцдог. Тухайн систем дээр байгаа эхүүд бас хуучин байвал шинэ хувилбар руу шилжүүлэх талаар бичсэн <<synching>>-с дэлгэрэнгүйг үзнэ үү.

Системийг эхээс шинэчлэх нь эхлээд санагдсанаасаа илүү нарийн байдаг бөгөөд тойрон гарах боломжгүй, хамаарлууд бүхий шинэ асуудлууд гардгаас болоод FreeBSD-ийн хөгжүүлэгчид зөвлөдөг чиг хандлагаа жил ирэх тутам нэлээнээр өөрчлөх шаардлагатай болсон. Энэ хэсгийн үлдсэн хэсэг нь одоогоор зөвлөж байгаа шинэчлэх дарааллын талаар тайлбарлах болно.

Амжилттай болох шинэчлэх дараалал бүр дараах асуудлуудыг шийдэх ёстой:

* Хуучин хөрвүүлэгч шинэ цөмийг бүтээж чадахгүй байж болох юм. (Хуучин хөрвүүлэгчид заримдаа алдаатай байдаг.) Тиймээс шинэ цөмийг шинэ хөрвүүлэгчээр бүтээх ёстой. Ялангуяа шинэ цөм бүтээхээсээ өмнө шинэ хөрвүүлэгчийг бүтээх хэрэгтэй. Энэ нь шинэ хөрвүүлэгчийг заавал шинэ цөмөөс өмнө _суулгасан_ байх ёстой гэсэн үг биш юм.
* Шинэ ертөнц шинэ цөмийн боломжууд дээр тулгуурлаж байж болох юм. Тиймээс шинэ цөмийг шинэ ертөнцийг суулгахаасаа өмнө суулгасан байх шаардлагатай.

Эдгээр хоёр асуудал нь бидний дараагийн хэсгүүдэд тайлбарлах гол `buildworld`, `buildkernel`, `installkernel`, `installworld` дарааллын үндэс болдог. Энэ нь одоогоор зөвлөдөг шинэчлэлтийн просессийг та яагаад заавал сонгох ёстойг харуулсан бүх шалтгаануудын бүрэн дүүрэн жагсаалт биш юм. Зарим нэг тийм ч мэдээжийн биш зүйлсийг доор жагсаав:

* Хуучин ертөнц шинэ цөм дээр зөв ажиллахгүй байж болох учир та шинэ цөм суулгасныхаа дараа шинэ ертөнцийг даруйхан суулгах ёстой.
* Шинэ ертөнц суулгахаасаа өмнө зарим нэг тохиргооны өөрчлөлтүүдийг хийх ёстой боловч зарим нь хуучин ертөнцийг эвдэж магадгүй юм. Тийм болохоор хоёр өөр тохиргооны шинэчлэлтийн алхам ерөнхийдөө шаардлагатай байдаг.
* Ихэнх хэсгийн хувьд шинэчлэх процесс нь зөвхөн файлуудыг солих юм уу эсвэл нэмдэг бөгөөд байгаа хуучин файлуудыг устгадаггүй. Цөөн тохиолдолд энэ нь асуудал үүсгэж болох юм. Үүний дүнд шинэчлэх арга зам нь зарим нэг алхам дээр гараар устгах тодорхой файлуудыг заримдаа зааж өгдөг. Үүнийг ирээдүйд автоматчилах юм уу эсвэл үгүй ч байж болох юм.

Эдгээр зүйлс нь дараах зөвлөсөн дараалалд хүргэдэг. Тухайн шинэчлэлтүүдэд зориулсан дэлгэрэнгүй дараалал нь нэмэлт алхмуудыг шаардаж болохыг санаарай. Гэхдээ эдгээр гол процессууд тодорхой хугацаагаар өөрчлөгдөхгүй байх ёстой юм:

. `make buildworld`
+ 
Энэ нь эхлээд шинэ хөрвүүлэгч болон хамааралтай цөөн хэрэгслүүдийг бүтээж дараа нь шинэ ертөнцийн бусдыг хөрвүүлэхийн тулд шинэ хөрвүүлэгчийг ашигладаг. Үр дүн нь [.filename]#/usr/obj#-д хадгалагддаг.
. `make buildkernel`
+ 
man:config[8] болон man:make[1]-ийг ашигладаг хуучин аргаасаа ялгаатай нь энэ тушаал [.filename]#/usr/obj# санд байрлаж байгаа _шинэ_ хөрвүүлэгчийг ашигладаг. Энэ нь хөрвүүлэгч болон цөмийн хооронд тохиромжгүй байдал үүсэхээс таныг хамгаалдаг.
. `make installkernel`
+ 
Шинэ цөм болон цөмийн модулиудыг дискэд байрлуулж шинээр шинэчилсэн цөмөөр ачаалах боломжийг бүрдүүлдэг.
. Ганц хэрэглэгчийн горим руу ачаалан орно.
+ 
Ганц хэрэглэгчийн горим нь ажиллаж байгаа програм хангамжуудыг шинэчлэхэд гарах асуудлуудыг багасгадаг. Энэ нь бас шинэ цөм дээр хуучин ертөнцийг ажиллуулахад гарах асуудлыг багасгадаг.
. `mergemaster -p`
+ 
Энэ нь шинэ ертөнцөд зориулж зарим нэг тохиргооны файлуудын эхний шинэчлэлтүүдийг хийдэг. Жишээ нь энэ нь шинэ хэрэглэгчийн бүлгийг системд нэмэх, эсвэл шинэ хэрэглэгчийн нэрсийг нууц үгийн мэдээллийн санд нэмж болох юм. Сүүлийн шинэчлэлтээс хойш шинэ бүлгүүд эсвэл системийн тусгай хэрэглэгчийн бүртгэлүүдийг нэмэх үед энэ нь ихэвчлэн шаардлагатай байдаг. Ингэснээр `installworld` алхам нь шинээр суулгагдсан системийн хэрэглэгч эсвэл системийн бүлгийн нэрсийг ямар ч асуудалгүйгээр ашиглах боломжтой болох юм.
. `make installworld`
+ 
[.filename]#/usr/obj# сангаас ертөнцийг хуулдаг. Та одоо диск дээрээ шинэ цөм болон шинэ ертөнцтэй боллоо.
. `mergemaster`
+ 
Нэгэнт диск дээрээ шинэ ертөнцтэй болсон болохоор та одоо үлдсэн тохиргооны файлуудаа шинэчилж болно.
. Дахин ачаална.
+ 
Шинэ цөм болон шинэ ертөнцийг шинэ тохиргооны файлуудтай дуудахын тулд машиныг бүрэн дахин ачаалах хэрэгтэй.

Хэрэв та FreeBSD-ийн нэг салбар дотор нэг хувилбараас илүү сүүлийн хувилбар руу шинэчилж байгаа бол, өөрөөр хэлбэл 7.0-с 7.1 рүү шинэчилж байгаа бол хөрвүүлэгч, цөм, хэрэглэгчийн талбар болон тохиргооны файлуудын хооронд айхтар таарамжгүй байдлууд тантай бараг л тохиолдохгүй учир энэ арга нь заавал шаардлагатай биш байж болох юм. Хуучин арга болох `make world` болон шинэ цөмийг бүтээж суулгах нь жижиг шинэчлэлтийн хувьд хангалттай сайн ажиллаж болох юм.

Гэхдээ гол хувилбаруудын хооронд шинэчлэлт хийж байх үед энэ арга замыг дагахгүй байгаа хүмүүст зарим асуудлууд учирч болох юм.

Олон шинэчлэлтүүд (өөрөөр хэлбэл 4._X_-с 5.0 руу) тусгайлсан нэмэлт алхмуудыг (жишээ нь installworld хийхээс өмнө тусгай файлуудын нэрийг өөрчлөх эсвэл устгах гэх мэт) шаардаж болохыг энд тэмдэглэх нь зүйтэй юм. [.filename]#/usr/src/UPDATING# файлыг анхааралтай уншина уу, ялангуяа одоогоор зөвлөсөн байгаа шинэчлэх дарааллыг тусгайлан тайлбарласан төгсгөл хэсгийг уншаарай.

Зарим нэг тохиромжгүй байдалтай холбоотой асуудлуудаас бүрэн гүйцэд хамгаалах боломжгүйг хөгжүүлэгчид мэдсэнээр энэ арга нь цаг хугацааны туршид сайжруулагдсаар ирсэн юм. Одоогийн арга замууд нь удаан хугацааны туршид тогвортой байна гэдэгт найдаж байна.

Дүгнэхэд FreeBSD-г эхээс шинэчлэхэд одоогоор зөвлөдөг арга бол:

[source,bash]
....
# cd /usr/src
# make buildworld
# make buildkernel
# make installkernel
# shutdown -r now
....

[NOTE]
====
`buildworld` алхмаас өмнө `mergemaster -p` тушаалыг нэмж ажиллуулах цөөн ховор тохиолдлууд байдаг. Эдгээрийн талаар [.filename]#UPDATING# файлд тайлбарласан байдаг. Хэрэв та FreeBSD-ийн нэг буюу олон голлох хувилбаруудын дагуу шинэчлэл хийхгүй байгаа бол ерөнхийдөө энэ алхмыг эмээлгүйгээр орхиж болох юм.
====

`installkernel` амжилттай дууссаны дараа та ганц хэрэглэгчийн горим уруу ачаалах хэрэгтэй (өөрөөр хэлбэл `boot -s` тушаалыг дуудагч мөрөөс ашиглана). Дараа нь доор дурдсан тушаалуудыг ажиллуулна:

[source,bash]
....
# mount -u /
# mount -a -t ufs
# adjkerntz -i
# mergemaster -p
# cd /usr/src
# make installworld
# mergemaster
# reboot
....

[WARNING]
.Тайлбаруудыг цааш уншина уу
====
Дээр тайлбарласан дараалал нь зөвхөн таныг эхлэхэд туслах богино сэргээлт болох юм. Гэхдээ хэрэв та ялангуяа өөрчлөн тохируулсан цөмийн тохиргоо ашиглахыг хүсэж байгаа бол дараах хэсгүүдийг уншиж алхам бүрийг сайтар ойлгох хэрэгтэй.
====

[[src-updating]]
=== [.filename]#/usr/src/UPDATING# файлыг унш

Өөр юм хийж эхлэхээсээ өмнө та [.filename]#/usr/src/UPDATING#-г (эсвэл эх кодын хуулбар хаана байгаа тэндээс үүнтэй төстэй файлыг ) уншаарай. Энэ файл нь танд учирч болзошгүй асуудлуудын талаар чухал мэдээлэл агуулдаг бөгөөд эсвэл таны ажиллуулах зарим нэг тушаалуудын дарааллын талаар заасан байдаг. Хэрэв [.filename]#UPDATING# файл таны энд уншсантай зөрчилдөж байвал [.filename]#UPDATING# файлд заасныг дагах хэрэгтэй.

[IMPORTANT]
====
[.filename]#UPDATING# файлыг унших нь өмнө нь тайлбарласнаар зөв захидлын жагсаалтад бүртгүүлэхтэй харьцуулах юм бол хүлээн зөвшөөрч болохуйц орлогч байж чадахгүй юм. Энэ хоёр шаардлага нь нэмэлт бөгөөд заавал шаардлагатай биш юм.
====

[[make-conf]]
=== [.filename]#/etc/make.conf# файлыг шалга

[.filename]#/usr/shared/examples/etc/make.conf# болон [.filename]#/etc/make.conf# файлыг шалгаарай. Эхнийх нь зарим нэг анхдагч тодорхойлолтуудыг агуулдаг - тэдгээрийн ихэнх нь тайлбар болон хаагдсан байдаг. Та системээ эхээс нь дахин бүтээх үедээ тэдгээрийг ашиглахын тулд [.filename]#/etc/make.conf# файлд нэмэх хэрэгтэй. [.filename]#/etc/make.conf# файлд нэмсэн болгон `make` тушаалыг ажиллуулах бүрд бас ашиглагддаг учир өөрийн системдээ зориулан тэдгээрийг боломжийн утгаар тохируулж өгөх нь зүйтэй юм.

Ердийн хэрэглэгч [.filename]#/usr/shared/examples/etc/make.conf# файлд байдаг `NO_PROFILE` мөрийг [.filename]#/etc/make.conf# уруу хуулж тайлбар болгосныг болиулж нээхийг магадгүй хүсэж болох юм.

`NOPORTDOCS` гэх зэрэг бусад тодорхойлолтуудыг шалгаж танд хамаатай эсэхээс хамаарч оруулах эсэхээ шийдээрэй.

[[updating-etc]]
=== [.filename]#/etc# дэх файлуудыг шинэчил

[.filename]#/etc# сан нь таны системийн тохиргооны мэдээллийн ихэнх хэсгийг агуулдгаас гадна системийг эхлүүлэхэд ажилладаг скриптүүд энд байдаг. Эдгээр скриптүүдийн зарим нь FreeBSD-ийн хувилбараас хувилбарт өөрчлөгддөг.

Тохиргооны файлуудын зарим нь бас системийг ажиллуулахад өдөр тутам хэрэглэгддэг. Ялангуяа [.filename]#/etc/group#-г дурдаж болно.

`make installworld` тушаалын суулгалт хийх хэсэг нь зарим нэг хэрэглэгчийн нэр эсвэл бүлгүүд байж байна гэж тооцдог тохиолдлууд байдаг. Шинэчлэл хийж байх үед эдгээр хэрэглэгчид эсвэл бүлгүүд ихэнхдээ байхгүй байдаг. Энэ нь шинэчлэл хийхэд асуудал учруулдаг. Зарим тохиолдолд `make buildworld` нь эдгээр хэрэглэгчид эсвэл бүлгүүд байгаа эсэхийг шалгана.

Үүний нэг жишээ нь `smmsp` хэрэглэгч нэмэгдсэн тохиолдол юм. man:mtree[8] нь [.filename]#/var/spool/clientmqueue#-г үүсгэхийг оролдох үед хэрэглэгчийн суулгалтын процесс энэ асуудлаас болж амжилтгүй болж байсан.

Үүний шийдэл нь man:mergemaster[8]-г ертөнцийг бүтээхээс урд `-p` тохируулгатай ажиллуулах явдал юм. Энэ нь `buildworld` эсвэл `installworld` тушаалыг амжилттай болгоход зөвхөн шаардлагатай файлуудыг харьцуулдаг.

[TIP]
====

Хэрэв та ялангуяа хэтэрхий санаа зовж байгаа бол тухайн бүлэгт харьяалагдаж байгаа нэрийг нь өөрчилж байгаа эсвэл устгаж байгаа ямар файлууд байгааг өөрийн системээс шалгаарай:

[source,bash]
....
# find / -group GID -print
....

дээрх нь _GID_ (энэ бүлгийн нэр байж болно эсвэл бүлгийн тоон ID байж болно) бүлгийн эзэмшдэг файлуудыг харуулна.
====

[[makeworld-singleuser]]
=== Ганц хэрэглэгчийн горимд шилж

Та системийг ганц хэрэглэгчийн горимд эмхэтгэхийг хүсэж болох юм. Энэ нь шинэчлэлтийг арай илүү хурдасгах илэрхий ашиг тустайгаас гадна системийг дахин суулгах нь системийн стандарт хоёртын файлууд, libraries буюу туслах сангууд, оруулгын файлууд гэх зэрэг системийн маш олон чухал файлуудыг хөнддөг. Ажиллаж байгаа систем дээр эдгээрийг өөрчлөх нь (ялангуяа хэрэв тухайн үед таны систем дээр идэвхтэй хэрэглэгчид байвал) гай төвгийг өөрөө эрж байна гэсэн үг юм.

Өөр нэг арга бол системийг олон хэрэглэгчийн горимд эмхэтгэж дараа нь суулгахдаа ганц хэрэглэгчийн горимд шилжин хийх явдал юм. Хэрэв та энэ замаар хийхийг хүсэж байвал бүтээлт дуустал дараах алхмууд дээр хүлээж байгаарай. Та `installkernel` эсвэл `installworld` хийх хүртлээ ганц хэрэглэгчийн горимд оролгүйгээр хүлээж байж болно.

Супер хэрэглэгч болоод та доор дурдсаныг:

[source,bash]
....
# shutdown now
....

ажиллаж байгаа системээс ганц хэрэглэгчийн горим уруу оруулахдаа ажиллуулж болно.

Өөр нэг арга нь системийг дахин ачаалаад ачаалалтын тушаал хүлээх мөрөн дээр "single user буюу ганц хэрэглэгч" тохируулгыг сонгоорой. Ингэхэд систем ганц хэрэглэгчийг ачаална. Бүрхүүлийн тушаал хүлээх мөрөнд та доор дурдсан тушаалуудыг ажиллуулах шаардлагатай:

[source,bash]
....
# fsck -p
# mount -u /
# mount -a -t ufs
# swapon -a
....

Энэ нь файлын системүүдийг шалгаж [.filename]#/#-г дахин унших/бичихээр дахин холбож бусад бүх UFS файлын системүүдийг [.filename]#/etc/fstab#-д заасны дагуу холбон дараа нь swap-ийг идэмвхжүүлэх болно.

[NOTE]
====
Хэрэв таны CMOS цаг нь GMT биш локал хугацаагаар тохируулагдсан бол (хэрэв man:date[1] тушаалын гаралт зөв цаг болон бүсийг харуулахгүй бол энэ нь үнэн) та дараах тушаалыг бас ажиллуулах хэрэгтэй болж болох юм:

[source,bash]
....
# adjkerntz -i
....

Энэ нь таны локал цагийн бүсийн тохируулгуудыг зөвөөр тохируулж өгдөг - үүнийг хийхгүй бол та дараа нь зарим асуудлуудтай тулгарч магадгүй. 
====

[[cleaning-usr-obj]]
=== [.filename]#/usr/obj#-г устга

Системийн хэсгүүд дахин бүтээгдсэнийхээ дараа (анхдагчаар) [.filename]#/usr/obj# дахь сангуудад байршдаг. Эдгээр сангууд нь [.filename]#/usr/src# дотор байгааг халхалдаг.

Та `make buildworld` процессийг хурдасгаж болох бөгөөд энэ санг бас устгаснаар хамаарлын зовлонгуудаас өөрийгөө магадгүй аврах болно.

[.filename]#/usr/obj# доторх зарим файлуудад immutable буюу хувиршгүй туг тавигдсан (дэлгэрэнгүй мэдээллийг man:chflags[1]-с үзнэ үү ) байж болох бөгөөд түүнийг эхлээд арилгах хэрэгтэй.

[source,bash]
....
# cd /usr/obj
# chflags -R noschg *
# rm -rf *
....

[[updating-upgrading-compilebase]]
=== Үндсэн системийг дахин эмхэтгэ

==== Гаралтыг хадгалах нь

man:make[1]-г ажиллуулахдаа гарах үр дүнг өөр файл уруу хадгалах нь зүйтэй юм. Хэрэв ямар нэг юм болохоо боливол та алдааны мэдэгдлийн хуулбартай байх болно. Энэ нь танд юу буруутсаныг шинжлэхэд чинь тус болохгүй байж болох боловч та өөрийн энэ асуудлаа FreeBSD-ийн аль нэг захидлын жагсаалт уруу илгээсэн тохиолдолд бусдад тус болж болох юм.

Үүнийг хамгийн амраар хийхийн тулд man:script[1] тушаалыг бүх гаралтыг хадгалах файлын нэрийг заасан параметрийн хамтаар ашиглана. Та үүнийг ертөнцийг дахин бүтээхээс өмнөхөн нэн даруй хийж дараа нь процесс дууссаны дараа `exit` гэж бичиж гарна.

[source,bash]
....
# script /var/tmp/mw.out
Script started, output file is /var/tmp/mw.out
# make TARGET
… compile, compile, compile …
# exit
Script done, …
....

Хэрэв та үүнийг хийх бол гаралтыг [.filename]#/tmp# дотор _битгий_ хадгалаарай. Энэ сан нь таныг дахин ачаалсны дараа цэвэрлэгдэж болох юм. Энэ файлыг хадгалах арай илүү боломжийн газар нь [.filename]#/var/tmp# (өмнөх жишээн дээрх шиг) эсвэл `root` хэрэглэгчийн гэр сан байж болох юм.

[[make-buildworld]]
==== Үндсэн системийг эмхэтгэ

Та [.filename]#/usr/src# сан дотор байх шаардлагатай:

[source,bash]
....
# cd /usr/src
....

(гэхдээ мэдээж таны код өөр газар байгаа тохиолдолд тэр сан уруугаа орох хэрэгтэй).

Ертөнцийг дахин бүтээхдээ та man:make[1] тушаалыг ашиглана. Энэ тушаал нь FreeBSD-ийн агуулсан програмууд ямар дарааллаар дахин хэрхэн бүтээгдэх зэргийг тайлбарласан [.filename]#Makefile# файлаас заавруудыг уншдаг.

Таны бичих тушаалын мөрийн ерөнхий хэлбэр нь дараах байдлаар байна:

[source,bash]
....
# make -x -DVARIABLE target
....

Энэ жишээн дээр `-_x_` нь man:make[1] уруу таны дамжуулах тохируулга юм. man:make[1]-н гарын авлагын хуудаснаас та дамжуулж болох тохируулгуудын жишээг үзнэ үү.

`-D_VARIABLE_` тохируулга нь [.filename]#Makefile# уруу хувьсагч дамжуулж байна. [.filename]#Makefile#-ийн ажиллагаа эдгээр хувьсагчуудаар хянагдана. Эдгээр нь [.filename]#/etc/make.conf# дотор зааж өгсөн хувьсагчуудтай адил бөгөөд энэ нь тэдгээрийг тохируулах бас нэг өөр арга юм.

[source,bash]
....
# make -DNO_PROFILE target
....

тушаал нь профиль хийгдсэн сангууд бүтээгдэх ёсгүйг заах өөр нэг арга бөгөөд энэ нь [.filename]#/etc/make.conf# дахь дараах

[.programlisting]
....
NO_PROFILE=    true 	#    Avoid compiling profiled libraries
....

мөрд харгалзах юм.

_target_ нь man:make[1]-д таны юу хийхийг хэлж өгдөг. [.filename]#Makefile# болгон өөр өөр "targets буюу даалгаврын төрлүүдийг" тодорхойлдог бөгөөд таны сонгосон төрөл юу болохыг тодорхойлдог.

Зарим төрлүүд [.filename]#Makefile#-д жагсаагдсан байх бөгөөд гэхдээ эдгээр нь таныг ажиллуулахад зориулагдаагүй. Харин тэдгээр нь системийг дахин бүтээхэд шаардлагатай алхмуудыг хэд хэдэн дэд алхмуудад хуваахын тулд бүтээх процессод хэрэглэгддэг.

Ихэнх тохиолдолд та man:make[1] уруу ямар ч параметр дамжуулах хэрэггүй бөгөөд тэгэхээр таны тушаал дараахтай ижил байж болно:

[source,bash]
....
# make target
....

дээрх _target_ нь олон бүтээх тохируулгуудын нэг болно. Эхний төрөл нь үргэлж `buildworld` байх ёстой.

Нэртэйгээ адилаар `buildworld` нь [.filename]#/usr/obj# дотор бүрэн гүйцэд шинэ модыг бүтээх бөгөөд өөр нэг төрөл болох `installworld` нь энэ модыг тухайн машин дээр суулгадаг.

Тусдаа тохируулгуудтай байх нь хоёр шалтгаанаар маш ач холбогдолтой юм. Нэгдүгээрт энэ нь бүтээлтийг таны ажиллаж байгаа системийн ямар ч хэсэгт нөлөөлөхгүйгээр аюулгүйгээр хийхийг танд зөвшөөрдөг. Бүтээлт нь "өөр дээрээ хийгдэнэ (self hosted)". Ийм болохоор та `buildworld` тушаалыг олон хэрэглэгчийн горимд ажиллаж байгаа машин дээр буруу нөлөөллөөс айлгүйгээр аюулгүйгээр хийж болно. Гэхдээ `installworld` хэсгийн хувьд ганц хэрэглэгчийн горимд хийхийг танд зөвлөдөг.

Хоёрдугаарт энэ нь сүлжээн дэх олон машинуудыг шинэчлэхэд NFS холболтуудыг ашиглахыг танд зөвшөөрдөг. Хэрэв танд гурван машин байгаа бөгөөд `A`, `B` болон `C` машинуудыг шинэчлэхийг хүсвэл `make buildworld` болон `make installworld` тушаалыг `A` дээр ажиллуулна. Дараа нь `B` болон `C` машинууд `A` дээрх [.filename]#/usr/src# болон [.filename]#/usr/obj# сангуудыг NFS холболт хийн `make installworld`-г ажиллуулж бүтээлтийн үр дүнг `B` болон `C` дээр суулгаж болох юм.

`world` төрөл байсаар байгаа хэдий ч танд түүнийг ашиглахгүй байхыг зөвлөж байна.

Дараах тушаалыг ажиллуул

[source,bash]
....
# make buildworld
....

Хэд хэдэн зэрэгцээ процессуудыг үүсгэх `-j` тохируулгыг `make` тушаалд зааж өгөх боломжтой. Энэ нь олон CPU-тэй машинууд дээр хамгийн их ашигтай. Гэхдээ эмхэтгэх процессийн ихэнх нь CPU дээр биш IO дээр ажилладаг болохоор энэ нь бас нэг CPU-тэй машинууд дээр ашигтай юм.

Ердийн нэг CPU-тэй машин дээр та доор дурдсаныг ажиллуулж болох юм:

[source,bash]
....
# make -j4 buildworld
....

man:make[1] нь 4 хүртэлх процессийг нэгэн зэрэг ажиллуулах юм. Захидлын жагсаалтуудад илгээгдсэн туршлагаас харахад энэ нь ерөнхийдөө ажиллагааг хамгийн сайн хангаж хурдасгадаг байна.

Хэрэв та олон CPU машинтай бөгөөд SMP тохируулагдсан цөм ашиглаж байвал утгыг 6-аас 10 хүртэл болгож хэр хурдсаж байгааг хараарай.

==== Хугацаа

Бүтээхэд шаардагдах хугацаанд олон хүчин зүйлс нөлөөлдөг, гэхдээ нэлээн сүүлийн үеийн машинуудын хувьд FreeBSD-STABLE модыг процессийн явцад ямар нэгэн заль мэх эсвэл дөт зам ашиглалгүйгээр бүтээхэд зөвхөн нэг юм уу эсвэл хоёр цаг л шаардагдах болох юм. FreeBSD-CURRENT модны хувьд арай удах болов уу.

[[new-kernel]]
=== Шинэ цөмийг эмхэтгэж суулга

Та өөрийн шинэ системийн давуу талыг бүгдийг нь авахын тулд цөмөө дахин эмхэтгэх хэрэгтэй. Зарим нэг санах ойн бүтцүүд өөрчлөгдсөн байх талтай бөгөөд man:ps[1] болон man:top[1] зэрэг програмууд нь цөм болон эх кодын хувилбарууд адил болтол ажилладаггүй болохоор эмхэтгэх нь үнэндээ чухал хэрэгцээтэй юм.

Үүнийг хамгийн хялбараар аюулгүйгээр хийхийн тулд [.filename]#GENERIC# дээр тулгуурласан цөмийг бүтээж суулгах явдал юм. [.filename]#GENERIC# нь таны системийн хувьд хэрэгцээтэй төхөөрөмжүүдийг агуулаагүй байж болох боловч таны системийг ядаж ганц хэрэглэгчийн горимд ачаалахад шаардлагатай бүгдийг агуулсан байх ёстой. Шинэ систем зөв ажиллуулахад энэ сайн тест болж өгдөг. [.filename]#GENERIC#-с ачаалж таны систем ажиллаж байгааг шалгасны дараа та өөрийн ердийн цөмийн тохиргооны файл дээр тулгуурлан шинэ цөмөө бүтээж болох юм.

FreeBSD дээр шинэ цөм бүтээхээсээ өмнө <<make-buildworld,ертөнцийг бүтээх>> нь чухал юм.

[NOTE]
====
Хэрэв та өөрчлөн тохируулсан цөмийг бүтээхийг хүсэж тохиргооны файлаа аль хэдийн үүсгэсэн бол доор дурдсантай адилаар `KERNCONF=MYKERNEL` гэж ашиглаарай:

[source,bash]
....
# cd /usr/src
# make buildkernel KERNCONF=MYKERNEL
# make installkernel KERNCONF=MYKERNEL
....

====

Хэрэв та `kern.securelevel` хувьсагчийг 1-ээс дээш болгон ихэсгэсэн _бөгөөд_ `noschg` эсвэл түүнтэй адил тугуудыг өөрийн цөмийн хоёртын файлд тавьсан бол `installkernel` хийхийн тулд та ганц хэрэглэгчийн горимд шилжин орох шаардлагатай байж болох юм. Үгүй бол та энэ хоёр тушаалыг олон хэрэглэгчийн горимоос ямар ч асуудалгүйгээр ажиллуулах ёстой. `kern.securelevel`-ийн талаар дэлгэрэнгүйг man:init[8] болон төрөл бүрийн файлын тугуудын талаар дэлгэрэнгүйг man:chflags[1] гарын авлагын хуудаснуудаас үзнэ үү.

[[new-kernel-singleuser]]
=== Ганц хэрэглэгчийн горим уруу дахин ачаалан ор

Та шинэ цөмийн ажиллагааг шалгахын тулд ганц хэрэглэгчийн горимд дахин ачаалан орох хэрэгтэй. Үүнийг <<makeworld-singleuser>> дахь заавруудын дагуу хийнэ.

[[make-installworld]]
=== Шинэ системийн хоёртын файлуудыг суулга

Та шинэ системийн хоёртын файлуудыг суулгахын тулд `installworld` тушаалыг ашиглах шаардлагатай.

Доор дурдсаныг ажиллуулна

[source,bash]
....
# cd /usr/src
# make installworld
....

[NOTE]
====
Хэрэв та `make buildworld` тушаалын мөрөнд хувьсагчуудыг зааж өгсөн бол тэдгээр хувьсагчуудыг `make installworld` тушаалын мөрөнд бас адилаар зааж өгөх хэрэгтэй. Энэ бусад тохируулгуудын хувьд заавал шаардлагатай биш байж болох юм; жишээ нь `-j` тохируулга `installworld`-той цуг хэзээ ч хэрэглэгдэх ёсгүй.

Жишээ нь хэрэв та доор дурдсаныг ажиллуулсан бол:

[source,bash]
....
# make -DNO_PROFILE buildworld
....

хоёртын файлуудыг дараах тушаалаар суулгана:

[source,bash]
....
# make -DNO_PROFILE installworld
....

ингэхгүй бол `make buildworld` тушаалын ажиллах явцад бүтээгдээгүй профиль хийгдсэн сангуудыг (libraries) суулгахыг оролдох болно.
====

[[post-installworld-updates]]
=== `make installworld` тушаалаар шинэчлэгдээгүй файлуудыг шинэчил

Ертөнцийг дахин бүтээх нь зарим нэг сангуудыг (ялангуяа [.filename]#/etc#, [.filename]#/var# болон [.filename]#/usr#) шинэ болон өөрчлөгдсөн тохиргооны файлуудаар шинэчилдэггүй.

Эдгээр файлуудыг хамгийн амархнаар шинэчлэх арга нь man:mergemaster[8]-г ашиглах явдал юм, гэхдээ та хэрэв хүсвэл үүнийг гараар ажиллуулах боломжтой юм. Аль ч аргыг сонголоо гэсэн ямар нэгэн зүйл буруутсан тохиолдолд сэргээх боломжтойгоор [.filename]#/etc#-г нөөцөлж авах нь зүйтэй юм.

[[mergemaster]]
==== `mergemaster`

man:mergemaster[8] хэрэгсэл нь [.filename]#/etc# дэх таны тохиргооны файлууд болон [.filename]#/usr/src/etc# эх модон дахь тохиргооны файлуудын ялгааг тодорхойлоход танд тусалдаг Bourne скрипт юм. Энэ нь системийн тохиргооны файлуудыг эх модон дахь тохиргооны файлуудаар шинэчлэх зориулалттай бидний зөвлөдөг шийдэл юм.

Эхлэхийн тулд өөрийн тушаал оруулах мөрөнд ердөө л `mergemaster`-г бичиж түүний эхлэхийг нь хараарай. `mergemaster` нь түр зуурын root орчныг [.filename]#/#-с доошлуулан бүтээж төрөл бүрийн системийн тохиргооны файлуудаар дамждаг. Тэдгээр файлууд нь таны системд суулгагдсан файлуудтай харьцуулагддаг. Энэ үед хоорондоо ялгаатай файлууд man:diff[1] хэлбэрээр үзүүлэгддэг бөгөөд `+` тэмдэгтээр нэмэгдсэн эсвэл өөрчлөгдсөн мөрүүдийг `-` тэмдэгтээр устгагдсан эсвэл шинэ мөрөөр солигдсон мөрүүдийг харуулдаг. man:diff[1]-н синтакс болон файлын өөрчлөлтүүдийг хэрхэн үзүүлдэг талаар дэлгэрэнгүй мэдээллийг man:diff[1] гарын авлагын хуудаснаас үзнэ үү.

man:mergemaster[8] нь зөрчилдөөнүүдийг үзүүлсэн файл болгоныг харуулдаг бөгөөд энэ үед танд шинэ файлыг устгах (түр зуурын файл гэгддэг), түр зуурын файлыг өөрчлөлгүйгээр суулгах, суусан байгаа файлтай түр зуурын файлыг нийлүүлэх эсвэл man:diff[1]-н гаралтыг дахин харах сонголтыг үзүүлэх болно.

Түр зуурын файлыг устгахыг сонгосноор бид одоо байгаа файлаа хэвээр өөрчлөлгүй үлдээж шинэ хувилбарыг устгахыг хүсэж байгаагаа man:mergemaster[8]-д хэлж байна гэсэн үг юм. Хэрэв та одоо байгаа файлаа өөрчлөх шалтгааныг олж харахгүй байгаагаас бусад тохиолдолд энэ сонголтыг хийхийг зөвлөдөггүй. Та ямар ч үед man:mergemaster[8] тушаал хүлээх мөрөн дээр kbd:[?] гэж бичин тусламж авч болох юм. Хэрэв хэрэглэгч файлыг орхихоор сонгосон бол энэ нь бусад бүх файлуудтай ажилсны дараа дахин үзүүлэгдэн хэрэглэгчээс тушаал хүлээх болно.

Өөрчлөгдөөгүй түр зуурын файлыг суулгахыг сонгосноор одоо байгаа файлыг шинээр сольдог. Ихэнх өөрчлөгдөөгүй файлуудын хувьд энэ нь хамгийн шилдэг сонголт юм.

Файлыг нийлүүлэхийг сонгосноор текст засварлагч болон хоёр файлын агуулгыг танд харуулах болно. Та дэлгэцийн хоёр талд байрласан тэдгээр хоёр файлыг хоёуланг нь шалган аль аль талаас нь хэрэгтэй хэсгүүдийг сонгон эцсийн бүтээгдэхүүн гаргаж аван нийлүүлж болно. Файлууд нь дэлгэцийн хоёр талд байрлан харьцуулагдах явцад kbd:[l] түлхүүр таны зүүн талын агуулгыг сонгодог бол kbd:[r] түлхүүр нь таны баруун тал дахь агуулгыг сонгох юм. Гарах эцсийн үр дүн нь хоёр файлын хоёулангийн хэсгүүдийг агуулсан файл болох бөгөөд түүнийг дараа нь суулгах боломжтой болох юм. Энэ сонголтыг хэрэглэгчийн тохиргоонуудад хийгдсэн өөрчлөлтүүдтэй файлуудын хувьд хэрэглэх нь зуршил болжээ.

man:diff[1]-ээс гарах үр дүнг дахин харахыг сонгосноор өмнө нь man:mergemaster[8] файлын өөрчлөлтүүдийг харуулан таны сонголтыг хүлээсний нэгэн адилыг дахин харуулдаг.

man:mergemaster[8] системийн файлуудтай ажиллаж дууссаны дараа танаас бусад сонголтуудыг хийхийг хүлээдэг. man:mergemaster[8] тушаал нууц үгийн файлыг дахин бүтээхийг хүсэж байгаа эсэхийг танаас асууж үлдсэн түр зуурын файлуудыг устгах сонголтыг үзүүлэн дуусдаг.

==== Гараар шинэчлэх

Хэрэв та гараар шинэчлэхийг хүсвэл гэхдээ та [.filename]#/usr/src/etc# сангаас [.filename]#/etc# сан уруу файлуудыг зүгээр л дарж хуулж ажиллуулж чадахгүй. Зарим файлуудыг эхлээд "суулгах" хэрэгтэй. Учир нь [.filename]#/usr/src/etc# сан таны [.filename]#/etc# сангийн хуулбар шиг байхаар _харагддагүй_. Мөн [.filename]#/usr/src/etc# санд байдаггүй хэрнээ [.filename]#/etc# сан дотор байх шаардлагатай зарим файлууд байдаг.

Хэрэв та man:mergemaster[8] (зөвлөсний дагуу) ашиглаж байвал та <<updating-upgrading-rebooting,дагаагийн хэсэг>> уруу орж болно.

Үүнийг гараар хамгийн хялбар аргаар хийхийн тулд файлуудыг шинэ сан уруу суулгаж нэг бүрчлэн өөрчлөлтүүдийг хайн ажиллах хэрэгтэй.

[WARNING]
.Өөрт байгаа [.filename]#/etc#-г нөөцөл
====
Онолоор бол автоматаар энэ санд юу ч хүрдэггүй ч үүнд үргэлж итгэлтэй байх хэрэгтэй. Тэгэхээр өөрийн байгаа [.filename]#/etc# санг хаа нэг аюулгүй газар хуулах хэрэгтэй. Доорхтой адилаар:

[source,bash]
....
# cp -Rp /etc /etc.old
....

`-R` нь рекурсив хуулбар хийх бөгөөд `-p` нь файлуудын хугацаа, эзэмшигч гэх мэтийг хадгалдаг.
====

Та шинэ [.filename]#/etc# болон бусад файлуудыг суулгахын тулд хоосон сангууд бүтээх хэрэгтэй. [.filename]#/var/tmp/root# нь боломжийн сонголт болох бөгөөд энэ сангийн доор хэд хэдэн дэд сангууд бас шаардлагатай болно.

[source,bash]
....
# mkdir /var/tmp/root
# cd /usr/src/etc
# make DESTDIR=/var/tmp/root distrib-dirs distribution
....

Энэ нь шаардлагатай сангийн бүтцийг бүтээж файлуудыг суулгадаг. [.filename]#/var/tmp/root# дотор үүсгэгдсэн олон дэд сангууд хоосон бөгөөд тэдгээрийг устгах шаардлагатай байдаг. Үүнийг хамгийн хялбараар хийхийн тулд:

[source,bash]
....
# cd /var/tmp/root
# find -d . -type d | xargs rmdir 2>/dev/null
....

Энэ нь бүх хоосон сангуудыг устгана. (Хоосон биш сангуудын тухай анхааруулгуудыг гаргахгүйн тулд стандарт алдаа нь [.filename]#/dev/null# уруу илгээгддэг.)

Одоо [.filename]#/var/tmp/root# нь [.filename]#/#-с доор байрлах тохирох байрлалуудад байршуулах ёстой бүх файлуудыг агуулсан байх болно. Та одоо эдгээр файл бүрийг шалгаж танд байгаа файлуудаас хэрхэн ялгаатай болохыг тогтоох хэрэгтэй.

[.filename]#/var/tmp/root# дотор суулгагдсан зарим файлуудын нэр урдаа "." тэмдэгттэй байдгийг анхаарна уу. Энэ баримтыг бичиж байх үед ийм файлуудтай адил файлууд [.filename]#/var/tmp/root/# болон [.filename]#/var/tmp/root/root/# сан дахь бүрхүүлийн эхлүүлэх файлууд байсан, гэхдээ (таны хэзээ үүнийг уншиж байгаагаас хамаарч) өөр бусад файлууд байхыг үгүйсгэхгүй. Тэдгээрийг олж харахын тулд `ls -a` тушаалыг заавал ашиглаарай.

Үүнийг хамгийн хялбар аргаар хийж хоёр файлыг харьцуулахын тулд man:diff[1] тушаалыг ашиглах явдал юм:

[source,bash]
....
# diff /etc/shells /var/tmp/root/etc/shells
....

Энэ нь таны [.filename]#/etc/shells# файл болон шинэ [.filename]#/var/tmp/root/etc/shells# файлын хоорондын ялгааг харуулна. Эдгээрийг ашиглаж өөрийн хийсэн өөрчлөлтүүдийг нийлүүлэх эсвэл өөрийн хуучин файл дээрээс хуулах эсэхээ шийдээрэй.

[TIP]
.Хувилбаруудын Хоорондох Ялгаануудыг Хялбараар Харьцуулахын Тулд Та Шинэ Root Сангаа Тухайн Үеийн Хугацаагаар Нэрлээрэй
====
Ертөнцийг байнга дахин бүтээнэ гэдэг нь [.filename]#/etc#-г та бас байнга шинэчилнэ гэсэн үг бөгөөд энэ нь ердөө л жижиг хэвшмэл ажил юм.

Та энэ процессийг [.filename]#/etc# уруу нийлүүлсэн өөрийн хамгийн сүүлийн өөрчлөгдсөн файлуудыг хадгалснаар хурдасгаж болох юм. Дараах процедур үүнийг хэрхэн хийж болох нэг санааг өгч байна.

[.procedure]
======
. Ертөнцийг жирийнээр бүтээ. [.filename]#/etc# болон бусад сангуудыг шинэчлэхийг хүсэхдээ тухайн цаг дээр тулгуурласан нэр бүхий санг өг. Хэрэв та үүнийг 1998 оны 2 сарын 14-нд хийж байгаа бол дараах байдлаар хийнэ:
+
[source,bash]
....
# mkdir /var/tmp/root-19980214
# cd /usr/src/etc
# make DESTDIR=/var/tmp/root-19980214 \
    distrib-dirs distribution
....

. Энэ сангийн өөрчлөлтүүдийг дээр дурдсаны дагуу нийлүүл.
+ 
Та дууссаныхаа дараа [.filename]#/var/tmp/root-19980214# санг _битгий_ устгаарай.
. Та эхийн хамгийн сүүлийн хувилбарыг татан авч дахин бүтээхдээ 1-р алхмыг дага. Энэ нь танд шинэ сан өгөх бөгөөд [.filename]#/var/tmp/root-19980221# гэж нэрлэгдсэн байж болох юм (хэрэв та шинэчлэлтүүдийг хийхдээ долоо хоног хүлээсэн бол).
. Та одоо man:diff[1] ашиглан хоёр сангийн хооронд рекурсив diff үүсгэж долоо хоногийн хооронд хийгдсэн өөрчлөлтүүдийг харж болно:
+
[source,bash]
....
# cd /var/tmp
# diff -r root-19980214 root-19980221
....
+ 
Ихэнхдээ энэ нь [.filename]#/var/tmp/root-19980221/etc# болон [.filename]#/etc# хоёрын хоорондох өөрчлөлтүүдийг бодох юм бол харьцангуй бага өөрчлөлтүүд байдаг. Өөрчлөлтүүд нь арай бага болохоор тэдгээр өөрчлөлтүүдийг өөрийн [.filename]#/etc# сан уруу шилжүүлэх нь илүү хялбар байдаг.
. Та одоо хоёр [.filename]#/var/tmp/root-*# сангуудын аль хуучныг устгаж болно:
+
[source,bash]
....
# rm -rf /var/tmp/root-19980214
....
+
. [.filename]#/etc# уруу өөрчлөлтүүдийг нийлүүлэх болгондоо энэ процессийг давтах хэрэгтэй.
======

Та man:date[1]-г ашиглан сангийн нэрсийг автоматаар үүсгэж болно:

[source,bash]
....
# mkdir /var/tmp/root-`date "+%Y%m%d"`
....

====

[[updating-upgrading-rebooting]]
=== Дахин ачаалах нь

Та ерөнхийдөө ингээд хийгээд дуусч байна. Та бүх зүйл байх ёстой байрандаа байгаа эсэхийг шалгасныхаа дараа системийг дахин ачаалж болно. Энгийн man:shutdown[8] үүнийг хийх болно:

[source,bash]
....
# shutdown -r now
....

=== Дууслаа

Одоо та өөрийн FreeBSD системийг амжилттайгаар шинэчлээд дууссан байх ёстой. Баяр хүргэе.

Хэрэв юмс шал буруугаар эргэвэл системийн тухайн хэсгийг дахин бүтээхэд амархан байдаг. Жишээ нь хэрэв та шинэчлэлтийн явцад эсвэл [.filename]#/etc#-г нийлүүлэх явцад санамсаргүйгээр [.filename]#/etc/magic# файлыг устгасан бол man:file[1] тушаал ажиллахаа больно. Ийм тохиолдолд дараах засварыг ажиллуулж болох юм:

[source,bash]
....
# cd /usr/src/usr.bin/file
# make all install
....

[[updating-questions]]
=== Асуултууд

==== Өөрчлөлт бүрт зориулан ертөнцийг дахин бүтээх хэрэгтэй юу?

Үүнд хялбар хариулт байхгүй, учир нь өөрчлөлтийн цаад утга чанараас хамаарна. Жишээ нь хэрэв та CVSup-г дөнгөж ажиллуулахад дараах файлууд шинэчлэгдэж байгааг үзүүлж байгаа бол:

[source,bash]
....
src/games/cribbage/instr.c
src/games/sail/pl_main.c
src/release/sysinstall/config.c
src/release/sysinstall/media.c
src/shared/mk/bsd.port.mk
....

магадгүй бүхэл ертөнцийг дахин бүтээх хэрэггүй байж болох юм. Та тохирох дэд сангууд уруу орж `make all install` гэж тушаалыг өгөөд л болох юм. Хэрэв зарим нэг гол чухал зүйл жишээ нь [.filename]#src/lib/libc/stdlib# өөрчлөгдсөн бол та ертөнцийг эсвэл хамгийн багаар бодоход статикаар холбогдсон (statically linked) түүний тэдгээр хэсгүүдийг дахин бүтээх шаардлагатай болно.

Эцсийн эцэст энэ нь танаас л хамаарна. Та жишээ нь хоёр долоо хоног тутам ертөнцийг дахин бүтээж тэр хоёр долоо хоногийн хугацаанд өөрчлөлтүүдийг хуримтлуулж байгаадаа сэтгэл хангалуун байж болно. Эсвэл та зөвхөн өөрчлөгдсөн зүйлсүүдийг дахин бүтээхийг хүсэж магадгүй бөгөөд бүх хамаарлуудыг шийднэ гэдэгтээ итгэлтэй байх хэрэгтэй.

Тэгээд мэдээж энэ бүхэн таны ямар давтамжтайгаар шинэчлэхийг хүсдэг болон FreeBSD-STABLE эсвэл FreeBSD-CURRENT-ийн алийг дагаж байгаагаас хамаарах болно.

==== Миний эмхэтгэл маш олон дохио 11 дохио 11 (эсвэл бусад дохионы дугаар) алдаагаар амжилтгүй болсон. Юу болсон юм бол?

Энэ нь ихэвчлэн тоног төхөөрөмжийн асуудлыг илэрхийлдэг. Ертөнцийг (дахин) бүтээх нь өөрийн тоног төхөөрөмжийг ачаалах тест хийх үр дүнтэй арга бөгөөд удаа дараа санах ойн асуудлууд байвал тэдгээрийг илрүүлдэг. Эмхэтгэгч нь сонин/хачин дохионуудыг хүлээн авч ид шидийн байдлаар амжилтгүй болсноор тэдгээр асуудлууд нь өөрсдийгөө зарлан тунхагладаг.

Хэрэв та бүтээлтийг дахин эхлүүлээд тэр нь процессийн өөр өөр хэсэгт амжилтгүй болж байвал энэ нь үүнийг тодоор зааж байна гэсэн үг юм.

Энэ тохиолдолд та өөрийн машин дахь бүрэлдэхүүн хэсгүүдээ өөрчлөн нэгээс нөгөөд сольж тавин аль нь ажиллахгүй байгааг олохоос өөр зүйл хийж чадахгүй л болов уу.

==== Би дууссаныхаа дараа /usr/obj-г устгаж болох уу?

Товчхондоо бол болно.

[.filename]#/usr/obj# нь эмхэтгэх үед бүтээгдсэн бүх обьект файлуудыг агуулдаг. Жирийн үед `make buildworld` процессийн эхний алхмуудын нэг нь энэ санг устгаад цоо шинээр эхлэх явдал юм. Энэ тохиолдолд [.filename]#/usr/obj#-г дууссаныхаа дараа байлгаад байх нь ухаалаг биш бөгөөд үүнийг устгаснаар ихээхэн хэмжээний дискний зайг суллах болно (одоогоор 2 GB орчим).

Гэхдээ хэрэв та юу хийж байгаагаа мэдэж байгаа бол `make buildworld` хийхдээ энэ алхмыг алгасаж болно. Энэ нь дараа дараагийн бүтээлтийг илүү хурдасгадаг бөгөөд учир нь ихэнх эхүүд дахин эмхэтгэх шаардлагагүй байдаг. Үүний сул тал нь баригдашгүй хамаарлын асуудлууд илэрч таны бүтээлтийг хачин байдлаар амжилтгүй болгодог. Хэн нэгэн илүү дөтлөх гэснээсээ болоод амжилтгүй болсныг мэдэлгүй өөрийн бүтээлтийг амжилтгүй болсныг гомдоллосноор FreeBSD-ийн захидлын жагсаалтуудад хий дэмий шуугианыг удаа дараа үүсгэдэг билээ.

==== Тасалдсан бүтээлтүүдийг үргэлжлүүлж болох уу?

Энэ нь асуудлыг олох хүртлээ та хэр хол явснаас хамаарна.

_Ерөнхийдөө_ (энэ нь хэцүү бас хурдан дүрэм биш) `make buildworld` процесс нь үндсэн багажуудын (man:gcc[1], болон man:make[1] зэрэг) болон системийн сангуудын шинэ хуулбаруудыг бүтээдэг. Тэдгээр багажууд болон сангууд нь дараа нь суулгагддаг. Шинэ багажууд болон сангууд дараа нь өөрсдийгөө дахин бүтээхэд ашиглагддаг бөгөөд дахин суулгагддаг. Бүхэл бүтэн систем (одоо man:ls[1] эсвэл man:grep[1] зэрэг ердийн хэрэглэгчийн програмууд) дараа нь шинэ системийн файлуудтайгаар дахин бүтээгддэг.

Хэрэв та сүүлийн шатанд байгаа бөгөөд та үүнийг мэдэж байгаа бол (та хадгалж байгаа гаралтаас харсан болохоор) та дараах тушаалыг ажиллуулж (бараг л аюулгүйгээр) болно:

[source,bash]
....
... fix the problem ...
# cd /usr/src
# make -DNO_CLEAN all
....

Энэ нь өмнөх `make buildworld` тушаалын хийснийг буцаахгүй.

Хэрэв та доорх мэдэгдлийг :

[source,bash]
....
--------------------------------------------------------------
Building everything..
--------------------------------------------------------------
....

`make buildworld` тушаалын гаралт дээр харсан бол магадгүй тэгж хийх нь аюулгүй байж болох юм.

Хэрэв та тийм мэдэгдэл харахгүй байгаа бол эсвэл та итгэлтэй биш байгаа бол харамсахаасаа өмнө аюулгүй байдлыг бодож бүтээлтийг бүр эхнээс нь дахин эхлүүлсэн нь дээр юм.

==== Би ертөнцийг бүтээхийг хэрхэн хурдасгах вэ?

* Ганц хэрэглэгчийн горимд ажиллуул.
* [.filename]#/usr/src# болон [.filename]#/usr/obj# сангуудыг тус тусдаа байх дискнүүд дээр тус тусдаа байх файлын системүүд дээр байрлуул. Хэрэв боломжтой бол эдгээр дискнүүдийг тус тусад нь дискний хянагчууд дээр байрлуул.
* man:ccd[4] (нийлүүлсэн дискний драйвер) төхөөрөмж ашиглан эдгээр файлын системүүдийг олон дискнүүдийн дагуу байрлуулах нь бас арай илүү хурдасгах юм.
* Профиль хийгдэхийг ([.filename]#/etc/make.conf# файлд "NO_PROFILE=true" гэж зааж өг) болиул. Танд энэ бараг гарцаагүй хэрэггүй.
* `-j__n__` тохируулгыг man:make[1]-д дамжуулж олон процессийг зэрэгцээгээр ажиллуул. Энэ нь танд ганц эсвэл олон процессортой машин аль нь ч байсан ялгаагүйгээр ихэвчлэн тусалдаг.
* [.filename]#/usr/src#-г агуулж байгаа файлын систем `noatime` тохируулгаар холболт хийгдэж (эсвэл салгагдаж) болно. Энэ нь файлын систем файл уруу хандах хандалтын хугацааг бүртгэхийг болиулдаг. Танд магадгүй энэ мэдээлэл бараг л хэрэггүй биз ээ.
+
[source,bash]
....
# mount -u -o noatime /usr/src
....
+
[WARNING]
====

Энэ жишээ [.filename]#/usr/src# нь өөрийн файлын систем дээр байгаа гэж тооцож байгаа болно. Хэрэв энэ нь тийм биш бол (хэрэв энэ сан жишээ нь [.filename]#/usr#-ийн хэсэг маягаар байгаа бол) та [.filename]#/usr/src#-г биш харин тэр файлын системээ холболтын цэг болгон ашиглах хэрэгтэй.
====

* [.filename]#/usr/obj#-г агуулж байгаа файлын систем `async` тохируулгатай холболт хийгдэж (эсвэл салгагдаж) болно. Энэ нь диск уруу хийх бичилтийг асинхроноор буюу зэрэг биш хийлгэдэг. Өөрөөр хэлбэл бичилт нэн даруй хийгдээд өгөгдөл диск уруу цөөн секундын дараа бичигддэг. Энэ нь бичилтүүдийг бүлэглэхийг зөвшөөрч маш их үр дүнтэйгээр ажиллагааг хурдасгаж болох юм.
+
[WARNING]
====

Энэ тохируулга нь таны файлын системийг илүү эмзэг болгохыг санаарай. Тэжээл тасалдаж машин дахин ачаалах үед файлын систем сэргээж болшгүй төлөвт орох магадлал энэ тохируулгатай байхад илүү байдаг.

Хэрэв [.filename]#/usr/obj# нь энэ файлын систем дээрх цорын ганц зүйл бол энэ асуудал биш юм. Хэрэв танд уг файлын систем дээр өөр, үнэтэй өгөгдөл байгаа бол энэ тохируулгыг идэвхжүүлэхээсээ өмнө өөрийн нөөц чинь шинэ эсэхийг шалгаарай.
====
+
[source,bash]
....
# mount -u -o async /usr/obj
....
+
[WARNING]
====

Дээр дурдсан шиг хэрэв [.filename]#/usr/obj# нь өөрийн файлын систем дээр биш байх юм бол жишээн дээрхийг тохирох холболт хийх цэгийн нэрээр солиорой.
====

==== Хэрэв ямар нэг юм буруутвал би юу хийх вэ?

Таны орчинд өмнөх бүтээлтүүдийн үеийн илүү үлдэгдлүүд байхгүйд үнэхээр итгэлтэй байх хэрэгтэй. Энэ нь их амархан юм.

[source,bash]
....
# chflags -R noschg /usr/obj/usr
# rm -rf /usr/obj/usr
# cd /usr/src
# make cleandir
# make cleandir
....

Тиймээ, `make cleandir` тушаалыг үнэндээ хоёр удаа ажиллуулах шаардлагатай.

Тэгээд `make buildworld` тушаалыг эхлүүлж бүх процессийг дахин эхлүүл.

Хэрэв та асуудалтай хэвээр байгаа бол алдаа болон `uname -a` тушаалын дүнг {freebsd-questions} уруу явуулаарай. Өөрийн тохиргооныхоо талаар бусад асуултанд хариулахад бэлэн байгаарай!

[[make-delete-old]]
== Хуучин файлууд, хавтаснууд болон сангуудыг устгах

FreeBSD хөгжүүлэлтийн явцад файлууд болон тэдгээрийн агуулга үе үе хуучирдаг.Тэдгээрийн үүрэг болон боломжууд өөр хаа нэгтээ хийгдсэн юм уу эсвэл сангийн хувилбарын дугаар өөрчлөгдсөн юм уу эсвэл системээс бүрмөсөн хасагдсанаас болоод тийм байж болох юм. Эдгээрт хуучин файлууд, сангууд болон хавтаснууд ордог бөгөөд эдгээрийг системийг шинэчлэхдээ устгах ёстой. Энэ нь хэрэглэгчийн хувьд хадгалах (болон нөөц) төхөөрөмж дээр хэрэгцээгүй зай эзлээд байгаа хуучин файлуудаар систем дүүрэхгүй байх ашигтай юм. Үүнээс гадна хуучин сан аюулгүй байдлын болон найдвартай ажиллагааны хувьд асуудалтай байсан бол та өөрийн системийг аюулгүй болгож хуучин сангаас болоод ажиллахаа болиод байсан асуудлаас сэргийлэхийн тулд шинэ сан руу шинэчлэх хэрэгтэй. Хуучин гэгдсэн файлууд, хавтаснууд, сангуудын жагсаалт [.filename]#/usr/src/ObsoleteFiles.inc# файлд байдаг. Дараах заавар нь системийг шинэчлэх явцад хуучин файлуудыг устгахад туслах болно.

Таныг <<canonical-build>>-д заасны дагуу явж байгаа гэж энд үзнэ. `make installworld` болон дараагийн `mergemaster` тушаал амжилттай хэрэгжсэний дараа дараах маягаар та хуучин файлууд болон сангуудыг шалгах ёстой:

[source,bash]
....
# cd /usr/src
# make check-old
....

Хэрэв ямар нэг хуучин файл олдвол дараах тушаал ашиглан тэдгээрийг устгаж болно:

[source,bash]
....
# make delete-old
....

[TIP]
====

Түлхүүр үгсийн талаар дэлгэрэнгүйг сонирхож байгаа бол [.filename]#/usr/src/Makefile# файлыг үзнэ үү.
====

Хуучин файл бүрийг устгахын өмнө асууж хариулах дэлгэц гарна. Та энэ дэлгэцийг өнгөрөөж систем эдгээр файлуудыг автоматаар устгахаар тохируулахын тулд `BATCH_DELETE_OLD_FILES` хувьсагчийг дараах байдлаар ашиглана:

[source,bash]
....
# make -DBATCH_DELETE_OLD_FILES delete-old
....

Мөн энэ зорилгод хүрэхийн тулд доорхитой адилаар эдгээр тушаалд `yes` өгч хүрч болно:

[source,bash]
....
# yes|make delete-old
....

.Анхааруулга
[WARNING]
====

Хуучин файлуудыг устгах нь тэдгээр хуучин файлуудаас хамааралтай програмуудыг ажиллахгүй болгоно. Энэ нь ялангуяа хуучин сангуудын хувьд үнэн байдаг. Ихэнх тохиолдолд та `make delete-old-libs` тушаалыг биелүүлэхээсээ өмнө хуучин сан ашиглаж байсан програмууд, портууд эсвэл сангуудыг дахин бүтээх хэрэгтэй.
====

Хуваалцсан сангуудаас хамааралтай эсэхийг шалгадаг хэрэгслүүд package:sysutils/libchk[] эсвэл package:sysutils/bsdadminscripts[] зэрэг портын цуглуулгад байдаг.

Хуучин хуваалцсан сангууд нь шинэ сангуудтай зөрчилдөж болох бөгөөд доорх шиг алдаа өгч болно:

[source,bash]
....
/usr/bin/ld: warning: libz.so.4, needed by /usr/local/lib/libtiff.so, may conflict with libz.so.5
/usr/bin/ld: warning: librpcsvc.so.4, needed by /usr/local/lib/libXext.so, may conflict with librpcsvc.so.5
....

Эдгээр асуудлуудыг шийдэхийн тулд уг санг аль порт суулгасныг олно:

[source,bash]
....
# pkg_info -W  /usr/local/lib/libtiff.so
/usr/local/lib/libtiff.so was installed by package tiff-3.9.4
# pkg_info -W /usr/local/lib/libXext.so
/usr/local/lib/libXext.so was installed by package libXext-1.1.1,1
....

Дараа нь уг портыг deinstall хийгээд дахин бүтээж суулгах хэрэгтэй. Энэ явцыг автоматжуулахын тулд package:ports-mgmt/portmaster[] болон package:ports-mgmt/portupgrade[] хэрэгслийг ашиглаж болно. Бүх портуудыг дахин бүтээсэн гэдэгтээ итгэлтэй болсны дараа хуучин сангуудыг ашиглах хэрэггүй бөгөөд тэдгээрийг дараах тушаал ашиглан устгаж болно:

[source,bash]
....
# make delete-old-libs
....

[[small-lan]]
== Олон машины хувьд дагах нь

Хэрэв та олон машинуудын хувьд ижил эх модыг дагахыг хүсэж бүгдийн хувьд эхийг татан авахуулж бүгдийг дахин бүтээхийг хүсэж байгаа бол энэ нь дискний зай, сүлжээний зурвасын өргөн болон CPU циклүүд зэрэг эх үүсвэрүүдийг үр ашиггүйгээр ашиглахад хүргэхээр санагдаж болох юм. Тиймээ, үүний шийдэл нь нэг машинаар ихэнх ажлыг хийлгэж бусад машинууд нь тэр ажлыг NFS-ээр дамжуулан холбох явдал юм. Энэ хэсэгт ингэж хийх аргыг тайлбарсан.

[[small-lan-preliminaries]]
=== Бэлтгэл ажлууд

Эхлээд хоёртын адил файлуудыг ажиллуулах _build set буюу бүтээх олонлог_ гэж бидний нэрлэх машинуудыг олох хэрэгтэй. Машин бүр өөрчлөн тохируулсан цөмтэй байж болох бөгөөд гэхдээ тэд ижил хэрэглэгчийн талбарын хоёртын файлуудыг ажиллуулж байх ёстой. Тэр олонлогоос __бүтээх машин__ыг сонгох хэрэгтэй. Энэ нь ертөнц болон цөм бүтээгдэх машин байх юм. Туйлын хүслээр бол энэ нь `make buildworld` болон `make buildkernel` тушаалуудыг ажиллуулахад хангалттай нөөц CPU бүхий хурдан машин байх хэрэгтэй. Та мөн үйлдвэрлэлд ашиглахаас өмнө програм хангамжуудыг тест хийдэг _тест машин_ сонгохыг бас хүсэж болох юм. Энэ нь удаан хугацаагаар унтраастай эсвэл зогссон байж болох машин _байх ёстой_. Энэ нь бүтээх машин байж болох юм, гэхдээ заавал биш юм.

Энэ бүтээх олонлог дахь бүх машинууд нь өөр өөрийн машин дээрээсээ ижил цэг дээр [.filename]#/usr/obj# болон [.filename]#/usr/src#-г холболт хийх хэрэгтэй. Туйлын хүслээр бол энэ нь бүтээх машин дээрх хоёр өөр дискнүүд байж болох бөгөөд гэхдээ эдгээр нь уг машин дээр NFS холболт бас хийгдэж болохоор байж болох юм. Хэрэв танд олон бүтээх олонлогууд байгаа бол [.filename]#/usr/src# сан нь нэг бүтээх машин дээр байрлаж бусад дээр нь NFS холболт хийгдсэн байх юм.

Төгсгөлд нь бүтээх олонлогийн бүх машинууд дээрх [.filename]#/etc/make.conf# болон [.filename]#/etc/src.conf# файлууд бүтээх машиныхтай тохирч байгаа эсэхийг шалгаарай. Энэ нь бүтээх олонлогийн машин бүрийн суулгах үндсэн системийн бүх хэсгүүдийг бүтээх машин хийх ёстой гэсэн үг юм. Мөн бүтээх машин бүр өөрийн цөмийн нэрийг [.filename]#/etc/make.conf# файлд `KERNCONF` хувьсагчид заан өгөх ёстой бөгөөд бүтээх машин бүр `KERNCONF` хувьсагчдаа өөрийн цөмийг эхэнд оруулан дараа нь тэдгээрийг жагсаах ёстой байдаг. Бүтээх машин нь машин бүрийн цөмийг бүтээхээр болох юм бол тэдгээрийн тохиргооны файлыг [.filename]#/usr/src/sys/arch/conf# санд агуулсан байх шаардлагатай.

[[small-lan-base-system]]
=== Үндсэн систем

Одоо бүх юм ингэж хийгдсэний дараа та бүгдийг бүтээхэд бэлэн боллоо. Бүтээх машин дээр <<make-buildworld>>-д тайлбарласны дагуу цөм болон ертөнцийг бүтээ, гэхдээ юуг ч битгий суулгаарай. Бүтээлт дууссаны дараа тест машин дээр дөнгөж саяхан бүтээсэн цөмөө суулга. Хэрэв энэ машин нь [.filename]#/usr/src# болон [.filename]#/usr/obj# сангуудыг NFS-ээр холболт хийх гэж байгаа бол та ганц хэрэглэгчийн горимд дахин ачаалахдаа сүлжээг нээж тэдгээрийг холбож өгөх хэрэгтэй. Үүнийг хамгийн хялбараар хийхийн тулд олон хэрэглэгчийн горимд ачаалан `shutdown now` тушаалыг ажиллуулж ганц хэрэглэгчийн горимд орох явдал юм. Тэгэж орсныхоо дараа та шинэ цөм болон ертөнцийг суулгаж жирийн үедээ хийдэг `mergemaster` тушаалыг ажиллуулж болно. Ингэж дууссаныхаа дараа энэ машины хувьд ердийн олон хэрэглэгчийн үйлдлүүдэд дахин ачаалж орно.

Тест машин дээрх бүх зүйлс зөв ажиллаж байгааг мэдсэнийхээ дараа та бүтээх олонлогийн бусад машин бүр дээр шинэ програм хангамж суулгахдаа ижил процедурыг ашиглаарай.

[[small-lan-ports]]
=== Портууд

Үүнтэй адил санааг бас портуудын модонд ашиглаж болно. Эхний чухал алхам бол нөгөө машин дээрх [.filename]#/usr/ports# санг бүтээх олонлогийн бусад машинууд дээр холбож өгөх явдал юм. Дараа нь та [.filename]#/etc/make.conf# файлыг distfiles буюу түгээлтийн файлуудыг хуваалцахаар зөв тохируулж өгч болно. Та `DISTDIR` хувьсагчийг таны NFS холболтуудад заагдсан аль ч `root` хэрэглэгчийн хувьд бичигдэх боломжтой байх нийтлэг хуваалцсан сангаар тохируулах шаардлагатай. Машин бүр `WRKDIRPREFIX` хувьсагчийг локал бүтээх сангаар зааж өгөх хэрэгтэй. Эцэст нь хэрэв та багцуудыг бүтээж түгээх гэж байгаа бол `PACKAGES` хувьсагчийг `DISTDIR` хувьсагчийн нэгэн адил сангаар зааж өгөх хэрэгтэй.
