#
# The FreeBSD Simplified Chinese Project
#
# Original Revision: 1.14
# $FreeBSD$

SUBDIR = arch-handbook
SUBDIR+= handbook
SUBDIR+= porters-handbook

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
