# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

#DOCS=	announce.xml
DOCS=	notes.xml
#DOCS=+	notes.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
