# $FreeBSD: www/ja/releases/2.1.7R/Makefile,v 1.5 2000/11/07 11:37:58 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

#DOCS=	announce.sgml
DOCS=	notes.sgml
#DOCS=+	notes.sgml

### Revision checking
REVCHECK=	YES

.include "${WEB_PREFIX}/share/mk/web.site.mk"
