.\"
.\" Copyright (c) 1996 Joerg Wunsch
.\"
.\" All rights reserved.
.\"
.\" This program is free software.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE DEVELOPERS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" %FreeBSD: src/share/man/man7/clocks.7,v 1.9.2.1 2000/12/08 14:59:18 ru Exp %
.\" jpman %Id: clocks.7,v 1.4 1999/01/21 17:54:55 kuma Stab %
.\" "
.Dd April 1, 1996
.Os
.Dt CLOCKS 7
.Sh 名称
.Nm clocks
.Nd いろいろなシステムタイマ
.Sh 書式
.Fd #include <time.h>
.Sh 解説
.Ql HZ
(ヘルツ) は BSD におけるアプリケーションインタフェースの一部ではありません。
.Pp
周波数の異なるいろいろな実体をもつクロックおよび仮想的 (計時用) なクロック
があります。
.Bl -bullet -offset XXX
.It
スケジューリングクロック。周波数 100 となるはずの実クロックです。
アプリケーションからは参照できません。
.It
統計クロック。周波数 128 となるはずの実クロックです。
アプリケーションから直接参照することはできません。
.It
.Xr clock 3
によって報告されるクロック。
周波数が通常 128 の仮想クロックです。実際の周波数は
.Dv CLOCKS_PER_SEC
マクロによって与えられます。
.Dv CLOCKS_PER_SEC
は浮動小数点値であるかもしれないことに注意してください。
.Fn clock
は
.Fx
での新しいプログラムには使用しないでください。
これは
.Xr getrusage 2
に比較して機能的に劣っていますが、ANSI に適合するために
提供されています。
.Fn getrusage
をコールし、情報と結果を受け渡すことによって実装されています。
.It
.Xr times 3
によって報告されるクロック。
周波数が通常 128 の仮想クロックです。実際の周波数は
.Dv CLK_TCK
マクロ (これは反対されています。使用しないでください。) と
.Fn sysconf _SC_CLK_TCK
と
.Xr sysctl 3
によって与えられます。
この周波数は
.Dv CLOCKS_PER_SEC
とは異なりうることに注意してください。
.Xr times 3
は
.Fx
での新しいプログラムには使用しないでください。
これは
.Fn getrusage
と組み合わせた
.Xr gettimeofday 2
に比較して機能的に劣っていますが、POSIX に適合するために
提供されています。
.Fn gettimeofday
と
.Fn getrusage
をコールし、情報と結果を受け渡すことによって実装されています。
.It
プロファイリングクロック。1024 の周波数をもつ実クロックです。
これは主に
.Xr moncontrol 3
と
.Xr kgmon 8
と
.Xr gprof 1
で使用されます。
アプリケーションはこの実際の周波数を決定するためには
.Xr sysctl 3
を使うか、プロファイリングデータファイルのヘッダを読んで
調べなければなりません。
.It
mc14618a のクロック。32768 の公称周波数をもつ実クロックです。
分周されて統計クロックおよびプロファイリングクロックに使われます。
このクロックはアプリケーションからは参照できません。
.It
マイクロ秒クロック。1000000 の周波数をもつ仮想クロックです。
これは BSD ではほとんどの時間計測に使用され、アプリケーションに対して
.Xr getrusage 2
や
.Xr gettimeofday 2
や
.Xr select 2
や
.Xr getitimer 2
などでエクスポートされています。これが通常 BSD のアプリケーションで
使用されるべきクロックです。
.It
i8254 クロック。1193182 の公称周波数をもつ実クロックです。
分周されてスケジューリングクロックに使われます。
アプリケーションからは参照できません。
.It
i586 システムでの i586 クロック。最大 200000000 の周波数をもつ実クロック
です。
これはスケジューリングクロックの値の間に挿入するために使用されます。
アプリケーションからは参照できません。
.El
.Pp
まとめ: もし
.Ql HZ
(ヘルツ) が 1000000 でなければ、アプリケーションはおそらく間違った
クロックを使用することになるでしょう。
.Sh 関連項目
.Xr gprof 1 ,
.Xr getitimer 2 ,
.Xr getrusage 2 ,
.Xr gettimeofday 2 ,
.Xr select 2 ,
.Xr clock 3 ,
.Xr moncontrol 3 ,
.Xr times 3
.Sh 作者
.An -nosplit
この man ページは
.An Bruce Evans
によって投稿された説明にもとづいて、
.ie t J\(:org Wunsch
.el Joerg Wunsch
によって書かれました。
.\"ZZZ: 3.0-RELEASE compliant by N. Kumagai 99-1-21
