.ig \"-*- nroff -*-
Copyright (C) 1989-1995 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.\" Original Revision: 1.1.1.1
.\" jpman %Id: groff_ms.7,v 1.3 1999/01/06 22:32:03 vanitas Stab %
.TH MSAFER 7 "7 September 1996" "Groff Version 1.15"
.SH 名称
groff_ms \- groff ms マクロ
.SH 書式
.B groff
.B \-ms
[
.IR options .\|.\|.
]
[
.IR files .\|.\|.
]
.SH 解説
このマニュアルページは GNU バージョンの ms マクロの解説をします。
このマクロは、groff 文書整形システムの一部分です。
この groff ms マクロは、4.3
.SM BSD
Unix ms マクロの文書化された機能と互換であるように設計されています。
しかし、次のような制限があります:
.IP \(bu
groff ms の内部は Unix ms の内部とは同じではありません。
したがって、Unix ms の実装の細部に依存する書式については、
機能しないとしてももっともでしょう。
.IP \(bu
タイプライタ様のデバイスには、サポートはありません。
.IP \(bu
バークレイ方言、特に、
.B TM
や
.B CT
マクロは、実装されていません。
.IP \(bu
groff ms
では、
.\" ページ間の
カットマーク
.\" (.CM マクロ etc.)
は提供しません。
.IP \(bu
重複した行送りは許されません
(代わりに、大きな垂直行送りを使用して下さい)。
.IP \(bu
groff ms は、互換モードでは機能しません
(例えば、
.B \-C
オプションなど)。
.IP \(bu
エラー処理の方針については、groff ms は、沈黙したままエラーを無視
したりせず、エラーを検出してレポートします。
.LP
groff ms マクロは、GNU troff の多くの機能を利用しています。
したがって、これは他のいかなる troff によっても使用できません。
.LP
ベル研の方言は、
.SM BSD
ms マクロにも groff ms マクロのいずれにも実装されていません。
.LP
ある Unix ms の文書には、数値レジスタの
.B CW
と
.B GW
とが、それぞれカラム幅とガター幅
.\" (マルチカラム間の幅)
を制御する為に
使用できると述べられています。
しかし、ここでは事実はそうではありません。
これらの数値レジスタは、groff ms では使用できません。
.LP
リセットを引き起こすマクロはインデントを設定します。
インデントを変更するマクロはインデントを増減するのではなく、
むしろインデントを絶対的に設定します。
このことによって、独自のマクロを追加定義している文書に
問題が生じるかも知れません。
これを解決するには、
.B in
リクエストを用いずに、代わりに
.B RS
や
.B RE
マクロを用いて下さい。
.LP
数値レジスタの
.B GS
は、groff ms マクロによって 1 に設定されます。
しかし、この数値レジスタは Unix ms マクロでは使用されていません。
このレジスタの目的は、
Unix ms か groff ms かのどちらによってフォーマットされているのかを確定する
必要のある文書によって利用されることです。
.LP
脚注はキープやディスプレイの中で安全に使用できるように実装されています。
自動的に番号を割り振る脚注をフローティングキープの中で使うことは、推奨
できません。
.B \e**
と
対応する
.BR .FS
との間にもう一つの
.B \e**
があるようにすると安全です。
その際には、次のようなことだけが要求されています。
つまり、各
.B .FS
は対応する
.B \e**
の後に出現することと、
対応する
.B \e**
の置かれる順番と同じ順番で
.B .FS
が出現することです。
.LP
文字列の
.B \e*{
や
.B \e*}
は、上付き文字を開始したり終了したりするのに使うことができます。
.LP
いくつかの Unix V10 ms の機能が実装されています。
.BR B ,
.BR I
や
.B BI
マクロでは、第 3 番目の引数がオプションとして指定できます。
この引数は、現在のフォントで最初の引数の直前に印字されます。
.B B
と同じようなマクロ
.B CW
があります。
これは、定幅フォントにします。
.LP
次の文字列は、groff ms マクロを英語以外の言語に適合させるために
再定義することができます。
.LP
.nf
.ta \w'REFERENCES'u+2n
文字列	デフォルト値
.sp .3v
REFERENCES	References
ABSTRACT	ABSTRACT
TOC	Table of Contents
MONTH1	January
MONTH2	February
MONTH3	March
MONTH4	April
MONTH5	May
MONTH6	June
MONTH7	July
MONTH8	August
MONTH9	September
MONTH10	October
MONTH11	November
MONTH12	December
.fi
.LP
フォントファミリは、リセットで文字列
.BR FAM
から取られて置き直されます。
初期化時にこの文字列が未定義であった場合は、現在のフォントファミリが
設定されます。
脚注のポイントサイズ、垂直行送り幅、そして段落間の行送り幅は、
数値レジスタの
.BR FPS ,
.BR FVS ,
や
.B FPD
から取り出されます。
初期化時に、これらは、それぞれ
.BR \en(PS-2 ,
.BR \en[FPS]+2 ,
および
.B \en(PD/2
に等しく設定されます。
しかし、これらのレジスタのいずれかでも初期化前に定義されていれば、
そのレジスタは、これらの値に設定されません。
(
.B .hy
リクエストによって設定される)ハイフネーションフラグは、
.B HY
レジスタから取られて設定されます。
これが初期化時に定義されていない場合には、
.B HY
レジスタは 14 に設定されます。
.LP
右詰めのディスプレイは
.B ".DS R"
および
.BR .RD
を用いて利用可能です。
.LP
次のような慣行がマクロ、文字列そして数値レジスタの名前に行なわれています。
groff ms マクロを使用する文書に利用出来る外部名は大文字と数字だけから
なります。
内部的には、マクロはモジュールに分割されます。
ある一つのモジュールの中だけで使用される名前は、
.IB mudule * name\fR
という形をしています。
定義されているモジュールの外部で使用される名前は、
.IB module @ name\fR
という形をしています。
ある特別の環境に関わる名前は、
.IB environment : name\fR
という形をしています。
これらの名前は、
.B par
モジュールの中でのみ使われ、
.I name
には、モジュールは接頭辞としてつきません。
組み合わされた名前で配列を実装するのに使われるものは、
.IB array ! index\fR
という形をしています。
以上より groff ms では以下の名前を予約しています:
.IP \(bu
.BR *
を含んでいる名前。
.IP \(bu
.BR @
を含んでいる名前。
.IP \(bu
.BR :
を含んでいる名前。
.IP \(bu
大文字と数字だけを含んでいる名前。
.SH 関連ファイル
.B /usr/share/tmac/tmac.s
.SH 関連項目
.BR groff (1),
.BR troff (1),
.BR tbl (1),
.BR pic (1),
.BR eqn (1)
.br
.BR ms (7)
.\" Translated by Tetsuro FURUYA <ht5t-fry@asahi-net.or.jp> on Nov 24, 1998.
