# $FreeBSD$

MAN7 =	ascii.7\
	build.7\
	clocks.7\
	development.7\
	environ.7\
	firewall.7\
	hier.7\
	hostname.7\
	intro.7\
	operator.7\
	ports.7\
	re_format.7\
	release.7\
	roff.7\
	security.7\
	symlink.7\
	term.7\
	tuning.7

MLINKS+=intro.7 miscellaneous.7

.include "bsd.prog.mk"
