MAN7 =	ascii.7\
	clocks.7\
	environ.7\
	groff_char.7\
	groff_me.7\
	groff_mm.7\
	groff_mmse.7\
	groff_ms.7\
	hier.7\
	hostname.7\
	intro.7\
	mailaddr.7\
	mdoc.7\
	mdoc.samples.7\
	operator.7\
	ports.7\
	re_format.7\
	symlink.7

MLINKS=	groff_me.7 me.7
MLINKS+=groff_mm.7 mm.7
MLINKS+=groff_mmse.7 mmse.7
MLINKS+=groff_ms.7 ms.7
MLINKS+=intro.7 miscellaneous.7

.include "bsd.prog.mk"
