# $FreeBSD: www/ja/releases/4.0R/Makefile,v 1.2 2000/06/29 00:06:24 motoyuki Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

LOCALTOP= ../..

DOCS=	announce.sgml
DOCS+=	notes.sgml
DOCS+=	errata.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
