#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/books/handbook/mac/Makefile,v 1.1 2004/07/01 10:55:54 den Exp $
# Original revision: 1.1
#

CHAPTERS= 	mac/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
