# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.15

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	copyright.sgml
DOCS+=	daemon.sgml
DOCS+=	freebsd-doc-license.sgml
DOCS+=	freebsd-license.sgml
DOCS+=	license.sgml
DOCS+=	trademarks.sgml

INDEXLINK= copyright.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
