#
# Build the Handbook with just the content from this chapter.
#
# %SOURCE%    en_US.ISO8859-1/books/handbook/advanced-networking/Makefile
# %SRCID%     1.2
#
# $FreeBSD$
#

CHAPTERS= 	advanced-networking/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
