=== Разработка драйверов FreeBSD для BananaPi-R64/R2-PRO

Ссылки: +
link:https://wiki.freebsd.org/arm/Bananapi[Wiki] URL: link:https://wiki.freebsd.org/arm/Bananapi[]

Контактное лицо: Martin Filla <freebsd@sysctl.cz>

Приветствуются участники.
Если вы заинтересованы в помощи с этим проектом, тестировании текущей
реализации или внесении кода, пожалуйста, свяжитесь со мной.

==== Введение в R64

Banana Pi R64 — это плата разработки на базе MediaTek MT7622 (ARM Cortex-A53, двухъядерный ~1.35 ГГц), оснащённая 4× Gigabit LAN, 1× Gigabit WAN, Wi-Fi (4×4n), Bluetooth 5.0 и множеством периферийных интерфейсов (UART, SPI, I²C, GPIO, SATA, mini-PCIe, eMMC и т.д.).

==== Текущее состояние поддержки FreeBSD для R64

Реализовано на данный момент:

- **Драйвер UART**
- **Управление тактовой частотой (clocks)**
- **Pinctrl**
- **Драйвер контроллеров хранилища (eMMC/SD/MMC)**
- **Драйвер Ethernet-коммутатора mt7531**
- **Драйвер Ethernet mt7622**
- **Драйвер XHCI**
- **Драйвер Watchdog**
- **Драйвер RTC**
- **Драйвер RNG**
- **Драйвер Pciecfg**
- **Драйвер SysIRQ**
- **USB3**
- **T-PHY**

==== План разработки для R64

Реализовать недостающие драйверы:

- SATA / AHCI
- Wi-Fi (вероятно, MediaTek MT7615)
- Подсистемы GPIO
- I2C
- SPI
- PWM
- PCIE

==== Введение в R2-PRO

Banana Pi BPI-R2 Pro — это плата разработки для маршрутизаторов следующего поколения.
Она работает на процессоре Rockchip RK3568.
На борту 2 ГБ оперативной памяти LPDDR4 и 16 ГБ встроенной памяти eMMC, поддерживается 2 интерфейса USB 3.0, 5 гигабитных сетевых портов.
Интерфейс M.2 key-E и mini PCIe, 2 интерфейса mipi DSI (один можно программно изменить на LVDS), 1 интерфейс камеры CSI, 1 выход HDMI.

==== Текущее состояние поддержки FreeBSD для R2-PRO

Реализовано на данный момент:

- **Драйвер UART**
- **Управление тактовой частотой (clocks)**
- **Pinctrl**
- **GPIO**
- **Драйвер контроллеров хранилища (eMMC/SD/MMC)**
- **Драйвер XHCI**
- **Драйвер Watchdog**
- **Драйвер PCIE**

==== План разработки для R2-PRO

Реализовать недостающие драйверы:

- HDMI
- MIPI
- USB3
- SATA

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (13.06.2026): ef4489657da230e5f9df621b78c15abfdf5de70c
//
