=== Совместное управление производительностью процессора (CPPC)

Контактное лицо: Olivier Certner <olce@FreeBSD.org> +
Контактное лицо: ShengYi Hung <aokblast@FreeBSD.org>

Совместное управление производительностью процессора (CPPC) — это стандарт, введённый ACPI, позволяющий операционной системе управлять уровнями производительности и энергоэффективности процессоров благодаря абстрактной шкале производительности, в общем случае не связанной с уровнями частоты и более детализированной, чем они.

Работа возобновлена после очередного начала в ходе Хаккатона в Галифаксе в конце июня.

В разработке находятся:

- Новые параметры минимальной, максимальной и желаемой производительности для драйвера Intel (man:hwpstate_intel[4]).
- Обучение man:powerd[8] работе с этими параметрами и предоставление базовых политик для них.
- Параметр для установки EPP (Предпочтение эффективности/производительности) для всех процессоров одновременно и, вероятно, аналогичные параметры для минимального, максимального и желаемого значений производительности.
- Условное включение функциональности CPPC драйвера AMD (man:hwpstate_amd[4]) при наличии таблицы ACPI `_CPC`.
  Параметр позволит пользователям обходить эту проверку, а также, возможно, проверку на наличие функциональности CPPC, сообщаемой через CPUID.
- Глобальный параметр профиля с предопределёнными значениями (например, «Сбалансированный», «Производительность» и т.д.), который устанавливает все остальные более детальные параметры.
  Явная установка детального параметра переключит профиль на «Пользовательский».

В конце июня было закоммичено несколько предварительных чисток и исправлений.

Спонсор: The FreeBSD Foundation

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (07.07.2026): 6c3661df1e104877e4571b5af6afed8f133b4153
//
