=== FreeBSD на EC2

Контактное лицо: Colin Percival <cperciva@FreeBSD.org>

FreeBSD доступна на EC2-инстансах как amd64 (Intel и AMD), так и arm64 (Graviton).

Была исправлена проблема, из-за которой драйвер man:ena[4] терял пакеты при приёме джамбограмм (jumbogram).
Исправление присутствовало в 15.1-RELEASE (июнь) и будет присутствовать в 14.5-RELEASE (сентябрь).
Это исправление улучшило производительность сети для одного TCP-потока на некоторых EC2-инстансах со 110 Мбит/с до 9.5 Гбит/с, а также значительно улучшило пропускную способность для нескольких TCP-потоков.

Была выявлена проблема, из-за которой драйвер man:ena[4] запускал очереди задач (taskqueues) на неверных процессорах в системах NUMA.
Исправление должно появиться в 14.5-RELEASE (сентябрь) и даёт двукратное увеличение пропускной способности для нескольких TCP-потоков на инстансах c8gn.48xlarge.

Спонсор: Amazon +
Спонсор: https://www.patreon.com/cperciva

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (27.06.2026): 26cf022abb6e340a036456a4baeecaa5ceab6a22
//
