[[_hackathon_202606_halifax_nova_scotia_canada]]
=== Хакатон 202606 — Галифакс, Новая Шотландия, Канада

Ссылки: +
link:https://wiki.freebsd.org/Hackathon/202606[Страница вики Хакатона/202606] URL: link:https://wiki.freebsd.org/Hackathon/202606[] +
link:https://wiki.freebsd.org/Hackathon[Страница вики хакатонов FreeBSD] URL: link:https://wiki.freebsd.org/Hackathon[]

Контактное лицо: Joe Mingrone <jrm@FreeBSD.org>

После link:https://www.bsdcan.org/2026/[BSDCan 2026 в Оттаве] некоторые члены сообщества собрались на хакатон в Университете Далхаузи в Галифаксе, Новая Шотландия, Канада.
По трём репозиториям было закоммичено 93 изменения с тегом `Event: Halifax Hackathon 202606`.

Большая часть этой работы описана в отдельных записях отчёта, но здесь приводится краткий обзор.
Основной объём работы над src был сосредоточен на управлении энергопотреблением процессора.
Большая его часть попала в man:hwpstate_intel[4], который получил исправления для нескольких ошибок, связанных с MSR и неинициализированными переменными, перенёс настройку предпочтения энергоэффективности на 8-битную шкалу и заменил `thread_lock()` и `sched_bind()` на IPI.
Был также добавлен новый KPI `cpu_get_pcpuid()`, который был принят как man:hwpstate_intel[4], так и `hwpstate_amd`.
Проход по коду ACPI ужесточил типы обработчиков событий сна и пробуждения, удалил неиспользуемые флаги отключения из `acpi_cpu`, man:acpi_hpet[4] и `acpi_timer`, а также заставил ядро отклонять S4, когда S4BIOS не поддерживается.
Для поддержки ноутбуков был закоммичен новый драйвер `hrfkill` для клавиши режима «в самолёте» на некоторых ноутбуках Framework, в man:acpi_ibm[4] была добавлена отправка в evdev события о нажатии клавиши отключения микрофона, а man:iichid[4] был изменён так, чтобы всегда освобождать свой ресурс прерываний.
Другие изменения в src затронули libusb, libdtrace, libcxxrt, man:ifconfig[8], `sched_ule` и ряд справочных страниц.
В портах Python по умолчанию был переключён на 3.12, добавлен новый порт package:databases/py-oracledb[], а изменение в package:sysutils/consolekit2[] включило приостановку S0ix на 16-CURRENT.
Порты Emacs получили различные обновления и улучшения; были обновлены порты R, Jenkins и некоторые биоинформатические порты.
Работа над документацией добавила раздел в Справочник (Handbook) о собственной ZFS-шифровании, обновила инструкции по зашифрованному подкачку geli и улучшила руководство FDP Primer по созданию патчей с контекстом.

Вот сырые данные о коммитах хакатона в репозиториях link:https://cgit.freebsd.org/doc/log/?qt=grep&q=Event%3A.*Halifax+Hackathon+202606[doc], link:https://cgit.freebsd.org/ports/log/?qt=grep&q=Event%3A.*Halifax+Hackathon+202606[ports] и link:https://cgit.freebsd.org/src/log/?qt=grep&q=Event%3A.*Halifax+Hackathon+202606[src].

Хотя большая часть времени была посвящена программированию, это были не только рабочие будни, как показывают link:https://p.obiw.ac/s/hfx[фотографии].
Участники провели несколько вечеров и полдня за развлечениями.

Спонсор: The FreeBSD Foundation (питание)

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (14.07.2026): ea81d6f2c21407b3416381638fc02f3b110a0cba
//
