=== KDE во FreeBSD

Ссылки: +
link:https://freebsd.kde.org/[Инициатива KDE/FreeBSD] URL: link:https://freebsd.kde.org/[] +
link:https://community.kde.org/FreeBSD[FreeBSD — Вики сообщества KDE] URL: link:https://community.kde.org/FreeBSD[]

Контактное лицо: Список рассылки KDE во FreeBSD <kde@FreeBSD.org>

Проект KDE во FreeBSD упаковывает CMake, Qt и программное обеспечение из сообщества KDE для дерева портов FreeBSD.
Программное обеспечение включает полноценную среду рабочего стола под названием KDE Plasma (как для X11, так и для Wayland) и сотни приложений, которые могут использоваться на любой машине FreeBSD.
Команда mailto:kde@FreeBSD.org[KDE] является частью mailto:desktop@FreeBSD.org[desktop@], создавая программный стек, чтобы сделать FreeBSD красивой и пригодной для использования в качестве ежедневной графической рабочей станции.

==== Инфраструктура

CMake обновлён до версии 3.31.12.

Qt6 и PySide6 обновлены до версии 6.11.1.
PyQt6 обновлён до версии 6.11.0.

Qt5 и PySide2 обновлены до набора патчей KDE версии 5.15.19.
Официальная поддержка Qt5 вышестоящим проектом завершена.
Это последнее обновление для Qt5.

==== Стек KDE

Релизы KDE Frameworks, Plasma и Gear происходят очень регулярно.
Команда mailto:kde@FreeBSD.org[KDE] включает эти обновления вскоре после их выхода вышестоящими проектами.

* Порты KDE Frameworks обновлены до версии 6.28.0.
* KDE Plasma Desktop обновлён до версии 6.6.6.
* KDE Gear обновлён до версии 26.04.3.

==== Связанные порты

Было добавлено несколько новых портов KDE.
Amarok, классический музыкальный плеер KDE, был восстановлен и обновлён до версии 3.3.3.

==== Завершение поддержки портов Qt5

Qt5 всё ещё используется примерно 350 портами.
Хотя Qt5 объявлен устаревшим, пока нет определённой даты его удаления из дерева портов.
Тем не менее, порт Qt5WebEngine, основанный на очень старой версии Chromium с множеством уязвимостей, запланирован к удалению непосредственно перед 2026Q4.
Команда KDE призывает сопровождающих перенести свои порты на Qt6, удалить варианты (flavors) с Qt5 и удалить заброшенное программное обеспечение на Qt5.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (14.07.2026): e77e4225ac3104190c46ffed7c4894b600fc22c6
//
