=== Поддержка метрики маршрутизации

Контактное лицо: Pouria Mousavizadeh Tehrani <pouria@FreeBSD.org>

Я работаю над реализацией метрики с 2026Q1.
Метрики маршрутизации — это значения конфигурации, используемые маршрутизатором для принятия решений о маршрутизации.
Метрики маршрутизации помогают стеку маршрутизации выбирать наилучший маршрут среди нескольких возможных маршрутов к пункту назначения.
Трафик будет направлен в сторону шлюза с наименьшей метрикой.
Поддержка метрики в нашем стеке маршрутизации реализована и доступна в CURRENT.
Поддержка метрики требует многочисленных обновлений как в ядре, так и в пользовательском пространстве.

Вот некоторые основные добавленные возможности:

* Поддержка метрики в rtsock через rmx_metric.
* Поддержка RTA_PRIORITY для метрики в netlink.
* Удалено резервирование 8 старших битов для метрики.
* man:route[8] теперь отображает значение метрики.
* man:netstat[1] теперь отображает значение метрики каждого маршрута при использовании -w.

Вы также можете использовать метрику с помощью package:net/bird[] для ваших протоколов маршрутизации.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (14.07.2026): 37202ca85426ad980293829501a4a2a7a8040c7c
//
