=== Нативная поддержка MPLS для FreeBSD

Ссылки: +
link:https://wiki.freebsd.org/SummerOfCode2026Projects/NativeMPLSSupportForFreeBSD[Вики проекта GSoC] +
link:https://codeberg.org/Subhash_Murmu/freebsd-src[Форк исходного кода FreeBSD]

Контактное лицо: Subhash Murmu <subhashmurmujsr2511@gmail.com>

Этот проект добавляет нативную поддержку Multiprotocol Label Switching (MPLS) в ядро FreeBSD в рамках Google Summer of Code 2026 под руководством наставников Bruce Simpson и Alexander Chernikov.
MPLS широко используется для коммутации с метками в производственных сетях, но во FreeBSD отсутствует плоскость данных MPLS в базовой системе, поэтому демоны маршрутизации с поддержкой MPLS не имеют пути пересылки в ядре для программирования.
Работа ведётся снизу вверх: от инкапсуляции на канальном уровне до плоскости управления, и интегрируется с существующим сетевым стеком FreeBSD, а не существует рядом с ним.

Этапы с 1 по 3 завершены и представлены в виде пятикоммитной истории с наслоением на ветке `mpls` форка на Codeberg.
Этап 1 добавляет инкапсуляцию канального уровня и диспетчеризацию man:netisr[9] для EtherType 0x8847.
Этап 2 портирует man:ldpd[8] из OpenBSD во FreeBSD, где он теперь собирается и работает.
Этап 3 добавляет механизм пересылки и информационную базу меток (Label Information Base) для каждого VNET, при этом сквозная передача LSP была проверена с помощью tcpdump между VNET-клетками через man:epair[4].

Серия изменений ещё не отправлена в Phabricator.
Продолжается работа над программированием маршрутов ядра для ldpd.

Спонсор: Google Summer of Code 2026

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (17.07.2026): 331ffed7ca68b29d45b3b379edbbc86fa422f516
//
