=== NTSYNC(9)

Контактное лицо: Konstantin Belousov <kib@FreeBSD.org>

В последнее время появился поток статей, рекламирующих драйвер Linux ntsync, который реализует вспомогательный механизм для Wine для ускорения примитивов синхронизации Windows NT.
Субстрат для реализации семафоров, мьютексов и событий из мира Win32 предоставляется им.
Драйвер представляет каждый объект NT как файловый дескриптор, для которого определён набор ioctl, напрямую отображаемых на операции Win32.

Проект реализовал драйвер, предоставляющий совместимый интерфейс ntsync, как указано в документе Linux 7.0-rc3 Documentation/userspace-api/ntsync.rst.
Написаны как нативный интерфейс FreeBSD, так и слои совместимости ABI Linux.

Для тестирования драйвера был портирован минимальный набор тестов из набора тестов ядра Linux.
Драйвер FreeBSD следует деталям интерфейса, закодированным в тестах, когда было обнаружено расхождение между документацией Linux и тестами.

Как драйвер, так и его справочная страница man:ntsync(4) были написаны с нуля без обращения к исходному коду Linux.

Спонсор: The FreeBSD Foundation

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (17.07.2026): f02503c4f0c9c0b42848602cc7fd753b20c697b5
//
