[[_raspberry_pi_imager_freebsd_port]]
=== Порт Raspberry Pi Imager для FreeBSD

Ссылки: +
link:https://github.com/raspberrypi/rpi-imager[основной репозиторий rpi-imager] URL: https://github.com/raspberrypi/rpi-imager[] +
link:https://github.com/raspberrypi/rpi-imager/pull/1655[запрос на включение порта для FreeBSD] URL: https://github.com/raspberrypi/rpi-imager/pull/1655[] +
link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=296480[PR 296480 - открытое рецензирование порта FreeBSD] URL: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=296480[]

Контакт: Jim Chen <jim.chen.1827@gmail.com>
Контакт: Nimish Jain <njain15@protonmail.com>

Raspberry Pi Imager — это удобный графический инструмент, разработанный Raspberry Pi Foundation, который позволяет пользователям легко настраивать и записывать образы операционных систем на карты памяти для одноплатных компьютеров Raspberry Pi Zero и Raspberry Pi серий 1–5.

Наша цель при переносе этого приложения во FreeBSD — продолжать снижать порог входа.
Мы хотим, чтобы пользователи, не знакомые с командной строкой, могли легко записывать операционные системы на свои Raspberry Pi.

В настоящее время основной проект поддерживает только Linux, MacOS и Windows.
Мы создали порт FreeBSD, который использует собственные API ввода-вывода, дисковые и сетевые API и компонуется с предварительно упакованными библиотеками FreeBSD.

Основным препятствием для этого проекта в настоящее время является неопределённость в основном репозитории.
Сопровождающие запросили поддержку со стороны разработчиков FreeBSD для долгосрочного сопровождения кода, специфичного для FreeBSD.
Если вы являетесь коммитером или участником, заинтересованным в инструментарии для Raspberry Pi во FreeBSD, пожалуйста, сообщите нам об этом или присоединитесь к обсуждению в запросе на включение на GitHub!

Если эта работа будет принята в основной репозиторий, Makefile для репозитория портов FreeBSD готов к рецензированию как PR 296480 (link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=296480[]).

Если вы заинтересованы, пожалуйста, попробуйте локальную сборку, клонировав дерево портов и применив патч из указанного выше PR, и сообщите нам, если у вас возникнут какие-либо проблемы!

Спонсор: The FreeBSD Foundation

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (22.07.2026): 65329e18c004bbb7da54623532618a10d4bde7d6
//
