[[_freebsd_software_bill_of_materials_sbom]]
=== Перечень компонентов программного обеспечения FreeBSD (FreeBSD Software Bill of Materials - SBOM)

Ссылки: +
link:https://github.com/illuusio/freebsd-src/tree/freebsd-lua-tools-sbom/share/sbom[Инструменты FreeBSD Lua для SBOM] URL: https://github.com/illuusio/freebsd-src/tree/freebsd-lua-tools-sbom/share/sbom +
link:https://github.com/illuusio/freebsd-src/tree/sbom-pkgconfig-meld/share/sbom[Файлы SBOM для pkg-config (в разработке), которые являются основой для работы Пьера Проншери] URL: https://github.com/illuusio/freebsd-src/tree/sbom-pkgconfig-meld/share/sbom +
link:https://reviews.freebsd.org/D56474[Рецензирование генерации файлов SBOM как части процесса сборки] URL: https://reviews.freebsd.org/D56474 +

Открытые запросы на включение идентификаторов лицензий SPDX в вышестоящие проекты: +
link:https://github.com/freebsd/atf/pull/128[ATF PR#128] URL: https://github.com/freebsd/atf/pull/128 +
link:https://gnats.netbsd.org/60308[bmake NetBSD GNATS#60308] URL: https://gnats.netbsd.org/60308 +
link:https://github.com/NLnetLabs/ldns/issues/305[LDNS ISSUE#305] URL: https://github.com/NLnetLabs/ldns/issues/305 +
link:https://github.com/gwsw/less/pull/792[Less PR#792] URL: https://github.com/gwsw/less/pull/792 +
link:https://github.com/libarchive/libarchive/pull/3129[Libarchive PR#3129] URL: https://github.com/libarchive/libarchive/pull/3129 +
link:https://github.com/PJK/libcbor/issues/430[LibCBOR ISSUE#430] URL: https://github.com/PJK/libcbor/issues/430 +
link:https://gnats.netbsd.org/60309[libedit NetBSD GNATS#60309] URL: https://gnats.netbsd.org/60309 +
link:https://github.com/libevent/libevent/issues/1864[Libevent ISSUE#1864] URL: https://github.com/libevent/libevent/issues/1864 +
link:https://github.com/the-tcpdump-group/libpcap/pull/1689[LibPCAP PR#1689] URL: https://github.com/the-tcpdump-group/libpcap/pull/1689 +
link:https://github.com/vstakhov/libucl/pull/386[LibUCL PR#386] URL: https://github.com/vstakhov/libucl/pull/386 +
link:https://bugs.astron.com/view.php?id=777[TCSH Mantis#777] URL: https://bugs.astron.com/view.php?id=777 +

Контакт: Tuukka Pasanen <tuukka.pasanen@ilmi.fi>

Работа над спецификацией состава программного обеспечения FreeBSD (SBOM) продолжалась в течение второго квартала 2026 года.
В этом квартале основное внимание уделялось рецензированию и обновлению файлов pkg-config [.filename]#.pc# и добавлению SPDX-License-Identifier в сторонние проекты, включённые в исходный код FreeBSD.
Эта работа будет продолжена в третьем квартале.

Как уже было сказано, большая часть работы в этом квартале была посвящена доработке файлов pkg-config [.filename]#.pc#, поскольку эти файлы необходимы при формировании файлов SBOM, совместимых с SPDX 2.2 и SPDX Lite 3.0.1.
В течение этого года Пьер Проншери (Pierre Pronchery) добавлял другие важные компоненты, такие как pkgconf, в исходный код FreeBSD.
В настоящее время самые большие усилия с его стороны в части инструментария направлены на рецензирование части сборки, отвечающей за генерацию SBOM, в рамках которой также рецензируются файлы [.filename]#.pc#.
Когда рецензирование будет завершено и исходный код будет добавлен во FreeBSD, SBOM можно будет создавать в процессе сборки.

Помимо работы над файлами [.filename]#.pc#, была проведена доработка инструментов FreeBSD Lua для SBOM. Эти инструменты использовались для создания текущего набора файлов [.filename]#.pc# и могут быть применены для будущих обновлений.
Эти скрипты всё ещё несколько сырые и сложные в использовании, но сейчас они в гораздо лучшем состоянии, чем раньше, и к ним есть документация по использованию.

Добавление SPDX-License-Identifier в репозитории сторонних проектов также продолжается и будет выполняться в порядке, согласованном с предпочтениями сопровождающих этих проектов.
Почему идентификаторы лицензий добавляются в сторонние проекты?
На этот вопрос нет простого ответа, но наиболее близкое объяснение заключается в том, что машиночитаемые идентификаторы лицензий помогают поддерживать информацию SBOM в будущем.

Если вы хотите помочь в этой работе:

* Примите участие в рецензировании файлов [.filename]#.pc# в Phabricator в рамках рецензирования "Generate SBOM files as part of the build".
* Помогите с рецензированием импорта pkgconf 3.0 в исходный код FreeBSD.

Спонсор: FreeBSD Foundation

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (22.07.2026): 65329e18c004bbb7da54623532618a10d4bde7d6
//
