=== Улучшения приостановки/возобновления

Ссылки: +
link:https://obiw.ac/s0ix/[Блог] URL: link:https://obiw.ac/s0ix/[] +
link:https://youtu.be/RCjPc4X2Edc[Доклад на BSDCan о s2idle/S0ix] URL: link:https://youtu.be/RCjPc4X2Edc[] +
link:https://github.com/obiwac/freebsd-s0ix/pull/15[Рабочая ветка] URL: link:https://github.com/obiwac/freebsd-s0ix/pull/15[]

Контактное лицо: obiwac <obiwac@FreeBSD.org>

Приостановка с сохранением состояния (suspend-to-idle) и поддержка режима сна S0ix находятся в процессе добавления во FreeBSD.

Это позволит современным ноутбукам Intel и AMD, некоторые из которых не поддерживают режим сна ACPI S3, переходить в состояния пониженного энергопотребления для увеличения времени работы от батареи.

В основном статус такой же, как в предыдущем квартале — работа всё ещё продолжается по сужению проблем с возобновлением NVMe и исправлению проблем с состояниями D-state.

Общий интерфейс управления питанием был закоммичен, а man:zzz[8] был переписан для его использования.
Теперь ожидается, что вы будете использовать sysctl `kern.power.supported_stype` для получения списка поддерживаемых общих типов сна и устанавливать sysctl `kern.power.suspend` для указания типа сна, который должен использовать man:zzz[8].

В драйвер acpi_spmc было внесено множество мелких исправлений и улучшений.

Общая поддержка USB4 NHI также была закоммичена.
Единственное, что осталось закоммитить для поддержки USB4, необходимой для входа в S0i3, — это сама процедура приостановки.
Справочная страница man:thunderbolt[4] была обновлена, чтобы более чётко указать, что она предназначена только для поддержки входа в S0i3.

Была написана справочная страница для man:amdsmu[4], чтобы лучше объяснить, как диагностировать вход в S0i3.

Спонсор: The FreeBSD Foundation

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (07.07.2026): f16529a77e6a0aa12bfca3b50f6d57015f03e810
//
