# $FreeBSD: www/en/copyright/Makefile,v 1.15 2004/06/09 17:32:09 ceri Exp $

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	copyright.sgml

INDEXLINK= copyright.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
