# $FreeBSD: doc/en_US.ISO_8859-1/books/Makefile,v 1.7 2000/05/17 18:25:44 nik Exp $

SUBDIR = design-44bsd
SUBDIR+= faq
SUBDIR+= fdp-primer
SUBDIR+= handbook
SUBDIR+= porters-handbook
SUBDIR+= ppp-primer

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
