# $FreeBSD: doc/en_US.ISO_8859-1/books/Makefile,v 1.5 1999/09/06 06:52:39 peter Exp $

SUBDIR = faq
SUBDIR+= fdp-primer
SUBDIR+= handbook
SUBDIR+= ppp-primer

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
