# $FreeBSD: www/ja/releases/4.2R/Makefile,v 1.1 2000/11/22 20:34:39 hrs Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml
DOCS+=	errata.sgml
DOCS+=	notes.sgml

### Revision checking
REVCHECK=	YES

.include "${WEB_PREFIX}/share/mk/web.site.mk"
