# $FreeBSD$
.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA= RELNOTES.FreeBSD WHATS_NEW-1.1.5.1

.include "${DOC_PREFIX}/share/mk/web.site.mk"
