# $FreeBSD: doc/ja_JP.eucJP/articles/diskless-x/Makefile,v 1.2 2000/10/03 11:08:09 hrs Exp $
# Original revision: 1.5

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

NO_TIDY=YES

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
