# $FreeBSD: doc/ja_JP.eucJP/articles/diskless-x/Makefile,v 1.1 2000/03/22 06:32:12 kuriyama Exp $
# Original revision: 1.5

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
