---
title: 序
prev: books/handbook/
next: books/handbook/parti
---

[preface]
[[book-preface]]
= 序
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: 目录
:table-caption: 表
:figure-caption: 图
:example-caption: 例 
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:

[[preface-audience]]
== 給讀者的話

若您是第一次接觸 FreeBSD 的新手，可以在本書第一部分找到 FreeBSD 的安裝程序，同時會逐步介紹 UNIX(TM) 的基礎概念與一些常用、共通的東西。而閱讀這部分並不難，只需要您有探索的精神和接受新概念。

讀完這些之後，手冊中的第二部分花很長篇幅介紹的各種廣泛主題，相當值得系統管理者去注意。 在閱讀這些章節的內容時所需要的背景知識，都註釋在該章的大綱裡面，若不熟的話，可在閱讀前先預習一番。

延伸閱讀方面，可參閱 crossref:bibliography[bibliography,參考書目]。

[[preface-changes-from3]]
== 自第三版後的主要修訂

您目前看到的這本手冊代表著上百位貢獻者歷時 10 年所累積的心血之作。以下為自 2014 年發佈的兩冊第三版後所做的主要修訂：

* crossref:dtrace[dtrace,DTrace] 增加說明有關強大的 DTrace 效能分析工具的資訊。
* crossref:filesystems[filesystems,其他檔案系統] 增加有關 FreeBSD 非原生檔案系統的資訊，如：來自 Sun(TM) 的 ZSF。
* crossref:audit[audit,安全事件稽查] 增加的內容涵蓋 FreeBSD 的新稽查功能及其使用說明。
* crossref:virtualization[virtualization,虛擬化] 增加有關在虛擬化軟體安裝 FreeBSD 的資訊。
* crossref:bsdinstall[bsdinstall,安裝 FreeBSD] 增加的內容涵蓋使用新安裝工具 bsdinstall 來安裝 FreeBSD。

[[preface-changes-from2]]
== 自第二版後的主要修訂 (2004)

您目前看到的這本手冊第三版是 FreeBSD 文件計劃的成員歷時兩年完成的心血之作。因文件內容成長到一定大小，印刷版需要分成兩冊發佈。新版的主要修訂部分如下：

* crossref:config[config-tuning,設定與調校] 已針對新內容作更新，如：ACPI 電源管理、`cron` 以及其他更多的核心調校選項說明內容。
* crossref:security[security,安全性] 增加了虛擬私人網路 (VPN)、檔案系統的存取控制 (ACL)，以及安全報告。
* crossref:mac[mac,強制存取控制 (MAC)] 是此版本新增的章節。該章介紹：什麼是 MAC 機制？以及如何運用它來使您的 FreeBSD 系統更安全。
* crossref:disks[disks,儲存設備] 新增了像是：USB 隨身碟、檔案系統快照 (Snapshot)、檔案系統配額 (Quota) 、檔案與網路為基礎的檔案系統、以及如何對硬碟分割區作加密等詳解。
* crossref:ppp-and-slip[ppp-and-slip,PPP] 增加了疑難排解的章節。
* crossref:mail[mail,電子郵件] 新增有關如何使用其它的傳輸代理程式、SMTP 認證、UUCP、fetchmail、procmail 的運用以及其它進階主題。
* crossref:network-servers[network-servers,網路伺服器] 是該版中全新的一章。這一章介紹了如何架設 Apache HTTP 伺服器、ftpd 以及用於支援 Microsoft(TM)Windows(TM) 客戶端的 Samba。其中有些段落來自原先的 crossref:advanced-networking[advanced-networking,進階網路設定] 。
* crossref:advanced-networking[advanced-networking,進階網路設定] 新增有關在 FreeBSD 中使用藍牙(TM)裝置、設定無線網路以及使用非同步傳輸模式 (Asynchronous Transfer Mode, ATM) 網路的介紹。
* 增加詞彙表，用以說明全書中出現的術語。
* 重新美編書中所列的圖表。

[[preface-changes]]
== 自第一版後的主要修訂 (2001)

本手冊的第二版是 FreeBSD 文件計劃的成員歷時兩年完成的心血之作。第二版包的主要變動如下：

* 增加完整的目錄索引。
* 所有的 ASCII 圖表均改成圖檔格式的圖表。
* 每個章節均加入概述，以便快速的瀏覽該章節內容摘要、讀者所欲了解的部分。
* 內容架構重新組織成三大部分："入門"、"系統管理" 以及 "附錄"。
* crossref:basics[basics,FreeBSD 基礎] 新增了程序、Daemon 以及信號 (Signal) 的介紹。
* crossref:ports[ports,安裝應用程式：套件與 Port] 新增了介紹如何管理 Binary 套件的資訊。
* crossref:x11[x11,X Window 系統] 經過全面改寫，著重於在 XFree86(TM) 4.X 上的現代桌面技術，如： KDE 和 GNOME。
* crossref:boot[boot,FreeBSD 開機程序] 更新相關內容。
* crossref:disks[disks,儲存設備] 分別以兩個章節 "磁碟" 與 "備份" 來撰寫。我們認為這樣子會比單一章節來得容易瞭解。還有關於 RAID (包含硬體、軟體 RAID) 的段落也新增上去了。
* crossref:serialcomms[serialcomms,序列通訊] 架構重新改寫，並更新至 FreeBSD 4.X/5.X 的內容。
* crossref:ppp-and-slip[ppp-and-slip,PPP] 有相當程度的更新。
* crossref:advanced-networking[advanced-networking,進階網路設定] 加入許多新內容。
* crossref:mail[mail,電子郵件] 大量新增了設定 sendmail 的介紹。
* crossref:linuxemu[linuxemu,Linux® Binary 相容性] 增加許多有關安裝 Oracle(TM) 以及 SAP(TM) R/3(TM) 的介紹。
* 此外，第二版還新加章節，以介紹下列新主題：

** crossref:config[config-tuning,設定與調校]。
** crossref:multimedia[multimedia,多媒體]。

[[preface-overview]]
== 本書架構

本書主要分為五大部分，第一部份__入門__：介紹 FreeBSD 的安裝、基本操作。 讀者可根據自己的程度，循序或者跳過一些熟悉的主題來閱讀； 第二部分__一般作業__：介紹 FreeBSD 常用功能，這部分可以不按順序來讀。 每章前面都會有概述，概述會描述本章節涵蓋的內容和讀者應該已知的， 這主要是讓讀者可以挑喜歡的章節閱讀； 第三部分__系統管理__：介紹 FreeBSD 老手所感興趣的各種主題部分； 第四部分__網路通訊__：則包括網路和各式伺服器主題；而第五部分則為附錄包含各種有關 FreeBSD 的資源。

_crossref:introduction[introduction,簡介]_::
向新手介紹 FreeBSD。該篇說明了 FreeBSD 計劃的歷史、目標和開發模式。

_crossref:bsdinstall[bsdinstall,安裝 FreeBSD]_::
帶領使用者走一次使用 bsdinstall 在 FreeBSD 9._x_ 及之後版本的完整安裝流程。

_crossref:basics[basics,FreeBSD 基礎]_::
涵蓋 FreeBSD 作業系統的基礎指令及功能。若您熟悉 Linux(TM) 或其他類 UNIX(R) 系統，您則可跳過此章。

_crossref:ports[ports,安裝應用程式：套件與 Port]_::
涵蓋如何使用 FreeBSD 獨創的 "Port 套件集" 與標準 Binary 套件安裝第三方軟體。

_crossref:x11[x11,X Window 系統]_::
介紹 X Windows 系統概要及在 FreeBSD 上使用 X11，同時也會介紹常用的桌面環境如 KDE 與 GNOME。

_crossref:desktop[desktop,桌面應用程式]_::
列出一些常用的桌面應用程式，例如：網頁瀏覽器、辦工工具並介紹如何安裝這些應用程式到 FreeBSD。

_crossref:multimedia[multimedia,多媒體]_::
示範如何在您的系統設定音效及影像播放支援，同時會介紹幾個代表性的音訊及視訊應用程式。

_crossref:kernelconfig[kernelconfig,設定 FreeBSD 核心]_::
說明為何需要設定新的核心並會提供設定、編譯與安裝的詳細操作說明。

_crossref:printing[printing,列印]_::
介紹如何在 FreeBSD 管理印表機，包含橫幅頁面、列印帳務以及初始設定等資訊。

_crossref:linuxemu[linuxemu,Linux® Binary 相容性]_::
介紹 FreeBSD 的 Linux(TM) 相容性功能，同時提供許多熱門的 Linux(TM) 應用程式詳細的安裝操作說明，例如 Oracle(TM) 及 Mathematica(TM)。

_crossref:config[config-tuning,設定與調校]_::
介紹可供系統管理者用來調校 FreeBSD 系統的可用參數來最佳化效率，同時也介紹 FreeBSD 用到的各種設定檔以及到何處尋找這些設定檔。

_crossref:boot[boot,FreeBSD 開機程序]_::
介紹 FreeBSD 開機流程並說明如何使用設定選項控制開機流程。

_crossref:security[security,安全性]_::
介紹許多可讓您的 FreeBSD 系統更安全的各種工具，包含 Kerberos, IPsec 及 OpenSSH。

_crossref:jails[jails,Jail]_::
介紹 Jail Framework，以及 Jail 改進那些 FreeBSD 傳統 chroot 不足的地方。

_crossref:mac[mac,強制存取控制 (MAC)]_::
說明什麼是強制存取控制 (Mandatory Access Control, MAC) 及這個機制如何用來確保 FreeBSD 系統的安全。

_crossref:audit[audit,安全事件稽查]_::
介紹什麼事 FreeBSD 事件稽查，如何安裝與設定，以及如何檢查與監控稽查線索。

_crossref:disks[disks,儲存設備]_::
介紹如何在 FreeBSD 管理儲存媒體及檔案系統，這包含了實體磁碟、RAID 陣列、光碟與磁帶媒體、記憶體為基礎的磁碟以及網路檔案系統。

_crossref:geom[geom,GEOM. 模組化磁碟轉換框架]_::
介紹在 FreeBSD 中的 GEOM Framework 是什麼，以及如何設定各種支援的 RAID 階層。

_crossref:filesystems[filesystems,其他檔案系統]_::
查看 FreeBSD 還支援那些非原生檔案系統，如 Sun(TM) 的 Z 檔案系統。

_crossref:virtualization[virtualization,虛擬化]_::
介紹虛擬化系統提供了那些功能，以及如何在 FreeBSD 上使用。

_crossref:l10n[l10n,在地化 - i18n/L10n 使用與安裝]_::
介紹如何在 FreeBSD 使用非英文的語言，這涵蓋了系統及應用層的在地化。

_crossref:cutting-edge[updating-upgrading,更新與升級 FreeBSD]_::
說明 FreeBSD-STABLE、FreeBSD-CURRENT 以及 FreeBSD 發佈版之間的差異，並介紹那些使用者適何追蹤開發系統以及程序的概述，這涵蓋了使用者更新系統到最新安全性發佈版本的方法。

_crossref:dtrace[dtrace,DTrace]_::
介紹如何在 FreeBSD 設定及使用 Sun(TM) 的 DTrace 工具，動態追蹤可以透過執行真實時間系統分析來協助定位效能問題。

_crossref:serialcomms[serialcomms,序列通訊]_::
介紹如何使用撥入及撥出連線到您的 FreeBSD 系統的終端機與數據機。

_crossref:ppp-and-slip[ppp-and-slip,PPP]_::
介紹如何在 FreeBSD 使用 PPP 來連線遠端的系統。

_crossref:mail[mail,電子郵件]_::
說明組成電子郵件伺服器的各種元件，並深入說明如何設定最熱門的郵件伺服器軟體：sendmail。

_crossref:network-servers[network-servers,網路伺服器]_::
提供詳細的操作說明與範例設定檔，讓您可安裝您的 FreeBSD 機器為網路檔案伺服器、網域名稱伺服器、網路資訊系統伺服器或時間同步伺服器。

_crossref:firewalls[firewalls,防火牆]_::
說明軟體為基礎的防火牆背後的理念，並提供可用於 FreeBSD 中不同的防火牆設定的詳細資訊。

_crossref:advanced-networking[advanced-networking,進階網路設定]_::
介紹許多網路主題，包含在您的區域網路 (LAN) 分享網際網路連線給其他電腦、進階路由主題、無線網路、Bluetooth(TM)、ATM、IPv6 以及更多相關主題。

_crossref:mirrors[mirrors,取得 FreeBSD]_::
列出取得 FreeBSD CDROM 或 DVD 媒體的各種來源，以及在網際網路上的各種網站，讓您可以下載並安裝 FreeBSD。

_crossref:bibliography[bibliography,參考書目]_::
本書觸及許多不同主題，可能會讓您想更深入的了解，參考書目列出了在文中引用的許多優秀書籍。

_crossref:eresources[eresources,網路資源]_::
介紹了可讓 FreeBSD 使用者提出問題以及參與有關 FreeBSD 技術會談的許多論壇。

_crossref:pgpkeys[pgpkeys,OpenPGP 金鑰]_::
列出了數個 FreeBSD 開發人員的 PGP 指紋。

[[preface-conv]]
== 本書的編排體裁

為了提供有一致性且易於閱讀的內容，以下是一些本書所遵循的編排體裁。

[[preface-conv-typographic]]
=== 文字編排體裁

_斜體字_::
__斜體字__用於：檔名、目錄、網址 (URL)、 強調語氣、以及第一次提及的技術詞彙。

`等寬字`::
``等寬字``用於： 錯誤訊息、指令、環境變數、Port 名稱、主機名稱、帳號、群組、裝置名稱、變數、程式碼等。

粗體字::
以kbd:[粗體字]表示：應用程式、指令、按鍵。

[[preface-conv-commands]]
=== 使用者輸入

鍵盤輸入以**粗體字**表示，以便與一般文字做區隔。 組合鍵是指同時按下一些按鍵，我們以 `+` 來表示連接，像是：

kbd:[Ctrl+Alt+Del]

是說，一起按 kbd:[Ctrl]、 kbd:[Alt] 以及 kbd:[Del] 鍵。

若要逐一按鍵，那麼會以逗號 (,) 來表示，像是：

kbd:[Ctrl+X], kbd:[Ctrl+S]

是說：先同時按下 kbd:[Ctrl] 與 kbd:[X] 鍵， 然後放開後再同時按 kbd:[Ctrl] 與 kbd:[S] 鍵。

[[preface-conv-examples]]
=== 範例

範例以 [.filename]#C:\># 為開頭代表 MS-DOS(TM) 的指令。 若沒有特殊情況的話，這些指令應該是在 Microsoft(TM) Windows(TM) 環境的 "指令提示字元 (Command Prompt)" 視窗內執行。

[source,bash]
....
E:\> tools\fdimage floppies\kern.flp A:
....

範例以 `#` 為開頭代表在 FreeBSD 中以超級使用者權限來執行的指令。 你可以先以 `root` 登入系統並下指令，或是以你自己的帳號登入再使用 man:su[1] 來取得超級使用者權限。

[source,bash]
....
# dd if=kern.flp of=/dev/fd0
....

範例以 `%` 為開頭代表在 FreeBSD 中以一般使用者帳號執行的指令。 除非有提到其他用法，否則都是預設為 C-shell 語法，用來設定環境變數以及下其他指令的意思。

[source,bash]
....
% top
....

[[preface-acknowledgements]]
== 銘謝

您所看到的這本書是經過數百個分散在世界各地的人所努力而來的結果。 無論他們只是糾正一些錯誤或提交完整的章節，所有的點滴貢獻都是非常寶貴有用的。

也有一些公司透過提供資金讓作者專注於撰稿、提供出版資金等模式來支持文件的寫作。 其中，BSDi (之後併入 http://www.windriver.com[Wind River Systems]) 資助 FreeBSD 文件計劃成員來專職改善這本書直到 2000 年 3 月第一版的出版。(ISBN 1-57176-241-8) Wind River Systems 同時資助其他作者來對輸出架構做很多改進，以及給文章增加一些附加章節。這項工作結束於 2001 年 11 月第二版。(ISBN 1-57176-303-1) 在 2003-2004 兩年中，link:http://www.freebsdmall.com[FreeBSD Mall, Inc] 把報酬支付給改進這本手冊以使第三版印刷版本能夠出版的志工。

這部份是提供給初次使用 FreeBSD 的使用者和系統管理者。 這些章節包括：

* 介紹 FreeBSD 給您。
* 在安裝過程給您指引。
* 教您 UNIX(TM) 的基礎及原理。
* 展示給您看如何安裝豐富的 FreeBSD 的應用軟體。
* 向您介紹 X，UNIX(TM) 的視窗系統以及詳細的桌面環境設定，讓您更有生產力。

我們試著儘可能的讓這段文字的參考連結數目降到最低，讓您在讀使用手冊的這部份時可以不太需要常常前後翻頁。
