---
title: "ソースコードリポジトリ"
sidenav: developers
---

= ソースコードリポジトリ

== Git

FreeBSD プロジェクトは、ソースを管理するツールに
https://git-scm.com/[Git] を使っています。
すべての変更は、(その変更目的を説明するログメッセージと共に) リポジトリに記録され、以下で述べるウェブインタフェースで簡単に見ることができます。

2020 年 12 月、ベースシステムの開発は Subversion から Git に移行しました。
https://cgit.FreeBSD.org/src/[ウェブインタフェース] を利用してリポジトリを見ることができます。

2020 年 12 月、FreeBSD ドキュメンテーションプロジェクトは、Subversion から Git へと移行しました。
https://cgit.FreeBSD.org/doc/[ウェブインタフェース] を利用して FreeBSD ドキュメンテーションプロジェクトの Git リポジトリの内容を見ることができます。

FreeBSD の Ports ツリーも、2021 年 3 月末に Subversion から Git へと移行予定です。
https://cgit-dev.FreeBSD.org/ports/[ウェブインタフェース] を利用してベータ版のリポジトリを見ることができます。

== Subversion

FreeBSD プロジェクトは、ソースを管理するツールとして https://subversion.apache.org/[Subversion] (略して SVN) を使っていました。
すべての変更は、(その目的を説明するログメッセージと共に) リポジトリに記録され、 以下で述べるウェブインタフェースで簡単に見ることができます。

2008 年 6 月に、ベースシステムの開発は CVS から Subversion に移行しました。
2020 年 12 月に Git に開発が移行した後は、stable/11, stable/12 およびサポートしているリリースブランチに対する変更を git2svn によって変換したコミットのみ記録しています。
https://svnweb.FreeBSD.org/base/[ウェブインタフェース] を利用してリポジトリを見ることができます。

2012 年 5 月に、FreeBSD ドキュメンテーションプロジェクトは CVS から Subversion に移行しました。
2020 年 12 月の Git への移行後、doc subversion リポジトリには変更は行われていません。
link:https://svnweb.FreeBSD.org/doc/[ウェブインタフェース] を利用して FreeBSD ドキュメンテーションプロジェクトの SVN リポジトリの内容を見ることができます。

2012 年 6 月より、FreeBSD Ports ツリーは、CVS から Subversion へと移行しました。link:https://svnweb.FreeBSD.org/ports/[ウェブインタフェース] を利用してリポジトリの内容を見ることができます。
