# $FreeBSD: www/en/layout/js/Makefile,v 1.1 2005/10/04 05:49:13 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   google.js \
	styleswitcher.js

.include "${WEB_PREFIX}/share/mk/web.site.mk"
