# $FreeBSD: www/en/news/1996/Makefile,v 1.2 2000/03/22 16:22:43 phantom Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=	index.sgml

.include "../../web.mk"
