# $FreeBSD: www/ja/news/1996/Makefile,v 1.3 2000/10/02 09:16:10 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

LOCALTOP= ../..

.if exists(${LOCALTOP}/Makefile.conf)
.include "${LOCALTOP}/Makefile.conf"
.endif

DOCS=	index.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
