---
title: BSD Nedir?
authors:
  - author: Greg Lehey
    email: grog@FreeBSD.org
trademarks: ["freebsd", "apple", "xfree86", "linux", "opengroup", "sun", "general"]
---

= BSD Nedir?
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:images-path: articles/explaining-bsd/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
:imagesdir: ../../../images/{images-path}
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[.abstract-title]
Özet

Açık kod dünyasında "Linux" kelimesi neredeyse "işletim sistemi" ile eş anlamlıdır fakat açık kaynak kodlu UNIX(R) sadece "Linux" değildir. http://www.leb.net/hzo/ioscount/data/r.9904.txt[İnternet İşletim Sistemi Sayacı] 'na göre Nisan 1999 itibarıyla dünyada internete bağlı makinelerin %31.3 'ü Linux, %14.6 'ü ise UNIX(R) 'tir. http://www.yahoo.com/[Yahoo!] gibi dünyanın en büyük organizasyonlarından biri BSD kullanmaktadır. Dünyanın en meşgul FTP sunucularından biri olan link:ftp://ftp.cdrom.com/[ftp.cdrom.com] günde 1.4 TB dosya transferi için BSD kullanmaktadır.

Öyleyse sır nedir? Neden BSD daha iyi bilinmiyor? Bu küçük yazı, bu ve diğer soruların cevaplarını aramaktadır.

Bu yazıda BSD ve Linux arasındaki farklar _bu şekilde_ ifade edilecektir.

'''

toc::[]

== BSD nedir?

BSD "Berkeley Software Distribution" 'ın kısaltılmışıdır. Bu isim California Üniversitesi, Berkeley 'in kaynak kodu dağıtımı olan AT&T 'nin UNIX(R) 'i için bir eklentiler zinciridir. Birçok açık kaynak kodlu işletim sistemi projesi, 4.4BSD-Lite olarak bilinen kaynak kodu dağıtımını temel alır. Ek olarak bunlar, özellikle GNU projesi olmak üzere diğer birçok açık kod projesini de kapsar. BSD 'in içeriği:

* BSD çekirdeği işlem zamanlama, hafıza yönetimi, simetrik çoklu işlemci (SMP), aygıt sürücüleri ve diğerlerini kapsar.
+ 
__Linux çekirdeğinden farklı olarak kapasite ve güçte bir çok farklı BSD çekirdeği vardır.__
* C kütüphanesi, sistem API 'sinin temellidir
+ 
__BSD C kütüphanesi GNU projesi tabanlı değildir, Berkeley kodu temellidir.__
* Kabuk, dosya araçları derleyiciler ve linkerler gibi araçlar.
+ 
__Bazı araçlar dışında birçoğu projesinden sağlanmıştır.__
* X Windows sistemi grafik ekran arabirimi.
+ 
Birçok BSD türevinde kullanılan X Window sistemi ayrı bir proje olan http://www.XFree86.org/[projesi] 'nde devam ettirilmektedır. Linux da bu sistemi kullanmaktadır. BSD KDE ya da GNOME gibi bir "görsel masaüstü" ile öntanımlı olarak gelmez. Fakat istenirse bunlar da kullanılabilir.
* Birçok diğer program ve araçlar.

== Ne gerçek bir UNIX(R) 'mi?

BSD işletim sistemi bir kopya değildir, fakat temelde UNIX(R) 'in atası sayılan AT&T'nin işletim sisteminin kaynak kodundan oluşur. Ayrıca bu kod System V UNIX(R) 'in de atasıdır. Bu durum sizi belki şaşırtmış olabilir. Yada AT&T hiçbir zaman kaynak kodunu vermemiş olmasına rağmen bu nasıl mümkün olabilir?

AT&T UNIX(R) 'inin açık kaynak kodlu olmadığı doðrudur ve kopya hakkı düşünüldüğünde BSD kesinlikle bir UNIX(R) _değildir_ fakat diğer taraftan AT&T diğer projelerden ve özellikle Berkeley'deki California Üniversitesi Computer Science Research Group (CSRG -Bilgisayar Bilimi Araştırma Grubu)undan AT&T UNIX(R) 'e birçok kod dahil ettiği düşünülmelidir. 1976 'dan başlayarak CSRG yazılımı içeren teyp 'leri dağıtarak bunu _Berkeley Software Distribution_ ya da _BSD_ olarak nitelendirdi.

BSD ilk sürümleri asıl olarak kullanıcı programlarından oluşuyordu. Ta ki dramatik bir şekilde CSRG karşılığı olarak DARPA (Defence Advanced Projects Research Agency) ile ağlarındaki (ARPANET) iletişim protokollerini güncellemek için sözleşme imzalayana kadar. Bu yeni protokol _İnternet Protokolü_ daha sonra da _TCP/IP_ olarak adlandırıldı. BSD 'nin asıl geniş alanlara yayılmış sürümü 1982 de piyasaya sürülen 4.2 BSD 'dir.

1980 'lerde birçok küçük çaplı işletim sistemi şirketi piyasaya çıktı. Ve birçokları kendi işletim sistemlerini yazmak yerine UNIX(R) işletim sistemini lisanslamayı tercih ettiler. Özelde SUN Microsystems 4.2BSD temelli UNIX(R) üzerinde değişiklikler yaparak SunOS(TM) adıyla lisansladı. AT&T UNIX(R) 'in ticari olarak satılmasına izin verince, çok kısa bir süre içinde System V adını alacak System III isimli küçük uygulamalarla satışa başlandı. System V networking uygulama ve bileşenlerini içermiyordu, bu sebeble piyasaya sürülen birçok uygulama BSD 'den özellikle ağ teknolojileri alanında TCP/IP protokolünü kullanmaya baþladı. Bunun yanında _csh_ kabuğu ve _vi_ editörünü de kendi sistemlerine dahil etti. BSD 'den alınan bütün bu eklentilere _Berkeley Extensions_ adı verildi.

Piyasaya sunulan BSD kasetleri AT&T kaynak kodu ve gerekli olan olan UNIX lısansını içeriyordu. 90larda CSRG'a ayrılan fon azalınca grup kapanma ile karşı karşıya kaldı ve bazı grup üyeleri AT&T 'nin kodunu içermeyen BSD Açık kaynak kod olarak dağıtılan kodlarını dağıtmaya karar verdi ve bu _Networking Tape 2_ ya da kısaca _Net/2_ adı verilen dağıtım ile gerçekleşti. Net/2 tam anlamıyla bir işletim sistemi değildi çünkü yaklaşık olarak %20 oranındaki çekirdek kaynak kodu eksikti. CSRG üyelerinde William F. Jolitz geriye kalan %20 lik kodu yazarak 1992'de _386BSD_ ismiyle piyasaya sürdü. Aynı zaman zarfında eski CSRG üyelerinden oluşan bir grup http://www.bsdi.com/[Berkeley Software Design Inc.] adı verilen işletim sisteminin betasını piyasaya sürdüler ve bu işletim sisteminin adı daha sonra BSD/OS olarak değiştirildi.

386BSD hiçbir zaman güvenilir bir işletim sistemi olamadı. Onun yerine 1993 yılında iki ayrı proje doğdu. Bunlar: http://www.NetBSD.org/[NetBSD] ve http://www.FreeBSD.org[FreeBSD]. NetBSD 93'ün başlarında tamamlandı ancak FreeBSD 'nin ilk versiyonu yılın sonuna kadar hazır durumda değildi. Bu süre içerisinde kodu devam ettirilmekte güçlük çekilince karışıklığı önlemek ve yönetimi kolay kılmak için ayrıldı. Projeler farklı amaçlar gütmeye başladı. 1996 'da NetBSD 'den ayrılarak doğan http://www.OpenBSD.org/[OpenBSD] doğdu.

== BSD neden daha iyi tanınmıyor?

Aşağıdaki birçok sebebe bağlı olarak BSD tam olarak bilinmemektedir:

. BSD programcıları çoğu zaman pazarlama amacı gütmek yerine kendi kodlarını geliştirme ile ilgileniyorlar.
. Linux 'ların popülaritesi özellikle baskı (ve kitap piyasası) ve şirketlerin desteği Linux'lara özel destek ve güncellik sağlıyor. Buna karşılık BSD 'nin bu şekilde herhangi bir destekçisi yoktur. Fakat bu gün geçtikçe değişmektedir.
. BSD programcıları Linux programcılarından daha tecrübeliler ve işletim sisteminin kullanım kolaylığı ile daha az ilgileniyorlar. Yeni kullanıcılar Linux 'ları daha kullanışlı olarak kabul ediyor ve destekliyorlar.
. 1992, AT&T http://www.bsdi.com/[BSDI] 'a dava açtı ve bu yazılımın AT&T 'ye ait olan lisanslı kaynak kodunu içerdiğini iddia etti. Dava 1994 'te anlaşma ile sona erdi. Fakat davanın hayaleti insanları avlamaya devam etti. Mart 2000 'de ise web üzerine, davanın mahkeme tarafından geçmişte "sonlandırıldığını" haykıran bir makale yayınlandı.
+ 
Davanın ortaya çıkardığı önemli bir detayda isimlendirmeydi. 1980 'lerde BSD aynı zamanda "BSD UNIX(R)" olarakta bilinmekteydi. AT&T 'ye ait kodların son kalıntılarının da BSD'den çıkartılması ile birlikte BSD UNIX(R) adından kurtuldu. Bu sebeble birçok kitapta "the 4.3BSD UNIX(R) operating system" ve "the 4.4BSD operating system" isimlerini görebilirsiniz.
. BSD ile ilgili olarak akılda kalan genellikle dağınık ve saldırgan olduðudur. There is a perception that the BSD projects are fragmented and belligerent. http://interactive.wsj.com/bin/login?Tag=/&URI=/archive/retrieve.cgi%253Fid%253DSB952470579348918651.djm&[Wall Street Journal]'da bir makalede BSD projelerinin "balkan" ülkelerinin ürünü olduğundan bahsedildi. Davada olduğu gibi burada da akılda kalan bu tip düşünceler BSD'nin geçmişteki konumu ve durumudur.

== BSD ve Linux nasıl karşılaştırması

Linux (mesela Debian Linux) ile BSD arasındaki asıl farklılık nedir? Normal kullanıcılar için fark asında çok küçüktür yani ikiside UNIX(R) benzeri işletim sistemidir. Her ikisi de ticari olmayan amaçlar için geliştirildi (Tabii ki bu diğer bazı ticari Linux dağıtımlarındaki gibi değildir). Bu bölümde BSD'nin yapısına bakıp Linux ile karşılaştıracağız. Genel olarak söylediklerimiz FreeBSD 'ye yakın olacak çünkü yaygın olarak kullanýlan BSD versiyonu FreeBSD 'dir.

=== BSD'nin sahibi kimdir?

Hiç kimse veya hiçbir kuruluş BSD 'nin sahibi değildir. BSD bütün dünya üzerinde teknik olarak üst düzeyde ve uzman bir çok insan tarafından geliştirildi ve BSD 'nin bazı bileşenleri farklı açık kaynak kod geliştiricileri tarafından sağlandı.

=== BSD nasıl geliştirildi ve güncellendi?

BSD çekirdeği Açık kaynak geliştirim modeli ile geliştirilmiştir. Her proje erişimi herkese açık olan _kaynak kodu ağacı_ altında http://www.sourcegear.com/CVS/[Concurrent Versions System] (CVS) ile dağıtıldı. Bu sistemde BSD ile alakalı doküman ve diğer dosyalar da bulunmaktadır. CVS ile herhangi bir kişi "check out" (yani gerekli dosyaların bir kopyasını sistemine indirerek) yaparak sistemin herhangi bir bolümüne sahip olabilmektedir.

Dünya üzerinde oldukça fazla sayıda programcı BSD 'nin gelişimine katkıda bulunur. Bu programcı ve geliştiriciler temelde üç kısma ayrılır:

* _Contributors(Katkıda Bulunanlar)_ doküman ya da kod yazarlar. Bu grubun direk olarak kod ağacına herhangi bir kod eklenmelerine izin verilmez. Bu kişilerin yazdığı kodlar _committer_ tarafından incelenip ana sistemde dahil edilirler.
* _Committers_ kaynak ağacına kod ekleme yetkisinde sahip geliştiriciler. Committer olabilmek için çalıştığı alan üzerinde çok yüksek bilgi seviyesine sahip olması gerekir.
+ 
Bazı commiterler bütün kaynak koduna ulaşma yetkisine sahiptirler diğerleri ise gerçek koddan ayrı tutulurlar. Dökümantasyonla ilgilenenler normal olarak çekirdek koduna ulaşma yetkisine sahip değillerdir. Principal Architect olarak adlandırılan çekirdek takımındaki bazı kişilerin ise _back out_ adı verilen kaynak kodu ağacındaki kodları silme hakkı vardır. Bütün committer 'lar yapılan her bir commit (işlem) için e-posta alırlar ve böylece gizlice bir kodun kaynak kodu ağacına girmesi engellenmiş olur.
* _Core team (Çekirdek Takımı)_. FreeBSD ve NetBSD kesinlikle bir çekirdek takıma sahiptir. Çekirdek takım projenin gelişimi ve oluşturulması sırasında programlarını yaparlar ve rolleri tam olarak belli değildir. Çekirdek takımı üyesi olmak için program geliştiricisi (developer) olma zorunluluðu yoktur ve bu da son derece normaldir. Çekirdek takım için kurallar bir projeden diğerine farklılık gösterebilir ve genel olarak çekirdek takımın projenin gelişme ve gidişat noktasındaki görüş ve fikirleri kesinlikle Çekirdek Takım üyesi olmayan kişilerin görüş ve fikirlerinden daha üstün tutulur.

İşte bütün bu düzenlemeler Linux'tan birçok noktada farklılık gösterir:

. Hiç kimse sistem içeriğini kontrol edemez. Pratikte bu farklılık göze çok önemli gelebilir. Asıl mimar (Chief Architect) kodun asıl koddan çıkartılması isteğinde bulunabilir ve hatta Linux projelerinde birçok kişi değişiklikler yapabilir.
. Diğer taraftan merkezi bir depo vardır. Bu depo eski tüm versiyonlarda dahil olmak üzere bir noktada toplanmış olarak işletim sistemine ait tüm kodları barındırır.
. BSD projeleri yalnızca kernel (çekirdek) olarak değil "bütün işletim sistemi" olarak kabul edilir. Bu özellik yalnızca marjinal olarak faydalıdır. Ne BSD ne de Linux programlar olmadan yararlı değildir. Ve bu programlar Linux altında BSD altında kullanıldığı gibi kullanılır.
. CVS kod ağacının (source tree) biçimlendirilmiş olmasının bir neticesi olarak BSD gelişim evreleri gayet açıktır ve herhangi bir versiyona ait bilgi versiyon numarası ya da piyasaya sürülme tarihi ile bulunabilir. Hatta CVS güncellemelere izin bile verir. Örneğin FreeBSD deposu ortalama günde 100 kez güncellenir ancak bu güncellemeler çoğu zaman çok küçüktür. 

=== BSD Sürümleri

Her BSD projesi üç tane farklı sürüm içerir. Linux'taki gibi bu sürümler 1.4.1 ya da da 3.5.0 olarak belirlenir. Ek olarak versiyon numaraları kendi amacını belirten bir son eke sahiptir:

. Geliştirilmiş olan versiyon _CURRENT_ (Geçerli En Son) olarak adlandırılır. FreeBSD'de CURRENT'a bir numara atanır. Örneğin FreeBSD 5.0-CURRENT. NetBSD açık bir biçimde farklı isimlendirme şeması kullanır. Kullanılan bu şema tek harften oluþan bir son ektir ki bu son ek dahili arayüzdeki değişikliği ifade eder. Örneğin NetBSD 1.4.3G gibi. OpenBSD her hangi bir numara ataması yapmaz (OpenBSD-current). Bütün yeni sürümler sistemde bu şekilde kullanılır.
. Belirli aralıklarla yılda iki ila dört defa projeler CD-ROM ile edinme yada FTP sitelerinden ücretsiz olarak indirmek için piyasaya sürülür (RELEASE). Örneğin OpenBSD 2.6 RELEASE. Yada NetBSD 1.4-RELEASE. Piyasaya sürülen _Sürüm_ (RELEASE) versiyonu son kullanıcı için gerekli olan sürümdür ve sistemin normal versiyonudur. Ayrıca NetBSD ayrıca _yama sürümleri_ (patch releases) Örneğin NetBSD 1.4.2 gibi. Bu sürümler üç basamaklıdır.
. RELEASE versiyonlarda herhangi bir hata (bug) bulunduğunda hatalar düzeltilir ve CVS kaynak kodu ağacına (source tree) dahil edilir. FreeBSD 'de son elde edilen sürüm _STABLE_ (sağlam versiyon) olarak adlandırılır ancak OpenBSD ve NetBSD RELEASE versiyon ismini kullanmaya devam eder. CURRENT versiyonun test edilmesi sırasında yeni ama küçük özellikler sisteme dahil edilebilir.

_Bütün bunların aksine Linux 'ta iki ayrı kod ağacı (code tree) vardır: Stable (Sağlam) versiyon ve Development (Gelişmekte olan) versiyon. Stable versiyon çift sayılardan oluşan minor versiyon numaralarına sahiptir. 2.0, 2.2, 2.4 gibi. Development versiyon ise tek sayılardan oluşan minor versiyon numaralarına sahiptir. 2.1, 2.3, 2.5 gibi. Bazı durumlarda değişik Linux dağıtım firmaları kendi geliştirdikleri ürünleri "TurboLinux 6.0 with kernel 2.2.14"_ şeklinde piyasaya sürebilir.

=== BSD 'nin hangi versiyonları bulunabilir?

Birçok Linux sürümünün aksine açık kaynak kodu olan yalnızca üç tane BSD sürümü vardır. Her BSD projesi kendi kod ağacına (source tree) ve çekirdeğine sahiptir. Ve pratikte kullanıcıların projelere kendi ekledikleri kodlarla Linux'taki kodlar arasında daha az farklılık vardır.

Her projenin amacını gruplamak gerçekten zordur: Farklılıklar kişilere özeldir. Genel olarak:

* FreeBSD yüksek performans ve son kullanıcılar için kullanım kolaylığı amacını güder. Ve ISP firmaları için favori işletim sistemdir. PCler ve Compaq 'ın Alpha işlemcileri üzerinde calışır. FreeBSD açık bir farkla diğer projelere oranla daha fazla kişi taraından kullanılır.
* NetBSD azami seviyede taşınılabilirlik hedefler. "NetBSD üzerinde elbette çalışır!" ile de bu belirtilmiş olur. Ek olarak sade dizayna sahip olmak önemlidir. NetBSD laptoplardan büyük sunuculara kadar her platformda çalışır ve NASA'nın uzay çalışmalarında da kullanılmıştır. Özel olarakda Intel-olmayan donanımlar için iyi seçimdir.
* OpenBSD kod temizliğini ve güvenliğini hedef alır. Açık kaynak kod geliştirim modeli ve sıkı kod incelemesini içerir ve banka ABD hükümet bakanlıkları, hisse senedi kurumları gibi güvenlik temelli işletmeler için bir işletim sistemi olmayı hedefler. NetBSD gibi birçok platformda çalışabilir.

Bunlardan başka açık kod olmayan iki değişik BSD UNIX(R) işletim sistemi mevcuttur. Bunlar BSD/OS ve Apple 'ın geliştirdiği Mac OS(R) X:

* BSD/OS 4.4 BSD türetilmiş en eski sürümdür. Açık kaynak kodlu değildir ve bu sebeble kod çok küçük bir maliyetle satın alınabilir. Birçok açıdan FreeBSD 'ye benzer ve birçok geliştirici iki sistemle de çalışır.
* http://www.apple.com/macosx/server/[Mac OS(R) X] http://www.apple.com/[Apple Computer Inc.'in] Macintosh(R) serisinin en son üyesidir. Bu işletim sisteminin çekirdeği BSD tabanlıdır ve http://developer.apple.com/darwin/[Darwin], olarak adlandırılır. Diğer versiyonların aksine çekirdeği açık kaynak kodludur. Bu gelişimin bir neticesi olarak Apple geliştiricileri FreeBSD committer 'ıdır. Bu çekirdeğin üzerinde Aqua/Quartz grafik arabirimi ve Mac OS(R) 'un diğer ürünleri vardır. Fakat bu X arabiriminin kodu kapalıdır. Bu işletim sistemi x86 and PPC mimarilerinde de çalışır.

=== BSD kullanım lisansının GNU kullanım lisansından farkı nedir?

Linux kapalı kod (closed source) yazılımlarını saf dışı bırakmak için tasarlanmış http://www.fsf.org/copyleft/gpl.html[GNU General Public License] (GPL) lisansı ile dağıtılır. GPL lisanslı bir ürün kullanarak geliştirilen bir yazılım da mutlaka GPL lisansı ile dağıtılmalıdır. Fakat http://www.opensource.org/licenses/bsd-license.html[BSD lisansı] daha az kısıtlayıcıdır ve binary dağıtıma izin verir. Bu özellikle gömülü uygulamalar için çekici bir lisans türüdür.

=== Daha başka ne bilmeliyim?

BSD 'ler için Linux 'lara oranla daha az programın üretildiği zamanlarda BSD geliştiricileri Linux programlarını BSD altında çalıştırmayı sağlayan Linux uyumluluk paketini ortaya çıkardılar. Bu paket, Linux sistem çağrılarını düzgün yapabilmek için her iki çekirdek değişikliklerini ve C Library (C kütüphanesi) gibi Linux uyumluluk dosyalarını içerir. Linux programlarını Linux makinesi ile BSD makinesi altında çalıştırmak arasında hız bakımından herhangi bir kayda değer fark yoktur.

BSD 'nin "All from one supplier (Her şey tek elden)" mantığı Linux 'larda aynı sıklıkla yapılan güncelleme işlemlerinin daha kolay olduğu anlamına gelir. BSD kütüphane versiyon güncellemelerini eski versiyon kütüphaneleri ile uyumlu olarak yapar ve bu eski Binary kodlarını çalıştırmayı mümkün kılar.

=== BSD mi Linux mu kullanmalıyım?

Bunların hepsinin pratikteki anlamı nedir? Kim BSD kim Linux kullanmalı?

Bu hakikatten cevaplanması zor bir sorudur. Birkaç öneri şu şekilde sıralanabilir:

* "If it ain't broke, don't fix it" (Bozulmuyorsa düzeltme). Eğer halihazırda açık kodlu bir işletim sistemi kullanıyorsanız ve ondan memnunsanız değişiklik yapmak için iyi bir sebep yoktur.
* BSD sistemi, özellikle FreeBSD dikkate değer bir şekilde Linuxlerden daha fazla performans sağlayabilir. Fakat bu herkesi aynı derecede etkileyen bir şey değildir ve birçok durumda da yok denecek kadar az performans farkı vardır. Ama bazı özel durumlarda da Linux da FreeBSD 'den daha iyi olarak nitelendirilebilir.
* Genelde BSD sistemi güvenilirlilik açısından daha iyi bir üne sahiptir ve bu genelde daha olgun koda sahip oluşundan kaynaklanır.
* BSD lisansı GPL Lisansından daha dikkat çekicidir.
* BSD Linux kodlarını çalıştırabilir ama Linux BSD kodlarını çalıştıramayabilir. Bunun bir neticesi olarakda BSD için Linux 'tan daha fazla yazılım vardır.

=== BSD için kim yardım servis ve eğitim sağlıyor?

BSDi her zaman BSD/OS'u desteklemektedir ve yakın zaman önce FreeBSD ile bir anlaşma imzalamışlardır.

Ek olarak her projenin kendi yardım yada kiralama departmanı vardır: link:https://www.FreeBSD.org/commercial/consult_bycat/[FreeBSD], http://www.netbsd.org/gallery/consultants.html[NetBSD], and http://www.openbsd.org/support.html[OpenBSD].
