# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/articles/multi-os/Makefile
# %SRCID%	1.8

DOC?= article

FORMATS?= html
INSTALL_COMPRESSED?=gz

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
