#
# $FreeBSD$
# $RCS: fx/doc/el_GR.ISO8859-7/articles/multi-os/Makefile,v 1.1 2002/11/26 22:14:41 keramida Exp $
# Original version: 1.8
#

DOC?= article

FORMATS?= html
INSTALL_COMPRESSED?=gz
TIDYFLAGS+= -raw

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
