#
# $FreeBSD$
# Original version: 1.8
#

DOC?= article

FORMATS?= html
INSTALL_COMPRESSED?=gz
TIDYFLAGS+= -raw

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
