---
title: "Устав команды управления исходным кодом"
sidenav: about
---

= Устав команды управления исходным кодом

Команда управления исходным кодом (srcmgr) — это группа разработчиков FreeBSD, отвечающая за контроль за разработкой дерева исходного кода базовой системы FreeBSD и продуктов, создаваемых из этого дерева.
Цель этой команды — обеспечение функциональности, стабильности и производительности артефактов и выпусков базовой системы.
Базовая система собирается из git-репозитория src и включает ядро, загрузчик и пользовательские программы.

== Обязанности

Для достижения этой цели команда управления исходным кодом исполняет следующие обязанности (*Пояснительные примечания курсивом являются описательными, но не обязательными*):

* Утверждать новые и возвращаемые права на коммит для репозиториев исходного кода.
* Отзывать неиспользуемые права на коммит для репозиториев исходного кода.
* Определять и управлять деятельностью по привлечению как новых коммиттеров, так и наставников.
  _Это включает выявление активных участников, которые ещё не являются коммиттерами, и поиск наставников для новых участников среди существующих коммиттеров. Мы можем управлять любым подкомитетом, который занимается привлечением._
* Разрешать споры, связанные с репозиторием исходного кода, между участниками сообщества FreeBSD.
* Определять и поощрять здоровые нормы взаимодействия между коммиттерами и внешними участниками.
  _Например, руководства и лучшие практики для рассмотрения патчей и работы с bugmeister@ по разработке рабочих процессов приоритизации ошибок, специфичных для исходного кода._
* Определять политики внесения изменений в репозиторий исходного кода.
  _Например, кто может переносить коммиты в репозиторий и когда. Это включает явные полномочия откатывать коммиты и вводить заморозки (freezes) и т.д. Другой пример — определение того, как поддерживать политики. Эти политики будут различаться в зависимости от ветки._
* Обеспечивать создание и публикацию артефактов базовой системы.
  _Например, работа с re@ для проверки образов релизов или обеспечение своевременной публикации пакетов базовой системы._
* Определение ожиданий от коммитов в src.
  _Например, какие инструментальные цепочки поддерживаются и требуются. Требуются ли кроссплатформенные сборки или нет. Какие задачи проверяются в CI после коммита. Какие недочёты допустимы после коммита, а какие крайне нежелательны._
* Коммуникация и публикация сводных отчётов о работе в соответствии с нормами проекта.
  _Например, публикация ежемесячных или ежеквартальных отчётов, проведение открытых встреч или дискуссионных форумов, где решения принимаются открыто, так далее. Конкретные формы этих действий со временем меняются, поэтому они не детализированы в уставе._
* Взаимодействие с другими частями проекта и Основной командой (Core team), когда это необходимо для координации.
* Команда управления исходным кодом ОБЯЗАНА поддерживать строгие письменные политики для каждой из обязанностей, определённых уставом.

Пожалуйста, ознакомьтесь с link:../policies/[Политиками команды исходного кода] для получения полного списка текущих политик, которые были приняты для помощи в достижении этих целей.

== Членство

Участники с правом голоса занимают свою должность в течение одного года.
Один участник может занимать должность вплоть до трёх сроков подряд.
После перерыва как минимум в один полный срок (один год) участник снова может претендовать на дополнительные три срока.
В команду также должен входить один или несколько участников без права голоса («наблюдатели») в качестве кандидатов в будущие участники с правом голоса.
Участники с правом голоса и наблюдатели выбираются действующими участниками с правом голоса команды управления исходным кодом.
Команда управления исходным кодом обязана публиковать изменения в своём составе (участники с правом голоса и без).

Первоначальный состав команды выбирается Основной командой. Основная команда может по своему усмотрению изменить состав.

== Полномочия

Команда управления исходным кодом действует под руководством Основной команды FreeBSD.
Настоящий устав действует до тех пор, пока он не будет изменен или отозван Основной командой; любые изменения в этот устав должны быть утверждены Основной командой.
Основная команда будет курировать команду управления исходным кодом и, при необходимости, разрешать споры, связанные с ней.
