# $FreeBSD$

SUBDIR =
SUBDIR+= cvs-freebsd
SUBDIR+= dialup-firewall
SUBDIR+= explaining-bsd
SUBDIR+= formatting-media
SUBDIR+= freebsd-questions
SUBDIR+= java-tomcat
SUBDIR+= laptop
SUBDIR+= new-users
SUBDIR+= problem-reports
SUBDIR+= releng
SUBDIR+= releng-packages

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
