# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/articles/Makefile
# %SRCID%	1.39

SUBDIR = bsdl-gpl
SUBDIR+= compiz-fusion
SUBDIR+= contributing
SUBDIR+= cvs-freebsd
SUBDIR+= dialup-firewall
SUBDIR+= explaining-bsd
SUBDIR+= formatting-media
SUBDIR+= freebsd-questions
SUBDIR+= gjournal-desktop
SUBDIR+= greek-language-support
SUBDIR+= laptop
SUBDIR+= linux-users
SUBDIR+= mailing-list-faq
SUBDIR+= multi-os
SUBDIR+= nanobsd
SUBDIR+= new-users
SUBDIR+= problem-reports
SUBDIR+= releng
SUBDIR+= releng-packages

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
