# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
# $FreeBSDde: de-docproj/books/developers-handbook/kerneldebug/Makefile,v 1.2 2007/08/31 06:13:09 as Exp $
# basiert auf: 1.1
#

CHAPTERS= 	kerneldebug/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
