# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=		css
SUBDIR+=	images

.include "${DOC_PREFIX}/share/mk/web.site.mk"
