# $FreeBSD: www/en/gnome/Makefile,v 1.20 2004/11/25 04:29:18 marcus Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=		css
SUBDIR+=	images
SUBDIR+=	js

.include "${WEB_PREFIX}/share/mk/web.site.mk"
