# $FreeBSD: www/en/releases/2.0/Makefile,v 1.2 2000/11/07 04:05:23 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml
DOCS+=	credits.sgml
DOCS+=	install.sgml
DOCS+=	notes.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
