# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml credits.sgml install.sgml notes.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
