# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	faq.sgml
DOCS+=	howtoports.sgml
DOCS+=	newbies.sgml
DOCS+=	tutorials.sgml
DOCS+=	performance.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
