---
title: Capítulo 6. Aplicaciones de escritorio
part: Parte II. Tareas comunes
prev: books/handbook/partii
next: books/handbook/multimedia
---

[[desktop]]
= Aplicaciones de escritorio
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Tabla de contenidos
:table-caption: Tabla
:figure-caption: Figura
:example-caption: Ejemplo
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 6

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/es/mailing-lists.adoc[]
include::shared/es/teams.adoc[]
include::shared/es/urls.adoc[]

toc::[]

[[desktop-synopsis]]
== Sinopsis

FreeBSD puede ejecutar gran número de aplicaciones de escritorio, como navegadores y procesadores de texto. La mayoría de ellas están disponibles como packages o se pueden compilar automáticamente desde la colección de ports. Muchos usuarios nuevos esperan encontrar este tipo de aplicaciones en su escritorio. Este capítulo mostrará cómo instalar de forma fácil algunas aplicaciones populares, bien como packages o desde la colección de ports.

Tenga en cuenta que cuando se instalan programas desde los ports se compilan desde el código fuente. Esto puede tardar muchísimo tiempo, dependiendo de qué esté compilando y la potencia de proceso de su máquina. Si compilar una o más aplicaciones le requiere una cantidad de tiempo desmesurada para sus necesidades recuerde que puede instalar la mayoría de programas de la Colección de Ports como packages precompilados.

FreeBSD tiene compatibilidad binaria con Linux(R), así que muchas aplicaciones originariamente desarrolladas para Linux existen también para su escritorio. Le recomendamos encarecidamente que lea el crossref:linuxemu[linuxemu,Compatibilidad binaria con Linux] antes instalar aplicaciones Linux. Muchos de los ports que usan la compatibilidad binaria de Linux empiezan por «linux-». Recuérdelo cuando busque un port en particular, por ejemplo con man:whereis[1]. En el siguiente texto se asume que ha habilitado usted la compatibilidad binaria de Linux antes de instalar aplicaciones de Linux.

Estas son las categorías que cubre este capítulo:

* Navegadores (como Mozilla, man:getenv[3], Opera, Firefox, Konqueror)
* Productividad (como KOffice, AbiWord, The GIMP, OpenOffice.org)
* Visores de documentos (como Acrobat Reader(R), gv, Xpdf, GQview)
* Finanzas (como GnuCash, Gnumeric, Abacus)

Antes de leer este capítulo, usted debería:

* Saber como instalar software de terceros (crossref:ports[ports,Instalación de aplicaciones: «packages» y ports]).
* Saber como instalar software de Linux (crossref:linuxemu[linuxemu,Compatibilidad binaria con Linux]).

Si quiere más información sobre cómo conseguir un entorno un entorno multimedia en FreeBSD consulte el crossref:multimedia[multimedia,Multimedia]. Si quiere configurar y usar el correo electrónico consulte el crossref:[mail,Correo Electrónico].

[[desktop-browsers]]
== Navegadores

FreeBSD no trae ningún navegador preinstalado, pero en el directorio http://www.FreeBSD.org/ports/[www] de la colección de ports tiene muchos navegadores listos para instalar. Si no tiene tiempo para compilarlo todo (esto puede requerir muchísimo tiempo en algunos casos) muchos de ellos están disponibles como packages.

KDE y GNOME ya proporcionan navegadores HTML. Consulte la crossref:x11[x11-wm,Entornos de escritorio] para más información sobre cómo configurar estos escritorios.

Si busca navegadores ligeros tiene en la colección de ports package:www/dillo[], package:www/links[], o package:www/w3m[].

Esta sección cubre estas aplicaciones:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Nombre de aplicación
| Recursos necesarios
| Instalación desde los Ports
| Dependencias importantes

|Mozilla
|pesado
|pesado
|Gtk+

|Opera
|ligero
|ligero
|Versiones para FreeBSD y Linux disponibles. La versión de Linux depende de la compatibiliad binaria de Linux y de linux-openmotif.

|Firefox
|medio
|pesado
|Gtk+

|Konqueror
|medio
|pesado
|KDE Librerís
|===

=== Mozilla

Mozilla es una navegador moderno y estable que dispone de soporte completo en FreeBSD: dispone de un motor de presentación de HTML muy ajustado a los estándares, tiene cliente de correo electrónico, lector de noticias e incluso ofrece un editor de páginas HTML por si quiere crear páginas web. Los usuarios de man:getenv[3] encontrarán semejanzas con la suite Communicator, dado que ambos navegadores comparten parte de la base de desarrollo.

En máquinas lentas, con una CPU de velocidad inferior a 233MHz o con menos de 64MB de RAM, Mozilla puede consumir demasiados recursos para poder utilizarse. Puede usar el navegador Opera, mucho más ligero, que se describe más adelante en este mismo capítulo.

Si no puede o no quiere compilar Mozilla por algún motivo, el equipo de FreeBSD GNOME ya lo ha hecho por usted. Instale el package desde la red del siguiente modo:

[source,bash]
....
# pkg_add -r mozilla
....

Si no hay package disponible y tiene suficiente tiempo y espacio en el disco puede obtener el código de Mozilla, compilarlo e instalarlo en su sistema. Esto se hace con:

[source,bash]
....
# cd /usr/ports/www/mozilla
# make install clean
....

El port de Mozilla se asegura de que se inicialice adecuadamente ejecutando la configuración del registro «chrome» con privilegios de `root`, aunque si quiere instalar algún añadido como «mouse gestures» (gestos del ratón) tendrá que ejecutar que correr Mozilla como `root` para que se instale correctamente.

Una vez efectuada la instalación de Mozilla no es necesario ser `root` por más tiempo. Puede arrancar Mozilla como navegador escribiendo:

[source,bash]
....
% mozilla
....

Puede arrancarlo directamente como lector de correo y noticias del siguiente modo:

[source,bash]
....
% mozilla -mail
....

=== Firefox

Firefox es un navegador de nueva generación basado en el código fuente de Mozilla. Mozilla es una suite completa de aplicaciones en la que encontrará un navegador, un cliente de correo, un cliente de chat y muchas otras. Firefox es solamente un navegador, lo que hace que sea mucho más pequeño y ligero.

Puede instalarlo como package del siguiente modo:

[source,bash]
....
# pkg_add -r firefox
....

Si prefiere compilar el código fuente e instalarlo desde los ports puede hacer esto otro:

[source,bash]
....
# cd /usr/ports/www/firefox
# make install clean
....

[[moz-java-plugin]]
=== Firefox, Mozilla y el «plugin» Java(TM)

[NOTE]
====
En esta sección y en la siguiente asumiremos que ya ha instalado Firefox o Mozilla.
====

La FreeBSD Foundation disponde una licencia de Sun Microsystems que le permite distribuir binarios FreeBSD del Java Runtime Environment (JRE(TM)) y del Java Development Kit (JDK(TM)). Puede descargar packages binarios para FreeBSD desde el http://www.freebsdfoundation.org/downloads/java.shtml[sitio web] de la FreeBSD Foundation.

Para añadir soporte Java(TM) a Firefox o Mozilla tiene que instalar el port the package:java/javavmwrapper[]. Después descargue el package Diablo JRE(TM) desde http://www.freebsdfoundation.org/downloads/java.shtml[http://www.freebsdfoundation.org/downloads/java.shtml] e instálelo con man:pkg_add[1].

Arranque su navegador, introduzca `about:plugins` en la barra de navegación y pulse kbd:[Intro]. Verá una página con una lista de los «plugins» que tenga instalados; el «plugin» Java(TM) debería ser uno de los que aparezcan. Si no es así ejecute (como `root`) lo siguiente

[source,bash]
....
# ln -s /usr/local/diablo-jre1.6.0/plugin/i386/ns7/libjavaplugin_oji.so \
  /usr/local/lib/browser_plugins/
....

y reinicie su navegador.

=== Opera

Opera es un navegador muy rápido, completo y que cumple con los estándares. Hay dos versiones: la versión «nativa» de FreeBSD y la versión que se ejecuta bajo la emulación de Linux. Para cada sistema operativo hay una versión gratuita que muestra publicidad y otra sin publicidad que se puede comprar en http://www.opera.com/[la página web de Opera].

Para navegar por la web con la versión para FreeBSD de Opera tendrá que instalar el package:

[source,bash]
....
# pkg_add -r opera
....

Algunos sitios FTP no tienen todos los paquetes, pero puede instalarlo desde la Colección de Ports:

[source,bash]
....
# cd /usr/ports/www/opera
# make install clean
....

Si quiere instalar la versión de Linux de Opera ponga `linux-opera` en lugar de `opera` en los atnteriores ejemplos. La versión de Linux es útil en situaciones donde se necesitan «plugins» de los que sólo hay versiones para Linux, como Adobe Acrobat Reader(R). En todos los demás aspectos las versiones de FreeBSD y Linux son iguales.

=== Konqueror

Konqueror forma parte de KDE pero también se puede instalar y usar independienmente de KDE instalando package:x11/kdebase3[]. Konqueror es mucho más que un navegador, también es gestor de ficheros y visor multimedia.

Konqueror también trae un conjunto de «plugins», disponibles en package:misc/konq-plugins[].

Konqueror también soporta Flash(TM), hay un tutorial en http://freebsd.kde.org/howto.php[http://freebsd.kde.org/howto.php].

[[desktop-productivity]]
== Productividad

Cuando se trata de productividad, normalmente los nuevos usuarios piensan en una buena suite ofimática o un procesador de textos amigable. Mientras que algunos crossref:x11[x11-wm,entornos de escritorio] como KDE ofrecen una suite ofimática propia, no hay una aplicación por defecto. FreeBSD permite usar todo lo que se necesite sin importar qué entorno de escritorio use.

Esta sección cubre estas aplicaciones:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Nombre de la aplicación
| Recursos necesarios
| Instalación desde los ports
| Dependencias importantes

|KOffice
|ligero
|pesado
|KDE

|AbiWord
|ligero
|ligero
|Gtk+ o GNOME

|The Gimp
|ligero
|pesado
|Gtk+

|OpenOffice.org
|pesado
|enorme
|GCC 3.1, JDK(TM) 1.3, Mozilla
|===

=== KOffice

La comunidad de KDE ha dotado su entorno de escritorio con una suite ofimática totalmente independiente de KDE. Incluye los 4 componentes estándar que se pueden encontrar en otras suites ofimáticas. KWord es el procesador de textos, KSpread es la hoja de cálculo, KPresenter se encarga de las presentaciones y Kontour le permite dibujar documentos gráficos.

Antes de instalar el último KOffice asegúrese de que tiene una versión actualizada de KDE.

Para instalar KOffice como un paquete ejecute la siguiente orden:

[source,bash]
....
# pkg_add -r koffice
....

Si el paquete no está disponible puede usar la colección de ports. Por ejemplo, para instalar KOffice para KDE3 haga lo siguiente:

[source,bash]
....
# cd /usr/ports/editors/koffice-kde3
# make install clean
....

=== AbiWord

AbiWord es un procesador de textos libre con un aspecto parecido a Microsoft(R) Word. Es útil para escribir documentos, cartas, informes, notas, etc. Es muy rápido, tiene muchas opciones y es muy amigable.

AbiWord puede importar o exportar muchos formatos de fichero, incluyendo algunos propietarios como Microsoft [.filename]#.doc#.

AbiWord está disponible como package. Si quiere instalarlo haga lo siguiente:

[source,bash]
....
# pkg_add -r AbiWord2
....

Si el package no está disponible por el motivo que fuere puede instalarlo desde la colección de Ports. La colección de ports debería estar más actualizada:

[source,bash]
....
# cd /usr/ports/editors/AbiWord2
# make install clean
....

=== The GIMP

GIMP es un programa de manipulación de imágenes muy sofisticado que le permitirá también crearlas y retocarlas. Puede usarlo como un programa de dibujo sencillo o como una sofisticada herramienta de retoque fotográfico. Admite una gran cantidad de «plug-ins» y tiene opciones tan interesantes como una interfaz para «scripts». GIMP puede leer y escribir un gran número de formatos de fichero. Soporta escáners y tabletas gráficas.

Instale el package mediante la siguiente orden:

[source,bash]
....
# pkg_add -r gimp
....

Si su servidor FTP no tiene este package puede usar la colección de ports. El directorio http://www.FreeBSD.org/ports/[graphics] de la colección de ports también contiene The Gimp Manual. Si quiere instalarlo haga lo siguiente:

[source,bash]
....
# cd /usr/ports/graphics/gimp
# make install clean
# cd /usr/ports/graphics/gimp-manual-pdf
# make install clean
....

[NOTE]
====
El directorio http://www.FreeBSD.org/ports/[graphics] de la colección de ports tiene la versión de desarrollo de GIMP en package:graphics/gimp-devel[]. Hay una versión en HTML de The Gimp Manual en package:graphics/gimp-manual-html[].
====

=== OpenOffice.org

OpenOffice.org incluye todas las aplicaciónes esenciales en una completa suite ofimática: un procesador de textos, una hoja de cálculo, un gestor de presentaciones y un programa de dibujo. Su interfaz de usuario es muy parecida a otras suites ofimáticas y puede importar y exportar diversos formatos muy extendidos. Está disponible en diversos idiomas; el proceso de internacionalización incluye interfaces, correctores ortográficos y diccionarios.

El procesador de textos de OpenOffice.org usa un fichero XML nativo para aumentar la portabilidad y la eficiencia. El programa de hojas de cálculo tiene un lenguaje de macros y puede usarse desde bases de datos externas. OpenOffice.org es estable y hay versiones nativas para Windows(R), Solaris(TM), Linux, FreeBSD, y Mac OS(R) X. Tiene más información sobre OpenOffice.org en http://www.openoffice.org/[la página web de OpenOffice]. Si quiere información específica para FreeBSD, o si quiere bajar directamente los packages use la página web de http://porting.openoffice.org/freebsd/[FreeBSD OpenOffice Porting Team].

Para instalar OpenOffice.org ejecute:

[source,bash]
....
# pkg_add -r openoffice
....

[NOTE]
====
Si usa una versión -RELEASE de FreeBSD todo lo antedicho funcionará. Si usa cualquier otra versión visite el sitio web del FreeBSD OpenOffice.org Porting Team, desde el cual podrá descargar e instalar el package más adecuado e instalarlo mediante man:pkg_add[1]. En este sitio web encontrará tanto una versión current como la de desarrollo.
====

Una vez instalado el package escriba la siguiente orden para ejecutar OpenOffice.org:

[source,bash]
....
% openoffice.org
....

[NOTE]
====
En el primer arranque se le harán diversas preguntas se creará un directorio [.filename]#.openoffice.org2# en su «home».
====

Si no hay packages de OpenOffice.org disponibles siempre tiene la opción de compilar el port. Tenga muy en cuenta que necesitará gran cantidad de espacio en disco y que este port necesita una cantidad de tiempo monstruosa para efectuar la compilación.

[source,bash]
....
# cd /usr/ports/editors/openoffice.org-2
# make install clean
....

[NOTE]
====
Si quiere compilar una de las muchas versiones que existen en idiomas distintos del inglés sustituya la orden anterior por la que se muestra a continuación:

[source,bash]
....
# make LOCALIZED_LANG=su_idioma install clean
....

Sustituya _su_idioma_ por el código ISO del idioma que quiera. Tiene una lista de códigos de idioma disponibles dentro del directorio del port en [.filename]#files/Makefile.localized#.
====

Hecho esto puede ejecutar OpenOffice.org con la orden:

[source,bash]
....
% openoffice.org
....

[[desktop-viewers]]
== Visores de documentos

Desde la aparición de UNIX(R) han ido apareciendo formatos de documento de lo más diverso, alguno de los cuales se ha hecho muy popular. Los visores de documentos estándar que requieren no tienen por qué estar en el sistema base. En esta sección veremos cómo instalar estos visores.

Esta sección cubre las siguientes aplicaciones:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Nombre de la aplicación
| Recursos necesarios
| Instalación desde los ports
| Dependencias importantes

|Acrobat Reader(R)
|ligero
|ligero
|Compatibilidad binaria de Linux

|gv
|ligero
|ligero
|Xaw3d

|Xpdf
|ligero
|ligero
|FreeType

|GQview
|ligero
|ligero
|Gtk+ o GNOME
|===

=== Acrobat Reader(R)

Muchos documentos se distribuyen en formato PDF, siglas de «Portable Document Format». Uno de los visores recomendados para este tipo de ficheros es Acrobat Reader(R), un producto de Adobe para Linux. Dado que FreeBSD puede ejecutar binarios de Linux también existe para FreeBSD.

Para instalar Acrobat Reader(R) 7 desde la Colección de Ports ejecute:

[source,bash]
....
# cd /usr/ports/print/acroread7
# make install clean
....

No hay package debido a las restricciones que impone la licencia del software.

=== gv

gv es un visor de PostScript(R) y PDF. Tiene su origen en ghostview pero tiene un aspecto bastante mejorado gracias a la librería Xaw3d. Es rápido y tiene una interfaz limpia. gv tiene muchas opciónes como orientación, tamaño del papel, escalado o antialias. Casi todas las operaciones se pueden realizar desde el teclado o desde el ratón.

Para instalar gv como package ejecute:

[source,bash]
....
# pkg_add -r gv
....

Si no puede obtener el package puede usar la colección de ports:

[source,bash]
....
# cd /usr/ports/print/gv
# make install clean
....

=== Xpdf

Si quiere un visor de PDF pequeño, Xpdf es un visor ligero y eficiente. Requiere muy pocos recursos y es muy estable. Usa los tipos estándar de X y no depende de Motif(R) ni de ningún otro «toolkit» de X.

Para instalar el package de Xpdf use la siguiente orden:

[source,bash]
....
# pkg_add -r xpdf
....

Si el paquete no está disponible o prefiere usar la colección de ports ejecute:

[source,bash]
....
# cd /usr/ports/graphics/xpdf
# make install clean
....

Una vez que la instalación haya concluido puede lanzar Xpdf; use el botón derecho del ratón para activar el menú.

=== GQview

GQview es un visor de imágenes. Puede ver un fichero con un click, lanzar un editor externo, obtener imágenes de previsualización y muchas cosas más. También tiene un modo de presentación y admite algunas opciones básicas de manipulación de ficheros. Puede gestionar colecciones de imágenes y encontrar ficheros duplicados con facilidad. GQview puede mostrar las imágenes a pantalla completa y está preparado para la internacionalización.

Si quiere instalar el paquete de GQview ejecute:

[source,bash]
....
# pkg_add -r gqview
....

Si el paquete no está disponible o prefiere usar la colección de ports ejecute:

[source,bash]
....
# cd /usr/ports/graphics/gqview
# make install clean
....

[[desktop-finance]]
== Finanzas

Si por algun motivo quisiera gestionar sus finanzas personales en su escritorio FreeBSD hay algunas aplicaciones potentes y sencillas de utilizar que puede instalar. Algunas de ellas son compatibles con formatos muy extendidos como documentos de Quicken o Excel.

Esta sección cubre las siguientes aplicaciones:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Nombre de aplicación
| Recursos necesarios
| Instalación desde los ports
| Dependencias importantes

|GnuCash
|ligero
|pesado
|GNOME

|Gnumeric
|ligero
|pesado
|GNOME

|Abacus
|ligero
|pesado
|Tcl/Tk

|KMyMoney
|ligero
|pesado
|KDE
|===

=== GnuCash

GnuCash es parte del afán de GNOME por ofrecer aplicaciones de uso sencillo pero a la vez potentes a los usuarios. Con GnuCash, puede gestionar sus ingresos y sus gastos, sus cuentas bancarias o sus acciones. Tiene una interfaz intuitiva pero muy profesional.

GnuCash dispone de un registro elegante, un sistema jerárquico de cuentas, muchos atajos de teclado y métodos de autocompletado. Puede dividir una transacción en varias partes más detalladas. GnuCash puede importar y mezclar ficheros QIF de Quicken. También admite muchos formatos internacionales de fecha y moneda.

Para instalar GnuCash en su sistema ejecute:

[source,bash]
....
# pkg_add -r gnucash
....

Si el paquete no está disponible puede usar la colección de ports:

[source,bash]
....
# cd /usr/ports/finance/gnucash
# make install clean
....

=== Gnumeric

Gnumeric es una hoja de cálculo que forma parte del entorno de escritorio GNOME. Implementa una «predicción» automática de la entrada del usuario de acuerdo con el formato de celda y un sistema de completado automático para múltiples secuencias. Puede importar ficheros de un gran número de formatos muy extendidos, como Excel, Lotus 1-2-3 o Quattro Pro. Gnumeric soporta gráficas mediante el programa de gráficas package:math/guppi[]. Tiene un gran námero de funciones internas y permite todos los formatos normales de celda como número, moneda, fecha, hora y muchos más.

Para instalar Gnumeric como package ejecute:

[source,bash]
....
# pkg_add -r gnumeric
....

Si el package no está disponible puede usar la colección de ports del siguiente modo:

[source,bash]
....
# cd /usr/ports/math/gnumeric
# make install clean
....

=== Abacus

Abacus es una hoja de cálculo pequeña y fácil de usar. Tiene muchas funciones útiles en varios ámbitos como la estadística, las finanzas y las matemáticas. Puede importar y exportar ficheros con formato Excel. Abacus puede generar ficheros PostScript(R).

Para instalar Abacus como package ejecute:

[source,bash]
....
# pkg_add -r abacus
....

Si no hay package al alcance puede usar la colección de ports:

[source,bash]
....
# cd /usr/ports/deskutils/abacus
# make install clean
....

[[desktop-summary]]
== Resumen

FreeBSD está muy extendido en ISP por su alto rendimiento y estabilidad, pero también se puede usar a diario como escritorio. Hay miles de aplicaciones disponibles como http://www.FreeBSD.org/where/[packages] o http://www.FreeBSD.org/ports/[ports] con las que puede crear un escritorio que cubra todas sus necesidades.

Aqui hay un resumen de todas las aplicaciones cubiertas en este cápitulo:

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Nombre De La Aplicación
| Nombre Del Paquete
| Nombre Del Port

|Mozilla
|`mozilla`
|package:www/mozilla[]

|Opera
|`opera`
|package:www/opera[]

|Firefox
|`firefox`
|package:www/firefox[]

|KOffice
|`koffice-kde3`
|package:editors/koffice-kde3[]

|AbiWord
|`AbiWord2`
|package:editors/AbiWord2[]

|GIMP
|`gimp`
|package:graphics/gimp[]

|OpenOffice.org
|`openoffice`
|package:editors/openoffice-1.1[]

|Acrobat Reader(R)
|`acroread`
|package:print/acroread7[]

|gv
|`gv`
|package:print/gv[]

|Xpdf
|`xpdf`
|package:graphics/xpdf[]

|GQview
|`gqview`
|package:graphics/gqview[]

|GnuCash
|`gnucash`
|package:finance/gnucash[]

|Gnumeric
|`gnumeric`
|package:math/gnumeric[]

|Abacus
|`abacus`
|package:deskutils/abacus[]

|KMyMoney
|`kmymoney2`
|package:finance/kmymoney2[]
|===
