---
title: "FreeBSD 3.2 Errata Notes"
sidenav: download
--- 

= FreeBSD 3.2 Errata Notes

....
The file 
ERRATA.TXT contains post-release ERRATA for 3.2 and should always
be considered the definitive place to look *first* before reporting
a problem with this release.  This file will also be periodically
updated as new issues are reported so even if you've checked this
file recently, check it again before filing a bug report.  Any
changes to this file are also automatically emailed to:

    freebsd-stable@FreeBSD.org

For all FreeBSD security advisories, see:

ftp://ftp.FreeBSD.org/pub/FreeBSD/CERT/

For the latest information.

---- Security Advisories:

Current active security advisories for 3.2:     None

---- System Update Information:

o The compat20 and compat21 distributions install themselves into
  /usr/lib/compat.  The compat20/compat21 distributions are a.out libraries,
  thus they should live in /usr/lib/compat/aout to match the
  "ldconfig_paths_aout" configuration in /etc/defaults/rc.conf.

Fix: cd /usr/lib/compat
     mkdir -p aout
     mv lib*.so.*.* aout

o /usr/bin/gdb crashes when debugging core files from static programs

Fix: This was corrected in revision 1.3.2.2 of solib.c. Obtain the fixed
     version via CVSup (see instructions in handbook) or apply the patch
     from our CVSweb service.

o While booting the install floppy, user sees the following message
  and nothing seems to happen, nor can anything be entered from the keyboard:

     Keyboard: no

Fix: Due to a lack of space, full support for old XT/AT (84-key) keyboards
     is no longer available in the bootblocks.  Some notebook computers may
     also have this type of keyboard and if you are still using this kind of
     hardware, you will see the above message about no keyboard being found
     when you boot from an installation CD-ROM or floppy.

     As soon as you see the message, hit the space bar and you will see
     the following prompt:

       >> FreeBSD/i386 BOOT
       Default: x:xx(x,x)/boot/loader
       boot:

     Then enter `-Dh', and things should proceed normally with your keyboard
     type.  This only happens once at initial installation time and will
     not be a problem afterwards.
....

link:../../[Release Home]
