# $Id: Makefile,v 1.1 1999-08-16 22:00:10 nik Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ../../..

.include "../../../share/mk/docproj.docbook.mk"
