# $FreeBSD: www/en/community/Makefile,v 1.1 2005/10/04 05:44:55 murray Exp $
# Original Revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.sgml mailinglists.sgml newsgroups.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
