# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: r42775

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.xml \
#	relnotes.xml \
#	schedule.xml

DATA=	docbook.css \
#	errata.html \
#	hardware.html \
#	installation.html \
#	readme.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
