# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# $FreeBSD$
#
# Original revision: r38826
#
# Article: Building products using FreeBSD

DOC?=			article

FORMATS?=		html html-split
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=	gz
INSTALL_ONLY_COMPRESSED?=

SRCS=			article.xml

IMAGES_EN=		freebsd-branches.pic freebsd-organization.pic

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
