---
title: "Contattare FreeBSD"
sidenav: about
---

include::shared/it/urls.adoc[]

= Contattare FreeBSD

== Domande su FreeBSD...

Le domande riguardanti FreeBSD dovrebbero essere indirizzate alla mailing list sulle domande su FreeBSD, freebsd-questions@FreeBSD.org.

Le link:https://www.FreeBSD.org/community/mailinglists/[mailing list] sono il canale primario di supporto per gli utenti FreeBSD e coprono differenti aree tematiche. Sono inoltre disponibili numerose mailing list in lingue diverse dall'inglese. Per gli utenti di lingua italiana esistono diverse mailing list gestite dal http://www.gufi.org/[Gruppo Utenti FreeBSD Italia (GUFI)], raggiungibili a questa http://liste.gufi.org/mailman/listinfo[pagina].

== Domande sui contenuti di questo server WWW...

Le domande o i suggerimenti riguardanti la traduzione in italiano di questo sito web dovrebbero essere indirizzati ad Alex Dupre <ale@FreeBSD.org>, coordinatore del http://utenti.gufi.org/~alex/[FreeBSD Italian Documentation Project].

Le domande o i suggerimenti sulla documentazione (link:{handbook}[Manuale], link:{faq}[FAQ], link:../docs/[Libri & Articoli]) dovrebbero essere indirizzati alla mailing list sul progetto di documentazione di FreeBSD, freebsd-doc@FreeBSD.org o, alternativamente, alla mailing list sul progetto di documentazione in italiano di FreeBSD, traduzioni@gufi.org.

== Email, telefono e fax

Per ordini di CDROM: http://www.freebsdmall.com/[The FreeBSD Mall]

Per supporto commerciale: http://www.freebsdmall.com/[The FreeBSD Mall]

== link:{contributors}#staff-who/[Chi è Responsabile di Cosa]

Relazioni Pubbliche & Collegamento con le Aziende, Responsabile della Sicurezza, Postmaster, Webmaster ecc.
