# $FreeBSD$

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.xml
DOCS+=	myths.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
