#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/books/handbook/bibliography/Makefile
# %SRCID%	38826
#

CHAPTERS= 	bibliography/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
