DATA=	apache.gif apachepower.gif daemon.gif dir.gif doc.gif
DATA+=	home.gif littlelogo.gif new.gif power-button.gif
DATA+=	powerlogo.gif ugu_icon.gif wclogo.gif topbar.gif
DATA+=  1faq.gif 2faq.gif 1soft.gif 2soft.gif 1support.gif 2support.gif
DATA+=  1doc.gif 2doc.gif 1vendor.gif 2vendor.gif 1search.gif 2search.gif
DATA+=  1index.gif 2index.gif 1home.gif 2home.gif dae_up2.gif bar.gif
DATA+=  freebsd_1.gif flash.gif 2flash.gif 1get.gif 2get.gif
DATA+=  1handboo.gif 2handboo.gif powerani.gif pbfbsd2.gif
.include "../web.mk"
