# $Id: Makefile,v 1.2 1998-06-17 18:14:52 wosch Exp $

.if exists(Makefile.conf)
.include "Makefile.conf"
.endif

DOCS=  current.sgml doc-set.sgml sgml.sgml submitting.sgml who.sgml 
DOCS+=  translations.sgml

.include "../web.mk"
