---
title: Bijlage C. Bronnen op Internet
part: Deel V. Appendix
prev: books/handbook/bibliography
next: books/handbook/pgpkeys
---

[appendix]
[[eresources]]
= Bronnen op Internet
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Inhoudsopgave
:table-caption: Tabel
:figure-caption: Afbeelding
:example-caption: Voorbeeld
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: C

include::shared/mirrors.adoc[]
include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/nl/mailing-lists.adoc[]
include::shared/nl/teams.adoc[]
include::shared/nl/urls.adoc[]

Door de snelle ontwikkeling van FreeBSD zijn gedrukte media niet zo praktisch om de laatste ontwikkelingen te volgen. Elektronische bronnen zijn de beste, en vaak de enige, om op de hoogte te blijven van de laatste ontwikkelingen. Omdat FreeBSD draait op de inzet van vrijwilligers, is de gebruikersgemeenschap vaak een soort "technische ondersteuningsgroep", die heeft ontdekt dat email, webfora, en USENET de meeste effectieve manieren zijn om de gebruikersgemeenschap te bereiken.

Hieronder staan de meest belangrijke contactmogelijkheden met de FreeBSD gebruikersgemeenschap beschreven. Mochten er andere bronnen zijn die hier niet beschreven zijn, laat die dan weten aan de {freebsd-doc}, zodat ze hier ook beschreven kunnen worden.

[[eresources-mail]]
== Mailinglijsten

De mailinglijsten zijn de meest directe manier om vragen te stellen aan of een technische discussie te beginnen met een geconcentreerd FreeBSD-publiek. Er is een grote verscheidenheid aan lijsten met betrekking tot verschillende FreeBSD-onderwerpen. Door uw vragen aan de meest geschikte mailinglijst te stellen bent u ongetwijfeld verzekerd van een sneller en accurater antwoord.

De doelstellingen van de verschillende lijsten staan onderaan dit document. _Lees alstublieft de doelstellingen alvorens lid te worden of mail te sturen_. De meeste leden ontvangen tegenwoordig vaak honderden FreeBSD-gerelateerde berichten per dag, en door de doelstellingen en gebruiksregels op te stellen wordt gestreefd om zo min mogelijk ruis op de lijn te krijgen. Door de voorgaande adviezen te negeren zouden de mailinglijsten op termijn falen als een effectief communicatiemedium over het project.

[NOTE]
====
_Als u wilt testen of u naar de FreeBSD lijsten email kunt versturen, stuur dan een bericht naar {freebsd-test}._ Stuur alstublieft geen testberichten naar andere lijsten.
====

Bij twijfel over naar welke lijst te posten, kan de pagina link:{freebsd-questions-article}[Hoe de beste resultaten uit de FreeBSD-vragen mailinglijst te halen] wellicht helpen.

Alvorens naar enige lijst te posten, is het verstandig te leren hoe de mailinglijsten het beste gebruikt kunnen worden. Hoe bijvoorbeeld zich vaak herhalende discussies voorkomen kunnen worden door het document link:{mailing-list-faq}[Veel Gestelde Mailinglijstvragen] (FAQ) te lezen.

Voor alle mailinglijsten worden archieven bijgehouden die doorzocht kunnen worden op de link:https://www.FreeBSD.org/search/[FreeBSD World Wide Web server]. De met sleutelwoorden te doorzoeken archieven bieden een voortreffelijke methode om antwoorden te vinden op vaak gestelde vragen en horen geraadpleegd te worden voordat er vragen op een lijst worden gesteld. Merk op dat dit ook betekent dat berichten die naar de mailinglijsten van FreeBSD worden verzonden tot in de oneindigheid worden gearchiveerd. Overweeg, wanneer het beschermen van privacy belangrijk is, om een tweede emailadres dat weggegooid kan worden te gebruiken en om alleen publieke informatie te posten.

[[eresources-summary]]
=== Lijstsamenvatting

_Algemene lijsten:_ De volgende zijn algemene lijsten waarop vrijelijk (en aangemoedigd) geabonneerd kan worden:

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Lijst
| Doel

|link:{freebsd-advocacy-url}[freebsd-advocacy]
|FreeBSD Evangelisatie

|{freebsd-announce}
|Belangrijke gebeurtenissen en projectdoelen (gemodereerd)

|link:{freebsd-arch-url}[freebsd-arch]
|Architectuur en ontwerp discussies

|link:{freebsd-bugbusters-url}[freebsd-bugbusters]
|Discussie over het onderhoud van de FreeBSD probleemrapportendatabase en aanverwante zaken

|link:{freebsd-bugs-url}[freebsd-bugs]
|Bugbeschrijvingen

|link:{freebsd-chat-url}[freebsd-chat]
|Niet-technische onderwerpen met betrekking tot de FreeBSD-gemeenschap

|link:{freebsd-chromium-url}[freebsd-chromium]
|FreeBSD specifieke Chromium problemen

|{freebsd-current}
|Discussie over het gebruik van FreeBSD-CURRENT

|link:{freebsd-isp-url}[freebsd-isp]
|Zaken voor Internet Service Providers die FreeBSD gebruiken

|link:{freebsd-jobs-url}[freebsd-jobs]
|Werk en mogelijkheden voor het geven van advies met betrekking tot FreeBSD

|link:{freebsd-questions-url}[freebsd-questions]
|Gebruikersvragen en technische ondersteuning

|{freebsd-security-notifications}
|Beveiligingswaarschuwingen (gemodereerd)

|{freebsd-stable}
|Discussies over het gebruik van FreeBSD-STABLE

|{freebsd-test}
|Hier kunnen testberichten heengestuurd worden in plaats van naar de eigenlijke lijsten
|===

_Technische lijsten:_ De volgende lijsten zijn voor technische discussie. Het is van belang de doelstellingen te lezen alvorens lid te worden of mail te sturen omdat de richlijnen voor het gebruik en de inhoud erg strikt zijn.

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Lijst
| Doel

|{freebsd-acpi}
|Ontwikkeling van ACPI en energiebeheer

|link:{freebsd-afs-url}[freebsd-afs]
|Porten van AFS naar FreeBSD

|link:{freebsd-aic7xxx-url}[freebsd-aic7xxx]
|Ontwikkeling van stuurprogramma's voor de Adaptec(R) AIC 7xxx

|link:{freebsd-amd64-url}[freebsd-amd64]
|Porten van FreeBSD naar AMD64-systemen (gemodereerd)

|link:{freebsd-apache-url}[freebsd-apache]
|Discussie over ports met betrekking tot Apache

|link:{freebsd-arm-url}[freebsd-arm]
|Porten van FreeBSD naar ARM(R)-processors

|link:{freebsd-atm-url}[freebsd-atm]
|Het gebruik van ATM-netwerken met FreeBSD

|link:{freebsd-bluetooth-url}[freebsd-bluetooth]
|Bluetooth(R) technologie gebruiken in FreeBSD

|link:{freebsd-cluster-url}[freebsd-cluster]
|FreeBSD gebruiken in een geclusterde omgeving

|link:{freebsd-cvsweb-url}[freebsd-cvsweb]
|CVSweb onderhoud

|link:{freebsd-database-url}[freebsd-database]
|Discussie over het gebruik en de ontwikkeling van databases met FreeBSD

|link:{freebsd-desktop-url}[freebsd-desktop]
|FreeBSD gebruiken op en verbeteren voor bureaubladen

|link:{freebsd-doc-url}[freebsd-doc]
|Het maken van FreeBSD-gerelateerde documenten

|link:{freebsd-drivers-url}[freebsd-drivers]
|Apparaatstuurprogramma's schrijven voor FreeBSD

|link:{freebsd-dtrace-url}[freebsd-dtrace]
|DTrace op FreeBSD gebruiken en ontwikkelen

|link:{freebsd-eclipse-url}[freebsd-eclipse]
|Gebruikers van Eclipse IDE, hulpprogramma's, cliëntapplicaties en ports

|link:{freebsd-eol-url}[freebsd-eol]
|Ondersteuning voor FreeBSD-gerelateerde software welke niet langer ondersteund worden door het FreeBSD-project.

|link:{freebsd-embedded-url}[freebsd-embedded]
|FreeBSD gebruiken in embedded applicaties.

|link:{freebsd-emulation-url}[freebsd-emulation]
|Emulatie van andere systemen zoals Linux(R), MS-DOS(R), en Windows(R)

|link:{freebsd-firewire-url}[freebsd-firewire]
|FreeBSD FireWire(R) (iLink, IEEE 1394) technische discussie

|link:{freebsd-fs-url}[freebsd-fs]
|Bestandssystemen

|link:{freebsd-gecko-url}[freebsd-gecko]
|Discussies over de Gecko Rendering Engine

|link:{freebsd-geom-url}[freebsd-geom]
|GEOM-specifieke discussies en implementaties

|link:{freebsd-gnome-url}[freebsd-gnome]
|Porten van GNOME en GNOME applicaties

|link:{freebsd-hackers-url}[freebsd-hackers]
|Algemene technische discussies

|link:{freebsd-hardware-url}[freebsd-hardware]
|Algemene discussies over hardware voor het draaien van FreeBSD

|link:{freebsd-i18n-url}[freebsd-i18n]
|FreeBSD Internationalisatie

|link:{freebsd-ia32-url}[freebsd-ia32]
|FreeBSD op het IA-32 (Intel(R) x86) platform

|link:{freebsd-ia64-url}[freebsd-ia64]
|Porten van FreeBSD naar Intel(R)'s IA64 systemen

|link:{freebsd-infiniband-url}[freebsd-infiniband]
|Infiniband op FreeBSD

|link:{freebsd-ipfw-url}[freebsd-ipfw]
|Technische discussie over het herontwerp van de IP-firewallcode

|link:{freebsd-isdn-url}[freebsd-isdn]
|ISDN-ontwikkelaars

|link:{freebsd-jail-url}[freebsd-jail]
|Discussies over de man:jail[8]-faciliteiten.

|link:{freebsd-java-url}[freebsd-java]
|Java(TM) ontwikkelaars en mensen die JDK(TM)s porten naar FreeBSD

|link:{freebsd-kde-url}[freebsd-kde]
|Porten van KDE en KDE applicaties

|link:{freebsd-lfs-url}[freebsd-lfs]
|Porten van LFS naar FreeBSD

|link:{freebsd-mips-url}[freebsd-mips]
|Porten van FreeBSD naar MIPS(R)

|link:{freebsd-mobile-url}[freebsd-mobile]
|Discussie over mobiel computeren

|link:{freebsd-mono-url}[freebsd-mono]
|Mono en C# applicaties op FreeBSD

|link:{freebsd-mozilla-url}[freebsd-mozilla]
|Porten van Mozilla naar FreeBSD

|{freebsd-multimedia}
|Multimedia-applicaties

|link:{freebsd-new-bus-url}[freebsd-new-bus]
|Technische discussies over busarchitecturen

|link:{freebsd-net-url}[freebsd-net]
|Discussies over netwerken en TCP/IP-broncode

|link:{freebsd-numerics-url}[freebsd-numerics]
|Discussies over implementaties van hoge kwaliteit van functies in libm

|link:{freebsd-office-url}[freebsd-office]
|Kantoortoepassingen op FreeBSD

|link:{freebsd-performance-url}[freebsd-performance]
|Optimalisatie van prestaties voor installaties met hoge prestaties en/of load

|link:{freebsd-perl-url}[freebsd-perl]
|Onderhoud van een aantal ports met betrekking tot Perl

|link:{freebsd-pf-url}[freebsd-pf]
|Discussies en vragen voor het pakketfilter firewallsysteem

|link:{freebsd-platforms-url}[freebsd-platforms]
|Ports naar niet Intel(R)-architectuurplatformen

|link:{freebsd-ports-url}[freebsd-ports]
|Discussie over de Portscollectie

|link:{freebsd-ports-announce-url}[freebsd-ports-announce]
|Belangrijk nieuws en belangrijke instructies over de Portscollectie (gemodereerd)

|link:{freebsd-ports-bugs-url}[freebsd-ports-bugs]
|Discussie over bugs in ports en PR's

|link:{freebsd-ppc-url}[freebsd-ppc]
|Porten van FreeBSD naar de PowerPC(R)

|link:{freebsd-proliant-url}[freebsd-proliant]
|Technische discussie over FreeBSD op HP Proliant serverplatforms

|link:{freebsd-python-url}[freebsd-python]
|FreeBSD-specifieke zaken over Python

|link:{freebsd-realtime-url}[freebsd-realtime]
|Ontwikkeling van realtime-uitbreidingen voor FreeBSD

|link:{freebsd-rc-url}[freebsd-rc]
|Discussie over het [.filename]#rc.d#-systeem en de ontwikkeling daarvan

|link:{freebsd-ruby-url}[freebsd-ruby]
|FreeBSD-specifieke discussies over Ruby

|link:{freebsd-scsi-url}[freebsd-scsi]
|Het SCSI-subsysteem

|{freebsd-security}
|Beveiligingsonderwerpen betreffende FreeBSD

|link:{freebsd-small-url}[freebsd-small]
|FreeBSD gebruiken in embedded toepassingen, verouderd, gebruik in plaats hiervan link:{freebsd-embedded-url}[freebsd-embedded]

|link:{freebsd-snapshots-url}[freebsd-snapshots]
|Aankondigingen van ontwikkel-snapshots van FreeBSD

|link:{freebsd-sparc64-url}[freebsd-sparc64]
|Porten van FreeBSD naar op SPARC(R) gebaseerde systemen

|link:{freebsd-standards-url}[freebsd-standards]
|Volgen van de C99- en de POSIX(R) standaarden door FreeBSD

|link:{freebsd-sysinstall-url}[freebsd-sysinstall]
|Ontwikkeling van man:sysinstall[8]

|link:{freebsd-tcltk-url}[freebsd-tcltk]
|FreeBSD-specifieke discussies over Tcl/Tk

|link:{freebsd-testing-url}[freebsd-testing]
|Testen op FreeBSD

|link:{freebsd-tex-url}[freebsd-tex]
|TeX en haar toepassingen op FreeBSD overzetten

|link:{freebsd-threads-url}[freebsd-threads]
|Threading in FreeBSD

|link:{freebsd-tilera-url}[freebsd-tilera]
|FreeBSD porteren naar de Tilera CPU-familie

|link:{freebsd-tokenring-url}[freebsd-tokenring]
|Ondersteuning voor Token Ring in FreeBSD

|link:{freebsd-toolchain-url}[freebsd-toolchain]
|Onderhoud van de ingebouwde toolchain van FreeBSD

|link:{freebsd-usb-url}[freebsd-usb]
|Discussie over FreeBSD-ondersteuning voor USB

|link:{freebsd-virtualization-url}[freebsd-virtualization]
|Discussies over verscheidene virtualisatietechnieken ondersteund door FreeBSD

|link:{freebsd-vuxml-url}[freebsd-vuxml]
|Discussie over VuXML-infrastructuur

|link:{freebsd-x11-url}[freebsd-x11]
|Onderhoud en ondersteuning voor X11 op FreeBSD

|link:{freebsd-xen-url}[freebsd-xen]
|Discussies over het overbrengen van FreeBSD naar Xen(TM) - implementatie en gebruik

|link:{freebsd-xfce-url}[freebsd-xfce]
|Overbrengen en onderhouden van XFCE voor FreeBSD

|link:{freebsd-zope-url}[freebsd-zope]
|Zope voor FreeBSD - overbrengen en onderhouden
|===

_Beperkte lijsten:_ De volgende lijsten zijn voor meer gespecialiseerd publiek en algemene gebruikers hebben er waarschijnlijk niets aan. Het is verstandig om eerst naam te maken in de technische lijsten alvorens lid te worden van een van de onderstaande beperkte lijsten, zodat de gebruiken op die lijst bekend zijn.

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Lijst
| Doel

|link:{freebsd-hubs-url}[freebsd-hubs]
|Mensen die mirrorsites draaien (infrastructurele ondersteuning)

|link:{freebsd-user-groups-url}[freebsd-user-groups]
|Gebruikersgroepcoördinatie

|link:{freebsd-wip-status-url}[freebsd-wip-status]
|FreeBSD Werk-In-Uitvoering status

|link:{freebsd-wireless-url}[freebsd-wireless]
|Discussies over de ontwikkeling van de 802.11-stack, gereedschappen en stuurprogramma's.
|===

_Verkorte versie van lijsten (digest):_ Alle hierboven beschreven lijsten zijn beschikbaar in verkorte vorm. Na het lid worden van een lijst zijn de digest opties te wijzigen bij de accountopties.

_SVN-lijsten:_ De volgende lijsten zijn voor mensen met interesse in het zien van logboekberichten voor wijzigingen in verschillende onderdelen van de broncodeboom. Het zijn _Alleen-lezen_-lijsten waar geen email heen gezonden hoort te worden.

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Lijst
| Broncodegebied
| Broncodebeschrijving

|link:{svn-doc-all-url}[svn-doc-all]
|[.filename]#/usr/doc#
|Alle wijzigingen aan het doc-Subversion-reservoir (behalve [.filename]#user#, [.filename]#projects# en [.filename]#translations#)

|link:{svn-doc-head-url}[svn-doc-head]
|[.filename]#/usr/doc#
|Alle wijzigingen aan de tak "head" van het doc-Subversion-reservoir

|link:{svn-doc-projects-url}[svn-doc-projects]
|[.filename]#/usr/doc/projects#
|Alle wijzigingen in het projects-gebied van het doc-Subversion-reservoir

|link:{svn-doc-svnadmin-url}[svn-doc-svnadmin]
|[.filename]#/usr/doc#
|Alle wijzigingen aan de administratieve scripts, haken en andere configuratiegegevens van het doc-Subversion-reservoir

|link:{svn-ports-all-url}[svn-ports-all]
|[.filename]#/usr/ports#
|Alle wijzigingen aan het ports-Subversion-reservoir

|link:{svn-ports-head-url}[svn-ports-head]
|[.filename]#/usr/ports#
|Alle wijzigingen aan de tak "head" van het ports-Subversion-reservoir

|link:{svn-ports-svnadmin-url}[svn-ports-svnadmin]
|[.filename]#/usr/ports#
|Alle wijzigingen aan de administratieve scripts, haken en andere configuratiegegevens van het ports-Subversion-reservoir

|{svn-src-all}
|[.filename]#/usr/src#
|Alle wijzigingen in het src-Subversion-repository (behalve [.filename]#user# en [.filename]#projects#)

|{svn-src-head}
|[.filename]#/usr/src#
|Alle wijzigingen aan de "head"-tak van het src-Subversion-repository (de tak FreeBSD-CURRENT)

|link:{svn-src-projects-url}[svn-src-projects]
|[.filename]#/usr/projects#
|Alle wijzigingen aan het gebied [.filename]#projects# van het src-Subversion-repository

|link:{svn-src-release-url}[svn-src-release]
|[.filename]#/usr/src#
|Alle veranderingen aan het gebied [.filename]#releases# van het src-Subversion-repository

|link:{svn-src-releng-url}[svn-src-releng]
|[.filename]#/usr/src#
|Alle veranderingen aan de takken [.filename]#releng# van het src-Subversion-repository (de beveiligings- / uitgavetakken)

|link:{svn-src-stable-url}[svn-src-stable]
|[.filename]#/usr/src#
|Alle veranderingen aan alle stable-takken van het src-Subversion-repository

|link:{svn-src-stable-6-url}[svn-src-stable-6]
|[.filename]#/usr/src#
|Alle veranderingen aan de [.filename]#stable/6#-tak van het src-Subversion-repository

|link:{svn-src-stable-7-url}[svn-src-stable-7]
|[.filename]#/usr/src#
|Alle veranderingen aan de [.filename]#stable/7#-tak van het src-Subversion-repository

|link:{svn-src-stable-8-url}[svn-src-stable-8]
|[.filename]#/usr/src#
|Alle veranderingen aan de [.filename]#stable/8#-tak van het src-Subversion-repository

|{svn-src-stable-9}
|[.filename]#/usr/src#
|Alle veranderingen aan de [.filename]#stable/9#-tak van het src-Subversion-repository

|link:{svn-src-stable-other-url}[svn-src-stable-other]
|[.filename]#/usr/src#
|Alle veranderingen aan de oudere [.filename]#stable#-takken van het src-Subversion-repository

|link:{svn-src-svnadmin-url}[svn-src-svnadmin]
|[.filename]#/usr/src#
|Alle veranderingen aan de administratieve scripts, haken, en andere configuratiegegevens van het src-Subversion-repository

|link:{svn-src-user-url}[svn-src-user]
|[.filename]#/usr/src#
|Alle veranderingen aan het experimentele gebied [.filename]#user# van het src-Subversion-repository

|link:{svn-src-vendor-url}[svn-src-vendor]
|[.filename]#/usr/src#
|Alle wijzigingen aan het verkoperswerkgebied van het src-Subversion-repository
|===

[[eresources-subscribe]]
=== Hoe abonneren

Om te abonneren op een lijst kan geklikt worden op de naam van de lijst hierboven of kan op {mailman-lists-url} geklikt worden op de lijst waarin interesse bestaat. De pagina waarop de lijsten staan beschreven bevat alle informatie die nodig is om te abonneren.

Om te posten op een lijst kan een email gestuurd worden naar mailto:lijstnaam@FreeBSD.org[lijstnaam@FreeBSD.org]. Daarna wordt die doorgestuurd aan leden van de lijst in de hele wereld.

Om het abonnement op een lijst op te zeggen kan op de URL die onderaan iedere email van een lijst staat geklikt worden. Het is ook mogelijk om een email te sturen naar mailto:lijstnaam-unsubscribe@FreeBSD.org[lijstnaam-unsubscribe@FreeBSD.org] om een abonnement op te zeggen.

Hierbij nogmaals het advies om discussies op de technische mailinglijsten technisch te houden. Als er alleen interesse bestaat in belangrijke mededelingen dan wordt aangeraden te abonnneren op {freebsd-announce}, waarop zelden verkeer voorkomt.

[[eresources-charters]]
=== Lijstdoelstellingen

_Alle_ FreeBSD-mailinglijsten hebben eigen regels waaraan voldaan dient te worden bij gebruik. Als daaraan niet wordt voldaan, resulteert dat in maximaal twee (2) schriftelijke waarschuwingen van de FreeBSD Postmaster mailto:postmaster@FreeBSD.org[postmaster@FreeBSD.org], waarna na de derde overtreding de poster verwijderd wordt van alle FreeBSD-mailinglijsten en alle toekomstige mail van het adres van de verzender wordt uitgefilterd. Helaas zijn deze regels nodig, omdat het Internet van vandaag de dag een onvriendelijke omgeving is en slechts weinigen zich bewust zijn van hoe fragiel sommige mechanismen zijn.

Standaardregels:

* Het onderwerp van iedere mail dient te voldoen aan de basisdoelstellingen van de lijst waarnaar wordt gepost. Als de lijst bijvoorbeeld over technische onderwerpen gaat, dan hoort een post ook over iets technisch te gaan. Ruis en flaming doen alleen af aan de waarde van een mailinglijst voor alle leden en dat wordt niet getolereerd. Voor vrije discussie dient de {freebsd-chat} gebruikt te worden die daar speciaal voor is ingesteld.
* Bijdragen horen niet naar meer dan twee mailinglijsten verzonden te worden en alleen dan naar twee als het helder en duidelijk is dat daarvoor de noodzaak bestaat. Voor de meeste lijsten bestaat er al veel overlap in de leden en met uitzondering van de meer esoterische lijsten, zoals bijvoorbeeld "-stable & -scsi", is er eigenlijk slechts zelden aanleiding om naar meer dan een lijst te posten. Als een bericht zo is verzonden dat er meerdere mailinglijsten op de regel `Cc` staan, dan hoort de regel `Cc` weer ingekort te worden in een eventueel antwoord. _De verzender is verantwoordelijk voor zijn eigen kruisposten, wie ook een eerdere zender was._
* Persoonlijke aanvallen en profane taal (in de context van een geschil) zijn niet toegestaan. Dit geldt zowel voor gebruikers als ontwikkelaars. Grove schending van de netiquette, zoals kopiëren uit of het volledig doorsturen van persoonlijke email zonder dat daarvoor toestemming is gegeven, wordt niet op prijs gesteld. Er zijn hoe dan ook zeer weinig gevallen waarin zoiets dergelijks wel binnen de doelstelling van een lijst valt, waardoor dat soort emails op grond van de inhoud alleen al vaak reden zijn voor een waarschuwing (of ban).
* Adverteren voor niet-FreeBSD-gerelateerde producten is streng verboden en heeft direct een ban tot gevolg als helder is dat de overtreder adverteert door middel van spam.

_Individuele lijstdoelstellingen:_

{freebsd-acpi}::
_ACPI en energiebeheerontwikkeling_

link:{freebsd-afs-url}[freebsd-afs]::
_Andrew Bestandssysteem (Andrew File System)_
+
Deze lijst is voor onderwerpen over het porten en gebruik van AFS van CMU/Transarc

{freebsd-announce}::
_Belangrijke gebeurtenissen en projectdoelen_
+
Dit is de mailinglijst voor hen die alleen interesse hebben in gelegenheidsmededelingen of belangrijke FreeBSD-gebeurtenissen. Hieronder vallen aankondigingen over snapshots en andere uitgaven. De lijst omvat ook aankondigingen over nieuwe mogelijkheden binnen FreeBSD. Er kunnen ook oproepen gedaan worden voor vrijwilligers, enzovoort. Deze lijst kent een laag volume en is volledig gemodereerd.

link:{freebsd-arch-url}[freebsd-arch]::
_Discussie van architectuur en ontwerp_
+
Deze lijst is bedoeld voor het bespreken van de FreeBSD-architectuur. Berichten zijn in het algemeen strikt technisch van aard. Voorbeelden van geschikte onderwerpen zijn:

** Hoe het buildsysteem bijgewerkt kan worden zodat meerdere aanpaste builds tegelijkertijd kunnen lopen.
** Wat moet er aan VPS aangepast worden om Heidemann-lagen te laten werken.
** Hoe kan de apparataatstuurprogramma interface aangepast worden zodat dezelfde stuurprogramma's netjes op vele bussen en architecturen gebruikt kunnen worden.
** Hoe een netwerkstuurprogramma geschreven kan worden.

link:{freebsd-bluetooth-url}[freebsd-bluetooth]::
_Bluetooth(R) in FreeBSD_
+
Dit is het forum waar gebruikers van Bluetooth(R) op FreeBSD samenkomen. Gespreksstof op het gebied van ontwerp, implementatiedetails, patches, probleemrapportages, statusrapportages, verzoeken voor nieuwe mogelijkheden en al het andere dat met Bluetooth(R) te maken heeft is geschikt materiaal.

link:{freebsd-bugbusters-url}[freebsd-bugbusters]::
_Coördinatie afhandeling Problem Reports_
+
Het doel van deze lijst is een platform zijn voor de coördinatie en discussie voor de Bugmeister, zijn Bugbusters en anderen die interesse hebben in de PR-database. Deze lijst is niet bedoeld voor discussies over specifieke bugs, patches of PR's.

link:{freebsd-bugs-url}[freebsd-bugs]::
_Bug reports_
+
Dit is de mailinglijst voor het rapporteren van bugs in FreeBSD. Waar mogelijk dienen bugs ingezonden te worden via man:send-pr[1] of via de link:https://www.FreeBSD.org/send-pr.html[Webinterface] daarvan.

link:{freebsd-chat-url}[freebsd-chat]::
_Niet-technische onderwerpen met betrekking tot de FreeBSD-gemeenschap_
+
Deze lijst bevat alle onderwerpen waar op andere lijsten geen ruimte voor is wat betreft niet-technische en sociale informatie. Er wordt gesproken over de moord op Van Gogh, of er in onderkast of kapitalen geschreven dient te worden, wie er te veel koffie drinkt, waar het beste bier vandaan komt, enzovoort. Belangrijke gebeurtenissen (zoals feestjes, bruiloften, geboorten, nieuwe banen, enzovoort) kunnen op de technische lijsten aangekondigd worden, maar antwoorden dienen naar deze -chat lijst te gaan.

link:{freebsd-chromium-url}[freebsd-chromium]::
_FreeBSD specifieke Chromium problemen_
+
Dit is een lijst voor het bespreken van Chromium ondersteuning voor FreeBSD. Dit is een technische lijst om de ontwikkelingen en installatie van Chromium te bespreken.

{core-name}::
_FreeBSD Kernteam_
+
Dit is een interne mailinglijst die wordt gebruikt door de kernleden. Er kunnen berichten naar gestuurd worden als een belangrijke FreeBSD-gerelateerde zaak arbitrage nodig heeft of een onderzoekende blik op hoog niveau nodig is.

{freebsd-current}::
_Discussie over het gebruikt van FreeBSD-CURRENT_
+
Dit is de mailinglijst voor gebruikers van FreeBSD-CURRENT. Er staan waarschuwingen op over nieuwe mogelijkheden in -CURRENT die impact hebben op gebruikers en instructies over de te nemen stappen om -CURRENT te blijven. Iedereen die "CURRENT" draait, zou zich moeten abonneren. Dit is een technische mailinglijst waarop strikt technische berichten worden verwacht.

link:{freebsd-cvsweb-url}[freebsd-cvsweb]::
_FreeBSD CVSweb Project_
+
Technische discussie over het gebruik, de ontwikkeling en het beheer van FreeBSD-CVSweb.

link:{freebsd-desktop-url}[freebsd-desktop]::
_FreeBSD gebruiken op en verbeteren voor bureaubladen_
+
Dit is een forum voor het bespreken van FreeBSD op desktops. Het is vooral een plaats voor porters en gebruikers van bureaubladomgevingen om zaken te bespreken en de ondersteuning van FreeBSD op het bureaublad te verbeteren.

link:{freebsd-doc-url}[freebsd-doc]::
_Documentatieproject_
+
Dit is de mailinglijst voor het bespreken van onderwerpen en projecten die te maken hebben met het maken van documentatie voor FreeBSD. De leden van deze mailinglijst worden samen "The FreeBSD Documentation Project" genoemd. Het is een open lijst waarop zonder problemen een abonnement genomen kan worden en bijdragen zeer op prijs worden gesteld!

link:{freebsd-drivers-url}[freebsd-drivers]::
_Apparaatstuurprogramma's schrijven voor FreeBSD_
+
Dit is een forum voor technische discussie met betrekking tot apparaatstuurprogramma's op FreeBSD. Het is vooral een plaats voor schrijvers van apparaatstuurprogramma's om vragen te stellen over hoe apparaatstuurprogramma's te schrijven met de API's in de kernel van FreeBSD.

link:{freebsd-dtrace-url}[freebsd-dtrace]::
_DTrace op FreeBSD gebruiken en ontwikkelen_
+
DTrace is een geïntegreerd component van FreeBSD dat een raamwerk biedt om de kernel en de gebruikersprogramma's tijdens het draaien te begrijpen. De mailinglijst is een gearchiveerde discussie voor ontwikkelaars van de code en voor de gebruikers ervan.

link:{freebsd-eclipse-url}[freebsd-eclipse]::
_Gebruikers van Eclipse IDE, hulpprogramma's, cliëntapplicaties en ports_
+
De doelstelling van deze lijst is wederzijdse ondersteuning bieden voor alles dat te maken heeft met het kiezen, installeren, gebruiken, ontwikkelen, en onderhouden van Eclipse IDE, hulpprogramma's en cliëntapplicaties op het FreeBSD-platform en te ondersteunen bij het porten van Eclipse IDE en plugins naar de FreeBSD-omgeving.
+
Het is ook de bedoeling om het uitwisselen van informatie tussen de Eclipse gemeenschap en de FreeBSD-gemeenschap te bevorderen zodat beiden ervan kunnen profiteren.
+
Hoewel deze lijst voornamelijk is gericht op de behoeften van gebruikers van Eclipse, wordt ook een forum geboden voor hen die FreeBSD-specifieke applicaties willen ontwikkelen met het Eclipse raamwerk.

link:{freebsd-eol-url}[freebsd-eol]::
_Ondersteuning van FreeBSD gerelateerde software welke niet meer ondersteund wordt door het FreeBSD-project._
+
Deze lijst is voor degenen die geïnteresseerd zijn in het leveren of gebruiken van ondersteuning voor FreeBSD-gerelateerde software voor welke het FreeBSD-project geen ondersteuning meer biedt (in de vorm van beveiligingsadviezen en patches).

link:{freebsd-embedded-url}[freebsd-embedded]::
_FreeBSD gebruiken in embedded applicaties_
+
Deze lijst heeft tot doel om te discussieren over FreeBSD in embedded systemen. Dit is een technische mailinglijst waarbij men alleen technische inhoud verwacht. Voor het belang van deze lijst definiëren we embedded systemen als computersystemen die geen desktop-systemen zijn en meestal slechts één doel hebben ten opzichte van gewone systemen. Voorbeelden bevatten onder andere: diverse soorten telefoonsets, netwerkapparatuur zoals routers, switches en PBX'en, op afstand bestuurbare meetapparatuur, PDA's, Point of Sale systemen etc.

link:{freebsd-emulation-url}[freebsd-emulation]::
_Emulatie van andere systemen zoals Linux(R), MS-DOS(R) en Windows(R)_
+
Dit is een forum voor technische discussie met betrekking tot het draaien van programma's op FreeBSD die zijn geschreven voor andere besturingssystemen.

link:{freebsd-firewire-url}[freebsd-firewire]::
_FireWire(R) (iLink, IEEE 1394)_
+
Dit is de mailinglijst voor het bespreken van het ontwerp en de implementatie van een FireWire(R) (ook wel IEEE 1394 of iLink) subsysteem voor FreeBSD. Relevante onderwerpen omvatten de standaarden, busapparaten en hun protocollen, adapter boards/kaarten/chipssets en de architectuur en implementatie van code voor een juiste ondersteuning.

link:{freebsd-fs-url}[freebsd-fs]::
_Bestandssystemen_
+
Discussie over FreeBSD-bestandssystemen. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-gecko-url}[freebsd-gecko]::
_Gecko Rendering Engine_
+
Dit is een forum over Gecko applicaties die FreeBSD gebruiken.
+
De discussie concentreert zich op toepassingen van Gecko Ports, hun installatie, hun ontwikkeling en hun ondersteuning binnen FreeBSD.

link:{freebsd-geom-url}[freebsd-geom]::
_GEOM_
+
Discussie specifiek over GEOM en gerelateerde implementaties. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-gnome-url}[freebsd-gnome]::
_GNOME_
+
Discussie over de bureaubladomgeving GNOME voor FreeBSD. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-infiniband-url}[freebsd-infiniband]::
_Infiniband op FreeBSD_
+
Technische mailinglijst over Infiniband, OFED en OpenSM op FreeBSD.

link:{freebsd-ipfw-url}[freebsd-ipfw]::
_IP Firewall_
+
Dit is het forum voor technische bespreking van het herontwerp van de IP-firewallcode in FreeBSD. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-ia64-url}[freebsd-ia64]::
_Porten van FreeBSD naar IA64_
+
Dit is een technische mailinglijst voor individuen die actief werken aan het porten van FreeBSD naar het platform IA-64 van Intel(R), om problemen op tafel te leggen of alternatieve oplossingen te bespreken. Geïnteresseerden die alleen de technische bespreking willen volgen zijn ook welkom.

link:{freebsd-isdn-url}[freebsd-isdn]::
_ISDN-communicatie_
+
Dit is de mailinglijst voor discussie over de ontwikkeling van ISDN-ondersteuning voor FreeBSD.

link:{freebsd-java-url}[freebsd-java]::
_Java(TM) Ontwikkeling_
+
Dit is de mailinglijst voor het bespreken van de ontwikkeling van significante Java(TM) applicaties voor FreeBSD en het porten en het beheer van JDK(TM)'s.

[[eresources-charters-jobs]]
link:{freebsd-jobs-url}[freebsd-jobs]::
_Banen in de aanbieding en gezocht_
+
Dit is een forum voor vacatures en CV's specifiek gerelateerd aan FreeBSD, bijvoorbeeld als er FreeBSD-gerelateerd werk wordt gezocht of in de aanbieding is. Dit is _geen_ mailinglijst voor algemene werkonderwerpen omdat daarvoor al elders ruimte staat.
+
Ook deze lijst wordt net als alle andere `FreeBSD.org` mailinglijsten wereldwijd verspreid. Daarom dient duidelijk vermeld te worden om welke locatie het gaat en onder welke voorwaarden telewerken of bijdragen in huisvesting mogelijk zijn.
+
Email dient alleen open formaten te bevatten. Bij voorkeur platte tekst, maar standaard Portable Document Format (PDF), HTML, en een aantal andere, zijn acceptabel voor lezers. Gesloten formaten, zoals Microsoft(R) Word ([.filename]#.doc#), worden door de mailinglijstserver geweigerd.

link:{freebsd-kde-url}[freebsd-kde]::
_KDE_
+
Discussie over KDE op FreeBSD-systemen. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-hackers-url}[freebsd-hackers]::
_Technische discussies_
+
Dit is een forum voor technische discussie met betrekking tot FreeBSD. Dit is de leidende technische mailinglijst die is bestemd voor mensen die actief aan FreeBSD werken om problemen aan het voetlicht te brengen of alternatieve oplossingen te bespreken. Geïnteresseerden die alleen de technische bespreking willen volgen zijn ook welkom. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-hardware-url}[freebsd-hardware]::
_Algemene discussie over FreeBSD-hardware_
+
Algemene discussie over de typen hardware waar FreeBSD op draait en problemen en oplossingen over wat te kopen en wat vooral niet.

link:{freebsd-hubs-url}[freebsd-hubs]::
_Mirrorsites_
+
Aankondigingen en discussie voor beheerders van FreeBSD-mirrorsites.

link:{freebsd-isp-url}[freebsd-isp]::
_Onderwerpen voor Internet Service Providers_
+
Deze mailinglijst is voor het bespreken van relevante onderwerpen voor Internet Service Providers (ISP's) die FreeBSD gebruiken. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-mono-url}[freebsd-mono]::
_Mono en C# applicaties op FreeBSD_
+
Dit is een lijst voor discussies met betrekking tot het Mono-ontwikkelraamwerk op FreeBSD. Dit is een technische mailinglijst. Het is bedoeld voor individuen die actief werken aan het overbrengen van Mono of C# applicaties naar FreeBSD, om problemen naar voren te brengen of alternatieve oplossingen te bespreken. Individuen die geïnteresseerd zijn in het volgen van de technische discussie zijn ook welkom.

link:{freebsd-office-url}[freebsd-office]::
_Kantoortoepassingen op FreeBSD_
+
De discussie richt zich op kantoortoepassingen, hun installatie, hun ontwikkeling en hun ondersteuning binnen FreeBSD.

link:{freebsd-ops-announce-url}[freebsd-ops-announce]::
_Aankondigingen over de projectinfrastructuur_
+
Deze mailinglijst is bedoeld voor mensen die geïnteresseerd zijn in veranderingen en zaken die te maken hebben met de infrastructuur van het FreeBSD.org project.
+
Deze gemodereerde lijst is strict voor aankondigingen: geen antwoorden, verzoeken, discussies of meningen.

link:{freebsd-performance-url}[freebsd-performance]::
_Discussie over het optimaliseren of versnellen van FreeBSD_
+
Deze mailinglijst is een platform voor hackers, beheerders en/of andere belanghebbenden om FreeBSD- en prestatiegerelateerde onderwerpen te bespreken. De onderwerpen die besproken kunnen worden omvatten FreeBSD-installaties met een hoge load, systemen met prestatieproblemen of systemen die tegen de limieten van FreeBSD aan zitten. Zij die willen meewerken om de prestaties van FreeBSD te verbeteren worden sterk aangemoedigd zich op deze lijst te abonneren. Deze lijst is bijzonder technisch en bijzonder geschikt voor ervaren FreeBSD-gebruikers, hackers en beheerders die FreeBSD snel, robuust, en schaalbaar willen houden. Deze lijst is geen vraag-en-antwoord lijst die dient als vervanging voor het lezen van documentatie, maar hier worden bijdragen geleverd of vragen gesteld over nog niet eerder beschreven prestatiegerelateerde onderwerpen.

link:{freebsd-pf-url}[freebsd-pf]::
_Discussie en vragen over het pakketfilter firewallsysteem_
+
Discussie over het pakketfilter (pf) firewallsysteem met betrekking tot FreeBSD. Technische discussie en gebruikersvragen zijn beiden welkom. Deze lijst is ook de plaats om het raamwerk ALTQ QoS te bespreken.

link:{freebsd-pkg-url}[freebsd-pkg]::
_Discussies over binair pakketbeheer en pakketgereedschappen_
+
Discussies over alle aspecten over het beheren van FreeBSD-systemen door middel van het gebruik van binaire pakketten om software te installeren, inclusief de gereedschappen en formaten van binaire pakketten, hun ontwikkeling en ondersteuning binnen FreeBSD, het beheer van pakketreservoirs en pakketten van derde partijen.
+
Merk op dat discussies over poorten die onjuiste pakketten genereren over het algemeen als problemen met poorten moet worden gezien en dus ongeschikt zijn voor deze lijst.

link:{freebsd-platforms-url}[freebsd-platforms]::
_Porten van niet-Intel(R) platforms_
+
Cross-platform FreeBSD-zaken, algemene discussie en voorstellen voor niet-Intel(R) FreeBSD ports. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-ports-url}[freebsd-ports]::
_Discussie over "ports"_
+
Discussie over de "Portscollectie" ([.filename]#/usr/ports#) van FreeBSD, de Ports infrastructuur en algemene coördinatie aangaande ports. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-ports-announce-url}[freebsd-ports-announce]::
_Belangrijk nieuws en belangrijke instructies over FreeBSD "Portscollectie"_
+
Belangrijk nieuws voor ontwikkelaars, porters en gebruikers van de "Portscollectie" ([.filename]#/usr/ports#), waaronder veranderingen aan de architectuur/infrastructuur, nieuwe mogelijkheden, kritische opwaardeerinstructies, en uitgave-informatie. Dit is een mailinglijst met een laag volume, bedoeld voor aankondigingen.

link:{freebsd-ports-bugs-url}[freebsd-ports-bugs]::
_Discussie over "ports" bugs_
+
Discussie over probleemrapportages voor de FreeBSD "Portscollectie" ([.filename]#/usr/ports#), voorgestelde ports of aanpassingen aan ports. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-proliant-url}[freebsd-proliant]::
_Technische discussie over FreeBSD op HP Proliant serverplatforms_
+
Deze mailinglijst wordt gebruikt voor technische discussie over het gebruik van FreeBSD op HP ProLiant servers, inclusief het bespreken van ProLiant-specifieke stuurprogramma's, beheersoftware, gereedschappen voor instellingen en BIOS-updates. Dit is daaarom ook de uitgesproken plaats voor het bespreken van de modules hpasmd, hpasmcli, en hpacucli.

link:{freebsd-python-url}[freebsd-python]::
_Python op FreeBSD_
+
Dit is een lijst voor discussie gerelateerd aan het verbeteren van ondersteuning voor Python op FreeBSD. Dit is een technische mailinglijst voor mensen die aan het porten van Python, aanverwante modules en Zope-dingen naar FreeBSD werken.

link:{freebsd-questions-url}[freebsd-questions]::
_Gebruikersvragen_
+
Dit is de mailinglijst voor vragen over FreeBSD. Er horen geen "how to" vragen op de technische mailinglijsten thuis, tenzij een vraag erg technisch van aard is.

link:{freebsd-ruby-url}[freebsd-ruby]::
_FreeBSD-specifieke discussies over Ruby_
+
Dit is een lijst voor discussies gerelateerd aan de Ruby-ondersteuning op FreeBSD. Dit is een technische mailinglijst. Het is bedoeld voor individuen die aan Ruby-ports, bibliotheken van derde partijen, en raamwerken werken.
+
Individuen die geïnteresseerd zijn in de technische discussie zijn ook welkom.

link:{freebsd-scsi-url}[freebsd-scsi]::
_SCSI-subsysteem_
+
Dit is de mailinglijst voor mensen die aan het SCSI-subsysteem voor FreeBSD werken. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

{freebsd-security}::
_Beveiligingsonderwerpen_
+
FreeBSD-computerbeveiligingsonderwerpen (DES, Kerberos, bekende beveiligingsgaten, oplossingen, enzovoort). Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht. Dit is zeker geen vraag-en-antwoord lijst, maar bijdragen voor de FAQ (zowel _vraag_ als _antwoord_) zijn welkom.

{freebsd-security-notifications}::
_Beveiligingswaarschuwingen_
+
Waarschuwingen voor FreeBSD beveiligingsproblemen en oplossingen. Dit is geen discussielijst. De discussielijst is {freebsd-security}.

link:{freebsd-small-url}[freebsd-small]::
_FreeBSD gebruiken in embedded toepassingen_
+
Op deze lijst worden onderwerpen gerelateerd aan ongebruikelijk kleine en embedded FreeBSD-installaties besproken. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.
+
Deze lijst is vervangen door link:{freebsd-embedded-url}[freebsd-embedded]

link:{freebsd-snapshots-url}[freebsd-snapshots]::
_Aankondigingen van ontwikkel-snapshots van FreeBSD_
+
Deze lijst houdt u op de hoogte over de beschikbaarheid van nieuwe ontwikkel-snapshots voor de takken head/ en stable/ van FreeBSD.

{freebsd-stable}::
_Discussie over het gebruik van FreeBSD-STABLE_
+
Dit is de mailinglijst voor gebruikers van FreeBSD-STABLE. Er worden ook waarschuwingen op gepost over nieuwe opties in -STABLE die invloed op de systemen van gebruikers kunnen hebben en instructies over de te nemen stappen om -STABLE te blijven. Iedereen die "STABLE" draait hoort zich op deze lijst te abonneren. Dit is een technische mailinglijst waarop slechts strikt technische bijdragen worden verwacht.

link:{freebsd-standards-url}[freebsd-standards]::
_Conformeren C99 & POSIX_
+
Dit is een forum voor technische bespreking gerelateerd aan het conformeren van FreeBSD aan de C99- en de POSIX-standaarden.

link:{freebsd-testing-url}[freebsd-testing]::
_Testen op FreeBSD_
+
Technische mailinglijst voor discussies over testen op FreeBSD, inclusief ATF/Kyua, infrastructuren voor testbuilds, het testen van ports naar FreeBSD van andere besturingssystemen (NetBSD, ...), enzovoorts.

link:{freebsd-tex-url}[freebsd-tex]::
_TeX en haar toepassingen op FreeBSD overzetten_
+
Dit is een technische mailinglijst voor discussies over TeX en haar toepassingen op FreeBSD. Het is bedoeld voor degenen die actief werken aan het overzetten van TeX op FreeBSD, om problemen te bespreken of alternatieve oplossingen aan te dragen. Personen die geïnteresseerd zijn in het volgen van de technische discussie zijn ook welkom.

link:{freebsd-toolchain-url}[freebsd-toolchain]::
_Onderhoud van de ingebouwde toolchain van FreeBSD_
+
Dit is de mailinglijst bedoeld voor discussies over het onderhoud van de toolchain die met FreeBSD wordt geleverd. Dit zou de toestand van Clang en GCC kunnen omvatten, maar ook software als assemblers, linkers en debuggers.

link:{freebsd-usb-url}[freebsd-usb]::
_Discussie over FreeBSD ondersteuning voor USB_
+
Dit is de mailinglijst voor technische bespreking van onderwerpen gerelateerd aan FreeBSD ondersteuning voor USB.

link:{freebsd-user-groups-url}[freebsd-user-groups]::
_Gebruikersgroep Coördinatie Lijst_
+
Dit is de mailinglijst voor coördinatoren voor alle lokale gebruikersgroepen, zodat ze met elkaar en een lid van het Kernteam zaken kunnen bespreken. Deze lijst hoort beperkt te blijven tot een overzicht van overleggen en de coördinatie van projecten waarbij meerdere gebruikersgroepen betrokken zijn.

link:{freebsd-virtualization-url}[freebsd-virtualization]::
_Discussies over verscheidene virtualisatietechnieken ondersteund door FreeBSD_
+
Een lijst om de verscheidene virtualisatietechnieken die door FreeBSD worden ondersteund te bespreken. Aan de ene kant zal de nadruk liggen op de implementatie van de basale functionaliteit alsook op het toevoegen van nieuwe mogelijkheden. Aan de andere kant zullen gebruikers een forum hebben om om hulp te vragen bij problemen of om hun usecases te bespreken.

link:{freebsd-wip-status-url}[freebsd-wip-status]::
_FreeBSD Werk-In-Uitvoering status_
+
Deze mailinglijst kan gebruikt worden om de schepping en voortgang van uw FreeBSD-gerelateerd werk aan te kondigen. Berichten zullen gemodereerd worden. Het wordt gesuggereerd om het bericht "Aan:" een FreeBSD-mailinglijst dat het onderwerp beter dekt te sturen en deze lijst alleen te "BCC:"-en. Op deze manier kan uw werk-in-uitvoering ook op de onderwerpslijst worden bediscussieerd, aangezien discussies op deze lijst niet zijn toegestaan.
+
Kijk in de archieven voor voorbeelden van geschikte berichten.
+
Een redactioneel overzicht van de berichten aan deze lijst kan om de paar maanden naar de FreeBSD-website gezonden worden als deel van de Status Reports . Meer voorbeelden en oude rapportages zijn daar ook te vinden.

link:{freebsd-wireless-url}[freebsd-wireless]::
_Discussies over de 802.11-stack, de ontwikkeling van gereedschappen voor stuurprogramma's_
+
De FreeBSD-wireless lijst richt zich op de 802.11-stack (sys/net80211) en de ontwikkeling van stuurprogramma's en gereedschappen. Dit omvat bugs, nieuwe eigenschappen en onderhoud.

link:{freebsd-xen-url}[freebsd-xen]::
_Discussies over het porteren van FreeBSD naar Xen(TM) - implementatie en gebruik_
+
Een lijst die zich richt op de FreeBSD Xen(TM) port. De verwachte hoeveelheid verkeer is laag genoeg zodat het voor zowel technische discussies over de implementatie- en ontwerpdetails als voor zaken over administratief gebruik bedoeld is.

link:{freebsd-xfce-url}[freebsd-xfce]::
_XFCE_
+
Dit is een forum voor discussies gerelateerd aan de XFCE-omgeving voor FreeBSD. Dit is een technische mailinglijst. Het is bedoeld voor degenen die actief werken aan het porten van XFCE naar FreeBSD, om problemen naar voren te brengen of alternatieve oplossingen te bespreken. Personen die geïnteresseerd zijn in het volgen van de technische discussie zijn ook welkom.

link:{freebsd-zope-url}[freebsd-zope]::
_Zope_
+
Dit is een forum voor discussies die verwant zijn aan het brengen van de Zope-omgeving naar FreeBSD. Dit is een technische mailinglijst. Het is bedoeld voor individuen die actief werken aan het overbrengen van Zope naar FreeBSD, om problemen aan te dragen of alternatieve oplossingen te bespreken. Individuen die geïnteresseerd zijn in het volgen van de technische discussie zijn ook welkom.

[[eresources-mailfiltering]]
=== Filters op de mailinglijsten

De FreeBSD-mailinglijsten worden op verschillende manieren gefilterd om het doorsturen van spam, virussen, en andere ongewenste email te beperken. De hieronder beschreven filteracties bevatten niet alle genomen acties voor de beveiliging van de mailinglijsten.

Er is een beperkt aantal typen bijlagen toegestaan op de mailinglijsten. Alle bijlagen met een MIME-inhoudtype dat niet in de onderstaande lijst staat worden verwijderd voordat de mail wordt doorgestuurd naar de mailinglijsten.

* application/octet-stream
* application/pdf
* application/pgp-signature
* application/x-pkcs7-signature
* message/rfc822
* multipart/alternative
* multipart/related
* multipart/signed
* text/html
* text/plain
* text/x-diff
* text/x-patch

[NOTE]
====
Sommige mailinglijsten staan wellicht bijlagen toe met andere MIME-inhoudtypen, maar de bovenstaande lijst zal gelden voor de meeste mailinglijsten.
====

Als een email zowel een HTML- als een platte tekstversie bevat, dan wordt de HTML-versie verwijderd. Als een mail alleen een HTML-versie bevat, dan wordt die omgezet naar platte tekst.

[[eresources-news]]
== Usenet-nieuwsgroepen

Naast de twee specifieke FreeBSD-nieuwsgroepen zijn er nog vele andere waarin FreeBSD wordt besproken of die anderszins relevant zijn voor gebruikers van FreeBSD.

=== Specifieke BSD nieuwsgroepen

* link:news:comp.unix.bsd.freebsd.announce[comp.unix.bsd.freebsd.announce]
* link:news:comp.unix.bsd.freebsd.misc[comp.unix.bsd.freebsd.misc]
* link:news:de.comp.os.unix.bsd[de.comp.os.unix.bsd] (Duits)
* link:news:fr.comp.os.bsd[fr.comp.os.bsd] (Frans)
* link:news:it.comp.os.freebsd[it.comp.os.freebsd] (Italiaans)

=== Overige interessante UNIX(R)-nieuwsgroepen

* link:news:comp.unix[comp.unix]
* link:news:comp.unix.questions[comp.unix.questions]
* link:news:comp.unix.admin[comp.unix.admin]
* link:news:comp.unix.programmer[comp.unix.programmer]
* link:news:comp.unix.shell[comp.unix.shell]
* link:news:comp.unix.user-friendly[comp.unix.user-friendly]
* link:news:comp.security.unix[comp.security.unix]
* link:news:comp.sources.unix[comp.sources.unix]
* link:news:comp.unix.advocacy[comp.unix.advocacy]
* link:news:comp.unix.misc[comp.unix.misc]
* link:news:comp.unix.bsd[comp.unix.bsd]

=== X Window systeem

* link:news:comp.windows.x.i386unix[comp.windows.x.i386unix]
* link:news:comp.windows.x[comp.windows.x]
* link:news:comp.windows.x.apps[comp.windows.x.apps]
* link:news:comp.windows.x.announce[comp.windows.x.announce]
* link:news:comp.windows.x.intrinsics[comp.windows.x.intrinsics]
* link:news:comp.windows.x.motif[comp.windows.x.motif]
* link:news:comp.windows.x.pex[comp.windows.x.pex]
* link:news:comp.emulators.ms-windows.wine[comp.emulators.ms-windows.wine]

[[eresources-web]]
== World wide webservers

[[eresources-web-social]]
=== Fora, blogs, en sociale netwerken

* http://forums.freebsd.org/[The FreeBSD Forums] bieden een webgebaseerd discussieforum voor vragen en technische discussies over FreeBSD.
* http://planet.freebsdish.org/[Planet FreeBSD] biedt een samengestelde feed van tientallen blogs geschreven door FreeBSD-ontwikkelaars. Vele ontwikkelaars gebruiken dit om korte notities te posten over waaraan ze werken, nieuwe patches, en ander werk in uitvoering.
* Het http://www.youtube.com/bsdconferences[BSDConferences YouTube Channel] biedt een verzameling van video's van hoge kwaliteit van wereldwijde BSD-conferenties. Dit is een prima manier om presentaties van hoofdontwikkelaars over nieuw werk in FreeBSD te zien.

[[eresources-web-mirrors]]
=== Officiële spiegels

<<central-mirrors, {central}>>, <<armenia-mirrors, {mirrors-armenia}>>, <<australia-mirrors, {mirrors-australia}>>, <<austria-mirrors, {mirrors-austria}>>, <<czech-republic-mirrors, {mirrors-czech}>>, <<denmark-mirrors, {mirrors-denmark}>>, <<finland-mirrors, {mirrors-finland}>>, <<france-mirrors, {mirrors-france}>>, <<germany-mirrors, {mirrors-germany}>>, <<hong-kong-mirrors, {mirrors-hongkong}>>, <<ireland-mirrors, {mirrors-ireland}>>, <<japan-mirrors, {mirrors-japan}>>, <<latvia-mirrors, {mirrors-latvia}>>, <<lithuania-mirrors, {mirrors-lithuania}>>, <<netherlands-mirrors, {mirrors-netherlands}>>, <<norway-mirrors, {mirrors-norway}>>, <<russia-mirrors, {mirrors-russia}>>, <<slovenia-mirrors, {mirrors-slovenia}>>, <<south-africa-mirrors, {mirrors-south-africa}>>, <<spain-mirrors, {mirrors-spain}>>, <<sweden-mirrors, {mirrors-sweden}>>, <<switzerland-mirrors, {mirrors-switzerland}>>, <<taiwan-mirrors, {mirrors-taiwan}>>, <<uk-mirrors, {mirrors-uk}>>, <<usa-mirrors, {mirrors-us}>>.

(as of UTC)

[[central-mirrors]]
*{central}*

* {central-www}

[[armenia-mirrors]]
*{mirrors-armenia}*

* {mirrors-armenia-www-httpv6} (IPv6)

[[australia-mirrors]]
*{mirrors-australia}*

* {mirrors-australia-www-http}
* {mirrors-australia-www2-http}

[[austria-mirrors]]
*{mirrors-austria}*

* {mirrors-armenia-www-httpv6} (IPv6)

[[czech-republic-mirrors]]
*{mirrors-czech}*

* {mirrors-czech-www-httpv6} (IPv6)

[[denmark-mirrors]]
*{mirrors-denmark}*

* {mirrors-denmark-www-httpv6} (IPv6)

[[finland-mirrors]]
*{mirrors-finland}*

* {mirrors-finland-www-http}

[[france-mirrors]]
*{mirrors-france}*

* {mirrors-france-www-http}

[[germany-mirrors]]
*{mirrors-germany}*

* {mirrors-germany-www-http}

[[hong-kong-mirrors]]
*{mirrors-hongkong}*

* {mirrors-hongkong-www}

[[ireland-mirrors]]
*{mirrors-ireland}*

* {mirrors-ireland-www} 

[[japan-mirrors]]
*{mirrors-japan}*

* {mirrors-japan-www-httpv6} (IPv6)

[[latvia-mirrors]]
*{mirrors-latvia}*

* {mirrors-latvia-www} 

[[lithuania-mirrors]]
*{mirrors-lithuania}*

* {mirrors-lithuania-www} 

[[netherlands-mirrors]]
*{mirrors-netherlands}*

* {mirrors-netherlands-www} 

[[norway-mirrors]]
*{mirrors-norway}*

* {mirrors-norway-www} 

[[russia-mirrors]]
*{mirrors-russia}*

* {mirrors-russia-www-httpv6} (IPv6)

[[slovenia-mirrors]]
*{mirrors-slovenia}*

* {mirrors-slovenia-www} 

[[south-africa-mirrors]]
*{mirrors-south-africa}*

* {mirrors-south-africa-www}

[[spain-mirrors]]
*{mirrors-spain}*

* {mirrors-spain-www}
* {mirrors-spain-www2}

[[sweden-mirrors]]
*{mirrors-sweden}*

* {mirrors-sweden-www}

[[switzerland-mirrors]]
*{mirrors-switzerland}*

* {mirrors-switzerland-www-httpv6} (IPv6)
* {mirrors-switzerland-www2-httpv6} (IPv6)

[[taiwan-mirrors]]
*{mirrors-taiwan}*

* {mirrors-taiwan-www}
* {mirrors-taiwan-www2}
* {mirrors-taiwan-www4}
* {mirrors-taiwan-www5-httpv6} (IPv6)

[[uk-mirrors]]
*{mirrors-uk}*

* {mirrors-uk-www}
* {mirrors-uk-www3}

[[usa-mirrors]]
*{mirrors-us}*

* {mirrors-us-www5-httpv6} (IPv6)

[[eresources-email]]
== Email-adressen

De onderstaande gebruikersgroepen bieden FreeBSD-gerelateerde email-adressen aan voor hun leden. De aangegeven beheerders behouden zich het recht voor om een account te verwijderen als die op enigerlei wijze wordt misbruikt.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Domein
| Faciliteiten
| Gebruikersgroep
| Beheerder

|ukug.uk.FreeBSD.org
|Alleen forwarden
|mailto:ukfreebsd@uk.FreeBSD.org[ukfreebsd@uk.FreeBSD.org]
|Lee Johnston mailto:lee@uk.FreeBSD.org[lee@uk.FreeBSD.org]
|===
