# $FreeBSD: www/en/java/dists/Makefile,v 1.6 2005/01/20 09:00:13 phantom Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	10.sgml
DOCS+=	11.sgml
DOCS+=	12.sgml
DOCS+=	13.sgml
DOCS+=	14.sgml
DOCS+=	15.sgml
DOCS+=	16.sgml
DOCS+=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
