# $FreeBSD: www/en/java/dists/Makefile,v 1.3 2000/03/02 15:55:29 phantom Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	10.sgml
DOCS+=	11.sgml
DOCS+=	12.sgml
DOCS+=	13.sgml
DOCS+=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
