# $Id: Makefile,v 1.1.1.1 1999-01-30 23:20:34 vanilla Exp $

.NOTPARALLEL: 

SGMLOPTS=-links -e big5
DOC=	FAQ
SRCS= FAQ.sgml acknowledgments.sgml admin.sgml applications.sgml
SRCS+= commercial.sgml hackers.sgml hardware.sgml install.sgml
SRCS+= kernelconfig.sgml misc.sgml network.sgml preface.sgml
SRCS+=	serial.sgml troubleshoot.sgml x.sgml

.include <bsd.sgml.mk>
