---
title: FreeBSD гарын авлага
authors:
  - author: FreeBSD-г Монголоор баримтжуулах төсөл
copyright: 1995-2020 FreeBSD-г Монголоор баримтжуулах төсөл
trademarks: ["freebsd", "ibm", "ieee", "redhat", "3com", "adobe", "apple", "intel", "linux", "microsoft", "opengroup", "sun", "realnetworks", "oracle", "3ware", "arm", "adaptec", "heidelberger", "intuit", "lsilogic", "themathworks", "thomson", "vmware", "wolframresearch", "xiph", "xfree86", "general"] 
next: books/handbook/preface
add_single_page_link: true
showBookMenu: true
weight: 0
params:
  path: "/books/handbook/"
---

= FreeBSD гарын авлага
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[.abstract-title]
Товч агуулга

FreeBSD-д тавтай морилно уу! Энэ гарын авлага нь _FreeBSD {rel112-current}-RELEASE_ болон _FreeBSD {rel120-current}-RELEASE_ хувилбаруудын суулгацаас эхлээд өдөр тутмын хэрэглээг тайлбарласан билээ. Энэ гарын авлага нь _төгс дуусаагүй_ бөгөөд маш олон хүний хамтын бүтээл юм. Зарим хэсэг нь хуучирч шинэчлэгдэх шаардлагатай байж болзошгүй. Хэрэв та энэ төсөлд хувь нэмрээ оруулж, бидэнд туслахыг хүсвэл {freebsd-doc} хаяг руу захиа бичнэ үү. Энэ гарын авлагын хамгийн сүүлийн хувилбарыг http://www.FreeBSD.org/[FreeBSD вэб хуудаснаас] татаж авч болно. (энэ гарын авлагын өмнөх хувилбаруудыг http://docs.FreeBSD.org/doc/[http://docs.FreeBSD.org/doc/]-с авах боломжтой). Мөн янз бүрийн шахаж бэлтгэсэн хэлбэрээр link:ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/[FreeBSD FTP серверээс] эсвэл <<mirrors-ftp,толин тусгал хуудаснаас>> татаж авагдаж болно. Хэрэв та энэ гарын авлагын хэвлэсэн хуулбарыг авахыг хүсвэл http://www.freebsdmall.com/[FreeBSD Mall] хуудсанд зорчино уу. Та мөн гарын авлага дотор link:https://www.FreeBSD.org/search/[хайлт хийх] боломжтой.

'''
