---
title: хэсэг II. Нийтлэг асуудлууд
prev: books/handbook/x11
next: books/handbook/desktop
---

[[common-tasks]]
= Нийтлэг асуудлууд

Үндсэн ойлголтуудыг нэгэнт тайлбарласан болохоор одоо FreeBSD-ийн гарын авлагын энэ хэсэгт FreeBSD-ийн зарим байнга ашиглагддаг боломжуудыг авч үзэх болно. Эдгээр бүлгүүд нь:

* Түгээмэл хэрэглэгддэг ширээний програмуудыг танд танилцуулах болно: хөтчүүд, бүтээмжийн багажууд, баримт үзэгчид гэх мэт.
* FreeBSD-н хэд хэдэн мультимедиа багажуудыг танд танилцуулах болно.
* Тусгайлан тохируулсан FreeBSD цөмийг бүтээх үйл явц болон, системд нэмэлт функцуудыг хэрхэн идэвхжүүлэхийг тайлбарлах болно.
* Ширээний болон сүлжээнд холбогдсон хэвлэгчийн тохируулгуудын хувьд хэвлэх системийг дэлгэрэнгүй тайлбарлах болно.
* FreeBSD систем дээр Линукс програмуудыг хэрхэн ажиллуулахыг танд үзүүлэх болно.

Эдгээр бүлгүүдийн заримд таныг зарим нэг ойлголтуудын талаар урьдаар уншихыг зөвлөх бөгөөд энэ нь бүлэг бүрийн эхэнд ерөнхий агуулгад дурдсан байгаа болно.

include::content/mn/books/handbook/toc-2.adoc[]
