# 
# $FreeBSD$
#
# Article: FreeBSD Quickstart for Linux Users

MAINTAINER=ebrandi@FreeBSD.org

DOC?= article

FORMATS?= html html-split
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
