# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.xml
DOCS+=	notes.xml
DOCS+=	errata.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
