# Summary for busdma project status
#
# $FreeBSD: www/en/projects/netperf/Makefile,v 1.1 2004/11/11 22:21:42 rwatson Exp $

MAINTAINER=	rwatson

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
DOCS+=	cluster.sgml
DATA=	style.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
