---
description: '이 장에서는 FreeBSD에서 지원하는 다른 파일 시스템을 설명합니다'
next: books/handbook/virtualization
part: '파트 III. 시스템 관리'
path: /books/handbook/
prev: books/handbook/zfs
showBookMenu: 'true'
tags: ["filesystem", "ext2", "ext3", "ext4", "ext2fs"]
title: '22장. 기타 파일 시스템'
weight: 26
---

[[filesystems]]
= 기타 파일 시스템
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 22
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/filesystems/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[filesystems-synopsis]]
== 요약

파일 시스템은 모든 운영 체제의 필수적인 부분입니다. 파일 시스템을 통해 사용자는 파일을 업로드 및 저장하고, 데이터에 액세스할 수 있으며, 하드 드라이브를 유용하게 사용할 수 있습니다. 운영 체제마다 기본 파일 시스템이 다릅니다. 전통적으로 기본 FreeBSD 파일 시스템은 UFS2로 현대화된 유닉스 파일 시스템 UFS였습니다. FreeBSD 7.0부터는 Z 파일 시스템(ZFS)도 기본 파일 시스템으로 사용할 수 있습니다. 자세한 내용은 crossref:zfs[zfs,Z 파일 시스템(ZFS)]을 참조하세요.

기본 파일 시스템 외에도 FreeBSD는 로컬에 연결된 USB 저장 장치, 플래시 드라이브 및 하드 디스크에 저장된 데이터와 같은 다른 운영 체제의 데이터에 로컬로 액세스할 수 있도록 다양한 다른 파일 시스템을 지원합니다. 여기에는 Linux(R) EXT(확장 파일 시스템)에 대한 지원이 포함됩니다.

다양한 파일 시스템에 대한 FreeBSD 지원 수준은 여러 가지가 있습니다. 일부는 커널 모듈을 로드해야 하고 다른 일부는 도구 세트를 설치해야 할 수 있습니다. 일부 비-기본 파일 시스템(non-native file system) 지원은 전체 읽기-쓰기가 가능한 반면, 일부 파일 시스템은 읽기 전용입니다.

이 챕터를 읽고 나면, 여러분은:

* 기본 파일 시스템과 지원되는 파일 시스템의 차이점.
* FreeBSD에서 지원되는 파일 시스템 종류.
* 기본이 아닌 파일 시스템을 활성화, 구성, 액세스 및 사용하는 방법.

이 챕터를 읽기 전에 여러분은:

* UNIX(R)와 crossref:basics[basics,FreeBSD basics]의 이해.
* crossref:kernelconfig[kernelconfig,kernel configuration and compilation]에 친숙해야 합니다.
* FreeBSD의 crossref:ports[ports,installing software]에 익숙해야 합니다.
* FreeBSD의 crossref:disks[disks,disks], 스토리지 및 장치 이름에 익숙해져 있어야 합니다.

[[filesystems-linux]]
== Linux(R) 파일 시스템

FreeBSD는 여러 Linux(R) 파일 시스템에 대한 기본 지원을 제공합니다. 이 섹션에서는 지원되는 Linux(R) 파일 시스템에 대한 지원을 로드하는 방법과 마운트하는 방법을 설명합니다.

=== ext2 / ext3 / ext4

ext2 파일 시스템에 대한 커널 지원은 FreeBSD 2.2부터 제공되었습니다. man:ext2fs[5] 드라이버를 사용하면 FreeBSD 커널에서 ext2, ext3 및 ext4 파일 시스템을 읽고 쓸 수 있습니다.

[NOTE]
====
아직 저널링과 암호화는 지원되지 않습니다.
====

확장 파일 시스템에 액세스하려면, 확장 볼륨의 FreeBSD 파티션 이름과 기존 마운트 지점을 지정하여 해당 볼륨을 마운트합니다. 이 예에서는 [.filename]#/dev/ad1s1#을 [.filename]#/mnt#에 마운트합니다:

[source, shell]
....
# mount -t ext2fs /dev/ad1s1 /mnt
....
