# $FreeBSD$

MAINTAINER= abulfazl@juniv.edu

DOC?=	article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "$(DOC_PREFIX)/share/mk/doc.project.mk"
