---
title: Chapter 6. Desktop Applications
part: Part II. Common Tasks
prev: books/handbook/partii
next: books/handbook/multimedia
---

[[desktop]]
= Desktop Applications
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 6

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../../images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/en/mailing-lists.adoc[]
include::shared/en/teams.adoc[]
include::shared/en/urls.adoc[]

toc::[]

[[desktop-synopsis]]
== Synopsis

While FreeBSD is popular as a server for its performance and stability, it is also suited for day-to-day use as a desktop. With over {numports} applications available as FreeBSD packages or ports, it is easy to build a customized desktop that runs a wide variety of desktop applications. This chapter demonstrates how to install numerous desktop applications, including web browsers, productivity software, document viewers, and financial software.

[NOTE]
====
Users who prefer to install a pre-built desktop version of FreeBSD rather than configuring one from scratch should refer to https://ghostbsd.org[GhostBSD], https://www.midnightbsd.org[MidnightBSD] or https://www.nomad.org[NomadBSD].
====

Readers of this chapter should know how to:

* Install additional software using packages or ports as described in crossref:ports[ports,Installing Applications: Packages and Ports].
* Install X and a window manager as described in crossref:x11[x11,The X Window System].

For information on how to configure a multimedia environment, refer to crossref:multimedia[multimedia,Multimedia].

[[desktop-browsers]]
== Browsers

FreeBSD does not come with a pre-installed web browser. Instead, the https://www.FreeBSD.org/ports/[www] category of the Ports Collection contains many browsers which can be installed as a package or compiled from the Ports Collection.

The KDE and GNOME desktop environments include their own HTML browser. Refer to crossref:x11[x11-wm,“Desktop Environments”] for more information on how to set up these complete desktops.

Some lightweight browsers include package:www/dillo2[], package:www/links[], and package:www/w3m[].

This section demonstrates how to install the following popular web browsers and indicates if the application is resource-heavy, takes time to compile from ports, or has any major dependencies.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Application Name
| Resources Needed
| Installation from Ports
| Notes

|Firefox
|medium
|heavy
|FreeBSD, Linux(R), and localized versions are available

|Konqueror
|medium
|heavy
|Requires KDE libraries

|Chromium
|medium
|heavy
|Requires Gtk+
|===

=== Firefox

Firefox is an open source browser that features a standards-compliant HTML display engine, tabbed browsing, popup blocking, extensions, improved security, and more. Firefox is based on the Mozilla codebase.

To install the package of the latest release version of Firefox, type:

[source,bash]
....
# pkg install firefox
....

To instead install Firefox Extended Support Release (ESR) version, use:

[source,bash]
....
# pkg install firefox-esr
....

The Ports Collection can instead be used to compile the desired version of Firefox from source code. This example builds package:www/firefox[], where `firefox` can be replaced with the ESR or localized version to install.

[source,bash]
....
# cd /usr/ports/www/firefox
# make install clean
....

=== Konqueror

Konqueror is more than a web browser as it is also a file manager and a multimedia viewer. Supports WebKit as well as its own KHTML. WebKit is a rendering engine used by many modern browsers including Chromium.

Konqueror can be installed as a package by typing:

[source,bash]
....
# pkg install konqueror
....

To install from the Ports Collection:

[source,bash]
....
# cd /usr/ports/x11-fm/konqueror/
# make install clean
....

=== Chromium

Chromium is an open source browser project that aims to build a safer, faster, and more stable web browsing experience. Chromium features tabbed browsing, popup blocking, extensions, and much more. Chromium is the open source project upon which the Google Chrome web browser is based.

Chromium can be installed as a package by typing:

[source,bash]
....
# pkg install chromium
....

Alternatively, Chromium can be compiled from source using the Ports Collection:

[source,bash]
....
# cd /usr/ports/www/chromium
# make install clean
....

[NOTE]
====
The executable for Chromium is [.filename]#/usr/local/bin/chrome#, not [.filename]#/usr/local/bin/chromium#.
====

[[desktop-productivity]]
== Productivity

When it comes to productivity, users often look for an office suite or an easy-to-use word processor. While some <<x11-wm,desktop environments>> like KDE provide an office suite, there is no default productivity package. Several office suites and graphical word processors are available for FreeBSD, regardless of the installed window manager.

This section demonstrates how to install the following popular productivity software and indicates if the application is resource-heavy, takes time to compile from ports, or has any major dependencies.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Application Name
| Resources Needed
| Installation from Ports
| Major Dependencies

|Calligra
|light
|heavy
|KDE

|AbiWord
|light
|light
|Gtk+ or GNOME

|The Gimp
|light
|heavy
|Gtk+

|Apache OpenOffice
|heavy
|huge
|JDK(TM) and Mozilla

|LibreOffice
|somewhat heavy
|huge
|Gtk+, or KDE/ GNOME, or JDK(TM)
|===

=== Calligra

The KDE desktop environment includes an office suite which can be installed separately from KDE. Calligra includes standard components that can be found in other office suites. Words is the word processor, Sheets is the spreadsheet program, Stage manages slide presentations, and Karbon is used to draw graphical documents.

In FreeBSD, package:editors/calligra[] can be installed as a package or a port. To install the package:

[source,bash]
....
# pkg install calligra
....

If the package is not available, use the Ports Collection instead:

[source,bash]
....
# cd /usr/ports/editors/calligra
# make install clean
....

=== AbiWord

AbiWord is a free word processing program similar in look and feel to Microsoft(R) Word. It is fast, contains many features, and is user-friendly.

AbiWord can import or export many file formats, including some proprietary ones like Microsoft(R) [.filename]#.rtf#.

To install the AbiWord package:

[source,bash]
....
# pkg install abiword
....

If the package is not available, it can be compiled from the Ports Collection:

[source,bash]
....
# cd /usr/ports/editors/abiword
# make install clean
....

=== The GIMP

For image authoring or picture retouching, The GIMP provides a sophisticated image manipulation program. It can be used as a simple paint program or as a quality photo retouching suite. It supports a large number of plugins and features a scripting interface. The GIMP can read and write a wide range of file formats and supports interfaces with scanners and tablets.

To install the package:

[source,bash]
....
# pkg install gimp
....

Alternately, use the Ports Collection:

[source,bash]
....
# cd /usr/ports/graphics/gimp
# make install clean
....

The graphics category (https://www.FreeBSD.org/ports/graphics/[freebsd.org/ports/graphics/]) of the Ports Collection contains several GIMP-related plugins, help files, and user manuals.

=== Apache OpenOffice

Apache OpenOffice is an open source office suite which is developed under the wing of the Apache Software Foundation's Incubator. It includes all of the applications found in a complete office productivity suite: a word processor, spreadsheet, presentation manager, and drawing program. Its user interface is similar to other office suites, and it can import and export in various popular file formats. It is available in a number of different languages and internationalization has been extended to interfaces, spell checkers, and dictionaries.

The word processor of Apache OpenOffice uses a native XML file format for increased portability and flexibility. The spreadsheet program features a macro language which can be interfaced with external databases. Apache OpenOffice is stable and runs natively on Windows(R), Solaris(TM), Linux(R), FreeBSD, and Mac OS(R) X. More information about Apache OpenOffice can be found at http://openoffice.org/[openoffice.org]. For FreeBSD specific information refer to http://porting.openoffice.org/freebsd/[porting.openoffice.org/freebsd/].

To install the Apache OpenOffice package:

[source,bash]
....
# pkg install apache-openoffice
....

Once the package is installed, type the following command to launch Apache OpenOffice:

[source,bash]
....
% openoffice-X.Y.Z
....

where _X.Y.Z_ is the version number of the installed version of Apache OpenOffice. The first time Apache OpenOffice launches, some questions will be asked and a [.filename]#.openoffice.org# folder will be created in the user's home directory.

If the desired Apache OpenOffice package is not available, compiling the port is still an option. However, this requires a lot of disk space and a fairly long time to compile:

[source,bash]
....
# cd /usr/ports/editors/openoffice-4
# make install clean
....

[NOTE]
====
To build a localized version, replace the previous command with:

[source,bash]
....
# make LOCALIZED_LANG=your_language install clean
....

Replace _your_language_ with the correct language ISO-code. A list of supported language codes is available in [.filename]#files/Makefile.localized#, located in the port's directory.
====

=== LibreOffice

LibreOffice is a free software office suite developed by http://www.documentfoundation.org/[documentfoundation.org]. It is compatible with other major office suites and available on a variety of platforms. It is a rebranded fork of Apache OpenOffice and includes applications found in a complete office productivity suite: a word processor, spreadsheet, presentation manager, drawing program, database management program, and a tool for creating and editing mathematical formulæ. It is available in a number of different languages and internationalization has been extended to interfaces, spell checkers, and dictionaries.

The word processor of LibreOffice uses a native XML file format for increased portability and flexibility. The spreadsheet program features a macro language which can be interfaced with external databases. LibreOffice is stable and runs natively on Windows(R), Linux(R), FreeBSD, and Mac OS(R) X. More information about LibreOffice can be found at http://www.libreoffice.org/[libreoffice.org].

To install the English version of the LibreOffice package:

[source,bash]
....
# pkg install libreoffice
....

The editors category (https://www.FreeBSD.org/ports/editors/[freebsd.org/ports/editors/]) of the Ports Collection contains several localizations for LibreOffice. When installing a localized package, replace `libreoffice` with the name of the localized package.

Once the package is installed, type the following command to run LibreOffice:

[source,bash]
....
% libreoffice
....

During the first launch, some questions will be asked and a [.filename]#.libreoffice# folder will be created in the user's home directory.

If the desired LibreOffice package is not available, compiling the port is still an option. However, this requires a lot of disk space and a fairly long time to compile. This example compiles the English version:

[source,bash]
....
# cd /usr/ports/editors/libreoffice
# make install clean
....

[NOTE]
====
To build a localized version, `cd` into the port directory of the desired language. Supported languages can be found in the editors category (https://www.FreeBSD.org/ports/editors/[freebsd.org/ports/editors/]) of the Ports Collection.
====

[[desktop-viewers]]
== Document Viewers

Some new document formats have gained popularity since the advent of UNIX(R) and the viewers they require may not be available in the base system. This section demonstrates how to install the following document viewers:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Application Name
| Resources Needed
| Installation from Ports
| Major Dependencies

|Xpdf
|light
|light
|FreeType

|gv
|light
|light
|Xaw3d

|Geeqie
|light
|light
|Gtk+ or GNOME

|ePDFView
|light
|light
|Gtk+

|Okular
|light
|heavy
|KDE
|===

=== Xpdf

For users that prefer a small FreeBSD PDF viewer, Xpdf provides a light-weight and efficient viewer which requires few resources. It uses the standard X fonts and does not require any additional toolkits.

To install the Xpdf package:

[source,bash]
....
# pkg install xpdf
....

If the package is not available, use the Ports Collection:

[source,bash]
....
# cd /usr/ports/graphics/xpdf
# make install clean
....

Once the installation is complete, launch `xpdf` and use the right mouse button to activate the menu.

=== gv

gv is a PostScript(R) and PDF viewer. It is based on ghostview, but has a nicer look as it is based on the Xaw3d widget toolkit. gv has many configurable features, such as orientation, paper size, scale, and anti-aliasing. Almost any operation can be performed with either the keyboard or the mouse.

To install gv as a package:

[source,bash]
....
# pkg install gv
....

If a package is unavailable, use the Ports Collection:

[source,bash]
....
# cd /usr/ports/print/gv
# make install clean
....

=== Geeqie

Geeqie is a fork from the unmaintained GQView project, in an effort to move development forward and integrate the existing patches. Geeqie is an image manager which supports viewing a file with a single click, launching an external editor, and thumbnail previews. It also features a slideshow mode and some basic file operations, making it easy to manage image collections and to find duplicate files. Geeqie supports full screen viewing and internationalization.

To install the Geeqie package:

[source,bash]
....
# pkg install geeqie
....

If the package is not available, use the Ports Collection:

[source,bash]
....
# cd /usr/ports/graphics/geeqie
# make install clean
....

=== ePDFView

ePDFView is a lightweight `PDF` document viewer that only uses the Gtk+ and Poppler libraries. It is currently under development, but already opens most `PDF` files (even encrypted), save copies of documents, and has support for printing using CUPS.

To install ePDFView as a package:

[source,bash]
....
# pkg install epdfview
....

If a package is unavailable, use the Ports Collection:

[source,bash]
....
# cd /usr/ports/graphics/epdfview
# make install clean
....

=== Okular

Okular is a universal document viewer based on KPDF for KDE. It can open many document formats, including `PDF`, PostScript(R), DjVu, `CHM`, `XPS`, and ePub.

To install Okular as a package:

[source,bash]
....
# pkg install okular
....

If a package is unavailable, use the Ports Collection:

[source,bash]
....
# cd /usr/ports/graphics/okular
# make install clean
....

[[desktop-finance]]
== Finance

For managing personal finances on a FreeBSD desktop, some powerful and easy-to-use applications can be installed. Some are compatible with widespread file formats, such as the formats used by Quicken and Excel.

This section covers these programs:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Application Name
| Resources Needed
| Installation from Ports
| Major Dependencies

|GnuCash
|light
|heavy
|GNOME

|Gnumeric
|light
|heavy
|GNOME

|KMyMoney
|light
|heavy
|KDE
|===

=== GnuCash

GnuCash is part of the GNOME effort to provide user-friendly, yet powerful, applications to end-users. GnuCash can be used to keep track of income and expenses, bank accounts, and stocks. It features an intuitive interface while remaining professional.

GnuCash provides a smart register, a hierarchical system of accounts, and many keyboard accelerators and auto-completion methods. It can split a single transaction into several more detailed pieces. GnuCash can import and merge Quicken QIF files. It also handles most international date and currency formats.

To install the GnuCash package:

[source,bash]
....
# pkg install gnucash
....

If the package is not available, use the Ports Collection:

[source,bash]
....
# cd /usr/ports/finance/gnucash
# make install clean
....

=== Gnumeric

Gnumeric is a spreadsheet program developed by the GNOME community. It features convenient automatic guessing of user input according to the cell format with an autofill system for many sequences. It can import files in a number of popular formats, including Excel, Lotus 1-2-3, and Quattro Pro. It has a large number of built-in functions and allows all of the usual cell formats such as number, currency, date, time, and much more.

To install Gnumeric as a package:

[source,bash]
....
# pkg install gnumeric
....

If the package is not available, use the Ports Collection:

[source,bash]
....
# cd /usr/ports/math/gnumeric
# make install clean
....

=== KMyMoney

KMyMoney is a personal finance application created by the KDE community. KMyMoney aims to provide the important features found in commercial personal finance manager applications. It also highlights ease-of-use and proper double-entry accounting among its features. KMyMoney imports from standard Quicken QIF files, tracks investments, handles multiple currencies, and provides a wealth of reports.

To install KMyMoney as a package:

[source,bash]
....
# pkg install kmymoney-kde4
....

If the package is not available, use the Ports Collection:

[source,bash]
....
# cd /usr/ports/finance/kmymoney-kde4
# make install clean
....
