#
# $FreeBSD$
#
# Article: Building products using FreeBSD

DOC?=			article

FORMATS?=		html

INSTALL_COMPRESSED?=	gz
INSTALL_ONLY_COMPRESSED?=

SRCS=			article.sgml

IMAGES_EN=		freebsd-branches.eps

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
