# The FreeBSD Korean Documentation Project
# $FreeBSD$
# Original Revision: 1.7

SUBDIR = articles
#SUBDIR+= books

COMPAT_SYMLINK = ko

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
