# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA+=	cd.jpg cd-thumb.jpg
DATA+=	logo-bw.png logo-bw-thumb.png
DATA+=	logo-full.png logo-full-thumb.png
DATA+=	logo-reverse.png logo-reverse-thumb.png
DATA+=	logo-basic.ai logo-basic.svg logo-basic.png logo-basic-thumb.png
DATA+=	logo-simple.svg
DATA+=	postcard1.jpg postcard1-thumb.jpg
DATA+=	postcard2.jpg postcard2-thumb.jpg
DATA+=	postcard3.jpg postcard3-thumb.jpg
DATA+=	postcard4.jpg postcard4-thumb.jpg
DATA+=	wall1.jpg wall1-thumb.jpg
DATA+=	wall2.jpg wall2-thumb.jpg
DATA+=	wall3.jpg wall3-thumb.jpg

.include "${DOC_PREFIX}/share/mk/web.site.mk"
