#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# $FreeBSD$

SUBDIR =
SUBDIR+= building-products
SUBDIR+= contributing
SUBDIR+= cups
SUBDIR+= explaining-bsd
SUBDIR+= fonts
SUBDIR+= freebsd-questions
SUBDIR+= freebsd-update-server
SUBDIR+= hubs
SUBDIR+= ipsec-must
SUBDIR+= ldap-auth
SUBDIR+= leap-seconds
SUBDIR+= linux-emulation
SUBDIR+= linux-users
SUBDIR+= mailing-list-faq
SUBDIR+= nanobsd
SUBDIR+= new-users
SUBDIR+= port-mentor-guidelines
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports
SUBDIR+= remote-install
SUBDIR+= solid-state

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
