#
# Build the FreeBSD FAQ
#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: r38826
#
# $FreeBSD$

SUBDIR =
SUBDIR+= contributing
SUBDIR+= linux-users
SUBDIR+= problem-reports

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
