#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: r38826
#
# $FreeBSD$
#

DESTDIR?=	${DOCDIR}/pt_BR.ISO8859-1/articles/${.CURDIR:T}
