#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# $FreeBSD$

SUBDIR =
SUBDIR+= bsdl-gpl
SUBDIR+= building-products
SUBDIR+= contributing
SUBDIR+= cups
SUBDIR+= explaining-bsd
SUBDIR+= filtering-bridges
SUBDIR+= fonts
SUBDIR+= freebsd-questions
SUBDIR+= freebsd-update-server
SUBDIR+= hubs
SUBDIR+= ipsec-must
SUBDIR+= ldap-auth
SUBDIR+= leap-seconds
SUBDIR+= linux-emulation
SUBDIR+= linux-users
SUBDIR+= mailing-list-faq
SUBDIR+= nanobsd
SUBDIR+= new-users
SUBDIR+= pam
SUBDIR+= port-mentor-guidelines
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports
SUBDIR+= rc-scripting
SUBDIR+= remote-install
SUBDIR+= solid-state
SUBDIR+= vinum
SUBDIR+= vm-design

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
