#
# $FreeBSD$
#
# Article: Installing and using compiz-fusion
#
# %SOURCE%    en_US.ISO8859-1/articles/compiz-fusion/Makefile
# %SRCID%     1.1
#

MAINTAINER = doc@FreeBSD.org

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
