#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/marketing/Makefile,v 1.1 2005/05/18 16:25:37 andy Exp $
#
# Original revision: 1.1
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	os-comparison.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
