# $Id: Makefile,v 1.6 1998-08-12 09:04:06 hanai Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.10

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

# DOCS=   photos.sgml     
DOCS+=  internal.sgml   
DOCS+=  about.sgml
DOCS+=  machines.sgml
DOCS+=  mirror.sgml
DOCS+=  resignation.sgml

INDEXLINK=	internal.html

# DATA+=  README.mirror

.include "../../web.mk"
