# $Id: Makefile,v 1.4 1998-08-10 12:59:12 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.8

# DOCS=   photos.sgml     
DOCS+=  internal.sgml   
DOCS+=  about.sgml
DOCS+=  machines.sgml
DOCS+=  mirror.sgml
DOCS+=  resignation.sgml

# INDEXLINK=      internal.html

# DATA+=  README.mirror

.include "../../web.mk"
