# $Id: Makefile,v 1.8 1999-02-14 03:10:20 jkh Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.11

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

# DOCS=   photos.sgml     
DOCS+=  internal.sgml   
DOCS+=  about.sgml
DOCS+=  machines.sgml
DOCS+=  mirror.sgml
# DOCS+= statistic.sgml

INDEXLINK=	internal.html

# DATA+=  README.mirror

.include "../../web.mk"
