# $FreeBSD: www/en/releases/4.7R/Makefile,v 1.1 2002/08/06 07:45:45 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml qa.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
