---
title: "FreeBSD Press Release: October 18, 2000"
sidenav: about
loadPress: false
---

= FreeBSD Press Release: October 18, 2000

== Выбран новый состав Основной Команды FreeBSD

*BSD Conference, Монтерей, CA, 18 октября 2000* Проектом FreeBSD было объявлено о выборах новой основной команды разработчиков (Core Team), которая выполняет функции совета директоров. Это первый случай, когда состав команды определился в результате выборов между участниками проекта. В основную группу в качестве новых членов вошли Greg Lehey, Warner Losh, Mike Smith и Robert Watson. Повторно были выбраны Satoshi Asami, David Greenman, Jordan Hubbard, Doug Rabson и Peter Wemm.

Сооснователь Проекта FreeBSD и продолжающий оставаться членом основной группы Джордан Хаббард (Jordan Hubbard), выражая удовлетворенность результатами, сказал: "Впервые с момента основания проекта состав основной группы определился в результате свободных выборов, создав тем самым инцидент, когда любой разработчик может стать частью руководящей проектом группы". Новый состав основной группы также представляет собой группу высококлассных разработчиков со всего мира, специализирующихся в разных областях, от файловой системы RAID и разработки драйверов устройств до вопросов обеспечения безопасности систем.

Новые члены основной группы были выбраны из коммиттеров, формальной команды участников проекта FreeBSD. Коммиттеры имеют прямой доступ к хранилищу исходных текстов FreeBSD и выполняют основную работу по разработке программного обеспечения, связанного с проектом. До этого момента основная команда являлась самоорганизующейся группой, определяющей архитектурные и административные направления работы.

Этим летом коммиттеры проголосовали за переход к демократичной модели, позволяющей проекту соответствовать изменяющимся требованиям к разработке в сообществе открытой операционной системы. Однако, так как более половины старых членов основной группы остались в ней, преемственность сохраняется.

Ушедший из основной группы Poul-Henning Kamp сказал: "Я горжусь тем, что мы сделали в основной группе вместе за последние 8 лет. Новая основная группа, и сам факт, что она выбрана коммиттерами, означает, что в будущем проект будет в большей степени отвечать изменениям."

Смена состава в руководстве проектом прошла в хорошей обстановке, Кэмп отмечает, что все бывшие члены основной группы продолжат работать в проекте с большим напором на разработку: "Теперь я могу посвятить больше времени исходному коду FreeBSD, а не управлению проектом."

== Выбранные члены основной группы

*Satoshi Asami* - сооснователь и CTO компании DecorMagic, Inc. и отвечает за Коллекцию Портов FreeBSD.

*David Greenman* - сооснователь Проекта FreeBSD и в настоящий момент является президентом TeraSolutions, Inc., компании, производящей серверы Интернет и RAID-системы хранения данных.

*Jordan Hubbard* - сооснователь Проекта FreeBSD, а также его представитель по связям с общественностью и релиз-инженер. Он также является вице-президентом по Решениям с Открытым Кодом в BSDi.

*Greg Lehey* - исследователь, специализирующийся на открытом коде в Linuxcare; большую часть своей профессиональной карьеры он сделал в Германии, где работал на таких производителей вычислительной техники, как Univac, Tandem и Siemens-Nixdorf. Он является автором программного обеспечения Vinum для управления томами и RAID во FreeBSD, был привлечен к проекту SMPng во FreeBSD, и к тому же он является автором книг Porting Unix Software и The Complete FreeBSD.

*Warner Losh* занимался переносом кода pccard из NetBSD во FreeBSD и последние два года был начальником службы безопасности FreeBSD.

*Doug Rabson* является сооснователем компании Qube Software Ltd., специализирующейся на технологиях трехмерной графики. Его работа во FreeBSD включает перенос на платформы alpha и ia64, и он был главным идеологом системы драйверов устройств во FreeBSD.

*Mike Smith* является Principal Engineer в группе Open Source Solutions компании BSDi, и проявлял активность во FreeBSD как разработчик, как связывающий с OEM, иногда как архитектор и автор драйверов устройств.

*Robert Watson* является ученым-исследователем из NAI Labs, работающим над вопросами обеспечения безопасности сетей и операционных систем. Его вклад в Проект FreeBSD включает работу над расширениями операционной системы (http://www.trustedbsd.org[TrustedBSD]), архитектуру системы безопасности и работу в составе службы безопасности.

*Peter Wemm* был привлечен к FreeBSD с первых дней работы ISP в Австралии и с тех пор успел переехать в США, где работает в качестве инженера по программному обеспечению в компании Yahoo!, Inc. Его работа во FreeBSD включает управление хранилищем исходного кода FreeBSD и работа над ядром.

== О FreeBSD

FreeBSD является свободно лицензируемой операционной системой с открытым кодом, ведущей свою родословную от BSD Net/2 и 4.4 Lite, дистрибутивах Berkeley Software, разрабатывавшихся в Калифорнийском Университете в Беркли до 1994 года. Она разрабатывается и поддерживается всемирной организацией разработчиков, как оплачиваемых и работающих бесплатно. FreeBSD отличают высокая производительность работы в сети и с файловой подсистемой, что широко используется провайдерами Интернет, включая такие известные в индустрии компании, как *Yahoo!*, *above.net* и *Verio*. FreeBSD также часто используется как платформа для встраиваемых сетевых устройств, включая продукты таких компаний, как *IBM*, *Inktomi*, *Juniper Networks* и *Network Alchemy - a Nokia Company*.

Более подробная информация может быть найдена по адресу http://www.FreeBSD.org[http://www.FreeBSD.org/].

== Контакты с прессой

Jordan Hubbard +
The FreeBSD Project +
925-682-7859 +
jkh@FreeBSD.org

== # # #

BSD является зарегистрированным торговым знаком Berkeley Software Design, Inc. Все другие торговые марки являются собственностью их владельцев. Технологии BSD первоначально были разработаны в Калифорнийском Университете в Беркли и его участниками.
