---
title: "FreeBSD Press Release: April 29, 1999"
sidenav: about
loadPress: false
---

= FreeBSD Press Release: April 29, 1999

== Полная система разработки XML интегрирована во FreeBSD

*Конкорд, CA, 29 апреля 1999*: Во FreeBSD 3.1 включена полная интегрированная система разработки SGML/XML, которая устанавливается простой, легко повторяемой последовательностью команд.

Система портов FreeBSD и ее многозадачная архитектура позволяет разработчику SGML/XML легко сгружать и устанавливать все самые последние версии инструментария и справочных материалов, которые нужны для работы с языками разметки SGML и XML и документами в этих форматах, а онлайновые списки рассылки в Internet помогают им всегда иметь последние разработки, касающиеся реализации XML.

FreeBSD - это полноценная операционная система с открытым кодом, которая работает практически на всех персональных компьютерах с архитектурой Intel x86. Ее 580-страничное "Руководство" недавно было полностью переведено в формат DocBook, и это является живым примером эволюции документа, построенного с помощью SGML-утилит. Руководство доступно в Internet по адресам:

* http://www.FreeBSD.org/handbook/
* ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/

Проект документирования FreeBSD также опубликовал книгу "Проект документирования FreeBSD в примерах", чтобы облегчить новичкам внесение изменений в пакет документации по FreeBSD. В основном информация из этого документа подходит для всех пользователей SGML/XML, и свободно доступна. Этот документ, постоянно дополняемый командой Проекта Документирования, можно найти по адресам:

* http://www.FreeBSD.org/tutorials/primer/

=== Возможности системы SGML/XML Проекта Документирования включают:

* Jade 1.2.1 и SP suite версии 1.3.3 Джеймса Кларка (James Clark), осуществляющие форматирование и проверку документов SGML и XML.
* Полный набор для разметки 19 наборов символов ISO в SGML
* DocBook (v2.4.1, v3.0, v3.1), HTML (все версии) и LinuxDoc Document Type Definitions (DTD)
* Modular DocBook Stylesheets Норма Уолша (Norm Walsh), позволяющие управлять внешним видом и форматированием DocBook-документов.
* Emacs и XEmacs вместе с пакетом расширения PSGML, дает настраиваемое решение промышленного уровня для редактирования SGML.
* Пакет teTeX-beta вместе с макросами JadeTeX позволяют осуществлять перенос документов в формате DocBook в DVI, Postscript и PDF со встроенными гиперссылками.
* Дополнительные программы и утилиты, работающие с SGML, можно найти в системе портов FreeBSD.

Проект документирования FreeBSD активно переходит от LinuxDoc DTD к DocBook DTD и все эти годы предоставляет информацию о новых возможностях и способах работы с DocBook все эти годы. Для получения подробной информации о Проекте Документирования FreeBSD, обратитесь в список рассылки freebsd-doc@FreeBSD.org.

Операционная система FreeBSD доступна для сгрузки в Internet с основного сайта FreeBSD и с различных зеркал по всему миру, а также может быть получена на обычном компакт-диске в фирме Walnut Creek CDROM. Информация обо всех этих возможностях находится по таким адресам:

* http://www.FreeBSD.org/
* http://www.wccdrom.com/
