---
title: "Пресс-релиз FreeBSD: 22 апреля 1999"
sidenav: about
loadPress: false
---

= Пресс-релиз FreeBSD: 22 апреля 1999

== Для создания зрелищных спецэффектов применялась FreeBSD

*Конкорд, CA, 22 апреля 1999*: Для создания большого количества спецэффектов в последнем фильме кинокомпании Warner Brothers, _The Matrix_, использовались 32 двухпроцессорные системы, работающие под управлением FreeBSD.

Компания Manex Visual Effects использовала 32 системы Dell Precision 410 Dual P-II/450 под управлением FreeBSD в качестве основы для кластера CG Render Farm. Чарльз Хенрик (Charles Henrich), главный системный администратор фирмы Manex, сказал: "В процессе создания наступил момент, когда мы обнаружили, что имеющейся у нас инфраструктуре, основанной на SGI, не хватает вычислительной мощности для интенсивных 3-D вычислений. И тогда мы решили опереться на решение, основанное на FreeBSD, из-за возможности быстро получить требуемое оборудование, а также надежности и простоты администрирования, которое дает FreeBSD. Связавшись с Dell, мы заказали 32 таких системы в среду, а в субботу днем они уже были включены в работу. Это была по-настоящему сложная задача для всех, и я не думаю, что мы бы с ней справились, выбрав любую другую операционную систему."

Операционная система FreeBSD - это мощная система с полностью открытым исходным кодом, основанная на Berkeley Software Distribution ОС UNIX. Она свободно доступна с множества сайтов Internet а также на компакт-дисках, распространяемых компанией Walnut Creek CDROM, и включает тысячи портированных приложений, включая те, которые работают с трехмерной графикой и множество других не менее мощных инструментов. FreeBSD оптимизирована для использования на процессорах семейства Intel x86, которые являются сердцем современных персональных компьютеров. Обладающая неисчерпаемыми возможностями по индивидуальной настройке и оптимизации, FreeBSD является сердцем таких мощных приложений Internet, как Yahoo! и U.S. West, потому что диапазон ее не ограничен коммерческой лицензией и она может свободно распространяться и модифицироваться.

Для получения дополнительной информации о FreeBSD, посетите сайт http://www.FreeBSD.org/ и http://www.wccdrom.com/. Для получения дополнительной информации о компании Manex Visual Effects, посетите сервер http://www.mvfx.com/.
