---
title: "Пресс-релиз FreeBSD: 9 марта 2000"
sidenav: about
loadPress: false
---

= Пресс-релиз FreeBSD: 9 марта 2000

== ДЛЯ НЕМЕДЛЕННОГО ОПУБЛИКОВАНИЯ

== КОМПАНИИ, ПОДДЕРЖИВАЮЩИЕ BSD, ОБъЕДИНЯЮТСЯ ДЛЯ СОЗДАНИЯ САМЫХ ПОПУЛЯРНЫХ ОПЕРАЦИОННЫХ СИСТЕМ ДЛЯ INTERNET

=== Обновлённая BSDI собирается выпускать операционную систему, основанную на знаменитых технологиях BSD и поддерживать быстро растущее сообщество FreeBSD, операционной системы с идеологией Open Source

*Колорадо Спрингс, Колорадо, 9 марта 2000:* Компания Berkeley Software Design, Inc. (BSDI) объявила сегодня о слиянии с Walnut Creek CDROM, дистрибутором популярной операционной системы FreeBSD. После слияния обновленная BSDI объединит ведущих разработчиков и распространителей операционных систем ветки Berkeley Software Distribution. BSDI будет развивать и распространять BSD/OS, операционную систему и платформу для Internet, в то же время делясь с Проектом FreeBSD, построенным на идеологии открытого кода, своими технологиями, финансовой помощью и расширенной поддержкой пользователей.

Операционные системы BSD используются на самых загруженных сайтах Internet и самыми крупными провайдерами услуг, в список которых входит Yahoo!, Hotmail фирмы Microsoft и UUNET, подразделение компании MCI WorldCom. Согласно исследованию Survey.com, лидирующей компании в области исследований электронных средств массовой информации, BSD и Linux сегодня являются самыми быстро растущими операционными системами.

Операционная система BSD, сетевые технологии и технологии Internet широко применяются в инфраструктуре Internet. Более 100,000 коммерческих пользователей Internet используют BSD на более чем 2,000,000 серверов. Примерно 9 из 10 провайдеров услуг интернет (ISP) и провайдеров сетевых услуг (NSP), а также 15 процентов всех сайтов Internet работают под управлением систем BSD. Операционные системы BSD также работают в новаторские разработки компаний Intel, IBM, Lucent, F5 Labs, Hitachi и многих других.

BSDI также объявила, что Yahoo! Inc. будет оказывать поддержку новой компании. BSDI будет использовать эту поддержку для воплощения в жизнь своего стремления объединить новаторские разработки с открытым кодом и коммерческие интересы. Помощь будет использоваться для усиления позиций BSDI как основного поставщика наиболее мощных операционных систем для построения инфраструктуры Internet.

BSDI собирается сформироваться единый образ для операционных систем BSD. Компания будет распространять, поддерживать и развивать как BSD/OS, так и FreeBSD. BSDI и Проект FreeBSD сейчас совместно исследуют требования технологии и маркетинга для слияния кода двух операционных систем.

== Лидерство обновленной BSDI

"Технологии BSD имеют долгую историю развития в качестве вычислительных систем, образующих основу Internet", - сказал доктор Маршалл Кирк МакКузик (Dr. Marshall Kirk McKusick), руководитель BSDI. "Новый BSDI будет и далее развивать вычислительную платформу BSD, которая уже широко используется во всем мире." МакКузик был одним из создателем Группы Исследований Вычислительных Систем (Computer Systems Research Group - CSRG) в Калифорнийском Университете (Беркли) и широко известен как основной вкладчик на раннем этапе становления движения Open Source.

Для реализации новой политики BSDI, ее продвижения к цели и продолжения роста доходов на пост исполнительного директора был приглашен Гэри Дж. Джонсон (Gary J. Johnson). Джонсон является опытным управленцем, работавшим на высоких руководящих позициях в области менеджмента, маркетинга и продаж в таких лидирующих компаниях из Кремниевой Долины, как Tandem Computers (Compaq), Convergent Technologies (Unisys) и SCO. Последнее время Джонсон являлся президентом компании ClickService Software, основным поставщиком программного обеспечения для электронной коммерции в области управления связями с клиентурой (CRM).

"Инновации в области операционных систем весьма сильно опираются на работу в сообществе, поддерживающем открытый код", сказал Джонсон. "На сегодняшний день компании, поддерживающие Linux, такие, как Red Hat Software и VA Linux, привлекли большое внимание к идеологии открытого кода в разработках. Однако в для организации работы Internet в основном применяются технологии BSD. Новая BSDI будет тесно сотрудничать с сообществом, поддерживающим открытый код, чтобы удовлетворять все более усиливающийся спрос на серверы Internet, приложения, сопутствующие инструменты и другие элементы, жизненно важные для инфраструктуры Internet."

Кроме текущих обязанностей, Майк Карелс (Mike Karels), вице-президент BSDI по разработкам и бывший главный архитектор системы и разработчик принципиальных частей системы в CSRG из Калифорнийского Университета (Беркли), планирует подключиться к команде архитекторов в Проекте FreeBSD. Карелс, который пришел на смену основателя Sun Microsystems Билла Джоя Bill Joy в CSRG, известен как один из крупнейших разработчиков внутренностей Unix и программного обеспечения для работы с TCP/IP.

"Технологии BSD были приложены к продолжающемуся успеху Yahoo!, дав надежность и масштабируемость, которая была нужна нам для обеспечения круглосуточной работы Yahoo! вне зависимости от нагрузки", сказал Дэвид Файло (David Filo), основатель и руководитель Yahoo, Yahoo! Inc.

== BSDI продолжит распространение BSD/OS и FreeBSD: Расширение и ускорение разработок в направлении идеологии открытого кода FreeBSD

Обновленная BSDI будет предлагать и поддерживать FreeBSD, BSD/OS, BSDI Internet Super Server и другие продукты линии BSD через свои каналы продаж по всему миру всем провайдерам инфраструктуры Internet, прикладным разработчикам и корпоративным пользователям. BSDI будет предлагать коммерчески поддерживаемые операционные системы BSD и связанные с ними приложения, платформы для работы Internet, техническую поддержку и услуги, разработку программного обеспечения с открытым кодом и консалтинговые услуги. Компания будет разрабатывать свои сетевые и internet технологии BSD для основных микропроцессорных платформ, включая Intel, SPARC, Alpha, PowerPC и StrongARM.

BSDI продолжит разработку, развитие и продвижение BSD/OS и FreeBSD в рамках дружественной к бизнесу необременяющей лицензии Berkeley software, что ускорит разработки программных проектов с открытым кодом, встроенных систем, специализированных приложений, информационные инструментов и других продуктов, связанных с использованием операционных систем.

BSDI будет развивать и ускорять развитие открытого кода FreeBSD компании Walnut Creek CDROM с помощью обмена техническими новациями BSD/OS с Проектом FreeBSD и давая этому проекту с открытым кодом оперативную и техническую поддержку, маркетинг и финансирование. BSDI продолжит распространение коробочных версий FreeBSD, а также планирует разработку дополнительных продуктов, основанных на FreeBSD, как и предоставление технической поддержки, консалтинговых услуг, образовательных услуг и учебных курсов для пользователей FreBSD. Предполагается, что эти шаги помогут в продвижении и укреплении систем BSD с открытой моделью вычислений. Проект FreeBSD разрабатывает популярную операционную систему FreeBSD, в которую включено и интегрировано дополнительное программное обеспечение от более чем 5000 разработчиков со всего мира.

== Лидеры Internet и движения Open Source поддерживают новую BSDI

"Мы довольны, что BSDI поддерживает сообщество FreeBSD с открытым кодом", сказал Джордан Хаббард, главный евангелист и основатель Проекта FreeBSD. "Новая BSDI достаточно компетентна в вопросах коммерции, управления, распространении и поддержки самой продвинутой операционной системы для Internet в мире. Мы рады и с надеждой смотрим на будущее партнерство с ведущими разработчиками BSDI, особенно это касается Майка Карелса и других разработчиков, работавших первоначально в CSRG Калифорнийского Университета в Беркли, для ускорения работы над операционной системой, сетевыми технологиями и инновационными возможностями Internet."

"Операционные системы с открытым кодом, такие, как BSD, предлагают лучшую технологию и больше выбора пользователям", сказал Эрик Рэймонд (Eric Raymond), президент Open Source Initiative. "Я полагаю, что BSDI еще раз продемонстрирует, что сообщество, поддерживающее открытый код и деловой мир совместно могут сделать великие дела, двигая индустрию вперед так же, как Internet."

"Наше исследование показывает, что BSD и Linux усилят свое присутствие на серверах корпораций от 100 до 500 процентов в течении последующих двух лет в основных приложениях, на которых зиждется бизнес в США", сказал Дэйв Троубридж (Dave Trowbridge), ведущий аналитик в Survey.com. "Эта новая компания поможет занять BSD свое место под солнцем, соответствующее ее богатым возможностям и крепкой технической основе."

== Об операционной системе Berkeley Software Distribution

Технологии операционной системы Berkeley Software Distribution первоначально были разработаны с 1979 по 1992 в Группе Исследований Вычислительных Систем Computer Systems Research Group (CSRG) в Калифорнийском Университете (Беркли). Операционные системы, опирающиеся на код BSD и ее сетевые технологии, лежат в основе самых современных Unix и Unix-подобных операционных систем. Сегодня практически каждый крупный провайдер инфраструктуры Internet использует операционные системы BSD. Технологии операционных систем BSD используются в большинстве критически важных сетевых вычислениях и встроены в платформы построения Internet, требующие особенной функциональности, надежности и безопасности.

== О Проекте FreeBSD

FreeBSD является популярной операционной системой с открытым кодом, разработанной в рамках Проекта FreeBSD и его командой разработчиков со всего мира, состоящей из более чем 5000 человек, труд которых пропускаются через 185 "коммиттеров". Она свободно доступна для сгрузки с сервера ftp.FreeBSD.org, а также распространяется как коробочный продукт через CompUSA, Fry's, Borders, Ingram, FreeBSDmall.com и другие компании. В поставку FreeBSD включены тысячи портированных приложений, включая самые популярные из них для работы с вебом, Internet и электронной почтой. FreeBSD распространяется на условиях лицензии Berkeley Software Distribution, что означает ее свободное копирование и модификацию. Подробная информация о Проекте FreeBSD находится на сервере http://www.FreeBSD.org/[www.FreeBSD.org].

== О компании Walnut Creek CDROM

Компания Walnut Creek CDROM была основана в 1991 и начала выпуск программного обеспечения Linux в 1992, а BSD в 1993. Компания имеет длинную историю тесной работы с сообществом свободного программного обеспечения и предоставляет финансирование, оборудование и другие ресурсы для проектов с открытым кодом. Walnut Creek CDROM выпускает широкую номенклатуру программ, включая FreeBSD и Slackware, самую похожую на BSD версию Linux.

О компании Berkeley Software Design, Inc. (BSDI)

Основные разработчики BSD основали Berkeley Software Design, Inc. в 1991 для коммерциализации технологий BSD и продолжения традиций Unix из Berkeley как надежной, устойчивой и весьма защищенной операционной системы Internet для сетевых вычислений. После слияния Berkeley Software Design, Inc. и Walnut Creek CDROM, BSDI становится основным поставщиком продвинутых операционных систем для Internet и построения его инфраструктуры. Вы можете вступить в контакт с BSDI по адресу info@BSDI.com или http://www.BSDI.com/[www.BSDI.com] или позвонить по телефону 1-719-593-9445 (бесплатный: 1-800-800-4273).

== # # #

BSD является зарегистрированной торговой маркой, а BSD/OS и BSDI являются товарными марками Berkeley Software Design, Inc. Yahoo! и логотип Yahoo! являются зарегистрированными товарными марками Yahoo! Inc. Все торговые марки, упомянутые в этом документе, являются собственностью их владельцев.

Для контактов: +
Kevin Rose +
BSDI +
801-553-8166 +
kgr@bsdi.com

Jordan Hubbard +
FreeBSD Project +
925-691-2863 +
jkh@FreeBSD.org

Brigid Fuller +
ZNA Communications +
831-425-1581 +
brigid@zna.com
