# Summary of work needed to support large disks and arrays.
#
# $FreeBSD$

MAINTAINER=	scottl

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.xml
DATA=	style.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
