# $FreeBSD: doc/ja_JP.eucJP/articles/multi-os/Makefile,v 1.1.1.1 2000/01/06 07:22:41 kuriyama Exp $
# Original revision: 1.8

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

NO_TIDY= YES

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
