# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=		md5.sums.20121118.txt
DATA+=		sha256.sums.20121118.txt

.include "${DOC_PREFIX}/share/mk/web.site.mk"
