#
#	The FreeBSD Documentation Project
#	The FreeBSD German Documentation Project
#
#	$FreeBSD$
#	$FreeBSDde: de-docproj/articles/solid-state/Makefile,v 1.2 2011/12/31 12:33:27 bcr Exp $
#	basiert auf: 1.5
#
# Article: FreeBSD und Solid State Devices

DOC?= article

FORMATS?= html html-split
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?= ../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
