#
#	The FreeBSD Documentation Project
#	The FreeBSD German Documentation Project
# 
#	$FreeBSD$
#	$FreeBSDde: de-docproj/articles/solid-state/Makefile,v 1.1 2010/09/18 13:58:33 bcr Exp $
#	basiert auf: 1.17
#
# Article: FreeBSD und Solid State Devices

DOC?= article

FORMATS?= html html-split
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?= ../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
