---
title: Chapter 2. Tools
prev: books/fdp-primer/overview
next: books/fdp-primer/working-copy
description: Tools used in the FreeBSD Documentation Project
tags: ["tools", "required tools", "optional tools"]
showBookMenu: true
weight: 3
params:
  path: "/books/fdp-primer/tools/"
---

[[tools]]
= Tools
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 2
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

Several software tools are used to manage the FreeBSD documentation and render it to different output formats.
Some of these tools are required and must be installed before working through the examples in the following chapters.
Some are optional, adding capabilities or making the job of creating documentation less demanding.

[[tools-required]]
== Required Tools

Install `docproj` _meta-port_ as shown in crossref:overview[overview,the overview chapter] from the Ports Collection.
These applications are required to do useful work with the FreeBSD documentation.
Some further notes on particular components are given below.

[[tools-optional]]
== Optional Tools

These applications are not required, but can make working on the documentation easier or add capabilities.

[[tools-optional-software]]
=== Software

Vim (package:editors/vim[]) -- a popular editor for working with Asciidoctor.

Emacs (package:editors/emacs[]).

Both tools include a special mode that reduces the amount of typing needed, and helps to reduce errors.
