---
title: Chapter 2. Tools
prev: books/fdp-primer/overview
next: books/fdp-primer/working-copy
---

[[tools]]
= Tools
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 2

toc::[]

Several software tools are used to manage the FreeBSD documentation and render it to different output formats. Some of these tools are required and must be installed before working through the examples in the following chapters. Some are optional, adding capabilities or making the job of creating documentation less demanding.

[[tools-required]]
== Required Tools

Install `hugo` and `asciidoctor` as showed in the <<overview,the overview chapter>> from the Ports Collection. These applications are required to do useful work with the FreeBSD documentation. Some further notes on particular components are given below.

[[tools-optional]]
== Optional Tools

These applications are not required, but can make working on the documentation easier or add capabilities.

[[tools-optional-software]]
=== Software

Vim (package:editors/vim[])::
A popular editor for working with AsciiDoctor.

Emacs (package:editors/emacs[])::
Both of these editors include a special mode for editing documents. This mode includes commands to reduce the amount of typing needed, and help reduce the possibility of errors.
