# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

# DOCS=	announce.xml schedule.xml todo.xml
# DOCS+=	hardware.xml relnotes.xml installation.xml
DOCS= relnotes.xml installation.xml

# DATA=	docbook.css
# DATA+=	errata.html
# DATA+=	early-adopter.html
# DATA+=	hardware-alpha.html
# DATA+=	hardware-ia64.html
# DATA+=	hardware-i386.html
# DATA+=	hardware-pc98.html
# DATA+=	hardware-sparc64.html
# DATA+=	relnotes-alpha.html
# DATA+=	relnotes-ia64.html
# DATA+=	relnotes-i386.html
# DATA+=	relnotes-pc98.html
# DATA+=	relnotes-sparc64.html
# DATA+=	installation-alpha.html
# DATA+=	installation-ia64.html
# DATA+=	installation-i386.html
# DATA+=	installation-pc98.html
# DATA+=	installation-sparc64.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
