#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#       $FreeBSD$
#       $FreeBSDde: de-docproj/articles/Makefile,v 1.6 2009/01/17 11:49:01 jkois Exp $
#       basiert auf:  1.42

SUBDIR = contributing
SUBDIR+= contributing-ports
SUBDIR+= explaining-bsd
SUBDIR+= laptop
SUBDIR+= linux-comparison
SUBDIR+= new-users
SUBDIR+= version-guide

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
