#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#       $FreeBSD$
#       $FreeBSDde: de-docproj/articles/Makefile,v 1.3 2005/01/29 11:48:10 jkois Exp $
#       basiert auf:  1.42

SUBDIR = contributing
SUBDIR+= explaining-bsd
SUBDIR+= laptop
SUBDIR+= new-users

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
