#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD$
#    $FreeBSDde: de-docproj/articles/Makefile.inc,v 1.1 2004/11/28 21:13:46 jkois Exp $
#    basiert auf: 1.4
#

DESTDIR?=	${DOCDIR}/de_DE.ISO8859-1/articles/${.CURDIR:T}
