#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#       $FreeBSD$
#       $FreeBSDde: de-docproj/articles/Makefile,v 1.4 2005/08/26 19:42:43 jkois Exp $
#       basiert auf:  1.42

SUBDIR = contributing
SUBDIR+= explaining-bsd
SUBDIR+= laptop
SUBDIR+= new-users
SUBDIR+= version-guide

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
