# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.10

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq2.xml
DOCS+=	gnome_porting.xml
DOCS+=	gnome2_porting.xml
DOCS+=	porting.xml
DOCS+=	bugging.xml
DOCS+=  volunteer.xml
# DOCS+=	knownissues.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
