# $FreeBSD: www/es/security/Makefile,v 1.2 1999/09/06 07:03:14 peter Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=  
DOCS+=	programmers.sgml
DOCS+=	security.sgml
DOCS+=  secure.sgml

INDEXLINK= security.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
