# $Id: Makefile,v 1.1.1.1 1999-02-08 19:26:12 wosch Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=  
DOCS+=	programmers.sgml
DOCS+=	security.sgml
DOCS+=  secure.sgml

INDEXLINK= security.html

.include "../web.mk"
