---
title: Manual de FreeBSD
authors:
  - author: Proyecto de Documentación de FreeBSD
copyright: 1995-2020 Proyecto de Documentación de FreeBSD
trademarks: ["freebsd", "ibm", "ieee", "redhat", "3com", "adobe", "apple", "intel", "linux", "microsoft", "opengroup", "sun", "realnetworks", "oracle", "3ware", "arm", "adaptec", "google", "heidelberger", "intuit", "lsilogic", "themathworks", "thomson", "vmware", "wolframresearch", "xiph", "xfree86", "general"] 
next: books/handbook/preface
showBookMenu: true
weight: 0
params:
  path: "/books/handbook/"
---

= Manual de FreeBSD
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[.abstract-title]
Resumen

¡Bienvenido a FreeBSD! Este manual cubre la instalación y uso diario de _FreeBSD {rel121-current}-RELEASE_ and _FreeBSD {rel114-current}-RELEASE_. Este manual está en _constante evolución_ y es el resultado del trabajo de muchas personas. Algunas secciones no están completas y otras necesitan ser actualizadas. Si está interesado en colaborar en este proyecto envíe un mensaje de correo electrónico a {freebsd-doc}. La última versión de este documento está siempre disponible en el http://www.FreeBSD.org[ sitio web de FreeBSD]. También puede encontrarla en diferentes formatos y opciones de compresión en el link:ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/[servidor FTP de FreeBSD] o en las numerosas crossref:mirrors[mirrors-ftp,réplicas]. Si prefiere una copia en papel de este manual puede comprarla en http://www.freebsdmall.com/[FreeBSD Mall]. También es posible link:https://www.FreeBSD.org/search/[hacer búsquedas] en este manual.

'''
