---
title: Parte II. Tareas comunes
prev: books/handbook/x11
next: books/handbook/desktop
---

ifdef::env-beastie+backend-html5[]
:chapters-path: content/{{% lang %}}/books/handbook/
endif::[]

ifndef::env-beastie[]
:chapters-path:
endif::[]

[[common-tasks]]
= Tareas comunes

Una vez tratados los aspectos más básicos, pasaremos a detallar alguna de las características más utilizadas de FreeBSD:

* Introducción a algunas de las aplicaciones de escritorio más útiles y extendidas: navegadores, herramientas de productividad, visores de documentos, etc.
* Introducción a algunas de las herramientas multimedia de FreeBSD.
* Explicación de cómo crear un kernel personalizado en FreeBSD, lo que le permitirá añadir nuevas funcionalidades al sistema.
* Descripción en detalle del sistema de impresión, tanto en entornos de escritorio como en impresoras conectadas en red.
* Cómo ejecutar aplicaciones de Linux(R) en FreeBSD.

Algunos de los capítulos recomiendan lecturas de capítulos anteriores, lo que se indica al inicio de cada capítulo.

include::{chapters-path}toc-2.adoc[]
