DATA=	apache.gif apachepower.gif daemon.gif dir.gif doc.gif
DATA+=	home.gif littlelogo.gif new.gif power-button.gif
DATA+=	powerlogo.gif ugu_icon.gif wclogo.gif topbar.gif
DATA+=  flash0.gif flash1.gif soft0.gif soft1.gif support0.gif support1.gif
DATA+=  docs0.gif docs1.gif vendors0.gif vendors1.gif search0.gif search1.gif
DATA+=  index0.gif index1.gif get0.gif get1.gif faq0.gif faq1.gif
DATA+=  handboo0.gif handboo1.gif dae_up2.gif bar.gif
DATA+=  freebsd_1.gif powerani.gif pbfbsd2.gif
.include "../web.mk"
