# $FreeBSD: www/en/gifs/Makefile,v 1.47 2003/12/14 17:28:12 ceri Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   apache.gif apachepower.gif daemon.gif dir.gif doc.gif
DATA+=  home.gif littlelogo.gif new.gif power-button.gif
DATA+=  powerlogo.gif ugu_icon.gif wclogo.gif topbar.gif
DATA+=  flash0.gif flash1.gif soft0.gif soft1.gif support0.gif support1.gif
DATA+=  docs0.gif docs1.gif vendors0.gif vendors1.gif search0.gif search1.gif
DATA+=  index0.gif index1.gif get0.gif get1.gif faq0.gif faq1.gif
DATA+=  handboo0.gif handboo1.gif dae_up2.gif dae_up3.gif bar.gif
DATA+=  freebsd_1.gif powerani.gif pbfbsd2.gif 205-jp.jpg
DATA+=  205-jpb.jpg bsdisc.jpg bsdiscb.jpg comp_b.jpg complete.jpg
DATA+=  cover.jpg coverb.jpg fultus-cover.gif fullcourse3.jpg
DATA+=  fullcourse3b.jpg getstarb.jpg getstart.jpg
DATA+=  jp.jpg jpb.jpg kr.jpg krb.jpg las5.jpg las5b.jpg las512.jpg
DATA+=  las512b.jpg las523.jpg las523b.jpg wc-docs.jpg wc-docsb.jpg
DATA+=  pc98-jp.jpg pc98-jpb.jpg pht.jpg phtb.jpg running.jpg
DATA+=  runningb.jpg starkit.jpg starkitb.jpg tw.jpg twb.jpg
DATA+=  unixuser.jpg unixuserb.jpg wc-10.jpg wc-10b.jpg wc-11.jpg wc-11b.jpg 
DATA+=  wc-200.jpg wc-200b.jpg wc-205.jpg wc-205b.jpg wc-21.jpg wc-215.jpg 
DATA+=  wc-215b.jpg wc-216.jpg wc-216b.jpg wc-216jp.jpg wc-216jpb.jpg 
DATA+=  wc-217.jpg wc-217b.jpg wc-21b.jpg wc-221.jpg wc-221b.jpg 
DATA+=  wc-222.jpg wc-222b.jpg wc-22snap.jpg wc-22snapb.jpg 
DATA+=  wc-44lite2.jpg wc-44lite2b.jpg wc-blun.jpg wc-blunb.jpg 
DATA+=  wc-30snab.jpg wc-30sna.jpg newsletb.jpg newslett.jpg
DATA+=  newslet2b.jpg newslet2.jpg
DATA+=  banner1.gif banner2.gif banner3.gif banner4.gif
DATA+=  lynx.gif
DATA+=  smart-reseller-small.jpg smart-reseller.jpg
DATA+=	bsdm.jpg
DATA+=	bsdmb.jpg
DATA+=	fhp_mini.jpg
DATA+=  mall_title_tiny.gif
DATA+=  mall_title_medium.gif
DATA+=  plueschtier-tiny.jpg
DATA+=	instman.jpg instmanb.jpg sam.jpg samb.jpg urm.jpg urmb.jpg
DATA+=	releases.jpg bug.jpg doc.jpg news.jpg power.jpg
DATA+=	gourchin3.gif
DATA+=	darbylogo.gif
DATA+=	bsdmagazine.jpg
DATA+=	aboutf.jpg aboutfb.jpg
DATA+=	bukudepan.jpg
DATA+=	wc-bsdtool.gif
DATA+=	wc-bsdalph-4.2.gif
DATA+=	wc-freebsd-4.2.gif wc-freebsd-4.2b.gif
DATA+=	bsdcomp-4.2.gif
DATA+=	lob-freebsd-4.2.gif lob-freebsd-4.4-small.gif lob-freebsd-4.4.gif
DATA+=	daemon_hammer.jpg
DATA+=	daemon_hammer-tn15.jpg daemon_hammer-tn20.jpg daemon_hammer-tn25.jpg
DATA+=	branches.png
DATA+=	wr-bsdtool-june2001.png wr-freebsd43.png wr-freebsd44.png
DATA+=	wr-handbook-2nd.png
DATA+=	bsdi-handbook.png fm-freebsd45.png
DATA+=  done.png how_to_contribute.png in_progress.png news.png
DATA+=  not_planned.png not_started.png project_goal.png project_plan.png
DATA+=  resources_and_links.png status_board.png blocked.png c99.jpg
DATA+=  fbsdcng-english.png fbsdcng-japanese.png
DATA+=  abs_bsd_cov.gif fbsd-ososfypc.jpg
DATA+=  kapak.jpg kapak_sml.jpg
DATA+=  1.pnm 2.pnm 3.pnm 4.pnm 5.pnm 6.pnm 7.pnm 8.pnm 9.pnm
DATA+=  A.pnm B.pnm C.pnm D.pnm E.pnm F.pnm G.pnm H.pnm I.pnm J.pnm
DATA+=  K.pnm L.pnm M.pnm N.pnm P.pnm Q.pnm R.pnm S.pnm T.pnm U.pnm
DATA+=  V.pnm W.pnm X.pnm Y.pnm Z.pnm

.include "${WEB_PREFIX}/share/mk/web.site.mk"
