DATA=	apache.gif apachepower.gif daemon.gif dir.gif doc.gif
DATA+=	freebsd-advert.gif home.gif littlelogo.gif new.gif power-button.gif
DATA+=	powerlogo.gif ugu_icon.gif wclogo.gif

.include "../web.mk"
