# $FreeBSD: www/en/gifs/Makefile,v 1.30 1999/10/20 19:49:15 motoyuki Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DATA=   apache.gif apachepower.gif daemon.gif dir.gif doc.gif
DATA+=  home.gif littlelogo.gif new.gif power-button.gif
DATA+=  powerlogo.gif ugu_icon.gif wclogo.gif topbar.gif
DATA+=  flash0.gif flash1.gif soft0.gif soft1.gif support0.gif support1.gif
DATA+=  docs0.gif docs1.gif vendors0.gif vendors1.gif search0.gif search1.gif
DATA+=  index0.gif index1.gif get0.gif get1.gif faq0.gif faq1.gif
DATA+=  handboo0.gif handboo1.gif dae_up2.gif bar.gif
DATA+=  freebsd_1.gif powerani.gif pbfbsd2.gif 205-jp.jpg
DATA+=  205-jpb.jpg bsdisc.jpg bsdiscb.jpg comp_b.jpg complete.jpg
DATA+=  cover.jpg coverb.jpg fullcourse3.jpg
DATA+=  fullcourse3b.jpg getstarb.jpg getstart.jpg
DATA+=  jp.jpg jpb.jpg kr.jpg krb.jpg las5.jpg las5b.jpg las512.jpg
DATA+=  las512b.jpg las523.jpg las523b.jpg wc-docs.jpg wc-docsb.jpg
DATA+=  pc98-jp.jpg pc98-jpb.jpg pht.jpg phtb.jpg running.jpg
DATA+=  runningb.jpg starkit.jpg starkitb.jpg tw.jpg twb.jpg
DATA+=  unixuser.jpg unixuserb.jpg wc-10.jpg wc-10b.jpg wc-11.jpg wc-11b.jpg 
DATA+=  wc-200.jpg wc-200b.jpg wc-205.jpg wc-205b.jpg wc-21.jpg wc-215.jpg 
DATA+=  wc-215b.jpg wc-216.jpg wc-216b.jpg wc-216jp.jpg wc-216jpb.jpg 
DATA+=  wc-217.jpg wc-217b.jpg wc-21b.jpg wc-221.jpg wc-221b.jpg 
DATA+=  wc-222.jpg wc-222b.jpg wc-22snap.jpg wc-22snapb.jpg 
DATA+=  wc-44lite2.jpg wc-44lite2b.jpg wc-blun.jpg wc-blunb.jpg 
DATA+=  wc-30snab.jpg wc-30sna.jpg newsletb.jpg newslett.jpg
DATA+=  newslet2b.jpg newslet2.jpg
DATA+=  banner1.gif banner2.gif banner3.gif banner4.gif
DATA+=  lynx.gif
DATA+=  smart-reseller-small.jpg smart-reseller.jpg
DATA+=	bsdm.jpg
DATA+=	bsdmb.jpg
DATA+=	fhp_mini.jpg
DATA+=  mall_title_tiny.gif
DATA+=  mall_title_medium.gif
DATA+=  plueschtier-tiny.jpg
DATA+=	instman.jpg instmanb.jpg sam.jpg samb.jpg urm.jpg urmb.jpg
DATA+=	releases.jpg bug.jpg doc.jpg news.jpg power.jpg
DATA+=	gourchin3.gif
DATA+=	darbylogo.gif
DATA+=	bsdmagazine.jpg
DATA+=	aboutf.jpg aboutfb.jpg

.include "../web.mk"
