# $FreeBSD: www/ru/news/Makefile,v 1.1 2000/03/12 22:24:13 phantom Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists("../Makefile.conf")
.include "../Makefile.conf"
.endif

# quick news letter
DOCS=	qnewsletter.sgml
DOCS+=	qnewsletter-1-1.sgml
DOCS+=	qnewsletter-1-2.sgml
DOCS+=	qnewsletter-1-3.sgml
DOCS+=	qnewsletter-1-4.sgml
DOCS+=	qnewsletter-1-5.sgml
DOCS+=	qnewsletter-1-6.sgml
DOCS+=	qnewsletter-1-7.sgml
DOCS+=	qnewsletter-2-1.sgml
DOCS+=	qnewsletter-2-2.sgml

DOCS+= press.sgml
DOCS+= newsflash.sgml
DOCS+= news.sgml
DOCS+= webchanges.sgml

# press releases
DOCS+= pressreleases.sgml
DOCS+= press-rel-1.sgml
DOCS+= press-rel-2.sgml
DOCS+= press-rel-3.sgml

# The yearly State of the Union address
#DOCS+= sou1999.sgml

INDEXLINK= news.html

.include "../web.mk"
