=== FreeBSD on EC2

Links: +
link:https://www.freebsd.org/releases/15.0R/ec2-ami-ids/release/[FreeBSD 15.0-RELEASE AMIs] URL: link:https://www.freebsd.org/releases/15.0R/ec2-ami-ids/release/[]

Contact: Colin Percival <cperciva@FreeBSD.org>

FreeBSD is available on both amd64 (Intel and AMD) and arm64 (Graviton) EC2 instances.

A list of EC2 AMIs for FreeBSD 15.0-RELEASE has been added to the FreeBSD website.
This page includes javascript to allow the list to be filtered by region, architecture, flavour, and root filesystem.

A process is now in place for publishing updated EC2 AMIs in response to security advisories; we now have FreeBSD 15.0-RELEASE-p5 AMIs and anticipate typically having updated AMIs in place within a few hours of advisories being published.
The AMI IDs for these are published via the SSM Parameter Store and the FreeBSD website.
At present there is no mechanism in place for building updated AMIs for 14.x releases.

An issue causing the man:ena[4] driver's I/O interrupts to all land on CPU 0 on arm64 systems has been fixed in main.
The fix should be present in 15.1-RELEASE (June) and 14.5-RELEASE (September).

An issue causing the man:ena[4] driver to not attach when FreeBSD boots on r8i.96xlarge instances has been fixed in main.
The fix is expected to be present in 15.1-RELEASE (June) and 14.5-RELEASE (September).

Sponsor: Amazon +
Sponsor: https://www.patreon.com/cperciva
