=== Make openjdk25 the default JAVA_VERSION

Link:
link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=293559[Issue 293559] URL: link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=293559[]

Contact: Ronald Klop <ronald@FreeBSD.org>

Java is an important environment for running some application on FreeBSD.
The OpenJDK ports are actively maintained and up to date.
Since October 2025 OpenJDK 25 LTS is available in the ports tree.

Building on the groundwork of moving ports to OpenJDK 21 the switch of JAVA_DEFAULT to 25 is a much smaller step.
Most Java ports compile and run without changes.
Only a handful of ports need some fixes, which is currently in progress.

The work is being tracked in PR 293559.

I think it is reasonable to have the ports in shape for the JAVA_VERSION=25 setting in the second quarter of 2026.

Plan:

* An exp-run is requested
* Check the last ports and create a PR or commit
* Commit the PRs that are timing out on maintainer feedback
* Maybe ask for another exp-run
* If done, increase JAVA_VERSION
