=== FreeBSD Release Engineering Team

Links: +
link:https://www.freebsd.org/releases/14.4R/announce/[FreeBSD 14.4-RELEASE announcement] URL: link:https://www.freebsd.org/releases/14.4R/announce/[] +
link:https://www.freebsd.org/releases/15.1R/schedule/[FreeBSD 15.1-RELEASE schedule] URL: link:https://www.freebsd.org/releases/15.1R/schedule/[] +
link:https://download.freebsd.org/releases/ISO-IMAGES/[FreeBSD releases] URL: link:https://download.freebsd.org/releases/ISO-IMAGES/[] +
link:https://download.freebsd.org/snapshots/ISO-IMAGES/[FreeBSD development snapshots] URL: link:https://download.freebsd.org/snapshots/ISO-IMAGES/[]

Contact: FreeBSD Release Engineering Team <re@FreeBSD.org>

The FreeBSD Release Engineering Team is responsible for setting and publishing release schedules for official project releases of FreeBSD, announcing code freezes and maintaining the respective branches, among other things.

The Team managed 14.4-RELEASE, leading to the official RELEASE build and announcement in March.
Planning has started for the upcoming 15.1-RELEASE, which is due to arrive in June.

The Team gained four new members, mailto:carlavilla@FreeBSD.org[Sergio Carlavilla Delgado], mailto:leres@FreeBSD.org[Craig Leres], mailto:vladlen@FreeBSD.org[Vladlen Popolitov], and mailto:ziaee@FreeBSD.org[Alexander Ziaee], and two members have departed: mailto:jfree@FreeBSD.org[Jake Freeland] and mailto:mmokhi@FreeBSD.org[Mahdi Mokhtari].
We thank them for their contributions.

The Release Engineering Team continued providing weekly development snapshot builds for the *main*, *stable/15*, *stable/14*, and *stable/13* branches.
Note that the weekly snapshot builds for *stable/13* will end when that branch reaches its End-of-Life at the end of April.
