---
title: "FreeBSD Summer Projects"
sidenav: developers
--- 

= FreeBSD Summer Projects

The FreeBSD Project is looking forward to participating as a mentoring organization in https://summerofcode.withgoogle.com/[Google Summer of Code] 2020. This program offers students a stipend of https://developers.google.com/open-source/gsoc/help/student-stipends[up to $6,600 USD] to contribute to an open source project over the summer break. We have had over 200 successful students working on FreeBSD as part of this program since 2005.

This page and the https://wiki.freebsd.org/SummerOfCodeIdeas[ideas lists] will be updated throughout the application period to include new information, such as project ideas, proposal information, and potential mentor contact information. If you don't see an idea that interests you, visit again in a couple of days! Additionally, we welcome proposals unrelated to the ideas listed here.

* <<benefits,Benefits of Participating>>
* <<students,Past Student Projects>>
* <<ideas,Example Proposal Ideas>>
* <<mentors,Possible Mentors>>
* <<proposals,Proposal Guidelines>>
* <<infrastructure,Infrastructure Provided to Students>>
* <<faq,Frequently Asked Questions>>

[[benefits]]
== Benefit of Participating

Google Summer of Code is an exciting opportunity for students to "intern" with an open source project for a summer. The FreeBSD Project, as one of the most successful and oldest open source projects, is an excellent place to do this internship. Founded in 1993, the project now consists of several hundred "committers" and tens of thousands of contributors. FreeBSD is the foundation for many commercial products, including Apple's Mac OS X, NetApp's OnTap/GX, Juniper's JunOS, as well countless other products, and is widely used in the Internet Service Provider and corporate IT worlds. Many of these sponsors participate daily in the FreeBSD community, and students have the opportunity to develop software ideas in an exciting environment with many real world applications, and under the mentorship of experienced developers.

After the summer ends, students can be sponsored by Google or the FreeBSD Foundation to attend operating systems and open source conferences to present on their work, and a significant number go on to become FreeBSD developers. It's also a great job networking opportunity!

[[ideas]]
== Example Proposal Ideas

The FreeBSD Project maintains a https://wiki.FreeBSD.org/SummerOfCodeIdeas[list of possible ideas] on our wiki. All projects listed are believed to be sized for a useful summer hacking, and have technical contacts who can help answer questions as you write your proposal. We also maintain a more generic https://wiki.FreeBSD.org/IdeasPage[Ideas Page]. These projects are less suitable as Summer of Code projects as they may be scoped larger or smaller than a summer, or might not have such a clear mentor - we suggest e-mailing our soc-admins alias for help if you do decide to propose one of them. These pages exist to help provide inspiration. Students are also welcome, and are indeed encouraged to propose your own ideas, and if the proposal is strong, we'll try to match you with a mentor!

For additional ideas about upcoming development projects in FreeBSD, take a look at recent link:../status/[Developer Status Reports].

[[students]]
== Past Student Projects

For a complete list of student projects from previous years, visit:

* https://wiki.FreeBSD.org/SummerOfCode2019Projects[Summer of Code 2019 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2018Projects[Summer of Code 2018 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2017Projects[Summer of Code 2017 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2016Projects[Summer of Code 2016 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2015Projects[Summer of Code 2015 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2014Projects[Summer of Code 2014 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2013Projects[Summer of Code 2013 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2012Projects[Summer of Code 2012 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2011Projects[Summer of Code 2011 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2010Projects[Summer of Code 2010 FreeBSD Projects Wiki]
* https://wiki.FreeBSD.org/SummerOfCode2009Projects[Summer of Code 2009 FreeBSD Projects Wiki]
* link:../summerofcode-2008/[Summer of Code 2008 FreeBSD Projects Summary]
* link:../summerofcode-2007/[Summer of Code 2007 FreeBSD Projects Summary]
* link:../summerofcode-2006/[Summer of Code 2006 FreeBSD Projects Summary]
* link:../summerofcode-2005/[Summer of Code 2005 FreeBSD Projects Summary]

See also our wiki pages for student projects [https://wiki.FreeBSD.org/SummerOfCode2008[2008], https://wiki.FreeBSD.org/SummerOfCode2007[2007], https://wiki.FreeBSD.org/SummerOfCode2006[2006], and https://wiki.FreeBSD.org/SummerOfCode2005[2005]].

[[proposals]]
== Proposal Guidelines

Students are responsible for writing a proposal and submitting it to Google before the application deadline. The following outline was adapted from the Perl Foundation. The objective of the proposal is to identify what is to be done, explain why this needs to be done, and convince us that:

* You are qualified to do this project. This means both having the necessary background and demonstrating a general understanding of the problem.
* You have the resources (especially time!) needed to complete the project within the working period of the Summer of Code.

A strong proposal will include (at least):

=== General Information

* *Name*
* *Email*
* *Phone*
* *IM/IRC*
* *Availability*
+
How many hours per week will you spend working on this? How many on other things? What other obligations (work, school, vacation, weddings, etc.) do you have this summer? Be as specific as possible: when will the project begin and end? You should be ready to produce a day by day schedule before the program starts.)
+
*Please note*: participating in Google Summer of Code is a significant time commitment, and you should not apply if you already have another full-time job planned for the summer.
* *Biography*
+
Who are you? What skills do you bring to this project? What is your past involvement with The FreeBSD Project? (Past involvement is not required, but ideally you will have at least installed FreeBSD and perhaps fixed a bug or two) If your project includes programming in a particular language, such as C, or in a specific environment, such as the kernel or an embedded platform, what experience do you have working in that area? Are you familiar with or a user of revision control systems? Have you completed courses that will be relevant to your project idea? What do you think you will need to learn to complete this project?
* *Possible Mentor*
+
Optional, but highly recommended. Do not put a name here if you have not contacted them.

=== Project Information

* *Project Title*
+
In forty characters or less, what you propose to do.
* *Project Description*
+
A few paragraphs describing your project. Direct copies from the ideas page will be rejected - proposals should reveal that you have done some research into the problem and its solutions. Include both what you will be doing and why it is a good thing for The FreeBSD Project.
* *Deliverables*
+
A list quantifiable results and related code milestones. We suggest at least two milestones before the mid-term evaluations and two after. Where appropriate, this schedule should include multiple committable or releasable points so people can benefit from and/or test your work as early as possible.
* *Test Plan*
+
What parts of your code need testing and how do you plan to test them? This might include both functionality and performance tests.
* *Project Schedule*
+
How long will the project take? When can you begin work?

[[mentors]]
== Mentors

A number of FreeBSD committers are willing to mentor students. A good place to start is the 'Technical contacts' listed with the example projects on the https://wiki.FreeBSD.org/SummerOfCodeIdeas[ideas page].

[[infrastructure]]
== Infrastructure Provided to Students

We expect project work to be done in GitHub repositories in order to facilitate student collaboration, provide public access and archiving for the on-going student projects, and to help mentors and the community monitor on-going work. Students will also be asked to maintain wiki pages on their on-going projects. In the past, e-mail, IRC, and instant messaging have proven popular among students and mentors, and students participating in the FreeBSD summer program are encouraged to use these and other electronic communication mechanisms to become active in the community.

[[faq]]
== Frequently Asked Questions

* *When are proposals due, and how do I submit mine?*
+
At the time of writing, Google has announced the following dates of interest relating to the application process:
+
** *12 March* - Student application period opens.
** *27 March 18:00 UTC* - Student application period closes.
** *23 April* - Accepted students announced, students start creating their work plans. Community bonding period starts.
** *14 May* - Coding starts.
** *6 August* - Suggested end of coding.
+
Note that these dates may change, and the Google FAQ timeline is the authoritative source of detailed schedule information:
** https://summerofcode.withgoogle.com/how-it-works/[GSoC Timeline]
+
All students must register with, and submit applications via, the Google Summer of Code home page:
** https://summerofcode.withgoogle.com/[Google Summer of Code Home Page]
* *What advice do you have for a student who might want to submit a proposal?*
+
Experience suggests that the strongest proposals come from students who contact FreeBSD developers and potential mentors well in advance of submitting their proposal, seek feedback on their proposal ideas, and write proposals that reflect time spent exploring and understanding the problem area to be addressed. Even if the FreeBSD developer(s) you contact aren't the eventual mentor of the project, their feedback can be invaluable.
* *Can I submit multiple project proposals to the FreeBSD Project?*
+
Yes, but do make sure you invest adequate time in each proposal. We are not able to accept more than one project per student, so you may do better spending more time on one or two detailed proposals than by submitting lots of less-detailed ones.
* *Will the FreeBSD Project accept more than one student for the same idea?*
+
In general, we will accept only one student for any given proposal idea, as most proposal ideas in our ideas list are sized with a single student summer project in mind. This is a good reason to consider coming up with your own idea, or at least, making sure that your proposal for one of our project ideas reflects your unique contribution and viewpoint. If you plan to submit multiple proposals, you might consider doing one with an idea from the list, and another with an original idea.
* *What if my proposal is not selected in the application process? Can I still participate?*
+
We always have more good applications than student places, but that doesn't mean you can't do the project anyway. The FreeBSD Project always welcomes new volunteers to work on projects, and is generally happy to provide mentoring and support for students whose proposals could not be selected in order to allow them to work on their project anyway. You will need to work with the FreeBSD Project GSoC administrators to identify a possible mentor. However, Google will not fund that participation.
* *What projects were completed successfully by students in previous summers?*
+
Please see the https://wiki.FreeBSD.org/SummerOfCode2018Projects[2018 FreeBSD Summer of Code page], as well as older project pages from https://wiki.FreeBSD.org/SummerOfCode2017Projects[2017], https://wiki.FreeBSD.org/SummerOfCode2016Projects[2016], https://wiki.FreeBSD.org/SummerOfCode2015Projects[2015], https://wiki.FreeBSD.org/SummerOfCode2014Projects[2014], https://wiki.FreeBSD.org/SummerOfCode2013Projects[2013], https://wiki.FreeBSD.org/SummerOfCode2012Projects[2012], https://wiki.FreeBSD.org/SummerOfCode2011Projects[2011], https://wiki.FreeBSD.org/SummerOfCode2010Projects[2010], https://wiki.FreeBSD.org/SummerOfCode2009Projects[2009], link:summerofcode-2008.html[2008], link:summerofcode-2007.html[2007], link:summerofcode-2006.html[2006], and link:summerofcode-2005.html[2005] for a list of the completed projects from previous years.
* *How can I learn more about FreeBSD?*
+
The link://www.FreeBSD.org/[FreeBSD Project Home Page] is the best way to learn more about the project - from there you can reach the FreeBSD Handbook, FreeBSD Developer's Handbook, project mailing list archives, regular project status reports, and more. If you have questions about specific project ideas, e-mail the technical contacts for those ideas. If you have general GSoC questions relating to FreeBSD, such as if you are unable to reach a project technical contact, need help finding documentation, or want to know who might be a good person to talk to about your idea, send them to soc-admins@FreeBSD.org.
* *Is there an IRC channel I can join to talk about proposal ideas or get help finding out more?*
+
You can join #freebsd-soc on the efnet IRC network to chat with FreeBSD developers interested in mentoring student proposals and projects, past FreeBSD/GSoC students, and other students applying to FreeBSD/GSoC this year.
