# $Id: Makefile,v 1.6 1998-08-09 16:22:16 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.4

DOCS=  current.sgml 
DOCS+= doc-set.sgml
DOCS+= sgml.sgml
DOCS+= submitting.sgml
DOCS+= who.sgml 
DOCS+= translations.sgml
DOCS+= docproj.sgml

INDEXLINK= docproj.html

.include "../../web.mk"
