# $Id: Makefile,v 1.2 1998-07-24 05:46:07 hanai Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

.if exists(Makefile.conf)
.include "Makefile.conf"
.endif

DOCS=	doc-set.sgml submitting.sgml who.sgml translations.sgml
#DOCS+=	current.sgml sgml.sgml 

.include "../../web.mk"
