.\" $FreeBSD$
.TH GRDC 6
.SH 名称
grdc \- 立派なデジタル時計 (curses)
.SH 書式
.B grdc
[-s] [
.I n
]
.SH 解説
.I grdc
は curses 互換な VDU 画面に反転表示された空白を使ってデジタル時計を
表示します。 省略可能な数値引き数
.I n
を指定すると、
.I n
秒後に止まります (デフォルトでは止まりません)。省略可能な
.B -s
フラグを指定すると数字が変わるときにスクロールするようになります。
この curses モードの実装では、遅れないようにスクロールするのは難しいです。
.SH 作者
Amos Shapirが作成し、 John Lupien が curses 用に修正しました。
