.\" %FreeBSD: src/games/grdc/grdc.6,v 1.6 2003/05/16 21:27:23 ru Exp %
.\"
.\" $FreeBSD$
.Dd September 25, 2001
.Dt GRDC 6
.Os
.Sh 名称
.Nm grdc
.Nd 立派なデジタル時計 (curses)
.Sh 書式
.Nm
.Op Fl st
.Op Ar n
.Sh 解説
.Nm
は curses 互換な VDU 画面に反転表示された空白を使ってデジタル時計を
表示します。 省略可能な数値引数
.Ar n
を指定すると、
.Ar n
秒後に止まります (デフォルトでは止まりません)。省略可能な
.Fl s
フラグを指定すると数字が変わるときにスクロールするようになります。
省略可能な
.Fl t
フラグを指定すると 12 時間書式で時刻を表示するようになります。
この curses モードの実装では、遅れないようにスクロールするのは難しいです。
.Sh 作者
.An -nosplit
.An Amos Shapir
が作成し、
.An John Lupien
が curses 用に修正しました。
