# $FreeBSD$

MAN6 =	banner.6\
	caesar.6\
	factor.6\
	fortune.6\
	grdc.6\
	intro.6\
	morse.6\
	number.6\
	pom.6\
	random.6\

MLINKS+=bcd.6 ppt.6 
MLINKS+=factor.6 primes.6
MLINKS+=caesar.6 rot13.6

.include "bsd.prog.mk"
