MAN6 =	adventure.6\
	arithmetic.6\
	atc.6\
	backgammon.6\
	banner.6\
	battlestar.6\
	bcd.6\
	bs.6\
	caesar.6\
	canfield.6\
	cribbage.6\
	factor.6\
	fish.6\
	fortune.6\
	grdc.6\
	hack.6\
	hangman.6\
	intro.6\
	larn.6\
	mille.6\
	morse.6\
	number.6\
	phantasia.6\
	piano.6\
	pig.6\
	pom.6\
	quiz.6\
	rain.6\
	random.6\
	robots.6\
	rogue.6\
	sail.6\
	snake.6\
	trek.6\
	wargames.6\
	worm.6\
	worms.6\
	wump.6

MLINKS=	canfield.6 cfscores.6
MLINKS+=bcd.6 ppt.6 
MLINKS+=factor.6 primes.6
MLINKS+=caesar.6 rot13.6
MLINKS+=snake.6 snscore.6
.include "bsd.prog.mk"
