#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/events/Makefile.inc,v 1.1 2004/02/23 14:37:05 andy Exp $
#
# Original revision: 1.2
#

DOC_PREFIX?=	${.CURDIR}/../../../..
WEBBASE?=	/data/ru/events
