# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/articles/releng-packages/Makefile
# %SRCID%	1.4

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=  article.xml

CSS_SHEET_ADDITIONS= extra.css

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
