# $Id: Makefile,v 1.1 1998-07-30 02:35:20 hanai Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1
 
DOCS=   alpha.sgml

# DOCS+=  current.sgml
# DOCS+=  bootstrapping.sgml
 
.include "../../web.mk"
