# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =  freebsd.sgml
DOCS+=  tools.sgml
DOCS+=  api.sgml
DOCS+=  index.sgml 
DOCS+=  tutorials.sgml
DOCS+=  development.sgml
DOCS+=  resources.sgml 
DOCS+=  vendor.sgml
DOCS+=  documentation.sgml
DOCS+=  servlets.sgml

### Revision checking
REVCHECK= YES

.include "${WEB_PREFIX}/share/mk/web.site.mk"
