---
title: "FreeBSD Quarterly Status Report 4th Quarter 2021"
sidenav: about
---

= Introduction
:doctype: article
:toc: macro
:toclevels: 2
:icons: font
:!sectnums:
:source-highlighter: rouge
:experimental:
:reports-path: content/en/status/report-2021-10-2021-12

This report covers FreeBSD related projects for the period between October and December.  It is the fourth of four planned reports for 2021, and contains 19 entries.  Highlights include faster boot times, more LLDB work, a base OpenSSH update, and more wireless development.

Yours, +
Pau Amma, Daniel Ebdrup, John-Mark Gurney, and Joe Mingrone

'''

toc::[]

'''

[[FreeBSD-Team-Reports]]
== FreeBSD Team Reports

Entries from the various official and semi-official teams, as found in the link:../../administration/[Administration Page].

include::{reports-path}/freebsd-foundation.adoc[]

'''

include::{reports-path}/portmgr.adoc[]

'''

include::{reports-path}/doceng.adoc[]

'''

include::{reports-path}/www.adoc[]

'''

[[projects]]
== Projects

Projects that span multiple categories, from the kernel and userspace to the Ports Collection or external projects.


include::{reports-path}/aslr.adoc[]

'''

include::{reports-path}/boot-performance.adoc[]

'''

include::{reports-path}/lldb.adoc[]

'''

include::{reports-path}/ls1027a.adoc[]

'''

include::{reports-path}/membarrier-rseq.adoc[]

'''

include::{reports-path}/openssh.adoc[]

'''

include::{reports-path}/vdso.adoc[]

'''

[[kernel]]
== Kernel

Updates to kernel subsystems/features, driver support, filesystems, and more.


include::{reports-path}/avx-bug.adoc[]

'''

include::{reports-path}/ena.adoc[]

'''

include::{reports-path}/iwlwifi.adoc[]

'''

include::{reports-path}/ocf-wg.adoc[]

'''


[[ports]]
== Ports

Changes affecting the Ports Collection, whether sweeping changes that touch most of the tree, or individual ports themselves.

include::{reports-path}/kde.adoc[]

'''

include::{reports-path}/office.adoc[]

'''

[[third-Party-Projects]]
== Third-Party Projects

Many projects build upon FreeBSD or incorporate components of FreeBSD into their project.
As these projects may be of interest to the broader FreeBSD community, we sometimes include brief updates submitted by these projects in our quarterly report.
The FreeBSD project makes no representation as to the accuracy or veracity of any claims in these submissions.

include::{reports-path}/hellosystem.adoc[]

'''

include::{reports-path}/pot.adoc[]

'''
