=== helloSystem

Links: +
link:https://hellosystem.github.io/docs/[Documentation] URL: link:https://hellosystem.github.io/[https://hellosystem.github.io/]

Contact: Simon Peter <probono@puredarwin.org> +
Contact: `\#helloSystem` on `irc.libera.chat`, mirrored to link:https://matrix.to/#/%23helloSystem:matrix.org?via=matrix.org[`#helloSystem:matrix.org` on Matrix]

==== What is helloSystem?

helloSystem is FreeBSD preconfigured as a desktop operating system with a focus on simplicity, elegance, and usability.
Its design follows the “Less, but better” philosophy.

==== Q4 2021 Status

* Version 0.7.0 of helloSystem has been published including many contributed features and bugfixes
** helloSystem is now based on FreeBSD 13.0-RELEASE
** Completely reworked Live ISO architecture, resulting in 1/3rd boot time and under 800 MB size (fits a CD-ROM)
** Developer Tools are now a separate download
** Disk Images are increasingly used throughout the system, such as for application distribution and Linuxulator userland deployment
** Many new features and GUI utilities to make the desktop more usable for "mere mortals" without the need for a terminal

Installable Live ISO images and a full changelog are available at https://github.com/helloSystem/ISO/releases/tag/r0.7.0

==== Contributing

link:https://github.com/helloSystem/hello/blob/master/CONTRIBUTING.md[The project appreciates contributions in various areas].
