=== FreeBSD Office Team

Links: +
link:https://wiki.freebsd.org/Office[The FreeBSD Office project] URL: link:https://wiki.freebsd.org/Office[https://wiki.freebsd.org/Office]

Contact: FreeBSD Office team ML <office@FreeBSD.org> +
Contact: Dima Panov <fluffy@FreeBSD.org> +
Contact: Li-Wen Hsu <lwhsu@FreeBSD.org>

The FreeBSD Office team works on a number of office-related software suites and tools such as OpenOffice and LibreOffice.

Work during this quarter was focused on providing the latest stable release of LibreOffice suite and companion apps to all FreeBSD users.

Latest and quarterly ports branches got a new branch (7.2) of the LibreOffice suite and updated to the 7.2.4 release while new preleases
such as 7.2.5.RC2 and 7.3.0.RC1 are cooking in the WIP stage area.

Meanwhile, our link:https://github.org/freebsd/freebsd-ports-libreoffice[WIP repository] got back a working CI instance again, thanks to Li-Wen Hsu.

Also we are still working on the link:https://github.com/fluffykhv/freebsd-ports-boost[Boost WIP repository] to bring the latest Boost library to the ports.

We are looking for people to help with the open tasks:

* The link:https://bugs.freebsd.org/bugzilla/buglist.cgi?bug_status=open&email1=office%40FreeBSD.org&emailassigned_to1=1&emailcc1=1&emailreporter1=1&emailtype1=substring&query_format=advanced&list_id=374316[open bugs list] contains all filed issues which need some attention
* Upstream local patches in ports

Patches, comments and objections are always welcome in the mailing list and bugzilla.
