# FreeBSD list of projects and ideas for volunteers
#
# $FreeBSD$

MAINTAINER=	joel

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	style.css

DOCS=	ideas.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
