---
title: "Unterstützung"
sidenav: support
---

= FUnterstützung

Für FreeBSD gibt es sowohl Hilfestellung durch die FreeBSD-Gemeinde als auch durch kommerzielle Anbieter. Der Abschnitt link:../community/[Community] dieser Internetseiten beschreibt, wie man die Hilfe der FreeBSD-Gemeinde (beispielsweise über eine der link:../community/mailinglists/[Mailinglisten]) in Anspruch nehmen kann.

Benötigen Sie kommerziellen Support, können Sie auf einen der zahlreichen https://www.FreeBSD.org/commercial/[Anbieter] zurückgreifen, die kommerzielle Produkte, Dienste und/oder Beratung für FreeBSD anbieten.

== Problemberichte

Sie haben einen Bug in FreeBSD entdeckt? Oder Ihnen ist ein Fehler innerhalb der Dokumentation aufgefallen? Wurde dieser Fehler noch nicht gemeldet, so teilen Sie uns dies bitte mit.

Um festzustellen, ob ein Fehler bereits gemeldet wurde, können Sie die https://bugs.freebsd.org/search/[Problemberichte-Datenbank] durchsuchen (beispielsweise nach einer bestimmten Kategorie, nach dem für die Behebung des Fehlers Zuständigen, dem Einreicher des Problemberichts oder auch nach einem bestimmten Begriff). Alternativ können Sie sich auch https://bugs.freebsd.org/browse/[alle offenen Problemberichte anzeigen lassen].

Wurde der Fehler noch nicht gemeldet, lesen Sie bitte zuerst unsere link:bugreports[Richtlinien zur Erstellung von Problemberichten] und melden Sie danach den Fehler über unser https://bugs.freebsd.org/submit/[Problembericht-Formular].
