---
title: "Problemberichte"
sidenav: support
---

include::shared/de/urls.adoc[]

= Problemberichte

== Problemberichte-Datenbank

* https://bugs.FreeBSD.org/search/[Die Datenbank durchsuchen]
* https://bugs.FreeBSD.org/submit/[Ein Problem melden]

Bei einem FreeBSD-Problembericht (_PR_) handelt es sich nicht zwangsweise um ein Problem von FreeBSD selbst. Es kann sich auch um einen Fehler in der Dokumentation (etwa einen Tippfehler) oder um eine 'Wunschliste' mit Funktionen handeln, die der Einsender gerne in FreeBSD sehen würde.

Neue Problemberichte erhalten den Status _open_ (offen) und werden geschlossen, wenn das zugrundeliegende Problem gelöst wurde. Jeder PR erhält eine eindeutige Nummer (ID) zugewiesen. Daher enthalten viele Änderungen an FreeBSD die ID des Problemberichtes, der die Änderung erforderlich machte.

== Wie man einen Problembericht einreicht

Problemberichte werden über ein https://bugs.FreeBSD.org/submit/[Internetformular] eingereicht und an das Entwicklerteam geschickt. Bevor Sie einen Bericht einreichen können, müssen Sie sich registrieren. Beachten Sie dabei, dass Nachrichten an die Mailingliste _nicht_ als offizielle Problemberichte erfasst werden und daher auch verloren gehen können!

Bevor Sie einen Problembericht erstellen, sollten Sie den Artikel link:{problem-reports}[Writing FreeBSD Problem Reports] lesen. Dieser Artikel beschreibt, wann Sie einen Bericht erstellen sollten, welche Angaben benötigt werden und wie Sie Ihren Bericht am Besten an das FreeBSD Project senden. Nützliche Hintergrundinformationen enthält der Artikel link:{pr-guidelines}[Problem Report Handling Guidelines].

FreeBSD Problemberichte werden über http://www.bugzilla.org/[Bugzilla] verwaltet.
