# $Id: Makefile,v 1.8 1997-07-26 01:30:13 nsj Exp $

DOCS?=	index.sgml snapshots.sgml

SUBDIR=	1.1 1.1.5 2.0 2.0.5A 2.0.5R 2.0A 2.1R 2.1.5R 2.1.6R 2.1.7R 2.2R
SUBDIR+=	2.2.1R 2.2.2R

.if defined $(NEW_BUILD)
SUBDIR=
.endif

.include "../web.mk"
