# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq.sgml
DOCS+=	faq2.sgml
DOCS+=	porting.sgml
DOCS+=	bugging.sgml
DOCS+=  volunteer.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
