# $FreeBSD: www/es/gnome/docs/Makefile,v 1.3 2004/03/05 06:17:10 rushani Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   faq2.sgml
DOCS+=  gnome_porting.sgml
DOCS+=  gnome2_porting.sgml
DOCS+=  porting.sgml
DOCS+=  bugging.sgml
DOCS+=  volunteer.sgml
DOCS+=  knownissues.sgml
DOCS+=  develfaq.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
