# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/docs/Makefile,v 1.3 2000/11/10 17:04:50 phantom Exp $
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	faq.sgml
DOCS+=	howtoports.sgml
DOCS+=	newbies.sgml
DOCS+=	performance.sgml
DOCS+=	tutorials.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
