#
# The FreeBSD Simplified Chinese Project
# Original Revision: 1.1
#
# $FreeBSD: www/zh_CN/layout/css/Makefile,v 1.1.1000.1 2005/12/17 16:27:02 delphij Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   fixed.css fixed_large.css global.css iefixes.css layout.css navigation.css table.css text.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
