---
title: "The 4.4BSD Copyright"
sidenav: about
---

= The 4.4BSD Copyright

訳注: 以下は原文です。

All of the documentation and software included in the 4.4BSD and 4.4BSD-Lite Releases is copyrighted by The Regents of the University of California.

Copyright 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994 The Regents of the University of California. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
. All advertising materials mentioning features or use of this software must display the following acknowledgement:
+
____
This product includes software developed by the University of California, Berkeley and its contributors.
____
. Neither the name of the University nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The Institute of Electrical and Electronics Engineers and the American National Standards Committee X3, on Information Processing Systems have given us permission to reprint portions of their documentation.

In the following statement, the phrase ``this text'' refers to portions of the system documentation.

Portions of this text are reprinted and reproduced in electronic form in the second BSD Networking Software Release, from IEEE Std 1003.1-1988, IEEE Standard Portable Operating System Interface for Computer Environments (POSIX), copyright C 1988 by the Institute of Electrical and Electronics Engineers, Inc. In the event of any discrepancy between these versions and the original IEEE Standard, the original IEEE Standard is the referee document.

In the following statement, the phrase ``This material'' refers to portions of the system documentation.

This material is reproduced with permission from American National Standards Committee X3, on Information Processing Systems. Computer and Business Equipment Manufacturers Association (CBEMA), 311 First St., NW, Suite 500, Washington, DC 20001-2178. The developmental work of Programming Language C was completed by the X3J11 Technical Committee.

The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the Regents of the University of California.

_注意:_ カリフォルニア大学バークレイ校の Berkeley Software Distribution ("BSD") の著作権の原文が更新されました。追加された著作権はftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change にあります。以下に転載します。

____
July 22, 1999

To All Licensees, Distributors of Any Version of BSD:

As you know, certain of the Berkeley Software Distribution ("BSD") source code files require that further distributions of products containing all or portions of the software, acknowledge within their advertising materials that such products contain software developed by UC Berkeley and its contributors.

Specifically, the provision reads:

....
"     * 3. All advertising materials mentioning features or use of this software
      *    must display the following acknowledgement:
      *    This product includes software developed by the University of
      *    California, Berkeley and its contributors."
....

Effective immediately, licensees and distributors are no longer required to include the acknowledgement within advertising materials. Accordingly, the foregoing paragraph of those BSD Unix files containing it is hereby deleted in its entirety.

William Hoskins +
Director, Office of Technology Licensing +
University of California, Berkeley
____

'''''

以下の日本語訳は参考のために添付したものです。 英語版だけが法律的に有効であることに注意してください。

BSD ライセンス参考訳

4.4BSD および 4.4BSD-Lite リリースに含まれる全ての文書と ソフトウェアの著作権は、カリフォルニア大学評議員会 にあるものとする。

Copyright 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994 The Regents of the University of California. All rights reserved.

ソースコード形式であれバイナリ形式であれ、変更の有無に 関わらず、以下の条件を満たす限りにおいて、再配布および使用を許可します:

. ソースコード形式で再配布する場合、上記著作権表示、 本条件書および下記責任限定規定を必ず含めてください。
. バイナリ形式で再配布する場合、上記著作権表示、 本条件書および下記責任限定規定を、配布物とともに提供される文書 および/または 他の資料に必ず含めてください。
. このソフトウェアの機能または利用について触れる全ての広告には、 下記の謝辞を必ず掲載してください。
+
____
この製品にはカリフォルニア大学バークレイ校と、 その寄与者によって開発されたソフトウェアが含まれています。
____
. 書類による事前の明確な許諾を得ずに、カリフォルニア大学 およびその寄与者の名前を、このソフトウェアに由来する製品 の宣伝あるいは推奨に利用してはいけません。

本ソフトウェアは評議員会および寄与者によって、”現状のまま” 提供されるものとします。本ソフトウェアについては、明示黙示を問わず、 商用品として通常そなえるべき品質をそなえているとの保証も、 特定の目的に適合するとの保証を含め、何の保証もなされません。 事由のいかんを問わず、 損害発生の原因いかんを問わず、且つ、 責任の根拠が契約であるか厳格責任であるか (過失その他) 不法行為であるかを問わず、評議員も寄与者も、 仮にそのような損害が発生する可能性を知らされていたとしても、 本ソフトウェアの使用から発生した直接損害、間接損害、偶発的な損害、 特別損害、懲罰的損害または結果損害のいずれに対しても (代替品または サービスの提供; 使用機会、データまたは利益の損失の補償; または、業務の中断に対する補償を含め) 責任をいっさい負いません。

米国電気電子技術者協会 (IEEE) と、情報処理システムのための 米国規格委員会 X3 は、我々が彼らの文書の一部を再版することを 許可してくださいました。

以下の説明で、``このテキスト''とは、上記のシステムに関する 文書の一部のことを指すものとする。

このテキストの一部は、BSD Networking Software Release/2 に おいて、電子形態による再版と複製がおこなわれた。このテキスト の一部は IEEE 標準 1003.1-1988、計算機環境におけるポータブルな オペレーションシステムのインターフェース (POSIX) に関する IEEE 標準に由来するものであり、法人米国電気電子技術者協会が 1988 年に著作権を取得したものである。この再版され複製され たバージョンとオリジナルの IEEE 標準の間に何らかの差異があった 場合、オリジナルの IEEE 標準こそが信頼すべき文書である。

以下の声明で、``この資料''とは、上記のシステムに関する 文書の一部のことを指すものとする。

この資料は情報処理システムのための米国規格委員会 X3 の 許可を得て再版された。委員会の住所は Computer and Business Equipment Manufacturers Association (CBEMA), 311 First St., NW, Suite 500, Washington, DC 20001-2178 である。 プログラミング言語 C の準備作業は X3J11 専門委員会によって 完成された。

このソフトウェアと文書に含まれる意見や結論はそれらの著作者による ものであって、カリフォルニア大学評議員会の 公式な方針を、明示黙示を問わず、あらわしているものと とってはならない。

_注意:_ カリフォルニア大学バークレイ校の Berkeley Software Distribution ("BSD") の著作権の原文が更新されました。追加された著作権は ftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change にあります。以下は 4bsd/README.Impt.License.Change の参考訳です。

____
July 22, 1999

全てのバージョンの BSD ライセンシーおよび配布者へ:

ご存じのように、Berkeley Software Distribution ("BSD") のソースコードファイルの中では、 そのソフトウェアの全てもしくは一部含む製品を再配布するなら、 製品にはカリフォルニア大学バークレイ校と寄与者によって開発されたソフトウェアが含まれているという謝辞を広告に表示することを要求しています。

具体的には、以下の条項です:

....
"     * 3. このソフトウェアの機能または利用について触れる全ての広告には、
      *    下記の謝辞を必ず掲載してください。:
      *    この製品にはカリフォルニア大学バークレイ校と、
      *    その寄与者によって開発されたソフトウェアが含まれています。"
....

即時発効にて、ライセンシーと配布者は、広告に謝辞を含める必要がなくなりました。 従って、前述の節を含んでいる BSD Unix ファイルから、その節は完全に削除されます。

William Hoskins +
Director, Office of Technology Licensing +
University of California, Berkeley
____

link:../[知的財産権のホームに戻る]
