---
title: "登録商標"
sidenav: about
---

= 登録商標

FreeBSD は FreeBSD Foundation の登録商標です。

FreeBSD Logo は FreeBSD Foundation の商標です。

FreeBSD マークの利用に関しては、 https://www.freebsdfoundation.org/[FreeBSD Foundation] の https://www.freebsdfoundation.org/legal/trademark-usage-terms-and-conditions/[Trademark Usage Terms and Conditions] ページをご覧ください。

Adobe, Acrobat, Acrobat Reader および PostScript はアメリカ合衆国およびその他の国における Adobe Systems Incorporated の登録商標または商標です。

AMD, Am486, Am5X86, AMD Athlon, AMD Duron, AMD Opteron, AMD-K6, Athlon, Élan, Opteron および PCnet は Advanced Micro Devices, Inc. の商標です。

Apple, FireWire, Mac, Macintosh, Mac OS, Quicktime および TrueType は Apple Computer, Inc. の商標で、 アメリカ合衆国およびその他の国で登録されています。

CVSup は John D. Polstra の登録商標です。

IBM および PowerPC はアメリカ合衆国およびその他の国における International Business Machines Corporation の商標です。

IEEE, POSIX および 802 は Institute of Electrical and Electronics Engineers, Inc. の登録商標です。

Intel, Celeron, EtherExpress, i386, i486, Itanium, Pentium および Xeon はアメリカ合衆国およびその他の国における Intel Corporation またはその関連会社の商標または登録商標です。

Linux はアメリカ合衆国における Linus Torvalds の登録商標です。

Motif, OSF/1 および UNIX はアメリカ合衆国およびその他の国における The Open Group の登録商標で、 IT DialTone および The Open Group は同じく商標です。

MySQL はアメリカ合衆国、欧州連合およびその他の国における MySQL AB の登録商標です。

Silicon Graphics, SGI および OpenGL はアメリカ合衆国およびその他の国における Silicon Graphics, Inc. の登録商標です。

Sparc, Sparc64, SPARCEngine および UltraSPARC はアメリカ合衆国およびその他の国における SPARC International, Inc. の商標です。SPARC の商標をつけた製品は Sun Microsystems, Inc. が開発したアーキテクチャに基づいています。

Sun, Sun Microsystems, SunOS, Solaris, および Java はアメリカ合衆国およびその他の国における Sun Microsystems, Inc. の商標または登録商標です。

製造者および販売者が製品を区別するのに用いている表示の多くは、商標とされています。 この web サイトに登場する表示のうち FreeBSD Project がその商標を確認しているものには、その表示に続いて '(TM)' または '(R)' 記号がおかれています。
