.\" -*- nroff -*-
.\"
.\" Copyright (c) 1996 Doug Rabson
.\"
.\" All rights reserved.
.\"
.\" This program is free software.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE DEVELOPERS BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" %FreeBSD: src/share/man/man9/vnode.9,v 1.27 2003/10/23 02:22:07 hmp Exp %
.\"
.\" $FreeBSD$
.Dd May 20, 2003
.Os
.Dt VNODE 9
.Sh 名称
.Nm vnode
.Nd ファイルまたはディレクトリの内部表現
.Sh 書式
.In sys/param.h
.In sys/vnode.h
.Sh 解説
vnode は
.Ux
でのファイル活動の中心です。
vnode は
.Vt "struct vnode"
で記述されます。
個々の活動中のファイル、
個々の現在のディレクトリ、個々のマウントされたファイル、
テキストファイル、およびルートのために割当てられた一意的な vnode があります。
.Pp
個々の vnode は 3 つの参照カウント、
.Va v_usecount ,
.Va v_holdcnt
および
.Va v_writecount
を持っています。
最初のものはカーネル内でこの vnode を使用しているクライアントの数です。
このカウントは
.Xr vref 9 ,
.Xr vrele 9
および
.Xr vput 9
によって管理されます。
2 番目のものはカーネル内でこの vnode の再利用を拒否しているクライアントの
数です。
このカウントは
.Xr vhold 9
および
.Xr vdrop 9
によって管理されます。
vnode の
.Va v_usecount
および
.Va v_holdcnt
の両方が 0 に達すると、それからその vnode はフリーリスト上に置かれ、
ことによっては別のファイルシステムで、
別のファイルのために再利用されるかもしれません。
フリーリストへのおよびフリーリストからの移行は、
.Xr getnewvnode 9 ,
.Xr vfree 9
および
.Xr vbusy 9
によって取り扱われます。
3 番目のものはファイルに書込み中のクライアントの数のカウントです。
これは
.Xr open 2
および
.Xr close 2
システムコールによって管理されます。
.Pp
vnode を返すあらゆる呼び出し (例えば
.Xr vget 9 ,
.Xr VOP_LOOKUP 9
など) は vnode の
.Va v_usecount
を 1 ずつ増やします。
呼び出し側が vnode の利用を完了したときには、この参照は
.Xr vrele 9
(または vnode がロックされていれば
.Xr vput 9 )
の呼び出しによって解放されるべきです。
.Pp
その他の共通に使用される vnode 構造体のメンバは、
名前キャッシュでの一貫性を管理するために使用される
.Va v_id
と、その vnode を所有しているファイルシステムを指す
.Va v_mount
と、その vnode が表現するオブジェクトの型を含む
.Va v_type
と、その vnode のファイルシステム特有のデータを保存するために
ファイルシステムによって使用される
.Va v_data
があります。
.Va v_op
フィールドは vnode の機能を実装するファイルシステム内の関数を呼び出すための
.Dv VOP_*
マクロによって使用されます。
.Sh VNODE の型
.Bl -tag -width VSOCK
.It Dv VNON
型なしです。
.It Dv VREG
通常ファイルです。
VM オブジェクトの支持が有るかもしれませんし無いかもしれません。
必ず支持オブジェクトを取得したい場合には、
.Xr vfs_object_create 9
を呼び出します。
.It Dv VDIR
ディレクトリです。
.It Dv VBLK
ブロック型デバイスです。
VM オブジェクトの支持が有るかもしれませんし無いかもしれません。
必ず支持オブジェクトを取得したい場合には、
.Xr vfs_object_create 9
を呼び出します。
.It Dv VCHR
文字型デバイスです。
.It Dv VLNK
シンボリックリンクです。
.It Dv VSOCK
ソケットです。
通知ロックは動作しないでしょう。
.It Dv VFIFO
FIFO (名前付きパイプ) です。
通知ロックは動作しないでしょう。
.It Dv VBAD
古い形式のバッドセクタマップです。
.El
.Sh 実装に関する注
VFIFO は
.Pa /sys/kern/sys_pipe.c
の "struct fileops" を使用します。
VSOCK は
.Pa /sys/kern/sys_socket.c
の "struct fileops" を使用します。
その他の全ては
.Pa /sys/kern/vfs_vnops.c
の "struct fileops" を使用します。
.Pp
VFIFO/VSOCK のコードになぜか "struct fileops" が使用されている理由は、
カーネルへの VFS コードの不完全な統合の文化遺産です。
.Pp
.Xr vnode 9
インタロックを保持している時の
.Fn malloc
または
.Fn free
への全ての呼出しは、VM オブジェクトと vnode のもつれ合いのために、
LOR (ロック順序の逆転) を引き起こします。
.Sh 関連項目
.Xr malloc 9 ,
.Xr VFS 9
.Sh 作者
このマニュアルページは
.An Doug Rabson
が書きました。
