#
# Build the Porters Handbook with just the content from this chapter.
#
# $FreeBSD$
#
# Original revision: r43840
#

CHAPTERS=	pkg-files/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?=	${.CURDIR}/../../../..

.include "../Makefile"
