# $FreeBSD: www/es/releases/Makefile,v 1.8 2001/08/05 16:13:34 jesusr Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml snapshots.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
