# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/dists/Makefile,v 1.2 2000/10/11 16:16:15 phantom Exp $
# Original revision: 1.3

DOCS =	10.sgml
DOCS+=	11.sgml
DOCS+=	12.sgml
DOCS+=	13.sgml
DOCS+=	index.sgml

.include "../../web.mk"
