#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
# Original revision: 1.1
#

CHAPTERS= 	cutting-edge/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
