# $FreeBSD: www/ja/releases/4.1R/Makefile,v 1.2 2000/09/15 07:45:38 hrs Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

LOCALTOP= ../..

DOCS=	announce.sgml
DOCS+=	notes.sgml
DOCS+=	errata.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
