# $FreeBSD: www/en/conspectus/stable/2000/05/Makefile,v 1.1 2000/05/31 20:35:47 nik Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	29.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
