# $FreeBSD: www/es/projects/Makefile,v 1.3 2000/11/29 23:56:59 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	projects.sgml
DOCS+=	newbies.sgml

INDEXLINK= projects.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
