# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.38

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	photos.xml
DOCS+=	internal.xml
DOCS+= 	about.xml
DOCS+= 	machines.xml
DOCS+= 	mirror.xml
DOCS+=	new-account.xml
DOCS+=	statistic.xml
DOCS+= 	developer.xml
DOCS+=	bylaws.xml
DOCS+=  releng.xml
DOCS+=	expire-bits.xml
DOCS+=	core-vote.xml
# DOCS+=	trb-dispute.xml
# DOCS+=	doceng.xml
# DOCS+=	rtp.xml

INDEXLINK=	internal.html

# DATA+=	README.mirror ssh-keys.asc

.include "${DOC_PREFIX}/share/mk/web.site.mk"
