# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/projects/Makefile,v 1.3 2000/11/10 17:04:52 phantom Exp $
# Original revision: 1.7

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	projects.sgml
DOCS+=	mozilla.sgml
DOCS+=	newbies.sgml

INDEXLINK= projects.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
