# $FreeBSD: www/ru/projects/Makefile,v 1.7 2004/01/23 18:20:22 andy Exp $
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/projects/Makefile,v 1.6 2004/01/23 18:19:55 andy Exp $
# Original revision: 1.7

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	projects.sgml
DOCS+=	newbies.sgml
DOCS+=	cvsweb.sgml

INDEXLINK= projects.html

#SUBDIR=	 busdma

.include "${WEB_PREFIX}/share/mk/web.site.mk"
