# $FreeBSD: www/en/releng/Makefile,v 1.2 2002/03/05 15:27:34 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml charter.sgml dst_info.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
