# $FreeBSD: www/en/releng/Makefile,v 1.1 2002/03/04 06:49:52 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml charter.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
