# $FreeBSD: www/en/releng/Makefile,v 1.3 2007/02/26 22:35:28 kensmith Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml charter.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
