# $FreeBSD$
# $FreeBSDde: de-www/docs/Makefile,v 1.1 2005/10/23 14:24:54 jkois Exp $
# basiert auf: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS= books.sgml
DOCS+= man.sgml
DOCS+= webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
