---
title: Глава 7. Приложения для настольного компьютера
part: Часть II. Общие задачи
prev: books/handbook/partii
next: books/handbook/multimedia
---

[[desktop]]
= Приложения для настольного компьютера
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Содержание
:table-caption: Таблица
:figure-caption: Рисунок
:example-caption: Пример
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 7

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/ru/mailing-lists.adoc[]
include::shared/ru/teams.adoc[]
include::shared/ru/urls.adoc[]

toc::[]

[[desktop-synopsis]]
== Краткий обзор

FreeBSD может работать с широким кругом приложений для настольного компьютера (десктопа), таких как браузеры и текстовые процессоры. Большинство из них доступны в качестве пакетов или могут быть автоматически собраны из коллекции портов. Многим новым пользователям хотелось бы видеть эти приложения на своем компьютере. В этой главе показано как без усилий установить некоторые популярные приложения для настольного компьютера из пакетов или из коллекции портов.

Обратите внимание, что при установке программ из портов они компилируются из исходных текстов. Это может занять очень много времени, в зависимости от того, что вы собираете, и от скорости процессора вашего компьютера (компьютеров). Большинство программ, имеющихся в коллекции портов, могут быть установлены из прекомпилированных пакетов, если сборка из исходных текстов занимает недопустимо много времени.

Поскольку FreeBSD обеспечивает двоичную совместимость с Linux, многие приложения, первоначально разработанные для Linux, доступны и на вашем компьютере. Настоятельно рекомендуется прочитать crossref:linuxemu[linuxemu, Двоичная совместимость с Linux] перед установкой любого из приложений Linux. Названия многих портов, использующих двоичную совместимость с Linux, начинаются с "linux-". Помните это при поиске отдельного порта, например с помощью man:whereis[1]. Далее в статье подразумевается, что вы включили бинарную совместимость с Linux перед установкой какого-либо приложения Linux.

Вот несколько категорий, о которых пойдет речь в этой главе:

* Браузеры (такие как Mozilla, Opera, Firefox, Konqueror)
* Бизнес приложения (такие как KOffice, AbiWord, GIMP, OpenOffice.org)
* Программы просмотра документов (такие как Acrobat Reader(R), gv, Xpdf, GQview)
* Финансовые программы (такие как GnuCash, Gnumeric, Abacus)

Перед прочтением этой главы вам потребуется:

* Узнать, как устанавливать дополнительные программы сторонних производителей (crossref:ports[ports, Установка приложений. порты и пакеты]).
* Узнать, как устанавливать программы Linux (crossref:linuxemu[linuxemu, Двоичная совместимость с Linux]).

Чтобы получить дополнительную информацию о настройке мультимедиа среды, прочтите crossref:multimedia[multimedia, Мультимедиа]. Если вам нужна электронная почта, обратитесь к crossref:mail[mail, Электронная почта].

[[desktop-browsers]]
== Браузеры

FreeBSD поставляется без предустановленного браузера. Вместо этого, в категории http://www.FreeBSD.org/ru/ports/[www] коллекции портов содержится множество готовых к установке браузеров. Если у вас нет времени компилировать все (в некоторых случаях это может занять очень много времени), многие из них доступны в виде пакетов.

В KDE и GNOME уже есть HTML браузеры. Обратитесь к crossref:x11[x11-wm,Графические оболочки] за подробной информацией об установке этих полноценных десктопов.

Если вы ищете облегченный браузер, попробуйте package:www/dillo[], package:www/links[], или package:www/w3m[] из коллекции портов.

Этот раздел рассказывает о следующих приложениях:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Название приложения
| Потребность в ресурсах
| Установка из портов
| Основные зависимости

|Mozilla
|большая
|тяжелая
|Gtk+

|Opera
|малая
|легкая
|Доступны версии для FreeBSD и Linux. Для Linux версии необходимо наличие Linux Binary Compatibility и linux-openmotif

|Firefox
|средняя
|тяжелая
|Gtk+

|Konqueror
|средняя
|тяжелая
|Библиотеки KDE
|===

=== Mozilla

Mozilla это наиболее современный и стабильный браузер; он полностью портирован на FreeBSD. Его достоинство в высокой совместимости со стандартами HTML. В нем есть почтовая и новостная программы. В нем даже найдется редактор HTML, если вам потребуется самостоятельно написать несколько веб-страничек. Пользователи man:getenv[3] найдут общие черты с Communicator, поскольку оба браузера имеют одну основу.

На медленных компьютерах с частотой CPU меньше 233MHz или с памятью меньше 64MB, Mozilla требует слишком много ресурсов, чтобы быть удобной в использовании. Вместо нее вы можете обратить внимание на браузер Opera, описанный ниже в этой главе.

Если вы не можете или не хотите компилировать Mozilla по какой-то причине, команда FreeBSD GNOME уже сделала это для вас. Просто установите пакет из сети с помощью:

[source,bash]
....
# pkg_add -r mozilla
....

Если пакет недоступен, но у вас достаточно времени и места на диске, вы можете скачать исходные тексты для Mozilla, скомпилировать их и установить в вашу систему. Это делается так:

[source,bash]
....
# cd /usr/ports/www/mozilla
# make install clean
....

Порт Mozilla проверяет правильность установки путем запуска регистрации chrome с привилегиями пользователя `root`. Если вы хотите загрузить некоторые дополнения, например курсоры мыши, потребуется запустить Mozilla под `root` для их правильной установки.

После завершения установки Mozilla, больше не требуется работать под `root`. Вы можете запустить Mozilla в качестве браузера, набрав:

[source,bash]
....
% mozilla
....

Вы можете также запустить непосредственно программу чтения почты и новостей, как показано ниже:

[source,bash]
....
% mozilla -mail
....

[[moz-java-plugin]]
=== Mozilla и Java(TM)

Установка Mozilla проста, но к сожалению, установка Mozilla с поддержкой дополнений, таких как Java(TM) и Macromedia(R) Flash(TM) отнимает и время и место на диске.

Первое, что нужно сделать - загрузить файлы, которые будут использоваться с Mozilla. Зайдите с помощью имеющегося веб браузера на http://www.sun.com/software/java2/download.html[http://www.sun.com/software/java2/download.html] и создайте учетную запись на этом веб-сайте. Сохраните имя пользователя и пароль, они могут понадобиться в будущем. Загрузите копию файлов [.filename]#jdk-1_5_0-bin-scsl.zip# (JDK 5.0 SCSL Binaries) и [.filename]#jdk-1_5_0-src-scsl.zip# (JDK 5.0 SCSL Source) и поместите их в каталог [.filename]#/usr/ports/distfiles#, поскольку порт не может загрузить их автоматически в связи с лицензионными ограничениями. Загрузите с этого же сайта "java environment", http://javashoplm.sun.com/ECom/docs/Welcome.jsp?StoreId=22&PartDetailId=j2sdk-1.4.2_08-oth-JPR&SiteId=JSC&TransactionId=noreg[http://javashoplm.sun.com/ECom/docs/Welcome.jsp?StoreId=22&PartDetailId=j2sdk-1.4.2_08-oth-JPR&SiteId=JSC&TransactionId=noreg], файл [.filename]#j2sdk-1_4_2_08-linux-i586.bin#. Как и предыдущий, этот файл должен находиться в каталоге [.filename]#/usr/ports/distfiles/#. Загрузите копию "java patchkit" с http://www.eyesbeyond.com/freebsddom/java/jdk15.html[http://www.eyesbeyond.com/freebsddom/java/jdk15.html] и поместите ее в [.filename]#/usr/ports/distfiles/#. Наконец, установите порт package:java/jdk15[] при помощи стандартной команды `make install clean`.

Запустите Mozilla и выберите пункт [.guimenuitem]#About Plug-ins# в меню menu:Help[]. В списке установленных плагинов должен присутствовать плагин Java(TM).

[[moz-flash-plugin]]
=== Mozilla и Macromedia(R) Flash(TM) plugin

Плагина Macromedia(R) Flash(TM) для FreeBSD не существует. Тем не менее, есть решение (обертка, wrapper) для запуска плагина для Linux. Это решение также поддерживает плагины для Adobe(R) Acrobat(R), RealPlayer и других.

Установите порт package:www/linuxpluginwrapper[]. Он требует для работы достаточно большого порта package:emulators/linux_base[]. Следуя инструкциям, исправьте файл [.filename]#/etc/libmap.conf#! Примеры конфигураций вы можете найти в каталоге [.filename]#/usr/local/shared/examples/linuxpluginwrapper/#.

Установите порт package:www/mozilla[], если Mozilla еще не установлена.

Теперь просто запустите Mozilla:

[source,bash]
....
% mozilla &
....

И войдите в пункт [.guimenuitem]#About Plug-ins# меню menu:Help[]. Должен появиться список со всеми доступными плагинами.

[NOTE]
====
Плагин linuxpluginwrapper работает только на архитектуре i386(TM).
====

=== Opera

Opera это очень быстрый, полноценный и совместимый со стандартами браузер. Он также идет в комплекте с почтовой и новостной программами, клиентом IRC, модулем чтения RSS/Atom и другими. Несмотря на все это, браузер Opera относительно легок и быстр. Он поставляется в двух вариантах: "родная" для FreeBSD версия и версия, запускаемая в режиме эмуляции Linux.

Для работы в сети с помощью FreeBSD версии Opera установите пакет:

[source,bash]
....
# pkg_add -r opera
....

На некоторых серверах FTP нет всех пакетов, но те же результаты можно получить с помощью коллекции портов, набрав:

[source,bash]
....
# cd /usr/ports/www/opera
# make install clean
....

Для установки Linux версии Opera, замените `opera` на `linux-opera` в примере выше. Версия для Linux полезна в ситуации, когда требуются плагины, доступные только для Linux, такие как Adobe Acrobat Reader(R). Во всех других отношениях версии для FreeBSD и Linux являются функционально идентичными.

=== Firefox

Firefox это браузер следующего поколения, основанный на коде Mozilla. Mozilla это полный набор приложений, таких как браузер, почтовый клиент, чат клиент и многое другое. Firefox это всего лишь браузер, что делает его меньше и быстрее.

Установите пакет, выполнив:

[source,bash]
....
# pkg_add -r firefox
....

Вы можете также использовать коллекцию портов, если предпочитаете сборку из исходных текстов:

[source,bash]
....
# cd /usr/ports/www/firefox
# make install clean
....

=== Konqueror

Konqueror это часть KDE, но может быть использован и отдельно от KDE, путем установки package:x11/kdebase3[]. Konqueror это гораздо больше чем просто браузер, это также менеджер файлов и программа просмотра мультимедиа.

Konqueror поставляется с набором плагинов, доступных из package:misc/konq-plugins[].

Konqueror поддерживает также Flash(TM), документация How To для него доступна по адресу http://freebsd.kde.org/howto.php[http://freebsd.kde.org/howto.php].

[[desktop-productivity]]
== Бизнес приложения

В начале работы новые пользователи зачастую стремятся найти хороший офисный пакет или удобный текстовый процессор. Хотя некоторые crossref:x11[x11-wm,десктопы], такие как KDE, поставляются с готовым офисным пакетом, приложения по умолчанию не существует. В FreeBSD есть все необходимое, кроме графической среды.

Этот раздел описывает следующие приложения:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Название приложения
| Потребность в ресурсах
| Установка из портов
| Основные зависимости

|KOffice
|малая
|тяжелая
|KDE

|AbiWord
|малая
|легкая
|Gtk+ или GNOME

|The Gimp
|малая
|тяжелая
|Gtk+

|OpenOffice.org
|большая
|очень тяжелая
|JDK(TM) 1.4, Mozilla
|===

=== KOffice

Сообщество KDE предоставляет графическую среду с офисным пакетом, который может быть использован вне KDE. Он включает четыре стандартных компонента, встречающиеся и в других офисных пакетах. Текстовый процессор KWord, программа электронных таблиц KSpread, KPresenter для создания презентаций и программа векторной графики Kontour.

Перед установкой последней версии KOffice, убедитесь в наличии свежей версии KDE.

Для установки KOffice из пакета, выполните следующую команду:

[source,bash]
....
# pkg_add -r koffice
....

Если пакет недоступен, используйте коллекцию портов. Например, для установки KOffice для KDE3, выполните:

[source,bash]
....
# cd /usr/ports/editors/koffice-kde3
# make install clean
....

=== AbiWord

AbiWord это свободно распространяемый текстовый процессор, по внешнему виду и поведению очень похожий на Microsoft(R) Word. Он подходит для набора документов, писем, отчетов, напоминаний и так далее. Он очень быстр, содержит много новшеств и очень удобен в использовании.

AbiWord может импортировать и экспортировать множество файловых форматов, включая патентованный Microsoft [.filename]#.doc#.

AbiWord доступен в виде пакета. Вы можете установить его так:

[source,bash]
....
# pkg_add -r abiword
....

Если пакет недоступен, он может быть собран из коллекции портов, которая должна быть свежей. Это можно сделать командой:

[source,bash]
....
# cd /usr/ports/editors/abiword
# make install clean
....

=== GIMP

Для создания и редактирования изображений есть продвинутая программа GIMP. Она может быть использована как простая программа рисования и как программа обработки фотографий. Поддерживается большое количество плагинов и предоставлен интерфейс для скриптов. GIMP может читать и записывать файлы многих форматов. Есть интерфейс со сканерами и планшетами.

Вы можете установить пакет, выполнив эту команду:

[source,bash]
....
# pkg_add -r gimp
....

Если на вашем сервере FTP нет этого пакета, вы можете использовать коллекцию портов. Категория http://www.FreeBSD.org/ru/ports/[graphics] коллекции портов содержит также раздел Руководство Gimp. Здесь показано, как его установить:

[source,bash]
....
# cd /usr/ports/graphics/gimp
# make install clean
# cd /usr/ports/graphics/gimp-manual-pdf
# make install clean
....

[NOTE]
====
Категория http://www.FreeBSD.org/ru/ports/[graphics] коллекции портов содержит версию GIMP для разработчиков в package:graphics/gimp-devel[]. HTML версия Руководства Gimp находятся в package:graphics/gimp-manual-html[].
====

=== OpenOffice.org

OpenOffice.org включает все обязательные компоненты полноценного офисного пакета: текстовый процессор, программу электронных таблиц, программу управления презентациями и программу векторной графики. Интерфейс пользователя очень похож на другие офисные пакеты, возможен импорт и экспорт различных популярных файловых форматов. Приложение доступно в вариантах для множества разных языков, включая интерфейсы, проверку орфографии и словари.

Текстовый процессор OpenOffice.org использует чистый XML формат файлов для увеличения переносимости и гибкости. Программа для работы с текстовыми таблицами предоставляет макроязык и может работать с внешними базами данных. OpenOffice.org уже стабильна и существует в версиях для Windows(R), Solaris(TM), Linux, FreeBSD, и Mac OS(R) X. Дополнительную информацию об OpenOffice.org можно найти на http://www.openoffice.org/[веб сайте OpenOffice.org]. Получить специфичную для FreeBSD информацию и загрузить пакеты можно с веб сайта команды портирования OpenOffice на FreeBSD (http://porting.openoffice.org/freebsd/[FreeBSD OpenOffice.org Porting Team]).

Для установки OpenOffice.org, выполните:

[source,bash]
....
# pkg_add -r openoffice
....

[NOTE]
====
Эта операция должна работать для любого релиза (-RELEASE) FreeBSD. Если вы используете иные версии (-STABLE, -CURRENT), нужный пакет может быть загружен с сайта группы поддержки OpenOffice.org и затем установлен при помощи man:pkg_add[1]. На сайте вы найдете как последний стабильный релиз, так и текущую версию, находящуюся в разработке.
====

После установки пакета просто наберите следующую команду для запуска OpenOffice.org:

[source,bash]
....
% openoffice.org
....

[NOTE]
====
Во время первого запуска, вам будут заданы несколько вопросов и в вашей домашней директории будет создан каталог [.filename]#.openoffice.org2#.
====

Если пакеты OpenOffice.org недоступны, можно выбрать компиляцию порта. Однако, вы должны помнить, что это потребует много места на диске и компиляция будет довольно долгой.

[source,bash]
....
# cd /usr/ports/editors/openoffice.org-2.0
# make install clean
....

[NOTE]
====
Если вы хотите собрать локализованную версию, то вместо предыдущей командной строки используйте следующее:

[source,bash]
....
# make LOCALIZED_LANG=your_language install clean
....

Вам следует изменить _your_language_ на корректный ISO код языка. Список поддерживаемых языковых кодов доступен в файле [.filename]#files/Makefile.localized#, расположенный в директории порта.
====

После того, как это было сделано OpenOffice.org может быть запущен командой:

[source,bash]
....
% openoffice.org
....

[[desktop-viewers]]
== Программы просмотра документов

Некоторые новые форматы документов приобрели большую популярность. Стандартные программы для их просмотра могут отсутствовать в базовой системе. В этом разделе мы увидим, как их установить.

В разделе говорится о следующих приложениях:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Название приложения
| Потребность в ресурсах
| Установка из портов
| Основные зависимости

|Acrobat Reader(R)
|малая
|легкая
|Linux Binary Compatibility

|gv
|малая
|легкая
|Xaw3d

|Xpdf
|малая
|легкая
|FreeType

|GQview
|малая
|легкая
|Gtk+ или GNOME
|===

=== Acrobat Reader(R)

Сейчас многие документы распространяются в формате PDF, аббревиатура для "Portable Document Format". Одна из рекомендованных программ для просмотра этого типа документов, это Acrobat Reader(R), выпущенный Adobe для Linux. Поскольку FreeBSD может запускать исполняемые файлы Linux, он доступен также и для FreeBSD.

Для установки Acrobat Reader(R) 7 из Коллекции портов выполните:

[source,bash]
....
# cd /usr/ports/print/acroread7
# make install clean
....

Пакет acroread7 недоступен из-за лицензионных ограничений.

=== gv

gv это программа просмотра PostScript(R) и PDF. Она разработана на основе ghostview, но выглядит лучше благодаря библиотеке Xaw3d. Она быстра, а ее интерфейс несложен. У gv есть множество функций, таких как выбор ориентации, размера бумаги, масштаба и сглаживание. Почти любая операция может быть выполнена как с клавиатуры, так и мышью.

Для установки gv из пакета, выполните:

[source,bash]
....
# pkg_add -r gv
....

Если вы не можете получить пакет, используйте коллекцию портов:

[source,bash]
....
# cd /usr/ports/print/gv
# make install clean
....

=== Xpdf

Если вам нужна небольшая программа просмотра PDF под FreeBSD, Xpdf это легкая и эффективная программа. Она требует очень небольшого количества ресурсов и очень стабильна. Используются стандартные шрифты X, Motif(R) или другие пакеты для X не нужны.

Для установки пакета Xpdf, выполните эту команду:

[source,bash]
....
# pkg_add -r xpdf
....

Если пакет недоступен, или вы предпочитаете коллекцию портов, выполните:

[source,bash]
....
# cd /usr/ports/graphics/xpdf
# make install clean
....

После завершения установки вы можете запустить Xpdf и использовать правую кнопку мыши для активации меню.

=== GQview

GQview это программа для работы с изображениями. Вы можете просмотреть файл одним кликом, запустить внешний редактор, получить миниатюры и многое другое. Еще в нем есть слайд-шоу и несколько основных файловых операций. Вы можете управлять коллекциями изображений и легко находить дубликаты. В GQview изображения можно просматривать во весь экран, его можно адаптировать к разным языкам.

Если вы хотите установить пакет GQview, выполните:

[source,bash]
....
# pkg_add -r gqview
....

Если пакет недоступен, или вы предпочитаете использовать коллекцию портов, выполните:

[source,bash]
....
# cd /usr/ports/graphics/gqview
# make install clean
....

[[desktop-finance]]
== Финансовые программы

Если по каким-то причинам вам нужно управлять своими финансами на десктопе FreeBSD, есть несколько мощных и простых в использовании приложений. Некоторые из них совместимы с широко распространенными форматами файлов, такими как документы Quicken или Excel.

В этом разделе говорится о следующих приложениях:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Название приложения
| Потребность в ресурсах
| Установка из портов
| Основные зависимости

|GnuCash
|малая
|тяжелая
|GNOME

|Gnumeric
|малая
|тяжелая
|GNOME

|Abacus
|малая
|легкая
|Tcl/Tk
|===

=== GnuCash

GnuCash это часть проекта GNOME, который стремится предоставить дружественные к пользователю приложения с широким набором функций. С GnuCash вы можете отслеживать доходы и расходы, банковские счета или акции. Интуитивный интерфейс программы не мешает ей оставаться очень профессиональной.

GnuCash предоставляет интеллектуальный журнал записей, иерархическую систему учетных записей, множество клавиатурных сокращений и метод автозавершения. Он может разбивать одну транзакцию на несколько частей, детализируя ее. GnuCash может импортировать и присоединять файлы Quicken QIF. Он также работает с основными международными форматами дат и валютами.

Для установки GnuCash в вашу систему, выполните:

[source,bash]
....
# pkg_add -r gnucash
....

Если пакет недоступен, вы можете использовать коллекцию портов:

[source,bash]
....
# cd /usr/ports/finance/gnucash
# make install clean
....

=== Gnumeric

Gnumeric это электронная таблица, часть графической среды GNOME. Она использует удобное автоматическое "угадывание" ввода пользователя в зависимости от формата ячейки и систему автозаполнения для множества последовательностей. Она может импортировать файлы нескольких популярных форматов, таких как Excel, Lotus 1-2-3, или Quattro Pro. Gnumeric работает с диаграммами через package:math/guppi[]. В ней множество встроенных функций, можно использовать обычные форматы ячеек: число, валюта, дата, время и многие другие.

Для установки Gnumeric из пакета, введите:

[source,bash]
....
# pkg_add -r gnumeric
....

Если пакет недоступен, вы можете использовать коллекцию портов:

[source,bash]
....
# cd /usr/ports/math/gnumeric
# make install clean
....

=== Abacus

Abacus это небольшая и простая в использовании программа электронных таблиц. В ней много встроенных функций из нескольких областей, таких как статистика, финансы и математика. Она может импортировать и экспортировать файлы Excel. Abacus также может печатать PostScript(R).

Для установки Abacus из пакета, выполните:

[source,bash]
....
# pkg_add -r abacus
....

Если пакет недоступен, вы можете использовать коллекцию портов, выполнив:

[source,bash]
....
# cd /usr/ports/deskutils/abacus
# make install clean
....

[[desktop-summary]]
== Итоги

Хотя FreeBSD популярна в основном среди провайдеров из-за стабильности и высокой производительности, на сегодняшний день она вполне готова к использованию в качестве десктопа. С несколькими тысячами приложений, доступных в виде http://www.FreeBSD.org/ru/where/[пакетов] или http://www.FreeBSD.org/ru/ports/[портов], вы можете создать прекрасный десктоп, отвечающий всем вашим потребностям.

После первой установки десктопа, вы можете попробовать сделать шаг вперед с package:misc/instant-workstation[]. Этот "мета-порт" позволяет вам собрать типичный набор портов для рабочей станции. Вы можете настроить его, редактируя [.filename]#/usr/ports/misc/instant-workstation/Makefile#. Следуйте синтаксису существующего файла при добавлении и удалении портов, соберите порт как обычно. В конечном итоге, вы можете создать большой пакет, соответствующий вашему собственному десктопу, и установить его на другие рабочие станции!

Вот небольшой обзор всех графических приложений, о которых говорилось в этой главе:

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Имя приложения
| Имя пакета
| Имя порта

|Mozilla
|`mozilla`
|package:www/mozilla[]

|Opera
|`linux-opera`
|package:www/linux-opera[]

|Firefox
|`firefox`
|package:www/firefox[]

|KOffice
|`koffice-kde3`
|package:editors/koffice-kde3[]

|AbiWord
|`abiword`
|package:editors/abiword[]

|The GIMP
|`gimp`
|package:graphics/gimp1[]

|OpenOffice.org
|`openoffice`
|package:editors/openoffice[]

|Acrobat Reader(R)
|`acroread`
|package:print/acroread7[]

|gv
|`gv`
|package:print/gv[]

|Xpdf
|`xpdf`
|package:graphics/xpdf[]

|GQview
|`gqview`
|package:graphics/gqview[]

|GnuCash
|`gnucash`
|package:finance/gnucash[]

|Gnumeric
|`gnumeric`
|package:math/gnumeric[]

|Abacus
|`abacus`
|package:deskutils/abacus[]
|===
