---
description: 'Эта глава демонстрирует, как установить множество рабочих сред, включая веб-браузеры, офисные программы, средства просмотра документов и финансовое программное обеспечение'
next: books/handbook/multimedia
params:
  path: /books/handbook/desktop/
part: 'Часть II. Стандартные задачи'
prev: books/handbook/partii
showBookMenu: 'true'
tags: ["desktop", "KDE Plasma", "GNOME", "XFCE", "MATE", "Cinnamon", "LXQT", "browsers", "Firefox", "Chromium", "Iridium", "Falkon", "Konqueror", "Epiphany", "qutebrowser", "Dillo", "Links", "w3m", "Development tools", "Visual Studio Code", "Qt Creator", "Kdevelop", "Eclipse IDE", "Vim", "Neovim", "GNU Emacs", "Productivity", "LibreOffice", "Calligra", "AbiWord", "Viewers", "Okular", "Evince", "ePDFView", "Xpdf", "Finance", "KMyMoney", "GnuCash"]
title: 'Глава 8. Графические среды рабочего стола'
weight: 11
---

[[desktop]]
= Рабочие столы
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 8
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/desktop/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[desktop-synopsis]]
== Обзор

Хотя FreeBSD популярна в качестве сервера благодаря своей производительности и стабильности, она также отлично подходит для повседневного использования в качестве настольной системы. Более чем {numports} приложений, доступных в дереве портов FreeBSD, позволяют легко создать настроенный рабочий стол, способный запускать широкий спектр настольных приложений. В этой главе показано, как установить популярные окружения рабочего стола, а также настольные приложения, такие как веб-браузеры, офисные программы, средства просмотра документов и финансовое ПО.

Предварительные требования:

* Читатели этой главы уже должны знать, как установить либо crossref:x11[x11,X Window System], либо crossref:wayland[wayland,Wayland] в FreeBSD.
* В этой главе читателям рекомендуется устанавливать официальные пакеты. Для сборки настраиваемых пакетов из портов обратитесь к разделу crossref:ports[ports-using,использование коллекции портов].

[[desktop-environments]]
== Рабочие столы

Этот раздел описывает, как установить и настроить некоторые популярные графические среды на системе FreeBSD. Графическая среда может варьироваться от простого оконного менеджера до полного набора приложений для рабочего стола.

.Поддерживаемые рабочие окружения
[options="header", cols="1,1,1"]
|===
| Имя | Лицензия | Пакет

| KDE Plasma
| GPL 2.0 или более поздняя
| x11/kde

| GNOME
| GPL 2.0 или более поздняя
| x11/gnome

| XFCE
| GPL, LGPL, BSD
| x11-wm/xfce4

| MATE
| GPL 2.0, LGPL 2.0
| x11/mate

| Cinnamon
| GPL 2.0 или более поздняя
| x11/cinnamon

| LXQT
| GPL, LGPL
| x11-wm/lxqt

|===

[[kde-environment]]
=== KDE Plasma

KDE Plasma — это удобная среда рабочего стола. Она предоставляет набор приложений с единообразным внешним видом и поведением, стандартизированным меню и панелями инструментов, сочетаниями клавиш, цветовыми схемами, поддержкой интернационализации и централизованной настройкой рабочего стола через диалоговые окна. Дополнительную информацию о KDE можно найти на сайте link:https://kde.org/[KDE homepage]. Информацию, специфичную для FreeBSD, см. на link:https://freebsd.kde.org/[FreeBSD homepage at KDE].

[[kde-meta-install]]
==== Установка мета-пакета KDE Plasma

Для установки мета-пакета KDE Plasma, включающего KDE Frameworks, Plasma Desktop и Applications, выполните:

[source, shell]
....
# pkg install kde
....

[[kde-minimal-install]]
==== Минимальная установка KDE Plasma

Для установки минимальной версии KDE Plasma выполните:

[source, shell]
....
# pkg install plasma6-plasma
....

[TIP]
====
Эта установка *действительно* минимальна. Konsole необходимо установить отдельно, выполнив:

[source, shell]
....
# pkg install konsole
....
====

[[kde-configuration]]
==== Настройка KDE Plasma

KDE Plasma использует man:dbus-daemon[1] в качестве шины сообщений и для аппаратной абстракции. Это приложение автоматически устанавливается как зависимость KDE Plasma.

Включите службу D-BUS в `/etc/rc.conf` для запуска при загрузке системы:

[source, shell]
....
# sysrc dbus_enable="YES"
....

KDE Plasma требует увеличенного размера сообщений для оптимальной производительности.

Добавьте следующие строки в man:sysctl.conf[5]:

[.programlisting]
....
sysctl net.local.stream.recvspace=65536
sysctl net.local.stream.sendspace=65536
....

Чтобы применить изменения, выполните следующую команду от имени root или просто перезагрузите систему:

[source, shell]
....
# sysctl -f /etc/sysctl.conf
....

[[kde-start]]
==== Запуск KDE Plasma

Предпочтительным дисплейным менеджером для KDE Plasma является package:x11/sddm[]. Для установки package:x11/sddm[] выполните:

[source, shell]
....
# pkg install sddm
....

Включите службу SDDM в `/etc/rc.conf` для автоматического запуска при загрузке системы:

[source, shell]
....
# sysrc sddm_enable="YES"
....

Язык клавиатуры можно настроить в SDDM, выполнив следующую команду (например, для испанского языка):

[source, shell]
....
# sysrc sddm_lang="es_ES"
....

Второй способ запуска KDE Plasma — это ручной вызов man:startx[1]. Для этого необходимо добавить следующую строку в файл ~/.xinitrc:

[source, shell]
....
% echo "exec dbus-launch --exit-with-x11 ck-launch-session startplasma-x11" > ~/.xinitrc
....

[[gnome-environment]]
=== GNOME

GNOME — это удобная графическая среда рабочего стола. Она включает панель для запуска приложений и отображения состояния, рабочий стол, набор инструментов и приложений, а также набор соглашений, которые упрощают взаимодействие и обеспечение согласованности между приложениями.

[[gnome-meta-install]]
==== Установка метапакета GNOME

Для установки метапакета GNOME с рабочим столом GNOME и приложениями выполните:

[source, shell]
....
# pkg install gnome
....

[[gnome-minimal-install]]
==== Минимальная установка GNOME

Для установки мета-пакета GNOME-lite с облегчённой версией рабочего стола GNOME, содержащей только основы, выполните:

[source, shell]
....
# pkg install gnome-lite
....

[[gnome-configuration]]
==== Настройка GNOME

Для работы GNOME необходимо подключить `/proc`. Добавьте следующую строку в `/etc/fstab`, чтобы автоматически подключать эту файловую систему при загрузке системы:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

GNOME использует man:dbus-daemon[1] в качестве шины сообщений и для аппаратной абстракции. Это приложение автоматически устанавливается как зависимость GNOME.

Включите службу D-BUS в `/etc/rc.conf` для запуска при загрузке системы:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[gnome-start]]
==== Запуск GNOME

GNOME Display Manager — это предпочтительный дисплейный менеджер для GNOME. GDM устанавливается как часть пакета GNOME.

Включите GDM в `/etc/rc.conf` для запуска при загрузке системы:

[source, shell]
....
# sysrc gdm_enable="YES"
....

Второй способ запуска GNOME — это ручной вызов man:startx[1]. Для этого необходимо добавить следующую строку в файл `~/.xinitrc`:

[source, shell]
....
% echo "exec gnome-session" > ~/.xinitrc
....

[[xfce-environment]]
=== XFCE

XFCE — это среда рабочего стола, основанная на GTK+, легковесная и предоставляющая простой, эффективный и удобный рабочий стол. Она полностью настраиваема, имеет главную панель с меню, апплетами и запусками приложений, предоставляет файловый менеджер и менеджер звука, а также поддерживает темы. Благодаря своей быстроте, легкости и эффективности, она идеально подходит для старых или медленных машин с ограниченными ресурсами памяти.

[[xfce-install]]
==== Установка XFCE

Для установки метапакета XFCE выполните:

[source, shell]
....
# pkg install xfce
....

[[xfce-configuration]]
==== Настройка XFCE

XFCE использует man:dbus-daemon[1] для шины сообщений и абстракции оборудования. Это приложение автоматически устанавливается как зависимость XFCE.

Включите D-BUS в `/etc/rc.conf` для запуска при загрузке системы:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[xfce-start]]
==== Запуск XFCE

package:x11/lightdm[] — это дисплейный менеджер, поддерживающий различные технологии отображения. Он является хорошим выбором, так как очень легковесен, требует мало памяти и обладает высокой производительностью.

Для установки выполните:

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

Включите lightdm в `/etc/rc.conf` для автоматического запуска при загрузке системы:

[source, shell]
....
# sysrc lightdm_enable="YES"
....

Второй способ запустить XFCE — вручную вызвать man:startx[1]. Для этого в `~/.xinitrc` должна быть следующая строка:

[source, shell]
....
% echo '. /usr/local/etc/xdg/xfce4/xinitrc' > ~/.xinitrc
....

[[mate-environment]]
=== MATE

Среда рабочего стола MATE является продолжением GNOME 2. Она предоставляет интуитивно понятную и привлекательную среду рабочего стола, использующую традиционные метафоры.

[[mate-meta-install]]
==== Установка метапакета MATE

Для установки метапакета MATE, который включает в себя MATE Desktop с дополнительными приложениями, такими как текстовый редактор, менеджер архивов и т.д., выполните:

[source, shell]
....
# pkg install mate
....

[[mate-minimal-install]]
==== Минимальная установка MATE

Чтобы установить мета-пакет MATE lite с облегчённой версией рабочего стола MATE, содержащий только основы, выполните:

[source, shell]
....
# pkg install mate-base
....

[[mate-configuration]]
==== Настройка MATE

MATE требует подключения `/proc`. Добавьте следующую строку в `/etc/fstab`, чтобы автоматически подключать эту файловую систему при загрузке системы:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

MATE использует man:dbus-daemon[1] для шины сообщений и абстракции оборудования. Это приложение автоматически устанавливается как зависимость MATE. Для запуска D-BUS при загрузке системы включите его в `/etc/rc.conf`:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[mate-start]]
==== Запуск MATE

package:x11/lightdm[] — это дисплейный менеджер, поддерживающий различные технологии отображения. Он является хорошим выбором, так как очень легковесен, требует мало памяти и обладает высокой производительностью.

Для установки выполните:

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

Включите lightdm в `/etc/rc.conf` для автоматического запуска при загрузке системы:

[source, shell]
....
# sysrc lightdm_enable="YES"
....

Второй способ запустить MATE — вручную вызвать man:startx[1]. Для этого необходимо добавить следующую строку в файл `~/.xinitrc`:

[source, shell]
....
% echo "exec dbus-launch --exit-with-x11 ck-launch-session mate-session" > ~/.xinitrc
....

[[cinnamon-environment]]
=== Cinnamon

Cinnamon — это UNIX(R)-совместимая рабочая среда, которая предоставляет передовые инновационные функции и традиционный пользовательский опыт. Компоновка рабочего стола похожа на Gnome 2. Базовые технологии являются ответвлением от Gnome Shell. Основной акцент сделан на том, чтобы пользователи чувствовали себя как дома, предоставляя им простую и комфортную рабочую среду.

[[cinnamon-install]]
==== Установка Cinnamon

Для установки пакета Cinnamon выполните:

[source, shell]
....
# pkg install cinnamon
....

[[cinnamon-configuration]]
==== Настройка Cinnamon

Для работы Cinnamon требуется подключенный `/proc`. Добавьте следующую строку в `/etc/fstab`, чтобы автоматически подключать эту файловую систему при загрузке системы:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

Cinnamon использует man:dbus-daemon[1] для шины сообщений и абстракции оборудования. Это приложение автоматически устанавливается как зависимость Cinnamon. Для запуска D-BUS при загрузке системы включите его в `/etc/rc.conf`:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[cinnamon-start]]
==== Запуск Cinnamon

package:x11/lightdm[] — это дисплейный менеджер, поддерживающий различные технологии отображения. Он является хорошим выбором, так как очень легковесен, требует мало памяти и обладает высокой производительностью.

Для установки выполните:

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

Включите lightdm в `/etc/rc.conf` для автоматического запуска при загрузке системы:

[source, shell]
....
# sysrc lightdm_enable="YES"
....

Второй способ запустить Cinnamon — вручную вызвать man:startx[1]. Для этого необходимо добавить следующую строку в файл `~/.xinitrc`:

[source, shell]
....
% echo "exec dbus-launch --exit-with-x11 ck-launch-session cinnamon-session" > ~/.xinitrc
....

[[lxqt-environment]]
=== LXQT

LXQt — это современная, простая в использовании и быстрая среда рабочего стола, основанная на технологиях Qt. Она создана для пользователей, которые ценят простоту, скорость и интуитивно понятный интерфейс. В отличие от большинства сред рабочего стола, LXQt также хорошо работает на менее производительных компьютерах.

[[lxqt-install]]
==== Установка LXQT

Чтобы установить метапакет LXQT, выполните:

[source, shell]
....
# pkg install lxqt
....

[[lxqt-configuration]]
==== Настройка LXQT

LXQT требует подключения `/proc`. Добавьте следующую строку в `/etc/fstab`, чтобы автоматически подключать эту файловую систему при загрузке системы:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

LXQT использует man:dbus-daemon[1] в качестве шины сообщений и для аппаратной абстракции. Это приложение автоматически устанавливается как зависимость LXQT.

Включите D-BUS в `/etc/rc.conf` для запуска при загрузке системы:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[lxqt-start]]
==== Запуск LXQT

Предпочтительным дисплейным менеджером для LXQT является package:x11/sddm[]. Для установки package:x11/sddm[] выполните:

[source, shell]
....
# pkg install sddm
....

Включите службу SDDM в `/etc/rc.conf` для автоматического запуска при загрузке системы:

[source, shell]
....
# sysrc sddm_enable="YES"
....

Язык клавиатуры можно настроить в SDDM, выполнив следующую команду (например, для испанского):

[source, shell]
....
# sysrc sddm_lang="es_ES"
....

Второй способ запуска LXQT — вручную вызвать man:startx[1]. Для этого потребуется добавить следующую строку в `~/.xinitrc`:

[source, shell]
....
% echo "exec dbus-launch --exit-with-x11 ck-launch-session startlxqt" > ~/.xinitrc
....

[[desktop-browsers]]
== Браузеры

В этом разделе описано, как установить и настроить некоторые популярные веб-браузеры в системе FreeBSD — от полнофункциональных браузеров с высоким потреблением ресурсов до текстовых браузеров с пониженным использованием ресурсов.

.Поддерживаемые браузеры
[options="header", cols="1,1,1,1"]
|===
| Имя | Лицензия | Пакет | Необходимые ресурсы

| Firefox
| MPL 2.0
| package:www/firefox[]
| Много

| Chromium
| BSD-3 и другие
| package:www/chromium[]
| Много

| Браузер Iridium
| BSD-3 и другие
| package:www/iridium-browser[]
| Много

| Falkon
| MPL 2.0
| package:www/falkon-qtonly[]
| Много

| Konqueror
| GPL 2.0 или более поздняя
| package:x11-fm/konqueror[]
| Средне

| Gnome Web (Epiphany)
| GPL 3.0 или новее
| package:www/epiphany[]
| Средне

| qutebrowser
| GPL 3.0 или новее
| package:www/qutebrowser[]
| Средне

| Dillo
| GPL 3.0 или новее
| package:www/dillo2[]
| Мало

| Ссылки
| GPL 2.0 или более поздняя
| package:www/links[]
| Мало

| w3m
| MIT
| package:www/w3m[]
| Мало

|===

[[firefox]]
=== Firefox

Firefox — это браузер с открытым исходным кодом, который включает в себя движок отображения HTML, соответствующий стандартам, вкладки, блокировку всплывающих окон, расширения, улучшенную безопасность и многое другое. Firefox основан на кодовой базе Mozilla.

Для установки пакета последней выпущенной версии Firefox выполните:

[source, shell]
....
# pkg install firefox
....

Для установки Firefox Extended Support Release (ESR) выполните:

[source, shell]
....
# pkg install firefox-esr
....

[[chromium]]
=== Chromium

Chromium — это проект браузера с открытым исходным кодом, целью которого является создание более безопасного, быстрого и стабильного веб-браузера. Chromium поддерживает вкладки, блокировку всплывающих окон, расширения и многое другое. Chromium — это проект с открытым исходным кодом, на основе которого создан браузер Google Chrome.

Чтобы установить Chromium, выполните:

[source, shell]
....
# pkg install chromium
....

[NOTE]
====
Исполняемый файл Chromium находится по пути [.filename]#/usr/local/bin/chrome#, а не [.filename]#/usr/local/bin/chromium#.
====

[[iridium]]
=== Браузер Iridium

Iridium — это бесплатный, открытый и свободный модифицированный браузер на основе кодовой базы Chromium, в котором усилена защита приватности в нескольких ключевых аспектах. Автоматическая передача частичных запросов, ключевых слов и метрик в центральные службы блокируется и происходит только с согласия пользователя.

Для установки Iridium выполните:

[source, shell]
....
# pkg install iridium-browser
....

[[falkon]]
=== Falkon

Falkon — это относительно новый и очень быстрый браузер на основе QtWebEngine. Он стремится быть легковесным веб-браузером, доступным на всех основных платформах. Falkon обладает всеми стандартными функциями, которые можно ожидать от веб-браузера, включая закладки, историю (доступные также в боковой панели) и вкладки. Кроме того, плагин AdBlock может блокировать рекламу, Click2Flash — Flash-содержимое, а SSL Manager позволяет редактировать локальную базу данных сертификатов CA.

Для установки Falkon выполните:

[source, shell]
....
# pkg install falkon
....

[[konqueror]]
=== Konqueror

Konqueror — это не просто веб-браузер, он также является файловым менеджером и мультимедийным просмотрщиком. Он поддерживает WebKit, механизм визуализации, используемый многими современными браузерами, включая Chromium, а также собственный движок KHTML.

Чтобы установить Konqueror, выполните:

[source, shell]
....
# pkg install konqueror
....

[[gnome-web-epiphany]]
=== Gnome Web (Epiphany)

Gnome Web (Epiphany) — это веб-браузер, разработанный для максимальной легкости и скорости, в ущерб многим функциям, присутствующим в других браузерах.

Для установки Gnome Web (Epiphany) выполните:

[source, shell]
....
# pkg install epiphany
....

[[qutebrowser]]
=== qutebrowser

Qutebrowser — это браузер с минимальным графическим интерфейсом, ориентированный на управление с клавиатуры. Он написан на Python и PyQt5 и распространяется как свободное программное обеспечение под лицензией GPL.

Для установки qutebrowser выполните:

[source, shell]
....
# pkg install qutebrowser
....

[[dillo]]
=== Dillo

Dillo стремится быть мультиплатформенным альтернативным браузером, который отличается компактностью, стабильностью, удобством для разработчиков, практичностью, скоростью работы и расширяемостью. Эта новая, экспериментальная версия Dillo основана на инструментарии FLTK, а не на GTK1, и была существенно переработана.

Для установки Dillo выполните:

[source, shell]
....
# pkg install dillo2
....

[[links]]
=== Ссылки

Веб-браузер, подобный lynx, с текстовым и графическим режимами, поддерживающий множество функций, таких как отображение таблиц, меню и т.д.

Для установки Links выполните:

[source, shell]
....
# pkg install links
....

[[w3m]]
=== w3m

w3m — это программа для просмотра текстовых страниц (пейджер) и текстовый веб-браузер. Это приложение похоже на Lynx, но обладает рядом функций, которых нет в Lynx, таких как отображение таблиц и фреймов.

Для установки w3m выполните:

[source, shell]
....
# pkg install w3m
....

[[desktop-development]]
== Инструменты разработки

Этот раздел описывает, как установить и настроить некоторые популярные инструменты разработки в системе FreeBSD.

.Поддерживаемые инструменты разработки
[options="header", cols="1,1,1,1"]
|===
| Имя | Лицензия | Пакет | Необходимые ресурсы

| Visual Studio Code
| MIT
| package:editors/vscode[]
| Много

| Qt Creator
| QtGPL
| package:devel/qtcreator[]
| Много

| Kdevelop
| GPL 2.0 или более поздняя и LGPL 2.0 или более поздняя
| package:devel/kdevelop[]
| Много

| Eclipse IDE
| EPL
| package:java/eclipse[]
| Много

| Vim
| VIM
| package:editors/vim[]
| Мало

| Neovim
| Apache 2.0
| package:editors/neovim[]
| Мало

| GNU Emacs
| GPL 3.0 или новее
| package:editors/emacs[]
| Мало

|===

[[vs-code]]
=== Visual Studio Code

Visual Studio Code — это инструмент, который сочетает простоту редактора кода с необходимыми для разработчиков возможностями цикла редактирования, сборки и отладки. Он предоставляет комплексную поддержку редактирования и отладки, модель расширяемости и лёгкую интеграцию с существующими инструментами.

Для установки Visual Studio Code выполните:

[source, shell]
....
# pkg install vscode
....

[[qt-creator]]
=== Qt Creator

Qt Creator — это кроссплатформенная IDE (интегрированная среда разработки), созданная с учетом потребностей разработчиков Qt. Функциональные возможности Qt Creator включают:

* редактор кода с поддержкой C++, QML и ECMAscript;
* быстрые инструменты для навигации по коду;
* статическая проверка кода и подсказки по стилю во время набора;
* контекстно-зависимая справка;
* визуальный отладчик;
* интегрированный графический интерфейс и конструктор форм.

Для установки Qt Creator выполните:

[source, shell]
....
# pkg install qtcreator
....

[[kdevelop]]
=== kdevelop

Открытая, многофункциональная IDE с поддержкой расширений через плагины для языков программирования C/C++ и других. Основана на KDevPlatform, а также библиотеках KDE и Qt, и разрабатывается с 1998 года.

Для установки kdevelop выполните:

[source, shell]
....
# pkg install kdevelop
....

[[eclipse]]
=== Eclipse IDE

Платформа Eclipse — это открытая расширяемая среда разработки (IDE) для чего угодно и в то же время ничего конкретного. Платформа Eclipse предоставляет строительные блоки и основу для создания и запуска интегрированных инструментов разработки программного обеспечения. Платформа Eclipse позволяет разработчикам инструментов независимо создавать инструменты, которые интегрируются с инструментами других разработчиков.

Для установки Eclipse IDE выполните:

[source, shell]
....
# pkg install eclipse
....

[[vim]]
=== Vim

Vim — это высоконастраиваемый текстовый редактор, созданный для эффективного редактирования текста. Это улучшенная версия редактора vi, поставляемого с большинством UNIX-систем.

Vim часто называют «редактором программиста», и он настолько полезен для программирования, что многие считают его полноценной IDE. Однако он предназначен не только для программистов. Vim идеально подходит для любого вида редактирования текста — от написания электронных писем до правки конфигурационных файлов.

Для установки Vim выполните:

[source, shell]
....
# pkg install vim
....

[[neovim]]
=== Neovim

Neovim представляет собой радикальный рефакторинг package:editors/vim[]. Это полная переработка кодовой базы с множеством улучшений, включая разумные настройки по умолчанию, встроенный эмулятор терминала, асинхронную архитектуру плагинов и мощные API, ориентированные на скорость и расширяемость. При этом сохраняется полная совместимость с почти всеми плагинами и скриптами Vim.

Для установки Neovim выполните:

[source, shell]
....
# pkg install neovim
....

[[gnu-emacs]]
=== GNU Emacs

GNU Emacs — это расширяемый, настраиваемый, свободный текстовый редактор. В его основе лежит интерпретатор Emacs Lisp, диалекта языка программирования Lisp с расширениями для поддержки редактирования текста.

Чтобы установить GNU Emacs, выполните:

[source, shell]
....
# pkg install emacs
....

[[desktop-productivity]]
== Настольные офисные приложения

Когда речь заходит о продуктивности, пользователи часто ищут офисный пакет или простой в использовании текстовый редактор. Хотя некоторые окружения рабочего стола, такие как crossref:desktop[kde-environment, KDE Plasma], предоставляют офисный пакет, стандартного пакета для продуктивности не существует. Для FreeBSD доступно несколько офисных пакетов и графических текстовых процессоров, независимо от установленных окружений рабочего стола.

В этом разделе показано, как установить следующее популярное программное обеспечение для повышения продуктивности, а также указано, является ли приложение ресурсоемким, требует ли оно много времени для компиляции из портов или имеет какие-либо значительные зависимости.

.Поддерживаемые офисные пакеты для настольных компьютеров
[options="header", cols="1,1,1,1"]
|===
| Имя | Лицензия | Пакет | Необходимые ресурсы

| LibreOffice
| MPL 2.0
| package:editors/libreoffice[]
| Много

| Calligra Suite
| LGPL и GPL
| package:editors/calligra[]
| Средне

| AbiWord
| GPL 2.0 или более поздняя
| package:editors/abiword[]
| Средне

|===

[[libreoffice]]
=== LibreOffice

LibreOffice — это свободный офисный пакет, разрабатываемый http://www.documentfoundation.org/[The Document Foundation]. Он совместим с другими крупными офисными пакетами и доступен на различных платформах. Это переименованная форк Apache OpenOffice, включающая приложения, входящие в полный офисный пакет: текстовый процессор, электронные таблицы, программу для создания презентаций, графический редактор, систему управления базами данных и инструмент для создания и редактирования математических формул. LibreOffice доступен на множестве языков, а интернационализация охватывает интерфейсы, средства проверки орфографии и словари. Дополнительную информацию о LibreOffice можно найти на http://www.libreoffice.org/[libreoffice.org].

Для установки LibreOffice выполните:

[source, shell]
....
# pkg install libreoffice
....

Пакет LibreOffice по умолчанию поставляется только на английском языке. Для получения локализованной версии LibreOffice необходимо установить языковой пакет. Например, для версии на испанском языке необходимо установить пакет package:editors/libreoffice-es[] с помощью команды:

[source, shell]
....
# pkg install libreoffice-es
....

[[calligra]]
=== Calligra

Среда рабочего стола KDE Plasma включает офисный пакет, который можно установить отдельно от KDE Plasma. Calligra содержит стандартные компоненты, которые можно встретить в других офисных пакетах. Words — это текстовый процессор, Sheets — программа для работы с электронными таблицами, Stage предназначен для управления презентациями, а Karbon используется для создания графических документов.

Для установки Calligra выполните:

[source, shell]
....
# pkg install calligra
....

[[abiword]]
=== AbiWord

AbiWord — это бесплатная программа для обработки текстов, внешне и функционально схожая с Microsoft(R) Word. Она быстрая, обладает множеством функций и удобна в использовании.

AbiWord может импортировать или экспортировать множество форматов файлов, включая некоторые проприетарные, такие как Microsoft(R) [.filename]#.rtf#.

Для установки AbiWord выполните:

[source, shell]
....
# pkg install abiword
....

[[desktop-viewers]]
== Просмотрщики документов

Некоторые новые форматы документов приобрели популярность со времен появления UNIX(R), и программы для их просмотра могут отсутствовать в базовой системе. В этом разделе показано, как установить следующие программы для просмотра документов:

.Поддерживаемые программы для просмотра документов
[options="header", cols="1,1,1,1"]
|===
| Имя | Лицензия | Пакет | Необходимые ресурсы

| Okular
| GPL 2.0
| package:graphics/okular[]
| Много

| Evince
| GPL 2.0
| package:graphics/evince[]
| Средне

| ePDFView
| GPL 2.0
| package:graphics/epdfview[]
| Средне

| Xpdf
| GPL 2.0
| package:graphics/xpdf[]
| Мало

| Zathura
| Zlib
| package:graphics/zathura[]
| Мало

|===

[[okular]]
=== Okular

Okular — это универсальный просмотрщик документов, часть проекта KDE Plasma.

Okular сочетает в себе превосходную функциональность с универсальностью поддержки различных типов документов, таких как PDF, Postscript, DjVu, CHM, XPS, ePub и других.

Чтобы установить Okular, выполните:

[source, shell]
....
# pkg install okular
....

[[evince]]
=== Evince

Evince — это программа для просмотра документов в различных форматах, включая PDF и Postscript. Часть проекта GNOME. Цель Evince — заменить такие программы для просмотра документов, как ggv и gpdf, на одно простое приложение.

Для установки Evince выполните:

[source, shell]
....
# pkg install evince
....

[[epdfview]]
=== ePDFView

ePDFView — это легковесная программа для просмотра PDF-документов, использующая только библиотеки Gtk+ и Poppler. Цель ePDFView — создать простой просмотрщик PDF-документов, аналогичный Evince, но без использования библиотек GNOME.

Для установки ePDFView выполните:

[source, shell]
....
# pkg install epdfview
....

[[xpdf]]
=== Xpdf

Для пользователей, предпочитающих небольшой просмотрщик PDF в FreeBSD, Xpdf предоставляет легковесное и эффективное решение, требующее минимум ресурсов. Он использует стандартные шрифты X и не требует дополнительных инструментариев.

Для установки Xpdf выполните:

[source, shell]
....
# pkg install xpdf
....

[[zathura]]
=== Zathura

Zathura — это высоконастраиваемая и функциональная программа для просмотра документов. Она предоставляет минималистичный и компактный интерфейс, а также простоту использования, ориентированную в основном на взаимодействие с клавиатурой.

Для установки zathura с поддержкой PDF выполните:

[source, shell]
....
# pkg install zathura zathura-pdf-mupdf
....

Кроме того, можно установить package:graphics/zathura-pdf-poppler[] для альтернативной поддержки PDF, package:graphics/zathura-ps[] для поддержки PostScript, package:graphics/zathura-djvu[] для поддержки DjVu и package:graphics/zathura-cb[] для поддержки комиксов.

[[desktop-finance]]
== Финансы

Для управления личными финансами на рабочем столе FreeBSD можно установить мощные и удобные приложения. Некоторые из них совместимы с распространёнными форматами файлов, такими как форматы, используемые Quicken и Excel.

Этот раздел охватывает следующие программы:

.Поддерживаемые программы для финансов
[options="header", cols="1,1,1,1"]
|===
| Имя | Лицензия | Пакет | Необходимые ресурсы

| KMyMoney
| GPL 2.0
| package:finance/kmymoney[]
| Много

| GnuCash
| GPL 2.0 и GPL 3.0
| package:finance/gnucash[]
| Много

|===

[[kmymoney]]
=== KMyMoney

KMyMoney — это приложение для управления личными финансами, созданное сообществом KDE. KMyMoney стремится предоставить важные функции, которые можно встретить в коммерческих приложениях для управления финансами. Среди его особенностей — простота использования и поддержка двойной бухгалтерии. KMyMoney поддерживает импорт из стандартных файлов Quicken QIF, отслеживание инвестиций, работу с несколькими валютами и предоставляет множество отчетов.

Для установки KMyMoney выполните:

[source, shell]
....
# pkg install kmymoney
....

[[gnucash]]
=== GnuCash

GnuCash — это часть проекта GNOME, направленного на предоставление пользователям удобных, но мощных приложений. GnuCash позволяет отслеживать доходы и расходы, банковские счета и акции. Он сочетает интуитивно понятный интерфейс с профессиональным функционалом.

GnuCash предоставляет умный регистр, иерархическую систему счетов, а также множество сочетаний клавиш и методов автодополнения. Он позволяет разделять одну транзакцию на несколько более детализированных частей. GnuCash поддерживает импорт и объединение файлов Quicken QIF. Также программа работает с большинством международных форматов дат и валют.

Для установки GnuCash выполните:

[source, shell]
....
# pkg install gnucash
....
