# $FreeBSD$

SUBDIR = developers-handbook
SUBDIR+= faq
SUBDIR+= fdp-primer
SUBDIR+= handbook
SUBDIR+= porters-handbook
#SUBDIR+= zh-tut

ROOT_SYMLINKS = faq fdp-primer handbook porters-handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
