# $FreeBSD: www/en/donations/Makefile,v 1.5 2003/01/27 16:42:27 trhodes Exp $
# $FreeBSDru: frdp/www/ru/donations/Makefile,v 1.1 2003/09/30 17:23:51 andy Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml wantlist.sgml donors.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
