---
title: Приложение B. Библиография
part: Часть V. Приложения
prev: books/handbook/mirrors
next: books/handbook/eresources
---

[appendix]
[[bibliography]]
= Библиография
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Содержание
:table-caption: Таблица
:figure-caption: Рисунок
:example-caption: Пример
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: B

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/ru/mailing-lists.adoc[]
include::shared/ru/teams.adoc[]
include::shared/ru/urls.adoc[]

Так как страницы Справочника FreeBSD предоставляют лишь описание отдельных частей операционной системы FreeBSD, они не очень удобны для иллюстрации объединения этих частей вместе для того, чтобы настроить ОС и сделать ее работу более гладкой. Для этого незаменимы хорошая книга по системному администрированию UNIX(R) и хорошее руководство пользователя.

[[bibliography-freebsd]]
== Книги и журналы, специализирующиеся на FreeBSD

_Международные книги и журналы:_

* http://jdli.tw.FreeBSD.org/publication/book/freebsd2/index.html[Using FreeBSD] (на китайском).
* FreeBSD Unleashed (перевод на китайский), опубликовано http://www.hzbook.com/[China Machine Press]. ISBN 7-111-10201-0. 
* FreeBSD From Scratch First Edition (на китайском), опубликовано China Machine Press. ISBN 7-111-07482-3. 
* FreeBSD From Scratch Second Edition (на китайском), опубликовано China Machine Press. ISBN 7-111-10286-X. 
* FreeBSD Handbook (на китайском), опубликовано http://www.ptpress.com.cn/[Posts & Telecom Press]. ISBN 7-115-10541-3. 
* FreeBSD 3.x Internet (на китайском), опубликовано http://www.tup.tsinghua.edu.cn/[Tsinghua University Press]. ISBN 7-900625-66-6.
* FreeBSD & Windows (на китайском), ISBN 7-113-03845-X
* FreeBSD Internet Services HOWTO (на китайском), ISBN 7-113-03423-3
* FreeBSD for PC 98'ers (на японском), выпущено SHUWA System Co, LTD. ISBN 4-87966-468-5 C3055 P2900E.
* FreeBSD (на японском), выпущено CUTT. ISBN 4-906391-22-2 C3055 P2400E.
* http://www.shoeisha.com/book/Detail.asp?bid=650[Complete Introduction to FreeBSD] (на японском), выпущено http://www.shoeisha.co.jp/[Shoeisha Co., Ltd]. ISBN 4-88135-473-6 P3600E.
* http://www.ascii.co.jp/pb/book1/shinkan/detail/1322785.html[Personal UNIX Starter Kit FreeBSD] (на японском), выпущено http://www.ascii.co.jp/[ASCII]. ISBN 4-7561-1733-3 P3000E.
* FreeBSD Handbook (японский перевод), выпущено http://www.ascii.co.jp/[ASCII]. ISBN 4-7561-1580-2 P3800E.
* FreeBSD mit Methode (на немецком), выпущено http://www.cul.de[Computer und Literatur Verlag]/Vertrieb Hanser, 1998. ISBN 3-932311-31-0.
* http://www.cul.de/freebsd.html[FreeBSD 4 - Installieren, Konfigurieren, Administrieren] (на немецком), выпущено http://www.cul.de[Computer und Literatur Verlag], 2001. ISBN 3-932311-88-4.
* http://www.cul.de/freebsd.html[FreeBSD 5 - Installieren, Konfigurieren, Administrieren] (на немецком), выпущено http://www.cul.de[Computer und Literatur Verlag], 2003. ISBN 3-936546-06-1.
* http://www.mitp.de/vmi/mitp/detail/pWert/1343/[ FreeBSD de Luxe] (на немецком), выпущено http://www.mitp.de[Verlag Modere Industrie], 2003. ISBN 3-8266-1343-0. 
* http://www.pc.mycom.co.jp/FreeBSD/install-manual.html[FreeBSD Install and Utilization Manual] (на японском), выпущено http://www.pc.mycom.co.jp/[Mainichi Communications Inc.].
* Onno W Purbo, Dodi Maryanto, Syahrial Hubbany, Widjil Widodo _http://maxwell.itb.ac.id/[Создание Интернет Сервера с использованием FreeBSD]_ (на Индонезийском языке), выпущено http://www.elexmedia.co.id/[Elex Media Komputindo].

_Книги и журналы на английском языке:_

* http://www.AbsoluteBSD.com/[Absolute BSD: The Ultimate Guide to FreeBSD], выпущено http://www.nostarch.com/[No Starch Press], 2002. ISBN: 1886411743
* http://www.freebsdmall.com/cgi-bin/fm/bsdcomp[ The Complete FreeBSD], выпущено http://www.oreilly.com/[O'Reilly], 2003. ISBN: 0596005164
* http://www.freebsd-corp-net-guide.com[The FreeBSD Corporate Networker's Guide], выпущено http://www.awl.com/aw/[Addison-Wesley], 2000. ISBN: 0201704811
* http://andrsn.stanford.edu/FreeBSD/introbook/[ FreeBSD: An Open-Source Operating System for Your Personal Computer], выпущено The Bit Tree Press, 2001. ISBN: 0971204500
* Teach Yourself FreeBSD in 24 Hours, выпущено http://www.samspublishing.com/[Sams], 2002. ISBN: 0672324245
* FreeBSD unleashed, выпущено http://www.samspublishing.com/[Sams], 2006. ISBN: 0672328755
* FreeBSD: The Complete Reference, выпущено http://books.mcgraw-hill.com[McGrawHill], 2003. ISBN: 0072224096 

[[bibliography-userguides]]
== Руководства для пользователей

* Computer Systems Research Group, UC Berkeley. _4.4BSD User's Reference Manual_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-075-9
* Computer Systems Research Group, UC Berkeley. _4.4BSD User's Supplementary Documents_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-076-7
* _UNIX in a Nutshell_. O'Reilly & Associates, Inc., 1990. ISBN 093717520X
* Mui, Linda. _What You Need To Know When You Can't Find Your UNIX System Administrator_. O'Reilly & Associates, Inc., 1995. ISBN 1-56592-104-6
* http://www-wks.acs.ohio-state.edu/[Ohio State University] написал http://www-wks.acs.ohio-state.edu/unix_course/unix.html[ Ознакомительный Курс UNIX] который доступен в Online в HTML и PS форматах.
+ 
Итальянский https://www.FreeBSD.org/doc/it_IT.ISO8859-15/books/unix-introduction/index.html[перевод] этого документа доступен как часть FreeBSD Italian Documentation Project.
* http://www.jp.FreeBSD.org/[Jpman Project, Japan FreeBSD Users Group]. http://www.pc.mycom.co.jp/FreeBSD/urm.html[FreeBSD User's Reference Manual] (Японский перевод). http://www.pc.mycom.co.jp/[Mainichi Communications Inc.], 1998. ISBN4-8399-0088-4 P3800E.
* http://www.ed.ac.uk/[Эдинбургский Университет] составил http://unixhelp.ed.ac.uk/[Online Путеводитель] для новичков в UNIX.

[[bibliography-adminguides]]
== Руководства для администраторов

* Albitz, Paul and Liu, Cricket. _DNS and BIND_, 4th Ed. O'Reilly & Associates, Inc., 2001. ISBN 1-59600-158-4
* Computer Systems Research Group, UC Berkeley. _4.4BSD System Manager's Manual_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-080-5
* Costales, Brian, et al. _Sendmail_, 2nd Ed. O'Reilly & Associates, Inc., 1997. ISBN 1-56592-222-0
* Frisch, Æleen. _Essential System Administration_, 2nd Ed. O'Reilly & Associates, Inc., 1995. ISBN 1-56592-127-5
* Hunt, Craig. _TCP/IP Network Administration_, 2nd Ed. O'Reilly & Associates, Inc., 1997. ISBN 1-56592-322-7
* Nemeth, Evi. _UNIX System Administration Handbook_. 2nd Ed. Prentice Hall, 2000. ISBN 0-13-020601-6
* Stern, Hal _Managing NFS and NIS_ O'Reilly & Associates, Inc., 1991. ISBN 0-937175-75-7
* http://www.jp.FreeBSD.org/[Jpman Project, Japan FreeBSD Users Group]. http://www.pc.mycom.co.jp/FreeBSD/sam.html[FreeBSD System Administrator's Manual] (Japanese translation). http://www.pc.mycom.co.jp/[Mainichi Communications Inc.], 1998. ISBN4-8399-0109-0 P3300E.
* Dreyfus, Emmanuel. http://www.eyrolles.com/Informatique/Livre/9782212114638/[Cahiers de l'Admin: BSD] 2nd Ed. (на французском), Eyrolles, 2004. ISBN 2-212-11463-X

[[bibliography-programmers]]
== Руководства для программистов

* Asente, Paul, Converse, Diana, and Swick, Ralph. _X Window System Toolkit_. Digital Press, 1998. ISBN 1-55558-178-1
* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Reference Manual_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-078-3
* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Supplementary Documents_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-079-1
* Harbison, Samuel P. and Steele, Guy L. Jr. _C: A Reference Manual_. 4th ed. Prentice Hall, 1995. ISBN 0-13-326224-3
* Kernighan, Brian and Dennis M. Ritchie. _The C Programming Language_. 2nd Ed. PTR Prentice Hall, 1988. ISBN 0-13-110362-8
* Lehey, Greg. _Porting UNIX Software_. O'Reilly & Associates, Inc., 1995. ISBN 1-56592-126-7
* Plauger, P. J. _The Standard C Library_. Prentice Hall, 1992. ISBN 0-13-131509-9
* Spinellis, Diomidis. http://www.spinellis.gr/codereading/[Code Reading: The Open Source Perspective]. Addison-Wesley, 2003. ISBN 0-201-79940-5
* Spinellis, Diomidis. http://www.spinellis.gr/codequality/[Code Quality: The Open Source Perspective]. Addison-Wesley, 2003. ISBN 0-201-79940-5
* Stevens, W. Richard. _Advanced Programming in the UNIX Environment_. 2nd Ed. Reading, Mass. : Addison-Wesley, 2005. ISBN 0-201-43307-9
* Stevens, W. Richard. _UNIX Network Programming_. 2nd Ed, PTR Prentice Hall, 1998. ISBN 0-13-490012-X
* Wells, Bill. "Writing Serial Drivers for UNIX". _Dr. Dobb's Journal_. 19(15), December 1994. pp68-71, 97-99.

[[bibliography-osinternals]]
== Внутренности операционной системы

* Andleigh, Prabhat K. _UNIX System Architecture_. Prentice-Hall, Inc., 1990. ISBN 0-13-949843-5
* Jolitz, William. "Porting UNIX to the 386". _Dr. Dobb's Journal_. January 1991-July 1992.
* Leffler, Samuel J., Marshall Kirk McKusick, Michael J Karels and John Quarterman _The Design and Implementation of the 4.3BSD UNIX Operating System_. Reading, Mass. : Addison-Wesley, 1989. ISBN 0-201-06196-1
* Leffler, Samuel J., Marshall Kirk McKusick, _The Design and Implementation of the 4.3BSD UNIX Operating System: Answer Book_. Reading, Mass. : Addison-Wesley, 1991. ISBN 0-201-54629-9
* McKusick, Marshall Kirk, Keith Bostic, Michael J Karels, and John Quarterman. _The Design and Implementation of the 4.4BSD Operating System_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-54979-4
+ 
(глава 2 этой книги доступна link:{design-44bsd}[онлайн] как часть Проекта документирования FreeBSD, и глава 9 доступна http://www.netapp.com/tech_library/nfsbook.html[ здесь].)
* Marshall Kirk McKusick, George V. Neville-Neil _The Design and Implementation of the FreeBSD Operating System_. Boston, Mass. : Addison-Wesley, 2004. ISBN 0-201-70245-2
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 1: The Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63346-9
* Schimmel, Curt. _Unix Systems for Modern Architectures_. Reading, Mass. : Addison-Wesley, 1994. ISBN 0-201-63338-8
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 3: TCP for Transactions, HTTP, NNTP and the UNIX Domain Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63495-3
* Vahalia, Uresh. _UNIX Internals -- The New Frontiers_. Prentice Hall, 1996. ISBN 0-13-101908-2
* Wright, Gary R. and W. Richard Stevens. _TCP/IP Illustrated, Volume 2: The Implementation_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63354-X

[[bibliography-security]]
== Безопасность

* Cheswick, William R. and Steven M. Bellovin. _Firewalls and Internet Security: Repelling the Wily Hacker_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63357-4
* Garfinkel, Simson and Gene Spafford. _Practical UNIX & Internet Security_. 2nd Ed. O'Reilly & Associates, Inc., 1996. ISBN 1-56592-148-8
* Garfinkel, Simson. _PGP Pretty Good Privacy_ O'Reilly & Associates, Inc., 1995. ISBN 1-56592-098-8

[[bibliography-hardware]]
== Оборудование

* Anderson, Don and Tom Shanley. _Pentium Processor System Architecture_. 2nd Ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40992-5
* Ferraro, Richard F. _Programmer's Guide to the EGA, VGA, and Super VGA Cards_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-62490-7
* Intel Corporation publishes documentation on their CPUs, chipsets and standards on their http://developer.intel.com/[developer web site], usually as PDF files.
* Shanley, Tom. _80486 System Architecture_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40994-1
* Shanley, Tom. _ISA System Architecture_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40996-8
* Shanley, Tom. _PCI System Architecture_. 4th ed. Reading, Mass. : Addison-Wesley, 1999. ISBN 0-201-30974-2
* Van Gilluwe, Frank. _The Undocumented PC_, 2nd Ed. Reading, Mass: Addison-Wesley Pub. Co., 1996. ISBN 0-201-47950-8
* Messmer, Hans-Peter. _The Indispensable PC Hardware Book_, 4th Ed. Reading, Mass: Addison-Wesley Pub. Co., 2002. ISBN 0-201-59616-4

[[bibliography-history]]
== История UNIX(R)

* Lion, John _Lion's Commentary on UNIX, 6th Ed. With Source Code_. ITP Media Group, 1996. ISBN 1573980137
* Raymond, Eric S. _The New Hacker's Dictionary, 3rd edition_. MIT Press, 1996. ISBN 0-262-68092-0. Also known as the http://www.catb.org/~esr/jargon/html/index.html[Jargon File]
* Salus, Peter H. _A quarter century of UNIX_. Addison-Wesley Publishing Company, Inc., 1994. ISBN 0-201-54777-5
* Simon Garfinkel, Daniel Weise, Steven Strassmann. _The UNIX-HATERS Handbook_. IDG Books Worldwide, Inc., 1994. ISBN 1-56884-203-1. Не печаталась, доступна по адресу http://research.microsoft.com/~daniel/unix-haters.html[ online].
* Don Libes, Sandy Ressler _Life with UNIX_ - special edition. Prentice-Hall, Inc., 1989. ISBN 0-13-536657-7
* _The BSD family tree_. http://www.FreeBSD.org/cgi/cvsweb.cgi/src/shared/misc/bsd-family-tree[http://www.FreeBSD.org/cgi/cvsweb.cgi/src/shared/misc/bsd-family-tree] или link:file://localhost/usr/shared/misc/bsd-family-tree[/usr/shared/misc/bsd-family-tree] на компьютере FreeBSD.
* _The BSD Release Announcements collection_. 1997. http://www.de.FreeBSD.org/de/ftp/releases/[http://www.de.FreeBSD.org/de/ftp/releases/]
* _Networked Computer Science Technical Reports Library_. http://www.ncstrl.org/[http://www.ncstrl.org/]
* _Old BSD releases from the Computer Systems Research group (CSRG)_. http://www.mckusick.com/csrg/[http://www.mckusick.com/csrg/]: В набор на 4CD включены все версии BSD от 1BSD до 4.4BSD и 4.4BSD-Lite2 (но к сожалению нет 2.11BSD). На последнем диске находится также последняя версия исходных текстов и файлы SCCS.

[[bibliography-journals]]
== Прочие издания

* _The C/C++ Users Journal_. R&D Publications Inc. ISSN 1075-2838
* _Sys Admin - The Journal for UNIX System Administrators_ Miller Freeman, Inc., ISSN 1061-2688
* _freeX - Das Magazin für Linux - BSD - UNIX_ (на немецком) Computer- und Literaturverlag GmbH, ISSN 1436-7033
