---
title: "Руководство по сообщению о нарушениях кодекса поведения FreeBSD"
sidenav: docs
---

= Руководство по сообщению о нарушениях кодекса поведения FreeBSD

== Руководство по сообщению о нарушениях кодекса поведения FreeBSD

Если вы считаете, что кто-то нарушает link:../code-of-conduct[кодекс поведения], мы просим вас сообщить об этом в Комитет по кодексу поведения FreeBSD по электронной почте conduct@freebsd.org.

Все сообщения будут сохраняться конфиденциальными, насколько это возможно.
Мы стремимся защитить личность и безопасность заявителей.
В некоторых случаях нам может потребоваться сделать публичное заявление в той или иной форме, и в этом случае мы будем использовать минимум деталей и идентифицирующей информации, необходимых для защиты нашего сообщества.
В редких случаях нам может потребоваться раскрыть личность некоторых вовлечённых лиц для соблюдения закона или защиты других потенциальных жертв.
В таких случаях мы проконсультируемся с заявителем, чтобы узнать его пожелания, и учтём их при принятии окончательного решения.
Во всех случаях мы не будем прямо или косвенно идентифицировать заявителей без их согласия, если только не увидим иного выхода.

Если вы считаете, что кто-либо находится в физической опасности, сначала обратитесь в соответствующие правоохранительные органы.

В вашем сообщении укажите:

* Ваше имя и контактную информацию (чтобы мы могли связаться с вами при необходимости).
* Имена (настоящие, прозвища и/или псевдонимы) всех вовлечённых лиц. Если были другие свидетели, кроме вас, пожалуйста, укажите и их.
* Когда и где произошёл инцидент. Пожалуйста, укажите как можно более конкретные детали.
* Ваше описание произошедшего. Если существует общедоступная запись (например, архив списка рассылки, твит или публичный лог IRC), пожалуйста, приложите ссылку и/или скриншоты.
* Любые дополнительные обстоятельства, которые вы считаете важными для инцидента.
* Если вы считаете, что инцидент продолжается.
* Любую другую информацию, которая, по вашему мнению, может быть полезна.

== Что происходит после подачи сообщения?

Поскольку Комитет по кодексу поведения FreeBSD управляется Командой ядра, вы получите письмо от Команды ядра в течение 48 часов с подтверждением получения жалобы.

Комитет соберётся как можно скорее для рассмотрения инцидента и определения:

* Необходимо ли проведение расследования, включая опрос дополнительных сторон или свидетелей;
* Что, по-видимому, произошло;
* Является ли данное поведение нарушением Кодекса поведения.

Если член Комитета по кодексу поведения FreeBSD является одним из лиц, упомянутых в сообщении, он должен самоотвести себя от рассмотрения этого сообщения.

После того как рабочая группа получит полную картину событий, она примет решение о том, как реагировать.
Предпринимаемые меры могут включать:

* Отсутствие мер (например, если мы определим, что нарушения не было).
* Если нарушение признано исключительно техническим по своей природе или выходит за рамки Кодекса поведения, передача инцидента Команде ядра FreeBSD.
* Частное предупреждение от рабочей группы вовлечённому лицу (лицам).
* Публичное предупреждение.
* Принудительный перерыв в пространствах, контролируемых проектом FreeBSD (например, просьба «взять неделю отпуска» в списке рассылки или IRC).
* Постоянный или временный запрет на участие в некоторых или всех пространствах, контролируемых проектом FreeBSD (мероприятия, встречи, списки рассылки, IRC и т.д.)
* Просьба о публичном или частном извинении.
* Просьба о посредничестве и/или плане восстановления.

Мы приложим все усилия, чтобы ответить в течение недели лицу, подавшему сообщение, либо с решением, либо с объяснением, почему ситуация ещё не разрешена.

После того как мы определим окончательные меры, мы свяжемся с первоначальным заявителем, чтобы сообщить ему о принятых мерах (если таковые были).
Мы примем во внимание отзывы заявителя о соответствии нашего ответа, но не гарантируем, что будем действовать в соответствии с ними.

Команда ядра может принять решение о публичном отчёте об инциденте.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (22.06.2023): 9e3690e5b69c86c27b224197cea0ce4c14196bab
//
