---
title: "Политика в отношении пользовательских данных"
sidenav: docs
---

= Политика в отношении пользовательских данных

== Обоснование

Проект FreeBSD предоставляет разработчикам несколько ресурсов, включая различные машины и хранилища данных. Эти ресурсы предназначены для использования в деятельности, связанной с проектом FreeBSD. Проект не даёт разработчикам никаких гарантий относительно данных, не связанных с проектом, которые хранятся на ресурсах проекта. Разработчикам настоятельно рекомендуется не использовать ресурсы проекта для хранения данных, не связанных с проектом. Команда ядра FreeBSD утвердила следующую политику в отношении пользовательских данных, которая была опубликована в списке рассылки разработчиков 4 августа 2011 года.

== Политика

Ресурсы проекта FreeBSD должны использоваться только для деятельности, связанной с проектом, и для хранения данных, относящихся к проекту.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (21.02.2021): eb4b89b8d31574df0a18fc5f7562181ccd6eecd6
//
