---
title: "Информация для коммиттеров FreeBSD"
sidenav: docs
---

include::shared/ru/urls.adoc[]

= Информация для коммиттеров FreeBSD

== link:{committers-guide}[Руководство для коммиттеров]

Основной документ для всех новых коммиттеров, описывающий как технические, так и организационные аспекты. В частности, могут оказаться полезными разделы link:{committers-guide}#cvs.operations[Работа с CVS], link:{committers-guide}#gnats[система отслеживания ошибок GNATS] и link:{committers-guide}#ssh.guide[Краткое руководство по SSH].

Этот документ содержит практически всё, что должен знать новый коммиттер проекта FreeBSD.

== link:{fdp-primer}[Учебник для новых участников проекта документирования FreeBSD]

Этот учебник отражает всё, что вам нужно знать для того, чтобы принять участие в Проекте документирования FreeBSD, от инструментов и программного обеспечения, которое вы будете использовать (как в обязательном, так и факультативном порядке), до основополагающих идей Проекта Документирования.

== link:{porters-handbook}[Руководство по созданию портов FreeBSD]

Руководство для коммиттеров портов FreeBSD, включающее в себя link:{porters-handbook}#freebsd-versions[Таблицу значений переменной __FreeBSD_version].

== link:{fdp-primer}#the-website-build[Построение страниц веб-сервера FreeBSD]

Этот документ описывает построение и обновление веб-страниц FreeBSD из дерева CVS в ручном режиме.

== Проекты FreeBSD

* link:../../docproj/[Проект Документирования FreeBSD]
* link:../../releng/[Процесс выпуска релизов FreeBSD]
* http://people.FreeBSD.org/~picobsd/[PicoBSD]
* link:../../platforms/alpha[Проект FreeBSD/Alpha]
* link:../../platforms/ia64/[Проект FreeBSD/IA-64]
* link:../../platforms/ppc[Проект FreeBSD/PPC]
* link:../../platforms/sparc[Проект FreeBSD/SPARC]
* http://www.TrustedBSD.org/[Проект TrustedBSD]
* link:../../projects/[Проекты разработки FreeBSD]

== Другие ресурсы

* link:../../developers/cvs[CVS Repository]
* link:../../support/#gnats[Сообщения об ошибках]
* link:../../security/[Информация о безопасности FreeBSD]
* link:../../copyright/[Copyright]
* http://wikitest.FreeBSD.org[FreeBSD Wiki (веб-энциклопедия)]
* http://perforce.FreeBSD.org[Репозиторий Perforce для коммиттерских проектов]

link:..[Внутренняя информация FreeBSD]
