---
title: "Информация для коммиттеров FreeBSD"
sidenav: docs
---

include::shared/ru/urls.adoc[]

= Информация для коммиттеров FreeBSD

== link:{committers-guide}[Руководство для коммиттеров]

Этот документ является общим руководством для всех новых коммиттеров, включая как технические детали, так и политики.
Что касается первого, см. главы о link:{committers-guide}#git-primer[системе контроля версий Git], системе отслеживания ошибок link:{committers-guide}#bugzilla[Bugzilla] и link:{committers-guide}#ssh.guide[кратком руководстве по SSH].

Он содержит почти всё, что нужно знать новому коммиттеру проекта FreeBSD.
Для получения дополнительной информации см. «Руководство для начинающих по проекту документации» и «Руководство FreeBSD по созданию портов».

== link:{fdp-primer}[Руководство для новых участников проекта документации FreeBSD]

Всё, что вам нужно знать, чтобы начать вносить вклад в проект – от обязательного и рекомендуемого программного обеспечения до философии, лежащей в основе проекта.

=== link:{fdp-primer}doc-build/#doc-build-rendering-html[Компиляция в HTML]

Использование Git-репозитория для обновления и сборки страниц.

== link:{porters-handbook}[Руководство FreeBSD по созданию портов]

Руководство для участников и коммиттеров портов FreeBSD.
Включает каноническую link:{porters-handbook}versions[таблицу значений `__FreeBSD_version`].

== Проекты FreeBSD

* link:../../docproj/[Проект Документирования FreeBSD]
* link:../../releng/[Информация о подготовке релизов]
* link:../../platforms/[Проекты аппаратных платформ FreeBSD]
* link:../../projects/[Проекты разработки FreeBSD]

== Другие ресурсы

* link:https://docs.freebsd.org/ru/articles/committers-guide/#committer.types[Репозитории исходного кода]
* link:../../support/[Поддержка]
* link:../../security/[Информационная безопасность FreeBSD]
* link:../../copyright/[Информация об авторских правах на FreeBSD]
* https://wiki.FreeBSD.org[Вики FreeBSD]

link:..[Домашняя страница внутренних ресурсов FreeBSD]

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (22.07.2023): 15f38de2dd79b77e1de1694a49ba44d97d26c3d4
//
