---
title: "Обязанности группы FreeBSD Doceng Team"
sidenav: docs
---

= Обязанности группы FreeBSD Doceng Team

Команда doceng@ является новой рабочей группой для решения общих вопросов, имеющих отношение к Проекту Документирования FreeBSD. К первоочередным обязанностям этой группы относятся:

* Прохождение новых кандидатур коммиттеров для работы над doc/, www/, документацией по релизам и справочным страницам.
* Поддержку учебника по проекту документирования, в котором описаны наилучшие подходы, используемые во FreeBSD Documentation Project.
* Управление процессом подготовки doc/ к релизу. Сюда включается координация обновлений к документации по релизам между различными группами переводчиков, работа с группой подготовки релизов по наложению метки на дерево doc/ при выпуске релиза, а также документирование этих процедур.
* Обеспечение размещения генерируемой документации (в форматах PDF, HTML и так далее) на Web-сайте и FTP-сервере, а также их соответствие версиям документов в хранилище CVS. Сюда включается обеспечение нормального построения Web-сайта и работа с группой администраторов по установке на основной Web-сервер всего требуемого программного обеспечения (включая скрипты для построения).
* Выступать при необходимости как MAINTAINER (поддерживающий) или работать вместе с существующими группами поддержки для обеспечения работоспособности используемых инструментов построения (DocBook, groff и так далее).
* Поддержка целостности деревьев doc/ и www/ во FreeBSD. Из-за видимости этих файлов и документов во внешнем мире, doceng@ оставляет за собой право немедленно откатывать (или исправлять, не ожидая ответа от коммиттера) изменения, приведшие к появлению неправильных ссылок, некорректного построения Web-сайта или каким-либо другим неприятным последствиям для доступности Web-сайта и документации FreeBSD.

Особенно подчёркивается, что doceng@ *не* занимается решением конфликтов внутри FreeBSD Documentation Project. Проект ведёт и будет вести обсуждение и принятие решений в списке рассылки freebsd-doc.

== Текущий состав участников

На данный момент участниками этой группы являются Nik Clayton, Ruslan Ermilov, Marc Fonvieille, Hiroki Sato и Murray Stokely. Предполагается, что этот список будет пополняться вместе с добавлением новых участников из различных проектов перевода.

== Новые коммиттеры документации

Новые коммиттеры документации подтверждаются группой doceng@ посредством голосования по электронной почте в течение 1 недели. Кандидат считается прошедшим, если по крайней мере 1 участник doceng@ проголосовал положительно, и ни один человек из состава группы doceng@ не проголосовал против. core@ оповещается копией сообщения (CC) для admins@ о создании новой учётной записи.

== Неактивные коммиттеры

Группа doceng@ связывается с коммиттерами документации, в течение 12 месяцев не проявлявшими активности (отсутствие коммитов в основной репозиторий); если в течение 1 месяца ответ не получен, такие коммиттеры автоматически удаляются из списков доступа. Кроме того, в случае отсутствия ответа, группа doceng@ сообщает о неактивных коммиттерах группе core@.
