---
title: "Правила устаревания коммит бита"
sidenav: docs
--- 

= Правила устаревания коммит бита

== Обоснование

Случается, что коммиттеры FreeBSD находят другие занятия, которые занимают их время, и решают отказаться от коммит бита. В некоторых ситуациях, впрочем, коммиттер может не проявлять активности в течение долгого времени без явного отказа от бита. В долгосрочной перспективе, такие учетные записи могут создавать проблемы безопасности, а также поднимать вопросы, связанные с поддержкой контактной информации и методов доступа этой учетной записи. По этим причинам, FreeBSD Core утверждает нижеследующие правила окончания срока действия коммит бита (опубликованы в списке рассылки разработчиков FreeBSD 22 февраля 2002 г.)

== Правила

Коммиттеры, не вносившие изменений в репозиторий в течение 18 месяцев, будут время от времени удаляться из файла доступа. Коммиттеры, желающие восстановить коммит бит, должны обращаться к соответствующим персонам. В будущем данная процедура может быть уточнена.
