---
title: "Политика ограничения сроков полномочий для назначенных ролей (hat)"
sidenav: docs
---

= Политика ограничения сроков полномочий для назначенных ролей (hat)

== Обоснование

Основная Команда FreeBSD (Core Team) назначает несколько лиц для выполнения критически важных ролей в проекте. Важно уменьшить количество единых точек отказа на этих должностях. Кроме того, смена ролей может привнести свежие идеи и помочь избежать профессионального выгорания.

В настоящее время к назначенным Основной Комадой ролям относятся: секретарь Основной Команды, главный инженер релизов, офицер безопасности и почтмейстер.

Основная Команда FreeBSD утвердила следующую политику ограничения сроков полномочий для ролей. Впервые она была опубликована в списке рассылки разработчиков 22 июня 2012 года и дополнена в июне 2015 года.

== Политика

Лицо может занимать роль, назначенную Основной Командой, при соблюдении следующих условий:

* Основная Команда утверждает его назначение или переназначение на эту роль.
* Лицо согласно продолжать работу.
* Лицо по-прежнему способно эффективно выполнять свои обязанности.

Роли назначаются по усмотрению Основной Команды. Назначения могут быть отозваны Основной Командой в любое время, если это соответствует интересам проекта.

Срок полномочий каждой роли начинается через три месяца после начала двухлетнего срока полномочий Основной Команды и заканчивается через три месяца после окончания срока полномочий Основной Команды. Роли должны быть явно утверждены новой Основной Командой в начале срока своих полномочий.

Если роль становится вакантной в течение срока, Основная Команда назначает замену на оставшийся срок.

Основная Команда проводит ежегодный пересмотр всех ролей.

В целом ожидается, что добровольцы, занимающие роли, будут ограничены четырьмя последовательными годами службы с округлением до ближайшего естественного цикла пересмотра/назначения.

Недобровольцы, занимающие роли, по-прежнему обязаны участвовать в ежегодных пересмотрах и обеспечивать преемственность, удовлетворительную для Основной Команды.

Каждая роль должна назначить заместителя, который сможет выполнять его обязанности в случае отсутствия или болезни, а также быть обученным и готовым принять на себя роль (при условии одобрения Основной Командой), если текущий обладатель должности уйдёт в отставку до окончания своего срока.

Если полномочия Основной Команды будут досрочно прекращены, то следующий срок для каждой роли начнётся через три месяца после начала срока полномочий новой Основной Команды.

Эти ограничения применяются к отдельным ролям, а не к командам. Для команд с единым руководящим лицом ограничения применяются к этому руководящему лицу. Лицо, которое не имеет права занимать руководящую должность в команде, может продолжать быть членом этой команды.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (21.02.2021): eb4b89b8d31574df0a18fc5f7562181ccd6eecd6
//
