---
title: "Сеть FreeBSD.org"
sidenav: docs
---

= Сеть FreeBSD.org

Для тех, кто имеет доступ к сети FreeBSD.org, эта страница описывает, какие машинные ресурсы доступны и для каких целей они выделены.

Список ключей SSH и их подписей для открыто доступных машин в домене FreeBSD.org находится в link:https://www.FreeBSD.org/internal/ssh-keys.asc[этом файле].

== Хосты FreeBSD.org для разработчиков

Эти системы доступны для использования разработчиками / коммиттерами FreeBSD. Эталонные системы могут использоваться для тестовых сборок и т.д.

[.tblbasic]
[cols=",,,",options="header",]
|===
|Хост |ОС |Тип |Назначение
|freefall |16-CURRENT |amd64 |Вход в оболочку.
|ref[16\|15\|14\|13]-amd64 |X-STABLE |amd64 |Эталонная машина для общего тестирования и сборки портов.
|ref[14\|13]-i386 |X-STABLE |i386 |Эталонная машина для общего тестирования и сборки портов.
|ref[16\|15\|14\|13]-aarch64 |X-STABLE |arm64\|aarch64 |Эталонная машина для общего тестирования и сборки портов.
|universe[16\|15\|14\|13][a\|b] |X-STABLE |amd64 |Машина для сборки universe для быстрой компиляции в больших масштабах.
|===

Машины обычно подключены на скорости 1 Гбит/с в полнодуплексном режиме к выделенному коммутатору с резервированными гигабитными аплинками. Все системы имеют последовательные консоли с ведением журнала и удалённое управление питанием.

link:..[Внутренняя информация FreeBSD]

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (19.09.2025): e5e303758d5279e69d72b82b8fcfb98613524cd7
//
