---
title: "Зеркалирование страниц веб-сервера FreeBSD"
sidenav: docs
---

include::shared/ru/urls.adoc[]

= Зеркалирование страниц веб-сервера FreeBSD

Вы можете (и даже приглашаетесь) зеркалировать страницы веб-сервера FreeBSD `www.FreeBSD.org`. Чтобы сделать это, вам нужно сгрузить и установить на ваш веб-сервер программу, которая называется _cvsup_. link:{handbook}#INSTALL[CVSup] является пакетом программ для распространения и обновления наборов файлов по сети.

== Установка CVSup

Вы можете построить и проинсталлировать CVSup из исходных текстов при помощи команд

....
 # cd /usr/ports/net/cvsup-without-gui
 # make all install clean
....

Впрочем, гораздо проще может оказаться поставить готовый пакет из link:{handbook}#packages-using[Коллекции пакетов]. За подробностями обращайтесь к упомянутой главе Руководства.

== Запуск CVSup

Если вы сохраняете зеркалируемые страницы веб-сервера FreeBSD в каталоге `/usr/FreeBSD-mirror`, владельцем которого является пользователь `fred', запустите такую команду от пользователя `fred':

....
     $ cvsup supfile-www
....

Файл `supfile-www` содержит:

....
       *default host=cvsup.FreeBSD.org
       *default prefix=/usr/FreeBSD-mirror
       *default base=/usr/local/etc/cvsup
       www release=current delete use-rel-suffix compress
....

Здесь страницы веб-сервера FreeBSD будут зеркалироваться в `/usr/FreeBSD-mirror`. Вы можете внести эту команду в crontab пользователя fred, чтобы она запускалась ежедневно. Страницы на сервере www.FreeBSD.org обновляются ежедневно в 4:30am по Калифорнийскому времени.

== Дополнительная информация о CVSup

Посмотрите link:{handbook}#CVSUP[Введение в CVSup] в Руководстве.

link:..[Внутренняя информация FreeBSD]
