---
title: "Процедура заведения новых учетных записей"
sidenav: docs
---

include::shared/ru/urls.adoc[]

= Процедура заведения новых учетных записей

== Выдвижение нового коммиттера

Если Вы собираетесь рекомендовать кого-либо в команду коммиттеров FreeBSD, необходимо послать ответственному лицу письмо со следующей информацией:

* Историю участия претендента в проекте FreeBSD. Эта информация _необходима_, и ее предоставление стало стандартом де-факто за последние несколько лет.
* Имя (учетную запись) коммиттера, готового стать ментором для нового коммиттера.
* Адрес электронной почты претендента (его довольно часто забывают!)

Запрос на коммиттерский бит, не оформленный по указанным правилам, будет в лучшем случае отложен в долгий ящик, а то и вызовет раздражение в ваш адрес со стороны ответственной персоны.

Адреса ответственных лиц по различным частям репозитория:

* src -> core@
* doc -> doceng@
* ports -> portmgr@

Вы получите подтверждение после прочтения Вашего письма; ответ от core@ или doceng@ должен прийти в течение <= 7 дней. Группе portmgr@ может потребоваться до 14 дней для принятия решения. Ответ претенденту и номинируемому может прийти раньше, если голосование закончится досрочно.

== Авторизация нового логина

Для авторизации с одного из приведенных ниже адресов на адреса admins@FreeBSD.org, core@FreeBSD.org и адрес персоны, которая будет ментором для нового коммиттера, должно прийти подписанное PGP письмо, подтверждающее необходимость заведения нового логина. Письмо должно содержать ссылку на эту страницу, чтобы ментор и его подопечный знали, что от них ожидают.

Подписанные PGP подтверждения принимаются только со следующих адресов:

* core-secretary
* portmgr-secretary
* doceng

_ВНИМАНИЕ: Запросы на создание новых логинов не от указанных персон, или подписанные иными PGP-ключами (или не подписанные), не обрабатываются. Без исключений. Запрос на создание логина для коммиттера портов или документации должен быть отправлен также (CC:) на адрес Правления (core@)._

== Информация, необходимая от ментора нового коммиттера

Ментор нового коммиттера должен собрать и прислать на адрес admins@FreeBSD.org следующую информацию:

* Строка для `master.passwd`, содержащая предпочитаемое имя пользователя, оболочку и личную информацию (GECOS); поле пароля заполнять не нужно
* публичный ключ для ssh V2 (*ТОЛЬКО для версии 2*)

Ментор отвечает за достоверный сбор этой информации и предоставление ее группе admins@ достоверным образом. Предпочтительным способом доставки является письмо, подписанное находящимся в Руководстве Пользователя PGP-ключом ментора. Если этот метод по каким-либо причинам недоступен, ментор может создать файл, содержащий необходимую информацию, в своем домашнем каталоге на машине freefall, после чего сообщить имя файла на admins@freebsd.org. Нам необходимо удостовериться, что информация о новом коммиттере в самом деле исходит от ментора, а не подписанные письма в настоящее время не дают такой возможности. Поскольку информация от будущего коммиттера не может быть проверена напрямую, ее должен посылать ментор.

== admins@FreeBSD.org создают учетную запись

Кто-либо из группы admins@FreeBSD.org на основе вышеописанной информации создает на машинах кластера FreeBSD.org новую учетную запись и информирует об этом нового коммиттера и его ментора.

== Ментор активирует коммит бит

После того, как новый коммиттер подтвердит, что новая учетная запись работает, ментор активизирует коммит бит и помогает ему завершить первые шаги.

== Завершение работы с ментором

Период работы с ментором не фиксируется жестко. Когда ментор решает, что его подопечный готов к "свободному полету", он сообщает об этом сообществу разработчиков, делая форсированный коммит в файл `access` с соответствующим комментарием.

== Передача опекаемого другому ментору

При необходимости передать опекаемого вами коммиттера другому ментору напишите письмо ответственным, как при создании новой учетной записи. Как правило, подобные запросы утверждаются без лишней волокиты. Сообщество уведомляется о передаче коммиттера путем форсированного коммита в файл `access`.
