---
title: "Процедура заведения новых учетных записей"
sidenav: docs
---

include::shared/ru/urls.adoc[]

= Процедура заведения новых учетных записей

== Выдвижение нового коммиттера

Если Вы собираетесь рекомендовать кого-либо в команду коммиттеров FreeBSD, необходимо послать ответственному лицу письмо со следующей информацией:

* Историю участия претендента в проекте FreeBSD. Эта информация _необходима_, и ее предоставление стало стандартом де-факто за последние несколько лет.
* Имя (учетную запись) коммиттера, готового стать ментором для нового коммиттера.
* Адрес электронной почты претендента (его довольно часто забывают!)

Запрос на коммиттерский бит, не оформленный по указанным правилам, будет в лучшем случае отложен в долгий ящик, а то и вызовет раздражение в ваш адрес со стороны ответственной персоны.
Для получения некоторых рекомендаций о том, как должно быть написано само предложение, пожалуйста, обратитесь к link:../proposing-committers[краткому обзору].

Адреса ответственных лиц по различным частям репозитория:

* src -> core@
* doc -> doceng@
* ports -> portmgr@

Вы получите подтверждение после того, как сообщение будет просмотрено, а srcmgr@, doceng@ и portmgr@ ответят вам после завершения голосования или по истечении таймаута.
Таймаут для srcmgr@ и portmgr@ установлен в 7 дней, тогда как для doceng@ — 14 дней, однако, как указано, это лишь наихудший случай, и члены команд могут завершить голосование раньше.

== Авторизация нового логина

Кто-либо из перечисленного ниже списка отправляет по электронной почте на адрес accounts@ письмо, подписанное PGP, копируя наставника, назначенного новому коммиттеру, и с копией core@FreeBSD.org, подтверждающее утверждение новой учётной записи.
Это письмо должно содержать ссылку на данный документ, чтобы наставник и подопечный знали, что от них ожидается.

Утверждения новых учётных записей действительны только от следующих PGP-сущностей:

* srcmgr-secretary (для прав на коммит в src)
* portmgr-secretary (для прав на коммит в ports)
* doceng-secretary (для прав на коммит в doc)

_ПРИМЕЧАНИЕ: Запросы на создание новых учётных записей от кого-либо, кроме этих сущностей, или запросы, подписанные PGP-ключами, отличными от ключей этих сущностей, не будут обрабатываться.
Исключений нет._

== Информация, необходимая от ментора нового коммиттера

Лицо, назначенное наставником нового коммиттера, должно собрать и отправить следующую информацию на адрес accounts@:

* имя пользователя (строчные латинские буквы a-z и цифры 0-9)
* полное имя (как в поле GECOS; в кодировке UTF-8)
* дополнительную информацию GECOS (телефон, местоположение и т.п.) — необязательно
* командную оболочку (доступны sh, csh/tcsh, bash, zsh)
* открытый ключ SSH версии 2

Наставник обязан получить эту информацию от нового коммиттера надёжным способом и передать её в accounts@ также надёжным способом. 
Предпочтительным методом для отправки информации в accounts@ является письмо, подписанное PGP, при условии, что открытый ключ наставника уже добавлен в Справочник.
Если по какой-либо причине это невозможно, допустимой заменой является размещение наставником информации об учётной записи в своём домашнем каталоге на freefall с последующим уведомлением accounts@ о месте размещения.
Мы должны быть уверены, что информация об учётной записи действительно исходит от наставника, и неподписанное письмо для этого недостаточно. 
Поскольку у accounts@ нет способа проверить что-либо от нового коммиттера, эта информация должна быть отправлена в accounts@ наставником, а не новым коммиттером.

== accounts@FreeBSD.org создают учетную запись

accounts@ создаёт новую учётную запись с указанной выше информацией в кластере FreeBSD.org и уведомляет наставника и нового коммиттера.

== Ментор активирует коммит бит нового коммиттера

После того как новый коммиттер подтвердит, что учётная запись работает, наставник добавляет нового коммиттера в соответствующий файл `access`, используя соответствующее сообщение коммита.
Сообщение коммита должно содержать как минимум полное имя и имя пользователя коммиттера, имя наставника и область, в которой новый коммиттер начнёт работать.
Также должна быть добавлена запись в файл `mentors` в соответствующем link:{committers-guide}#admin-branch[репозитории Git] для указания отношений наставничества.
После выполнения всех этих действий новый коммиттер и наставник совместно выполняют первые операции коммита.

== Дополнительные службы

Наставник должен добавить нового коммиттера в группу https://wiki.freebsd.org/DevelopersGroup[Developers] на вики-сайте и в проект https://reviews.freebsd.org/project/view/3/[committer] на Phabricator.

Чтение link:{committers-guide}[Руководства коммиттера] считается хорошим первым шагом для новых коммиттеров, особенно раздела link:{committers-guide}#conventions[«Соглашения и традиции»].

== Завершение работы с ментором

Период работы с ментором не фиксируется жестко.
Когда наставник посчитает, что подопечный готов к самостоятельной работе, наставник уведомляет сообщество разработчиков, удаляя запись из файла `mentors` ветки `internal/admin` в репозитории Git.

== Передача опекаемого другому ментору

При необходимости передать опекаемого вами коммиттера другому ментору напишите письмо ответственным, как при создании новой учетной записи. 
Как правило, подобные запросы утверждаются без лишней волокиты.
Сообщество уведомляется о передаче коммиттера путем форсированного коммита в файл `mentors` в Git.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (20.04.2025): acd54835f6f138c8ad455af7903d2479d3c49727
//
