---
title: "Предложение кандидатов в коммиттеры"
sidenav: docs
---

= Предложение кандидатов в коммиттеры

Следующие рекомендации предназначены для потенциальных наставников при принятии решения о том, подходит ли кандидат для предложения на получение права на коммит, и при подготовке предложения для рассмотрения Основной Командой или её делегатами. Обратите внимание, что в случае делегированного утверждения (например, Portmgr или Doceng) могут применяться дополнительные процедуры или ограничения (например, касающиеся характера вклада).

Рецензенты предложений о предоставлении прав на коммит будут обращать внимание на несколько ключевых качеств потенциальных разработчиков: сильные технические способности, наличие подтверждённого вклада в проект FreeBSD, свидетельства способности работать самостоятельно в рамках сообщества (т.е. наставничество не потребуется бесконечно), свидетельства способности разработчика конструктивно взаимодействовать с сообществом FreeBSD (и, в частности, наличие социальных навыков для участия в иногда острых онлайн-дискуссиях), а также намерение вносить вклад в проект в будущем. Как правило, подтверждающие материалы для предложения о предоставлении прав на коммит включают описание профессионального и образовательного опыта кандидата, контекст его вклада в проект (например, волонтёр, сотрудник и т.п.), ссылки на патчи, сообщения о проблемах или коммиты, подтверждающие его вклад, указания на участие в списках рассылки или иное участие в жизни сообщества (например, выступления на конференциях по BSD), убедительные свидетельства конструктивного взаимодействия с наставником на данный момент, а также список интересов и потенциальных областей для дальнейшего и будущего вклада.

Потенциальным наставникам напоминается, что предоставить доступ на коммит гораздо проще, чем отозвать его, поэтому значительный вес придаётся конструктивному взаимодействию с сообществом, а не просто техническим заслугам. Если наставник сомневается в пригодности кандидата, разумным может быть сначала обратиться в Основную Команду с неформальным запросом о рекомендациях, а не с официальным предложением — это может привести к совету продолжать работу, просьбе предоставить дополнительные материалы или предложению отложить предложение до накопления дополнительного опыта. Предполагается, что просьбы набраться опыта или предоставить дополнительные доказательства участия и вклада в сообщество будут восприняты в том духе, в каком они сделаны: предоставление права на коммит — это значимое действие, которое во многом основывается на уже проделанной работе, а не только на высоких технических навыках. Проект предпочитает консервативный подход к предоставлению прав на коммит, а не преждевременное их предоставление.

В некоторых случаях могут предоставляться «права на коммит для поставщиков» (vendor commit bits), чтобы разрешить прямые коммиты в драйверы устройств (или потенциально другие компоненты), поддерживаемые, например, производителем оборудования. К таким кандидатам могут предъявляться менее строгие требования по прошлому участию в сообществе на основании серьёзных обязательств со стороны поставщика и опытного наставника, а также ограниченной сферы полномочий на самостоятельные изменения в системе. Крайне важно, чтобы такие права на коммит использовались с должной осмотрительностью и пониманием проблем сообщества; ответственность наставника заключается в том, чтобы не допустить нежелательных трений и чтобы изменения соответствовали процедурам проекта и ожиданиям сообщества. Если право на коммит предоставлено в таком контексте, оно может быть отозвано, когда сотрудник покинет своего работодателя; однако имеется значительная история того, как обладатели «прав для поставщиков» впоследствии вносили более широкий вклад, и это желаемый исход! Наставникам, предлагающим такие права, следует предпринять все необходимые шаги, чтобы права на коммит предоставлялись только тем лицам, которые могут нести ответственность за качество и тестирование вносимых ими изменений от имени поставщика и обладают необходимыми техническими и социальными навыками для конструктивного взаимодействия с сообществом. Рекомендуется, чтобы предложения о таких правах в максимально возможной степени содержали те же сведения, что и для обычных прав на коммит, с особым акцентом на качество технического вклада.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (21.02.2021): eb4b89b8d31574df0a18fc5f7562181ccd6eecd6
//
