---
title: "Политика прав на коммит и ресурсов проекта"
sidenav: docs
---

include::shared/ru/urls.adoc[]

= Политика прав на коммит и ресурсов проекта

== Обоснование

Основная Команда (Core Team) управляет доступом к ресурсам проекта, включая предоставление и отзыв как прав на коммит, так и учётных записей пользователей. Основная Команда может делегировать части этих задач другим группам или лицам по своему усмотрению. Например, определённые права на коммит управляются другими группами, как указано в link:{committers-guide}#committer.types[Типах прав на коммит], при условии окончательного утверждения Основной Командой. Основная Команда обладала этими полномочиями с момента своего создания, но хотела сделать это явным, чтобы избежать путаницы. Основная Команда FreeBSD утвердила следующую политику прав на коммит и ресурсов проекта, которая была опубликована в списке рассылки разработчиков 4 августа 2011 года.

== Политика

Основная Команда обладает исключительным правом управления доступом к ресурсам проекта. Это включает предоставление и отзыв как прав на коммит, так и учётных записей пользователей.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (19.06.2021): 8e22e76d94dc5fef83abcb3c082ab4242ef90ba2
//
