# $FreeBSD: www/ja/conspectus/Makefile,v 1.2 2000/10/02 09:16:05 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml 

# not translated yet
#SUBDIR=	stable

### Revision checking
REVCHECK=	yes

.include "${WEB_PREFIX}/share/mk/web.site.mk"
