# $FreeBSD: www/ja/conspectus/Makefile.inc,v 1.1 2000/06/18 23:06:42 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

WEBBASE?=	/data/ja/conspectus
WEB_PREFIX?=	${.CURDIR}/../../..
