# $FreeBSD: www/ja/conspectus/Makefile,v 1.1 2000/06/18 23:06:42 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

LOCALTOP= ..

.if exists(${LOCALTOP}/Makefile.conf)
.include "${LOCALTOP}/Makefile.conf"
.endif

DOCS=   index.sgml 

# not translated yet
#SUBDIR=	stable

### Revision checking
REVCHECK=	yes

.include "${LOCALTOP}/web.mk"
