---
title: "Sobre las Aplicaciones para FreeBSD"
sidenav: about
---

= Sobre las Aplicaciones para FreeBSD

== Experimenta las posibilidades con FreeBSD

FreeBSD puede manejar cualquier tarea que pueda esperar de una estación de trabajo UNIX(R), incluyendo algunas que no esperaría:

== FreeBSD es un verdadero sistema abierto con todo el código fuente.

No hay duda que los llamados sistemas abiertos son _el_ requerimiento para las aplicaciones informáticas de hoy en día. Pero ningún solución comercial es más abierta que una que incluya el código fuente de todo el sistema, incluyendo el kernel además de todos los daemons del sistema, programas y utilidades. Puede modificar cualquier parte de FreeBSD para acomodarlo a sus necesidades personales, de organización o corporativas.

Con su generosa link:../copyright/license/[política de licencias], puede usar FreeBSD como base para cualquier tipo de _aplicación_ tanto comercial como libre.

== FreeBSD ejecuta miles de aplicaciones.

Por que FreeBSD está basado en 4.4BSD, una versión estándar de UNIX(R) en la industria, es fácil compilar y ejecutar programas. FreeBSD también incluye una extensa link:../where/[colección de packages] y link:../ports/[colección de ports] que ofrecen software precompilado y fácil de instalar. Existe también un grán número de link:../commercial/[aplicaciones comerciales] escritas para FreeBSD

Aquí tiene algunos ejemplos de los entornos en los que FreeBSD es usado:

* *Servicios Internet.* Muchos proveedores de Internet (ISPs) encuentran en FreeBSD la plataforma ideal para ofrecer servicios WWW, News, FTP, Email y otros. Software "Ready-to-run" como el servidor web http://www.apache.org/[Apache] o el servidor FTP http://proftpd.org/[ProFTPD] hacen realmente sencillo poner en marcha un servidor de servicios Internet. Por supuesto, con la potencia de link:../internet[networking] de FreeBSD, sus usuarios disfrutarán de alta velocidad y servicios fiables.
* *Estación de trabajo X Window.* Desde un barato terminal X hasta un avanzado monitor X, FreeBSD responde. Un software X está incluso (http://x.org/[X.Org](TM)). http://www.nvidia.com/[nVidia] ofrece controladores nativos para su hardware gráfico de alta potencia, y hay soporte de las librerías http://www.opengroup.org/motif/[Motif](R) y http://www.opengl.org/[OpenGL](R) que son las estándares indistriales. Ambos entornos de escritorio, http://www.kde.org[KDE] y http://www.gnome.org[GNOME] tienen soporte entero y estos ofrecen la funcionalided de un bulto de oficina con otras buenas funcionalidades accessibles en los productos http://www.openoffice.org/[OpenOffice.Org] y http://www.softmaker.de/tml_en.htm[TextMaker].
* *Networking.* Desde filtrado de paquetes hasta rutas o servicios de resolución de nombres, FreeBSD puede convertir cualquier PC en un excelente Firewall de Internet, servidor de correo, servidor de impresión, servidor PC/NFS y mucho más.
* *Desarrollo de software.* Cuenta con una suite de herramientas de desarrollo, incluyendo el compilador y debugger de GNU C/C++. Los desarrollos en p.ej. Java(TM) y Tcl/Tk también son posibles, pero lenguas más específicas como Icon funcionan también. Y las librerías compartidas siempre han sido fáciles de hacer y usar. Además, hay un surtido abundante de avanzados editores comuneros, como XEmacs y Vim.
* *Navegación por la red.* Una verdadera estación de trabajo UNIX(R) es una grán "embarcación" para la red, y la versión BSD de http://www.mozilla.org/products/firefox/[Firefox] y http://www.opera.com/[Opera] funciona bien en FreeBSD. Navegue, publique sus propias páginas, lea las News y envíe y reciba correo con un sistema FreeBSD en su máquina.
* *Educación e investigación*. FreeBSD es una excelente plataforma de investigación por que incluye el código fuente completo. Estudiantes e investigadores de sistemas operativos pueden beneficiarse enormemente de este sistema abierto y bién documentado.
* *Y mucho más.* Accounting, juegos de acción, bases de datos, visualización científica, vídeo conferencia, Internet Relay Chat (IRC), automatización del hogar, bbs's, escaneo de imágenes y más son todos usos reales de FreeBSD hoy.

== Un sistema operativo que colmará todas tus necesidades.

Aunque FreeBSD es un software libre, es un software _soportado por usuarios_. Cualquier pregunta que tenga puede ser enviada a cientos de desarrolladores de FreeBSD y usuarios a la lista de distribución freebsd-questions@FreeBSD.org.

FreeBSD tiene un completo grupo a nivel mundial de programadores y desarrolladores que se encargan de fijar los posibles bugs, añadir nuevas características y documentar el sistema. Soporte de nuevos dispositivos y opciones especiales se incluyen en el proceso de desarrollo constante, manteniendo una atención especial a los problemas que afectan a la estabilidad del sistema. Los usuarios de FreeBSD están soberbios del hecho, que su sistema no es sólo rápido, sino confiable también.

== Lo que dicen los expertos . . .

_"FreeBSD handles [our] heavy load quite well and it is nothing short of amazing. Salutations to the FreeBSD team."_

---Mark Hittinger, administrator of WinNet Communications, Inc.
