---
title: "Avances Tecnológicos de FreeBSD"
sidenav: about
---

= Avances Tecnológicos de FreeBSD

== FreeBSD ofrece diferentes características avanzadas.

No importa que aplicación quieras que use los recursos del sistema aprovechándolos al máximo. Las avanzadas características de FreeBSD se encargarán de ello.

== Un sistema operativo completo basado en 4.4BSD.

Las raices de FreeBSD derivan de la última release de software del Computer Systems Research Group de la Universidad de California, Berkeley. El libro _The Design and Implementation of 4.4BSD Operating System_, escrito por los arquitectos del sistema 4.4BSD, describe en detalle muchas de las funcionalidades del núcleo de FreeBSD.

Gracias al nivel y experiencia de diversos grupos de desarrolladores de todo el mundo, el proyecto FreeBSD ha trabajado para extender las características y posibilidades del sistema operativo 4.4BSD, consiguiendo en cada nueva release un sistema operativo más estable, rápido y conteniendo nuevas funcionalidades creadas a demanda de los usuarios.

== FreeBSD ofrece el más alto rendimiento, gran compatibilidad con otros sistemas operativos y una menor administración del sistema.

Los desarrolladores de FreeBSD se han enfrentado a algunos de los problemas más difíciles en el diseño de sistemas operativos para poder ofrecerte estas avanzadas características:

* *Bounce buffering* trata sobre la limitación en la arquitectura ISA de los PC's que limita el acceso directo a memoria en los primeros 16 megabytes.
+
_Resultado:_ sistemas con más de 16 megabytes operan más eficientemente con periféricos DMA en el bus ISA.
* *Un buffer de caché conjunto de memoria virtual y sistema de ficheros* continuamente ajusta la cantidad de memoria usada por los programas y el cache de disco.
+
_Resultado:_ los programas reciben una excelente gestión de memoria y un alto rendimiento en los accesos a disco, liberando al administrador del sistema del trabajo de ajustar los tamaños de los cachés.
* *Módulos de compatibilidad* que permiten la ejecución de programas de otros sistemas operativos en FreeBSD, incluyendo programas para Linux, SCO, NetBSD y BSDI.
+
_Resultado:_ los usuarios no tendrán que recompilar programas ya compilados para algunos de los sistemas compatibles, teniendo acceso a programas como las extensiones para BSDI de http://www.microsoft.com/FrontPage/[Microsoft FrontPage Server] o http://www.corel.com/products/unix/wpunix/index.htm[WordPerfect] para SCO y Linux.
* *Módulos de kernel de carga dinámica* que permiten tener acceso a nuevos sistemas de ficheros, protocolos de red o emuladores de binarios en tiempo de ejecución sin necesidad de generar un nuevo kernel.
+
_Resultado:_ Se puede ganar mucho tiempo y desarrolladores de terceras partes pueden ofrecer subsistemas completos como módulos de kernel sin necesidad de distribuir el código fuente o complejos procedimientos de instalación.
* *Librerías compartidas* reducen el tamaño de los programas, ahorrando espacio de disco y memoria. FreeBSD usa un avanzado esquema de librerías compartidas que ofrecen muchas de las ventajas de ELF, ofreciendo la versión actual compatibilidad ELF con programas de Linux y nativos de FreeBSD.

Naturalmente, cómo FreeBSD es un esfuerzo en constante evolución, puedes esperar nuevas características y niveles más altos de estabilidad con cada release.

== Lo que dicen los expertos . . .

_"FreeBSD has an outline-structured visual configuration editor ... you can enter the configuration of every device the OS supports and can therefore get a successful installation on the first try almost every time. IBM, Microsoft, and others would do well to emulate FreeBSD's approach."_

---Brett Glass, _Infoworld_, April 8 1996.
