---
title: "Contactando con FreeBSD"
sidenav: about
---

include::shared/es/urls.adoc[]

= Contactando con FreeBSD

== Preguntas sobre FreeBSD...

Las preguntas referentes a FreeBSD deberían ser enviadas a la lista de distribución freebsd-questions@FreeBSD.org.

Las link:https://www.FreeBSD.org/community/mailinglists/[listas de distribución] son el canal primario de soporte de los usuarios de FreeBSD, con numerosas listas cubriendo diferentes áreas. Diferentes listas en otros idiomas están disponibles.

== Preguntas sobre el contenido de este servidor WWW...

Las preguntas o sugerencias sobre nuestra documentación, (link:{handbook}[Handbook], link:{faq}[FAQ], link:../docs//[Libros y Articulos]) deberín ser enviadas a la lista de distribución freebsd-doc@FreeBSD.org.

== Correo, teléfono y fax

Para pedidos de CD-ROM: http://www.freebsdmall.com[The FreeBSD Mall]

Para soporte comercial: http://www.freebsdmall.com[The FreeBSD Mall]

== link:https://www.FreeBSD.org/administration/[Quién es responsable de qué]

Relaciones publicas & Enlace corporativo, oficial de seguridad, postmaster, webmaster, etc.
