---
title: "FreeBSD 12.1-RELEASE Installation Instructions"
sidenav: download
---

:releaseCurrent: "12.1-RELEASE"
:localRel: "12.1"

= FreeBSD {localRel}-RELEASE Installation Instructions

FreeBSD {releaseCurrent} Installation Instructions

== Abstract

This article gives some brief instructions on installing FreeBSD {releaseCurrent} and upgrading the systems running earlier releases.

== Table of Contents

* <<install,Installing FreeBSD>>
* <<upgrade,Upgrading FreeBSD>>

[[install]]
== Installing FreeBSD

The Installing FreeBSD chapter of the FreeBSD Handbook provides more in-depth information about the installation program itself, including a guided walk-through with screenshots.

[[upgrade]]
== Upgrading FreeBSD

If you are upgrading from a previous release of FreeBSD, please read upgrading section in the Release Notes for notable incompatibilities carefully.

[[upgrade-source]]
== Upgrading from Source

The procedure for doing a source code based update is described in Updating FreeBSD from Source.

For SVN use the releng/{localRel} branch which will be where any upcoming Security Advisories or Errata Notices will be applied.

[[upgrade-binary]]
== Upgrading Using "FreeBSD Update"

The {{< manpage "freebsd-update" "8">}} utility supports binary upgrades of i386 and amd64 systems running earlier FreeBSD releases. Systems running 11.3-RELEASE or 12.0-RELEASE can upgrade as follows:

[.screen]
----
# freebsd-update fetch
# freebsd-update install
----

Now the {{< manpage "freebsd-update" "8">}} utility can fetch bits belonging to {releaseCurrent}. During this process {{< manpage "freebsd-update" "8">}} will ask for help in merging configuration files.

[.screen]
----
# freebsd-update upgrade -r {localRel}-RELEASE
# freebsd-update install
----

The system must now be rebooted with the newly installed kernel before the non-kernel components are updated.

[.screen]
----
# shutdown -r now
----

After rebooting, {{< manpage "freebsd-update" "8">}} needs to be run again to install the new userland components:

[.screen]
----
# freebsd-update install
----

At this point, users of systems being upgraded from earlier FreeBSD releases will be prompted by {{< manpage "freebsd-update" "8">}} to rebuild all third-party applications (e.g., ports installed from the ports tree) due to updates in system libraries.

After updating installed third-party applications (and again, only if {{< manpage "freebsd-update" "8">}} printed a message indicating that this was necessary), run {{< manpage "freebsd-update" "8">}} again so that it can delete the old (no longer used) system libraries:

[.screen]
----
# freebsd-update install
----

Finally, reboot into {releaseCurrent}

[.screen]
----
# shutdown -r now
----

After rebooting, it is recommended to regenerate the pkg binary tool to prevent future issues when installing some applications using the pkg tool.

[.screen]
----
# pkg-static install -f pkg
----
