---
title: Előszó
prev: books/handbook/
next: books/handbook/parti
---

[preface]
[[book-preface]]
= Előszó
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums!:
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Tartalom
:table-caption: Táblázat
:figure-caption: Ábra
:example-caption: Példa
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:

[[preface-audience]]
== Kiknek szánjuk ezt a könyvet

A FreeBSD-t még nem ismerõk felfedezhetik, hogy a könyv elsõ része a FreeBSD telepítésének folyamatán vezeti keresztül a felhasználót, valamint érintõlegesen bemutatja az ezt alátámasztó UNIX(R)-os alapfogalmakat és szabályokat. Ennek a résznek a végigjárása nem kíván többet, csupán egy kis felfedezõ kedvet, illetve a menet közben bemutatott új fogalmak befogadását.

Ha túljutottunk rajta, a kézikönyv második, jóval terjedelmesebb része a FreeBSD-t használó rendszergazdák számára nyújt mindenféle témában minden részletre kiterjedõ referenciát. Ezek közül egyes fejezetek elvárnak némi elõzetes felkészülést, amelyet minden fejezet áttekintésében említeni is fogunk.

További információkért olvassuk át a crossref:bibliography[bibliography,Irodalomjegyzék]et.

[[preface-changes-from3]]
== Változtatások a harmadik kiadás óta

A kézikönyv jelenleg interneten elérhetõ változata számtalan önkéntes által az utóbbi 10 évben végzett együttes erõfeszítéseinek eredményeit tükrözi. A 2004-ben két kötetben megjelentetett harmadik kiadás óta a következõ fontosabb változások történtek:

* crossref:dtrace[dtrace,DTrace]: készült egy új fejezet a DTrace nevû teljesítmény-elemzõ eszközrõl.
* crossref:filesystems[filesystems,Támogatott állományrendszerek]: ebben a fejezetben a FreeBSD és a különbözõ más rendszerekhez fejlesztett állományrendszerek viszonyát mutatjuk be, többek a Sun(TM) ZFS megoldását.
* crossref:audit[audit,Biztonsági események vizsgálata]: ez a fejezet FreeBSD új biztonsági fejlesztéseit foglalja össze és mutatja be a használatukat.
* crossref:virtualization[virtualization,Virtualizáció]: ebben az új fejezetben a FreeBSD rendszerhez és rajta elérhetõ különbözõ virtualizációs technológiákról szólunk.

[[preface-changes-from2]]
== Változtatások a második kiadás (2004) óta

A harmadik kiadás a FreeBSD Dokumentációs Projekt tagjainak két évi kemény munkájának gyümölcse. A nyomtatott változat már olyan nagyra nõtt, hogy két külön kötetben kellett kiadnunk. Az alábbi fontosabb változtatások jelentek meg ebben az új kiadásban:

* crossref:config[config-tuning,Beállítás és finomhangolás]: a beállításra és finomhangolásra vonatkozó részeket bõvítettük az ACPI energia- és erõforrás gazdálkodásról szóló részekkel, a `cron` rendszerprogrammal, illetve még több, a rendszermag finomhangolását elõsegítõ opció leírásával.
* crossref:security[security,Biztonság]: a biztonságról szóló részt bõvítettük a virtuális magánhálózatokról (VPN-ekrõl), állományrendszeri hozzáférés-vezérlési listákról (ACL-ek) szóló elemekkel, valamint biztonságtechnikai tanácsokkal.
* crossref:mac[mac,Kötelező hozzáférés-vezérlés (MAC)]: a kötelezõ hozzáférés-vezérlésrõl (MAC-rõl) szóló fejezet teljesen új ebben a kiadásban. Bemutatja, mi is az a MAC és hogyan hasznosítható egy FreeBSD-s rendszer biztonságossá tételében.
* crossref:disks[disks,Háttértárak]: a háttértárakat tartalmazó részt bõvítettük az USB-tárakról, állományrendszeri pillanatképeirõl, lemezkvótákról, állomány- és hálózat alapú állományrendszerekrõl, továbbá a titkosított partíciókról szóló részekkel.
* crossref:vinum[vinum-vinum,A Vinum kötetkezelő]: a Vinum egy új fejezet ebben a kiadásban. Bemutatja a Vinum logikaikötet-kezelõ használatát, aminek segítségével eszközfüggetlen módon hozhatunk létre logikai lemezeket, szoftveres RAID-0, RAID-1 és RAID-5 konfigurációkat.
* Bekerült egy hibaelhárításról szóló rész a crossref:ppp-and-slip[ppp-and-slip,A PPP és a SLIP] PPP és SLIP leírásához.
* crossref:mail[mail,Elektronikus levelezés]: az elektronikus levelezést ismertetõ részt bõvítettük a különféle levéltovábbító rendszerekrõl, az SMTP hitelesítésrõl, UUCP protokollról, a fetchmail és procmail programokról szóló elemekkel, valamint egyéb, haladókat megcélzó témákkal.
* crossref:network-servers[network-servers,Hálózati szerverek]: a hálózati szervereket ismertetõ rész egy teljesen új fejezet ebben a kiadásban. Benne megtalálható az Apache HTTP szerver, az ftpd szerver, illetve a Microsoft(R) Windows(R)-os kliensek számára megfelelõ Samba szerver beállítása. Az érthetõség kedvéért egyes részek átkerültek ide a crossref:advanced-networking[advanced-networking,Egyéb haladó hálózati témák], vagyis a haladó hálózati témákat tárgyaló fejezetbõl.
* crossref:advanced-networking[advanced-networking,Egyéb haladó hálózati témák]: a haladó hálózati témákat tartalmazó részt kiegészítettük a FreeBSD és a Bluetooth(R) eszközök kapcsolatáról, a vezeték nélküli hálózatokról és az aszinkron adatátvitel módról (ATM-rõl) szóló ismeretekkel.
* Létrehoztunk egy szójegyzéket abból a célból, hogy a könyvben használt definíciók és szakkifejezések egyetlen központi helyen össze legyenek foglalva.
* Számos esztétikai javítást eszközöltünk a könyvben található ábrákon és táblázatokon.

[[preface-changes]]
== Változtatások az elsõ kiadás (2001) óta

A második kiadás a FreeBSD Dokumentációs Projekt tagjainak két évi komoly munkájának eredménye. Az alábbi fontosabb változtatások jelennek meg ebben a kiadásban:

* Bekerült egy teljes tárgy- és névmutató.
* Mindegyik ASCII-ábrát grafikusak váltották fel.
* Mindegyik fejezet elejére odakerült egy általános áttekintés, ami egy rövid összefoglalást ad a fejezet tartalmáról, valamint közli az elolvasásához szükséges ismereteket.
* A tartalmat felosztottuk logikailag három részre: "Bevezetés", "Rendszeradminisztráció" és "Függelék".
* A crossref:install[install,A FreeBSD telepítése]et ("A FreeBSD telepítése") teljesen újraírtuk és sok-sok illusztráció is hozzáadásra került a könnyebb megértés érdekében.
* A crossref:basics[basics,A UNIX alapjai] ("A UNIX(R) alapjai") kiegészült a futó programokról, démonokról és jelzésekrõl szóló további hasznos információkkal.
* A crossref:ports[ports,Alkalmazások telepítése. csomagok és portok]et ("Alkalmazások telepítése") bõvítettük a bináris csomagkezelésrõl szóló további ismeretekkel.
* A crossref:x11[x11,Az X Window System] ("Az X Window System") teljes újraíráson ment át, aminek folyamán igyekeztünk nagyobb hangsúlyt helyezni a modern asztali technológiák, mint pl. a KDE és GNOME XFree86(TM) 4.X-en történõ használatának leírására.
* A crossref:boot[boot,A FreeBSD rendszerindítási folyamata] ("A FreeBSD rendszerindítási folyamata") kibõvült.
* A crossref:disks[disks,Háttértárak] ("Háttértárak") két, korábban külön levõ fejezet, a "Lemezek" és "Biztonsági mentések" összeolvasztásából jött létre. Úgy éreztük, a bennük helyet kapott témákat sokkal könnyebb úgy megérteni, ha egyetlen fejezetben tárgyaljuk ezeket. Egy (hardveres és szoftveres) RAID-rõl szóló rész is belekerült.
* A crossref:serialcomms[serialcomms,Soros vonali kommunikáció] ("Soros vonali kommunikáció") teljes átszervezésre került, valamint a FreeBSD 4.X/5.X verziókhoz igazítottuk.
* A crossref:ppp-and-slip[ppp-and-slip,A PPP és a SLIP] ("A PPP és a SLIP") lényegesen sokat fejlõdött.
* Számos új rész került a crossref:advanced-networking[advanced-networking,Egyéb haladó hálózati témák]be ("Egyéb haladó hálózati témák").
* A crossref:mail[mail,Elektronikus levelezés] ("Elektronikus levelezés") kibõvült a sendmail beállításáról tartalmazó újabb információkkal.
* A crossref:linuxemu[linuxemu,Bináris Linux kompatibilitás] ("Bináris Linux kompatibilitás") kiegészült az Oracle(R) és a SAP(R) R/3(R) telepítését bemutató részekkel.
* Az alábbi új témák kerültek tárgyalásra a második kiadásban:

** Beállítás és finomhangolás (crossref:config[config-tuning,Beállítás és finomhangolás])
** Multimédia (crossref:multimedia[multimedia,Multimédia])

[[preface-overview]]
== A könyv felépítése

A könyvet négy logikailag elkülönülõ részre osztottuk fel. Az elsõ, _Bevezetés_ címû részben bemutatjuk a FreeBSD telepítését és használatának alapjait. Elgondolásunk szerint az itt szereplõ fejezeteket sorban érdemes elolvasni, esetenként kihagyni azokat, amelyek már az olvasó számára ismert témákat dolgoznak fel. A második, _Gyakori feladatok_ címû részben megismerhetjük a FreeBSD néhány gyakorta használt lehetõségét. Ez a rész, valamint az ezt követõ összes többi tetszõleges sorrendben olvasható. Mindegyik fejezet egy rövidke összefoglalással kezdõdik, amely ismerteti, az olvasótól milyen jellegû tapasztalatokat vár el a fejezet megértése. Célja, hogy segítsen az olvasónak megtalálni a számára érdekes témákat. A harmadik, _Rendszeradminisztráció_ címû részben rendszergazdai feladatokat tárgyalunk. A negyedik, _Hálózati kommunikáció_ címû részben hálózatok és szerverek üzemeltetésével kapcsolatos ismereteket foglaltunk össze. Végül, az ötödik rész tartalmazza a függeléket és az irodalomjegyzéket, hivatkozásokat.

_crossref:introduction[introduction,	Bemutatkozás]: Bemutatkozás_::
A FreeBSD bemutatkozik az új felhasználóknak. Szó esik a FreeBSD Projekt történetérõl, célkitûzéseirõl és a fejlesztési modelljérõl.

_crossref:install[install,A FreeBSD telepítése]: A FreeBSD telepítése_::
Végigvezetjük a felhasználót a telepítési folyamat egészén. Bizonyos rendhagyó kérdések, mint például a soros konzolon keresztül történõ telepítés is terítékre kerülnek.

_crossref:basics[basics,A UNIX alapjai]: A UNIX(R) alapjai_::
Sorra vesszük a FreeBSD operációs rendszer alapvetõ parancsait és lehetõségeit. Amennyiben már jártasak vagyunk valamilyen szinten a Linux(R) vagy más UNIX(R)-típusú rendszerek használatában, nyugodtan kihagyhatjuk ezt a fejezetet.

_crossref:ports[ports,Alkalmazások telepítése. csomagok és portok]: Alkalmazások telepítése, csomagok és portok_::
Megismerhetjük, miként tudunk külsõ cégek által fejlesztett alkalmazásokat telepíteni a FreeBSD "Portgyûjteményének" (FreeBSD Ports Collection) vagy a megszokott bináris csomagok használatán keresztül.

_crossref:x11[x11,Az X Window System]: Az X Window System_::
Általános bemutatásra kerül az X Window System, valamint az X11 használata a FreeBSD-n. Ezenkívül olvashatunk az elterjedtebb munkakörnyezetekrõl, mint pl. a KDE és a GNOME.

_crossref:desktop[desktop,Asztali alkalmazások]: Asztali alkalmazások_::
Felsoroljuk az ismertebb asztali alkalmazásokat: webböngészõket és alkalmazói programcsomagokat, és bemutatjuk, hogyan telepítsük ezeket FreeBSD-re.

_crossref:multimedia[multimedia,Multimédia]: Multimédia_::
Megtudhatjuk, hogyan állítsuk be a zene- és videolejátszást rendszerünkön. Emellett olvashatunk néhány multimédiás alkalmazás használatáról is.

_crossref:kernelconfig[kernelconfig,A FreeBSD rendszermag testreszabása]: A FreeBSD rendszermag testreszabása_::
Kifejtjük, miért lehet szükségünk egy új rendszermag konfigurálására, és részletesen végigjárjuk egy rendszermag konfigurációjának, fordításának és telepítésének lépéseit.

_crossref:printing[printing,Nyomtatás]: Nyomtatás_::
Ismertetjük, hogyan lehet nyomtatókat használni FreeBSD alatt, beleértve a munkalapok készítésének mikéntjét, a nyomtatóhasználat nyilvántartását és a kezdeti beállításokat.

_crossref:linuxemu[linuxemu,Bináris Linux kompatibilitás]: Bináris Linux kompatibilitás_::
Megismerhetjük a FreeBSD bináris Linux kompabilitásához kapcsolódó lehetõségeket. Ezenfelül részletekre is kitérõ telepítési útmutatót találhatunk különbözõ népszerû linuxos alkalmazásokhoz, mint például az Oracle(R), SAP(R) R/3(R) és a Mathematica(R).

_crossref:config[config-tuning,Beállítás és finomhangolás]: Beállítás és finomhangolás_::
Megismerhetjük a FreeBSD azon paramétereit, amelyek megfelelõ állításával a rendszergazdák a lehetõ legtöbbet képesek kihozni FreeBSD rendszerükbõl. Ezenkívül bemutatásra kerül a FreeBSD-ben használt számos konfigurációs állomány, valamint hogy ezeket hol találhatjuk meg.

_crossref:boot[boot,A FreeBSD rendszerindítási folyamata]: A FreeBSD rendszerindítási folyamata_::
Tartalmazza a FreeBSD rendszerindítási folyamatának leírását, és elmagyarázza, miként lehet ezt vezérelni a konfigurációs beállítások segítségével.

_crossref:users[users,Felhasználók és hozzáférések alapvető kezelése]: Felhasználók és hozzáférések alapvetõ kezelése_::
Bemutatja a felhasználói fiókok létrehozását és kezelését. Emellett megemlíti a felhasználókra érvényesíthetõ erõforrás-megszorításokat, illetve egyéb fiókkezelési feladatokat.

_crossref:security[security,Biztonság]: Biztonság_::
Bemutatásra kerül a FreeBSD rendszerünk biztonságossá tételére alkalmas számos különféle eszköz, többek közt a Kerberos, IPsec és az OpenSSH.

_crossref:jails[jails,A jail alrendszer]_: A jail alrendszer_::
Megtudhatjuk, hogyan mûködik az alkalmazások elszigeteléséért felelõs jail alrendszer, valamint miben emelkedik ki a FreeBSD-ben is megtalálható hagyományos "chroot" megoldással szemben.

_crossref:mac[mac,Kötelező hozzáférés-vezérlés (MAC)]: Kötelezõ hozzáférés-vezérlés_::
Megismerhetjük a kötelezõ hozzáférés-vezérlést (MAC-et), valamint azt, hogyan is tudjuk felhasználni egy FreeBSD-s rendszer biztonsága érdekében.

_crossref:audit[audit,Biztonsági események vizsgálata]: Biztonsági események vizsgálata_::
Kiderül, mit jelent a FreeBSD-ben az események vizsgálata, illetve mindez hogyan telepíthetõ, konfigurálható és miként tudjuk a vizsgálatok adatait kielemezni vagy felügyelni.

_crossref:disks[disks,Háttértárak]: Háttértárak_::
Bemutatásra kerül, miként kezelhetjük a háttértárolókat és állományrendszereket a FreeBSD-ben. Ide tartoznak a fizikai lemezek, RAID-tömbök, optikai és szalagos egységek, memória alapú lemezek és a hálózati állományrendszerek.

_crossref:geom[geom,GEOM. a moduláris lemezszervező rendszer]: GEOM, a moduláris lemezszervezõ rendszer_::
Megismerhetjük a FreeBSD-ben jelenlevõ GEOM alrendszert és az általa támogatott különbözõ RAID-szintek beállítását.

_crossref:filesystems[filesystems,Támogatott állományrendszerek]: Támogatott állományrendszerek_::
A FreeBSD operációs rendszer számára nem natív állományrendszerekkel foglalkozik, például a Sun(TM) Z állományrendszerével.

_crossref:vinum[vinum-vinum,A Vinum kötetkezelő]: A Vinum kötetkezelõ_::
Megtudhatjuk, hogyan használjuk a Vinumot, a logikaikötet-kezelõt, amely eszközfüggetlen logikai lemezeket, szoftveres RAID-0, RAID-1 és RAID-5 konfigurációkat biztosít.

_crossref:virtualization[virtualization,Virtualizáció]: Virtualizáció_::
Tartalmazza a virtualizációs rendszerek által felkínált lehetõségek bemutatását és használatát a FreeBSD-vel.

_crossref:l10n[l10n,Honosítás. Az I18N/L10N használata és beállítása]: Honosítás, az I18N/L10N használata és beállítása_::
Bemutatja, hogyan használjuk a FreeBSD-t a rendszer és az alkalmazások szintjén az angoltól eltérõ nyelveken.

_crossref:cutting-edge[updating-upgrading,A FreeBSD frissítése és frissen tartása]: A FreeBSD frissítése és frissen tartása_::
Elmagyarázza, mik az alapvetõ különbségek a FreeBSD-STABLE, FreeBSD-CURRENT verziók, valamint a FreeBSD kiadások között. Bemutatja, mely felhasználók lehetnek azok, akik a legtöbbet tudnak profitálni egy fejlesztõi rendszer használatából, illetve körvonalazza ennek folyamatát. Továbbá röviden összefoglalja azokat az eszközöket, amelyekkel a felhasználók frissíthetik a rendszerüket a biztonsági és kritikus hibák javításakor.

_crossref:dtrace[dtrace,DTrace]: DTrace_::
A Sun(TM) DTrace eszközének beállítását és használatát mutatja be. A segítségével megvalósított dinamikus nyomkövetéssel lehetõségünk nyílik valós idejû elemzéseken keresztül felderíteni a különbözõ teljesítménybeli problémákat.

_crossref:serialcomms[serialcomms,Soros vonali kommunikáció]: Soros vonali kommunikáció_::
Kifejti, hogyan csatlakoztassunk terminált vagy modemet a FreeBSD rendszerünkhöz, ha behívó vagy betárcsázós kapcsolatot szeretnénk létrehozni.

_crossref:ppp-and-slip[ppp-and-slip,A PPP és a SLIP]: A PPP és a SLIP_::
Bemutatja, miként tudjuk PPP-n, SLIP-en és Etherneten keresztüli PPP-vel (PPPoE) összekapcsolni a FreeBSD-t távoli rendszerekkel.

_crossref:mail[mail,Elektronikus levelezés]: Elektronikus levelezés_::
Megismerhetjük egy elektronikus levelezõ szerver különféle komponenseit, és elmélyedhetünk az egyik leghíresebb levelezõszerver-szoftver, a sendmail használatában és felületesebb konfigurálásában.

_crossref:network-servers[network-servers,Hálózati szerverek]: Hálózati szerverek_::
Részletekbe menõen és konfigurációs példákkal mutatja be, miként tudunk hálózati állományrendszer kiszolgálónak, névszervernek, hálózati információs rendszer kiszolgálónak vagy idõszinkronizációs szervernek beállítani egy FreeBSD-s számítógépet.

_crossref:firewalls[firewalls,Tűzfalak]: Tûzfalak_::
Kifejti a szoftveres tûzfalak mögött álló filozófiát, valamint részletesen tárgyalja a különbözõ, FreeBSD-n elérhetõ tûzfalak konfigurációját.

_crossref:advanced-networking[advanced-networking,Egyéb haladó hálózati témák]: Egyéb haladó hálózati témák_::
Feldolgoz számos hálózati témát, beleértve az internet kapcsolat helyi hálózaton (LAN-on) keresztül történõ megosztását több számítógép között, haladó forgalomirányítási kérdéseket, vezeték nélküli hálózatok beállítását, Bluetooth(R), ATM, IPv6 és sok minden mással kapcsolatos információkat.

_crossref:mirrors[mirrors,A FreeBSD beszerzése]: A FreeBSD beszerzése_::
Felsorolja azokat a forrásokat, ahonnan a FreeBSD CD-n vagy DVD-n beszerezhetõ, valamint azokat a honlapokat, ahonnan letölthetõ vagy telepíthetõ a FreeBSD.

_crossref:bibliography[bibliography,Irodalomjegyzék]: Irodalomjegyzék_::
A könyv sok tekintetben olyan témákat is érint, amelyek felkelthetik az olvasó érdeklõdését és ezek kapcsán bõvebb magyarázatra vágyik. Az irodalomjegyzékben ezért összeírtunk számos remek könyvet, amelyekre hivatkozunk is a fejezetekben.

_crossref:eresources[eresources,Források az interneten]: Erõforrások az interneten_::
Tartalmazza a FreeBSD felhasználók számára elérhetõ azon fórumokat, ahová beküldhetik kérdéseiket, illetve szakmai jellegû társalgásokat folytathatnak.

_crossref:pgpkeys[pgpkeys,PGP-kulcsok]: PGP-kulcsok_::
Az egyes FreeBSD fejlesztõk PGP-kulcsait sorolja fel.

[[preface-conv]]
== A könyvben alkalmazott konvenciók

A könnyebb és egységesebb olvashatóság kedvéért az alábbi konvenciókat igyekeztünk követni a könyvben.

[[preface-conv-typographic]]
=== Tipográfiai konvenciók

_Dõlt_::
A _dõlt_ betûket állománynevek, URL-ek, kiemelt szövegek és a szakmai kifejezések elsõ elõfordulásakor használjuk.

`Írógépszerû`::
Az `írógépszerû` betûket hibaüzenetek, parancsok, környezeti változók, portok, számítógépek, felhasználók, csoportok, eszközök nevei, változók és kódrészletek esetén használjuk.

Félkövér::
A félkövér betûket alkalmazások, parancsok és billentyûk megnevezésénél használjuk.

[[preface-conv-commands]]
=== Felhasználói bevitel

A billentyûket *félkövérrel* írjuk, hogy kiemelkedjenek a szöveg többi részébõl. Az egyszerre megnyomni kívánt billentyûk kombinációját a `+` jelöléssel adjuk meg, mint például:

kbd:[Ctrl+Alt+Del]

Ez azt jelenti, hogy a felhasználónak a kbd:[Ctrl], kbd:[Alt] és kbd:[Del] billentyûket egyszerre kell lenyomnia.

Azokat a billentyûket, amelyeket egymás után kell lenyomni, vesszõvel választjuk el, például:

kbd:[Ctrl+X], kbd:[Ctrl+S]

Ez tehát azt jelenti, hogy a felhasználónak elõször a kbd:[Ctrl] és kbd:[X] billentyûket, majd a kbd:[Ctrl] és kbd:[S] billentyûket kell egyszerre lenyomnia.

[[preface-conv-examples]]
=== Példák

A [.filename]#E:\># kijelzéssel kezdõdõ példák egy MS-DOS(R) parancsot jelölnek. Ha másképpen nem említjük, ezeket a parancsokat a modern Microsoft(R) Windows(R)-okban található "Parancssorból" kell kiadni.

[source,bash]
....
E:\> tools\fdimage floppies\kern.flp A:
....

A # kijelzéssel kezdõdõ példák a FreeBSD-ben rendszeradminisztrátori jogokat igénylõ parancsok kiadását jelentik. Ehhez bejelentkezhetünk a `root` felhasználóval, vagy felvethetjük a rendszeradminisztrátori jogokat a saját felhasználói fiókunkból a man:su[1] használatával is.

[source,bash]
....
# dd if=kern.flp of=/dev/fd0
....

A % kijelzéssel kezdõdõ példák olyan parancsra utalnak, amelyeket egy normál felhasználói fiókból érdemes kiadni. Hacsak másképpen nem jelezzük, a C-shell szintaxisát használjuk a környezeti változók és egyéb parancsok megadásakor.

[source,bash]
....
% top
....

[[preface-acknowledgements]]
== Köszönetnyilvánítás

A könyv, amit itt most olvashatunk, több száz ember együttes munkájának eredménye a világ minden tájáról. Akár csak elgépeléseket javítottak, vagy komplett fejezeket adtak hozzá, minden hozzájárulás hasznosnak bizonyult.

Emellett sok cég anyagilag is támogatta a könyv fejlõdését, lehetõvé téve ezáltal, hogy a szerzõk teljes munkaidõben dolgozhassanak rajta, pénzt kapjanak az írásaikért stb. Leginkább a BSDi (amelyet késõbb felvásárolt a http://www.windriver.com[Wind River Systems]) adott teljes munkaidõs fizetést a FreeBSD Dokumentációs Projekt tagjainak a könyv gondozásához, amely végül az elsõ nyomtatott kiadás megjelentetéséhez vezetett 2000 márciusában (ISBN 1-57176-241-8). A Wind River Systems ezt követõen további szerzõket is finanszírozott a nyomtatási-szedési infrastruktúra továbbfejlesztéséhez és a könyv tartalmának bõvítéséhez. Ennek eredménye lett a második nyomtatott kiadás, amely 2001 novemberében jelent meg (ISBN 1-57176-303-1). 2003 - 2004 folyamán a http://www.freebsdmall.com[FreeBSD Mall, Inc.] támogatott anyagilag számos hozzájárulót a kézikönyvet illetõ munkájáért, a harmadik nyomtatott kiadásra történõ elõkészítésben.
