=== FreeBSD Foundation

Links: +
link:https://www.freebsdfoundation.org[FreeBSD Foundation] URL: link:https://www.freebsdfoundation.org[https://www.freebsdfoundation.org] +
link:https://freebsdfoundation.org/blog/technology-roadmap/[Technology Roadmap] URL: link:https://freebsdfoundation.org/blog/technology-roadmap/[https://freebsdfoundation.org/blog/technology-roadmap/] +
link:https://www.freebsdfoundation.org/donate/[Donate] URL: link:https://www.freebsdfoundation.org/donate/[https://www.freebsdfoundation.org/donate/] +
link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[Foundation Partnership Program] URL: link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/] +
link:https://www.freebsdfoundation.org/journal/[FreeBSD Journal] URL: link:https://www.freebsdfoundation.org/journal/[https://www.freebsdfoundation.org/journal/] +
link:https://www.freebsdfoundation.org/news-and-events/[Foundation News and Events] URL: link:https://www.freebsdfoundation.org/news-and-events/[https://www.freebsdfoundation.org/news-and-events/]

Contact: Deb Goodkin <deb@FreeBSDFoundation.org>

The FreeBSD Foundation is a 501(c)(3) non-profit organization dedicated to supporting and promoting the FreeBSD Project and community worldwide.
Donations from individuals and corporations are used to fund and manage software development projects, conferences, and developer summits.
We also provide travel grants to FreeBSD contributors, purchase and support hardware to improve and maintain FreeBSD infrastructure, and provide resources to improve security, quality assurance, and release engineering efforts.
We publish marketing material to promote, educate, and advocate for the FreeBSD Project, facilitate collaboration between commercial vendors and FreeBSD developers, and finally, represent the FreeBSD Project in executing contracts, license agreements, and other legal arrangements that require a recognized legal entity.

==== Fundraising Efforts

Thank you to everyone who made a financial contribution in 2022!
We're still tallying up the totals and will have final numbers soon.
Unfortunately, we did not meet our fundraising goal, which reinforced our need of having someone who can focus on encouraging organizations to invest in FreeBSD.
We will bring someone on board soon to help with that effort.

In this Quarterly Status report you'll read about many of the areas we funded in Q4 to improve FreeBSD and advocate for the Project (the two main areas we spend money on).
Check out reports on the internally and externally funded projects like Openstack on FreeBSD, Enabling Snapshots on Filesystems Using Journaled Soft Updates, FreeBSD as a Tier 1 cloud-init Platform, and FreeBSD/riscv64 Improvements.
In addition, we provided tons of community engagement and education opportunities virtually and in-person!

If you want to help us continue our efforts, please consider making a donation towards our 2023 fundraising campaign!
link:https://www.freebsdfoundation.org/donate/[https://www.freebsdfoundation.org/donate/]

We also have a Partnership Program for larger commercial donors.
You can read about it at link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/].

==== OS Improvements

During the last quarter of 2022, 218 src, 45 ports, and 12 doc tree commits identified the Foundation as a sponsor.
Work was committed under Foundation sponsorship to repositories outside of FreeBSD as well, e.g., to the cloud-init project.
Some of this sponsored work is described in separate report entries:

* FreeBSD as a Tier 1 cloud-init Platform
* OpenStack on FreeBSD project update
* Wireless Report
* Enabling Snapshots on Filesystems Using Journaled Soft Updates

Other Foundation work in the src tree included:

- a variety of additions and fixes from Konstantin Belousov including commits to the virtual memory system (e.g., link:https://cgit.freebsd.org/src/commit/?id=ec201dddfbddd3a77dd3f3afc9b007d0e13e7ad1[ec201dd], link:https://cgit.freebsd.org/src/commit/?id=cd086696c2cb6d23bac3bc749836d36a9280ae98[cd08669], and link:https://cgit.freebsd.org/src/commit/?id=d537d1f12e8829faccd395115193b03b578f1176[d537d1f]), and file systems (e.g., link:https://cgit.freebsd.org/src/commit/?id=37aea2649ff707f23d35309d882b38e9ac818e42[37aea26], link:https://cgit.freebsd.org/src/commit/?id=83aff0f08c525ea3c394f3dd6598665cd369d53c[83aff0f], link:https://cgit.freebsd.org/src/commit/?id=860399eb86cc431412bfbce0ab76c6652e5b6c07[860399e], and link:https://cgit.freebsd.org/src/commit/?id=4d903a1a74d9526aba4d177e89c10f97df5662f2[4d903a1])
- work from Andrew Turner on arm64 such as link:https://cgit.freebsd.org/src/commit/?id=c15085278cb55bd3c1ea252adf5635bb6800b431[an implementation of per-superpage locks] and link:https://cgit.freebsd.org/src/commit/?id=969935b86b179b2b517ab5d35d943fcb761203c1[the addition of support for an array of hwresets]
- more RISC-V improvements from Mitchell Horne, including link:https://cgit.freebsd.org/src/commit/?id=701923e2a4105be606c5263181b6eb6f546f1a84[improvements to parsing of ISA property strings], link:https://cgit.freebsd.org/src/commit/?id=95b1c27069775dd969cd045888b4ea5aeb53cb7f[optimizations to memory allocation], and various documentation additions and improvements
- follow-up commits to Mark Johnston's work to add ZFS Support to makefs(8) (e.g., link:https://cgit.freebsd.org/src/commit/?id=89585511cc052643a774f64f6450d18e7dd51d4a[work to easily provide ZFS-based VM and cloud images] and link:https://cgit.freebsd.org/src/commit/?id=72a1cb05cd230ce0d12a7180ae65ddbba2e0cb6d[automation for better defaults] from Li-Wen Hsu)
- a variety of work from Ed Maste, including link:https://cgit.freebsd.org/src/commit/?id=38a52bd3b5cac3da6f7f6eef3dd050e6aa08ebb3[an ssh update] and link:https://cgit.freebsd.org/src/commit/?id=86edb11e7491e657e6c75ef6814867021665c377[a switch to LLVM objdump].

==== Continuous Integration and Quality Assurance

The Foundation provides a full-time staff member and funds projects to improve continuous integration, automated testing, and overall quality assurance efforts for the FreeBSD project.
You can read about the latest activity for that work in a separate report entry.

==== FreeBSD Advocacy and Education

Much of our effort is dedicated to Project advocacy.
This may involve highlighting interesting FreeBSD work, producing literature and video tutorials, attending events, or giving presentations.
The goal of the literature we produce is to teach people FreeBSD basics and help make their path to adoption or contribution easier.
Other than attending and presenting at events, we encourage and help community members run their own FreeBSD events, give presentations, or staff FreeBSD tables.

The FreeBSD Foundation sponsors many conferences, events, and summits around the globe.
These events can be BSD-related, open source, or technology events geared towards underrepresented groups.
We support the FreeBSD-focused events to help provide a venue for sharing knowledge, working together on projects, and facilitating collaboration between developers and commercial users.
This all helps provide a healthy ecosystem.
We support the non-FreeBSD events to promote and raise awareness of FreeBSD, to increase the use of FreeBSD in different applications, and to recruit more contributors to the Project.
We are continuing to attend events both in person and virtual as well as planning the November Vendor Summit.
In addition to attending and planning virtual events, we are continually working on new training initiatives and updating our selection of link:https://freebsdfoundation.org/freebsd-project/resources/[how-to guides] to facilitate getting more folks to try out FreeBSD.

Check out some of the advocacy and education work we did last quarter:

* Sponsored the OpenZFS Developer Summit, October 24-25, 2022 in San Francisco, CA

* Sponsored All Things Open, October 30-November 2, 2022 in Raleigh, NC

* Sponsored and helped organize the November 2022 FreeBSD Vendor Summit.
link:https://youtube.com/playlist?list=PLugwS7L7NMXwVfBq5eDRky450jp7LTRJj[Videos from the Summit are available].

* Held a new FreeBSD Friday: link:https://youtu.be/t2VLTtHYIcA[An Introduction to FreeBSD Services] by Drew Gurkowski

* Published the link:https://freebsdfoundation.org/news-and-events/newsletter/freebsd-foundation-fall-2022-update/[Fall] and link:https://freebsdfoundation.org/news-and-events/newsletter/11982/[Winter] Newsletter updates

* New Blog Posts

** link:https://freebsdfoundation.org/blog/meet-the-2022-freebsd-google-summer-of-code-students-koichi-imai/[Meet the 2022 FreeBSD Google Summer of Code Students: Koichi Imai]
** link:https://freebsdfoundation.org/blog/meet-the-2022-freebsd-google-summer-of-code-students-bojan-novkovic/[Meet the 2022 FreeBSD Google Summer of Code Students: Bojan Novković]
** link:https://freebsdfoundation.org/blog/keeping-freebsd-secure-learn-the-whys-and-hows-with-the-freebsd-sec-team/[Keeping FreeBSD Secure: Learn the Whys and Hows with the FreeBSD Sec Team]
** link:https://freebsdfoundation.org/blog/the-freebsd-journal-is-still-free/[The FreeBSD Journal is still Free!]
** link:https://freebsdfoundation.org/blog/eurobsdcon-2022-trip-report-muhammad-moinur-rahman/[EuroBSDCon 2022 Trip Report: Muhammad Moinur Rahman]
** link:https://freebsdfoundation.org/blog/eurobsdcon-2022-trip-report-patrick-mcevoy/[EuroBSDCon 2022 Trip Report: Patrick McEvoy]
** link:https://freebsdfoundation.org/blog/fall-foundation-software-development-update/[Fall Foundation Software Development Update]
** link:https://freebsdfoundation.org/blog/invest-in-freebsd/[Invest in FreeBSD]
** link:https://freebsdfoundation.org/blog/2022-in-review-advocacy/[2022 in Review: Advocacy]
** link:https://freebsdfoundation.org/blog/foundation-sponsors-update-to-wireguard-kernel-port-for-freebsd/[Foundation Sponsors Update to WireGuard Kernel Port for FreeBSD]
** link:https://freebsdfoundation.org/blog/2022-in-review-fundraising-update/[2022 in Review: Fundraising Update]
** link:https://freebsdfoundation.org/blog/2022-in-review-software-development/[2022 in Review: Software Development]
** link:https://freebsdfoundation.org/blog/2022-in-review-continuous-integration-and-quality-assurance-update/[2022 in Review: Continuous Integration and Quality Assurance Update]

* FreeBSD in the news:

** link:https://freebsdfoundation.org/news-and-events/latest-news/ampere-getting-cloud-native-with-freebsd-on-oci-ampere-a1-with-terraform/[Ampere: Getting Cloud-Native with FreeBSD on OCI Ampere A1 with Terraform]
** link:https://freebsdfoundation.org/news-and-events/latest-news/freebsd-is-well-supported-on-4th-gen-amd-epyc-processors/[FreeBSD is Well Supported on 4th Gen AMD EPYC™ Processors]

* For a quick review of all the Foundation efforts in 2022, check out our link:https://youtu.be/6ybbeFXFm-I[2022 Thank You Video].

We help educate the world about FreeBSD by publishing the professionally produced FreeBSD Journal.
As we mentioned previously, the FreeBSD Journal is now a free publication.
Find out more and access the latest issues at link:https://www.freebsdfoundation.org/journal/[https://www.freebsdfoundation.org/journal/].

You can find out more about events we attended and upcoming events at link:https://www.freebsdfoundation.org/news-and-events/[https://www.freebsdfoundation.org/news-and-events/].

==== Legal/FreeBSD IP

The Foundation owns the FreeBSD trademarks, and it is our responsibility to protect them.
We also provide legal support for the core team to investigate questions that arise.

Go to link:https://www.freebsdfoundation.org[https://www.freebsdfoundation.org] to find more about how we support FreeBSD and how we can help you!
