=== Ports Collection

Links: +
link:https://www.FreeBSD.org/ports/[About FreeBSD Ports] URL: link:https://www.FreeBSD.org/ports/[https://www.FreeBSD.org/ports/] +
link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[Contributing to Ports] URL: link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[https://docs.freebsd.org/en/articles/contributing/#ports-contributing] +
link:http://portsmon.freebsd.org/[FreeBSD Ports Monitoring] URL: link:http://portsmon.freebsd.org/[http://portsmon.freebsd.org/] +
link:https://www.freebsd.org/portmgr/[Ports Management Team] URL: link:https://www.freebsd.org/portmgr/[https://www.freebsd.org/portmgr/] +
link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[Ports Tarball] URL: link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[http://ftp.freebsd.org/pub/FreeBSD/ports/ports/]

Contact: René Ladan <portmgr-secretary@FreeBSD.org> +
Contact: FreeBSD Ports Management Team <portmgr@FreeBSD.org>

The Ports Management Team is responsible for overseeing the overall direction of the Ports Tree, building packages (through its subsidiary pkgmgr), and personnel matters.
Below is what happened in the last quarter.

Currently we have just over 31,000 ports in the Ports Tree.
There are currently close to 2900 open ports PRs of which almost 800 are unassigned.
The last quarter saw 8194 commits by 159 committers on the main branch and 657 commits by 53 committers on the 2022Q4 branch.
Compared to the quarter before, this means a small increase in the number of available ports but also in the number of open PRs and a decreasing number of commits made.

On the personnel front, we welcomed Ronald Klop (ronald@) and said goodbye to bar@ and bhughes@.
We welcomed pizzamig@ as a new official member after a successful lurking period.
We also welcomed three new lurkers: bofh@, ler@, and ygy@.

Portmgr split itself up into portmgr and pkgmgr.
The new pkgmgr team, currently consisting of antoine@ and bdrewery@, is responsible for building packages and maintaining the package building cluster.

Four new USES were introduced:

* llvm to canonicalize ports dependencies on LLVM
* luajit to select a LuaJIT runtime
* octave to help ports depend on Octave and Octave-Forge
* tex to define dependencies on TeX and its various components.

The following default versions were bumped:

* Firebird to 3.0
* GCC to 12
* Lazarus to 2.2.4
* Lua to 5.4
* PHP to 8.1
* Samba to 4.13
* Varnish to 6
* LuaJIT is new and set at "luajit-openresty" for PowerPC64 and "luajit-devel" for all other architectures.

Three new features were introduced, PIE, RELRO, and BIND_NOW.
Each port can opt out of them by setting the <feature>_UNSAFE variable.
Users can activate or deactivate them globally by setting WITH_<feature> or WITHOUT_<feature>.

The following major ports were updated to new versions:

* Chromium 108.0.5359.124
* Electron 18.3.11, 19.0.15, and 21.2.0
* Firefox 108.0.1
* Firefox-ESR 102.6.0
* gcc 12
* KDE Plasma 5.24.7, Frameworks 5.101.0, Applications 22.12.0
* Qt 5.15.7 and 6.4.1
* Rust 1.66.0
* SDL 2.26.1
* Sway 1.8
* wlroots 0.16.1
* Wine 7.0.1.

The exp-run reports are available again.
During the last quarter, antoine@ ran 38 exp-runs to:

* test port updates
* change default versions
* identify use of IPPROTO_DIVERT in ports
* support PF_DIVERT in Python for FreeBSD 14.
