# $FreeBSD: www/ru/java/links/Makefile,v 1.1 2000/03/05 16:52:30 phantom Exp $
# Original version: 1.2

DOCS =	freebsd.sgml
DOCS+=	tools.sgml
DOCS+=	api.sgml
DOCS+=	index.sgml 
DOCS+=	tutorials.sgml
DOCS+=	development.sgml
DOCS+=	resources.sgml 
DOCS+=	vendor.sgml
DOCS+=	documentation.sgml
DOCS+=	servlets.sgml

.include "../../web.mk"
