# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/links/Makefile,v 1.2 2000/10/11 16:16:15 phantom Exp $
# Original revision: 1.2

DOCS =	freebsd.sgml
DOCS+=	tools.sgml
DOCS+=	api.sgml
DOCS+=	index.sgml 
DOCS+=	tutorials.sgml
DOCS+=	development.sgml
DOCS+=	resources.sgml 
DOCS+=	vendor.sgml
DOCS+=	documentation.sgml
DOCS+=	servlets.sgml

.include "../../web.mk"
