# $FreeBSD: www/ja/releases/2.1.5R/Makefile,v 1.2 1999/09/06 07:03:24 peter Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

#DOCS=	announce.sgml notes.sgml
DOCS=	notes.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/2.1.5R

.include "../../../web.mk"
