#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/books/handbook/l10n/Makefile,v 1.1 2004/03/24 13:29:24 den Exp $
#
# Original revision: 1.1
#

CHAPTERS= 	l10n/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
