# $FreeBSD$

DOC_PREFIX?=	${.CURDIR}/../../../..
RELN_ROOT?=	${.CURDIR}/..

MAN4DIR?=	${DOC_PREFIX}/../src/share/man/man4

SUBDIR=		errata \
		hardware \
		readme \
		relnotes

.include "${DOC_PREFIX}/share/mk/doc.subdir.mk"
