#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD$
#    $FreeBSDde: de-docproj/articles/explaining-bsd/Makefile,v 1.2 2005/01/06 20:22:43 mheinen Exp $
#    basiert auf: 1.6
#
# Article: Hintergrundwissen zu BSD

DOC?= article

FORMATS?= html html-split
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
