# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/articles/dialup-firewall/Makefile
# %SRCID%	1.16

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
