# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif
.if exists(../../../en_US.ISO8859-1/htdocs/ports/Makefile.inc)
.include "../../../en_US.ISO8859-1/htdocs/ports/Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif

.include "${DOC_PREFIX}/share/mk/web.site.mk"
