---
title: Хавсралт B. Ном зүй
part: хэсэг V. Хавсралтууд
prev: books/handbook/mirrors
next: books/handbook/eresources
---

[appendix]
[[bibliography]]
= Ном зүй
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Гарчиг
:table-caption: Хүснэгт
:figure-caption: Зураг
:example-caption: Жишээ
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: B

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/mn/mailing-lists.adoc[]
include::shared/mn/teams.adoc[]
include::shared/mn/urls.adoc[]

Гарын авлагын хуудаснууд нь FreeBSD үйлдлийн системийн хувь хэсгүүдэд зориулсан эцсийн лавлагааг өгдөг боловч тэдгээр хэсгүүдийг хэрхэн нийлүүлж бүхэл бүтэн үйлдлийн системийг тэгш ажиллуулах талаар дүрслэн үзүүлдэггүйгээрээ зартай юм. Ийм учраас UNIX(R), системийн удирдлагын талаар бичсэн сайн ном болон хэрэглэгчдийн сайн гарын авлагыг орлохоор зүйлс байхгүй юм.

[[bibliography-freebsd]]
== FreeBSD-ийн талаар тусгайлан бичсэн ном & сэтгүүлүүд

_Олон улсад хэвлэгдсэн ном & сэтгүүлүүд:_

* http://jdli.tw.FreeBSD.org/publication/book/freebsd2/index.htm[Using FreeBSD] (Уламжлалт Хятад хэл дээр), хэвлэсэн http://www.drmaster.com.tw/[Drmaster], 1997. ISBN 9-578-39435-7.
* FreeBSD Unleashed (Хялбаршуулсан Хятад орчуулга), хэвлэсэн http://www.hzbook.com/[China Machine Press]. ISBN 7-111-10201-0. 
* FreeBSD From Scratch Хоёр дахь хэвлэл (Хялбаршуулсан Хятад хэл дээр), хэвлэсэн China Machine Press. ISBN 7-111-10286-X. 
* FreeBSD Handbook Хоёр дахь хэвлэл (Хялбаршуулсан Хятад орчуулга), хэвлэсэн http://www.ptpress.com.cn/[Posts & Telecom Press]. ISBN 7-115-10541-3. 
* FreeBSD & Windows (Хялбаршуулсан Хятад хэл дээр), хэвлэсэн http://www.tdpress.com/[China Railway Publishing House]. ISBN 7-113-03845-X
* FreeBSD Internet Services HOWTO (Хялбаршуулсан Хятад хэл дээр), хэвлэсэн China Railway Publishing House. ISBN 7-113-03423-3
* FreeBSD (Япон хэл дээр), хэвлэсэн CUTT. ISBN 4-906391-22-2 C3055 P2400E.
* http://www.shoeisha.com/book/Detail.asp?bid=650[Complete Introduction to FreeBSD] (Япон хэл дээр), хэвлэсэн http://www.shoeisha.co.jp/[Shoeisha Co., Ltd]. ISBN 4-88135-473-6 P3600E.
* http://www.ascii.co.jp/pb/book1/shinkan/detail/1322785.html[Personal UNIX Starter Kit FreeBSD] (Япон хэл дээр), хэвлэсэн http://www.ascii.co.jp/[ASCII]. ISBN 4-7561-1733-3 P3000E.
* FreeBSD Handbook (Япон орчуулга), хэвлэсэн http://www.ascii.co.jp/[ASCII]. ISBN 4-7561-1580-2 P3800E.
* FreeBSD mit Methode (Герман хэл дээр), хэвлэсэн http://www.cul.de[Computer und Literatur Verlag]/Vertrieb Hanser, 1998. ISBN 3-932311-31-0.
* http://www.mitp.de/vmi/mitp/detail/pWert/1343/[ FreeBSD de Luxe] (Герман хэл дээр), хэвлэсэн http://www.mitp.de[Verlag Modere Industrie], 2003. ISBN 3-8266-1343-0. 
* http://www.pc.mycom.co.jp/FreeBSD/install-manual.html[FreeBSD Install and Utilization Manual] (Япон хэл дээр), хэвлэсэн http://www.pc.mycom.co.jp/[Mainichi Communications Inc, 1998. ISBN 4-8399-0112-0.].
* Onno W Purbo, Dodi Maryanto, Syahrial Hubbany, Widjil Widodo _http://maxwell.itb.ac.id/[ Building Internet Server with FreeBSD]_ (Индонез хэл дээр), published by http://www.elexmedia.co.id/[Elex Media Komputindo].
* Absolute BSD: The Ultimate Guide to FreeBSD (Уламжлалт Хятад орчуулга), хэвлэсэн http://www.grandtech.com.tw/[GrandTech Press], 2003. ISBN 986-7944-92-5.
* http://www.twbsd.org/cht/book/[The FreeBSD 6.0 Book] (Уламжлалт Хятад хэл дээр), хэвлэсэн Drmaster, 2006. ISBN 9-575-27878-X.

_Англи хэл дээрх ном & сэтгүүлүүд:_

* http://www.absoluteFreeBSD.com/[Absolute FreeBSD, 2nd Edition: The Complete Guide to FreeBSD], хэвлэсэн http://www.nostarch.com/[No Starch Press], 2007. ISBN: 978-1-59327-151-0
* http://www.freebsdmall.com/cgi-bin/fm/bsdcomp[ The Complete FreeBSD], хэвлэсэн http://www.oreilly.com/[O'Reilly], 2003. ISBN: 0596005164
* http://www.freebsd-corp-net-guide.com/[The FreeBSD Corporate Networker's Guide], хэвлэсэн http://www.awl.com/aw/[Addison-Wesley], 2000. ISBN: 0201704811
* http://andrsn.stanford.edu/FreeBSD/introbook/[ FreeBSD: An Open-Source Operating System for Your Personal Computer], хэвлэсэн The Bit Tree Press, 2001. ISBN: 0971204500
* Teach Yourself FreeBSD in 24 Hours, хэвлэсэн http://www.samspublishing.com/[Sams], 2002. ISBN: 0672324245
* FreeBSD 6 Unleashed, хэвлэсэн http://www.samspublishing.com/[Sams], 2006. ISBN: 0672328755
* FreeBSD: The Complete Reference, хэвлэсэн http://books.mcgraw-hill.com[McGrawHill], 2003. ISBN: 0072224096 
* http://www.bsdmag.org[BSD magazine], хэвлэсэн Software Press Sp. z o.o. SK. ISSN 1898-9144

[[bibliography-userguides]]
== Хэрэглэгчдийн гарын авлагууд

* Охайогийн Их Сургууль http://www.cs.duke.edu/csl/docs/unix_course/[ UNIX Introductory Course] авлагыг бичсэн бөгөөд энэ нь шууд вэбээр үзэх боломжтойгоор HTML болон PostScript хэлбэрээр байдаг.
+ 
Энэ баримтын Итал https://www.FreeBSD.org/doc/it_IT.ISO8859-15/books/unix-introduction/index.html[орчуулга] Италийн FreeBSD-ийн Баримтжуулах Төслийн хэсэг болон авах боломжтойгоор байдаг.
* http://www.jp.FreeBSD.org/[Jpman Төсөл, Японы FreeBSD Хэрэглэгчдийн Бүлэг]. http://www.pc.mycom.co.jp/FreeBSD/urm.html[FreeBSD User's Reference Manual] (Япон орчуулга). http://www.pc.mycom.co.jp/[Mainichi Communications Inc.], 1998. ISBN4-8399-0088-4 P3800E.
* http://www.ed.ac.uk/[Эдинбургийн Их Сургууль] UNIX орчинд шинээр ирж байгаа хүмүүст зориулж http://unixhelp.ed.ac.uk/[Онлайн заавар] бичсэн.

[[bibliography-adminguides]]
== Администраторууд зориулсан зааврууд

* http://www.jp.FreeBSD.org/[Jpman Төсөл, Японы FreeBSD Хэрэглэгчдийн Бүлэг]. http://www.pc.mycom.co.jp/FreeBSD/sam.html[FreeBSD System Administrator's Manual] (Япон орчуулга). http://www.pc.mycom.co.jp/[Mainichi Communications Inc.], 1998. ISBN4-8399-0109-0 P3300E.
* Dreyfus, Emmanuel. http://www.eyrolles.com/Informatique/Livre/9782212114638/[Cahiers de l'Admin: BSD] 2nd Ed. (Франц хэл дээр), Eyrolles, 2004. ISBN 2-212-11463-X

[[bibliography-programmers]]
== Програм зохиогчдод зориулсан зааврууд

* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Reference Manual_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-078-3
* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Supplementary Documents_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-079-1
* Harbison, Samuel P. and Steele, Guy L. Jr. _C: A Reference Manual_. 4th ed. Prentice Hall, 1995. ISBN 0-13-326224-3
* Kernighan, Brian and Dennis M. Ritchie. _The C Programming Language_. 2nd Ed. PTR Prentice Hall, 1988. ISBN 0-13-110362-8
* Lehey, Greg. _Porting UNIX Software_. O'Reilly & Associates, Inc., 1995. ISBN 1-56592-126-7
* Plauger, P. J. _The Standard C Library_. Prentice Hall, 1992. ISBN 0-13-131509-9
* Spinellis, Diomidis. http://www.spinellis.gr/codereading/[Code Reading: The Open Source Perspective]. Addison-Wesley, 2003. ISBN 0-201-79940-5
* Spinellis, Diomidis. http://www.spinellis.gr/codequality/[Code Quality: The Open Source Perspective]. Addison-Wesley, 2006. ISBN 0-321-16607-8
* Stevens, W. Richard and Stephen A. Rago. _Advanced Programming in the UNIX Environment_. 2nd Ed. Reading, Mass. : Addison-Wesley, 2005. ISBN 0-201-43307-9
* Stevens, W. Richard. _UNIX Network Programming_. 2nd Ed, PTR Prentice Hall, 1998. ISBN 0-13-490012-X

[[bibliography-osinternals]]
== Үйлдлийн системийн дотоод бүрэлдэхүүнүүдийн талаар

* Andleigh, Prabhat K. _UNIX System Architecture_. Prentice-Hall, Inc., 1990. ISBN 0-13-949843-5
* Jolitz, William. "Porting UNIX to the 386". _Dr. Dobb's Journal_. January 1991-July 1992.
* Leffler, Samuel J., Marshall Kirk McKusick, Michael J Karels and John Quarterman _The Design and Implementation of the 4.3BSD UNIX Operating System_. Reading, Mass. : Addison-Wesley, 1989. ISBN 0-201-06196-1
* Leffler, Samuel J., Marshall Kirk McKusick, _The Design and Implementation of the 4.3BSD UNIX Operating System: Answer Book_. Reading, Mass. : Addison-Wesley, 1991. ISBN 0-201-54629-9
* McKusick, Marshall Kirk, Keith Bostic, Michael J Karels, and John Quarterman. _The Design and Implementation of the 4.4BSD Operating System_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-54979-4
+ 
(Энэ номын 2-р бүлэг link:{design-44bsd}[онлайн]аар FreeBSD баримтжуулах төслийн хүрээнд байгаа.)
* Marshall Kirk McKusick, George V. Neville-Neil _The Design and Implementation of the FreeBSD Operating System_. Boston, Mass. : Addison-Wesley, 2004. ISBN 0-201-70245-2
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 1: The Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63346-9
* Schimmel, Curt. _Unix Systems for Modern Architectures_. Reading, Mass. : Addison-Wesley, 1994. ISBN 0-201-63338-8
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 3: TCP for Transactions, HTTP, NNTP and the UNIX Domain Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63495-3
* Vahalia, Uresh. _UNIX Internals -- The New Frontiers_. Prentice Hall, 1996. ISBN 0-13-101908-2
* Wright, Gary R. and W. Richard Stevens. _TCP/IP Illustrated, Volume 2: The Implementation_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63354-X

[[bibliography-security]]
== Аюулгүй байдлын тухай номнууд

* Cheswick, William R. and Steven M. Bellovin. _Firewalls and Internet Security: Repelling the Wily Hacker_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63357-4
* Garfinkel, Simson. _PGP Pretty Good Privacy_ O'Reilly & Associates, Inc., 1995. ISBN 1-56592-098-8

[[bibliography-hardware]]
== Тоног төхөөрөмжийн тухай номнууд

* Anderson, Don and Tom Shanley. _Pentium Processor System Architecture_. 2nd Ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40992-5
* Ferraro, Richard F. _Programmer's Guide to the EGA, VGA, and Super VGA Cards_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-62490-7
* Интел корпораци өөрсдийн CPU-ууд, бичил схемүүд болон стандартуудын тухай баримт бичгүүдийг http://developer.intel.com/[хөгжүүлэгчийн вэб хуудсанд] ихэвчлэн PDF файл хэлбэрээр байрлуулдаг.
* Shanley, Tom. _80486 System Architecture_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40994-1
* Shanley, Tom. _ISA System Architecture_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40996-8
* Shanley, Tom. _PCI System Architecture_. 4th ed. Reading, Mass. : Addison-Wesley, 1999. ISBN 0-201-30974-2
* Van Gilluwe, Frank. _The Undocumented PC_, 2nd Ed. Reading, Mass: Addison-Wesley Pub. Co., 1996. ISBN 0-201-47950-8
* Messmer, Hans-Peter. _The Indispensable PC Hardware Book_, 4th Ed. Reading, Mass: Addison-Wesley Pub. Co., 2002. ISBN 0-201-59616-4

[[bibliography-history]]
== UNIX(R)-ийн түүх

* Lion, John _Lion's Commentary on UNIX, 6th Ed. With Source Code_. ITP Media Group, 1996. ISBN 1573980137
* Raymond, Eric S. _The New Hacker's Dictionary, 3rd edition_. MIT Press, 1996. ISBN 0-262-68092-0. http://www.catb.org/~esr/jargon/html/index.html[Жаргон Файл] гэж бас хэлэгддэг.
* Salus, Peter H. _A quarter century of UNIX_. Addison-Wesley Publishing Company, Inc., 1994. ISBN 0-201-54777-5
* Simon Garfinkel, Daniel Weise, Steven Strassmann. _The UNIX-HATERS Handbook_. IDG Books Worldwide, Inc., 1994. ISBN 1-56884-203-1. Хэвлэгдэхээ больсон, гэхдээ http://www.simson.net/ref/ugh.pdf[ онлайн] байгаа.
* Don Libes, Sandy Ressler _Life with UNIX_ - special edition. Prentice-Hall, Inc., 1989. ISBN 0-13-536657-7
* _BSD-н ургийн бичиг_. FreeBSD машин дээрх http://www.FreeBSD.org/cgi/cvsweb.cgi/src/shared/misc/bsd-family-tree[http://www.FreeBSD.org/cgi/cvsweb.cgi/src/shared/misc/bsd-family-tree] эсвэл link:file://localhost/usr/shared/misc/bsd-family-tree[/usr/shared/misc/bsd-family-tree]
* _Networked Computer Science Technical Reports Library_. http://www.ncstrl.org/[http://www.ncstrl.org/]
* _Computer Systems Research group (CSRG) буюу Компьютерийн Системүүдийн Судалгааны Бүлгийн гаргасан хуучин BSD хувилбарууд_. http://www.mckusick.com/csrg/[http://www.mckusick.com/csrg/]: 4 CD бүхий цуглуулга нь 1BSD-ээс авахуулаад 4.4BSD болон 4.4BSD-Lite2 (харамсалтай нь 2.11BSD-г биш) хүртэлх бүх BSD хувилбаруудыг хамардаг. Сүүлийн диск нь төгсгөлийн эхүүдээс гадна SCCS файлуудыг бас агуулдаг.

[[bibliography-journals]]
== Сонин, сэтгүүлүүд

* _The C/C++ Users Journal_. R&D Publications Inc. ISSN 1075-2838
* _Sys Admin - The Journal for UNIX System Administrators_ Miller Freeman, Inc., ISSN 1061-2688
* _freeX - Das Magazin für Linux - BSD - UNIX_ (Герман хэл дээр) Computer- und Literaturverlag GmbH, ISSN 1436-7033
