.\" @(#)publickey.3r	2.1 88/08/07 4.0 RPCSRC
.\" %FreeBSD: src/lib/libc/rpc/publickey.3,v 1.4.2.2 2001/12/14 18:33:56 ru Exp %
.\" $FreeBSD$
.\"
.Dd October 6, 1987
.Dt PUBLICKEY 3
.Os
.Sh 名称
.Nm publickey , getpublickey , getsecretkey
.Nd 公開鍵か秘密鍵の入手
.Sh ライブラリ
.Lb librpcsvc
.Sh 書式
.In rpc/rpc.h
.In rpc/key_prot.h
.Ft int
.Fo getpublickey
.Fa "char netname[MAXNETNAMELEN+1]"
.Fa "char publickey[HEXKEYBYTES+1]"
.Fc
.Ft int
.Fo getsecretkey
.Fa "char netname[MAXNETNAMELEN+1]"
.Fa "char secretkey[HEXKEYBYTES+1]"
.Fa "char *passwd"
.Fc
.Sh 解説
これらのルーチンは、公開鍵と秘密鍵を
.Tn YP
データベースから入手します。
.Fn getsecretkey
には追加の引数
.Fa passwd
があり、
データベースに保存されている、暗号化された秘密鍵の復号化に使用されます。
どちらのルーチンも、鍵が見つかると 1 を戻し、見つからないと 0 を戻します。
鍵は、
.Dv NULL
で終わる 16 進文字列として戻されます。
.Fn getsecretkey
に指定されたパスワードで秘密鍵を復号化できない場合は 1 が戻されますが、
.Fa secretkey
引数は
.Dv NULL
文字列
.Pq Dq
になります。
.Sh 関連項目
.Xr publickey 5
.Pp
.Pa /usr/share/doc/psd/23.rpc
の
.%T "RPC Programmer's Manual"
