---
title: "About Applications for FreeBSD"
sidenav: about
---

= About Applications for FreeBSD

== Experience the possibilities with FreeBSD

FreeBSD can handle nearly any task you would expect of a UNIX(R) workstation, as well as many you might not expect:

== FreeBSD is a true open system with full source code.

There is no doubt that so-called open systems are _the_ requirement for today's computing applications. But no commercial vendor-supplied solution is more open than one which includes full source code to the entire operating system, including the kernel and all of the system daemons, programs, and utilities. You can modify any part of FreeBSD to suit your personal, organizational, or corporate needs.

With its generous link:../copyright/freebsd-license/[licensing policy], you can use FreeBSD as the basis for any number of free _or commercial_ applications.

== FreeBSD runs thousands of applications.

Because FreeBSD is based on 4.4BSD, an industry-standard version of UNIX, it is easy to compile and run programs. FreeBSD also includes an extensive link:../where/[packages collection] and link:../ports/[ports collection] that bring precompiled and easy-to-build software right to your desktop or enterprise server. There is also a growing number of link:../commercial/software/[commercial applications] written for FreeBSD.

Here are some examples of the environments in which FreeBSD is used:

* *Internet services.* Many Internet Service Providers (ISPs) find FreeBSD ideal, running WWW, Usenet news, FTP, Email, and other services. Ready-to-run software like the http://nginx.org[nginx] or http://www.apache.org/[Apache] web server or the http://proftpd.org/[ProFTPD] or http://security.appspot.com/vsftpd.html[vsftpd] FTP server make it easy to set up a business or community-centered ISP. Of course, with FreeBSD's unbeatable link:../internet/[networking], your users will enjoy high speed, reliable services.
* *X Window workstation.* From an inexpensive X terminal to an advanced X display, FreeBSD works quite well. Free X software (http://x.org/[X.Org](T)) comes with the system. http://www.nvidia.com/[nVidia] offers native drivers for their high-performance graphics hardware, and the industry standard http://www.opengroup.org/motif/[Motif](R) and http://www.opengl.org/[OpenGL](R) libraries are supported. The http://xfce.org/[Xfce] and http://lxde.org/[LXDE] products provide a desktop environment. The http://www.kde.org[KDE] and http://www.gnome.org[GNOME] desktop environments also enjoy full support and provide office suite functionality, with further good functionality available in the https://www.libreoffice.org/[LibreOffice], http://www.openoffice.org/[OpenOffice.Org] and http://www.softmaker.com/en/[TextMaker] products.
* *Networking.* From packet filtering to routing to name service, FreeBSD can turn any PC into a Internet firewall, email host, print server, PC/NFS server, and more.
* *Software development.* A suite of development tools comes with FreeBSD, including the GNU C/C++ compiler and debugger. The LLVM-based clang suite is also provided and will eventually replace the GNU suite. Java(R) and Tcl/Tk development are also possible for example, and more esoteric programming languages like Icon work just fine, too. And FreeBSD's shared libraries have always been easy to make and use. You can also choose from a wide range of popular and powerful editors, such as Emacs and Vim.
* *Net surfing.* A real UNIX workstation makes a great Internet surfboard. FreeBSD versions of http://www.chromium.org/Home[Chromium] and http://www.mozilla.org/firefox/[Firefox] are available for serious web users. Surf the web, publish your own web pages, read Usenet news, and send and receive email with a FreeBSD system on your desktop.
* *Education and research.* FreeBSD makes an excellent research platform because it includes complete source code. Students and researchers of operating systems or other computer science fields can benefit greatly from such an open and well-documented system.
* *And much more.* Accounting, action games, MIS databases, scientific visualization, video conferencing, Internet relay chat (IRC), home automation, multiuser dungeons, bulletin board systems, image scanning, and more are all real uses for FreeBSD today.

== FreeBSD is an operating system that will grow with your needs.

Though FreeBSD is free software, it is also _user supported_ software. Any questions you have can be posted to hundreds of FreeBSD developers and users simply by e-mailing the freebsd-questions@FreeBSD.org mailing list.

FreeBSD also has a worldwide group of programmers and writers who fix bugs, add new features and document the system. Support for new devices or special features is an almost constant development process, and the team keeps a special eye out for problems which affect system stability. FreeBSD users are quite proud of not only how fast but how reliable their systems are.

== What experts have to say . . .

_"FreeBSD handles [our] heavy load quite well and it is nothing short of amazing. Salutations to the FreeBSD team."_

[.right]
---Mark Hittinger, administrator of WinNet Communications, Inc.
