---
title: "Contacting the FreeBSD Community"
sidenav: about
---

include::shared/en/mailing-lists.adoc[]
include::shared/en/urls.adoc[]

= Contacting the Community

link:../community/mailinglists[Mailing lists are the primary communication channel].

Please note, some lists require subscription before posting; posts from non-subscribers may be held in a queue.

== Questions

Write to the {freebsd-questions}; see the link:../community[Community] page for other options.

== Website Content

Questions or suggestions about documentation may be addressed to the {freebsd-doc}.

Alternatively, for link:{main-site}[Documentation Portal] content -- including the link:{handbook}[FreeBSD Handbook] and link:{faq}[FAQ] -- in-page resources include the option to edit the page in GitHub.

== Project Administration and Management

link:../administration[Core Team, Security, Tree Management, Webmaster Team, Postmaster Team, Bugmeisters, and others.]

== Legal

FreeBSD trademarks are owned by the link:https://freebsdfoundation.org/[FreeBSD Foundation].

