---
title: "Download FreeBSD"
sidenav: download
---

:url-rel: https://download.FreeBSD.org/releases
:url-snapshot: https://download.freebsd.org/snapshots

include::shared/releases.adoc[]
include::shared/en/urls.adoc[]

= Download FreeBSD

[[choose-version]]
[[choose-arch]]
== Choosing an Architecture

Most users of FreeBSD will have hardware for either the amd64 or aarch64 architectures, which are well supported.

Modern PCs use the amd64 architecture, including those with Intel(R) branded processors.
Embedded devices and single-board computers (SBCs) such as the Raspberry Pi 3 and 4, ESPRESSObin, as well as many Allwinner and Rockchip boards, use the aarch64 SD card image.

All other users should reference the link:../platforms/[complete list] of supported FreeBSD platforms.

[[choose-image]]
== Choosing an Image

The FreeBSD installer can be downloaded in a number of different formats including CD (disc1), DVD (dvd1), and Network Install (bootonly) sized ISO Disc Images, as well as regular and mini USB memory stick images.
Recent versions of FreeBSD are also offered as prebuilt expandable Virtual Machine images, and as SD Card images for embedded platforms.

[[download]]
[[download-rel131]]
== FreeBSD {rel131-current}-RELEASE
[.tblbasic]
[.tblDownload]
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Installer Images |Virtual Machine Images |SD Card Images |Documentation
a|
* link:{url-rel}/amd64/amd64/ISO-IMAGES/{rel131-current}/[amd64]
* link:{url-rel}/i386/i386/ISO-IMAGES/{rel131-current}/[i386]
* link:{url-rel}/powerpc/powerpc/ISO-IMAGES/{rel131-current}/[powerpc]
* link:{url-rel}/powerpc/powerpc64/ISO-IMAGES/{rel131-current}/[powerpc64]
* link:{url-rel}/powerpc/powerpc64le/ISO-IMAGES/{rel131-current}/[powerpc64le]
* link:{url-rel}/powerpc/powerpcspe/ISO-IMAGES/{rel131-current}/[powerpcspe]
* link:{url-rel}/arm/armv6/ISO-IMAGES/{rel131-current}/[armv6]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel131-current}/[armv7]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel131-current}/[aarch64]
* link:{url-rel}/riscv/riscv64/ISO-IMAGES/{rel131-current}/[riscv64]

a|
* link:{url-rel}/VM-IMAGES/README.txt[README]
* link:{url-rel}/VM-IMAGES/{rel131-current}-RELEASE/amd64/Latest/[amd64]
* link:{url-rel}/VM-IMAGES/{rel131-current}-RELEASE/i386/Latest/[i386]
* link:{url-rel}/VM-IMAGES/{rel131-current}-RELEASE/aarch64/Latest/[aarch64]
//* link:{url-rel}/VM-IMAGES/{rel131-current}-RELEASE/riscv64/Latest/[riscv64]
* link:{url-rel}/CI-IMAGES/{rel131-current}-RELEASE/amd64/Latest/[amd64] (BASIC-CI)

a|
* aarch64
* {blank}
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel131-current}/[PINE64]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel131-current}/[PINE64-LTS]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel131-current}/[ROCK64]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel131-current}/[ROCKPRO64]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel131-current}/[RPI] (3/4)
* armv6/armv7
* {blank}
** link:{url-rel}/arm/armv7/ISO-IMAGES/{rel131-current}/[GENERICSD]
** link:{url-rel}/arm/armv6/ISO-IMAGES/{rel131-current}/[RPI-B]
* riscv64
* {blank}
** link:{url-rel}/riscv/riscv64/ISO-IMAGES/{rel131-current}/[GENERICSD]

a|
* link:../releases/#current[Released]: {rel131-current-date}
* link:{u-rel131-notes}[Release Notes]
* link:{u-rel131-readme}[Readme]
* link:{u-rel131-hardware}[Hardware Compatibility List]
* link:{u-rel131-installation}[Installation Instructions]
* link:{u-rel131-errata}[Errata]
* link:{u-rel131-signatures}[Signed Checksums]

|===

[[download-rel123]]
== FreeBSD {rel123-current}-RELEASE

[.tblbasic]
[.tblDownload]
[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Installer Images |Virtual Machine Images |SD Card Images |Documentation
a|
* link:{url-rel}/amd64/amd64/ISO-IMAGES/{rel123-current}/[amd64]
* link:{url-rel}/i386/i386/ISO-IMAGES/{rel123-current}/[i386]
* link:{url-rel}/powerpc/powerpc/ISO-IMAGES/{rel123-current}/[powerpc]
* link:{url-rel}/powerpc/powerpc64/ISO-IMAGES/{rel123-current}/[powerpc64]
* link:{url-rel}/powerpc/powerpcspe/ISO-IMAGES/{rel123-current}/[powerpcspe]
* link:{url-rel}/sparc64/sparc64/ISO-IMAGES/{rel123-current}/[sparc64]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel123-current}/[aarch64]

a|
* link:{url-rel}/VM-IMAGES/README.txt[README]
* link:{url-rel}/VM-IMAGES/{rel123-current}-RELEASE/amd64/Latest/[amd64]
* link:{url-rel}/VM-IMAGES/{rel123-current}-RELEASE/i386/Latest/[i386]
* link:{url-rel}/VM-IMAGES/{rel123-current}-RELEASE/aarch64/Latest/[aarch64]

a|
* link:{url-rel}/arm/armv6/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm-armv6-RPI-B.img.xz[RPI-B]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm-armv7-BANANAPI.img.xz[BANANAPI]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm-armv7-CUBIEBOARD.img.xz[CUBIEBOARD]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm-armv7-CUBIEBOARD2.img.xz[CUBIEBOARD2]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm-armv7-CUBOX-HUMMINGBOARD.img.xz[CUBOX-HUMMINGBOARD]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm-armv7-GENERICSD.img.xz[GENERICSD]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm-armv7-RPI2.img.xz[RPI2]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm-armv7-PANDABOARD.img.xz[PANDABOARD]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm-armv7-WANDBOARD.img.xz[WANDBOARD]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm64-aarch64-PINE64.img.xz[PINE64]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm64-aarch64-PINE64-LTS.img.xz[PINE64-LTS]
//* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel123-current}/FreeBSD-{rel123-current}-RELEASE-arm64-aarch64-RPI3.img.xz[RPI3]

a|
* {blank}
* link:../releases/#current[Released]: {rel123-current-date}
* link:{u-rel123-notes}[Release Notes]
* link:{u-rel123-readme}[Readme]
* link:{u-rel123-hardware}[Hardware Compatibility List]
* link:{u-rel123-installation}[Installation Instructions]
* link:{u-rel123-errata}[Errata]
* link:{u-rel123-signatures}[Signed Checksums]

|===

//[[helptest]]
//== Help Test
//
//If you are interested in testing the next upcoming release, please visit the link:../where/[FreeBSD download page].

[[download-snapshots]]
== Development Snapshots

If you are interested in a purely experimental *snapshot* release of FreeBSD-CURRENT (AKA {rel-head}-CURRENT), aimed at developers and bleeding-edge testers only, then please see the link:../snapshots/[FreeBSD Snapshot Releases] page.
For more information about past, present and future releases in general, please visit the link:../releases/[release information page].

== FreeBSD {rel-head}-CURRENT

Installer and SD card images are available for link:{url-snapshot}/amd64/amd64/ISO-IMAGES/{rel-head}/[amd64], link:{url-snapshot}/i386/i386/ISO-IMAGES/{rel-head}/[i386], link:{url-snapshot}/powerpc/powerpc/ISO-IMAGES/{rel-head}/[powerpc], link:{url-snapshot}/powerpc/powerpc64/ISO-IMAGES/{rel-head}/[powerpc64], link:{url-snapshot}/powerpc/powerpc64le/ISO-IMAGES/{rel-head}/[powerpc64le], link:{url-snapshot}/powerpc/powerpcspe/ISO-IMAGES/{rel-head}/[powerpcspe], link:{url-snapshot}/arm/armv6/ISO-IMAGES/{rel-head}/[armv6], link:{url-snapshot}/arm/armv7/ISO-IMAGES/{rel-head}/[armv7], link:{url-snapshot}/arm64/aarch64/ISO-IMAGES/{rel-head}/[aarch64], and link:{url-snapshot}/riscv/riscv64/ISO-IMAGES/{rel-head}/[riscv64].

VM images are available for link:{url-snapshot}/VM-IMAGES/{rel-head}-CURRENT/amd64/Latest/[amd64], link:{url-snapshot}/VM-IMAGES/{rel-head}-CURRENT/i386/Latest/[i386], link:{url-snapshot}/VM-IMAGES/{rel-head}-CURRENT/aarch64/Latest/[aarch64], and link:{url-snapshot}/VM-IMAGES/{rel-head}-CURRENT/riscv64/Latest/[riscv64].

== FreeBSD {rel131-current}-STABLE

Installer and SD card images are available for link:{url-snapshot}/amd64/amd64/ISO-IMAGES/{rel131-current}/[amd64], link:{url-snapshot}/i386/i386/ISO-IMAGES/{rel131-current}/[i386], link:{url-snapshot}/powerpc/powerpc/ISO-IMAGES/{rel131-current}/[powerpc], link:{url-snapshot}/powerpc/powerpc64/ISO-IMAGES/{rel131-current}/[powerpc64], link:{url-snapshot}/powerpc/powerpc64le/ISO-IMAGES/{rel131-current}/[powerpc64le], link:{url-snapshot}/powerpc/powerpcspe/ISO-IMAGES/{rel131-current}/[powerpcspe], link:{url-snapshot}/arm/armv6/ISO-IMAGES/{rel131-current}/[armv6], link:{url-snapshot}/arm/armv7/ISO-IMAGES/{rel131-current}/[armv7], link:{url-snapshot}/arm64/aarch64/ISO-IMAGES/{rel131-current}/[aarch64], and link:{url-snapshot}/riscv/riscv64/ISO-IMAGES/{rel131-current}/[riscv64].

VM images are available for link:{url-snapshot}/VM-IMAGES/{rel131-current}-STABLE/amd64/Latest/[amd64], link:{url-snapshot}/VM-IMAGES/{rel131-current}-STABLE/i386/Latest/[i386], link:{url-snapshot}/VM-IMAGES/{rel131-current}-STABLE/aarch64/Latest/[aarch64], and link:{url-snapshot}/VM-IMAGES/{rel131-current}-STABLE/riscv64/Latest/[riscv64].

== FreeBSD {rel123-current}-STABLE

Installer and SD card images are available for link:{url-snapshot}/amd64/amd64/ISO-IMAGES/{rel123-current}/[amd64], link:{url-snapshot}/i386/i386/ISO-IMAGES/{rel123-current}/[i386], link:{url-snapshot}/powerpc/powerpc/ISO-IMAGES/{rel123-current}/[powerpc], link:{url-snapshot}/powerpc/powerpc64/ISO-IMAGES/{rel123-current}/[powerpc64], link:{url-snapshot}/powerpc/powerpcspe/ISO-IMAGES/{rel123-current}/[powerpcspe], link:{url-snapshot}/sparc64/sparc64/ISO-IMAGES/{rel123-current}/[sparc64], link:{url-snapshot}/arm/armv6/ISO-IMAGES/{rel123-current}/[armv6], link:{url-snapshot}/arm/armv7/ISO-IMAGES/{rel123-current}/[armv7], and link:{url-snapshot}/arm64/aarch64/ISO-IMAGES/{rel123-current}/[aarch64].

VM images are available for link:{url-snapshot}/VM-IMAGES/{rel123-current}-STABLE/amd64/Latest/[amd64] and link:{url-snapshot}/VM-IMAGES/{rel123-current}-STABLE/i386/Latest/[i386].

If you plan on getting FreeBSD via HTTP or FTP, please check the listing of *link:{handbook}mirrors/#mirrors[mirror sites]* in the Handbook to see if there is a site closer to you.

[[install]]
=== Install FreeBSD

There are many options for installing FreeBSD, including installation from CD-ROM, DVD, USB Memory Stick or even directly using anonymous FTP, HTTP, or NFS.
Please read through the link:{handbook}bsdinstall/[FreeBSD installation guide] before downloading the entire FreeBSD distribution.

[[distribution]]
=== Purchase FreeBSD Media

FreeBSD can be acquired on CD-ROM or DVD from http://www.freebsdmall.com/[FreeBSD Mall], or one of the other link:{handbook}mirrors/#mirrors-cdrom[CD-ROM and DVD Publishers].

[[past]]
=== Past Releases

For downloading past releases, please visit the http://ftp-archive.FreeBSD.org/pub/FreeBSD-Archive/old-releases/[FTP archive].

[[derived]]
=== FreeBSD-derived Operating System Distributions

FreeBSD is widely used as a building block for other commercial and open-source operating systems.
The projects below are widely used and of particular interest to FreeBSD users.

* https://www.truenas.com/[TrueNAS] is a Network Attached Storage (NAS) software that shares and protects data from modern-day threats like ransomware and malware. TrueNAS makes it easy for users and client devices to access shared data through virtually any sharing protocol.
* https://ghostbsd.org[GhostBSD] is derived from FreeBSD, GhostBSD uses the GTK environment to provide a beautiful look and a comfortable experience on the modern BSD platform offering a natural and native UNIX(R) work environment.
* https://www.midnightbsd.org[MidnightBSD] is a BSD-derived operating system developed with desktop users in mind. It includes all the software you would expect for your daily tasks: mail, web browsing, word processing, gaming, and much more.
* https://www.nomadbsd.org[NomadBSD] is a persistent live system for USB flash drives, based on FreeBSD. Together with automatic hardware detection and setup, it is configured to be used as a desktop system that works out of the box, but can also be used for data recovery, for educational purposes, or to test FreeBSD's hardware compatibility.
* http://www.pfsense.org[pfSense] is a FreeBSD based customized distribution tailored for use as a firewall and router.

[[apps]]
=== Applications and Utility Software

==== The Ports Collection

The FreeBSD Ports Collection is a diverse collection of utility and application software that has been ported to FreeBSD.

See *link:{handbook}#ports[Installing Applications: Packages and Ports]* in the Handbook.

* ftp://ftp.FreeBSD.org/pub/FreeBSD/ports/[Download the FreeBSD Ports Collection framework]
* link:../ports/[Web interface to the Ports Collection]
* http://www.freshports.org/[FreshPorts - a more advanced web interface to the Ports Collection]

For information about how _you_ can contribute _your_ favorite piece of software to the Ports Collection, have a look at _link:{porters-handbook}[The Porter's Handbook]_ and the article _link:{contributing}[Contributing to FreeBSD]_.
