---
title: "FreeBSD 3.4 Announcement"
sidenav: download
--- 

= FreeBSD 3.4 Announcement

*Date:* Mon, 20 Dec 1999 10:45:47 -0800 +
*From:* "Jordan K. Hubbard" <jkh@freebsd.org> +
**Subject:**FreeBSD 3.4-RELEASE is now available.

Just in under the wire for the current millenium, I'm happy to announce the availability of FreeBSD 3.4-RELEASE, the very latest in 3.x-STABLE branch technology. Following the release of FreeBSD 3.3 in Sept, 1999, a lot of new features have been added, many bugs were fixed and even more important security issues were dealt with. Please see the link:notes.html[release notes] for more information.

FreeBSD 3.4-RELEASE is available at ftp://ftp.FreeBSD.org/pub/FreeBSD/[ftp.FreeBSD.org] and various https://www.FreeBSD.org/handbook/mirrors.html[FTP mirror sites] throughout the world. It can also be ordered on CD from http://www.FreeBSDMall.com/[The FreeBSD Mall], from where it will be shipping soon on a 4 CD set containing installation bits for x86 architecture, as well as a lot of other material of general interest to programmers and end-users alike (3.4-RELEASE for the Alpha architecture is available from the FTP site and will also be available on CDROM several weeks after the x86 product is released).

NOTE: All of the profits from the sales of this CD set go to support the FreeBSD Project! We are also continuing our new tradition (started with 3.3-RELEASE) of making disc #1 from Walnut Creek CDROM's official distribution available via anonymous FTP. This is the most important CD of their 4 set, one which will allow users to install the base system and all of its most important add-ons from a single ISO 9660 image. We are doing this because the ISO image is rapidly becoming the preferred format for distributing operating system releases and we're certainly not going to go out of our way to make FreeBSD harder to "test drive" if providing the standard NFS/FTP network installation methods is no longer enough. This is a fully-bootable ISO 9660 (with RockRidge extensions) image and can be written as a raw ISO image by most CD creator software.

We can't promise that all the mirror sites will carry the rather large installation (660MB) image, but it will at least be available from:

ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/ISO-IMAGES/3.4-install.iso

along with the more traditional 3.4-RELEASE bits. If you can't afford the CDs, are impatient, or just want to use it for evangelism purposes, then by all means download the ISO, otherwise please do continue to support the FreeBSD project by purchasing one of its official CD releases from Walnut Creek CDROM.

The official FTP distribution site for FreeBSD is:

____
ftp://ftp.FreeBSD.org/pub/FreeBSD/
____

Or via the WEB pages at:

____
http://www.FreeBSDMall.com/ and +
http://www.cdrom.com/[http://www.cdrom.com]
____

And directly from Walnut Creek CDROM:

____
Walnut Creek CDROM +
4041 Pike Lane, #F +
Concord CA, 94520 USA +
Phone: +1 925 674-0783 +
Fax: +1 925 674-0821 +
Tech Support: +1 925 603-1234 +
Email: info@cdrom.com +
WWW: http://www.cdrom.com/
____

Additionally, FreeBSD is available via anonymous FTP from https://www.FreeBSD.org/handbook/mirrors.html[mirror sites] in the following countries: Argentina, Australia, Brazil, Bulgaria, Canada, the Czech Republic, Denmark, Estonia, Finland, France, Germany, Hong Kong, Hungary, Iceland, Ireland, Israel, Japan, Korea, Latvia, Malaysia, the Netherlands, Poland, Portugal, Rumania, Russia, Slovenia, South Africa, Spain, Sweden, Taiwan, Thailand, the Ukraine and the United Kingdom (and quite possibly several others which I've never even heard of :).

Before trying the central FTP site, please check your regional mirror(s) first by going to:

ftp://ftp.<yourdomain>.freebsd.org/pub/FreeBSD

Any additional mirror sites will be labeled ftp2, ftp3 and so on.

The latest versions of export-restricted code for FreeBSD (2.0C or later) (eBones and secure) are also being made available at the following locations. If you are outside the U.S. or Canada, please get secure (DES) and eBones (Kerberos) from one of the following foreign distribution sites:

South Africa::
  ftp://ftp.internat.FreeBSD.ORG/pub/FreeBSD +
  ftp://ftp2.internat.FreeBSD.ORG/pub/FreeBSD
Brazil::
  ftp://ftp.br.FreeBSD.ORG/pub/FreeBSD
Finland::
  ftp://nic.funet.fi/pub/unix/FreeBSD/eurocrypt

Thanks!

- Jordan

link:../../[Release Home]
