# $FreeBSD$
# $FreeBSDes: doc/es_ES.ISO8859-1/articles/Makefile,v 1.3 2004/10/09 02:01:17 jesusr Exp $

SUBDIR =
SUBDIR+= casestudy-argentina.com
SUBDIR+= contributing
SUBDIR+= cvs-freebsd
SUBDIR+= dialup-firewall
SUBDIR+= euro
SUBDIR+= explaining-bsd
SUBDIR+= fbsd-from-scratch
SUBDIR+= fdp-es
SUBDIR+= laptop
SUBDIR+= linux-comparison
SUBDIR+= linux-users
SUBDIR+= mailing-list-faq
SUBDIR+= nanobsd
SUBDIR+= p4-primer
SUBDIR+= problem-reports
SUBDIR+= pxe
SUBDIR+= releng
SUBDIR+= version-guide
SUBDIR+= zip-drive

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"

