# $FreeBSD$
# $FreeBSDes: doc/es_ES.ISO8859-1/articles/Makefile,v 1.3 2004/10/09 02:01:17 jesusr Exp $

SUBDIR =
SUBDIR+= contributing
SUBDIR+= explaining-bsd
SUBDIR+= fdp-es
SUBDIR+= leap-seconds
SUBDIR+= linux-users
SUBDIR+= mailing-list-faq
SUBDIR+= nanobsd
SUBDIR+= p4-primer
SUBDIR+= problem-reports
SUBDIR+= releng

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"

