# $FreeBSD$

SUBDIR =
SUBDIR+= contributing
SUBDIR+= dialup-firewall
SUBDIR+= explaining-bsd
SUBDIR+= fbsd-from-scratch
SUBDIR+= laptop
SUBDIR+= zip-drive

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
