---
title: 網頁資源
sidenav: docs
--- 

= 網頁資源

== 連結

* http://dmoz.org/Computers/Software/Operating_Systems/Unix/BSD/FreeBSD/[Open Directory 計劃] 有列出一堆不錯的 FreeBSD 連結， 包括一些有助於推廣市場的 http://dmoz.org/Computers/Software/Operating_Systems/Unix/BSD/FreeBSD/Prominent_Users/[知名用戶]。

== 現實生活中...

=== link:../../press/[FreeBSD 相關報導]

FreeBSD 的相關報導。

== Newsgroups

以下是 FreeBSD 使用者較常參與的討論區：

* link:news:comp.unix.bsd.freebsd.announce[comp.unix.bsd.freebsd.announce] (有管制)
* link:news:comp.unix.bsd.freebsd.misc[comp.unix.bsd.freebsd.misc]
* link:news:comp.unix.bsd.misc[comp.unix.bsd.misc]

== 額外資源

=== http://fxr.watson.org/[The Source Code]

若想挖掘原始碼來看的話，這邊有現成的 FreeBSD _kernel_ 原始碼的網頁版。 這是由 Robert Watson 所製作的。

=== http://www.daemonnews.org/[Daemon News]

BSD 新聞網站的龍頭

就像 FreeBSD，每篇文章都是志工所提供的。 該計劃目標就是矢志成為BSD 新聞網站的龍頭， 並也提供發佈更正稿、新聞來源的管道。

=== http://www.freebsddiary.org/[The FreeBSD Diary]

The FreeBSD Diary 收錄許多初學者必讀的 how-to 優良文件， 該站矢志成為提供 step-by-step 文件(說明如何安裝、設定各種 port 軟體)的匯集地。

=== http://www.OnLamp.com/bsd/[The O'Reilly Network BSD Dev Center]

The BSD Dev Center 有兩個 FreeBSD 專欄， 著重於各類技巧以及上手說明。

=== http://www.BSDForums.org[BSDForums.org]

BSDForums.org 有活躍的討論區以及 FreeBSD 及各類 BSD 的新聞、 社群網站。

=== http://www.bsdguides.org[BSD Guides]

BSDGuides.org 有放許多 BSD 相關的上手說明文件。

== 其他文件

http://docs.FreeBSD.org/44doc/[4.4BSD Documents]: 乃是 4.4BSD 文件的 HTML 版，也可以在每台 FreeBSD 機器上的 file://localhost/usr/share/doc[/usr/share/doc] 目錄內瀏覽( 若有裝 doc 套件的話)。

http://docs.FreeBSD.org/info/[Info Documents]: 乃是 Info 文件的 HTML 版，也可以在每台 FreeBSD 機器上的 file://localhost/usr/share/info[/usr/share/info] 目錄內瀏覽( 若有裝 info 套件的話)。
