---
title: FreeBSD kézikönyv
authors:
  - author: A FreeBSD Dokumentációs Projekt
copyright: 1995-2020 The FreeBSD Documentation Project
releaseinfo: "$FreeBSD$" 
trademarks: ["freebsd", "ibm", "ieee", "redhat", "3com", "adobe", "apple", "intel", "linux", "microsoft", "opengroup", "sun", "realnetworks", "oracle", "3ware", "arm", "adaptec", "google", "heidelberger", "intuit", "lsilogic", "themathworks", "thomson", "vmware", "wolframresearch", "xiph", "xfree86", "general"] 
next: books/handbook/preface
---

= FreeBSD kézikönyv
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:toc-title: Tartalom
:table-caption: Táblázat
:figure-caption: Ábra
:example-caption: Példa

include::shared/releases.adoc[]
include::shared/hu/mailing-lists.adoc[]

[.abstract-title]
Kivonat

Üdvözöljük a FreeBSD világában! Ez a kézikönyv ismerteti a _FreeBSD {rel112-current}-RELEASE_, ill. a _FreeBSD {rel120-current}-RELEASE_ telepítését és használatát a mindennapokban. A kézikönyv tartalmán számos független fejlesztõ _folyamatosan dolgozik_. Emiatt elképzelhetõ, hogy bizonyos fejezetek már elavultak és aktualizálásra szorulnak. Amennyiben úgy érezzük, hogy segíteni tudnánk a projekt munkájában, értesítsük a fejlesztõket a {freebsd-doc} címén! Ezen dokumentum legfrissebb változata mindig elérhetõ a http://www.FreeBSD.org/[FreeBSD honlapjáról] (a korábbi változatok pedig megtalálhatóak a http://docs.FreeBSD.org/doc/[http://docs.FreeBSD.org/doc/] címen). Ezenkívül még rengeteg más formátumban és tömörítve is letölthetõ a link:ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/[FreeBSD FTP szerverérõl] vagy a crossref:mirrors[mirrors-ftp,tüköroldalak] egyikérõl. Amennyiben a kézikönyv nyomtatott változatára lenne szükségünk, megvásárolhatjuk a http://www.freebsdmall.com/[FreeBSD Mall]-ból. Ha pedig keresni szeretnénk benne, azt a funkciót link:https://www.FreeBSD.org/search/[itt] érhetjük el.

_Fordította: Páli Gábor, utolsó ellenõrzés: 2010.11.28._

'''

include::content/hu/books/handbook/toc.adoc[]

include::content/hu/books/handbook/toc-figures.adoc[]

include::content/hu/books/handbook/toc-tables.adoc[]

include::content/hu/books/handbook/toc-examples.adoc[]
