# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: r45300

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.xml \
#	schedule.xml \
#	todo.xml

#DATA=	announce.asc \
DATA=	docbook.css \
#	errata.html \
#	hardware.html \
#	installation.html \
#	readme.html \
#	relnotes.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
