---
description: 'FreeBSD는 다양한 언어의 현지화를 지원하여 사용자가 영어가 아닌 언어로 데이터를 보고, 입력하거나 처리할 수 있도록 합니다'
next: books/handbook/cutting-edge
part: '파트 III. 시스템 관리'
path: /books/handbook/
prev: books/handbook/virtualization
showBookMenu: 'true'
tags: ["i18n", "L10n", "localization", "Locale", "LANG", "MM_CHARSET", "cap_mkdb"]
title: '24장. 현지화(Localization) - i18n/L10n 사용 및 설정'
weight: 28
---

[[l10n]]
= 현지화(Localization) - i18n/L10n 사용 및 설정
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 24
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/l10n/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[l10n-synopsis]]
== 요약

FreeBSD는 전 세계에 사용자와 기여자가 있는 분산 프로젝트입니다. 따라서 FreeBSD는 다양한 언어로 현지화를 지원하여 사용자가 영어가 아닌 언어로 데이터를 보고, 입력하고, 처리할 수 있도록 합니다. 중국어, 독일어, 일본어, 한국어, 프랑스어, 러시아어, 베트남어 뿐만 아니라 이에 국한되지 않고 대부분의 주요 언어를 사용할 수 있습니다.

국제화라는 용어는 `국제화`의 첫 글자와 마지막 글자 사이의 글자 수를 나타내는 i18n으로 줄여서 사용합니다. L10n은 동일한 명명 체계를 사용하지만 `현지화`에서 유래했습니다. i18n/L10n 메서드, 프로토콜 및 애플리케이션을 사용하면 사용자가 원하는 언어를 사용할 수 있습니다.

이 장에서는 FreeBSD의 국제화 및 현지화 기능에 대해 설명합니다. 이 장을 읽고 나면 여러분은 다음을 배웁니다:

* 로캘 이름이 구성되는 방식.
* 로그인 셸의 로캘을 설정하는 방법.
* 영어 이외의 언어에 맞게 콘솔을 구성하는 방법.
* 다른 언어에 맞게 Xorg를 구성하는 방법.
* i18n 호환 애플리케이션을 찾는 방법.
* 특정 언어 설정에 대한 자세한 정보를 찾을 수 있는 방법.

이 챕터를 읽기 전에 여러분은:

* crossref:ports[ports,install additional third-party applications] 방법.

[[using-localization]]
== 현지화 사용하기

현지화 설정은 언어 코드, 국가 코드 및 인코딩의 세 가지 구성 요소를 기반으로 합니다. 로캘 이름은 다음과 같이 이러한 구성 요소로 만들어집니다:

[.programlisting]
....
LanguageCode_CountryCode.Encoding
....

_언어 코드_ 및 _국가 코드_는 국가 및 특정 언어 변형을 결정하는 데 사용됩니다. <<locale-lang-country>>에서는 __언어코드_국가코드__의 몇 가지 예를 제공합니다:

[[locale-lang-country]]
.흔한 언어와 국가 코드
[cols="1,1", frame="none", options="header"]
|===
| LanguageCode_Country Code
| Description

|en_US
|English, United States

|ru_RU
|Russian, Russia

|zh_TW
|Traditional Chinese, Taiwan
|===

사용 가능한 로캘의 전체 목록은 다음과 같이 입력하면 확인할 수 있습니다:

[source, shell]
....
% locale -a | more
....

현재 로캘 설정을 확인하려면:

[source, shell]
....
% locale
....

ISO8859-1, ISO8859-15, KOI8-R 및 CP437과 같은 언어별 문자 집합은 man:multibyte[3]에 설명되어 있습니다. 문자 세트의 활성 목록은 http://www.iana.org/assignments/character-sets[IANA 레지스트리]에서 확인할 수 있습니다.

중국어나 일본어와 같은 일부 언어는 ASCII 문자로는 표현할 수 없으며 와이드 또는 멀티바이트 문자를 사용하는 확장 언어 인코딩이 필요합니다. 와이드 또는 멀티바이트 인코딩의 예로는 EUC 및 Big5가 있습니다. 구형 애플리케이션은 이러한 인코딩을 제어 문자로 착각할 수 있지만 최신 애플리케이션은 일반적으로 이러한 문자를 인식합니다. 구현에 따라 사용자는 와이드 문자 또는 멀티바이트 문자를 지원하는 애플리케이션을 컴파일하거나 올바르게 구성해야 할 수 있습니다.

[NOTE]
====
FreeBSD는 Xorg 호환 로케일 인코딩을 사용합니다.
====

이 섹션의 나머지 부분에서는 FreeBSD 시스템에서 로캘을 구성하는 다양한 방법에 대해 설명합니다. 다음 섹션에서는 i18n을 지원하는 애플리케이션을 찾고 컴파일할 때 고려해야 할 사항에 대해 설명합니다.

[[setting-locale]]
=== 로그인 셸의 로캘 설정

로캘 설정은 사용자의 [.filename]#~/.login_conf# 또는 사용자 셸의 시작 파일([.filename]#~/.profile#, [.filename]#~/.bashrc# 또는 [.filename]#~/.cshrc#)에서 구성할 수 있습니다.

두 개의 환경 변수를 설정해야 합니다:

* 로캘을 설정하는 `LANG`
* 애플리케이션에서 사용하는 MIME 문자 집합을 설정하는 `MM_CHARSET`

사용자의 셸 구성 외에도 특정 애플리케이션 구성 및 Xorg 구성에 대해서도 이러한 변수를 설정해야 합니다.

필요한 변수를 할당하는 데는 권장 방법인 <<login-class,login class>> 방법과 <<startup-file,startup file>> 방법의 두 가지 방법을 사용할 수 있습니다. 다음 두 섹션에서는 두 가지 방법의 사용법을 설명합니다.

[[login-class]]
==== 로그인 클래스 방법 (Login Classes Method)

이 첫 번째 방법은 가능한 모든 셸에 대해 로캘 이름 및 MIME 문자 집합에 필요한 환경 변수를 할당하므로 권장되는 방법입니다. 이 설정은 각 사용자가 수행하거나 수퍼유저가 모든 사용자에 대해 구성할 수 있습니다.

이번 최소 예시에서는 개별 사용자의 홈 디렉터리인 [.filename]#.login_conf#에서 Latin-1 인코딩을 위해 두 변수를 모두 설정합니다:

[.programlisting]
....
me:\
	:charset=ISO-8859-1:\
	:lang=de_DE.ISO8859-1:
....

다음은 BIG-5 인코딩에서 중국어 번체 변수를 설정하는 사용자의 [.filename]#~/.login_conf# 예입니다. 일부 애플리케이션은 중국어, 일본어 및 한국어에 대한 로캘 변수를 올바르게 인식하지 못하므로 더 많은 변수가 필요합니다:

[.programlisting]
....
#Users who do not wish to use monetary units or time formats
#of Taiwan can manually change each variable
me:\
	:lang=zh_TW.Big5:\
	:setenv=LC_ALL=zh_TW.Big5,LC_COLLATE=zh_TW.Big5,LC_CTYPE=zh_TW.Big5,LC_MESSAGES=zh_TW.Big5,LC_MONETARY=zh_TW.Big5,LC_NUMERIC=zh_TW.Big5,LC_TIME=zh_TW.Big5:\
	:charset=big5:\
	:xmodifiers="@im=gcin": #Set gcin as the XIM Input Server
....

또는 수퍼유저가 시스템의 모든 사용자에대해 현지화를 구성할 수 있습니다. [filename]#/etc/login.conf#의 다음 변수는 로캘 및 MIME 문자 집합을 설정합니다:

[.programlisting]
....
language_name|Account Type Description:\
	:charset=MIME_charset:\
	:lang=locale_name:\
	:tc=default:
....

따라서 이전 Latin-1 예제는 다음과 같습니다:

[.programlisting]
....
german|German Users Accounts:\
	:charset=ISO-8859-1:\
	:lang=de_DE.ISO8859-1:\
	:tc=default:
....

이러한 변수에 대한 자세한 내용은 man:login.conf[5]를 참조하세요. 이미 사전 정의된 _russian_ 클래스가 포함되어 있습니다.

[filename]#/etc/login.conf#를 편집할 때마다 다음 명령을 실행하여 기능 데이터베이스를 업데이트해야 합니다:

[source, shell]
....
# cap_mkdb /etc/login.conf
....

[NOTE]
====
최종 사용자의 경우, 변경 사항을 적용하려면 [.filename]#~/.login_conf#에서 `cap_mkdb` 명령을 실행해야 합니다.
====

===== 로그인 클래스를 변경하는 유틸리티

[filename]#/etc/login.conf#를 수동으로 편집하는 것 외에도 신규 사용자의 로캘을 설정할 수 있는 여러 유틸리티가 있습니다.

`vipw`를 사용하여 새 사용자를 추가할 때는 _language_를 지정하여 로캘을 설정하세요:

[.programlisting]
....
user:password:1111:11:language:0:0:User Name:/home/user:/bin/sh
....

`adduser`를 사용하여 새 사용자를 추가할 때 기본 언어는 모든 새 사용자에 대해 미리 구성하거나 개별 사용자에 대해 지정할 수 있습니다.

모든 신규 사용자가 동일한 언어를 사용하는 경우 [.filename]#/etc/adduser.conf#에서 `defaultclass=_language_`를 설정하세요.

사용자를 만들 때 이 설정을 재정의하려면 이 프롬프트에서 필요한 로캘을 입력합니다:

[source, shell]
....
Enter login class: default []:
....

또는 `adduser`를 호출할 때 설정할 로캘을 지정합니다:

[source, shell]
....
# adduser -class language
....

새 사용자를 추가하기 위해 `pw`를 사용하는 경우 다음과 같이 로캘을 지정합니다:

[source, shell]
....
# pw useradd user_name -L language
....

기존 사용자의 로그인 클래스를 변경하기위해 `chpass`를 사용할 수 있습니다. 슈퍼유저로 호출하고 수정할 사용자 이름을 인수로 제공합니다.

[source, shell]
....
# chpass user_name
....


[[startup-file]]
==== 셸 시작파일 방법 (Shell Startup File Method)

두 번째 방법은 사용하는 셸마다 구성 파일이 다르고 구문도 다르기 때문에 수동 구성이 필요하므로 권장되지 않습니다. 예를 들어 `sh` 셸의 언어를 독일어로 설정하려면 [.filename]#~/.profile#에 다음 줄을 추가하여 해당 사용자에 대해서만 셸을 설정할 수 있습니다. 또한 [.filename]#/etc/profile# 또는 [.filename]#/usr/share/skel/dot.profile#에 다음 명령줄을 추가하여 모든 사용자에 대해 해당 셸을 설정할 수도 있습니다:

[.programlisting]
....
LANG=de_DE.ISO8859-1; export LANG
MM_CHARSET=ISO-8859-1; export MM_CHARSET
....

그러나 `csh` 셸의 경우 구성 파일의 이름과 사용되는 구문이 다릅니다. 이는 [.filename]#~/.login#, [.filename]#/etc/csh.login# 또는 [.filename]#/usr/share/skel/dot.login#에 대한 설정과 동일합니다:

[.programlisting]
....
setenv LANG de_DE.ISO8859-1
setenv MM_CHARSET ISO-8859-1
....

문제를 더 복잡하게 만드는 것은 [.filename]#~/.xinitrc#에서 Xorg를 구성하는 데 필요한 구문도 셸에 따라 다르다는 점입니다. 첫 번째 예제는 `sh` 셸에 대한 것이고 두 번째 예제는 `csh` 셸에 대한 것입니다:

[.programlisting]
....
LANG=de_DE.ISO8859-1; export LANG
....


[.programlisting]
....
setenv LANG de_DE.ISO8859-1
....


[[setting-console]]
=== 콘솔 설정

콘솔에서 여러 가지 현지화된 글꼴을 사용할 수 있습니다. 사용 가능한 글꼴 목록을 보려면 `ls /usr/share/syscons/fonts`를 입력하세요. 콘솔 글꼴을 구성하려면 [.filename]#/etc/rc.conf#에 [.filename]#.fnt# 접미사 없이 _폰트 이름_을 지정합니다:

[.programlisting]
....
font8x16=font_name
font8x14=font_name
font8x8=font_name
....

키맵과 스크린맵은 [.filename]#/etc/rc.conf#에 다음을 추가하여 설정할 수 있습니다:

[.programlisting]
....
scrnmap=screenmap_name
keymap=keymap_name
keychange="fkey_number sequence"
....

사용 가능한 스크린맵 목록을 보려면 `ls /usr/share/syscons/scrnmaps`를 입력합니다. 스크린맵_이름_을 지정할 때 [.filename]#.scm# 접미사를 포함하지 마세요. 화면 글꼴이 비트 8 열을 사용하는 경우, 문자가 의사 그래픽 영역을 넘어서기 때문에 VGA 어댑터의 글꼴 문자 매트릭스에서 비트 8을 비트 9로 매핑해주는 적절한 스크린 맵이 필요합니다.

사용 가능한 키맵 목록을 보려면 `ls /usr/share/syscons/keymaps`를 입력합니다. 키맵_이름_을 지정할 때 [.filename]#.kbd# 접미사를 포함하지 마세요. 재부팅하지 않고 키맵을 테스트하려면 man:kbdmap[1]을 사용합니다.

키맵에서는 펑션키 시퀀스를 정의할 수 없으므로, 일반적으로 선택한 단말기 유형에 맞게 펑션키를 프로그래밍하도록 `키 변경` 항목이 필요합니다.

그런 다음 모든 가상 터미널([.filename]#/etc/ttys#)에 적절한 콘솔 터미널 유형을 설정합니다. <<locale-charset>>에는 사용 가능한 터미널 유형이 요약되어 있습니다:

[[locale-charset]]
.문자세트에 대한 적절한 터미널 유형
[cols="1,1", frame="none", options="header"]
|===
| Character Set
| Terminal Type

|ISO8859-1 or ISO8859-15
|`cons25l1`

|ISO8859-2
|`cons25l2`

|ISO8859-7
|`cons25l7`

|KOI8-R
|`cons25r`

|KOI8-U
|`cons25u`

|CP437 (VGA default)
|`cons25`

|US-ASCII
|`cons25w`
|===

와이드 문자나 멀티바이트 문자를 사용하는 언어의 경우, FreeBSD 포트 컬렉션에서 해당 언어용 콘솔을 설치하세요. 사용 가능한 포트는 <<locale-console>>에 요약되어 있습니다. 설치시 포트의 [.filename]#pkg-message# 또는 매뉴얼 페이지에서 구성 및 사용 지침을 참조하세요.

[[locale-console]]
.포트 컬렉션에서 사용 가능한 콘솔
[cols="1,1", frame="none", options="header"]
|===
| Language
| Port Location

|Traditional Chinese (BIG-5)
|package:chinese/big5con[]

|Chinese/Japanese/Korean
|package:chinese/cce[]

|Chinese/Japanese/Korean
|package:chinese/zhcon[]

|Japanese
|package:chinese/kon2[]

|Japanese
|package:japanese/kon2-14dot[]

|Japanese
|package:japanese/kon2-16dot[]
|===

[.filename]#/etc/rc.conf#에서 마우스 데몬(moused)이 활성화된 경우 추가 구성이 필요할 수 있습니다. 기본적으로 man:syscons[4] 드라이버의 마우스 커서는 문자 집합에서 `0xd0`-`0xd3` 범위를 차지합니다. 언어에서 이 범위를 사용하는 경우 [.filename]#/etc/rc.conf#에 다음 줄을 추가하여 커서 범위를 이동하세요:

[.programlisting]
....
mousechar_start=3
....

=== Xorg 설정

crossref:x11[x11,The X Window System]에서는 Xorg를 설치하고 구성하는 방법을 설명합니다. 현지화를 위해 Xorg를 구성할 때, 추가 글꼴과 입력 방법은 FreeBSD 포트 컬렉션에서 사용할 수 있습니다. 글꼴 및 메뉴와 같은 애플리케이션별 i18n 설정은 [.filename]#~/.Xresources#에서 조정할 수 있으며, 사용자가 그래픽 애플리케이션 메뉴에서 선택한 언어를 볼 수 있도록 해야 합니다.

X 입력 방법(XIM) 프로토콜은 영어가 아닌 문자를 입력하기 위한 Xorg 표준입니다. <<locale-xim>>는 FreeBSD 포트 컬렉션에서 사용할 수 있는 입력용 애플리케이션을 설명하고 있습니다. 추가적인 Fcitx와 Uim 응용 프로그램도 사용할 수 있습니다.

[[locale-xim]]
.사용가능한 입력방법
[cols="1,1", frame="none", options="header"]
|===
| Language
| Input Method

|Chinese
|package:chinese/gcin[]

|Chinese
|package:chinese/ibus-chewing[]

|Chinese
|package:chinese/ibus-pinyin[]

|Chinese
|package:chinese/oxim[]

|Chinese
|package:chinese/scim-fcitx[]

|Chinese
|package:chinese/scim-pinyin[]

|Chinese
|package:chinese/scim-tables[]

|Japanese
|package:japanese/ibus-anthy[]

|Japanese
|package:japanese/ibus-mozc[]

|Japanese
|package:japanese/ibus-skk[]

|Japanese
|package:japanese/im-ja[]

|Japanese
|package:japanese/kinput2[]

|Japanese
|package:japanese/scim-anthy[]

|Japanese
|package:japanese/scim-canna[]

|Japanese
|package:japanese/scim-honoka[]

|Japanese
|package:japanese/scim-honoka-plugin-romkan[]

|Japanese
|package:japanese/scim-honoka-plugin-wnn[]

|Japanese
|package:japanese/scim-prime[]

|Japanese
|package:japanese/scim-skk[]

|Japanese
|package:japanese/scim-tables[]

|Japanese
|package:japanese/scim-tomoe[]

|Japanese
|package:japanese/scim-uim[]

|Japanese
|package:japanese/skkinput[]

|Japanese
|package:japanese/skkinput3[]

|Japanese
|package:japanese/uim-anthy[]

|Korean
|package:korean/ibus-hangul[]

|Korean
|package:korean/imhangul[]

|Korean
|package:korean/nabi[]

|Korean
|package:korean/scim-hangul[]

|Korean
|package:korean/scim-tables[]

|Vietnamese
|package:vietnamese/xvnkb[]

|Vietnamese
|package:vietnamese/x-unikey[]
|===

[[l10n-compiling]]
== i18n 애플리케이션 찾기

i18n 애플리케이션은 라이브러리 아래의 i18n 키트를 사용하여 프로그래밍됩니다. 이를 통해 개발자는 간단한 파일을 작성하고 표시되는 메뉴와 텍스트를 각 언어로 번역할 수 있습니다.

link:https://www.FreeBSD.org/ports/[FreeBSD Ports Collection]에는 여러 언어의 와이드 문자 또는 멀티바이트 문자를 기본으로 지원하는 많은 응용 프로그램이 포함되어 있습니다. 이러한 응용 프로그램들은 쉽게 식별할 수 있도록 이름에 `i18n`이 포함되어 있습니다. 그러나 필요한 언어를 항상 지원하는 것은 아닙니다.

일부 애플리케이션은 특정 문자셋으로 컴파일할 수 있습니다. 이는 일반적으로 포트의 [.filename]#Makefile#에서 또는 구성할 값을 전달하여 수행됩니다. 필요한 구성 값을 결정하는 방법에 대한 자세한 내용은 각 FreeBSD 포트의 소스에 있는 i18n 문서를 참조하거나 포트의 [.filename]#Makefile#에서 포트를 빌드할 때 사용할 컴파일 옵션을 확인할 수 있습니다.

[[lang-setup]]
== 특정 언어에 대한 로캘 구성

이 섹션에서는 러시아어를 위해 FreeBSD 시스템을 로컬라이즈하기 위한 구성 예제를 제공합니다. 그런 다음, 다른 언어를 로컬라이즈하기 위한 몇 가지 추가 리소스를 제공합니다.

[[ru-localize]]
=== 러시아어 (KOI8-R Encoding)

이 섹션에서는 러시아어에 맞게 FreeBSD 시스템을 현지화하는 데 필요한 설정을 보여줍니다. 각 설정 유형에 대한 자세한 설명은 <<using-localization,Using Localization>>을 참조하십시오.

로그인 셸에 이 로캘을 설정하려면 각 사용자의 [.filename]#~/.login_conf#에 다음 줄을 추가합니다:

[.programlisting]
....
me:My Account:\
	:charset=KOI8-R:\
	:lang=ru_RU.KOI8-R:
....

콘솔을 구성하려면 [.filename]#/etc/rc.conf#에 다음 줄을 추가합니다:

[.programlisting]
....
keymap="ru.utf-8"
scrnmap="utf-82cp866"
font8x16="cp866b-8x16"
font8x14="cp866-8x14"
font8x8="cp866-8x8"
mousechar_start=3
....

[.filename]#/etc/ttys#의 각 `ttyv` 항목에 대해 터미널 유형으로 `cons25r`을 사용합니다.

인쇄를 구성하려면 러시아어 문자를 사용하는 대부분의 프린터가 하드웨어 코드 페이지 CP866를 사용하므로, KOI8-R에서 CP866으로 변환하기 위한 특수 출력 필터가 필요합니다. FreeBSD에는 이 목적을 위한 기본 필터인 [.filename]#/usr/libexec/lpr/ru/koi2alt#이 포함되어 있습니다. 이 필터를 사용하기 위해서는 [.filename]#/etc/printcap#에 다음 항목을 추가합니다:

[.programlisting]
....
lp|Russian local line printer:\
	:sh:of=/usr/libexec/lpr/ru/koi2alt:\
	:lp=/dev/lpt0:sd=/var/spool/output/lpd:lf=/var/log/lpd-errs:
....

추가적인 설명은 man:printcap[5]을 참조하세요.

마운트된 MS-DOS(R) 파일 시스템에서 러시아어 파일 이름에 대한 지원을 구성하려면 [.filename]#/etc/fstab#에 항목을 추가할 때 `-L`과 로캘 이름을 포함하세요:

[.programlisting]
....
/dev/ad0s2      /dos/c  msdos   rw,-Lru_RU.KOI8-R 0 0
....

추가적인 설명은 man:mount_msdosfs[8]을 참조하세요.

Xorg용 러시아어 글꼴을 구성하려면 package:x11-fonts/xorg-fonts-cyrillic[] 패키지를 설치하세요. 그런 다음 [.filename]#/etc/X11/xorg.conf#에서 `”Files”` 섹션을 확인합니다. 다음 내용은 다른 `FontPath` 항목보다 _앞에_ 추가해야 합니다:

[.programlisting]
....
FontPath   "/usr/local/lib/X11/fonts/cyrillic"
....

포트 컬렉션에는 추가로 사용할 수 있는 키릴 폰트가 있습니다.

러시아어 키보드를 활성화하려면 [.파일명]#/etc/xorg.conf#의 `”Keyboard”` 섹션에 다음을 추가하세요:

[.programlisting]
....
Option "XkbLayout"   "us,ru"
Option "XkbOptions"  "grp:toggle"
....

해당 파일에서 `XkbDisable`이 주석 처리되었는지 확인합니다.

`grp:toggle`의 경우 kbd:[Right Alt]를 사용하고, `grp:ctrl_shift_toggle`의 경우 kbd:[Ctrl+Shift]를 사용합니다. `grp:caps_toggle`의 경우는 kbd:[CapsLock]을 사용합니다. 이전 kbd:[CapsLock] 함수는 LAT 모드에서만 kbd:[Shift+CapsLock]을 사용할 수 있습니다. 알 수 없는 이유로 인해 `grp:caps_toggle`은 Xorg에서 작동하지 않습니다.

키보드에 “Windows(R)” 키가 있고 알파벳이 아닌 일부 키가 잘못 매핑되어 있는 경우 [.filename]#/etc/xorg.conf#에 다음 줄을 추가하세요:

[.programlisting]
....
Option "XkbVariant" ",winkeys"
....

[NOTE]
====
러시아어 XKB 키보드는 현지화되지 않은 응용 프로그램에서 작동하지 않을 수 있습니다. 최소한으로 현지화된 애플리케이션은 프로그램 초기에 `XtSetLanguageProc (NULL, NULL, NULL);` 함수를 호출해야 합니다.
====

Xorg 애플리케이션 현지화에 대한 자세한 지침은 http://koi8.pp.ru/xwin.html[http://koi8.pp.ru/xwin.html]를 참조하세요. KOI8-R 인코딩에 대한 자세한 내용은 http://koi8.pp.ru/[http://koi8.pp.ru/]를 참조하세요.

=== 언어별 추가 리소스

이 섹션에는 다른 로캘을 구성하기 위한 추가 리소스가 나와 있습니다.

대만 중국어 번체::
FreeBSD-대만 프로젝트는 http://netlab.cse.yzu.edu.tw/\~statue/freebsd/zh-tut/[http://netlab.cse.yzu.edu.tw/~statue/freebsd/zh-tut/]에서 FreeBSD를 위한 중국어 HOWTO를 제공합니다.

그리스어 로캘::
FreeBSD의 그리스어 지원에 대한 전체 자료는 공식 FreeBSD 그리스어 문서의 일부로 그리스어로만 제공되는 https://www.FreeBSD.org/doc/gr/articles/greek-language-support/[이곳]에서 확인할 수 있습니다.

일본어 및 한국어 로캘::
일본어는 http://www.jp.FreeBSD.org/[http://www.jp.FreeBSD.org/], 한국어는 http://www.kr.FreeBSD.org/[http://www.kr.FreeBSD.org/]를 참조하세요.

비 영어권 FreeBSD 문서::
일부 FreeBSD 기여자들은 FreeBSD 문서를 다른 언어로 번역했습니다. https://www.FreeBSD.org/[FreeBSD 웹 사이트] 링크 또는 [.filename]#/usr/share/doc#에 있는 링크를 통해 확인할 수 있습니다.
