# $Id: Makefile,v 1.2 1999-08-17 21:35:52 nik Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ../../..

.include "../../../share/mk/docproj.docbook.mk"
