=== GCC: updating GCC_DEFAULT and other improvements

Links: +
link:https://gcc.gnu.org[GCC Project] URL: link:https://gcc.gnu.org[https://gcc.gnu.org] +
link:https://gcc.gnu.org/gcc-11/[GCC 11 release series] URL: link:https://gcc.gnu.org/gcc-11/[https://gcc.gnu.org/gcc-11/]

Contact: <toolchain@FreeBSD.org> +
Contact: Gerald Pfeifer <gerald@pfeifer.com> +
Contact: Lorenzo Salvadore <salvadore@FreeBSD.org> +
Contact: Piotr Kubaj <pkubaj@FreeBSD.org>

 * salvadore@ worked on the upgrade of GCC_DEFAULT in Mk/bsd.default-versions.mk from 10 to 11, opening bug reports based on antoine@'s exp-runs and fixing some: many thanks to all those that helped with this task.
   The GCC_DEFAULT update from GCC 10 to GCC 11 has now been committed by gerald@ and happened in time for the next quarterly branch.
   link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258378[https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258378]

 * pkubaj@ switched GCC bootstrapping to use Link Time Optimization for GCC itself for GCC 11 and newer by introducing a new option enabled by default.
   Building with LTO_BOOTSTRAP enabled requires significant amounts of memory and time.
   How much resources are actually needed depends on your configuration (e.g. are you building from ports or with poudriere? What is your architecture?).
   To give an idea, link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264949#c17[a user reported needing 5 GiB of tmpfs], while in link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265254#c2[PR 265254] a need of about 130 GB of memory is estimated due to an excessive amount of processes spawning (see also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106328).
   Consider disabling LTO_BOOTSTRAP in favor of STANDARD_BOOTSTRAP (or disabling BOOTSTRAP altogether) in case that is a problem.

 * pkubaj@ also added lang/gcc12 and lang/gcc13-devel ports and updated lang/gcc9 to 9.5.

 * Help is still needed with these three changes to work through with upstream GCC (requires src expertise, not ports):

     ** upstreaming lang/gcc11/patch-gets-no-more
     ** upstreaming lang/gcc11/patch-arm-unwind-cxx-support
     ** link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256874[https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256874]
