=== Feature Complete Port of Intel's igt-gpu-tools

Links: +
link:https://wiki.freebsd.org/SummerOfCode2022Projects/ImprovingTheLinuxKPICompatibilityLayerForTheFreeBSDGraphicsStack/[FreeBSD Wiki Project Page] URL:
link:https://wiki.freebsd.org/SummerOfCode2022Projects/ImprovingTheLinuxKPICompatibilityLayerForTheFreeBSDGraphicsStack/[https://wiki.freebsd.org/SummerOfCode2022Projects/ImprovingTheLinuxKPICompatibilityLayerForTheFreeBSDGraphicsStack] +
link:https://cdaemon.com/tags/gsoc2022/[Status Reports] URL:
link:https://cdaemon.com/tags/gsoc2022/[https://cdaemon.com/tags/gsoc2022]

Contact: Jake Freeland <jfree@freebsd.org>

Intel’s igt-gpu-tools serves as a generic testing suite for drm drivers on Linux.
The igt-gpu-tools suite is separated into tests and tools that target kms, memory management, and command submission.
The utility provides low-level reporting for transparent tracking of kernel changes and efficient debugging of modern drm drivers.

Porting the project to FreeBSD could introduce greater stability in future releases of FreeBSD’s LinuxKPI-driven drm drivers.
A proper kms-driven testing suite could also increase code output and bring the FreeBSD desktop experience up to speed with the Linux codebase.

The project officially started under FreeBSD's Google Summer of Code program on June 13, 2022.
My adapted code can compile with non-FreeBSD compatible snippets removed.
The plan is to reimplement these stripped components in a POSIX compliant fashion.

Notable incompatible code includes: debugfs, libkmod, libprocps, Linux performance events, and Linux userfaultfd.
If you would like to assist in the porting of libkmod or libprocps into the ports tree, don't hesitate to contact me.

When the FreeBSD compatible code is complete, I will run the modified igt tests using a host of graphics processors on FreeBSD 14.0-CURRENT.
If all is well, the project's diff will be submitted into the ports tree.

Sponsor: FreeBSD Google Summer of Code
