=== Ports Collection

Links: +
link:https://www.FreeBSD.org/ports/[About FreeBSD Ports] URL:link:https://www.FreeBSD.org/ports/[https://www.FreeBSD.org/ports/] +
link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[Contributing to Ports] URL: link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[https://docs.freebsd.org/en/articles/contributing/#ports-contributing] +
link:http://portsmon.freebsd.org/[FreeBSD Ports Monitoring] URL: link:http://portsmon.freebsd.org/[http://portsmon.freebsd.org/] +
link:https://www.freebsd.org/portmgr/[Ports Management Team] URL: link:https://www.freebsd.org/portmgr/[https://www.freebsd.org/portmgr/] +
link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[Ports Tarball] URL: link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[http://ftp.freebsd.org/pub/FreeBSD/ports/ports/]

Contact: René Ladan <portmgr-secretary@FreeBSD.org> +
Contact: FreeBSD Ports Management Team <portmgr@FreeBSD.org>

The Ports Management Team is responsible for overseeing the overall direction of the Ports Tree, building packages, and personnel matters.
Below is what happened in the last quarter.

The number of ports is slightly above 30,000.
The last quarter saw 9,137 commits by 151 committers on the "main" and 589 commits by 61 committers on the "2022Q2" branch.
At the time of writing, there are 2,700 open ports PRs of which 682 are unassigned.
Compared to the previous quarter, there was a slight decrease in commit activity and a constant number of PRs.
Note: Freshports appears to overcount substantially.
This quarter's ports count was derived differently and is not comparable with the previous quarter's.

During the last quarter, portmgr
welcomed back salvadore@ but also said goodbye to seven ports committers due to lack of activity.

In its bi-weekly meetings, portmgr discussed the following topics:
* the future of ca_root_nss
* feasibility of the base system providing certain .pc files
* ways to deal with incompatibilities in kernel module ports on minor version upgrades of the base system

Following a discussion among developers, portmgr decided to grant all documentation and source
committers approval to fix any documentation-related error in the Ports Tree which does not affect its functionality.

The following changes were made to the Ports Tree during 2022q2:
* pkg got updated to version 1.18.3, Firefox to version 102.0 and Chromium to version 103.0.50060.53
* Default versions of GCC, Lazarus, Python and Ruby got updated to respectively 11 (powerpcspe keeps version 8), 2.2.2, 3.9, and 3.0.
* Two new USES were added, gstreamer to support ports based on GStreamer plugins and pytest to help testing with pytest.
