---
title: "Информационная безопасность FreeBSD"
sidenav: support
---

include::shared/en/urls.adoc[]
include::shared/releases.adoc[]

= Информационная безопасность FreeBSD

== Введение

FreeBSD относится к безопасности очень серьёзно, и её разработчики постоянно работают над тем, чтобы сделать операционную систему максимально защищённой. На этой странице представлена информация о том, что делать в случае обнаружения уязвимости безопасности, затрагивающей вашу систему.

== Содержание

* <<reporting,Сообщение об инцидентах безопасности FreeBSD>>
* <<recent,Недавние уязвимости безопасности FreeBSD>>
* <<advisories,Объяснение бюллетеней безопасности FreeBSD>>
* <<how,Как обновить вашу систему>>
* <<sup,Поддерживаемые релизы FreeBSD>>
* <<model,Модель поддержки FreeBSD>>

[[reporting]]
== Как и куда сообщать о проблеме в информационной безопасности FreeBSD

Все проблемы информационной безопасности FreeBSD следует направлять на адрес mailto:secteam@FreeBSD.org[службы информационной безопасности FreeBSD] или, если необходим более высокий уровень конфиденциальности, в зашифрованном при помощи PGP виде на адрес mailto:security-officer@FreeBSD.org[службы Директора по информационной безопасности], используя link:../../security/so_public_key.asc[ключ PGP Офицера информационной безопасности]. Дополнительная информация доступна на странице link:reporting/[сообщения об инцидентах безопасности FreeBSD].

[[when-reporting]]
== Когда выпускается бюллетень безопасности (Security Advisory)?

По каждому сообщённому вопросу создаётся внутренний номер для отслеживания, кроме случаев, когда он очевидно не является проблемой безопасности. Чтобы определить, требуется ли выпуск бюллетень безопасности, мы используем следующую схему:

* Является ли это уязвимостью повышения привилегий?
* Является ли это уязвимостью внедрения кода?
* Является ли это уязвимостью раскрытия памяти или утечки данных?
** Исходящей либо из ядра
** Из привилегированного процесса
** Из процесса, принадлежащего другому пользователю?
* Является ли это уязвимостью отказа в обслуживании?
** Только если она используется удалённо, где «удалённо» означает «из другого широковещательного домена», поэтому атаки на основе ARP и/или NDP не подпадают под эту категорию.
* Является ли это уязвимостью обхода изоляции системы без дополнительной поддержки или использования других уязвимостей?
* Является ли это сбоем, который может привести к генерации небезопасных криптографических ключей, например, ошибкой PRNG?

Для пунктов, подпадающих под эти категории, выпуск бюллетеня безопасности весьма вероятен. Пункты, не входящие в этот список, рассматриваются индивидуально, и тогда определяется, будет ли по ним выпущен бюллетень безопасности или уведомление об ошибке (Errata Notice).

После того как будет определено, что выпуск бюллетеня безопасности обоснован, отправитель предоставляет номер CVE, если он уже был запрошен, или мы используем номер из доступного пула FreeBSD.

[[recent]]
== Недавние уязвимости безопасности FreeBSD

Полный список всех уязвимостей безопасности, затрагивающих базовую систему, можно найти link:advisories[на этой странице].

Полный список всех других ошибок, затрагивающих базовую систему, можно найти link:notices[на этой странице].

[[advisories]]
== Объяснение бюллетеней безопасности FreeBSD

Бюллетени, затрагивающие базовую систему, рассылаются по следующим спискам рассылки:

* FreeBSD-security-notifications@FreeBSD.org
* FreeBSD-security@FreeBSD.org
* FreeBSD-announce@FreeBSD.org

Список выпущенных бюллетеней можно найти на странице link:advisories[Бюллетени безопасности FreeBSD].

Бюллетени всегда подписываются с использованием link:so_public_key.asc[PGP-ключа] Директора по информационной безопасности FreeBSD и архивируются вместе со связанными с ними патчами на веб-сервере https://security.FreeBSD.org в подкаталогах https://security.FreeBSD.org/advisories/[advisories] и https://security.FreeBSD.org/patches/[patches].

Директор по информационной безопасности FreeBSD предоставляет Бюллетени безопасности для _-STABLE веток_ и _веток безопасности_. (Бюллетени не выпускаются для ветки _-CURRENT_, которая в первую очередь ориентирована на разработчиков FreeBSD.)

* Теги ветки -STABLE имеют имена вида `stable/13`. Соответствующие сборки имеют имена вида `FreeBSD 13.2-STABLE`.
* Каждый выпуск FreeBSD имеет связанную с ним ветку безопасности. Теги веток безопасности имеют имена вида `releng/13.2`. Соответствующие сборки имеют имена вида `FreeBSD 13.2-RELEASE-p1`.

Проблемы, затрагивающие Коллекцию портов FreeBSD, рассматриваются отдельно в https://vuxml.FreeBSD.org/[документах VuXML для FreeBSD].

Ошибки, затрагивающие базовую систему, но не классифицированные как уязвимости безопасности, рассматриваются отдельно на странице link:notices[Уведомления об исправлениях FreeBSD].

[[how]]
== Как обновить вашу систему

Для пользователей, которые ранее установили бинарную версию FreeBSD (например, {rel131-current} или {rel123-current}), команды:

`# freebsd-update fetch`

`# freebsd-update install`

Если это не сработает, следуйте другим инструкциям в интересующем вас бюллетене безопасности.

Обратите внимание, что приведённая выше процедура предназначена только для пользователей, которые ранее установили бинарный дистрибутив. Тем, кто собирал систему из исходных кодов, потребуется обновить своё дерево исходных кодов.

Для получения более подробной информации обратитесь к разделу link:{handbook}cutting-edge/#freebsdupdate-security-patches[как применять патчи безопасности].

[[sup]]
== Поддерживаемые выпуски FreeBSD

Каждый релиз поддерживается Директором по информационной безопасности только в течение ограниченного времени.

Обозначения и предполагаемый срок службы всех поддерживаемых в настоящее время веток и их соответствующих релизов приведены ниже. Столбец _Ожидаемый EoL (конец срока службы)_ указывает самую раннюю дату, когда поддержка этой ветки или релиза будет прекращена. Обратите внимание, что эти даты могут быть перенесены, если того потребуют обстоятельства.

link:unsupported[Более старые выпуски] не поддерживаются, и пользователям настоятельно рекомендуется обновиться до одного из этих поддерживаемых релизов:

[.tblbasic]
[cols=",,,",options="header",]
|===
|Ветка |Релиз |Дата релиза |Ожидаемый EoL (конец срока службы)
|stable/14 |н/д |н/д |30 ноября 2028 г.
|releng/14.3 |14.3-RELEASE |10 июня 2025 г. |30 июня 2026 г.
|stable/13 |н/д |н/д |30 апреля 2026 г.
|releng/13.5 |13.5-RELEASE |11 марта 2025 г. |30 апреля 2026 г.
|===

В преддверии выпуска может быть опубликовано несколько версий -BETA и -RC для целей тестирования. Эти релизы поддерживаются всего несколько недель, по мере наличия ресурсов, и не будут перечислены на этой странице как поддерживаемые. Пользователям настоятельно не рекомендуется использовать эти релизы в системах промышленной эксплуатации.

[[model]]
== Модель поддержки FreeBSD

В соответствии с текущей моделью поддержки стабильная ветка каждой основной версии явно поддерживается в течение 5 лет, в то время как каждый отдельный релиз с точкой поддерживается всего три месяца после выхода следующего релиза с точкой.

Подробности и обоснование этой модели можно найти в https://lists.freebsd.org/pipermail/freebsd-announce/2015-February/001624.html[официальном объявлении], отправленном в феврале 2015 года.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (15.10.2025): a3c08199268bed7b921428d6e39f095a0758c333
//
