---
title: "Устав Директора по информационной безопасности FreeBSD"
sidenav: support
---

= Устав Директора по информационной безопасности FreeBSD

[ Принято Основной командой (Core team) в феврале 2002 г. ]

== 1. Введение

Миссия Директора по информационной безопасности FreeBSD заключается в защите сообщества пользователей FreeBSD путём: информирования сообщества об ошибках, уязвимостях, популярных атаках и других рисках; выступая в качестве связующего звена от имени проекта FreeBSD с внешними организациями по вопросам, связанным с конфиденциальными, не публикуемыми проблемами безопасности; и способствуя распространению информации, необходимой для безопасной эксплуатации систем FreeBSD, такой как советы по системному администрированию и программированию.

== 2. Обязанности

В обязанности Директора по информационной безопасности входят:

* Разрешение споров, связанных с безопасностью.
* Своевременное устранение программных ошибок, влияющих на безопасность FreeBSD.
* Публикация уведомлений о безопасности для FreeBSD.
* Ответ на запросы поставщиков по вопросам безопасности.
* Аудит максимально возможного объема кода, но особенно кода, связанного с безопасностью и сетями.
* Мониторинг соответствующих каналов для получения отчетов об ошибках, уязвимостях и других обстоятельствах, которые могут повлиять на безопасность системы FreeBSD.
* Участие в разработке архитектуры FreeBSD для оказания положительного влияния на безопасность системы.
* Директор по информационной безопасности FreeBSD управляет PGP-ключом Директора по информационной безопасности FreeBSD.

== 3. Полномочия

Основная команда FreeBSD делегировала полномочия в области безопасности Директору по информационной безопасности, при этом Директор по информационной безопасности подотчётен Основной команде в использовании этих полномочий. От него ожидается проявление здравого смысла и соответствующей осмотрительности при использовании любых из назначенных полномочий. Любые действия, которые конфликтуют с руководящими принципами для коммиттеров, требуют особенно тщательной оценки.

В частности, с учётом ограничений подотчетности, Директору по информационной безопасности предоставлены следующие полномочия:

* Ускоренные коммиты: Офицер по информационной безопасности может не соблюдать обычные руководящие принципы для коммиттеров в областях, связанных с безопасностью.
* Право вето: Офицер по информационной безопасности имеет решающее слово в вопросах безопасности и может запросить отмену любых коммитов или удаление любых подсистем, которые, по его мнению, наносят ущерб безопасности FreeBSD.
* Команда: Директор по информационной безопасности может формировать команду Директора по информационной безопасности FreeBSD и делегировать соответствующие полномочия и обязанности по своему усмотрению. Состав выбирается Директором по информационной безопасности, но всегда включает почётных Директоров по информационной безопасности --- как раз когда они уже думали, что своё отработали.
* Список рассылки: Список рассылки security-officer@FreeBSD.org администрируется Директором по информационной безопасности.

== 4. Структура

Новый Директор по информационной безопасности  назначается предыдущим Директором по информационной безопасности и утверждается Основной командой. Директор по информационной безопасности подотчётен Основной команде.

Участники команды Директора по информационной безопасности FreeBSD выбираются Директором по информационной безопасности, и они подотчётны Директору по информационной безопасности и Основной команде. От членов команды Директора по информационной безопасности ожидается помощь Директору по информационной безопасности в выполнении его обязанностей, а также иное участие в защите сообщества пользователей FreeBSD.
