# $FreeBSD: www/en/releases/5.0R/Makefile,v 1.1 2002/03/04 08:17:50 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml

SUBDIR=	DP1

.include "${WEB_PREFIX}/share/mk/web.site.mk"
