# $FreeBSD: www/en/releases/5.0R/Makefile,v 1.3 2002/08/31 08:48:09 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml todo.sgml

SUBDIR=	DP1 DP2

.include "${WEB_PREFIX}/share/mk/web.site.mk"
