# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

# DOCS=	announce.sgml credits.sgml install.sgml notes.sgml
DOCS= credits.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
