# $FreeBSD: www/ja/docs/Makefile,v 1.1 2010/07/05 17:00:55 ryusuke Exp $
# Original Revision: 1.6

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
