# $FreeBSD$
# Original Revision: 1.6

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.sgml webresources.sgml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
