---
title: "Проект FreeBSD GNOME: Как с нами связаться"
sidenav: gnome
---

include::shared/ru/urls.adoc[]

= Проект FreeBSD GNOME: Как с нами связаться

== Контактная информация

Все вопросы относительно GNOME на FreeBSD должны отправляться в адрес списка рассылки mailto:freebsd-gnome@FreeBSD.org[freebsd-gnome]. Все пользователи FreeBSD GNOME, а также те, кто имеет желание помочь в усовершенствовании и поддержке GNOME на FreeBSD, могут к нам link:{handbook}#ERESOURCES-SUBSCRIBE[присоединиться]. Однако не нужно оформлять подписку, если вы просто хотите сообщить о проблеме или попросить помощь - просто пошлите сообщение на адрес freebsd-gnome@FreeBSD.org.

Всё обсуждение должно вестись в списке рассылки, если только нет причин общаться с одним из разработчиков напрямую. Далее приводится список лиц, участвующих в Проекте FreeBSD GNOME (в алфавитном порядке):

* mailto:adamw@FreeBSD.org[Adam Weinberger]
* mailto:bland@FreeBSD.org[Alexander Nedotsukov]
* mailto:marcus@FreeBSD.org[Joe Marcus Clarke] (AIM: FreeBSDMarcus)
* mailto:sobomax@FreeBSD.org[Maxim Sobolev]

Разработчиков FreeBSD GNOME можно также найти в IRC. Так что подключайтесь к каналу #freebsd-gnome в сети FreeNode, если вы хотите обсудить GNOME на FreeBSD.
