# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.6

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	15.xml
DOCS+=	index.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
