# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.6

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	10.sgml
DOCS+=	11.sgml
DOCS+=	12.sgml
DOCS+=	13.sgml
DOCS+=	14.sgml
DOCS+=	15.sgml
DOCS+=	index.sgml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
