---
authors:
  - 
    author: 'The FreeBSD Documentation Project'
bookOrder: 5
copyright: '1995-2023 The FreeBSD Documentation Project'
description: 'Veelgestelde vragen (FAQ) voor FreeBSD'
layout: single
tags: ["FAQ", "FreeBSD FAQ"]
title: 'Veelgestelde vragen (FAQ) voor FreeBSD'
trademarks: ["freebsd", "ieee", "linux", "microsoft", "openbsd", "netbsd", "general"]
---

= Veelgestelde vragen (FAQ) voor FreeBSD
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/faq/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[.abstract-title]
Samenvatting

Hier vindt u de veelgestelde vragen (FAQ) voor FreeBSD. Er is alles aan gedaan om deze FAQ zo informatief mogelijk te maken.

'''

toc::[]

[[introduction]]
== Introductie

Welkom in de wereld van FreeBSD! In dit gedeelte vertellen we uitgebreid wat FreeBSD is, waar het vandaan komt en we bespreken doelstellingen, toepassingen en de community achter FreeBSD.

Ontdek de oorsprong van de naam, lees hoe u kunt bijdragen aan dit project en verken het rijke ecosysteem van FreeBSD binnen de context van opensource besturingssystemen.

[[what-is-FreeBSD]]
=== Wat is FreeBSD?

FreeBSD is een veelzijdig, opensource UNIX(R)-achtig besturingssysteem dat bekend staat om zijn exceptionele stabiliteit, beveiliging en prestaties. Het is gebaseerd op het UNIX besturingssysteem van de Berkeley Software Distribution (BSD) en verder doorontwikkeld door een toegewijde community van vrijwilligers.

FreeBSD biedt een krachtige en naar wens in te stellen omgeving, die geschikt is voor een breed scala aan toepassingen, van servers en embedded systemen tot desktops en netwerkapparatuur. De toewijding aan de opensource principes zorgt voor een transparant en toegankelijk ontwikkelproces. Dit maakt FreeBSD een veilige keuze voor als u op zoek bent naar een betrouwbaar en sterk aanpasbaar besturingssysteem.

[[why-called-FreeBSD]]
=== Waarom heet het FreeBSD?

De naam "FreeBSD" heeft zijn roots in de Berkeley Software Distribution (BSD), een UNIX besturingssysteem, vermaard om zijn bijdragen aan de wereld van de opensource software. Het "Free" in FreeBSD toont de toewijding aan de principes van gratis en opensource software, die gebruikers de vrijheid bieden om de code te bestuderen, aan te passen en te distribueren.

Merk op dat het Engelse woord "free" hier op twee manieren wordt gebruikt. In de betekenis van "gratis" en in de betekenis van "doe ermee wat je wilt".

[[FreeBSD-goals]]
=== Wat is het doel van het FreeBSD-project?

Het FreeBSD-project heeft een helder en onwrikbaar doel: het bieden van een hoogwaardig, opensource, UNIX-achtig besturingssysteem, dat uitblinkt in prestaties, beveiliging en stabiliteit.

Het heeft als doel een veelzijdig platform te bieden, dat geschikt is voor een breed scala aan computertoepassingen, van servers en werkstations tot embedded systemen en nog veel meer. FreeBSD is ontwikkeld met een grote toewijding aan de opensource principes, resulterend in een omgeving waar de bijdragen van een wereldwijde community van ontwikkelaars het besturingssysteem vormgeven en definiëren. Deze toewijding aan kwaliteit, vrijheid en betrouwbaarheid is wat FreeBSD onderscheidt en wat het doorlopende succes als opensource project verklaard.

[[FreeBSD-usecases]]
=== What use cases is FreeBSD good for?

FreeBSD is een veelzijdig besturingssysteem dat uitblinkt in verschillende toepassingsgebieden. Het is in het bijzonder geschikt voor servers. De stabiliteit en prestaties van FreeBSD maken het een populaire keuze voor webhosting, databases en netwerktoepassingen. De robuuste beveiligingsfuncties maken het ook een sterke kandidaat voor firewalls en beveiligingstoepassingen. Naast het gebruik als server kan FreeBSD ook op maat worden ingesteld voor gespecialiseerde omgevingen, zoals bijvoorbeeld embedded systemen en game consoles. De aanpasbaarheid, betrouwbaarheid en het opensource karakter maken FreeBSD een aantrekkelijke keuze voor een breed scala aan computertoepassingen.

[[responsible]]
=== Wie is verantwoordelijk voor FreeBSD?

FreeBSD is een opensource project met een decentrale structuur, ontwikkeld en beheerd door 'de community'. Dit is een wereldwijde gemeenschap van toegewijde vrijwilligers, ontwikkelaars en organisaties die samenwerken om het besturingssysteem te verbeteren en uit te breiden.

Een gekozen kernteam van negen personen neemt de belangrijke beslissingen voor het FreeBSD-project, zoals bijvoorbeeld de algehele richting van het project of wie het is toegestaan om iets toe te voegen aan de broncode.

Deze aanpak, gericht op samenwerking in de community, is de basis voor het succes en het duurzame karakter van FreeBSD als betrouwbaar en robuust UNIX-achtig besturingssysteem.

[[how-to-contribute]]
=== Hoe kan ik bijdragen aan FreeBSD? Wat kan ik doen om te helpen?

We staan open voor allerlei soorten bijdragen: documentatie, coderen en zelfs kunst. Zie het artikel extref:{contributing}[Bijdragen aan FreeBSD] voor specifieke informatie om hiermee aan de slag te gaan.

En bedankt voor het meedenken!

[[bsd-license-restrictions]]
=== Heeft de FreeBSD-licentie bepaalde restricties?

FreeBSD wordt uitgegeven onder de licentie https://www.FreeBSD.org/copyright/freebsd-license/[BSD License], die bekendstaat om haar tolerante karakter.

De licentie stelt erg weinig beperkingen aan het gebruik van FreeBSD:

* Beweer niet dat je dit geschreven hebt.
* Klaag ons niet aan als het uitvalt.
* Verwijder of verander de licentie niet.

De licentie houdt in dat u FreeBSD vrij mag wijzigen, distribueren en zelfs mag verkopen zonder *verplicht te zijn om de wijzigingen te publiceren als opensource*. Er zijn echter enkele minimale voorwaarden voor het distribueren van FreeBSD, zoals het behoud van de originele copyrightmelding en de vrijwaringen. De BSD-licentie biedt dus een grote mate van vrijheid en flexibiliteit, wat FreeBSD een aantrekkelijke keuze maakt voor een breed scala aan toepassingen en projecten.

Programmacode in onze broncode, die valt onder de licentie https://www.FreeBSD.org/copyright/COPYING[GNU General Public License (GPL)] of https://www.FreeBSD.org/copyright/COPYING.LIB[GNU Library General Public License (LGPL)] heeft wat meer voeten in de aarde, tenminste als het gaat om afgedwongen toegang, vergeleken met het gebruikelijke tegengestelde.

[[replace-current-OS]]
=== Kan FreeBSD mijn huidige besturingssysteem vervangen?

Voor veel gebruikers en beheerders is het antwoord daarop ja. Maar deze vraag is wat te eenvoudig gesteld.

FreeBSD is een krachtig en veelzijdig besturingssysteem dat prima naast of in plaats van een ander besturingssysteem geïnstalleerd kan worden, afhankelijk van de specifieke wensen van de gebruiker of beheerder. Of FreeBSD uw huidige besturingssysteem kan vervangen, hangt af van factoren zoals het type hardware, softwarevereisten en vertrouwdheid met FreeBSD.

Het biedt een robuust alternatief met zeer veel mogelijkheden, maar het is essentieel dat u uw eigen specifieke situatie en eisen onderzoekt voordat u de overstap maakt.

Als een bepaald programma slechts beschikbaar is voor één besturingssysteem, kan dat besturingssysteem niet zomaar worden vervangen.

Gebruikers die vanaf een andere UNIX-achtige omgeving overstappen naar FreeBSD, zullen weinig verrassingen ondervinden. Niet-UNIX-gebruikers, bijvoorbeeld Windows-gebruikers, zullen wat meer tijd moeten steken in het leren kennen van de UNIX-omgeving en werkwijze.

[[run-popular-software]]
=== Draait populaire opensource software wel op FreeBSD?

Ja, FreeBSD is goed uitgerust voor het uitvoeren van populaire opensource software. Het is compatibel met een breed scala aan applicaties en bibliotheken, wat het een favoriete keuze maakt voor degenen die graag opensource software willen gebruiken. FreeBSD biedt een robuuste en stabiele omgeving met ondersteuning voor diverse programmeertalen, databases, webservers en andere software die veel wordt gebruikt in de opensource-community. Het systeem van poorten en pakketten vereenvoudigt de installatie en het beheer van dergelijke software, zodat gebruikers met heel weinig moeite hun favoriete opensource tools en programma's kunnen draaien op FreeBSD.

[[install-software]]
=== Hoe installeer ik software in FreeBSD?

FreeBSD biedt meerdere methoden voor het installeren van software. Een van de meest gebruikte methoden is het gebruik van de ingebouwde man:pkg[8] package manager, die het proces vereenvoudigt door vooraf gebouwde binaire pakketten op te halen en te installeren. Een andere benadering is het compileren en installeren van software vanuit broncode via de man:ports[7] collectie. Deze methode is flexibel en biedt mogelijkheden om de software op maat te installeren.

De documentatie bij FreeBSD geeft gedetailleerde uitleg over beide methoden, zodat gebruikers eenvoudig de mogelijkheden van hun systeem kunnen uitbreiden met de software die zij nodig hebben.

[[differences-to-other-bsds]]
=== Wat zijn de verschillen tussen FreeBSD, NetBSD, OpenBSD en andere opensource BSD-besturingssystemen?

FreeBSD, NetBSD, OpenBSD en DragonFly BSD zijn allen onderdeel van de opensource BSD-familie en delen de op UNIX gebaseerde uitgangspunten, maar elke variant heeft zijn eigen focus en prioriteiten. De verschillen tonen de unieke doelstellingen van elk project en hoewel ze overeenkomsten hebben, komen hun specifieke sterktes en aandachtsgebieden tegemoet aan verschillende toepassingsgebieden en voorkeuren binnen het BSD-ecosysteem.

[[freebsd-linux-distribution]]
=== Is FreeBSD een Linux(R)-distributie?

Nee, FreeBSD is geen Linux-distributie.

Hoewel zowel FreeBSD als Linux UNIX-achtige besturingssystemen zijn en veel overeenkomsten vertonen, hebben ze verschillende kernels. Linux gebruikt de Linux-kernel, terwijl FreeBSD de FreeBSD-kernel gebruikt, die is gebaseerd op het UNIX-besturingssysteem van de Berkeley Software Distribution (BSD).

FreeBSD en Linux hebben elk hun eigen unieke ontwikkelcommunity, release-cyclus en systeemarchitectuur, waardoor ze verschillende en onafhankelijke besturingssystemen zijn.

FreeBSD biedt zijn eigen voordelen, waaronder een ander licentiemodel, systeemontwerp en andere systeem- en hulpprogramma's vergeleken met Linux-distributies.

[[run-linux-programs-freebsd]]
=== Is het mogelijk om Linux-programma's te draaien op FreeBSD?

Ja, FreeBSD biedt een compatibiliteitslaag genaamd _linuxulator_ (man:linux[4]), waarmee veel Linux-programma's uitgevoerd kunnen worden op FreeBSD. Met deze feature kan een breed spectrum aan Linux-binaries worden uitgevoerd zonder dat een speciale Linux-omgeving nodig is.

Het is overigens goed om op te merken dat erg veel opensource software *originele FreeBSD-versies beschikbaar* hebben via het ports and packages-systeem.

[[installing-freebsd]]
== FreeBSD installeren

Het installeren van FreeBSD is de eerste stap naar het ontplooien van de kracht van dit robuuste opensource besturingssysteem. Dit hoofstuk beschrijft waar u FreeBSD kunt verkrijgen, geeft gedetailleerde installatie-instructies en legt uit wat het verschil is tussen FreeBSD-CURRENT en FreeBSD-STABLE. We duiken ook in de release- en snapshot-planning, configuratietools voor ná de installatie, het zoeken naar pakketten en algemene vragen over pakketupdates.

[[where-get]]
=== Waar kan ik FreeBSD vandaan halen?

FreeBSD is vrij verkrijgbaar voor downloaden via link:https://www.FreeBSD.org/where/[official FreeBSD website].

Daarnaast is FreeBSD ook beschikbaar via verscheidene mirror-sites, wat het toegankelijkheid maakt voor gebruikers wereldwijd. De link:https://www.FreeBSD.org/where/[official website] is de primaire en meest betrouwbare bron voor het verkrijgen van de laatste release en updates van FreeBSD en is het ideale startpunt om FreeBSD beter te leren kennen.

[[install-instructions-location]]
=== Waar vind ik installatie-instructies voor FreeBSD?

Installatie-instructies kunt u vinden in extref:{handbook}bsdinstall/[het hoofdstuk FreeBSD installeren van het Handboek].

[[current]]
=== Wat is het concept achter FreeBSD-CURRENT?

FreeBSD-CURRENT is de ontwikkelingstak van het FreeBSD besturingssysteem. Het is de meest recente versie van FreeBSD, waar actieve ontwikkelingen in plaatsvinden.

Het bevat de laatste functies, verbeteringen en experimentele wijzigingen, maar is niet altijd even stabiel als de FreeBSD-STABLE- of de release-versies.

FreeBSD-CURRENT dient als platform voor ontwikkelaars en enthousiaste gebruikers die willen bijdragen aan de toekomst van FreeBSD en de laatste ontwikkelingen willen volgen, ondanks dat er af en toe grondige wijzigingen plaatsvinden en de versie *niet aanbevolen wordt voor productiesystemen*.

[[stable]]
=== Wat is het concept achter FreeBSD-STABLE?

De FreeBSD-STABLE-versie is een stabielere versie dan de CURRENT. De versie bevat code die nog in de testfase is en waar nog aan wordt gewerkt voordat het wordt toegevoegd aan de RELEASE-versie. STABLE is een goede keuze voor diegenen die wel de ontwikkelingen willen volgen, maar liever een stabielere omgeving hebben dan de CURRENT.

[[release-freq]]
=== Wanneer worden de FreeBSD-versies vrijgegeven?

De {re} publiceert ongeveer elke 18 maanden een grote versie-update van FreeBSD en ongeveer elke 8 maanden een kleinere update. Publicatiedata worden ruim van tevoren aangekondigd, zodat de mensen die aan het project werken, weten wanneer hun projecten gereed en getest moeten zijn. Een publicatie wordt altijd voorafgegaan door een testperiode om zeker te zijn dat het toevoegen van de nieuwe functies niet de stabiliteit van de bestaande versie in gevaar brengen.

[[snapshot-freq]]
=== Wanneer worden er momentopnames van FreeBSD gemaakt?

Voor alle actief ontwikkelde versies van FreeBSD worden met regelmatige tussenpozen momentopnames gegenereerd. Deze momentopnames leggen een moment in de tijd vast van de FreeBSD-broncode en de bijbehorende pakketten. De frequentie van deze momentopnames kan variëren, maar het wordt meestal wekelijks of twee-wekelijks uitgevoerd. De gebruikers krijgen met deze momentopnames toegang tot de laatste ontwikkelingen en wijzigingen in FreeBSD, zodat ze op de hoogte blijven van de voortgang van het project.

[[general-configuration-tool]]
=== Is er een tool om na de installatie nog instellingen te wijzigen?

Ja. man:bsdconfig[8] biedt een prettige interface om FreeBSD te configureren na de installatie.

[[search-software-freebsd]]
=== Hoe kan ik in FreeBSD zoeken naar te installeren software?

In FreeBSD kan met de pakketmanager man:pkg[8] en het commando `pkg search` naar beschikbare software worden gezocht.

Gebruikers kunnen dit commando toepassen voor het zoeken naar beschikbare pakketten met gebruikmaking van zoekwoorden, pakketnamen of beschrijvingen. Deze functie helpt gebruikers om in de uitgebreide verzameling poorten en pakketten binnen FreeBSD snel de software te vinden die ze nodig hebben. Het toevoegen van nieuwe applicaties en tools aan hun FreeBSD-systeem wordt op deze manier erg eenvoudig.

[[latest-packages-freebsd]]
=== Waarom krijg ik niet de laatste pakketten in mijn FreeBSD-systeem?

De beschikbaarheid van de meest recente pakketten in FreeBSD wordt beïnvloed door verschillende factoren, zoals de update-frequentie van de pakketarchieven en de gebruikte FreeBSD-versie.

Daarnaast bestaan er twee aftakkingen voor de FreeBSD-poorten. De meest recente is de `latest` en de meest stabiele is de `quarterly`. Om de meest recente pakketten te gebruiken, moet de `latest` aftakking geconfigureerd worden. Informatie over het configureren van aftakkingen is te vinden in link:{handbook}ports/[hoofdstuk Poorten van het Handboek].

[[hardware]]
== Hardware

Het hoofdstuk Hardware beschrijft de compatibiliteit van FreeBSD met verschillende hardwareconfiguraties. Het bevat uiteenlopende onderwerpen, zoals ondersteunde architecturen, maximale RAM-capaciteit, schaalbaarheid van processoren, ondersteunde grafische kaarten, WiFi-kaarten en ondersteuning voor 10 Gigabit Ethernet-netwerkkaarten. Dit hoofdstuk geeft inzicht in de mogelijkheden en beperkingen van FreeBSD en informatie over hardwarekeuzes en -configuraties voor zowel het gebruik van FreeBSD op servers en werkstations als op gespecialiseerde hardware.

[[architectures-support]]
=== Welke architecturen ondersteunt FreeBSD?

FreeBSD draait op een grote verscheidenheid aan architecturen, waardoor het een flexibele keuze is voor veel hardwareomgevingen. Het is onder andere compatibel met architecturen zoals `amd64`, `arm64` en `riscv`.

Een complete lijst met architecturen is te vinden op link:https://www.FreeBSD.org/platforms/[pagina platforms].

[[ram-support]]
=== Hoeveel RAM ondersteunt FreeBSD?

FreeBSD ondersteunt als besturingssysteem gewoonlijk net zoveel fysiek geheugen (RAM) als het platform waarop het draait. Houd in gedachten dat verschillende platforms verschillende limieten hebben wat betreft geheugen.

Amd64-platforms ondersteunen bijvoorbeeld maximaal 4 TB aan fysiek geheugen.

[[cpu-support]]
=== Hoeveel processors ondersteunt FreeBSD?

De ondersteuning van FreeBSD voor processors verschilt per architectuur. Op amd64- en arm64-systemen kan FreeBSD efficiënt de kracht van maar liefst 1024 processors verwerken. In op powerpc-gebaseerde systemen ondersteunt FreeBSD maximaal 256 processors en op risc-v-systemen maximaal 16 processors.

[[graphics-cards-support]]
=== Welke grafische kaarten ondersteunt FreeBSD?

Er is goede ondersteuning voor de populaire fabrikanten van grafische kaarten, zoals Intel(R), AMD(R) en NVIDIA(R).

Een lijst van ondersteunde grafische kaarten van link:https://wiki.freebsd.org/Graphics/Intel-GPU-Matrix[Intel] en link:https://wiki.freebsd.org/Graphics/AMD-GPU-Matrix[AMD] is te vinden in de FreeBSD Wiki.

[[wifi-support]]
=== Welke WiFi-kaarten ondersteunt FreeBSD?

Anno 2025 gaan de veranderingen snel op dit gebied. Hou vooral de Hardware Compatibility List in de gaten voor uw gekozen link:https://www.freebsd.org/releases/[versie].

De lijst met PCIe WiFi-apparaten die goed werken onder FreeBSD:

* Intel chipset-apparaten worden behandeld in man:iwlwifi[4] (high-speed vanaf FreeBSD 14.3)
* Realtek RTL8188CE Mini PCIe

De lijst met USB WiFi-apparaten die goed werken onder FreeBSD:

* RT5370 USB dongles (ondersteunt hostap mode)
* TP-Link TL-WDN3200 (RT5592, man:if_run[4])
* TP-Link TL-WN725N v2 (RTL8188EU, man:rtwn[4])
* TP-Link Archer T4U (RTL8812AU, man:rtwn[4])
* D-Link DWA-131 (RTL8192CU, man:rtwn[4])
* D-Link DWA-171 rev A1 (RTL8821AU, man:rtwn[4])
* ASUS USB-N10 NANO (RTL8188CUS, man:rtwn[4])


[[gigabit-ethernet-network-support]]
=== Ondersteunt FreeBSD 10 Gigabit Ethernet netwerkkaarten?

FreeBSD biedt een robuuste ondersteuning voor 10 Gigabit Ethernet netwerkkaarten, waardoor het een uitstekende keuze is voor high-speed netwerkomgevingen. De FreeBSD-kernel bevat stuurprogramma's voor een groot aantal 10 Gigabit Ethernet adapters van verschillende fabrikanten, wat zorgt voor een naadloze integratie en optimale netwerkprestaties.

Zie voor meer informatie link:https://wiki.freebsd.org/Networking/10GbE[FreeBSD Wiki].

[[documentation-support]]
== Documentatie en ondersteuning

Dit gedeelte geeft waardevolle informatie voor diegenen die hun kennis van FreeBSD verder willen verdiepen. Het behandelt verschillende onderwerpen, zoals aanbevolen boeken voor het leren van FreeBSD, routes naar commerciële trainingen en ondersteuning, een kijkje onder de motorkap van FreeBSD en informatie over waar hulp te vinden is binnen de FreeBSD-community.

[[books]]
=== Wat zijn goede boeken over FreeBSD?

Bent u enthousiast over FreeBSD en wilt u er meer van leren, dan zijn er diverse boeken beschikbaar die toegespitst zijn op dit besturingssysteem. De onderwerpen variëren van de basisbeginselen tot geavanceerd systeembeheer en programmeren.

Enkele goed bekend staande titels zijn "Absolute FreeBSD: The Complete Guide To FreeBSD" van Michael W. Lucas en de "FreeBSD Mastery series" ook van Michael W. Lucas en medeauteurs. Deze boeken leveren waardevolle inzichten aan gebruikers van alle niveaus om FreeBSD onder de knie te krijgen en maximaal te benutten.

Naast de boeken produceert het FreeBSD-project een grote hoeveelheid documentatie, online beschikbaar via het link:https://docs.FreeBSD.org/[Documentatieportaal].

[[training]]
=== Waar kan ik commerciële trainingen volgen en ondersteuning krijgen voor FreeBSD?

Voor diegenen die professionele trainingen en ondersteuning zoeken voor FreeBSD zijn er diverse aanbieders die oplossingen op maat aanbieden. Het FreeBSD-project heeft een link:https://www.freebsd.org/commercial/[lijst met bedrijven] waar ondersteuning kan worden aangevraagd.

[[learn-advanced]]
=== Hoe kan ik meer te weten komen over de interne werking van FreeBSD?

Om FreeBSD op een dieper niveau te leren kennen, kunnen geïnteresseerde gebruikers bronnen raadplegen zoals bijvoorbeeld "The Design And Implementation Of The FreeBSD Operating System". Het extref:{arch-handbook}[FreeBSD Architecture Handbook] is ook een waardevolle bron, die gedetailleerde informatie geeft over de architectuur, systeemopbouw en ontwerpprincipes van FreeBSD.

Daarnaast kan het doornemen van de broncode van FreeBSD via de FreeBSD bronbestanden waardevolle inzichten geven omtrent de kerncomponenten van het besturingssysteem.

[[help-freebsd-system]]
=== Waar kan ik hulp vinden binnen een FreeBSD-systeem?

Ondersteuning is rechtstreeks beschikbaar binnen FreeBSD. Er is een grote verzameling ingebouwde documentatie, die direct toegankelijk is via het man:man[1] commando. Dat geeft uitgebreide informatie over diverse commando's en systeemcomponenten.

Daarnaast vormt het extref:{handbook}[FreeBSD Handboek], dat zowel online als lokaal op het systeem beschikbaar is, een waardevolle informatiebron met uitgebreide instructies.

Als er problemen optreden, kan er meestal snel een oplossing gevonden worden door hulp te vragen aan ervaren gebruikers en ontwikkelaars in de FreeBSD-community via mailing lists, forums of IRC.

[[community-questions]]
== Vragen aan de community

Bestudeer dit hoofdstuk om te ontdekken hoe u deel kunt nemen aan de FreeBSD-community.

U vindt hier uitleg over de IRC-kanalen voor realtime discussies, webgebaseerde forums voor het delen van inzichten en toegang tot de mailing lists en nieuwsgroepen van FreeBSD voor diepgaande discussies en nieuwsupdates.

[[irc]]
=== Zijn er IRC (Internet Relay Chat)-kanalen voor FreeBSD?

Ja, de meeste grote IRC-netwerken hosten een FreeBSD-chatkanaal en de FreeBSD-wiki houdt een actuele link:https://wiki.freebsd.org/IRC/Channels[lijst van IRC-kanalen] bij.

Elk van deze kanalen staan op zichzelf en zijn niet verbonden met elkaar. Omdat de chat-stijlen verschillen, raden we u aan elk kanaal te proberen en te kijken welk het best bij u past.

[[forums]]
=== Zijn er ook internetforums die discussiëren over FreeBSD?

De officiële FreeBSD-forums zijn te vinden via link:https://forums.FreeBSD.org/[FreeBSD Forums startpagina].

[[mailing]]
=== Waar vind ik informatie over de FreeBSD-maillijsten?

De publieke maillijsten zijn te vinden via link:https://lists.freebsd.org/[FreeBSD maillijsten].

[[misc]]
== Overige vragen

Blader door een variëteit van intrigerende en praktische vragen over FreeBSD. Van keuzes voor de shell en eigenaardigheden van het systeem tot en met de naam van het huisdier van FreeBSD.

[[minimal-sh]]
=== Waarom is /bin/sh zo minimaal? Waarom gebruikt FreeBSD geen bash of andere shell?

Veel mensen moeten shellscripts schrijven, die uitwisselbaar zijn tussen verschillende systemen. Daarom specificeert POSIX(R) de shell en ondersteunende commando's zeer gedetailleerd. De meeste scripts zijn geschreven in de Bourne-shell (man:sh[1]), omdat verscheidene belangrijke programmeerinterfaces de Bourne-shell gebruiken om commando's te interpreteren. Omdat de Bourne-shell zo vaak en wijdverbreid wordt gebruikt, is het belangrijk dat deze snel start, deterministisch is qua gedrag en weinig geheugen gebruikt.

De bestaande implementatie is onze beste oplossing om aan al deze vereisten tegelijk te voldoen. Om `/bin/sh` klein te houden, hebben we veel van de handige functies die andere shells hebben, niet ingebouwd.

Om die reden zijn er andere shells met meer functies beschikbaar, zoals `bash`, `scsh`, man:tcsh[1] en `zsh`.

[[keyboard-delete-key]]
=== Hoe gebruik ik de delete-toets in sh en csh?

Voor de Bourne Shell voegt u de volgende regels toe aan [.filename]#~/.shrc#:

[.programlisting]
....
bind ^[[3~ ed-delete-next-char # for xterm
....

Voor the C-shell voegt u de volgende regels toe aan [.filename]#~/.cshrc#:

[.programlisting]
....
bindkey ^[[3~ delete-char # for xterm
....

[[forgot-root-pw]]
=== Ik ben het root-wachtwoord vergeten! Wat moet ik doen?

Geen paniek! Herstart het systeem, typ `boot -s` op de `Boot:` prompt om naar single-user mode te gaan. Op de vraag over welke shell te gebruiken, drukt u op kbd:[Enter]. Hierna verschijnt een # prompt. Typ `mount -urw /` om het root bestandssysteem te remounten als read/write. Typ vervolgens `mount -a` om alle bestandssystemen te remounten. Typ `passwd root` om het `root` wachtwoord te wijzigen en voer dan man:exit[1] uit om verder te gaan met booten.

[TIP]
====
Als u nog steeds wordt gevraagd het `root` wachtwoord in te voeren als u naar single-user-mode gaat, dan is de console aangemerkt als `insecure` in [.filename]#/etc/ttys#. In dat geval moet u opstarten van een FreeBSD installatieschijf, vervolgens aan het begin van het installatieproces kiezen voor de [.guimenuitem]#Live CD# of de [.guimenuitem]#Shell# en bovenstaande commando's geven. Mount in dit geval de specifieke partitie en ga hier met chroot naartoe. Vervang bijvoorbeeld `mount -urw /` met `mount /dev/ada0p1 /mnt; chroot /mnt` als het systeem zich op _ada0p1_ bevindt.
====

[TIP]
====
Als de root-partitie niet vanuit single-user-mode gemount kan worden, zijn de partities mogelijk beveiligd en is het onmogelijk ze te mounten zonder toegangscode. Zie voor meer informatie het hoofdstuk over beveiligde schijven in het FreeBSD extref:{handbook}disks/[Handboek, schijfbeveiliging].
====

[[rcconf-readonly]]
=== Ik heb een fout gemaakt in rc.conf of een ander opstartbestand en nu kan ik het niet meer bewerken, omdat het bestandssysteem alleen-lezen is. Wat kan ik doen?

Start het systeem opnieuw op met `boot -s` in de loader-prompt om naar single-user-mode te gaan. Wanneer gevraagd wordt naar een padnaam voor de shell, drukt u op kbd:[Enter] en typt u `mount -urw /` om het root bestandssysteem te remounten in lees/schrijf-modus. U moet mogelijk ook `mount -a -t ufs` uitvoeren om het bestandssysteem te mounten waar uw favoriete editor is geconfigureerd. Als het bestandssysteem van de editor zich op het netwerk bevindt, configureert u handmatig het netwerk voordat de bestandssystemen op het netwerk worden gemount of u gebruikt een editor die zich op een lokaal bestandssysteem bevindt, zoals man:ed[1].

Om een full screen editor zoals man:vi[1] of man:emacs[1] te gebruiken, voert u `export TERM=xterm` uit, zodat deze editors de juiste gegevens kunnen ophalen uit de man:termcap[5] database.

Na het uitvoeren van deze stappen, bewerkt u [.filename]#/etc/rc.conf# om de syntaxfout te corrigeren. De foutmelding die wordt weergegeven direct na de opstartmeldingen van de kernel, zou het regelnummer moeten aangeven in het bestand waar de fout in optreedt.

[[free-memory-amount]]
=== Hoeveel vrij geheugen is er beschikbaar?

Er zijn verschillende soorten "vrij geheugen". Het meest gebruikelijke is de hoeveelheid geheugen die direct beschikbaar is, zonder geheugen terug te claimen die al in gebruik is. Dat is de grootte van de wachtrij met vrije pagina's plus wat andere gereserveerde pagina's. Deze hoeveelheid wordt geëxporteerd door `vm.stats.vm.v_free_count` man:sysctl[8], weergegeven door bijvoorbeeld man:top[1]. Een ander soort "vrij geheugen" is de totale hoeveelheid virtueel geheugen beschikbaar voor userland-processen, die afhangt van de totale swapruimte en het bruikbaar geheugen. ther kinds of "free memory" descriptions are also possible, but it is relatively useless to define these, but rather it is important to make sure that the paging rate is kept low, and to avoid running out of swap space.

[[timezone]]
=== Mijn tijd klopt niet, hoe kan ik de tijdzone veranderen?

Via man:tzsetup[8].

[[more-swap]]
=== FreeBSD gebruikt veel swapruimte, terwijl de computer veel vrij geheugen heeft. Waarom?

FreeBSD verplaatst proactief complete niet-gebruikte pagina's van het hoofdgeheugen naar swap om meer hoofdgeheugen beschikbaar te maken voor actief gebruik. Dit extra gebruik van swap wordt in evenwicht gehouden door het extra vrije geheugen te gebruiken als cache.

Er zijn verschillende soorten "vrij geheugen". Het meest gebruikelijke is de hoeveelheid geheugen die direct beschikbaar is, zonder geheugen terug te claimen die al in gebruik is. Dat is de grootte van de wachtrij met vrije pagina's plus wat andere gereserveerde pagina's. Deze hoeveelheid wordt geëxporteerd door `vm.stats.vm.v_free_count` man:sysctl[8], weergegeven door bijvoorbeeld man:top[1]. Een ander soort "vrij geheugen" is de totale hoeveelheid virtueel geheugen beschikbaar voor userland-processen, die afhangt van de totale swapruimte en het bruikbaar geheugen. ther kinds of "free memory" descriptions are also possible, but it is relatively useless to define these, but rather it is important to make sure that the paging rate is kept low, and to avoid running out of swap space.

[[top-freemem]]
=== Waarom toont top erg weinig vrij geheugen, terwijl er erg weinig programma's actief zijn?

Het simpele antwoord is dat vrij geheugen verloren geheugen is.

Geheugen dat programma's niet actief reserveren, wordt binnen de FreeBSD-kernel gebruikt als disk-cache. De waarden die man:top[1] toont bij `Inact` en `Laundry` zijn cache-gegevens van verschillende ouderdomsniveaus. Dankzij deze cache-gegevens hoeft het systeem niet opnieuw toegang te vragen tot een langzame schijf voor gegevens waarvoor kortgeleden toegang is verkregen. Op deze manier wordt het hele systeem sneller. In het algemeen is een lage waarde voor `Free` geheugen in man:top[1] goed, zolang het maar niet _erg_ laag is.

[[daemon-name]]
=== Wat is de naam van dat grappige kleine mannetje?

Hij heeft geen naam en wordt gewoonlijk "de BSD-daemon" genoemd. Als u hem echt een naam wilt geven, noem hem dan "Beastie". Let op dat "Beastie" wordt uitgesproken als "BSD".

Kijk voor meer informatie over de BSD-daemon op http://www.mckusick.com/beastie/index.html[home page].

[[use-beastie]]
=== Mag ik de afbeelding van de BSD-daemon gebruiken?

Misschien. De BSD-daemon valt onder het copyright van Marshall Kirk McKusick. Kijk voor meer informatie over de gebruiksvoorwaarden op zijn website http://www.mckusick.com/beastie/mainpage/copyright.html[Statement on the Use of the BSD Daemon Figure].

Samenvattend kan de afbeelding op een fatsoenlijke manier gebruikt worden voor persoonlijk gebruik, zolang de bron op een correcte manier wordt vermeld. Neem contact op met {mckusick} voor toestemming als u het logo zakelijk wilt gebruiken. Ga voor meer informatie naar http://www.mckusick.com/beastie/index.html[BSD Daemon's home page].

[[bikeshed-painting]]
=== Waarom moet ik me druk maken over de kleur van het fietsenschuurtje?

Het heel korte antwoord is dat u zich daar niet druk om moet maken. Het iets langere antwoord is dat alleen omdat u een fietsenschuurtje kan bouwen, betekent dat nog niet dat u anderen moet verhinderen ook zo'n schuurtje te bouwen, omdat u de kleur niet mooi vindt. Dit is een metafoor om aan te geven dat u niet over elke kleine wijziging of vernieuwing moet discussiëren, alleen omdat u er veel van afweet. Sommige mensen hebben geschreven dat de hoeveelheid gegenereerde ruis omgekeerd evenredig is met de complexiteit van de wijziging.

Het langere en complete antwoord is dat na een zeer lange discussie over of man:sleep[1] secondenargumenten met cijfers achter de komma zou moeten accepteren, {phk} een lang bericht postte met de titel link:http://www.bikeshed.com[A bike shed (any color will do) on greener grass...].

[[acknowledgments]]
== Dankbetuiging

Deze FAQ heeft de laatste decennia talloze revisies en verbeteringen ondergaan, uitgevoerd door een grote verscheidenheid aan vrijwilligers.
