---
title: "Les applications pour FreeBSD"
sidenav: about
---

= Les applications pour FreeBSD

== FreeBSD vous offre de nombreuses possibilités

FreeBSD saura accomplir quasiment toutes les tâches que vous pouvez attendre d'une station UNIX(R), et bien plus encore :

== FreeBSD est un véritable système ouvert accompagné de l'intégralité de son code source.

Cela ne fait plus aucun doute, les systèmes ouverts sont _indispensables_ pour les applications informatiques actuelles. Aucune solution commerciale n'est plus ouverte qu'une solution qui met à disposition de l'utilisateur l'integralité du code source, y compris pour le noyau, les serveurs systèmes, les programmes et les utilitaires. Vous pouvez modifier n'importe quelle partie de FreeBSD afin qu'il s'adapte à vos exigences personnelles ou professionnelles.

Grâce aux link:../copyright/freebsd-license/[fondements de sa licence], vous pouvez utiliser FreeBSD comme base pour toutes vos applications libres _ou commerciales_.

== FreeBSD est capable de faire fonctionner des milliers d'applications.

FreeBSD étant basé sur 4.4BSD, une version standard d'UNIX, il est facile de compiler et d'utiliser des programmes. FreeBSD inclu également une vaste link:../where/[collection de paquetages] et de link:../ports/[ports] qui apportent des logiciels précompilés et faciles à mettre en place pour votre ordinateur personnel ou votre serveur d'entreprise. De plus en plus de link:../commercial/software/[logiciels commerciaux] sont également écrits pour FreeBSD.

Quelques exemples d'utilisations de FreeBSD :

* *Internet.* De nombreux fournisseurs d'accès Internet (dits ISP ou FAI) aprécient FreeBSD et l'utilisent pour le web, les news Usenet, le FTP, l'Email et d'autres services. FreeBSD étant en mesure de faire fonctionner des logiciels comme le serveur web http://www.apache.org/[Apache] ou encore le serveur FTP http://proftpd.org/[ProFTPD], il est facile de mettre en place un FAI communautaire ou commercial. Evidemment, les imbattables link:&base;/internet.html[performances réseaux] de FreeBSD permettront à tous vos utilisateurs de bénéficier de services fiables et rapides.
* *Station de travail X Window.* Que ce soit pour un terminal X modeste ou une station X avancée, FreeBSD est parfaitement adapté. La version libre de X, (http://x.org/[X.Org](TM)) est livrée avec le système. http://www.nvidia.com/[nVidia] fournit des pilotes natifs pour son matériel graphique haute performance, et les standards industriels http://www.opengroup.org/motif/[Motif](R) et http://www.opengl.org/[OpenGL](R) sont supportés. Les environnements de bureau http://www.kde.org[KDE] et http://www.gnome.org[GNOME] disposent d'un support complet et fournissent une suite bureautique, avec davantage de fonctionnalités pour les produits http://www.openoffice.org/[OpenOffice.Org] et http://www.softmaker.de/tml_en.htm[TextMaker].
* *Le réseau.* Que ce soit pour le filtrage de paquets, le routage ou les serveurs de noms, FreeBSD peut transformer n'importe quel PC en pare-feu Internet, en serveur de mail, en serveur d'impression, en serveur PC/NFS et bien plus encore.
* *Développement de logiciels.* Toute une suite de logiciels de développement sont inclus avec FreeBSD comme le compilateur GNU C/C++ et son debogueur. Par exemple le développement en Java(R) et Tcl/Tk est également possible, des langages de programmation plus ésotériques comme Icon fonctionnent aussi parfaitement sous FreeBSD. Et Les librairies partagées sous FreeBSD ont toujours été faciles à développer et à utiliser. Vous pouvez également choisir parmi une large gamme d'éditeurs célèbres et puissants, comme XEmacs et Vim.
* *Surfer sur le net.* Une véritable station UNIX a toujours été une plate-forme de choix pour surfer sur Internet. Les versions FreeBSD de http://www.mozilla.org/products/firefox/[Firefox] et http://www.opera.com/[Opera] sont disponibles pour les utilisateurs avancés du web. Explorez le web, publiez vos propres pages web, lisez les news Usenet, envoyez et recevez vos courriers électroniques grâce à votre ordinateur de bureau FreeBSD.
* *Recherche et éducation.* FreeBSD est une excellente plate-forme pour la recherche car il est livré avec son code source complet. Les étudiants et les chercheurs en informatique tireront sans aucun doute un grand profit de ce système ouvert et bien documenté.
* *Et bien plus.* Comptabilité, jeux d'action, bases de données, visualisation de données scientifiques, vidéo-conférence, discussions sur Internet (IRC), automatisation domestique, jeux de donjons multi-joueurs (MUDs), BBS, digitalisation d'images... sont autant d'utilisations possibles de FreeBSD aujourd'hui.

== FreeBSD est un système d'exploitation qui s'adaptera à vos besoins.

Bien que FreeBSD soit un logiciel libre et gratuit, c'est aussi un logiciel _supporté par ses utilisateurs_. Toutes vos questions peuvent être posées aux centaines de développeurs et utilisateurs de FreeBSD en écrivant à la liste de diffusion électronique freebsd-questions@FreeBSD.org.

FreeBSD est sans cesse amélioré et documenté par de nombreux développeurs de part le monde. Le support de nouveaux périphériques et l'ajout de nouvelles fonctions sont sans cesse développés et l'équipe garde toujours une attention toute particulière aux problèmes pouvant affecter la stabilité du systeme. Les utilisateurs de FreeBSD sont fiers non seulement de la rapidité mais également de la fiabilité de leur système.

== Paroles d'expert . . .

_"FreeBSD gère de façon excellente [notre] forte charge réseau, c'est tout simplement incroyable. Salutations à toute l'équipe FreeBSD."_

---Mark Hittinger, administrateur chez WinNet Communications, Inc.
