#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $Id: Makefile,v 1.1 2002-04-20 21:07:09 gioria Exp $
# $FreeBSD$
#    Original revision: 1.1
# Article about using FreeBSD on laptops
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.xml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
