#
# The FreeBSD Russian Documentation Project
# 
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/version-guide/Makefile,v 1.1 2005/10/09 16:19:35 gad Exp $
# $FreeBSD$
# 
# Original revision: 1.3
#
# Article: FreeBSD Version Guide

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
