---
title: A BSD bemutatása
authors:
  - author: Greg Lehey
    email: grog@FreeBSD.org
releaseinfo: "$FreeBSD$" 
trademarks: ["freebsd", "amd", "apple", "intel", "xfree86", "linux", "opengroup", "sparc", "sun", "unix", "general"]
---

= A BSD bemutatása
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:toc-title: Tartalom
:table-caption: Táblázat
:figure-caption: Ábra
:example-caption: Példa

include::shared/authors.adoc[]

[.abstract-title]
Kivonat

A nyílt forrású világban a "Linux(R)" szó majdnem az "operációs rendszer" szinonimájává vált, pedig nem ez az egyetlen nyílt forrású UNIX(R)-szerû operációs rendszer. Az http://www.leb.net/hzo/ioscount/data/r.9904.txt[Internet Operating System Counter] szerint 1999 áprilisában a világ hálózatra kapcsolt számítógépeinek 31,3%-a Linux(R)ot futtat. 14,6% használ BSD UNIX(R)-ot. A világ legnagyobb webes szolgáltatásai közül néhány, mint például a http://www.yahoo.com/[Yahoo!] is BSD-t használ. A világ legforgalmasabb FTP szervere 1999-ben (már halott), az link:ftp://ftp.cdrom.com/[ftp.cdrom.com], BSD-t használt a napi 1,4 TB adatforgalom biztosításához. Ez egyértelmûen nem egy szûk piaci réteg: a BSD egy jól megõrzött titok.

Tehát mi is a titok? Miért nem ismert jobban a BSD? Ez a dokumentum többek között ezt a kérdést hivatott megvizsgálni.

A dokumentumban a BSD és Linux(R) közötti különbségeket __így olvashatja__.

_Fordította: `{gabor}`_

'''

toc::[]

[[what-is-bsd]]
== Mi az a BSD?

A BSD "Berkeley Software Distribution" rövidítése, amely annak a disztribúciónak a neve, amit a berkeley-i egyetemen fejlesztettek ki Californiában az AT&T UNIX(R) operációs rendszerének a kiterjesztéseként. Számos nyílt forású operációs rendszer épül a 4.4BSD-Lite néven ismertté vált kiadásra. Ráadásul tartalmaznak több csomagot más nyílt forrású projektekbõl, különösen a GNU projektbõl. A teljes operációs rendszer a következõket tartalmazza:

* A BSD kernel, amely a processzütemezést, illetve a memóriakezelést végzi, kezeli a szimmetrikus többprocesszoros rendszereket (SMP), az eszközmeghajtókat, stb.
+ 
__A Linux(R) kernellel ellentétben, BSD kernelbõl több van, különbözõ adottságokkal.__
* A C könyvtár, a rendszer alapvetõ API-ja.
+ 
__A BSD C könyvtár a Berkeley kódon alapszik, nem a GNU projekten.__
* Segédprogramok, mint shellek, fájlkezelõ eszközök, fordítók és linkerek.
+ 
__Néhány segédprogram a GNU projektbõl származik, mások nem.__
* Az X Window rendszer, amely a grafikus megjelenítést kezeli.
+ 
Az X Window rendszert, amelyet a legtöbb BSD rendszer használ, két különbözõ projekt fejleszti, az http://www.XFree86.org/[projekt] és az http://www.X.org/[X.Org projekt]. A Linux(R) is ezeket használja. A BSD általában nem jelöl ki egy "grafikus felületet", mint például a GNOME, vagy KDE, de ennek ellenére ezek is elérhetõek.
* Sok egyéb program és segédeszköz.

[[what-a-real-unix]]
== Micsoda? Egy igazi UNIX(R)?

A BSD operációs rendszerek nem klónok, hanem az AT&T's Research UNIX(R) operációs rendszer nyílt forráskódú leszármazottai, amely a modern UNIX(R) System V õse. Talán meglepõnek találja, hogy hogyan lehetséges ez, amikor az AT&T soha nem tette nyílt forrásúvá a kódját?

Igaz, hogy az AT&T UNIX(R) nem nyílt forrású és jogi szempontból a BSD határozottan _nem_ UNIX(R), de az AT&T átvett kódot más projektekbõl is, különösen a kaliforniai Berkeley egyetemen mûködõ Computer Sciences Research Group (CSRG)-tól. 1976-tól a CSRG szalagokon kiadta a szoftverét, amelynek neve __Berkeley Software Distribution__, avagy _BSD_ volt.

A BSD kezdeti kiadásai leginkább felhasználói programokból álltak, de a helyzet drámaian megváltozott, amint a CSRG szerzõdött az Advanced Research Projects Agency-vel (DARPA) a hálózataik ARPANET-re történõ aktualizálásával kapcsolatban. Az új protokollok, mint _Internet Protokollok_ voltak ismertek, késõbb mint __TCP/IP__, a protokollcsalád két legfontosabb protokollja után. A legelsõ szélesebb körben használt implementáció a 4.2BSD része volt, 1982-ben.

Az 1980-as években számos új munkaállomásokkal foglalkozó cég tûnt fel. Sokuk a UNIX(R) licencelését részesítette elõnyben egy saját operációs rendszer fejlesztésével szemben. Különösen a Sun Microsystems licencelte a UNIX(R)-ot és megvalósította a 4.2BSD egy új verzióját, amelyet SunOS(TM)-nak nevezett. Amikor az AT&T jogosulttá vált arra, hogy maguk árusítsák a UNIX(R)-ot kereskedelmi forgalomban, a valamelyest mérföldkõnek számító System III rendszerüket hamarosan a System V követte. A System V kódja nem tartalmazott hálózatkezelést, így minden implementációjukhoz a BSD-bõl vettek át szoftvereket, ideértve a TCP/IP szoftvert és egyéb más programokat is, mint például a _csh_ shell és a _vi_ editor. Ezek az eszközök kollektívan a _Berkeley Extensions_ (berkeley-i kiegészítések) néven váltak ismertté.

A BSD szalagok az AT&T tulajdonában lévõ kódot is tartalmaztak, így használatuk UNIX(R) source licencet igényelt. 1990-re a CSRG kifogyott a támogatásokból, így be kellett szüntetniük a munkát. A csoport néhány tagja úgy döntött, hogy kiadja a BSD kódját, amely nyílt forráskódú volt az AT&T kód nélkül. Ez végül a _Networking Tape 2_ kiadással valósult meg, amely általában mint _Net/2_ ismert. A Net/2 nem volt komplett operációs rendszer, a kernel kódjának kb. 20%-a hiányzott. A CSRG tagok egyike, William F. Jolitz megírta a hiányzó kódrészeket és 1992 elején kiadta a _386BSD_ rendszert. Ezzel egyidõben a volt CSRG tagok egy másik csoportja létrehozott egy kereskedelmi céget http://www.bsdi.com/[Berkeley Software Design Inc.] néven és kiadtak egy béta verziójú operációs rendszert, a http://www.bsdi.com/[BSD/386]-ot, amely ugyanarra a kódra épült. Az operációs rendszer neve késõbb BSD/OS-re változott.

A 386BSD soha nem vált stabil rendszerré. Ehelyett két másik projekt nõtt ki belõle 1993-ban: a http://www.NetBSD.org/[NetBSD] és a link:https://www.FreeBSD.org/[FreeBSD]. A két projekt akkor vált szét, amikor a 386BSD fejlõdését várták: a NetBSD az év elején startolt, a FreeBSD elsõ kiadása pedig csak az év végére készült el. Eközben a kód eléggé más irányba fejlõdött ahhoz, hogy könnyen egyesíhessék azt. Ezen kívül a projektek küönbözõ célokat tûztek ki, ahogyan majd lentebb látni fogjuk. 1996-ban az http://www.OpenBSD.org/[OpenBSD] kivált a NetBSD-bõl, 2003-ban pedig a http://www.dragonflybsd.org/[DragonFlyBSD] a FreeBSD-bõl.

[[why-is-bsd-not-better-known]]
== Miért nem ismert jobban a BSD?

Számos ok miatt, a BSD relatíve ismeretlen:

. A BSD fejlesztõit gyakran jobban érdekli, hogy a kódot javítgassák, minthogy marketinget szervezzenek köré.
. A Linux(R) ismertsége a projekten kívüli okoknak köszönhetõ, mint a sajtó vagy a cégek, amelyek linuxos szolgáltatásokat kínálnak. Ezidáig a nyílt forrású BSD-k nem rendelkeznek ilyen kiváltságokkal.
. A BSD fejlesztõi gyakran több tapasztalattal rendelkeznek, mint a Linux(R) fejlesztõi, így kevésbé érdekeltek abban, hogy a rendszert könnyen használhatóvá tegyék. Az új felhasználók általában kényelmesebbnek találják a Linux(R)ot.
. 1992-ben az AT&T beperelte a http://www.bsdi.com/[BSDI]-t, a BSD/386 terjesztõjét azzal az indokkal, hogy a termék az AT&T tulajdonában lévõ kódrészleteket tartalmaz. A bíróság 1994-ben lezárta az ügyet, de a per szelleme továbbra is kísérti az embereket. Mostanában, 2000 márciusában egy webes cikk is azt állította, hogy a bírósági ügy "nemrég fejezõdött be".
+ 
A név volt az egyik kérdés, amit a per tisztázott: az 1980-as években a BSD mint "BSD UNIX(R)" volt ismert. Az AT&T birtokolta kódok utolsó nyomainak eltávolításával a BSD elvesztette a UNIX(R) névhez való jogát. Ennek eredményeképp olyan hivatkozások olvashatók a könyvcímekben, mint "4.3BSD UNIX(R) operációs rendszer" és "4.4BSD operációs rendszer".
. Egyes megfigyelések szerint a BSD projektek szétdarabolódtak és ellenségesek egymással. A http://interactive.wsj.com/bin/login?Tag=/&URI=/archive/retrieve.cgi%253Fid%253DSB952470579348918651.djm&[Wall Street Journal] a BSD projektek "balkánizációjáról" beszél. A perhez hasonlóan, ez is nagyrészt õsi történetekre épül.

[[comparing-bsd-and-linux]]
== A BSD és a Linux(R) összehasonlítása

Tehát valójában mi is a különbség mondjuk a Debian Linux(R) és a FreeBSD közt? Az átlag felhasználó számára a különbség meglepõen csekély: mindkettõ UNIX(R)-szerû operációs rendszer. Mindkettõt non-profit projektek fejlesztik. (Természetesen ez nem igaz sok más Linux(R) disztribúcióra.) A következõ fejezetben a BSD és a Linux(R) közötti különbségeket tekintjük át. A leírás leginkább a FreeBSD-re illik, amely a BSD telepítések kb. 80%-át teszi ki, de a NetBSD, OpenBSD és DragonflyBSD nem sokban különbözik tõle.

=== Kinek a birtokában van a BSD?

A BSD nem egy személy vagy egy vállalat tulajdona. Egy magasan képzett és elkötelezett közösség fejleszti és terjeszti világszerte. A BSD néhány összetevõje különálló nyílt forrású projekt, amelyet más fejlesztõk tartanak karban.

=== Hogyan fejlesztik és aktualizálják a BSD-t?

A BSD kerneleket a nyílt forrású fejlesztési modell szerint fejlesztik és tartják naprakészen. Mind a négy projekt fenntart egy publikusan elérheõ _forrásfát_ a http://www.cvshome.org/[Concurrent Versions System] (CVS) verziókezelõ rendszer segítségével, amely a projekt minden forrásfájlját tartalmazza a dokumentációval és egyéb fontos fájlokkal együtt. A CVS segítségével a felhasználók lekérhetik ("check out") a rendszer bármely óhajtott verzióját.

Világszerte sok fejlesztõ járul hozzá a BSD fejlõdéséhez. Három kategóriába soroljuk õket:

* A _contributor-ok_ ("külsõ munkatársak") kódot vagy dokumentációt írnak. Nincs jogosultságuk a forráskódban közvetlenül változtatásokat végrehajtani. Ahhoz, hogy a munkájuk bekerüjön a rendszerbe, egy hivatalos fejlesztõnek - _committernek_ - kell azt átnéznie és a kódbázishoz adnia.
* A _Committerek_ azok a fejlesztõk, akiknek írási jogosultságuk van a forráskódhoz. Ahhoz, hogy valaki committerré váljon, be kell bizonyítania, hogy megfelelõ tudással rendelkezik azon a területen, amelyen dolgozik.
+ 
A committer egyéni döntése, hogy él-e a felhatalmazásával, mielõtt változtatást hajt végre a forráskódon. Általában, egy tapasztalt committer végrehajthat olyan változtatásokat, amelyek nyilvánvalóan helyesek, anélkül, hogy ehhez más beleegyezését kérné. Példál egy dokumentáción dolgozó committer kijavíthat helyesírási, vagy nyelvtani hibákat, anélkül, hogy azt más megvizsgálná. Másrészt, azoktól a fejlesztõktõl, akik messzemenõ vagy összetett változtatásokon dolgoznak, elvárt, hogy átnézésre közzétegyék a kódot a tényleges változtatások elõtt. Extrém esetekben a core team egy tagja, mint elöljáró tervezõ, elrendelheti a változtatások törlését a forráskódból, azon a folyamaton keresztül, amelynek neve _backing out_. Minden committer kap értesítést minden változásról, így nem lehet titokban változtatásokat eszközölni.
* A _Core team_ ("projektvezetõk"). A FreeBSD és a NetBSD is rendelkezik egy core csapattal, amely a projektet menedzseli. A core csapatok a projekt elõremenetele során alakultak ki, és a szerepük nem mindig pontosan meghatározott. Nem szükséges fejlesztõnek lenni ahhoz, hogy valaki a core csapat tagja legyen, habár ez a megszokott. A core csapat feladata egyik projektrõl a másikra változik, de általában több beleszólásuk van a projekt menetébe, mint a nem core tagoknak.

Ez a rendszer számos pontban eltér a Linux(R)étól:

. Nem egyetlen ember irányítja a rendszert. A gyakorlatban ez az eltérés túlértékelt, hiszen az elöljáró tervezõ kérheti a kód visszaállítását és még a Linux(R) projektben is több embernek van jogosultsága változtatni.
. Másrészt, _van_ egy központi repository, azaz a teljes operációs rendszer forráskódja egy helyen érhetõ el, beleértve a régi verziókat is.
. A BSD projektek az egész "operációs rendszert" karbantartják, nemcsak a kernelt. Ez a megkülönböztetés csak részben hasznos: a BSD és a Linux(R) is haszontalan alkalmazások nélkül. A BSD alatt használt alkalmazások gyakran azonosak a Linux(R)on használtakkal.
. A központilag karbantartott CVS forrásfának köszönhetõen a BSD fejlesztése áttekinthetõ, továbbá lehetõség van arra, hogy bármely verziót elérjünk a kiadási verzió vagy a dátum alapján. A CVS segítségével növekményesen is frissíthetjük rendszerünket: például a FreeBSD repositoryja kb. 100 alkalommal frissül naponta. Ezek közül a változások közül a legtöbb kicsi.

=== A BSD kiadások

A FreeBSD, NetBSD és OpenBSD háromféle "kiadáson" keresztül teszi elérhetõvé a rendszert. Ahogyan a Linux(R) esetében is, a kiadások kapnak egy verziószámot, mint pl. 1.4.1 vagy 3.5. Továbbá, a verziószám rendelkezik egy utótaggal, amelyik a kiadás célját jelöli:

. A rendszer fejlesztõi verziójának neve _CURRENT_. A FreeBSD egy számot rendel ehhez, pl. 5.0-CURRENT. A NetBSD egy kicsit más elnevezési konvenciót alkalmaz, egy egybetûs utótagot fûz a névhez, amely azt jelzi, hogy csak a belsõ interfészeket érinti a változás, ilyen pl. a NetBSD 1.4.3G. Az OpenBSD nem használ számokat ("OpenBSD-current"). Minden új fejlesztés elõször ebbe az ágba kerül bele.
. Meghatározott idõnként, 2-4 alkalommal évente, a projekt kiad egy _RELEASE_ (kiadás) verziót, amely elérhetõ CD-ROM-on és szabadon letölthetõ az FTP szerverekrõl, ilyen pl. az OpenBSD 2.6-RELEASE vagy a NetBSD 1.4-RELEASE. A RELEASE verzió végfelhasználók számára készül és ez a rendszer normális verziója. A NetBSD ezen kívül _patch release_ kiadásokat is kínál egy harmadik számjeggyel, pl. NetBSD 1.4.2.
. Ahogy hibák bukkannak fel a RELEASE verzióban és javításra kerülnek, a javítások bekerülnek a CVS fába. Az így létrejövõ verzió neve a FreeBSD-nél _STABLE_, de a NetBSD és az OpenBSD továbra is RELEASE néven hívja ezt a verziót. Kisebb új funkciók szintén bekerülhetnek ebbe az elágazásba, miután a CURRENT ágban már egy ideje stabilnak bizonyultak.

__Ezzel ellentében a Linux(R) két különbözõ forrásfát tart fenn: a stabil- és a fejlesztõi verziót. A stabil verzióknak egy páros minor számuk van, mint pl. 2.0, 2.2 vagy 2.4. A fejlesztõi verziók minor száma páratlan, mint pl. 2.1, 2.3 vagy 2.5. Ezt a verziószámot minden esetben egy harmadik szám követi, ez adja meg a pontos verziót. Ezen kívül, minden terjesztõ saját programokat és segédeszközöket mellékel, így a disztribúció neve is meghatározó. Minden disztribútor külön verziószámmal látja el a disztribúciót is, tehát egy teljes meghatározás valahogy így hangzana: "TurboLinux 6.0 2.2.14-es kernellel"__.

=== Milyen BSD verziók vannak?

A rengeteg Linux(R) disztribúcióval ellentétben csak négy jelentõsebb nyílt forrású BSD van. Minden BSD projekt karbantartja a saját forrásfáját és saját kernelét. A gyakorlatban azonban kevesebb az eltérés a userland kódokban, mint a Linux(R) esetében.

Nehéz kategorizálni a projektek céljait, mert a különbségek nagyon szubjektívak. Alapvetõen a következõek érvényesek:

* A FreeBSD a nagy teljesítményt és a könnyû használhatóságot célozza meg, a webszolgáltatók kedvence. Számos platformon fut, ide értve az i386(TM) alapú rendszereket ("PC-ket"), az AMD 64-bites processzorait, az UltraSPARC(R) rendszereket, a Compaq Alpha rendszereit, illetve a NEC PC-98 specifikációján alapuló rendszereket. A FreeBSD Projekt jelentõsen több felhasználóval rendelkezik, mint más projektek.
* A NetBSD a lehetõ legnagyobb hordozhatóságra törekszik, ahogyan az idézet is mutatja: "of course it runs NetBSD". Elfut a palmtopokon és a nagy szervereken egyaránt, és a NASA is használja az ûrkutatásai során. Különösen jó választás régi, nem Intel(R) alapú hardverhez.
* Az OpenBSD a biztonságra és a kód egyszerûségére koncentrál: a nyílt forrású koncepciót kombinálják a szigorú ellenõrzésekkel, hogy így egy bizonyítottan korrekt rendszert hozzanak létre, megoldást kínálva ezzel a biztonságot megkövetelõ szervezeteknek, mint például bankoknak, tõzsdéknek és amerikai kormányügyi szervezeteknek. Ahogyan a NetBSD, az OpenBSD is több platformon fut.
* A DragonFlyBSD a nagy teljesítményt és a skálázhatóságot célozza meg az egyszerû UP rendszerektõl kezdve a hatalmas, fürtözött rendszerekig. Számos hosszútávú technikai célja van, de a legfontosabb, hogy egy olyan SMP-képes infrastruktúrát hozzon létre, amely könnyen érthetõ és karbantartható, valamint könnyû rá fejleszteni.

Létezik még két másik BSD UNIX(R), amelyek azonban nem nyílt forrásúak: a BSD/OS és az Apple Mac OS(R) X:

* A BSD/OS volt a legrégebbi leszármazottja a 4.4BSD-nek. Nem volt ugyan nyílt forrású, de viszonylag alacsony áron lehetett licencet vásárolni a forráskódhoz. Sok tekintetben hasonlított a FreeBSD-hez. Két évvel azután, hogy a Wind River Systems megvette a BSDi-t, a BSD/OS, mint önálló termék megszûnt létezni. Támogatás és a forráskód még mindig elérhetõ a Wind Rivernél, de az új fejlesztések már a VxWorks beágyazott operációs rendszerre irányulnak.
* A http://www.apple.com/macosx/server/[Mac OS(R) X] az http://www.apple.com/[Apple Computer Inc.] operációs rendszerének legújabb verziója a Macintosh(R) termékvonalhoz. Ennek a rendszernek a BSD magja, a http://developer.apple.com/darwin/[Darwin] egy teljes értékû nyílt forrású operációs rendszerként érhetõ el x86 és PPC számítógépekhez. Az Aqua/Quartz grafikus rendszer és a Mac OS(R) X pár egyéb saját fejlesztése zárt forrású maradt. Számos Darwin fejlesztõ egyben FreeBSD committer is, és fordítva.

=== Hogyan tér el a BSD licenc a GNU General Public licenctõl?

A Linux(R) a http://www.fsf.org/copyleft/gpl.html[GNU General Public Licenc] (GPL) alatt érhetõ el, amely azért jött létre, hogy felszámolja a zárt forráskódú szoftverfejlesztést. Konkrétan, minden olyan munkának, amely GPL licenc alatt kiadott termékre épül, szintén nyílt forrásúnak kell lennie. Ezzel szemben a http://www.opensource.org/licenses/bsd-license.html[BSD licenc] kevésbé korlátozó: tisztán bináris terjesztést is megenged. Ez különösen vonzó a beágyazott alkalmazások számára.

=== Mi mást kell még tudnom?

Mivel a BSD-hez kevesebb alkalmazás érhetõ el, mint a Linux(R)hoz, ezért a BSD fejlesztõi készítettek egy Linux(R) kompatibilitási csomagot, amellyel Linux(R) programok futtathatók BSD rendszeren. A csomag egyaránt tartalmaz kernel módosításokat a Linux(R) rendszerhívások megfelelõ végrehajtásához, és kompatibilitási fájlokat, mint például a C könyvtár. A BSD rendszeren futtatott Linux(R) alkalmazások és a natív Linux(R) környezetben futó Linux(R) alkalmazások között nincs észrevehetõ sebességkülönbség.

A BSD "mindent együtt" természetének köszönhetõen a frissítések sokszor sokkal könnyebben kezelhetõek, mint a Linux(R) esetében. A BSD úgy kezeli a könyvtárak verzióit, hogy kompatibilitási modulokat bizosít a régebbi könyvtárakhoz, így több éves programok is probléma nélkül futtathatóak.

=== Melyiket használjam, a BSD-t, vagy a Linux(R)ot?

Mit jelent mindez a gyakorlatban? Kinek való a BSD és kinek a Linux(R)?

Ezt a kérdést nagyon nehéz megválaszoli. Pár irányelv:

* "Ha nem romlott el, ne javítsd meg": Ha már egy olyan nyílt forrású operációs rendszert használ, amellyel elégedett, várhatóan nincs semmi nyomós oka, hogy váltson.
* A BSD rendszerek, különösen a FreeBSD jelentõsen nagyobb teljesítményt produkálhatnak, mint a Linux(R). Ez azonban nem mindenkire érvényes. Sok esetben kicsi a különbség, vagy egyáltalán nincs különbség a teljesítményben. Néhány esetben pedig a Linux(R) teljesít jobban a FreeBSD-nél.
* Általában a BSD rendszerek nagyobb tiszteletnek örvendenek a megbízhatóság terén, amely leginkább a kiforrottabb kód eredménye.
* A BSD projektek nagyobb tiszteletnek örvendenek a minõségi és átfogó dokumentációjukért. A különbözõ dokumentációs projektek célja, hogy jól karbantartott dokumentációt biztosítsanak sok nyelven és a rendszer minden területét tárgyalják.
* A BSD licenc vonzóbb lehet, mint a GPL.
* A BSD a legtöbb Linux(R) programot képes futtatni, amíg a Linux(R) nem képes BSD programokat futtatni. Ezenkívül sok BSD implementáció más UNIX(R)-szerû operációs rendszerek programjait is képes futtatni, így a BSD rendszerekre könnyebb migrálni más rendszereket, mint a Linux(R)ra.

=== Ki kínál terméktámogatást és tréninget a BSD-hez?

A BSDi / http://www.freebsdmall.com[FreeBSD Mall, Inc.] közel egy évtizede kínál terméktámogatási szerzõdéseket a FreeBSD-hez.

Ezen kívül minden projekt rendelkezik egy listával a konzultánsairól: link:https://www.FreeBSD.org/commercial/consult_bycat/[FreeBSD], http://www.netbsd.org/gallery/consultants.html[NetBSD], és http://www.openbsd.org/support.html[OpenBSD].
