# $FreeBSD$
# Original Revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

#DOCS=	bugreports.sgml webresources.sgml
DOCS=	bugreports.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
