#
# $FreeBSD$
#
# Article about using FreeBSD on laptops
# "Article" sobre FreeBSD en computadoras portátiles.

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

#
WITH_ARTICLE_TOC?=YES


SRCS= article.xml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
