---
title: "FreeBSD 4.2 Announcement"
sidenav: download
--- 

= FreeBSD 4.2 Announcement

*Date:* Tue, 21 Nov 2000 04:31:48 -0800 +
*From:* "Jordan K. Hubbard" <jkh@winston.osd.bsdi.com> +
*To:* announce@FreeBSD.org +
*Subject:* 4.2-RELEASE is now available

It is my almost excessive pleasure to announce the availability of FreeBSD 4.2-RELEASE, the very latest in 4.x-STABLE branch technology. Following the release of FreeBSD 4.1.1 in September, 2000, many bugs were fixed, important security issues dealt with, and a conservative number of new features added. Please see the release notes for more information.

4.2-RELEASE is now available for the ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/4.2-RELEASE[i386] and ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/alpha/4.2-RELEASE[alpha] architectures right now and can be installed directly over the net using the boot floppies or copied to a local NFS/ftp server.

ISO (CD) Images +
--------------- +

We can't promise that all the mirror sites will carry the larger ISO images, but they will at least be available from:

ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/ISO-IMAGES/4.2-install.iso +
and ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/alpha/ISO-IMAGES/4.2-install.iso

If you can't afford the CDs, are impatient, or just want to use it for evangelism purposes, then by all means download the ISOs, otherwise please do continue to support the FreeBSD project by purchasing one of its official CD releases from BSDi. FreeBSD 4.2-RELEASE can be ordered as a 4 CD set from http://www.freebsdmall.com[The FreeBSD Mall] from where it will soon be shipping. Each CD sets contains the FreeBSD installation and application package bits for either the x86 or the alpha architecture (each architecture has its own CD set). For a set of distfiles used to build ports in the ports collection, please see also the FreeBSD Toolkit, a 6 CD set containing all such extra bits which we can no longer fit on the 4 CD sets. You can also order by phone, postal mail, FAX or email at:

....
  BSDi
  4041 Pike Lane, #F
  Concord CA, 94520 USA
  Phone: +1 925 674-0783
  Fax: +1 925 674-0821
  Tech Support: +1 925 603-1234
  Email: orders@wccdrom.com
  WWW: http://www.freebsdmall.com/
....

FreeBSD is also available via anonymous FTP from mirror sites in the following countries: Argentina, Australia, Austria, Brazil, Bulgaria, Canada, the Czech Republic, Denmark, Estonia, Finland, France, Germany, Hong Kong, Hungary, Iceland, Ireland, Israel, Japan, Korea, Latvia, Malaysia, the Netherlands, Poland, Portugal, Rumania, Russia, Slovenia, South Africa, Spain, Sweden, Taiwan, Thailand, Elbonia, the Ukraine and the United Kingdom, among others.

Before trying the central FTP site, please check your regional mirror(s) first by going to:

ftp://ftp.<yourdomain>.FreeBSD.org/pub/FreeBSD

Any additional mirror sites will be labeled ftp2, ftp3 and so on.

Thanks! - Jordan
