# $FreeBSD$
# $FreeBSDde$
# basiert auf: r52778

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	charter.xml
DOCS+=  reporting.xml
DOCS+=	security.xml
DOCS+=  unsupported.xml

INDEXLINK=	security.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
