# $FreeBSD$
# $FreeBSDde: de-www/security/Makefile,v 1.7 2008/03/01 17:12:05 jkois Exp $
# basiert auf: 1.16

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	charter.sgml
DOCS+=	security.sgml

INDEXLINK=	security.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
