# $FreeBSD$
#
# The FreeBSD Mongolian Documentation Project
#
# Original revision 1.14

#SUBDIR = arch-handbook
#SUBDIR+= corp-net-guide
#SUBDIR+= design-44bsd
#SUBDIR+= dev-model
#SUBDIR+= developers-handbook
#SUBDIR+= faq
#SUBDIR+= fdp-primer
SUBDIR+= handbook
#SUBDIR+= pmake
#SUBDIR+= porters-handbook

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
