---
title: "Проект FreeBSD/ia64 Project -- планируемые работы"
sidenav: developers
--- 

= Проект FreeBSD/ia64 Project -- планируемые работы

'''''

Поиск в базе данных PR по FreeBSD/ia64:

'''''

== Что необходимо сделать.

Эта страница может стать отправной точкой для тех, кто пытается найти работу, которую необходимо выполнить. Возраст пунктов на этой странице не обязательно говорит об их важности, скорее, это хороший знак. Есть похожие задачи, которые не приведены здесь, но которые должны быть реализованы в любом случае. Типичным примером является сопровождение веб-страниц ia64... к сожалению.

=== Стать платформой ранга 1.

Имея два релиза в качестве платформы 2 ранга, самое время поработать для того, чтобы стать платформой 1 ранга. Сюда включены такие разные задачи:

* Улучшить процесс установки, учитывающий, что уже есть GPT с разделом EFI, включая случай с другими операционными системами. Возможность добавления записи о FreeBSD в меню загрузки EFI также будет хорошим делом.
* Портирование отладчика GNU. Его очень не хватает на машинах разработчиков и он требуется для платформ 1 ранга.
* Портирование X-сервера (ports/x11/XFree86-4-Server). На самом деле не является требованием для получения статуса 1 ранга, но без этого не обойтись, если кому-то захочется использовать ia64 в качестве настольной системы.

=== Порты и пакаджи,

Очень важная работа для успеха FreeBSD на ia64, обеспечивающая возможность пользователям запускать что-то, кроме ls(1). Наша огромная коллекция портов большей частью ориентирована на ia32, поэтому не удивительно, что есть много портов, которые не строятся или не работают на ia64. Смотрите http://bento.freebsd.org/errorlogs/ia64-5-latest/[здесь] самый последний перечень портов, которые не строятся по тем или иным причинам. Заметьте, что если есть порты, зависящие от одного или большего количества нерабочих портов, то они не строятся и не подсчитываются. Хорошим способом помочь здесь является работа над теми портами, которые имеют много портов, зависящих от них (смотрите колонку "Aff." в таблице).

=== Заточить пилу.

Имеется достаточно функций (особенно ассемблерных подпрограмм), которые были написаны для покрытия отсутствующей функциональность без принятия во внимание скорости и/или надёжности. Просмотр этих функций и их замена является хорошей задачей, которая может быть выполнена параллельно и независимо от других действий и не обязательно требует огромных знаний и/или опыта.

=== Разработка ядра.

Кроме высокоуровневых вещей, которые не работают или не существуют, есть также и другие, подразумевающие, что изменения будут делаться в основе и потенциально могут затронуть другие платформы. Сюда включается:

* Улучшение стабильности UP и SMP посредством переделки модуля PMAP. Обработку VM-преобразований на низком уровне нужно улучшить. Здесь подразумевается как правильность, так и производительность.
* Драйверы основных устройств, таких, как sio(4) и syscons(4), не работают на машинах ia64, не имеющих поддержку старых устройств. Это весьма большая проблема, потому что это затрагивает все платформы и моет привести к переписыванию (больших) частей некоторых подсистем. Очевидно, что эта задача требует общую поддержку и координацию.
* Улучшенная обработка в конфигурациях с разрывами (физической) памяти путём отказа от создания таблиц VM, покрывающих всё адресное пространство, в пользу покрывающих "куски" имеющейся памяти. На данный момент по этой причине память игнорируется в принудительном порядке.
