#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
#
# Article: CUPS on FreeBSD
#
# Original revision: r33118
#

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
