# $FreeBSD: www/en/events/Makefile,v 1.2 2002/03/26 08:11:53 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=	2002 2003

DATA=   events.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
