---
title: Manuel FreeBSD
authors: 
releaseinfo: "$FreeBSD$" 
trademarks: ["freebsd", "ibm", "ieee", "redhat", "3com", "adobe", "apple", "intel", "linux", "microsoft", "opengroup", "sun", "realnetworks", "oracle", "3ware", "arm", "adaptec", "google", "heidelberger", "intuit", "lsilogic", "themathworks", "thomson", "vmware", "wolframresearch", "xiph", "xfree86", "general"] 
next: books/handbook/preface
---

= Manuel FreeBSD
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:toc-title: Table des matières
:part-signifier: Partie
:chapter-signifier: Chapitre
:appendix-caption: Annexe
:table-caption: Tableau
:example-caption: Exemple

include::shared/releases.adoc[]
include::shared/fr/mailing-lists.adoc[]

[.abstract-title]
Résumé

Bienvenue à FreeBSD! Ce manuel décrit l'installation et l'utilisation quotidienne de _FreeBSD {rel121-current}-RELEASE_, et _FreeBSD {rel113-current}-RELEASE_. Ce document est le résultat du travail toujours en cours de nombreuses personnes. Certaines sections peuvent ne pas être à jour. Les personnes qui sont intéressées pour aider à mettre à jour et à compléter ce document devraient envoyer un courrier électronique à la {freebsd-doc}.

La dernière version anglaise de ce document est disponible sur le https://www.FreeBSD.org/[site Web de FreeBSD]. Les versions antérieures peuvent être obtenues auprès de https://docs.FreeBSD.org/doc/[http://docs.FreeBSD.org/doc/]). Il peut être aussi téléchargé dans divers formats et options de compression depuis le https://download.freebsd.org/ftp/doc/[serveur FTP FreeBSD] ou l'un des nombreux crossref:mirrors[mirrors-ftp,sites miroirs]. Des versions imprimées peuvent être achetées auprès de https://www.freebsdmall.com/[FreeBSD Mall]. Des recherches dans le Manuel et les autres documents peuvent être effectuées à partir de la link:https://www.FreeBSD.org/search/[page de recherches].

N.d.T.: Contactez {fonvieille} si vous voulez collaborer à la traduction.

'''

include::content/fr/books/handbook/toc.adoc[]

include::content/fr/books/handbook/toc-figures.adoc[]

include::content/fr/books/handbook/toc-tables.adoc[]

include::content/fr/books/handbook/toc-examples.adoc[]
