---
title: Partie I. Pour commencer
prev: books/handbook/preface
next: books/handbook/introduction
---

ifdef::env-beastie+backend-html5[]
:chapters-path: content/{{% lang %}}/books/handbook/
endif::[]

ifndef::env-beastie[]
:chapters-path:
endif::[]

[[getting-started]]
= Pour commencer

Cette partie du Manuel FreeBSD est destinée aux nouveaux venus à FreeBSD, utilisateurs et administrateurs. Ces chapitres:

* Présenteront FreeBSD.
* Guideront les lecteurs à travers le processus d'installation.
* Enseigneront quelques bases et fondements d'UNIX(R).
* Montreront comment installer la profusion d'applications tierces disponibles pour FreeBSD.
* Présenteront X, le système de fenêtrage d'UNIX(R), et détailleront comment configurer un environnement de travail qui rendra les utilisateurs plus productifs.

Le nombre de références dans le texte a été limité au minimum afin que cette section du Manuel puisse être lue du début jusqu'à la fin avec le moins de changements de pages possibles.

include::{chapters-path}toc-1.adoc[]
