# $FreeBSD: doc/ja_JP.eucJP/articles/ipsec-must/Makefile,v 1.2 2001/09/04 10:40:53 hrs Exp $
# Original revision: 1.2

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

NO_TIDY=YES

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
