---
title: "FreeBSD 15.1-RELEASE Errata"
sidenav: download
---

:release: 15.1-RELEASE
:releaseNext: 15.2-RELEASE
:releaseBranch: 15-STABLE

= FreeBSD {release} Errata

== Abstract

This document lists errata items for FreeBSD {release}, containing significant information discovered after the release or too late in the release cycle to be otherwise included in the release documentation.
This information includes security advisories, as well as news relating to the software or documentation that could affect its operation or usability.
An up-to-date version of this document should always be consulted before installing this version of FreeBSD.

This errata document for FreeBSD {release} will be maintained until the release of FreeBSD {releaseNext}.

== Table of Contents

* <<intro,Introduction>>
* <<security,Security Advisories>>
* <<errata,Errata Notices>>
* <<open-issues,Open Issues>>
* <<late-news,Late-Breaking News>>

[[intro]]
== Introduction

This errata document contains "late-breaking news" about FreeBSD {release}.
Before installing this version, it is important to consult this document to learn about any post-release discoveries or problems that may already have been found and fixed.

Any version of this errata document actually distributed with the release (for example, on a CDROM distribution) will be out of date by definition, but other copies are kept updated on the Internet and should be consulted as the "current errata" for this release.
These other copies of the errata are located at https://www.FreeBSD.org/releases/, plus any sites which keep up-to-date mirrors of this location.

Source and binary snapshots of FreeBSD {releaseBranch} also contain up-to-date copies of this document (as of the time of the snapshot).

For a list of all FreeBSD CERT security advisories, see https://www.FreeBSD.org/security/.

[[security]]
== Security Advisories

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Advisory |Date |Topic
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:37.vm.asc[FreeBSD-SA-26:37.vm] |30 June 2026 |Use-after-free in device pager page list
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:38.jail.asc[FreeBSD-SA-26:38.jail] |30 June 2026 |Jail reference count underflow
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:39.execve.asc[FreeBSD-SA-26:39.execve] |30 June 2026 |Local privilege escalation via execve(2) TOCTOU race
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:40.zfs.asc[FreeBSD-SA-26:40.zfs] |30 June 2026 |Multiple vulnerabilities in OpenZFS
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:41.libalias.asc[FreeBSD-SA-26:41.libalias] |30 June 2026 |Buffer overflow in libalias RTSP handler
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:42.unlinkat.asc[FreeBSD-SA-26:42.unlinkat] |30 June 2026 |unlinkat(2) ignores AT_RESOLVE_BENEATH flag
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:43.tcp.asc[FreeBSD-SA-26:43.tcp] |30 June 2026 |Use-after-free in TCP RACK stack option handler
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:44.posixshm.asc[FreeBSD-SA-26:44.posixshm] |30 June 2026 |Multiple vulnerabilities in POSIX largepage objects
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:45.audit.asc[FreeBSD-SA-26:45.audit] |30 June 2026 |Incorrect audit records for ptrace(2) syscall requests
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:46.ktls.asc[FreeBSD-SA-26:46.ktls] |30 June 2026 |Remote DOS via uninitialized memory access in KTLS receive
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:49.iconv.asc[FreeBSD-SA-26:49.iconv] |30 June 2026 |Multiple vulnerabilities in iconv(3)
|===

[[errata]]
== Errata Notices

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Errata |Date |Topic

|No errata notices.||

|===

[[open-issues]]
== Open Issues

1. The **man:nfs[4]** client may cause a kernel panic when an NFSv4.1 or NFSv4.2 server becomes unresponsive or reboots. The system will automatically reboot after the panic. +
**Workaround**: Avoid using `soft` or `intr` mount options with NFSv4.1/4.2 mounts. If the panic occurs frequently, consider downgrading to NFSv3 until a patched version is available. +
**State**: Fixed in main - https://bugs.freebsd.org/294925

2. Systems with **man:zfs[4]** encrypted pools with `keylocation=prompt` datasets may stall waiting for a passphrase on boot if the `zfskeys` **man:rc[8]** script is enabled, diverging from previous behavior where mounting them would be skipped. +
**Workaround**: Use `zpool set cachefile=none <pool>` so that the pool is not imported at boot. +
**State**: Open - https://bugs.freebsd.org/296130

[[late-news]]
== Late-Breaking News

No late-breaking news.
