# $FreeBSD$
# $FreeBSDru: frdp/www/ru/docproj/Makefile,v 1.2 2000/10/27 11:26:10 phantom Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=   current.sgml 
DOCS+=	doc-set.sgml
DOCS+=  sgml.sgml
DOCS+=  submitting.sgml
DOCS+=  who.sgml 
DOCS+=  translations.sgml
DOCS+=	docproj.sgml

INDEXLINK= docproj.html

.include "../web.mk"
