---
title: Chapter 1. Introduction
part: Part I. Getting Started
prev: books/handbook/parti
next: books/handbook/bsdinstall
description: This chapter covers various aspects of the FreeBSD Project, such as its history, goals, development model, and so on
tags: ["introduction", "synopsis", "about", "Who Uses FreeBSD", "goals", "history"]
showBookMenu: true
weight: 3
params:
  path: "/books/handbook/introduction/"
---

[[introduction]]
= Introduction
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 1
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/introduction/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[introduction-synopsis]]
== Synopsis

Thank you for your interest in FreeBSD! The following chapter covers various aspects of the FreeBSD Project, such as its history, goals, development model, and so on.

After reading this chapter you will know:

* How FreeBSD relates to other computer operating systems.
* The history of the FreeBSD Project.
* The goals of the FreeBSD Project.
* The basics of the FreeBSD open-source development model.
* And of course: where the name "FreeBSD" comes from.

[[nutshell]]
== Welcome to FreeBSD!

FreeBSD is an Open Source, standards-compliant Unix-like operating system for x86 (both 32 and 64 bit), ARM, AArch64, RISC-V, POWER, and PowerPC computers.
It provides all the features that are nowadays taken for granted, such as preemptive multitasking, memory protection, virtual memory, multi-user facilities, SMP support, all the Open Source development tools for different languages and frameworks, and desktop features centered around X Window System, KDE, or GNOME.
Its particular strengths are:

* _Liberal Open Source license_, which grants you rights to freely modify and extend its source code and incorporate it in both Open Source projects and closed products without imposing restrictions typical to copyleft licenses, as well as avoiding potential license incompatibility problems.
* _Strong TCP/IP networking_ - FreeBSD implements industry standard protocols with ever increasing performance and scalability. This makes it a good match in both server, and routing/firewalling roles - and indeed many companies and vendors use it precisely for that purpose.
* _Fully integrated OpenZFS support_, including root-on-ZFS, ZFS Boot Environments, fault management, administrative delegation, support for jails, FreeBSD specific documentation, and system installer support.
* _Extensive security features_, from the Mandatory Access Control framework to Capsicum capability and sandbox mechanisms.
* _Over 30 thousand prebuilt packages_ for all supported architectures, and the Ports Collection which makes it easy to build your own, customized ones.
* _Documentation_ - in addition to the Handbook and books from different authors that cover topics ranging from system administration to kernel internals, there are also the man:man[1] pages, not only for userspace daemons, utilities, and configuration files, but also for kernel driver APIs (section 9) and individual drivers (section 4).
* _Simple and consistent repository structure and build system_ - FreeBSD uses a single repository for all of its components, both kernel and userspace. This, along with a unified and easy to customize build system and a well thought-out development process makes it easy to integrate FreeBSD with build infrastructure for your own product.
* _Staying true to Unix philosophy_, preferring composability instead of monolithic "all in one" daemons with hardcoded behavior.
* _Binary compatibility_ with Linux, which makes it possible to run many Linux binaries without the need for virtualisation.

FreeBSD is based on the 4.4BSD-Lite release from Computer Systems Research Group (CSRG) at the University of California at Berkeley, and carries on the distinguished tradition of BSD systems development.
In addition to the fine work provided by CSRG, the FreeBSD Project has put in many thousands of man-hours into extending the functionality and fine-tuning the system for maximum performance and reliability in real-life load situations.
FreeBSD offers performance and reliability on par with other Open Source and commercial offerings, combined with cutting-edge features not available anywhere else.

[[os-overview]]
=== What Can FreeBSD Do?

The applications to which FreeBSD can be put are truly limited only by your own imagination.
From software development to factory automation, inventory control to azimuth correction of remote satellite antenna; if it can be done with a commercial UNIX(R) product then it is more than likely that you can do it with FreeBSD too! FreeBSD also benefits significantly from literally thousands of high quality applications developed by research centers and universities around the world, often available at little to no cost.

Because the source code for FreeBSD itself is freely available, the system can also be customized to an almost unheard-of degree for special applications or projects, and in ways not generally possible with operating systems from most major commercial vendors.
Here is just a sampling of some of the applications in which people are currently using FreeBSD:

* _Internet Services:_ The robust TCP/IP networking built into FreeBSD makes it an ideal platform for a variety of Internet services such as:

** Web servers
** IPv4 and IPv6 routing
** Firewalls and NAT ("IP masquerading") gateways
** FTP servers
** Email servers
** Storage servers
** Virtualization servers
** And more...

* _Education:_ Are you a student of computer science or a related engineering field? There is no better way of learning about operating systems, computer architecture and networking than the hands-on, under-the-hood experience that FreeBSD can provide. A number of freely available CAD, mathematical and graphic design packages also make it highly useful to those whose primary interest in a computer is to get _other_ work done!
* _Research:_ With source code for the entire system available, FreeBSD is an excellent platform for research in operating systems as well as other branches of computer science. FreeBSD's freely available nature also makes it possible for remote groups to collaborate on ideas or shared development without having to worry about special licensing agreements or limitations on what may be discussed in open forums.
* _Networking:_ Need a new router? A name server (DNS)? A firewall to keep people out of your internal network? FreeBSD can easily turn that unused PC sitting in the corner into an advanced router with sophisticated packet-filtering capabilities.
* _Embedded:_ FreeBSD makes an excellent platform to build embedded systems upon. With support for the ARM, AArch64 and PowerPC platforms, coupled with a robust network stack, cutting edge features, and the permissive extref:{faq}[BSD license, bsd-license-restrictions], FreeBSD makes an excellent foundation for building embedded routers, firewalls, and other devices.
* _Desktop:_ FreeBSD makes a fine choice for an inexpensive desktop solution using the freely available X11 server and Wayland display server. FreeBSD offers a choice from many open-source desktop environments, including the standard GNOME and KDE graphical user interfaces. FreeBSD can even boot "diskless" from a central server, making individual workstations even cheaper and easier to administer.
* _Software Development:_ The basic FreeBSD system comes with a full suite of development tools including a full C/C++ compiler and debugger suite. Support for many other languages are also available through the ports and packages collection.

FreeBSD is available to download free of charge, or can be obtained on either CD-ROM or DVD.
Please see crossref:mirrors[mirrors, Obtaining FreeBSD] for more information about obtaining FreeBSD.

[[introduction-nutshell-users]]
=== Who Uses FreeBSD?

FreeBSD has been known for its web serving capabilities.
A list of link:https://freebsdfoundation.org/about-us/testimonials/[testimonials from companies basing their products and services on FreeBSD] can be found at the FreeBSD Foundation website.
Wikipedia also maintains a link:https://en.wikipedia.org/wiki/List_of_products_based_on_FreeBSD[list of products based on FreeBSD].

[[history]]
== About the FreeBSD Project

The following section provides some background information on the project, including a brief history, project goals, and the extref:{dev-model}[development model] of the project.

[[intro-history]]
=== A Brief History of FreeBSD

The FreeBSD Project had its genesis in the early part of 1993, partially as the brainchild of the Unofficial 386BSDPatchkit's last 3 coordinators: Nate Williams, Rod Grimes and Jordan Hubbard.

The original goal was to produce an intermediate snapshot of 386BSD in order to fix a number of problems that the patchkit mechanism was just not capable of solving.
The early working title for the project was 386BSD 0.5 or 386BSD Interim in reference to that fact.

386BSD was Bill Jolitz's operating system, which had been up to that point suffering rather severely from almost a year's worth of neglect.
As the patchkit swelled ever more uncomfortably with each passing day, they decided to assist Bill by providing this interim "cleanup" snapshot.
Those plans came to a rude halt when Bill Jolitz suddenly decided to withdraw his sanction from the project without any clear indication of what would be done instead.

The trio thought that the goal remained worthwhile, even without Bill's support, and so they adopted the name "FreeBSD" coined by David Greenman.
The initial objectives were set after consulting with the system's current users and, once it became clear that the project was on the road to perhaps even becoming a reality, Jordan contacted Walnut Creek CDROM with an eye toward improving FreeBSD's distribution channels for those many unfortunates without easy access to the Internet.
Walnut Creek CDROM not only supported the idea of distributing FreeBSD on CD but also went so far as to provide the project with a machine to work on and a fast Internet connection.
Without Walnut Creek CDROM's almost unprecedented degree of faith in what was, at the time, a completely unknown project, it is quite unlikely that FreeBSD would have gotten as far, as fast, as it has today.

The first CD-ROM (and general net-wide) distribution was FreeBSD 1.0, released in December of 1993.
This was based on the 4.3BSD-Lite ("Net/2") tape from U.C. Berkeley, with many components also provided by 386BSD and the Free Software Foundation.
It was a fairly reasonable success for a first offering, and they followed it with the highly successful FreeBSD 1.1 release in May of 1994.

Around this time, some rather unexpected storm clouds formed on the horizon as Novell and U.C. Berkeley settled their long-running lawsuit over the legal status of the Berkeley Net/2 tape.
A condition of that settlement was U.C. Berkeley's concession that three files of Net/2 were "encumbered" code and had to be removed as they were the property of Novell, who had in turn acquired it from AT&T some time previously.
What Berkeley got in return was Novell's "blessing" that the 4.4BSD-Lite release, when it was finally released, would be declared unencumbered and all existing Net/2 users would be strongly encouraged to switch.
This included FreeBSD, and the project was given until the end of July 1994 to stop shipping its own Net/2 based product.
Under the terms of that agreement, the project was allowed one last release before the deadline, that release being FreeBSD 1.1.5.1.

FreeBSD then set about the arduous task of literally re-inventing itself from a completely new and rather incomplete set of 4.4BSD-Lite bits.
Although only three files having to do with System V shared memory and semaphores were removed, many other changes and bug fixes had been made to the BSD distribution, so it was a huge task to merge all the FreeBSD developments into 4.4BSD-Lite.
It took the project until November of 1994 to make this transition, and in December it released FreeBSD 2.0 to the world.
Despite being still more than a little rough around the edges, the release was a significant success and was followed by the more robust and easier to install FreeBSD 2.0.5 release in June of 1995.

Since that time, FreeBSD has made a series of releases each time improving the stability, speed, and feature set of the previous version.

For now, long-term development projects continue to take place in the {rel-head}-CURRENT (main) branch, and snapshot releases of {rel-head} are continually made available from link:https://download.freebsd.org/snapshots/[the snapshot server] as work progresses.

[[goals]]
=== FreeBSD Project Goals

The goals of the FreeBSD Project are to provide software that may be used for any purpose and without strings attached.
Many of us have a significant investment in the code (and project) and would certainly not mind a little financial compensation now and then, but we are definitely not prepared to insist on it.
We believe that our first and foremost "mission" is to provide code to any and all comers, and for whatever purpose, so that the code gets the widest possible use and provides the widest possible benefit.
This is, we believe, one of the most fundamental goals of Free Software and one that we enthusiastically support.

That code in our source tree which falls under the GNU General Public License (GPL) or Library General Public License (LGPL) comes with slightly more strings attached, though at least on the side of enforced access rather than the usual opposite.
Due to the additional complexities that can evolve in the commercial use of GPL software we do, however, prefer software submitted under the more relaxed BSD license when it is a reasonable option to do so.

[[development]]
=== The FreeBSD Development Model

The development of FreeBSD is a extref:{dev-model}[very open and flexible process], being literally built from the contributions of thousands of people around the world, as can be seen from our extref:{contributors}[list of contributors].
FreeBSD's development infrastructure allows these thousands of contributors to collaborate over the Internet.
We are constantly on the lookout for new volunteers, and those interested in becoming more closely involved should consult the article on extref:{contributing}[Contributing to FreeBSD].

Useful things to know about the FreeBSD Project and its development process, whether working independently or in close cooperation:

The Git repositories[[development-cvs-repository]]::
For several years, the central source tree for FreeBSD was maintained by link:https://www.nongnu.org/cvs/[CVS] (Concurrent Versions System), a freely available source code control tool.
In June 2008, the Project switched to using link:https://subversion.apache.org/[SVN] (Subversion).
The switch was deemed necessary, as the technical limitations imposed by CVS were becoming obvious due to the rapid expansion of the source tree and the amount of history already stored.
The Documentation Project and Ports Collection repositories also moved from CVS to SVN in May 2012 and July 2012, respectively.
In December 2020, the Project link:https://www.freebsd.org/status/report-2020-10-2020-12.html#Git-Migration-Working-Group[migrated Source and Documentation repositories] to link:https://git-scm.com/[Git], with link:https://www.freebsd.org/status/report-2021-04-2021-06/#_git_migration_working_group[Ports following suit] in April 2021.
Please refer to the crossref:cutting-edge[synching, Obtaining the Source] section for more information on obtaining the FreeBSD `src/` repository and crossref:ports[ports-using, Using the Ports Collection] for details on obtaining the FreeBSD Ports Collection.

The committers list[[development-committers]]::
The _committers_ are the people who have _push_ access to the Git repository, and are authorized to make modifications to the FreeBSD source (the term "committer" comes from `commit`, the source control command which is used to bring new changes into the repository).
Anyone can submit a bug to the link:https://bugs.FreeBSD.org/submit/[Bug Database].
Before submitting a bug report, the FreeBSD mailing lists, IRC channels, or forums can be used to help verify that an issue is actually a bug.

The FreeBSD core team[[development-core]]::
The _FreeBSD core team_ would be equivalent to the board of directors if the FreeBSD Project were a company.
The primary task of the core team is to make sure the project, as a whole, is in good shape and is heading in the right directions.
Inviting dedicated and responsible developers to join our group of committers is one of the functions of the core team, as is the recruitment of new core team members as others move on.
The current core team was elected from a pool of committer candidates in May and June 2024.
Elections are held every 2 years.
+
[NOTE]
====
Like most developers, most members of the core team are also volunteers when it comes to FreeBSD development and do not benefit from the project financially, so "commitment" should also not be misconstrued as meaning "guaranteed support."
The "board of directors" analogy above is not very accurate, and it may be more suitable to say that these are the people who gave up their lives in favor of FreeBSD against their better judgement!
====

The FreeBSD Foundation[[development-foundation]]::
The link:https://freebsdfoundation.org/[FreeBSD Foundation] is a 501(c)(3), US-based, non-profit organization dedicated to supporting and promoting the FreeBSD Project and community worldwide.
The Foundation funds software development via project grants and provides staff to immediately respond to urgent problems and implement new features and functionality.
The Foundation purchases hardware to improve and maintain FreeBSD infrastructure, and funds staffing to improve test coverage, continuous integration and automation.
The Foundation advocates for FreeBSD by promoting FreeBSD at technical conferences and events around the world.
The Foundation also provides workshops, educational material, and presentations to recruit more users and contributors to FreeBSD.
The Foundation also represents the FreeBSD Project in executing contracts, license agreements, and other legal arrangements that require a recognized legal entity.

Outside contributors::
Last, but definitely not least, the largest group of developers are the users themselves who provide feedback and bug fixes to us on an almost constant basis.
The primary way of keeping in touch with the development of the FreeBSD base system is to subscribe to the {freebsd-hackers} where such things are discussed.
For porting third party applications, it would be the {freebsd-ports}.
For documentation - {freebsd-doc}.
See crossref:eresources[eresources, Resources on the Internet] for more information about the various FreeBSD mailing lists.
+
extref:{contributors}[The FreeBSD Contributors List] is a long and growing one, so why not join it by extref:{contributing}[contributing something back to FreeBSD] today?
Providing code is not the only way!

In summary, our development model is organized as a loose set of concentric circles.
The centralized model is designed for the convenience of the _users_ of FreeBSD, who are provided with an easy way of tracking one central code base, not to keep potential contributors out!
Our desire is to present a stable operating system with a large set of coherent crossref:ports[ports,application programs] that the users can easily install and use - this model works very well in accomplishing that.

All we ask of those who would join us as FreeBSD developers is some of the same dedication its current people have to its continued success!

[[third-party-programs]]
=== Third Party Programs

In addition to the base distributions, FreeBSD offers a ported software collection with thousands of commonly sought-after programs.
The list of ports ranges from HTTP servers to games, languages, editors, and almost everything in between.
There are about {numports} ports; the entire Ports Collection requires approximately {ports-size}.
To compile a port, you simply change to the directory of the program you wish to install, type `make install`, and let the system do the rest.
The full original distribution for each port you build is retrieved dynamically so you need only enough disk space to build the ports you want.

Almost every port is also provided as a pre-compiled "package", which can be installed with a simple command (`pkg install`) by those who do not wish to compile their own ports from source.
More information on packages and ports can be found in crossref:ports[ports,Installing Applications: Packages and Ports].

=== Additional Documentation

All supported FreeBSD versions provide an option in the installer to install additional documentation under [.filename]#/usr/local/share/doc/freebsd# during the initial system setup.
Documentation may also be installed later using packages:

[source,shell]
....
# pkg install en-freebsd-doc
....

For localized versions replace the "en" with the language prefix of choice.
Be aware that some of the localised versions might be out of date and might contain information that is no longer correct or relevant.
You may view the locally installed manuals with a web browser using the following URLs:

The FreeBSD Handbook::
`/usr/local/share/doc/freebsd/en/books/handbook/handbook_en.pdf`

The FreeBSD FAQ::
`/usr/local/share/doc/freebsd/en/books/faq/faq_en.pdf`

You can always find up to date documentation at link:https://docs.FreeBSD.org/[The Documentation Portal].

All trademarks are the property of their respective owners.
