#
# $FreeBSD$
#

DOC_PREFIX?=	${.CURDIR}/../../..
RELN_ROOT?=	${.CURDIR}

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=		11.0R

.include "${DOC_PREFIX}/share/mk/doc.subdir.mk"
