# $FreeBSD: www/ja/java/dists/Makefile,v 1.8 2010/08/06 20:54:16 ryusuke Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.8

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	10.sgml
DOCS+=	11.sgml
DOCS+=	12.sgml
DOCS+=	13.sgml
DOCS+=	14.sgml
DOCS+=	15.sgml
#DOCS+=	16.sgml
#DOCS+=	17.sgml
DOCS+=	index.sgml

### Revision checking
REVCHECK= YES

.include "${DOC_PREFIX}/share/mk/web.site.mk"
