#
# $FreeBSDde: de-www/handbook/Makefile,v 1.2 2002/12/02 05:35:13 ue Exp $
# $FreeBSD$
# basiert auf:	1.9

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	index.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
