---
title: "FreeBSD 14.4-RELEASE Errata"
sidenav: download
---

:release: 14.4-RELEASE
:releaseNext: 14.5-RELEASE
:releaseBranch: 14-STABLE

= FreeBSD {release} Errata

== Abstract

This document lists errata items for FreeBSD {release}, containing significant information discovered after the release or too late in the release cycle to be otherwise included in the release documentation.
This information includes security advisories, as well as news relating to the software or documentation that could affect its operation or usability.
An up-to-date version of this document should always be consulted before installing this version of FreeBSD.

This errata document for FreeBSD {release} will be maintained until the release of FreeBSD {releaseNext}.

== Table of Contents

* <<intro,Introduction>>
* <<security,Security Advisories>>
* <<errata,Errata Notices>>
* <<open-issues,Open Issues>>
* <<late-news,Late-Breaking News>>

[[intro]]
== Introduction

This errata document contains "late-breaking news" about FreeBSD {release}.
Before installing this version, it is important to consult this document to learn about any post-release discoveries or problems that may already have been found and fixed.

Any version of this errata document actually distributed with the release (for example, on a CDROM distribution) will be out of date by definition, but other copies are kept updated on the Internet and should be consulted as the "current errata" for this release.
These other copies of the errata are located at https://www.FreeBSD.org/releases/, plus any sites which keep up-to-date mirrors of this location.

Source and binary snapshots of FreeBSD {releaseBranch} also contain up-to-date copies of this document (as of the time of the snapshot).

For a list of all FreeBSD CERT security advisories, see https://www.FreeBSD.org/security/.

[[security]]
== Security Advisories

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Advisory |Date |Topic
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:06.tcp.asc[FreeBSD-SA-26:06.tcp] |26 March 2026 |TCP: remotely exploitable DoS vector (mbuf leak)
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:08.rpcsec_gss.asc[FreeBSD-SA-26:08.rpcsec_gss] |26 March 2026 |Remote code execution via RPCSEC_GSS packet validation
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:09.pf.asc[FreeBSD-SA-26:09.pf] |26 March 2026 |pf silently ignores certain rules
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:10.tty.asc[FreeBSD-SA-26:10.tty] |21 April 2026 |Kernel use-after-free bug in the TIOCNOTTY handler
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-26:11.amd64.asc[FreeBSD-SA-26:11.amd64] |21 April 2026 |Missing large page handling in pmap_pkru_update_range()
|===

[[errata]]
== Errata Notices

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Errata |Date |Topic

|No errata notices.||

|===

[[open-issues]]
== Open Issues

1. **man:freebsd-update[8]** commands such as `fetch` or `install` may hang when man:pkg[8] is not bootstrapped on the system. +
**Workaround**: run man:pkg[8] to install the package management tool, then reuse man:freebsd-update[8]. +
**State**: open - https://bugs.freebsd.org/293516 +

2. **man:loader_lua[8]** A regression in the boot loader scripts causes the wrong kernel to be selected if /boot/kernel is a symlink. +
**Workaround**: Disable automatic kernel detection by adding kernels_autodetect="NO" to [.filename]#/boot/loader.conf#. +
**State**: fixed in main - https://bugs.freebsd.org/293654 +

[[late-news]]
== Late-Breaking News

No late-breaking news.
