=== Проект генеральной уборки Alpha-Omega (Alpha-Omega Beach Cleaning)

Ссылки: +
link:https://alpha-omega.dev[Alpha-Omega -- Проект Linux Foundation] URL: link:https://alpha-omega.dev[] +
link:https://github.com/ossf/alpha-omega[Alpha-Omega на GitHub] URL: link:https://github.com/ossf/alpha-omega[] +
link:https://freebsdfoundation.org[Фонд FreeBSD] URL: link:https://freebsdfoundation.org[] +
link:https://github.com/FreeBSDFoundation/alpha-omega-beach-cleaning[Репозиторий проекта от Фонда FreeBSD] URL: link:https://github.com/FreeBSDFoundation/alpha-omega-beach-cleaning[]

Контакт: Pierre Pronchery <pierre@freebsdfoundation.org>

Миссия Alpha-Omega — стимулировать устойчивые улучшения безопасности критически важных проектов с открытым исходным кодом и экосистем.
После успешного проекта с Фондом FreeBSD в 2024 году (аудит гипервизора bhyve и фреймворка изоляции Capsicum) Alpha-Omega снова выбрала FreeBSD — на этот раз для проекта Alpha Omega Beach Cleaning.
Этот новый грант направлен на общее повышение безопасности и сопровождаемости стороннего программного обеспечения в базовой системе FreeBSD.
Фонд FreeBSD получил грант, а также управлял и выполнял проект.
Официально проект завершён 30 марта 2026 года.

После предыдущего отчёта за 2025Q4 были определены две основные цели:

* Импорт pkgconf в базовую систему (см. link:https://github.com/freebsd/freebsd-src/pull/1994[черновик PR #1994] на GitHub)
* Импорт pkg в базовую систему (см. link:https://github.com/khorben/freebsd-src/tree/khorben/pkg-2.6.2[ветку khorben/pkg-2.6.2] на GitHub)

Обе цели близки к завершению, и они были публично представлены на AsiaBSDCon 2026 на Тайване, как в ходе link:https://wiki.freebsd.org/DevSummit/202603[Саммита разработчиков FreeBSD], так и на link:https://2026.asiabsdcon.org/entry/talk/MSBLUR/[сессии Work-in-Progress] конференции.

Ежемесячные отчёты направлялись в alpha-omega и доступны, как и прежде, на GitHub: link:https://github.com/ossf/alpha-omega/tree/main/alpha/engagements/2025/FreeBSD[за 2025 год] и link:https://github.com/ossf/alpha-omega/tree/main/alpha/engagements/2026/FreeBSD[за 2026 год].

Спонсоры: Alpha-Omega, Фонд FreeBSD

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (18.04.2026): c2b58fa4f22a49990eee8c547a55aaeb63b59cdd
//
