=== Разработка драйверов FreeBSD для BananaPi-R64/R2-PRO

Ссылки: +
link:https://wiki.freebsd.org/arm/Bananapi[Wiki] URL: link:https://wiki.freebsd.org/arm/Bananapi[]

Контакт: Martin Filla <freebsd@sysctl.cz>

==== Введение в R64

Banana Pi R64 — это плата разработки на базе MediaTek MT7622 (ARM Cortex-A53, двухъядерный ~1.35 ГГц), оснащённая 4× Gigabit LAN, 1× Gigabit WAN, Wi-Fi (4×4n), Bluetooth 5.0 и множеством периферийных интерфейсов (UART, SPI, I²C, GPIO, SATA, mini-PCIe, eMMC и так далее).

==== Текущее состояние поддержки FreeBSD на R64

На данный момент реализовано:

- **Драйвер UART**
- **Управление тактовой частотой (clocks)**
- **Pinctrl**
- **Драйвер контроллера хранения (eMMC/SD/MMC)**
- **Драйвер Ethernet-коммутатора mt7531**
- **Драйвер Ethernet mt7622**
- **Драйвер XHCI**
- **Драйвер Watchdog**
- **Драйвер RTC**
- **Драйвер RNG**
- **Драйвер Pciecfg**
- **Драйвер SysIRQ**

==== План разработки для R64

Реализовать недостающие драйверы:

- USB3 / T-PHY
- SATA / AHCI / T-PHY
- Wi-Fi (вероятно, MediaTek MT7615)
- Подсистемы GPIO
- I2C
- SPI
- PWM
- PCIE

Драйверы в стадии разработки:
- T-PHY


==== Введение в R2-PRO

Banana Pi BPI-R2 Pro — это плата разработки следующего поколения для интеллектуальных маршрутизаторов.
Она работает на процессоре Rockchip RK 3568.
Имеет на борту 2 ГБ LPDDR4 и 16 ГБ eMMC, поддерживает 2 интерфейса USB 3.0, 5 гигабитных сетевых портов.
Интерфейсы M.2 key-E и mini PCIe, 2 интерфейса mipi DSI (один можно программно переключить на LVDS), 1 интерфейс CSI для камеры, 1 выход HDMI.

==== Текущее состояние поддержки FreeBSD на R2-PRO

На данный момент реализовано:

- **Драйвер UART**
- **Управление тактовой частотой (clocks)**
- **Pinctrl**
- **GPIO**
- **Драйвер контроллера хранения (eMMC/SD/MMC)**
- **Драйвер XHCI**
- **Драйвер Watchdog**
- **Драйвер PCIE**

==== План разработки для R2-PRO

Реализовать недостающие драйверы:
- HDMI
- MIPI
- USB3

Драйверы в стадии разработки:
- AHCI/SATA
- PCIE

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (18.04.2026): 3480adec52cec96058bf41422969e7354c66e97b
//
