=== Графический интерфейс управления bhyve, написанный на Freepascal/Lazarus

Ссылки: +
link:https://github.com/alonsobsd/bhyvemgr[Bhyvemgr] URL: link:https://github.com/alonsobsd/bhyvemgr/[] +

Контакт: José Alonso Cárdenas Márquez <acm@FreeBSD.org>

Bhyvemgr — это графический интерфейс управления bhyve, написанный на Freepascal/Lazarus во FreeBSD.
Для работы ему требуется набор инструментов, в основном установленных в базовой системе, а некоторые устанавливаются из портов/пакетов.
Основная цель — создать настольное приложение, ориентированное на пользователей рабочих станций, позволяющее легко и быстро настраивать и запускать виртуальные машины на хостах FreeBSD.

В течение этого квартала в Bhyvemgr было сделано множество исправлений ошибок и улучшений.

Вот некоторые основные добавленные улучшения:

- Добавлена поддержка PF/NAT
- Добавлен параметр -n для команд sudo/doas.
  В случае отсутствия прав на запуск некоторых приложений ошибка будет сохранена в файл журнала
- Добавлены некоторые инструкции в link:https://github.com/alonsobsd/bhyvemgr/wiki[wiki] bhyvemgr
- Изменён параметр RDP: /log-level:off на /log-level:ERROR
- Улучшена поддержка aarch64
- Улучшено окно настроек
- Улучшена поддержка IPv6
- Улучшена функциональность журналирования
- Обновлены переводы

Bhyvemgr поддерживает aarch64 на версиях от 15.x до 16-CURRENT и amd64 на версиях FreeBSD от 14.x до 16-CURRENT.
Его можно скомпилировать или установить из link:https://www.freshports.org/sysutils/bhyvemgr[портов] или пакетов с поддержкой интерфейса gtk2, qt5 или qt6.

Приветствуются люди, заинтересованные в помощи или поддержке проекта.

Текущая версия: 1.13.1

Спонсор: link:https://paypal.me/alonsocbsd[]

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (18.04.2026): bbcf0280a1c74936f620e44327d8639d1eeca8c4
//
