=== Контейнеры и FreeBSD: Cloud Native Buildpacks

Ссылки: +
link:https://buildpacks.io/[Cloud Native Buildpacks (CNBs)] URL: link:https://buildpacks.io/[] +
link:https://github.com/buildpacks/pack[Репозиторий Buildpacks на GitHub] URL: link:https://github.com/buildpacks/pack[]

Контакт: Robert Gogolok <gogolok@gmail.com>

link:https://buildpacks.io/[Cloud Native Buildpacks (CNBs)] преобразуют исходный код приложения в образы контейнеров.
Эти образы могут работать в любом облаке.
С помощью buildpacks организации могут сконцентрировать знания о передовых практиках сборки контейнеров в специализированной команде, вместо того чтобы заставлять разработчиков приложений по всей организации индивидуально сопровождать свои собственные Dockerfile.

С момента последнего отчёта в 2025Q1 проект перешёл от экспериментальной поддержки к официальному предоставлению бинарных файлов:

* Как основной инструмент CLI `pack`, так и ключевой компонент `lifecycle` теперь поставляются с бинарными файлами для FreeBSD при каждом новом релизе вышестоящего репозитория.
* Новый порт для CLI, `sysutils/pack`, был отправлен (link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=292952[PR 292952]).
  Это позволит пользователям устанавливать инструмент с помощью `pkg install pack` после того, как порт будет зафиксирован.
* Официальный репозиторий link:https://github.com/buildpacks/samples[buildpacks/samples] теперь включает pull request (link:https://github.com/buildpacks/samples/pull/201[PR #201]) для FreeBSD в статусе Work-In-Progress.

Следующие шаги сосредоточены на снижении порога входа для разработчиков и улучшении автоматизации процесса сборки для FreeBSD:

* Найти коммитера портов FreeBSD, который рассмотрит и добавит link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=292952[новый порт sysutils/pack] в дерево портов.
* Решить link:https://github.com/buildpacks/pack/issues/2546[известную проблему] в `pack builder create`, где инструмент ошибочно пытается использовать URL-адреса, не предназначенные для FreeBSD, для загрузки определённых бинарных файлов.
* Изучить возможность создания link:https://paketo.io[buildpacks в стиле Paketo] специально для FreeBSD.
  Это обеспечит сборки с «нулевой конфигурацией» для популярных языков (например, Go), создающие внутри контейнеров нативные бинарные файлы для FreeBSD.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (18.04.2026): 52a1580efbe35dc8b5ecb173d31f81811db8415a
//
