=== Порты — сделать openjdk21 версией JAVA_VERSION по умолчанию

Ссылки:
link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272855[Ошибка 272855] URL: link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272855[]
link:https://docs.google.com/spreadsheets/d/17hmRQ0ShY4SHHVEkQBVxqK2G88fPZLriTzO26zXdjC4/edit?usp=sharing[Таблица отслеживания незавершённой работы] URL: link:https://docs.google.com/spreadsheets/d/17hmRQ0ShY4SHHVEkQBVxqK2G88fPZLriTzO26zXdjC4/edit?usp=sharing[]

Контакт: Ronald Klop <ronald@FreeBSD.org>

Наличие активной среды Java полезно для всех видов приложений FreeBSD.

Версия JAVA_VERSION по умолчанию в портах FreeBSD была изменена с 8 на 21 26 февраля.
Это был серьёзный шаг в смене версий.
Поэтому потребовалось довольно много работы.
Теперь всё сделано.

Все известные порты, которые могли сломаться, были исправлены, и с тех пор не поступало сообщений о регрессиях.
Ветка портов 2026Q2 будет первой стабильной веткой портов, в которой OpenJDK 21 будет версией Java по умолчанию.

* Большое спасибо всем причастным
* Во втором квартале начата работа по тому, чтобы сделать 25 новой версией JAVA_DEFAULT в main

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (18.04.2026): 48c4af7948fb2b7792af4a91f642a2b57cf6a9fe
//
