=== Бенчмарк ядра, MAINTAINERS и pkgdist

Ссылки: +

link:https://github.com/Humanoid-Human/fbsd-work/blob/main/kernel-benchmark.md[Статья о бенчмарке ядра] URL: https://github.com/Humanoid-Human/fbsd-work/blob/main/kernel-benchmark.md[] +
link:https://github.com/freebsd/srcmgr/issues/21[Обсуждение MAINTAINERS в srcmgr] URL: https://github.com/freebsd/srcmgr/issues/21[] +
link:https://github.com/freebsd/freebsd-src/pull/2107[Pull request для MAINTAINERS] URL: https://github.com/freebsd/freebsd-src/pull/2107[] +
link:https://github.com/Humanoid-Human/fbsd-work/pull/1[Конвертер pkg в набор дистрибутива] URL: https://github.com/Humanoid-Human/fbsd-work/pull/1[]

Контакт: Trevor Xu <trevorxu5@gmail.com>

Моя работа в этом квартале была разделена между тремя проектами.

==== Бенчмарк ядра

Я провёл несколько бенчмарков FreeBSD 15.0-RELEASE, FreeBSD 16.0-CURRENT (установка по умолчанию) и FreeBSD 16.0-CURRENT с отключённой отладкой ядра.
Целью этой работы было предоставление точных измерений влияния инструментов отладки ядра на производительность.
Я обнаружил, что установка 16.0-CURRENT по умолчанию (то есть с отладкой) была значительно медленнее, чем 15.0-RELEASE, особенно в таких областях, как выделение памяти.
С другой стороны, 16.0-CURRENT при правильной настройке показал производительность, сравнимую с 15.0-RELEASE, во всех проведённых мной тестах.
Доступна link:https://github.com/Humanoid-Human/fbsd-work/blob/main/kernel-benchmark.md[полная статья].

==== Модернизация MAINTAINERS

Основываясь на информации из link:https://github.com/freebsd/srcmgr/issues/21[обсуждения в srcmgr], я создал структуру для UCL-файла, который будет хранить сопровождающих и пути для отслеживания, в качестве замены текущего файла MAINTAINERS.
Затем я написал скрипт на flua, который читает этот файл и может выводить CODEOWNERS для GitHub или Forgejo, получать сопровождающих для конкретного пути, получать пути для конкретного сопровождающего и так далее.
Pull request можно найти link:https://github.com/freebsd/freebsd-src/pull/2107[здесь].

==== Конвертер pkg в набор дистрибутива

В настоящее время я работаю над написанием shell-скрипта, который может преобразовывать набор пакетов pkgbase в набор дистрибутива.
Это поможет облегчить переход на pkgbase.

Спонсор: Фонд FreeBSD

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (18.04.2026): 6440a94fe4e27bf6484ee3605e7cf580c4b05f74
//
