=== Коллекция портов

Ссылки: +
link:https://www.FreeBSD.org/ports/[О портах FreeBSD] URL:link:https://www.FreeBSD.org/ports/[] +
link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[Вклад в порты] URL: link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[] +
link:https://www.freebsd.org/portmgr/[Команда управления портами] URL: link:https://www.freebsd.org/portmgr/[] +
link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[Tar-архив портов] URL: link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[]

Контакт: Команда управления портами FreeBSD <portmgr@FreeBSD.org>

Команда управления портами отвечает за общее направление развития дерева портов, сборку пакетов и кадровые вопросы.
Ниже описано, что произошло в последнем квартале.

В течение последнего квартала мы приветствовали Юсуфа Ямана (Yusuf Yaman, nxjoseph), Косукэ Каннаги (Kousuke Kannagi, mce), Петра Смырака (Piotr Smyrak, smyru), Лорана Шардона (Laurent Chardon, laurent) и Кеннета Рэпли (Kenneth Raplee, kenrap) в качестве новых коммиттеров портов и попрощались с одним коммиттером.

Согласно INDEX, в настоящее время в Коллекции портов насчитывается 37 958 портов (выросло с 37 163).
В настоящее время открыто около 2 710 PR по портам (снизилось с 3 428), из которых 798 (снизилось с 821) не назначены.
За последний квартал было совершено 8 970 коммитов (выросло с 8 738) от 166 коммиттеров (выросло с 156) в основной ветке и 697 коммитов (снизилось с 898) от 59 коммиттеров (снизилось с 61) в ветке 2026Q1.

Наиболее активные коммиттеры в основной ветке:
2135 sunpoet@FreeBSD.org
 800 yuri@FreeBSD.org
 528 vvd@FreeBSD.org
 312 bofh@FreeBSD.org
 294 tagattie@FreeBSD.org
 182 nivit@FreeBSD.org
 177 arrowd@FreeBSD.org
 175 eduardo@FreeBSD.org
 153 fuz@FreeBSD.org
 132 mfechner@FreeBSD.org

За последние три месяца в дереве портов произошло много событий, вот выдержка из основных обновлений программного обеспечения:

- pkg 2.6.2
- Новый USES: inotify
- Версия Go по умолчанию переключена на 1.25
- Версия Java по умолчанию переключена на 21 (и 11 на armv*)
- Версия Lazarus по умолчанию переключена на 4.6 (и 4.99 на aarch64 и powerpc*)
- Версия MySQL по умолчанию переключена на 8.4
- Версия PostgreSQL по умолчанию переключена на 18
- Chromium 146.0.7680.177
- Electron 40.8.3 добавлен
- Firefox 149.0
- Firefox-esr 140.9.0
- KDE Plasma 6.6.3
- KDE Frameworks 6.24.0
- KDE Applications 25.12.3
- Qt6 6.10.2
- Ruby 3.2.10, 3.4.8, 4.0.1
- Rust 1.94.0
- SDL 3.2.30
- wlroots 0.20.0 добавлен
- Wine 11.0

В течение последнего квартала pkgmgr@ провёл 29 экспериментальных сборок (exp-run) для тестирования различных изменений в базовой системе и обновлений портов.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (18.04.2026): 5a8e131a22f67d7bfba507cf895c65114c2a3695
//
