=== Wazuh на FreeBSD

Ссылки: +
link:https://wazuh.com[Wazuh] URL: link:https://wazuh.com[]

Контакт: José Alonso Cárdenas Márquez <acm@FreeBSD.org> +
Контакт: Jesús Daniel Colmenares Oviedo <dtxdf@FreeBSD.org>

Wazuh — это бесплатная платформа с открытым исходным кодом, используемая для предотвращения, обнаружения угроз и реагирования на них.
Она способна защищать рабочие нагрузки в локальных, виртуализированных, контейнерных и облачных средах.

Решение Wazuh состоит из агента безопасности конечной точки, развёртываемого на отслеживаемых системах, и управляющего сервера (менеджера), который собирает и анализирует данные, собранные агентами.
Кроме того, Wazuh полностью интегрирован с Elastic Stack или OpenSearch Stack, предоставляя поисковую систему и инструмент визуализации данных, который позволяет пользователям перемещаться по своим оповещениям безопасности.

В этом квартале произошло много событий.
Многочисленные улучшения и исправления ошибок для улучшения поддержки FreeBSD этой превосходной платформой XDR/SIEM и безопасности.

* Мы создали репозиторий на GitHub для централизации работы и уменьшения патчей в менеджере и агенте.
Ссылки: link:https://github.com/alonsobsd/wazuh-freebsd[Репозиторий], link:https://cgit.freebsd.org/ports/commit/?id=b1f52980fe0a34ccaa674408c92869aec9aac4fe[b1f5298]
* Пакет Python обновлён до версии 3.11.15.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=c941e5b33dea22c240b2b0bb53dd191bb1e8da4a[c941e5b]
* Исправлена проблема, которая не позволяла wazuh-manager запускаться при включённой опции MYSQL.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=c941e5b33dea22c240b2b0bb53dd191bb1e8da4a[c941e5b]
* Исправлена проблема разбора в функции `getPorts()` модуля sysinfo.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=35fcd6a4cc00bedfe350da9503d4d09d3e914006[35fcd6a]
* Добавлена поддержка FreeBSD в библиотеку asyncinotify, которая предотвращала корректный запуск Wazuh API.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=35fcd6a4cc00bedfe350da9503d4d09d3e914006[35fcd6a]
* Теперь Wazuh использует OpenSearch Dashboards 2.19.4.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=b1f52980fe0a34ccaa674408c92869aec9aac4fe[b1f5298]
* Модуль sysinfo теперь может получать информацию о пользователях и группах.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=e9cebac52c06bab51b406304d7e5a6397fddec77[e9cebac]
* Исправлена проблема между агентом и менеджером, которая препятствовала успешному активному состоянию для TCP-соединений, и теперь этот протокол используется по умолчанию вместо UDP.
Ссылки: link:https://cgit.freebsd.org/ports/commit/?id=055d5c96c56d8cc876451ccb9b0eb80bcac8d72a[055d5c9], link:https://cgit.freebsd.org/ports/commit/?id=508a8c8d4b9b836cc1effee7b5f462a53c644501[508a8c8]
* Обновлены файлы SCA, декодеров и правил для FreeBSD, исправлены конфликтные проблемы.
Ссылки: link:https://cgit.freebsd.org/ports/commit/?id=055d5c96c56d8cc876451ccb9b0eb80bcac8d72a[055d5c9], link:https://cgit.freebsd.org/ports/commit/?id=508a8c8d4b9b836cc1effee7b5f462a53c644501[508a8c8]
* Проблема с Python-скриптами в менеджере препятствовала их корректному выполнению, когда не установлена переменная окружения `CRYPTOGRAPHY_OPENSSL_NO_LEGACY`.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=8bd6c77634f475a0ff31bda46b4c04f91fa74d79[8bd6c77]
* Улучшена функция `getSerialNumber()` в sysinfo, поэтому менеджер и агент теперь могут использовать sysctl `kern.hostuuid` для уникальной идентификации устройств.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=284813ec0382a2bfe5b2e74a3081a67599d3155d[284813e]
* Исправлена проблема в wazuh-modulesd, которая вызывала SIGSEGV при распаковке базы данных обнаружения уязвимостей и доступе к неинициализированной структуре.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=d3c13b6b24ec7d9be58f0ebd3a2c7d0a2e7b7d79[d3c13b6]
* Исправлена проблема в агенте, которая вызывала «ошибку разрешения» из-за неправильного владельца файла [.filename]#etc/clients.keys#.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=c74ab75450040f0367851979ff46cd64d74d6a1f[c74ab75]
* package:security/wazuh-server[] переключён с beats7 на beats8.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=ce6831e12ecbcdbce6a1b4fb2988b9663e370a78][ce6831e]
* Исправлена ошибка сегментации в wazuh-modulesd, когда man:pkg[8] не установлен в системе, а функция `getPackages()` sysinfo пытается получить информацию об установленных пакетах.
Теперь эта функция реализована заново для использования SQLite.
Ссылки: link:https://cgit.freebsd.org/ports/commit/?id=ff957155fa2a7ee01ceeec45b1fb75d80f856c58[ff95715], link:https://cgit.freebsd.org/ports/commit/?id=a4242bfeafc2dd423cf145060abb9b5562958c72[a4242bf]
* Применён man:dos2unix[1] к файлу [.filename]#api.yaml# Wazuh API.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=a4242bfeafc2dd423cf145060abb9b5562958c72[a4242bf]
* Исправлена проблема с wazuh-apid, которая не позволяла ему запускаться корректно, помечая себя как DOWN, когда `security.bsd.see_other_{u,g}ids` установлен в `0`.
Ссылка: link:https://cgit.freebsd.org/ports/commit/?id=c86d3fc116b3437ff3351e8e886926175aaec2b1[c86d3fc]
* Создана страница в вики FreeBSD для централизации проделанной нами работы и того, что осталось сделать.
Ссылка: link:https://wiki.FreeBSD.org/Wazuh[Wiki]

Makejails для Wazuh были улучшены и теперь имитируют официальные Dockerfile, поэтому пользователи, знакомые с ними, могут легко развернуть все компоненты Wazuh с помощью link:https://github.com/DtxdF/AppJail[AppJail] и link:https://github.com/DtxdF/director[Director]:

* link:https://github.com/AppJail-makejails/wazuh-manager[wazuh-manager]
* link:https://github.com/AppJail-makejails/wazuh-agent[wazuh-agent]
* link:https://github.com/AppJail-makejails/wazuh-indexer[wazuh-indexer]
* link:https://github.com/AppJail-makejails/wazuh-certs-tool[wazuh-certs-tool]
* link:https://github.com/AppJail-makejails/wazuh-dashboard[wazuh-dashboard]

Это также добавляет инфраструктуру кластерного режима для Makejails.

Обнаружение уязвимостей (vulnerability detection) ещё не реализовано во FreeBSD, но для устранения этого недостатка был разработан link:https://github.com/DtxdF/serpico[Serpico].
Serpico — это сканер безопасности для пакетов и релизов FreeBSD, который сравнивает версии со списком версий, помеченных как уязвимые, и отображает информацию об уязвимостях в компактном формате JSON для лёгкого анализа с помощью других инструментов безопасности.
Пакет включает правила для Wazuh и панель управления, которую можно легко установить через веб-интерфейс или OpenSearch Dashboards API.

Текущая версия: 4.14.3

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (18.04.2026): 9f26ca80793e63aaf97f45babafe2e42beed5b2d
//
