# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.10

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   current.xml
DOCS+=	doc-set.xml
DOCS+=  handbook.xml
DOCS+=  handbook3.xml
DOCS+=  sgml.xml
DOCS+=  submitting.xml
DOCS+=  who.xml
DOCS+=  translations.xml
DOCS+=	docproj.xml

INDEXLINK= docproj.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
