---
title: "Supporto su FreeBSD"
sidenav: support
---

= Supporto su FreeBSD

FreeBSD offre agli utenti una grande varietà di scelta di supporto sia dalla comunità che commerciale. La sezione sulla link:../community/[Comunità] di questo sito web descrive le opzioni di supporto disponibili per gli utenti della comunità di FreeBSD, tra cui un certo numero di link:https://www.FreeBSD.org/community/mailinglists/[mailing list].

Il supporto commerciale è inoltre disponibile da uno dei tanti link:https://www.FreeBSD.org/commercial/[venditori] che offrono prodotti commerciali, servizi, e/o consulenza su FreeBSD.

== Comunicare un Problema

Hai trovato un bug in FreeBSD? Hai notato un errore nella documentazione? Se non è stato già segnalato, faccelo sapere.

Per scoprirlo, puoi link:https://www.FreeBSD.org/cgi/query-pr-summary.cgi?query[ricercare tra le segnalazioni di problemi correnti] (e vederli per categoria, assegnatario, e così via), link:https://www.FreeBSD.org/cgi/query-pr.cgi[vedere una singola segnalazione di un problema], oppure link:https://www.FreeBSD.org/cgi/query-pr-summary.cgi[vedere tutte le segnalazioni di problemi aperti].

Se il bug non è già stato segnalato, per favore leggi le nostre link:https://www.FreeBSD.org/support/bugreports/[linee guida per la comunicazione dei problemi] e poi avvisaci tramite il nostro link:https://bugs.freebsd.org/submit/[form di segnalazione di un problema].
