.\" $FreeBSD$
.\" @(#)publickey.5	2.1 88/08/07 4.0 RPCSRC; from 1.6 88/02/29 SMI;
.\" $Id: publickey.5,v 1.1 2002-10-07 15:43:56 gioria Exp $
.\" Original Revision: 1.6
.Dd 19 Octobre 1987
.Dt PUBLICKEY 5
.Os
.Sh NAME
.Nm publickey
.Nd "base de données des clefs publiques"
.Sh SYNOPSIS
.Pa /etc/publickey
.Sh DESCRIPTION
.Pa /etc/publickey
est la base de données des clefs publiques utilisée pour
les connexions réseau sécurisées. Chaque entrée
dans la base de données, consiste en un nom d'utilisateur 
réseau (qui peut être un utilisateur ou un nom de 
machine), suivie par la clef publique de l'utilisateur (en
notation hexadécimale), une virgule, et la clef secrète
de l'utilisateur chiffrée avec son mot de passe de session (
en notation hexadécimale aussi).
.Pp
Ce fichier peut être modifié par l'utilisateur via
la commande
.Xr chkey 1
ou par l'administrateur système via la commande
.Xr newkey 8 .
Le fichier
.Pa /etc/publickey
doit uniquement contenir des données sur la machine maitre
.Tn NIS
, ou il est converti en fichier
.Pa publickey.byname 
dans la base de données
.Tn NIS .
.Sh SEE ALSO
.Xr chkey 1 ,
.Xr publickey 3 ,
.Xr newkey 8 ,
.Xr ypupdated 8
