---
title: "Proyecto FreeBSD/i386"
sidenav: developers
---

include::shared/es/urls.adoc[]
include::shared/releases.adoc[]

= Proyecto FreeBSD/i386

[[intro]]
== Introducción

Esta página contiene información acerca de la plataforma FreeBSD/i386. Esta arquitectura soporta una extensa variedad de CPU ya que la mayoría de los usuarios compran este tipo de máquinas. Si se tiene una máquina de una compañía de PC (tal como Dell(TM), HP o eMachines(R)) lo más probable es que tenga una CPU AMD(TM) o Intel(R), que pertenecen a esta categoría.

[[toc]]
== Índice

* <<news,Últimas noticias>>
* <<hw,Lista de hardware>>
* <<links,Puntos interesantes>>

[[news]]
== Últimas noticias

* FreeBSD 6.0 (y versiones posteriores) no soporta la CPU original Intel 80386; estos sistemas tienen más de siete añ y sólo FreeBSD 5.X (y versiones anteriores) las soportan. El kernel GENERIC incluye soporte para la CPU 80386 sólamente en FreeBSD 4.X y versiones anteriores.

[[hw]]
== Lista de hardware

Hay una lista de CPU soportadas en las link:https://www.FreeBSD.org/releases/{u-rel120-hardware}#PROC-I386[Notas de Hardware de FreeBSD/i386].

[[links]]
== Puntos interesantes

* http://laptop.bsdgroup.de/freebsd/[Lista de computadoras portátiles compatibles con FreeBSD]
* link:wiki.freebsd.org/ACPI[Página del Proyecto ACPI]
