---
title: "FreeBSD/MIPS Project"
sidenav: developers
---

include::shared/es/urls.adoc[]

= FreeBSD/MIPS Project

Esta página contiene información sobre el port de FreeBSD para MIPS.

== Información general

* <<faq,FAQ del port>>
* <<list,Lista de correo de FreeBSD/MIPS>>

[[faq]]
== Preguntas más frecuentes

. <<what,¿Qué es el proyecto FreeBSD/MIPS?>>
. <<hw,¿Qué hardware soporta?>>
. <<status,¿Cuál es el estado actual?>>
. <<get,¿Cómo puedo conseguir FreeBSD/MIPS?>>
. <<contact,¿Con quién debo ponerme en contacto?>>

[[what]]
=== ¿Qué es el proyecto FreeBSD/MIPS?

FreeBSD/MIPS es un port del sistema operativo FreeBSD para computadoras con MIPS R4K o procesadores más recientes, especialmente computadores MIPS de SGI.

[[hw]]
=== ¿Qué hardware soporta?

Actualmente las computadoras MIPS de SGI. Esperamos que más adelante el soporte llegue a otras arquitecturas MIPS, como las placas empotradas más comunes y los sistemas menos exóticos que dispongan de configuraciones similares a los de SGI.

[[status]]
=== ¿Cuál es el estado actual?

FreeBSD/MIPS está en sus primeros pasos de desarrollo, consulte link:https://www.FreeBSD.org/projects/mips[la página de situación del proyecto] para más información.

[[get]]
=== ¿Cómo puedo conseguir FreeBSD/MIPS?

FreeBSD/MIPS está de momento en el repositorio Perforce de FreeBSD pero de vez en cuando se envían "diffs" a la <<list,lista de correo>>.

[[contact]]
=== ¿Con quién debo ponerme en contacto?

mailto:jmallett@FreeBSD.org[Juli Mallett] es la jefa del proyecto. Póngase en contacto con ella si puede contribuir al código. Si solamente quiere saber cuál es el estado del proyecto, consulte link:https://www.FreeBSD.org/projects/mips[la página de situación del proyecto] con frecuencia o suscríbase a la <<list,lista de correo de FreeBSD/MIPS>>.

[[list]]
== Lista de correo de FreeBSD/MIPS

Para suscribirse a la lista envíe un correo a `<freebsd-mips-subscribe@FreeBSD.org>` o visite http://lists.FreeBSD.org/mailman/listinfo/freebsd-mips[la interfaz de mailman].
