---
title: "Proyecto FreeBSD/sun4v"
sidenav: developers
---

include::shared/releases.adoc[]
include::shared/es/urls.adoc[]
include::shared/authors.adoc[]

= Proyecto FreeBSD/sun4v

[[intro]]
== Introducción

Esta página contiene información sobre el port de FreeBSD para arquitectura UltraSPARC-T1(R) de Sun Microsystem. El intercambio de información sobre el port UltraSPARC-T1 tienen lugar en la lista de distribución http://lists.freebsd.org/mailman/listinfo/freebsd-sun4v[freebsd-sun4v].

[[toc]]
== Contenidos

* <<who,Créditos>>
* <<news,Últimas noticias>>
* <<hw,Lista de hardware>>
* <<todo,Tareas pendientes>>
* <<links,Enlaces de interés>>

[[who]]
== Créditos

Las personas siguientes han trabajado en mayor o menor medida para que el port funcione:

* {kmacy}
* {jb}

[[news]]
== Últimas noticias

* *13 de noviembre de 2006*: La gestión de tiempo/fecha del sistema está terminada.
* *12 de noviembre de 2006*: La primer imágen ISO de instalación y CD "live" está lista para su uso: http://people.freebsd.org/~jb/sun4v/7.0-20061112-SNAP-sun4v-disc1.iso.bz2[7.0-20061112-SNAP-sun4v-disc1.iso.bz2].
+
Verá errores de "timeout" de acd0 durante el arranque. Estos errores se corregirán en versiones posteriores. De momento tendrá que tener paciencia.
+
Si quiere usar el CD "live" seleccione "Fixit" en el menú. Tenga en cuenta que al ser una instantánea recibirá un aviso de que la etiqueta no coincide con 7.0-CURRENT.

[[hw]]
== Lista de hardware

A continuación verá una lista de sistemas soportados. SMP funciona en todos los sistemas soportados.

* http://www.sun.com/servers/coolthreads/t1000/[Servidor Sun Fire T1000]
* http://www.sun.com/servers/coolthreads/t2000/[Servidor T2000]

[[todo]]
== Tareas pendientes

* Las interrupciones del balanceo de carga entre procesadores
* Soporte para puerto serie
* Hay que implementar el reinicio del sistema y la salida a OFW (usar sc para reiniciar)

[[links]]
== Enlaces de interés

* http://www.sun.com/processors/documentation.html[Documentación del procesador UltraSPARC]
* http://www.opensparc.net/[Sitio web de OpenSPARC]
