---
title: "Proyecto FreeBSD/xbox"
sidenav: developers
---

include::shared/authors.adoc[]

= Proyecto FreeBSD/xbox

== Introducción

FreeBSD/xbox es un proyecto que pretende ejecutar FreeBSD en sistemas de Xbox(R) de Microsoft(R). {rink} comenzó este proyecto e hizo la mayoría de los parches y el trabajo de programación. mailto:ed@fxq.nl[Ed Schouten] le ayudó revisando parches y facilitando información sobre ciertas particularidades del funcionamiento interno de Xbox.

== Estado

FreeBSD/xbox está soportado en 6-STABLE y FreeBSD 7-CURRENT. Están soportados los dispositivos Ethernet, "framebuffer", sonido y USB (por ejemplo un teclado USB para la consola).

Se ha creado un disco combinado (de instalación y "live" CD para facilitar la http://lists.freebsd.org/pipermail/freebsd-stable/2006-August/027894.html[instalación] de FreeBSD/xbox. Puede encontrarlo ftp://ftp.stack.nl/pub/freebsd-xbox/[aquí].

== Arranque del kernel de FreeBSD-CURRENT

Para que arranque la versión del CVS de FreeBSD 7-CURRENT necesita una versión actualizada de la BIOS Linux/xbox, llamada Cromwell (su kernel dejará de funcionar tras arrancarlo). Hay una versión de Cromwell con UFS de FreeBSD (con el que podrá cargar un kernel directamente desde un sistemas de ficheros UFS) en el árbol de ports, más concretamente en disponible en el ports en /usr/ports/sysutils/cromwell; puede actualizar la EEPROM mediante el port raincoat (/usr/ports/sysutils/raincoat) siempre y cuando su Xbox sea de una versión anterior a la 1.6.

*Nota*: Diversos componentes de Xbox rechazan ciertos tipos de soportes. Si experimenta cuelgues, "panics" o corrupciones durante la instalación pruebe con otro DVD/CD-ROM que sepa que funcione.

== Instalación en un disco duro

Puede instalar usando el CD "live" pero tendrá que hacer todo a mano. Le recomendamos que configure su disco en una máquina FreeBSD/i386 y adapte el fichero de configuración /boot/xboxlinux.cfg a su gusto para que Cromwell pueda determinar qué kernel debe cargar.

== Enlaces

* http://www.xbox-linux.org/[Proyecto Linux Xbox]
* http://www.xbox-bsd.nl/[Proyecto FreeBSD/xbox]
