---
title: Κεφάλαιο 7. Desktop Εφαρμογές
part: Μέρος II. Βασικές Εργασίες
prev: books/handbook/partii
next: books/handbook/multimedia
---

[[desktop]]
= Desktop Εφαρμογές
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Πίνακας Περιεχομένων
:table-caption: Πίνακας
:figure-caption: Σχήμα
:example-caption: Παράδειγμα
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 7

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/el/mailing-lists.adoc[]
include::shared/el/teams.adoc[]
include::shared/el/urls.adoc[]

toc::[]

[[desktop-synopsis]]
== Σύνοψη

Το FreeBSD μπορεί να εκτελέσει μια ευρεία γκάμα desktop εφαρμογών, όπως φυλλομετρητές (browsers) και επεξεργαστές κειμένου. Οι περισσότερες από αυτές είναι διαθέσιμες ως πακέτα (packages) ή μπορούν να εγκατασταθούν αυτόματα από την Συλλογή των Ports. Πολλοί νέοι χρήστες αναμένουν να βρουν τέτοιου είδους εφαρμογές στο desktop τους. Το κεφάλαιο αυτό θα σας δείξει πως να εγκαταστήσετε χωρίς κόπο τις πιο δημοφιλείς desktop εφαρμογές, είτε από πακέτα είτε από τη Συλλογή των Ports.

Σημειώστε ότι όταν εγκαθιστάτε προγράμματα από τη Συλλογή των Ports, γίνεται μεταγλώττιση από τον πηγαίο κώδικα. Αυτό μπορεί να χρειαστεί πολύ χρόνο, καθώς εξαρτάται από το πρόγραμμα το οποίο μεταγλωττίζετε και την υπολογιστική ισχύ του μηχανήματός σας. Αν το χρονικό διάστημα το οποίο χρειάζεται η μεταγλώττιση είναι απαγορευτικά μεγάλο, μπορείτε να εγκαταστήσετε τα περισσότερα προγράμματα της Συλλογής των Ports από προ-μεταγλωττισμένα πακέτα.

Καθώς το FreeBSD διαθέτει συμβατότητα με εκτελέσιμα προγράμματα για Linux, πολλές εφαρμογές που αναπτύχθηκαν αρχικά για το Linux είναι διαθέσιμες για το desktop σας. Σας συνιστούμε θερμά να διαβάσετε το crossref:linuxemu[linuxemu,Συμβατότητα με Εκτελέσιμα του Linux] πριν εγκαταστήσετε οποιαδήποτε από τις εφαρμογές Linux. Πολλά από τα ports που χρησιμοποιούν τη συμβατότητα με Linux έχουν ονόματα που ξεκινούν με "linux-". Θυμηθείτε το όταν ψάχνετε για κάποιο συγκεκριμένο port, για παράδειγμα με την man:whereis[1]. Στο κείμενο που ακολουθεί θεωρείται ότι έχετε ενεργοποιήσει την συμβατότητα με εκτελέσιμα προγράμματα Linux πριν εγκαταστήσετε οποιαδήποτε από τις εφαρμογές του Linux.

Οι κατηγορίες που καλύπτονται από αυτό το κεφάλαιο είναι οι εξής:

* Φυλλομετρητές (όπως Firefox, Opera, KonquerorChromium)
* Εφαρμογές γραφείου (όπως KOffice, AbiWord, The GIMP, OpenOffice.org, LibreOffice)
* Προγράμματα προβολής εγγράφων (όπως Acrobat Reader(R), gv, Xpdf, GQview)
* Χρηματοοικονομικές εφαρμογές (όπως GnuCash, Gnumeric, Abacus)

Πριν διαβάσετε αυτό το κεφάλαιο θα πρέπει:

* Να ξέρετε πως να εγκαταστήσετε πρόσθετο λογισμικό τρίτου κατασκευαστή (crossref:ports[ports,Εγκατάσταση Εφαρμογών: Πακέτα και Ports]).
* Να ξέρετε πως να εγκαταστήσετε πρόσθετο λογισμικό Linux (crossref:linuxemu[linuxemu,Συμβατότητα με Εκτελέσιμα του Linux]).

Για πληροφορίες σχετικά με την εγκατάσταση πολυμεσικού περιβάλλοντος διαβάστε το crossref:multimedia[multimedia,Πολυμέσα]. Αν θέλετε να ρυθμίσετε και να χρησιμοποιήσετε κάποια υπηρεσία ηλεκτρονικού ταχυδρομείου δείτε το crossref:mail[mail,Ηλεκτρονικό Ταχυδρομείο].

[[desktop-browsers]]
== Φυλλομετρητές (Browsers)

Το FreeBSD δεν έχει προεγκατεστημένο κάποιο συγκεκριμένο φυλλομετρητή. Στον κατάλογο http://www.FreeBSD.org/ports/www.html[www] της συλλογής Ports μπορείτε να βρείτε αρκετούς φυλλομετρητές, έτοιμους για εγκατάσταση. Αν δεν έχετε χρόνο για να μεταγλωττίσετε ότι χρειάζεστε (ίσως χρειαστείτε αρκετή ώρα), πολλοί από αυτούς είναι διαθέσιμοι και ως έτοιμα πακέτα.

Τα KDE και GNOME, ως πλήρη περιβάλλοντα εργασίας, παρέχουν τους δικούς τους φυλλομετρητές HTML. Δείτε το crossref:x11[x11-wm,Γραφικά Περιβάλλοντα] για περισσότερες πληροφορίες σχετικά με την εγκατάσταση τους.

Αν ενδιαφέρεστε για ελαφρείς (από άποψη κατανάλωσης πόρων) φυλλομετρητές, δείτε τις ακόλουθες εφαρμογές στη συλλογή των Ports: package:www/dillo2[], package:www/links[], ή package:www/w3m[].

Το τμήμα αυτό καλύπτει τις παρακάτω εφαρμογές:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Όνομα Εφαρμογής
| Απαιτούμενοι Πόροι
| Εγκατάσταση από Ports
| Βασικές Εξαρτήσεις

|Firefox
|μεσαία
|βαριά
|Gtk+

|Opera
|λίγοι (ελαφριά)
|ελαφριά
|Υπάρχουν διαθέσιμες εκδόσεις για FreeBSD και Linux. Η έκδοση για Linux εξαρτάται από την δυαδική συμβατότητα με Linux (Linux Binary Compatibility) και το linux-openmotif.

|Konqueror
|μεσαία
|βαριά
|Βιβλιοθήκες KDE

|Chromium
|μεσαία
|μεσαία
|Gtk+
|===

=== Firefox

Ο Firefox είναι ένας μοντέρνος, ελεύθερος, ανοιχτός και σταθερός φυλλομετρητής, ο οποίος είναι πλήρως προσαρμοσμένος για χρήση στο FreeBSD. Διαθέτει μηχανή απεικόνισης η οποία εναρμονίζεται πλήρως με τις τυποποιήσεις της HTML, και δυνατότητες όπως εμφάνιση πολλαπλών σελίδων σε tabs, μπλοκάρισμα αναδυόμενων παραθύρων (popups), πρόσθετα προγράμματα, βελτιωμένη ασφάλεια και πολλά ακόμη. Ο Firefox βασίζεται στον αρχικό πηγαίο κώδικα του Mozilla.

Εγκαταστήστε το πακέτο γράφοντας:

[source,bash]
....
# pkg_add -r firefox
....

Η παραπάνω εντολή θα εγκαταστήσει την τελευταία σταθερή έκδοση του Firefox. Αν θέλετε να εγκαταστήσετε την παλιά έκδοση εκτεταμένης υποστήριξης (Extended Support Release, ESR), πληκτρολογήστε:

[source,bash]
....
# pkg_add -r firefox-esr
....

Μπορείτε επίσης να χρησιμοποιήσετε την Συλλογή των Ports αν προτιμάτε να μεταγλωττίσετε από τον πηγαίο κώδικα:

[source,bash]
....
# cd /usr/ports/www/firefox
# make install clean
....

Για τον Firefox ESR, αντικαταστήστε στην παραπάνω εντολή τη λέξη `firefox` με `firefox-esr`.

[[moz-java-plugin]]
=== Ο Firefox και το Πρόσθετο (plugin) της Java(TM)

[NOTE]
====
Σε αυτό το τμήμα και τα δύο επόμενα, θεωρούμε ότι έχετε ήδη εγκαταστήσει τον Firefox.
====

Εγκαταστήστε το OpenJDK 6 από τη Συλλογή των Ports, πληκτρολογώντας:

[source,bash]
....
# cd /usr/ports/java/openjdk6
# make install clean
....

Εγκαταστήστε έπειτα το port package:java/icedtea-web[]:

[source,bash]
....
# cd /usr/ports/java/icedtea-web
# make install clean
....

Βεβαιωθείτε ότι δεν αλλάξατε τις προεπιλεγμένες επιλογές στις οθόνες ρυθμίσεων και των δύο ports.

Ξεκινήστε το φυλλομετρητή σας, γράψτε `about:plugins` στη γραμμή διευθύνσεων και πιέστε kbd:[Enter]. Θα δείτε μια σελίδα με όλα τα εγκατεστημένα πρόσθετα. Στη σελίδα αυτή θα πρέπει να δείτε και την καταχώριση για το πρόσθετο της Java(TM).

Αν ο φυλλομετρητής δεν καταφέρει να εντοπίσει το πρόσθετο, κάθε χρήστης θα χρειαστεί να εκτελέσει την παρακάτω εντολή και να επανεκκινήσει το φυλλομετρητή του:

[source,bash]
....
% ln -s /usr/local/lib/IcedTeaPlugin.so \
  $HOME/.mozilla/plugins/
....

[[moz-flash-plugin]]
=== Ο Firefox και το Adobe(R) Flash(TM) Plugin

Το Adobe(R) Flash(TM) plugin δεν διατίθεται για το FreeBSD. Ωστόσο, υπάρχει ένα επίπεδο εξομοίωσης (software layer, wrapper) για την εκτέλεση του αντίστοιχου plugin του Linux. To wrapper αυτό υποστηρίζει επίσης και τα plugins για τον Adobe(R) Acrobat(R), το RealPlayer και άλλα.

Εκτελέστε τα παρακάτω βήματα, ανάλογα με την έκδοση του FreeBSD που χρησιμοποιείτε:

[.procedure]
====
. Για το FreeBSD 7._X_
+ 
Εγκαταστήστε το port package:www/nspluginwrapper[]. Το port αυτό απαιτεί το package:emulators/linux_base-fc4[] το οποίο είναι μεγάλο.
+ 
Το επόμενο βήμα είναι η εγκατάσταση του port package:www/linux-flashplugin9[]. Θα εγκατασταθεί η έκδοση Flash(TM) 9._X_ η οποία γνωρίζουμε ότι δουλεύει σωστά στο FreeBSD 7._X_.
+
[NOTE]
======
Σε εκδόσεις του FreeBSD παλαιότερες από την 7.1-RELEASE, θα πρέπει να εγκαταστήσετε το πακέτο package:www/linux-flashplugin7[] και να παραλείψετε το βήμα σχετικά με το man:linprocfs[5] που φαίνεται παρακάτω.
======
+
. Για το FreeBSD 8._X_ ή Νεώτερη Έκδοση
+ 
Εγκαταστήστε το port package:www/nspluginwrapper[]. Το port αυτό απαιτεί το package:emulators/linux_base-f10[] το οποίο είναι μεγάλο.
+ 
Το επόμενο βήμα είναι η εγκατάσταση του Flash(TM) 11.X από το port package:www/linux-f10-flashplugin11[].
+ 
Για να λειτουργήσει σωστά αυτή η έκδοση, θα χρειαστεί να δημιουργήσετε τον συμβολικό σύνδεσμο που φαίνεται παρακάτω:
+
[source,bash]
....
# ln -s /usr/local/lib/npapi/linux-f10-flashplugin/libflashplayer.so \
  /usr/local/lib/browser_plugins/
....
+ 
Θα χρειαστεί να δημιουργήσετε χειροκίνητα τον κατάλογο [.filename]#/usr/local/lib/browser_plugins# αν δεν υπάρχει στο σύστημα σας.
====

Μετά την εγκατάσταση του σωστού (σύμφωνα με την έκδοση του FreeBSD) Flash(TM) port, ο κάθε χρήστης θα πρέπει να ολοκληρώσει την προσωπική του εγκατάσταση του plugin εκτελώντας την παρακάτω εντολή του `nspluginwrapper`:

[source,bash]
....
% nspluginwrapper -v -a -i
....

Μετά την εγκατάσταση του plugin, ξεκινήστε το φυλλομετρητή σας, γράψτε `about:plugins` στη γραμμή διευθύνσεων και πιέστε kbd:[Enter]. Θα πρέπει να δείτε μια λίστα με όλα τα τρέχοντα διαθέσιμα plugins.

[[moz-swfdec-flash-plugin]]
=== Ο Firefox και το Swfdec Flash(TM) Plugin

To Swfdec είναι μια βιβλιοθήκη για αποκωδικοποίηση και αναπαραγωγή σκηνών Flash(TM). Το Swfdec-Mozilla είναι ένα plugin για τους φυλλομετρητές Firefox το οποίο χρησιμοποιεί αυτή τη βιβλιοθήκη για την αναπαραγωγή αρχείων SWF. Είναι ακόμα στο στάδιο της ανάπτυξης.

Αν δεν μπορείτε ή δεν θέλετε να το μεταγλωττίσετε, απλώς εγκαταστήστε το πακέτο από το δίκτυο:

[source,bash]
....
# pkg_add -r swfdec-plugin
....

Αν το πακέτο δεν είναι διαθέσιμο, μπορείτε να το μεταγλωττίσετε και να το εγκαταστήσετε από τη Συλλογή των Ports:

[source,bash]
....
# cd /usr/ports/www/swfdec-plugin
# make install clean
....

Μετά την εγκατάσταση, επανεκκινήστε το φυλλομετρητή σας για να ενεργοποιηθεί το plugin.

=== Opera

Ο Opera είναι ένας φυλλομετρητής με πλήρεις δυνατότητες και συμβατός με τα πρότυπα. Έρχεται επίσης με ενσωματωμένο πρόγραμμα ανάγνωσης ταχυδρομείου (mail) και ειδήσεων (news), πρόγραμμα για IRC, αναγνώστη για RSS/Atom και πολλά ακόμα. Παρ'όλα αυτά, ο Opera είναι μια σχετικά ελαφριά και πολύ γρήγορη εφαρμογή. Έρχεται σε δύο τύπους: μια "εγγενής" έκδοση για το FreeBSD και μια έκδοση που εκτελείται μέσω της συμβατότητας με το Linux.

Για να χρησιμοποιήσετε την FreeBSD έκδοση του Opera, εγκαταστήστε το πακέτο:

[source,bash]
....
# pkg_add -r opera
....

Ορισμένες τοποθεσίες FTP δεν διαθέτουν όλα τα πακέτα, αλλά μπορείτε να έχετε το ίδιο αποτέλεσμα μέσω της συλλογής των Ports, γράφοντας:

[source,bash]
....
# cd /usr/ports/www/opera
# make install clean
....

Για να εγκαταστήσετε την Linux έκδοση του Opera, αντικαταστήστε με `linux-opera` το `opera` στα παραπάνω παραδείγματα.

Το πρόσθετο Adobe(R) Flash(TM) δεν είναι διαθέσιμο για το FreeBSD. Διατίθεται ωστόσο μια έκδοση κατάλληλη για το Linux(R). Για να την χρησιμοποιήσετε θα πρέπει αρχικά να εγκαταστήσετε το port package:www/linux-f10-flashplugin11[] και έπειτα το port package:www/opera-linuxplugins[]:

[source,bash]
....
# cd /usr/ports/www/linux-f11-flashplugin10
# make install clean
# cd /usr/ports/www/opera-linuxplugins
# make install clean
....

Μπορείτε να ελέγξετε εύκολα την ύπαρξη του plugin: ξεκινήστε τον φυλλομετρητή σας, γράψτε `opera:plugins` στη γραμμή διευθύνσεων και πιέστε kbd:[Enter]. Θα πρέπει να δείτε μια λίστα με όλα τα διαθέσιμα πρόσθετα.

Για να προσθέσετε το πρόσθετο της Java(TM), ακολουθήστε τις <<moz-java-plugin, αντίστοιχες οδηγίες για τον Firefox>>.

=== Konqueror

Ο Konqueror είναι κομμάτι του KDE αλλά μπορεί να χρησιμοποιηθεί και έξω από το KDE με την εγκατάσταση του package:x11/kdebase3[]. Ο Konqueror είναι πολύ περισσότερο από ένας απλός φυλλομετρητής, είναι επίσης διαχειριστής αρχείων και πρόγραμμα προβολής αρχείων πολυμέσων.

Ο Konqueror διατίθεται επίσης με ένα σετ από plugins, στο package:misc/konq-plugins[].

Ο Konqueror υποστηρίζει τόσο το WebKit όσο και το δικό του KHTML. Το WebKit χρησιμοποιείται από πολλούς σύγχρονους φυλλομετρητές, συμπεριλαμβανομένου και του Chromium. Για να χρησιμοποιήσετε το WebKit με τον Konqueror στο FreeBSD:

[source,bash]
....
# cd /usr/ports/www/kwebkitpart
# make install clean
....

Μετά την εγκατάσταση, στον Konqueror κάντε κλικ στο "Settings", "Configure Konqueror" και τέλος στο "Change KHTML to WebKit".

Ο Konqueror υποστηρίζει επίσης Flash(TM) και οι σχετικές οδηγίες (How To) είναι διαθέσιμες στο http://freebsd.kde.org/howtos/konqueror-flash.php[http://freebsd.kde.org/howtos/konqueror-flash.php].

=== Chromium

Ο Chromium είναι μια εφαρμογή browser ανοικτού κώδικα που στοχεύει στη βελτίωση της εμπειρίας του χρήστη παρέχοντας ένα φυλλομετρητή ο οποίος είναι ασφαλέστερος, ταχύτερος και πιο σταθερός. Ο Chromium παρέχει δυνατότητα εμφάνισης σελίδων σε καρτέλες, αποκλεισμό αναδυόμενων παραθύρων (popup blocker), πρόσθετα (extensions) και πολλά ακόμα. Ο Chromium είναι το Έργο ανοικτού κώδικα στο οποίο βασίζεται ο φυλλομετρητής Google Chrome.

Ο Chromium μπορεί να εγκατασταθεί από πακέτο, με την εντολή:

[source,bash]
....
# pkg_add -r chromium
....

Εναλλακτικά, μπορείτε να μεταγλωττίσετε τον Chromium χρησιμοποιώντας τη Συλλογή των Ports:

[source,bash]
....
# cd /usr/ports/www/chromium
# make install clean
....

[NOTE]
====
Ο Chromium εγκαθιστάται ως [.filename]#/usr/local/bin/chrome# και όχι ως [.filename]#/usr/local/bin/chromium#.
====

[[chromium-java-plugin]]
=== Ο Chromium και το Πρόσθετο της Java(TM)

[NOTE]
====
Στην ενότητα αυτή θεωρούμε ότι έχετε ήδη εγκαταστήσει τον Chromium.
====

Εγκαταστήστε το OpenJDK 6 μέσω της Συλλογής των Ports, γράφοντας:

[source,bash]
....
# cd /usr/ports/java/openjdk6
# make install clean
....

Έπειτα, εγκαταστήστε το package:java/icedtea-web[] από τη Συλλογή των Ports:

[source,bash]
....
# cd /usr/ports/java/icedtea-web
# make install clean
....

Ξεκινήστε τον Chromium και πληκτρολογήστε `about:plugins` στη γραμμή διευθύνσεων. Θα πρέπει να δείτε το IcedTea-Web να εμφανίζεται ως ένα από τα πρόσθετα.

Αν το πρόσθετο δεν εμφανίζεται στον Chromium, εκτελέστε τις παρακάτω εντολές και επανεκκινήστε το φυλλομετρητή σας:

[source,bash]
....
# mkdir -p /usr/local/shared/chromium/plugins
#  ln -s /usr/local/lib/IcedTeaPlugin.so \
  /usr/local/shared/chromium/plugins/
....

[[chromium-flash-plugin]]
=== Ο Chromium και το Πρόσθετο Adobe(R) Flash(TM)

[NOTE]
====
Στην ενότητα αυτή θεωρούμε ότι έχετε ήδη εγκαταστήσει τον Chromium.
====

Για τη ρύθμιση του Chromium για χρήση με το πρόσθετο Adobe(R) Flash(TM), χρησιμοποιήστε τις <<moz-flash-plugin,οδηγίες για τον Firefox>>. Στον προηγούμενο σύνδεσμο θα βρείτε πλήρεις οδηγίες για την εγκατάσταση του Adobe(R) Flash(TM) στο FreeBSD. Δεν απαιτούνται επιπλέον βήματα, καθώς ο Chromium μπορεί να χρησιμοποιήσει κάποια πρόσθετα από άλλους φυλλομετρητές.

[[desktop-productivity]]
== Εφαρμογές Γραφείου

Όσο αφορά τις εφαρμογές γραφείου, οι νέοι χρήστες συχνά αναζητούν μια καλή σουίτα εφαρμογών ή ένα φιλικό επεξεργαστή κειμένου. Αν και κάποια crossref:x11[x11-wm,γραφικά περιβάλλοντα] όπως το KDE παρέχουν τη δική τους σουίτα εφαρμογών γραφείου, δεν υπάρχει ωστόσο προεπιλεγμένη εφαρμογή. Το FreeBSD παρέχει ότι χρειάζεστε, άσχετα από το περιβάλλον εργασίας σας.

Το τμήμα αυτό καλύπτει τις παρακάτω εφαρμογές:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Όνομα Εφαρμογής
| Απαιτούμενοι Πόροι
| Εγκατάσταση από Ports
| Βασικές Εξαρτήσεις

|KOffice
|λίγοι (ελαφριά)
|βαριά
|KDE

|AbiWord
|λίγοι (ελαφριά)
|ελαφριά
|Gtk+ ή GNOME

|The Gimp
|λίγοι (ελαφριά)
|βαριά
|Gtk+

|OpenOffice.org
|πολλοί (βαριά)
|εξαιρετικά βαριά
|JDK(TM), Mozilla

|LibreOffice
|σχετικά βαριά
|τεράστια
|Gtk+ ή KDE/ GNOME ή JDK(TM)
|===

=== KOffice

Η κοινότητα του KDE εξοπλίζει το γραφικό της περιβάλλον με μια σουίτα εφαρμογών γραφείου που μπορεί να χρησιμοποιηθεί και έξω από το KDE. Περιλαμβάνει τα τέσσερα βασικά προγράμματα που μπορείτε επίσης να βρείτε και σε άλλες σουίτες γραφείου. Το KWord είναι ο επεξεργαστής κειμένου, το KSpread είναι το πρόγραμμα υπολογιστικών φύλλων, το KPresenter διαχειρίζεται τις παρουσιάσεις, ενώ το Kontour σας επιτρέπει να δημιουργήσετε έγγραφα με γραφικά.

Πριν εγκαταστήσετε το τελευταίο KOffice, βεβαιωθείτε ότι έχετε ανανεωμένη έκδοση του KDE.

Για να εγκαταστήσετε το KOffice για το KDE4 ως πακέτο, δώστε την ακόλουθη εντολή:

[source,bash]
....
# pkg_add -r koffice-kde4
....

Αν το πακέτο δεν είναι διαθέσιμο, μπορείτε να χρησιμοποιήσετε την Συλλογή των Ports. Για παράδειγμα, για να εγκαταστήσετε το KOffice για το KDE4, πληκτρολογήστε:

[source,bash]
....
# cd /usr/ports/editors/koffice-kde4
# make install clean
....

=== AbiWord

Το AbiWord είναι ένα ελεύθερο πρόγραμμα επεξεργασίας κειμένου, όμοιο στην αίσθηση και την εμφάνιση με το Microsoft(R) Word. Είναι κατάλληλο για την πληκτρολόγηση άρθρων, γραμμάτων, αναφορών, υπενθυμίσεων κ.ο.κ. Είναι πολύ γρήγορο, έχει αρκετές δυνατότητες και είναι ιδιαίτερα φιλικό στο χρήστη.

Το AbiWord μπορεί να εισάγει ή να εξάγει αρχεία διάφορων μορφών, περιλαμβανομένων και κάποιων κλειστών όπως το [.filename]#.doc# της Microsoft(R).

Το AbiWord είναι διαθέσιμο ως πακέτο. Μπορείτε να το εγκαταστήσετε γράφοντας:

[source,bash]
....
# pkg_add -r abiword
....

Αν το πακέτο δεν είναι διαθέσιμο για κάποιο λόγο, μπορείτε να το μεταγλωττίσετε από την Συλλογή των Ports. Σε αυτή την περίπτωση πιθανώς να εγκαταστήσετε νεώτερη έκδοση σε σχέση με το έτοιμο πακέτο. Μπορείτε να το κάνετε ως εξής:

[source,bash]
....
# cd /usr/ports/editors/abiword
# make install clean
....

=== Το GIMP

Το The GIMP είναι ένα ιδιαίτερα εξελιγμένο πρόγραμμα διαχείρισης γραφικών για δημιουργία εικόνων ή επεξεργασία φωτογραφιών. Μπορεί να χρησιμοποιηθεί ως απλό πρόγραμμα ζωγραφικής ή σαν σουίτα επεξεργασίας και διόρθωσης φωτογραφιών. Περιέχει μεγάλο αριθμό από plugins ενώ διαθέτει και scripting interface. Το The GIMP μπορεί να διαβάσει και να γράψει μεγάλο φάσμα αρχείων εικόνας. Περιλαμβάνει επίσης διεπαφές διασύνδεσης με σαρωτές και tablets.

Μπορείτε να εγκαταστήσετε το πακέτο δίνοντας την εντολή:

[source,bash]
....
# pkg_add -r gimp
....

Αν η τοποθεσία FTP που χρησιμοποιείτε δεν διαθέτει αυτό το πακέτο, μπορείτε να χρησιμοποιήσετε την Συλλογή των Ports. Ο κατάλογος http://www.FreeBSD.org/ports/[graphics] της Συλλογής των Ports περιέχει επίσης και το The Gimp Manual (εγχειρίδιο χρήσης). Δείτε παρακάτω πως να το εγκαταστήσετε:

[source,bash]
....
# cd /usr/ports/graphics/gimp
# make install clean
# cd /usr/ports/graphics/gimp-manual-pdf
# make install clean
....

[NOTE]
====
Ο κατάλογος http://www.FreeBSD.org/ports/[graphics] της συλλογής των Ports έχει επίσης την υπό εξέλιξη έκδοση της εφαρμογής The GIMP στο package:graphics/gimp-devel[]. Μπορείτε να βρείτε την HTML έκδοση του εγχειριδίου, The Gimp Manual στο package:graphics/gimp-manual-html[].
====

=== OpenOffice.org

Το OpenOffice.org περιέχει όλες τις απαραίτητες εφαρμογές σε μια πλήρη σουίτα εφαρμογών γραφείου: επεξεργαστή κειμένου, υπολογιστικό φύλλο, διαχειριστή παρουσιάσεων και πρόγραμμα σχεδίασης. Το περιβάλλον εργασίας του είναι πολύ όμοιο με άλλες σουίτες γραφείου, και μπορεί να χρησιμοποιήσει διάφορους δημοφιλείς τύπους αρχείων. Είναι διαθέσιμο σε πολλές διαφορετικές γλώσσες, τόσο ως προς το περιβάλλον εργασίας όσο και ως προς τα λεξικά και τον ορθογραφικό έλεγχο.

Ο επεξεργαστής κειμένου του OpenOffice.org χρησιμοποιεί εγγενώς μορφή αρχείου XML για αυξημένη φορητότητα και ευελιξία. Το πρόγραμμα υπολογιστικών φύλλων διαθέτει γλώσσα μακροεντολών και μπορεί να διασυνδεθεί με εξωτερικές βάσεις δεδομένων. Το OpenOffice.org είναι σταθερή εφαρμογή και εκτελείται εγγενώς στα Windows(R), το Solaris(TM), το Linux, το FreeBSD, καθώς και στο Mac OS(R) X. Περισσότερες πληροφορίες για το OpenOffice.org μπορείτε να βρείτε στη http://www.openoffice.org/[δικτυακή τοποθεσία του OpenOffice.org]. Για πληροφορίες σχετικά με την έκδοση για FreeBSD, καθώς και για απευθείας κατέβασμα πακέτων, χρησιμοποιήστε την δικτυακή τοποθεσία http://porting.openoffice.org/freebsd/[FreeBSD OpenOffice.org Porting Team].

Για να εγκαταστήσετε το OpenOffice.org, γράψτε:

[source,bash]
....
# pkg_add -r openoffice.org
....

[NOTE]
====
Αν χρησιμοποιείτε -RELEASE έκδοση του FreeBSD, το παραπάνω πρέπει να δουλέψει. Διαφορετικά, θα πρέπει να δείτε την δικτυακή τοποθεσία του FreeBSD OpenOffice.org Porting Team για να κατεβάσετε και να εγκαταστήσετε το αντίστοιχο πακέτο χρησιμοποιώντας την man:pkg_add[1]. Τόσο η τρέχουσα όσο και η υπό εξέλιξη έκδοση είναι διαθέσιμες για κατέβασμα από την παραπάνω τοποθεσία.
====

Από τη στιγμή που το πακέτο εγκατασταθεί, πρέπει να γράψετε απλώς την παρακάτω εντολή για να εκτελέσετε το OpenOffice.org:

[source,bash]
....
% openoffice.org
....

[NOTE]
====
Κατά την πρώτη εκκίνηση, θα σας γίνουν διάφορες ερωτήσεις και θα δημιουργηθεί ένας κατάλογος με όνομα [.filename]#.openoffice.org# μέσα στον προσωπικό σας κατάλογο.
====

Αν τα πακέτα του OpenOffice.org δεν είναι διαθέσιμα, έχετε πάντα την επιλογή να μεταγλωττίσετε το αντίστοιχο port. Ωστόσο, να έχετε υπόψη σας ότι αυτό απαιτεί αρκετό χώρο στο δίσκο και θα χρειαστεί και πάρα πολύ χρόνο για να ολοκληρωθεί.

[source,bash]
....
# cd /usr/ports/editors/openoffice.org-3
# make install clean
....

[NOTE]
====
Αν θέλετε να δημιουργήσετε μια έκδοση με τις δικές σας τοπικές ρυθμίσεις, αντικαταστήστε την προηγούμενη γραμμή εντολών με την επόμενη:

[source,bash]
....
# make LOCALIZED_LANG=your_language install clean
....

Πρέπει να αντικαταστήσετε το _your_language_ με το σωστό ISO κωδικό για τη γλώσσα σας. Η λίστα με τους υποστηριζόμενους κωδικούς γλωσσών είναι διαθέσιμη στο αρχείο [.filename]#files/Makefile.localized#, το οποίο βρίσκεται στον κατάλογο του port.
====

Μόλις γίνει αυτό, μπορείτε να ξεκινήσετε την εφαρμογή OpenOffice.org δίνοντας την εντολή:

[source,bash]
....
% openoffice.org
....

=== LibreOffice

Το LibreOffice είναι μια ελεύθερη σουίτα εφαρμογών γραφείου η οποία αναπτύσσεται από το http://www.documentfoundation.org/[The Document Foundation]. Είναι συμβατή με τις άλλες γνωστές σουίτες γραφείου και διατίθεται για τις περισσότερες πλατφόρμες. Πρόκειται για fork της γνωστής εφαρμογής OpenOffice.org η οποία περιλαμβάνει όλα τα απαραίτητα μιας σουίτας γραφείου: επεξεργαστή κειμένου, υπολογιστικό φύλλο, πρόγραμμα παρουσιάσεων, πρόγραμμα σχεδίασης και ένα εργαλείο για δημιουργία και επεξεργασία μαθηματικών τύπων. Διατίθεται σε πλήθος γλωσσών - η διεθνής υποστήριξη επεκτείνεται μάλιστα τόσο στο περιβάλλον όσο και στα επιπλέον προγράμματα ελέγχου ορθογραφίας και λεξικών.

Ο επεξεργαστής κειμένου του OpenOffice χρησιμοποιεί εγγενώς μορφή αρχείου XML το οποίο εξασφαλίζει αυξημένη φορητότητα και ευελιξία. Το υπολογιστικό φύλλο διαθέτει μια γλώσσα μακροεντολών και μπορεί να διασυνδεθεί με εξωτερικές βάσεις δεδομένων. Το LibreOffice είναι ήδη σταθερό και διατίθεται σε εκδόσεις για Windows(R), Linux(R), FreeBSD και Mac OS(R) X. Για περισσότερες πληροφορίες σχετικά με το LibreOffice επισκεφθείτε την http://www.libreoffice.org/[δικτυακή τοποθεσία του].

Για να εγκαταστήσετε το LibreOffice από έτοιμο πακετό, γράψτε:

[source,bash]
....
# pkg_add -r libreoffice
....

[NOTE]
====
Το παραπάνω θα λειτουργήσει αν τρέχετε κάποιο επίσημο -RELEASE του FreeBSD.
====

Μετά την εγκατάσταση του πακέτου, πληκτρολογήστε το παρακάτω για να εκτελέσετε το LibreOffice:

[source,bash]
....
% libreoffice
....

[NOTE]
====
Κατά την πρώτη εκκίνηση, θα σας γίνουν κάποιες ερωτήσεις και θα δημιουργηθεί ένας κατάλογος [.filename]#.libreoffice# μέσα στον προσωπικό σας κατάλογο.
====

Αν δεν υπάρχουν διαθέσιμα πακέτα για το LibreOffice, έχετε επίσης την επιλογή να το μεταγλωττίσετε από το αντίστοιχο port. Θα πρέπει ωστόσο να γνωρίζετε ότι απαιτείται αρκετός χώρος στο δίσκο και αρκετός χρόνος για τη μεταγλώττιση.

[source,bash]
....
# cd /usr/ports/editors/libreoffice
# make install clean
....

[NOTE]
====
Αν θέλετε να δημιουργήσετε μια έκδοση με υποστήριξη κάποιας συγκεκριμένης γλώσσας, αντικαταστήστε την προηγούμενη εντολή με:

[source,bash]
....
# make LOCALIZED_LANG=your_language install clean
....

Θα πρέπει να αντικαταστήσετε το _your_language_ με το σωστό ISO κωδικό της γλώσσας που επιθυμείτε να χρησιμοποιήσετε. Για να βρείτε τον κωδικό, δείτε το αρχείο [.filename]#Makefile# του port και ειδικότερα την ενότητα `pre-fetch`.
====

Μπορείτε έπειτα να εκτελέσετε το LibreOffice χρησιμοποιώντας την παρακάτω εντολή:

[source,bash]
....
% libreoffice
....

[[desktop-viewers]]
== Προγράμματα Προβολής Εγγράφων

Πρόσφατα έχουν γίνει αρκετά δημοφιλείς κάποιες νέες μορφές αρχείων. Τα προγράμματα προβολής που απαιτούνται για τα αρχεία αυτά ίσως να μην είναι διαθέσιμα στο βασικό σύστημα. Στο τμήμα αυτό θα δούμε πως μπορείτε να τα εγκαταστήσετε.

Το τμήμα αυτό καλύπτει τις εφαρμογές:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Όνομα Εφαρμογής
| Απαιτούμενοι Πόροι
| Εγκατάσταση από Ports
| Βασικές Εξαρτήσεις

|Acrobat Reader(R)
|λίγοι (ελαφριά)
|ελαφριά
|Δυαδική συμβατότητα με Linux (Linux Binary Compatibility)

|gv
|λίγοι (ελαφριά)
|ελαφριά
|Xaw3d

|Xpdf
|λίγοι (ελαφριά)
|ελαφριά
|FreeType

|GQview
|λίγοι (ελαφριά)
|ελαφριά
|Gtk+ ή GNOME
|===

=== Acrobat Reader(R)

Πολλά έγγραφα διανέμονται πλέον ως αρχεία PDF το οποίο σημαίνει "Portable Document Format" (Φορητή Μορφή Εγγράφου). Ένα από τα συνιστώμενα προγράμματα προβολής για αυτό τον τύπο αρχείων είναι το Acrobat Reader(R), το οποίο η Adobe διαθέτει για Linux. Καθώς το FreeBSD μπορεί να χρησιμοποιήσει εκτελέσιμα του Linux, η εφαρμογή είναι επίσης διαθέσιμη για το FreeBSD.

Για να εγκαταστήσετε το Acrobat Reader(R) 8 από τη Συλλογή των Ports, γράψτε:

[source,bash]
....
# cd /usr/ports/print/acroread8
# make install clean
....

Δεν υπάρχει διαθέσιμο πακέτο, λόγω περιορισμών στην άδεια χρήσης.

=== gv

Το gv είναι ένα πρόγραμμα προβολής εγγράφων για αρχεία PostScript(R) και PDF. Είναι αρχικά βασισμένο στην εφαρμογή ghostview αλλά έχει καλύτερη εμφάνιση χάρη στη βιβλιοθήκη Xaw3d. Είναι γρήγορο, και το interface του είναι ξεκάθαρο. Το gv έχει πολλές δυνατότητες, όπως προσανατολισμό και μέγεθος χαρτιού, εμφάνιση υπό κλίμακα και βελτίωση εμφάνισης γραμματοσειρών (antialias). Σχεδόν κάθε λειτουργία του μπορεί να εκτελεστεί τόσο από το πληκτρολόγιο όσο και από το ποντίκι.

Για να εγκαταστήσετε το gv ως πακέτο, γράψτε:

[source,bash]
....
# pkg_add -r gv
....

Αν το πακέτο δεν είναι διαθέσιμο, μπορείτε να χρησιμοποιήσετε την Συλλογή των Ports:

[source,bash]
....
# cd /usr/ports/print/gv
# make install clean
....

=== Xpdf

Αν θέλετε ένα μικρό πρόγραμμα προβολής αρχείων PDF για το FreeBSD, το Xpdf είναι ελαφρύ και αποδοτικό. Απαιτεί ελάχιστους πόρους και είναι ιδιαίτερα σταθερό. Χρησιμοποιεί τις βασικές γραμματοσειρές των X και δεν απαιτεί χρήση του Motif(R) ή άλλης εργαλειοθήκης των Χ.

Για να εγκαταστήσετε το Xpdf ως πακέτο, δώστε την εντολή:

[source,bash]
....
# pkg_add -r xpdf
....

Αν το πακέτο δεν είναι διαθέσιμο ή προτιμάτε να χρησιμοποιήσετε την Συλλογή των Ports, γράψτε:

[source,bash]
....
# cd /usr/ports/graphics/xpdf
# make install clean
....

Μόλις ολοκληρωθεί η εγκατάσταση, μπορείτε να ξεκινήσετε το Xpdf και να χρησιμοποιήσετε το δεξί πλήκτρο του ποντικιού για να ενεργοποιήσετε το μενού.

=== GQview

Το GQview είναι ένας διαχειριστής εικόνων. Μπορείτε να δείτε ένα αρχείο με ένα απλό κλικ, να ξεκινήσετε ένα εξωτερικό πρόγραμμα επεξεργασίας, να δείτε προεπισκόπηση σε μορφή thumbnail και πολλά άλλα. Διαθέτει επίσης προβολή παρουσίασης και κάποιες βασικές λειτουργίες αρχείων. Μπορείτε να διαχειριστείτε συλλογές εικόνων και να βρείτε με εύκολο τρόπο τις διπλές. Το GQview μπορεί να χρησιμοποιηθεί για προβολή σε πλήρη οθόνη και υποστηρίζει τοπικές / διεθνείς ρυθμίσεις.

Αν θέλετε να εγκαταστήσετε το GQview ως πακέτο, γράψτε:

[source,bash]
....
# pkg_add -r gqview
....

Αν το πακέτο δεν είναι διαθέσιμο, ή προτιμάτε να χρησιμοποιήσετε την Συλλογή των Ports, γράψτε:

[source,bash]
....
# cd /usr/ports/graphics/gqview
# make install clean
....

[[desktop-finance]]
== Χρηματοοικονομικές Εφαρμογές

Αν, για οποιοδήποτε λόγο, θέλετε να διαχειρίζεστε τα χρηματοοικονομικά σας μέσω του FreeBSD desktop σας, υπάρχουν κάποιες ισχυρές και εύκολες στη χρήση εφαρμογές, έτοιμες προς εγκατάσταση. Ορισμένες από αυτές είναι συμβατές με διαδεδομένες μορφές αρχείων, όπως αυτές που χρησιμοποιούνται στα έγγραφα του Quicken ή του Excel.

Το τμήμα αυτό καλύπτει τις εφαρμογές:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Όνομα Εφαρμογής
| Απαιτούμενοι Πόροι
| Εγκατάσταση Από Ports
| Βασικές Εξαρτήσεις

|GnuCash
|λίγοι (ελαφριά)
|βαριά
|GNOME

|Gnumeric
|λίγοι (ελαφριά)
|βαριά
|GNOME

|Abacus
|λίγοι (ελαφριά)
|ελαφριά
|Tcl/Tk

|KMyMoney
|λίγοι (ελαφριά)
|βαριά
|KDE
|===

=== GnuCash

Το GnuCash είναι μέρος της προσπάθειας του GNOME να παρέχει φιλικές εφαρμογές στους τελικούς χρήστες. Με το GnuCash, μπορείτε να κρατάτε λογαριασμό των εσόδων και εξόδων σας, των τραπεζικών σας λογαριασμών και των μετοχών σας. Διαθέτει περιβάλλον εργασίας το οποίο είναι εύκολο στη χρήση χωρίς να χρειάζεται ιδιαίτερη εκμάθηση, αλλά είναι ταυτόχρονα και πολύ επαγγελματικό.

Το GnuCash παρέχει έξυπνο σύστημα καταχώρησης, ιεραρχικό σύστημα λογαριασμών, πολλά πλήκτρα συντομεύσεων πληκτρολογίου, καθώς και μεθόδους αυτόματης συμπλήρωσης. Μπορεί να διαχωρίσει μια συναλλαγή σε πολλά λεπτομερή τμήματα. Το GnuCash μπορεί να εισάγει και να συγχωνεύσει αρχεία QIF του Quicken. Μπορεί επίσης να χειριστεί τις περισσότερες διεθνείς μορφές ημερομηνιών και νομισματικών μονάδων.

Για να εγκαταστήσετε το GnuCash στο σύστημα σας, γράψτε:

[source,bash]
....
# pkg_add -r gnucash
....

Αν το πακέτο δεν είναι διαθέσιμο, μπορείτε να χρησιμοποιήσετε την Συλλογή των Ports:

[source,bash]
....
# cd /usr/ports/finance/gnucash
# make install clean
....

=== Gnumeric

Το Gnumeric είναι ένα υπολογιστικό φύλλο και αποτελεί μέρος του περιβάλλοντος εργασίας GNOME. Διαθέτει βολική αυτόματη "πρόβλεψη" της εισόδου του χρήστη σύμφωνα με τη μορφή του κελιού καθώς και σύστημα αυτόματης συμπλήρωσης (autofill) για διάφορες ακολουθίες. Μπορεί να εισάγει αρχεία διάφορων δημοφιλών μορφών, όπως αυτά που χρησιμοποιούνται στο Excel, το Lotus 1-2-3, ή το Quattro Pro. Το Gnumeric υποστηρίζει γραφήματα μέσω του προγράμματος γραφικών package:math/guppi[]. Έχει μεγάλο αριθμό ενσωματωμένων συναρτήσεων και επιτρέπει όλες τις συνήθεις μορφές κελιών, όπως αριθμούς, νομισματικές μονάδες, ημερομηνίες, ώρες και πολλές ακόμα.

Για να εγκαταστήσετε το Gnumeric ως πακέτο, γράψτε:

[source,bash]
....
# pkg_add -r gnumeric
....

Αν το πακέτο δεν είναι διαθέσιμο, μπορείτε να χρησιμοποιήσετε την Συλλογή των Ports, γράφοντας:

[source,bash]
....
# cd /usr/ports/math/gnumeric
# make install clean
....

=== Abacus

Το Abacus είναι ένα μικρό και εύκολο στη χρήση υπολογιστικό φύλλο. Περιλαμβάνει πολλές ενσωματωμένες συναρτήσεις οι οποίες είναι χρήσιμες σε διάφορα πεδία, όπως η στατιστική, τα χρηματοοικονομικά και τα μαθηματικά. Μπορεί να εισάγει και να εξάγει αρχεία του Excel. Το Abacus μπορεί να παράγει έξοδο μορφής PostScript(R).

Για να εγκαταστήσετε το Abacus ως πακέτο, γράψτε:

[source,bash]
....
# pkg_add -r abacus
....

Αν το πακέτο δεν είναι διαθέσιμο, μπορείτε να χρησιμοποιήσετε την Συλλογή των Ports, γράφοντας:

[source,bash]
....
# cd /usr/ports/deskutils/abacus
# make install clean
....

=== KMyMoney

Το KMyMoney είναι μια εφαρμογή διαχείρισης των προσωπικών σας οικονομικών, φτιαγμένη για το περιβάλλον KDE. To KMyMoney στοχεύει να παρέχει και να ενσωματώσει όλες τις λειτουργίες που διατίθενται σε αντίστοιχες εμπορικές εφαρμογές. Το KMyMoney μπορεί να εισάγει αρχεία του προτύπου QIF (Quicken Interchange Format), να τηρεί καταγραφή των επενδύσεων σας, να χειρίζεται πολλαπλές νομισματικές μονάδες και να παρέχει πλήθος αναφορών. Μέσα από ξεχωριστό plugin, παρέχεται επίσης η δυνατότητα εισαγωγής αρχείων OFX.

Για να εγκαταστήσετε το KMyMoney ως πακέτο, εκτελέστε την εντολή:

[source,bash]
....
# pkg_add -r kmymoney2
....

Αν το πακέτο δεν είναι διαθέσιμο, μπορείτε να χρησιμοποιήσετε την Συλλογή των Ports, όπως φαίνεται παρακάτω:

[source,bash]
....
# cd /usr/ports/finance/kmymoney2
# make install clean
....

[[desktop-summary]]
== Περίληψη

Αν και το FreeBSD είναι δημοφιλές στους παροχείς Internet (ISPs) για την απόδοση και τη σταθερότητα του, είναι επίσης έτοιμο και για καθημερινή χρήση ως desktop. Με αρκετές χιλιάδες εφαρμογές διαθέσιμες ως http://www.FreeBSD.org/applications/[πακέτα] ή http://www.FreeBSD.org/ports/[ports], μπορείτε να δημιουργήσετε το τέλειο desktop που καλύπτει όλες τις ανάγκες σας.

Παρακάτω, φαίνεται μια γρήγορη περίληψη όλων των desktop εφαρμογών που παρουσιάστηκαν σε αυτό το κεφάλαιο:

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Όνομα Εφαρμογής
| Όνομα Πακέτου
| Όνομα Port

|Opera
|`opera`
|package:www/opera[]

|Firefox
|`firefox`
|package:www/firefox[]

|Chromium
|`chromium`
|package:www/chromium[]

|KOffice
|`koffice-kde4`
|package:editors/koffice-kde4[]

|AbiWord
|`abiword`
|package:editors/abiword[]

|The GIMP
|`gimp`
|package:graphics/gimp[]

|OpenOffice.org
|`openoffice`
|package:editors/openoffice.org-3[]

|LibreOffice
|`libreoffice`
|package:editors/libreoffice[]

|Acrobat Reader(R)
|`acroread`
|package:print/acroread8[]

|gv
|`gv`
|package:print/gv[]

|Xpdf
|`xpdf`
|package:graphics/xpdf[]

|GQview
|`gqview`
|package:graphics/gqview[]

|GnuCash
|`gnucash`
|package:finance/gnucash[]

|Gnumeric
|`gnumeric`
|package:math/gnumeric[]

|Abacus
|`abacus`
|package:deskutils/abacus[]

|KMyMoney
|`kmymoney2`
|package:finance/kmymoney2[]
|===
