.\" Copyright (c) 1983, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)bind.2	8.1 (Berkeley) 6/4/93
.\" %FreeBSD: src/lib/libc/sys/bind.2,v 1.27 2002/12/19 09:40:24 ru Exp %
.\"
.\" $FreeBSD$
.Dd June 4, 1993
.Dt BIND 2
.Os
.Sh 名称
.Nm bind
.Nd ローカルプロトコルアドレスをソケットに割り当てる
.Sh ライブラリ
.Lb libc
.Sh 書式
.In sys/types.h
.In sys/socket.h
.Ft int
.Fn bind "int s" "const struct sockaddr *addr" "socklen_t addrlen"
.Sh 解説
.Fn bind
システムコールは、ローカルプロトコルアドレスをソケットに割り当てます。
ソケットは、
.Xr socket 2
で作成される時にアドレスファミリ空間に存在しますが、
プロトコルアドレスは割り当てられていません。
.Fn bind
システムコールはソケットに
.Fa addr
を割り当てることを要求します。
.Sh 注
UNIX ドメイン内でのアドレスのバインドによってファイルシステム内に
ソケットが作成されます。
これは、必要なくなったときに呼び出し側が
.Pf ( Xr unlink 2
を使用して) 削除する必要があります。
.Pp
アドレスのバインドで使用される規則は通信ドメイン間で異なります。
詳細については、
セクション 4 のマニュアルエントリを参照してください。
.Pp
移植性を最大にするためには、ソケット構造体は、使用前
つまりこれを
.Fn bind
に渡す前に、0 で埋めるべきです。
.Sh 戻り値
.Rv -std bind
.Sh エラー
.Fn bind
システムコールは次の場合に失敗します:
.Bl -tag -width Er
.It Bq Er EAGAIN
要求を満たすためのカーネルリソースが一時的に利用できません。
.It Bq Er EBADF
.Fa s
引数が有効な記述子ではありません。
.It Bq Er ENOTSOCK
.Fa s
引数がソケットではありません。
.It Bq Er EADDRNOTAVAIL
指定のアドレスがローカルマシンから利用できません。
.It Bq Er EADDRINUSE
指定のアドレスは既に使用中です。
.It Bq Er EACCES
要求されたアドレスは保護されており、現在のユーザが持っているパーミッションは
それにアクセスするのには不適切です。
.It Bq Er EFAULT
.Fa addr
引数が有効なユーザアドレス空間ではありません。
.El
.Pp
次のエラーは UNIX ドメイン内のバインドアドレスに固有のものです。
.Bl -tag -width EADDRNOTAVA
.It Bq Er ENOTDIR
パスの構成要素中にディレクトリ以外のものが含まれています。
.It Bq Er ENAMETOOLONG
パス名の構成要素が 255 文字を越えているか、
またはパス名全体が 1023 文字を越えています。
.It Bq Er ENOENT
パス名の接頭辞構成要素が存在しません。
.It Bq Er ELOOP
パス名を変換するときに検出されたシンボリックリンクが多すぎます。
.It Bq Er EIO
ディレクトリエントリを作成している間、または inode を割り振りしている間に
入出力エラーが発生しました。
.It Bq Er EROFS
指定されたファイルは読取り専用ファイルシステム上にあります。
.It Bq Er EISDIR
空のパス名が指定されました。
.El
.Sh 関連項目
.Xr connect 2 ,
.Xr getsockname 2 ,
.Xr listen 2 ,
.Xr socket 2
.Sh 歴史
.Fn bind
システムコールは
.Bx 4.2
で登場しました。
