# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	status.sgml
DOCS+=	report-june-2001.sgml

INDEXLINK=	status.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"

