---
title: Часть II. Общие задачи
prev: books/handbook/x11
next: books/handbook/desktop
---

ifdef::env-beastie+backend-html5[]
:chapters-path: content/{{% lang %}}/books/handbook/
endif::[]

ifndef::env-beastie[]
:chapters-path:
endif::[]

[[common-tasks]]
= Общие задачи

Теперь, когда основы были пройдены, в данной части Руководства FreeBSD будут обсуждаться некоторые часто используемые возможности FreeBSD. В этих главах:

* Введение в популярные и полезные графические приложения: браузеры, бизнес приложения, программы просмотра документов и т.д.
* Представлены множество мультимедийных программ, доступных в FreeBSD.
* Описан процесс создания собственного ядра FreeBSD для включения дополнительных функций системы.
* Система печати разобрана в деталях, как для непосредственно подключенных принтеров, так и для принтеров, подключенных через сеть.
* Показано, как запускать приложения Linux в системе FreeBSD.

Перед прочтением некоторых из этих глав необходимо ознакомиться с предварительной информацией, что указано в кратком обзоре в начале каждой главы.

include::{chapters-path}toc-2.adoc[]
