# $FreeBSD: www/ja/releases/Makefile.inc,v 1.4 1999/09/07 15:15:51 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.5

WEBBASE?=	/data/ja/releases
WEB_PREFIX?=	${.CURDIR}/../../..
