# $FreeBSD: www/ja/releases/2.2.7R/Makefile,v 1.5 1999/12/23 01:16:04 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

LOCALTOP= ../..

DOCS=	announce.sgml notes.sgml errata.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
