---
title: "Le Copyright FreeBSD"
sidenav: about
---

= Le Copyright FreeBSD

Copyright 1994-2011 Le Projet FreeBSD Tous droits réservés.

La redistribution et l'utilisation sous forme binaire ou de code source, avec ou sans modification, sont autorisées à condition que les conditions suivantes soient respectées :

. Les redistributions du code source doivent conserver l'indication de copyright ci-dessus, cette liste de conditions et la renonciation suivante.
. Les redistributions sous forme binaire doivent reproduire l'indication de copyright ci-dessus, cette liste de conditions et la renonciation suivante dans la documentation et/ou les autres accessoires fournis avec la distribution.

CE LOGICIEL EST FOURNI PAR LE PROJET FREEBSD "TEL QUEL" ET TOUTES LES GARANTIES EXPLICITES OU IMPLICITES, Y COMPRIS, MAIS NON LIMITÉES A CELLES-CI, LES GARANTIES IMPLICITES DE COMMERCIALISATION ET D'ADÉQUATION À UN USAGE PARTICULIER SONT DÉNIÉES. EN AUCUN CAS LE PROJET FREEBSD OU LES PARTICIPANTS NE PEUVENT ÊTRE TENUS POUR RESPONSABLE DES DOMMAGES DIRECTS, INDIRECTS, FORTUITS, PARTICULIERS, EXEMPLAIRES OU CONSÉCUTIFS À UNE ACTION (Y COMPRIS, MAIS NON LIMITÉS À CEUX-CI, L'ACQUISITION DE MARCHANDISES OU DE SERVICES DE REMPLACEMENT; LES PERTES D'UTILISATIONS, DE DONNÉES OU FINANCIÈRES; OU L'INTERRUPTION D'ACTIVITÉS) DE QUELQUE MANIÈRE QUE CES DOMMAGES SOIENT CAUSÉS ET CECI POUR TOUTES LES THÉORIES DE RESPONSABILITÉS, QUE CE SOIT DANS UN CONTRAT, POUR DES RESPONSABILITÉS STRICTES OU DES PRÉJUDICES (Y COMPRIS DUS À UNE NEGLIGENCE OU AUTRE CHOSE) SURVENANT DE QUELQUE MANIÈRE QUE CE SOIT EN DEHORS DE L'UTILISATION DE CE LOGICIEL, MÊME EN CAS D'AVERTISSEMENT DE LA POSSIBILITÉ DE TELS DOMMAGES.

Les points de vues et les conclusions contenus dans le logiciel et dans la documentation sont ceux des auteurs et ne doivent pas être interprétés comme représentant un avis officiel, explicite ou implicite, du Projet FreeBSD.

link:..[Informations légales]
