# $FreeBSD$

DOC?= article

FORMATS?= html

IMAGES_EN = fig1.eps
IMAGES_EN+= fig2.eps
IMAGES_EN+= fig3.eps
IMAGES_EN+= fig4.eps

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
