# $FreeBSD$

DOC?= article

FORMATS?= html

IMAGES = ../../../en_US.ISO8859-1/articles/vm-design/fig1.eps
IMAGES+= ../../../en_US.ISO8859-1/articles/vm-design/fig2.eps
IMAGES+= ../../../en_US.ISO8859-1/articles/vm-design/fig3.eps
IMAGES+= ../../../en_US.ISO8859-1/articles/vm-design/fig4.eps

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"