# Summary for C99 project status
#
# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.1

MAINTAINER=	mike

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.xml
DATA=	style.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
