---
title: Chapter 26. Updating and Upgrading FreeBSD
part: Part III. System Administration
prev: books/handbook/l10n
next: books/handbook/dtrace
description: Information about how to keep a FreeBSD system up-to-date with freebsd-update or Git, how to rebuild and reinstall the entire base system, etc
tags: ["updating", "upgrading", "documentation", "FreeBSD-STABLE", "FreeBSD-CURRENT", "Security Patches"]
showBookMenu: true
weight: 30
params:
  path: "/books/handbook/cutting-edge/"
---

[[updating-upgrading]]
= Updating and Upgrading FreeBSD
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 26
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/cutting-edge/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[updating-upgrading-synopsis]]
== Synopsis

FreeBSD is under constant development between releases.
Some people prefer to use the officially released versions, while others prefer to keep in sync with the latest developments.
However, even official releases are often updated with security and other critical fixes.
Regardless of the version used, FreeBSD provides all the necessary tools to keep the system updated, and allows for easy upgrades between versions.
This chapter describes how to track the development system and the basic tools for keeping a FreeBSD system up-to-date.

Read this chapter to learn:

* How to keep a FreeBSD system up-to-date with freebsd-update or Git.
* How to compare the state of an installed system against a known pristine copy.
* How to keep the installed documentation up-to-date with Git or documentation ports.
* The difference between the two development branches: FreeBSD-STABLE and FreeBSD-CURRENT.
* How to rebuild and reinstall the entire base system.

Before reading this chapter:

* Properly set up the network connection (crossref:advanced-networking[advanced-networking,Advanced Networking]).
* Know how to install additional third-party software (crossref:ports[ports,Installing Applications: Packages and Ports]).

[NOTE]
====
Throughout this chapter, `git` is used to obtain and update FreeBSD sources.
Optionally, the package:devel/git[] port or package may be used.
====

[[updating-upgrading-freebsdupdate]]
== FreeBSD Update

Applying security patches in a timely manner and upgrading to a newer release of an operating system are important aspects of ongoing system administration.
FreeBSD includes a utility called `freebsd-update` which can be used to perform both these tasks.

This utility supports binary security and errata updates to FreeBSD, without the need to manually compile and install the patch or a new kernel.
Binary updates are available for all architectures and releases currently supported by the security team.
The list of supported releases and their estimated end-of-life dates are listed at https://www.FreeBSD.org/security/[https://www.FreeBSD.org/security/].

This utility also supports operating system upgrades to minor point releases as well as upgrades to another release branch.
Before upgrading to a new release, review its release announcement as it contains important information pertinent to the release.
Release announcements are available from https://www.FreeBSD.org/releases/[https://www.FreeBSD.org/releases/].

[NOTE]
====
If a man:crontab[5] utilizing the features of man:freebsd-update[8] exists, it must be disabled before upgrading the operating system.
====

This section describes the configuration file used by `freebsd-update`, demonstrates how to apply a security patch and how to upgrade to a minor or major operating system release, and discusses some of the considerations when upgrading the operating system.

[[freebsdupdate-config-file]]
=== The Configuration File

The default configuration file for `freebsd-update` works as-is.
Some users may wish to tweak the default configuration in [.filename]#/etc/freebsd-update.conf#, allowing better control of the process.
The comments in this file explain the available options, but the following may require a bit more explanation:

[.programlisting]
....
# Components of the base system which should be kept updated.
Components world kernel
....

This parameter controls which parts of FreeBSD will be kept up-to-date.
The default is to update the entire base system and the kernel.
Individual components can instead be specified, such as `src/base` or `src/sys`.
However, the best option is to leave this at the default as changing it to include specific items requires every needed item to be listed.
Over time, this could have disastrous consequences as source code and binaries may become out of sync.

[.programlisting]
....
# Paths which start with anything matching an entry in an IgnorePaths
# statement will be ignored.
IgnorePaths /boot/kernel/linker.hints
....

To leave specified directories, such as [.filename]#/bin# or [.filename]#/sbin#, untouched during the update process, add their paths to this statement.
This option may be used to prevent `freebsd-update` from overwriting local modifications.

[.programlisting]
....
# Paths which start with anything matching an entry in an UpdateIfUnmodified
# statement will only be updated if the contents of the file have not been
# modified by the user (unless changes are merged; see below).
UpdateIfUnmodified /etc/ /var/ /root/ /.cshrc /.profile
....

This option will only update unmodified configuration files in the specified directories.
Any changes made by the user will prevent the automatic updating of these files.
There is another option, `KeepModifiedMetadata`, which will instruct `freebsd-update` to save the changes during the merge.

[.programlisting]
....
# When upgrading to a new FreeBSD release, files which match MergeChanges
# will have any local changes merged into the version from the new release.
MergeChanges /etc/ /var/named/etc/ /boot/device.hints
....

List of directories with configuration files that `freebsd-update` should attempt to merge.
The file merge process is a series of man:diff[1] patches.
Merges are either accepted, open an editor, or cause `freebsd-update` to abort.
When in doubt, backup [.filename]#/etc# and just accept the merges.

[.programlisting]
....
# Directory in which to store downloaded updates and temporary
# files used by FreeBSD Update.
# WorkDir /var/db/freebsd-update
....

This directory is where all patches and temporary files are placed.
In cases where the user is doing a version upgrade, this location should have at least a gigabyte of disk space available.

[.programlisting]
....
# When upgrading between releases, should the list of Components be
# read strictly (StrictComponents yes) or merely as a list of components
# which *might* be installed of which FreeBSD Update should figure out
# which actually are installed and upgrade those (StrictComponents no)?
# StrictComponents no
....

When this option is set to `yes`, `freebsd-update` will assume that the `Components` list is complete and will not attempt to make changes outside of the list.
Effectively, `freebsd-update` will attempt to update every file which belongs to the `Components` list.

Refer to man:freebsd-update.conf[5] for more details.

[[freebsdupdate-security-patches]]
=== Applying Security Patches

The process of applying FreeBSD security patches has been simplified, allowing an administrator to keep a system fully patched using `freebsd-update`.
More information about FreeBSD security advisories can be found in crossref:security[security-advisories,"FreeBSD Security Advisories"].

FreeBSD security patches may be downloaded and installed using the following commands.
The first command will determine if any outstanding patches are available, and if so, will list the files that will be modified if the patches are applied.
The second command will apply the patches.

[source,shell]
....
# freebsd-update fetch
# freebsd-update install
....

If the update applies any kernel patches, the system will need a reboot in order to boot into the patched kernel.
If the patch was applied to any running binaries, the affected applications should be restarted so that the patched version of the binary is used.

[NOTE]
====
Usually, the user needs to be prepared to reboot the system.
To know if the system requires a reboot due to a kernel update, execute the commands `freebsd-version -k` and `uname -r`.
Reboot the system if the outputs differ.
====

The system can be configured to automatically check for updates once every day by adding this entry to [.filename]#/etc/crontab#:

[.programlisting]
....
@daily                                  root    freebsd-update cron
....

If patches exist, they will automatically be downloaded but will not be applied.
The `root` user will be sent an email so that the patches may be reviewed and manually installed with `freebsd-update install`.

If anything goes wrong, `freebsd-update` has the ability to roll back the last set of changes with the following command:

[source,shell]
....
# freebsd-update rollback
Uninstalling updates... done.
....

Again, the system should be restarted if the kernel or any kernel modules were modified and any affected binaries should be restarted.

Only the [.filename]#GENERIC# kernel can be automatically updated by `freebsd-update`.
If a custom kernel is installed, it will have to be rebuilt and reinstalled after `freebsd-update` finishes installing the updates.
The default kernel name is _GENERIC_.
The man:uname[1] command may be used to verify its installation.

[NOTE]
====
Always keep a copy of the [.filename]#GENERIC# kernel in [.filename]#/boot/GENERIC#.
It will be helpful in diagnosing a variety of problems and in performing version upgrades.
Refer to crossref:cutting-edge[freebsd-update-custom-kernel-9x, Custom Kernels with FreeBSD 9.X and Later] for instructions on how to get a copy of the [.filename]#GENERIC# kernel.
====

Unless the default configuration in [.filename]#/etc/freebsd-update.conf# has been changed,
`freebsd-update` will install the updated kernel sources along with the rest of the updates.
Rebuilding and reinstalling a new custom kernel can then be performed in the usual way.

The updates distributed by `freebsd-update` do not always involve the kernel.
It is not necessary to rebuild a custom kernel if the kernel sources have not been modified by `freebsd-update install`.
However, `freebsd-update` will always update [.filename]#/usr/src/sys/conf/newvers.sh#.
The current patch level, as indicated by the `-p` number reported by `uname -r`, is obtained from this file.
Rebuilding a custom kernel, even if nothing else changed, allows `uname` to accurately report the current patch level of the system.
This is particularly helpful when maintaining multiple systems, as it allows for a quick assessment of the updates installed in each one.

[[freebsdupdate-upgrade]]
=== Performing Minor and Major Version Upgrades

Upgrades from one minor version of FreeBSD to another are called _minor version_ upgrades. An example:

- FreeBSD 13.1 to 13.2.

_Major version_ upgrades increase the major version number. An example:

- FreeBSD 13.2 to 14.0.

Both types of upgrade can be performed by providing `freebsd-update` with a release version target.

[WARNING]
====
After each new `RELEASE`, FreeBSD package build servers will, for a limited period, *not* use the newer version of the operating system.
This provides continuity for the many users who do not upgrade immediately after a release announcement.
For example:

* packages for users of 13.1 and 13.2 will be built on a server running 13.1, until 13.1 reaches end of life

-- and, critically:

* a kernel module that is built on 13.1 might *not* be suitable for 13.2.

So, with any minor or major OS upgrade, if the package requirements include any kernel module:

* *be prepared to build the module from source*.

====

[NOTE]
====
If the system is running a custom kernel, make sure that a copy of the [.filename]#GENERIC# kernel exists in [.filename]#/boot/GENERIC# before starting the upgrade.
Refer to crossref:cutting-edge[freebsd-update-custom-kernel-9x, Custom Kernels with FreeBSD 9.X and Later] for instructions on how to get a copy of the [.filename]#GENERIC# kernel.
====

Before upgrading to a new version, ensure the existing FreeBSD installation is up to date with respect to security and errata patches:

[source,shell]
....
# freebsd-update fetch
# freebsd-update install
....

The following command, when run on a FreeBSD 13.1 system, will upgrade it to FreeBSD 13.2:

[source,shell]
....
# freebsd-update -r 13.2-RELEASE upgrade
....

After the command has been received, `freebsd-update` will evaluate the configuration file and current system in an attempt to gather the information necessary to perform the upgrade.
A screen listing will display which components have and have not been detected.
For example:

[source,shell]
....
Looking up update.FreeBSD.org mirrors... 1 mirrors found.
Fetching metadata signature for 13.1-RELEASE from update1.FreeBSD.org... done.
Fetching metadata index... done.
Inspecting system... done.

The following components of FreeBSD seem to be installed:
kernel/smp src/base src/bin src/contrib src/crypto src/etc src/games
src/gnu src/include src/krb5 src/lib src/libexec src/release src/rescue
src/sbin src/secure src/share src/sys src/tools src/ubin src/usbin
world/base world/info world/lib32 world/manpages

The following components of FreeBSD do not seem to be installed:
kernel/generic world/catpages world/dict world/doc world/games
world/proflibs

Does this look reasonable (y/n)? y
....

At this point, `freebsd-update` will attempt to download all files required for the upgrade.
In some cases, the user may be prompted with questions regarding what to install or how to proceed.

When using a custom kernel, the above step will produce a warning similar to the following:

[source,shell]
....
WARNING: This system is running a "MYKERNEL" kernel, which is not a
kernel configuration distributed as part of FreeBSD 13.1-RELEASE.
This kernel will not be updated: you MUST update the kernel manually
before running "/usr/sbin/freebsd-update install"
....

This warning may be safely ignored at this point.
The updated [.filename]#GENERIC# kernel will be used as an intermediate step in the upgrade process.

Once all the patches have been downloaded to the local system, they will be applied.
This process may take a while, depending on the speed and workload of the machine.
Configuration files will then be merged.
The merging process requires some user intervention as a file may be merged or an editor may appear on screen for a manual merge.
The results of every successful merge will be shown to the user as the process continues.
A failed or ignored merge will cause the process to abort.
Users may wish to make a backup of [.filename]#/etc# and manually merge important files,
such as [.filename]#master.passwd# or [.filename]#group# at a later time.

[NOTE]
====
The system is not being altered yet as all patching and merging is happening in another directory.
Once all patches have been applied successfully,
all configuration files have been merged and it seems the process will go smoothly,
the changes can be committed to disk by the user using the following command:

[source,shell]
....
# freebsd-update install
....

====

The kernel and kernel modules will be patched first.
If the system is running with a custom kernel,
use man:nextboot[8] to set the kernel for the next boot to the updated [.filename]#/boot/GENERIC#:

[source,shell]
....
# nextboot -k GENERIC
....

[WARNING]
====
Before rebooting with the [.filename]#GENERIC# kernel,
make sure it contains all the drivers required for the system to boot properly and connect to the network,
if the machine being updated is accessed remotely.
In particular, if the running custom kernel contains built-in functionality usually provided by kernel modules, make sure to temporarily load these modules into the [.filename]#GENERIC# kernel using the [.filename]#/boot/loader.conf# facility.
It is recommended to disable non-essential services as well as any disk and network mounts until the upgrade process is complete.
====

The machine should now be restarted with the updated kernel:

[source,shell]
....
# shutdown -r now
....

Once the system has come back online, restart `freebsd-update` using the following command.
Since the state of the process has been saved, `freebsd-update` will not start from the beginning,
but will instead move on to the next phase and remove all old shared libraries and object files.

[source,shell]
....
# freebsd-update install
....

[NOTE]
====
Depending upon whether any library version numbers were bumped, there may only be two install phases instead of three.
====

The upgrade is now complete.
If this was a major version upgrade, reinstall all ports and packages as
described in crossref:cutting-edge[freebsdupdate-portsrebuild, Upgrading Packages After a Major Version Upgrade].

[[freebsd-update-custom-kernel-9x]]
==== Custom Kernels with FreeBSD 9.X and Later

Before using `freebsd-update`, ensure that a copy of the [.filename]#GENERIC# kernel exists in [.filename]#/boot/GENERIC#.
If a custom kernel has only been built once, the kernel in [.filename]#/boot/kernel.old# is the `GENERIC` kernel.
Simply rename this directory to [.filename]#/boot/GENERIC#.

If a custom kernel has been built more than once or if it is unknown how many times the custom kernel has been built,
obtain a copy of the `GENERIC` kernel that matches the current version of the operating system.
If physical access to the system is available, a copy of the `GENERIC` kernel can be installed from the installation media:

[source,shell]
....
# mount /media
# cd /media/usr/freebsd-dist
# tar -C/ -xvf kernel.txz boot/kernel/kernel
....

Alternately, the `GENERIC` kernel may be rebuilt and installed from source:

[source,shell]
....
# cd /usr/src
# make kernel __MAKE_CONF=/dev/null SRCCONF=/dev/null
....

For this kernel to be identified as the `GENERIC` kernel by `freebsd-update`,
the [.filename]#GENERIC# configuration file must not have been modified in any way.
It is also suggested that the kernel is built without any other special options.

Rebooting into the [.filename]#GENERIC# kernel is not required as `freebsd-update` only needs [.filename]#/boot/GENERIC# to exist.

[[freebsdupdate-portsrebuild]]
==== Upgrading Packages After a Major Version Upgrade

Generally, installed applications will continue to work without problems after minor version upgrades.
Major versions use different Application Binary Interfaces (ABIs), which will break most third-party applications.
After a major version upgrade, all installed packages and ports need to be upgraded.
Packages can be upgraded using `pkg upgrade`.
To upgrade installed ports, use a utility such as package:ports-mgmt/portmaster[].

A forced upgrade of all installed packages will replace the packages with fresh versions from the repository even if the version number has not increased.
This is required because of the ABI version change when upgrading between major versions of FreeBSD.
The forced upgrade can be accomplished by performing:

[source,shell]
....
# pkg-static upgrade -f
....

A rebuild of all applications installed from the ports collection can be accomplished with this command:

[source,shell]
....
# portmaster -af
....

This command will display the configuration screens for each application that has configurable options and wait for the user to interact with those screens.
To prevent this behavior, and use only the default options, include `-G` in the above command.

Once the software upgrades are complete,
finish the upgrade process with a final call to `freebsd-update` in order to tie up all the loose ends in the upgrade process:

[source,shell]
....
# freebsd-update install
....

If the [.filename]#GENERIC# kernel was temporarily used,
this is the time to build and install a new custom kernel using the instructions in crossref:kernelconfig[kernelconfig,Configuring the FreeBSD Kernel].

Reboot the machine into the new FreeBSD version.
The upgrade process is now complete.

[[freebsdupdate-system-comparison]]
=== System State Comparison

The state of the installed FreeBSD version against a known good copy can be tested using `freebsd-update IDS`.
This command evaluates the current version of system utilities, libraries, and configuration files and can be used as a built-in Intrusion Detection System (IDS).

[WARNING]
====
This command is not a replacement for a real IDS such as package:security/snort[].
As `freebsd-update` stores data on disk, the possibility of tampering is evident.
While this possibility may be reduced using `kern.securelevel` and by storing the `freebsd-update` data on a read-only file system when not in use,
a better solution would be to compare the system against a secure disk, such as a DVD or securely stored external USB disk device.
An alternative method for providing IDS functionality using a built-in utility is described in crossref:security[security-ids,"Binary Verification"]
====

To begin the comparison, specify the output file to save the results to:

[source,shell]
....
# freebsd-update IDS >> outfile.ids
....

The system will now be inspected and a lengthy listing of files, along with the SHA256 hash values for both the known value in the release and the current installation, will be sent to the specified output file.

The entries in the listing are extremely long, but the output format may be easily parsed.
For instance, to obtain a list of all files which differ from those in the release, issue the following command:

[source,shell]
....
# cat outfile.ids | awk '{ print $1 }' | more
/etc/master.passwd
/etc/motd
/etc/passwd
/etc/pf.conf
....

This sample output has been truncated as many more files exist.
Some files have natural modifications.
For example, [.filename]#/etc/passwd# will be modified if users have been added to the system.
Kernel modules may differ as `freebsd-update` may have updated them.
To exclude specific files or directories, add them to the `IDSIgnorePaths` option in [.filename]#/etc/freebsd-update.conf#.

[[updating-bootcode]]
== Updating Bootcode

The following manuals describe the upgrade process of bootcode and boot loaders: man:gpart[8], man:gptboot[8], man:gptzfsboot[8], and man:loader.efi[8].

[[updating-upgrading-documentation]]
== Updating the Documentation Set

Documentation is an integral part of the FreeBSD operating system.
While an up-to-date version of the FreeBSD documentation is always available on the FreeBSD web site (link:https://docs.FreeBSD.org[Documentation Portal]), it can be handy to have an up-to-date, local copy of the FreeBSD website, handbooks, FAQ, and articles.

This section describes how to use either source or the FreeBSD Ports Collection to keep a local copy of the FreeBSD documentation up-to-date.

For information on editing and submitting corrections to the documentation,
refer to the FreeBSD Documentation Project Primer for New Contributors (extref:{fdp-primer}[FreeBSD Documentation Project Primer for New Contributors]).

[[updating-installed-documentation]]
=== Updating Documentation from Source

Rebuilding the FreeBSD documentation from source requires a collection of tools which are not part of the FreeBSD base system.
The required tools can be installed following extref:{fdp-primer}overview[these steps, overview-quick-start] from the FreeBSD Documentation Project Primer.

Once installed, use `git` to fetch a clean copy of the documentation source:

[source,shell]
....
# git clone https://git.FreeBSD.org/doc.git /usr/doc
....

The initial download of the documentation sources may take a while.
Let it run until it completes.

Future updates of the documentation sources may be fetched by running:

[source,shell]
....
# git pull
....

Once an up-to-date snapshot of the documentation sources has been fetched to [.filename]#/usr/doc#,
everything is ready for an update of the installed documentation.

A full update may be performed by typing:

[source,shell]
....
# cd /usr/doc
# make
....

[[current-stable]]
== Tracking a Development Branch

FreeBSD has two development branches: FreeBSD-CURRENT and FreeBSD-STABLE.

This section provides an explanation of each branch and its intended audience, as well as how to keep a system up-to-date with each respective branch.

[[current]]
=== Using FreeBSD-CURRENT

FreeBSD-CURRENT is the "bleeding edge" of FreeBSD development and FreeBSD-CURRENT users are expected to have a high degree of technical skill.
Less technical users who wish to track a development branch should track FreeBSD-STABLE instead.

FreeBSD-CURRENT is the very latest source code for FreeBSD and includes works in progress, experimental changes, and transitional mechanisms that might or might not be present in the next official release.
While many FreeBSD developers compile the FreeBSD-CURRENT source code daily, there are short periods of time when the source may not be buildable.
These problems are resolved as quickly as possible, but whether or not FreeBSD-CURRENT brings disaster or new functionality can be a matter of when the source code was synced.

FreeBSD-CURRENT is made available for three primary interest groups:

. Members of the FreeBSD community who are actively working on some part of the source tree.
. Members of the FreeBSD community who are active testers. They are willing to spend time solving problems, making topical suggestions on changes and the general direction of FreeBSD, and submitting patches.
. Users who wish to keep an eye on things, use the current source for reference purposes, or make the occasional comment or code contribution.

FreeBSD-CURRENT should _not_ be considered a fast-track to getting new features before the next release as pre-release features are not yet fully tested and most likely contain bugs.
It is not a quick way of getting bug fixes as any given commit is just as likely to introduce new bugs as to fix existing ones.
FreeBSD-CURRENT is not in any way "officially supported".

To track FreeBSD-CURRENT:

. Join the {freebsd-current} and the {dev-commits-src-main} lists. This is _essential_ in order to see the comments that people are making about the current state of the system and to receive important bulletins about the current state of FreeBSD-CURRENT.
+
The {dev-commits-src-main} list records the commit log entry for each change as it is made, along with any pertinent information on possible side effects.
+
To join these lists, go to {mailing-lists}, click on the list to subscribe to, and follow the instructions.
In order to track changes to the whole source tree, not just the changes to FreeBSD-CURRENT, subscribe to the {dev-commits-src-all}.
. Synchronize with the FreeBSD-CURRENT sources. Typically, `git` is used to check out the -CURRENT code from the `main` branch of the FreeBSD Git repository (see crossref:mirrors[git,“Using Git”] for details).
. Due to the size of the repository, some users choose to only synchronize the sections of source that interest them or which they are contributing patches to. However, users that plan to compile the operating system from source must download _all_ of FreeBSD-CURRENT, not just selected portions.
+
Before compiling FreeBSD-CURRENT, read [.filename]#/usr/src/Makefile# very
carefully and follow the instructions in crossref:cutting-edge[makeworld, Updating FreeBSD from Source].
Read the {freebsd-current} and [.filename]#/usr/src/UPDATING# to stay up-to-date on other bootstrapping procedures that sometimes become necessary on the road to the next release.
. Be active! FreeBSD-CURRENT users are encouraged to submit their suggestions for enhancements or bug fixes. Suggestions with accompanying code are always welcome.

[[stable]]
=== Using FreeBSD-STABLE

FreeBSD-STABLE is the development branch from which major releases are made.
Changes go into this branch at a slower pace and with the general assumption that they have first been tested in FreeBSD-CURRENT.
This is _still_ a development branch and, at any given time, the sources for FreeBSD-STABLE may or may not be suitable for general use.
It is simply another engineering development track, not a resource for end-users.
Users who do not have the resources to perform testing should instead run the most recent release of FreeBSD.

Those interested in tracking or contributing to the FreeBSD development process, especially as it relates to the next release of FreeBSD, should consider following FreeBSD-STABLE.

While the FreeBSD-STABLE branch should compile and run at all times, this cannot be guaranteed.
Since more people run FreeBSD-STABLE than FreeBSD-CURRENT, it is inevitable that bugs and corner cases will sometimes be found in FreeBSD-STABLE that were not apparent in FreeBSD-CURRENT.
For this reason, one should not blindly track FreeBSD-STABLE.
It is particularly important _not_ to update any production servers to FreeBSD-STABLE without thoroughly testing the code in a development or testing environment.

To track FreeBSD-STABLE:

. Join the {freebsd-stable} in order to stay informed of build dependencies that may appear in FreeBSD-STABLE or any other issues requiring special attention. Developers will also make announcements in this mailing list when they are contemplating some controversial fix or update, giving the users a chance to respond if they have any issues to raise concerning the proposed change.
+
Join the relevant git list for the branch being tracked.
For example, users tracking the {betarel-current-major}-STABLE branch should join the {dev-commits-src-branches}.
This list records the commit log entry for each change as it is made, along with any pertinent information on possible side effects.
+
To join these lists, go to {mailing-lists}, click on the list to subscribe to, and follow the instructions.
In order to track changes for the whole source tree, subscribe to {dev-commits-src-all}.
. To install a new FreeBSD-STABLE system, install the most recent FreeBSD-STABLE release from the crossref:mirrors[mirrors,FreeBSD mirror sites] or use a monthly snapshot built from FreeBSD-STABLE. Refer to link:https://www.FreeBSD.org/snapshots/[www.freebsd.org/snapshots] for more information about snapshots.
+
To compile or upgrade an existing FreeBSD system to FreeBSD-STABLE, use `git` to check out the source for the desired branch.
Branch names, such as `stable/13`, are listed at link:https://www.FreeBSD.org/releng/[www.freebsd.org/releng].
. Before compiling or upgrading to FreeBSD-STABLE , read
  [.filename]#/usr/src/Makefile# carefully and follow the instructions in
  crossref:cutting-edge[makeworld, Updating FreeBSD from Source]. Read the {freebsd-stable} and [.filename]#/usr/src/UPDATING# to keep up-to-date on other bootstrapping procedures that sometimes become necessary on the road to the next release.

[[translate-n-number]]
=== The N-number
When tracking down bugs it is important to know which versions of the source code have been used to create the system exhibiting an issue.
FreeBSD provides version information compiled into the kernel.
man:uname[1] retrieves this information, for example:
[source,shell]
....
% uname -v
FreeBSD 14.0-CURRENT #112 main-n247514-031260d64c18: Tue Jun 22 20:43:19 MDT 2021     fred@machine:/usr/home/fred/obj/usr/home/fred/git/head/amd64.amd64/sys/FRED
....
The final field gives information regarding the kernel name, the person that built it, and the location that it was compiled in.
Looking at the 4th field, it is made up of several parts:
[source,shell]
....
main-n247514-031260d64c18

main		<.>
n247514		<.>
031260d64c18	<.>
		<.>
....
<.> Git branch name.
Note: comparisons of n-numbers are only valid on branches published by the project (`main`, `stable/XX` and `releng/XX`).
Local branches will have n-numbers that will overlap commits of their parent branch.
<.> The n-number is a linear count of commits back to the start of the Git repository starting with the Git hash included in the line.
<.> Git hash of the checked out tree
<.> Sometimes a suffix of `-dirty` is present when the kernel was built in a tree with uncommitted changes.
It is absent in this example because the FRED kernel was built from a pristine checkout.

The `git rev-list` command is used to find the n-number corresponding to a Git hash.
For example:
[source,shell]
....
% git rev-list --first-parent --count 031260d64c18 <.>
247514 <.>
....
<.> git hash to translate (the hash from the above example is reused)
<.> The n-number.

Usually this number is not all that important.
However, when bug fixes are committed, this number makes it easy to quickly determine whether the fix is present in the currently running system.
Developers will often refer to the hash of the commit (or provide a URL which has that hash), but not the n-number since the hash is the easily visible identifier for a change while the n-number is not.
Security advisories and errata notices will also note an n-number, which can be directly compared against the system.
When shallow Git clones are used, n-numbers cannot be compared reliably, as the git rev-list command counts all revisions in the repository, which a shallow clone omits.

[[makeworld]]
== Updating FreeBSD from Source

Updating FreeBSD by compiling from source offers several advantages over binary updates.
Code can be built with options to take advantage of specific hardware.
Parts of the base system can be built with non-default settings, or left out entirely where they are not needed or desired.
The build process takes longer to update a system than just installing binary updates, but allows complete customization to produce a tailored version of FreeBSD.

[[updating-src-quick-start]]
=== Quick Start

This is a quick reference for the typical steps used to update FreeBSD by building from source.
Later sections describe the process in more detail.

[WARNING]
====
When switching from man:mergemaster[8] to man:etcupdate[8], the first run might merge changes incorrectly generating spurious conflicts.
To prevent this, perform the following steps *before* updating sources and building the new world:

[source,shell]
....
# etcupdate extract <.>
# etcupdate diff <.>
....

<.> Bootstrap the database of stock [.filename]#/etc# files; for more information see man:etcupdate[8].

<.> Check the diff after bootstrapping. Trim any local changes that are no longer needed to reduce the chance of conflicts in future updates.
====

[.procedure]
====
* Update and Build
+
[source,shell]
....
# git -C /usr/src pull <.>
check /usr/src/UPDATING  <.>
# cd /usr/src          <.>
# make -j4 buildworld  <.>
# make -j4 kernel      <.>
# shutdown -r now      <.>
# etcupdate -p         <.>
# cd /usr/src          <.>
# make installworld    <.>
# etcupdate -B         <.>
# shutdown -r now      <.>
....

<.> Get the latest version of the source. See
crossref:cutting-edge[updating-src-obtaining-src, Updating the Source] for more information on obtaining and updating source.

<.> Check [.filename]#/usr/src/UPDATING# for any manual steps required before or after building from source.

<.> Go to the source directory.

<.> Compile the world, everything except the kernel.

<.> Compile and install the kernel. This is equivalent to `make buildkernel installkernel`.

<.> Reboot the system to the new kernel.

<.> Update and merge configuration files in [.filename]#/etc/# required before installworld.

<.> Go to the source directory.

<.> Install the world.

<.> Update and merge configuration files in [.filename]#/etc/#.

<.> Restart the system to use the newly-built world and kernel.
====

[[updating-src-preparing]]
=== Preparing for a Source Update

Read [.filename]#/usr/src/UPDATING#. Any manual steps that must be performed before or after an update are described in this file.

[[updating-src-obtaining-src]]
=== Updating the Source

FreeBSD source code is located in [.filename]#/usr/src/#.
The preferred method of updating this source is through the Git version control system.
Verify that the source code is under version control:

[source,shell]
....
# cd /usr/src
# git remote --v
origin  https://git.freebsd.org/src.git (fetch)
origin  https://git.freebsd.org/src.git (push)
....

This indicates that [.filename]#/usr/src/# is under version control and can be updated with man:git[1]:

[[synching]]
[source,shell]
....
# git -C /usr/src pull
....

The update process can take some time if the directory has not been updated recently.
After it finishes, the source code is up to date and the build process described in the next section can begin.

[NOTE]
====
Obtaining the source:

If the output says `fatal: not a git repository`, the files there are missing or were installed with a different method.
A new checkout of the source is required.
====

[[updating-src-obtaining-src-repopath]]
.FreeBSD Versions and Repository Branches
[cols="10%,10%,80%", options="header"]
|===
| uname&#160;&#8209;r Output
| Repository Path
| Description

|`_X.Y_-RELEASE`
|`releng/_X.Y_`
|The Release version plus only critical security and bug fix patches. This branch is recommended for most users.

|`_X.Y_-STABLE`
|`stable/_X_`
|

The Release version plus all additional development on that branch. _STABLE_ refers to the Applications Binary Interface (ABI) not changing, so software compiled for earlier versions still runs. For example, software compiled to run on FreeBSD 10.1 will still run on FreeBSD 10-STABLE compiled later.

STABLE branches occasionally have bugs or incompatibilities which might affect users, although these are typically fixed quickly.

|`_X_-CURRENT`
|`main`
|The latest unreleased development version of FreeBSD. The CURRENT branch can have major bugs or incompatibilities and is recommended only for advanced users.
|===

Determine which version of FreeBSD is being used with man:uname[1]:

[source,shell]
....
# uname -r
13.2-RELEASE
....

Based on crossref:cutting-edge[updating-src-obtaining-src-repopath,FreeBSD Versions and Repository Branches], the source used to update `13.2-RELEASE` has a repository path of `releng/13.2`.
That path is used when checking out the source:

[source,shell]
....
# mv /usr/src /usr/src.bak <.>
# git clone --branch releng/13.2 https://git.FreeBSD.org/src.git /usr/src <.>
....

<.> Move the old directory out of the way. If there are no local modifications in this directory, it can be deleted.

<.> The path from crossref:cutting-edge[updating-src-obtaining-src-repopath,FreeBSD Versions and Repository Branches] is added to the repository URL. The third parameter is the destination directory for the source code on the local system.

[[updating-src-building]]
=== Building from Source

The _world_, or all of the operating system except the kernel, is compiled.
This is done first to provide up-to-date tools to build the kernel.
Then the kernel itself is built:

[source,shell]
....
# cd /usr/src
# make buildworld
# make buildkernel
....

The compiled code is written to [.filename]#/usr/obj#.

These are the basic steps.
Additional options to control the build are described below.

[[updating-src-building-clean-build]]
==== Performing a Clean Build

Some versions of the FreeBSD build system leave previously-compiled code in the temporary object directory, [.filename]#/usr/obj#.
This can speed up later builds by avoiding recompiling code that has not changed.
To force a clean rebuild of everything, use `cleanworld` before starting a build:

[source,shell]
....
# make cleanworld
....

[[updating-src-building-jobs]]
==== Setting the Number of Jobs

Increasing the number of build jobs on multi-core processors can improve build speed.
Determine the number of cores with `sysctl hw.ncpu`.
Processors vary, as do the build systems used with different versions of FreeBSD, so testing is the only sure method to tell how a different number of jobs affects the build speed.
For a starting point, consider values between half and double the number of cores.
The number of jobs is specified with `-j`.

[[updating-src-building-jobs-example]]
.Increasing the Number of Build Jobs
[example]
====
Building the world and kernel with four jobs:

[source,shell]
....
# make -j4 buildworld buildkernel
....

====

[[updating-src-building-only-kernel]]
==== Building Only the Kernel

A `buildworld` must be completed if the source code has changed.
After that, a `buildkernel` to build a kernel can be run at any time.
To build just the kernel:

[source,shell]
....
# cd /usr/src
# make buildkernel
....

[[updating-src-building-custom-kernel]]
==== Building a Custom Kernel

The standard FreeBSD kernel is based on a _kernel config file_ called [.filename]#GENERIC#.
The [.filename]#GENERIC# kernel includes the most commonly-needed device drivers and options.
Sometimes it is useful or necessary to build a custom kernel, adding or removing device drivers or options to fit a specific need.

For example, someone developing a small embedded computer with severely limited RAM could remove unneeded device drivers or options to make the kernel slightly smaller.

Kernel config files are located in [.filename]#/usr/src/sys/arch/conf/#, where _arch_ is the output from `uname -m`.
On most computers, that is `amd64`, giving a config file directory of [.filename]#/usr/src/sys/amd64/conf/#.

[TIP]
====
[.filename]#/usr/src# can be deleted or recreated, so it is preferable to keep custom kernel config files in a separate directory, like [.filename]#/root#.
Link the kernel config file into the [.filename]#conf# directory.
If that directory is deleted or overwritten, the kernel config can be re-linked into the new one.
====

A custom config file can be created by copying the [.filename]#GENERIC# config file.
In this example, the new custom kernel is for a storage server, so is named [.filename]#STORAGESERVER#:

[source,shell]
....
# cp /usr/src/sys/amd64/conf/GENERIC /root/STORAGESERVER
# cd /usr/src/sys/amd64/conf
# ln -s /root/STORAGESERVER .
....

[.filename]#/root/STORAGESERVER# is then edited, adding or removing devices or options as shown in man:config[5].

The custom kernel is built by setting `KERNCONF` to the kernel config file on the command line:

[source,shell]
....
# make buildkernel KERNCONF=STORAGESERVER
....

[[updating-src-installing]]
=== Installing the Compiled Code

After the `buildworld` and `buildkernel` steps have been completed, the new kernel and world are installed:

[source,shell]
....
# cd /usr/src
# make installkernel
# shutdown -r now
# cd /usr/src
# make installworld
# shutdown -r now
....

If a custom kernel was built, `KERNCONF` must also be set to use the new custom kernel:

[source,shell]
....
# cd /usr/src
# make installkernel KERNCONF=STORAGESERVER
# shutdown -r now
# cd /usr/src
# make installworld
# shutdown -r now
....

[[updating-src-completing]]
=== Completing the Update

A few final tasks complete the update.
Any modified configuration files are merged with the new versions, outdated libraries are located and removed, then the system is restarted.

[[updating-src-completing-merge-etcupdate]]
==== Merging Configuration Files with man:etcupdate[8]

man:etcupdate[8] is a tool for managing updates to files that are not updated as part of an installworld such as files located in [.filename]#/etc/#.
It manages updates by doing a three-way merge of changes made to these files against the local versions.
man:etcupdate[8] is designed to minimize the amount of user intervention.

[NOTE]
====
In general, man:etcupdate[8] does not need any specific arguments for its job.
There is however a handy in between command for sanity checking what will be done the first time man:etcupdate[8] is used:

[source,shell]
....
# etcupdate diff
....

This command allows the user to audit configuration changes.
====

If man:etcupdate[8] is not able to merge a file automatically, the merge conflicts can be resolved with manual interaction by issuing:

[source,shell]
....
# etcupdate resolve
....

[WARNING]
====
When switching from man:mergemaster[8] to man:etcupdate[8], the first run might merge changes incorrectly generating spurious conflicts.
To prevent this, perform the following steps *before* updating sources and building the new world:

[source,shell]
....
# etcupdate extract <.>
# etcupdate diff <.>
....

<.> Bootstrap the database of stock [.filename]#/etc# files; for more information see man:etcupdate[8].

<.> Check the diff after bootstrapping. Trim any local changes that are no longer needed to reduce the chance of conflicts in future updates.
====

[[updating-src-completing-check-old]]
==== Checking for Outdated Files and Libraries

Some obsolete files or directories can remain after an update.
These files can be located:

[source,shell]
....
# make check-old
....

and deleted:

[source,shell]
....
# make delete-old
....

Some obsolete libraries can also remain.
These can be detected with:

[source,shell]
....
# make check-old-libs
....

and deleted with

[source,shell]
....
# make delete-old-libs
....

Programs which were still using those old libraries will stop working when the library has been deleted.
These programs must be rebuilt or replaced after deleting the old libraries.

[TIP]
====
When all the old files or directories are known to be safe to delete,
pressing kbd:[y] and kbd:[Enter] to delete each file can be avoided by setting `BATCH_DELETE_OLD_FILES` in the command.
For example:

[source,shell]
....
# make BATCH_DELETE_OLD_FILES=yes delete-old-libs
....

====

[[updating-src-completing-restart]]
==== Restarting After the Update

The last step after updating is to restart the computer so all the changes take effect:

[source,shell]
....
# shutdown -r now
....

[[pkgbase]]
== Updating FreeBSD with Base System Packages

Starting from 14.0-RELEASE, the FreeBSD project has published a set of packages of the kernel and base system, using man:pkg[8].
These can be used in the same convenient way that users are used to, for adding and upgrading ported software, but for the kernel and userland itself.
The packages, and usage thereof, are often referred to as pkgbase.

Packages have been available since link:https://lists.freebsd.org/archives/freebsd-pkgbase/2023-October/000221.html[October 2023], considered experimental for FreeBSD's 14 Release.

Starting from 15.0-RELEASE, Base System packages will be the default and officially supported way to both install new FreeBSD instances, and also to update and upgrade between minor and major releases.

[NOTE]
====
From 15.0-RELEASE onwards, the long-running man:freebsd-update[8] tool will only be supported on the earlier 13 and 14 release branches.
====

Base System Packages replace:

* tarball distribution sets, such as `base.txz` or `kernel.txz`, which are historically used for installation of the OS with man:bsdinstall[8]
* man:freebsd-update[8] for updates to the OS.

Base System packages complement crossref:cutting-edge[makeworld,"building and installing from source"], which is still available for those who wish to build their own custom kernels or userland.
It is also possible to build custom base system packages from local sources, as well as just relying on officially provided packages.

=== Converting a Host to use pkgbase

Systems installed with FreeBSD 14.0-RELEASE or later can be converted to use Base System packages.
For earlier versions, it is recommended to first upgrade to a recent Version, and then convert.

The FreeBSD Foundation has sponsored development of a tool called link:https://github.com/FreeBSDFoundation/pkgbasify[pkgbasify], which for most users, will be the easiest and safest way to convert systems to use Base System packages.

[WARNING]
====
Note that this migration requires up to 5GiB additional free space, to download, unpack, and relocate any conflicting files.
The pkgbasify tool does not check for this and it is the responsibility of the user to ensure that enough space is available before running the migration.
====

man:pkgbasify[8] (or whatever outcome link:https://reviews.freebsd.org/D51594[D51594] or link:https://wiki.freebsd.org/WantedPorts#O-P[port request] will have) performs 6 main tasks:

* Creates a backup boot environment (ZFS only) with man:bectl[8]
* Creates the new package repository config files
* Upgrades existing system components such as base, kernel, lib32, debug
* Merges existing and new config files
* Updates passwd and capabilities databases
* Restarts sshd immediately

[source,shell]
....
# cd /tmp
# fetch https://github.com/FreeBSDFoundation/pkgbasify/raw/refs/heads/main/pkgbasify.lua
# chmod +x pkgbasify.lua
# ./pkgbasify.lua
....

=== Upgrading a Host using pkgbase

[WARNING]
====
This is still in development, so please be careful especially when converting an existing system to use pkgbase.
====

Create a folder for custom pkg repository config files, if there is none present already.

[source,shell]
....
# mkdir -p /usr/local/etc/pkg/repos/
....

For using the pkgbase repository, create a pkg repository configuration file called `FreeBSD-base.conf`:

[[pgk-base-repo-configuration]]
[.programlisting]
....
FreeBSD-base {
    url = "pkg+https://pkg.freebsd.org/${ABI}/base_release_${VERSION_MINOR}";
    mirror_type = "srv";
    signature_type = "fingerprints";
    fingerprints = "/usr/share/keys/pkg";
    enabled = yes;
}
....

for more information on specific configuration options see man:pkg.conf[5].

There are different branches to choose from (by changing the url accordingly):

[[table-of-packagebase-branches]]
.Base system package Branches
[cols="10%,20%,70%, options="header"]
|===
| Branch
| Frequency
| URL

| main
| twice daily - 12:00 and 00:00 UTC
| `https://pkg.freebsd.org/${ABI}/base_latest`

| main
| weekly – Sunday at 12:00 UTC
| `https://pkg.freebsd.org/${ABI}/base_weekly`

| stable/14
| twice daily – 12:00 and 00:00 UTC
| `https://pkg.freebsd.org/${ABI}/base_latest`

| stable/14
| weekly – Sunday at 12:00 UTC
| `https://pkg.freebsd.org/${ABI}/base_weekly`

| releng/14.2
| twice daily – 12:00 and 00:00 UTC
| `https://pkg.freebsd.org/${ABI}/base_release_2`

| releng/14.3
| twice daily – 12:00 and 00:00 UTC
| `https://pkg.freebsd.org/${ABI}/base_release_3`
|===

To upgrade the system, change the configuration file according to the desired release, and run:

[source,shell]
....
# pkg update -r FreeBSD-base
# pkg upgrade -r FreeBSD-base
....

check, if these packages are correct and accept the changes.

Reboot the OS executing the following command:

[source,shell]
....
# shutdown -r now
....

==== Performing Major version upgrades

When running ZFS, consider creating a boot environment before upgrading to a newer version.
To create a new boot environment using the man:bectl[8] tool run:

[source,shell]
....
# bectl create 14.2-RELEASE-p4
....

Use this boot environment to start the system as it was before the update if something goes wrong.

Save a list of the non-base packages in case they are needed later:

[source,shell]
....
pkg prime-origins | sort -u > /var/tmp/pkg-prime-origins.txt
....

Change `/usr/local/etc/pkg/repos/FreeBSD-base.conf` to target the correct major release like `base_latest`, so it looks like:

[.programlisting]
....
FreeBSD-base {
    url = "pkg+https://pkg.freebsd.org/${ABI}/base_latest";
    mirror_type = "srv";
    signature_type = "fingerprints";
    fingerprints = "/usr/share/keys/pkg";
    enabled = yes;
}
....

The next step will upgrade the system to the specified version.

[WARNING]
====
This step might remove non-base packages, which could include the running desktop environment.
Be careful.
====

Set the environment variable ABI to upgrade the major version (replace amd64 with the architecture and 15 with the targeted version).

[source,shell]
....
# env ABI=FreeBSD:15:amd64 pkg-static upgrade -r FreeBSD-base
....

There will be a prompt to ask about ignoring the version mismatch looking like this:

[source,shell]
....
Newer FreeBSD version for package FreeBSD-zoneinfo:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1500058
- running userland: 1500000
Ignore the mismatch and continue? [y/N]:
....

Check and confirm that.

To check if that was successful, run `freebsd-version -kru`.

Then reboot.

After upgrading to a new major version, updates and upgrades of installed packages to match the ABI version may be necessary.

[source,shell]
....
# pkg update
# pkg upgrade
....

If something broke, go back and activate the backup boot environment created before.

[source,shell]
....
# bectl activate 14.2-RELEASE-p4
....
Reboot, and the system will be back to the state before upgrading.

If no boot environment was created before, consider getting help from link:https://www.freebsd.org/support/[FreeBSD Support].

[[build-pkgbase-packages-locally]]
=== Manually building pkgbase and publishing it to the local network

When building custom pkgbase packages clone the FreeBSD source tree:

[source,shell]
....
# cd /usr/src
# git clone https://github.com/freebsd/freebsd-src.git /usr/src
....

Check out the branch for the release to build packages for:

[source,shell]
....
# git checkout releng/14.3
....

Start the building process, depending on the resources available this could take some while.
Set the parallel processes according to the CPU core count.

This example is written for an 8 core CPU:

[source,shell]
....
# make -j8 buildworld && make -j8 buildkernel && make -j8 packages
....

When building frequently, consider using package:devel/ccache[] to speed up subsequent builds from the cache.

After building, the packages will get saved into `/usr/obj/usr/src/repo/FreeBSD:14:amd64/14.3p2` or something like that, depending on the version build.

To publish these packages to the network set up a nginx service and use this location in the http server configuration:

[.programlisting]
....
 location /FreeBSD:14:amd64 {
   alias /usr/obj/usr/src/repo/FreeBSD:14:amd64/;
   autoindex on;
 }
....

And reload the nginx service.

When not using https, use a small configuration file on the clients to target the pkgbase version just built by editing `/usr/local/etc/pkg/repos/upgrade.conf`:

[.programlisting]
....
upgrade: {
	url         = http://ip.of.the.server/FreeBSD:14:amd64/14.3p2
	enabled     = yes
}
....

and use it as written above (but use -r upgrade instead of FreeBSD-base).

[[small-lan]]
== Tracking for Multiple Machines

When multiple machines need to track the same source tree, it is a waste of disk space, network bandwidth, and CPU cycles to have each system download the sources and rebuild everything.
The solution is to have one machine do most of the work, while the rest of the machines mount that work via NFS.
This section outlines a method of doing so.
For more information about using NFS, refer to crossref:network-servers[network-nfs,"Network File System (NFS)"].

First, identify a set of machines which will run the same set of binaries, known as a _build set_.
Each machine can have a custom kernel, but will run the same userland binaries.
From that set, choose a machine to be the _build machine_ that the world and kernel are built on.
Ideally, this is a fast machine that has sufficient spare CPU to run `make buildworld` and `make buildkernel`.

Select a machine to be the _test machine_, which will test software updates before they are put into production.
This _must_ be a machine that can afford to be down for an extended period of time.
It can be the build machine, but need not be.

All the machines in this build set need to mount [.filename]#/usr/obj# and [.filename]#/usr/src# from the build machine via NFS.
For multiple build sets, [.filename]#/usr/src# should be on one build machine, and NFS mounted on the rest.

Ensure that [.filename]#/etc/make.conf# and [.filename]#/etc/src.conf# on all the machines in the build set agree with the build machine.
That means that the build machine must build all the parts of the base system that any machine in the build set is going to install.
Also, each build machine should have its kernel name set with `KERNCONF` in [.filename]#/etc/make.conf#,
and the build machine should list them all in its `KERNCONF`, listing its own kernel first.
The build machine must have the kernel configuration files for each machine in its [.filename]#/usr/src/sys/arch/conf#.

On the build machine, build the kernel and world as described in
crossref:cutting-edge[makeworld, Updating FreeBSD from Source],
but do not install anything on the build machine.
Instead, install the built kernel on the test machine.
On the test machine, mount [.filename]#/usr/src# and [.filename]#/usr/obj# via NFS.
Then, run `shutdown now` to go to single-user mode in order to install the new kernel and world and run `etcupdate` as usual.
When done, reboot to return to normal multi-user operations.

After verifying that everything on the test machine is working properly,
use the same procedure to install the new software on each of the other machines in the build set.

The same methodology can be used for the ports tree.
The first step is to share [.filename]#/usr/ports# via NFS to all the machines in the build set.
To configure [.filename]#/etc/make.conf# to share distfiles,
set `DISTDIR` to a common shared directory that is writable by whichever user `root` is mapped to by the NFS mount.
Each machine should set `WRKDIRPREFIX` to a local build directory, if ports are to be built locally.
Alternately, if the build system is to build and distribute packages to the machines in the build set,
set `PACKAGES` on the build system to a directory similar to `DISTDIR`.

[[building-on-non-freebsd-hosts]]
== Building on non-FreeBSD Hosts

Historically, building required a FreeBSD host.
Nowadays, FreeBSD can be built on Linux and macOS.

To build on a non-FreeBSD host, the `tools/build/make.py` script is recommended.
This script acts as a wrapper around `bmake`, which is the make implementation used by FreeBSD.
It ensures that the necessary tooling, including the actual FreeBSD's man:make[1], is bootstrapped and that the build environment is properly configured.
In particular, it sets the external toolchain variables, such as `XCC`, `XLD`, and others.
Additionally, the script can pass any additional command arguments, such as `-j 4` for parallel builds or specific make targets, to `bmake`.

[NOTE]
====
A recent version of `bmake` can be used instead of the `tools/build/make.py` script as well.
In that case, however, required environment variables need to be set manually (the easiest way to obtain a list of them is by running `tools/build/make.py --debug`).
====

Otherwise, the list of prerequisites for building FreeBSD is rather short.
In fact, it boils down to installing a couple of dependencies.

On macOS, the only dependency is LLVM.
The necessary dependencies can be installed with package manager (e.g., link:https://brew.sh/[Homebrew]):

[source,shell]
....
brew install llvm
....

On a Linux distributions, install link:https://clang.llvm.org/[Clang] version 10.0 or newer and the headers for libarchive and libbz2 (often packaged as libarchive-dev and libbz2-dev).

Once the dependencies are installed, the host should be able to build FreeBSD.

For example, the following `tools/build/make.py` invocation builds the world:

[source,shell]
....
MAKEOBJDIRPREFIX=/tmp/obj tools/build/make.py -j 8 TARGET=arm64 TARGET_ARCH=aarch64 buildworld
....

It builds the world for target `aarch64:arm64` on 8 CPUs and uses [.filename]#/tmp/obj# for object files.
Note that the variables `MAKEOBJDIRPREFIX`, `TARGET`, and `TARGET_ARCH` are mandatory when building on non-FreeBSD hosts.
Also, make sure to create the object directory pointed to by the `MAKEOBJDIRPREFIX` environment variable.

Refer to man:arch[7] and man:build[7] for more details.
