# $FreeBSD$
# $FreeBSDde: de-www/java/Makefile,v 1.1 2007/11/10 10:18:30 jkois Exp $
# basiert auf: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

#SUBDIR =	dists
#SUBDIR+=	docs
#SUBDIR+=	links

#DOCS =  advocacy.xml
#DOCS+=  howhelp.xml
DOCS+=  index.xml
#DOCS+=  install.xml
#DOCS+=  newsflash.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
