# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=
DATA+=	fixed.css
DATA+=	fixed_large.css
DATA+=	global.css
DATA+=	iefixes.css
DATA+=	layout.css
DATA+=	navigation.css
DATA+=	table.css
DATA+=	text.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
