---
title: 付録B. 参考図書
part: パートV. 付録
prev: books/handbook/mirrors
next: books/handbook/eresources
---

[appendix]
[[bibliography]]
= 参考図書
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: 目次
:table-caption: 表
:figure-caption: 図
:example-caption: 例 
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: B

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/ja/mailing-lists.adoc[]
include::shared/ja/teams.adoc[]
include::shared/ja/urls.adoc[]

FreeBSD オペレーティングシステムの個々の部分については マニュアルページで定義のような説明がなされていますが, どうやってその部分どうしをつなぎあわせて オペレーティングシステム全体を円滑に動作させるかについては, ほとんど説明されていません。 それを補うためにはのよい本や, UNIX(R) システム管理についての 利用者向けのマニュアルが欠かせません。

[[bibliography-freebsd]]
== FreeBSD 専門の書籍

_非英語文化圏の書籍:_

* http://jdli.tw.FreeBSD.org/publication/book/freebsd2/index.htm[ FreeBSD 入門與應用] (繁体字中国語)。 http://www.drmaster.com.tw/[Drmaster] 発行, 1997. ISBN 9-578-39435-7.
* FreeBSD Unleashed (簡体字中国語訳), http://www.hzbook.com/[China Machine Press] 発行. ISBN 7-111-10201-0.
* FreeBSD From Scratch Second Edition (簡体字中国語), China Machine Press 発行. ISBN 7-111-10286-X.
* FreeBSD ハンドブック第 2 版 (簡体字中国語訳), http://www.ptpress.com.cn/[Posts & Telecom Press] 発行. ISBN 7-115-10541-3.
* FreeBSD & Windows (簡体字中国語), http://www.tdpress.com/[China Railway Publishing House] 発行. ISBN 7-113-03845-X
* FreeBSD Internet Services HOWTO (簡体字中国語), China Railway Publishing House 発行. ISBN 7-113-03423-3
* FreeBSD入門キット AT互換機版 第二版。 宮嵜忠臣 著。 秀和システム。 ISBN 4-87966-535-5 C3055 2900 円。
* ここまでできる FreeBSD パワーガイド。 霜山 滋, 仲道 嘉夫, 山中 右次 著。 秀和システム。 ISBN 4-87966-637-8 2600円。
* http://www.shoeisha.co.jp/book/Detail.asp?bid=650[ FreeBSD徹底入門]。 あさだ たくや / 天川 修平 / 衛藤 敏寿 / 浜田 直樹 / 細川 達己 / 三田 吉郎 著。 http://www.shoeisha.co.jp/[翔泳社]。 ISBN 4-88135-473-6 3600 円。
* http://www.ascii.co.jp/pb/book1/shinkan/detail/1322785.html[パーソナル UNIX スターターキット FreeBSD]。 民田 雅人 / 古場 正行 / 増田 佳泰 / 天池 健 / 宮川 晋 共著。 http://www.ascii.co.jp/[アスキー]。 ISBN 4-7561-1733-3 3000 円。
* FreeBSD ハンドブック (日本語版)。 http://www.ascii.co.jp/[アスキー]。 ISBN 4-7561-1580-2 3800 円。
* FreeBSD mit Methode (ドイツ語版)。 http://www.cul.de[Computer und Literatur Verlag]/Vertrieb Hanser 発行。1998。 ISBN 3-932311-31-0
* http://www.mitp.de/vmi/mitp/detail/pWert/1343/[ FreeBSD de Luxe] (ドイツ語), http://www.mitp.de[Verlag Modere Industrie] 発行, 2003 年。ISBN 3-8266-1343-0. 
* http://www.pc.mycom.co.jp/FreeBSD/install-manual.html[FreeBSD インストール & 活用マニュアル], http://www.pc.mycom.co.jp/[ 毎日コミュニケーションズ]発行。1998 年. ISBN 4-8399-0112-0.
* Onno W Purbo, Dodi Maryanto, Syahrial Hubbany, Widjil Widodo 著 _http://maxwell.itb.ac.id/[FreeBSD を使ったインターネットサーバの構築 (Building Internet Server with FreeBSD)]_ (インドネシア語), http://www.elexmedia.co.id/[Elex Media Komputindo] 発行。
* Absolute BSD: The Ultimate Guide to FreeBSD (繁体字中国語訳) http://www.grandtech.com.tw/[GrandTech Press] 発行 (2003 年)。ISBN 986-7944-92-5.
* http://www.twbsd.org/cht/book/[The FreeBSD 6.0 Book] (繁体字中国語), Drmaster 発行 (2006 年)。ISBN 9-575-27878-X.

_英語の書籍:_

* http://www.absoluteFreeBSD.com/[Absolute FreeBSD, 2nd Edition: The Complete Guide to FreeBSD], http://www.nostarch.com/[No Starch Press] 刊、2007 年。ISBN: 978-1-59327-151-0
* http://www.freebsdmall.com/cgi-bin/fm/bsdcomp[ The Complete FreeBSD], http://www.oreilly.com/[O'Reilly]、 2003 年。ISBN: 0596005164
* http://www.freebsd-corp-net-guide.com/[The FreeBSD Corporate Networker's Guide], http://www.awl.com/aw/[Addison-Wesley] 刊、 2000 年。ISBN: 0201704811
* http://andrsn.stanford.edu/FreeBSD/introbook/[ FreeBSD: An Open-Source Operating System for Your Personal Computer]、The Bit Tree Press 刊、2001 年。 ISBN: 0971204500
* Teach Yourself FreeBSD in 24 Hours, http://www.samspublishing.com/[Sams] 刊、 2002 年。ISBN: 0672324245
* FreeBSD 6 unleashed, http://www.samspublishing.com/[Sams] 刊、 2006 年。ISBN: 0672328755
* FreeBSD: The Complete Reference, http://books.mcgraw-hill.com[McGrawHill] 刊、 2003 年。ISBN: 0072224096

[[bibliography-userguides]]
== 利用者向けのガイド

* オハイオ州立大学による http://www.cs.duke.edu/csl/docs/unix_course/[UNIX Introductory Course]。 オンラインで HTML 版と PostScript 版が利用可能。
+ 
FreeBSD イタリア語ドキュメンテーションプロジェクトの一環 として、このドキュメントの https://www.FreeBSD.org/doc/it_IT.ISO8859-15/books/unix-introduction/index.html[イタリア語訳] が用意されています。
* http://www.jp.FreeBSD.org/[FreeBSD 友の会 jpman プロジェクト]。link:http://www.pc.mycom.co.jp/FreeBSD/urm.html[FreeBSD User's Reference Manual] (日本語訳)。 http://www.pc.mycom.co.jp/[毎日コミュニケーションズ], 1998。ISBN4-8399-0088-4 P3800E。
* http://www.ed.ac.uk/[Edinburgh University] による UNIX 環境の初心者向け http://www.ed.ac.uk/information-services/help-consultancy/is-skills/catalogue/program-op-sys-catalogue/unix1[オンラインガイド]。

[[bibliography-adminguides]]
== 管理者向けのガイド

* http://www.jp.FreeBSD.ORG/[FreeBSD 友の会 jpman プロジェクト]。link:http://www.pc.mycom.co.jp/FreeBSD/sam.html[FreeBSD System Administrator's Manual] (日本語訳)。 http://www.pc.mycom.co.jp/[毎日コミュニケーションズ], 1998. ISBN4-8399-0109-0 P3300E.
* Dreyfus, Emmanuel. http://www.eyrolles.com/Informatique/Livre/9782212114638/[Cahiers de l'Admin: BSD] 第 2 版。(フランス語、「管理者ノート」)、Eyrolles, 2004. ISBN 2-212-11463-X

== プログラマ向けのガイド

* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Reference Manual_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-078-3
* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Supplementary Documents_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-079-1
* Harbison, Samuel P. and Steele, Guy L. Jr. _C: A Reference Manual_. 4th Ed. Prentice Hall, 1995. ISBN 0-13-326224-3 (訳注: 邦訳は以下のものが出版されています。 斎藤 信男監訳。 _新・詳説 C 言語リファレンス [H&Sリファレンス]_。 ソフトバンク, 1994。 ISBN 4-89052-506-8 原本は第 4 版だが, 訳出は第 3 版のみ。)
* Kernighan, Brian and Dennis M. Ritchie. _The C Programming Language_. 2nd Ed. PTR Prentice Hall, 1988. ISBN 0-13-110362-8 (訳注: 邦訳は以下のものが出版されています。 石田 晴久 訳。 _プログラミング言語 C 第 2 版(訳書訂正版)_ 共立出版, 1989。 ISBN 4-320-02692-6)
* Lehey, Greg. _Porting UNIX Software_. O'Reilly & Associates, Inc., 1995. ISBN 1-56592-126-7
* Plauger, P. J. _The Standard C Library_. Prentice Hall, 1992. ISBN 0-13-131509-9 (訳注: 邦訳は以下のものが出版されています。 福富 寛 / 門倉 明彦 / 清水 恵介 訳。 _標準 C ライブラリ ANSI/ISO/JIS C規格_. トッパン, 1995。 ISBN 4-8101-8541-9)
* Spinellis, Diomidis. http://www.spinellis.gr/codereading/[Code Reading: The Open Source Perspective]. Addison-Wesley, 2003. ISBN 0-201-79940-5
* Spinellis, Diomidis. http://www.spinellis.gr/codequality/[Code Quality: The Open Source Perspective]. Addison-Wesley, 2006. ISBN 0-321-16607-8
* Stevens, W. Richard and Stephen A. Rago. _Advanced Programming in the UNIX Environment_. 2nd Ed. Reading, Mass. : Addison-Wesley, 2005. ISBN 0-201-43307-9 (訳注: 第 1 版の邦訳は以下のものが出版されています。 大木 敦雄 訳。 _詳解 UNIX プログラミング_。トッパン, 1994。 ISBN 4-89052-524-6)
* Stevens, W. Richard. _UNIX Network Programming_. 2nd Ed. PTR Prentice Hall, 1998. ISBN 0-13-949876-1 (訳注: 第 1 版の邦訳は以下のものが出版されています. 篠田 陽一 訳. _UNIX ネットワークプログラミング_。 トッパン, 1992. ISBN 4-8101-8509-5) 第 2 版の邦訳は以下のものが出版されています。 篠田 陽一 訳. _UNIX ネットワークプログラミング 第 2 版 Vol.1_。 トッパン, 1999。 ISBN 4-8101-8612-1)

== オペレーティングシステム内部

* Andleigh, Prabhat K. _UNIX System Architecture_. Prentice-Hall, Inc., 1990. ISBN 0-13-949843-5
* Jolitz, William. "Porting UNIX to the 386". _Dr. Dobb's Journal_. January 1991-July 1992.
* Leffler, Samuel J., Marshall Kirk McKusick, Michael J Karels and John Quarterman _The Design and Implementation of the 4.3BSD UNIX Operating System_. Reading, Mass. : Addison-Wesley, 1989. ISBN 0-201-06196-1 (訳注: 邦訳は以下のものが出版されています。 中村 明 / 相田 仁 / 計 宇生 / 小池 汎平 訳。 _UNIX 4.3BSDの設計と実装_。丸善, 1991。 ISBN 4-621-03607-6)
* Leffler, Samuel J., Marshall Kirk McKusick, _The Design and Implementation of the 4.3BSD UNIX Operating System: Answer Book_. Reading, Mass. : Addison-Wesley, 1991. ISBN 0-201-54629-9 (訳注: 邦訳は以下のものが出版されています。 相田 仁 / 計 宇生 / 小池 汎平 訳。 _UNIX 4.3BSDの設計と実装_。 アンサーブック, トッパン, 1991。 ISBN 4-8101-8039-5)
* McKusick, Marshall Kirk, Keith Bostic, Michael J Karels, and John Quarterman. _The Design and Implementation of the 4.4BSD Operating System_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-54979-4
+ 
(この本の第二章が FreeBSD ドキュメンテーションプロジェクト の一部として link:{design-44bsd}[オンライン] で公開されています。)
* Marshall Kirk McKusick, George V. Neville-Neil _The Design and Implementation of the FreeBSD Operating System_. Boston, Mass. : Addison-Wesley, 2004. ISBN 0-201-70245-2
* Marshall Kirk McKusick, George V. Neville-Neil, Robert N. M. Watson _The Design and Implementation of the FreeBSD Operating System, 2nd Ed._. Westford, Mass. : Pearson Education, Inc., 2014. ISBN 0-321-96897-2
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 1: The Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63346-9
* Schimmel, Curt. _Unix Systems for Modern Architectures_. Reading, Mass. : Addison-Wesley, 1994. ISBN 0-201-63338-8
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 3: TCP for Transactions, HTTP, NNTP and the UNIX Domain Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63495-3 (訳注: 邦訳は以下のものが出版されています。 中本 幸一 / 石川 裕次 / 田中 伸佳 訳。 _詳解 TCP/IP Vol.3: トランザクション TCP, HTTP, NNTP, UNIX ドメインプロトコル_, アジソンウェスレイパブリッシャーズジャパン, 1998。 ISBN 4-8101-8039-5)
* Vahalia, Uresh. _UNIX Internals -- The New Frontiers_. Prentice Hall, 1996. ISBN 0-13-101908-2 (訳注: 邦訳は以下のものが出版されています。 徳田 英幸 / 中村 明 / 戸辺 義人 / 津田 悦幸 訳。 _最前線UNIXのカーネル_, ピアソンエデュケーション, 2000。 ISBN 4-89471-189-3)
* Wright, Gary R. and W. Richard Stevens. _TCP/IP Illustrated, Volume 2: The Implementation_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63354-X
* Messmer, Hans-Peter. _The Indispensable PC Hardware Book_, 4th Ed. Reading, Mass : Addison-Wesley Pub. Co., 2002. ISBN 0-201-59616-4

== セキュリティの参考資料

* Cheswick, William R. and Steven M. Bellovin. _Firewalls and Internet Security: Repelling the Wily Hacker_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63357-4 (訳注: 邦訳は以下のものが出版されています。 川副 博 監訳。_ファイアウォール_。 ソフトバンク, 1995。 ISBN 4-89052-672-2)
* Garfinkel, Simson. _PGP Pretty Good Privacy_ O'Reilly & Associates, Inc., 1995. ISBN 1-56592-098-8

[[bibliography-hardware]]
== ハードウェアの参考資料

* Anderson, Don and Tom Shanley. _Pentium Processor System Architecture_. 2nd Ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40992-5
* Ferraro, Richard F. _Programmer's Guide to the EGA, VGA, and Super VGA Cards_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-62490-7
* Intel Corporation は、自社の CPU やチップセットに関する文書を自社の http://developer.intel.com/[開発者向け Web サイト] で公開しています。文書のフォーマットは通常 PDF です。
* Shanley, Tom. _80486 System Architecture_. 3rd Ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40994-1
* Shanley, Tom. _ISA System Architecture_. 3rd Ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40996-8
* Shanley, Tom. _PCI System Architecture_. 4th Ed. Reading, Mass. : Addison-Wesley, 1999. ISBN 0-201-30974-2
* Van Gilluwe, Frank. _The Undocumented PC_, 2nd Ed. Reading, Mass: Addison-Wesley Pub. Co., 1996. ISBN 0-201-47950-8

[[bibliography-history]]
== UNIX(R) の歴史

* Lion, John _Lion's Commentary on UNIX, 6th Ed. With Source Code_. ITP Media Group, 1996. ISBN 1573980137
* Raymond, Eric s. _The New Hacker's Dictionary, 3rd edition_. MIT Press, 1996. ISBN 0-262-68092-0 これは http://www.catb.org/~esr/jargon/html/index.html[ジャーゴンファイル (Jargon File)] として知られています。
* Saulus, Peter H. _A quarter century of UNIX_. Addison-Wesley Publishing Company, Inc., 1994. ISBN 0-201-54777-5
* Simon Garfinkel, Daniel Weise, Steven Strassmann. _The UNIX-HATERS Handbook_. IDG Books Worldwide, Inc., 1994. ISBN 1-56884-203-1. 絶版となりましたが、link:http://www.simson.net/ref/ugh.pdf[オンライン] で入手できます。
* Don Libes, Sandy Ressler _Life with UNIX_ - special edition. Prentice-Hall, Inc., 1989. ISBN 0-13-536657-7 (訳注: 邦訳は以下のものが出版されています。 坂本 文 監訳. _Life with UNIX_. アスキー, 1990。 ISBN 4-7561-0783-4 邦訳が Special 版の訳出か否かは不明)
* _BSD 系 OS の系譜図_。 https://svnweb.freebsd.org/base/head/shared/misc/bsd-family-tree?view=co[https://svnweb.freebsd.org/base/head/shared/misc/bsd-family-tree?view=co] か、もしくは、FreeBSD マシンにある link:file://localhost/usr/shared/misc/bsd-family-tree[/usr/shared/misc/bsd-family-tree]。
* _Networked Computer Science Technical Reports Library_. http://www.ncstrl.org/[http://www.ncstrl.org/]
* _Computer Systems Research group (CSRG) からの古い BSD リリース集_。link:http://www.mckusick.com/csrg/[http://www.mckusick.com/csrg/]: この 4 枚 CD セットには、1BSD から 4.4BSD までと 4.4BSD-Lite2 が含まれます (残念ながら 2.11BSD は含まれていません)。 また 4 枚目の CD には、最終ソースおよび SCCS ファイルが含まれています。
* Kernighan, Brian _Unix: A History and a Memoir_.  Kindle Direct Publishing, 2020.  ISBN 978-169597855-3

[[bibliography-journals]]
== 定期刊行物、雑誌およびジャーナル

* http://www.admin-magazin.de/[Admin Magazin] (in German), published by Medialinx AG. ISSN: 2190-1066
* http://www.bsdmag.org/[BSD Magazine], published by Software Press Sp. z o.o. SK. ISSN: 1898-9144
* http://www.bsdnow.tv/[BSD Now - Video Podcast], published by Jupiter Broadcasting LLC
* http://bsdtalk.blogspot.com/[BSD Talk Podcast], by Will Backman
* http://freebsdjournal.com/[FreeBSD Journal], published by S&W Publishing, sponsored by The FreeBSD Foundation. ISBN: 978-0-615-88479-0
