# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/news/status/Makefile,v 1.1 2004/04/09 11:16:09 phantom Exp $
# Original revision: 1.23

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	status.xml

INDEXLINK=	status.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
