# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/commercial/Makefile,v 1.3 2000/11/10 17:04:48 phantom Exp $
# Original revision: 1.14

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS = 	commercial.xml
# DOCS+=  consulting.xml
# DOCS+=  consulting_bycat.xml
# DOCS+=  hardware.xml
# DOCS+=  misc.xml
# DOCS+=  software.xml
# DOCS+=  software_bycat.xml

INDEXLINK=commercial.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
