# The FreeBSD Simplified Chinese Project
#
# Original Revision: 1.5
# $FreeBSD$
#
# Article: Setting up a CVS repository - the FreeBSD way

MAINTAINER= stijn@win.tue.nl

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
