#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/FAQ/Makefile,v 1.3 2003/12/13 11:16:34 andy Exp $
#
# Original revision: 1.8
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   index.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
