---
title: "FreeBSD Advocacy Project"
sidenav: about
---

include::shared/en/urls.adoc[]

= FreeBSD Advocacy Project

Much of FreeBSD's success comes from users advocating to their friends, colleagues, and employers.

== Mailing lists

* https://lists.freebsd.org/subscription/freebsd-advocacy[FreeBSD advocacy mailing list]

== Web resources

* link:../status[FreeBSD quarterly status reports]
+
Details of activities within and surrounding FreeBSD.

* link:whyusefreebsd[Why use FreeBSD?]
+
Users explain why FreeBSD should be used.

* link:myths[*BSD myths]
+
Describes and debunks some of the mythology.

* link:../press[FreeBSD in the press]
+
Links to articles.

== Sites using FreeBSD

Organisations, products and services that make use of FreeBSD are https://freebsdfoundation.org/freebsd-project/what-is-freebsd/[shortlisted by the FreeBSD Foundation]. 

== FreeBSD conferences

* https://www.bsdcan.org/[BSDCan], the annual BSD Conference held in Ottawa, Canada.
* https://www.eurobsdcon.org/[EuroBSDCon], the annual BSD Conference in Europe.
* https://asiabsdcon.org/[AsiaBSDCon], the annual BSD Conference held in Asia.
