---
title: "Projet FreeBSD/ARM"
sidenav: developers
---

include::shared/authors.adoc[]
include::shared/fr/urls.adoc[]

= Projet FreeBSD/ARM

FreeBSD/ARM est un port de FreeBSD destiné à fonctionner sur l'architecture et le matériel ARM. Le but du projet est de fournir un support pour l'architecture et le matériel qui le concerne.

== Notes matérielles sur FreeBSD/ARM

Acuellement, FreeBSD devrait fonctionner sur les cartes de développement Intel basées sur l'i80321, dont les cartes IQ31244 et IQ80321. Le support reste minimal, couvrant uniquement le CPU, le bus PCI-X, les cartes Ethernet em(4), l'UART et le timer.

Un support minimal du CPU StrongARM 1100 est fourni, mais uniquement dans les limites de ce que Simics émule : le CPU, l'UART et l'horloge. Il est théoriquement possible de booter sur la carte Assabet, que Simics emule; aucune tentative, fructueuse ou infructueuse, n'a été rapportée.

== Ce qui doit être fait

* Le support SATA doit être ajouté.
* D'autres périphériques, comme le watchdog, l'i2c et le bus doivent être importés de NetBSD.

== Liens relatifs à FreeBSD/ARM

* http://tisu.mit.jyu.fi/embedded/TIE345/luentokalvot/Embedded_3_ARM.pdf[Brève histoire de ARM]
* http://www.netbsd.org/Ports/arm32/[Projet NetBSD Arm/32]

== Guide de mini-installation

{cognet} a écrit un guide de mini-installation à partir des sources de FreeBSD -current. Il est http://people.freebsd.org/~cognet/freebsd_arm.txt[disponible ici].

[[list]]
== Liste de diffusion FreeBSD/ARM

Pour s'inscrire à cette liste, envoyez un courrier électronique à `<freebsd-arm-subscribe@FreeBSD.org>` ou utilisez http://lists.FreeBSD.org/mailman/listinfo/freebsd-arm[l'interface mailman].

== Ce que disent les musiciens au sujet de FreeBSD/ARM

Avec FreeBSD/ARM, vous pouvez apprécier le silence de votre ordinateur (système embarqué). Il existe même une chanson à ce sujet, "Enjoy The Silence", par Depeche Mode:

....
All I ever wanted
All I ever needed
Is here in my ARMs
Words are very unnecessary
They can only do harm
....
