---
title: "Projet FreeBSD/i386"
sidenav: developers
---

include::shared/fr/urls.adoc[]
include::shared/releases.adoc[]

= Projet FreeBSD/i386

[[intro]]
== Introduction

Cette page contient des informations concernant la plateforme FreeBSD/i386. Cette architecture supporte une grande gamme de processeurs puisque la plupart des particuliers achètent ces machines. Si vous avez une machine provenant d'un gros fabricant de PC (comme Dell(TM), HP, eMachines(R)) il y a des chances que vous ayez un processeur AMD(TM) ou Intel(R) et que vous soyez donc dans cette catégorie.

[[toc]]
== Table des matières

* <<news,Dernières Nouvelles>>
* <<hw,Matériel supporté>>
* <<links,Autres liens intéressants]>>

[[news]]
== Dernières Nouvelles

* FreeBSD 6.0 et versions suivantes ne supportent plus les machines à base de processeur Intel 80386; ces ordinateurs ont plus de sept ans et ne sont supportés que par les versions 5.X et antérieures. Veuillez noter que le noyau GENERIC ne supporte les processeurs 80386 que dans les versions 4.X et antérieures.

[[hw]]
== Matériel supporté

Une liste des processeurs supportés peut être trouvée dans les link:https://www.FreeBSD.org/releases/{rel120-current}R/hardware-i386.html[Notes de compatibilité matérielle FreeBSD/i386]

[[links]]
== Autres liens intéressants

* http://laptop.bsdgroup.de/freebsd/[Liste de compatibilité des portables sous FreeBSD]
* link:https://wiki.FreeBSD.org/ACPI[Page du Projet ACPI]
