---
title: "Projet FreeBSD/PPC"
sidenav: developers
---

include::shared/releases.adoc[]
include::shared/fr/urls.adoc[]

= Projet FreeBSD/PPC

== Informations générales

* <<intro,Introduction>>
* <<news,Dernières nouvelles>>
* <<faq,Foire aux questions>>
* <<hardware,Matériel supporté>>
* <<list,Liste de diffusion FreeBSD/ppc>>
* <<issues,Problèmes connus>>
* <<doc,Documentation, publications et outils divers>>
* <<links,Autres liens d'interêt>>

[[intro]]
== Introduction

Les pages du Projet FreeBSD/ppc contiennent des informations sur le portage de FreeBSD sur l'architecture PowerPC(R). Comme le portage lui même, ces pages sont un travail en cours.

Le portage FreeBSD/ppc est toujours une plate-forme Tier-2. Cela veut dire qu'il n'est pas totalement supporté par notre officier de sécurité, par l'équipe de sortie des nouvelles versions de FreeBSD et les mainteneurs de la chaîne de compilation.

'''''

[[news]]
== Dernières nouvelles

* *25 Juin, 2005*: Cette page a été significativement mise à jour

'''''

[[faq]]
== Foire aux questions

. <<one,Comment installer FreeBSD/ppc?>>
. <<two,Où trouver des paquetages pour FreeBSD/ppc?>>
. <<three,Comment utiliser les logiciels portés sous FreeBSD/ppc?>>
. <<four,Qui contacter en cas de problème?>>

[[one]]
=== Comment installer FreeBSD/ppc?

Des images ISO 7.0-CURRENT sont disponibles au téléchargement à cette http://people.freebsd.org/~grehan/ppc_iso[adresse]. La dernière version est disponible http://people.freebsd.org/~grehan/ppc_iso/latest.iso[ici]. Suivez les instructions données http://people.freebsd.org/~grehan/iso_install.txt[ici].

[[two]]
=== Où trouver des paquetages pour FreeBSD/ppc?

Grâce à Peter Grehan et Tilman Linneweh, vous pouvez trouver quelques paquetages http://people.freebsd.org/~grehan/ppc_pkgs/[ici] et http://people.freebsd.org/~arved/packages_powerpc/[ici]. Notez que ces paquetages ne sont pas à jour. Si possible, vous devriez plutôt utiliser les ports.

[[three]]
=== Comment utiliser les logiciels portés sous FreeBSD/ppc?

La façon la plus simple d'utiliser les logiciels portés sous FreeBSD depuis 6.0-RELEASE est d'utiliser portsnap. Consultez le Manuel de référence si vous avez besoin d'aide pour link:{handbook}#ports-using[utiliser le catalogue des logiciels portés].

[[four]]
=== Qui contacter en cas de problème?

mailto:grehan@FreeBSD.org[Peter Grehan] est le responsable du portage. Contactez le si vous pouvez participer au portage. Si vous voulez juste connaître le status du projet, consultez cette page régulièrement ou inscrivez vous à <<list,la liste de diffusion FreeBSD/ppc>>.

'''''

[[hardware]]
== Matériel supporté

Le portage FreeBSD/ppc devrait fonctionner sur n'importe quelle machine de type New-World. FreeBSD fonctionne sur les machines suivantes:

[.tblbasic]
[cols=",,,",options="header",]
|===
|Fabricant |Modèle |Contact (liens optionnels) |Notes
|Apple |iMac G3 350 MHz |mailto:diskiller@diskiller.net[Martin Minkus] |Rage 128VR
|Apple |iMac G3 DV Special Edition |mailto:webmaster@machowto.com[David S. Besade] (http://people.freebsd.org/~flz/local/dmesg.ppc[dmesg]) |Aucune
|Apple |iMac G3 Revision B |mailto:grehan@FreeBSD.org[Peter Grehan] |Rage 3D Pro 215GP, accel disabled
|Apple |eMac 700 MHz |mailto:grehan@FreeBSD.org[Peter Grehan] |Nvidia GeForce2 MX
|Apple |Mac Mini G4 1.4 GHz |mailto:arved@FreeBSD.org[Tilman Linneweh] (http://people.freebsd.org/~arved/stuff/minimac[dmesg]) |Aucune
|Apple |Powerbook G4 1.33 GHz |mailto:grehan@FreeBSD.org[Peter Grehan] |Nvidia GeForce G5200
|Apple |Aluminium Powerbook G4 1.5 GHz |mailto:toa@pop.agri.ch[Andreas Tobler] |None
|===

'''''

[[list]]
== Liste de diffusion de FreeBSD/ppc

Pour vous inscrire à cette liste, envoyez un courrier à freebsd-ppc-subscribe@FreeBSD.org ou visitez http://lists.FreeBSD.org/mailman/listinfo/freebsd-ppc[l'interface mailman].

'''''

[[issues]]
== Problèmes connus

* Pas de support AltiVec pour le moment.
* Les contrôleurs intégrés BMAC+ ne fonctionnent pas. Un pilote de périphérique bm(4) en cours d'écriture est disponible sur la page personnelle de Peter Grehan http://people.freebsd.org/~grehan/[ici] (if_bm.c et if_bmreg.h).
* Le curseur de la souris n'apparaît pas en mode console.
* Fdisk ne fonctionne pas.
* Seulement les claviers USB sont supportés.
* Si vous avez du Bluetooth, il y a un faux port OHCI et les périphériques créés peuvent être utilisés pour accéder à un clavier ou à une souris sans-fil. Le problème est qu'il est détecté avant les clavier/souris fixes. Pour eviter ceci, l'emplacement PCI associé avec le périphérique ohci2 problématique peut être désactivé au chargement:
+
....
OK set hint.pcib.1.skipslot=26
....
* Pour les machines à base de cartes graphiques ATI Radeon:
** Une vérification d'intervalle syscons doit être désactivée avec le paramêtre sysctl hw.ofwfb.relax_mmap.
** Un http://people.freebsd.org/~grehan/radeon_driver.c[pilote] spécial pour radeon est nécessaire. Vous devez ajouter ceci dans votre fichier xorg.conf dans la section Device:
+
....
Option "iBookHacks" "on"
....
* Il y a un problème connu avec le chargeur d'amorçage (boot-loader) qui empêche de charger un autre noyau, ce qui fait que tester votre propre noyau est un peu risqué. Quand vous arrivez à l'invite d'Open Firmware, donnez lui le nom d'une partition qui n'existe pas, qui n'a pas de noyau à charger, ou qui n'est pas une partition UFS:
+
....
0 > boot hd:loader hd:0
....
+
A ce moment vous pouvez changer la valeur de currdev et charger manuellement votre noyau:
+
....
OK set currdev=hd:14
OK load /boot/kernel/kernel.save
....

'''''

[[doc]]
== Documentation, publication et outils divers

* http://e-www.motorola.com/brdata/PDFDB/docs/MPCFPE32B.pdf[Documentation processeur PowerPC]
* http://www.firmworks.com/QuickRef.html[Référence rapide Open Firmware]
* http://developer.apple.com/technotes/tn/tn1061.html["TN1061: Principes fondamentaux d'Open Firmware, Partie 1 - L'interface utilisateur"]
* http://developer.apple.com/technotes/tn/tn1062.html["TN1062: Principes fondamentaux d'Open Firmware, Partie 2 - L'arbre des périphériques"]
* http://developer.apple.com/techpubs/hardware/hardware2.html[Documentations pour le développeur de matériel Apple]
* http://developer.apple.com/technotes/tn/tn2004.html["TN2004: Debogguer Open Firmware en utilisant telnet"]
* http://developer.apple.com/technotes/tn/tn2023.html["TN2023: Debogguer Open Firmware par Ethernet II - Téléchargement via telnet"]
* http://developer.apple.com/technotes/tn/tn2001.html["TN2001: Lancer des applications depuis un disque dur dans Open Firmware"]
* http://sourceware.cygnus.com/psim/[psim] - Un simulateur PowerPC, disponible dans le catalogue des logiciel portés sur FreeBSD: http://www.freshports.org/?package=psim-freebsd[emulators/psim-freebsd]

[[links]]
== Autres liens d'interêt

* http://wiki.freebsd.org/moin.cgi/powerpc[Page du Projet FreeBSD/ppc sur le wiki]
* http://lists.freebsd.org/pipermail/freebsd-ppc/2005-January/000814.html[Description de Garance A. Drosehn sur l'installation de FreeBSD sur un Mac Mini]
* http://www.NetBSD.org/Ports/macppc/[Projet NetBSD/macppc]
* http://www.OpenBSD.org/macppc.html[Projet OpenBSD/macppc]
