---
title: "Projet FreeBSD/Sparc64"
sidenav: developers
---

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/fr/urls.adoc[]

= Projet FreeBSD/Sparc64

[[intro]]
== Introduction

Cette page contient des informations à propos du port de FreeBSD sur systèmes UltraSPARC(R) de Sun Microsystem. Ultrasparc est une link:{committers-guide}#archs[plateforme de niveau 1], et est donc totalement supportée par le projet link:https://www.FreeBSD.org/fr/[FreeBSD]. Néanmoins, le port n'est pas aussi mature que les ports i386 et amd64 existants. Les discussions à propos du port UltraSPARC ont lieu sur la liste de diffusion http://lists.freebsd.org/mailman/listinfo/freebsd-sparc64[freebsd-sparc].

[[toc]]
== Table Des Matières

* <<who,Crédits>>
* <<news,Dernières Nouvelles>>
* <<hw,Matériel Supporté>>
* <<todo,Ce qu'il reste à faire>>
* <<links,Liens Intéressants>>

[[who]]
== Crédits

Les personnes suivantes ont travaillé à l'avant-scène ou à l'arrière-scène pour donner naissance au port FreeBSD:

* {jake}
* {tmm}
* {obrien}

[[news]]
== Dernières Nouvelles

* *25 Octobre 2004*: Le pilote audio CS4231 a été porté de http://www.OpenBSD.org/[OpenBSD], donc les stations de travail SBus équipées de matériel audio (Ultra 1E, Ultra 2) gagnent le support du son.
* *9 Octobre 2004*: Le pilote auxio a été porté de http://www.NetBSD.org/[NetBSD].
* *10 Juin 2004*: Le pilote esp a été importé de http://www.NetBSD.org/[NetBSD], donc les machines Ultra 1E et Ultra 2 gagnent le support SCSI.
* *18 Janvier 2003*: Le pilote if_xl est http://docs.FreeBSD.org/cgi/mid.cgi?200301190023.h0J0Nx0N068255[maintenant] supporté dans -CURRENT.
* *10 Décembre 2002*: Des instantanés quotidiens de 5.0-CURRENT sont maintenant disponibles sur ftp://ftp2.FreeBSD.org/pub/FreeBSD/snapshots/sparc64[ftp2.FreeBSD.org].

[[hw]]
== Matériel Supporté

Une liste des systèmes supportés suit ci-après. Le support SMP fonctionne sur tous les systèmes supportés qui ont plus d'1 processeur. Pour plus de détails, veuillez vous reporter aux link:https://www.FreeBSD.org/releases/{rel120-current}R/hardware-sparc64.html[notes matérielles] de la link:../../releases/[version] que vous utilisez.

* Blade 100
* Blade 150
* Enterprise 220R
* Enterprise 250
* Enterprise 420R
* Enterprise 450
* Fire V100
* Fire V120
* Netra(TM) T1 105
* Netra T1 AC200/DC200
* Netra t 1100
* Netra t 1120
* Netra t 1125
* Netra t 1400/1405
* Netra 120
* Netra X1
* SPARCEngine(R) Ultra Axi
* SPARCEngine Ultra AXmp
* Ultra 1E
* Ultra 2
* Ultra(TM) 5
* Ultra 10
* Ultra 30
* Ultra 60
* Ultra 80

Les systèmes suivants sont supportés, mais ne peuvent démarrer qu'à partir d'un réseau à cause du contrôleur SCSI intégré qui n'est pas supporté. Un travail est en cours pour ajouter le support de ce contrôleur SCSI. Ces systèmes pourraient peut-être marcher avec le pilote esp importé de http://www.NetBSD.org[NetBSD].

* Enterprise 3500
* Enterprise 4500

Les systèmes suivants ne sont pas supportés.

* Tout système avec un processeur UltraSPARC III ou supérieur.
* Ultra 1

Un système non présent ici et qui n'a pas de processeur UltraSPARC III ou supérieur est sensé fonctionner, mais n'a peut-être pas été testé. Si vous avez un tel système, veuillez l'essayer, et faites mailto:freebsd-sparc@FreeBSD.org[nous] le savoir.

[[todo]]
== Ce qu'il reste à faire

* Mettre à jour cette page plus souvent.

[[links]]
== Liens Intéressants

* http://www.sun.com/processors/manuals/[Manuels des Utilisateurs pour processeurs UltraSPARC]
* http://www.sparc.org/standards.html[Documents Standards SPARC]
* http://www.netbsd.org/Ports/sparc64/[NetBSD/sparc64]
* http://www.openbsd.org/sparc64.html[OpenBSD/sparc64]
