---
title: "Projet FreeBSD/sun4v"
sidenav: developers
---

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/fr/urls.adoc[]

= Projet FreeBSD/sun4v

[[intro]]
== Introduction

Cette page contient les informations sur le portage de FreeBSD pour l'architecture UltraSPARC-T1(R) de Sun Microsystem. Les discussions sur le portage pour UltraSPARC-T1 ont lieu sur la liste de diffusion http://lists.freebsd.org/mailman/listinfo/freebsd-sun4v[freebsd-sun4v].

[[toc]]
== Sommaire

* <<who,Crédits>>
* <<news,Dernières nouvelles>>
* <<hw,Liste du matériel supporté>>
* <<todo,Ce qui doit être fait>>
* <<links,Liens intéressants>>

[[who]]
== Crédits

Les personnes suivantes ont oeuvré soit au devant de la scène soit dans l'ombre à l'émergence de ce portage FreeBSD:

* {kmacy}
* {jb}

[[news]]
== Dernières nouvelles

* *13 Novembre 2006*: La partie gestion de la date et de l'horloge est terminée.
* *12 Novembre 2006*: La toute première image ISO d'installation et de CD live peut être téléchargée ici: http://people.freebsd.org/~jb/sun4v/7.0-20061112-SNAP-sun4v-disc1.iso.bz2[7.0-20061112-SNAP-sun4v-disc1.iso.bz2].
+
Vous remarquerez un certain nombre de dépassements des délais d'attente du pilote de périphérique acd0 lors du démarrage. Cela sera corrigé dans une version ultérieure. Pour le moment soyez juste patient.
+
Pour utiliser le CD live, utilisez le menu "Fixit". Notez bien que c'est un instantané, il y aura donc un avertissement concernant le fait que la version ne correspond pas à la 7.0-CURRENT.

[[hw]]
== Liste du matériel supporté

Un résumé des systèmes supportés est donné ci-dessous. Le SMP est supporté sur tous les systèmes de cette liste.

* http://www.sun.com/servers/coolthreads/t1000/[Sun Fire T1000 Server]
* http://www.sun.com/servers/coolthreads/t2000/[Sun Fire T2000 Server]

[[todo]]
== Ce qui doit être fait

* La répartition de la charge des interruptions entre microprocesseurs.
* Ajout du support pour le port série.
* La réinitialisation du système et la sortie vers l'OFW doivent être implémentées (utilisation du pilote sc pour la réinitialisation).

[[links]]
== Liens intéressants

* http://www.sun.com/processors/documentation.html[la documentation du processeur UltraSPARC]
* http://www.opensparc.net/[le site d'OpenSPARC]
