---
title: "Projet FreeBSD/xbox"
sidenav: developers
---

include::shared/authors.adoc[]

= Projet FreeBSD/xbox

== Introduction

FreeBSD/xbox est un portage de FreeBSD sur architecture Microsoft(R) Xbox(R). Ce projet a été lancé par {rink}, qui a produit les patches et le code. mailto:ed@fxq.nl[Ed Schouten] l'a aidé en relisant les patches et a fourni des détails sur certains mécanismes internes de Xbox.

== Statut

FreeBSD/xbox est supporté sur FreeBSD 6-STABLE et FreeBSD 7-CURRENT. Le framebuffer, l'Ethernet, le son et les périphériques USB (comme le clavier USB pour la console) sont tous supportés.

Afin d'aider les utilisateurs à installer FreeBSD/xbox, un CD live/d'installation a été http://lists.freebsd.org/pipermail/freebsd-stable/2006-August/027894.html[créé]. Il est disponible ftp://ftp.stack.nl/pub/freebsd-xbox/[ici].

== Démarrer sur des noyaux FreeBSD-CURRENT

Pour démarrer sur FreeBSD 7-CURRENT du dépôt CVS, vous devez avoir la dernière version du BIOS Linux/xbox, appelé Cromwell (sinon votre noyau plantera juste après son chargement). Un Cromwell avec les correctifs UFS FreeBSD (ceci permet de charger un noyau à partir d'un système de fichier UFS) est disponible dans le catalogue des logiciels portés dans /usr/ports/sysutils/cromwell; il peut être flashé dans l'EEPROM avec l'utilitaire /usr/ports/sysutils/raincoat (si votre Xbox a une version inférieure à 1.6).

*Note*: Plusieurs lecteurs d'Xbox sont connus pour refuser certains types de supports. Si vous faites l'expérience de blocages aléatoires, de panique ou de corruption des données lors de l'installation, essayez avec un DVD ou un CD connu pour fonctionner avec le lecteur.

== Installer sur le disque dur

Vous pouvez procéder à l'installation à partir du Live CD, mais vous devrez tout faire à la main. Il vaut mieux préparer votre disque dur à partir d'une installation FreeBSD/i386, puis changer le fichier de configuration /boot/xboxlinux.cfg, pour que Cromwell sache quel noyau charger.

== Liens

* http://www.xbox-linux.org/[Le projet Linux Xbox]
* http://www.xbox-bsd.nl/[Le projet FreeBSD/xbox]
