# $FreeBSD: www/en/releases/9.0R/Makefile,v 1.1 2011/07/10 17:12:24 hrs Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml

DATA=	docbook.css \
	hardware.html \
	readme.html \

.include "${WEB_PREFIX}/share/mk/web.site.mk"
