# $FreeBSD: www/en/releases/9.0R/Makefile,v 1.2 2012/01/06 05:19:59 hrs Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml

DATA=	docbook.css \
	hardware.html \
	readme.html \
	installation.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
