---
title: 章 30. 防火牆
part: 部 IV. 網路通訊
prev: books/handbook/network-servers
next: books/handbook/advanced-networking
showBookMenu: true
weight: 35
params:
  path: "/books/handbook/firewalls/"
---

[[firewalls]]
= 防火牆
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 30
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/firewalls/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[firewalls-intro]]
== 概述

防火牆能夠過濾透過系統內送 (Incoming) 與外發 (Outgoing) 的流量，防火牆可使用一組或多組 "規則 (Rules)" 來檢查網路連線中進出的網路封包(Network packets)，並且能允許或阻擋其通過。 而防火牆規則可以檢查封包中一個或數個特徵，例如通訊協定類型、來源或目的主機位址，以及來源及目地的連接埠 (Port)。

防火牆可以加強主機或網路的安全性，它可以用來完成下列事情：

* 保護並隔離內部網路的應用程式、服務與主機，避免來自網際網路不必要的存取。
* 限制或者禁止內部網路的主機存取網際網路服務。
* 支援網路位址轉譯 (Network address translation, NAT)，可允許內部網路使用私有 IP 位址並共用一個連線使用一個 IP 位址連到網際網路或者自動分配一個共用池當中的公開位址。

FreeBSD 有三種內建於基礎系統的防火牆：PF, IPFW 與 IPFILTER 即 IPF。FreeBSD 也提供了兩種流量限制程式 (Traffic shaper) 來控制頻寬的用量：man:altq[4] 與 man:dummynet[4]，ALTQ 一般配合 PF 使用，而 dummynet 會配合 IPFW。每一種防火牆都會使用規則來管制來自與送往 FreeBSD 的封包，儘管它們用不同的方式運作且有不同的規則語法。

FreeBSD 提供多個防火牆是為了滿足不同的需求與各種使用者的偏好，每位使用者應評估那一種防火牆最能滿足其需求。

讀完這章，您將了解：

* 如何定義封包過濾規則。
* FreeBSD 內建防火牆之間的差異。
* 如何使用與設定 PF 防火牆。
* 如何使用與設定 IPFW 防火牆。
* 如何使用與設定 IPFILTER 防火牆。

在開始閱讀這章之前，您需要：

* 了解 FreeBSD 基礎及網路概念。

[NOTE]
====
由於所有防火牆均是以監控所選封包的控制欄位值為基礎運作，所以防火牆規則集的建立者必須很明白 TCP/IP 是如何運作的，在封包的控制欄位中會有那些數值，這些數值會被如何用在一般的連線階段，要了解更多相關資訊，可參考 http://www.ipprimer.com[Daryl's TCP/IP Primer]。
====

[[firewalls-concepts]]
== 防火牆概念

一個規則集 (Ruleset) 中會有一群根據封包內的資料來判斷通過或封鎖的規則，主機間雙向的封包交換構成一個連線階段的對話，防火牆規則集會同時處理接收自網際網路的封包以及由系統所產生的回應封包，每一個 TCP/IP 服務都會預先定義其通訊協定以及要傾聽的埠，要送往指定服務的封包會誕生在來源位址，使用一個不需特殊權限的埠並傳送給目標位址上特定服務的埠，所有上述過程中的參數均可用來當做建立規則的篩選條件，來允許或封鎖服務。

要查詢一個不清楚的埠號，可參考 [.filename]#/etc/services#，或者至 http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers[http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers] 查詢埠號來找出特定埠號的用途。

查看這個連結來了解有 http://web.archive.org/web/20150803024617/http://www.sans.org/security-resources/idfaq/oddports.php[那些埠號會被木馬程式使用]。

FTP 有兩個模式：主動 (Active) 模式與被動 (Passive) 模式，兩者的差異在於取得資料通道的方式，被動模式會較安全，由於資料通道會取自 FTP 連線請求者。想要取得 FTP 與兩種模式更進一步的說明，詳見 http://www.slacksite.com/other/ftp.html[http://www.slacksite.com/other/ftp.html]。

防火牆規則集可以為排除式 ("exclusive") 或者內含式 ("inclusive")，一個排除式的防火牆會允許所有的連線通過除了符合規則集的連線，內含式的防火牆則會反過來只允許符合規則集的連線並封鎖其他任何的連線。

內含式的防火牆對於外發的流量有較好的控制，使其成為提供網際網路服務的系統的最佳選擇，它同時可以控制可存取私有網路的網際網路連線，所有不符合該規則的連線會被封鎖並記錄。一般來說，內含式的防火牆會比排除式的防火牆安全，因為內含式的防火牆可以明顯的減少不必要連線所造成風險。

[NOTE]
====
除非另有說明，否則所有在此章節的範例規則集均為內含式防火牆規則集。
====

使用具狀態防火牆 ("Stateful firewall") 可以更進一步加強安全性，這種類型的防火牆可持續追蹤連線，只允許與現有連線相符的封包或符合允許條件的新連線通過。

狀態過濾技術 (Stateful filtering) 將所有的流量當做是一個由雙向封包交換所組成的連線階段，當在符合的規則上指定狀態 (State) 時，防火牆會自動產生內部規則來處理該連線階段中每個預期會通過的封包，這種防火牆有足夠的比對能力可以辨別是否為同一個連線階段的封包，任何不符合連線階段樣板的封包都會被自動拒絕。

當連線階段結束時，該規則將會動態狀態表 (Dynamic state table) 中移除。

Stateful filtering 讓管理者可以專注於封鎖/傳遞新的連線階段，若新的連線階段通過，那麼該連線階段後續的封包將會自動允許通過，且任何假冒的封包會自動被拒絕。若新的連線階最被封鎖，將不允許其任何後續的封包。Stateful filtering 提供了進階的比對能力，能夠抵禦不同種類由攻擊者發動的 flood 攻擊。

NAT 代表 _Network Address Translation_ 即網路位址轉譯，NAT 功能讓在防火牆之後的私有 LAN 可以共用一個 ISP 分配的 IP 位址 (甚至是動態分配的)，NAT 每一台在該 LAN 中的電腦均可連線網際網路，而不需要支付 ISP 多個網路帳號或 IP 位址的額外費用。

NAT 在當封包要外送到防火牆之外的網際網路時，會自動轉譯每一台電腦在私有 LAN 的 IP 位址成為一個公有 IP 位址，它也同樣會對回傳的封包做反向轉譯。

根據 RFC1918，會保留以下範圍的 IP 位址做為私有網路使用，永遠不會被傳送到網際網路，因此可供 NAT 使用：

* `10.0.0.0/8`.
* `172.16.0.0/12`.
* `192.168.0.0/16`.

[WARNING]
====

在使用防火牆規則時要_非常小心_，有一些設定_會將管理者鎖在伺服器之外_，保險起見的方式是在本機的 Console 做初次的防火牆設定，不要直接由遠端透過 ssh 來設定防火牆。
====

[[firewalls-pf]]
== PF

自 FreeBSD 5.3 開始，基礎系統便有內建 OpenBSD's PF 防火牆的移植版本，PF 是一套完整、多功能的防火牆，並可選擇開啟 ALTQ (Alternate Queuing) 的支援來提供 Quality of Service (QoS) 機制。

OpenBSD 計劃有維護一份官方參考文件於 http://www.openbsd.org/faq/pf/[PF FAQ] ，Peter Hansteen 有維一份詳盡的 PF 教學於 http://home.nuug.no/\~peter/pf/[http://home.nuug.no/~peter/pf/]。

[WARNING]
====

閱讀 http://www.openbsd.org/faq/pf/[PF FAQ] 時，請注意 FreeBSD 的 PF 版本多年來已與上游 OpenBSD 版本產生相當大的差異。並非所有功能在 FreeBSD 與 OpenBSD 上的運作方式都相同，反之亦然。
====

要詢問有關設定與執行 PF 防火牆的問題可至 http://lists.FreeBSD.org/mailman/listinfo/freebsd-pf[FreeBSD packet filter 郵遞論壇]，在詢問問題之前請先查看該郵遞論壇的封存資料，因您的問題可能已有解答。

本手冊此段落著重於 PF 在 FreeBSD 上的應用，說明如何啟用 PF 和 ALTQ，並提供幾個在 FreeBSD 系統上建立規則集的範例。

=== 開啟 PF

要使用 PF，必須先載入其核心模組。本段落說明可以加到 [.filename]#/etc/rc.conf# 中以啟用 PF 的設定項目。

首先將 `pf_enable=yes` 加入 [.filename]#/etc/rc.conf#：

[source,shell]
....
# sysrc pf_enable=yes
....

PF 啟動時可以傳入其他選項，相關說明請參考 man:pfctl[8]。在 [.filename]#/etc/rc.conf# 中新增或修改以下設定項目，並在兩個引號 (`""`) 之間指定所需的旗標：

[.programlisting]
....
pf_flags=""                     # additional flags for pfctl startup
....

如果 PF 找不到規則集設定檔就不會啟動。FreeBSD 預設並不附帶規則集，也沒有 [.filename]#/etc/pf.conf# 檔案。範例規則集可以在 [.filename]#/usr/shared/examples/pf/# 找到。如果自訂規則集存放在其他位置，請在 [.filename]#/etc/rc.conf# 中新增一行，指定該檔案的完整路徑：

[.programlisting]
....
pf_rules="/path/to/pf.conf"
....

PF 的記錄功能由 man:pflog[4] 提供。要啟用記錄功能，請將 `pflog_enable=yes` 加入 [.filename]#/etc/rc.conf#：

[source,shell]
....
# sysrc pflog_enable=yes
....

也可以加入以下幾行來變更記錄檔的預設位置，或指定 man:pflog[4] 啟動時要傳入的額外旗標：

[.programlisting]
....
pflog_logfile="/var/log/pflog"  # where pflogd should store the logfile
pflog_flags=""                  # additional flags for pflogd startup
....

最後，如果防火牆後方有區域網路，且需要為區域網路上的電腦轉送封包，或需要使用網路位址轉譯 (NAT)，請啟用以下選項：

[.programlisting]
....
gateway_enable="YES"            # Enable as LAN gateway
....

儲存所需的編輯後，即可輸入以下指令啟動 PF 並開啟記錄功能：

[source,shell]
....
# service pf start
# service pflog start
....

PF 預設從 [.filename]#/etc/pf.conf# 讀取設定規則，並根據此檔案中指定的規則或定義來修改、丟棄或放行封包。FreeBSD 安裝時附帶了幾個範例檔案，位於 [.filename]#/usr/shared/examples/pf/#。關於 PF 規則集的完整說明，請參閱 http://www.openbsd.org/faq/pf/[PF FAQ]。

要控制 PF，請使用 `pfctl`。<<pfctl>> 列出了這個指令的幾個實用選項。所有可用選項的說明請參閱 man:pfctl[8]：
[[pfctl]]
.有用的 `pfctl` 選項
[cols="1,1", frame="none", options="header"]
|===
| 指令
| 用途

|`pfctl -e`
|啟用 PF。

|`pfctl -d`
|停用 PF。

|`pfctl -F all -f /etc/pf.conf`
|清除所有 NAT、過濾、狀態和表格規則，並重新載入 [.filename]#/etc/pf.conf#。

|`pfctl -s [ rules \| nat \| states ]`
|顯示過濾規則、NAT 規則或狀態表。

|`pfctl -vnf /etc/pf.conf`
|檢查 [.filename]#/etc/pf.conf# 是否有錯誤，但不載入規則集。
|===

[TIP]
====

package:security/sudo[] 對於執行像 `pfctl` 這類需要較高權限的指令非常有用，可從 Port 套件集安裝。
====

若要監控通過 PF 防火牆的流量，可以考慮安裝 package:sysutils/pftop[] 套件或 Port。安裝完成後，可以執行 pftop 來即時檢視流量快照，其顯示格式類似 man:top[1]。

[[pf-tutorial]]
=== PF 規則集

本段落示範如何建立自訂規則集。從最簡單的規則集開始，再透過幾個範例逐步擴充概念，展示 PF 多種功能在實務上的運用。

最簡單的規則集適用於不執行任何服務、只需要存取一個網路（可能是網際網路）的單機。要建立這個最基本的規則集，請編輯 [.filename]#/etc/pf.conf# 使其內容如下：

[.programlisting]
....
block in all
pass out all keep state
....

第一條規則預設阻擋所有傳入流量。第二條規則允許本系統建立的連線通過，同時保留這些連線的狀態資訊。此狀態資訊讓回應流量可以通過，這項功能應僅用於可信任的機器。規則集可以用以下指令載入：

[source,shell]
....
# pfctl -e ; pfctl -f /etc/pf.conf
....

除了保持狀態外，PF 還提供了 _清單_ 和 _巨集_，可在建立規則時定義使用。巨集可以包含清單，但必須在使用前先定義。舉例來說，可以在規則集最上方插入以下幾行：

[.programlisting]
....
tcp_services = "{ ssh, smtp, domain, www, pop3, auth, pop3s }"
udp_services = "{ domain }"
....

PF 能辨識連接埠名稱和連接埠號碼，只要名稱有列在 [.filename]#/etc/services# 中即可。這個範例建立了兩個巨集，第一個是七個 TCP 連接埠名稱的清單，第二個是一個 UDP 連接埠名稱。巨集定義後就可以在規則中使用。在這個範例中，除了本系統發起的七個指定 TCP 服務和一個指定 UDP 服務的連線外，所有流量都會被阻擋：

[.programlisting]
....
tcp_services = "{ ssh, smtp, domain, www, pop3, auth, pop3s }"
udp_services = "{ domain }"
block all
pass out proto tcp to any port $tcp_services keep state
pass proto udp to any port $udp_services keep state
....

雖然 UDP 被視為無狀態通訊協定，PF 仍然能追蹤部分狀態資訊。例如，當一個 UDP 請求被放行去查詢名稱伺服器的網域名稱時，PF 會監視回應並讓它通過。

每次編輯規則集後，都必須載入新規則才能生效：

[source,shell]
....
# pfctl -f /etc/pf.conf
....

如果沒有語法錯誤，`pfctl` 在載入規則時不會輸出任何訊息。規則也可以在載入前先進行測試：

[source,shell]
....
# pfctl -nf /etc/pf.conf
....

加上 `-n` 會讓規則只進行解譯而不載入，這提供了修正錯誤的機會。最後一次成功載入的有效規則集會持續生效，直到 PF 被停用或載入新的規則集為止。

[TIP]
====

在 `pfctl` 驗證或載入規則集時加上 `-v`，會顯示完整解析後的規則，與實際載入的內容一模一樣。這在除錯規則時非常有用。
====

[[pftut-gateway]]
==== 使用 NAT 的簡單通訊閘

本段落示範如何將執行 PF 的 FreeBSD 系統設定為至少一台其他機器的閘道。閘道需要至少兩個網路介面，分別連接不同的網路。在本範例中，[.filename]#xl1# 連接網際網路，[.filename]#xl0# 連接內部網路。

首先，啟用閘道功能讓機器將一個網路介面收到的流量轉送到另一個網路介面。以下 sysctl 設定會啟用 IPv4 封包轉送：

[source,shell]
....
# sysctl net.inet.ip.forwarding=1
....

要轉送 IPv6 流量，請使用：

[source,shell]
....
# sysctl net.inet6.ip6.forwarding=1
....

要在系統開機時啟用這些設定，請使用 man:sysrc[8] 將它們加入 [.filename]#/etc/rc.conf#：

[source,shell]
....
# sysrc gateway_enable=yes
# sysrc ipv6_gateway_enable=yes
....

使用 `ifconfig` 確認兩個網路介面都已啟動且正常運作。

接著，建立 PF 規則讓閘道可以傳遞流量。雖然以下規則允許有狀態的流量從網際網路傳遞到網路上的主機，但 `to` 關鍵字並不保證封包能從來源一路到達目的地：

[.programlisting]
....
pass in on xl1 from xl1:network to xl0:network port $ports keep state
....

這條規則只讓流量通過閘道進入內部網路介面。要讓封包繼續傳遞，還需要一條相對應的規則：

[.programlisting]
....
pass out on xl0 from xl1:network to xl0:network port $ports keep state
....

雖然這兩條規則可以運作，但這麼精確的規則很少有必要。對忙碌的網路管理員來說，可讀性高的規則集就是安全的規則集。本段落接下來會示範如何盡量保持規則簡潔易讀。例如，上面兩條規則可以用一條取代：

[.programlisting]
....
pass from xl1:network to any port $ports keep state
....

`interface:network` 表示法可以用巨集取代，讓規則集更容易閱讀。例如，可以定義 `$localnet` 巨集為直接連接到內部介面的網路 (`$xl1:network`)。也可以將 `$localnet` 的定義改為 _IP 位址/子網路遮罩_ 表示法來代表網路，例如用 `192.168.100.1/24` 表示私有位址子網路。

如果需要，`$localnet` 甚至可以定義為網路清單。無論具體需求為何，合理的 `$localnet` 定義可以在典型的放行規則中如下使用：

[.programlisting]
....
pass from $localnet to any port $ports keep state
....

以下範例規則集允許由內部網路機器發起的所有流量。首先定義兩個巨集來代表閘道的外部和內部 3COM 網路介面。

[NOTE]
====
撥接用戶的外部介面應使用 [.filename]#tun0#。使用 ADSL 連線，特別是使用 PPP over Ethernet (PPPoE) 的情況，正確的外部介面是 [.filename]#tun0#，而非實體乙太網路介面。
====

[.programlisting]
....
ext_if = "xl0"	# macro for external interface - use tun0 for PPPoE
int_if = "xl1"	# macro for internal interface
localnet = $int_if:network
# ext_if IP address could be dynamic, hence ($ext_if)
nat on $ext_if from $localnet to any -> ($ext_if)
block all
pass from { lo0, $localnet } to any keep state
....

這個規則集引入了 `nat` 規則，用來處理從內部網路不可路由位址到外部介面 IP 位址的網路位址轉譯。nat 規則最後一部分 `($ext_if)` 的括號是在外部介面 IP 位址為動態指派時使用的，確保即使外部 IP 位址變更，網路流量仍然不會受到嚴重中斷。

請注意，這個規則集可能允許比實際需要更多的流量通過網路。一個合理的設定可以建立如下巨集：

[.programlisting]
....
client_out = "{ ftp-data, ftp, ssh, domain, pop3, auth, nntp, http, \
    https, cvspserver, 2628, 5999, 8000, 8080 }"
....

在主要放行規則中使用：

[.programlisting]
....
pass inet proto tcp from $localnet to any port $client_out \
    flags S/SA keep state
....

可能還需要其他幾條放行規則。這一條在外部介面啟用 SSH：

[.programlisting]
....
pass in inet proto tcp to $ext_if port ssh
....

以下巨集定義和規則允許內部用戶端使用 DNS 和 NTP：

[.programlisting]
....
udp_services = "{ domain, ntp }"
pass quick inet proto { tcp, udp } to any port $udp_services keep state
....

請注意這條規則中的 `quick` 關鍵字。由於規則集包含多條規則，了解規則集中各規則之間的關係很重要。規則按照撰寫順序從上到下逐一評估。對於 PF 評估的每個封包或連線，規則集中 _最後一條符合的規則_ 才是實際套用的規則。但是，當封包符合含有 `quick` 關鍵字的規則時，規則處理會立即停止，封包按照該規則處理。當需要為通用規則建立例外時，這個功能非常實用。

[[pftut-ftp]]
==== 建立 FTP Proxy

由於 FTP 通訊協定的本質，設定可運作的 FTP 規則可能很棘手。FTP 比防火牆早了幾十年，在設計上就不安全。反對使用 FTP 最常見的理由包括：

* 密碼以明文傳輸。
* 此通訊協定要求在不同連接埠上使用至少兩個 TCP 連線（控制和資料）。
* 建立工作階段後，資料傳輸使用隨機選擇的連接埠。

這些特性都帶來安全上的挑戰，還不包括用戶端或伺服器軟體本身可能存在的安全漏洞。更安全的檔案傳輸替代方案包括 man:sftp[1] 或 man:scp[1]，兩者都透過加密連線提供認證和資料傳輸。

在必須使用 FTP 的情況下，PF 提供將 FTP 流量重導到一個名為 man:ftp-proxy[8] 的小型代理程式的功能，此程式包含在 FreeBSD 基礎系統中。該代理程式透過一組錨點 (anchor) 動態新增和刪除規則集中的規則，以正確處理 FTP 流量。

要啟用 FTP 代理程式，請將以下這行加入 [.filename]#/etc/rc.conf#：

[.programlisting]
....
ftpproxy_enable="YES"
....

然後執行 `service ftp-proxy start` 啟動代理程式。

基本設定需要在 [.filename]#/etc/pf.conf# 中加入三個元素。首先是代理程式用來插入 FTP 工作階段規則的錨點：

[.programlisting]
....
nat-anchor "ftp-proxy/*"
rdr-anchor "ftp-proxy/*"
....

第二，需要一條放行規則允許 FTP 流量進入代理程式。

第三，重導和 NAT 規則必須定義在過濾規則之前。在 `nat` 規則後面立即插入這條 `rdr` 規則：

[.programlisting]
....
rdr pass on $int_if proto tcp from any to any port ftp -> 127.0.0.1 port 8021
....

最後，允許重導的流量通過：

[.programlisting]
....
pass out proto tcp from $proxy to any port ftp
....

其中 `$proxy` 展開為代理程式常駐程序綁定的位址。

儲存 [.filename]#/etc/pf.conf#，載入新規則，並從用戶端驗證 FTP 連線是否正常運作：

[source,shell]
....
# pfctl -f /etc/pf.conf
....

此範例涵蓋了區域網路內用戶端需要連線到外部 FTP 伺服器的基本設定。這個基本設定應該能與大多數 FTP 用戶端和伺服器的組合正常運作。如 man:ftp-proxy[8] 所述，可以在 `ftpproxy_flags=` 行加入選項來調整代理程式的行為。部分用戶端或伺服器可能有特殊行為需要在設定中加以因應，或者可能需要以特定方式整合代理程式，例如將 FTP 流量指派到特定佇列。

若要執行受 PF 和 man:ftp-proxy[8] 保護的 FTP 伺服器，請使用 `-R` 在反向模式下設定獨立的 `ftp-proxy`，配置在不同的連接埠並搭配專屬的重導放行規則。

[[pftut-icmp]]
==== 管理 ICMP

許多用來除錯或排除 TCP/IP 網路問題的工具都仰賴網際網路控制訊息通訊協定 (ICMP)，這個通訊協定就是專為除錯而設計的。

ICMP 通訊協定在主機和閘道之間傳送和接收 _控制訊息_，主要是向發送端回報通往目標主機途中遇到的異常或困難狀況。路由器使用 ICMP 來協商封包大小和其他傳輸參數，這個過程通常稱為 _路徑 MTU 探索_。

從防火牆的角度來看，某些 ICMP 控制訊息容易受到已知攻擊手法的利用。此外，無條件放行所有診斷流量雖然讓除錯更容易，但也讓他人更容易擷取網路資訊。基於這些原因，以下規則可能不是最佳選擇：

[.programlisting]
....
pass inet proto icmp from any to any
....

一個解決方案是讓來自區域網路的所有 ICMP 流量通過，同時阻擋來自外部網路的所有探測：

[.programlisting]
....
pass inet proto icmp from $localnet to any keep state
pass inet proto icmp from any to $ext_if keep state
....

還有其他選項可以展示 PF 的彈性。例如，與其允許所有 ICMP 訊息，可以只指定 man:ping[8] 和 man:traceroute[8] 使用的訊息類型。首先為該訊息類型定義一個巨集：

[.programlisting]
....
icmp_types = "echoreq"
....

以及使用該巨集的規則：

[.programlisting]
....
pass inet proto icmp all icmp-type $icmp_types keep state
....

如果需要其他類型的 ICMP 封包，可以將 `icmp_types` 擴充為這些封包類型的清單。輸入 `more /usr/src/sbin/pfctl/pfctl_parser.c` 可以查看 PF 支援的 ICMP 訊息類型清單。各訊息類型的說明請參閱 http://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml[http://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml]。

由於 Unix `traceroute` 預設使用 UDP，因此需要另一條規則來允許 Unix `traceroute`：

[.programlisting]
....
# allow out the default range for traceroute(8):
pass out on $ext_if inet proto udp from any to any port 33433 >< 33626 keep state
....

由於 Microsoft Windows 系統上的 `TRACERT.EXE` 使用 ICMP echo request 訊息，只需要第一條規則就能允許來自這些系統的網路追蹤。Unix `traceroute` 也可以設定使用其他通訊協定，使用 `-I` 時會採用 ICMP echo request 訊息。詳情請查閱 man:traceroute[8] 手冊頁。

[[pftut-pathmtudisc]]
===== Path MTU Discovery

網際網路通訊協定的設計與設備無關，而設備無關性的一個結果就是無法總是可靠地預測特定連線的最佳封包大小。封包大小的主要限制因素是 _最大傳輸單元_ (MTU)，它設定了網路介面封包大小的上限。輸入 `ifconfig` 可以查看系統網路介面的 MTU。

TCP/IP 使用一種稱為路徑 MTU 探索的機制來決定連線的適當封包大小。這個過程會發送不同大小且設定了「不分割」旗標的封包，預期在達到上限時會收到「type 3, code 4」的 ICMP 回應封包。Type 3 表示「目的地無法到達」，code 4 是「需要分割，但設定了不分割旗標」的簡稱。要允許路徑 MTU 探索以支援不同 MTU 的連線，請將 `destination unreachable` 類型加入 `icmp_types` 巨集：

[.programlisting]
....
icmp_types = "{ echoreq, unreach }"
....

由於放行規則已經使用了該巨集，不需要修改就能支援新的 ICMP 類型：

[.programlisting]
....
pass inet proto icmp all icmp-type $icmp_types keep state
....

PF 允許對所有 ICMP 類型和代碼的變體進行過濾。可能的類型和代碼清單記錄在 man:icmp[4] 和 man:icmp6[4] 中。

[[pftut-tables]]
==== 使用 Tables

某些類型的資料在特定時間與過濾和重導有關，但其定義太長無法放在規則集檔案中。PF 支援使用表格，表格是已定義的清單，可以在不重新載入整個規則集的情況下操作，且能提供快速查詢。表格名稱總是用 `< >` 包起來，像這樣：

[.programlisting]
....
table <clients> { 192.168.2.0/24, !192.168.2.5 }
....

在這個範例中，`192.168.2.0/24` 網路是表格的一部分，但位址 `192.168.2.5` 透過 `!` 運算子排除在外。也可以從檔案載入表格，每個項目各佔一行，如以下 [.filename]#/etc/clients# 範例：

[.programlisting]
....
192.168.2.0/24
!192.168.2.5
....

要參照該檔案，請如下定義表格：

[.programlisting]
....
table <clients> persist file "/etc/clients"
....

表格定義完成後，就可以在規則中參照使用：

[.programlisting]
....
pass inet proto tcp from <clients> to any port $client_out flags S/SA keep state
....

表格的內容可以用 `pfctl` 即時操作。以下範例將另一個網路加入表格：

[source,shell]
....
# pfctl -t clients -T add 192.168.1.0/16
....

請注意，以這種方式進行的變更會立即生效，非常適合測試，但在斷電或重新開機後不會保留。要使變更永久生效，請修改規則集中的表格定義，或編輯表格參照的檔案。可以使用 man:cron[8] 排程工作定期將表格內容傾印到磁碟，使用類似 `pfctl -t clients -T show >/etc/clients` 的指令來維護磁碟上的表格副本。或者，也可以用記憶體中的表格內容更新 [.filename]#/etc/clients#：

[source,shell]
....
# pfctl -t clients -T replace -f /etc/clients
....

[[pftut-overload]]
==== 使用 Overload Tables 保護 SSH

在外部介面上執行 SSH 的人，可能在認證記錄中看過類似這樣的內容：

[.programlisting]
....
Sep 26 03:12:34 skapet sshd[25771]: Failed password for root from 200.72.41.31 port 40992 ssh2
Sep 26 03:12:34 skapet sshd[5279]: Failed password for root from 200.72.41.31 port 40992 ssh2
Sep 26 03:12:35 skapet sshd[5279]: Received disconnect from 200.72.41.31: 11: Bye Bye
Sep 26 03:12:44 skapet sshd[29635]: Invalid user admin from 200.72.41.31
Sep 26 03:12:44 skapet sshd[24703]: input_userauth_request: invalid user admin
Sep 26 03:12:44 skapet sshd[24703]: Failed password for invalid user admin from 200.72.41.31 port 41484 ssh2
....

這表示有人或某個程式正在進行暴力破解攻擊，試圖找出能登入系統的使用者名稱和密碼。

如果合法使用者需要從外部存取 SSH，更改 SSH 使用的預設連接埠可以提供一些保護。不過，PF 提供了更優雅的解決方案。放行規則可以限制連線主機的行為，違規者會被放入一個位址表格中，拒絕其部分或全部存取。甚至可以丟棄來自超過限制的機器的所有現有連線。

要進行此設定，請在規則集的表格區段中建立以下表格：

[.programlisting]
....
table <bruteforce> persist
....

接著，在規則集較前面的位置，加入阻擋暴力存取同時允許合法存取的規則：

[.programlisting]
....
block quick from <bruteforce>
pass inet proto tcp from any to $localnet port $tcp_services \
    flags S/SA keep state \
    (max-src-conn 100, max-src-conn-rate 15/5, \
    overload <bruteforce> flush global)
....

括號中的部分定義了限制值，數字應依據本機需求調整。其內容可以解讀如下：

`max-src-conn` 是允許單一主機的同時連線數。

`max-src-conn-rate` 是允許任何單一主機在指定秒數 (_5_) 內的新連線速率 (_15_)。

`overload <bruteforce>` 表示任何超過這些限制的主機，其位址會被加入 `bruteforce` 表格。規則集會阻擋來自 `bruteforce` 表格中所有位址的流量。

最後，`flush global` 表示當主機達到限制時，該主機的所有 (`global`) 連線都會被終止 (`flush`)。

[NOTE]
====
如 http://home.nuug.no/\~peter/hailmary2013/[http://home.nuug.no/~peter/hailmary2013/] 所述，這些規則 _不會_ 阻擋緩慢的暴力破解攻擊。
====

這個範例規則集主要是做為說明用途。例如，如果一般連線希望較為寬鬆，但針對 ssh 想要更嚴格的限制，可以在規則集較前面的位置，用以下類似的規則補充上面的規則：

[.programlisting]
....
pass quick proto { tcp, udp } from any to any port ssh \
    flags S/SA keep state \
    (max-src-conn 15, max-src-conn-rate 5/3, \
    overload <bruteforce> flush global)
....

[NOTE]
.不一定需要阻擋所有超載者
====
值得注意的是，超載機制是一種通用技術，並不專屬於 SSH，而且完全阻擋違規者的所有流量也不一定是最佳做法。

例如，超載規則可以用來保護郵件服務或網頁服務，超載表格可以在規則中使用，將違規者指派到頻寬配額最小的佇列，或重導到特定網頁。
====

隨著時間推移，表格會因超載規則不斷填入而逐漸增長，佔用更多記憶體。有時被阻擋的 IP 位址是動態分配的，之後可能已指派給有正當理由與區域網路主機通訊的主機。

針對這類情況，pfctl 提供了讓表格項目到期的功能。例如，以下指令會移除 `86400` 秒內未被參照的 `<bruteforce>` 表格項目：

[source,shell]
....
# pfctl -t bruteforce -T expire 86400
....

package:security/expiretable[] 也提供類似功能，可以移除在指定時間內未被存取的表格項目。

安裝完成後，可以執行 expiretable 來移除超過指定時間的 `<bruteforce>` 表格項目。以下範例會移除所有超過 24 小時的項目：

[.programlisting]
....
/usr/local/sbin/expiretable -v -d -t 24h bruteforce
....

[[pftut-spamd]]
==== SPAM 防護

請勿與 spamassassin 附帶的 spamd 常駐程序混淆，package:mail/spamd[] 可以搭配 PF 設定來提供對抗垃圾郵件的外層防護。這個 spamd 透過一組重導規則與 PF 設定整合。

垃圾郵件發送者傾向大量發送訊息，垃圾郵件主要來自少數對垃圾郵件發送者友善的網路和大量被入侵的機器，這兩者都會很快被通報到 _黑名單_。

當收到來自黑名單位址的 SMTP 連線時，spamd 會顯示其橫幅標語，然後立即切換到逐位元組回應 SMTP 流量的模式。這種技術旨在盡可能浪費垃圾郵件發送端的時間，稱為 _tarpitting_（焦油坑）。使用逐位元組 SMTP 回應的特定實作方式通常稱為 _stuttering_（結巴）。

此範例示範使用自動更新黑名單設定 spamd 的基本程序。更多資訊請參閱隨 package:mail/spamd[] 安裝的手冊頁。

[.procedure]
====
*程序：設定 spamd*

. 安裝 package:mail/spamd[] 套件或 Port。要使用 spamd 的灰名單功能，必須在 [.filename]#/dev/fd# 掛載 man:fdescfs[5]。將以下這行加入 [.filename]#/etc/fstab#：
+
[.programlisting]
....
 fdescfs /dev/fd fdescfs rw 0 0
....
+ 
然後掛載檔案系統：
+
[.programlisting]
....
# mount fdescfs
....
+
. 接著，編輯 PF 規則集加入以下內容：
+
[.programlisting]
....
table <spamd> persist
table <spamd-white> persist
rdr pass on $ext_if inet proto tcp from <spamd> to \
    { $ext_if, $localnet } port smtp -> 127.0.0.1 port 8025
rdr pass on $ext_if inet proto tcp from !<spamd-white> to \
    { $ext_if, $localnet } port smtp -> 127.0.0.1 port 8025
....
+ 
`<spamd>` 和 `<spamd-white>` 這兩個表格是必要的。來自列在 `<spamd>` 但不在 `<spamd-white>` 中位址的 SMTP 流量，會被重導到監聽連接埠 8025 的 spamd 常駐程序。
. 下一步是在 [.filename]#/usr/local/etc/spamd.conf# 中設定 spamd 並加入一些 [.filename]#rc.conf# 參數。
+ 
package:mail/spamd[] 的安裝包含了範例設定檔 ([.filename]#/usr/local/etc/spamd.conf.sample#) 和 [.filename]#spamd.conf# 的手冊頁。本範例以外的其他設定選項請參閱這些文件。
+ 
設定檔中最先出現的非 `#` 註解行之一，包含定義 `all` 清單的區塊，用來指定要使用的清單：
+
[.programlisting]
....
all:\
    :traplist:whitelist:
....
+ 
這個項目以冒號 (`:`) 分隔，加入所需的黑名單。要使用白名單從黑名單中排除位址，請在該黑名單名稱 _緊接_ 之後加入白名單名稱。例如：`:blacklist:whitelist:`。
+ 
接著是指定黑名單的定義：
+
[.programlisting]
....
traplist:\
    :black:\
    :msg="SPAM. Your address %A has sent spam within the last 24 hours":\
    :method=http:\
    :file=www.openbsd.org/spamd/traplist.gz
....
+ 
其中第一行是黑名單的名稱，第二行指定清單類型。`msg` 欄位包含在 SMTP 對話期間向黑名單發送者顯示的訊息。`method` 欄位指定 spamd-setup 擷取清單資料的方式；支援的方法有 `http`、`ftp`、從掛載檔案系統中的 `file`，以及透過 `exec` 執行外部程式。最後，`file` 欄位指定 spamd 預期接收的檔案名稱。
+ 
指定白名單的定義類似，但省略了 `msg` 欄位，因為不需要訊息：
+
[.programlisting]
....
whitelist:\
    :white:\
    :method=file:\
    :file=/var/mail/whitelist.txt
....
+
[TIP]
.謹慎選擇資料來源
======
使用範例 [.filename]#spamd.conf# 中的所有黑名單會將網際網路的大片區塊列入黑名單。管理員需要編輯此檔案以建立使用適當資料來源的最佳設定，並在必要時使用自訂清單。
======
+ 
接著，將以下項目加入 [.filename]#/etc/rc.conf#。註解中指定的手冊頁有其他旗標的說明：
+
[.programlisting]
....
spamd_flags="-v" # use "" and see spamd-setup(8) for flags
....
+ 
完成後，重新載入規則集，輸入 `service obspamd start` 啟動 spamd，並使用 `spamd-setup` 完成設定。最後，建立一個 man:cron[8] 排程工作，以合理的間隔呼叫 `spamd-setup` 來更新表格。
====

在郵件伺服器前的典型閘道上，主機很快就會在幾秒到幾分鐘內開始被捕捉。

PF 也支援 _灰名單_，以 _45n_ 回應碼暫時拒絕來自未知主機的訊息。來自被列入灰名單的主機若在合理時間內重試，訊息就會被放行。來自設定符合 RFC 1123 和 RFC 2821 限制的發送者的流量會立即放行。

關於灰名單技術的更多資訊可在 http://www.greylisting.org/[greylisting.org] 網站找到。灰名單除了簡單之外，最令人驚訝的是它至今仍然有效。垃圾郵件發送者和惡意軟體作者在適應並繞過此技術方面進展非常緩慢。

設定灰名單的基本程序如下：

[.procedure]
====
*程序：設定灰名單*

. 確認 man:fdescfs[5] 已依照前述程序步驟 1 的說明掛載。
. 要在灰名單模式下執行 spamd，請將以下這行加入 [.filename]#/etc/rc.conf#：
+
[.programlisting]
....
spamd_grey="YES"  # use spamd greylisting if YES
....
+ 
其他相關參數的說明請參閱 spamd 手冊頁。
. 要完成灰名單設定：
+
[.programlisting]
....
# service obspamd restart
# service obspamlogd start
....
====

在幕後，spamdb 資料庫工具和 spamlogd 白名單更新程式為灰名單功能執行必要的工作。spamdb 是管理員透過 [.filename]#/var/db/spamdb# 資料庫內容管理黑名單、灰名單和白名單的主要介面。

[[pftut-hygiene]]
==== 網路保健

本段落說明如何使用 `block-policy`、`scrub` 和 `antispoof` 讓規則集運作得更合理。

`block-policy` 是一個可以在規則集 `options` 區段設定的選項，位於重導和過濾規則之前。此選項決定 PF 對被規則阻擋的主機傳送什麼回饋訊息（如果有的話）。此選項有兩個可能的值：`drop` 會直接丟棄被阻擋的封包且不回饋，`return` 則回傳一個狀態碼，例如 `Connection refused`。

如果未設定，預設策略為 `drop`。要變更 `block-policy`，請指定所需的值：

[.programlisting]
....
set block-policy return
....

在 PF 中，`scrub` 是啟用網路封包正規化的關鍵字。這個程序會重組被分割的封包，並丟棄具有無效旗標組合的 TCP 封包。啟用 `scrub` 可以對某些基於不正確處理封包分割的攻擊提供一定程度的保護。有多種選項可用，但最簡單的形式適用於大多數設定：

[.programlisting]
....
scrub in all
....

某些服務，例如 NFS，需要特定的分割處理選項。更多資訊請參閱 https://home.nuug.no/\~peter/pf/en/scrub.html[https://home.nuug.no/~peter/pf/en/scrub.html]。

此範例會重組分割的封包、清除「不分割」位元，並將最大區段大小設定為 1440 位元組：

[.programlisting]
....
scrub in all fragment reassemble no-df max-mss 1440
....

`antispoof` 機制透過阻擋在邏輯上不可能出現在特定網路介面和方向的封包，來防護偽造或假冒 IP 位址的活動。

以下規則可以過濾來自外部世界的偽造流量，以及源自區域網路的偽造封包：

[.programlisting]
....
antispoof for $ext_if
antispoof for $int_if
....

[[pftut-unrouteables]]
==== 處理不可路由 (Non-Routable) 的位址

即使閘道已正確設定處理網路位址轉譯，仍可能需要因應他人的錯誤設定。常見的錯誤設定是讓不可路由位址的流量流出到網際網路。由於來自不可路由位址的流量可能在多種 DoS 攻擊技術中扮演角色，請考慮明確阻擋不可路由位址的流量從外部介面進入網路。

在此範例中，定義了一個包含不可路由位址的巨集，然後在阻擋規則中使用。往返這些位址的流量會在閘道的外部介面上被無聲丟棄。

[.programlisting]
....
martians = "{ 127.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12, \
	      10.0.0.0/8, 169.254.0.0/16, 192.0.2.0/24, \
	      0.0.0.0/8, 240.0.0.0/4 }"

block drop in quick on $ext_if from $martians to any
block drop out quick on $ext_if from any to $martians
....

=== 開啟 ALTQ

在 FreeBSD 上，ALTQ 可以搭配 PF 使用來提供服務品質 (QOS)。啟用 ALTQ 後，可以在規則集中定義佇列來決定送出封包的處理優先順序。

啟用 ALTQ 之前，請參閱 man:altq[4] 以確認系統上安裝的網路卡驅動程式是否支援。

ALTQ 無法做為可載入核心模組使用。如果系統的網路介面支援 ALTQ，請依照 crossref:kernelconfig[kernelconfig,設定 FreeBSD 核心] 中的說明建立自訂核心。以下是可用的核心選項。第一個選項是啟用 ALTQ 所必需的，其他選項中至少需要一個來指定佇列排程演算法：

[.programlisting]
....
options         ALTQ
options         ALTQ_CBQ        # Class Based Queuing (CBQ)
options         ALTQ_RED        # Random Early Detection (RED)
options         ALTQ_RIO        # RED In/Out
options         ALTQ_HFSC       # Hierarchical Packet Scheduler (HFSC)
options         ALTQ_PRIQ       # Priority Queuing (PRIQ)
....

以下是可用的排程演算法：

CBQ::
以類別為基礎的佇列 (CBQ) 用於將連線的頻寬劃分為不同的類別或佇列，根據過濾規則來排定流量的優先順序。

RED::
隨機早期偵測 (RED) 透過測量佇列長度並與佇列的最小和最大閾值比較來避免網路壅塞。當佇列超過最大值時，所有新封包會被隨機丟棄。

RIO::
在隨機早期偵測進出 (RIO) 模式下，RED 維護多個平均佇列長度和多個閾值，每個 QOS 等級各一組。

HFSC::
階層式公平服務曲線封包排程器 (HFSC) 的說明請參閱 http://www-2.cs.cmu.edu/\~hzhang/HFSC/main.html[http://www-2.cs.cmu.edu/~hzhang/HFSC/main.html]。

PRIQ::
優先佇列 (PRIQ) 總是先傳遞較高優先順序佇列中的流量。

關於排程演算法和規則集範例的更多資訊，請參閱 https://web.archive.org/web/20151109213426/http://www.openbsd.org/faq/pf/queueing.html[OpenBSD 的網頁封存]。

[[firewalls-ipfw]]
== IPFW

IPFW 是一套專為 FreeBSD 所寫的具狀態防火牆 (Stateful firewall)，它同時支援 IPv4 與 IPv6，它由數個元件組成：核心防火牆過濾規則處理器與其整合的封包計帳設施、記錄設施、NAT、man:dummynet[4] 流量限制程式、轉送設施、橋接設施以及 ipstealth 設施。

FreeBSD 提供一個範本規則集於 [.filename]#/etc/rc.firewall#，其定義了幾個常見情境會使用的防火牆類型來協助初學的使用者撰寫合適的規則集。IPFW 提供了強大的語法讓進階的使用者可以用來自訂符合環境安全性要求的規則集。

本節將介紹如何開啟 IPFW、規則語法的概要以及示範幾種常見情境所使用的規則集。

[[firewalls-ipfw-enable]]
=== 開啟 IPFW

IPFW 已內建於 FreeBSD 基本安裝中，以可載入核心模組的形式提供，因此不需要自訂核心即可啟用 IPFW。

若您希望將 IPFW 支援靜態編譯進自訂核心，請參閱 <<firewalls-ipfw-kernelconfig>>。

若要設定系統在開機時啟用 IPFW，請在 [.filename]#/etc/rc.conf# 中加入 `firewall_enable="YES"`：

[source,shell]
....
# sysrc firewall_enable="YES"
....

若要使用 FreeBSD 提供的預設防火牆類型，請再加入一行指定類型：

[source,shell]
....
# sysrc firewall_type="open"
....

可用的類型如下：

* `open`：允許所有流量通過。
* `client`：僅保護本機。
* `simple`：保護整個網路。
* `closed`：完全停用 IP 流量，僅保留 loopback 介面。
* `workstation`：使用具狀態規則僅保護本機。
* `UNKNOWN`：停用防火牆規則的載入。
* [.filename]#filename#：包含防火牆規則集的檔案完整路徑。

如果 `firewall_type` 設為 `client` 或 `simple`，請修改 [.filename]#/etc/rc.firewall# 中的預設規則以符合系統設定。

請注意 `filename` 類型是用來載入自訂規則集的。

另一種載入自訂規則集的方式是將 `firewall_script` 變數設為包含 IPFW 指令的 _可執行 Script_ 的絕對路徑。本節的範例假設 `firewall_script` 設定為 [.filename]#/etc/ipfw.rules#：

[source,shell]
....
# sysrc firewall_script="/etc/ipfw.rules"
....

若要透過 man:syslogd[8] 啟用記錄功能，請加入這一行：

[source,shell]
....
# sysrc firewall_logging="YES"
....

[WARNING]
====

只有帶有 `log` 選項的防火牆規則才會被記錄。預設規則不包含此選項，必須手動加入。因此建議編輯預設規則集以加入記錄功能。此外，如果記錄儲存在獨立的檔案中，可能還需要設定記錄輪替。
====

[.filename]#/etc/rc.conf# 中沒有用來設定記錄上限的變數。若要限制每次連線嘗試時某條規則被記錄的次數，請在 [.filename]#/etc/sysctl.conf# 中加入以下設定：

[source,shell]
....
# echo "net.inet.ip.fw.verbose_limit=5" >> /etc/sysctl.conf
....

若要改用名為 `ipfw0` 的專用介面來啟用記錄，請在 [.filename]#/etc/rc.conf# 中改加入這一行：

[source,shell]
....
# sysrc firewall_logif="YES"
....

接著使用 tcpdump 查看記錄的內容：

[source,shell]
....
# tcpdump -t -n -i ipfw0
....

[TIP]
====

除非有 tcpdump 正在監聽，否則記錄功能不會產生額外負擔。
====

儲存所需的編輯後，啟動防火牆。若要立即啟用記錄上限，也請設定上述的 `sysctl` 值：

[source,shell]
....
# service ipfw start
# sysctl net.inet.ip.fw.verbose_limit=5
....

[[firewalls-ipfw-rules]]
=== IPFW 規則語法

當封包進入 IPFW 防火牆時，會從規則集的第一條規則開始逐條比對，由上而下依序進行。當封包符合某條規則的篩選條件時，便會執行該規則的動作，且該封包的規則集搜尋隨即結束。這就是所謂的「先符合者優先」。如果封包沒有符合任何規則，就會被 IPFW 強制存在的預設規則 65535 攔截，該規則會拒絕所有封包並靜默丟棄。不過，如果封包符合的規則包含 `count`、`skipto` 或 `tee` 等關鍵字，搜尋會繼續進行。關於這些關鍵字如何影響規則處理，請參閱 man:ipfw[8]。

建立 IPFW 規則時，關鍵字必須按照以下順序撰寫。有些關鍵字是必要的，有些則是選用的。以大寫顯示的字詞代表變數，以小寫顯示的字詞則必須出現在其後變數的前面。`#` 符號用來標記註解的開頭，可以出現在規則的結尾或獨立一行。空白行會被忽略。

_CMD RULE_NUMBER set SET_NUMBER ACTION log LOG_AMOUNT PROTO from SRC SRC_PORT to DST DST_PORT OPTIONS_

本節提供這些關鍵字及其選項的概要說明，並非所有可用選項的完整列表。如需建立 IPFW 規則時可使用的規則語法完整說明，請參閱 man:ipfw[8]。

CMD::
每條規則都必須以 [parameter]#ipfw add# 開頭。

RULE_NUMBER::
每條規則都有一個從 `1` 到 `65534` 的編號。此編號用來指定規則的處理順序。多條規則可以使用相同的編號，此時會按照加入的先後順序來套用。

SET_NUMBER::
每條規則都屬於一個從 `0` 到 `31` 的集合編號。集合可以個別停用或啟用，因此能快速新增或刪除一整組規則。如果未指定 SET_NUMBER，規則會被加入集合 `0`。

ACTION::
規則可以搭配以下其中一個動作。當封包符合規則的篩選條件時，便會執行所指定的動作。
+
[parameter]#allow | accept | pass | permit#：這些關鍵字功能相同，會允許符合規則的封包通過。
+
[parameter]#check-state#：比對封包與動態狀態表。如果找到相符的項目，便執行產生該動態規則的原始規則所關聯的動作，否則繼續比對下一條規則。`check-state` 規則沒有篩選條件。如果規則集中沒有 `check-state` 規則，動態規則表會在第一條 `keep-state` 或 `limit` 規則時被檢查。
+
[parameter]#count#：為所有符合規則的封包更新計數器。搜尋會繼續比對下一條規則。
+
[parameter]#deny | drop#：這兩個關鍵字都會靜默丟棄符合此規則的封包。
+
還有其他可用的動作，詳情請參閱 man:ipfw[8]。

LOG_AMOUNT::
當封包符合帶有 `log` 關鍵字的規則時，會以 `SECURITY` 設施名稱將訊息記錄到 man:syslogd[8]。只有在該條規則已記錄的封包數量未超過指定的 LOG_AMOUNT 時才會記錄。如果未指定 LOG_AMOUNT，上限會取自 `net.inet.ip.fw.verbose_limit` 的值。設為零則取消記錄上限。達到上限後，可以使用 `ipfw resetlog` 清除該規則的記錄計數器或封包計數器來重新啟用記錄。
+

[NOTE]
====
記錄是在所有其他封包比對條件都滿足之後、對封包執行最終動作之前進行的。由管理者決定要對哪些規則啟用記錄。
====

PROTO::
此選用值可用來指定 [.filename]#/etc/protocols# 中的任何通訊協定名稱或編號。

SRC::
`from` 關鍵字後面必須接來源位址或代表來源位址的關鍵字。位址可以用 `any`、`me`（本系統任何網路介面上設定的位址）、`me6`（本系統任何網路介面上設定的 IPv6 位址）或 `table` 加上包含位址列表的查詢表編號來表示。指定 IP 位址時，可以選擇性地在後面加上 CIDR 遮罩或子網路遮罩。例如 `1.2.3.4/25` 或 `1.2.3.4:255.255.255.128`。

SRC_PORT::
可以選擇性地使用 [.filename]#/etc/services# 中的連接埠號碼或名稱來指定來源連接埠。

DST::
`to` 關鍵字後面必須接目的位址或代表目的位址的關鍵字。SRC 段落中說明的關鍵字和位址格式同樣適用於目的端。

DST_PORT::
可以選擇性地使用 [.filename]#/etc/services# 中的連接埠號碼或名稱來指定目的連接埠。

OPTIONS::
來源和目的之後可以接數個關鍵字。顧名思義，OPTIONS 是選用的。常用的選項包括 `in` 或 `out`（指定封包流向）、`icmptypes` 加上 ICMP 訊息類型，以及 `keep-state`。
+
當封包符合 [parameter]#keep-state# 規則時，防火牆會建立一條動態規則，比對使用相同通訊協定在來源與目的位址及連接埠之間雙向流通的流量。
+
動態規則機制容易受到 SYN 洪水攻擊的影響，這種攻擊會建立大量動態規則而耗盡資源。若要以 IPFW 對抗這類攻擊，請使用 `limit`。此選項會檢查已開啟的動態規則，計算此規則與 IP 位址組合出現的次數，藉此限制同時進行的連線數量。如果計數超過 `limit` 指定的值，該封包就會被丟棄。
+
有數十種 OPTIONS 可用，各選項的說明請參閱 man:ipfw[8]。

=== 範例規則集

本節示範如何建立一個名為 [.filename]#/etc/ipfw.rules# 的範例具狀態防火牆規則集 Script。在這個範例中，所有連線規則都使用 `in` 或 `out` 來明確指定方向，也使用 `via` _interface-name_ 來指定封包經過的網路介面。

[NOTE]
====
初次建立或測試防火牆規則集時，可以考慮暫時設定這個調校參數：

[.programlisting]
....
net.inet.ip.fw.default_to_accept="1"
....

這會將 man:ipfw[8] 的預設政策設為比預設的 `deny ip from any to any` 更為寬鬆，讓重新開機後不容易把自己鎖在系統外面。
====

防火牆 Script 開頭先宣告這是一個 Bourne shell Script，並清除所有既有的規則。接著建立 `cmd` 變數，這樣就不需要在每條規則開頭都輸入 `ipfw add`。此外也定義了 `pif` 變數，代表連接到網際網路的網路介面名稱。

[.programlisting]
....
#!/bin/sh
# Flush out the list before we begin.
ipfw -q -f flush

# Set rules command prefix
cmd="ipfw -q add"
pif="dc0"     # interface name of NIC attached to Internet
....

前兩條規則允許受信任的內部網路介面和 loopback 介面上的所有流量：

[.programlisting]
....
# Change xl0 to LAN NIC interface name
$cmd 00005 allow all from any to any via xl0

# No restrictions on Loopback Interface
$cmd 00010 allow all from any to any via lo0
....

下一條規則會在封包符合動態規則表中的既有項目時允許其通過：

[.programlisting]
....
$cmd 00101 check-state
....

下一組規則定義了內部系統可以對網際網路上的主機建立哪些具狀態連線：

[.programlisting]
....
# Allow access to public DNS
# Replace x.x.x.x with the IP address of a public DNS server
# and repeat for each DNS server in /etc/resolv.conf
$cmd 00110 allow tcp from any to x.x.x.x 53 out via $pif setup keep-state
$cmd 00111 allow udp from any to x.x.x.x 53 out via $pif keep-state

# Allow access to ISP's DHCP server for cable/DSL configurations.
# Use the first rule and check log for IP address.
# Then, uncomment the second rule, input the IP address, and delete the first rule
$cmd 00120 allow log udp from any to any 67 out via $pif keep-state
#$cmd 00120 allow udp from any to x.x.x.x 67 out via $pif keep-state

# Allow outbound HTTP and HTTPS connections
$cmd 00200 allow tcp from any to any 80 out via $pif setup keep-state
$cmd 00220 allow tcp from any to any 443 out via $pif setup keep-state

# Allow outbound email connections
$cmd 00230 allow tcp from any to any 25 out via $pif setup keep-state
$cmd 00231 allow tcp from any to any 110 out via $pif setup keep-state

# Allow outbound ping
$cmd 00250 allow icmp from any to any out via $pif keep-state

# Allow outbound NTP
$cmd 00260 allow udp from any to any 123 out via $pif keep-state

# Allow outbound SSH
$cmd 00280 allow tcp from any to any 22 out via $pif setup keep-state

# deny and log all other outbound connections
$cmd 00299 deny log all from any to any out via $pif
....

下一組規則控制從網際網路主機到內部網路的連線。首先拒絕通常與攻擊行為有關的封包，然後明確允許特定類型的連線。所有從網際網路發起的已授權服務都使用 `limit` 來防止洪水攻擊。

[.programlisting]
....
# Deny all inbound traffic from non-routable reserved address spaces
$cmd 00300 deny all from 192.168.0.0/16 to any in via $pif     #RFC 1918 private IP
$cmd 00301 deny all from 172.16.0.0/12 to any in via $pif      #RFC 1918 private IP
$cmd 00302 deny all from 10.0.0.0/8 to any in via $pif         #RFC 1918 private IP
$cmd 00303 deny all from 127.0.0.0/8 to any in via $pif        #loopback
$cmd 00304 deny all from 0.0.0.0/8 to any in via $pif          #loopback
$cmd 00305 deny all from 169.254.0.0/16 to any in via $pif     #DHCP auto-config
$cmd 00306 deny all from 192.0.2.0/24 to any in via $pif       #reserved for docs
$cmd 00307 deny all from 204.152.64.0/23 to any in via $pif    #Sun cluster interconnect
$cmd 00308 deny all from 224.0.0.0/3 to any in via $pif        #Class D & E multicast

# Deny public pings
$cmd 00310 deny icmp from any to any in via $pif

# Deny ident
$cmd 00315 deny tcp from any to any 113 in via $pif

# Deny all Netbios services.
$cmd 00320 deny tcp from any to any 137 in via $pif
$cmd 00321 deny tcp from any to any 138 in via $pif
$cmd 00322 deny tcp from any to any 139 in via $pif
$cmd 00323 deny tcp from any to any 81 in via $pif

# Deny fragments
$cmd 00330 deny all from any to any frag in via $pif

# Deny ACK packets that did not match the dynamic rule table
$cmd 00332 deny tcp from any to any established in via $pif

# Allow traffic from ISP's DHCP server.
# Replace x.x.x.x with the same IP address used in rule 00120.
#$cmd 00360 allow udp from any to x.x.x.x 67 in via $pif keep-state

# Allow HTTP connections to internal web server
$cmd 00400 allow tcp from any to me 80 in via $pif setup limit src-addr 2

# Allow inbound SSH connections
$cmd 00410 allow tcp from any to me 22 in via $pif setup limit src-addr 2

# Reject and log all other incoming connections
$cmd 00499 deny log all from any to any in via $pif
....

最後一條規則會記錄所有未符合規則集中任何規則的封包：

[.programlisting]
....
# Everything else is denied and logged
$cmd 00999 deny log all from any to any
....

[[in-kernel-nat]]
=== 核心內 NAT

FreeBSD 的 IPFW 防火牆有兩種網路位址轉譯 (NAT) 的實作方式：一種是 Userland 的 man:natd[8] daemon，另一種是較新的 IPFW 內建 NAT 功能，也稱為核心內 NAT。兩者都與 IPFW 搭配運作以提供網路位址轉譯。這可用來實現網路連線共享的方案，讓多台內部電腦透過單一公用 IP 位址連接網際網路。

要達成此目的，連接到網際網路的 FreeBSD 機器必須擔任閘道的角色。這台系統必須有兩張網路卡，一張連接到網際網路，另一張連接到內部區域網路。區域網路上的每台機器都應分配一個私有網路位址空間的 IP 位址，如 https://www.ietf.org/rfc/rfc1918.txt[RFC 1918] 所定義。

需要一些額外的設定才能啟用 IPFW 的核心內 NAT 功能。若要在開機時啟用核心內 NAT 支援，必須在 [.filename]#/etc/rc.conf# 中設定以下項目：

[.programlisting]
....
gateway_enable="YES"
firewall_enable="YES"
firewall_nat_enable="YES"
....

[NOTE]
====
當未設定 `firewall_enable` 但設定了 `firewall_nat_enable` 時，不會有任何效果，因為核心內 NAT 的實作僅與 IPFW 相容。
====

當規則集包含具狀態規則時，NAT 規則的位置至關重要，且會使用 `skipto` 動作。`skipto` 動作需要一個規則編號以便知道要跳轉到哪條規則。此外，由於 man:libalias[3] 的架構（這是一個以核心模組形式實作的函式庫，供 IPFW 的核心內 NAT 功能使用），必須停用 TCP 分段卸載（TSO）。TSO 可以使用 man:ifconfig[8] 針對個別網路介面停用，或使用 man:sysctl[8] 在全系統範圍停用。若要在全系統停用 TSO，必須在 [.filename]#/etc/sysctl.conf# 中設定以下項目：

[.programlisting]
....
net.inet.tcp.tso="0"
....

以下範例以前一節所示的防火牆規則集為基礎，新增了一些項目並修改了一些既有規則，以便為核心內 NAT 設定防火牆。首先加入一些額外的變數，分別代表要跳轉到的規則編號、`keep-state` 選項，以及用來減少規則數量的 TCP 連接埠列表。

[.programlisting]
....
#!/bin/sh
ipfw -q -f flush
cmd="ipfw -q add"
skip="skipto 1000"
pif=dc0
ks="keep-state"
good_tcpo="22,25,37,53,80,443,110"
....

同時也需要設定一個 NAT 實例。核心內 NAT 可以擁有多個 NAT 實例，各自有獨立的設定。不過在本範例中只需要一個 NAT 實例，即 NAT 實例編號 1。設定時需要幾個參數和旗標，例如：`if` 指定公用網路介面、`same_ports` 確保別名連接埠與本地連接埠編號對應一致、`unreg_only` 使 NAT 實例僅處理未註冊的（私有）位址空間，以及 `reset` 讓 IPFW 機器的公用 IP 位址變更時 NAT 實例仍能正常運作。所有可傳入單一 NAT 實例設定的選項，請參閱 man:ipfw[8]。此外，由於具狀態 NAT 防火牆的特性，必須允許已轉譯的封包重新注入防火牆以進行後續處理，這可以在防火牆 Script 開頭停用 `one_pass` 行為來達成。

[.programlisting]
....
ipfw disable one_pass
ipfw -q nat 1 config if $pif same_ports unreg_only reset
....

入站 NAT 規則要插在允許受信任介面和 loopback 介面所有流量的兩條規則以及重組規則 _之後_，但在 `check-state` 規則 _之前_。重要的是，為此 NAT 規則選擇的規則編號（本範例中為 `100`）必須大於前三條規則，且小於 `check-state` 規則。此外，由於核心內 NAT 的行為特性，建議在第一條 NAT 規則之前、允許受信任介面流量的規則之後放置一條重組規則。一般情況下不應發生 IP 分片，但處理 IPSEC/ESP/GRE 通道流量時可能會發生，因此在將完整封包交給核心內 NAT 引擎之前，需要先重組分片。

[NOTE]
====
使用 Userland 的 man:natd[8] 時不需要重組規則，因為 IPFW `divert` 動作的內部運作已自動處理此事，man:ipfw[8] 中也有說明。

目前的 NAT 實例編號和 NAT 規則編號與 [.filename]#rc.firewall# 建立的預設 NAT 實例編號和規則編號並不一致，[.filename]#rc.firewall# 是用來設定 FreeBSD 內建預設防火牆規則集的 Script。
====

[.programlisting]
....
$cmd 005 allow all from any to any via xl0  # exclude LAN traffic
$cmd 010 allow all from any to any via lo0  # exclude loopback traffic
$cmd 099 reass all from any to any in       # reassamble inbound packets
$cmd 100 nat 1 ip from any to any in via $pif # NAT any inbound packets
# Allow the packet through if it has an existing entry in the dynamic rules table
$cmd 101 check-state
....

出站規則經過修改，將 `allow` 動作替換為 `$skip` 變數，表示規則處理將在規則 `1000` 繼續。原本的七條 `tcp` 規則已被規則 `125` 取代，因為 `$good_tcpo` 變數包含了七個允許的出站連接埠。

[NOTE]
====
請記住，IPFW 防火牆的效能在很大程度上取決於規則集中的規則數量。
====

[.programlisting]
....
# Authorized outbound packets
$cmd 120 $skip udp from any to x.x.x.x 53 out via $pif $ks
$cmd 121 $skip udp from any to x.x.x.x 67 out via $pif $ks
$cmd 125 $skip tcp from any to any $good_tcpo out via $pif setup $ks
$cmd 130 $skip icmp from any to any out via $pif $ks
....

入站規則維持不變，唯一例外是最後一條規則移除了 `via $pif`，以便同時攔截入站和出站的規則。NAT 規則必須跟在這最後一條出站規則之後，編號必須大於該規則，且該規則編號必須被 `skipto` 動作所參照。在這個規則集中，規則編號 `1000` 負責將所有封包傳送到我們設定好的實例進行 NAT 處理。下一條規則則允許所有經過 NAT 處理的封包通過。

[.programlisting]
....
$cmd 999 deny log all from any to any
$cmd 1000 nat 1 ip from any to any out via $pif # skipto location for outbound stateful rules
$cmd 1001 allow ip from any to any
....

在這個範例中，規則 `100`、`101`、`125`、`1000` 和 `1001` 控制出站與入站封包的位址轉譯，使得動態狀態表中的項目始終記錄的是私有區域網路 IP 位址。

假設有一個內部網路的瀏覽器透過連接埠 80 發起一個新的出站 HTTP 連線。當第一個出站封包進入防火牆時，不會符合規則 `100`，因為它是往外而非往內的。它也不符合規則 `101`，因為這是第一個封包，尚未被記錄到動態狀態表中。封包最終符合規則 `125`，因為它是透過允許的連接埠出站，且來源 IP 位址來自內部區域網路。符合此規則時會執行兩個動作：首先，`keep-state` 動作會在動態狀態表中新增一筆項目，然後執行指定的動作 `skipto rule 1000`。接著封包經過 NAT 處理後送往網際網路。封包到達目的端網頁伺服器後，會產生回應封包並送回。這個新封包從規則集的頂端開始處理，符合規則 `100` 並將其目的 IP 位址映射回原始的內部位址。然後由 `check-state` 規則處理，在表中找到對應的既有連線，隨即放行到區域網路。

在入站方面，規則集必須拒絕不良封包並僅允許已授權的服務。符合入站規則的封包會被記錄到動態狀態表中，然後放行到區域網路。其回應封包會被 `check-state` 規則辨識為屬於既有連線，接著送到規則 `1000` 進行 NAT 處理，然後才從出站介面送出。

[NOTE]
====
從 Userland 的 man:natd[8] 轉換到核心內 NAT 乍看之下似乎很順暢，但有一個小地方需要注意。使用 GENERIC 核心時，當 [.filename]#rc.conf# 中啟用了 `firewall_nat_enable`，IPFW 會載入 [.filename]#libalias.ko# 核心模組。但是，載入的模組僅提供基本的 NAT 功能，而 Userland 的 man:natd[8] 實作則可透過其 Userland 函式庫提供全部功能，無需額外設定。所謂的全部功能是指除了標準的 [.filename]#libalias.ko# 核心模組之外，還可視需要額外載入以下核心模組：[.filename]#alias_cuseeme.ko#、[.filename]#alias_ftp.ko#、[.filename]#alias_bbt.ko#、[.filename]#skinny.ko#、[.filename]#irc.ko#、[.filename]#alias_pptp.ko# 和 [.filename]#alias_smedia.ko#，透過 [.filename]#rc.conf# 中的 `kld_list` 指示來模擬 Userland 實作的完整功能。如果使用自訂核心，可以透過 `option LIBALIAS` 將 Userland 函式庫的全部功能編譯進核心中。
====

==== Port 重新導向

NAT 的一般缺點是區域網路上的用戶端無法從網際網路存取。區域網路上的用戶端可以向外建立連線，但無法接收傳入的連線。如果想在區域網路上的某台用戶端機器執行網際網路服務，這就會是個問題。簡單的解決方式是將提供 NAT 的機器上選定的網際網路連接埠重新導向到區域網路用戶端。

舉例來說，用戶端 `A` 上執行著 IRC 伺服器，用戶端 `B` 上執行著網頁伺服器。為了讓這些服務正常運作，連接埠 6667 (IRC) 和 80 (HTTP) 收到的連線必須分別重新導向到對應的機器。

使用核心內 NAT 時，所有設定都在 NAT 實例設定中完成。核心內 NAT 實例可用選項的完整列表，請參閱 man:ipfw[8]。IPFW 語法遵循 natd 的語法。`redirect_port` 的語法如下：

[.programlisting]
....
redirect_port proto targetIP:targetPORT[-targetPORT]
  [aliasIP:]aliasPORT[-aliasPORT]
  [remoteIP[:remotePORT[-remotePORT]]]
....

要設定上述範例，參數應為：

[.programlisting]
....
redirect_port tcp 192.168.0.2:6667 6667
redirect_port tcp 192.168.0.3:80 80
....

將這些參數加入上述規則集中 NAT 實例 1 的設定後，TCP 連接埠就會被轉送到執行 IRC 和 HTTP 服務的區域網路用戶端機器。

[.programlisting]
....
ipfw -q nat 1 config if $pif same_ports unreg_only reset \
  redirect_port tcp 192.168.0.2:6667 6667 \
  redirect_port tcp 192.1683.0.3:80 80
....

透過 `redirect_port` 也可以指定連接埠範圍而非個別連接埠。例如 _tcp 192.168.0.2:2000-3000 2000-3000_ 會將連接埠 2000 到 3000 收到的所有連線重新導向到用戶端 `A` 的連接埠 2000 到 3000。

==== 位址重新導向

當有多個 IP 位址可用時，位址重新導向就很有用。man:ipfw[8] 可以為每個區域網路用戶端分配各自的外部 IP 位址，然後將區域網路用戶端的出站封包改寫為正確的外部 IP 位址，並將該特定 IP 位址收到的所有傳入流量重新導向回對應的區域網路用戶端。這也稱為靜態 NAT。舉例來說，如果有 `128.1.1.1`、`128.1.1.2` 和 `128.1.1.3` 三個 IP 位址可用，`128.1.1.1` 可作為 man:ipfw[8] 機器的外部 IP 位址，而 `128.1.1.2` 和 `128.1.1.3` 則分別轉送回區域網路用戶端 `A` 和 `B`。

`redirect_address` 的語法如下，其中 `localIP` 是區域網路用戶端的內部 IP 位址，`publicIP` 是對應到該區域網路用戶端的外部 IP 位址。

[.programlisting]
....
redirect_address localIP publicIP
....

以此範例來說，參數如下：

[.programlisting]
....
redirect_address 192.168.0.2 128.1.1.2
redirect_address 192.168.0.3 128.1.1.3
....

與 `redirect_port` 一樣，這些參數放在 NAT 實例的設定中。使用位址重新導向時，不需要連接埠重新導向，因為特定 IP 位址收到的所有資料都會被重新導向。

man:ipfw[8] 機器上的外部 IP 位址必須處於啟用狀態並以別名方式綁定到外部網路介面。詳情請參閱 man:rc.conf[5]。

==== Userspace NAT

首先說明一點：Userspace 的 NAT 實作 man:natd[8] 的負擔比核心內 NAT 更大。man:natd[8] 在轉譯封包時，封包必須從核心複製到 Userspace 再複製回來，這會帶來核心內 NAT 所沒有的額外負擔。

要在開機時啟動 Userspace 的 NAT daemon man:natd[8] 需在 [.filename]#/etc/rc.conf# 中做以下最小設定，其中 `natd_interface` 要設成連接到網際網路的 NIC 名稱，man:rc[8] script of man:natd[8] 會自動檢查是否有使用動態 IP 位址，並且自行設定並處理。

[.programlisting]
....
gateway_enable="YES"
natd_enable="YES"
natd_interface="rl0"
....

一般來說，前面為核心內 NAT 說明的規則集也可以搭配 man:natd[8] 使用。唯一的例外是核心內 NAT 實例的設定 `(ipfw -q nat 1 config ...)` 不再適用，規則編號 100 和 1000 需要稍作修改如下所示，而且重組規則 99 也不再需要，因為所使用的 `divert` 動作已涵蓋分片處理。

[.programlisting]
....
$cmd 100 divert natd ip from any to any in via $pif
$cmd 1000 divert natd ip from any to any out via $pif
....

若要設定連接埠或位址重新導向，使用的語法與核心內 NAT 類似。不過現在不是像核心內 NAT 那樣在規則集 Script 中指定設定，man:natd[8] 的設定最好寫在設定檔中。為此，需要透過 [.filename]#/etc/rc.conf# 傳入一個額外的旗標來指定設定檔的路徑。

[.programlisting]
....
natd_flags="-f /etc/natd.conf"
....

[NOTE]
====
指定的檔案必須包含一份設定選項列表，每行一個。關於設定檔和可用變數的更多資訊，請參閱 man:natd[8]。以下是兩個範例項目，每行一個：

[.programlisting]
....
redirect_port tcp 192.168.0.2:6667 6667
redirect_address 192.168.0.3 128.1.1.3
....

====

[[firewalls-ipfw-cmd]]
=== IPFW 指令

`ipfw` 可以在防火牆運作中手動新增或刪除單條規則。但這種方式的問題是，所有變更在系統重新開機後都會遺失。建議改為將所有規則寫在檔案中，利用該檔案在開機時載入規則，並在檔案變更時取代目前正在運作的防火牆規則。

`ipfw` 也是在主控台畫面上顯示運作中防火牆規則的好工具。IPFW 的計帳設施會為每條規則動態建立一個計數器，計算符合該規則的每個封包。在測試規則的過程中，列出規則及其計數器是判斷規則是否如預期運作的一種方式。

依序列出所有運作中的規則：

[source,shell]
....
# ipfw list
....

列出所有運作中的規則，並顯示每條規則最後一次被符合的時間戳記：

[source,shell]
....
# ipfw -t list
....

下一個範例列出計帳資訊和已符合規則的封包計數，以及規則本身。第一欄是規則編號，接著是符合的封包數和位元組數，最後是規則本身。

[source,shell]
....
# ipfw -a list
....

除了靜態規則外，也列出動態規則：

[source,shell]
....
# ipfw -d list
....

同時顯示已過期的動態規則：

[source,shell]
....
# ipfw -d -e list
....

將計數器歸零：

[source,shell]
....
# ipfw zero
....

僅將規則編號 _NUM_ 的計數器歸零：

[source,shell]
....
# ipfw zero NUM
....

==== 記錄防火牆訊息

即使啟用了記錄設施，IPFW 也不會自動產生任何規則記錄。防火牆管理者決定規則集中哪些規則要記錄，並對這些規則加入 `log` 關鍵字。通常只記錄拒絕規則。慣例做法是複製一份「ipfw default deny everything」規則，加上 `log` 關鍵字作為規則集的最後一條規則。這樣就能看到所有未符合規則集中任何規則的封包。

記錄是一把雙面刃。如果不小心，過多的記錄資料或 DoS 攻擊可能會把磁碟塞滿記錄檔。記錄訊息不僅會寫入 syslogd，也會顯示在 root 主控台畫面上，很快就會令人困擾。

`IPFIREWALL_VERBOSE_LIMIT=5` 核心選項會限制針對特定規則的封包比對，連續送往 man:syslogd[8] 的訊息數量。在核心中啟用此選項後，關於特定規則的連續訊息數量會被限制在指定的數字。200 條相同的記錄訊息毫無意義。此選項設為五時，關於特定規則的連續訊息只會有五條記錄到 syslogd，其餘相同的連續訊息會被計數，並以類似以下的詞句發送到 syslogd：

[.programlisting]
....
last message repeated 45 times
....

所有已記錄的封包訊息預設會寫入 [.filename]#/var/log/security#，此路徑定義在 [.filename]#/etc/syslog.conf# 中。

[[firewalls-ipfw-rules-script]]
==== 建立規則 Script

大多數有經驗的 IPFW 使用者會建立一個包含規則的檔案，並以可作為 Script 執行的方式來撰寫。這麼做的主要好處是防火牆規則可以大量更新，不需要重新開機即可生效。這個方式在測試新規則時很方便，因為程序可以視需要執行多次。由於是 Script，可以使用符號替換，將常用的值代入多條規則中。

此範例 Script 的語法相容於 man:sh[1]、man:csh[1] 和 man:tcsh[1] shell。符號替換欄位以錢號 ($) 為前綴。符號欄位本身沒有 $ 前綴。用來填入符號欄位的值必須以雙引號 ("") 括起。

規則檔案的開頭如下：

[.programlisting]
....
############### start of example ipfw rules script #############
#
ipfw -q -f flush       # Delete all rules
# Set defaults
oif="tun0"             # out interface
odns="192.0.2.11"      # ISP's DNS server IP address
cmd="ipfw -q add "     # build rule prefix
ks="keep-state"        # just too lazy to key this each time
$cmd 00500 check-state
$cmd 00502 deny all from any to any frag
$cmd 00501 deny tcp from any to any established
$cmd 00600 allow tcp from any to any 80 out via $oif setup $ks
$cmd 00610 allow tcp from any to $odns 53 out via $oif setup $ks
$cmd 00611 allow udp from any to $odns 53 out via $oif $ks
################### End of example ipfw rules script ############
....

規則本身不是重點，此範例的重點是展示符號替換欄位如何被填入。

如果上述範例存放在 [.filename]#/etc/ipfw.rules# 中，可以使用以下指令重新載入規則：

[source,shell]
....
# sh /etc/ipfw.rules
....

[.filename]#/etc/ipfw.rules# 可以放在任何位置，檔案名稱也不限。

同樣的事情也可以手動執行以下指令來完成：

[source,shell]
....
# ipfw -q -f flush
# ipfw -q add check-state
# ipfw -q add deny all from any to any frag
# ipfw -q add deny tcp from any to any established
# ipfw -q add allow tcp from any to any 80 out via tun0 setup keep-state
# ipfw -q add allow tcp from any to 192.0.2.11 53 out via tun0 setup keep-state
# ipfw -q add 00611 allow udp from any to 192.0.2.11 53 out via tun0 keep-state
....

[[firewalls-ipfw-kernelconfig]]
=== IPFW 核心選項

若要將 IPFW 支援靜態編譯進自訂核心，請參閱 crossref:kernelconfig[kernelconfig,設定 FreeBSD 核心] 中的說明。以下是自訂核心設定檔可用的選項：

[.programlisting]
....
options    IPFIREWALL			# enables IPFW
options    IPFIREWALL_VERBOSE		# enables logging for rules with log keyword to syslogd(8)
options    IPFIREWALL_VERBOSE_LIMIT=5	# limits number of logged packets per-entry
options    IPFIREWALL_DEFAULT_TO_ACCEPT # sets default policy to pass what is not explicitly denied
options    IPFIREWALL_NAT		# enables in-kernel NAT support
options    IPFIREWALL_NAT64		# enables in-kernel NAT64 support
options    IPFIREWALL_NPTV6		# enables in-kernel IPv6 NPT support
options    IPFIREWALL_PMOD		# enables protocols modification module support
options    IPDIVERT			# enables NAT through natd(8)
....

[NOTE]
====
IPFW 可以作為核心模組載入：上述選項預設會編譯為模組，也可以在執行期間透過調校參數來設定。
====

[[firewalls-ipf]]
== IPFILTER (IPF)

IPFILTER 即為 IPF，是一套跨平台、開放源碼的防火牆，已被移植到各種作業系統，包含 FreeBSD, NetBSD, OpenBSD 與 Solaris(TM)。

IPFILTER 是核心端 (Kernel-side) 的防火牆且 NAT 機制可由 Userland 的程式控制與監控，防火牆規則可以使用 ipf 設定或刪除，NAT 規則可以使用 ipnat 設定或刪除，可使用 ipfstat 來列出 IPFILTER 在核心部份的執行期統計資訊，可使用 ipmon 來記錄 IPFILTER 動作到系統記錄檔。

IPF 原來是以 "最後一個符合的條件優先" 的規則處理邏輯所撰寫並只能使用無狀態 (Stateless) 的規則，之後 IPF 才被加強支援快速 (`quick`) 與保留狀態 (`keep state`) 的選項。

IPF FAQ 位於 http://www.phildev.net/ipf/index.html[http://www.phildev.net/ipf/index.html]，可搜尋的 IPFilter 郵遞論壇封存資料可至 http://marc.info/?l=ipfilter[http://marc.info/?l=ipfilter] 取得。

由於 FreeBSD 也支援 IPF 因此操作手冊特別在此章節對此介紹，本節提供幾個有使用快速 (`quick`) 與保留狀態 (`keep state`) 選項的規則範例。

=== 開啟 IPF

IPF 已包含在 FreeBSD 基本安裝中，以可載入核心模組的形式提供，這表示不需要自訂核心就能啟用 IPF。

若偏好將 IPF 支援靜態編譯進自訂核心，請參閱 crossref:kernelconfig[kernelconfig,設定 FreeBSD 核心] 中的說明。以下為可用的核心選項：

[.programlisting]
....
options IPFILTER
options IPFILTER_LOG
options IPFILTER_LOOKUP
options IPFILTER_DEFAULT_BLOCK
....

其中 `options IPFILTER` 啟用 IPFILTER 支援，`options IPFILTER_LOG` 使用 [.filename]#ipl# 封包記錄虛擬裝置為每條含有 `log` 關鍵字的規則啟用 IPF 記錄功能，`IPFILTER_LOOKUP` 啟用 IP 集區以加速 IP 查詢，而 `options IPFILTER_DEFAULT_BLOCK` 則變更預設行為，使任何不符合防火牆 `pass` 規則的封包都被阻擋。

要設定系統在開機時啟用 IPF，請將以下項目加入 [.filename]#/etc/rc.conf#。這些項目也會啟用記錄功能及 `default pass all`。若要在不編譯自訂核心的情況下將預設策略改為 `block all`，請記得在規則集的最後加上一條 `block all` 規則。

[.programlisting]
....
ipfilter_enable="YES"             # Start ipf firewall
ipfilter_rules="/etc/ipf.rules"   # loads rules definition text file
ipmon_enable="YES"                # Start IP monitor log
ipmon_flags="-Ds"                 # D = start as daemon
                                  # s = log to syslog
                                  # v = log tcp window, ack, seq
                                  # n = map IP & port to names
....

若需要 NAT 功能，也請加入以下這幾行：

[.programlisting]
....
gateway_enable="YES"              # Enable as LAN gateway
ipnat_enable="YES"                # Start ipnat function
ipnat_rules="/etc/ipnat.rules"    # rules definition file for ipnat
....

接著，立即啟動 IPF：

[.programlisting]
....
# service ipfilter start
....

要載入防火牆規則，請使用 `ipf` 指定規則集檔案名稱。以下指令可用來取代目前正在執行的防火牆規則：

[source,shell]
....
# ipf -Fa -f /etc/ipf.rules
....

其中 `-Fa` 會清除所有內部規則表，`-f` 則指定要載入的規則檔案。

這樣就能修改自訂規則集，並以全新的規則更新執行中的防火牆，而不需要重新開機。此方法對於測試新規則相當方便，因為可以視需要重複執行。

關於此指令可用的其他旗標，請參閱 man:ipf[8]。

=== IPF 規則語法

本節說明用來建立具狀態規則的 IPF 規則語法。建立規則時請注意，除非規則中有 `quick` 關鍵字，否則每條規則會依序讀取，以_最後一個符合的規則_為準。這表示即使第一條符合的規則是 `pass`，若後面還有符合的 `block` 規則，封包仍然會被丟棄。範例規則集可在 [.filename]#/usr/shared/examples/ipfilter# 中找到。

建立規則時，`#` 字元用來標記註解的開頭，可以出現在規則的結尾以說明該規則的功能，也可以獨立成一行。空白行會被忽略。

規則中使用的關鍵字必須依特定順序由左到右撰寫。部分關鍵字為必要，其餘則為選用。有些關鍵字有子選項，而子選項本身也可能是關鍵字並包含更多子選項。關鍵字的順序如下，其中大寫字母代表變數，小寫字母則必須放在其後方變數之前：

_ACTION DIRECTION OPTIONS proto PROTO_TYPE from SRC_ADDR SRC_PORT to DST_ADDR DST_PORT TCP_FLAG|ICMP_TYPE keep state STATE_

本節說明每個關鍵字及其選項，但並非所有可能選項的完整清單。關於建立 IPF 規則時可使用的完整規則語法說明與各關鍵字的使用範例，請參閱 man:ipf[5]。

ACTION::
動作 (action) 關鍵字指示封包符合該規則時要執行的操作。每條規則都__必須__有一個動作。以下為可辨識的動作：
+
`block`：丟棄封包。
+
`pass`：允許封包通過。
+
`log`：產生一筆記錄。
+
`count`：計算封包數量與位元組數，可用來了解某條規則的使用頻率。
+
`auth`：將封包排入佇列，交由其他程式進一步處理。
+
`call`：存取 IPF 內建的函式，以執行更複雜的動作。
+
`decapsulate`：移除所有標頭，以便處理封包的內容。

DIRECTION::
接著，每條規則必須使用以下其中一個關鍵字明確指定流量方向：
+
`in`：此規則套用於傳入的封包。
+
`out`：此規則套用於傳出的封包。
+
`all`：此規則同時套用於兩個方向。
+
若系統有多個網路介面，可以在方向之後指定介面。例如 `in on fxp0`。

OPTIONS::
選項為非必要項目。不過，若指定多個選項，必須按此處列出的順序使用。
+
`log`：執行指定的 ACTION 時，封包標頭的內容會被寫入 man:ipl[4] 封包記錄虛擬裝置。
+
`quick`：若封包符合此規則，即執行規則指定的 ACTION，不再繼續處理後續的規則。
+
`on`：後面必須接 man:ifconfig[8] 所顯示的介面名稱。只有當封包以指定方向通過指定介面時，此規則才會符合。
+
使用 `log` 關鍵字時，可按以下順序使用這些修飾詞：
+
`body`：表示在標頭之後，會一併記錄封包內容的前 128 位元組。
+
`first`：若 `log` 關鍵字與 `keep state` 選項搭配使用，建議加上此選項，這樣只會記錄觸發的封包，而非每個符合該狀態連線的封包。
+
此外還有其他選項可用來指定錯誤回傳訊息，詳情請參閱 man:ipf[5]。

PROTO_TYPE::
通訊協定類型為選用項目。但如果規則需要指定 SRC_PORT 或 DST_PORT，由於需定義通訊協定類型，此欄位就變成必要的。指定通訊協定類型時，請使用 `proto` 關鍵字，後接通訊協定編號或 [.filename]#/etc/protocols# 中的名稱。常見的通訊協定名稱有 `tcp`、`udp` 或 `icmp`。若指定了 PROTO_TYPE 但未指定 SRC_PORT 或 DST_PORT，該通訊協定的所有連接埠號碼都會符合此規則。

SRC_ADDR::
`from` 關鍵字為必要項目，後面接代表封包來源的關鍵字。來源可以是主機名稱、IP 位址加 CIDR 遮罩、位址集區，或關鍵字 `all`。範例請參閱 man:ipf[5]。
+
對於無法輕易用「點分十進位 / 遮罩長度」表示法表示的 IP 位址範圍，沒有直接的比對方式。可使用 package:net-mgmt/ipcalc[] 套件或 Port 來簡化 CIDR 遮罩的計算。更多資訊可在該工具的網頁取得：http://jodies.de/ipcalc[http://jodies.de/ipcalc]。

SRC_PORT::
來源連接埠號碼為選用項目。但若要使用，規則中必須先定義 PROTO_TYPE。連接埠號碼前面也必須有 `proto` 關鍵字。
+
支援多種比較運算子：`=`（等於）、`!=`（不等於）、`<`（小於）、`>`（大於）、`<=`（小於或等於）、`>=`（大於或等於）。
+
要指定連接埠範圍，請將兩個連接埠號碼放在 `<>`（小於且大於）、`><`（大於且小於）或 `:`（大於或等於且小於或等於）之間。

DST_ADDR::
`to` 關鍵字為必要項目，後面接代表封包目的地的關鍵字。與 SRC_ADDR 類似，可以是主機名稱、IP 位址加 CIDR 遮罩、位址集區，或關鍵字 `all`。

DST_PORT::
與 SRC_PORT 類似，目的地連接埠號碼為選用項目。但若要使用，規則中必須先定義 PROTO_TYPE。連接埠號碼前面也必須有 `proto` 關鍵字。

TCP_FLAG|ICMP_TYPE::
若 PROTO_TYPE 指定為 `tcp`，可以用字母來指定旗標，每個字母代表一個用來判斷連線狀態的 TCP 旗標。可用的值有：`S` (SYN)、`A` (ACK)、`P` (PSH)、`F` (FIN)、`U` (URG)、`R` (RST)、`C` (CWN) 及 `E` (ECN)。
+
若 PROTO_TYPE 指定為 `icmp`，可以指定要比對的 ICMP 類型。可用的類型請參閱 man:ipf[5]。

STATE::
若 `pass` 規則包含 `keep state`，IPF 會在其動態狀態表中新增一筆記錄，並允許後續符合該連線的封包通過。IPF 可追蹤 TCP、UDP 及 ICMP 工作階段的狀態。任何 IPF 能確定屬於進行中工作階段的封包，即使使用不同的通訊協定，也會被允許通過。
+
在 IPF 中，要通過連接公開網際網路介面送出的封包，會先比對動態狀態表。若封包符合進行中工作階段交談的下一個預期封包，就會通過防火牆，同時動態狀態表中的工作階段交談流程狀態也會更新。不屬於任何進行中工作階段的封包，則會比對傳出規則集。從連接公開網際網路的介面傳入的封包，同樣先比對動態狀態表。若封包符合進行中工作階段的下一個預期封包，就通過防火牆並更新動態狀態表中的工作階段交談流程狀態。不屬於任何進行中工作階段的封包，則會比對傳入規則集。
+
`keep state` 之後可以加上多個關鍵字。這些關鍵字用來設定控制具狀態過濾的各種選項，例如連線數量限制或連線存活時間。可用選項及其說明請參閱 man:ipf[5]。

=== 範例規則集

本節示範如何建立一個範例規則集，只允許符合 `pass` 規則的服務通過，其餘全部阻擋。

FreeBSD 使用迴路介面 ([.filename]#lo0#) 及 IP 位址 `127.0.0.1` 進行內部通訊。防火牆規則集必須包含規則，允許這些內部使用的封包自由傳輸：

[.programlisting]
....
# no restrictions on loopback interface
pass in quick on lo0 all
pass out quick on lo0 all
....

連接到網際網路的公開介面用來授權及控制所有傳出與傳入連線的存取。若有一個或多個介面連接到私人網路，這些內部介面可能需要規則來允許來自區域網路的封包在內部網路之間流動，或是流向連接網際網路的介面。規則集應組織為三大區段：受信任的內部介面、通過公開介面的傳出連線、以及通過公開介面的傳入連線。

以下兩條規則允許所有流量通過名為 [.filename]#xl0# 的受信任區域網路介面：

[.programlisting]
....
# no restrictions on inside LAN interface for private network
pass out quick on xl0 all
pass in quick on xl0 all
....

公開介面的傳出及傳入區段規則，應將最常被比對到的規則放在較少被比對到的規則之前，區段中的最後一條規則則負責阻擋並記錄該介面及方向的所有封包。

以下這組規則定義名為 [.filename]#dc0# 的公開介面傳出區段。這些規則保留狀態，並指定內部系統被授權存取公開網際網路的特定服務。所有規則都使用 `quick`，並指定適當的連接埠號碼，以及在適用的情況下指定目的地位址。

[.programlisting]
....
# interface facing Internet (outbound)
# Matches session start requests originating from or behind the
# firewall, destined for the Internet.

# Allow outbound access to public DNS servers.
# Replace x.x.x. with address listed in /etc/resolv.conf.
# Repeat for each DNS server.
pass out quick on dc0 proto tcp from any to x.x.x. port = 53 flags S keep state
pass out quick on dc0 proto udp from any to xxx port = 53 keep state

# Allow access to ISP's specified DHCP server for cable or DSL networks.
# Use the first rule, then check log for the IP address of DHCP server.
# Then, uncomment the second rule, replace z.z.z.z with the IP address,
# and comment out the first rule
pass out log quick on dc0 proto udp from any to any port = 67 keep state
#pass out quick on dc0 proto udp from any to z.z.z.z port = 67 keep state

# Allow HTTP and HTTPS
pass out quick on dc0 proto tcp from any to any port = 80 flags S keep state
pass out quick on dc0 proto tcp from any to any port = 443 flags S keep state

# Allow email
pass out quick on dc0 proto tcp from any to any port = 110 flags S keep state
pass out quick on dc0 proto tcp from any to any port = 25 flags S keep state

# Allow NTP
pass out quick on dc0 proto tcp from any to any port = 37 flags S keep state

# Allow FTP
pass out quick on dc0 proto tcp from any to any port = 21 flags S keep state

# Allow SSH
pass out quick on dc0 proto tcp from any to any port = 22 flags S keep state

# Allow ping
pass out quick on dc0 proto icmp from any to any icmp-type 8 keep state

# Block and log everything else
block out log first quick on dc0 all
....

這個公開介面傳入區段的規則範例，會先阻擋所有不需要的封包，藉此減少被最後一條規則記錄的封包數量。

[.programlisting]
....
# interface facing Internet (inbound)
# Block all inbound traffic from non-routable or reserved address spaces
block in quick on dc0 from 192.168.0.0/16 to any    #RFC 1918 private IP
block in quick on dc0 from 172.16.0.0/12 to any     #RFC 1918 private IP
block in quick on dc0 from 10.0.0.0/8 to any        #RFC 1918 private IP
block in quick on dc0 from 127.0.0.0/8 to any       #loopback
block in quick on dc0 from 0.0.0.0/8 to any         #loopback
block in quick on dc0 from 169.254.0.0/16 to any    #DHCP auto-config
block in quick on dc0 from 192.0.2.0/24 to any      #reserved for docs
block in quick on dc0 from 204.152.64.0/23 to any   #Sun cluster interconnect
block in quick on dc0 from 224.0.0.0/3 to any       #Class D & E multicast

# Block fragments and too short tcp packets
block in quick on dc0 all with frags
block in quick on dc0 proto tcp all with short

# block source routed packets
block in quick on dc0 all with opt lsrr
block in quick on dc0 all with opt ssrr

# Block OS fingerprint attempts and log first occurrence
block in log first quick on dc0 proto tcp from any to any flags FUP

# Block anything with special options
block in quick on dc0 all with ipopts

# Block public pings and ident
block in quick on dc0 proto icmp all icmp-type 8
block in quick on dc0 proto tcp from any to any port = 113

# Block incoming Netbios services
block in log first quick on dc0 proto tcp/udp from any to any port = 137
block in log first quick on dc0 proto tcp/udp from any to any port = 138
block in log first quick on dc0 proto tcp/udp from any to any port = 139
block in log first quick on dc0 proto tcp/udp from any to any port = 81
....

只要有使用 `log first` 選項的規則產生記錄訊息，就應執行 `ipfstat -hio` 來評估該規則被比對到的次數。大量的比對次數可能表示系統正遭受攻擊。

傳入區段的其餘規則定義了哪些連線可以從網際網路發起。最後一條規則則拒絕所有未被本區段先前規則明確允許的連線。

[.programlisting]
....
# Allow traffic in from ISP's DHCP server. Replace z.z.z.z with
# the same IP address used in the outbound section.
pass in quick on dc0 proto udp from z.z.z.z to any port = 68 keep state

# Allow public connections to specified internal web server
pass in quick on dc0 proto tcp from any to x.x.x.x port = 80 flags S keep state

# Block and log only first occurrence of all remaining traffic.
block in log first quick on dc0 all
....

=== 設定 NAT

要啟用 NAT，請將以下敘述加入 [.filename]#/etc/rc.conf#，並指定包含 NAT 規則的檔案名稱：

[.programlisting]
....
gateway_enable="YES"
ipnat_enable="YES"
ipnat_rules="/etc/ipnat.rules"
....

NAT 規則相當靈活，可以達成許多不同的功能來滿足商業及家庭使用者的需求。此處呈現的規則語法已簡化，以示範常見用法。完整的規則語法說明請參閱 man:ipnat[5]。

NAT 規則的基本語法如下，其中 `map` 為規則的起始，_IF_ 應替換為外部介面的名稱：

[.programlisting]
....
map IF LAN_IP_RANGE -> PUBLIC_ADDRESS
....

_LAN_IP_RANGE_ 是內部用戶端使用的 IP 位址範圍，通常是私人位址範圍，例如 `192.168.1.0/24`。_PUBLIC_ADDRESS_ 可以是靜態的外部 IP 位址，或是關鍵字 `0/32`，代表指派給 _IF_ 的 IP 位址。

在 IPF 中，當封包從區域網路到達防火牆且目的地為公開位址時，會先通過防火牆規則集的傳出規則。接著封包被傳到 NAT 規則集，由上而下讀取，第一條符合的規則即生效。IPF 會將每條 NAT 規則與封包的介面名稱及來源 IP 位址進行比對。當封包的介面名稱符合某條 NAT 規則時，會檢查封包在私人區域網路中的來源 IP 位址是否落在 _LAN_IP_RANGE_ 指定的 IP 位址範圍內。若符合，封包的來源 IP 位址會被改寫為 _PUBLIC_ADDRESS_ 指定的公開 IP 位址。IPF 會在其內部 NAT 表中記錄一筆項目，這樣當封包從網際網路返回時，就能將它對應回原本的私人 IP 位址，再交給防火牆規則做進一步處理。

對於擁有大量內部系統或多個子網路的網路，將所有私人 IP 位址集中到單一公開 IP 位址的過程會成為資源問題。有兩種方法可以緩解此問題。

第一種方法是指派一個連接埠範圍作為來源連接埠。加上 `portmap` 關鍵字後，NAT 就只會使用指定範圍內的來源連接埠：

[.programlisting]
....
map dc0 192.168.1.0/24 -> 0/32 portmap tcp/udp 20000:60000
....

或者，使用 `auto` 關鍵字讓 NAT 自行決定可用的連接埠：

[.programlisting]
....
map dc0 192.168.1.0/24 -> 0/32 portmap tcp/udp auto
....

第二種方法是使用一組公開位址集區。當區域網路位址太多而無法塞進單一公開位址，且有一整組公開 IP 位址可用時，這個方法就很實用。這些公開位址可作為集區使用，NAT 會在封包送出時從中選取一個 IP 位址來進行對應。

公開 IP 位址的範圍可以使用子網路遮罩或 CIDR 表示法來指定。以下兩條規則是等效的：

[.programlisting]
....
map dc0 192.168.1.0/24 -> 204.134.75.0/255.255.255.0
map dc0 192.168.1.0/24 -> 204.134.75.0/24
....

常見的做法是將可公開存取的網頁伺服器或郵件伺服器隔離到內部網路區段。這些伺服器的流量仍然需要經過 NAT，但需要連接埠重新導向才能將傳入流量導到正確的伺服器。例如，要將使用內部位址 `10.0.10.25` 的網頁伺服器對應到其公開 IP 位址 `20.20.20.5`，請使用以下規則：

[.programlisting]
....
rdr dc0 20.20.20.5/32 port 80 -> 10.0.10.25 port 80
....

如果這是唯一的網頁伺服器，以下規則也可以使用，因為它會將所有外部 HTTP 請求重新導向到 `10.0.10.25`：

[.programlisting]
....
rdr dc0 0.0.0.0/0 port 80 -> 10.0.10.25 port 80
....

IPF 有內建的 FTP 代理程式可搭配 NAT 使用。它會監控所有傳出流量中的主動或被動 FTP 連線請求，並動態建立包含 FTP 資料通道所用連接埠號碼的暫時過濾規則。這樣就不需要為 FTP 連線開啟大範圍的高位連接埠。

以下範例中，第一條規則為來自內部區域網路的傳出 FTP 流量呼叫代理程式。第二條規則讓 FTP 流量從防火牆通過到網際網路，第三條規則則處理來自內部區域網路的所有非 FTP 流量：

[.programlisting]
....
map dc0 10.0.10.0/29 -> 0/32 proxy port 21 ftp/tcp
map dc0 0.0.0.0/0 -> 0/32 proxy port 21 ftp/tcp
map dc0 10.0.10.0/29 -> 0/32
....

FTP 的 `map` 規則必須放在 NAT 規則之前，這樣當封包符合 FTP 規則時，FTP 代理程式就會建立暫時過濾規則，讓 FTP 工作階段封包通過並進行 NAT。所有非 FTP 的區域網路封包不會符合 FTP 規則，但若符合第三條規則，仍會進行 NAT。

若不使用 FTP 代理程式，則需要以下防火牆規則。請注意，沒有代理程式的情況下，必須允許所有 `1024` 以上的連接埠：

[.programlisting]
....
# Allow out LAN PC client FTP to public Internet
# Active and passive modes
pass out quick on rl0 proto tcp from any to any port = 21 flags S keep state

# Allow out passive mode data channel high order port numbers
pass out quick on rl0 proto tcp from any to any port > 1024 flags S keep state

# Active mode let data channel in from FTP server
pass in quick on rl0 proto tcp from any to any port = 20 flags S keep state
....

每當編輯包含 NAT 規則的檔案後，請以 `-CF` 執行 `ipnat` 來刪除目前的 NAT 規則並清除動態轉譯表的內容。加上 `-f` 並指定要載入的 NAT 規則集名稱：

[source,shell]
....
# ipnat -CF -f /etc/ipnat.rules
....

顯示 NAT 統計資訊：

[source,shell]
....
# ipnat -s
....

列出 NAT 表目前的對應：

[source,shell]
....
# ipnat -l
....

開啟詳細模式，顯示規則處理及作用中規則與表格項目的相關資訊：

[source,shell]
....
# ipnat -v
....

=== 檢視 IPF 統計資訊

IPF 包含 man:ipfstat[8]，可用來擷取並顯示封包通過防火牆時比對規則所收集的統計資訊。統計資料從防火牆上次啟動起，或上次以 `ipf -Z` 歸零後開始累積。

預設的 `ipfstat` 輸出如下所示：

[source,shell]
....
input packets: blocked 99286 passed 1255609 nomatch 14686 counted 0
 output packets: blocked 4200 passed 1284345 nomatch 14687 counted 0
 input packets logged: blocked 99286 passed 0
 output packets logged: blocked 0 passed 0
 packets logged: input 0 output 0
 log failures: input 3898 output 0
 fragment state(in): kept 0 lost 0
 fragment state(out): kept 0 lost 0
 packet state(in): kept 169364 lost 0
 packet state(out): kept 431395 lost 0
 ICMP replies: 0 TCP RSTs sent: 0
 Result cache hits(in): 1215208 (out): 1098963
 IN Pullups succeeded: 2 failed: 0
 OUT Pullups succeeded: 0 failed: 0
 Fastroute successes: 0 failures: 0
 TCP cksum fails(in): 0 (out): 0
 Packet log flags set: (0)
....

有多個選項可用。指定 `-i` 代表傳入、`-o` 代表傳出時，指令會擷取並顯示目前安裝在核心中使用的對應過濾規則清單。要同時顯示規則編號，請加上 `-n`。例如，`ipfstat -on` 會顯示含有規則編號的傳出規則表：

[source,shell]
....
@1 pass out on xl0 from any to any
@2 block out on dc0 from any to any
@3 pass out quick on dc0 proto tcp/udp from any to any keep state
....

加上 `-h` 可在每條規則前面顯示該規則被比對到的次數。例如，`ipfstat -oh` 會顯示傳出內部規則表，每條規則前面附有使用次數：

[source,shell]
....
2451423 pass out on xl0 from any to any
354727 block out on dc0 from any to any
430918 pass out quick on dc0 proto tcp/udp from any to any keep state
....

要以類似 man:top[1] 的格式顯示狀態表，請使用 `ipfstat -t`。當防火牆遭受攻擊時，此選項能幫助辨識並檢視攻擊封包。選用的子旗標可指定要即時監控的目的地或來源 IP、連接埠或通訊協定。詳情請參閱 man:ipfstat[8]。

=== IPF 日誌

IPF 提供 `ipmon`，可將防火牆的記錄資訊以人類可讀的格式寫出。使用前必須先依照 crossref:kernelconfig[kernelconfig,設定 FreeBSD 核心] 中的說明，將 `options IPFILTER_LOG` 加入自訂核心。

此指令通常以常駐程式模式執行，以提供持續的系統記錄檔，方便事後檢閱過往事件。由於 FreeBSD 內建 man:syslogd[8] 機制可自動輪替系統記錄，預設的 [.filename]#rc.conf#`ipmon_flags` 設定使用 `-Ds`：

[.programlisting]
....
ipmon_flags="-Ds" # D = start as daemon
                  # s = log to syslog
                  # v = log tcp window, ack, seq
                  # n = map IP & port to names
....

記錄功能讓您能事後檢閱哪些封包被丟棄、來自什麼位址、以及要送往何處等資訊，這些資訊對於追蹤攻擊者相當有用。

在 [.filename]#rc.conf# 中啟用記錄功能並以 `service ipmon start` 啟動後，IPF 只會記錄包含 `log` 關鍵字的規則。防火牆管理員決定規則集中哪些規則應該記錄，通常只記錄拒絕規則。慣例上會在規則集的最後一條規則中加入 `log` 關鍵字，這樣就能看到所有未符合規則集中任何規則的封包。

預設情況下，`ipmon -Ds` 模式使用 `local0` 作為記錄設施。以下記錄層級可用來進一步區隔記錄資料：

[source,shell]
....
LOG_INFO - packets logged using the "log" keyword as the action rather than pass or block.
LOG_NOTICE - packets logged which are also passed
LOG_WARNING - packets logged which are also blocked
LOG_ERR - packets which have been logged and which can be considered short due to an incomplete header
....

要設定 IPF 將所有資料記錄到 [.filename]#/var/log/ipfilter.log#，請先建立空檔案：

[source,shell]
....
# touch /var/log/ipfilter.log
....

接著，要將所有記錄訊息寫入指定檔案，請將以下敘述加入 [.filename]#/etc/syslog.conf#：

[.programlisting]
....
local0.* /var/log/ipfilter.log
....

要啟用變更並指示 man:syslogd[8] 讀取修改後的 [.filename]#/etc/syslog.conf#，請執行 `service syslogd reload`。

別忘了編輯 [.filename]#/etc/newsyslog.conf# 來輪替新的記錄檔。

`ipmon` 產生的訊息由以空白分隔的資料欄位組成。所有訊息共通的欄位有：

. 封包接收日期。
. 封包接收時間，格式為 HH:MM:SS.F，分別代表時、分、秒及秒的小數部分。
. 處理該封包的介面名稱。
. 規則的群組及規則編號，格式為 `@0:17`。
. 動作：`p` 代表通過、`b` 代表阻擋、`S` 代表短封包、`n` 代表未符合任何規則、`L` 代表記錄規則。
. 位址以三個欄位呈現：來源位址與連接埠以逗號分隔、-> 符號、以及目的地位址與連接埠。例如：`209.53.17.22,80 -> 198.73.220.17,1722`。
. `PR` 後接通訊協定名稱或編號，例如 `PR tcp`。
. `len` 後接標頭長度與封包總長度，例如 `len 20 40`。

若封包為 TCP 封包，會有一個額外欄位，以連字號開頭，後接對應已設定旗標的字母。字母與旗標的對照清單請參閱 man:ipf[5]。

若封包為 ICMP 封包，結尾會有兩個欄位：第一個固定為 "icmp"，第二個為 ICMP 訊息類型及子訊息類型，以斜線分隔。例如：`icmp 3/3` 代表連接埠不可達訊息。

[[firewalls-blacklistd]]
== Blacklistd

Blacklistd 是一個監聽 socket 的常駐程式，用來接收其他常駐程式所發出關於連線嘗試成功或失敗的通知。它最常用於阻擋對開放連接埠的過多連線嘗試。一個典型的例子是在網際網路上執行的 SSH，會收到大量來自機器人或指令碼嘗試猜密碼以取得存取權限的請求。透過 Blacklistd，常駐程式可以通知防火牆建立過濾規則，在嘗試次數達到上限後，阻擋來自單一來源的過多連線嘗試。Blacklistd 最初在 NetBSD 開發，於該系統 7 版首次出現。FreeBSD 11 從 NetBSD 引入了 Blacklistd。

本章說明如何設定及使用 Blacklistd，並提供使用範例。讀者應熟悉防火牆的基本概念如規則等。詳情請參閱防火牆章節。範例中使用 PF，但 FreeBSD 上其他可用的防火牆也能與 Blacklistd 搭配使用。

=== 開啟 Blacklistd

Blacklistd 的主要設定存放在 man:blacklistd.conf[5]。另有多個命令列選項可變更 Blacklistd 的執行時期行為。要跨重開機保留的持久設定應存放在 [.filename]#/etc/blacklistd.conf# 中。要在系統開機時啟用此常駐程式，請將 `blacklistd_enable` 這行加入 [.filename]#/etc/rc.conf#，如下所示：

[source,shell]
....
# sysrc blacklistd_enable=yes
....

要手動啟動服務，請執行以下指令：

[source,shell]
....
# service blacklistd start
....

=== 建立 Blacklistd 規則集

Blacklistd 的規則在 man:blacklistd.conf[5] 中設定，每行一筆。每條規則包含以空格或 Tab 分隔的欄位組合。規則分為 `local`（本地）或 `remote`（遠端），分別套用於 Blacklistd 所執行的機器或外部來源。

==== 本地規則

以下是本地規則在 blacklistd.conf 中的設定範例：

[.programlisting]
....
[local]
ssh             stream  *       *               *       3       24h
....

所有在 `[local]` 區段之後的規則都視為本地規則（這是預設值），套用於本機。當遇到 `[remote]` 區段時，其後的所有規則都會當作遠端機器規則處理。

每條規則由七個欄位組成，以 Tab 或空格分隔。前四個欄位用來辨識應被列入黑名單的流量，後三個欄位定義 Blacklistd 的行為。萬用字元以星號 (`*`) 表示，代表該欄位可比對任何值。第一個欄位定義位置，在本地規則中就是網路連接埠。位置欄位的語法如下：

[.programlisting]
....
[address|interface][/mask][:port]
....

位址可以用數字格式的 IPv4 或方括號括住的 IPv6 指定。也可以使用介面名稱，例如 `_em0_`。

第二個欄位定義 socket 類型。TCP socket 的類型為 `stream`，UDP 則以 `dgram` 表示。上述範例使用 TCP，因為 SSH 使用該通訊協定。

第三個欄位可指定通訊協定。可使用的通訊協定有：`tcp`、`udp`、`tcp6`、`udp6` 或數字編號。除非有必要依特定通訊協定區分流量，否則通常使用萬用字元來比對所有通訊協定，如同範例所示。

第四個欄位定義回報事件的常駐程式程序之有效使用者或擁有者。此處可使用使用者名稱或 UID，也可使用萬用字元（請參考上述規則範例）。

第五個欄位宣告封包過濾器的規則名稱，這也是規則行為部分的起始。預設情況下，Blacklistd 會將所有阻擋規則放在 [.filename]#pf.conf# 中名為 `blacklistd` 的 pf anchor 底下，如下所示：

[.programlisting]
....
anchor "blacklistd/*" in on $ext_if
block in
pass out
....

若要使用不同的黑名單，可以在此欄位指定 anchor 名稱。其他情況下使用萬用字元即可。當名稱以連字號 (`-`) 開頭時，表示應使用預設規則名稱加上此名稱的 anchor。以下是使用連字號的修改範例：

[.programlisting]
....
ssh             stream  *       *               -ssh       3       24h
....

使用這樣的規則，任何新的黑名單規則都會被加入名為 `blacklistd-ssh` 的 anchor。

要因單一規則違規而阻擋整個子網路，可在規則名稱中使用 `/`。這會使名稱的剩餘部分被解讀為套用在規則中指定位址上的遮罩。例如，以下規則會阻擋 `/24` 範圍內的所有位址。

[.programlisting]
....
22              stream  tcp       *               */24    3       24h
....

[NOTE]
====
此處務必指定正確的通訊協定。IPv4 和 IPv6 對 /24 的解讀不同，這就是為什麼此規則的第三個欄位不能使用 `*` 的原因。
====

此規則表示只要該網路中有任何一台主機行為異常，該網路中的其他所有主機也會被阻擋。

第六個欄位稱為 `nfail`，設定將該遠端 IP 列入黑名單所需的登入失敗次數。若此位置使用萬用字元，表示永遠不會進行阻擋。上述範例規則中定義的限制為三次，表示在同一連線中嘗試登入 SSH 三次後，該 IP 就會被阻擋。

Blacklistd 規則定義中的最後一個欄位指定主機被列入黑名單的時間長度。預設單位為秒，但也可以使用 `m`、`h` 及 `d` 字尾分別代表分鐘、小時和天。

完整來看，此範例規則表示對 SSH 進行三次驗證失敗後，就會為該主機產生一條新的 PF 阻擋規則。規則比對的執行方式是先逐一檢查本地規則，從最具體的到最不具體的。當比對成功時，會套用 `remote` 規則，並由符合的 `remote` 規則變更名稱、`nfail` 及停用欄位。

==== 遠端規則

遠端規則用來指定 Blacklistd 依目前評估的遠端主機如何變更其行為。遠端規則中的每個欄位與本地規則相同，唯一的差異在於 Blacklistd 使用它們的方式。以下範例規則用來說明此概念：

[.programlisting]
....
[remote]
203.0.113.128/25 *      *       *               =/25    =       48h
....

位址欄位可以是 IP 位址（v4 或 v6）、連接埠或兩者皆有。這使得可以像此範例一樣，為特定遠端位址範圍設定特殊規則。類型、通訊協定及擁有者欄位的解讀方式與本地規則完全相同。

但名稱欄位有所不同：遠端規則中的等號 (`=`) 告訴 Blacklistd 使用符合的本地規則的值。這表示會取用防火牆規則項目，並加上 `/25` 前置碼（子網路遮罩 `255.255.255.128`）。當來自該位址範圍的連線被列入黑名單時，整個子網路都會受到影響。此處也可使用 PF anchor 名稱，在這種情況下，Blacklistd 會將此位址區塊的規則加入該名稱的 anchor。指定萬用字元時會使用預設表格。

可以為某個位址在 `nfail` 欄位自訂失敗次數。這對於特定規則的例外狀況相當實用，例如對某些對象套用較寬鬆的規則或給予更多登入嘗試機會。當此第六個欄位使用星號時，阻擋功能會被停用。

與來自辦公室等區域網路的嘗試相比，遠端規則允許對登入嘗試實施更嚴格的限制。

=== Blacklistd 客戶端設定

FreeBSD 中有幾個軟體套件可以利用 Blacklistd 的功能。其中最主要的兩個是 man:ftpd[8] 及 man:sshd[8]，用來阻擋過多的連線嘗試。要在 SSH 常駐程式中啟用 Blacklistd，請將以下行加入 [.filename]#/etc/ssh/sshd_config#：

[.programlisting]
....
UseBlacklist yes
....

接著重新啟動 sshd 來使變更生效。

man:ftpd[8] 的黑名單功能透過 `-B` 啟用，可在 [.filename]#/etc/inetd.conf# 中設定，或作為 [.filename]#/etc/rc.conf# 中的旗標，如下所示：

[.programlisting]
....
ftpd_flags="-B"
....

以上就是讓這些程式與 Blacklistd 溝通所需的全部設定。

=== Blacklistd 管理

Blacklistd 提供一個名為 man:blacklistctl[8] 的管理工具。它會顯示被 man:blacklistd.conf[5] 中定義的規則列入黑名單的已阻擋位址及網路。要檢視目前被阻擋的主機清單，請搭配使用 `dump` 與 `-b`，如下所示。

[source,shell]
....
# blacklistctl dump -b
      address/ma:port id      nfail   last access
213.0.123.128/25:22   OK      6/3     2019/06/08 14:30:19
....

此範例顯示來自位址範圍 `213.0.123.128/25` 在連接埠 22 上，在允許的三次中已有六次嘗試。列出的嘗試次數比允許的多，是因為 SSH 允許用戶端在單一 TCP 連線中嘗試多次登入。目前進行中的連線不會被 Blacklistd 中斷。最後一次連線嘗試列在輸出的 `last access` 欄位中。

要查看此主機在黑名單上的剩餘時間，請在前述指令中加上 `-r`。

[source,shell]
....
# blacklistctl dump -br
      address/ma:port id      nfail   remaining time
213.0.123.128/25:22   OK      6/3     36s
....

在此範例中，還剩 36 秒此主機就不再被阻擋。

=== 從封鎖清單移除主機

有時候需要在剩餘時間到期前將主機從封鎖清單中移除。很遺憾，Blacklistd 本身沒有提供這項功能。不過，可以使用 pfctl 從 PF 表格中移除位址。每個被阻擋的連接埠在 [.filename]#/etc/pf.conf# 中定義的 blacklistd anchor 底下都有一個子 anchor。例如，阻擋連接埠 22 的子 anchor 稱為 `blacklistd/22`。該子 anchor 中有一個包含被阻擋位址的表格，表格名稱為 port 加上連接埠號碼。以此範例而言，表格名稱為 `port22`。有了這些資訊，就可以使用 man:pfctl[8] 顯示所有被列出的位址，如下所示：

[source,shell]
....
# pfctl -a blacklistd/22 -t port22 -T show
...
213.0.123.128/25
...
....

找出要從清單中解除封鎖的位址後，以下指令可將其從清單中移除：

[source,shell]
....
# pfctl -a blacklistd/22 -T delete 213.0.123.128/25
....

該位址現在已從 PF 中移除，但仍會出現在 blacklistctl 清單中，因為它不知道 PF 中所做的變更。Blacklistd 資料庫中的項目最終會過期並從輸出中移除。若該主機再次符合 Blacklistd 中的某條阻擋規則，該項目將會再次被加入。
