# $FreeBSD: www/ja/news/1996/Makefile,v 1.4 2000/10/19 19:05:13 hrs Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

### Revision checking
REVCHECK=	YES

.include "${WEB_PREFIX}/share/mk/web.site.mk"
