# $FreeBSD: www/en/smp/Makefile,v 1.1 2000/10/18 19:43:57 nik Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
