# $Id: Makefile,v 1.1 1999-03-01 17:03:44 motoyuki Exp $
# The FreeBSD Japanese Documentation Project

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

# Following file will be installed directly.

DATA=	index.html

.include "../../web.mk"
