# $FreeBSD$
# The FreeBSD Japanese Documentation Project

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

# Following file will be installed directly.

DATA=	index.html

.include "../../web.mk"
