# $FreeBSD: www/ja/java/Makefile.inc,v 1.2 2000/04/28 12:21:21 phantom Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

WEBBASE?=	/data/ja/java
WEB_PREFIX?=	${.CURDIR}/../../..
