---
title: Hoofdstuk 7. Bureaubladapplicaties
part: Deel II. Algemene taken
prev: books/handbook/partii
next: books/handbook/multimedia
---

[[desktop]]
= Bureaubladapplicaties
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Inhoudsopgave
:table-caption: Tabel
:figure-caption: Afbeelding
:example-caption: Voorbeeld
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 7

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/nl/mailing-lists.adoc[]
include::shared/nl/teams.adoc[]
include::shared/nl/urls.adoc[]

toc::[]

[[desktop-synopsis]]
== Overzicht

FreeBSD kan een groot aantal bureaubladapplicaties draaien, zoals browsers en tekstverwerkers. De meeste hiervan zijn beschikbaar als pakketten of kunnen automatisch vanuit de Portscollectie gebouwd worden. Veel nieuwe gebruikers verwachten dit soort applicaties op hun bureaublad. Dit hoofdstuk laat zien hoe populaire bureaubladapplicaties moeiteloos geïnstalleerd kunnen worden vanuit een pakket of vanuit de Portscollectie.

Als programma's vanuit ports geïnstalleerd worden, wordt hun broncode gecompileerd. Dit kan erg lang duren, afhankelijk van wat er gecompileerd wordt en de rekenkracht van een machine. Als compileren vanuit broncode te veel tijd kost, kunnen de meeste programma's van de Portscollectie als een voorgebouwd pakket geïnstalleerd worden.

Omdat FreeBSD compatibel is met Linux(R), zijn veel applicaties die voor Linux(R) zijn ontwikkeld beschikbaar een FreeBSD bureaublad. Het wordt sterk aanbevolen om crossref:linuxemu[linuxemu,Linux® binaire compatibiliteit] te lezen voordat Linux(R) applicaties geïnstalleerd worden. Veel ports die gebruik maken van Linux(R) compatibiliteit beginnen met "linux-". Dit is handig om te onthouden wanneer er naar een port gezocht wordt met bijvoorbeeld man:whereis[1]. In dit hoofdstuk wordt aangenomen dat Linux(R) binaire compatibiliteit is ingeschakeld voordat Linux(R) applicaties worden geïnstalleerd.

In dit hoofdstuk worden de volgende categoriën behandeld:

* Browsers (zoals Firefox, Opera, Konqueror, Chromium)
* Productiviteit (zoals KOffice, AbiWord, The GIMP, Apache OpenOffice, LibreOffice)
* Documentviewers (zoals Acrobat Reader(R), gv, Xpdf, GQview)
* Financieel (zoals GnuCash, Gnumeric, Abacus)

Er wordt aangenomen dat de lezer van dit hoofdstuk:

* Weet hoe aanvullende software van derde partijen geïnstalleerd wordt (crossref:ports[ports,Applicaties installeren. pakketten en ports]).
* Weet hoe aanvullende Linux(R) software geïnstalleerd wordt (crossref:linuxemu[linuxemu,Linux® binaire compatibiliteit]).

Meer informatie over een multimedia-omgeving staat in crossref:multimedia[multimedia,Multimedia]. Installatie van email staat beschreven in crossref:mail[mail,Elektronische mail].

[[desktop-browsers]]
== Browsers

FreeBSD wordt zonder een voorgeïnstalleerde browser geleverd. In plaats hiervan bevat de link:https://www.FreeBSD.org/ports/[www] map van de Portscollectie browsers om te installeren. Het is ook mogelijk voor de meeste ports een pakket te installeren als compileren niet gewenst is. Compileren kan soms lang duren.

KDE en GNOME bevatten reeds HTML-browsers. In crossref:x11[x11-wm,Bureaubladomgevingen] staat meer informatie over de installatie van deze complete bureaubladen.

Lichtgewicht browsers uit de Portscollectie zijn onder andere package:www/dillo2[], package:www/links[] of package:www/w3m[].

Dit gedeelte behandelt deze applicaties:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Applicatie
| Bronnen
| Ports
| Grote afhankelijkheden

|Firefox
|gemiddeld
|zwaar
|Gtk+

|Opera
|weinig
|licht
|FreeBSD en Linux(R) versies beschikbaar. De Linux(R) versie is afhankelijk van de Linux(R) binaire compatibiliteit en linux-openmotif.

|Konqueror
|gemiddeld
|zwaar
|KDE bibliotheken

|Chromium
|gemiddeld
|gemiddeld
|Gtk+
|===

=== Firefox

Firefox is een moderne, gratis, stabiele open-source browser die volledig geporteerd is naar FreeBSD: het heeft een motor voor HTML-weergave die zich zeer strikt aan de standaarden houdt, browsen met tabbladen, blokkeren van pop-ups, uitbreidingen, verbeterde veiligheid, en meer. Firefox is gebaseerd op de codebase van Mozilla.

Installeer het pakket door het volgende te typen:

[source,bash]
....
# pkg_add -r firefox
....

Dit zal de laatste uitgave van Firefox installeren, als u in plaats hiervan de Extended Support Release (ESR) van Firefox wilt draaien, gebruik dan:

[source,bash]
....
# pkg_add -r firefox-esr
....

De Portscollectie kan ook gebruikt worden als u liever vanuit de broncode installeert.

[source,bash]
....
# cd /usr/ports/www/firefox
# make install clean
....

Voor Firefox ESR dient `firefox` in het vorige commando vervangen te worden door `firefox-esr`.

[[moz-java-plugin]]
=== Firefox en Java(TM) plugin

[NOTE]
====
In deze en de volgende twee secties wordt er vanuit gegaan dat Firefox reeds geïnstalleerd is.
====

Installeer OpenJDK 6 vanuit de Ports Collectie door het volgende typen:

[source,bash]
....
# cd /usr/ports/java/openjdk6
# make install clean
....

Installeer daarna de port package:java/icedtea-web[]:

[source,bash]
....
# cd /usr/ports/java/icedtea-web
# make install clean
....

Zorg ervoor dat de standaard configuratieopties voor beide ports zijn geselecteerd.

Start de browser en voer `about:plugins` in de locatie balk en druk op kbd:[Enter]. Er zal een pagina gepresenteerd worden die de geïnstalleerde plugins toont; de Java(TM) plugin zal nu getoond moeten worden.

Als de browser de plugin niet kan vinden, dient elke gebruiker het volgende commando uit te voeren en de browser opnieuw te starten:

[source,bash]
....
% ln -s /usr/local/lib/IcedTeaPlugin.so \
  $HOME/.mozilla/plugins/
....

[[moz-flash-plugin]]
=== Firefox en Adobe(R) Flash(TM) plugin

De Adobe(R) Flash(TM) plugin is niet beschikbaar voor FreeBSD. Er is echter wel een softwarelaag (wrapper) om de Linux(R)-versie van de plugin te draaien. Deze wrapper ondersteunt ook Adobe(R) Acrobat(R) plugin, RealPlayer(R) plugin en meer.

Afhankelijk van de versie van FreeBSD die u draait zijn er verschillende stappen nodig:

[.procedure]
====

. Op FreeBSD 7.X
+ 
Installeer de port package:www/nspluginwrapper[]. Deze port heeft package:emulators/linux_base-fc4[] nodig, wat een grote port is.
+ 
De volgende stap is om de port package:www/linux-flashplugin9[] te installeren. Dit zal Flash(TM) 9.X installeren, van deze versie is bekend dat die correct werkt op FreeBSD 7.X.
. Op FreeBSD 8.X of nieuwer
+ 
Installeer de port package:www/nspluginwrapper[]. Deze port heeft package:emulators/linux_base-f10[] nodig, wat een grote port is.
+ 
De volgende stap is om de Flash(TM) 11.X vanuit de port package:www/linux-f10-flashplugin11[] te installeren.
+ 
Voor deze versie is het nodig om de volgende koppeling aan te maken:
+
[source,bash]
....
# ln -s /usr/local/lib/npapi/linux-f10-flashplugin/libflashplayer.so \
  /usr/local/lib/browser_plugins/
....
+ 
De [.filename]#/usr/local/lib/browser_plugins# directory moet handmatig aangemaakt worden als deze nog niet op het systeem bestaat.
====

Wanneer de juiste Flash(TM) port, afhankelijk van de versie van FreeBSD die u draait, is geïnstalleerd, moet de plugin door elke gebruiker worden geïnstalleerd met `nspluginwrapper`:

[source,bash]
....
% nspluginwrapper -v -a -i
....

Start dan de browser en voer op de adresbalk `about:plugins` in en druk op kbd:[Enter]. Een pagina met alle geïnstalleerde plugins wordt nu getoond.

[[moz-swfdec-flash-plugin]]
=== Firefox en Swfdec Flash(TM) plugin

Swfdec is de bibliotheek om Flash(TM)-animaties te decoderen en af te beelden. Swfdec-Mozilla is een plugin voor Firefox-browsers dat de Swfdec-bibliotheek gebruikt om SWF-bestanden af te spelen. Er wordt nog steeds veel aan ontwikkeld.

Als u het niet kunt of wilt compileren, kan het pakket vanaf het netwerk worden geïnstalleerd:

[source,bash]
....
# pkg_add -r swfdec-plugin
....

Als het pakket niet beschikbaar is, kunt u het vanuit de Portscollectie compileren en installeren:

[source,bash]
....
# cd /usr/ports/www/swfdec-plugin
# make install clean
....

Herstart hierna uw browser om deze plugin effectief te maken.

=== Opera

Opera is een volledige en een standaard volgende browser. Hij wordt standaard geleverd met een ingebouwde email-client, een nieuwslezer, een IRC client, een RSS/ATOM feed lezer en nog veel meer. Ondanks dat is Opera relatief gezien niet zwaar en erg snel. Hij komt in twee smaken: een FreeBSD versie en een versie die draait onder Linux(R) emulatie.

De FreeBSD pakketversie van Opera wordt zo geïnstalleerd:

[source,bash]
....
# pkg_add -r opera
....

Sommige FTP-sites hebben niet alle pakketten, maar Operakan worden nog altijd via de Portscollectie worden verkregen door te typen:

[source,bash]
....
# cd /usr/ports/www/opera
# make install clean
....

De Linux(R) versie van Opera kan geïnstalleerd worden door bij de bovenstaande voorbeelden `linux-opera` te gebruiken in plaats van `opera`.

De Adobe(R) Flash(TM) plugin is niet beschikbaar voor FreeBSD. Er bestaat echter een Linux(R) versie van de plugin. Om deze versie te installeren moet de port package:www/linux-f10-flashplugin11[] geïnstalleerd zijn, installeer daarna de port package:www/opera-linuxplugins[]:

[source,bash]
....
# cd /usr/ports/www/linux-f10-flashplugin11
# make install clean
# cd /usr/ports/www/opera-linuxplugins
# make install clean
....

U kunt controleren of de plugin aanwezig is: start uw browser, geef `opera:plugins` in op de adresbalk en druk op kbd:[Enter]. Er zou een lijst moeten verschijnen met alle huidig beschikbare plugins.

Volg de <<moz-java-plugin,instructies voor Firefox>> om de Java(TM) plugin te installeren.

=== Konqueror

Konqueror is deel van KDE, maar kan ook buiten KDE gebruikt worden door package:x11/kdebase3[] te installeren. Konqueror is meer dan een browser, het is ook een bestandsbeheerder en multimedia-viewer.

Er is ook een verzameling plugins beschikbaar voor Konqueror, beschikbaar in package:misc/konq-plugins[].

Konqueror ondersteunt WebKit naast het eigen KHTML. WebKit wordt gebruikt door vele moderne browsers waaronder Chromium. Om WebKit met Konqueror op FreeBSD te gebruiken:

[source,bash]
....
# cd /usr/ports/www/kwebkitpart
# make install clean
....

Klik vervolgens in Konqueror op "Settings", "Configure Konqueror", en "Change KHTML to WebKit".

Konqueror ondersteunt ook Flash(TM); een "How To" gids om ondersteuning voor Flash(TM) in Konqueror te krijgen is beschikbaar op http://freebsd.kde.org/howtos/konqueror-flash.php[http://freebsd.kde.org/howtos/konqueror-flash.php].

=== Chromium

Chromium is een open-source browserproject dat er op gericht is om een veiligere, snellere en stabielere surfervaring op te bouwen. Chromium biedt surfen met tabbladen, het blokkeren van pop-ups, uitbreidingen en nog veel meer. Chromium is het open-source project waar de browser Google Chrome op is gebaseerd.

Chromium kan als volgt als een pakket worden geïnstalleerd:

[source,bash]
....
# pkg_add -r chromium
....

Als alternatief kan Chromium worden gecompileerd vanuit de broncode door de Portscollectie te gebruiken:

[source,bash]
....
# cd /usr/ports/www/chromium
# make install clean
....

[NOTE]
====
Chromium wordt geïnstalleerd als [.filename]#/usr/local/bin/chrome#, niet als [.filename]#/usr/local/bin/chromium#.
====

[[chromium-java-plugin]]
=== Chromium en Java(TM) plugin

[NOTE]
====
Deze sectie neemt aan dat Chromium al is geïnstalleerd.
====

Installeer OpenJDK 6 vanuit de Portscollectie:

[source,bash]
....
# cd /usr/ports/java/openjdk6
# make install clean
....

Installeer vervolgens package:java/icedtea-web[] vanuit de Portscollectie:

[source,bash]
....
# cd /usr/ports/java/icedtea-web
# make install clean
....

Start Chromium en geef `about:plugins` op in de adresbalk. IcedTea-Web zou genoemd moeten worden als één van de geïnstalleerde plugins.

Als Chromium de plugin IcedTea-Web niet vermeldt, voer dan de volgende commando's uit en herstart de browser:

[source,bash]
....
# mkdir -p /usr/local/shared/chromium/plugins
# ln -s /usr/local/lib/IcedTeaPlugin.so \
  /usr/local/shared/chromium/plugins/
....

[[chromium-flash-plugin]]
=== Chromium en Adobe(R) Flash(TM) plugin

[NOTE]
====
Deze sectie neemt aan dat Chromium al is geïnstalleerd.
====

Het configureren van Chromium en Adobe(R) Flash(TM) lijkt op de <<moz-flash-plugin,instructies voor Firefox>>. Raadpleeg die sectie voor gedetailleerdere instructies en het installeren van Adobe(R) Flash(TM) op FreeBSD. Er zou geen verdere configuratie nodig moeten zijn, aangezien Chromium sommige plugins van andere browsers kan gebruiken.

[[desktop-productivity]]
== Productiviteit

Als het op productiviteit aankomt, zoeken nieuwe gebruikers vaak een goed kantoorpakket of een vriendelijke tekstverwerker. Hoewel sommige crossref:x11[x11-wm,bureaubladomgevingen] zoals KDE reeds een kantoorpakket verschaffen, is er geen standaard produktiviteitspakket. FreeBSD kan alles verschaffen wat nodig is, ongeacht de bureaubladomgeving.

In dit gedeelte worden de onderstaande applicaties beschreven:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Applicatie
| Bronnen
| Ports
| Afhankelijkheden

|KOffice
|weinig
|zwaar
|KDE

|AbiWord
|weinig
|licht
|Gtk+ of GNOME

|The GIMP
|weinig
|licht
|Gtk+

|Apache OpenOffice
|veel
|erg zwaar
|JDK(TM), Mozilla

|LibreOffice
|enigszins veel
|zwaar
|Gtk+, of KDE / GNOME, of JDK(TM)
|===

=== KOffice

De KDE-gemeenschap heeft zijn bureaubladomgeving met een kantoorpakket geleverd dat buiten KDE gebruikt kan worden. Het bevat de vier standaardcomponenten uit andere kantoorpakketten. KWord is de tekstverwerker, KSpread is het spreadsheetprogramma, KPresenter beheert diapresentaties en Kontour voorziet in grafische mogelijkheden.

Voordat de nieuwste KOffice wordt geïnstalleert, moet er een recente versie van KDE geïnstalleerd zijn.

KOffice voor KDE als pakket installeren gaat met het volgende commando:

[source,bash]
....
# pkg_add -r koffice-kde4
....

Als het pakket niet beschikbaar is, kan de Portscollectie gebruiken worden. Om KOffice voor KDE4 te installeren:

[source,bash]
....
# cd /usr/ports/editors/koffice-kde4
# make install clean
....

=== AbiWord

AbiWord is een vrij tekstverwerkingsprogramma, ongeveer gelijk aandoet als Microsoft(R) Word. Het is geschikt om verslagen, brieven, rapporten, memo's, enzovoort mee te typen. Het programma is snel, bevat veel mogelijkheden en is gebruikersvriendelijk.

AbiWord kan veel bestandsformaten importeren en exporteren, waaronder enkele gesloten formaten, zoals Microsoft(R)'s [.filename]#.doc#.

AbiWord is beschikbaar als pakket en te installeren met:

[source,bash]
....
# pkg_add -r abiword
....

Als het pakket niet beschikbaar is, kan het worden gecompileerd vanuit de Portscollectie. De Portscollectie is meer recent. Dat kan als volgt:

[source,bash]
....
# cd /usr/ports/editors/abiword
# make install clean
....

=== The GIMP

Voor het bewerken of retoucheren van afbeeldingen is The GIMP een zeer geavanceerd afbeeldingenmanipulatieprogramma. Het kan als eenvoudig tekenprogramma worden gebruikt of als kwalititeitspakket voor het retoucheren van foto's. Het ondersteunt een groot aantal plugins en bevat een scripting interface. The GIMP kan een groot aantal bestandsformaten lezen en schrijven. Het ondersteunt interfaces met scanners en tabletten.

Het pakket is te installeren met:

[source,bash]
....
# pkg_add -r gimp
....

Als een FTP-site dit pakket niet heeft, kan de Portscollectie gebruikt worden. De link:https://www.FreeBSD.org/ports/[graphics] map van de Portscollectie bevat ook The GIMP Manual. Die kan zo geïnstalleerd worden:

[source,bash]
....
# cd /usr/ports/graphics/gimp
# make install clean
# cd /usr/ports/graphics/gimp-manual-pdf
# make install clean
....

[NOTE]
====
De link:https://www.FreeBSD.org/ports/graphics.html[graphics] map van de Portscollectie bevat de ontwikkelversie van The GIMP in package:graphics/gimp-devel[]. Een HTML-versie van The GIMP Manual staan in package:graphics/gimp-manual-html[].
====

=== Apache OpenOffice

Op 1 juni 2011 doneerde Oracle Corporation de codebasis van OpenOffice.org aan de Apache Software Foundation. OpenOffice.org staat nu bekend als Apache OpenOffice en wordt ontwikkeld onder de vleugels van de Incubator van de Apache Software Foundation.

Apache OpenOffice bevat alle noodzakelijke applicaties in een compleet kantoorproductiviteitspakket: een tekstverwerker, een spreadsheet, een presentatiebeheerder en een tekenprogramma. De gebruikersinterface is vrijwel gelijk aan die van andere kantoorpakketten en het kan veel populaire bestandsformaten in- en uitvoeren. Het is beschikbaar in een aantal verschillende talen - internationalisatie is uitgebreid tot interfaces, spellingcontrole, en woordenboeken.

De tekstverwerker van Apache OpenOffice gebruikt een eigen XML-bestandsformaat voor overdraagbaarheid en flexibiliteit. Het spreadsheetprogramma bevat een macrotaal en kan gekoppeld worden aan externe databases. Apache OpenOffice is stabiel en draait zonder aanpassingen op Windows(R), Solaris(TM), Linux, FreeBSD en Mac OS(R) X. Meer informatie over Apache OpenOffice staat op de http://incubator.apache.org/openofficeorg/[Apache OpenOffice website]. Voor specifieke FreeBSD informatie en om direct pakketten te downloaden is er de website van het http://porting.openoffice.org/freebsd/[FreeBSD Apache OpenOffice Porting Team].

Om Apache OpenOffice te installeren:

[source,bash]
....
# pkg_add -r apache-openoffice
....

[NOTE]
====
Dit hoort te werken als er een -RELEASE versie van FreeBSD wordt gedraaid. In andere gevallen is het verstandig om te kijken op de website van het FreeBSD Apache OpenOffice Porting Team en het juiste pakket met man:pkg_add[1] te downloaden en te installeren. Zowel de huidige release als de ontwikkelversie kunnen op die locatie gedownload worden.
====

Als het pakket geïnstalleerd is, start dan met het volgende commando Apache OpenOffice:

[source,bash]
....
% openoffice-X.Y.Z
....

waarbij _X.Y.Z_ het versienummer van de geïnstalleerde Apache OpenOffice is, bijvoorbeeld _3.4.0_.

[NOTE]
====
Tijdens de eerste keer starten worden er een aantal vragen gesteld en wordt de map [.filename]#.openoffice.org# in de thuismap van de aangemelde gebruiker gemaakt.
====

Als de Apache OpenOffice pakketten niet beschikbaar zijn, kan het uit de ports gecompileerd worden. Hiervoor is veel schijfruimte en tijd nodig:

[source,bash]
....
# cd /usr/ports/editors/openoffice-3
# make install clean
....

[NOTE]
====
Vervang om een gelokaliseerde versie te bouwen de voorgaande commandoregel door de volgende:

[source,bash]
....
# make LOCALIZED_LANG=uw_taal install clean
....

Vervang _taal_ door de juiste ISO-taalcode. Een lijst met ondersteunde taalcodes is beschikbaar in het bestand [.filename]#files/Makefile.localized# in de map van de port.
====

Start hierna Apache OpenOffice met:

[source,bash]
....
% openoffice-X.Y.Z
....

waarbij _X.Y.Z_ het versienummer van de geïnstalleerde Apache OpenOffice is, bijvoorbeeld _3.4.0_.

=== LibreOffice

LibreOffice is een gratis kantoorpakket ontwikkeld door http://www.documentfoundation.org/[The Document Foundation] en is compatibel met andere grote kantoorpakketten en is beschikbaar op meerdere platforms. Het is een afsplitsing van OpenOffice.org onder een nieuw merk en bevat alle verwachte toepassingen van een compleet kantoorpakket: een tekstverwerker, een spreadsheet, een presentatiebeheerder, een tekenprogramma, een databasebeheerprogramma, en een programma om wiskundige formules te bewerken. Het is beschikbaar in een aantal verschillende talen - internationalisatie heeft zich uitgebreid naar interfaces, spellingcheckers en woordenboeken.

De tekstverwerker van LibreOffice gebruikt een eigen XML-bestandsformaat voor verhoogde portabiliteit en flexibiliteit. Het spreadsheetprogramma bevat een macrotaal en kan met externe databases gebruikt worden. LibreOffice is reeds stabiel en draait op Windows(R), Linux, FreeBSD, en Mac OS(R) X. Meer informatie over LibreOffice is te vinden op de http://www.libreoffice.org/[website van LibreOffice].

Om LibreOffice als een pakket te installeren:

[source,bash]
....
# pkg_add -r libreoffice
....

[NOTE]
====
Dit zou moeten werken met een -RELEASE-versie van FreeBSD.
====

Als het pakket is geïnstalleerd, dient de volgende opdracht gebruikt te worden om LibreOffice te draaien:

[source,bash]
....
% libreoffice
....

[NOTE]
====
Tijdens de eerste keer draaien worden u wat vragen gesteld en wordt er een map [.filename]#.libreoffice# aangemaakt in uw thuismap.
====

Als er geen pakket voor LibreOffice beschikbaar is, heeft u nog altijd de optie om de port te compileren. Denk er echter aan dat dit veel schijfruimte en redelijk veel tijd kost.

[source,bash]
....
# cd /usr/ports/editors/libreoffice
# make install clean
....

[NOTE]
====
Als u een gelokaliseerde versie wilt bouwen, dient u de vorige opdracht door het volgende te vervangen:

[source,bash]
....
# make LOCALIZED_LANG=uw_taal install clean
....

U dient _uw_taal_ te vervangen door de juiste ISO-taalcode. Een lijst met ondersteunde talen is beschikbaar in het doel `pre-fetch` van de [.filename]#Makefile# van de port.
====

Wanneer dit is gedaan, kan LibreOffice gestart worden met deze opdracht:

[source,bash]
....
% libreoffice
....

[[desktop-viewers]]
== Documentviewers

Sommige nieuwe documentformaten hebben aan populariteit gewonnen sinds de komst van UNIX(R); het kan zijn dat de standaardviewers die ze vereisen niet in het basissysteem zitten. In dit gedeelte wordt aangegeven hoe zulke viewers geïnstalleerd kunnen worden.

Dit gedeelte behandelt de onderstaande applicaties:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Applicatie
| Bronnen
| Ports
| Afhankelijkheden

|Acrobat Reader(R)
|weinig
|licht
|Linux(R) binaire compatibiliteit

|gv
|weinig
|licht
|Xaw3d

|Xpdf
|weinig
|licht
|FreeType

|GQview
|weinig
|licht
|Gtk+ of GNOME
|===

=== Acrobat Reader(R)

Documenten worden vaak als PDF-bestanden, "Portable Document Format", verspreid. Een van de aanbevolen viewers voor dit bestandstype is Acrobat Reader(R) dat Adobe voor Linux(R) heeft uitgegeven. Omdat FreeBSD Linux(R) binaries kan draaien, is het ook beschikbaar voor FreeBSD.

Om Acrobat Reader(R) 8 te installeren uit de Portscollectie:

[source,bash]
....
# cd /usr/ports/print/acroread8
# make install clean
....

Vanwege de licentie is een pakket niet beschikbaar.

=== gv

gv is een PostScript(R) en PDF viewer. Het is gebaseerd op ghostview maar heeft een vriendelijker uiterlijk dankzij de Xaw3d bibliotheek. Het is snel en heeft mogelijkheden, zoals oriëntatie, papiergrootte, schalen en anti-aliassen. Bijna elke bewerking kan met het toetsenbord of de muis worden gedaan.

gv is als pakket te installeren:

[source,bash]
....
# pkg_add -r gv
....

Of uit de Portscollectie:

[source,bash]
....
# cd /usr/ports/print/gv
# make install clean
....

=== Xpdf

Xpdf een efficiënte lichtgewicht PDF-viewer voor FreeBSD. Het heeft erg weinig bronnen nodig en is zeer stabiel. Het gebruikt de standaard X-fonts en is niet afhankelijk van Motif(R) of andere X-toolkits.

Xpdf is als pakket te installeren:

[source,bash]
....
# pkg_add -r xpdf
....

Of uit de Portscollectie:

[source,bash]
....
# cd /usr/ports/graphics/xpdf
# make install clean
....

Als de installatie voltooid is, kan Xpdf gestart worden en het menu kan met de rechtermuisknop geactiveerd worden.

=== GQview

GQview is een afbeeldingenbeheerder. Een bestand kan met één klik bekeken worden, er kan een externe editor opgestart worden er kunnen thumbnail-voorbeelden gemaakt worden en nog veel meer. Het bevat ook een diapresentatie-modus en enkele standaard bestandsoperaties. Er kunnen afbeeldingsverzamelingen beheerd worden en eenvoudig duplicaten gevonden worden. GQview kan het complete scherm gebruiken en ondersteunt meerdere talen.

GQview is als pakket te installeren:

[source,bash]
....
# pkg_add -r gqview
....

Of uit de Portscollectie:

[source,bash]
....
# cd /usr/ports/graphics/gqview
# make install clean
....

[[desktop-finance]]
== Financiën

Om financiën via het FreeBSD bureaublad te beheren zijn er krachtige en gemakkelijk te gebruiken applicaties om te installeren. Sommige zijn compatibel met wijdverbreide bestandsformaten, zoals de formaten gebruikt door Quicken en Excel om documenten op te slaan.

Dit gedeelte behandelt deze programma's:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Applicatie
| Bronnen
| Ports
| Afhankelijkheden

|GnuCash
|weinig
|zwaar
|GNOME

|Gnumeric
|weinig
|zwaar
|GNOME

|Abacus
|weinig
|licht
|Tcl/Tk

|KMyMoney
|weinig
|zwaar
|KDE
|===

=== GnuCash

GnuCash is onderdeel van GNOME dat gebruikersvriendelijke en krachtige applicaties aan eindgebruikers wil leveren. Met GnuCash kunnen inkomsten en uitgaven, bankrekeningen en voorraden bijgehouden worden. Het bevat een intuïtieve interface terwijl het erg professioneel blijft.

GnuCash levert een slim kasboek, een hiërarchisch systeem van rekeningen, en veel toetsenbordversnellers en auto-invul mogelijkheden. Het kan een transactie splitsen in meer gedetailleerde stukken. GnuCash kan Quicken QIF-bestanden invoeren en samenvoegen. Het kan ook met de meeste internationale datum- en valutaformaten omgaan.

GnuCash is als pakket te installeren:

[source,bash]
....
# pkg_add -r gnucash
....

Of uit de Portscollectie:

[source,bash]
....
# cd /usr/ports/finance/gnucash
# make install clean
....

=== Gnumeric

Gnumeric is een spreadsheetprogramma uit de GNOME bureaubladomgeving. Het maakt gebruikt van "auto-invullen" afhankelijk van het celformaat. Het kan bestanden in een aantal populaire formaten zoals Excel, Lotus 1-2-3 en Quattro Pro inlezen. Gnumeric ondersteunt grafieken door middel van het grafiekprogramma package:math/guppi[]. Het heeft een groot aantal ingebouwde functies en kent gebruikelijke celformaten als nummer, valuta, datum, tijd en veel meer.

Gnumeric is als pakket te installeren:

[source,bash]
....
# pkg_add -r gnumeric
....

Of uit de Portscollectie:

[source,bash]
....
# cd /usr/ports/math/gnumeric
# make install clean
....

=== Abacus

Abacus is een kleine en gemakkelijk te gebruiken spreadsheetprogramma. Het bevat veel ingebouwde functies die nuttig zijn in verschillende domeinen zoals statistiek, financiën, en wiskunde. Het kan Excel-bestanden lezen en schrijven. Abacus kan PostScript(R) uitvoer produceren.

Abacus is als pakket te installeren:

[source,bash]
....
# pkg_add -r abacus
....

Of uit de Portscollectie:

[source,bash]
....
# cd /usr/ports/deskutils/abacus
# make install clean
....

=== KMyMoney

KMyMoney is een persoonlijke financiële beheerder gebouwd voor KDE. KMyMoney poogt om alle belangrijke eigenschappen die in commerciële persoonlijke financiële beheerders zitten te bieden en te integreren. Gebruiksgemak en degelijke dubbele accounting zijn eigenschappen die worden benadrukt. KMyMoney importeert vanuit standaard Quicken Interchange Format (QIF) bestanden, houdt investeringen bij, kan met meerdere munteenheden overweg, en biedt een waaier aan rapporten. Mogelijkheden om OFX te importeren zijn via een aparte plugin beschikbaar.

Om KMyMoney als een pakket te installeren:

[source,bash]
....
# pkg_add -r kmymoney2
....

Als het pakket niet beschikbaar is, kan de Portscollectie gebruikt worden:

[source,bash]
....
# cd /usr/ports/finance/kmymoney2
# make install clean
....

[[desktop-summary]]
== Samenvatting

Hoewel FreeBSD populair is bij ISP's om zijn prestaties en stabiliteit, is het behoorlijk klaar voor dagelijks gebruik als een bureaublad. Met enkele duizenden applicaties als link:https://www.FreeBSD.org/applications/[pakketten] of link:https://www.FreeBSD.org/ports/[ports], is een perfect bureaublad te bouwen dat aan alle noden voldoet.

Nu volgt nog een overzicht van alle bureaubladapplicaties die in dit hoofdstuk zijn behandeld:

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Applicatie
| Package
| Port

|Opera
|`linux-opera`
|package:www/linux-opera[]

|Firefox
|`firefox`
|package:www/firefox[]

|Chromium
|`chromium`
|package:www/chromium[]

|KOffice
|`koffice-kde4`
|package:editors/koffice-kde4[]

|AbiWord
|`abiword`
|package:editors/abiword[]

|The GIMP
|`gimp`
|package:graphics/gimp[]

|Apache OpenOffice
|`openoffice`
|package:editors/openoffice-3[]

|LibreOffice
|`libreoffice`
|package:editors/libreoffice[]

|Acrobat Reader(R)
|`acroread`
|package:print/acroread8[]

|gv
|`gv`
|package:print/gv[]

|Xpdf
|`xpdf`
|package:graphics/xpdf[]

|GQview
|`gqview`
|package:graphics/gqview[]

|GnuCash
|`gnucash`
|package:finance/gnucash[]

|Gnumeric
|`gnumeric`
|package:math/gnumeric[]

|Abacus
|`abacus`
|package:deskutils/abacus[]

|KMyMoney
|`kmymoney2`
|package:finance/kmymoney2[]
|===
