# $Id: Makefile,v 1.2 1998-03-27 08:23:34 hanai Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

DOCS=	announce.sgml notes.sgml errata.sgml

.include "../../../web.mk"
# $Id: Makefile,v 1.2 1998-03-27 08:23:34 hanai Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

DOCS=	announce.sgml notes.sgml errata.sgml

.include "../../../web.mk"
