#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/snapshots/Makefile.inc,v 1.1 2005/06/08 16:46:01 andy Exp $
#
# Original revision: 1.1
#

WEBBASE?=	/data/ru/snapshots
DOC_PREFIX?=	${.CURDIR}/../../..
