# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/Makefile
# %SRCID%	38826
#

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = nl

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
