# $FreeBSD: www/en/ipv6/Makefile,v 1.1 2011/06/03 12:48:52 bz Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=		index.sgml
DOCS+=		ipv6only.sgml
DOCS+=		w6d.sgml

DATA+=		IPv6-badge-blue-256-trans.png

.include "${WEB_PREFIX}/share/mk/web.site.mk"
