# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/Makefile,v 1.2 2000/10/11 16:16:11 phantom Exp $
# Original version: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

SUBDIR =	dists
SUBDIR+=	docs
SUBDIR+=	links

DOCS =  advocacy.sgml
DOCS+=  howhelp.sgml
DOCS+=  index.sgml
DOCS+=  install.sgml
DOCS+=  newsflash.sgml
DOCS+=  press.sgml

#DATA=	j2j.gif

.include "../web.mk"
