# $FreeBSD$
# Original version: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

SUBDIR =	dists
SUBDIR+=	docs
SUBDIR+=	links

DOCS =  advocacy.sgml
DOCS+=  howhelp.sgml
DOCS+=  index.sgml
DOCS+=  install.sgml
DOCS+=  newsflash.sgml
DOCS+=  press.sgml

#DATA=	j2j.gif

.include "../web.mk"
