# $FreeBSD$
#
# Article: FreeBSD and Linux Comparison Whitepaper
#
# %SOURCE%    en_US.ISO8859-1/articles/linux-comparison/Makefile
# %SRCID%     1.1
#

MAINTAINER= gabor@FreeBSD.org

DOC?= article

FORMATS?= html
INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
