---
title: 前言
prev: books/handbook/
next: books/handbook/parti
---

[preface]
[[book-preface]]
= 前言
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums!:
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: 目录
:table-caption: 表
:figure-caption: 图
:example-caption: 例
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:

[[preface-audience]]
== 预期的读者

作为 FreeBSD 的新用户，您将会在本手册第一部分找到 FreeBSD 的安装方法，同时逐渐引入概念和习俗来加强 UNIX(R) 基础。 阅读这部分只需要您有探索的精神和接受新概念的能力。

读完这些之后，手册中很漫长的第二部分是 FreeBSD 中系统管理员感兴趣的所有主题的全面参考。 在阅读这些章节的内容时所需要的背景知识都注释在每一章节的大纲里面， 如果需要，可在阅读前进行预习。

要获得附加的信息来源列表，请查阅 crossref:bibliography[bibliography,参考文献]。

[[preface-changes-from3]]
== 相对于第三版的改动

目前的在线手册代表了数百位贡献者过去 10 年多所累积的努力成果。 以下是自 2004 年出版的两卷第三版之后的一些重要变更：

* crossref:dtrace[dtrace,DTrace]， DTrace， 增加了有关强大的 DTrace 性能分析工具有关的信息。
* crossref:filesystems[filesystems,文件系统 Support]， 文件系统支持， 增加 FreeBSD 上非原生文件系统有关的信息， 比如 Sun(TM) 的 ZFS。
* crossref:audit[audit,安全事件审计]， 安全事件审计， 增加了 FreeBSD 新的审计功能和使用方法。
* crossref:virtualization[virtualization,虚拟化]， 虚拟化， 增加了在虚拟化软件上安装 FreeBSD 有关的信息。

[[preface-changes-from2]]
== 相对于第二版的改动 (2004)

您目前看到的这本手册的第三版是 FreeBSD 文档计划的成员历时两年完成的顶峰之作。 这一版的内容已经增长到需要分成两卷才能印刷出版。 第三版包含了如下的的主要变动：

* crossref:config[config-tuning,设置和调整]， 配置和优化， 进行了扩充并增加了关于 ACPI 电源和资源管理， `cron` 系统实用程序，以及更多的内核优化选项的相关内容。
* crossref:security[security,安全]， 安全 一章增加了虚拟专用网 (VPNs)， 文件访问控制表 (ACLs)， 以及安全公告的内容。
* crossref:mac[mac,强制访问控制]， 强制访问控制 (MAC) 是这一版新增的章节。 它解释了什么是 MAC， 以及这一机制如何使您的 FreeBSD 系统更安全。
* crossref:disks[disks,存储]， 存储， 在原有基础上增加了 USB 存储设备， 文件系统快照， 文件系统容限， 基于文件及网络的文件系统， 以及与加密磁盘分区有关的内容。
* crossref:vinum[vinum-vinum,Vinum 卷管理程序]，Vinum， 是这一版中的新章节。 描述了如何使用这种提供了设备无关的逻辑磁盘、软件 RAID-0, RAID-1 和 RAID-5 的卷管理系统――Vinum。
* 在 crossref:ppp-and-slip[ppp-and-slip,PPP 和 SLIP]，PPP 和 SLIP 一章中增加了排除故障的说明。
* crossref:mail[mail,电子邮件]， 电子邮件 一章中增加了关于如何使用其它的邮件传输代理、 SMTP 认证、 UUCP、 fetchmail、 procmail、 以及其它进阶内容。
* crossref:network-servers[network-servers,网络服务器]，网络服务， 是新版中全新的一章。 这一章包括了如何架设 Apache HTTP 服务器、 ftpd， 以及用于支持 Microsoft(R) Windows(R) 客户的 Samba。 一些段落来自原先的 crossref:advanced-networking[advanced-networking,高级网络]， 进阶网络应用 一章。
* crossref:advanced-networking[advanced-networking,高级网络]，进阶网络应用 一章增加了关于在 FreeBSD 中使用 Bluetooth(R) 设备， 安装无线网络， 以及使用异步传输模式 (ATM) 网络的内容。
* 增加了一份词汇表， 用以说明整本书中出现的术语。
* 对于全书中图表进行了进一步的美化工作。

[[preface-changes]]
==  相对于第一版的改变 (2001)

本手册的第二版是 FreeBSD 文档计划的成员历时两年完成的顶峰之作。 第二版包含了如下的的主要变动：

* 添加了完整的索引。
* 用图形替换了以前所有用 ASCII 插图。
* 每个章节添加了标准大纲，列出了该章所包含的信息和读者所应该了解的知识。
* 内容逻辑地分成三个部分： "起步"，"系统管理"和"附录"。
* crossref:install[install,安装 FreeBSD] ("安装 FreeBSD") 新版本中使用了抓屏图片，使新用户更容易的领会正文。
* crossref:basics[basics,UNIX 基础] ("UNIX(R) 基础")扩充了进程、守护进程和信号的附加信息。
* crossref:ports[ports,安装应用程序. Packages 和 Ports] ("安装应用程序") 扩充了二进制包管理的附加信息。
* crossref:x11[x11,X Window 系统] ("X Window 系统") 新版本中着重介绍使用现代桌面技术例如 XFree86(TM) 4.x 上的 KDE 和 GNOME
* crossref:boot[boot,FreeBSD 引导过程] ("FreeBSD 启动过程") 对第一版内容进行扩充。
* crossref:disks[disks,存储] ("存储") 由第一版中两个单独的章节"磁盘"和"备份"合并而成。 我们认为这两部分作为一个整体比较容易理解。同时 RAID (包括硬件和软件 RAID) 部分也被添加进来。
* crossref:serialcomms[serialcomms,串口通讯] ("串口通信") 对第一版进行完善，并为 FreeBSD 4.x/5.x 做了更新。
* crossref:ppp-and-slip[ppp-and-slip,PPP 和 SLIP] ("PPP 和 SLIP") 全部更新。
* 许多新的内容被添加到 crossref:advanced-networking[advanced-networking,高级网络] ("高级网络").
* crossref:mail[mail,电子邮件] ("电子邮件")增加了关于配置 sendmail 的信息。
* crossref:linuxemu[linuxemu,Linux(R) 二进制兼容模式]("Linux(R) 兼容性") 增加了关于安装 Oracle(R) 和 SAP(R) R/3(R) 的信息。
* 第二版中也涵盖了下列主题：

** 配置和调整(crossref:config[config-tuning,设置和调整)])。
** 多媒体(crossref:multimedia[multimedia,多媒体])

[[preface-overview]]
== 本手册的组织

这本手册分成了五个逻辑清晰的部分。第一部分 _起步_ 涵盖了 FreeBSD 的安装和基本使用方法。 读者可根据自己的情况按顺序或者跳过一些熟悉的主题来阅读。第二部分 _常用操作_ 涵盖了 FreeBSD 常用的功能， 这部分可以不按顺序阅读。每个部分由一个简明的大纲开始， 这个大纲描述本章节涵盖的内容和读者应该已经知道的知识。 这主要是让读者可以更好的选择感兴趣的章节阅读。第三部分 _系统管理_ 涵盖了 FreeBSD 高级用户所感兴趣的广泛的话题。 第四部分 _网络通讯_ 包括了网络和服务的话题， 而第五部分则是资源信息的附录。

_crossref:introduction[introduction,介绍]， 介绍_::
向新用户介绍 FreeBSD。它描述了 FreeBSD 计划的历史、目标和开发模式。

_crossref:install[install,安装 FreeBSD]， 安装_::
本章将会带领用户完成安装过程。一些高级安装主题， 例如如何通过串行控制台安装，也涵盖在内。

_crossref:basics[basics,UNIX 基础]， UNIX(R) 基础_::
本章涵盖了 FreeBSD 操作系统基础命令和功能。 如果熟悉 Linux(R) 或者其他类 UNIX(R) 操作系统，则可以跳过这章。

_crossref:ports[ports,安装应用程序. Packages 和 Ports]， 安装应用程序_::
本章涵盖如何用 FreeBSD 的 "Ports Collection" 和标准二进制软件包来安装第三方软件。

_crossref:x11[x11,X Window 系统]， X Window 系统_::
本章概要地描述了 X Window System 系统并详细地介绍了如何在 FreeBSD 上使用它。 此外他也描述了常用的桌面环境， 例如 KDE 和 GNOME。

_crossref:desktop[desktop,桌面应用]， 桌面应用_::
列出了一些常用的桌面应用程序，比如 web 浏览器和办公套件， 描述了在 FreeBSD 上如何安装它们。

_crossref:multimedia[multimedia,多媒体]， 多媒体_::
展示了如何为您的系统设置声卡和视频回放支持。 也描述了一些简单的音频和视频应用程序。

_crossref:kernelconfig[kernelconfig,配置FreeBSD的内核]， 配置 FreeBSD 内核_::
解释了为什么需要配置一个新内核并提供了配置、 编译、安装自定义内核的详细说明。

_crossref:printing[printing,打印]， 打印_::
描绘了 FreeBSD 上打印机管理， 包括横幅页、打印统计，还有初始的设置。

_crossref:linuxemu[linuxemu,Linux(R) 二进制兼容模式]， Linux(R) 二进制兼容_::
描述了 FreeBSD 的 Linux(R) 兼容特性。 也提供了许多流行的 Linux(R) 应用程序的详细的安装说明， 比如 Oracle(R) 和 Mathematica(R)。

_crossref:config[config-tuning,设置和调整]， 配置和调整_::
本章描述了管理员调整 FreeBSD 系统以优化性能时可能用到的一些参数。 也描述了 FreeBSD 中的各种配置文件以及它们所在的位置。

_crossref:boot[boot,FreeBSD 引导过程]， 启动过程_::
本章描述 FreeBSD 的启动过程并且解释了如何用配置选项来控制这个过程。

_crossref:users[users,用户和基本的帐户管理]， 用户和基本帐号管理_::
本章描述了如何创建和操作用户帐号， 同样也论述了设置用户资源限制和其他账号管理任务的方法。

_crossref:security[security,安全]， 安全_::
描述了保证 FreeBSD 系统安全可以使用的许多工具， 这包括 Kerberos， IPsec 以及 OpenSSH。

_crossref:jails[jails,Jails]， Jail_::
介绍了 jail 框架， 以及 jail 相对于 FreeBSD 中传统的 chroot 支持的改进。

_crossref:mac[mac,强制访问控制]， 强制访问控制_::
解释了何谓强制访问控制 (MAC) 以及如何利用这一机制来加强 FreeBSD 系统的安全。

_crossref:audit[audit,安全事件审计]， 安全事件审计_::
介绍了 FreeBSD 事件审计是什么， 以及如何安装、 配置它， 并检查或监视审计记帐信息。

_crossref:disks[disks,存储]， 存储_::
本章描述了怎样用 FreeBSD 来管理存储介质和文件系统，包括物理磁盘、RAID 阵列、光学和磁带媒体、后备存储磁盘以及网络文件系统。

_crossref:geom[GEOM,GEOM. 模块化磁盘变换框架]， GEOM_::
介绍了 FreeBSD 中的 GEOM 框架是什么， 以及如何配置它所支持的各级 RAID。

_crossref:filesystems[filesystems,文件系统 Support], 文件系统支持_::
探讨了 FreeBSD 对非原生文件系统的支持，比如 Sun(TM) 的 Z 文件系统。

_crossref:vinum[vinum-vinum,Vinum 卷管理程序], Vinum_::
本章描述了怎样使用逻辑卷管理器 Vinum。它提供了设备无关的逻辑磁盘和软件 RAID-0、RAID-1 以及 RAID-5。

_crossref:virtualization[virtualization,虚拟化]， 虚拟化_::
介绍了虚拟化系统提供的功能， 以及如何配合 FreeBSD 使用它们。

_crossref:l10n[l10n,本地化－I18N/L10N使用和设置]， 本地化_::
本章描述了如何在 FreeBSD 上使用非英语语言。它涵盖了系统和应用程序级的本地化。

_crossref:cutting-edge[updating-upgrading,更新与升级 FreeBSD]， 更新与升级 FreeBSD_::
介绍了 FreeBSD-STABLE、 FreeBSD-CURRENT 以及 FreeBSD 发行版本之间的差异。 描述了一般用户如何紧跟开发过程并从中受益。 涵盖了如何更新用户的系统至发行版最新安全修正的方法。

_crossref:dtrace[dtrace,DTrace], DTrace_::
本章描述了如何在 FreeBSD 上配置和使用 Sun(TM) 的 DTrace 工具. 动态跟踪可以通过实时的系统分析，帮助找出系统性能瓶颈。

_crossref:serialcomms[serialcomms,串口通讯]， 串行通信_::
本章解释了如何连接终端和调制解调器到 FreeBSD 系统，包括拨入和拨出连接。

_crossref:ppp-and-slip[ppp-and-slip,PPP 和 SLIP]， PPP 和 SLIP_::
本章描述了如何用 FreeBSD 通过使用 PPP，SLIP 或者基于以太网的 PPP (PPPoE) 来连接远程系统。

_crossref:mail[mail,电子邮件]， 电子邮件_::
本章解释了一个 email 服务器的不同组成部分并且简单讨论了关于最流行的 mail 服务器软件 sendmail 的配置。

_crossref:network-servers[network-servers,网络服务]， 网络服务_::
提供了详细的指引和示范配置文件以说明如何将一台 FreeBSD 机器作为网络文件系统服务器， 域名服务器， 网络信息服务器或时间同步服务器来使用的方法。

_crossref:firewalls[firewalls,防火墙]， 防火墙_::
解释了基于软件的防火墙的原理， 并提供了关于配置 FreeBSD 上的几种防火墙的详细说明。

_crossref:advanced-networking[advanced-networking,高级网络应用]， 高级网络应用_::
描述了许多关于网络的主题，包括如何在您的局域网中共享 Internet 连接， 高级路由话题， 无线网络， Bluetooth(R)， ATM， IPv6以及许多高级话题。

_crossref:mirrors[mirrors,获取 FreeBSD]， 获取 FreeBSD_::
列出了获得 FreeBSD 安装 CDROM 或 DVDROM 的不同资源，也提供了允许您自由下载 FreeBSD 的不同 Internet 站点。

_crossref:bibliography[bibliography,参考书目]， 参考书目_::
由于本手册触及到了很多不同的主题，因而可能引发您想要获取更多详细的讲解。 参考书目列出了很多写作这本书时参考的好书。

_crossref:eresources[eresources,Internet 上的资源]， Internet 上的资源_::
讲述了很多对 FreeBSD 用户有用的能够提出问题并进行技术交流的关于 FreeBSD 的论坛。

_crossref:pgpkeys[pgpkeys,PGP 公钥]， PGP 公钥_::
列出了一些 FreeBSD 开发者的 PGP 签名公钥。

[[preface-conv]]
== 本书中使用的一些约定

为了使本书保持一致性和易读性特做了以下约定：

[[preface-conv-typographic]]
=== 排版约定

_斜体_::
_斜体_ 字用来表示文件名、URLs、强调文字和术语的主流用法。

`等宽`::
`等宽` 字体用来表示错误信息、 命令、 环境变量、 port 的名字、 主机名、 用户名、 组名、 设备名、 变量名， 以及代码片断。

粗体::
粗体 字用来表示应用程序、命令和关键字。

[[preface-conv-commands]]
=== 用户输入

按键用**粗体**来突出于其他文本。 组合键意味着字用``+``连接时，同时的按下它们，例如：

kbd:[Ctrl+Alt+Del]

表示您应该同时按下 kbd:[Ctrl]， kbd:[Alt] 和 kbd:[Del] 键。

按顺序依次键入的关键字通常是用逗号隔开，例如：

kbd:[Ctrl+X], kbd:[Ctrl+S]

这意味着用户应该同时按kbd:[Ctrl] 和 kbd:[X]，然后同时按 kbd:[Ctrl] 和 kbd:[S]。

[[preface-conv-examples]]
=== 示例

以 [.filename]#E:\># 开头的例子代表一个 MS-DOS(R) 命令。除非另有说明，这些命令都可以在一个现代的 Microsoft(R) Windows(R) "命令行"窗口环境被执行。

[source,bash]
....
E:\> tools\fdimage floppies\kern.flp A:
....

以 # 开头的例子代表必须以 FreeBSD 超级用户身份执行的命令。您可以用 `root` 身份登录来输入这些命令，或者以普通账号登录然后用 man:su[1] 来获得超级用户权限。

[source,bash]
....
# dd if=kern.flp of=/dev/fd0
....

以 % 开头的例子代表命令应该被普通账号执行。 除非另有说明， 在设置环境变量和使用的其他 shell 命令均为 C-shell 语法。

[source,bash]
....
% top
....

[[preface-acknowledgements]]
== 致谢

您所看到的这本书是全球几百人努力的结果。 无论他们只是纠正一些错误或提交完整的章节，所有的贡献都是非常有用的。

一些公司通过提供资金让作者专注于文档开发、 提供出版资金等等方式来支持文档开发。 其中， BSDi (后并入http://www.windriver.com[Wind River Systems]) 资助 FreeBSD 文档计划成员来专职改善这本书直到 2000 年三月第一个印刷版 (ISBN 1-57176-241-8) 的出版。 Wind River Systems 同时资助其他作者来对输出结构做很多改进和给文章添加一些附加章节。 这项工作结束于 2001 年 11 月印刷第二版 (ISBN 1-57176-303-1)。在 2003-2004 两年中，http://www.freebsdmall.com[FreeBSD Mall]， 向为改进这本手册以使其第三版印刷版本能够出版的志愿者支付了报酬。
