---
title: "Coordination des donations au projet FreeBSD"
sidenav: about
--- 

= Coordination des donations au projet FreeBSD

== Contenu

* <<goal,Objectif pour la coordination des donations>>
* <<charter,Charte>>
* <<donating,Faire un don au projet FreeBSD>>

== Autres liens au sujet des donations

* link:wantlist[Liste des besoins des développeurs FreeBSD]
* link:donors[Liste des donations]

[[goal]]
== Objectif

Parallèlement à l'augmentation du nombre d'utilisateurs de FreeBSD, le nombre de personnes qui désirent faire des dons matériels ou financiers a également augmenté. La coordination des donations a pour but de rationaliser la gestion de ces dons et de s'assurer qu'ils sont gérés de manière raisonnable et dans les meilleurs délais.

[[charter]]
== Charte

L'objectif du responsable des donations est d'encourager et de faciliter les donations en accord avec un ensemble de règles acceptés par la communauté FreeBSD. Ce responsable a les reponsabilités suivantes :

* établir et maintenir un ensemble claire de procédures pour la gestion des donations.
* répondre aux offres de dons dans un délai raisonnable.
* maintenir une liste d'équipements et de ressources dont aurait besoin la communauté FreeBSD.
* coordonner les offres de dons avec la communauté des développeurs FreeBSD.
* "guider" les donations à travers tout le processus de donation.
* coordonner une équipe de 3 à 4 personnes afin de s'assurer qu'une réponse correcte puisse être apportée dans un temps raisonnable à toute éventuelle question.
* remercier publiquement les donateurs et confirmer publiquement la réception des dons.
* enregistrer le statut de tous les prêts au Projet FreeBSD.
* fournir une liste consultable publiquement de tous les dons faits au profit de la communauté des développeurs FreeBSD.

[[donating]]
== Faire un don au projet FreeBSD

Donc, vous voulez faire don de quelque chose au projet FreeBSD ? Excellent ! Nous comptons beaucoup sur les dons d'utilisateurs pour accomplir nos objectifs. Merci de lire les informations ci-dessous pour savoir comment nous contacter à propos de votre don.

Si vous ne savez pas exactement ce que vous voulez donner, vous pouvez consulter notre link:wantlist[liste de besoins]. Nous recevrons avec plaisir n'importe quel objet de cette liste. Si vous avez du matériel que vous souhaitez donner, lisez ce qui suit.

[[taxcredit]]
=== Réduction d'impôts pour les donations

La "FreeBSD Foundation" peut être considérée comme organisation charitable en ce qui concerne les impôts. *SI VOUS HABITEZ AUX ETATS-UNIS*, votre don peut-être déduit de vos impôts sous certaines conditions. Si vous désirez un reçu pour déduire de vos impôts votre contribution, merci de le préciser avec les informations nécessaires pour votre donation.

Pouvoir bénéficier de cette réduction d'impôts n'est pas aussi simple qu'il n'y paraît. Les contributions déductibles doivent être envoyées à la "FreeBSD Foundation". Ensuite, un membre de la fondation doit s'occuper de la donation et l'envoyer à son destinataire final. La fondation doit aussi pouvoir démontrer que la donation est pour le _bien publique_. Tout cela fait que même si nous avons probablement des développeurs qui seraient intéressés par cette grosse boîte de cartes ISA qui dort dans votre débarras, vous ne pourrez sans doute pas avoir une réduction d'impôts pour ce don; la somme totale de travail nécessaire pour gérer, livrer et documenter ce don excéderait de loin leur valeur totale.

La "FreeBSD Foundation" fournira un reçu pour la livraison du matériel. Elle ne fera pas une estimation de la valeur marchande du matériel -- en fait, la loi lui interdit de le faire. Nous conseillons de rechercher ailleurs les évaluations des dons de matériels. Etant donné que la plupart des donations concernent du matériel obsolète, ce qui rend difficile une évaluation juste, nous suggérons de rechercher sur Ebay ou sur d'autres sites de matériels d'occasions les prix payés pour des équipements similaires.

=== Comment faire un don

Un des objectifs du Comité de Coordination des Donations est de faire le lien entre les donations et les développeurs qui peuvent les utiliser. Nous n'acceptons pas simplement n'importe quelle donation; nous prenons uniquement en charge celles qu'un développeur pourra utiliser dans le cadre du projet FreeBSD. Cela permet un gain de temps pour tout le monde et permet aussi d'apporter aux donateurs l'assurance que leurs contributions seront vraiment utiliser pour le projet FreeBSD. L'inconvénient est que nous avons besoin de quelques informations au sujet de votre donation avant de pouvoir l'accepter.

Les donations se classent généralement dans l'une de ces trois catégories :

* <<money,Financières>>
* <<systems,Ordinateurs complets>>
* <<hardware,Pièces détachées>>

Si vous avez quelque chose à offrir qui ne tombe pas dans l'une de ces catégories, pas d'inquiétude ! Contactez-nous à l'adresse donations@FreeBSD.org avec votre proposition. Ce n'est pas parce que cela sort de l'ordinaire que nous ne sommes pas intéressés.

[[money]]
=== Contributions financières

Le Projet FreeBSD n'accepte pas directement les contributions financières. Une autre organisation, la http://www.freebsdfoundation.org[FreeBSD Foundation], accepte les contributions financières pour notre compte. Merci de consulter leur site web pour tous les détails à propos des contributions financières.

[[systems]]
=== Ordinateurs complets

Le Projet FreeBSD a constamment besoin d'ordinateurs. Si vous possédez un ordinateur dont vous souhaitez faire don au Projet, merci de nous contacter avec les informations suivantes :

* Précisions sur le matériel : architecture, carte mère, processeur, espace disque, mémoire (si l'ordinateur est un Alpha, merci d'inclure également la sortie des commandes SHOW CONFIG, SHOW MEM et SHOW DEV.)
* Est-ce que ce système fonctionne actuellement sous FreeBSD ou est-il non supporté ? Si possible, merci de joindre la sortie de la commande dmesg à partir d'un FreeBSD installé sur ce système.
* Etes-vous prêts à expédier ce système ?
* Votre localisation géographique. Nous essayons de rendre l'expédition aussi simple et peu couteuse que possible.
* Précisez également si vous désirez une <<taxcredit,réduction d'impôts>> pour cet ordinateur (notez que toutes les donations ne peuvent pas en pratique donner lieu à une réduction d'impôts, le coût de gestion de la réduction pouvant dépasser la valeur de la donation).

[[components]]
=== Pièces détachées

Si vous avez des pièces détachées dont vous souhaitez faire don au Projet, merci de nous contacter avec les informations suivantes :

* Une description du matériel : modèle, numéro de série, fabricant, etc. Si vous avez un lien précis sur une page web du fabricant pour ce composant, cela sera très utile.
* Est-ce que ce matériel est actuellement supporté par FreeBSD ?
* Quelle documentation avez-vous ? Un composant ne suffit pas pour écrire un driver; les développeurs de driver ont besoin de données détaillées sur le composant de la part du fabricant (ne vous inquiétez pas trop si vous n'avez pas cette documentation, elle est sans doute disponible ailleurs).
* Etes-vous prêts à expédier ce matériel ?
* Votre localisation géographique. Nous essayons de rendre l'expédition aussi simple et peu couteuse que possible.
* Précisez également si vous désirez une <<taxcredit,réduction d'impôts>> pour cet ordinateur (notez que toutes les donations ne peuvent pas en pratique donner lieu à une réduction d'impôts, le coût de gestion de la réduction pouvant dépasser la valeur de la donation).

=== Que faisons-nous de ces informations

Une fois que nous avons une description de la donation, le Comité de Coordination des Donations contactera l'ensemble des développeurs pour leur faire part de l'offre. Si un développeur est intéressé, nous mettons en contact le donateur et le futur destinataire afin qu'ils se mettent d'accord sur la livraison. Si plusieurs développeurs sont intéressés, nous essayons de savoir ce que chaque développeur compte faire de ce don et nous l'allouons à ce qui paraît le plus profitable pour le Projet. Si aucun développeur n'est intéressé, nous déclinons l'offre.

Notre objectif est de placer (ou de décliner) toutes les donations dans un délai de 7 jours après la réception de toutes les informations.
