# $FreeBSDru: frdp/www/ru/developers/Makefile,v 1.1 2006/02/18 18:20:33 gad Exp $
# $FreeBSD$
#
# Original revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   cvs.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
