# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../../en/ports/Makefile.inc)
.include "../../en/ports/Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif


.include "../web.mk"
