# $FreeBSD: www/ja/ports/Makefile.inc0,v 1.1 1999/11/15 21:58:16 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.3

.if exists(${.CURDIR}/../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(${.CURDIR}/../../en/ports/Makefile.inc)
.include "../../en/ports/Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif


.include "../web.mk"
