---
title: Приложение C. Ресурсы в интернет
part: Часть V. Приложения
prev: books/handbook/bibliography
next: books/handbook/pgpkeys
---

[appendix]
[[eresources]]
= Ресурсы в интернет
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Содержание
:table-caption: Таблица
:figure-caption: Рисунок
:example-caption: Пример
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: C

include::shared/mirrors.adoc[]
include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/ru/mailing-lists.adoc[]
include::shared/ru/teams.adoc[]
include::shared/ru/urls.adoc[]

Высокая скорость прогресса FreeBSD делает непрактичным использование печатных изданий для информирования о последних разработках. Электронные ресурсы это лучший, а зачастую и единственный способ информирования о новых возможностях. Поскольку FreeBSD основывается на усилиях добровольцев, сообщество пользователей само по себе зачастую выполняет роль "службы технической поддержки", а электронная почта, веб форумы и новости USENET это наиболее эффективный способ обращения к этому сообществу.

Наиболее важная контактная информация сообщества пользователей FreeBSD показана ниже. Если вам известно о других ресурсах, не упомянутых здесь, пожалуйста отправьте информацию о них в {freebsd-doc}, чтобы мы могли включить в этот документ.

[[eresources-mail]]
== Списки рассылки

Обращение в списки рассылки является наиболее простым способом задания вопросов или открытия технических дискуссий в сосредоточенной аудитории пользователей и разработчиков FreeBSD. Существует большое разнообразие списков по десяткам разных тем FreeBSD. Обращение в наиболее подходящий список рассылки обеспечит вас более быстрым и более точным ответом.

[WARNING]
====

Все сообщения в приведенные ниже списки рассылки должны быть составлены _только на английском языке_.
====

Описание каждой рассылки дано в конце этого документа. _Пожалуйста, прочтите описание перед подпиской или отправкой почты в любой из списков_. Большинство наших подписчиков получают многие сотни относящихся к FreeBSD сообщений каждый день, и определяя правила использования рассылок мы стремимся удержать высокое соотношение "сигнал к шуму". При меньшем соотношении списки рассылки перестанут быть эффективной средой общения участников проекта.

[NOTE]
====
_Если вы желаете проверить возможность отправки сообщений в списки рассылки FreeBSD, пошлите тестовое сообщение на {freebsd-test}._ Пожалуйста, не шлите тестовые сообщения в любой другой список рассылки.
====

Если вы сомневаетесь, в какой именно список рассылки нужно направить вопрос, то прочтите статью link:{freebsd-questions-article}[Как эффективно использовать список рассылки FreeBSD-questions].

Перед тем, как направлять сообщение в любой список рассылки, пожалуйста, выясните, как лучше всего их использовать, например, как избежать частого повторения одних и тех же дискуссий, прочитав документ link:{mailing-list-faq}[Часто задаваемые вопросы о списках рассылки] (FAQ).

Архивы поддерживаются для всех списков рассылки и поиск по ним организован на link:https://www.FreeBSD.org/ru/search/[WWW сервере FreeBSD]. Поиск в архиве по ключевым словам дает отличный способ получения ответов на часто задаваемые вопросы и должен быть выполнен перед отправкой вопроса. Следует также отметить то, что отправленные в списки рассылок сообщения сохраняются в архивах навсегда. Если есть необходимость сохранить приватность, то задействуйте любой доступный вам второстепенный адрес электронной почты, предоставляя в сообщении лишь публичную информацию.

[[eresources-summary]]
=== Списки рассылки

_Общие списки:_ Ниже представлены общие списки рассылки, к которым каждый может (и приглашается) присоединиться:

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Список
| Назначение

|link:{freebsd-advocacy-url}[freebsd-advocacy]
|В защиту FreeBSD

|{freebsd-announce}
|Важные события и вехи проекта

|link:{freebsd-arch-url}[freebsd-arch]
|Обсуждения архитектуры и дизайна системы

|link:{freebsd-bugbusters-url}[freebsd-bugbusters]
|Обсуждения, относящиеся к поддержке базы данных сообщений о проблемах FreeBSD и соответствующим инструментам

|link:{freebsd-bugs-url}[freebsd-bugs]
|Сообщения о проблемах

|link:{freebsd-chat-url}[freebsd-chat]
|Не-технические темы, относящиеся к сообществу FreeBSD

|link:{freebsd-chromium-url}[freebsd-chromium]
|Вопросы, относящиеся к Chromium во FreeBSD

|{freebsd-current}
|Обсуждения, относящиеся к использованию FreeBSD-CURRENT

|link:{freebsd-isp-url}[freebsd-isp]
|Вопросы использования FreeBSD провайдерами

|link:{freebsd-jobs-url}[freebsd-jobs]
|Вакансии и резюме, относящиеся к FreeBSD, с полной и частичной занятостью

|link:{freebsd-policy-url}[freebsd-policy]
|Публикация правил FreeBSD Core team. Только для чтения, малое количество сообщений

|link:{freebsd-questions-url}[freebsd-questions]
|Вопросы пользователей и техническая поддержка

|{freebsd-security-notifications}
|Уведомления безопасности

|{freebsd-stable}
|Обсуждения, относящиеся к использованию FreeBSD-STABLE

|{freebsd-test}
|Рассылка для отправки тестовых сообщений (вместо обычных списков рассылки
|===

_Технические списки:_ Следующие списки предназначены для технических обсуждений. Вам необходимо внимательно прочитать описание перед подпиской или отправкой почты в один из этих списков, поскольку они предназначены для использования внутри проекта.

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Список
| Назначение

|{freebsd-acpi}
|Разработка ACPI и системы управления энергопотреблением

|link:{freebsd-afs-url}[freebsd-afs]
|Портирование AFS на FreeBSD

|link:{freebsd-aic7xxx-url}[freebsd-aic7xxx]
|Разработка драйверов для Adaptec(R) AIC 7xxx

|link:{freebsd-amd64-url}[freebsd-amd64]
|Портирование FreeBSD на системы AMD64

|link:{freebsd-apache-url}[freebsd-apache]
|Обсуждение портов, относящихся к Apache

|link:{freebsd-arm-url}[freebsd-arm]
|Портирование FreeBSD на процессоры ARM(R)

|link:{freebsd-atm-url}[freebsd-atm]
|Использование ATM сетей с FreeBSD

|link:{freebsd-audit-url}[freebsd-audit]
|Проект аудита исходных текстов

|link:{freebsd-binup-url}[freebsd-binup]
|Дизайн и разработка системы бинарных обновлений

|link:{freebsd-bluetooth-url}[freebsd-bluetooth]
|Использование технологии Bluetooth(R) во FreeBSD

|link:{freebsd-cluster-url}[freebsd-cluster]
|Использование FreeBSD в кластерах

|link:{freebsd-cvsweb-url}[freebsd-cvsweb]
|Поддержка CVSweb

|link:{freebsd-database-url}[freebsd-database]
|Обсуждение использования и разработки баз данных под FreeBSD

|link:{freebsd-doc-url}[freebsd-doc]
|Создание относящихся к FreeBSD документов

|link:{freebsd-drivers-url}[freebsd-drivers]
|Создание драйверов устройств для FreeBSD

|link:{freebsd-eclipse-url}[freebsd-eclipse]
|Использование в FreeBSD Eclipse IDE, а также приложений и портов для нее.

|link:{freebsd-eol-url}[freebsd-eol]
|Взаимная поддержка относящегося к FreeBSD программного обеспечения, более не поддерживаемого проектом FreeBSD.

|link:{freebsd-embedded-url}[freebsd-embedded]
|Использование FreeBSD во встроенных системах

|link:{freebsd-emulation-url}[freebsd-emulation]
|Эмуляция других систем, таких как Linux/MS-DOS(R)/Windows(R)

|link:{freebsd-firewire-url}[freebsd-firewire]
|Техническое обсуждение FreeBSD FireWire(R) (iLink, IEEE 1394)

|link:{freebsd-fs-url}[freebsd-fs]
|Файловые системы

|link:{freebsd-gecko-url}[freebsd-gecko]
|Проблемы со средствами визуализации Gecko

|link:{freebsd-geom-url}[freebsd-geom]
|Относящиеся к GEOM обсуждения и реализации

|link:{freebsd-gnome-url}[freebsd-gnome]
|Портирование GNOME и приложений GNOME

|link:{freebsd-hackers-url}[freebsd-hackers]
|Общее техническое обсуждение

|link:{freebsd-hardware-url}[freebsd-hardware]
|Общее обсуждение оборудования для FreeBSD

|link:{freebsd-i18n-url}[freebsd-i18n]
|Интернационализация FreeBSD

|link:{freebsd-ia32-url}[freebsd-ia32]
|FreeBSD на платформе IA-32 (Intel(R) x86)

|link:{freebsd-ia64-url}[freebsd-ia64]
|Портирование FreeBSD на будущие системы Intel(R) IA64

|link:{freebsd-ipfw-url}[freebsd-ipfw]
|Технические обсуждения, относящиеся к переработке кода IP брандмауэра

|link:{freebsd-isdn-url}[freebsd-isdn]
|Разработчики ISDN

|link:{freebsd-jail-url}[freebsd-jail]
|Обсуждение man:jail[8]

|link:{freebsd-java-url}[freebsd-java]
|Разработчики Java(TM) и те, кто занимается переносом JDK(TM) на FreeBSD

|link:{freebsd-kde-url}[freebsd-kde]
|Портирование KDE и приложений KDE

|link:{freebsd-lfs-url}[freebsd-lfs]
|Портирование LFS на FreeBSD

|link:{freebsd-libh-url}[freebsd-libh]
|Второе поколение программы установки системы и пакетов

|link:{freebsd-mips-url}[freebsd-mips]
|Портирование FreeBSD на MIPS(R)

|link:{freebsd-mobile-url}[freebsd-mobile]
|Обсуждение портативных компьютеров

|link:{freebsd-mono-url}[freebsd-mono]
|Mono и C# приложения на FreeBSD

|link:{freebsd-mozilla-url}[freebsd-mozilla]
|Портирование Mozilla на FreeBSD

|{freebsd-multimedia}
|Мультимедиа приложения

|link:{freebsd-new-bus-url}[freebsd-new-bus]
|Технические обсуждения архитектуры шины

|link:{freebsd-net-url}[freebsd-net]
|Обсуждения, относящиеся к сети и исходному тексту TCP/IP

|link:{freebsd-office-url}[freebsd-office]
|Офисные приложения во FreeBSD

|link:{freebsd-performance-url}[freebsd-performance]
|Вопросы оптимизации производительности для быстрых/работающих под большой нагрузкой серверов

|link:{freebsd-perl-url}[freebsd-perl]
|Поддержка различных портов, относящихся к Perl

|link:{freebsd-pf-url}[freebsd-pf]
|Обсуждение брандмауэра на базе packet filter

|link:{freebsd-platforms-url}[freebsd-platforms]
|Относится к портам для платформ не-Intel(R) архитектуры

|link:{freebsd-ports-url}[freebsd-ports]
|Обсуждения Коллекции Портов

|link:{freebsd-ports-bugs-url}[freebsd-ports-bugs]
|Обсуждения относящихся к портам ошибок/PR

|link:{freebsd-ppc-url}[freebsd-ppc]
|Портирование FreeBSD на PowerPC(R)

|link:{freebsd-proliant-url}[freebsd-proliant]
|Работа FreeBSD на серверной платформе HP ProLiant

|link:{freebsd-python-url}[freebsd-python]
|Вопросы, специфичные для использования Python во FreeBSD

|link:{freebsd-rc-url}[freebsd-rc]
|Обсуждения, касающиеся системы [.filename]#rc.d# и работы над ней

|link:{freebsd-realtime-url}[freebsd-realtime]
|Разработка расширений реального времени для FreeBSD

|link:{freebsd-ruby-url}[freebsd-ruby]
|Обсуждения, касающиеся специфики использования Ruby во FreeBSD

|link:{freebsd-scsi-url}[freebsd-scsi]
|Подсистема SCSI

|{freebsd-security}
|Сообщения безопасности, касающиеся FreeBSD

|link:{freebsd-small-url}[freebsd-small]
|Использование FreeBSD во встроенных приложениях (устарел; следует использовать link:{freebsd-embedded-url}[freebsd-embedded])

|link:{freebsd-sparc64-url}[freebsd-sparc64]
|Портирование FreeBSD на системы, основанные на SPARC(R)

|link:{freebsd-standards-url}[freebsd-standards]
|Соответствие FreeBSD стандартам C99 и POSIX(R)

|link:{freebsd-sysinstall-url}[freebsd-sysinstall]
|Разработка man:sysinstall[8]

|link:{freebsd-threads-url}[freebsd-threads]
|Потоки в FreeBSD

|link:{freebsd-testing-url}[freebsd-testing]
|Тестирование производительности и стабильности FreeBSD

|link:{freebsd-tilera-url}[freebsd-tilera]
|Портирование FreeBSD на процессоры Tilera

|link:{freebsd-tokenring-url}[freebsd-tokenring]
|Поддержка Token Ring в FreeBSD

|link:{freebsd-toolchain-url}[freebsd-toolchain]
|Поддержка встроенных инструментальных средств FreeBSD

|link:{freebsd-usb-url}[freebsd-usb]
|Обсуждение поддержки USB в FreeBSD

|link:{freebsd-virtualization-url}[freebsd-virtualization]
|Обсуждение различных техник виртуализации, поддерживаемых FreeBSD

|link:{freebsd-vuxml-url}[freebsd-vuxml]
|Обсуждение инфраструктуры VuXML

|link:{freebsd-x11-url}[freebsd-x11]
|Сопровождение и поддержка X11 в FreeBSD

|link:{freebsd-xen-url}[freebsd-xen]
|Обсуждение портирования FreeBSD на Xen(TM) - реализация и использование
|===

_Ограниченные списки:_ Следующие списки рассылки предназначены для более специализированной (и более официальной) аудитории и вероятно не могут заинтересовать широкую публику. Вероятно хорошей идеей будет сначала наладить общение в технических списках рассылки перед присоединением к ограниченным спискам, так вы сможете освоить этику общения.

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Список
| Назначение

|link:{freebsd-hubs-url}[freebsd-hubs]
|Люди, поддерживающие зеркала (поддержка инфраструктуры)

|link:{freebsd-user-groups-url}[freebsd-user-groups]
|Координация групп пользователей

|link:{freebsd-vendors-url}[freebsd-vendors]
|Координация поставщиков перед релизом

|link:{freebsd-wip-status-url}[freebsd-wip-status]
|Статус начатых работ (Work-In-Progress) во FreeBSD

|link:{freebsd-wireless-url}[freebsd-wireless]
|Обсуждение разработки стека 802.11, утилит, драйверов устройств

|link:{freebsd-www-url}[freebsd-www]
|Ответственные за link:https://www.FreeBSD.org/[www.FreeBSD.org]
|===

_Дайджест рассылки:_ Все вышеприведенные списки доступны в формате дайджеста. После подписки на рассылку, вы можете изменить параметры дайджеста в разделе настроек учетной записи.

_CVS и SVN рассылки:_ Следующие рассылки предназначены для людей, заинтересованных в просмотре сообщений об изменении в различных областях дерева исходных текстов. Это списки _только для чтения_ и вы не должны отправлять туда почту.

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Рассылка
| Область исходного текста
| Описание области исходного текста

|link:{cvs-all-url}[cvs-all]
|[.filename]#/usr/(CVSROOT\|doc\|ports)#
|Все изменения в любой области дерева исходных текстов (надмножество других списков рассылки CVS)

|link:{cvs-doc-url}[cvs-doc]
|[.filename]#/usr/(doc\|www)#
|Все изменения в дереве исходных текстов документации и Web-сервера

|link:{cvs-ports-url}[cvs-ports]
|[.filename]#/usr/ports#
|Все изменения в дереве портов

|link:{cvs-projects-url}[cvs-projects]
|[.filename]#/usr/projects#
|Все изменения в дереве проектов

|link:{cvs-src-url}[cvs-src]
|[.filename]#/usr/src#
|Все изменения в дереве исходных текстов системы (создаваемых во время импорта из SVN в CVS)

|{svn-src-all}
|[.filename]#/usr/src#
|Все изменения в репозитории Subversion (за исключением [.filename]#user# и [.filename]#projects#)

|{svn-src-head}
|[.filename]#/usr/src#
|Все изменения в ветке "head" репозитория Subversion (ветка FreeBSD-CURRENT)

|link:{svn-src-projects-url}[svn-src-projects]
|[.filename]#/usr/projects#
|Все изменения в части [.filename]#projects# дерева исходных текстов репозитория Subversion

|link:{svn-src-release-url}[svn-src-release]
|[.filename]#/usr/src#
|Все изменения в части [.filename]#release# дерева исходных текстов репозитория Subversion

|link:{svn-src-releng-url}[svn-src-releng]
|[.filename]#/usr/src#
|Все изменения в части [.filename]#releng# дерева исходных текстов репозитория Subversion

|link:{svn-src-stable-url}[svn-src-stable]
|[.filename]#/usr/src#
|Все изменения во всех ветках stable дерева исходных текстов репозитория Subversion

|link:{svn-src-stable-6-url}[svn-src-stable-6]
|[.filename]#/usr/src#
|Все изменения в ветке [.filename]#stable/6# дерева исходных текстов репозитория Subversion

|link:{svn-src-stable-7-url}[svn-src-stable-7]
|[.filename]#/usr/src#
|Все изменения в ветке [.filename]#stable/7# дерева исходных текстов репозитория Subversion

|link:{svn-src-stable-8-url}[svn-src-stable-8]
|[.filename]#/usr/src#
|Все изменения в ветке [.filename]#stable/8# дерева исходных текстов репозитория Subversion

|link:{svn-src-stable-other-url}[svn-src-stable-other]
|[.filename]#/usr/src#
|Все изменения в предыдущих ветках [.filename]#stable# дерева исходных текстов репозитория Subversion

|link:{svn-src-svnadmin-url}[svn-src-svnadmin]
|[.filename]#/usr/src#
|Все изменения в административных скриптах, хуках (hook) и других конфигурационных параметрах дерева исходных текстов репозитория Subversion

|link:{svn-src-user-url}[svn-src-user]
|[.filename]#/usr/src#
|Все изменения в экспериментальной части [.filename]#user# дерева исходных текстов репозитория Subversion

|link:{svn-src-vendor-url}[svn-src-vendor]
|[.filename]#/usr/src#
|Все изменения в части дерева исходных текстов репозитория Subversion, выделенной для работы поставщиков (vendor)
|===

[[eresources-subscribe]]
=== Как подписаться

Для подписки на рассылку, нажмите на название списка рассылки выше или воспользуйтесь ссылкой {mailman-lists-url} и нажмите на имя рассылки, которой вы заинтересовались. Страница списка рассылки содержит все необходимые инструкции по подписке.

Для отправки сообщения в выбранный список рассылки, отправьте письмо в mailto:listname@FreeBSD.org[listname@FreeBSD.org]. Это письмо будет разослано участникам рассылки по всему миру.

Для отписки от рассылки, нажмите на ссылку, находящуюся внизу каждого письма, отправляемого через список рассылки. Возможна также отписка путем отправки письма на mailto:listname-unsubscribe@FreeBSD.org[listname-unsubscribe@FreeBSD.org].

Напоминаем, что обсуждение в технических списках рассылки должно оставаться в рамках технической темы. Если вас интересует только получение важных анонсов, мы предлагаем подписаться на рассылку с небольшим трафиком {freebsd-announce}.

[[eresources-charters]]
=== Описание рассылок

_Все_ списки рассылки FreeBSD имеют определенные основные правила, которых должен придерживаться каждый использующий их. Несоблюдение этих правил приведет к отправлению двух (2) предупреждений от FreeBSD Postmaster mailto:postmaster@FreeBSD.org[postmaster@FreeBSD.org], после которых, после третьего нарушения, подписчик будет удален из всех списков рассылки FreeBSD и дальнейшие его сообщения будут отфильтровываться. Мы сожалеем, что эти правила и меры вообще необходимы, но современный интернет это довольно суровая среда и многие его механизмы довольно слабы.

Основные правила:

* Тема любого сообщения должна соответствовать назначению списка рассылки, в который это сообщение отправляется. Например, если список рассылки посвящен техническим вопросам, сообщение должно быть техническим. Продолжающееся обсуждение вне темы, или флейм только понижают ценность рассылки для всех ее участников и поэтому не разрешаются. Для обсуждений вне какой-либо определенной темы необходимо использовать {freebsd-chat}, специально для этого предназначенный.
* Ни одно сообщение не должно отправляться более чем в 2 рассылки, отправка сообщения в 2 рассылки должна выполняться только при наличии простой и очевидной причины для дублирования сообщения. В большинстве рассылок подписчикам уже приходит много избыточного материала, и за исключением редких случаев (скажем, "-stable & -scsi"), на самом деле нет причины отправлять сообщение более чем в один список рассылки. Если сообщение отправлено вам так, что в поле `Cc` находятся несколько списков рассылки, необходимо урезать поле `Cc` перед отправкой ответа. _Именно вы отвечаете за собственные сообщения, независимо от того, кто был автором исходного письма._
* Персональные нападки и профанация (в контексте аргументов) не разрешены, это относится и к пользователям, и к разработчикам. Грубые нарушения сетевой этики, такие как цитирование или пересылка личной переписки без специального на то разрешения, осуждаются но специальные меры в этом случае не принимаются. _Однако_, существует несколько специальных случаев, когда такие письма не отвечают назначению списка рассылки и, следовательно, могут повлечь отправку предупреждения (или исключение из списка рассылки).
* Реклама не-FreeBSD продуктов или сервисов строго запрещена и исключение из списка рассылки последует незамедлительно, если станет очевидным, что это спам.

_Описания рассылок:_

{freebsd-acpi}::
_Разработка ACPI и системы управления энергопотреблением_

link:{freebsd-afs-url}[freebsd-afs]::
_Andrew File System_
+
Этот список предназначен для обсуждения портирования и использования AFS от CMU/Transarc

{freebsd-announce}::
_Важные события / вехи проекта_
+
Этот список рассылки предназначен для тех, кто интересуется только периодическими анонсами значительных событий FreeBSD. Сюда включаются анонсы снэпшотов и других релизов, а также новых возможностей FreeBSD. Рассылка может содержать призыв к добровольцам и т.п. Это строго модерируемый список рассылки с малым объемом трафика.

link:{freebsd-arch-url}[freebsd-arch]::
_Обсуждение архитектуры и дизайна системы_
+
Эта рассылка предназначена для обсуждения архитектуры FreeBSD. Сообщения в основном строго технические. Примеры подходящих тем:

** Как изменить систему сборки для одновременной сборки нескольких по-разному настроенных систем.
** Что необходимо исправить в VFS для включения слоев Heidemann.
** Как необходимо изменить интерфейс драйверов устройств для использования одних и тех же драйверов на множестве шин и архитектур.
** Как написать сетевой драйвер.

link:{freebsd-audit-url}[freebsd-audit]::
_Проект аудита исходных текстов_
+
Это список рассылки для проекта аудита исходных текстов FreeBSD. Хотя первоначально он предназначался для изменений, связанных с безопасностью, его назначение было расширено для пересмотра всех изменений кода.
+
В эту рассылку отправляется большой объем исправлений, и она вероятно не представляет интереса для обычного пользователя FreeBSD. Обсуждения безопасности, не относящиеся к определенному изменению в коде, ведутся в freebsd-security. Разработчикам предлагается отправлять изменения в этот список рассылки для просмотра, особенно если эти изменения затрагивают части кода, ошибки в которых могут повлечь нарушение целостности системы.

link:{freebsd-binup-url}[freebsd-binup]::
_Проект бинарного обновления FreeBSD_
+
Этот список предназначен для обсуждений системы бинарного обновления системы, или binup. В этой рассылке обсуждаются вопросы дизайна, детали реализации, исправления, сообщения об ошибках, сообщения о статусе, запросы на расширение функциональности, протоколы коммитов, и все, что относится к binup.

link:{freebsd-bluetooth-url}[freebsd-bluetooth]::
_Bluetooth(R) во FreeBSD_
+
Это форум, где собираются пользователи Bluetooth(R) во FreeBSD. Обсуждения касаются вопросов архитектуры, деталей реализации, патчей, сообщений об ошибках, состояния работы, запросов на добавление функций и всего, что относится к Bluetooth(R).

link:{freebsd-bugbusters-url}[freebsd-bugbusters]::
_Координация усилий по обработке сообщений о проблемах_
+
Назначение этой рассылки в координации и предоставлении места для обсуждения для лиц, обслуживающих базу данных сообщений о проблемах (bugmeister, bugbusters) и для всех сторон, интересующихся базой данных PR. Эта рассылка не предназначена для обсуждения отдельных проблем, исправлений или PR.

link:{freebsd-bugs-url}[freebsd-bugs]::
_Сообщения об ошибках_
+
Этот список рассылки предназначен для отправки сообщений об ошибках в FreeBSD. Когда это возможно, сообщения должны отправляться с использованием man:send-pr[1] или через link:https://www.FreeBSD.org/ru/send-pr/[WEB интерфейс] к `send-pr`.

link:{freebsd-chat-url}[freebsd-chat]::
_Не-технические темы, относящиеся к сообществу FreeBSD_
+
В эту рассылку входят все темы, не подходящие для других рассылок, с не-технической, социальной информацией. Она включает обсуждения на темы:  кто пьет слишком много кофе, где варят лучшее пиво, кто варит пиво в своем подвале, и так далее. Нерегулярные анонсы важных событий (такие как будущие встречи, свадьбы, дни рождения, новая работа и т.д.) могут быть опубликованы в технических рассылках, но ответы должны отправляться в -chat.

link:{freebsd-chromium-url}[freebsd-chromium]::
_Вопросы, относящиеся к Chromium во FreeBSD_
+
Список рассылки, предназначенный для обсуждения поддержки Chromium во FreeBSD. Это технический список рассылки, в котором обговаривается разработка и установка Chromium.

{core-name}::
_Команда FreeBSD core_
+
Это внутренний список рассылки, используемый членами core. Сообщения в эту рассылку могут быть отправлены по серьезной, имеющей отношение к FreeBSD причине, которая требует рассмотрения на самом высоком уровне.

{freebsd-current}::
_Обсуждения, касающиеся использования FreeBSD-CURRENT_
+
Это список рассылки для пользователей FreeBSD-CURRENT. Он включает предупреждения о новых возможностях, вносимых в -CURRENT, влияющих на пользователей, и инструкции относительно действий, которые должны быть предприняты для поддержки -CURRENT. Всякий, работающий с "CURRENT", должен подписаться на эту рассылку. Это технический список рассылки, все сообщения должны быть строго техническими.

link:{freebsd-cvsweb-url}[freebsd-cvsweb]::
_FreeBSD CVSweb Project_
+
Технические обсуждения использования, разработки и поддержки FreeBSD-CVSweb.

link:{freebsd-doc-url}[freebsd-doc]::
_Проект документирования_
+
Этот список рассылки предназначен для обсуждения вопросов и проектов, относящихся к созданию документации для FreeBSD. Члены этой рассылки все вместе обозначаются как "The FreeBSD Documentation Project". Это открытая рассылка; присоединяйтесь и участвуйте!

link:{freebsd-drivers-url}[freebsd-drivers]::
_Создание драйверов устройств для FreeBSD_
+
Этот список рассылки предназначен для технических дискуссий, относящихся к написанию драйверов устройств для FreeBSD. Это наилучшее место для того, чтобы задать вопросы по форматам и протоколам общенияi (API) драйверов устройств с ядром FreeBSD.

link:{freebsd-eclipse-url}[freebsd-eclipse]::
_Список рассылки для пользователей системы Eclipse IDE под FreeBSD, а также ее приложений и портов._
+
Этот список рассылки призван оказать помощь тем, кто выбирает, устанавливает, использует, разрабатывает и поддерживает работу Eclipse IDE под FreeBSD, а также портирует их под FreeBSD.
+
Кроме того, в данном списке для общего блага пересекаются и обмениваются информацией сообщества Eclipse и FreeBSD.
+
Хотя данный список предназначен главным образом для тех, кто использует Eclipse, в нем также можно обсуждать средства разработки приложений для FreeBSD при помощи среды Eclipse. 

link:{freebsd-embedded-url}[freebsd-embedded]::
_Использование FreeBSD во встроенных системах_
+
Этот список рассылки, предназначенный для технических обсуждений, рассматривает работу FreeBSD в особо стесненных условиях, в частности, во встроенных (embedded) системах. В данном случае встроенными считаются вычислительные устройства, отличные от настольных компьютеров и выполняющие, как правило, специализированные задачи. Примером могут служить смартфоны, сетевые устройства, такие как маршрутизаторы, коммутаторы и офисные АТС, телеметрические системы, КПК, кассовые терминалы и т.п.

link:{freebsd-emulation-url}[freebsd-emulation]::
_Эмуляция других систем, таких как Linux/MS-DOS(R)/Windows(R) _
+
Этот список рассылки предназначен для обсуждения вопросов запуска и эксплуатации под FreeBSD программ, предназначенных для работы под другими операционными системами.

link:{freebsd-eol-url}[freebsd-eol]::
_Взаимная поддержка относящегося к FreeBSD программного обеспечения, более не поддерживаемого проектом FreeBSD._
+
Этот список рассылки предназначен для интересующихся предоставлением или использованием взаимной поддержки относящегося к FreeBSD программного обеспечения, для которого проект FreeBSD более не предоставляет официальной поддержки (например, в виде сообщений безопасности или патчей).

link:{freebsd-firewire-url}[freebsd-firewire]::
_FireWire(R) (iLink, IEEE 1394)_
+
Это список рассылки, предназначенный для обсуждения дизайна и реализации подсистемы FireWire(R) (также известной как IEEE 1394 или iLink) в FreeBSD. Соответствующие темы относятся к стандартам, устройствам шины и их протоколам, наборам плат/карт/чипов адаптера, а также архитектуре и реализации кода для их правильной поддержки.

link:{freebsd-fs-url}[freebsd-fs]::
_Файловые системы_
+
Обсуждения, относящиеся к файловым системам FreeBSD. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-gecko-url}[freebsd-gecko]::
_Средства визуализации Gecko_
+
Дискуссия о приложениях Gecko, используемых на FreeBSD.
+
Обсуждение сосредоточено вокруг портированных приложений Gecko, их установки, разработки и поддержки во FreeBSD.

link:{freebsd-geom-url}[freebsd-geom]::
_GEOM_
+
Обсуждения, относящиеся к GEOM и связанным с GEOM реализациям. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-gnome-url}[freebsd-gnome]::
_GNOME_
+
Обсуждения, относящиеся к графической среде GNOME для системы FreeBSD. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-ipfw-url}[freebsd-ipfw]::
_IP брандмауэр_
+
Это форум для технических обсуждений, относящихся к перепроектированию кода межсетевого экрана IP во FreeBSD. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-ia64-url}[freebsd-ia64]::
_Портирование FreeBSD на IA64_
+
Это технический список рассылки для тех, кто активно работает над портированием FreeBSD на платформу IA-64 от Intel(R), предназначенный для поднятия вопросов или обсуждения альтернативных решений. Те, кто интересуется обсуждаемыми проблемами, также приглашаются к участию в рассылке.

link:{freebsd-isdn-url}[freebsd-isdn]::
_ISDN соединения_
+
Это список рассылки для обсуждения разработки поддержки ISDN для FreeBSD.

link:{freebsd-java-url}[freebsd-java]::
_Разработка Java(TM)_
+
Этот список рассылки предназначен для обсуждения ключевых приложений Java(TM) для FreeBSD, а также портирования и поддержки JDK(TM).

[[eresources-charters-jobs]]
link:{freebsd-jobs-url}[freebsd-jobs]::
_Предложение и поиск работы_
+
Это форум для публикации вакансий и резюме, относящихся к FreeBSD. Например, если вы ищете работу, относящеюся к FreeBSD, или у вас есть работа, связанная с FreeBSD, вы можете разместить соответствующую информацию именно здесь. Эта рассылка _не_ предназначена для обсуждения общих вопросов о приеме на работу, поскольку форумы на соответствующие темы уже существуют на других сайтах.
+
Имейте ввиду, что эта рассылка, как и другие рассылки `FreeBSD.org`, распространяется по всему миру. Поэтому вам необходимо чётко указать свое местоположение и область, с которой возможны телекоммуникации или помощь в перемещении.
+
Письма должны быть составлены только в открытых форматах - предпочтителен чистый текст, но Portable Document Format (PDF), HTML, и некоторые другие форматы могут быть прочитаны многими. Закрытые форматы, такие как Microsoft(R) Word ([.filename]#.doc#) будут отброшены сервером почтовой рассылки.

link:{freebsd-kde-url}[freebsd-kde]::
_KDE_
+
Обсуждения, относящиеся к KDE в системах FreeBSD. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-hackers-url}[freebsd-hackers]::
_Технические обсуждения_
+
Это форум для технических обсуждений, относящихся к FreeBSD. Это в основном технический список рассылки. Он предназначен для тех, кто активно работает над FreeBSD, и служит для поднятия вопросов или обсуждения альтернативных решений. Те, кто интересуется обсуждаемыми вопросами, также приглашаются к участию в обсуждении. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-hardware-url}[freebsd-hardware]::
_Общее обсуждение оборудования FreeBSD_
+
Общее обсуждение типов оборудования, на котором работает FreeBSD, различных проблем и предложений относительно того, какое оборудование можно покупать а какое нет.

link:{freebsd-hubs-url}[freebsd-hubs]::
_Сайты зеркал_
+
Анонсы и обсуждения для поддерживающих зеркала FreeBSD.

link:{freebsd-isp-url}[freebsd-isp]::
_Вопросы использования FreeBSD провайдерами_
+
Этот список рассылки предназначен для обсуждения тем, имеющих значение для провайдеров, использующих FreeBSD. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-mono-url}[freebsd-mono]::
_Mono и C# приложения на FreeBSD_
+
Этот список рассылки посвящен обсуждениям разработки инфраструктуры Mono на FreeBSD. Это технический список рассылки, который предназначен для людей, активно работающих над портированием Mono или C# приложений на FreeBSD, для освещения проблем или обсуждения альтернативных решений. Также к дискуссии приглашаются все заинтересованные данной темой.

link:{freebsd-office-url}[freebsd-office]::
_Офисные приложения во FreeBSD_
+
Тема этого списка рассылки - офисные приложения, установка офисных приложений, их разработка и поддержка во FreeBSD.

link:{freebsd-performance-url}[freebsd-performance]::
_Обсуждения оптимизации или повышения скорости FreeBSD_
+
Этот список рассылки существует как место для обсуждения тем, имеющих отношение к производительности FreeBSD, хакерами, администраторами, и/или заинтересованными сторонами. Приемлемые темы включают обсуждения установок FreeBSD, которые находятся под высокой нагрузкой и сталкиваются с проблемами производительности, или преодоление ограничений FreeBSD. Заинтересованным сторонам, собирающимся работать над улучшением производительности FreeBSD, настоятельно рекомендуется подписаться на эту рассылку. Это техническая рассылка, идеально подходящая для пользователей, хакеров или администраторов, заинтересованных в скорости, стабильности и расширяемости FreeBSD. Это не рассылка вопросов-и-ответов, заменяющая чтение документации, а место, где можно внести свой вклад или получить информацию по еще незатронутой теме, связанной с производительностью.

link:{freebsd-pf-url}[freebsd-pf]::
_Обсуждение брандмауэра на базе packet filter_
+
Обсуждения, касающиеся работы пакетного фильтра pf под FreeBSD. Допускаются как вопросы пользователей, так и технические дискуссии. Помимо этого, в данном списке уместно обсуждать инфраструктуру ALTQ QoS.

link:{freebsd-platforms-url}[freebsd-platforms]::
_Портирование на не-Intel(R) платформы_
+
Кросс-платформенные вопросы FreeBSD, общее обсуждение и предложения для не-Intel(R) портов FreeBSD. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-policy-url}[freebsd-policy]::
_Правила core team_
+
Это рассылка с малым количеством сообщений, только для чтения, предназначенная для публикации решений FreeBSD Core Team.

link:{freebsd-ports-url}[freebsd-ports]::
_Обсуждения "ports"_
+
Обсуждения, относящиеся к "коллекции портов" FreeBSD, ([.filename]#/usr/ports#), инфраструктуры портов и общих усилий по координации портов. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-ports-bugs-url}[freebsd-ports-bugs]::
_Обсуждение проблем в "ports"_
+
Обсуждения, относящиеся к сообщениям о проблемах для "коллекции портов" FreeBSD ([.filename]#/usr/ports#), предлагаемых портов, или изменений к портам. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-proliant-url}[freebsd-proliant]::
_Работа FreeBSD на серверной платформе HP ProLiant_
+
Этот список используется для обсуждения технических аспектов использования FreeBSD на серверах HP ProLiant, в том числе для обсуждения специфичных для ProLiant драйверов, управляющего ПО, систем конфигурации и обновлений BIOS. В частности, это основное место для обсуждения модулей hpasmd, hpasmcli и hpacucli.

link:{freebsd-python-url}[freebsd-python]::
_Python во FreeBSD_
+
Этот список рассылки посвящён обсуждениям, связанным с улучшением поддержки Python во FreeBSD. Это технический список рассылки. Он предназначен тем, кто работает над портированием во FreeBSD языка Python, модулей сторонних разработчиков для него и Zope. К участию приглашаются также все, кому интересны технические вопросы.

link:{freebsd-questions-url}[freebsd-questions]::
_Вопросы пользователей_
+
Это список рассылки по вопросам о FreeBSD. Вы не должны отправлять вопросы "как сделать" в технические рассылки, если только не уверены, что ваш вопрос чисто технический.

link:{freebsd-ruby-url}[freebsd-ruby]::
_Обсуждения, касающиеся специфики использования Ruby во FreeBSD_
+
Список рассылки по вопросам поддержки Ruby на FreeBSD. Это технический список рассылки, который предназначен для людей, работающих над портами Ruby, над инфраструктурой и библиотеками от третьих сторон.
+
Также к обсуждению приглашаются все, кто заинтересован этой технической дискуссией.

link:{freebsd-scsi-url}[freebsd-scsi]::
_Подсистема SCSI_
+
Это список рассылки для тех, кто работает над подсистемой SCSI для FreeBSD. Это технический список рассылки, предназначенный только для технических обсуждений.

{freebsd-security}::
_Вопросы безопасности_
+
Вопросы безопасности FreeBSD (DES, Kerberos, известные проблемы безопасности и исправления, и т.п.). Это технический список рассылки, предназначенный только для технических обсуждений. Обратите внимание, что это не рассылка вопросов-и-ответов, но дополнения в FAQ (И вопрос И ответ) приветствуются.

{freebsd-security-notifications}::
_Уведомления безопасности_
+
Уведомления о проблемах безопасности FreeBSD и исправления. Эта рассылка не предназначена для обсуждений. Для обсуждения предназначена рассылка FreeBSD-security.

link:{freebsd-small-url}[freebsd-small]::
_Использование FreeBSD во встроенных приложениях_
+
В этой рассылке обсуждаются темы, связанные с необычно малыми и встроенными установками FreeBSD. Это технический список рассылки, предназначенный только для технических обсуждений.
+

[NOTE]
====
Этот список рассылки устарел; следует использовать link:{freebsd-embedded-url}[freebsd-embedded].
====

{freebsd-stable}::
_Обсуждения, касающиеся использования FreeBSD-STABLE_
+
Этот список рассылки предназначен для пользователей FreeBSD-STABLE. Он включает предупреждения о новых возможностях, добавляемых в -STABLE, и влияющих на пользователей, и инструкции по действиям, которые необходимы для поддержки системы в состоянии -STABLE. Всякий, использующий "STABLE", должен подписаться на эту рассылку. Это технический список рассылки, предназначенный только для технических обсуждений.

link:{freebsd-standards-url}[freebsd-standards]::
_Соответствие C99 и POSIX_
+
Это форум для технических обсуждений, относящихся к соответствию FreeBSD стандартам C99 и POSIX.

link:{freebsd-toolchain-url}[freebsd-toolchain]::
_Поддержка встроенных инструментальных средств FreeBSD_
+
Список рассылки для технических дискуссий, относящихся к поддержке инструментальных средств, поставляемых с FreeBSD. Сюда включено состояние Clang и GCC, а также части программного обеспечения, такого как ассемблеры, компоновщики и отладчики.

link:{freebsd-usb-url}[freebsd-usb]::
_Обсуждение поддержки USB в FreeBSD_
+
Это форум для технических обсуждений, относящихся к поддержке в FreeBSD устройств с интерфейсом USB.

link:{freebsd-user-groups-url}[freebsd-user-groups]::
_Список координации групп пользователей_
+
Этот список рассылки предназначен для обсуждения вопросов координаторами каждой группы пользователей и назначенным членом Core Team. Обсуждения в этой рассылке ограничены темой встреч и координацией проектов, относящихся к группам пользователей.

link:{freebsd-vendors-url}[freebsd-vendors]::
_Поставщики_
+
Обсуждения, относящиеся к координации между FreeBSD Project и поставщиками программного и аппаратного обеспечения для FreeBSD.

link:{freebsd-virtualization-url}[freebsd-virtualization]::
_Обсуждение различных техник виртуализации, поддерживаемых FreeBSD_
+
Список рассылки, который предназначен для обсуждений различных техник виртуализации, поддерживаемых FreeBSD. С одной стороны фокус сосредоточен на реализации базовой функциональности, также, как и на добавлении новых возможностей. С другой стороны, пользователи получают возможность обратиться за помощью в случае возникновения проблем или обсудить их конкретные варианты использования.

link:{freebsd-wip-status-url}[freebsd-wip-status]::
_Статус начатых работ (Work-In-Progress) во FreeBSD_
+
Этот список рассылки может быть использован для анонсов начала и прогресса вашей работы над FreeBSD. Сообщения модерируются. Предполагается, что сообщение посылается ("To:") в тематический список рассылки FreeBSD, а в этот список отправляется копия ("BCC:"). Таким образом ваша работа может обсуждаться в тематическом списке рассылки, так как в этом списке дискуссии не разрешены.
+
Выборочный обзор сообщений из этого списка рассылки может публиковаться на сайте FreeBSD как часть Status Reports .
+
Если вам нужны подходящие примеры сообщений, загляните в архивы рассылки или на страницу Status Reports.

link:{freebsd-wireless-url}[freebsd-wireless]::
_Обсуждение разработки стека 802.11, утилит, драйверов устройств_
+
Список рассылки FreeBSD-wireless предназначен для обсуждения разработки стека 802.11 (sys/net80211), утилит и драйверов устройств. Сообщения о проблемах и новых функциональных возможностях также направляются в эту рассылку.

link:{freebsd-xen-url}[freebsd-xen]::
_Обсуждение портирования FreeBSD на Xen(TM) - реализация и использование_
+
Список рассылки, предназначенный для дискуссий на тему портирования FreeBSD на Xen(TM). Ожидаемый объем сообщений довольно невелик, поэтому эта рассылка объединяет как технические обсуждения реализации и деталей дизайна, так и административные вопросы развертывания.

[[eresources-mailfiltering]]
=== Фильтрация списков рассылки

Списки рассылки FreeBSD фильтруются различными способами для предотвращения распространения спама, вирусов, и другой нежелательной почты. Действия по фильтрации, описанные в этом разделе, не включают всех используемых для фильтрации списков рассылки проекта действий.

Только определенные типы вложений разрешены в списках рассылки. Все вложения с типами MIME содержимого, не входящие в список ниже, будут вырезаться перед тем, как письмо будет отправлено в список рассылки.

* application/octet-stream
* application/pdf
* application/pgp-signature
* application/x-pkcs7-signature
* message/rfc822
* multipart/alternative
* multipart/related
* multipart/signed
* text/html
* text/plain
* text/x-diff
* text/x-patch

[NOTE]
====
Некоторые из списков рассылки могут пропускать вложения других типов MIME, но список выше применим к большинству рассылок.
====

Если письмо содержит как HTML, так и только текстовую версию, версия HTML будет удалена. Если письмо содержит только HTML версию, она будет конвертирована в простой текст.

[[eresources-news]]
== Новостные группы Usenet

В дополнение к двум относящимся к FreeBSD группам новостей, существуют множество других, где обсуждается FreeBSD или куда помещается другая информация, относящаяся к пользователям FreeBSD. http://minnie.tuhs.org/BSD-info/bsdnews_search.html[Архивы с поиском по ключевому слову] доступны для некоторых из этих новостных групп благодаря Warren Toomey mailto:wkt@cs.adfa.edu.au[wkt@cs.adfa.edu.au].

=== Относящиеся к BSD новостные группы

* link:news:comp.unix.bsd.freebsd.announce[comp.unix.bsd.freebsd.announce]
* link:news:comp.unix.bsd.freebsd.misc[comp.unix.bsd.freebsd.misc]
* link:news:de.comp.os.unix.bsd[de.comp.os.unix.bsd] (German)
* link:news:fr.comp.os.bsd[fr.comp.os.bsd] (French)
* link:news:it.comp.os.freebsd[it.comp.os.freebsd] (Italian)
* link:news:tw.bbs.comp.386bsd[tw.bbs.comp.386bsd] (Traditional Chinese)

=== Другие интересные UNIX(R) новостные группы

* link:news:comp.unix[comp.unix]
* link:news:comp.unix.questions[comp.unix.questions]
* link:news:comp.unix.admin[comp.unix.admin]
* link:news:comp.unix.programmer[comp.unix.programmer]
* link:news:comp.unix.shell[comp.unix.shell]
* link:news:comp.unix.user-friendly[comp.unix.user-friendly]
* link:news:comp.security.unix[comp.security.unix]
* link:news:comp.sources.unix[comp.sources.unix]
* link:news:comp.unix.advocacy[comp.unix.advocacy]
* link:news:comp.unix.misc[comp.unix.misc]
* link:news:comp.bugs.4bsd[comp.bugs.4bsd]
* link:news:comp.bugs.4bsd.ucb-fixes[comp.bugs.4bsd.ucb-fixes]
* link:news:comp.unix.bsd[comp.unix.bsd]

=== X Window System

* link:news:comp.windows.x.i386unix[comp.windows.x.i386unix]
* link:news:comp.windows.x[comp.windows.x]
* link:news:comp.windows.x.apps[comp.windows.x.apps]
* link:news:comp.windows.x.announce[comp.windows.x.announce]
* link:news:comp.windows.x.intrinsics[comp.windows.x.intrinsics]
* link:news:comp.windows.x.motif[comp.windows.x.motif]
* link:news:comp.windows.x.pex[comp.windows.x.pex]
* link:news:comp.emulators.ms-windows.wine[comp.emulators.ms-windows.wine]

[[eresources-web]]
== Серверы World Wide Web

<<central-mirrors, {central}>>, <<armenia-mirrors, {mirrors-armenia}>>, <<australia-mirrors, {mirrors-australia}>>, <<austria-mirrors, {mirrors-austria}>>, <<czech-republic-mirrors, {mirrors-czech}>>, <<denmark-mirrors, {mirrors-denmark}>>, <<finland-mirrors, {mirrors-finland}>>, <<france-mirrors, {mirrors-france}>>, <<germany-mirrors, {mirrors-germany}>>, <<hong-kong-mirrors, {mirrors-hongkong}>>, <<ireland-mirrors, {mirrors-ireland}>>, <<japan-mirrors, {mirrors-japan}>>, <<latvia-mirrors, {mirrors-latvia}>>, <<lithuania-mirrors, {mirrors-lithuania}>>, <<netherlands-mirrors, {mirrors-netherlands}>>, <<norway-mirrors, {mirrors-norway}>>, <<russia-mirrors, {mirrors-russia}>>, <<slovenia-mirrors, {mirrors-slovenia}>>, <<south-africa-mirrors, {mirrors-south-africa}>>, <<spain-mirrors, {mirrors-spain}>>, <<sweden-mirrors, {mirrors-sweden}>>, <<switzerland-mirrors, {mirrors-switzerland}>>, <<taiwan-mirrors, {mirrors-taiwan}>>, <<uk-mirrors, {mirrors-uk}>>, <<usa-mirrors, {mirrors-us}>>.

(as of UTC)

[[central-mirrors]]
*{central}*

* {central-www}

[[armenia-mirrors]]
*{mirrors-armenia}*

* {mirrors-armenia-www-httpv6} (IPv6)

[[australia-mirrors]]
*{mirrors-australia}*

* {mirrors-australia-www-http}
* {mirrors-australia-www2-http}

[[austria-mirrors]]
*{mirrors-austria}*

* {mirrors-armenia-www-httpv6} (IPv6)

[[czech-republic-mirrors]]
*{mirrors-czech}*

* {mirrors-czech-www-httpv6} (IPv6)

[[denmark-mirrors]]
*{mirrors-denmark}*

* {mirrors-denmark-www-httpv6} (IPv6)

[[finland-mirrors]]
*{mirrors-finland}*

* {mirrors-finland-www-http}

[[france-mirrors]]
*{mirrors-france}*

* {mirrors-france-www-http}

[[germany-mirrors]]
*{mirrors-germany}*

* {mirrors-germany-www-http}

[[hong-kong-mirrors]]
*{mirrors-hongkong}*

* {mirrors-hongkong-www}

[[ireland-mirrors]]
*{mirrors-ireland}*

* {mirrors-ireland-www} 

[[japan-mirrors]]
*{mirrors-japan}*

* {mirrors-japan-www-httpv6} (IPv6)

[[latvia-mirrors]]
*{mirrors-latvia}*

* {mirrors-latvia-www} 

[[lithuania-mirrors]]
*{mirrors-lithuania}*

* {mirrors-lithuania-www} 

[[netherlands-mirrors]]
*{mirrors-netherlands}*

* {mirrors-netherlands-www} 

[[norway-mirrors]]
*{mirrors-norway}*

* {mirrors-norway-www} 

[[russia-mirrors]]
*{mirrors-russia}*

* {mirrors-russia-www-httpv6} (IPv6)

[[slovenia-mirrors]]
*{mirrors-slovenia}*

* {mirrors-slovenia-www} 

[[south-africa-mirrors]]
*{mirrors-south-africa}*

* {mirrors-south-africa-www}

[[spain-mirrors]]
*{mirrors-spain}*

* {mirrors-spain-www}
* {mirrors-spain-www2}

[[sweden-mirrors]]
*{mirrors-sweden}*

* {mirrors-sweden-www}

[[switzerland-mirrors]]
*{mirrors-switzerland}*

* {mirrors-switzerland-www-httpv6} (IPv6)
* {mirrors-switzerland-www2-httpv6} (IPv6)

[[taiwan-mirrors]]
*{mirrors-taiwan}*

* {mirrors-taiwan-www}
* {mirrors-taiwan-www2}
* {mirrors-taiwan-www4}
* {mirrors-taiwan-www5-httpv6} (IPv6)

[[uk-mirrors]]
*{mirrors-uk}*

* {mirrors-uk-www}
* {mirrors-uk-www3}

[[usa-mirrors]]
*{mirrors-us}*

* {mirrors-us-www5-httpv6} (IPv6)

[[eresources-web-social]]
=== Форумы, блоги и социальные сети

* Страница http://forums.freebsd.org/[форумов FreeBSD] предоставляет веб форум для технических дискуссий и вопросов о FreeBSD.
* Страница http://planet.freebsdish.org/[Planet FreeBSD] содержит коллекцию ссылок на десятки блогов, ведомых разработчиками FreeBSD. Многие разработчики используют свои блоги для размещения коротких сообщений о своих текущих занятостях, о новых патчах и о прогрессе в своих работах.
* Страница http://www.youtube.com/bsdconferences[Конференций BSD на YouTube] предоставляет коллекцию видеозаписей с Конференций BSD со всего мира. Это прекрасная возможность ознакомиться с презентациями от ключевых разработчиков, освещающих новые работы во FreeBSD.

[[eresources-web-mirrors]]
=== Официальные зеркала

[[eresources-email]]
== Адреса Email

Следующие группы пользователей предоставляют для своих участников почтовые адреса. Приведенные в списке администраторы оставляют за собой право удалить адреса при любом злоупотреблении.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Домен
| Возможности
| Группа пользователей
| Администратор

|ukug.uk.FreeBSD.org
|Только пересылка
|mailto:ukfreebsd@uk.FreeBSD.org[ukfreebsd@uk.FreeBSD.org]
|Lee Johnston mailto:lee@uk.FreeBSD.org[lee@uk.FreeBSD.org]
|===
