# The FreeBSD Korean Documentation Project
# $FreeBSD$
# Original Revision:

SUBDIR =
SUBDIR+= bsdl-gpl
SUBDIR+= contributing
SUBDIR+= explaining-bsd

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
