# $FreeBSD$
# $FreeBSDde: de-www/snapshots/Makefile,v 1.1 2010/04/18 19:37:56 jkois Exp $
# basiert auf: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
