# $Id: Makefile,v 1.2 1998-11-25 22:37:17 motoyuki Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

# DOCS=	announce.sgml notes.sgml errata.sgml
DOCS=	notes.sgml errata.sgml

.include "../../../web.mk"
