# $Id: Makefile,v 1.1 1998-10-21 03:01:36 motoyuki Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

# DOCS=	announce.sgml notes.sgml errata.sgml
DOCS=	errata.sgml

.include "../../../web.mk"
