# $FreeBSD$
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

### Revision checking
REVCHECK=	yes

.include "${DOC_PREFIX}/share/mk/web.site.mk"
