# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.xml
DOCS+=	credits.xml
DOCS+=	install.xml
DOCS+=	notes.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
