# $FreeBSD: www/en/releases/6.0R/Makefile,v 1.2 2005/06/10 14:23:55 kensmith Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	todo.sgml schedule.sgml approvals.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
