# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.xml \
	schedule.xml \
	todo.xml

DATA=	docbook.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
