# $Id: Makefile,v 1.34 1999-02-06 20:20:16 dillon Exp $

.NOTPARALLEL:

SGMLOPTS=-links
SRCS= anoncvs.sgml authors.sgml backups.sgml basics.sgml bibliography.sgml
SRCS+= boothelp.sgml booting.sgml contrib.sgml crypt.sgml ctm.sgml current.sgml
SRCS+= cvsup.sgml cyclades.sgml development.sgml dialup.sgml dialout.sgml
SRCS+= disks.sgml diskless.sgml dma.sgml eresources.sgml esdi.sgml 
SRCS+= firewalls.sgml german.sgml glossary.sgml goals.sgml
SRCS+= handbook.sgml history.sgml hw.sgml install.sgml isdn.sgml 
SRCS+= kerberos.sgml kernelconfig.sgml kerneldebug.sgml kernelopts.sgml
SRCS+= lists.sgml mail.sgml makeworld.sgml memoryuse.sgml vm.sgml
SRCS+= mirrors.sgml nfs.sgml nutshell.sgml pgpkeys.sgml policies.sgml
SRCS+= porting.sgml ports.sgml ppp.sgml printing.sgml 
SRCS+= quotas.sgml relnotes.sgml routing.sgml russian.sgml
SRCS+= serial.sgml scsi.sgml scsihd.sgml
SRCS+= sections.sgml sio.sgml skey.sgml slipc.sgml 
SRCS+= slips.sgml stable.sgml submitters.sgml synching.sgml 
SRCS+= term.sgml userppp.sgml uart.sgml linuxemu.sgml

.include <bsd.sgml.mk>
