.if exists(../../Makefile.conf)
.include "../../Makefile.conf"
.endif
.if exists(../../Makefile.inc)
.include "../../Makefile.inc"
.endif

DOCS!=		cat multimedia.sgml.created
DATA=		multimedia.xml

WEBDIR=		multimedia

WEB_PREFIX:=	${WEB_PREFIX}/../

.include "${WEB_PREFIX}/share/mk/web.site.mk"
