.if exists(../../Makefile.conf)
.include "../../Makefile.conf"
.endif
.if exists(../../Makefile.inc)
.include "../../Makefile.inc"
.endif

DOCS!=		cat multimedia.sgml.created
DATA=		multimedia.xml

WEBDIR=		multimedia

DOC_PREFIX:=	${DOC_PREFIX}/../

.include "${DOC_PREFIX}/share/mk/web.site.mk"
