---
title: "La red FreeBSD.org"
sidenav: docs
---

= La red FreeBSD.org

Esta página describe, para aquellos con cuentas de acceso en la red FreeBSD.org, las máquinas y recursos actualmente disponibles y el tipo de tarea que realiza cada una de ellas.

== Todos los nombres de máquinas en el dominio FreeBSD.org

[cols=",,,",options="header",]
|===
|Máquina |S.O. |Objetivo |Administrador(es)
|builder |4.0-current |Creación de packages -current |Equipo de ports
|beast |4.0-current |Máquina Alpha para tests FreeBSD/alpha |jkh
|bento |3.0-stable |Creación de packages 3.0-stable |Equipo de ports
|freefall |3-stable |CVS main repository |committers
|hub |3-stable |Servicios Mail & WWW |post/webmaster
|node82-89 |3-stable |Cluster creación de ports |Equipo de ports
|===

== Configuraciones Hardware

[cols="10%,10%,80%",options="header",]
|===
|Máquina |Tipo |Hardware
|builder |Intel x86 |400Mhz Pentium II, 128MB mem, NCR 53c875, 9GB IBM Disco SCSI, Winbond 100bTX NIC.
|beast |Aspen Durango |500MHz 21164A en DEC PCI64 MB, 128MB mem, controladora NCR 53c875 SCSI , discos 2x4GB SCSI WIDE (uno NetBSD/alpha, uno FreeBSD/alpha), DEC 21140 NIC.
|bento |Intel x86 MP |2x300MHz Pentium II, 128MB mem, controladora AHC 2940 PCI SCSI, discos 5x4GB SCSI WIDE, Intel EtherExpress Pro 10/100B NIC.
|freefall |Intel x86 |400MHz Pentium II, 256MB mem, controladora AHA2940U2W PCI SCSI , discos 2x4GB SCSI WIDE y 3x9GB SCSI U2W, Intel EtherExpress Pro 10/100B NIC.
|hub |Intel x86 |400MHz Pentium II, 256MB mem, AHC 2940 PCI SCSI controller, 3x4GB SCSI WIDE drives, HP 6020i CDR, Intel EtherExpress Pro 10/100B NIC.
|node82-89 |AMD x86 |300MHz AMD K6/2, 64MB mem, disco 3GB IDE, Intel EtherExpress Pro 10/100B NIC.
|===

Como regla general, todas las máquinas están conectadas a 100Mbits a la red FreeBSD (switch de 100Mbit), a no ser que por alguna razón determinada, se deba conectar a 10Mbits.

== Políticas Administrativas

Si la máquina en cuestión es administrada por alguna persona determinada, por favor, pregúntale primero a ellos sobre temas administrativos, incluyendo cambios en las cuentas de usuario o en los sistemas de ficheros.

Todas las nuevas cuentas deben ser aceptadas por el equipo de administradores, admins@freebsd.org y solo se dan a desarrolladores de FreeBSD, ya sea en la documentación, ports o código fuente del sistema. La única excepción a esta regla es la máquina de pruebas kickme.freebsd.org, para la cual se podrán conceder cuentas de acceso a desarrolladores no pertenecientes a FreeBSD, pero que requieran de acceso a un sistema FreeBSD para temas verdaderamente experimentales o muy específicos. Las cuentas no son concedidas al "público en general", así que por favor, no preguntes. Gracias.

Jordan Hubbard +
jkh@freebsd.org

link:..[FreeBSD Internal Home]
