---
title: "Galería de fotos"
sidenav: docs
---

= Galería de fotos

== http://www.freebsd.org/~nik/Oxford/index.html[Oxford (UK) FreeBSD meeting, Noviembre 1998]

Fotos y texto por mailto:nik@freebsd.org[Nik]. Organizado por Paul Richards.

== Dutch FreeBSD meeting, Octubre 1998

Fotos por http://www.freebsd.org/~jkh/holland/[Jordan] y http://www.tcja.nl/hackersparty/[Wilko]

== http://www.de.freebsd.org/de/gif/hamburg-1998-06-20/index.html[BSD Social Event Hamburg, Junio 1998]

Aled Morris, Andre Oppermann, Andreas Klemm, Andrew Gordon, Christoph Badura, Dirk Meyer, Frank Nobis, Harald Klatte, Joerg Wunsch, Jonathan Laventhol, Lars Gerhard Kuehl, Martin Cracauer, Stefan Bethke, Stefan Esser, Stefan Huerter, Stefan Zehl, Stephan Forth, Thomas Gellekum

== http://www.lemis.com/grog/auug98.html[AUUG Spring conference, Sydney, Septiembre 1998]

Richard Stallman, Peter Wemm, Mark White, Andrew McRae, Greg Rose, muchos no identificados.

== http://www.freebsd.org/~grog/usenix.html[Summer 1998 USENIX, Nueva Orleans]

Branson, David Greenman, David O'Brien, Greg Lehey, Guido van Rooij, John Polstra, Jonathan Bresler, Jordan Hubbard, Justin Gibbs, Luigi Rizzo, Mark Murray, Mike Smith, Monique van Rooij, Ollivier Robert, Philippe Regnauld, Poul-Henning Kamp, Sharon, Steve Mann

== http://www.de.freebsd.org/de/gif/aachen-19950902/[FreeBSD Social Event Aachen, 1995]

Aled Morris, Christoph Kukulies, Guido van Rooij, Jonathan Leventhol, Jörg Wunsch, Martin Welk, Michael Reifenberger, Patrick Hausen, Paul Richard, Paul Richards, Poul-Henning Kamp, René de Vries, Stefan Esser, Ulf Kieber, Wilko Bulte

== http://www.freebsd.org/~jhs/freebsd/people.html[FreeBSD People]

Aled Morris, Andrey Chernov, Christoph Kukulies, Gary Jennejohn, Gary Palmer, Guido Van Rooij, Guy Helmer, Hellmuth Michaelis, James Robinson, Joerg Wunsch, John Fieber, Jon Loeliger, Jonathan Leventhol, Jordan Hubbard, Julian Stacey, Mark Murray, Martin Welk, Michael Reifenberger, Mike Smith, Ollivier Robert, Patrick Hausen, Paul Richards, Paul Traina, Poul-Henning Kamp, Rene de Vries, Stefan Esser, Thomas Gellekum, Timo Rinne, Ulf Kieber, Wilko Bulte, Wolfram Schneider

link:..[FreeBSD Internal Home]
