# $FreeBSD: www/ja/java/dists/Makefile,v 1.4 2000/11/07 05:13:20 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	10.sgml
DOCS+=	11.sgml
DOCS+=	12.sgml
DOCS+=	13.sgml
DOCS+=	index.sgml

### Revision checking
REVCHECK= YES

.include "${WEB_PREFIX}/share/mk/web.site.mk"
