# $FreeBSD: www/en/java/dists/Makefile,v 1.3 2000/03/02 15:55:29 phantom Exp $

# The FreeBSD Japanese Documentation Project
# Original revision: 1.3

#DOCS =	10.sgml
DOCS=	11.sgml
DOCS+=	12.sgml
DOCS+=	13.sgml
DOCS+=	index.sgml

.include "../../web.mk"
