# $FreeBSD$
# $FreeBSDde: de-www/ports/Makefile.inc0,v 1.1 2007/03/31 14:27:06 jkois Exp $
# basiert auf: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif
.if exists(Makefile.inc)
.include "Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif

.include "${DOC_PREFIX}/share/mk/web.site.mk"
