#!/bin/sh
# Copyright (c) June 1998 Wolfram Schneider <wosch@FreeBSD.ORG>, Berlin.
#
# packages - create a sorted list of precompiled packages which
#            are available at the FreeBSD FTP Server.
#
# $FreeBSD$
# $FreeBSDde: de-www/ports/packages,v 1.1 2007/03/31 14:27:06 jkois Exp $
# basiert auf: 1.10


PATH=/bin:/usr/bin:/usr/local/bin; export PATH

url="http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/"

temp=_lynx$$

if lynx -source "$url" > $temp || ( sleep 300; lynx -source "$url" > $temp ) || ( sleep 300; lynx -source "$url" > $temp )
then
    perl -ne 'print $1, "\n" if m%href="([^"]+)"%oi' < $temp |
    perl -npe  's%.*/%%' | sort | grep -v '^\.\.$'
    rm -f $temp
else
	rm -f $temp
	exit 1
fi
