#
# $FreeBSD$
#
# Article: Contributing to FreeBSD
#
# Original revision: 1.6

DOC?= article
WITH_ARTICLE_TOC?= YES

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
