---
add_single_page_link: 'true'
authors:
  - 
    author: 'Alfonso S. Siciliano'
bookOrder: 50
copyright: '2025 The FreeBSD Foundation'
description: 'Технологии доступности в FreeBSD'
next: books/accessibility/preface
params:
  path: /books/accessibility/
showBookMenu: 'true'
tags: ["Accessibility", "Documentation", "FreeBSD", "Index"]
title: 'Руководство по доступности FreeBSD'
trademarks: ["freebsd"]
weight: 10
---

= Руководство по доступности FreeBSD
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/accessibility/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

// Split HTML view, sync with book.adoc
[.abstract-title]
Аннотация

Добро пожаловать в Руководство по доступности. Эта книга охватывает технологии доступности в FreeBSD.

Доступность — это непрерывный процесс, а не фиксированная цель. Поэтому данное руководство является живым документом и постоянно развивается. Вклад, предложения и обратная связь крайне приветствуются. Если вы заинтересованы в участии, пожалуйста, свяжитесь с нами через https://lists.freebsd.org/subscription/freebsd-accessibility[список рассылки по доступности FreeBSD].

Вы можете загрузить эту книгу в различных форматах и с опциями сжатия с сервера загрузок FreeBSD или одного из его многочисленных зеркальных сайтов.

'''
