# $Id: Makefile,v 1.1 1998-08-04 11:15:50 wosch Exp $

DOCSUBDIR=	FAQ
FORMATS?=	"html roff"
SGMLOPTS=	-links -hdr ${.CURDIR}/doc.hdr -ftr ${.CURDIR}/doc.ftr -e EUC-JP


WEBBASE=	/data

.include "../web.mk"

