---
title: Πως να χρησιμοποιείτε με επιτυχία την λίστα ηλεκτρονικού ταχυδρομείου FreeBSD-questions
authors:
  - author: Greg Lehey
    email: grog@FreeBSD.org
releaseinfo: "$FreeBSD$" 
trademarks: ["freebsd", "microsoft", "opengroup", "qualcomm", "general"]
---

= Πως να χρησιμοποιείτε με επιτυχία την λίστα ηλεκτρονικού ταχυδρομείου FreeBSD-questions
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:toc-title: Πίνακας Περιεχομένων
:table-caption: Πίνακας
:figure-caption: Σχήμα
:example-caption: Παράδειγμα

include::shared/el/urls.adoc[]
include::shared/el/mailing-lists.adoc[]

[.abstract-title]
Περίληψη

Αυτό το κείμενο παρέχει χρήσιμες πληροφορίες για όσους προσπαθούν να προετοιμάσουν ένα γράμμα για την λίστα ταχυδρομείου FreeBSD-questions. Δίνονται συμβουλές και οδηγίες που θα μεγιστοποιήσουν την πιθανότητα ο αναγνώστης να πάρει χρήσιμες απαντήσεις.

Αυτό το κείμενο (ΣΤΜ: η αγγλική έκδοση) στέλνεται τακτικά στην ίδια τη λίστα FreeBSD-questions.

'''

toc::[]

== Εισαγωγή

Η `FreeBSD-questions` είναι μια ταχυδρομική λίστα που συντηρείται από την ομάδα ανάπτυξης του FreeBSD για να βρίσκουν σε αυτή βοήθεια όσοι έχουν απορίες σχετικά με την χρήση του FreeBSD. Μια άλλη λίστα, η `FreeBSD-hackers`, είναι για πιο προχωρημένες ερωτήσεις, όπως για παράδειγμα συζητήσεις για μελλοντικές εργασίες ανάπτυξης.

[NOTE]
====
Ο όρος "hacker" δεν έχει καμία απολύτως σχέση με την εισβολή στους υπολογιστές άλλων ανθρώπων. Ο σωστός όρος για τέτοιου είδους ενέργειες είναι "cracker", αλλά τα δημοφιλή μέσα ενημέρωσης δεν το έχουν ανακαλύψει ακόμα. Οι FreeBSD hackers δεν εγκρίνουν την παραβίαση της ασφάλειας των υπολογιστών (cracking), και δεν έχουν καμία σχέση με τέτοιου είδους ενέργειες. Για να πιο λεπτομερή περιγραφή των hackers, δείτε το http://www.catb.org/~esr/faqs/hacker-howto.html[How to Become A Hacker] του Eric Raymond.
====

Αυτό είναι ένα τακτικό μήνυμα του οποίου σκοπός είναι να βοηθήσει τόσο αυτούς που αναζητούν βοήθεια από την FreeBSD-questions (τους "καινούριους") όσο και αυτούς που απαντάνε τις ερωτήσεις (τους "hackers").

Αναπόφευκτα υπάρχει μια κόντρα, που οφείλεται στην διαφορετική οπτική γωνία που έχει η κάθε ομάδα. Οι καινούριοι κατηγορούν τους hackers ότι είναι εγωιστές, κολλημένοι, και ότι δεν βοηθάνε, ενώ οι hackers κατηγορούν τους καινούριους ότι είναι χαζοί, ανίκανοι να διαβάσουν απλά Αγγλικά, κι ότι περιμένουν τα πάντα να τους δίνονται σε ένα ασημένιο δίσκο. Γεγονός είναι, βέβαια, ότι μια δόση αλήθειας υπάρχει και στις δυο αυτές απόψεις, αλλά κατά κύριο λόγο αυτές οι απόψεις οφείλονται σε αισθήματα οργής.

Με αυτό το κείμενο, θα ήθελα να κάνω κάτι να απαλύνω κάπως αυτή την οργή, και να βοηθήσω όσο μπορώ όλους να χρησιμοποιούν με τα καλύτερα δυνατά αποτελέσματα τη λίστα FreeBSD-questions. Παρακάτω περιγράφω πως να στείλει κάποιος μια ερώτηση. Μετά θα δούμε και τρόπους για να δίνονται απαντήσεις.

== Πως να γραφτείτε στην FreeBSD-questions

Η FreeBSD-questions είναι μια λίστα ηλεκτρονικού ταχυδρομείου, οπότε χρειάζεστε πρόσβαση σε κάποια υπηρεσία ηλεκτρονικού ταχυδρομείου. Για να γραφτείτε στη λίστα, επισκεφθείτε με το φυλλομετρητή σας τη {freebsd-questions}. Στο τμήμα "Subscribing to freebsd-questions" συμπληρώστε το πεδίο "Your email address" κι όποια άλλα προαιρετικά πεδία θέλετε.

[NOTE]
====
Τα πεδία κωδικού παρέχουν μέτρια ασφάλεια, αλλά οι κωδικόί αυτός θα εμποδίσουν τον περισσότερο κόσμο από το να κάνει αλλαγές στη συνδρομή σας. _Μη χρησιμοποιήσετε όμως κάποιο πολύτιμο κωδικό σε αυτό το πεδίο, γιατί θα σας έρχεται περιοδικά μια υπενθύμιση του κωδικού σε ένα απλό, μη κρυπτογραφημένο μήνυμα ηλεκτρονικού ταχυδρομείου._
====

Λίγο μετά θα λάβετε ένα μήνυμα επιβεβαίωσης της εγγραφής από το mailman. Ακολουθήστε τις οδηγίες του μηνύματος για να ενεργοποιηθεί η συνδρομή σας.

Τέλος, μόλις λάβετε το μήνυμα καλωσορίσματος από το mailman, που περιγράφει τη λίστα και τον κωδικό της συνδρομής σας, __κρατήστε ένα αντίγραφο__. Αν θελήσετε ποτέ να ακυρώσετε την εγγραφή σας στη λίστα, θα χρειαστείτε τις πληροφορίες του μηνύματος. Δείτε και τις επόμενες παραγράφους για περισσότερες λεπτομέρειες.

== Πως να διαγραφείτε από την FreeBSD-questions

Όταν γραφτήκατε στην FreeBSD-questions, πήρατε ένα μήνυμα καλωσορίσματος από το mailto:mailman[mailman]. Σε αυτό το μήνυμα, ανάμεσα σε άλλα πράγματα, εξηγεί και πως μπορείτε να διαγραφείτε από τη λίστα. Ορίστε ένα τυπικό μήνυμα:

....
Welcome to the freebsd-questions@freebsd.org mailing list!

To post to this list, send your email to:

  freebsd-questions@freebsd.org

General information about the mailing list is at:

  http://lists.freebsd.org/mailman/listinfo/freebsd-questions

If you ever want to unsubscribe or change your options (eg, switch to
or from digest mode, change your password, etc.), visit your
subscription page at:

http://lists.freebsd.org/mailman/options/freebsd-questions/grog%40lemsi.de

You can also make such adjustments via email by sending a message to:

  freebsd-questions-request@freebsd.org

with the word `help' in the subject or body (don't include the
quotes), and you will get back a message with instructions.

You must know your password to change your options (including changing
the password, itself) or to unsubscribe.  It is:

  12345

Normally, Mailman will remind you of your freebsd.org mailing list
passwords once every month, although you can disable this if you
prefer.  This reminder will also include instructions on how to
unsubscribe or change your account options.  There is also a button on
your options page that will email your current password to you.
....

Χρησιμοποιώντας τη διεύθυνση URL που περιέχει το μήνυμα καλωσορίσματος που λάβατε (με τίτλο "Welcome") μπορείτε να επισκεφθείτε τη "Σελίδα προσωπικών ρυθμίσεων" και να αιτηθείτε τη διαγραφή σας ("Unsubscribe") από τη λίστα FreeBSD-questions.

Μόλις ζητήσετε τη διαγραφή σας το mailman θα σας στείλει ένα μήνυμα επιβεβαίωσης της διαγραφής. Ακολουθήστε τις οδηγίες του μηνύματος για να ολοκληρώσετε τη διαδικασία διαγραφής.

Αν τα έχετε κάνει όλα αυτά και ακόμα δεν μπορείτε να καταλάβετε τι συμβαίνει, στείλτε ένα μήνυμα στη διεύθυνση mailto:Postmaster@FreeBSD.org[Postmaster@FreeBSD.org], και αυτός θα σας βοηθήσει να βρείτε μια άκρη. _Μην_ στείλετε κάποιο μήνυμα στην FreeBSD-questions: δεν μπορούν να σας βοηθήσουν.

== Που να στείλω την ερώτησή μου; Στην `-questions` ή στην `-hackers`;

Δύο είναι οι λίστες που μπορεί κάποιος να κάνει ερωτήσεις γενικού περιεχομένου σχετικά με το FreeBSD, η `FreeBSD-questions` και η `FreeBSD-hackers`. Σε κάποιες περιπτώσεις, δεν είναι απολύτως ξεκάθαρο σε ποια λίστα πρέπει να ρωτήσετε. Τα παρακάτω κριτήρια θα σας βοηθήσουν να αποφασίσετε στο 99% των περιπτώσεων, όμως:

. Αν η ερώτηση είναι γενικού περιεχομένου, ρωτήστε στην `FreeBSD-questions`. Παραδείγματα μπορεί να είναι ερωτήσεις σχετικά με την εγκατάσταση του FreeBSD ή την χρήση ενός συγκεκριμένου UNIX(R) εργαλείου.
. Αν νομίζετε ότι η ερώτηση έχει σχέση με κάποιο bug, αλλά δεν είστε σίγουροι, ή δεν ξέρετε πως να το ψάξετε περισσότερο, στείλτε το μήνυμα στην `FreeBSD-questions`.
. Αν η ερώτηση έχει σχέση με κάποιο bug, και είστε _σίγουροι_ ότι είναι bug (για παράδειγμα, μπορείτε να δείξετε το μέρος στον πηγαίο κώδικα που εμφανίζεται, ή ίσως έχετε και κάποια διόρθωση έτοιμη), τότε στείλτε το μήνυμά σας στην `FreeBSD-hackers`.
. Αν η ερώτηση έχει σχέση με βελτιώσεις στο FreeBSD, και μπορείτε να κάνετε προτάσεις σχετικά με την υλοποίησή τους, στείλτε το μήνυμα στην `FreeBSD-hackers`.

Υπάρχουν επίσης κι άλλες λίστες ηλεκτρονικού ταχυδρομείου, για παράδειγμα η `FreeBSD-isp`, η οποία ασχολείται με τα ενδιαφέροντα των ISP (Παροχείς Υπηρεσιών Internet-Internet Service Providers) που τρέχουν FreeBSD. Αν τυχαίνει να παρέχετε υπηρεσίες Internet, αυτό δεν σημαίνει πως αυτόματα πρέπει να στέλνετε όλες σας τις ερωτήσεις στην `FreeBSD-isp`. Τα κριτήρια που αναφέραμε παραπάνω πάλι ισχύουν, και μάλλον σας συμφέρει να τα χρησιμοποιήσετε, αφού έτσι είναι πιο πιθανόν να πάρετε καλύτερα αποτελέσματα.

== Πριν στείλετε μια ερώτηση

Μπορείτε (και πρέπει) να κάνετε κάποια πράγματα από μόνοι σας πριν στείλετε μια ερώτηση σε κάποια από τις λίστες ηλεκτρονικού ταχυδρομείου.

* Προσπαθείστε να λύσετε το πρόβλημα μόνοι σας. Αν στείλετε μια ερώτηση η οποία δείχνει ότι έχετε προσπαθήσει ήδη να λύσετε το πρόβλημα, είναι σχεδόν σίγουρο ότι η ερώτησή σας θα κινήσει το ενδιαφέρον περισσότερο ενδιαφέρον. Η προσπάθεια να λύσετε το πρόβλημα μόνοι σας έχει κι άλλα καλά αποτελέσματα: θα βελτιώσει την κατανόηση που έχετε για τον τρόπο που δουλεύει το FreeBSD, οπότε ύστερα θα μπορείτε ακόμη και να χρησιμοποιήσετε τη γνώση που αποκτήσατε για να βοηθήσετε άλλους, απαντώντας τις ερωτήσεις τους σε κάποια από τις λίστες.
* Διαβάστε τα manual pages, και την τεκμηρίωση του FreeBSD (είτε το αντίγραφο που διανέμεται μαζί με τις εκδόσεις του FreeBSD κι εγκαθίσταται στον κατάλογο [.filename]#/usr/doc# ή μέσω WWW στη διεύθυνση http://www.FreeBSD.org[http://www.FreeBSD.org]), ειδικά το link:{handbook}[Εγχειρίδιο του FreeBSD] και τη link:{faq}[λίστα συχνών ερωτήσεων].
* Περιηγηθείτε ή αναζητήστε σχετικά θέματα στα αρχεία της λίστας, για να δείτε αν η ερώτησή σας ή κάποια παρόμοια έχει ήδη εμφανιστεί ή έχει απαντηθεί στο παρελθόν. Μπορείτε να βρείτε τα αρχεία της λίστας στη διεύθυνση http://www.FreeBSD.org/mail[http://www.FreeBSD.org/mail] και να αναζητήσετε παλιά θέματα στη διεύθυνση http://www.FreeBSD.org/search/#mailinglists[http://www.FreeBSD.org/search/#mailinglists]. Τέτοιες αναζητήσεις μπορούν να γίνουν και σε άλλους εξυπηρετητές που έχουν το αρχείο της λίστας, π.χ. στη διεύθυνση http://marc.theaimsgroup.com[http://marc.theaimsgroup.com].
* Χρησιμοποιήστε μια μηχανή αναζήτησης, όπως το http://www.google.com[Google] ή το http://www.yahoo.com[Yahoo] για να βρείτε απαντήσεις στις ερωτήσεις σας. Το Google έχει ακόμα και http://www.google.com/bsd[ειδικό τμήμα για τα BSD λειτουργικά συστήματα].

== Πως να στείλετε μια ερώτηση

Όταν στέλνετε μια ερώτηση στην FreeBSD-questions, σκεφτείτε πρώτα τα παρακάτω πράγματα:

* Να θυμάστε πως κανείς δεν πληρώνεται για να απαντήσει μια ερώτηση στην FreeBSD-questions. Απαντούν επειδή οι ίδιοι θέλουν να απαντήσουν. Μπορείτε να επηρεάσετε την θέληση κάποιου να απαντήσει θετικά στέλνοντας μια προσεγμένη ερώτηση και δίνοντας όσο το δυνατόν περισσότερες σχετικές πληροφορίες. Μπορεί να επηρεάσετε αρνητικά την θέληση κάποιου να απαντήσει, στέλνοντας μια ατελή, δύσκολη να διαβαστεί, ή αγενή ερώτηση. Είναι επίσης πολύ πιθανόν να στείλετε ένα μήνυμα στην FreeBSD-questions και να μην πάρετε απάντηση, ακόμα και αν ακολουθήσετε αυτούς τους κανόνες. Είναι όμως ακόμα περισσότερο πιθανό να μην πάρετε μια απάντηση, αν δεν τους ακολουθήσετε. Στο υπόλοιπο αυτού του κειμένου θα δούμε πως θα έχετε τα καλύτερα δυνατά αποτελέσματα από την FreeBSD-questions.
* Δεν διαβάζουν όλα τα μηνύματα όσοι απαντούν στην FreeBSD-questions: κοιτάζουν την γραμμή θέματος (subject) και αποφασίζουν αν τους ενδιαφέρει ή όχι. Προφανώς, σας συμφέρει να έχετε ορίσει ένα θέμα. Θέματα όμως όπως "FreeBSD problem" ή "Help" δεν είναι αρκετά. Αν δεν έχετε βάλει κανένα θέμα, πολλοί ούτε καν που θα κάτσουν να διαβάσουν το μήνυμα. Αν το θέμα είναι κάπως ασαφές και δεν αναφέρει ακριβώς το πρόβλημα, άνθρωποι που μπορούν να απαντήσουν ίσως να μην το διαβάσουν καν.
* Διαμορφώστε το γράμμα σας ώστε να διαβάζεται εύκολα, και ΜΗΝ ΦΩΝΑΖΕΤΕ ΣΑΣ ΠΑΡΑΚΑΛΩ!!!!! Καταλαβαίνουμε ότι πολύς κόσμος δεν έχει για μητρική του γλώσσα τα Αγγλικά, και προσπαθούμε να είμαστε αρκετά ανεκτικοί σε αυτό το θέμα, αλλά είναι πραγματικά ενοχλητικό να προσπαθεί κανείς να διαβάσει ένα μήνυμα γεμάτο ορθογραφικά λάθη ή όταν είναι όλο γραμμένο σε μια γραμμή.
+ 
Μην υποτιμάτε την επίδραση που ένα κακογραμμένο μήνυμα μπορεί να έχει, κι αυτό όχι μόνο στην FreeBSD-questions λίστα. Το μήνυμα σας είναι αυτό που θα δουν οι άλλοι, κι αν είναι κακογραμμένο, με το κείμενο ολόκληρων παραγράφων σε μια γραμμή, ή γεμάτο λάθη, θα δώσει άσχημη εντύπωση στους άλλους για σας.
+ 
Πάρα πολλά κακογραμμένα μηνύματα οφείλονται σε http://www.lemis.com/email.html[ελλατωματικά ή κακορυθμισμένα προγράμματα ηλεκτρονικής αλληλογραφίας]. Τα παρακάτω προγράμματα είναι γνωστό ότι στέλνουν κακογραμμένα μηνύματα χωρίς εσείς να το ξέρετε πως κάτι τέτοιο γίνεται:

** cc:Mail
** Eudora(R)
** exmh
** Microsoft(R) Exchange
** Microsoft(R) Internet Mail
** Microsoft(R) Outlook(R)
** Netscape(R)
+ 
Όπως βλέπετε, τα προγράμματα ηλεκτρονικής αλληλογραφίας στον κόσμο της Microsoft είναι αρκετά συχνά στη λίστα. Όταν είναι δυνατόν, χρησιμοποιήστε ένα πρόγραμμα ηλεκτρονικής αλληλογραφίας που τρέχει σε UNIX(R). Αν είστε υποχρεωμένοι να χρησιμοποιήσετε κάποιο πρόγραμμα ηλεκτρονικής αλληλογραφίας σε Microsoft περιβάλλον, τότε σιγουρευτείτε ότι το έχετε ρυθμίσει σωστά. Προσπαθήστε να μην χρησιμοποιείτε MIME: πολλοί χρησιμοποιούν προγράμματα να διαβάσουν την αλληλογραφία τους που δεν τα πάνε καλά με το MIME.
* Σιγουρευτείτε ότι η ώρα και η ζώνη ώρας είναι σωστά ρυθμισμένες στο σύστημά σας. Αυτό μπορεί να φαίνεται λίγο χαζό, αφού το μήνυμά σας έτσι κι αλλιώς θα φτάσει, αλλά πολλοί από τους ανθρώπους που προσπαθείτε να επικοινωνήσετε μαζί τους παίρνουν αρκετές εκατοντάδες μηνύματα κάθε μέρα. Πολλές φορές ταξινομούν τα εισερχόμενα μηνύματά τους ανάλογα με το θέμα και την ημερομηνία, και αν το μήνυμά σας δεν φτάσει πριν την πρώτη απάντηση, μπορεί να θεωρήσουν ότι δεν το πήραν καν και να μην ασχοληθούν παραπάνω.
* Μην συμπεριλαμβάνετε άσχετες ερωτήσεις στο ίδιο μήνυμα. Πρώτα από όλα, ένα τεράστιο μήνυμα μπορεί να φοβίσει τον κόσμο και να μην ασχοληθούν, και δεύτερον, είναι δύσκολο να πετύχετε να διαβάσουν όλες τις ερωτήσεις όλοι όσοι μπορούν να απαντήσουν.
* Δώστε όσο περισσότερες πληροφορίες γίνεται. Αυτό είναι μια κάπως περίεργη απαίτηση, και πρέπει να αναλύσουμε κάπως τι πληροφορίες χρειάζεται να στείλετε, αλλά για αρχή ας πούμε τα εξής:

** Σχεδόν σε κάθε περίπτωση, είναι σημαντικό να ξέρει κανείς ποια έκδοση του FreeBSD τρέχετε. Ειδικά με το FreeBSD-CURRENT, θα πρέπει να πείτε ακόμα και ποια είναι η ημερομηνία του πηγαίου κώδικα. Όπως και νά 'χει, δεν πρέπει να στέλνετε όμως ερωτήσεις για το -CURRENT στην FreeBSD-questions.
** Για οποιοδήποτε πρόβλημα _μπορεί_ να έχει σχέση με το υλικό του υπολογιστή σας (hardware), πείτε μας και για το υλικό που έχει ο υπολογιστής. Αν έχετε αμφιβολίες, υποθέστε ότι μάλλον έχει σχέση με το υλικό. Τι είδος CPU χρησιμοποιείτε; Πόσο γρήγορη; Τι μητρική; Πόσο μνήμη; Τι περιφερειακά;
+ 
Γενικά πρέπει να χρησιμοποιήσετε και την κρίση σας εδώ, αλλά συνήθως η έξοδος της εντολής man:dmesg[8] μπορεί να αποδειχθεί χρήσιμη, αφού μας λέει όχι μόνο τι υλικό χρησιμοποιείτε, αλλά και ποια έκδοση του FreeBSD τρέχετε.
** Αν βλέπετε κάποια μηνύματα λάθους, μην γράφετε "Βλέπω κάποια μηνύματα λάθους", αλλά γράψτε (για παράδειγμα) "Βλέπω το μήνυμα λάθους 'No route to host'".
** Αν το σύστημα κάνει panic, μην πείτε "Το σύστημά μου έκανε panic", αλλά (για παράδειγμα) "το σύστημά μου έκανε panic με το μήνυμα 'free vnode isn't'".
** Αν έχετε κάποια δυσκολία με την εγκατάσταση του FreeBSD, πείτε μας σίγουρα τι υλικό έχετε. Πιο συγκεκριμένα, είναι σημαντικό να ξέρουμε τα IRQ και τις διευθύνσεις I/O για όλες τις κάρτες που έχετε εγκατεστημένες στο μηχάνημά σας.
** Αν έχετε κάποιο πρόβλημα με το να καταφέρετε το PPP να δουλέψει, περιγράψτε τις ρυθμίσεις σας. Ποια έκδοση του PPP τρέχετε; Πως συνδέεστε και με ποιο τρόπο ελέγχεται η ταυτότητά σας; Έχετε στατική ή δυναμική IP διεύθυνση; Τι μηνύματα παίρνετε στα log αρχεία σας;

* Πολλές από τις πληροφορίες που θέλετε συνήθως να στείλετε, περιλαμβάνονται στην έξοδο προγραμμάτων όπως το man:dmesg[8], ή στα μηνύματα που βλέπετε στην κονσόλα σας, τα οποία τις πιο πολλές φορές σώζονται και στο αρχείο [.filename]#/var/log/messages#. Μην δοκιμάσετε να αντιγράψετε αυτές τις πληροφορίες ξαναγράφοντάς τες. Είναι βαρετό και σχεδόν σίγουρα θα κάνετε κάποιο λάθος. Για να στείλετε τα περιεχόμενα κάποιου log αρχείου, είτε κάντε ένα αντίγραφο του αρχείου και χρησιμοποιήστε κάποιον επεξεργαστή κειμένου να κόψετε όσα κομμάτια δεν είναι σχετικά, ή αντιγράψτε και επικολλήστε ότι έχει σχέση στο μήνυμά σας. Για την έξοδο κάποιου προγράμματος, όπως π.χ. το man:dmesg[8], ανακατευθύνετε την έξοδο σε κάποιο αρχείο και χρησιμοποιήστε αυτό το αρχείο. Για παράδειγμα:
+
[source,bash]
....
% dmesg > /tmp/dmesg.out
....
+ 
Αυτό θα στείλει την έξοδο της εντολής στο αρχείο [.filename]#/tmp/dmesg.out#.
* Αν τα κάνετε όλα αυτά, και πάλι δεν πάρετε κάποια απάντηση μπορεί να υπάρχουν άλλοι λόγοι. Για παράδειγμα, μπορεί το πρόβλημα να είναι τόσο περίπλοκο που κανείς δεν ξέρει την απάντηση, ή μπορεί το άτομο που ξέρει να απαντήσει να μην ήταν διαθέσιμο. Αν δεν πάρετε απάντηση για π.χ. πάνω από μια βδομάδα, μπορεί να βοηθήσει αν ξαναστείλετε το μήνυμα. Πάντως, αν δεν πάρετε απάντηση ούτε την δεύτερη φορά, μάλλον δεν θα βρείτε βοήθεια σε αυτή τη λίστα. Το να στέλνετε το μήνυμα ξανά και ξανά το μόνο που θα έχει σαν αποτέλεσμα θα είναι να μην θέλει κανείς να ασχοληθεί μαζί του.

Για να ανακεφαλαιώσουμε, ας πούμε ότι ξέρετε την απάντηση στην παρακάτω ερώτηση (ναι είναι η ίδια ερώτηση και στις δυο περιπτώσεις). Μπορείτε να διαλέξετε ποια από τις δυο αυτές ερωτήσεις θα προτιμούσατε να απαντήσετε:

.Παράδειγμα 1
[example]
====

....
Subject: HELP!!?!??
I just can't get hits damn silly FereBSD system to
workd, and Im really good at this tsuff, but I have never seen
anythign sho difficult to install, it jst wont work whatever I try
so why don't y9ou guys tell me what I doing wrong.
....
====

.Παράδειγμα 2
[example]
====

....
Subject: Problems installing FreeBSD

I've just got the FreeBSD 2.1.5 CDROM from Walnut Creek, and I'm having a lot
of difficulty installing it.  I have a 66 MHz 486 with 16 MB of
memory and an Adaptec 1540A SCSI board, a 1.2GB Quantum Fireball
disk and a Toshiba 3501XA CDROM drive.  The installation works just
fine, but when I try to reboot the system, I get the message
``Missing Operating System''.
....
====

== Πως να συμπληρώσετε μια ερώτηση

Συχνά θα θέλετε να στείλετε κάποιες παραπάνω πληροφορίες για μια ερώτηση που έχετε κάνει ήδη. Ο καλύτερος τρόπος να το κάνετε αυτό είναι να απαντήσετε στο ίδιο το αρχικό σας μήνυμα. Αυτό έχει τρία πλεονεκτήματα:

. Περιλαμβάνετε και το αρχικό σας μήνυμα, κι έτσι κάποιος που διαβάζει θα ξέρει σε τι αναφέρεστε. Βεβαίως, μην ξεχάσετε να κόψετε ότι δεν είναι απαραίτητο.
. Το κείμενο της γραμμής θέματος παραμένει το ίδιο (θυμηθήκατε να βάλετε κάποιο θέμα, σωστά;). Πολλά προγράμματα ηλεκτρονικής αλληλογραφίας ταξινομούν τα μηνύματα ανάλογα με το θέμα τους. Αυτό βοηθάει τα σχετικά μηνύματα να μένουν μαζί.
. Οι αριθμοί αναφοράς στην επικεφαλίδα του μηνύματος θα δείχνουν στο προηγούμενο γράμμα. Κάποια προγράμματα ηλεκτρονικής αλληλογραφίας, όπως το http://www.mutt.org/[mutt], μπορούν να _ομαδοποιήσουν_ τα μηνύματα, δείχνοντας ακριβώς τι σχέση έχουν το ένα με το άλλο.

== Πως να απαντήσετε μια ερώτηση

Πριν απαντήσετε κάποια ερώτηση στην FreeBSD-questions, σκεφτείτε τα εξής:

. Πολλά πράγματα από αυτά που ισχύουν για τις ερωτήσεις, ισχύουν και για τις απαντήσεις. Διαβάστε τα πρώτα, παραπάνω
. Μήπως κάποιος άλλος έχει απαντήσει στην ερώτηση; Ο πιο εύκολος τρόπος να το ελέγξετε αυτό είναι να ταξινομήσετε τα εισερχόμενα γράμματά σας ανάλογα με το θέμα τους. Έτσι (ας ελπίσουμε) θα δείτε την ερώτηση να ακολουθείται από τις απαντήσεις (όταν αυτές υπάρχουν) όλες μαζί.
+ 
Αν κάποιος άλλος έχει ήδη απαντήσει δεν σημαίνει πως εσείς δεν πρέπει να απαντήσετε κάπως διαφορετικά. Αλλά έχει νόημα να διαβάστε πρώτα όλες τις απαντήσεις.
. Έχετε να προσθέσετε κάτι σε όσα έχουν ήδη γραφτεί; Γενικά, απαντήσεις του στυλ "Ναι, κι εγώ" δεν βοηθάνε και πολύ. Υπάρχουν βέβαια και εξαιρέσεις, όπως όταν, για παράδειγμα, κάποιος περιγράφει ένα πρόβλημα που έχει και δεν ξέρει αν είναι δικό του φταίξιμο ή κάτι δεν πάει καλά είτε με το υλικό είτε με το λογισμικό του. Αν στείλετε ωστόσο ένα "κι εγώ" μήνυμα, φροντίστε τουλάχιστον να έχει όλες τις πληροφορίες που χρειάζονται.
. Είστε σίγουρος ότι καταλαβαίνετε την ερώτηση; Πολύ συχνά, αυτός που ρωτάει έχει μπερδευτεί ή δεν έχει εκφραστεί με αρκετή σαφήνεια. Ακόμα και με την καλύτερη δυνατή γνώση του συστήματος, είναι εύκολο να στείλετε μια απάντηση που δεν απαντά στην ερώτηση. Αυτό δεν βοηθά και πολύ. Θα αφήσετε αυτόν που ρωτάει πιο θυμωμένο και μπερδεμένο από πριν. Αν κανείς άλλος δεν απαντήσει, και δεν είστε ούτε εσείς σίγουρος, μπορείτε πάντα να ζητήσετε πιο πολλές πληροφορίες.
. Είστε σίγουρος ότι η απάντηση σας είναι σωστή; Αν όχι περιμένετε μια μέρα περίπου. Αν κανείς δεν στείλει κάποια καλύτερη απάντηση, μπορείτε να απαντήσετε εσείς, γράφοντας για παράδειγμα "Δεν ξέρω αν αυτό είναι σωστό, αλλά αφού κανείς άλλος δεν έχει απαντήσει, γιατί δεν δοκιμάζεις να αντικαταστήσεις το ATAPI CDROM σου με ένα βάτραχο;".
. Αν δεν υπάρχει κάποιος καλός λόγος για να κάνετε κάτι διαφορετικό, απαντήστε και στον αποστολέα και στην FreeBSD-questions. Πολύς κόσμος στην FreeBSD-questions είναι "παρατηρητές": μαθαίνουν διαβάζοντας τα μηνύματα που στέλνονται σαν απαντήσεις στους άλλους. Αν μεταφέρετε κάποιο μήνυμα γενικού ενδιαφέροντος εκτός λίστας, στερείτε αυτούς τους αναγνώστες από μια πολύτιμη πηγή πληροφοριών. Προσοχή όμως με τις ομαδικές απαντήσεις. Πολύς κόσμος στέλνει απαντήσεις με εκατοντάδες Cc αντίγραφα. Σε αυτή την περίπτωση, κόψτε τις κατάλληλες Cc διευθύνσεις.
. Συμπεριλάβετε το σχετικό κείμενο από το αρχικό μήνυμα. Αφαιρέστε ότι δεν χρειάζεται, αλλά μην το παρακάνετε. Θα πρέπει να μπορεί κάποιος που δεν διάβασε την αρχική ερώτηση να καταλάβει για τι πράγμα μιλάτε.
. Χρησιμοποιήστε κάποια τεχνική για να ξεχωρίσετε ποιο κείμενο προέρχεται από το αρχικό μήνυμα, και ποιο έχετε προσθέσει εσείς. Προσωπικά βρίσκω ότι βάζοντας στην αρχή κάθε γραμμής του αρχικού μηνύματος ένα "`>`" είναι αρκετά καλός τρόπος να γίνει κάτι τέτοιο. Το να αφήνετε κενά μετά τις γραμμές που αρχίζουν με "`>`" και να αφήνετε μια κενή γραμμή μεταξύ του αρχικού κειμένου και του δικού σας επίσης βοηθά στο να είναι πιο εύκολο να διαβαστεί το αποτέλεσμα.
. Βάλτε τις απαντήσεις σας στο σωστό μέρος (μετά το κείμενο στο οποίο απαντάτε). Είναι πολύ δύσκολο να διαβαστεί μια ομάδα απαντήσεων όπου κάθε απάντηση έρχεται πριν το κείμενο στο οποίο απαντάει.
. Τα πιο πολλά προγράμματα ηλεκτρονικής αλληλογραφίας αλλάζουν το θέμα προσθέτοντας στην αρχή ένα "Re: ". Αν το δικό σας πρόγραμμα δεν το κάνει αυτόματα, θα πρέπει να το κάνετε εσείς.
. Αν ο αποστολέας δεν ακολούθησε τις συμβάσεις μορφοποίησης (γραμμές πολύ μεγάλες, άσχετη ή ασαφής γραμμή θέματος), _προτιμήστε_ να το διορθώσετε. Στην περίπτωση ακατάλληλης γραμμής θέματος (όπως π.χ "HELP!!??"), αλλάξτε το θέμα σε κάτι όπως "Re: Difficulties with sync PPP (was: HELP!!??)". Έτσι όσοι προσπαθούν να παρακολουθήσουν αυτή την ομάδα μηνυμάτων θα δυσκολευτούν λιγότερο να την παρακολουθήσουν.
+ 
Σε τέτοιες περιπτώσεις είναι καλό να λέτε τι κάνατε και γιατί, αλλά προσπαθήστε να μην είστε αγενείς. Αν δείτε ότι δεν μπορείτε να απαντήσετε χωρίς να είστε αγενείς, καλύτερα μην απαντάτε.
+ 
Αν απλά θέλετε να απαντήσετε σε ένα μήνυμα λόγω της κακής του μορφοποίησης, απαντήστε καλύτερα στον αποστολέα, κι όχι στη λίστα. Μπορείτε απλώς να του στείλετε αυτό το κείμενο σαν απάντηση, αν θέλετε.
