# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/articles/cvs-freebsd/Makefile
# %SRCID%	1.5

MAINTAINER= keramida@freebsd.org

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
