# $FreeBSD: www/ja/releases/3.1R/Makefile,v 1.3 1999/09/06 07:03:28 peter Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

DOCS=	announce.sgml notes.sgml errata.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/3.1R

.include "../../../web.mk"
