# $Id: Makefile,v 1.1 1999-03-01 16:36:03 motoyuki Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

#DOCS=	announce.sgml notes.sgml errata.sgml
DOCS=	notes.sgml errata.sgml

.include "../../../web.mk"
