---
title: "Die FreeBSD-Gemeinde"
sidenav: community
---

include::shared/de/urls.adoc[]

= Die FreeBSD-Gemeinde

Es gibt mehr als 100 link:mailinglists/[Mailinglisten], dutzende https://forums.FreeBSD.org/[Foren] sowie diverse link:{handbook}#eresources-news[Newsgroups]. Dazu kommen mehr als {{< get-usergroups-info "usergroups" >}} https://www.FreeBSD.org/usergroups/[User Groups] in {{< get-usergroups-info "countries" >}} Ländern. Zusätzlich existiert eine aktive link:irc[IRC]-Gemeinde. Außerdem betreiben die FreeBSD-Entwickler gemeinsam mit einigen der wichtigsten Unterstützer ein https://wiki.FreeBSD.org/[Wiki], das Informationen zur FreeBSD-Entwicklung und zu diversen Projekten enthält.

Letztes Jahr gab es insgesamt {{< get-event-last-year-info "events" >}} FreeBSD-Veranstaltungen in {{< get-event-last-year-info "countries" >}} verschiedenen Ländern. Ein https://www.FreeBSD.org/events/events.ics[Kalender] sowie ein https://www.FreeBSD.org/events/feed.xml[RSS Feed] zu bevorstehenden FreeBSD-spezifischen Veranstaltungen sind auf der Seite https://www.FreeBSD.org/events/[Veranstaltungen] verfügbar. Und nicht zuletzt gibt es dutzende Videos im Youtube-Channel https://www.youtube.com/bsdconferences[BSD Conferences].

== Soziale Netzwerke

FreeBSD ist auf diversen sozialen Netzwerken vertreten.

* Es gibt tausende Photos von Usergroup-Treffen, Konferenzen und Hackatons, die auf http://www.flickr.com[flickr] mit dem Tag 'link:https://flickr.com/search/?z=t&ss=2&w=all&q=freebsd&m=text[freebsd]' versehen wurden.
* Auf https://www.youtube.com[YouTube] gibt es hunderte Videos von Konferenzen, Präsentatitionen und Vorträgen, die sich auf https://www.youtube.com/results?search_query=freebsd[FreeBSD] beziehen. Weiters gibt es den Channel https://www.youtube.com/bsdconferences[BSD Conferences], über den Sie komplette Präsentationen von FreeBSD-Konferenzen verfolgen/ansehen können.
* Auf https://www.facebook.com[Facebook] gibt es die https://www.facebook.com/home.php#/group.php?gid=2204657214[FreeBSD Users Group], auf https://www.linkedin.com[LinkedIn] die https://www.linkedin.com/groups?gid=47628[FreeBSD Group].
* Auf https://twitter.com[Twitter] können Sie beispielsweise https://twitter.com/freebsd[@freebsd], https://twitter.com/freebsdhelp[@freebsdhelp], https://twitter.com/freebsdblogs[@freebsdblogs] oder https://twitter.com/freebsdcore[@freebsdcore] folgen.
