---
title: "Libri e Articoli Tradotti Online"
sidenav: docs
---

include::shared/it/urls.adoc[]

= Libri e Articoli Tradotti Online

== Su questo sito

Tutta la documentazione presente su questo sito può essere scaricata in vari formati (HTML, Postscript, PDF, e altri) e algoritmi di compressione differenti (BZip2, Zip) dal ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/[sito FTP di FreeBSD].

Questa documentazione è fornita e mantenuta dal link:https://www.FreeBSD.org/docproj/[FreeBSD Documentation Project], e siamo sempre alla ricerca di persone che contribuiscano con nuova documentazione e che mantengano quella esistente.

[[books]]
=== Libri tradotti in italiano

link:{handbook}[Il Manuale di FreeBSD] (`handbook`) +
Una risorsa esauriente, in costante evoluzione per gli utenti FreeBSD.


[[articles]]
=== Articoli tradotti in italiano

link:{committers-guide}[La Guida del Committer] (`committers-guide`) +
Informazioni introduttive per i committer di FreeBSD.

link:{explaining-bsd}[Panoramica su BSD] (`explaining-bsd`) +
Una risposta alla domanda ``Cos'è BSD?''

link:{filtering-bridges}[Filtering Bridges] (`filtering-bridges`) +
Configurazione di firewall e packet filtering su host FreeBSD che fungono da bridge anziché da router.

link:{new-users}[Primi Passi con FreeBSD] (`new-users`) +
Per persone che arrivano a FreeBSD e &unix; per la prima volta.

link:{vm-design}[Elementi di progettazione del sistema di VM di FreeBSD] (`vm-design`) +
Una descrizione facile da seguire sulla progettazione del sistema di memoria virtuale di FreeBSD.
