# $FreeBSD$

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

WITH_ARTICLE_TOC?=YES

SRCS= article.sgml
SRCS+=contrib.ent
SRCS+=contrib.386bsd.sgml
SRCS+=contrib.additional.sgml
SRCS+=contrib.committers.sgml
SRCS+=contrib.core.sgml
SRCS+=contrib.corealumni.sgml
SRCS+=contrib.develalumni.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
