=== Bugmeister Team

Links: +
link:https://bugs.freebsd.org/[FreeBSD Bugzilla] URL: link:https://bugs.freebsd.org/[]
link:https://bugs.freebsd.org/bugzilla/page.cgi?id=showreport.html&type=total_open_bugs_over_time[Total Open Bugs Over Time] URL: link:https://bugs.freebsd.org/bugzilla/page.cgi?id=showreport.html&type=total_open_bugs_over_time[]

Contact: Bugmeister <bugmeister@FreeBSD.org>

In this quarter we have decreased the Problem Reports count.

Although we do continue to get patches for the src tree, the majority of patches we receive are for ports.
This may be due to the auto-notifier customizations we have implemented.

For the src tree, in the last 180 days we have received 643 new Problem Reports and closed 844.
For ports, the count was 3493 in and 4375 respectively.

We do not currently maintain statistics about how many of these actually generate commits, although we do believe the number to be non-trivial.

During the same 180-day period Mark Linimon and Torsten Zuehlsdorff continued to work to triage older Problem Reports.
Mark's work was partly funded by the FreeBSD Foundation in 2025.
These results are visible from the last two dips in our link:https://bugs.freebsd.org/bugzilla/page.cgi?id=showreport.html&type=total_open_bugs_over_time[Total Open Bugs Over Time] graph.


As well, we seem to be getting more attention from various FreeBSD committers this year.
Please contact mailto:bugmeister@FreeBSD.org[bugmeister] if you are interested in helping.

Of course, we still are doing better at triaging PRs than we are generating attention to the ones we already have.
Suggestions welcome.

Mark Linimon has taken on the long-term project of making sure that the submitted patches all apply.
However, he does not claim to be a QA person and to be able to evaluate their aptness by himself.

The general takeaway is that, with user education, we are getting better-quality Problem Reports this year.
In particular, the ones with patches are being tested for applicability within a week or two of their arrival, and corrected if needed.

However, the farther back in time you go, the more problematic the PRs get, especially 2019 and earlier.
I suppose this is to be expected.
Mark continues to work on these in the background.
The current count is 2611.
Around 427 of these, mostly from 2019 and earlier, still need further work.

A problem with the setup of the upgrade to Bugzilla 5.2 has been fixed.
Light testing showed no meaningful regressions.
A bugfix version to 5.2.1 is imminent.
Switching to this codebase is intended to be as soon at it is released.
It was initially planned for earlier, however, it seemed inadvisable when the release engineering for FreeBSD 15.0 was ongoing, and then got further put off for 15.1.

"patchQA.py" still remains in beta.
The patch application code is not up to its task and must be replaced.

The other problem known with patchQA.py is that it does not know the origins of files that are installed into /etc by installworld.
There are external shell scripts that are in testing to help automate fixing the data.
This may be simpler than trying to write more fragile Python code for this purpose.

We have created many new Bugzilla accounts by user request.
The number of new-account requests has increased this year.
So far in 2026 we are at 291, which is not quite 2 per day.

It is now a year since we started requiring emailed requests to create accounts, rather than allowing automated requests.
By doing so, the spam flood has been reduced to nearly zero.

The other problem that we are monitoring is the huge number of http requests from crawlers.
By now these requests far outnumber those from actual FreeBSD users.
These are the cause for the sudden slowdowns our users object to.
As none of us are professional sysadmins, we would welcome help from someone with professional experience dealing with them.

Thanks to Alexander Ziaee and the many others who have helped to bring us up to our current state.

See also: link:https://wiki.freebsd.org/Bugzilla/SearchQueries[]
