=== Cluster Administration Team

Links: +
link:https://www.freebsd.org/administration/#t-clusteradm[Cluster Administration Team members] URL: link:https://www.freebsd.org/administration/#t-clusteradm[]

Contact: Cluster Administration Team <clusteradm@FreeBSD.org> +
Contact: Philip Paeps <philip@FreeBSD.org>

FreeBSD Cluster Administration Team members are responsible for managing the machines the Project relies on to synchronize its distributed work and communications.

In this quarter, the team has worked on the following:

* Regular support for FreeBSD.org user accounts.
* Regular disk and parts support (and replacement) for all physical hosts and mirrors.
* Cluster software refresh.
* Coordinate community mirrors.
* Additional support to the wiki-admin@ team.
* Frequent interventions to thwart denial of service by bots.

==== Cluster refresh

Work continues to refresh the software running on FreeBSD.org cluster machines.
We have started putting production workloads on stable/15.
As part of this work some workloads are being moved around to different machines.
This work is ongoing at the end of the quarter.

The clusteradm team refreshes the production package builders (circa 35 physical machines) on a roughly six- to eight-week cadence.
These machines run FreeBSD current snapshots.

Other machines are upgraded on an as-needed basis, keeping up with security fixes depending on how exposed they are.

At the time of this writing there are 142 physical machines in the cluster.
We have 42 machines on current, 21 on stable/15 and 73 on stable/14.

Most of the remaining stable/13 installations will be upgraded to stable/15.

[.screen]
----
 12.x: Regular   0, Jails   7
 13.x: Regular   6, Jails  31
 14.x: Regular  73, Jails 254
 15.x: Regular  21, Jails   4
 16.x: Regular  42, Jails   6
Total: Regular 142, Jails 302
Total installations: 444
Running -RELEASE|{-p*}: 0
Total geographic sites: 13
----

==== FreeBSD official mirrors

Current locations are Australia, Brazil, Japan (two full mirror sites), Malaysia, South Africa, Sweden, Taiwan and United States of America -- California, Chicago, New Jersey, and Washington.

Our mirror site in Taiwan is experiencing an extended outage.

One of our mirror sites in Japan will get a complete hardware refresh in 2026Q3.

The hardware and network connection have been generously provided by:

* Cloud and SDN Laboratory at link:https://www.bbtower.co.jp/en/corporate/[BroadBand Tower, Inc]
* link:https://www.cs.nycu.edu.tw/[Department of Computer Science, National Yang Ming Chiao Tung University]
* link:https://internet.asn.au/[Internet Association of Australia]
* link:https://www.isc.org/[Internet Systems Consortium]
* link:https://www.inx.net.za/[INX-ZA]
* link:https://www.kddi-webcommunications.co.jp/english/[KDDI Web Communications Inc]
* link:https://www.mohe.gov.my/en/services/research/myren[Malaysian Research & Education Network]
* link:https://www.metapeer.com/[MetaPeer]
* link:https://www.nyi.net/[New York Internet]
* link:https://nic.br/[NIC.br]
* link:https://sonic.net[Sonic]
* link:https://www.teleservice.net/[Teleservice Skåne AB]
* link:https://your.org/[Your.Org]

New official mirrors are always welcome.
We have noted the benefits of hosting single mirrors at Internet Exchange Points globally, as evidenced by our existing mirrors in Australia, Brazil, and South Africa.
If you are affiliated with or know of any organizations willing to sponsor a single mirror server, please contact us.
We are particularly interested in locations in Europe.

See link:https://wiki.freebsd.org/Teams/clusteradm/generic-mirror-layout[generic mirrored layout] for full mirror site specs and link:https://wiki.freebsd.org/Teams/clusteradm/tiny-mirror[tiny-mirror] for a single mirror site.

==== Supporting the wiki-admin@ team

The Cluster Administration Team assumed the role of the wiki-admin for most of this quarter while the position was vacant.
A new wiki-admin team was recently installed.
The Cluster Administration Team continues to support the wiki-admin team with necessary upgrades to the backend wiki infrastructure.

==== Large language model scraping

The FreeBSD Project's infrastructure continues to be under constant attack from scrapers collecting training data for large language models ("AI").
The companies training these models have largely moved scraping operations from their own - easy to identify - infrastructure to botnets ("residential proxies"), making them difficult to block at the network edges without significant collateral damage.
The Cluster Administration Team spent a considerable amount of time again this quarter mitigating these distributed denial of service attacks.

Sponsor: Anonymous individuals and companies +
Sponsor: https://github.com/sponsors/ppaeps
