=== DRM drivers

Links: +
link:https://github.com/freebsd/drm-kmod/pull/469[Update to Linux 6.13 DRM drivers] URL: link:https://github.com/freebsd/drm-kmod/pull/469[]

Contact: Jean-Sébastien Pédron <dumbbell@FreeBSD.org>

DRM drivers are **kernel drivers for integrated and discrete GPUs**.
They are maintained in the Linux kernel and we port them to FreeBSD.
As of this report, we take the AMD and Intel DRM drivers only (NVIDIA FreeBSD drivers are proprietary and provided by NVIDIA themselves).

We port them one Linux version at a time.
This allows us to ship updates more often and it eases porting and debugging because we have a smaller delta compared to a bigger jump skipping several versions.

This quarter, we finished the **porting of DRM drivers from Linux 6.12 LTS in time for the release of FreeBSD 15.1-RELEASE**.
Because this is an LTS version, we will track changes from the Linux 6.12.x patches.
Currently, we are at 6.12.81 and work is underway to continue to bump to the latest patch.
These drivers are available from the Ports tree and as packages.

As part of the work on 6.12 drivers, several bugs or regressions were fixed for already supported GPUs.
Some newer GPUs started to work as well.

We still have several instabilities to fix in both the i915 and the amdgpu drivers.

We also continued to port DRM drivers from following Linux versions:
* The **update to Linux 6.13 is under review and testing**.
* The update to Linux 6.14 is ready as well and will be reviewed after the 6.13 update.

This work is kindly sponsored by the FreeBSD Foundation as part of the Laptop and Desktop Project.

Sponsor: The FreeBSD Foundation
