=== GCC on FreeBSD

Links: +
link:https://gcc.gnu.org/[GCC Project] URL: link:https://gcc.gnu.org/[] +
link:https://gcc.gnu.org/gcc-13/[GCC 13 release series] URL: link:https://gcc.gnu.org/gcc-13/[] +
link:https://gcc.gnu.org/gcc-14/[GCC 14 release series] URL: link:https://gcc.gnu.org/gcc-14/[] +
link:https://gcc.gnu.org/gcc-15/[GCC 15 release series] URL: link:https://gcc.gnu.org/gcc-15/[] +
link:https://gcc.gnu.org/gcc-16/[GCC 16 release series] URL: link:https://gcc.gnu.org/gcc-16/[] +
link:https://gcc.gnu.org/gcc-17/[GCC 17 release series] URL: link:https://gcc.gnu.org/gcc-17/[]

Contact: Lorenzo Salvadore <salvadore@FreeBSD.org>

Two new ports have been created: package:lang/gcc16[] and package:lang/gcc17-devel[].

link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=294062[PR 294062] about arm64 build failures has been fixed.
More precisely, in 2026Q2 package:lang/gcc16-devel[] and package:lang/gcc17-devel[] have been fixed, while package:lang/gcc16[] has been fixed in the beginning of 2026Q3 (at the time this report is written the patch still needs to be forwarded to the ports quarterly branch).
Unfortunately, the solution is local to the FreeBSD ports tree and cannot be upstreamed directly.
Discussion for an upstream solution can be found in the link:https://gcc.gnu.org/bugzilla/show_bug.cgi?id=125182[upstream bugzilla].
Thanks to all those who have helped, in particular to Mark Millard.

I have not worked personally on the link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=292692[process] to get GCC_DEFAULT=15 this quarter, but some work is being done in the associated PRs, so this is getting forward as well.
Moreover, minor version updates to package:lang/gcc13[], package:lang/gcc14[] and package:lang/gcc15[] are planned.

As I continue to work on the GCC ports, I realize that I am having less time and less energy to put into them.
These ports are important, I prefer not to leave them unmaintained at least until I am able to deal with them, even if slowly.
But if there is someone who would like to take them, please stand up and I would be glad to transfer maintainership.
