=== Raspberry Pi Imager FreeBSD Port

Links: +
link:https://github.com/raspberrypi/rpi-imager[rpi-imager upstream] URL: https://github.com/raspberrypi/rpi-imager[] +
link:https://github.com/raspberrypi/rpi-imager/pull/1655[FreeBSD Port pull request] URL: https://github.com/raspberrypi/rpi-imager/pull/1655[] +
link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=296480[PR 296480 - FreeBSD Ports open review] URL: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=296480[]

Contact: Jim Chen <jim.chen.1827@gmail.com> +
Contact: Nimish Jain <njain15@protonmail.com>

The Raspberry Pi Imager is a convenient graphical tool developed by the Raspberry Pi Foundation that allows users to easily configure and flash operating system images to storage cards for the Raspberry Pi Zero and Raspberry Pi 1-5 series single-board computers.

Our goal in porting this app to FreeBSD is to continue lowering barriers to entry.
We want users unfamiliar with the command line to easily flash operating systems to their Raspberry Pi.

Currently, the upstream project supports only Linux, MacOS, and Windows.
We have created a FreeBSD port that uses native I/O, disk, and network APIs and links against pre-packaged FreeBSD libraries.

The main blocker for this project is currently upstream uncertainty.
The maintainers have requested buy-in from FreeBSD developers to help with the long-term maintenance of the FreeBSD-specific code.
If you are a committer or a contributor invested in Raspberry Pi tooling on FreeBSD, please let us know or join the discussion on the GitHub pull request!

If this work is accepted upstream, a Makefile for the FreeBSD Ports repository is ready for review as PR 296480 (link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=296480[]).

If you’re interested, please do try out a local release by cloning the Ports tree and applying the patch in the PR mentioned above, and let us know if you have any issues!

Sponsor: The FreeBSD Foundation
