=== Sylve -- A Unified System Management Platform for FreeBSD

Links: +
link:https://sylve.io[Website] URL: link:https://sylve.io[] +
link:https://github.com/AlchemillaHQ/Sylve[GitHub] URL: link:https://github.com/AlchemillaHQ/Sylve[] +
link:https://sylve-ci.alchemilla.io[CI] URL: link:https://sylve-ci.alchemilla.io[] +
link:https://discord.gg/bJB826JvXK[Discord] URL: link:https://discord.gg/bJB826JvXK[]

Contact: Hayzam Sherif <hayzam@alchemilla.io>

Sylve is a modern, unified system management platform for FreeBSD.
It provides an integrated web interface for managing virtual machines (via Bhyve), Jails, the networking around them, and ZFS storage.

The backend is implemented in Go, while the frontend is built with Svelte.
The project emphasizes a minimal system footprint.
By default, it does not require any packages outside of the base system.

Optional runtime dependencies, required only when their respective features are used, include:

- package:devel/libvirt[] for virtualization
- package:devel/qemu[devel/qemu-tools] for disk image management
- package:net/samba419[] for SMB file sharing
- package:sysutils/swtpm[] for TPM emulation support
- package:dns/dnsmasq[] for DHCP and DNS services

The port pulls in these dependencies for convenience to the user, but by itself, Sylve needs no dependencies to run.

==== Q2 Progress Highlights

===== Data Center / Cluster

* Implemented ways for users to have highly available VMs and Jails, with automatic failover to a secondary/tertiary etc. node in the cluster with the help of ZFS replication (no live migration yet).
* Made it easy to migrate VMs/Jails between nodes in a cluster without Quorum or HA, with a simple "Migrate" button in the UI.
* Backups and Restore workflows have been improved significantly, with enhanced error handling and better user feedback, including the support for encrypted datasets.

===== Networking

* Added support for adding network routes from the Web UI.
* A PF based firewall is now implemented with full support for Traffic and NAT rules, including the ability to use objects within rules for things like lists of IPs, FQDNs, etc.
* Added support for an intuitive WireGuard configuration UI, allowing users to easily set up and manage WireGuard tunnels.

===== Storage

* man:smart[8] was vendored in as a dependency as an alternative to smartmontools
* ZFS pool management now supports creating special VDEVs.
* Samba now uses a built-in mDNS server instead of avahi
* Initial iSCSI support was added, allowing users to create and manage iSCSI targets and initiators directly from the Web UI.

===== Virtual Machines & Jails

* UI responsiveness and performance have been improved, especially for large clusters with many VMs/Jails.
* Added support for VLAN tagging for Jails directly instead of requiring users to create a separate bridge for each VLAN.
* A lot of manual command-line flags have now been converted into libvirt XML syntax for VMs, allowing easier management and better compatibility with libvirt-based tools.
* Significant improvements have been made to the auto-start/stop processes for VMs and Jails.

===== General

* Notifications system has been re-worked to add support discord webhooks, ntfy.sh and SMTP based transports, it now also supports multiple transports at once, and allows users to configure which events they want to receive notifications for.

==== Roadmap Update

* All the road map items (except NFS shares from the previous quarter) have been completed, and we are now working on the next set of features for Q3:
  * NFS shares support, allowing users to create and manage NFS shares directly from the Web UI.
  * A simplified UI-mode aiming to make it easier for new users to get started with Sylve as a NAS appliance.
  * Podman and OCI container support, allowing users to run containers alongside VMs and (classic) Jails.
  * A mobile application for iOS and Android, allowing users to manage their clusters on the go.
  * App template library, allowing users to easily deploy popular applications (like Nextcloud, Plex, etc.) with a single click.

Sponsors: The FreeBSD Foundation, Alchemilla Ventures (Development), IPTechnics LLC (Infrastructure & Testing)
