#
# $FreeBSD$
#
# Article: Design elements of the FreeBSD VM system

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.xml
IMAGES_EN=	fig1.eps
IMAGES_EN+=	fig2.eps
IMAGES_EN+=	fig3.eps
IMAGES_EN+=	fig4.eps

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
