# $FreeBSD: www/en/projects/Makefile,v 1.9 2001/09/18 18:28:07 alex Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	projects.sgml
DOCS+=	updater.sgml
DOCS+=	newbies.sgml
DOCS+=	libh.sgml

INDEXLINK= projects.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
