# $FreeBSD: www/en/layout/css/Makefile,v 1.2 2006/09/18 21:25:38 shaun Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	fixed.css
DATA+=	fixed_large.css
DATA+=	global.css
DATA+=	iefixes.css
DATA+=	layout.css
DATA+=	navigation.css
DATA+=	query-pr.css
DATA+=	table.css
DATA+=	text.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
