# $FreeBSD: www/en/gifs/Makefile,v 1.53 2005/05/08 15:49:57 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   fixed.css fixed_large.css global.css iefixes.css layout.css navigation.css table.css text.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
