# $FreeBSD: www/en/layout/css/Makefile,v 1.3 2007/03/17 15:36:10 simon Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	cvsweb.css
DATA+=	fixed.css
DATA+=	fixed_large.css
DATA+=	global.css
DATA+=	iefixes.css
DATA+=	layout.css
DATA+=	navigation.css
DATA+=	query-pr.css
DATA+=	table.css
DATA+=	text.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
