---
title: "FreeBSD のアプリケーションについて"
sidenav: about
---

= FreeBSD のアプリケーションについて

== FreeBSD で実行できること

FreeBSD は、あなたが UNIX(R) ワークステーションに期待するほとんどすべての仕事を、 あなたがたの多くが期待していないであろうほど上手に扱うことができます。

== FreeBSD は、すべてのソースコードが提供されている正真正銘にオープンなシステムです

今日のコンピュータ応用分野では、 オープンシステムと呼ばれるものが__要求__されることは疑う余地がないでしょう。 しかし、カーネル、すべてのシステムデーモン、プログラム、 ユーティリティを含むオペレーティングシステム全体の完全なソースコードが含まれたシステムよりもオープンな商用システムは存在しません。 あなたは、あなた個人や組織や会社の要求に応じて、 都合のいいように FreeBSD の任意の部分を変更できます。

link:../copyright/freebsd-license/[ライセンス方針]が寛大であり、 あなたは任意の数のフリーまたは__商用__のアプリケーションの基盤として FreeBSD を使うことができます。

== FreeBSD では膨大な数のアプリケーションが動きます

FreeBSD は UNIX の業界標準である 4.4BSD をもとにしているので、 プログラムをコンパイルして実行するのが容易です。 また、FreeBSD には広範囲に及ぶ link:../where/[package コレクション] と link:../ports/[Ports Collection] が含まれており、コンパイル済みのものをインストールしたり、 あなたのデスクトップや業務用サーバに適したソフトウェアを簡単に構築したりできます。 FreeBSD のために書かれたlink:../commercial/software/[商用アプリケーション] もまた、急増しています。

FreeBSD が利用されている環境の例:

* *インターネットサービス。* 多くのインターネットサービスプロバイダ (ISP) は、 FreeBSD が WWW, Usenet news, FTP, Email 他のサービスを動かす理想的な環境であると考えています。link:http://nginx.org[nginx] または http://www.apache.org/[Apache] ウェブサーバや http://proftpd.org/[ProFTPD] または http://security.appspot.com/vsftpd.html[vsftpd] FTP サーバなど即実行可能なソフトウェアにより、 業務用や社会基盤としての ISP を容易に準備できます。 もちろん、FreeBSD の頑強なlink:../internet/[ネットワーク]により、 あなたがたのユーザは高速で信頼性のあるサービスを享受できるでしょう。
* *X Window ワークステーション。* 廉価な X 端末としても上級の X ディスプレイとしても FreeBSD はとてもよく動きます。 フリーの X ソフトウェア (http://x.org/[X.Org](TM)) はシステムとともに提供されています。 http://www.nvidia.com/[nVidia] は、 高性能なグラフィックスハードウェアのネイティブドライバを提供しています。 また、業界標準である http://www.opengroup.org/motif/[Motif](R) や http://www.opengl.org/[OpenGL](R) ライブラリにも対応しています。link:http://xfce.org/[Xfce] および http://lxde.org/[LXDE] はデスクトップ環境を提供します。 http://www.kde.org[KDE] や http://www.gnome.org[GNOME] デスクトップ環境に完全に対応し、 オフィススィートの機能を提供します。 さらに、link:https://www.libreoffice.org/[LibreOffice], http://www.openoffice.org/[OpenOffice.Org] や http://www.softmaker.com/en/[TextMaker] などの製品によって、さらなる機能を利用できます。
* *ネットワーキング。* パケットフィルタリングからネームサービスへのルーティングまで、 FreeBSD ではどのような PC でもインターネットファイヤウォール、 email ホスト、プリントサーバ、 PC/NFS サーバなどに仕立てることができます。
* *ソフトウェア開発。* FreeBSD には開発ツール一式が用意されており、 GNU C/C++ コンパイラ、デバッガが含まれています。 LLVM ベースの clang も含まれており、将来的には GNU スイートを置き換える予定です。 Java(TM) や Tcl/Tk もまた開発可能で、 Icon のようにより深遠なプログラミング言語も快適に動きます。 そして、FreeBSD の共有ライブラリは常に作成と使用を容易にしています。 また、Emacs や Vim といったポピュラーでパワフルなエディタも利用できます。
* *ウェブブラウジング。* 本物の UNIX ワークステーションは、 インターネットを楽しむためのすばらしい道具を提供します。 真剣なウェブユーザのために、FreeBSD 版の http://www.chromium.org/Home[Chromium] や http://www.mozilla.org/firefox/[Firefox] が用意されています。 あなたのデスクトップ上の FreeBSD でウェブブラウジングを楽しみ、 あなた自身のウェブページを公開し、Usenet news を読み、email を送受信できます。
* *教育や研究。* FreeBSD はすべてのソースコードを含んでいるので、優れた研究環境を構築できます。 オペレーティングシステムや他の情報科学分野の学生と研究者は、 オープンで文書が完備されたシステムから大いに恩恵を受けることができます。
* *それ以外のこと。* 経理、アクションゲーム、MIS データベース、科学的可視化、ビデオ会議、 インターネットリレーチャット (IRC)、ホームオートメーション、 マルチユーザダンジョン、掲示板システム、イメージスキャニングなどにおいて、 FreeBSD が実際に利用されています。

== FreeBSD オペレーティングシステムはあなたと共に成長していきます

FreeBSD はフリーソフトウェアですが、_ユーザに支持された_ ソフトウェアでもあります。あなたのどんな質問でも、単に freebsd-questions@FreeBSD.org メーリングリストに投稿するだけで、多数の FreeBSD 開発者やユーザに送ることができます。

さらに FreeBSD には世界規模のプログラマやライタのグループがあり、 彼らはバグを直したり、新しい機能を追加したり、 システムのドキュメントを整備したりしています。 新しいデバイスや特殊な機能を支援するようにほぼ定常的に開発されており、 (開発者) チームはシステムの安定性に影響する問題に対して注意を注いでいます。 FreeBSD ユーザは、いかに速いかだけでなく、 いかに彼らのシステムが信頼できるかということにとても誇りを持っています。

== ある専門家の意見では...

__''FreeBSDは「我々」の膨大な仕事を難なくこなし、驚きの連続である。 FreeBSDチームの皆様に敬意を。''__

---Mark Hittinger, WinNet Communications, Inc. 管理者
