# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

LOCALTOP= ../..

DOCS=	announce.sgml
DOCS+=	notes.sgml
DOCS+=	errata.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
