---
title: "Проект FreeBSD/MIPS"
sidenav: developers
---

include::shared/ru/urls.adoc[]

= Проект FreeBSD/MIPS

На этой странице находится информация о переносе FreeBSD на платформу MIPS.

== Общая информация

* <<faq,FAQ о порте>>
* <<list,Список рассылки FreeBSD/MIPS>>

[[faq]]
== Часто задаваемый вопросы

. <<one,Что представляет собой проект FreeBSD/MIPS?>>
. <<two,На какое оборудование вы ориентируетесь?>>
. <<three,Каково состояние на текущий момент?>>
. <<four,Как можно получить FreeBSD/MIPS?>>
. <<four,С кем можно связаться?>>

[[one]]
=== Что представляет собой проект FreeBSD/MIPS?

FreeBSD/MIPS является переносом операционной системы FreeBSD на компьютеры с процессорами MIPS R4K и выше, самыми известными из которых являются MIPS-компьютеры компании SGI.

[[two]]
=== На какое оборудование вы ориентируетесь?

На данный момент это компьютеры MIPS компании SGI. В дальнейшем предполагается, что это и другие платформы MIPS, такие, как распространённые встраиваемые системы и неэкзотичные компьютеры в конфигурациях, похожих на те, что поставляет SGI.

[[three]]
=== Каково состояние на текущий момент?

FreeBSD/MIPS находится на ранних стадиях разработки, посмотрите страницу о link:../projects/mips[состоянии проекта] для получения информации о ведущейся в настоящее время работе.

[[four]]
=== Как можно получить FreeBSD/MIPS?

Работа над FreeBSD/MIPS ведётся в хранилище Perforce проекта FreeBSD, но иногда изменения публикуются в <<list,списке рассылки>>.

[[five]]
=== С кем можно связаться?

mailto:jmallett@FreeBSD.org[Juli Mallett] является лидером проекта. Обратитесь к ней, если вы хотите поделиться своим кодом. Если вы просто хотите выяснить состояние этого проекта, то просто регулярно посещайте link:../projects/mips[страницу состояния проекта] или подключитесь к <<list,списку рассылки FreeBSD/MIPS>>.

[[list]]
== Список рассылки FreeBSD/MIPS

Для того, чтобы подписаться на этот список, пошлите письмо на адрес `<freebsd-mips-subscribe@FreeBSD.org>` или воспользуйтесь http://lists.FreeBSD.org/mailman/listinfo/freebsd-mips[интерфейсом mailman].
