---
title: "Проект FreeBSD/ppc"
sidenav: developers
---

include::shared/releases.adoc[]
include::shared/ru/urls.adoc[]

= Проект FreeBSD/ppc

== Общая информация

* <<intro,Введение>>
* <<news,Последние новости>>
* <<faq,FAQ по переносу>>
* <<hardware,Поддерживаемое оборудование>>
* <<list,Список рассылки FreeBSD/ppc>>
* <<issues,Известные проблемы>>
* <<doc,Документация, статьи, утилиты>>
* <<links,Другие интересные ссылки>>

[[intro]]
== Введение

Странички проекта FreeBSD/ppc содержат информацию о портировании FreeBSD на архитектуру PowerPC(R). Также как и сам порт, эти документы находятся в процессе написания.

Порт FreeBSD/ppc до сих базируется на платформе Tier-2. Это означает, что он не полностью поддерживается нашими офицером по безопасности, инженерами, отвечающими за выпуск релизов и мэйнтейнерами утилит.

'''''

[[news]]
== Последние новости

* *25 июня 2005* : Эта страница была серьезно переработана.

'''''

[[faq]]
== Часто задаваемые вопросы

. <<one,Как я могу установить FreeBSD/ppc?>>
. <<two,Где я могу найти пакеты для платформы FreeBSD/ppc?>>
. <<three,Как использовать порты на FreeBSD/ppc?>>
. <<four,С кем я могу связаться?>>

[[one]]
=== Как я могу установить FreeBSD/ppc

Существуют ISO образы, доступные для скачивания http://people.freebsd.org/~grehan/ppc_iso[по этой ссылке]. Последний 7.0-CURRENT ISO образ может быть загружен http://people.freebsd.org/~grehan/ppc_iso/latest.iso[отсюда]. Пожалуйста, следуйте инструкциями, представленными http://people.freebsd.org/~grehan/iso_install.txt[по этой ссылке].

[[two]]
=== Где я могу найти пакеты для платформы FreeBSD/ppc?

Благодаря Питеру Грехану (Peter Grehan) и Тильман Линневе (Tilman Linneweh), вы можете найти некоторые пакеты http://people.freebsd.org/~grehan/ppc_pkgs/[тут] и http://people.freebsd.org/~arved/packages_powerpc/[тут]. Пожалуйста, заметьте, что эти пакеты на сегодняшний день довольно устарели. Если возможно, то старайтесь использовать порты.

[[three]]
=== Kак использовать порты на FreeBSD/ppc?

Легкий путь использовать порты во FreeBSD, начиная с 6.0-RELEASe заключается в использовании portsnap. Обратитесь к Руководству, если вам нужна помощь в link:{handbook}#ports-using[использовании Коллекции Портов].

[[four]]
=== С кем я могу связаться?

mailto:grehan@FreeBSD.org[Peter Grehan] - руководитель проекта. Если вы только хотите узнать о статусе проекта, обращайтесь к этой странице регулярно или присоединяйтесь к <<list,списку рассылки FreeBSD/ppc>>.

'''''

[[hardware]]
== Поддерживаемое оборудование

Порт FreeBSD/ppc должен работать на любой новой (New-World) машине. Пользователи сообщили, что FreeBSD работает на следующих машинах:

[cols=",,,",options="header",]
|===
|Производитель |Модель |Кто сообщил (ссылки может и не быть) |Заметки
|Apple |iMac G3 350 MHz |mailto:diskiller@diskiller.net[Martin Minkus] |Rage 128VR
|Apple |iMac G3 DV Special Edition |mailto:webmaster@machowto.com[David S. Besade] (http://people.freebsd.org/~flz/local/dmesg.ppc[dmesg]) |отсутствуют
|Apple |iMac G3 Revision B |mailto:grehan@FreeBSD.org[Peter Grehan] |Rage 3D Pro 215GP, accel disabled
|Apple |eMac 700 MHz |mailto:grehan@FreeBSD.org[Peter Grehan] |Nvidia GeForce2 MX
|Apple |Mac Mini G4 1.4 GHz |mailto:arved@FreeBSD.org[Tilman Linneweh] (http://people.freebsd.org/~arved/stuff/minimac[dmesg]) |отсутствуют
|Apple |Powerbook G4 1.33 GHz |mailto:grehan@FreeBSD.org[Peter Grehan] |Nvidia GeForce G5200
|Apple |Aluminium Powerbook G4 1.5 GHz |mailto:toa@pop.agri.ch[Andreas Tobler] |отсутствуют
|===

'''''

[[list]]
== Список рассылки FreeBSD/ppc

Для подписки на эту рассылку, отправьте письмо на `<freebsd-ppc-subscribe@FreeBSD.org>` или воспользуйтесь http://lists.FreeBSD.org/mailman/listinfo/freebsd-ppc[интерфейсом mailman].

'''''

[[issues]]
== Известные проблемы

* Не поддержки AltiVec.
* Встроенные BMAC+ ethernet карточки не работают. Продолжается работа над bm(4) драйвером, доступным на персональной страничке Peter Grehan http://people.freebsd.org/~grehan/[here] (see if_bm.c and if_bmreg.h).
* Нет графического курсора мыши в консоли.
* Не работает Fdisk.
* Поддерживаются только USB клавиатуры.
* Если у вас имеется оборудование с поддержкой Bluetooth, то существует 'поддельный' порт OHCI и устройства, которые могут использоваться для доступа к беспроводной клавиатуре или мыши. Проблема заключается в том, что оно исследуется перед фиксированной (fixed) клавиатурой/мышью и является первым на очереди к syscons. Чтобы решить это проблему, PCI слот, ассоциированный с проблематичным ohci2 может быть отключен в загрузчике:
+
....
OK set hint.pcib.1.skipslot=26
....
* Для машин, базирующихся на ATI Radeon:
** Проверку диапазона ofw syscons нужно отключить, используя sysctl hw.ofwfb.relax_mmap.
** Нужен специальный radeon http://people.freebsd.org/~grehan/radeon_driver.c[драйвер]. Вы должны добавить следующее в раздел Section "Device" файла xorg.conf
+
....
Option "iBookHacks" "on"
....
* Существует известная ошибка в загрузчике, что не дает загружать альтернативное ядро, и поэтому тестирование вашего собственного ядра рискованно. При запуске загрузчика из приглашения (prompt) Open Firmware, укажите либо несуществующий раздел, либо тот, который не имеет ядра на нем, либо не является UFS разделом:
+
....
0 > boot hd:loader hd:0
....
+
На этом этапе, вы можете установить currdev и вручную загрузить ядро:
+
....
OK set currdev=hd:14
OK load /boot/kernel/kernel.save
....

'''''

[[doc]]
== Документация, статьи, утилиты

* http://e-www.motorola.com/brdata/PDFDB/docs/MPCFPE32B.pdf[Документация на чип PowerPC]
* http://www.firmworks.com/QuickRef.html[Кратко о Open Firmware]
* http://developer.apple.com/technotes/tn/tn1061.html["TN1061: Основы Open Firmware, часть 1 - Интерфейс Пользователя"]
* http://developer.apple.com/technotes/tn/tn1062.html["TN1062: Основы Open Firmware, часть 2 - Дерево Устройств"]
* http://developer.apple.com/techpubs/hardware/hardware2.html[Документы по оборудованию Apple для разработчиков]
* http://developer.apple.com/technotes/tn/tn2004.html["TN2004: Отладка Open Firmware, используя Telnet"]
* http://developer.apple.com/technotes/tn/tn2023.html["TN2023: Open Firmware Ethernet Debugging II - Telnet Downloading"]
* http://developer.apple.com/technotes/tn/tn2001.html["TN2001: Запуск Файлов с жёсткого диска в Open Firmware"]
* http://sourceware.cygnus.com/psim/[psim] - Симулятор PowerPC, доступный, как порт FreeBSD в http://www.freshports.org/?package=psim-freebsd[emulators/psim-freebsd]

[[links]]
== Другие интересные ссылки

* http://wikitest.freebsd.org/moin.cgi/powerpc[Страничка wiki, посвященная проекту FreeBSD/ppc]
* http://lists.freebsd.org/pipermail/freebsd-ppc/2005-January/000814.html[Описание, подготовленное Гарансом А. Дрошенным (Garance A. Drosehn) о работе FreeBSD на Mac Mini]
* http://www.NetBSD.org/Ports/macppc/[NetBSD/macppc]
* http://www.OpenBSD.org/macppc.html[OpenBSD/macppc]
