---
title: "Проект FreeBSD/sparc64"
sidenav: developers
---

include::shared/releases.adoc[]
include::shared/ru/urls.adoc[]

= Проект FreeBSD/sparc64

[[intro]]
== Введение

На данной странице содержится информация о портировании FreeBSD на архитектуры SPARC64(R) компании Fujitsu и UltraSPARC(R) компании Oracle. Обсуждение этого порта ведется в рассылке https://lists.freebsd.org/subscription/freebsd-sparc64[freebsd-sparc].

== Оглавление

* <<status,Статус>>
* <<hw,Список аппаратного обеспечения>>
* <<list,Рассылка FreeBSD/sparc64>>
* <<links,Интересные материалы по FreeBSD/sparc64>>

[[status]]
== Статус

UltraSPARC является архитектурой уровня link:{committers-guide}#archs[Уровень 2] вплоть до FreeBSD 12.x. Начиная с FreeBSD 13.0 и новее, она больше не поддерживается.

[[hw]]
== Список аппаратного обеспечения

Далее следует перечень поддерживаемых систем. SMP поддерживается на всех поддерживаемых системах, содержащих более одного процессора. За полной информацией обращайтесь к link:../../releases/{rel120-current}r/hardware/[информации об аппаратной совместимости] link:../../releases/[релиза], который вы используете.

* Naturetech GENIALstation 777S
* Sun Blade 100
* Sun Blade 150
* Sun Enterprise 150
* Sun Enterprise 220R
* Sun Enterprise 250
* Sun Enterprise 420R
* Sun Enterprise 450
* Sun Fire B100s (поддержка встроенных сетевых карт впервые появилась в 8.1-RELEASE)
* Sun Fire V100
* Sun Fire V120
* Sun Netra(T) T1 100/105
* Sun Netra T1 AC200/DC200
* Sun Netra t 1100
* Sun Netra t 1120
* Sun Netra t 1125
* Sun Netra t 1400/1405
* Sun Netra 120
* Sun Netra X1
* Sun SPARCEngine(R) Ultra AX1105
* Sun SPARCEngine Ultra AXe
* Sun SPARCEngine Ultra AXi
* Sun SPARCEngine Ultra AXmp
* Sun SPARCEngine CP1500
* Sun Ultra(T) 1
* Sun Ultra 1E
* Sun Ultra 2
* Sun Ultra 5
* Sun Ultra 10
* Sun Ultra 30
* Sun Ultra 60
* Sun Ultra 80
* Sun Ultra 450

Эти системы поддерживаются FreeBSD частично. В частности, контроллеры Fibre Channel в системах на базе SBus не поддерживаются. Однако их можно использовать с SCSI-контроллером, поддерживаемым драйвером esp(4) (контроллеры Sun ESP SCSI, Sun FAS Fast-SCSI и Sun FAS366 Fast-Wide SCSI).

* Sun Enterprise 3500
* Sun Enterprise 4500

Начиная с 7.2-RELEASE, FreeBSD также поддерживает системы sparc64 на базе Sun UltraSPARC III и новее, включая следующие известные рабочие системы:

* Sun Blade 1000
* Sun Blade 1500
* Sun Blade 2000
* Sun Blade 2500
* Sun Fire 280R
* Sun Fire V210
* Sun Fire V215 (поддержка впервые появилась в 7.3-RELEASE и 8.1-RELEASE)
* Sun Fire V240
* Sun Fire V245 (поддержка впервые появилась в 7.3-RELEASE и 8.1-RELEASE)
* Sun Fire V250
* Sun Fire V440 (поддержка встроенных сетевых карт впервые появилась в 7.3-RELEASE и 8.0-RELEASE)
* Sun Fire V480 (только монтажные панели 501-6780 и 501-6790, поддержка которых впервые появилась в 7.3-RELEASE и 8.1-RELEASE; другие монтажные панели могут работать, начиная с 8.3-RELEASE и 9.0-RELEASE)
* Sun Fire V880
* Sun Fire V890 (поддержка впервые появилась в 7.4-RELEASE и 8.1-RELEASE, только конфигурации CPU без смешения Ultrasparc IV/IV+)
* Sun Netra 20/Netra T4

Эти системы Sun UltraSPARC не тестировались, но считается, что они также поддерживаются FreeBSD:

* Sun Fire V125
* Sun Fire V490 (поддержка впервые появилась в 7.4-RELEASE и 8.1-RELEASE, только конфигурации CPU без смешения Ultrasparc IV/IV+)

Начиная с 7.4-RELEASE и 8.1-RELEASE, FreeBSD также поддерживает системы sparc64 на базе Fujitsu SPARC64 V, включая следующие известные рабочие системы:

* Fujitsu PRIMEPOWER(R) 250

Эти системы Fujitsu SPARC64 не тестировались, но считается, что они также поддерживаются FreeBSD:

* Fujitsu PRIMEPOWER 450
* Fujitsu PRIMEPOWER 650
* Fujitsu PRIMEPOWER 850

Если у вас есть система, не указанная здесь, пожалуйста, испытайте ее и дайте mailto:freebsd-sparc@FreeBSD.org[нам] знать.

[[list]]
== Рассылка FreeBSD/sparc64

Чтобы подписаться на эту рассылку, отправьте электронное письмо на адрес `<freebsd-sparc64+subscribe@FreeBSD.org>` или посетите https://lists.FreeBSD.org/subscription/freebsd-sparc64[интерфейс mlmmj].

[[links]]
== Интересные материалы

* http://www.sparc.org/technical-documents-test-2/[Стандарты SPARC и технические документы]
* http://www.netbsd.org/Ports/sparc64/[NetBSD/sparc64]
* http://www.openbsd.org/sparc64.html[OpenBSD/sparc64]
