#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
# $Id: Makefile,v 1.1 2003-07-08 18:52:37 blackend Exp $
# Original revision: 1.1
#

CHAPTERS= 	mirrors/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
