---
title: "Исправления и дополнения для FreeBSD 15.1-RELEASE"
sidenav: download
---

:release: 15.1-RELEASE
:releaseNext: 15.2-RELEASE
:releaseBranch: 15-STABLE

= Исправления и дополнения для FreeBSD {release}

== Общая информация о документе

В этом документе перечислены исправления и дополнения для FreeBSD {release}, содержащие важную информацию, выявленную после выпуска релиза или в рамках цикла подготовки релиза, но слишком поздно для её включения в документацию к релизу.
Эта информация включает в себя уведомления о безопасности, а также актуальные новости, связанные с программным обеспечением или документацией, способные повлиять на их работу или возможность использования.
Перед установкой этой версии FreeBSD всегда следует обращаться к актуальной версии данного документа.

Этот документ с информацией об исправлениях и дополнениях для FreeBSD {release} будет поддерживаться вплоть до выпуска релиза FreeBSD {releaseNext}.

== Содержание

* <<intro,Введение>>
* <<security,Уведомления о безопасности>>
* <<errata,Уведомления об исправлениях и дополнениях>>
* <<open-issues,Открытые проблемы>>
* <<late-news,Актуальные новости>>

[[intro]]
== Введение

Этот документ с информацией об исправлениях и дополнениях содержит "самые свежие новости" о FreeBSD {release}.
Перед установкой этой версии важно ознакомиться с этим документом, чтобы узнать о любых нюансах и проблемах, обнаруженных после публикации релиза, которые уже могли быть найдены и устранены.

Любая версия этого документа с информацией об исправлениях и дополнениях, распространяемая с данным релизом на физическом носителе (например, в составе дистрибутива на CDROM), по определению будет устаревшей, однако его копии поддерживаются в актуальном состоянии в сети Интернет и должны использоваться в качестве "актуальной информации об исправлениях и дополнениях" для данного релиза.
Эти копии с информацией об исправлениях и дополнениях находятся по адресу https://www.FreeBSD.org/ru/releases/, а также на любых зеркалирующих сайтах, которые поддерживают актуальные копии этого ресурса.

Исходные и бинарные промежуточные сборки FreeBSD {releaseBranch} также содержат актуальные копии этого документа (на момент создания соответствующей промежуточной сборки).

Список всех уведомлений CERT, касающихся безопасности FreeBSD, доступен по адресу https://www.FreeBSD.org/ru/security/.

[[security]]
== Уведомления о безопасности

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Уведомление |Дата |Тема

|Уведомления отсутствуют.||

|===

[[errata]]
== Уведомления об исправлениях и дополнениях

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Исправление и дополнение |Дата |Тема

|Уведомления отсутствуют.||

|===

[[open-issues]]
== Открытые проблемы

1. Клиент **man:nfs[4]** может вызывать аварийное завершение работы ядра в ситуации, когда сервер NFSv4.1 или NFSv4.2 перестаёт отвечать на запросы или находится в состоянии перезагрузки. После аварийного завершения работы система автоматически перезапустится. +
**Обходное решение**: Избегайте использования параметров монтирования `soft` или `intr` для ресурсов NFSv4.1/4.2. Если аварийное завершение работы происходит часто, рассмотрите возможность перехода на использование NFSv3 до появления исправленной версии. +
**Статус**: Исправлено в ветке main - https://bugs.freebsd.org/294925

2. Загрузка систем, имеющих зашифрованные пулы **man:zfs[4]** с наборами данных `keylocation=prompt`, может застопориться из-за ожидания ввода ключевой фразы, если в **man:rc[8]** активирован скрипт `zfskeys`, хотя ранее монтирование таких пулов пропускалось. +
**Обходное решение**: Используйте `zpool set cachefile=none <pool>`, чтобы при загрузке соответствующий пул не импортировался. +
**Статус**: Открыто - https://bugs.freebsd.org/296130

[[late-news]]
== Актуальные новости

Актуальные новости отсутствуют.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (21.06.2026): a4366bb091ae7ace1d2725a8218666fa29db9197
//
