#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/explaining-bsd/Makefile,v 1.3 2001/07/06 07:46:47 kappa Exp $
#
# Original revision: 1.1
#

MAINTAINER=	kappa@FreeBSD.org.ua

DOC?=	article

FORMATS?=	html

INSTALL_COMPRESSED?=	gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?=	${.CURDIR}/../../..
.include	"${DOC_PREFIX}/share/mk/doc.project.mk"
