# $FreeBSD: www/en/support/Makefile,v 1.1 2005/10/04 05:52:16 murray Exp $

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   bugreports.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
