---
title: "User Groups"
sidenav: community
---

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (24.09.2025): ed9fed7680ffb50fd5735cd6fe6a1454551c19e1
//

= Группы пользователей

Широкая популярность FreeBSD породила ряд групп пользователей по всему миру.

Если вы знаете о группе пользователей FreeBSD, не указанной здесь, пожалуйста, заполните link:../support/bugreports[отчет о проблеме] в категории Documentation->Website со следующей информацией:

. URL-адрес веб-сайта группы пользователей.
. Контактный адрес электронной почты ответственного лица для использования нашими посетителями и администраторами веб-сайта.
. Краткое (один абзац) описание группы пользователей.

В духе FreeBSD мы отдаем предпочтение активным группам пользователей, которые ведут свою деятельность открыто.
Если локальной группы нет, для поиска заинтересованных лиц поблизости можно использовать http://bsd.meetup.com/.

Подумайте о создании собственной группы пользователей!

== Регионы

Группы пользователей FreeBSD можно найти по всему миру, они объединяют энтузиастов и профессионалов, разделяющих страсть к этой универсальной операционной системе.
Присоединяйтесь к группе пользователей FreeBSD в вашем регионе и станьте частью этого vibrant сообщества, устанавливайте связи и учитесь у единомышленников-энтузиастов FreeBSD рядом с вами.

[[europe]]
=== Европа

link:https://bsdstammtisch.at/[Wiener BSD Stammtisch]::
Венский BSD-штаммтиш — это говорящая на английском и немецком языках группа пользователей BSD, расположенная в столице Австрии.
Мы встречаемся раз в месяц для проведения сессии «покажи и расскажи», обсуждений и пары кружек пива.
Идея в том, чтобы улучшать наши навыки и знакомиться с другими энтузиастами BSD.
Не стесняйтесь присоединиться!

link:https://brmlab.cz/groups/start#prague_bsd_group[Prague BSD Group]::
Небольшая группа пользователей BSD из пражского хакерспейса Brmlab, Чехия.
Мы — группа любителей, профессионалов и энтузиастов.

link:http://www.bsd-dk.dk/[BSD-DK]::
Датская группа пользователей BSD.
Продвижение и поддержка операционных систем, производных от BSD, в Дании.
Списки рассылки, лекции и workshops.
Запросы на подписку отправляйте по адресу link:mailto:bsd-dk-request@bsd-dk.dk[bsd-dk-request@bsd-dk.dk].
Расположена в Дании.

link:https://www.AlbaBSD.org[AlbaBUG]::
Албанская группа пользователей BSD — это группа, которая представляет и поддерживает *BSD на албанском языке.
Больше информации доступно на link:https://www.AlbaBSD.org[https://www.AlbaBSD.org].
Расположена в Приштине, Косово.

link:http://www.augusta.de/[Augusta]::
Группа пользователей BSD Augsburger Computer Forum e.V. встречается каждую вторую субботу в 17:00.
Пожалуйста, посетите наш link:http://www.augusta.de/[веб-сайт] для получения дополнительной информации о датах и нашем адресе.
У нас представлены все виды BSD, но в основном FreeBSD и Mac OS X. Расположена в Германии, Аугсбург.

link:http://www.bsdhh.org/bsdhh-de-index.html[BSD User Group Hamburg (BSDHH)]::
Группа пользователей BSD Гамбурга (BSDHH) встречается в первую среду месяца в 19:00 в ресторане _Léon_ (Koppel 1, 20099 Hamburg).
Большинство участников — пользователи FreeBSD, хотя пользователи всех вариантов BSD приветствуются.
Расположена в Германии, Гамбург.

link:https://bsd.nrw/[BSD User Group Düsseldorf/NRW (BSD.NRW)]::
BSD.NRW находится в Дюссельдорфе, Северный Рейн-Вестфалия, Германия.
Мы открыты для всех людей в районе Рейн-Рур, интересующихся семейством BSD.
У нас проходят двухмесячные встречи (всегда во второй вторник этих месяцев).
Предстоящие даты и дополнительная информация можно найти на link:https://bsd.nrw[веб-сайте BSD.NRW].

link:http://www.HappaBSD.de/[HappaBSD Regensburg]::
HappaBSD — это регулярные встречи, проходящие каждый месяц в Регенсбурге, Бавария, Германия.
Для получения дополнительной информации см. link:http://www.HappaBSD.de/[веб-сайт HappaBSD].

link:https://www.uugrn.org/[Unix Users Group Rhein-Neckar e.V. (UUGRN e.V.)]::
Группа пользователей Unix Рейн-Неккар e.V. (UUGRN e.V.) предоставляет региональный форум для пользователей всех вариантов Unix с акцентом на Linux и BSD.
link:https://stammtisch.uugrn.org/[Встречи (UnixUserStammtisch)] проводятся в третий понедельник каждого месяца.
link:https://fixme.uugrn.org/[Практическая встреча FIXME] проходит каждую первую пятницу месяца.
Расположена в Германии, link:https://rhein-neckar-wiki.de/[регион Рейн-Неккар], Гейдельберг.
Все мероприятия анонсируются в X link:https://twitter.com/uugrn[@uugrn].

link:http://berklix.org/bim/[Berkeley in Munich (BIM)]::
Berkeley in Munich (BIM) обслуживает пользователей систем на базе BSD в Верхней Баварии.
Расположена в Германии, Мюнхен.

link:http://www.u-bus.de[Ulmer BSD User Stammtisch]::
U-BUS встречается каждый последний четверг месяца.
Для получения дополнительной информации о встречах и связанных вопросах, пожалуйста, проверьте веб-страницу (link:http://www.u-bus.de[u-bus]).
Расположена в Германии, Ульм.

link:http://www.bluefrogs.de/[Bluefrogs e.V.]::
Группа пользователей Unix и Linux в Бергиш-Гладбахе (близ Кёльна), Германия.
Встречи проводятся два раза в месяц.
Мы работаем со всеми производными Open Source Unix: FreeBSD, NetBSD, OpenBSD, Linux и другими.
Мы проводим workshops, лекции, доклады и установочные вечеринки.
Для получения дополнительной информации напишите нам по адресу: link:mailto:info@bluefrogs.de[info@bluefrogs.de].

link:http://bse.42.org/[BSE München]::
BSE (BSD Social Event) находится в Мюнхене, Германия.
Не стесняйтесь посещать наши регулярные встречи (каждые четыре недели) или присоединяйтесь к списку рассылки.
Для получения дополнительной информации посетите link:http://bse.42.org/[веб-сайт BSE].

link:http://www.fug-fr.org/[FUG-FR]::
Группа пользователей FreeBSD Франции (FUG-FR) — это группа энтузиастов FreeBSD во Франции, в настоящее время занимающаяся переводом маркетинговых материалов и т.д.
Они также активно помогают в проведении FOSDEM (проводится в Брюсселе).
Для получения дополнительной информации посетите нашу веб-страницу link:http://www.fug-fr.org/[http://www.fug-fr.org] или свяжитесь с link:mailto:rodrigo@bebik.net[Родриго Осорио].

link:https://www.meetup.com/Dublin-BSD-User-Group/[Dublin BSD User Group]::
Дублинская группа пользователей BSD — это коллектив людей, интересующихся применением BSD в производственных сценариях.
Нас интересует, как BSD могут помочь как системным администраторам, так и разработчикам приложений развертывать и управлять надежными решениями, а также изучение некоторых уникальных особенностей BSD.
Для получения дополнительной информации посетите наш link:https://www.meetup.com/Dublin-BSD-User-Group/[веб-сайт].

link:http://www.lissyara.su[Lissyara.su]::
Мы — русскоязычное сообщество FreeBSD.
На нашем сайте представлены несколько статей по настройке FreeBSD и различных других приложений.
В дополнение к статьям мы также предоставляем link:http://forum.lissyara.su/[форум пользователей], где опытные пользователи FreeBSD рады помочь другим пользователям.

link:http://bsdportal.ru[Russian FreeBSD User Group (RFUG)]::
Российская группа пользователей FreeBSD (RFUG) — это ориентированная на русский язык группа пользователей для русскоязычных пользователей и пользователей из стран бывшего СССР.
Расположена в России.

link:http://www.ulbsd.ru/[Ulyanovsk FreeBSD Users Group]::
Ульяновская группа пользователей FreeBSD (ULBSD) предназначена для русскоязычных пользователей операционной системы ULBSD, основанной на FreeBSD.
Мы предоставляем бесплатные и платные версии нашей операционной системы.
Мы также бесплатно отвечаем на множество вопросов пользователей и помогаем им работать в FreeBSD и ULBSD.
Для получения дополнительной информации отправьте электронное письмо по адресу link:mailto:info@ulbsd.ru[info@ulbsd.ru] или посетите веб-сайт по адресу link:http://www.ulbsd.ru/[http://www.ulbsd.ru/].
Расположена в Ульяновске, Россия.

link:http://www.gufi.org/[Gruppo Utenti FreeBSD Italia (GUFI)]::
Gruppo Utenti FreeBSD Italia (GUFI) — это группа пользователей FreeBSD с итальянским акцентом.
Она предназначена для помощи итальянским пользователям FreeBSD в поиске поддержки и статей о FreeBSD на итальянском языке.
Пожалуйста, перейдите по этой link:http://www.gufi.org/[ссылке], чтобы узнать больше о нас.
Расположена в Италии.

link:http://www.bug.lv[BSD User Group Latvia]::
Чтобы узнать больше о группе пользователей BSD Латвии, пожалуйста, посетите наш link:http://www.bug.lv/[сайт] и наши link:http://www.bug.lv/[форумы].
Расположена в Латвии.

link:http://www.nobug.no/[The Norwegian BSD User Group (NOBUG)]::
Норвежская группа пользователей BSD (NOBUG) — это группа пользователей для пользователей и энтузиастов BSD в Норвегии.
Встречи в настоящее время проводятся в Осло и Бергене.
Посетите наш веб-сайт для получения дополнительной информации. Также существует Группа пользователей Unix (link:http://www.nuug.no/[NUUG]) с более регулярными встречами, иногда даже на тему BSD. Расположена в Норвегии.

link:https://bsd-pl.org/[Polish BSD User Group]::
Наша группа была создана для продвижения систем семейства BSD в Польше.
Мы организуем встречи, объединяющие любителей Unix-систем.
Расположена в Варшаве.

link:https://www.sbug.org/[SBUG]::
SBUG — это группа пользователей *BSD, базирующаяся в Жешуве и ориентированная на Подкарпатское воеводство.

link:mailto:ptbsd@yahoo.com[The Portuguese *BSD Users Group]::
Португальская группа пользователей *BSD — это группа пользователей для португальских пользователей операционных систем BSD.
Свяжитесь с Руи Перейра link:mailto:ptbsd@yahoo.com[ptbsd@yahoo.com] для получения дополнительной информации.
Расположена в Португалии, Амадора.

link:https://bsd.si/[BSD User Group Slovenia]::
Группа пользователей BSD Словении объединяет пользователей систем BSD в Словении.
Участники группы также общаются на IRC-канале ##bsd.si в сети Libera Chat.
Расположена в Любляне, Словения.

link:http://www.bsd.hu/[The Hungarian BSD Group]::
Венгерская группа BSD — это группа пользователей NetBSD, FreeBSD и OpenBSD, расположенная в Венгрии.
Их встречи проходят во вторую пятницу месяца.
Веб-сайт группы: link:http://www.bsd.hu/[http://www.bsd.hu/].

link:https://lists.stacken.kth.se/mailman/listinfo/bus[BSD Users Sweden (BUS)]::
Группа пользователей BSD Швеции (BUS) поддерживает список рассылки.
Чтобы присоединиться, отправьте электронное письмо на link:mailto:majordomo@stacken.kth.se[majordomo@stacken.kth.se] с текстом `subscribe bus` в теле письма.
Расположена в Швеции.

link:http://www.bsdgroups.org.uk/manchester[Manchester BSD Users Group]::
Манчестерская группа пользователей BSD встречается достаточно часто в пабе Lass O'Gowrie на Чарльз-стрит, Манчестер.
Свяжитесь с link:mailto:sams@bsdgroups.org.uk[Сэмом Смитом] для получения дополнительной информации.
Расположена в Великобритании, Манчестер.

link:http://mailman.uk.freebsd.org/mailman/listinfo/ukfreebsd[FreeBSD UK Users group (FreeBSD UKUG)]::
Группа пользователей FreeBSD Великобритании (FreeBSD UKUG) существует для пользы пользователей FreeBSD в Соединенном Королевстве.
Пожалуйста, перейдите по ссылке для получения дополнительной информации.
Расположена в Великобритании.

link:https://twitter.com/bsdbelfast[The BSD in Belfast Group]::
Встречайтесь с группой BSD Белфаста в третью пятницу месяца.
Мы — группа академических и промышленных пользователей и поклонников BSD.

link:https://freebsd.web.tr/[FreeBSD Türkiye]::
Мы — сообщество энтузиастов и профессионалов FreeBSD, посвятивших себя поддержке и развитию систем FreeBSD.
Наша группа активно занимается написанием документации, внесением кода и проведением исследований для улучшения экосистемы FreeBSD.
Будь вы опытный разработчик или только начинаете работать с FreeBSD, присоединяйтесь к нам в содействии сотрудничеству и инновациям в сообществе FreeBSD Турции.

link:https://ossmalta.eu/[Open Source Society Malta]::
Общество открытого исходного кода Мальты — это локальное сообщество для инициативы открытого исходного кода на Мальте, поддерживающее энтузиастов и профессионалов открытого исходного кода.

[[north-america]]
=== Северная Америка

link:http://sites.google.com/site/bugortn/Home[BSD User Group Oak Ridge (BUGOR)]::
BUGOR — это открытая и свободная сеть пользователей BSD в районе Ок-Ридж, Теннесси.
В идеале, профессиональные системные администраторы, программисты и бывалые хакеры будут встречаться каждую неделю, чтобы исследовать и обсуждать тонкости философии дизайна Unix и искусство программирования в Unix, одновременно наставляя начинающих пользователей и реабилитируя пользователей WIMP.

link:http://www.buug.org[The Berkeley Unix User Group]::
Группа пользователей Unix Беркли — это общая группа пользователей Unix для всех в районе залива Сан-Франциско.
Мы встречаемся еженедельно в центре Беркли.
Посетите веб-сайт или отправьте сообщение на link:mailto:buug-request@weak.org[buug-request@weak.org] с текстом `subscribe` в теле письма.
Расположена в Беркли, Калифорния.

link:http://lists.nycbug.org/mailman/listinfo/cdbug-talk[The Capitals District *BSD Users Group]::
Группа пользователей *BSD столичного округа (The Capitals District *BSD Users Group) черпает своих членов из столичного округа Нью-Йорка и окружающих сообществ.
CDBUG была основана в декабре 2004 года и имеет небольшое, но растущее членство.
В настоящее время мы встречаемся в последнее воскресенье каждого месяца в районе Олбани.
Наш список рассылки любезно размещается NYCBUG по адресу: link:http://lists.nycbug.org/mailman/listinfo/cdbug-talk[http://lists.nycbug.org/mailman/listinfo/cdbug-talk].
Расположена в Олбани, Нью-Йорк.

link:https://www.meetup.com/CharmBUG[Baltimore Area BSD Operating System User Group (CharmBUG)]::
CharmBUG — это группа пользователей операционных систем BSD в районе Балтимора, где основное внимание уделяется FreeBSD, OpenBSD, NetBSD и DragonFly BSD, включая системное администрирование и безопасность во всех UNIX-подобных операционных системах.
Пожалуйста, свяжитесь с link:mailto:shirkdog@gmail.com[shirkdog@gmail.com] для получения подробностей.

link:http://ufo.chicago.il.us[The Users of Free Operating Systems (UFO Chicago)]::
Пользователи свободных операционных систем (UFO Chicago) — это группа пользователей Unix с открытым исходным кодом, которая встречается два раза в месяц в Чикаго.
Для получения указаний и информации о списке рассылки, пожалуйста, проверьте наш веб-сайт link:http://ufo.chicago.il.us[http://ufo.chicago.il.us].
Чикаго, Иллинойс.

link:http://cobug.org[The Colorado BSD Users Group (CoBUG)]::
Созданная в 2014 году, CoBUG — это полностью открытое сообщество BSD, созданное с целью распространения любви к BSD.
Расположена в Колорадо.

link:https://hambug.ca[HamBUG]::
Группа пользователей BSD Гамильтона (Онтарио, Канада) встречается во второй вторник каждого месяца.
Встречи включают открытые обсуждения, короткие демонстрации и время для вопросов и ответов.
Пользователи со всего GTA (район Большого Торонто), Лондона и Ватерлоо регулярно посещают встречи.

link:http://knoxbug.org[KnoxBUG]::
Группа пользователей BSD Ноксвилла, Теннесси (KnoxBUG) встречается раз в месяц.
Для получения дополнительной информации посетите link:http://knoxbug.org[http://knoxbug.org] и/или подпишитесь на наш link:http://lists.nycbug.org/mailman/listinfo/knoxbug-talk[список рассылки].

link:mailto:majordomo@swcp.com[NMLUG]::
NMLUG в Альбукерке встречается раз в месяц и поддерживает пользователей как BSD, так и Linux.
Чтобы присоединиться к списку рассылки, отправьте сообщение на link:mailto:majordomo@swcp.com[majordomo@swcp.com] с текстом `subscribe nmlug` в теле письма.
Расположена в Нью-Мексико.

link:http://www.nycbug.org[New York City *BSD User Group (NYCBUG)]::
Группа пользователей *BSD Нью-Йорка (NYCBUG) встречается в первую среду месяца.
Списки рассылки доступны по адресу link:http://lists.nycbug.org[http://lists.nycbug.org].
Расположена в Нью-Йорке, Нью-Йорк.

link:mailto:rcarter@consys.com[Yavapai Free Unix Users Group]::
Группа пользователей свободного Unix Явапаи (Yavapai Free Unix Users Group) сейчас формируется для пользователей *BSD/Linux и т.д. в Северной Аризоне.
Пожалуйста, свяжитесь с Расселом Картером (link:mailto:rcarter@consys.com[rcarter@consys.com]) для получения подробностей.
Расположена в Северной Аризоне.

link:http://www.wplug.org[Western Pennsylvania Linux Users Group (WPLUG)]::
Группа пользователей Linux Западной Пенсильвании (WPLUG) имеет сильное и растущее сообщество пользователей BSD, которое она поддерживает.
Смотрите нашу домашнюю страницу (link:http://www.wplug.org[http://www.wplug.org]) для получения информации о регулярных встречах и присоединяйтесь к спискам рассылки.
Расположена в Пенсильвании.

link:mailto:pdx-freebsd@toybox.placo.com[Portland (Oregon) FreeBSD Users Group]::
Группа пользователей FreeBSD Портленда (Орегон) встречается в третий четверг каждого месяца.
Пишите на link:mailto:pdx-freebsd@toybox.placo.com[адрес группы пользователей FreeBSD Портленда].
Расположена в Портленде, Орегон.

link:http://www.rlug.org[Reno Linux Users Group (RLUG)]::
Группа пользователей Linux Рено (RLUG) собирается ежемесячно в Рено, Невада, и обсуждает использование BSD и Linux.
Посетите link:http://www.rlug.org[наш веб-сайт] для получения дополнительной информации, где вы также можете присоединиться к нашему списку рассылки.
Расположена в Рено, Невада.

link:http://www.seabug.org[Seattle BSD Users Group (SeaBUG)]::
Группа пользователей BSD Сиэтла (SeaBUG) встречается время от времени. Посетите наш веб-сайт для получения более подробной информации и сведений о том, как присоединиться к нашему списку рассылки.
Расположена в Сиэтле, Вашингтон.

link:https://sdbug.org/[San Diego BSD Users Group (SDBUG)]::
Группа пользователей BSD Сан-Диего (SDBUG) встречается в первый четверг каждого месяца, обычно в пивоварне AleSmith на Мирамар-Роуд.
Сверяйтесь с link:https://sdbug.org/[веб-сайтом] и списками рассылки для уточнения деталей.
Расположена в Сан-Диего, Калифорния.

link:http://www.tfug.org[Tucson Free Unix Group (TFUG)]::
Группа пользователей свободного Unix Тусона, Аризона. Расположена в Тусоне, Аризона.

link:http://www.su3g.org[The Southern Utah Unix Users Group (SU3G)]::
Группа пользователей Unix Южной Юты (SU 3 G, SU^3G, SU3G или SUUUG) предназначена для пользователей любой версии Unix или Unix-подобной операционной системы, коммерческой или с открытым исходным кодом.
Так что, используете ли вы FreeBSD, Linux, Mac OS X, BSD/OS, Solaris, OpenBSD или любую другую ОС Unix или Unix-подобную, и если вы живете, работаете или общаетесь с кем-то, кто живет или работает в юго-западной Юте, тогда рассмотрите возможность присоединения к SU 3 G.
Для получения дополнительной информации отправьте электронное письмо на link:mailto:kendall@su3g.org[kendall@su3g.org] или посетите веб-сайт по адресу link:http://www.su3g.org/[http://www.su3g.org/].

link:http://capbug.org[Capital Area BSD Users Group]::
Мы встречаемся в последний вторник месяца.
Присоединяйтесь к нашему link:http://groups.google.com/group/capbug[списку рассылки] или посетите наш веб-сайт link:http://www.capbug.org[здесь].
Мы встречаемся в Мэриленде, но приветствуем всех из Мэриленда, округа Колумбия или Вирджинии.

link:http://www.kcbug.org[Kansas City Area *BSD User.s Group]::
Мы — начинающаяся группа пользователей BSD, в настоящее время состоящая из двух участников.
Если вы хотите присоединиться, пожалуйста, посетите наш веб-сайт link:http://www.kcbug.org/[здесь].
Наши цели — получать удовольствие, помогать другим изучать и использовать *BSD и пропагандировать операционные системы BSD.

link:http://www.gtabug.ca[GTABUG]::
Группа пользователей GTABUG приветствует всех пользователей BSD.
Ежемесячные встречи дают участникам возможность делиться идеями, обсуждать и обмениваться информацией.
Установки и другие мероприятия помогают нести благую весть о BSD сообществу.
Заходите на встречу! Расположена в районе Большого Торонто, Онтарио.

link:http://www.ocbug.ca/[Ottawa-Carleton Unix Users Group]::
Мы — небольшая группа энтузиастов, пользователей, авторов, системных администраторов и хакеров, которые встречаются ежемесячно для обсуждения последних тем в очень неформальной обстановке.
Проверяйте наш link:http://mail.ocbug.ca/mailman/listinfo/ocbug_ocbug.ca[список рассылки] для получения самой свежей информации.
Расположена в Оттаве, Онтарио.

link:https://www.orlandobsd.org/[The Orlando BSD Users Group]::
Небольшая группа пользователей BSD из района Большого Орландо в центральной Флориде.
Мы — группа компьютерных энтузиастов, ИТ-профессионалов и энтузиастов мейкерспейсов.

[[south-america]]
=== Южная Америка

link:http://www.bsd.cl/[BSD Chile]::
Группа пользователей BSD Чили (bsd.cl) поддерживает зеркала, документы и списки рассылки для чилийского сообщества BSD.
Группа также предоставляет инфраструктуру для мероприятий BSD в Чили, и с ней можно связаться на IRC-сервере irc.bsd.cl #BSD в дополнение к link:www.bsd.cl[веб-сайту].

link:https://www.fug.com.br/[The Brazilian FreeBSD User Group (FUG-BR)]::
Бразильская группа пользователей FreeBSD (FUG-BR) — это ориентированная на португальский язык группа пользователей, предназначенная для помощи бразильским пользователям FreeBSD в поиске поддержки и статей о FreeBSD на португальском языке.
Мы поддерживаем несколько проектов, таких как link:https://sourceforge.net/projects/livecd/[FreeBSD LiveCD].
В настоящее время в группе более 800 участников, и наш список рассылки имеет среднюю нагрузку 80 сообщений в день.
Чтобы присоединиться к списку рассылки FUG-BR, посетите https://www.fug.com.br/mailman/listinfo/www

[[asia]]
=== Азия

link:https://www.kbug.gr.jp/[The Kansai *BSD Users Group (K*BUG)]::
Группа пользователей *BSD Кансай была основана 13 ноября 1999 года.
Она призвана способствовать общению пользователей любых вариантов BSD.
Некоторые из ее мероприятий — проведение дружеских встреч участников и проведение семинаров, охватывающих широкий круг тем.
Пожалуйста, напишите сюда (link:mailto:kbug-admin@kbug.gr.jp[kbug-admin@kbug.gr.jp]).
Расположена в Кансай, Япония.

link:https://www.ebug.jp/[The Echigo BSD Users Group (EBUG)]::
Группа пользователей BSD Этиго (EBUG) — это группа пользователей для пользователей BSD в районе Этиго (также известном как Ниигата).
Для получения дополнительной информации о наших мероприятиях и списках рассылки, пожалуйста, проверьте веб-сайт EBUG.

link:mailto:22961476@students.ukdw.ac.id[The Jogja FreeBSD Users Group]::
Группа пользователей FreeBSD Джокьякарты базируется в городе Джокьякарта, Индонезия.
Отправьте электронное письмо на 22961476@students.ukdw.ac.id для получения дополнительной информации.

link:http://www.meetbsd.ir[meetBSD Iran]::
meetbsd.ir — это иранская группа пользователей BSD, которая предоставляет конференции, iso, электронные книги и PKG для местных пользователей BSD.

link:http://www.mybsd.org.my[The MyBSD Malaysia Project]::
Проект MyBSD Малайзии — это базирующаяся в Куала-Лумпуре группа пользователей для пользователей BSD и открытого исходного кода в целом, продвигающая и поддерживающая использование FreeBSD, OpenBSD, NetBSD и открытого исходного кода.
Мы встречаемся раз в месяц, обычно в Университете Малайя или в ресторане Бахадур Шах.
Один из наших проектов — разработка link:http://staff.mybsd.org.my/skywizard/bsd-explorer[файлового менеджера Unix].
Посетите наш веб-сайт или свяжитесь с link:mailto:info@mybsd.org.my[info@MyBSD.org.my] для получения дополнительной информации.

link:http://ndbug.in[New Delhi BSD User Group]::
Группа пользователей BSD Нью-Дели (NDBUG) — это группа энтузиастов, профессионалов и любителей.
Наши участники разделяют интересы в BSD Unix и свободных реализациях Unix, а также в другом программном обеспечении с открытым исходным кодом.
NDBUG была основана для распространения знаний о BSD Unix, программном обеспечении с открытым исходным кодом и связанных технологиях и интересах в Индии и, в частности, в Нью-Дели.

link:https://bsdtw.org/[BSD Taiwan]::
BSD Taiwan — это группа пользователей BSD для тайваньских пользователей BSD, где мы можем делиться знаниями, идеями и искать помощи.
Для получения дополнительной информации посетите наш link:https://bsdtw.org[веб-сайт].

link:https://ambug.org[Armenia BSD User Group]::
Мы — сообщество хакеров BSD, системных администраторов Unix и пользователей Unix-подобных систем, которые собираются раз в месяц (онлайн и оффлайн) для обсуждения тем, связанных с BSD Unix.

link:https://arbian.org[Saudi Arabia BSD User Group]::
Сообщество открытого исходного кода Arbian в Саудовской Аравии, *BSD является частью сообщества, представляет и поддерживает арабский язык.

[[oceania]]
=== Океания

link:https://www.humbug.org.au/[Home Unix Users Group for Brisbane]::
Мы встречаемся раз в две недели в переговорных комнатах, предоставляемых link:http://www.uq.edu.au/[Университетом Квинсленда].
Больше информации, включая способы присоединения к спискам рассылки, доступно на link:http://www.humbug.org.au/[http://www.humbug.org.au].
Расположена в Квинсленде.

link:mailto:majordomo@lemis.com[BUGA, The BSD User Group of Adelaide]::
Мы встречаемся через нерегулярные промежутки времени.
Присоединяйтесь к списку рассылки, отправив сообщение на link:mailto:majordomo@lemis.com[majordomo@lemis.com] с текстом `subscribe BUGA` в теле письма.
Расположена в Южной Австралии.

link:http://www.bugs.au.FreeBSD.org/[BSD Users Group, Sydney (BUGS)]::
Группа пользователей BSD Сиднея (BUGS) время от времени встречается в Сиднее и его окрестностях.
У нас есть участники со всего штата Новый Южный Уэльс.
Чтобы присоединиться к списку рассылки или IRC-каналу, посетите link:http://www.bugs.au.freebsd.org/[http://www.bugs.au.freebsd.org/].
Расположена в Новом Южном Уэльсе.

[[global]]
=== Глобальные

link:https://metabug.org/[The Global BSD User Groups]::
Организация глобальных групп пользователей BSD была основана для помощи в продвижении местных групп пользователей BSD путем обмена идеями и опытом с другими организациями BUG.
Наши цели: Мы работаем над способами обеспечения удаленного участия через потоковое видео презентаций.
Вы можете проверить наш link:https://metabug.org/[веб-сайт] или связаться с нами через link:mailto:info@metabug[электронную почту].
