# $Id: Makefile,v 1.1 1998-06-19 09:46:48 wosch Exp $

.if exists(Makefile.conf)
.include "Makefile.conf"
.endif

DOCS=  
DOCS+=	programmers.sgml
DOCS+=	security.sgml
DOCS+=  secure.sgml

.include "../web.mk"
