# $FreeBSD: www/en/releases/4.8R/Makefile,v 1.2 2003/02/19 15:13:01 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml todo.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
