---
title: "FreeBSD 3.5 Announcement"
sidenav: download
--- 

= FreeBSD 3.5 Announcement

*Date:* Sat, 24 Jun 2000 18:23:01 -0700 +
*From:* "Jordan K. Hubbard" <jkh@freebsd.org> +
**Subject:**FreeBSD 3.5 now available for x86

I'm pleased to announce the availability of FreeBSD 3.5-RELEASE, the very LAST in 3.x-STABLE branch technology. Following the release of FreeBSD 3.4 in December, 1999, many bugs were fixed, important security issues dealt with, and even a few new features added. Please see the link:../notes[release notes] for more information.

FreeBSD 3.5-RELEASE is available at ftp://ftp.FreeBSD.org/pub/FreeBSD/[ftp.FreeBSD.org] and various https://www.FreeBSD.org/handbook/mirrors.html[FTP mirror sites] throughout the world. It can also be ordered on CD from http://www.FreeBSDMall.com/[The FreeBSD Mall], from where it will be shipping soon on a 4 CD set containing installation bits for x86 architecture, as well as a lot of other material of general interest to programmers and end-users alike

We can't promise that all the mirror sites will carry the rather large installation (660MB) image, but it will at least be available from:

ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/ISO-IMAGES/3.5-install.iso

along with the more traditional 3.5-RELEASE bits. If you can't afford the CDs, are impatient, or just want to use it for evangelism purposes, then by all means download the ISO, otherwise please do continue to support the FreeBSD project by purchasing one of its official CD releases from BSDi.

The official FTP distribution site for FreeBSD is:

____
ftp://ftp.FreeBSD.org/pub/FreeBSD/
____

Or via the WEB pages at:

____
http://www.FreeBSDMall.com/ and +
http://www.freebsd.org/[http://www.freebsd.org]
____

And directly from BSDi:

____
BSDi +
4041 Pike Lane, #F +
Concord CA, 94520 USA +
Phone: +1 925 674-0783 +
Fax: +1 925 674-0821 +
Email: info@cdrom.com +
WWW: http://www.cdrom.com/
____

Additionally, FreeBSD is available via anonymous FTP from https://www.FreeBSD.org/handbook/mirrors.html[mirror sites] in the following countries: Argentina, Australia, Brazil, Bulgaria, Canada, the Czech Republic, Denmark, Elbonia, Estonia, Finland, France, Germany, Hong Kong, Hungary, Iceland, Ireland, Israel, Japan, Korea, Latvia, Malaysia, the Netherlands, Poland, Portugal, Rumania, Russia, Slovenia, South Africa, Spain, Sweden, Taiwan, Thailand, the Ukraine and the United Kingdom (and quite possibly several others which I've never even heard of :).

Before trying the central FTP site, please check your regional mirror(s) first by going to:

ftp://ftp.<yourdomain>.freebsd.org/pub/FreeBSD

Any additional mirror sites will be labeled ftp2, ftp3 and so on.

The latest versions of export-restricted code for FreeBSD (2.0C or later) (eBones and secure) are also being made available at the following locations. Now that FreeBSD has export permission for crypto from the United States government, you can get it from these locations or from ftp.freebsd.org.

South Africa::
  ftp://ftp.internat.FreeBSD.ORG/pub/FreeBSD +
  ftp://ftp2.internat.FreeBSD.ORG/pub/FreeBSD
Brazil::
  ftp://ftp.br.FreeBSD.ORG/pub/FreeBSD
Finland::
  ftp://nic.funet.fi/pub/unix/FreeBSD/eurocrypt

Thanks!

- Jordan

link:../../[Release Home]
