---
title: Como obter os melhores resultados da lista de email FreeBSD-questions
authors:
  - author: Greg Lehey
    email: grog@FreeBSD.org
releaseinfo: "$FreeBSD$" 
trademarks: ["freebsd", "microsoft", "opengroup", "qualcomm", "general"]
---

= Como obter os melhores resultados da lista de email FreeBSD-questions
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:toc-title: Índice
:part-signifier: Parte
:chapter-signifier: Capítulo
:appendix-caption: Apêndice
:table-caption: Tabela
:figure-caption: Figura
:example-caption: Exemplo

include::shared/pt-br/urls.adoc[]

[.abstract-title]
Resumo

Este documento provê informação para pessoas que desejam mandar um email para a lista de discussão FreeBSD-questions. Avisos e dicas são disponibilizados para maximizar a chance do leitor de receber respostas úteis.

Esse documento é regularmente postado na lista de email FreeBSD-questions.

'''

toc::[]

== Introdução

A `FreeBSD-questions` é uma lista de emails mantida pelo Projeto FreeBSD para ajudar pessoas que tenham questões sobre o uso normal do FreeBSD. Outra lista, a `FreeBSD-hackers`, aborda questões mais avançadas tais como desenvolvimentos futuros.

[NOTE]
====
O termo "hacker" não tem nada a ver com invasão de computadores alheios.O termo correto para este tipo de atividade é "cracker", mas a mídia popular e a imprensa não tomou conhecimento deste fato ainda. Os hackers do FreeBSD fortemente desaprovam a atividade de cracking e não se envolvem neste tipo de atividades. Para uma descrição mais abrangente sobre hackers, veja o link de Eric Raymond's http://www.catb.org/~esr/faqs/hacker-howto.html[How To Become A Hacker]
====

Esta é uma mensagem padrão com vistas a ajudar tanto quem busca ajuda na lista FreeBSD-questions (os "novatos"), quanto quem responde às questões (os "hackers").

Inevitavelmente sempre existe algum atrito, o qual deriva dos diferentes pontos de vista dos dois grupos. Os novatos acusam os hackers de serem arrogantes, orgulhosos e não ajudarem, enquanto os hackers acusam os novatos de serem burros, incapazes de lerem textos em simples Português, e esperarem que tudo seja dado a eles em uma bandeja de prata. Claro que há algum elemento de verdade em cada um dos discursos, mas normalmente estes pontos de vista são frutos de algum tipo de frustração.

Nesse documento, eu desejo fazer algo para aliviar essa frustração e ajudar todos a obterem melhores resultados da FreeBSD-questions. Na próxima seção, eu recomendo como enviar uma pergunta; depois disso, veremos como responder a uma.

== Como se Inscrever na FreeBSD-questions

A FreeBSD-questions é uma lista de email, então você precisa de uma conta de email. Aponte o seu navegador Web para a http://lists.FreeBSD.org/mailman/listinfo/freebsd-questions[página de informações da lista FreeBSD-questions]. Na seção entitulada "Inscrevendo-se na freebsd-questions" preencha o campo "Seu endereço de email"; os demais campos são opcionais.

[NOTE]
====
O campo para senha no formulário de inscrição proporciona somente uma segurança moderada, mas deve evitar que outros enviem mensagens usando sua conta. _Não use uma senha importante para você_ pois ela eventualmente poderá ser enviada para você por email em texto plano.
====

Você receberá uma mensagem de confirmação do mailman; siga as instruções incluídas na mensagem para completar sua inscrição.

Finalmente, quando você receber a mensagem de "Boas-vindas" do mailman informando os detalhes da lista e a senha para acesso à área restrita, __por favor salve-a__. Se você algum dia desejar sair da lista, você necessitará das informações contidas nesta mensagem. Veja a próxima seção para mais detalhes.

== Como sair da lista FreeBSD-questions

Quando você se inscreve na lista FreeBSD-questions, você recebe uma mensagem de boas-vindas do mailman. Nessa mensagem, dentre outras coisas, é informado como sair da lista. Segue um exemplo desta mensagem:

....
Bem-vindo à lista de discussão freebsd-questions@freebsd.org!

Para enviar uma mensagem para esta lista, mande seu email para:

  freebsd-questions@freebsd.org

Informações gerais sobre a lista estão em:

  https://lists.freebsd.org/mailman/listinfo/freebsd-questions

Se você eventualmente desejar sair da lista ou alterar suas opções (ex. mudar
para o modo resumo diário ou para sair dele, mudar senha, etc.) visite sua página de
inscrição em:

https://lists.freebsd.org/mailman/options/freebsd-questions/grog%40lemsi.de

Você pode também fazer estes ajustes por email, enviando uma mensagem para:

  freebsd-questions-request@freebsd.org

com a palavra 'help' no campo assunto ou no corpo da mensagem (não inclua
as aspas), e você receberá uma mensagem com instruções.

Você precisa saber sua senha para alterar as opções (incluindo alterar a 
própria senha) ou para sair da lista. Ela é:

  12345

Normalmente, Mailman lembrará você de sua senha na lista do freebsd.org
uma vez por mês, mas você pode desabilitar isto se assim desejar. Este 
lembrete também incluirá instruções de como sair da lista ou alterar 
suas preferências de conta. Há também um botão na sua página de opções 
que enviará sua senha atual para você.
....

A partir da URL informada na sua mensagem de "Boas-vindas" você pode visitar a "Página de gerenciamento da sua conta" e fazer uma requisição para "Sair" da lista FreeBSD-questions.

Uma mensagem de confirmação será enviada para você pelo mailman; siga as instruções contidas na mensagem para finalizar o desligamento da lista.

Se você já fez isso, e ainda não conseguiu entender o que está havendo, mande uma mensagem para mailto:freebsd-questions-request@FreeBSD.org[freebsd-questions-request@FreeBSD.org], e eles irão resolver as coisas para você. _Não envie_ uma mensagem para a FreeBSD-questions: eles não podem ajudá-lo.

== Devo perguntar na lista `-questions` ou na `-hackers`?

Duas listas de discussão abordam questões gerais sobre o FreeBSD, `FreeBSD-questions` e `FreeBSD-hackers`. Em alguns casos, não é realmente claro para qual lista você deve enviar sua pergunta. Entretanto, os seguintes critérios devem ajudar em 99% de todas as perguntas:

. Se a questão é genérica, pergunte na `FreeBSD-questions`. Como exemplo temos questões sobre a instalação do FreeBSD ou o uso de uma ferramenta doUNIX(R).
. Se você acredita que a pergunta está relacionada a um bug, mas não tem certeza disso, ou você não sabe como pesquisar sobre isso, mande a mensagem para a lista `FreeBSD-questions`.
. Se você acredita que a pergunta está relacionada com um bug, e você tem _certeza_ que é um bug (por exemplo, você pode apontar o lugar do código onde isso acontece, e você poder ter uma correção para o problema), então envie a mensagem para a lista `FreeBSD-hackers`.
. Se a questão envolve melhoramentos no FreeBSD, e você pode sugerir em como isto pode ser implementado, então mande a menssagem para a lista `FreeBSD-hackers`.

Há também uma boa quantidade de link:{handbook}#eresources-mail[listas de email especializadas], que atendem interesses mais específicos. O critério acima ainda se aplica, e é interessante que você o siga, pois há mais chance de você obter melhores resultados desta forma.

== Antes de Enviar uma Pergunta

Você pode (e deve) fazer algumas coisas você mesmo antes de fazer uma pergunta em uma das listas de discussão:

* Tente resolver o problema sozinho. Se você enviar uma pergunta que demonstre que você tentou resolver o problema, sua mensagem vai normalmente atrair mais atenção de uma forma positiva das pessoas que a leram. Tentar resolver o problema sozinho também vai aumentar seu entendimento do FreeBSD, e eventualmente vai proporcionar conhecimento para você poder responder perguntas de outros usuários das listas e também ajudar.
* Leia as páginas dos manuais, e a documentação do FreeBSD (tanto a instalada em [.filename]#/usr/doc# ou a versão acessível via Web em http://www.FreeBSD.org[http://www.FreeBSD.org]), especialmente o link:{handbook}[handbook] e o link:{faq}[FAQ].
* Procure e/ou pesquise nos arquivos da lista de discussão, para verificar se a sua pergunta ou uma pergunta semelhante já foi feita (e possivelmente respondida) antes na lista. Você pode navegar e/ou pesquisar os arquivos da lista de discussão em https://www.FreeBSD.org/mail[https://www.FreeBSD.org/mail] e https://www.FreeBSD.org/search/#mailinglists[https://www.FreeBSD.org/search/#mailinglists], respectivamente. Isso pode ser feito em outros sites da Web, como por exemplo, em http://marc.theaimsgroup.com[http://marc.theaimsgroup.com].
* Use um mecanismo de pesquisa como o http://www.google.com[Google] ou http://www.yahoo.com[Yahoo] para encontrar respostas para a sua pergunta.

== Como Enviar uma Pergunta

Quando for enviar uma pergunta para a lista FreeBSD-questions, considere as seguintes diretivas:

* Lembre-se que ninguém é pago por responder uma pergunta sobre o FreeBSD. Eles fazem isso por vontade própria. Você pode influenciar positivamente esse livre arbítrio enviando uma pergunta bem formulada, fornecendo o máximo possível de informações relevantes. Você pode influenciar esse livre arbítrio negativamente enviando uma pergunta incompleta, ilegível ou grosseira. É perfeitamente possível enviar uma mensagem para a lista FreeBSD-questions e não obter uma resposta, mesmo que você siga estas regras. É muito mais fácil não obter uma resposta se você não o fizer. No restante deste documento, veremos como tirar o máximo proveito de uma pergunta para a FreeBSD-questions.
* Nem todo mundo que responde as perguntas sobre o FreeBSD lê todas as mensagens: eles olham para o assunto e decidem se isso lhes interessa. Claramente, é do seu interesse especificar um assunto. Assuntos como "Problema do FreeBSD" ou "Ajuda" não são suficientes. Se você não fornecer nenhum assunto, muitas pessoas não se incomodarão em lê-lo. Se o seu assunto não for específico o suficiente, as pessoas que podem responder sua pergunta podem não ler sua mensagem.
* Formate a sua mensagem para que ela fique legível e, POR FAVOR, NÃO GRITE !!!!! Nós apreciamos que muitas pessoas não falam inglês como sua primeira língua, e tentamos fazer concessões para isso, mas é realmente doloroso tentar ler uma mensagem escrita com erros de digitação ou sem quebras de linha.
+ 
Não subestime o efeito que uma mensagem de correio mal formatada tem, não apenas na lista de discussão FreeBSD-questions. Sua mensagem de e-mail é o que todas as pessoas vêem de você, e se estiver mal formatada, uma linha por parágrafo, mal grafada ou cheia de erros, isso dará às pessoas uma má impressão sobre você.
+ 
Muitas mensagens mal formatadas vêm de http://www.lemis.com/email.html[clientes de email ruins ou mal-configurados]. Os seguintes clientes de email são conhecidos por enviar mensagens mal formatadas sem que você saiba sobre elas:

** Eudora(R)
** exmh
** Microsoft(R) Exchange
** Microsoft(R) Outlook(R)

+ 
Tente não usar MIME: muitas pessoas usam clientes de email que não se dão muito bem com MIME.
* Verifique se seu horário e fuso horário estão definidos corretamente. Isso pode parecer um pouco bobo, já que sua mensagem ainda será distribuída, mas muitas das pessoas que você está tentando alcançar recebem várias centenas de mensagens por dia. Eles frequentemente classificam as mensagens recebidas por assunto e por data, e se a sua mensagem não vem antes da primeira resposta, eles podem assumir que eles perderam e não se darão ao trabalho de procurar.
* Não inclua perguntas não relacionadas na mesma mensagem. Em primeiro lugar, uma mensagem longa tende a assustar as pessoas e, em segundo lugar, é mais difícil conseguir que todas as pessoas que podem responder a todas as perguntas leiam a mensagem.
* Especifique o máximo de informação possível. Essa é uma área difícil, precisamos expandir e detalhar melhor quais informações você precisa enviar, mas aqui está um começo:

** Em quase todos os casos, é importante conhecer a versão do FreeBSD que você está executando. Este é particularmente o caso do FreeBSD-CURRENT, onde você também deve especificar a data do código fonte, embora, obviamente, você não deva enviar perguntas sobre -CURRENT para a FreeBSD-questions.
** Com qualquer problema que _possa_ ser relacionado a hardware, informe-nos sobre o seu hardware. Em caso de dúvida, suponha que seja possível que seja hardware. Que tipo de CPU você está usando? Quão rápido? Qual placa-mãe? Quanta memória? Quais periféricos?
+ 
Há uma chamada de julgamento aqui, é claro, mas a saída do comando man:dmesg[8] frequentemente pode ser muito útil, já que não apenas informa qual hardware você está executando, mas qual a versão do FreeBSD também.
** Se você receber mensagens de erro, não diga "eu recebo mensagens de erro", diga (por exemplo) " eu recebo a mensagem de erro 'No route to host'".
** Se o seu sistema entrar em panic, não diga "Meu sistema entrou em panic", diga (por exemplo) "meu sistema entrou em panic com a mensagem 'free vnode isn't'".
** Se você tiver dificuldades em instalar o FreeBSD, por favor, nos diga qual hardware você possui. Em particular, é importante conhecer os IRQs e os endereços de I/O das placas instaladas em sua máquina.
** Se você tiver dificuldade em executar o PPP, descreva a configuração. Qual versão do PPP você usa? Que tipo de autenticação você tem? Você tem um endereço IP estático ou dinâmico? Que tipo de mensagens você recebe no arquivo de log?

* Muitas das informações que você precisa fornecer são a saída de programas, como man:dmesg[8], ou mensagens do console, que geralmente aparecem em [.filename]#/var/log/messages#. Não tente copiar essa informação digitando-a novamente; é um sofrimento real e você está fadado a cometer um erro. Para enviar o conteúdo do arquivo de log, faça uma cópia do arquivo e use um editor para reduzir as informações apenas ao que for relevantes ou copie e cole na sua mensagem. Para a saída de programas como man:dmesg[8], redirecione a saída para um arquivo e inclua-o. Por exemplo,
+
[source,bash]
....
% dmesg > /tmp/dmesg.out
....
+ 
Isto redireciona a informação para o arquivo [.filename]#/tmp/dmesg.out#.
* Se você fizer tudo isso e ainda não obtiver uma resposta, pode haver outras razões. Por exemplo, o problema é tão complicado que ninguém sabe a resposta, ou a pessoa que sabe a resposta estava offline. Se você não obtiver uma resposta depois de, digamos, uma semana, pode ajudar se você reenviar a mensagem. Se você não obtiver uma resposta para sua segunda mensagem, provavelmente não obterá uma deste fórum. Reenviar a mesma mensagem de novo e de novo só o tornará impopular.

Para resumir, vamos supor que você saiba a resposta para a seguinte pergunta (sim, é a mesma em cada caso). Você escolhe qual destas duas perguntas você estaria mais preparado para responder:

.Mensagem 1
[example]
====

....
Subject: HELP!!?!??
I just can't get hits damn silly FereBSD system to
workd, and Im really good at this tsuff, but I have never seen
anythign sho difficult to install, it jst wont work whatever I try
so why don't you guys tell me what I doing wrong.
....
====

.Mensagem 2
[example]
====

....
Subject: Problems installing FreeBSD

I've just got the FreeBSD 2.1.5 CDROM from Walnut Creek, and I'm having a lot
of difficulty installing it.  I have a 66 MHz 486 with 16 MB of
memory and an Adaptec 1540A SCSI board, a 1.2GB Quantum Fireball
disk and a Toshiba 3501XA CDROM drive.  The installation works just
fine, but when I try to reboot the system, I get the message
Missing Operating System.
....
====

== Como Acompanhar uma Pergunta

Algumas vezes você vai querer mandar informação adicional para uma questão que você já enviou. A melhor maneira de fazer isso é responder a sua própria mensagem original. Isto tem três vantagens:

. Você inclui o texto da mensagem original, assim as pessoas saberão do que você está falando. Não esqueça de retirar texto desnecessário.
. O texto no campo do assunto permanece o mesmo (você lembrou de colocar o assunto, não foi?). Muitos aplicativos ordenarão as mensagens pelo assunto. Isto ajuda o agrupamento de mensagens.
. Os números de referência da mensagem no cabeçalho se referem à mensagem anterior. Alguns mailers, como o http://www.mutt.org/[mutt], podem agrupar as mensagens em __thread__, mostrando as relações exatas entre as mensagens.

== Como Responder uma Pergunta

Antes de responder uma pergunta na FreeBSD-questions, considere:

. Muitas das diretivas usadas quando se está para escrever uma questão também são válidas para respondê-las. Leia-as.
. Alguém já respondeu à pergunta? A maneira mais fácil de conferir isto é ordenando as mensagens recebidas pelo assunto: então (esperançosamente) você verá a pergunta seguida pelas respectivas respostas, todas juntas.
+ 
Se alguém já respondeu, isso não significa automaticamente que você não deve enviar outra resposta. Mas faz sentido ler todas as outras respostas primeiro.
. Você tem algo para contribuir além do que já foi dito? Em geral, as respostas do tipo "Sim, eu também" não ajudam muito, embora haja exceções, como quando alguém está descrevendo um problema que está tendo, e não sabe se é culpa dela ou se existe algo de errado com o hardware ou software. Se você for enviar uma resposta do tipo "eu também", você também deverá incluir outras informações relevantes.
. Tem certeza de que entendeu a pergunta? Muito freqüentemente, a pessoa que faz a pergunta é confusa ou não se expressa muito bem. Mesmo com o melhor entendimento do sistema, é fácil enviar uma resposta que não responde à pergunta. Isso não ajuda: você deixará a pessoa que enviou a pergunta ainda mais frustrada ou confusa do que nunca. Se ninguém mais responder e você também não tiver certeza, você sempre poderá pedir mais informações.
. Tem certeza de que sua resposta está correta? Se não, espere um dia ou mais. Se ninguém mais aparecer com uma resposta melhor, você ainda pode responder e dizer, por exemplo, "Eu não sei se isso está correto, mas como ninguém mais respondeu, por que você não tenta substituir seu CDROM ATAPI com por sapo?".
. A menos que haja uma boa razão para fazer o contrário, responda ao remetente e para a FreeBSD-questions. Muitas pessoas na FreeBSD-questions são "lurkers": elas aprendem lendo mensagens enviadas e respondidas por outras pessoas. Se você tirar uma mensagem que é de interesse geral da lista, você está privando essas pessoas de suas informações. Tenha cuidado com as respostas para grupo; Muitas pessoas enviam mensagens com centenas de CCs. Se este for o caso, certifique-se de reduzir as linhas Cc: apropriadamente.
. Incluir texto relevante da mensagem original. Reduza ao mínimo, mas não exagere. O conteúdo original remanescente ainda deve possibilitar à alguém que não leu a mensagem original entender do que você está falando.
. Use alguma técnica para identificar qual texto veio da mensagem original e qual texto você adicionou. Eu pessoalmente acho que a adição do "`>`" no inicio da mensagem original funciona bem. Deixando espaço em branco após o "`>`" e deixar linhas vazias entre o seu texto e o texto original, ambos tornam o resultado mais legível.
. Coloque sua resposta no lugar correto (após o texto ao qual ela se refere). É muito difícil ler um encadeamento de respostas em que cada resposta vem antes do texto ao qual ela se refere.
. A maioria dos programas de email mudam a linha do assunto em um resposta , adicionando no início desta um texto do tipo "Re:". Se seu programa não faz isso automaticamente, você deve fazer manualmente.
. Se o remetente não respeitar as convenções de formato (linhas muito longas, linha de assunto imprópria), _por favor_ conserte-o. No caso de uma linha de assunto incorreta (como " HELP !! ?? "), mude a linha de assunto para (digamos) "Re: Dificuldades com a sincronização PPP (era: HELP !! ??)". Dessa forma, outras pessoas que tentam seguir o tópico terão menos dificuldade em segui-lo.
+ 
Nesses casos, é apropriado falar o que você fez e porque o fez, mas tente fazê-lo de forma a não ser rude. Se você notar que não consegue responder de uma forma que não seja rude, não responda.
+ 
Se você quer responder a uma mensagem somente pelo seu formato inadequado, responda-a somente para quem a enviou, não à lista. Você pode simplesmente enviar esta mensagem em resposta, se quiser.
