# $Id: Makefile,v 1.4 1998-07-26 10:58:50 hanai Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

.if exists(Makefile.conf)
.include "Makefile.conf"
.endif

DOCS=	current.sgml doc-set.sgml submitting.sgml who.sgml translations.sgml
DOCS+=	sgml.sgml 

.include "../../web.mk"
