# $Id: Makefile,v 1.1 1998-07-07 03:14:11 hanai Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

.if exists(Makefile.conf)
.include "Makefile.conf"
.endif

DOCS=	doc-set.sgml submitting.sgml who.sgml
#DOCS+=	current.sgml sgml.sgml translation.sgml 

.include "../../web.mk"
