---
title: "Recherche"
sidenav: about
---

include::shared/fr/urls.adoc[]

= Recherche

== Services de recherche FreeBSD

* <<web,Pages Web>>
* <<mailinglists,Archives des listes de diffusion>>
* link:search-mid[Message-ID]
* http://www.FreeBSD.org/cgi/query-pr-summary.cgi?query[Base de données des rapports de problèmes GNATS (Bugs)]
* http://www.FreeBSD.org/cgi/man.cgi[Pages de Manuels]
* http://www.FreeBSD.org/cgi/ports.cgi[Changements dans les Ports]
* http://fxr.watson.org/[Code Source]
* http://minnie.tuhs.org/BSD-info/bsdnews_search.html[Recherche dans les forums de discussion BSD]
* http://www.google.com/bsd[Recherche Google BSD]
* http://www.greasydaemon.com/[GreasyDaemon], un moteur de recherche UNIX BSD "tout-en-un"
* http://freebsd.rambler.ru/[Recherche dans les archives des listes de diffusion FreeBSD]

'''''

[[web]]
== Pages Web (y compris la link:{faq}[FAQ] et link:{handbook}[le manuel de référence])

=== Rechercher :

_Note : Utilisez les opérateurs AND ou NOT pour restreindre votre recherche. link:searchhints[Consultez cette page pour d'autres astuces]._

{{< form-search-site >}}

'''''

[[mailinglists]]
== Archives des listes de diffusion

Les http://www.FreeBSD.org/mail/[archives des listes de diffusion] sont maintenant mises à jour toutes les semaines !

Une solution alternative pour lire les archives des listes de diffusion est d'utiliser http://lists.FreeBSD.org/mailman/listinfo[l'archive de listes de diffusion Mailman/Pipermail] (notez que cette archive ne remonte que jusqu'à Mars 2003).

Ces listes de diffusion (ainsi que bien d'autres) sont également archivées par http://www.geocrawler.com/[GeoCrawler].

{{< form-search-mail >}}
