#
# Crea il Manuale con il contenuto di solo questo capitolo.
#
# $FreeBSD$
#

CHAPTERS= 	basics/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
