# $FreeBSD: www/en/java/docs/Makefile,v 1.3 2000/05/03 14:14:27 patrick Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	faq.sgml
DOCS+=	howtoports.sgml
DOCS+=	newbies.sgml
DOCS+=	tutorials.sgml
DOCS+=	performance.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
