=== FreeBSD as a Tier 1 cloud-init Platform

Links: +
link:https://https://cloud-init.io/[cloud-init Website] URL: link:https://cloud-init.io/[https://cloud-init.io/] +
link:https://cloudinit.readthedocs.io/en/latest/[cloud-init Documentation] URL: link:https://cloudinit.readthedocs.io/en/latest/[https://cloudinit.readthedocs.io/en/latest/] +
link:https://github.com/canonical/cloud-init/blob/main/WIP-ONGOING-REFACTORIZATION.rst[cloud-init ongoing refactorization] URL: link:https://github.com/canonical/cloud-init/blob/main/WIP-ONGOING-REFACTORIZATION.rst[link:https://github.com/canonical/cloud-init/blob/main/WIP-ONGOING-REFACTORIZATION.rst] +

Contact: Mina Galić <me+FreeBSD@igalic.co>

cloud-init is the standard way of provisioning servers in the cloud.
Unfortunately, cloud-init support for operating systems other than Linux is rather poor, and the lack of cloud-init support on FreeBSD is a hindrance to cloud providers who want to offer FreeBSD as a Tier 1 platform.
To remedy the situation, this project aims to bring FreeBSD cloud-init support on par with Linux support.
The broader plan is to lift support across all BSDs.

The project deliverables include completing an extraction of certain networking classes, implementing man:ifconfig[8] and man:login.conf[5] parsers, implementing IPv6 configuration, creating man:devd.conf[5] rules for Azure, and link:{handbook}[FreeBSD Handbook] documentation about productionizing FreeBSD.

On the way there, any BSD-related bugs found in modules and documentation will also be fixed.

People interested in helping with the project can help with testing new features and fixes through package:net/cloud-init-devel[], which will be updated on a weekly basis.
Further, people with access to, and experience with, OpenBSD and NetBSD are also highly welcome to help.

Sponsor: The FreeBSD Foundation +
