////
Quarter:	3rd quarter of 2022
Prepared by:	fernape
Reviewed by:	gjb, dbaio
Last edit:	$Date: 2022-09-24 14:24:33 +0200 (Sat, 24 Sep 2022) $
Version:	$Id: doceng-2022-3rd-quarter-status-report.adoc 272 2022-09-24 12:24:33Z dbaio $
////

=== Documentation Engineering Team

Link: link:https://www.freebsd.org/docproj/[FreeBSD Documentation Project] +
Link: link:https://docs.freebsd.org/en/books/fdp-primer/[FreeBSD Documentation Project Primer for New Contributors] +
Link: link:https://www.freebsd.org/administration/#t-doceng[Documentation Engineering Team]

Contact: FreeBSD Doceng Team <doceng@FreeBSD.org>

The doceng@ team is a body to handle some of the meta-project issues associated with the FreeBSD Documentation Project; for more information, see link:https://www.freebsd.org/internal/doceng/[FreeBSD Doceng Team Charter].

During the last quarter:

* 0mp@ stepped down as Doceng's Secretary, fernape@ joined as the new Secretary.
  Doceng would like to thank 0mp@ for his service.

* eadler@'s doc bit was taken in for safekeeping per his request.

* A git commit message template was added for the doc repository.

Items pending and in the discussion:

* Remove outdated translations from the Website and Documentation portal.

==== FreeBSD's Documentation Project Primer

The FDP was link:https://cgit.freebsd.org/doc/commit/?id=311e6e3d5e7476cda9107107d779a145241f11fa[expanded with information on trademark handling].

==== Porter's Handbook:

* The documentation on link:https://cgit.freebsd.org/doc/commit/?id=08dd1185b44003d698b267851f704820c9d492c6[porting Haskell programs was updated].

* The link:https://reviews.freebsd.org/D36369[move of WWW from pkg-descr to Makefile was documented].

* link:https://cgit.freebsd.org/doc/commit/?id=78deabd3b1b2aabe9960c24d0c7e8df3fb57e607[Qt 6-related documentation has been added] following the import of the library in the ports framework.

==== FreeBSD Translations on Weblate

Link: link:https://wiki.freebsd.org/Doc/Translation/Weblate[Translate FreeBSD on Weblate] +
Link: link:https://translate-dev.freebsd.org/[FreeBSD Weblate Instance]

===== Q3 2022 Status

* 12 languages
* 148 registered users

 - Gasol Wu joined the Chinese translation team.
 - Alvaro Felipe Calle joined the Spanish translation team.

===== Languages

* Chinese (Simplified) (zh-cn)	(progress: 8%)
* Chinese (Traditional) (zh-tw)	(progress: 4%)
* Dutch (nl) 			(progress: 1%)
* French (fr)			(progress: 1%)
* German (de)			(progress: 1%)
* Indonesian (id)		(progress: 1%)
* Italian (it)			(progress: 4%)
* Norwegian (nb-no)		(progress: 1%)
* Persian (fa-ir)		(progress: 3%)
* Portuguese (pt-br)		(progress: 16%)
* Spanish (es)			(progress: 15%)
* Turkish (tr)			(progress: 2%)

We want to thank everyone who contributed, translating or reviewing documents.

Please, promote this effort in your local user group, we always need more volunteers.

==== FreeBSD Manual Pages Portal

Contact: Sergio Carlavilla <carlavilla@FreeBSD.org>

The Manual Pages Portal has been redesigned to use man:mandoc[1] for rendering.
A link:https://www.carlavilla.es/[portal preview] is available.
Feedback has been collected and addressed where possible.
There are some remaining non-blocking issues.
Doceng@ would like to move forward with the migration to this new portal.

Thanks to all of those who reviewed it and provided feedback.

==== FreeBSD Website Revamp - WebApps working group

Contact: Sergio Carlavilla <carlavilla@FreeBSD.org>

Working group in charge of creating the new FreeBSD Documentation Portal and redesigning the FreeBSD main website and its components.
FreeBSD developers can follow and join the working group on the FreeBSD Slack channel #wg-www21.
The work will be divided into four phases:

. Redesign of the Documentation Portal
+
Create a new design, responsive and with global search. (_Complete_)

. Redesign of the Manual Pages on web
+
Scripts to generate the HTML pages using mandoc. (_Complete_)

. Redesign of the Ports page on web
+
Ports scripts to create an applications portal. (_Work in progress_)

. Redesign of the FreeBSD main website
+
New design, responsive and dark theme. (_Not started_)
