=== Intel wireless towards 11ac

Links: +
link:https://wiki.freebsd.org/WiFi/Iwlwifi[Intel iwlwifi status FreeBSD wiki page] URL: link:https://wiki.freebsd.org/WiFi/Iwlwifi[https://wiki.freebsd.org/WiFi/Iwlwifi]

Contact: Bjoern A. Zeeb <bz@FreeBSD.org>

The ongoing project aims to support the latest Intel wireless chipsets on FreeBSD using LinuxKPI compat code backed by native net80211 and kernel code.
In addition work is on the way to support 11n and 11ac standards in the LinuxKPI 802.11 compat code and fill gaps for mostly 11ac in the native net80211 wireless stack.

For the Intel iwlwifi wireless driver there were no major updates in the last months.
We updated the firmware to the latest publicly available version and fixed some of the most visible bugs.
Work is also on the way to support the D3 power saving code.

LinuxKPI compat code also got some improvements and fixes which at times were only observable on certain generations of iwlwifi chipsets.

Changes in net80211 and LinuxKPI compat code for 11n and 11ac have little public visibility so far in order to not break basic support.
Updates to constants based on newer 802.11 standards and other changes without user-visible effect were merged, and
functional changes will follow in the coming months, initially hidden behind compile-time or runtime options.

Improvements and updates were largely merged back to stable/13 for the benefit of the users tracking this branch and to help with more testing.

For the latest state of the development, please follow the freebsd-wireless mailing list and check the wiki pages.

Sponsor: The FreeBSD Foundation
