=== KDE on FreeBSD

Links: +
link:https://freebsd.kde.org/[KDE FreeBSD] URL: link:https://freebsd.kde.org/[https://freebsd.kde.org/] +
link:https://community.kde.org/FreeBSD[KDE Community FreeBSD] URL: link:https://community.kde.org/FreeBSD[https://community.kde.org/FreeBSD]

Contact: Adriaan de Groot <kde@FreeBSD.org>

The KDE on FreeBSD project packages the software from the KDE Community, along with dependencies and related software, for the FreeBSD ports tree.
The software includes a full desktop environment called KDE Plasma (for both X11 and Wayland) and hundreds of applications that can be used on any FreeBSD machine.

The KDE team (kde@) is part of desktop@ and x11@, building the software stack to make FreeBSD beautiful and usable as a daily-driver graphics-based desktop machine.
The notes below describe *mostly* ports for KDE, but also include items that are important for the entire desktop stack.

==== Qt6 Landed

The big news in the KDE ports is not directly KDE-related.
Qt6 has landed, which prepares us for the next generation of Qt-based applications.

It is now possible to have `USES=qt:6` to select the new Qt version.
Some ports have been flavorized to make use of the new version.

KDE itself is not affected: the upstream work on KDE Frameworks for Qt6 is not yet completed.
Most of the KDE Frameworks will compile with Qt6, but that is not important for FreeBSD ports yet.
With package:devel/qt6[] you get Qt 6.4.0, released at the end of the quarter.

==== KDE Stack

KDE Gear releases happen every quarter, KDE Plasma updates once a month, and KDE Frameworks have a new release every month as well.
These (large) updates land shortly after their upstream release and are not listed separately.

* KDE Frameworks 5 is now at version 5.98 (latest monthly release from September 2022).
* KDE Gear is now version 22.08.1 (update for September 2022).
* KDE Plasma is now version 5.24.6 (update for July 2022).

Note that KDE Plasma 5.25 has been released upstream, but is waiting on fixes before it can land in the ports tree (for example, link:https://bugs.kde.org/show_bug.cgi?id=458356[this KActivityManager bug] in KDE's bug-tracker).

==== Related Ports

* package:accessibility/qt5-speech[] now supports multiple backends, as well as no-backends, for speech synthesis.
* package:devel/cmake[] was reorganized, so that package:devel/cmake[] is now a metaport that installs package:devel/cmake-core[] and the rest of the CMake suite. (Thanks to diizzy@) The CMake ports were also updated to version 3.24, with attendant changes in ports all over the tree.
* package:net/qt5-network[] has improved compatibility with libressl.
* package:x11/plasma-wayland-protocols[] was updated in advance of KDE Plasma Desktop updates in the next quarter.
