=== FreeBSD Release Engineering Team

Links: +
link:https://www.freebsd.org/releases/12.4R/schedule/[FreeBSD 12.4-RELEASE schedule] URL: link:https://www.freebsd.org/releases/12.4R/schedule/[https://www.freebsd.org/releases/12.4R/schedule/] +
link:https://www.freebsd.org/releases/13.2R/schedule/[FreeBSD 13.2-RELEASE schedule] URL: link:https://www.freebsd.org/releases/13.2R/schedule/[https://www.freebsd.org/releases/13.2R/schedule/] +
link:https://www.freebsd.org/releases/14.0R/schedule/[FreeBSD 14.0-RELEASE schedule] URL: link:https://www.freebsd.org/releases/14.0R/schedule/[https://www.freebsd.org/releases/14.0R/schedule/] +
link:https://download.freebsd.org/snapshots/ISO-IMAGES/[FreeBSD development snapshots] URL: link:https://download.freebsd.org/snapshots/ISO-IMAGES/[https://download.freebsd.org/snapshots/ISO-IMAGES/]

Contact: FreeBSD Release Engineering Team, <re@FreeBSD.org>

The FreeBSD Release Engineering Team is responsible for setting and publishing release schedules for official project releases of FreeBSD, announcing code freezes and maintaining the respective branches, among other things.

During the third quarter of 2022, the Release Engineering Team continued providing weekly development snapshot builds for the *main*, *stable/13*, and *stable/12* branches.

Additionally, the schedules for the upcoming 12.4, 13.2, and 14.0 release cycles were published on the Project website.

Sponsor: Rubicon Communications, LLC ("Netgate")
Sponsor: The FreeBSD Foundation
