---
authors:
  - 
    author: 'The FreeBSD Documentation Project'
copyright: '2004-2021 The FreeBSD Documentation Project'
description: 'Cómo usar bien las listas de correo, por ejemplo cómo evitar discusiones que se repiten frecuentemente'
tags: ["FAQ", "Mailing Lists", "FreeBSD"]
title: 'Preguntas más frecuentes sobre las listas de correo de FreeBSD'
---

= Preguntas más frecuentes sobre las listas de correo de FreeBSD
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:images-path: articles/mailing-list-faq/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
:imagesdir: ../../../images/{images-path}
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[.abstract-title]
Resumen

Este es el FAQ de las listas de correo de FreeBSD. Si estás interesado en ayudar con este proyecto, manda un email a {freebsd-doc}. La última versión de este documento siempre está disponible en el link:.[servidor World Wide Web de FreeBSD]. También se puede descargar como un gran fichero link:.[HTML] por HTTP o como texto plano, PostScript, PDF, etc. desde https://download.freebsd.org/doc/[servidor FTP de FreeBSD].

'''

toc::[]

[[introduction]]
== Introducción

Como es habitual en las FAQ, este documento pretende cubrir las preguntas más frecuentes relacionadas con las listas de correo de FreeBSD (¡y por supuesto, responderlas!). Aunque originalmente tenía la intención de reducir el ancho de banda y evitar que se hicieran las mismas preguntas una y otra vez, las FAQ han sido reconocidas como un recurso de información valioso.

Este documento intenta representar el consenso de la comunidad, y como tal nunca puede ser __una fuente de autoridad__. Sin embargo, si encuentras errores técnicos en este documento, o tienes sugerencias acerca de puntos que deberían ser añadidos, por favor, envía un PR, o email a {freebsd-doc}. Gracias.

=== ¿Cuál es el propósito de las listas de correo de FreeBSD?

Las listas de correo de FreeBSD constituyen el canal principal de comunicación de la comunidad de FreeBSD, cubriendo varias áreas y comunidades de intereses diferentes.

=== ¿Quién es el público de las listas de correo de FreeBSD?

Esto depende de cómo se constituya cada lista individual. Algunas listas están más orientadas hacia los desarrolladores; algunas están más orientadas hacia la comunidad de FreeBSD en su conjunto. Por favor, visita link:https://lists.FreeBSD.org/[esta lista] para ver un resumen actualizado.

Las listas están en Inglés, a menos que se especifique lo contrario.

=== ¿Las listas de correo de FreeBSD están abiertas para que cualquiera pueda participar?

Una vez más, esto depende del cometido oficial de cada lista en particular. Por favor, consulta el chárter (la declaración del cometido de las listas de correo) antes de enviar un correo a la lista y sigue la filosofía de dicha lista en los envíos que haga. Esto ayudará al resto de usuarios a sacar más provecho de la lista.

Si después de leer las listas anteriores todavía no has podido discernir a qué lista debes enviar tu pregunta, probablemente puedas enviar la consulta a la lista freebsd-questions (pero por favor lee más abajo antes de hacerlo).

Ten en cuenta también que las listas de correo tradicionalmente han estado abiertas a la recepción de correo por parte de no subscriptores. Esta ha sido una elección deliberada, para hacer que unirse a la comunidad de FreeBSD sea un proceso más fácil y para fomentar el intercambio abierto de ideas. No obstante, debido a los abusos de envío masivo de correos por parte de algunos individuos, ciertas listas ahora tienen una política según la cual las publicaciones de no suscriptores deben seleccionarse manualmente para asegurarse de que sean apropiadas.

=== ¿Cómo puedo suscribirme?

Puedes utilizar link:https://lists.FreeBSD.org/[el interfaz web de Mlmmj] para subscribirte a cualquiera de las listas públicas.

=== ¿Cómo puedo darme de baja?

Puede utilizar exactamente la misma interfaz que en el caso anterior; o puede seguir las instrucciones que se añaden automáticamente al final de cualquier mensaje publicado en la lista.

Por favor, no envíes mensajes de baja directamente a la lista de correo. Primero, con esto no obtendrás tu objetivo, y en segundo lugar, irritarás a los subscriptores y probablemente serás increpado por ello. Se trata de un error bastante común cuando se comienza a utilizar listas de correo; por favor, intenta evitarlo.

=== ¿Están los archivos históricos disponibles?

Sí. Hay disponibles archivos en formato de hilo de conversación link:https://docs.FreeBSD.org/mail/[aquí]. También puedes acceder al https://lists.freebsd.org/pipermail[archivo de mailman] y al link:https://lists.freebsd.org/archives[archivo de mlmmj] directamente.

=== ¿Las listas de correo están disponibles en un formato resumen (digest)?

Sí. Visita link:https://lists.FreeBSD.org/[el interfaz web de Mlmmj].

[[etiquette]]
== Normas de protocolo de las listas de correo

La participación en listas de correo, al igual que en cualquier otra comunidad, requiere una base común para la comunicación. Por favor, haz únicamente preguntas o respuestas adecuadas y sigue las reglas de protocolo habituales.

=== ¿Qué debo hacer antes de enviar un correo?

Leyendo este documento ya has realizado el paso más importante. Sin embargo, si eres nuevo en FreeBSD, podrías necesitar primero familiarizarte con el software y con toda la historia social a su alrededor leyendo los numerosos link:https://www.FreeBSD.org/docs/books/[libros y artículos] que hay disponibles. Algunos elementos de especial interés incluyen el documento de he extref:{faq}[Preguntas Frecuentas de FreeBSD (FAQ)], el extref:{handbook}[manual de FreeBSD], y los artículos extref:{freebsd-questions-article}[Cómo obtener los mejores resultados de la lista de correo de FreeBSD-questions], extref:{explaining-bsd}[Explicando BSD], y extref:{new-users}[primeros pasos con FreeBSD].

Enviar una consulta sobre algo que ya está respondido en los documentos anteriores se considera malas formas. Esto no ocurre porque los voluntarios que colaboran en las listas sean personas especialmente susceptibles, sino porque después de un cierto tiempo respondiendo una y otra vez las mismas preguntas las personas comienzan a sentirse frustradas. Ten siempre en cuenta que casi todo el trabajo realizado en FreeBSD lo realizan voluntarios, y que simplemente somos humanos.

=== ¿Qué se considera un mensaje inapropiado?

* Las publicaciones deben seguir el charter de la lista de correo.
* Por favor, evita los ataques personales. Como buenos ciudadanos de la red, debemos tratar de mantenernos en unos altos estándares de comportamiento.
* No se permite el spam, en ningún caso. Las listas de correo se procesan constantemente para asegurarse del cumplimiento de esta regla.

=== ¿Qué se considera como una norma de etiqueta apropiada cuando se envían correos a las listas?

* Por favor ajusta todas las líneas a 75 caracteres, ya que no todo el mundo utiliza programas de correo con interfaces gráficas avanzadas.
* Por favor, ten presente el hecho de que el ancho de banda no es un recurso infinito. No todo el mundo lee el correo electrónico a través de conexiones de alta velocidad, de forma que si tus mensajes contienen adjuntos tales como el contenido del fichero [.filename]#config.log# o un amplio volcado de la pila, considera colocar esa información en un sitio web y proporciona solo la URL. Recuerda, también, que estas publicaciones se archivarán indefinidamente, por lo que las publicaciones enormes aumentarán el tamaño de los archivos mucho después de que su propósito haya expirado.
* Formatea tu mensaje de forma que sea legible, y, ¡¡¡¡¡POR FAVOR NO GRITES!!!!! No subestimes el efecto que tiene un mensaje de correo mal formateado, y no solo en las listas de correo de FreeBSD. Tu mensaje de correo es todo lo que la gente ve de ti, y si está mal formateado, mal escrito, lleno de errores y/o tiene muchos signos de exclamación, darás a la gente una mala impresión.
* Por favor utiliza el idioma apropiado para cada lista de correo particular. Hay link:https://www.FreeBSD.org/community/mailinglists/[disponibles] muchas listas de correo de habla no inglesa.
+
Para las que no lo son, sabemos que muchas personas no hablan inglés como primer idioma, y tratamos de hacer concesiones. Criticar a hablantes de inglés no nativos por una gramática pobre o errores en su escritura se consideran (muy) malos modos. FreeBSD posee un excelente bagaje en este tema; por favor ayúdanos a mantener esta tradición.
* Por favor utiliza Mail User Agents (MUA) que siguen los estándares. Muchos mensajes mal formateados vienen de http://www.lemis.com/grog/email/email.php[malos programas de correo o programas de correo mal configurados]. Los siguientes programas de correo son conocidos por enviar mensajes mal formateados sin que te des cuenta:

** exmh
** Microsoft(R) Exchange
** Microsoft(R) Outlook(R)
+
Intenta no utilizar MIME: mucha gente utiliza aplicaciones de correo que no se llevan muy bien con MIME.
* Asegúrate de que su hora y zona horaria están configuradas correctamente. Esto puede parecer un poco estúpido a primera vista, ya que tu mensaje será recibido, pero muchas de las personas en estas listas de correo reciben varios cientos de mensajes al día. Frecuentemente, ordenan los mensajes entrantes por asunto y por fecha, y si tu mensaje no aparece antes de la primera respuesta, pueden asumir que lo pasaron por alto y no molestarse en mirar.
* Mucha de la información que tienes que proporcionar es la salida de algunos programas, como man:dmesg[8], o mensajes de consola que normalmente aparecen en [.filename]#/var/log/messages#. No intentes copiar esta información escribiéndola de nuevo; es un verdadero dolor y estás destinado a cometer un error. Para enviar el contenido de ficheros de log, haz una copia del fichero y utiliza un editor para dejar sólo la información relevante, o corta y pega en tu mensaje. Para la salida de programas como man:dmesg[8], redirecciona la salida a un fichero e inclúyelo. Por ejemplo,
+
[source, shell]
....
% dmesg > /tmp/dmesg.out
....
+
Esto redirige la información al fichero [.filename]#/tmp/dmesg.out#.
* Cuando uses copia y pega, por favor ten en cuenta que muchas de esas operaciones entremezclan los mensajes. Esto es especialmente importante cuando se postea contenido de [.filename]#Makefiles#, donde `tab` es un carácter con significado. Este es un problema muy común, y muy molesto, con los envíos a la link:https://www.FreeBSD.org/support/[base de datos de Reportes de Error]. [.filename]#Makefiles# con los tabs cambiados por espacios, o la molesta secuencia de escape `=3B`, es muy exasperante para los committers.

=== ¿Cuáles son las consideraciones especiales de etiqueta cuando se responde a un mensaje en las listas de correo?

* Por favor incluye el texto del mensaje original que considere relevante. Recórtalo al mínimo, pero no exageres. Cualquier otra persona que no leyó el mensaje original debería ser capaz de entender de qué se estás hablando.
+
Esto es particularmente importante en el caso de envíos del estilo de "sí, yo también veo esto", donde el mensaje original formado por cientos de líneas no aparece.
* Usa alguna técnica para identificar qué texto venía del mensaje original y cual has añadido tú. Una convención habitual es utilizar como prefijo "` >`" en el mensaje original. Dejar un espacio entre el "` >`" y dejando líneas en blanco entre tu texto y el texto original, hace que el resultado sea más legible.
* Asegúrate de que las atribuciones del texto que estás citando son correctas. Las personas pueden ofenderse si les atribuye palabras que ellos mismos no escribieron.
* Por favor no hagas `top post`. Con esto, nos referimos a que se respondes a un mensaje, por favor pongas tus respuestas después del texto que copias en tu respuesta.
+
** R: Porque invierte el flujo lógico de la conversación.
** P: ¿Por qué el top posting está mal visto?
+
(Gracias a Randy Bush por la broma.)

[[recurring]]
== Temas recurrentes en las listas de correo

La participación en las listas de correo, así como la participación en cualquier otra comunidad, se basa en una serie de normas básicas para posibilitar la comunicación. Muchas de las listas de correo presuponen un conocimiento de la historia del proyecto. En particular, existen ciertos temas que suelen aparecer regularmente a los recién llegados a la comunidad. Es responsabilidad de cada participante comprobar que sus mensajes no caen en alguna de estas categorías. Al hacerlo, ayudará a mantener a la lista en el tema, y probablemente se salve de ser atacado en el proceso.

El mejor método para evitar esto consiste en familiarizarse con los http://docs.FreeBSD.org/mail/[archivos de las listas de correo], así sabrás qué temas se han tratado con anterioridad. En este aspecto resulta de gran valor https://www.FreeBSD.org/search/#mailinglists[la interfaz de búsqueda] de la lista de correo. (Si ese método no produce resultados útiles, complétalo con una búsqueda en tu motor de búsqueda principal favorito).

Si te familiarizas con los archivos históricos, no solo sabrás qué temas se han tratado anteriormente, también aprenderás cómo se produce la discusión en la lista, quiénes son los participantes y quién es el público objetivo. Estos puntos conviene conocerlos antes de preguntar en cualquier lista de correo, no solo en las de FreeBSD.

No hay duda de que los archivos son bastante extensos, y algunas preguntas se repiten con más frecuencia que otras, algunas veces camufladas dentro de hilos donde la línea del asunto no refleja precisamente el nuevo contenido del mensaje. Sin embargo tú, quien envía el mensaje, eres responsable de evitar que se produzcan temas recurrentes.

[[bikeshed]]
== ¿Qué es un "Bikeshed"?

Literalmente, un `bikeshed` es una pequeña caseta exterior en la cual uno almacena una forma de trasporte sobre dos ruedas. Sin embargo, en la jerga de FreeBSD, el término se refiere a temas que son suficientemente sencillos que (casi) cualquiera puede opinar sobre ellos y habitualmente (casi) todo el mundo lo hace. El nacimiento de este término se explica en más detalle en extref:{faq}[este documento, bikeshed-painting]. Simplemente tienes que saber algo sobre este concepto antes de enviar a cualquier lista de FreeBSD.

De una forma más general, un bikeshed es un asunto que tiende a generar meta-discusiones y ataques si no se han leído las discusiones anteriores.

Por favor, colabora en el mantenimiento de las listas de correo evitando los bikesheds siempre que puedas. Gracias.

[[acknowledgments]]
== Reconocimientos

`{grog}`::
Autor original de la mayor parte del material sobre etiqueta en las listas de correo, recogido del artículo sobre extref:{freebsd-questions-article}[Cómo obtener los mejores resultados de la lista de correo de FreeBSD-questions].

`{linimon}`::
Por la creación del borrador inicial de estas FAQ.
