#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/euro/Makefile,v 1.3 2005/06/12 06:08:28 gad Exp $
#
# Original revision: 1.5
#
# Article: The Euro Symbol on FreeBSD

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= 	article.sgml

URL_RELPREFIX?=		../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
