---
title: "FreeBSD 4.3 Announcement"
sidenav: download
--- 

= FreeBSD 4.3 Announcement

*Date:* Friday, 20 Apr 2001 21:00:00 -0800 +
*From:* "Jordan K. Hubbard" <jkh@freebsd.org> +
*To:* announce@FreeBSD.org +
*Subject:* 4.3-RELEASE is now available

It gives me great pleasure to announce what is probably the finest release produced from the 4.x-STABLE branch to date, FreeBSD 4.3-RELEASE. Following the release of FreeBSD 4.2 in November, 2000, many bugs were fixed, important security issues dealt with, and a reasonable number of new features added. Please see the release notes for more information.

4.3-RELEASE is available for the ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/4.3-RELEASE[i386] and ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/alpha/4.3-RELEASE[alpha] architectures and can be installed directly over the net using the boot floppies or copied to a local NFS/ftp server.

ISO (CD) Images +
--------------- +

We can't promise that all the mirror sites will carry the larger ISO images, but they will at least be available from:

ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/ISO-IMAGES/4.3-install.iso +
and ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/alpha/ISO-IMAGES/4.3-install.iso

If you can't afford the CDs, are impatient, or just want to use it for evangelism purposes, then by all means download the ISOs, otherwise please do continue to support the FreeBSD project by purchasing one of its official CD releases from BSDi. FreeBSD 4.3-RELEASE can be ordered as a 4 CD set from http://www.freebsdmall.com[The FreeBSD Mall] from where it will soon be shipping. Each CD sets contains the FreeBSD installation and application package bits for either the x86 or the alpha architecture (each architecture has its own CD set). For a set of distfiles used to build ports in the ports collection, please see also the FreeBSD Toolkit, a 6 CD set containing all such extra bits which we can no longer fit on the 4 CD sets. You can also order by phone, postal mail, FAX or email at:

....
  BSDi
  4041 Pike Lane, #F
  Concord CA, 94520 USA
  Phone: +1 925 674-0783
  Fax: +1 925 674-0821
  Tech Support: +1 925 603-1234
  Email: orders@wccdrom.com
  WWW: http://www.freebsdmall.com/
....

*Note:* Despite the recent acquisition of BSDi's software assets by Wind River, the above information still holds true for the forseeable future and will not change for at least the life-cycle of the FreeBSD 4.3 product. Any changes in the FreeBSD product sales infrastructure will be announced if and as they occur.

FreeBSD is also available via anonymous FTP from mirror sites in the following countries: Argentina, Australia, Austria, Brazil, Bulgaria, Canada, the Czech Republic, Denmark, Estonia, Finland, France, Germany, Hong Kong, Hungary, Iceland, Ireland, Israel, Japan, Korea, Latvia, Malaysia, the Netherlands, Poland, Portugal, Rumania, Russia, Slovenia, South Africa, Spain, Sweden, Taiwan, Thailand, Elbonia, the Ukraine and the United Kingdom, among others.

Before trying the central FTP site, please check your regional mirror(s) first by going to:

ftp://ftp.<yourdomain>.FreeBSD.org/pub/FreeBSD

Any additional mirror sites will be labeled ftp2, ftp3 and so on.

Thanks! - Jordan
