# $FreeBSD: www/en/ports/growth/Makefile,v 1.1 2002/05/20 12:43:10 phantom Exp $
#

TOOLDIR=${.CURDIR}/../../../tools/portsgrowth

all install clean:
	cd ${TOOLDIR}; \
		 ${MAKE} ${MAKEFLAGS} ${.TARGETS}

