# $FreeBSD: www/ja/releases/2.1.6R/Makefile,v 1.3 1999/12/23 01:15:59 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

LOCALTOP= ../..

#DOCS=	announce.sgml notes.sgml security.sgml
DOCS=	notes.sgml security.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
