#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: doc/fr_FR.ISO_8859-1/articles/Makefile,v 1.1 1999/11/10 21:28:21 nik Exp $
#    Original revision: 1.3
#

SUBDIR = diskless-x
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= ip-aliasing
SUBDIR+= make-world
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= ntfs
SUBDIR+= ppp
SUBDIR+= programming-tools
SUBDIR+= committers-guide
SUBDIR+= zip-drive

ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
