# The FreeBSD Simplified Chinese Project
# Original Revision: 1.1
#
# $FreeBSD: www/zh_CN/layout/Makefile.inc,v 1.1.1000.2 2005/12/17 16:28:55 delphij Exp $

WEBBASE?=	/data/zh_CN/layout
WEB_PREFIX?=	${.CURDIR}/../../..
