# The FreeBSD Simplified Chinese Project
# Original Revision: 1.1
#
# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR=		css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
