---
title: "Обязанности Группы подготовки релизов"
sidenav: developers
--- 

= Обязанности Группы подготовки релизов

Группа подготовки релизов отвечает за следующие вопросы:

* Определение и публикация плана выпуска релизов для официальных релизов Проекта FreeBSD.
* Документирование и формализация процесса подготовки релизов, так чтобы его можно было пересматривать и улучшать. В эту работу включается подготовка документации о кластере портов и процедурах разделения пакаджей.
* Установка и публикация дат "заморозки кода", и выполнение роли комитета по просмотру изменений для решения вопроса о том, какие изменения можно вносить в ветку во момент заморозки кода. К этим вопросам относится заморозка ветки HEAD при подготовке релиза .0, а также традиционные заморозки кода `RELENG_*` при выпуске релизов -STABLE.
* Создание и обслуживание веток `RELENG_*` дерева `src/`. Сюда относится принятие конечного решения о том, какие изменения делаются (и остаются) в ветке -STABLE до создания ветки, соответствующей релизу.
* Работа с руководством проекта и/или Фондом FreeBSD для определения набора правил, которым должны следовать поставщики, если они хотят, чтобы их продукт назывался "FreeBSD" или "Официальным релизом FreeBSD".
* Тестирование и интеграция необходимых пакаджей из коллекции портов на носители с официальными релизами. Portmgr@ отвечает за управление заморозкой кода в `ports/` и полноту построения пакаджей портов, которые можно распространять. re@ отвечает за размещение этих пакаджей на различных ISO, требуемых для носителей релизов. re@ безусловно отвечает за то, что все требуемые пакаджи размещаются на носителях с релизом FreeBSD, но без участия portmgr@ здесь не обойтись.
* Координация с Проектом создания документации FreeBSD для обеспечения наличия полного набора документации к релизу. В круг вопросов входит запрет на внесение больших изменений в наборе документации в недели, предшествующие релизу.
* Координация с командой начальника отдела информационной безопасности для обеспечения того, что релизы FreeBSD не будут подвержены недавно выявленным уязвимостям. Кроме того, примерно примерно через 1 неделю после релиза право на утверждение внесения изменений в ветках релизов (`RELENG_X_Y`) передаётся от релиз-инженеров службе безопасности. Конкретная дата передачи согласуется обоими сторонами, как только становится ясно, что релиз состоялся. В этот момент в адрес developers@ должно посылаться предупреждающее письмо.
* Посылка сообщений в адрес announce@FreeBSD.org от имени проекта для анонсирования новых релизов FreeBSD.
