# $FreeBSD$

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOC=			installation
FORMATS?=		html txt
INSTALL_COMPRESSED?=	gz
INSTALL_ONLY_COMPRESSED=

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
