# $FreeBSD: www/en/conspectus/stable/2000/Makefile,v 1.1 2000/05/31 20:35:47 nik Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=	index.sgml

SUBDIR=	05
SUBDIR+= 06

.include "../../../web.mk"
