# $FreeBSD: www/en/conspectus/stable/2000/Makefile,v 1.2 2000/06/17 13:15:37 nik Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

SUBDIR=	05
SUBDIR+= 06

.include "${WEB_PREFIX}/share/mk/web.site.mk"
