=== Audio Stack Improvements

Contact: Christos Margiolis <christos@FreeBSD.org>

The FreeBSD audio stack is one of those fields that does not attract the same attention and development as others do, since it has been left largely unmaintained, and, although high in quality, there is still room for improvement -- from lack of audio development frameworks, to missing userland utilities and kernel driver-related bugs.
This project is meant to touch on all those areas, and as such, is more of a general improvement project, than an implementation of a specific feature.

Important work since link:https://www.freebsd.org/status/report-2024-07-2024-09/#_audio_stack_improvements[last report]:

* man:sound[4] and driver bug fixes, including panics and races.
  Several cleanup and refactor patches.
* Committed man:mididump[1].
  Ships with 14.2-RELEASE and 14-STABLE.
* Implementing link:https://reviews.freebsd.org/D47638[AFMT_FLOAT] support.
  This fixes ports, such as package:emulators/wine[], that require `AFMT_FLOAT` support from OSS.
  Related bug reports: link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=184380[PR 184380], link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281390[PR 281390], link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264973[PR 264973], link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=157050[PR 157050].

Future work includes:

* More bug fixes, optimizations and general improvements.
* Implement a generic MIDI layer, similar to pcm/, and improve/modernize the MIDI codebase in general.
* Implement a bluetooth device management utility.
* virtual_oss patches and improvements.
* Attempt to automate man:snd_hda[4] pin-patching.
* Investigate SOF/DMIC support.

You can also follow the development process in link:https://lists.freebsd.org/subscription/freebsd-multimedia[freebsd-multimedia@], where I post regular reports.

Sponsor: The FreeBSD Foundation
