=== A bhyve management GUI written in Freepascal/Lazarus

Links: +
link:https://github.com/alonsobsd/bhyvemgr[Bhyvemgr] URL: link:https://github.com/alonsobsd/bhyvemgr/[] +

Contact: José Alonso Cárdenas Márquez <acm@FreeBSD.org>

Bhyvemgr is a bhyve management GUI written in Freepascal/Lazarus on FreeBSD.
It needs a bunch of tools mostly installed on base system and some installed from ports/packages.
The application is being developed for desktop users to easily and quickly setup and run virtual machines on FreeBSD hosts.

During this quarter, there were many bugfixes and improvements to Bhyvemgr.

These are some new features that were added:

- Support for Trusted Platform Module (TPM through software via swtpm) on CURRENT
- Bootvars support
- Bios, system, board and chassis information can be modified
- Systray icon support on almost all desktop environment (tested on Plasma, Gnome, Xfce, LXQt and IceWM)

Bhyvemgr supports aarch64 only on 15-CURRENT and amd64 from FreeBSD 13.x to 15-CURRENT.
Also bhyvemgr can be

* compiled and installed from link:https://www.freshports.org/sysutils/bhyvemgr[ports],
* installed as binaries through `pkg` with gtk2, qt5 or qt6 interface support.

Anyone interested in helping or supporting the project are welcome.

Current version: 1.3.1

TODO

* Testing on real aarch64 hardware (aarch64 device donation for testing is welcome)
* Add uart device support
