////
Quarter:	4th
Prepared by:	fernape
Reviewed by:	carlavilla
Last edit:	$Date$
Version:	$Id:$
////

=== Documentation Engineering Team

Link: link:https://www.freebsd.org/docproj/[FreeBSD Documentation Project] URL: link:https://www.freebsd.org/docproj/[] +
Link: link:https://docs.freebsd.org/en/books/fdp-primer/[FreeBSD Documentation Project Primer for New Contributors] URL: link:https://docs.freebsd.org/en/books/fdp-primer/[] +
Link: link:https://www.freebsd.org/administration/#t-doceng[Documentation Engineering Team] URL: link:https://www.freebsd.org/administration/#t-doceng[]

Contact: FreeBSD Doceng Team <doceng@FreeBSD.org>

The doceng@ team is a body to handle some of the meta-project issues associated with the FreeBSD Documentation Project; for more information, see link:https://www.freebsd.org/internal/doceng/[FreeBSD Doceng Team Charter].

==== Document changes

* Handbook:
  ** Add warning about custom kernel configurations.
  ** Mention Rocky Linux 9 userland.
  ** Add notes to VMWare related setup guide.

* Committer's guide: Document "Discussed with"
  Improve "Fixes:" metadata.

* Porter's Handbook: Document new `TCL_` variables.

* Website: Remove Turkish links.

* Documentation repository:
  ** Added OpenBSD 7.6 manual pages.
  ** Updated Debian 11/12 manpages.


==== FreeBSD Translations on Weblate

Link: link:https://wiki.freebsd.org/Doc/Translation/Weblate[Translate FreeBSD on Weblate] URL: link:https://wiki.freebsd.org/Doc/Translation/Weblateurl[] +
Link: link:https://translate-dev.freebsd.org/[FreeBSD Weblate Instance] URL: link:https://translate-dev.freebsd.org/url[]

===== Q4 2024 Status

* 18 team languages
* 215 registered users

1 new translator joined Weblate:

* Sean Markham (ES)

===== Languages

* Chinese (Simplified) (zh-cn)	(progress: 14%)
* Chinese (Traditional) (zh-tw)	(progress: 11%)
* Dutch (nl) 			(progress: 1%)
* French (fr)			(progress: 1%)
* German (de)			(progress: 1%)
* Greek (el)			(progress: 1%)
* Indonesian (id)		(progress: 1%)
* Italian (it)			(progress: 11%)
* Korean (ko)			(progress: 30%)
* Norwegian (nb-no)		(progress: 1%)
* Persian (fa-ir)		(progress: 6%)
* Polish			(progress: 2%)
* Portuguese			(progress: 0%)
* Portuguese (pt-br)		(progress: 31%)
* Sinhala			(progress: 1%)
* Spanish (es)			(progress: 39%)
* Spanish (Chile)		(progress: 0%)
* Turkish (tr)			(progress: 5%)

We want to thank everyone who contributed, translating, or reviewing documents.

And please, help promote this effort on your local user group; we always need more volunteers.

==== Packages maintained by DocEng

During this quarter the following work was done in packages maintained by doceng@:

* www/gohugo: update to 0.140.2
* misc/freebsd-doc-ja: fix build

==== Open issues

There is 1 open PR in Bugzilla assigned to doceng@:

 * 276923 www/gohugo link error under poudriere

