=== Infrastructure Modernization

Contact: Ed Maste <emaste@FreeBSD.org> +
Contact: Alice Sowerby <alice@freebsdfoundation.org>

The project started in Q3 of 2024 and was commissioned by the Sovereign Tech Agency with a budget of $745,000, to be spent over about one year.
The main goals are to improve security tools for the base system, ports, and packages, update the project's infrastructure to speed up development, enhance build security, and make it easier for new developers to get started.

Q4 update

* Work Package A: Technical Debt reduction.
The Foundation collaborated with the Source Management team to commission and deploy a number of dashboards that characterize the bug backlog for the FreeBSD Project.
These were created to the team's specifications by our project partner, Bitergia, who used an open source tool called GrimoireLab to create the dashboards.
Foundation staff have hosted the dashboards on a FreeBSD deployment and they can be seen at https://grimoire.freebsd.org/.
More information about the dashboards can be found at https://github.com/freebsd/grimoire.
+
The Source Management team has also used these dashboards to support their new, evolving approach to bug triage and it has been included as a key tool for collaborative bug-squashing events.

* Work Package B: Zero Trust Builds, and Work Package C: CI/CD Automation.
The Foundation collaborated with various key management and administration teams within the FreeBSD Project to co-create the details of the scope for these two projects.
They are scheduled to start in January and will conclude in Q2/3.

* Work Package D: Security Controls in Ports and Packages, and Work Package E: Improve Software Bill of Materials (SBOM).
These have not started yet as they are scheduled for February and March starts respectively.

Commissioning body: link:https://www.sovereign.tech/[Sovereign Tech Agency]
