=== Framework Laptop support

Links: +
link:https://wiki.freebsd.org/Laptops/Framework_Laptop/[Framework Laptop page on FreeBSD Wiki] URL: https://wiki.freebsd.org/Laptops/Framework_Laptop/[] +
link:https://github.com/FrameworkComputer/freebsd-on-framework[Guide on installing and using FreeBSD on Framework systems] URL: https://github.com/FrameworkComputer/freebsd-on-framework[] +
link:https://bugs.freebsd.org/262152[Tracking ticket: Framework Laptop: Feature support, bugs and improvements] URL: https://bugs.freebsd.org/262152[]

Contact: Daniel Schaefer <dhs@frame.work> +
Contact: Li-Wen Hsu <lwhsu@FreeBSD.org> +
Contact: Sheng-Yi Hong <aokblast@FreeBSD.org>

For a long time, Framework Laptop Inc is friendly to the FreeBSD project in many aspects, including providing engineering samples to Foundation for testing and working on support.

Since 2024 summer, there are several small hackathons in Framework's Taipei office on testing FreeBSD on different models of Framework laptop, and the peripheral devices.

Sheng-Yi is using the laptop provided by Framework Computer to add more device support, e.g. https://cgit.freebsd.org/src/commit/?id=d3b05d0ea10abe059dc63c6fb6ef3f061b758af2[d3b05d0ea10a: Add smbus and i2c device IDs for Meteor Lake].

Daniel from Framework Computer Inc started link:https://github.com/FrameworkComputer/freebsd-on-framework[a repository under Framework Computer's GitHub organization] to keep the notes of installation and miscellaneous information.
He fixed fingerprint readers (libfprint) not just for Framework, but in general on FreeBSD.
And working on the support and fix to many related drivers on FreeBSD.

In November, Foundation people and some FreeBSD developers visited Framework's San Francisco office and had a meeting for checking the current FreeBSD support status and discussing the possible future collaboration plans.

Foundation will continue working on improving the general laptop support and using Framework as one of the link:https://github.com/FreeBSDFoundation/proj-laptop/blob/main/supported/laptops.md[target platforms] for the link:https://github.com/FreeBSDFoundation/proj-laptop/[Laptop Support and Usability Project].

Sponsor: The FreeBSD Foundation for Li-Wen's work +
Sponsor: Framework Computer Inc for Daniel's work, hardware and space support
