=== Greenbone Vulnerability Management Community Edition

Links: +
link:https://www.greenbone.net/en/[Greenbone] URL: link:https://www.greenbone.net/en/[] +
link:https://github.com/greenbone/[Greenbone GitHub] URL: link:https://github.com/greenbone/[] +

Contact: José Alonso Cárdenas Márquez <acm@FreeBSD.org>

The Greenbone Community Edition (GVM) covers the actual source code of the Greenbone Vulnerability Management software stack, which is also known as OpenVAS scanner, a security feed with more than 160.000 vulnerability tests, a vulnerability management application, and much more.

During this quarter, package:security/gvm[] metaport was updated to 24.1.2.
This update includes the following:

- package:databases/pg-gvm[]: Updated to 22.6.6
- package:security/gsa[]: Updated to 24.1.0 (Only amd64 and aarch64)
- package:security/gsad[]: Updated to 24.1.0
- package:security/openvas[]: Updated to 23.14.0
- package:security/gvmd[]: Updated to 24.1.2
- package:security/gvm-libs[]: Updated to 22.15.0
- package:security/py-notus-scanner[]: Updated to 22.6.5
- package:security/py-greenbone-feed-sync[]: Updated to 24.9.0
- package:security/py-ospd-openvas[]: Bump PORTREVISION
- package:security/py-gvm-tools[]: Updated to 24.12.1
- package:security/py-python-gvm[]: Updated to 24.12.0

A quick GVM jail installation to test it can be done using link:https://github.com/DtxdF/AppJail[AppJail], link:https://github.com/alonsobsd/greenbone-openvas-makejail[makejail], or link:https://github.com/AppJail-makejails/greenbone-openvas[].

Anyone interested in helping with the project or interested in aarch64 device donation for testing is welcome.

Current version: 24.1.2
