=== FreeBSD Release Engineering Team

Links: +
link:https://www.freebsd.org/releases/14.2R/announce/[FreeBSD 14.2-RELEASE announcement] URL: link:https://www.freebsd.org/releases/14.2R/announce/[] +
link:https://www.freebsd.org/releases/13.5R/schedule/[FreeBSD 13.5-RELEASE schedule] URL: link:https://www.freebsd.org/releases/13.5R/schedule/[] +
link:https://download.freebsd.org/releases/ISO-IMAGES/[FreeBSD releases] URL: link:https://download.freebsd.org/releases/ISO-IMAGES/[] +
link:https://download.freebsd.org/snapshots/ISO-IMAGES/[FreeBSD development snapshots] URL: link:https://download.freebsd.org/snapshots/ISO-IMAGES/[]

Contact: FreeBSD Release Engineering Team, <re@FreeBSD.org>

The FreeBSD Release Engineering Team is responsible for setting and publishing release schedules for official project releases of FreeBSD, announcing code freezes and maintaining the respective branches, among other things.

The Team managed 14.2-RELEASE, leading to the official RELEASE build and announcement in December.
Planning has started for the upcoming 13.5-RELEASE cycle, which is expected to be the final release from the legacy *stable/13* branch; as such it will include updates to "contrib" code and some bug fixes, but is not expected to have any significant new features.

In addition to previously shipped release artifacts (ISO and memory stick images, VM images, cloud offerings, etc.) the Team is now also providing OCI compatible container images.

The Release Engineering Team continued providing weekly development snapshot builds for the *main*, *stable/14*, and *stable/13* branches.
