=== Suspend/Resume Improvements

Links: +
link:https://obiw.ac/s0ix/[Blog] URL: link:https://obiw.ac/s0ix/[] +
link:https://github.com/obiwac/freebsd-s0ix[Working Branch] URL: link:https://github.com/obiwac/freebsd-s0ix[]

Contact: obiwac <obiwac@freebsd.org>

Suspend-to-idle and support for S0ix sleep is in the process of being added to FreeBSD.

This will allow modern Intel and AMD laptops (e.g. AMD and newer Intel Framework laptops), some of which do not support ACPI S3 sleep, to enter low power states to increase battery life.

Ben Widawsky from Intel started working on this in 2018 but his work was never finished and is now outdated.
His work has now been picked up and the first goal is to get suspend/resume working on the Framework 13 AMD Ryzen 7040 series by end of January.
There are plans for presenting initial results at a talk at FOSDEM.

Currently, all device power constraints on AMD can already be parsed to enter a system's low power states.

Sponsor: The FreeBSD Foundation
