=== Wireless Update

Contact: Tom Jones <thj@FreeBSD.org> +
Contact: The FreeBSD wireless mailing list <wireless@FreeBSD.org>

With Support from the FreeBSD Foundation this quarter I started working on porting the iwx WiFi driver from OpenBSD (via Haiku).
The iwx driver supports many of the chipsets supported by iwlwifi, but rather than make that driver more complex the OpenBSD developers decided to support these devices in a new driver.

iwx on OpenBSD currently supports running as a station in 80211abgn and ac, it does not yet support ax rates.
The goals of this project are to import a maintainable driver from OpenBSD and to gradually increase support until we have a native driver in FreeBSD with support for 80211ac (and potentially 80211ax).

Currently the driver supports 80211a and 80211g and is able to saturate the practical limits of the rates these standards offers (roughly 28Mbit down and 25 Mbit up).
The driver is under active development and moving quite quickly.

The plan for the next quarter is to add support for high throughput rates, implement monitor mode and stabilise the driver for a public call for testing.

Once the driver is stable enough a call for testing will be posted to the link:https://lists.freebsd.org/subscription/freebsd-current[freebsd-current] and link:https://lists.freebsd.org/subscription/freebsd-wireless[freebsd-wireless] mailing lists.


Sponsor: The FreeBSD Foundation
