#
# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/articles/solid-state/Makefile
# %SRCID%	39631
#
# Article: FreeBSD and Solid State Devices

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
