# $FreeBSD$

MAN=	aic.4 \
	apm.4 \
	ar.4 \
	cs.4 \
	cx.4 \
	el.4 \
	ep.4 \
	ex.4 \
	fe.4 \
	ie.4 \
	io.4 \
	lnc.4 \
	mcd.4 \
	npx.4 \
	pcf.4 \
	perfmon.4 \
	pnp.4 \
	scd.4 \
	spkr.4 \
	sr.4 \
	vx.4 \
	wd.4

MLINKS+=spkr.4 speaker.4

MANSUBDIR=/i386	

.include <bsd.prog.mk>
