=== Git Migration Working Group

Links: +
link:https://wiki.freebsd.org/git[Git transition wiki] URL: link:https://wiki.freebsd.org/git[https://wiki.freebsd.org/git] +
link:https://cgit.FreeBSD.org/doc[doc git repo] URL: link:https://cgit.FreeBSD.org/doc[https://cgit.FreeBSD.org/doc] +
link:https://cgit.FreeBSD.org/ports[ports git repo] URL: https://cgit.FreeBSD.org/ports[https://cgit.FreeBSD.org/ports] +
link:https://cgit.FreeBSD.org/src[src (base system) git repo] URL: link:https://cgit.FreeBSD.org/src[https://cgit.FreeBSD.org/src] +
link:https://docs.freebsd.org/en/articles/committers-guide/#git-primer[Committers guide Git primer] URL: link:https://docs.freebsd.org/en/articles/committers-guide/#git-primer[https://docs.freebsd.org/en/articles/committers-guide/#git-primer] +
link:https://docs.freebsd.org/en/books/handbook/mirrors/#git[Handbook Using Git appendix] URL: link:https://docs.freebsd.org/en/books/handbook/mirrors/#git[https://docs.freebsd.org/en/books/handbook/mirrors/#git] +
link:http://gameoftrees.org/[Game of Trees] URL: link:http://gameoftrees.org/[http://gameoftrees.org/] +
link:https://github.com/johnmehr/gitup[gitup] URL: link:https://github.com/johnmehr/gitup[https://github.com/johnmehr/gitup]

Contact: Li-Wen Hsu <lwhsu@FreeBSD.org> +
Contact: Warner Losh <imp@FreeBSD.org> +
Contact: Ed Maste <emaste@FreeBSD.org> +
Contact: Ulrich Spörlein <uqs@FreeBSD.org> +
Contact: link:https://lists.freebsd.org/mailman/listinfo/freebsd-git[FreeBSD-git mailing list] +
Contact IRC #gitcvt channel on EFnet

The doc and src trees were migrated from Subversion to Git at the end of 2020, with some additional work extending into the first quarter of 2021.
The Git Working Group implemented or updated commit hooks, and prepared for FreeBSD 13 to be built from Git.
We converted draft documentation from Markdown to AsciiDoc and merged it into the committer's guide and handbook.

The ports repository migration to Git started at the end of the quarter, beginning with a final Subversion commit on March 31st to indicate that the conversion started.
We are working on portsnap and other ports infrastructure and they will be finished before or soon after the migration.

The Git Working Group continues to track progress on two permissively-licensed git compatible tools: Gitup and Game of Trees.
Gitup is a small, dependency-free tool to clone and update git repositories.
It is used only to keep a local tree up-to-date, and has no support for local commits.

Game of Trees is a version control client that is compatible with Git repositories.
It provides a user interface and workflow that is distinct from that of Git.
It is in no way intended to be a drop-in replacement for git, but can be used to develop software maintained in a Git repository.

Gitup and Game of Trees are currently available as ports and packages.
Future work will evaluate them as candidates for the base system.

In the second quarter of 2021 we expect to complete some minor remaining migration tasks.
This will complete the initial phase of the Git migration, and the working group will wind down.
The core team will then begin a new effort to investigate and evaluate new workflow changes.

Sponsor: The FreeBSD Foundation (in part)
