=== Intel wireless update

Links: +
link:https://lists.freebsd.org/mailman/listinfo/freebsd-wireless[The freebsd-wireless mailing list] URL: link:https://lists.freebsd.org/mailman/listinfo/freebsd-wireless[https://lists.freebsd.org/mailman/listinfo/freebsd-wireless]

Contact: Bjoern A. Zeeb <bz@FreeBSD.org>

==== Newer Intel Wireless device support

The Intel Wireless driver update project aims to bring support for newer chipsets.

During the first quarter the driver and firmware were synched from upstream so that we will have support for all modern cards currently supported in Linux.
Some iwlwifi driver changes were also submitted back upstream.

Several conflicts with the original implementation of LinuxKPI were or are being resolved and more LinuxKPI code was upstreamed to FreeBSD HEAD.

LinuxKPI 802.11 compat code was improved and as of the day of writing we have data packets going over 11a.

The plan for the next weeks is to clean things up, land as much as possible in HEAD, provide the code for testing and work on stability based on feedback before filling gaps in the LinuxKPI 802.11 compat code to enhance support for more standards and features.

Sponsor: The FreeBSD Foundation
