=== OpenBSM Synchronisation

Links: +
link:http://www.trustedbsd.org/openbsm.html[TrustedBSD / OpenBSM] URL: link:http://www.trustedbsd.org/openbsm.html[http://www.trustedbsd.org/openbsm.html] +
link:https://github.com/openbsm/openbsm[OpenBSM Github Sources] URL: link:https://github.com/openbsm/openbsm[https://github.com/openbsm/openbsm] +
link:https://github.com/openbsm/openbsm/commit/54a0c07cf8bac71554130e8f6760ca68e5f36c7f[Synchronisation with macOS Catalina] URL: link:https://github.com/openbsm/openbsm/commit/54a0c07cf8bac71554130e8f6760ca68e5f36c7f[https://github.com/openbsm/openbsm/commit/54a0c07cf8bac71554130e8f6760ca68e5f36c7f] +
link:https://opensource.apple.com[Apple OpenSource] URL: link:https://opensource.apple.com[https://opensource.apple.com]

Contact: Gordon Bergling <gbe@FreeBSD.org>

OpenBSM is a crucial part of FreeBSD, which provides auditing features for the operating system.
OpenBSM is incorporated into FreeBSD and macOS.
Both Apple and FreeBSD have currently made changes to the OpenBSM framework, which weren't upstreamed.
This small project aims to consolidate these changes and upstream them to the OpenBSM github repository, so that both development efforts can be merged to FreeBSD later on.

There is currently a pull request pending that synchronizes the FreeBSD sources with OpenBSM.
A comparison was made to incorporate Apple's Catalina changes.
A few weeks ago Apple has also made the source code of Big Sur available.
In the latest comparison against OpenBSM Apple has made overlapping ID changes, which are making a simple import of the changes impossible.
I am currently trying to work around that issue by making OpenBSM a little vendor specific.
