=== PkgBase.live

Links: +
link:https://alpha.pkgbase.live/[Website] URL: link:https://alpha.pkgbase.live/[https://alpha.pkgbase.live/]

Contact: Mina Galić <me@igalic.co>

PkgBase.live is an unofficial repository for the FreeBSD link:https://wiki.freebsd.org/PkgBase[PkgBase project].
PkgBase packages the FreeBSD base system as ca 330 packages.

The PkgBase project gives users the choice of which parts of the system to install.
Users can choose which parts of the base system to install, without building their system from source and optionally choose to install `-dbg` packages when they need them.
PkgBase is built with default options.
There's no need to build `WITHOUT_SENDMAIL`, when users can just chose not to install it!
In addition, PkgBase.live builds _every_ usable kernel! This is especially important for architectures like `armv7`.

As a service, PkgBase.live was inspired by link:https://up.bsd.lv/[up.bsd.live], which provides man:freebsd-update[8] for STABLE and CURRENT branches.
Despite this inspiration, freebsd-update has been a constant point of frustrations for me, so I was looking for alternatives.

PkgBase is not ready for prime time yet, or else the FreeBSD project would be providing this service.
With the call for testing open since 2016, I thought it was time to offer a _public_ service, so a broader part of the community can take part in testing, without having to do all the work for themselves.

A lot of things already work fine, but more work needs to be done, as can be seen from the TODO list, as well as the "Pending Changes" on the website.
Perhaps the most important thing would be to provide ISOs which lets people setup a fresh system with PkgBase from the get-go.

Hardware for PkgBase is kindly sponsored by a member of the FreeBSD community.
