=== Ports Collection

Links: +
link:https://www.FreeBSD.org/ports/[About FreeBSD Ports] URL: link:https://www.FreeBSD.org/ports/[https://www.FreeBSD.org/ports/] +
link:https://docs.freebsd.org/en/articles/contributing/ports-contributing/[Contributing to Ports] URL: link:https://docs.freebsd.org/en/articles/contributing/ports-contributing/[https://docs.freebsd.org/en/articles/contributing/ports-contributing/] +
link:http://portsmon.freebsd.org/[FreeBSD Ports Monitoring] URL: link:http://portsmon.freebsd.org/[http://portsmon.freebsd.org/] +
link:https://www.freebsd.org/portmgr/[Ports Management Team] URL: link:https://www.freebsd.org/portmgr/[https://www.freebsd.org/portmgr/] +
link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[Ports Tarball] URL: link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[http://ftp.freebsd.org/pub/FreeBSD/ports/ports/]

Contact: René Ladan <portmgr-secretary@FreeBSD.org> +
Contact: FreeBSD Ports Management Team <portmgr@FreeBSD.org>

The Ports Management Team is responsible for overseeing the overall direction of the Ports Tree, building packages, and personnel matters.
Below is what happened in the last quarter.

As always, first the quarterly dashboard:
* we currently have around 43,800 ports (including flavors).
* the open PR count for ports is currently 2477, of which 532 are unassigned.
* during the last quarter, 9481 commits were made by 168 committers on the main branch, and 620 commits by 64 committers on the 2021Q1 branch.
Compared to 2020Q4, the number of ports again grew by five percent, the number of open PRs dropped a bit, and the number of commits on the main branch grew with almost nine percent.

During the last quarter, we welcomed Neel Chauhan (nc@), Lewis Cook (lcook@), and Nuno Teixeira (eduardo@).
Adrian Chadd (adrian@) who is already a src committer got a ports commit bit extension.
Tobias Berner (tcberner@) asked if he could join the portmgr-lurker program and was shortly added afterwards.

We sent another mail to the ports@ mailing list outlining further plans for removing Python 2.7 from the Ports Tree.
Currently all ports recursively depending on Python 2.7 are marked to expire on 2021-06-23, which unfortunately includes a lot of KDE ports due to the qt5-webengine port.
We are evaluating various mitigation strategies.

portmgr has been collaborating with the Git Working Group over the last year to prepare the Ports Tree to be converted to Git.
Tasks included:
* converting various scripts and tools to support Git
* attending Git Working Group meetings
* updating documentation
* updating various internal and public third-party services
* evaluating numerous test conversion (git-beta) results

Regarding the Ports Tree itself, two new USES were introduced:
* `kodi` to ease porting of Kodi add-ons
* `mpi` for dependencies of MPICH and OpenMPI
A new default version for ImageMagick was added and the default version for Julia was removed
as no Julia port currently exists.
`pkg` was updated to 1.16.3, Firefox to 87.0, and Chromium to 89.0.4389.114

The Cluster Administration Team assisted with getting three new package building machines running in the build cluster.
Two are for arm64 builds and one is a general builder.

antoine@ was again busy with exp-runs, 28 this time, to:
* test various ports updates
* update the clang/LLVM version from 6 to 10 in USES=compiler
* reduce includes in /usr/include/crypto
