=== FreeBSD Release Engineering Team

Links: +
link:https://www.freebsd.org/releases/13.0R/schedule.html[FreeBSD 13.0-RELEASE schedule] URL: link:https://www.freebsd.org/releases/13.0R/schedule.html[https://www.freebsd.org/releases/13.0R/schedule.html] +
link:https://download.freebsd.org/ftp/snapshots/ISO-IMAGES/[FreeBSD development snapshots] URL: link:https://download.freebsd.org/ftp/snapshots/ISO-IMAGES/[https://download.freebsd.org/ftp/snapshots/ISO-IMAGES/]

Contact: FreeBSD Release Engineering Team, <re@FreeBSD.org>

The FreeBSD Release Engineering Team is responsible for setting
and publishing release schedules for official project releases
of FreeBSD, announcing code freezes and maintaining the respective
branches, among other things.

During the first quarter of 2021, the Release Engineering Team started
work on the 13.0-RELEASE cycle, the first release from the stable/13 branch.
As of this writing, the release is progressing smoothly, with one additional
BETA build and two additional RC builds added to the schedule.  The schedule
has been updated on the FreeBSD Project website to reflect the updates.

Additionally throughout the quarter, several development snapshots builds
were released for the *head*, *stable/12*, and *stable/11* branches.
Development snapshot builds for *stable/13* will be available after the 13.0
release.

Thank you to all that have helped test the 13.0 builds up until this point and
have reported issues.  As always, we strive for quality over quantity.

Sponsor: Rubicon Communications, LLC ("Netgate")
Sponsor: The FreeBSD Foundation
