# $FreeBSD: www/ja/releases/2.2.2R/Makefile,v 1.5 2000/11/07 11:37:59 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	notes.sgml
DOCS+=	errata.sgml

### Revision checking
REVCHECK=	YES

.include "${WEB_PREFIX}/share/mk/web.site.mk"
