---
title: "Советы по поиску"
sidenav: about
--- 

= Советы по поиску

== Если вы получили много не относящихся к делу результатов...

. Если вы производите поиск по нескольким словам, типа "`quantum  hard drives`", то неявно применяется операция OR, означающая, что в результаты поиска попадут все сообщения, которые содержат хотя бы одно слово из предложенных. Для поиска только тех сообщений, которые содержат все три слова, измените строку поиска на "`quantum and hard and drives`"
. Если вы все равно получаете массу не относящихся к делу результатов, посмотрите, нет ли среди них похожих. Если это так, вы можете исключить их с помощью оператора `not`. Например, "`quantum and hard and drives not ide`" исключит все сообщения о дисках quantum с интерфейсом IDE.

== Если вы полагаете, что получили не все, что хотели...

. Если одно из ключевых слов имеет различные формы, попробуйте указать их все. Если вы ищете "`buslogic`", можно сменить шаблон поиска на "`buslogic or bustek`".
. Слова с различными суффиксными частями можно задать шаблоном. Поиск по ключу "`drive*`" покроет такие слова, как `drive`, `drives`, `driver`, `drivers` и так далее.
. Попробуйте отбросить слова, которые могут подразумеваться в контексте текста сообщения. Например, при поиске по "`quantum and hard and drive`" могут быть пропущены сообщения, которые подходят под "`quantum and drive`".

'''''

link:..[Возврат к странице поисковой службы]
