#
# $FreeBSD$
#

MAINTAINER= des@FreeBSD.org

DOC?= book

FORMATS?= html-split html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS= book.sgml

IMAGES_EN= figures/branches.png
IMAGES_EN+= figures/freebsd-code-model.png
IMAGES_EN+= figures/hats-overview.png
IMAGES_EN+= figures/maintenance.png
IMAGES_EN+= figures/orghierarchy.png
IMAGES_EN+= figures/orghierarchy2.png
IMAGES_EN+= figures/portsstatus.png
IMAGES_EN+= figures/proc-add-committer.png
IMAGES_EN+= figures/proc-add-cvsup.png
IMAGES_EN+= figures/proc-commit.png
IMAGES_EN+= figures/proc-contrib.png
IMAGES_EN+= figures/proc-elections.png
IMAGES_EN+= figures/proc-pr.png
IMAGES_EN+= figures/proc-releng.png
IMAGES_EN+= figures/proc-rm-committer.png

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
