# $FreeBSD$
# $FreeBSDde: de-www/community/Makefile,v 1.2 2006/02/03 14:32:11 jkois Exp $
# basiert auf: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	irc.sgml
DOCS+=	mailinglists.sgml
DOCS+=	newsgroups.sgml
DOCS+=	webresources.sgml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
