# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   bugreports.xml webresources.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
