---
description: 'Инструменты, используемые в проекте документации FreeBSD'
next: books/fdp-primer/working-copy
params:
  path: /books/fdp-primer/tools/
prev: books/fdp-primer/overview
showBookMenu: true
tags: ["tools", "required tools", "optional tools"]
title: 'Глава 2. Инструменты'
weight: 3
---

[[tools]]
= Инструменты
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 2
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

Для управления документацией FreeBSD и её преобразования в различные выходные форматы используется несколько программных инструментов. Некоторые из них обязательны и должны быть установлены перед работой с примерами из следующих глав. Другие являются опциональными, расширяя возможности или упрощая процесс создания документации.

[[tools-required]]
== Необходимые инструменты

Установите `docproj` _мета-порт_, как показано в crossref:overview[overview,обзорной главе] из Коллекции портов. Эти приложения необходимы для работы с документацией FreeBSD. Далее приведены дополнительные заметки об отдельных компонентах.

[[tools-optional]]
== Необязательные инструменты

Эти приложения не обязательны, но могут упростить работу с документацией или расширить её возможности.

[[tools-optional-software]]
=== Программное обеспечение

Vim (package:editors/vim[]) — популярный редактор для работы с Asciidoctor.

Emacs (package:editors/emacs[]).

Оба инструмента включают специальный режим, который сокращает количество необходимых нажатий клавиш и помогает снизить количество ошибок.
