---
title: "FreeBSD Project Administration and Management"
sidenav: about
---

include::shared/authors.adoc[]

////
NOTE: If any alias listed on this page is modified in the
/etc/aliases on the FreeBSD project's mail server,
then this page must be updated.
////

= Администрирование и управление проектом FreeBSD

== Введение

На этой странице перечислены команды, группы и лица в проекте FreeBSD, имеющие определенные проектные роли и области ответственности, вместе с краткими описаниями и контактной информацией.

* Управление проектом
** <<t-core,Основная команда (Core Team)>>
** <<t-doceng,Команда управления документацией>>
** <<t-portmgr,Команда управления портами>>
** <<t-ports-secteam,Команда безопасности портов>>
** <<t-pkgmgr,Команда управления пакетами>>
** <<t-srcmgr,Команда управления исходным кодом>>
* Инженерия выпусков
** <<t-re,Основная команда выпуска релизов>>
* Команды
** <<t-donations,Команда по работе с пожертвованиями>>
** <<t-secteam,Команда безопасности>>
** <<t-vendor,Отношения с поставщиками>>
* Секретари
** <<t-core-secretary,Секретарь Основной команды>>
** <<t-doceng-secretary,Секретарь команды инженерии документации>>
** <<t-portmgr-secretary,Секретарь команды управления портами>>
** <<t-srcmgr-secretary,Секретарь команды управления исходным кодом>>
* Внутреннее администрирование
** <<t-accounts,Команда управления учетными записями>>
** <<t-backups,Администраторы резервного копирования>>
** <<t-bugmeister,Багмастер (Bugmeister)>>
** <<t-clusteradm,Администраторы кластера>>
** <<t-dnsadm,Администраторы DNS>>
** <<t-forum-admins,Администраторы форумов>>
** <<t-git,Администраторы Git>>
** <<t-github-automation,Зеркало репозиториев на GitHub>>
** <<t-jenkins-admin,Администраторы непрерывного тестирования Jenkins>>
** <<t-mirror-admin,Координаторы сайтов-зеркал FTP/WWW>>
** <<t-phabric-admin,Администрирование ревью кода в Phabricator>>
** <<t-postmaster,Почтовая команда (Postmaster)>>
** <<t-webmaster,Веб-мастера>>
** <<t-wiki,Команда администрирования Вики>>

'''

[[t-core]]
== Основная команда FreeBSD <core@FreeBSD.org>

Основная команда FreeBSD представляет собой «Совет директоров» проекта, отвечающий за определение общих целей и направления проекта, а также за управление конкретными областями проекта FreeBSD.
Основная команда избирается активными разработчиками проекта.

* {allanjude} (Представитель команды безопасности)
* {dch} (Представитель команды инженерии выпусков)
* {glebius} (Представитель команды багмастера и команды управления исходным кодом)
* {hrs} (Представитель Фонда)
* {lwhsu} (Представитель команды инженерии документации)
* {mat} (Представитель команды администраторов кластера)
* {olivier} (Представитель команды непрерывной интеграции)
* {tcberner} (Представитель команды управления портами)

[[t-doceng]]
== Команда управления документацией FreeBSD <doceng@FreeBSD.org>

Команда управления документацией FreeBSD отвечает за контроль и определение целей по документации для коммиттеров в проекте Документации.
https://www.freebsd.org/internal/doceng/[Устав команды doceng] подробно описывает обязанности и ответственность команды управления документацией.

* {blackend}
* {hrs}
* {ebrandi}

[[t-portmgr]]
== Команда управления портами FreeBSD <portmgr@FreeBSD.org>

Основная обязанность команды управления портами FreeBSD — обеспечение того, чтобы сообщество разработчиков портов FreeBSD предоставляло коллекцию портов, которая является функциональной, стабильной, актуальной и полнофункциональной.
Ее вторичная обязанность — координация между коммиттерами и разработчиками, которые над ней работают.
https://www.freebsd.org/portmgr/charter/[Устав команды portmgr] подробно описывает обязанности и ответственность команды управления портами.

* {bapt}
* {mat} (Представитель команды администрирования кластера)
* {pizzamig}
* {rene}
* {dvl}

'''

[[t-ports-secteam]]
== Команда безопасности портов FreeBSD <ports-secteam@FreeBSD.org>

Основная обязанность команды безопасности портов FreeBSD — обеспечение оперативного реагирования на инциденты безопасности, затрагивающие коллекцию портов FreeBSD, и защита сообщества пользователей FreeBSD путем информирования сообщества об ошибках, уязвимостях, популярных атаках и других рисках.
Более подробная информация доступна на https://wiki.freebsd.org/PortsSecteam[странице Вики].

* {fernape}
* {fluffy}
* {joneum}
* {riggs}
* {tz}

'''

[[t-pkgmgr]]
== Команда управления пакетами FreeBSD <pkgmgr@FreeBSD.org>

Основная обязанность команды управления пакетами FreeBSD — обеспечение функциональности дерева портов, включая выполнение тестовых сборок предлагаемых изменений, откат/исправление сломанных коммитов, которые нарушают сборки, обслуживание автоматизированного кластера сборки пакетов и обеспечение доступности результирующих пакетов для загрузки пользователями FreeBSD.

* {antoine}
* {bdrewery}

'''

[[t-srcmgr]]
== Команда управления исходным кодом FreeBSD <srcmgr@FreeBSD.org>

Команда управления исходным кодом FreeBSD (также известная как srcmgr по своему почтовому псевдониму) отвечает за вопросы, связанные с базовой системой.
https://www.freebsd.org/srcmgr/charter/[Устав команды srcmgr] подробно описывает обязанности и ответственность команды управления исходным кодом.

* {emaste}
* {imp}
* {jhb}
* {markj}

[[t-re]]
== Основная команда команда выпуска релизов <re@FreeBSD.org>

Основная команда команда выпуска релизов отвечает за установление и публикацию графиков выпуска официальных релизов проекта FreeBSD, объявление о заморозках кода и поддержку веток `releng/*`, среди прочего.
https://www.freebsd.org/releng/charter/[Устав команды команда выпуска релизов] подробно описывает обязанности и ответственность Основной команды инженерии выпусков.

* {dch}
* {blackend}
* {jfree}
* {delphij}
* {emaste} (Заместитель руководителя)
* {mmokhi}
* {cperciva} (Руководитель)
* {bofh}
* {ivy}

[[t-donations]]
== Команда по работе с пожертвованиями <donations@FreeBSD.org>

Команда по работе с пожертвованиями отвечает за ответ на предложения о пожертвованиях, установление руководящих принципов и процедур для пожертвований и координацию предложений о пожертвованиях с сообществом разработчиков FreeBSD.
Более подробное описание обязанностей Команды по работе с пожертвованиями доступно по ссылке: link:https://www.freebsd.org/donations/[Координатор по пожертвованиям FreeBSD].

* {gahr}
* {bhughes}
* {adridg}

[[t-secteam]]
== Команда безопасности <secteam@FreeBSD.org>

Команда безопасности FreeBSD (во главе с офицером по информационной безопасности) отвечает за информирование сообщества об ошибках, уязвимостях и рисках безопасности, затрагивающих деревья src и ports FreeBSD, а также за распространение информации, необходимой для безопасной эксплуатации систем FreeBSD.
Кроме того, она отвечает за устранение программных ошибок, влияющих на безопасность FreeBSD, и выпуск уведомлений о безопасности.
Устав офицера по информационной безопасности FreeBSD подробно описывает обязанности и ответственность офицера по безопасности.

* {gordon} (Офицер)
* {allanjude} (Представитель Основной команды)
* {delphij} (Почетный офицер, представитель команды инженерии выпусков)
* {des} (Почетный офицер)
* {emaste} (Заместитель офицера)
* {markj}
* {oshogbo}
* {philip}

[[t-vendor]]
== Отношения с поставщиками <vendor-relations@FreeBSD.org>

Отдел по связям с поставщиками отвечает за обработку электронной почты от производителей аппаратного и программного обеспечения.
Письма, отправленные в Отдел по связям с поставщиками, пересылаются в Основную команду FreeBSD, а также в Фонд FreeBSD.

'''

[[t-core-secretary]]
== Секретарь Основной команды <core-secretary@FreeBSD.org>

Секретарь Основной команды FreeBSD является членом Основной команды без права голоса, ответственным за документирование работы, выполненной core, отслеживание повестки дня core, связь с членами, не входящими в core, от имени core, рассылку писем для core и взаимодействие с административной командой по утверждению коммиттеров/учетных записей.
Секретарь Основной команды также отвечает за написание и рассылку ежемесячных отчетов о состоянии сообществу разработчиков FreeBSD, содержащих сводку последних решений и действий core.

* {rene}

[[t-doceng-secretary]]
== Секретарь команды инженерии документации <doceng-secretary@FreeBSD.org>

Секретарь команды инженерии документации FreeBSD является членом команды инженерии документации без права голоса, ответственным за документирование работы, выполненной doceng, отслеживание процедур голосования и взаимодействие с другими командами, особенно с административной и Основной командами.

В настоящее время секретарь команды инженерии документации не назначен; письма пересылаются в команду инженерии документации.

[[t-portmgr-secretary]]
== Секретарь команды управления портами <portmgr-secretary@FreeBSD.org>

Секретарь команды управления портами FreeBSD является членом команды управления портами без права голоса, ответственным за документирование работы, выполненной portmgr, отслеживание процедур голосования и взаимодействие с другими командами, особенно с административной и Основной командами.
Секретарь команды управления портами также отвечает за написание и рассылку ежемесячных отчетов о состоянии сообществу разработчиков FreeBSD, содержащих сводку последних решений и действий portmgr.

* (vacant)

[[t-srctmgr-secretary]]
== Секретарь команды управления исходным кодом <srcmgr-secretary@FreeBSD.org>

В настоящее время секретарь команды управления исходным кодом не назначен; письма пересылаются в команду управления исходным кодом.

'''

[[t-accounts]]
== Команда управления учетными записями <accounts@>
////
admins mail aliases intentionally left incomplete
////

Команда управления учетными записями отвечает за настройку учетных записей для новых коммиттеров в проекте.
Запросы на создание новых учетных записей не будут обработаны без соответствующего одобрения от уполномоченного органа.

Письма, отправленные в Команду управления учетными записями, обрабатываются Администраторами кластера.

[[t-backups]]
== Администраторы резервного копирования <backups@>
////
admins mail aliases intentionally left incomplete
////

Администраторы резервного копирования обрабатывают все операции резервного копирования в кластере FreeBSD.

Письма, отправленные в Команду резервного копирования, обрабатываются Администраторами кластера.

[[t-bugmeister]]
== Багмастер (Bugmeister) <bugmeister@FreeBSD.org>

Команда багмастера отвечает за обеспечение работоспособности программного обеспечения для отчетов о проблемах, правильную категоризацию записей и отсутствие недопустимых записей.

* {linimon}
* Сива Махадеван <mailto:me@svmhdvn.name[]>
* {ziaee}

[[t-clusteradm]]
== Администраторы кластера <clusteradm@>
////
admins mail aliases intentionally left incomplete
////

Администраторы кластера отвечают за обслуживание машин и служб, от которых проект зависит для своей распределенной работы и коммуникации.
Вопросы, касающиеся инфраструктуры проекта, или настройки новых машин или служб, следует направлять им.
Этой командой руководит ведущий администратор кластера, чьи обязанности и ответственность подробно описаны в https://www.freebsd.org/internal/clusteradm/[уставе администрирования кластера].

* {bapt}
* {bofh}
* {dbaio}
* {dhw}
* {lwhsu}
* {peter}
* {philip}
* {zi} (Руководитель)

Пожалуйста, рассмотрите возможность использования одного из более конкретных псевдонимов (например, accounts@, dnsadm@, mirror-admin@,...) или https://bugs.freebsd.org/submit/[создания отчета об ошибке] для сообщения о проблемах с инфраструктурой кластера. Выберите "Services", а затем "Core Infrastructure".

[[t-dnsadm]]
== Администраторы DNS <dnsadm@>
////
admins mail aliases intentionally left incomplete
////

Администраторы DNS отвечают за управление службами DNS и связанными с ними службами.

Письма, отправленные администраторам DNS, обрабатываются Администраторами кластера.

[[t-forum-admins]]
== Администраторы форумов FreeBSD <forum-admins@FreeBSD.org>

Администраторы форумов поддерживают форум проекта FreeBSD в Интернете, расположенный по адресу https://forums.freebsd.org/, и руководят группой модераторов, которые работают над обеспечением релевантности и качества контента форума.

* {brd}
* {danger}
* {dutchdaemon}
* {lme}

[[t-git]]
== Администраторы Git <gitadm@>
////
admins mail aliases intentionally left incomplete
////

Администраторы Git FreeBSD отвечают за поддержание работоспособности репозиториев Git.

Письма администраторам Git обрабатываются Администраторами кластера.

Пожалуйста, https://bugs.freebsd.org/submit/[создайте отчет об ошибке] для сообщения о проблемах с репозиториями Git. Выберите "Services", а затем "Core Infrastructure".

[[t-github-automation]]
== Координаторы автоматического зеркалирования репозиториев на GitHub <github-automation@FreeBSD.org>

Команда автоматизации GitHub курирует экспорт содержимого репозитория исходного кода FreeBSD в read-only репозитории на GitHub.

* {koobs}
* {mva}
* {robak}
* {rodrigc}
* {uqs}

[[t-jenkins-admin]]
== Администраторы непрерывного тестирования Jenkins <jenkins-admin@FreeBSD.org>

Администраторы Jenkins поддерживают инфраструктуру непрерывной интеграции и тестирования для проекта FreeBSD.
Это включает в себя обслуживание экземпляра Jenkins и заданий, которые выполняют сборки и запускают тесты.

* {bapt}
* {brd}
* {brooks}
* {lwhsu}
* {swills}

[[t-mirror-admin]]
== Координаторы сайтов-зеркал FTP/WWW <mirror-admin@>
////
admins mail aliases intentionally left incomplete
////

Координаторы сайтов-зеркал FTP/WWW координируют всех администраторов сайтов-зеркал FTP/WWW, чтобы обеспечить распространение текущих версий программного обеспечения, наличие у них возможности обновляться при выполнении крупных обновлений и упростить для широкой публики поиск ближайшего FTP/WWW зеркала.

Письма координаторам сайтов-зеркал обрабатываются Администраторами кластера.

Пожалуйста, https://bugs.freebsd.org/submit/[создайте отчет об ошибке] для сообщения о проблемах с инфраструктурой зеркал. Выберите "Services", а затем "FTP/WWW Sites & Mirrors".

[[t-phabric-admin]]
== Администраторы приложения для ревью кода Phabricator <phabric-admin@FreeBSD.org>

Администраторы Phabricator отвечают за поддержку экземпляра онлайнового инструмента ревью кода Phabricator для FreeBSD, расположенного по адресу https://reviews.freebsd.org/

* {allanjude}
* {bofh}
* {eadler}
* {emaste}
* {jtl}
* {lwhsu}
* {mat}
* {pi}

По любым проблемам, связанным с Phabricator, пожалуйста, https://bugs.freebsd.org/submit/[создайте отчет об ошибке] и выберите "Services", а затем "Code Review".

[[t-postmaster]]
== Почтовые администраторы (Postmaster Team) <postmaster@FreeBSD.org>

Почтовая команда отвечает за корректную доставку почты на адреса электронной почты коммиттеров, обеспечение работы списков рассылки и должна принимать меры против возможных сбоев в работе почтовых служб проекта, таких как настройка фильтров против троллинга, спама и вирусов.

* {bapt}
* {krion}
* {ler}
* {philip}
* {pi}
* {vsevolod}
* {zi}

[[t-webmaster]]
== Команда веб-мастеров <webmaster@FreeBSD.org>

Команда веб-мастеров FreeBSD назначается Командой инженерии документации FreeBSD и отвечает за поддержание работы основных веб-сайтов FreeBSD.
Это означает конфигурацию веб-сервера, CGI-скрипты, полнотекстовый поиск и поиск по спискам рассылки. Все, что связано с веб-технологиями, входит в сферу ответственности команды веб-мастеров, за исключением ошибок в документации.

Письма в команду веб-мастеров в настоящее время пересылаются в команду инженерии документации с добавлением:

* {wosch}

[[t-wiki]]
== Команда администрирования Вики <wiki-admin@FreeBSD.org>

Команда Вики FreeBSD отвечает за поддержание работоспособности сайта https://wiki.FreeBSD.org/[Вики] FreeBSD. Они также определяют общий дизайн и структуру контента.

* {linimon}
* {koobs}

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (04.12.2025): d5213e70dd8fd4771458cfa67b17b535ff4867c8
//
