---
title: "Администрирование и управление проектом FreeBSD"
sidenav: about
---

include::shared/authors.adoc[]

////
ПРИМЕЧАНИЕ: Если какой-либо псевдоним, указанный на этой странице, изменяется в
файле /etc/aliases на почтовом сервере проекта FreeBSD,
то эта страница обязательно должна быть актуализирована.
////

= Администрирование и управление проектом FreeBSD

== Введение

На этой странице перечислены команды, группы и отдельные участники проекта FreeBSD, имеющие определённые проектные роли и области ответственности, вместе с их краткими описаниями и контактной информацией.

* Управление проектом
** <<t-core,Управляющая команда>>
** <<t-doceng,Команда подготовки документации>>
** <<t-portmgr,Команда управления портами>>
** <<t-pkgmgr,Команда управления пакетами>>
** <<t-srcmgr,Команда управления исходным кодом>>
* Команды
** <<t-donations,Команда по работе с пожертвованиями>>
** <<t-re,Команда подготовки релизов>>
** <<t-secteam,Команда безопасности>>
** <<t-ports-secteam,Команда безопасности портов>>
** <<t-vendor,Отдел по связям с вендорами>>
* Секретари
** <<t-core-secretary,Секретарь Управляющей команды>>
** <<t-doceng-secretary,Секретарь Команды подготовки документации>>
** <<t-portmgr-secretary,Секретарь Команды управления портами>>
** <<t-srcmgr-secretary,Секретарь Команды управления исходным кодом>>
* Внутреннее администрирование
** <<t-accounts,Команда управления учётными записями>>
** <<t-backups,Администраторы резервного копирования>>
** <<t-bugmeister,Ответственный за ошибки (Bugmeister)>>
** <<t-clusteradm,Администраторы кластера>>
** <<t-dnsadm,Администраторы DNS>>
** <<t-forum-admins,Администраторы форумов>>
** <<t-git,Администраторы Git>>
** <<t-github-automation,Зеркало репозиториев на GitHub>>
** <<t-jenkins-admin,Администраторы непрерывного тестирования Jenkins>>
** <<t-mirror-admin,Координаторы сайтов-зеркал FTP/WWW>>
** <<t-phabric-admin,Администрирование рецензирования кода в Phabricator>>
** <<t-postmaster,Почтовая команда (Postmaster)>>
** <<t-webmaster,Веб-мастера>>
** <<t-wiki,Команда администрирования Вики>>

[[t-core]]
== Управляющая команда FreeBSD <core@FreeBSD.org>

Управляющая команда FreeBSD в проекте является «Советом директоров», отвечающим за определение общих целей и направления проекта, а также за управление конкретными областями проекта FreeBSD.
Управляющая команда избирается активными разработчиками проекта.

* {adamw}
* {adrian}
* {bapt}
* {glebius}
* {hrs}
* {imp}
* {jrm}
* {kevans}
* {olivier}

[[t-doceng]]
== Команда подготовки документации FreeBSD <doceng@FreeBSD.org>

Команда подготовки документации FreeBSD отвечает за контроль и определение целей по документации для коммиттеров в Проекте документирования.
https://www.freebsd.org/internal/doceng/[Устав Команды doceng] подробно описывает обязанности и ответственность Команды подготовки документации.

* {blackend}
* {hrs}
* {ebrandi}
* {ziaee}

[[t-portmgr]]
== Команда управления портами FreeBSD <portmgr@FreeBSD.org>

Основной обязанностью Команды управления портами FreeBSD является обеспечение формирования функциональной, стабильной, актуальной и полнофункциональной Коллекции портов силами сообщества разработчиков портов FreeBSD.
Ещё одна её обязанность заключается в координации коммиттеров и разработчиков, работающих с Коллекцией портов.
https://www.freebsd.org/portmgr/charter/[Устав команды portmgr] подробно описывает обязанности и ответственность Команды управления портами.

* {bapt}
* {mat} (Представитель Команды администрирования кластера)
* {pizzamig}
* {rene}
* {dvl}

[[t-pkgmgr]]
== Команда управления пакетами FreeBSD <pkgmgr@FreeBSD.org>

Основная обязанность Команды управления пакетами FreeBSD заключается в обеспечении функциональности дерева портов, в том числе выполнение тестовых сборок предлагаемых изменений, откат/исправление изменений, влияющих на корректность сборки, обслуживание автоматизированного кластера сборки пакетов и обеспечение доступности результирующих пакетов для загрузки пользователями FreeBSD.

* {antoine}
* {bdrewery}

[[t-srcmgr]]
== Команда управления исходным кодом FreeBSD <srcmgr@FreeBSD.org>

Команда управления исходным кодом FreeBSD (также известная как srcmgr по своему почтовому псевдониму) отвечает за вопросы, связанные с базовой системой.
https://www.freebsd.org/srcmgr/charter/[Устав команды srcmgr] подробно описывает обязанности и ответственность Команды управления исходным кодом.

* {emaste}
* {imp}
* {jhb}
* {markj}

[[t-donations]]
== Команда по работе с пожертвованиями <donations@FreeBSD.org>

Команда по работе с пожертвованиями отвечает за реагирование на предложения о пожертвованиях, установление руководящих принципов и процедур для пожертвований и согласование предложений о пожертвованиях с сообществом разработчиков FreeBSD.
Более подробное описание обязанностей Команды по работе с пожертвованиями доступно на странице link:https://www.freebsd.org/ru/donations/[Центра пожертвований FreeBSD].

* {gahr}
* {bhughes}
* {adridg}

[[t-re]]
== Команда подготовки релизов <re@FreeBSD.org>

Команда подготовки релизов отвечает за формирование и публикацию графиков выпуска официальных релизов проекта FreeBSD, за объявления о приостановке изменений кода и, кроме всего прочего, за обслуживание веток `releng/*`.
https://www.freebsd.org/ru/releng/charter/[Устав команды подготовки релизов] более подробно описывает обязанности и ответственность Команды подготовки релизов.

* {carlavilla}
* {dch}
* {blackend}
* {leres}
* {delphij}
* {emaste} (Заместитель руководителя)
* {cperciva} (Руководитель)
* {bofh}
* {vladlen}
* {ivy}
* {ziaee}

[[t-secteam]]
== Команда безопасности <secteam@FreeBSD.org>

Команда безопасности FreeBSD (во главе с Директором по безопасности) отвечает за информирование сообщества об ошибках, уязвимостях и рисках безопасности, затрагивающих деревья src и ports FreeBSD, а также за распространение информации, необходимой для безопасной эксплуатации систем FreeBSD.
Кроме того, она отвечает за устранение программных ошибок, влияющих на безопасность FreeBSD, и выпуск уведомлений о безопасности.
Должностная инструкция Директора по безопасности FreeBSD подробно описывает обязанности и ответственность Директора по безопасности.

* {gordon} (Директор)
* {allanjude} (Представитель Управляющей команды)
* {delphij} (Почётный директор, представитель Команды подготовки релизов)
* {des} (Почётный директор)
* {emaste} (Заместитель директора)
* {khorben}
* {markj}
* {oshogbo}
* {philip}

[[t-ports-secteam]]
== Команда безопасности портов FreeBSD <ports-secteam@FreeBSD.org>

Основной обязанностью команды безопасности портов FreeBSD является обеспечение оперативного реагирования на инциденты безопасности, затрагивающие коллекцию портов FreeBSD, и защита сообщества пользователей FreeBSD за счёт постоянного информирования сообщества об ошибках, уязвимостях, популярных атаках и других рисках.
Более подробная информация доступна на https://wiki.freebsd.org/PortsSecteam[странице Wiki].

* {fernape}
* {fluffy}
* {joneum}
* {riggs}
* {tz}

[[t-vendor]]
== Отдел по связям с вендорами <vendor-relations@FreeBSD.org>

Отдел по связям с вендорами отвечает за обработку электронной почты от производителей аппаратного и программного обеспечения.
Письма, направляемые в Отдел по связям с вендорами, пересылаются в Управляющую команду FreeBSD, а также в Фонд FreeBSD.

[[t-core-secretary]]
== Секретарь Управляющей команды <core-secretary@FreeBSD.org>

Секретарь Управляющей команды FreeBSD входит в Управляющую команду без права голоса и является ответственным за документирование работы, выполненной Управляющей командой, отслеживание текущей повестки для Управляющей команды, связь с участниками, не входящими в Управляющую команду, от её имени, а также отправку писем в адрес Управляющей команды и взаимодействие с Командой администрирования по вопросам согласования коммиттеров/учётных записей.
Секретарь Управляющей команды также отвечает за написание и рассылку ежемесячных отчётов о состоянии работ сообществу разработчиков FreeBSD, содержащих сводку последних решений и действий Управляющей команды.

* (vacant)

[[t-doceng-secretary]]
== Секретарь Команды подготовки документации <doceng-secretary@FreeBSD.org>

Секретарь Команды подготовки документации FreeBSD является её участником без права голоса, ответственным за документирование работы, выполненной doceng, отслеживание процедур голосования и взаимодействие с другими командами, особенно с Управляющей командой и Командой администрирования.

В настоящее время секретарь Команды подготовки документации не назначен; письма пересылаются в Команду подготовки документации.

[[t-portmgr-secretary]]
== Секретарь Команды управления портами <portmgr-secretary@FreeBSD.org>

Секретарь Команды управления портами FreeBSD является членом команды управления портами без права голоса, ответственным за документирование работы, выполненной portmgr, отслеживание процедур голосования и взаимодействие с другими командами, особенно с Управляющей командой и Командой администрирования.
Секретарь Команды управления портами также отвечает за написание и рассылку ежемесячных отчётов, содержащих сводку последних решений и действий portmgr, сообществу разработчиков FreeBSD.

* (vacant)

[[t-srctmgr-secretary]]
== Секретарь Команды управления исходным кодом <srcmgr-secretary@FreeBSD.org>

В настоящее время секретарь Команды управления исходным кодом не назначен; письма пересылаются в Команду управления исходным кодом.

[[t-accounts]]
== Команда управления учётными записями <accounts@>
////
Почтовые псевдонимы администраторов намеренно оставлены неполными
////

Команда управления учётными записями отвечает за настройку учётных записей для новых коммиттеров в проекте.
Запросы на создание новых учётных записей не будут обработаны без соответствующего одобрения от уполномоченного органа.

Письма, отправленные в Команду управления учётными записями, обрабатываются Администраторами кластера.

[[t-backups]]
== Администраторы резервного копирования <backups@>
////
Почтовые псевдонимы администраторов намеренно оставлены неполными
////

Администраторы резервного копирования обрабатывают все операции резервного копирования в кластере FreeBSD.

Письма, отправленные в Команду резервного копирования, обрабатываются Администраторами кластера.

[[t-bugmeister]]
== Ответственный за ошибки (Bugmeister) <bugmeister@FreeBSD.org>

Команда ответственного за ошибки отвечает за обеспечение работоспособности программного обеспечения для отчетов о проблемах, правильную категоризацию записей и отсутствие недопустимых записей.

* {linimon}
* {siva}
* {ziaee}

[[t-clusteradm]]
== Администраторы кластера <clusteradm@>
////
Почтовые псевдонимы администраторов намеренно оставлены неполными
////

Администраторы кластера отвечают за обслуживание машин и служб, от которых проект зависит для своей распределенной работы и коммуникации.
Вопросы, касающиеся инфраструктуры проекта, или настройки новых машин или служб, следует направлять им.
Этой командой руководит ведущий администратор кластера, чьи обязанности и ответственность подробно описаны в https://www.freebsd.org/internal/clusteradm/[уставе администрирования кластера].

* {bapt}
* {bofh}
* {dbaio}
* {dhw}
* {lwhsu}
* {peter}
* {philip}
* {zi} (Руководитель)

Пожалуйста, рассмотрите возможность использования одного из более конкретных псевдонимов (например, accounts@, dnsadm@, mirror-admin@,...) или https://bugs.freebsd.org/submit/[создания отчета об ошибке] для сообщения о проблемах с инфраструктурой кластера. Выберите "Services", а затем "Core Infrastructure".

[[t-dnsadm]]
== Администраторы DNS <dnsadm@>
////
Почтовые псевдонимы администраторов намеренно оставлены неполными
////

Администраторы DNS отвечают за управление службами DNS и связанными с ними службами.

Письма, отправленные администраторам DNS, обрабатываются Администраторами кластера.

[[t-forum-admins]]
== Администраторы форумов FreeBSD <forum-admins@FreeBSD.org>

Администраторы форумов поддерживают форум проекта FreeBSD в Интернете, расположенный по адресу https://forums.freebsd.org/, и руководят группой модераторов, которые работают над обеспечением релевантности и качества контента форума.

* {brd}
* {danger}
* {dutchdaemon}
* {lme}

[[t-git]]
== Администраторы Git <gitadm@>
////
Почтовые псевдонимы администраторов намеренно оставлены неполными
////

Администраторы Git FreeBSD отвечают за поддержание работоспособности репозиториев Git.

Письма администраторам Git обрабатываются Администраторами кластера.

Пожалуйста, https://bugs.freebsd.org/submit/[создайте отчет об ошибке] для сообщения о проблемах с репозиториями Git. Выберите "Services", а затем "Core Infrastructure".

[[t-github-automation]]
== Координаторы автоматического зеркалирования репозиториев на GitHub <github-automation@FreeBSD.org>

Команда автоматизации GitHub контролирует перенос содержимого хранилища исходного кода FreeBSD в соответствующие репозитории GitHub, доступные только в режиме просмотра.

* {koobs}
* {mva}
* {robak}
* {rodrigc}
* {uqs}

[[t-jenkins-admin]]
== Администраторы непрерывного тестирования Jenkins <jenkins-admin@FreeBSD.org>

Администраторы Jenkins поддерживают инфраструктуру непрерывной интеграции и тестирования для проекта FreeBSD.
Это включает в себя обслуживание экземпляра Jenkins и заданий, которые выполняют сборки и запускают тесты.

* {bapt}
* {brd}
* {brooks}
* {lwhsu}
* {siva}

[[t-mirror-admin]]
== Координаторы сайтов-зеркал FTP/WWW <mirror-admin@>
////
Почтовые псевдонимы администраторов намеренно оставлены неполными
////

Координаторы сайтов-зеркал FTP/WWW координируют всех администраторов сайтов-зеркал FTP/WWW, чтобы обеспечить распространение текущих версий программного обеспечения, наличие у них возможности обновляться при выполнении крупных обновлений и упростить для широкой публики поиск ближайшего FTP/WWW зеркала.

Письма координаторам сайтов-зеркал обрабатываются Администраторами кластера.

Пожалуйста, https://bugs.freebsd.org/submit/[создайте отчет об ошибке] для сообщения о проблемах с инфраструктурой зеркал. Выберите "Services", а затем "FTP/WWW Sites & Mirrors".

[[t-phabric-admin]]
== Администраторы приложения для рецензирования кода Phabricator <phabric-admin@FreeBSD.org>

Администраторы Phabricator отвечают за поддержку экземпляра онлайнового инструмента рецензирования кода Phabricator для FreeBSD, расположенного по адресу https://reviews.freebsd.org/

* {allanjude}
* {bofh}
* {eadler}
* {emaste}
* {jtl}
* {lwhsu}
* {mat}
* {pi}

По любым проблемам, связанным с Phabricator, пожалуйста, https://bugs.freebsd.org/submit/[создайте отчёт об ошибке] и выберите "Services", а затем "Code Review".

[[t-postmaster]]
== Почтовые администраторы (Postmaster Team) <postmaster@FreeBSD.org>

Почтовая команда отвечает за корректную доставку почты на адреса электронной почты коммиттеров, обеспечение работы списков рассылки и должна принимать меры против возможных сбоев в работе почтовых служб проекта, таких как настройка фильтров против троллинга, спама и вирусов.

* {bapt}
* {ler}
* {philip}
* {pi}
* {rea}
* {vsevolod}
* {zi}

[[t-webmaster]]
== Команда веб-мастеров <webmaster@FreeBSD.org>

Команда веб-мастеров FreeBSD назначается Командой подготовки документации FreeBSD и отвечает за поддержание работы основных веб-сайтов FreeBSD.
Это означает конфигурацию веб-сервера, CGI-скрипты, полнотекстовый поиск и поиск по спискам рассылки. Все, что связано с веб-технологиями, входит в сферу ответственности команды веб-мастеров, за исключением ошибок в документации.

Письма в команду веб-мастеров в настоящее время пересылаются в Команду подготовки документации с добавлением:

* {wosch}

[[t-wiki]]
== Команда администрирования Вики <wiki-admin@FreeBSD.org>

Команда Вики FreeBSD отвечает за поддержание работоспособности сайта https://wiki.FreeBSD.org/[Вики] FreeBSD. Она также определяет общий дизайн и структуру контента.

Сообщения электронной почты, направляемые администраторам Вики, обрабатываются администраторами кластера.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (21.06.2026): 6ae188e12756359415577a140603168756ec2758
//
