---
title: "О приложениях для FreeBSD"
sidenav: about
---

= О приложениях для FreeBSD

== Используйте возможности FreeBSD

FreeBSD может делать работу, которую обычно выполняют рабочие станции UNIX(R), впрочем, она также может делать и работу, о возможности выполнения которой вы можете и не подозревать:

== FreeBSD является самой настоящей операционной системой, поставляемой со всеми исходными текстами.

Несомненно то, что использование так называемых открытых систем является _требованием_ организации вычислительного процесса в современных условиях. Однако не существует коммерческого продукта, более открытого, чем то, которое включает полные исходные тексты всей операционной системы, включая ядро и все системные даемоны, программы и утилиты. Вы можете модифицировать любую часть FreeBSD, если это требуется вам, вашей организации или фирме.

Согласно общей link:../copyright/freebsd-license/[политике лицензирования] FreeBSD, вы можете использовать её как основу для любого количества свободно распространяемых или _коммерческих_ приложений.

== С FreeBSD работают тысячи приложений.

Так как FreeBSD основывается на 4.4BSD, стандартной промышленной версии UNIX, компилировать и запускать программы достаточно легко. FreeBSD также включает большую link:../where/[коллекцию пакаджей] и link:../ports/[коллекцию портов], что обеспечивает лёгкость компиляции и установки уже откомпилированного программного обеспечения на вашей рабочей машине или сервере. Имеется также всё увеличивающееся количество link:../commercial/software/[коммерческих приложений], написанных для FreeBSD.

Вот некоторые области деятельности, в которых используется FreeBSD:

* *Предоставление услуг Internet.* Многие провайдеры Internet (ISP) находят, что FreeBSD является для них идеальным решением, и организуют под её управлением Web-серверы, серверы конференций Usenet, сервисы FTP, электронной почты, и другие услуги. Наличие готового к использованию программное обеспечение типа Web-сервера http://www.apache.org/[Apache] или FTP сервера ProFTPD упрощает развертывание ISP в какой-либо фирме или географической области. Конечно, пользуясь несравненными link:../internet/[сетевыми возможностями] FreeBSD, ваши пользователи будут довольны высокой скоростью и надежностью услуг.
* *Графическая рабочая станция X Window.* FreeBSD может прекрасно работать как в роли дешёвого X терминала, так и в роли богатого возможностями X дисплея. Свободное программное обеспечение для X (http://x.org/[X.Org](TM)) поставляется вместе с системой. Компания http://www.nvidia.com/[nVidia] предоставляет драйверы для собственных высокопроизводительных графических адаптеров; поддерживаются библиотеки, реализующие промышленные стандарты Motif(R) и OpenGL(R). Графические оболочки http://www.kde.org[KDE] и http://www.gnome.org[GNOME] обеспечивают полную поддержку и предоставляют функциональность офисных приложений, ещё в большей степени развитую в пакетах http://www.openoffice.org/[OpenOffice.Org] и http://www.softmaker.de/tml_en.htm[TextMaker].
* *Сетевые возможности.* Возможности FreeBSD, от фильтрации пакетов до маршрутизации и сервиса имён, могут превратить ваш ПК в сетевой экран Internet, почтовый сервер, сервер печати, сервер PC/NFS и многое другое.
* *Разработка программного обеспечения.* Набор инструментов для разработчика, поставляемый с FreeBSD, включает компилятор GNU C/C++ и отладчик и язык написания скриптов Perl. Возможно ведение разработок на языках Java(R) и Tcl/Tk. Также прекрасно работают популярные текстовые редакторы типа XEmacs и другие эзотерические языки программирования типа Icon. А совместно используемые библиотеки во FreeBSD всегда были просты для создания и использования.
* *Работа в Internet.* Настоящая рабочая станция UNIX является хорошим средством работы в Internet. Серьёзным пользователям Web-технологий предназначены FreeBSD-версии http://www.mozilla.org/products/firefox/[Firefox] и http://www.opera.com/[Opera]. Вы можете бродить по Internet, помещать там ваши странички, читайте новости Usenet, посылать и принимать электронную почту с помощью системы FreeBSD на вашем рабочем месте.
* *Образование и исследовательская деятельность.* FreeBSD является прекрасной платформой для научно-исследовательской деятельности, потому что поставляется вместе с исходными текстами системы. Студенты и специалисты в области операционных систем или других областях информатики много могут получить от подобной открытой и хорошо документированной системы.
* *И много чего ещё.* Бухгалтерский учёт, игры, базы данных MIS, визуализация научных расчетов, видеоконференции, системы BBS, сканирование изображений и много для чего ещё реально можно использовать FreeBSD сегодня.

== FreeBSD - это операционная система, вырастающая вместе с ростом ваших потребностей.

Хотя FreeBSD относится к классу свободно распространяемого программного обеспечения, она также является программным обеспечением, _поддерживаемым её пользователями_. Любой вопрос, который у вас имеется, может быть послан сотням разработчиков FreeBSD и её пользователям по электронной почте на адрес списка рассылки freebsd-questions@FreeBSD.org.

В проекте FreeBSD участвует группа программистов и писателей, которые исправляют ошибки, добавляют новые возможности и документируют систему. Поддержка новых устройств или специальных возможностей является постоянным процессом разработки, и команда разработчиков обращает особое внимание на проблемы, которые касаются стабильности системы. Пользователи FreeBSD гордятся не только производительностью, но и надёжностью этой системы.

== Вот что говорят специалисты . . .

_``FreeBSD справляется с [нашей] большой нагрузкой достаточно хорошо и это не удивительно. Салют команде разработчиков FreeBSD.''_

---Марк Хиттингер (Mark Hittinger), администратор WinNet Communications, Inc.
