---
title: "О приложениях для FreeBSD"
sidenav: about
---

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (20.09.2024): 6fcd17d9dcdd12cd69fe2007c13d7a83a07c7e3a
//

= О приложениях для FreeBSD

== Испытайте возможности FreeBSD

FreeBSD может выполнять практически любую работу, исполнение которой можно ожидать от рабочей станции UNIX(R), а также многое из того, о чём вы можете и не подозревать:

== FreeBSD является по-настоящему открытой системой с полным исходным кодом.

Нет сомнений в том, что использование так называемых открытых систем является _требованием_ к современному прикладному программному обеспечению. Однако никакое поставляемое коммерческое решение не будет более открытым, чем то, что содержит полный исходный код всей операционной системы, включая ядро и все системные даемоны, программы и утилиты. Вы можете модифицировать любую часть FreeBSD в соответствии с вашими потребностями или требованиями вашей организации или компании.

Располагая широкими возможностями link:../copyright/freebsd-license/[политики лицензирования] FreeBSD, вы можете использовать её в качестве основы для любого количества свободно распространяемых или _коммерческих_ приложений.

== Во FreeBSD работают тысячи приложений.

Так как FreeBSD основывается на 4.4BSD, стандартной промышленной версии UNIX, компилировать и запускать программы несложно. Также во FreeBSD имеется обширная коллекция пакетов и link:../ports/[портов], которые обеспечивают простую сборку и  установку уже откомпилированного программного обеспечения на ваш настольный компьютер или корпоративный сервер. Также растёт количество link:../commercial/software/[коммерческих приложений], написанных для FreeBSD.

Вот некоторые примеры областей деятельности, в которых используется FreeBSD:

* *Услуги Интернет.* Многие поставщики услуг Интернет находят FreeBSD идеальным решением, обеспечивающим работу веб-серверов, серверов конференций Usenet, сервисов FTP, электронной почты и других. Наличие готового к использованию программное обеспечение, подобного веб-серверу http://nginx.org[NGINX] или http://www.apache.org/[Apache], серверу FTP http://proftpd.org/[ProFTPD] или http://security.appspot.com/vsftpd.html[vsftpd] упрощает разворачивание сервисов Интернет на коммерческих или общественных началах. Учитывая наличие во FreeBSD несравненных link:../internet/[сетевых возможностей], ваши пользователи будут довольны надёжностью услуг и высокой скоростью.
* *Рабочая станция X Window.* FreeBSD достаточно хорошо работает как в качестве недорогого X-терминала, так и в роли продвинутого X-дисплея. Свободное программное обеспечение для X (https://x.org/[X.Org](T)) поставляется вместе с системой. https://www.nvidia.com/[NVIDIA] предоставляет драйверы для собственных высокопроизводительных графических адаптеров, также поддерживаются библиотеки, реализующие промышленные стандарты https://www.opengroup.org/motif/[Motif](R) и https://www.opengl.org/[OpenGL](R). Продукты https://xfce.org/[Xfce] и https://lxde.org/[LXDE] реализуют окружение рабочего стола. Графические оболочки https://www.kde.org[KDE] и https://www.gnome.org[GNOME] обеспечивают полную поддержку и реализуют функциональность офисных приложений, в ещё большей степени развитую в продуктах https://www.libreoffice.org/[LibreOffice] и https://www.openoffice.org/[OpenOffice.Org].
* *Сети передачи данных.* От фильтрации пакетов и маршрутизации до сервиса преобразования имён, возможности FreeBSD могут превратить ваш персональный компьютер в межсетевой экран Интернет, почтовый сервер, сервер печати, сервер PC/NFS и много что ещё.
* *Разработка программного обеспечения.* Набор https://docs.freebsd.org/ru/books/developers-handbook/tools/[инструментов для разработки], поставляемый с FreeBSD, включает clang, являющийся компилятором и отладчиком C/C++, основанным на LLVM. Также возможно ведение разработок на языках Java(R) и Tcl/Tk. А совместно используемые библиотеки FreeBSD всегда были просты для создания и использования. Кроме того, вам доступен широкий выбор мощных и популярных редакторов, таких как Emacs и Vim.
* *Работа в Сети.* Настоящая рабочая станция UNIX является хорошим средством работы в Интернет. Серьёзным пользователям Сети доступны версии http://www.chromium.org/Home[Chromium] и http://www.mozilla.org/firefox/[Firefox] для FreeBSD. Бродите в Сети, публикуйте собственные веб-страницы, читайте новости Usenet, а также отправляйте и принимайте электронную почту с помощью системы FreeBSD на вашем настольном компьютере.
* *Образование и исследовательская деятельность.* FreeBSD является прекрасной платформой для научно-исследовательской деятельности, потому что включает полный исходный код. Студенты и исследователи в области операционных систем или других областях информатики могут многое получить от подобной открытой и хорошо документированной системы.
* *И много чего ещё.* Бухгалтерский учёт, динамичные игры, базы данных MIS, визуализация научных данных, видеоконференции, групповые коммуникации (IRC), домашняя автоматика, многопользовательские подземелья, системы BBS, сканирование изображений и много чего ещё являются актуальными и реальными примерами использования FreeBSD.

== FreeBSD - операционная система, которая будет расти вместе с вашими потребностями.

Хотя FreeBSD является свободно распространяемым программным обеспечением, она также является программным обеспечением, _поддерживаемым её пользователями_. Любой интересующий вас вопрос может быть легко направлен сотням разработчиков и пользователей FreeBSD по электронной почте в адрес списка рассылки freebsd-questions@FreeBSD.org.

Во FreeBSD также имеется международная группа программистов и писателей, которые исправляют недочёты, добавляют новые функции и документируют систему. Поддержка новых устройств или специальных возможностей является практически непрерывным процессом разработки, и эта команда уделяет особое внимание проблемам, которые влияют на стабильность системы. Пользователи FreeBSD очень гордятся не только высокой производительностью, но и надёжностью своих систем.

== Вот что говорят специалисты . . .

_"FreeBSD весьма хорошо справляется с [нашей] высокой нагрузкой, и это потрясающе. Честь и хвала команде FreeBSD."_

[.right]
---Марк Хиттинджер, администратор WinNet Communications, Inc.
