---
title: "О работе FreeBSD в сетях"
sidenav: about
---

include::shared/ru/urls.adoc[]

= О работе FreeBSD в сетях

== FreeBSD предназначена для работы в Internet

В поставку FreeBSD включен стек протоколов TCP/IP от 4.4BSD, который признается многими _эталонной_ реализацией программного обеспечения TCP/IP, что позволяет считать FreeBSD идеальным решением для работы сетевых приложений и Internet.

== FreeBSD поддерживает стандартные протоколы TCP/IP.

Как и большинство систем UNIX(R), операционная система FreeBSD позволит вам

* Организовать совместное использование файлов с помощью NFS
* Распространять информацию по сети с помощью NIS
* Осуществлять дистанционный вход в систему
* Осуществлять дистанционное управление и конфигурирование по SNMP
* Передавать файлы по протоколу FTP
* Организовать службу имен Internet с помощью DNS/BIND
* Маршрутизировать пакеты между многими интерфейсами, включая каналы PPP и SLIP
* Использовать службы широковещательной передачи (MBONE)

С помощью поставляемого вместе с системой программного обеспечения FreeBSD позволяет вам превратить ваш PC в сервер World Wide Web или сервер новостей Usenet. С помощью программного обеспечения SAMBA вы даже можете использовать файловые системы или принтеры совместно с машинами Win95 и NT и, с помощью поставляемого аутентификационного даемона PCNFS, можете поддерживать машины, использующие PC/NFS. FreeBSD также поддерживает работы в сетях Appletalk и Novell как в качестве клиента, так и сервера (с помощью http://www.netcon.com/[дополнительного коммерческого программного обеспечения]), что делает ее настоящим сетевым решением для "Intranet".

FreeBSD также поддерживает такие расширения протокола TCP, как высокопроизводительное расширение по стандарту http://www.cis.ohio-state.edu/htbin/rfc/rfc1323.html[RFC-1323], и расширение для транзакций по стандарту http://www.cis.ohio-state.edu/htbin/rfc/rfc1644.html[RFC-1644], плюс протоколы SLIP и dial-on-demand PPP. Эта операционная система может удовлетворить запросы как обычного домашнего пользователя, так и администратора корпоративной сети.

== Работа FreeBSD в сети отличается высокой производительностью и стабильностью.

Если вам нужна надёжная платформа для сервера Internet, дающая лучшую производительность при высокой нагрузке, остановите свой выбор на FreeBSD. Вот список всего лишь несколько компаний, использующих FreeBSD в своей повседневной работе:

* Walnut Creek CDROM поддерживает один из наиболее популярных FTP серверов в интернет, ftp.cdrom.com, работающий только на FreeBSD много лет. Это был один сервер FreeBSD, поддерживающий 6000 соединений и способный передавать более 30 терабайт (в июне 1999; да, _терабайт_!) файлов каждый месяц более 10 миллионам человек.
* Компания http://www.yahoo.com/[Yahoo Inc.], являющаяся создателем уникального каталога ресурсов Internet, обслуживает множество ежедневных запросов о информации в World Wide Web. Yahoo, как и другие компании, дающие свою рекламу в каталоге Yahoo, при построении надежных и всегда доступных веб-серверов полагаются на FreeBSD.
* http://www.netcraft.com/[Netcraft] это ведущие исследователи использования программного обеспечения веб серверов в интернет. Они используют FreeBSD и Apache для поддержки своего сайта и FreeBSD/Perl для сбора данных из интернет.
* Если этого вам не достаточно, посетите нашу link:../gallery/[Галерею] пользователей, довольных FreeBSD.

FreeBSD является идеальной платформой для этих и других служб Internet:

* WWW-служба для внутренних нужд компании или представительства в Internet
* Служба прокси-доступа к Internet
* Служба общедоступных серверов FTP
* Корпоративные службы доступа к файлам, печати и почты

link:../ports/[Коллекция портов] FreeBSD содержит готовое к использованию программное обеспечение, позволяющее легко создать ваш сервер Internet.

== Высокая производительность _и_ безопасность.

Разработчики FreeBSD заботятся о безопасности не в меньшей мере, чем о производительности. В ядро FreeBSD наряду с возможностью организации брандмауэра, включена, например, служба организации шлюзов IP. Если вы помещаете сервер вашей фирмы в Internet, любой компьютер с установленной FreeBSD может выступать в роли межсетевого экрана для их защиты от вторжения извне.

Криптографическое программное обеспечение, оболочки, обеспечивающие секретность, система Kerberos, шифрование передаваемых данных и поддержка протокола secure RPC также могут быть доступны (это касается законодательных ограничений на экспорт подобного программного обеспечения).

Более того, команда FreeBSD активно сотрудничает в области обнаружения и предотвращения нарушений безопасности и оформления соответствующих рекомендаций с mailto:security-officer@FreeBSD.ORG[офицером безопасности] и Группой Оперативного Реагирования по безопасности Компьютерных систем (Computer Emergency Response Team) (http://www.cert.org/[CERT]).

== Что говорят эксперты . . .

_``Похоже, что FreeBSD ... предоставляет самый надежный и полноценный стек протоколов TCP/IP из существующих ...''_

---Майкл О'Брайен (Michael O'Brien), _SunExpert_ Август 1996 volume 7 number 8.
