#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/mh/Makefile,v 1.3 2005/10/28 17:42:40 gad Exp $
#
# Original revision: r39631
#
# Article: An MH Primer

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

DOC_PREFIX?=	${.CURDIR}/../../..
.include	"${DOC_PREFIX}/share/mk/doc.project.mk"
