#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/mh/Makefile,v 1.1 2001/07/19 10:20:52 phantom Exp $
#
# Original revision: 1.1
#

MAINTAINER=	andy@FreeBSD.org.ua

DOC?=	article

FORMATS?=	html

INSTALL_COMPRESSED?=	gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?=	${.CURDIR}/../../..
.include	"${DOC_PREFIX}/share/mk/doc.project.mk"
