=== FreeBSD Core Team

Contact: FreeBSD Core Team <core@FreeBSD.org>

The FreeBSD Core Team is the governing body of FreeBSD.

==== Project roadmap

Core is collecting ideas and comments to draft Project's roadmap.
It is an item core.13 thinks is worth to continue from core.12.
The roadmap is not about restricting or limiting what developers and contributors can do, but about the compiled goals and expectations of the Project and things the community can collaborate on.
It will also let the FreeBSD Foundation help the Project more effectively, so, this is an important discussion item for the meetings between core and the FreeBSD Foundation.

==== Policy on generative AI created code and documentation

Core is investigating setting up a policy for LLM/AI usage (including but not limited to generating code).
The result will be added to the Contributors Guide in the doc repository.
AI can be useful for translations (which seems faster than doing the work manually), explaining long/obscure documents, tracking down bugs, or helping to understand large code bases.
We currently tend to not use it to generate code because of license concerns.
The discussion continues at the core session at BSDCan 2025 developer summit, and core is still collecting feedback and working on the policy.

==== Work in Progress

Core is currently working on the following items:

* Core and the FreeBSD Foundation are working on the 2025 edition of the Community survey
* Privacy-friendly web analytics, proposed by the Foundation.
  An idea is to compare traffic flows between freebsd.org and freebsdfoundation.org
