=== FreeBSD Release Engineering Team

Links: +
link:https://www.freebsd.org/releases/14.3R/announce/[FreeBSD 14.3-RELEASE announcement] URL: link:https://www.freebsd.org/releases/14.3/announce/[] +
link:https://www.freebsd.org/releases/15.0R/schedule/[FreeBSD 15.0-RELEASE schedule] URL: link:https://www.freebsd.org/releases/15.0R/schedule/[] +
link:https://download.freebsd.org/releases/ISO-IMAGES/[FreeBSD releases] URL: link:https://download.freebsd.org/releases/ISO-IMAGES/[] +
link:https://download.freebsd.org/snapshots/ISO-IMAGES/[FreeBSD development snapshots] URL: link:https://download.freebsd.org/snapshots/ISO-IMAGES/[]

Contact: FreeBSD Release Engineering Team, <re@FreeBSD.org>

The FreeBSD Release Engineering Team is responsible for setting and publishing release schedules for official project releases of FreeBSD, announcing code freezes and maintaining the respective branches, among other things.

The Team managed 14.3-RELEASE, leading to the official RELEASE build and announcement in June.
Planning has started for the upcoming 15.0-RELEASE, which is due to arrive in December.

The OCI Container Images built by the Release Engineering Team are now being uploaded to Docker and GitHub repositories in addition to being available on the FreeBSD download site.

The Team gained a new member, mailto:jfree@FreeBSD.org[Jake Freeland], and three members have departed: mailto:kib@FreeBSD.org[Konstantin Belousov], mailto:jhixson@FreeBSD.org[John Hixson], mailto:dfr@FreeBSD.org[Doug Rabson].
We thank them for their contributions.

The Release Engineering Team continued providing weekly development snapshot builds for the *main*, *stable/14*, and *stable/13* branches.
