---
title: 6. Fejezet - Asztali alkalmazások
part: Μέρος II. Βασικές Εργασίες
prev: books/handbook/partii
next: books/handbook/multimedia
---

[[desktop]]
= II. Rész Gyakori feladatok
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Tartalom
:table-caption: Táblázat
:figure-caption: Ábra
:example-caption: Példa
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 6

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/hu/mailing-lists.adoc[]
include::shared/hu/teams.adoc[]
include::shared/hu/urls.adoc[]

toc::[]

[[desktop-synopsis]]
== Áttekintés

A FreeBSD-n asztali alkalmazások széles spektrumát lehet futtatni, például böngészõket és szövegszerkesztõket. Legtöbbjük csomagként áll rendelkezésre, illetve automatizált módon lefordíthatóak a Portgyûjteménybõl. Az új felhasználók közül sokan szeretnének ilyen fajta alkalmazásokat használni, ezért ez a fejezet bemutatja, miként lehet a népszerûbb asztali alkalmazásokat minden különösebb erõfeszítés nélkül telepíteni, legyen szó az elõre csomagolt vagy a Portgyûjteményben megtalálható formájukról.

Amikor portként telepítünk egy programot, lényegében a forráskódját fordítjuk le. Ez bizonyos esetekben nagyon sokáig is eltarthat attól függõen, hogy pontosan mit is fordítunk le, illetve mekkora az erre a célra felhasznált számítógépünk vagy számítógépeink teljesítménye. Amennyiben a fordításra nem tudunk vagy nem kívánunk elegendõ idõt szánni, a Portgyûjteményben található programok többségét már elõre lefordított csomagból is telepíthetjük.

Mivel a FreeBSD-ben bináris szintû Linux kompatibilitás is található, ezért az eredetileg Linuxra fejlesztett alkalmazások is használhatóak a munkakörnyezetünkben. Azonban határozottan javasoljuk, hogy a linuxos alkalmazások használatához elõször figyelmesen olvassuk át a crossref:linuxemu[linuxemu,Bináris Linux kompatibilitás]et. A linuxos bináris kompabilitást használó portok neve általában a "linux-" elõtaggal kezdõdik, amit ne felejtsük el figyelembe venni, amikor például a man:whereis[1] segítségével keressük valamelyiket. A fejezet további részében feltételezzük, hogy a linuxos alkalmazások telepítése elõtt aktiváltuk a bináris Linux kompatibilitást.

Íme a fejezetben tárgyalt kategóriák:

* Böngészõk (mint a Firefox, Opera, Konqueror)
* Irodai eszközök (mint a KOffice, AbiWord, The GIMP, OpenOffice.org)
* Dokumentum-megjelenítõk (mint az Acrobat Reader(R), gv, Xpdf, GQview)
* Pénzügyi szoftverek (mint a GnuCash, Gnumeric, Abacus)

A fejezet elolvasásához ajánlott:

* a külsõ alkalmazások telepítésének ismerete (crossref:ports[ports,Alkalmazások telepítése. csomagok és portok]);
* linuxos alkalmazások telepítésének ismerete (crossref:linuxemu[linuxemu,Bináris Linux kompatibilitás]).

a multimédiás környezet kialakítására vonatkozó információkért a crossref:multimedia[multimedia,Multimédia]et érdemes elolvasni. Az elektronikus levelezés beállítását és használatát a crossref:mail[mail,Elektronikus levelezés]bõl tudhatjuk meg.

[[desktop-browsers]]
== Böngészõk

A FreeBSD-vel együtt nem települ semmilyen böngészõ. Helyette keressük meg a Portgyûjteményben a http://www.FreeBSD.org/ports/[www] könyvtárat, ahol ezzel szemben rengeteg böngészõ áll telepítésre készen. Ha nem lenne idõnk mindent lefordítani (ami egyes esetekben akár rengeteg idõnkbe is kerülhet), ezek csomagolt formában is elérhetõek.

A KDE-hez és a GNOME-hoz eleve tartoznak HTML-böngészõk. Ezen komplett munkakörnyezetek beállításához a crossref:x11[x11-wm,Munkakörnyezetek]t olvassuk el.

Ha viszont csak egy kevés erõforrást igénylõ böngészõkre vágyunk, érdemes megnéznünk a Portgyûjteményben található package:www/dillo2[], package:www/links[] vagy package:www/w3m[] portokat.

Ez a rész az alábbi alkalmazásokat említi:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Alkalmazás
| Erõforrásigény
| Telepítés forrásból
| Fõbb függõségek

|Firefox
|közepes
|nehéz
|Gtk+

|Opera
|kevés
|könnyû
|Vannak FreeBSD-s és linuxos változatai is. A linuxos verzió használatához azonban szükség van a bináris Linux kompatibilitásra és a linux-openmotif portra.

|Konqueror
|közepes
|nehéz
|A KDE függvénykönyvtárai.
|===

=== Firefox

A Firefox egy modern, szabad és nyílt forráskódú böngészõ, amely tökéletesen használható FreeBSD alatt. Megtalálható benne egy, a jelenlegi HTML szabványoknak nagyon jól megfelelõ megjelenítõ motor, a lapokra bontható böngészés támogatása, a kéretlenül felbukkanó ablakok blokkolása, különbözõ kiterjesztések, javított biztonsági lehetõségek és még sok minden más. A Firefox forrása a Mozilla kódján alapszik.

Csomagból így telepíthetõ:

[source,bash]
....
# pkg_add -r firefox
....

Ekkor a Firefox 3.6 változata fog települni. Ha helyette a Firefox 3.5 változatát szeretnénk használni, akkor ezt a parancsot adjuk ki:

[source,bash]
....
# pkg_add -r firefox35
....

Ha forrásból szeretnénk felrakni, használhatjuk a Portgyûjteményben található portját is:

[source,bash]
....
# cd /usr/ports/www/firefox
# make install clean
....

A Firefox 3.5 telepítéséhez az iménti parancsban cseréljük ki a `firefox` részt a `firefox35` könyvtárra.

[[moz-java-plugin]]
=== A Firefox és a Java(TM) plugin

[NOTE]
====
Ennél és a következõ résznél feltételezzük, hogy már korábban telepítettük a Firefox alkalmazást.

A Java(TM) plugin jelenleg nem mûködik a Firefox 3.6 változatával.
====

A FreeBSD Alapítvány megegyezett a Sun Microsystems-szel, hogy terjesztheti a Java(TM) futtatókörnyezet (JRE(TM)) és a Java(TM) fejlesztõkörnyezet (JDK(TM)) FreeBSD-re lefordított bináris változatait. Ezek a csomagok elérhetõek a http://www.freebsdfoundation.org/downloads/java.shtml[FreeBSD Alapítvány] honlapjáról.

Ha tehát Java(TM)-támogatást szeretnénk hozzáadni a Firefox böngészõhöz, elsõként fel kell telepítenünk a package:java/javavmwrapper[] portot. Ezután le kell töltenünk a Diablo JRE(TM) csomagot a http://www.freebsdfoundation.org/downloads/java.shtml[http://www.freebsdfoundation.org/downloads/java.shtml] címrõl, majd telepítenünk azt a man:pkg_add[1] segítségével.

[NOTE]
====
Ezen az oldalon nem találunk bináris csomagokat FreeBSD 8._X_ rendszerekhez, azonban a FreeBSD 7._X_ rendszerekhez készült csomagok használhatóak 8._X_ esetén is. Ehhez mindössze a package:misc/compat7x[] portot kell elõtte telepítenünk.

A másik lehetõség a Diablo JRE(TM) (valamint a Diablo JDK(TM)) telepítése a Portgyûjteménybõl (package:java/diablo-jre16[] és package:java/diablo-jdk16[]). Ehhez a szükséges forrásokat (distfile állományokat) licencelési megkötések miatt nekünk kell külön letölteni. A kapcsolódó utasításokat a `make maketarget` parancs meghívásával kaphatjuk meg.
====

Indítsuk el a böngészõnket, és írjuk be a címsorba, hogy `about:plugins` és nyomjuk le az kbd:[Enter] billentyût. Az eredményül kapott oldalon láthatjuk az eddig telepített pluginok listáját, ahol mostanra már a Java(TM) pluginnak is meg kell jelennie. Amennyiben ez nem következne be, mindegyik felhasználónál adjuk ki az alábbi parancsot:

[source,bash]
....
% ln -s /usr/local/diablo-jre1.6.0/plugin/i386/ns7/libjavaplugin_oji.so \
  $HOME/.mozilla/plugins/
....

Vagy ha a Diablo JDK(TM) csomagot telepítettük:

[source,bash]
....
% ln -s /usr/local/diablo-jdk1.6.0/jre/plugin/i386/ns7/libjavaplugin_oji.so \
  $HOME/.mozilla/plugins/
....

Ezt követõen indítsuk újra a böngészõnket.

[NOTE]
====
Ezek a parancsok az i386 architektúra használatát feltételezik, de a csomagok az amd64 architektúra esetén is elérhetõek.
====

[[moz-flash-plugin]]
=== A Firefox és a Macromedia(R) Flash(TM) plugin

A Macromedia(R) Flash(TM) plugin nem érhetõ el közvetlenül FreeBSD-re. Azonban létezik egy, a plugin linuxos verziójára épített szoftveres réteg (wrapper). Ez a wrapper még többek közt az Adobe(R) Acrobat(R) és a RealPlayer(R) pluginjait is használhatóvá teszi.

Attól függõen, hogy a FreeBSD melyik változatát használjuk, különbözõ módokon tudjuk mûködésbe hozni:

[.procedure]
====
. FreeBSD 7._X_
+ 
Telepítsük a package:www/nspluginwrapper[] portot. Ehhez szükség lesz még az package:emulators/linux_base-fc4[] portra is, amely viszonylag nagy méretû.
+ 
Következõ lépésként telepítsük a package:www/linux-flashplugin9[] portot. Ezáltal megkapjuk a Flash(TM) 9._X_ változatát, amely FreeBSD 7._X_ alatt remekül mûködik.
+
[NOTE]
======
A 7.1-RELEASE elõtti FreeBSD verziók esetén a package:www/linux-flashplugin7[] portot telepítsük és hagyjuk ki a man:linprocfs[5] használatára vonatkozó részt.
======
+
. FreeBSD 8._X_
+ 
Telepítsük a package:www/nspluginwrapper[] portot. Ehhez szükségünk lesz majd a valamivel nagyobb package:emulators/linux_base-f10[] portra.
+ 
Ezt követõen telepítsük a package:www/linux-f10-flashplugin10[] portot. Ekkor a Flash(TM) 10._X_ változatát kapjuk, amely FreeBSD 8._X_ alatt remekül használható.
+ 
Ezen változat beüzemeléséhez még létre kell hoznunk az alábbi linket:
+
[source,bash]
....
# ln -s /usr/local/lib/npapi/linux-f10-flashplugin/libflashplayer.so \
  /usr/local/lib/browser_plugins/
....
====

Miután a FreeBSD rendszerünk változatának megfelelõen elvégeztük a Flash(TM) port telepítését, a plugint az egyes felhasználóknak a `nspluginwrapper` paranccsal tehetjük elérhetõvé:

[source,bash]
....
% nspluginwrapper -v -a -i
....

Ha Flash(TM) animációkat szeretnénk lejátszani, akkor ehhez a [.filename]#/usr/compat/linux/proc# könyvtárba csatlakoztatnunk kell egy man:linprocfs[5] típusú linuxos proc állományrendszert. Ezt a következõ paranccsal tehetjük meg:

[source,bash]
....
# mount -t linprocfs linproc /usr/compat/linux/proc
....

Az [.filename]#/etc/fstab# állományban az alábbi sor hozzáadásával azonban ennek csatlakoztatása akár automatikussá is tehetõ a rendszerindítás során:

[.programlisting]
....
linproc  /usr/compat/linux/proc  linprocfs      rw       0       0
....

Ezután indítsuk el a böngészõt, majd gépeljük be az `about:plugins` szöveget a címsorba és nyomjuk le az kbd:[Enter] billentyût. Ekkor a jelenleg elérhetõ pluginok listájának kell megjelennie.

[[moz-swfdec-flash-plugin]]
=== A Firefox és az Swfdec Flash(TM) plugin

Az Swfdec egy Flash(TM) animációk dekódolásáért és megjelenítéséért felelõs programkönyvtár. Az Swfdec-Mozilla pedig egy Firefox böngészõkhöz készített plugin, amely az Swfdec könyvtáron keresztül játszik le SWF állományokat. Jelenleg még aktív fejlesztés alatt áll.

Ha nem akarjuk vagy netalán nem tudjuk forrásból lefordítani, akkor egyszerûen csak telepítsük csomagként a hálózaton keresztül:

[source,bash]
....
# pkg_add -r swfdec-plugin
....

Ha valamiért mégsem érhetõ el hozzá csomag, akkor a Portgyûjteménybõl is telepíthetjük:

[source,bash]
....
# cd /usr/ports/www/swfdec-plugin
# make install clean
....

Miután telepítettük a plugint, a használatához indítsuk újra a böngészõt.

=== Opera

Az Opera egy sokoldalú és szabványokkal kompatibilis böngészõ. Tartalmaz beépített levelezõ klienst és hírolvasót, IRC-klienst, RSS/Atom-olvasót és még sok mindent mást. Ennek ellenére az Opera viszonylag pehelysúlyúnak és gyorsnak számít. Két fajta módon is használható: létezik "natív" FreeBSD-s változata, valamint a Linux emulációval futó változata.

Az Opera FreeBSD-s változatát a megfelelõ csomag telepítésével érhetjük el:

[source,bash]
....
# pkg_add -r opera
....

Habár egyes FTP oldalakon nem található meg az összes csomag, viszont a Portgyûjteménybõl még ekkor is be tudjuk szerezni az Operat:

[source,bash]
....
# cd /usr/ports/www/opera
# make install clean
....

A linuxos Opera telepítéséhez `opera` helyett `linux-opera` nevet kell megadnunk a fenti parancsokban. Ennek a verziónak a használata akkor lehet elõnyös, ha olyan plugineket akarunk elérni, amelyek csak Linuxra léteznek. Ilyen például az Adobe Acrobat Reader(R). Ettõl eltekintve azonban a FreeBSD-s és a linuxos változatok szinte teljesen megegyeznek.

=== Konqueror

A Konqueror a KDE része, de a használatához elegendõ, ha csak a package:x11/kdebase3[] portot telepítjük fel. A Konqueror több, mint egy egyszerû böngészõ: állománykezelõ és multimédiás nézegetõ is.

Számtalan plugin áll rendelkezésre a Konquerorhoz, melyeket a package:misc/konq-plugins[] portban találunk meg.

A Konqueror ismeri a Flash(TM)t is. A Flash(TM) és a Konqueror kapcsolatával egy külön "Hogyan" is foglalkozik, amelyet a http://freebsd.kde.org/howtos/konqueror-flash.php[http://freebsd.kde.org/howtos/konqueror-flash.php] címen olvashatunk el.

[[desktop-productivity]]
== Irodai eszközök

Amikor irodai felhasználásról van szó, az új felhasználók gyakorta keresnek egy jó irodai programcsomagot vagy egy barátságos szövegszerkesztõt. Habár az egyes crossref:x11[x11-wm,munkakörnyezetek], mint például a KDE, gyakran saját irodai eszközöket is tartalmaznak, FreeBSD alatt nincs alapértelmezett irodai programcsomag. A rendszer a munkakörnyezetektõl függetlenül igyekszik felkínálni mindazt, amire szükségünk lehet.

Ebben a részben a következõ alkalmazásokról esik szó:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Alkalmazás
| Erõforrásigény
| Telepítés forrásból
| Fõbb függõségek

|KOffice
|kevés
|nehéz
|KDE

|AbiWord
|kevés
|könnyû
|Gtk+ vagy GNOME

|The Gimp
|kevés
|nehéz
|Gtk+

|OpenOffice.org
|sok
|nagyon nehéz
|JDK(TM), Mozilla
|===

=== KOffice

A KDE közösség által kiadott munkakörnyezethez társul egy irodai programcsomag is, amely a KDE-tõl függetlenül is használható. Tartalmazza a többi irodai programcsomagban is megtalálható négy szabványos komponenst: a KWord szövegszerkesztõt, a KSpread táblazatkezelõt, a KPresenter prezentációkészítõt és végezetül a Kontourt, mellyel grafikus dokumentumokat tudunk elkészíteni.

A legfrissebb KOffice telepítése elõtt bizonyosodjuk meg róla, hogy a KDE legfrissebb verziójával is rendelkezünk.

Ha a KOffice-t csomagként akarjuk telepíteni, akkor adjuk ki az alábbi parancsot:

[source,bash]
....
# pkg_add -r koffice
....

Amennyiben ez a csomag nem érhetõ el, telepíthetjük a Portgyûjteménybõl is. Például a KDE3-hoz tartozó KOffice-t így rakhatjuk fel:

[source,bash]
....
# cd /usr/ports/editors/koffice-kde3
# make install clean
....

=== AbiWord

Az AbiWord egy szabad szövegszerkesztõ program, a Microsoft(R) Word-höz hasonló kinézettel. Remekül használható levelek, beszámolók, feljegyzések, cikkek stb. írásához. Nagyon gyors, rengeteg funkciót ajánl fel, és kifejezetten felhasználóbarát.

Az AbiWord képes többféle állományformátumba exportálni és onnan importálni, beleértve az olyan zárt formátumokat is, mint például a Microsoft(R) [.filename]#.doc#.

Az AbiWord csomagból telepíthetõ a következõ módon:

[source,bash]
....
# pkg_add -r abiword
....

Amennyiben ez a csomag nem érhetõ el, lefordítható a Portgyûjteménybõl is, ami ráadásul sokszor egy frissebb verziót tartalmaz. Ezt így tudjuk megtenni:

[source,bash]
....
# cd /usr/ports/editors/abiword
# make install clean
....

=== The GIMP

Képek készítésére vagy retusálásra a The GIMP a legfejlettebb képszerkesztõ program. Egyszerû rajzolóprogram gyanánt is használható, de akár minõségi fényképretusálásra is. Óriási mennyiségû plugin található hozzá és magában foglal egy szkriptes interfészt is. A The GIMP formátumok széles skáláját ismeri. Számos scanner és digitális rajztábla csatlakoztatható hozzá.

A hozzá tartozó csomag a következõ módon telepíthetõ fel:

[source,bash]
....
# pkg_add -r gimp
....

Ha a csomagoknak beállított FTP oldalon nem található meg ez a csomag, megpróbálkozhatunk vele a Portgyûjteményen keresztül is. A gyûjtemény http://www.FreeBSD.org/ports/[graphics] könyvtárában ezen felül fellelhetjük a The Gimp Manualt, vagyis a The GIMP kézikönyvét. Így kell ezeket innen telepíteni:

[source,bash]
....
# cd /usr/ports/graphics/gimp
# make install clean
# cd /usr/ports/graphics/gimp-manual-pdf
# make install clean
....

[NOTE]
====
A Portgyûjtemény http://www.FreeBSD.org/ports/[graphics] könyvtárában a The GIMP fejlesztõi változatával is találkozhatunk a package:graphics/gimp-devel[] alkönyvtárban. A The Gimp Manual HTML változata pedig a package:graphics/gimp-manual-html[] alkönyvtárban található.
====

=== OpenOffice.org

Az OpenOffice.org tartalmaz minden olyan elengedhetetlenül fontos alkalmazást, amelyek napjaink bármelyik irodájához hozzátartoznak: egy szövegszerkesztõt, egy táblázatkezelõt, egy prezentációszerkesztõt és egy rajzolóprogramot. A felhasználói felülete nagyon hasonlít a többi irodai programcsomagéhoz, és képes többféle elterjedt állományformátumot kezelni. Számos különbözõ nyelven elérhetõ - a honosítása kiterjed a felületekre, helyesírás-ellenõrzõkre és szótárakra is.

Az OpenOffice.org szövegszerkesztõje natív XML állományformátumot használ a hordozhatóság és a rugalmasság növeléséhez. A táblázatkezelõje tartalmaz egy makrónyelvet és könnyedén összekapcsolható külsõ adatbázisokkal. Az OpenOffice.org natívan és megbízhatóan fut Windows(R)-on, Solaris(TM)-on, Linux(R)-on, FreeBSD-n és Mac OS(R) X-en. Az OpenOffice.org-ról bõvebb információt a http://www.openoffice.org/[projekt saját honlapján] találhatunk. A FreeBSD-s változatra vonatkozó információkat és a csomagokat pedig a http://porting.openoffice.org/freebsd/[FreeBSD OpenOffice.org Porting Team] honlapján lelhetjük meg.

Az OpenOffice.org telepítéséhez ennyit kell csak beírni:

[source,bash]
....
# pkg_add -r openoffice.org
....

[NOTE]
====
Ha a FreeBSD -RELEASE ágát használjuk, ennek mûködnie kell. Ettõl eltérõ esetben érdemes egy pillantást vetni a FreeBSD OpenOffice.org Porting Team honlapjára, ahonnan le tudjuk tölteni a verziókhoz megfelelõ csomagot, amelyet ezután a man:pkg_add[1]-al fel is tudunk telepíteni. A legfrissebb megbízható és a fejlesztõi változat egyaránt elérhetõ errõl a helyrõl.
====

Ahogy sikerült feltelepíteni a csomagot, egyszerûen csak be kell gépelni a következõ parancsot az OpenOffice.org futtatásához:

[source,bash]
....
% openoffice.org
....

[NOTE]
====
Az elsõ futtatás során válaszolnunk kell még néhány további kérdésre is, valamint a felhasználói könyvtárunkban keletkezik egy [.filename]#.openoffice.org# könyvtár.
====

Ha nem érhetõek el OpenOffice.org csomagok, lefordíthatjuk a forrását is. Azonban mielõtt még ennek nekilátnánk, el kell fogadnunk, hogy ez a mûvelet a lemezünkön rettenetesen sok területet fog igényelni és meglehetõsen sokáig tart.

[source,bash]
....
# cd /usr/ports/editors/openoffice.org-3
# make install clean
....

[NOTE]
====
Ha egy honosított verziót szeretnénk fordítani, az utolsó parancs helyett írjuk inkább ezt:

[source,bash]
....
# make LOCALIZED_LANG=nyelv install clean
....

A _nyelv_ helyett itt természetesen a nyelvnek megfelelõ ISO-kódot kell megadni. Az itt támogatott nyelvek kódjának listája a port könyvtárán belül, a [.filename]#files/Makefile.localized# állományban található meg.
====

Ahogy a fordítás befejezõdött, az OpenOffice.org így indítható el parancssorból:

[source,bash]
....
% openoffice.org
....

[[desktop-viewers]]
== Dokumentum-megjelenítõk

A UNIX(R) megjelenése óta néhány új népszerû dokumentumformátum is felbukkant, melyek szabványos megjelenítõi nem minden esetben részei az alaprendszernek. Ebben a részben azt tekintjük át, hogyan lehet ilyen megjelenítõket telepíteni.

Ez a rész az alábbi alkalmazásokat említi:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Alkalmazás
| Erõforrásigény
| Telepítés forrásból
| Fõbb függõségek

|Acrobat Reader(R)
|kevés
|könnyû
|Bináris Linux kompatibilitás

|gv
|kevés
|könnyû
|Xaw3d

|Xpdf
|kevés
|könnyû
|FreeType

|GQview
|kevés
|könnyû
|Gtk+ vagy GNOME
|===

=== Acrobat Reader(R)

A dokumentumok többsége manapság PDF (Portable Document Format, avagy "hordozható dokumentumformátum)" állományok formájában terjed. Az ilyen típusú állományok megnézésére az egyik legmegfelelõbb alkalmazás az Acrobat Reader(R), melyet az Adobe adott ki Linuxra. De mivel a FreeBSD képes Linux binárisok futtatására, ezért így FreeBSD-re is elérhetõ.

Ha az Acrobat Reader(R) 8-at a Portgyûjteménybõl akarjuk telepíteni, akkor írjuk be:

[source,bash]
....
# cd /usr/ports/print/acroread8
# make install clean
....

Licencelési megszorítások miatt csomag nem áll rendelkezésre.

=== gv

A gv egy PostScript(R) és PDF megjelenítõ. Eredetileg a ghostview alapján készült, de a Xaw3d-nek köszönhetõen sokkal szebben néz ki. Gyors és a felülete letisztult. A gv sok mindent tud, többek közt beállítható benne a dokumentum tájolása, a papírméret, skálázás és az élsimítás. Szinte bármelyik mûvelet elvégezhetõ csak billentyûzetrõl vagy egérrel.

A gv csomagjának telepítéséhez a következõ parancsot használhatjuk:

[source,bash]
....
# pkg_add -r gv
....

Ha pedig nem tudjuk letölteni a csomagot, használhatjuk a Portgyûjteményt is:

[source,bash]
....
# cd /usr/ports/print/gv
# make install clean
....

=== Xpdf

Ha egy egyszerû FreeBSD-s PDF megjelenítõre lenne szükségünk, erre a célra az Xpdf pontosan megfelel. Nagyon kevés erõforrást igényel és nagyon megbízható. A szabványos X-beli betûtípusokat használja, és nincs szüksége sem a Motif(R)ra, sem pedig más X-es eszközkészletre.

Az Xpdf csomagjának felrakásához az alábbi parancs javasolt:

[source,bash]
....
# pkg_add -r xpdf
....

Amennyiben nem áll rendelkezésre az említett csomag, vagy egyszerûen csak a Portgyûjteménybõl szeretnénk felrakni, adjuk ki ezeket a parancsokat:

[source,bash]
....
# cd /usr/ports/graphics/xpdf
# make install clean
....

Ahogy a telepítés befejezõdik, már el is indíthatjuk az Xpdf alkalmazást, ahol a jobb egérgombbal tudjuk aktiválni a menüt.

=== GQview

A GQview egy képkezelõ. Állományokat tudunk megnyitni benne egyetlen kattintással, külsõ szerkesztõprogramot tudunk indítani vagy akár még a képek kicsinyített változatait is láthatjuk és így tovább. Megtalálható benne a diavetítés és az alapvetõ állománymûveletek. Képgyûjteményeket is kezelhetünk és könnyedén megtalálhatjuk a bennük levõ képek között az egyezõeket. A GQview teljes képernyõs nézegetést is megenged, illetve támogatja a honosítást.

A GQview csomag telepítéséhez ezt a parancsot kell kiadni:

[source,bash]
....
# pkg_add -r gqview
....

Amikor ez a csomag nem tölthetõ le, vagy amikor inkább a Portgyûjteménybõl szeretnénk felrakni, ezt írjuk be:

[source,bash]
....
# cd /usr/ports/graphics/gqview
# make install clean
....

[[desktop-finance]]
== Pénzügyi szoftverek

Ha bármilyen ok folytán a FreeBSD-vel szeretnénk kezeli személyes pénzügyeinket, akadnak olyan kellõen komoly és könnyen kezelhetõ alkalmazások, amelyek csak a telepítésükre várnak. Néhány közülük kompatibilis az elterjedtebb állományformátumokkal, mint például amiben a Quicken és az Excel is tárolja az adatait.

Ebben a részben az alábbi programokat vesszük sorra:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Alkalmazás
| Erõforrásigény
| Telepítés forrásból
| Fõbb függõségek

|GnuCash
|kevés
|nehéz
|GNOME

|Gnumeric
|kevés
|nehéz
|GNOME

|Abacus
|kevés
|könnyû
|Tcl/Tk

|KMyMoney
|kevés
|nehéz
|KDE
|===

=== GnuCash

A GnuCash a GNOME része, és egy felhasználóbarát, mégis hatékony eszközt ad a felhasználók kezébe. A GnuCash segítségével nyilván tudjuk tartani a bevételeinket és kiadásainkat, bankszámláinkat és befektetéseinket. Felülete intuitív, miközben továbbra is professzionális minõségû.

A GnuCash-ben megtalálhatunk egy intelligens nyilvántartást, a számlák hierarchikus rendszerét, és számtalan billentyûkombinációt és automatikus kiegészítést, amivel felgyorsul a munkánk. Egyetlen tranzakciót képes felbontani több kisebb és részletesebb elemre. A GnuCash képes importálni és exportálni a Quicken QIF típusú állományait. Ezenkívül még kezeli a legtöbb nemzetközi dátumformátumot és pénznemet.

A GnuCash-t az alábbi módon tudjuk telepíteni a rendszerünkre:

[source,bash]
....
# pkg_add -r gnucash
....

Ha ez a csomag nem érhetõ el, használhatjuk a Portgyûjteményt is:

[source,bash]
....
# cd /usr/ports/finance/gnucash
# make install clean
....

=== Gnumeric

A Gnumeric egy táblázatkezelõ program, a GNOME munkakörnyezet része. Sok esetben képes a helyzethez alkalmazkodva automatikusan "kitalálni" a felhasználó gondolatait a cellák formátumának megfelelõ automatikus kiegészítõ rendszerével. Be tud olvasni számos népszerûbb formátumot, mint például az Excel, Lotus 1-2-3 vagy a Quattro Pro állományait. A package:math/guppi[] grafikonkészítõ programon keresztül támogatja grafikonok rajzolását is. Nagyszámú beépített funkcióval rendelkezik, és ismeri az összes megszokott cellaformátumot, legyen az szám, pénznem, dátum, idõ vagy bármi más.

A Gnumeric telepítését az alábbi paranccsal adhatjuk ki:

[source,bash]
....
# pkg_add -r gnumeric
....

Ha valamiért nem érhetõ el ez a csomag, a Portgyûjteménybõl is fel tudjuk rakni:

[source,bash]
....
# cd /usr/ports/math/gnumeric
# make install clean
....

=== Abacus

Az Abacus egy kicsi és egyszerûen használható táblázatkezelõ program. Számos olyan funkciót tartalmaz beépítve, amelyek kifejezetten hasznosnak bizonyulhatnak a statisztika, pénzügyek és a matematika területén. Importálni és exportálni tudja az Excel állományformátumát is. Az Abacus még PostScript(R) formátumú kimenetet is tud készíteni.

Az Abacus telepítéséhez csupán ennyit kell tennünk:

[source,bash]
....
# pkg_add -r abacus
....

Amennyiben viszont nem érhetõ el ez a csomag, használhatjuk a Portgyûjteményt is:

[source,bash]
....
# cd /usr/ports/deskutils/abacus
# make install clean
....

=== KMyMoney

A KMyMoney a KDE részeként kifejlesztett személyi pénzügyi nyilvántartó. A KMyMoney igyekszik az összes kereskedelmi pénzügyi nyilvántartó programban megtalálható fontosabb lehetõséget magában foglalni és rendelkezésre bocsátani. Mindezek mellett egy könnyen használható és nagyon ügyes kettõs könyvelést is találhatunk benne. A KMyMoney képes beolvasni a szabványos Quicken Interchange Format (QIF) szerint készült állományokat, követni a befektetéseket, többféle pénznemet kezelni és sokfajta kimutatást tudunk vele készíteni. A megfelelõ bõvítmény hozzáadásával még az OFX formátumú állományok olvasására is alkalmas.

A KMyMoney csomagként így telepíthetõ:

[source,bash]
....
# pkg_add -r kmymoney2
....

Ha ez a csomag nem érhetõ el, akkor a Portgyûjteményen keresztül is fel tudjuk rakni:

[source,bash]
....
# cd /usr/ports/finance/kmymoney2
# make install clean
....

[[desktop-summary]]
== Összefoglalás

Miközben a FreeBSD igen népszerû az internetszolgáltatók körében a teljesítménye és megbízhatósága révén, a hétköznapi használatban is remekül beválik. Többezernyi olyan alkalmazás érhetõ el hozzá http://www.FreeBSD.org/where/[csomag]ként vagy http://www.FreeBSD.org/ports/[port]ként, amelyekkel az igényeinknek megfelelõ munkakörnyezetet tudjuk kiépíteni.

Íme egy rövidke emlékeztetõ azokról az asztali alkalmazásokról, melyeket a fejezetben tárgyaltunk:

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Alkalmazás
| Csomag
| Port

|Opera
|`opera`
|package:www/opera[]

|Firefox
|`firefox`
|package:www/firefox[]

|KOffice
|`koffice-kde3`
|package:editors/koffice-kde3[]

|AbiWord
|`abiword`
|package:editors/abiword[]

|The GIMP
|`gimp`
|package:graphics/gimp[]

|OpenOffice.org
|`openoffice`
|package:editors/openoffice.org-3[]

|Acrobat Reader(R)
|`acroread`
|package:print/acroread8[]

|gv
|`gv`
|package:print/gv[]

|Xpdf
|`xpdf`
|package:graphics/xpdf[]

|GQview
|`gqview`
|package:graphics/gqview[]

|GnuCash
|`gnucash`
|package:finance/gnucash[]

|Gnumeric
|`gnumeric`
|package:math/gnumeric[]

|Abacus
|`abacus`
|package:deskutils/abacus[]

|KMyMoney
|`kmymoney2`
|package:finance/kmymoney2[]
|===
