# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.14

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =  commercial.xml

INDEXLINK=commercial.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
