---
title: "Проект Документирования FreeBSD"
sidenav: docs
---

= Проект Документирования FreeBSD

== Обзор

Изучение и понимание новой и сложной операционной системы всегда является трудной задачей, вне зависимости от того, насколько хорош пользовательский интерфейс. В этом аспекте FreeBSD ничем не отличается от других операционных систем.

Хотя имеется достаточное количество книг по BSD Unix (и об UNIX(R) вообще), FreeBSD имеет свои уникальные особенности, приемы работы и различные хитрости.

Кроме того, FreeBSD может быть первым опытом работы с Unix-подобными операционными системами для многих ее пользователей, поэтому наличие высококачественной, аккуратно составленной документации имеет очень высокое значение.

Проект The FreeBSD Documentation Project имеет цель заполнить этот пробел. Это осуществляется двумя способами:

. Участники Проекта пишут документации и предоставляют ее для включения во _FreeBSD Documentation Set_.
. Участники Проекта обсуждают и упорядочивают формат и организацию _FreeBSD Documentation Set_.

[.tblbasic]
[width="100%",cols="100%",]
|===
a|
[.center]
=== link:current[Текущие проекты]

В настоящий момент _на этапе реализации_ находятся несколько проектов, являющихся частью Проекта Документирования. Пожалуйста, выберите время, чтобы взглянуть на этот список и определиться, есть ли в нем что-либо, в чем *вы* можете помочь.

|===

== link:who[Кто мы и как к нам присоединиться]

Эта страница описывает, кто осуществляет Проект Документирования, и как вы можете к нему присоединиться.

== link:doc-set[The FreeBSD Documentation Set]

Эта страница описывает компоненты Комплекта Документации FreeBSD, и то, какую работу с ним проделывает Проект Документирования.

== link:sgml[SGML и Documentation Project]

Для документации проект пытается использовать SGML. Эта страница описывает, как это достигается, и отправляет заинтересовавшегося читателя к более подробным ресурсам SGML.

== link:submitting[Посылка документации]

Посылка документации является лучшим способом принять участие в проекте и помочь FreeBSD стать более легкой для использования. Эта страница описывает наиболее эффективный способ посылки документации, при котором она будет просмотрена наиболее быстро.

== link:translations[Перевод]

Переводы документации FreeBSD, страниц веб, Руководства, страниц Справочника и FAQ.
