---
title: "Проект Документирования FreeBSD: Текущие проекты"
sidenav: docs
---

= Проект Документирования FreeBSD: Текущие проекты

Здесь приведён список проектов, которые находятся в работе (или активно обсуждаются в списке рассылки freebsd-doc).

Если вы думаете, что сможете принять участие в любом из этих проектов, не стесняйтесь заявить об этом. Поговорите с человеком, отвечающим за конкретный проект, и он поможет вам стать его участником. Если у вас есть какие-либо идеи относительно новых проектов, пожалуйста, отправьте письмо по адресу FreeBSD-doc@FreeBSD.org.

* <<todo,TODO список для документации>>
* <<pr,Открытые сообщения об ошибках в документации>>
* <<handbook-index,Улучшение тематического указателя в Руководстве>>
* <<slides,Разработка демонстрационных слайдов и презентационных материалов>>
* <<freebsd4linux,FreeBSD для пользователей Linux>>
* <<handbooksection,Написание разделов в Руководстве и/или FAQ>>
* <<newpapers,Написание некоторых новых документов>>
* <<cgiscripts,Скрипты CGI>>
* <<multilingualwebscripts,Многонациональные скрипты для Web-сервера>>
* <<translations,Переводы документации FreeBSD>>
* <<search-enhancements,Усовершенствования средств поиска>>

[[todo]]
== TODO список для документации

link:&enbase;/docproj/todo.html[TODO] список для документации - это постоянно обновляющийся список проблем с документацией, которые должны быть решены. Этот список ежемесячно отсылается в список рассылки FreeBSD-doc@FreeBSD.org. Если вы хотите помочь нам улучшить документацию FreeBSD, то в первую вы должны выбрать пункт из этого списка.

[[pr]]
== Открытые сообщения об ошибках в документации

Текущие сообщения об ошибках в документации отслеживаются с помощью базы данных GNATS. Вы можете http://www.FreeBSD.org/cgi/query-pr-summary.cgi?category=docs&responsible=[просмотреть] открытые сообщения об ошибках в документации.

[[handbook-index]]
== Улучшение тематического указателя в Руководстве

*Ответственный:* FreeBSD-doc < FreeBSD-doc@FreeBSD.org>

*Описание:* В Руководстве FreeBSD было добавлено много новых разделов без тематических указателей, другие были добавлены с несоответствующими первичными или вторичными ключами индексации, которые не подходят в существующую схему. Некоторые тематические указатели добавлялись внутри списков или других областях текста, где их использование в соответствии с применяемыми нами таблицами стилей не разрешается. Это приводит к появлению символов `???` вместо реальных номеров страниц при выдаче индексного указатели на печать.

Работа с указателями требует опыта и всякому, работающему над этой проблемой, настоятельно рекомендуется тщательно прочесть имеющийся указатель (готовый к выдаче на печать) одновременно с книгой Chicago Manual of Style или другим документом, описывающим стилистику и, кроме всего прочего, тематические указатели. Пожалуйста, просмотрите журнал CVS некоторых файлов chapter.xml, чтобы проанализировать некоторые прошлые уже исправленные ошибки индексации. Работать после внесения любых изменений в указатели в обязательном порядке нужно с версией Руководства в формате PostScript, так как многие ошибки, такие как длинные слова или указатели с большим уровнем вложения будут отрицательно сказываться на используемую здесь выдачу в две колонки, либо будут приводить в выдаче номеров страниц в виде `???`.

Имеется скрипт `doc/share/misc/indexreport.pl`, который может использоваться для выявления областей SGML-файла, в котором метки <indexterm> встречаются редко.

[[slides]]
== Разработка демонстрационных слайдов и презентационных материалов

*Ответственный:* FreeBSD-doc <FreeBSD-doc@FreeBSD.org>, Мюррей Стокели <murray@FreeBSD.org>

*Описание:* К набору документации в каталоге `doc/en_US.ISO8859-1/slides` недавно были добавлены презентации, размеченные в формате DocBook-slides DTD. Нам нужны дополнительные презентационные материалы, необходима доработка таблиц стилей для формирования контента из замечаний к релизам и других XML-источников в нашем наборе документации для обновления и построения слайдов по команде 'make'. Пример простой презентации с некоторой такой функциональностью уже был создан, но работа должна продолжаться! Кроме того, таблицы стилей для выдачи на печать и в формате PDF (использующие XSLT-процессоры на основе Java, возможности PassiveTeX для слайдов слишком ограничены) могут быть улучшены, так как таблицы стилей DocBook Slides XSL-FO генерируют для слайдов весьма спартанское оформление.

[[[freebsd4linux]]
== FreeBSD для пользователей Linux

*Ответственный:* FreeBSD-doc <FreeBSD-doc@FreeBSD.org>

*Описание:* Пользователи, переходящие от Linux к FreeBSD, могут столкнуться с некоторыми различиями между системами (различные командные процессоры, используемые по умолчанию, конфигурирование системы при загрузке и т.д.).

[[handbooksection]]
== Написание разделов в Руководстве и/или FAQ

*Ответственный:* Никто

*Описание:* Части FAQ и Руководства имеют пустые разделы. Их требуется заполнить. Если вы использовали какие-либо из этих документов и нашли их неполными, пожалуйста, найдите время для описания вашего опыта в качестве возможной замены.

Кроме того, если вы сделали что-то, что не описано в FAQ или Руководстве, просто напишите новый раздел. Затем пошлите его так, как описано выше.

[[newpapers]]
== Написание некоторых новых документов

=== Новый уровень SCSI для FreeBSD (CAM)

*Ответственный:* <doc@FreeBSD.org>, <scsi@FreeBSD.org>

*Описание:* Посмотрите первый вариант http://www.FreeBSD.org/~gibbs/[Архитектура и реализация подсистемы SCSI во FreeBSD].

[[cgiscripts]]
== Скрипты CGI

*Ответственный:* <doc@FreeBSD.org>, Wolfram Schneider <wosch@FreeBSD.org>

*Описание:* Изменение CGI скриптов url.cgi, ports.cgi, pds.cgi и скрипта portindex с использованием Perl модулей http://people.FreeBSD.org/~tom/portpm/[FreeBSD::Ports] modules. Эти модули также нуждаются в тестировании.

[[multilingualwebscripts]]
== Многонациональные скрипты для Web-сервера

*Ответственный:* <doc@FreeBSD.org>

*Описание:*

Наши основные страницы Web-сервера написаны на (американском) английском. Проект link:../translations[FreeBSD Translations Projects] занимается переводом страниц Web-сервера, Руководства и FAQ на другие языки.

Мы должны перевести скрипты cgi, а также и скрипты для построения Web-страниц. Скрипты должны поддерживать несколько языков, а не только один. Большинство скриптов написано на языке perl.

* Объединение сценариев perl ftp://ftp.FreeBSD.org/pub/FreeBSD/FreeBSD-current/www/en/ports/portindex[www/en/ports/portindex] и ftp://ftp.FreeBSD.org/pub/FreeBSD/FreeBSD-current/www/ja/ports/portindex[www/ja/ports/portindex] в один скрипт. Добавление параметра для вывода результата на английском или японском языках.

[[translations]]
== Переводы документации FreeBSD

*Ответственный:* <doc@FreeBSD.org>

Перевод документации FreeBSD (Web-страницы, FAQ, Руководство, страницы справочника) на другие языки. Обратитесь к link:../translations[проектам перевода FreeBSD]

[[search-enhancements]]
== Улучшение средств поиска

*Ответственный:* Eric Anderson <anderson@centtech.com>

При поиске по Web-серверу выводимый текст включает имя файла, который были найден, например, `FAQ34.html`.

Будет более удобно, если в результат поиска будет включен и запрашиваемый текст, что позволит пользователю увидеть, насколько результат поиска соответствует запросу.
