---
title: "Проект Документирования FreeBSD: Посылка документации"
sidenav: docs
---

include::shared/ru/urls.adoc[]

= Проект Документирования FreeBSD: Посылка документации

== Я написал некоторое количество документации. Как вам её послать?

Во-первых, спасибо, что вы нашли время и сделали это.

Вы должны сделать вашу документацию доступной для предварительного просмотра. Если это возможно, поместите её на какой-либо веб-сервер.

После этого пошлите сообщение в список рассылки `FreeBSD-doc` с кратким описанием документации и ссылкой на её местоположение, а также просьбой поделиться отзывами.

Если по каким-то причинам вы не можете поместить документацию на какой-либо веб-сервер, то пошлите её непосредственно в список рассылки `FreeBSD-doc`. Если вы собираетесь поступить именно так, то присылайте документы в формате обычного текста.

Скорее всего, вы ещё понадобится сделать cc: этого запроса на комментарии в другие подходящие списки рассылки. Например, что-либо, относящееся к использованию Git для синхронизации дерева исходных текстов, будет интересно подписчикам списков рассылки `FreeBSD-stable`. Пожалуйста, делайте копии максимум в один список рассылки.

После того, как люди посмотрели на вашу документацию, и вы получили шанс включить в документ любые из их пожеланий, вы уже можете посылать эту документацию.

Правильный способ сделать это — открыть отчет о проблеме (Problem Report). Инструкции по этому можно найти по ссылке link:../../support/bugreports/[Отчёты об ошибках].

Вы делаете это для того, чтобы ваше послание могло быть отслежено. Когда вы оформляете PR (Problem Report - сообщение о проблеме), ему назначается уникальный номер. Один из коммиттеров может затем направить PR себе, и установить с вами связь по поводу включения новой документации в систему. Для получения дополнительной информации см. link:{problem-reports}[Написание отчётов о проблемах в FreeBSD].

Убедитесь, что для "Product" установлено значение "Documentation", а для "Component" установлено либо "Documentation", либо "Website" в зависимости от ситуации. Вы должны прикрепить ваши файлы из предыдущего шага к PR. Пожалуйста, также предоставьте ссылки на сообщения в списках рассылки, где обсуждались ваши изменения, если это уместно.

== Я сделал некоторые изменения и исправления в существующей документации, как вам их послать?

Мы снова благодарим вас за то, что вы потратили на это время.

Прежде всего вам нужно сгенерировать особый файл, называемый _diff_. В этом diff-файле содержатся только изменения, которые вы внесли. Это облегчает персоне, выполняющей внесение изменений в систему, просмотр ваших изменений, что означает ненужность траты массы времени на объяснения, что конкретно было изменено (хотя вы должны будете объяснить, почему эти изменения так необходимы).

Чтобы сделать 'diff', вы должны:

. Сделать копию файла, который собираетесь менять. Если вы изменяете `foo.xml`, выполните
+
....
% cp foo.xml foo.xml.old
....
. Затем внесите ваши изменения в foo.xml
+
....
% vi foo.xml
... клац клац клац ...

... тестируем изменения, ищем опечатки, и тому подобное ...
....
. Делаем diff. Команда, это делающая:
+
....
% diff -ru foo.xml.old foo.xml > foo.diff
....
+
Здесь выполняется просмотр отличий между двумя файлами и запись этих отличий в файл `foo.diff`.

После этого вы можете послать `foo.diff` обратно в адрес проекта. Пошлите PR так, как это было описано выше, включив файл `foo.diff` в PR.

== Дополнительная информация

* link:{fdp-primer}[Проект документации FreeBSD: введение для новых участников]
* link:..[Проект Документирования FreeBSD]

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (19.06.2021): 8e22e76d94dc5fef83abcb3c082ab4242ef90ba2
//
