---
title: "Проект создания документации FreeBSD: Переводы"
sidenav: docs
---

= Проект создания документации FreeBSD: Переводы

* <<brazilian_portuguese,Проект создания документации на бразильском португальском>>
* <<bulgarian,Болгарский Проект Документирования>>
* <<chinese-cn,Проект создания документации на упрощённом китайском>>
* <<chinese-tw,Проект создания документации на традиционном китайском>>
* <<dutch,Датский Проект создания документации>>
* <<estonian,Эстонский Проект Документирования>>
* <<french,Французский Проект Документирования>>
* <<german,Немецкий Проект Документирования>>
* <<italian,Итальянский Проект Документирования>>
* <<japanese,Японский Проект Документирования>>
* <<korean,Корейский Проект Документирования>>
* <<polish,Польский Проект Документирования>>
* <<romanian,Румынский Проект Документирования>>
* <<russian,Русский Проект Документирования>>
* <<spanish,Испанский Проект Документирования>>
* <<turkish,Турецкий Проект создания документации>>

[[brazilian_portuguese]]
== Бразильско-португальский Проект Документирования FreeBSD

*Web*: http://doc.fugspbr.org/ +
*E-Mail*: lioux@FreeBSD.org +

_Имеющиеся списки рассылки_::
Перейдите по следующей ссылке http://lists.fugspbr.org/listinfo.cgi/doc-fugspbr.org/ за инструкциями по подписке на список рассылки бразильско-португальской группы перевода. +
Или отправьте письмо на mailto:doc-request@fugspbr.org?subject=subscribe[doc-request@fugspbr.org] со словом "subscribe" в теме письма. +
Создавать новые сообщения могут участники списка рассылки doc@fugspbr.org
_Имеющиеся документы_::
link:https://www.FreeBSD.org/doc/pt_BR/books/faq/[FAQ]
+
link:https://www.FreeBSD.org/doc/pt_BR/articles/contributing/[Как помочь FreeBSD]
_Документы, находящиеся в работе_::
http://doc.fugspbr.org/fdp/[Пример проекта документирования FreeBSD для новых участников]
+
http://doc.fugspbr.org/handbook/[Руководство FreeBSD]

[[bulgarian]]
== Болгарский Проект Документирования FreeBSD

*Web-сайт*: http://fdp.bg-freebsd.org/ +
*Электронная почта*: freebsd-fdp@bg-freebsd.org +

_Имеющиеся списки рассылки_::
Перейдите по ссылке http://lists.bg-freebsd.org/, чтобы получить инструкции по подписке на список рассылки болгарской группы перевода. +
Либо отправьте письмо на адрес freebsd-fdp-subscribe@bg-freebsd.org. +
Создавать новые сообщения могут участники списка рассылки freebsd-fdp@bg-freebsd.org
_Имеющиеся документы_::
http://www.cybershade.us/freebsd/bg/fdp/split/[Учебник по Проекту документирования FreeBSD для новых участников]
_Документы, находящиеся в работе_::
Руководство FreeBSD
+
Web-сайт FreeBSD
+
Архитектура и реализация 4.4BSD (ознакомительная глава)
+
Часто задаваемые вопросы по FreeBSD

[[chinese-tw]]
== Проект Документирования на традиционном китайском

*Web*: - +
*E-Mail*: foxfair@FreeBSD.org +

_Имеющиеся списки рассылки_::
Пошлите письмо со строчкой "subscribe freebsd-chinese-doc" на адрес majordomo@freebsd.sinica.edu.tw. +
Посылка сообщений разрешена участникам по адресу freebsd-chinese-doc@freebsd.sinica.edu.tw
_Имеющиеся документы_::
link:https://www.FreeBSD.org/doc/zh-tw/books/faq/[FAQ]
_Документы, находящиеся в работе_::
http://www.tw.FreeBSD.org/handbook-big5.html[Руководство]

[[chinese-cn]]
== Проект создания документации на упрощённом китайском

*Web-сайт*: http://www.FreeBSD.org.cn[www.FreeBSD.org.cn] +
*Электронная почта*: delphij@FreeBSD.org +

_Имеющиеся списки рассылки_::
Инструкции по подключению к списку рассылки Проекта создания документации на упрощённом китайском доступны по ссылке http://lists.cn.FreeBSD.org/mailman/listinfo
_Последние результаты нашей работы_::
http://cnsnap.cn.FreeBSD.org/zh_CN/[Web-сайт]
+
http://cnsnap.cn.FreeBSD.org/doc/zh_CN/books/arch-handbook[Руководство по архитектуре]
+
http://cnsnap.cn.FreeBSD.org/doc/zh_CN/books/developers-handbook[Руководство для разработчиков]
+
http://cnsnap.cn.FreeBSD.org/doc/zh_CN/books/handbook[Руководство]
+
http://cnsnap.cn.FreeBSD.org/doc/zh_CN/books/porters-handbook[Руководство по созданию портов]
+
http://cnsnap.cn.FreeBSD.org/doc/zh_CN/books/faq[FAQ]

[[dutch]]
== Датский проект создания документации FreeBSD

*Электронная почта*: remko@FreeBSD.org +

_Имеющиеся списки рассылки_::
Для подключения к датскому списку рассылки FreeBSD-doc-nl, в котором ведутся обсуждения, отправьте сообщение по электронной почте на адрес majordomo@majordomo.elvandar.org с текстом "subscribe freebsd-doc-nl" в теле письма. +
+
Для подключения к списку рассылки CVS FreeBSD-doc-nl-cvs, отправьте сообщение по электронной почте на адрес majordomo@majordomo.elvandar.org с текстом "subscribe freebsd-doc-nl-cvs" в теле письма. +
_Опубликованные документы_::
http://www.freebsd.org/doc/nl/books/handbook[Руководство (готово 80%)]
_Работа ещё ведётся_::
http://www.freebsd-nl.org/doc/nl[Руководство]
+
http://www.freebsd-nl.org/www/nl[Web-страница]

[[estonian]]
== Эстонский Проект Документирования FreeBSD

*Web*: http://www.bsd.ee/tolge.php +

_Имеющиеся документы_::
http://www.bsd.ee/handbook/[Руководство FreeBSD]

[[french]]
== Французский Проект Документирования FreeBSD

*Web*: http://www.freebsd-fr.org/[http://www.freebsd-fr.org] +

_Имеющиеся списки рассылки_::
Пошлите письмо со строчкой "SUB freebsd-questions" на адрес listserver@freebsd-fr.org, чтобы подписаться на франкоязычный список рассылки, посвящённый вопросам пользователей. +
+
Пошлите письмо со строчкой "SUB annonces" на адрес listserver@freebsd-fr.org, чтобы подписаться на франкоязычный список рассылки с анонсами. +
_Имеющиеся документы_::
link:https://www.FreeBSD.org/doc/fr/books/faq[FAQ]
+
link:https://www.FreeBSD.org/doc/fr/articles/[Некоторые статьи и пособия]
+
http://www.freebsd-fr.org/local-fr/www/spec/bulletins_index.html[Really Quick Newsletters]
+
http://www.freebsd-fr.org/doc/fr/books/picobsd/[PicoBSD]
_Документы, находящиеся в работе_::
link:https://www.FreeBSD.org/doc/fr/books/handbook/book[Руководство], link:https://www.FreeBSD.org/fr/[Web]
_Дерево CVS_::
http://www.freebsd-fr.org/cgi-fr/cvsweb.cgi/[CVS web]
+
Пошлите письмо со строчкой "SUB cvs" на адрес listserver@freebsd-fr.org для того, чтобы подписаться на список рассылки French CVS update. +

[[german]]
== Немецкий Проект Документирования FreeBSD

*Web-сайт*: http://people.FreeBSD.org/~mheinen/de-bsd-translators/de-bsd-translators.html +
*Электронная почта*: de-bsd-translators@de.FreeBSD.org +

_Имеющиеся документы_::
link:https://www.FreeBSD.org/doc/de/books/faq/[FAQ], link:https://www.FreeBSD.org/doc/de/articles/[несколько статей]
_Документы, находящиеся в работе_::
link:https://www.FreeBSD.org/doc/de/books/handbook/[Руководство], link:https://www.FreeBSD.org/doc/de/books/fdp-primer/[Учебник FDP], link:https://www.FreeBSD.org/de/[Web-сайт]

[[italian]]
== Итальянский Проект Документирования FreeBSD

*Web-сайт*: http://www.gufi.org/~alex/ +
*Электронная почта*: ale@freebsd.org +

_Имеющиеся списки рассылки_::
Для получения инструкций по подключению к списку рассылки группы переводчиков на итальянский язык, обратитесь по ссылке http://liste.gufi.org/mailman/listinfo/traduzioni. +
Либо отправьте электронное письмо на адрес mailto:traduzioni-request@gufi.org?subject=subscribe[traduzioni-request@gufi.org], указав "subscribe" в теме сообщения. +
Публикация сообщений разрешена участникам по адресу traduzioni@gufi.org
_Имеющиеся документы_::
link:https://www.FreeBSD.org/doc/it/books/unix-introduction/[Введение в Unix]
+
link:https://www.FreeBSD.org/it/docs/#articles[Несколько статей]
_Документы, над которыми сейчас ведётся работа_::
link:https://www.FreeBSD.org/doc/it/books/handbook/[Руководство]
+
link:https://www.FreeBSD.org/it/[Web-сайт]
_CVS-хранилище_::
http://cvs.gufi.org/cgi/cvsweb.cgi/doc/[Web-интерфейс к CVS]
+
Для подключения к итальянскому списку рассылки с обновлениями в итальянском CVS-хранилище отправьте сообщение на адрес электронной почты mailto:cvs-all-request@gufi.org?subject=subscribe[cvs-all-request@gufi.org] со словом "subscribe" в теме письма. +

[[japanese]]
== Японский Проект Документирования FreeBSD

*Web*: http://www.jp.FreeBSD.org/doc-jp/ +
*E-Mail*: doc-jp@jp.FreeBSD.org +

_Имеющиеся документы_::
link:https://www.FreeBSD.org/doc/ru/books/handbook/[Руководство], link:https://www.FreeBSD.org/doc/ja/books/faq/[FAQ], link:https://www.FreeBSD.org/ja/[Web], http://www.jp.FreeBSD.org/NewsLetter/Issue2/[FreeBSD NewsLetter Issue #2]
_Документы, находящиеся в работе_::
FreeBSD Tutorials

[[korean]]
== Корейский Проект Документирования FreeBSD

*Web*: http://www.kr.FreeBSD.org/projects/doc-kr/ +
*E-Mail*: doc@kr.FreeBSD.org +

_Документы, находящиеся в работе_::
Руководство

[[polish]]

== Польский Проект Документирования FreeBSD

*Web*: http://tlumaczenie.freebsd.pl +
*E-Mail*: ni@merkury.pol.lublin.pl +

_Имеющиеся документы_::
Некоторые учебники
_Документы, находящиеся в работе_::
Учебники FreeBSD
+
Руководство
+
FDP-Primer

[[romanian]]
== Румынский Проект Документирования FreeBSD

*Web*: http://www.rofug.ro/projects/ro-l10n/ +
*E-Mail*: ady@rofug.ro +

_Имеющиеся списки рассылки_::
Для подписки на список рассылки ro-l10n обратитесь к Web-сайту проекта или отправьте письмо на listar@rofug.ro с телом "subscribe ro-l10n". +
Создавать новые сообщения могут только участники списка рассылки ro-l10n.
_Документы, находящиеся в работе_::
Руководство

[[russian]]
== Русский Проект Документирования FreeBSD

*Web*: http://www.FreeBSD.org.ua/[http://www.FreeBSD.org.ua] +
*E-Mail*: frdp@FreeBSD.org.ua +

_Имеющиеся документы_::
link:https://www.FreeBSD.org/doc/ru/books/faq/[FAQ]
+
link:https://www.FreeBSD.org/ru/[WWW]
+
http://www.FreeBSD.org.ua/docs.html[Другие документы]
+
http://surw.chel.su/~andy/ncvs/doc/ru/QA/QA.html[QA]
_Документы, находящиеся в работе_::
http://www.FreeBSD.org.ua/doc/ru/books/handbook/[Руководство]

[[spanish]]
== Испанский Проект Документирования FreeBSD

*Web-сайт*: http://www.es.FreeBSD.org/es/ +
*Электронная почта*: jesusr@FreeBSD.org +

_Имеющиеся списки рассылки_::
https://listas.es.freebsd.org/mailman/listinfo/doc[Документация на испанском языке]
_Имеющиеся документы_::
link:https://www.FreeBSD.org/doc/es/books/faq/[FAQ]
+
link:https://www.FreeBSD.org/doc/es/books/handbook/[Руководство]
+
link:https://www.FreeBSD.org/doc/es/articles/[Статьи]

[[turkish]]
== Турецкий проект создания документации для FreeBSD

*Web-сайт*: http://www.enderunix.org/ftdp/ +
*Электронная почта*: ofsen@enderunix.org +

_Имеющиеся списки рассылки_::
Для подключения к списку рассылки ftdp обратитесь к Web-странице проекта либо отошлите пустое сообщение электронной почты на адрес link:ftdp-subscribe@lists.enderunix.org[ftpd-subscribe@lists.enderunix.org].
_Имеющиеся документы_::
link:https://www.FreeBSD.org/tr/[WWW]
+
http://www.enderunix.org/ftdp/[Список остальных документов]
_Документы, над которыми в настоящее время ведётся работа_::
Учебник FDP

link:..[Главная страница Проекта Документирования FreeBSD]
