////
Quarter:	3rd quarter of 2021
Prepared by:	dbaio
Reviewed by:	gjb, carlavilla
Last edit:	$Date: 2021-10-03 05:34:14 -0300 (Sun, 03 Oct 2021) $
Version:	$Id: doceng-2021-3rd-quarter-status-report.adoc 185 2021-10-03 08:34:14Z carlavilla $
////

=== Documentation Engineering Team

Links: +
link:https://www.freebsd.org/docproj/[FreeBSD Documentation Project] URL: link:https://www.freebsd.org/docproj/[https://www.freebsd.org/docproj/] +
link:https://docs.freebsd.org/en/books/fdp-primer/[FreeBSD Documentation Project Primer for New Contributors] URL: https://docs.freebsd.org/en/books/fdp-primer/[link:https://docs.freebsd.org/en/books/fdp-primer/] +
link:https://www.freebsd.org/administration/#t-doceng[Documentation Engineering Team] URL: link:https://www.freebsd.org/administration/#t-doceng[https://www.freebsd.org/administration/#t-doceng]

Contact: FreeBSD Doceng Team <doceng@FreeBSD.org>

The doceng@ team is a body to handle some of the meta-project issues associated with the FreeBSD Documentation Project; for more information, see link:https://www.freebsd.org/internal/doceng/[FreeBSD Doceng Team Charter].

During the last quarter, Philip Paeps (philip@) and Li-Wen Hsu (lwhsu@), already src and ports committers, were granted documentation commit bits, both now have all commit bit types.
Ed Maste (emaste@) who is already a src committer was granted a documentation commit bit.
We also said goodbye to Murray Stokely (murray@), Gábor Kövesdán (gabor@), Warren Block (wblock@), and Sevan Janiyan (sevan@).
Gábor Kövesdán (gabor@) and Warren Block (wblock@) are now former members of the doceng@ team; we thank them for their years of service.

Implicit (blanket) approvals were documented in the link:https://docs.freebsd.org/en/articles/committers-guide/#doc-blanket-approval[Committers Guide].
That does not cover all cases, but doceng@ encourages any FreeBSD committer from ports and src to contribute to the doc tree.

All ports/packages misc/freebsd-doc-* were updated.
They have the entire documentation set from the FreeBSD Documentation Project, like Handbook, FAQ, articles, and more.
