=== FreeBSD Foundation

Links: +
link:https://www.FreeBSDfoundation.org[FreeBSD Foundation] URL: link:https://www.FreeBSDfoundation.org[https://www.FreeBSDfoundation.org] +
link:https://freebsdfoundation.org/blog/technology-roadmap/[Technology Roadmap] URL: link:https://freebsdfoundation.org/blog/technology-roadmap/[https://freebsdfoundation.org/blog/technology-roadmap/] +
link:https://www.FreeBSDfoundation.org/donate/[Donate] URL: link:https://www.FreeBSDfoundation.org/donate/[https://www.FreeBSDfoundation.org/donate/] +
link:https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program/[Foundation Partnership Program] URL: link:https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program[https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program] +
link:https://www.FreeBSDfoundation.org/journal/[FreeBSD Journal] URL: link:https://www.FreeBSDfoundation.org/journal/[https://www.FreeBSDfoundation.org/journal/] +
link:https://www.FreeBSDfoundation.org/news-and-events/[Foundation News and Events] URL: link:https://www.FreeBSDfoundation.org/news-and-events/[https://www.FreeBSDfoundation.org/news-and-events/] +

Contact: Deb Goodkin <deb@FreeBSDFoundation.org>

The FreeBSD Foundation is a 501(c)(3) non-profit organization dedicated to
supporting and promoting the FreeBSD Project and community worldwide. Donations
from individuals and corporations are used to fund and manage software
development projects, conferences, and developer summits. We also provide travel
grants to FreeBSD contributors, purchase and support hardware to improve and
maintain FreeBSD infrastructure, and provide resources to improve security,
quality assurance, and release engineering efforts. We publish marketing
material to promote, educate, and advocate for the FreeBSD Project, facilitate
collaboration between commercial vendors and FreeBSD developers, and finally,
represent the FreeBSD Project in executing contracts, license agreements, and
other legal arrangements that require a recognized legal entity.

Here are some highlights of what we did to help FreeBSD last quarter:

==== Fundraising Efforts

Fundraising last quarter wasn’t as spectacular as we were hoping. But, then
again, people tend to take vacations during the summer months, which makes it
that more difficult for our funding requests to go through the management chain
for approvals.

So far this year we’ve raised $180,000 towards our $2,000,000 spending
budget. Why do we need so much money? Well, last year we decided to make more
significant software contributions to FreeBSD.  In order to do that, we had to
grow our team. We developed
link:https://freebsdfoundation.org/blog/technology-roadmap/[a technology
roadmap] based on input we were receiving from commercial users as well as
market trends. Based on the roadmap, we identified positions we needed to fill.

This year we've hired three full-time software developers, one full-time ARM
kernel developer, and one project manager. We also are funding wifi work
full-time and some other projects to help with FreeBSD on the desktop. You can
read about this effort to attract new users and contributors to the Project in
individual entries elsewhere in this status report.

Our growth wasn’t just in our technology team, but in our advocacy team
too. Here we hired a marketing coordinator and technical writer to provide more
educational and informational content. You’ll see in the *Advocacy and
Education* section below all the work we did to promote FreeBSD, provide
community engagement, education opportunities, and informative content to
help pave the path to getting started with FreeBSD.

You’ll find out how we used your donations here and in individual entries
throughout this status report.

We’re passionate about supporting you, the FreeBSD community, but we can’t do it
without your financial support.

Please consider making a donation to help us continue and increase our support
for FreeBSD in 2021:
link:https://www.FreeBSDfoundation.org/donate/[https://www.FreeBSDfoundation.org/donate/].

We also have the Partnership Program, to provide more benefits for our larger
commercial donors. Find out more information at
link:https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program/[https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program/]
and share with your companies!

==== OS Improvements

During the third quarter, Foundation staff and grant recipients committed 420
src tree changes, 24 ports tree changes, and 11 doc tree changes. This
represents 38%, 48%, and 16% of src, port, and doc commits which identify a
sponsor.

You can read about Foundation-sponsored projects in individual quarterly report
entries:

- Base System OpenSSH Update
- Fixes for msdosfs_rename VOP
- Hole Punching
- Improved amd64 UEFI boot
- Intel Wireless driver support
- LLDB Debugger Improvements
- Microchip LAN743x mgb(4) Device Driver
- OpenZFS RAIDZ Expansion update
- Using OCF in WireGuard
- syzkaller on FreeBSD

Foundation-sponsored arm64 work:

- Support for booting FreeBSD on the Arm Armv8-A AEM simulator
- sha256 instruction support to libmd(4) on arm64
- Initial work to support RAS, PAC and BTI on arm64

==== Continuous Integration and Quality Assurance

The Foundation provides a full-time staff member and funds projects to improve
continuous integration, automated testing, and overall quality assurance efforts
for the FreeBSD project.

See the separate Continuous Integration entry for details.

==== Supporting FreeBSD Infrastructure

The Foundation provides hardware and support for the Project. Last quarter, we
continued supporting the test cluster at Sentex, purchased a few needed drives
and spam filtering software for project email. We also set up a new and more
efficient hardware request/purchase process for clusteradm to use.

==== Partnerships and Commercial User Support

We met virtually with corporate users and started travelling again in late Q3
for some in-person meetings. The goals of the meetings are to facilitate
collaboration between commercial users and FreeBSD developers. We also met with
companies to discuss their needs and share that information with the Project.

==== FreeBSD Advocacy and Education

Much of our effort is dedicated to Project advocacy. This may involve
highlighting interesting FreeBSD work, producing literature, attending events,
or giving presentations. The goal of the literature we produce is to teach
people FreeBSD basics and help make their path to adoption or contribution
easier. Other than attending and presenting at events, we encourage and help
community members run their own FreeBSD events, give presentations, or staff
FreeBSD tables.

The FreeBSD Foundation sponsors many conferences, events, and summits around the
globe. These events can be BSD-related, open source, or technology events geared
towards underrepresented groups. We support the FreeBSD-focused events to help
provide a venue for sharing knowledge, working together on projects, and
facilitating collaboration between developers and commercial users. This all
helps provide a healthy ecosystem. We support the non-FreeBSD events to promote
and raise awareness of FreeBSD, to increase the use of FreeBSD in different
applications, and to recruit more contributors to the Project. We finally made
it back to our first in-person meeting with the *Open Source Summit* in late
September. We are also continuing to attend virtual events. In addition to
attending and planning virtual events, we are continually working on new
training initiatives and updating our selection of
link:https://www.freebsdfoundation.org/freebsd/how-to-guides/[how-to guides] to
facilitate getting more folks to try out FreeBSD.

Check out some of the advocacy and education work we did last quarter:

* Participated as an Industry Partner for USENIX ATC and OSD, July 14-16, 2021
* Participated as an Industry Partner for USENIX Security, August 11-13, 2021
* Held a FreeBSD Friday: link:https://youtu.be/BRACcRqgnWQ[How to Track FreeBSD Using Git]
* Sponsored and gave a talk at OpenFest 2020 in Sofia, Bulgaria, August 14-15, 2021
* Began planning for the https://www.eventbrite.com/e/november-2021-freebsd-vendor-summit-tickets-169166733253[November 2021 FreeBSD Vendor Summit] to be held online, November 18-19
* Presented at APNIC on August 13-16, 2021
* Served as a Nonprofit In-Kind Sponsor of OSI’s POSI 2021, September 16, 2021
* Sponsored EuroBSDcon at the Silver Level. The event took place, September 17-19, 2021
* Presented at Open Source Summit, in Seattle, WA, September 27-30, 2021
* Committed to be a Bronze Sponsor for the OpenZFS Summit
* New blog and video posts:
** link:https://youtu.be/BRACcRqgnWQ[Status of Online Conference Software on FreeBSD]
** link:https://freebsdfoundation.org/blog/meet-the-summer-2021-foundation-interns/[Meet the Summer 2021 Foundation Interns]
** link:https://freebsdfoundation.org/blog/a-look-at-profiling-freebsd-sort/[A Look at Profiling: FreeBSD Sort]
** link:https://freebsdfoundation.org/blog/meet-the-2021-freebsd-google-summer-of-code-students/[Meet the 2021 FreeBSD Google Summer of Code Students]
** link:https://freebsdfoundation.org/blog/a-co-op-term-at-the-freebsd-foundation/[A Co-op Term at the FreeBSD Foundation]
** link:https://freebsdfoundation.org/blog/technology-roadmap/[Technology Roadmap]
* link:https://freebsdfoundation.org/news-and-events/latest-news/devstyler-interview-with-deb-goodkin/[Devstyler Interview with Deb Goodkin]
* New Video How-to Guides on link:https://freebsdfoundation.org/installing-hellosystem/[installing HelloSystem] and link:https://freebsdfoundation.org/installing-ghostbsd/[installing GhostBSD]
* New Quick Start Guide on link:https://freebsdfoundation.org/freebsd-project/resources/printing-on-freebsd-quick-guide/[Printing on FreeBSD]
* Committed to be a Media Sponsor for All Things Open

We help educate the world about FreeBSD by publishing the professionally
produced FreeBSD Journal. As we mentioned previously, the FreeBSD Journal is now
a free publication. Find out more and access the latest issues at
link:https://www.FreeBSDfoundation.org/journal/[https://www.FreeBSDfoundation.org/journal/].

You can find out more about events we attended and upcoming events at
link:https://www.FreeBSDfoundation.org/news-and-events/[https://www.FreeBSDfoundation.org/news-and-events/].

==== Legal/FreeBSD IP

The Foundation owns the FreeBSD trademarks, and it is our responsibility to
protect them. We also provide legal support for the core team to investigate
questions that arise.

Go to link:https://www.FreeBSDfoundation.org[https://www.FreeBSDfoundation.org]
to find more about how we support FreeBSD and how we can help you!
