=== helloSystem

Links: +
link:https://hellosystem.github.io/docs/[Documentation] URL: link:https://hellosystem.github.io/[https://hellosystem.github.io/]

Contact: Simon Peter <probono@puredarwin.org> +
Contact: `\#helloSystem` on `irc.libera.chat`, mirrored to link:https://matrix.to/#/%23helloSystem:matrix.org?via=matrix.org[`#helloSystem:matrix.org` on Matrix]

==== What is helloSystem?

helloSystem is FreeBSD preconfigured as a desktop operating system with a focus on simplicity, elegance, and usability.
Its design follows the “Less, but better” philosophy.

==== Q3 2021 Status

* Version 0.6.0 of helloSystem has been published including many contributed features and bugfixes
** Improved window management with KWin as the window manager
** Simplified Filer file manager
* Contributors have started to port the helloSystem desktop environment, helloDesktop, to the FreeBSD Ports and Packages Collection (see changelog at https://github.com/helloSystem/ISO/releases/tag/r0.6.0 for details)

Installable Live ISO images and a full changelog are available at https://github.com/helloSystem/ISO/releases/tag/r0.6.0

==== Contributing

link:https://github.com/helloSystem/hello/blob/master/CONTRIBUTING.md[Help is wanted in a number of areas], especially in the areas of the FreeBSD core OS and kernel, and Qt/C++.
