=== Valgrind - Official Support for FreeBSD has Landed

Links +
link:https://www.valgrind.org/[Valgrind Home Page] URL: link:https://www.valgrind.org/[https://www.valgrind.org/] +
link:https://www.valgrind.org/docs/manual/dist.news.html[Valgrind News] URL: link:https://www.valgrind.org/docs/manual/dist.news.html[https://www.valgrind.org/docs/manual/dist.news.html] +

Contact: Paul Floyd <pjfloyd@wanadoo.fr>

Valgrind is an instrumentation framework for building dynamic analysis
tools. There are Valgrind tools that can automatically detect many memory
management and threading bugs, and profile your programs in detail. You can also
use Valgrind to build new tools.

With the release of version 3.18.0 of Valgrind, official FreeBSD support has
landed upstream.  The two supported architectures are amd64 and i386 (x86).

The next step will be to update the FreeBSD port.  This will involve switching
from code that was maintained out-of-tree for over 15 years to using the
official upstream tarball.

As Valgrind is closely tied to operating system details, obtaining official
FreeBSD support was the result of significant effort from dozens of developers.
