#
# Build the Handbook with just the content from this chapter.
#
# Original revision: 1.1
# $FreeBSD$
#

CHAPTERS= 	install/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
