---
title: Chapter 5. Configuring the Makefile
prev: books/porters-handbook/slow-porting
next: books/porters-handbook/special
---

[[makefiles]]
= Configuring the Makefile
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: 目录
:part-signifier: 部分
:chapter-signifier: 第
:appendix-caption: 附录
:table-caption: 表
:figure-caption: 图
:example-caption: 例 
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:g-plus-plus: g++
:sectnumoffset: 5

include::shared/mirrors.adoc[]
include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/zh-tw/mailing-lists.adoc[]
include::shared/zh-tw/urls.adoc[]

toc::[]

Configuring the [.filename]#Makefile# is pretty simple, and again we suggest looking at existing examples before starting. Also, there is a <<porting-samplem,sample Makefile>> in this handbook, so take a look and please follow the ordering of variables and sections in that template to make the port easier for others to read.

Consider these problems in sequence during the design of the new [.filename]#Makefile#:

[[makefile-source]]
== The Original Source

Does it live in `DISTDIR` as a standard ``gzip``ped tarball named something like [.filename]#foozolix-1.2.tar.gz#? If so, go on to the next step. If not, the distribution file format might require overriding one or more of `DISTVERSION`, `DISTNAME`, `EXTRACT_CMD`, `EXTRACT_BEFORE_ARGS`, `EXTRACT_AFTER_ARGS`, `EXTRACT_SUFX`, or `DISTFILES`.

In the worst case, create a custom `do-extract` target to override the default. This is rarely, if ever, necessary.

[[makefile-naming]]
== Naming

The first part of the port's [.filename]#Makefile# names the port, describes its version number, and lists it in the correct category.

[[makefile-portname]]
=== `PORTNAME`

Set `PORTNAME` to the base name of the software. It is used as the base for the FreeBSD package, and for <<makefile-distname,`DISTNAME`>>.

[IMPORTANT]
====
The package name must be unique across the entire ports tree. Make sure that the `PORTNAME` is not already in use by an existing port, and that no other port already has the same `PKGBASE`. If the name has already been used, add either <<porting-pkgnameprefix-suffix,`PKGNAMEPREFIX` or `PKGNAMESUFFIX`>>.
====

[[makefile-versions]]
=== Versions, `DISTVERSION` _or_ `PORTVERSION`

Set `DISTVERSION` to the version number of the software.

`PORTVERSION` is the version used for the FreeBSD package. It will be automatically derived from `DISTVERSION` to be compatible with FreeBSD's package versioning scheme. If the version contains _letters_, it might be needed to set `PORTVERSION` and not `DISTVERSION`.

[IMPORTANT]
====
Only one of `PORTVERSION` and `DISTVERSION` can be set at a time.
====

From time to time, some software will use a version scheme that is not compatible with how `DISTVERSION` translates in `PORTVERSION`.

[TIP]
====

When updating a port, it is possible to use man:pkg-version[8]'s `-t` argument to check if the new version is greater or lesser than before. See <<makefile-versions-ex-pkg-version>>.
====

[[makefile-versions-ex-pkg-version]]
.Using man:pkg-version[8] to Compare Versions.
[example]
====
`pkg version -t` takes two versions as arguments, it will respond with `<`, `=` or `>` if the first version is less, equal, or more than the second version, respectively.

[source,bash]
....
% pkg version -t 1.2 1.3
< <.>
% pkg version -t 1.2 1.2
= <.>
% pkg version -t 1.2 1.2.0
= <.>
% pkg version -t 1.2 1.2.p1
> <.>
% pkg version -t 1.2.a1 1.2.b1
< <.>
% pkg version -t 1.2 1.2p1
< <.>
....

<.> `1.2` is before `1.3`.
<.> `1.2` and `1.2` are equal as they have the same version.
<.> `1.2` and `1.2.0` are equal as nothing equals zero.
<.> `1.2` is after `1.2.p1` as `.p1`, think "pre-release 1".
<.> `1.2.a1` is before `1.2.b1`, think "alpha" and "beta", and `a` is before `b`.
<.> `1.2` is before `1.2p1` as `2p1`, think "2, patch level 1" which is a version after any `2.X` but before `3`.

[NOTE]
****
In here, the `a`, `b`, and `p` are used as if meaning "alpha", "beta" or "pre-release" and "patch level", but they are only letters and are sorted alphabetically, so any letter can be used, and they will be sorted appropriately.
****

====

.Examples of `DISTVERSION` and the Derived `PORTVERSION`
[cols="10%,90%", frame="none", options="header"]
|===
| DISTVERSION
| PORTVERSION

|0.7.1d
|0.7.1.d

|10Alpha3
|10.a3

|3Beta7-pre2
|3.b7.p2

|8:f_17
|8f.17
|===

[[makefile-versions-ex1]]
.Using `DISTVERSION`
[example]
====
When the version only contains numbers separated by dots, dashes or underscores, use `DISTVERSION`.

[.programlisting]
....
PORTNAME=   nekoto
DISTVERSION=	1.2-4
....

It will generate a `PORTVERSION` of `1.2.4`.
====

[[makefile-versions-ex2]]
.Using `DISTVERSION` When the Version Starts with a Letter or a Prefix
[example]
====
When the version starts or ends with a letter, or a prefix or a suffix that is not part of the version, use `DISTVERSIONPREFIX`, `DISTVERSION`, and `DISTVERSIONSUFFIX`.

If the version is `v1.2-4`:

[.programlisting]
....
PORTNAME=   nekoto
DISTVERSIONPREFIX=  v
DISTVERSION=	1_2_4
....

Some of the time, projects using GitHub will use their name in their versions. For example, the version could be `nekoto-1.2-4`:

[.programlisting]
....
PORTNAME=   nekoto
DISTVERSIONPREFIX=  nekoto-
DISTVERSION=	1.2_4
....

Those projects also sometimes use some string at the end of the version, for example, `1.2-4_RELEASE`:

[.programlisting]
....
PORTNAME=   nekoto
DISTVERSION=	1.2-4
DISTVERSIONSUFFIX=  _RELEASE
....

Or they do both, for example, `nekoto-1.2-4_RELEASE`:

[.programlisting]
....
PORTNAME=   nekoto
DISTVERSIONPREFIX=  nekoto-
DISTVERSION=	1.2-4
DISTVERSIONSUFFIX=  _RELEASE
....

`DISTVERSIONPREFIX` and `DISTVERSIONSUFFIX` will not be used while constructing `PORTVERSION`, but only used in `DISTNAME`.

All will generate a `PORTVERSION` of `1.2.4`.
====

[[makefile-versions-ex3]]
.Using `DISTVERSION` When the Version Contains Letters Meaning "alpha", "beta", or "pre-release"
[example]
====
When the version contains numbers separated by dots, dashes or underscores, and letters are used to mean "alpha", "beta" or "pre-release", which is, before the version without the letters, use `DISTVERSION`.

[.programlisting]
....
PORTNAME=   nekoto
DISTVERSION=	1.2-pre4
....

[.programlisting]
....
PORTNAME=   nekoto
DISTVERSION=	1.2p4
....

Both will generate a `PORTVERSION` of `1.2.p4` which is before than 1.2. man:pkg-version[8] can be used to check that fact:

[source,bash]
....
% pkg version -t 1.2.p4 1.2
<
....

====

[[makefile-versions-ex4]]
.Not Using `DISTVERSION` When the Version Contains Letters Meaning "Patch Level"
[example]
====
When the version contains letters that are not meant as "alpha", "beta", or "pre", but more in a "patch level", and meaning after the version without the letters, use `PORTVERSION`.

[.programlisting]
....
PORTNAME=   nekoto
PORTVERSION=	1.2p4
....

In this case, using `DISTVERSION` is not possible because it would generate a version of `1.2.p4` which would be before `1.2` and not after. man:pkg-version[8] will verify this:

[source,bash]
....
% pkg version -t 1.2 1.2.p4
> <.>
% pkg version -t 1.2 1.2p4
< <.>
....

<.> `1.2` is after `1.2.p4`, which is _wrong_ in this case.
<.> `1.2` is before `1.2p4`, which is what was needed.
====

For some more advanced examples of setting `PORTVERSION`, when the software's versioning is really not compatible with FreeBSD's, or `DISTNAME` when the distribution file does not contain the version itself, see <<makefile-distname>>.

[[makefile-naming-revepoch]]
=== `PORTREVISION` and `PORTEPOCH`

[[makefile-portrevision]]
==== `PORTREVISION`

`PORTREVISION` is a monotonically increasing value which is reset to 0 with every increase of `DISTVERSION`, typically every time there is a new official vendor release. If `PORTREVISION` is non-zero, the value is appended to the package name. Changes to `PORTREVISION` are used by automated tools like man:pkg-version[8] to determine that a new package is available.

`PORTREVISION` must be increased each time a change is made to the port that changes the generated package in any way. That includes changes that only affect a package built with non-default <<makefile-options,options>>.

Examples of when `PORTREVISION` must be bumped:

* Addition of patches to correct security vulnerabilities, bugs, or to add new functionality to the port.
* Changes to the port [.filename]#Makefile# to enable or disable compile-time options in the package.
* Changes in the packing list or the install-time behavior of the package. For example, a change to a script which generates initial data for the package, like man:ssh[1] host keys.
* Version bump of a port's shared library dependency (in this case, someone trying to install the old package after installing a newer version of the dependency will fail since it will look for the old libfoo.x instead of libfoo.(x+1)).
* Silent changes to the port distfile which have significant functional differences. For example, changes to the distfile requiring a correction to [.filename]#distinfo# with no corresponding change to `DISTVERSION`, where a `diff -ru` of the old and new versions shows non-trivial changes to the code.

Examples of changes which do not require a `PORTREVISION` bump:

* Style changes to the port skeleton with no functional change to what appears in the resulting package.
* Changes to `MASTER_SITES` or other functional changes to the port which do not affect the resulting package.
* Trivial patches to the distfile such as correction of typos, which are not important enough that users of the package have to go to the trouble of upgrading.
* Build fixes which cause a package to become compilable where it was previously failing. As long as the changes do not introduce any functional change on any other platforms on which the port did previously build. Since `PORTREVISION` reflects the content of the package, if the package was not previously buildable then there is no need to increase `PORTREVISION` to mark a change.

A rule of thumb is to decide whether a change committed to a port is something which _some_ people would benefit from having. Either because of an enhancement, fix, or by virtue that the new package will actually work at all. Then weigh that against that fact that it will cause everyone who regularly updates their ports tree to be compelled to update. If yes, `PORTREVISION` must be bumped.

[NOTE]
====
People using binary packages will _never_ see the update if `PORTREVISION` is not bumped. Without increasing `PORTREVISION`, the package builders have no way to detect the change and thus, will not rebuild the package.
====

[[makefile-portepoch]]
==== `PORTEPOCH`

From time to time a software vendor or FreeBSD porter will do something silly and release a version of their software which is actually numerically less than the previous version. An example of this is a port which goes from foo-20000801 to foo-1.0 (the former will be incorrectly treated as a newer version since 20000801 is a numerically greater value than 1).

[TIP]
====

The results of version number comparisons are not always obvious. `pkg version` (see man:pkg-version[8]) can be used to test the comparison of two version number strings. For example:

[source,bash]
....
% pkg version -t 0.031 0.29
>
....

The `>` output indicates that version 0.031 is considered greater than version 0.29, which may not have been obvious to the porter.
====

In situations such as this, `PORTEPOCH` must be increased. If `PORTEPOCH` is nonzero it is appended to the package name as described in section 0 above. `PORTEPOCH` must never be decreased or reset to zero, because that would cause comparison to a package from an earlier epoch to fail. For example, the package would not be detected as out of date. The new version number, `1.0,1` in the above example, is still numerically less than the previous version, 20000801, but the `,1` suffix is treated specially by automated tools and found to be greater than the implied suffix `,0` on the earlier package.

Dropping or resetting `PORTEPOCH` incorrectly leads to no end of grief. If the discussion above was not clear enough, please consult the {freebsd-ports}.

It is expected that `PORTEPOCH` will not be used for the majority of ports, and that sensible use of `DISTVERSION`, or that use `PORTVERSION` carefully, can often preempt it becoming necessary if a future release of the software changes the version structure. However, care is needed by FreeBSD porters when a vendor release is made without an official version number - such as a code "snapshot" release. The temptation is to label the release with the release date, which will cause problems as in the example above when a new "official" release is made.

For example, if a snapshot release is made on the date `20000917`, and the previous version of the software was version `1.2`, do not use `20000917` for `DISTVERSION`. The correct way is a `DISTVERSION` of `1.2.20000917`, or similar, so that the succeeding release, say `1.3`, is still a numerically greater value.

[[makefile-portrevision-example]]
==== Example of `PORTREVISION` and `PORTEPOCH` Usage

The `gtkmumble` port, version `0.10`, is committed to the ports collection:

[.programlisting]
....
PORTNAME=	gtkmumble
DISTVERSION=	0.10
....

`PKGNAME` becomes `gtkmumble-0.10`.

A security hole is discovered which requires a local FreeBSD patch. `PORTREVISION` is bumped accordingly.

[.programlisting]
....
PORTNAME=	gtkmumble
DISTVERSION=	0.10
PORTREVISION=	1
....

`PKGNAME` becomes `gtkmumble-0.10_1`

A new version is released by the vendor, numbered `0.2` (it turns out the author actually intended `0.10` to actually mean `0.1.0`, not "what comes after 0.9" - oops, too late now). Since the new minor version `2` is numerically less than the previous version `10`, `PORTEPOCH` must be bumped to manually force the new package to be detected as "newer". Since it is a new vendor release of the code, `PORTREVISION` is reset to 0 (or removed from the [.filename]#Makefile#).

[.programlisting]
....
PORTNAME=	gtkmumble
DISTVERSION=	0.2
PORTEPOCH=	1
....

`PKGNAME` becomes `gtkmumble-0.2,1`

The next release is 0.3. Since `PORTEPOCH` never decreases, the version variables are now:

[.programlisting]
....
PORTNAME=	gtkmumble
DISTVERSION=	0.3
PORTEPOCH=	1
....

`PKGNAME` becomes `gtkmumble-0.3,1`

[NOTE]
====
If `PORTEPOCH` were reset to `0` with this upgrade, someone who had installed the `gtkmumble-0.10_1` package would not detect the `gtkmumble-0.3` package as newer, since `3` is still numerically less than `10`. Remember, this is the whole point of `PORTEPOCH` in the first place.
====

[[porting-pkgnameprefix-suffix]]
=== `PKGNAMEPREFIX` and `PKGNAMESUFFIX`

Two optional variables, `PKGNAMEPREFIX` and `PKGNAMESUFFIX`, are combined with `PORTNAME` and `PORTVERSION` to form `PKGNAME` as `${PKGNAMEPREFIX}${PORTNAME}${PKGNAMESUFFIX}-${PORTVERSION}`. Make sure this conforms to our <<porting-pkgname,guidelines for a good package name>>. In particular, the use of a hyphen (`-`) in `PORTVERSION` is _not_ allowed. Also, if the package name has the _language-_ or the _-compiled.specifics_ part (see below), use `PKGNAMEPREFIX` and `PKGNAMESUFFIX`, respectively. Do not make them part of `PORTNAME`.

[[porting-pkgname]]
=== Package Naming Conventions

These are the conventions to follow when naming packages. This is to make the package directory easy to scan, as there are already thousands of packages and users are going to turn away if they hurt their eyes!

Package names take the form of [.filename]#language_region-name-compiled.specifics-version.numbers#.

The package name is defined as `${PKGNAMEPREFIX}${PORTNAME}${PKGNAMESUFFIX}-${PORTVERSION}`. Make sure to set the variables to conform to that format.

[[porting-pkgname-language]]
[.filename]#language_region-#::
FreeBSD strives to support the native language of its users. The _language-_ part is a two letter abbreviation of the natural language defined by ISO-639 when the port is specific to a certain language. Examples are `ja` for Japanese, `ru` for Russian, `vi` for Vietnamese, `zh` for Chinese, `ko` for Korean and `de` for German.
+
If the port is specific to a certain region within the language area, add the two letter country code as well. Examples are `en_US` for US English and `fr_CH` for Swiss French.
+
The _language-_ part is set in `PKGNAMEPREFIX`.

[[porting-pkgname-name]]
[.filename]#name#::
Make sure that the port's name and version are clearly separated and placed into `PORTNAME` and `DISTVERSION`. The only reason for `PORTNAME` to contain a version part is if the upstream distribution is really named that way, as in the package:textproc/libxml2[] or package:japanese/kinput2-freewnn[] ports. Otherwise, `PORTNAME` cannot contain any version-specific information. It is quite normal for several ports to have the same `PORTNAME`, as the package:www/apache*[] ports do; in that case, different versions (and different index entries) are distinguished by `PKGNAMEPREFIX` and `PKGNAMESUFFIX` values.
+
There is a tradition of naming `Perl 5` modules by prepending `p5-` and converting the double-colon separator to a hyphen. For example, the `Data::Dumper` module becomes `p5-Data-Dumper`.
[[porting-pkgname-compiled-specifics]]
[.filename]#-compiled.specifics#::
If the port can be built with different <<makefile-masterdir,hardcoded defaults>> (usually part of the directory name in a family of ports), the _-compiled.specifics_ part states the compiled-in defaults. The hyphen is optional. Examples are paper size and font units.
+
The _-compiled.specifics_ part is set in `PKGNAMESUFFIX`.

[[porting-pkgname-version-numbers]]
[.filename]#-version.numbers#::
The version string follows a dash (`-`) and is a period-separated list of integers and single lowercase alphabetics. In particular, it is not permissible to have another dash inside the version string. The only exception is the string `pl` (meaning "patchlevel"), which can be used _only_ when there are no major and minor version numbers in the software. If the software version has strings like "alpha", "beta", "rc", or "pre", take the first letter and put it immediately after a period. If the version string continues after those names, the numbers follow the single alphabet without an extra period between them (for example, `1.0b2`).
+
The idea is to make it easier to sort ports by looking at the version string. In particular, make sure version number components are always delimited by a period, and if the date is part of the string, use the `d__yyyy.mm.dd__` format, not `_dd.mm.yyyy_` or the non-Y2K compliant `_yy.mm.dd_` format. It is important to prefix the version with a letter, here `d` (for date), in case a release with an actual version number is made, which would be numerically less than `_yyyy_`.

[IMPORTANT]
====
Package name must be unique among all of the ports tree, check that there is not already a port with the same `PORTNAME` and if there is add one of <<porting-pkgnameprefix-suffix,`PKGNAMEPREFIX` or `PKGNAMESUFFIX`>>.
====

Here are some (real) examples on how to convert the name as called by the software authors to a suitable package name, for each line, only one of `DISTVERSION` or `PORTVERSION` is set in, depending on which would be used in the port's [.filename]#Makefile#:

.Package Naming Examples
[cols="1,1,1,1,1,1,1", frame="none", options="header"]
|===
| Distribution Name
| PKGNAMEPREFIX
| PORTNAME
| PKGNAMESUFFIX
| DISTVERSION
| PORTVERSION
| Reason or comment

|mule-2.2.2
|(empty)
|mule
|(empty)
|2.2.2
|
|No changes required

|mule-1.0.1
|(empty)
|mule
|1
|1.0.1
|
|This is version 1 of mule, and version 2 already exists

|EmiClock-1.0.2
|(empty)
|emiclock
|(empty)
|1.0.2
|
|No uppercase names for single programs

|rdist-1.3alpha
|(empty)
|rdist
|(empty)
|1.3alpha
|
|Version will be `1.3.a`

|es-0.9-beta1
|(empty)
|es
|(empty)
|0.9-beta1
|
|Version will be `0.9.b1`

|mailman-2.0rc3
|(empty)
|mailman
|(empty)
|2.0rc3
|
|Version will be `2.0.r3`

|v3.3beta021.src
|(empty)
|tiff
|(empty)
|
|3.3
|What the heck was that anyway?

|tvtwm
|(empty)
|tvtwm
|(empty)
|
|p11
|No version in the filename, use what upstream says it is

|piewm
|(empty)
|piewm
|(empty)
|1.0
|
|No version in the filename, use what upstream says it is

|xvgr-2.10pl1
|(empty)
|xvgr
|(empty)
|
|2.10.pl1
|In that case, `pl1` means patch level, so using DISTVERSION is not possible.

|gawk-2.15.6
|ja-
|gawk
|(empty)
|2.15.6
|
|Japanese language version

|psutils-1.13
|(empty)
|psutils
|-letter
|1.13
|
|Paper size hardcoded at package build time

|pkfonts
|(empty)
|pkfonts
|300
|1.0
|
|Package for 300dpi fonts
|===

If there is absolutely no trace of version information in the original source and it is unlikely that the original author will ever release another version, just set the version string to `1.0` (like the `piewm` example above). Otherwise, ask the original author or use the date string the source file was released on (`d__yyyy.mm.dd__`, or `d__yyyymmdd__`) as the version.

[TIP]
====

Use any letter. Here, `d` here stands for date, if the source is a Git repository, `g` followed by the commit date is commonly used, using `s` for snapshot is also common.
====

[[makefile-categories]]
== Categorization

[[makefile-categories-definition]]
=== `CATEGORIES`

When a package is created, it is put under [.filename]#/usr/ports/packages/All# and links are made from one or more subdirectories of [.filename]#/usr/ports/packages#. The names of these subdirectories are specified by the variable `CATEGORIES`. It is intended to make life easier for the user when he is wading through the pile of packages on the FTP site or the CDROM. Please take a look at the <<porting-categories,current list of categories>> and pick the ones that are suitable for the port.

This list also determines where in the ports tree the port is imported. If there is more than one category here, the port files must be put in the subdirectory with the name of the first category. See <<choosing-categories,below>> for more discussion about how to pick the right categories.

[[porting-categories]]
=== Current List of Categories

Here is the current list of port categories. Those marked with an asterisk (`*`) are _virtual_ categories-those that do not have a corresponding subdirectory in the ports tree. They are only used as secondary categories, and only for search purposes.

[NOTE]
====
For non-virtual categories, there is a one-line description in `COMMENT` in that subdirectory's [.filename]#Makefile#.
====

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Category
| Description
| Notes

|[.filename]#accessibility#
|Ports to help disabled users.
|

|[.filename]#afterstep#`*`
|Ports to support the http://www.afterstep.org[AfterStep] window manager.
|

|[.filename]#arabic#
|Arabic language support.
|

|[.filename]#archivers#
|Archiving tools.
|

|[.filename]#astro#
|Astronomical ports.
|

|[.filename]#audio#
|Sound support.
|

|[.filename]#benchmarks#
|Benchmarking utilities.
|

|[.filename]#biology#
|Biology-related software.
|

|[.filename]#cad#
|Computer aided design tools.
|

|[.filename]#chinese#
|Chinese language support.
|

|[.filename]#comms#
|Communication software.
|Mostly software to talk to the serial port.

|[.filename]#converters#
|Character code converters.
|

|[.filename]#databases#
|Databases.
|

|[.filename]#deskutils#
|Things that used to be on the desktop before computers were invented.
|

|[.filename]#devel#
|Development utilities.
|Do not put libraries here just because they are libraries. They should _not_ be in this category unless they truly do not belong anywhere else.

|[.filename]#dns#
|DNS-related software.
|

|[.filename]#docs#`*`
|Meta-ports for FreeBSD documentation.
|

|[.filename]#editors#
|General editors.
|Specialized editors go in the section for those tools. For example, a mathematical-formula editor will go in [.filename]#math#, and have [.filename]#editors# as a second category.

|[.filename]#elisp#`*`
|Emacs-lisp ports.
|

|[.filename]#emulators#
|Emulators for other operating systems.
|Terminal emulators do _not_ belong here. X-based ones go to [.filename]#x11# and text-based ones to either [.filename]#comms# or [.filename]#misc#, depending on the exact functionality.

|[.filename]#enlightenment#`*`
|Ports related to the Enlightenment window manager.
|

|[.filename]#finance#
|Monetary, financial and related applications.
|

|[.filename]#french#
|French language support.
|

|[.filename]#ftp#
|FTP client and server utilities.
|If the port speaks both FTP and HTTP, put it in [.filename]#ftp# with a secondary category of [.filename]#www#.

|[.filename]#games#
|Games.
|

|[.filename]#geography#`*`
|Geography-related software.
|

|[.filename]#german#
|German language support.
|

|[.filename]#gnome#`*`
|Ports from the http://www.gnome.org[GNOME] Project.
|

|[.filename]#gnustep#`*`
|Software related to the GNUstep desktop environment.
|

|[.filename]#graphics#
|Graphics utilities.
|

|[.filename]#hamradio#`*`
|Software for amateur radio.
|

|[.filename]#haskell#`*`
|Software related to the Haskell language.
|

|[.filename]#hebrew#
|Hebrew language support.
|

|[.filename]#hungarian#
|Hungarian language support.
|

|[.filename]#irc#
|Internet Relay Chat utilities.
|

|[.filename]#japanese#
|Japanese language support.
|

|[.filename]#java#
|Software related to the Java(TM) language.
|The [.filename]#java# category must not be the only one for a port. Save for ports directly related to the Java language, porters are also encouraged not to use [.filename]#java# as the main category of a port.

|[.filename]#kde#`*`
|Ports from the http://www.kde.org[KDE] Project (generic).
|

|[.filename]#kde-applications#`*`
|Applications from the http://www.kde.org[KDE] Project.
|

|[.filename]#kde-frameworks#`*`
|Add-on libraries from the http://www.kde.org[KDE] Project for programming with Qt.
|

|[.filename]#kde-plasma#`*`
|Desktop from the http://www.kde.org[KDE] Project.
|

|[.filename]#kld#`*`
|Kernel loadable modules.
|

|[.filename]#korean#
|Korean language support.
|

|[.filename]#lang#
|Programming languages.
|

|[.filename]#linux#`*`
|Linux applications and support utilities.
|

|[.filename]#lisp#`*`
|Software related to the Lisp language.
|

|[.filename]#mail#
|Mail software.
|

|[.filename]#mate#`*`
|Ports related to the MATE desktop environment, a fork of GNOME 2.
|

|[.filename]#math#
|Numerical computation software and other utilities for mathematics.
|

|[.filename]#mbone#`*`
|MBone applications.
|

|[.filename]#misc#
|Miscellaneous utilities
|Things that do not belong anywhere else. If at all possible, try to find a better category for the port than `misc`, as ports tend to be overlooked in here.

|[.filename]#multimedia#
|Multimedia software.
|

|[.filename]#net#
|Miscellaneous networking software.
|

|[.filename]#net-im#
|Instant messaging software.
|

|[.filename]#net-mgmt#
|Networking management software.
|

|[.filename]#net-p2p#
|Peer to peer network applications.
|

|[.filename]#net-vpn#`*`
|Virtual Private Network applications.
|

|[.filename]#news#
|USENET news software.
|

|[.filename]#parallel#`*`
|Applications dealing with parallelism in computing.
|

|[.filename]#pear#`*`
|Ports related to the Pear PHP framework.
|

|[.filename]#perl5#`*`
|Ports that require Perl version 5 to run.
|

|[.filename]#plan9#`*`
|Various programs from http://www.cs.bell-labs.com/plan9dist/[Plan9].
|

|[.filename]#polish#
|Polish language support.
|

|[.filename]#ports-mgmt#
|Ports for managing, installing and developing FreeBSD ports and packages.

|[.filename]#portuguese#
|Portuguese language support.
|

|[.filename]#print#
|Printing software.
|Desktop publishing tools (previewers, etc.) belong here too.

|[.filename]#python#`*`
|Software related to the http://www.python.org/[Python] language.
|

|[.filename]#ruby#`*`
|Software related to the http://www.ruby-lang.org/[Ruby] language.
|

|[.filename]#rubygems#`*`
|Ports of http://www.rubygems.org/[RubyGems] packages.
|

|[.filename]#russian#
|Russian language support.
|

|[.filename]#scheme#`*`
|Software related to the Scheme language.
|

|[.filename]#science#
|Scientific ports that do not fit into other categories such as [.filename]#astro#, [.filename]#biology# and [.filename]#math#.
|

|[.filename]#security#
|Security utilities.
|

|[.filename]#shells#
|Command line shells.
|

|[.filename]#spanish#`*`
|Spanish language support.
|

|[.filename]#sysutils#
|System utilities.
|

|[.filename]#tcl#`*`
|Ports that use Tcl to run.
|

|[.filename]#textproc#
|Text processing utilities.
|It does not include desktop publishing tools, which go to [.filename]#print#.

|[.filename]#tk#`*`
|Ports that use Tk to run.
|

|[.filename]#ukrainian#
|Ukrainian language support.
|

|[.filename]#vietnamese#
|Vietnamese language support.
|

|[.filename]#wayland#`*`
|Ports to support the Wayland display server.
|

|[.filename]#windowmaker#`*`
|Ports to support the WindowMaker window manager.
|

|[.filename]#www#
|Software related to the World Wide Web.
|HTML language support belongs here too.

|[.filename]#x11#
|The X Window System and friends.
|This category is only for software that directly supports the window system. Do not put regular X applications here. Most of them go into other [.filename]#x11-*# categories (see below).

|[.filename]#x11-clocks#
|X11 clocks.
|

|[.filename]#x11-drivers#
|X11 drivers.
|

|[.filename]#x11-fm#
|X11 file managers.
|

|[.filename]#x11-fonts#
|X11 fonts and font utilities.
|

|[.filename]#x11-servers#
|X11 servers.
|

|[.filename]#x11-themes#
|X11 themes.
|

|[.filename]#x11-toolkits#
|X11 toolkits.
|

|[.filename]#x11-wm#
|X11 window managers.
|

|[.filename]#xfce#`*`
|Ports related to the http://www.xfce.org/[Xfce] desktop environment.
|

|[.filename]#zope#`*`
|http://www.zope.org/[Zope] support.
|
|===

[[choosing-categories]]
=== Choosing the Right Category

As many of the categories overlap, choosing which of the categories will be the primary category of the port can be tedious. There are several rules that govern this issue. Here is the list of priorities, in decreasing order of precedence:

* The first category must be a physical category (see <<porting-categories,above>>). This is necessary to make the packaging work. Virtual categories and physical categories may be intermixed after that.
* Language specific categories always come first. For example, if the port installs Japanese X11 fonts, then the `CATEGORIES` line would read [.filename]#japanese x11-fonts#.
* Specific categories are listed before less-specific ones. For instance, an HTML editor is listed as [.filename]#www editors#, not the other way around. Also, do not list [.filename]#net# when the port belongs to any of [.filename]#irc#, [.filename]#mail#, [.filename]#news#, [.filename]#security#, or [.filename]#www#, as [.filename]#net# is included implicitly.
* [.filename]#x11# is used as a secondary category only when the primary category is a natural language. In particular, do not put [.filename]#x11# in the category line for X applications.
* Emacs modes are placed in the same ports category as the application supported by the mode, not in [.filename]#editors#. For example, an Emacs mode to edit source files of some programming language goes into [.filename]#lang#.
* Ports installing loadable kernel modules also have the virtual category [.filename]#kld# in their `CATEGORIES` line. This is one of the things handled automatically by adding `USES=kmod`.
* [.filename]#misc# does not appear with any other non-virtual category. If there is `misc` with something else in `CATEGORIES`, that means `misc` can safely be deleted and the port placed only in the other subdirectory.
* If the port truly does not belong anywhere else, put it in [.filename]#misc#.

If the category is not clearly defined, please put a comment to that effect in the https://bugs.freebsd.org/submit/[port submission] in the bug database so we can discuss it before we import it. As a committer, send a note to the {freebsd-ports} so we can discuss it first. Too often, new ports are imported to the wrong category only to be moved right away.

[[proposing-categories]]
=== Proposing a New Category

As the Ports Collection has grown over time, various new categories have been introduced. New categories can either be _virtual_ categories-those that do not have a corresponding subdirectory in the ports tree- or _physical_ categories-those that do. This section discusses the issues involved in creating a new physical category. Read it thouroughly before proposing a new one.

Our existing practice has been to avoid creating a new physical category unless either a large number of ports would logically belong to it, or the ports that would belong to it are a logically distinct group that is of limited general interest (for instance, categories related to spoken human languages), or preferably both.

The rationale for this is that such a change creates a link:{committers-guide}#ports[fair amount of work] for both the committers and also for all users who track changes to the Ports Collection. In addition, proposed category changes just naturally seem to attract controversy. (Perhaps this is because there is no clear consensus on when a category is "too big", nor whether categories should lend themselves to browsing (and thus what number of categories would be an ideal number), and so forth.)

Here is the procedure:

[.procedure]
====
. Propose the new category on {freebsd-ports}. Include a detailed rationale for the new category, including why the existing categories are not sufficient, and the list of existing ports proposed to move. (If there are new ports pending in Bugzilla that would fit this category, list them too.) If you are the maintainer and/or submitter, respectively, mention that as it may help the case.
. Participate in the discussion.
. If it seems that there is support for the idea, file a PR which includes both the rationale and the list of existing ports that need to be moved. Ideally, this PR would also include these patches:

** [.filename]##Makefile##s for the new ports once they are repocopied
** [.filename]#Makefile# for the new category
** [.filename]#Makefile# for the old ports' categories
** [.filename]##Makefile##s for ports that depend on the old ports
** (for extra credit, include the other files that have to change, as per the procedure in the Committer's Guide.)

. Since it affects the ports infrastructure and involves moving and patching many ports but also possibly running regression tests on the build cluster, assign the PR to the {portmgr}.
. If that PR is approved, a committer will need to follow the rest of the procedure that is link:{committers-guide}#PORTS[outlined in the Committer's Guide].
====

Proposing a new virtual category is similar to the above but much less involved, since no ports will actually have to move. In this case, the only patches to include in the PR would be those to add the new category to `CATEGORIES` of the affected ports.

[[proposing-reorg]]
=== Proposing Reorganizing All the Categories

Occasionally someone proposes reorganizing the categories with either a 2-level structure, or some other kind of keyword structure. To date, nothing has come of any of these proposals because, while they are very easy to make, the effort involved to retrofit the entire existing ports collection with any kind of reorganization is daunting to say the very least. Please read the history of these proposals in the mailing list archives before posting this idea. Furthermore, be prepared to be challenged to offer a working prototype.

[[makefile-distfiles]]
== The Distribution Files

The second part of the [.filename]#Makefile# describes the files that must be downloaded to build the port, and where they can be downloaded.

[[makefile-distname]]
=== `DISTNAME`

`DISTNAME` is the name of the port as called by the authors of the software. `DISTNAME` defaults to `${PORTNAME}-${DISTVERSIONPREFIX}${DISTVERSION}${DISTVERSIONSUFFIX}`, and if not set, `DISTVERSION` defaults to `${PORTVERSION}` so override `DISTNAME` only if necessary. `DISTNAME` is only used in two places. First, the distribution file list (`DISTFILES`) defaults to `${DISTNAME}${EXTRACT_SUFX}`. Second, the distribution file is expected to extract into a subdirectory named `WRKSRC`, which defaults to [.filename]#work/${DISTNAME}#.

Some vendor's distribution names which do not fit into the `${PORTNAME}-${PORTVERSION}`-scheme can be handled automatically by setting `DISTVERSIONPREFIX`, `DISTVERSION`, and `DISTVERSIONSUFFIX`. `PORTVERSION` will be derived from `DISTVERSION` automatically.

[IMPORTANT]
====
Only one of `PORTVERSION` and `DISTVERSION` can be set at a time. If `DISTVERSION` does not derive a correct `PORTVERSION`, do not use `DISTVERSION`.
====

If the upstream version scheme can be derived into a ports-compatible version scheme, set some variable to the upstream version, _do not_ use `DISTVERSION` as the variable name. Set `PORTVERSION` to the computed version based on the variable you created, and set `DISTNAME` accordingly.

If the upstream version scheme cannot easily be coerced into a ports-compatible value, set `PORTVERSION` to a sensible value, and set `DISTNAME` with `PORTNAME` with the verbatim upstream version.

[[makefile-distname-ex1]]
.Deriving `PORTVERSION` Manually
[example]
====
BIND9 uses a version scheme that is not compatible with the ports versions (it has `-` in its versions) and cannot be derived using `DISTVERSION` because after the 9.9.9 release, it will release a "patchlevels" in the form of `9.9.9-P1`. DISTVERSION would translate that into `9.9.9.p1`, which, in the ports versioning scheme means 9.9.9 pre-release 1, which is before 9.9.9 and not after. So `PORTVERSION` is manually derived from an `ISCVERSION` variable to output `9.9.9p1`.

The order into which the ports framework, and pkg, will sort versions is checked using the `-t` argument of man:pkg-version[8]:

[source,bash]
....
% pkg version -t 9.9.9 9.9.9.p1
> <.>
% pkg version -t 9.9.9 9.9.9p1 
< <.>
....

<.> The `>` sign means that the first argument passed to `-t` is greater than the second argument. `9.9.9` is after `9.9.9.p1`.
<.> The `<` sign means that the first argument passed to `-t` is less than the second argument. `9.9.9` is before `9.9.9p1`.

In the port [.filename]#Makefile#, for example package:dns/bind99[], it is achieved by:

[.programlisting]
....
PORTNAME=	bind
PORTVERSION=	${ISCVERSION:S/-P/P/:S/b/.b/:S/a/.a/:S/rc/.rc/} 
CATEGORIES=	dns net
MASTER_SITES=	ISC/bind9/${ISCVERSION} 
PKGNAMESUFFIX=	99
DISTNAME=	${PORTNAME}-${ISCVERSION} 

MAINTAINER=	mat@FreeBSD.org
COMMENT=	BIND DNS suite with updated DNSSEC and DNS64

LICENSE=	ISCL

# ISC releases things like 9.8.0-P1 or 9.8.1rc1, which our versioning does not like
ISCVERSION=	9.9.9-P6
....

Define upstream version in `ISCVERSION`, with a comment saying _why_ it is needed.
Use `ISCVERSION` to get a ports-compatible `PORTVERSION`.
Use `ISCVERSION` directly to get the correct URL for fetching the distribution file.
Use `ISCVERSION` directly to name the distribution file.
====

[[makefile-distname-ex2]]
.Derive `DISTNAME` from `PORTVERSION`
[example]
====
From time to time, the distribution file name has little or no relation to the version of the software.

In package:comms/kermit[], only the last element of the version is present in the distribution file:

[.programlisting]
....
PORTNAME=	kermit
PORTVERSION=	9.0.304
CATEGORIES=	comms ftp net
MASTER_SITES=	ftp://ftp.kermitproject.org/kermit/test/tar/
DISTNAME=	cku${PORTVERSION:E}-dev20
....

The `:E` man:make[1] modifier returns the suffix of the variable, in this case, `304`. The distribution file is correctly generated as `cku304-dev20.tar.gz`.
====

[[makefile-distname-ex3]]
.Exotic Case 1
[example]
====
Sometimes, there is no relation between the software name, its version, and the distribution file it is distributed in.

From package:audio/libworkman[]:

[.programlisting]
....
PORTNAME=       libworkman
PORTVERSION=    1.4
CATEGORIES=     audio
MASTER_SITES=   LOCAL/jim
DISTNAME=       ${PORTNAME}-1999-06-20
....

====

[[makefile-distname-ex4]]
.Exotic Case 2
[example]
====
In package:comms/librs232[], the distribution file is not versioned, so using <<makefile-dist_subdir,`DIST_SUBDIR`>> is needed:

[.programlisting]
....
PORTNAME=       librs232
PORTVERSION=    20160710
CATEGORIES=     comms
MASTER_SITES=   http://www.teuniz.net/RS-232/
DISTNAME=       RS-232
DIST_SUBDIR=	${PORTNAME}-${PORTVERSION}
....

====

[NOTE]
====
`PKGNAMEPREFIX` and `PKGNAMESUFFIX` do not affect `DISTNAME`. Also note that if `WRKSRC` is equal to [.filename]#${WRKDIR}/${DISTNAME}# while the original source archive is named something other than `${PORTNAME}-${PORTVERSION}${EXTRACT_SUFX}`, leave `DISTNAME` alone- defining only `DISTFILES` is easier than both `DISTNAME` and `WRKSRC` (and possibly `EXTRACT_SUFX`).
====

[[makefile-master_sites]]
=== `MASTER_SITES`

Record the directory part of the FTP/HTTP-URL pointing at the original tarball in `MASTER_SITES`. Do not forget the trailing slash ([.filename]#/#)!

The `make` macros will try to use this specification for grabbing the distribution file with `FETCH` if they cannot find it already on the system.

It is recommended that multiple sites are included on this list, preferably from different continents. This will safeguard against wide-area network problems.

[IMPORTANT]
====
`MASTER_SITES` must not be blank. It must point to the actual site hosting the distribution files. It cannot point to web archives, or the FreeBSD distribution files cache sites. The only exception to this rule is ports that do not have any distribution files. For example, meta-ports do not have any distribution files, so `MASTER_SITES` does not need to be set.
====

[[makefile-master_sites-shorthand]]
==== Using `MASTER_SITE_*` Variables

Shortcut abbreviations are available for popular archives like SourceForge (`SOURCEFORGE`), GNU (`GNU`), or Perl CPAN (`PERL_CPAN`). `MASTER_SITES` can use them directly:

[.programlisting]
....
MASTER_SITES=	GNU/make
....

The older expanded format still works, but all ports have been converted to the compact format. The expanded format looks like this:

[.programlisting]
....
MASTER_SITES=		${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR=	make
....

These values and variables are defined in https://svnweb.freebsd.org/ports/head/Mk/bsd.sites.mk?view=markup[Mk/bsd.sites.mk]. New entries are added often, so make sure to check the latest version of this file before submitting a port.

[TIP]
====

For any `MASTER_SITE_FOO` variable, the shorthand `_FOO_` can be used. For example, use:

[.programlisting]
....
MASTER_SITES=	FOO
....

If `MASTER_SITE_SUBDIR` is needed, use this:

[.programlisting]
....
MASTER_SITES=	FOO/bar
....

====

[NOTE]
====
Some `MASTER_SITE_*` names are quite long, and for ease of use, shortcuts have been defined:

[[makefile-master_sites-shortcut]]
.Shortcuts for `MASTER_SITE_*` Macros
[cols="1,1", frame="none", options="header"]
|===
| Macro
| Shortcut

|`PERL_CPAN`
|`CPAN`

|`GITHUB`
|`GH`

|`GITHUB_CLOUD`
|`GHC`

|`LIBREOFFICE_DEV`
|`LODEV`

|`NETLIB`
|`NL`

|`RUBYGEMS`
|`RG`

|`SOURCEFORGE`
|`SF`
|===
====

[[makefile-master_sites-magic]]
==== Magic MASTER_SITES Macros

Several "magic" macros exist for popular sites with a predictable directory structure. For these, just use the abbreviation and the system will choose a subdirectory automatically. For a port named `Stardict`, of version `1.2.3`, and hosted on SourceForge, adding this line:

[.programlisting]
....
MASTER_SITES=	SF
....

infers a subdirectory named `/project/stardict/stardict/1.2.3`. If the inferred directory is incorrect, it can be overridden:

[.programlisting]
....
MASTER_SITES=	SF/stardict/WyabdcRealPeopleTTS/${PORTVERSION}
....

This can also be written as

[.programlisting]
....
MASTER_SITES=	SF
MASTER_SITE_SUBDIR=	stardict/WyabdcRealPeopleTTS/${PORTVERSION}
....

[[makefile-master_sites-popular]]
.Magic `MASTER_SITES` Macros
[cols="1,1", frame="none", options="header"]
|===
| Macro
| Assumed subdirectory

|`APACHE_COMMONS_BINARIES`
|`${PORTNAME:S,commons-,,}`

|`APACHE_COMMONS_SOURCE`
|`${PORTNAME:S,commons-,,}`

|`APACHE_JAKARTA`
|`${PORTNAME:S,-,/,}/source`

|`BERLIOS`
|`${PORTNAME:tl}.berlios`

|`CHEESESHOP`
|`source/${DISTNAME:C/(.).\*/\1/}/${DISTNAME:C/(.*)-[0-9].*/\1/}`

|`CPAN`
|`${PORTNAME:C/-.*//}`

|`DEBIAN`
|`pool/main/${PORTNAME:C/^((lib)?.).*$/\1/}/${PORTNAME}`

|`FARSIGHT`
|`${PORTNAME}`

|`FESTIVAL`
|`${PORTREVISION}`

|`GCC`
|`releases/${DISTNAME}`

|`GENTOO`
|`distfiles`

|`GIMP`
|`${PORTNAME}/${PORTVERSION:R}/`

|`GH`
|`${GH_ACCOUNT}/${GH_PROJECT}/tar.gz/${GH_TAGNAME}?dummy=/`

|`GHC`
|`${GH_ACCOUNT}/${GH_PROJECT}/`

|`GNOME`
|`sources/${PORTNAME}/${PORTVERSION:C/^([0-9]+\.[0-9]+).*/\1/}`

|`GNU`
|`${PORTNAME}`

|`GNUPG`
|`${PORTNAME}`

|`GNU_ALPHA`
|`${PORTNAME}`

|`HORDE`
|`${PORTNAME}`

|`LODEV`
|`${PORTNAME}`

|`MATE`
|`${PORTVERSION:C/^([0-9]+\.[0-9]+).*/\1/}`

|`MOZDEV`
|`${PORTNAME:tl}`

|`NL`
|`${PORTNAME}`

|`QT`
|`archive/qt/${PORTVERSION:R}`

|`SAMBA`
|`${PORTNAME}`

|`SAVANNAH`
|`${PORTNAME:tl}`

|`SF`
|`${PORTNAME:tl}/${PORTNAME:tl}/${PORTVERSION}`
|===

[[makefile-master_sites-github]]
=== `USE_GITHUB`

If the distribution file comes from a specific commit or tag on https://github.com[GitHub] for which there is no officially released file, there is an easy way to set the right `DISTNAME` and `MASTER_SITES` automatically. These variables are available:

[[makefile-master_sites-github-description]]
.`USE_GITHUB` Description
[cols="1,1,1", options="header"]
|===
| Variable
| Description
| Default

|`GH_ACCOUNT`
|Account name of the GitHub user hosting the project
|`${PORTNAME}`

|`GH_PROJECT`
|Name of the project on GitHub
|`${PORTNAME}`

|`GH_TAGNAME`
|Name of the tag to download (2.0.1, hash, ...) Using the name of a branch here is incorrect. It is also possible to use the hash of a commit id to do a snapshot.
|`${DISTVERSIONPREFIX}${DISTVERSION}${DISTVERSIONSUFFIX}`

|`GH_SUBDIR`
|When the software needs an additional distribution file to be extracted within `${WRKSRC}`, this variable can be used. See the examples in <<makefile-master_sites-github-multiple>> for more information.
|(none)

|`GH_TUPLE`
|`GH_TUPLE` allows putting `GH_ACCOUNT`, `GH_PROJECT`, `GH_TAGNAME`, and `GH_SUBDIR` into a single variable. The format is _account_`:`_project_`:`_tagname_`:`_group_`/`_subdir_. The `/`_subdir_ part is optional. It is helpful when there is more than one GitHub project from which to fetch.
|===

[IMPORTANT]
====
Do not use `GH_TUPLE` for the default distribution file, as it has no default.
====

[[makefile-master_sites-github-ex1]]
.Simple Use of `USE_GITHUB`
[example]
====

While trying to make a port for version `1.2.7` of pkg from the FreeBSD user on github, at https://github.com/freebsd/pkg[], The [.filename]#Makefile# would end up looking like this (slightly stripped for the example):

[.programlisting]
....
PORTNAME=	pkg
DISTVERSION=	1.2.7

USE_GITHUB=	yes
GH_ACCOUNT=	freebsd
....

It will automatically have `MASTER_SITES` set to `GH GHC` and `WRKSRC` to `${WRKDIR}/pkg-1.2.7`.
====

[[makefile-master_sites-github-ex2]]
.More Complete Use of `USE_GITHUB`
[example]
====
While trying to make a port for the bleeding edge version of pkg from the FreeBSD user on github, at https://github.com/freebsd/pkg[], the [.filename]#Makefile# ends up looking like this (slightly stripped for the example):

[.programlisting]
....
PORTNAME=	pkg-devel
DISTVERSION=	1.3.0.a.20140411

USE_GITHUB=	yes
GH_ACCOUNT=	freebsd
GH_PROJECT=	pkg
GH_TAGNAME=	6dbb17b
....

It will automatically have `MASTER_SITES` set to `GH GHC` and `WRKSRC` to `${WRKDIR}/pkg-6dbb17b`.

[TIP]
****

`20140411` is the date of the commit referenced in `GH_TAGNAME`, not the date the [.filename]#Makefile# is edited, or the date the commit is made.
****

====

[[makefile-master_sites-github-ex3]]
.Use of `USE_GITHUB` with `DISTVERSIONPREFIX`
[example]
====
From time to time, `GH_TAGNAME` is a slight variation from `DISTVERSION`. For example, if the version is `1.0.2`, the tag is `v1.0.2`. In those cases, it is possible to use `DISTVERSIONPREFIX` or `DISTVERSIONSUFFIX`:

[.programlisting]
....
PORTNAME=	foo
DISTVERSIONPREFIX=	v
DISTVERSION=	1.0.2

USE_GITHUB=	yes
....

It will automatically set `GH_TAGNAME` to `v1.0.2`, while `WRKSRC` will be kept to `${WRKDIR}/foo-1.0.2`.
====

[[makefile-master_sites-github-ex4]]
.Using `USE_GITHUB` When Upstream Does Not Use Versions
[example]
====
If there never was a version upstream, do not invent one like `0.1` or `1.0`. Create the port with a `DISTVERSION` of `g__YYYYMMDD__`, where `g` is for Git, and `_YYYYMMDD_` represents the date the commit referenced in `GH_TAGNAME`.

[.programlisting]
....
PORTNAME=	bar
DISTVERSION=	g20140411

USE_GITHUB=	yes
GH_TAGNAME=	c472d66b
....

This creates a versioning scheme that increases over time, and that is still before version `0` (see <<makefile-versions-ex-pkg-version>> for details on man:pkg-version[8]):

[source,bash]
....
% pkg version -t g20140411 0
<
....

Which means using `PORTEPOCH` will not be needed in case upstream decides to cut versions in the future.
====

[[makefile-master_sites-github-ex5]]
.Using `USE_GITHUB` to Access a Commit Between Two Versions
[example]
====

If the current version of the software uses a Git tag, and the port needs to be updated to a newer, intermediate version, without a tag, use man:git-describe[1] to find out the version to use:

[source,bash]
....
% git describe --tags f0038b1
v0.7.3-14-gf0038b1
....

`v0.7.3-14-gf0038b1` can be split into three parts:

`v0.7.3`::
This is the last Git tag that appears in the commit history before the requested commit.

`-14`::
This means that the requested commit, `f0038b1`, is the 14th commit after the `v0.7.3` tag.

`-gf0038b1`::
The `-g` means "Git", and the `f0038b1` is the commit hash that this reference points to.

[.programlisting]
....
PORTNAME=	bar
DISTVERSIONPREFIX=  v
DISTVERSION=	0.7.3-14
DISTVERSIONSUFFIX=  -gf0038b1

USE_GITHUB=	yes
....

This creates a versioning scheme that increases over time (well, over commits), and does not conflict with the creation of a `0.7.4` version. (See <<makefile-versions-ex-pkg-version>> for details on man:pkg-version[8]):

[source,bash]
....
% pkg version -t 0.7.3 0.7.3.14
<
% pkg version -t 0.7.3.14 0.7.4
<
....

[NOTE]
****
If the requested commit is the same as a tag, a shorter description is shown by default. The longer version is equivalent:

[source,bash]
....
% git describe --tags c66c71d
v0.7.3

% git describe --tags --long c66c71d
v0.7.3-0-gc66c71d
....

****

====

[[makefile-master_sites-github-multiple]]
==== Fetching Multiple Files from GitHub

The `USE_GITHUB` framework also supports fetching multiple distribution files from different places in GitHub. It works in a way very similar to <<porting-master-sites-n>>.

Multiple values are added to `GH_ACCOUNT`, `GH_PROJECT`, and `GH_TAGNAME`. Each different value is assigned a group. The main value can either have no group, or the `:DEFAULT` group. A value can be omitted if it is the same as the default as listed in <<makefile-master_sites-github-description>>.

`GH_TUPLE` can also be used when there are a lot of distribution files. It helps keep the account, project, tagname, and group information at the same place.

For each group, a `${WRKSRC_group}` helper variable is created, containing the directory into which the file has been extracted. The `${WRKSRC_group}` variables can be used to move directories around during `post-extract`, or add to `CONFIGURE_ARGS`, or whatever is needed so that the software builds correctly.

[CAUTION]
====

The `:__group__` part _must_ be used for _only one_ distribution file. It is used as a unique key and using it more than once will overwrite the previous values.
====

[NOTE]
====
As this is only syntactic sugar above `DISTFILES` and `MASTER_SITES`, the group names must adhere to the restrictions on group names outlined in <<porting-master-sites-n>>
====

When fetching multiple files from GitHub, sometimes the default distribution file is not fetched from GitHub. To disable fetching the default distribution, set:

[.programlisting]
....
USE_GITHUB=	nodefault
....

[IMPORTANT]
====
When using `USE_GITHUB=nodefault`, the [.filename]#Makefile# must set `DISTFILES` in its <<porting-order-portname,top block>>. The definition should be:

[.programlisting]
....
DISTFILES=    ${DISTNAME}${EXTRACT_SUFX}
....

====

[[makefile-master_sites-github-multi]]
.Use of `USE_GITHUB` with Multiple Distribution Files
[example]
====
From time to time, there is a need to fetch more than one distribution file. For example, when the upstream git repository uses submodules. This can be done easily using groups in the `GH_*` variables:

[.programlisting]
....
PORTNAME=	foo
DISTVERSION=	1.0.2

USE_GITHUB=	yes
GH_ACCOUNT=	bar:icons,contrib
GH_PROJECT=	foo-icons:icons foo-contrib:contrib
GH_TAGNAME=	1.0:icons fa579bc:contrib
GH_SUBDIR=	ext/icons:icons

CONFIGURE_ARGS=	--with-contrib=${WRKSRC_contrib}
....

This will fetch three distribution files from github. The default one comes from [.filename]#foo/foo# and is version `1.0.2`. The second one, with the `icons` group, comes from [.filename]#bar/foo-icons# and is in version `1.0`. The third one comes from [.filename]#bar/foo-contrib# and uses the Git commit `fa579bc`. The distribution files are named [.filename]#foo-foo-1.0.2_GH0.tar.gz#, [.filename]#bar-foo-icons-1.0_GH0.tar.gz#, and [.filename]#bar-foo-contrib-fa579bc_GH0.tar.gz#.

All the distribution files are extracted in `${WRKDIR}` in their respective subdirectories. The default file is still extracted in `${WRKSRC}`, in this case, [.filename]#${WRKDIR}/foo-1.0.2#. Each additional distribution file is extracted in `${WRKSRC_group}`. Here, for the `icons` group, it is called `${WRKSRC_icons}` and it contains [.filename]#${WRKDIR}/foo-icons-1.0#. The file with the `contrib` group is called `${WRKSRC_contrib}` and contains `${WRKDIR}/foo-contrib-fa579bc`.

The software's build system expects to find the icons in a [.filename]#ext/icons# subdirectory in its sources, so `GH_SUBDIR` is used. `GH_SUBDIR` makes sure that [.filename]#ext# exists, but that [.filename]#ext/icons# does not already exist. Then it does this:

[.programlisting]
....
post-extract:
      @${MV} ${WRKSRC_icons} ${WRKSRC}/ext/icons
....

====

[[makefile-master_sites-github-multi2]]
.Use of `USE_GITHUB` with Multiple Distribution Files Using `GH_TUPLE`
[example]
====

This is functionally equivalent to <<makefile-master_sites-github-multi>>, but using `GH_TUPLE`:

[.programlisting]
....
PORTNAME=	foo
DISTVERSION=	1.0.2

USE_GITHUB=	yes
GH_TUPLE=	bar:foo-icons:1.0:icons/ext/icons \
		bar:foo-contrib:fa579bc:contrib

CONFIGURE_ARGS=	--with-contrib=${WRKSRC_contrib}
....

Grouping was used in the previous example with `bar:icons,contrib`. Some redundant information is present with `GH_TUPLE` because grouping is not possible.
====

[[makefile-master_sites-github-submodules]]
.How to Use `USE_GITHUB` with Git Submodules?
[example]
====
Ports with GitHub as an upstream repository sometimes use submodules. See man:git-submodule[1] for more information.

The problem with submodules is that each is a separate repository. As such, they each must be fetched separately.

Using package:finance/moneymanagerex[] as an example, its GitHub repository is https://github.com/moneymanagerex/moneymanagerex[]. It has a https://github.com/moneymanagerex/moneymanagerex/blob/master/.gitmodules[.gitmodules] file at the root. This file describes all the submodules used in this repository, and lists additional repositories needed. This file will tell what additional repositories are needed:

[.programlisting]
....
[submodule "lib/wxsqlite3"]
	path = lib/wxsqlite3
	url = https://github.com/utelle/wxsqlite3.git
[submodule "3rd/mongoose"]
	path = 3rd/mongoose
	url = https://github.com/cesanta/mongoose.git
[submodule "3rd/LuaGlue"]
	path = 3rd/LuaGlue
	url = https://github.com/moneymanagerex/LuaGlue.git
[submodule "3rd/cgitemplate"]
	path = 3rd/cgitemplate
	url = https://github.com/moneymanagerex/html-template.git
[...]
....

The only information missing from that file is the commit hash or tag to use as a version. This information is found after cloning the repository:

[source,bash]
....
% git clone --recurse-submodules https://github.com/moneymanagerex/moneymanagerex.git
Cloning into 'moneymanagerex'...
remote: Counting objects: 32387, done.
[...]
Submodule '3rd/LuaGlue' (https://github.com/moneymanagerex/LuaGlue.git) registered for path '3rd/LuaGlue'
Submodule '3rd/cgitemplate' (https://github.com/moneymanagerex/html-template.git) registered for path '3rd/cgitemplate'
Submodule '3rd/mongoose' (https://github.com/cesanta/mongoose.git) registered for path '3rd/mongoose'
Submodule 'lib/wxsqlite3' (https://github.com/utelle/wxsqlite3.git) registered for path 'lib/wxsqlite3'
[...]
Cloning into '/home/mat/work/freebsd/ports/finance/moneymanagerex/moneymanagerex/3rd/LuaGlue'...
Cloning into '/home/mat/work/freebsd/ports/finance/moneymanagerex/moneymanagerex/3rd/cgitemplate'...
Cloning into '/home/mat/work/freebsd/ports/finance/moneymanagerex/moneymanagerex/3rd/mongoose'...
Cloning into '/home/mat/work/freebsd/ports/finance/moneymanagerex/moneymanagerex/lib/wxsqlite3'...
[...]
Submodule path '3rd/LuaGlue': checked out 'c51d11a247ee4d1e9817dfa2a8da8d9e2f97ae3b'
Submodule path '3rd/cgitemplate': checked out 'cd434eeeb35904ebcd3d718ba29c281a649b192c'
Submodule path '3rd/mongoose': checked out '2140e5992ab9a3a9a34ce9a281abf57f00f95cda'
Submodule path 'lib/wxsqlite3': checked out 'fb66eb230d8aed21dec273b38c7c054dcb7d6b51'
[...]
% cd moneymanagerex
% git submodule status
 c51d11a247ee4d1e9817dfa2a8da8d9e2f97ae3b 3rd/LuaGlue (heads/master)
 cd434eeeb35904ebcd3d718ba29c281a649b192c 3rd/cgitemplate (cd434ee)
 2140e5992ab9a3a9a34ce9a281abf57f00f95cda 3rd/mongoose (6.2-138-g2140e59)
 fb66eb230d8aed21dec273b38c7c054dcb7d6b51 lib/wxsqlite3 (v3.4.0)
[...]
....

It can also be found on GitHub. Each subdirectory that is a submodule is shown as `_directory @ hash_`, for example, `mongoose @ 2140e59`.

[NOTE]
****
While getting the information from GitHub seems more straightforward, the information found using `git submodule status` will provide more meaningful information. For example, here, ``lib/wxsqlite3``'s commit hash `fb66eb2` correspond to `v3.4.0`. Both can be used interchangeably, but when a tag is available, use it.
****

Now that all the required information has been gathered, the [.filename]#Makefile# can be written (only GitHub-related lines are shown):

[.programlisting]
....
PORTNAME=	moneymanagerex
DISTVERSIONPREFIX=	v
DISTVERSION=	1.3.0

USE_GITHUB=	yes
GH_TUPLE=	utelle:wxsqlite3:v3.4.0:wxsqlite3/lib/wxsqlite3 \
		moneymanagerex:LuaGlue:c51d11a:lua_glue/3rd/LuaGlue \
		moneymanagerex:html-template:cd434ee:html_template/3rd/cgitemplate \
		cesanta:mongoose:2140e59:mongoose/3rd/mongoose \
		[...]
....

====

[[makefile-master_sites-gitlab]]
=== `USE_GITLAB`

Similar to GitHub, if the distribution file comes from https://gitlab.com[gitlab.com] or is hosting the GitLab software, these variables are available for use and might need to be set.

[[makefile-master_sites-gitlab-description]]
.`USE_GITLAB` Description
[cols="1,1,1", options="header"]
|===
| Variable
| Description
| Default

|`GL_SITE`
|Site name hosting the GitLab project
|https://gitlab.com

|`GL_ACCOUNT`
|Account name of the GitLab user hosting the project
|`${PORTNAME}`

|`GL_PROJECT`
|Name of the project on GitLab
|`${PORTNAME}`

|`GL_COMMIT`
|The commit hash to download. Must be the full 160 bit, 40 character hex sha1 hash. This is a required variable for GitLab.
|`(none)`

|`GL_SUBDIR`
|When the software needs an additional distribution file to be extracted within `${WRKSRC}`, this variable can be used. See the examples in <<makefile-master_sites-gitlab-multiple>> for more information.
|(none)

|`GL_TUPLE`
|`GL_TUPLE` allows putting `GL_SITE`, `GL_ACCOUNT`, `GL_PROJECT`, `GL_COMMIT`, and `GL_SUBDIR` into a single variable. The format is _site_`:`_account_`:`_project_`:`_commit_`:`_group_`/`_subdir_. The _site_`:` and `/`_subdir_ part is optional. It is helpful when there are more than one GitLab project from which to fetch.
|===

[[makefile-master_sites-gitlab-ex1]]
.Simple Use of `USE_GITLAB`
[example]
====
While trying to make a port for version `1.14` of libsignon-glib from the accounts-sso user on gitlab.com, at https://gitlab.com/accounts-sso/libsignon-glib[], The [.filename]#Makefile# would end up looking like this for fetching the distribution files:

[.programlisting]
....
PORTNAME=	libsignon-glib
DISTVERSION=	1.14

USE_GITLAB=	yes
GL_ACCOUNT=	accounts-sso
GL_COMMIT=	e90302e342bfd27bc8c9132ab9d0ea3d8723fd03
....

It will automatically have `MASTER_SITES` set to https://gitlab.com[gitlab.com] and `WRKSRC` to `${WRKDIR}/libsignon-glib-e90302e342bfd27bc8c9132ab9d0ea3d8723fd03-e90302e342bfd27bc8c9132ab9d0ea3d8723fd03`.
====

[[makefile-master_sites-gitlab-ex2]]
.More Complete Use of `USE_GITLAB`
[example]
====

A more complete use of the above if port had no versioning and foobar from the foo user on project bar on a self hosted GitLab site `https://gitlab.example.com`, the [.filename]#Makefile# ends up looking like this for fetching distribution files:

[.programlisting]
....
PORTNAME=	foobar
DISTVERSION=	g20170906

USE_GITLAB=	yes
GL_SITE=	https://gitlab.example.com
GL_ACCOUNT=	foo
GL_PROJECT=	bar
GL_COMMIT=	9c1669ce60c3f4f5eb43df874d7314483fb3f8a6
....

It will have `MASTER_SITES` set to "`https://gitlab.example.com`" and `WRKSRC` to `${WRKDIR}/bar-9c1669ce60c3f4f5eb43df874d7314483fb3f8a6-9c1669ce60c3f4f5eb43df874d7314483fb3f8a6`.

[TIP]
****

`20170906` is the date of the commit referenced in `GL_COMMIT`, not the date the [.filename]#Makefile# is edited, or the date the commit to the FreeBSD ports tree is made.
****

[NOTE]
****
``GL_SITE``'s protocol, port and webroot can all be modified in the same variable.
****

====

[[makefile-master_sites-gitlab-multiple]]
==== Fetching Multiple Files from GitLab

The `USE_GITLAB` framework also supports fetching multiple distribution files from different places from GitLab and GitLab hosted sites. It works in a way very similar to <<porting-master-sites-n>> and <<makefile-master_sites-gitlab-multiple>>.

Multiple values are added to `GL_SITE`, `GL_ACCOUNT`, `GL_PROJECT` and `GL_COMMIT`. Each different value is assigned a group. <<makefile-master_sites-gitlab-description>>.

`GL_TUPLE` can also be used when there are a lot of distribution files. It helps keep the site, account, project, commit, and group information at the same place.

For each group, a `${WRKSRC_group}` helper variable is created, containing the directory into which the file has been extracted. The `${WRKSRC_group}` variables can be used to move directories around during `post-extract`, or add to `CONFIGURE_ARGS`, or whatever is needed so that the software builds correctly.

[CAUTION]
====

The `:__group__` part _must_ be used for _only one_ distribution file. It is used as a unique key and using it more than once will overwrite the previous values.
====

[NOTE]
====
As this is only syntactic sugar above `DISTFILES` and `MASTER_SITES`, the group names must adhere to the restrictions on group names outlined in <<porting-master-sites-n>>
====

When fetching multiple files using GitLab, sometimes the default distribution file is not fetched from a GitLab site. To disable fetching the default distribution, set:

[.programlisting]
....
USE_GITLAB=	nodefault
....

[IMPORTANT]
====
When using `USE_GITLAB=nodefault`, the [.filename]#Makefile# must set `DISTFILES` in its <<porting-order-portname,top block>>. The definition should be:

[.programlisting]
....
DISTFILES=    ${DISTNAME}${EXTRACT_SUFX}
....

====

[[makefile-master_sites-gitlab-multi]]
.Use of `USE_GITLAB` with Multiple Distribution Files
[example]
====

From time to time, there is a need to fetch more than one distribution file. For example, when the upstream git repository uses submodules. This can be done easily using groups in the `GL_*` variables:

[.programlisting]
....
PORTNAME=	foo
DISTVERSION=	1.0.2

USE_GITLAB=	yes
GL_SITE=	https://gitlab.example.com:9434/gitlab:icons
GL_ACCOUNT=	bar:icons,contrib
GL_PROJECT=	foo-icons:icons foo-contrib:contrib
GL_COMMIT=	c189207a55da45305c884fe2b50e086fcad4724b ae7368cab1ca7ca754b38d49da064df87968ffe4:icons 9e4dd76ad9b38f33fdb417a4c01935958d5acd2a:contrib
GL_SUBDIR=	ext/icons:icons

CONFIGURE_ARGS= --with-contrib=${WRKSRC_contrib}
....

This will fetch two distribution files from gitlab.com and one from `gitlab.example.com` hosting GitLab. The default one comes from [.filename]#https://gitlab.com/foo/foo# and commit is `c189207a55da45305c884fe2b50e086fcad4724b`. The second one, with the `icons` group, comes from [.filename]#https://gitlab.example.com:9434/gitlab/bar/foo-icons# and commit is `ae7368cab1ca7ca754b38d49da064df87968ffe4`. The third one comes from [.filename]#https://gitlab.com/bar/foo-contrib# and is commit `9e4dd76ad9b38f33fdb417a4c01935958d5acd2a`. The distribution files are named [.filename]#foo-foo-c189207a55da45305c884fe2b50e086fcad4724b_GL0.tar.gz#, [.filename]#bar-foo-icons-ae7368cab1ca7ca754b38d49da064df87968ffe4_GL0.tar.gz#, and [.filename]#bar-foo-contrib-9e4dd76ad9b38f33fdb417a4c01935958d5acd2a_GL0.tar.gz#.

All the distribution files are extracted in `${WRKDIR}` in their respective subdirectories. The default file is still extracted in `${WRKSRC}`, in this case, [.filename]#${WRKDIR}/foo-c189207a55da45305c884fe2b50e086fcad4724b-c189207a55da45305c884fe2b50e086fcad4724b#. Each additional distribution file is extracted in `${WRKSRC_group}`. Here, for the `icons` group, it is called `${WRKSRC_icons}` and it contains [.filename]#${WRKDIR}/foo-icons-ae7368cab1ca7ca754b38d49da064df87968ffe4-ae7368cab1ca7ca754b38d49da064df87968ffe4#. The file with the `contrib` group is called `${WRKSRC_contrib}` and contains `${WRKDIR}/foo-contrib-9e4dd76ad9b38f33fdb417a4c01935958d5acd2a-9e4dd76ad9b38f33fdb417a4c01935958d5acd2a`.

The software's build system expects to find the icons in a [.filename]#ext/icons# subdirectory in its sources, so `GL_SUBDIR` is used. `GL_SUBDIR` makes sure that [.filename]#ext# exists, but that [.filename]#ext/icons# does not already exist. Then it does this:

[.programlisting]
....
post-extract:
        @${MV} ${WRKSRC_icons} ${WRKSRC}/ext/icons
....

====

[[makefile-master_sites-gitlab-multi2]]
.Use of `USE_GITLAB` with Multiple Distribution Files Using `GL_TUPLE`
[example]
====
This is functionally equivalent to <<makefile-master_sites-gitlab-multi>>, but using `GL_TUPLE`:

[.programlisting]
....
PORTNAME=	foo
DISTVERSION=	1.0.2

USE_GITLAB=	yes
GL_COMMIT=	c189207a55da45305c884fe2b50e086fcad4724b
GL_TUPLE=	https://gitlab.example.com:9434/gitlab:bar:foo-icons:ae7368cab1ca7ca754b38d49da064df87968ffe4:icons/ext/icons \
		bar:foo-contrib:9e4dd76ad9b38f33fdb417a4c01935958d5acd2a:contrib

CONFIGURE_ARGS= --with-contrib=${WRKSRC_contrib}
....

Grouping was used in the previous example with `bar:icons,contrib`. Some redundant information is present with `GL_TUPLE` because grouping is not possible.
====

[[makefile-extract_sufx]]
=== `EXTRACT_SUFX`

If there is one distribution file, and it uses an odd suffix to indicate the compression mechanism, set `EXTRACT_SUFX`.

For example, if the distribution file was named [.filename]#foo.tar.gzip# instead of the more normal [.filename]#foo.tar.gz#, write:

[.programlisting]
....
DISTNAME=	foo
EXTRACT_SUFX=	.tar.gzip
....

The `USES=tar[:__xxx__]`, `USES=lha` or `USES=zip` automatically set `EXTRACT_SUFX` to the most common archives extensions as necessary, see <<uses>> for more details. If neither of these are set then `EXTRACT_SUFX` defaults to `.tar.gz`.

[NOTE]
====
As `EXTRACT_SUFX` is only used in `DISTFILES`, only set one of them..
====

[[makefile-distfiles-definition]]
=== `DISTFILES`

Sometimes the names of the files to be downloaded have no resemblance to the name of the port. For example, it might be called [.filename]#source.tar.gz# or similar. In other cases the application's source code might be in several different archives, all of which must be downloaded.

If this is the case, set `DISTFILES` to be a space separated list of all the files that must be downloaded.

[.programlisting]
....
DISTFILES=	source1.tar.gz source2.tar.gz
....

If not explicitly set, `DISTFILES` defaults to `${DISTNAME}${EXTRACT_SUFX}`.

[[makefile-extract_only]]
=== `EXTRACT_ONLY`

If only some of the `DISTFILES` must be extracted-for example, one of them is the source code, while another is an uncompressed document-list the filenames that must be extracted in `EXTRACT_ONLY`.

[.programlisting]
....
DISTFILES=	source.tar.gz manual.html
EXTRACT_ONLY=	source.tar.gz
....

When none of the `DISTFILES` need to be uncompressed, set `EXTRACT_ONLY` to the empty string.

[.programlisting]
....
EXTRACT_ONLY=
....

[[porting-patchfiles]]
=== `PATCHFILES`

If the port requires some additional patches that are available by FTP or HTTP, set `PATCHFILES` to the names of the files and `PATCH_SITES` to the URL of the directory that contains them (the format is the same as `MASTER_SITES`).

If the patch is not relative to the top of the source tree (that is, `WRKSRC`) because it contains some extra pathnames, set `PATCH_DIST_STRIP` accordingly. For instance, if all the pathnames in the patch have an extra `foozolix-1.0/` in front of the filenames, then set `PATCH_DIST_STRIP=-p1`.

Do not worry if the patches are compressed; they will be decompressed automatically if the filenames end with [.filename]#.Z#, [.filename]#.gz#, [.filename]#.bz2# or [.filename]#.xz#.

If the patch is distributed with some other files, such as documentation, in a compressed tarball, using `PATCHFILES` is not possible. If that is the case, add the name and the location of the patch tarball to `DISTFILES` and `MASTER_SITES`. Then, use `EXTRA_PATCHES` to point to those files and [.filename]#bsd.port.mk# will automatically apply them. In particular, do _not_ copy patch files into [.filename]#${PATCHDIR}#. That directory may not be writable.

[TIP]
====

If there are multiple patches and they need mixed values for the strip parameter, it can be added alongside the patch name in `PATCHFILES`, e.g:

[.programlisting]
....
PATCHFILES=	patch1 patch2:-p1
....

This does not conflict with <<porting-master-sites-n,the master site grouping feature>>, adding a group also works:

[.programlisting]
....
PATCHFILES=	patch2:-p1:source2
....

====

[NOTE]
====
The tarball will have been extracted alongside the regular source by then, so there is no need to explicitly extract it if it is a regular compressed tarball. Take extra care not to overwrite something that already exists in that directory if extracting it manually. Also, do not forget to add a command to remove the copied patch in the `pre-clean` target.
====

[[porting-master-sites-n]]
=== Multiple Distribution or Patches Files from Multiple Locations

(Consider this to be a somewhat "advanced topic"; those new to this document may wish to skip this section at first).

This section has information on the fetching mechanism known as both `MASTER_SITES:n` and `MASTER_SITES_NN`. We will refer to this mechanism as `MASTER_SITES:n`.

A little background first. OpenBSD has a neat feature inside `DISTFILES` and `PATCHFILES` which allows files and patches to be postfixed with `:n` identifiers. Here, `n` can be any word containing `[0-9a-zA-Z_]` and denote a group designation. For example:

[.programlisting]
....
DISTFILES=	alpha:0 beta:1
....

In OpenBSD, distribution file [.filename]#alpha# will be associated with variable `MASTER_SITES0` instead of our common `MASTER_SITES` and [.filename]#beta# with `MASTER_SITES1`.

This is a very interesting feature which can decrease that endless search for the correct download site.

Just picture 2 files in `DISTFILES` and 20 sites in `MASTER_SITES`, the sites slow as hell where [.filename]#beta# is carried by all sites in `MASTER_SITES`, and [.filename]#alpha# can only be found in the 20th site. It would be such a waste to check all of them if the maintainer knew this beforehand, would it not? Not a good start for that lovely weekend!

Now that you have the idea, just imagine more `DISTFILES` and more `MASTER_SITES`. Surely our "distfiles survey meister" would appreciate the relief to network strain that this would bring.

In the next sections, information will follow on the FreeBSD implementation of this idea. We improved a bit on OpenBSD's concept.

[IMPORTANT]
====
The group names cannot have dashes in them (`-`), in fact, they cannot have any characters out of the `[a-zA-Z0-9_]` range. This is because, while man:make[1] is ok with variable names containing dashes, man:sh[1] is not.
====

[[porting-master-sites-n-simplified]]
==== Simplified Information

This section explains how to quickly prepare fine grained fetching of multiple distribution files and patches from different sites and subdirectories. We describe here a case of simplified `MASTER_SITES:n` usage. This will be sufficient for most scenarios. More detailed information are available in <<ports-master-sites-n-detailed>>.

Some applications consist of multiple distribution files that must be downloaded from a number of different sites. For example, Ghostscript consists of the core of the program, and then a large number of driver files that are used depending on the user's printer. Some of these driver files are supplied with the core, but many others must be downloaded from a variety of different sites.

To support this, each entry in `DISTFILES` may be followed by a colon and a "group name". Each site listed in `MASTER_SITES` is then followed by a colon, and the group that indicates which distribution files are downloaded from this site.

For example, consider an application with the source split in two parts, [.filename]#source1.tar.gz# and [.filename]#source2.tar.gz#, which must be downloaded from two different sites. The port's [.filename]#Makefile# would include lines like <<ports-master-sites-n-example-simple-use-one-file-per-site>>.

[[ports-master-sites-n-example-simple-use-one-file-per-site]]
.Simplified Use of `MASTER_SITES:n` with One File Per Site
[example]
====

[.programlisting]
....
MASTER_SITES=	ftp://ftp1.example.com/:source1 \
		http://www.example.com/:source2
DISTFILES=	source1.tar.gz:source1 \
		source2.tar.gz:source2
....

====

Multiple distribution files can have the same group. Continuing the previous example, suppose that there was a third distfile, [.filename]#source3.tar.gz#, that is downloaded from `ftp.example2.com`. The [.filename]#Makefile# would then be written like <<ports-master-sites-n-example-simple-use-more-than-one-file-per-site>>.

[[ports-master-sites-n-example-simple-use-more-than-one-file-per-site]]
.Simplified Use of `MASTER_SITES:n` with More Than One File Per Site
[example]
====

[.programlisting]
....
MASTER_SITES=	ftp://ftp.example.com/:source1 \
		http://www.example.com/:source2
DISTFILES=	source1.tar.gz:source1 \
		source2.tar.gz:source2 \
		source3.tar.gz:source2
....

====

[[ports-master-sites-n-detailed]]
==== Detailed Information

Okay, so the previous example did not reflect the new port's needs? In this section we will explain in detail how the fine grained fetching mechanism `MASTER_SITES:n` works and how it can be used.

. Elements can be postfixed with `:__n__` where _n_ is `[^:,]+`, that is, _n_ could conceptually be any alphanumeric string but we will limit it to `[a-zA-Z_][0-9a-zA-Z_]+` for now.
+ 
Moreover, string matching is case sensitive; that is, `n` is different from `N`.
+ 
However, these words cannot be used for postfixing purposes since they yield special meaning: `default`, `all` and `ALL` (they are used internally in item <<porting-master-sites-n-what-changes-in-port-targets, ii>>). Furthermore, `DEFAULT` is a special purpose word (check item <<porting-master-sites-n-DEFAULT-group,3>>).
. Elements postfixed with `:n` belong to the group `n`, `:m` belong to group `m` and so forth.
+
[[porting-master-sites-n-DEFAULT-group]]
. Elements without a postfix are groupless, they all belong to the special group `DEFAULT`. Any elements postfixed with `DEFAULT`, is just being redundant unless an element belongs to both `DEFAULT` and other groups at the same time (check item <<porting-master-sites-n-comma-operator,5>>).
+ 
These examples are equivalent but the first one is preferred:
+
[.programlisting]
....
MASTER_SITES=	alpha
....
+
[.programlisting]
....
MASTER_SITES=	alpha:DEFAULT
....

. Groups are not exclusive, an element may belong to several different groups at the same time and a group can either have either several different elements or none at all.
+
[[porting-master-sites-n-comma-operator]]
. When an element belongs to several groups at the same time, use the comma operator (`,`).
+ 
Instead of repeating it several times, each time with a different postfix, we can list several groups at once in a single postfix. For instance, `:m,n,o` marks an element that belongs to group `m`, `n` and `o`.
+ 
All these examples are equivalent but the last one is preferred:
+
[.programlisting]
....
MASTER_SITES=	alpha alpha:SOME_SITE
....
+
[.programlisting]
....
MASTER_SITES=	alpha:DEFAULT alpha:SOME_SITE
....
+
[.programlisting]
....
MASTER_SITES=	alpha:SOME_SITE,DEFAULT
....
+
[.programlisting]
....
MASTER_SITES=	alpha:DEFAULT,SOME_SITE
....

. All sites within a given group are sorted according to `MASTER_SORT_AWK`. All groups within `MASTER_SITES` and `PATCH_SITES` are sorted as well.
+
[[porting-master-sites-n-group-semantics]]
. Group semantics can be used in any of the variables `MASTER_SITES`, `PATCH_SITES`, `MASTER_SITE_SUBDIR`, `PATCH_SITE_SUBDIR`, `DISTFILES`, and `PATCHFILES` according to this syntax:
.. All `MASTER_SITES`, `PATCH_SITES`, `MASTER_SITE_SUBDIR` and `PATCH_SITE_SUBDIR` elements must be terminated with the forward slash `/` character. If any elements belong to any groups, the group postfix `:__n__` must come right after the terminator `/`. The `MASTER_SITES:n` mechanism relies on the existence of the terminator `/` to avoid confusing elements where a `:n` is a valid part of the element with occurrences where `:n` denotes group `n`. For compatibility purposes, since the `/` terminator was not required before in both `MASTER_SITE_SUBDIR` and `PATCH_SITE_SUBDIR` elements, if the postfix immediate preceding character is not a `/` then `:n` will be considered a valid part of the element instead of a group postfix even if an element is postfixed with `:n`. See both <<ports-master-sites-n-example-detailed-use-master-site-subdir>> and <<ports-master-sites-n-example-detailed-use-complete-example-master-sites>>.
+
[[ports-master-sites-n-example-detailed-use-master-site-subdir]]
.Detailed Use of `MASTER_SITES:n` in `MASTER_SITE_SUBDIR`
[example]
====

[.programlisting]
....
MASTER_SITE_SUBDIR=	old:n new/:NEW
....

*** Directories within group `DEFAULT` -> old:n
*** Directories within group `NEW` -> new

====
+
[[ports-master-sites-n-example-detailed-use-complete-example-master-sites]]
.Detailed Use of `MASTER_SITES:n` with Comma Operator, Multiple Files, Multiple Sites and Multiple Subdirectories
[example]
====

[.programlisting]
....
MASTER_SITES=	http://site1/%SUBDIR%/ http://site2/:DEFAULT \
		http://site3/:group3 http://site4/:group4 \
		http://site5/:group5 http://site6/:group6 \
		http://site7/:DEFAULT,group6 \
		http://site8/%SUBDIR%/:group6,group7 \
		http://site9/:group8
DISTFILES=	file1 file2:DEFAULT file3:group3 \
		file4:group4,group5,group6 file5:grouping \
		file6:group7
MASTER_SITE_SUBDIR=	directory-trial:1 directory-n/:groupn \
		directory-one/:group6,DEFAULT \
		directory
....

The previous example results in this fine grained fetching. Sites are listed in the exact order they will be used.

*** [.filename]#file1# will be fetched from

**** `MASTER_SITE_OVERRIDE`
**** http://site1/directory-trial:1/
**** http://site1/directory-one/
**** http://site1/directory/
**** http://site2/
**** http://site7/
**** `MASTER_SITE_BACKUP`

*** [.filename]#file2# will be fetched exactly as [.filename]#file1# since they both belong to the same group

**** `MASTER_SITE_OVERRIDE`
**** http://site1/directory-trial:1/
**** http://site1/directory-one/
**** http://site1/directory/
**** http://site2/
**** http://site7/
**** `MASTER_SITE_BACKUP`

*** [.filename]#file3# will be fetched from

**** `MASTER_SITE_OVERRIDE`
**** http://site3/
**** `MASTER_SITE_BACKUP`

*** [.filename]#file4# will be fetched from

**** `MASTER_SITE_OVERRIDE`
**** http://site4/
**** http://site5/
**** http://site6/
**** http://site7/
**** http://site8/directory-one/
**** `MASTER_SITE_BACKUP`

*** [.filename]#file5# will be fetched from

**** `MASTER_SITE_OVERRIDE`
**** `MASTER_SITE_BACKUP`

*** [.filename]#file6# will be fetched from

**** `MASTER_SITE_OVERRIDE`
**** http://site8/
**** `MASTER_SITE_BACKUP`

====

. How do I group one of the special macros from [.filename]#bsd.sites.mk#, for example, SourceForge (`SF`)?
+ 
This has been simplified as much as possible. See <<ports-master-sites-n-example-detailed-use-master-site-sourceforge>>.
+
[[ports-master-sites-n-example-detailed-use-master-site-sourceforge]]
.Detailed Use of `MASTER_SITES:n` with SourceForge (`SF`)
[example]
====

[.programlisting]
....
MASTER_SITES=	http://site1/ SF/something/1.0:sourceforge,TEST
DISTFILES=	something.tar.gz:sourceforge
....

[.filename]#something.tar.gz# will be fetched from all sites within SourceForge.
====
. How do I use this with `PATCH*`?
+ 
All examples were done with `MASTER*` but they work exactly the same for `PATCH*` ones as can be seen in <<ports-master-sites-n-example-detailed-use-patch-sites>>.
+
[[ports-master-sites-n-example-detailed-use-patch-sites]]
.Simplified Use of `MASTER_SITES:n` with `PATCH_SITES`
[example]
====

[.programlisting]
....
PATCH_SITES=	http://site1/ http://site2/:test
PATCHFILES=	patch1:test
....

====

[[port-master-sites-n-what-changed]]
==== What Does Change for Ports? What Does Not?

[lowerroman]
. All current ports remain the same. The `MASTER_SITES:n` feature code is only activated if there are elements postfixed with `:__n__` like elements according to the aforementioned syntax rules, especially as shown in item <<porting-master-sites-n-group-semantics, 7>>.
+
[[porting-master-sites-n-what-changes-in-port-targets]]
. The port targets remain the same: `checksum`, `makesum`, `patch`, `configure`, `build`, etc. With the obvious exceptions of `do-fetch`, `fetch-list`, `master-sites` and `patch-sites`.

** `do-fetch`: deploys the new grouping postfixed `DISTFILES` and `PATCHFILES` with their matching group elements within both `MASTER_SITES` and `PATCH_SITES` which use matching group elements within both `MASTER_SITE_SUBDIR` and `PATCH_SITE_SUBDIR`. Check <<ports-master-sites-n-example-detailed-use-complete-example-master-sites>>.
** `fetch-list`: works like old `fetch-list` with the exception that it groups just like `do-fetch`.
** `master-sites` and `patch-sites`: (incompatible with older versions) only return the elements of group `DEFAULT`; in fact, they execute targets `master-sites-default` and `patch-sites-default` respectively.
+ 
Furthermore, using target either `master-sites-all` or `patch-sites-all` is preferred to directly checking either `MASTER_SITES` or `PATCH_SITES`. Also, directly checking is not guaranteed to work in any future versions. Check item <<porting-master-sites-n-new-port-targets-master-sites-all, B>> for more information on these new port targets.

. New port targets
.. There are `master-sites-_n_` and `patch-sites-_n_` targets which will list the elements of the respective group _n_ within `MASTER_SITES` and `PATCH_SITES` respectively. For instance, both `master-sites-DEFAULT` and `patch-sites-DEFAULT` will return the elements of group `DEFAULT`, `master-sites-test` and `patch-sites-test` of group `test`, and thereon.
+
[[porting-master-sites-n-new-port-targets-master-sites-all]]
.. There are new targets `master-sites-all` and `patch-sites-all` which do the work of the old `master-sites` and `patch-sites` ones. They return the elements of all groups as if they all belonged to the same group with the caveat that it lists as many `MASTER_SITE_BACKUP` and `MASTER_SITE_OVERRIDE` as there are groups defined within either `DISTFILES` or `PATCHFILES`; respectively for `master-sites-all` and `patch-sites-all`.

[[makefile-dist_subdir]]
=== `DIST_SUBDIR`

Do not let the port clutter [.filename]#/usr/ports/distfiles#. If the port requires a lot of files to be fetched, or contains a file that has a name that might conflict with other ports (for example, [.filename]#Makefile#), set `DIST_SUBDIR` to the name of the port (`${PORTNAME}` or `${PKGNAMEPREFIX}${PORTNAME}` are fine). This will change `DISTDIR` from the default [.filename]#/usr/ports/distfiles# to [.filename]#/usr/ports/distfiles/${DIST_SUBDIR}#, and in effect puts everything that is required for the port into that subdirectory.

It will also look at the subdirectory with the same name on the backup master site at http://distcache.FreeBSD.org[http://distcache.FreeBSD.org] (Setting `DISTDIR` explicitly in [.filename]#Makefile# will not accomplish this, so please use `DIST_SUBDIR`.)

[NOTE]
====
This does not affect `MASTER_SITES` defined in the [.filename]#Makefile#.
====

[[makefile-maintainer]]
== `MAINTAINER`

Set your mail-address here. Please. _:-)_

Only a single address without the comment part is allowed as a `MAINTAINER` value. The format used is `user@hostname.domain`. Please do not include any descriptive text such as a real name in this entry. That merely confuses the Ports infrastructure and most tools using it.

The maintainer is responsible for keeping the port up to date and making sure that it works correctly. For a detailed description of the responsibilities of a port maintainer, refer to link:{contributing}#maintain-port[The challenge for port maintainers].

[NOTE]
====
A maintainer volunteers to keep a port in good working order. Maintainers have the primary responsibility for their ports, but not exclusive ownership. Ports exist for the benefit of the community and, in reality, belong to the community. What this means is that people other than the maintainer can make changes to a port. Large changes to the Ports Collection might require changes to many ports. The FreeBSD Ports Management Team or members of other teams might modify ports to fix dependency issues or other problems, like a version bump for a shared library update.

Some types of fixes have "blanket approval" from the {portmgr}, allowing any committer to fix those categories of problems on any port. These fixes do not need approval from the maintainer.

Blanket approval for most ports applies to fixes like infrastructure changes, or trivial and _tested_ build and runtime fixes. The current list is available in link:{committers-guide}#ports-qa-misc-blanket-approval[Ports section of the Committer's Guide].
====

Other changes to the port will be sent to the maintainer for review and approval before being committed. If the maintainer does not respond to an update request after two weeks (excluding major public holidays), then that is considered a maintainer timeout, and the update can be made without explicit maintainer approval. If the maintainer does not respond within three months, or if there have been three consecutive timeouts, then that maintainer is considered absent without leave, and all of their ports can be assigned back to the pool. Exceptions to this are anything maintained by the {portmgr}, or the {security-officer}. No unauthorized commits may ever be made to ports maintained by those groups.

We reserve the right to modify the maintainer's submission to better match existing policies and style of the Ports Collection without explicit blessing from the submitter or the maintainer. Also, large infrastructural changes can result in a port being modified without the maintainer's consent. These kinds of changes will never affect the port's functionality.

The {portmgr} reserves the right to revoke or override anyone's maintainership for any reason, and the {security-officer} reserves the right to revoke or override maintainership for security reasons.

[[makefile-comment]]
== `COMMENT`

The comment is a one-line description of a port shown by `pkg info`. Please follow these rules when composing it:

. The COMMENT string should be 70 characters or less.
. Do _not_ include the package name or version number of software.
. The comment must begin with a capital and end without a period.
. Do not start with an indefinite article (that is, A or An).
. Capitalize names such as Apache, JavaScript, or Perl.
. Use a serial comma for lists of words: "green, red, and blue."
. Check for spelling errors.

Here is an example:

[.programlisting]
....
COMMENT=	Cat chasing a mouse all over the screen
....

The COMMENT variable immediately follows the MAINTAINER variable in the [.filename]#Makefile#.

[[licenses]]
== Licenses

Each port must document the license under which it is available. If it is not an OSI approved license it must also document any restrictions on redistribution.

[[licenses-license]]
=== `LICENSE`

A short name for the license or licenses if more than one license apply.

If it is one of the licenses listed in <<licenses-license-list>>, only `LICENSE_FILE` and `LICENSE_DISTFILES` variables can be set.

If this is a license that has not been defined in the ports framework (see <<licenses-license-list>>), the `LICENSE_PERMS` and `LICENSE_NAME` must be set, along with either `LICENSE_FILE` or `LICENSE_TEXT`. `LICENSE_DISTFILES` and `LICENSE_GROUPS` can also be set, but are not required.

The predefined licenses are shown in <<licenses-license-list>>. The current list is always available in [.filename]#Mk/bsd.licenses.db.mk#.

[[licenses-license-ex1]]
.Simplest Usage, Predefined Licenses
[example]
====

When the [.filename]#README# of some software says "This software is under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version." but does not provide the license file, use this:

[.programlisting]
....
LICENSE=	LGPL21+
....

When the software provides the license file, use this:

[.programlisting]
....
LICENSE=	LGPL21+
LICENSE_FILE=	${WRKSRC}/COPYING
....

====

For the predefined licenses, the default permissions are `dist-mirror dist-sell pkg-mirror pkg-sell auto-accept`.

[[licenses-license-list]]
.Predefined License List
[cols="1,1,1,1", frame="none", options="header"]
|===
| Short Name
| Name
| Group
| Permissions

|`AGPLv3`
|GNU Affero General Public License version 3
|`FSF GPL OSI`
|(default)

|`AGPLv3+`
|GNU Affero General Public License version 3 (or later)
|`FSF GPL OSI`
|(default)

|`APACHE10`
|Apache License 1.0
|`FSF`
|(default)

|`APACHE11`
|Apache License 1.1
|`FSF OSI`
|(default)

|`APACHE20`
|Apache License 2.0
|`FSF OSI`
|(default)

|`ART10`
|Artistic License version 1.0
|`OSI`
|(default)

|`ART20`
|Artistic License version 2.0
|`FSF GPL OSI`
|(default)

|`ARTPERL10`
|Artistic License (perl) version 1.0
|`OSI`
|(default)

|`BSD`
|BSD license Generic Version (deprecated)
|`FSF OSI COPYFREE`
|(default)

|`BSD2CLAUSE`
|BSD 2-clause "Simplified" License
|`FSF OSI COPYFREE`
|(default)

|`BSD3CLAUSE`
|BSD 3-clause "New" or "Revised" License
|`FSF OSI COPYFREE`
|(default)

|`BSD4CLAUSE`
|BSD 4-clause "Original" or "Old" License
|`FSF`
|(default)

|`BSL`
|Boost Software License
|`FSF OSI COPYFREE`
|(default)

|`CC-BY-1.0`
|Creative Commons Attribution 1.0
|
|(default)

|`CC-BY-2.0`
|Creative Commons Attribution 2.0
|
|(default)

|`CC-BY-2.5`
|Creative Commons Attribution 2.5
|
|(default)

|`CC-BY-3.0`
|Creative Commons Attribution 3.0
|
|(default)

|`CC-BY-4.0`
|Creative Commons Attribution 4.0
|
|(default)

|`CC-BY-NC-1.0`
|Creative Commons Attribution Non Commercial 1.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-2.0`
|Creative Commons Attribution Non Commercial 2.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-2.5`
|Creative Commons Attribution Non Commercial 2.5
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-3.0`
|Creative Commons Attribution Non Commercial 3.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-4.0`
|Creative Commons Attribution Non Commercial 4.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-ND-1.0`
|Creative Commons Attribution Non Commercial No Derivatives 1.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-ND-2.0`
|Creative Commons Attribution Non Commercial No Derivatives 2.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-ND-2.5`
|Creative Commons Attribution Non Commercial No Derivatives 2.5
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-ND-3.0`
|Creative Commons Attribution Non Commercial No Derivatives 3.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-ND-4.0`
|Creative Commons Attribution Non Commercial No Derivatives 4.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-SA-1.0`
|Creative Commons Attribution Non Commercial Share Alike 1.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-SA-2.0`
|Creative Commons Attribution Non Commercial Share Alike 2.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-SA-2.5`
|Creative Commons Attribution Non Commercial Share Alike 2.5
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-SA-3.0`
|Creative Commons Attribution Non Commercial Share Alike 3.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-NC-SA-4.0`
|Creative Commons Attribution Non Commercial Share Alike 4.0
|
|`dist-mirror``pkg-mirror``auto-accept`

|`CC-BY-ND-1.0`
|Creative Commons Attribution No Derivatives 1.0
|
|(default)

|`CC-BY-ND-2.0`
|Creative Commons Attribution No Derivatives 2.0
|
|(default)

|`CC-BY-ND-2.5`
|Creative Commons Attribution No Derivatives 2.5
|
|(default)

|`CC-BY-ND-3.0`
|Creative Commons Attribution No Derivatives 3.0
|
|(default)

|`CC-BY-ND-4.0`
|Creative Commons Attribution No Derivatives 4.0
|
|(default)

|`CC-BY-SA-1.0`
|Creative Commons Attribution Share Alike 1.0
|
|(default)

|`CC-BY-SA-2.0`
|Creative Commons Attribution Share Alike 2.0
|
|(default)

|`CC-BY-SA-2.5`
|Creative Commons Attribution Share Alike 2.5
|
|(default)

|`CC-BY-SA-3.0`
|Creative Commons Attribution Share Alike 3.0
|
|(default)

|`CC-BY-SA-4.0`
|Creative Commons Attribution Share Alike 4.0
|
|(default)

|`CC0-1.0`
|Creative Commons Zero v1.0 Universal
|`FSF GPL COPYFREE`
|(default)

|`CDDL`
|Common Development and Distribution License
|`FSF OSI`
|(default)

|`CPAL-1.0`
|Common Public Attribution License
|`FSF OSI`
|(default)

|`ClArtistic`
|Clarified Artistic License
|`FSF GPL OSI`
|(default)

|`EPL`
|Eclipse Public License
|`FSF OSI`
|(default)

|`GFDL`
|GNU Free Documentation License
|`FSF`
|(default)

|`GMGPL`
|GNAT Modified General Public License
|`FSF GPL OSI`
|(default)

|`GPLv1`
|GNU General Public License version 1
|`FSF GPL OSI`
|(default)

|`GPLv1+`
|GNU General Public License version 1 (or later)
|`FSF GPL OSI`
|(default)

|`GPLv2`
|GNU General Public License version 2
|`FSF GPL OSI`
|(default)

|`GPLv2+`
|GNU General Public License version 2 (or later)
|`FSF GPL OSI`
|(default)

|`GPLv3`
|GNU General Public License version 3
|`FSF GPL OSI`
|(default)

|`GPLv3+`
|GNU General Public License version 3 (or later)
|`FSF GPL OSI`
|(default)

|`GPLv3RLE`
|GNU GPL version 3 Runtime Library Exception
|`FSF GPL OSI`
|(default)

|`GPLv3RLE+`
|GNU GPL version 3 Runtime Library Exception (or later)
|`FSF GPL OSI`
|(default)

|`ISCL`
|Internet Systems Consortium License
|`FSF GPL OSI COPYFREE`
|(default)

|`LGPL20`
|GNU Library General Public License version 2.0
|`FSF GPL OSI`
|(default)

|`LGPL20+`
|GNU Library General Public License version 2.0 (or later)
|`FSF GPL OSI`
|(default)

|`LGPL21`
|GNU Lesser General Public License version 2.1
|`FSF GPL OSI`
|(default)

|`LGPL21+`
|GNU Lesser General Public License version 2.1 (or later)
|`FSF GPL OSI`
|(default)

|`LGPL3`
|GNU Lesser General Public License version 3
|`FSF GPL OSI`
|(default)

|`LGPL3+`
|GNU Lesser General Public License version 3 (or later)
|`FSF GPL OSI`
|(default)

|`LPPL10`
|LaTeX Project Public License version 1.0
|`FSF OSI`
|`dist-mirror dist-sell`

|`LPPL11`
|LaTeX Project Public License version 1.1
|`FSF OSI`
|`dist-mirror dist-sell`

|`LPPL12`
|LaTeX Project Public License version 1.2
|`FSF OSI`
|`dist-mirror dist-sell`

|`LPPL13`
|LaTeX Project Public License version 1.3
|`FSF OSI`
|`dist-mirror dist-sell`

|`LPPL13a`
|LaTeX Project Public License version 1.3a
|`FSF OSI`
|`dist-mirror dist-sell`

|`LPPL13b`
|LaTeX Project Public License version 1.3b
|`FSF OSI`
|`dist-mirror dist-sell`

|`LPPL13c`
|LaTeX Project Public License version 1.3c
|`FSF OSI`
|`dist-mirror dist-sell`

|`MIT`
|MIT license / X11 license
|`COPYFREE FSF GPL OSI`
|(default)

|`MPL10`
|Mozilla Public License version 1.0
|`FSF OSI`
|(default)

|`MPL11`
|Mozilla Public License version 1.1
|`FSF OSI`
|(default)

|`MPL20`
|Mozilla Public License version 2.0
|`FSF OSI`
|(default)

|`NCSA`
|University of Illinois/NCSA Open Source License
|`COPYFREE FSF GPL OSI`
|(default)

|`NONE`
|No license specified
|
|`none`

|`OFL10`
|SIL Open Font License version 1.0 (http://scripts.sil.org/OFL)
|`FONTS`
|(default)

|`OFL11`
|SIL Open Font License version 1.1 (http://scripts.sil.org/OFL)
|`FONTS`
|(default)

|`OWL`
|Open Works License (owl.apotheon.org)
|`COPYFREE`
|(default)

|`OpenSSL`
|OpenSSL License
|`FSF`
|(default)

|`PD`
|Public Domain
|`GPL COPYFREE`
|(default)

|`PHP202`
|PHP License version 2.02
|`FSF OSI`
|(default)

|`PHP30`
|PHP License version 3.0
|`FSF OSI`
|(default)

|`PHP301`
|PHP License version 3.01
|`FSF OSI`
|(default)

|`PSFL`
|Python Software Foundation License
|`FSF GPL OSI`
|(default)

|`PostgreSQL`
|PostgreSQL Licence
|`FSF GPL OSI COPYFREE`
|(default)

|`RUBY`
|Ruby License
|`FSF`
|(default)

|`UNLICENSE`
|The Unlicense
|`COPYFREE FSF GPL`
|(default)

|`WTFPL`
|Do What the Fuck You Want To Public License version 2
|`GPL FSF COPYFREE`
|(default)

|`WTFPL1`
|Do What the Fuck You Want To Public License version 1
|`GPL FSF COPYFREE`
|(default)

|`ZLIB`
|zlib License
|`GPL FSF OSI`
|(default)

|`ZPL21`
|Zope Public License version 2.1
|`GPL OSI`
|(default)
|===

[[licenses-license_perms]]
=== `LICENSE_PERMS` and `LICENSE_PERMS_NAME_`

Permissions. use `none` if empty.

.License Permissions List
[[licenses-license_perms-dist-mirror]]
`dist-mirror`::
Redistribution of the distribution files is permitted. The distribution files will be added to the FreeBSD `MASTER_SITE_BACKUP` CDN.

[[licenses-license_perms-no-dist-mirror]]
`no-dist-mirror`::
Redistribution of the distribution files is prohibited. This is equivalent to setting <<porting-restrictions-restricted,`RESTRICTED`>>. The distribution files will _not_ be added to the FreeBSD `MASTER_SITE_BACKUP` CDN.

[[licenses-license_perms-dist-sell]]
`dist-sell`::
Selling of distribution files is permitted. The distribution files will be present on the installer images.

[[licenses-license_perms-no-dist-sell]]
`no-dist-sell`::
Selling of distribution files is prohibited. This is equivalent to setting <<porting-restrictions-no_cdrom,`NO_CDROM`>>.

[[licenses-license_perms-pkg-mirror]]
`pkg-mirror`::
Free redistribution of package is permitted. The package will be distributed on the FreeBSD package CDN https://pkg.freebsd.org/[https://pkg.freebsd.org/].

[[licenses-license_perms-no-pkg-mirror]]
`no-pkg-mirror`::
Free redistribution of package is prohibited. Equivalent to setting <<porting-restrictions-no_package,`NO_PACKAGE`>>. The package will _not_ be distributed from the FreeBSD package CDN https://pkg.freebsd.org/[https://pkg.freebsd.org/].

[[licenses-license_perms-pkg-sell]]
`pkg-sell`::
Selling of package is permitted. The package will be present on the installer images.

[[licenses-license_perms-no-pkg-sell]]
`no-pkg-sell`::
Selling of package is prohibited. This is equivalent to setting <<porting-restrictions-no_cdrom,`NO_CDROM`>>. The package will _not_ be present on the installer images.

[[licenses-license_perms-auto-accept]]
`auto-accept`::
License is accepted by default. Prompts to accept a license are not displayed unless the user has defined `LICENSES_ASK`. Use this unless the license states the user must accept the terms of the license.

[[licenses-license_perms-no-auto-accept]]
`no-auto-accept`::
License is not accepted by default. The user will always be asked to confirm the acceptance of this license. This must be used if the license states that the user must accept its terms.

When both `_permission_` and `no-_permission_` is present the `no-_permission_` will cancel `_permission_`.

When `_permission_` is not present, it is considered to be a `no-_permission_`.

[WARNING]
====

Some missing permissions will prevent a port (and all ports depending on it) from being usable by package users:

A port without the `auto-accept` permission will never be be built and all the ports depending on it will be ignored.

A port without the `pkg-mirror` permission will be removed, as well as all the ports depending on it, after the build and they will ever end up being distributed.
====

[[licenses-license_perms-ex1]]
.Nonstandard License
[example]
====
Read the terms of the license and translate those using the available permissions.

[.programlisting]
....
LICENSE=        UNKNOWN
LICENSE_NAME=   unknown
LICENSE_TEXT=   This program is NOT in public domain.\
                It can be freely distributed for non-commercial purposes only.
LICENSE_PERMS=  dist-mirror no-dist-sell pkg-mirror no-pkg-sell auto-accept
....

====

[[licenses-license_perms-ex2]]
.Standard and Nonstandard Licenses
[example]
====

Read the terms of the license and express those using the available permissions. In case of doubt, please ask for guidance on the {freebsd-ports}.

[.programlisting]
....
LICENSE=        WARSOW GPLv2
LICENSE_COMB=   multi
LICENSE_NAME_WARSOW=    Warsow Content License
LICENSE_FILE_WARSOW=    ${WRKSRC}/docs/license.txt
LICENSE_PERMS_WARSOW=   dist-mirror pkg-mirror auto-accept
....

When the permissions of the GPLv2 and the UNKNOWN licenses are mixed, the port ends up with `dist-mirror dist-sell pkg-mirror pkg-sell auto-accept dist-mirror no-dist-sell pkg-mirror no-pkg-sell auto-accept`. The `no-_permissions_` cancel the _permissions_. The resulting list of permissions are _dist-mirror pkg-mirror auto-accept_. The distribution files and the packages will not be available on the installer images.
====

[[licenses-license_groups]]
=== `LICENSE_GROUPS` and `LICENSE_GROUPS_NAME`

Groups the license belongs.

.Predefined License Groups List
[[licenses-license_groups-FSF]]
`FSF`::
Free Software Foundation Approved, see the http://www.fsf.org/licensing[FSF Licensing & Compliance Team].

[[licenses-license_groups-GPL]]
`GPL`::
GPL Compatible

[[licenses-license_groups-OSI]]
`OSI`::
OSI Approved, see the Open Source Initiative http://opensource.org/licenses[Open Source Licenses] page.

[[licenses-license_groups-COPYFREE]]
`COPYFREE`::
Comply with Copyfree Standard Definition, see the http://copyfree.org/standard/licenses[Copyfree Licenses] page.

[[licenses-license_groups-FONTS]]
`FONTS`::
Font licenses

[[licenses-license_name]]
=== `LICENSE_NAME` and `LICENSE_NAME_NAME`

Full name of the license.

[[licenses-license_name-ex1]]
.`LICENSE_NAME`
[example]
====

[.programlisting]
....
LICENSE=        UNRAR
LICENSE_NAME=   UnRAR License
LICENSE_FILE=   ${WRKSRC}/license.txt
LICENSE_PERMS=  dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
....

====

[[licenses-license_file]]
=== `LICENSE_FILE` and `LICENSE_FILE_NAME`

Full path to the file containing the license text, usually [.filename]#${WRKSRC}/some/file#. If the file is not in the distfile, and its content is too long to be put in <<licenses-license_text,`LICENSE_TEXT`>>, put it in a new file in [.filename]#${FILESDIR}#.

[[licenses-license_file-ex1]]
.`LICENSE_FILE`
[example]
====

[.programlisting]
....
LICENSE=	GPLv3+
LICENSE_FILE=	${WRKSRC}/COPYING
....

====

[[licenses-license_text]]
=== `LICENSE_TEXT` and `LICENSE_TEXT_NAME`

Text to use as a license. Useful when the license is not in the distribution files and its text is short.

[[licenses-license_text-ex1]]
.`LICENSE_TEXT`
[example]
====
[.programlisting]
....
LICENSE=        UNKNOWN
LICENSE_NAME=   unknown
LICENSE_TEXT=   This program is NOT in public domain.\
                It can be freely distributed for non-commercial purposes only,\
                and THERE IS NO WARRANTY FOR THIS PROGRAM.
LICENSE_PERMS=  dist-mirror no-dist-sell pkg-mirror no-pkg-sell auto-accept
....

====

[[licenses-license_distfiles]]
=== `LICENSE_DISTFILES` and `LICENSE_DISTFILES_NAME`

The distribution files to which the licenses apply. Defaults to all the distribution files.

[[licenses-license_distfiles-ex1]]
.`LICENSE_DISTFILES`
[example]
====
Used when the distribution files do not all have the same license. For example, one has a code license, and another has some artwork that cannot be redistributed:

[.programlisting]
....
MASTER_SITES=   SF/some-game
DISTFILES=      ${DISTNAME}${EXTRACT_SUFX} artwork.zip

LICENSE=        BSD3CLAUSE ARTWORK
LICENSE_COMB=   dual
LICENSE_NAME_ARTWORK=      The game artwork license
LICENSE_TEXT_ARTWORK=      The README says that the files cannot be redistributed
LICENSE_PERMS_ARTWORK=     pkg-mirror pkg-sell auto-accept
LICENSE_DISTFILES_BSD3CLAUSE=   ${DISTNAME}${EXTRACT_SUFX}
LICENSE_DISTFILES_ARTWORK= artwork.zip
....

====

[[licenses-license_comb]]
=== `LICENSE_COMB`

Set to `multi` if all licenses apply. Set to `dual` if any license applies. Defaults to `single`.

[[licenses-license_comb-ex1]]
.Dual Licenses
[example]
====

When a port says "This software may be distributed under the GNU General Public License or the Artistic License", it means that either license can be used. Use this:

[.programlisting]
....
LICENSE=	ART10 GPLv1
LICENSE_COMB=   dual
....

If license files are provided, use this:

[.programlisting]
....
LICENSE=	ART10 GPLv1
LICENSE_COMB=   dual
LICENSE_FILE_ART10=     ${WRKSRC}/Artistic
LICENSE_FILE_GPLv1=     ${WRKSRC}/Copying
....

====

[[licenses-license_comb-ex2]]
.Multiple Licenses
[example]
====

When part of a port has one license, and another part has a different license, use `multi`:

[.programlisting]
....
LICENSE=	GPLv2 LGPL21+
LICENSE_COMB=	multi
....

====

[[makefile-portscout]]
== `PORTSCOUT`

Portscout is an automated distfile check utility for the FreeBSD Ports Collection, described in detail in <<distfile-survey>>.

`PORTSCOUT` defines special conditions within which the Portscout distfile scanner is restricted.

Situations where `PORTSCOUT` is set include:

* When distfiles have to be ignored, whether for specific versions, or specific minor revisions. For example, to exclude version _8.2_ from distfile version checks because it is known to be broken, add:
+
[.programlisting]
....
PORTSCOUT=	ignore:8.2
....

* When specific versions or specific major and minor revisions of a distfile must be checked. For example, if only version _0.6.4_ must be monitored because newer versions have compatibility issues with FreeBSD, add:
+
[.programlisting]
....
PORTSCOUT=	limit:^0\.6\.4
....

* When URLs listing the available versions differ from the download URLs. For example, to limit distfile version checks to the download page for the package:databases/pgtune[] port, add:
+
[.programlisting]
....
PORTSCOUT=	site:http://pgfoundry.org/frs/?group_id=1000416
....

[[makefile-depend]]
== Dependencies

Many ports depend on other ports. This is a very convenient feature of most Unix-like operating systems, including FreeBSD. Multiple ports can share a common dependency, rather than bundling that dependency with every port or package that needs it. There are seven variables that can be used to ensure that all the required bits will be on the user's machine. There are also some pre-supported dependency variables for common cases, plus a few more to control the behavior of dependencies.

[IMPORTANT]
====
When software has extra dependencies that provide extra features, the base dependencies listed in `*_DEPENDS` should include the extra dependencies that would benefit most users. The base dependencies should never be a "minimal" dependency set. The goal is not to include every dependency possible. Only include those that will benefit most people.
====

[[makefile-lib_depends]]
=== `LIB_DEPENDS`

This variable specifies the shared libraries this port depends on. It is a list of `_lib:dir_` tuples where `_lib_` is the name of the shared library, `_dir_` is the directory in which to find it in case it is not available. For example,

[.programlisting]
....
LIB_DEPENDS=   libjpeg.so:graphics/jpeg
....

will check for a shared jpeg library with any version, and descend into the [.filename]#graphics/jpeg# subdirectory of the ports tree to build and install it if it is not found.

The dependency is checked twice, once from within the `build` target and then from within the `install` target. Also, the name of the dependency is put into the package so that `pkg install` (see man:pkg-install[8]) will automatically install it if it is not on the user's system.

[[makefile-run_depends]]
=== `RUN_DEPENDS`

This variable specifies executables or files this port depends on during run-time. It is a list of ``_path:dir_``[:``_target_``] tuples where `_path_` is the name of the executable or file, _dir_ is the directory in which to find it in case it is not available, and _target_ is the target to call in that directory. If _path_ starts with a slash (`/`), it is treated as a file and its existence is tested with `test -e`; otherwise, it is assumed to be an executable, and `which -s` is used to determine if the program exists in the search path.

For example,

[.programlisting]
....
RUN_DEPENDS=	${LOCALBASE}/news/bin/innd:news/inn \
		xmlcatmgr:textproc/xmlcatmgr
....

will check if the file or directory [.filename]#/usr/local/news/bin/innd# exists, and build and install it from the [.filename]#news/inn# subdirectory of the ports tree if it is not found. It will also see if an executable called `xmlcatmgr` is in the search path, and descend into [.filename]#textproc/xmlcatmgr# to build and install it if it is not found.

[NOTE]
====
In this case, `innd` is actually an executable; if an executable is in a place that is not expected to be in the search path, use the full pathname.
====

[NOTE]
====
The official search `PATH` used on the ports build cluster is

[.programlisting]
....
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
....

====

The dependency is checked from within the `install` target. Also, the name of the dependency is put into the package so that `pkg install` (see man:pkg-install[8]) will automatically install it if it is not on the user's system. The _target_ part can be omitted if it is the same as `DEPENDS_TARGET`.

A quite common situation is when `RUN_DEPENDS` is literally the same as `BUILD_DEPENDS`, especially if ported software is written in a scripted language or if it requires the same build and run-time environment. In this case, it is both tempting and intuitive to directly assign one to the other:

[.programlisting]
....
RUN_DEPENDS=	${BUILD_DEPENDS}
....

However, such assignment can pollute run-time dependencies with entries not defined in the port's original `BUILD_DEPENDS`. This happens because of man:make[1]'s lazy evaluation of variable assignment. Consider a [.filename]#Makefile# with `USE_*`, which are processed by [.filename]#ports/Mk/bsd.*.mk# to augment initial build dependencies. For example, `USES= gmake` adds package:devel/gmake[] to `BUILD_DEPENDS`. To prevent such additional dependencies from polluting `RUN_DEPENDS`, create another variable with the current content of `BUILD_DEPENDS` and assign it to both `BUILD_DEPENDS` and `RUN_DEPENDS`:

[.programlisting]
....
MY_DEPENDS=	some:devel/some \
		other:lang/other
BUILD_DEPENDS=	${MY_DEPENDS}
RUN_DEPENDS=	${MY_DEPENDS}
....

[IMPORTANT]
====
_Do not_ use `:=` to assign `BUILD_DEPENDS` to `RUN_DEPENDS` or vice-versa. All variables are expanded immediately, which is exactly the wrong thing to do and almost always a failure.
====

[[makefile-build_depends]]
=== `BUILD_DEPENDS`

This variable specifies executables or files this port requires to build. Like `RUN_DEPENDS`, it is a list of ``_path:dir_``[:``_target_``] tuples. For example,

[.programlisting]
....
BUILD_DEPENDS=	unzip:archivers/unzip
....

will check for an executable called `unzip`, and descend into the [.filename]#archivers/unzip# subdirectory of the ports tree to build and install it if it is not found.

[NOTE]
====
"build" here means everything from extraction to compilation. The dependency is checked from within the `extract` target. The _target_ part can be omitted if it is the same as `DEPENDS_TARGET`
====

[[makefile-fetch_depends]]
=== `FETCH_DEPENDS`

This variable specifies executables or files this port requires to fetch. Like the previous two, it is a list of ``_path:dir_``[:``_target_``] tuples. For example,

[.programlisting]
....
FETCH_DEPENDS=	ncftp2:net/ncftp2
....

will check for an executable called `ncftp2`, and descend into the [.filename]#net/ncftp2# subdirectory of the ports tree to build and install it if it is not found.

The dependency is checked from within the `fetch` target. The _target_ part can be omitted if it is the same as `DEPENDS_TARGET`.

[[makefile-extract_depends]]
=== `EXTRACT_DEPENDS`

This variable specifies executables or files this port requires for extraction. Like the previous, it is a list of ``_path:dir_``[:``_target_``] tuples. For example,

[.programlisting]
....
EXTRACT_DEPENDS=	unzip:archivers/unzip
....

will check for an executable called `unzip`, and descend into the [.filename]#archivers/unzip# subdirectory of the ports tree to build and install it if it is not found.

The dependency is checked from within the `extract` target. The _target_ part can be omitted if it is the same as `DEPENDS_TARGET`.

[NOTE]
====
Use this variable only if the extraction does not already work (the default assumes `tar`) and cannot be made to work using `USES=tar`, `USES=lha` or `USES=zip` described in <<uses>>.
====

[[makefile-patch_depends]]
=== `PATCH_DEPENDS`

This variable specifies executables or files this port requires to patch. Like the previous, it is a list of ``_path:dir_``[:``_target_``] tuples. For example,

[.programlisting]
....
PATCH_DEPENDS=	${NONEXISTENT}:java/jfc:extract
....

will descend into the [.filename]#java/jfc# subdirectory of the ports tree to extract it.

The dependency is checked from within the `patch` target. The _target_ part can be omitted if it is the same as `DEPENDS_TARGET`.

[[makefile-uses]]
=== `USES`

Parameters can be added to define different features and dependencies used by the port. They are specified by adding this line to the [.filename]#Makefile#:

[.programlisting]
....
USES= feature[:arguments]
....

For the complete list of values, please see <<uses>>.

[WARNING]
====

`USES` cannot be assigned after inclusion of [.filename]#bsd.port.pre.mk#.
====

[[makefile-use-vars]]
=== `USE_*`

Several variables exist to define common dependencies shared by many ports. Their use is optional, but helps to reduce the verbosity of the port [.filename]##Makefile##s. Each of them is styled as `USE_*`. These variables may be used only in the port [.filename]##Makefile##s and [.filename]#ports/Mk/bsd.*.mk#. They are not meant for user-settable options - use `PORT_OPTIONS` for that purpose.

[NOTE]
====
It is _always_ incorrect to set any `USE_*` in [.filename]#/etc/make.conf#. For instance, setting

[.programlisting]
....
USE_GCC=X.Y
....

(where X.Y is version number) would add a dependency on gccXY for every port, including `lang/gccXY` itself!
====

[[makefile-use-vars-table]]
.`USE_*`
[cols="1,1", frame="none", options="header"]
|===
| Variable
| Means

|`USE_GCC`
a|

The port requires GCC (`gcc` or `{g-plus-plus}`) to build. Some ports need any GCC version, some require modern, recent versions. It is typically set to `any` (in this case, GCC from base would be used on versions of FreeBSD that still have it, or `lang/gcc` port would be installed when default C/C++ compiler is Clang); or `yes` (means always use stable, modern GCC from `lang/gcc` port). The exact version can also be specified, with a value such as `4.7`. The minimal required version can be specified as `4.6+`. The GCC from the base system is used when it satisfies the requested version, otherwise an appropriate compiler is built from the port, and `CC` and `CXX` are adjusted accordingly.

[NOTE]
====
`USE_GCC` will register a build-time and a run-time dependency.
====

|===

Variables related to gmake and [.filename]#configure# are described in <<building>>, while autoconf, automake and libtool are described in <<using-autotools>>. Perl related variables are described in <<using-perl>>. X11 variables are listed in <<using-x11>>. <<using-gnome>> deals with GNOME and <<using-kde>> with KDE related variables. <<using-java>> documents Java variables, while <<using-php>> contains information on Apache, PHP and PEAR modules. Python is discussed in <<using-python>>, while Ruby in <<using-ruby>>. <<using-sdl>> provides variables used for SDL applications and finally, <<using-xfce>> contains information on Xfce.

[[makefile-version-dependency]]
=== Minimal Version of a Dependency

A minimal version of a dependency can be specified in any `*_DEPENDS` except `LIB_DEPENDS` using this syntax:

[.programlisting]
....
p5-Spiffy>=0.26:devel/p5-Spiffy
....

The first field contains a dependent package name, which must match the entry in the package database, a comparison sign, and a package version. The dependency is satisfied if p5-Spiffy-0.26 or newer is installed on the machine.

[[makefile-note-on-dependencies]]
=== Notes on Dependencies

As mentioned above, the default target to call when a dependency is required is `DEPENDS_TARGET`. It defaults to `install`. This is a user variable; it is never defined in a port's [.filename]#Makefile#. If the port needs a special way to handle a dependency, use the `:target` part of `*_DEPENDS` instead of redefining `DEPENDS_TARGET`.

When running `make clean`, the port dependencies are automatically cleaned too. If this is not desirable, define `NOCLEANDEPENDS` in the environment. This may be particularly desirable if the port has something that takes a long time to rebuild in its dependency list, such as KDE, GNOME or Mozilla.

To depend on another port unconditionally, use the variable `${NONEXISTENT}` as the first field of `BUILD_DEPENDS` or `RUN_DEPENDS`. Use this only when the source of the other port is needed. Compilation time can be saved by specifying the target too. For instance

[.programlisting]
....
BUILD_DEPENDS=	${NONEXISTENT}:graphics/jpeg:extract
....

will always descend to the `jpeg` port and extract it.

[[makefile-circular-dependencies]]
=== Circular Dependencies Are Fatal

[IMPORTANT]
====
Do not introduce any circular dependencies into the ports tree!
====

The ports building technology does not tolerate circular dependencies. If one is introduced, someone, somewhere in the world, will have their FreeBSD installation broken almost immediately, with many others quickly to follow. These can really be hard to detect. If in doubt, before making that change, make sure to run: `cd /usr/ports; make index`. That process can be quite slow on older machines, but it may be able to save a large number of people, including yourself, a lot of grief in the process.

[[makefile-automatic-dependencies]]
=== Problems Caused by Automatic Dependencies

Dependencies must be declared either explicitly or by using the <<makefile-options,OPTIONS framework>>. Using other methods like automatic detection complicates indexing, which causes problems for port and package management.

[[makefile-automatic-dependencies-bad]]
.Wrong Declaration of an Optional Dependency
[example]
====

[.programlisting]
....
.include <bsd.port.pre.mk>

.if exists(${LOCALBASE}/bin/foo)
LIB_DEPENDS=	libbar.so:foo/bar
.endif
....

====

The problem with trying to automatically add dependencies is that files and settings outside an individual port can change at any time. For example: an index is built, then a batch of ports are installed. But one of the ports installs the tested file. The index is now incorrect, because an installed port unexpectedly has a new dependency. The index may still be wrong even after rebuilding if other ports also determine their need for dependencies based on the existence of other files.

[[makefile-automatic-dependencies-good]]
.Correct Declaration of an Optional Dependency
[example]
====

[.programlisting]
....
OPTIONS_DEFINE=	BAR
BAR_DESC=	Calling cellphones via bar

BAR_LIB_DEPENDS=	libbar.so:foo/bar
....

====

Testing option variables is the correct method. It will not cause inconsistencies in the index of a batch of ports, provided the options were defined prior to the index build. Simple scripts can then be used to automate the building, installation, and updating of these ports and their packages.

[[makefile-masterdir]]
== Slave Ports and `MASTERDIR`

If the port needs to build slightly different versions of packages by having a variable (for instance, resolution, or paper size) take different values, create one subdirectory per package to make it easier for users to see what to do, but try to share as many files as possible between ports. Typically, by using variables cleverly, only a very short [.filename]#Makefile# is needed in all but one of the directories. In the sole [.filename]#Makefile#, use `MASTERDIR` to specify the directory where the rest of the files are. Also, use a variable as part of <<porting-pkgname,`PKGNAMESUFFIX`>> so the packages will have different names.

This will be best demonstrated by an example. This is part of [.filename]#print/pkfonts300/Makefile#;

[.programlisting]
....
PORTNAME=	pkfonts${RESOLUTION}
PORTVERSION=	1.0
DISTFILES=	pk${RESOLUTION}.tar.gz

PLIST=		${PKGDIR}/pkg-plist.${RESOLUTION}

.if !defined(RESOLUTION)
RESOLUTION=	300
.else
.if ${RESOLUTION} != 118 && ${RESOLUTION} != 240 && \
	${RESOLUTION} != 300 && ${RESOLUTION} != 360 && \
	${RESOLUTION} != 400 && ${RESOLUTION} != 600
.BEGIN:
	@${ECHO_MSG} "Error: invalid value for RESOLUTION: \"${RESOLUTION}\""
	@${ECHO_MSG} "Possible values are: 118, 240, 300, 360, 400 and 600."
	@${FALSE}
.endif
.endif
....

package:print/pkfonts300[] also has all the regular patches, package files, etc. Running `make` there, it will take the default value for the resolution (300) and build the port normally.

As for other resolutions, this is the _entire_ [.filename]#print/pkfonts360/Makefile#:

[.programlisting]
....
RESOLUTION=	360
MASTERDIR=	${.CURDIR}/../pkfonts300

.include	"${MASTERDIR}/Makefile"
....

([.filename]#print/pkfonts118/Makefile#, [.filename]#print/pkfonts600/Makefile#, and all the other are similar). `MASTERDIR` definition tells [.filename]#bsd.port.mk# that the regular set of subdirectories like `FILESDIR` and `SCRIPTDIR` are to be found under [.filename]#pkfonts300#. The `RESOLUTION=360` line will override the `RESOLUTION=300` line in [.filename]#pkfonts300/Makefile# and the port will be built with resolution set to 360.

[[makefile-manpages]]
== Man Pages

If the port anchors its man tree somewhere other than `PREFIX`, use `MANDIRS` to specify those directories. Note that the files corresponding to manual pages must be placed in [.filename]#pkg-plist# along with the rest of the files. The purpose of `MANDIRS` is to enable automatic compression of manual pages, therefore the file names are suffixed with [.filename]#.gz#.

[[makefile-info]]
== Info Files

If the package needs to install GNU info files, list them in `INFO` (without the trailing `.info`), one entry per document. These files are assumed to be installed to [.filename]#PREFIX/INFO_PATH#. Change `INFO_PATH` if the package uses a different location. However, this is not recommended. These entries contain just the path relative to [.filename]#PREFIX/INFO_PATH#. For example, package:lang/gcc34[] installs info files to [.filename]#PREFIX/INFO_PATH/gcc34#, and `INFO` will be something like this:

[.programlisting]
....
INFO=	gcc34/cpp gcc34/cppinternals gcc34/g77 ...
....

Appropriate installation/de-installation code will be automatically added to the temporary [.filename]#pkg-plist# before package registration.

[[makefile-options]]
== Makefile Options

Many applications can be built with optional or differing configurations. Examples include choice of natural (human) language, GUI versus command-line, or type of database to support. Users may need a different configuration than the default, so the ports system provides hooks the port author can use to control which variant will be built. Supporting these options properly will make users happy, and effectively provide two or more ports for the price of one.

[[makefile-options-options]]
=== `OPTIONS`

[[makefile-options-background]]
==== Background

`OPTIONS_*` give the user installing the port a dialog showing the available options, and then saves those options to [.filename]#${PORT_DBDIR}/${OPTIONS_NAME}/options#. The next time the port is built, the options are reused. `PORT_DBDIR` defaults to [.filename]#/var/db/ports#. `OPTIONS_NAME` is to the port origin with an underscore as the space separator, for example, for package:dns/bind99[] it will be `dns_bind99`.

When the user runs `make config` (or runs `make build` for the first time), the framework checks for [.filename]#${PORT_DBDIR}/${OPTIONS_NAME}/options#. If that file does not exist, the values of `OPTIONS_*` are used, and a dialog box is displayed where the options can be enabled or disabled. Then [.filename]#options# is saved and the configured variables are used when building the port.

If a new version of the port adds new `OPTIONS`, the dialog will be presented to the user with the saved values of old `OPTIONS` prefilled.

`make showconfig` shows the saved configuration. Use `make rmconfig` to remove the saved configuration.

[[makefile-options-syntax]]
==== Syntax

`OPTIONS_DEFINE` contains a list of `OPTIONS` to be used. These are independent of each other and are not grouped:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2
....

Once defined, `OPTIONS` are described (optional, but strongly recommended):

[.programlisting]
....
OPT1_DESC=	Describe OPT1
OPT2_DESC=	Describe OPT2
OPT3_DESC=	Describe OPT3
OPT4_DESC=	Describe OPT4
OPT5_DESC=	Describe OPT5
OPT6_DESC=	Describe OPT6
....

[.filename]#ports/Mk/bsd.options.desc.mk# has descriptions for many common `OPTIONS`. While often useful, override them if the description is insufficient for the port.

[TIP]
====

When describing options, view it from the perspective of the user: "What functionality does it change?" and "Why would I want to enable this?" Do not just repeat the name. For example, describing the `NLS` option as "include NLS support" does not help the user, who can already see the option name but may not know what it means. Describing it as "Native Language Support via gettext utilities" is much more helpful.
====

[IMPORTANT]
====
Option names are always in all uppercase. They cannot use mixed case or lowercase.
====

`OPTIONS` can be grouped as radio choices, where only one choice from each group is allowed:

[.programlisting]
....
OPTIONS_SINGLE=		SG1
OPTIONS_SINGLE_SG1=	OPT3 OPT4
....

[WARNING]
====

There _must_ be one of each `OPTIONS_SINGLE` group selected at all times for the options to be valid. One option of each group _must_ be added to `OPTIONS_DEFAULT`.
====

`OPTIONS` can be grouped as radio choices, where none or only one choice from each group is allowed:

[.programlisting]
....
OPTIONS_RADIO=		RG1
OPTIONS_RADIO_RG1=	OPT7 OPT8
....

`OPTIONS` can also be grouped as "multiple-choice" lists, where _at least one_ option must be enabled:

[.programlisting]
....
OPTIONS_MULTI=		MG1
OPTIONS_MULTI_MG1=	OPT5 OPT6
....

`OPTIONS` can also be grouped as "multiple-choice" lists, where none or any option can be enabled:

[.programlisting]
....
OPTIONS_GROUP=		GG1
OPTIONS_GROUP_GG1=	OPT9 OPT10
....

`OPTIONS` are unset by default, unless they are listed in `OPTIONS_DEFAULT`:

[.programlisting]
....
OPTIONS_DEFAULT=	OPT1 OPT3 OPT6
....

`OPTIONS` definitions must appear before the inclusion of [.filename]#bsd.port.options.mk#. `PORT_OPTIONS` values can only be tested after the inclusion of [.filename]#bsd.port.options.mk#. Inclusion of [.filename]#bsd.port.pre.mk# can be used instead, too, and is still widely used in ports written before the introduction of [.filename]#bsd.port.options.mk#. But be aware that some variables will not work as expected after the inclusion of [.filename]#bsd.port.pre.mk#, typically some `USE_*` flags.

[[ports-options-simple-use]]
.Simple Use of `OPTIONS`
[example]
====

[.programlisting]
....
OPTIONS_DEFINE=	FOO BAR
OPTIONS_DEFAULT=FOO

FOO_DESC=	Option foo support
BAR_DESC=	Feature bar support

# Will add --with-foo / --without-foo
FOO_CONFIGURE_WITH=	foo
BAR_RUN_DEPENDS=	bar:bar/bar

.include <bsd.port.mk>
....

====

[[ports-options-check-unset]]
.Check for Unset Port `OPTIONS`
[example]
====

[.programlisting]
....
.if ! ${PORT_OPTIONS:MEXAMPLES}
CONFIGURE_ARGS+=--without-examples
.endif
....

The form shown above is discouraged. The preferred method is using a configure knob to really enable and disable the feature to match the option:

[.programlisting]
....
# Will add --with-examples / --without-examples
EXAMPLES_CONFIGURE_WITH=	examples
....

====

[[ports-options-practical-use]]
.Practical Use of `OPTIONS`
[example]
====

[.programlisting]
....
OPTIONS_DEFINE=		EXAMPLES
OPTIONS_DEFAULT=	PGSQL LDAP SSL

OPTIONS_SINGLE=		BACKEND
OPTIONS_SINGLE_BACKEND=	MYSQL PGSQL BDB

OPTIONS_MULTI=		AUTH
OPTIONS_MULTI_AUTH=	LDAP PAM SSL

EXAMPLES_DESC=		Install extra examples
MYSQL_DESC=		Use MySQL as backend
PGSQL_DESC=		Use PostgreSQL as backend
BDB_DESC=		Use Berkeley DB as backend
LDAP_DESC=		Build with LDAP authentication support
PAM_DESC=		Build with PAM support
SSL_DESC=		Build with OpenSSL support

# Will add USE_PGSQL=yes
PGSQL_USE=	pgsql=yes
# Will add --enable-postgres / --disable-postgres
PGSQL_CONFIGURE_ENABLE=	postgres

ICU_LIB_DEPENDS=	libicuuc.so:devel/icu

# Will add --with-examples / --without-examples
EXAMPLES_CONFIGURE_WITH=	examples

# Check other OPTIONS

.include <bsd.port.mk>
....

====

[[makefile-options-default]]
==== Default Options

These options are always on by default.

* `DOCS` - build and install documentation.
* `NLS` - Native Language Support.
* `EXAMPLES` - build and install examples.
* `IPV6` - IPv6 protocol support.

[NOTE]
====
There is no need to add these to `OPTIONS_DEFAULT`. To have them active, and show up in the options selection dialog, however, they must be added to `OPTIONS_DEFINE`.
====

[[makefile-options-auto-activation]]
=== Feature Auto-Activation

When using a GNU configure script, keep an eye on which optional features are activated by auto-detection. Explicitly disable optional features that are not needed by adding `--without-xxx` or `--disable-xxx` in `CONFIGURE_ARGS`.

[[makefile-options-auto-activation-bad]]
.Wrong Handling of an Option
[example]
====

[.programlisting]
....
.if ${PORT_OPTIONS:MFOO}
LIB_DEPENDS+=		libfoo.so:devel/foo
CONFIGURE_ARGS+=	--enable-foo
.endif
....

====

In the example above, imagine a library libfoo is installed on the system. The user does not want this application to use libfoo, so he toggled the option off in the `make config` dialog. But the application's configure script detects the library present in the system and includes its support in the resulting executable. Now when the user decides to remove libfoo from the system, the ports system does not protest (no dependency on libfoo was recorded) but the application breaks.

[[makefile-options-auto-activation-good]]
.Correct Handling of an Option
[example]
====

[.programlisting]
....
FOO_LIB_DEPENDS=		libfoo.so:devel/foo
# Will add --enable-foo / --disable-foo
FOO_CONFIGURE_ENABLE=	foo
....

====

[NOTE]
====
Under some circumstances, the shorthand conditional syntax can cause problems with complex constructs. The errors are usually `Malformed conditional`, an alternative syntax can be used.

[.programlisting]
....
.if !empty(VARIABLE:MVALUE)
....

as an alternative to

[.programlisting]
....
.if ${VARIABLE:MVALUE}
....

====

[[options-helpers]]
=== Options Helpers

There are some macros to help simplify conditional values which differ based on the options set. For easier access, a comprehensive list is provided:

`PLIST_SUB`, `SUB_LIST`::
For automatic `%%_OPT_%%` and `%%NO__OPT__%%` generation, see <<options_sub>>.
+
For more complex usage, see <<options-variables>>.

`CONFIGURE_ARGS`::
For `--enable-_x_` and `--disable-_x_`, see <<options-configure_enable>>.
+
For `--with-_x_` and `--without-_x_`, see <<options-configure_with>>.
+
For all other cases, see <<options-configure_on>>.

`CMAKE_ARGS`::
For arguments that are booleans (`on`, `off`, `true`, `false`, `0`, `1`) see <<options-cmake_bool>>.
+
For all other cases, see <<options-cmake_on>>.

`MESON_ARGS`::
For arguments that take `true` or `false`, see <<options-meson_true>>.
+
For arguments that take `yes` or `no`, use <<options-meson_yes>>.
+
For arguments that take `enabled` or `disabled`, see <<options-meson_enabled>>.
+
For all other cases, use <<options-meson_on>>.

`QMAKE_ARGS`::
See <<options-qmake_on>>.

`USE_*`::
See <<options-use>>.

`*_DEPENDS`::
See <<options-dependencies>>.

`*` (Any variable)::
The most used variables have direct helpers, see <<options-variables>>.
+
For any variable without a specific helper, see <<options-vars>>.

Options dependencies::
When an option need another option to work, see <<options-implies>>.

Options conflicts::
When an option cannot work if another is also enabled, see <<options-prevents>>.

Build targets::
When an option need some extra processing, see <<options-targets>>.

[[options_sub]]
==== `OPTIONS_SUB`

If `OPTIONS_SUB` is set to `yes` then each of the options added to `OPTIONS_DEFINE` will be added to `PLIST_SUB` and `SUB_LIST`, for example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPTIONS_SUB=	yes
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
PLIST_SUB+=	OPT1="" NO_OPT1="@comment "
SUB_LIST+=	OPT1="" NO_OPT1="@comment "
.else
PLIST_SUB+=	OPT1="@comment " NO_OPT1=""
SUB_LIST+=	OPT1="@comment " NO_OPT1=""
.endif
....

[NOTE]
====
The value of `OPTIONS_SUB` is ignored. Setting it to any value will add `PLIST_SUB` and `SUB_LIST` entries for _all_ options.
====

[[options-use]]
==== `OPT_USE` and `OPT_USE_OFF`

When option _OPT_ is selected, for each `_key=value_` pair in ``OPT_USE``, _value_ is appended to the corresponding `USE_KEY`. If _value_ has spaces in it, replace them with commas and they will be changed back to spaces during processing. `OPT_USE_OFF` works the same way, but when `OPT` is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_USES=	xorg
OPT1_USE=	mysql=yes xorg=x11,xextproto,xext,xrandr
OPT1_USE_OFF=	openssl=yes
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
USE_MYSQL=	yes
USES+=		xorg
USE_XORG=	x11 xextproto xext xrandr
.else
USE_OPENSSL=	yes
.endif
....

[[options-configure-helpers]]
==== `CONFIGURE_ARGS` Helpers

[[options-configure_enable]]
===== `OPT_CONFIGURE_ENABLE`

When option _OPT_ is selected, for each _entry_ in `OPT_CONFIGURE_ENABLE` then `--enable-_entry_` is appended to `CONFIGURE_ARGS`. When option _OPT_ is _not_ selected, `--disable-_entry_` is appended to `CONFIGURE_ARGS`. An optional argument can be specified with an `=` symbol. This argument is only appended to the `--enable-_entry_` configure option. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2
OPT1_CONFIGURE_ENABLE=	test1 test2
OPT2_CONFIGURE_ENABLE=	test2=exhaustive
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
CONFIGURE_ARGS+=	--enable-test1 --enable-test2
.else
CONFIGURE_ARGS+=	--disable-test1 --disable-test2
.endif

.if ${PORT_OPTIONS:MOPT2}
CONFIGURE_ARGS+=	--enable-test2=exhaustive
.else
CONFIGURE_ARGS+=	--disable-test2
.endif
....

[[options-configure_with]]
===== `OPT_CONFIGURE_WITH`

When option _OPT_ is selected, for each _entry_ in `_OPT_CONFIGURE_WITH` then `--with-_entry_` is appended to `CONFIGURE_ARGS`. When option _OPT_ is _not_ selected, `--without-_entry_` is appended to `CONFIGURE_ARGS`. An optional argument can be specified with an `=` symbol. This argument is only appended to the `--with-_entry_` configure option. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2
OPT1_CONFIGURE_WITH=	test1
OPT2_CONFIGURE_WITH=	test2=exhaustive
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
CONFIGURE_ARGS+=	--with-test1
.else
CONFIGURE_ARGS+=	--without-test1
.endif

.if ${PORT_OPTIONS:MOPT2}
CONFIGURE_ARGS+=	--with-test2=exhaustive
.else
CONFIGURE_ARGS+=	--without-test2
.endif
....

[[options-configure_on]]
===== `OPT_CONFIGURE_ON` and `OPT_CONFIGURE_OFF`

When option _OPT_ is selected, the value of `OPT_CONFIGURE_ON`, if defined, is appended to `CONFIGURE_ARGS`. `OPT_CONFIGURE_OFF` works the same way, but when `OPT` is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_CONFIGURE_ON=	--add-test
OPT1_CONFIGURE_OFF=	--no-test
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
CONFIGURE_ARGS+=	--add-test
.else
CONFIGURE_ARGS+=	--no-test
.endif
....

[TIP]
====

Most of the time, the helpers in <<options-configure_enable>> and <<options-configure_with>> provide a shorter and more comprehensive functionality.
====

[[options-cmake-helpers]]
==== `CMAKE_ARGS` Helpers

[[options-cmake_on]]
===== `OPT_CMAKE_ON` and `OPT_CMAKE_OFF`

When option _OPT_ is selected, the value of `OPT_CMAKE_ON`, if defined, is appended to `CMAKE_ARGS`. `OPT_CMAKE_OFF` works the same way, but when `OPT` is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_CMAKE_ON=	-DTEST:BOOL=true -DDEBUG:BOOL=true
OPT1_CMAKE_OFF=	-DOPTIMIZE:BOOL=true
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
CMAKE_ARGS+=	-DTEST:BOOL=true -DDEBUG:BOOL=true
.else
CMAKE_ARGS+=	-DOPTIMIZE:BOOL=true
.endif
....

[TIP]
====

See <<options-cmake_bool>> for a shorter helper when the value is boolean.
====

[[options-cmake_bool]]
===== `OPT_CMAKE_BOOL` and `OPT_CMAKE_BOOL_OFF`

When option _OPT_ is selected, for each _entry_ in `OPT_CMAKE_BOOL` then `-D_entry_:BOOL=true` is appended to `CMAKE_ARGS`. When option _OPT_ is _not_ selected, `-D_entry_:BOOL=false` is appended to `CONFIGURE_ARGS`. `OPT_CMAKE_BOOL_OFF` is the opposite, `-D_entry_:BOOL=false` is appended to `CMAKE_ARGS` when the option is selected, and `-D_entry_:BOOL=true` when the option is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_CMAKE_BOOL=	TEST DEBUG
OPT1_CMAKE_BOOL_OFF=	OPTIMIZE
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
CMAKE_ARGS+=	-DTEST:BOOL=true -DDEBUG:BOOL=true \
		-DOPTIMIZE:BOOL=false
.else
CMAKE_ARGS+=	-DTEST:BOOL=false -DDEBUG:BOOL=false \
		-DOPTIMIZE:BOOL=true
.endif
....

[[options-meson-helpers]]
==== `MESON_ARGS` Helpers

[[options-meson_on]]
===== `OPT_MESON_ON` and `OPT_MESON_OFF`

When option _OPT_ is selected, the value of `OPT_MESON_ON`, if defined, is appended to `MESON_ARGS`. `OPT_MESON_OFF` works the same way, but when `OPT` is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_MESON_ON=	-Dopt=1
OPT1_MESON_OFF=	-Dopt=2
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
MESON_ARGS+=	-Dopt=1
.else
MESON_ARGS+=	-Dopt=2
.endif
....

[[options-meson_true]]
===== `OPT_MESON_TRUE` and `OPT_MESON_FALSE`

When option _OPT_ is selected, for each _entry_ in `OPT_MESON_TRUE` then `-D_entry_=true` is appended to `MESON_ARGS`. When option _OPT_ is _not_ selected, `-D_entry_=false` is appended to `MESON_ARGS`. `OPT_MESON_FALSE` is the opposite, `-D_entry_=false` is appended to `MESON_ARGS` when the option is selected, and `-D_entry_=true` when the option is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_MESON_TRUE=	test debug
OPT1_MESON_FALSE=	optimize
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
MESON_ARGS+=	-Dtest=true -Ddebug=true \
		-Doptimize=false
.else
MESON_ARGS+=	-Dtest=false -Ddebug=false \
		-Doptimize=true
.endif
....

[[options-meson_yes]]
===== `OPT_MESON_YES` and `OPT_MESON_NO`

When option _OPT_ is selected, for each _entry_ in `OPT_MESON_YES` then `-D_entry_=yes` is appended to `MESON_ARGS`. When option _OPT_ is _not_ selected, `-D_entry_=no` is appended to `MESON_ARGS`. `OPT_MESON_NO` is the opposite, `-D_entry_=no` is appended to `MESON_ARGS` when the option is selected, and `-D_entry_=yes` when the option is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_MESON_YES=	test debug
OPT1_MESON_NO=	optimize
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
MESON_ARGS+=	-Dtest=yes -Ddebug=yes \
		-Doptimize=no
.else
MESON_ARGS+=	-Dtest=no -Ddebug=no \
		-Doptimize=yes
.endif
....

[[options-meson_enabled]]
===== `OPT_MESON_ENABLED` and `OPT_MESON_DISABLED`

When option _OPT_ is selected, for each _entry_ in `OPT_MESON_ENABLED` then `-D_entry_=enabled` is appended to `MESON_ARGS`. When option _OPT_ is _not_ selected, `-D_entry_=disabled` is appended to `MESON_ARGS`. `OPT_MESON_DISABLED` is the opposite, `-D_entry_=disabled` is appended to `MESON_ARGS` when the option is selected, and `-D_entry_=enabled` when the option is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_MESON_ENABLED=	test
OPT1_MESON_DISABLED=	debug
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
MESON_ARGS+=	-Dtest=enabled -Ddebug=disabled
.else
MESON_ARGS+=	-Dtest=disabled -Ddebug=enabled
.endif
....

[[options-qmake_on]]
==== `OPT_QMAKE_ON` and `OPT_QMAKE_OFF`

When option _OPT_ is selected, the value of `OPT_QMAKE_ON`, if defined, is appended to `QMAKE_ARGS`. `OPT_QMAKE_OFF` works the same way, but when `OPT` is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_QMAKE_ON=	-DTEST:BOOL=true
OPT1_QMAKE_OFF=	-DPRODUCTION:BOOL=true
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
QMAKE_ARGS+=	-DTEST:BOOL=true
.else
QMAKE_ARGS+=	-DPRODUCTION:BOOL=true
.endif
....

[[options-implies]]
==== `OPT_IMPLIES`

Provides a way to add dependencies between options.

When _OPT_ is selected, all the options listed in this variable will be selected too. Using the <<options-configure_enable,`OPT_CONFIGURE_ENABLE`>> described earlier to illustrate:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2
OPT1_IMPLIES=	OPT2

OPT1_CONFIGURE_ENABLE=	opt1
OPT2_CONFIGURE_ENABLE=	opt2
....

Is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
CONFIGURE_ARGS+=	--enable-opt1
.else
CONFIGURE_ARGS+=	--disable-opt1
.endif

.if ${PORT_OPTIONS:MOPT2} || ${PORT_OPTIONS:MOPT1}
CONFIGURE_ARGS+=	--enable-opt2
.else
CONFIGURE_ARGS+=	--disable-opt2
.endif
....

[[options-implies-ex1]]
.Simple Use of `OPT_IMPLIES`
[example]
====

This port has a `X11` option, and a `GNOME` option that needs the `X11` option to be selected to build.

[.programlisting]
....
OPTIONS_DEFINE=	X11 GNOME
OPTIONS_DEFAULT=	X11

X11_USES=	xorg
X11_USE=	xorg=xi,xextproto
GNOME_USE=	gnome=gtk30
GNOME_IMPLIES=	X11
....

====

[[options-prevents]]
==== `OPT_PREVENTS` and `OPT_PREVENTS_MSG`

Provides a way to add conflicts between options.

When _OPT_ is selected, all the options listed in `OPT_PREVENTS` must be un-selected. If `OPT_PREVENTS_MSG` is set and a conflict is triggered, its content will be shown explaining why they conflict. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2
OPT1_PREVENTS=	OPT2
OPT1_PREVENTS_MSG=	OPT1 and OPT2 enable conflicting options
....

Is roughly equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT2} && ${PORT_OPTIONS:MOPT1}
BROKEN=	Option OPT1 conflicts with OPT2 (select only one)
.endif
....

The only difference is that the first one will write an error after running `make config`, suggesting changing the selected options.

[[options-prevents-ex1]]
.Simple Use of `OPT_PREVENTS`
[example]
====

This port has `X509` and `SCTP` options. Both options add patches, but the patches conflict with each other, so they cannot be selected at the same time.

[.programlisting]
....
OPTIONS_DEFINE=	X509 SCTP

SCTP_PATCHFILES=	${PORTNAME}-6.8p1-sctp-2573.patch.gz:-p1
SCTP_CONFIGURE_WITH=	sctp

X509_PATCH_SITES=	http://www.roumenpetrov.info/openssh/x509/:x509
X509_PATCHFILES=	${PORTNAME}-7.0p1+x509-8.5.diff.gz:-p1:x509
X509_PREVENTS=		SCTP
X509_PREVENTS_MSG=	X509 and SCTP patches conflict
....

====

[[options-vars]]
==== `OPT_VARS` and `OPT_VARS_OFF`

Provides a generic way to set and append to variables.

[WARNING]
====

Before using `OPT_VARS` and `OPT_VARS_OFF`, see if there is already a more specific helper available in <<options-variables>>.
====

When option _OPT_ is selected, and `OPT_VARS` defined, `_key_=_value_` and `_key_+=_value_` pairs are evaluated from `OPT_VARS`. An `=` cause the existing value of `KEY` to be overwritten, an `+=` appends to the value. `OPT_VARS_OFF` works the same way, but when `OPT` is _not_ selected.

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2 OPT3
OPT1_VARS=	also_build+=bin1
OPT2_VARS=	also_build+=bin2
OPT3_VARS=	bin3_build=yes
OPT3_VARS_OFF=	bin3_build=no

MAKE_ARGS=	ALSO_BUILD="${ALSO_BUILD}" BIN3_BUILD="${BIN3_BUILD}"
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1 OPT2

MAKE_ARGS=	ALSO_BUILD="${ALSO_BUILD}" BIN3_BUILD="${BIN3_BUILD}"

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
ALSO_BUILD+=	bin1
.endif

.if ${PORT_OPTIONS:MOPT2}
ALSO_BUILD+=	bin2
.endif

.if ${PORT_OPTIONS:MOPT2}
BIN3_BUILD=	yes
.else
BIN3_BUILD=	no
.endif
....

[IMPORTANT]
====
Values containing whitespace must be enclosed in quotes:

[.programlisting]
....
OPT_VARS=	foo="bar baz"
....

This is due to the way man:make[1] variable expansion deals with whitespace. When `OPT_VARS= foo=bar baz` is expanded, the variable ends up containing two strings, `foo=bar` and `baz`. But the submitter probably intended there to be only one string, `foo=bar baz`. Quoting the value prevents whitespace from being used as a delimiter.

Also, _do not_ add extra spaces after the `_var_=` sign and before the value, it would also be split into two strings. _This will not work_:

[.programlisting]
....
OPT_VARS=	foo=	bar
....

====

[[options-dependencies]]
==== Dependencies, `OPT_DEPTYPE` and `OPT_DEPTYPE_OFF`

For any of these dependency types:

* `PKG_DEPENDS`
* `EXTRACT_DEPENDS`
* `PATCH_DEPENDS`
* `FETCH_DEPENDS`
* `BUILD_DEPENDS`
* `LIB_DEPENDS`
* `RUN_DEPENDS`

When option _OPT_ is selected, the value of `PT_DEPTYPE`, if defined, is appended to `DEPTYPE`. `OPT_DEPTYPE_OFF` works the same, but when `OPT` is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_LIB_DEPENDS=	liba.so:devel/a
OPT1_LIB_DEPENDS_OFF=	libb.so:devel/b
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
LIB_DEPENDS+=	liba.so:devel/a
.else
LIB_DEPENDS+=	libb.so:devel/b
.endif
....

[[options-variables]]
==== Generic Variables Replacement, `OPT_VARIABLE` and `OPT_VARIABLE_OFF`

For any of these variables:

* `ALL_TARGET`
* `BINARY_ALIAS`
* `BROKEN`
* `CATEGORIES`
* `CFLAGS`
* `CONFIGURE_ENV`
* `CONFLICTS`
* `CONFLICTS_BUILD`
* `CONFLICTS_INSTALL`
* `CPPFLAGS`
* `CXXFLAGS`
* `DESKTOP_ENTRIES`
* `DISTFILES`
* `EXTRACT_ONLY`
* `EXTRA_PATCHES`
* `GH_ACCOUNT`
* `GH_PROJECT`
* `GH_SUBDIR`
* `GH_TAGNAME`
* `GH_TUPLE`
* `GL_ACCOUNT`
* `GL_COMMIT`
* `GL_PROJECT`
* `GL_SITE`
* `GL_SUBDIR`
* `GL_TUPLE`
* `IGNORE`
* `INFO`
* `INSTALL_TARGET`
* `LDFLAGS`
* `LIBS`
* `MAKE_ARGS`
* `MAKE_ENV`
* `MASTER_SITES`
* `PATCHFILES`
* `PATCH_SITES`
* `PLIST_DIRS`
* `PLIST_FILES`
* `PLIST_SUB`
* `PORTDOCS`
* `PORTEXAMPLES`
* `SUB_FILES`
* `SUB_LIST`
* `TEST_TARGET`
* `USES`

When option _OPT_ is selected, the value of `OPT_ABOVEVARIABLE`, if defined, is appended to `_ABOVEVARIABLE_`. `OPT_ABOVEVARIABLE_OFF` works the same way, but when `OPT` is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1
OPT1_USES=	gmake
OPT1_CFLAGS_OFF=	-DTEST
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MOPT1}
USES+=		gmake
.else
CFLAGS+=	-DTEST
.endif
....

[NOTE]
====
Some variables are not in this list, in particular `PKGNAMEPREFIX` and `PKGNAMESUFFIX`. This is intentional. A port _must not_ change its name when its option set changes.
====

[WARNING]
====

Some of these variables, at least `ALL_TARGET`, `DISTFILES` and `INSTALL_TARGET`, have their default values set _after_ the options are processed.

With these lines in the [.filename]#Makefile#:

[.programlisting]
....
ALL_TARGET=	all

DOCS_ALL_TARGET=	doc
....

If the `DOCS` option is enabled, `ALL_TARGET` will have a final value of `all doc`; if the option is disabled, it would have a value of `all`.

With only the options helper line in the [.filename]#Makefile#:

[.programlisting]
....
DOCS_ALL_TARGET=	doc
....

If the `DOCS` option is enabled, `ALL_TARGET` will have a final value of `doc`; if the option is disabled, it would have a value of `all`.
====

[[options-targets]]
==== Additional Build Targets, `_target_-_OPT_-on` and `_target_-_OPT_-off`

These [.filename]#Makefile# targets can accept optional extra build targets:

* `pre-fetch`
* `do-fetch`
* `post-fetch`
* `pre-extract`
* `do-extract`
* `post-extract`
* `pre-patch`
* `do-patch`
* `post-patch`
* `pre-configure`
* `do-configure`
* `post-configure`
* `pre-build`
* `do-build`
* `post-build`
* `pre-install`
* `do-install`
* `post-install`
* `post-stage`
* `pre-package`
* `do-package`
* `post-package`

When option _OPT_ is selected, the target `_TARGET_-_OPT_-on`, if defined, is executed after `_TARGET_`. `_TARGET_-_OPT_-off` works the same way, but when `OPT` is _not_ selected. For example:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

post-patch-OPT1-on:
	@${REINPLACE_CMD} -e '/opt1/s|/usr/bin/|${EXAMPLESDIR}/|' ${WRKSRC}/Makefile

post-patch-OPT1-off:
	@${REINPLACE_CMD} -e '/opt1/s|/usr/bin/|${PREFIX}/bin/|' ${WRKSRC}/Makefile
....

is equivalent to:

[.programlisting]
....
OPTIONS_DEFINE=	OPT1

.include <bsd.port.options.mk>

post-patch:
.if ${PORT_OPTIONS:MOPT1}
	@${REINPLACE_CMD} -e '/opt1/s|/usr/bin/|${EXAMPLESDIR}/|' ${WRKSRC}/Makefile
.else
	@${REINPLACE_CMD} -e '/opt1/s|/usr/bin/|${PREFIX}/bin/|' ${WRKSRC}/Makefile
.endif
....

[[makefile-wrkdir]]
== Specifying the Working Directory

Each port is extracted into a working directory, which must be writable. The ports system defaults to having `DISTFILES` unpack in to a directory called `${DISTNAME}`. In other words, if the [.filename]#Makefile# has:

[.programlisting]
....
PORTNAME=	foo
DISTVERSION=	1.0
....

then the port's distribution files contain a top-level directory, [.filename]#foo-1.0#, and the rest of the files are located under that directory.

A number of variables can be overridden if that is not the case.

[[makefile-wrksrc]]
=== `WRKSRC`

The variable lists the name of the directory that is created when the application's distfiles are extracted. If our previous example extracted into a directory called [.filename]#foo# (and not [.filename]#foo-1.0#) write:

[.programlisting]
....
WRKSRC=	${WRKDIR}/foo
....

or possibly

[.programlisting]
....
WRKSRC=	${WRKDIR}/${PORTNAME}
....

[[makefile-wrksrc_subdir]]
=== `WRKSRC_SUBDIR`

If the source files needed for the port are in a subdirectory of the extracted distribution file, set `WRKSRC_SUBDIR` to that directory.

[.programlisting]
....
WRKSRC_SUBDIR=	src
....

[[makefile-no_wrksubdir]]
=== `NO_WRKSUBDIR`

If the port does not extract in to a subdirectory at all, then set `NO_WRKSUBDIR` to indicate that.

[.programlisting]
....
NO_WRKSUBDIR=	yes
....

[NOTE]
====
Because `WRKDIR` is the only directory that is supposed to be writable during the build, and is used to store many files recording the status of the build, the port's extraction will be forced into a subdirectory.
====

[[conflicts]]
== Conflict Handling

There are three different variables to register a conflict between packages and ports: `CONFLICTS`, `CONFLICTS_INSTALL` and `CONFLICTS_BUILD`.

[NOTE]
====
The conflict variables automatically set the variable `IGNORE`, which is more fully documented in <<dads-noinstall>>.
====

When removing one of several conflicting ports, it is advisable to retain `CONFLICTS` in those other ports for a few months to cater for users who only update once in a while.

[[conclicts-conflicts_install]]
`CONFLICTS_INSTALL`::
If the package cannot coexist with other packages (because of file conflicts, runtime incompatibilities, etc.). `CONFLICTS_INSTALL` check is done after the build stage and prior to the install stage.

[[conclicts-conflicts_build]]
`CONFLICTS_BUILD`::
If the port cannot be built when other specific ports are already installed. Build conflicts are not recorded in the resulting package.

[[conclicts-conflicts]]
`CONFLICTS`::
If the port cannot be built if a certain port is already installed and the resulting package cannot coexist with the other package. `CONFLICTS` check is done prior to the build stage and prior to the install stage.

The most common content of one of these variable is the package base of another port. The package base is the package name without the appended version, it can be obtained by running `make -V PKGBASE`.

[[conflicts-ex1]]
.Basic usage of `CONFLICTS*`
[example]
====

package:dns/bind99[] cannot be installed if package:dns/bind910[] is present because they install same files. First gather the package base to use:

[source,bash]
....
% make -C dns/bind99 -V PKGBASE
bind99
% make -C dns/bind910 -V PKGBASE
bind910
....

Then add to the [.filename]#Makefile# of package:dns/bind99[]:

[.programlisting]
....
CONFLICTS_INSTALL=	bind910
....

And add to the [.filename]#Makefile# of package:dns/bind910[]:

[.programlisting]
....
CONFLICTS_INSTALL=	bind99
....

====

Sometime, only some version of another port is incompatible, in this case, use the full package name, with the version, and use shell globs, like `*` and `?` to make sure all possible versions are matched.

[[conflicts-ex2]]
.Using `CONFLICTS*` With Globs.
[example]
====

From versions from 2.0 and up-to 2.4.1_2, package:deskutils/gnotime[] used to install a bundled version of package:databases/qof[].

To reflect this past, the [.filename]#Makefile# of package:databases/qof[] contains:

[.programlisting]
....
CONFLICTS_INSTALL=	gnotime-2.[0-3]* \
			gnotime-2.4.0* gnotime-2.4.1 \
			gnotime-2.4.1_[12]
....

The first entry match versions `2.0` through `2.3`, the second all the revisions of `2.4.0`, the third the exact `2.4.1` version, and the last the first and second revisions of the `2.4.1` version.

package:deskutils/gnotime[] does not have any conflicts line because its current version does not conflict with anything else.
====

[[install]]
== Installing Files

[IMPORTANT]
====
The `install` phase is very important to the end user because it adds files to their system. All the additional commands run in the port [.filename]#Makefile#'s `*-install` targets should be echoed to the screen. _Do not_ silence these commands with `@` or `.SILENT`.
====

[[install-macros]]
=== `INSTALL_*` Macros

Use the macros provided in [.filename]#bsd.port.mk# to ensure correct modes of files in the port's `*-install` targets. Set ownership directly in [.filename]#pkg-plist# with the corresponding entries, such as `@(_owner_,_group_,)`, `@owner _owner_`, and `@group _group_`. These operators work until overridden, or until the end of [.filename]#pkg-plist#, so remember to reset them after they are no longer needed. The default ownership is `root:wheel`. See <<plist-keywords-base>> for more information.

* `INSTALL_PROGRAM` is a command to install binary executables.
* `INSTALL_SCRIPT` is a command to install executable scripts.
* `INSTALL_LIB` is a command to install shared libraries (but not static libraries).
* `INSTALL_KLD` is a command to install kernel loadable modules. Some architectures do not like having the modules stripped, so use this command instead of `INSTALL_PROGRAM`.
* `INSTALL_DATA` is a command to install sharable data, including static libraries.
* `INSTALL_MAN` is a command to install manpages and other documentation (it does not compress anything).

These variables are set to the man:install[1] command with the appropriate flags for each situation.

[IMPORTANT]
====
Do not use `INSTALL_LIB` to install static libraries, because stripping them renders them useless. Use `INSTALL_DATA` instead.
====

[[install-strip]]
=== Stripping Binaries and Shared Libraries

Installed binaries should be stripped. Do not strip binaries manually unless absolutely required. The `INSTALL_PROGRAM` macro installs and strips a binary at the same time. The `INSTALL_LIB` macro does the same thing to shared libraries.

When a file must be stripped, but neither `INSTALL_PROGRAM` nor `INSTALL_LIB` macros are desirable, `${STRIP_CMD}` strips the program or shared library. This is typically done within the `post-install` target. For example:

[.programlisting]
....
post-install:
	${STRIP_CMD} ${STAGEDIR}${PREFIX}/bin/xdl
....

When multiple files need to be stripped:

[.programlisting]
....
post-install:
.for l in geometry media body track world
	${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/lib${PORTNAME}-${l}.so.0
.endfor
....

Use man:file[1] on a file to determine if it has been stripped. Binaries are reported by man:file[1] as `stripped`, or `not stripped`. Additionally, man:strip[1] will detect programs that have already been stripped and exit cleanly.

[IMPORTANT]
====
When `WITH_DEBUG` is defined, elf files _must not_ be stripped.

The variables (`STRIP_CMD`, `INSTALL_PROGRAM`, `INSTALL_LIB`, ...) and <<uses,`USES`>> provided by the framework handle this automatically.

Some software, add `-s` to their `LDFLAGS`, in this case, either remove `-s` if `WITH_DEBUG` is set, or remove it unconditionally and use `STRIP_CMD` in `post-install`.
====

[[install-copytree]]
=== Installing a Whole Tree of Files

Sometimes, a large number of files must be installed while preserving their hierarchical organization. For example, copying over a whole directory tree from `WRKSRC` to a target directory under `PREFIX`. Note that `PREFIX`, `EXAMPLESDIR`, `DATADIR`, and other path variables must always be prepended with `STAGEDIR` to respect staging (see <<staging>>).

Two macros exist for this situation. The advantage of using these macros instead of `cp` is that they guarantee proper file ownership and permissions on target files. The first macro, `COPYTREE_BIN`, will set all the installed files to be executable, thus being suitable for installing into [.filename]#PREFIX/bin#. The second macro, `COPYTREE_SHARE`, does not set executable permissions on files, and is therefore suitable for installing files under [.filename]#PREFIX/share# target.

[.programlisting]
....
post-install:
	${MKDIR} ${STAGEDIR}${EXAMPLESDIR}
	(cd ${WRKSRC}/examples && ${COPYTREE_SHARE} . ${STAGEDIR}${EXAMPLESDIR})
....

This example will install the contents of the [.filename]#examples# directory in the vendor distfile to the proper examples location of the port.

[.programlisting]
....
post-install:
	${MKDIR} ${STAGEDIR}${DATADIR}/summer
	(cd ${WRKSRC}/temperatures && ${COPYTREE_SHARE} "June July August" ${STAGEDIR}${DATADIR}/summer)
....

And this example will install the data of summer months to the [.filename]#summer# subdirectory of a [.filename]#DATADIR#.

Additional `find` arguments can be passed via the third argument to `COPYTREE_*` macros. For example, to install all files from the first example except Makefiles, one can use these commands.

[.programlisting]
....
post-install:
	${MKDIR} ${STAGEDIR}${EXAMPLESDIR}
	(cd ${WRKSRC}/examples && \
	${COPYTREE_SHARE} . ${STAGEDIR}${EXAMPLESDIR} "! -name Makefile")
....

These macros do not add the installed files to [.filename]#pkg-plist#. They must be added manually. For optional documentation (`PORTDOCS`, see <<install-documentation>>) and examples (`PORTEXAMPLES`), the `%%PORTDOCS%%` or `%%PORTEXAMPLES%%` prefixes must be prepended in [.filename]#pkg-plist#.

[[install-documentation]]
=== Install Additional Documentation

If the software has some documentation other than the standard man and info pages that is useful for the user, install it under `DOCSDIR` This can be done, like the previous item, in the `post-install` target.

Create a new directory for the port. The directory name is `DOCSDIR`. This usually equals `PORTNAME`. However, if the user might want different versions of the port to be installed at the same time, the whole `PKGNAME` can be used.

Since only the files listed in [.filename]#pkg-plist# are installed, it is safe to always install documentation to `STAGEDIR` (see <<staging>>). Hence `.if` blocks are only needed when the installed files are large enough to cause significant I/O overhead.

[.programlisting]
....
post-install:
	${MKDIR} ${STAGEDIR}${DOCSDIR}
	${INSTALL_MAN} ${WRKSRC}/docs/xvdocs.ps ${STAGEDIR}${DOCSDIR}
....

On the other hand, if there is a DOCS option in the port, install the documentation in a `post-install-DOCS-on` target. These targets are described in <<options-targets>>.

Here are some handy variables and how they are expanded by default when used in the [.filename]#Makefile#:

* `DATADIR` gets expanded to [.filename]#PREFIX/shared/PORTNAME#.
* `DATADIR_REL` gets expanded to [.filename]#share/PORTNAME#.
* `DOCSDIR` gets expanded to [.filename]#PREFIX/shared/doc/PORTNAME#.
* `DOCSDIR_REL` gets expanded to [.filename]#share/doc/PORTNAME#.
* `EXAMPLESDIR` gets expanded to [.filename]#PREFIX/shared/examples/PORTNAME#.
* `EXAMPLESDIR_REL` gets expanded to [.filename]#share/examples/PORTNAME#.

[NOTE]
====
The `DOCS` option only controls additional documentation installed in `DOCSDIR`. It does not apply to standard man pages and info pages. Things installed in `EXAMPLESDIR` are controlled by the `EXAMPLES` option.
====

These variables are exported to `PLIST_SUB`. Their values will appear there as pathnames relative to [.filename]#PREFIX# if possible. That is, [.filename]#share/doc/PORTNAME# will be substituted for `%%DOCSDIR%%` in the packing list by default, and so on. (See more on [.filename]#pkg-plist# substitution <<plist-sub,here>>.)

All conditionally installed documentation files and directories are included in [.filename]#pkg-plist# with the `%%PORTDOCS%%` prefix, for example:

[.programlisting]
....
%%PORTDOCS%%%%DOCSDIR%%/AUTHORS
%%PORTDOCS%%%%DOCSDIR%%/CONTACT
....

As an alternative to enumerating the documentation files in [.filename]#pkg-plist#, a port can set the variable `PORTDOCS` to a list of file names and shell glob patterns to add to the final packing list. The names will be relative to `DOCSDIR`. Therefore, a port that utilizes `PORTDOCS`, and uses a non-default location for its documentation, must set `DOCSDIR` accordingly. If a directory is listed in `PORTDOCS` or matched by a glob pattern from this variable, the entire subtree of contained files and directories will be registered in the final packing list. If the `DOCS` option has been unset then files and directories listed in `PORTDOCS` would not be installed or added to port packing list. Installing the documentation at `PORTDOCS` as shown above remains up to the port itself. A typical example of utilizing `PORTDOCS`:

[.programlisting]
....
PORTDOCS=	README.* ChangeLog docs/*
....

[NOTE]
====
The equivalents of `PORTDOCS` for files installed under `DATADIR` and `EXAMPLESDIR` are `PORTDATA` and `PORTEXAMPLES`, respectively.

The contents of [.filename]#pkg-message# are displayed upon installation. See <<porting-message,the section on using [.filename]#pkg-message#>> for details. [.filename]#pkg-message# does not need to be added to [.filename]#pkg-plist#.
====

[[install-subdirs]]
=== Subdirectories Under `PREFIX`

Try to let the port put things in the right subdirectories of `PREFIX`. Some ports lump everything and put it in the subdirectory with the port's name, which is incorrect. Also, many ports put everything except binaries, header files and manual pages in a subdirectory of [.filename]#lib#, which does not work well with the BSD paradigm. Many of the files must be moved to one of these directories: [.filename]#etc# (setup/configuration files), [.filename]#libexec# (executables started internally), [.filename]#sbin# (executables for superusers/managers), [.filename]#info# (documentation for info browser) or [.filename]#share# (architecture independent files). See man:hier[7] for details; the rules governing [.filename]#/usr# pretty much apply to [.filename]#/usr/local# too. The exception are ports dealing with USENET "news". They may use [.filename]#PREFIX/news# as a destination for their files.

[[binary-alias]]
== Use `BINARY_ALIAS` to Rename Commands Instead of Patching the Build

When `BINARY_ALIAS` is defined it will create symlinks of the given commands in a directory which will be prepended to `PATH`.

Use it to substitute hardcoded commands the build phase relies on without having to patch any build files.

[[binary-alias-ex1]]
.Using `BINARY_ALIAS` to Make `gsed` Available as `sed`
[example]
====

Some ports expect `sed` to behave like GNU sed and use features that man:sed[1] does not provide. GNU sed is available from package:textproc/gsed[] on FreeBSD.

Use `BINARY_ALIAS` to substitute `sed` with `gsed` for the duration of the build:

[.programlisting]
....
BUILD_DEPENDS=	gsed:textproc/gsed
...
BINARY_ALIAS=	sed=gsed
....

====

[[binary-alias-ex2]]
.Using `BINARY_ALIAS` to Provide Aliases for Hardcoded `python3` Commands
[example]
====

A port that has a hardcoded reference to `python3` in its build scripts will need to have it available in `PATH` at build time. Use `BINARY_ALIAS` to create an alias that points to the right Python 3 binary:

[.programlisting]
....
USES=	python:3.4+,build
...
BINARY_ALIAS=	python3=${PYTHON_CMD}
....

See <<using-python>> for more information about `USES=python`.
====
