#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD$
#    Original revision: 1.4
#

SUBDIR = faq
SUBDIR+= handbook

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
