---
title: "A FreeBSD Projekt szervezeti felépítése"
sidenav: about
---

include::shared/authors.adoc[]

////
NOTE: If any alias listed on this page is modified in the
/etc/aliases on the FreeBSD project's mail server,
then this page must be updated.
////

= A FreeBSD Projekt szervezeti felépítése

== Bevezetés

Ez az oldal tartalmazza a FreeBSD Projektben kiemelt szereppel és felelõsséggel bíró csoportokat és személyeket, illetve az azon belül betöltött szerepük rövid leírását, valamint elérhetõségeiket.

* A Projekt vezetõsége
** <<t-core,A Core Team>>
** <<t-doceng,A Documentation Engineering Team>>
** <<t-portmgr,A Port Management Team>>
* Kiadások tervezése és ütemezése
** <<t-re,Elsõdleges Release Engineering Team>>
** <<t-re-amd64,FreeBSD/amd64 Release Engineering Team>>
** <<t-re-ia64,FreeBSD/ia64 Release Engineering Team>>
** <<t-re-x86,FreeBSD/i386 Release Engineering Team>>
** <<t-re-pc98,FreeBSD/pc98 Release Engineering Team>>
** <<t-re-ppc,FreeBSD/ppc Release Engineering Team>>
** <<t-re-sparc64,FreeBSD/sparc64 Release Engineering Team>>
* További csoportok
** <<t-donations,Donations Team>>
** <<t-marketing,Marketing Team>>
** <<t-secteam,Security Team>>
** <<t-vendor,Vendor Relations Team>>
* Titkárok
** <<t-core-secretary,Core Team titkár>>
** <<t-portmgr-secretary,Port Management Team titkár>>
** <<t-secteam-secretary,Security Team titkár>>
* Belsõ ügyintézés
** <<t-accounts,Hozzáférések>>
** <<t-backups,Biztonsági mentések>>
** <<t-bugmeister,Bugmeisterek és GNATS rendszergazdák>>
** <<t-clusteradm,Klaszter rendszergazdák>>
** <<t-dcvs,doc/www CVS repository megbízottak>>
** <<t-pcvs,ports CVS repository megbízottak>>
** <<t-ncvs,src CVS repository megbízottak>>
** <<t-cvsup-master,A CVSup tükrözések koordinátorai>>
** <<t-dnsadm,DNS rendszergazdák>>
** <<t-mirror-admin,Az FTP/WWW tükrözések koordinátorai>>
** <<t-perforce-admin,Perforce repository rendszergazdák>>
** <<t-postmaster,Postamesterek>>
** <<t-refadm,A referencia rendszerek rendszergazdái>>
** <<t-webmaster,Webmesterek>>

'''''

[[t-core]]
=== FreeBSD Core Team <core@FreeBSD.org>

A FreeBSD Core Team képezi a Projekt "`igazgatótanácsát`". A Projekt általános céljainak meghatározásáért és a FreeBSD egyes területeinek kézbentartásáért felelõs. A Core Team tagjait a Projekt aktív fejlesztõi választják.

* {jhb}
* {kib}
* {brooks}
* {wilko}
* {imp}
* {pav}
* {cperciva}
* {hrs}
* {rwatson}

[[t-doceng]]
=== FreeBSD Documentation Engineering Team <doceng@FreeBSD.org>

A FreeBSD Documentation Engineering Team a Dokumentációs Projekt résztvevõi számára jelöli ki a dokumentációval kapcsolatos célokat. A link:https://www.FreeBSD.org/internal/doceng/[doceng szabadalomlevele] nagy részletességgel ismerteti a Documentation Engineering Team feladatait és kötelezettségeit.

* {nik}
* {blackend}
* {hrs}
* {keramida}

[[t-portmgr]]
=== FreeBSD Port Management Team <portmgr@FreeBSD.org>

A FreeBSD Port Management Team elsõdleges feladata gondoskodni arról, hogy a portokon dolgozó fejlesztõi közösség egy mûködõ, stabil és naprakész Portgyûjteményt nyújtson a felhasználók számára. A másodlagos feladata a committerek és a Portgyûjteményen dolgozó fejlesztõk közti koordináció. A link:https://www.FreeBSD.org/portmgr/charter/[portmgr szabadalomlevele] részleteiben mutatja be a Port Management Team kötelességeit és felelõsségeit.

* {marcus}
* {erwin}
* {linimon}
* {pav}
* {itetcu}
* {flz}
* {miwi}

'''''

[[t-re]]
=== Elsõdleges Release Engineering Team <re@FreeBSD.org>

Az Elsõdleges Release Engineering Team a FreeBSD hivatalos kiadásainak idõbeosztását határozza meg és hirdeti ki. Több más tennivaló mellett bejelenti a kód befagyasztását és karbantartja a `RELENG_*` ágakat. A link:https://www.FreeBSD.org/releng/charter/[releng szabadalomlevele] részletesen ismerteti az Elsõdleges Release Engineering Team feladatait és kötelezettségeit.

* {kib}
* {blackend}
* {mux}
* {gnn}
* {hrs}
* {kensmith} (Vezetõ)
* {rwatson}
* {dwhite}
* {bz}

[[t-re-amd64]]
=== FreeBSD/amd64 Release Engineering Team <re-amd64@FreeBSD.org>

A FreeBSD/amd64 Release Engineering Team a FreeBSD/amd64 platform egyéni kiadási problémáiért felelõs.

* {obrien}

[[t-re-ia64]]
=== FreeBSD/ia64 Release Engineering Team <re-ia64@FreeBSD.org>

A FreeBSD/ia64 Release Engineering Team a FreeBSD/ia64 platform egyéni kiadási problémáiért felelõs.

* {marcel}

[[t-re-x86]]
=== FreeBSD/i386 Release Engineering Team <re-x86@FreeBSD.org>

A FreeBSD/i386 Release Engineering Team a FreeBSD/i386 platform egyéni kiadási problémáiért felelõs.

* {rwatson}

[[t-re-pc98]]
=== FreeBSD/pc98 Release Engineering Team <re-pc98@FreeBSD.org>

A FreeBSD/pc98 Release Engineering Team a FreeBSD/pc98 platform egyéni kiadási problémáiért felelõs.

* {nyan}

[[t-re-ppc]]
=== FreeBSD/ppc Release Engineering Team <re-ppc@FreeBSD.org>

A FreeBSD/ppc Release Engineering Team a FreeBSD/ppc platform egyéni kiadási problémáiért felelõs.

* {grehan}
* {marcel}

[[t-re-sparc64]]
=== FreeBSD/sparc64 Release Engineering Team <re-sparc64@FreeBSD.org>

A FreeBSD/sparc64 Release Engineering Team a FreeBSD/sparc64 platform egyéni kiadási problémáiért felelõs.

* {jake}
* {phk}
* {tmm}
* {obrien}
* {kensmith}
* {rwatson}

'''''

[[t-donations]]
=== Donations Team <donations@FreeBSD.org>

A FreeBSD Donations Team köteles a felajánlott adományokra válaszolni, kiépíteni az adományozási irányelveket és módszereket és koordinálni az érkezõ adományokat a FreeBSD közösségén belül. A Donations Team munkájáról részletesebb leírást a link:https://www.FreeBSD.org/donations/[FreeBSD Donations Liaison] oldalon találhatunk.

* {gjb}
* {wilko}
* {gahr}
* {pgollucci}
* {skreuzer}
* {obrien}
* {trhodes}
* Daniel Seuffert <ds@FreeBSD.org>
* {rwatson}

[[t-marketing]]
=== Marketing Team <marketing@FreeBSD.org>

Médiakapcsolat, marketing, interjúk, információk.

* Steven Beedle <steven@zna.com>
* Denise Ebery <denise@ixsystems.com>
* Deb Goodkin <deb@FreeBSD.org>
* {jkoshy}
* Dru Lavigne <dlavigne6@sympatico.ca>
* {mwlucas}
* {imp}
* Kris Moore <kris@pcbsd.org>
* {murray}
* Matt Olander <matt@FreeBSD.org>
* Jeremy C. Reed <reed@reedmedia.net>
* {rwatson}

[[t-secteam]]
=== Security Team <secteam@FreeBSD.org>

A FreeBSD Security Team (a Security Officer irányításával) azért felelõs, hogy felhívja a közösség figyelmét az src és ports forrásokat érintõ hibákra és biztonsági kockázatokra, valamint összegyûjtse és publikálja a FreeBSD biztonságos futtatásához szükséges információkat. Továbbá felelõs a FreeBSD-t érintõ biztonsági hibák kijavításáért és velük kapcsolatos biztonsági figyelmeztetések kiadásáért. A link:https://www.FreeBSD.org/security/charter/[FreeBSD Security Officer szabadalomlevele] nagyobb részletességgel írja le a Security Officer feladatait és kötelezettségeit.

* {qingli}
* {delphij}
* {remko}
* {simon} (Officer helyettes)
* {philip}
* {cperciva} (Officer)
* {csjp}
* {stas}
* {rwatson} (Core Team kapcsolattartó)
* {miwi}
* {bz}

[[t-vendor]]
=== Vendor Relations Team <vendor-relations@FreeBSD.org>

Kapcsolattartás a terjesztõkkel.

* {gioria}
* {jmg}
* {rik}
* {philip}
* {hmp}
* {marks}
* {murray}

'''''

[[t-core-secretary]]
=== Core Team titkár <core-secretary@FreeBSD.org>

A FreeBSD Core Team titkára a Core Team egy szavazati joggal nem rendelkezõ tagja, aki a Core Team munkájának dokumentálásáért, a tanács teendõinek nyomon követéséért és a külsõ tagokkal való kapcsolattartásért felel, továbbá egy új committer felvételekor õ közvetíti az új hozzáférések iránti igényt az adminisztrátorok felé. A Core Team titkár szintén köteles havi rendszerességû helyzetjelentéseket küldeni a FreeBSD fejlesztõi közössége felé, amelyben röviden összegzi a Core Team legutóbbi döntéseit és tevékenységét.

* {philip}

[[t-portmgr-secretary]]
=== Port Management Team titkár <portmgr-secretary@FreeBSD.org>

A FreeBSD Port Management Team titkára a Port Management Team egy szavazati joggal nem rendelkezõ tagja, aki a portmgr munkáját dokumentálja és nyomonköveti a a szavazásokat, illetve a többi team, különösen a Core és az adminisztrátorok felé közvetít azokat. A Port Management Team titkár szintén köteles havi rendszerességû helyzetjelentéseket küldeni a FreeBSD fejlesztõi közösség felé, amelyben összegzi a Port Management Team legutóbbi döntéseit és tevékenységét.

* {tabthorpe}

[[t-secteam-secretary]]
=== Security Team titkár <secteam-secretary@FreeBSD.org>

A FreeBSD Security Team titkára gondoskodik róla, hogy a Security Team felé érkezõ leveleket rendesen megválaszolják. Visszaigazolja a levelek megérkezését és nyomon követi a folyamatot a Security Team keretein belül. Szükség esetén kapcsolatba lép a Security Team tagjaival, hogy tájékoztassa õket a folyamatban lévõ események fejleményeirõl. Jelenleg a Security Team titkára nem foglalkozik a Security Officer Team feladataival.

* {remko}

'''''

[[t-accounts]]
=== Hozzáférések <accounts@>

A hozzáférésekkel foglalkozó csoport tagjai a Projekten belül az új committerek hozzáféréseinek létrehozásáért felelõsek. Az új hozzáférések iránti kérelmeket addig nem teljesítik, amíg a felelõs szerv azt jóvá nem hagyja.

* {markm}
* {simon}
* {kensmith}
* {dhw}

[[t-backups]]
=== Biztonsági mentések <backups@>

A biztonsági mentésekért felelõs rendszergazdák kezelik a FreeBSD klaszter biztonsági mentéseit.

* {simon}
* {kensmith}
* {dhw}

[[t-bugmeister]]
=== Bugmeisterek és GNATS rendszergazdák <bugmeister@FreeBSD.org>

A bugmeisterek és GNATS rendszergazdák a hibajelentéseket tároló adatbázis megfelelõ mûködéséért felelõsek. A bejegyzéseknek megfelelõen kategorizálva kell lenniük és az adatbázisban nem lehetnek érvénytelen bejegyzések.

* {gavin}
* {linimon}
* {remko}
* {vwe}

[[t-clusteradm]]
=== Klaszter rendszergazdák <clusteradm@>

A klaszter rendszergazdái a Projekt elosztott munkájában és a szinkronizált kommunikációjában fontos szerepet betöltõ számítógépeket tartják karban. Elsõsorban azokból az emberekbõl áll, akik fizikailag is hozzáférnek ezekhez a szerverekhez. A Projekt infrastruktúrájával és az újabb számítógépek beállításával kapcsolatos kérelmeket ennek a csoportnak kell címezni.

* {bhaga}
* {brd}
* {bz}
* {kensmith}
* {peter}
* {sbruno}
* {simon}

[[t-dcvs]]
=== doc/www CVS repository megbízottak <dcvs@FreeBSD.org>

A doc/www CVS repository megbízottjai a CVS eszközök nélkül, közvetlenül módosíthatják a repositoryt. Az õ felelõsségük, hogy a repositoryval kapcsolatban felmerülõ problémákat gyorsan orvosolják. A doc/www CVS repository megbízottjainak joga van visszaállítani egy commit mûveletet, ha ez szükséges a technikai probléma megoldásához. A repo-copy iránti kérelmeket is õk kezelik.

* {joe}
* {kuriyama}
* {markm}
* {simon}

[[t-pcvs]]
=== ports CVS repository megbízottak <pcvs@FreeBSD.org>

A ports CVS repository megbízottjai a CVS eszközök nélkül, közvetlenül módosíthatják a repositoryt. Az õ felelõsségük, hogy a repositoryval kapcsolatban felmerülõ problémákat gyorsan orvosolják. A ports CVS repository megbízottaknak joga van visszaállítani egy commit mûveletet, ha ez szükséges a technikai probléma megoldásához. A repo-copy iránti kérelmeket is õk kezelik.

* {marcus}
* {joe}
* {kuriyama}
* {markm}
* {simon}

[[t-ncvs]]
=== src CVS repository megbízottak <ncvs@FreeBSD.org>

Az src CVS repository megbízottjai a CVS eszközök nélkül, közvetlenül módosíthatják a repositoryt. Az õ felelõsségük, hogy a repositoryval kapcsolatban felmerülõ problémákat gyorsan orvosolják. Az src CVS repository megbízottjainak joga van visszaállítani egy commit mûveletet, ha ez szükséges a technikai probléma megoldásához. A repo-copy iránti kérelmeket is õk kezelik.

* {joe}
* {kuriyama}
* {markm}
* {simon}
* {peter}

[[t-cvsup-master]]
=== A CVSup tükrözések koordinátorai <cvsup-master@FreeBSD.org>

A CVSup tükrözések koordinátorai hangolják össze a tükörszerverek rendszergazdáinak munkáit, ezáltal gondoskodnak róla, hogy a tükrözésekrõl a FreeBSD mindig naprakész verziója legyen elérhetõ és elég kapacitással rendelkezzenek ahhoz, hogy a nagyobb frissítéseket képesek legyenek követni. Emellett arra is ügyelnek, hogy a közösség könnyen elérhesse a legközelebbi CVSup tükrözést.

* {kuriyama}
* {jdp}
* {kensmith}

[[t-dnsadm]]
=== DNS rendszergazdák <dnsadm@>

A DNS rendszergazdák a névfeloldásért és a hozzá kapcsolódó szolgáltatásokért felelõsek.

* {billf}
* {dg}
* {ps}
* {kensmith}
* {peter}

[[t-mirror-admin]]
=== Az FTP/WWW tükrözések koordinátorai <mirror-admin@FreeBSD.org>

Az FTP/WWW tükrözések koordinátorai hangolják össze a tükörszerverek rendszergazdáinak munkáját, így gondoskodnak róla, hogy a tükrözésekrõl mindig a FreeBSD naprakész verziója legyen elérhetõ, és elegendõ kapacitással rendelkezzenek a nagyobb frissítések követéséhez. Továbbá felügyelik, hogy a közösség mindig könnyen elérhesse a legközelebbi FTP/WWW tükrözést.

* {kuriyama}
* {kensmith}

[[t-perforce-admin]]
=== Perforce repository rendszergazdák <perforce-admin@FreeBSD.org>

A Perforce repository rendszergazdák a FreeBSD Perforce repository karbantartásáért és az új Perforce hozzáférések létrehozásáért felelnek. A nem committer felhasználók részére igényelt hozzáféréseket feléjük kell küldeni.

* {scottl}
* {kensmith}
* {gordon}
* {rwatson}
* {peter}
* {dhw}

[[t-postmaster]]
=== Postamasterek <postmaster@FreeBSD.org>

A postmasterek felelnek azért, hogy az e-mailek mindig megfelelõen kézbesítésre kerüljenek a committerek felé, illetve, hogy a levelezési listák rendesen mûködjenek, valamint gondoskodjanak a troll-, spam- és vírusszûrésrõl.

* {jmb}
* {brd}
* {dhw}

[[t-refadm]]
=== A referencia rendszerek rendszergazdái <refadm@>

A referencia rendszerek rendszergazdái felelõsek a FreeBSD klaszterben található referencia rendszerek megfelelõ mûködtetéséért, frissítéséért és karbantartásáért. Ezek a rendszerek minden committer számára elérhetõek.

* {jake}
* {billf}
* {markm}
* {simon}
* {obrien}
* {ps}
* {kensmith}
* {peter}
* {dhw}

[[t-webmaster]]
=== Webmesterek <webmaster@FreeBSD.org>

A webmesterek az elsõdleges FreeBSD webszerver megfelelõ mûködéséért felelõsek. Hozzájuk tartozik a webszerver konfigurációja, a CGI scriptek, a weboldal és a levelezési listák keresése. A webbel kapcsolatos minden technikai dolog a webmesterek felügyelete alá esik, kivéve a dokumentációs hibákat.

* {nik}
* {kuriyama}
* {simon}
* {jesusr}
* {wosch}
