---
title: "Группа управления портами"
sidenav: about
---

include::shared/ru/urls.adoc[]
include::shared/authors.adoc[]

= Группа управления портами

Группа управления портами FreeBSD (которую также называют кратко `portmgr` из-за соответствующего адреса электронной почты) отвечает за вопросы, имеющие отношение к http://www.FreeBSD.org/ports[Коллекции Портов FreeBSD].

== link:charter[Устав]

Описаны цели, права и ответственность этой группы. Содержание этого документа согласовано с Управляющим советом FreeBSD.

== link:policies[Правила]

Описаны текущие правила, которым следует группа для реализации своих задач.

== link:qa[Работы по контролю качества]

Взгляд изнутри на те усилия, которые предпринимаются для обеспечения максимально качественной работы Коллекции Портов.

== Участники группы

portmgr@FreeBSD.org: {portmgr-members}

Секретарь: {erwin}

== Документация, имеющая отношение к делу

* link:{porters-handbook}[Руководство по созданию портов FreeBSD] +
Общее руководство для коммиттеров портов FreeBSD, в котором присутствует как техническая информация, так и рекомендации по организации работ.
* http://pointyhat.FreeBSD.org[Кластер построения портов FreeBSD] +
Эти машины постоянно строят пакаджи для всех возможных комбинаций релизов ОС и процессорных архитектур (по нашей терминологии, `сред построения`) и генерируют протоколы ошибок, отражающие проблемы, которые встретились в процессе построения.
* Процедуры построения пакаджей FreeBSD +
Описывает техническую организацию кластера построения.
* Подготовка релизов FreeBSD для пакаджей сторонних разработчиков +
Описывает подходы, используемые группой подготовки релизов FreeBSD для создания высококачественного набора пакаджей, подходящего для размещения на носителях с официальными релизами. Особое внимание уделено тому, как подготовить пакаджи для размещения на носителях и как проверить целостность набора пакаджей.
* {committers-guide}[Руководство коммиттера FreeBSD] +
Включает описание правил и проблем, которые представляют особый интерес для коммиттеров, занимающихся деревом портов.
* link:{pr-guidelines}[Рекомендации по работе с сообщениями о проблемах] +
Хотя этот документ в первую очередь адресован коммиттерам FreeBSD, он должен быть прочитан пользователями, интересующимися тем, как эффективнее всего привлечь внимание к своим PR.
