---
title: "Устав Группы управления портами"
sidenav: about
--- 

= Устав Группы управления портами

Коллекция Портов FreeBSD является продуктом, предназначенным в большей степени и в первую очередь конечным пользователям FreeBSD. Команда управления портами (portmgr) представляет собой группу, отвечающую за ведение разработок в этой области. Её сотрудники назначаются Управляющим советом FreeBSD (core).

В основном группа portmgr отвечает за то, чтобы в результате работы сообщества разработчиков портов FreeBSD имеющаяся коллекция портов была функциональной, стабильной, актуальной и обладала полным набором возможностей. Её второй задачей является координация работ коммиттеров и разработчиков, работающих над системой портов.

Группа управления портами исполняет следующие обязанности:

* Обеспечивает целостность Коллекции Портов, управляя изменениями, вносимыми в раздел `ports` CVS-хранилища FreeBSD. Сюда включается прямое управление определёнными ключевыми файлами, проведение тестовых построений в случае планирования больших изменениях и исполнение роли арбитра по отношению к другим изменениям.
* Поддержка автоматизированного http://pointyhat.FreeBSD.org[кластера построения пакаджей] и организация доступности для сгрузки получающихся пакаджей пользователями FreeBSD.
* Работает совместно с группой информационной безопасности FreeBSD для гарантии того, что проблемы в защите обнаружены и устраняются своевременно.
* Работает с коммиттерами портов и документации FreeBSD над актуализацией соответствующей документации.
* В той мере, которая вообще возможна в рамках добровольного проекта, обеспечение соблюдения прав авторов, чьи работы помещены в Коллекцию Портов.
* Выступать в роли ведущего арбитра в обсуждениях между членами сообщества FreeBSD, такими как мэйнтейнеры и коммиттеры.
* Управление доступом на выполнение изменений в CVS в дереве портов. Все утверждения новых коммиттеров должны посылаться на адрес admins@ с копией для core@; они должны быть подписаны PGP-ключом.
* Разработка руководящих указаний и политик, отражающих права и обязанности мэйнтейнеров и коммиттеров портов.
* Помощь в приоритетизации будущих направлений развития Коллекции Портов.

Кроме своих обязанностей, Группа управления портами может предпринимать любые действия, которые, по мнению Группы, пойдут на пользу управления коллекцией портов.

Пожалуйста, обратитесь к link:../policies[Своду правил группы портов] для выяснения полного списка текущих правил, которые предназначены для реализации этих задач.

Этот Устав контролируется Управляющим Советом FreeBSD. Он действует, пока не будет модифицирован или отменён Правлением; любые изменения в этот Устав должны согласовываться с Правлением.
