# $FreeBSD: www/en/releases/3.5R/Makefile,v 1.2 2000/11/07 04:05:34 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml notes.sgml errata.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
