---
title: "Hewlett-Packard donates blade cluster to FreeBSD"
sidenav: about
loadPress: false
---

= Hewlett-Packard donates blade cluster to FreeBSD

*The FreeBSD Foundation received a donation of a blade system from Hewlett-Packard for use as a third-party software build cluster. This 20-node HP BladeSystem cluster triples the speed of the build process for i386 packages.*

_"With this generous donation from HP, we are able to continuously produce up-to-date packages from more than 13000 ports of third-party software available in the FreeBSD Ports Collection, at about three times the rate of the previous hardware cluster,"_ said Kris Kennaway, member of the FreeBSD Port Management Team.

_"This directly benefits the users of FreeBSD through the rapid availability of new and updated software packages, and through the increased testing and QA of FreeBSD that the new hardware allows."_

_"We at HP recognize the important role of FreeBSD in the Internet's global network infrastructure, and we are happy that the HP BladeSystem cluster can contribute to the on-going success of the FreeBSD Foundation,"_ said Mark Potter, vice president of the Hewlett-Packard BladeSystem division.

_"They're just standard i386 systems, architecturally, with a very nice ssh- and serial-based management server,"_ said Kennaway, who maintains the FreeBSD Ports cluster.

Kennaway said FreeBSD has a few dozen other machines scattered around the globe for package builds. A big concentration of sparc machines hosted by Hiroki Sato in Japan include some large multiprocessor e4500's (10, 12 and 14 CPUs) that have been extremely valuable for SMP testing. Also, a couple of machines hosted by ISC, an amd64 hosted by Scott Long, three i386 machines at Yahoo! Korea, and sometimes Kennaway's own machines in Canada are used for the official package builds.

The HP BladeSystem cluster is hosted at the Yahoo! datacenter in the San Francisco Bay area. In addition to Kennaway, Paul Saab and Peter Wemm from the FreeBSD project, and John Cagle from HP helped with blade system setup.

== About The FreeBSD Project

The FreeBSD Project provides an up-to-date and scalable modern operating system that offers high-performance, security, and advanced networking for personal workstations, Internet servers, routers, and firewalls. The FreeBSD packages collection includes popular software like Apache Web Server, Gnome, KDE, X.org X11 Window System, Python, Mozilla, and over 13,000 software suites. FreeBSD can be found on the Internet at http://www.FreeBSD.org/[http://www.FreeBSD.org].

== More Information:

FreeBSD Ports webpage +
http://www.freebsd.org/ports/[http://www.FreeBSD.org/ports/] +
 +
FreeBSD Package building logs and errors webpage +
http://pointyhat.freebsd.org/errorlogs/
