---
title: "FreeBSD Press Release: April 22, 1999"
sidenav: about
loadPress: false
---

= FreeBSD Press Release: April 22, 1999

== FreeBSD Used to Generate Spectacular Special Effects

*Concord, CA, April 22, 1999*: 32 Dual-Processor FreeBSD systems were used to generate a large number of special effects in the cutting edge Warner Brothers film, _The Matrix_.

Manex Visual Effects used 32 Dell Precision 410 Dual P-II/450 Processor systems running FreeBSD as the core CG Render Farm. Charles Henrich, the senior systems administrator at Manex, says, "We came to a point in the production where we realized we just did not have enough computing power on our existing SGI infrastructure to get through the 3-D intensive sequences. It was at that point we decided on going with a FreeBSD based solution, due to the ability to get the hardware quickly as well as the reliability and ease of administration that FreeBSD provides us. Working with Dell, we purchased 32 of these systems on a Wednesday, and had them rendering in production by Saturday afternoon. It was truly an amazing effort on everyone's part, and I don't believe it would've been possible had we chosen to go with any other Operating System solution."

The FreeBSD operating system is a powerful, completely open-source system based on the Berkeley Software Distribution of UNIX. It is available free of charge from numerous Internet websites and also on CD-ROM from Walnut Creek CDROM, and includes thousands of ported applications including 3-D graphics rendering and many other equally powerful tools. FreeBSD is optimized for use on the Intel x86 processor line that is the heart of today's versatile commodity personal computers. Infinitely customizable, FreeBSD is at the heart of such Internet powerhouse applications as Yahoo! and U.S. West because it is unencumbered by commercial license restrictions and can be copied and modified freely.

For more information on FreeBSD, visit http://www.FreeBSD.org/ and http://www.wccdrom.com/. For more information about Manex Visual Effects, please visit http://www.mvfx.com/ .
