---
title: "FreeBSD Press Release: April 29, 1999"
sidenav: about
loadPress: false
---

= FreeBSD Press Release: April 29, 1999

== Complete XML Development System Integrated with FreeBSD

*Concord, CA, April 29, 1999*: Included with FreeBSD 3.1 is a complete, integrated SGML/XML development system that installs with a simple, easy to use command sequence.

FreeBSD's Ports system and multitasking architecture makes it easy for an SGML/XML developer to download and install all the latest versions of the tools and reference material he needs to develop SGML and XML formatting languages and documents, and the online Internet mailing lists help him learn and keep up-to-date with the evolving XML implementation.

FreeBSD is a full-featured open-source operating system which runs on virtually all Intel x86-based personal computers. Its 580 page "Handbook" has recently been completely done over into DocBook format, and it is a living example of an evolving document built with SGML tools. The Handbook is available on the Internet at:

* http://www.FreeBSD.org/handbook/
* ftp://ftp.FreeBSD.org/pub/FreeBSD/doc/

The FreeBSD Documentation Project is also making available the "FreeBSD Documentation Project Primer" to make it as painless as possible for newcomers to contribute to the FreeBSD Documentation Set. Much of the information in the primer is appropriate to all SGML/XML users, and is freely available. The primer, which is constantly being updated by the Documentation Project team, can be found at:

* http://www.FreeBSD.org/tutorials/primer/

=== Features of the Document Project SGML/XML System include:

* James Clark's Jade 1.2.1 and SP suite version 1.3.3, enabling formatting and validation of SGML and XML documents.
* A complete set of 19 ISO SGML character set entities
* The DocBook (v2.4.1, v3.0, v3.1), HTML (all versions), and LinuxDoc Document Type Definitions (DTD)
* Norm Walsh's Modular DocBook Stylesheets, allowing fine control over the appearance and formatting of DocBook documents.
* Emacs and XEmacs, in conjunction with the PSGML extension package, provide a customizable industrial-strength SGML editing solution.
* The teTeX-beta package in conjunction with the JadeTeX macros make it possible to convert DocBook documents to DVI, Postscript, and PDF formats with embedded hyperlinks.
* Additional SGML-aware programs and utilities can be found in the FreeBSD ports system.

The FreeBSD Documentation Project is actively migrating from the LinuxDoc DTD to the DocBook DTD, and has been providing feedback to the DocBook maintainers regarding new features and possible implementations for the past year. For more information about the FreeBSD Documentation Project, please contact the freebsd-doc@FreeBSD.org mailing list.

The FreeBSD operating system is available on the Internet from the master FreeBSD website and from various mirror systems around the world, and it can also be obtained on convenient CDROMs from Walnut Creek CDROM. Information on all of these options is available through:

* http://www.FreeBSD.org/
* http://www.wccdrom.com/
