---
title: "FreeBSD Press Release: June 7, 1999"
sidenav: about
loadPress: false
---

= FreeBSD Press Release: June 7, 1999

== BSD Community Welcomes Apple's New Open Source Operating System

*Concord, CA, June 7, 1999*: Today, at the start of the UNIX development community's annual Usenix convention, operating system influentials embraced Apple Computer's Darwin (www.apple.com/darwin) as a new member of the Berkeley Software Distribution (BSD) operating system family.

"We're very pleased to have Apple's participation in the BSD community," said Jordan Hubbard, chairman of the USENIX convention's Freenix track and co-founder of the FreeBSD Project. "As more smart businesses discover the incredible free resource that is BSD software, they'll realize that contributing to open source development is in their best interest."

According to Herb Peyerl of the NetBSD Project, "Our interaction with Apple on the Darwin project has been extremely rewarding for NetBSD and is the kind of open cooperation of which we would like to see more."

"Leveraging the twenty-year BSD heritage allows Apple developers to concentrate on adding a unique user experience to the solid, robust foundation of the BSD code," according to Avie Tevanian, Apple Computer's senior vice president of Software Engineering. "We believe that by embracing the open source movement with our Darwin software, the result will be better products for millions of Mac customers worldwide. The BSD code in Darwin is an essential part of our operating system strategy."

This type of reciprocation is a return to the original software development model that was universal in the early days of computing, before PCs. Wilfredo Sanchez, technical lead for the Darwin Project, will speak on Darwin at this week's Freenix track, a series of programs at Usenix devoted exclusively to this sort of open source software development.

=== About NetBSD and FreeBSD

NetBSD and FreeBSD are open source operating systems based on the last public release of BSD UNIX, 4.4BSDLite2. Each effort has kept up with the latest technologies in processors and software architectures. While having different priorities, the BSD development teams share a friendly competitive rivalry, spurring each other on to produce better product for their worldwide users. Over the twenty years of development, a huge base of software has been developed around BSD -- including much of the Internet infrastructure -- enabling the OS to be used effectively in almost any computing application. The open development model means there are no secrets, creating a worldwide understanding of the code which enables BSD developers to build on the efforts of prior developers without the hassles endemic to proprietary operating systems and applications.

=== For More Information, Contact:

The FreeBSD Project +
Concord, California +
925-682-7859 +
freebsd-questions@FreeBSD.org +
http://www.FreeBSD.org +

The NetBSD Project +
C/O Charles M. Hannum +
81 Bromfield Rd, #2 +
Somerville, MA 02144 +
mindshare@netbsd.org +
http://www.netbsd.org +
