---
title: "ウェブ上の情報"
sidenav: docs
---

= ウェブ上の情報

== In the real world...

=== link:../../press/[FreeBSD in the Press]

FreeBSD に関する報道記事です。

== ニュースグループ

以下のニュースグループでは FreeBSD ユーザに適した議論が行われています。

* link:news:comp.unix.bsd.freebsd.announce[comp.unix.bsd.freebsd.announce] (moderated)
* link:news:comp.unix.bsd.freebsd.misc[comp.unix.bsd.freebsd.misc]
* link:news:comp.unix.bsd.misc[comp.unix.bsd.misc]

== その他のリソース

=== https://www.freebsdnews.com/[FreeBSDNews.com]

FreeBSDNews.com は、FreeBSD コミュニティにおける最新の出来事が書かれているブログです。 投稿される記事は、ニュース、チュートリアルなどです。

=== https://www.bsdnow.tv/[BSD Now]

BSD Now は、BSD ファミリのオペレーティングシステムについて、 世界に毎週配信しているビデオポッドキャストです。 最新の開発の概要だけでなく、機能についてのインタビュー、 チュートリアルそして、 リスナーから寄せられた問題に対するヘルプも提供します。

=== https://bsdmag.org/[BSD MAG]

BSD MAG は、BSD およびオープンソースのソリューションについて、 初心者および経験豊かなユーザ両方を対象としています。 無料で毎月発行されています。

=== http://fxr.watson.org/[ソースコード]

ソースコードに手を入れてみたいという方のために、ここに FreeBSD _カーネル_ のソースコードをハイパーテキスト化したものがあります。 これは、Robert Watson の好意により提供されています。

=== https://forums.freebsd.org[FreeBSD フォーラム]

FreeBSD の公式フォーラムで、FreeBSD や FreeBSD ファンのためのフォーラムを提供しています。
