# $FreeBSD: www/en/marketing/Makefile,v 1.2 2005/07/24 16:24:41 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
