# The FreeBSD Russian Documentation Project
#
# $FreeBSDru: frdp/www/ru/community/Makefile,v 1.1 2005/10/31 13:38:09 gad Exp $
# $FreeBSD$
#
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.xml mailinglists.xml newsgroups.xml webresources.xml

XMLDOCS+=	social::${XML_EVENTS_EVENTS}:

.include "${DOC_PREFIX}/share/mk/web.site.mk"
