# The FreeBSD Russian Documentation Project
#
# $FreeBSDru: frdp/www/ru/community/Makefile,v 1.1 2005/10/31 13:38:09 gad Exp $
# $FreeBSD: www/ru/community/Makefile,v 1.1 2005/11/08 18:22:23 bvs Exp $
#
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.sgml mailinglists.sgml newsgroups.sgml webresources.sgml

XMLDOCS+=	social::${XML_EVENTS_EVENTS}:

.include "${WEB_PREFIX}/share/mk/web.site.mk"
