# $FreeBSD: www/en/releases/5.5R/Makefile,v 1.1 2006/01/26 00:10:24 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	todo.sgml approvals.sgml
DOCS+=	schedule.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
