# $FreeBSD: www/ja/news/Makefile.inc,v 1.1 2000/05/12 15:34:39 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

WEBBASE?=	/data/ja/news
WEB_PREFIX?=	${.CURDIR}/../../..
