# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/releases/Makefile.inc,v 1.3 2000/11/10 17:04:53 phantom Exp $
# Original version: 1.5

WEBBASE?=	/data/ru/releases
WEB_PREFIX?=	${.CURDIR}/../../..
