# $Id: Makefile,v 1.1.1.1 1997-11-23 22:23:07 max Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

#DOCS=	announce.sgml notes.sgml security.sgml
DOCS=	notes.sgml security.sgml

.include "../../../web.mk"
