# $FreeBSD$
# $FreeBSDru: frdp/www/ru/security/Makefile,v 1.2 2000/10/27 11:26:12 phantom Exp $
 
.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=   security.sgml
 
INDEXLINK=security.html
 
.include "../web.mk"
