---
title: "FreeBSD 3.1 Errata Notes"
sidenav: download
--- 

= FreeBSD 3.1 Errata Notes

....
The file 
ERRATA.TXT contains post-release ERRATA for 3.1 and should always
be considered the definitive place to look *first* before reporting
a problem with this release.  This file will also be periodically
updated as new issues are reported so even if you've checked this
file recently, check it again before filing a bug report.  Any
changes to this file are also automatically emailed to:

    freebsd-stable@FreeBSD.org

For all FreeBSD security advisories, see:

ftp://ftp.FreeBSD.org/pub/FreeBSD/CERT/

For the latest information.

---- Security Advisories:

Current active security advisories for 3.1:     None

---- System Update Information:

o  Some packages, like netscape, will fail to install if chosen
   at initial system installation time, in some cases claiming
   that the "compat22" distribution needs to be installed even
   though it has, indeed, been installed.


Fix: The problem here is that though the compatibility a.out libraries
     may have been installed from compat22 and as part of the XFree86
     distribution, the a.out library (ldconfig) cache has not yet been
     built given that this doesn't happen until the system has booted
     completely at least once.  This causes packages which require the
     old a.out libraries (like netscape) to get confused if they're
     installed before that has occurred.  To work around the problem,
     simply complete the installation as normal and come up fully,
     then re-run /stand/sysinstall (or use the pkg_add(1) command
     directly) to re-install the failing package(s).


o  Kernel change information is not saved in the new kernel, even
   though this is claimed to work in the docs.


Fix: The change information is being written out, in fact, but to the
     wrong location.  move /kernel.config to /boot/kernel.conf (if it
     exists, otherwise there were no changes to save) and add the
     following lines to /boot/loader.rc:

        load /kernel
        load -t userconfig_script /boot/kernel.conf
        autoboot 5

     This will cause the kernel change information to be read in and
     used properly (and you just learned a little about the new 3-stage
     loader in the process, so the exercise wasn't a total loss).


o  DOS installation fails when you actually follow the instructions
   to install stuff under C:\FREEBSD\BIN\... and so on.


Fix: The instructions are correct but the code was wrong in 3.1-RELEASE,
     sysinstall looking instead directly under C:\ (e.g. C:\BIN\...)
     or under C:\RELEASES\ (C:\RELEASES\BIN\... and so on).  Fixed
     in 3.1-STABLE.
....

link:../../[Release Home]
