---
title: "Dépôt CVS"
sidenav: developers
---

include::shared/fr/urls.adoc[]

= Dépôt CVS

== Subversion

http://www.FreeBSD.org/cgi/man.cgi?cvs[CVS] (Concurrent Version System) est l'outil que nous utilisons pour pouvoir gérer le code source. Tous les changements (accompagnés des explications de chacune des modifications) depuis FreeBSD 2.0 jusqu'à la version actuelle sont stockés dans la base CVS. Ils peuvent être facilement consultés via l'interface web mentionnée ci-dessus. Pour obtenir une copie complète de la base CVS de FreeBSD ou de n'importe quelle branche de la base CVS, utilisez:

* link:{handbook}#cvsup[CVSup] si vous désirez un accès à la demande, nécessitant peu de ressources et utilisant un utilitaire propre (écrit en Modula-3, rien que ça).
* link:{handbook}#anoncvs[anoncvs] si vous désirez un accès à la demande nécessitant davantage de ressources que cvsup (en terme d'octets transférés et de disponibilité du CPU) mais plus simple d'utilisation pour des petites parties de l'arbre CVS et qui ne demande rien de plus que les outils CVS livrés directement avec FreeBSD.
* link:{handbook}#ctm[CTM] si vous recherchez un accès nécessitant très peu de ressources, et en mode batch (en fait, des patches par courrier électronique).
* L'http://cvsweb.FreeBSD.org/[interface web] si vous voulez simplement explorer le dépôt CVS à la recherche d'un changement ou d'une révision de fichier spécifique.
* Enfin, si vous disposez d'une grosse bande passante ou si vous préférez/devez utiliser le protocole FTP, vous pouvez faire un miroir du dépôt CVS depuis ftp://ftp.FreeBSD.org/pub/FreeBSD/development/FreeBSD-CVS[ftp.FreeBSD.org].

Des miroirs de l'interface web CVS sont disponibles au http://cvs.freebsd.uwaterloo.ca/cgi-bin/cvsweb.cgi/[Canada], au http://www.jp.FreeBSD.org/cgi/cvsweb.cgi/[Japon], au http://cvsup.pt.FreeBSD.org/cgi-bin/cvsweb/cvsweb.cgi/[Portugal], aux http://cvsweb.FreeBSD.org/[Etats-Unis/Californie] et en http://www.FreeBSD.org.ua/cgi/cvsweb.cgi?cvsroot=freebsd[Ukraine].
