# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.10
#
# $FreeBSD$

#SUBDIR = corp-net-guide
#SUBDIR+= design-44bsd
#SUBDIR+= developers-handbook
#SUBDIR+= faq
#SUBDIR+= fdp-primer
SUBDIR+= handbook
#SUBDIR+= porters-handbook
#SUBDIR+= ppp-primer

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
