---
title: "Центр Пожертвований FreeBSD"
sidenav: about
--- 

= Центр Пожертвований FreeBSD

== Содержание

* <<goal,Цели работы Центра Пожертвований>>
* <<charter,Устав Центра Пожертвований>>
* <<donating,Спонсирование Проекта FreeBSD>>

== Остальные ссылки на пожертвования

* link:wantlist[Список требуемого для Проекта FreeBSD]
* link:donors[Перечень пожертвований для FreeBSD]

[[goal]]
== Цели проекта

Вместе с ростом количества пользователей FreeBSD увеличилось число людей, которые готовы предоставить Проекту материальные или финансовые ресурсы. Центр Пожертвований был создан для упорядочения обработки таких пожертвований своевременно и корректно.

[[charter]]
== Устав Центра Пожертвований

Работа Начальника Центра Пожертвований заключается в поиске и правильном направлении пожертвований в соответствии с общепринятыми правилами. На нём лежат следующие обязанности.

* составлять и поддерживать понятный перечень действий для обработки пожертвований.
* своевременно отвечать на предложения по пожертвованию.
* поддерживать перечень оборудования и ресурсов, требуемых сообществу FreeBSD.
* сопоставлять предложения по пожертвованию с сообществом разработчиков FreeBSD.
* отслеживать пожертвования по всему процессу их предоставления.
* управлять командой из 3-4 человек для постоянного обеспечения своевременности, полноты и корректности ответов на запросы.
* официально приносить благодарности жертвователям за их вклад, когда процесс оформления закончен.
* отслеживать состояния всех займов Проекту.
* предоставлять открытую информацию обо всех пожертвованиях сообществу разработчиков FreeBSD.

[[donating]]
== Пожертвования Проекту FreeBSD

Итак, вы хотите пожертвовать что-то Проекту FreeBSD? Великолепно! Мы сильно надеемся на пожертвования пользователей для выполнения нашей задачи. Пожалуйста, прочтите дальнейшую информацию, чтобы понять, как вступить в контакт с нами относительно вашего пожертвования.

Если вы не знаете, что хотите отдать, взгляните на наш link:wantlist[перечень требуемого]. Мы возьмём любое оборудование из этого списка. Если у вас есть оборудование, которое вы готовы нам передать, читайте дальше.

[[taxcredit]]
=== Налогообложение на пожертвования

В целях налогообложения FreeBSD Foundation может выступать как благотворительная организация. Если вы живёте в Соединённых Штатах, ваше пожертвование при определённых условиях может быть вычтено из начисленной суммы налогов. Если вы хотите подтвердить факт пожертвования в целях налогообложения, пожалуйста, дайте нам знать об этом в момент посылки информации о будущем пожертвовании.

Получить налоговую скидку не так уж просто, как кажется. Пожертвования, которые подлежат вычету, должны быть высланы в адрес Фонда FreeBSD. Затем доброволец из Фонда должен обработать пожертвование и переслать его реальному получателю. Фонд должен также иметь возможность показать, что пожертвование сделано в целях _общественной пользы_. Всё это в целом означает, что, хотя у нас есть разработчики, которые заинтересованы в получении большой коробки ISA-адаптеров из вашего чулана, вы не сможете за них получить налоговый вычет; объём работы, который нужно выполнить для её упаковки, посылки и документирования, гораздо больше её стоимости.

Фонд FreeBSD предоставляет подтверждение на доставку оборудования. Однако он не даст оценки рыночной стоимости оборудования -- на самом деле закон запрещает это делать. Мы рекомендуем выяснить стоимость пожертвований оборудования где-нибудь в другом месте. Так как многое из получаемого оборудования устарело, выяснить рыночную стоимость весьма трудно, так что просим поискать на Ebay или других сайтах, посвящённых бывшему в употреблении оборудованию, суммы, которые платятся за похожее оборудование.

=== Как сделать пожертвование

Одной из целей работы Центра Пожертвований является соотнесение пожертвований и нужд разработчиков, которые могут их использовать. Мы не принимаем любые пожертвования; мы обрабатываем только те, что получают разработчика, могущего этим пожертвованием воспользоваться для улучшения FreeBSD. Это вообще экономит время и помогает жертвователям понять, что их пожертвования действительно поддерживают Проект FreeBSD. Обратной стороной медали является то, что мы должны владеть дополнительной информацией о вашем пожертвовании перед тем, как принять его.

Пожертвования обычно подпадают под одну из трёх категорий:

* <<money,Финансы>>
* <<systems,Компьютеры в комплекте>>
* <<components,Аппаратные компоненты>>

Если у вас есть что-то предложить, не подпадающее ни под одну из этих категорий, не беспокойтесь! Просто обратитесь с вашим предложением к нам на адрес donations@FreeBSD.org. То, что это не обычное предложение, вовсе не значит, что мы им не интересуемся.

[[money]]
=== Финансовая поддержка

Проект FreeBSD напрямую финансовую поддержку не принимает. Для нас её принимает организация-спонсор, http://www.freebsdfoundation.org[Фонд FreeBSD]. Пожалуйста, обратитесь к её сайту для выяснения всех подробностей относительно финансовой поддержки.

[[systems]]
=== Вычислительные системы в комплекте

Проекту FreeBSD всегда требуются компьютеры. Если у вас есть компьютер, который вы можете передать Проекту, пожалуйста, свяжитесь с нами со следующей информацией:

* Аппаратные спецификации: архитектура, материнская плата, процессор, объём дисковой памяти, оперативная память. (Если это компьютер Alpha, пожалуйста, включите выдачу команд SHOW CONFIG, SHOW MEM и SHOW DEV.)
* Работает ли на системе FreeBSD, или она не поддерживается? Если это возможно, приложите выдачу dmesg от программы установки FreeBSD на этой системы.
* Можете ли вы выслать эту систему?
* Ваше физическое расположение. Мы стараемся сделать пересылку максимально простой и недорогой.
* Также укажите, хотите ли вы получить <<taxcredit,налоговые вычеты>> за эту систему. (Заметьте, что не все пожертвования могут получить реальные налоговые вычеты, так как стоимость получения вычета может превысить стоимость пожертвования.)

[[components]]
=== Комплектующие

Если у вас есть оборудование, которое вы можете передать Проекту, пожалуйста, свяжитесь с нами со следующей информацией:

* Описание оборудования: модель, номер по каталогу, производитель и так далее. Если у вас есть точная ссылка на страницу сайта производителя об этом комплектующем, это будет полезным.
* Поддерживается ли в настоящее время FreeBSD это оборудование?
* Какая документация у вас есть? Просто оборудования недостаточно для написания драйвера; авторам драйверов нужна подробная информация о микросхемах от производителя. (Не заботьтесь слишком об этом, если у вас такой документации не окажется, так как её может удастся найти где-то ещё.)
* Можете ли вы прислать эту систему?
* Ваше физическое местоположение. Мы стараемся выполнять пересылки максимально просто и недорого.
* Также укажите, хотите ли вы получить <<taxcredit,налоговые вычеты>> за это оборудование. (Заметьте, что не все пожертвования могут получить реальные налоговые вычеты, так как стоимость получения вычета может превысить стоимость пожертвования.)

=== Что мы делаем с этой информацией

Как только мы получаем описание пожертвования, Центр Пожертвований связывается с сообществом разработчиков и предлагает им этот ресурс. Если у нас есть разработчик, которому понравится это предложение, мы связываем дарителя и получателя напрямую для обсуждения вопросов доставки. Если предложением заинтересовались несколько разработчиков, мы пытаемся выяснить, какой из них сможет использовать ресурс с максимальной пользой для Проекта. Если никто из разработчиков предложением не заинтересовался, мы отклоняем предложение.

Мы стремимся отрабатывать (или отклонять) все пожертвования в течение 7 дней после получения полной информации.
