#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/gnome/docs/Makefile,v 1.2 2004/02/21 16:36:21 andy Exp $
#
# Original revision: 1.13
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq2.sgml
DOCS+=	gnome_porting.sgml
DOCS+=	gnome1_porting.sgml
DOCS+=	gnome2_porting.sgml
DOCS+=	porting.sgml
DOCS+=	bugging.sgml
DOCS+=  volunteer.sgml
DOCS+=	knownissues.sgml
DOCS+=	develfaq.sgml
DOCS+=	example-Makefile.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
