# The FreeBSD Russian Documentation Project
#
# $FreeBSD: www/en/gnome/docs/Makefile,v 1.10 2003/09/18 16:13:26 bland Exp $
# $FreeBSDru: frdp/www/ru/gnome/docs/Makefile,v 1.1 2003/11/02 17:57:31 andy Exp $
#
# Original revision: 1.10

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq2.sgml
DOCS+=	gnome_porting.sgml
DOCS+=	gnome2_porting.sgml
DOCS+=	porting.sgml
DOCS+=	bugging.sgml
DOCS+=  volunteer.sgml
DOCS+=	knownissues.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
