[[_accessibility_handbook]]
=== Руководство по доступности (Accessibility Handbook)

Ссылка: +
link:https://docs.freebsd.org/en/books/accessibility/[Руководство по доступности FreeBSD] URL: link:https://docs.freebsd.org/en/books/accessibility/[]

Контакт: Список рассылки FreeBSD по доступности <freebsd-accessibility@FreeBSD.org> +
Контакт: Alfonso Sabato Siciliano <asiciliano@FreeBSD.org>

В недавних отчётах было анонсировано новое Руководство по доступности и опубликованы его рецензии.
Цель руководства — документировать вспомогательные технологии, доступные во FreeBSD как в базовой системе, так и в коллекции портов.

В течение этого квартала:

* Книга была представлена на саммите разработчиков FreeBSD в Загребе в 2025 году, слайды доступны link:https://docs.google.com/presentation/d/1rnw5fU8KyUCGNqR6gkM5IBdyx8cVVdqigCGmrrd--a4[здесь].
* Книга была опубликована и теперь доступна на веб-сайте FreeBSD в разделе link:https://docs.freebsd.org/en/[Документация] > link:https://docs.freebsd.org/en/books/[Книги] > link:https://docs.freebsd.org/en/books/accessibility/[Руководство по доступности].

В настоящее время руководство описывает вспомогательные технологии, связанные с нарушениями зрения.
Оно является частью проекта по доступности для людей с нарушениями зрения (Vision Accessibility), спонсируемого Фондом FreeBSD.
Руководство структурировано в две части и шесть глав:

. Помощь (Help) — Описывает, как эффективно запрашивать помощь через соответствующие каналы связи FreeBSD.
. Виртуальный терминал (Virtual Terminal) — Документирует функции доступности для людей с нарушениями зрения в виртуальной консоли FreeBSD (man:vt[4]).
. Цвета (Colors) — Объясняет, как настраивать цветовые схемы, включая темы с высокой контрастностью и адаптацию цветов экрана под освещение.
. Плохое зрение (Low Vision) — Описывает инструменты доступности в графических средах рабочего стола для пользователей с плохим зрением, такие как экранные лупы, читаемые шрифты и масштабирование.
. Слепота (Blindness) — Описывает вспомогательные технологии для незрячих пользователей, фокусируясь в первую очередь на программах чтения содержимого экрана (screen readers) и совместимых с ними инструментах.
. Разработка (Development) — Предоставляет ресурсы для разработчиков, чтобы сделать их программное обеспечение доступным, тестировать доступность и улучшить поддержку для пользователей с нарушениями зрения.

Руководство намеренно избегает изображений и минимизирует использование элементов, не являющихся обычным текстом, для улучшения совместимости со вспомогательными технологиями.
Советы и новые идеи приветствуются.
Если возможно, отправляйте отчёты в список рассылки FreeBSD по доступности, чтобы делиться и отслеживать обсуждения в публичном месте.

Спонсор: Фонд FreeBSD

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (10.01.2026): 0fc374bc297420a310d608dc206d209c483b9680
//
