=== FreeBSD Git Weekly (Еженедельные дайджесты Git)

Ссылки: +
link:https://freebsd-git-weekly.tarsnap.net/[FreeBSD Git Weekly] URL: link:https://freebsd-git-weekly.tarsnap.net/[]

Контакт: Graham Percival <gperciva@tarsnap.com>

Это еженедельные списки коммитов в link:https://cgit.freebsd.org/src/[дерево исходных текстов FreeBSD], разбитые по категориям, таким как "документация", "поддержка оборудования", "тестирование" и "ядро".
Мы также включаем ежеквартальные списки категоризированных коммитов для тех, кто предпочитает видеть три месяца разработки сразу.

Наша цель — упростить разработчикам и пользователям отслеживание изменений в FreeBSD, которые имеют к ним отношение, без необходимости подписываться на список рассылки dev-commits-src-main и просматривать каждый коммит, попадающий в их почтовый ящик.

Существует список рассылки link:https://www.tarsnap.com/lists.html[freebsd-git-weekly@tarsnap.com], который предоставляет анонсы о каждом отчете.

Спонсор: Tarsnap Backup Inc.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (29.12.2025): 784d600109aa9953a94212bed20dd320703c7c7d
//
