=== Сделать OpenJDK 21 версией JAVA по умолчанию (Make OpenJDK 21 the default JAVA_VERSION)

Ссылки:
link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272855[Запрос 272855] URL: link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272855[] +
link:https://docs.google.com/spreadsheets/d/17hmRQ0ShY4SHHVEkQBVxqK2G88fPZLriTzO26zXdjC4/edit?usp=sharing[Таблица отслеживания текущей работы] URL: https://docs.google.com/spreadsheets/d/17hmRQ0ShY4SHHVEkQBVxqK2G88fPZLriTzO26zXdjC4/edit?usp=sharing

Контакт: Ronald Klop <ronald@FreeBSD.org>

Версией Java по умолчанию (JAVA_VERSION) в портах FreeBSD все еще является OpenJDK 8.
Пришло время обновить ее до более современной версии, такой как OpenJDK 21.
Нам необходимо протестировать и исправить все порты, использующие Java для сборки или работы с JDK 21, либо закрепить (pin) JAVA_VERSION в порту на последнюю поддерживаемую версию.

Работа отслеживается в PR 272855 и в Google Таблице для более подробной информации.
Уже исправлено более половины портов, которые не прошли тестовый прогон.

Если у вас есть опыт работы с Java и системой портов, вас приглашают помочь.
Я думаю, что вполне реально привести порты в порядок для установки JAVA_VERSION=21 в феврале 2026 года.

План:

* Проверить последние 12 портов и создать PR или сделать коммит
* Зафиксировать PR, по которым истек срок ожидания ответа от мейнтейнера
* Запросить еще один экспериментальный прогон (exp-run)
* Если все готово, увеличить JAVA_VERSION

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (21.02.2026): f1998c4cc36e37d4a599269b8a3bf2c32f720804
//