=== KDE на FreeBSD

Ссылки: +
link:https://freebsd.kde.org/[Инициатива KDE/FreeBSD] URL: link:https://freebsd.kde.org/[] +
link:https://community.kde.org/FreeBSD[FreeBSD -- Вики сообщества KDE] URL: link:https://community.kde.org/FreeBSD[]

Контакт: Список рассылки KDE на FreeBSD <kde@FreeBSD.org>

Проект KDE на FreeBSD занимается упаковкой CMake, Qt и программного обеспечения из сообщества KDE для дерева портов FreeBSD.
Программное обеспечение включает в себя полноценную среду рабочего стола под названием KDE Plasma (как для X11, так и для Wayland) и сотни приложений, которые можно использовать на любой машине с FreeBSD.
Команда mailto:kde@FreeBSD.org[KDE] является частью mailto:desktop@FreeBSD.org[desktop@], создавая стек программного обеспечения, чтобы сделать FreeBSD красивой и пригодной для использования в качестве ежедневной графической рабочей станции.

==== Инфраструктура

CMake обновлен до версии 3.31.10.
Ninja обновлен до версии 1.13.2.

Qt6, PyQt6 и PySide6 обновлены до версии 6.10.1.

Qt5 обновлен до коллекции патчей KDE для версии 5.15.18.
Стандартная поддержка Qt5 вышестоящим проектом (upstream) официально прекращена.
Возможно, это последнее обновление для Qt5 на FreeBSD.

==== Стек KDE

Релизы KDE Frameworks, Plasma и Gear происходят очень регулярно.
Команда mailto:kde@FreeBSD.org[KDE] добавляет эти обновления вскоре после их выпуска вышестоящим проектом.

* Порты KDE Frameworks обновлены до версии 6.21.0.
* Среда рабочего стола KDE Plasma обновлена до версии 6.5.4.
* KDE Gear обновлен до версии 25.12.0.

С выходом KDE Gear 25.12.0 последние два приложения были наконец портированы на Qt6, и теперь стек KDE освобожден от пакетов Qt5.
Порт package:x11/kde[] был сокращен и больше не устанавливает плагины интеграции с Plasma 6 для приложений на Qt5 и GTK2.
Они все еще доступны и могут быть установлены через порт package:x11/plasma6-plasma[], если необходимо.

Поддержка Plasma/Wayland была улучшена.
Ее можно использовать как ежедневный драйвер вместо Plasma/X11.

==== Связанные порты

Команда mailto:kde@FreeBSD.org[KDE] поддерживает почти 730 портов и обновляет их все по мере необходимости.
Согласно link:https://portscout.freebsd.org/kde@freebsd.org.html[portscout], только 1% портов устарели.

Команда KDE хотела бы поблагодарить mailto:arrowd@FreeBSD.org[Глеба Попова], mailto:jhale@FreebSD.org[Джейсона Хейла (Jason E. Hale)], mailto:lbartoletti@FreeBSD.org[Лоика Бартолетти (Loïc Bartoletti)] и mailto:makc@FreeBSD.org[Максима Бражникова] за поддержание всего в актуальном состоянии.
Команда KDE благодарна Харли (Harley, SponiX в IRC) за предоставление своей сборочной машины.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (21.02.2026): 1520076b50c9e09bbeb13ef65c46b11241278e51
//
