=== Использование Bazel в качестве инструмента сборки для MongoDB 8.0

Ссылки: +
link:https://www.freshports.org/databases/mongodb80/[Порт MongoDB 8.0] URL: https://www.freshports.org/databases/mongodb80/[] +
link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=287546[PR для Bazel 8] URL: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=287546[]

Контакт: Ronald Klop <ronald@FreeBSD.org>

MongoDB — это NoSQL-база данных производственного уровня.
В наших портах уже много лет существует Community Edition MongoDB.
MongoDB используется в портах различного программного обеспечения для контроллеров WiFi, таких как Unifi и Omada.
Начиная с версии MongoDB 8.0.13, система сборки изменена с SCons на Bazel.

У нас есть версия 8 Bazel в Bugzilla (PR 287546).
С этой версией сборка MongoDB 8.0 запускается.
К сожалению, сборка довольно быстро завершается ошибкой.

Из-за проблем безопасности в порту MongoDB 8.0 становится важным обновить порт до последней версии.

Я ищу кого-нибудь с опытом сборки с помощью Bazel для помощи.

* Свяжитесь со мной.
* Настройте свою среду сборки с Bazel 8.
* Скомпилируйте и исправьте.
* Давайте закоммитим это!

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (21.02.2026): f1998c4cc36e37d4a599269b8a3bf2c32f720804
//
