=== Parthenope -- Дизайн и идеи

Ссылка: +
link:https://gitlab.com/alfix/parthenope[Репозиторий Parthenope] URL: link:https://gitlab.com/alfix/parthenope[]

Контакт: Alfonso Sabato Siciliano <asiciliano@FreeBSD.org>

Parthenope — это модульный, двухэтапный установщик для операционной системы FreeBSD, написанный в основном на Lua.
Процесс установки разделен на две фазы:

. На первом этапе файлы конфигурации и команды установки генерируются с использованием различных интерактивных интерфейсов.
. На втором этапе выполняется фактическая установка системы на основе ранее созданных файлов.

Проект является простым, расширяемым и гибким.
Он разработан для поддержки нескольких внешних интерфейсов (frontend), языков, режимов установки ("Авто", "Легкий" и "Экспертный"), уровней интерактивности и возможностей ведения журнала.

Parthenope начинался как личный проект, чтобы ответить на простой вопрос: "Какие функции я хотел бы видеть при установке FreeBSD на свой ноутбук?"
С тех пор он превратился в инструмент с открытым исходным кодом, который каждый может использовать, адаптировать или расширять в соответствии со своими требованиями.

В течение этого квартала:

* Мотивация, концептуальное доказательство (proof of concept) и несколько предварительных скриншотов были представлены на EuroBSDCon 2025, link:https://events.eurobsdcon.org/media/2025/submissions/FV7RJ7/resources/2-step-installer-zagreb-20_rpFDkax.pdf[слайды].
* Были выполнены рефакторинг скрипта генерации ISO-образа и подсистемы интернационализации.
* Был создан публичный репозиторий.

На данный момент установить FreeBSD с его помощью еще невозможно.
Следующие шаги:

* Рефакторинг файла конфигурации.
* Рефакторинг подсистем: журналирование, режимы, фаза-2 и т.д.
* Реализация компонентов установщика: разметчик дисков (partitioner), менеджер сети, дата/время и т.д.

На начальном этапе единственным внешним интерфейсом (frontend) будет текстовый пользовательский интерфейс (TUI), очень похожий на bsdinstall, установщик FreeBSD по умолчанию.
Дополнительные внешние интерфейсы будут добавлены в будущем.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (21.02.2026): f1998c4cc36e37d4a599269b8a3bf2c32f720804
//
