[[_suspendresume_improvement]]
=== Улучшение функций системы приостановки/возобновления работы (Suspend/Resume)

Ссылки: +
link:https://obiw.ac/s0ix/[Блог] URL: link:https://obiw.ac/s0ix/[] +
link:https://youtu.be/RCjPc4X2Edc[Доклад на BSDCan о s2idle/S0ix] URL: https://youtu.be/RCjPc4X2Edc[] +
link:https://people.freebsd.org/~obiwac/s0ix/[Образ для тестирования режимов сна] URL: https://people.freebsd.org/~obiwac/s0ix/[] +
link:https://reviews.freebsd.org/D48721[Ключевая часть стека s2idle/S0ix + AMD SMU] URL: https://reviews.freebsd.org/D48721[]

Контакт: obiwac <obiwac@FreeBSD.org>

В FreeBSD ведётся работа по добавлению поддержки режима "приостановка в бездействие" (suspend-to-idle) и сна S0ix.

Это позволит современным ноутбукам на Intel и AMD, некоторые из которых не поддерживают сон ACPI S3, переходить в состояния с низким энергопотреблением для увеличения времени автономной работы.

Вход в состояние S0i3 теперь работает с частичной надёжностью на ноутбуках Framework 13 с AMD Ryzen 7040 под управлением FreeBSD 15.

Код типа сна и sysctl был закоммичен, и было внесено исправление проблемы, которую он вызвал (link:https://reviews.freebsd.org/D53909[D53909]).
Из-за некоторых существующих проблем в нашем коде D-state ACPI, из-за которых некоторые ранее работавшие устройства перестали входить в состояние S3, связанные коммиты изменений D-state, необходимых для S0ix, пришлось отменить, хотя, похоже, это не влияет на вход в S0i3 на вышеупомянутой машине.
Проводилась работа по очистке и исправлению нашего кода D-state, но это не является большим приоритетом, если это не препятствует входу в S0i3 на целевой(ых) машине(ах).

Ревизии для s2idle и SPMC (link:https://reviews.freebsd.org/D48734[D48734] и link:https://reviews.freebsd.org/D48387[D48387] соответственно) были рассмотрены, и была проделана некоторая работа по подготовке их к коммиту.
Были созданы новые исследовательские ревизии для реализации цикла s2idle (link:https://reviews.freebsd.org/D54406[D54406] и link:https://reviews.freebsd.org/D54410[D54410]) и некоторых необходимых изменений в планировщике (link:https://reviews.freebsd.org/D54407[D54407] и link:https://reviews.freebsd.org/D54409[D54409]).

Возникли некоторые проблемы при возобновлении работы из S0i3, по-видимому, только при загрузке драйвера USB4, которые были исследованы.

Доступен предварительно собранный образ для тестирования режимов сна, облегчающий проверку входа в S0i3 на машинах.
Подробные инструкции находятся на link:https://obiw.ac/s0ix/[веб-странице].

Что касается ссылок, запись в блоге все еще устарела.

Спонсор: Фонд FreeBSD

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (17.01.2026): a0b7615194723980ab8fd71de5e4ca6e524ce608
//
