# $Id: Makefile,v 1.3 1998-08-03 13:28:58 wosch Exp $

DOCS=	qnewsletter.sgml

DOCS+=	qnewsletter-1-1.sgml
DOCS+=	qnewsletter-1-2.sgml
DOCS+=	qnewsletter-1-3.sgml

DOCS+= press.sgml
DOCS+= newsflash.sgml

.include "../web.mk"
