# $Id: Makefile,v 1.6 1998-08-16 12:52:26 wosch Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists("../Makefile.conf")
.include "../Makefile.conf"
.endif

# quick news letter
DOCS=	qnewsletter.sgml
DOCS+=	qnewsletter-1-1.sgml
DOCS+=	qnewsletter-1-2.sgml
DOCS+=	qnewsletter-1-3.sgml

DOCS+= press.sgml
DOCS+= newsflash.sgml

DOCS+= news.sgml

INDEXLINK= news.html

.include "../web.mk"
