# $Id: Makefile,v 1.11 1998-12-21 21:38:45 wosch Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists("../Makefile.conf")
.include "../Makefile.conf"
.endif

# quick news letter
DOCS=	qnewsletter.sgml
DOCS+=	qnewsletter-1-1.sgml
DOCS+=	qnewsletter-1-2.sgml
DOCS+=	qnewsletter-1-3.sgml
DOCS+=	qnewsletter-1-4.sgml
DOCS+=	qnewsletter-1-5.sgml
DOCS+=	qnewsletter-1-6.sgml
DOCS+=	qnewsletter-1-7.sgml

DOCS+= press.sgml
DOCS+= newsflash.sgml
DOCS+= news.sgml
DOCS+= webchanges.sgml

INDEXLINK= news.html

.include "../web.mk"
