# $FreeBSD: www/fr/prstats/Makefile,v 1.1 2003/12/15 16:04:59 stephane Exp $

# The FreeBSD French Documentation Project
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
