# $FreeBSD: www/ja/releases/3.3R/Makefile,v 1.2 1999/10/29 13:03:14 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

DOCS=	announce.sgml notes.sgml errata.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/3.3R

.include "../../../web.mk"
