# $FreeBSD: www/ja/releases/3.3R/Makefile,v 1.3 1999/12/23 01:16:10 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

LOCALTOP= ../..

DOCS=	announce.sgml notes.sgml errata.sgml

### Revision checking
REVCHECK=	YES

.include "${LOCALTOP}/web.mk"
