=== Continuous Integration

Links: +
link:https://ci.FreeBSD.org[FreeBSD Jenkins Instance] URL: link:https://ci.FreeBSD.org[https://ci.FreeBSD.org] +
link:https://ci.FreeBSD.org/hwlab[FreeBSD Hardware Testing Lab] URL: link:https://ci.FreeBSD.org/hwlab[https://ci.FreeBSD.org/hwlab] +
link:https://artifact.ci.FreeBSD.org[FreeBSD CI artifact archive] URL: link:https://artifact.ci.FreeBSD.org[https://artifact.ci.FreeBSD.org] +
link:https://hackmd.io/@FreeBSD-CI[FreeBSD CI weekly report] URL: link:https://hackmd.io/@FreeBSD-CI[https://hackmd.io/@FreeBSD-CI] +
link:https://wiki.freebsd.org/Jenkins[FreeBSD Jenkins wiki] URL: link:https://wiki.freebsd.org/Jenkins[https://wiki.freebsd.org/Jenkins] +
link:https://wiki.freebsd.org/HostedCI[Hosted CI wiki] URL: link:https://wiki.freebsd.org/HostedCI[https://wiki.freebsd.org/HostedCI] +
link:https://wiki.freebsd.org/3rdPartySoftwareCI[3rd Party Software CI] URL: link:https://wiki.freebsd.org/3rdPartySoftwareCI[https://wiki.freebsd.org/3rdPartySoftwareCI] +
link:https://preview.tinyurl.com/y9maauwg[Tickets related to freebsd-testing@] URL: link:https://preview.tinyurl.com/y9maauwg[https://preview.tinyurl.com/y9maauwg] +
link:https://github.com/freebsd/freebsd-ci[FreeBSD CI Repository] URL: link:https://github.com/freebsd/freebsd-ci[https://github.com/freebsd/freebsd-ci]

Contact: Jenkins Admin <jenkins-admin@FreeBSD.org> +
Contact: Li-Wen Hsu <lwhsu@FreeBSD.org> +
Contact: link:https://lists.FreeBSD.org/mailman/listinfo/freebsd-testing[freebsd-testing Mailing List] +
Contact: IRC #freebsd-ci channel on EFNet

The FreeBSD CI team maintains the continuous integration system of the FreeBSD project.
The CI system firstly checks the committed changes can be successfully built, then performs various tests and analysis over the newly built results.
The artifacts from those builds are archived in the artifact server for further testing and debugging needs.
The CI team members examine the failing builds and unstable tests and work with the experts in that area to fix the code or adjust test infrastructure.
The details of these efforts are available in the link:https://hackmd.io/@FreeBSD-CI[weekly CI reports].

During the second quarter of 2021, we continued working with the contributors and developers in the project to fulfil their testing needs and also keep collaborating with external projects and companies to improve their products and FreeBSD.

Important changes:

* The build environment of main (-CURRENT) and stable/13 branches are changed to 13.0-RELEASE

Retired jobs:

* link:https://ci.freebsd.org/job/FreeBSD-main-amd64-gcc6_build[GCC 6 build for main on amd64]

Work in progress and open tasks:

* Designing and implementing pre-commit CI building and testing
* Designing and implementing use of CI cluster to build release artifacts as release engineering does
* Collecting and sorting CI tasks and ideas link:https://hackmd.io/@FreeBSD-CI/freebsd-ci-todo[here]
* Testing and merging pull requests in link:https://github.com/freebsd/freebsd-ci/pulls[the FreeBSD-ci repo]
* Reducing the procedures of CI/test environment setting up for contributors and developers
* Setting up the CI stage environment and putting the experimental jobs on it
* Setting up public network access for the VM guest running tests
* Implementing using bare metal hardware to run test suites
* Adding drm ports building tests against -CURRENT
* Planning to run ztest and network stack tests
* Adding more external toolchain related jobs
* Improving the hardware lab to be more mature and adding more hardware
* Helping more software get FreeBSD support in its CI pipeline (Wiki pages: link:https://wiki.freebsd.org/3rdPartySoftwareCI[3rdPartySoftwareCI], link:https://wiki.freebsd.org/HostedCI[HostedCI])
* Working with hosted CI providers to have better FreeBSD support

Please see link:https://bugs.freebsd.org/bugzilla/buglist.cgi?bug_status=__open__&email1=testing%40FreeBSD.org&emailassigned_to1=1&emailcc1=1&emailreporter1=1&emailtype1=substring&query_format=advanced[freebsd-testing@ related tickets] for more WIP information, and don't hesitate to join the effort!

Sponsor: The FreeBSD Foundation
