=== GCC in the Ports Tree (lang/gcc*)

Links: +
link:https://gcc.gnu.org[GCC Project] URL: link:https://gcc.gnu.org[https://gcc.gnu.org] +
link:https://gcc.gnu.org/gcc-10/[GCC 10 release series] URL: link:https://gcc.gnu.org/gcc-10/[https://gcc.gnu.org/gcc-10/]

Contact: Gerald Pfeifer <gerald@pfeifer.com>

With the great help of linimon@ GCC 10 became the default version of GCC in the Ports Collection bringing many improvements and fixes.

Looking one step ahead, GCC 11 is now available as a port and even for use as GCC_DEFAULT via Mk/bsd.default-versions.mk .

Modern GCC ports like this now feature support for powerpcle, and most related changes also made it it upstream.

On the infrastructure side, USE_GCC now allows for a build time-only dependency, e.g. USE_GCC=yes:build .

And in case you are developing other ports, USE_GCC=any is a thing of the past and USE_GCC no longer tries to use the old 4.2-based system compiler (/usr/bin/gcc) even if present.

Finally, after some two decades of maintaining FreeBSD's lang/gcc* ports, the time has come to hand over the baton and largely step back.
Please reach out if you are want to help - we'd hate to simply drop maintainership and would be happy to collaborate and transition.
