# $FreeBSDru: frdp/www/ru/support/Makefile,v 1.1 2005/11/03 21:27:23 gad Exp $
# $FreeBSD$
# Original revision: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   bugreports.xml webresources.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
