# $FreeBSD$

MAN4=	adv.4\
	adw.4\
	aha.4\
	ahb.4\
	ahc.4\
	arp.4\
	asc.4\
	atkbd.4\
	atkbdc.4\
	ax.4\
	bktr.4\
	bpf.4\
	bridge.4\
	bt.4\
	ccd.4\
	cd.4\
	ch.4\
	cy.4\
	da.4\
	daic.4\
	ddb.4\
	de.4\
	dgb.4\
	divert.4\
	dpt.4\
	drum.4\
	dummynet.4\
	ed.4\
	fd.4\
	fdc.4\
	fxp.4\
	gsc.4\
	icmp.4\
	ifmib.4\
	iic.4\
	iicbb.4\
	iicbus.4\
	iicsmb.4\
	imm.4\
	inet.4\
	intro.4\
	ip.4\
	ipfirewall.4\
	ipnat.4\
	joy.4\
	keyboard.4\
	labpc.4\
	le.4\
	lkm.4\
	lo.4\
	lp.4\
	lpbb.4\
	lpt.4\
	matcd.4\
	mem.4\
	mouse.4\
	mtio.4\
	mx.4\
	ncr.4\
	netintro.4\
	null.4\
	od.4\
	opie.4\
	pass.4\
	pcm.4\
	plip.4\
	pn.4\
	ppbus.4\
	ppc.4\
	ppi.4\
	psm.4\
	pt.4\
	pty.4\
	random.4\
	rdp.4\
	rl.4\
	route.4\
	sa.4\
	sb.4\
	screen.4\
	scsi.4\
	sio.4\
	smb.4\
	smbus.4\
	smp.4\
	snp.4\
	splash.4\
	ssc.4\
	stl.4\
	su.4\
	sysmouse.4\
	tcp.4\
	tl.4\
	tty.4\
	tun.4\
	tw.4\
	tx.4\
	udp.4\
	uk.4\
	unix.4\
	update.4\
	vga.4\
	vn.4\
	vpo.4\
	vr.4\
	wb.4\
	wfd.4\
	wt.4\
	xl.4\
	yp.4\
	ze.4\
	zero.4\
	zp.4

MLINKS+=fd.4 stderr.4
MLINKS+=fd.4 stdin.4
MLINKS+=fd.4 stdout.4
MLINKS+=fpa.4 fea.4
MLINKS+=ipfirewall.4 ipaccounting.4
MLINKS+=ipfirewall.4 ipacct.4
MLINKS+=ipfirewall.4 ipfw.4
MLINKS+=mem.4 kmem.4
MLINKS+=netintro.4 networking.4
MLINKS+=pcvt.4 vt.4
MLINKS+=random.4 urandom.4
MLINKS+=scsi.4 cam.4
MLINKS+=smp.4 SMP.4
MLINKS+=splash.4 screensaver.4
MLINKS+=stl.4 stli.4
MLINKS+=yp.4 NIS.4
MLINKS+=yp.4 YP.4
MLINKS+=yp.4 nis.4

SUBDIR=	man4.i386

.include "bsd.prog.mk"
