#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/events/2003/Makefile,v 1.1 2004/02/21 18:16:21 andy Exp $
#
# Original revision: 1.1
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	bsdcon-devsummit.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
