# $FreeBSD: www/en/conspectus/advocacy/2000/11/Makefile,v 1.1 2000/11/07 21:25:10 jim Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	05.sgml
DOCS+=	12.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
