# $FreeBSD: www/en/conspectus/advocacy/2000/11/Makefile,v 1.3 2000/11/27 21:40:24 jim Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	05.sgml
DOCS+=	12.sgml
DOCS+=	19.sgml
DOCS+=	26.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
