---
description: 'Где получить помощь'
next: books/accessibility/partii
params:
  path: /books/accessibility/help/
part: 'Часть I. Общие положения'
prev: books/accessibility/parti
showBookMenu: 'true'
tags: ["Accessibility", "Help"]
title: 'Глава 1. Помощь'
weight: 3
---

[[help]]
= Помощь
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 1
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/accessibility/help/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[help-mailinglists]]
== Списки рассылки

Списки рассылки являются основным каналом коммуникации для сообщества FreeBSD, охватывая широкий спектр тем, связанных с проектом. Сообщения обычно пишутся в виде простого текста без графических элементов, что делает их хорошо подходящими для использования с экранными читалками (как брайлевскими дисплеями, так и речевыми синтезаторами). Полный список доступных списков рассылки можно найти по адресу: https://lists.freebsd.org/.

По вопросам доступности основным контактным лицом является список рассылки FreeBSD Accessibility. Чтобы подписаться, просмотреть архив, отправлять сообщения или управлять подпиской, посетите: https://lists.freebsd.org/subscription/freebsd-accessibility

[[help-chat]]
== Чат

Пользователи и разработчики FreeBSD также активны в IRC (Internet Relay Chat), где происходит общение в реальном времени. Полный список серверов и каналов доступен по адресу: https://wiki.freebsd.org/IRC/Channels . Сообщения обычно передаются в виде обычного текста, что делает IRC удобным для экранных читалок (как брайлевских дисплеев, так и речевых синтезаторов).

[[help-ports-pkgs]]
== Порты и пакеты

Если проблема касается внешнего инструмента, установленного через extref:{handbook}ports[порт или пакет], рассмотрите возможность привлечения сопровождающего порта к обсуждению для обеспечения должного внимания и решения.

Чтобы узнать, кто поддерживает конкретный порт, перейдите в каталог порта и выполните команду `make maintainer`. Например, чтобы найти ответственного за порт www/edbrowse[], выполните:

[source, shell]
....
% cd /usr/ports/www/edbrowse
% make maintainer
....

Чтобы найти сопровождающего установленного пакета, используйте `pkg info -f _пакет_`. Например:

[source, shell]
....
% pkg info -f edbrowse | grep Maintainer | awk '{print $3}'
....
