---
title: Einführung in NanoBSD
authors:
  - author: Daniel Gerzo
copyright: 2006 The FreeBSD Documentation Project
trademarks: ["freebsd", "general"]
---

= Einführung in NanoBSD
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:toc-title: Inhaltsverzeichnis
:table-caption: Tabelle
:figure-caption: Abbildung
:example-caption: Beispiel

include::shared/authors.adoc[]

[.abstract-title]
Zusammenfassung

Dieses Dokument stellt Informationen zu den NanoBSD Werkzeugen bereit, die dazu verwendet werden können ein FreeBSD Abbild für eingebettete Systeme zu erstellen, welche auf eine Compact Flash Karte passen (oder andere Massenspeicher).

__Übersetzt von Björn Heidotting__.

'''

toc::[]

[[intro]]
== Einführung in NanoBSD

NanoBSD ist ein Werkzeug welches derzeit von {phk-name} entwickelt wird. Es erstellt ein FreeBSD Systemabbild für eingebettete Systeme, die auf eine Compact Flash Karte passen (oder andere Massenspeicher).

Es kann dazu benutzt werden um spezialisierte Installationsabbilder zu bauen, entworfen für die einfache Installation und Wartung von Systemen die als "Computer Appliances" bekannt sind. Computer Appliances haben ihre Hard- und Software fest verbaut, dass bedeutet alle Anwendungen sind vorinstalliert. Die Appliance wird an ein bestehendes Netzwerk angeschlossen und kann mit der Arbeit (fast) sofort beginnen.

Zu den Eigenschaften von NanoBSD gehören:

* Ports und Pakete funktionieren wie in FreeBSD - Jede einzelne Anwendung kann auf dem NanoBSD Abbild installiert und benutzt werden, auf die gleiche Weise wie Sie es aus FreeBSD gewohnt sind.
* Keine fehlende Funktionalität - Wenn es möglich ist, etwas mit FreeBSD zu tun, ist es auch möglich, die gleiche Sache mit NanoBSD zu tun, es sei denn, eine oder mehrere Funktionen wurden ausdrücklich vor dem Bau des NanoBSD Abbilds entfernt.
* Zur Laufzeit ist alles read-only - Es ist sicher den Stromstecker zu ziehen. Es besteht dann keine Notwendigkeit, einen man:fsck[8] nach einem nicht ordnungsgemäßem Herunterfahren des Systems auszuführen.
* Einfach zu bauen und anzupassen - Unter Verwendung von nur einem Shell-Skript und einer Konfigurationsdatei ist es möglich, ein reduziertes und angepasstes Abbild zu bauen, welches jegliche Reihe von Anforderungen erfüllt.

[[howto]]
== NanoBSD Anleitung

[[design]]
=== Das Design von NanoBSD

Sobald das Abbild auf dem Medium verfügbar ist, kann NanoBSD gebootet werden. Der Massenspeicher ist standardmäßig in drei Teile unterteilt:

* Zwei Abbild Partitionen: `code#1` und `code#2`.
* Die Partition der Konfigurationsdatei, welche zur Laufzeit unter dem [.filename]#/cfg# Verzeichnis gemountet werden kann.

Diese Partitionen sind im Allgemeinen read-only.

Die [.filename]#/etc# und [.filename]#/var# Verzeichnisse sind man:md[4] (malloc) Speicher.

Die Partition der Konfigurationsdatei besteht unter dem [.filename]#/cfg# Verzeichnis. Sie enthält Dateien für das [.filename]#/etc# Verzeichnis und wird direkt nach dem Botten read-only eingehangen, weshalb es erforderlich ist geänderte Dateien von [.filename]#/etc# zurück nach [.filename]#/cfg# zu kopieren falls die Änderungen nach einem Neustart bestehen bleiben sollen.

.Dauerhafte Änderungen in [.filename]#/etc/resolv.conf# vornehmen
[example]
====

[source,bash]
....
# vi /etc/resolv.conf
[...]
# mount /cfg
# cp /etc/resolv.conf /cfg
# umount /cfg
....

====

[NOTE]
====
Die [.filename]#/cfg# Partition sollte nur während des Bootvorgangs und zu Änderungen an den Konfigurationsdateien gemountet werden.

Die [.filename]#/cfg# Partition jederzeit gemountet zu haben ist keine gute Idee, besonders wenn das NanoBSD System auf einem Massenspeicher betrieben wird, der eventuell druch eine große Anzahl von Schreiboperationen nachteilig beeinträchtigt wird (z. B. wenn der Dateisystem-Syncer den Speicher mit Daten überflutet).
====

=== Ein NanoBSD Abbild erstellen

Ein NanoBSD Abbild wird über ein einfaches [.filename]#nanobsd.sh# Shell-Skript gebaut, das sich unter [.filename]#/usr/src/tools/tools/nanobsd# befindet. Das Skript erstellt ein Abbild, welches dann mittels man:dd[1] auf einen Massenspeicher kopiert werden kann.

Die folgenden Kommandos sind notwendig um ein NanoBSD Abbild zu erstellen:

[source,bash]
....
# cd /usr/src/tools/tools/nanobsd <.>
# sh nanobsd.sh <.>
# cd /usr/obj/nanobsd.full <.>
# dd if=_.disk.full of=/dev/da0 bs=64k <.>
....

<.> Wechsel in das Basisverzeichnis des NanoBSD Skripts.

<.> Den Bauprozess starten.

<.> Wechsel in das Verzeichnis, in dem das gebaute Abbild liegt.

<.> NanoBSD auf einem Massenspeicher installieren.

=== Ein NanoBSD Abbild anpassen

Dies ist wahrscheinlich das wichtigste und interessanteste Merkmal von NanoBSD. Hierbei werden Sie auch die meiste Zeit mit der Entwicklung von NanoBSD verbringen.

Der Aufruf des folgenden Kommandos wird [.filename]#nanobsd.sh# dazu zwingen, seine Konfiguration aus [.filename]#myconf.nano# aus dem aktuellen Verzeichnis zu lesen:

[source,bash]
....
# sh nanobsd.sh -c myconf.nano
....

Die Anpassung wird auf zwei Arten geschehen:

* Konfigurations-Optionen
* Benutzerdefinierte Funktionen

==== Konfigurations-Optionen

Durch Konfigurationseinstellungen ist es möglich Optionen zu übergeben, die sowohl die `buildworld` und `installworld` Phasen des NanoBSD Bauprozesses betreffen, sowie interne Optionen, die den Haupt-Bauprozess von NanoBSD beeinflussen. Durch diese Optionen ist es möglich, das System so zu reduzieren, dass es mit wenig Platz, etwa 64 MB auskommt. Sie können die Konfigurationsdateien dazu nutzten FreeBSD noch weiter zu trimmen, bis es nur noch aus dem Kernel und zwei oder drei Dateien im Userland besteht.

Die Konfigurationsdatei besteht aus Konfigurations-Optionen, welche die Standardwerte überschreiben.

* `NANO_NAME` - Name des Build (wird verwendet, um die workdir Namen zu konstruieren).
* `NANO_SRC` - Pfad zum Quelltextverzeichnis, das für den Bau des Abbilds verwendet wird.
* `NANO_KERNEL` - Name der Kernelkonfigurationsdatei, die für den Bau des Kernels verwendet wird.
* `CONF_BUILD` - Optionen für die `buildworld` Phase des Bauprozesses.
* `CONF_INSTALL` - Optionen für die `installworld` Phase des Bauprozesses.
* `CONF_WORLD` - Optionen für die `buildworld` und `installworld` Phasen des Bauprozesses.
* `FlashDevice` - Definiert den zu benutzenden Medientyp. Überprüfen Sie die Datei [.filename]#FlashDevice.sub# für weitere Informationen.

==== Benutzerdefinierte Funktionen

Mit Hilfe von Shell-Funktionen in der Konfigurationsdatei besteht die Möglichkeit zur Feinabstimmung von NanoBSD. Das folgende Beispiel illustriert das Grundmodell von benutzerdefinierten Funktionen:

[.programlisting]
....
cust_foo () (
	echo "bar=baz" > \
		${NANO_WORLDDIR}/etc/foo
)
customize_cmd cust_foo
....

Ein besseres Beispiel für eine Anpassung ist folgende, welche die Standardgröße des [.filename]#/etc# Verzeichnisses von 5 MB auf 30 MB ändert:

[.programlisting]
....
cust_etc_size () (
	cd ${NANO_WORLDDIR}/conf
	echo 30000 > default/etc/md_size
)
customize_cmd cust_etc_size
....

Es gibt ein paar vordefinierte Standardfunktionen die Sie nutzen können:

* `cust_comconsole` - Deaktiviert man:getty[8] auf den VGA Geräten (den [.filename]#/dev/ttyv*# Gerätedateien) und ermöglicht die Nutzung der seriellen Schnittstelle COM1 als Systemkonsole.
* `cust_allow_ssh_root` - Erlaubt es `root` sich über man:sshd[8] anzumelden.
* `cust_install_files` - Installiert Dateien aus dem [.filename]#nanobsd/Files# Verzeichnis, das einige nützliche Skripte für die Systemverwaltung enthält.

==== Pakete hinzufügen

Durch benutzerdefinierte Funktionen können Pakete zum NanoBSD Abbild hinzugefügt werden. Die nachfolgende Funktion installiert alle Pakete aus [.filename]#/usr/src/tools/tools/nanobsd/packages#:

[.programlisting]
....
install_packages () (
mkdir -p ${NANO_WORLDDIR}/packages
cp /usr/src/tools/tools/nanobsd/packages/* ${NANO_WORLDDIR}/packages
chroot ${NANO_WORLDDIR} sh -c 'cd packages; pkg_add -v *;cd ..;'
rm -rf ${NANO_WORLDDIR}/packages
)
customize_cmd install_packages
....

==== Beispiel einer Konfigurationsdatei

Ein komplettes Beispiel für eine Konfigurationsdatei zum Erstellen eines benutzerdefinierten NanoBSD Abbilds könnte folgende sein:

[.programlisting]
....
NANO_NAME=custom
NANO_SRC=/usr/src
NANO_KERNEL=MYKERNEL
NANO_IMAGES=2

CONF_BUILD='
NO_KLDLOAD=YES
NO_NETGRAPH=YES
NO_PAM=YES
'

CONF_INSTALL='
NO_ACPI=YES
NO_BLUETOOTH=YES
NO_CVS=YES
NO_FORTRAN=YES
NO_HTML=YES
NO_LPR=YES
NO_MAN=YES
NO_SENDMAIL=YES
NO_SHAREDOCS=YES
NO_EXAMPLES=YES
NO_INSTALLLIB=YES
NO_CALENDAR=YES
NO_MISC=YES
NO_SHARE=YES
'

CONF_WORLD='
NO_BIND=YES
NO_MODULES=YES
NO_KERBEROS=YES
NO_GAMES=YES
NO_RESCUE=YES
NO_LOCALES=YES
NO_SYSCONS=YES
NO_INFO=YES
'

FlashDevice SanDisk 1G

cust_nobeastie() (
	touch ${NANO_WORLDDIR}/boot/loader.conf
	echo "beastie_disable=\"YES\"" >> ${NANO_WORLDDIR}/boot/loader.conf
)

customize_cmd cust_comconsole
customize_cmd cust_install_files
customize_cmd cust_allow_ssh_root
customize_cmd cust_nobeastie
....

=== NanoBSD aktualisieren

The Update-Prozess von NanoBSD ist relativ einfach:

[.procedure]
====
. Erstellen Sie ein neues NanoBSD Abbild.
. Laden Sie das neue Abbild in eine unbenutzte Partition eines laufenden NanoBSD Systems.
+ 
Der wichtigste Unterschied dieses Schrittes zur ersten NanoBSD Installation besteht darin, das jetzt anstatt der Datei [.filename]#\_.disk.full# (enthält ein Abbild der gesamten Platte) die Datei [.filename]#_.disk.image# (enthält ein Abbild einer einzelnen System-Partition) installiert wird.
. Neustart, um das System von der neu installierten Partition zu starten.
. Wenn alles gut geht, ist die Aktualisierung abgeschlossen.
. Wenn etwas schief läuft, starten Sie wieder in die vorherige Partition (die das alte, funktionierende Abbild enthält) um die System-Funktionalität so schnell wie möglich wieder herzustellen. Beheben Sie alle Probleme des neu gebauten Abbilds, und wiederholen Sie den Vorgang.
====

Um das neue Abbild auf das laufende NanoBSD System zu installieren, ist es möglich, entweder das [.filename]#updatep1# oder [.filename]#updatep2# Skript im [.filename]#/root# Verzeichnis zu verwenden, je nachdem, von welcher Partition das aktuelle System läuft.

In Abhängigkeit davon welche Dienste der Host, der das NanoBSD Abbild anbietet, und welche Art von Transfer bevorzugt wird, bestehen eine von drei zu prüfenden Möglichkeiten:

==== Verwendung von man:ftp[1]

Wenn die Übertragungsgeschwindigkeit an erster Stelle steht, verwenden Sie dieses Beispiel:

[source,bash]
....
# ftp myhost
get _.disk.image "| sh updatep1"
....

==== Verwendung von man:ssh[1]

Wenn eine sichere Übertragung bevorzugt wird, sollten Sie die Verwendung dieses Beispiels in Betracht ziehen:

[source,bash]
....
# ssh myhost cat _.disk.image.gz | zcat | sh updatep1
....

==== Verwendung von man:nc[1]

Verwenden Sie dieses Beispiel, wenn auf dem Remote-Host kein man:ftpd[8] oder man:sshd[8] Dienst läuft:

[.procedure]
====
. Zunächst öffnen Sie eine TCP-Listener auf dem Host der das Abbild bereitstellt und zum Client sendet:
+
[source,bash]
....
myhost# nc -l 2222 < _.disk.image
....
+
[NOTE]
======
Stellen Sie sicher das der benutzte Port nicht blockiert wird, um eingehende Verbindungen, vom NanoBSD Host durch die Firewall, zu ermöglichen.
======
. Verbinden Sie sich zum Host der das Abbild bereitstellt und führen Sie das [.filename]#updatep1# Skript aus:
+
[source,bash]
....
# nc myhost 2222 | sh updatep1
....
====
