---
title: Capítulo 9. Imprimir
part: Parte II. Tareas comunes
prev: books/handbook/kernelconfig
next: books/handbook/linuxemu
---

[[printing]]
= Imprimir
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Tabla de contenidos
:table-caption: Tabla
:figure-caption: Figura
:example-caption: Ejemplo
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 9

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/printing/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/printing/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/printing/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/es/mailing-lists.adoc[]
include::shared/es/teams.adoc[]
include::shared/es/urls.adoc[]

toc::[]

== Sinopsis

FreeBSD puede utilizarse para imprimir en una gran variedad de impresoras, desde las antiguas impresoras de matriciales hasta las más modernas impresoras laser y todo lo que existe entre unas y otras, con lo que podrá imprimir con una calidad muy alta desde cualquier aplicación.

FreeBSD puede usarse también como servidor de impresión en red; FreeBSD puede recibir peticiones de impresión de una gran cantidad de sistemas, bien sean FreeBSD, Windows(R) y Mac OS(R). FreeBSD se encarga de los trabajos se vayan imprimiendo uno tras otro y puede mantener estadísticas sobre qué usuarios y qué máquinas están imprimiendo más, generar páginas de «encabezado» para colocarlas antes de cada trabajo y distinguir así de quién es la impresión, etc.

Tras leer el presente capítulo sabrá usted:

* Cómo configurar la cola de impresión en FreeBSD.
* Cómo instalar filtros de impresión para gestionar diversos trabajos especiales como la conversión de documentos a formatos aptos para su impresora.
* Cómo habilitar encabezados en sus impresiones.
* Cómo imprimir en impresoras conectadas a otras máquinas.
* Cómo imprimir en impresoras conectadas directamente a la red.
* Cómo controlar restricciones de impresión, como por ejemplo limitaciones del tamaño de trabajos o evitar que ciertos usuarios puedan imprimir.
* Cómo mantener estadísticas de impresión y cuentas de usuario de impresión.
* Cómo solucionar los problemas de impresión más comunes.

Antes de leer este capítulo usted debería:

* Saber cómo compilar e instalar un kernel personalizado (crossref:kernelconfig[kernelconfig,Configuración del kernel de FreeBSD]).

[[printing-intro-spooler]]
== Introducción

Si quiere utilizar impresoras con FreeBSD debe configurarlas de forma que funcionen con el sistema de cola de impresión de Berkeley, también conocido como sistema de cola LPD. Es el sistema de control de impresión estándar en FreeBSD. Este capítulo trata sobre el sistema LPD, al que en adelante nos referiremos simplemente como LPD, y le introducirá en la configuración del mismo.

Si está familiarizado con el sistema de cola de impresión LPD, o bien con algún otro sistema de impresión, puede pasar a la sección <<printing-intro-setup,Configuración del sistema de cola de impresión>>.

LPD se encarga de controlar todo lo relacionado con la impresión, lo que en consecuencia implica encargarse de lo siguiente:

* Controlar el acceso a las impresoras conectadas directamente al sistema y a impresoras conectadas a otras máquinas de la red.
* Permitir que ciertos usuarios puedan enviar ficheros para su impresión; estos envíos reciben el nombre de _trabajos_ ("jobs").
* Evita que usuarios diferentes accedan a la impresora al mismo tiempo manteniendo un orden estricto en la cola de impresión de cada impresora.
* Imprimir _encabezados_ de forma que los usuarios puedan distinguir fácilmente los trabajos que han impreso.
* Se ocupa de los parámetros para impresoras conectadas a puertos serie.
* Enviar trabajos de impresión a través de una red a la cola LPD de una máquina remota.
* Ejecutar filtros especiales para formatear trabajos que requieren la gestión de lenguajes de impresión o impresoras de diferentes características.
* Mantener un registro del uso de la impresora.

Gracias al fichero de configuración ([.filename]#/etc/printcap#) y mediante programas especiales de filtrado puede hacerse que el sistema LPD cumpla todas las tareas citadas o si lo prefiere solo unas cuantas; además puede hacerlo en una gran variedad de impresoras.

[[printing-intro-why]]
=== ¿Por qué utilizar una cola de impresión?

Si es usted la única persona que usa el sistema se estará por qué preocuparse de utilizar un sistema de cola de impresión si es evidente que no necesita restricciones de acceso, encabezados ni cuentas de impresión. Puede utilizar el acceso directo a impresión, pero debería utilizar una cola de impresión por las siguientes razones:

* El sistema LPD ejecuta los trabajos en segundo plano, esto es, no tiene que esperar a que la impresora procese los datos para seguir trabajando.
* LPD puede procesar un trabajo de forma que pase por filtros, añadir cabeceras de fecha y hora o convertir un fichero de formato especial (por ejemplo TeX DVI) a un formato que la impresora entienda y que no tenga usted que ocuparse de ello manualmente.
* Muchos programas, tanto libres como comerciales, desde los que se puede imprimir están hechos pensando en que haya disponible un sistema de impresión. Una vez que configure un sistema de colas podrá utilizar software que ya tiene instalado y preparar el campo para el que instale en el futuro.

[[printing-intro-setup]]
== Configuración básica

Pendiente de traducción.

[[printing-advanced]]
== Configuración avanzada de impresoras

Pendiente de traducción

[[printing-using]]
== Cómo utilizar impresoras

Pendiente de traducción.

[[printing-lpd-alternatives]]
== Alternativas a LPD

Pendiente de traducción

[[printing-troubleshooting]]
== Solución de problemas

Pendiente de traducción
