#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/problem-reports/Makefile,v 1.3 2005/06/30 03:23:24 gad Exp $
#
# Original revision: r39631
#
# Article: Writing FreeBSD Problem Reports

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=  article.xml

URL_RELPREFIX?=        ../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
