#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/Makefile,v 1.37 2006/03/22 17:06:02 marck Exp $
#
# Original revision: r21216
#

SUBDIR =
SUBDIR+= committers-guide
SUBDIR+= console-server
SUBDIR+= contributing
#SUBDIR+= contributors
SUBDIR+= cups
SUBDIR+= custom-gcc
SUBDIR+= cvs-freebsd
SUBDIR+= explaining-bsd
SUBDIR+= fbsd-from-scratch
#SUBDIR+= filtering-bridges
SUBDIR+= fonts
SUBDIR+= freebsd-questions
SUBDIR+= geom-class
SUBDIR+= gjournal-desktop
SUBDIR+= hubs
SUBDIR+= ipsec-must
SUBDIR+= laptop
SUBDIR+= linux-comparison
SUBDIR+= mailing-list-faq
SUBDIR+= mh
SUBDIR+= new-users
SUBDIR+= pam
SUBDIR+= portbuild
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports
SUBDIR+= relaydelay
SUBDIR+= releng
SUBDIR+= releng-packages
#SUBDIR+= serial-uart
SUBDIR+= solid-state
#SUBDIR+= vinum
SUBDIR+= vm-design

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
