#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/Makefile,v 1.37 2006/03/22 17:06:02 marck Exp $
#
# Original revision: 1.42
#

SUBDIR =
SUBDIR+= 5-roadmap
SUBDIR+= checkpoint
SUBDIR+= committers-guide
SUBDIR+= console-server
SUBDIR+= contributing
#SUBDIR+= contributors
SUBDIR+= cvs-freebsd
SUBDIR+= cvsup-advanced
SUBDIR+= dialup-firewall
SUBDIR+= diskless-x
SUBDIR+= euro
SUBDIR+= explaining-bsd
SUBDIR+= fbsd-from-scratch
#SUBDIR+= filtering-bridges
SUBDIR+= fonts
SUBDIR+= formatting-media
SUBDIR+= freebsd-questions
SUBDIR+= geom-class
SUBDIR+= gjournal-desktop
SUBDIR+= hats
SUBDIR+= hubs
SUBDIR+= ipsec-must
SUBDIR+= laptop
SUBDIR+= linux-comparison
SUBDIR+= mailing-list-faq
SUBDIR+= mh
SUBDIR+= multi-os
SUBDIR+= new-users
SUBDIR+= pam
SUBDIR+= portbuild
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports
SUBDIR+= pxe
SUBDIR+= relaydelay
SUBDIR+= releng
SUBDIR+= releng-packages
#SUBDIR+= serial-uart
SUBDIR+= solid-state
#SUBDIR+= storage-devices
#SUBDIR+= vinum
SUBDIR+= version-guide
SUBDIR+= vm-design
SUBDIR+= zip-drive

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
