# 
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/Makefile.inc,v 1.1 2001/03/11 10:41:06 phantom Exp $
# $FreeBSD: doc/ru_RU.KOI8-R/articles/Makefile.inc,v 1.1 2001/03/11 16:23:41 phantom Exp $
# Original revision: 1.3
#

DESTDIR?=	${DOCDIR}/ru_RU.KOI8-R/articles/${.CURDIR:T}
