# 
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/Makefile.inc,v 1.1 2001/03/11 10:41:06 phantom Exp $
# $FreeBSD$
# Original revision: 1.3
#

DESTDIR?=	${DOCDIR}/en_US.ISO_8859-1/articles/${.CURDIR:T}
