# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/Makefile,v 1.1 2001/03/11 10:41:06 phantom Exp $
# $FreeBSD$
# Original revision: 1.9

#SUBDIR = committers-guide
#SUBDIR+= dialup-firewall
#SUBDIR+= diskless-x
SUBDIR = freebsd-questions
#SUBDIR+= fonts
#SUBDIR+= formatting-media
#SUBDIR+= ipsec-must
#SUBDIR+= mh
#SUBDIR+= multi-os
#SUBDIR+= new-users
#SUBDIR+= programming-tools
#SUBDIR+= zip-drive

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
