---
title: "Порты FreeBSD"
sidenav: ports
---

include::shared/releases.adoc[]
include::shared/ru/urls.adoc[]

= Порты FreeBSD

{{< form-ports >}}

'''''

Коллекция Портов и Пакетов FreeBSD даёт пользователям и администраторам простой метод установки приложений. На текущий момент всего портов доступно: *{numports}*.

Коллекция портов поддерживается на последних релизах веток link:{faq}#CURRENT[FreeBSD-CURRENT] и link:{faq}#STABLE[FreeBSD-STABLE]. Предыдущие релизы не поддерживаются и могут работать или не работать корректно с обновленной коллекцией портов. Со временем изменения в коллекции портов могут быть основаны на возможностях, не представленных в предыдущих релизах. Мы стараемся не нарушать поддержку последних релизов, но иногда это невозможно. Когда сообщество пользователей предлагает исправления, они обычно вносятся.

Каждый ''порт'', указанный здесь, содержит все патчи, необходимые для компиляции и запуска оригинального приложения во FreeBSD. Установка приложения проста и сводится к выполнению команды `make install` в каталоге порта. Загрузив и установив link:{handbook}#ports-tree[полное дерево портов], вы моментально получаете тысячи приложений под рукой.

`Makefile` каждого порта автоматически сгружает исходный код приложения с локального диска или CDROM либо по http://www.freebsd.org/cgi/man.cgi?query=ftp[`ftp`], распаковывает его в вашей системе, прикладывает патчи и компилирует. Если всё проходит гладко, набор команды `make install` приводит к установке приложения и регистрации его в системе.

Для большинства портов имеется уже откомпилированный `пакет`, что позволяет избавиться от компиляции чего бы то ни было. В каждом порту имеется ссылка на соответствующий пакет и вы можете просто скачать соответствующий файл, а затем применить к нему команду http://www.freebsd.org/cgi/man.cgi?query=pkg_add[`+pkg_add+`] либо указать местоположение пакета в виде ссылки в командной строке при запуске `pkg_add`, так как эта утилита способна воспринимать как имена файлов, так и URL.
