# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/man/man3/Makefile,v 1.7 2007/11/20 06:53:29 ru Exp $

MAN=	setbuf.3 \
	strcpy.3

MLINKS+= setbuf.3 setbuffer.3
MLINKS+= setbuf.3 setlinebuf.3
MLINKS+= setbuf.3 setvbuf.3
MLINKS+= strcpy.3 stpcpy.3
MLINKS+= strcpy.3 strncpy.3

.include <bsd.prog.mk>
