---
title: "Trademark Legend"
sidenav: about
---

= Trademark Legend

FreeBSD is a registered trademark of The FreeBSD Foundation.

The FreeBSD Logo is a trademark of The FreeBSD Foundation.

See https://www.freebsdfoundation.org/[The FreeBSD Foundation's] https://www.freebsdfoundation.org/legal/trademark-usage-terms-and-conditions/[Trademark Usage Terms and Conditions] page for information on use of the FreeBSD marks.

Adobe, Acrobat, Acrobat Reader, and PostScript are either registered trademarks or trademarks of Adobe Systems Incorporated in the United States and/or other countries.

AMD, Am486, Am5X86, AMD Athlon, AMD Duron, AMD Opteron, AMD-K6, Athlon, Élan, Opteron, and PCnet are trademarks of Advanced Micro Devices, Inc.

Apple, FireWire, Mac, Macintosh, Mac OS, Quicktime, and TrueType are trademarks of Apple Computer, Inc., registered in the United States and other countries.

CVSup is a registered trademark of John D. Polstra.

F5, F5 Networks, and the F5 logo are trademarks of F5 Networks, Inc. in the U.S. and in certain other countries. Other F5 trademarks are identified at f5.com. Any other products, services, taglines/slogans, or company names referenced herein may be trademarks of their respective owners with no endorsement or affiliation, expressed or implied, claimed by F5.

IBM and PowerPC are trademarks of International Business Machines Corporation in the United States, other countries, or both.

IEEE, POSIX, and 802 are registered trademarks of The Institute of Electrical and Electronics Engineers, Inc.

Intel, Celeron, EtherExpress, i386, i486, Itanium, Pentium, and Xeon are trademarks or registered trademarks of Intel Corporation or its subsidiaries in the United States and other countries.

Linux is a registered trademark of Linus Torvalds in the United States.

Motif, OSF/1, and UNIX are registered trademarks and IT DialTone and The Open Group are trademarks of The Open Group in the United States and other countries.

MySQL is a registered trademark of MySQL AB in the United States, the European Union and other countries.

NVIDIA, the NVIDIA logo, 3D Play, 3D Vision Pro, 4-Plus-1, APEX, BattleBox, BFGD, Big Format Gaming Display, CUDA, Dabbler, DALI, DGX Station, DirectStylus, DirectTouch, Game Ready, GameStream, Geared For Gaming, GeForce, GeForce Experience, GeForce GTX, GeForce RTX, GPUDirect, G-SYNC, GRID LINK, GRID VGX, IceClear, ICERA, I AM AI, Iray, Jetson, Jetson AGX Xavier, Kepler, Made To Game, Maximus, Mental Ray, NSIST on NVIDIA, nTersect, NVIDIA 3D Vision, NVIDIA AGX, NVIDIA AutoWorks, NVIDIA BATTERY BOOST, NVIDIA BFGD, NVIDIA Big Format Gaming Display, NVIDIA Business Platform, NVIDIA Clara, NVIDIA DALI, NVIDIA Denver, NVIDIA DesignWorks, NVIDIA DGX, NVIDIA DGX POD, NVIDIA DGX Superpod, NVIDIA DRIVE, NVIDIA DRIVE Autopilot, NVIDIA DRIVE Constellation, NVIDIA DRIVE Hyperion, NVIDIA DRIVE Sim, NVIDIA GameWorks, NVIDIA GPU BOOST, NVIDIA GPU CLOUD, NVIDIA GRID, NVIDIA GRID vGPU, NVIDIA G-SYNC, NVIDIA HGX, NVIDIA Holodeck, NVIDIA IndeX, NVIDIA Isaac, NVIDIA Isaac SDK, NVIDIA Isaac SIM, NVIDIA Jetpack, NVIDIA Kepler, NVIDIA Maglev, NVIDIA Maximus, NVIDIA Maxwell, NVIDIA nForce, NVIDIA OptiX, NVIDIA Orin, NVIDIA PartnerForce, NVIDIA PureAudio, NVIDIA Quadro, NVIDIA RTX, NVIDIA SHIELD, NVIDIA SLI, NVIDIA SLI Ready, NVIDIA Slide Cover, NVIDIA SPOT, NVIDIA Tegra, NVIDIA Turing, nView, NVLink, NVS, NVSwitch, OpenACC, Openautomate, Optimus, OptiX, Pascal, Pegasus, PGI, PGI Visual Fortran, PhysX, Quadro, Quadro Experience, Quadro RTX, RealityServer, SceniX, Shadowplay, SHIELD, SLI, Surround, Tegra, Tegra NOTE, TegraZone, TensorRT, Tesla, The Way It's Meant to be Played,  TWIMTBP, ULMB, vGPU, Vibrante, VisionWorks, VRLync, and Xavier are trademarks and/or registered trademarks of NVIDIA Corporation in the U.S. and/or other countries

Silicon Graphics, SGI, and OpenGL are registered trademarks of Silicon Graphics, Inc., in the United States and/or other countries worldwide.

Sparc, Sparc64, SPARCEngine, and UltraSPARC are trademarks of SPARC International, Inc in the United States and other countries. Products bearing SPARC trademarks are based upon architecture developed by Sun Microsystems, Inc.

Sun, Sun Microsystems, SunOS, Solaris, and Java are trademarks or registered trademarks of Sun Microsystems, Inc. in the United States and other countries.

Many of the designations used by manufacturers and sellers to distinguish their products are claimed as trademarks. Where those designations appear on this website, and the FreeBSD Project was aware of the trademark claim, the designations have been followed by the '(TM)' or the '(R)' symbol.
