---
title: "Trademark Legend"
sidenav: about
---

= Trademark Legend

FreeBSD is a registered trademark of The FreeBSD Foundation.

The FreeBSD Logo is a trademark of The FreeBSD Foundation.

See https://www.freebsdfoundation.org/[The FreeBSD Foundation's] https://www.freebsdfoundation.org/legal/trademark-usage-terms-and-conditions/[Trademark Usage Terms and Conditions] page for information on use of the FreeBSD marks.

Adobe, Acrobat, Acrobat Reader, and PostScript are either registered trademarks or trademarks of Adobe Systems Incorporated in the United States and/or other countries.

AMD, Am486, Am5X86, AMD Athlon, AMD Duron, AMD Opteron, AMD-K6, Athlon, Élan, Opteron, and PCnet are trademarks of Advanced Micro Devices, Inc.

Apple, FireWire, Mac, Macintosh, Mac OS, Quicktime, and TrueType are trademarks of Apple Computer, Inc., registered in the United States and other countries.

CVSup is a registered trademark of John D. Polstra.

IBM and PowerPC are trademarks of International Business Machines Corporation in the United States, other countries, or both.

IEEE, POSIX, and 802 are registered trademarks of The Institute of Electrical and Electronics Engineers, Inc.

Intel, Celeron, EtherExpress, i386, i486, Itanium, Pentium, and Xeon are trademarks or registered trademarks of Intel Corporation or its subsidiaries in the United States and other countries.

Linux is a registered trademark of Linus Torvalds in the United States.

Motif, OSF/1, and UNIX are registered trademarks and IT DialTone and The Open Group are trademarks of The Open Group in the United States and other countries.

MySQL is a registered trademark of MySQL AB in the United States, the European Union and other countries.

Silicon Graphics, SGI, and OpenGL are registered trademarks of Silicon Graphics, Inc., in the United States and/or other countries worldwide.

Sparc, Sparc64, SPARCEngine, and UltraSPARC are trademarks of SPARC International, Inc in the United States and other countries. Products bearing SPARC trademarks are based upon architecture developed by Sun Microsystems, Inc.

Sun, Sun Microsystems, SunOS, Solaris, and Java are trademarks or registered trademarks of Sun Microsystems, Inc. in the United States and other countries.

Many of the designations used by manufacturers and sellers to distinguish their products are claimed as trademarks. Where those designations appear on this website, and the FreeBSD Project was aware of the trademark claim, the designations have been followed by the '(TM)' or the '(R)' symbol.
