---
title: "Проект FreeBSD Java®: Новости"
sidenav: developers
---

include::shared/ru/urls.adoc[]

= Проект FreeBSD Java(R): Новости

== Январь 2005

* *19 января 2005:* +
mailto:glewis@FreeBSD.org[Грег Льюис] выпустил начальный набор патчей (patchset 1) в серии JDK(R) 1.5. Обратитесь к link:dists/15[странице JDK 1.5.x] для получения более полной информации.

== Декабрь 2004

* *13 декабря 2004:* +
mailto:glewis@FreeBSD.org[Грег Льюис] выпустил седьмой набор патчей (patchset 7) в серии JDK(R) 1.4. Обратитесь к странице JDK 1.4.x для получения более полной информации.

== Ноябрь 2004

* *25 ноября 2004:* +
В подключаемом модуле Java-браузера найдена http://cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2004-1029[уязвимость]. Порт jdk14 был исправлен в версии 1.4.2p6_7. Порт jdk13 остаётся подверженным уязвимости. Вы можете выяснить точные номера версий и портов, в которых есть уязвимость, http://www.vuxml.org/freebsd/ac619d06-3ef8-11d9-8741-c942c075aa41.html[здесь].

== Декабрь 2003

* *30 декабря 2003:* +
mailto:glewis@FreeBSD.org[Грег Льюис] (Greg Lewis) выпустил шестой набор патчей (patchset 6) в серии JDK(R) 1.4. Обратитесь к странице JDK 1.4.x за дальнейшей информацией.
* *19 декабря 2003:* +
mailto:glewis@FreeBSD.org[Грег Льюис] (Greg Lewis) выпустил обновлённый набор патчей (patchset 9) для пакета &jdk; 1.3.1 Дополнительную информацию можно найти на странице о JDK 1.3.x.

== Ноябрь 2003

* *11 ноября 2003:* +
mailto:glewis@FreeBSD.org[Грег Льюис] (Greg Lewis) выпустил пятый набор патчей (patchset 5) в серии JDK(R) 1.4. Дополнительную информацию можно найти на странице о JDK 1.4.x.

== Октябрь 2003

* *10 октября 2003:* +
mailto:glewis@FreeBSD.org[Грег Льюис] (Greg Lewis) выпустил четвёртый набор патчей (patchset 4) в серии &jdk; 1.4. Дополнительную информацию можно найти на странице о JDK 1.4.x.

== Август 2003

* *26 августа 2003:* +
FreeBSD Foundation http://www.freebsdfoundation.org/press/20030825-java131.shtml[анонсировала] поддержку JDK(R) 1.3.1 во FreeBSD.

== Март 2003

* *7 марта 2003:* +
mailto:glewis@FreeBSD.org[Грег Льюис] (Greg Lewis) выпустил третий набор патчей (patchset 3) в серии JDK(R) 1.4. Обратитесь к странице JDK 1.4.x за более подробной информацией.

== Февраль 2003

* *12 февраля 2003:* +
mailto:glewis@FreeBSD.org[Грег Льюис] (Greg Lewis) выпустил обновленный набор патчей (patchlevel 8) для программного обеспечения JDK(R) 1.3.1. Обратитесь к странице JDK 1.3.x за более подробной информацией.
* *4 февраля 2003:* +
mailto:glewis@FreeBSD.org[Грег Льюис] (Greg Lewis) выпустил второй набор патчей (patchset 2) в серии JDK(R) 1.4. Обратитесь к странице JDK 1.4.x за более подробной информацией.

== Ноябрь 2002

* *15 ноября 2002:* +
mailto:glewis@FreeBSD.org[Грэг Льюис] (Greg Lewis) выпустил первый набор патчей (patchlevel 1) для пакета JDK(R) 1.4.0. Для получения более полной информации обратитесь к странице JDK 1.2.x.

== Сентябрь 2002

* *18 сентября 2002:* +
mailto:glewis@FreeBSD.org[Грэг Льюис] (Greg Lewis) выпустил обновлённый набор патчей (patchlevel 11) для пакета &jdk; 1.2.2. Для получения более полной информации обратитесь к странице JDK 1.2.x.
* *17 сентября 2002:* +
Сразу после выпуска компанией Sun пакета J2SE 1.4.1 FCS, версия для Linux стала доступной через систему портов FreeBSD. Для получения более полной информации обратитесь к http://java.sun.com/j2se/1.4.1/[странице о J2SE 1.4.1].

== Июль 2002

* *26 июля 2002:* +
mailto:glewis@FreeBSD.org[Грэг Льюис] (Greg Lewis) выпустил обновлённый набор патчей (patchlevel 7) для пакета &jdk; 1.3.1. Для получения более полной информации обратитесь к странице JDK 1.3.x.

== Февраль 2002

* *13 февраля 2002:* +
mailto:glewis@FreeBSD.org[Грэг Льюис] (Greg Lewis) выпустил обновлённый набор патчей (patchlevel 6) для пакета &jdk; 1.3.1. Для получения более полной информации обратитесь к странице JDK 1.3.x.

== Декабрь 2001

* *22 декабря 2001:* +
+
В списке announce@FreeBSD.org было опубликовано следующее:
+
FreeBSD Foundation получила лицензию от Sun Microsystems на распространение версий для FreeBSD как для Java Development Kit (JDK(R)), так и Java Runtime Environment (JRE). Благодаря огромным усилиям команды FreeBSD Java, они должны быть готовы к включению в готовящийся релиз FreeBSD 4.5 в январе 2002.
+
Общедоступность отчуждаемой версии Java полезно конечным пользователям, коммерческим пользователям и разработчикам, которые используют FreeBSD. Популярность Java продолжает расти и этот язык становится часто используемым для построения серверных приложений для Web, что является одной из основных сильных сторон FreeBSD. Имея официально лицензированный бинарный дистрибутив Java, FreeBSD становится идеальной платформой для выполнения, разработки и внедрения решений, основанных на Java.
+
Этого соглашения не могло быть без усилий mailto:nate@FreeBSD.org[Нэйта Вильямса] (Nate Williams). Нэйт не только инициировал процесс переноса Java на FreeBSD, но и организовал возможность подписания лицензионного соглашения между Sun Microsystems и Foundation.
+
Вы можете получить полный текст анонса http://daily.daemonnews.org/view_story.php3?story_id=2602[здесь].

== Октябрь 2001

* *16 октября 2001:* +
mailto:glewis@FreeBSD.org[Грэг Льюис] (Greg Lewis) выпустил обновлённый набор патчей (patchlevel 5) для пакета &jdk; 1.3.1. Для получения более полной информации обратитесь к странице JDK 1.3.x.

=== Сентябрь 2001

* *10 сентября 2001:* +
mailto:glewis@FreeBSD.org[Грэг Льюис] (Greg Lewis) выпустил обновлённый набор патчей (patchlevel 4) для пакета JDK(R) 1.3.1. Для получения более полной информации обратитесь к странице JDK 1.3.x.
* *6 сентября 2001:* +
mailto:sobomax@FreeBSD.org[Максим Соболев] (Maxim Sobolev) создал порт пакета http://www.sun.com/forte/ffj/index.html[Forte[tm] for Java[tm]] от Sun, release 3.0 Community Edition, который представляет собой интегрированную среду разработки (IDE). Этот пакет может быть построен из каталога портов ports/java/forte.
+
Порт может быть использован совместно либо с собственным JDK(R) 1.3.1, либо с Linux JDK(R) 1.3.1.

== Август 2001

* *27 августа 2001:* +
mailto:glewis@FreeBSD.org[Грег Льюис] (Greg Lewis) выпустил долгожданный порт для программного обеспечения JDK(R) 1.3.1. Теперь он может строиться из каталога портов ports/java/jdk13. Обратитесь к страничке JDK 1.3.x для получения более полной информации.
+
Следует заметить, что по большей части этот релиз предназначен только для разработчиков, в промышленной эксплуатации его использовать не рекомендуется.

== Октябрь 2000

* *14 октября 2000:* +
mailto:sobomax@FreeBSD.org[Максим Соболев] (Maxim Sobolev) создал порт пакета JDK(R) 1.2.2. Теперь он может быть построен из каталога ports/java/jdk12-beta Коллекции портов. Обратитесь к странице о JDK 1.2.x для получения более подробной информации.
+
Однако все замечания, о которых идёт речь ниже, остаются в силе.
+
Таким образом, теперь очередь тех, у кого есть готовый порт Java2.

=== Сентябрь 2000

* *15 сентября 2000:* С доски объявлений Java: +
mailto:sean@stat.duke.edu[Sean O'Connell] и mailto:gallatin@cs.duke.edu[Andrew Gallatin] сделали патчи, позволяющие запускать JDK(R) 1.3 фирмы IBM во FreeBSD. +
mailto:ernst@jollem.com[Ernst de Haan] удалось запустить Linux JDK(R) 1.3.0b9 фирмы Sun в 4.0-STABLE.
+
Полная информация находится здесь.

== Август 2000

* *10 августа 2000:* 7 августа 2000 года команде FreeBSD JDK(R) был дан доступ к JCK (Java Compatibility Kit) фирмы Sun, что позволит нам протестировать и (надеемся!) выпустить бинарную версию с использованием текущего набора патчей. К сожалению, мы не можем (по соображениям юридического плана) распространять JDK(R), который не работает с JCK, как мы могли это делать с релизами JDK(R) 1.1.*.
+
К несчастью, как утверждает фирма Sun (мы это *пока* не проверяли), работа над портом JCK - долгий и трудный процесс. Надеемся, что это не займёт у нас 3 месяцев, как предполагает Sun. :(
+
Наконец, остаётся ещё несколько проблем касательно Motif®, которые должны быть разрешены до выпуска полного релиза. Sun работает над этим, и нам нужно попытаться поработать с OpenGroup над получением особого разрешения на использование бинарных дистрибутивов Motif в релизе JDK(R).

== Май 2000

* *3 мая 2000:* Порт JDK(R) 1.2.2 для платформы FreeBSD вошёл в стадию альфа-тестирования +
Грег Льюис (Greg Lewis) только что объявил о том, что порт JDK(R) 1.2.2 для платформы FreeBSD перешёл в стадию альфа-тестирования. +
В том виде, в каком он имеется сейчас, порт будет строиться и работать на большинстве релизов FreeBSD (3.4, 4.0 и 5.0 для x86) и завершается работа над другими (2.2.8 для x86 и 4.0 alpha). Большинство демонстрационных приложений и апплет работают. +
Сейчас мы ищем энтузиастов, готовых потратить немного времени на тестирование нового порта. Хотя это нетривиальная задача, имеются чёткие пошаговые указания по построению и использованию порта. +
Патчи, как обычно, находятся по адресу +
http://www.eyesbeyond.com/freebsddom/java/jdk.html +
Дополнительная информация, открытые вопросы и пошаговые инструкции могут быть найдены по адресу: +
http://www.kjkoster.org/java/index.html
* *1 мая 2000:* Запрос на доработку - Теперь RFE номер 1 +
Мы обращались в компанию Sun с просьбой о создании официального порта JDK2 для FreeBSD. В настоящий момент в счётчике голосов мы занимаем *первое* место. Если вы являетесь участником Java Developer's Connection (это бесплатно), вы тоже можете проголосовать по адресу http://developer.java.sun.com/developer/bugParade/bugs/4288745.html

== Март 2000

* *22 марта 2000:* Выпущены пре-альфа патчи JDK(R) 1.2.2. +
Грег Льюис (Greg Lewis) выпустил пре-альфа патчи для корпоративных пользователей Java для построения из них собственных родных FreeBSD JDK(R) 1.2.2. Этот процесс не для слабонервных и получающийся JDK(R) не предназначен для работающих систем. Несмотря на это, большинство демонстрационных приложений AWT и Swing работают. Здесь ещё достаточно работы, и нам требуется как можно больше тестеров. Патчи и инструкции по построению могут быть сгружены с http://www.eyesbeyond.com/freebsd-jdk122-patches-latest.tar.gz. Текущий список открытых вопросов и результаты тестирования находятся по адресу http://www.kjkoster.org/java/index.html[http://www.kjkoster.org/java/index.html.]

== Январь 2000

* *30 января 2000:* Blackdown 1.2.2RC4 JDK(R) +
Команда Linux Blackdown Port Team выпустила RC4 пакета JDK(R) 1.2. Он был протестирован во FreeBSD 3.4-STABLE и более поздних релизах и с ним работают все демонстрационные апплеты и демонстрационные программы jfc. Несколько человек отметило некоторые проблемы при работе с Apache JServ. Пока он не добавлен в дерево портов FreeBSD, но может быть найден по адресу http://www.jmcm.org/tech/ports/linux_jdk.html. (Прислал Хосе Маркус /Jose Marques/)

== Ноябрь 1999

* *28 ноября 1999:* Запрос на доработку +
Мы направили в Sun петицию на создание официального порта JDK2 для FreeBSD. В настоящее время мы находимся на *втором* месте по количеству собранных голосов. Если вы являетесь участником Java Developer's Connection (это бесплатно), вы тоже можете проголосовать за нас по адресу http://developer.java.sun.com/developer/bugParade/bugs/4288745.html
* *9 ноября 1999:* Ещё один релиз &jdk; 1.1.8, в котором исправлен определённый тип ошибок в многоадресной рассылке.
** ftp://ftp.FreeBSD.org/pub/FreeBSD/ports/local-distfiles/nate/JDK1.1/jdk1.1.8_AOUT.V99-11-9.tar.gz[jdk1.1.8_AOUT.V99-11-9.tar.gz]. Для FreeBSD версий 2.2.*, в которых для выполнимых файлов используется формат A.OUT.
** ftp://ftp.FreeBSD.org/pub/FreeBSD/ports/local-distfiles/nate/JDK1.1/jdk1.1.8_ELF.V99-11-9.tar.gz[jdk1.1.8_ELF.V99-11-9.tar.gz]. Для FreeBSD версий 3.* и 4.*, в которых для выполнимых файлов используется формат ELF. Заметьте, что из-за некоторых изменений в -CURRENT, JDK(R) может работать неправильно.

== Октябрь 1999

* *11 октября 1999:* Начата работа над портированием Java2/JDK(R) 1.2. В ближайшие недели должен будет выйти ранний 'альфа' релиз для FreeBSD 3.3-stable/ELF.

== Сентябрь 1999

* *22 сентября 1999:* Ещё один выпуск &jdk; 1.1.8, в котором исправлены некоторые мелкие ошибки, найденные ранее, а также повышена производительность. Для выяснения подробностей обратитесь к файлу README.FreeBSD, который есть в релизах.
** jdk1.1.8_AOUT.V99-9-22.tar.gz. Для FreeBSD версий 2.2.*, в которых для выполнимых файлов используется формат A.OUT.
** jdk1.1.8_ELF.V99-9-22.tar.gz. Для FreeBSD версий 3.* и 4.*, в которых для выполнимых файлов используется формат ELF.

== Июль 1999

* *19 июля 1999:* Повторный релиз JDK(R) 1.1.8, в котором исправлено несколько маленьких (но неприятных) ошибок. Во-первых, netpatch (смотри ниже) был добавлен в исходные тексты, и во-вторых, была найдена и исправлена неприятная ошибка Floating Point. Последняя ошибка влияла на многопоточный код, который выполнял вычисления с плавающей точкой и в зависимости от результата мог выдавать абсолютно неверные результаты.
** jdk1.1.8_AOUT.V99-7-19.tar.gz. Для FreeBSD версий 2.2.*, в которых для выполнимых файлов используется формат A.OUT.
** jdk1.1.8_ELF.V99-7-19.tar.gz. Для FreeBSD версий 3.* и 4.*, в которых для выполнимых файлов используется формат ELF.
* *2 июля 1999:* Организация команды FreeBSD 'CommAPI', целью которой будет создание свободно доступного http://java.sun.com/products/javacomm/index.html[JAVA's CommAPI] для сообщества FreeBSD. Координатором проекта является mailto:jdricot@ulb.ac.be?subject=JAVA%20CommAPI:%20[DRICOT Jean-Michel] и располагается по адресу http://student.ulb.ac.be/~jdricot/commapi/. Обращайтесь туда, если хотите принять участие в проекте.

== Июнь 1999

* *8 июня 1999:* В релизе JDK(R) 1.1.8 была найдена небольшая ошибка, которая влияла на работу сокетов UDP. При попытке послать пакет на широковещательный адрес, FreeBSD JDK(R) его отвергал, выдавая ошибку прав доступа. Эта ошибка была исправлена, и вместо повторного выпуска релиза был выпущен небольшой набор патчей для тех, кто встретился с этой проблемой. Если вы столкнулись с такой проблемой, скачайте архив в формате tar.gz и распакуйте его там, где был установлен jdk. Он сам установится поверх старой версии. Если у вас указанной ошибки не возникает, применять патч вовсе не обязательно, хотя ни к чему страшному это не приведет.
** AOUT.netpatch.tar.gz. Для FreeBSD версий 2.2.*, в которых для выполнимых файлов используется формат A.OUT.
** ELF.netpatch.tar.gz. Для FreeBSD версий 3.* и 4.*, в которых для выполнимых файлов используется формат ELF.
* *3 июня 1999:* Релизы JDK(R) 1.1.8 для A.OUT и ELF. В этом релизе добавлена поддержка старых релизов 3.*/ELF (что не требует изменения загрузчика), а также исправлены ошибки в поддержке LOCALE и временной зоны для всех релизов FreeBSD.
** jdk1.1.8_AOUT.V99-6-3.tar.gz. Для FreeBSD версий 2.2.*, в которых для выполнимых файлов используется формат A.OUT.
** jdk1.1.8_ELF.V99-6-3.tar.gz. Для FreeBSD версий 3.* и 4.*, в которых для выполнимых файлов используется формат ELF.
* *1 июня 1999:* Статус JDK2
** Работа над JDK(R) 1.2/JDK2 продвигается очень медленно, так как команда разработчиков сфокусировала свои усилия на релизах JDK1. Для большинства из вопросов, касающихся разработки JDK2, вы можете использовать релиз JDK1 и релизы http://java.sun.com/products/jfc/index.html#download-swing[Swing], предоставляемые Sun для JDK1, которые прекрасно работают под FreeBSD.

== Апрель 1999

* *16 апреля 1999:* Новый A.OUT релиз JDK(R) 1.1.7. В нем исправлены проблемы при компиляции мартовского релиза. Новый ELF релиз будет выпущен в ближайшее время и в нем также будет включена поддержка старых релизов 3.0.
** jdk1.1.7_AOUT.V99-4-16.tar.gz. Для FreeBSD версий 2.2.*, в которых для выполнимых файлов используется формат A.OUT.

== Март 1999

* *26 марта 1999:* Поддержка ELF для JDK(R) 1.1.7, а также новый релиз в формате A.OUT, исправления мелких ошибок.
** jdk1.1.7_AOUT.V99-3-24.tar.gz. Для FreeBSD версий 2.2.*, в которых для выполнимых файлов используется формат A.OUT.
** jdk1.1.7_ELF.V99-3-25.tar.gz. Для FreeBSD версий 3.x и 4, в которых для выполнимых файлов используется формат ELF. *Замечание*: Это требует изменения в загрузчике для поддержки функциональности dladdr(), которая появилась 1999/3/24. Вам нужно работать с 3.1-stable или 4.0-current позже 1999/3/24. Если у вас нет нового загрузчика или вы не отслеживаете -stable или -current, вы можете скачать загрузчик link:ld-elf.so.1[отсюда] и установить его как /usr/libexec/ld-elf.so.1 (чтобы это сделать, вам нужно работать с привилегиями пользователя root):
+
....
# install -c -s -o bin -g bin -m 555 -C -fschg ld-elf.so.1 /usr/libexec
....
* *16 марта 1999:* Обновления в текущих разработках:
** ELF JDK(R) 1.1.7 : Построение JDK(R) 1.1.7 в формате ELF (для использования с FreeBSD 3.x и выше) перешло в фазу начального внутреннего тестирования. Бета-релиз должен появиться в течении нескольких недель.
** JDK2 (известный также как JDK(R) 1.2): Несколько человек работают над переносом JDK2 на FreeBSD, но работа продвигается медленно. Это происходит в основном из-за отсутствия времени для работы над этим проектом. (Выход порта Blackdown JDK2 поможет нашей разработке, когда они опубликуют diff-файлы для исходных текстов.)

== Декабрь 1998

* *21 декабря 1998:* jdk1.1.7.V98-12-21.tar.gz.
** Исправленная версия JDK(R) 1.1.7. Благодарности должны направляться Кейту Уайту, кто исправил несколько неприятных (и серьезных) ошибок в JDK(R), в частности, ошибка операций с модулями. В этом релизе также увеличено ограничение на количество файловых дескрипторов с 256 до 2048. JRE также более работоспособен, за что снова спасибо Кейту.

== Ноябрь 1998

* *14 ноября 1998:* jdk1.1.7.V98-11-5.tar.gz.
** Порт обновлен до JDK(R) 1.1.7. Благодарности должны направляться Пэтрику Гарделле (Patrick Gardella) patrick@FreeBSD.org, который выполнил основную работу по тестированию этого релиза.

== Сентябрь 1998

* *23 сентября 1998:* jdk1.1.6.V98-9-23.tar.gz.
** В выпуск от 14 августа включен неправильно скомпонованный jre, как для JDK(R), так и для JRE, так что релиз был перестроен и корректно скомпонован. Кроме этого, никаких отличий от старых релизов.

== Август 1998

* *22 августа 1998:*
** На обновленной странице помещен список различных сайтов, которые согласились зеркалировать JDK(R) и предоставлять доступ по ftp. Спасибо всем!
* *14 августа 1998:* jdk1.1.6.V98-8-14.tar.gz.
** Опция SO_REUSEADDR теперь устанавливается правильно для ServerSockets (может также влиять и на другие сокеты).

== Июль 1998

* *21 июля 1998:* jdk1.1.6.V98-7-21.tar.gz.
** Обновлен порт до JDK(R)1.1.6. Благодарности должны направляться Кейту Уайту (Keith White) kwhite@site.uottawa.ca, который сделал основной объем работы, приведший к выпуску этого релиза!
** Более стандартное 'именование' для java.version и тому подобное.
** Исправления, касающиеся сокетов UDP/Multicast.
** Ошибка прерывания сигнала, похоже, исправлена (стучим по дереву).
** Добавлена поддержка для кодировок "KOI8-R" и "CP866".
** Временные зоны теперь работают под FreeBSD корректно (что потребовало написания родного кода, однако он встроен в JDK(R), так что это не должно коснуться пользователей. Однако FreeBSD стала одной из нескольких (или единственной?) VM, корректно поддерживающих временные зоны.
** sysRmdir() теперь корректно удаляет каталоги.
** Для поддержки локализации CJK компоновка с библиотекой xpg4.

== Май 1998

* *5 мая 1998:*
** На обновленной страничке добавлена инструкция по настройке работы JWS (Java Work Shop) фирмы Sun на платформе FreeBSD.

== Февраль 1998

* *25 февраля 1998:* jdk1.1.5.V98-2-25.tar.gz.
** Построение JDK(R) для 2.2.2 теперь снова работает.
** Теперь AWT правильно устанавливает имя окна.
** Исправлена непонятная ошибка, приводящая к аварийному завершению работы при нажатии кнопки в диалоговом окне несколько раз.
** Исправлена ошибка, при которой SHMEM не освобождалась при работе с изображениями, что приводило к утечке памяти.
+
*12 февраля 1998:*
** Йохан Ларссон (Johan Larsson) любезно предоставил зеркальный ftp-сервер для JDK(R), так что если у вас есть предубеждение против использования HTTP, можете скачать его с этого сервера.
** Логотип 'Steaming Cup of Java' заменен на 'Jump to Java', который более политически (и юридически) грамотен с точки зрения SUN.
+
*9 февраля 1998:* jdk1.1.5.V98-2-8.tar.gz.
** Исправлены ошибки в Process.waitFor()
** Модифицирован способ компоновки библиотеки Motif. Это позволит всем, у кого имеется библиотека Motif (статическая или динамическая), строить JDK(R) самостоятельно при наличии набора соответствующих патчей. Если позволяет лицензия на Motif, можно будет распространять релизы в бинарном виде.
** Неблокирующее чтение из конвейера (pipe) работает ненадежно во всех версиях ОС.
** Многоадресная рассылка (мультикаст) теперь работает.

== Январь 1998

* *Январь 1998:*
** Организация команды разработчиков для портирования JDK(R) на FreeBSD, которая совместными усилиями делает новые релизы JDK(R) для FreeBSD.
** Новый JDK(R)1.1.5 в бинарном виде, со статически вкомпилированным Motif. (К сожалению, этот релиз был утерян из-за сбоя диска на ftp-сервере,)
