# $Id: Makefile,v 1.6 1998-08-09 16:22:19 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.2

.if exists(Makefile.conf)
.include "Makefile.conf"
.endif

DOCS=  
DOCS+=	programmers.sgml
DOCS+=	security.sgml
DOCS+=  secure.sgml

INDEXLINK= security.html

.include "../../web.mk"
