# $FreeBSD: www/en/releases/4.4R/Makefile,v 1.2 2001/09/19 19:43:18 bmah Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml notes.sgml

DATA=	docbook.css
DATA+=	errata.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
