---
title: "FreeBSD támogatás"
sidenav: support
---

= FreeBSD támogatás

A FreeBSD fejlõdését széles körben támogatja egy közösség és több kereskedelmi támogató. A honlap link:../community/[Közösség] szekciója részletezi a közösség által elérhetõ támogatási lehetõségeket, beleértve számos link:../community/mailinglists/[levelezési listát].

Kereskedelmi támogatás is igénybe vehetõ, rengeteg link:https://www.FreeBSD.org/commercial/[cég] kínál termékeket, szolgáltatásokat és/vagy szaktanácsadást a FreeBSD-hez.

== Hibajelentés

Hibát találtunk a FreeBSD-ben? Téves információra akadtunk a dokumentációban? Jelezzük, ha a hibát eddig még nem jelentették!

Az jelentett hibák ellenõrzéséhez link:https://www.FreeBSD.org/cgi/query-pr-summary.cgi?query[kereshetünk a hibajelentések adatbázisában], kategória, felelõs, beküldõ, a hibajelentés szövege stb. szerint, vagy megnézhetjük az link:https://www.FreeBSD.org/cgi/query-pr-summary.cgi?category=[összes nyitott hibajelentést].

Ha a hibát még nem jelentették, olvassuk el a link:../support/bugreports/[a hibajelentési irányelveket] és jelentsük a hibát a link:https://bugs.freebsd.org/submit/[hibajelentési ûrlapunk segítségével].
