---
title: "Hibajelentések"
sidenav: support
---

include::shared/hu/urls.adoc[]

= Hibajelentések

== A hibajelentések adatbázisa

Az aktuális FreeBSD hibajelentések nyomkövetését a http://www.gnu.org/software/gnats/[GNATS] rendszer végzi.

Egy FreeBSD hibajelentés (Problem Report, PR) nem feltétlen egy FreeBSD-t érintõ hiba leírása. Esetenként lehet egy hiba a dokumentációban (akár egy egyszerû elírás), máskor viszont lehet egy "`kívánságlista`", amely azt tartalmazza, hogy a beküldõ mit látnánk szívesen a FreeBSD-ben. Sok esetben a PR egy portot tartalmaz, amelyet a FreeBSD link:https://www.FreeBSD.org/ports/[Portgyûjteménye] részére készítettek elõ.

A hibajelentés kezdeti állapota "`nyílt`", és akkor válik lezárttá, ha a hozzá tartozó hiba kijavult. Továbbá, minden PR-hoz tartozik egy egyedi azonosító, amellyel nyomonkövethetõ, így biztosítható, hogy a jelentés nem veszett el. Sok módosítás a FreeBSD-ben magában foglalja, hogy melyik azonosító tartozik ahhoz a jelentéshez, amely az adott változtatást indokolta.

* http://www.FreeBSD.org/cgi/query-pr-summary.cgi[A nyitott hibajelentések megtekintése vagy keresése]
* link:https://bugs.freebsd.org/submit/[Hibajelentés küldése]
* link:https://www.FreeBSD.org/prstats/[A PR statisztikák megtekintése]

== Hibajelentések küldése

Hibajelentések a FreeBSD rendszereken található link:https://www.FreeBSD.org/cgi/man.cgi?query=send-pr&sektion=1[send-pr(1)] paranccsal küldhetõek be. Hibajelentéseket ezenkívül még webes link:https://bugs.freebsd.org/submit/[ûrlapon] is küldhetünk, vagy a freebsd-bugs@FreeBSD.org címre küldött e-maileken keresztül. A fejlesztõk a link:https://bugs.freebsd.org/submit/[send-pr] használatát részesítik elõnyben, mivel a levelezési listára küldött üzeneteket _nem_ követi nyomon a rendszer mint hivatalos hibajelentéseket, ezért könnyen "`elveszhetnek`" a listára érkezõ levéláradatban.

Mielõtt beküldenénk egy hibajelentést, érdemes lehet elolvasnunk a link:{problem-reports}[FreeBSD hibajelentések írásáról] szóló cikket. Ebbõl megtudhatjuk, milyen esetekben szükséges hibajelentést küldeni, miket kell benne megemlíteni és mi a legjobb módja, hogy elküldjük. Néhány egyéb háttérinformáció is megtalálható link:{pr-guidelines}[a FreeBSD hibajelentések kezelésének irányelveit] ismertetõ cikkben.
