# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/man/Makefile.inc,v 1.3 2003/09/04 21:24:22 ru Exp $

MANDIR=		${SHAREDIR}/man/ru_RU.KOI8-R/man
MROFF_CMD=	groff -Tkoi8-r -mtty-char -man -t -dlocale=ru.KOI8-R
