# $FreeBSD$
# $FreeBSDde: de-www/support/Makefile,v 1.1 2005/10/24 20:40:42 jkois Exp $
# basiert auf: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS= bugreports.xml
DOCS+= webresources.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
