---
title: "Замечания по установке FreeBSD 14.4-RELEASE"
sidenav: download
---

:releaseCurrent: 14.4-RELEASE
:releasePrev: 14.3-RELEASE
:releasePrevLegacy: 13.5-RELEASE
:localRel: 14.4

include::shared/ru/urls.adoc[]

= Замечания по установке FreeBSD {localRel}-RELEASE

== Аннотация

Эта статья содержит краткие инструкции по установке FreeBSD {releaseCurrent} и обновлению систем, работающих под более ранними выпусками.

== Содержание

* <<install,Установка FreeBSD>>
* <<upgrade,Обновление FreeBSD>>

[[install]]
== Установка FreeBSD

Глава link:{handbook}bsdinstall/[Установка FreeBSD] Руководства FreeBSD предоставляет более подробную информацию о самой программе установки, включая пошаговое руководство со скриншотами.

[[upgrade]]
== Обновление FreeBSD

Если вы обновляетесь с предыдущего выпуска FreeBSD, пожалуйста, внимательно прочитайте раздел об обновлении в link:../relnotes[Информации о релизе] для ознакомления с важными несовместимостями.

[[upgrade-source]]
== Обновление из исходного кода

Процедура обновления на основе исходного кода описана в link:{handbook}cutting-edge/#makeworld[Обновление FreeBSD из исходного кода].

Для Git используйте ветку releng/{localRel}, где будут применяться будущие рекомендации по безопасности или уведомления об ошибках.

[[upgrade-binary]]
== Обновление с помощью "FreeBSD Update"

Утилита man:freebsd-update[8] поддерживает бинарные обновления систем amd64 и arm64, работающих под более ранними выпусками FreeBSD.
Системы, работающие под {releasePrev}, могут обновиться следующим образом:

[.screen]
----
# freebsd-update fetch
# freebsd-update install
----

[IMPORTANT]
====
Этот шаг является обязательным, так как обновление до {releaseCurrent} без применения исправлений и дополнений FreeBSD-EN-25:18.freebsd-update приведет к неработоспособности системы!
====

Теперь утилита man:freebsd-update[8] может получать компоненты, принадлежащие {releaseCurrent}.
В ходе этого процесса man:freebsd-update[8] попросит помощи в слиянии конфигурационных файлов.

[.screen,subs="verbatim,attributes"]
----
# freebsd-update upgrade -r {localRel}-RELEASE
# freebsd-update install
----

Теперь система должна быть перезагружена с новым установленным ядром перед обновлением компонентов, не относящихся к ядру.

[.screen]
----
# shutdown -r now
----

После перезагрузки необходимо снова запустить man:freebsd-update[8] для установки новых компонентов пользовательского пространства:

[.screen]
----
# freebsd-update install
----

На этом этапе пользователям систем, обновляемых с более ранних выпусков FreeBSD, будет предложено пересобрать или переустановить все сторонние приложения (например, порты, установленные из дерева портов, или пакеты, установленные с помощью man:pkg[8]) из-за обновлений в системных библиотеках.

После обновления установленных сторонних приложений (и снова, только если man:freebsd-update[8] вывел сообщение, указывающее на необходимость этого), запустите man:freebsd-update[8] снова, чтобы он мог удалить старые (больше не используемые) системные библиотеки:

[.screen]
----
# freebsd-update install
----

Наконец, перезагрузитесь в полностью {releaseCurrent} систему:

[.screen]
----
# shutdown -r now
----

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (15.10.2025): fdb916e1c318b87a24b66ce62efd7e5d9e72f926
//
