# $FreeBSD$
#
# The FreeBSD Documentation Project
# The FreeBSD Spanish Documentation Project
#
# Article: Contributing
#

MAINTAINER=carlavilla@FreeBSD.org

DOC?= article

FORMATS?= html html-split

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

WITH_ARTICLE_TOC?=YES

SRCS= article.xml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
