---
title: "FreeBSD 3.3 Announcement"
sidenav: download
--- 

= FreeBSD 3.3 Announcement

*Date:* Fri, 17 Sep 1999 05:06:44 -0700 +
*From:* "Jordan K. Hubbard" <jkh@freebsd.org> +
**Subject:**FreeBSD 3.3-RELEASE is now available.

Yes, it's that time again! I'm very happy to announce the availability of FreeBSD 3.3-RELEASE, the latest in our line of releases from the 3.x-STABLE branch. The follow-on to FreeBSD 3.2 (released in May, 1999), a lot of new drivers have been added, many bugs were fixed and several important security issues where dealt with. Please see the link:../notes/[release notes] for more information.

FreeBSD 3.3-RELEASE is available at ftp://ftp.freebsd.org/pub/FreeBSD[ftp.freebsd.org] and various https://www.FreeBSD.org/handbook/mirrors.html[FTP mirror sites] throughout the world. It can also be ordered on CD from http://www.freebsdmall.com/[The FreeBSD Mall], from where it will be shipping soon on a 4 CD set containing installation bits for the x86 architectures, as well a lot of other material of general interest to programmers and end-users alike. (3.3-RELEASE for the Alpha architecture is available from the FTP site).

NOTE: All of the profits from the sales of this CD set go to support the FreeBSD Project! We are also trying something new with 3.3-RELEASE in making ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/ISO-IMAGES/3.3-install.cd0[disc #1] from Walnut Creek CDROM's official distribution available via ftp://ftp.freebsd.org/pub/FreeBSD/[anonymous FTP.] This is the most important CD of their 4 set, one which will allow users to install the base system and all of its most important add-ons from a single ISO 9660 image. We are doing this because the ISO image is rapidly becoming the preferred format for distributing operating system releases and we're certainly not going to go out of our way to make FreeBSD harder to "test drive" if providing the standard NFS/FTP network installation methods is no longer enough. We can't promise that all the mirror sites will carry the rather large installation (660MB) image, but it will at least be available from:

ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/ISO-IMAGES/3.3-install.cd0.

along with the more traditional 3.3-RELEASE bits. If you can't afford the CDs, are impatient, or just want to use it for evangelism purposes, then by all means download the ISO, otherwise please do continue to support the FreeBSD project by purchasing one of its official CD releases from http://www.freebsdmall.com[Walnut Creek CDROM].

The official FTP distribution site for FreeBSD is:

____
ftp://ftp.FreeBSD.org/pub/FreeBSD
____

Or via the WEB page at:

____
http://www.freebsdmall.com
____

and

____
http://www.cdrom.com
____

And directly from Walnut Creek CDROM:

____
Walnut Creek CDROM +
4041 Pike Lane, #F +
Concord CA, 94520 USA +
Phone: +1 925 674-0783 +
Fax: +1 925 674-0821 +
Tech Support: +1 925 603-1234 +
Email: info@cdrom.com +
WWW: http://www.cdrom.com/
____

Additionally, FreeBSD is available via anonymous FTP from link:../../handbook/mirrors.html[mirror sites] in the following countries: Argentina, Australia, Brazil, Bulgaria, Canada, the Czech Republic, Denmark, Estonia, Finland, France, Germany, Hong Kong, Hungary, Iceland, Ireland, Israel, Japan, Korea, Latvia, Malaysia, the Netherlands, Poland, Portugal, Romania, Russia, Slovenia, South Africa, Spain, Sweden, Taiwan, Thailand, the Ukraine and the United Kingdom (and quite possibly several others which I've never even heard of :).

Before trying the central FTP site, please check your regional mirror(s) first by going to:

____
ftp://ftp.<yourdomain>.freebsd.org/pub/FreeBSD
____

Any additional mirror sites will be labeled ftp2, ftp3 and so on.

The latest versions of export-restricted code for FreeBSD (2.0C or later) (eBones and secure) are also being made available at the following locations. If you are outside the U.S. or Canada, please get secure (DES) and eBones (Kerberos) from one of the following foreign distribution sites:

South Africa::
  ftp://ftp.internat.FreeBSD.ORG/pub/FreeBSD +
  ftp://ftp2.internat.FreeBSD.ORG/pub/FreeBSD
Brazil::
  ftp://ftp.br.FreeBSD.ORG/pub/FreeBSD
Finland::
  ftp://nic.funet.fi/pub/unix/FreeBSD/eurocrypt

link:../../[Release Home]
