=== FreeBSD on Microsoft HyperV and Azure

Links: +
link:https://wiki.freebsd.org/MicrosoftAzure[Microsoft Azure article on FreeBSD wiki] URL: link:https://wiki.freebsd.org/MicrosoftAzure[] +
link:https://wiki.freebsd.org/HyperV[Microsoft HyperV article on FreeBSD wiki] URL: link:https://wiki.freebsd.org/HyperV[]

Contact: Microsoft FreeBSD Integration Services Team <bsdic@microsoft.com> +
Contact: link:https://lists.freebsd.org/subscription/freebsd-cloud[freebsd-cloud Mailing List] +
Contact: The FreeBSD Azure Release Engineering Team <releng-azure@FreeBSD.org> +
Contact: Wei Hu <whu@FreeBSD.org> +
Contact: Souradeep Chakrabarti <schakrabarti@microsoft.com> +
Contact: Li-Wen Hsu <lwhsu@FreeBSD.org> +

In this quarter, we have published the link:https://azuremarketplace.microsoft.com/marketplace/apps/thefreebsdfoundation.freebsd-14_1[14.1-RELEASE on Azure Marketplace].
Souradeep Chakrabarti from Microsoft has improved the TLB flushing mechanism in Azure.

Work in progress tasks:

* Automating the image building and publishing process and merging to [.filename]#src/release/#.
* Building and publishing snapshot builds to link:https://learn.microsoft.com/azure/virtual-machines/share-gallery-community[Azure community gallery].
* Testing adding FreeBSD support in link:https://azure.microsoft.com/products/devops/pipelines/[Azure Pipelines]
** https://github.com/microsoft/azure-pipelines-agent/pull/3266[]

The above tasks are sponsored by The FreeBSD Foundation, with resources provided by Microsoft.

Open tasks:

* Update FreeBSD-related doc at link:https://learn.microsoft.com[Microsoft Learn]
* Update package:sysutils/azure-agent[] to the latest version
* Upstream link:https://github.com/Azure/WALinuxAgent/pull/1892[local modifications of Azure agent]
* Port link:https://github.com/Azure/azure-linux-extensions[Linux Virtual Machine Extensions for Azure]

Sponsor: Microsoft for people in Microsoft, and for resources for the rest +
Sponsor: The FreeBSD Foundation for everything else
