=== FreeBSD Core Team

Contact: FreeBSD Core Team <core@FreeBSD.org>

The FreeBSD Core Team is the governing body of FreeBSD.

==== DevSummit 202405

The Core Team has presented the status update at the DevSummit 202405.
Details are available at link:https://wiki.freebsd.org/DevSummit/202405[]

==== Passing of Mike Karels

It is with a heavy heart that we have learned of Mike Karels' recent passing.
We want to offer our sincere condolences to his family, friends, and the community for this loss.
Mike was an inspirational fellow developer and will be sorely missed.

link:https://lists.freebsd.org/archives/freebsd-announce/2024-June/000135.html[In Memory of Mike Karels].

For more details about him, please visit the FreeBSD Foundation's page at:

link:https://freebsdfoundation.org/mike_karels/[]

==== 2024 Core Team Election

Core.12 appointed Muhammad Moinur Rahman (bofh@) and Allan Jude (allanjude@) as the managers of the 2024 Core Team election.
After Allan decided to run for Core, Moin continued to handle all the election tasks independently.

The result was announced on June 12th, with 8 members:

* Allan Jude (allanjude@)
* Dave Cottlehuber (dch@)
* Gleb Smirnoff (glebius@)
* Hiroki Sato (hrs@)
* Li-Wen Hsu (lwhsu@)
* Mathieu Arnold (mat@)
* Olivier Cochard (olivier@)
* Tobias C. Berner (tcberner@)

Mike Karels has run for the 2024 Core Team election, and was in the top nine candidates in the result.
After a discussion, core.13 came to the conclusion that the eight members will serve as the new team.

Core.13 takes office on June 12th, and hold the handover meeting with core.12 on June 21st.

The project thanks the outgoing core.12 members for their service in the last two years:

* Baptiste Daroussin (bapt@)
* Benedict Reuschling (bcr@)
* Ed Maste (emaste@)
* Greg Lehey (grog@)
* John Baldwin (jhb@)
* Emmanuel Vadot (manu@)
* Mateusz Piotrowski (0mp@)

==== Commit bits

* Core approved the src commit bit for Osama Abboud (osamaabb@)
* Core reactivated the src commit bit for Ryan Libby (rlibby@)
