=== FreeBSD Erlang Ecosystem Ports update

Links: +
link:https://wiki.freebsd.org/Erlang[FreeBSD Erlang wiki] URL: link:https://wiki.freebsd.org/Erlang[] +
link:https://erlang.org/[Erlang/OTP language] URL: link:https://erlang.org/[] +
link:https://elixir-lang.org/[Elixir language] URL: link:https://elixir-lang.org/[] +
link:https://gleam.run/[Gleam language] URL: link:https://gleam.run/[] +

Contact: FreeBSD Erlang mailing list <erlang@FreeBSD.org>

The Erlang runtime system, commonly known as the BEAM, provides a runtime that is used by a number of programming languages and applications in the FreeBSD ports collection.

Notable changes in 2024 include:

* adding OTP27, the latest Erlang runtime release, Elixir 1.17, and Gleam 1.20
* more than 57 point release updates so far in 2024
* improved inline documentation within Erlang ports
* moved RabbitMQ port to the generic UNIX build, decoupling this from Elixir as a build-time dependency.
This enables moving RabbitMQ to the latest supported release.
Users of RabbitMQ need to update each quarter to avoid being stuck on an unsupported release of Erlang/OTP + RabbitMQ

Note that as the upstream Erlang OTP team only commit to supporting the two latest major releases, more and more point updates are arriving for OTP26-27, but not for the older Erlang runtime releases, which are now unlikely to get security and bug fixes.

During 2024Q3, the Erlang team is planning to:

* migrate the base package:lang/erlang[] port to OTP26 and update related dependencies

Additional testing and community contributions are welcome, please reach out on the mailing list, especially if you are able to help testing of specific port updates.
