=== GCC on FreeBSD

Links: +
link:https://gcc.gnu.org/[GCC Project] URL: link:https://gcc.gnu.org/[] +
link:https://gcc.gnu.org/gcc-11/[GCC 11 release series] URL: link:https://gcc.gnu.org/gcc-11/[] +
link:https://gcc.gnu.org/gcc-12/[GCC 12 release series] URL: link:https://gcc.gnu.org/gcc-12/[] +
link:https://gcc.gnu.org/gcc-13/[GCC 13 release series] URL: link:https://gcc.gnu.org/gcc-13/[] +
link:https://gcc.gnu.org/gcc-14/[GCC 14 release series] URL: link:https://gcc.gnu.org/gcc-14/[] +

Contact: Lorenzo Salvadore <salvadore@FreeBSD.org>

Upstream has released link:https://gcc.gnu.org/gcc-14[GCC 14.1].
Therefore port package:lang/gcc-14[] has been created, as well as package:lang/gcc15-devel[] which tracks the new latest development GCC version.
Previous major versions of GCC are being updated as well.

Only very little work has been done on existing bugs for GCC ports this quarter, contrary to the original plan stated in the precedent report.
This is due to the fact that I noticed an increasing interest in upstream to support GCC on FreeBSD, which however gets blocked by the fact that GCC sources do not build out-of-the-box on our platform, but needs instead many patches which are in our ports tree framework.
It is then necessary to focus on upstreaming all of those patches, possibly at once and not one at the time as it has been done until now, and to also regularly run the tests suite, fixing all tests that fail.
Then I am working on a new setup of automation that allows me to build and test all supported GCC versions as efficiently as possible, including GCC from sources but without the ports tree framework support.
All of this has significantly slowed down usual GCC ports maintainership (users of the -devel ports have probably noticed that they are being updated much less frequently), but I am confident that it will eventually pay off.

It should also be noted that mailto:fuz@FreeBSD.org[Robert Clausecker] has enabled package:lang/gcc11[], package:lang/gcc12[], and package:lang/gcc13[] for riscv64 architecture as the ports build fine on 15-CURRENT.
