=== FreeBSD Release Engineering Team

Links: +
link:https://www.freebsd.org/releases/14.1R/announce/[FreeBSD 14.1-RELEASE announcement] URL: link:https://www.freebsd.org/releases/14.1R/announce/[] +
link:https://www.freebsd.org/releases/13.4R/schedule/[FreeBSD 13.4-RELEASE schedule] URL: link:https://www.freebsd.org/releases/13.4R/schedule/[] +
link:https://download.freebsd.org/releases/ISO-IMAGES/[FreeBSD releases] URL: link:https://download.freebsd.org/releases/ISO-IMAGES/[] +
link:https://download.freebsd.org/snapshots/ISO-IMAGES/[FreeBSD development snapshots] URL: link:https://download.freebsd.org/snapshots/ISO-IMAGES/[]

Contact: FreeBSD Release Engineering Team, <re@FreeBSD.org>

The FreeBSD Release Engineering Team is responsible for setting and publishing release schedules for official project releases of FreeBSD, announcing code freezes and maintaining the respective branches, among other things.

The Team mourns the loss of Mike Karels, who was the Deputy Release Engineering Lead and mere days before his death agreed to take the role of Release Engineer for 13.4-RELEASE.

The Team managed 14.1-RELEASE, leading to the final RELEASE build and announcement in June.
During the second quarter of the year, the Team has gained new members: Ed Maste (Deputy Release Engineer Lead), Dave Cottlehuber, John Hixson, Mahdi Mokhtari, Doug Rabson, Muhammad Moinur Rahman.
Planning has started for the upcoming 13.4-RELEASE cycle.

The Release Engineering Team continued providing weekly development snapshot builds for the *main*, *stable/14*, and *stable/13* branches.
