---
title: "Règles établies par l'équipe principale"
sidenav: docs
--- 

= Règles établies par l'équipe principale

Ces règles ont été approuvées par un vote des participants actifs ("committers") le 28 Août 2000.

* Les participants actifs doivent avoir apportés au moins une modification aux sources dans les 12 derniers mois.
* L'équipe principale est composée de 9 participants actifs élus.
* L'élection de l'équipe principale a lieu tous les 2 ans, la première s'étant tenue en Septembre 2000.
* Les membres de l'équipe principale ainsi que les participants actifs peuvent être exclus par un vote des 2/3 de l'équipe principale.
* Si le nombre de membres de l'équipe principale devient inférieur à 7, une élection anticipée est organisée.
* Une pétition d'un tiers des participants actifs peut provoquer une élection anticipée.
* Toutes les élections se déroulent de la façon suivante :
** L'équipe principale désigne une personne chargée d'organiser l'élection.
** 1 semaine pour établir la liste des participants actifs qui souhaitent être candidat.
** 4 semaines pour le vote
** 1 semaine pour comptabiliser les votes et communiquer les résultats.
** Chaque participant actif peut voter une seule fois pour soutenir jusqu'à neuf candidats.
** La nouvelle équipe principale devient effective 1 semaine après la communication des résultats.
** Les cas d'égalités sont départagés par les membres de la nouvelle équipe principale qui ont été élus sans ambiguïtés.
* Ces règles peuvent être changées à la majorité des 2/3 des participants actifs si au moins 50% des participants actifs votent.

== Information complémentaire

La dernière élection de l'équipe principale s'est tenue en juin 2004. La prochaine est prévue pour juin 2006.

== Interprétations des règles par l'équipe principale

L'équipe principale donnera de temps à autre des interprétations de ces règles afin de clarifier les points qui pourraient être ambigus de manière à assurer un fonctionnement sans problème du projet.

* *03/05/2002* La prochaine élection est toujours prévue 2 ans après la précédente élection. Cela signifie qu'une élection anticipée remets à zéro la date de l'élection suivante de manière à ce qu'elle se déroule deux ans après l'élection anticipée.

link:../developer[Ressources pour les participants à FreeBSD - Accueil]
