---
title: "Procédures de vote de l'équipe principale ('core')"
sidenav: docs
--- 

= Procédures de vote de l'équipe principale ("core")

== Participants ("committers")

* Tous les membres de l'équipe principale votent "oui", "non" ou "sans objection".
* Les candidats acceptés doivent avoir au moins un vote "oui".
* Les candidats acceptés ne doivent avoir aucun vote "non".
* Au moins 3 personnes doivent voter.
* La période de vote est normalement de 1 semaine ou s'achève dès que le résultat est certain.
* Le secrétaire de l'équipe principale est en charge des détails du scrutin, des notifications, etc.

== Personnel

* Tous les membres de l'équipe principale votent "oui" ou "non".
* Les candidats acceptés doivent avoir au moins (2/3 * nb de personnes de l'équipe principale) de votes "oui".
* Au moins (2/3 * nb de personnes de l'équipe principale) de personnes doivent voter ou la mesure échoue.
* La période de vote est normalement de 1 semaine ou s'achève dès que le résultat est certain.
* Le secrétaire de l'équipe principale est en charge des détails du scrutin, des notifications, etc.

== Problèmes

* Le débat s'instaure.
* Lorsque qu'un consensus sur une résolution est atteint, un vote est organisé.
* Tous les membres de l'équipe principale votent "oui" ou "non".
* Les résolutions acceptées doivent avoir au moins (2/3 * nb de personnes de l'équipe principale) de votes "oui".
* Au moins (2/3 * nb de personnes de l'équipe principale) de personnes doivent voter ou la mesure échoue.
* La période de vote est normalement de 1 semaine ou s'achève dès que le résultat est certain.
* Le secrétaire de l'équipe principale est en charge des détails du scrutin, des notifications, etc.

== Sans objection

* Chaque membre de l'équipe principale peut demander à celle-ci, par courrier électronique, s'il peut entreprendre une action courante, sujette à une rapide vérification de routine de la part des autres membres de l'équipe.
* S'il n'y a aucune objection dans les 48 heures, cette personne peut alors procéder (ou bien dès que (2/3 * nb de personnes de l'équipe principale) des membres ont voté "oui").
* S'il y a la moindre objection, alors la procédure concernant les problèmes est utilisée.
* Le secrétaire de l'équipe principale peut envoyer un accord formel s'il le juge nécessaire.

Chaque participant utilise également cette procédure aussi longtemps qu'un membre de l'équipe principale vote "oui" et que le reste du paragraphe précédent est respecté. Cette procédure vise à régler les problémes courants qui ne nécessitent qu'une rapide vérification de routine, pas ceux nécessitant une procédure plus lourde et sujets à délibération. Il est admis qu'un nombre suffisant de membres de l'équipe principale est présent par tranche de 48h pour soit régler les problémes de vérification de routine, soit reconnaître un problème qui nécessite de passer par la procédure de résolution des problémes.
