---
title: "Procédure de création d'un nouveau compte"
sidenav: docs
---

include::shared/fr/urls.adoc[]

= Procédure de création d'un nouveau compte

== Proposer un nouveau committer

Si vous désirez proposer un nouveau committer, vous devez envoyer les informations suivantes à l'entité appropriée :

* Les antécédents (en rapport avec FreeBSD) de la personne proposée. Ce _n'est pas_ facultatif; c'est devenu une pratique courante ces derniéres années.
* Le nom de la personne se portant volontaire pour devenir le mentor du nouveau committer.
* L'adresse électronique de la personne proposée (trop souvent oubliée).

Toute proposition de nouveau committer ne respectant pas les règles décrites ci-dessous sera retardée (au mieux) ou vous rapporterons de mauvaises vibrations de l'équipe respective/du secrétaire de l'équipe.

Les parties responsables de cette procédure sont :

* src --> core@
* doc --> doceng@
* ports --> portmgr@

Vous recevrez un AR après que le message ait été vu, et core@ et doceng@ vous donneront une réponse en <= 7 jours. Leur délai d'expiration est fixé à 7 jours. Le délai pour portmgr@ est de 14 jours. Si le vote se finit plus tôt, la personne ayant proposé le nouveau committer et celui-ci sont informés du résultat plus tôt.

== Autorisation d'un nouveau compte

Une personne de la liste ci-dessous envoie un courrier électronique signé en PGP à l'adresse admins@FreeBSD.org, à la personne désignée comme mentor du nouveau participant et en copie à l'adresse core@FreeBSD.org pour confirmation de l'approbation du nouveau compte. Ce courrier électronique doit inclure un lien vers ce document afin que le mentor/le nouveau participant sachent ce qu'ils doivent faire.

L'approbation d'un nouveau compte est uniquement valide à partir de ces entités PGP :

* core-secretary
* portmgr-secretary
* doceng

_NOTE : les demandes de nouveau compte faites par quiconque en dehors de ces entités ou les demandes signées avec d'autres clefs PGP ne seront pas acceptées. Il n'y a aucune exception. En cas d'un nouveau committer ports ou doc le courrier de demande de compte doit être faite avec core en copie._

== Informations à fournir par le mentor

La personne désignée comme mentor du nouveau committer doit demander puis envoyer les informations suivantes à l'adresse admins@FreeBSD.org :

* la ligne `master.passwd` contenant le nom d'utilisateur désiré, le shell et les informations GECOS (aucun mot de passe n'est nécessaire)
* la clef publique ssh V2 (*version 2 UNIQUEMENT*)

Le mentor est chargé d'obtenir ces informations du nouveau committer de manière sécurisée, et de les fournir à admins@ d'une manière sécurisée. Un courrier électronique signé avec PGP, avec la clé publique du mentor déjà comprise dans le manuel, est la méthode préférée pour que le mentor envoie ces informations à admins@. Si ceci est impossible pour une raison ou pour une autre, un substitut acceptable est que le mentor place les informations du compte dans son répertoire personnel sur freefall et de dire à admins@ où les trouver. Nous devons nous assurer que les informations proviennent vraiment du mentor et un courrier non signé n'est pas suffisant de nos jours. Puisque admins@ ne peut rien vérifier sur le nouveau committer ces informations doivent être envoyées à admins@ par le mentor, et non par le nouveau committer.

== admins@FreeBSD.org créé le nouveau compte

admins@FreeBSD.org créé le nouveau compte à partir des informations données sur le cluster FreeBSD.org et en informe le mentor et le nouveau committer.

== Le mentor active les droits de commit du nouveau participant

Après que le nouveau participant ait confirmé que son compte fonctionne, le mentor active ses droits de commit et le guide dans la suite du processus.

== Fin du mentorat

Il n'y a pas de durée prédéterminée pour un mentorat. Une fois que le mentor juge que le nouveau est prêt à voler de ses propres ailes, le mentor en fait part à la communauté des développeurs avec un commit forcé sur `access` avec un message de commit approprié.

== Transfert de mentorat

Si le besoin d'un transfert de mentorat pour un committer se fait sentir veuillez contacter par courrier électronique la partie responsable, comme pour la proposition d'un nouveau compte. Typiquement cette demande est acceptée telle quelle. Un commit forcé sur `access` avec un message de commit approprié doit informer tout le monde de ce transfert.
