---
title: "Gallerie de photo"
sidenav: docs
---

include::shared/authors.adoc[]
include::shared/fr/urls.adoc[]

= Gallerie de photo

== USENIX 2004, à Boston, juin 2004

http://apollo.backplane.com/USENIX2004/[Photos] de l'événement par mailto:dillon@backplane.com[Matt Dillon].

== 20th Chaos Communication Congress, à Berlin, décembre 2003

http://gallery.daemon.li/20c3/[Photos] de l'événement par mailto:josef@FreeBSD.org[Josef].

== FreeBSD 10 Year Anniversary Party, à San Francisco, novembre 2003

http://apollo.backplane.com/pics.bsdparty/[Photos] de l'événement par mailto:dillon@backplane.com[Matt Dillon].

== BSDCon 2003, à San Mateo, septembre 2003

http://apollo.backplane.com/BSDCON2003/[Photos] de l'événement par mailto:dillon@backplane.com[Matt Dillon].

== LinuxTag 2003, à Karlsruhe, juillet 2003

http://gallery.daemon.li/linuxtag/[Photos] du Linuxtag de mailto:josef@FreeBSD.org[Josef].

== BSDCon Europe 2002, à Amsterdam, novembre 2002

http://people.FreeBSD.org/~wilko/EuroBSDcon2002/[Photos] Photos et commentaires de mailto:wilko@FreeBSD.org[Wilko].

== USENIX 2002, à Monterey, juin 2002

http://apollo.backplane.com/USENIX2002/[Photos] de l'événement par mailto:dillon@backplane.com[Matt Dillon].

== BSDCon Europe 2001, à Brighton, novembre 2001

http://2001.eurobsdcon.org/pictures/[Photos]

== BSDCon 2000, à Monterey, octobre 2000

Photos de http://people.FreeBSD.org/~will/bsdcon/[Will]

== http://people.FreeBSD.org/~jkh/lw200/[]LinuxWorld 2000, février 2000

Photos de mailto:jkh@FreeBSD.org[jkh].

== http://www.de.FreeBSD.org/de/gif/berlin-1999-10-09/[Rencontre BSD à Berlin, octobre 1999]

== http://people.FreeBSD.org/~nik/Oxford/index.html[Réunion FreeBSD à Oxford (GB), novembre 1998]

Photos et textes de mailto:nik@FreeBSD.org[Nik]. Organisé par Paul Richards.

== Réunion FreeBSD en Hollande, octobre 1998

Photos de http://people.FreeBSD.org/~jkh/holland/[Jordan] et http://www.tcja.nl/hackersparty/[Wilko]

== http://www.de.FreeBSD.org/de/gif/hamburg-1998-06-20/index.html[Rencontre BSD à Hambourg, juin 1998]

Aled Morris, Andre Oppermann, Andreas Klemm, Andrew Gordon, Christoph Badura, Dirk Meyer, Frank Nobis, Harald Klatte, Joerg Wunsch, Jonathan Laventhol, Lars Gerhard Kuehl, Martin Cracauer, Stefan Bethke, Stefan Esser, Stefan Huerter, Stefan Zehl, Stephan Forth, Thomas Gellekum

== http://www.lemis.com/grog/auug98.html[Conférence de printemps de l'AUUG à Sydney, septembre 1998]

Richard Stallman, Peter Wemm, Mark White, Andrew McRae, Greg Rose, plusieurs personnes non identifiés.

== http://people.FreeBSD.org/~grog/usenix.html[USENIX de l'été 1998, Nouvelle-Orléans]

Branson, David Greenman, David O'Brien, Greg Lehey, Guido van Rooij, John Polstra, Jonathan Bresler, Jordan Hubbard, Justin Gibbs, Luigi Rizzo, Mark Murray, Mike Smith, Monique van Rooij, Ollivier Robert, Philippe Regnauld, Poul-Henning Kamp, Sharon, Steve Mann

== http://www.de.FreeBSD.org/de/gif/aachen-19950902/[Rencontre FreeBSD à Aachen, 1995]

Aled Morris, Christoph Kukulies, Guido van Rooij, Jonathan Leventhol, Jörg Wunsch, Martin Welk, Michael Reifenberger, Patrick Hausen, Paul Richard, Paul Richards, Poul-Henning Kamp, René de Vries, Stefan Esser, Ulf Kieber, Wilko Bulte

link:..[Les coulisses de FreeBSD]
