---
title: "Rapports de statuts FreeBSD"
sidenav: about
---

= Rapports de statuts FreeBSD

== Prochaines soumissions : 7 Juillet 2006

Utilisez le http://www.FreeBSD.org/cgi/monthly.cgi[générateur XML] ou téléchargez et modifiez le link:https://www.freebsd.org/news/status/report-sample.md[Markdown template].

'''''

Un des avantages du modèle de développement FreeBSD est sa focalisation sur une implémentation et une conception centralisées, dans lequel le système d'exploitation est maintenu dans un dépôt central et où les discussions ont lieu sur des listes de diffusion centralisées. Cela permet un haut degré de coordination entre les auteurs des différents composants du système et le respect de certaines règles dans l'ensemble du système pour des aspects allant de l'architecture générale au style du code source. Cependant, comme la communauté des développeurs FreeBSD augmente ainsi que le traffic sur les listes de diffusion et le nombre de modifications sur les sources, il devient difficile même pour le plus dévoué des développeurs de rester au courant de tout ce qui se fait.

Le rapport de statut trimestriel des développements FreeBSD essaye de corriger ce problème en proposant un moyen pour les développeurs d'informer le plus de personnes possible à propos de leurs travaux en cours sur FreeBSD, que ce soit pour les projets inclus ou extérieurs au code source officiel. Pour chaque projet et sous-projet, on trouvera un paragraphe de résumé indiquant les progrès faits depuis le dernier rapport. S'il s'agit d'un nouveau projet, ou si un projet n'avait pas encore envoyé de rapport de statut, une courte description précède les informations sur le statut.

Ces rapports de statuts peuvent être reproduits en intégralité ou en partie à condition que la source soit clairement indiquée et que le crédit soit donné à qui de droit.

== 2006

* link:https://www.FreeBSD.org/status/report-jan-2006-mar-2006/[Janvier 2006 - Mars 2006]

== 2005

* link:https://www.FreeBSD.org/status/report-oct-2005-dec-2005/[Octobre 2005 - Décembre 2005]
* link:https://www.FreeBSD.org/status/report-july-2005-oct-2005/[Juillet 2005 - Octobre 2005]
* link:https://www.FreeBSD.org/status/report-mar-2005-june-2005/[Mars 2005 - Juin 2005]
* link:https://www.FreeBSD.org/status/report-jan-2005-mar-2005/[Janvier 2005 - Mars 2005]

== 2004

* link:https://www.FreeBSD.org/status/report-july-2004-dec-2004/[Juillet 2004 - Décembre 2004]
* link:https://www.FreeBSD.org/status/report-may-2004-june-2004/[Mai 2004 - Juin 2004]
* link:https://www.FreeBSD.org/status/report-mar-2004-apr-2004/[Mars 2004 - Avril 2004]
* link:https://www.FreeBSD.org/status/report-jan-2004-feb-2004/[Janvier 2004 - Février 2004]

== 2003

* link:https://www.FreeBSD.org/status/report-oct-2003-dec-2003/[Octobre 2003 - Décembre 2003]
* link:https://www.FreeBSD.org/status/report-mar-2003-sep-2003/[Mars 2003 - Septembre 2003]
* link:https://www.FreeBSD.org/status/report-jan-2003-feb-2003/[Janvier 2003 - Février 2003]

== 2002

* link:https://www.FreeBSD.org/status/report-nov-2002-dec-2002/[Novembre 2002 - Décembre 2002]
* link:https://www.FreeBSD.org/status/report-sept-2002-oct-2002/[Septembre 2002 - Octobre 2002]
* link:report-july-2002-aug-2002[Juillet 2002 - Août 2002]
* link:https://www.FreeBSD.org/status/report-may-2002-june-2002/[Mai 2002 - Juin 2002]
* link:https://www.FreeBSD.org/status/report-feb-2002-apr-2002/[Février 2002 - Avril 2002]
* link:https://www.FreeBSD.org/status/report-dec-2001-jan-2002/[Décembre 2001 - Janvier 2002]

== 2001

* link:https://www.FreeBSD.org/status/report-november-2001/[Novembre 2001]
* link:https://www.FreeBSD.org/status/report-september-2001/[Septembre 2001]
* link:https://www.FreeBSD.org/status/report-august-2001/[Août 2001]
* link:https://www.FreeBSD.org/status/report-july-2001/[Juillet 2001]
* link:https://www.FreeBSD.org/status/report-june-2001/[Juin 2001]
