.\" Copyright (c) 1997, 1998, 1999
.\"	Bill Paul <wpaul@ee.columbia.edu> All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by Bill Paul.
.\" 4. Neither the name of the author nor the names of any co-contributors
.\"    may be used to endorse or promote products derived from this software
.\"   without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY Bill Paul AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL Bill Paul OR THE VOICES IN HIS HEAD
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
.\" THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" %FreeBSD: src/usr.sbin/ancontrol/ancontrol.8,v 1.3.2.6 2001/03/06 14:21:01 ru Exp %
.\"
.\" jpman %Id: ancontrol.8,v 1.3 2000/04/28 05:37:56 takaha Stab %
.Dd September 10, 1999
.Dt ANCONTROL 8
.Os FreeBSD
.Sh 名称
.Nm ancontrol
.Nd Aironet 4500/4800 デバイスの設定
.Sh 書式
.Nm
.Fl i Ar iface Fl A
.Nm
.Fl i Ar iface Fl N
.Nm
.Fl i Ar iface Fl S
.Nm
.Fl i Ar iface Fl I
.Nm
.Fl i Ar iface Fl T
.Nm
.Fl i Ar iface Fl C
.Nm
.Fl i Ar iface Fl t Ar 0|1|2|3|4
.Nm
.Fl i Ar iface Fl s Ar 0|1|2|3
.Nm
.Fl i Ar iface
.Op Fl v Ar 1|2|3|4
.Fl a Ar AP
.Nm
.Fl i Ar iface Fl b Ar beacon period
.Nm
.Fl i Ar iface 
.Op Fl v Ar 0|1
.Fl d Ar 0|1|2|3
.Nm
.Fl i Ar iface Fl e Ar 0|1|2|4
.Nm
.Fl i Ar iface 
.Op Fl v Ar 0|1|2|3|4|5|6|7
.Fl k Ar key
.Nm
.Fl i Ar iface 
.Fl K Ar mode
.Nm
.Fl i Ar iface 
.Fl W Ar mode
.Nm
.Fl i Ar iface Fl j Ar netjoin timeout
.Nm
.Fl i Ar iface Fl l Ar station name
.Nm
.Fl i Ar iface Fl m Ar mac address
.Nm
.Fl i Ar iface
.Op Fl v Ar 1|2|3
.Fl n Ar SSID
.Nm
.Fl i Ar iface Fl o Ar 0|1
.Nm
.Fl i Ar iface Fl p Ar tx power
.Nm
.Fl i Ar iface Fl c Ar channel number
.Nm
.Fl i Ar iface Fl f Ar fragmentation threshold
.Nm
.Fl i Ar iface Fl r Ar RTS threshold
.Nm
.Fl h
.Sh 解説
.Nm
コマンドは、
.Xr an 4
ドライバを介し、Aironet ワイヤレスネットワークデバイスの動作を制御します。
変更可能なほとんどのパラメータは、
Aironet カードが実装している IEEE 802.11 プロトコルに関連するものです。
これに含まれるのは、
ステーション名、
動作がアドホックモード (ポイントツーポイント) と
インフラストラクチャモードのどちらであるか、
加入するサービスセットのネットワーク名です。
.Nm
コマンドを使用して、現在の NIC の状態や設定を閲覧できますし、
カードの統計カウンタの値をダンプできます。
.Pp
.Nm
に与えられる
.Ar iface
引数は、Aironet デバイスに関連付けられる論理インタフェース名
(an0, an1 等) であることが必要です。
指定しない場合には an0 がデフォルトとして使用されます。
.Pp
.Nm
コマンドは、異なった
.Sx 書式
行の引数の組み合わせを単一の
.Nm
コマンドの起動でサポートするようにはデザインされていません。
そのような組み合わせはお勧めしません。
.Sh オプション
オプションは次の通りです:
.Bl -tag -width Fl
.It Fl i Ar iface Fl A
希望するアクセスポイントリストを表示します。
接続を希望するアクセスポイントの MAC アドレスを指定するために、
ステーションは AP リストを使用可能です。
AP リストを指定しないと (デフォルト)、
SSID リストで指定した SSID (複数可) にサービスするアクセスポイントで
最初に発見したものに、
ステーションは接続します。
AP リストは
.Fl a
オプションで変更可能です。
.It Fl i Ar iface Fl N
SSID リストを表示します。
これは、サービス集合 ID (つまりネットワーク名) であり、
これに対してステーションは接続を希望します。
リスト中には最大 3 個の SSID まで存在可能です:
ステーションはリストを昇順に見て、
最初にマッチを見付けた SSID に接続します。
.It Fl i Ar iface Fl S
NIC の状態情報を表示します。
これには、現在の動作状態、現在の BSSID、SSID、チャネル、ビーコン周期、
現在接続中のアクセスポイントを含みます。
動作モードは、NIC の状態と、MAC の状態と、受信器の状態を含みます。
キーワード "synced" が表示されたときには、
NIC はアクセスポイントへの接続に成功したか、
アドホック「マスタ」ステーションへの接続に成功したか、「マスタ」自身
になったかを意味します。
ビーコン周期は 20 ミリ秒から 976 ミリ秒の範囲です。
デフォルトは 100 です。
.It Fl i Ar iface Fl I
NIC のケーパビリティ情報を表示します。
デバイスタイプ、周波数、速度とパワーレベルケーパビリティ、
ファームウェアリビジョンレベルが表示されます。
.It Fl i Ar iface Fl T
NIC 内部の統計カウンタを表示します。
.It Fl i Ar iface Fl C
現在の NIC の設定を表示します。
現在の動作モード、受信モード、MAC アドレス、パワーセーブ設定、
様々なタイミング設定、チャネル選択、ダイバシティ、送信パワー、
送信速度が表示されます。
.It Fl i Ar iface Fl t Ar 0|1|2|3|4
送信速度を選択します。使用可能な設定は次の通りです:
.Bl -column "TX レート " "NIC 速度 " -offset indent
.Em "TX レート	NIC 速度"
0	自動 -- NIC が最適速度を選択
1	1Mbps 固定
2	2Mbps 固定
3	5.5Mbps 固定
4	11Mbps 固定
.El
.Pp
5.5Mbps と 11Mbps の設定は、
4800 シリーズアダプタでのみサポートされていることに注意してください:
4500 シリーズアダプタの最大速度は 2Mbps です。
.It Fl i Ar iface Fl s Ar 0|1|2|3
パワーセーブモードの設定をします。正当な選択肢は次の通りです:
.Bl -column "選択肢 " "パワーセーブモード " -offset indent
.Em "選択肢	パワーセーブモード"
0	無し - パワーセーブ無効
1	常にアウェイクモード (CAM)
2	パワーセーブポーリング (PSP)
3	高速パワーセーブポーリング (PSP-CAM)
.El
.Pp
IBSS (アドホック) モードでは、
PSP モードのみがサポートされることに注意してください。
しかも、ATIM ウィンドウが非 0 の場合に限ります。
.It Xo
.Fl i Ar iface
.Op Fl v Ar 1|2|3|4
.Fl a Ar AP
.Xc
希望するアクセスポイントを設定します。
.Ar AP
は、コロンで区切った 6 個の 16 進数から成る MAC アドレスで指定します。
デフォルトでは、
.Fl a
オプションは AP リストの最初のエントリのみを設定します。
.Fl v
修飾子を使用して、どの AP リストエントリを修正するかを正確に指定可能です。
.Fl v
フラグを使用しないと、最初の AP リストエントリが変更されます。
.It Fl i Ar iface Fl b Ar beacon period
アドホックモードのビーコン周期を指定します。
ビーコン周期はミリ秒単位で指定します。
デフォルトは 100ms です。
.It Xo
.Fl i Ar iface
.Op Fl v Ar 0|1
.Fl d Ar 0|1|2|3
.Xc
アンテナダイバシティを選択します。
Aironet デバイスは、最大 2 個のアンテナで設定可能であり、
送受信それぞれに対してダイバシティを設定可能です。
有効な選択肢は次の通りです:
.Bl -column "選択肢 " "ダイバシティ " -offset indent
.Em "選択肢	ダイバシティ"
0	工場出荷デフォルトのダイバシティの選択
1	アンテナ 1 のみ
2	アンテナ 2 のみ
3	アンテナ 1 と 2
.El
.Pp
受信と送信のダイバシティは独立に設定可能です。
どちらのダイバシティ設定を修正するかを示す必要があり、
.Fl v
オプションを使用します:
選択肢
.Ar 0
は受信ダイバシティを設定し、
.Ar 1
は送信ダイバシティを設定します。
.It Fl i Ar iface Fl e Ar 0|1|2|3
使用する、送信 WEP 鍵を設定します。
このコマンドを発行するまでは、
最後にプログラムされた鍵をデバイスは使用します。
送信鍵は NVRAM に格納されます。
現在の送信鍵の設定は "-C" オプションで確認可能です。
.It Xo
.Fl i Ar iface
.Op Fl v Ar 0|1|2|3|4|5|6|7
.Fl k Ar key
.Xc
WEP 鍵を設定します。
40 ビット時には、10 桁の 16 進数の前に 0x を付けます。
128 ビット時には、26 桁の 16 進数の前に 0x を付けます。
鍵を削除するには "" を使用します。
4 個の鍵がサポートされています。
偶数は永続的な鍵であり、奇数は一時的な鍵です。
例えば、"-v 1" は最初の一時的な鍵を設定します
("永続的な" 鍵は NVRAM に格納されますが、"一時的な" 鍵は違います)。
デフォルトでは、
デバイスは最も最近にプログラムされた鍵を使用することに注意してください。
現在の送信鍵の設定は "-C" オプションで確認可能であり、
鍵のサイズのみが返されます。
.It Fl i Ar iface Fl K Ar 0|1|2
認証タイプを設定します。
0 は無しを、
1 は "オープン" を、
2 は "共有鍵" を、それぞれ意味します。
.It Fl i Ar iface Fl W Ar 0|1|2
WEP を有効化します。
0 は WEP 無しを、
1 は完全な WEP の有効化を、
2 は混合セルを、それぞれ意味します。
.It Fl i Ar iface Fl j Ar netjoin timeout
アドホックネットワークへの加入タイムアウトを設定します。
ステーションが最初にアドホックモードで活動開始したときには、
ステーションは希望する SSID を持つ「マスタ」ステーションを探し、
これに接続します。
適切なタイムアウトが経過しても、
同じ SSID を持つ他のステーションを見付けられない場合、
ステーションは自己を「マスタ」として設定しますので、
他のステーションが接続できるようになります。
このタイムアウトのデフォルトは 10000 ミリ秒 (10 秒) ですが、
本オプションで変更可能です。
タイムアウトはミリ秒で設定します。
.It i Ar iface Fl l Ar station name
NIC 内部で使用するステーション名を設定します。
.Ar station name
は 16 文字までの長さの任意のテキストです。
デフォルトの名前は、ドライバが "FreeBSD" に設定します。
.It Fl i Ar iface Fl m Ar mac address
指定したインタフェースのステーションアドレスを設定します。
.Ar mac address
は、コロンで区切られた 6 個の連続する 16 進数で指定し、
例えば 00:60:1d:12:34:56 です。
これにより、新しいアドレスをカードにプログラムし、
インタフェースもまた更新します。
.It Xo
.Fl i Ar iface
.Op Fl v Ar 1|2|3
.Fl n Ar SSID
.Xc
希望する SSID (ネットワーク名) を設定します。
SSID は 3 個ありますので、
設定を修正することなく様々な場所で NIC がアクセスポイントへ接続可能です。
マッチを探すとき、NIC は各 SSID を順番にチェックします。
変更する SSID は
.Fl v
修正子オプションで指定します。
.Fl v
フラグが使用されないと、リストの最初の SSID が設定されます。
.It Fl i Ar iface Fl o Ar 0|1
Aironet インタフェースの動作モードを設定します。
正当な選択肢は
.Ar 0
がアドホックモードで、
.Ar 1
がインフラストラクチャモードです。
デフォルトのドライバ設定はアドホックモードです。
.It Fl i Ar iface Fl p Ar tx power
送信パワーレベルをミリワット単位で設定します。
正当なパワー設定は実際の NIC に依存して変わり、
.Fl I
フラグでデバイスケーパビリティをダンプすることで閲覧可能です。
典型的な値は 1, 5, 20, 50, 100mW です。
0 を選択すると、工場出荷デフォルトを選択します。
.It Fl i Ar iface Fl c Ar channel
指定したインタフェースの電波周波数を設定します。
.Ar frequency
は、下表に示すチャネル ID で指定します。
使用可能な周波数一覧は、地域当局が指定する電波規制に依存します。
既知の規制当局には、FCC (米国)、ETSI (欧州)、フランス、日本があります。
表中の周波数は MHz 単位です。
.Bl -column "チャネル ID " "FCC " "ETSI " "仏 " "日 " -offset indent
.Em "チャネル ID	FCC	ETSI	仏	日"
1	2412	2412	-	-
2	2417	2417	-	-
3	2422	2422	-	-
4	2427	2427	-	-
5	2432	2432	-	-
6	2437	2437	-	-
7	2442	2442	-	-
8	2447	2447	-	-
9	2452	2452	-	-
10	2457	2457	2457	-
11	2462	2462	2462	-
12	-	2467	2467	-
13	-	2472	2472	-
14	-	-	-	2484
.El
.Pp
不正なチャネルが指定された場合、NIC はデフォルトチャネルに戻します。
米国および欧州で販売されている NIC では、デフォルトチャネルは 3 です。
フランスで売られている NIC では、デフォルトチャネルは 11 です。
日本で売られている NIC では、使用可能なチャネルは 14 だけです。
通信するには、2 つのステーションを同じチャネルに設定する必要があることに
注意してください。
.It Fl i Ar iface Fl f Ar fragmentation threshold
断片化の閾値をバイト単位で設定します。
この閾値は、出力パケットが複数の断片に分割される点を制御します。
単一の断片の送信に失敗した場合、
パケット全体ではなく、その断片のみの再送が必要です。
断片化の閾値は 64 から 2312 バイトの任意です。
デフォルト値は 2312 です。
.It Fl i Ar iface Fl r Ar RTS threshold
指定したインタフェースの RTS/CTS 閾値を設定します。
これは、RTS/CTS ハンドシェイク境界に使用されるバイト数を制御します。
.Ar RTS threshold
は 0 から 2312 の任意の値です。デフォルト値は 2312 です。
.It Fl h
使用可能なオプションと、サンプルの使用方法を表示します。
.El
.Sh セキュリティに関する注
WEP ("wired equivalent privacy") は RC4 アルゴリズムに基いており、
24 ビットの初期化ベクタを使用します。
.Pp
RC4 は、既知のプレインテキストによる攻撃に対して脆いとされており、
特に 40 ビット鍵においてはそうです。
よって、WEP のセキュリティは、
既知のプレインテキストがどれだけ転送されるかに幾分か依存します。
.Pp
このために、WEP を有効にしたときには直観とは逆に、
(既知のプレインテキストの送信を含む) "共有鍵"
認証を使用する方が "オープン" 認証を使用するよりも、安全ではありません。
.Pp
デバイスは、パケット送信時に、
設定されたすべての WEP 鍵の間で使用する鍵を交換し得ます。
よって、すべての設定された鍵 (最大 4 個) が合致していることが必要です。
.Sh 使用例
.Bd -literal -offset indent
ancontrol -i an0 -v 0 -k 0x12345678901234567890123456
ancontrol -i an0 -K 2
ancontrol -i an0 -W 1
ancontrol -i an0 -e 0
.Ed
.Pp
WEP 鍵 0 を設定し、"共有鍵" 認証を有効にし、
完全な WEP を有効にし、送信鍵 0 を使用します。
.Sh 関連項目
.Xr an 4 ,
.Xr ifconfig 8
.Sh 歴史
.Nm
コマンドは 
.Fx 4.0
ではじめて登場しました。
.Sh バグ
統計カウンタは、送受信フレームの合計を、増加するように表示しないようです。
おそらく、
.Xr an 4
が、NIC 自身に 802.11/イーサネットカプセル化を行わせずに、
無修正パケットモードを使用しているためです。
.Pp
チャネルの設定は効果が無いようです。
.Sh 作者
.Nm
コマンドは
.An Bill Paul Aq wpaul@ee.columbia.edu
が記述しました。
