.\"
.\" ===================================
.\" HARP  |  Host ATM Research Platform
.\" ===================================
.\"
.\"
.\" This Host ATM Research Platform ("HARP") file (the "Software") is
.\" made available by Network Computing Services, Inc. ("NetworkCS")
.\" "AS IS".  NetworkCS does not provide maintenance, improvements or
.\" support of any kind.
.\"
.\" NETWORKCS MAKES NO WARRANTIES OR REPRESENTATIONS, EXPRESS OR IMPLIED,
.\" INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS FOR A PARTICULAR PURPOSE, AS TO ANY ELEMENT OF THE
.\" SOFTWARE OR ANY SUPPORT PROVIDED IN CONNECTION WITH THIS SOFTWARE.
.\" In no event shall NetworkCS be responsible for any damages, including
.\" but not limited to consequential damages, arising from or relating to
.\" any use of the Software or related support.
.\"
.\" Copyright 1994-1998 Network Computing Services, Inc.
.\"
.\" Copies of this Software may be made, however, the above copyright
.\" notice must be reproduced on all copies.
.\"
.\" @(#) %FreeBSD: src/usr.sbin/atm/atmarpd/atmarpd.8,v 1.3 1999/08/28 01:15:31 peter Exp %
.\" jpman %Id: atmarpd.8,v 1.3 1998/12/19 20:11:02 vanitas Stab %
.\"
.\"
.de EX		\"Begin example
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 1
.if t .sp .5
..
.TH ATMARPD 8 "1998-08-04" "HARP"

.SH 名称
atmarpd \- ATMARP/SCSP インタフェースデーモン
.SH 書式
.B atmarpd
[\fB-l\fP <log file>]
[\fB-d\fP]
<netif> ...

.SH 解説
\fIatmarpd\fP は、
Host ATM Research Platform (HARP) ネットワーキングソフトウェア用に、
カーネル内の ATMARP サーバと SCSP デーモンとの間のインタフェースを提供します。
\fIatmarpd\fP は ATMARP キャッシュをカーネルから定期的に読み込み、
更新されたエントリを \fIscspd\fP に渡すことにより、
リモートサーバに伝播させます。
\fIatmarpd\fP はまた
リモートサーバが \fIscspd\fP へ送った更新エントリを受け取り、
新規エントリと、現在のエントリよりも新しいエントリを、
カーネル内の ATMARP キャッシュにインストールします。
ATMARP キャッシュが同期される前に、
\fIatmarpd\fP と \fIscspd\fP の両方が走行している必要があります。

\fIatmarpd\fP が実行を開始すると、
自己に与えられたコマンドラインを解析し、バックグラウンドに移行します。

コマンドラインオプションは次の通りです:
.IP "\fB-l\fP <log file>" 15
ログメッセージをシステムのログではなく
<log file> という名前のファイルに書き込むように、
\fIatmarpd\fP に指定します。
.IP "\fB-d\fP" 15
\fIatmarpd\fP をデバッグモードで実行することを指定します。
デバッグモードでは、\fIatmarpd\fP はバックグラウンドにはなりません。
ログメッセージは、
ログファイルではなく、標準出力に書かれます。
.IP "<netif>" 15
ホストが ATMARP サービスを提供し、
SCSP を使用してキャッシュを同期する
ネットワークインタフェース (複数可) を指定します。
複数のネットワークインタフェース名を指定した場合、
指定した全インタフェース上のサーバのために、
\fIatmarpd\fP は \fIscspd\fP に対するインタフェースを提供します。

.SH シグナル処理
次のシグナルを使用して \fIatmarpd\fP を制御できます:

.IP \fBSIGINT\fP 10
デバッグ情報をファイルにダンプします。
SIGINT を受信すると、
\fIatmarpd\fP は制御ブロックのサマリをテキストファイルにダンプします
(「\fB関連ファイル\fP」参照)。

.SH 関連ファイル

.IP "/tmp/atmarpd.<pid>.<seq>.out"
デバッグ情報をダンプするファイルの名前です。
\fIatmarpd\fP が SIGINT シグナルを受信すると、
制御ブロックのサマリをこのファイルに書き込みます。
<pid> はデーモンのプロセス ID であり、
<seq> はダンプがとられるごとに増えるシーケンス番号です。

.SH 関連項目
\fIatm\fP (8);
\fIscspd\fP (8);
RFC 1577, \fIClassical IP and ARP over ATM\fP;
RFC 2225, \fIClassical IP and ARP over ATM\fP;
RFC 2334, \fIServer Cache Synchronization Protocol (SCSP)\fP;
draft-ietf-ion-scsp-atmarpd-00.txt, \fIA Distributed ATMARP Service
Using SCSP\fP


.SH バグ
あるネットワークインタフェースに対し
複数の \fIatmarpd\fP のインスタンスが同時に実行されると、
予測できない結果となります。

バグは harp-bugs@magic.net に報告してください。

.SH 著作権
Copyright (c) 1994-1998, Network Computing Services, Inc.

.SH 作者
John Cavanaugh, Network Computing Services, Inc.
.br
Mike Spengler, Network Computing Services, Inc.
.br
Joe Thomas, Network Computing Services, Inc.
.fi
.SH 謝辞
本ソフトウェアは、
Defense Advanced Research Projects Agency (DARPA) の協力により開発されました。

.SH 日本語訳
堀川和雄 <horikawa@jp.FreeBSD.org>
