.\" %FreeBSD: src/libexec/bootpd/tools/bootptest/bootptest.8,v 1.2.2.1 2001/01/16 13:14:38 ru Exp %
.\"
.\" bootptest.8
.\" jpman %Id: bootptest.8,v 1.3 1997/10/11 07:41:11 horikawa Stab %
.Dd June 10, 1993
.Dt BOOTPTEST 8
.Os
.Sh 名称
.Nm bootptest
.Nd "BOOTP に質問を送り、応答を出力する"
.Sh 書式
.Op Fl f Ar bootfile
.Op Fl h
.Op Fl m Ar magic_number
.Ar server\-name
.Op Ar template\-file
.Sh 解説
.Nm
は、BOOTP リクエストを
.Ar server\-name
で指定されたホストに送ります。
このとき、応答が得られるか、10 個の
リクエストが無応答に終わるまで 1 秒間隔で連続してリクエストを送信します。
応答を受けとると、
.Nm
は追加の応答を得るためにもう 1 秒待ちます。
.Sh オプション
.Bl -tag -width indent
.It Fl f Ar bootfile
ブートファイルリクエストのブートファイルフィールドを 
.Ar bootfile
で埋めます。
.It Fl h
クライアントの識別にハードウェア (Ethernet) アドレスを用います。
デフォルトでは、クライアントがすでにその IP アドレスを知っていると
いうことを示すようにリクエスト内に IP アドレスがコピーされます。
.TP
.It Fl m Ar magic_number
ベンダオプションフィールドの第 1 ワードを
.Ar magic\-number
で初期化します。
.Pp
.Ar template\-file
が指定されると、 
.Nm
はリクエストパケットのオプションエリアを初期化するために
このファイルの内容 (バイナリデータ) を使用します。
.El
.Sh 作者
.Nm
プログラムは独自の創作物と創作派生物の組み合わせです。
メインプログラムモジュール
.Pq Pa bootptest.c
は
.An Gordon W. Ross Aq gwr@mc.com
独自の創作物です。
パケット表示モジュール
.Pq Pa print\-bootp.c
は
.Bx
の
.Xr tcpdump 1
プログラムから持ってきたファイルを一部変更したものです。
.Pp
このプログラムは
University of California、
Lawrence Berkeley Laboratory と
その貢献者により開発されたソフトウェアを含んでいます (
.Pa print\-bootp.c
の著作権表示を参照のこと)。
.Sh 関連項目
.Xr bootpd 8
.Rs
.%O RFC951
.%T "BOOTSTRAP PROTOCOL (BOOTP)"
.Re
.Rs
.%O RFC1048
.%T "BOOTP Vendor Information Extensions"
.Re
