.\" Copyright (c) 1999 Robert Nordier
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
.\" OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
.\" OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
.\" EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" %FreeBSD: src/usr.sbin/boot0cfg/boot0cfg.8,v 1.5.2.3 2000/12/19 00:40:01 rnordier Exp %
.\"
.\" $FreeBSD$
.\"
.Dd February 21, 1999
.Dt BOOT0CFG 8
.Os
.Sh 名称
.Nm boot0cfg
.Nd ブートマネージャのインストールと設定ユーティリティ
.Sh 書式
.Nm
.Op Fl Bv
.Op Fl b Ar boot0
.Op Fl d Ar drive
.Op Fl f Ar file
.Op Fl m Ar mask
.Op Fl o Ar options
.Op Fl s Ar slice
.Op Fl t Ar ticks
.Ar disk
.Sh 解説
.Fx
の
.Sq boot0
ブートマネージャは、
i386 マシン (PC) がどのディスクのどのスライスから起動するかを、
操作者が選択できるようにします。
.Pp
ここで、
.Dq スライス
と言及しているものは、BSD 以外の PC 関連文書においては一般的に
.Dq パーティション
と呼ばれることに注意してください。
典型的には、リムーバブルディスク以外のみ、スライスを持ちます。
.Pp
オプションとして、
.Nm
ユーティリティは
.Sq boot0
ブートマネージャを指定した
.Ar disk
へインストールします;
そして、様々に操作可能なパラメータの設定を許します。
.Pp
PC では、ブートマネージャは典型的にディスクのセクタ 0 にあり、
マスタブートレコード (Master Boot Record; MBR) として知られています。
MBR は、コード (PC BIOS から制御を渡されます) と
データ (定義されたスライスに関する組み込みの表) の、両方を含みます。
.Pp
オプションは次の通りです:
.Bl -tag -width indent
.It Fl B
.Sq boot0
ブートマネージャをインストールします。
このオプションは、MBR コードを交換しますが、
組み込み済のスライス表には影響しません。
.It Fl v
冗長: 定義されたスライスに関する情報などを表示します。
.It Fl b Ar boot0
どの
.Sq boot0
イメージを使用するかを指定します。デフォルトは
.Pa /boot/boot0
です。
.It Fl d Ar drive
指定した
.Ar disk
を含むドライブを参照するために PC BIOS が使用する、ドライブ番号を指定します。
典型的には、最初のハードドライブは 0x80 であり、
2 番目のハードドライブは 0x81 などとなります;
0 から 0xff までの間の任意の整数を受け付け可能です。
.It Fl f Ar file
以前あった MBR のバックアップコピーを
.Ar file
に書き込むべきであることを指定します。
このファイルは、存在しない場合には作成され、
存在する場合には切り詰められます。
.It Fl m Ar mask
スライスの有効/無効を指定します。
.Ar mask
は 0 (全スライスが無効) から 0xf (4 つ全部のスライスが有効) の間の整数です。
.It Fl o Ar options
コンマで区切られた文字列であり、次のオプションを指定可能です (必要に応じて
.Dq no
を前に付けることが可能です):
.Bl -tag -width indent
.It packet
ディスク関連 BIOS サービスにアクセスするときに、
伝統的な (CHS) インタフェースではなく、
ディスクパケット (BIOS Int 0x13 拡張) インタフェースを必要に応じて使用します。
これにより、1023 シンリンダ超からブート可能となりますが、
特定のBIOS サポートが必要です。
デフォルトは
.Sq nopacket
です。
.It setdrv
ディスクを含むドライブの参照に、-d オプションにより
定義可能なドライブ番号を使用することを強制します。
デフォルトは
.Sq nosetdrv
です。
.It update
ブートマネージャが MBR を更新することを許可します。(スライスを
.Sq 活動
状態とするためや、スライスの選択情報を保存するために、MBR が更新されます。)
これがデフォルトです;
.Sq noupdate
オプションを指定すると、MBR は読み込み専用で扱われます。
.El
.It Fl s Ar slice
デフォルトのブート選択を
.Ar slice
に設定します。
1 から 4 までの値は、スライスを示します。
値  5 は、2 番目のディスクからのブートを示します。
本オプションは、通常、
.Sq noupdate
オプションと共に使用します。
.It Fl t Ar ticks
タイムアウト値を
.Ar ticks
に設定します。
(1 秒あたり、およそ 18.2 ticks です。)
.El
.Sh 関連項目
.Xr boot 8 ,
.Xr fdisk 8
.Sh 診断
終了状態は、成功時には 0 であり、エラー時には 0 より大きくなります。
.Sh AUTHORS
.An Robert Nordier Aq rnordier@FreeBSD.org
.Sh バグ
.Sq packet
オプションを使用すると、
.Sq boot0
が失敗することがあります。
これは BIOS サポートの性質に依存しています。
.Pp
誤った -d オペランドとともに
.Sq setdrv
オプションを使用すると、MBR を誤ったディスクへ書き込むことになります。
注意してください !
