.\" @(#)bootparamd.8
.\" %FreeBSD: src/usr.sbin/bootparamd/bootparamd/bootparamd.8,v 1.14 2002/07/14 14:42:38 charnier Exp %
.\"
.\" $FreeBSD$
.Dd December 14, 2000
.Dt BOOTPARAMD 8
.Os
.Sh 名称
.Nm bootparamd
.Nd ブートパラメータサーバ
.Sh 書式
.Nm
.Op Fl ds
.Op Fl r Ar router
.Op Fl f Ar file
.Sh 解説
.Nm bootparamd
ユーティリティは、
.Xr diskless 8
クライアントの起動時に必要な情報を提供するサーバプロセスです。
.Pa /etc/bootparams
ファイルの内容を参照します。
.Pp
このバージョンでは
.Pa /etc/bootparams
ファイルにおいてホストの別名を使う事ができます。
起動中のクライアントが発行した
.Em whoami
リクエストに対し返されるホスト名は
.Pa /etc/bootparams
中の名前であり、正式名ではありません。
この方法により、長いホスト名を扱う事のできないマシンに対しても、
起動に失敗する事の無い短い名前を答える事ができます。
.Sh オプション
.Bl -tag -width Fl
.It Fl d
デバッグ情報を出力します。
.It Fl s
デバッグ情報を
.Xr syslog 3
にて記録します。
.It Fl r Ar router
デフォルトルータを、ホスト名もしくは IP アドレスで指定します。
無指定時のデフォルトルータはサーバが動作しているマシンになります。
.It Fl f Ar file
.Pa /etc/bootparams
の代わりに使用するブートパラメータファイル名を指定します。
.El
.Sh 関連ファイル
.Bl -tag -width /etc/bootparams -compact
.It /etc/bootparams
デフォルトのブートパラメータファイル
.El
.Sh 使用例
ディスクレス SunOS/Xkernel SPARCstation がネットブートするとき、
ブートした SunOS カーネルはオール 0 アドレスに対してブロードキャストします。
SunOS カーネルは、応答を受け取るまで停止します。
この動作に対応するために、
オール 0 ブロードキャストに応答するエイリアスアドレスを追加します。
つまり、次のような設定を、
.Nm
サーバの適切なネットワークインタフェースに追加します:
.Ql "ifconfig xl0 192.168.200.254 netmask 255.255.255.255 broadcast 192.168.200.0 alias
。
もちろん、エイリアスアドレスは、使用可能であるように空いている必要があります。
.Sh 関連項目
.Xr syslog 3 ,
.Xr bootparams 5 ,
.Xr diskless 8
.Sh バグ
.Xr syslog 3
への出力情報が多少冗長すぎるかもしれません。
.Sh 作者
.An Klas Heggemann Aq klas@nada.kth.se
が作成しました。
