.\" 
.\" Copyright (c) 2000 Sen Schmidt
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer,
.\"    without modification, immediately at the beginning of the file.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" %FreeBSD: src/usr.sbin/burncd/burncd.8,v 1.6.2.2 2000/12/08 15:27:58 ru Exp %
.\" jpman %Id: burncd.8,v 1.3 2000/03/11 22:37:36 horikawa Stab %
.\"
.Dd January 6, 2000
.Os
.Dt BURNCD 8
.Sh 名称
.Nm burncd
.Nd ATAPI CD-R/RW ドライバの制御
.Sh 書式
.Nm
.Op Fl f Ar device
.Op Fl s Ar speed
.Op Fl e
.Op Fl p
.Op Fl q
.Ar [command]
.Ar [command filename...]
.Sh 解説
.Nm
ユーティリティは ATAPI cd ドライバを用いて CD-R/RW メディアを
焼きつけるために使用されます。
.Pp
利用可能なオプションとオペランド:
.Pp
.Bl -tag -width XXXXXXXXXXXX
.It Fl f Ar device
焼きつけ過程において使用するデバイスを設定します。
.It Fl s Ar speed
焼きつけデバイスの速さを設定します。
典型的には 1, 2, 4 のいずれかであり、
デフォルトは 1 に設定されます。
.It Fl e
終了時に CD-R/RW を排出します。
.It Fl p
オーディオトラックに対して高域補正を行います。
.It Fl q
静かにします。進捗状況を出力しません。
.It Fl t
書き込みテストを行います。メディアに対して
実際に書き込みは行いません。
.El
.Pp
.Ar command 
は以下のどれか一つになります。
.Pp
.Bl -tag -width XXXXXXXXXXXX
.It Ar msinfo
メディア上の最後のトラックの最初の LBA と、
メディア上の次に書き込み可能なアドレスを表示します。
これは、
追加セッション付の ISO ファイルシステムに追加データを追記するときに、
.Xr mkisofs 1
の
.Fl C 
スイッチで使用します。
.It Ar blank
CD-RW メディアを消去します。
高速な消去方法を使用するため、データは物理的には上書きされず、
後で使う際にメディアが空である事を示す領域のみ上書きします。
.It Ar mode2
コマンドラインで後続するイメージファイルに対し、
書き込みモードがデータ (mode2) トラックを生成するようにします。
.It Ar XAmode1
コマンドラインで後続するイメージファイルに対し、
書き込みモードがデータ (XAmode1) トラックを生成するようにします。
.It Ar fixate
TOC が作成されメディアが普通の CD ドライブで使用できるように
メディアを固定します。
ドライバはデフォルトではマルチセッションメディアを作成します。
このコマンドが終了した時にプログラムが終了するように
.Nm
に渡される最後のコマンドとしてください。
.It Ar raw | audio
コマンドラインで続いて指定されるイメージファイルを
オーディオ (raw mode) トラックとして処理するように
書き込みモードを設定します。
.It Ar data | mode1
コマンドラインで続いて指定されるイメージファイルを
データ (mode1) トラックとして処理するように
書き込みモードを設定します。
.It Ar filename
他の全ての引数はメディアに書き込むためのイメージファイルとして
扱われます。
.El
.Pp
ファイルの長さが現在のメディアのブロックサイズの倍数でない場合
ブロックサイズの要求に合わせるために 0 が詰められます。
.Pp
.Sh 使用例
データ CD-R を焼きつけるための典型的な使い方:
.Bd -literal
# burncd -f /dev/acd0c data file1 fixate
.Pp
オーディオ CD-R を焼きつけるための典型的な使い方:
.Bd -literal
# burncd -f /dev/acd0c audio file1 file2 file3 fixate
.Pp
ミックスモード CD-R を焼きつけるための典型的な使い型:
.Bd -literal
# burncd -f /dev/acd0c data file1 audio file2 file3 fixate
.Pp
.Sh バグ
多分あります。みつけたら報告してください。
.Sh 歴史
.Nm
は現在開発中です。
.Nm
コマンドは
.Fx 4.0
で登場しました。
.Sh AUTHORS
本プログラムは
.ie t S/oren Schmidt,
.el Soren Schmidt,
Denmark により提供されました。
