.\"
.\" Copyright (c) 2000,2001,2002 S鷨en Schmidt <sos@FreeBSD.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer,
.\"    without modification, immediately at the beginning of the file.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" %FreeBSD: src/usr.sbin/burncd/burncd.8,v 1.30 2003/05/22 11:52:23 ru Exp %
.\" $FreeBSD$
.\".
.Dd October 18, 2002
.Os
.Dt BURNCD 8
.Sh 抩憊
.Nm burncd
.Nd ATAPI CD-R/RW 玉仿奶田及孺豢
.Sh 踏摯
.Nm
.Op Fl delmnpqtv
.Op Fl f Ar device
.Op Fl s Ar speed
.Op Ar command
.Op Ar command Ar
.Sh 荸濩
.Nm
交□氾奴伉氾奴反 ATAPI cd 玉仿奶田毛迕中化 CD-R/RW 丟犯奴失毛
嬴五勾仃月凶戶卞銀迕今木引允﹝
.Pp
厙迕第Х卅左皿扑亦件午左矢仿件玉:
.Pp
.Bl -tag -width XXXXXXXXXXXX
.It Fl d
DAO (犯奴旦弁失永玄伐件旦) 乒□玉匹 CD-R/RW 毛嬴五引允﹝
.It Fl e
蔽弇凜卞丟犯奴失毛к請仄引允﹝
.It Fl f Ar device
嬴五勾仃聊蠢卞云中化銀迕允月犯田奶旦毛澀爛仄引允﹝
.It Fl F
煞屢卞井井歹日內醜綜毛雄墊仄引允﹝
.It Fl l
隙爛仄凶白央奶伙井日﹜奶丟□斥白央奶伙及域厖毛づ心潸曰引允﹝
.It Fl m
穴伙民本永扑亦件乒□玉及犯奴旦弁毛岉元引允
(隙爛仄卅中樺寧卞反﹜扑件弘伙本永扑亦件午仄化犯奴旦弁毛岉元引允)﹝
.It Fl n
DAO 乒□玉卞云中化﹜犯□正玄仿永弁棉卞幼乓永皿毛踏五慇心引六氏﹝
.It Fl p
左□犯奴左玄仿永弁卞覆仄化嫖啗怀懇毛墊中引允﹝
.It Fl q
斃井卞仄引允﹝褡躅橇須毛請恘仄引六氏﹝
.It Fl s Ar speed
嬴五勾仃犯田奶旦及簧今毛澀爛仄引允﹝
犯白巧伙玄反 4 卞澀爛今木引允﹝
玉仿奶皮及瘉嫖簧蘸毛隙爛允月凶戶卞
.Dq Li max
毛隙爛仄化仁分今中﹝
.It Fl t
踏五慇心氾旦玄毛墊中引允﹝丟犯奴失卞覆仄化
撢端卞踏五慇心反墊中引六氏﹝
.It Fl v
暸贏卞卅曰﹜馨笛及褡躅丟永本□斥毛刓憎仄引允﹝
.El
.Pp
.Ar command
反動票及升木井域勾卞卅曰引允﹝
.Pp
.Bl -tag -width XXXXXXXXXXXX
.It Cm msinfo
丟犯奴失曉及瘉詨及玄仿永弁及瘉賡及 LBA 午﹜
丟犯奴失曉及慼卞踏五慇心第Х卅失玉伊旦毛刓憎仄引允﹝
仇木反﹜
馨笛本永扑亦件尥及 ISO 白央奶伙扑旦氾丞卞馨笛犯□正毛馨筏允月午五卞﹜
.Xr mkisofs 8
及
.Fl C
旦奶永民匹銀迕仄引允﹝
.It Cm blank
CD-RW 丟犯奴失毛壅蛔仄引允﹝
嫖簧卅壅蛔杅芊毛銀迕允月凶戶﹜犯□正反坁咥讀卞反曉踏五今木內﹜
詨匹銀丹端卞丟犯奴失互塢匹丐月儀毛憎允恄啗及心曉踏五仄引允﹝
.It Cm erase
CD-RW 丟犯奴失毛壅蛔仄引允﹝
丟犯奴失蟈蟲毛壅蛔仄引允﹝
敦弇引匹卞 1 凜棉井井月仇午手丐曰引允﹝
.It Cm format Brq Cm dvd+rw | dvd-rw
DVD+RW 手仄仁反 DVD-RW 丟犯奴失毛﹜
犯白巧伙玄及瘉釐扔奶朮匹 2048 田奶玄皮伕永弁匹﹜
白巧□穴永玄仄引允﹝
仇及醜綜反贏凜棉毛邰仄ぜ引允﹝
質咥醱卞褡躅扷屢互卅今木引允﹝
.It Cm fixate
TOC 互綜嶽今木丟犯奴失互忔騷及 CD 玉仿奶皮匹銀迕匹五月方丹卞
丟犯奴失毛裔爛仄引允﹝
玉仿奶田反犯白巧伙玄匹反扑件弘伙本永扑亦件丟犯奴失毛綜嶽仄引允 (
.Fl m
毛輔寰仄化仁分今中)﹝
仇及戊穴件玉互蔽弇仄凶凜卞皿伕弘仿丞互蔽弇允月方丹卞
.Nm
卞欐今木月瘉詨及戊穴件玉午仄化仁分今中﹝
DAO 乒□玉匹反拑骰今木引允 (
.Fl d
左皿扑亦件毛輔寰仄化仁分今中)﹝
.It Cm raw | audio
戊穴件玉仿奶件匹糧中化隙爛今木月奶丟□斥白央奶伙毛
左□犯奴左 (raw mode) 玄仿永弁午仄化質咥允月方丹卞
踏五慇心乒□玉毛澀爛仄引允﹝
.It Cm data | mode1
戊穴件玉仿奶件匹糧中化隙爛今木月奶丟□斥白央奶伙毛
犯□正 (mode1) 玄仿永弁午仄化質咥允月方丹卞
踏五慇心乒□玉毛澀爛仄引允﹝
.It Cm mode2
戊穴件玉仿奶件匹詨糧允月奶丟□斥白央奶伙卞覆仄﹜
踏五慇心乒□玉互犯□正 (mode2) 玄仿永弁毛戲嶽允月方丹卞仄引允﹝
.It Cm XAmode1
戊穴件玉仿奶件匹詨糧允月奶丟□斥白央奶伙卞覆仄﹜
踏五慇心乒□玉互犯□正 (XAmode1) 玄仿永弁毛戲嶽允月方丹卞仄引允﹝
.It Cm XAmode2
戊穴件玉仿奶件匹詨糧允月奶丟□斥白央奶伙卞覆仄﹜
踏五慇心乒□玉互犯□正 (XAmode2) 玄仿永弁毛戲嶽允月方丹卞仄引允﹝
.It Cm vcd
戊穴件玉仿奶件匹詨糧允月奶丟□斥白央奶伙卞覆仄﹜
踏五慇心乒□玉互 VCD/SVCD 玄仿永弁毛戲嶽允月方丹卞仄引允﹝
仇木反﹜憤が讀卞 DAO
.Pq Fl d
午
.Dq 幼乓永皿拑仄
.Pq Fl n
乒□玉毛澀爛仄引允﹝
.It Cm dvdrw
詨糧允月奶丟□斥井日 DVD+RW 毛踏五慇戈乒□玉卞澀爛仄引允﹝
DVD 反簽域玄仿永弁及心毛儅切引允﹝
.It Ar file
職及蟈化及婁醒反丟犯奴失卞踏五慇戈凶戶及奶丟□斥白央奶伙午仄化
健歹木引允﹝
.Fl l
左皿扑亦件隙爛凜卞反﹜
奶丟□斥及域厖毛殖戈白央奶伙午仄化健歹木引允﹝
.El
.Pp
白央奶伙及贏今互蜇箕及丟犯奴失及皮伕永弁扔奶朮及у醒匹卅中樺寧
皮伕永弁扔奶朮及邰菲卞寧歹六月凶戶卞 0 互腴戶日木引允﹝
晰蓮讀卅白央奶伙抩
.Fl
反伓賞ェ恘毛隙仄﹜1 蘸分仃銀迕第Х匹允﹝
.Sh 銀迕拺
犯□正 CD-R 毛嬴五勾仃月凶戶及霾滇讀卅銀中杅:
.Pp
.Dl "burncd -f /dev/acd0c data file1 fixate"
.Pp
左□犯奴左 CD-R 毛嬴五勾仃月凶戶及霾滇讀卅銀中杅:
.Pp
.Dl "burncd -f /dev/acd0c audio file1 file2 file3 fixate"
.Pp
左□犯奴左 CD-R 毛 DAO 乒□玉匹嬴五勾仃月凶戶及霾滇讀卅銀中杅:
.Pp
.Dl "burncd -f /dev/acd0c -d audio file1 file2 file3"
.Pp
立永弁旦乒□玉 CD-R 毛嬴五勾仃月凶戶及霾滇讀卅銀中杅:
.Pp
.Dl "burncd -f /dev/acd0c data file1 audio file2 file3 fixate"
.Pp
做諒奶丟□斥白央奶伙毛伓賞ェ恘井日づ氏匹嬴五勾仃月凶戶及霾滇讀卅銀中杅:
.Pp
.Dl "gunzip -c file.iso.gz | burncd -f /dev/acd0c data - fixate"
.Pp
蟆課及拺匹反﹜犯□正 CD-R 卞嬴五勾仃日木月白央奶伙反
ISO9660 白央奶伙扑旦氾丞匹丐月仇午互移爛今木化中引允﹝
.Fx
Ports Collection 卞化ェ澎第Х卅
.Xr mkisofs 8
反﹜隙爛今木凶犯奴伊弁玄伉汁伉□井日 ISO9660 白央奶伙扑旦氾丞奶丟□斥
毛綜嶽允月凶戶卞僮仁銀迕今木化中引允﹝
.Sh 棕雁庍醒
慼及棕雁庍醒互
.Nm
及撢墊卞排黍仄引允:
.Pp
.Bl -tag -width ".Ev CDROM"
.It Ev CDROM
.Fl f
白仿弘匹 CD 犯田奶旦互隙爛今木卅中樺寧卞銀迕允月手及﹝
.El
.Sh 田弘
聶坌丐曰引允﹝心勾仃凶日扷屢仄化仁分今中﹝
.Sh 昳銖
.Nm
交□氾奴伉氾奴反
.Fx 4.0
匹瓚樺仄引仄凶﹝
.Sh 綜樊
.Nm
交□氾奴伉氾奴午仇及穴瓦亙失伙矢□斥反
.An S\(/oren Schmidt ,
Denmark
.Aq sos@FreeBSD.org
卞方曰羼間今木引仄凶﹝
