.\"	$NetBSD: fsck.8,v 1.19 1999/03/10 00:08:33 erh Exp $
.\"	%FreeBSD: src/sbin/fsck/fsck.8,v 1.35 2004/07/03 00:13:43 ru Exp %
.\"
.\" Copyright (c) 1996 Christos Zoulas.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by Christos Zoulas.
.\" 4. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $FreeBSD$
.Dd April 25, 2001
.Dt FSCK 8
.Os
.Sh 名称
.Nm fsck
.Nd ファイルシステムの整合性チェックと対話的修正
.Sh 書式
.Nm
.Op Fl dvpfyn
.Op Fl B | F
.Op Fl t Ar fstype
.Op Fl T Ar fstype : Ns Ar fsoptions
.Op Ar special | node ...
.Sh 解説
.Nm
ユーティリティは、ファイルシステムに特化したプログラムを起動し、
.Xr fstab 5
ファイルにリストされているもの、もしくは
コマンドラインで与えたスペシャルデバイスの整合性をチェックします。
.Pp
通常は、自動リブートの間に
.Pa /etc/rc
スクリプトの中で使用されます。
従来からのやり方では、ファイルシステムがマウントされる前に
.Nm
が起動され、マウントされるときにはチェックはすべて
完了しています。
バックグラウンドでのチェックが利用できる場合には、
.Nm
は 2 回起動されます。
まず最初に、従来からのやり方と同じとき、つまり
ファイルシステムがマウントされる前にバックグラウンドでの
チェックができないファイルシステムをすべてチェックするため、
.Fl F
フラグをつけて起動されます。
その後、システムがマルチユーザモードに移行完了した後で
2 度目の起動がなされ、このときには
.Fl B
フラグをつけ、バックグラウンドでのチェックができる
ファイルシステムをすべてチェックするようにします。
フォアグラウンドでのチェックとは違い、
バックグラウンドでのチェックは非同期に開始されるため、
ファイルシステムがチェック中になっているときであっても
システムの他の仕事は進行できます。
.Pp
ファイルシステムが指定されていない場合、
.Nm
はテーブル
.Pa /etc/fstab
を読んで、チェックするファイルシステムを決定します。
.Pa /etc/fstab
内の
.Dq rw ,
.Dq rq ,
.Dq ro
のいずれかのオプションでマウントされる、0 以外のパス番号を
もつパーティションのみがチェックの対象です。
パス番号 1 を持つファイルシステム
(通常はルートファイルシステムだけです) は、
常に 1 つずつ順番にチェックされます。
.Pp
preen モードでない場合は、パス番号の昇順に
残りのエントリが 1 つずつ順番にチェックされます。
この機能は、
.Nm
を用いて対話的に処理することが必須である場合に必要です。
.Pp
preen モードでは、パス番号 1 が完了すると残りすべての
ファイルシステムがチェックされますが、
各パス番号について昇順であり、なおかつ 1 つのディスクドライブに
つき 1 つずつ並行にプロセスが走るようなパス番号順にチェックされます。
.Pp
つまりこういうことです: preen モードでは、パス番号が 1 である
パーティションは 1 つずつ順番にチェックされます。
次に、パス番号が 2 であるパーティションが並行にチェックされますが、
このとき 1 つのディスクドライブにつきプロセスは 1 つだけです。
その次に、パス番号が 3 であるパーティションが並行にチェック
されますが、このとき 1 つのディスクドライブにつきプロセスは
1 つだけ、という具合です。
.Pp
各ファイルシステムが入っているディスクドライブは、数字で終わる
デバイス名の最短プレフィックスから判断されます。デバイス名の
残りの文字はパーティションおよびスライス指示子とみなされます。
.Pp
オプションは次の通りです:
.Bl -tag -width indent
.It Fl d
デバッグモードです。
コマンドを実行せず、表示だけ行います。
このモードをサポートするように
.Nm
がコンパイルされたときだけ利用可能です。
.It Fl f
たとえクリーンであるとマークがついていても (この機能を
サポートしているファイルシステムについて)
ファイルシステムを強制的にチェックします。
.It Fl n
"CONTINUE?" を除くオペレータへの問い合わせに対して
すべて no と答えたものと
.Nm
がみなすようになります。
.It Fl p
preen モードに入ります。preen モードでは、害のない
ファイルシステムの不整合のうち、限られたものだけを
修復します。
ハードウェアもしくはソフトウェアの問題により予期しない
不整合が発見された場合、このチェックプログラムは
エラーで終了します。
preen モードで実行されているときにチェックプログラムが
修復する欠陥の種類を示したリストについては、それぞれの
チェックプログラムのマニュアルページを参照してください。
.It Fl F
フォアグラウンドモードで実行します。
このチェックプログラムは、各ファイルシステムに対して
.Fl F
フラグつきで実行され、ブートアップシーケンスの一部として
実行したいものかどうか、もしくはシステムが立ち上がって
動作した後バックグラウンドでジョブを実行できるかどうかを
決定します。
0 以外の終了コードである場合、後でバックグラウンドで
実行できるということであり、後で行うというメッセージだけが
表示されます。
.It Fl B
バックグラウンドモードで実行します。
このチェックプログラムは、各ファイルシステムに対して
.Fl F
フラグつきで実行され、ブートアップシーケンスの一部として
実行したいものかどうか、もしくはシステムが立ち上がって
動作した後バックグラウンドでジョブを実行できるかどうかを
決定します。
0 以外の終了コードである場合、フォアグラウンドで実行
したかったものであり、すでに実行が終了しているとみなす
ものであるということですので、そのファイルシステムは
スキップされます。
終了コードが 0 である場合、バックグラウンドで実行可能で
あるということですので、このチェックプログラムは
.Fl B
フラグつきで実行され、アクティブなファイルシステムに
対するチェックは済んでいるはずであることが示されます。
バックグラウンドモードで実行している場合、
一度にチェックされるファイルシステムは 1 つだけです。
.It Fl t Ar fstype
ファイルシステムの種類が書かれたコンマ区切りのリストに
対してのみ
.Nm
を起動します。
リストが
.Dq no
で始まる場合、
リストで指定されていないファイルシステムの種類に対して
.Nm
を起動します。
.It Fl v
コマンドを実行する前に表示します。
.It Fl y
オペレータへの質問にすべて yes と答えたものと
.Nm
がみなします。
.It Fl T Ar fstype : Ns Ar fsoptions
指定されたファイルシステムの種類に特化したオプションを
コンマ区切りにしたリストであり、
.Xr mount 8
と同じ形式です。
.El
.Sh 関連ファイル
.Bl -tag -width /etc/fstab -compact
.It Pa /etc/fstab
ファイルシステムのテーブルです。
.El
.Sh 関連項目
.Xr fstab 5 ,
.Xr fsck_ffs 8 ,
.Xr fsck_msdosfs 8 ,
.Xr mount 8
