.\" Copyright (c) 1997 Todd C. Miller <Todd.Miller@courtesan.com>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgment:
.\"	This product includes software developed by Todd C. Miller.
.\" 4. The name of the author may not be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
.\" INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
.\" THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
.\" EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
.\" OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\" OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
.\" ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\"	$OpenBSD: fsirand.8,v 1.6 1997/02/23 03:58:26 millert Exp $
.\" %FreeBSD: src/sbin/fsirand/fsirand.8,v 1.17 2004/07/02 21:45:02 ru Exp %
.\"
.\" $FreeBSD$
.\"
.Dd January 25, 1997
.Dt FSIRAND 8
.Os
.Sh 名称
.Nm fsirand
.Nd inode 世代番号をランダム化する
.Sh 書式
.Nm
.Op Fl b
.Op Fl f
.Op Fl p
.Ar special
.Op Ar "special ..."
.Sh 解説
.Nm
ユーティリティは、コマンドラインにて
.Ar special
で指定したファイルシステム上の全ての inode に対し、
ランダムな世代番号を書き込みます。
これにより、ファイルハンドルを ``予測'' しにくくし、
NFS export したファイルシステムのセキュリティを向上させます。
.Pp
.Em 注 :
現在
.Xr newfs 8
が
.Nm
と同等の処理を行うため、新規ファイルシステムに対し手動で
.Nm
を実行する必要は有りません。
用途は、
既存のファイルシステムを再びランダム化することか、
そこからレポートを得ることだけです。
.Pp
.Nm
ユーティリティは、アンマウントした後
.Xr fsck 8
にてチェックしたファイルシステムか、
リードオンリにてマウントしたファイルシステムのみに適用すべきです。
.Nm
ユーティリティを
シングルユーザモードにてルートファイルシステムに適用できますが、
その後システムを ``reboot -n'' にてリブートしなければなりません。
.Sh オプション
.Bl -tag -width indent
以下のオプションを使用可能です:
.It Fl b
ディスクラベルから得たブロックサイズではなく、
デフォルトのブロックサイズ(通常 512 バイト)を使用します。
.It Fl f
.Ar special
がクリーンとマークされていなくとも、
.Nm
を強制的に実行します。
.It Fl p
新たな世代番号を生成するのではなく、
全ての inode に対して現在の世代番号を表示します。
.El
.Sh 警告
.Nm
はシリンダグループ中の全ての inode を保持できるだけの量のメモリを確保するため、
シリンダグループが少ない大きなディスクにおいては大量のメモリを消費する
可能性があります。
.Sh 関連項目
.Xr fs 5 ,
.Xr fsck 8 ,
.Xr newfs 8
.Sh 歴史
.Nm
ユーティリティは SunOS 3.x から登場しました。
.Pp
このバージョンの
.Nm
は
.Ox 2.1
から登場しました。
.Pp
.Fx
のものは
.Fx 2.2.5
から登場しました。
.Sh 作者
.An Todd C. Miller Aq Todd.Miller@courtesan.com
