MAN8 =	IPXrouted.8\
	MAKEDEV.8\
	ac.8\
	accton.8\
	adding_user.8\
	adduser.8\
	adjkerntz.8\
	amd.8\
	amq.8\
	ancontrol.8\
	apm.8\
	apmd.8\
	arp.8\
	atm.8\
	atmarpd.8\
	atrun.8\
	badsect.8\
	boot0cfg.8\
	boot_i386.8\
	bootparamd.8\
	bootpd.8\
	bootpef.8\
	bootptest.8\
	btxld.8\
	burncd.8\
	camcontrol.8\
	ccdconfig.8\
	chat.8\
	chkgrp.8\
	chkprintcap.8\
	chown.8\
	chroot.8\
	clri.8\
	comcontrol.8\
	comsat.8\
	config.8\
	crash.8\
	cron.8\
	cvsbug.8\
	dev_mkdb.8\
	dhclient-script.8\
	dhclient.8\
	disklabel.8\
	diskless.8\
	diskpart.8\
	dm.8\
	dmesg.8\
	dump.8\
	dumpfs.8\
	dumpon.8\
	edquota.8\
	faithd.8\
	fdcontrol.8\
	fdisk.8\
	fingerd.8\
	fixmount.8\
	fore_dnld.8\
	fsck.8\
	fsdb.8\
	fsinfo.8\
	fsirand.8\
	ftpd.8\
	genassym.8\
	gensetdefs.8\
	getty.8\
	gifconfig.8\
	hlfsd.8\
	ibcs2.8\
	ifconfig.8\
	ifmcstat.8\
	ilmid.8\
	inetd.8\
	init.8\
	intro.8\
	iostat.8\
	ip6fw.8\
	ipf.8\
	ipfstat.8\
	ipfw.8\
	ipmon.8\
	isdnd.8\
	isdndebug.8\
	isdndecode.8\
	isdnmonitor.8\
	isdntel.8\
	isdntelctl.8\
	isdntrace.8\
	ispcvt.8\
	jail.8\
	joy.8\
	kernbb.8\
	keyserv.8\
	kget.8\
	kgmon.8\
	kgzip.8\
	kldload.8\
	kldstat.8\
	kldunload.8\
	kzip.8\
	ldconfig.8\
	linux.8\
	loader.4th.8\
	loader.8\
	locate.updatedb.8\
	lpc.8\
	lpd.8\
	lptcontrol.8\
	mail.local.8\
	mailstats.8\
	mailwrapper.8\
	makekey.8\
	makemap.8\
	makewhatis.local.8\
	manctl.8\
	map-mbone.8\
	memcontrol.8\
	mergemaster.8\
	mixer.8\
	mk-amd-map.8\
	mknetid.8\
	mknod.8\
	mld6query.8\
	mlxcontrol.8\
	mount.8\
	mount_cd9660.8\
	mount_ext2fs.8\
	mount_msdos.8\
	mount_nfs.8\
	mount_ntfs.8\
	mount_null.8\
	mount_nwfs.8\
	mount_portal.8\
	mount_std.8\
	mount_umap.8\
	mount_union.8\
	mountd.8\
	moused.8\
	mrinfo.8\
	mrouted.8\
	mtest.8\
	mtrace.8\
	mtree.8\
	named-bootconf.8\
	named-xfer.8\
	named.8\
	named.reload.8\
	named.restart.8\
	natd.8\
	ndc.8\
	ndp.8\
	newfs.8\
	newfs_msdos.8\
	newkey.8\
	newsyslog.8\
	nextboot.8\
	nfsd.8\
	nfsiod.8\
	ngctl.8\
	nghook.8\
	nologin.8\
	nos-tun.8\
	nslookup.8\
	nsupdate.8\
	ntpd.8\
	ntpdate.8\
	ntpdc.8\
	ntpq.8\
	ntptime.8\
	ntptrace.8\
	pac.8\
	pam.8\
	pam_radius.8\
	pccardc.8\
	pccardd.8\
	pciconf.8\
	periodic.8\
	picobsd.8\
	pim6dd.8\
	pim6sd.8\
	ping.8\
	ping6.8\
	pnpinfo.8\
	portmap.8\
	ppp.8\
	pppctl.8\
	pppd.8\
	pppoed.8\
	pppstats.8\
	praliases.8\
	prefix.8\
	procctl.8\
	pstat.8\
	pw.8\
	pwd_mkdb.8\
	pxeboot.8\
	quot.8\
	quotacheck.8\
	quotaon.8\
	rarpd.8\
	rbootd.8\
	rc.8\
	reboot.8\
	renice.8\
	repquota.8\
	restore.8\
	revnetgroup.8\
	rexecd.8\
	rip6query.8\
	rlogind.8\
	rmail.8\
	rmt.8\
	rmuser.8\
	rndcontrol.8\
	route.8\
	route6d.8\
	routed.8\
	rpc.lockd.8\
	rpc.rquotad.8\
	rpc.rstatd.8\
	rpc.rusersd.8\
	rpc.rwalld.8\
	rpc.sprayd.8\
	rpc.statd.8\
	rpc.umntall.8\
	rpc.yppasswdd.8\
	rpc.ypxfrd.8\
	rpcinfo.8\
	rrenumd.8\
	rshd.8\
	rtadvd.8\
	rtquery.8\
	rtsold.8\
	rwhod.8\
	sa.8\
	savecore.8\
	scspd.8\
	sendmail.8\
	setkey.8\
	showmount.8\
	shutdown.8\
	sicontrol.8\
	slattach.8\
	sliplogin.8\
	slstat.8\
	smrsh.8\
	spkrtest.8\
	spppcontrol.8\
	spray.8\
	sticky.8\
	stlload.8\
	stlstats.8\
	strfile.8\
	svr4.8\
	swapon.8\
	sync.8\
	sysctl.8\
	syslogd.8\
	talkd.8\
	tcpdchk.8\
	tcpdmatch.8\
	telnetd.8\
	tftpd.8\
	timed.8\
	timedc.8\
	traceroute.8\
	traceroute6.8\
	trpt.8\
	tunefs.8\
	tzsetup.8\
	umount.8\
	usbd.8\
	usbdevs.8\
	uuchk.8\
	uucico.8\
	uucpd.8\
	uusched.8\
	uuxqt.8\
	vinum.8\
	vipw.8\
	vmstat.8\
	vnconfig.8\
	watch.8\
	wicontrol.8\
	wire-test.8\
	wlconfig.8\
	xtend.8\
	yp_mkdb.8\
	ypbind.8\
	ypinit.8\
	yppoll.8\
	yppush.8\
	ypserv.8\
	ypset.8\
	ypxfr.8\
	zdump.8\
	zic.8

MLINKS+=apm.8 apmconf.8
MLINKS+=apm.8 zzz.8
MLINKS+=boot_i386.8 boot.8
MLINKS+=bootpd.8 bootpgw.8
MLINKS+=dump.8 rdump.8
MLINKS+=inetd.8 inetd.conf.5
MLINKS+=init.8 securelevel.8
MLINKS+=locate.updatedb.8 updatedb.8
MLINKS+=makewhatis.local.8 catman.local.8
MLINKS+=mount_std.8 mount_devfs.8
MLINKS+=mount_std.8 mount_fdesc.8
MLINKS+=mount_std.8 mount_kernfs.8
MLINKS+=mount_std.8 mount_procfs.8
MLINKS+=mount_std.8 mount_linprocfs.8
MLINKS+=newfs.8 mount_mfs.8
MLINKS+=newfs.8 mfs.8
MLINKS+=newfs.8 tmpfs.8
MLINKS+=pam.8 pam.conf.5
MLINKS+=pam.8 pam.d.5
MLINKS+=pstat.8 swapinfo.8
MLINKS+=quotaon.8 quotaoff.8
MLINKS+=rc.8 rc.atm.8
MLINKS+=rc.8 rc.firewall.8
MLINKS+=rc.8 rc.i386.8
MLINKS+=rc.8 rc.local.8
MLINKS+=rc.8 rc.network.8
MLINKS+=rc.8 rc.pccard.8
MLINKS+=rc.8 rc.serial.8
MLINKS+=rc.8 rc.shutdown.8
MLINKS+=reboot.8 halt.8
MLINKS+=reboot.8 fastboot.8
MLINKS+=reboot.8 fasthalt.8
MLINKS+=restore.8 rrestore.8
MLINKS+=rtsold.8 rtsol.8
MLINKS+=slattach.8 slip.8
MLINKS+=strfile.8 unstr.8
MLINKS+=vnconfig.8 swapfile.8

.include "bsd.prog.mk"
