.\"
.\" %FreeBSD: src/usr.sbin/xntpd/doc/ntpdate.8,v 1.4.2.1 1999/08/29 15:49:13 peter Exp %
.\" jpman %Id: ntpdate.8,v 1.3 1997/09/12 02:30:46 seki Stab %
.\"
.Dd December 21, 1993
.Dt NTPDATE 8
.Os
.Sh 名称
.Nm ntpdate
.Nd NTP を介して日付と時刻を設定する
.Sh 書式
.Nm
.Op Fl bds
.Op Fl o Ar version
.Op Fl a Ar key#
.Op Fl e Ar authdelay
.Op Fl k Ar keyfile
.Op Fl p Ar samples
.Op Fl t Ar timeout
.Ar server ...
.Sh 解説
.Nm 
は、正確な時刻を決めるために引数に与えられたホスト (複数可) の
ネットワークタイムプロトコル (Network Time Protocol)
サーバを調べることによって、
ローカルな日付と時刻を設定します。
これは、ローカルホストの root として起動されなければなりません。
指定された各サーバからたくさんのサンプルを得て、
標準の NTP 時計フィルタと選択アルゴリズムを適用し、
その中から最良のものを選択します。
通常
.Nm
コマンドは、ブート時の時刻を設定するために起動時スクリプト
.Pa /etc/rc.local
の中に挿入したり、
.Xr cron 8
を介して時間毎に間欠的に走らせたりすることができます。
.Nm
の信頼性と正確さは、
サーバ数が増えると劇的に改善することを覚えておいてください。
単一のサーバを使っても構いませんが、
あまり多くないにしても、
少なくとも 3 つないし 4 つのサーバを用意すると、
より良い性能と、
どれかのサーバの部分的な狂いに対するより大きな抵抗性が得られます。
.Pp
.Nm
は 2 つの方法のうちの 1 つで時刻の調整を行います。
.Nm
は、時計が 0.5 秒以上ずれていると判断すると、
.Xr settimeofday 2
を呼ぶことで単に時刻を合わせ直します。
しかし、
誤差が 0.5 秒以内のときは、デフォルトでは、そのずれを指定して
.Xr adjtime 2
を呼ぶことで、時計の時刻を微調整します。
後者のテクニックは、ずれが小さいときには、より滑らかな上に正確であり、
.Nm
を
.Xr cron 8
で 1 〜 2 時間に一回走らせるときには、かなりうまく働きます。
後者の方法で行う調整は、実際には、計測されたずれよりも 50% 大きくなります。
これは、ひどくフラフラする時計をより正確に保持するのに役立つからです
(安定性は少し犠牲になりますが、この取り引きは大抵は有効です)。 
しかしブート時には、大抵の場合、必ず合わせ直す方がいいでしょう。
コマンドラインに
.Fl b
スイッチを指定することにより、すべての場合にこれを強制することができます。
.Fl s
スイッチは、
.Nm
の動作を標準出力ではなく、
.Xr syslog 3
機能でログを取るようにします。
これはプログラムを
.Xr cron 8
から走らせる際に便利なオプションです。
.Pp
.Fl d
フラグは
.Nm
が何を行うのかを、
実際に実行させずに知るために使われます。
一般のデバッグに便利な情報も出力されます。
デフォルトでは、
.Nm
は、パケットを出力するときに NTPバージョン 3 の実装であると自称します。
古いソフトウェアのいくつかはバージョン 3 の問い合わせへの返答を拒否するため、
代わりに
.Fl o Ar version
スイッチにより、
バージョン 2 または 1 の実装として調べるように強制できます。
.Pp
.Nm
が各サーバから得るサンプルの数は、
.Fl p
スイッチを使って、 1 から 8 までを設定することができます。
デフォルトは 4 です。
応答待ちに使われる時間は
.Fl t
スイッチで設定でき、 0.2 秒の倍数に丸められます。
デフォルトは 1 秒で、これは LAN を通じて調べるのに適当な値です。
.Pp
必要なら
.Nm ntpdate
は、その処理を認証します。
.Fl a
スイッチは、すべてのパケットは指定されたキー番号を使って
認証されなければならないという指定です。
.Fl k
スイッチにより、デフォルトで
.Pa /etc/ntp.keys
となっている、キーを読み込むファイルの名前を変更できます。
このファイルは
.Xr xntpd 8
に記載されているフォーマットで記述されなければなりません。
.Fl e
オプションは、認証処理による遅れを秒単位で指定できます
(詳細は
.Xr xntpd  8
を参照してください)。
この値は、通常は
.Nm 
の用途では無視し得るほどわずかですが、
非常に遅い CPU ではこの数を指定することで、
時間の正確さが改善するかもしれません。
.Pp
.Nm
は、同一ホスト上に NTP サーバデーモン
(例えば
.Xr xntpd 8
)
が走っているときには、時刻の設定を拒否します。
デーモンを走らせる代わりに
.Nm
を
.Xr cron 8
から定期的に走らせるときは、
1 時間か 2 時間に 1 回動かせば、
時計の合わせ直しを避けて十分正確に時刻を刻むことになるでしょう。
.Sh 関連ファイル
.Bl -tag -width /etc/ntp.keys -compact
.It Pa /etc/ntp.keys
は
.Nm
で使われる暗号キーを含みます。
.El
.Sh 関連項目
.Xr xntpd 8
.Sh 歴史
Toronto 大学の 
.An Dennis Ferguson
によって書かれました。
.Sh バグ
時計の発振子の誤差を補正して精度を高めるために用いたテクニックは
あまり出来がよくありませんが、
もっとうまくやるためには、
このプログラムが前回実行した時の状態を保存しておくことが必要となるでしょう。

