.\" Copyright (c) 1997 FreeBSD, Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" %FreeBSD: src/usr.sbin/periodic/periodic.8,v 1.11.2.3 2000/09/20 20:17:21 brian Exp %
.\" jpman %Id: periodic.8,v 1.3 1998/10/10 09:07:49 yohta Stab %
.\"
.\" WORD: registry         レジストリ
.\" WORD: script fragment  スクリプトフラグメント
.\"
.Dd 13 August 1997
.Os FreeBSD 3.0
.Dt PERIODIC 8
.Sh 名称
.Nm periodic
.Nd
定期的なシステム機能を実行する
.Sh 書式
.Nm periodic
.Ar directory Ns No ...
.Sh 解説
.Nm
プログラムは指定されたディレクトリにあるシェルスクリプトを実行するために、
cron(8) に呼び出されることを意図しています。
.Pp
以下の引数から一つ以上を指定しなければいけません :
.Bl -tag -width Fl
.It Cm daily
標準的な 1 日周期の実行ファイルを実行します。
これはよく (その地域の時刻で) 朝早くに行なわれます。
.It Cm weekly
標準的な 1 週間周期の実行ファイルを実行します。
これはよく日曜日の朝に行なわれます。
.It Cm monthly
標準的な 1 ヶ月周期の実行ファイルを実行します。
これはよく月の 1 日目に行なわれます。
.It Ar path
実行すべき一連の実行ファイルがある任意のディレクトリを指定します。
.El
.Pp
引数が絶対パスのディレクトリ名の場合はそれがそのまま使われます。
それ以外の場合は
.Pa /etc/periodic
の下と
.Xr periodic.conf 5
(以下を参照) の中の
.Va local_periodic
で指定されたディレクトリが検索されます。
.Pp
.Nm
プログラムは指定されたディレクトリ (複数指定可) にある
各実行可能ファイルを実行します。もし実行可能ビットが
セットされていないファイルがあっても、無視するだけで
それに関するメッセージも表示しません。
.Pp
各スクリプトは以下のいずれかの値とともに終了することが要求されます。
.Bl -tag -width XXXX
.It 0
スクリプトの出力に注目すべき点はありません。
変数
.Va <basedir>_show_success
で出力のマスクを制御します。
.It 1
スクリプトから注意すべき情報が出力されています。
変数
.Va <basedir>_show_info
でこの出力をマスクするかどうかを制御します。
.It 2
スクリプトは無効な設定による警告を発しました。
変数
.Va <basedir>_show_badconfig
でこの出力をマスクするかどうかを制御します。
.It >2
スクリプトからマスクされない出力が出されています。
.El
.Pp
もし、
.Pa periodic.conf
中の関連のある変数 (
.Ar <basedir>
はスクリプトが置かれた基準となるディレクトリ) 
が
.Dq NO
に設定されているなら、
スクリプトの出力はマスクされます。
その変数が
.Dq YES
か
.Dq NO
のどちらにも設定されていなければ、
.Xr periodic.conf 5
に記述されたデフォルトの値が採用されます。
.Pp
残った出力は
.Va <basedir>_output
に設定された値に基づいて送られます。
.Pp
もし、これにパス名 (
.Dq /
で始まります)
が設定されているなら、出力は単純にそのファイルに記録されます。
.Xr newsyslog 8
は
.Pa /var/log/daily.log ,
.Pa /var/log/weekly.log ,
.Pa /var/log/monthly.log
というファイルを知っており、
これらのファイルがが存在するなら、
適当な回数でローテートされます。
したがって、
.Nm
の出力を記録しようとするなら、
これらを設定するのが適切です。
.Pp
.Va <basedir>_output
の値が
.Dq /
で始まっておらず、空でもない場合には、
メールのアドレスのリストが含まれているとみなされ、
出力はメールで送られます。
.Pp
.Va <basedir>_output
が設定されていないか、空である場合には
出力は標準出力に送られます。
.Sh 環境変数
.Nm
コマンドは環境変数
.Ev PATH
をすべての標準的なシステムディレクトリを含むように設定します。
ただし、
.Pa /usr/local/bin
のような追加的なディレクトリは含めません。もし他のパスに
依存するような実行ファイルを加えるなら、それぞれの実行ファイルが
自己の環境変数を適切に設定する責任を負う必要があります。
.Sh 関連ファイル
.Bl -tag -width /etc/periodic
.It Pa /etc/crontab
典型的な
.Nm
プログラムの呼び出しはシステムのデフォルト cron テーブル内の
エントリから行なわれます。
.It Pa /etc/periodic
サブディレクトリとして
.Pa daily ,
.Pa weekly ,
.Pa monthly
を含む上層のディレクトリです。これらのサブディレクトリには
システムの標準的な定期的実行ファイルが置かれます。
.It Pa /etc/defaults/periodic.conf
.Pa periodic.conf
システムレジストリは
.Nm
と標準の
.Pa daily ,
.Pa weekly ,
.Pa monthly
スクリプト
の振舞を制御する変数を保持します。
.It Pa /etc/periodic.conf
このファイルはデフォルトの periodic の設定の
一部を置き換えるものです。
.El
.Sh 使用例
システム crontab には下の例のような
.Nm
のエントリが記述されているはずです :
.Pp
.Dl # do daily/weekly/monthly maintenance
.Dl 0      2       *       *       *       root    periodic daily
.Dl 0      3       *       *       6       root    periodic weekly
.Dl 0      5       1       *       *       root    periodic monthly
.Pp
典型的なシステムレジストリ
.Pa /etc/defaults/periodic.conf
には変数
.Va local_periodic
について次のように記述してあるでしょう :
.Pp
.Dl local_periodic="/usr/local/etc/periodic /usr/X11R6/etc/periodic"
.Pp
.Nm
の出力をメールで受け取る代わりにログにとるには
以下のような行を
.Pa /etc/periodic.conf
に追加します :
.Pp
.Dl daily_output=/var/log/daily.log
.Dl weekly_output=/var/log/weekly.log
.Dl monthly_output=/var/log/monthly.log
.Pp
毎日実行される periodic のジョブから
重要な情報のみを見るためには、
以下の行を
.Pa /etc/periodic.conf
に追加します :
.Pp
.Dl daily_show_success=NO
.Dl daily_show_info=NO
.Dl daily_show_badconfig=NO
.Sh 関連項目
.Xr sh 1 ,
.Xr crontab 5 ,
.Xr periodic.conf 5 ,
.Xr cron 8 ,
.Xr newsyslog 8
.Rs
.Sh 診断
終了状態は成功時には 0 です。もし以下のいずれかの理由で
コマンドが失敗すれば、終了状態は 1 になります :
.Bl -diag
.It usage: periodic <directory of files to execute>
スクリプトフラグメントがどこにあるかを指定する
ディレクトリパス引数が
.Nm
に渡されませんでした。
.It <directory> not found
説明するまでもありません。(訳注: 指定したディレクトリが見つかりません。)
.El
.Sh 歴史
.Nm
プログラムは
.Fx 3.0
に初めて登場しました。
.Sh 作者
.An Paul Traina Aq pst@FreeBSD.org
.An Brian Somers Aq brian@Awfulhak.org
