.\" Copyright (c) 1997 FreeBSD, Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" %FreeBSD: src/usr.sbin/periodic/periodic.8,v 1.11.2.1 2000/08/08 18:05:42 brian Exp %
.\" jpman %Id: periodic.8,v 1.3 1998/10/10 09:07:49 yohta Stab %
.\"
.\" WORD: registry         レジストリ
.\" WORD: script fragment  スクリプトフラグメント
.\"
.Dd 13 August 1997
.Os FreeBSD 3.0
.Dt PERIODIC 8
.Sh 名称
.Nm periodic
.Nd
定期的なシステム機能を実行する
.Sh 書式
.Nm periodic
.Ao
.Cm daily | weekly | monthly |
.Ar path Op path ...
.Ac
.Sh 解説
.Nm
プログラムは指定されたディレクトリにあるシェルスクリプトを実行するために、
cron(8) に呼び出されることを意図しています。
.Pp
以下の引数からひとつだけを必ず指定しなければいけません :
.Bl -tag -width Fl
.It Cm daily
標準的な 1 日周期の実行ファイルを実行します。
これはよく (その地域の時刻で) 朝早くに行なわれます。
.It Cm weekly
標準的な 1 週間周期の実行ファイルを実行します。
これはよく日曜日の朝に行なわれます。
.It Cm monthly
標準的な 1 ヶ月周期の実行ファイルを実行します。
これはよく月の 1 日目に行なわれます。
.It Ar path
実行すべき一連の実行ファイルがあるディレクトリの絶対パスを指定します。
.El
.Pp
.Nm
プログラムは指定されたディレクトリ (複数指定可) にある
各実行可能ファイルを実行します。もし実行可能ビットが
セットされていないファイルがあっても、無視するだけで
それに関するメッセージも表示しません。
.Sh 環境変数
.Nm
コマンドは環境変数
.Ev PATH
をすべての標準的なシステムディレクトリを含むように設定します。
ただし、
.Pa /usr/local/bin
のような追加的なディレクトリは含めません。もし他のパスに
依存するような実行ファイルを加えるなら、それぞれの実行ファイルが
自己の環境変数を適切に設定する責任を負う必要があります。
.Sh 関連ファイル
.Bl -tag -width /etc/periodic
.It Pa /etc/crontab
典型的な
.Nm
プログラムの呼び出しはシステムのデフォルト cron テーブル内の
エントリから行なわれます。
.It Pa /etc/periodic
サブディレクトリとして
.Pa daily ,
.Pa weekly ,
.Pa monthly
を含む上層のディレクトリです。これらのサブディレクトリには
システムの標準的な定期的実行ファイルが置かれます。
.It Pa /etc/defaults/periodic.conf
.Pa periodic.conf
システムレジストリは変数
.Va local_periodic
を含みます。これは
.Pa /usr/local/etc/periodic
や
.Pa /usr/X11R6/etc/periodic
などのような、定期的に実行する標準の上層ディレクトリを
追加指定するのに使用できます。
.El
.Sh 使用例
システム crontab には下の例のような
.Nm
のエントリが記述されているはずです :
.Pp
.Dl # do daily/weekly/monthly maintenance
.Dl 0      2       *       *       *       root    periodic daily   2>&1
.Dl 0      3       *       *       6       root    periodic weekly  2>&1
.Dl 0      5       1       *       *       root    periodic monthly 2>&1
.Pp
さらに、典型的なシステムレジストリ
.Pa /etc/defaults/periodic.conf
には変数
.Va local_periodic
について次のように記述してあるでしょう :
.Pp
.Dl local_periodic="/usr/local/etc/periodic /usr/X11R6/etc/periodic"
.Sh 関連項目
.Xr sh 1 ,
.Xr crontab 5 ,
.Xr periodic.conf 5 ,
.Xr cron 8
.Rs
.Sh 診断
終了状態は成功時には 0 です。もし以下のいずれかの理由で
コマンドが失敗すれば、終了状態は 1 になります :
.Bl -diag
.It usage: periodic <directory of files to execute>
スクリプトフラグメントがどこにあるかを指定する
ディレクトリパス引数が
.Nm
に渡されませんでした。
.It <directory> not found
説明するまでもありません。(訳注: 指定したディレクトリが見つかりません。)
.El
.Sh 歴史
.Nm
プログラムは
.Fx 3.0
に初めて登場しました。
.Sh 作者
.An Paul Traina Aq pst@FreeBSD.org
