.\"-
.\" Copyright (c) 1999 Brian Somers <brian@Awfulhak.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" %FreeBSD: src/libexec/pppoed/pppoed.8,v 1.2 1999/11/23 00:21:19 brian Exp %
.\"
.\" jpman %Id: pppoed.8,v 1.3 1999/12/17 05:28:31 mitchy Stab %
.Dd November 8, 1999
.Dt PPPOED 8
.Os FreeBSD
.Sh 名称
.Nm pppoed
.Nd PPP over Ethernet の待ち受けを扱う
.Sh 書式
.Nm pppoed
.Op Fl Fd
.Op Fl P Ar pidfile
.Op Fl a Ar name
.Op Fl e Ar exec
.Op Fl p Ar provider
.Ar interface
.Sh 解説
.Nm
プログラムは、指定された
.Ar interface
に対して PPP over Ethernet (PPPoE) サービス要求パケットを listen し、
このパケットへの対応として、セッション交渉後に
.Em PPP
プログラムを起動します。
交渉は
.Dq pppoe
netgraph ノードとして実装されています。
詳細は
.Xr ng_pppoe 8
を参照してください。
.Pp
.Nm
は、指定された
.Ar provider
からサービスを要求しているクライアントに対してのみ、サービスを提供します。
.Ar provider
は、指定されない場合には空の名前とされます。
.Ar provier
名として
.Dq \&*
が指定されると、すべての PPPoE 要求に対してサービスが提供されます。
.Pp
指定した
.Ar name
は、接続確立時に、アクセス集中者 (access concentrator) 名として与えられます。
.Ar name
を指定しないと、現在のベースホスト名が使用されます。
.Pp
PPPoE netgraph ノードからの要求 (PADI) 受信後は、
.Nm
は子プロセスを
.Xr fork 2
し、更なる要求へサービスするために戻ります。
子プロセスは
.Po
.Ar name
を使用して
.Pc
サービスを提供し、PPPoE ノードからの
.Dv 「成功」
表示を待ちます。
「成功」表示を受けると、
.Nm 
は次のコマンドをシェルのサブプロセスとして実行します。
.Pp
.D1 Ic exec /usr/sbin/ppp -direct Ar provider
.Pp
.Ar exec
引数を使用することにより、別のコマンドを指定可能です。
.Ar provider
を指定しない場合には、これは必須です。
この子プロセスは開始時に、標準入力と標準出力が、同じ
.Xr netgraph 4
データソケット
.Po
.Xr ng_socket 8
参照
.Pc
へ接続されます。
.Pp
.Nm
は起動時に、
.Dq Ar interface Ns No \&:
をノード名として使用し、
.Dq pppoe
netgraph ノードを適切な
.Dq ether
ノードへ接続します。その後この
.Dq pppoe
ノードをローカルの
.Dq socket
ノードへ接続します。
.Fl F
フラグを指定しないと、
.Nm
はバックグラウンドモードへ移行し、制御端末を切り離します。
.Fl F
を指定すると、
.Nm
はフォアグラウンドにとどまります。
.Pp
.Fl d
フラグを指定すると、追加の診断機能が提供されます (後述の
.Sx 診断
を参照してください)。
.Pp
.Ar pidfile
を指定すると、
.Nm
は起動時に、自己のプロセス ID をこのファイルへ書き込みます。
.Sh 診断
前述のように必要な
.Xr netgraph 4
ノードを作成した後では、
.Nm
は
.Xr syslogd 8
を使用し、全ての受け付けた接続を報告します。
.Fl d
を指定すると、
.Nm
は新規 netgraph ソケットでの子プロセス生成と、
そのサービス提供、
.Em PPP
プログラムの起動に関して報告します。
.Pp
.Pa /etc/syslog.conf
へ
.Pp
.Dl !pppoed
.Dl *.*				/var/log/pppoed.log
.Pp
を追加し、
.Pa /etc/newsyslog.conf
へ
.Pp
.Dl /var/log/pppoed.log			640  3	   100	*     Z
.Pp
を追加すると便利な場合があります。
.Sh 関連項目
.Xr netgraph 4 ,
.Xr syslog.conf 5 ,
.Xr ng_pppoe 8 ,
.Xr ng_socket 8 ,
.Xr ppp 8 ,
.Xr syslogd 8
.Sh バグ
指定したインタフェースを他の netgraph ノードが使用している場合、
.Nm
は開始できません。現在の
.Xr netgraph 4
は、ノードの連鎖を許していないためです。
将来これは変更されるかもしれません。
.Sh 歴史
.Nm
プログラムは
.An Brian Somers Aq brian@Awfulhak.org
が記述し、
.Fx 3.4
で初登場しました。
