.\" %FreeBSD: src/usr.sbin/procctl/procctl.8,v 1.7.2.1 2000/12/12 10:14:50 ru Exp %
.\"
.\" jpman %Id: procctl.8,v 1.3 1998/10/12 14:27:48 horikawa Stab %
.Dd November 23, 1997
.Dt PROCCTL 8
.Os FreeBSD
.Sh 名称
.Nm procctl
.Nd procfs イベントフラグのクリア
.Sh 書式
.Nm
.Ar pid ...
.Sh 解説
.Nm
コマンドは
.Xr truss 1
によって使われる
.Xr procfs 5
イベントマスクをクリアします。
.Xr procfs 5
のイベントによって殺せないプロセスが結果として生じてしまった為に、
プロセスが立往生して残ってしまった場合に、
この
.Nm
コマンドを使うことが出来ます。
引数はプロセス ID のリストです;
.Nm
コマンドはこのリストを順次評価します。
そして、リストに明示されたそれぞれのプロセスに対応するイベントマスク
をクリアします。
.Sh 関連項目
.Xr truss 1 ,
.Xr procfs 5
.Sh 歴史
.Nm
コマンドは
.An Sean Eric Fagan
によって
.Fx
の為に書かれました。
