.\" %FreeBSD: src/usr.sbin/procctl/procctl.8,v 1.3.2.2 1999/08/29 15:47:16 peter Exp %
.\"
.\" jpman %Id: procctl.8,v 1.3 1998/10/12 14:27:48 horikawa Stab %
.Dd Nov 23, 1997
.Dt PROCCTL 8
.Os FreeBSD
.Sh 名称
.Nm procctl
.Nd procfs イベントフラグのクリア
.Sh 書式
.Nm
.Ar command
.Op Ar ...
.Sh 解説
.Nm
は
.Xr truss 1
によって使われる
.Xr procfs 5
イベントマスクをクリアします。
.Xr procfs 5
のイベントによって殺せないプロセスが結果として生じてしまった為に、
プロセスが立往生して残ってしまった場合に、
この
.Nm
コマンドを使うことが出来ます。
コマンドオプションはプロセスIDのリストです;
.Nm
コマンドはこのリストを順次評価します。
そして、リストに明示されたそれぞれのプロセスに対応するイベントマスク
をクリアします。
.Sh 関連項目
.Xr truss 1 ,
.Xr procfs 5
.Sh 歴史
.Nm
コマンドは
.An Sean Eric Fagan
によって
.Bx Free
の為に書かれました。
