.\" @(#)rstat_svc.8c    2.2 88/08/03 4.0 RPCSRC; from 1.10 87/09/09 SMI
.\" jpman %Id: rstat_svc.8,v 1.3 1997/07/27 12:04:04 horikawa Stab %
.TH RSTAT_SVC 8 "24 November 1987"
.SH 名称
rstat_svc \- カーネル統計サーバ
.SH 書式
.B /etc/rstat_svc
.SH 解説
.LP
.B rstat_svc
は、
カーネルから得られた性能統計を返すサーバです。
これらの統計値は Sun Microsystems のプログラム、
.BR perfmeter (1)
によってグラフで表示されます。
.B rstat_svc
デーモンは、
通常 /etc/rc.local を通してブート時に呼び出されます。
.PP
.B rstat_svc
は、
/usr/include/rpcsvc/rstat.x で定義された RPC プロトコルを使用します。
.\" .SH "関連項目"
.\" .BR rstat (1),
