''' %FreeBSD: src/gnu/libexec/uucp/uusched/uusched.8,v 1.1.4.1 1999/08/29 14:30:48 peter Exp %
.TH uusched 8 "Taylor UUCP 1.06"
.SH 名称
uusched \- UUCP ファイル転送デーモン
.SH 書式
.B uusched 
[uucico options]
.SH 解説
.B uusched
プログラムは実際にはただのシェルスクリプトであり、
.B uucico(8)
デーモンを呼び出します。これはバックワードコンパチビリティのために用意して
あります。
このプログラムは、
仕事があるシステムすべてに対して uucico(8) に呼び出しを行わせます。
uucico(8) に与えることが可能なオプションは
.B uusched
にも与えることが可能です。
.SH 関連項目
uucico(8), uucp(1)
.SH 作者
Ian Lance Taylor (ian@airs.com).
このマニュアルページは Taylor UUCP 1.06 の Texinfo 文書に基きます。

