.\"
.\"	@(#)zdump.8	7.3
.\" %FreeBSD: src/usr.sbin/zic/zdump.8,v 1.7.2.1 2000/12/08 15:29:08 ru Exp %
.\"
.\" jpman %Id: zdump.8,v 1.3 1997/08/30 18:39:05 take-i Stab %
.\"
.Dd September 13, 1994
.Dt ZDUMP 8
.Os
.Sh 名称
.Nm zdump
.Nd タイムゾーンをダンプする
.Sh 書式
.Nm
.Op Fl v
.Op Fl c Ar cutoffyear
.Op Ar zonename ...
.Sh 解説
.Nm
は、コマンドラインの
.Ar zonename
で指定された各タイムゾーンを用いて現在時刻を表示します。
.Pp
以下のオプションが利用可能です:
.Bl -tag -width indent
.It Fl v
コマンドラインの各
.Ar zonename
に対し、表現可能な最も古い時刻、
その最も古い時刻から 1 日後の時刻、
検知された時間の不連続点の 1 秒前および不連続点そのものの時刻、
表現可能な最も先の時刻の 1 日前の時刻、
および表現可能な最も先の時刻そのもの
を表示します。
各時刻は、それが夏時間 (Daylight Saving Time) であれば
.Em isdst=1
、そうでなければ
.Em isdst=0
と行末にしるして表示されます。
.It Fl c Ar cutoffyear
指定した年の最初に近い余分な出力をなくします。
.El
.Sh "関連項目"
.Xr ctime 3 ,
.Xr tzfile 5 ,
.Xr zic 8
