#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/releng/Makefile,v 1.1 2003/10/22 16:35:21 andy Exp $
#
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.xml charter.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
