# $FreeBSD: www/ja/alpha/Makefile,v 1.8 1999/09/06 07:03:17 peter Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.6

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
 
DOCS=   alpha.sgml

INDEXLINK=alpha.html

.include "../../web.mk"
