# $Id: Makefile,v 1.7 1998-10-01 16:05:25 motoyuki Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
 
DOCS=   alpha.sgml

INDEXLINK=alpha.html

.include "../../web.mk"
