#
# $FreeBSD: www/ru/tutorials/Makefile,v 1.1 2000/01/05 15:39:47 phantom Exp $
# The FreeBSD Russian Documentation Project
# Original revision: 1.5
#
# Build the FreeBSD tutorials/articles outside of the www tree, and then
# install them in to the right place.

DOCS = index.sgml

.include "../web.mk"
