# $FreeBSD$
#
# The FreeBSD Mongolian Documentation Project
#
# Original revision 1.2
#
# Build the Handbook with just the content from this chapter.
#

CHAPTERS= 	multimedia/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
