---
description: '시스템과 네트워크를 보호하는 방법에 대한 수백 가지의 표준 관행이 작성되어 있으며, FreeBSD 사용자는 공격과 침입자로부터 보호하는 방법을 이해하는 것은 필수입니다'
next: books/handbook/jails
part: '파트 III. 시스템 관리'
path: /books/handbook/
prev: books/handbook/boot
showBookMenu: 'true'
tags: ["security", "one-time passwords", "TCP Wrapper", "Kerberos", "OpenSSL", "IPsec", "OpenSSH", "ACL", "advisories", "sudo", "doas", "monitoring"]
title: '15장. 보안'
weight: 19
---

[[security]]
= 보안
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 15
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/security/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[security-synopsis]]
== 요약

물리적이든 가상이든 보안은 매우 광범위한 주제이며, 전체 산업은 보안을 중심으로 발전해 왔습니다. 시스템과 네트워크를 보호하는 방법에 대한 수백 가지의 표준 관행이 작성되었으며, FreeBSD 사용자라면 공격과 침입자로부터 보호하는 방법을 이해하는 것은 필수입니다.

이 장에서는 몇 가지 기본 사항과 기술에 대해 설명합니다. FreeBSD 시스템에는 여러 계층의 보안이 제공되며, 보안을 강화하기 위해 더 많은 타사 유틸리티를 추가할 수 있습니다.

이 챕터를 읽고 나면, 여러분은:

* 기본적인 FreeBSD 시스템 보안 개념.
* FreeBSD에서 사용할 수 있는 다양한 암호화 메커니즘.
* 일회용 비밀번호 인증을 설정하는 방법.
* man:inetd[8]을 사용해 TCP 래퍼를 구성하는 방법.
* FreeBSD에서 Kerberos를 설정하는 방법.
* IPsec을 구성하고 VPN을 만드는 방법.
* FreeBSD에서 OpenSSH를 구성하고 사용하는 방법.
* 파일 시스템 ACL을 사용하는 방법.
* pkg를 사용하여 포트 컬렉션에서 설치된 타사 소프트웨어 패키지를 감사하는 방법.
* FreeBSD 보안 권고를 활용하는 방법.
* 프로세스 어카운팅이란 무엇이며 FreeBSD에서 이를 활성화하는 방법.
* 로그인 클래스 또는 리소스 제한 데이터베이스를 사용하여 사용자 리소스를 제어하는 방법.

이 챕터를 읽기 전에 여러분은:

* 기본적인 FreeBSD 사용법 및 인터넷의 개념.

추가 보안 주제는 이 핸드북의 다른 곳에서 다룹니다. 예를 들어, 필수 액세스 제어는 crossref:mac[mac,Mandatory Access Control]에서, 인터넷 방화벽은 crossref:firewalls[firewalls,Firewalls]에서 설명합니다.

[[security-intro]]
== 소개

보안은 모두의 책임입니다. 모든 시스템의 진입 지점이 취약하면 침입자가 중요한 정보에 액세스하여 전체 네트워크에 혼란을 일으킬 수 있습니다. 정보 보안의 핵심 원칙 중 하나는 정보 시스템의 기밀성, 무결성, 가용성을 의미하는 CIA 삼원칙입니다.

CIA 삼원칙은 고객과 사용자가 자신의 데이터가 보호받기를 바라는 컴퓨터 보안의 기본 개념입니다. 예를 들어, 고객은 자신의 신용카드 정보가 안전하게 저장되고(기밀성), 주문이 뒤에서 변경되지 않으며(무결성), 주문 정보에 항상 액세스할 수 있기를 기대합니다(가용성).

보안 전문가는 CIA에 심층 방어 전략을 적용합니다. 심층 방어의 개념은 하나의 계층이 실패하여 전체 보안 시스템이 무너지는 것을 방지하기 위해 여러 계층의 보안을 추가하는 것입니다. 예를 들어, 시스템 관리자는 단순히 방화벽을 켜고 네트워크나 시스템이 안전하다고 생각할 수 없습니다. 또한 계정을 감사하고 바이너리의 무결성을 확인하며 악성 도구가 설치되지 않았는지 확인해야 합니다. 효과적인 보안 전략을 구현하려면 위협과 이를 방어하는 방법을 이해해야 합니다.

컴퓨터 보안과 관련된 위협이란 무엇일까요? 위협은 원격 위치에서 허가 없이 시스템에 액세스하려는 원격 공격자에게만 국한되지 않습니다. 위협에는 직원, 악성 소프트웨어, 승인되지 않은 네트워크 장치, 자연 재해, 보안 취약성, 심지어 경쟁 기업도 포함됩니다.

시스템과 네트워크는 때로는 실수로, 때로는 원격 공격자에 의해, 때로는 기업 스파이나 전직 직원을 통해 무단으로 액세스될 수 있습니다. 사용자는 실수로 인해 보안 침해가 발생했을 때 이에 대비하고 인정하며 보안 팀에 가능한 문제를 보고하는 것이 중요합니다. 관리자는 위협을 파악하고 이를 완화할 수 있도록 준비하는 것이 중요합니다.

시스템에 보안을 적용할 때는 기본 계정과 시스템 구성을 보호하는 것부터 시작한 다음, 시스템 정책과 조직의 보안 절차를 준수할 수 있도록 네트워크 계층을 보호하는 것이 좋습니다. 많은 조직이 이미 기술 디바이스 구성을 다루는 보안 정책을 가지고 있습니다. 이 정책에는 워크스테이션, 데스크톱, 모바일 디바이스, 휴대폰, 프로덕션 서버 및 개발 서버의 보안 구성이 포함되어야 합니다. 대부분의 경우 표준 운영 절차(SOP)가 이미 존재합니다. 확실하지 않은 경우 보안팀에 문의하세요.

이 소개의 나머지 부분에서는 이러한 기본 보안 구성 중 일부가 FreeBSD 시스템에서 어떻게 수행되는지 설명합니다. 그리고 이 장의 나머지 부분에서는 FreeBSD 시스템에서 보안 정책을 구현할 때 사용할 수 있는 몇 가지 도구에 대해 설명합니다.

[[security-accounts]]
=== 로그인 방지

시스템 보안에 있어 가장 좋은 출발점은 계정 감사입니다. `root`에 강력한 비밀번호가 설정되어 있는지, 이 비밀번호가 공유되지 않았는지 확인하세요. 로그인 액세스가 필요하지 않은 계정은 모두 비활성화하세요.

계정에 대한 로그인 액세스를 거부하는 방법에는 두 가지가 있습니다. 첫 번째는 계정을 잠그는 것입니다. 이 예에서는 `toor` 계정을 잠급니다:

[source, shell]
....
# pw lock toor
....

두 번째 방법은 셸을 [.filename]#/usr/sbin/nologin#으로 변경하여 로그인 액세스를 방지하는 것입니다. 수퍼유저만 다른 사용자의 셸을 변경할 수 있습니다:

[source, shell]
....
# chsh -s /usr/sbin/nologin toor
....

[.filename]#/usr/sbin/nologin# 셸은 사용자가 로그인을 시도할 때 시스템에서 사용자에게 셸을 할당하지 못하도록 합니다.

[[security-accountmgmt]]
=== 허용된 계정 승격

경우에 따라 시스템 관리를 다른 사용자와 공유해야 하는 경우가 있습니다. FreeBSD에는 이를 처리하는 두 가지 방법이 있습니다. 첫 번째 방법은 권장되지 않는 방법이지만, `wheel` 그룹의 구성원들이 사용하는 공유 루트 암호입니다. 이 방법을 사용하면, 사용자는 수퍼유저 접근이 필요할 때마다 `su`를 입력하고 `wheel`의 암호를 입력합니다. 그런 다음 사용자는 관리 액세스 권한이 필요한 명령을 완료한 후 `exit`를 입력하여 권한 있는 액세스 권한을 종료해야 합니다. 이 그룹에 사용자를 추가하려면 [.filename]#/etc/group#을 편집하고 `wheel` 항목의 끝에 사용자를 추가합니다. 사용자는 공백 없이 쉼표로 구분해야 합니다.

권한 상승을 허용하는 두 번째 방법이자 권장되는 방법은 package:security/sudo[] 패키지 또는 포트를 설치하는 것입니다. 이 소프트웨어는 추가 감사와 보다 세분화된 사용자 제어 기능을 제공하며 사용자가 지정된 권한 명령만 실행하도록 제한할 수 있습니다.

설치 후, `visudo`를 사용하여 [.filename]#/usr/local/etc/sudoers#를 편집합니다. 이 예제에서는 새로운 `webadmin` 그룹을 생성하고, 해당 그룹에 `trhodes` 계정을 추가한 다음, package:apache24[]를 재시작하도록 해당 그룹 액세스를 구성합니다:

[source, shell]
....
# pw groupadd webadmin -M trhodes -g 6000
# visudo
%webadmin ALL=(ALL) /usr/sbin/service apache24 *
....

[[security-passwords]]
=== 암호 해시

비밀번호는 기술의 필요악입니다. 암호를 사용해야 하는 경우, 암호는 복잡해야 하며 암호 데이터베이스에 저장된 버전을 암호화하기 위해 강력한 해시 메커니즘을 사용해야 합니다. FreeBSD는 `crypt()` 라이브러리에서 DES, MD5, SHA256, SHA512 및 Blowfish 해시 알고리즘을 지원합니다. 기본값인 SHA512는 보안성이 낮은 해싱 알고리즘으로 변경해서는 안 되며, 보안성이 높은 Blowfish 알고리즘으로 변경할 수 있습니다.

[NOTE]
====
블로우피쉬(Blowfish)는 AES의 일부가 아니며 연방 정보 처리 표준(FIPS)을 준수하는 것으로 간주되지 않습니다. 일부 환경에서는 사용이 허용되지 않을 수 있습니다.
====

사용자의 암호를 암호화하는 데 사용되는 해시 알고리즘을 확인하기 위해 수퍼유저는 FreeBSD 암호 데이터베이스에서 사용자의 해시를 볼 수 있습니다. 각 해시는 비밀번호를 암호화하는 데 사용되는 해시 메커니즘의 유형을 나타내는 기호로 시작합니다. DES를 사용하는 경우 시작 기호가 없습니다. MD5의 경우 기호는 `$`입니다. SHA256 및 SHA512의 경우 기호는 `$6$`입니다. Blowfish의 경우 기호는 `$2a$`입니다. 이 예제에서는 해시가 `$6$`로 시작하므로 `dru`의 비밀번호는 기본 SHA512 알고리즘을 사용하여 해시됩니다. 비밀번호 자체가 아닌 암호화된 해시가 비밀번호 데이터베이스에 저장된다는 점에 유의하세요:

[source, shell]
....
# grep dru /etc/master.passwd
dru:$6$pzIjSvCAn.PBYQBA$PXpSeWPx3g5kscj3IMiM7tUEUSPmGexxta.8Lt9TGSi2lNQqYGKszsBPuGME0:1001:1001::0:0:dru:/usr/home/dru:/bin/csh
....

해시 메커니즘은 사용자의 로그인 클래스에서 설정됩니다. 이 예제에서는 사용자가 ‘default’ 로그인 클래스에 있으며 해시 알고리즘은 [.filename]#/etc/login.conf#에 다음 줄로 설정되어 있습니다:

[.programlisting]
....
        :passwd_format=sha512:\
....

알고리즘을 블로우피쉬로 변경하려면 해당 줄을 다음과 같이 수정합니다:

[.programlisting]
....
        :passwd_format=blf:\
....

그런 다음 <<users-limiting>>>에 설명된 대로 `cap_mkdb /etc/login.conf`를 실행합니다. 이 변경 사항은 기존 비밀번호 해시에는 영향을 미치지 않습니다. 즉, 비밀번호를 변경하려면 사용자에게 `passwd`를 실행하도록 요청하여 모든 비밀번호를 다시 해시해야 합니다.

원격 로그인의 경우 2단계 인증을 사용해야 합니다. 2단계 인증의 예로는 키와 같은 “가지고 있는 것”과 해당 키의 암호와 같은 “알고 있는 것”이 있습니다. OpenSSH는 FreeBSD 기본 시스템의 일부이므로 모든 네트워크 로그인은 암호화된 연결을 통해 이루어져야 하며 비밀번호 대신 키 기반 인증을 사용해야 합니다. 자세한 내용은 <<openssh>>을 참조하세요. Kerberos 사용자는 네트워크에서 OpenSSH를 구현하기 위해 추가 변경을 수행해야 할 수 있습니다. 이러한 변경 사항은 <<kerberos5>>에 설명되어 있습니다.

[[security-pwpolicy]]
=== 비밀번호 정책 시행

로컬 계정에 강력한 암호 정책을 시행하는 것은 시스템 보안의 기본 요소입니다. FreeBSD에서는 내장된 PAM(플러그 가능한 인증 모듈)을 사용하여 암호 길이, 암호 강도 및 암호 복잡성을 구현할 수 있습니다.

이 섹션에서는 [.filename]#pam_passwdqc.so# 모듈을 사용하여 최소 및 최대 비밀번호 길이와 혼합 문자 적용을 구성하는 방법에 대해 설명합니다. 이 모듈은 사용자가 비밀번호를 변경할 때 적용됩니다.

이 모듈을 구성하려면 수퍼유저가 되어 [.filename]#/etc/pam.d/passwd#의 `pam_passwdqc.so`가 포함된 줄의 주석 처리를 해제합니다. 그런 다음 비밀번호 정책과 일치하도록 해당 줄을 편집합니다:

[.programlisting]
....
password        requisite       pam_passwdqc.so         min=disabled,disabled,disabled,12,10 similar=deny retry=3 enforce=users
....

이 예에서는 새 비밀번호에 대한 몇 가지 요구 사항을 설정합니다. `min` 설정은 최소 비밀번호 길이를 제어합니다. 이 모듈은 복잡도에 따라 다섯 가지 유형의 비밀번호를 정의하기 때문에 다섯 가지 값이 있습니다. 복잡도는 문자, 숫자, 특수문자, 대/소문자 등 비밀번호에 포함되어야 하는 문자 유형에 따라 정의됩니다. 비밀번호의 유형은 man:pam_passwdqc[8]에 설명되어 있습니다. 이 예에서는 처음 세 가지 유형의 비밀번호가 비활성화되어 있으므로 이러한 복잡도 요구 사항을 충족하는 비밀번호는 길이에 관계없이 허용되지 않습니다. `12`는 비밀번호에 세 가지 유형의 복잡도를 가진 문자가 포함된 경우 최소 12자 이상의 비밀번호 정책을 설정합니다. `10`은 비밀번호에 4가지 유형의 복잡도를 가진 문자가 포함된 경우 최소 10자 이상의 비밀번호도 허용하도록 비밀번호 정책을 설정합니다.

`similar` 설정은 사용자의 이전 비밀번호와 유사한 비밀번호를 거부합니다. `retry` 설정은 사용자에게 새 비밀번호를 입력할 수 있는 세 번의 기회를 제공합니다.

이 파일이 저장되면 비밀번호를 변경하는 사용자에게 다음과 유사한 메시지가 표시됩니다:

[source, shell]
....
% passwd
Changing local password for trhodes
Old Password:

You can now choose the new password.
A valid password should be a mix of upper and lower case letters,
digits and other characters.  You can use a 12 character long
password with characters from at least 3 of these 4 classes, or
a 10 character long password containing characters from all the
classes.  Characters that form a common pattern are discarded by
the check.
Alternatively, if no one else can see your terminal now, you can
pick this as your password: "trait-useful&knob".
Enter new password:
....

정책과 일치하지 않는 비밀번호를 입력하면 경고와 함께 거부되며 사용자는 구성된 재시도 횟수까지 다시 시도할 수 있는 기회를 갖게 됩니다.

대부분의 암호 정책은 암호가 특정 날짜 후에 만료되도록 요구합니다. FreeBSD에서 비밀번호 유효기간을 설정하려면 [.filename]#/etc/login.conf#에서 사용자의 로그인 클래스에 대해 `passwordtime`을 설정합니다. `default` 로그인 클래스에 예제가 포함되어 있습니다:

[.programlisting]
....
#       :passwordtime=90d:\
....

따라서 이 로그인 클래스의 만료일을 90일로 설정하려면 주석 기호(`+#+`)를 제거하고 편집 내용을 저장한 후 `cap_mkdb /etc/login.conf`를 실행합니다.

개별 사용자에 대해 만료일을 설정하려면 만료일 또는 만료일까지의 일수와 사용자 아이디를 `pw`로 전달합니다:

[source, shell]
....
# pw usermod -p 30-apr-2015 -n trhodes
....

여기에서 볼 수 있듯이 만료 날짜는 일, 월, 연도의 형태로 설정됩니다. 자세한 내용은 man:pw[8]을 참조하세요.

[[security-rkhunter]]
=== 루트킷 감지

_루트킷_은 시스템에 대한 `root`액세스 권한을 얻으려고 시도하는 무단 소프트웨어입니다. 이 악성 소프트웨어는 일단 설치되면 일반적으로 공격자에게 또 다른 침입 경로를 열어줍니다. 현실적으로 시스템이 루트킷에 의해 손상되어 조사를 수행한 후에는 시스템을 처음부터 다시 설치해야 합니다. 아무리 신중한 보안 또는 시스템 엔지니어라도 공격자가 남긴 무언가를 놓칠 위험이 매우 높습니다.

루트킷은 관리자에게 유용한 한 가지 기능을 수행합니다. 일단 탐지되면 어느 시점에 침해가 발생했다는 신호입니다. 하지만 이러한 유형의 애플리케이션은 매우 잘 숨겨져 있는 경향이 있습니다. 이 섹션에서는 루트킷을 탐지하는 데 사용할 수 있는 도구인 package:security/rkhunter[]를 보여줍니다.

이 패키지 또는 포트를 설치한 후 다음 명령을 사용하여 시스템을 확인할 수 있습니다. 이 명령은 많은 정보를 생성하며 kbd:[ENTER]를 수동으로 눌러야 합니다:

[source, shell]
....
# rkhunter -c
....

프로세스가 완료되면 화면에 상태 메시지가 인쇄됩니다. 이 메시지에는 검사한 파일의 양, 의심스러운 파일, 가능한 루트킷 등이 포함됩니다. 검사하는 동안 숨겨진 파일, OpenSSH 프로토콜 선택, 설치된 소프트웨어의 알려진 취약 버전에 대한 일반적인 보안 경고가 표시될 수 있습니다. 이러한 경고는 지금 처리하거나 더 자세한 분석이 수행된 후에 처리할 수 있습니다.

모든 관리자는 자신이 담당하는 시스템에서 무엇이 실행되고 있는지 알아야 합니다. rkhunter, package:sysutils/lsof[] 같은 타사 도구와 `netstat`, `ps` 같은 기본 명령은 시스템에 대한 많은 정보를 보여줄 수 있습니다. 무엇이 정상인지 메모하고, 뭔가 이상해 보이면 질문하고, 의심해 보세요. 보안 침해를 예방하는 것이 가장 이상적이지만, 보안 침해를 탐지하는 것은 필수입니다.

[[security-ids]]
=== 바이너리 검증

시스템 파일과 바이너리의 검증은 시스템 관리 및 보안 팀에 시스템 변경에 대한 정보를 제공하기 때문에 중요합니다. 시스템의 변경 사항을 모니터링하는 소프트웨어 애플리케이션을 침입 탐지 시스템(IDS)이라고 합니다.

FreeBSD는 기초적인 IDS 시스템에 대한 기본 지원을 제공합니다. 야간 보안 이메일은 관리자에게 변경 사항을 알려주지만, 이 정보는 로컬에 저장되므로 악의적인 사용자가 시스템에 대한 변경 사항을 숨기기 위해 이 정보를 수정할 가능성이 있습니다. 따라서 별도의 바이너리 서명 세트를 만들어 읽기 전용, 루트 소유 디렉터리 또는 이동식 USB 디스크 또는 원격 rsync 서버에 저장하는 것이 좋습니다.

내장된 `mtree` 유틸리티를 사용하여 디렉터리 콘텐츠의 사양을 생성할 수 있습니다. 시드 또는 숫자 상수는 사양을 생성하는 데 사용되며 사양이 변경되지 않았는지 확인하는 데 필요합니다. 이를 통해 파일 또는 바이너리가 수정되었는지 여부를 확인할 수 있습니다. 공격자가 시드 값을 알 수 없기 때문에 파일의 체크섬 값을 위조하거나 확인하는 것은 어렵거나 불가능합니다. 다음 예제는 [.filename]#/bin#의 각 시스템 바이너리에 대해 하나씩 SHA256 해시 집합을 생성하고 해당 값을 ‘root’의 홈 디렉터리인 [.filename]#/root/.bin_chksum_mtree#에 있는 숨겨진 파일에 저장합니다:

[source, shell]
....
# mtree -s 3483151339707503 -c -K cksum,sha256digest -p /bin > /root/.bin_chksum_mtree
# mtree: /bin checksum: 3427012225
....

_3483151339707503_은 시드를 나타냅니다. 이 값은 기억해야 하지만 공유해서는 안 됩니다.

[.filename]#/root/.bin_cksum_mtree#를 확인하면 다음과 비슷한 출력이 표시됩니다:

[.programlisting]
....
#          user: root
#       machine: dreadnaught
#          tree: /bin
#          date: Mon Feb  3 10:19:53 2014

# .
/set type=file uid=0 gid=0 mode=0555 nlink=1 flags=none
.               type=dir mode=0755 nlink=2 size=1024 \
                time=1380277977.000000000
    \133        nlink=2 size=11704 time=1380277977.000000000 \
                cksum=484492447 \
                sha256digest=6207490fbdb5ed1904441fbfa941279055c3e24d3a4049aeb45094596400662a
    cat         size=12096 time=1380277975.000000000 cksum=3909216944 \
                sha256digest=65ea347b9418760b247ab10244f47a7ca2a569c9836d77f074e7a306900c1e69
    chflags     size=8168 time=1380277975.000000000 cksum=3949425175 \
                sha256digest=c99eb6fc1c92cac335c08be004a0a5b4c24a0c0ef3712017b12c89a978b2dac3
    chio        size=18520 time=1380277975.000000000 cksum=2208263309 \
                sha256digest=ddf7c8cb92a58750a675328345560d8cc7fe14fb3ccd3690c34954cbe69fc964
    chmod       size=8640 time=1380277975.000000000 cksum=2214429708 \
                sha256digest=a435972263bf814ad8df082c0752aa2a7bdd8b74ff01431ccbd52ed1e490bbe7
....

이 보고서에는 머신의 호스트 이름, 사양이 생성된 날짜와 시간, 사양을 생성한 사용자의 이름이 포함됩니다. 디렉터리의 각 바이너리에 대한 체크섬, 크기, 시간, SHA256 다이제스트가 있습니다.

바이너리 서명이 변경되지 않았는지 확인하려면 디렉터리의 현재 내용을 이전에 생성한 사양과 비교하고 결과를 파일에 저장합니다. 이 명령에는 원본 사양을 생성하는 데 사용된 시드가 필요합니다:

[source, shell]
....
# mtree -s 3483151339707503 -p /bin < /root/.bin_chksum_mtree >> /root/.bin_chksum_output
# mtree: /bin checksum: 3427012225
....

이렇게 하면 사양을 생성할 때 생성된 것과 동일한 [.filename]#/bin#에 대한 체크섬이 생성되어야 합니다. 이 디렉터리의 바이너리에 변경 사항이 없는 경우 [.filename]#/root/.bin_chksum_output# 출력 파일은 비어 있습니다. 변경을 시뮬레이션하려면 `touch`를 사용하여 [.filename]#/bin/cat#의 날짜를 변경하고 확인 명령을 다시 실행합니다:

[source, shell]
....
# touch /bin/cat
# mtree -s 3483151339707503 -p /bin < /root/.bin_chksum_mtree >> /root/.bin_chksum_output
# more /root/.bin_chksum_output
cat changed
	modification time expected Fri Sep 27 06:32:55 2013 found Mon Feb  3 10:28:43 2014
....

바이너리와 구성 파일이 포함된 디렉터리와 민감한 데이터가 포함된 디렉터리에 대한 사양을 생성하는 것이 좋습니다. 일반적으로 [.filename]#/bin#, [.filename]#/sbin#, [.filename]#/usr/bin#, [.filename]#/usr/sbin#, [.filename]#/usr/local/bin#, [.filename]#/etc#, [.filename]#/usr/local/etc#에 대해 사양을 생성합니다.

package:security/aide[]과 같은 고급 IDS 시스템이 존재합니다. 대부분의 경우 `mtree`는 관리자가 필요로 하는 기능을 제공합니다. 시드 값과 체크섬 출력을 악의적인 사용자로부터 숨기는 것이 중요합니다. `mtree`에 대한 자세한 정보는 man:mtree[8]에서 확인할 수 있습니다.

[[security-tuning]]
=== 보안을 위한 시스템 튜닝

FreeBSD에서는 `sysctl`을 사용하여 많은 시스템 기능을 조정할 수 있습니다. 이 섹션에서는 서비스 거부(DoS) 공격을 방지하기 위해 조정할 수 있는 몇 가지 보안 기능에 대해 다룹니다. 일시적으로 값을 변경하는 방법과 테스트 후 변경 사항을 영구적으로 적용하는 방법을 포함하여 `sysctl` 사용에 대한 자세한 정보는 crossref:config[configtuning-sysctl,“Tuning with sysctl(8)”]에서 찾을 수 있습니다.

[NOTE]
====
`sysctl`로 설정을 변경할 때마다 원치 않는 피해를 유발하여 시스템 가용성에 영향을 미칠 가능성이 높아집니다. 모든 변경 사항은 모니터링하고 가능하면 프로덕션 시스템에서 사용하기 전에 테스트 시스템에서 시도해야 합니다.
====

기본적으로 FreeBSD 커널은 보안 수준 `-1`로 부팅됩니다. 이를 “안전하지 않은 모드”라고 부르는데, 변경 불가능한 파일 플래그가 꺼지고 모든 장치에서 읽거나 쓸 수 있기 때문입니다. 보안 수준은 `sysctl` 또는 시작 스크립트의 설정을 통해 변경하지 않는 한 `-1`로 유지됩니다. 시스템 시작 시 [.filename]#/etc/rc.conf#에서 `kern_securelevel_enable`을 `YES`로 설정하고 `kern_securelevel`의 값을 원하는 보안 수준으로 설정하여 보안 수준을 높일 수 있습니다. 이러한 설정과 사용 가능한 보안 수준에 대한 자세한 내용은 man:security[7] 및 man:init[8]을 참조하세요.

[WARNING]
====
`securelevel`을 높이면 Xorg가 중단되고 다른 문제가 발생할 수 있습니다. 디버깅을 할 준비를 하세요.
====

`net.inet.tcp.blackhole` 및 `net.inet.udp.blackhole` 설정을 사용하면 반환 RST 응답을 보내지 않고 닫힌 포트에서 들어오는 SYN 패킷을 드롭할 수 있습니다. 기본 동작은 포트가 닫혔음을 나타내는 RST를 반환하는 것입니다. 기본값을 변경하면 시스템에서 실행 중인 애플리케이션을 확인하는 데 사용되는 포트 검사에 대해 어느 정도 보호할 수 있습니다. `net.inet.tcp.blackhole`을 `2`로, `net.inet.udp.blackhole`을 `1`로 설정합니다. 이 설정에 대한 자세한 내용은 man:blackhole[4]을 참조하세요.

`net.inet.icmp.drop_redirect` 및 `net.inet.ip.redirect` 설정은 _리디렉션 공격_을 방지하는 데 도움이 됩니다. 리디렉션 공격은 대량의 ICMP 유형 5 패킷을 전송하는 DoS의 한 유형입니다. 이 패킷은 필요하지 않으므로 `net.inet.icmp.drop_redirect`를 `1`로 설정하고 `net.inet.ip.redirect`를 `0`으로 설정합니다.

소스 라우팅은 내부 네트워크에서 라우팅할 수 없는 주소를 감지하고 액세스하는 방법입니다. 라우팅할 수 없는 주소는 일반적으로 의도적으로 라우팅할 수 없으므로 이 기능은 비활성화해야 합니다. 이 기능을 비활성화하려면 `net.inet.ip.sourceroute` 및 `net.inet.ip.accept_sourceroute`를 `0`으로 설정하세요.

네트워크의 컴퓨터가 서브넷의 모든 호스트에 메시지를 보내야 하는 경우 ICMP 에코 요청 메시지가 브로드캐스트 주소로 전송됩니다. 그러나 외부 호스트가 이러한 작업을 수행할 이유는 없습니다. 모든 외부 브로드캐스트 요청을 거부하려면 `net.inet.icmp.bmcastecho`를 `0`으로 설정합니다.

일부 추가 설정은 man:security[7]에 문서화되어 있습니다.

[[one-time-passwords]]
== 일회용 비밀번호

기본적으로 14.x 이전 버전의 FreeBSD에는 OPIE(One-time Password In Everything)가 지원됩니다.

[NOTE]
====
OPIE는 더 이상 안전한 것으로 간주되지 않으며 FreeBSD -CURRENT에서 제거되었습니다; 14.x 이후부터는 사용할 수 없습니다. 13.x 이후 버전의 FreeBSD에서 OPIE를 사용하려면 package:security/opie[] 패키지 또는 포트를 사용할 수 있지만 권장되지는 않습니다.
====

OPIE는 공격자가 사용자의 비밀번호를 알아내어 시스템에 액세스하는 데 사용하는 리플레이 공격을 방지하도록 설계되었습니다. OPIE에서 비밀번호는 한 번만 사용되므로, 공격자가 발견한 비밀번호는 거의 쓸모가 없습니다. OPIE는 보안 해시와 챌린지/응답 시스템을 사용하여 암호를 관리합니다. FreeBSD 구현은 기본적으로 MD5 해시를 사용합니다.

OPIE는 세 가지 유형의 비밀번호를 사용합니다. 첫 번째는 일반적인 UNIX(R) 또는 Kerberos 암호입니다. 두 번째는 `opiekey`에 의해 생성되는 일회용 비밀번호입니다. 세 번째 유형의 비밀번호는 일회용 비밀번호를 생성하는 데 사용되는 “비밀 비밀번호”입니다. 비밀 비밀번호는 UNIX(R) 비밀번호와 관련이 없으며, UNIX(R) 비밀번호와는 달라야 합니다.

OPIE에 중요한 두 가지 데이터가 더 있습니다. 하나는 두 글자와 다섯 자리 숫자로 구성된 “시드” 또는 “키”입니다. 다른 하나는 1에서 100 사이의 숫자인 “반복 횟수”입니다. OPIE는 시드와 비밀 비밀번호를 연결하고, 반복 횟수에 지정된 횟수만큼 MD5 해시를 적용한 다음, 그 결과를 일회용 비밀번호를 나타내는 6개의 짧은 영어 단어로 변환하여 일회용 비밀번호를 생성합니다. 인증 시스템은 마지막으로 사용된 일회용 비밀번호를 추적하고, 사용자가 제공한 비밀번호의 해시가 이전 비밀번호와 동일한 경우 사용자를 인증합니다. 단방향 해시를 사용하기 때문에 성공적으로 사용된 비밀번호가 캡처되면 향후 일회용 비밀번호를 생성할 수 없습니다. 반복 횟수는 로그인에 성공할 때마다 감소하여 사용자와 로그인 프로그램의 동기화를 유지합니다. 반복 횟수가 ‘1’이 되면 OPIE를 다시 초기화해야 합니다.

이 과정에는 몇 가지 프로그램이 관여합니다. 일회용 비밀번호 또는 일회용 비밀번호의 연속 목록은 반복 횟수, 시드, 비밀 비밀번호를 man:opiekey[1]에 전달하여 생성됩니다. OPIE를 초기화하는 것 외에도 man:opiepasswd[1]는 비밀번호, 반복 횟수 또는 시드를 변경하는 데 사용됩니다. [filename]#/etc/opiekeys#에 있는 관련 자격증명 파일은 호출하는 사용자의 현재 반복 횟수와 시드를 출력하는 man:opieinfo[1]에 의해 검사됩니다.

이 섹션에서는 네 가지 종류의 작업에 대해 설명합니다. 첫 번째는 보안 연결을 통해 처음으로 일회용 비밀번호를 설정하는 방법입니다. 두 번째는 안전하지 않은 연결에서 `opiepasswd`를 사용하는 방법입니다. 세 번째는 안전하지 않은 연결에서 로그인하는 방법입니다. 네 번째는 안전하지 않은 위치에서 사용하기 위해 기록하거나 인쇄할 수 있는 여러 개의 키를 생성하는 방법입니다.

=== OPIE 초기화하기

OPIE를 처음 초기화하려면 안전한 위치에서 이 명령을 실행하세요:

[source, shell]
....
% opiepasswd -c
Adding unfurl:
Only use this method from the console; NEVER from remote. If you are using
telnet, xterm, or a dial-in, type ^C now or exit with no password.
Then run opiepasswd without the -c parameter.
Using MD5 to compute responses.
Enter new secret pass phrase:
Again new secret pass phrase:

ID unfurl OTP key is 499 to4268
MOS MALL GOAT ARM AVID COED
....

`-c`는 명령이 사용자가 제어하는 컴퓨터 또는 사용자가 제어하는 컴퓨터에 대한 SSH 세션과 같은 보안 위치에서 실행되고 있다고 가정하는 콘솔 모드를 설정합니다.

메시지가 표시되면 일회용 로그인 키를 생성하는 데 사용할 비밀 비밀번호를 입력합니다. 이 비밀번호는 추측하기 어렵고 사용자의 로그인 계정과 연결된 비밀번호와 달라야 합니다. 비밀번호 길이는 10~127자 사이여야 합니다. 이 비밀번호를 기억하세요.

`ID` 줄에는 로그인 이름(`unfurl`), 기본 반복 횟수(`499`), 기본 시드(`to4268`)가 나열됩니다. 로그인할 때 시스템이 이러한 매개변수를 기억하여 표시하므로 기억할 필요가 없습니다. 마지막 줄에는 해당 매개변수에 해당하는 생성된 일회용 비밀번호와 비밀 비밀번호가 나열됩니다. 다음에 로그인할 때 이 일회용 비밀번호를 사용하세요.

=== 안전하지 않은 연결 초기화

안전하지 않은 시스템에서 비밀 비밀번호를 초기화하거나 변경하려면 `opiekey`를 실행할 수 있는 곳에 보안 연결이 필요합니다. 신뢰할 수 있는 컴퓨터의 셸 프롬프트일 수 있습니다. 반복 횟수는 100이 적당하며, 시드는 지정하거나 무작위로 생성된 시드를 사용할 수 있습니다. 안전하지 않은 연결에서 초기화 중인 머신은 man:opiepasswd[1]을 사용합니다:

[source, shell]
....
% opiepasswd

Updating unfurl:
You need the response from an OTP generator.
Old secret pass phrase:
	otp-md5 498 to4268 ext
	Response: GAME GAG WELT OUT DOWN CHAT
New secret pass phrase:
	otp-md5 499 to4269
	Response: LINE PAP MILK NELL BUOY TROY

ID mark OTP key is 499 gr4269
LINE PAP MILK NELL BUOY TROY
....

기본 시드를 수락하려면 kbd:[Return]을 누릅니다. 액세스 비밀번호를 입력하기 전에 보안 연결로 이동하여 동일한 매개 변수를 입력합니다:

[source, shell]
....
% opiekey 498 to4268
Using the MD5 algorithm to compute response.
Reminder: Do not use opiekey from telnet or dial-in sessions.
Enter secret pass phrase:
GAME GAG WELT OUT DOWN CHAT
....

안전하지 않은 연결로 다시 전환하고 생성된 일회용 비밀번호를 관련 프로그램에 복사합니다.

=== 단일 일회용 비밀번호 생성하기

OPIE를 초기화하고 로그인하면 다음과 같은 메시지가 표시됩니다:

[source, shell]
....
% telnet example.com
Trying 10.0.0.1...
Connected to example.com
Escape character is '^]'.

FreeBSD/i386 (example.com) (ttypa)

login: <username>
otp-md5 498 gr4269 ext
Password:
....

OPIE 프롬프트는 유용한 기능을 제공합니다. 비밀번호 프롬프트에서 kbd:[Return]을 누르면 프롬프트가 에코를 켜고 입력한 내용을 표시합니다. 이 기능은 인쇄물에서 직접 비밀번호를 입력하려고 할 때 유용합니다.

이 시점에서 로그인 프롬프트에 응답할 일회용 비밀번호를 생성합니다. 이 작업은 man:opiekey[1]를 실행해도 안전한 신뢰할 수 있는 시스템에서 수행해야 합니다. 이 명령은 Windows(R), Mac OS(R) 및 FreeBSD용 버전이 있습니다. 이 명령은 명령줄 옵션으로 반복 횟수와 시드가 필요합니다. 로그인하려는 컴퓨터의 로그인 프롬프트에서 잘라내기 및 붙여넣기를 사용합니다.

신뢰할 수 있는 시스템에서:

[source, shell]
....
% opiekey 498 to4268
Using the MD5 algorithm to compute response.
Reminder: Do not use opiekey from telnet or dial-in sessions.
Enter secret pass phrase:
GAME GAG WELT OUT DOWN CHAT
....

일회용 비밀번호가 생성되면 계속 로그인합니다.

=== 여러 개의 일회용 비밀번호 생성하기

신뢰할 수 있는 컴퓨터나 보안 연결에 액세스할 수 없는 경우가 있습니다. 이 경우 man:opiekey[1]를 사용하여 미리 여러 개의 일회용 비밀번호를 생성할 수 있습니다. 예를 들어:

[source, shell]
....
% opiekey -n 5 30 zz99999
Using the MD5 algorithm to compute response.
Reminder: Do not use opiekey from telnet or dial-in sessions.
Enter secret pass phrase: <secret password>
26: JOAN BORE FOSS DES NAY QUIT
27: LATE BIAS SLAY FOLK MUCH TRIG
28: SALT TIN ANTI LOON NEAL USE
29: RIO ODIN GO BYE FURY TIC
30: GREW JIVE SAN GIRD BOIL PHI
....

`-n 5` 는 5개의 키를 순서대로 요청하고 `30`은 마지막 반복 횟수를 지정합니다. 사용 순서의 _역_ 순서로 출력된다는 점에 유의하세요. 정말 편집증적인 사람은 결과를 손으로 적고 싶을 수도 있지만, 그렇지 않다면 목록을 인쇄하세요. 각 줄에는 반복 횟수와 일회용 비밀번호가 모두 표시됩니다. 사용한 비밀번호는 지워버리세요.

=== UNIX(R) 암호 사용 제한하기

OPIE는 로그인 세션의 IP 주소에 따라 UNIX(R) 비밀번호 사용을 제한할 수 있습니다. 관련 파일은 [.filename]#/etc/opieaccess#이며, 기본적으로 존재합니다. 이 파일에 대한 자세한 내용과 이 파일을 사용할 때 주의해야 할 보안 고려사항은 man:opieaccess[5]를 참조하세요.

[.filename]#opieaccess#의 샘플이 있습니다:

[.programlisting]
....
permit 192.168.0.0 255.255.0.0
....

이 줄을 사용하면 스푸핑에 취약한 IP 소스 주소가 지정된 값과 마스크와 일치하는 사용자는 언제든지 UNIX(R) 비밀번호를 사용할 수 있습니다.

[.filename]#opieaccess#에 일치하는 규칙이 없는 경우 기본값은 OPIE가 아닌 로그인을 거부합니다.

[[tcpwrappers]]
== TCP 래퍼

TCP 래퍼는 crossref:network-servers[network-inetd,“The inetd Super-Server”]의 기능을 확장하는 호스트 기반 액세스 제어 시스템입니다. inetd의 제어를 받는 서버 데몬에 대해 로깅 지원, 메시지 반환 및 연결 제한을 제공하도록 구성할 수 있습니다. TCP 래퍼와 그 기능에 대한 자세한 내용은 man:tcpd[8]을 참조하세요.

TCP 래퍼는 제대로 구성된 방화벽을 대체하는 것으로 간주해서는 안 됩니다. 대신, 보안 정책을 구현할 때 또 다른 보호 계층을 제공하기 위해 방화벽 및 기타 보안 향상 기능과 함께 TCP 래퍼를 사용해야 합니다.

=== 초기 구성

FreeBSD에서 TCP 래퍼를 활성화하려면 [.filename]#/etc/rc.conf#에 다음 줄을 추가합니다:

[.programlisting]
....
inetd_enable="YES"
inetd_flags="-Ww"
....

그리고 나서 [.filename]#/etc/hosts.allow#를 적절히 구성합니다.

[NOTE]
====
다른 TCP 래퍼 구현과 달리, [.filename]#hosts.deny#의 사용은 FreeBSD에서 더 이상 사용되지 않습니다. 모든 구성 옵션은 [.filename]#/etc/hosts.allow#에 배치해야 합니다.
====

가장 간단한 구성에서 데몬 연결 정책은 [.filename]#/etc/hosts.allow#의 옵션에 따라 허용 또는 차단으로 설정됩니다. FreeBSD의 기본 구성은 inetd로 시작하는 데몬에 대한 모든 연결을 허용하는 것입니다.

기본 구성은 일반적으로 `daemon : address : action`의 형식을 취하는데, 여기서 `daemon`은 inetd를 시작한 데몬이고, `address`는 괄호([ ])로 묶인 유효한 호스트 이름, IP 주소 또는 IPv6 주소이며, `action`은 `allow` 또는 `deny` 중 하나입니다. TCP 래퍼는 첫 번째 규칙 일치 시맨틱을 사용합니다. 즉, 구성 파일에서 일치하는 규칙이 있는지 처음부터 검색합니다. 일치하는 규칙이 발견되면 규칙이 적용되고 검색 프로세스가 중지됩니다.

예를 들어 package:mail/qpopper[] 데몬을 통해 POP3 연결을 허용하려면 [.filename]#hosts.allow#에 다음 줄을 추가해야 합니다:

[.programlisting]
....
# This line is required for POP3 connections:
qpopper : ALL : allow
....

이 파일을 편집할 때마다 inetd를 다시 시작합니다:

[source, shell]
....
# service inetd restart
....

=== 고급 구성

TCP 래퍼는 연결이 처리되는 방식을 더 잘 제어할 수 있는 고급 옵션을 제공합니다. 경우에 따라 특정 호스트나 데몬 연결에 대한 코멘트를 반환하는 것이 적절할 수 있습니다. 다른 경우에는 로그 항목을 기록하거나 관리자에게 이메일을 보내야 합니다. 다른 상황에서는 로컬 연결 전용 서비스를 사용해야 할 수도 있습니다. 와일드카드, 확장 문자, 외부 명령 실행으로 알려진 구성 옵션을 사용하면 이 모든 것이 가능합니다.

연결을 거부해야 하지만 연결을 시도한 호스트에게 이유를 보내야 하는 상황이 발생한다고 가정해 보겠습니다. `twist`를 사용하면 이러한 작업이 가능합니다. 연결이 시도되면 `twist`는 셸 명령 또는 스크립트를 실행합니다. 예제는 [.filename]#hosts.allow#에 있습니다:

[.programlisting]
....
# The rest of the daemons are protected.
ALL : ALL \
	: severity auth.info \
	: twist /bin/echo "You are not welcome to use %d from %h."
....

이 예에서는 [.filename]#hosts.allow#에서 구성되지 않은 데몬에 대해 “_호스트명_에서 _데몬 이름_을 사용할 수 없습니다.”라는 메시지가 반환됩니다. 이는 설정된 연결이 끊어진 직후 연결 개시자에게 회신을 보낼 때 유용합니다. 반환되는 모든 메시지는 따옴표(`”`) 문자로 묶어야 합니다.

[WARNING]
====
공격자가 이러한 데몬에 연결 요청을 폭주하면 서버에 대한 서비스 거부 공격을 시작할 수 있습니다.
====

또 다른 가능성은 `spawn`을 사용하는 것입니다. `twist`와 마찬가지로 `spawn`은 암시적으로 연결을 거부하며 외부 셸 명령이나 스크립트를 실행하는 데 사용될 수 있습니다. `twist`와 달리 `spawn`은 연결을 설정한 호스트에게 응답을 보내지 않습니다. 예를 들어 다음 구성을 고려하세요:

[.programlisting]
....
# We do not allow connections from example.com:
ALL : .example.com \
	: spawn (/bin/echo %a from %h attempted to access %d >> \
	  /var/log/connections.log) \
	: deny
....

이렇게 하면 `*.example.com`으로부터의 모든 연결 시도가 거부되고 호스트 이름, IP 주소, 액세스가 시도된 데몬을 [.filename]#/var/log/connections.log#에 기록합니다. 이 예에서는 대체 문자 `%a`와 `%h`를 사용합니다. 전체 목록은 man:hosts_access[5]를 참조하세요.

데몬, 도메인 또는 IP 주소의 모든 인스턴스를 일치시키려면 `ALL`을 사용합니다. 또 다른 와일드카드는 `PARANOID`로, IP 주소가 확인된 호스트 이름과 다르기 때문에 위조되었을 수 있는 IP 주소를 제공하는 모든 호스트와 일치시키는 데 사용할 수 있습니다. 이 예에서는 호스트 이름과 다른 IP 주소를 가진 센드메일에 대한 모든 연결 요청이 거부됩니다:

[.programlisting]
....
# Block possibly spoofed requests to sendmail:
sendmail : PARANOID : deny
....

[CAUTION]
====
`PARANOID` 와일드카드를 사용하면 클라이언트 또는 서버의 DNS 설정이 손상된 경우 연결이 거부됩니다.
====

와일드카드 및 관련 기능에 대해 자세히 알아보려면 man:hosts_access[5]를 참조하세요.

[NOTE]
====
새 구성 줄을 추가할 때 해당 데몬에 대한 불필요한 항목이 [.filename]#hosts.allow#에 주석 처리되어 있는지 확인하세요.
====

[[kerberos5]]
== Kerberos

Kerberos는 잠재적으로 적대적인 네트워크에서 안전하게 인증을 제공하기 위해 매사추세츠 공과대학(MIT)에서 만든 네트워크 인증 프로토콜입니다. Kerberos 프로토콜은 강력한 암호화를 사용하여 클라이언트와 서버 모두 암호화되지 않은 비밀을 네트워크를 통해 전송하지 않고도 자신의 신원을 증명할 수 있습니다. Kerberos는 신원 확인 프록시 시스템과 신뢰할 수 있는 타사 인증 시스템으로 설명할 수 있습니다. 사용자가 Kerberos로 인증하면 통신을 암호화하여 개인 정보 보호 및 데이터 무결성을 보장할 수 있습니다.

Kerberos의 유일한 기능은 네트워크에서 사용자와 서버에 대한 보안 인증을 제공하는 것입니다. 권한 부여 또는 감사 기능은 제공하지 않습니다. Kerberos는 권한 부여 및 감사 서비스를 제공하는 다른 보안 방법과 함께 사용하는 것이 좋습니다.

현재 프로토콜의 버전은 RFC 4120에 설명된 버전 5입니다. 이 프로토콜은 다양한 운영 체제를 지원하는 여러 무료 구현을 사용할 수 있습니다. MIT는 Kerberos 패키지를 계속 개발하고 있습니다. 이 패키지는 미국에서 암호화 제품으로 일반적으로 사용되며, 역사적으로 미국 수출 규제의 적용을 받아왔습니다. FreeBSD에서 MITKerberos는 package:security/krb5[] 패키지 또는 포트로 제공됩니다. 하임달 케르베로스(Heimdal Kerberos) 구현은 수출 규제를 피하기 위해 미국 이외의 지역에서 명시적으로 개발되었습니다. 하임달 케르베로스 배포판은 기본 FreeBSD 설치에 포함되어 있으며, 구성 가능한 옵션이 더 많은 다른 배포판은 포트 컬렉션에서 package:security/heimdal[]로 사용할 수 있습니다.

Kerberos에서 사용자 및 서비스는 “영역(Realm)”이라고 하는 관리 그룹 내에 포함된 “주체(Principal)”로 식별됩니다. 일반적인 사용자 주체는 `_user_@_REALM_` 형식입니다(영역은 전통적으로 대문자임).

이 섹션에서는 FreeBSD에 포함된 하임달 배포판을 사용하여 Kerberos를 설정하는 방법에 대한 가이드를 제공합니다.

Kerberos 설치 데모를 위해 이름 공간(Name space)은 다음과 같습니다:

* DNS 도메인(영역)은 `example.org`가 됩니다.
* Kerberos 영역은 `EXAMPLE.ORG`가 됩니다.

[NOTE]
====
내부에서 실행되는 경우에도 Kerberos를 설정할 때는 실제 도메인 이름을 사용하세요. 이렇게 하면 DNS 문제를 방지하고 다른 Kerberos 영역과의 상호 운용을 보장할 수 있습니다.
====

=== 하임달 KDC 설정하기

KDC(Key Distribution Center)는 Kerberos가 제공하는 중앙 집중식 인증 서비스로, 시스템의 “신뢰할 수 있는 제3자”입니다. 여기서 KDC는 클라이언트가 서버에 인증하는 데 사용되는 Kerberos 티켓을 발급하는 컴퓨터입니다. KDC는 Kerberos 영역의 다른 모든 컴퓨터에서 신뢰할 수 있는 것으로 간주되므로 보안에 대한 우려가 높습니다. KDC에 대한 직접 액세스는 제한되어야 합니다.

KDC를 실행하는 데는 컴퓨팅 리소스가 거의 필요하지 않지만, 보안상의 이유로 KDC 역할만 하는 전용 머신을 사용하는 것이 좋습니다.

시작하려면 다음과 같이 package:security/heimdal[] 패키지를 설치합니다:

[source, shell]
....
# pkg install heimdal
....

그런 다음 `sysrc`를 사용하여 다음과 같이 [.filename]#/etc/rc.conf#를 업데이트합니다:

[source, shell]
....
# sysrc kdc_enable=yes
# sysrc kadmind_enable=yes
....

다음으로 [.filename]#/etc/krb5.conf#을 편집합니다:

[.programlisting]
....
[libdefaults]
    default_realm = EXAMPLE.ORG
[realms]
    EXAMPLE.ORG = {
	kdc = kerberos.example.org
	admin_server = kerberos.example.org
    }
[domain_realm]
    .example.org = EXAMPLE.ORG
....

이 예제에서 KDC는 정규화된 호스트 이름인 `kerberos.example.org`를 사용합니다. KDC의 호스트 이름은 DNS에서 확인할 수 있어야 합니다.

Kerberos는 또한 [.filename]#/etc/krb5.conf#의 `[realms]` 섹션 대신 DNS를 사용하여 KDC를 찾을 수 있습니다. 자체 DNS 서버가 있는 대규모 조직의 경우 위의 예제를 다음과 같이 다듬을 수 있습니다:

[.programlisting]
....
[libdefaults]
      default_realm = EXAMPLE.ORG
[domain_realm]
    .example.org = EXAMPLE.ORG
....

`example.org` 영역 파일에 다음 줄이 포함되어 있습니다:

[.programlisting]
....
_kerberos._udp      IN  SRV     01 00 88 kerberos.example.org.
_kerberos._tcp      IN  SRV     01 00 88 kerberos.example.org.
_kpasswd._udp       IN  SRV     01 00 464 kerberos.example.org.
_kerberos-adm._tcp  IN  SRV     01 00 749 kerberos.example.org.
_kerberos           IN  TXT     EXAMPLE.ORG
....

[NOTE]
====
클라이언트가 Kerberos 서비스를 찾을 수 있으려면 완전히 구성된 [.filename]#/etc/krb5.conf# 또는 최소로 구성된 [.filename]#/etc/krb5.conf#과 제대로 구성된 DNS _서버가 있어야_ 합니다.
====

다음으로 마스터 비밀번호로 암호화된 모든 주체(사용자 및 호스트)의 키가 포함된 Kerberos 데이터베이스를 만듭니다. 이 비밀번호는 [.filename]#/var/heimdal/m-key#에 저장되므로 기억할 필요가 없으며, 45자 임의의 비밀번호를 사용하는 것이 좋습니다. 마스터 키를 생성하려면 `kstash`를 실행하고 비밀번호를 입력합니다:

[source, shell]
....
# kstash
Master key: xxxxxxxxxxxxxxxxxxxxxxx
Verifying password - Master key: xxxxxxxxxxxxxxxxxxxxxxx
....

마스터 키가 생성되면 데이터베이스를 초기화해야 합니다. Kerberos 관리 도구 man:kadmin[8]은 `kadmin -l`로 man:kadmind[8] 네트워크 서비스를 구동하지 않고 데이터베이스에서 직접 KDC에서 사용할 수 있습니다. 이렇게 하면 데이터베이스가 생성되기 전에 데이터베이스에 연결하려고 시도하는 닭과 달걀 문제를 해결할 수 있습니다. `kadmin` 프롬프트에서 `init`을 사용하여 영역의 초기 데이터베이스를 만듭니다:

[source, shell]
....
# kadmin -l
kadmin> init EXAMPLE.ORG
Realm max ticket life [unlimited]:
....

마지막으로 `kadmin`에 있는 동안 `add`를 사용하여 첫 번째 주체(Principal)를 생성합니다. 나중에 `modify`를 사용하여 변경할 수 있으므로 지금은 기본 옵션을 그대로 사용합니다. 프롬프트에 `?`를 입력하여 사용 가능한 옵션을 확인합니다.

[source, shell]
....
kadmin> add tillman
Max ticket life [unlimited]:
Max renewable life [unlimited]:
Principal expiration time [never]:
Password expiration time [never]:
Attributes []:
Password: xxxxxxxx
Verifying password - Password: xxxxxxxx
....

아래의 명령으로 KDC 서비스를 시작합니다:

[source, shell]
....
# service kdc start
# service kadmind start
....

이 시점에서 실행 중인 케르베로스화된 데몬은 없지만 방금 생성한 주체에 대한 티켓을 가져와서 KDC가 작동 중인지 확인할 수 있습니다:

[source, shell]
....
% kinit tillman
tillman@EXAMPLE.ORG's Password:
....

`klist`를 사용하여 티켓을 성공적으로 받았는지 확인합니다:

[source, shell]
....
% klist
Credentials cache: FILE:/tmp/krb5cc_1001
	Principal: tillman@EXAMPLE.ORG

  Issued                Expires               Principal
Aug 27 15:37:58 2013  Aug 28 01:37:58 2013  krbtgt/EXAMPLE.ORG@EXAMPLE.ORG
....

임시 티켓은 테스트가 완료되면 폐기할 수 있습니다:

[source, shell]
....
% kdestroy
....

=== 케르베로스 사용을 위한 서버 구성하기

Kerberos 인증을 사용하도록 서버를 구성하는 첫 번째 단계는 [.filename]#/etc/krb5.conf#에 올바른 구성이 있는지 확인하는 것입니다. KDC의 버전을 그대로 사용하거나 새 시스템에서 다시 생성할 수 있습니다.

그런 다음 서버에 [.filename]#/etc/krb5.keytab#을 만듭니다. 이것은 서비스 “케르베로스화(Kerberizing)”의 주요 부분으로, 서비스와 KDC 간에 공유되는 시크릿을 생성하는 것에 해당합니다. 시크릿은 암호화 키로, “keytab”에 저장됩니다. keytab에는 서버의 호스트 키가 포함되어 있어 서버와 KDC가 서로의 신원을 확인할 수 있습니다. 키가 공개되면 서버의 보안이 손상될 수 있으므로 안전한 방식으로 서버에 전송해야 합니다. 일반적으로 관리자가 신뢰할 수 있는 컴퓨터에서 `kadmin`을 사용하여 [.filename]#keytab#을 생성한 다음 man:scp[1] 등을 사용하여 서버로 안전하게 전송하지만, 원하는 보안 정책에 부합하는 경우 서버에서 직접 생성할 수도 있습니다. 키탭이 안전한 방식으로 서버로 전송되는 것이 매우 중요합니다. 다른 사람이 키를 알고 있으면 그 사람이 서버에 어떤 사용자든 사칭할 수 있기 때문입니다! KDC 데이터베이스의 호스트 주체에 대한 항목도 `kadmin`을 사용하여 생성되므로 서버에서 `kadmin`을 직접 사용하는 것이 편리합니다.

물론 `kadmin`은 케르베로스화된 서비스이므로 네트워크 서비스에 인증하려면 케르베로스 티켓이 필요하지만, `kadmin`을 실행하는 사용자가 실제로 존재하고 세션이 도용되지 않았는지 확인하기 위해 `kadmin`은 새 티켓을 얻기 위해 암호를 입력하라는 메시지를 표시합니다. kadmin 서비스에 인증하는 주체는 [.filename]#/var/heimdal/kadmind.acl#에 지정된 대로 `kadmin` 인터페이스를 사용할 수 있도록 허용되어야 합니다. 액세스 제어 목록 설계에 대한 자세한 내용은 `info heimda`의 “Remote administration” 섹션을 참조하세요. 관리자는 원격 `kadmin` 액세스를 활성화하는 대신 로컬 콘솔 또는 man:ssh[1]를 통해 KDC에 안전하게 연결하고 `kadmin -l`을 사용하여 로컬에서 관리를 수행할 수 있습니다.

[.filename]#/etc/krb5.conf#을 설치한 후 `kadmin`에서 `add —random-key`를 사용합니다. 이렇게 하면 서버의 호스트 주체가 데이터베이스에 추가되지만 호스트 주체의 키 복사본이 키탭으로 추출되지는 않습니다. 키탭을 생성하려면 `ext`를 사용하여 서버의 호스트의 principal 키를 자체 키탭으로 추출합니다:

[source, shell]
....
# kadmin
kadmin> add --random-key host/myserver.example.org
Max ticket life [unlimited]:
Max renewable life [unlimited]:
Principal expiration time [never]:
Password expiration time [never]:
Attributes []:
kadmin> ext_keytab host/myserver.example.org
kadmin> exit
....

`ext_keytab`은 기본적으로 추출된 키를 [.filename]#/etc/krb5.keytab#에 저장한다는 점에 유의하세요. 이는 케르베로스화 되는 서버에서 실행할 때 유용하지만, 키탭을 다른 곳에서 추출할 때는 `—keytab _path/to/file_` 인수를 사용해야 합니다:

[source, shell]
....
# kadmin
kadmin> ext_keytab --keytab=/tmp/example.keytab host/myserver.example.org
kadmin> exit
....

그런 다음 man:scp[1] 또는 이동식 미디어를 사용하여 키탭(keytab)을 서버에 안전하게 복사할 수 있습니다. 시스템의 키탭에 불필요한 키가 삽입되지 않도록 기본 키탭 이름이 아닌 다른 이름을 지정해야 합니다.

이 시점에서 서버는 [.filename]#krb5.keytab#에 저장된 공유 키를 사용하여 KDC에서 암호화된 메시지를 읽을 수 있습니다. 이제 Kerberos를 사용하는 서비스를 사용할 준비가 되었습니다. 이러한 서비스 중 가장 일반적인 서비스 중 하나는 GSS-API를 통해 Kerberos를 지원하는 man:sshd[8]입니다. [.filename]#/etc/ssh/sshd_config#에 다음 줄을 추가합니다:

[.programlisting]
....
GSSAPIAuthentication yes
....

변경된 사항을 적용하려면 man:sshd[8]를 다시 시작해야 합니다: `service sshd restart`.

=== 케르베로스를 사용하는 클라이언트 구성하기

서버에서와 마찬가지로 클라이언트에서도 [.filename]#/etc/krb5.conf#에 구성이 필요합니다. 파일을 (안전하게) 복사하거나 필요에 따라 다시 입력합니다.

클라이언트에서 `kinit`, `klist` 및 `kdestroy`를 사용하여 기존 주체에 대한 티켓을 가져와서 표시한 다음 삭제하여 클라이언트를 테스트합니다. Kerberos 애플리케이션도 Kerberos 사용 서버에 연결할 수 있어야 합니다. 그렇게 해도 작동하지 않지만 티켓을 얻는 데는 성공한다면 클라이언트나 KDC가 아니라 서버에 문제가 있을 가능성이 높습니다. 케르베로스화된 man:ssh[1]의 경우 GSS-API는 기본적으로 비활성화되어 있으므로 `ssh -o GSSAPIAuthentication=yes _hostname_`을 사용하여 테스트하세요.

케르베로스화된 애플리케이션을 테스트할 때는 `tcpdump`와 같은 패킷 스니퍼를 사용하여 민감한 정보가 전송되지 않는지 확인하세요.

다양한 Kerberos 클라이언트 애플리케이션을 사용할 수 있습니다. 인증에 SASL을 사용하는 애플리케이션이 GSS-API 메커니즘도 사용할 수 있도록 브리지가 등장함에 따라 Jabber 클라이언트에서 IMAP 클라이언트에 이르기까지 다양한 종류의 클라이언트 애플리케이션이 인증에 Kerberos를 사용할 수 있게 되었습니다.

영역(Realm) 내의 사용자는 일반적으로 Kerberos 주체가 로컬 사용자 계정에 매핑되어 있습니다. 때때로 일치하는 Kerberos 주체가 없는 사람에게 로컬 사용자 계정에 대한 액세스 권한을 부여해야 하는 경우가 있습니다. 예를 들어, `tillman@EXAMPLE.ORG`은 로컬 사용자 계정 `webdevelopers`에 대한 액세스 권한이 필요할 수 있습니다. 다른 주체는 해당 로컬 계정에 대한 액세스 권한도 필요할 수 있습니다.

사용자의 홈 디렉터리에 있는 [.filename]#.k5login# 및 [.filename]#.k5users# 파일을 사용하여 이 문제를 해결할 수 있습니다. 예를 들어 [.filename]#.k5login#을 `webdevelopers`의 홈 디렉터리에 배치하면 양쪽 주체(Principal) 모두 공유 비밀번호 없이도 해당 계정에 액세스할 수 있습니다:

[.programlisting]
....
tillman@example.org
jdoe@example.org
....

man:ksu[1]에서 [.filename]#.k5users#에 대한 자세한 내용을 참조하세요.

=== MIT 차이점

MIT와 Heimdal 구현의 가장 큰 차이점은 `kadmin`의 명령 집합이 다르지만 동일하며, 다른 프로토콜을 사용한다는 것입니다. KDC가 MIT인 경우 Heimdal 버전의 `kadmin`을 사용하여 원격으로 KDC를 관리할 수 없으며, 그 반대의 경우도 마찬가지입니다.

클라이언트 애플리케이션은 동일한 작업을 수행하기 위해 약간 다른 명령줄 옵션을 사용할 수도 있습니다. http://web.mit.edu/Kerberos/www/[http://web.mit.edu/Kerberos/www/]의 지침을 따르는 것이 좋습니다. 경로 문제에 주의하세요: MIT 포트는 기본적으로 [.filename]#/usr/local/#에 설치되며, `PATH`에 시스템 디렉터리가 먼저 나열되어 있으면 MIT 버전 대신 FreeBSD 시스템 애플리케이션이 실행됩니다.

FreeBSD에서 MIT Kerberos를 KDC로 사용하는 경우 [.filename]#rc.conf#도 다음과 같이 편집해야 합니다:

[.programlisting]
....
kdc_program="/usr/local/sbin/kdc"
kadmind_program="/usr/local/sbin/kadmind"
kdc_flags=""
kdc_enable="YES"
kadmind_enable="YES"
....

=== 케르베로스 팀과 트릭, 그리고 문제해결

Kerberos를 구성하고 문제를 해결할 때는 다음 사항에 유의하세요:

* 포트에서 Heimdal 또는 MITKerberos를 사용하는 경우, `PATH`에 시스템 버전보다 먼저 포트의 클라이언트 애플리케이션 버전이 나열되어 있는지 확인하세요.
* 영역(Realm) 내 모든 컴퓨터의 시간 설정이 동기화되어 있지 않으면 인증에 실패할 수 있습니다. crossref:network-servers[network-ntp,“Clock Synchronization with NTP”]에서는 NTP를 사용하여 시계를 동기화하는 방법을 설명합니다.
* 호스트명이 변경되면 `host/` 주체(Principal)를 변경하고 keytab을 업데이트해야 합니다. 이는 아파치 package:www/mod_auth_kerb[]에 사용되는 `HTTP/` 주체와 같은 특수 키탭 항목에도 적용됩니다.
* 영역(Realm)의 모든 호스트는 DNS에서 정방향 및 역방향으로 모두 확인 가능하거나 최소한 [.filename]#/etc/hosts#에 존재해야 합니다. CNAME은 작동하지만 A 및 PTR 레코드가 정확하고 제자리에 있어야 합니다. 확인할 수 없는 호스트에 대한 오류 메시지는 직관적이지 않습니다: `Kerberos5 refuses authentication because Read req failed: Key table entry not found`.
* KDC의 클라이언트 역할을 하는 일부 운영 체제는 `ksu`에 대한 권한을 `root`로 설정하지 않습니다. 즉, `ksu`가 작동하지 않습니다. 이는 KDC 오류가 아니라 권한 문제입니다.
* MITKerberos에서 티켓 수명을 기본 수명인 10시간보다 길게 하려면 man:kadmin[8] 프롬프트에서 `modify_principal`을 사용하여 해당 주체(Principal)의 `maxlife`와 `krbtgt` 주체(Principal)의 `maxlife`를 모두 변경합니다. 이후 주체(Principal)는 `kinit -l`을 사용하여 더 긴 수명의 티켓을 요청할 수 있습니다.
* 워크스테이션에서 `kinit`을 실행하는 동안 문제 해결을 돕기 위해 KDC에서 패킷 스니퍼를 실행하면 비밀번호를 입력하기 전에도 티켓 부여 티켓(TGT)이 즉시 전송됩니다. 이는 Kerberos 서버가 승인되지 않은 요청에 대해 TGT를 자유롭게 전송하기 때문입니다. 그러나 모든 TGT는 사용자의 비밀번호에서 파생된 키로 암호화됩니다. 사용자가 비밀번호를 입력할 때, 비밀번호는 KDC로 전송되지 않고 대신 `kinit`이 이미 획득한 TGT를 해독하는 데 사용됩니다. 복호화 프로세스에서 유효한 타임스탬프가 있는 유효한 티켓이 생성되면 사용자는 유효한 Kerberos 자격 증명을 갖게 됩니다. 이러한 자격 증명에는 향후 Kerberos 서버와의 보안 통신을 설정하기 위한 세션 키와 Kerberos 서버의 자체 키로 암호화된 실제 TGT가 포함됩니다. 이 두 번째 암호화 계층을 통해 Kerberos 서버는 각 TGT의 진위 여부를 확인할 수 있습니다.
* 호스트 주체는 티켓 수명이 더 길 수 있습니다. 사용자 주체의 수명이 일주일이지만 연결 중인 호스트의 수명이 9시간인 경우에는 사용자 캐시에 만료된 호스트 주체가 있고 티켓 캐시가 예상대로 작동하지 않습니다.
* man:kadmind[8]에 설명된 대로 특이하게 잘못된 비밀번호가 사용되지 않도록 [.filename]#krb5.dict#를 설정할 때는 비밀번호 정책이 할당된 주체에만 적용된다는 점을 기억하세요. [.filename]#krb5.dict#에 사용되는 형식은 한 줄당 하나의 문자열입니다. [.filename]#/usr/share/dict/words#에 대한 심볼릭 링크를 만드는 것이 유용할 수 있습니다.

=== Kerberos 제한 완화하기

Kerberos는 All or Nothing 접근 방식이므로 네트워크에서 사용하도록 설정된 모든 서비스는 Kerberos와 함께 작동하도록 수정하거나 네트워크 공격으로부터 보안을 유지해야 합니다. 이는 사용자 자격 증명이 도용되어 재사용되는 것을 방지하기 위한 것입니다. 예를 들어 모든 원격 셸에서 Kerberos를 사용하도록 설정했지만 케르베로스화되지 않은 POP3 메일 서버가 일반 텍스트로 비밀번호를 전송하는 경우를 들 수 있습니다.

KDC는 단일 장애 지점입니다. 설계상 KDC는 마스터 비밀번호 데이터베이스만큼 안전해야 합니다. KDC는 다른 서비스가 전혀 실행되지 않아야 하며 물리적으로 안전해야 합니다. Kerberos는 모든 암호를 동일한 마스터 키로 암호화하여 KDC에 파일로 저장하기 때문에 위험성이 높습니다.

마스터 키 유출은 우려하는 것만큼 나쁘지 않습니다. 마스터 키는 Kerberos 데이터베이스를 암호화하기 위한 난수 생성기의 시드로만 사용됩니다. KDC에 대한 액세스가 안전한 한, 공격자는 마스터 키로 많은 일을 할 수 없습니다.

KDC를 사용할 수 없는 경우 인증을 수행할 수 없으므로 네트워크 서비스를 사용할 수 없습니다. 하나의 마스터 KDC와 하나 이상의 슬레이브를 사용하고 PAM을 사용하여 보조 인증 또는 폴백 인증을 신중하게 구현하면 이러한 문제를 완화할 수 있습니다.

Kerberos를 사용하면 사용자, 호스트 및 서비스가 서로 인증할 수 있습니다. 그러나 Keroberos는 사용자, 호스트 또는 서비스에 대해 KDC를 인증하는 메커니즘이 없습니다. 즉, 트로이 목마에 감염된 `kinit`은 모든 사용자 이름과 비밀번호를 기록할 수 있습니다. package:security/tripwire[] 같은 파일 시스템 무결성 검사 도구를 사용하면 이 문제를 완화할 수 있습니다.

=== 리소스 및 추가 정보

* http://www.faqs.org/faqs/Kerberos-faq/general/preamble.html[The Kerberos FAQ]
* http://web.mit.edu/Kerberos/www/dialogue.html[Designing an Authentication System: a Dialog in Four Scenes]
* https://www.ietf.org/rfc/rfc4120.txt[RFC 4120, The Kerberos Network Authentication Service (V5)]
* http://web.mit.edu/Kerberos/www/[MIT Kerberos home page]
* https://github.com/heimdal/heimdal/wiki[Heimdal Kerberos project wiki page]

[[openssl]]
== OpenSSL

OpenSSL은 SSL 및 TLS 프로토콜의 오픈 소스 구현입니다. 일반 통신 계층 위에 암호화 전송 계층을 제공하여 많은 네트워크 애플리케이션 및 서비스와 연동할 수 있습니다.

FreeBSD에 포함된 OpenSSL 버전은 전송 계층 보안 1.0/1.1/1.2/1.3(TLSv1/TLSv1.1/TLSv1.2/TLSv1.3) 네트워크 보안 프로토콜을 지원하며 일반 암호화 라이브러리로 사용할 수 있습니다.

OpenSSL은 메일 클라이언트의 인증을 암호화하고 신용카드 결제와 같은 웹 기반 거래를 보호하는 데 자주 사용됩니다. package:www/apache24[] 및 package:databases/postgresql11-server[] 등 일부 포트에는 OpenSSL로 빌드하기 위한 컴파일 옵션이 포함되어 있습니다. 이 옵션을 선택하면 포트가 기본 시스템에서 OpenSSL을 사용하여 지원을 추가합니다. 대신 package:security/openssl[] 포트에서 OpenSSL에 대해 컴파일하도록 하려면 [.filename]#/etc/make.conf#에 다음을 추가합니다:

[.programlisting]
....
DEFAULT_VERSIONS+= ssl=openssl
....

OpenSSL의 또 다른 일반적인 용도는 소프트웨어 애플리케이션에 사용할 인증서를 제공하는 것입니다. 인증서는 회사 또는 개인의 자격 증명을 확인하는 데 사용할 수 있습니다. 인증서가 http://www.verisign.com[http://www.verisign.com]와 같은 외부 CA(인증 기관)에 의해 서명되지 않은 경우, 인증서를 사용하는 애플리케이션에서 경고가 표시됩니다. 서명된 인증서를 받는 데는 비용이 들며, 인증서를 자체 서명할 수 있으므로 서명된 인증서를 사용하는 것이 필수는 아닙니다. 그러나 외부 기관을 사용하면 경고를 방지하고 사용자를 안심시킬 수 있습니다.

이 섹션에서는 FreeBSD 시스템에서 인증서를 만들고 사용하는 방법을 설명합니다. 자체 인증서에 서명하기 위한 CA를 만드는 방법의 예는 crossref:network-servers[ldap-config,”LDAP 서버 구성하기”]를 참조하세요.

SSL에 대한 자세한 내용은 무료 https://www.feistyduck.com/books/openssl-cookbook/[OpenSSL Cookbook]을 참조하세요.

=== 인증서 생성하기

외부 CA가 서명할 인증서를 생성하려면 다음 명령을 실행하고 프롬프트에서 요청하는 정보를 입력합니다. 이 입력 정보는 인증서에 기록됩니다. `Common Name` 프롬프트에서 인증서를 사용할 시스템의 정규화된 이름을 입력합니다. 이 이름이 서버와 일치하지 않으면 인증서를 확인하는 애플리케이션에서 사용자에게 경고를 발행하여 인증서가 제공한 확인을 쓸모없게 만듭니다.

[source, shell]
....
# openssl req -new -nodes -out req.pem -keyout cert.key -sha256 -newkey rsa:2048
Generating a 2048 bit RSA private key
..................+++
.............................................................+++
writing new private key to 'cert.key'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:US
State or Province Name (full name) [Some-State]:PA
Locality Name (e.g., city) []:Pittsburgh
Organization Name (e.g., company) [Internet Widgits Pty Ltd]:My Company
Organizational Unit Name (e.g., section) []:Systems Administrator
Common Name (e.g., YOUR name) []:localhost.example.org
Email Address []:trhodes@FreeBSD.org

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:Another Name
....

인증서를 만들 때 만료 시간 및 대체 암호화 알고리즘과 같은 다른 옵션을 사용할 수 있습니다. 옵션의 전체 목록은 man:openssl[1]에 설명되어 있습니다.

이 명령은 현재 디렉터리에 두 개의 파일을 만듭니다. 인증서 요청 파일인 [.filename]#req.pem#은 입력한 자격 증명의 유효성을 검사하고 요청에 서명하고 서명된 인증서를 반환하는 CA로 보낼 수 있습니다. 두 번째 파일인 [.filename]#cert.key#는 인증서의 개인 키이며 안전한 위치에 저장해야 합니다. 이 파일이 다른 사람에게 넘어가면 사용자나 서버를 사칭하는 데 사용될 수 있습니다.

또는 CA의 서명이 필요하지 않은 경우 자체 서명된 인증서를 만들 수 있습니다. 먼저 RSA 키를 생성합니다:

[source, shell]
....
# openssl genrsa -rand -genkey -out cert.key 2048
0 semi-random bytes loaded
Generating RSA private key, 2048 bit long modulus
.............................................+++
.................................................................................................................+++
e is 65537 (0x10001)
....

이 키를 사용하여 자체 서명 인증서를 만들 수 있습니다. 인증서를 만드는 일반적인 프롬프트를 따릅니다:

[source, shell]
....
# openssl req -new -x509 -days 365 -key cert.key -out cert.crt -sha256
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:US
State or Province Name (full name) [Some-State]:PA
Locality Name (e.g., city) []:Pittsburgh
Organization Name (e.g., company) [Internet Widgits Pty Ltd]:My Company
Organizational Unit Name (e.g., section) []:Systems Administrator
Common Name (e.g. server FQDN or YOUR name) []:localhost.example.org
Email Address []:trhodes@FreeBSD.org
....

그러면 현재 디렉터리에 두 개의 새 파일이 생성됩니다: 개인 키 파일 [.filename]#cert.key#와 인증서 자체 [.filename]#cert.crt#입니다. 이 파일은 `root`만 읽을 수 있는 디렉토리, 가급적 [.filename]#/etc/ssl/# 아래에 배치해야 합니다. 이 파일에는 `0700`의 권한이 적합하며 `chmod`를 사용하여 설정할 수 있습니다.

=== 인증서 사용하기

인증서의 용도중 한 가지는 일반 텍스트 인증의 사용을 방지하기 위해 Sendmail 메일 서버에 대한 연결을 암호화하는 것입니다.

[NOTE]
====
사용자가 인증서의 로컬 복사본을 설치하지 않은 경우 일부 메일 클라이언트에서 오류를 표시합니다. 인증서 설치에 대한 자세한 내용은 소프트웨어에 포함된 설명서를 참조하세요.
====

FreeBSD 10.0-RELEASE 이상에서는 Sendmail용 자체 서명 인증서를 자동으로 생성할 수 있습니다. 이 기능을 사용하려면 [.filename]#/etc/rc.conf#에 다음 줄을 추가하세요:

[.programlisting]
....
sendmail_enable="YES"
sendmail_cert_create="YES"
sendmail_cert_cn="localhost.example.org"
....

그러면 자체 서명 인증서인 [.filename]#/etc/mail/certs/host.cert#, 서명 키인 [.filename]#/etc/mail/certs/host.key# 및 CA 인증서인 [.filename]#/etc/mail/certs/cacert.pem#이 자동으로 만들어집니다. 인증서는 `sendmail_cert_cn`에 지정된 `Common Name`을 사용합니다. 편집 내용을 저장한 후 Sendmail을 다시 시작합니다:

[source, shell]
....
# service sendmail restart
....

모든 것이 정상적으로 진행되었다면 [.filename]#/var/log/maillog#에 오류 메시지가 표시되지 않을 것입니다. 간단한 테스트를 위해 `telnet`을 사용하여 메일 서버의 수신 포트에 연결합니다:

[source, shell]
....
# telnet example.com 25
Trying 192.0.34.166...
Connected to example.com.
Escape character is '^]'.
220 example.com ESMTP Sendmail 8.14.7/8.14.7; Fri, 18 Apr 2014 11:50:32 -0400 (EDT)
ehlo example.com
250-example.com Hello example.com [192.0.34.166], pleased to meet you
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-8BITMIME
250-SIZE
250-DSN
250-ETRN
250-AUTH LOGIN PLAIN
250-STARTTLS
250-DELIVERBY
250 HELP
quit
221 2.0.0 example.com closing connection
Connection closed by foreign host.
....

출력에 `STARTTLS` 줄이 나타나면 모든 것이 올바르게 작동하는 것입니다.

[[ipsec]]
== IPsec을 통한 VPN

인터넷 프로토콜 보안(IPsec)은 인터넷 프로토콜(IP) 계층 위에 있는 일련의 프로토콜입니다. 이 프로토콜은 통신 세션의 각 IP 패킷을 인증하고 암호화하여 두 개 이상의 호스트가 안전한 방식으로 통신할 수 있도록 합니다. FreeBSD IPsec 네트워크 스택은 http://www.kame.net/[http://www.kame.net/] 구현을 기반으로 하며 IPv4 및 IPv6 세션을 모두 지원합니다.

IPsec은 다음과 같은 하위 프로토콜로 구성됩니다:

* _Encapsulated Security Payload (ESP)_: 이 프로토콜은 Blowfish 및 3DES와 같은 대칭 암호화 알고리즘을 사용하여 내용을 암호화함으로써 제3자의 간섭으로부터 IP 패킷 데이터를 보호합니다.
* _Authentication Header (AH)_: 이 프로토콜은 암호화 체크섬을 계산하고 보안 해싱 기능으로 IP 패킷 헤더 필드를 해싱하여 제3자의 간섭 및 스푸핑으로부터 IP 패킷 헤더를 보호합니다. 그런 다음 해시가 포함된 추가 헤더를 추가하여 패킷의 정보를 인증할 수 있도록 합니다.
* _IP Payload Compression Protocol (IPComp_): 이 프로토콜은 전송되는 데이터 양을 줄이기 위해 IP 페이로드를 압축하여 통신 성능을 향상시키려고 합니다.

이러한 프로토콜은 환경에 따라 함께 사용하거나 개별적으로 사용할 수 있습니다.

IPsec은 두 가지 작동 모드를 지원합니다. 첫 번째 모드인 _Transport Mode_는 두 호스트 간의 통신을 보호합니다. 두 번째 모드인 _Tunnel Mode_는 일반적으로 가상 사설망(VPN)으로 알려진 가상 터널을 구축하는 데 사용됩니다. FreeBSD의 IPsec 서브시스템에 대한 자세한 정보는 man:ipsec[4]을 참고하세요.

IPsec 지원은 FreeBSD 11 이상에서 기본적으로 활성화되어 있습니다. 이전 버전의 FreeBSD의 경우 사용자 지정 커널 구성 파일에 이러한 옵션을 추가하고 crossref:kernelconfig[kernelconfig,FreeBSD 커널 구성하기]의 지침에 따라 커널을 다시 빌드하세요:

[source, shell]
....
options   IPSEC        IP security
device    crypto
....

IPsec 디버깅 지원을 원하는 경우 다음 커널 옵션도 추가해야 합니다:

[source, shell]
....
options   IPSEC_DEBUG  debug for IP security
....

이 장의 나머지 부분에서는 홈 네트워크와 회사 네트워크 간에 IPsecVPN을 설정하는 과정을 설명합니다. 예제 시나리오에서:

* 두 사이트 모두 FreeBSD를 실행하는 게이트웨이를 통해 인터넷에 연결됩니다.
* 각 네트워크의 게이트웨이에는 하나 이상의 외부 IP 주소가 있습니다. 이 예에서 회사 LAN의 외부 IP 주소는 `172.16.5.4`이고 홈 LAN의 외부 IP 주소는 `192.168.1.12`입니다.
* 두 네트워크의 내부 주소는 공용 또는 사설 IP 주소 중 하나를 사용할 수 있습니다. 그러나 주소 공간이 겹치지 않아야 합니다. 이 예에서 회사 LAN의 내부 IP 주소는 `10.246.38.1`이고 홈 LAN의 내부 IP 주소는 `10.0.0.5`입니다.

[.programlisting]
....
           corporate                          home
10.246.38.1/24 -- 172.16.5.4 <--> 192.168.1.12 -- 10.0.0.5/24
....

=== FreeBSD에서 VPN 구성하기

시작하려면, package:security/ipsec-tools[]를 포트 컬렉션에서 설치해야 합니다. 이 소프트웨어는 구성을 지원하는 여러 애플리케이션을 제공합니다.

다음 요구 사항은 패킷을 터널링하고 두 네트워크가 제대로 통신할 수 있도록 하는 데 사용되는 두 개의 man:gif[4] 의사 장치를 생성하는 것입니다. `root`로 각 게이트웨이에서 다음 명령을 실행합니다:

[source, shell]
....
corp-gw# ifconfig gif0 create
corp-gw# ifconfig gif0 10.246.38.1 10.0.0.5
corp-gw# ifconfig gif0 tunnel 172.16.5.4 192.168.1.12
....

[source, shell]
....
home-gw# ifconfig gif0 create
home-gw# ifconfig gif0 10.0.0.5 10.246.38.1
home-gw# ifconfig gif0 tunnel 192.168.1.12 172.16.5.4
....

`ifconfig gif0`을 사용하여 각 게이트웨이의 설정을 확인합니다. 다음은 홈 게이트웨이의 출력입니다:

[.programlisting]
....
gif0: flags=8051 mtu 1280
tunnel inet 172.16.5.4 --> 192.168.1.12
inet6 fe80::2e0:81ff:fe02:5881%gif0 prefixlen 64 scopeid 0x6
inet 10.246.38.1 --> 10.0.0.5 netmask 0xffffff00
....

다음은 회사 게이트웨이의 출력입니다:

[.programlisting]
....
gif0: flags=8051 mtu 1280
tunnel inet 192.168.1.12 --> 172.16.5.4
inet 10.0.0.5 --> 10.246.38.1 netmask 0xffffff00
inet6 fe80::250:bfff:fe3a:c1f%gif0 prefixlen 64 scopeid 0x4
....

완료되면 man:ping[8]을 사용하여 두 내부 IP 주소에 모두 연결할 수 있어야 합니다:

[source, shell]
....
home-gw# ping 10.0.0.5
PING 10.0.0.5 (10.0.0.5): 56 data bytes
64 bytes from 10.0.0.5: icmp_seq=0 ttl=64 time=42.786 ms
64 bytes from 10.0.0.5: icmp_seq=1 ttl=64 time=19.255 ms
64 bytes from 10.0.0.5: icmp_seq=2 ttl=64 time=20.440 ms
64 bytes from 10.0.0.5: icmp_seq=3 ttl=64 time=21.036 ms
--- 10.0.0.5 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 19.255/25.879/42.786/9.782 ms

corp-gw# ping 10.246.38.1
PING 10.246.38.1 (10.246.38.1): 56 data bytes
64 bytes from 10.246.38.1: icmp_seq=0 ttl=64 time=28.106 ms
64 bytes from 10.246.38.1: icmp_seq=1 ttl=64 time=42.917 ms
64 bytes from 10.246.38.1: icmp_seq=2 ttl=64 time=127.525 ms
64 bytes from 10.246.38.1: icmp_seq=3 ttl=64 time=119.896 ms
64 bytes from 10.246.38.1: icmp_seq=4 ttl=64 time=154.524 ms
--- 10.246.38.1 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max/stddev = 28.106/94.594/154.524/49.814 ms
....

예상대로 양쪽 모두 비공개로 구성된 주소에서 ICMP 패킷을 보내고 받을 수 있습니다. 다음으로, 각 게이트웨이 뒤에 있는 네트워크에서 트래픽을 올바르게 보내려면 두 게이트웨이에 패킷 라우팅 방법을 알려야 합니다. 다음 명령으로 이 목표를 달성할 수 있습니다:

[source, shell]
....
corp-gw# route add 10.0.0.0 10.0.0.5 255.255.255.0
corp-gw# route add net 10.0.0.0: gateway 10.0.0.5
home-gw# route add 10.246.38.0 10.246.38.1 255.255.255.0
home-gw# route add host 10.246.38.0: gateway 10.246.38.1
....

각 게이트웨이와 게이트웨이 뒤에 있는 머신에서 내부 머신에 연결할 수 있어야 합니다. 다시 man:ping[8]을 사용하여 확인합니다:

[source, shell]
....
corp-gw# ping -c 3 10.0.0.8
PING 10.0.0.8 (10.0.0.8): 56 data bytes
64 bytes from 10.0.0.8: icmp_seq=0 ttl=63 time=92.391 ms
64 bytes from 10.0.0.8: icmp_seq=1 ttl=63 time=21.870 ms
64 bytes from 10.0.0.8: icmp_seq=2 ttl=63 time=198.022 ms
--- 10.0.0.8 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 21.870/101.846/198.022/74.001 ms

home-gw# ping -c 3 10.246.38.107
PING 10.246.38.1 (10.246.38.107): 56 data bytes
64 bytes from 10.246.38.107: icmp_seq=0 ttl=64 time=53.491 ms
64 bytes from 10.246.38.107: icmp_seq=1 ttl=64 time=23.395 ms
64 bytes from 10.246.38.107: icmp_seq=2 ttl=64 time=23.865 ms
--- 10.246.38.107 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 21.145/31.721/53.491/12.179 ms
....

이 시점에서 트래픽은 암호화되지 않은 채 gif 터널로 캡슐화된 네트워크 간에 흐릅니다. 다음으로, IPSec을 사용하여 PSK(사전 공유 키)를 사용하여 트래픽을 암호화합니다. IP 주소를 제외하고 두 게이트웨이의 [.filename]#/usr/local/etc/racoon/racoon.conf#는 동일하며 다음과 비슷하게 보입니다:

[.programlisting]
....
path    pre_shared_key  "/usr/local/etc/racoon/psk.txt"; #location of pre-shared key file
log     debug;	#log verbosity setting: set to 'notify' when testing and debugging is complete

padding	# options are not to be changed
{
        maximum_length  20;
        randomize       off;
        strict_check    off;
        exclusive_tail  off;
}

timer	# timing options. change as needed
{
        counter         5;
        interval        20 sec;
        persend         1;
#       natt_keepalive  15 sec;
        phase1          30 sec;
        phase2          15 sec;
}

listen	# address [port] that racoon will listen on
{
        isakmp          172.16.5.4 [500];
        isakmp_natt     172.16.5.4 [4500];
}

remote  192.168.1.12 [500]
{
        exchange_mode   main,aggressive;
        doi             ipsec_doi;
        situation       identity_only;
        my_identifier   address 172.16.5.4;
        peers_identifier        address 192.168.1.12;
        lifetime        time 8 hour;
        passive         off;
        proposal_check  obey;
#       nat_traversal   off;
        generate_policy off;

                        proposal {
                                encryption_algorithm    blowfish;
                                hash_algorithm          md5;
                                authentication_method   pre_shared_key;
                                lifetime time           30 sec;
                                dh_group                1;
                        }
}

sainfo  (address 10.246.38.0/24 any address 10.0.0.0/24 any)	# address $network/$netmask $type address $network/$netmask $type ( $type being any or esp)
{								# $network must be the two internal networks you are joining.
        pfs_group       1;
        lifetime        time    36000 sec;
        encryption_algorithm    blowfish,3des;
        authentication_algorithm        hmac_md5,hmac_sha1;
        compression_algorithm   deflate;
}
....

사용 가능한 각 옵션에 대한 설명은 [.filename]#racoon.conf#의 설명서 페이지를 참조하세요.

FreeBSD와 Racoon이 호스트 간의 네트워크 트래픽을 암호화하고 해독할 수 있도록 보안 정책 데이터베이스(Security Policy Database, SPD)를 구성해야 합니다.

이는 회사 게이트웨이에서 다음과 유사한 셸 스크립트를 사용하여 수행할 수 있습니다. 이 파일은 시스템 초기화 중에 사용되며 [.filename]#/usr/local/etc/racoon/setkey.conf#로 저장해야 합니다.

[.programlisting]
....
flush;
spdflush;
# To the home network
spdadd 10.246.38.0/24 10.0.0.0/24 any -P out ipsec esp/tunnel/172.16.5.4-192.168.1.12/use;
spdadd 10.0.0.0/24 10.246.38.0/24 any -P in ipsec esp/tunnel/192.168.1.12-172.16.5.4/use;
....

설치가 완료되면 다음 명령을 사용하여 두 게이트웨이 모두에서 Racoon을 시작할 수 있습니다:

[source, shell]
....
# /usr/local/sbin/racoon -F -f /usr/local/etc/racoon/racoon.conf -l /var/log/racoon.log
....

출력은 다음과 비슷해야 합니다:

[source, shell]
....
corp-gw# /usr/local/sbin/racoon -F -f /usr/local/etc/racoon/racoon.conf
Foreground mode.
2006-01-30 01:35:47: INFO: begin Identity Protection mode.
2006-01-30 01:35:48: INFO: received Vendor ID: KAME/racoon
2006-01-30 01:35:55: INFO: received Vendor ID: KAME/racoon
2006-01-30 01:36:04: INFO: ISAKMP-SA established 172.16.5.4[500]-192.168.1.12[500] spi:623b9b3bd2492452:7deab82d54ff704a
2006-01-30 01:36:05: INFO: initiate new phase 2 negotiation: 172.16.5.4[0]192.168.1.12[0]
2006-01-30 01:36:09: INFO: IPsec-SA established: ESP/Tunnel 192.168.1.12[0]->172.16.5.4[0] spi=28496098(0x1b2d0e2)
2006-01-30 01:36:09: INFO: IPsec-SA established: ESP/Tunnel 172.16.5.4[0]->192.168.1.12[0] spi=47784998(0x2d92426)
2006-01-30 01:36:13: INFO: respond new phase 2 negotiation: 172.16.5.4[0]192.168.1.12[0]
2006-01-30 01:36:18: INFO: IPsec-SA established: ESP/Tunnel 192.168.1.12[0]->172.16.5.4[0] spi=124397467(0x76a279b)
2006-01-30 01:36:18: INFO: IPsec-SA established: ESP/Tunnel 172.16.5.4[0]->192.168.1.12[0] spi=175852902(0xa7b4d66)
....

터널이 제대로 작동하는지 확인하려면 다른 콘솔로 전환하고 man:tcpdump[1]를 사용하여 다음 명령을 사용하여 네트워크 트래픽을 확인합니다. 필요에 따라 `em0`을 네트워크 인터페이스 카드로 바꿉니다:

[source, shell]
....
corp-gw# tcpdump -i em0 host 172.16.5.4 and dst 192.168.1.12
....

콘솔에 다음과 유사한 데이터가 표시되어야 합니다. 그렇지 않은 경우 문제가 있는 것이므로 반환된 데이터를 디버깅해야 합니다.

[.programlisting]
....
01:47:32.021683 IP corporatenetwork.com > 192.168.1.12.privatenetwork.com: ESP(spi=0x02acbf9f,seq=0xa)
01:47:33.022442 IP corporatenetwork.com > 192.168.1.12.privatenetwork.com: ESP(spi=0x02acbf9f,seq=0xb)
01:47:34.024218 IP corporatenetwork.com > 192.168.1.12.privatenetwork.com: ESP(spi=0x02acbf9f,seq=0xc)
....

이 시점에서 두 네트워크 모두 사용할 수 있어야 하며 동일한 네트워크의 일부인 것처럼 보입니다. 두 네트워크 모두 방화벽으로 보호되어 있을 가능성이 높습니다. 두 네트워크 간에 트래픽이 흐르도록 허용하려면 패킷을 통과시키는 규칙을 추가해야 합니다. man:ipfw[8] 방화벽의 경우 방화벽 구성 파일에 다음 줄을 추가합니다:

[.programlisting]
....
ipfw add 00201 allow log esp from any to any
ipfw add 00202 allow log ah from any to any
ipfw add 00203 allow log ipencap from any to any
ipfw add 00204 allow log udp from any 500 to any
....

[NOTE]
====
현재 호스트 구성에 따라 규칙 번호를 변경해야 할 수도 있습니다.
====

man:pf[4] 또는 man:ipf[8] 사용자의 경우 다음 규칙이 도움이 될 것입니다:

[.programlisting]
....
pass in quick proto esp from any to any
pass in quick proto ah from any to any
pass in quick proto ipencap from any to any
pass in quick proto udp from any port = 500 to any port = 500
pass in quick on gif0 from any to any
pass out quick proto esp from any to any
pass out quick proto ah from any to any
pass out quick proto ipencap from any to any
pass out quick proto udp from any port = 500 to any port = 500
pass out quick on gif0 from any to any
....

마지막으로, 시스템 초기화 중에 컴퓨터가 VPN 지원을 시작하도록 하려면 [.filename]#/etc/rc.conf#에 다음 줄을 추가하세요:

[.programlisting]
....
ipsec_enable="YES"
ipsec_program="/usr/local/sbin/setkey"
ipsec_file="/usr/local/etc/racoon/setkey.conf" # allows setting up spd policies on boot
racoon_enable="yes"
....

[[openssh]]
== OpenSSH

OpenSSH는 원격 머신에 대한 보안 액세스를 제공하는 데 사용되는 네트워크 연결 도구 세트입니다. 또한, TCP/IP 연결은 SSH 연결을 통해 안전하게 터널링하거나 전달할 수 있습니다. OpenSSH는 모든 트래픽을 암호화하여 도청, 연결 하이재킹 및 기타 네트워크 수준 공격을 효과적으로 제거합니다.

OpenSSH는 OpenBSD 프로젝트에서 유지 관리하며 FreeBSD에 기본적으로 설치됩니다.

데이터가 암호화되지 않은 형태로 네트워크를 통해 전송되면 클라이언트와 서버 사이에 있는 네트워크 스니퍼가 세션 중에 전송된 사용자/비밀번호 정보나 데이터를 훔칠 수 있습니다. OpenSSH는 이를 방지하기 위해 다양한 인증 및 암호화 방법을 제공합니다. OpenSSH에 대한 자세한 정보는 http://www.openssh.com/[http://www.openssh.com/]에서 확인할 수 있습니다.

이 섹션에서는 다른 시스템에 안전하게 액세스하고 FreeBSD 시스템에서 파일을 안전하게 전송하기 위한 내장 클라이언트 유틸리티에 대한 개요를 제공합니다. 그런 다음 FreeBSD 시스템에서 SSH 서버를 구성하는 방법을 설명합니다. 자세한 내용은 이 장에 언급된 매뉴얼 페이지에서 확인할 수 있습니다.

=== SSH 클라이언트 유틸리티 사용하기

SSH 서버에 로그인하려면 `ssh`를 사용하여 해당 서버에 존재하는 사용자 아이디와 서버의 IP 주소 또는 호스트명을 지정합니다. 지정한 서버에 처음 연결하는 경우 먼저 서버의 지문을 확인하라는 메시지가 표시됩니다:

[source, shell]
....
# ssh user@example.com
The authenticity of host 'example.com (10.0.0.1)' can't be established.
ECDSA key fingerprint is 25:cc:73:b5:b3:96:75:3d:56:19:49:d2:5c:1f:91:3b.
Are you sure you want to continue connecting (yes/no)? yes
Permanently added 'example.com' (ECDSA) to the list of known hosts.
Password for user@example.com: user_password
....

SSH는 키 지문 시스템을 사용하여 클라이언트가 연결할 때 서버의 진위 여부를 확인합니다. 사용자가 처음 연결할 때 `yes`를 입력하여 키 지문을 수락하면 키의 사본이 사용자의 홈 디렉터리에 있는 [.filename]#.ssh/known_hosts#에 저장됩니다. 향후 로그인 시도는 저장된 키와 비교하여 확인되며 서버의 키가 저장된 키와 일치하지 않으면 `ssh`에서 경고를 표시합니다. 이 경우 사용자는 연결을 계속하기 전에 먼저 키가 변경된 이유를 확인해야 합니다.

최신 버전의 OpenSSH는 SSHv2 연결만 허용합니다. SSH 프로토콜 버전 1은 더 이상 사용되지 않습니다.

man:scp[1]을 사용하여 원격 시스템으로 또는 원격 시스템에서 파일을 안전하게 복사합니다. 이 예에서는 원격 시스템의 [.filename]#COPYRIGHT#을 로컬 시스템의 현재 디렉터리에 있는 같은 이름의 파일로 복사합니다:

[source, shell]
....
# scp user@example.com:/COPYRIGHT COPYRIGHT
Password for user@example.com: *******
COPYRIGHT            100% |*****************************|  4735
00:00
#
....

이 호스트에 대해 이미 지문이 확인되었으므로 사용자의 비밀번호를 묻기 전에 서버의 키가 자동으로 확인됩니다.

`scp`에 전달되는 인수는 `cp`와 유사합니다. 복사할 파일은 첫 번째 인수이고 복사할 대상은 두 번째 인수입니다. 파일은 네트워크를 통해 가져오기 때문에 하나 이상의 파일 인수는 `사용자@호스트:<원격_파일_경로>` 형식을 취합니다. 디렉터리를 재귀적으로 복사할 때 `scp`는 `-r`을 사용하는 반면, `cp`는 `-R`을 사용한다는 점에 유의하세요.

파일 복사를 위한 대화형 세션을 열려면 `sftp`를 사용합니다. `sftp` 세션에서 사용할 수 있는 명령어 목록은 man:sftp[1]을 참조하세요.

[[security-ssh-keygen]]
==== 키 기반 인증

암호를 사용하는 대신 키를 사용하여 원격 컴퓨터에 연결하도록 클라이언트를 구성할 수 있습니다. RSA 인증 키를 생성하려면 `ssh-keygen`을 사용합니다. 공개 키와 개인 키 쌍을 생성하려면 키 유형을 지정하고 지시에 따릅니다. 기억하기 쉽지만 추측하기 어려운 암호 구문으로 키를 보호하는 것이 좋습니다.

[source, shell]
....
% ssh-keygen -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (/home/user/.ssh/id_rsa):
Enter passphrase (empty for no passphrase):  <.>
Enter same passphrase again:                 <.>
Your identification has been saved in /home/user/.ssh/id_rsa.
Your public key has been saved in /home/user/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:54Xm9Uvtv6H4NOo6yjP/YCfODryvUU7yWHzMqeXwhq8 user@host.example.com
The key's randomart image is:
+---[RSA 2048]----+
|                 |
|                 |
|                 |
|        . o..    |
|       .S*+*o    |
|      . O=Oo . . |
|       = Oo= oo..|
|      .oB.* +.oo.|
|       =OE**.o..=|
+----[SHA256]-----+
....

<.> 여기에 비밀번호를 입력합니다. 공백과 기호를 포함할 수 있습니다.
<.> 비밀번호를 다시 입력하여 확인합니다.

개인 키는 [.filename]#~/.ssh/id_rsa#에 저장되고 공개 키는 [.filename]#~/.ssh/id_rsa.pub#에 저장됩니다. 공개 키는 원격 컴퓨터의 [.filename]#~/.ssh/authorized_keys#에 복사해야 키 기반 인증이 작동합니다.

[WARNING]
====
많은 사용자가 키가 설계상 안전하다고 믿고 비밀번호 없이 키를 사용합니다. 이는 _위험한_ 행동입니다. 관리자는 개인키를 수동으로 확인하여 키 쌍이 암호문으로 보호되는지 확인할 수 있습니다. 개인키 파일에 `ENCRYPTED`라는 단어가 포함되어 있으면 키 소유자가 암호 구문을 사용하고 있는 것입니다. 또한 최종 사용자를 더 안전하게 보호하기 위해 공개 키 파일에 `from`을 넣을 수 있습니다. 예를 들어, `ssh-rsa` 접두사 앞에 `from=“192.168.10.5”`를 추가하면 특정 사용자만 해당 IP 주소에서 로그인할 수 있습니다.
====

옵션과 파일은 OpenSSH 버전에 따라 다릅니다. 문제를 방지하려면 man:ssh-keygen[1]을 참조하세요.

암호 구문을 사용하는 경우 서버에 연결할 때마다 사용자에게 암호 구문을 묻는 메시지가 표시됩니다. SSH 키를 메모리에 로드하여 매번 암호를 입력할 필요가 없도록 하려면 man:ssh-agent[1] 및 man:ssh-add[1]를 사용하세요.

인증은 로드된 개인 키를 사용하여 `ssh-agent`에 의해 처리됩니다. `ssh-agent`는 셸이나 창 관리자와 같은 다른 애플리케이션을 시작하는 데 사용할 수 있습니다.

셸에서 `ssh-agent`를 사용하려면 셸을 인수로 사용하여 시작합니다. `ssh-add`를 실행하고 개인 키의 암호를 입력하여 ID를 추가합니다. 그러면 사용자는 해당 공개 키가 설치된 모든 호스트에 `ssh`할 수 있습니다. 예를 들어:

[source, shell]
....
% ssh-agent csh
% ssh-add
Enter passphrase for key '/usr/home/user/.ssh/id_rsa':  <.>
Identity added: /usr/home/user/.ssh/id_rsa (/usr/home/user/.ssh/id_rsa)
%
....

<.> 키의 비밀번호를 입력합니다.

Xorg에서 `ssh-agent`를 사용하려면 [.filename]#~/.xinitrc#에 해당 항목을 추가합니다. 이렇게 하면 Xorg에서 실행되는 모든 프로그램에 `ssh-agent` 서비스가 제공됩니다. 예제 [.filename]#~/.xinitrc#은 다음과 같습니다:

[.programlisting]
....
exec ssh-agent startxfce4
....

이렇게 하면 Xorg가 시작될 때마다 `ssh-agent`가 실행되고, 이는 다시 XFCE를 시작합니다. 변경 사항을 적용할 수 있도록 Xorg를 재시작한 후, `ssh-add`를 실행하여 모든 SSH 키를 로드합니다.

[[security-ssh-tunneling]]
==== SSH 터널링

OpenSSH는 터널을 생성하여 암호화된 세션에서 다른 프로토콜을 캡슐화할 수 있습니다.

다음 명령은 `ssh`에게 텔넷용 터널을 생성하도록 지시합니다:

[source, shell]
....
% ssh -N -f -L 5023:localhost:23 user@foo.example.com
%
....

이 예에서는 다음 옵션을 사용합니다:

`-N`::
명령이 없거나 터널만 있음을 나타냅니다. 생략하면 `ssh`가 일반 세션을 시작합니다.

`-f`::
`ssh`가 백그라운드에서 실행되도록 강제합니다.

`-L`::
_localport:remotehost:remoteport_ 형식의 로컬 터널을 나타냅니다.

`user@foo.example.com`::
지정된 원격 SSH 서버에서 사용할 로그인 이름입니다.

SSH 터널은 지정된 `localport`의 `localhost`에 수신 대기 소켓을 생성하는 방식으로 작동합니다. 그런 다음 SSH 연결을 통해 `localport`에서 수신된 모든 연결을 지정된 `remotehost:remoteport`로 전달합니다. 이 예제에서는 클라이언트의 `5023` 포트가 원격 컴퓨터의 `23` 포트로 전달됩니다. 포트 23은 텔넷에서 사용되므로 SSH 터널을 통해 암호화된 텔넷 세션이 생성됩니다.

이 방법은 다음 예제에서 볼 수 있듯이 SMTP, POP3, FTP 등 안전하지 않은 TCP 프로토콜을 얼마든지 래핑하는 데 사용할 수 있습니다.

.SMTP용 보안 터널 만들기
[example]
====

[source, shell]
....
% ssh -N -f -L 5025:localhost:25 user@mailserver.example.com
user@mailserver.example.com's password: *****
% telnet localhost 5025
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 mailserver.example.com ESMTP
....
`ssh-keygen` 및 추가 사용자 계정과 함께 사용하여 보다 원활한 SSH 터널링 환경을 만들 수 있습니다. 비밀번호를 입력하는 대신 키를 사용할 수 있으며, 터널을 별도의 사용자로 실행할 수 있습니다.
====

.POP3 서버의 보안 액세스
[example]
====
이 예제에서는 외부로부터의 연결을 허용하는 SSH 서버가 있습니다. 같은 네트워크에 POP3 서버를 실행하는 메일 서버가 있습니다. 안전한 방식으로 이메일을 확인하려면 SSH 서버에 대한 SSH 연결을 만들고 메일 서버로 터널링합니다:

[source, shell]
....
% ssh -N -f -L 2110:mail.example.com:110 user@ssh-server.example.com
user@ssh-server.example.com's password: ******
....

터널이 실행되면 이메일 클라이언트에서 포트 2110의 `localhost`로 POP3 요청을 보내도록 지정합니다. 이 연결은 터널을 통해 `mail.example.com`으로 안전하게 전달됩니다.
====

.방화벽 우회하기
[example]
====
일부 방화벽은 들어오는 연결과 나가는 연결을 모두 필터링합니다. 예를 들어, 방화벽은 원격 컴퓨터에서 22번과 80번 포트로의 액세스를 제한하여 SSH와 웹 서핑만 허용할 수 있습니다. 이렇게 하면 22번이나 80번 이외의 포트를 사용하는 다른 서비스에 대한 액세스가 차단됩니다.

해결책은 네트워크 방화벽 외부의 머신에 SSH 연결을 생성하고 이를 사용하여 원하는 서비스로 터널링하는 것입니다:

[source, shell]
....
% ssh -N -f -L 8888:music.example.com:8000 user@unfirewalled-system.example.org
user@unfirewalled-system.example.org's password: *******
....

이 예제에서는 이제 스트리밍 Ogg Vorbis 클라이언트가 `localhost` 포트 8888을 가리키면 포트 8000의 `music.example.com`으로 전달되어 방화벽을 성공적으로 우회할 수 있습니다.
====

=== SSH 서버 활성화하기

FreeBSD 시스템은 내장된 SSH 클라이언트 유틸리티를 제공할 뿐만 아니라, 다른 SSH 클라이언트로부터의 연결을 수락하여 SSH 서버로 구성할 수 있습니다.

sshd가 작동 중인지 확인하려면 man:service[8] 명령을 사용합니다:

[source, shell]
....
# service sshd status
....

서비스가 실행 중이 아닌 경우 [.filename]#/etc/rc.conf#에 다음 줄을 추가합니다.

[.programlisting]
....
sshd_enable="YES"
....

그러면 다음 번에 시스템이 부팅될 때 OpenSSH용 데몬 프로그램인 sshd가 시작됩니다. 지금 시작하려면:

[source, shell]
....
# service sshd start
....

FreeBSD 시스템에서 sshd를 처음 시작하면 시스템의 호스트 키가 자동으로 생성되고 콘솔에 지문이 표시됩니다. 사용자가 서버에 처음 연결할 때 지문을 확인할 수 있도록 사용자에게 지문을 제공하세요.

sshd를 시작할 때 사용할 수 있는 옵션 목록과 인증, 로그인 프로세스 및 다양한 구성 파일에 대한 자세한 설명은 man:sshd[8]을 참조하세요.

이 시점에서 시스템에서 사용자 이름과 비밀번호를 가진 모든 사용자가 sshd를 사용할 수 있어야 합니다.

=== SSH 서버 보안

sshd는 FreeBSD에서 가장 널리 사용되는 원격 관리 기능이지만, 무차별 대입 및 드라이브 바이 공격은 공용 네트워크에 노출된 모든 시스템에서 흔히 발생합니다. 이러한 공격의 성공을 막기 위해 몇 가지 추가 매개변수를 사용할 수 있으며 이에대해 이번 섹션에서 설명합니다.

OpenSSH 서버 구성 파일에서 `AllowUsers` 키워드를 사용하여 SSH 서버에 로그인할 수 있는 사용자와 로그인 위치를 제한하는 것이 좋습니다. 예를 들어 ‘root’만 `192.168.1.32`에서 로그인할 수 있도록 허용하려면 [.filename]#/etc/ssh/sshd_config#에 이 줄을 추가합니다:

[.programlisting]
....
AllowUsers root@192.168.1.32
....

`admin`이 어디서든 로그인할 수 있도록 하려면 IP 주소를 지정하지 않고 해당 사용자를 나열합니다:

[.programlisting]
....
AllowUsers admin
....

다음과 같이 여러 사용자가 같은 줄에 나열되어야 합니다:

[.programlisting]
....
AllowUsers root@192.168.1.32 admin
....

[.filename]#/etc/ssh/sshd_config#을 변경한 후 sshd를 실행하여 구성 파일을 다시 로드하도록 지시합니다:

[source, shell]
....
# service sshd reload
....

[NOTE]
====
이 키워드를 사용할 때는 컴퓨터에 로그인해야 하는 각 사용자를 나열하는 것이 중요합니다. 해당 줄에 지정되지 않은 사용자는 모두 잠깁니다. 또한 OpenSSH 서버 구성 파일에 사용되는 키워드는 대소문자를 구분합니다. 키워드의 철자가 대소문자를 포함하여 올바르지 않으면 무시됩니다. 항상 이 파일의 변경 사항을 테스트하여 편집 내용이 예상대로 작동하는지 확인하세요. 사용 가능한 키워드의 철자와 사용법을 확인하려면 man:sshd_config[5]를 참조하세요.
====

또한 사용자는 공개 키와 개인 키를 사용하여 2단계 인증을 사용해야 할 수도 있습니다. 필요한 경우 사용자는 man:ssh-keygen[1]을 사용하여 키 쌍을 생성하고 관리자에게 공개 키를 보낼 수 있습니다. 이 키 파일은 위의 클라이언트 섹션에서 설명한 대로 [.filename]#authorized_keys#에 배치됩니다. 사용자가 키만 사용하도록 하려면 다음 옵션을 구성할 수 있습니다:

[.programlisting]
....
AuthenticationMethods publickey
....

[TIP]
====

[.filename]#/etc/ssh/sshd_config#과 [.filename]#/etc/ssh/ssh_config#을 혼동하지 마세요(첫 번째 파일명에서 `d`가 추가됨을 주의하세요). 첫 번째 파일은 서버를 구성하고 두 번째 파일은 클라이언트를 구성합니다. 사용 가능한 클라이언트 설정 목록은 man:ssh_config[5]를 참조하세요.
====

[[fs-acl]]
== 액세스 제어 목록

ACL(액세스 제어 목록, Access Control Lists)은 표준 UNIX(R) 권한 모델을 POSIX(R).1e와 호환되는 방식으로 확장합니다. 이를 통해 관리자는 보다 세분화된 권한 모델을 활용할 수 있습니다.

FreeBSD [.filename]#GENERIC# 커널은 UFS 파일 시스템에 대한 ACL 지원을 제공합니다. 사용자 정의 커널을 컴파일하려는 사용자는 사용자 정의 커널 구성 파일에 다음 옵션을 포함해야 합니다:

[.programlisting]
....
options UFS_ACL
....

이 옵션이 컴파일되어 있지 않으면 ACL을 지원하는 파일 시스템을 마운트하려고 할 때 경고 메시지가 표시됩니다. ACL은 UFS2에서 기본적으로 지원되는 확장 속성에 의존합니다.

이 장에서는 ACL 지원을 사용 설정하는 방법과 몇 가지 사용 예제를 설명합니다.

=== ACL 지원 활성화하기

ACL은 마운트 시간 관리 플래그(mount-time administrative flag)인 `acls`에 의해 활성화되며, 이 플래그는 [.filename]#/etc/fstab#에 추가할 수 있습니다. 마운트-시간 플래그는 파일 시스템 헤더의 슈퍼블록 ACL 플래그를 수정하는 man:tunefs[8]를 사용하여 영구적인 방식으로 자동으로 설정할 수도 있습니다. 일반적으로 여러 가지 이유로 슈퍼블록 플래그를 사용하는 것이 바람직합니다:

* 슈퍼블록 플래그는 완전한 ‘마운트’와 새로운 ‘마운트’가 필요하므로 ‘mount -u’를 사용한 재마운트로(remount)는 변경할 수 없습니다. 즉, 부팅 후 루트 파일 시스템에서 ACL을 사용할 수 없습니다. 또한 시스템이 사용 중일 때는 파일 시스템의 ACL 지원을 변경할 수 없다는 의미이기도 합니다.
* 슈퍼블록 플래그를 설정하면 [.filename]#fstab# 항목이 없거나 장치 순서가 바뀌더라도 파일 시스템이 항상 ACL이 활성화된 상태로 마운트됩니다. 이렇게 하면 ACL이 지원되지 않는 파일 시스템이 실수로 마운트되는 것을 방지할 수 있습니다.

[NOTE]
====
ACL을 사용하도록 설정했다가 비활성화했다가 확장 속성을 플러시하지 않고 다시 사용하도록 설정하면 불쾌한 일이 발생할 수 있으므로 ACL을 사용하지 않고 마운트하지 않는 것이 바람직합니다. 일반적으로 파일 시스템에서 ACL을 사용하도록 설정하면 그 결과 파일 보호가 시스템 사용자가 의도한 것과 호환되지 않을 수 있으며, ACL을 다시 사용하도록 설정하면 권한이 변경된 파일에 이전 ACL이 다시 적용되어 예측할 수 없는 동작이 발생할 수 있으므로 비활성화 시켜서는 안 됩니다.
====

ACL이 활성화된 파일 시스템에는 권한 설정에 더하기(`+`) 기호가 표시됩니다:

[.programlisting]
....
drwx------  2 robert  robert  512 Dec 27 11:54 private
drwxrwx---+ 2 robert  robert  512 Dec 23 10:57 directory1
drwxrwx---+ 2 robert  robert  512 Dec 22 10:20 directory2
drwxrwx---+ 2 robert  robert  512 Dec 27 11:57 directory3
drwxr-xr-x  2 robert  robert  512 Nov 10 11:54 public_html
....

이 예제에서 [.filename]#directory1#, [.filename]#directory2#, [.filename]#directory3#은 모두 ACL을 활용하고 있지만 [.filename]#private#과 [.filename]#public_html#은 활용하지 않습니다.

=== ACL 사용하기

파일 시스템 ACL은 `getfacl`을 사용하여 볼 수 있습니다. 예를 들어, [.filename]#test#의 ACL 설정을 보려면:

[source, shell]
....
% getfacl test
	#file:test
	#owner:1001
	#group:1001
	user::rw-
	group::r--
	other::r--
....

이 파일에 대한 ACL 설정을 변경하려면 `setfacl`을 사용합니다. 파일 또는 파일 시스템에서 현재 정의된 모든 ACL을 제거하려면 `-k`를 포함합니다. 그러나 `-b`를 사용하면 ACL이 작동하는 데 필요한 기본 필드는 그대로 유지되므로 권장되는 방법입니다.

[source, shell]
....
% setfacl -k test
....

기본 ACL 항목을 수정하려면 `-m`을 사용합니다:

[source, shell]
....
% setfacl -m u:trhodes:rwx,group:web:r--,o::--- test
....

이 예에서는 이전 명령에 의해 제거되었으므로 사전 정의된 항목이 없습니다. 이 명령은 기본 옵션을 복원하고 나열된 옵션을 할당합니다. 시스템에 존재하지 않는 사용자 또는 그룹을 추가하면 `Invalid argument` 오류가 표시됩니다.

이러한 명령에 사용할 수 있는 옵션에 대한 자세한 내용은 man:getfacl[1] 및 man:setfacl[1]을 참조하세요.

[[security-pkg]]
== 타사 보안 문제 모니터링

최근 몇 년 동안 보안 업계에서는 취약성 평가 처리 방식을 많이 개선했습니다. 현재 사용 가능한 거의 모든 운영 체제에 대해 타사 유틸리티가 설치 및 구성됨에 따라 시스템 침입의 위협이 증가하고 있습니다.

취약성 평가는 보안의 핵심 요소입니다. FreeBSD는 기본 시스템에 대한 권고사항을 발표하지만, 모든 타사 유틸리티에 대한 권고사항을 발표하는 것은 FreeBSD 프로젝트의 역량을 넘어서는 일입니다. 타사 취약성을 완화하고 관리자에게 알려진 보안 문제를 경고하는 방법이 있습니다. pkg로 알려진 FreeBSD 애드온 유틸리티에는 이러한 목적을 위한 옵션이 명시적으로 포함되어 있습니다.

pkg는 데이터베이스에서 보안 문제를 조사합니다. 데이터베이스는 FreeBSD 보안 팀과 포트 개발자가 업데이트하고 유지 관리합니다.

pkg 설치에 대한 자세한 내용은 crossref:ports[pkgng-intro,instructions]을 참조하세요.

설치는 pkg 감사 데이터베이스를 유지 관리하기 위한 man:periodic[8] 구성 파일을 제공하며, 이를 업데이트하는 프로그래밍 방법을 제공합니다. 이 기능은 man:periodic.conf[5]에서 `daily_status_security_pkgaudit_enable`을 `YES`로 설정하면 활성화됩니다. ``root``의 이메일 계정으로 전송되는 일일 보안 실행 이메일이 읽히고 있는지 확인합니다.

설치 후 언제든지 포트 컬렉션의 일부로 타사 유틸리티를 감사하기 위해 관리자는 데이터베이스를 업데이트하고 설치된 패키지의 알려진 취약성을 확인하도록 선택할 수 있습니다:

[source, shell]
....
# pkg audit -F
....

pkg는 설치된 패키지에 게시된 모든 취약점을 메시지로 표시합니다:

[.programlisting]
....
Affected package: cups-base-1.1.22.0_1
Type of problem: cups-base -- HPGL buffer overflow vulnerability.
Reference: <https://www.FreeBSD.org/ports/portaudit/40a3bca2-6809-11d9-a9e7-0001020eed82.html>

1 problem(s) in your installed packages found.

You are advised to update or deinstall the affected package(s) immediately.
....

관리자는 웹 브라우저로 표시된 URL을 가리키면 해당 취약점에 대한 자세한 정보를 얻을 수 있습니다. 여기에는 영향을 받는 버전, FreeBSD 포트 버전, 보안 권고가 포함될 수 있는 다른 웹사이트가 포함됩니다.

pkg는 강력한 유틸리티이며 package:ports-mgmt/portmaster[]와 함께 사용하면 매우 유용합니다.

[[security-advisories]]
== FreeBSD 보안 권고사항

많은 고품질 운영 체제 제작자들과 마찬가지로, FreeBSD 프로젝트에는 각 FreeBSD 릴리스의 종료일(EoL)을 결정하고 아직 종료일에 도달하지 않은 지원 릴리스에 대한 보안 업데이트를 제공하는 보안 팀이 있습니다. FreeBSD 보안 팀과 지원되는 릴리스에 대한 자세한 정보는 https://www.FreeBSD.org/security[FreeBSD 보안 페이지] 링크에서 확인할 수 있습니다.

보안팀의 업무 중 하나는 보고된 FreeBSD 운영체제의 보안 취약점에 대응하는 것입니다. 취약점이 확인되면 보안팀은 취약점을 수정하는 데 필요한 단계를 확인하고 수정 사항이 포함된 소스 코드를 업데이트합니다. 그런 다음 세부 사항을 ‘보안 권고’로 게시합니다. 보안 권고문은 https://www.FreeBSD.org/security/advisories/[FreeBSD 웹사이트] 링크에 게시되며 {freebsd-security-notifications}, {freebsd-security} 및 {freebsd-announce} 메일링 리스트에 발송됩니다.

이 섹션에서는 FreeBSD 보안 권고의 형식을 설명합니다.

=== 보안 권고 형식

다음은 FreeBSD 보안 권고의 예입니다:

[.programlisting]
....
=============================================================================
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

=============================================================================
FreeBSD-SA-14:04.bind                                       Security Advisory
                                                          The FreeBSD Project

Topic:          BIND remote denial of service vulnerability

Category:       contrib
Module:         bind
Announced:      2014-01-14
Credits:        ISC
Affects:        FreeBSD 8.x and FreeBSD 9.x
Corrected:      2014-01-14 19:38:37 UTC (stable/9, 9.2-STABLE)
                2014-01-14 19:42:28 UTC (releng/9.2, 9.2-RELEASE-p3)
                2014-01-14 19:42:28 UTC (releng/9.1, 9.1-RELEASE-p10)
                2014-01-14 19:38:37 UTC (stable/8, 8.4-STABLE)
                2014-01-14 19:42:28 UTC (releng/8.4, 8.4-RELEASE-p7)
                2014-01-14 19:42:28 UTC (releng/8.3, 8.3-RELEASE-p14)
CVE Name:       CVE-2014-0591

For general information regarding FreeBSD Security Advisories,
including descriptions of the fields above, security branches, and the
following sections, please visit <URL:http://security.FreeBSD.org/>.

I.   Background

BIND 9 is an implementation of the Domain Name System (DNS) protocols.
The named(8) daemon is an Internet Domain Name Server.

II.  Problem Description

Because of a defect in handling queries for NSEC3-signed zones, BIND can
crash with an "INSIST" failure in name.c when processing queries possessing
certain properties.  This issue only affects authoritative nameservers with
at least one NSEC3-signed zone.  Recursive-only servers are not at risk.

III. Impact

An attacker who can send a specially crafted query could cause named(8)
to crash, resulting in a denial of service.

IV.  Workaround

No workaround is available, but systems not running authoritative DNS service
with at least one NSEC3-signed zone using named(8) are not vulnerable.

V.   Solution

Perform one of the following:

1) Upgrade your vulnerable system to a supported FreeBSD stable or
release / security branch (releng) dated after the correction date.

2) To update your vulnerable system via a source code patch:

The following patches have been verified to apply to the applicable
FreeBSD release branches.

a) Download the relevant patch from the location below, and verify the
detached PGP signature using your PGP utility.

[FreeBSD 8.3, 8.4, 9.1, 9.2-RELEASE and 8.4-STABLE]
# fetch http://security.FreeBSD.org/patches/SA-14:04/bind-release.patch
# fetch http://security.FreeBSD.org/patches/SA-14:04/bind-release.patch.asc
# gpg --verify bind-release.patch.asc

[FreeBSD 9.2-STABLE]
# fetch http://security.FreeBSD.org/patches/SA-14:04/bind-stable-9.patch
# fetch http://security.FreeBSD.org/patches/SA-14:04/bind-stable-9.patch.asc
# gpg --verify bind-stable-9.patch.asc

b) Execute the following commands as root:

# cd /usr/src
# patch < /path/to/patch

Recompile the operating system using buildworld and installworld as
described in <URL:https://www.FreeBSD.org/handbook/makeworld.html>.

Restart the applicable daemons, or reboot the system.

3) To update your vulnerable system via a binary patch:

Systems running a RELEASE version of FreeBSD on the i386 or amd64
platforms can be updated via the man:freebsd-update[8] utility:

# freebsd-update fetch
# freebsd-update install

VI.  Correction details

The following list contains the correction revision numbers for each
affected branch.

Branch/path                                                      Revision
- -------------------------------------------------------------------------
stable/8/                                                         r260646
releng/8.3/                                                       r260647
releng/8.4/                                                       r260647
stable/9/                                                         r260646
releng/9.1/                                                       r260647
releng/9.2/                                                       r260647
- -------------------------------------------------------------------------

To see which files were modified by a particular revision, run the
following command, replacing NNNNNN with the revision number, on a
machine with Subversion installed:

# svn diff -cNNNNNN --summarize svn://svn.freebsd.org/base

Or visit the following URL, replacing NNNNNN with the revision number:

<URL:https://svnweb.freebsd.org/base?view=revision&revision=NNNNNN>

VII. References

<URL:https://kb.isc.org/article/AA-01078>

<URL:http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0591>

The latest revision of this advisory is available at
<URL:http://security.FreeBSD.org/advisories/FreeBSD-SA-14:04.bind.asc>
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJS1ZTYAAoJEO1n7NZdz2rnOvQP/2/68/s9Cu35PmqNtSZVVxVG
ZSQP5EGWx/lramNf9566iKxOrLRMq/h3XWcC4goVd+gZFrvITJSVOWSa7ntDQ7TO
XcinfRZ/iyiJbs/Rg2wLHc/t5oVSyeouyccqODYFbOwOlk35JjOTMUG1YcX+Zasg
ax8RV+7Zt1QSBkMlOz/myBLXUjlTZ3Xg2FXVsfFQW5/g2CjuHpRSFx1bVNX6ysoG
9DT58EQcYxIS8WfkHRbbXKh9I1nSfZ7/Hky/kTafRdRMrjAgbqFgHkYTYsBZeav5
fYWKGQRJulYfeZQ90yMTvlpF42DjCC3uJYamJnwDIu8OhS1WRBI8fQfr9DRzmRua
OK3BK9hUiScDZOJB6OqeVzUTfe7MAA4/UwrDtTYQ+PqAenv1PK8DZqwXyxA9ThHb
zKO3OwuKOVHJnKvpOcr+eNwo7jbnHlis0oBksj/mrq2P9m2ueF9gzCiq5Ri5Syag
Wssb1HUoMGwqU0roS8+pRpNC8YgsWpsttvUWSZ8u6Vj/FLeHpiV3mYXPVMaKRhVm
067BA2uj4Th1JKtGleox+Em0R7OFbCc/9aWC67wiqI6KRyit9pYiF3npph+7D5Eq
7zPsUdDd+qc+UTiLp3liCRp5w6484wWdhZO6wRtmUgxGjNkxFoNnX8CitzF8AaqO
UWWemqWuz3lAZuORQ9KX
=OQzQ
-----END PGP SIGNATURE-----
....

모든 보안 권고에는 다음 형식이 사용됩니다:

* 각 보안 권고에는 보안 담당자의 PGP 키가 서명되어 있습니다. 보안 담당자의 공개 키는 crossref:pgpkeys[pgpkeys,OpenPGP Keys]에서 확인할 수 있습니다.
* 보안 권고의 이름은 항상 `FreeBSD-SA-`(FreeBSD 보안 권고의 경우)로 시작하고, 두 자리 형식의 연도(`14:`), 해당 연도의 권고 번호(`04.`), 영향을 받는 애플리케이션 또는 서브시스템의 이름(`bind`)이 이어집니다. 여기에 표시된 권고 사항은 2014년에 대한 네 번째 권고 사항이며 BIND에 영향을 줍니다.
* ‘Topic’ 필드에는 취약점이 요약되어 있습니다.
* `Category`는 시스템의 영향을 받는 부분을 의미하며, `core`, `contrib` 또는 `ports` 중 하나일 수 있습니다. `core` 카테고리는 취약점이 FreeBSD 운영 체제의 핵심 구성 요소에 영향을 미친다는 것을 의미합니다. `contrib` 카테고리는 취약점이 BIND와 같이 FreeBSD에 포함된 소프트웨어에 영향을 미친다는 것을 의미합니다. `ports` 카테고리는 취약점이 포트 컬렉션을 통해 제공되는 소프트웨어에 영향을 미친다는 것을 나타냅니다.
* `Module` 필드는 컴포넌트 위치를 나타냅니다. 이 예에서는 `bind` 모듈이 영향을 받으므로 이 취약점은 운영 체제와 함께 설치된 애플리케이션에 영향을 미칩니다.
* `Announced` 필드는 보안 권고가 발표된 날짜를 반영합니다. 이는 보안 팀이 해당 문제가 존재하고 패치가 FreeBSD 소스 코드 저장소에 커밋되었음을 확인했음을 의미합니다.
* `Credits` 필드에는 취약점을 발견하고 신고한 개인 또는 조직에 대한 크레딧이 표시됩니다.
* `Affects` 필드에는 이 취약점에 영향을 받는 FreeBSD 릴리스가 설명되어 있습니다.
* `Corrected` 필드에는 수정된 날짜, 시간, 시간 오프셋 및 릴리스가 표시됩니다. 괄호 안의 섹션에는 수정 사항이 병합된 각 브랜치와 해당 브랜치에서 해당 릴리스의 버전 번호가 표시됩니다. 릴리스 식별자 자체에는 버전 번호와 적절한 경우 패치 레벨이 포함됩니다. 패치 레벨은 문자 ‘p’ 뒤에 숫자가 붙어 패치의 시퀀스 번호를 나타내며, 사용자가 시스템에 이미 적용된 패치를 추적할 수 있습니다.
* `CVE Name` 필드에는 공개 http://cve.mitre.org[cve.mitre.org] 보안 취약성 데이터베이스에 있는 권고 번호가 있는 경우 해당 번호가 나열됩니다.
* `Background` 필드에는 영향을 받는 모듈에 대한 설명이 제공됩니다.
* `Problem Description` 필드에는 취약점을 설명합니다. 여기에는 결함이 있는 코드와 유틸리티가 악의적으로 사용될 수 있는 방법에 대한 정보가 포함될 수 있습니다.
* `Impact` 필드에는 문제가 시스템에 미칠 수 있는 영향의 유형을 설명합니다.
* `Workaround` 필드는 시스템 관리자가 시스템을 즉시 패치할 수 없는 경우 해결 방법을 사용할 수 있는지 여부를 나타냅니다.
* `Solution` 필드에는 영향을 받는 시스템에 패치를 적용하기 위한 지침이 제공됩니다. 이는 시스템을 패치하고 안전하게 작동시키기 위한 단계별 테스트 및 검증 방법입니다.
* `Correction Details` 필드에는 수정된 코드가 포함된 리비전 번호와 함께 영향을 받는 각 서브버전 브랜치가 표시됩니다.
* `References` 필드에는 취약점과 관련된 추가 정보의 출처가 나와 있습니다.

[[security-accounting]]
== 프로세스 통계 (Process Accounting)

프로세스 통계는 관리자가 사용된 시스템 리소스와 사용자 간의 할당을 추적하고, 시스템 모니터링을 제공하며, 사용자의 명령을 최소한으로 추적할 수 있는 보안 방법입니다.

프로세스 통계는 긍정적인 점과 부정적인 점이 모두 있습니다. 긍정적인 점 중 하나는 침입을 침입 지점까지 좁힐 수 있다는 점입니다. 단점은 프로세스 계정으로 인해 생성되는 로그의 양과 이에 필요한 디스크 공간입니다. 이 섹션에서는 관리자에게 프로세스 통계의 기본 사항을 안내합니다.

[NOTE]
====
더 세분화된 통계 처리가 필요한 경우 crossref:audit[감사,보안 이벤트 감사]를 참조하세요.
====

=== 프로세스 통계 활성화 및 활용

프로세스 통계를 사용하기 전에 다음 명령을 사용하여 활성화해야 합니다:

[source, shell]
....
# sysrc accounting_enable=yes
# service accounting start
....

계정 정보는 [.filename]#/var/account#에 있는 파일에 저장되며, 필요한 경우 계정 서비스를 처음 시작할 때 자동으로 생성됩니다. 이 파일에는 모든 사용자가 실행한 모든 명령을 포함한 민감한 정보가 포함되어 있습니다. 파일에 대한 쓰기 권한은 ‘root’로 제한되며, 읽기 권한은 ‘root’와 ‘wheel’ 그룹의 구성원으로 제한됩니다. `wheel`의 구성원이 파일을 읽지 못하도록 하려면 [.filename]#/var/account# 디렉터리의 모드를 변경하여 `root`만 액세스할 수 있도록 허용하세요.

활성화하면 프로세스가 CPU 통계 및 실행된 명령과 같은 정보를 추적하기 시작합니다. 모든 계정 로그는 사람이 읽을 수 없는 형식으로 되어 있으며, `sa`를 사용하여 볼 수 있습니다. 옵션 없이 `sa`를 실행하면 사용자당 호출 수, 총 경과 시간(분), 총 CPU 및 사용자 시간(분), 평균 I/O 작업 수와 관련된 정보를 인쇄합니다. 출력을 제어하는 사용 가능한 옵션 목록은 man:sa[8]을 참조하세요.

사용자가 실행한 명령을 표시하려면 `lastcomm`을 사용합니다. 예를 들어, 이 명령은 `ttyp1` 터미널에서 `trhodes`가 `ls`를 사용한 모든 내용을 출력합니다:

[source, shell]
....
# lastcomm ls trhodes ttyp1
....

다른 많은 유용한 옵션이 존재하며 man:lastcomm[1], man:acct[5], man:sa[8]에 설명되어 있습니다.

[[security-resourcelimits]]
== 리소스 제한

FreeBSD는 관리자가 개인이 사용할 수 있는 시스템 리소스의 양을 제한할 수 있는 몇 가지 방법을 제공합니다. 디스크 할당량은 사용자가 사용할 수 있는 디스크 공간의 양을 제한합니다. 할당량은 Quotas are discussed in crossref:disks[quotas,”Disk Quotas”]에 설명되어 있습니다.

CPU 및 메모리와 같은 기타 리소스에 대한 제한은 플랫 파일 또는 리소스 제한 데이터베이스를 구성하는 명령을 사용하여 설정할 수 있습니다. 기존 방법은 [.filename]#/etc/login.conf#를 편집하여 로그인 클래스를 정의합니다. 이 방법은 여전히 지원되지만 변경하려면 이 파일을 편집하고, 리소스 데이터베이스를 다시 빌드하고, [.filename]#/etc/master.passwd#에 필요한 변경을 수행하고, 비밀번호 데이터베이스를 다시 빌드하는 여러 단계의 프로세스를 거쳐야 합니다. 이 과정은 구성할 사용자 수에 따라 시간이 오래 걸릴 수 있습니다.

`rctl`을 사용하면 리소스 제한을 보다 세밀하게 제어하는 방법을 제공할 수 있습니다. 이 명령은 프로세스와 jail에 리소스 제약을 설정하는 데에도 사용할 수 있으므로 사용자 제한 이상의 기능을 지원합니다.

이 섹션에서는 기존 방법부터 시작하여 리소스를 제어하는 두 가지 방법을 설명합니다.

[[users-limiting]]
=== 로그인 클래스 구성하기

기존 방식에서는 로그인 클래스와 로그인 클래스에 적용할 리소스 제한이 [.filename]#/etc/login.conf#에 정의됩니다. 각 사용자 계정은 로그인 클래스에 할당될 수 있으며, 여기서 `default`는 기본 로그인 클래스입니다. 각 로그인 클래스에는 연결된 로그인 기능 집합이 있습니다. 로그인 기능은 `_name_=_value_` 쌍으로, 여기서 _name_은 잘 알려진 식별자이고 _value_는 _name_에 따라 적절하게 처리되는 임의의 문자열입니다.

[NOTE]
====
[.filename]#/etc/login.conf#를 편집할 때마다 다음 명령을 실행하여 [.filename]#/etc/login.conf.db#를 업데이트해야 합니다:

[source, shell]
....
# cap_mkdb /etc/login.conf
....

====

리소스 제한은 기본 로그인 기능과는 두 가지 점에서 다릅니다. 첫째, 모든 제한에는 _소프트_ 및 _하드_ 제한이 있습니다. 소프트 제한은 사용자 또는 애플리케이션에서 조정할 수 있지만 하드 제한보다 높게 설정할 수 없습니다. 하드 제한은 사용자가 낮출 수 있지만 수퍼유저만 올릴 수 있습니다. 둘째, 대부분의 리소스 제한은 특정 사용자에 대해 프로세스별로 적용됩니다.

<<resource-limits>> 에는 가장 일반적으로 사용되는 리소스 제한이 나열되어 있습니다. 사용 가능한 모든 리소스 제한 및 기능은 man:login.conf[5]에 자세히 설명되어 있습니다.

[[resource-limits]]
.로그인 클래스 리소스 제한
[cols="20%,80%", frame="none", options="header"]
|===
| Resource Limit
| Description

|coredumpsize
|The limit on the size of a core file generated by a program is subordinate to other limits on disk usage, such as `filesize` or disk quotas. This limit is often used as a less severe method of controlling disk space consumption. Since users do not generate core files and often do not delete them, this setting may save them from running out of disk space should a large program crash.

|cputime
|The maximum amount of CPU time a user's process may consume. Offending processes will be killed by the kernel. This is a limit on CPU _time_ consumed, not the percentage of the CPU as displayed in some of the fields generated by `top` and `ps`.

|filesize
|The maximum size of a file the user may own. Unlike disk quotas (crossref:disks[quotas,"Disk Quotas"]), this limit is enforced on individual files, not the set of all files a user owns.

|maxproc
|The maximum number of foreground and background processes a user can run. This limit may not be larger than the system limit specified by `kern.maxproc`. Setting this limit too small may hinder a user's productivity as some tasks, such as compiling a large program, start lots of processes.

|memorylocked
|The maximum amount of memory a process may request to be locked into main memory using man:mlock[2]. Some system-critical programs, such as man:amd[8], lock into main memory so that if the system begins to swap, they do not contribute to disk thrashing.

|memoryuse
|The maximum amount of memory a process may consume at any given time. It includes both core memory and swap usage. This is not a catch-all limit for restricting memory consumption, but is a good start.

|openfiles
|The maximum number of files a process may have open. In FreeBSD, files are used to represent sockets and IPC channels, so be careful not to set this too low. The system-wide limit for this is defined by `kern.maxfiles`.

|sbsize
|The limit on the amount of network memory a user may consume. This can be generally used to limit network communications.

|stacksize
|The maximum size of a process stack. This alone is not sufficient to limit the amount of memory a program may use, so it should be used in conjunction with other limits.
|===

리소스 제한을 설정할 때 기억해야 할 몇 가지 다른 사항이 있습니다:

* 시스템 시작 시 [.filename]#/etc/rc#에 의해 시작된 프로세스는 `데몬` 로그인 클래스에 할당됩니다.
* 기본값인 [.filename]#/etc/login.conf#는 대부분의 제한에 대해 합리적인 값을 제공하는 좋은 소스이지만, 모든 시스템에 적합하지 않을 수도 있습니다. 제한을 너무 느슨하게 설정하면 시스템이 남용될 수 있고, 너무 빡빡하게 설정하면 생산성에 부담을 줄 수 있습니다.
* Xorg는 많은 리소스를 사용하며 사용자가 더 많은 프로그램을 동시에 실행하도록 권장합니다.
* 많은 제한은 사용자 뿐만 아니라 개별 프로세스에도 적용됩니다. 예를 들어, `openfiles`를 `50`으로 설정하면 사용자가 실행하는 각 프로세스가 최대 `50`개의 파일을 열 수 있습니다. 사용자가 열 수 있는 파일의 총량은 `openfiles` 값에 `maxproc` 값을 곱한 값입니다. 이는 메모리 소비에도 적용됩니다.

리소스 제한과 로그인 클래스 및 기능 전반에 대한 자세한 내용은 man:cap.mkdb[1], man:getrlimit[2], man:login.conf[5]를 참조하세요.

=== 리소스 제한 활성화 및 구성하기

`kern.racct.enable` 튜너블은 0이 아닌 값으로 설정해야 합니다. 커스텀 커널은 특정 구성이 필요합니다:

[.programlisting]
....
options         RACCT
options         RCTL
....

시스템이 새 커널로 재부팅되면 `rctl`을 사용하여 시스템에 대한 규칙을 설정할 수 있습니다.

규칙 구문은 이 예제 규칙에서 볼 수 있듯이 제목, 제목-ID, 리소스 및 작업을 사용하여 제어됩니다:

[.programlisting]
....
user:trhodes:maxproc:deny=10/user
....

이 규칙에서 제목은 `user`이며, 제목-ID는 `trhodes`, 리소스, `maxproc`은 최대 프로세스 수, 액션은 `deny`로 새 프로세스가 생성되지 않도록 차단합니다. 즉, 사용자 `trhodes`는 `10`개 이하의 프로세스로 제한됩니다. 다른 가능한 작업으로는 콘솔에 로깅하거나, man:devd[8]에 알림을 전달하거나, 프로세스에 시그너처를 보내는 것 등이 있습니다.

규칙을 추가할 때는 약간의 주의가 필요합니다. 이 사용자는 `10` 프로세스로 제한되므로 이 예에서는 사용자가 로그인하여 `screen` 세션을 실행한 후 다른 작업을 수행하지 못하도록 합니다. 리소스 제한에 도달하면 이 예제에서와 같이 오류가 인쇄됩니다:

[source, shell]
....
% man test
    /usr/bin/man: Cannot fork: Resource temporarily unavailable
eval: Cannot fork: Resource temporarily unavailable
....

다른 예로, jail이 메모리 제한을 초과하지 못하도록 할 수 있습니다. 이 규칙은 다음과 같이 작성할 수 있습니다:

[source, shell]
....
# rctl -a jail:httpd:memoryuse:deny=2G/jail
....

규칙은 [.filename]#/etc/rctl.conf#에 추가한 경우 재부팅 시에도 지속됩니다. 형식은 앞의 명령어가 없는 규칙입니다. 예를 들어 이전 규칙을 다음과 같이 추가할 수 있습니다:

[.programlisting]
....
# Block jail from using more than 2G memory:
jail:httpd:memoryuse:deny=2G/jail
....

규칙을 제거하려면 `rctl`을 사용하여 목록에서 규칙을 제거합니다:

[source, shell]
....
# rctl -r user:trhodes:maxproc:deny=10/user
....

모든 규칙을 제거하는 방법은 man:rctl[8]에 문서화되어 있습니다. 그러나 단일 사용자에 대한 모든 규칙을 제거해야 하는 경우 이 명령을 실행할 수 있습니다:

[source, shell]
....
# rctl -r user:trhodes
....

다양한 ‘주제’를 추가로 제어하는 데 사용할 수 있는 다른 많은 리소스가 존재합니다. 이에 대한 자세한 내용은 man:rctl[8]을 참고하세요.

[[security-sudo]]
== Sudo를 통한 공유 관리

시스템 관리자는 종종 사용자에게 권한 있는 작업을 수행할 수 있도록 향상된 권한을 부여할 수 있는 기능이 필요합니다. 팀원들이 특정 작업을 수행하기 위해 FreeBSD 시스템에 대한 액세스 권한을 제공받는다는 생각은 모든 관리자에게 고유한 과제를 안겨줍니다. 이러한 팀원들은 일반 최종 사용자 수준 이상의 일부 액세스만 필요하지만, 거의 항상 수퍼유저 액세스 없이는 작업을 수행할 수 없다고 관리자에게 말합니다. 다행히도 이러한 요구 사항을 정확히 관리할 수 있는 도구가 존재하기 때문에 최종 사용자에게 이러한 액세스 권한을 제공할 이유가 없습니다.

지금까지 보안 장에서는 권한이 부여된 사용자에게 액세스를 허용하고 무단 액세스를 방지하는 방법에 대해 설명했습니다. 권한이 부여된 사용자가 시스템 리소스에 액세스할 수 있게 되면 또 다른 문제가 발생합니다. 대부분의 경우 일부 사용자는 애플리케이션 시작 스크립트에 액세스해야 하거나 관리자 팀이 시스템을 유지 관리해야 할 수 있습니다. 기존에는 표준 사용자 및 그룹, 파일 권한, 심지어 man:su[1] 명령으로 이러한 액세스를 관리했습니다. 애플리케이션에 더 많은 액세스 권한이 필요하고 시스템 리소스를 사용해야 하는 사용자가 늘어남에 따라 더 나은 솔루션이 필요했습니다. 현재 가장 많이 사용되는 애플리케이션은 Sudo입니다.

관리자는 Sudo를 사용하여 시스템 명령에 대한 보다 엄격한 액세스를 구성하고 일부 고급 로깅 기능을 제공할 수 있습니다. 도구로서, 포트 컬렉션에서 package:security/sudo[] 또는 man:pkg[8] 유틸리티를 사용하여 사용할 수 있습니다. man:pkg[8] 도구를 사용하려면:

[source, shell]
....
# pkg install sudo
....

설치가 완료되면 설치된 `visudo`가 텍스트 편집기로 구성 파일을 엽니다. 구문 검사기가 내장되어 있어 파일을 저장하기 전에 오류가 없는지 확인할 수 있으므로 `visudo`를 사용하는 것을 적극 권장합니다.

구성 파일은 여러 개의 작은 섹션으로 구성되어 있어 광범위하게 구성할 수 있습니다. 다음 예제에서 웹 애플리케이션 관리자인 user1은 _webservice_라는 웹 애플리케이션을 시작, 중지 및 다시 시작해야 합니다. 이 사용자에게 이러한 작업을 수행할 수 있는 권한을 부여하려면 [.filename]#/usr/local/etc/sudoers#의 끝에 이 줄을 추가합니다:

[.programlisting]
....
user1   ALL=(ALL)       /usr/sbin/service webservice *
....

이제 사용자는 다음 명령을 사용하여 _webservice_를 시작할 수 있습니다:

[source, shell]
....
% sudo /usr/sbin/service webservice start
....

이 구성을 사용하면 한 명의 사용자가 웹서비스 서비스에 액세스할 수 있지만, 대부분의 조직에서는 전체 웹팀이 서비스 관리를 담당합니다. 한 줄로 전체 그룹에 대한 액세스 권한을 부여할 수도 있습니다. 이 단계에서는 웹 그룹을 만들고, 이 그룹에 사용자를 추가하고, 그룹의 모든 구성원이 서비스를 관리할 수 있도록 허용합니다:

[source, shell]
....
# pw groupadd -g 6001 -n webteam
....

동일한 man:pw[8] 명령을 사용하여 사용자가 웹팀 그룹에 추가됩니다:

[source, shell]
....
# pw groupmod -m user1 -n webteam
....

마지막으로 [.filename]#/usr/local/etc/sudoers#에 있는 이 줄을 통해 웹팀 그룹의 모든 구성원이 _webservice_를 관리할 수 있습니다:

[.programlisting]
....
%webteam   ALL=(ALL)       /usr/sbin/service webservice *
....

man:su[1]와 달리 sudo는 최종 사용자 비밀번호만 필요합니다. 따라서 대부분의 보안 감사에서 지적되는 공유 비밀번호가 필요하지 않다는 이점이 있습니다.

sudo로 애플리케이션을 실행할 수 있는 사용자는 자신의 비밀번호만 입력합니다. 이는 `root` 비밀번호를 입력하고 사용자가 모든 `root` 권한을 획득하는 man:su[1]보다 더 안전하며 더 나은 제어 기능을 제공합니다.

[TIP]
====

대부분의 조직은 2단계 인증 모델로 전환 중이거나 이미 전환한 상태입니다. 이러한 경우 사용자에게 입력할 비밀번호가 없을 수 있습니다. sudo는 이러한 경우를 위해 `NOPASSWD` 변수를 제공합니다. 위의 구성에 이 변수를 추가하면 _webteam_ 그룹의 모든 구성원이 비밀번호 없이도 서비스를 관리할 수 있습니다:

[.programlisting]
....
%webteam   ALL=(ALL)       NOPASSWD: /usr/sbin/service webservice *
....

====

[[security-sudo-loggin]]
=== 로그 출력

sudo를 구현할 때의 장점은 세션 로깅을 활성화할 수 있다는 것입니다. 기본 제공 로그 메커니즘과 포함된 sudoreplay 명령을 사용하면 나중에 확인할 수 있도록 sudo를 통해 시작된 모든 명령이 로깅됩니다. 이 기능을 사용하려면 기본 로그 디렉터리 항목을 추가하세요. 이 예에서는 사용자 변수를 사용합니다. 다른 로그 파일 이름 규칙이 몇 가지 더 있으며, 자세한 내용은 sudoreplay 매뉴얼 페이지를 참조하세요.

[.programlisting]
....
Defaults iolog_dir=/var/log/sudo-io/%{user}
....

[TIP]
====

이 디렉터리는 로깅을 구성한 후 자동으로 생성됩니다. 안전을 위해 시스템에서 기본 권한으로 디렉터리를 만들도록 하는 것이 가장 좋습니다. 또한 이 항목은 sudoreplay 명령을 사용하는 관리자에 대해서도 로깅합니다. 이 동작을 변경하려면 [.filename]#sudoers# 내부의 로깅 옵션을 읽고 주석을 해제하세요.
====

이 지시문을 [.filename]#sudoers# 파일에 추가하면 액세스 로그 요청을 통해 모든 사용자 구성을 업데이트할 수 있습니다. 표시된 예에서 업데이트된 _webteam_ 항목에는 다음과 같은 추가 변경 사항이 있습니다:

[.programlisting]
....
%webteam ALL=(ALL) NOPASSWD: LOG_INPUT: LOG_OUTPUT: /usr/sbin/service webservice *
....

이 시점부터 _webservice_ 애플리케이션의 상태를 변경하는 모든 _webteam_ 멤버가 기록됩니다. 이전 및 현재 세션 목록이 함께 표시될 수 있습니다:

[source, shell]
....
# sudoreplay -l
....

출력에서 특정 세션을 재생하려면 `TSID=` 항목을 검색한 다음 다른 옵션 없이 sudoreplay에 전달하면 세션이 정상 속도로 재생됩니다. 예를 들어:

[source, shell]
....
# sudoreplay user1/00/00/02
....

[WARNING]
====

세션이 기록되는 동안 모든 관리자는 세션을 삭제할 수 있으며, 왜 세션을 삭제했는지에 대한 질문만 남길 수 있습니다. 침입 탐지 시스템(IDS) 또는 유사한 소프트웨어를 통해 매일 확인을 추가하여 다른 관리자에게 수동 변경에 대한 경고를 보내는 것이 좋습니다.
====

`sudoreplay`’는 확장성이 매우 뛰어납니다. 자세한 내용은 문서를 참조하세요.

[[security-doas]]
== sudo의 대안으로 doas 사용하기

package:security/sudo[] 대신 package:security/doas[]를 사용하여 사용자가 향상된 권한을 얻을 수 있는 기능을 제공할 수 있습니다.

doas 유틸리티는 package:security/doas[]의 포트 컬렉션을 통해 또는 man:pkg[8] 유틸리티를 통해 사용할 수 있습니다.

설치 후 [.filename]#/usr/local/etc/doas.conf#를 구성하여 특정 명령 또는 역할에 대한 사용자 액세스 권한을 부여해야 합니다.

가장 간단한 항목은 다음과 같을 수 있는데, doas 명령을 실행할 때 비밀번호를 묻지 않고 local_user 루트 권한을 부여합니다.

[source, shell]
....
permit nopass local_user as root
....

더 많은 구성 예제는 man:doas.conf[5]를 참조하세요.

이제 `doas` 유틸리티를 설치하고 구성한 후 다음과 같이 향상된 권한으로 명령을 실행할 수 있습니다.

[source, shell]
....
$ doas vi /etc/rc.conf
....
