# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/Makefile,v 1.3 2000/11/10 17:04:50 phantom Exp $
# Original version: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

SUBDIR =	dists
SUBDIR+=	docs
SUBDIR+=	links

DOCS =  advocacy.xml
DOCS+=  howhelp.xml
DOCS+=  index.xml
DOCS+=  install.xml
DOCS+=  newsflash.xml
DOCS+=  press.xml

#DATA=	j2j.gif

.include "${DOC_PREFIX}/share/mk/web.site.mk"
