# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/Makefile.inc,v 1.3 2000/11/10 17:04:50 phantom Exp $
# Original revision: 1.2

WEBBASE?=	/data/ru/java
DOC_PREFIX?=	${.CURDIR}/../../../..
