# $FreeBSD$

SUBDIR =
SUBDIR+= contributing
SUBDIR+= freebsd-questions
SUBDIR+= hubs
SUBDIR+= leap-seconds
SUBDIR+= mailing-list-faq
SUBDIR+= nanobsd
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports
SUBDIR+= remote-install

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
