---
title: "Снэпшот-релизы FreeBSD"
sidenav: download
---

:url-snapshots: ftp://ftp.freebsd.org/pub/FreeBSD/snapshots

include::shared/ru/urls.adoc[]

= Снэпшот-релизы FreeBSD

== Что представляют собой снэпшоты?

Для улучшения общей системы выпуска релизов _до_ их реального выхода в свет с возможными проблемами, мы теперь периодически выпускаем промежуточные тестовые релизы, которые называем _снэпшотами_. Они будут очень похожи на полные релизы, за исключением того, что будут несколько меньше.

== Получение снэпшотов

На данный момент доступны следующие снэпшоты:

* link:{url-snapshots}/Jun_2005/[Снэпшоты июня 2005 года] (link:{url-snapshots}/Jun_2005/README.TXT[README.TXT])
** Построены 3 июня 2005 05:00 UTC.
** 5-STABLE: В процессе построения.
** 6-CURRENT: link:{url-snapshots}/Jun_2005/6.0-CURRENT-SNAP004-amd64-disc1.iso[amd64], link:{url-snapshots}/Jun_2005/6.0-CURRENT-SNAP004-i386-disc1.iso[i386], link:{url-snapshots}/Jun_2005/6.0-CURRENT-SNAP004-pc98-disc1.iso[pc98], link:{url-snapshots}/Jun_2005/6.0-CURRENT-SNAP004-sparc64-disc1.iso[sparc64].
** С момента выпуска мартовского снэпшота было исправлено значительное количество ошибок в VFS, однако требуется дополнительное тестирование.
* link:{url-snapshots}/Mar_2005/[Снэпшоты марта 2005 года] (link:{url-snapshots}/Mar_2005/README.TXT[README.TXT], link:{url-snapshots}/Mar_2005/6.0-CURRENT-SNAP002-alpha-disc1.iso[alpha], link:{url-snapshots}/Mar_2005/6.0-CURRENT-SNAP002-amd64-disc1.iso[amd64], link:{url-snapshots}/Mar_2005/6.0-CURRENT-SNAP002-i386-disc1.iso[i386], link:{url-snapshots}/Mar_2005/6.0-CURRENT-SNAP002-pc98-disc1.iso[pc98], link:{url-snapshots}/Mar_2005/6.0-CURRENT-SNAP002-sparc64-disc1.iso[sparc64])
** Только 6-CURRENT. Построены 15 марта 2005 15:48 UTC.
** Множество улучшений в блокировке VFS.
** Новая компоновка ISO с релизом. На disc1 теперь размещается установочный дистрибутивный комплект с полностью подготовленной живой файловой системой. Пакаджи для официальных релизов перейдут на disc2. Такое распределение также будет использоваться для релиза FreeBSD 5.4.
** Поддержка CARP (Common Address Redundancy Protocol).
** Множество исправлений ошибок в маршрутизации прерываний, busdma и прочих подсистемах и драйверах.
* link:{url-snapshots}/Feb_2005/[Снэпшоты февраля 2005 года (alpha, amd64, i386, ia64, pc98, sparc64)]

В настоящее время снэпшоты link:{handbook}#CURRENT[6-CURRENT] и link:{handbook}#STABLE[5-STABLE] выпускаются ежемесячно и размещаются по URL с адресом в формате `{url-snapshots}/<month>_<year>/` где `<year>` обозначает год, а `<month>` обозначает месяц выпуска снэпшота. Каталог каждого снэпшота может содержать файл `RELNOTES.TXT`, в котором описываются изменения, внесённые в данный снэпшот.

== Вещи, знание которых вам может понадобиться

В частности, перед тем, как получить и установить снэпшот-релиз, имейте в виду следующее:

* Снэпшоты в основном предназначены для тестирования и по сравнению с релизами проверяются не так тщательно. В них могут включаться экспериментальные или недоделанные функции, которые, возможно, разрушат вашу существующую систему.
* Старший номер релиза для любого снэпшота не будет изменяться в основном дистрибутиве. Он будет изменяться _только_ на загрузочных дискетах, чтобы вы знали, когда был сделан снэпшот. Они _не являются_ релизами, это _снэпшоты_, и важно, чтобы это различие сохранялось. Хотя люди могут и, конечно, будут обозначать снэпшоты по датам в переписке и конференциях, не путайте их.
* Наконец, мы не будем обновлять документацию в обязательном порядке. К примеру, `README` могут остаться упоминания предыдущего релиза. Это так, потому что этот вопрос менее важен, чем исправление настоящих ошибок и добавление новых возможностей для тестирования. Пожалуйста, не присылайте сообщения об ошибках в документации.

Ваши отклики на эти снэпшоты, конечно, приветствуются. Они нужны не только нам - те, кто собирается опираться на FreeBSD для работы с критичными для бизнеса приложениями, должны приветствовать возможность получать обновляемые версии в структурированной форме. Вы можете также использовать эти снэпшоты в качестве материального доказательства тому, что ваш предложения были учтены и вы (к счастью) не столкнётесь ни с какими ненужными сюрпризами в следующем релизе. С другой стороны, если вы будете посылать нам гневные письма в следующем релизе и окажется, что вы никогда даже не пробовали использовать снэпшоты, ну, это распространяется на обе стороны!

== Другие ресурсы

Вот некоторые связанные с этим информационные ресурсы. Заметьте, что они находятся в распоряжение людей, не входящих в Группу подготовки релизов FreeBSD. Эти сайты предоставляют снэпшоты FreeBSD в форме "живой файловой системы" и загрузочных образов ISO на ежедневной основе. Для выяснения подробностей посетите следующие ссылки и обратитесь к ним напрямую, если у вас есть вопросы.

* http://snapshots.jp.FreeBSD.org/[Сервис FreeBSD SNAPSHOT сайта jp.FreeBSD.org].
* http://snapshots.se.FreeBSD.org/[Сервис FreeBSD снэпшотов сайта se.FreeBSD.org].
