---
title: Capítulo 6. Aplicações de Desktop
part: Parte II. Tarefas comuns
prev: books/handbook/partii
next: books/handbook/multimedia
---

[[desktop]]
= Aplicações de Desktop
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Índice
:table-caption: Tabela
:figure-caption: Figura
:example-caption: Exemplo
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 6

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/desktop/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/en/mailing-lists.adoc[]
include::shared/en/teams.adoc[]
include::shared/en/urls.adoc[]

toc::[]

[[desktop-synopsis]]
== Sinopse

Embora o FreeBSD seja popular como um servidor por seu desempenho e estabilidade, ele também é adequado para o uso diário como desktop. Com mais de 24.000 aplicativos disponíveis como pacotes ou ports para o FreeBSD, é fácil construir um desktop personalizado que executa uma ampla variedade de aplicativos de desktop. Este capítulo demonstra como instalar vários aplicativos de desktop, incluindo navegadores da Web, software de produtividade, visualizadores de documentos e softwares financeiros.

[NOTE]
====
Os usuários que preferem instalar uma versão de desktop pré-configurada do FreeBSD em vez de configurar um do zero devem consultar http://www.furybsd.org[FuryBSD.], https://ghostbsd.org[GhostBSD] or https://www.midnightbsd.org[MidnightBSD].
====

Os leitores deste capítulo devem saber como:

* Instalar software adicional usando pacotes ou ports, conforme descrito em crossref:ports[ports, Instalando Aplicativos. Pacotes e Ports].
* Instalar o X e um gerenciador de janelas, conforme descrito em crossref:x11[x11, O sistema X Window].

Para obter informações sobre como configurar um ambiente multimídia, consulte crossref:multimedia[multimedia, Multimídia].

[[desktop-browsers]]
== Navegadores

O FreeBSD não vem com um navegador Web pré-instalado. Em vez disso, a categoria https://www.FreeBSD.org/ports/[www] da Coleção de Ports contém muitos navegadores que podem ser instalados como um pacote ou compilados a partir da coleção de Ports.

Os ambientes de área de trabalho KDE e GNOME incluem seu próprio navegador HTML. Consulte crossref:x11[x11-wm,Ambientes de desktop] para mais informações sobre como configurar esses desktops completos.

Alguns navegadores leves incluem o package:www/dillo2[], o package:www/links[] e o package:www/w3m[].

Esta seção demonstra como instalar os seguintes navegadores Web populares e indica se o aplicativo é pesado em recursos, se leva tempo para compilar a partir do Ports ou se possui dependências importantes.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Nome da aplicação
| Recursos necessários
| Instalação a partir do Ports
| Notas

|Firefox
|médio
|pesado
|FreeBSD, Linux(TM), e versões localizadas estão disponíveis

|Konqueror
|médio
|pesado
|Requer bibliotecas do KDE

|Chromium
|médio
|pesado
|Requer Gtk+
|===

=== Firefox

O Firefox é um navegador de código-fonte aberto que apresenta um mecanismo de exibição HTML compatível com os padrões, navegação por guias, bloqueio de pop-up, extensões, segurança aprimorada e muito mais. O Firefox é baseado na base de código Mozilla.

Para instalar o pacote da versão mais recente do Firefox, digite:

[source,bash]
....
# pkg install firefox
....

Para instalar a versão ESR (Extended Support Release) do Firefox, use:

[source,bash]
....
# pkg install firefox-esr
....

A Coleção de Ports pode ser usada para compilar a versão desejada do Firefox a partir do código-fonte. Este exemplo compila o package:www/firefox[], onde o `firefox` pode ser substituído pelo ESR ou pela versão localizada para instalar.

[source,bash]
....
# cd /usr/ports/www/firefox
# make install clean
....

=== Konqueror

O Konqueror é mais do que um navegador Web, pois também é um gerenciador de arquivos e um visualizador de multimídia. Suporta WebKit assim como seu próprio KHTML. WebKit é um motor de renderização usado por diversos navegadores modernos incluiindo o Chromium.

O Konqueror pode ser instalado como um pacote digitando:

[source,bash]
....
# pkg install konqueror
....

Para instalar a partir da Coleção de Ports:

[source,bash]
....
# cd /usr/ports/x11-fm/konqueror/
# make install clean
....

=== Chromium

O Chromium é um projeto de navegador de código aberto que visa criar uma experiência de navegação na Web mais segura, mais rápida e mais estável. O Chromium apresenta navegação com guias, bloqueio de pop-up, extensões e muito mais. O Chromium é o projeto de código-fonte aberto no qual o navegador Web do Google Chrome é baseado.

O Chromium pode ser instalado como um pacote digitando:

[source,bash]
....
# pkg install chromium
....

Alternativamente, o Chromium pode ser compilado a partir do código-fonte usando a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/www/chromium
# make install clean
....

[NOTE]
====
O executável do Chromium é [.filename]#/usr/local/bin/chrome#, não [.filename]#/usr/local/bin/chromium#.
====

[[desktop-productivity]]
== Produtividade

Quando se trata de produtividade, os usuários geralmente procuram uma suíte de escritório ou um processador de texto fácil de usar. Embora alguns crossref:x11[x11-wm,ambientes de desktop] como o KDE forneçam uma suíte de escritório, não há um pacote de produtividade padrão. Várias suítes de escritório e processadores de texto gráficos estão disponíveis para o FreeBSD, independentemente do gerenciador de janelas instalado.

Esta seção demonstra como instalar os seguintes softwares populares de produtividade e indica se o aplicativo é pesado em recursos, se leva tempo para compilar a partir do ports ou se possui dependências importantes.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Nome da aplicação
| Recursos necessários
| Instalação a partir do Ports
| Principais Dependências

|Calligra
|leve
|pesado
|KDE

|AbiWord
|leve
|leve
|Gtk+ ou GNOME

|The Gimp
|leve
|pesado
|Gtk+

|Apache OpenOffice
|pesado
|enorme
|JDK(TM) e Mozilla

|LibreOffice
|um pouco pesado
|enorme
|Gtk+, ou KDE/ GNOME, ou JDK(TM)
|===

=== Calligra

O ambiente de área de trabalho do KDE inclui uma suíte de escritório que pode ser instalada separadamente do KDE. O Calligra inclui componentes padrões que podem ser encontrados em outros pacotes de escritório. O Words é o processador de texto, Sheets é o programa de planilha eletrônica, o Stage gerencia apresentações de slides e Karbon é usado para desenhar documentos gráficos.

No FreeBSD, o package:editors/calligra[] pode ser instalado como um pacote ou um port. Para instalar o pacote:

[source,bash]
....
# pkg install calligra
....

Se o pacote não estiver disponível, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/editors/calligra
# make install clean
....

=== AbiWord

O AbiWord é um programa gratuito de processamento de texto semelhante em aparência ao Microsoft(TM) Word. É rápido, contém muitos recursos e é de fácil utilização.

O AbiWord pode importar ou exportar muitos formatos de arquivo, incluindo alguns formatos proprietários como o Microsoft(TM)[.filename]#.rtf#.

Para instalar o pacote do AbiWord:

[source,bash]
....
# pkg install abiword
....

Se o pacote não estiver disponível, ele pode ser compilado a partir da Coleção de Ports:

[source,bash]
....
# cd /usr/ports/editors/abiword
# make install clean
....

=== O GIMP

Para autoria ou retoque de imagens, o GIMP fornece um sofisticado programa de manipulação de imagens. Ele pode ser usado como um programa de pintura simples ou como um pacote de qualidade para retoque de fotos. Ele suporta um grande número de plugins e possui uma interface de script. O GIMP pode ler e gravar uma grande variedade de formatos de arquivos e suporta interfaces com scanners e tablets.

Para instalar o pacote:

[source,bash]
....
# pkg install gimp
....

Como alternativa, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/graphics/gimp
# make install clean
....

A categoria de programas gráficos (https://www.FreeBSD.org/ports/[freebsd.org/ports/]) da Coleção de Ports contém vários plugins relacionados ao GIMP, arquivos de ajuda e manuais do usuário.

=== Apache OpenOffice

O Apache OpenOffice é uma suíte de escritório de código-fonte aberto que é desenvolvida sob a asa da Incubadora da Apache Software Foundation. Ele inclui todos os aplicativos encontrados em um pacote completo de produtividade de escritório: um processador de texto, uma planilha eletrônica, um gerenciador de apresentação e um programa de desenho. Sua interface de usuário é semelhante a outros pacotes de escritório e pode importar e exportar em vários formatos de arquivo populares. Está disponível em vários idiomas diferentes e a internacionalização foi estendida para interfaces, corretores ortográficos e dicionários.

O processador de texto do Apache OpenOffice usa um formato de arquivo XML nativo para maior portabilidade e flexibilidade. O programa de planilha eletrônica possui uma linguagem de macros que pode ser conectada a bancos de dados externos. O Apache OpenOffice é estável e roda nativamente em Windows(TM), Solaris(TM), Linux(TM), FreeBSD, e Mac OS(TM) X. Maiores informações sobre o Apache OpenOffice podem ser encontradas em http://openoffice.org/[openoffice.org]. Para informações específicas do FreeBSD, consulte http://porting.openoffice.org/freebsd/[porting.openoffice.org/freebsd/].

Para instalar o pacote Apache OpenOffice:

[source,bash]
....
# pkg install apache-openoffice
....

Depois que o pacote for instalado, digite o seguinte comando para iniciar o Apache OpenOffice:

[source,bash]
....
% openoffice-X.Y.Z
....

onde _X.Y.Z_ é o número da versão instalada do Apache OpenOffice. Na primeira vez que o Apache OpenOffice for iniciado, algumas perguntas serão feitas e uma pasta [.filename]#.openoffice.org# será criada no diretório pessoal do usuário.

Se o pacote do Apache OpenOffice desejado não estiver disponível, a compilação do port ainda será uma opção. No entanto, isso requer muito espaço em disco e um tempo bastante longo para compilar:

[source,bash]
....
# cd /usr/ports/editors/openoffice-4
# make install clean
....

[NOTE]
====
Para compilar uma versão localizada, substitua o comando anterior por:

[source,bash]
....
# make LOCALIZED_LANG=your_language install clean
....

Substitua _your_language_ pelo código ISO do idioma correto. Uma lista de códigos de idiomas suportados está disponível em [.filename]#files/Makefile.localized#, localizado no diretório do port.
====

=== LibreOffice

O LibreOffice é um pacote de software livre desenvolvido por http://www.documentfoundation.org/[documentfoundation.org]. É compatível com outras grandes suítes de escritórios e está disponível em diversas plataformas. Ele é um fork renomeado do Apache OpenOffice e inclui aplicativos encontrados em um pacote completo de produtividade de escritório: processador de texto, planilha, gerenciador de apresentação, programa de desenho, programa de gerenciamento de banco de dados e uma ferramenta para criar e editar fórmulas matemáticas. Está disponível em vários idiomas diferentes e a internacionalização foi estendida para interfaces, corretores ortográficos e dicionários.

O processador de texto do LibreOffice usa um formato de arquivo XML nativo para maior portabilidade e flexibilidade. O programa de planilha eletrônica possui uma linguagem de macros que pode ser conectada a bancos de dados externos. O LibreOffice é estável e roda nativamente em Windows(TM), Linux(TM), FreeBSD e Mac OS(TM) X. Maiores informações sobre o LibreOffice podem ser encontradas em http://www.libreoffice.org/[libreoffice.org].

Para instalar a versão em inglês do pacote LibreOffice:

[source,bash]
....
# pkg install libreoffice
....

A categoria de editores de texto (https://www.FreeBSD.org/ports/[freebsd.org/ports/]) da Coleção de Ports contém várias versões versões localizadas do LibreOffice. Ao instalar um pacote localizado, substitua `libreoffice` pelo nome do pacote localizado.

Quando o pacote estiver instalado, digite o seguinte comando para executar o LibreOffice:

[source,bash]
....
% libreoffice
....

Durante a primeira execução, algumas perguntas serão feitas e uma pasta [.filename]#.libreoffice# será criada no diretório pessoal do usuário.

Se o pacote LibreOffice desejado não estiver disponível, a compilação do port ainda será uma opção. No entanto, isso requer muito espaço em disco e um tempo bastante longo para compilar. Este exemplo compila a versão em inglês:

[source,bash]
....
# cd /usr/ports/editors/libreoffice
# make install clean
....

[NOTE]
====
Para compilar uma versão localizada, faça `cd` para o diretório do port do idioma desejado. Os idiomas suportados podem ser encontrados na categoria de editores (https://www.FreeBSD.org/ports/[freebsd.org/ports/]) da Coleção de Ports.
====

[[desktop-viewers]]
== Visualizadores de Documentos

Alguns novos formatos de documentos ganharam popularidade desde o advento do UNIX(TM) e os visualizadores que eles exigem podem não estar disponíveis no sistema base. Esta seção demonstra como instalar os seguintes visualizadores de documentos:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Nome da aplicação
| Recursos necessários
| Instalação a partir do Ports
| Principais Dependências

|Xpdf
|leve
|leve
|FreeType

|gv
|leve
|leve
|Xaw3d

|Geeqie
|leve
|leve
|Gtk+ ou GNOME

|ePDFView
|leve
|leve
|Gtk+

|Okular
|leve
|pesado
|KDE
|===

=== Xpdf

Para os usuários que preferem um pequeno visualizador de PDF do FreeBSD, o Xpdf fornece um visualizador leve e eficiente que requer poucos recursos. Ele usa as fontes X padrão e não requer nenhum kit de ferramentas adicional.

Para instalar o pacote Xpdf:

[source,bash]
....
# pkg install xpdf
....

Se o pacote não estiver disponível, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/graphics/xpdf
# make install clean
....

Quando a instalação estiver concluída, inicie o `xpdf` e use o botão direito do mouse para ativar o menu.

=== gv

O gv é um visualizador de arquivos PostScript(TM) e PDF. Ele é baseado no ghostview, mas tem uma aparência mais agradável, pois é baseado no kit de ferramentas do widget Xaw3d. O gv possui muitos recursos configuráveis, como orientação, tamanho do papel, escala e anti-aliasing. Quase qualquer operação pode ser executada com o teclado ou com o mouse.

Para instalar o gv como um pacote:

[source,bash]
....
# pkg install gv
....

Se um pacote não estiver disponível, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/print/gv
# make install clean
....

=== Geeqie

O  Geeqie  é um fork do projeto abandonado GQView, em um esforço para levar o desenvolvimento adiante e integrar os patches existentes. O Geeqie é um gerenciador de imagens que suporta a visualização de um arquivo com um único clique, a execução de um editor externo e a visualização de miniaturas. Ele também possui um modo de apresentação de slides e algumas operações básicas de arquivo, facilitando o gerenciamento das coleções de imagens e a localização de arquivos duplicados. O Geeqie suporta visualização em tela cheia e a internacionalização.

Para instalar o pacote Geeqie:

[source,bash]
....
# pkg install geeqie
....

Se o pacote não estiver disponível, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/graphics/geeqie
# make install clean
....

=== ePDFView

O ePDFView é um visualizador de documentos PDF leve que usa somente as bibliotecas Gtk+ e Poppler. Ele está atualmente em desenvolvimento, mas já abre a maioria dos arquivos PDF (até os criptografados), salva cópias de documentos e tem suporte para impressão usando o CUPS.

Para instalar o ePDFView como um pacote:

[source,bash]
....
# pkg install epdfview
....

Se um pacote não estiver disponível, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/graphics/epdfview
# make install clean
....

=== Okular

O Okular é um visualizador de documentos universal baseado no KPDF para KDE. Ele pode abrir muitos formatos de documentos, incluindo PDF, PostScript(TM), DjVu, CHM, XPS e ePub.

Para instalar o Okular como um pacote:

[source,bash]
....
# pkg install okular
....

Se um pacote não estiver disponível, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/graphics/okular
# make install clean
....

[[desktop-finance]]
== Finanças

Para gerenciar finanças pessoais em um desktop FreeBSD, alguns aplicativos poderosos e fáceis de usar podem ser instalados. Alguns são compatíveis com formatos de arquivos comuns, como os formatos usados pelo Quicken e Excel.

Esta seção cobre estes programas:

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Nome da aplicação
| Recursos necessários
| Instalação a partir do Ports
| Principais Dependências

|GnuCash
|leve
|pesado
|GNOME

|Gnumeric
|leve
|pesado
|GNOME

|KMyMoney
|leve
|pesado
|KDE
|===

=== GnuCash

O GnuCash faz parte do esforço do GNOME para fornecer aplicativos fáceis de usar, mas poderosos, para usuários finais. O GnuCash pode ser usado para acompanhar receitas e despesas, contas bancárias e ações. Ele apresenta uma interface intuitiva, mantendo-se profissional.

O  GnuCash  fornece um registro inteligente, um sistema hierárquico de contas e muitos aceleradores de teclado e métodos de preenchimento automático. Ele pode dividir uma única transação em várias partes mais detalhadas. O GnuCash pode importar e mesclar arquivos QIF do Quicken. Ele também lida com a maioria dos formatos internacionais de data e moeda.

Para instalar o pacote GnuCash:

[source,bash]
....
# pkg install gnucash
....

Se o pacote não estiver disponível, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/finance/gnucash
# make install clean
....

=== Gnumeric

O Gnumeric é um programa de planilha eletrônica desenvolvido pela comunidade GNOME. Ele possui adivinhação automática e conveniente de entrada do usuário de acordo com o formato da célula para muitas sequências. Ele pode importar arquivos em vários formatos populares, incluindo Excel, Lotus 1-2-3 e Quattro Pro. Ele tem um grande número de funções internas e permite todos os formatos usuais de célula, como número, moeda, data, hora e muito mais.

Para instalar o Gnumeric como um pacote:

[source,bash]
....
# pkg install gnumeric
....

Se o pacote não estiver disponível, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/math/gnumeric
# make install clean
....

=== KMyMoney

O KMyMoney é uma aplicação de finanças pessoais criada pela comunidade KDE. O KMyMoney tem como objetivo fornecer os recursos importantes encontrados em aplicativos comerciais de gerenciamento de finanças pessoais. Ele também destaca a facilidade de uso e a contabilidade adequada de dupla entrada entre seus recursos. O KMyMoney importa a partir de arquivos QIF padrão do Quicken, rastreia investimentos, manipula várias moedas e fornece diversos relatórios.

Para instalar o KMyMoney como um pacote:

[source,bash]
....
# pkg install kmymoney-kde4
....

Se o pacote não estiver disponível, use a Coleção de Ports:

[source,bash]
....
# cd /usr/ports/finance/kmymoney-kde4
# make install clean
....
