#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
# $Id: Makefile,v 1.1 2003-06-09 13:49:17 blackend Exp $
# Original revision: 1.1
#

CHAPTERS= 	disks/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
