# $FreeBSD: www/en/releng/Makefile,v 1.4 2012/04/29 21:35:32 simon Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.sgml charter.sgml dst_info.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
