# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/docs/Makefile,v 1.2 2000/10/11 16:16:15 phantom Exp $
# Original revision: 1.2

DOCS =	faq.sgml
DOCS+=	howtoports.sgml
DOCS+=	newbies.sgml
DOCS+=	performance.sgml
DOCS+=	tutorials.sgml

.include "../../web.mk"
