<p>The FreeBSD Ports Collection offers a simple way for users and
administrators to install applications.  Each ``port'' listed here
contains any patches necessary to make the original application source
code compile and run on FreeBSD.  Installing an application is as
simple as downloading the port, unpacking it and typing <tt>make</tt>
in the port directory.  The <tt>Makefile</tt> automatically fetches the
application source code, either from a local disk or via ftp,
unpacks it on your system, applies the patches, and compiles.  If
all goes well, simply type <tt>make install</tt> to install the
application.</p>

<p>For more information about using ports, see <a
href="../handbook/ports.html">The ports collection</a>.  For
information about creating new ports, see <a
href="../handbook/porting.html">Porting applications</a>.  Both are
part of the <a href="../handbook">FreeBSD Handbook</a>.</p>

<p>For more information about new ports, changed ports,
removed ports, or searching for an application see the 
<a href="http://www.de.freebsd.org/de/cgi/ports.cgi">
FreeBSD Ports Changes</a> script.</p>
