<p>The FreeBSD Ports Collection offers a simple way for users and
administrators to install applications.  Each ``port'' listed here
contains any patches necessary to make the original application source
code compile and run on FreeBSD.  Installing an application is as
simple as downloading the port, unpacking it and typing <tt>make</tt>
in the port directory.  The <tt>Makefile</tt> automatically fetches the
application source code, either from a local disk or via ftp,
unpacks it on your system, applies the patches, and compiles.  If
all goes well, simply type <tt>make install</tt> to install the
application.</p>

<p>Below are the listings of ports currently available, arranged
by application type.  Four links are available for each port listed:</p>

<dl>
<dt><b>Description</b></dt><dd>This fetches a description
of the application from the FTP archive (ftp.freebsd.org).</dd>

<dt><b>Browse</b></dt><dd>This is a link to the FTP archive directory
for the port where you can examine the Makefile and patches.</dd>

<dt><b>Download</b></dt><dd>This is a link to a gzip'd tar file
containing the port. Be sure to tell your browser to <em>save</em>
rather than <em>display</em>!</dd>

<dt><b>Maintainer</b></dt><dd>The person responsible for maintaining
the port.  If you have problems with a <em>specific</em> port,
contact this person.</dd>
</dl>

<p>For more information, see <a href="../handbook/ports.html">The
ports collection</a> and <a
href="../handbook/porting.html">Porting applications</a> in the <a
href="../handbook">FreeBSD Handbook</a>.</p>
