#
# The FreeBSD Russian Documentation Project
#
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/linux-comparison/Makefile,v 1.2 2005/09/13 10:23:44 gad Exp $
# $FreeBSD$
#
# Original revision: r39631
#
# Article: FreeBSD and Linux Comparison Whitepaper

DOC?= article

FORMATS?= html
INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
