# $FreeBSD: www/hu/docs/Makefile,v 1.1 2007/01/07 22:44:47 keramida Exp $

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.sgml webresources.sgml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
