# $FreeBSD: www/en/java/docs/Makefile,v 1.2 2000/03/02 15:55:52 phantom Exp $

DOCS =	faq.sgml
DOCS+=	howtoports.sgml
DOCS+=	newbies.sgml
DOCS+=	tutorials.sgml
DOCS+=	performance.sgml

.include "../../web.mk"
