# $FreeBSD: www/en/developers/Makefile,v 1.1 2005/10/04 05:57:25 murray Exp $

###################################################
# The FreeBSD Hungarian Documentation Project     #
###################################################

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   cvs.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
