---
title: Κεφάλαιο 25. DTrace
part: Μέρος III. Διαχείριση Συστήματος
prev: books/handbook/cutting-edge
next: books/handbook/partiv
---

[[dtrace]]
= DTrace
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Πίνακας Περιεχομένων
:table-caption: Πίνακας
:figure-caption: Σχήμα
:example-caption: Παράδειγμα
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: 25

ifeval::["{backend}" == "html5"]
:imagesdir: ../../../images/books/handbook/dtrace/
endif::[]

ifeval::["{backend}" == "pdf"]
:imagesdir: ../../../../static/images/books/handbook/dtrace/
endif::[]

ifeval::["{backend}" == "epub3"]
:imagesdir: ../../../../static/images/books/handbook/dtrace/
endif::[]

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/el/mailing-lists.adoc[]
include::shared/el/teams.adoc[]
include::shared/el/urls.adoc[]

toc::[]

[[dtrace-synopsis]]
== Σύνοψη

Το DTrace, γνωστό επίσης ως Dynamic Tracing, είναι ένα εργαλείο το οποίο αναπτύχθηκε από την Sun(TM) για τον εντοπισμό προβλημάτων απόδοσης σε συστήματα που πρόκειται να χρησιμοποιηθούν ή χρησιμοποιούνται ήδη στην παραγωγή. Δεν πρόκειται για εργαλείο αποσφαλμάτωσης, αλλά για εργαλείο ανάλυσης πραγματικού χρόνου, με το οποίο μπορούν να εντοπιστούν προβλήματα απόδοσης και άλλες καταστάσεις.

Το DTrace είναι ένα θαυμάσιο εργαλείο profiling και διαθέτει εντυπωσιακό πλήθος χαρακτηριστικών για την διάγνωση προβλημάτων του συστήματος. Μπορεί επίσης να χρησιμοποιηθεί για να εκτελέσει από πριν έτοιμα scripts, με τα οποία μπορείτε να εκμεταλλευθείτε καλύτερα τις δυνατότητες του. Οι χρήστες μπορούν ακόμα να γράψουν και τα δικά τους βοηθητικά προγράμματα, χρησιμοποιώντας την Γλώσσα D που παρέχει το DTrace, και να προσαρμόσουν με αυτό τον τρόπο το profiling στις δικές τους ανάγκες.

Αφού διαβάσετε αυτό το κεφάλαιο, θα γνωρίζετε:

* Τι είναι το DTrace και τι δυνατότητες παρέχει.
* Τις διαφορές υλοποίησης μεταξύ του DTrace του Solaris(TM) και του FreeBSD.
* Πως να ενεργοποιήσετε και να χρησιμοποιήσετε το DTrace στο FreeBSD.

Πριν διαβάσετε αυτό το κεφάλαιο, θα πρέπει:

* Να κατανοείτε βασικές έννοιες του UNIX(R) και του FreeBSD (crossref:basics[basics,Βασικές Έννοιες στο UNIX(R)]).
* Να είστε εξοικειωμένος με τις βασικές διαδικασίες ρύθμισης και μεταγλώττισης προσαρμοσμένου πυρήνα (crossref:kernelconfig[kernelconfig,Ρυθμίζοντας τον Πυρήνα του FreeBSD]).
* Να είστε εξοικειωμένος με την ασφάλεια και τον τρόπο που αυτή σχετίζεται με το FreeBSD (crossref:security[security,Ασφάλεια]).
* Να κατανοείτε πως μπορείτε να ανακτήσετε τον πηγαίο κώδικα του FreeBSD και να τον χρησιμοποιήσετε ώστε να επαναμεταγλωττίσετε το σύστημα σας (crossref:cutting-edge[updating-upgrading,Ενημέρωση και Αναβάθμιση του FreeBSD]).

[WARNING]
====

Τη δεδομένη στιγμή, το DTrace θεωρείται ότι είναι σε πειραματικό στάδιο. Ορισμένες επιλογές μπορεί να υπολείπονται σε λειτουργικότητα, και κάποια τμήματα ίσως να μη λειτουργούν καθόλου. Με την πάροδο του χρόνου, οι παραπάνω δυνατότητες θα θεωρηθούν έτοιμες για χρήση σε μηχανήματα παραγωγής, και η παρούσα τεκμηρίωση θα ανανεωθεί ώστε να αντιπροσωπεύει αυτή την κατάσταση.
====

[[dtrace-implementation]]
== Διαφορές στην Υλοποίηση

Αν και το DTrace στο FreeBSD είναι αρκετά όμοιο με αυτό του Solaris(TM), υπάρχουν κάποιες διαφορές που θα πρέπει να τις εξηγήσουμε πριν συνεχίσουμε. Η μεγαλύτερη διαφορά που θα παρατηρήσουν οι χρήστες, είναι ότι στο FreeBSD το DTrace πρέπει να ενεργοποιηθεί χειροκίνητα. Υπάρχουν διάφορες επιλογές και αρθρώματα για τον πυρήνα που πρέπει να ενεργοποιηθούν ώστε το DTrace να λειτουργεί σωστά. Θα εξηγήσουμε αργότερα αυτές τις ρυθμίσεις.

Η επιλογή `DDB_CTF` του πυρήνα χρησιμοποιείται για να ενεργοποιήσει την υποστήριξη φορτώματος των δεδομένων CTF από τον πυρήνα και τα αρθρώματα του. Το CTF είναι το Compact C Type format του Solaris(TM), το οποίο ενθυλακώνει μια ελαττωμένη μορφή πληροφοριών αποσφαλμάτωσης (debugging), όμοια με το DWARF και τα stabs. Αυτά τα δεδομένα CTF προστίθενται στα εκτελέσιμα μέσω των εργαλείων `ctfconvert` και `ctfmerge`. Το βοηθητικό πρόγραμμα `ctfconvert` ερμηνεύει τα τμήματα των DWARFELF που περιέχουν πληροφορίες debug (δημιουργούνται από το μεταγλωττιστή), και το `ctfmerge` συγχωνεύει τα τμήματα CTF και ELF από τα αντικείμενα σε άλλα εκτελέσιμα ή κοινόχρηστες βιβλιοθήκες. Περισσότερες πληροφορίες για την ενεργοποίηση των παραπάνω στη μεταγλώττιση του πυρήνα και του συστήματος του FreeBSD, θα δούμε παρακάτω.

Στο FreeBSD κάποιοι παροχείς είναι διαφορετικοί σε σχέση με το Solaris(TM). Ο πιο αξιοσημείωτος είναι ο παροχέας `dtmalloc` ο οποίος επιτρέπει το tracing του `malloc()` ανάλογα με τον τύπο του, στον πυρήνα του FreeBSD.

Μόνο ο `root` μπορεί να χρησιμοποιήσει το DTrace στο FreeBSD. Αυτό σχετίζεται με διαφορές στην ασφάλεια, καθώς το Solaris(TM) διαθέτει κάποιους ελέγχους ασφάλειας χαμηλού επιπέδου, οι οποίοι δεν υπάρχουν ακόμα στο FreeBSD. Για το λόγο αυτό, η χρήση της συσκευής [.filename]#/dev/dtrace/dtrace# απαγορεύεται αυστηρά για όλους τους χρήστες εκτός από τον `root`.

Τέλος, το λογισμικό DTrace βρίσκεται υπό την άδεια CDDL της Sun(TM). Μπορείτε να διαβάσετε το κείμενο της άδειας `Common Development and Distribution License` στο FreeBSD, στο αρχείο [.filename]#/usr/src/cddl/contrib/opensolaris/OPENSOLARIS.LICENSE# ή να το διαβάσετε online στη διεύθυνση http://www.opensolaris.org/os/licensing[http://www.opensolaris.org/os/licensing].

Η άδεια ουσιαστικά σημαίνει ότι ένας πυρήνας FreeBSD με τις επιλογές του DTrace, εξακολουθεί να βρίσκεται υπό την άδεια BSD. Ωστόσο το CDDL εμπλέκεται τη στιγμή που γίνεται διανομή των αρθρωμάτων σε δυαδική μορφή, ή τη στιγμή που φορτώνονται.

[[dtrace-enable]]
== Ενεργοποίηση της Υποστήριξης DTrace

Για να ενεργοποιήσετε την υποστήριξη για το DTrace, προσθέστε τις ακόλουθες γραμμές στο αρχείο ρυθμίσεων του πυρήνα:

[.programlisting]
....
options         KDTRACE_HOOKS
options         DDB_CTF
....

[NOTE]
====
Οι χρήστες της αρχιτεκτονικής AMD64 θα θέλουν να προσθέσουν την ακόλουθη γραμμή στο αρχείο ρυθμίσεων του πυρήνα τους:

[.programlisting]
....
options         KDTRACE_FRAME
....

Η επιλογή αυτή παρέχει υποστήριξη για τη λειτουργία FBT. Το DTrace μπορεί να λειτουργήσει και χωρίς αυτήν. Ωστόσο, θα παρέχει περιορισμένη υποστήριξη για function boundary tracing.
====

Όλος ο πηγαίος κώδικας θα πρέπει να μεταγλωττιστεί ξανά με τις επιλογές CTF. Για να γίνει αυτό, μεταγλωττίστε ξανά το FreeBSD χρησιμοποιώντας:

[source,bash]
....
# cd /usr/src

# make WITH_CTF=1 kernel
....

Θα χρειαστεί να επανεκκινήσετε το σύστημα.

Μετά την επανεκκίνηση, και με τον νέο πυρήνα φορτωμένο πλέον στη μνήμη, θα πρέπει να προσθέσετε υποστήριξη για το κέλυφος Korn. Αυτό απαιτείται, καθώς τα εργαλεία DTrace περιλαμβάνουν διάφορα βοηθητικά προγράμματα τα οποία είναι γραμμένα σε `ksh`. Εγκαταστήστε το port package:shells/ksh93[]. Μπορείτε επίσης να εκτελέσετε αυτά τα εργαλεία και μέσω του package:shells/pdksh[] ή του package:shells/mksh[].

Τέλος, ανακτήστε την τρέχουσα σειρά εργαλείων DTrace. Η τελευταία έκδοση διατίθεται στην τοποθεσία http://www.opensolaris.org/os/community/dtrace/dtracetoolkit/[http://www.opensolaris.org/os/community/dtrace/dtracetoolkit/]. Διατίθεται και πρόγραμμα εγκατάστασης, το οποίο δεν είναι ωστόσο απαραίτητο να εκτελέσετε προκειμένου να χρησιμοποιήσετε τα εργαλεία.

[[dtrace-using]]
== Χρησιμοποιώντας το DTrace

Πριν χρησιμοποιήσετε τις λειτουργίες του DTrace, θα πρέπει να υπάρχει η αντίστοιχη συσκευή. Για να φορτώσετε τη συσκευή, θα πρέπει να δώσετε την παρακάτω εντολή:

[source,bash]
....
# kldload dtraceall
....

Θα πρέπει να έχετε πλέον υποστήριξη DTrace. Για να δείτε όλα τα probes, θα πρέπει να εκτελέσετε ως διαχειριστής την παρακάτω εντολή:

[source,bash]
....
# dtrace -l | more
....

Όλη η έξοδος περνάει μέσω του βοηθητικού προγράμματος `more`, διαφορετικά γρήγορα θα υπερχείλιζε την προσωρινή μνήμη της οθόνης. Στο σημείο αυτό, θα πρέπει να θεωρηθεί ότι το DTrace λειτουργεί. Είναι πλέον ώρα να εξετάσουμε αυτή τη σειρά εργαλείων.

Η σειρά των εργαλείων είναι μια συλλογή από έτοιμα scripts που εκτελούνται με το DTrace ώστε να συλλέξουν πληροφορίες σχετικά με το σύστημα. Υπάρχουν scripts που ελέγχουν για ανοικτά αρχεία, τη μνήμη, τη χρήση της CPU και πολλά ακόμα. Κάντε εξαγωγή των scripts με την ακόλουθη εντολή:

[source,bash]
....
# gunzip -c DTraceToolkit* | tar xvf -
....

Μετακινηθείτε στον κατάλογο που τα αποσυμπιέσατε με την εντολή `cd` και αλλάξτε τα δικαιώματα εκτέλεσης σε όλα τα αρχεία, όπως στα αρχεία με τα μικρά γράμματα, σε `755`.

Θα χρειαστεί να γίνουν αλλαγές στο περιεχόμενο σε όλα τα scripts. Όσα περιέχουν το [.filename]#/usr/bin/ksh# θα πρέπει να αλλαχθούν σε [.filename]#/usr/local/bin/ksh#, τα άλλα που περιέχουν το [.filename]#/usr/bin/sh# θα πρέπει να αλλαχθούν σε [.filename]#/bin/sh#, και τέλος αυτά που περιέχουν το [.filename]#/usr/bin/perl# θα πρέπει να αλλαχθούν σε [.filename]#/usr/local/bin/perl#.

[IMPORTANT]
====
Στο σημείο αυτό είναι σημαντικό να υπενθυμίσουμε στον αναγνώστη ότι η υποστήριξη DTrace στο FreeBSD είναι _ατελής_ και πειραματική. Πολλά από αυτά τα scripts δεν θα λειτουργήσουν, καθώς είναι είτε πολύ προσανατολισμένα στο Solaris(TM), ή χρησιμοποιούν probes τα οποία δεν υποστηρίζονται τη δεδομένη στιγμή.
====

Τη στιγμή που γράφονται αυτές οι γραμμές, μόνο δύο scripts από τη σειρά εργαλείων του DTrace υποστηρίζονται πλήρως στο FreeBSD: το [.filename]#hotkernel# και το [.filename]#procsystime#. Αυτά τα δύο θα εξερευνήσουμε στα επόμενα τμήματα αυτής της ενότητας.

Το [.filename]#hotkernel# έχει σχεδιαστεί να αναγνωρίζει ποια συνάρτηση καταναλώνει το μεγαλύτερο χρόνο στον πυρήνα. Εκτελώντας το υπό κανονικές συνθήκες, θα δείτε έξοδο παρόμοια με την παρακάτω:

[source,bash]
....
# ./hotkernel
Sampling... Hit Ctrl-C to end.
....

Ο διαχειριστής του συστήματος θα πρέπει να χρησιμοποιήσει το συνδυασμό πλήκτρων kbd:[Ctrl+C] για να σταματήσει τη διεργασία. Με τον τερματισμό του, το script θα απεικονίσει μια σειρά από συναρτήσεις του πυρήνα και πληροφορίες σχετικά με το χρόνο τους, ταξινομώντας τις σε αύξουσα σειρά ανάλογα με το χρόνο:

[source,bash]
....
kernel`_thread_lock_flags                                   2   0.0%
0xc1097063                                                  2   0.0%
kernel`sched_userret                                        2   0.0%
kernel`kern_select                                          2   0.0%
kernel`generic_copyin                                       3   0.0%
kernel`_mtx_assert                                          3   0.0%
kernel`vm_fault                                             3   0.0%
kernel`sopoll_generic                                       3   0.0%
kernel`fixup_filename                                       4   0.0%
kernel`_isitmyx                                             4   0.0%
kernel`find_instance                                        4   0.0%
kernel`_mtx_unlock_flags                                    5   0.0%
kernel`syscall                                              5   0.0%
kernel`DELAY                                                5   0.0%
0xc108a253                                                  6   0.0%
kernel`witness_lock                                         7   0.0%
kernel`read_aux_data_no_wait                                7   0.0%
kernel`Xint0x80_syscall                                     7   0.0%
kernel`witness_checkorder                                   7   0.0%
kernel`sse2_pagezero                                        8   0.0%
kernel`strncmp                                              9   0.0%
kernel`spinlock_exit                                       10   0.0%
kernel`_mtx_lock_flags                                     11   0.0%
kernel`witness_unlock                                      15   0.0%
kernel`sched_idletd                                       137   0.3%
0xc10981a5                                              42139  99.3%
....

Το script αυτό λειτουργεί επίσης με αρθρώματα του πυρήνα. Για να χρησιμοποιήσετε αυτό το χαρακτηριστικό, εκτελέστε το με την επιλογή `-m`:

[source,bash]
....
# ./hotkernel -m
Sampling... Hit Ctrl-C to end.
^C
MODULE                                                  COUNT   PCNT
0xc107882e                                                  1   0.0%
0xc10e6aa4                                                  1   0.0%
0xc1076983                                                  1   0.0%
0xc109708a                                                  1   0.0%
0xc1075a5d                                                  1   0.0%
0xc1077325                                                  1   0.0%
0xc108a245                                                  1   0.0%
0xc107730d                                                  1   0.0%
0xc1097063                                                  2   0.0%
0xc108a253                                                 73   0.0%
kernel                                                    874   0.4%
0xc10981a5                                             213781  99.6%
....

Το [.filename]#procsystime# script συλλαμβάνει και τυπώνει τον χρόνο των κλήσεων συστήματος για μια συγκεκριμένη διεργασία μέσω του PID ή του ονόματος της. Στο παρακάτω παράδειγμα έχουμε ξεκινήσει μια νέα διεργασία του [.filename]#/bin/csh#. Εκτελέσαμε το [.filename]#procsystime# και το αφήσαμε στην αναμονή καθώς γράφαμε μερικές εντολές στο `csh` που είχαμε ανοίξει. Αυτά είναι τα αποτελέσματα της δοκιμής μας:

[source,bash]
....
# ./procsystime -n csh
Tracing... Hit Ctrl-C to end...
^C

Elapsed Times for processes csh,

         SYSCALL          TIME (ns)
          getpid               6131
       sigreturn               8121
           close              19127
           fcntl              19959
             dup              26955
         setpgid              28070
            stat              31899
       setitimer              40938
           wait4              62717
       sigaction              67372
     sigprocmask             119091
    gettimeofday             183710
           write             263242
          execve             492547
           ioctl             770073
           vfork            3258923
      sigsuspend            6985124
            read         3988049784
....

Όπως φαίνεται, η κλήση του συστήματος για ανάγνωση (`read()`) είναι αυτή που καταναλώνει τον περισσότερο χρόνο σε νανοδευτερόλεπτα, ενώ το λιγότερο τον καταναλώνει η κλήση συστήματος `getpid()`.

[[dtrace-language]]
== Η Γλώσσα D

Η σειρά εργαλείων DTrace, περιλαμβάνει αρκετά scripts γραμμένα στην ειδική γλώσσα του DTrace. Η γλώσσα αυτή ονομάζεται "η γλώσσα D" στην τεκμηρίωση της Sun(TM), και είναι αρκετά όμοια με τη C++. Αναλυτική περιγραφή αυτής της γλώσσας είναι πέρα από τους σκοπούς αυτού του κειμένου. Υπάρχει ενεργή συζήτηση σχετικά με αυτή, στη διεύθυνση http://wikis.sun.com/display/DTrace/Documentation[http://wikis.sun.com/display/DTrace/Documentation].
