# $FreeBSD: www/en/conspectus/stable/2000/06/Makefile,v 1.2 2000/07/03 23:49:29 nik Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	05.sgml
DOCS+=	12.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
