# $FreeBSD: www/en/conspectus/stable/2000/06/Makefile,v 1.1 2000/06/17 13:13:11 nik Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=	05.sgml
DOCS+=	12.sgml

.include "../../../../web.mk"
