# $FreeBSD: www/en/gnome/docs/Makefile,v 1.7 2003/02/07 17:53:24 marcus Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq.sgml
DOCS+=	faq2.sgml
DOCS+=	gnome_porting.sgml
DOCS+=	gnome2_porting.sgml
DOCS+=	porting.sgml
DOCS+=	bugging.sgml
DOCS+=  volunteer.sgml
DOCS+=	22knownissues.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
