# $FreeBSD: www/en/gnome/docs/Makefile,v 1.14 2004/04/04 22:07:06 adamw Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq2.sgml
DOCS+=	faq26.sgml
DOCS+=	gnome_porting.sgml
DOCS+=	gnome1_porting.sgml
DOCS+=	gnome2_porting.sgml
DOCS+=	porting.sgml
DOCS+=	bugging.sgml
DOCS+=  volunteer.sgml
DOCS+=	develfaq.sgml
DOCS+=	example-Makefile.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
