# $FreeBSD: www/en/gnome/docs/Makefile,v 1.22 2006/10/14 16:45:32 marcus Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq2.sgml
DOCS+=	faq28.sgml
DOCS+=	faq210.sgml
DOCS+=	faq212.sgml
DOCS+=	faq214.sgml
DOCS+=	faq216.sgml
DOCS+=	faq218.sgml
DOCS+=	gnome_porting.sgml
DOCS+=	gnome1_porting.sgml
DOCS+=	gnome2_porting.sgml
DOCS+=	porting.sgml
DOCS+=	bugging.sgml
DOCS+=  volunteer.sgml
DOCS+=	develfaq.sgml
DOCS+=	example-Makefile.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
