#
# The FreeBSD Russian Documentation Project
# 
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/vm-design/Makefile,v 1.4 2003/11/08 14:35:28 phantom Exp $
#
# Original revision: 1.4
#

DOC?= article

FORMATS?= html

IMAGES_EN = fig1.eps fig2.eps fig3.eps fig4.eps

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=  article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
