# 
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/vm-design/Makefile,v 1.2 2001/07/25 10:26:34 phantom Exp $
#
# Original revision: 1.1
#

MAINTAINER=andy@FreeBSD.org.ua

DOC?= article

FORMATS?= html

IMAGES=	fig1.eps fig2.eps fig3.eps fig4.eps

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=  article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
