---
title: "FreeBSD Ports について"
sidenav: ports
---

include::shared/ja/urls.adoc[]
include::shared/releases.adoc[]

= FreeBSD Ports について

{{< form-ports >}}

'''''

FreeBSD Ports/Packages Collection は、 ユーザや管理者がアプリケーションのインストールを簡単に行なえる方法を提供します。 現時点で *{numports}* 個の ports が提供されています。

Ports Collection は link:{faq}#current[FreeBSD-CURRENT ブランチ] と link:{faq}#stable[FreeBSD-STABLE ブランチ] の最新のリリースに対応しています。 それより古いリリースには対応しておらず、先端の Ports Collection は正しく動作するかもしれませんし、しないかもしれません。 時間の経過とともに、過去のリリースには存在しない機能を必要とする変更が Ports Collection に加えられるかもしれません。どんな環境でも利用できるように、 最近のリリースでの対応を理由なく取り止めることはないように努めていますが、 やむをえないときもあります。 なお、古いリリースを保守するためのパッチがユーザコミュニティから寄贈された場合は採用されるでしょう。

ここに並べられている各 "`port`" には、 FreeBSD 上でオリジナルのアプリケーションのソースコードをコンパイルし、 実行するために必要なパッチがすべて含まれています。
アプリケーションのインストールは簡単で、port のディレクトリで `make install` と打つだけです。
link:{handbook}ports/#ports-using[ports 階層全体] をインストールし、すべての ports 一覧のフレームワークをダウンロードしたら、何千ものアプリケーションが、すぐに使えるようになります。

各 ports の `Makefile` は自動的に、ローカルディスクやネットワーク経由でアプリケーションのソースコードを入手し、システム上で展開し、パッチをあて、コンパイルします。
問題が起きなければ、あとは `make install` とするだけでアプリケーションをインストールして パッケージシステムへ登録できます。

ほとんどの ports には、あらかじめコンパイルされた `package` が用意されており、すべてをコンパイルする作業や時間を節約できます。
このコンパイルされた port を安全にダウンロードしてインストールするには、man:pkg-install[8] を使用してください。
詳細については、link:{handbook}ports/#pkgng-intro[pkg によるバイナリ package の管理] をご覧ください。
