---
description: 'Diretrizes para marcas registradas no Projeto de Documentação do FreeBSD'
next: books/fdp-primer/see-also
path: /books/fdp-primer/
prev: books/fdp-primer/editor-config/
showBookMenu: 'true'
tags: ["trademarks", "AsciiDoctor", "HTML"]
title: 'Chapter 13. Marcas Registradas'
weight: 14
---

[[trademarks]]
= Marcas Registradas
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 13
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

Para todos os documentos do Projeto de Documentação do FreeBSD, é necessário citar marcas registradas, e isso é dever de todo escritor e colaborador.

[[trademark-symbols]]
== Símbolos de Marca Registrada

Adicione um símbolo de marca registrada (TM), (R) ou outros símbolos na primeira ocorrência do nome da empresa ou do software e sempre ao usar logotipos. Além disso, escreva o nome da empresa ou do software seguindo suas diretrizes de marca registrada.

Em caso de dúvida, pesquise a empresa na Internet ou no website do software, além do link:https://www.uspto.gov/trademarks[site da United States Patent and Trademark Office].

[[trademark-citing]]
== Citação de Marca Registrada

É costume citar marcas registradas em documentação técnica, e o Projeto de Documentação do FreeBSD fornece um template para isso, o que também evita a duplicação de marcas registradas nos documentos.

Primeiro, verifique o https://cgit.freebsd.org/doc/tree/documentation/themes/beastie/i18n/en.toml#n197[template] do projeto pela marca registrada e adicione-a à tag de marcas registradas na Seção `Front Matter` do documento, que fica no início de cada documento.

O seguinte é um exemplo de `Front Matter` do artigo extref:{contributing}[Contribuindo com o FreeBSD]:

....
---
title: Contributing to FreeBSD
authors:
  - author: Jordan Hubbard
  - author: Sam Lawrance
  - author: Mark Linimon
description: How to contribute to the FreeBSD Project
trademarks: ["freebsd", "ieee", "general"]
weight: 15
tags: ["Contributing", "FreeBSD", "Non-Programmer Tasks", "Programmer Tasks"]
---
....

As tags de marca registrada `freebsd`, `ieee` e `general` serão renderizadas automaticamente ao compilar o documento, ficando desta forma:

....
FreeBSD is a registered trademark of the FreeBSD Foundation.

IEEE, POSIX, and 802 are registered trademarks of Institute of Electrical and Electronics Engineers, Inc. in the United States.

Many of the designations used by manufacturers and sellers to distinguish their products are claimed as trademarks. Where those designations appear in this document, and the FreeBSD Project was aware of the trademark claim, the designations have been followed by the “™” or the “®” symbol.
....

Caso a marca não esteja presente no template do projeto, ela deve ser submetida. Qualquer desenvolvedor ou colaborador pode atualizar as marcas registradas.

As tags de marca registrada `freebsd` e `general` geralmente estão presentes em todos os documentos.
