# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

SUBDIR=	11

.include "${WEB_PREFIX}/share/mk/web.site.mk"
