# $FreeBSD: www/en/prstats/Makefile,v 1.1 2001/10/29 02:17:31 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml
SUBDIR+= ../../tools/prstats

.include "${WEB_PREFIX}/share/mk/web.site.mk"
