---
title: Μέρος I. Ξεκινώντας με το FreeBSD
prev: books/handbook/preface
next: books/handbook/introduction
---

[[getting-started]]
= Ξεκινώντας με το FreeBSD

Αυτό το μέρος του Εγχειριδίου του FreeBSD είναι για τους χρήστες και τους διαχειριστές συστημάτων που δεν έχουν ήδη μεγάλη εμπειρία με το FreeBSD. Τα κεφάλαια που ακολουθούν:

* Είναι εισαγωγικά για το FreeBSD
* Σας καθοδηγούν κατά τη διάρκεια της διαδικασίας εγκατάστασης
* Σας εισάγουν στις βασικές έννοιες του UNIX(R)
* Περιγράφουν τη διαδικασία εγκατάστασης της πληθώρας εφαρμογών που είναι διαθέσιμες στο FreeBSD
* Σας εισάγουν στο γραφικό περιβάλλον του UNIX(R), το σύστημα Χ, και σας καθοδηγούν σχετικά με τις αρχικές ρυθμίσεις ενός γραφικού περιβάλλοντος εργασίας, με το οποίο μπορείτε να είστε ακόμα πιο παραγωγικοί

Σε αυτό το τμήμα του βιβλίου, έχουμε προσπαθήσει να μειώσουμε στο ελάχιστο τις αναφορές σε τμήματα ή κεφάλαια του Εγχειριδίου τα οποία δεν έχετε ήδη διαβάσει. Αυτό αποσκοπεί στο να γίνει πιο εύκολη η ανάγνωση του τμήματος αυτού του Εγχειριδίου από την αρχή μέχρι και το τέλος, χωρίς να απαιτείται να ψάχνετε συνεχώς τα επόμενα ή προηγούμενα τμήματα.

include::content/el/books/handbook/toc-1.adoc[]
