#
# The FreeBSD Simplified Chinese Project
# Original Revision: 1.2
#
# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   fixed.css fixed_large.css global.css layout.css navigation.css text.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
