---
title: "FreeBSD 14.0-RELEASE Errata"
sidenav: download
---

:release: 14.0-RELEASE
:releaseNext: 14.1-RELEASE
:releaseBranch: 14-STABLE

= FreeBSD {release} Errata

== Abstract

This document lists errata items for FreeBSD {release}, containing significant information discovered after the release or too late in the release cycle to be otherwise included in the release documentation.
This information includes security advisories, as well as news relating to the software or documentation that could affect its operation or usability.
An up-to-date version of this document should always be consulted before installing this version of FreeBSD.

This errata document for FreeBSD {release} will be maintained until the release of FreeBSD {releaseNext}.

== Table of Contents

* <<intro,Introduction>>
* <<security,Security Advisories>>
* <<errata,Errata Notices>>
* <<open-issues,Open Issues>>
* <<late-news,Late-Breaking News>>
* <<erratas-announcement,Erratas in Announcement>>

[[intro]]
== Introduction

This errata document contains "late-breaking news" about FreeBSD {release}.
Before installing this version, it is important to consult this document to learn about any post-release discoveries or problems that may already have been found and fixed.

Any version of this errata document actually distributed with the release (for example, on a CDROM distribution) will be out of date by definition, but other copies are kept updated on the Internet and should be consulted as the "current errata" for this release.
These other copies of the errata are located at https://www.FreeBSD.org/releases/, plus any sites which keep up-to-date mirrors of this location.

Source and binary snapshots of FreeBSD {releaseBranch} also contain up-to-date copies of this document (as of the time of the snapshot).

For a list of all FreeBSD CERT security advisories, see https://www.FreeBSD.org/security/.

[[security]]
== Security Advisories

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Advisory |Date |Topic
|===

[[errata]]
== Errata Notices

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Errata |Date |Topic
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-EN-23:15.sanitizer.asc[FreeBSD-EN-23:15.sanitizer] |1 December 2023 |Clang sanitizer failure with ASLR enabled
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-EN-23:16.openzfs.asc[FreeBSD-EN-23:16.openzfs] |1 December 2023 |OpenZFS data corruption
|===

[[open-issues]]
== Open Issues

No open issues.

[[late-news]]
== Late-Breaking News

No late-breaking news.
