---
description: '이 챕터는 FreeBSD에서 그래픽 환경을 제공하는 Xorg(X 윈도우 시스템)를 설치하고 설정하는 방법에 대해 설명합니다'
next: books/handbook/wayland
part: '파트 I. 시작하기'
path: /books/handbook/
prev: books/handbook/ports
showBookMenu: 'true'
tags: ["X11", "Xorg", "TrueType", "Intel", "AMD", "NVIDIA", "Anti-Aliased", "VESA", "SCFB"]
title: '챕터 5. X 윈도우 시스템'
weight: 7
---

[[x11]]
= X 윈도우 시스템
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 5
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/x11/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[x11-synopsis]]
== 요약

bsdinstall을 사용하는 FreeBSD의 설치과정은 자동으로 그래픽 사용자 인터페이스를 설치하지 않습니다. 이 챕터는 그래픽 환경을 제공하는 오픈 소스 X 윈도우 시스템인 Xorg의 설치와 설정에 대해 설명합니다. 그리고 그래픽 환경과 윈도우 관리자를 찾아 설치하는 법을 설명합니다.

이 챕터를 읽기 전에 여러분은:

* crossref:ports[ports,Installing Applications: Packages and Ports]에서 설명하고 있는 서드파티 소프트웨어를 추가로 설치하는 방법.

이 챕터를 읽고 나면, 여러분은:

* X Window 시스템의 다양한 구성 요소와 이들이 상호 운용되는 방식.
* Xorg의 설치방법과 설정방법.
* Xorg에서 트루타입 폰트(TrueType(R) font)를 사용하는 방법.
* 그래픽 환경에서 로그인하도록 시스템을 설정하는 방법(XDM).

[[x-install]]
== Xorg 설치하기

FreeBSD에서 Xorg는 패키지 또는 포트(Port)로 설치할 수 있습니다.

바이너리 메타 패키지는 빠르게 설치할 수 있지만 사용자 지정 옵션이 적습니다:

[source, shell]
....
# pkg install xorg
....

이 두 가지 설치 방법 중 하나를 선택하면 전체 Xorg 시스템이 설치됩니다.

현재 사용자는 `video` 그룹의 구성원이어야 합니다. `video` 그룹에 사용자를 추가하려면 다음 명령을 실행합니다:

[source, shell]
....
# pw groupmod video -m username
....

[TIP]
====
숙련된 사용자에게 적합한 X 시스템의 더 작은 버전은 package:x11/xorg-minimal[]에서 다운 받을 수 있습니다. 대부분의 문서, 라이브러리 및 애플리케이션은 설치되지 않습니다. 일부 애플리케이션이 작동하려면 이러한 추가 구성 요소가 필요합니다.
====

[TIP]
====
비디오 카드, 모니터 및 입력 장치는 자동으로 감지되므로 수동 구성이 필요하지 않습니다. 자동 구성에 실패하지 않는 한 `xorg.conf`를 만들거나 `-configure` 단계를 실행하지 마세요.
====

[[x-graphic-card-drivers]]
== 그래픽 카드 드라이버

다음 표는 FreeBSD에서 지원하는 다양한 그래픽 카드, 설치해야 하는 패키지 및 해당 모듈을 보여줍니다.

.그래픽 카드 패키지
[options="header", cols="1,1,1,1"]
|===
| Brand | Type | Package | Module

| Intel(R)
| Open Source
| drm-kmod
| `i915kms`

| AMD(R)
| Open Source
| drm-kmod
| `amdgpu` and `radeonkms`

| NVIDIA(R)
| Proprietary
| nvidia-driver
| `nvidia` or `nvidia-modeset`

| VESA
| Open Source
| xf86-video-vesa
| vesa

| SCFB
| Open Source
| xf86-video-scfb
| scfb

| Virtualbox
| Open Source
| virtualbox-ose-additions
| Virtualbox OSE additions include the `vboxvideo` driver.

| VMware(R)
| Open Source
| xf86-video-vmware
| vmwgfx

|===

다음 명령을 사용하여 시스템에 어떤 그래픽 카드가 설치되어 있는지 식별할 수 있습니다:

[source, shell]
....
% pciconf -lv|grep -B4 VGA
....

출력은 다음과 비슷해야 합니다:

[.programlisting]
....
vgapci0@pci0:0:2:0:     class=0x030000 rev=0x07 hdr=0x00 vendor=0x8086 device=0x2a42 subvendor=0x17aa subdevice=0x20e4
    vendor     = 'Intel Corporation'
    device     = 'Mobile 4 Series Chipset Integrated Graphics Controller'
    class      = display
    subclass   = VGA
....

[WARNING]
====
그래픽 카드가 Intel(R), AMD(R) 또는 NVIDIA(R) 드라이버에서 지원되지 않는 경우 VESA 또는 SCFB 모듈을 사용해야 합니다. BIOS 모드로 부팅할 때는 VESA 모듈을 사용해야 하며, UEFI 모드로 부팅할 때는 SCFB 모듈을 사용해야 합니다.

이 명령은 부팅 모드를 확인하는 데 사용할 수 있습니다:

[source, shell]
....
% sysctl machdep.bootmethod
....

출력은 다음과 비슷해야 합니다:

[.programlisting]
....
machdep.bootmethod: BIOS
....
====

[[x-configuration-intel]]
=== Intel(R)

인텔(R) 그래픽은 인텔(R) CPU와 동일한 다이에 통합된 그래픽 칩 클래스를 말합니다. Wikipedia의 link:https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units[여러 세대의 인텔 HD 그래픽에 사용된 변형 및 이름에 대한 좋은 개요]를 확인하세요.

package:graphics/drm-kmod[] 패키지는 인텔(R) 그래픽 카드와 함께 사용할 수 있는 다양한 커널 모듈을 간접적으로 제공합니다. 인텔(R) 드라이버는 다음 명령을 실행하여 설치할 수 있습니다:

[source, shell]
....
# pkg install drm-kmod
....

그런 다음, 다음 명령을 실행하여 `/etc/rc.conf` 파일에 모듈을 추가합니다:

[source, shell]
....
# sysrc kld_list+=i915kms
....

[TIP]
====
CPU 사용량이 높거나 HD 동영상에서 과도한 테어링이 발생하는 경우 package:multimedia/libva-intel-driver[]를 설치하면 도움이 될 수 있습니다. 패키지를 설치하려면 다음 명령을 실행하세요:

[source, shell]
....
# pkg install libva-intel-driver mesa-libs mesa-dri
....
====

[[x-configuration-amd]]
=== AMD(R)

package:graphics/drm-kmod[] 패키지는 AMD(R) 그래픽 카드와 함께 사용할 수 있는 다양한 커널 모듈을 간접적으로 제공합니다. 하드웨어의 세대에 따라 `amdgpu`와 `radeonkms` 모듈을 사용할 수 있습니다. FreeBSD 프로젝트는 https://wiki.freebsd.org/Graphics/AMD-GPU-Matrix[AMD 그래픽 지원 매트릭스를 이용해 필수적으로 사용해야 할 드라이버 확인하기] 링크를 관리합니다.

AMD(R) 드라이버는 다음 명령을 실행하여 설치할 수 있습니다:

[source, shell]
....
# pkg install drm-kmod
....

HD-7000 또는 타히티 그래픽 카드 후속모델의 경우 다음 명령을 실행하여 `/etc/rc.conf` 파일에 모듈을 추가합니다:

[source, shell]
....
# sysrc kld_list+=amdgpu
....

구형 그래픽 카드(HD-7000 이전 또는 타히티 이전)의 경우 다음 명령을 실행하여 `/etc/rc.conf` 파일에 모듈을 추가합니다:

[source, shell]
....
# sysrc kld_list+=radeonkms
....

[[x-configuration-nvidia]]
=== NVIDIA(R)

FreeBSD는 다양한 버전의 독점적인 NVIDIA(R) 드라이버를 지원합니다. 최신 그래픽 카드 사용자는 package:x11/nvidia-driver[] 패키지를 설치해야 합니다. 구형 카드를 사용하시는 분들은 아래에서 어떤 버전이 지원되는지 확인하셔야 합니다.

.NVIDIA(R) 드라이버의 지원버전
[options="header", cols="1,1"]
|===
| Package | Supported hardware

| x11/nvidia-driver-304
| link:https://www.nvidia.com/Download/driverResults.aspx/123712/en-us/[supported hardware]

| x11/nvidia-driver-340
| link:https://www.nvidia.com/Download/driverResults.aspx/156167/en-us/[supported hardware]

| x11/nvidia-driver-390
| link:https://www.nvidia.com/Download/driverResults.aspx/191122/en-us/[supported hardware]

| x11/nvidia-driver-470
| link:https://www.nvidia.com/Download/driverResults.aspx/191234/en-us/[supported hardware]

| x11/nvidia-driver
| link:https://www.nvidia.com/Download/driverResults.aspx/187164/en-us/[supported hardware]

|===

[WARNING]
====
NVIDIA(R) 그래픽 드라이버 버전 304(nvidia-driver-304)는 xorg-server 1.20 이상을 지원하지 않습니다.
====

다음 명령을 실행하여 최신 NVIDIA(R) 드라이버를 설치할 수 있습니다:

[source, shell]
....
# pkg install nvidia-driver
....

그런 다음, 다음 명령을 실행하여 `/etc/rc.conf` 파일에 모듈을 추가합니다:

[source, shell]
....
# sysrc kld_list+=nvidia-modeset
....

[WARNING]
====
`nvidia` 드라이버는 x11/nvidia-driver-304 또는 x11/nvidia-driver-340 패키지가 설치되어 있는 경우 사용해야 합니다.

[source, shell]
....
# sysrc kld_list+=nvidia
....
====

[[x-config]]
== Xorg 구성

Xorg는 대부분의 일반적인 비디오 카드, 키보드, 포인팅 장치를 지원합니다.

[WARNING]
====
비디오 카드, 모니터 및 입력 장치는 자동으로 감지되므로 수동 구성이 필요하지 않습니다. 자동 구성에 실패하지 않는 한 [.filename]#xorg.conf#를 만들거나 `Xorg -configure` 단계를 실행하지 마세요.
====

[[x-config-files]]
=== 구성 파일

Xorg는 여러 디렉터리에서 구성 파일을 찾습니다. [.filename]#/usr/local/etc/X11/#은 FreeBSD에서 이러한 파일을 위한 *권장* 디렉터리입니다. 이 디렉터리를 사용하면 애플리케이션 파일을 운영 체제 파일과 분리하여 보관할 수 있습니다.

[[x-config-files-single-or-multi]]
=== 단일 또는 다중 파일

기존의 단일 [.filename]#xorg.conf#보다 각각 특정 설정을 구성하는 여러 파일을 사용하는 것이 더 쉽습니다. 이러한 파일은 [.filename]#/usr/local/etc/X11/xorg.conf.d/# 의 하위 디렉터리에 저장됩니다.

[TIP]
====
기존의 단일 [.filename]#xorg.conf#는 여전히 작동되지만 [.filename]#/usr/local/etc/X11/xorg.conf.d/# 하위 디렉터리에 있는 여러 파일만큼 명확하거나 유연하지 않습니다.
====

[[x-config-video-cards]]
=== 비디오 카드

그래픽 카드를 위한 드라이버는 [.filename]#/usr/local/etc/X11/xorg.conf.d/# 디렉터리에 지정할 수 있습니다.

구성 파일에서 인텔(R) 드라이버를 구성하려면:

[[x-config-video-cards-file-intel]]
.파일에서 인텔(R) 비디오 드라이버 선택
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-intel.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "intel"
EndSection
....
====

구성 파일에서 AMD(R) 드라이버를 구성하려면:

[[x-config-video-cards-file-amd]]
.파일에서 AMD(R) 비디오 드라이버 선택
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-radeon.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "radeon"
EndSection
....
====

구성 파일에서 NVIDIA(R) 드라이버를 구성하려면:

[[x-config-video-cards-file-nvidia]]
.파일에서 NVIDIA(R) 비디오 드라이버 선택
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-nvidia.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "nvidia"
EndSection
....
====

구성 파일에서 `VESA` 드라이버를 구성하려면:

[[x-config-video-cards-file-vesa]]
.파일에서 VESA 비디오 드라이버를 선택
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-vesa.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "vesa"
EndSection
....
====

구성 파일에서 SCFB 드라이버를 구성하려면:

[[x-config-video-cards-file-sfcb]]
.파일에서 SCFB 비디오 드라이버를 선택
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-scfb.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "scfb"
EndSection
....
====

비디오 카드가 두 개 이상 있는 경우 `BusID`를 추가할 수 있습니다. 비디오 카드 버스 ``ID``의 목록은 다음을 실행하여 확인할 수 있습니다:

[source, shell]
....
% pciconf -lv | grep -B3 display
....

출력은 다음과 비슷해야 합니다:

[.programlisting]
....
vgapci0@pci0:0:2:0:     class=0x030000 rev=0x07 hdr=0x00 vendor=0x8086 device=0x2a42 subvendor=0x17aa subdevice=0x20e4
    vendor     = 'Intel Corporation'
    device     = 'Mobile 4 Series Chipset Integrated Graphics Controller'
    class      = display
--
vgapci1@pci0:0:2:1:     class=0x038000 rev=0x07 hdr=0x00 vendor=0x8086 device=0x2a43 subvendor=0x17aa subdevice=0x20e4
    vendor     = 'Intel Corporation'
    device     = 'Mobile 4 Series Chipset Integrated Graphics Controller'
    class      = display
....

[[x-config-video-cards-file-multiple]]
.파일에서 인텔(R) 비디오 드라이버와 NVIDIA(R) 비디오 드라이버를 선택
[example]
====

[.filename]#/usr/local/etc/X11/xorg.conf.d/20-drivers.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "intel"
	BusID     "pci0:0:2:0"
EndSection

Section "Device"
	Identifier "Card0"
	Driver     "nvidia"
	BusID     "pci0:0:2:1"
EndSection
....
====

[[x-config-monitors]]
=== 모니터

대부분의 모니터는 확장 디스플레이 식별 데이터 표준(`EDID`)을 지원합니다. Xorg는 `EDID`를 사용하여 모니터와 통신하고 지원되는 해상도 및 재생률(refresh rates)을 감지합니다. 그런 다음 해당 모니터에 사용할 가장 적절한 설정 조합을 선택합니다.

모니터에서 지원되는 다른 해상도로 변경하고 싶은 경우, 구성 파일에서 원하는 해상도를 설정하거나 X 서버를 시작한 후 man:xrandr[1]를 사용하여 선택할 수 있습니다.

[[x-config-monitors-xrandr]]
==== RandR 사용하기 (리사이징과 회전)

매개변수 없이 man:xrandr[1]를 실행하면 비디오 출력 및 감지된 모니터 모드 목록을 확인할 수 있습니다:

[source, shell]
....
% xrandr
....

출력은 다음과 비슷해야 합니다:

[.programlisting]
....
Screen 0: minimum 320 x 200, current 2560 x 960, maximum 8192 x 8192
LVDS-1 connected 1280x800+0+0 (normal left inverted right x axis y axis) 261mm x 163mm
   1280x800      59.99*+  59.81    59.91    50.00  
   1280x720      59.86    59.74  
   1024x768      60.00  
   1024x576      59.90    59.82  
   960x540       59.63    59.82  
   800x600       60.32    56.25  
   864x486       59.92    59.57  
   640x480       59.94  
   720x405       59.51    58.99  
   640x360       59.84    59.32  
VGA-1 connected primary 1280x960+1280+0 (normal left inverted right x axis y axis) 410mm x 257mm
   1280x1024     75.02    60.02  
   1440x900      74.98    60.07  
   1280x960      60.00* 
   1280x800      74.93    59.81  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
....

이 메세지는 약 60Hz의 재생률로 1920x1200픽셀의 화면 해상도를 표시하기 위해 `VGA-1` 출력이 사용되고 있음을 보여줍니다. `LVDS-1`은 약 60Hz의 주사율로 1280x800 픽셀의 화면 해상도를 표시하기 위해 보조 모니터로 사용되고 있습니다. `HDMI-1`, `HDMI-2`, `DP-1`, `DP-2` 및 `DP-3` 커넥터에는 모니터가 연결되어 있지 않습니다.

다른 디스플레이 모드는 man:xrandr[1]로 선택할 수 있습니다. 예를 들어, 60Hz에서 1280x1024로 전환합니다:

[source, shell]
....
% xrandr --output LVDS-1 --mode 1280x720 --rate 60
....

[[x-config-monitors-files]]
==== Xorg 구성파일 사용하기

모니터 구성은 구성 파일에서도 설정할 수 있습니다.

구성 파일에서 화면 해상도를 1024x768로 설정하려면 다음과 같이 하세요:

.파일에서 화면 해상도 설정
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/10-monitor.conf#

[.programlisting]
....
Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	SubSection "Display"
	Modes      "1024x768"
	EndSubSection
EndSection
....
====

[[x-config-input]]
=== 입력 장치

Xorg는 package:x11/libinput[]을 통해 대부분의 입력 장치를 지원합니다.

[TIP]
====
일부 데스크톱 환경(예: KDE Plasma)에서는 이러한 매개변수를 설정할 수 있는 그래픽 UI를 제공합니다. 수동 구성 편집을 사용하기 전에 해당되는지 확인하세요.
====

[[x-config-input-keyboard-layout]]
이 예에서 키보드 레이아웃을 구성하기 위해:

.키보드 레이아웃 설정
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/00-keyboard.conf#

[.programlisting]
....
Section "InputClass"
        Identifier "Keyboard1"
        MatchIsKeyboard "on"
        Option "XkbLayout" "es, fr"
        Option "XkbModel" "pc104"
        Option "XkbVariant" ",qwerty"
        Option "XkbOptions" "grp:win_space_toggle"
EndSection
....
====

[[x-fonts]]
== Xorg에서 글꼴 사용

Xorg와 함께 제공되는 기본 글꼴은 일반적인 데스크톱 퍼블리싱 애플리케이션에 적합하지 않습니다. 큰 프레젠테이션 글꼴은 들쭉날쭉하고 비전문적으로 보이며, 작은 글꼴은 거의 알아볼 수 없습니다. 하지만 Xorg와 함께 쉽게 사용할 수 있는 고품질의 무료 Type1(PostScript(R)) 글꼴이 몇 가지 있습니다.

[[type1]]
=== Type1 글꼴

URW 글꼴 컬렉션(package:x11-fonts/urwfonts[])에는 표준 Type1 글꼴(Times Roman(TM), Helvetica(TM), Palatino(TM) 및 기타)의 고품질 버전이 포함되어 있습니다. 프리폰트 컬렉션(package:x11-fonts/freefonts[])에는 더 많은 글꼴이 포함되어 있지만, 대부분은 Gimp와 같은 그래픽 소프트웨어에서 사용하기 위한 것으로 화면 글꼴로 사용하기에는 적합하지 않습니다. 또한 최소한의 노력으로 TrueType(R) 글꼴을 사용하도록 Xorg를 구성할 수 있습니다. 이에 대한 자세한 내용은 man:X[7] 매뉴얼 페이지 또는 <<truetype>>을 참조하세요.

바이너리 패키지에서 위의 Type1 글꼴 컬렉션을 설치하려면 다음 명령을 실행합니다:

[source, shell]
....
# pkg install urwfonts
....

무료 글꼴이나 다른 컬렉션도 마찬가지입니다. X 서버가 이러한 글꼴을 감지하도록 하려면 X 서버 구성 파일([.filename]#/usr/local/etc/X11/xorg.conf.d/90-fonts.conf#)에 다음과 같이 적절한 내용을 추가합니다:

[.programlisting]
....
Section "Files"
  FontPath "/usr/local/share/fonts/urwfonts/"
EndSection
....

또는 X 세션의 명령줄에서 실행합니다:

[source, shell]
....
% xset fp+ /usr/local/share/fonts/urwfonts
% xset fp rehash
....

이 방법은 잘 작동하지만 시작 파일에 추가하지 않으면 X 세션이 닫히면 소실됩니다(일반 `startx` 세션의 경우 [.filename]#~/.xinitrc# 또는 XDM과 같은 그래픽 로그인 관리자를 통해 로그인하는 경우 [.filename]#~/.xsession# ). 세 번째 방법은 <<antialias>>에 설명된 대로 새로운 [.filename]#/usr/local/etc/fonts/local.conf#를 사용하는 것입니다.

[[truetype]]
=== TrueType(R) 글꼴

Xorg에는 TrueType(R) 글꼴 렌더링 기능이 내장되어 있습니다. 이 기능을 활성화할 수 있는 두 가지 모듈이 있습니다. 이 예제에서는 다른 글꼴 렌더링 백엔드와 더 일관성이 있기 때문에 freetype 모듈을 사용했습니다. Freetype 모듈을 활성화하려면 [.filename]#/usr/local/etc/X11/xorg.conf.d/90-fonts.conf#의 `”Module”` 섹션에 다음 줄을 추가하기만 하면 됩니다.

[.programlisting]
....
Load  "freetype"
....

이제 TrueType(R) 글꼴을 위한 디렉터리(예: [.filename]#/usr/local/share/fonts/TrueType#)를 만들고 모든 TrueType(R) 글꼴을 이 디렉터리에 복사합니다. TrueType(R) 글꼴은 Apple(R) Mac(R)에서 직접 가져올 수 없으며, Xorg에서 사용하려면 UNIX(R)/MS-DOS(R)/Windows(R) 형식이어야 한다는 점에 유의하세요. 파일을 이 디렉터리에 복사한 후 mkfontscale을 사용하여 [.filename]#fonts.dir#을 생성하고 X 폰트 렌더러가 새 파일이 설치되었음을 알 수 있도록 합니다. `mkfontscale`은 패키지로 설치할 수 있습니다:

[source, shell]
....
# pkg install mkfontscale
....

그런 다음 디렉터리에 X 글꼴 파일의 색인을 만듭니다:

[source, shell]
....
# cd /usr/local/share/fonts/TrueType
# mkfontscale
....

이제 글꼴 경로에 TrueType(R) 디렉터리를 추가합니다. 이는 <<type1>>에서 설명한 것과 동일합니다:

[source, shell]
....
% xset fp+ /usr/local/share/fonts/TrueType
% xset fp rehash
....

또는 [.filename]#xorg.conf#에 `FontPath` 줄을 추가합니다.

이제 Gimp, LibreOffice 및 기타 모든 X 응용 프로그램에서 시스템에 설치된 TrueType(R) 글꼴을 인식할 수 있습니다. 이제 매우 작은 글꼴(웹 페이지의 고해상도 디스플레이에 있는 텍스트와 같이)과 매우 큰 글꼴(LibreOffice 안에서)이 훨씬 더 보기 좋아질 것입니다.

[[antialias]]
=== 안티 엘리어싱(anti-aliasing) 글꼴

[.filename]#/usr/local/share/fonts/# 및 [.filename]#~/.fonts/# 에 있는 Xorg의 모든 글꼴은 Xft-aware 응용 프로그램에 의해 앤티 앨리어싱(anti-aliasing)을 자동으로 사용할 수 있습니다. KDE, GNOME, Firefox 등 대부분의 최신 애플리케이션은 Xft-aware가 포함되어 있습니다.

앤티앨리어싱이 적용되는 글꼴을 제어하거나 앤티앨리어싱 속성을 구성하려면 [.filename]#/usr/local/etc/fonts/local.conf# 파일을 생성(또는 이미 존재하는 경우 편집)하세요. 이 파일을 사용하여 Xft 글꼴 시스템의 여러 고급 기능을 조정할 수 있으며, 이 섹션에서는 몇 가지 간단한 기능만을 설명합니다. 자세한 내용은 man:fonts-conf[5]를 참조하세요.

이 파일은 XML 형식이어야 합니다. 대소문자에 주의하고 모든 태그가 올바르게 닫혀 있는지 확인하세요. 파일은 일반적인 XML 헤더로 시작하여 DOCTYPE 정의와 `<fontconfig>` 태그가 이어집니다:

[.programlisting]
....
<?xml version="1.0"?>
      <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
      <fontconfig>
....

앞서 설명한 것처럼 [.filename]#/usr/local/share/fonts/# 및 [.filename]#~/.fonts/#에 있는 모든 글꼴은 이미 Xft-aware 애플리케이션에서 사용할 수 있도록 설정되어 있습니다. 이 두 디렉터리 트리 외에 다른 디렉터리를 추가하려면 [.filename]#/usr/local/etc/fonts/local.conf#에 다음과 같이 한 줄을 추가합니다:

[.programlisting]
....
<dir>/path/to/my/fonts</dir>
....

새 글꼴, 특히 새 글꼴 디렉터리를 추가한 후에는 글꼴 캐시를 다시 빌드합니다:

[source, shell]
....
# fc-cache -f
....

앤티 앨리어싱은 테두리를 약간 흐릿하게 만들어 매우 작은 텍스트의 가독성을 높이고 큰 텍스트의 “계단현상”을 제거하지만 일반 텍스트에 적용하면 눈의 피로를 유발할 수 있습니다. 14포인트보다 작은 글꼴 크기를 앤티 앨리어싱에서 제외하려면 다음 줄을 포함하세요:

[.programlisting]
....
	<match target="font">
	    <test name="size" compare="less">
		<double>14</double>
	    </test>
	    <edit name="antialias" mode="assign">
		<bool>false</bool>
	    </edit>
	</match>
	<match target="font">
	    <test name="pixelsize" compare="less" qual="any">
		<double>14</double>
	    </test>
	    <edit mode="assign" name="antialias">
		<bool>false</bool>
	    </edit>
	</match>
....

일부 단일 간격 글꼴의 간격도 앤티 앨리어싱을 사용하면 부적절할 수 있습니다. 이는 특히 KDE에서 발생하는 문제인 것 같습니다. 한 가지 가능한 해결 방법은 이러한 글꼴의 간격을 100으로 강제 설정하는 것입니다. 이 줄을 추가합니다:

[.programlisting]
....
	<match target="pattern" name="family">
	   <test qual="any" name="family">
	       <string>fixed</string>
	   </test>
	   <edit name="family" mode="assign">
	       <string>mono</string>
	   </edit>
	</match>
	<match target="pattern" name="family">
	    <test qual="any" name="family">
		<string>console</string>
	    </test>
	    <edit name="family" mode="assign">
		<string>mono</string>
	    </edit>
	</match>
....

(이렇게 하면 고정 글꼴의 다른 일반적인 이름은 `”mono”`로 별칭이 지정됨)그리고 나서 다음 추가합니다:

[.programlisting]
....
	<match target="pattern" name="family">
	     <test qual="any" name="family">
		 <string>mono</string>
	     </test>
	     <edit name="spacing" mode="assign">
		 <int>100</int>
	     </edit>
	 </match>
....

Helvetica와 같은 몇몇 글꼴은 앤티 앨리어싱 시 문제가 발생할 수 있습니다. 일반적으로 세로로 반으로 잘린 듯한 글꼴로 나타납니다. 최악의 경우 애플리케이션이 충돌할 수 있습니다. 이를 방지하려면 [.filename]#local.conf#에 다음을 추가하세요:

[.programlisting]
....
	<match target="pattern" name="family">
	     <test qual="any" name="family">
		 <string>Helvetica</string>
	     </test>
	     <edit name="family" mode="assign">
		 <string>sans-serif</string>
	     </edit>
	 </match>
....

[.filename]#local.conf#를 수정한 후 `</fontconfig>` 태그로 파일을 끝내야 합니다. 이렇게 하지 않으면 변경 사항이 무시됩니다.

사용자는 자신만의 [.filename]#~/.config/fontconfig/fonts.conf#을 생성하여 개인화된 설정을 추가할 수 있습니다. 이 파일은 위에서 설명한 것과 동일한 `XML` 형식을 사용합니다.

마지막으로 LCD 화면의 경우 서브 픽셀 샘플링이 필요할 수 있습니다. 이는 기본적으로 (수평으로 분리된) 빨강, 녹색 및 파랑 구성 요소를 개별적으로 처리하여 수평 해상도를 향상시키며, 그 결과는 극적으로 달라질 수 있습니다. 이 기능을 활성화하려면 [.filename]#local.conf# 아무데나 다음 내용을 추가하세요:

[.programlisting]
....
	 <match target="font">
	     <test qual="all" name="rgba">
		 <const>unknown</const>
	     </test>
	     <edit name="rgba" mode="assign">
		 <const>rgb</const>
	     </edit>
	 </match>
....

[NOTE]
====
디스플레이 종류에 따라 'RGB'를 ‘BGR', 'VRGB' 또는 'VBGR'로 변경해야 할 수 있으므로 실험을 통해 어떤 것이 가장 효과적인지 확인하세요.
====

FreeBSD에서 글꼴을 설치하고 구성하는 방법에 대한 자세한 내용은 문서 link:{fonts}[글꼴 및 FreeBSD]를 참조하세요.
