---
description: '이 챕터는 FreeBSD에서 그래픽 환경을 제공하는 Xorg(X 윈도우 시스템)를 설치하고 설정하는 방법에 대해 설명합니다'
next: books/handbook/wayland
part: '파트 I. 시작하기'
path: /books/handbook/
prev: books/handbook/ports
showBookMenu: 'true'
tags: ["X11", "Xorg", "TrueType", "Intel", "AMD", "NVIDIA", "Anti-Aliased", "VESA", "SCFB"]
title: '챕터 5. X 윈도우 시스템'
weight: 7
---

[[x11]]
= X 윈도우 시스템
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 5
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/x11/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[x11-synopsis]]
== 요약

bsdinstall을 사용하는 FreeBSD의 설치과정은 자동으로 그래픽 사용자 인터페이스를 설치하지 않습니다. 이 챕터는 그래픽 환경을 제공하는 오픈 소스 X 윈도우 시스템인 Xorg의 설치와 설정에 대해 설명합니다. 그리고 그래픽 환경과 윈도우 관리자를 찾아 설치하는 법을 설명합니다.

이 챕터를 읽기 전에 여러분은 다음 사항을 알고 있어야 합니다:

* crossref:ports[ports,Installing Applications: Packages and Ports]에서 설명하고 있는 서드파티 소프트웨어를 추가로 설치하는 방법.

이 챕터를 읽고 나면, 여러분은:

* X Window 시스템의 다양한 구성 요소와 이들이 상호 운용되는 방식.
* Xorg의 설치방법과 설정방법.
* Xorg에서 트루타입 폰트(TrueType(R) font)를 사용하는 방법.
* 그래픽 환경에서 로그인하도록 시스템을 설정하는 방법(XDM).

[[x-install]]
== Xorg 설치

FreeBSD에서 Xorg는 패키지 또는 포트(Port)로 설치할 수 있습니다.

The binary meta package can be installed quickly but with fewer options for customization:

[source, shell]
....
# pkg install xorg
....

Either of these installations results in the complete Xorg system being installed.

The current user must be a member of the `video` group. To add a user to `video` group, execute the following command:

[source, shell]
....
# pw groupmod video -m username
....

[TIP]
====
숙련된 사용자에게 적합한 X 시스템의 더 작은 버전은 package:x11/xorg-minimal[]에서 다운 받을 수 있습니다. 대부분의 문서, 라이브러리 및 애플리케이션은 설치되지 않습니다. 일부 애플리케이션이 작동하려면 이러한 추가 구성 요소가 필요합니다.
====

[TIP]
====
Video cards, monitors, and input devices are automatically detected and do not require any manual configuration. Do not create `xorg.conf` or run a `-configure` step unless automatic configuration fails.
====

[[x-graphic-card-drivers]]
== Graphic card drivers

The following table shows the different graphics cards supported by FreeBSD, which package should be installed and its corresponding module.

.Graphic card packages
[options="header", cols="1,1,1,1"]
|===
| Brand | Type | Package | Module

| Intel(R)
| Open Source
| drm-kmod
| `i915kms`

| AMD(R)
| Open Source
| drm-kmod
| `amdgpu` and `radeonkms`

| NVIDIA(R)
| Proprietary
| nvidia-driver
| `nvidia` or `nvidia-modeset`

| VESA
| Open Source
| xf86-video-vesa
| vesa

| SCFB
| Open Source
| xf86-video-scfb
| scfb

| Virtualbox
| Open Source
| virtualbox-ose-additions
| Virtualbox OSE additions include the `vboxvideo` driver.

| VMware(R)
| Open Source
| xf86-video-vmware
| vmwgfx

|===

The following command can be used to identify which graphics card is installed in the system:

[source, shell]
....
% pciconf -lv|grep -B4 VGA
....

The output should be similar to the following:

[.programlisting]
....
vgapci0@pci0:0:2:0:     class=0x030000 rev=0x07 hdr=0x00 vendor=0x8086 device=0x2a42 subvendor=0x17aa subdevice=0x20e4
    vendor     = 'Intel Corporation'
    device     = 'Mobile 4 Series Chipset Integrated Graphics Controller'
    class      = display
    subclass   = VGA
....

[WARNING]
====
If the graphics card is not supported by Intel(R), AMD(R) or NVIDIA(R) drivers, then VESA or SCFB modules should be used. VESA module must be used when booting in BIOS mode and SCFB module must be used when booting in UEFI mode.

This command can be used to check the booting mode:

[source, shell]
....
% sysctl machdep.bootmethod
....

The output should be similar to the following:

[.programlisting]
....
machdep.bootmethod: BIOS
....
====

[[x-configuration-intel]]
=== Intel(R)

Intel(R) Graphics refers to the class of graphics chips that are integrated on the same die as an Intel(R) CPU. Wikipedia offers link:https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units[a good overview of the variations and names used for generations of Intel HD Graphics].

The package:graphics/drm-kmod[] package indirectly provides a range of kernel modules for use with Intel(R) Graphics cards. The Intel(R) driver can be installed by executing the following command:

[source, shell]
....
# pkg install drm-kmod
....

Then add the module to `/etc/rc.conf` file, executing the following command:

[source, shell]
....
# sysrc kld_list+=i915kms
....

[TIP]
====
If a high CPU usage is noticed or excessive tearing with HD video, the installation of package:multimedia/libva-intel-driver[] may help. To install the package execute the following command:

[source, shell]
....
# pkg install libva-intel-driver mesa-libs mesa-dri
....
====

[[x-configuration-amd]]
=== AMD(R)

The package:graphics/drm-kmod[] package indirectly provides a range of kernel modules for use with AMD(R) Graphics cards. The modules `amdgpu` and `radeonkms` can be used depending the generation of the hardware. The FreeBSD project maintains an link:https://wiki.freebsd.org/Graphics/AMD-GPU-Matrix[AMD graphics support matrix to determine which driver must be used].

AMD(R) driver can be installed by executing the following command:

[source, shell]
....
# pkg install drm-kmod
....

For post-HD7000 or Tahiti graphic cards add the module to `/etc/rc.conf` file, executing the following command:

[source, shell]
....
# sysrc kld_list+=amdgpu
....

For older graphic cards (pre-HD7000 or pre-Tahiti) add the module to `/etc/rc.conf` file, executing the following command:

[source, shell]
....
# sysrc kld_list+=radeonkms
....

[[x-configuration-nvidia]]
=== NVIDIA(R)

FreeBSD supports different versions of the proprietary NVIDIA(R) driver. Users of newer graphics cards should install the package:x11/nvidia-driver[] package. Those with older cards will have to check below which version supports them.

.Supported versions of NVIDIA(R) drivers
[options="header", cols="1,1"]
|===
| Package | Supported hardware

| x11/nvidia-driver-304
| link:https://www.nvidia.com/Download/driverResults.aspx/123712/en-us/[supported hardware]

| x11/nvidia-driver-340
| link:https://www.nvidia.com/Download/driverResults.aspx/156167/en-us/[supported hardware]

| x11/nvidia-driver-390
| link:https://www.nvidia.com/Download/driverResults.aspx/191122/en-us/[supported hardware]

| x11/nvidia-driver-470
| link:https://www.nvidia.com/Download/driverResults.aspx/191234/en-us/[supported hardware]

| x11/nvidia-driver
| link:https://www.nvidia.com/Download/driverResults.aspx/187164/en-us/[supported hardware]

|===

[WARNING]
====
Version 304 of the NVIDIA(R) graphics driver (nvidia-driver-304) does not support xorg-server 1.20 or later.
====

The latest NVIDIA(R) driver can be installed by running the following command:

[source, shell]
....
# pkg install nvidia-driver
....

Then add the module to `/etc/rc.conf` file, executing the following command:

[source, shell]
....
# sysrc kld_list+=nvidia-modeset
....

[WARNING]
====
The `nvidia` driver must be used if the packages x11/nvidia-driver-304 or x11/nvidia-driver-340 have been installed.

[source, shell]
....
# sysrc kld_list+=nvidia
....
====

[[x-config]]
== Xorg 구성

Xorg는 대부분의 일반적인 비디오 카드, 키보드, 포인팅 장치를 지원합니다.

[WARNING]
====
Video cards, monitors, and input devices are automatically detected and do not require any manual configuration. Do not create [.filename]#xorg.conf# or run a `Xorg -configure` step unless automatic configuration fails.
====

[[x-config-files]]
=== 구성 파일

Xorg looks in several directories for configuration files. [.filename]#/usr/local/etc/X11/# is the *recommended* directory for these files on FreeBSD. Using this directory helps keep application files separate from operating system files.

[[x-config-files-single-or-multi]]
=== 단일 또는 다중 파일

It is easier to use multiple files that each configure a specific setting than the traditional single [.filename]#xorg.conf#. These files are stored in the [.filename]#/usr/local/etc/X11/xorg.conf.d/# subdirectory.

[TIP]
====
The traditional single [.filename]#xorg.conf# still works, but is neither as clear nor as flexible as multiple files in the [.filename]#/usr/local/etc/X11/xorg.conf.d/# subdirectory.
====

[[x-config-video-cards]]
=== 비디오 카드

The driver for the graphics card can be specified in the [.filename]#/usr/local/etc/X11/xorg.conf.d/# directory.

To configure the Intel(R) driver in a configuration file:

[[x-config-video-cards-file-intel]]
.파일에서 인텔(R) 비디오 드라이버 선택
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-intel.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "intel"
EndSection
....
====

To configure the AMD(R) driver in a configuration file:

[[x-config-video-cards-file-amd]]
.Select AMD(R) Video Driver in a File
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-radeon.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "radeon"
EndSection
....
====

To configure the NVIDIA(R) driver in a configuration file:

[[x-config-video-cards-file-nvidia]]
.Select NVIDIA(R) Video Driver in a File
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-nvidia.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "nvidia"
EndSection
....
====

To configure the VESA driver in a configuration file:

[[x-config-video-cards-file-vesa]]
.Select VESA Video Driver in a File
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-vesa.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "vesa"
EndSection
....
====

To configure the SCFB driver in a configuration file:

[[x-config-video-cards-file-sfcb]]
.Select SCFB Video Driver in a File
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/20-scfb.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "scfb"
EndSection
....
====

To configure multiple video cards, the `BusID` can be added. A list of video card bus ``ID``s can be displayed by executing:

[source, shell]
....
% pciconf -lv | grep -B3 display
....

The output should be similar to the following:

[.programlisting]
....
vgapci0@pci0:0:2:0:     class=0x030000 rev=0x07 hdr=0x00 vendor=0x8086 device=0x2a42 subvendor=0x17aa subdevice=0x20e4
    vendor     = 'Intel Corporation'
    device     = 'Mobile 4 Series Chipset Integrated Graphics Controller'
    class      = display
--
vgapci1@pci0:0:2:1:     class=0x038000 rev=0x07 hdr=0x00 vendor=0x8086 device=0x2a43 subvendor=0x17aa subdevice=0x20e4
    vendor     = 'Intel Corporation'
    device     = 'Mobile 4 Series Chipset Integrated Graphics Controller'
    class      = display
....

[[x-config-video-cards-file-multiple]]
.Select Intel(R) Video Driver and NVIDIA(R) Video Driver in a File
[example]
====

[.filename]#/usr/local/etc/X11/xorg.conf.d/20-drivers.conf#

[.programlisting]
....
Section "Device"
	Identifier "Card0"
	Driver     "intel"
	BusID     "pci0:0:2:0"
EndSection

Section "Device"
	Identifier "Card0"
	Driver     "nvidia"
	BusID     "pci0:0:2:1"
EndSection
....
====

[[x-config-monitors]]
=== 모니터

대부분의 모니터는 확장 디스플레이 식별 데이터 표준(`EDID`)을 지원합니다. Xorg는 `EDID`를 사용하여 모니터와 통신하고 지원되는 해상도 및 재생률(refresh rates)을 감지합니다. 그런 다음 해당 모니터에 사용할 가장 적절한 설정 조합을 선택합니다.

모니터에서 지원되는 다른 해상도로 변경하고 싶은 경우, 구성 파일에서 원하는 해상도를 설정하거나 X 서버를 시작한 후 man:xrandr[1]을 사용하여 선택할 수 있습니다.

[[x-config-monitors-xrandr]]
==== Using RandR (Resize and Rotate)

매개변수 없이 man:xrandr[1]을 실행하면 비디오 출력 및 감지된 모니터 모드 목록을 확인할 수 있습니다:

[source, shell]
....
% xrandr
....

The output should be similar to the following:

[.programlisting]
....
Screen 0: minimum 320 x 200, current 2560 x 960, maximum 8192 x 8192
LVDS-1 connected 1280x800+0+0 (normal left inverted right x axis y axis) 261mm x 163mm
   1280x800      59.99*+  59.81    59.91    50.00  
   1280x720      59.86    59.74  
   1024x768      60.00  
   1024x576      59.90    59.82  
   960x540       59.63    59.82  
   800x600       60.32    56.25  
   864x486       59.92    59.57  
   640x480       59.94  
   720x405       59.51    58.99  
   640x360       59.84    59.32  
VGA-1 connected primary 1280x960+1280+0 (normal left inverted right x axis y axis) 410mm x 257mm
   1280x1024     75.02    60.02  
   1440x900      74.98    60.07  
   1280x960      60.00* 
   1280x800      74.93    59.81  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
....

This shows that the `VGA-1` output is being used to display a screen resolution of 1280x960 pixels at a refresh rate of about 60 Hz. The `LVDS-1` is being used as a secondary monitor to display a screen resolution of 1280x800 pixels at a refresh rate of about 60 Hz. Monitors are not attached to the `HDMI-1`, `HDMI-2`, `DP-1`, `DP-2` and `DP-3` connectors.

다른 디스플레이 모드는 man:xrandr[1]로 선택할 수 있습니다. 예를 들어, 60Hz에서 1280x1024로 전환합니다:

[source, shell]
....
% xrandr --output LVDS-1 --mode 1280x720 --rate 60
....

[[x-config-monitors-files]]
==== Using the Xorg configuration file

The monitor configuration can also be set in a configuration file.

구성 파일에서 화면 해상도를 1024x768로 설정하려면 다음과 같이 하세요:

.파일에서 화면 해상도 설정
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/10-monitor.conf#

[.programlisting]
....
Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	SubSection "Display"
	Modes      "1024x768"
	EndSubSection
EndSection
....
====

[[x-config-input]]
=== 입력 장치

Xorg supports the vast majority of input devices via package:x11/libinput[].

[TIP]
====
Some desktop environments (such as KDE Plasma) provide a graphical UI for setting these parameters. Check if this is the case before resorting to manual configuration editing.
====

[[x-config-input-keyboard-layout]]
For example, to configure the keyboard layout:

.키보드 레이아웃 설정
[example]
====
[.filename]#/usr/local/etc/X11/xorg.conf.d/00-keyboard.conf#

[.programlisting]
....
Section "InputClass"
        Identifier "Keyboard1"
        MatchIsKeyboard "on"
        Option "XkbLayout" "es, fr"
        Option "XkbModel" "pc104"
        Option "XkbVariant" ",qwerty"
        Option "XkbOptions" "grp:win_space_toggle"
EndSection
....
====

[[x-fonts]]
== Xorg에서 글꼴 사용

The default fonts that ship with Xorg are less than ideal for typical desktop publishing applications. Large presentation fonts show up jagged and unprofessional looking, and small fonts are almost completely unintelligible. However, there are several free, high quality Type1 (PostScript(R)) fonts available which can be readily used with Xorg.

[[type1]]
=== Type1 글꼴

The URW font collection (package:x11-fonts/urwfonts[]) includes high quality versions of standard type1 fonts (Times Roman(TM), Helvetica(TM), Palatino(TM) and others). The Freefonts collection (package:x11-fonts/freefonts[]) includes many more fonts, but most of them are intended for use in graphics software such as the Gimp, and are not complete enough to serve as screen fonts. In addition, Xorg can be configured to use TrueType(R) fonts with a minimum of effort. For more details on this, see the man:X[7] manual page or <<truetype>>.

바이너리 패키지에서 위의 Type1 글꼴 컬렉션을 설치하려면 다음 명령을 실행합니다:

[source, shell]
....
# pkg install urwfonts
....

And likewise with the freefont or other collections. To have the X server detect these fonts, add an appropriate line to the X server configuration file ([.filename]#/usr/local/etc/X11/xorg.conf.d/90-fonts.conf#), which reads:

[.programlisting]
....
Section "Files"
  FontPath "/usr/local/share/fonts/urwfonts/"
EndSection
....

또는 X 세션의 명령줄에서 실행합니다:

[source, shell]
....
% xset fp+ /usr/local/share/fonts/urwfonts
% xset fp rehash
....

이 방법은 잘 작동하지만 시작 파일에 추가하지 않으면 X 세션이 닫히면 소실됩니다(일반 `startx` 세션의 경우 [.filename]#~/.xinitrc# 또는 XDM과 같은 그래픽 로그인 관리자를 통해 로그인하는 경우 [.filename]#~/.xsession# ). 세 번째 방법은 <<antialias>>에 설명된 대로 새로운 [.filename]#/usr/local/etc/fonts/local.conf#를 사용하는 것입니다.

[[truetype]]
=== TrueType(R) 글꼴

Xorg has built in support for rendering TrueType(R) fonts. There are two different modules that can enable this functionality. The freetype module is used in this example because it is more consistent with the other font rendering back-ends. To enable the freetype module just add the following line to the `"Module"` section of [.filename]#/usr/local/etc/X11/xorg.conf.d/90-fonts.conf#.

[.programlisting]
....
Load  "freetype"
....

이제 TrueType(R) 글꼴을 위한 디렉터리(예: [.filename]#/usr/local/share/fonts/TrueType#)를 만들고 모든 TrueType(R) 글꼴을 이 디렉터리에 복사합니다. TrueType(R) 글꼴은 Apple(R) Mac(R)에서 직접 가져올 수 없으며, Xorg에서 사용하려면 UNIX(R)/MS-DOS(R)/Windows(R) 형식이어야 한다는 점에 유의하세요. 파일을 이 디렉터리에 복사한 후 mkfontscale을 사용하여 [.filename]#fonts.dir#을 생성하고 X 폰트 렌더러가 새 파일이 설치되었음을 알 수 있도록 합니다. `mkfontscale`은 패키지로 설치할 수 있습니다:

[source, shell]
....
# pkg install mkfontscale
....

그런 다음 디렉터리에 X 글꼴 파일의 색인을 만듭니다:

[source, shell]
....
# cd /usr/local/share/fonts/TrueType
# mkfontscale
....

이제 글꼴 경로에 TrueType(R) 디렉터리를 추가합니다. 이는 <<type1>>에서 설명한 것과 동일합니다:

[source, shell]
....
% xset fp+ /usr/local/share/fonts/TrueType
% xset fp rehash
....

또는 [.filename]#xorg.conf#에 `FontPath` 줄을 추가합니다.

이제 Gimp, LibreOffice 및 기타 모든 X 응용 프로그램에서 시스템에 설치된 TrueType(R) 글꼴을 인식할 수 있습니다. 이제 매우 작은 글꼴(웹 페이지의 고해상도 디스플레이에 있는 텍스트와 같이)과 매우 큰 글꼴(LibreOffice 안에서)이 훨씬 더 보기 좋아질 것입니다.

[[antialias]]
=== 안티 엘리어싱(anti-aliasing) 글꼴

[.filename]#/usr/local/share/fonts/# 및 [.filename]#~/.fonts/# 에 있는 Xorg의 모든 글꼴은 Xft-aware 응용 프로그램에 의해 앤티 앨리어싱(anti-aliasing)을 자동으로 사용할 수 있습니다. KDE, GNOME, Firefox 등 대부분의 최신 애플리케이션은 Xft-aware가 포함되어 있습니다.

앤티앨리어싱이 적용되는 글꼴을 제어하거나 앤티앨리어싱 속성을 구성하려면 [.filename]#/usr/local/etc/fonts/local.conf# 파일을 생성(또는 이미 존재하는 경우 편집)하세요. 이 파일을 사용하여 Xft 글꼴 시스템의 여러 고급 기능을 조정할 수 있으며, 이 섹션에서는 몇 가지 간단한 기능만을 설명합니다. 자세한 내용은 man:fonts-conf[5]를 참조하세요.

이 파일은 XML 형식이어야 합니다. 대소문자에 주의하고 모든 태그가 올바르게 닫혀 있는지 확인하세요. 파일은 일반적인 XML 헤더로 시작하여 DOCTYPE 정의와 `<fontconfig>` 태그가 이어집니다:

[.programlisting]
....
<?xml version="1.0"?>
      <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
      <fontconfig>
....

앞서 설명한 것처럼 [.filename]#/usr/local/share/fonts/# 및 [.filename]#~/.fonts/#에 있는 모든 글꼴은 이미 Xft-aware 애플리케이션에서 사용할 수 있도록 설정되어 있습니다. 이 두 디렉터리 트리 외에 다른 디렉터리를 추가하려면 [.filename]#/usr/local/etc/fonts/local.conf#에 다음과 같이 한 줄을 추가합니다:

[.programlisting]
....
<dir>/path/to/my/fonts</dir>
....

새 글꼴, 특히 새 글꼴 디렉터리를 추가한 후에는 글꼴 캐시를 다시 빌드합니다:

[source, shell]
....
# fc-cache -f
....

앤티 앨리어싱은 테두리를 약간 흐릿하게 만들어 매우 작은 텍스트의 가독성을 높이고 큰 텍스트의 “’계단현상”을 제거하지만 일반 텍스트에 적용하면 눈의 피로를 유발할 수 있습니다. 14포인트보다 작은 글꼴 크기를 앤티 앨리어싱에서 제외하려면 다음 줄을 포함하세요:

[.programlisting]
....
	<match target="font">
	    <test name="size" compare="less">
		<double>14</double>
	    </test>
	    <edit name="antialias" mode="assign">
		<bool>false</bool>
	    </edit>
	</match>
	<match target="font">
	    <test name="pixelsize" compare="less" qual="any">
		<double>14</double>
	    </test>
	    <edit mode="assign" name="antialias">
		<bool>false</bool>
	    </edit>
	</match>
....

일부 단일 간격 글꼴의 간격도 앤티 앨리어싱을 사용하면 부적절할 수 있습니다. 이는 특히 KDE에서 발생하는 문제인 것 같습니다. 한 가지 가능한 해결 방법은 이러한 글꼴의 간격을 100으로 강제 설정하는 것입니다. 이 줄을 추가합니다:

[.programlisting]
....
	<match target="pattern" name="family">
	   <test qual="any" name="family">
	       <string>fixed</string>
	   </test>
	   <edit name="family" mode="assign">
	       <string>mono</string>
	   </edit>
	</match>
	<match target="pattern" name="family">
	    <test qual="any" name="family">
		<string>console</string>
	    </test>
	    <edit name="family" mode="assign">
		<string>mono</string>
	    </edit>
	</match>
....

(이렇게 하면 고정 글꼴의 다른 일반적인 이름은 `”mono”`로 별칭이 지정됨)그리고 나서 다음 추가합니다:

[.programlisting]
....
	<match target="pattern" name="family">
	     <test qual="any" name="family">
		 <string>mono</string>
	     </test>
	     <edit name="spacing" mode="assign">
		 <int>100</int>
	     </edit>
	 </match>
....

Helvetica와 같은 몇몇 글꼴은 앤티 앨리어싱 시 문제가 발생할 수 있습니다. 일반적으로 세로로 반으로 잘린 듯한 글꼴로 나타납니다. 최악의 경우 애플리케이션이 충돌할 수 있습니다. 이를 방지하려면 [.filename]#local.conf#에 다음을 추가하세요:

[.programlisting]
....
	<match target="pattern" name="family">
	     <test qual="any" name="family">
		 <string>Helvetica</string>
	     </test>
	     <edit name="family" mode="assign">
		 <string>sans-serif</string>
	     </edit>
	 </match>
....

[.filename]#local.conf#를 수정한 후 `</fontconfig>` 태그로 파일을 끝내야 합니다. 이렇게 하지 않으면 변경 사항이 무시됩니다.

사용자는 자신만의 [.filename]#~/.config/fontconfig/fonts.conf#을 생성하여 개인화된 설정을 추가할 수 있습니다. 이 파일은 위에서 설명한 것과 동일한 `XML` 형식을 사용합니다.

마지막으로 LCD 화면의 경우 서브 픽셀 샘플링이 필요할 수 있습니다. 이는 기본적으로 (수평으로 분리된) 빨강, 녹색 및 파랑 구성 요소를 개별적으로 처리하여 수평 해상도를 향상시키며, 그 결과는 극적으로 달라질 수 있습니다. 이 기능을 활성화하려면 [.filename]#local.conf# 아무데나 다음 내용을 추가하세요:

[.programlisting]
....
	 <match target="font">
	     <test qual="all" name="rgba">
		 <const>unknown</const>
	     </test>
	     <edit name="rgba" mode="assign">
		 <const>rgb</const>
	     </edit>
	 </match>
....

[NOTE]
====
디스플레이 종류에 따라 'RGB'를 ‘BGR', 'VRGB' 또는 'VBGR'로 변경해야 할 수 있으므로 실험을 통해 어떤 것이 가장 효과적인지 확인하세요.
====

For more information about how to install and configure fonts on FreeBSD, please read the article link:{fonts}[Fonts and FreeBSD].
