# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
#
# $FreeBSD$
# $FreeBSDde: de-www/projects/Makefile,v 1.2 2006/10/19 19:26:04 jkois Exp $
# basiert auf: 1.20

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=	newbies.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
