# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
#
# $FreeBSD$
# $FreeBSDde: de-www/projects/Makefile,v 1.1 2005/01/29 19:07:54 jkois Exp $
# basiert auf: 1.20

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=	newbies.sgml

INDEXLINK= projects.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
