=== Changes to dhclient to speed up the FreeBSD boot process

Links: +
link:https://wiki.freebsd.org/SummerOfCode2024Projects/SpeedingUpTheFreeBSDBootProcess[Speeding up the FreeBSD boot process] URL: link:https://wiki.freebsd.org/SummerOfCode2024Projects/SpeedingUpTheFreeBSDBootProcess[] +

link:https://github.com/freebsd/freebsd-src/pull/1368[dhclient Pull Request] URL: link:https://github.com/freebsd/freebsd-src/pull/1368[] +

Contact: Isaac Cilia Attard <icattard@FreeBSD.org>

As part of my Google Summer of Code 2024 project, involving speeding up the FreeBSD boot process, I have worked on decreasing the time it takes for ARP resolution within dhclient to happen.
This involved reducing the default ARP resolution timeout from 2000 ms to 250 ms, and adding an option to disable it altogether.
The latter is useful within cloud environments, where a node is certain to have an IP address allotted to it.

As a consequence of this, connecting to a DHCP network is now faster, including the boot process during which this happens.
The speedup experienced is about 2 seconds.

This causes FreeBSD systems to boot significantly faster than before.

Sponsor: Google LLC (GSoC 2024)
