////
Quarter:	
Prepared by:	
Reviewed by:	
Last edit:	$Date$
Version:	$Id:$
////

=== Documentation Engineering Team

Link: link:https://www.freebsd.org/docproj/[FreeBSD Documentation Project] URL: link:https://www.freebsd.org/docproj/[] +
Link: link:https://docs.freebsd.org/en/books/fdp-primer/[FreeBSD Documentation Project Primer for New Contributors] URL: link:https://docs.freebsd.org/en/books/fdp-primer/[] +
Link: link:https://www.freebsd.org/administration/#t-doceng[Documentation Engineering Team] URL: link:https://www.freebsd.org/administration/#t-doceng[]

Contact: FreeBSD Doceng Team <doceng@FreeBSD.org>

The doceng@ team is a body to handle some of the meta-project issues associated with the FreeBSD Documentation Project; for more information, see link:https://www.freebsd.org/internal/doceng/[FreeBSD Doceng Team Charter].

Benedict Reuschling steps down from doceng@.
doceng@ would like to thank bcr@ for his service.

==== Document changes

* Handbook: Document the automatic creation of XDG directories starting with
  FreeBSD 14.1.
  The VNET config example script has been fixed.

* Architecture Handbook: remove K&R prototypes in MAC chapter.

* Website: Some improvements regarding the top banner and layout, visually
  rearrange buttons and more.

* Documentation repository: fix of all malformed tables warnings.
  Removal of deprecated attributes to conform to new gohugo releases.

==== FreeBSD Translations on Weblate

Link: link:https://wiki.freebsd.org/Doc/Translation/Weblate[Translate FreeBSD on Weblate] URL: link:https://wiki.freebsd.org/Doc/Translation/Weblate[] +
Link: link:https://translate-dev.freebsd.org/[FreeBSD Weblate Instance] URL: link:https://translate-dev.freebsd.org/[]

===== Q3 2024 Status

* 17 team languages
* 214 registered users

1 new translator joined Weblate:

* matthew (id)

===== Languages

* Chinese (Simplified) (zh-cn)	(progress: 7%)
* Chinese (Traditional) (zh-tw)	(progress: 3%)
* Dutch (nl) 			(progress: 1%)
* French (fr)			(progress: 1%)
* German (de)			(progress: 1%)
* Greek (el)			(progress: 1%)
* Indonesian (id)		(progress: 1%)
* Italian (it)			(progress: 5%)
* Korean (ko)			(progress: 32%)
* Norwegian (nb-no)		(progress: 1%)
* Persian (fa-ir)		(progress: 3%)
* Polish			(progress: 2%)
* Portuguese			(progress: 0%)
* Portuguese (pt-br)		(progress: 24%)
* Spanish (es)			(progress: 36%)
* Turkish (tr)			(progress: 2%)

We want to thank everyone that contributed, translating or reviewing documents.

And please, help promote this effort on your local user group, we always need more volunteers.

==== Packages maintained by DocEng

During this quarter the following work was done in packages maintained by
doceng@:

* textproc/docproj: Bump gohugo dependency to 0.133.1
* www/gohugo: update to 0.134.3

==== Open issues

There are 2 Open PRs in bugzilla assigned to doceng@:

 * 276923 www/gohugo link error under poudriere
 * 267274 Please remove the zh-CN Handbook of the current FreeBSD website

During this quarter doceng@ closed 3 PRs:

 * 266107 FreeBSD Handbook and other books: PDF: broken links – crossref
 * 279815 status reports: ERR_TOO_MANY_REDIRECTS
 * 281396 handbook: ERROR: <stdin>: line 149: dropping cells from incomplete row detected
