=== The FreeBSD Russian Documentation Project

Links: +
link:https://docs.freebsd.org/ru/books/faq/[FAQ] URL: link:https://docs.freebsd.org/ru/books/faq/[] +
link:https://docs.freebsd.org/ru/books/handbook/[Handbook] URL: link:https://docs.freebsd.org/ru/books/handbook/[] +
link:https://www.freebsd.org/ru/[Web] URL: link:https://www.freebsd.org/ru/[]

Contact: Andrei Zakhvatov <andrey.zakhvatov@gmail.com>

The FreeBSD Russian Documentation Project's current goal is to provide up-to-date Russian translations of the most important parts of FreeBSD documentation (FAQ, Handbook, Web).
It is important to support Russian speakers with high-quality official technical materials and increase acceptance of the operating system around the globe.
We hope that this activity will receive some support from the Russian-speaking FreeBSD community and lead to more translated materials.

There is some progress in document translation:

* FAQ: link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277008[PR #277008] and link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282062[PR #282062]
* Handbook: Chapter 1. Introduction: link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276334[PR #276334]
* Handbook: Chapter 2. Installing FreeBSD: link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280610[PR #280610]
* Handbook: Chapter 3. FreeBSD Basics: link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282059[PR #282059]

Check link:https://docs.freebsd.org/en/books/fdp-primer/translations/[the official translation guide] if you are willing to help.
We always appreciate your help with translation of the following materials:

* Handbook chapters and sections
* Articles
* Web pages
