=== FreeBSD Samba Team

Links: +
link:https://wiki.freebsd.org/Samba[FreeBSD Samba Team Wiki] URL: link:https://wiki.freebsd.org/Samba[] +
link:https://www.samba.org/[Samba Homepage] URL: https://www.samba.org/[] +

Contact: FreeBSD Samba Team <samba@FreeBSD.org>

Samba provides secure, stable and fast file and print services for all clients using the SMB/CIFS protocol.
It is an important component to seamlessly integrate FreeBSD/Linux/Unix Servers and Desktops into Active Directory environments.
It can function both as a domain controller or as a regular domain member.

The new FreeBSD Samba Team was created to better coordinate maintenance efforts of the Samba ports and its dependencies, in particular:

* package:databases/ldb22[]
* package:databases/ldb25[]
* package:databases/ldb28[]
* package:databases/tdb[]
* package:devel/talloc[]
* package:devel/tevent[]
* package:net/samba416[]
* package:net/samba419[]

Notable changes in the last quarter include:

* Creation of the FreeBSD Samba Team by mailto:timur@FreeBSD.org[Timur Bakeyev], mailto:kiwi@oav.net[Xavier Beaudouin], mailto:yasu@freebsd.org[Yasuhiro Kimura], mailto:0mp@FreeBSD.org[Mateusz Piotrowski], and mailto:mikael@FreeBSD.org[Mikaël Urankar].
* Added `SAMBA_LDB_PORT` to [.filename]#Mk/Uses/samba.mk# (sponsored by Klara, Inc.)
* Switching package:net/samba419[] to use external dependencies by default instead of vendoring (sponsored by Klara, Inc.)
* Updating package:net/samba419[] to 4.19.8

Currently, the FreeBSD Samba team is coordinating efforts in the following areas:

* Switching the default version of Samba from 4.16 to 4.19 (link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280769[Bugzilla PR#280769]).
  * Current blockers are:
    * Broken `fruit:posix_rename = yes` (link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281360[Bugzilla PR#281360])
    * Broken replication in Samba 4.19.8_1 (link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281672[Bugzilla PR#281672])
* Adding Samba 4.20 to the ports tree (link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280533[Bugzilla PR#280533])
* Adding Samba 4.21 to the ports tree (link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281262[Bugzilla PR#281262])

Testing and community contributions are welcome, please reach out on Bugzilla or via the team email.
