=== Linux Source Compatibility Wiki page

Links: +
link:https://wiki.freebsd.org/LinuxSourceCompatibility[Linux Source Compatibility] URL: link:https://wiki.freebsd.org/LinuxSourceCompatibility[]

Contact: Edward Tomasz Napierala <trasz@freebsd.org>

There is now a wiki page to track source compatibility differences between FreeBSD and Linux -- and it needs your input!

FreeBSD and Linux are already largely compatible at the source code level due to both being Unix systems and following the same standards.
There are however certain system calls specific to Linux; there are also differences in header files, constants and so on.
Implementing them in FreeBSD would make porting software easier.

Not all of the items there are fixable.
Some differences cannot be eliminated due to naming clashes, disagreements on how the system is supposed to work, or because it would make autoconf pick up a less functional compatibility API instead of the native one.
In such cases we should document it and advise what API to use instead.

The wiki page aims to provide an overview and help track progress.
That is where your help is needed.
I need people who actually port software to FreeBSD to add missing APIs, based on their experiences.
This also includes non-syscall items, like missing headers and unsupported constants.
Preferably also mention the name of the software that could use them.

 * Add missing items
 * Add prospective API consumers

Sponsor: Innovate UK
