=== FreeBSD Wiki

Links: +
link:https://wiki.freebsd.org/FrontPage[FreeBSD wiki front page] URL: link:https://wiki.freebsd.org/FrontPage[]

Contact: Mark Linimon <linimon@freebsd.org>
Contact: Wiki admin <wiki-admin@freebsd.org>

The FreeBSD wiki is a repository of information that does not fit well in the link:https://docs.freebsd.org/en/[official project documentation] because it is too specific, too disparate, or too transient.

==== Current projects:

Mark Linimon has started attacking various stale pages.
The focus has been on pages that we show to new, interested, users.
(Recent Foundation newsletters refer to some of these pages directly.)
Unfortunately, many of these pages have become stale, to the point where they were actually not good recommendations.

The pages that have received the most work are:

* link:https://wiki.freebsd.org/IdeasPage[IdeasPage] (referenced in Foundation documentation)
* link:https://wiki.freebsd.org/JuniorJobs[JuniorJobs] (referenced in Foundation documentation)
* link:https://wiki.freebsd.org/SummerOfCodeIdeas[SummerOfCodeIdeas]
* various pages under link:https://wiki.freebsd.org/CategoryProject[CategoryProject]
* various pages under link:https://wiki.freebsd.org/CategoryTodo[CategoryTodo]
* link:https://wiki.freebsd.org/MentorMatch[MentorMatch]

In addition to removing obviously stale entries, all entries have now been datestamped with the time that they were added to the various pages.
link:mailto:wiki-admin@freebsd.org[wiki-admin@] would like to request that we carry forward this tradition into the future.

As well, link:mailto:wiki-admin@freebsd.org[wiki-admin@] has been sending email to ask committers/contributors to the above pages "should we keep this entry?"
This task will continue until the pages have been cleaned up.

(NB: the fact that content in the wiki was stale was mentioned by numerous respondents in the FreeBSD Foundation 2024 Community Survey Report.)

==== Previous plans that have stalled

Plans are still underway to familiarize our audience on Discord with the wiki (there are too many "silos" in our FreeBSD community).
The team has simply not had enough cycles to do this.
However, contact Setesh on the FreeBSD Discord for more information.

Preliminary work was being done on updating the wiki software itself.
Earlier, we were looking at switching implementations because MoinMoin development seemed to have stalled, leaving us with an unwanted hanging python2 dependency.
However, MoinMoin now claims that they are nearing a 2.0 release.
We have not yet tried an install of their latest beta version to test compatibility.
Testers welcome.
