=== Wireless Update

Links: +
link:https://bugs.freebsd.org/bugzilla/showdependencytree.cgi?id=277512&hide_resolved=0[Categorised Wireless Problem Reports] URL: link:https://bugs.freebsd.org/bugzilla/showdependencytree.cgi?id=277512&hide_resolved=0[]

Contact: Bjoern A. Zeeb <bz@FreeBSD.org> +
Contact: The FreeBSD wireless mailing list <wireless@FreeBSD.org>

The ongoing wireless efforts are trying to bring more support for recent chipsets as well as newer standards.

With man:iwlwifi[4] and man:rtw88[4] being supported we received patches and initial reports for rtw89 and ath10k working for some people.
Additionally ath11k, ath12k and various chipsets supported by mt76 are waiting for someone to find the time to finish compat code, test and debug.

Work is ongoing to update drivers to Linux v6.11 using the now bootstrapped vendor branches, which should help maintenance a lot in the future.
One particular focus for this update is also to find ways to minimize incompatibilities between wireless compat code versions in order to support multiple Linux versions as needed.

After the native kern_malloc changes got committed, LinuxKPI is seeing ongoing work for memory allocation to play better by the rules set out in Linux which should help with DMA problems seen.
There is further work pending to add missing bus_dmamap_sync() calls.

There is work to support man:rtw88[4] SDIO devices (being tested on an r2s-plus) and ongoing work to stabilize updated USB support which should start landing once the driver updates have finished.
Lastly there are more updates in the queue to finish 11n support for LinuxKPI 802.11 compat code as well as improving native net80211 code.

If you have questions or feedback please use the link:https://lists.freebsd.org/subscription/freebsd-wireless[freebsd-wireless mailing list].
That way everyone will see, be able to join in, and the answers will be publicly archived.

Sponsor: The FreeBSD Foundation
