# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.xml

DATA=	docbook.css \
        hardware.html \
        readme.html \
        installation.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
