---
title: Over applicaties voor FreeBSD
sidenav: about
---

= Over applicaties voor FreeBSD

== Ervaar de mogelijkheden met FreeBSD

FreeBSD kan bijna elke taak aan die verwacht wordt van een UNIX(R) werkstation, maar ook vele die u niet zou verwachten:

== FreeBSD is een waar open systeem met volledige broncode.

Er bestaat geen twijfel dat zogenaamde open systemen _de_ vereiste zijn voor de rekentoepassingen van vandaag. Maar geen leveranciersoplossing is meer open dan een die de volledige broncode van het gehele besturingssysteem bevat, inclusief de kernel en alle systeem-daemons, programma's, en gereedschappen. U kunt elk deel van FreeBSD aanpassen aan uw persoonlijke, organisatorische of bedrijfsmatige behoeften.

Met het genereuze link:https://www.FreeBSD.org/copyright/freebsd-license/[licentiebeleid] kan FreeBSD als de basis van elk aantal vrije _of commerciële_ applicaties gebruikt worden.

== FreeBSD draait duizenden applicaties.

Omdat FreeBSD gebaseerd is op 4.4BSD, een industriestandaard-versie van UNIX, is het eenvoudig om programma's te compileren en te draaien. FreeBSD bevat ook een uitgebreide link:../where/[pakketverzameling] en link:https://www.FreeBSD.org/ports/[portverzameling] die voorgecompileerde en gemakkelijk bouwbare software rechtstreeks naar uw bureaublad of bedrijfsserver brengen. Er is ook een groeiend aantal link:https://www.FreeBSD.org/commercial/software/[commerciële applicaties] geschreven voor FreeBSD.

Hier zijn enkele voorbeelden van omgevingen waarin FreeBSD gebruikt wordt:

* *Internetdiensten.* Vele Internetproviders (ISPs) vinden FreeBSD ideaal om WWW, Usenet nieuws, FTP, email, en andere diensten te draaien. Direct te gebruiken software zoals de http://nginx.org[nginx] of http://www.apache.org/[Apache] webserver of de http://proftpd.org[ProFTPD] of http://security.appspot.com/vsftpd.html[vsftpd] FTP-server maken het eenvoudig om een zaak- of gemeenschapsgerichte ISP op te zetten. Natuurlijk, met FreeBSD's onverslaanbare link:../internet/[netwerkdienst], zullen uw gebruikers genieten van razendsnelle, betrouwbare diensten.
* *X Window werkstation.* Van een goedkope X-terminal tot een geavanceerd X-display werkt FreeBSD behoorlijk goed. Gratis X-software (http://x.org/[X.Org](TM)) wordt met het systeem geleverd. http://www.nvidia.com/[nVidia] biedt oorspronkelijke stuurprogramma's voor hun hoog presterende grafische hardware, en de industriestandaardbibliotheken http://www.opengroup.org/motif[Motif](R) en http://www.opengl.org[OpenGL](R) worden ondersteund. De http://xfce.org/[Xfce] en http://lxde.org/[LXDE]-producten bieden een bureaubladomgeving aan. De http://www.kde.org[KDE] en http://www.gnome.org[GNOME] bureaubladomgevingen hebben ook volledige ondersteuning en bieden kantoorfunctionaliteit, verder is goede functionaliteit beschikbaar in de producten http://www.libreoffice.org/[LibreOffice], http://www.openoffice.org/[OpenOffice.Org] en http://www.softmaker.de/tml_en.htm[TextMaker].
* *Netwerken.* Van pakketten filteren tot routing tot naamdiensten leveren, FreeBSD kan van elke PC een Internet firewall, email-gastheer, printserver, PC/NFS-server, en meer maken.
* *Software-ontwikkeling.* Een pakket aan ontwikkelgereedschappen wordt met FreeBSD geleverd, inclusief de GNU C/C++ compiler en debugger. De clang-suite gebaseerd op LLVM wordt ook aangeboden en zal uiteindelijk de GNU-suite vervangen. Ontwikkelen in Java(R) en Tcl/Tk is ook mogelijk, en esoterischere talen zoals Icon werken ook prima. En de gedeelde bibliotheken van FreeBSD zijn altijd eenvoudig te bouwen en gebruiken geweest. U kunt ook kiezen uit een groot aantal populaire en krachtige tekstverwerkers zoals XEmacs en Vim.
* *Netsurfen.* Een echt UNIX werkstation is een prachtige surfplank voor Internet. Versies voor FreeBSD van http://www.chromium.org/Home[Chromium], http://www.mozilla.org/firefox/[Firefox] en http://www.opera.com/[Opera] zijn beschikbaar voor serieuze webgebruikers. Surf op het web, publiceer uw eigen webpagina's, lees Usenet nieuws, en verzend en ontvang email met een FreeBSD systeem op uw bureau.
* *Onderwijs en onderzoek.* FreeBSD is een uitstekend onderzoeksplatform omdat het de complete broncode bevat. Studenten en onderzoekers van besturingssystemen of andere velden van computerwetenschappen kunnen enorm profiteren van zo'n open en goed gedocumenteerd systeem.
* **En nog veel meer.**Accounting, actiespellen, MIS-databases, wetenschappelijke visualisatie, videovergaderen, Internet relay chat (IRC), thuisautomatisering, dungeons voor meerdere gebruikers, prikbordsystemen, beeldscannen en meer zijn vandaag allemaal echte toepassingen van FreeBSD.

== FreeBSD is een besturingssysteem dat meegroeit met uw behoeften.

Hoewel FreeBSD gratis software is, is het ook _door gebruikers ondersteunde_ software. Elke vraag die u heeft kan naar honderden FreeBSD ontwikkelaars en gebruikers worden gestuurd door simpelweg de freebsd-questions@FreeBSD.org mailinglijst te emailen.

FreeBSD heeft ook een wereldwijde groep programmeurs en schrijvers die fouten herstellen, nieuwe mogelijkheden toevoegen en het systeem documenteren. Ondersteuning voor nieuwe apparaten of speciale mogelijkheden is een bijna constant ontwikkelproces, en het team houdt een speciaal oog in het zeil voor problemen die de stabiliteit van het systeem beïnvloeden. Gebruikers van FreeBSD zijn behoorlijk trots op niet alleen de snelheid maar ook de betrouwbaarheid van hun systemen.

== Wat de experts te zeggen hebben . . .

_``FreeBSD gaat behoorlijk goed om met [onze] zware belasting en het is werkelijk verbazingwekkend. Hulde aan het FreeBSD team.''_

---Mark Hittinger, beheerder van WinNet Communications, Inc.
