---
title: Netwerkmogelijkheden van FreeBSD
sidenav: about
---

= Netwerkmogelijkheden van FreeBSD

== FreeBSD is ontworpen voor het Internet

FreeBSD bevat wat velen beschouwen als de _referentie_ implementatie voor TCP/IP software, de 4.4 BSD TCP/IP protocolstack, waardoor het besturingssysteem ideaal is voor netwerkapplicaties en het Internet. FreeBSD 7.0 bevat ook de referentie-implementatie van SCTP, waardoor het een ideaal platform is voor telefonie en andere gegevens-streaming-toepassingen.

== FreeBSD ondersteunt standaard alle TCP/IP protocollen

Net als de meeste UNIX(R)-systemen, stelt het FreeBSD besturingssysteem u in staat om:

* Statische en dynamische webinhoud over HTTP te serveren
* Bestandssystemen te delen met NFS
* Netwerkinformatie te distribueren met NIS
* Email-diensten over SMTP, IMAP en POP3 af te handelen en aan te bieden
* Aanmelden op afstand te ondersteunen over SSH en rsh
* Op afstand via SNMP instellingen te maken en te beheren
* Bestanden te serveren met FTP
* Internet-hostnamen te resolven met DNS/BIND
* Pakketten te routeren tussen meerdere interfaces, inclusief PPP en SLIP
* IP Multicastdiensten te gebruiken (de MBONE)
* Diensten aan te bieden over IPv6

FreeBSD stelt u in staat een PC om te toveren in een webserver of mailserver of een Usenet news relay met bijgesloten software. Met de bijgesloten software SAMBA kunt u zelfs bestanden of printers delen met Microsoft(R) Windows(R) machines en met de PCNFS authenticatie-daemon is het mogelijk te integreren met machines die PC/NFS draaien. FreeBSD ondersteunt ook Appletalk en Novell client/server (via een optioneel commercieel pakket), waardoor het een echte "Intranet"-netwerkoplossing is.

FreeBSD kan ook omgaan met TCP-uitbreidingen als de http://www.ietf.org/rfc/rfc1323.html[RFC-1323] hoge prestaties uitbreiding, plus SLIP en bel-op-aanvraag PPP. Het is een besturingssysteem dat geschikt is voor de surfende thuisgebruiker en de bedrijfssysteembeheerder.

== Netwerken met FreeBSD is stabiel en snel

Als u een Internet-server-platform zoekt dat betrouwbaar is en de beste prestaties onder zware belasting biedt, overweeg dan FreeBSD. Hieronder een opsomming van slechts een aantal bedrijven dat iedere dag FreeBSD gebruikt:

* Walnut Creek CDROM draaide vele jaren een van de meest populaire FTP servers op het Internet, ftp.cdrom.com, exclusief op FreeBSD. Het was slechts een FreeBSD machine die 6000 verbindingen ondersteunde en in staat was om meer dan dertig 30 terabyte (in juni 1999 - ja, _terabyte_!) aan bestanden te serveren aan meer dan 10 miljoen mensen.
* http://www.yahoo.com/[Yahoo Inc.] draait de untieme index op Internet, en serveert hordes surfers informatie over Internet. Yahoo, en ook de bedrijven die op Yahoo adverteren, vertrouwen op FreeBSD als betrouwbare en responsieve webserver.
* http://www.netcraft.com/[Netcraft] is de leidende onderzoeker naar gebruik van webserver-software op Internet. Ze gebruiken FreeBSD en Apache voor hun website en FreeBSD/Perl voor al hun data collectie op Internet.

FreeBSD is het ideale platform voor deze en andere Internetdiensten:

* Bedrijfsbrede of wereldwijde webdiensten
* WWW proxy
* Anonieme FTP
* Enterprise bestands-, print- en emaildiensten
* Routers, firewalls en binnendringdetectiesystemen

De FreeBSD link:../ports/[Portscollectie] bevat kant-en-klare software die het makkelijk maakt om uw eigen Internetserver op te zetten.

== Hoge prestaties _en_ beveiliging

De FreeBSD ontwikkelaar zijn net zo druk met beveiliging als met prestaties. FreeBSD bevat kernelondersteuning voor IP firewalling en andere diensten als IP proxy gateways. Als uw bedrijfsservers zijn aangesloten op Internet, kan iedere computer waarop FreeBSD draait dienst doen als netwerk-firewall om ze te beschermen tegen dreigingen van buitenaf.

Encryptiesoftware, secure shells, Kerberos, end-to-end encryptie en veilige RPC-faciliteiten zijn ook beschikbaar.

Verder is het FreeBSD team pro-actief bezig met het ontdekken en elimineren van beveiligingsproblemen door het verstrekken van beveiligingsinformatie en het verwerken van bugmeldingen met een mailto:security-officer@FreeBSD.org[Beveiligingsofficier] en banden met het Computer Emergency Response Team (http://www.cert.org/[CERT]).

== Wat de experts te zeggen hebben. . .

_``FreeBSD ... biedt wat mogelijk de meest robuuste en capabele TCP/IP-stack is die bestaat ...''_

---Michael O'Brien, _SunExpert_ Augustus 1996 jaargang 7 nummer 8.
