---
title: Contact opnemen met FreeBSD
sidenav: about
---

include::shared/nl/urls.adoc[]

= Contact opnemen met FreeBSD

== Vragen over FreeBSD...

Vragen over FreeBSD dienen gericht te worden aan de FreeBSD Vragen mailinglijst, freebsd-questions@FreeBSD.org.

link:https://www.FreeBSD.org/community/mailinglists/[Mailinglijsten] zijn de primaire ondersteuningskanalen voor gebruikers van FreeBSD, met verschillende mailinglijsten die verschillende onderwerpsgebieden behandelen. Er zijn ook verschillende niet-Engelstalige mailinglijsten beschikbaar.

== Vragen over de inhoud van deze webserver...

Vragen of opmerkingen over onze documentatie (link:{handbook}[Handboek], link:{faq}[FAQ], link:../docs/[Boeken & artikelen]) dienen gericht te worden aan de FreeBSD Documentatie Project mailinglijst, freebsd-doc@FreeBSD.org.

== Slakkenpost, telefoon en fax

Voor CDROM-bestellingen: http://www.freebsdmall.com/[The FreeBSD Mall]

Voor commerciële ondersteuning: http://www.freebsdmall.com/[The FreeBSD Mall]

== link:../administration/[Wie is waarvoor verantwoordelijk]

Marketing, Bugmeister, Beveiligingsofficier, Postmeester, Webmaster etc.
