# $FreeBSD$
# $FreeBSDde: de-www/docs/Makefile,v 1.2 2007/07/22 07:02:49 jkois Exp $
# basiert auf: 1.6

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS= books.xml
DOCS+= webresources.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
