---
title: "FreeBSD 14.5-RELEASE Announcement"
sidenav: download
---

:thisBranch: 14
:thisRelease: 14.5
:nextRelease: 14.6
:lastRelease: 14.4
:thisBranchEOL: November 30, 2028
:thisEOL: June 30, 2027
:lastEOL: December 31, 2026
:which: sixth

include::shared/releases.adoc[]
:thisDate: {rel145-current-date}

= FreeBSD {thisRelease}-RELEASE Announcement

Date: {thisDate}

The FreeBSD Release Engineering Team is pleased to announce the availability of FreeBSD {thisRelease}-RELEASE.
This is the {which} release of the stable/{thisBranch} branch.

Since this release is occurring late in a legacy stable branch, there are few new features; rather, the focus is primarily on maintenance.
As such, changes since {lastRelease}-RELEASE consist mostly of bug fixes, driver updates, and new versions of externally-maintained software.

For a complete list of new features, supported hardware, and known problems, please see the online release notes, hardware compatibility notes, and errata list, available at:

* `https://www.FreeBSD.org/releases/{thisRelease}R/relnotes/`
* `https://www.FreeBSD.org/releases/{thisRelease}R/hardware/`
* `https://www.FreeBSD.org/releases/{thisRelease}R/errata/`

For more information about FreeBSD release engineering activities, please see:

* `https://www.FreeBSD.org/releng/`

== Availability

FreeBSD {thisRelease}-RELEASE is now available for the amd64, i386, aarch64, armv7, powerpc, poerpcspe, powerpc64, powerpc64le, and riscv64 architectures.

FreeBSD {thisRelease}-RELEASE can be installed from bootable ISO images or over the network.
Some architectures also support installing from a USB memory stick.
The required files can be downloaded as described below.

SHA512 and SHA256 hashes for the release ISO, memory stick, and SD card images are included at the bottom of this message.

PGP-signed checksums for the release images are also available at:

* https://www.FreeBSD.org/releases/{thisRelease}R/signatures/

A PGP-signed version of this announcement is available at:

* https://www.FreeBSD.org/releases/{thisRelease}R/announce.asc

The purpose of the images provided as part of the release are as follows:

dvd1::
This contains everything necessary to install the base FreeBSD operating system, the documentation, debugging distribution sets, and a small set of pre-built packages aimed at getting a graphical workstation up and running.
It also supports booting into a "livefs" based rescue mode.
This should be all you need if you can burn and use DVD-sized media.
+
Additionally, this can be written to a USB memory stick (flash drive) for the amd64 architecture and used to do an install on machines capable of booting off USB drives.
It also supports booting into a "livefs" based rescue mode.
+
As one example of how to use the dvd1 image, assuming the USB drive appears as /dev/da0 on your machine something like this should work:
+
[subs="attributes"]
....
# dd if=FreeBSD-{thisRelease}-RELEASE-amd64-dvd1.iso \
    of=/dev/da0 bs=1m conv=sync
....
+
Be careful to make sure you get the target (of=) correct.
disc1::
This contains the base FreeBSD operating system.
It also supports booting into a "livefs" based rescue mode.
There are no pre-built packages.
+
Additionally, this can be written to a USB memory stick (flash drive) for the amd64 architecture and used to do an install on machines capable of booting off USB drives.
It also supports booting into a "livefs" based rescue mode.
There are no pre-built packages.
+
As one example of how to use the disc1 image, assuming the USB drive appears as /dev/da0 on your machine something like this should work:
+
[subs="attributes"]
....
# dd if=FreeBSD-{thisRelease}-RELEASE-amd64-disc1.iso \
    of=/dev/da0 bs=1m conv=sync
....
+
Be careful to make sure you get the target (of=) correct.
bootonly::
This supports booting a machine using the CDROM drive but does not contain the installation distribution sets for installing FreeBSD from the CD itself.
You would need to perform a network based install (e.g., from an HTTP or FTP server) after booting from the CD.
+
Additionally, this can be written to a USB memory stick (flash drive) for the amd64 architecture and used to do an install on machines capable of booting off USB drives.
It also supports booting into a "livefs" based rescue mode.
There are no pre-built packages.
+
As one example of how to use the bootonly image, assuming the USB drive appears as /dev/da0 on your machine something like this should work:
+
[subs="attributes"]
....
# dd if=FreeBSD-{thisRelease}-RELEASE-amd64-bootonly.iso \
    of=/dev/da0 bs=1m conv=sync
....
+
Be careful to make sure you get the target (of=) correct.
memstick::
This can be written to a USB memory stick (flash drive) and used to do an install on machines capable of booting off USB drives.
It also supports booting into a "livefs" based rescue mode.
There are no pre-built packages.
+
As one example of how to use the memstick image, assuming the USB drive appears as /dev/da0 on your machine something like this should work:
+
[subs="attributes"]
....
# dd if=FreeBSD-{thisRelease}-RELEASE-amd64-memstick.img \
    of=/dev/da0 bs=1m conv=sync
....
+
Be careful to make sure you get the target (of=) correct.
mini-memstick::
This can be written to a USB memory stick (flash drive) and used to boot a machine, but does not contain the installation distribution sets on the medium itself, similar to the bootonly image.
It also supports booting into a "livefs" based rescue mode.
There are no pre-built packages.
+
As one example of how to use the mini-memstick image, assuming the USB drive appears as /dev/da0 on your machine something like this should work:
+
[subs="attributes"]
....
# dd if=FreeBSD-{thisRelease}-RELEASE-amd64-mini-memstick.img \
    of=/dev/da0 bs=1m conv=sync
....
+
Be careful to make sure you get the target (of=) correct.
FreeBSD/arm SD card images::
These can be written to an SD card and used to boot the supported arm system.
The SD card image contains the full FreeBSD installation, and can be installed onto SD cards as small as 5 GB.
+
For convenience for those without console access to the system, a `freebsd` user with a password of `freebsd` is available by default for `ssh(1)` access.
Additionally, the `root` user password is set to `root`; it is strongly recommended to change the password for both users after gaining access to the system.
+
To write the FreeBSD/arm image to an SD card, use the `dd(1)` utility, replacing _KERNEL_ with the appropriate kernel configuration name for the system.
+
[subs="attributes"]
....
# dd if=FreeBSD-{thisRelease}-RELEASE-arm64-aarch64-RPI.img \
    of=/dev/da0 bs=1m conv=sync
....
+
Be careful to make sure you get the target (of=) correct.

Pre-installed virtual machine images are also available for the amd64 (x86_64), i386 (x86_32), AArch64 (arm64), and RISCV (riscv64) architectures in `QCOW2`, `VHD`, and `VMDK` disk image formats, as well as raw (unformatted) images.

FreeBSD {thisRelease}-RELEASE is also available on these cloud hosting platforms:

* FreeBSD Amazon(R) EC2(TM): +

FreeBSD/amd64 EC2 AMI IDs can be retrieved from the Systems Manager Parameter Store in each region using the keys:

....
        /aws/service/freebsd/amd64/base/ufs/14.5/RELEASE
        /aws/service/freebsd/amd64/base/zfs/14.5/RELEASE
        /aws/service/freebsd/amd64/builder/ufs/14.5/RELEASE
        /aws/service/freebsd/amd64/builder/zfs/14.5/RELEASE
        /aws/service/freebsd/amd64/cloud-init/ufs/14.5/RELEASE
        /aws/service/freebsd/amd64/cloud-init/zfs/14.5/RELEASE
        /aws/service/freebsd/amd64/small/ufs/14.5/RELEASE
        /aws/service/freebsd/amd64/small/zfs/14.5/RELEASE
....

AMIs are also expected to be available soon in the AWS Marketplace at:

....
        https://aws.amazon.com/marketplace/pp/prodview-sxzreyutwngxy (UFS)
        https://aws.amazon.com/marketplace/pp/prodview-4csbncujmsgbk (ZFS)
....

FreeBSD/aarch64 EC2 AMI IDs can be retrieved from the Systems Manager Parameter Store in each region using the keys:

....
        /aws/service/freebsd/arm64/base/ufs/14.5/RELEASE
        /aws/service/freebsd/arm64/base/zfs/14.5/RELEASE
        /aws/service/freebsd/arm64/builder/ufs/14.5/RELEASE
        /aws/service/freebsd/arm64/builder/zfs/14.5/RELEASE
        /aws/service/freebsd/arm64/cloud-init/ufs/14.5/RELEASE
        /aws/service/freebsd/arm64/cloud-init/zfs/14.5/RELEASE
        /aws/service/freebsd/arm64/small/ufs/14.5/RELEASE
        /aws/service/freebsd/arm64/small/zfs/14.5/RELEASE
....

AMIs are also expected to be available soon in the AWS Marketplace at:

....
        https://aws.amazon.com/marketplace/pp/prodview-axdyrrhr6pboq (UFS)
        https://aws.amazon.com/marketplace/pp/prodview-7xtubzy4v4oo4 (ZFS)
....

* Google(R) Compute Engine(TM): +
Instances can be deployed using the `gcloud` utility:

....
      % gcloud compute instances create INSTANCE \
        --image freebsd-14-5-release-amd64-ufs \
        --image-project=freebsd-org-cloud-dev
      % gcloud compute ssh INSTANCE
....

Replace _INSTANCE_ with the name of the Google Compute Engine instance.
FreeBSD images are also available in the Google Compute Engine(TM) Marketplace at: +
https://console.cloud.google.com/marketplace/browse?filter=category:os&filter=price:free&q=freebsd

* Microsoft(R) Azure(TM): +
FreeBSD virtual machine images are expected to be available on the Azure Marketplace at: +
https://azuremarketplace.microsoft.com/marketplace/apps/thefreebsdfoundation.freebsd-14_5

== Download

FreeBSD {thisRelease}-RELEASE may be downloaded via https from the following site:

* `https://download.freebsd.org/releases/ISO-IMAGES/{thisRelease}/`

FreeBSD {thisRelease}-RELEASE virtual machine images may be downloaded from:

* `https://download.freebsd.org/releases/VM-IMAGES/{thisRelease}-RELEASE/`

FreeBSD {thisRelease}-RELEASE BASIC-CI images may be downloaded from:

* `https://download.freebsd.org/releases/CI-IMAGES/{thisRelease}-RELEASE/`

FreeBSD {thisRelease}-RELEASE OCI container images may be downloaded from:

* `https://download.freebsd.org/releases/OCI-IMAGES/{thisRelease}-RELEASE/`

and are also available in the Docker and GitHub container repositories.

For instructions on installing FreeBSD or updating an existing machine to {thisRelease}-RELEASE please see:

* `https://www.FreeBSD.org/releases/{thisRelease}R/installation/`

== Support

This point release, FreeBSD {thisRelease}-RELEASE, will be supported until {thisEOL}.
The previous point release, FreeBSD {lastRelease}-RELEASE, will reach its End of Life at {lastEOL}.
The FreeBSD {thisBranch} release series will be supported until {thisBranchEOL}.
Additional support information can be found at:

* `https://www.FreeBSD.org/platforms/`
* `https://www.FreeBSD.org/security/`

== Acknowledgments

Many companies donated equipment, network access, or human time to support the release engineering activities for FreeBSD {thisRelease} including:

[cols="",]
|===
|https://www.freebsdfoundation.org[The FreeBSD Foundation]
|https://www.juniper.net[Juniper Networks]
|https://www.nyi.net[New York Internet]
|https://www.sentex.ca[Sentex Data Communications]
|https://www.tarsnap.com[Tarsnap]
|https://365datacenters.com/[365 Data Centers]
|===

The release engineering team for {thisRelease}-RELEASE includes:

[cols=",",]
|===
|Antoine Brodin <antoine@FreeBSD.org> |Package Building
|Dave Cottlehuber <dch@FreeBSD.org> |Release Engineering
|Sergio Carlavilla Delgado <carlavilla@FreeBSD.org> |Release Engineering
|Marc Fonvieille <blackend@FreeBSD.org> |Release Engineering, Documentation
|Craig Leres <leres@FreeBSD.org> |Release Engineering
|Xin Li <delphij@FreeBSD.org> |Release Engineering, Security Team Liaison
|Ed Maste <emaste@FreeBSD.org> |Release Engineering Deputy Lead
|Colin Percival <cperciva@FreeBSD.org> |Release Engineering Lead, {thisRelease}-RELEASE Release Engineer
|Vladlen Popolitov <vladlen@FreeBSD.org> |Release Engineering
|Muhammad Moinur Rahman <bofh@FreeBSD.org> |Release Engineering
|Lexi Winter <ivy@FreeBSD.org> |Release Engineering
|Alexander Ziaee <ziaee@FreeBSD.org> |Release Engineering
|===

== Trademark

FreeBSD is a registered trademark of The FreeBSD Foundation.

== ISO Image Checksums

=== amd64 (x86_64):

....
  SHA512 (FreeBSD-14.5-RELEASE-amd64-bootonly.iso) = aca2c6146a975176eee6320f6b2ec063c3ada097cf1da7fa98c24c22fc6abc89bff32602ed6e8fa6d8d27a37abd18306d33413756425322f3c66f208ca2cb3a5
  SHA512 (FreeBSD-14.5-RELEASE-amd64-bootonly.iso.xz) = 4cf31d1952fe5925d8b482274dc0586665839ec1a14d64d5bc8c11769be1ba8102bcfdb6461f6718b1881747e100fa2ae0199b8be9beff5f677a91d43c00755c
  SHA512 (FreeBSD-14.5-RELEASE-amd64-disc1.iso) = 9121fac289cfe1b1845ea171ff35d3bde5fd082f0cc0f04ef7536d443cc263f7ba8033c85b019e5f635734c4e96b01dd1bc167c882fec9c77645fc883352763e
  SHA512 (FreeBSD-14.5-RELEASE-amd64-disc1.iso.xz) = 47f4bb5946455a0e0d4b8ca82c43fb9f148649c864ccc0fb9017cf8a132fa885fd9c87857c763fcc563abcd58ab8ddb50d8d764080ecb868708538b8f730131f
  SHA512 (FreeBSD-14.5-RELEASE-amd64-dvd1.iso) = 01b3e4c09a34f9502075ac8feb86e336720369d3e7f4d81c6dff686b75130a6561ef0c7402845bb3c2b4a0fb4fed2313d4a6d0d67ba1940d28ff2e5dd8fdc901
  SHA512 (FreeBSD-14.5-RELEASE-amd64-dvd1.iso.xz) = d8869c2762b889d494ee9edf0dafdef72ec519d5b65543e0cec7071a404e23b4dda06cef9f228cd5cea0cf2198386c0777773662de7925045f20fcfe2fa5973c
  SHA512 (FreeBSD-14.5-RELEASE-amd64-memstick.img) = 55d938e7482d79db20892a4cfd7c0196468dc9f769b3c71ec53c349163e1ca884ef8881140f7f5f598a3947ab0190878ecf813098527955d27f1968f7c5716cf
  SHA512 (FreeBSD-14.5-RELEASE-amd64-memstick.img.xz) = d1ab331758a6554d15e8c994aeb6630dd34766c9e454fbd0cb8d4af74276300ebe6db6d89480f4019af15ef13202ea57208f97c8c1f55ff28f3e6f9c93ff56ca
  SHA512 (FreeBSD-14.5-RELEASE-amd64-mini-memstick.img) = c403cd13ca21f890363ff3406cbd48dc125d0aa706a004f4f664e71149610230118ab3ab60245185f6710d28c4e09b4fd377cae229b2adbdccdb8d02ca84bfbd
  SHA512 (FreeBSD-14.5-RELEASE-amd64-mini-memstick.img.xz) = e28fd8039cefa1a93068546ea40c2f76072670d28f668d0d0c4245a8bb93e51ab0cb3340c40e8119fc431bb8e82b8de41a69a1dba623b6cd133cd57c14757729

  SHA256 (FreeBSD-14.5-RELEASE-amd64-bootonly.iso) = 33dd8e0bc682a08fc22b67313f44f8932e0e4aef7d2c9004b75840d03c0f79e9
  SHA256 (FreeBSD-14.5-RELEASE-amd64-bootonly.iso.xz) = 487853da9ede32d0213c669d230d11f41ef35a647439879ca273e57e6713ae0c
  SHA256 (FreeBSD-14.5-RELEASE-amd64-disc1.iso) = a7f360c8dbd4727a8d3213ac85f6eb9b51ee4ed2577a2c31aaebbcae3d921d56
  SHA256 (FreeBSD-14.5-RELEASE-amd64-disc1.iso.xz) = 6bd5a1040e00e4a45c8a7ab007d47a19f50f06186c3f77852cf1710e42216b4b
  SHA256 (FreeBSD-14.5-RELEASE-amd64-dvd1.iso) = bda03fd9fe0cb09f19043d47a2686deacd495bd43fd620c6033ada3279f731e7
  SHA256 (FreeBSD-14.5-RELEASE-amd64-dvd1.iso.xz) = 508d71e01444fcd0bfbb465f03b7607fb18bf11640a5d5c56b6c363496125cf0
  SHA256 (FreeBSD-14.5-RELEASE-amd64-memstick.img) = 910c718f7aefaa78ecd9f358755ee9cdf47201b8fef8cd203b0c0d4abd722682
  SHA256 (FreeBSD-14.5-RELEASE-amd64-memstick.img.xz) = d6df52cfe6b8c00206a31d8be90239c7e15f1c7b185e0ba7304d679d013de56f
  SHA256 (FreeBSD-14.5-RELEASE-amd64-mini-memstick.img) = 9899968f9b48f36d91ec03ab3683e7c2c76e49d78da5edda3f0b2eb3c1343d3c
  SHA256 (FreeBSD-14.5-RELEASE-amd64-mini-memstick.img.xz) = f8ceabee1c90ecdf998c85d7e90e75150fd797ef604d0092dfd834ae86cc0268

....

=== i386 (x86):

....
  SHA512 (FreeBSD-14.5-RELEASE-i386-bootonly.iso) = d8bf14cdb3a2bf207ca64e1b8cd90a1a976ed68f715c533f7897c45aa9342506824c15c19da4e4c8edce661592e7612784e3a45e8d396f011eb819fd34031ce6
  SHA512 (FreeBSD-14.5-RELEASE-i386-bootonly.iso.xz) = 45170a26de00e6c2744a3fd2bfe7b0e8ea294d3a53063f86e1e914740c8ffe24419eaa1842fadabc627ca56681e18065c37859cf9eee00e874f267c6198e56f5
  SHA512 (FreeBSD-14.5-RELEASE-i386-disc1.iso) = 955bacb41ad091d4fbc8c983c1d0f07eecff3ac5529c0152b8c3553fdf9545eca81c1bda68e062d6257cd52985fd089f60ef4acac8455ba96cf314609d098189
  SHA512 (FreeBSD-14.5-RELEASE-i386-disc1.iso.xz) = d72b2f2e223f57b13ea120bd8f38e0fde6482bdba97868ca2bb2a8a24164c2bbce1b66d7183d9dd6ba4d41e42b2d9e96313475fcb4f7058ac0512adbe059a6b5
  SHA512 (FreeBSD-14.5-RELEASE-i386-dvd1.iso) = 8275f1cd78eb55d25db6d8029223b1d4a4a32e7f2843d95c16713e03245f439d0d4bc49072b84ce28ad11c2eec3d56276bcc80074181284b5252f103248d9052
  SHA512 (FreeBSD-14.5-RELEASE-i386-dvd1.iso.xz) = 874235937df92b7712c51e8443644b0886d02a4029a9d9613b13f4406c340ac3dfb2b6d95a3b87bbb8bdc2241ccbcfbc2a2a73f92c861d4e347be43e6c48744d
  SHA512 (FreeBSD-14.5-RELEASE-i386-memstick.img) = a9e2c304d7005ce6201585476552aa4520e1e3fbd67690ead4b01df2bf42c1bf4fc4d081c744bfb2f21666f450a1ded2031e78986417949ff45d9340688feb7e
  SHA512 (FreeBSD-14.5-RELEASE-i386-memstick.img.xz) = 721afee5d173671d8f869273b9c56301dc36656e5c2c0683effecda29ec57b097c9f6a791fe7c675744ca4a657d3a8cea8da063d1f4ffcb249c3b3ced8edd17a
  SHA512 (FreeBSD-14.5-RELEASE-i386-mini-memstick.img) = d30be9e1873e55f9b6153c7baa16faa79f22b15f971300f8988219a5427bdc80de9b4caa1d6044d3c5a8b283842f91665a9a52dab5a60b9ee8c9c5c475dde9dc
  SHA512 (FreeBSD-14.5-RELEASE-i386-mini-memstick.img.xz) = 5b9f43f86f27e4bd68ee1d3c2b454d642b434bccd24ae74dfee18052591ec42eaa722a5cd97ba4ba07a878f47050ed290b18d1492ce43962e0068f96d5bbc88c

  SHA256 (FreeBSD-14.5-RELEASE-i386-bootonly.iso) = e24ccba2355d798f46ed4409278a13c422f82962b0f8811755c5cd930442248d
  SHA256 (FreeBSD-14.5-RELEASE-i386-bootonly.iso.xz) = 0292155e79d6223b2dcb34dc6d739104a1730ff1480d8110e817e417b122ba83
  SHA256 (FreeBSD-14.5-RELEASE-i386-disc1.iso) = 697280ea21c3c17d82391429a93d817f6cc0e14339802b2568fe27d2dbc9df1d
  SHA256 (FreeBSD-14.5-RELEASE-i386-disc1.iso.xz) = dc9f2964f6e1fdd48620b684e51b33f7703c2b11c8a11b07371741d61a2e3e5f
  SHA256 (FreeBSD-14.5-RELEASE-i386-dvd1.iso) = fb794435526bbef3d2da54be9046d141b4773f9daf59f25895e007a63f5fee39
  SHA256 (FreeBSD-14.5-RELEASE-i386-dvd1.iso.xz) = 0a192f2b8bda13e680e1a266f168819bf41ab0bb0679dc58ccb59c6c459c4acd
  SHA256 (FreeBSD-14.5-RELEASE-i386-memstick.img) = baf9ceb120ca0ffce0fb3aea6cebe58728a4bbb7bb0941ed7afbe3920f8ef0a8
  SHA256 (FreeBSD-14.5-RELEASE-i386-memstick.img.xz) = a435bf5a36bae9284ba3146868cec257d38da665495d366835bdc2dabe0aefe8
  SHA256 (FreeBSD-14.5-RELEASE-i386-mini-memstick.img) = 13002c842c47eb43c0ababb4c813c3a4c62dc944bf02a718828c163bd627ffb6
  SHA256 (FreeBSD-14.5-RELEASE-i386-mini-memstick.img.xz) = e32ce3277a7cb8688a065d160a8f3cb180228850c4df2b1e13535df0dda8f917

....

=== aarch64 GENERIC:

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-bootonly.iso) = 141eb5e307e49bcb1923d8fb3e0de5e156a6c3acfe2e7e85e85ec00409872f2c8d99dacd8e5e9618b45f7ce59ed8821d20f0c839594b6380e9e82395e5e29af7
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-bootonly.iso.xz) = c2192e9fd0f7f8c9a311120fa470535a92887635ba9f70f6bcf3834f07af11b34b2304ad4dea03dd1b423529f4e8508e24ac003605b91267ace75f5eb33a7e6b
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-disc1.iso) = e134e4935b7975d028f8310dbab6ce0f7302a90c86bcedb0003129a4f8ef4fb7388f24cb44105484927602284a6847d3263f659cc0cf552a480caf34dce8de78
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-disc1.iso.xz) = 37ab9666973490cb7ba325c7f86c9280ce25c7492a378576d4e5fdaf10cd7b31e9665eb5bb2c6753c850f02d0262b4a764f03e1b53e317860d45390d6f6d631d
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-dvd1.iso) = 173adf664b21aa9c4dd4f668b10d49b1e9e6327ac9d8e6fa349fa7448805c9aab56216e6213173a0cbc49f198596176c6656721c59975c2db556fcf5f4587dc7
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-dvd1.iso.xz) = c27424e62dba1aa0a19575edb50c121ce14a6c270ed3ee400dde14aed886348f2f13aad7f1f23113aa6a782c605d2ebbdec5b93698cb5619abe1a90c08b63fef
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-memstick.img) = ee6c8b56867b321cfd4c80b45bc2a6dae3dc86d8208076db879ff2c70ae691764a1f278c01b1bea8ec01eac4869110d96f3c0d81063646f7f35ea768e2d63c96
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-memstick.img.xz) = 58686db7a1d2b887f97e35c9f7e98b115b4f0c91f9657e81b0b4b182fb0016e9a910f1fe4008bdacc1340a557200267f58968234617472b44121bb42cde69046
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-mini-memstick.img) = 03bd45d6b3496db16b1e82bcbbf57cfc11de73e1766997d29c12f2ce093fed3adf8f19498ea1a23cf1fd4d01fd97f6b1e39321aab5b90556531ebd0bda5f2cc9
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-mini-memstick.img.xz) = 3ad438869636b1d427957e7624ea8db9c4d96e32b5234142baef220b9f8684aeb6f4b2f41bd0ae3db3051cc87a916a4d7ffcf41a0a2cf8cb3ee4a7ba22f501ac

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-bootonly.iso) = f83d67f1206bbd7eec151000bd6971166a01d9683689977d9b9a0b9a57b65dac
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-bootonly.iso.xz) = c9993bf8ee1cf5a5a21a76bc7f65cd33895f5ce2f88d3e16a3dc9461ada7a308
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-disc1.iso) = e02942ca7856c7822577d7d5cb1e8fd60b02c2936612d73f2b6f0d8423f3844b
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-disc1.iso.xz) = 56ad645bfe4c7b1004a1c5ca3e16dcfaea888535e5218e1c62e659f754a91e05
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-dvd1.iso) = 1587572fe117f5929ad99f39559521993897428639e4f5c16bfabc1e05139a74
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-dvd1.iso.xz) = b1e571cfe2e36b6146785b48adb455d5c66784b0d91247786a253632f4fc26dc
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-memstick.img) = e67928775828b57780f32faf9a7bc0068025d1181ca2af6875f4e48424e4bb55
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-memstick.img.xz) = 87f4ecc43e5b5d1df8686efcf9b1717fa21057d93888abeb5efbaf9383051d97
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-mini-memstick.img) = 55e716884cff8b6ccce5ae23fb92044e5018be83832553b097ae5371054032ab
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-mini-memstick.img.xz) = d1ef4172d0be323856b9888cbcb1cbb1327fcf49694872280c13dc09e5559600

....

=== aarch64 RPI (3/4):

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-RPI.img.xz) = 67806cd9ee9a552a674efecaf68c11045d27e8fa4e474da0afacef1cf4a8d10d849e481c018ead7d31cf9550cd7cf704642e55c0574f38b25a23dbe432addbea

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-RPI.img.xz) = e0b4c63b4fc7c0a897568eb7df04a830cc17bf0c415f12c248884900b8025b17

....

=== aarch64 PINE64:

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-PINE64.img.xz) = 2e2262ae6936c89391663c0fa681243f0d5c1815a334402cb49f55a3eed24b5ef61b62f02dd239876ff2d883e111e0c8ba04a78655a2a06a29cbe122b022e97f

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-PINE64.img.xz) = bb423633bbf60c2bd40665937c89967999e28d0f6be3ea903c13c9c3e8380ceb

....

=== aarch64 PINE64-LTS:

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-PINE64-LTS.img.xz) = 623196623504b17da5935a586320070d5e43276458c3bea8d77ea34d03bce0abdcf165e93abf39672299ec6a67ebeebc669b920d9f429409ffd291589405102e

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-PINE64-LTS.img.xz) = 2eaf639869665d20537ca1bb89af91b37d53c5d2b2af28c1ecf9f66c90fe56ec

....

=== aarch64 PINEBOOK:

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-PINEBOOK.img.xz) = bc1a14dce2b4a6d5efb270c82ccf6065f3da4cd18d463fc732248d1516a6a1cb0ab10eff9f382dc51300f21d413438c592602a4b2b93932ddc74d3cf3e59755d

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-PINEBOOK.img.xz) = adb315a8dac632b668a4efd359c836091672ad3a3d0c6539a3b1baec1ab38fbd

....

=== aarch64 ROCK64:

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-ROCK64.img.xz) = 2182bf09e702c75091cce93d18b6ca962b63cdd53dd5527c7907b4257e3362c798959d603a29e61e8f0a6b57cc5b822d33656ae3d3d75ff4d20b9cd5d87ac6ba

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-ROCK64.img.xz) = bf09f18bfb9d6d07a543ead652fdeace7a459c1851d57bd0a7bbec1ed1178b0d

....

=== aarch64 ROCKPRO64:

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-ROCKPRO64.img.xz) = 60846674d44f32a64eef0d020c6a8a687fe63a509c16ff728a348dc7ffaeddd7d7e01684b559421c9b06856d4ed022728bf9b4c0e93e8ae6658d1cbdaf508d53

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-ROCKPRO64.img.xz) = 3cc27bc857641b6e7046c229ef4f0f5e7760239daecdf1994ee33bdf9fbdcf73

....

=== armv7 GENERICSD:

....
  SHA512 (FreeBSD-14.5-RELEASE-arm-armv7-GENERICSD.img.xz) = a5a127811cd20145ca5008f27528394f3fb559992098d1060c6fe09f0dc21877045f462fbf4702796d20495aacf8a562950080ce152b88af32a5f0e092bc3ece

  SHA256 (FreeBSD-14.5-RELEASE-arm-armv7-GENERICSD.img.xz) = 8e1f0b3230cb70f9668c4231a6b47332bc54f69f0b4328eca11621dafb396949

....

=== powerpc:

....
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-bootonly.iso) = 92acb817d5d81842f75afd5a5381fa73b12ff2c56f3cf3a926d8756b7198eb83287f7e201864be94cf53a02fef23df46db9502715bce451a484529ea5ab07552
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-bootonly.iso.xz) = 1d3163423c1c80be7eec82d307cd27243793e9bfdd2395445ef112a8e508283e11c73a94e8130f2d2f7bc6aea5cab4c5bfe157e5619668b930ff882a8030e93d
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-disc1.iso) = ca77e1e36287796865c093f65e53f616749db24f9a2bddbd23c4d9ac626e7040171fd30c5e703570d33f27860c87a20972fa87578eacec71624efaea149367b4
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-disc1.iso.xz) = b797ea0a00cfc986dd9a11508271b3cf65c8be9f0d5e61fad1f6427c0a3978ce8e650df4c1c74448aaa291f7736d521513e6c55ba257854de5dc0ddaada1ba4b

  SHA256 (FreeBSD-14.5-RELEASE-powerpc-bootonly.iso) = 7788ab19bea9d70350b5134bf257d03f9f60846a500ec8cf3c52e6b842c640f2
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-bootonly.iso.xz) = b1a6f4740da8632b73705387d5c97b14e71729d810bdca229026961f87810c57
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-disc1.iso) = ba604f4e144f95d6b9c7c43e8a0b718d7b52df294cf13d759a972466cfe8ae94
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-disc1.iso.xz) = f43683c5e7899b84ef26192128d40f49a87050c0c616d10d2ee679e9ccacc548

....

=== powerpcspe:

....
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpcspe-bootonly.iso) = 81bf521c52bac7d3301a705b23b790dca1a8cdb73042f8d4b2da0b66f98fa0306e996de86d44f1fa03d8ef09b439b5b9d0b03b781b6de0ac4c7005a4932fe176
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpcspe-bootonly.iso.xz) = 49c2d4950a1ae539e2160dbed6d97aa8b1c7438db05335a9e6d8c6491a9c80113264219f999c921f3ff764a03c5d3a9e963aab5dd91d95b51326cb43efc2012d
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpcspe-disc1.iso) = bbd8050ac4cbc4259368d6156c3ffa721c5df5e4740c405335c58056b84d428a9bf5d5dd6dffbd7b95b7683d9e766974ce9631b334492be33691706d2b2bb5eb
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpcspe-disc1.iso.xz) = 38f1ed85353e38661f219fb33a52ef6f931636126477cc600b5605e71346b32943b376b639a75e8d799c3c64f6d8540a078bbe042fd4ecc068bc46eee5779d97

  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpcspe-bootonly.iso) = f363ff402a2faa1596609fd9fdffd5a0cbdd97d9b89b8a09552191a3d6504e1d
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpcspe-bootonly.iso.xz) = 067df23d4faf2ae30864024d5e0608331a2ff56dace3612aee45d880d1dd38cf
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpcspe-disc1.iso) = 1c19ab1aba8b879d188aa8bcddedd0e4691187765681027c6327f29611231f17
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpcspe-disc1.iso.xz) = a5dd644956357b4c90165a47b999c91079086b14b4feb2e8a15e2308ef780be1
....

=== powerpc64:

....
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpc64-bootonly.iso) = e064b3cd967d9b97c36e990917ebf84b857c9c0ce578df710f3e6548990a23c4f1e5f4eaf2cf0aa84c33e191a2770d464ada722a7caaf7185ab138cd410c082f
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpc64-bootonly.iso.xz) = 43fd3213470c70079f32fa74121fdfb4d7477a46f4cc3ba1e243687d2697a4d50e27be5f2bea1e6e498bb164aa57324da85ce5dec2eadf7235889909e90940e1
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpc64-disc1.iso) = fa65f82edfb05b2e6a8d3bb1b1fc2d3843035fb04cbcc7357b0840b3bdb51b5b4baa0cac9179e2dfd4025709ad8685de881c169628dd7ea72776254c98b01647
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpc64-disc1.iso.xz) = 1b9cd3029103df54d1142ef2fffe1018f94b37fd63cf022e3e7e7695f085c6b9fd4a05ef11eaddcff6360c4a20978d83582fdc95a0483e8e88a55eb0a592c82f

  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpc64-bootonly.iso) = 3b569ee7a85f5ca49b3baa4edabd9eb3a443657fa4914e42fbdd6b4f6d272b59
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpc64-bootonly.iso.xz) = a710e973d83bbf2472e53f633fc03ad47cf5d62980c5f79e0a57065b6728ae31
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpc64-disc1.iso) = 4c2b6748305a5c0d4ad6787f8ba1aa2ca45f8d02a6199fd27a2faca5ca4dd0f5
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpc64-disc1.iso.xz) = 545740fcfe226c5034bb85ddba4226b23373f029668fe90a333c55fcab049327

....

=== powerpc64le:

....
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpc64le-bootonly.iso) = 650ba9d7e0dad981e68c55dcdc324ceab1946415210ef910720e1ec0d2875445884477ad63cd063dd52f40e58d8899ba40e17da262d37f6e800d60dec406856e
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpc64le-bootonly.iso.xz) = bdfccc02bdde51130d6ca22152fece0c904668d1f99f5e55152be15efe25062769b626a5f5c8ff1090882da1645424990dafc9d20902e132c5b64527d1d8c5d5
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpc64le-disc1.iso) = e3b059de80ee9d1d5398bc13c706f187bbb7abe7c84adfb7be806da740e59c3b2f1d4d27d7e10b703598fad594587b33465d048d7a3157feefba1c2db2aab566
  SHA512 (FreeBSD-14.5-RELEASE-powerpc-powerpc64le-disc1.iso.xz) = 479ddf12c85c7b73b7a591b525aedd966b24c4c5d99e58962bc24b0d692664df314dcbe3e00384203557836ec89458db39979668b453e42ddb4915e7b764aff1

  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpc64le-bootonly.iso) = 23576c1ba5b21dad8541a046d7e8b3919fcf6404c05705ab663d975df71aa56a
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpc64le-bootonly.iso.xz) = 2c61f5429a765df7408e6251f191c56ad55c3d91ee0918d30484be90034eee1c
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpc64le-disc1.iso) = 96b7ea4e6a490d0a9c4c2d7e1173ff995d3b3d39923e4bf6d9c2f938b2cef5fe
  SHA256 (FreeBSD-14.5-RELEASE-powerpc-powerpc64le-disc1.iso.xz) = 2898507e12c7de82183a5de38732eb4e5fc552f05808064e0b7b5f56ba515530

....

=== riscv64 GENERIC

....
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-bootonly.iso) = fa60a260605d47d2e0be06e88a1c10a0a69b0a36179999a63489b71ad609b8ed9538b836d55832420297fdad0cac3bd546f5a67d8e7fa9ad3498ed53499f2b47
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-bootonly.iso.xz) = 3c03a47d3a7f351994321170b9c256d39ce11620ddfafa207b0d31a3136d3c81eb9ccd0427e90a5fa63e6bbbb0c19c728bf52574cbc8f57741b69860db7496a5
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-disc1.iso) = 259c916a6279c881fedd8075d4d5cb0a5f86a925ecddf78fc499d3d15a5cd4b92b3fed6f0d8b620b963f2271b15b105d0fa9217ece84b7128c78e578d9069dfb
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-disc1.iso.xz) = 58435c16e37629803738c28bb14278bd951908ac7f7bb609846c312d75ac1601228ecb140b83e66dc9e514baa5c244597faa6ab784785cad253bfe9460b9ff44
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-memstick.img) = 23206e97797b02dd4d0be5e243e76cbe8179afde34743ea553e17d42984877e7517b509c36318108ade951f90bd5fa660bfc38487cf55811ec3b47cdd142cfcb
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-memstick.img.xz) = 9807386f509cd644c75d04cf8f640be410e3b45b835f1f96a75b2bcb85a776524b4ef83e314f1621cfe3f1638696425dd8ebe22e49d2309518a3d66f2815a8e3
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-mini-memstick.img) = 8e24aec02a47845ad2de60701d1797a7ac9c4f8d480d912e361dc7afedcbd5cc3c9e1e9c92669482c89ed25f99a1eff9a44a40c49a0605652aed683c2ff1130d
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-mini-memstick.img.xz) = 31d58b60bf33fcb9c1b520645dedc12e7fecbf0cdea6042baf26eef67fd4e408cc99fd2e15d5c634f83d3111bf92acded71dfd6701aea3f188f30157d33480ec

  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-bootonly.iso) = 7b4597d04f3621351facc9d4055983ec580a4aae5ce1d83fe12405ec0419d7d5
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-bootonly.iso.xz) = 69b6011ca399ad87f8323cf394d0989985c1399d8008afe59eead9022b663a2a
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-disc1.iso) = 17e8b3d3435238853f39f9587f3b6bd790c4f21b8e241d5f324e972e974d7a58
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-disc1.iso.xz) = ec0327429eff8fdc5268632965c50047107f93eb8838eacc127853abbe58bf72
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-memstick.img) = 86454522357037923e878e6e8e7bbefee4c52c5c9052cab31f88d5af5ec99b78
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-memstick.img.xz) = 4cbbea797a9442e5a791371151fc7f2c363fe9224465455dbad73f5b42fb27b1
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-mini-memstick.img) = 5249bd03e369984fe9615072310ece6822f061860e1a1a5a394c970e52729b93
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-mini-memstick.img.xz) = 58289d2b905d5343b68464ecf9bec0190fbca69a9d6c9c8a22d9eac1eea4cdf4

....

=== riscv64 GENERICSD:

....
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-GENERICSD.img.xz) = 5a181e4c0a912934966c20bc093d2a8c8446c8ba0870d438e6b722846f035d1f297e3871ee0c620cc9b2e3780eb4796ed1cc7686e569af5c510bbb58ab9059b9

  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-GENERICSD.img.xz) = 0e41a431e77ec6adaf0b1f773cf3ad90522cd2c0d5d39386f9f335faaef7cd5c

....

== Virtual Machine Disk Image Checksums

=== amd64 (x86_64):

....
  SHA512 (FreeBSD-14.5-RELEASE-amd64-BASIC-CLOUDINIT-ufs.qcow2.xz) = 6778efae749f3a7ba2c6c953e15db9dcc633b51ce824bd8e6f2b0d9f447222555e75329fa89eec8b600aee62f5856335ac8a7a3273a2018a92c7715074b03b4b
  SHA512 (FreeBSD-14.5-RELEASE-amd64-BASIC-CLOUDINIT-ufs.raw.xz) = 8b3b739641be99eeacdc4a8883d69ea0aa90dd5c016026dd352eb3cbc9e8c9a4f0147d1b4afe7052f90ac4caf9bdda5f25f0d3f14561043215b20a65af6e9065
  SHA512 (FreeBSD-14.5-RELEASE-amd64-BASIC-CLOUDINIT-zfs.qcow2.xz) = de3d078fbef3fba53e2789b97a9af2dac3dc294f852c2abeeea5454071528c8668497839a87a58b27f98e0b3a961cc266763756d1a50aae921a3e325e305e6ff
  SHA512 (FreeBSD-14.5-RELEASE-amd64-BASIC-CLOUDINIT-zfs.raw.xz) = 98311a15ee4c951b54e9283ee9d673e177ed2bc89690bac437fb8ea9947afc33b350a94cd8b03467ea96efe3b595337e5f241f89c94b71dc2ed06251bf80f61d
  SHA512 (FreeBSD-14.5-RELEASE-amd64-ufs.qcow2.xz) = 9960eea5f5dfbd7e95de023dbf3cc5771dabe1dd633a98f2069ac99b3de8d444455df313fc15da5de8d149cfb5d65eee25526d7fb30bb04f75b8c65a85e59bf6
  SHA512 (FreeBSD-14.5-RELEASE-amd64-ufs.raw.xz) = 90c6d24a01286f12b6294a9a2b0e706e9b52dd7e52ce3bbe42731a6eca771f98941f6fa1109831ce1be2a5e72a48c57d6c3a2d66ae272427337816bfb17ece4d
  SHA512 (FreeBSD-14.5-RELEASE-amd64-ufs.vhd.xz) = 896a800deb9e92ddbcb5879d3f655c2ab62ccb1054ade43cd71e51ec9f5ada26504c695d2d93b3d6b433ecf4a9edb47e1293f8ad5b8d4239a976eb9f09d2d37f
  SHA512 (FreeBSD-14.5-RELEASE-amd64-ufs.vmdk.xz) = 31982219b8290284c7208f4b586dd2688f2fd1826325163b64ae36b895f189786994cf8851a04dce8817ae339652b0cc4a9a21caf933e0c371ffc71be9a98d62
  SHA512 (FreeBSD-14.5-RELEASE-amd64-zfs.qcow2.xz) = 4353776ba572857a59565a489c70ac7a34fafe171962766ebed8dc76e5eaaf56834555f1634d569aaef59dbce388ca911aaa2df3c4dcb9707921670c77e56491
  SHA512 (FreeBSD-14.5-RELEASE-amd64-zfs.raw.xz) = 0359b4a966810577f61cfc949f34f956428fd6b9de4595b9659d88cd526f003c19c20d1f912fc6cbde71fb3dd30d53582761ef0e4f436e490e996770f4e9780d
  SHA512 (FreeBSD-14.5-RELEASE-amd64-zfs.vhd.xz) = e0407e3304b1614bd3d2f3ad31cd8253540e81c67f5ce2ad3b9f165f8fade9bb4dd2db752ff5c51fe8d0e733a98c9fbaf2b3f07e0fd205a20dab2f36e2cdec29
  SHA512 (FreeBSD-14.5-RELEASE-amd64-zfs.vmdk.xz) = bdabcd0bbfdc4839ace4a4744bbecf2dea0498f792928575730949bcca9135649ed362ccb392411a27ea134b1f161859dd43941396aa02c5b73c892065e0ca66
  SHA512 (FreeBSD-14.5-RELEASE-amd64.qcow2.xz) = 9960eea5f5dfbd7e95de023dbf3cc5771dabe1dd633a98f2069ac99b3de8d444455df313fc15da5de8d149cfb5d65eee25526d7fb30bb04f75b8c65a85e59bf6
  SHA512 (FreeBSD-14.5-RELEASE-amd64.raw.xz) = 90c6d24a01286f12b6294a9a2b0e706e9b52dd7e52ce3bbe42731a6eca771f98941f6fa1109831ce1be2a5e72a48c57d6c3a2d66ae272427337816bfb17ece4d
  SHA512 (FreeBSD-14.5-RELEASE-amd64.vhd.xz) = 896a800deb9e92ddbcb5879d3f655c2ab62ccb1054ade43cd71e51ec9f5ada26504c695d2d93b3d6b433ecf4a9edb47e1293f8ad5b8d4239a976eb9f09d2d37f
  SHA512 (FreeBSD-14.5-RELEASE-amd64.vmdk.xz) = 31982219b8290284c7208f4b586dd2688f2fd1826325163b64ae36b895f189786994cf8851a04dce8817ae339652b0cc4a9a21caf933e0c371ffc71be9a98d62

  SHA256 (FreeBSD-14.5-RELEASE-amd64-BASIC-CLOUDINIT-ufs.qcow2.xz) = a2a8cd84cd59077225a0e75ead852e8a08fe26f9ab251a96d5a4fd4fe1db4454
  SHA256 (FreeBSD-14.5-RELEASE-amd64-BASIC-CLOUDINIT-ufs.raw.xz) = f5fe75766bb152293384a34ab392c4cc101921d20cb7f45e8f3b9609bc977104
  SHA256 (FreeBSD-14.5-RELEASE-amd64-BASIC-CLOUDINIT-zfs.qcow2.xz) = 126138a9e3b68641579b9f05105c1fdd9dc2e0eb2b5a02737908f629888fe8e7
  SHA256 (FreeBSD-14.5-RELEASE-amd64-BASIC-CLOUDINIT-zfs.raw.xz) = fc22b709db0e384de89e2048903790e726867071470765b924445cdeceea0c65
  SHA256 (FreeBSD-14.5-RELEASE-amd64-ufs.qcow2.xz) = a027c3a9deafa5af07a8f910c38aed3a58e9adefa18ffb040bc512ecfbc1799a
  SHA256 (FreeBSD-14.5-RELEASE-amd64-ufs.raw.xz) = 1dd19661a4dd0ab80b2315a352245ff38b28f1e96b4ea982bf833daa826254e7
  SHA256 (FreeBSD-14.5-RELEASE-amd64-ufs.vhd.xz) = 26bdacc73d4ea12163142e8d25a1a27cf9adc2a8b0ab751001d53fe2e005ef2b
  SHA256 (FreeBSD-14.5-RELEASE-amd64-ufs.vmdk.xz) = 5de60a19be87c0e51524520e2a21de920bb428d698a7ecd54b5466dc3e3cc4f0
  SHA256 (FreeBSD-14.5-RELEASE-amd64-zfs.qcow2.xz) = 7060198dad071373d42b21ba492c83c9451bf94335870644ef4b30dcf6cca9c8
  SHA256 (FreeBSD-14.5-RELEASE-amd64-zfs.raw.xz) = 1e5428fb486b4ea3ab660456ab1a969694b669945c0cfe617afcf61f38c36d6d
  SHA256 (FreeBSD-14.5-RELEASE-amd64-zfs.vhd.xz) = f83551519b5bc20279fb13ac3a2e88f9ef3d5c419436e01491dbd879274a81be
  SHA256 (FreeBSD-14.5-RELEASE-amd64-zfs.vmdk.xz) = 308044c799953264ea886c77406bd243839e16eb0ed57916c8533129813cd154
  SHA256 (FreeBSD-14.5-RELEASE-amd64.qcow2.xz) = a027c3a9deafa5af07a8f910c38aed3a58e9adefa18ffb040bc512ecfbc1799a
  SHA256 (FreeBSD-14.5-RELEASE-amd64.raw.xz) = 1dd19661a4dd0ab80b2315a352245ff38b28f1e96b4ea982bf833daa826254e7
  SHA256 (FreeBSD-14.5-RELEASE-amd64.vhd.xz) = 26bdacc73d4ea12163142e8d25a1a27cf9adc2a8b0ab751001d53fe2e005ef2b
  SHA256 (FreeBSD-14.5-RELEASE-amd64.vmdk.xz) = 5de60a19be87c0e51524520e2a21de920bb428d698a7ecd54b5466dc3e3cc4f0

....

=== i386 (x86):

....
  SHA512 (FreeBSD-14.5-RELEASE-i386-ufs.qcow2.xz) = d2d2814948301a08492e488a569f9fa6ff6110839a8d84bd1d96145931cee9738fe79c0bae97194ae7444a6e7a7c985169163f7ba7304ff49dcdd78f60ec420a
  SHA512 (FreeBSD-14.5-RELEASE-i386-ufs.raw.xz) = 3effc7a0290991e1eb156d4a9b51d580553f7a6b1aaca64174b4484320d5930d7873a938afa554d31934e5fd910e574403694f512b1b1fae05c54af43e730b20
  SHA512 (FreeBSD-14.5-RELEASE-i386-ufs.vhd.xz) = 108bf8b3d1f94ee00e14e83ac170dc7532656f9ed72ed1693ec10c181b4873d7b8a7fa69a7a9ceeaf15ed72c79378820e4afcd6561a5900f7cabb34b4ff31b79
  SHA512 (FreeBSD-14.5-RELEASE-i386-ufs.vmdk.xz) = 56042f0a63a4c3dbfdc679e5c8ca083582c9c14572d6e4bc9c89d66254566d608ae8f768803db67ae3f43aa96e3fb980831b1c1b0866340472444720823b4aa1
  SHA512 (FreeBSD-14.5-RELEASE-i386-zfs.qcow2.xz) = 7e5f380d4f685ee375b261486e2ea4ff1368db0da708440ec7daf29809a1d8e4790839a0bd9d727ad6f16c8f0191663e6d8963449832b00a1f66ac64cc901bea
  SHA512 (FreeBSD-14.5-RELEASE-i386-zfs.raw.xz) = a59409c20cdc0759cffedc26a3861041d55bf191cc8d0eeab7e917077598688ebf7f503b9658c85d092908ee2a1e57901f3eb55773556e2cdab098dd8e948cab
  SHA512 (FreeBSD-14.5-RELEASE-i386-zfs.vhd.xz) = 9908f9d1411752cc21399a95f0c798ce831fe911b89c2879972ecddbd999a45b622a01dd9e9732c7fe3baaf31b2b94e7d92c4dba5775b835547d18da5e62968a
  SHA512 (FreeBSD-14.5-RELEASE-i386-zfs.vmdk.xz) = 103dbdd781a8643106b1ab53a12188a98d525f7ed7da115ad1306741883de73b9cbbfa2d4dd0cafc9224826e63b55cdfecf67ac7f3193b2f0611c4bf30d6ec7e
  SHA512 (FreeBSD-14.5-RELEASE-i386.qcow2.xz) = d2d2814948301a08492e488a569f9fa6ff6110839a8d84bd1d96145931cee9738fe79c0bae97194ae7444a6e7a7c985169163f7ba7304ff49dcdd78f60ec420a
  SHA512 (FreeBSD-14.5-RELEASE-i386.raw.xz) = 3effc7a0290991e1eb156d4a9b51d580553f7a6b1aaca64174b4484320d5930d7873a938afa554d31934e5fd910e574403694f512b1b1fae05c54af43e730b20
  SHA512 (FreeBSD-14.5-RELEASE-i386.vhd.xz) = 108bf8b3d1f94ee00e14e83ac170dc7532656f9ed72ed1693ec10c181b4873d7b8a7fa69a7a9ceeaf15ed72c79378820e4afcd6561a5900f7cabb34b4ff31b79
  SHA512 (FreeBSD-14.5-RELEASE-i386.vmdk.xz) = 56042f0a63a4c3dbfdc679e5c8ca083582c9c14572d6e4bc9c89d66254566d608ae8f768803db67ae3f43aa96e3fb980831b1c1b0866340472444720823b4aa1

  SHA256 (FreeBSD-14.5-RELEASE-i386-ufs.qcow2.xz) = 05763f7c70404d7084148391644ad1a8c26796acf8ebe01fa90cc6a05ad923df
  SHA256 (FreeBSD-14.5-RELEASE-i386-ufs.raw.xz) = 40f6e4a3f92de5694d1c27efc1d934dd4fe593875f49908c812675248595eed0
  SHA256 (FreeBSD-14.5-RELEASE-i386-ufs.vhd.xz) = 33f1e6601f6a491800a92b09682d9387fb596200531e3e18cd1bf81958d5e6ed
  SHA256 (FreeBSD-14.5-RELEASE-i386-ufs.vmdk.xz) = e04756e4d5c07338695af82e794a6ff466c23a8634f5605d6a730154528310db
  SHA256 (FreeBSD-14.5-RELEASE-i386-zfs.qcow2.xz) = afdf14b73f2cf71920f908e5a3dedc671515228667842fb913564683f4400b44
  SHA256 (FreeBSD-14.5-RELEASE-i386-zfs.raw.xz) = 2706992f7767213fd336782c6dee6980736620a430832aa048e2694aae442b69
  SHA256 (FreeBSD-14.5-RELEASE-i386-zfs.vhd.xz) = b87d7660b7286f6d80b2fa966f965b4083bd3d661fbe9f9b0067efff5a753fe9
  SHA256 (FreeBSD-14.5-RELEASE-i386-zfs.vmdk.xz) = c9581b598d4cb7959db7a75430c9c9b35f78b79388ca6ab93aac989217ed3aab
  SHA256 (FreeBSD-14.5-RELEASE-i386.qcow2.xz) = 05763f7c70404d7084148391644ad1a8c26796acf8ebe01fa90cc6a05ad923df
  SHA256 (FreeBSD-14.5-RELEASE-i386.raw.xz) = 40f6e4a3f92de5694d1c27efc1d934dd4fe593875f49908c812675248595eed0
  SHA256 (FreeBSD-14.5-RELEASE-i386.vhd.xz) = 33f1e6601f6a491800a92b09682d9387fb596200531e3e18cd1bf81958d5e6ed
  SHA256 (FreeBSD-14.5-RELEASE-i386.vmdk.xz) = e04756e4d5c07338695af82e794a6ff466c23a8634f5605d6a730154528310db

....

=== aarch64 (arm64):

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-ufs.qcow2.xz) = 27a7f049008bf245b6d88398ea76d21167eb1505df9e6e38c3bc37b3bc3e8ebcf32ed6502fca39cdc8017c5197e942a6dea8fbb94e29ed5438602935a605033a
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-ufs.raw.xz) = a1fa02976dfefed9476c4c5967dbcdbad901aca6951250ea4777869713f5345815b47ed13e9e68851639d8974384d99a20b9d1ef2af94a8de03f93af98766f3a
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-zfs.qcow2.xz) = 653c4f1a16901fa30bbfe41a2372f913138668f99b70841d87ba2bf554b7b2658b69da8758ca95c8f0f8793227e80d5c12e48543104b332deb5eadd4ff5a9339
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-zfs.raw.xz) = 9cfe06a37ef866537abf7ac375edf75902bf7c44c1e1d8dc02956412c8b42691e9754107fd4e9cce2fc97cc0bf8064aa7b6020b5bad2a6b42896c4f487dc2893
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-ufs.qcow2.xz) = 7a01e3eca74f36b1ca1d85476a6baa0345865bbd5b453c93c240313ff58e1354ec88cbf7e72e0ce4ff6d892b0ba18dfce8bd5960f6c860c30eb5382bc9484c46
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-ufs.raw.xz) = 66e2cdb538d30d716a783b6d9f17ce40ea7cc665006a73acc26c0d0d204284ed2dc46fdc60dbb51400d4aa73624c13ee42801bc32c4ef78433d01cb58fa09eb3
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-ufs.vhd.xz) = 4f3ce30537eb7dafa1b0dcd5c899b17877683c312e32c62dddca49c738d231ca6a2d328f75b7d1d4cd65f99c660469630cb4c019d67916ae47786756062bfb2d
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-ufs.vmdk.xz) = d9ddff536e498cdfbd6fc4963f3c68572b324a26bd708ee699788e4db9f125bdce07cb4ce7694339abab232ac9e8b88101c4237f7689db5c5cf98aa721b83197
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-zfs.qcow2.xz) = 9f8d4420080c53ebb0d3a25601d8b42badcdd04d8e4be9dd24f45f455bbe9177fbc39f32d9117cfd7f3a2a9bf838738c23dc65d17cdf3124d130d644991ff428
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-zfs.raw.xz) = f9f4e46677a27be21f1ab5739222c8c7f381e905fa3c3cc93d734f3a5bc789ca9d7e18b671cda6795efb279ca67419c7dce788380fd6a45f7ceaa74dc45e0568
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-zfs.vhd.xz) = 113392fedbe76190e4df30a8ae6f5987c5145cc439b43cfebc7aac3d4629e68997993f09e4300c246a38bd92bed482bae4290f00780b6185693a6ca08b2c7cf9
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-zfs.vmdk.xz) = 488e1d2b9f2fad0006af544ec3c55577c77ce9e1c9a126f8c6209d7e8df751de5b3882f6b0fb4b3db49229f5b27de56bdd45cab06b02cf1bfdfe4fbe2360ac8d
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64.qcow2.xz) = 7a01e3eca74f36b1ca1d85476a6baa0345865bbd5b453c93c240313ff58e1354ec88cbf7e72e0ce4ff6d892b0ba18dfce8bd5960f6c860c30eb5382bc9484c46
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64.raw.xz) = 66e2cdb538d30d716a783b6d9f17ce40ea7cc665006a73acc26c0d0d204284ed2dc46fdc60dbb51400d4aa73624c13ee42801bc32c4ef78433d01cb58fa09eb3
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64.vhd.xz) = 4f3ce30537eb7dafa1b0dcd5c899b17877683c312e32c62dddca49c738d231ca6a2d328f75b7d1d4cd65f99c660469630cb4c019d67916ae47786756062bfb2d
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64.vmdk.xz) = d9ddff536e498cdfbd6fc4963f3c68572b324a26bd708ee699788e4db9f125bdce07cb4ce7694339abab232ac9e8b88101c4237f7689db5c5cf98aa721b83197

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-ufs.qcow2.xz) = 8c0309f7aaa69674c3e657eb4d4642d5eef816094aea3c7c0b0b505a7049f0ca
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-ufs.raw.xz) = 26d68ac71da285d89e3143e090818760fd909fc8b644d4a201bee77bdc2a366f
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-zfs.qcow2.xz) = f660e3c3cf92483da37a4f8e176315e87f277c9da50439247dfb0f0835156dcc
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CLOUDINIT-zfs.raw.xz) = a8b5f945575c916d70ed6c0dee07977ef42e10dc641b006dbe46252a469600ed
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-ufs.qcow2.xz) = 3afc488c46810b3afc5297aede4849115b8de3c2699b365c5f4492ddc6ead517
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-ufs.raw.xz) = 8b07567c2cb4b67f75816ddffcd47aa886362313bf2fc944a4f54075bddc1602
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-ufs.vhd.xz) = a16e4b100b445b2cc9a23e5c57f217e5316c7a4a14e85c2371fd0dd2afcc9d80
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-ufs.vmdk.xz) = 74b3c1b591a675f397c73736d1c5f0738314734ac102a7e40c51a4b8ee35d035
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-zfs.qcow2.xz) = 43d6005e6d35b5368aebd9fa075d8d7433f403a5d382ee2b92465ba281ef9d59
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-zfs.raw.xz) = adf9a833d779a617430f601da9999b3dc8c533305c571a7e8ec4d79c961362f5
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-zfs.vhd.xz) = 85975a177e306fc90a5852699ab40951dceb977175238cd07a433168b3c3005c
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-zfs.vmdk.xz) = 72716f88d9ae3bb9098070bc95993bf8fb9367209e3752532fdde8fd08b4357d
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64.qcow2.xz) = 3afc488c46810b3afc5297aede4849115b8de3c2699b365c5f4492ddc6ead517
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64.raw.xz) = 8b07567c2cb4b67f75816ddffcd47aa886362313bf2fc944a4f54075bddc1602
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64.vhd.xz) = a16e4b100b445b2cc9a23e5c57f217e5316c7a4a14e85c2371fd0dd2afcc9d80
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64.vmdk.xz) = 74b3c1b591a675f397c73736d1c5f0738314734ac102a7e40c51a4b8ee35d035

....

=== riscv64:

....
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-ufs.qcow2.xz) = d3ae27b3f6c05dc93816b3d81b694fa93244dfaef89305028894fe1c5a92c6e12bdab8a237da6341aed93729b77173942d7aaa33a3084cc63a630026ab6c0a76
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-ufs.raw.xz) = 50063cd8756c51606f88ed6a6379708faded0bd7e368c2bdc13d00a176f569c698757be28df50c9aaff2ad6a2cc9b52418bc2a1095539c186805252be608cbad
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-ufs.vhd.xz) = 224bf20c178454d134580536087431f1f42f15ed1129d51dd9cd1d9628f8d33ce9a560b629d2504546989c34ab3b40c1c1ffaf2bc75625109a680ffbe199b02c
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-ufs.vmdk.xz) = fd356d01d7837958153ec5ea1283ecff459f767ac9e6651ef5aa51c7bf0702a7334739b48b24a456b075eeaa04734ac949f8dea6b30f91f90d37c8615f09ef0c
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-zfs.qcow2.xz) = 7700ea2d24a297ef44ac87828fdad63e421d11425ca45c3c0163acce153e4c3e2055c505757e7511631c891d50859389032718a7ceffb891651d58479cfa187f
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-zfs.raw.xz) = b7b34077f1016d708b241316b42903a595e3650ed2398a35b7953a9afe530d0690d7f4f67e3a12a116b9ad38a908940470e0613dff873c7b7c8b8968841c2cb1
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-zfs.vhd.xz) = 2ea848ff72c540594fca6539554151f4ae343e88db2cb5fc54e47ca7b427dca5cfb948fa5a189f0be0b2193dbfb1e2ddeb639c2afbadc829d4bf135e34759278
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-zfs.vmdk.xz) = b8c9d681ed2a19f18728d97ed9b711c5ff6d5027380e0e26b3a29ddabfccb15cf5963bd891dd9123e4bcfe3fd5b7fe3f99a1554cc7db5ca3fa25a51cefde585e
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64.qcow2.xz) = d3ae27b3f6c05dc93816b3d81b694fa93244dfaef89305028894fe1c5a92c6e12bdab8a237da6341aed93729b77173942d7aaa33a3084cc63a630026ab6c0a76
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64.raw.xz) = 50063cd8756c51606f88ed6a6379708faded0bd7e368c2bdc13d00a176f569c698757be28df50c9aaff2ad6a2cc9b52418bc2a1095539c186805252be608cbad
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64.vhd.xz) = 224bf20c178454d134580536087431f1f42f15ed1129d51dd9cd1d9628f8d33ce9a560b629d2504546989c34ab3b40c1c1ffaf2bc75625109a680ffbe199b02c
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64.vmdk.xz) = fd356d01d7837958153ec5ea1283ecff459f767ac9e6651ef5aa51c7bf0702a7334739b48b24a456b075eeaa04734ac949f8dea6b30f91f90d37c8615f09ef0c

  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-ufs.qcow2.xz) = 74629c6a51f0e3e78d2dade406a9b179cd454ddf0b8063af155f6a0194cc3c33
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-ufs.raw.xz) = 3e75eccdaa1b66b5299d680cd069dbc96ddb5c3aad6c98846daabd0e2e00fc8d
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-ufs.vhd.xz) = 7ccdd960406521b2fa5423d88bc7aea55e2c97bf4c31194457a6b2b84e85cb7f
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-ufs.vmdk.xz) = 5a7786f757f9e24fdc82ad69d3e1b088ce80d6838f8752672575afe8b7ce7726
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-zfs.qcow2.xz) = 195a06b0db39b1c9cb929e6888582bfbdd90582ccb99bb314d5d4e0b52be5a10
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-zfs.raw.xz) = b590c846c437fcd8234ea07e94570c6ddb596920b54fd639e05393e929b9cff0
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-zfs.vhd.xz) = a4b4dcfe34eba5494fe286ba6be2aa6660b0a9368c31d58383ba57066a508a3a
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-zfs.vmdk.xz) = 3868b94c53d95e187488a3655f9a81e5037e025eb4c665e620c6b107d3fb438d
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64.qcow2.xz) = 74629c6a51f0e3e78d2dade406a9b179cd454ddf0b8063af155f6a0194cc3c33
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64.raw.xz) = 3e75eccdaa1b66b5299d680cd069dbc96ddb5c3aad6c98846daabd0e2e00fc8d
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64.vhd.xz) = 7ccdd960406521b2fa5423d88bc7aea55e2c97bf4c31194457a6b2b84e85cb7f
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64.vmdk.xz) = 5a7786f757f9e24fdc82ad69d3e1b088ce80d6838f8752672575afe8b7ce7726

....

=== amd64 (x86_64) BASIC-CI:

....
  SHA512 (FreeBSD-14.5-RELEASE-amd64-BASIC-CI-ufs.raw.xz) = 2d69250ca4c73a26bbffcad57a30e19123019b167d0dd6eacd2a2606f0fd48f0602d5e80e6c5307a7495de205e069a9f979456401e2021006d00cc2406e94ba8
  SHA512 (FreeBSD-14.5-RELEASE-amd64-BASIC-CI.raw.xz) = 2d69250ca4c73a26bbffcad57a30e19123019b167d0dd6eacd2a2606f0fd48f0602d5e80e6c5307a7495de205e069a9f979456401e2021006d00cc2406e94ba8

  SHA256 (FreeBSD-14.5-RELEASE-amd64-BASIC-CI-ufs.raw.xz) = d3797afea543f53faac72f0b35fdc5c00f7e898cc8058b828eca251885239917
  SHA256 (FreeBSD-14.5-RELEASE-amd64-BASIC-CI.raw.xz) = d3797afea543f53faac72f0b35fdc5c00f7e898cc8058b828eca251885239917

....

=== aarch64 (arm64) BASIC-CI:

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CI-ufs.raw.xz) = f5feae0a91701a607e4690c727461137df24a0036d1ce9199e6cf33fe77077d8367ead884da5d167e3d6aa9507918791a73272ed144f4ed97417bf764bab5d84
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CI.raw.xz) = f5feae0a91701a607e4690c727461137df24a0036d1ce9199e6cf33fe77077d8367ead884da5d167e3d6aa9507918791a73272ed144f4ed97417bf764bab5d84

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CI-ufs.raw.xz) = fb95554873dfaac3e8e20fb5982ceae9c24c4f4851ae12c6bb4c5bbd770bf81d
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-BASIC-CI.raw.xz) = fb95554873dfaac3e8e20fb5982ceae9c24c4f4851ae12c6bb4c5bbd770bf81d

....

== OCI Container Checksums

=== amd64 (x86_64):

....
  SHA512 (FreeBSD-14.5-RELEASE-amd64-container-image-dynamic.txz) = db190a519bb298d2760c35290dabf08e935b174ed351eec0a3975e050c016132b37b0ccb730a79ac3e48cf6e86a6aeebf5d3c1e975596d108e44bc8119b1b354
  SHA512 (FreeBSD-14.5-RELEASE-amd64-container-image-runtime.txz) = f90af30c67e9a97c6ec4976192e5a03519f597e535167019d0b0e1b7211bdcf82982d3af86bc8e9fa8f9b7d87d11f402a7d93bd510f1b3663c239358c8d89a0e
  SHA512 (FreeBSD-14.5-RELEASE-amd64-container-image-static.txz) = bb3e37d537d42a81409bbbaa50ca75e60d2747cd303a7eb27b0a48835b7afaad9b069c3c4f4c5d4e170a1ff410bbd11fb7b494b001322c4a2e63e535c30130a2

  SHA256 (FreeBSD-14.5-RELEASE-amd64-container-image-dynamic.txz) = d86ac5eeaaf64e0d9e7d9307a477f314d7be4ab51896092262b852a2004fb157
  SHA256 (FreeBSD-14.5-RELEASE-amd64-container-image-runtime.txz) = 1db81c23b559837df69a00f33aed631c7b6ae5ccc4b0450b609dcfd9057c9657
  SHA256 (FreeBSD-14.5-RELEASE-amd64-container-image-static.txz) = ed4dbe6f0bc2c33fc96916fd6463edd02b90b2ec111ebba07791f833c94427a4

....

=== i386 (x86):

....
  SHA512 (FreeBSD-14.5-RELEASE-i386-container-image-dynamic.txz) = 4b5fb6ac65b05dd17ca80b22ff64d74dcaa5585e36b89d88311bdc82f156ff6c8d0182266fc156d55b849cf05be7d2ed48b56f59f9eb75ed7929022d5e96d79d
  SHA512 (FreeBSD-14.5-RELEASE-i386-container-image-runtime.txz) = 4b393a37a818be80279eae3bd4dfbb6f01b1aa8ad6eaf1447797a55c167685f9bcfb954c03ec1455d8198ef0a1d5a77faced21f18b76bd5ed5ed5f879dae52ac
  SHA512 (FreeBSD-14.5-RELEASE-i386-container-image-static.txz) = 759cdf9868ca85eb6ab077c5b8b4176ec10eb112d9c027c5fba59ac15199f5e076bafea2365dad171238b4f64b6bc96ccfb8866c72dc97b653a7e501287720f5

  SHA256 (FreeBSD-14.5-RELEASE-i386-container-image-dynamic.txz) = 58dc8819164b7db984fc00becefd3ea9b0d45f2052bb8403cb57f1f044b2b434
  SHA256 (FreeBSD-14.5-RELEASE-i386-container-image-runtime.txz) = 1c52566392a7528062c52df1081b580ddcafe4b916154538b0afd6917bd3f9ac
  SHA256 (FreeBSD-14.5-RELEASE-i386-container-image-static.txz) = 44e8b1df636afcfe09eda1d26133cb9cc1494e8f5703efac6259bea5ee684eb3

....

=== aarch64 (arm64):

....
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-container-image-dynamic.txz) = 6d116019f8e7d1ea066679bf94983f33b67b70c41aa3c6ef14efa7d626465b49eeb204e63f85deecd316f40bb61a919be1ab966c8410fd033eadc96c937b828c
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-container-image-runtime.txz) = eef287d78b6bf1b5652549edc4cfc097e3f45c43ddf14af988561c236ff8dfe1104f72bbe924b66f7d31023b3b3079eee5b12fa40fd537a85f790027d9199648
  SHA512 (FreeBSD-14.5-RELEASE-arm64-aarch64-container-image-static.txz) = e8c49018ad24c56efb64f7b0e28eeacb0aded4c7416eda84ebab8d3fc76af94c870522048d1538396dc31bc6f9fa9f463e61390f2738b73e58ad2cf7f6e55c50

  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-container-image-dynamic.txz) = 98413a3601937ae4cb01ace72bf958eeeb77279bd725c504ac36ca45079dbc3b
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-container-image-runtime.txz) = 4f08f7078470c14955ef117e30904756b7212ef97e4d004e81e9809f68222bfa
  SHA256 (FreeBSD-14.5-RELEASE-arm64-aarch64-container-image-static.txz) = cd4a9469acfdb367b3b244c5f2a4fae034d06f8c81c112783b6ef917c95a3cba

....

=== riscv64:

....
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-container-image-dynamic.txz) = 9358bf9782f4f080d39147f8aff8b546e10f620306deb5e871789a57e8d36f37849efcaa8c33985d9a9281ff555e04312d0c0dc3def36d1a1552b870ce634e83
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-container-image-runtime.txz) = 485367094c37319db83b4133b22dd4efe9cc335ed978a679d18ac8cb736e7e7ffb5db6eb34702b4f40be9746d4e33545bf53f4e650d69bbb861770d5836519b9
  SHA512 (FreeBSD-14.5-RELEASE-riscv-riscv64-container-image-static.txz) = ff2d1806ac7deed2716dca2fb9b0904c392f3a996d71c55362c053afa1a59b84ca5dba62730a411210ea26d9eb57dab1716135c7cb2b9ea5dcddfcdfc25d6012

  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-container-image-dynamic.txz) = 0125c987bdd47f7ffa185ea2a70ee0f3b614457229efdf5a0b789dc16cb304c8
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-container-image-runtime.txz) = 45f7fc887c26e49ca96142264623ae710925b421e1df8b629a364d10083be58a
  SHA256 (FreeBSD-14.5-RELEASE-riscv-riscv64-container-image-static.txz) = 8191ba25decd0ec611bba33818d237fa00865e23e5d22ce5a05458d8e0205808

....

Love FreeBSD?
Support this and future releases with a https://www.freebsdfoundation.org/donate/[donation] to The FreeBSD Foundation!
