---
title: Apéndice B. Bibliografía
part: Parte V. Apéndices
prev: books/handbook/mirrors
next: books/handbook/eresources
---

[appendix]
[[bibliography]]
= Bibliografía
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Tabla de contenidos
:table-caption: Tabla
:figure-caption: Figura
:example-caption: Ejemplo
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: B

include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/es/mailing-lists.adoc[]
include::shared/es/teams.adoc[]
include::shared/es/urls.adoc[]

Aunque las páginas del manual proveen la referencia definitiva para partes individuales del sistema operativo FreeBSD, son notorias por no ilustrar como poner todas las piezas juntas para hacer que todo el sistema operativo funcione fácilmente. Debido a esto, no hay sustituto para un buen libro de administración de sistemas UNIX y un buen manual de usuario.

== Libros y revistas específicas sobre FreeBSD

_Libros y revistas internacionales:_

* http://freebsd.csie.nctu.edu.tw/~jdli/book.html[Usando FreeBSD] (en Chino).
* FreeBSD for PC 98'ers (en japonés), publicado por SHUWA System Co, LTD. ISBN 4-87966-468-5 C3055 P2900E.
* FreeBSD (en japonés), publicado por CUTT. ISBN 4-906391-22-2 C3055 P2400E.
* http://www.shoeisha.co.jp/pc/index/shinkan/97_05_06.htm[Introducción completa a FreeBSD] (en japonés), publicado por http://www.shoeisha.co.jp/[Shoeisha Co., Ltd]. ISBN 4-88135-473-6 P3600E.
* http://www.ascii.co.jp/pb/book1/shinkan/detail/1322785.html[Kit personal del principiante UNIX FreeBSD] (en japonés), publicado por http://www.ascii.co.jp/[ASCII]. ISBN 4-7561-1733-3 P3000E.
* Manual FreeBSD (traducción del japonés), publicado por http://www.ascii.co.jp/[ASCII]. ISBN 4-7561-1580-2 P3800E.
* FreeBSD mit Methode (en alemán), publicado por Computer und Literatur Verlag/Vertrieb Hanser, 1998. ISBN 3-932311-31-0.
* http://www.pc.mycom.co.uk/FreeBSD/install-manual.html[Manual de instalación y utilización de FreeBSD] (en japonés), publicado por http://www.pc.mycom.co.jp/[Mainichi Communications Inc.].

_Libros y revistas en inglés:_

* http://www.cdrom.com/titles/freebsd/bsdcomp_bkx.phtml[ The Complete FreeBSD], publicado por http://www.cdrom.com/[Walnut Creek CDROM].

== Guías de usuario

* Computer Systems Research Group, UC Berkeley. _4.4BSD User's Reference Manual_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-075-9
* Computer Systems Research Group, UC Berkeley. _4.4BSD User's Supplementary Documents_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-076-7
* _UNIX in a Nutshell_. O'Reilly & Associates, Inc., 1990. ISBN 093717520X
* Mui, Linda. _What You Need To Know When You Can't Find Your UNIX System Administrator_. O'Reilly & Associates, Inc., 1995. ISBN 1-56592-104-6
* La http://www-wks.acs.ohio-state.edu/[Ohio State University] ha escrito un http://www-wks.acs.ohio-state.edu/unix_course/unix.html[Curso de introducción a UNIX] disponible en línea en formato HTML y postscript.
* http://www.jp.FreeBSD.org/[Jpman Project, Japan FreeBSD Users Group]. http://www.pc.mycom.co.jp/FreeBSD/urm.html[FreeBSD User's Reference Manual] (traducción japonesa). http://www.pc.mycom.co.jp/[Mainichi Communications Inc.], 1998. ISBN4-8399-0088-4 P3800E.

== Guías de administrador

* Albitz, Paul and Liu, Cricket. _DNS and BIND_, 2nd Ed. O'Reilly & Associates, Inc., 1997. ISBN 1-56592-236-0
* Computer Systems Research Group, UC Berkeley. _4.4BSD System Manager's Manual_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-080-5
* Costales, Brian, et al. _Sendmail_, 2nd Ed. O'Reilly & Associates, Inc., 1997. ISBN 1-56592-222-0
* Frisch, Æleen. _Essential System Administration_, 2nd Ed. O'Reilly & Associates, Inc., 1995. ISBN 1-56592-127-5
* Hunt, Craig. _TCP/IP Network Administration_. O'Reilly & Associates, Inc., 1992. ISBN 0-937175-82-X
* Nemeth, Evi. _UNIX System Administration Handbook_. 2nd Ed. Prentice Hall, 1995. ISBN 0131510517
* Stern, Hal _Managing NFS and NIS_ O'Reilly & Associates, Inc., 1991. ISBN 0-937175-75-7
* http://www.jp.FreeBSD.org/[Jpman Project, Japan FreeBSD Users Group]. http://www.pc.mycom.co.jp/FreeBSD/sam.html[FreeBSD System Administrator's Manual] (traducción japonesa). http://www.pc.mycom.co.jp/[Mainichi Communications Inc.], 1998. ISBN4-8399-0109-0 P3300E.

== Guías de programadores

* Asente, Paul. _X Window System Toolkit_. Digital Press. ISBN 1-55558-051-3
* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Reference Manual_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-078-3
* Computer Systems Research Group, UC Berkeley. _4.4BSD Programmer's Supplementary Documents_. O'Reilly & Associates, Inc., 1994. ISBN 1-56592-079-1
* Harbison, Samuel P. and Steele, Guy L. Jr. _C: A Reference Manual_. 4rd ed. Prentice Hall, 1995. ISBN 0-13-326224-3
* Kernighan, Brian and Dennis M. Ritchie. _The C Programming Language._. PTR Prentice Hall, 1988. ISBN 0-13-110362-9
* Lehey, Greg. _Porting UNIX Software_. O'Reilly & Associates, Inc., 1995. ISBN 1-56592-126-7
* Plauger, P. J. _The Standard C Library_. Prentice Hall, 1992. ISBN 0-13-131509-9
* Stevens, W. Richard. _Advanced Programming in the UNIX Environment_. Reading, Mass. : Addison-Wesley, 1992 ISBN 0-201-56317-7
* Stevens, W. Richard. _UNIX Network Programming_. 2nd Ed, PTR Prentice Hall, 1998. ISBN 0-13-490012-X
* Wells, Bill. "Writing Serial Drivers for UNIX". _Dr. Dobb's Journal_. 19(15), December 1994. pp68-71, 97-99.

== El sistema operativo por dentro

* Andleigh, Prabhat K. _UNIX System Architecture_. Prentice-Hall, Inc., 1990. ISBN 0-13-949843-5
* Jolitz, William. "Porting UNIX to the 386". _Dr. Dobb's Journal_. January 1991-July 1992.
* Leffler, Samuel J., Marshall Kirk McKusick, Michael J Karels and John Quarterman _The Design and Implementation of the 4.3BSD UNIX Operating System_. Reading, Mass. : Addison-Wesley, 1989. ISBN 0-201-06196-1
* Leffler, Samuel J., Marshall Kirk McKusick, _The Design and Implementation of the 4.3BSD UNIX Operating System: Answer Book_. Reading, Mass. : Addison-Wesley, 1991. ISBN 0-201-54629-9
* McKusick, Marshall Kirk, Keith Bostic, Michael J Karels, and John Quarterman. _The Design and Implementation of the 4.4BSD Operating System_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-54979-4
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 1: The Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63346-9
* Schimmel, Curt. _Unix Systems for Modern Architectures_. Reading, Mass. : Addison-Wesley, 1994. ISBN 0-201-63338-8
* Stevens, W. Richard. _TCP/IP Illustrated, Volume 3: TCP for Transactions, HTTP, NNTP and the UNIX Domain Protocols_. Reading, Mass. : Addison-Wesley, 1996. ISBN 0-201-63495-3
* Vahalia, Uresh. _UNIX Internals -- The New Frontiers_. Prentice Hall, 1996. ISBN 0-13-101908-2
* Wright, Gary R. and W. Richard Stevens. _TCP/IP Illustrated, Volume 2: The Implementation_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63354-X

== Referencia de seguridad

* Cheswick, William R. and Steven M. Bellovin. _Firewalls and Internet Security: Repelling the Wily Hacker_. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-63357-4
* Garfinkel, Simson and Gene Spafford. _Practical UNIX Security_. 2nd Ed. O'Reilly & Associates, Inc., 1996. ISBN 1-56592-148-8
* Garfinkel, Simson. _PGP Pretty Good Privacy_ O'Reilly & Associates, Inc., 1995. ISBN 1-56592-098-8

== Referencia de hardware

* Anderson, Don and Tom Shanley. _Pentium Processor System Architecture_. 2nd Ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40992-5
* Ferraro, Richard F. _Programmer's Guide to the EGA, VGA, and Super VGA Cards_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-62490-7
* La corporación Intel publica documentación sobre sus CPUs, chipsets y estándares en su http://developer.intel.com/[web para desarrolladores], normalmente en archivos con formato PDF.
* Shanley, Tom. _80486 System Architecture_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40994-1
* Shanley, Tom. _ISA System Architecture_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40996-8
* Shanley, Tom. _PCI System Architecture_. 3rd ed. Reading, Mass. : Addison-Wesley, 1995. ISBN 0-201-40993-3
* Van Gilluwe, Frank. _The Undocumented PC_. Reading, Mass: Addison-Wesley Pub. Co., 1994. ISBN 0-201-62277-7

== Historia de UNIX

* Lion, John _Lion's Commentary on UNIX, 6th Ed. With Source Code_. ITP Media Group, 1996. ISBN 1573980137
* Raymond, Eric S. _The New Hacker's Dictionary, 3rd edition_. MIT Press, 1996. ISBN 0-262-68092-0. Also known as the http://www.ccil.org/jargon/jargon.html[Jargon File]
* Salus, Peter H. _A quarter century of UNIX_. Addison-Wesley Publishing Company, Inc., 1994. ISBN 0-201-54777-5
* Simon Garfinkel, Daniel Weise, Steven Strassmann. _The UNIX-HATERS Handbook_. IDG Books Worldwide, Inc., 1994. ISBN 1-56884-203-1
* Don Libes, Sandy Ressler _Life with UNIX_ - special edition. Prentice-Hall, Inc., 1989. ISBN 0-13-536657-7
* _The BSD family tree_. 1997. link:ftp://ftp.FreeBSD.org/pub/FreeBSD/FreeBSD-current/src/shared/misc/bsd-family-tree[ftp://ftp.FreeBSD.org/pub/FreeBSD/FreeBSD-current/src/shared/misc/bsd-family-tree] o link:file://localhost/usr/shared/misc/bsd-family-tree[local] on a FreeBSD-current machine.
* _The BSD Release Announcements collection_. 1997. http://www.de.FreeBSD.org/de/ftp/releases/[http://www.de.FreeBSD.org/de/ftp/releases/]
* _Networked Computer Science Technical Reports Library_. http://www.ncstrl.org/[http://www.ncstrl.org/]
* _Antiguas releases BSD procedentes del Computer Systems Research Group (CSRG)_. http://www.mckusick.com/csrg/[http://www.mckusick.com/csrg/]: El paquete de 4 CDs cubre todas las versiones de BSD desde la 1BSD hasta la 4.4BSD y 4.4BSD-Lite2 (pero no la 2.11BSD, desafortunadamente). El último disco contiene el código fuente final y los archivos SCCS.

== Diarios y revistas

* _The C/C++ Users Journal_. R&D Publications Inc. ISSN 1075-2838
* _Sys Admin - The Journal for UNIX System Administrators_ Miller Freeman, Inc., ISSN 1061-2688
