---
title: Приложение A. Получение FreeBSD
part: Часть V. Приложения
prev: books/handbook/partv
next: books/handbook/bibliography
---

[appendix]
[[mirrors]]
= Получение FreeBSD
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Содержание
:table-caption: Таблица
:figure-caption: Рисунок
:example-caption: Пример
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: A

include::shared/mirrors.adoc[]
include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/ru/mailing-lists.adoc[]
include::shared/ru/teams.adoc[]
include::shared/ru/urls.adoc[]

[[mirrors-cdrom]]
== Наборы CD и DVD

Наборы FreeBSD CD и DVD доступны у нескольких онлайн поставщиков:

* FreeBSD Mall, Inc. +
2420 Sand Creek Rd C-1 #347 +
Brentwood, CA +
94513 +
США +
Телефон: +1 925 240-6652 +
Факс: +1 925 674-0821 +
Email: <info@freebsdmall.com> +
WWW: http://www.freebsdmall.com/

* Getlinux +
78 Rue de la Croix Rochopt +
'Epinay-sous-S'enart +
91860 +
Франция +
Email: <contact@getlinux.fr> +
WWW: http://www.getlinux.fr/

* Dr. Hinner EDV +
Kochelseestr. 11 +
D-81371 M"unchen +
Германия +
Телефон: (0177) 428 419 0 +
Email: <infow@hinner.de> +
WWW: http://www.hinner.de/linux/freebsd.html

* Linux Center +
ул. Галерная, 55 +
Санкт-Петербург +
190000 +
Россия +
Телефон: +7-812-3125208 +
Email: <info@linuxcenter.ru> +
WWW: http://linuxcenter.ru/shop/freebsd

[[mirrors-ftp]]
== FTP сайты

Официальные исходные тексты FreeBSD доступны через анонимные FTP зеркала по всему миру. Сайт link:ftp://ftp.FreeBSD.org/pub/FreeBSD/[ftp://ftp.FreeBSD.org/pub/FreeBSD/] имеет хорошее подключение и поддерживает большое количество одновременных соединений, но для вас возможно потребуется найти "ближайшее" зеркало (особенно если вы решили настроить у себя какой-то из видов зеркал).

Кроме того, FreeBSD доступна через анонимный FTP со следующих зеркал. Если вы выбрали получение FreeBSD через анонимный FTP, пожалуйста, выберите ближайший к вам сайт. Зеркала из списка "Основных зеркал" обычно содержат полный архив FreeBSD (все доступные на данный момент версии для каждой архитектуры), но скорость загрузки возможно будет больше с зеркала, расположенного в вашей стране или регионе. Сайты каждой страны содержат последнюю версию для наиболее популярных архитектур, но на них может не быть полного архива FreeBSD. Все сайты предоставляют доступ через анонимный FTP, а некоторые предоставляют доступ и другими методами. Для каждого сайта приведен список методов доступа в скобках после имени хоста.

<<central, {central}>>, <<primary, {mirrors-primary}>>, <<armenia, {mirrors-armenia}>>, <<australia, {mirrors-australia}>>, <<austria, {mirrors-austria}>>, <<brazil, {mirrors-brazil}>>, <<czech-republic, {mirrors-czech}>>, <<denmark, {mirrors-denmark}>>, <<estonia, {mirrors-estonia}>>, <<finland, {mirrors-finland}>>, <<france, {mirrors-france}>>, <<germany, {mirrors-germany}>>, <<greece, {mirrors-greece}>>, <<hong-kong, {mirrors-hongkong}>>, <<ireland, {mirrors-ireland}>>, <<japan, {mirrors-japan}>>, <<korea, {mirrors-korea}>>, <<latvia, {mirrors-latvia}>>, <<lithuania, {mirrors-lithuania}>>, <<netherlands, {mirrors-netherlands}>>, <<new-zealand, {mirrors-new-zealand}>>, <<norway, {mirrors-norway}>>, <<poland, {mirrors-poland}>>, <<russia, {mirrors-russia}>>, <<saudi-arabia, {mirrors-saudi-arabia}>>, <<slovenia, {mirrors-slovenia}>>, <<south-africa, {mirrors-south-africa}>>, <<spain, {mirrors-spain}>>, <<sweden, {mirrors-sweden}>>, <<switzerland, {mirrors-switzerland}>>, <<taiwan, {mirrors-taiwan}>>, <<ukraine, {mirrors-ukraine}>>, <<uk, {mirrors-uk}>>, <<usa, {mirrors-us}>>.

(as of UTC)

[[central]]
*{central}*

{central-ftp} (ftp / ftpv6 / {central-http} / {central-httpv6}) 

[[primary]]
*{mirrors-primary}*

In case of problems, please contact the hostmaster `<{mirrors-primary-email}>` for this domain.

* {mirrors-primary-ftp1} (ftp)
* {mirrors-primary-ftp2} (ftp)
* {mirrors-primary-ftp3} (ftp)
* {mirrors-primary-ftp4} (ftp / ftpv6 / {mirrors-primary-ftp4-http} / {mirrors-primary-ftp4-httpv6})
* {mirrors-primary-ftp5} (ftp)
* {mirrors-primary-ftp6} (ftp)
* {mirrors-primary-ftp7} (ftp)
* {mirrors-primary-ftp10} (ftp / ftpv6 / {mirrors-primary-ftp10-http} / {mirrors-primary-ftp10-httpv6})
* {mirrors-primary-ftp11} (ftp)
* {mirrors-primary-ftp13} (ftp)
* {mirrors-primary-ftp14} (ftp / {mirrors-primary-ftp14-http}) 

[[armenia]]
*{mirrors-armenia}*

In case of problems, please contact the hostmaster `<{mirrors-armenia-email}>` for this domain.

* {mirrors-armenia-ftp} (ftp / {mirrors-armenia-ftp-http} / rsync) 

[[australia]]
*{mirrors-australia}*

In case of problems, please contact the hostmaster `<{mirrors-australia-email}>` for this domain.

* {mirrors-australia-ftp} (ftp)
* {mirrors-australia-ftp2} (ftp)
* {mirrors-australia-ftp3} (ftp) 

[[austria]]
*{mirrors-austria}*

In case of problems, please contact the hostmaster `<{mirrors-austria-email}>` for this domain.

* {mirrors-austria-ftp} (ftp / ftpv6 / {mirrors-austria-ftp-http} / {mirrors-austria-ftp-httpv6}) 

[[brazil]]
*{mirrors-brazil}*

In case of problems, please contact the hostmaster `<{mirrors-brazil-email}>` for this domain.

* {mirrors-brazil-ftp2} (ftp / {mirrors-brazil-ftp2-http})
* {mirrors-brazil-ftp3} (ftp / rsync)
* {mirrors-brazil-ftp4} (ftp) 

[[czech-republic]]
*{mirrors-czech}*

In case of problems, please contact the hostmaster `<{mirrors-czech-email}>` for this domain.

* {mirrors-czech-ftp} (ftp / {mirrors-czech-ftpv6} / {mirrors-czech-ftp-http} / {mirrors-czech-ftp-httpv6} / rsync / rsyncv6)
* {mirrors-czech-ftp2} (ftp / {mirrors-czech-ftp2-http}) 

[[denmark]]
*{mirrors-denmark}*

In case of problems, please contact the hostmaster `<{mirrors-denmark-email}>` for this domain.

* {mirrors-denmark-ftp} (ftp / ftpv6 / {mirrors-denmark-ftp-http} / {mirrors-denmark-ftp-httpv6}) 

[[estonia]]
*{mirrors-estonia}*

In case of problems, please contact the hostmaster `<{mirrors-estonia-email}>` for this domain.

* {mirrors-estonia-ftp} (ftp) 

[[finland]]
*{mirrors-finland}*

In case of problems, please contact the hostmaster `<{mirrors-finland-email}>` for this domain.

* {mirrors-finland-ftp} (ftp) 

[[france]]
*{mirrors-france}*

In case of problems, please contact the hostmaster `<{mirrors-france-email}>` for this domain.

* {mirrors-france-ftp} (ftp)
* {mirrors-france-ftp1} (ftp / {mirrors-france-ftp1-http} / rsync)
* {mirrors-france-ftp3} (ftp)
* {mirrors-france-ftp5} (ftp)
* {mirrors-france-ftp6} (ftp / rsync)
* {mirrors-france-ftp7} (ftp)
* {mirrors-france-ftp8} (ftp) 

[[germany]]
*{mirrors-germany}*

In case of problems, please contact the hostmaster `<{mirrors-germany-email}>` for this domain.

* ftp://ftp.de.FreeBSD.org/pub/FreeBSD/ (ftp)
* ftp://ftp1.de.FreeBSD.org/freebsd/ (ftp / http://www1.de.FreeBSD.org/freebsd/ / rsync://rsync3.de.FreeBSD.org/freebsd/)
* ftp://ftp2.de.FreeBSD.org/pub/FreeBSD/ (ftp / http://ftp2.de.FreeBSD.org/pub/FreeBSD/ / rsync)
* ftp://ftp4.de.FreeBSD.org/FreeBSD/ (ftp / http://ftp4.de.FreeBSD.org/pub/FreeBSD/)
* ftp://ftp5.de.FreeBSD.org/pub/FreeBSD/ (ftp)
* ftp://ftp7.de.FreeBSD.org/pub/FreeBSD/ (ftp / http://ftp7.de.FreeBSD.org/pub/FreeBSD/)
* ftp://ftp8.de.FreeBSD.org/pub/FreeBSD/ (ftp) 

[[greece]]
*{mirrors-greece}*

In case of problems, please contact the hostmaster `<{mirrors-greece-email}>` for this domain.

* {mirrors-greece-ftp} (ftp)
* {mirrors-greece-ftp2} (ftp) 

[[hong-kong]]
*{mirrors-hongkong}*

{mirrors-hongkong-ftp} (ftp) 

[[ireland]]
*{mirrors-ireland}*

In case of problems, please contact the hostmaster `<{mirrors-ireland-email}>` for this domain.

* {mirrors-ireland-ftp} (ftp / rsync) 

[[japan]]
*{mirrors-japan}*

In case of problems, please contact the hostmaster `<{mirrors-japan-email}>` for this domain.

* {mirrors-japan-ftp} (ftp)
* {mirrors-japan-ftp2} (ftp)
* {mirrors-japan-ftp3} (ftp)
* {mirrors-japan-ftp4} (ftp)
* {mirrors-japan-ftp5} (ftp)
* {mirrors-japan-ftp6} (ftp)
* {mirrors-japan-ftp7} (ftp)
* {mirrors-japan-ftp8} (ftp)
* {mirrors-japan-ftp9} (ftp) 

[[korea]]
*{mirrors-korea}*

In case of problems, please contact the hostmaster `<{mirrors-korea-email}>` for this domain.

* {mirrors-korea-ftp} (ftp / rsync)
* {mirrors-korea-ftp2} (ftp / {mirrors-korea-ftp2-http}) 

[[latvia]]
*{mirrors-latvia}*

In case of problems, please contact the hostmaster `<{mirrors-latvia-email}>` for this domain.

* {mirrors-latvia-ftp} (ftp / {mirrors-latvia-ftp-http}) 

[[lithuania]]
*{mirrors-lithuania}*

In case of problems, please contact the hostmaster `<{mirrors-lithuania-email}>` for this domain.

* {mirrors-lithuania-ftp} (ftp / {mirrors-lithuania-ftp-http}) 

[[netherlands]]
*{mirrors-netherlands}*

In case of problems, please contact the hostmaster `<{mirrors-netherlands-email}>` for this domain.

* {mirrors-netherlands-ftp} (ftp / {mirrors-netherlands-ftp-http} / rsync)
* {mirrors-netherlands-ftp2} (ftp) 

[[new-zealand]]
*{mirrors-new-zealand}*

* {mirrors-new-zealand-ftp} (ftp / {mirrors-new-zealand-ftp-http}) 

[[norway]]
*{mirrors-norway}*

In case of problems, please contact the hostmaster `<{mirrors-norway-email}>` for this domain.

* {mirrors-norway-ftp} (ftp / rsync) 

[[poland]]
*{mirrors-poland}*

In case of problems, please contact the hostmaster `<{mirrors-poland-email}>` for this domain.

* {mirrors-poland-ftp} (ftp)
* ftp2.pl.FreeBSD.org

[[russia]]
*{mirrors-russia}*

In case of problems, please contact the hostmaster `<{mirrors-russia-email}>` for this domain.

* {mirrors-russia-ftp} (ftp / {mirrors-russia-ftp-http} / rsync)
* {mirrors-russia-ftp2} (ftp / {mirrors-russia-ftp2-http} / rsync)
* {mirrors-russia-ftp4} (ftp)
* {mirrors-russia-ftp5} (ftp / {mirrors-russia-ftp5-http} / rsync)
* {mirrors-russia-ftp6} (ftp) 

[[saudi-arabia]]
*{mirrors-saudi-arabia}*

In case of problems, please contact the hostmaster `<{mirrors-saudi-arabia-email}>` for this domain.

* {mirrors-saudi-arabia-ftp} (ftp) 

[[slovenia]]
*{mirrors-slovenia}*

In case of problems, please contact the hostmaster `<{mirrors-slovenia-email}>` for this domain.

* {mirrors-slovenia-ftp} (ftp) 

[[south-africa]]
*{mirrors-south-africa}*

In case of problems, please contact the hostmaster `<{mirrors-south-africa-email}>` for this domain.

* {mirrors-south-africa-ftp} (ftp)
* {mirrors-south-africa-ftp2} (ftp)
* {mirrors-south-africa-ftp4} (ftp) 

[[spain]]
*{mirrors-spain}*

In case of problems, please contact the hostmaster `<{mirrors-spain-email}>` for this domain.

* {mirrors-spain-ftp} (ftp / {mirrors-spain-ftp-http})
* {mirrors-spain-ftp3} (ftp) 

[[sweden]]
*{mirrors-sweden}*

In case of problems, please contact the hostmaster `<{mirrors-sweden-email}>` for this domain.

* {mirrors-sweden-ftp} (ftp)
* {mirrors-sweden-ftp2} (ftp / {mirrors-sweden-ftp2-rsync})
* {mirrors-sweden-ftp3} (ftp)
* {mirrors-sweden-ftp4} (ftp / {mirrors-sweden-ftp4v6} / {mirrors-sweden-ftp4-http} / {mirrors-sweden-ftp4-httpv6} / {mirrors-sweden-ftp4-rsync} / {mirrors-sweden-ftp4-rsyncv6})
* {mirrors-sweden-ftp6} (ftp / {mirrors-sweden-ftp6-http}) 

[[switzerland]]
*{mirrors-switzerland}*

In case of problems, please contact the hostmaster `<{mirrors-switzerland-email}>` for this domain.

* {mirrors-switzerland-ftp} (ftp / {mirrors-switzerland-ftp-http}) 

[[taiwan]]
*{mirrors-taiwan}*

In case of problems, please contact the hostmaster `<{mirrors-taiwan-email}>` for this domain.

* {mirrors-taiwan-ftp} (ftp / {mirrors-taiwan-ftpv6} / rsync / rsyncv6)
* {mirrors-taiwan-ftp2} (ftp / {mirrors-taiwan-ftp2v6} / {mirrors-taiwan-ftp2-http} / {mirrors-taiwan-ftp2-httpv6} / rsync / rsyncv6)
* {mirrors-taiwan-ftp4} (ftp)
* {mirrors-taiwan-ftp5} (ftp)
* {mirrors-taiwan-ftp6} (ftp / {mirrors-taiwan-ftp6v6} / rsync)
* {mirrors-taiwan-ftp7} (ftp)
* {mirrors-taiwan-ftp8} (ftp)
* {mirrors-taiwan-ftp11} (ftp / {mirrors-taiwan-ftp11-http})
* {mirrors-taiwan-ftp12} (ftp)
* {mirrors-taiwan-ftp13} (ftp)
* {mirrors-taiwan-ftp14} (ftp)
* {mirrors-taiwan-ftp15} (ftp) 

[[ukraine]]
*{mirrors-ukraine}*

* {mirrors-ukraine-ftp} (ftp / {mirrors-ukraine-ftp-http})
* {mirrors-ukraine-ftp6} (ftp / {mirrors-ukraine-ftp6-http} / {mirrors-ukraine-ftp6-rsync})
* {mirrors-ukraine-ftp7} (ftp) 

[[uk]]
*{mirrors-uk}*

In case of problems, please contact the hostmaster `<{mirrors-uk-email}>` for this domain.

* {mirrors-uk-ftp} (ftp)
* {mirrors-uk-ftp2} (ftp / {mirrors-uk-ftp2-rsync})
* {mirrors-uk-ftp3} (ftp)
* {mirrors-uk-ftp4} (ftp)
* {mirrors-uk-ftp5} (ftp) 

[[usa]]
*{mirrors-us}*

In case of problems, please contact the hostmaster `<{mirrors-us-email}>` for this domain.

* {mirrors-us-ftp} (ftp)
* {mirrors-us-ftp2} (ftp)
* {mirrors-us-ftp3} (ftp)
* {mirrors-us-ftp4} (ftp / ftpv6 / {mirrors-us-ftp4-http} / {mirrors-us-ftp4-httpv6})
* {mirrors-us-ftp5} (ftp)
* {mirrors-us-ftp6} (ftp)
* {mirrors-us-ftp8} (ftp)
* {mirrors-us-ftp10} (ftp)
* {mirrors-us-ftp11} (ftp)
* {mirrors-us-ftp13} (ftp / {mirrors-us-ftp13-http} / rsync)
* {mirrors-us-ftp14} (ftp / {mirrors-us-ftp14-http})
* {mirrors-us-ftp15} (ftp) 

[[ctm]]
== Использование CTM

CTM это метод синхронизации удаленного дерева каталогов с центральным. Он встроен во FreeBSD и может использоваться для синхронизации системы с репозиториями исходных текстов FreeBSD. Он поддерживает синхронизацию всего репозитория или только заданного набора ветвей.

CTM создан специально для использования в условиях некачественного соединения по TCP/IP или его отсутствия и предоставляет возможность автоматической отправки изменений по электронной почте. Пользователю требуется загружать до трех изменений в день для наиболее активных ветвей. Размеры обновлений всегда поддерживаются настолько малыми, насколько это возможно, и обычно составляют меньше 5 Кб. Примерно на каждое десятое приходится по 10-50 Кб, и иногда случаются обновления больше 100 Кб.

При использовании CTM для отслеживания процесса разработки FreeBSD требуется учитывать особенности в работе напрямую с исходных текстов, находящихся в разработке, по сравнению с использованием готовых релизов. Эти вопросы рассматриваются в разделе <<current-stable,Использование ветви разработки>>.

Cуществует немного документации по процессу создания дельта-файлов (delta, разница между имеющимися и актуальными исходными текстами) или использованию CTM в других целях. Обратитесь в список рассылки link:{ctm-users-url}[ctm-users-desc] для получения ответов на вопросы по использованию CTM.

[[mirrors-ctm]]
=== Получение дельта-файлов

"Дельта-файлы" для использования в CTM можно получить двумя способами: через анонимный FTP или по электронной почте.

Дельта-файлы по FTP можно получить со следующих сайтов зеркал. При использовании анонимного FTP для получения дельта-файлов CTM выберите географически ближайшее зеркало. По случаю возникновения проблем сообщайте в список рассылки link:{ctm-users-url}[ctm-users-desc].

США, Калифорния, Bay Area, официальный источник::

** link:ftp://ftp.FreeBSD.org/pub/FreeBSD/development/CTM/[ftp://ftp.FreeBSD.org/pub/FreeBSD/development/CTM/]
** link:ftp://ftp.FreeBSD.org/pub/FreeBSD/CTM/[ftp://ftp.FreeBSD.org/pub/FreeBSD/CTM/]

Южная Африка, запасной сервер для старых дельт::

** link:ftp://ftp.za.FreeBSD.org/pub/FreeBSD/CTM/[ftp://ftp.za.FreeBSD.org/pub/FreeBSD/CTM/]

Тайвань/R.O.C.::

** link:ftp://ctm.tw.FreeBSD.org/pub/FreeBSD/development/CTM/[ftp://ctm.tw.FreeBSD.org/pub/FreeBSD/development/CTM/]
** link:ftp://ctm2.tw.FreeBSD.org/pub/FreeBSD/development/CTM/[ftp://ctm2.tw.FreeBSD.org/pub/FreeBSD/development/CTM/]
** link:ftp://ctm3.tw.FreeBSD.org/pub/FreeBSD/development/CTM/[ftp://ctm3.tw.FreeBSD.org/pub/FreeBSD/development/CTM/]

Для получения дельта-файлов по почте подпишитесь на один из списков распространения `ctm-src`, доступных на http://lists.freebsd.org/mailman/listinfo[http://lists.freebsd.org/mailman/listinfo]. Например, link:{ctm-src-cur-url}[ctm-src-cur-desc] поддерживает главную ветвь разработки, а link:{ctm-src-9-url}[ctm-src-9-desc] поддерживает ветвь выпуска релизов 9.X.

Как только вы получаете обновления CTM по почте, используйте программу `ctm_rmail` для их распаковки и применения. Эта программа может выполняться непосредственно из записи в [.filename]#/etc/aliases# для автоматизации процесса. Обращайтесь к странице справочника man:ctm_rmail[1] для получения дополнительной информации.

[NOTE]
====
Вне зависимости от способа получения дельта-файлов, пользователям CTM следует подписаться на список рассылки link:{ctm-announce-url}[ctm-announce-desc], поскольку это единственный механизм публикации объявлений CTM.
====

=== Использование CTM

Перед началом использования дельта-файлов CTM потребуется определить исходную точку для последующего их применения.

Один из способов состоит в применении "стартового" дельта-файла к пустому каталогу. В имени такого файла присутствует `Xempty`, например, [.filename]#src-cur.3210XEmpty.gz#. Обозначение перед `X` соответствует происхождению первоначального источника. [.filename]#Empty# означает пустой каталог. Как правило, файл с `Empty` создается через каждые 100 дельта-файлов. Обратите внимание, что стартовые дельта-файлы имеют большой размер, и от 70 до 80 мегабайт сжатых в `gzip` данных для [.filename]#XEmpty# является обычным делом.

Другой способ заключается в получении первоначального источника с -RELEASE CD. Это может существенно снизить объём передаваемых данных по сети.

Когда основной дельта-файл создан, примените все дельта-файлы с последующими номерами. Чтобы применить дельта-файлы:

[source,bash]
....
# cd /directory/to/store/the/stuff
# ctm -v -v /directory/which/stores/the/deltas/src-xxx.*
....

Можно применять несколько дельт одной командой, по мере их последовательной обработки уже применённые дельты игнорируются. CTM работает с дельта-файлами, сжатыми с помощью `gzip`, что позволяет сэкономить на используемом дисковом пространстве.

Для проверки дельта-файла без его применения используйте параметр командной строки `-c`. CTM не будет модифицировать локальное дерево, а только проверит целостность дельта-файла на предмет его применимости без ошибок. Обращайтесь к man:ctm[1] для получения дополнительной информации по имеющимся параметрам и понимания процесса применения дельт, который используется в CTM.

Для поддержания исходных текстов в актуальном состоянии каждый раз, когда становится доступна новая дельта, применяйте её с использованием CTM.

Рекомендуется не удалять дельты после применения, если их сложно загрузить повторно. В этом случае будет доступна локальная копия, которая может понадобиться при восстановлении после сбоя.

=== Сохранение локальных изменений

Разработчики часто экспериментируют и изменяют файлы в локальном дереве исходных текстов. CTM имеет ограниченную поддержку локальных изменений: перед проверкой наличия файла сначала проверяется файл тем же именем и расширением [.filename]#.ctm#. Если такой файл присутствует, CTM будет работать с ним вместо исходного файла.

Такое поведение обеспечивает простой путь поддержки локальных изменений. Перед изменением файла скопируйте его с расширением [.filename]#.ctm#. Вносите любые изменения в исходный файл, зная что CTM будет применять обновления только к файлу с расширением [.filename]#.ctm#.

=== Другие возможности CTM

Определение файлов, которые будут затронуты обновлением::
Для определения списка изменений, которые CTM внесет в локальный репозиторий исходных текстов, используйте параметр `-l`. Этот параметр используется для записи лога изменений или выполнения предварительной или последующей обработки какого-либо подмножества изменяемых файлов.

Создание резервных копий перед обновлением::
Для создания резервной копии всех файлов, которые будут изменены обновлением CTM, укажите параметр `-B _backup-file_`. С этим параметром CTM выполняет сохранение в [.filename]#backup-file# всех файлов, которые затрагиваются применяемыми дельтами CTM.

Ограничение обновлений для определенных файлов::
Для ограничения набора файлов, обновляемых CTM, или для извлечения лишь нескольких файлов из последовательности дельт можно указать фильтрующие регулярные выражения с использованием `-e`, который указывает, какие файлы обрабатывать, или `-x`, который указывает, какие файлы игнорировать.
+
Пример извлечения свежей копии [.filename]#lib/libc/Makefile# из коллекции сохраненных дельт CTM:
+
[source,bash]
....
# cd /directory/to/extract/to/
# ctm -e '^lib/libc/Makefile' /directory/which/stores/the/deltas/src-xxx.*
....
+
Для каждого файла, указанного в CTM дельте, параметры `-e` и `-x` применяются в порядке их задания в командной строке. Файл обрабатывается CTM, только если он помечается как подходящий после обработки всех параметров `-e` и `-x`.

[[svn]]
== Использование Subversion

[[svn-intro]]
=== Введение

По состоянию на июль 2012 года FreeBSD использует Subversion в качестве основной системы контроля версий для хранения всего исходного кода FreeBSD, документации и Коллекции Портов.

[NOTE]
====
Subversion в основном является инструментом разработчика. Большинству пользователей следует использовать `freebsd-update` (crossref:cutting-edge[updating-upgrading-freebsdupdate,Обновление FreeBSD]) для обновления основной системы FreeBSD и `portsnap` (crossref:ports[ports-using,Использование Коллекции Портов]) для обновления Коллекции Портов FreeBSD.
====

В этом разделе демонстрируется, как устанавливать Subversion в системе FreeBSD и затем использовать его для создания локальной копии репозитория FreeBSD. Здесь приводится список доступных зеркал Subversion для FreeBSD, а также ссылки на дополнительную информацию по использованию Subversion.

[[svn-install]]
=== Установка

Subversion должен быть установлен до его использования для получения содержимого любого из репозиториев. Если уже имеется копия дерева портов, Subversion можно установить следующим образом:

[source,bash]
....
# cd /usr/ports/devel/subversion
# make install clean
....

Если дерево портов недоступно, Subversion можно установить из пакета:

[source,bash]
....
# pkg_add -r subversion
....

Если для управления пакетов используется pkgng, то Subversion можно установить с его помощью:

[source,bash]
....
# pkg install devel/subversion
....

[[svn-usage]]
=== Работа с Subversion

Команда `svn` используется для извлечения чистой копии исходных кодов в локальный каталог. Файлы в этом каталоге называются _локальной рабочей копией_.

[WARNING]
====

Если локальный каталог уже существует, но не был создан с помощью `svn`, переименуйте его или удалите перед загрузкой. Загрузка в существующий не-`svn` каталог может вызвать конфликты между существующими файлами и получаемыми из репозитория.
====

Subversion для обозначения репозитория использует URL, которые имеют вид _протокол://имя/путь_. Зеркала могут поддерживать различные протоколы как указано ниже. Первый компонент пути обозначает используемый репозиторий. Существует три различных репозитория: `base` для исходного кода основной системы FreeBSD, `ports` для Коллекции Портов и `doc` для документации. Например, URL `svn://svn0.us-east.FreeBSD.org/ports/head/` указывает на главную ветвь репозитория портов на зеркале `svn0.us-east.FreeBSD.org` с использованием протокола `svn`.

Загрузка из данного репозитория выполняется следующей командой:

[source,bash]
....
# svn checkout svn-mirror/repository/branch lwcdir
....

где:

* _svn-mirror_ - URL для одного из <<svn-mirrors,сайтов зеркала Subversion>>.
* _repository_ - один из репозиториев проекта, т.е. `base`, `ports` или `doc`.
* _branch_ зависит от используемого репозитория. `ports` и `doc` в основном обновляются в ветви `head`, в то время как `base` содержит последнюю версию -CURRENT в `head` и соответственно последние версии ветви -STABLE в `stable/8` (для 8._x_), `stable/9` (9._x_) и `stable/10` (10._x_).
* _lwcdir_ - каталог для размещения содержимого указанной ветви. Обычно это [.filename]#/usr/ports# для `ports`, [.filename]#/usr/src# для `base` и [.filename]#/usr/doc# для `doc`.

В этом примере загружается Коллекция Портов с западного репозитория США с использованием протокола HTTPS и размещением локальной рабочей копии в [.filename]#/usr/ports#. Если [.filename]#/usr/ports# уже присутствует, но не был создан с помощью `svn`, не забудьте его переименовать или удалить перед загрузкой.

[source,bash]
....
# svn checkout https://svn0.us-west.FreeBSD.org/ports/head /usr/ports
....

Поскольку на первоначальном этапе с удалённого репозитория загружается вся ветвь целиком, на это может уйти некоторое время. Пожалуйста, будьте терпеливы.

После первоначальной загрузки локальную рабочую копию можно обновить:

[source,bash]
....
# svn update lwcdir
....

Для обновления [.filename]#/usr/ports#, созданного в вышеприведённом примере, используйте:

[source,bash]
....
# svn update /usr/ports
....

Обновление намного быстрее загрузки, т.к. передаются только файлы с изменениями.

Альтернативный способ обновления локальной рабочей копии после загрузки обеспечивается в [.filename]#Makefile# в каталогах [.filename]#/usr/ports#, [.filename]#/usr/src# и [.filename]#/usr/doc#. Используйте цель `update` с заданной переменной `SVN_UPDATE`. Пример для обновления [.filename]#/usr/src#:

[source,bash]
....
# cd /usr/src
# make update SVN_UPDATE=yes
....

[[svn-mirrors]]
=== Сайты зеркала Subversion

Все зеркала покрывают все репозитории.

Главный сервер Subversion FreeBSD `svn.FreeBSD.org` является общедоступным для чтения. Это может измениться в будущем, поэтому пользователям рекомендуется использовать одно из официальных зеркал. Для просмотра репозиториев Subversion FreeBSD через браузер используйте http://svnweb.FreeBSD.org/[http://svnweb.FreeBSD.org/].

[NOTE]
====
Сеть зеркал Subversion FreeBSD находится на раннем этапе развития и скорее всего будет меняться. Не полагайтесь на неизменность этого списка. В частности, серверные сертификаты SSL скорее всего изменятся.
====

[.informaltable]
[cols="1,1,1,1", options="header"]
|===
| Название
| Протоколы
| Местоположение
| SSL Fingerprint

|`svn0.us-west.FreeBSD.org`
|`svn`, http://svn0.us-west.FreeBSD.org/[http], https://svn0.us-west.FreeBSD.org/[https]
|США, Калифорния
|SHA1 `1C:BD:85:95:11:9F:EB:75:A5:4B:C8:A3:FE:08:E4:02:73:06:1E:61`

|`svn0.us-east.FreeBSD.org`
|`svn`, http://svn0.us-east.FreeBSD.org/[http], https://svn0.us-east.FreeBSD.org/[https], `rsync`
|Сша, Нью Джерси
|SHA1 `1C:BD:85:95:11:9F:EB:75:A5:4B:C8:A3:FE:08:E4:02:73:06:1E:61`

|`svn0.eu.FreeBSD.org`
|`svn`, http://svn0.eu.FreeBSD.org/[http], https://svn0.eu.FreeBSD.org/[https], `rsync`
|Великобритания
|SHA1 `39:B0:53:35:CE:60:C7:BB:00:54:96:96:71:10:94:BB:CE:1C:07:A7`

|`svn0.ru.FreeBSD.org`
|`svn`, http://svn0.ru.FreeBSD.org/[http], https://svn0.ru.FreeBSD.org/[https], `rsync`
|Россия, Москва
|SHA1 `F6:44:AA:B9:03:89:0E:3E:8C:4D:4D:14:F0:27:E6:C7:C1:8B:17:C5`
|===

Предпочтительным протоколом является HTTPS, который обеспечивает защиту от других компьютеров, маскирующихся под зеркало FreeBSD (известно как атака "человек посредине"), и прочих, пытающихся послать плохое содержимое конечному пользователю.

При первом соединении с зеркалом по HTTPS пользователю будет предложено проверить _fingerprint_ (отпечаток) сервера:

[source,bash]
....
Error validating server certificate for 'https://svn0.us-west.freebsd.org:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
 - The certificate hostname does not match.
Certificate information:
 - Hostname: svnmir.ysv.FreeBSD.org
 - Valid: from Jul 29 22:01:21 2013 GMT until Dec 13 22:01:21 2040 GMT
 - Issuer: clusteradm, FreeBSD.org, (null), CA, US (clusteradm@FreeBSD.org)
 - Fingerprint: 1C:BD:85:95:11:9F:EB:75:A5:4B:C8:A3:FE:08:E4:02:73:06:1E:61
(R)eject, accept (t)emporarily or accept (p)ermanently?
....

Сравните отпечаток с вышеуказанными в таблице. Если отпечаток совпадает, сертификат безопасности сервера можно принять на временной или постоянной основе. Временный сертификат действует до конца сессии с сервером, и при следующем соединении этап верификации будет повторён. Постоянное принятие сертификата сохраняет параметры аутентификации в [.filename]#~/.subversion/auth/#, и пользователю не придётся проверять отпечаток снова до истечения сертификата.

Если `https` не получается использовать из-за фаервола или иных проблем, `svn` - следующий выбор с чуть более быстрой передачей. Если ни один из них не может быть использован, используйте `http`.

=== Дополнительная информация

Для получения другой информации по использованию Subversion смотрите "книгу Subversion" по названию http://svnbook.red-bean.com/[Version Control with Subversion] или http://subversion.apache.org/docs/[Документацию Subversion].

[[mirrors-rsync]]
== Использование rsync

Следующие сайты организуют доступ к FreeBSD через протокол rsync. Утилита rsync работает в основном таким же способом, что и команда man:rcp[1], но поддерживает больше параметров и использует протокол удаленного обновления rsync, который передает только разницу между двумя наборами файлов, что значительно повышает скорость синхронизации по сети. Это особенно полезно, если вы поддерживаете зеркало сервера FreeBSD FTP или репозитория CVS. Пакет rsync доступен для многих операционных систем; в FreeBSD смотрите порт package:net/rsync[] или используйте пакет.

Чешская республика::
rsync://ftp.cz.FreeBSD.org/
+
Доступные коллекции:

** ftp: Частичное зеркало FreeBSD FTP сервера.
** FreeBSD: Полное зеркало FreeBSD FTP сервера.

Нидерланды::
rsync://ftp.nl.FreeBSD.org/
+
Доступные коллекции:

** FreeBSD: Полное зеркало FreeBSD FTP сервера.

Россия::
rsync://ftp.mtu.ru/
+
Доступные коллекции:

** FreeBSD: Полное зеркало FreeBSD FTP сервера.
** FreeBSD-gnats: База данных системы отслеживания ошибок GNATS.
** FreeBSD-Archive: Зеркало FreeBSD архивного FTP сервера.

Швеция::
rsync://ftp4.se.freebsd.org/
+
Доступные коллекции:

** FreeBSD: Полное зеркало FreeBSD FTP сервера.

Тайвань::
rsync://ftp.tw.FreeBSD.org/
+
rsync://ftp2.tw.FreeBSD.org/
+
rsync://ftp6.tw.FreeBSD.org/
+
Доступные коллекции:

** FreeBSD: Полное зеркало FreeBSD FTP сервера.

Великобритания::
rsync://rsync.mirrorservice.org/
+
Доступные коллекции:

** ftp.freebsd.org: Полное зеркало FreeBSD FTP сервера.

Соединенные Штаты Америки::
rsync://ftp-master.FreeBSD.org/
+
Этот сервер может использоваться только основными зеркалами FreeBSD.
+
Доступные коллекции:

** FreeBSD: Основной архив FreeBSD FTP сервера.
** acl: Основной ACL список FreeBSD.
+
rsync://ftp13.FreeBSD.org/
+
Доступные коллекции:

** FreeBSD: Полное зеркало FreeBSD FTP сервера.
