# $Id: Makefile,v 1.4 1998-07-27 04:47:05 hanai Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

.if exists(Makefile.conf)
.include "Makefile.conf"
.endif

DOCS=  
DOCS+=	programmers.sgml
DOCS+=	security.sgml
DOCS+=  secure.sgml

.include ".././/web.mk"
