# $Id: Makefile,v 1.3 1998-07-26 11:29:56 hanai Exp $

.if exists(Makefile.conf)
.include "Makefile.conf"
.endif

DOCS=  
DOCS+=	programmers.sgml
DOCS+=	security.sgml
DOCS+=  secure.sgml

.include "../web.mk"
