#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$
#
# %SOURCE%	en_US.ISO8859-1/books/handbook/jails/Makefile
# %SRCID%	39829
#
#

CHAPTERS= 	jails/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
