---
title: "Daylight Savings Time Changes for 2007"
sidenav: developers
--- 

= Daylight Savings Time Changes for 2007

This is a summary of the information about the change in Daylight Savings Time rules and how the change affects FreeBSD releases.

In 2005 several countries, including the United States of America and Canada, passed legislation changing when Daylight Savings Time begins and ends. That change takes effect in 2007. For the time zones affected by the change Daylight Savings Time will begin on March 11th (instead of April 1st) and end on November 4th (instead of October 28th).

FreeBSD uses `/etc/localtime` to control the conversion of the system's internal representation of time (based on UTC) to the format appropriate for the local time zone. That file gets copied from one of the files in `/usr/share/zoneinfo` by the tzsetup(8) command, usually as part of the initial installation procedure. The change in Daylight Savings Time rules affects the files in `/usr/share/zoneinfo` for the time zones affected by the legislation passed in 2005.

Of the release branches supported by the FreeBSD Security Team as of February 2007, FreeBSD-6.2 and FreeBSD-5.5 have up to date zoneinfo files. FreeBSD-6.1 has correct zoneinfo files for time zones in the United States of America but out of date zoneinfo files for some of the other countries affected (for example Canada). An Errata Notice will be released shortly to update the zoneinfo files in FreeBSD-6.1.

For the development branches HEAD, RELENG_6, RELENG_5, and RELENG_4 all have the correct zoneinfo files in them.

NOTE: `/etc/localtime` currently does not get updated when the cvsup/buildworld/etc system update procedures are used. If a machine was installed using one of the releases not listed above it will probably have an outdated `/etc/localtime` file. That file can be updated by running tzsetup(8).

For older systems no longer under support the misc/zoneinfo port can be installed to update the `/usr/share/zoneinfo` files, followed by running tzsetup(8) to update `/etc/localtime`.
