# $FreeBSD$
# $FreeBSDru: frdp/www/ru/donations/Makefile,v 1.1 2003/09/30 17:23:51 andy Exp $
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.xml wantlist.xml donors.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
