#
# Build the Handbook with just the content from this chapter.
#
# Original Revision: 1.143
# $FreeBSD$
#

CHAPTERS= 	ppp-and-slip/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
