# $FreeBSD: www/ja/releases/4.8R/Makefile,v 1.1 2003/03/22 05:05:00 hrs Exp $
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

#DOCS=	schedule.sgml qa.sgml

DATA=	docbook.css

### Revision checking
REVCHECK=       YES

.include "${WEB_PREFIX}/share/mk/web.site.mk"
