# $FreeBSD$
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

#DOCS=	schedule.sgml qa.sgml

DATA=	docbook.css

.include "${WEB_PREFIX}/share/mk/web.site.mk"
