# $FreeBSD$

#SUBDIR = committers-guide
#SUBDIR+= explaining-bsd
#SUBDIR+= freebsd-questions
#SUBDIR+= fonts
#SUBDIR+= ipsec-must
#SUBDIR+= mh
#SUBDIR+= new-users
#SUBDIR+= programming-tools

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
