# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: r51733

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=	doc-set.xml
DOCS+=  submitting.xml
DOCS+=  who.xml
DOCS+=  translations.xml
DOCS+=	docproj.xml

INDEXLINK= docproj.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
