---
title: "FreeBSD 9.2-RELEASE Announcement"
sidenav: download
---

include::shared/en/urls.adoc[]
include::shared/releases.adoc[]
:thisDate: {rel92-current-date}

= FreeBSD 9.2-RELEASE Announcement

Date: {thisDate}

The FreeBSD Release Engineering Team is pleased to announce the availability of FreeBSD 9.2-RELEASE. This is the second release from the stable/9 branch, which improves on the stability of FreeBSD 9.1 and introduces some new features. Some of the highlights:

* The ZFS filesystem now supports TRIM when used on solid state drives.
* The virtio(4) drivers have been added to the GENERIC kernel configuration for amd64 and i386 architectures.
* The ZFS filesystem now supports lz4 compression.
* OpenSSL has been updated to version 0.9.8y.
* DTrace hooks have been enabled by default in the GENERIC kernel.
* DTrace has been updated to version 1.9.0.
* Sendmail has been updated to version 8.14.7.
* OpenSSH has been updated to version 6.2p2.
* Import unmapped I/O support from head/.

For a complete list of new features and known problems, please see the online release notes and errata list, available at:

* `http://www.FreeBSD.org/releases/9.2R/relnotes/`

For more information about FreeBSD release engineering activities, please see:

* `http://www.FreeBSD.org/releng/`

== Availability

FreeBSD 9.2-RELEASE is now available for the amd64, i386, ia64, powerpc, powerpc64, and sparc64 architectures.

FreeBSD 9.2 can be installed from bootable ISO images or over the network. Some architectures also support installing from a USB memory stick. The required files can be downloaded via FTP as described in the section below. While some of the smaller FTP mirrors may not carry all architectures, they will all generally contain the more common ones such as amd64 and i386.

MD5 and SHA256 hashes for the release ISO and memory stick images are included at the bottom of this message.

The purpose of the images provided as part of the release are as follows:

dvd1::
This contains everything necessary to install the base FreeBSD operating system, the documentation, and a small set of pre-built packages aimed at getting a graphical workstation up and running. It also supports booting into a "livefs" based rescue mode. This should be all you need if you can burn and use DVD-sized media.
disc1::
This contains the base FreeBSD operating system. It also supports booting into a "livefs" based rescue mode. There are no pre-built packages.
bootonly::
This supports booting a machine using the CDROM drive but does not contain the support for installing FreeBSD from the CD itself. You would need to perform a network based install (e.g. from an FTP server) after booting from the CD.
memstick::
This can be written to an USB memory stick (flash drive) and used to do an install on machines capable of booting off USB drives. It also supports booting into a "livefs" based rescue mode. There are no pre-built packages.
+
As one example of how to use the memstick image, assuming the USB drive appears as /dev/da0 on your machine something like this should work:
+
....
# dd if=FreeBSD-9.2-RELEASE-amd64-memstick.img of=/dev/da0 bs=10240 conv=sync
....
+
Be careful to make sure you get the target (of=) correct.

FreeBSD 9.2-RELEASE can also be purchased on CD-ROM or DVD from several vendors. One of the vendors that will be offering FreeBSD 9.2-based products is:

* FreeBSD Mall, Inc.`http://www.freebsdmall.com`

== FTP

At the time of this announcement the following FTP sites have FreeBSD 9.2-RELEASE available.

* `ftp://ftp.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/9.2/`

However before trying these sites please check your regional mirror(s) first by going to:

* `ftp://ftp.<yourdomain>.FreeBSD.org/pub/FreeBSD`

Any additional mirror sites will be labeled ftp2, ftp3 and so on.

More information about FreeBSD mirror sites can be found at:

* `http://www.FreeBSD.org/doc/en_US.ISO8859-1/books/handbook/mirrors-ftp.html`

For instructions on installing FreeBSD or updating an existing machine to 9.2-RELEASE please see:

* `http://www.FreeBSD.org/releases/9.2R/installation/`

== Support

FreeBSD 9.2-RELEASE will be supported until 2014-09-30. The End-of-Life dates can be found at:

* `http://www.FreeBSD.org/security/`

=== Other Projects Based on FreeBSD

There are many "third party" Projects based on FreeBSD. The Projects range from re-packaging FreeBSD into a more "novice friendly" distribution to making FreeBSD available on Amazon's EC2 infrastructure. For more information about these Third Party Projects see:

* `http://wiki.FreeBSD.org/3rdPartyProjects`

=== Acknowledgments

Many companies donated equipment, network access, or man-hours to support the release engineering activities for FreeBSD 9.2 including The FreeBSD Foundation, Yahoo!, NetApp, Internet Systems Consortium, Sentex Communications, New York Internet, Juniper Networks, and iXsystems.

The release engineering team for 9.2-RELEASE includes:

[cols=",",]
|===
|Ken Smith <kensmith@FreeBSD.org> |Release Engineering Lead
|Marcus von Appen <mva@FreeBSD.org> |Release Engineering
|Glen Barber <gjb@FreeBSD.org> |Release Engineering, 9.2-RELEASE Release Engineer
|Konstantin Belousov <kib@FreeBSD.org> |Release Engineering
|Joel Dahl <joel@FreeBSD.org> |Release Engineering
|Marc Fonvieille <blackend@FreeBSD.org> |Release Engineering, Documentation
|Steven Kreuzer <skreuzer@FreeBSD.org> |Release Engineering
|Erwin Lansing <erwin@FreeBSD.org> |Package Building
|Xin Li <delphij@FreeBSD.org> |Release Engineering, Security
|Simon L. B. Nielsen <simon@FreeBSD.org> |Security Officer Emeritus
|Josh Paetzel <jpaetzel@FreeBSD.org> |Release Engineering
|Colin Percival <cperciva@FreeBSD.org> |Security Officer Emeritus
|Craig Rodrigues <rodrigc@FreeBSD.org> |Release Engineering
|Hiroki Sato <hrs@FreeBSD.org> |Release Engineering, Documentation
|Gleb Smirnoff <glebius@FreeBSD.org> |Release Engineering
|Dag-Erling Smørgrav <des@FreeBSD.org> |Security Officer
|Marius Strobl <marius@FreeBSD.org> |Release Engineering
|Robert Watson <rwatson@FreeBSD.org> |Release Engineering, Security
|===

=== Trademark

FreeBSD is a registered trademark of The FreeBSD Foundation.

=== ISO Image Checksums

....
SHA256 (FreeBSD-9.2-RELEASE-amd64-bootonly.iso) = 63db06d3f468d219b308bb3fbc3f48e791134481fb1abf39e9b1ee415dcfc099
SHA256 (FreeBSD-9.2-RELEASE-amd64-disc1.iso) = a8c1751b83646530148766618a89a97009e7500e7057a5cbe3afd74ef480c915
SHA256 (FreeBSD-9.2-RELEASE-amd64-dvd1.iso) = 36c99ac1ffb90f2272df1bf10cafec999fde1b1a6bd289b5583836639c3639ae
SHA256 (FreeBSD-9.2-RELEASE-amd64-memstick.img) = fbc0c46f2db8c347145ee7c8308e4f3058dc5ec3155a9fb51d0f0e52ab2bf5cb
....

....
MD5 (FreeBSD-9.2-RELEASE-amd64-bootonly.iso) = 2338f255d0ddc4659d04545a3c27bfa1
MD5 (FreeBSD-9.2-RELEASE-amd64-disc1.iso) = cde180e3c5e3e370c97598a4feccb5b4
MD5 (FreeBSD-9.2-RELEASE-amd64-dvd1.iso) = 21448c2688ba938b42c1727449d69750
MD5 (FreeBSD-9.2-RELEASE-amd64-memstick.img) = 8a7f0ee3cb2570785b2d0a760d99bad6
....

....
SHA256 (FreeBSD-9.2-RELEASE-i386-bootonly.iso) = e2df14515911ab964a587c4ae5e23882c71908c4e589ae57f7848399232c161d
SHA256 (FreeBSD-9.2-RELEASE-i386-disc1.iso) = 76093c27288f0ab939a5de14b621ec8eb1420d96343132c2b7c382747d35b67c
SHA256 (FreeBSD-9.2-RELEASE-i386-dvd1.iso) = a1bba5668792cfc8197c0f81b28cdd17e912a1ae5816887f8518bf1536a99af8
SHA256 (FreeBSD-9.2-RELEASE-i386-memstick.img) = aa635578fea1136da680420afaab21a8e0b7c39541566d28f468d6ebb7a1e3a8
....

....
MD5 (FreeBSD-9.2-RELEASE-i386-bootonly.iso) = c868d09dace9ec2d673fd62cbd1305b4
MD5 (FreeBSD-9.2-RELEASE-i386-disc1.iso) = ba7ba7943177aee9626df228fb1ee6c2
MD5 (FreeBSD-9.2-RELEASE-i386-dvd1.iso) = 917104df8d559f2ec981e98bfdf78e05
MD5 (FreeBSD-9.2-RELEASE-i386-memstick.img) = affea2f784472cfbed9d16a6fdeab5ce
....

....
SHA256 (FreeBSD-9.2-RELEASE-ia64-bootonly.iso) = 138b6f9fe7bbad418db956a53539ff75f77c918aedaf7fcc1d4960aa2ccca476
SHA256 (FreeBSD-9.2-RELEASE-ia64-disc1.iso) = 906cfc5012504501547aa0c89292e66047faaed34f18e79594ab95635c43f6c2
SHA256 (FreeBSD-9.2-RELEASE-ia64-memstick.img) = b178d6466f4b2eb9af0520eb8b434ce98ecab11b9d24bf6ad9478a30f9875531
....

....
MD5 (FreeBSD-9.2-RELEASE-ia64-bootonly.iso) = 2ef154556774c55ce0a5a27c7a674859
MD5 (FreeBSD-9.2-RELEASE-ia64-disc1.iso) = aa06455bfd9f54f1257c6b8484e81334
MD5 (FreeBSD-9.2-RELEASE-ia64-memstick.img) = b047ea9791272a4fbc66cd9f401d6122
....

....
SHA256 (FreeBSD-9.2-RELEASE-powerpc-bootonly.iso) = 89fea7d441a71b96def24a80815566936b7b6eaab640030ae78518001806d626
SHA256 (FreeBSD-9.2-RELEASE-powerpc-disc1.iso) = b5f5adc9ab2392c2796881553582a1da1cfa99c62b62b57a3325fc7e6a7259c4
SHA256 (FreeBSD-9.2-RELEASE-powerpc-memstick.img) = 3951ab28d6226f9c32a71f6d81d6ad9f9d05c9af5d11cf00118380f6ba20f282
....

....
MD5 (FreeBSD-9.2-RELEASE-powerpc-bootonly.iso) = 84ba491526faf1115827ee3c81593f92
MD5 (FreeBSD-9.2-RELEASE-powerpc-disc1.iso) = 1a1f683a69d20419834d056d43c8e3de
MD5 (FreeBSD-9.2-RELEASE-powerpc-memstick.img) = dd959ede1dff0971334d3722db8c8bcc
....

....
SHA256 (FreeBSD-9.2-RELEASE-powerpc-powerpc64-bootonly.iso) = 092fa817a0a44fb49d05ed7aae44d98e78f4e3e0fc6e0297ee0d11ec8f8ccf37
SHA256 (FreeBSD-9.2-RELEASE-powerpc-powerpc64-disc1.iso) = 56daf1f49bff7ee9e31c3255170fe2373c8674cfce1c560e78deff4ae81c505d
SHA256 (FreeBSD-9.2-RELEASE-powerpc-powerpc64-memstick.img) = be87c9edaa0b343a1223ebfb68dd161a023e287e067dd6550198c4ac23d47062
....

....
MD5 (FreeBSD-9.2-RELEASE-powerpc-powerpc64-bootonly.iso) = c914b221a8f09ac8d004aa4d7db710a0
MD5 (FreeBSD-9.2-RELEASE-powerpc-powerpc64-disc1.iso) = f471466df756ae85162fb8bb794d007a
MD5 (FreeBSD-9.2-RELEASE-powerpc-powerpc64-memstick.img) = c6b739c889dd94e3ed3ac8ef277ced91
....

....
SHA256 (FreeBSD-9.2-RELEASE-sparc64-bootonly.iso) = 76813e3a5b400ea56533a3d5762f76284746a736281b6e1bce882d9f0e2dd076
SHA256 (FreeBSD-9.2-RELEASE-sparc64-disc1.iso) = 0a15095210058fa7c1572102e6af49407462fcd670d28a3af9dfc154efaeb72e
....

....
MD5 (FreeBSD-9.2-RELEASE-sparc64-bootonly.iso) = ae21e0dc63aa0d6327f44c733705c055
MD5 (FreeBSD-9.2-RELEASE-sparc64-disc1.iso) = 7ce9c00d4b6e23124062cc2be8b56a74
....
