---
title: "FreeBSD 9.2-RELEASE Errata"
sidenav: download
---

= FreeBSD 9.2-RELEASE Errata

== Abstract

This document lists errata items for FreeBSD 9.2-RELEASE, containing significant information discovered after the release or too late in the release cycle to be otherwise included in the release documentation. This information includes security advisories, as well as news relating to the software or documentation that could affect its operation or usability. An up-to-date version of this document should always be consulted before installing this version of FreeBSD.

This errata document for FreeBSD 9.2-RELEASE will be maintained until the release of FreeBSD 9.3-RELEASE.

'''''

Table of Contents

* <<intro, Introduction>>
* <<security, Security Advisories>>
* <<errata, Errata Notices>>
* <<late-news, Late-Breaking News>>

[[intro]]
== Introduction

This errata document contains"late-breaking news" about FreeBSD 9.2-RELEASE Before installing this version, it is important to consult this document to learn about any post-release discoveries or problems that may already have been found and fixed.

Any version of this errata document actually distributed with the release (for example, on a CDROM distribution) will be out of date by definition, but other copies are kept updated on the Internet and should be consulted as the "current errata" for this release. These other copies of the errata are located at `http://www.FreeBSD.org/releases/`, plus any sites which keep up-to-date mirrors of this location.

Source and binary snapshots of FreeBSD 9.3-STABLE also contain up-to-date copies of this document (as of the time of the snapshot).

For a list of all FreeBSD CERT security advisories, see `http://www.FreeBSD.org/security/` or `ftp://ftp.FreeBSD.org/pub/FreeBSD/CERT/`.

[[security]]
== Security Advisories

Problems described in the following security advisories have been fixed in 9.3-RELEASE. For more information, consult the individual advisories available from `http://security.FreeBSD.org/`.

[cols=",,",options="header",]
|===
|Advisory |Date |Topic
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:01.bsnmpd.asc[SA-14:01.bsnmpd] |1 January 2014 |Fix bsnmpd remote denial of service vulnerability
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:02.ntpd.asc[SA-14:02.ntpd] |1 January 2014 |Fix ntpd distributed reflection Denial of Service vulnerability
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:03.bind.asc[SA-14:03.ntpd] |1 January 2014 |Fix BIND remote denial of service vulnerability
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:05.nfsserver.asc[SA-14:05.nfsserver] |8 April 2014 |Fix NFS deadlock vulnerability
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:06.openssl.asc[SA-14:06.openssl] |8 April 2014 |Fix ECDSA Cache Side-channel Attack
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:08.tcp.asc[SA-14:08.tcp] |30 April 2014 |Fix TCP reassembly vulnerability
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:11.sendmail.asc[SA-14:11.sendmail] |3 June 2014 |Fix sendmail improper close-on-exec flag handling
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:12.ktrace.asc[SA-14:12.ktrace] |3 June 2014 |Fix ktrace memory disclosure
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:13.pam.asc[SA-14:13.pam] |3 June 2014 |Fix incorrect error handling in PAM policy parser
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:14.openssl.asc[SA-14:14.openssl] |5 June 2014 |Multiple vulnerabilities
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:16.file.asc[SA-14:16.file] |24 June 2014 |Multiple vulnerabilities
|http://www.freebsd.org/security/advisories/FreeBSD-SA-14:17.kmem.asc[SA-14:17.kmem] |8 July 2014 |Kernel memory disclosure in control messages and SCTP notifications
|===

[[late-news]]
== Late-Breaking News

No late-breaking news.
