---
title: "FreeBSD 9.2-RELEASE Installation Instructions"
sidenav: download
---

= FreeBSD 9.2-RELEASE Installation Instructions

'''''
This article gives some brief instructions on installing FreeBSD 9.2-RELEASE and upgrading the systems running earlier releases.

'''''

[[INSTALL]]
== Installing FreeBSD

The link:{handbook}#bsdinstall[“Installing FreeBSD”] chapter of the link:{handbook}[FreeBSD Handbook] provides more in-depth information about the installation program itself, including a guided walk-through with screenshots.

'''''

[[UPGRADE]]
== Upgrading FreeBSD

'''''

=== Upgrading from Source

The procedure for doing a source code based update is described in link:{handbook}#synching[https://doc.FreeBSD.org/en/books/handbook/book/#synching] and link:{handbook}#makeworld[https://doc.FreeBSD.org/en/books/handbook/book/#makeworld].

For SVN use the `releng/9.2` branch which will be where any upcoming Security Advisories or Errata Notices will be applied.

Note that CVS is *not* supported.

'''''

=== Upgrading Using "FreeBSD Update"

The man:freebsd-update[8] utility supports binary upgrades of i386 and amd64 systems running earlier FreeBSD releases. Systems running `8.[34]-RELEASE`, `9.[01]-RELEASE`, `9.2-BETA[123]`, or `9.2-RC[1234]` can upgrade as follows:

[source,SCREEN]
----
# freebsd-update fetch
# freebsd-update install
----

Now the man:freebsd-update[8] utility can fetch bits belonging to 9.2-RELEASE. During this process man:freebsd-update[8] will ask for help in merging configuration files.

[source,SCREEN]
----
# freebsd-update upgrade -r 9.2-RELEASE
----

Due to changes in the way that FreeBSD is packaged on the release media, two complications may arise in this process if upgrading from FreeBSD 8.x:

[arabic]
. The FreeBSD kernel, which previously could appear in either `/boot/kernel` or `/boot/GENERIC`, now only appears as `/boot/kernel`. As a result, any kernel appearing in `/boot/GENERIC` will be deleted. Please carefully read the output printed by man:freebsd-update[8] and confirm that an updated kernel will be placed into `/boot/kernel` before proceeding beyond this point.
. The FreeBSD source tree in `/usr/src` (if present) will be deleted. (Normally the man:freebsd-update[8] utility will update a source tree, but in this case the changes in release packaging result in the man:freebsd-update[8] utility not recognizing that the source tree from the old release and the source tree from the new release correspond to the same part of FreeBSD.)

[source,SCREEN]
----
# freebsd-update install
----

The system must now be rebooted with the newly installed kernel before the non-kernel components are updated.

[source,SCREEN]
----
# shutdown -r now
----

After rebooting, man:freebsd-update[8] needs to be run again to install the new userland components:

[source,SCREEN]
----
# freebsd-update install
----

At this point, users of systems being upgraded from FreeBSD 8.4-RELEASE or earlier will be prompted by man:freebsd-update[8] to rebuild all third-party applications (e.g., ports installed from the ports tree) due to updates in system libraries.

After updating installed third-party applications (and again, only if man:freebsd-update[8] printed a message indicating that this was necessary), run man:freebsd-update[8] again so that it can delete the old (no longer used) system libraries:

[source,SCREEN]
----
# freebsd-update install
----

Finally, reboot into 9.2-RELEASE

[source,SCREEN]
----
# shutdown -r now
----
