# $FreeBSD: www/es/copyright/Makefile,v 1.3 2000/11/29 23:56:56 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	freebsd-license.sgml
DOCS+=	daemon.sgml
DOCS+=	copyright.sgml

INDEXLINK= copyright.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
