# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+= press.xml
DOCS+= newsflash.xml
DOCS+= news.xml

# press releases
DOCS+= pressreleases.xml
DOCS+= press-rel-1.xml
DOCS+= press-rel-2.xml
DOCS+= press-rel-3.xml

INDEXLINK= news.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
