# $FreeBSD: www/es/news/Makefile,v 1.6 2000/11/29 23:56:58 kuriyama Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+= press.sgml
DOCS+= newsflash.sgml
DOCS+= news.sgml

# press releases
DOCS+= pressreleases.sgml
DOCS+= press-rel-1.sgml
DOCS+= press-rel-2.sgml
DOCS+= press-rel-3.sgml

INDEXLINK= news.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
