---
title: "Заморозка репозитория портов 21 июля 2026 года"
sidenav: about
loadNews: false
---

include::shared/ru/urls.adoc[]

= Заморозка репозитория портов 21 июля 2026 года

Репозиторий портов был заморожен начиная с вторника, 21 июля 2026 года. +
Нет никаких оснований полагать, что дерево было скомпрометировано. +
Эта страница будет документировать данную заморозку. +

:toc:

[[announce]]
== Объявление: 22 июля 2026 года

Первое объявление было опубликовано в https://lists.freebsd.org/archives/freebsd-announce/[списке рассылки announce@].

https://lists.freebsd.org/archives/freebsd-announce/2026-July/000294.html

Вы, возможно, заметили, что репозиторий портов заморожен уже почти 24 часа на момент написания этого сообщения. Наше заявление о ситуации и дальнейших действиях приведено ниже.

В дерево портов недавно был зафиксирован бинарный файл размером 150 МБ, и в результате этого core@ принял решение о временной заморозке дерева портов для проведения очистки. Указанный коммит нарушил зеркалирование нашего дерева портов на github.com из-за жёсткого ограничения на размер файлов в 100 МБ, а также внёс в историю репозитория объект с сомнительной лицензионной чистотой.

Учитывая важность зеркалирования на github.com для нашего сообщества, мы активно предпринимаем шаги по удалению проблемных коммитов и восстановлению зеркалирования на внешние сервисы. Нет никаких оснований полагать, что дерево портов было скомпрометировано. Заморозка была полностью направлена на ограничение количества коммитов, которые потребуется переписать для приведения репозитория к корректному состоянию.

Для нас важно предоставить сообществу и конечным потребителям воспроизводимый и устойчивый путь исправления этой проблемы. Как вы хорошо знаете, исправление подобных проблем не всегда проходит так гладко, как хотелось бы.

Мы активно работаем над подготовкой инструкций, которым необходимо будет следовать существующим рабочим копиям, чтобы синхронизироваться с этими исправлениями. Для обеспечения полной прозрачности мы также предоставим процедуру проверки того, что официальные изменения в репозитории ограничены именно тем объёмом, который мы заявляем.

Мы также внедряем серверные хуки, чтобы предотвратить подобные инциденты в будущем.

Пожалуйста, следите за нашими дальнейшими обновлениями и спасибо за ваше внимание.

С уважением,

Кайл Эванс (от имени core@)
