# $FreeBSD$
# $FreeBSDes$
# Copiado de la version 1.5
#
# Article: Setting up a CVS repository - the FreeBSD way

#MAINTAINER= stijn@win.tue.nl

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=


WITH_ARTICLE_TOC?=YES


SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
