---
title: "FreeBSD Donations Liaison"
sidenav: about
--- 

= FreeBSD Donations Liaison

== Monetary FreeBSD Foundation Donations

The FreeBSD Foundation's fund-raising efforts are essential to keeping FreeBSD free. As the Project grows, so do the costs.

By donating to the foundation, you are helping us fund and manage projects, sponsor FreeBSD events, and provide travel grants to FreeBSD developers. You are also helping us represent the Project in executing contracts, license agreements, copyrights, trademarks, and other legal arrangements that require a recognized legal entity.

To make a monetary donation to the FreeBSD Foundation, please visit the https://www.freebsdfoundation.org/donate/[FreeBSD Foundation] donation page.

== Contents

* <<#goal,Donations Liaison Goals>>
* <<#charter,Donations Liaison Charter>>
* <<#donating,Donating to the FreeBSD Project>>

== Other Donations Links

* https://wiki.freebsd.org/Donations/WantList[FreeBSD Project Want List]
* link:donors[List of FreeBSD Donations]

[[goal]]
== Project Goal

As FreeBSD's userbase has grown, the number of people who want to donate materials or funds to the Project has grown. The Donations Liaison is intended to streamline the handling of these donations, and to ensure that they are handled in a timely and reasonable manner.

[[charter]]
== Donations Liaison Charter

The purpose of the Donations Liaison Office is to encourage and guide donations according to a set of community-accepted rules. The DLO has the following responsibilities.

* to establish and maintain a clear set of procedures for handling donations.
* to respond to donation offers in a timely manner.
* to maintain a list of equipment and resources desired by the FreeBSD community.
* to coordinate donation offers with the FreeBSD developer community.
* to shepherd donations through the entire donation process.
* to work with a small team to ensure a timely, informed, and correct response is available at all times.
* to publicly acknowledge donors and donations when the donation is complete.
* record the status of all loans to the Project.
* provide open records of all donations to the FreeBSD developer community.

[[donating]]
== Donating to the FreeBSD Project

So, you want to donate something to the FreeBSD Project? Great! We strongly rely upon user donations to accomplish our goals. Please read below to see how to contact us about your donation.

If you don't know what you want to give, take a look at our https://wiki.freebsd.org/Donations/WantList[list of needs]. We would appreciate any items on this list. If you have equipment you'd like to donate, read on.

[[taxcredit]]
=== Tax Credit for Donations

The FreeBSD Foundation can act as a charitable organization for tax purposes. If you live in the United States, your donation can be deducted from your taxes under certain conditions. If you want a receipt for tax purposes your contribution, please let us know when you send information on your donation.

A tax credit is not as easy as it might seem. The donations team must be informed of the desire for a tax deduction so the foundation may be notified, and informed when it has been shipped. The Foundation will also need to know when the item has been received by the intended individual. The Foundation must then be able to demonstrate that the donation is in the _public good_. All of this together means that while we probably have developers who would be interested in that big box of ISA cards in your closet, you probably cannot get a tax credit for them; the total work needed to process, ship, and document them far exceeds their total value.

The FreeBSD Foundation will provide a receipt for delivery of equipment. They will not, however, provide a fair-market valuation of the equipment -- in fact, the law forbids them to do so. We recommend checking elsewhere for valuations of hardware donations. Since many of our donations are obsolete, making fair market value hard to judge, we suggest searching on Ebay or other used equipment sites for prices paid for similar equipment.

To receive a tax receipt for a donation, you will need to complete a https://www.freebsdfoundation.org/wp-content/uploads/2015/12/Hardware-Donation-Form.pdf[Hardware Donation Form] from the FreeBSD Foundation website.

=== How to Donate

Part of the goal of the Donations Liaison Office is to match donations with developers who can use them. We don't accept just any donation; we only handle those that have a home with a developer who can use them to improve FreeBSD. This saves time all around, and also helps assure donors that what their contributions are actually supporting the FreeBSD Project. The down side is that we need some information about your donation before accepting it.

Donations generally fall into three categories:

* <<#money,Financial>>
* <<#systems,Complete Computers>>
* <<#components,Computer Components>>

If you have something to offer that doesn't fall into one of these categories, don't fret! Just contact us at donations@FreeBSD.org with your offer. Just because it's not the run-of-the-mill offer doesn't mean that we're not interested.

[[money]]
=== Financial Contributions

The FreeBSD Project does not directly accept financial contributions. A sponsor organization, the https://www.freebsdfoundation.org[FreeBSD Foundation], accepts financial contributions for us. Please see their Web site for details on financial contributions.

[[systems]]
=== Complete Computer Systems

The FreeBSD Project always needs computers. If you have a computer that you would like to donate to the Project, please contact us with the following information:

* Hardware specifications: architecture, motherboard, CPU, disk space, memory.
* Does this system currently run FreeBSD, or is it unsupported? If possible, please attach a dmesg from a FreeBSD install on this system.
* Are you willing to ship this system?
* Your physical location. We try to make shipping as easy and inexpensive as possible.
* Also mention if you want a <<#taxcredit,tax credit>> for this system. (Note that not all donations can realistically receive a tax credit, as the cost of supplying the credit may exceed the value of the donation.)

[[components]]
=== Computer Components

If you have hardware that you would like to donate to the Project, please contact us with the following information:

* The hardware description: model, part number, manufacturer, etc. If you have an exact link to the manufacturer's Web page for this component, that would be helpful.
* Is this hardware currently supported in FreeBSD?
* What documentation do you have? A piece of hardware is not sufficient to write a driver; driver authors need detailed chipset data from the manufacturer. (Don't worry too much if you don't have this documentation, as it may be available elsewhere.)
* Are you willing to ship this system?
* Your physical location. We try to make shipping as easy and inexpensive as possible.
* Also mention if you want a <<#taxcredit,tax credit>> for this hardware. (Note that not all donations can realistically receive a tax credit, as the cost of supplying the credit may exceed the value of the donation.)

=== What we Do with this Information

Once we have a description of the donation, the Donations Liaison Office will contact the developer community and offer the resource to them. If we have a developer who would like the item, we put the donor and the recipient in contact and let them work out shipping information. If there are multiple developers interested in a resource, we try to learn what each developer would use the resource for and allocate it most effectively for the Project. If no developer is interested, we turn down the offer.

Our goal is to place (or decline) all donations within 7 days of receipt of complete information.
