# $FreeBSD: www/en/gifs/Makefile,v 1.53 2005/05/08 15:49:57 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   beastie.png blt_gry_arrow.png blt_red_arrow.png front_get_back.png front_get_bl.png front_get_br.png front_get_tl.png front_get_tr.png front_new_back.png front_new_bl.png front_new_br.png front_new_tl.png front_new_tr.png hdr_fill.png ico_rss.png logo.png nav_rgt.png nav_tbl_btm.png nav_tbl_top.png

.include "${WEB_PREFIX}/share/mk/web.site.mk"