# $FreeBSD$
#
# Makefile for the advocacy site

# The FreeBSD French Documentation Project
# Original revision: 1.3

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.xml
DOCS+=	myths.xml
# DOCS+=	letter.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
