---
description: '웹사이트, 메일링 리스트, 미러 등과 같은 인터넷의 FreeBSD 추가 리소스'
next: books/handbook/pgpkeys
part: '파트 V. 부록'
path: /books/handbook/
prev: books/handbook/bibliography
showBookMenu: 'true'
tags: ["eresources", "Websites", "Mailing Lists", "Usenet", "Newsgroups"]
title: '부록 C. 인터넷 리소스'
weight: 42
---

[appendix]
[[eresources]]
= 인터넷 리소스
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: C
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/eresources/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

FreeBSD의 발전 속도가 빠르기 때문에 인쇄 매체는 최신 개발 사항을 따라잡는 수단으로 비현실적입니다. 전자 자료는 최신 정보를 얻을 수 있는 유일한 방법은 아니지만 최선의 방법입니다. FreeBSD는 자원봉사로 이루어지기 때문에, 사용자 커뮤니티 자체가 일종의 "기술 지원 부서" 역할을 하며, 전자 메일, 웹 포럼, USENET 뉴스는 이러한 커뮤니티에 가장 효과적으로 다가갈 수 있는 방법입니다.

FreeBSD 사용자 커뮤니티와의 가장 중요한 연락 창구는 아래에 요약되어 있습니다. 링크에 더 최신 목록이 있을 수 있습니다: https://wiki.freebsd.org/Community[FreeBSD 위키의 커뮤니티 포털]. 여기에 언급되지 않은 다른 리소스도 포함될 수 있도록 {freebsd-doc}으로 보내주세요.

[[eresources-www]]
== 웹사이트

* link:https://forums.FreeBSD.org/[FreeBSD 포럼]은 FreeBSD에 대한 질문과 기술 토론을 위한 웹 기반 토론 포럼을 제공합니다.
* link:https://wiki.FreeBSD.org/[FreeBSD 위키]는 아직 핸드북에 포함되지 않은 다양한 정보를 제공합니다.
* link:https://docs.FreeBSD.org/[FreeBSD 문서 웹사이트]는 사용자 핸드북만 제공하는 것이 아니라, 읽어볼 만한 다른 핸드북과 문서도 제공합니다.
* link:https://freebsdfoundation.org/our-work/journal/browser-based-edition/[FreeBSD 저널]은 전문적으로 편집된 격월간 무료 기술 잡지로, link:https://freebsdfoundation.org[FreeBSD 재단]에서 발행됩니다.
* link:http://www.youtube.com/bsdconferences[BSDConferences 유튜브 채널]은 전 세계 BSD 컨퍼런스의 고품질 비디오 모음을 제공합니다. 이것은 주요 개발자들이 FreeBSD의 새로운 작업에 대해 발표하는 것을 볼 수 있는 좋은 방법입니다.
* link:https://www.freebsd.org/status/[FreeBSD 상태 보고서]는 3개월마다 발표되며, FreeBSD 개발의 진행 상황을 추적합니다.
* r/freebsd에 link:https://www.reddit.com/r/freebsd/[FreeBSD 중심 Reddit 그룹]이 있습니다.
* link:https://superuser.com/questions/tagged/freebsd[슈퍼 사용자] 및 link:https://serverfault.com/questions/tagged/freebsd[서버 오류], 시스템 관리자용 Stack Exchange 서비스를 참조하세요.
* link:https://wiki.freebsd.org/Discord[FreeBSD Discord 서버]는 커뮤니케이션 및 커뮤니티 구축 서비스로, FreeBSD 커뮤니티 회원들의 친목을 도모하고, 다른 사람들을 지원하거나 도움을 받고, 배우고, 기여하고, 협업하고, FreeBSD와 관련된 모든 것에 대한 최신 정보를 얻을 수 있는 곳입니다.
* link:https://wiki.freebsd.org/IRC/Channels[IRC 채널], 널리 구현되어 있고 기술적으로 성숙한 개방형 표준 텍스트 채팅입니다.

[[eresources-mail]]
== 메일링 리스트

메일링 리스트는 집중된 FreeBSD 청중에게 질문을 하거나 기술 토론을 시작할 수 있는 가장 직접적인 방법입니다. 다양한 FreeBSD 주제에 대한 다양한 목록이 있습니다. 가장 적절한 메일링 리스트에 질문을 보내면 항상 더 빠르고 정확한 답변을 받을 수 있습니다.

[NOTE]
====
_FreeBSD 목록에 이메일을 보내는 기능을 테스트하려면 {freebsd-test}로 테스트 메시지를 보내세요._ 다른 목록에는 테스트 메시지를 보내지 마세요.
====

어떤 목록에 질문을 게시해야 할지 잘 모르겠다면, extref:{freebsd-questions-article}[FreeBSD-질문 메일링 리스트에서 최상의 결과를 얻는 방법]을 참조하세요.

리스트에 글을 올리기 전에 먼저 확인하시기 바랍니다:

* 자주 반복되는 토론을 피하는 방법 등 메일링 리스트를 가장 효과적으로 사용하는 방법에 대한 자세한 내용은 extref:{mailing-list-faq}[메일링 리스트 자주 묻는 질문](FAQ) 문서를 참조하세요
* 아카이브를 검색하여 게시하려는 내용을 다른 사람이 이미 게시했는지 확인합니다.

아카이브 검색 인터페이스에는 다음이 포함됩니다:
 
* https://www.freebsd.org/search/[] (DuckDuckGo)
* https://lists.freebsd.org/search[] (실험적 검색엔진)

이것은 또한 FreeBSD 메일링 리스트에 보낸 메시지가 영구적으로 보관된다는 것을 의미합니다. 개인 정보 보호가 우려되는 경우 일회용 보조 이메일 주소를 사용하고 공개 정보만 게시하는 것을 고려하세요.

FreeBSD 제공 아카이브:
 
* 링크를 링크로 표시하지 않음
* 인라인 이미지를 표시하지 않습니다
* HTML 메시지의 HTML 콘텐츠를 표시하지 않습니다.

[[eresources-summary]]
FreeBSD 공개 메일링 리스트는 link:{mailing-lists-url}[여기]에서 확인할 수 있습니다.

[[eresources-subscribe]]
=== 구독하는 방법

메일링 리스트에 가입하려면 {mailing-lists-url}에서 리스트 이름을 클릭합니다. 표시되는 페이지에는 해당 목록에 필요한 모든 구독 지침이 포함되어 있어야 합니다.

지정된 목록에 실제로 글을 올리려면 mailto:listname@FreeBSD.org[listname@FreeBSD.org]으로 메일을 보내세요. 그러면 전 세계 메일링 리스트 회원들에게 다시 배포됩니다.

목록에서 수신을 취소하려면 목록에서 받은 모든 이메일 하단에 있는 URL을 클릭합니다. mailto:listname+unsubscribe@FreeBSD.org[listname+unsubscribe@FreeBSD.org]으로 이메일을 보내 수신을 취소할 수도 있습니다.

기술 메일링 리스트의 토론을 기술적인 트랙으로 유지하는 것이 중요합니다. 중요한 공지사항만 받으려면 트래픽이 많지 않은 {freebsd-announce}에 가입하세요.

[[eresources-charters]]
=== 기본 규칙 목록

_모든_ FreeBSD 메일링 리스트에는 몇 가지 기본 규칙이 있으며, 이를 사용하는 모든 사람이 준수해야 합니다. 이러한 지침을 준수하지 않을 경우, 해당 게시자는 FreeBSD 포스트마스터 mailto:postmaster@FreeBSD.org[postmaster@FreeBSD.org]로부터 두 번의 서면 경고를 받게 되며, 세 번째 위반 시에는 모든 FreeBSD 메일링 리스트에서 삭제되고 더 이상 게시할 수 없게 차단될 것입니다. 이러한 규칙과 조치가 필요하다는 점을 유감스럽게 생각하지만, 오늘날의 인터넷은 매우 가혹한 환경이며, 많은 사람들이 인터넷의 일부 메커니즘이 얼마나 취약한지 인식하지 못하고 있는 것 같습니다.

통행규칙:

* 모든 게시물의 주제는 해당 게시물이 게시된 리스트의 기본 설명을 준수해야 합니다. 목록이 기술적인 문제에 관한 것이라면 게시글에 기술적인 논의가 포함되어야 합니다. 계속되는 관련 없는 잡담이나 비난은 메일링 리스트의 가치를 떨어뜨릴 뿐이며 메일링 리스트에 있는 모든 사람의 가치를 떨어뜨리므로 용납되지 않습니다. 특정 주제가 아닌 자유 형식 토론의 경우 {freebsd-chat}을 자유롭게 사용할 수 있으므로 이를 대신 사용하시기 바랍니다.
* 2군데 이상의 메일링 리스트에 글을 게시해서는 안 되며, 두 리스트 모두에 글을 게시해야 할 명백하고 분명한 이유가 있는 경우에만 두 곳에 글을 게시해야 합니다. 대부분의 목록에는 이미 구독자가 상당수 중복되어 있으며, 가장 난해한 혼합(예: "-stable & -scsi")을 제외하고는 한 번에 두 개 이상의 목록에 게시할 이유가 없습니다. `Cc` 줄에 여러 개의 메일링 리스트가 있는 메시지를 받은 경우 답장하기 전에 `Cc` 줄을 잘라내세요. _보낸 사람이 누구든 답장을 보낸 사람은 여전히 교차 게시에 대한 책임이 있습니다._
* 인신 공격과 욕설(논쟁의 맥락에서)은 허용되지 않으며, 여기에는 사용자와 개발자 모두 포함됩니다. 비공개 메일을 발췌하거나 재게시할 수 있는 권한을 얻지 못했거나 얻을 수 없는 경우와 같은 심각한 네티켓 위반은 눈살을 찌푸리게 하지만 특별히 강제되지는 않습니다.
* FreeBSD와 관련이 없는 제품이나 서비스의 광고는 엄격히 금지되며, 위반자가 스팸으로 광고하는 것이 명백한 경우 즉시 금지됩니다.

[[eresources-mailfiltering]]
=== 메일링 리스트에서 필터링하기

FreeBSD 메일링 리스트는 스팸, 바이러스 및 기타 원치 않는 이메일의 배포를 피하기 위해 여러 가지 방법으로 필터링됩니다. 이 섹션에 설명된 필터링 작업에는 메일링 리스트를 보호하기 위해 사용되는 모든 필터링 작업이 포함되어 있지는 않습니다.

메일링 리스트에는 특정 유형의 첨부파일만 허용됩니다. 아래 목록에 없는 MIME 콘텐츠 유형의 첨부 파일은 메일링 리스트에 이메일을 배포하기 전에 모두 삭제됩니다.

* application/octet-stream
* application/pdf
* application/pgp-signature
* application/x-pkcs7-signature
* message/rfc822
* multipart/alternative
* multipart/related
* multipart/signed
* text/html
* text/plain
* text/x-diff
* text/x-patch

[NOTE]
====
일부 메일링 리스트에서는 다른 MIME 콘텐츠 유형의 첨부 파일을 허용할 수도 있지만, 대부분의 메일링 리스트에는 위의 목록이 적용될 것입니다.
====

이메일에 HTML 버전과 일반 텍스트 버전이 모두 포함된 경우 HTML 버전이 제거됩니다. 이메일에 HTML 버전만 포함된 경우에는 일반 텍스트로 변환됩니다.

[[eresources-news]]
== 유즈넷 뉴스그룹

두 개의 FreeBSD 관련 뉴스그룹 외에도 FreeBSD에 대해 논의하거나 FreeBSD 사용자와 관련된 다른 많은 뉴스그룹이 있습니다.

=== BSD 특정 뉴스그룹

* link:news:comp.unix.bsd.freebsd.announce[comp.unix.bsd.freebsd.announce]
* link:news:comp.unix.bsd.freebsd.misc[comp.unix.bsd.freebsd.misc]
* link:news:de.comp.os.unix.bsd[de.comp.os.unix.bsd] (독일어)
* link:news:fr.comp.os.bsd[fr.comp.os.bsd] (프랑스어)

=== 기타 관심 있는 UNIX(R) 뉴스그룹

* link:news:comp.unix[comp.unix]
* link:news:comp.unix.questions[comp.unix.questions]
* link:news:comp.unix.admin[comp.unix.admin]
* link:news:comp.unix.programmer[comp.unix.programmer]
* link:news:comp.unix.shell[comp.unix.shell]
* link:news:comp.unix.misc[comp.unix.misc]
* link:news:comp.unix.bsd[comp.unix.bsd]

=== X 윈도우 시스템

* link:news:comp.windows.x[comp.windows.x]
