 #The FreeBSD Russian Documentation Project
 # $FreeBSDru: frdp/www/ru/docs/Makefile,v 1.1 2005/12/23 15:14:20 gad Exp $
 # $FreeBSD$
 # Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.xml man.xml webresources.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
