# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	freebsd.sgml
DOCS+=	tools.sgml
DOCS+=	api.sgml
DOCS+=	index.sgml
DOCS+=	tutorials.sgml
DOCS+=	development.sgml
DOCS+=	resources.sgml
DOCS+=	vendor.sgml
DOCS+=	documentation.sgml
DOCS+=	servlets.sgml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
