---
title: "User Groups"
sidenav: community
---

= User Groups

FreeBSD's widespread popularity has spawned a number of user groups around the world.

If you know of a FreeBSD user group not listed here, please fill out a link:../support/bugreports[problem report] in category Documentation->Website with the following information:

. A URL for the user group's website.
. An email contact address of a human in charge, for use by our visitors and website administrators.
. A short (one paragraph) description of the user group.

In keeping with the spirit of FreeBSD, we prefer user groups that are active and which conduct their business in public.
If there is no local group, http://bsd.meetup.com/ can be used to locate interested individuals near by.

Consider forming your own user group!

== Regions

FreeBSD User Groups can be found worldwide, connecting enthusiasts and professionals who share a passion for this versatile operating system.
Join a FreeBSD User Group in your region and become part of this vibrant community, networking and learning from fellow FreeBSD enthusiasts near you.

[[europe]]
=== Europe

link:https://bsdstammtisch.at/[Wiener BSD Stammtisch]::
The Vienna BSD-Stammtisch is an English and German speaking BSD user group located in Austria's capital.
We meet once a month to have a show and tell session, discuss and have a beer or two.
The idea is to improve our skills and meet other BSD enthusiasts.
Feel free to join!

link:https://brmlab.cz/groups/start#prague_bsd_group[Prague BSD Group]::
A small BSD user group from Brmlab Prague/Czech Republic Hackerspace.
We are a group of hobbyists, professionals, and enthusiasts.

link:http://www.bsd-dk.dk/[BSD-DK]::
The Danish BSD User Group.
Promotion and support of the BSD derived Operating Systems in Denmark.
Mailing lists, lecture and workshops.
Send mail subscription requests to link:mailto:bsd-dk-request@bsd-dk.dk[bsd-dk-request@bsd-dk.dk].
Located in Denmark.

link:https://www.AlbaBSD.org[AlbaBUG]::
The Albanian BSD Users Group is a group that represents and supports *BSD in Albanian language.
More information is available at link:https://www.AlbaBSD.org[https://www.AlbaBSD.org].
Located in Prishtina, Kosova.

link:http://www.augusta.de/[Augusta]::
The BSD User Group of the Augsburger Computer Forum e.V. meets every second Saturday at 17.00
Please visit our link:http://www.augusta.de/[web site] for more information on dates and our address.
We have all kinds of BSD, but mainly FreeBSD and Mac OS X. Located in Germany, Augsburg.

link:http://www.bsdhh.org/bsdhh-de-index.html[BSD User Group Hamburg (BSDHH)]::
The BSD User Group Hamburg (BSDHH) meets on the first Wednesday of the month at 7.00pm in the restaurant _Léon_ (Koppel 1, 20099 Hamburg).
Most members are FreeBSD users, although users of all BSD flavors are welcome.
Located in Germany, Hamburg.

link:https://bsd.nrw/[BSD User Group Düsseldorf/NRW (BSD.NRW)]::
BSD.NRW is located in Düsseldorf, NRW, Germany.
We are open for all people in the Rhein-Ruhr area that are interested in the BSD family.
We have bi-monthly meetings (always on the second Tuesday of these months).
Upcoming dates and additional information can be found on the link:https://bsd.nrw[BSD.NRW website].

link:http://www.HappaBSD.de/[HappaBSD Regensburg]::
HappaBSD is a regulars' table taking place every month in Regensburg, Bavaria, Germany.
For more information see the link:http://www.HappaBSD.de/[HappaBSD website].

link:https://www.uugrn.org/[Unix Users Group Rhein-Neckar e.V. (UUGRN e.V.)]::
The Unix Users Group Rhein-Neckar e.V. (UUGRN e.V.) provides a regional forum for users of all Unix flavors, with a stress on Linux and BSD.
link:https://stammtisch.uugrn.org/[Meetings (UnixUserStammtisch)] are held on the third Monday of each month.
The link:https://fixme.uugrn.org/[Hands-on FIXME meeting] happens every first Friday of each month.
Located in Germany, link:https://rhein-neckar-wiki.de/[Rhine-Neckar-Region], Heidelberg.
All events get announced on X link:https://twitter.com/uugrn[@uugrn].

link:http://berklix.org/bim/[Berkeley in Munich (BIM)]::
The Berkeley in Munich (BIM) caters for users of BSD based systems in Oberbayern.
Located in Germany, Munich.

link:http://www.u-bus.de[Ulmer BSD User Stammtisch]::
The U-BUS meets every last Thursday of the month.
For more information about meetings and related issues, please check the web page (link:http://www.u-bus.de[u-bus]).
Located in Germany, Ulm.

link:http://www.bluefrogs.de/[Bluefrogs e.V.]::
Unix and Linux User Group in Bergisch Gladbach (near Cologne), German.
Meetings are held twice a month.
We are working with all Open Source Unix derivates: FreeBSD, NetBSD, OpenBSD, Linux and others.
We give workshops, lectures, talks and install parties.
For more information please email us at: link:mailto:info@bluefrogs.de[info@bluefrogs.de].

link:http://bse.42.org/[BSE München]::
BSE (BSD Social Event) is located in München (Munich), Germany.
Feel free to visit our regular meetings (every four weeks) or join the mailing list.
For more information visit the link:http://bse.42.org/[BSE web site].

link:http://www.fug-fr.org/[FUG-FR]::
The FreeBSD User Group France (FUG-FR) is an group of FreeBSD enthusiasts in France currently involved translating marketing papers etc.
They are also active in helping out FOSDEM (held in Brussels).
For more information please visit our web page link:http://www.fug-fr.org/[http://www.fug-fr.org] or contact link:mailto:rodrigo@bebik.net[Rodrigo Osorio].

link:https://www.meetup.com/Dublin-BSD-User-Group/[Dublin BSD User Group]::
The Dublin BSD User Group is a collective of individuals who are interested in the application of BSDs in production scenarios.
We are interested in how the BSDs can help both sysadmins and application developers deploy and manage robust solutions as well as looking at some of the unique features of the BSDs.
For more information please visit our link:https://www.meetup.com/Dublin-BSD-User-Group/[website].

link:http://www.lissyara.su[Lissyara.su]::
We are a russian FreeBSD community.
On our site we offer several articles for setting up FreeBSD and various other applications.
In addtition to the articles we also provide a link:http://forum.lissyara.su/[user forum] where experienced users of FreeBSD are pleased to be able to help other users.

link:http://bsdportal.ru[Russian FreeBSD User Group (RFUG)]::
The Russian FreeBSD User Group (RFUG) is a Russian language oriented user group for the Russian and ex-USSR users.
Located in Russia.

link:http://www.ulbsd.ru/[Ulyanovsk FreeBSD Users Group]::
The Ulyanovsk FreeBSD Users Group (ULBSD) is for Russian users of ULBSD operating system that is based on FreeBSD.
We provide free and paid versions of our operating system.
We also answer many questions of users for free and help them work in the FreeBSD and ULBSD.
For more information send an email to link:mailto:info@ulbsd.ru[info@ulbsd.ru] or visit the website at link:http://www.ulbsd.ru/[http://www.ulbsd.ru/].
Located in Ulyanovsk, Russia.

link:http://www.gufi.org/[Gruppo Utenti FreeBSD Italia (GUFI)]::
The Gruppo Utenti FreeBSD Italia (GUFI) is a "italian powered" FreeBSD User Group.
It is intended to help Italian FreeBSD users to find support and articles on/about FreeBSD in the italian language.
Please follow this link:http://www.gufi.org/[link] to know more about us.
Located in Italia.

link:http://www.bug.lv[BSD User Group Latvia]::
To learn more about the BSD User Group Latvia, please visit our link:http://www.bug.lv/[site] and our link:http://www.bug.lv/[forums].
Located in Latvia.

link:http://www.nobug.no/[The Norwegian BSD User Group (NOBUG)]::
The Norwegian BSD User Group (NOBUG) is a User Group for BSD users and enthusiasts in Norway.
Meetings are currently held in Oslo and Bergen.
Visit our website for more information. There is also a Unix User Group (link:http://www.nuug.no/[NUUG]) with more regular meetings, sometimes even with a BSD subject. Located in Norway.

link:https://bsd-pl.org/[Polish BSD User Group]::
Our group was created to promote systems from the BSD family in Poland.
We organize meetings that bring together lovers of Unix systems.
Located in Warsaw.

link:https://www.sbug.org/[SBUG]::
SBUG is a *BSD user group based in Rzeszow and targeting the Podkarpackie Voivodeship.

link:mailto:ptbsd@yahoo.com[The Portuguese *BSD Users Group]::
The Portuguese *BSD Users Group is a User Group for Portuguese users of BSD operating systems.
Contact Rui Pereira link:mailto:ptbsd@yahoo.com[ptbsd@yahoo.com] for more information.
Located in Portugal, Amadora.

link:https://bsd.si/[BSD User Group Slovenia]::
BSD User Group Slovenia connects BSD system users in Slovenia.
Group members also gather on the ##bsd.si IRC channel on Libera Chat.
Located in Ljubljana, Slovenia.

link:http://www.bsd.hu/[The Hungarian BSD Group]::
The Hungarian BSD Group is a group of NetBSD, FreeBSD, and OpenBSD users located in Hungary.
Their meetings occur on the second Friday of the month.
The website of the group is link:http://www.bsd.hu/[http://www.bsd.hu/].

link:https://lists.stacken.kth.se/mailman/listinfo/bus[BSD Users Sweden (BUS)]::
The BSD Users Sweden (BUS) maintains a mailing list.
To join send an email to link:mailto:majordomo@stacken.kth.se[majordomo@stacken.kth.se] with `subscribe bus` in the body.
Located in Sweden.

link:http://www.bsdgroups.org.uk/manchester[Manchester BSD Users Group]::
The Manchester BSD Users Group meets reasonably often in the Lass O'Gowrie, on Charles Street, Manchester.
Contact link:mailto:sams@bsdgroups.org.uk[Sam Smith] for more information.
Located in The United Kingdom, Manchester.

link:http://mailman.uk.freebsd.org/mailman/listinfo/ukfreebsd[FreeBSD UK Users group (FreeBSD UKUG)]::
The FreeBSD UKUG (FreeBSD UK User's Group) exists for the benefit of FreeBSD users in the United Kingdom.
Please follow the link for more information.
Located in the United Kingdom.

link:https://twitter.com/bsdbelfast[The BSD in Belfast Group]::
Meet the BSD Belfast Group the third Friday of the month.
We are a group of academic and industrial BSD users and admirers.

link:https://freebsd.web.tr/[FreeBSD Türkiye]::
We are a community of FreeBSD enthusiasts and professionals dedicated to supporting and advancing FreeBSD systems.
Our group actively engages in writing documentation, contributing code, and conducting research to enhance the FreeBSD ecosystem.
Whether you're an experienced developer or just starting with FreeBSD, join us in fostering collaboration and innovation within the Turkey FreeBSD community.

[[north-america]]
=== North America

link:http://sites.google.com/site/bugortn/Home[BSD User Group Oak Ridge (BUGOR)]::
BUGOR is an open and free network of BSD users in the Oak Ridge TN area.
Ideally, professional sysadmins, programmers and grizzled old hackers will meet each week to explore and debate the intricacies of the Unix design philosophy and the art of Unix programming while mentoring neophyte users and rehabilitating WIMP users.

link:http://www.buug.org[The Berkeley Unix User Group]::
The Berkeley Unix User Group is a general Unix Users Group for anyone in the San Fransico Bay Area.
We meet on a weekly basis in downtown Berkeley.
Visit the web site or send a message to link:mailto:buug-request@weak.org[buug-request@weak.org] with `subscribe` in the body.
Located in Berkeley, CA.

link:http://lists.nycbug.org/mailman/listinfo/cdbug-talk[The Capitals District *BSD Users Group]::
The Capitals District *BSD Users Group draws it's membership from New York's capital district and the surrounding communities.
CDBUG was founded in December of 2004 and has a small but growing membership.
We currently meet on the last Sunday of every month in the Albany area.
Our mailing list is graciously being hosted by NYCBUG at: link:http://lists.nycbug.org/mailman/listinfo/cdbug-talk[http://lists.nycbug.org/mailman/listinfo/cdbug-talk].
Located in Albany, NY.

link:https://www.meetup.com/CharmBUG[Baltimore Area BSD Operating System User Group (CharmBUG)]::
CharmBUG is a Baltimore Area BSD Operating System User Group, where the focus is on FreeBSD, OpenBSD, NetBSD and DragonFly BSD, including system administration and security across all UNIX like operating systems.
Please contact link:mailto:shirkdog@gmail.com[shirkdog@gmail.com] for details.

link:http://ufo.chicago.il.us[The Users of Free Operating Systems (UFO Chicago)]::
The Users of Free Operating Systems (UFO Chicago) is an open-source Unix User Group that meets twice a month in Chicago.
For directions and mailing list information, please check our web site link:http://ufo.chicago.il.us[http://ufo.chicago.il.us].
Chicago, IL.

link:http://cobug.org[The Colorado BSD Users Group (CoBUG)]::
Created in 2014, CoBUG is a completely open BSD community, established with the intention of spreading love for the BSDs.
Located in Colorado.

link:https://hambug.ca[HamBUG]::
The Hamilton (Ontario, Canada) BSD User Group meets on the second Tuesday of each month.
Meetings consist of open discussions, short demonstrations, and question & answer time.
Users from the entire GTA (Greater Toronto Area), London, and Waterloo regularly attend.

link:http://knoxbug.org[KnoxBUG]::
The Knoxville, Tennessee BSD User Group (KnoxBUG) meets once a month.
For more information, please visit link:http://knoxbug.org[http://knoxbug.org] and/or subscribe to our link:http://lists.nycbug.org/mailman/listinfo/knoxbug-talk[mailing list].

link:mailto:majordomo@swcp.com[NMLUG]::
The NMLUG in Alburquerque meets once a month and supports both BSD and Linux users.
To join the mailing list, send a message to link:mailto:majordomo@swcp.com[majordomo@swcp.com] with `subscribe nmlug` in the body.
Located in New Mexico.

link:http://www.nycbug.org[New York City *BSD User Group (NYCBUG)]::
The New York City *BSD User Group (NYCBUG) meets the first Wednesday of the month.
Mailing lists are available at link:http://lists.nycbug.org[http://lists.nycbug.org].
Located in New York, NY.

link:mailto:rcarter@consys.com[Yavapai Free Unix Users Group]::
The Yavapai Free Unix Users Group is now forming for *BSD/Linux, etc., users in Northern Arizona.
Please contact Russel Carter (link:mailto:rcarter@consys.com[rcarter@consys.com]) for details.
Located in Northern Arizona.

link:http://www.wplug.org[Western Pennsylvania Linux Users Group (WPLUG)]::
The Western Pennsylvania Linux Users Group (WPLUG) has a strong and growing community of BSD users that it supports.
See our home page (link:http://www.wplug.org[http://www.wplug.org]) for information on regular meetings and join the mailing lists.
Located in Pennsylvania.

link:mailto:pdx-freebsd@toybox.placo.com[Portland (Oregon) FreeBSD Users Group]::
The Portland (Oregon) FreeBSD Users Group meets on the third Thursday of each month.
Mail link:mailto:pdx-freebsd@toybox.placo.com[The Portland FreeBSD Users Group].
Located in Portland, OR.

link:http://www.rlug.org[Reno Linux Users Group (RLUG)]::
The Reno Linux Users Group (RLUG) meets monthly in Reno, Nevada and discusses the use of BSD and Linux.
Visit link:http://www.rlug.org[our website] for more information, where you may also join our mailing list.
Located in Reno, NV.

link:http://www.seabug.org[Seattle BSD Users Group (SeaBUG)]::
The Seattle BSD Users Group (SeaBUG) meets occasionally. View our web site for more details and for information on how to join our mailing list.
Located in Seattle, WA.

link:https://sdbug.org/[San Diego BSD Users Group (SDBUG)]::
The San Diego BSD Users Group meets on the first Thursday of every
month, usually at AleSmith on Miramar Rd.
Check the link:https://sdbug.org/[website] and mailing lists for specifics.
Located in San Diego, CA.

link:http://www.tfug.org[Tucson Free Unix Group (TFUG)]::
Tucson Free Unix Group, Arizona. Located in Tucson, AZ.

link:http://www.su3g.org[The Southern Utah Unix Users Group (SU3G)]::
The Southern Utah Unix Users Group (SU 3 G, SU^3G, SU3G, or SUUUG) is for users of any version of Unix or Unix-like operating system, commercial or open source.
So, whether you use FreeBSD, Linux, Mac OS X, BSD/OS, Solaris, OpenBSD, or any other Unix or Unix-like OS, and if you live, work, or associate with someone who lives or works in southwestern Utah, then consider joining the SU 3 G.
For more information send an email to link:mailto:kendall@su3g.org[kendall@su3g.org] or visit the website at link:http://www.su3g.org/[http://www.su3g.org/].

link:http://capbug.org[Capital Area BSD Users Group]::
We meet on the last Tuesday of the month.
Join our link:http://groups.google.com/group/capbug[mailing list] or visit our web site link:http://www.capbug.org[here].
We meet in Maryland, but welcome anyone from MD, DC or VA.

link:http://www.kcbug.org[Kansas City Area *BSD User.s Group]::
We are a beginning BSD User Group with currently two members.
If you would like to join, please visit our web site link:http://www.kcbug.org/[here].
Our goals are to have fun, help others to learn about and using *BSD and evangelize the BSD operating systems.

link:http://www.gtabug.ca[GTABUG]::
The GTABUG User Group welcomes all BSD users.
Monthly meetings give attendees a chance to share ideas, discussion and information.
Installations and other events help preach the good news of BSD to the community.
Come drop by for a meeting! Located in Greater Toronto Area, Ontario.

link:http://www.ocbug.ca/[Ottawa-Carleton Unix Users Group]::
We are a small group of hobbyists, users, authors, sysadmins, and hackers that meet monthly to discuss the latest topics in a very informal setting.
Check our link:http://mail.ocbug.ca/mailman/listinfo/ocbug_ocbug.ca[mailing list] for the latest information.
Located in Ottawa, Ontario.

link:https://www.orlandobsd.org/[The Orlando BSD Users Group]::
A small BSD user group from the greater Orlando area in central Florida.
We are a group of computer hobbyists, I/T professionals, and Makerspace enthusiasts.

[[south-america]]
=== South America

link:http://www.bsd.cl/[BSD Chile]::
The BSD Chile User Group (bsd.cl) maintains mirrors, documents, and mailing lists for the Chilean BSD community.
The group also provides infrastructure for BSD events in Chile and can be reached on the IRC server irc.bsd.cl #BSD in addition to the link:www.bsd.cl[web site].

link:https://www.fug.com.br/[The Brazilian FreeBSD User Group (FUG-BR)]::
The Brazilian FreeBSD User Group (FUG-BR) is a Portuguese language oriented User Group intended to help Brazilian FreeBSD users to find support and articles on and about FreeBSD in the Portuguese language.
We keep some projects such as the link:https://sourceforge.net/projects/livecd/[FreeBSD LiveCD].
Currently the group has over 800 members and our mailing list has an average traffic of 80 messages per day.
To join FUG-BR mailing list, visit https://www.fug.com.br/mailman/listinfo/www

[[asia]]
=== Asia

link:https://www.kbug.gr.jp/[The Kansai *BSD Users Group (K*BUG)]::
The Kansai *BSD Users Group was established on November 13, 1999.
It is expected to promote communication of any of the BSD variants' users.
Some of its activities are to hold friendly parties of the members, and to hold seminars covering wide variety of topics.
Please e-mail here (link:mailto:kbug-admin@kbug.gr.jp[kbug-admin@kbug.gr.jp]).
Located in Kansai, Japan.

link:https://www.ebug.jp/[The Echigo BSD Users Group (EBUG)]::
The Echigo BSD Users Group is the users group for BSD users around Echigo (aka Niigata).
For more information on our events and mailing lists, please check the EBUG web site.

link:mailto:22961476@students.ukdw.ac.id[The Jogja FreeBSD Users Group]::
The Jogja FreeBSD Users Group is based in Yogyakarta City, Indonesia.
Send email to 22961476@students.ukdw.ac.id for more information.

link:http://www.meetbsd.ir[meetBSD Iran]::
meetbsd.ir is an Iranian BSD user group that provides conferences, iso, ebooks, and PKGs for BSD local users.

link:http://www.mybsd.org.my[The MyBSD Malaysia Project]::
The MyBSD Malaysia Project is a Kuala Lumpur based User Group for BSD users and open-source in general, promoting and supporting FreeBSD, OpenBSD, NetBSD and open source usage.
We meet once a month, usually at Universiti Malaya or Restaurant Bahadur Shah.
One of our projects is to develop a link:http://staff.mybsd.org.my/skywizard/bsd-explorer[Unix file manager].
Visit our web site or contact link:mailto:info@mybsd.org.my[info@MyBSD.org.my] for more information.

link:http://ndbug.in[New Delhi BSD User Group]::
The New Delhi BSD User Group (NDBUG) is a group of hobbyists, professionals, and enthusiasts.
Our members share interests in BSD Unix and free implementations of Unix, as well as other open source software.
NDBUG was founded to disseminate knowledge of BSD Unix, open source software, and related technologies and interests in India and New Delhi specifically.

link:https://bsdtw.org/[BSD Taiwan]::
BSD Taiwan is a BSD user group for Taiwanese BSD users, where we can share knowledge, ideas, and seek help.
For more information please visit our link:https://bsdtw.org[website].

link:https://ambug.org[Armenia BSD User Group]::
We're a community of BSD Hackers, Unix Sysadmins and Unix-like system users who gather once a month (online and offline) to discuss BSD Unix related topics.

[[oceania]]
=== Oceania

link:https://www.humbug.org.au/[Home Unix Users Group for Brisbane]::
We meet fortnightly at meeting rooms provided by the link:http://www.uq.edu.au/[University of Queensland].
More information, including how to join the mailing lists, is available at link:http://www.humbug.org.au/[http://www.humbug.org.au].
Located in Queensland.

link:mailto:majordomo@lemis.com[BUGA, The BSD User Group of Adelaide]::
We meet at irregular intervals.
Join the mailing list by sending a message to link:mailto:majordomo@lemis.com[majordomo@lemis.com] with the text `subscribe BUGA` in the body.
Located in South Australia.

link:http://www.bugs.au.FreeBSD.org/[BSD Users Group, Sydney (BUGS)]::
The BSD Users Group, Sydney (BUGS) meets occasionally in Sydney and surrounds.
We have members from all over NSW.
To join the mailing list or IRC channel, visit link:http://www.bugs.au.freebsd.org/[http://www.bugs.au.freebsd.org/].
Located in New South Wales.

[[global]]
=== Global

link:https://metabug.org/[The Global BSD User Groups]::
The Global BSD User Groups organization was founded to help promote local BSD user groups by helping to share ideas and experiences with other BUG organizations.
Our goals are: We are working on ways to provide remote participation through streaming video of presentations.
You can check our link:https://metabug.org/[website] or contact us via link:mailto:info@metabug[e-mail].
