---
title: "FreeBSD/sparc64 Project"
sidenav: developers
---

include::shared/de/urls.adoc[]

= FreeBSD/sparc64 Project

[[intro]]
== Einführung

Diese Seite enthält Informationen über die Portierung von FreeBSD auf die SPARC64(R)-Architektur von Fujitsu sowie auf die UltraSPARC(R) Architektur von Oracle. Diskussionen über diese Portierung finden auf der Mailingliste https://lists.freebsd.org/mailman/listinfo/freebsd-sparc64[freebsd-sparc] statt.

== Inhaltsverzeichnis

* <<status,Status>>
* <<hw,Hardware-Liste>>
* <<list,FreeBSD/sparc64 mailing list>>
* <<links,Weiterführende Informationen>>

[[status]]
== Status

UltraSPARC ist bis FreeBSD 12.X eine link:{committers-guide}#archs[Tier 2]-Architektur und als solche vom https://www.FreeBSD.org/[FreeBSD] Project nicht vollständig unterstützt. Beginnend mit FreeBSD 13.0 wird UltraSPARC nicht mehr unterstützt werden.

[[hw]]
== Hardware-Liste

Unten finden Sie eine Liste der unterstützten Systeme. SMP funktioniert auf allen unterstützten Systemen, die mehr als einen Prozessor besitzen. Alle Einzelheiten entnehmen Sie bitte den https://www.FreeBSD.org/releases/&rel.current;R/hardware.html[Hardware-Notes] des von Ihnen benutzten link:&base;/releases/[Release].

* Naturetech GENIALstation 777S
* Sun Blade 100
* Sun Blade 150
* Sun Enterprise 150
* Sun Enterprise 220R
* Sun Enterprise 250
* Sun Enterprise 420R
* Sun Enterprise 450
* Sun Fire B100s (die integrierte Netzwerkkarte wird ab 8.1-RELEASE unterstützt)
* Sun Fire V100
* Sun Fire V120
* Sun Netra(TM) T1 100/105
* Sun Netra T1 AC200/DC200
* Sun Netra t 1100
* Sun Netra t 1120
* Sun Netra t 1125
* Sun Netra t 1400/1405
* Sun Netra 120
* Sun Netra X1
* Sun SPARCEngine(R) Ultra AX1105
* Sun SPARCEngine Ultra AXe
* Sun SPARCEngine Ultra AXi
* Sun SPARCEngine Ultra AXmp
* Sun SPARCEngine CP1500
* Sun Ultra(TM) 1
* Sun Ultra 1E
* Sun Ultra 2
* Sun Ultra 5
* Sun Ultra 10
* Sun Ultra 30
* Sun Ultra 60
* Sun Ultra 80
* Sun Ultra 450

Die folgenden Systeme werden von FreeBSD nur teilweise unterstützt. Insbesondere werden Fibre-Channel-Controller in SBus-basierten Systemen derzeit noch nicht unterstützt. Es ist allerdings möglich, diese Systeme mit vom esp(4)-Treiber unterstützten SCSI-Controllern (Sun ESP SCSI-, Sun FAS Fast-SCSI- sowie Sun FAS366 Fast-Wide SCSI-Controller) zu betreiben.

* Sun Enterprise 3500
* Sun Enterprise 4500

Beginnend mit 7.2-RELEASE werden auch Sparc64-Systeme (die auf Sun UltraSPARC III und neuer basieren) von FreeBSD unterstützt. Dazu gehören die folgenden Systeme:

* Sun Blade 1000
* Sun Blade 1500
* Sun Blade 2000
* Sun Blade 2500
* Sun Fire 280R
* Sun Fire V210
* Sun Fire V215 (ab FreeBSD 7.3-RELEASE/8.1-RELEASE unterstützt)
* Sun Fire V240
* Sun Fire V245 (ab FreeBSD 7.3-RELEASE/8.1-RELEASE unterstützt)
* Sun Fire V250
* Sun Fire V440 (die On-Board-Netzwerkkarte wird beginnend mit FreeBSD 7.3-RELEASE/8.0-RELEASE unterstützt)
* Sun Fire V480 (seit FreeBSD 7.3-RELEASE/8.0-RELEASE werden die Centerplanes 501-6780 unterstützt, weitere Centerplanes sollen ab FreeBSD 8.3-RELEASE/9.0-RELEASE unterstützt werden)
* Fire V880
* Sun Fire V890 (ab 7.4-RELEASE/8.1-RELEASE unterstützt, nur reine Ultrasparc IV/IV+ CPU-Konfigurationen)
* Sun Netra 20/Netra T4

Die folgenden UltraSPARC IIIi-Systeme wurden zwar nicht getestet, sollten aber von FreeBSD ebenfalls unterstützt werden:

* Sun Fire V125
* Sun Fire V490 (ab 7.4-RELEASE/8.1-RELEASE unterstützt, nur reine Ultrasparc IV/IV+ CPU-Konfigurationen)

Beginnend mit 7.4-RELEASE und 8.1-RELEASE werden auch Sparc64-Systeme (die auf Fujitsu SPARC64 V basieren) von FreeBSD unterstützt. Dazu gehören die folgenden Systeme:

* Fujitsu PRIMEPOWER(R) 250

Die folgenden Fujitsu SPARC64-Systeme wurden zwar nicht getestet, sollten aber von FreeBSD ebenfalls unterstützt werden:

* Fujitsu PRIMEPOWER 450
* Fujitsu PRIMEPOWER 650
* Fujitsu PRIMEPOWER 850

Haben Sie ein System, welches hier nicht angeführt ist, lassen Sie mailto:freebsd-sparc@FreeBSD.org[uns] dies bitte wissen.

[[list]]
== Mailingliste FreeBSD/sparc64

Um diese Liste zu abonnieren, senden Sie eine E-Mail an `<freebsd-sparc64-subscribe@FreeBSD.org>` oder besuchen Sie die https://lists.FreeBSD.org/mailman/listinfo/freebsd-sparc64[mailman-Schnittstelle].

[[links]]
== Weiterführende Informationen

* http://www.sparc.org/technical-documents-test-2/[SPARC Standard Dokumente]
* http://www.netbsd.org/Ports/sparc64/[NetBSD/sparc64]
* http://www.openbsd.org/sparc64.html[OpenBSD/sparc64]
