---
title: "Исправления и дополнения для FreeBSD 14.5-RELEASE"
sidenav: download
---

:release: 14.5-RELEASE
:releaseNext: 14.6-RELEASE
:releaseBranch: 14-STABLE

= Исправления и дополнения для FreeBSD {release}

== Аннотация

В этом документе перечислены исправления и дополнения для FreeBSD {release}, содержащие важную информацию, обнаруженную после релиза или слишком поздно в цикле его подготовки, чтобы быть включённой в документацию к релизу.
Эта информация включает рекомендации по безопасности, а также новости, связанные с программным обеспечением или документацией, которые могут повлиять на его работу или удобство использования.
Перед установкой этой версии FreeBSD всегда следует обращаться к актуальной версии этого документа.

Этот документ исправлений и дополнений для FreeBSD {release} будет поддерживаться до выхода FreeBSD {releaseNext}.

== Содержание

* <<intro,Введение>>
* <<security,Уведомления о безопасности>>
* <<errata,Уведомления об исправлениях>>
* <<open-issues,Открытые проблемы>>
* <<late-news,Последние новости>>

[[intro]]
== Введение

Этот документ исправлений и дополнений содержит «последние новости» о FreeBSD {release}.
Перед установкой этой версии важно ознакомиться с этим документом, чтобы узнать о любых проблемах, обнаруженных после релиза, которые, возможно, уже были найдены и исправлены.

Любая версия этого документа исправлений и дополнений, фактически распространяемая с релизом (например, на диске CDROM), по определению будет устаревшей, но другие копии поддерживаются в актуальном состоянии в Интернете и должны рассматриваться как «текущие исправления» для этого выпуска.
Такие копии исправлений находятся по адресу https://www.FreeBSD.org/ru/releases/, а также на любых сайтах, которые поддерживают актуальные зеркала этого расположения.

Исходные и бинарные промежуточные сборки FreeBSD {releaseBranch} также содержат актуальные копии этого документа (на момент создания промежуточной сборки).

Список всех рекомендаций по безопасности FreeBSD CERT доступен по адресу https://www.FreeBSD.org/ru/security/.

[[security]]
== Уведомления о безопасности

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Уведомление |Дата |Тема

|Нет бюллетеней.||

|===

[[errata]]
== Уведомления об исправлениях

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Уведомление |Дата |Тема

|Уведомлений об исправлениях нет.||

|===

[[open-issues]]
== Открытые проблемы

1. Системы с **часто изменяющимися таблицами маршрутизации**, такие как BGP-маршрутизаторы, которые используют алгоритмы по умолчанию, могут работать нестабильно из-за утечки памяти. Это не касается систем, в которых явно настроены альтернативные алгоритмы маршрутизации. +
**Обходной путь**: Переключитесь на алгоритм маршрутизации без блокировок (non-lockless) с помощью `sysctl net.route.algo.inet4.algo=radix4` или `sysctl net.route.algo.inet6.algo=radix6`. +
**Состояние**: Открыта — https://bugs.freebsd.org/297339 +

[[late-news]]
== Актуальные новости

Актуальных новостей нет.

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (08.09.2026): 5109a54517fb819c8a16831f30569947303d8166
//
