---
title: "Инструкция по установке FreeBSD 14.5-RELEASE"
sidenav: download
---

:releaseCurrent: 14.5-RELEASE
:releasePrev: 14.4-RELEASE
:releasePrevLegacy: 13.5-RELEASE
:localRel: 14.5

include::shared/ru/urls.adoc[]

= Инструкция по установке FreeBSD {localRel}-RELEASE

== Краткое содержание

Эта статья содержит краткие инструкции по установке FreeBSD {releaseCurrent} и обновлению систем, работающих под управлением предыдущих релизов.

== Содержание

* <<install,Установка FreeBSD>>
* <<upgrade,Обновление FreeBSD>>

[[install]]
== Установка FreeBSD

Глава link:{handbook}bsdinstall/[Установка FreeBSD] Руководства FreeBSD предоставляет более подробную информацию о самой программе установки, включая пошаговое руководство со снимками экранов.

[[upgrade]]
== Обновление FreeBSD

Если вы обновляетесь с предыдущего релиза FreeBSD, пожалуйста, внимательно прочитайте раздел об обновлении в link:../relnotes[Информации о релизе] для ознакомления с важными несовместимостями.

[[upgrade-source]]
== Обновление из исходного кода

Процедура обновления на основе исходного кода описана в главе Руководства link:{handbook}cutting-edge/#makeworld[Обновление FreeBSD из исходного кода].

Для Git используйте ветку releng/{localRel}, где будут применяться будущие рекомендации по безопасности или уведомления об ошибках.

[[upgrade-binary]]
== Обновление с помощью "FreeBSD Update"

Утилита man:freebsd-update[8] поддерживает бинарные обновления систем amd64 и arm64, работающих на предыдущих релизах FreeBSD.
Системы, работающие под управлением {releasePrev}, могут быть обновлены следующим образом:

[.screen]
----
# freebsd-update fetch
# freebsd-update install
----

Теперь утилита man:freebsd-update[8] может получать компоненты, относящиеся к {releaseCurrent}.
В ходе этого процесса man:freebsd-update[8] попросит помощи в слиянии конфигурационных файлов.

[.screen,subs="verbatim,attributes"]
----
# freebsd-update upgrade -r {localRel}-RELEASE
# freebsd-update install
----

Теперь система должна быть перезапущена с новым установленным ядром перед обновлением компонентов, не относящихся к ядру.

[.screen]
----
# shutdown -r now
----

После перезагрузки необходимо снова запустить man:freebsd-update[8] для установки новых компонентов пользовательского пространства:

[.screen]
----
# freebsd-update install
----

На этом этапе пользователям систем, обновляемых с более ранних выпусков FreeBSD, будет предложено пересобрать или переустановить все сторонние приложения (например, порты, установленные из дерева портов, или пакеты, установленные с помощью man:pkg[8]) из-за обновлений в системных библиотеках.

После обновления установленных сторонних приложений (и снова, только если man:freebsd-update[8] вывел сообщение, указывающее на необходимость этого), запустите man:freebsd-update[8] снова, чтобы он мог удалить старые (больше не используемые) системные библиотеки:

[.screen]
----
# freebsd-update install
----

Наконец, выполните перезапуск для загрузки полноценной системы {releaseCurrent}:

[.screen]
----
# shutdown -r now
----

//
// The FreeBSD Russian Documentation Project
//
// Original EN revision (15.04.2025): ca6dd170a5e9aee409824b6155ce80fd12824fe8
//
