---
title: FreeBSD Accessibility Handbook
authors:
  - author: Alfonso S. Siciliano
copyright: 2025 The FreeBSD Foundation
trademarks: ["freebsd"]
description: Assistive technologies available in FreeBSD
tags: ["Accessibility", "Documentation", "FreeBSD", "Index"]
next: books/accessibility/preface
add_single_page_link: true
showBookMenu: true
weight: 10
params:
  path: "/books/accessibility/"
bookOrder: 50
---

= FreeBSD Accessibility Handbook
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/accessibility/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

// Split HTML view, sync with book.adoc
[.abstract-title]
Abstract

Welcome to the Accessibility Handbook.
This book covers the assistive technologies available in FreeBSD.

Accessibility is an ongoing effort, not a fixed destination.
As such, this handbook is a living document and continually evolving.
Contributions, suggestions, and feedback are highly encouraged.
If you are interested in contributing, please reach out to us via the https://lists.freebsd.org/subscription/freebsd-accessibility[FreeBSD accessibility mailing list].

You can download this book in various formats and compression options from the FreeBSD download server or one of its many mirror sites.

'''
