# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

# DOCS=	announce.xml notes.xml errata.xml
DOCS= errata.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
