#
#    The FreeBSD Documentation Project
#    The FreeBSD German Documentation Project
#
#    $FreeBSD: doc/de_DE.ISO_8859-1/books/Makefile.inc,v 1.1 2000/08/25 18:33:40 alex Exp $
#    $FreeBSDde: de-docproj/books/Makefile.inc,v 1.4 2001/02/01 21:24:27 alex Exp $
#

TIDYFLAGS=	-latin1

DESTDIR?=	${DOCDIR}/de_DE.ISO_8859-1/books/${.CURDIR:T}
