# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/dists/Makefile,v 1.4 2003/10/16 10:57:57 den Exp $
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif
 
DOCS =	10.sgml
DOCS+=	11.sgml
DOCS+=	12.sgml
DOCS+=	13.sgml
DOCS+=	14.sgml
DOCS+=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
