# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/java/dists/Makefile,v 1.4 2003/10/16 10:57:57 den Exp $
# Original revision: 1.5

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
