# The FreeBSD Mongolian Documentation Project
#
# Original revision 1.1
#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD$

CHAPTERS= 	filesystems/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
