# $FreeBSD: www/en/releases/8.1R/Makefile,v 1.1 2010/04/04 06:10:42 kensmith Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml

DATA=	docbook.css \
	errata.html \
	hardware.html \
	readme.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
