# $FreeBSD: www/en/releases/4.3R/Makefile,v 1.1 2001/04/21 07:58:32 jkh Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	announce.sgml notes.sgml errata.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
