---
title: "Info sui Port di FreeBSD"
sidenav: ports
---

include::shared/it/urls.adoc[]

= Info sui Port di FreeBSD

{{< form-ports >}}

'''''

La Collezione dei Port e dei Package di FreeBSD offre un modo semplice di installare le applicazioni per gli utenti e gli amministratori. Attualmente ci sono diverse link:https://www.FreeBSD.org/growth/status.png[*migliaia*] di port disponibili.

La Collezione dei Port supporta l'ultima release dei rami link:{faq}#CURRENT[FreeBSD-CURRENT] e link:{faq}#STABLE[FreeBSD-STABLE]. Le release precedenti non sono supportate e possono o non possono funzionare correttamente con una collezioni dei port aggiornata. Col tempo, le modifiche alla collezione dei port possono basarsi su funzionalità non presenti nelle vecchie release. Quando possibile, cerchiamo di non rompere il supporto alle release recenti, ma talvolta non è possibile. Quando accade, le patch inviate dalla comunità utenti per mantenere il supporto alle vecchie release vengono solitamente accettate.

Ogni ''port'' elencato qui contiene tutte le patch necessarie per rendere il codice sorgente dell'applicazione originale compilabile ed eseguibile sotto FreeBSD. Installare un'applicazione è semplice: basta scaricare il port, decomprimerlo e digitare http://www.freebsd.org/cgi/man.cgi?query=make[`make`] nella directory del port. Tuttavia, il metodo più conveniente (e comune) è scaricare il framework per l'intera lista dei port, installando l'link:https://www.FreeBSD.org/ports/installing/[intera gerarchia dei port] durante l'installazione di FreeBSD, in modo da avere migliaia di applicazioni pronte per essere installate.

Il `Makefile` di ogni port scarica automaticamente il codice sorgente dell'applicazione, vuoi da un disco locale, vuoi da CD-ROM, vuoi via http://www.freebsd.org/cgi/man.cgi?query=ftp[`ftp`], lo decomprime sul tuo sistema, applica le patch, e lo compila. Se tutto è andato bene, un semplice `make install` installerà l'applicazione e la registrerà nel sistema dei package.

Per la maggior parte dei port, esiste anche un `package` precompilato, che evita all'utente il lavoro di compilare tutto. Ogni port contiene un collegamento al suo rispettivo package e puoi semplicemente scaricare quel file ed eseguire il comando http://www.freebsd.org/cgi/man.cgi?query=pkg_add[`pkg_add`] su di esso oppure puoi copiare il collegamento e passarlo direttamente a `pkg_add` visto che può accettare URL FTP oltre ai nomi di file.
