---
title: Problem Report Handling Guidelines
authors:
  - author: Dag-Erling Smørgrav
  - author: Hiten Pandya
description: These guidelines describe recommended handling practices for FreeBSD Problem Reports (PRs).
trademarks: ["freebsd", "general"]
tags: ["PR", "guideline", "bugs", "maintenance", "Bugzilla", "FreeBSD"]
---

= Problem Report Handling Guidelines
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:images-path: articles/pr-guidelines/

ifdef::env-beastie[]
ifdef::backend-html5[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
:imagesdir: ../../../images/{images-path}
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[.abstract-title]
Abstract

These guidelines describe recommended handling practices for FreeBSD Problem Reports (PRs).
Whilst developed for the FreeBSD PR Database Maintenance Team mailto:freebsd-bugbusters@FreeBSD.org[freebsd-bugbusters@FreeBSD.org], these guidelines should be followed by anyone working with reports.

'''

toc::[]

[[intro]]
== Introduction

Bugzilla is an issue management system used by the FreeBSD Project.
As accurate tracking of outstanding software defects is important to FreeBSD's quality, the correct use of the software is essential to the forward progress of the Project.

Access to Bugzilla is available to the entire FreeBSD community.
In order to maintain consistency within the database and provide a consistent user experience, guidelines have been established covering common aspects of bug management such as presenting followup and handling close requests.

[[pr-lifecycle]]
== Problem Report Life-cycle

* The Reporter submits a bug report on the website.
The report has `New` status.
* Jane Random BugBuster confirms that the report has sufficient information to be reproducible.
If not, she goes back and forth with the reporter to obtain the needed information.
At this point the status is set to `Open`.
* Joe Random Committer takes interest and assigns the report to himself, or Jane Random BugBuster decides that Joe is best suited to handle the report and assigns it to him.
The status should be set to `In Progress`.
* Joe has a brief exchange with the originator (making sure it all goes into the audit trail) and determines the cause of the problem.
* Joe pulls an all-nighter and whips up a patch that he thinks fixes the problem, and submits it in a follow-up, asking the originator to test it.
He then sets the status to `Patch Ready`.
* A couple of iterations later, both Joe and the originator are satisfied with the patch, and Joe commits it to `-CURRENT` (or directly to `-STABLE` if the problem does not exist in `-CURRENT`), making sure to reference the Problem Report in his commit log (and credit the originator if they submitted all or part of the patch) and, if appropriate, start an MFC countdown.
The status is set to `Needs MFC`.
* If the patch does not need MFCing, Joe then closes the report as `Fixed`.

[NOTE]
====
Many reports are submitted with very little information about the problem, and some are either very complex to solve, or just scratch the surface of a larger problem; in these cases, it is very important to obtain all the necessary information needed to solve the problem.
If the problem contained within cannot be solved, or has occurred again, it is necessary to re-open the report.
====

[[pr-states]]
== Problem Report Status

It is important to update the status when certain actions are taken.
The status should accurately reflect the current state of work on the report.

.An example on when to change status
[example]
====
When a report has been worked on and the developer(s) responsible feel comfortable about the fix, they will submit a followup and change its status to "feedback".
At this point, the originator should evaluate the fix in their context and respond indicating whether the defect has indeed been remedied.
====

A Problem Report may be in one of the following statuses:

New::
Initial state; the problem has been pointed out and the report needs reviewing.

Open::
The report has been reviewed and a solution is being sought.

feedback::
Further work requires additional information from the originator or the community; possibly information regarding the proposed solution.

patched::
A patch has been committed, but something (MFC, or maybe confirmation from originator) is pending.

suspended::
The problem is not being worked on, due to lack of information or resources.
This is a prime candidate for somebody who is looking for a project to take on.
If the problem cannot be solved at all, it will be closed, rather than suspended.
The documentation project uses suspended for wish-list items that entail a significant amount of work which no one currently has time for.

Closed::
A problem report is closed when any changes have been integrated, documented, and tested, or when fixing the problem is abandoned.

[NOTE]
====
The "patched" status is directly related to feedback, so you may go directly to "Closed" if the originator cannot test the patch, and it works in your own testing.
====

[[pr-types]]
== Types of Problem Report

While handling reports, either as a developer who has direct access or as a contributor who browses the database and submits followups with patches, comments, suggestions or change requests, you will come across several different types of report.

* <<pr-unassigned>>
* <<pr-assigned>>
* <<pr-dups>>
* <<pr-stale>>
* <<pr-misfiled-notpr>>

The following sections describe what each different type of report is used for, when a report belongs to one of these types, and what treatment each different type receives.

[[pr-unassigned]]
== Unassigned Reports

When reports arrive, they are initially assigned to a generic (placeholder) assignee.
These are always prepended with `freebsd-`.
The exact value for this default depends on the category; in most cases, it corresponds to a specific FreeBSD mailing list.
Here is the current list, with the most common ones listed first:

[[default-assignees-common]]
.Default Assignees - most common
[cols="1,1,1", options="header"]
|===
| Type
| Categories
| Default Assignee

|base system
|bin, conf, gnu, kern, misc
|freebsd-bugs

|architecture-specific
|alpha, amd64, arm, i386, ia64, powerpc, sparc64
|freebsd-_arch_

|ports collection
|ports
|freebsd-ports-bugs

|documentation shipped with the system
|docs
|freebsd-doc

|FreeBSD web pages (not including docs)
|Website
|freebsd-www
|===

[[default-assignees-other]]
.Default Assignees - other
[cols="1,1,1", options="header"]
|===
| Type
| Categories
| Default Assignee

|advocacy efforts
|advocacy
|freebsd-advocacy

|Java Virtual Machine(TM) problems
|java
|freebsd-java

|standards compliance
|standards
|freebsd-standards

|threading libraries
|threads
|freebsd-threads

|man:usb[4] subsystem
|usb
|freebsd-usb
|===

Do not be surprised to find that the submitter of the report has assigned it to the wrong category.
If you fix the category, do not forget to fix the assignment as well.
(In particular, our submitters seem to have a hard time understanding that just because their problem manifested on an i386 system, that it might be generic to all of FreeBSD, and thus be more appropriate for `kern`.
The converse is also true, of course.)

Certain reports may be reassigned away from these generic assignees by anyone.
There are several types of assignees: specialized mailing lists; mail aliases (used for certain limited-interest items); and individuals.

For assignees which are mailing lists, please use the long form when making the assignment (e.g., `freebsd-foo` instead of `foo`);
this will avoid duplicate emails sent to the mailing list.

[NOTE]
====
Since the list of individuals who have volunteered to be the default assignee for certain types of report changes so often, it is much more suitable for https://wiki.freebsd.org/AssigningPRs[the FreeBSD wiki]. 
====

Here is a sample list of such entities; it is probably not complete.

[[common-assignees-base]]
.Common Assignees - base system
[cols="1,1,1,1", options="header"]
|===
| Type
| Suggested Category
| Suggested Assignee
| Assignee Type

|problem specific to the ARM(R) architecture
|arm
|freebsd-arm
|mailing list

|problem specific to the MIPS(R) architecture
|kern
|freebsd-mips
|mailing list

|problem specific to the PowerPC(R) architecture
|kern
|freebsd-ppc
|mailing list

|problem with Advanced Configuration and Power Management (man:acpi[4])
|kern
|freebsd-acpi
|mailing list

|problem with Asynchronous Transfer Mode (ATM) drivers
|kern
|freebsd-atm
|mailing list

|problem with embedded or small-footprint FreeBSD systems (e.g., NanoBSD/PicoBSD/FreeBSD-arm)
|kern
|freebsd-embedded
|mailing list

|problem with FireWire(R) drivers
|kern
|freebsd-firewire
|mailing list

|problem with the filesystem code
|kern
|freebsd-fs
|mailing list

|problem with the man:geom[4] subsystem
|kern
|freebsd-geom
|mailing list

|problem with the man:ipfw[4] subsystem
|kern
|freebsd-ipfw
|mailing list

|problem with Integrated Services Digital Network (ISDN) drivers
|kern
|freebsd-isdn
|mailing list

|man:jail[8] subsystem
|kern
|freebsd-jail
|mailing list

|problem with Linux(R) or SVR4 emulation
|kern
|freebsd-emulation
|mailing list

|problem with the networking stack
|kern
|freebsd-net
|mailing list

|problem with the man:pf[4] subsystem
|kern
|freebsd-pf
|mailing list

|problem with the man:scsi[4] subsystem
|kern
|freebsd-scsi
|mailing list

|problem with the man:sound[4] subsystem
|kern
|freebsd-multimedia
|mailing list

|problems with the man:wlan[4] subsystem and wireless drivers
|kern
|freebsd-wireless
|mailing list

|problem with man:sysinstall[8] or man:bsdinstall[8]
|bin
|freebsd-sysinstall
|mailing list

|problem with the system startup scripts (man:rc[8])
|kern
|freebsd-rc
|mailing list

|problem with VIMAGE or VNET functionality and related code
|kern
|freebsd-virtualization
|mailing list

|problem with Xen emulation
|kern
|freebsd-xen
|mailing list
|===

[[common-assignees-ports]]
.Common Assignees - Ports Collection
[cols="1,1,1,1", options="header"]
|===
| Type
| Suggested Category
| Suggested Assignee
| Assignee Type

|problem with the ports framework (__not__ with an individual port!)
|ports
|portmgr
|alias

|port which is maintained by apache@FreeBSD.org
|ports
|apache
|mailing list

|port which is maintained by autotools@FreeBSD.org
|ports
|autotools
|alias

|port which is maintained by doceng@FreeBSD.org
|ports
|doceng
|alias

|port which is maintained by eclipse@FreeBSD.org
|ports
|freebsd-eclipse
|mailing list

|port which is maintained by gecko@FreeBSD.org
|ports
|gecko
|mailing list

|port which is maintained by gnome@FreeBSD.org
|ports
|gnome
|mailing list

|port which is maintained by hamradio@FreeBSD.org
|ports
|hamradio
|alias

|port which is maintained by haskell@FreeBSD.org
|ports
|haskell
|alias

|port which is maintained by java@FreeBSD.org
|ports
|freebsd-java
|mailing list

|port which is maintained by kde@FreeBSD.org
|ports
|kde
|mailing list

|port which is maintained by mono@FreeBSD.org
|ports
|mono
|mailing list

|port which is maintained by office@FreeBSD.org
|ports
|freebsd-office
|mailing list

|port which is maintained by perl@FreeBSD.org
|ports
|perl
|mailing list

|port which is maintained by python@FreeBSD.org
|ports
|freebsd-python
|mailing list

|port which is maintained by ruby@FreeBSD.org
|ports
|freebsd-ruby
|mailing list

|port which is maintained by secteam@FreeBSD.org
|ports
|secteam
|alias

|port which is maintained by vbox@FreeBSD.org
|ports
|vbox
|alias

|port which is maintained by x11@FreeBSD.org
|ports
|freebsd-x11
|mailing list
|===

Ports reports that have a maintainer who is a ports committer may be reassigned by anyone (but note that not every FreeBSD committer is necessarily a ports committer, so you cannot simply go by the email address alone). 

For other reports, please do not reassign them to individuals (other than yourself) unless you are certain that the assignee really wants to track the report.
This will help to avoid the case where no one looks at fixing a particular problem because everyone assumes that the assignee is already working on it.

[[common-assignees-other]]
.Common Assignees - Other
[cols="1,1,1,1", options="header"]
|===
| Type
| Suggested Category
| Suggested Assignee
| Assignee Type

|problem with PR database
|bin
|bugmeister
|alias

|problem with Bugzilla https://bugs.freebsd.org/submit/[web form].
|doc
|bugmeister
|alias
|===

[[pr-assigned]]
== Assigned Reports

If a report has the `responsible` field set to the username of a FreeBSD developer, it means that the report has been handed over to that particular person for further work.

Assigned reports should not be touched by anyone but the assignee or bugmeister.
If you have comments, submit a followup.
If for some reason you think the report should change status or be reassigned, send a message to the assignee.
If the assignee does not respond within two weeks, unassign the report and do as you please.

[[pr-dups]]
== Duplicate Reports

If you find more than one report that describe the same issue, choose the one that contains the largest amount of useful information and close the others, stating clearly the number of the superseding report.
If several reports contain non-overlapping useful information, submit all the missing information to one in a followup, including references to the others; then close the other reports (which are now completely superseded).

[[pr-stale]]
== Stale Reports

A report is considered stale if it has not been modified in more than six months.
Apply the following procedure to deal with stale reports:

* If the report contains sufficient detail, try to reproduce the problem in `-CURRENT` and `-STABLE`.
If you succeed, submit a followup detailing your findings and try to find someone to assign it to. Set the status to "analyzed" if appropriate.
* If the report describes an issue which you know is the result of a usage error (incorrect configuration or otherwise), submit a followup explaining what the originator did wrong, then close the report with the reason "User error" or "Configuration error".
* If the report describes an error which you know has been corrected in both `-CURRENT` and `-STABLE`, close it with a message stating when it was fixed in each branch.
* If the report describes an error which you know has been corrected in `-CURRENT`, but not in `-STABLE`, try to find out when the person who corrected it is planning to MFC it, or try to find someone else (maybe yourself?) to do it.
Set the status to "patched" and assign it to whomever will do the MFC.
* In other cases, ask the originator to confirm if the problem still exists in newer versions.
If the originator does not reply within a month, close the report with the notation "Feedback timeout".

[[pr-misfiled-notpr]]
== Non-Bug Reports

Developers that come across reports that look like they should have been posted to {freebsd-bugs} or some other list should close the report, informing the submitter in a comment why this is not really a report and where the message should be posted.

The email addresses that Bugzilla listens to for incoming reports have been published as part of the FreeBSD documentation, have been announced and listed on the web-site.
This means that spammers found them.

Whenever you close one of these reports, please do the following:

* Set the component to `junk` (under `Supporting Services`.
* Set Responsible to `nobody@FreeBSD.org`.
* Set status to `Closed`.

Setting the category to `junk` makes it obvious that there is no useful content within the report, and helps to reduce the clutter within the main categories.

[[references]]
== Further Reading

This is a list of resources relevant to the proper writing and processing of problem reports.
It is by no means complete.

* extref:{problem-reports}[How to Write FreeBSD Problem Reports]-guidelines for originators.
