# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/news/1997/Makefile,v 1.3 2001/12/05 19:30:40 phantom Exp $
# Original revision: 1.4

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
