# $FreeBSD: www/en/gnome/images/Makefile,v 1.12 2003/07/16 05:23:51 marcus Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

# For screenshots, please create 320x240 thumbnails of the images, and name
# them <imagename>-tn.png.  This will minimize the load time for the index
# page.  You can use the convert tool included with ImageMagick to do this:
#
# convert -geometry 320x240\! <imagename>.png <imagename>-tn.png

DATA=	ss7.png
DATA+=	ss7-tn.png
DATA+=	ss8.png
DATA+=	ss8-tn.png
DATA+=	ss9.png
DATA+=	ss9-tn.png
DATA+=	ss10.png
DATA+=	ss10-tn.png
DATA+=	ss11.png
DATA+=	ss11-tn.png
DATA+=	ss12.png
DATA+=	ss12-tn.png
DATA+=	gnome.png

.include "${WEB_PREFIX}/share/mk/web.site.mk"
