---
title: FreeBSD Documentation Project
sidenav: docs
---

= FreeBSD Documentation Project

== Überblick

Sich mit einem neuen und komplexen Betriebssystem vertraut zu machen, ist immer eine schwierige Aufgabe, egal wie bunt die grafische Oberfläche auch sein mag. Dies gilt auch für FreeBSD.

Zwar gibt es viele Bücher zu BSD Unix (und UNIX(R) im Allgemeinen), die aber in der Regel nicht die einzigartigen Fähigkeiten, Prozeduren oder Besonderheiten von FreeBSD abdecken.

Für viele Benutzer ist FreeBSD der erste Kontakt mit einem Unix-artigem Betriebssystem, daher ist eine hochwertige, ausführliche Dokumentation von elementarer Bedeutung.

Das FreeBSD Documentation Project wurde gegründet, um diese Lücke zu schließen. Dabei konzentriert es sich auf folgende Bereiche:

. Mitglieder des Documentation Projects schreiben und verbessern Teile der Dokumentation, die danach in die offizielle _FreeBSD Dokumentation_ aufgenommen wird.
. Mitglieder des Documentation Projects diskutieren und implementieren die Formatierung und Organisation der offiziellen _FreeBSD Documentation_.

[width="100%",cols="100%",]
|===
a|
[.center]
=== https://www.FreeBSD.org/docproj/current/[Aktuelle Projekte]

Im Rahmen des Documentation Projects wird _ständig_ an verschiedenen Projekten gearbeitet. Lesen Sie sich bitte diese Liste durch und überlegen Sie sich, ob *Sie* eines dieser Projekte unterstützen könnten.

|===

== link:who/[Wer wir sind und wie Sie uns helfen können]

Diese Seite beschreibt die Organisation des Documentation Projects und erklärt auch, wie Sie dieses Projekt unterstützen können.

== link:doc-set/[Die FreeBSD-Dokumentation]

Auf dieser Seite wird der Aufbau der FreeBSD-Dokumentation beschrieben. Außerdem wird näher auf die Arbeit des Documentation Projects eingegangen.

== link:sgml/[SGML und das Documentation Project]

Die FreeBSD-Dokumentation wird in SGML geschrieben. Diese Seite erklärt, wie SGML bei der Arbeit an der Dokumentation eingesetzt wird und liefert Ihnen auch einige Links zu weiteren SGML-Ressourcen.

== link:submitting/[Beiträge einreichen]

Das Schreiben und Einreichen von Dokumentationen ist der beste Weg, um Teil des Documentation Projects zu werden und die Benutzung von FreeBSD zu vereinfachen. Diese Seite erklärt Ihnen, wie Sie Ihre Beiträge am besten einreichen, damit diese möglichst rasch geprüft werden können.

== https://www.FreeBSD.org/docproj/translations/[Übersetzungen]

Übersetzungen der FreeBSD-Dokumentation, der Internetseiten, des Handbuchs, der FAQ, der Manualpages und anderer Dokumente.
