---
title: "FreeBSD Documentation Project: Wer sind wir?"
sidenav: docs
---

include::shared/de/urls.adoc[]

= FreeBSD Documentation Project: Wer sind wir?

Das Documentation Project besteht aus einem losen Zusammenschluss verschiedener Personen, die alle die Mailingliste FreeBSD-doc@FreeBSD.org abbonniert haben.

Einige von uns dürfen Änderungen direkt in den FreeBSD Dokumentationsbaum einbringen (_committen_). Eine vollständige Liste aller link:{contributors}#staff-committers[FreeBSD-Entwickler mit Commit-Privilegien] sowie eine Liste mit den link:../administration/#t-doceng[leitenden Committern des FreeBSD Documentation Projects] sind auf den Internetseiten des FreeBSD Projects verfügbar.

Mitarbeiter ohne Commit-Privilegien können natürlich trotzdem an der Dokumentation arbeiten und ihre Beiträge einreichen. Wenn deren Beiträge gemäß den Anleitungen auf der Seite link:../submitting[Beiträge einreichen] eingereicht wurden, werden diese von einem oder mehreren Committern geprüft und danach in die FreeBSD-Dokumentation aufgenommen.

Wenn Sie das FreeBSD Documentation Project unterstützen wollen (worüber wir uns sehr freuen würden), müssen Sie lediglich die Mailingliste abbonnieren und Ihre Beiträge einreichen. Schon sind Sie ein Mitglied des Documentation Projects.

link:..[Startseite des FreeBSD Documentation Projects]
