---
title: "FreeBSD 2.1 Announcement"
sidenav: download
--- 

= FreeBSD 2.1 Announcement

Date: Sun, 19 Nov 1995 14:48:46 -0800 +
From: "Jordan K. Hubbard" <jkh@freebsd.org> +
To: announce@freefall.cdrom.com +
Subject: 2.1.0-RELEASE now available!

Could it be? Could the long-awaited release of FreeBSD 2.1 truly have arrived?

It gives me great pleasure to answer those questions with a ``yes!''

FreeBSD 2.1.0-RELEASE is now available on ftp://ftp.freebsd.org/pub/FreeBSD/2.1.0-RELEASE/[ftp.freebsd.org] and various FTP https://www.freebsd.org/handbook/mirrors.html[mirror sites throughout the world]. It can also be ordered on CD from http://www.cdrom.com/[Walnut Creek CDROM], from where it will be shipping shortly.

FreeBSD 2.1 represents the culmination of 6 months worth of work on the 2.1-STABLE branch of FreeBSD since the previous release (FreeBSD 2.0.5).

The STABLE branch was conceived out of the need to allow FreeBSD to grow and support long-term development projects like devfs, NFSv3, IPX, PCCARD, etc. while at the same time not jeopardizing the stability of its existing user base. Experimental or high-impact changes are allowed into https://www.freebsd.org/handbook/current.html[FreeBSD-current], which represents a sort of shared group development tree, and only well tested or obvious fixes are allowed into STABLE. In a few rare cases, where some bit of functionality was entirely missing before, we've supplied an ALPHA test quality version in STABLE on the premise that some functionality is better than none at all (a good example being the IDE CDROM driver).

For more information on the 2.1 release itself, please consult the documentation that accompanies the https://www.freebsd.org/handbook/install.html[installation procedure].

Jordan

link:../../[Release Home]
