#       $Id: Makefile,v 1.4 1999-09-03 17:24:43 nik Exp $

SUBDIR = faq
SUBDIR+= fdp-primer
SUBDIR+= handbook

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
