#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/portmgr/Makefile,v 1.1 2005/06/13 06:43:35 andy Exp $
#
# Original revision: 1.1
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	index.xml charter.xml policies.xml qa.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
