=== Cirrus-CI

Links: +
link:https://cirrus-ci.com/github/freebsd/[FreeBSD Cirrus-CI Repositories] URL: link:https://cirrus-ci.com/github/freebsd/[] +
link:https://cirrus-ci.com/github/freebsd/freebsd-src[FreeBSD src CI] URL: link:https://cirrus-ci.com/github/freebsd/freebsd-src[] +
link:https://cirrus-ci.com/github/freebsd/freebsd-doc[FreeBSD doc CI] URL: link:https://cirrus-ci.com/github/freebsd/freebsd-doc[]

Contact: Brooks Davis <brooks@FreeBSD.org> +
Contact: Ed Maste <emaste@FreeBSD.org> +
Contact: Li-Wen Hsu <lwhsu@FreeBSD.org>

Cirrus-CI is a hosted continuous integration service that supports open source projects with CI services on Linux, Windows, macOS, and FreeBSD.
It complements our own Jenkins CI infrastructure by supporting other use cases, including testing GitHub pull requests and FreeBSD forks.
We added Cirrus-CI configuration to the FreeBSD src tree in 2019 and to doc in 2020.
A number of additional FreeBSD projects hosted on GitHub (such as drm-kmod, kyua, pkg, and poudriere) also make use of Cirrus-CI.

Cirrus-CI configs received ongoing maintenance updates (moving to the most recent FreeBSD release images).
In the src tree we have added some additional checks.
These ensure that generated files are updated when needed (`make sysent` and `make makeman`) and check for missing directories.
We have added jobs that build using the Clang/LLVM 16 toolchain package, mirroring the Clang version now in the base system.
The GCC job is now run on the GitHub mirror by default, for all commits.

Sponsor: DARPA +
Sponsor: The FreeBSD Foundation
