=== Cluster Administration Team

Links: +
link:https://www.freebsd.org/administration/#t-clusteradm[Cluster Administration Team members] URL: link:https://www.freebsd.org/administration/#t-clusteradm[]

Contact: Cluster Administration Team <clusteradm@FreeBSD.org>

FreeBSD Cluster Administration Team members are responsible for managing the machines the Project relies on to synchronise its distributed work and communications.

In this quarter, the team has worked on the following:

* Regular support for FreeBSD.org user accounts.
* Regular disk and parts support (and replacement) for all physical hosts and mirrors.
* Enable mirroring of link:https://www.FreeBSD.org[] and link:https://docs.FreeBSD.org[] in the FreeBSD project-managed mirrors.
* Cluster refresh, upgrading all hosts and jails to the most recent versions of 14-CURRENT, 13-STABLE, and 12-STABLE.

==== Work in progress

* Large-scale network upgrade at our primary site.
** New link:https://www.juniper.net/[Juniper] switches arrived at our primary site to replace the former ones.
We thank Juniper for the donation.
* Replace old servers in our primary site and a few mirrors.
** Besides the broken CI servers, we have a few old servers with broken disks and faulty PSUs.
This task is in conjunction with The FreeBSD Foundation and donors/sponsors.
* Install new CI (Continuous Integration) machines repurposed from the package builders.
* Review the backup configuration of the services running in the FreeBSD cluster.

==== FreeBSD Official Mirrors Overview

Current locations are Australia, Brazil, Germany, Japan (two full mirror sites), Malaysia, South Africa, Taiwan, United Kingdom (full mirror site), United States of America -- California, New Jersey (primary site), and Washington.

The hardware and network connection have been generously provided by:

* https://www.bytemark.co.uk/[Bytemark Hosting]
* Cloud and SDN Laboratory at https://www.bbtower.co.jp/en/corporate/[BroadBand Tower, Inc]
* https://www.cs.nycu.edu.tw/[Department of Computer Science, National Yang Ming Chiao Tung University]
* https://deploy.equinix.com/[Equinix]
* https://internet.asn.au/[Internet Association of Australia]
* https://www.isc.org/[Internet Systems Consortium]
* https://www.inx.net.za/[INX-ZA]
* https://www.kddi-webcommunications.co.jp/english/[KDDI Web Communications Inc]
* https://www.mohe.gov.my/en/services/research/myren[Malaysian Research & Education Network]
* https://www.metapeer.com/[Metapeer]
* https://nic.br/[NIC.br]
* https://your.org/[Your.Org]
* https://365datacenters.com/[365 Data Centers]

The Frankfurt single server mirror is the primary Europe mirror in bandwidth and usage.

We are still looking for an additional full mirror site (five servers) in Europe to replace old servers in the United Kingdom full mirror site.

We see a good pattern in having single mirrors in Internet Exchange Points worldwide (Australia, Brazil, and South Africa); if you know or work for some of them that could sponsor a single mirror server, please get in touch.
United States (West Coast) and Europe (anywhere) are preferable places.

See link:https://wiki.freebsd.org/Teams/clusteradm/generic-mirror-layout[generic mirrored layout] for full mirror site specs and link:https://wiki.freebsd.org/Teams/clusteradm/tiny-mirror[tiny-mirror] for a single mirror site.
