=== FreeBSD Core Team

Contact: FreeBSD Core Team <core@FreeBSD.org>

The FreeBSD Core Team is the governing body of FreeBSD.

==== DevSummit 202305

The Core Team has presented the status update at the FreeBSD Developer Summit, 17th–18th May.
Slides are available at link:https://wiki.freebsd.org/DevSummit/202305[].

==== FreeBSD 14

The Core Team is working with other teams to ensure that FreeBSD 14.0-RELEASE will be of the highest quality.

The Core Team has no objection to mark riscv64sf (64-bit RISC-V soft-float) as https://www.freebsd.org/platforms/[unsupported in 14].

==== Meetings with The FreeBSD Foundation

The Core Team and The FreeBSD Foundation continue to meet regularly to discuss the next steps to take for the management, development, and future of FreeBSD.
The Core Team had two meetings with the Board of Directors of, and employees of, the Foundation.
They discussed how the Foundation can help the Core Team and the Project in general.

==== Matrix IM solution

One of the major items in the Core Team updates in DevSummit 202305 was proposing a new project communication solution.

There is currently a testing instance at matrix-dev.FreeBSD.org setup by clusteradm.
All developers can access the instance with their kerberos credentials, and some public rooms can be joined through Matrix's federation feature.
Please note this instance is for testing and evaluating so no backup or availability is guaranteed.

The Core Team is still discussing the scope and administration of this service, and collecting feedback from the community.

==== Code of Conduct Committee

Code of Conduct Committee (conduct@) is managed by the Core Team now.

==== Commit bits

Core approved the src commit bit for Christos Margiolis (christos@).
