=== KDE on FreeBSD

Links: +
link:https://freebsd.kde.org/[KDE FreeBSD] URL: link:https://freebsd.kde.org/[] +
link:https://community.kde.org/FreeBSD[KDE Community FreeBSD] URL:link:https://community.kde.org/FreeBSD[]

Contact: Adriaan de Groot <kde@FreeBSD.org>

The KDE on FreeBSD project packages CMake, Qt, and software from the KDE Community, for the FreeBSD ports tree.
The software includes a full desktop environment called KDE Plasma (for both X11 and Wayland) and hundreds of applications that can be used on any FreeBSD machine.

The KDE team (kde@) is part of desktop@ and x11@, building the software stack to make FreeBSD beautiful and usable as a daily-driver graphical desktop workstation.
The notes below describe *mostly* ports for KDE, but also include items that are important for the entire desktop stack.

==== Infrastructure

* Qt5 ports had various updates:
  * package:devel/qt5-webengine[] was repaired when building with Clang 16. This is preparation for the eventual release of FreeBSD 14.
* Qt6 ports had various updates:
  * package:devel/qt6-tools[] was repaired when building with Clang 16. This is preparation for the eventual release of FreeBSD 14.
* The package:accessibility/at-spi2-core[] port -- essential for accessible technologies on the desktop -- was updated to release 2.48.0.
* The package:devel/cmake-core[] port -- and the rest of the CMake ports and infrastructure -- was updated to release 3.26.1. This involved fixing a half-dozen consumers as well.
* The package:graphics/poppler[] port -- used by many PDF-viewers such as package:graphics/pdfgrep[] and package:graphics/okular[] -- was updated to release 23.04.
* The package::ports-mgmt/packagekit-qt[] port is a new addition to the tree to pave the way for graphical package managers on FreeBSD.


==== KDE Stack

KDE Gear releases happen every quarter, KDE Plasma updates once a month, and KDE Frameworks have a new release every month as well.
These (large) updates land shortly after their upstream release and are not listed separately.

* KDE Frameworks updated to 5.105.
* KDE Gear updated to 23.04.0.
* KDE Plasma Desktop was updated to version 5.27.4.


==== Related Ports

Deprecations:

* package:polish/kadu[], a chat application once popular in Poland, is deprecated and upstream has disappeared.
* package:sysutils/plasma5-ksysguard[], a system monitoring application, is deprecated upstream and will no longer update.

Updates:

* package:astro/kstars[], an interactive planetarium, was updated to release 3.6.4.
* package:devel/qtcreator[], an integrated development environment for Qt, C++, and more, was updated to release 10.0.0.
* package:games/gcompris-qt[], an education suite for children aged 3-12, was updated to release 3.2.
* package:graphics/kphotoalbum[], a photo album and display utility, was updated to release 5.10.0.
* package:net-im/tokodon[], a Mastodon social network client, joins KDE Gear. 
* package:textproc/kdiff3[], a text-differencing utility, was updated to release 1.10.1.

New Software:

* package:multimedia/kasts[] is a new podcast-listening and enjoyment application from the KDE community.
* package:textproc/arianna[] is a mobile-oriented e-book reader from the KDE community that makes reading FreeBSD documentation a joy.
