# $FreeBSD$

# The FreeBSD French Documentation Project
# Original revision: 1.9

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   index.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
