# $FreeBSD$

#
# The FreeBSD Hungarian Documentation Project
#

MAINTAINER=	gabor@FreeBSD.org

SUBDIR=		dialup-firewall	
SUBDIR+=	explaining-bsd
SUBDIR+=	laptop
SUBDIR+=	linux-comparison
SUBDIR+=	multi-os
SUBDIR+=	version-guide

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
