# $FreeBSD$

#
# The FreeBSD Hungarian Documentation Project
# %SOURCE%    en_US.ISO8859-1/articles/Makefile
# %SRCID%     1.61
#

MAINTAINER=	gabor@FreeBSD.org

SUBDIR+=	cups
SUBDIR+=	explaining-bsd
SUBDIR+=	gjournal-desktop
SUBDIR+=	linux-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
