# $FreeBSD$

#
# The FreeBSD Hungarian Documentation Project
#

MAINTAINER=	gabor@FreeBSD.org

SUBDIR= explaining-bsd
SUBDIR+= linux-comparison

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
