#
#    The FreeBSD Hungarian Documentation Project
#    %SOURCE%    en_US.ISO8859-1/articles/Makefile.inc
#    %SRCID%     1.4
#
#    $FreeBSD$
#

DESTDIR?=	${DOCDIR}/hu_HU.ISO8859-2/articles/${.CURDIR:T}
