# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/handbook/Makefile,v 1.2 2000/11/10 17:04:49 phantom Exp $

# This is home born version of Makefile. It will be remove then real handbook
# will be imported.

.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS = index.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
