---
description: '이 장에서는 그래픽 사용자 환경을 제공하는 FreeBSD에 wayland와 컴포지터를 설치하고 구성하는 방법을 설명합니다'
next: books/handbook/partii
part: '파트 I. 시작하기'
path: /books/handbook/
prev: books/handbook/x11
showBookMenu: 'true'
tags: ["Wayland", "XWayland", "KDE", "Plasma", "Xfce", "Gnome", "Intel", "AMD", "NVIDIA", "Wayfire", "Sway", "Hikari"]
title: '6장. Wayland'
weight: 8
---

[[wayland]]
= FreeBSD의 wayland
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 6
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/wayland/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[wayland-synopsis]]
== Wayland 시놉시스
Wayland는 새로운 디스플레이 서버이지만, 몇 가지 중요한 점에서 Xorg와 다릅니다. 첫째, Wayland는 X 서버에 대한 의존성을 제거하는 다른 메커니즘을 사용하여 클라이언트 간의 중개자 역할을 하는 프로토콜일 뿐입니다. Xorg에는 원격 디스플레이를 실행하는 데 사용되는 X11 프로토콜이 모두 포함되어 있으며, X 서버는 연결과 디스플레이 창을 수락합니다. Wayland에서는 컴포저 또는 창 관리자가 기존 X 서버 대신 디스플레이 서버를 제공합니다.

Wayland는 X 서버가 아니므로 기존 X 화면 연결은 원격 데스크톱 관리를 위해 VNC 또는 RDP와 같은 다른 방법을 활용해야 합니다. 둘째, Wayland는 X 프로토콜을 지원할 필요가 없는 별도의 엔티티로서 클라이언트와 컴포지터 간의 컴포지트 통신을 관리할 수 있습니다.

Wayland는 비교적 새롭고, 모든 소프트웨어가 `Xwayland` 지원 없이 실행되도록 업데이트된 것은 아닙니다. Wayland는 X 서버를 제공하지 않으며 컴포저가 해당 지원을 제공할 것으로 예상하기 때문에, 아직 Wayland를 지원하지 않는 X11 윈도우 관리자는 `-rootless` 매개 변수를 사용하여 `Xwayland`를 시작하지 않아야 합니다. `-rootless` 매개 변수를 제거하면 X11 창 관리자 지원이 복원됩니다.

[NOTE]
====
현재 NVidia 드라이버는 대부분의 wl-roots 컴포지터에서 작동해야 하지만 현재로서는 약간 불안정하고 모든 기능을 지원하지 않을 수 있습니다. NVidia DRM 작업을 도와줄 자원자가 필요합니다.
====

현재 Firefox를 포함한 많은 소프트웨어가 wayland에서 최소한의 문제만 일으키며 작동합니다. 또한 Wayfire로 알려진 Compiz Fusion 대체품과 i3 창 관리자 대체품인 Sway와 같은 몇 가지 데스크톱도 사용할 수 있습니다.

[NOTE]
====
2021년 5월 현재, plasma5-kwin은 FreeBSD의 Wayland를 지원합니다. Wayland에서 플라즈마를 사용하려면, `startplasma-wayland` 매개변수를 `ck-launch-session`에 사용하고 dbus에 연결하세요: `ck-launch-session dbus-run-session startplasma-wayland`로 연결하면 작동합니다.
====

컴포지터의 경우, 키 바인딩 기능을 활용하려면 man:evdev[4] 드라이버를 지원하는 커널이 존재해야 합니다. 이 기능은 기본적으로 [.filename]#GENERIC# 커널에 내장되어 있지만, 커스터마이징을 통해 man:evdev[4] 지원이 제거된 경우 man:evdev[4] 모듈을 로드해야 합니다. 또한 `Wayland` 사용자는 `video` 그룹의 구성원이어야 합니다. 이 변경을 빠르게 수행하려면 `pw` 명령을 사용합니다:

[source, shell]
----
pw groupmod video -m user
----

Wayland 설치는 간단합니다. 프로토콜 자체에 대한 구성이 많지 않습니다. 대부분의 구성은 선택한 컴포지터에 따라 달라집니다. 지금 'seatd'를 설치하면 특정 장치에 비루트 액세스를 제공하기 위해 'seatd'가 필요하므로 컴포저 설치 및 구성 단계를 건너뛸 수 있습니다.

여기에 설명된 모든 컴포지터는 package:graphics/drm-kmod[] 오픈 소스 드라이버와 함께 작동해야 하지만, NVidia 그래픽 카드의 경우 독점 드라이버를 사용할 때 문제가 발생할 수 있습니다. 다음 패키지를 설치하여 시작하세요:

[source, shell]
----
# pkg install wayland seatd
----

프로토콜과 지원 패키지가 설치되면 컴포지터가 사용자 인터페이스를 생성해야 합니다. 다음 섹션에서는 몇 가지 컴포지터를 다룰 것입니다. Wayland를 사용하는 모든 컴포지터는 환경에 정의된 런타임 디렉터리가 필요하며, 이는 bourne 셸에서 다음 명령으로 구현할 수 있습니다:

[source, shell]
----
% export XDG_RUNTIME_DIR=/var/run/user/`id -u`
----

대부분의 컴포지터는 XDG_RUNTIME_DIR 디렉터리에서 설정 파일을 검색한다는 점에 유의해야 합니다. 여기에 포함된 예제에서는 임시 파일과 구성 파일을 분리하기 위해 [.filename]#~/.config#에 구성 파일을 지정하는 파라미터를 사용합니다. 각 컴포지터가 지정된 구성 파일을 로드하도록 별칭을 구성하는 것이 좋습니다.

[WARNING]
====
ZFS 사용자는 런타임 디렉터리에서 `posix_fallocate()`에 액세스해야 하기 때문에 일부 Wayland 클라이언트에서 문제가 발생할 수 있다는 보고가 있었습니다. 작성자가 ZFS 시스템에서 이 문제를 재현할 수는 없었지만, 권장되는 해결 방법은 런타임 디렉터리에 ZFS를 사용하지 않고 대신 [.filename]#/var/run# 디렉터리에 `tmpfs`를 사용하는 것입니다. 이 경우, `tmpfs` 파일 시스템을 [.filename]#/var/run#에 사용하고 `mount -t tmpfs tmpfs /var/run` 명령을 통해 마운트한 다음, 재부팅 시에도 이 변경 사항이 [.filename]#/etc/fstab#을 통해 지속되도록 합니다. XDG_RUNTIME_DIR 환경 변수를 [.filename]#/var/run/user/$UID#를 사용하도록 구성하여 ZFS의 잠재적인 함정을 피할 수 있습니다. 다음 섹션의 구성 예제를 검토할 때 이 시나리오를 고려하세요.
====

seatd 데몬은 컴포지터에서 루트가 아닌 사용자의 공유 시스템 장치에 대한 액세스를 관리하는 데 도움이 되며, 여기에는 그래픽 카드가 포함됩니다. Plasma나 GNOME과 같은 기존 X11 관리자의 경우 `seatd`가 필요하지 않지만, 여기서 설명하는 Wayland 컴포지터의 경우 컴포지터 환경을 시작하기 전에 시스템에서 활성화하고 실행 중이어야 합니다. 바로 시스템 초기화 시 `seatd` 데몬을 활성화하고 시작하려면 다음과 같이 하세요:

[source, shell]
----
# sysrc seatd_enable=”YES”
# service seatd start
----

그 후에는 X11 데스크톱과 유사한 컴포지터를 설치해야 GUI 환경을 사용할 수 있습니다. 여기에서는 기본 구성 옵션, 화면 잠금 설정, 추가 정보에 대한 권장 사항 등 세 가지에 대해 설명합니다.

[[wayland-wayfire]]
== Wayfire 컴포지터

Wayfire는 가볍고 사용자 정의가 가능한 컴포지터를 지향합니다. 여러 가지 기능을 사용할 수 있으며 이전에 출시된 Compiz Fusion 데스크톱의 여러 요소를 재사용합니다. 모든 부분이 최신 하드웨어에서 아름답게 보입니다. Wayfire를 시작하고 실행하려면 필요한 패키지를 설치하는 것으로 시작하세요:

[source, shell]
----
# pkg install wayfire wf-shell alacritty swaylock-effects swayidle wlogout kanshi mako wlsunset
----

`Alacritty` 패키지는 터미널 에뮬레이터를 제공합니다. 하지만 `kitty`와 같은 다른 터미널 에뮬레이터와 XFCE-4 `Terminal`이 Wayfire 컴포지터에서 작동하는 것으로 테스트 및 검증되었기 때문에 반드시 필요한 것은 아닙니다. Wayfire 구성은 비교적 간단하며, 커스터마이징을 위해 검토해야 하는 파일을 사용합니다. 시작하려면 예제 파일을 런타임 환경 구성 디렉터리에 복사한 다음 파일을 편집합니다:

[source, shell]
----
% mkdir ~/.config/wayfire
% cp /usr/local/share/examples/wayfire/wayfire.ini ~/.config/wayfire
----

대부분의 사용자에게는 기본값으로 충분합니다. 구성 파일에는 유명한 `cube`와 같은 항목이 미리 구성되어 있으며, 사용 가능한 설정에 도움이 되는 지침이 있습니다. 몇 가지 주요 설정은 다음과 같습니다:

[.programlisting]
....
[output]
mode = 1920x1080@60000
position = 0,0
transform = normal
scale = 1.000000
....

이 예제에서는 구성 파일에서 화면 출력의 주파수는 나열된 모드중 하나가 되어야 합니다. 예를 들어, 모드는 `widthxheight@refresh_rate`로 설정해야 합니다. 위치는 지정된 특정 픽셀 위치에 출력을 배치합니다. 대부분의 사용자에게는 기본값이 적합할 것입니다. 마지막으로 트랜스폼은 배경 트랜스폼을 설정하고 스케일은 지정된 배율로 출력의 배율을 조정합니다. 이러한 옵션의 기본값이 적당하며 자세한 내용은 설명서를 참조하세요.

앞서 언급했듯이 Wayland는 새로운 프로토콜이며 아직 모든 애플리케이션이 이 프로토콜에서 작동하는 것은 아닙니다. 현재 `sddm`은 Wayland에서 컴포지터 시작 및 관리를 지원하지 않는 것으로 보입니다. 이 예제에서는 `swaylock` 유틸리티를 대신 사용했습니다. 구성 파일에는 화면 유휴 상태 및 잠금을 위해 `swayidle` 및 `swaylock`을 실행하는 옵션이 포함되어 있습니다.

시스템이 유휴 상태일 때 수행할 작업을 정의하는 이 옵션은 다음과 같이 나열됩니다:

[.programlisting]
....
idle = swaylock
....

잠금 시간 제한은 다음 줄을 사용하여 구성합니다:

[.programlisting]
....
[idle]
toggle = <super> KEY_Z
screensaver_timeout = 300
dpms_timeout = 600
....

첫 번째 옵션은 300초 후에 화면을 잠그고, 300초가 더 지나면 'dpms_timeout' 옵션을 통해 화면이 꺼집니다.

마지막으로 주목해야 할 것은 <super> 키입니다. 대부분의 설정에서 이 키를 언급하고 있으며, 이 키는 키보드의 전통적인 `Windows` 키입니다. 대부분의 키보드에서 이 슈퍼 키를 사용할 수 있지만, 사용할 수 없는 경우 이 구성 파일 내에서 다시 매핑해야 합니다. 예를 들어, 화면을 잠그려면 슈퍼 키인 kbd:[shift] 키를 길게 누른 상태에서 kbd:[escape] 키를 누릅니다. 매핑이 변경되지 않는 한, 이렇게 하면 swaylock 애플리케이션이 실행됩니다. 'swaylock'의 기본 구성은 회색 화면으로 표시되지만, 이 애플리케이션은 사용자 정의가 가능하고 문서화되어 있습니다. 또한, 설치된 버전에 따라 다음 명령을 사용하여 확인할 수 있는 흐림 효과와 같은 몇 가지 옵션을 사용할 수 있습니다:

[source, shell]
----
% swaylock --effect-blur 7x5
----

잠금 화면에 날짜와 시간이 표시된 시계를 표시하는 `--clock` 매개변수도 있습니다. package:x11/swaylock-effects[]를 설치할 때 기본 [.filename]#pam.d# 구성이 포함되어 있습니다. 대부분의 사용자에게 적합한 기본 옵션을 제공합니다. 더 고급 옵션을 사용할 수 있으며 자세한 내용은 PAM 설명서를 참조하세요.

이제 Wayfire를 테스트하고 시스템에서 시작할 수 있는지 확인할 차례입니다. 다음 명령을 입력하기만 하면 됩니다:

[source, shell]
----
% wayfire -c ~/.config/wayfire/wayfire.ini
----

이제 컴포지터가 시작되고 화면 상단에 메뉴 모음과 함께 배경 이미지가 표시됩니다. Wayfire는 데스크톱에 설치된 호환 가능한 애플리케이션을 나열하여 이 드롭다운 메뉴에 표시하려고 시도합니다(예: XFCE-4 파일 관리자가 설치된 경우 이 드롭다운 메뉴에 표시됨). 특정 애플리케이션이 키보드 단축키와 호환되고 충분히 가치 있는 경우, [.filename]#wayfire.ini# 구성 파일을 사용하여 키보드 시퀀스에 매핑할 수 있습니다. Wayfire에는 Wayfire Config Manager라는 구성 도구도 있습니다. 이 도구는 드롭다운 메뉴 모음에 있지만 터미널을 통해 다음 명령을 실행하여 시작할 수도 있습니다:

[source, shell]
----
% wcm
----

합성 특수 효과를 포함한 다양한 Wayfire 구성 옵션은 이 애플리케이션을 통해 활성화, 비활성화 또는 구성할 수 있습니다. 또한 보다 사용자 친화적인 환경을 위해 구성 파일에서 백그라운드 관리자, 패널 및 도킹 애플리케이션을 활성화할 수 있습니다:

[.programlisting]
....
panel = wf-panel
dock = wf-dock
background = wf-background
....

[WARNING]
====
`wcm`을 통해 변경한 내용은 [.filename]#wayfire.ini# 구성 파일을 덮어씁니다. 필수 변경 사항을 복원할 수 있도록 [.filename]#wayfire.ini# 파일을 백업하는 것을 적극 권장합니다.
====

마지막으로 [.filename]#wayfire.ini#에 나열된 기본 런처는 package:x11/wf-shell[]이며, 사용자가 원하는 경우 다른 패널로 대체할 수 있습니다.

[[wayland-hikari]]
== Hikari 컴포지터

Hikari 컴포지터는 시트, 작업 공간 등 생산성을 중심으로 한 몇 가지 개념을 사용합니다. 그런 면에서 타일링 창 관리자와 비슷합니다. 이를 세분화하면 컴포지터는 가상 데스크톱과 유사한 단일 작업 공간에서 시작됩니다. Hikari는 사용자 상호 작용을 위해 단일 작업 공간 또는 가상 데스크톱을 사용합니다. 작업 공간은 시트 또는 그룹으로 그룹화된 컴포지터의 다양한 뷰로 구성됩니다. 시트와 그룹은 모두 보기 모음으로 구성되며, 다시 한 번 그룹화된 창으로 구성됩니다. 시트 또는 그룹 간에 전환할 때 활성 시트 또는 그룹을 통칭하여 작업 공간으로 표시됩니다. 설명서 페이지에서 각 기능에 대해 자세히 설명하지만 이 문서에서는 단일 시트를 사용하는 단일 작업 공간을 고려하십시오. Hikari 설치는 단일 패키지인 package:x11-wm/hikari[] 및 터미널 에뮬레이터 `alacritty`로 구성됩니다:

[source, shell]
----
# pkg install hikari alacritty
----

[NOTE]
====
`kitty`나 Plasma의 `Terminal`과 같은 다른 셸은 wayland에서 작동합니다. 사용자는 선호하는 터미널 편집기로 실험하여 호환성을 확인해야 합니다.
====

Hikari는 구성 파일인 [.filename]#hikari.conf#을 사용하는데, 이 파일은 XDG_RUNTIME_DIR에 위치하거나 시작 시 `-c` 파라미터를 사용하여 지정할 수 있습니다. 자동 시작 구성 파일은 필수는 아니지만 이 컴포지터로의 마이그레이션을 조금 더 쉽게 할 수 있습니다. 구성의 시작은 Hikari 구성 디렉터리를 생성하고 편집할 구성 파일을 복사하는 것입니다:

[source, shell]
----
% mkdir ~/.config/hikari
% cp /usr/local/etc/hikari/hikari.conf ~/.config/hikari
----

구성은 UI, 출력, 레이아웃 등과 같은 다양한 스탠자로 나뉩니다. 대부분의 사용자에게는 기본값이 잘 작동하지만 몇 가지 중요한 변경이 필요합니다. 예를 들어, $TERMINAL 변수는 일반적으로 사용자 환경 내에서 설정되지 않습니다. 이 변수를 변경하거나 [.filename]#hikari.conf# 파일을 읽을 수 있도록 변경하세요:

[.programlisting]
....
terminal = "/usr/local/bin/alacritty"
....

바인딩된 키 누름을 사용하여 `alacritty` 터미널을 실행합니다. 구성 파일을 살펴보는 동안 대문자가 사용자를 위해 키를 매핑하는 데 사용된다는 점에 유의해야 합니다. 예를 들어, 터미널을 시작하기 위한 kbd:[L] 키는 실제로는 앞서 설명한 슈퍼 키 또는 Windows 로고 키입니다. 따라서 kbd:[L/super/Windows] 키를 누른 상태에서 kbd:[Enter]를 누르면 기본 구성으로 지정된 터미널 에뮬레이터가 열립니다. 다른 키를 애플리케이션에 매핑하려면 동작 정의를 생성해야 합니다. 이를 위해 작업 항목은 예를 들어 작업 스탠자에 나열되어야 합니다:

[.programlisting]
....
actions {
  terminal = "/usr/local/bin/alacritty"
  browser = "/usr/local/bin/firefox"
}
....

그런 다음 바인딩 스탠자 내에 정의된 키보드 스탠자 아래에 액션을 매핑할 수 있습니다:

[.programlisting]
....
bindings {
  keyboard {
SNIP
    "L+Return" = action-terminal
    "L+b" = action-browser
SNIP
....

Hikari가 재시작된 후 Windows 로고 버튼을 누른 상태에서 키보드의 kbd:[b] 키를 누르면 웹 브라우저가 시작됩니다. 컴포저에는 메뉴 표시줄이 없으므로 마이그레이션하기 전에 터미널 에뮬레이터를 최소한으로 설정하는 것이 좋습니다. 설명서 페이지에는 전체 마이그레이션을 수행하기 전에 읽어야 할 많은 문서가 포함되어 있습니다. Hikari의 또 다른 긍정적인 측면은 컴포지터로 마이그레이션하는 동안 Plasma 및 GNOME 데스크톱 환경에서 Hikari를 시작할 수 있어 완전히 마이그레이션하기 전에 테스트할 수 있다는 점입니다.

Hikari에서 화면을 잠그는 것은 기본 [.filename]#pam.d# 구성 파일과 잠금 해제 유틸리티가 패키지에 번들로 제공되므로
쉽습니다.  화면 잠금을 위한 키 바인딩은 kbd:[L](Windows 로고 키)+ kbd:[Shift] +
kbd:[Backspace]입니다.  공개로 표시되지 않은 모든 보기는 숨겨집니다.  이러한 보기는 잠긴 상태에서는 입력을 허용하지
않으므로 민감한 정보가 표시되지 않도록 주의하세요.  일부 사용자의 경우 이 섹션에서 설명하는 swaylock-effects와 같은 다른
화면 잠금 유틸리티로 마이그레이션하는 것이 더 쉬울 수 있습니다.  Hikari를 시작하려면 다음 명령을 사용합니다:

[source, shell]
----
% hikari -c ~/.config/hikari/hikari.conf
----

[[wayland-sway]]
== Sway 컴포지터

Sway 컴포지터는 i3 윈도우 매니저를 대체하려는 타일 형태의 컴포지터입니다. 사용자의 현재 i3 구성과 함께 작동해야 하지만 새로운 기능을 사용하려면 몇 가지 추가 설정이 필요할 수 있습니다. 다음 예제에서는 i3 구성을 마이그레이션하지 않고 새로 설치하는 것으로 가정합니다. Sway 및 주요 구성 요소를 설치하려면 루트 사용자로 다음 명령을 실행합니다:

[source, shell]
----
# pkg install sway swayidle swaylock-effects alacritty dmenu-wayland dmenu
----

기본 구성 파일의 경우 다음 명령을 실행한 다음 구성 파일을 복사한 후 편집합니다:

[source, shell]
----
% mkdir ~/.config/sway
% cp /usr/local/etc/sway/config ~/.config/sway
----

기본 구성 파일에는 대부분의 사용자에게 적합한 기본값이 많이 포함되어 있습니다. 다음과 같이 몇 가지 중요한 사항을 변경해야 합니다:

[.programlisting]
....
# Logo key. Use Mod1 for Alt.
input * xkb_rules evdev
set $mod Mod4
# Your preferred terminal emulator
set $term alacritty
set $lock swaylock -f -c 000000
output "My Workstation" mode 1366x786@60Hz position 1366 0
output * bg ~/wallpapers/mywallpaper.png stretch
### Idle configuration
exec swayidle -w \
          timeout 300 'swaylock -f -c 000000' \
          timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
          before-sleep 'swaylock -f -c 000000'
....

이전 예제에서는 man:evdev[4] 이벤트에 대한 `xkb` 규칙이 로드되고 $mod 키가 키 바인딩을 위해 Windows 로고 키로 설정되었습니다. 다음으로 터미널 에뮬레이터를 `alacritty`로 설정하고 화면 잠금 명령을 정의했습니다(이에 대해서는 나중에 자세히 설명합니다). 출력 키워드, 모드, 위치, 배경 배경화면, 그리고 이 배경화면을 늘려서 화면을 채우도록 Sway도 지정했습니다. 마지막으로 `swaylock`은 300초의 시간 초과 후 화면을 데몬화하여 잠그고 600초 후에 화면 또는 모니터를 절전 모드로 전환하도록 설정했습니다. 잠긴 배경색인 000000(검은색)도 여기에서 정의됩니다. swaylock-effects를 사용하면 `--clock` 매개변수를 사용하여 시계를 표시할 수도 있습니다. 더 많은 옵션은 매뉴얼 페이지를 참조하세요. 사용 가능한 출력 옵션 사용자 지정에 대한 많은 정보가 포함된 man:sway-output[5] 매뉴얼 페이지도 검토해야 합니다.

Sway에서 애플리케이션 메뉴를 불러오려면 Windows 로고 키(mod)를 누른 상태에서 kbd:[d] 키를 누릅니다. 메뉴는 키보드의 화살표 키를 사용하여 탐색할 수 있습니다. 바의 레이아웃을 조작하고 트레이를 추가하는 방법도 있습니다. 자세한 내용은 man:sway-bar[5] 매뉴얼 페이지를 참조하세요. 기본 구성은 오른쪽 상단에 날짜와 시간을 추가합니다. 예제는 구성 파일의 `Bar` 스탠자를 참조하세요. 기본적으로 구성에는 위의 예시 외에 화면 잠그기, 잠금 타이머 활성화가 포함되지 않습니다. 잠금 키 바인딩을 생성하려면 `Key bindings` 섹션에 다음 줄을 추가해야 합니다:

[.programlising]
....
# Lock the screen manually
bindsym $mod+Shift+Return exec $lock
....

이제 Windows 로고 키를 누른 상태에서 Shift 키를 길게 누른 다음 마지막으로 Return 키를 누르는 조합으로 화면을 잠글 수 있습니다. 패키지로 설치하든 FreeBSD 포트 컬렉션으로 설치하든, Sway가 설치되면 [.filename]#pam.d#의 기본 파일이 설치됩니다. 기본 구성은 대부분의 사용자에게 적합하지만 고급 옵션을 사용할 수 있습니다. 자세한 내용은 PAM 설명서를 읽어보세요.

마지막으로 Sway를 종료하고 셸로 돌아가려면 Windows 로고 키와 Shift 키를 누른 상태에서 kbd:[e] 키를 누릅니다. Sway를 종료할 수 있는 항목이 있는 프롬프트가 표시됩니다. 마이그레이션하는 동안 Plasma와 같은 X11 데스크톱의 터미널 에뮬레이터를 통해 Sway를 시작할 수 있습니다. 이렇게 하면 이 컴포지터로 완전히 마이그레이션하기 전에 다양한 변경 사항과 키 바인딩을 좀 더 쉽게 테스트할 수 있습니다. Sway를 시작하려면 다음 명령을 실행합니다:

[source, shell]
----
% sway -c ~/.config/sway/config
----

[[wayland-xwayland]]
== Xwayland 사용하기

Wayland를 설치할 때, X11을 지원하지 않는 Wayland를 빌드한 경우가 아니라면 `Xwayland` 바이너리가 설치되어 있어야 합니다. [.filename]#/usr/local/bin/Xwayland# 파일이 존재하지 않는 경우 다음 명령을 사용하여 설치하세요:

[source, shell]
----
# pkg install xwayland-devel
----

[NOTE]
====
Xwayland의 개발 버전이 권장되며 Wayland 패키지와 함께 설치되었을 가능성이 높습니다. 각 컴포지터에는 이 기능을 활성화 또는 비활성화하는 방법이 있습니다.
====

`Xwayland`가 설치되면 선택한 컴포지터 내에서 구성합니다. Wayfire의 경우 [.filename]#wayfire.ini# 파일에 다음 줄이 필요합니다:

[.programlisting]
....
xwayland = true
....

Sway 컴포지터의 경우 기본적으로 `Xwayland`가 활성화되어 있어야 합니다. 그렇더라도 다음과 같이 [.filename]#~/.config/sway/config#에 구성 줄을 수동으로 추가하는 것을 권장합니다:

[.programlisting]
.....
xwayland enable
.....

마지막으로 Hikari의 경우 변경이 필요하지 않습니다. `Xwayland`에 대한 지원은 기본적으로 빌드되어 있습니다. 해당 지원을 비활성화하려면 포트 컬렉션에서 패키지를 다시 빌드하고 이때 Xwayland 지원을 비활성화합니다.

이러한 변경이 완료되면 명령줄에서 컴포지터를 시작하고 키 바인딩에서 터미널을 실행합니다. 이 터미널에서 `env` 명령을 실행하고 `DISPLAY` 변수를 검색합니다. 컴포지터가 Xwayland X 서버를 정상적으로 시작할 수 있었다면, 환경 변수는 다음과 유사하게 보일 것입니다:

[source, shell]
----
% env | grep DISPLAY
----

[.programlisting]
....
WAYLAND_DISPLAY=wayland-1
DISPLAY=:0
....

이 출력에는 기본 wayland 디스플레이와 Xwayland 서버용 디스플레이가 설정되어 있습니다. `Xwayland`가 제대로 작동하는지 확인하는 또 다른 방법은 작은 package:[x11/eyes]를 설치 및 테스트하고 출력을 확인하는 것입니다. `xeyes` 애플리케이션이 시작되고 마우스 포인터를 따라 눈이 움직인다면 Xwayland가 정상적으로 작동하는 것입니다. 아래와 같은 에러가 표시된다면 `Xwayland` 초기화 과정에서 문제가 발생한 것이며 재설치가 필요할 수 있습니다:

[.programlisting]
....
Error: Cannot open display wayland-0
....

[WARNING]
====
Wayland의 보안상 특징은 X 서버를 실행하지 않으면 다른 네트워크 리스너가 없다는 것입니다.`Xwayland`가 활성화되면 이 보안 기능은 더 이상 시스템에 적용되지 않습니다.
====

Wayfire와 같은 일부 컴포지터의 경우, `Xwayland`가 제대로 시작되지 않을 수 있습니다. 따라서 `env`는 `DISPLAY` 환경 변수에 대해 다음과 같은 정보를 표시합니다:

[source, shell]
----
% env | grep DISPLAY
----

[.programlisting]
....
DISPLAY=wayland-1
WAYLAND_DISPLAY=wayland-1
....

`Xwayfire`가 설치 및 구성되었음에도 불구하고 X11 응용 프로그램에서 디스플레이 문제를 알리지 않습니다. 이 문제를 해결하려면 다음 두 가지 방법을 통해 UNIX 소켓을 사용하는 `Xwayland` 인스턴스가 이미 있는지 확인합니다. 먼저 `sockstat`의 출력을 확인하여 X11-unix를 검색합니다:

[source, shell]
----
% sockstat | grep x11
----

다음 정보와 비슷한 내용이 있어야 합니다:

[.programlisting]
....
trhodes  Xwayland   2734  8  stream /tmp/.X11-unix/X0
trhodes  Xwayland   2734  9  stream /tmp/.X11-unix/X0
trhodes  Xwayland   2734  10 stream /tmp/.X11-unix/X0
trhodes  Xwayland   2734  27 stream /tmp/.X11-unix/X0_
trhodes  Xwayland   2734  28 stream /tmp/.X11-unix/X0
....

이것은 X11 소켓의 존재를 암시합니다. 컴포지터에서 실행 중인 터미널 에뮬레이터에서 `Xwayland`를 수동으로 실행해 보면 이를 추가로 확인할 수 있습니다:

[source, shell]
----
% Xwayland
----

X11 소켓을 이미 사용할 수 있는 경우 사용자에게 다음 오류가 표시되어야 합니다:

[.programlisting]
....
(EE)
Fatal server error:
(EE) Server is already active for display 0
	If this server is no longer running, remove /tmp/.X0-lock
	and start again.
(EE)
....

디스플레이 0을 사용하여 사용할 수 있는 활성화된 X 디스플레이가 있으므로, 환경 변수가 잘못 설정된 것으로 판단할 수 있습니다. 이 문제를 해결하려면 `DISPLAY` 환경 변수를 `:0`으로 변경하고 애플리케이션을 다시 실행해 보시기 바랍니다. 다음 예제는 `Xwayland` 서비스가 필요한 애플리케이션으로 package:mail/claws-mail[]을 사용합니다:

[source, shell]
----
export DISPLAY=:0
----

변경 후 package:mail/claws-mail[] 애플리케이션은 이제 `Xwayland`를 사용하기 시작하고 예상대로 작동합니다.

[[wayland-remotedesktop]]
== VNC를 사용한 원격 데스크톱

이 문서의 앞부분에서 Wayland는 Xorg가 제공하는 것과 동일한 X 서버 스타일의 액세스를 제공하지 않는다고 언급했습니다. 대신, 사용자는 RDP나 VNC와 같은 원격 데스크톱 프로토콜을 자유롭게 선택할 수 있습니다. FreeBSD 포트 컬렉션에는 여기서 설명한 것과 같은 wlroots 기반 컴포지터를 지원하는 `wayvnc`가 포함되어 있습니다. 이 애플리케이션은 다음을 사용하여 설치할 수 있습니다:

[source, shell]
----
# pkg install wayvnc
----

다른 패키지와 달리 `wayvnc`에는 구성 파일이 제공되지 않습니다. 다행히도 설명서 페이지에 중요한 옵션이 문서화되어 있으며 간단한 구성 파일로 추정할 수 있습니다:

[.programlisting]
....
address=0.0.0.0
enable_auth=true
username=username
password=password
private_key_file=/path/to/key.pem
certificate_file=/path/to/cert.pem
....

키 파일을 생성해야 하며, 연결 보안을 강화하기 위해 키 파일을 사용하는 것이 좋습니다. 이 함수가 호출되면 wayvnc는 [.filename]#~/.config/wayvnc/config#에서 구성 파일을 검색합니다. 서버를 시작할 때 `-C configuration_file` 옵션을 사용하여 이 파일을 덮어쓸 수 있습니다. 따라서 `wayvnc` 서버를 시작하려면 다음 명령을 실행합니다:

[source, shell]
----
% wayvnc -C ~/.config/wayvnc/config
----

[NOTE]
====
이 글을 쓰는 시점에는 시스템 초기화 시 `wayvnc`를 시작하는 rc.d 스크립트가 없습니다. 이 기능을 원한다면 로컬 시작 파일을 만들어야 합니다. 이는 아마도 포트 관리자에게 기능 요청이 필요할 것입니다.
====

[[wayland-ly]]
== Wayland 로그인 관리자
여러 로그인 관리자가 존재하며 서서히 Wayland로 마이그레이션되고 있지만, 한 가지 옵션은 package:x11/ly[] 텍스트 사용자 인터페이스(TUI) 관리자입니다. 최소한의 구성이 필요한 `ly`는 시스템 초기화 시 로그인 창을 표시하여 Sway, Wayfire 등을 시작합니다. `ly`를 설치하려면 다음 명령을 실행합니다:

[source, shell]
----
# pkg install ly
----

몇 가지 구성 힌트가 표시되며, 가져오기 단계는 [.filename]#/etc/gettytab#에 다음 줄을 추가하는 것입니다:

[programlisting]
....
Ly:\
  :lo=/usr/local/bin/ly:\
  :al=root:
....

그런 다음 [.filename]#/etc/ttys#의 ttyv1 줄을 다음과 일치하도록 수정합니다:

[programlisting]
....
ttyv1 "/usr/libexec/getty Ly" xterm onifexists secure
....

시스템을 재부팅하면 로그인 화면이 나타납니다. 언어와 같은 특정 설정을 구성하고 [.filename]#/usr/local/etc/ly/config.ini#를 편집하려면 다음과 같이 하세요. 최소한 이 파일에는 이전에 [.filename]#/etc/ttys#에 지정한 tty가 있어야 합니다.

[NOTE]
====
ttyv0를 로그인 터미널로 설정한 경우, 로그인 창이 제대로 표시되려면 kbd:[alt] 및 kbd:[F1] 키를 눌러야 할 수 있습니다.
====

로그인 창이 나타나면 왼쪽 및 오른쪽 화살표를 사용하여 지원되는 다른 창 관리자로 전환할 수 있습니다.

[[wayland-utilities]]
== 유용한 유틸리티

모든 컴포지터가 사용할 수 있는 유용한 wayland 유틸리티 중 하나는 waybar입니다. Wayfire에는 시작 메뉴가 제공되지만, 사용하기 쉽고 빠른 작업 표시줄은 모든 컴포지터 또는 데스크톱 관리자에게 좋은 액세서리입니다. 빠르고 쉽게 구성할 수 있는 wayland 호환 작업 표시줄은 waybar입니다. 패키지와 지원 오디오 제어 유틸리티를 설치하려면 다음 명령을 실행합니다:

[source, shell]
----
# pkg install pavucontrol waybar
----

구성 디렉터리를 만들고 기본 구성 파일을 복사하려면 다음 명령을 실행합니다:

[source, shell]
----
% mkdir ~/.config/waybar
% cp /usr/local/etc/xdg/waybar/config ~/.config/waybar
----

`lavalauncher` 유틸리티는 다양한 애플리케이션을 위한 시작 표시줄을 제공합니다. 패키지와 함께 제공되는 예제 구성 파일은 없으므로 다음 작업을 수행해야 합니다:

[source, shell]
----
mkdir ~/.config/lavalauncher
----

오른쪽에 Firefox만 포함된 구성 파일의 예는 다음과 같습니다:

[.programlising]
....
global-settings {
	watch-config-file = true;
}

bar {
	output            = eDP-1;
	position          = bottom;
	background-colour = "#202020";

	# Condition for the default configuration set.
	condition-resolution = wider-than-high;

	config {
		position = right;
	}

	button {
		image-path          =     /usr/local/lib/firefox/browser/chrome/icons/default/default48.png;
		command[mouse-left] =     /usr/local/bin/firefox;
	}
	button {
	  image-path           =   /usr/local/share/pixmaps/thunderbird.png;
	  command[mouse-left]  =   /usr/local/bin/thunderbird;
}
....
