---
title: "FreeBSD 13.2-RELEASE Errata"
sidenav: download
---

:release: 13.2-RELEASE
:releaseNext: 13.3-RELEASE
:releaseBranch: 13-STABLE

= FreeBSD {release} Errata

== Abstract

This document lists errata items for FreeBSD {release}, containing significant information discovered after the release or too late in the release cycle to be otherwise included in the release documentation.
This information includes security advisories, as well as news relating to the software or documentation that could affect its operation or usability.
An up-to-date version of this document should always be consulted before installing this version of FreeBSD.

This errata document for FreeBSD {release} will be maintained until the release of FreeBSD {releaseNext}.

== Table of Contents

* <<intro,Introduction>>
* <<security,Security Advisories>>
* <<errata,Errata Notices>>
* <<open-issues,Open Issues>>
* <<late-news,Late-Breaking News>>
* <<erratas-announcement,Erratas in Announcement>>

[[intro]]
== Introduction

This errata document contains "late-breaking news" about FreeBSD {release}.
Before installing this version, it is important to consult this document to learn about any post-release discoveries or problems that may already have been found and fixed.

Any version of this errata document actually distributed with the release (for example, on a CDROM distribution) will be out of date by definition, but other copies are kept updated on the Internet and should be consulted as the "current errata" for this release.
These other copies of the errata are located at https://www.FreeBSD.org/releases/, plus any sites which keep up-to-date mirrors of this location.

Source and binary snapshots of FreeBSD {releaseBranch} also contain up-to-date copies of this document (as of the time of the snapshot).

For a list of all FreeBSD CERT security advisories, see https://www.FreeBSD.org/security/.

[[security]]
== Security Advisories

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Advisory |Date |Topic
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-23:04.pam_krb5.asc[FreeBSD-SA-23:04.pam_krb5] |21 June 2023 |Network authentication attack via pam_krb5
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-23:06.ipv6.asc[FreeBSD-SA-23:06.ipv6] |1 August 2023 |Remote denial of service in IPv6 fragment reassembly
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-23:07.bhyve.asc[FreeBSD-SA-23:07.bhyve] |1 August 2023 |bhyve privileged guest escape via fwctl
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-23:08.ssh.asc[FreeBSD-SA-23:08.ssh] |1 August 2023 |Potential remote code execution via ssh-agent forwarding
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-SA-23:09.pam_krb5.asc[FreeBSD-SA-23:09.pam_krb5] |1 August 2023 |Network authentication attack via pam_krb5
|===

[[errata]]
== Errata Notices

[width="100%",cols="40%,30%,30%",options="header",]
|===
|Errata |Date |Topic
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-EN-23:06.loader.asc[FreeBSD-EN-23:06.loader] |21 June 2023 |x86 kernel console configuration
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-EN-23:07.mpr.asc[FreeBSD-EN-23:07.mpr] |21 June 2023 |mpr(4) may fail to initialize devices
|link:https://www.FreeBSD.org/security/advisories/FreeBSD-EN-23:08.vnet.asc[FreeBSD-EN-23:08.vnet] |1 August 2023 |VNET and DPCPU module panic on arm64
|===

[[open-issues]]
== Open Issues

No open issues.

[[late-news]]
== Late-Breaking News

No late-breaking news.

[[erratas-announcement]]
== Erratas in Announcement

* tzdata version is 2023c and not 2023b.
* OpenSSH version is 9.3p1 and not 9.2p1.
