---
title: Parte II. Tarefas comuns
prev: books/handbook/x11
next: books/handbook/desktop
---

ifdef::env-beastie+backend-html5[]
:chapters-path: content/{{% lang %}}/books/handbook/
endif::[]

ifndef::env-beastie[]
:chapters-path:
endif::[]

[[common-tasks]]
= Tarefas comuns

Agora que o básico foi abordado, esta parte do livro discute alguns recursos freqüentemente usados do FreeBSD. Estes capítulos:

* Introduzem aplicativos de desktop populares e úteis: navegadores, ferramentas de produtividade, visualizadores de documentos e muito mais.
* Introduzem uma série de ferramentas multimídia disponíveis para o FreeBSD.
* Explicam o processo de compilação de um kernel customizado do FreeBSD para habilitar funcionalidades extras.
* Descrevem o sistema de impressão em detalhes, tanto configurações de impressoras conectadas em desktops quanto impressoras conectadas à rede.
* Mostram como executar aplicativos Linux no sistema FreeBSD.

Alguns destes capítulos recomendam leituras prévias, e isso é destacado na sinopse no início de cada capítulo.

include::{chapters-path}toc-2.adoc[]
