# $FreeBSD: www/en/releases/7.2R/Makefile,v 1.1 2009/03/17 13:39:34 rwatson Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml status.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
