# $FreeBSD: www/en/releases/7.2R/Makefile,v 1.2 2009/04/10 12:52:02 blackend Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	schedule.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
