#
# $FreeBSD$
#
# Article: Bootstrapping Vinum

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml
IMAGES_EN=	ad0b4aft.eps
IMAGES_EN+=	ad2b4aft.eps
IMAGES_EN+=	arch.eps

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
