# $FreeBSD$

DOC?= article

FORMATS?= html

IMAGES_EN=	ad0b4aft.eps ad2b4aft.eps arch.eps

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

WITH_ARTICLE_TOC?=YES

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
