#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/articles/ipsec-must/Makefile,v 1.1 2001/07/09 06:56:28 kappa Exp $
#
# Original revision: 1.1
#

MAINTAINER=	kappa@FreeBSD.org.ua

DOC?=	article

FORMATS?=	html

INSTALL_COMPRESSED?=	gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?=	${.CURDIR}/../../..
.include	"${DOC_PREFIX}/share/mk/doc.project.mk"
