# $Id: Makefile,v 1.1.1.1 1999-02-08 19:26:11 wosch Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS=	projects.sgml
DOCS+=	mozilla.sgml
DOCS+=	newbies.sgml

INDEXLINK= projects.html

.include "../web.mk"
