# $FreeBSD: www/ja/releases/3.4R/Makefile,v 1.2 2000/01/06 02:39:46 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

DOCS=	announce.sgml notes.sgml errata.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/3.4R

.include "../../../web.mk"
