# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

DOCS=	errata.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/3.4R

.include "../../../web.mk"
