# $FreeBSD: www/ja/releases/3.4R/Makefile,v 1.1 1999/12/28 08:17:16 kuriyama Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.1

DOCS=	announce.sgml errata.sgml

### Revision checking
REVFILES=	${DOCS:M*.sgml:S/.sgml$/.revinc/g}
BUILDTOP=	../../..
DIR_IN_LOCAL=	releases/3.4R

.include "../../../web.mk"
