# $Id: Makefile,v 1.5 1998-08-11 11:43:51 wosch Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

DOCS = 	commercial.sgml
DOCS+=	consulting.sgml
DOCS+=  hardware.sgml
DOCS+=  misc.sgml
DOCS+=  software.sgml

INDEXLINK=commercial.html

.include <../web.mk>
