# $FreeBSD: www/en/news/2000/Makefile,v 1.1 2001/04/13 00:54:11 eric Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
