=== FreeBSD Foundation

Links: +
link:https://freebsdfoundation.org/[FreeBSD Foundation] URL: link:https://freebsdfoundation.org/[] +
link:https://freebsdfoundation.org/blog/technology-roadmap/[Technology Roadmap] URL: link:https://freebsdfoundation.org/blog/technology-roadmap/[] +
link:https://freebsdfoundation.org/donate/[Donate] URL: link:https://freebsdfoundation.org/donate/[] +
link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[Foundation Partnership Program] URL: link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[] +
link:https://freebsdfoundation.org/journal/[FreeBSD Journal] URL: link:https://freebsdfoundation.org/journal/[] +
link:https://freebsdfoundation.org/our-work/events/[Foundation Events] URL: link:https://freebsdfoundation.org/our-work/events/[]

Contact: Deb Goodkin <deb@FreeBSDFoundation.org>

The FreeBSD Foundation is a 501(c)(3) non-profit organization dedicated to supporting and promoting the FreeBSD Project and worldwide community, and helping to advance the state of FreeBSD.
We do this in both technical and non-technical ways.
We are 100% supported by donations from individuals and corporations and those investments help us fund the:

* Software development projects to implement features and functionality in FreeBSD
* Sponsor and organize conferences and developer summits to provide collaborative opportunities and promote FreeBSD
* Purchase and support of hardware to improve and maintain FreeBSD infrastructure
* Resources to improve security, quality assurance, and continuous integration efforts
* Materials and staff needed to promote, educate, and advocate for FreeBSD
* Collaboration between commercial vendors and FreeBSD developers
* Representation of the FreeBSD Project in executing contracts, license agreements, and other legal arrangements that require a recognized legal entity

==== Operations
We kicked off the new year with ambitious goals to help move the FreeBSD Project forward by identifying features and functionality to support in the operating system and increasing our advocacy efforts to increase and expand the visibility of FreeBSD.
Stay tuned for a blog post that will provide more information on our 2024 goals and plans.

We also published the 2024 Budget.
In order to provide greater transparency about the budgeting process, we wrote a link:https://freebsdfoundation.org/blog/on-starting-the-2024-freebsd-foundation-budget-journey/[blog post] that provides more details on how funding is allocated, new breakouts of some of the project expense categories, and more details on where the funding is going.

==== OS Improvements
During the first quarter of 2024, 180 src, 65 ports, and 18 doc tree commits identified The FreeBSD Foundation as a sponsor.

Three new projects began this quarter.

* Work began to improve FreeBSD's audio stack and provide audio developers with useful tools and frameworks to make sound development on FreeBSD easier.
  Read more in mailto:christos@FreeBSD.org[Christos Margiolis] <<_audio_stack_improvements,Audio Stack Improvements>> report entry.

* mailto:olce@FreeBSD.org[Olivier Certner] began his second contract with the Foundation, and this time around, the main goal is to make unionfs stable and useful on FreeBSD.
  Other work may include revamping VFS lookups, improving out-of-memory handling, implementing a notification system for en-masse detection of filesystem changes such as inotify, and improving console usability.

* This quarter, a new project to add hierarchical rate limits to the OpenZFS file system began.
  mailto:pjd@FreeBSD.org[Pawel Dawidek] will add support for limits that will be configurable, similar to quotas, but would limit the number of read/write operations and read/write bandwidth.

Six projects continued this quarter.

* You can read about the continued work to port OpenStack components to FreeBSD in Chih-Hsin Chang's <<_openstack_on_freebsd,OpenStack on FreeBSD>> report entry.

* Work continued to improve cloud-init support for FreeBSD.
  You can read about Mina Galić's work in her <<_freeBSD_as_a_tier_1_cloud-init_platform,FreeBSD as a Tier 1 cloud-init Platform>> report entry.

* A new joint project began between Advanced Micro Devices (AMD) and The FreeBSD Foundation to develop a complete FreeBSD AMD IOMMU driver.
  This work will allow FreeBSD to fully support greater than 256 cores with features such as CPU mapping and will also include bhyve integration.
  For those interested in the technical details, follow mailto:kib@FreeBSD.org[Konstantin Belousov] commits tagged with Sponsored by fields for Advanced Micro Devices (AMD) and The FreeBSD Foundation.

* Refer to Pierre Pronchery's <<_graphical_installer_for_freebsd,Graphical Installer for FreeBSD>> report entry to read about the status of FreeBSD's new graphical installer.

* Work continues to port the Vector Packet Processor (VPP) to FreeBSD.
  VPP is an open-source, high-performance user space networking stack that provides fast packet processing suitable for software-defined networking and network function virtualization applications.
  Look for a pending article from the developer working on the project, mailto:thj@FreeBSD.org[Tom Jones], that details the experience of porting VPP to FreeBSD.

* mailto:bz@FreeBSD.org[Björn Zeeb] and mailto:cc@FreeBSDd.org[Cheng Cui] continue their wireless work.
  This quarter was mostly focused on bug fixes and stability improvements to LinuxKPI 802.11 and net80211.
  Much of this work made it into the 13.3 release.

Here is a sampling of other Foundation-sponsored development completed over the first quarter of 2024:

* FreeBSD was accepted in Google Summer of Code 2024 after receiving 22 contributor proposals; on May 1, we will learn how many projects we will be awarded
* OpenSSH: update to 9.6p1 then 9.7p1
* Deprecate bsdlabel
* Import the kernel parts of bhyve/arm64
* Various RISC-V improvements

==== FreeBSD Infrastructure
A contract was completed to set up a new cluster site at NYI Chicago.
You can read about the details of that project on the link:https://freebsdfoundation.org/blog/powering-up-the-future-the-new-freebsd-cluster-in-chicago/[Foundation's blog].

==== Continuous Integration and Workflow Improvement
As part of our continued support of the FreeBSD Project, the Foundation supports a full-time staff member dedicated to improving the Project's continuous integration system and the test infrastructure.
The full update can be found within the quarterly status report.

==== Partnerships and Research
A focus of Partnerships this Quarter has been to educate the industry about the innovations in the FreeBSD community and the impact that FreeBSD continues to have as a cornerstone to our digital society.
This is an ongoing priority, and one we invite (encourage) everyone using and working on FreeBSD to join us in.
Greg Wallace, the Foundation Partnerships lead, is grateful for the opportunities he has had to meet with open source and industry leaders at Microsoft, Google, AWS, OpenSSF, Alpha-Omega, CISA, Eclipse Foundation, Open Source Initiative, Apache Software Foundation, Rust Foundation, Red Hat, Linux Foundation and many others to ensure they have visibility into the key role FreeBSD plays in the global digital infrastructure.
This is a role FreeBSD has earned through its technical excellence, security by design, high availability, simplicity of operations, commitment to open source collaboration, and cohesiveness.

One sees these characteristics of FreeBSD in the important ongoing funded development work such as porting VPP to FreeBSD, sponsored by RG Nets.

Ensuring industry visibility to the excellence and impact of FreeBSD is vital to ensuring tier one support for FreeBSD across all key hardware and software platforms.
As a community, every conversation we have with people outside the BSD communities, and every piece of content we publish, that attest to how FreeBSD powers our individual and corporate success, brings us one step closer.

To this end, the Foundation is working on a FreeBSD Impact Report that will aggregate the core and often mission critical role FreeBSD plays in society, from embedded systems powered by QNX, to payments and check processing, to digital entertainment, internet and cybersecurity infrastructure.

Our community is stepping up in innumerable ways, including to make sure FreeBSD supports industry-standard containerized workloads -- check out the link:https://github.com/opencontainers/wg-freebsd-runtime[Open Container Initiative FreeBSD runtime extension working group].

The recently opened hardware vendor support survey will feed into a hardware support guide that reflects the collective experience of all respondents that is intended to help everyone identify hardware vendors that prioritize FreeBSD; it will also help focus Partnerships' outreach on the priority vendors.

To close, please *TELL THE WORLD YOU USE FREEBSD AND WHY. There is no wrong way to do this* -- put it on your blog, on your favorite social media channel, list FreeBSD on your company’s Open Source page, contact the Foundation about a Case Study, etc.

link:https://www.stormshield.com/news/a-short-history-of-open-source/[Stormshield, a leading cybersecurity company based in Europe, provides a great example of how vendors that use FreeBSD can do this]. The footer of their blogs says: "A strong supporter of Open Source, Stormshield is an active member (and sponsor) of the FreeBSD community...Whenever we modify Open Source software, make patches or add features, we offer them to the community for inclusion."

==== Advocacy
The first quarter of 2024 marked the beginning of a link:https://freebsdfoundation.org/blog/march-2024-advocacy-update/[new era] for the Foundation Advocacy team.
We welcomed link:https://freebsdfoundation.org/blog/kim-mcmahon-to-join-freebsd-foundation-as-senior-director-of-advocacy-and-community/[Kim McMahon] in the role of Senior Director of Advocacy and Community and also brought on two new technical writers to help increase the frequency and depth of the FreeBSD-related content we produce.
Just some of our expanded Q1 efforts to support FreeBSD are below.

* Began work planning the on the link:https://freebsdfoundation.org/news-and-events/event-calendar/may-2024-freebsd-developer-summit/[May 2024 FreeBSD Developer Summit], co-located with BSDCan, taking place May 29-30, 2024 in Ottawa, Canada
* Introduced FreeBSD to new and returning folks at link:https://stateofopencon.com/soocon-2024/[State of Open Con 24] in London, UK, February 6-7, 2024
* Held an Introduction to FreeBSD half-day workshop and staffed a booth at link:https://www.socallinuxexpo.org/scale/21x[SCaLE21x], which took place March 14-17, 2024 in Pasadena, CA.
  Thanks to Gordon Tetlow for his help with the workshop
* The Foundation team also worked on a common message on the improvement and benefits of FreeBSD to ensure consistency between the FreeBSD Foundation and Core Team
* Members of the Foundation team served as Administrators for the 2024 Google Summer of Code.
  This year marks the 20th anniversary of Google Summer of Code and the 20th year that the link:https://freebsdfoundation.org/blog/the-freebsd-project-participating-in-google-summer-of-code-2024-2/[FreeBSD Project was accepted as a mentoring organization].
  The Project received 23 applications from prospective interns
* Provided an link:https://freebsdfoundation.org/blog/freebsd-13-3-whats-new-and-how-did-we-get-here/[overview of FreeBSD 13.x] including the 13.3 release
* Worked on the final report of the 2024 FreeBSD Community Survey.
  Be on the lookout for the report at the end of April
* In partnership with Innovate UK and Digital Security by Design (DSbD), the Foundation held the first annual link:https://www.globenewswire.com/news-release/2024/04/03/2856691/0/en/FreeBSD-Foundation-and-Digital-Security-by-Design-DSbD-Announce-Beacon-Award-Winners-for-Innovations-and-Improvements-to-CheriBSD.html[Digital Security by Design (DSbD) Ecosystem Beacon Awards] to celebrate innovators working with and enhancing CheriBSD
* Published numerous blogs including:
** link:https://freebsdfoundation.org/blog/what-makes-the-freebsd-governance-model-successful/[What Makes the FreeBSD Governance Model Successful]
** link:https://freebsdfoundation.org/blog/guiding-the-future-of-freebsd-releases-colin-percival-the-new-release-engineering-team-lead/[Guiding the future of FreeBSD releases: Colin Percival, the new Release Engineering Team Lead]
* Authored or participated in a number of Thought Leadership and News articles including:
** link:https://freebsdfoundation.org/news-and-events/latest-news/the-cybersecurity-battle-has-come-to-hardware/[The Cybersecurity Battle Has Come to Hardware]
** link:https://freebsdfoundation.org/news-and-events/latest-news/ampere-in-the-wild-how-freebsd-employs-ampere-arm64-servers-in-the-data-center/[Ampere in the Wild: How FreeBSD Employs Ampere Arm64 Servers in the Data Center]
** link:https://freebsdfoundation.org/news-and-events/latest-news/isas-and-the-dawning-hardware-security-revolution/[ISAs and the Dawning Hardware Security Revolution]
** Published the link:https://freebsdfoundation.org/news-and-events/newsletter/march-2024-foundation-update/[March 2024 FreeBSD Update] with a new look
** Released the link:https://freebsdfoundation.org/past-issues/freebsd-14-0/[November/December 2023] and link:https://freebsdfoundation.org/past-issues/networking-10th-anniversary/[January/February 2024] issues of the FreeBSD Journal now with HTML versions of the articles

==== Fundraising
Thank you to everyone who gave us a financial contribution last quarter to help fund our work to support the Project.
2024 started strong with a total of $250,855 raised this quarter.
We are grateful for your investment in FreeBSD!

Please consider supporting our efforts in 2024 by making a donation here: link:https://freebsdfoundation.org/donate/[].

Or, check out our Partnership opportunities here:
link:https://freebsdfoundation.org/our-donors/freebsd-foundation-partnership-program/[].

==== Legal/FreeBSD IP

The Foundation owns the FreeBSD trademarks, and it is our responsibility to protect them.
We also provide legal support for the core team to investigate questions that arise.

Go to link:https://freebsdfoundation.org[] to find more about how we support FreeBSD and how we can help you!
