=== GCC on FreeBSD

Links: +
link:https://gcc.gnu.org/[GCC Project] URL: link:https://gcc.gnu.org/[] +
link:https://gcc.gnu.org/gcc-10/[GCC 10 release series] URL: link:https://gcc.gnu.org/gcc-10/[] +
link:https://gcc.gnu.org/gcc-11/[GCC 11 release series] URL: link:https://gcc.gnu.org/gcc-11/[] +
link:https://gcc.gnu.org/gcc-12/[GCC 12 release series] URL: link:https://gcc.gnu.org/gcc-12/[] +
link:https://gcc.gnu.org/gcc-13/[GCC 13 release series] URL: link:https://gcc.gnu.org/gcc-13/[]

Contact: Lorenzo Salvadore <salvadore@FreeBSD.org>

link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273397[Updating GCC default version to 13] is finally finished.
Thanks to mailto:antoine@FreeBSD.org[Antoine Brodin] who ran the exp-runs and to all other developers and ports maintainers involved.

As promised in the preceding report, the next goal is to reduce the number of open bugs for GCC ports.
Some work on existing bugs has already started.

In particular, package:lang/gcc14-devel[] has long stayed out of date due to some issues with building the port without any BOOTSTRAP option.
Thanks to the help of other developers and contributors (a special thank to Mark Millard), I noticed that according to the official documentation link:https://gcc.gnu.org/install/prerequisites.html[building GCC without bootstrap requires a working GCC binary] and thus I switched package:lang/gcc14-devel[] to require that a BOOTSTRAP option is set.
However it has later been stated that bootstrapping GCC using clang and libc++ is link:https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111632[officially supported].
But it has also been stated that this is not a high priority.

At the moment package:lang/gcc14-devel[] is the only GCC port requiring a BOOTSTRAP option to be set.
The plan is to have all GCC ports for versions greater or equal than 14 (i.e. future GCC ports) to require such an option: even if building without bootstrap is more or less officially supported, being low priority for upstream it increases the burden of maintaining GCC ports for low results.
In case lower versions start to have issues building without bootstrap, I am going to require bootstrap for those as well.
