=== Ports Collection

Links: +
link:https://www.FreeBSD.org/ports/[About FreeBSD Ports] URL:link:https://www.FreeBSD.org/ports/[] +
link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[Contributing to Ports] URL: link:https://docs.freebsd.org/en/articles/contributing/#ports-contributing[] +
link:https://www.freebsd.org/portmgr/[Ports Management Team] URL: link:https://www.freebsd.org/portmgr/[] +
link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[Ports Tarball] URL: link:http://ftp.freebsd.org/pub/FreeBSD/ports/ports/[]

Contact: Tobias C. Berner <portmgr-secretary@FreeBSD.org> +
Contact: FreeBSD Ports Management Team <portmgr@FreeBSD.org>

The Ports Management Team is responsible for overseeing the overall direction of the Ports Tree, building packages, and personnel matters.
Below is what happened in the last quarter.

According to INDEX, there are currently 32,244 ports in the Ports Collection.
There are currently ~3,300 open ports PRs.
The last quarter saw 12,991 commits by 158 committers on the main branch and 888 commits by 61 committers on the 2024Q1 branch.
Compared to last quarter, this means a large increase in the number of commits on the main branch (up from 9,424) and slightly more backports to the quarterly branch (up from 781).
The number of ports also increased (up from 31,942).

In Q1 there were around 14,127 commits to main:
The most active committers were:

* 2934 sunpoet
* 2676 bofh
* 1297 yuri
* 748 eduardo
* 545 jbeich
* 347 arrowd
* 233 diizzy
* 195 yasu
* 170 ehaupt
* 164 wen

A lot has happened in the ports tree in the last quarter, an excerpt of the major software upgrades are:

* pkg 1.21.0
* New USES: ocaml
* Default version of gcc switched to 13
* Default version of ruby switched to 3.2
* Default version of lazarus switched to 3.2.0
* Default version of go switched to 1.21
* Chromium updated to 123.0.6312.105
* Electron-28 updated to 28.2.10
* Electron-27 updated to 27.3.9
* Firefox updated to 124.0.2
* Firefox-esr updated to 115.9.1
* KDE updated to Frameworks 5 5.115, Frameworks 6 to 6.0.0 Plasma Desktop 5 to 5.27.11, Plasma Desktop 6 to 6.0.2
* Qt5 updated to 5.15.13
* Qt6 updated to 6.6.3
* Python updated to 3.11.9, 3.10.14 and 3.8.10
* Ruby updated to 3.2.3
* Rust updated to 1.77.0
* SDL updated to 2.30.2
* Sway updated to 1.9
* wlroots updated to 1.17.2
* Wine updated to 9.0
* Xorg server updated to 0.17.2


During the last quarter, mailto:pkgmgr@FreeBSD.org[FreeBSD Packages Management Team] ran 17 exp-runs to test various ports upgrades, updates to default versions of ports, subpackage support and base system changes.
