=== iwlwifi(4) and wireless for 13.3-RELEASE

Links: +
link:https://bugs.freebsd.org/bugzilla/showdependencytree.cgi?id=277512&hide_resolved=0[Categorised Wireless Problem Reports] URL: link:https://bugs.freebsd.org/bugzilla/showdependencytree.cgi?id=277512&hide_resolved=0[]

Contact: Bjoern A. Zeeb <bz@FreeBSD.org> +
Contact: The FreeBSD wireless mailing list <wireless@FreeBSD.org>

In the first weeks of 2024 focus was on stability for 13.3-RELEASE to finally make man:iwlwifi[4] usable.
The upcoming 14.1-RELEASE will benefit from this work too.
The response has since generally been positive and man:iwlwifi[4] supporting chipsets up to BE200 seems mostly stable, yet still slow.

A lot of testing was provided by the FreeBSD Foundation and by many users.
Massive thanks to everyone who tested, reported back, updated PRs and helped other users.

I have also slowly started to "categorise" more (old) wireless problem reports and will try to continue with some spring cleaning throughout the year.

If you have questions or feedback please use the link:https://lists.freebsd.org/subscription/freebsd-wireless[freebsd-wireless mailing list].
That way everyone will see, be able to join in, and the answers will be publicly archived.

Sponsor: minipci.biz (BE200 hardware)
