---
title: "FreeBSD 3.0 Announcement"
sidenav: download
---

include::shared/en/urls.adoc[]

= FreeBSD 3.0 Announcement

*Date:* Fri, 16 Oct 1998 13:19:03 -0700 +
*From:* "Jordan K. Hubbard" <jkh@time.cdrom.com> +
**Subject:**FreeBSD 3.0 is now released!

After what can only be described as a heroic effort by the FreeBSD Project volunteers, the long-awaited release of FreeBSD 3.0 is now out!

This release is primarily aimed at developers and early-adopters, though many ISPs have reported good results when using it in production (not that we recommend this to any but the most highly skilled). See the link:notes.html[release notes] for more information.

FreeBSD 3.0-RELEASE is available on ftp://ftp.FreeBSD.org/pub/FreeBSD[ftp.FreeBSD.org] and various link:{handbook}#mirrors[FTP mirror sites] throughout the world. It can also be ordered on CD from http://www.cdrom.com/[Walnut Creek CDROM], from where it will be shipping shortly as a 4 CD set containing a lot of extra stuff of interest to programmers and general users alike.

*IMPORTANT NOTE*: All of the profits from the sales of this CD set go to support the FreeBSD Project!

Like many businesses in the field of high-tech, Walnut Creek CDROM has realized that in order to make any product for an emerging market grow, you have to make a significant investment in such growth, even if it means abandoning short-term profits. Walnut Creek CDROM is the only CDROM vendor who currently does anything like this and it's certainly my hope that you will help support the project by buying (or getting someone else to buy :) one of their CDs. Thanks!

The official FTP distribution site for FreeBSD is:

____
ftp://ftp.FreeBSD.org/pub/FreeBSD
____

Or via the WEB page at:

____
http://www.cdrom.com/pub/FreeBSD
____

And on CD-ROM from Walnut Creek CDROM:

____
Walnut Creek CDROM +
4041 Pike Lane, #F +
Concord CA, 94520 USA +
Phone: +1 925 674-0783 +
Fax: +1 925 674-0821 +
Tech Support: +1 925 603-1234 +
Email: info@cdrom.com +
WWW: http://www.cdrom.com/
____

If you are in Japan, please refer to http://www.pht.co.jp/[Pacific HiTech] for information on ordering a localized (or the english) version of the 3.0 product when it becomes available. Pacific HiTech is now an affiliate of Walnut Creek CDROM for Japanese sales of FreeBSD.

Additionally, FreeBSD is available via anonymous FTP from link:{handbook}#mirrors[mirror sites] in the following countries: Argentina, Australia, Brazil, Bulgaria, Canada, the Czech Republic, Denmark, Estonia, Finland, France, Germany, Hong Kong, Hungary, Iceland, Ireland, Israel, Japan, Korea, Latvia, Malaysia, the Netherlands, Poland, Portugal, Romania, Russia, Slovenia, South Africa, Spain, Sweden, Taiwan, Thailand, the Ukraine and the United Kingdom (and quite possibly several others which I've never even heard of :).

Before trying the central FTP site, please check your regional mirror(s) first by going to:

____
ftp://ftp.<yourdomain>.FreeBSD.org/pub/FreeBSD
____

Any additional mirror sites will be labeled ftp2, ftp3 and so on.

The latest versions of export-restricted code for FreeBSD (2.0C or later) (eBones and secure) are also being made available at the following locations. If you are outside the U.S. or Canada, please get secure (DES) and eBones (Kerberos) from one of the following foreign distribution sites:

South Africa::
  ftp://ftp.internat.FreeBSD.ORG/pub/FreeBSD[ftp://ftp.internat.F reeBSD.ORG/pub/FreeBSD] +
  ftp://ftp2.internat.FreeBSD.ORG/pub/FreeBSD[ftp://ftp2.internat.FreeBS D.ORG/pub/FreeBSD]
Brazil::
  ftp://ftp.br.FreeBSD.ORG/pub/FreeBSD[ftp://ftp.br.FreeBSD.ORG/p ub/FreeBSD]
Finland::
  ftp://nic.funet.fi/pub/unix/FreeBSD/eurocrypt[ftp://nic.funet.f i/pub/unix/FreeBSD/eurocrypt]

link:../../[Release Home]
