# $FreeBSD: doc/ja_JP.eucJP/Makefile,v 1.12 1999/09/06 06:53:16 peter Exp $
#
# Original revision: 1.5
#

SUBDIR = articles
SUBDIR+= books
SUBDIR+= man

COMPAT_SYMLINK = ja_JP.eucJP

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
