# $FreeBSD$
# The FreeBSD Russian Documentation Project
# Original revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

.if exists(Makefile.inc)
.include "Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif


.include "../web.mk"
