# $FreeBSD$
# The FreeBSD Russian Documentation Project
# $FreeBSDru: frdp/www/ru/ports/Makefile.inc0,v 1.3 2000/10/11 16:26:22 phantom Exp $
# Original revision: 1.3

.if exists(${.CURDIR}/../Makefile.conf)
.include "${.CURDIR}/../Makefile.conf"
.endif

.if exists(${.CURDIR}/../../en/ports/Makefile.inc)
.include "${.CURDIR}/../../en/ports/Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif


.include "../web.mk"
