# $FreeBSD$

SUBDIR =
SUBDIR+= committers-guide
SUBDIR+= explaining-bsd
SUBDIR+= filtering-bridges
SUBDIR+= new-users
SUBDIR+= vm-design

DOC_PREFIX?= ${.CURDIR}/../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
