# $FreeBSD$

SUBDIR =
SUBDIR+= committers-guide
SUBDIR+= euro
SUBDIR+= explaining-bsd
SUBDIR+= filtering-bridges
SUBDIR+= multi-os
SUBDIR+= new-users

DOC_PREFIX?= ${.CURDIR}/../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
