# $FreeBSD: doc/ru_RU.KOI8-R/Makefile,v 1.9 1999/09/29 11:56:18 jhb Exp $

MAINTAINER = phantom@FreeBSD.org

SUBDIR = books

COMPAT_SYMLINK = ru

DOC_PREFIX = ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
