# $FreeBSDde$
# $FreeBSD$
# basiert auf: r39631

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS+=		index.xml

#DATA+=		../../en/ipv6/IPv6-badge-blue-256-trans.png	\
#		../../en/ipv6/IPv6-badge-blue-128-trans.png
#DATA+=		../../en/ipv6/w6d-www-stats-large.png		\
#		../../en/ipv6/w6d-www-stats-v6-large.png	\
#		../../en/ipv6/w6d-www-stats-v6.png		\
#		../../en/ipv6/w6d-www-stats.png

.include "${DOC_PREFIX}/share/mk/web.site.mk"
