---
title: "FreeBSD 4.1 Announcement"
sidenav: download
--- 

= FreeBSD 4.1 Announcement

*Date:* Thu, 27 Jul 2000 05:17:09 -0700 +
*From:* "Jordan K. Hubbard" <jkh@zippy.osd.bsdi.com> +
*To:* announce@FreeBSD.org +
*Subject:* 4.1-RELEASE now available from ftp.freebsd.org

I'm very pleased to announce the availability of FreeBSD 4.1-RELEASE, the very latest in 4.x-STABLE branch technology. Following the release of FreeBSD 4.0 in March, 2000, many bugs were fixed, important security issues dealt with, and quite a few new features added. Please see the release notes for more information.

The 4.1-RELEASE is available for ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/4.1-RELEASE[i386] and ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/alpha/4.1-RELEASE[alpha] right now and can be installed directly over the net using the boot floppies or copied to a local NFS/ftp server. ISO images will also be provided later (see below).

ISO (CD) Images +
--------------- +

ISO images of the installation CD will be made available by August 1st 2000, after the bits have undergone a bit more integration testing. This additional delay is necessary given that the ISO images are so large (~650MB each) and are not something which many people want to transfer more than once. A follow-up announcement will be sent once the ISO images are in place, so please don't send me email asking where they are or when they'll be ready. When they're ready, they'll be uploaded and an announcement will be sent out.

We also can't promise that all the mirror sites will carry these large ISO images, but they will at least be available from:

ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/i386/ISO-IMAGES/4.1-install.iso +
ftp://ftp.FreeBSD.org/pub/FreeBSD/releases/alpha/ISO-IMAGES/4.1-install.iso

If you can't afford the CDs, are impatient, or just want to use it for evangelism purposes, then by all means download the ISOs, otherwise please do continue to support the FreeBSD project by purchasing one of its official CD releases from BSDi. FreeBSD 4.1-RELEASE can be ordered as a 4 CD set from http://www.freebsdmall.com[The FreeBSD Mall] from where it will soon be shipping. Each CD sets contains the FreeBSD installation and application package bits for either the x86 or the alpha architecture (each architecture has its own CD set). For a set of distfiles used to build ports in the ports collection, please see also the FreeBSD Toolkit, a 6 CD set containing all such extra bits which we can no longer fit on the 4 CD sets. You can also order by phone, postal mail, FAX or email at:

....
  BSDi
  4041 Pike Lane, #F
  Concord CA, 94520 USA
  Phone: +1 925 674-0783
  Fax: +1 925 674-0821
  Tech Support: +1 925 603-1234
  Email: orders@wccdrom.com
  WWW: http://www.wccdrom.com/
....

FreeBSD is also available via anonymous FTP from mirror sites in the following countries: Argentina, Australia, Austria, Brazil, Bulgaria, Canada, the Czech Republic, Denmark, Estonia, Finland, France, Germany, Hong Kong, Hungary, Iceland, Ireland, Israel, Japan, Korea, Latvia, Malaysia, the Netherlands, Poland, Portugal, Rumania, Russia, Slovenia, South Africa, Spain, Sweden, Taiwan, Thailand, Elbonia, the Ukraine and the United Kingdom (and quite possibly several others which I've never even heard of :).

Before trying the central FTP site, please check your regional mirror(s) first by going to:

[.kbd]#ftp://ftp.<yourdomain>.FreeBSD.org/pub/FreeBSD#

Any additional mirror sites will be labeled ftp2, ftp3 and so on.

The latest versions of export-restricted code for FreeBSD are also being made available at the following locations. Now that FreeBSD has export permission for crypto from the United States government, you can get it from the following locations or from ftp.freebsd.org:

South Africa::
  ftp://ftp.internat.FreeBSD.org/pub/FreeBSD +
  ftp://ftp2.internat.FreeBSD.org/pub/FreeBSD
Brazil::
  ftp://ftp.br.FreeBSD.org/pub/FreeBSD
Finland::
  ftp://nic.funet.fi/pub/unix/FreeBSD/eurocrypt

Thanks! - Jordan
