# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
#
# $FreeBSD$
# $FreeBSDde$
# basiert auf: r48383

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	newbies.xml
DOCS+=	cvsweb.xml

INDEXLINK= newbies.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
