# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
#
# $FreeBSD$
# $FreeBSDde: de-www/projects/Makefile,v 1.3 2007/08/29 08:47:34 as Exp $
# basiert auf: 1.31

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	projects.xml
DOCS+=	newbies.xml
DOCS+=	cvsweb.xml

INDEXLINK= projects.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
