# The FreeBSD Documentation Project
# The FreeBSD German Documentation Project
#
# $FreeBSD$
# $FreeBSDde: de-www/projects/Makefile.inc,v 1.1 2005/01/29 19:07:54 jkois Exp $
# basiert auf:  1.1

WEBBASE?=	/data/de/projects
DOC_PREFIX?=	${.CURDIR}/../../..
