# $FreeBSD: doc/ja_JP.eucJP/articles/Makefile,v 1.1.1.1 2000/01/06 07:22:40 kuriyama Exp $
# Original revision: 1.5

#SUBDIR = committers-guide
SUBDIR+= diskless-x
#SUBDIR+= fonts
#SUBDIR+= formatting-media
#SUBDIR+= mh
SUBDIR+= multi-os
#SUBDIR+= new-users
#SUBDIR+= programming-tools

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
