# $FreeBSD$
# Original revision: r41535

SUBDIR =
#SUBDIR+= bsdl-gpl
#SUBDIR+= building-products
#SUBDIR+= casestudy-argentina.com
#SUBDIR+= committers-guide
#SUBDIR+= compiz-fusion
#SUBDIR+= console-server
SUBDIR+= contributing
#SUBDIR+= contributing-ports
SUBDIR+= contributors
#SUBDIR+= cups
#SUBDIR+= custom-gcc
#SUBDIR+= cvs-freebsd
#SUBDIR+= explaining-bsd
SUBDIR+= fbsd-from-scratch
#SUBDIR+= filtering-bridges
SUBDIR+= fonts
#SUBDIR+= freebsd-questions
#SUBDIR+= freebsd-update-server
#SUBDIR+= geom-class
#SUBDIR+= gjournal-desktop
#SUBDIR+= hubs
SUBDIR+= ipsec-must
#SUBDIR+= laptop
#SUBDIR+= ldap-auth
#SUBDIR+= linux-comparison
#SUBDIR+= linux-emulation
#SUBDIR+= linux-users
#SUBDIR+= mailing-list-faq
#SUBDIR+= mh
#SUBDIR+= nanobsd
#SUBDIR+= new-users
#SUBDIR+= p4-primer
#SUBDIR+= pam
#SUBDIR+= port-mentor-guidelines
#SUBDIR+= portbuild
#SUBDIR+= pr-guidelines
SUBDIR+= problem-reports
#SUBDIR+= rc-scripting
#SUBDIR+= relaydelay
#SUBDIR+= releng
#SUBDIR+= releng-packages
#SUBDIR+= remote-install
#SUBDIR+= serial-uart
#SUBDIR+= solid-state
#SUBDIR+= vm-design

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
