# $FreeBSD: doc/ja_JP.eucJP/articles/Makefile,v 1.2 2000/03/22 06:32:11 kuriyama Exp $
# Original revision: 1.8

#SUBDIR = committers-guide
#SUBDIR+= dialup-firewall
SUBDIR+= diskless-x
#SUBDIR+= fonts
#SUBDIR+= formatting-media
#SUBDIR+= ipsec-must
#SUBDIR+= mh
SUBDIR+= multi-os
#SUBDIR+= new-users
#SUBDIR+= programming-tools
SUBDIR+= zip-drive

# ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
