.\"
.\" Copyright (c) 1997, 1998 Hellmuth Michaelis. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" %FreeBSD: src/usr.sbin/i4b/isdnd/isdnd.rc.5,v 1.1.2.2 1999/08/29 15:41:42 peter Exp % 
.\"
.\"     last edit-date: [Sat Dec  5 18:10:08 1998]
.\"
.\" jpman %Id: isdnd.rc.5,v 1.4 1999/02/11 15:43:12 horikawa Stab %
.\"
.\" WORD: exchange	交換局
.\" WORD: subscribe	(AOCD サービス等を) 申し込んでいる
.Dd October 27, 1998
.Dt isdnd.rc 5
.Sh 名称
.Nm isdnd.rc
.Nd isdn4bsd ISDN 接続管理デーモンの設定ファイル書式
.Sh 解説
(コマンドラインで別のものを指定しない限り) ファイル
.Pa /etc/isdn/isdnd.rc
は、
.Xr isdnd 8
ISDN 接続管理デーモンの実行時設定を格納します。
本デーモンは、isdn4bsd パッケージの一部です。
.Pp
設定ファイルには、第 1 桁から始まるキーワードが複数含まれます。
キーワードの後には、1 個以上の空白・タブ、単一の等号、1 個以上の空白・タブ、
キーワード依存のパラメータ値と続きます。
.Pp
文字 '#' で開始する行はコメント行として扱われます。
.Pp
ブール値指定を要求するキーワードに対しては、真を
.Em yes
または
.Em on
で与え、偽を
.Em no
または
.Em off
で与えます。
.Pp
設定ファイルには、単一の
.Em システム
セクションと 1 個以上の
.Em エントリ
セクションが含まれます。
.Em システム
セクションでは、デーモンの操作に関するパラメータや
単一のリモート接続に関連付けられないパラメータを設定可能です。
.Em エントリ
セクションでは、
単一のリモート接続に直接関連付けられたパラメータを設定可能です。
.Pp
次のキーワードを
.Nm isdnd
は理解します:
.Pp
.Bl -tag -width system -compact

.It Li system
本キーワードにより、システム設定セクションが開始します。
パラメータを伴ってはなりませんし、1 度のみ使用可能です。
本キーワードは必須です。
次のキーワードは、システム設定セクション内で有効です:
.Bl -tag -width useacctfile -compact

.It Li acctall
本パラメータを
.Em on
に設定すると、
ローカルサイトが課金されてない場合や、
課金情報が利用不能だったり課金情報を申し込んでいない場合でも、
アカウンティング情報が書き込まれます。(省略可能)

.It Li acctfile
キーワード
.Em useacctfile
(後述) が
.Em on
に設定されたときに使用されるアカウンティングファイルの名前を指定します。
本キーワードを指定しないと、システムデフォルトが使用されます。(省略可能)

.It Li aliasing
本パラメータが
.Em on
に設定されると、電話番号から名前へのエイリアス処理が有効にされます (後述の
.Em aliasfile
キーワードも参照)。デフォルトは off です。(省略可能)

.It Li aliasfile
.Em aliasing
キーワードによりエイリアス処理が有効にされたときに
.Xr isdntel 1
ユーティリティと共有される、
電話番号から名前へのエイリアスデータベースファイルの名前を指定します。
(省略可能)

.It Li isdntime
本パラメータが
.Em on
に設定されると、(提供されるならば) 交換局から得られる日付/時刻情報を
ログファイルに書き込みます。デフォルトは off です。(省略可能)

.It Li monitor-allowed
本パラメータが
.Em on 
または
.Em yes
に設定されると、
ローカルマシンまたはリモートマシンを介した監視が有効になります。
本パラメータは省略可能であり、デフォルトで
.Em off
に設定されます。

.It Li monitor-port
リモート監視用の TCP ポート番号を設定します。
本整数パラメータは省略可能であり、デフォルトでポート 451 に設定されます。

.It Li monitor
本キーワードは、ローカルソケット名または、
リモート監視用にホストまたはネットワークを指定します。
.Em monitor 
の指定は次のいずれかです:
.Pp
.Bl -tag -width Ds -compact -offset
.It Ar ローカル (UNIX ドメイン) ソケット名
文字 "/" で開始する必要があります。例: /var/run/isdn-monitor
.It Ar ドット付き 4 つ組のホスト指定
例: 192.168.1.2
.It Ar ドット付き 4 つ組のネットワークアドレスとネットマスク
例: 192.168.1.0/24
.It Ar 解決可能なホスト名
例: localhost
.It Ar 解決可能なネットワーク名とネットマスク
例: up-vision-net/24
.El

.It Li monitor-access
本キーワードは、以前使用した
.Em monitor
キーワードのアクセス権限を指定します。
サポートされているアクセス権限は次の通りです:
.Pp
.Bl -tag -width Ds -compact -offset
.It Ar fullcmd
.It Ar restrictedcmd
.It Ar channelstate
.It Ar logevents
.It Ar callin
.It Ar callout
.El

.It Li ratesfile
料金ファイルの名前を指定します。
本キーワードが省略された場合、システムデフォルトが使用されます。(省略可能)

.It Li regexpr
本キーワードは、正規表現を指定するために使用されます。
1 度以上、コンパイル時依存の回数
(現在、ソースにおける MAX_RE の定義では 5 回)
まで指定することが可能です。
.Pp
指定した全正規表現は実行時にログ文字列と比較され、
マッチした場合には、ログテキストをパラメータとしてプログラムが実行されます
(後述のキーワード
.Em regprog
も参照)。
.Pp
正規表現の指定方法については、
.Xr re_format 7
と
.Xr regex 3
を参照してください。
.Em 拡張
正規表現の書式がサポートされています。
.Pp
ヒント: 設定ファイルのパーザが不適切に解釈することを避けるために、
式を適切にクォートする必要があるかもしれません。
(省略可能)

.It Li regprog
本キーワードは、対応する正規表現がログ文字列にマッチした場合に実行される、
プログラムの名前を指定するために使用されます。
.Nm isdnd
は、パス
.Pa /etc/isdn
以下でプログラムを見付けられるものと期待します。
このパスは、本キーワードのパラメータとして指定された文字列の前に付けられます。
(省略可能)

.It Li rtprio
.Nm isdnd
が実行されるリアルタイム優先度を、0 〜 31 の範囲の整数値で指定します。
0 は最高の優先度です。
本キーワードは省略可能です。
指定しない場合、
.Nm isdnd
の処理優先度はまったく修正されません。(
.Xr rtprio 1 
も参照)。
本キーワードは、
.Nm
を -DUSE_RTPRIO 付きでコンパイルした場合にのみ利用可能です。

.It Li useacctfile
本パラメータが
.Em on
に設定された場合、(利用可能な場合) 課金情報とアカウンティング情報が
アカウンティングファイルに書き込まれます。(省略可能)

.El

.It Li entry
本キーワードにより、単一の設定エントリが開始します。
パラメータを伴ってはなりません。
本キーワードは、少なくとも 1 度は使用する必要があります。
次のキーワードは、エントリセクション内で有効です:
.Bl -tag -width unitlengthsrc -compact

.It Li answerprog
本キーワードは、着信電話接続が設定エントリにおいて
.Em answer
を指定した場合に実行される、プログラムの名前を指定するために使用されます。
デフォルト名は
.Em answer
です。
.Nm isdnd
は、パス
.Pa /etc/isdn
以下でプログラムを見付けられるものと期待します。
このパスは、本キーワードのパラメータとして指定された文字列の前に付けられます。
(省略可能)

.It Li alert
呼 (call) を受け付ける前に待つ秒数を指定するために使用します。
本キーワードは、電話着呼 (dialin-reaction = answer)
のためにのみ指定可能です。
留守番マシンが実行を開始する前に、
電話の着呼 (incoming call) を受け付ける機会を持つために使用します。
本パラメータの最小値は 5 秒であり、パラメータの最大値は 180 秒です。
(省略可能)

.It Li b1protocol
本接続に使用される B チャネルのレイヤ 1 プロトコルです。
本キーワードは必須です。
現在設定可能な値は次の通りです:
.Pp
.Bl -tag -width Ds -compact -offset
.It Ar hdlc
HDLC フレーミング。
.It Ar raw
フレーミングを行わない (電話通信のために使用)。
.El

.It Li callbackwait
リモートサイトからの呼を切ってから
リモートサイトにコールバックするまでに待つ秒数です。(省略可能)

.It Li calledbackwait
ローカルサイトがリモートサイトを呼び出した後、
リモートサイトがローカルサイトにコールバックするまでに待つ秒数です。(省略可能)

.It Li dialin-reaction
着信接続要求を受けた場合にどうするかを指定するために使用します。
本キーワードは必須です。
現在サポートされているパラメータは次の通りです:
.Pp
.Bl -tag -width calledback -compact -offset
.It Ar accept
着呼を受け付けます。
.It Ar reject
着呼を拒否します。
.It Ar ignore
着呼を無視します。
.It Ar answer
着信音声呼び出しに対して、留守番電話を開始します。
.It Ar callback
リモートサイトが呼び出したとき、
その呼を切ってリモートサイトにコールバックします。
.El

.It Li dialout-type
本キーワードは、どのタイプのダイヤルアウトモードが使用されるかを設定します。
本キーワードは必須です。
現在サポートされているパラメータは次の通りです:
.Pp
.Bl -tag -width Ds -compact -offset
.It Ar normal
通常動作。呼を受け付けると思われるリモートサイトを呼び出します。
.It Ar calledback
コールバック動作。
呼を拒否してから当方にコールバックするリモートサイトを呼び出します。
.El

.It Li dialrandincr
ダイヤル時または再ダイヤル時、本パラメータが
.Em on
に設定されていると、
ダイヤル再試行時間に乱数 (現在 0 〜 3 秒) が加えられます。
2 つのサイトが同期してダイヤルしてしまい、
他方もダイヤルしているために双方がダイヤルする度にビジーを検出するという機会を
最小化します。

.It Li dialretries
ダイヤルをあきらめる前に再試行する回数です。(省略可能)

.It Li direction
本キーワードは、発信着信・発信のみ・着信のみのいずれの接続が可能であるかを
設定するために使用します。
本キーワードは省略可能であり、デフォルトは
.Em inout
です。
.Pp
現在サポートされているパラメータは次の通りです:
.Pp
.Bl -tag -width Ds -compact -offset
.It Ar inout
通常動作。接続の確立は、リモートからでもローカルからでも可能です。
.It Ar in
着信接続のみ可能です。
.It Ar out
発信接続のみ可能です。
.El

.It Li downtries
失敗する試行回数を指定するために使用します。
試行 (=再試行サイクルです!) がこの回数だけ失敗すると、
インタフェースを (
.Em downtime
秒だけ) 無効にします。
(詳細はキーワード
.Em usedown
を参照)。本キーワードは省略可能です。

.It Li downtime
.Em downtries
の設定値の回数の後、
インタフェースが無効化される秒数を設定するために使用されます。
(詳細はキーワード
.Em usedown
を参照)。
本キーワードは省略可能であり、デフォルトで 60 秒に設定されます。

.It Li earlyhangup
次の課金単位となる前に接続を切るための (保険の) 秒数を指定します。
(省略可能)

.It Li idletime-outgoing
接続を切る前に発呼 (outgoing call) がアイドルとなる秒数。(省略可能)

.It Li idletime-incoming
接続を切る前に着呼がアイドルとなる秒数。(省略可能)

.It Li isdncontroller
本エントリの接続に使用される ISDN コントローラ番号。(必須)

.It Li isdnchannel
本エントリの接続に対して使用される ISDN コントローラチャネル番号。
ここで明示的にチャネルを選択すると
SETUP メッセージはそのチャネルを要求しますが、
リクエストに
.Em 望ましい (preferred)
(指定チャネルを望む) とマークするだけであって、
排他的 (指定チャネルのみ受け付ける) とマークするのではありません。
よって、交換局は要求されたチャネル以外を選択することが依然として可能です!
(必須)

.It Li isdntxdel-incoming
.Em timeout()
カーネルサブルーチンに適合する遅延値であり、
.Em 着信
ISDN 接続に対して接続確立が成功した後に、
最初のパケットの送出をこの値だけ遅延させます。
指定単位は 1/100 秒です。
ゼロ (0) を指定すると本機能を無効化します。これがデフォルト値です。
本機能は
.Xr i4bipr 4
IP over raw HDLC ISDN ドライバ用に実装されました
(本ドライバに対してのみ意味を持ちます)。(省略可能)

.It Li isdntxdel-outgoing
.Em timeout()
カーネルサブルーチンに適合する遅延値であり、
.Em 発信
ISDN 接続に対して接続確立が成功した後に、
最初のパケットの送出をこの値だけ遅延させます。
指定単位は 1/100 秒です。
ゼロ (0) を指定すると本機能を無効化します。これがデフォルト値です。
本機能は
.Xr i4bipr 4
IP over raw HDLC ISDN ドライバ用に実装されました
(本ドライバに対してのみ意味を持ちます)。(省略可能)

.It Li local-phone-dialout
ローカルサイトからダイヤルアウトする場合に使用される、ローカルの電話番号。
リモートサイトに対してダイヤルアウトするとき、
ここで指定した番号が
.Em "発番号情報要素 (Calling Party Number Information Element)"
に埋め込まれます。
.Pp
本キーワードは、ipr ユーザランドインタフェースのために必須です。
.\" 原文の .em (Execute Macro) は、引数無しの場合効果が無いので削除
.\" horikawa@jp.freebsd.org 1999/01/19

.It Li local-phone-incoming
着呼の宛先を確認するために使用する、ローカルの電話番号です。
リモートサイトがダイヤルインするとき、
リモートサイトの希望接続先がローカルサイトであることを確認するために、
本番号を使用します。
この値は、電話交換局から得られる
.Em "着番号情報要素 (Called Party Number Information Element)"
と比較されます。
.Pp
本キーワードは ipr インタフェースのために必須です。

.It Li name
その設定エントリにシンボルによる名前を定義します。
全画面表示においてこの名前を使用して
リモートサイトへのリンクを識別しやすくすることと、
アカウンティングに使用することを目的としています。(必須)

.It Li ratetype
料金ファイル中の、使用する料金エントリ。(省略可能)
.br
例えば、
ratetype=0 は /etc/isdn/isdnd.rates 中で "ra0" で開始する行を選択します
(典型的には ra0 行は、
各曜日および各時刻における、ローカルの呼び出し料金の表集合です。)

.It Li recoverytime
ダイヤル再試行とダイヤル再試行の間に待つ秒数。(省略可能)

.It Li remdial-handling
複数個の発信番号が指定された場合のダイヤルアウト動作を指定するために
使用されます。
現在サポートされているパラメータは次の通りです:
.Pp
.Bl -tag -width Ds -compact -offset
.It Ar first
新規 (非再試行) 呼設定 (call setup) の度に、最初の番号から開始します。
.It Ar last
新規 (非再試行) 呼設定の度に、
接続確立が成功した最後の番号から開始します。
.It Ar next
新規 (非再試行) 呼設定の度に、
最後に使用したものの次の番号から開始します。
.El

.It Li remote-phone-dialout
ローカルサイトからダイヤルアウトする場合に使用される、リモートの電話番号。
リモートサイトに対してダイヤルアウトするとき、
ここで指定した番号が
.Em "着番号情報要素 (Called Party Number Information Element)"
に埋め込まれます。
.Pp
本キーワードは、ipr インタフェースのために必須です。
.\" 原文の .em (Execute Macro) は、引数無しの場合効果が無いので削除
.\" horikawa@jp.freebsd.org 1999/01/19
複数回指定して、
どれかひとつが成功するまでいくつかの番号に対して試行させることもできます。

.It Li remote-phone-incoming
着呼を確認するために使用する、リモートの電話番号です。
リモートサイトがダイヤルインするとき、
ローカルシステムに対して接続する権限がある
正しいリモートサイトであることを確認するために、
本番号を使用します。
この値は、電話交換局から得られる
.Em "発番号情報要素 (Calling Party Number Information Element)"
と比較されます。
.Pp
本キーワードは ipr インタフェースのために必須です。
.Pp
本キーワードにワイルドカードパラメータ '*' を渡して、
誰もがダイヤルイン可能とできます。

.It Li unitlength
秒数による課金単位の長さ。
アイドル時間とともに使用して、いつ接続を切るのかを決定します。
(省略可能)

.It Li unitlengthsrc
本キーワードは、ショートホールドモードにおいて
.Xr isdnd 8
がどこから unitlength を取得するかを指定します。
現在設定可能な値は次の通りです:
.Pp
.Bl -tag -width Ds -compact -offset
.It Ar none
unitlength は、どこにも指定されません。
.It Ar cmdl
コマンドラインで指定される unitlength を使用します。
.It Ar conf
設定ファイルでキーワード
.Em unitlength
で指定される unitlength を使用します。
.It Ar rate
設定ファイルにおいてキーワード
.Em ratetype
で指定される料金ファイル中の unitlength を使用します。
.It Ar aocd
ISDN 回線において AOCD を申し込んでいる場合、
動的に計算される unitlength を使用します。
(AOCD は ```Advice Of Charge During the call (呼の間の課金アドバイス)''
の頭文字で、遠距離通信 (すなわち電話) 業者が提供する、
課金単位を示すサービスです)。
.El

.It Li usrdevicename
ISDN B チャネルデータをユーザランドにインタフェースするために使用する、
ユーザランドインタフェースを指定します。
本キーワードは必須です。
本キーワードは次のパラメータを受け付けます:
.Pp
.Bl -tag -width Ds -compact -offset
.It Ar ipr
本パラメータは raw HDLC IP over ISDN インタフェースを設定します。
.It Ar isp
本パラメータは shyncronous PPP over ISDN インタフェースを設定します。
.It Ar rbch
本パラメータは Raw B CHannel アクセスインタフェースを設定します。
.It Ar tel
ISDN 電話通信。
.El

.It Li usrdeviceunit
usrdevicename が指定するデバイスの、ユニット番号を指定します。
.\" 原文の .em (Execute Macro) は、引数無しの場合効果が無いので削除
.\" horikawa@jp.freebsd.org 1999/01/19
.\" 文法もちょっとヘンですね。
.\" Specifies the unit number for the with the
.\" .em
.\" usrdevicename
.\" specified device.

.It Li usedown
エントリセクションにおいて、キーワード
.Em downtries
と
.Em downtime
を有効にするために使用します。
(回線ビジーの場合等) 遷移に失敗する場合に、
過度のダイヤル動作を避けるために、
.Nm isdnd
が IP インタフェースの有効・無効を動的に切り替えるために使用します。
本パラメータは省略可能であり、デフォルトで
.Em off
に設定されます。

.It Li connectprog
接続が確立してアドレス交渉が完了した後 (すなわち接続を使用可能となった後)、
毎回実行するプログラムを指定します。
.Nm isdnd
は、パス
.Pa /etc/isdn
以下でプログラムを見付けられるものと期待します。
このパスは、本キーワードのパラメータとして指定された文字列の前に付けられます。
(省略可能)

.It Li disconnectprog
接続がシャットダウンされた後、毎回実行するプログラムを指定します。
.Nm isdnd
は、パス
.Pa /etc/isdn
以下でプログラムを見付けられるものと期待します。
このパスは、本キーワードのパラメータとして指定された文字列の前に付けられます。
(省略可能)

.El
.El

.Sh アイドル時間の計算とショートホールドモード
.Bl -tag -width incoming calls -compact
.It Li 着呼
呼び出し側が課金構造などのほとんどを知っているものと見なすので、キーワード
.Em idletime-incoming
のみが着呼に機能します。
.Pp
着呼に対しては回線は定常的に監視され、
.Em idletime-incoming
で指定する秒数の期間トラフィックが無い場合には、呼は閉じられます。
.Pp
典型的には、
.Em idletime-incoming
は最終手段として使用するため、課金単位時間よりもずっと大きな値を設定します。
典型的な値は 1 〜 5 分です。

.It Li 発呼
発呼の切断時間を、2 種類の方法のいずれかに設定可能です:

.Bl -tag -width shorthold mode -compact
.It Li 単純モード
単純なモードであり、
.Em unitlength
の選択値は 0 (ゼロ) であり
.Em idletime-outgoing
は 0 より大きいことが必要です。
.Pp
送信のトラフィックは定常的に監視され、
.Em idletime-outgoing
で指定された秒数だけトラフィックが無かった場合、呼は閉じられます。
.Pp
単純なモードの典型値は 10 〜 30 秒です。

.It Li ショートホールドモード
ショートホールドモードでは、
.Em unitlength 
と
.Em idletime-outgoing
の選択値は 0 (ゼロ) より大きいことが必要であり、
.Em earlyhangup は 0 (ゼロ) 以上であることが必要です
。

.Bd -literal

|<unchecked window>|<checkwindow>|<safetywindow>|
|                  |             |              |
+------------------+-------------+--------------+
|                  |             |              |
|                  |<-idle-time->|<earlyhangup->|
|<--------------unitlength--------------------->|

.Ed

チェック対象外ウィンドウ (uncheked window) は、
(unitlength - (idle-time + earlyhangup)) の長さであり、
この間アイドルチェックはされません。
チェック対象外ウィンドウが終ると、idle-time の期間、
回線にトラフィックが無いかチェックされます。
チェックウィンドウ (check-window) の期間にトラフィックが検出された場合、
次の単位 (unit) の先頭から同じ手続きが再度開始されます。
チェックウィンドウの期間トラフィックが検出されない場合、
チェックウィンドウ終了時に回線が閉じられます、
.Pp
注:
.Em unitlength
は
.Em idletime-outgoing
と
.Em earlyhangup
の合計よりも大きいことが必要 (!) です!

.El
.El

.Pp
.Sh 関連ファイル
.Bl -tag -width /etc/isdn/isdnd.rc -compact
.It Pa /etc/isdn/isdnd.rc
.Nm isdnd
ISDN デーモンのデフォルトの設定ファイル。

.Sh 関連項目
.Xr isdnd 8
.Xr isdnmonitor 8
.Xr regex 3
.Xr re_format 7

.Sh 作者
.Xr isdnd 8
デーモンと本マニュアルページは Hellmuth Michaelis が書きました。
彼の連絡先は、hm@kts.org です。
