# $FreeBSD$
MAN5 =	a.out.5\
	acct.5\
	aliases.5\
	amd.conf.5\
	auth.conf.5\
	bootparams.5\
	bootptab.5\
	core.5\
	crontab.5\
	ctm.5\
	cvs.5\
	devd.conf.5\
	devfs.5\
	device.hints.5\
	dhclient.conf.5\
	dhclient.leases.5\
	dhcp-eval.5\
	dhcp-options.5\
	dir.5\
	disktab.5\
	drivers.conf.5\
	editrc.5\
	elf.5\
	ethers.5\
	exports.5\
	fbtab.5\
	fdescfs.5\
	finger.conf.5\
	forward.5\
	fs.5\
	fstab.5\
	ftpchroot.5\
	gettytab.5\
	groff_font.5\
	groff_out.5\
	groff_tmac.5\
	group.5\
	hosts.5\
	hosts.equiv.5\
	hosts.lpd.5\
	hosts_access.5\
	hosts_options.5\
	info.5\
	intro.5\
	ipf.5\
	ipnat.5\
	ipsend.5\
	isdnd.acct.5\
	isdnd.rates.5\
	isdnd.rc.5\
	kbdmap.5\
	keycap.5\
	link.5\
	linprocfs.5\
	loader.conf.5\
	login.access.5\
	login.conf.5\
	magic.5\
	mailer.conf.5\
	make.conf.5\
	motd.5\
	msdosfs.5\
	named.conf.5\
	netconfig.5\
	netgroup.5\
	netid.5\
	networks.5\
	nologin.5\
	ntp.conf.5\
	ntp.keys.5\
	opieaccess.5\
	opiekeys.5\
	passwd.5\
	pbm.5\
	pccard.conf.5\
	periodic.conf.5\
	phones.5\
	printcap.5\
	procfs.5\
	protocols.5\
	publickey.5\
	pw.conf.5\
	radius.conf.5\
	rc.conf.5\
	rcsfile.5\
	remote.5\
	resolver.5\
	rpc.5\
	rrenumd.conf.5\
	rtadvd.conf.5\
	services.5\
	shells.5\
	ssh_config.5\
	sshd_config.5\
	stab.5\
	sysctl.conf.5\
	syslog.conf.5\
	tacplus.conf.5\
	term.5\
	termcap.5\
	terminfo.5\
	texinfo.5\
	ttys.5\
	tzfile.5\
	usbd.conf.5\
	utmp.5\
	uuencode.format.5\
	vgrindefs.5

MLINKS+=kbdmap.5 keymap.5
MLINKS+=utmp.5 lastlog.5 utmp.5 wtmp.5
MLINKS+=hosts.equiv.5 rhosts.5
MLINKS+=uuencode.format.5 uuencode.5
MLINKS+=resolver.5 resolv.conf.5
MLINKS+=fs.5 inode.5
MLINKS+=dir.5 dirent.5
MLINKS+=groff_tmac.5 tmac.5
MLINKS+=ipnat.5 ipnat.conf.5
MLINKS+=passwd.5 master.passwd.5
MLINKS+=msdosfs.5 msdos.5

.include "bsd.prog.mk"
