# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/man/man1/Makefile,v 1.125 2007/11/20 06:53:29 ru Exp $

MAN=	apply.1 \
	apropos.1 \
	basename.1 \
	biff.1 \
	brandelf.1 \
	bsdiff.1 \
	bspatch.1 \
	builtin.1 \
	c89.1 \
	c99.1 \
	cat.1 \
	chgrp.1 \
	chkey.1 \
	ckdist.1 \
	cmp.1 \
	colrm.1 \
	column.1 \
	comm.1 \
	cp.1 \
	crontab.1 \
	cut.1 \
	df.1 \
	domainname.1 \
	du.1 \
	echo.1 \
	enigma.1 \
	expand.1 \
	expr.1 \
	false.1 \
	fdformat.1 \
	file2c.1 \
	find.1 \
	finger.1 \
	fold.1 \
	from.1 \
	fsync.1 \
	gcore.1 \
	groups.1 \
	head.1 \
	hostname.1 \
	id.1 \
	intro.1 \
	ipcrm.1 \
	ipcs.1 \
	join.1 \
	kbdmap.1 \
	kenv.1 \
	keylogin.1 \
	keylogout.1 \
	kill.1 \
	killall.1 \
	ldd.1 \
	ln.1 \
	locale.1 \
	lock.1 \
	lockf.1 \
	logins.1 \
	logname.1 \
	look.1 \
	lorder.1 \
	lsvfs.1 \
	makewhatis.1 \
	man.1 \
	manpath.1 \
	minigzip.1 \
	mkdir.1 \
	mkfifo.1 \
	mkstr.1 \
	mptable.1 \
	mv.1 \
	ncplist.1 \
	ncplogin.1 \
	ncplogout.1 \
	newgrp.1 \
	nfsstat.1 \
	nice.1 \
	nohup.1 \
	od.1 \
	pagesize.1 \
	passwd.1 \
	pkg_info.1 \
	pkill.1 \
	printenv.1 \
	pwd.1 \
	rcp.1 \
	realpath.1 \
	rev.1 \
	rm.1 \
	rmdir.1 \
	rup.1 \
	ruptime.1 \
	rusers.1 \
	rwall.1 \
	rwho.1 \
	script.1 \
	sh.1 \
	shar.1 \
	sleep.1 \
	split.1 \
	tail.1 \
	talk.1 \
	tcopy.1 \
	tee.1 \
	test.1 \
	tftp.1 \
	time.1 \
	true.1 \
	truncate.1 \
	truss.1 \
	tsort.1 \
	tty.1 \
	ul.1 \
	uname.1 \
	uniq.1 \
	unvis.1 \
	uptime.1 \
	users.1 \
	vidcontrol.1 \
	vis.1 \
	w.1 \
	wall.1 \
	wc.1 \
	what.1 \
	which.1 \
	who.1 \
	whoami.1 \
	write.1 \
	xstr.1 \
	yes.1 \
	ypmatch.1 \
	ypwhich.1

MLINKS+= apropos.1 whatis.1
MLINKS+= basename.1 dirname.1
MLINKS+= builtin.1 alias.1 \
	builtin.1 alloc.1 \
	builtin.1 bg.1 \
	builtin.1 bind.1 \
	builtin.1 bindkey.1 \
	builtin.1 break.1 \
	builtin.1 breaksw.1 \
	builtin.1 builtins.1 \
	builtin.1 case.1 \
	builtin.1 cd.1 \
	builtin.1 chdir.1 \
	builtin.1 command.1 \
	builtin.1 complete.1 \
	builtin.1 continue.1 \
	builtin.1 default.1 \
	builtin.1 dirs.1 \
	builtin.1 do.1 \
	builtin.1 done.1 \
	builtin.1 echotc.1 \
	builtin.1 elif.1 \
	builtin.1 else.1 \
	builtin.1 end.1 \
	builtin.1 endif.1 \
	builtin.1 endsw.1 \
	builtin.1 esac.1 \
	builtin.1 eval.1 \
	builtin.1 exec.1 \
	builtin.1 exit.1 \
	builtin.1 export.1 \
	builtin.1 fc.1 \
	builtin.1 fg.1 \
	builtin.1 fi.1 \
	builtin.1 filetest.1 \
	builtin.1 for.1 \
	builtin.1 foreach.1 \
	builtin.1 getopts.1 \
	builtin.1 glob.1 \
	builtin.1 goto.1 \
	builtin.1 hash.1 \
	builtin.1 hashstat.1 \
	builtin.1 history.1 \
	builtin.1 hup.1 \
	builtin.1 if.1 \
	builtin.1 jobid.1 \
	builtin.1 jobs.1 \
	builtin.1 limit.1 \
	builtin.1 log.1 \
	builtin.1 logout.1 \
	builtin.1 ls-F.1 \
	builtin.1 notify.1 \
	builtin.1 onintr.1 \
	builtin.1 popd.1 \
	builtin.1 pushd.1 \
	builtin.1 read.1 \
	builtin.1 readonly.1 \
	builtin.1 rehash.1 \
	builtin.1 repeat.1 \
	builtin.1 sched.1 \
	builtin.1 set.1 \
	builtin.1 setenv.1 \
	builtin.1 settc.1 \
	builtin.1 setty.1 \
	builtin.1 setvar.1 \
	builtin.1 shift.1 \
	builtin.1 source.1 \
	builtin.1 stop.1 \
	builtin.1 suspend.1 \
	builtin.1 switch.1 \
	builtin.1 telltc.1 \
	builtin.1 then.1 \
	builtin.1 times.1 \
	builtin.1 trap.1 \
	builtin.1 type.1 \
	builtin.1 ulimit.1 \
	builtin.1 umask.1 \
	builtin.1 unalias.1 \
	builtin.1 uncomplete.1 \
	builtin.1 unhash.1 \
	builtin.1 unlimit.1 \
	builtin.1 unset.1 \
	builtin.1 unsetenv.1 \
	builtin.1 until.1 \
	builtin.1 wait.1 \
	builtin.1 where.1 \
	builtin.1 while.1
MLINKS+= enigma.1 crypt.1
MLINKS+= expand.1 unexpand.1
MLINKS+= kbdmap.1 vidfont.1
MLINKS+= ln.1 link.1
MLINKS+= passwd.1 yppasswd.1
MLINKS+= pkill.1 pgrep.1
MLINKS+= rm.1 unlink.1
MLINKS+= test.1 [.1

.include <bsd.prog.mk>
