.\" %FreeBSD: src/usr.bin/ncplogin/ncplogout.1,v 1.11 2007/01/15 15:25:15 ru Exp %
.\" $FreeBSDru: frdp/doc/ru_RU.KOI8-R/man/man1/ncplogout.1,v 1.2 2007/01/15 16:03:49 ru Exp $
.\" $FreeBSD$
.Dd 15 сентября 1999
.Dt NCPLOGOUT 1
.Os
.Sh НАЗВАНИЕ
.Nm ncplogout
.Nd планирует закрытие постоянного подключения
.Sh СИНТАКСИС
.Nm
.Op Fl S Ar сервер
.Op Fl U Ar пользователь
.Op Fl c Ar идентификатор
.Nm
.Op Fl c Ar идентификатор
.No / Ns Ar сервер Ns : Ns Ar пользователь
.Sh ОПИСАНИЕ
Утилита
.Nm
планирует закрытие подключения, созданного программой
.Xr ncplogin 1 .
Если подключение занято (всё ещё используется другими процессами),
то оно будет закрыто по завершению последнего процесса,
использующего это подключение.
Данная программа аналогична утилите
.Pa logout.exe
для
.Tn DOS .
.Pp
Имеются следующие опции:
.Bl -tag -width indent
.It Fl S Ar сервер
Задаёт имя сервера
.Tn Netware ,
подключение к которому должно быть разорвано.
Можно не указывать, если существует только одно активное подключение.
.It Fl U Ar пользователь
Задаёт имя пользователя, используемое для определения подключения.
Можно не указывать, если существует только одно активное подключение.
.It Fl c Ar идентификатор
Закрывает подключение, соответствующее указанному идентификатору.
Список имеющихся идентификаторов подключений можно получить
с помощью такой команды:
.Pp
.Dl "ncplist c"
.El
.Sh ИСТОРИЯ
Утилита
.Nm
впервые появилась во
.Fx 4.0 .
.Sh АВТОРЫ
.An Борис Попов Aq bp@butya.kz ,
.Aq bp@FreeBSD.org
.Sh ПРОБЛЕМЫ
Пожалуйста, сообщайте обо всех ошибках автору.
