=== FreeBSD Foundation

Contact: Deb Goodkin <deb@FreeBSDFoundation.org>

The FreeBSD Foundation is a 501(c)(3) non-profit organization dedicated to supporting and promoting the FreeBSD Project and community worldwide.
Funding comes from individual and corporate donations and is used to fund and manage software development projects, conferences and developer summits, and provide travel grants to FreeBSD contributors.
The Foundation purchases and supports hardware to improve and maintain FreeBSD infrastructure and provides resources to improve security, quality assurance, and software engineering efforts; publishes marketing material to promote, educate, and advocate for the FreeBSD Project; facilitates collaboration between commercial vendors and FreeBSD developers; and finally, represents the FreeBSD Project in executing contracts, license agreements, and other legal arrangements that require a recognized legal entity.

Here are some highlights of what we did to help FreeBSD last quarter:

==== COVID-19 Impact to the Foundation

Like most organizations, our team continued to work from home.
Our temporary ban on travel for staff members remains in effect, but continues to not affect our output too much, since most conferences are still virtual.
As the world continues to open up we will re-evaluate the travel ban.
We continued supporting the community and Project through our regular channels.

==== Partnerships and Commercial User Support

We help facilitate collaboration between commercial users and FreeBSD developers.
We also meet with companies to discuss their needs and bring that information back to the Project.
Our temporary travel ban stayed in effect during Q2, so we continued meeting with corporate users virtually.
If things look good for in-person meetings in the fall, then we'll start incorporating those into an in-person and virtual meeting mix.

==== Fundraising Efforts

First, we’d like to say thank you to everyone who has given us a financial contribution this year!
Last quarter we raised $70,410, which includes donations from organizations like Verisign, VMware, and Stormshield, as well as many individuals.

We depend on these donations to fund our work supporting FreeBSD.
Late last year we decided to put more funding into helping to improve FreeBSD.
We hired a Sr. Software Developer to work on arm64 and a Project Coordinator to manage our projects and interface with the community.
We also hired two of our part-time software developers full-time.
The purpose of this was to provide more resources to step in to implement and improve major features in FreeBSD, review patches and bug reports, implement bug fixes, and support the security efforts.
This ensures FreeBSD remains the innovative, secure, and reliable operating system that you rely on.

You’ll find out how we used your donations for Q2 in our report, as well as individual reports throughout this status report.

We are excited about our plans for 2021, which include more FreeBSD online advocacy and training, operating system course content, and the software development work mentioned above.
While we are still in this pandemic, we’re working hard to help connect folks within the community with more virtual opportunities.

Please consider making a donation to help us continue and increase our support for FreeBSD in 2021: link:https://www.freebsdfoundation.org/donate/[https://www.freebsdfoundation.org/donate/].

We also have the Partnership Program, to provide more benefits for our larger commercial donors.
Find out more information and share with your companies! link:https://www.freebsdfoundation.org/FreeBSD-foundation-partnership-program/[https://www.freebsdfoundation.org/FreeBSD-foundation-partnership-program/]

==== OS Improvements

During the second quarter Foundation staff and grant recipients committed 348 src tree changes, 19 ports tree changes, and 11 doc tree changes.
This represents 40% of src commits which identify a sponsor.
For ports commits it's 15%, and 18% of doc commits.
Foundation staff and grant recipients also contributed to a number of 3rd party projects.
Two notable examples are the LLVM project's LLDB debugger and the Syzkaller code-coverage-guided system call fuzzer.

You can read about a number of Foundation projects in individual quarterly reports.
Smaller projects and improvements include:

* Implement on-demand coredump generation by the kernel via `ptrace(PT_COREDUMP)`
* General kernel debugging improvements
* Remove obsolete kernel mcount profiling
* Nullfs and tmpfs bug fixes
* libc cleanup and improvements
* rtld dlerror and thread local variable fixes (reported by Julia developers)
* kqueue and POSIX timer fixes
* UFS bug fixes
* Capsicum socket operation improvements
* hwpmc (hardware performance profiling) maintenance and CPU support
* Cirrus-CI boot smoke test
* sndstat(4) link:https://cgit.freebsd.org/src/commit/?id=4ce1ba6523839b5c88331de22937b1e0483fc40b[schema updates]
* AMD PCI passthrough fixes in vmm(4), see: link:https://cgit.freebsd.org/src/commit/?id=9d7eb557c1574f879b4bb4adee285cc9f2d5f18e[commit 1],  link:https://cgit.freebsd.org/src/commit/?id=6fe60f1d5c39c94fc87534e9dd4e9630594e0bec[commit 2] and link:https://reviews.freebsd.org/D30827[review]
* link:https://reviews.freebsd.org/D29708[Virtio 1.0 modern support] in bhyve(8)

As usual Foundation staff also supported the project with significant effort on code reviews and general bug triage and fixes.
Also, Ka Ho added an article titled https://docs.freebsd.org/en/articles/freebsd-src-lsp/[Use Language Servers for Development in the FreeBSD Src Tree].

==== Continuous Integration and Quality Assurance

The Foundation provides a full-time staff member and funds projects on improving continuous integration, automated testing, and overall quality assurance efforts for the FreeBSD project.

During the second quarter of 2021, work on pre-commit tests and building release artifacts in the CI environment continued.
A project using the netperf cluster to do network-related CI jobs is being planned.

See the FreeBSD CI section of this report for completed work items and detailed information.

==== Supporting FreeBSD Infrastructure

The Foundation provides hardware and support to improve the FreeBSD infrastructure.
Last quarter, we supported the test cluster at Sentex, purchased a few needed parts for infrastructure in general, and started working with the clusteradm team on a more efficient and improved hardware request/purchase process.

==== FreeBSD Advocacy and Education

A large part of our efforts are dedicated to advocating for the Project.
This includes promoting work being done by others with FreeBSD; producing advocacy literature to teach people about FreeBSD and help make the path to starting using FreeBSD or contributing to the Project easier; and attending and getting other FreeBSD contributors to volunteer to run FreeBSD events, staff FreeBSD tables, and give FreeBSD presentations.

The FreeBSD Foundation sponsors many conferences, events, and summits around the globe.
These events can be BSD-related, open source, or technology events geared towards underrepresented groups.
We support the FreeBSD-focused events to help provide a venue for sharing knowledge, to work together on projects, and to facilitate collaboration between developers and commercial users.
This all helps provide a healthy ecosystem.
We support the non-FreeBSD events to promote and raise awareness of FreeBSD, to increase the use of FreeBSD in different applications, and to recruit more contributors to the Project.
While we were still unable to attend in-person meetings due to Covid-19, we were able to attend virtual events and help organize the June 2021 FreeBSD Developer Summit.
In addition to attending and planning virtual events, we are continually working on new training initiatives and updating our selection of how-to guides to facilitate getting more folks to try out FreeBSD.

Check out some of the advocacy and education work we did last quarter:

* Participated as an Industry Partner for USENIX LISA21
* Held two new FreeBSD Fridays: link:https://youtu.be/IOUr7Is5FSU[Introduction to BastilleBSD] and link:https://youtu.be/6fwfRoDt9bQ[How to Submit a Patch to FreeBSD].
* Organized content and promoted FreeBSD Day on June 18-19, 2021
* Helped organize and run the June 2021 FreeBSD Developer Summit - videos are now posted on the link:https://wiki.freebsd.org/DevSummit/202106[wiki].
* Presented at the The 16th Open Source China Open Source World Summit on June 18
* New blog posts on the Linxulator work we funded and What’s new in FreeBSD 13.0
* New How To Guide on Git
* Continued to promote the FreeBSD Office Hours series Videos from the one hour sessions can be found on the Project’s link:https://www.youtube.com/c/FreeBSDProject[YouTube Channel].  See the Office Hours section of this report for more information.
* Committed to be a Silver Sponsor for EuroBSDcon

Keep up to date with our latest work in our newsletters: link:https://www.freebsdfoundation.org/news-and-events/newsletter/[https://www.freebsdfoundation.org/news-and-events/newsletter/]

We help educate the world about FreeBSD by publishing the professionally produced FreeBSD Journal.
As we mentioned previously, the FreeBSD Journal is now a free publication.
Find out more and access the latest issues at link:https://www.FreeBSDfoundation.org/journal/[https://www.FreeBSDfoundation.org/journal/].

You can find out more about events we attended and upcoming events at link:https://www.FreeBSDfoundation.org/news-and-events/[https://www.FreeBSDfoundation.org/news-and-events/].

==== Legal/FreeBSD IP

The Foundation owns the FreeBSD trademarks, and it is our responsibility to protect them.
We also provide legal support for the core team to investigate questions that arise.

Go to link:https://www.FreeBSDfoundation.org[https://www.FreeBSDfoundation.org] to find out how we support FreeBSD and how we can help you!
