=== helloSystem

Links: +
link:https://hellosystem.github.io/docs/[Documentation] URL: link:https://hellosystem.github.io/[https://hellosystem.github.io/]

Contact: Simon Peter <probono@puredarwin.org> +
Contact: `\#helloSystem` on `irc.libera.chat`, mirrored to link:https://matrix.to/#/%23helloSystem:matrix.org?via=matrix.org[`#helloSystem:matrix.org` on Matrix]

==== What is helloSystem?

helloSystem is FreeBSD preconfigured as a desktop operating system with a focus on simplicity, elegance, and usability.
Its design follows the “Less, but better” philosophy.

==== Q2 2021 Status

* Version 0.5.0 of helloSystem has been published. Installable Live ISO images are available. Download and changelog are at https://github.com/helloSystem/ISO/releases/tag/r0.5.0
* helloSystem was part of the Desktop panel at the FreeBSD Developer Summit 2021. A video is available at https://www.youtube.com/watch?v=3SUKJye54aI&t=11410s
* Work has started towards 0.6.0. Thanks for contributed features and bugfixes
** Improved spatial file manager
** Switch to KWin (if its dependencies can be reduced significantly for use outside of KDE Plasma)

Experimental and release builds of the Live ISO are available at https://github.com/helloSystem/ISO/releases.

==== Contributing

link:https://github.com/helloSystem/hello/blob/master/CONTRIBUTING.md[Help is wanted in a number of areas], especially in the areas of the FreeBSD core OS and kernel, and Qt/C++.
