=== Intel Wireless driver support

Links: +
link:https://wiki.freebsd.org/WiFi/Iwlwifi[iwlwifi status FreeBSD wiki page] URL: link:https://wiki.freebsd.org/WiFi/Iwlwifi[https://wiki.freebsd.org/WiFi/Iwlwifi]

The Intel Wireless driver update project aims to bring support for newer chipsets along with mac80211 LinuxKPI compat code.
The dual-licensed Intel driver code was ported in the past for the iwm(4) native driver and using the LinuxKPI compat framework allows us to use the driver directly with only very minor modifications.
Multiple updates during development in the last year have shown that pulling in newer versions can be done in under 1-2 hours.

After a break, part-time work resumed and the last LinuxKPI conflicts got resolved and most of the other LinuxKPI changes were committed to FreeBSD main.

During the update process firmware crashes were unxpectedly encountered which got solved and the 802.11 compat code improved.
The iwlwifi driver and firmware got updated from the iwlwifi-next git branch and the linux-firmware repository.

Integration into FreeBSD main is pending for a policy reason.
For the latest state of the development or code, please follow the referenced wiki page or the freebsd-wireless mailing list.

I would love to thank everyone who has reviewed changes, did initial testing, helped with drm-kmod, helped in various other ways, answered questions, encouraged, or patiently waited for any results or running code.

Sponsor: The FreeBSD Foundation
