=== Containers & FreeBSD: Pot, Potluck & Potman

Links: +
link:https://pot.pizzamig.dev[Pot on github] URL: link:https://github.com/pizzamig/pot[https://github.com/pizzamig/pot] +
link:https://potluck.honeyguide.net/[Potluck Repository & Project] URL: link:https://potluck.honeyguide.net/[https://potluck.honeyguide.net/] +
link:https://github.com/hny-gd/potluck[Potluck on github] URL: link:https://github.com/hny-gd/potluck[https://github.com/hny-gd/potluck] +
link:https://github.com/grembo/potman[Potman on github] URL: link:https://github.com/grembo/potman[https://github.com/grembo/potman]

Contact: Luca Pizzamiglio (Pot) <pizzamig@freebsd.org> +
Contact: Stephan Lichtenauer (Potluck) <sl@honeyguide.eu> +
Contact: Michael Gmelin (Potman) <grembo@FreeBSD.org>

Pot is a jail management tool that link:https://www.freebsd.org/news/status/report-2020-01-2020-03/#pot-and-the-nomad-pot-driver[also supports orchestration through Nomad].

In the last quarter, link:https://github.com/pizzamig/pot/releases/tag/0.12.0[v0.12.0] was released and many new improvements have been worked on since then. The main new feature under development at the moment is the possibility to link:https://github.com/pizzamig/pot/issues/148[create layered pot images] for e.g. quickly adding applications in a build pipeline to a bigger base image which can then be deployed via Ansible or Nomad.

Potluck aims to be to FreeBSD and Pot what Dockerhub is to Linux and Docker: A repository of Pot flavours and complete images for usage with Pot and in many cases Nomad.

Here, all images have been built for FreeBSD 13.0 for the first time, FreeBSD 11.4 support has been removed and 12.2 images have been upgraded to latest package versions. Furthermore, new images like a link:https://potluck.honeyguide.net/blog/postgresql-patroni/[PostgreSQL Patroni cluster] have been added or the link:https://potluck.honeyguide.net/blog/nomad-server/[Nomad] and link:https://potluck.honeyguide.net/blog/consul/[Consul] images have been extended to support clustering, encryption and a new link:https://potluck.honeyguide.net/blog/vault/[Vault] image.

Also, a link:https://honeyguide.eu/posts/potluck-containerd-poc/[PoC has been done] which shows that Potluck images can potentially easily be used with containerd and link:https://github.com/samuelkarp/runj[runj].

Potman aims to simplify building Pot images with Vagrant and VirtualBox based on the Potluck approach, e.g. as part of a DevOps workflow for software development including testing and publishing them to a repository.

Here, in the last quarter, usage and documentation has been improved.

Future plans include finishing the layered Pot images, further Potman workflow features and more new and improved Potluck images.

As always, feedback and patches are welcome.
