# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	beastie.png
DATA+=	blt_gry_arrow.png
DATA+=	blt_red_arrow.png
DATA+=	front_get_back.png
DATA+=	front_get_bl.png
DATA+=	front_get_br.png
DATA+=	front_get_tl.png
DATA+=	front_get_tr.png
DATA+=	front_new_back.png
DATA+=	front_new_bl.png
DATA+=	front_new_br.png
DATA+=	front_new_tl.png
DATA+=	front_new_tr.png
DATA+=	hdr_fill.png
DATA+=	ico_rss.png
DATA+=	logo.png
DATA+=	logo-red.png
DATA+=	nav_rgt.png
DATA+=	nav_tbl_btm.png
DATA+=	nav_tbl_top.png

.include "${DOC_PREFIX}/share/mk/web.site.mk"
