# $FreeBSD$

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=	beastie.png
DATA+=	blt_gry_arrow.png
DATA+=	blt_red_arrow.png
DATA+=	hdr_fill.png
DATA+=	ico_rss.png
DATA+=	logo.png
DATA+=	logo-red.png
DATA+=	nav_rgt.png
DATA+=	nav_tbl_btm.png
DATA+=	nav_tbl_top.png
DATA+=	25thanniversary.png

.include "${DOC_PREFIX}/share/mk/web.site.mk"
