#
# Web site build hooks for the release notes.  Also see the README file.
#
# The variable RELNOTES (I couldn't think of a better name) is a poor
# man's list.  Its semantics are very similar to that of MLINKS (see
# bsd.man.mk).  The first word is the directory under which that set
# of relnotes should appear on the web site.  The second word is the
# path to that relnotes set.
#
# $FreeBSD$
# Original Revision: 1.5
#
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

.include "${DOC_PREFIX}/en_US.ISO8859-1/htdocs/relnotes/Makefile.inc"
