#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/gnome/docs/Makefile,v 1.2 2004/02/21 16:36:21 andy Exp $
#
# Original revision: 1.13
#

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	faq2.xml
DOCS+=	gnome_porting.xml
DOCS+=	gnome1_porting.xml
DOCS+=	gnome2_porting.xml
DOCS+=	porting.xml
DOCS+=	bugging.xml
DOCS+=  volunteer.xml
DOCS+=	knownissues.xml
DOCS+=	develfaq.xml
DOCS+=	example-Makefile.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
