# $FreeBSD: www/en/community/Makefile,v 1.16 2004/05/05 07:56:31 josef Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.sgml man.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"