# $FreeBSD: www/en/docs/Makefile,v 1.5 2005/10/04 05:52:15 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   books.sgml webresources.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
