---
title: Annexe C. Ressources sur Internet
part: Partie V. Annexes
prev: books/handbook/bibliography
next: books/handbook/pgpkeys
---

[appendix]
[[eresources]]
= Ressources sur Internet
:doctype: book
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:toc-title: Table des matières
:table-caption: Tableau
:example-caption: Exemple
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnumoffset: C

include::shared/mirrors.adoc[]
include::shared/authors.adoc[]
include::shared/releases.adoc[]
include::shared/fr/mailing-lists.adoc[]
include::shared/fr/teams.adoc[]
include::shared/fr/urls.adoc[]

L'évolution rapide de FreeBSD rend peu pratique le suivi des développements via des supports imprimés. Les supports électroniques sont le meilleur, sinon la plupart du temps le seul, moyen de se tenir au courant des dernières avancées. Comme FreeBSD est un effort basé sur le volontariat, la communauté des utilisateurs sert généralement de "service de support technique", le courrier électronique et les forums de discussion étant le meilleur moyen de contacter cette communauté.

Les points de contact les plus importants avec la communauté des utilisateurs de FreeBSD sont listés ci-dessous. Si vous connaissez d'autres ressources qui n'y figurent pas, communiquez-les s'il vous plaît à la {freebsd-doc} de façon à ce qu'elles soient aussi mentionnées.

[[eresources-mail]]
== Listes de diffusion

Bien qu'un grand de nombre de développeurs de FreeBSD lisent les forums de discussion, nous ne pouvons vous garantir de réponse en temps et en heure à vos questions (ni même de réponse tout court) si vous ne les postez que sur un des forums `comp.unix.bsd.freebsd.*`. En adressant vos questions sur la liste de diffusion appropriée vous nous contacterez en même temps qu'un auditoire FreeBSD concentré, ce qui vous garantit invariablement une meilleure (ou tout au moins une plus rapide) réponse.

Les chartes d'utilisation pour les différentes listes sont données à la fin de ce document. _Lisez-les s'il vous plaît avant de vous inscrire ou d'envoyer du courrier à une liste_. La plupart des inscrits à nos listes reçoivent maintenant des centaines de messages en rapport à FreeBSD chaque jour, et en définissant des chartes et des règles d'utilisation, nous essayons de garder assez élevé le rapport signal/bruit sur les listes. Ne pas le faire verrait l'échec des listes de diffusion comme moyen efficace de communication pour le projet.

[NOTE]
====
_Si vous désirez tester votre capacité à envoyer du courrier aux listes FreeBSD, envoyez un message de test à la liste {freebsd-test}._ Veuillez ne pas envoyer de messages de test vers une autre liste.
====

En cas de doute sur la liste sur laquelle poser une question, lisez link:{freebsd-questions-article}[Comment obtenir les meilleurs résultats sur la liste de diffusion FreeBSD-questions].

Avant de poster sur une liste de diffusion, veuillez apprendre à utiliser au mieux les listes de diffusion, comme par exemple éviter de relancer des discussions qui reviennent régulièrement, en lisant le document (FAQ) sur link:{mailing-list-faq}[les questions fréquemment posées au sujet des listes de diffusion].

Des archives de toutes les listes de diffusion sont conservées et on peut effectuer des recherches sur le link:https://www.FreeBSD.org/search/[serveur World Wide Web de FreeBSD]. Les archives interrogeables par mots-clés offrent un excellent moyen de trouver des réponses aux questions fréquemment posées et devraient être consultées avant de poster une question.

[[eresources-summary]]
=== Résumé des listes de diffusion

_Listes générales:_ les listes suivantes sont des listes générales auxquelles chacun est libre (et encouragé) de s'inscrire:

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Liste
| Objet

|link:{cvs-all-url}[cvs-all]
|Toutes les modifications de l'arborescence des sources

|link:{freebsd-advocacy-url}[freebsd-advocacy]
|Propagande FreeBSD

|{freebsd-announce}
|Evénements et étapes importantes du projet

|link:{freebsd-arch-url}[freebsd-arch]
|Discussions sur l'architecture et l'implémentation de FreeBSD

|link:{freebsd-bugbusters-url}[freebsd-bugbusters]
|Discussions concernant la maintenance de la base des données des rapports de bogue de FreeBSD et des outils rattachés

|link:{freebsd-bugs-url}[freebsd-bugs]
|Rapports de bogue

|link:{freebsd-chat-url}[freebsd-chat]
|Sujets non-techniques en rapport avec la communauté FreeBSD

|{freebsd-current}
|Discussions concernant l'utilisation de FreeBSD-CURRENT

|link:{freebsd-isp-url}[freebsd-isp]
|Pour les fournisseurs d'accès utilisant FreeBSD

|link:{freebsd-jobs-url}[freebsd-jobs]
|Emplois et interventions de consultants en rapport avec FreeBSD

|link:{freebsd-policy-url}[freebsd-policy]
|Décisions de la politique de l'équipe de base de FreeBSD. Volume faible, et accès en lecture uniquement

|link:{freebsd-questions-url}[freebsd-questions]
|Questions des utilisateurs et support technique

|{freebsd-security-notifications}
|Avis de sécurité

|{freebsd-stable}
|Discussions concernant l'utilisation de FreeBSD-STABLE

|{freebsd-test}
|Où envoyer vos messages de test au lieu que dans une des listes réelles
|===

_Listes techniques:_ les listes suivantes sont destinées aux discussions techniques. Vous devriez lire la charte d'utilisation pour chaque liste attentivement avant de s'y inscrire ou d'y envoyer du courrier parce qu'il y a des règles fermes quant à leur utilisation et leur contenu.

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Liste
| Objet

|{freebsd-acpi}
|Développement de l'ACPI et de la gestion d'energie

|link:{freebsd-afs-url}[freebsd-afs]
|Portage d'AFS sous FreeBSD

|link:{freebsd-aic7xxx-url}[freebsd-aic7xxx]
|Développement de pilotes pour les contrôleurs AIC 7xxx d'Adaptec(R)

|link:{alpha-url}[alpha]
|Portage de FreeBSD sur les systèmes Alpha

|link:{freebsd-amd64-url}[freebsd-amd64]
|Portage de FreeBSD sur les systèmes AMD64

|link:{freebsd-apache-url}[freebsd-apache]
|Discussion sur les logiciels portés relatifs à Apache

|link:{freebsd-arm-url}[freebsd-arm]
|Portage de FreeBSD sur les processeurs ARM(R)

|link:{freebsd-atm-url}[freebsd-atm]
|Utilisation de réseaux ATM avec FreeBSD

|link:{freebsd-audit-url}[freebsd-audit]
|Projet d'audit du code source

|link:{freebsd-binup-url}[freebsd-binup]
|Conception et développement du système de mise à jour binaire

|link:{freebsd-bluetooth-url}[freebsd-bluetooth]
|Utilisation de la technologie Bluetooth(R) sous FreeBSD

|link:{freebsd-cluster-url}[freebsd-cluster]
|Utilisation de FreeBSD dans un environnement en grappe

|link:{freebsd-cvsweb-url}[freebsd-cvsweb]
|Maintenance du système CVSweb

|link:{freebsd-database-url}[freebsd-database]
|Discussions à propos de l'utilisation de bases de données et de leur développement sous FreeBSD

|link:{freebsd-doc-url}[freebsd-doc]
|Création de documents en rapport avec FreeBSD

|link:{freebsd-drivers-url}[freebsd-drivers]
|Ecrire des pilotes de périphériques pour FreeBSD

|link:{freebsd-eclipse-url}[freebsd-eclipse]
|Pour les utilisateurs FreeBSD de l'EDI Eclipse, les outils, les applications clientes et les logiciels portés.

|link:{freebsd-embedded-url}[freebsd-embedded]
|Utilisation de FreeBSD dans les applications embarquées

|link:{freebsd-eol-url}[freebsd-eol]
|Entre-aide sur les logiciels relatifs à FreeBSD et qui ne sont plus supportés par le projet FreeBSD.

|link:{freebsd-emulation-url}[freebsd-emulation]
|Emulation d'autres systèmes comme Linux/MS-DOS(R)/Windows(R)

|link:{freebsd-firewire-url}[freebsd-firewire]
|Discussion technique au sujet du FireWire(R) (iLink, IEEE 1394) sous FreeBSD

|link:{freebsd-fs-url}[freebsd-fs]
|Systèmes de fichiers

|link:{freebsd-geom-url}[freebsd-geom]
|Discussions spécifiques à GEOM et à ses implémentations

|link:{freebsd-gnome-url}[freebsd-gnome]
|Portage de GNOME et des applications GNOME

|link:{freebsd-hackers-url}[freebsd-hackers]
|Discussions techniques générales

|link:{freebsd-hardware-url}[freebsd-hardware]
|Discussion générale à propos du matériel fonctionnant sous FreeBSD

|link:{freebsd-i18n-url}[freebsd-i18n]
|Internationalisation de FreeBSD

|link:{freebsd-ia32-url}[freebsd-ia32]
|FreeBSD sur la plate-forme IA-32 (Intel(R) x86)

|link:{freebsd-ia64-url}[freebsd-ia64]
|Portage de FreeBSD sur les futurs système Intel(R) IA64

|link:{freebsd-ipfw-url}[freebsd-ipfw]
|Discussion technique concernant le développement du nouveau code du coupe-feu

|link:{freebsd-isdn-url}[freebsd-isdn]
|Développeurs ISDN

|link:{freebsd-jail-url}[freebsd-jail]
|Discussion au sujet des environnements man:jail[8]

|link:{freebsd-java-url}[freebsd-java]
|Développeurs Java(TM) et personnes portant et les JDKs sous FreeBSD

|link:{freebsd-kde-url}[freebsd-kde]
|Portage de KDE et des applications pour KDE

|link:{freebsd-lfs-url}[freebsd-lfs]
|Portage de LFS sous FreeBSD

|link:{freebsd-libh-url}[freebsd-libh]
|Le système d'installation et de logiciel pré-compilé de seconde génération

|link:{freebsd-mips-url}[freebsd-mips]
|Portage de FreeBSD sur MIPS(R)

|link:{freebsd-mobile-url}[freebsd-mobile]
|Discussions à propos des ordinateurs portables

|link:{freebsd-mozilla-url}[freebsd-mozilla]
|Portage de Mozilla sous FreeBSD

|{freebsd-multimedia}
|Applications multimédia

|link:{freebsd-new-bus-url}[freebsd-new-bus]
|Discussions techniques au sujet de l'architecture de bus

|link:{freebsd-net-url}[freebsd-net]
|Discussion au sujet des réseaux et du code source TCP/IP

|link:{freebsd-openoffice-url}[freebsd-openoffice]
|Portage d'OpenOffice.org et de StarOffice(TM) sous FreeBSD

|link:{freebsd-performance-url}[freebsd-performance]
|Questions relatives à l'optimisation pour les installations à charge/performances élevées.

|link:{freebsd-perl-url}[freebsd-perl]
|Maintenance des logiciels portés relatifs à perl

|link:{freebsd-pf-url}[freebsd-pf]
|Discussions et questions concernant le système de coupe-feu packet filter

|link:{freebsd-platforms-url}[freebsd-platforms]
|Portages sur des plateformes à architecture non Intel(R)

|link:{freebsd-ports-url}[freebsd-ports]
|Discussion sur le catalogue des logiciels portés

|link:{freebsd-ports-bugs-url}[freebsd-ports-bugs]
|Discussion sur les bogues/PRs des logiciels portés

|link:{freebsd-ppc-url}[freebsd-ppc]
|Portage de FreeBSD pour le PowerPC(R)

|link:{freebsd-proliant-url}[freebsd-proliant]
|Discussion technique sur l'utilisation de FreeBSD sur les serveurs HP ProLiant

|link:{freebsd-python-url}[freebsd-python]
|Problèmes concernant l'utilisation de Python sous FreeBSD

|link:{qa-url}[qa]
|Discussion sur la qualité de FreeBSD, généralement entre deux versions

|link:{freebsd-rc-url}[freebsd-rc]
|Discussion relative au système [.filename]#rc.d# et à son développement

|link:{freebsd-realtime-url}[freebsd-realtime]
|Développement des extensions temps réel de FreeBSD

|link:{freebsd-scsi-url}[freebsd-scsi]
|Sous-système SCSI

|{freebsd-security}
|Questions concernant la sécurité

|link:{freebsd-small-url}[freebsd-small]
|Utilisation de FreeBSD dans les applications embarquées (obsolète, utilisez link:{freebsd-embedded-url}[freebsd-embedded] à la place)

|link:{smp-url}[smp]
|Discussions sur la conception du traitement symétrique multiprocesseurs

|link:{freebsd-sparc64-url}[freebsd-sparc64]
|Portage de FreeBSD sur les systèmes SPARC(R)

|link:{freebsd-standards-url}[freebsd-standards]
|Conformité de FreeBSD aux normes C99 et POSIX(R)

|link:{freebsd-sun4v-url}[freebsd-sun4v]
|Portage de FreeBSD sur les systèmes basés sur UltraSPARC(R) T1

|link:{freebsd-threads-url}[freebsd-threads]
|Threading sous FreeBSD

|link:{freebsd-testing-url}[freebsd-testing]
|Tests de stabilité et de performance de FreeBSD

|link:{freebsd-tokenring-url}[freebsd-tokenring]
|Support du Token Ring sous FreeBSD

|link:{freebsd-x11-url}[freebsd-x11]
|Support et maintenance de X11 sous FreeBSD

|link:{freebsd-usb-url}[freebsd-usb]
|Discussion sur le support USB sous FreeBSD

|link:{freebsd-vuxml-url}[freebsd-vuxml]
|Discussion sur l'infrastructure VuXML

|link:{freebsd-x11-url}[freebsd-x11]
|Maintenance and support of X11 on FreeBSD
|===

_Liste à accès restreint:_ les listes suivantes sont pour les assistances plus spécialisées (et exigeantes) et ne sont probablement pas d'intérêt général. C'est aussi une bonne idée d'être d'abord actif sur les listes techniques avant de vous inscrire à une de ces listes limités de sorte que vous compreniez l'étiquette impliquée dans ces communications.

[.informaltable]
[cols="1,1", frame="none", options="header"]
|===
| Liste
| Objet

|link:{freebsd-hubs-url}[freebsd-hubs]
|Pour ceux qui gèrent des sites miroir (questions d'infrastructure)

|link:{freebsd-user-groups-url}[freebsd-user-groups]
|Coordination des groupes d'utilisateurs

|link:{freebsd-vendors-url}[freebsd-vendors]
|Coordination des fournisseurs des pré-versions

|link:{freebsd-www-url}[freebsd-www]
|Webmestres de link:https://www.FreeBSD.org/[www.FreeBSD.org]
|===

_Résumé de liste:_ Toutes les listes ci-dessus sont également disponibles sous forme de résumé. Une fois inscrit à une liste, vous pouvez modifier vos options de résumé dans les options de votre compte.

_Listes CVS lists:_ Les listes suivantes sont destinées aux personnes intéressées par la lecture des journaux des modifications effectuées sur les différentes partie de l'arborescence des sources. Ce sont des listes à _lecture seule_ et on ne devrait pas y envoyer de messages.

[.informaltable]
[cols="1,1,1", frame="none", options="header"]
|===
| Liste
| Partie de l'arborescence des sources
| Description de la partie (des sources concernées)

|link:{cvs-all-url}[cvs-all]
|[.filename]#/usr/(CVSROOT\|doc\|ports\|projects\|src)#
|Toute modification de l'arborescence (agrégation de l'ensemble des listes CVS)

|link:{cvs-doc-url}[cvs-doc]
|[.filename]#/usr/(doc\|www)#
|Toutes les modifications effectuées sur les arborescences doc et www

|link:{cvs-ports-url}[cvs-ports]
|[.filename]#/usr/ports#
|Toutes les modifications effectuées sur l'arborescence des logiciels portés

|link:{cvs-projects-url}[cvs-projects]
|[.filename]#/usr/projects#
|Toutes les modifications effectuées sur l'arborescence des projets

|link:{cvs-src-url}[cvs-src]
|[.filename]#/usr/src#
|Toutes les modifications effectuées sur l'arborescence des sources
|===

[[eresources-subscribe]]
=== Comment s'inscrire

Pour s'inscrire à une liste, cliquez sur le nom d'une liste ci-dessus où sur {mailman-lists-url} et cliquez ensuite sur la liste qui vous intéresse. La page de la liste devrait contenir toutes les instructions nécessaires à l'inscription.

Pour poster réellement sur une liste, envoyez simplement un courrier électronique à l'adresse mailto:nom-de-la-liste@FreeBSD.org[nom-de-la-liste@FreeBSD.org]. Ce courrier sera alors redistribué à l'ensemble des membres de la liste de par le monde.

Pour vous désabonner d'une liste, cliquez sur l'URL se trouvant à la fin de chaque message reçu de la liste. Il est également possible d'envoyer un message à mailto:nom-de-la-liste-unsubscribe@FreeBSD.org[nom-de-la-liste-unsubscribe@FreeBSD.org] pour vous désabonner.

Encore une fois, nous voudrions vous demander de garder aux discussions sur les listes techniques leur caractère technique. Si vous n'êtes intéressés uniquement que par les annonces importantes alors nous vous suggérons de vous inscrire à la liste {freebsd-announce}, dont le trafic n'est qu'occasionnel.

[[eresources-charters]]
=== Chartes d'utilisation des listes

Il y a pour _toutes_ les listes de diffusion FreeBSD des règles de base auxquelles tous leurs utilisateurs doivent se conformer. En cas de non respect de ces règles, et après deux (2) avertissements écrits de la part du "Postmaster" de FreeBSD mailto:postmaster@FreeBSD.org[postmaster@FreeBSD.org], au troisième manquement, le contrevenant sera désabonné de toutes les listes de diffusion de FreeBSD, et ses messages ultérieurs filtrés. Nous regrettons de devoir prendre de telles mesures, mais l'Internet d'aujourd'hui est un milieu relativement hostile, et beaucoup ne se rendent pas compte de la fragilité de certains de ses mécanismes.

Règles générales:

* Le sujet de tout message doit correspondre au sujet traité par la liste à laquelle il est adressé, e.g., si c'est une liste concernant des problèmes techniques alors le contenu de votre message doit être technique. Le bavardage continu et les polémiques ne font que dégrader la qualité de la liste de diffusion pour tous les utilisateurs et ne seront pas tolérés. Pour des discussions libres sans sujet particulier, la {freebsd-chat} est disponible et devrait être utilisée dans ce cas.
* Aucun message ne doit être adressé à plus de 2 listes de diffusion, et à 2 listes uniquement dans le cas où il y a une nécessité évidente de poster sur les deux listes. Pour la plupart des listes, il y a déjà beaucoup de souscripteurs communs, et mis à part les cas les plus ésotériques (par exemple "-stable -scsi"), il n'y a pas vraiment de raison de poster sur plus d'une liste à la fois. Si vous recevez un message où apparaissent sur la ligne `Cc` plusieurs listes de diffusion, vous devez purger cette ligne `Cc` avant d'y répondre. _Vous êtes toujours responsable de vos expéditions croisées, peu importe qui en a été à l'origine_.
* Les attaques personnelles et les insultes (dans le cadre d'une discussion) ne sont pas autorisés, et cela concerne tout autant les utilisateurs que les développeurs. Les manquements grossiers à la "nétiquette", citer ou reposter des courriers privés quand l'accord n'en a pas été donné et ne le sera pas, par exemple, sont désapprouvés, mais pas particulièrement réprimés. _Cependant_ de tels contenus entrent rarement dans le cadre des règles d'utilisation d'une liste, et entraîneront donc probablement un avertissement (ou une exclusion) pour cette seule raison.
* La publicité pour des produits ou services sans rapport avec FreeBSD est rigoureusement interdite et entraînera l'exclusion immédiate s'il s'avère que le contrevenant adresse ses publicités par "courrier électronique non sollicité" - spam.

_Chartes liste par liste:_

{freebsd-acpi}::
_Développement de l'ACPI et de la gestion de l'énergie_

link:{freebsd-afs-url}[freebsd-afs]::
_Système de fichiers Andrew - Andrew File System_
+
C'est une liste de discussion sur le portage et l'utilisation d'AFS de CMU/Transarc.

{freebsd-announce}::
_Evénements importants / étapes importantes pour le projet_
+
C'est une liste pour les gens intéressés uniquement par les annonces occasionnelles d'évènements FreeBSD importants. Cela inclut les annonces d'instantanés et autres versions. Cela comprend également les annonces de nouvelles fonctionnalités de FreeBSD. Il peut y avoir aussi des appels à volontaires, etc... C'est une liste de faible volume et rigoureusement modérée.

link:{freebsd-arch-url}[freebsd-arch]::
_Discussions concernant l'architecture et l'implémentation_
+
C'est une liste pour discuter de l'architecture de FreeBSD. Les messages y seront habituellement de nature technique. Des exemples de sujets qui cadrent avec cette liste sont:

** Comment revoir le système de compilation pour que plusieurs compilations personnalisées puissent être effectuées en même temps.
** Que faut-il corriger dans VFS pour que les couches Heidemann fonctionnent.
** Comment modifier l'interface des pilotes de périphériques pour que la même interface fonctionne proprement sur différents bus et architectures.
** Comment écrire un pilote réseau.

link:{freebsd-audit-url}[freebsd-audit]::
_Projet d'audit du code source_
+
C'est la liste de discussion pour le projet d'audit du code source de FreeBSD. Bien que n'étant à l'origine destinée qu'aux modifications relatives à la sécurité, sa charte a été élargie pour l'examen de toute modification de code.
+
Cette liste est très chargée de correctif, et n'est probablement pas intéressant pour l'utilisateur moyen de FreeBSD. Les discussions sur la sécurité non relatives à une modification particulière du code ont lieu sur freebsd-security. Réciproquement, tous les développeurs sont encouragés à envoyer leur correctifs sur la liste pour examen, tout particulièrement s'ils touchent une partie du système où un bogue peut compromettre l'intégrité du système.

link:{freebsd-binup-url}[freebsd-binup]::
_Projet de mise à jour binaire de FreeBSD_
+
Cette liste existe pour discuter du système de mise à jour binaire, ou binup. Problèmes de conception, détails d'implémentation, correctifs, rapports de bogue, rapport d'état, demandes de fonctionnalités, traces des modifications du code, et tout ce qui peut avoir rapport avec binup sont à leur place ici.

link:{freebsd-bluetooth-url}[freebsd-bluetooth]::
_Bluetooth(R) sous FreeBSD_
+
C'est un forum où se rassemble les utilisateurs de la technologie Bluetooth(R) sous FreeBSD. Problèmes de conception, détails de l'implémentation, rapports de bogues, état du support, demande de fonctionnalités, et tous les sujets en rapport avec Bluetooth(R) sont les bienvenues.

link:{freebsd-bugbusters-url}[freebsd-bugbusters]::
_Coordination de la gestion des rapports de bogue_
+
L'objet de cette liste est de servir de forum de coordination et de discussion entre le "Boguemestre", ses chasseurs de bogues et toute autre partie intéressée dans la base de données des PRs. Cette liste n'est pas destinée aux discussions sur des bogues spécifiques, correctifs ou PRs.

link:{freebsd-bugs-url}[freebsd-bugs]::
_Rapports de bogue_
+
C'est la liste pour rapporter les bogues de FreeBSD. Chaque fois que c'est possible, les bogues devraient être soumis en utilisant la commande man:send-pr[1] ou son link:https://www.FreeBSD.org/send-pr.html[interface WEB].

link:{freebsd-chat-url}[freebsd-chat]::
_Sujets non-techniques en rapport avec la communauté FreeBSD_
+
Cette liste reçoit le résidu des discussions sur les autres listes: informations sociologiques, et non techniques. Cela va de savoir si Jordan ressemble ou non à un furet de bande dessinée, s'il faut tapez en majuscules, qui boit trop de café, quelle est la meilleure bière, qui brasse de la bière dans sa cave, et ainsi de suite. Les annonces occasionnelles d'événements importants (les prochaines fêtes, mariages, naissances, nouveaux emplois, etc...) peuvent être adressées aux listes techniques, mais doivent ensuite être redirigées sur cette liste.

{core-name}::
_Equipe de base de FreeBSD_
+
C'est une liste interne à l'usage des membres de l'équipe de base. Des messages peuvent y être adressés lorsqu'un sujet en rapport avec FreeBSD demande arbitrage ou examen à haut niveau.

{freebsd-current}::
_Discussions concernant l'utilisation de FreeBSD-CURRENT_
+
C'est la liste de diffusion pour les utilisateurs de FreeBSD-CURRENT. Elle inclut avertissements au sujet de nouvelles fonctionnalités de -CURRENT qui affecteront les utilisateurs, et les instructions sur ce qu'il faut faire pour rester à jour avec -CURRENT. Tous les utilisateurs de "CURRENT" doivent s'inscrire à cette liste. C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-cvsweb-url}[freebsd-cvsweb]::
_Project CVSweb de FreeBSD_
+
Discussions techniques au sujet de l'utilisation, du développement et de la maintenance du FreeBSD-CVSweb.

link:{freebsd-doc-url}[freebsd-doc]::
_Project de documentation_
+
C'est la liste de discussion sur les questions et projets liés à la rédaction de documentation pour FreeBSD. Les membres de cette liste sont collectivement appelés "Le Projet de Documentation de FreeBSD" - The FreeBSD Documentation Project. C'est une liste ouverte; n'hésitez pas à vous inscrire et à participer!

link:{freebsd-drivers-url}[freebsd-drivers]::
_Ecrire des pilotes de périphériques pour FreeBSD_
+
C'est une liste pour les discussions techniques au sujet des pilotes de périphériques sous FreeBSD. C'est principalement un lieu où les personnes écrivant les pilotes peuvent poser des questions sur l'écriture de pilotes utilisant les APIs du noyau FreeBSD.

link:{freebsd-eclipse-url}[freebsd-eclipse]::
_Pour les utilisateurs FreeBSD de l'EDI Eclipse, les outils, les applications clientes et les logiciels portés._
+
L'objectif de cette liste est de fournir un support pour tout que qui concerne le choix, l'installation, l'utilisation, le développement et la maintenance de l'EDI Eclipse, des ses outils, de ses applications clients sous FreeBSD et l'aide au portage de l'EDI Eclipse et de ses greffons sous l'environnement FreeBSD.
+
Le but est également de faciliter les échanges d'information entre les communautés Eclipse et FreeBSD pour un bénéfice mutuel.
+
Bien que cette liste soit principalement destinée à répondre aux demandes des utilisateurs d'Eclipse, elle est également un forum pour ceux qui désirent développer des applications spécifiques à FreeBSD en utilisant le système Eclipse.

link:{freebsd-embedded-url}[freebsd-embedded]::
_Utilisation de FreeBSD dans les applications embarquées_
+
Cette liste aborde les sujets relatifs à l'utilisation de FreeBSD dans les systèmes embarqués. C'est une liste de diffusion à caractère technique pour laquelle on attend un contenu strictement technique. Dans le cadre de cette liste, nous définissons le terme de système embarqué pour les appareils informatisés qui ne sont pas des stations de travail et qui sont destinés à une application bien particulière et limitée par opposition aux systèmes informatiques classiques. Des exemples de systèmes embarqués, parmi tant d'autres, sont les combinés téléphoniques, les équipements réseau comme les routeurs, les commutateurs et les PABXs, les équipements de mesure à distance, les PDAs, les systèmes de distributeurs, et ainsi de suite.

link:{freebsd-emulation-url}[freebsd-emulation]::
_Emulation d'autres systèmes comme Linux/MS-DOS(R)/Windows(R)_
+
C'est une liste pour les discussions techniques relativent à l'exécution sous FreeBSD de programmes écris pour d'autres systèmes d'exploitation.

link:{freebsd-eol-url}[freebsd-eol]::
_Entre-aide sur les logiciels relatifs à FreeBSD et qui ne sont plus supportés par le projet FreeBSD._
+
Cette liste est destinée aux personnes désirant proposer ou recherchant une aide pour les logiciels relatifs à FreeBSD pour lesquels le projet FreeBSD ne fournir officiellement plus de support (par exemple sous la forme d'avis de sécutité et de correctifs).

link:{freebsd-firewire-url}[freebsd-firewire]::
_FireWire(R) (iLink, IEEE 1394)_
+
C'est une liste pour les discussions sur la conception et le développement d'un sous-système FireWire(R) (IEEE 1394, iLink) sous FreeBSD. Les sujets appropriés incluent spécifiquement les normes, les bus périphériques et leur protocole, l'ensemble d'adaptateurs/cartes/circuits, et l'architecture et l'implémentation de leur propre support.

link:{freebsd-fs-url}[freebsd-fs]::
_Systèmes de fichiers_
+
Discussions concernant les systèmes de fichiers FreeBSD. C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-geom-url}[freebsd-geom]::
_GEOM_
+
Discussions spécifiques à GEOM et aux implémentations relatives. C'est une liste de diffusion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-gnome-url}[freebsd-gnome]::
_GNOME_
+
Discussions concernant l'environnement de travail GNOME sous les systèmes FreeBSD. C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-ipfw-url}[freebsd-ipfw]::
_Coupe-feu IP_
+
C'est le forum pour les discussions techniques concernant la nouvelle implémentation du code du coupe-feu IP sous FreeBSD. C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-ia64-url}[freebsd-ia64]::
_Portage de FreeBSD sur IA64_
+
C'est une liste de discussion technique pour les personnes travaillant sur le portage de FreeBSD sur la plate-forme IA-64 d'Intel(R), pour soulever les problèmes ou discuter de solutions alternatives. Ceux qui sont intéressés à suivre les discussions techniques sont aussi bienvenus.

link:{freebsd-isdn-url}[freebsd-isdn]::
_Communications ISDN_
+
C'est la liste pour les personnes discutant du développement du support ISDN de FreeBSD.

link:{freebsd-java-url}[freebsd-java]::
_Développement Java(TM)_
+
C'est la liste pour les personnes discutant du développement d'applications Java(TM) significatives sous FreeBSD et du portage et de la maintenance des JDK(TM)s.

[[eresources-charters-jobs]]
link:{freebsd-jobs-url}[freebsd-jobs]::
_Recherches et offres d'emplois_
+
C'est un forum pour poster des offres d'emplois et des curriculum vitae relatifs à FreeBSD, c'est à dire si vous cherchez un emploi concernant FreeBSD ou que vous offrez un emploi impliquant FreeBSD, alors c'est le bon endroit. Ce n'est _pas_ une liste de diffusion pour les problèmes généraux relatifs aux offres et à la recherche d'un emploi puisque des forums adéquats existent déjà par ailleurs.
+
Notez que cette liste, comme les autres listes de diffusion du domaine `FreeBSD.org`, est diffusée au niveau mondial. Par conséquent, vous devez être précis quant à l'emplacement, les possibilités de travail à distance ou de déplacement.
+
Les messages devraient utiliser uniquement des formats ouverts - de préférence du texte brut, mais le PDF, l'HTML, et quelques autres formats sont acceptables. Les formats propriétaires comme Microsoft(R) Word ([.filename]#.doc#) seront rejetés par le serveur de la liste de diffusion.

link:{freebsd-kde-url}[freebsd-kde]::
_KDE_
+
Discussions concernant KDE sous les systèmes FreeBSD. C'est une liste de discussion technique sur laquelle le contenu doit rester strictement technique.

link:{freebsd-hackers-url}[freebsd-hackers]::
_Discussions techniques_
+
C'est le forum pour les discussions techniques au sujet de FreeBSD. C'est la principale liste technique. Elle est destinée à ceux qui travaillent activement à FreeBSD, pour soulever des problèmes et discuter de solutions alternatives. Ceux qui sont intéressés à suivre les discussions techniques sont aussi bienvenus. C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-hardware-url}[freebsd-hardware]::
_Discussions générales sur le matériel pour FreeBSD_
+
Discussions générales sur les types de matériel sur lesquels tourne FreeBSD, les problèmes rencontrés et suggestions sur quoi acheter ou éviter.

link:{freebsd-hubs-url}[freebsd-hubs]::
_Sites miroir_
+
Annonces et discussions pour les personnes qui font fonctionner les sites miroir FreeBSD.

link:{freebsd-isp-url}[freebsd-isp]::
_Questions concernant les fournisseurs d'accès à Internet_
+
C'est la liste pour discuter des sujets qui intéressent les fournisseurs d'accès Internet - Internet Service Providers (ISPs) - qui utilisent FreeBSD. C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-openoffice-url}[freebsd-openoffice]::
_OpenOffice.org_
+
Discussions concernant le portage et la maintenance d'OpenOffice.org et StarOffice(TM).

link:{freebsd-performance-url}[freebsd-performance]::
_Discussions au sujet de l'optimisation et l'accélération de la vitesse d'exécution de FreeBSD_
+
Cette liste de diffusion existe pour offrir un endroit aux hackers, administrateurs, et/ou les parties concernées pour discuter de sujets ayant trait aux performances de FreeBSD. Les sujets acceptables comprennent les discussions concernant les installations de FreeBSD qui sont soit sous charge importante, soit présentant des problèmes de performance, ou encore qui repoussent les limites de FreeBSD. Les personnes désirant travailler sur l'amélioration des performances de FreeBSD sont grandement encouragées à s'inscrire à cette liste. C'est une liste hautement technique destinée aux utilisateurs expérimentés de FreeBSD, aux hackers, ou aux administrateurs intéressés par un FreeBSD rapide, robuste, et adaptable. Ce n'est pas une liste de questions-réponses qui remplace la lecture de la documentation, mais c'est un endroit où il est possible d'effectuer des contributions ou de se préoccuper de sujets non-résolus relatifs aux performances.

link:{freebsd-pf-url}[freebsd-pf]::
_Discussions et questions concernant le système de coupe-feu packet filter_
+
Discussions concernant le système de coupe-feu packet filter (pf) sous FreeBSD. Les discussions techniques ainsi que les questions des utilisateurs sont les bienvenues. Cette liste est également un endroit où discuter du système de qualité de service ALTQ.

link:{freebsd-platforms-url}[freebsd-platforms]::
_Portage sur les plate-formes non Intel(R)_
+
Questions concernant le support d'autres plates-formes, discussions générales et propositions pour les portages sur des plates-formes non Intel(R). C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-policy-url}[freebsd-policy]::
_Décisions de la politique de l'équipe de base_
+
C'est une liste de discussion à faible trafic, et en lecture seule pour les décisions de la politique de l'équipe de base.

link:{freebsd-ports-url}[freebsd-ports]::
_Discussion sur les "logiciels portés"_
+
Discussions concernant le ``catalogue des logiciels portés'' de FreeBSD ([.filename]#/usr/ports#), propositions de portages, modifications de l'infrastructure du catalogue des logiciels portés et coordination générale. C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-proliant-url}[freebsd-proliant]::
_Discussion technique sur l'utilisation de FreeBSD sur les serveurs HP ProLiant_
+
Cette liste de diffusion doit être utilisée pour les discussions techniques concernant l'utilisation de FreeBSD sur les serveurs HP ProLiant, y compris les discussions sur les pilotes spécifiques à ces machines, les logiciels de gestion, les outils de configuration, et les mises à jour du BIOS. C'est également le premier endroit où discuter des modules hpasmd, hpasmcli, et hpacucli.

link:{freebsd-python-url}[freebsd-python]::
_Python sous FreeBSD_
+
C'est une liste pour les discussions relatives à l'amélioration du support de Python sous FreeBSD. C'est une liste de discussion technique. Elle est destinée aux personnes travaillant sur le portage de Python, de ses modules tiers partie et éléments relatifs à Zope sous FreeBSD. Les personnes intéressées par ces discussions techniques sont également les bienvenues.

link:{freebsd-questions-url}[freebsd-questions]::
_Questions des utilisateurs_
+
C'est la liste pour les questions à propos de FreeBSD. Vous ne devriez pas adresser de questions du type "comment faire" aux listes techniques à moins que vous n'estimiez que la question soit vraiment très technique.

link:{freebsd-scsi-url}[freebsd-scsi]::
_Sous-système SCSI_
+
C'est la liste de diffusion pour ceux qui travaillent sur le sous-système SCSI de FreeBSD. C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

{freebsd-security}::
_Questions relatives à la sécurité_
+
Questions ayant trait à la sécurité des ordinateurs sous FreeBSD (DES, Kerberos, trous de sécurité connus et correctifs, etc...). C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique. Notez que ce n'est pas une liste de question-réponse, mais ce type de contribution (la question ET la réponse) à la FAQ est le bienvenue.

{freebsd-security-notifications}::
_Avis de sécurité_
+
Notifications des problèmes de sécurité concernant FreeBSD et correctifs. Ce n'est pas une liste de discussion. La liste de discussion correspondante est FreeBSD-security.

link:{freebsd-small-url}[freebsd-small]::
_Utilisation de FreeBSD dans les applications embarquées_
+
Cette liste discute de sujets relatifs aux installations inhabituellement petites et embarquées de FreeBSD. C'est une liste de discussion technique sur laquelle un contenu strictement technique est attendu.
+
[NOTE]
====
Cette liste est obsolète depuis la création de link:{freebsd-embedded-url}[freebsd-embedded].
====

{freebsd-stable}::
_Discussions concernant l'utilisation de FreeBSD-STABLE_
+
C'est la liste de diffusion pour les utilisateurs de FreeBSD-STABLE. Elle inclut avertissements au sujet de nouvelles fonctionnalités de -STABLE qui affecteront les utilisateurs, et des instructions sur ce qu'il faut faire pour rester à jour avec -STABLE. Tous les utilisateurs de la branche "STABLE" devraient s'inscrire à cette liste. C'est une liste de discussion technique sur laquelle le contenu doit être strictement technique.

link:{freebsd-standards-url}[freebsd-standards]::
_Conformité aux normes C99 POSIX_
+
C'est un forum pour les discussions techniques concernant la conformité de FreeBSD aux normes C99 et POSIX.

link:{freebsd-usb-url}[freebsd-usb]::
_Discussion sur le support USB sous FreeBSD_
+
C'est une liste de diffusion pour les discussions techniques relatives au support de l'USB sous FreeBSD

link:{freebsd-user-groups-url}[freebsd-user-groups]::
_Coordination des groupes d'utilisateurs_
+
C'est la liste pour les coordinateurs des différents groupes locaux d'utilisateurs, destinée à leurs discussions entre eux et avec un membre désigné de l'équipe de base. Cette liste doit se limiter aux comptes-rendus de réunions et à la coordination de projets entre plusieurs groupes d'utilisateurs.

link:{freebsd-vendors-url}[freebsd-vendors]::
_Fournisseurs_
+
Coordination des discussions entre le projet FreeBSD et les fournisseurs de logiciel ou de matériel pour FreeBSD.

[[eresources-mailfiltering]]
=== Filtrages en vigueur sur les listes de diffusion

Les listes de diffusion FreeBSD sont filtrées de plusieurs façons en vue d'éviter la distribution de SPAM, de virus, et tout autre message non-sollicité. Les opérations de filtrage décries dans cette section ne comprennent pas toutes celles utilisées pour protéger les listes re diffusion.

Seuls certains types de pièces jointes sont autorisés sur les listes de diffusion. Toutes les pièces jointes avec un format MIME qui ne figurent pas parmi la liste ci-dessous seront retirées avant que le message ne soit distribué sur les listes de diffusion.

* application/octet-stream
* application/pdf
* application/pgp-signature
* application/x-pkcs7-signature
* message/rfc822
* multipart/alternative
* multipart/related
* multipart/signed
* text/html
* text/plain
* text/x-diff
* text/x-patch

[NOTE]
====
Certaines listes de diffusion pourront autoriser des pièces jointes sous d'autres formats MIME, mais la liste précédente devrait être applicable pour la plupart des listes de diffusion.
====

Si un message contient une version HTML et une version texte du contenu du message, la version HTML sera retirée. Si le corps d'un message est uniquement sous forme HTML, il sera converti sous forme texte brut.

[[eresources-news]]
== Forums de discussion

En plus de deux forums de discussion spécifiques à FreeBSD, il y en a de nombreux autres où il est question de FreeBSD ou qui sont par ailleurs d'intérêt pour les utilisateurs de FreeBSD. http://minnie.tuhs.org/BSD-info/bsdnews_search.html[Des archives interrogeables par mots-clés] sont disponibles pour certains de ces forums, grâce à Warren Toomey mailto:wkt@cs.adfa.edu.au[wkt@cs.adfa.edu.au].

=== Forums spécifiques à BSD

* link:news:comp.unix.bsd.freebsd.announce[comp.unix.bsd.freebsd.announce]
* link:news:comp.unix.bsd.freebsd.misc[comp.unix.bsd.freebsd.misc]
* link:news:de.comp.os.unix.bsd[de.comp.os.unix.bsd] (Allemand)
* link:news:fr.comp.os.bsd[fr.comp.os.bsd] (Français)
* link:news:it.comp.os.freebsd[it.comp.os.freebsd] (Italien)
* link:news:tw.bbs.comp.386bsd[tw.bbs.comp.386bsd] (Chinois)

=== Autres forums UNIX(R) intéressants

* link:news:comp.unix[comp.unix]
* link:news:comp.unix.questions[comp.unix.questions]
* link:news:comp.unix.admin[comp.unix.admin]
* link:news:comp.unix.programmer[comp.unix.programmer]
* link:news:comp.unix.shell[comp.unix.shell]
* link:news:comp.unix.user-friendly[comp.unix.user-friendly]
* link:news:comp.security.unix[comp.security.unix]
* link:news:comp.sources.unix[comp.sources.unix]
* link:news:comp.unix.advocacy[comp.unix.advocacy]
* link:news:comp.unix.misc[comp.unix.misc]
* link:news:comp.bugs.4bsd[comp.bugs.4bsd]
* link:news:comp.bugs.4bsd.ucb-fixes[comp.bugs.4bsd.ucb-fixes]
* link:news:comp.unix.bsd[comp.unix.bsd]

=== Système X Window

* link:news:comp.windows.x.i386unix[comp.windows.x.i386unix]
* link:news:comp.windows.x[comp.windows.x]
* link:news:comp.windows.x.apps[comp.windows.x.apps]
* link:news:comp.windows.x.announce[comp.windows.x.announce]
* link:news:comp.windows.x.intrinsics[comp.windows.x.intrinsics]
* link:news:comp.windows.x.motif[comp.windows.x.motif]
* link:news:comp.windows.x.pex[comp.windows.x.pex]
* link:news:comp.emulators.ms-windows.wine[comp.emulators.ms-windows.wine]

[[eresources-web]]
== Serveurs World Wide Web

[[eresources-email]]
== Adresses électroniques

Les groupes d'utilisateurs suivants fournissent à leurs membres des adresses électroniques liées à FreeBSD. Les administrateurs cités se réservent le droit de supprimer l'adresse si elle est à l'origine d'abus.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Domaine
| Possibilités offertes
| Groupe d'utilisateurs
| Administrateur

|ukug.uk.FreeBSD.org
|Transmission de courrier uniquement
| mailto:freebsd-users@uk.FreeBSD.org[freebsd-users@uk.FreeBSD.org]
|Lee Johnston mailto:lee@uk.FreeBSD.org[lee@uk.FreeBSD.org]
|===

[[eresources-shell]]
== Comptes

Les groupes d'utilisateurs suivants fournissent des comptes aux personnes supportant le projet FreeBSD. Les administrateurs cités se réservent le droit de supprimer le compte s'il est à l'origine d'abus.

[.informaltable]
[cols="1,1,1,1", frame="none", options="header"]
|===
| Hôte
| Accès
| Possibilités offertes
| Administrateur

|dogma.freebsd-uk.eu.org
|Telnet/FTP/SSH
|Adresse électronique, espace Web, FTP anonyme
|Lee Johnston mailto:lee@uk.FreeBSD.org[lee@uk.FreeBSD.org]
|===
