# $FreeBSD: www/en/events/2002/Makefile,v 1.1 2002/03/16 08:47:55 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS?=	bsdcon-devsummit.sgml usenix-devsummit.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
