# $FreeBSD: www/en/projects/Makefile,v 1.28 2006/10/04 22:01:50 murray Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	projects.sgml

INDEXLINK= projects.html

.include "${WEB_PREFIX}/share/mk/web.site.mk"
