# $FreeBSD: www/en/donations/Makefile,v 1.1 2002/05/09 12:50:53 mwlucas Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml wantlist.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
