# $FreeBSD: www/en/donations/Makefile,v 1.2 2002/08/05 14:45:15 mwlucas Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml wantlist.sgml donors.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
