# $FreeBSD: www/en/donations/Makefile,v 1.3 2002/11/25 02:15:05 trhodes Exp $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.sgml wantlist.sgml donors.sgml press.sgml

.include "${WEB_PREFIX}/share/mk/web.site.mk"
