name: "Label pull requests"
on: [pull_request_target]

jobs:

  label-pull-requests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/conf/label-pull-requests.yml"
