=== The FreeBSD Russian Documentation Project

Links: +
link:https://www.freebsd.org/ru/[FreeBSD Official Website in Russian] URL: link:https://www.freebsd.org/ru/[] +
link:https://docs.freebsd.org/ru/books/faq/[FAQ] URL: link:https://docs.freebsd.org/ru/books/faq/[] +
link:https://github.com/freebsd-doc-ru/freebsd-doc/discussions[The FreeBSD Russian Documentation Project site] URL: link:https://github.com/freebsd-doc-ru/freebsd-doc/discussions[]

Contact: Andrey Zakhvatov <andy@FreeBSD.org> +
Contact: Vladlen Popolitov <vladlen@FreeBSD.org>

The FreeBSD Russian Documentation Project's current goal is to provide up-to-date Russian translations of the most important parts of the FreeBSD documentation (FAQ, Handbook, website content).
It is essential to support Russian speaking users with high-quality official technical materials and to increase the adoption of the operating system worldwide.
We hope this initiative will gain support within the Russian-speaking FreeBSD community and lead to an increase in translated materials.

During the last quarter:

* 100% of the text in Weblate has been translated, accounting for all recent changes.
* The review and update process for the remaining documentation has been completed.
All 47 documents (books and articles) are now fully synchronized on the link:https://docs.freebsd.org/ru/[Russian documentation site].
* The Russian language section of link:https://www.FreeBSD.org/ru[www.FreeBSD.org/ru] has been restored, with approximately 90% of its pages updated.
* News, event announcements, and press links are now being translated and published on the Russian website.
Additionally, Errata Notices and Security Advisories have been translated into Russian starting from January 2025.
* For the FreeBSD 15.0 release, the complete set of release documentation (release notes, errata, etc.) has been translated into Russian in a timely manner alongside the English originals.
* The project to translate FreeBSD man pages has been initiated and is in its very early stages.
  Preliminary examples can be found at link:https://github.com/freebsd-doc-ru/freebsd-man-ru[GitHub].

This report acknowledges with appreciation the contributions of the following colleagues who performed reviews of our commits during the quarter (in Phabricator or by email):

* mailto:carlavilla@FreeBSD.org[Sergio Carlavilla Delgado]
* mailto:eugen@FreeBSD.org[Eugene Grosbein]
* mailto:marck@FreeBSD.org[Dmitry Morozovsky]
* mailto:maxim@FreeBSD.org[Maxim Konovalov]
* mailto:mizhka@FreeBSD.org[Michael Zhilin]
* mailto:pluknet@FreeBSD.org[Sergey Kandaurov]
* mailto:salvadore@FreeBSD.org[Lorenzo Salvadore]

Plan for next quarter:

* Finalize the update of all remaining pages on the Russian language website.
* Establish a sustainable workflow to keep the translated content (News, Events, Press, Errata, Security Advisories) up to date and publish it on the website as promptly as possible.
* Translate the new "FreeBSD Accessibility Handbook" as soon as it becomes available for translation in Weblate.
* Continue the ongoing project to translate FreeBSD man pages.

Check the https://docs.freebsd.org/ru/books/fdp-primer/translations/[official translation guide] if you would like to help.

We would appreciate your assistance with translating the following materials:

* Web pages
* Man pages
