=== GCC on FreeBSD

Links: +
link:https://gcc.gnu.org/[GCC Project] URL: link:https://gcc.gnu.org/[] +
link:https://gcc.gnu.org/gcc-13/[GCC 13 release series] URL: link:https://gcc.gnu.org/gcc-13/[] +
link:https://gcc.gnu.org/gcc-14/[GCC 14 release series] URL: link:https://gcc.gnu.org/gcc-14/[] +
link:https://gcc.gnu.org/gcc-15/[GCC 15 release series] URL: link:https://gcc.gnu.org/gcc-15/[] +
link:https://gcc.gnu.org/gcc-16/[GCC 16 release series] URL: link:https://gcc.gnu.org/gcc-16/[] +

Contact: Lorenzo Salvadore <salvadore@FreeBSD.org>

Very little has happened for GCC on FreeBSD this quarter.

The main news is that the link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281091[exp-run to update GCC default version from 13 to 14] is finally finished.
It took longer than expected due to some segmentation fault which happens in the emacs ports only on most recent FreeBSD versions.
Since the GCC_DEFAULT update was already long due, it has been chosen to pin the emacs ports to GCC 13 for now, so that this single bug does not prevent the rest of the ports tree from getting advantage of a more recent GCC version by default.
Please see link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=288303[PR 288303] for more information.

GCC 15 is already in our ports tree and the process to bring GCC_DEFAULT to 15 will soon start.
