=== KDE on FreeBSD

Links: +
link:https://freebsd.kde.org/[KDE/FreeBSD initiative] URL: link:https://freebsd.kde.org/[] +
link:https://community.kde.org/FreeBSD[FreeBSD -- KDE Community Wiki] URL: link:https://community.kde.org/FreeBSD[]

Contact: KDE on FreeBSD Mailing List <kde@FreeBSD.org>

The KDE on FreeBSD project packages CMake, Qt, and software from the KDE Community, for the FreeBSD ports tree.
The software includes a full desktop environment called KDE Plasma (for both X11 and Wayland) and hundreds of applications that can be used on any FreeBSD machine.
The mailto:kde@FreeBSD.org[KDE team] is part of mailto:desktop@FreeBSD.org[desktop@], building the software stack to make FreeBSD beautiful and usable as a daily driver graphical desktop workstation.

==== Infrastructure

CMake was updated to 3.31.10.
Ninja was updated to 1.13.2.

Qt6, PyQt6, and PySide6 were updated to 6.10.1.

Qt5 was updated to 5.15.18 KDE patch collection.
Upstream standard support for Qt5 is officially over.
This might be the last update for Qt5 on FreeBSD.

==== KDE Stack

KDE Frameworks, Plasma, and Gear release happen very regularly. mailto:kde@FreeBSD.org[KDE team] lands these updates shortly after their upstream release.

* KDE Frameworks ports were updated to 6.21.0.
* KDE Plasma Desktop was updated to 6.5.4.
* KDE Gear was updated to 25.12.0.

With KDE Gear 25.12.0 the last two applications have been finally ported to Qt6, and KDE Stack is liberated from Qt5 packages now.
The package:x11/kde[] port has been reduced and does not install Plasma 6 integration plugins for Qt5 and GTK2 applications anymore.
They are still available and can be installed via package:x11/plasma6-plasma[] port if required.

Support for Plasma/Wayland has been improved.
It can be used as a daily driver instead of Plasma/X11.

==== Related Ports

The mailto:kde@FreeBSD.org[KDE team] maintains nearly 730 ports and updates them all as needed.
According to link:https://portscout.freebsd.org/kde@freebsd.org.html[Portscout] only 1% ports are outdated.

The KDE team would like to thank mailto:arrowd@FreeBSD.org[Gleb Popov], mailto:jhale@FreebSD.org[Jason E. Hale], mailto:lbartoletti@FreeBSD.org[Loïc Bartoletti], and mailto:makc@FreeBSD.org[Max Brazhnikov] for keeping things up-to-date.
The KDE team is grateful to Harley (SponiX on IRC) for sharing his building box.
