=== FreeBSD Release Engineering Team

Links: +
link:https://www.freebsd.org/releases/15.0R/announce/[FreeBSD 15.0-RELEASE announcement] URL: link:https://www.freebsd.org/releases/15.0R/announce/[] +
link:https://www.freebsd.org/releases/14.4R/schedule/[FreeBSD 14.4-RELEASE schedule] URL: link:https://www.freebsd.org/releases/14.4R/schedule/[] +
link:https://download.freebsd.org/releases/ISO-IMAGES/[FreeBSD releases] URL: link:https://download.freebsd.org/releases/ISO-IMAGES/[] +
link:https://download.freebsd.org/snapshots/ISO-IMAGES/[FreeBSD development snapshots] URL: link:https://download.freebsd.org/snapshots/ISO-IMAGES/[]

Contact: FreeBSD Release Engineering Team, <re@FreeBSD.org>

The FreeBSD Release Engineering Team is responsible for setting and publishing release schedules for official project releases of FreeBSD, announcing code freezes and maintaining the respective branches, among other things.

The Team managed 15.0-RELEASE, leading to the official RELEASE build and announcement in December; this was the first release from the new *stable/15* branch.
As part of this, considerable work went into setting up a system for securely building, signing, and distributing package repositories for the 15.0-RELEASE base system.

Planning has started for the upcoming 14.4-RELEASE cycle.

The Release Engineering Team continued providing weekly development snapshot builds for the *main*, *stable/14*, and *stable/13* branches, and started providing weekly development snapshot builds for the new *stable/15* branch.
