=== Ports -- Use Bazel as build tool for MongoDB 8.0

Links: +
link:https://www.freshports.org/databases/mongodb80/[MongoDB 8.0 port] URL: https://www.freshports.org/databases/mongodb80/[] +
link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=287546[Bazel 8 PR] URL: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=287546[]

Contact: Ronald Klop <ronald@FreeBSD.org>

MongoDB is a production level NoSQL database.
Our ports has the Community edition of MongoDB for many years already.
MongoDB is used by several WiFi controller software in ports like Unifi and Omada.
In MongoDB 8.0.13 the build system is changed from SCons to Bazel.

We have version 8 of Bazel in Bugzilla (PR 287546).
With this version the build of MongoDB 8.0 starts. 
Unfortunately the build errors pretty quickly.

Because of security issues in the MongoDB 8.0 port it becomes important to upgrade the port to the latest version.

I am looking for somebody with experience of a Bazel build to help.

* Contact me.
* Set up your build environment with Bazel 8.
* Compile and fix.
* Let us commit it!
