=== Realtek Wireless driver support

Links: +
link:https://wiki.freebsd.org/WiFi/Rtw88[rtw88 status FreeBSD wiki page] URL: link:https://wiki.freebsd.org/WiFi/Rtw88[https://wiki.freebsd.org/WiFi/Rtw88] +
link:https://wiki.freebsd.org/WiFi/Rtw89[rtw89 status FreeBSD wiki page] URL: link:https://wiki.freebsd.org/WiFi/Rtw89[https://wiki.freebsd.org/WiFi/Rtw89]

Contact: Bjoern A. Zeeb <bz@FreeBSD.org>

While the Intel Wireless driver update project is the main driver behind the work to bring support for newer chipsets and eventually newer IEEE 802.11 standards support, there is also an ongoing effort to support more drivers.
The next two drivers in the (already longer) queue are Realtek's rtw88 and rtw89.

While the initial driver porting efforts for rtw88 and rtw89 happened on personal time, the LinuxKPI integration has to be done more and more along the Intel wireless driver work and so thanks are also due to The FreeBSD Foundation.

The rtw88 driver has started to work on some machines with less than 4GB of main memory and was committed to the FreeBSD git repository for broader testing.
While our version of the driver is aware of these limitations, the problem is currently assumed to be outside the driver in the interactions with LinuxKPI and busdma.

The rtw89 driver has happily started to send packets and has problems receiving frames at this point.
Further investigation will happen as soon as rtw88 is sorted out and it is expected that rtw89 will then also timely follow into FreeBSD's git repository.

The currently known requirements to compile both drivers have mostly gone into stable/13 and releng/13.1 already.

For the latest state of the development, please check the referenced wiki pages and follow the freebsd-wireless mailing list.

Sponsor: The FreeBSD Foundation (partly)
