# $FreeBSD$
# $FreeBSDde: de-www/ports/growth/Makefile,v 1.1 2007/03/31 14:27:07 jkois Exp $
# basiert auf: 1.2
#

TOOLDIR=${.CURDIR}/../../../../share/tools/portsgrowth

all install clean:
	cd ${TOOLDIR}; \
		 ${MAKE} ${MAKEFLAGS} ${.TARGETS}

