# $FreeBSD$
# Original Revision: r51870

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.xml mailinglists.xml webresources.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
