# $FreeBSD$
# Original Revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.xml mailinglists.xml newsgroups.xml webresources.xml

#XMLDOCS+=	social::${XML_EVENTS_EVENTS}:

.include "${DOC_PREFIX}/share/mk/web.site.mk"
