# $FreeBSD: www/ja/community/Makefile,v 1.1 2010/05/03 14:13:07 ryusuke Exp $
# Original Revision: 1.2

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   irc.sgml mailinglists.sgml newsgroups.sgml webresources.sgml

#XMLDOCS+=	social::${XML_EVENTS_EVENTS}:

.include "${WEB_PREFIX}/share/mk/web.site.mk"
