=== The FreeBSD Russian Documentation Project

Links: +
link:https://docs.freebsd.org/ru/books/faq/[FAQ] URL: link:https://docs.freebsd.org/ru/books/faq/[] +
link:https://www.freebsd.org/ru/[Web] URL: link:https://www.freebsd.org/ru/[] +
link:https://github.com/freebsd-doc-ru/freebsd-doc/discussions[The FreeBSD Russian Documentation Project site] URL: link:https://github.com/freebsd-doc-ru/freebsd-doc/discussions[]

Contact: Andrey Zakhvatov <andy@FreeBSD.org> +
Contact: Vladlen Popolitov <vladlen@FreeBSD.org>

The FreeBSD Russian Documentation Project's current goal is to provide up-to-date Russian translations of the most important parts of the FreeBSD documentation (FAQ, Handbook, website content).
It is essential to support Russian-speaking users with high-quality official technical materials and to increase the adoption of the operating system worldwide.
We hope this initiative will gain support within the Russian-speaking FreeBSD community and lead to an increase in translated materials.

In September 2025, two committers were granted commit bits to write Russian-translated documentation into the FreeBSD documentation tree:

* mailto:andy@FreeBSD.org[Andrey Zakhvatov], co-mentors Sergio Carlavilla and Maxim Konovalov
* mailto:vladlen@FreeBSD.org[Vladlen Popolitov], mentor Maxim Konovalov

During the last quarter:

* 100% of the text has been translated in Weblate.
* 31 out of 47 documents have been updated to the latest version from link:https://docs.freebsd.org/ru/[docs.FreeBSD.org/ru], with the remaining documents currently under review and awaiting commit.

This report acknowledges with appreciation the contributions of the following colleagues who performed reviews of our commits during the quarter (in Phabricator or by email):

* mailto:arrowd@FreeBSD.org[Gleb Popov]
* mailto:bcr@FreeBSD.org[Benedict Reuschling]
* mailto:eugen@FreeBSD.org[Eugene Grosbein]
* mailto:maxim@FreeBSD.org[Maxim Konovalov]
* mailto:mizhka@FreeBSD.org[Michael Zhilin]

Plan for next quarter:

* Finalize the review and commit process for documentation (books and articles)
* Restore the Russian pages on www.FreeBSD.org
* Review the feasibility and the mechanics of the man pages translation

Check the https://docs.freebsd.org/ru/books/fdp-primer/translations/[official translation guide] if you would like to help.

We would appreciate your assistance with translating the following materials:

* Web pages
