=== GCC on FreeBSD

Links: +
link:https://gcc.gnu.org/[GCC Project] URL: link:https://gcc.gnu.org/[] +
link:https://gcc.gnu.org/gcc-13/[GCC 13 release series] URL: link:https://gcc.gnu.org/gcc-13/[] +
link:https://gcc.gnu.org/gcc-14/[GCC 14 release series] URL: link:https://gcc.gnu.org/gcc-14/[] +
link:https://gcc.gnu.org/gcc-15/[GCC 15 release series] URL: link:https://gcc.gnu.org/gcc-15/[] +
link:https://gcc.gnu.org/gcc-16/[GCC 16 release series] URL: link:https://gcc.gnu.org/gcc-16/[]

Contact: Lorenzo Salvadore <salvadore@FreeBSD.org>

The link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281091[exp-run to update GCC default version from 13 to 14] is almost done at the time this report is written: only one last PR stays open.
Hopefully, the update has been finally done when you are reading these lines.
However I remind you that the latest GCC major version is GCC 15, so we will still be behind one version.
Of course, another exp-run will be prepared to update GCC_DEFAULT to GCC 15, but not immediately.
I will wait some time to ensure that the GCC_DEFAULT=14 update has indeed worked as expected and to deal with some other issues related to the GCC ports.

Another important change concerns bootstrapping.
The GCC ports were in an inconsistent state: some ports required a bootstrap option to be chosen, while others did not.
Now all GCC ports allow building without any bootstrap option selected, just as it was in the past.

The problem is that building GCC on FreeBSD with FreeBSD's default compiler (clang) is not fully supported.
Since I know that many users do prefer to build GCC without bootstrapping it, instead of enforcing it as I initially planned, I prefer to maintain the option but remove from a no-bootstrap build all features that cannot be built successfully.
It shall be the users' responsibility to ensure that they do not need any feature incompatible with no-bootstrap builds.

At the moment, jit is the only feature that is excluded from a no-bootstrap build.
The default bootstrap option is STANDARD_BOOTSTRAP, so users of packages from official FreeBSD packages repositories will have a full build with all the supported features available.

See commits link:https://cgit.freebsd.org/ports/commit/?id=5ee63cc45413954077b2b0c0546b8342585b41ba[5ee63cc45413954077b2b0c0546b8342585b41ba], link:https://cgit.freebsd.org/ports/commit/?id=62f186cdf6e9689f30e854a0e23482c552c851a2[62f186cdf6e9689f30e854a0e23482c552c851a2] and link:https://lists.freebsd.org/archives/dev-commits-ports-main/2025-August/160223.html[this mail] for more details.
