=== Geomman Release

Links: +
link:https://gitlab.com/brauliorivas/geomman[geomman gitlab repo] URL: link:https://gitlab.com/brauliorivas/geomman[] +
link:https://www.freshports.org/sysutils/geomman[geomman port] URL: link:https://www.freshports.org/sysutils/geomman[]

Contact: Braulio Rivas <brauliorivas@FreeBSD.org>

Geomman is a partitioning tool (TUI) based on man:sade[8] that brings more functionality such as copying, pasting partitions, creating ext filesystems or encrypting partitions using man:geli[8].

Geomman is relevant for both newcomers and experienced users because it is a complete and unified management of partitions and disks.

Features added to geomman since last report are:

* Grow UFS, NTFS, ext2, ext3 and ext4 filesystems.
* Shrink NTFS, ext2, ext3 and ext4 filesystems.
* New partition dialog, where users can visually select a free space to place the partition to be pasted or moved, added to link:https://gitlab.com/alfix/bsddialog[bsddialog].
* Create exFAT, NTFS, ext2, ext3 and ext4 filesystems.
* Check all the mentioned filesystems.

Then, two GEOM-related features were added too:

* Label man:glabel[8] new partitions.
* Encrypt man:geli[8] new partitions by adding an optional "keyfile", plus a "passphrase" (or passfile).

Finally, with the help of mailto:fuz@FreeBSD.org[Robert Clausecker], we published the link:https://www.freshports.org/sysutils/geomman[geomman port] to let people try it out.

Future work includes:

* Add geomman to FreeBSD natively (userland)
* Add ZFS management

Sponsor: Google Summer of Code 2025
