=== FreeBSD Release Engineering Team

Links: +
link:https://www.freebsd.org/releases/15.0R/schedule/[FreeBSD 15.0-RELEASE schedule] URL: link:https://www.freebsd.org/releases/15.0R/schedule/[] +
link:https://download.freebsd.org/releases/ISO-IMAGES/[FreeBSD releases] URL: link:https://download.freebsd.org/releases/ISO-IMAGES/[] +
link:https://download.freebsd.org/snapshots/ISO-IMAGES/[FreeBSD development snapshots] URL: link:https://download.freebsd.org/snapshots/ISO-IMAGES/[]

Contact: FreeBSD Release Engineering Team, <re@FreeBSD.org>

The FreeBSD Release Engineering Team is responsible for setting and publishing release schedules for official project releases of FreeBSD, announcing code freezes and maintaining the respective branches, among other things.

The Team managed the first half of the 15.0-RELEASE cycle, aiming for the official RELEASE build and announcement in December.
Of note, this has involved a significant amount of pkgbase-related work landing.

The Release Engineering Team continued providing weekly development snapshot builds for the *main*, *stable/14*, and *stable/13* branches.
