=== A new Wi-Fi management utility: wutil

Links: +
link:https://github.com/MainKt/wutil[source code] URL: link:https://github.com/MainKt/wutil[] +
link:https://www.freshports.org/net/wutil[port] URL: link:https://www.freshports.org/net/wutil[]

Contact: Muhammad Saheed <saheed@FreeBSD.org> +

package:net/wutil[] is a Wi-Fi management utility that supports most man:wpa_supplicant[8] station-mode operations (scanning, connecting or disconnecting from wireless networks, and managing known networks, etc.), accessible with much nicer interfaces.
It also automatically manages and updates man:wpa_supplicant.conf[8].
SSIDs with Unicode characters are also handled nicely.

man:wutil[8] is the Command-Line Interface (CLI), whereas man:wutui[8] is the Terminal User Interface (TUI).
wutui was built without any dependency on TUI libraries, by just spell-casting ANSI escape sequences in uncooked terminal raw mode and a man:kqueue[2] based event loop.
Both utilities communicate with wpa_supplicant via its control socket interface.
There is also a dependency on package:net/libifconfig[] for interface related functions.

In the future, I plan to support AP-mode operations from man:hostapd[8], clean up the TUI components and perhaps move away from wpa_supplicant to handle authentication in-house.

wutil is now available in ports.
Give it a whirl!
Contributions, bug reports and feature requests are very welcome on GitHub.

Mentors: mailto:obiwac@FreeBSD.org[Aymeric Wibo] and mailto:getz@FreeBSD.org[Getz Mikalsen] +
Sponsor: Google Summer of Code 2025
