# $FreeBSD$

SUBDIR = faq
SUBDIR+= porters-handbook
SUBDIR+= ppp-primer

ROOT_SYMLINKS = faq porters-handbook ppp-primer

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
