#
# $FreeBSD$
# $FreeBSDru: frdp/doc/ru_RU.KOI8-R/books/Makefile,v 1.6 2001/07/25 10:33:31 phantom Exp $
#
# Original revision: 1.10

#SUBDIR = design-44bsd
SUBDIR = faq
SUBDIR+= handbook
SUBDIR+= porters-handbook
SUBDIR+= ppp-primer

ROOT_SYMLINKS = faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
