=== A bhyve management GUI written in Freepascal/Lazarus

Links: +
link:https://github.com/alonsobsd/bhyvemgr[Bhyvemgr] URL: link:https://github.com/alonsobsd/bhyvemgr/[] +

Contact: José Alonso Cárdenas Márquez <acm@FreeBSD.org>

Bhyvemgr is a bhyve management GUI written in Freepascal/Lazarus on FreeBSD.
It needs a bunch of tools mostly installed on base system and some installed from ports/packages.
The main goal is to be a desktop application focus on desktop user to easily and quickly setup and run virtual machines on FreeBSD hosts.

During this quarter, there were many bugfixes and improvements to Bhyvemgr.

These are some highlights that were added:

- Improve aarch64 support
- RDP Login form keeps data of resolution and username used on previous connection while bhyvemgr is running
- Support for selecting TCP remote connection at com1 of LPC device
- Fix zombie process bug when xfreerdp and remote-viewer are running from bhyvemgr.
  Now bhyvemgr uses Tthread instead of only TProcess for it
- VM name and com1 connection strings can be copied to clipboard from Virtual Machine popup menu
- Now xfreerdp3 loads arguments from rdp.args file
- Re-use device forms.
  It avoids to consume memory each time that device forms are opened/used
- Network device name can be added/modified manually from Network device form.
  Take on mind that valid names are tapX or vmnetX (e.g tap0, vmnet0)
- Log messages support

Bhyvemgr supports aarch64 only on 15-CURRENT and amd64 from FreeBSD 13.x to 15-CURRENT.
Also, bhyvemgr can be compiled or installed from link:https://www.freshports.org/sysutils/bhyvemgr[ports] or pkg binaries with gtk2, qt5 or qt6 interface support.

A big thank to link:https://www.entersekt.com/[Entersekt] for sponsor my work.
Now I can use a RockPro64 (aarch64) for testing bhyvemgr on aarch64.

People interested in helping or supporting the project are welcome.

Current version: 1.5.0

TODO

* Add uart device support

Sponsor: Entersekt
