=== Bugmeister Team

Links: +
link:https://wiki.freebsd.org/Bugzilla[FreeBSD Bugzilla] URL: link:https://wiki.freebsd.org/Bugzilla[]

Contact: Bugmeister <bugmeister@FreeBSD.org>

In this quarter we made major progress on Base System PRs, closing over 1,000 old ones that no longer apply.
Many of these were detected by carefully going over all entries in [.filename]#ObsoleteFiles.inc#.

Also in this quarter we came even closer to steady-state for ports/doc; we are dealing with incoming PRs more quickly these days.
For reference: link:https://bugs.freebsd.org/bugzilla/page.cgi?id=dashboard.html&days=90[].

The overall number of PRs came down from slightly over 11,000 to just under 10,000.
This was due to work from several people to go over entire groups of PRs.

Mark Linimon attended several video calls with various src committers.
They are doing some experimentation to learn what kind of effort is sustainable.
The most recent effort was to evaluate the latest incoming src PRs; you will note that many of them from the past few weeks have been marked as requesting feedback.

Bugmeister folks also did some passes through the database to clean up metadata:

- re-checked bugs for Product: Base System, Status: In Progress.
  A few of these were not being actively worked on.
  The count is essentially holding at 186.
  The concept is to make sure "In Progress" has some real meaning.

- edited up the 'application/mbox' patches to be 'text/plain', which Bugzilla is then able to understand.

- obsoleted many stale patches where more than one patch was in the PR.

The "automate harvesting PRs and evaluating whether they still apply" task has resulted in the release of link:https://github.com/linimon/patchQA[patchQA.py] as beta.
The program can take either a number (as a single PR number), or, with some work, a full REST query.

The main current problem is that the py-patch algorithm does not correctly handle fuzz.
Until this is fixed, it will stay in beta.

Almost all of the PRs with patches have been processed by patchQA.py and several hundreds of them have been rebased (e.g. Base System patches to be relative to the top of the src tree).
We now have a sense of how many Ports patches are not actually patches to the FreeBSD port itself, but instead need to be manually applied to an extracted work/ directory.
A script to try to automate this is in alpha.

The other problem known with patchQA.py is that it does not know the origins of files that are installed into /etc by installworld.

However, it does know enough to internally rebase Ports patches to the ports tree base if necessary.

We also created 120+ new Bugzilla accounts by user request.
(We no longer create them automatically because of the spammers.)

Clusteradm@ helped us fend off yet more crawler sites.
OTOH, we seem to be losing the war against AI bots.

See also: link:https://wiki.freebsd.org/Bugzilla/SearchQueries[]

