=== Framework Laptop support

Links: +
link:https://wiki.freebsd.org/Laptops/Framework_Laptop/[Framework Laptop page on FreeBSD Wiki] URL: https://wiki.freebsd.org/Laptops/Framework_Laptop/[] +
link:https://github.com/FrameworkComputer/freebsd-on-framework[Guide on installing and using FreeBSD on Framework systems] URL: https://github.com/FrameworkComputer/freebsd-on-framework[] +
link:https://bugs.freebsd.org/262152[Tracking ticket: Framework Laptop: Feature support, bugs and improvements] URL: https://bugs.freebsd.org/262152[]

Contact: Daniel Schaefer <dhs@frame.work> +
Contact: Li-Wen Hsu <lwhsu@FreeBSD.org> +
Contact: Sheng-Yi Hong <aokblast@FreeBSD.org>

For a long time, Framework Computer Inc. has been very supportive of the FreeBSD project in many ways, including providing engineering samples to the Foundation for testing and working on compatibility.

The Foundation continues to work on improving overall laptop support, and Framework laptops are one of the link:https://github.com/FreeBSDFoundation/proj-laptop/blob/main/supported/laptops.md[target platforms] for the link:https://github.com/FreeBSDFoundation/proj-laptop/[Laptop Support and Usability Project].

In March, some FreeBSD developers visited Framework's Taipei office again to test FreeBSD on pre-release Framework products, the Framework Desktop and Framework Laptop 12.
The results of these tests will be used to help shape FreeBSD's development plans, and the FreeBSD support status will be updated in document after further verification.

Sheng-Yi is using the laptop provided by Framework Computer to add more device support, e.g. https://reviews.freebsd.org/D49587[hwpstate: add CPPC support for pstate driver on AMD].

Sponsor: The FreeBSD Foundation for Li-Wen and Sheng-Yi's work +
Sponsor: Framework Computer Inc for Daniel's work, hardware and space support
