=== GCC on FreeBSD

Links: +
link:https://gcc.gnu.org/[GCC Project] URL: link:https://gcc.gnu.org/[] +
link:https://gcc.gnu.org/gcc-11/[GCC 11 release series] URL: link:https://gcc.gnu.org/gcc-11/[] +
link:https://gcc.gnu.org/gcc-12/[GCC 12 release series] URL: link:https://gcc.gnu.org/gcc-12/[] +
link:https://gcc.gnu.org/gcc-13/[GCC 13 release series] URL: link:https://gcc.gnu.org/gcc-13/[] +
link:https://gcc.gnu.org/gcc-14/[GCC 14 release series] URL: link:https://gcc.gnu.org/gcc-14/[]

Contact: Lorenzo Salvadore <salvadore@FreeBSD.org>

The link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281091[exp-run to update GCC default version from 13 to 14] has been suspended.
Indeed it has been noticed that FreeBSD 13.4 lacks symbols that are used by GCC 14 for linking, please see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=284499#c0 for a more detailed explanation.
The symbols are however already present in higher FreeBSD version.
Since FreeBSD 13.4 is expected to go out of support soon (on June 30th), it has been decided that it is preferable to suspend the exp-run until then.
I plan to put it back on track on July 1st.

In the meantime, work is being done on bugs.
Bugs link:https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276070[276070] and https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=284441[284441] have been fixed.
At the time this report is written, some bugs are being discussed addressing special values of the CPUTYPE variable, please see for example https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=285711[285711].
