# $FreeBSD$
# $FreeBSDde: de-www/developers/Makefile,v 1.1 2007/03/31 12:02:05 jkois Exp $
# basiert auf: 1.1

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   cvs.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
