# $FreeBSD$
# The FreeBSD Japanese Documentation Project
# Original revision: r54089

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	projects.xml
DOCS+=	newbies.xml
#DOCS+=	summerofcode.xml
#DOCS+=	summerofcode-2005.xml
#DOCS+=	summerofcode-2006.xml
#DOCS+=	summerofcode-2007.xml
#DOCS+=	summerofcode-2008.xml

#DATA=	2018-freebsd-gsoc-thumbnail.png
#DATA+=	2018-freebsd-gsoc.pdf

INDEXLINK= projects.html

SUBDIR=	mips

.include "${DOC_PREFIX}/share/mk/web.site.mk"
