---
description: 'Руководство по использованию товарных знаков в Документационном проекте FreeBSD'
next: books/fdp-primer/see-also
params:
  path: /books/fdp-primer/trademarks/
prev: books/fdp-primer/editor-config/
showBookMenu: true
tags: ["trademarks", "AsciiDoctor", "HTML"]
title: 'Глава 14. Товарные знаки'
weight: 14
---

[[trademarks]]
= Товарные знаки
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 14
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

Для всех документов в рамках проекта FreeBSD Documentation Project необходимо указывать зарегистрированные товарные знаки, а также принято указывать другие товарные знаки, и это является требованием для каждого автора и участника.

[[trademark-symbols]]
== Символы товарных знаков

Добавьте символ товарного знака ((TM), (R) или другой) к первому упоминанию зарегистрированного названия и всегда при использовании логотипов. Используйте extref:{fdp-primer}/writing-style/#writing-style-special-characters[эквивалентную ASCII-последовательность], которая будет отображаться как соответствующий символ Юникода. Также пишите зарегистрированное название в соответствии с его правилами использования товарного знака.

Если сомневаетесь, изучите сайт владельца товарного знака, сайт продукта и/или сайт link:https://www.uspto.gov/trademarks[Ведомства по патентам и товарным знакам США для поиска товарных знаков].

[[trademark-citing]]
== Цитирование товарных знаков

Проект документации FreeBSD предоставляет шаблон для указания товарных знаков, что также позволяет избежать их дублирования в документах.

Сначала найдите товарный знак в разделе link:https://cgit.freebsd.org/doc/tree/documentation/themes/beastie/i18n/en.toml#n328[Copyright в шаблоне проекта], затем добавьте его в тег `trademarks` в разделе `Front Matter` документа, который расположен в начале каждого документа.

Вот пример `Front Matter` из статьи extref:{contributing}[Вклад в FreeBSD]:

....
---
title: Contributing to FreeBSD
authors:
  - author: Jordan Hubbard
  - author: Sam Lawrance
  - author: Mark Linimon
description: How to contribute to the FreeBSD Project
trademarks: ["freebsd", "ieee", "general"]
weight: 15
tags: ["Contributing", "FreeBSD", "Non-Programmer Tasks", "Programmer Tasks"]
---
....

Товарные знаки `freebsd`, `ieee` и `general` будут автоматически отображаться при сборке документа следующим образом:

....
FreeBSD is a registered trademark of the FreeBSD Foundation.

IEEE, POSIX, and 802 are registered trademarks of Institute of Electrical and Electronics Engineers, Inc. in the United States.

Many of the designations used by manufacturers and sellers to distinguish their products are claimed as trademarks. Where those designations appear in this document, and the FreeBSD Project was aware of the trademark claim, the designations have been followed by the “™” or the “®” symbol.
....

Если товарный знак отсутствует в шаблоне проекта, его необходимо предоставить. Любой разработчик или участник может обновлять товарные знаки.

Теги товарных знаков `freebsd` и `general` обычно присутствуют во всех документах.
