---
title: "Проект FreeBSD GNOME: Как сообщить об ошибке"
sidenav: gnome
--- 

= Проект FreeBSD GNOME: Как сообщить об ошибке

== 1. О чём сообщать?

Руководствоваться нужно следующим: сообщайте максимальное количество информации. Даже если будет присутствовать какая-то избыточная информация, разработчики её просто отбросят. С другой стороны, гораздо хуже выглядит ситуация, когда для выявления или повторения ошибочной ситуации информации слишком мало - в этом случае разработчики будут терять время на то, чтобы попытаться угадать и/или выяснить подробности у того, кто сообщил о проблеме.

Есть достаточно примеров абсолютно бесполезных сообщений об ошибках, нечто вроде _"Эй, порт gnomefoo не работает. Я использую FreeBSD-X.Y. Исправьте, пожалуйста."_ Не нужно говорить, что такие сообщения являются просто потерей вашего времени, времени соответствующего разработчика и пропускной способности сети. Как минимум сообщение должно включать следующую информацию:

* Точная версия операционной системы (обычно выдаётся командой `uname -a`).
* Перечень всех пакаджей, установленных в вашей системе.
* Настройки вашего окружения (выдача команды `/usr/bin/env`).
* Если вы выполняете построение из портов, то примерное время, когда вы последний раз обновляли ваше дерево портов.
* Информация, специфичная для каждого типа неисправности: полный журнал неудачного построения в случае, когда построение порта окончилось неудачно, трассировка стека в случае выдачи аварийного дампа памяти, чёткое и подробное описание проблемы, если приложение выполняет какие-то неожиданные действия, и так далее. Попытайтесь поставить себя на место разработчиков и в каждом конкретном случае понять, какая информация будет им необходима для выяснения причин возникновения проблемы. Не думайте, что они уже всё знают о проблеме, и лишь ленятся её исправить.

Если у вас есть решение или способ обхода проблемы, то включите его в ваше сообщение, даже если вы не совсем уверены, что это решение является правильным. Даже если это всё же не так, предложенный вами способ может натолкнуть разработчика на мысли о том, где это нужно посмотреть; и это сэкономит ему время.

== 2. Куда сообщать?

Перед тем, как сообщать об ошибке или даже посылать письмо в список рассылки, http://www.freebsd.org/search/[выполните поиск] в архивах списка рассылки FreeBSD GNOME на предмет того, не сообщалось ли уже об этой проблеме ранее. Большинство проблем, о которых пишется в списке рассылки, повторяются, и при помощи поиска вы сможете найти решение гораздо быстрее.

Как только вы убедились, что это новая проблема, существует несколько способов сообщить об ошибке в GNOME под управлением FreeBSD: вы можете выслать сообщение в адрес mailto:freebsd-gnome@FreeBSD.org[списка рассылки freebsd-gnome], заполнить форму с сообщением в http://www.freebsd.org/support#gnats[системе отслеживания ошибок FreeBSD], послать своё сообщение конкретному разработчику GNOME через их http://bugzilla.gnome.org/[систему отслеживания ошибок] или воспользоваться любой комбинацией из этих способов.

Невозможно однозначно описать, куда следует направлять сообщение в каждом конкретном случае - вам нужно использовать соображения общего характера, однако вот некоторые правила, которым нужно следовать:

* Если проблема специфична для FreeBSD и имеет временный характер (к примеру, несовпадение контрольных сумм, ошибка при наложении патча, синтаксическая ошибка в файле Makefile порта и так далее), то сообщайте о ней в mailto:freebsd-gnome@FreeBSD.org[список рассылки freebsd-gnome].
* Если проблема однозначно не является специфичной для FreeBSD и у вас нет готового решения, то сообщите непосредственно разработчикам программного обеспечения (для большинства основных компонентов GNOME это означает, что вы должны воспользоваться их системой отслеживания проблем Bugzilla).
* Если проблема не является специфичной для FreeBSD, но достаточно серьёзной, и у вас есть исправления, то сообщите в обе системы отслеживания ошибок, как FreeBSD, так и автора, чтобы этот конкретный порт был исправлен и другие пользователи FreeBSD смогли использовать ваше исправление, без ожидания следующего релиза от разработчика.
