---
title: "Проект FreeBSD GNOME: Примерный Makefile для GNOME"
sidenav: gnome
--- 

include::shared/releases.adoc[]

= Проект FreeBSD GNOME: Примерный Makefile для GNOME

Далее приводится примерный Makefile для порта FreeBSD приложения GNOME.

....
# New ports collection makefile for:    gnomeapp
# Date created:                     27 December 2003
# Whom:                             Some GNOME User <freebsd-gnome@FreeBSD.org>
#
# $FreeBSD: head/ru_RU.KOI8-R/htdocs/gnome/docs/example-Makefile.xml 43181 2013-11-13 06:10:37Z hrs $
#

# For this example, assume there was already a gnomeapp in the tree, and that this
# is the GTK+-2 version (i.e. gnomeapp2 versus gnomeapp).
PORTname=       gnomeapp2
PORTVERSION=    {gnomever}.2
MASTER_SITES=   ${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR= sources/${PORTNAME:S/2//}/{gnomever}
DISTname=       ${PORTNAME:S/2//}-${PORTVERSION}
DIST_SUBDIR=    gnome2

MAINTAINER=     gnome@FreeBSD.org
COMMENT=        A GNOME app that does some stuff

USE_BZIP2=      yes
USE_X_PREFIX=   yes
USE_LIBTOOL=    yes # many GNOME apps need libtool, and most need GNU configure
USE_GMAKE=      yes # same with GNU make
# This is for i18n:
CONFIGURE_ENV+= CPPFLAGS="-I${LOCALBASE}/include" \
                LDFLAGS="-L${LOCALBASE}/lib"
USE_GNOME=      gnomehack gnometarget lthack gtk20

# This application can dock in the GNOME panel, or it can not.
# But there's no need to build support for it if the GNOME panel
# libraries are not installed, so only build GNOME panel support
# if the gnomepanel port is already installed.
WANT_GNOME=     yes

.include <bsd.port.pre.mk>

.if ${HAVE_GNOME:Mgnomepanel}!=""
USE_GNOME+=         gnomepanel
CONFIGURE_ARGS+=    --with-gnome
PKGNAMESUFFIX=      -gnome
.else
CONFIGURE_ARGS+=    --without-gnome
.endif

# Given all the above code, the package name is either "gnomeapp2-{gnomever}.2-gnome" or
# "gnomeapp2-{gnomever}.2", depending upon whether you want gnomepanel support. The downloaded
# distfile will be "gnomeapp-{gnomever}.2.tar.bz2."

.include <bsd.port.post.mk>
  
....
