---
title: "Проект FreeBSD GNOME: Известные проблемы с GNOME во FreeBSD"
sidenav: gnome
--- 

include::shared/releases.adoc[]

= Проект FreeBSD GNOME: Известные проблемы с GNOME во FreeBSD

Далее приведёт перечень известных проблем с GNOME {gnomever}, которые специфичны для FreeBSD. Однако это не все известные проблемы. Пожалуйста, ознакомьтесь с http://www.gnome.org/start/{gnomever}/notes/[замечаниями к релизу] GNOME {gnomever}, в которых помещён http://www.gnome.org/start/{gnomever}/notes/rnknownissues.html[список] известных проблем, встречающихся на всех платформах.

== 1. Обновление с GNOME 2.2 до {gnomever} выглядит непростым делом

Вы должны следовать http://www.freebsd.org/gnome/docs/faq2/#q5[указаниям] по обновлению до GNOME {gnomever}. Однако при этом могут возникать ошибки. Вам может понадобиться перезапускать `pkgdb -F` после каждого шага. Если вы всё ещё сталкиваетесь с ошибками после выполнения инструкций по обновлению, создайте протокол всего процесса обновления (для этого вы можете воспользоваться параметром `-l` утилиты `portupgrade`). *Заархивируйте* и пришлите протокол на адрес freebsd-gnome@FreeBSD.org.

== 2. В evolution есть проблемы с вложениями при работе с GNOME {gnomever}

В evolution-1.4.4 действительно есть проблема с вложениями при работе с GNOME {gnomever}. Для обхода этого выполните следующее, работая как пользователь root:

....
# ln -s /usr/X11R6/share/icons/gnome/48x48/apps/gnome-unknown.png /usr/X11R6/share/gnome/pixmaps/gnome-unknown.png
....

Эта проблема была исправлена в evolution-1.4.5, поэтому обновление до evolution-1.4.5, вероятно, будет лучшим решением.

== 3. gstreamer плохо проигрывает контент с rhythmbox

gstreamer-0.6.3 плохо работает с rhythmbox. Рекомендуется построение rhythmbox с параметром `-DWITH_XINE`. (*ОБНОВЛЕНИЕ:* Начиная с gstreamer-plugins-0.6.3_1, эта проблема была решена.)

== 4. Запуск GDM оканчивается неудачно

GDM может запускаться неудачно, особенно при работе в 5.1-RELEASE или более ранних версиях. Всем пользователям GDM нужно скопировать `/usr/X11R6/etc/gdm/factory-gdm.conf` поверх `/usr/X11R6/etc/gdm/gdm.conf`. Старые версии конфигурационного файла от GNOME 2.2 работать не будут. Пользователям 5.1-RELEASE и более ранних версий нужно прочесть файл `pkg-message`, поставляемый с портом/пакаджем GDM2, в котором описывается, как изменить OpenPAM для работы с GDM2.

== 5. Не удаётся построить gnomemeeting

Gnomemeeting может не строиться, если у вас установлен ffmepg. Если это так, удалите ffmpeg, а затем постройте gnomemeeting, после чего переустановите ffmpeg, если он вам нужен.
