# $Id: Makefile,v 1.9 1998-11-10 19:02:24 motoyuki Exp $
# The FreeBSD Japanese Documentation Project
# Original revision: 1.9

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif

# quick news letter
DOCS=	qnewsletter.sgml
DOCS+=	qnewsletter-1-1.sgml
DOCS+=	qnewsletter-1-2.sgml
DOCS+=	qnewsletter-1-3.sgml
DOCS+=	qnewsletter-1-4.sgml 
DOCS+=	qnewsletter-1-5.sgml
DOCS+=	qnewsletter-1-6.sgml

DOCS+=	press.sgml
DOCS+=  newsflash.sgml

DOCS+=	news.sgml

INDEXLINK= news.html

.include "../../web.mk"
