#
# The FreeBSD Russian Documentation Project
#
# $FreeBSD$
# $FreeBSDru: frdp/www/ru/projects/busdma/Makefile,v 1.1 2004/01/23 18:11:35 andy Exp $
#
# Original revision: 1.1
#

# Summary for busdma project status

MAINTAINER=	rwatson

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	index.xml
DATA=	style.css

.include "${DOC_PREFIX}/share/mk/web.site.mk"
