#
# Build the Handbook with just the content from this chapter.
#
# Original Revision: b4346b9b2d (r39631)
# $FreeBSD$
#

CHAPTERS= 	bsdinstall/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
